### ISSUE TITLE
Unable to install `gdb-mi` package

### ISSUE THREAD

**Issue by myrgy** [hlissner/doom-emacs#1003]
Hello,

Thanks for great tool!

### Observed behavior

`bin/doom refresh/update` doesn't install `gdb-mi` package.
I've tried to change package name to `gdb-mi1` - installation process has started. Seems like this cryptic behaviour is related with package name.

### Steps to reproduce

packages.el
```
(package! gdb-mi :recipe (:fetcher github
                                   :repo "weirdNox/emacs-gdb"))
;; :files ("*.el" "*.c" "*.h" "Makefile")))
```

config.el
```
(def-package! gdb-mi
  :init
  (fmakunbound 'gdb)
(fmakunbound 'gdb-enable-debug))
```

My config could be find here: https://github.com/myrgy/doom.d

### System information

- OS: gnu/linux (x86_64-redhat-linux-gnu)
- Emacs: 26.1 (Jun 26, 2018)
- Doom: 2.0.9 (develop 85ea30377f764f31760023ced36b9badf32c8a56)
- Graphic display: t (daemon: nil)
- System features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS XWIDGETS LCMS2
- Details:
  ```elisp
  elc count: 152
  uname -a:  Linux cm-adalshov 4.18.12-200.fc28.x86_64 #1 SMP Thu Oct 4 15:46:35 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
  modules:   (:feature eval (evil +everywhere) file-templates (lookup +docsets) snippets spellcheck (syntax-checker +childframe) workspaces :completion company (helm +fuzzy) :ui doom doom-dashboard doom-modeline doom-quit evil-goggles hl-todo nav-flash treemacs (popup +all +defaults) vc-gutter vi-tilde-fringe window-select :editor multiple-cursors rotate-text :emacs dired ediff electric eshell hideshow imenu vc :tools editorconfig make magit pdf :lang cc data emacs-lisp latex lua markdown (org +attach +babel +capture +export +present) (sh +fish) :config default :private lsp (ccls +rainbow) prj)
  packages:  n/a
  exec-path: (~/.opt/bin ~/.cargo/bin ~/.opt/bin /usr/lib64/qt-3.3/bin /usr/share/Modules/bin /usr/local/bin /usr/local/sbin /usr/bin /usr/sbin ~/.local/bin ~/bin /usr/libexec/emacs/26.1/x86_64-redhat-linux-gnu)
  ```

**Comment by hlissner** [comment]
Sorry for the tremendously late reply.

It seems that the problem is that gdb-mi is already included in Emacs, so Doom thinks it's already installed. To get around this you must use a different name for the package and provide the `:files` property:

```elisp
(package! gdb-mi-new :recipe
  (:fetcher github
   :repo "weirdNox/emacs-gdb"
   :files ("*.el" "*.c" "*.h" "Makefile")))
```

**Comment by myrgy** [comment]
HI @hlissner ,

unfortunately that solution doesn't work - emacs can't import module because file is still named as gdb-mi, while emacs expects gdb-mi-new.

any advice will be appreciated!

**Comment by myrgy** [comment]
manged to install

config.el
```
(fmakunbound 'gdb)
(fmakunbound 'gdb-enable-debug)
```

packages.el
```
(package! gdb-mi
  :recipe (:host github
           :repo "weirdNox/emacs-gdb"
           :files ("*.el" "*.c" "*.h" "Makefile")))
```
