### ISSUE TITLE
Warning on `doom-modeline-buffer-file`

### ISSUE THREAD

**Issue by qhuyduong** [hlissner/doom-emacs#1004]
### Observed behavior
```
Warning (bytecomp): value returned from (propertize "%b" (quote face) (quote doom-modeline-buffer-file)) is unused
```

### Expected behavior

Don't see the warning message

### Steps to reproduce

1. Pull latest code from develop branch
2. `make install`
3. Start Emacs

### System information

<details>
<summary>Click to expand</summary>

- OS: darwin (x86_64-apple-darwin14.5.0)
- Emacs: 26.1 (May 31, 2018)
- Doom: 2.0.9 (develop 85ea30377f764f31760023ced36b9badf32c8a56)
- Graphic display: t (daemon: nil)
- System features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS
- Details:
  ```elisp
  elc count: 0
  uname -a:  Darwin Huys-MacBook-Pro.local 18.2.0 Darwin Kernel Version 18.2.0: Fri Oct  5 19:41:49 PDT 2018; root:xnu-4903.221.2~2/RELEASE_X86_64 x86_64
  modules:   (:feature debugger eval (evil +everywhere) (lookup +docsets) snippets file-templates spellcheck (syntax-checker +childframe) workspaces :completion company helm :ui doom doom-dashboard doom-modeline doom-quit evil-goggles hl-todo modeline nav-flash neotree (popup +all +defaults) pretty-code vc-gutter vi-tilde-fringe window-select :editor format multiple-cursors rotate-text :emacs dired electric hideshow imenu vc :tools gist macos magit make tmux :lang data emacs-lisp javascript latex markdown (org +attach +babel +capture +export +present) (python +pyenv) ruby sh web :config default)
  packages:  (bundler (exec-path-from-shell :disable t))
  exec-path: (/usr/local/bin /usr/bin /bin /usr/sbin /sbin /Applications/Emacs.app/Contents/MacOS/bin-x86_64-10_10 /Applications/Emacs.app/Contents/MacOS/libexec-x86_64-10_10 /Applications/Emacs.app/Contents/MacOS/libexec /Applications/Emacs.app/Contents/MacOS/bin)
  ```
</details>

**Comment by qhuyduong** [comment]
False alarm. I used wrong configs! Thanks.

**Comment by shuxiao9058** [comment]
How do you fix this warning?

**Comment by qhuyduong** [comment]
@shuxiao9058 just remove `modeline` from your init.el file. That package seems to be obsolete. We had `doom-modeline` already.

**Comment by hlissner** [comment]
@qhuyduong It is the other way around. The ui/modeline module is the newer module, and will eventually replace ui/doom-modeline.

ui/modeline, however, uses features only available in Emacs 26+, so 25 users must use ui/doom-modeline.

In any case, it appears you had both modules enabled. You should have only one or the other.
