### ISSUE TITLE
Wiki Update for Customization#keep-my-customizations-in-version-control

### ISSUE THREAD

**Issue by afonsoduarte** [hlissner/doom-emacs#1007]
### Observed behavior
[Wiki's instructions](https://github.com/hlissner/doom-emacs/wiki/Customization#keep-my-customizations-in-version-control) to keep customizations in version control are outdated:

```elisp
;; in ~/.emacs.d/init.el
(doom! :private my-module)

;; in ~/.emacs.d/modules/private/my-module/init.el
(doom! ...)
```

### Expected behavior

As per issue #352 , it should read:

```elisp
;; ~/.emacs.d/init.el
(require 'core (concat user-emacs-directory "core/core"))
(require! :private my-module) ; replace with your module

;; modules/private/my-module/init.el
(doom! ...)
```

**Comment by hlissner** [comment]
I've updated the wiki and removed this section. Now that private modules have been moved (in `develop`) to `~/.doom.d` (or `~/.config/doom`), the user doesn't need to do anything extra to version-control their private config, so I'll consider this issue resolved.

Thanks for letting me know!
