### ISSUE TITLE
copy always invoked when do vanilla emacs paste on region

### ISSUE THREAD

**Issue by braineo** [hlissner/doom-emacs#1008]
Here are some things you should try before filing a bug report:

+ Run `make install` to ensure all plugins are installed.
+ `void-function` or `void-variable` errors could signal an out-of-date autoloads file. Run `make autoloads` or `M-x doom//reload-autoloads` to update it.
+ Scan for common OS/environment issues with `make doctor`.
+ Never debug byte-compiled code. It will interfere in subtle ways. Clean up \*.elc files with `make clean` or `M-x doom//clean-byte-compiled-files`.
+ Check [the FAQ](https://github.com/hlissner/doom-emacs/wiki/FAQ#troubleshooting) to see if your issue is mentioned.
+ Check the relevant module's README.org, if one exists. There may be extra steps to getting certain features to work.

If none of those help, remove this section and fill out the four sections in the template below.

---

### Observed behavior

Hi hlissner. I was play around your work and observe followings. Tried to figure out why and I felt it might be in `core` ?

Select a region, and yank. What is in the kill ring does not paste. Instead, it saves the active region to kill ring and paste!

### Expected behavior

Yank on a selected region paste directly.

### Steps to reproduce

1. Get a clean doom-emacs
2. `mkdir -p ~/.doom.d && touch ~/.doom.d/init.el
3. `echo "(delete-selection-mode 1)" > ~/.doom.d/init.el`
4. `cd ~/.emacs.d && make`
5. type `aaa`, `bbb` in scratch buffer
6. copy `aaa`, select `bbb`, then `yank` (`ctrl` + `y`) in this case
7. `bbb` get copied!

### System information

<details>
<summary>Click to expand</summary>

```
Emacs v26.1
Doom v2.0.9 (412063f4)
shell: /usr/local/bin/zsh
Compiled with:
  DBUS NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS LCMS2
Darwin Kernel Version 18.2.0
```
</details>

**Comment by hlissner** [comment]
I apologize for the late reply. The reason for this because doom sets `(setq select-enable-primary t)`, which forces copy/pasting to use a certain register. Try `(setq select-enable-primary nil)` and you should see the behavior you want.

**Comment by braineo** [comment]
Cool. Thanks!

**Comment by hlissner** [comment]
As of fbce94c I've pushed this fix into Doom. Thanks for bringing it to my attention!
