### ISSUE TITLE
No vi-style keymaps for Flycheck or Smerge

### ISSUE THREAD

**Issue by beojan** [hlissner/doom-emacs#1010]
Currently, Flycheck and Smerge only have Emacs-style (`CTRL-c`) key bindings, which are a bit of a pain to use.

**Comment by hlissner** [comment]
What keybinds are you referring to? Flycheck has a number of evilified keybinds, like `]e` and `[e` for navigating errors and `SPC c x` or `:er[rors]` ex command to open the error list (`flycheck-list-errors`).

There are also flycheck-error-list-mode keybinds provided by evil-collection:

```elisp
(evil-collection-define-key 'normal 'flycheck-error-list-mode-map
    "gj" 'flycheck-error-list-next-error
    "gk" 'flycheck-error-list-previous-error
    (kbd "C-j") 'flycheck-error-list-next-error
    (kbd "C-k") 'flycheck-error-list-previous-error
    "]" 'flycheck-error-list-next-error
    "[" 'flycheck-error-list-previous-error
    "gr" 'flycheck-error-list-check-source
    "s" 'flycheck-error-list-set-filter
    "S" 'flycheck-error-list-reset-filter
    "x" 'flycheck-error-list-explain-error
    (kbd "<return>") 'flycheck-error-list-goto-error
    "q" 'quit-window)
```

However, there aren't any smerge keybinds that I know of. Could you offer suggestions for them?

**Comment by beojan** [comment]
For flycheck, I have 
```lisp
        (:prefix-map ("C" . "Flycheck")
          :desc "Describe checker"          "?" #'flycheck-describe-checker
          :desc "Clear"                     "C" #'flycheck-clear
          :desc "Show error"                "h" #'flycheck-display-error-at-point
          :desc "Version"                   "V" #'flycheck-version
          :desc "Check buffer"              "c" #'flycheck-buffer
          :desc "Explain error"             "e" #'flycheck-explain-error-at-point
          :desc "Manual"                    "i" #'flycheck-manual
          :desc "List errors"               "l" #'flycheck-list-errors
          :desc "Next error"                "[" #'flycheck-next-error
          :desc "Previous error"            "]" #'flycheck-previous-error
          :desc "Select checker"            "s" #'flycheck-select-checker
          :desc "Verify setup"              "v" #'flycheck-verify-setup
          :desc "Disable checker"           "x" #'flycheck-disable-checker
          :desc "Compile"                   "b" #'flycheck-compile
          :desc "Copy error"                "w" #'flycheck-copy-errors-as-kill)
```

Under the `c` (code) binding.

Personally, I've switched to ediff for resolving git conflicts, so I don't need smerge bindings anymore (what I found confusing about ediff before is that when you're done you have to quit the session without saving anything, and magit automatically picks up the changes made).

**Comment by webframp** [comment]
The only smerge binding I know of comes from #2512 and is only active if you also use hydra. Current evil flycheck bindings work fine for me though, `]e` and `[e` mainly.

I would love to see some more discoverable smerge bindings, `C-c ^` is a little annoying to use.
