### ISSUE TITLE
Typo in wiki

### ISSUE THREAD

**Issue by Silex** [hlissner/doom-emacs#1013]
Seems like there is no public wiki edits, so:

https://github.com/hlissner/doom-emacs/wiki/Modules

```
These are not loaded automatically. Use load! to do so.

;; from modules/feature/version-control/config.el
(load +git)
```

This should probably be `(load! '+git)` (exclam and quote missing)

**Comment by UndeadKernel** [comment]
@Silex, it should actually be 
```lisp
(load! "+git")
```
The syntax of `load!` changed not too long and needs a string rather than a symbol.

**Comment by hlissner** [comment]
This has been corrected. Thanks for letting me know!
