### ISSUE TITLE
Disable ivy-rich or make it an option

### ISSUE THREAD

**Issue by jbharat** [hlissner/doom-emacs#1015]
Ivy-rich is very slow when scrolling through open buffers. Is there a way to disable it?

I have tried this in my private package.el
```
(package! ivy-rich :ignore t)
```
But this does not seem to work

**Comment by hlissner** [comment]
It should be `:disable t`, not `:ignore t`. 

```elisp
(package! ivy-rich :disable t)
```

`:ignore` simply instructs the package manager not to deal with it, whether or not it is installed or not.

**Comment by jbharat** [comment]
Ivy-rich is disabled now. I am not sure how its working 😅. It is having the exact same code as mentioned above. I am guessing that SPC h R does not disable ivy-rich. Restarted emacs and ivy-rich is not shown now.

**Comment by jbharat** [comment]
We can close this. `(package! ivy-rich :disable t)` disables ivy-rich.
