### ISSUE TITLE
ivy does not work after session restore

### ISSUE THREAD

**Issue by ppwwyyxx** [hlissner/doom-emacs#1017]
### Observed behavior
1. Load a session with `+workspace/load-session`.
2. Anything that uses ivy (e.g., `M-x`) will only show this window:
![1116-14 59 49](https://user-images.githubusercontent.com/1381301/48651667-cb5a2a80-e9b0-11e8-9c2c-4571e375baa8.png)

i.e., no content was shown in the ivy childframe.

### Expected behavior

ivy works the same

### System information

<details>
<summary>Click to expand</summary>

- OS: gnu/linux (x86_64-pc-linux-gnu)
- Emacs: 27.0.50 (Jun 14, 2018)
- Doom: 2.0.9 (develop 6971bbdf9c9ec3c58abcd477d937ba4ac177d387)
- Graphic display: t (daemon: nil)
- System features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS NOTIFY ACL GNUTLS LIBXML2 FREETYPE LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LIBSYSTEMD JSON LCMS2
- Details:
  ```elisp
  elc count: 28
  uname -a:  Linux hawaii 4.19.1-arch1-1-ARCH #1 SMP PREEMPT Sun Nov 4 16:49:26 UTC 2018 x86_64 GNU/Linux
  modules:   (:feature evil debugger eval file-templates (lookup +docsets) snippets spellcheck syntax-checker workspaces :completion company (ivy +childframe) :ui doom modeline evil-goggles fci hl-todo nav-flash neotree pretty-code (popup +all +defaults) unicode vi-tilde-fringe vc-gutter window-select :editor rotate-text multiple-cursors :emacs dired electric eshell hideshow imenu term ediff vc :tools editorconfig make magit password-store prodigy pdf rgb tmux wakatime docker :lang assembly cc data emacs-lisp ess go (haskell +intero) (java +meghanada) javascript latex lua markdown (org +attach +babel +capture +export +present +publish) (python +conda +ipython) ruby sh web :collab impatient-mode :config default)
  packages:  n/a
  exec-path: (~/bin /usr/local/bin /usr/local/sbin /usr/bin /opt/facebook/bin /opt/facebook/ops/scripts/chef /opt/cuda/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /usr/local/bin /usr/bin /bin /usr/local/sbin /usr/sbin /sbin ~/.local/bin /usr/lib/emacs/27.0.50/x86_64-pc-linux-gnu)
  ```
</details>

**Comment by hlissner** [comment]
Sorry for the late response. Are you still experiencing this issue on the latest Doom?

**Comment by bricewge** [comment]
Not the author here but I have the same issue. Updating to 99904c0e doesn't solve it however instead of the scratch buffer being displayed in the childframe it is the doom dashboard.

**Comment by hlissner** [comment]
As of cf07bac this should be resolved. Thanks for letting me know! Please update and let me know if that isn't the case and I will reopen this.

**Comment by bricewge** [comment]
Yes it's resolved for me. Thanks for the quick fix!
