### ISSUE TITLE
wrong new line indent when edit rust code

### ISSUE THREAD

**Issue by laishulu** [hlissner/doom-emacs#1019]
### Observed behavior

When edit rust codes and type`O` or `o` to open a new line in evil mode,
if the orginal indent is 4, the new line will only indent 2
I notice that `tab-width=2` and then `evel-shift-width=2`, `rust-indent-offset=2`.

I find its modified from 4 to 2 by `editorconfig`, but I am sure I have no any `.editorconfig` file anywhere in my environment.
![default](https://user-images.githubusercontent.com/1224321/48686903-8f65d600-ebf9-11e8-9574-48e17e53e192.png)

Also I can see there is a defult value in official editorconfig repo:

![default](https://user-images.githubusercontent.com/1224321/48686996-0a2ef100-ebfa-11e8-920c-48059a56a372.png)

### Expected behavior

should indent 4

### Steps to reproduce

1. open source code

```
pub fn foo() {
    None
}
```
2. when cursor in the line with `None` and evil mode and rust mode enabled.
3. type `O` or `o` to insert a new line.
4. the new line will indent 2

### System information

<details>
<summary>Click to expand</summary>

- OS: darwin (x86_64-apple-darwin14.5.0)
- Emacs: 26.1 (May 31, 2018)
- Doom: 2.0.9 (develop abc7ca84d8719487113581111079a60ef6588c43)
- Graphic display: nil (daemon: nil)
- System features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS
- Details:

  ```elisp
  elc count: 0
  uname -a:  Darwin mao 18.2.0 Darwin Kernel Version 18.2.0: Fri Oct  5 19:41:49 PDT 2018; root:xnu-4903.221.2~2/RELEASE_X86_64 x86_64 i386 MacBookPro10,1 Darwin
  modules:   (:feature eval (evil +everywhere) file-templates (lookup +docsets) snippets spellcheck syntax-checker workspaces :completion company helm :ui deft doom doom-modeline doom-quit evil-goggles hl-todo nav-flash treemacs (popup +all +defaults) pretty-code unicode vc-gutter vi-tilde-fringe window-select :editor format multiple-cursors rotate-text :emacs dired ediff electric eshell hideshow imenu term vc :tools editorconfig make magit :lang data emacs-lisp (haskell +intero) markdown (org +attach +babel +capture +export +present) python rust (sh +fish) :config default)
  packages:  (evil-textobj-column evil-textobj-entire evil-textobj-line evil-textobj-syntax (mark-fill-column :recipe (mark-fill-column :fetcher gitlab :repo chw-pub/mark-fill-column)) s (tmux-pane :recipe (tmux-pane :fetcher gitlab :repo chw-pub/emacs-tmux-pane)))
  exec-path: (~/bin ~/.local/bin ~/.cargo/bin /usr/local/opt/python/libexec/bin /usr/local/opt/coreutils/libexec/gnubin /usr/local/bin /usr/local/sbin /usr/bin /bin /usr/sbin /sbin /Applications/VMware Fusion.app/Contents/Public /Library/TeX/texbin /usr/local/MacGPG2/bin /opt/X11/bin /Applications/Emacs.app/Contents/MacOS/bin-x86_64-10_10 /Applications/Emacs.app/Contents/MacOS/libexec-x86_64-10_10 /Applications/Emacs.app/Contents/MacOS/libexec /Applications/Emacs.app/Contents/MacOS/bin)
  ```
</details>

**Comment by hlissner** [comment]
Editorconfig should not set any defaults in the absence of an .editorconfig file somewhere, so there must be one somewhere on your system.

Try `M-x editorconfig-find-current-editorconfig` to see if Emacs can find what editorconfig file is causing this.

**Comment by laishulu** [comment]
@hlissner 

Thanks. found ~/.editorconfig, maybe generated by other editors.
