### ISSUE TITLE
+python/open-ipython-repl errors

### ISSUE THREAD

**Issue by liujoey** [hlissner/doom-emacs#1022]
When I call +python/open-ipython-repl function, I got a lot errors related to matplotlib. I'm not using matplot in my project.

So the question is, should we add `--pylab` args to the ipython repl? I feel ipython is a very general tool but not necessarily that everyone want to use matplotlib.

**Comment by hlissner** [comment]
I've removed `--pylab` by default, and added variables for users to customize, if desired. This should resolve your issue. Let me know if that isn't the case.
