### ISSUE TITLE
goto definition work abnormal after I updated the repo to the commit 9337c3f

### ISSUE THREAD

**Issue by ustcpxy** [hlissner/doom-emacs#1023]
### Observed behavior

after update the repo to the commit https://github.com/hlissner/doom-emacs/commit/9337c3f8c367964e28e09ad74e02425fd75e7d15, the +lookup/definition work abnormal. 
when there are many candidate showed in *helm-xref", and then I pick one but it is not displayed on the current window. 

### Expected behavior

the selected buffer should be displayed on the current window.

### Steps to reproduce

1. use a c++ project as example, and use xref-find-definitions as backend, helm-xref also enabled.
2. call +looup/definition at a symbol

### System information

<details>
<summary>Click to expand</summary>

```
- OS: gnu/linux (x86_64-pc-linux-gnu)
- Emacs: 26.1 (Nov 21, 2018)
- Doom: 2.0.9 (develop abc7ca84d8719487113581111079a60ef6588c43)
- Graphic display: t (daemon: nil)
- System features: JPEG PNG SOUND GSETTINGS NOTIFY ACL LIBXML2 FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK2 X11 THREADS
- Details:
  ```elisp
  elc count: 0
  uname -a:  Linux szxw 4.17.0-3-amd64 #1 SMP Debian 4.17.17-1 (2018-08-18) x86_64 GNU/Linux
  modules:   (:feature eval (evil +everywhere) file-templates (lookup +docsets) snippets spellcheck (syntax-checker +childframe) :completion company (helm +fuzzy) :ui doom doom-modeline evil-goggles hl-todo nav-flash (popup +all +defaults) vc-gutter vi-tilde-fringe window-select :editor multiple-cursors rotate-text :emacs dired ediff electric hideshow imenu vc :tools editorconfig magit :lang assembly (cc +irony +rtags) data emacs-lisp ess (java +meghanada) javascript latex ledger lua markdown (org +attach +babel +capture +export +present) perl php plantuml python rest ruby sh web :config default :private chinese org)
  packages:  (cal-china-x cnfonts fcitx gxref org-brain ox-hugo pinyinlib winum youdao-dictionary)
  exec-path: (~/projects/bin ~/.nvm/versions/node/v8.1.3/bin /usr/local/bin /usr/bin /bin /usr/local/games /usr/games /usr/local/libexec/emacs/26.1/x86_64-pc-linux-gnu)
  ```

```
</details>

**Comment by scturtle** [comment]
Same to me. Jump to the wrong line in the current file. The original `+lookup--jump-to` works correctly. So it seems to be a problem with `save-window-excursion`.

**Comment by hlissner** [comment]
I suspect it has to do with asynchronous goto-definition handlers, which `+lookup/definition` doesn't support yet. I'll look into this soon.

**Comment by chengyi** [comment]
> I suspect it has to do with asynchronous goto-definition handlers, which `+lookup/definition` doesn't support yet. I'll look into this soon.

after I remove the `save-window-excursion`, it works again.

**Comment by hlissner** [comment]
Are you still experiencing this issue? There have been a number of changes made recently to the feature/lookup module that I'd hope have addressed this issue, among others.

**Comment by scturtle** [comment]
It seems to be resolved.

**Comment by ustcpxy** [comment]
yes, it has been fixed. Thanks.
