### ISSUE TITLE
+cc/reload-compile-db, Make the complile database path configurable

### ISSUE THREAD

**Issue by svnwell** [hlissner/doom-emacs#1028]
Doom-emacs is great, thank you very much for your masterpiece, but I am having a small problem during use. The complile database path is fixed to the project root directory in the +cc/reload-compile-db function, but I am used to putting compile-related files in the build subdirectory, so can you set the compile database path to be configurable? Thank you.

``` lisp
;;;###autoload
(defun +cc/reload-compile-db ()
  "Reload the current project's JSON compilation database."
  (interactive)
  (unless (memq major-mode '(c-mode c++-mode objc-mode))
    (user-error "Not a C/C++/ObjC buffer"))
  (unless (project-file-exists-p! "compile_commands.json")
    (user-error "No compile_commands.json file"))
  ;; first rtag
  (when (and (featurep 'rtags)
             rtags-enabled
             (executable-find "rc"))
    (with-temp-buffer
      (message "Reloaded compile commands for rtags daemon")
      (rtags-call-rc :silent t "-J" (or (doom-project-root) default-directory))))
  ;; then irony
  (when (and (featurep 'irony) irony-mode)
    (+cc|irony-init-compile-options)))
```

**Comment by hlissner** [comment]
I've removed the cdb file check. Since irony preforms its own file checks, it is unnecessary. This should fix your issue. Let me know if that isn't the case.

Thanks for letting me know!
