### ISSUE TITLE
Make eshell/grep windows vertical.

### ISSUE THREAD

**Issue by deech** [hlissner/doom-emacs#1046]
This is not a bug but more something I couldn't find in the docs. When I run `M-x eshell` it shows up at the bottom of the screen but I can't seem to move it anywhere after that. For example doing `SPC w L` which normally moves a buffer to the far right of the screen does nothing in this case. The same for `grep` windows. Is there something I'm missing?

**Comment by hlissner** [comment]
The emacs/eshell module provides these methods for invoking eshell:

| Command | Default keybind | Description |
|------------|------------------|--------------|
| `+eshell/open` | <kbd>SPC o e</kbd> | Opens eshell in the current window |
| `+eshell/open-popup` | <kbd>SPC o E</kbd> | Opens eshell in a popup at the bottom |
| `+eshell/open-fullscreen` | no default keybind |

There's also the `+popup/raise` command, which "promotes" a popup into a normal window. Once it is a normal window, it can be moved by `SPC w L`.

(fyi, using `M-x eshell` is (almost) equivalent to using `+eshell/open-popup`)

If you'd like to change where `+eshell/open-popup` places the popup, you can create a rule for it in your private config, for example:

```elisp
(set-popup-rule! "^\\*doom eshell" :side 'right :size 0.4)
```

Hope that helps!

**Comment by deech** [comment]
Yes it does! Thanks for the comprehensive answer.
