### ISSUE TITLE
MacOS Crashes with Patched Emacs Executable

### ISSUE THREAD

**Issue by Hindol** [hlissner/doom-emacs#1048]
### Observed behavior

MacOS crashes after Emacs.app is patched. Happens with `fish-shell` and when the `oh-my-fish` emacs plugin is used to start emacs.

### Expected behavior

Expect emacs to start normally.

### Steps to reproduce

1. Switch to `develop` branch of doom emacs.

        $ cd ~/.emacs.d
        $ git checkout develop
        $ make quickstart

2. When asked about patching Emacs.app, say yes.
3. With fish as default shell, and with [emacs plugin](https://github.com/oh-my-fish/plugin-emacs) for omf installed, start emacs.

        $ e

MacOS will hang and then crash.

### System information

<details>
<summary>Click to expand</summary>

```
Doom Doctor
Emacs v26.1
Doom v2.0.9 (a89a2aa7)
shell: /usr/local/bin/fish
Compiled with:
  NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS
uname -a:
  Darwin Hindols-Mac-Pro.guest.corp.microsoft.com 18.2.0 Darwin Kernel Version
  18.2.0: Fri Oct 5 19:41:49 PDT 2018; root:xnu-4903.221.2~2/RELEASE_X86_64 x86_64

Checking your OS...
Checking your fonts...
Checking gnutls/openssl...
Testing your root certificates...
Checking for GNU/BSD tar...
Warning: BSD tar detected
  QUELPA (through package-build) uses the system tar to build plugins, but it
  expects GNU tar. BSD tar *could* cause errors during package installation or
  updating from non-ELPA sources.  MacOS users can install gnu-tar via homebrew:
  brew install gnu-tar
Checking your enabled modules...
Loading /Users/hiadhy/.emacs.d/core/autoload/cache.el (source)...
  > (:tools editorconfig) Couldn’t find the editorconfig binary.
    Using native elisp version (slower)
  > (:lang cc) Couldn’t find the rtag client and/or server programs
    (rdm rc). Disabling rtags support
  > (:lang cc) Irony server isn’t installed. Run M-x
    irony-install-server
  > (:lang cc) Couldn’t find glslangValidator. GLSL code completion
    is disabled


There are 5 warnings!
```
</details>

**Comment by hlissner** [comment]
Please try the following commands, line by line, in your terminal, and report any errors/warnings you receive. You'll need to adjust paths if they aren't correct.

```sh
# does the wrapper work?
/Applications/Emacs.app/Contents/MacOS/Emacs

# does the original executable work?
/Applications/Emacs.app/Contents/MacOS/RunEmacs  

# does running Emacs from fish work?
$(which fish) -l -c /Applications/Emacs.app/Contents/MacOS/RunEmacs

# does running Emacs from fish, in a bash shell work?
/bin/bash -l -c "$(which fish) -i -c /Applications/Emacs.app/Contents/MacOS/RunEmacs"
```

The above needs to be done while the patch is in effect.

Otherwise, you should avoid the Emacs.app patch, as it hasn't been fully tested with shells besides bash and zsh. You can undo it by running `~/.emacs.d/bin/doom patch-macos --undo`.

**Comment by Hindol** [comment]
Hi @hlissner,

In *fish*, `$(which fish)`  becomes `(which fish)` (without the **$**). All 4 commands work correctly.

Modified 3rd command,

    (which fish) -l -c /Applications/Emacs.app/Contents/MacOS/RunEmacs

Modified 4th command,

    /bin/bash -l -c "\$(which fish) -l -c /Applications/Emacs.app/Contents/MacOS/RunEmacs"

Please let me know if you need anything else. Thanks for the cool project by the way, :)

**Comment by hlissner** [comment]
I have recently added a better alternative to `patch-macos`, and that is `doom env refresh`. Could you try unpatching and using this new method?

```sh
doom patch-macos --undo
doom env refresh
```

If it doesn't work for you, you can reverse the env file with `doom env clear`

**Comment by Hindol** [comment]
Unfortunately I have switched to a new team which uses Windows. I no longer have access to a Mac, sorry, :( Maybe someone else can try and report.

**Comment by hlissner** [comment]
Understood. I'll close this for now under the assumption it has been resolved. Feel free to follow up if you find yourself fighting this on mac again.
