### ISSUE TITLE
bug: map! will override the existing leader key bindings

### ISSUE THREAD

**Issue by PoiScript** [hlissner/doom-emacs#1062]
### Observed behavior

For example, adding
```emacs-lisp
(map!
 :leader
 :prefix ("f" . "file")
 :desc "find file"           "f" #'projectile-find-file)
```
to the config file will remove the existed [shortcuts](https://github.com/hlissner/doom-emacs/blob/70a4db49d12f6ffa4f87a1feb4b55330b1410418/modules/config/default/%2Bevil-bindings.el#L564-L580) starts with `<leader> f` defined by doom emacs itself.

### Expected behavior

The keybindings is extended rather than overridden. 

### Steps to reproduce

1. Adding the snippet mentioned above to the config file
2. All `<leader> f` shortcuts (such as `<leader> f .`) is gone, but `<leader> f f`.

### System information

<details>
<summary>Click to expand</summary>

- OS: gnu/linux (x86_64-pc-linux-gnu)
- Emacs: 26.1 (Jul 05, 2018)
- Doom: 2.0.9 (develop 70a4db49d12f6ffa4f87a1feb4b55330b1410418)
- Graphic display: t (daemon: nil)
- System features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LIBSYSTEMD LCMS2
- Details:
  ```elisp
  elc count: 0
  uname -a:  Linux yuudachi-laptop 4.19.11-arch1-1-ARCH #1 SMP PREEMPT Thu Dec 20 03:40:28 UTC 2018 x86_64 GNU/Linux
  modules:   (:feature eval (evil +everywhere) file-templates spellcheck (syntax-checker +childframe) :completion company (ivy +fuzzy) :ui doom doom-dashboard doom-modeline evil-goggles fci hl-todo neotree (popup +all +defaults) vc-gutter vi-tilde-fringe window-select :editor multiple-cursors rotate-text :emacs dired ediff electric hideshow imenu :tools editorconfig magit :lang data emacs-lisp javascript latex (org +capture) rust (sh +fish) web :app rss :config literate (default +bindings +snippets))
  packages:  (cargo cdlatex company-lsp fcitx lsp-mode lsp-ui memory-usage tiny)
  exec-path: (~/.cargo/bin/ ~/.local/bin/ ~/.yarn/bin/ ~/go/bin/ /usr/local/sbin /usr/local/bin /usr/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /usr/lib/emacs/26.1/x86_64-pc-linux-gnu)
  ```
</details>

**Comment by fuxialexander** [comment]
This is the normal behavior as which-key will reinit the prefix group. To add keybinds to a prefix group, use
```lisp
(map!
 :leader
 :prefix "f"
 :desc "find file"           "f" #'projectile-find-file)
```

**Comment by PoiScript** [comment]
@fuxialexander thanks, this problem had confused me for a long time cause I thought it's regarding to general.el.
