### ISSUE TITLE
+ivy-rich-buffer-name is not customizable

### ISSUE THREAD

**Issue by yshui** [hlissner/doom-emacs#1065]
+ivy-rich-buffer-name re-uses `font-lock-comment-face` and `font-lock-doc-face` which have existing established meanings. Meaning I cannot customize then without affecting how other texts are displayed.

Maybe it's better to create specific faces for them.

**Comment by hlissner** [comment]
Sorry for the late response: `+ivy-rich-buffer-name` no longer distinguishes buffers that aren't in the same project, but it still dims those that are considered unreal with `font-lock-comment-face`. As of 00bb006 this is customizable with the `+ivy-buffer-unreal-face` variable, so I'll consider this resolved.

Thanks for bringing this to my attention.
