### ISSUE TITLE
mode request: Cucumber

### ISSUE THREAD

**Issue by idoo** [hlissner/doom-emacs#1067]
Hello, what do you think if we will add https://github.com/lazyatom/cucumber.el as an option to `init.el` ?

**Comment by hlissner** [comment]
Sorry for the very late reply. Since Cucumber and its ilk are language agnostic (and I'm unfamiliar with it), I'm uncertain where cucumber would fit in. I'll consider a PR, but if it requires no substantial configuration, I'd rather it be left to users to install themselves.
