### ISSUE TITLE
Hybrid evil and emacs keybindings?

### ISSUE THREAD

**Issue by cthachuk** [hlissner/doom-emacs#107]
This is just a query, probably more so regarding evil-mode than doom, in case anyone has suggestions.

Being a long time emacs user, I've enjoyed learning vim style modal editing using spacemacs because of the 'hybrid-mode' keybinding option which maintains emacs keybindings while in insert mode.  I find I am not yet proficient enough to do away with emacs bindings altogether, but don't want to give up evil mode either.  Is this a behavior that I can replicate in doom?  I wasn't sure if this feature comes out of the box with evil, and I just need to learn to configure it, or if spacemacs has added a lot of customization to make this possible.

Thanks for any suggestions.

**Comment by aminb** [comment]
I believe [this](https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.org#hybrid) is what @cthachuk is referring to. If you scroll down a bit, in the [States](https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.org#states) section, they mention that the hybrid state is "exclusive to spacemacs". But I do agree that it's a nice-to-have, and I could see myself using it.

**Comment by hlissner** [comment]
That's a tough one. I'm not against it -- in fact, I'd like to implement it -- however, my background is with vim and I've used evil my entire Emacs "career"; I simply don't know the vanilla keybindings (as far as editing is concerned, at least). That said, it's not a lot of code to lift from spacemacs. 

Give me some time to study it (and vanilla Emacs) and I'll get back to you.

**Comment by casouri** [comment]
We can just start with some simple mapping’s like 
* forward char
* back char
* previous line
* next line
* beginning of line
* end of line

These are the only ones I found myself using in hybrid mode

**Comment by fuxialexander** [comment]
@casouri I think that's already implemented. At least `C-a` `C-e` `C-f` `C-b` works.

**Comment by fintelkai** [comment]
`evil` actually has a setting that results in pretty much a hybrid state in insert state:

```
(use-package evil
  :custom
  evil-disable-insert-state-bindings t
  )
```

This worked for me when I moved from spacemacs to vanilla, and it works in doom as well.

**Comment by Shiandow** [comment]
Using `evil-disable-insert-state-bindings` got me most of the way there, but the evil 'omni completion' keybindings shadow a couple of important C-x keybindings. Most annoyingly C-x C-s, which no longer saves the file. Perhaps that prefix could be made configurable?

**Comment by kngtani** [comment]
I think C-z can get you to switch between emacs and evil state.
Similarly, I came across this setting that convinced me to migrate from spacemacs hybrid mode to doom.
```
(defalias 'evil-insert-state 'evil-emacs-state)
(define-key evil-emacs-state-map (kbd "<escape>") 'evil-normal-state)

```
I really appreciate the minimal UI and fast performance on doom.

**Comment by cthachuk** [comment]
Thanks everyone for comments, alternatives, workarounds, and solutions.
