### ISSUE TITLE
solaire mode is not enabled for the initial buffer

### ISSUE THREAD

**Issue by yshui** [hlissner/doom-emacs#1070]
### Observed behavior

When opening a file with command line argument (I.e. `emacs asdf`), solaire mode is not enabled in that buffer.

### Expected behavior

Solaire mode is enabled for all file buffers

**Comment by hlissner** [comment]
I've pushed an update for [solaire-mode](https://github.com/hlissner/emacs-solaire-mode). Please update both Doom (`bin/doom upgrade`) and your packages (`bin/doom update`), and that should resolve your issue! Let me know if that isn't the case.

**Comment by yshui** [comment]
@hlissner This fixed the problem for usual emacs invocation. But if I use a emacs daemon, then solaire mode is not enabled in client frames.
