### ISSUE TITLE
Remapping doom-leader-alt-key to M-m renders helm unusable

### ISSUE THREAD

**Issue by y-usuzumi** [hlissner/doom-emacs#1071]
### Observed behavior

Since I want more consistent behavior with Spacemacs, and because M-m conflicts with my desktop setup (Plasma klauncher shortcut),

In ~/.doom.d/init.el, I added:

```elisp
(setq doom-leader-alt-key "M-m"
      doom-localleader-alt-key "M-m m")
```

When I run any helm command, e.g. C-x C-f I get this message in the minibuffer:

> Key sequence M-SPC h M starts with non-prefix key M-SPC

### Expected behavior

Helm should work normally.

### Steps to reproduce

As in `Observed behavior`

### System information

<details>
<summary>Click to expand</summary>

- OS: gnu/linux (x86_64-pc-linux-gnu)
- Emacs: 26.1 (7月 05, 2018)
- Doom: 2.0.9 (develop b88c71271543ce8556451a90179c7a6c2457769a)
- Graphic display: t (daemon: nil)
- System features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LIBSYSTEMD LCMS2
- Details:
  ```elisp
  elc count: 0
  uname -a:  Linux DCHORUS-OFFICE 4.19.12-arch1-1-ARCH #1 SMP PREEMPT Fri Dec 21 13:56:54 UTC 2018 x86_64 GNU/Linux
  modules:   (:feature eval (evil +everywhere) file-templates (lookup +docsets) snippets spellcheck syntax-checker workspaces :completion company helm :ui doom doom-dashboard doom-modeline evil-goggles hl-todo nav-flash treemacs (popup +all +defaults) unicode vc-gutter vi-tilde-fringe window-select :editor multiple-cursors rotate-text :emacs dired ediff electric hideshow imenu vc :lang data emacs-lisp (haskell +intero) markdown (org +attach +babel +capture +export +present) python rust (sh +fish) :config default)
  packages:  n/a
  exec-path: (~/.local/bin ~/.cargo/bin ~/.cabal/bin ~/go/bin ~/.emacs.d/bin /usr/local/sbin /usr/local/bin /usr/bin /opt/cuda/bin /opt/cxoffice/bin /var/lib/flatpak/exports/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /usr/lib/emacs/26.1/x86_64-pc-linux-gnu)
  ```
</details>

**Comment by hlissner** [comment]
As of 63a224f0, this issue should be resolved. Please update and let me know!

**Comment by y-usuzumi** [comment]
Hi @hlissner ,
After doom upgrade, I got this error:
```
Symbol's function definition is void: solaire-global-mode
```

I tried M-x package-install but I couldn't find solaire-mode in the list.

**Comment by hlissner** [comment]
You'll need to update your packages by running `bin/doom update` (or `make update`, they do the same thing).

**Comment by y-usuzumi** [comment]
Hi @hlissner ,
Thank you, I should have read the wiki more carefully!

Now that I have upgraded, helm works fine, but the doom-leader-alt-key also has no effect. I bound it to "M-m" and it's still bound to the back-to-indentation command.

Did I miss something?

**Comment by hlissner** [comment]
@y-usuzumi My apologies, I hadn't noticed that you use evil. You should be using `doom-leader-key`, rather than `doom-leader-alt-key`:

```elisp
(setq doom-leader-key "M-m")
```

There are four leader variables:

+ `doom-leader-key`
+ `doom-localleader-key`
+ `doom-leader-alt-key`
+ `doom-localleader-alt-key`

The first two variables are relevant only to evil users, and only work in normal, visual, and motion states. They are ignored for non-evil users.

The two alt-key variables are relevant only to insert and emacs states (for evil users), and non-evil users.

I hope that clears things up a bit.

**Comment by y-usuzumi** [comment]
@hlissner 
Hi, thank you for your clarification.

I AM using evil but I do prefer a more emacs-y editing style, so I also added this to my config.el:
 ```elisp
(setq evil-default-state 'emacs)
```
That's why I was setting the -alt variations. I feel comfortable with the default SPC key in normal, visual modes, etc.

**Comment by y-usuzumi** [comment]
Hi @hlissner ,

I noticed that `doom-leader-alt-key` and `doom-localleader-alt-key` do work in insert mode, but not in emacs mode, leading me to investigate `core-keybinds.el` and find the code which I suspect caused the issue.
I'm making a pull request to fix the issue. Since I have no solid understanding of emacs lisp, could you give me some suggestions?

Thanks!

**Comment by y-usuzumi** [comment]
Hi,
Thank you! Not that the pull request has been merged, I'm marking the issue as closed.
