### ISSUE TITLE
Doom theme not getting setup in latest develop | missing function

### ISSUE THREAD

**Issue by baljeet** [hlissner/doom-emacs#1081]
### Observed behavior
doom is not able to set the theme correctly in the latest develop (869758e8f5ed677a0f1ceec9a9fd275e1ce5905d)
On start we see the message:  
`progn: Symbol’s function definition is void: solaire-global-mode`
<img width="582" alt="screenshot 2018-12-28 at 9 37 39 pm" src="https://user-images.githubusercontent.com/2904037/50520907-ec05bc00-0ae8-11e9-9733-350a92dc174b.png">

### Expected behavior
Doom opens normally. no error message and theme setup properly

### Steps to reproduce

1. Rebase develop to latest origin/develop
2. restart emacs

### System information

<details>
<summary>Click to expand</summary>

```
- OS: darwin (x86_64-apple-darwin14.5.0)
- Emacs: 26.1 (May 31, 2018)
- Doom: 2.0.9 (develop 562aa5b67771b99cffb6396e17a321e6321bcae5)
- Graphic display: t (daemon: nil)
- System features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS
- Details:
  ```elisp
  elc count: 0
  uname -a:  Darwin Baljeets-MacBook-Pro.local 18.2.0 Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64
  modules:   (:feature debugger eval (evil +everywhere) file-templates (lookup +docsets) snippets spellcheck syntax-checker workspaces :completion company helm :ui doom doom-dashboard doom-modeline doom-quit evil-goggles hl-todo nav-flash treemacs (popup +all +defaults) pretty-code vc-gutter vi-tilde-fringe window-select :editor format multiple-cursors rotate-text :emacs dired ediff electric hideshow imenu term vc :tools editorconfig gist magit pdf :lang data elixir emacs-lisp go javascript ledger markdown (org +attach +babel +capture +export +present) plantuml python rest (sh +fish) :app write :config literate (default +bindings +evil-commands))
  packages:  n/a
  exec-path: (/Library/Frameworks/Python.framework/Versions/3.7/bin/ /usr/local/bin/ /usr/bin/ /bin/ /usr/sbin/ /sbin/ ~/bin/ /Library/TeX/texbin/ /usr/local/go/bin/ /opt/X11/bin/ /Applications/Emacs.app/Contents/MacOS/bin-x86_64-10_10/ /Applications/Emacs.app/Contents/MacOS/libexec-x86_64-10_10/ /Applications/Emacs.app/Contents/MacOS/libexec/)
  ```

</details>

**Comment by baljeet** [comment]
This works if i comment the following:
  (solaire-global-mode +1)
 in modules/ui/doom/config.el

**Comment by powellc** [comment]
I'm guessing this has to do with this commit: https://github.com/hlissner/emacs-solaire-mode/commit/620df5a1d3d7e780af87079d2a43edf11a7ad5d2

And not having the most up to date solaire-mode package. I did re-make my doom-emacs config though, so I'm not sure what else has to happen.

**Comment by CodyWilson** [comment]
> And not having the most up to date solaire-mode package.

Assuming it has to do with packages not being up to date, you could try running `bin/doom upgrade && bin/doom update` from your `.emacs.d` directory. That should upgrade doom, as well as update your packages.

Fair warning, there's an issue with one of the packages upstream, so you'll likely have to do the fix in https://github.com/hlissner/doom-emacs/issues/1080 to fix that one when you update.

**Comment by powellc** [comment]
Yep ... strangely I hadn't realized `bin/doom/update` existed and always figured pulling the latest develop and re-making updated doom. Nice to know how upgrade packages now :)

**Comment by powellc** [comment]
I ought to add that this did fix this issue for me AND I did not run into the other bug you mentioned. Thanks @CodyWilson !

**Comment by baljeet** [comment]
@CodyWilson @powellc `bin/doom upgrade && bin/doom update` worked for me as well. I also had to apply the fix mentioned in 1080.

But it probably means this is a non-issue. We should use `bin/doom` commands for updating and upgrading rather than rebasing. Hence closing.
