### ISSUE TITLE
How to disable popup when I use R?

### ISSUE THREAD

**Issue by HesperusArcher** [hlissner/doom-emacs#1086]
### Observed behavior

I am a R user with ESS. I want to use R in emacs, while it was in popup buffer in my doom.
I commented the popup in `~/.doom.d/init.el` as below, it worked, but others such as tutorial did not display in the popup window.
```elisp
;; (popup          ; tame sudden yet inevitable temporary windows
;;+all             ; catch all popups that start with an asterix
;;+defaults)       ; default popup rules
```

### Expected behavior

I want to disable popup when I start R (or ess-r-mode) in doom.
Thank you!

### Steps to reproduce

1. `M-x R`
2. select the work dir of R
3. the R worked in popup window

### System information

Doom develop v2.0.9
GNU Emacs 27.0.50
Manjaro with cinnamon

**Comment by hlissner** [comment]
You'll have to create a popup rule for R/ESS to tell the popup system to ignore ESS buffers. I'm not familiar enough with ESS to know what the buffers' names are, so I'll simply assume they're `*ESS*`. You'll have to adjust from there:

```elisp
(set-popup-rule! "^\\*ESS" :ignore t)
```

You'll need to enable the :ui popup module again for this to work, but it will ensure the popup system doesn't handle ESS's windows.

**Comment by xvrdm** [comment]
If anybody ever come up this issue, the solution is actually to use the rule:

```
(set-popup-rule! "^\\*R:" :ignore t)
```

I would also have thought that these ESS buffer names start with `*ESS:`, but turns out it is just `*R:`.
