### ISSUE TITLE
+ivy/project-search doesn't work with tramp

### ISSUE THREAD

**Issue by bricewge** [hlissner/doom-emacs#1087]
### Observed behavior

When accessing a project via tramp `+ivy/project-search` search only from the current file's directory.

### Expected behavior

The same as calling directly `counsel-projectile-XX`, `counsel-projectile-rg` in my case, which is searching from the root of the repository.

### Steps to reproduce

1. `M-x` `/sudo::root@localhost:/etc/nixos/dir/file` (Where /etc/nixos is the root of the repo)
2. `+ivy/project-search` will search from `/etc/nixos/dir` instead of `/etc/nixos`

### System information

<details>
<summary>Click to expand</summary>

- OS: gnu/linux (x86_64-pc-linux-gnu)
- Emacs: 26.1 (déc. 26, 2018)
- Doom: 2.0.9 (develop 46499ec70fae2b311f7bafe986db4af1e9d020b0)
- Graphic display: t (daemon: t)
- System features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LIBSYSTEMD
- Details:
```elisp
  elc count: 0
  uname -a:  Linux taxo 4.19.12 #1-NixOS SMP Fri Dec 21 13:15:25 UTC 2018 x86_64 GNU/Linux
  modules:   (:feature eval (evil +everywhere) file-templates (lookup +docsets) snippets spellcheck syntax-checker workspaces :completion company (lsp +cpp +css +go +vue +python +sh) (ivy +fuzzy +childframe) :ui deft doom doom-dashboard doom-quit evil-goggles hl-todo modeline nav-flash neotree (popup +all +defaults) pretty-code vc-gutter vi-tilde-fringe window-select :editor lispy multiple-cursors rotate-text :emacs dired ediff electric eshell hideshow imenu vc :tools docker editorconfig make magit password-store pdf rgb :lang assembly (cc +irony +rtags) data emacs-lisp go javascript markdown nix (org +attach +babel +capture +export +present) python sh web :config default)
  packages:  ((anaconda-mode :disable t) auto-sudoedit company-lsp (company-shell :disable t) cquery direnv esh-autosuggest evil-lion forge hl-fill-column (justify-kp :recipe (justify-kp :fetcher github :repo Fuco1/justify-kp)) (lsp-css :recipe (lsp-css :fetcher github :repo emacs-lsp/lsp-css)) lsp-go lsp-mode lsp-ui lsp-vue nov (org-caldav :recipe (org-caldav :fetcher github :repo grauschnabel/org-caldav)) org-noter outshine poporg (projectile :recipe (projectile :fetcher github :repo juergenhoetzel/projectile :branch use-non-essential)) (rtags :disable t) solarized-theme systemd vue-mode webpaste yasnippet-snippets)
  exec-path: (~/bin /run/wrappers/bin ~/.nix-profile/bin /nix/var/nix/profiles/default/bin /run/current-system/sw/bin /etc/profiles/per-user/bricewge/bin /nix/store/38nvjpx10iib5aqzajfs21j65l1ia0js-emacs-26.1/libexec/emacs/26.1/x86_64-pc-linux-gnu)
  ```

</details>

**Comment by hlissner** [comment]
This is by design, because projectile project resolution is unbearably slow over tramp.

However, you can try to reverse this behavior by adding the following to your ~/.doom.d/config.el:

```elisp
(after! projectile
  (advice-remove #'projectile-locate-dominating-file #'doom*projectile-locate-dominating-file))
```

**Comment by hlissner** [comment]
I'll close this for the time being. If you're still having this issue, feel free to reopen it.

**Comment by bricewge** [comment]
Sorry for the late response. Yes removing the advice solve the issue, thanks!
