### ISSUE TITLE
open .offlineimaprc in conf-mode

### ISSUE THREAD

**Issue by SteamedFish** [hlissner/doom-emacs#1091]
### Observed behavior

emacs opens `~/.offlineimaprc` in fundamental mode, even after enable `:app email` layer

### Expected behavior

emacs should open `~/.offlineimaprc` in conf-mode

### Steps to reproduce

* enable `:app email` layer
* open `~/.offlineimaprc`
* emacs opens in fundamental mode instead of conf-mode

### System information

<details>
<summary>Click to expand</summary>

- OS: darwin (x86_64-apple-darwin18.2.0)
- Emacs: 26.1 (Dec 27, 2018)
- Doom: 2.0.9 (develop 5e3d4c3ba286f4b9ef5a59e502ff733673e38e46)
- Graphic display: t (daemon: nil)
- System features: DBUS NOTIFY ACL LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2
- Details:
  ```elisp
  elc count: 0
  uname -a:  Darwin SteamedFish-iMac.local 18.2.0 Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64
  modules:   (:feature debugger eval (evil +everywhere) file-templates (lookup +docsets) snippets spellcheck syntax-checker workspaces :completion company helm :ui deft doom doom-dashboard doom-modeline doom-quit evil-goggles fci hl-todo nav-flash treemacs (popup +all +defaults) pretty-code unicode vc-gutter vi-tilde-fringe window-select :editor format multiple-cursors rotate-text :emacs dired ediff electric eshell hideshow imenu term vc :tools ansible docker editorconfig gist macos make magit pdf rgb terraform tmux upload :lang cc data emacs-lisp go javascript latex markdown (org +attach +babel +capture +export +present) perl php python (sh +fish) web :app email irc (write +wordnut +langtool) :config default)
  packages:  (cnfonts fcitx)
  exec-path: (/usr/local/opt/python/libexec/bin/ /usr/local/bin/ /usr/local/sbin/ /usr/bin/ /bin/ /usr/sbin/ /sbin/ /usr/libexec/ /Volumes/DATA/ConTeXt/tex/texmf-osx-64/bin/ /usr/local/opt/llvm/bin/ /opt/X11/bin/ /Applications/Wireshark.app/Contents/MacOS/ /usr/local/Cellar/emacs-mac/emacs-26.1-z-mac-7.4/libexec/emacs/26.1/x86_64-apple-darwin18.2.0/)
  ```

</details>

**Comment by hlissner** [comment]
As of b1aca7db, both .offlineimaprc and .mbsyncrc files should open in conf-mode if app/email is enabled. Let me know if that isn't the case.

Thanks for letting me know!
