### ISSUE TITLE
Missing faces for emms-metaplaylist-mode-*

### ISSUE THREAD

**Issue by memeplex** [hlissner/doom-emacs#1093]
I'm using tomorrow night.

**Comment by hlissner** [comment]
Thanks for letting me know, but this belongs in the issue tracker for [doom-themes](https://github.com/hlissner/emacs-doom-themes), not Doom Emacs. Please move it there. It'd also be a big help if you could include a concrete list of those faces. Even better if it included the faces' default colors or settings.
