### ISSUE TITLE
If disable 'smartparens', it occour an error when type 'o' in normal go mode.

### ISSUE THREAD

**Issue by shuxiao9058** [hlissner/doom-emacs#1094]
```
let: Cannot open load file: No such file or directory, smartparens
```

The system is macOS 10.14.2, and the Emacs version is 27.0.50(head version of emacs-plus).

**Comment by hlissner** [comment]
Smartparens is a core plugin. It will cause problems if you disable core packages via `(package! X :disable t)`. Instead of disabling them that way, I suggest disabling their functionality instead. For smartparens, that'd be:

```elisp
(after! smartparens
  (smartparens-global-mode -1))
```

**Comment by jdelStrother** [comment]
This page is high in Google's results for doom emacs / smartparens searches, but that fix is no longer correct.  Instead (from the FAQ): 

```elisp
(remove-hook 'doom-first-buffer-hook #'smartparens-global-mode)
```
