### ISSUE TITLE
previous command was not an evil-paste

### ISSUE THREAD

**Issue by shuxiao9058** [hlissner/doom-emacs#1095]
paste with yank occurs an error.

type with `SPACE i y`
```
Quit
user-error: Previous command was not an evil-paste: evil-write
Quit [2 times]
user-error: Previous command was not an evil-paste: minibuffer-keyboard-quit
user-error: Previous command was not an evil-paste: evil-paste-pop
Mark set
```

**Comment by HaoZeke** [comment]
Yup I reported this on discord a few days back.

**Comment by hlissner** [comment]
Sorry for the late response. As of d46c258 this should be resolved. Please update and let me know if that isn't the case and I will reopen the issue.

Thanks for letting me know!

**Comment by shuxiao9058** [comment]
Thanks for your great job, it works fine now. @hlissner
