### ISSUE TITLE
Wiki: orphaned TOC item in Customization page

### ISSUE THREAD

**Issue by vlamacko** [hlissner/doom-emacs#1096]
After commit [207b353](https://github.com/hlissner/doom-emacs/wiki/Customization/207b353ea44c26f25206111e76536183c682cd27) there is an item "Keep my customizations in version control?" orphaned in the table of contents.

This also breaks the last question in FAQ that has a link pointing to the deleted section.

**Comment by hlissner** [comment]
I've removed the two sections. Thanks for letting me know!
