### ISSUE TITLE
Local leader keybindings are being triggered while in the replace state

### ISSUE THREAD

**Issue by robbert-vdh** [hlissner/doom-emacs#1097]
### Observed behavior

Trying to type a space character while in replace mode acts as a prefix for the `SPC m` local leader keybindings.

### Expected behavior

A regular whitespace character should be inserted instead.

### Steps to reproduce

1. Open a new scratch buffer.
2. Switch to `python-mode` (or any other mode that has local leader keybindings) using `M-x python-mode`.
2. Press `R` to enter the replace state.
3. Press `SPC` once.

### System information

<details>
<summary>Click to expand</summary>

- OS: gnu/linux (x86_64-pc-linux-gnu)
- Emacs: 26.1 (jul 05, 2018)
- Doom: 2.0.9 (develop 9916025d5c1fa6ce05aed883af96580179c2a2f0)
- Graphic display: t (daemon: nil)
- System features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LIBSYSTEMD LCMS2
- Details:
  ```elisp
  elc count: 29
  uname -a:  Linux desktop 4.20.0-1-MANJARO #1 SMP PREEMPT Mon Dec 24 08:20:48 UTC 2018 x86_64 GNU/Linux
  modules:   (:feature debugger eval (evil +everywhere) file-templates (lookup +docsets) snippets spellcheck (syntax-checker +childframe) workspaces :completion company (helm +fuzzy) :ui doom doom-modeline doom-quit evil-goggles hl-todo nav-flash treemacs (popup +all +defaults) vc-gutter vi-tilde-fringe window-select :editor format multiple-cursors rotate-text :emacs dired ediff electric eshell hideshow imenu term vc :tools docker editorconfig ein gist make magit pdf rgb :lang csharp data emacs-lisp ess (haskell +intero) javascript (latex +latexmk) markdown (org +attach +babel +capture +export +present) php python rest rust (sh +fish) web :app write :config default)
  packages:  (company-lsp ein evil-lion ggtags kotlin-mode lsp-mode lsp-ui ob-ipython page-break-lines phpcbf pkgbuild-mode (racer :ignore t :disable t))
  exec-path: (~/.cargo/bin ~/.local/bin ~/.cargo/bin ~/.dotfiles/bin ~/.local/bin /usr/local/sbin /usr/local/bin /usr/bin /opt/cuda/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /usr/lib/emacs/26.1/x86_64-pc-linux-gnu)
  ```
</details>

**Comment by hlissner** [comment]
As of 25b9a90, this should be resolved. Please update and let me know if that isn't the case, and I'll reopen this.

Thanks for letting me know!
