### ISSUE TITLE
Equivalent to x-focus-frame for doom-emacs?

### ISSUE THREAD

**Issue by Ptival** [hlissner/doom-emacs#1103]
On MacOS, when running emacs from the terminal, is starts in the background, rather than in the foreground.

The advice online is to put:
`(x-focus-frame nil)`
in your configuration.

However, this seems to make doom-emacs unhappy:
```
--------------------------------------------------

There was an unexpected error:
  Error in private config (doom-private-error)
  config.el
  (error Window system frame should be used)

Run the command again with the -d (or --debug) option to enable debug
mode and, hopefully, generate a stack trace. If you decide to file a bug
report, please include it!

Emacs outputs to standard error, so you’ll need to redirect stderr to
stdout to pipe this to a file or clipboard!

  e.g. doom -d install 2>&1 | clipboard-program
Doom loaded 233 packages across 48 modules in 3.210s
Error in Doom Emacs core: doom-private-error, "config.el", (error "Window system frame should be used")
```

Is there an equivalent command, or some sort of check I could use to get the feature without the error?

**Comment by hlissner** [comment]
That is peculiar, for two reasons:

1. That error message appears to be produced by a `bin/doom` (or `make`) command. It is expected for `x-focus-frame` to produce this error if used from non-interactive or tty Emacs (`bin/doom` creates a non-interactive instance). If this is the case, what `bin/doom` command did you run, exactly?

2. `bin/doom` is designed _not_ to load `~/.doom.d/config.el`, _only_ `~/.doom.d/init.el`. This suggests your config.el file is being loaded from your init.el somehow. Are you sure you don't have a `(load! "config")` or something in your init.el? If you do, that isn't necessary. Doom loads config.el after all other modules have loaded.

**Comment by Ptival** [comment]
Oh, I did not mention that this error appears while running `make`!

My `init.el` is copy-pasted from `init.example.el` with only some languages uncommented.

**Comment by hlissner** [comment]
Try this instead:

```elisp
(add-hook! 'window-setup-hook (x-focus-frame nil))
```
