### ISSUE TITLE
add gnuplot support.

### ISSUE THREAD

**Issue by flyingns** [hlissner/doom-emacs#1108]
I am planning to add gnuplot support in org-babel. What settings do I need to make? 
Simple point on the line.

Thanks.

**Comment by hlissner** [comment]
Sorry for the late response. I'd happily accept gnuplot support, but your question is too broad for me to answer, so here's a general answer:

1. Add your config to `modules/lang/org/+babel.el`,
2. Make sure packages are deferred/lazy-loaded,
3. Add any packages you need to `modules/lang/org/packages.el` inside the `(when (featurep! +babel) ...)` block.

I hope that helps!

**Comment by hlissner** [comment]
11bfb17 adds rudimentary gnuplot support with the new `+gnuplot` flag for the `:lang org` module, so I'll consider this resolved. Thanks for bringing it to my attention!

**Comment by flyingns** [comment]
Thanks a lot, @hlissner .
