### ISSUE TITLE
Disable the bottom panel for showing errors when using proof general?

### ISSUE THREAD

**Issue by Ptival** [hlissner/doom-emacs#1111]
ProofGeneral is meant to be used in a 3-pane style with a buffer dedicated to printing out errors when they happen.

Unfortunately, this ends up being redundant when flycheck (I think) also displays the error information both at the tip, and at the bottom of the editor.

![image](https://user-images.githubusercontent.com/478606/50998367-fdcd6300-14db-11e9-8704-eff436d7f2c9.png)

Notice how the error message is reported 3 times! I think it'd be best to prevent the bottom one from appearing when proof general is at work. I'm not sure how to do this modification, so any help would be appreciated!

**Comment by hlissner** [comment]
It does look troublesome. Do you still have this issue? I don't use ProofGeneral so my insight into the matter is limited. With your cursor over the error region, could you run `M-x doom/what-face` and tell me what faces/overlays it detects?

Also, from that SAW.v file buffer, tell me the values of these two variables:

+ `flycheck-display-errors-function`
+ `eldoc-documentation-function`

(You can retrieve them with `SPC h v flycheck-display-errors-function`, or `M-x helpful-variable RET flycheck-display-errors-function`, or `M-; flycheck-display-errors-function`)

**Comment by dkhalanskyjb** [comment]
For what it's worth, I installed Doom Emacs for use with Proof General today and didn't encounter such problems.

**Comment by Ptival** [comment]
Oh yeah, sorry I forgot about this, and it no longer happens to me. Closing!
