### ISSUE TITLE
org-store-agenda-views not working correctly

### ISSUE THREAD

**Issue by Pentaquark1** [hlissner/doom-emacs#1115]
### Observed behavior
Tried this script from the official org manual which works in vanilla emacs:
```
(setq org-agenda-custom-commands
      '(("X" agenda "" nil ("agenda.html" "agenda.ps"))
        ("Y" alltodo "" nil ("todo.html" "todo.txt" "todo.ps"))
        ("h" "Agenda and Home-related tasks"
         ((agenda "")
          (tags-todo "home")
          (tags "garden"))
         nil
         ("~/views/home.html"))
        ("o" "Agenda and Office-related tasks"
         ((agenda)
          (tags-todo "work")
          (tags "office"))
         nil
         ("~/views/office.ps" `"~/calendars/office.ics"))))
```
Calling org-store-agenda-views yields

> Wrong number of arguments: (0 . 1), 2

I assume this means we supplied 2 arguments, while the function only accepts 0 or 1 arguments as input

### Expected behavior

In vanilla emacs org-store-agenda-views exports the custom agenda views to the files specificied in org-agenda-custom-commands

### Steps to reproduce

1. Yank the snippet into ~/.doom.d/config.el
2. Call org-store-agenda-views

It didn't matter for me if I called it in the agenda or anywhere else, same result.

- OS: gnu/linux (x86_64-pc-linux-gnu)
- Emacs: 26.1 (Jul 05, 2018)
- Doom: 2.0.9 (develop 4b2dbe42a5a472d5836293727eebc672b54e5f1a)
- Graphic display: t (daemon: nil)
- System features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LIBSYSTEMD LCMS2
- Details:
  ```elisp
  elc count: 0
  uname -a:  Linux fractal 4.14.87-1-MANJARO #1 SMP PREEMPT Sat Dec 8 15:56:41 UTC 2018 x86_64 GNU/Linux
  modules:   (:feature eval (evil +everywhere) file-templates (lookup +devdocs +docsets) snippets spellcheck (syntax-checker +childframe) workspaces :completion company (helm +fuzzy) (ivy +childframe) :ui popup doom doom-dashboard doom-modeline doom-quit evil-goggles hl-todo nav-flash neotree pretty-code vc-gutter vi-tilde-fringe window-select :tools editorconfig ein gist make magit pdf prodigy rgb tmux upload :emacs dired ediff electric eshell hideshow imenu vc :editor multiple-cursors rotate-text :lang cc clojure data elm emacs-lisp ess hy julia latex ledger markdown nim nix (org +attach +babel +capture +export +present +publish) python rest sh web :app rss (write +wordnut +langtool) :config default)
  packages:  (idle-org-agenda)
  exec-path: (/usr/local/bin /usr/bin /bin /usr/local/sbin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /usr/lib/emacs/26.1/x86_64-pc-linux-gnu)

**Comment by hlissner** [comment]
Do `M-x toggle-debug-on-error` and recreate the error. Emacs should produce a backtrace; please copy that that here.

**Comment by hlissner** [comment]
I'll consider this issue resolved or forgotten. If that isn't the case, let me know and I'll reopen it.
