### ISSUE TITLE
When refiling: Invalid function: org-preserve-local-variables

### ISSUE THREAD

**Issue by jackbaty** [hlissner/doom-emacs#1116]
### Observed behavior

When attempting to use `org-refile` the operation fails and I'm shown this error:

> Invalid function: org-preserve-local-variables

```
Buffer has been modified; could not load undo-tree history
Getting targets...
uncompressing .!Users!jbaty!Dropbox!org!timesheet.org.~undo-tree~.gz...done
uncompressing .!Users!jbaty!Dropbox!org!tickler.org.~undo-tree~.gz...done
Getting targets...done
Copied: Subtree(s) with 531 characters
org-copy-subtree: Invalid function: org-preserve-local-variables
```

### Expected behavior

Running `org-refile` should refile the subtree

### Steps to reproduce

1. With point on a heading, run `C-c C-w` (org-refile)
2. Error "Invalid function: org-preserve-local-variables" is displayed in minibuffer and the subtree remains unmoved.

This feels like a package issue but I've run doom refresh, recompile, etc. with no effect. The only thing similar I could find was a [Spacemacs error](https://emacs-china.org/t/spacemacs-org-mode-org-refile/8157) that looks to have been fixed by recompiling. 

### System information

<details>
<summary>Click to expand</summary>

- OS: darwin (x86_64-apple-darwin14.5.0)
- Emacs: 26.1 (May 30, 2018)
- Doom: 2.0.9 (develop 4b2dbe42a5a472d5836293727eebc672b54e5f1a)
- Graphic display: t (daemon: nil)
- System features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS
- Details:
  ```elisp
  elc count: 29
  uname -a:  Darwin Jacks-iMac.localdomain 18.2.0 Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64
  modules:   (:feature eval (evil +everywhere) file-templates (lookup +docsets) snippets spellcheck syntax-checker workspaces :completion company helm :ui doom doom-dashboard doom-modeline doom-quit evil-goggles hl-todo nav-flash treemacs (popup +all +defaults) vc-gutter vi-tilde-fringe window-select :editor multiple-cursors rotate-text :emacs dired ediff electric hideshow imenu term vc :tools macos magit :lang data emacs-lisp markdown (org +attach +babel +capture +export +present) (sh +fish) :config default)
  packages:  (org-journal)
  exec-path: (~/bin/ /Library/TeX/texbin/ /usr/local/bin/ /usr/local/sbin/ /bin/ /usr/local/git/bin/ /usr/bin/ /usr/sbin/ /sbin/ /Applications/Emacs.app/Contents/MacOS/bin-x86_64-10_10/ /Applications/Emacs.app/Contents/MacOS/libexec-x86_64-10_10/ /Applications/Emacs.app/Contents/MacOS/libexec/)
  ```

</details>

**Comment by heyheydanhey** [comment]
I'm encountering exactly the same error message when using org-refile. I've tried stripping my init.el back literally to nothing, and it still occurs, although when launching with `emacs --no-init` it works fine. 

**System information**
- OS: Ubuntu (18.10)
- Emacs 25.2.2
- Org 20181230

**Comment by daviderestivo** [comment]
@jackbaty Try to remove all the .elc file from org folder in .emacs.d/elpa. It worked for me. You can find more infos in here: https://github.com/syl20bnr/spacemacs/issues/11801

**Comment by kmarker1101** [comment]
> You could also try running `~/.emacs.d/bin/doom compile :plugins` to recompile all your packages, including org.

This worked for me. I just switched from spacemacs and had the same issue there.

**Comment by jackbaty** [comment]
Recompiling worked, thanks. Could have sworn I tried that but seems not. Refiling is working great, now.

**Comment by alexlai97** [comment]
I encountered this same problem after updating (and upgrading) today. I tried all the methods above, doesn't work. I even reinstalled doom emacs, the issue is still there.

**Comment by hlissner** [comment]
The old instructions are obsolete now, so I'll compile the solutions into a new post:

1. Run `doom build` to recompile all your packages' byte-code. This seems to have fixed it for most folks.
2. Failing that, it's possible you are manually loading `org` too early (likely in your `~/.doom.d/init.el`. Loading org that early means you're loading the wrong version of org. Remove any `use-package` or `require` calls in your init.el.
3. If you have no time to debug and just want a quick solution, delete all `~/.emacs.d/.local/straight/build/org-mode/*.elc` files as a temporary measure.

Hope that helps!

**Comment by djelenc** [comment]
> The old instructions are obsolete now, so I'll compile the solutions into a new post:
> 
> 1. Run `doom build` to recompile all your packages' byte-code. This seems to have fixed it for most folks.
> 2. Failing that, it's possible you are manually loading `org` too early (likely in your `~/.doom.d/init.el`. Loading org that early means you're loading the wrong version of org. Remove any `use-package` or `require` calls in your init.el.
> 3. If you have no time to debug and just want a quick solution, delete all `~/.emacs.d/.local/straight/build/org-mode/*.elc` files as a temporary measure.
> 
> Hope that helps!

In my case, none of the three steps helped. The refile stopped working after I upgraded doom to `Doom v2.0.9 (HEAD -> develop 1c99aed0c 2020-08-25 21:22:56 -0400)`. Unfortunately, I cannot remember which version of Doom I was using before.

**Comment by murning** [comment]
Just had the same problem after upgrade. Step 3 worked for me.

**Comment by karlicoss** [comment]
Sadly, had the same on a fresh install (`f5c9739`) :(

Just step 3 from above didn't help, had to ditch all org-mode `elc` files: `find ~/.emacs.d/.local/straight/build-*/org*/*.elc -print0 | xargs -0 rm`

Sadly, after running `doom build` it started happening again. I then removed all `elc` files again, reran `M-x straight-rebuild-all` in emacs; restarted and it's fine now. Very weird!
