### ISSUE TITLE
Org mode Press C-c C-, report warning...

### ISSUE THREAD

**Issue by flyingns** [hlissner/doom-emacs#1127]
When I press C-c C- in org mode, report warning:

> Warning (org): Please update the entries of `org-structure-template-alist’.
> 
> In Org 9.2 the format was changed from something like
> 
> ("s" "#+BEGIN_SRC ?\n#+END_SRC")
> to something like
> 
> ("s" . "src")
> Please refer to the documentation of `org-structure-template-alist’.
> 
> The following entries must be updated:
> 
> ((“n” “#+BEGIN_NOTES\n?\n#+END_NOTES”))

The new DOOM, develop branch of git clone may be the reason for upgrading org 9.2, trying to solve it but not succeeding.

===========
MACOS/emacs-plus 26.1

**Comment by flyingns** [comment]
> Looks like you're missing the last key in `C-c C-`. What command are you trying to invoke?

Oh sorry, I didn't pay attention, I lost a comma.

I am in org mode, press "C-c C-," to call easy-template, org 9.2 was previously the input <s <TAB> automatically expanded into:

> #+BEGIN_SRC
> 
> #+END_SRC

There are a lot of changes in org 9.2, the automatic expansion here starts with a shortcut, but I use the shortcut to report the above warning.

**Comment by flyingns** [comment]
At first I thought it was my personal settings problem, but when I transferred the original .emacs.d and cloned the latest doom from github, without any changes to it, it still reported the warning, I will I don't quite understand why.

**Comment by hlissner** [comment]
It turns out that this is an issue with ox-reveal, and was already reported in https://github.com/yjwen/org-reveal/issues/363. I've pushed a fix for it in 24b4d24. Please update and let me know if that isn't the case.

**Comment by flyingns** [comment]
> It turns out that this is an issue with ox-reveal, and was already reported in [yjwen/org-reveal#363](https://github.com/yjwen/org-reveal/issues/363). I've pushed a fix for it in [24b4d24](https://github.com/hlissner/doom-emacs/commit/24b4d24d18d7f1e61f40be73484244e763141795). Please update and let me know if that isn't the case.

The problem is solved, thanks to @hlissner.
