### ISSUE TITLE
Binding for A-SPC eventually changes (in Haskell mode?)

### ISSUE THREAD

**Issue by Ptival** [hlissner/doom-emacs#1135]
Hey, this is a very weird bug and I am not quite sure yet what triggers it, but, in my configuration, I have:

```
  (define-key!
    ...
    [A-SPC]         #'just-one-space
    ...))
```

and, while it works when I start emacs, it's been several times that, after a little bit of using, the mapping changes to instead inserting a no-break space.

It's happened in Haskell mode, and i haven't tried yet to see if it happens in other modes. I have also never really noticed it right away, so I'm not sure what the trigger is. When it happens, even doing a `doom-reload` does not revert it (does reload not rerun config.el? EDIT: oh I guess it would had I run `make`?)

This is very low priority obviously. :-)

A `describe-key` after it has reverted says:

```
  (translated from A-SPC) runs the command self-insert-command (found in
global-map), which is an interactive built-in function in ‘C source code’.

It is bound to many ordinary text characters.

(self-insert-command N)
```

**Comment by hlissner** [comment]
> even doing a `doom-reload` does not revert it (does reload not rerun config.el? EDIT: oh I guess it would had I run `make`?)

`doom/reload` re-reads your config, but does not "reset" your current session in any way (no good way to do that without simply restarting Emacs).

> but, in my configuration, I have:

Is this in `~/.doom.d/init.el` or `~/.doom.d/config.el`?

> `[A-SPC]`

Could you try `"<A-SPC>"` instead? I'm not certain that `[A-SPC]` (as a vector) is a valid representation of that key.

-----

It's possible that `A-SPC` is being rebound somewhere, by some package, but it's hard to pinpoint the cause. You could try putting it in the override keymap to give it maximum precedence, but this may come back to bite you in modes that want to bind `A-SPC` themselves.

```elisp
(define-key! 'override "<A-SPC>" #'just-one-space)
```
