### ISSUE TITLE
Font Awesome symbols way to large big

### ISSUE THREAD

**Issue by asamwow** [hlissner/doom-emacs#1138]
### Observed behavior

Symbols from font awesome are about 4x bigger than they should be. For example, the save icon when you edit a file or the power icon next to recently opened files are enormous, 4x bigger than other icons which seem to work fine.

### Expected behavior

Normal sized icons.

### Steps to reproduce

1. sudo pacman -S ttf-font-awesome
2. open emacs

### System information

<details>
<summary>arch</summary>

```
- OS: gnu/linux (x86_64-pc-linux-gnu)
- Emacs: 26.1 (Jul 05, 2018)
- Doom: 2.0.9 (develop 2e8329e6b6b3a548fa2c5d0b61b685bbca654de0)
- Graphic display: t (daemon: nil)
- System features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LIBSYSTEMD LCMS2
- Details:
  ```elisp
  elc count: 0
  uname -a:  Linux verulent 4.20.3-arch1-1-ARCH #1 SMP PREEMPT Wed Jan 16 22:38:58 UTC 2019 x86_64 GNU/Linux
  modules:   (:feature eval file-templates (lookup +docsets) snippets spellcheck syntax-checker workspaces :completion company helm :ui doom doom-dashboard doom-modeline doom-quit hl-todo nav-flash treemacs (popup +all +defaults) vc-gutter vi-tilde-fringe window-select :editor multiple-cursors rotate-text :emacs dired ediff electric hideshow imenu vc :tools editorconfig magit pdf :lang csharp data emacs-lisp latex markdown (org +attach +babel +capture +export +present) python (sh +fish) :app email (write +wordnut +langtool) :config default)
  packages:  n/a
  exec-path: (/usr/local/bin /usr/bin /bin /usr/local/sbin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl ~/.rvm/bin /usr/lib/emacs/26.1/x86_64-pc-linux-gnu)
```
</details>

**Comment by hlissner** [comment]
The fonts must be installed via `M-x all-the-icons-install-fonts`. This is a known incompatibility with what `ttf-font-awesome` provides. I'm unaware of any workaround besides that, sorry to say.

**Comment by clawoflight** [comment]
That does indeed solve it, thanks!
I still have a lot of missing icons though, any idea how to solve that?

**Comment by asamwow** [comment]
> That does indeed solve it, thanks!
> I still have a lot of missing icons though, any idea how to solve that?

#724 you need to install manually.

**Comment by Amatrelan** [comment]
Hmm I got same problem. I'm using wayland and sway so for some reason `M-x all-the-icons-install-fonts` don't work right. But installed with yay (some was straight from pacman) `yay -S ttf-all-the-icons ttf-atom-file-icons ttf-font-icons ttf-material-design-icons` and now seems to work all icons in emacs. I try to check why `M-x all-the-icons-install-fonts` don't work right.

**Comment by hlissner** [comment]
I wasn't aware a `ttf-all-the-icons` package existed. That sounds like a good alternative to `all-the-icons-install-fonts` for Arch users who have this issue.

**Comment by Amatrelan** [comment]
Yeah `ttf-all-the-icons` had most of them but for example modeline git check mark on right corner isn't in that package so I installed `ttf-materlian-design-icons` and it works too right.

**Comment by Amatrelan** [comment]
Hey further notice about this. 
```
-rw-r--r-- 1 ichigo ichigo    0 Feb 12 19:31 all-the-icons.ttf
-rw-r--r-- 1 ichigo ichigo    0 Feb 12 19:31 file-icons.ttf
-rw-r--r-- 1 ichigo ichigo    0 Feb 12 19:31 fontawesome.ttf
-rw-r--r-- 1 ichigo ichigo    0 Feb 12 19:31 material-design-icons.ttf
-rw-r--r-- 1 ichigo ichigo    0 Feb 12 19:31 octicons.ttf
-rw-r--r-- 1 ichigo ichigo    0 Feb 12 19:31 weathericons.ttf
```
Used that command and found out it "donwloaded" them but with 0 byte size. @hlissner is that function made by you? Or some external?

**Comment by Amatrelan** [comment]
Ah found, [All-the-icons](https://github.com/domtronn/all-the-icons.el) seems to be that is quite dead. There was a lot problems with fonts.

**Comment by hlissner** [comment]
@Amatrelan `all-the-icons-install-fonts` is provided by the `all-the-icons` package.

Judging from [this thread](https://github.com/domtronn/all-the-icons.el/issues/133#issuecomment-463129217), a new maintainer was recently brought on board so it might not be dead yet. It might be better to report these issues there.

That said, these sound like these could be network issues. Perhaps all `all-the-icons-install-fonts` needs is better error checks.

**Comment by hlissner** [comment]
`all-the-icons-install-fonts` was fixed a little while ago, so I'll consider this issue resolved. Thanks for bringing this to my attention!
