### ISSUE TITLE
Haskell module repl doesn't support new-repl

### ISSUE THREAD

**Issue by ar1a** [hlissner/doom-emacs#1140]
SPC-o-r in a new-style cabal project, the repl will continually crash because it's trying to run `cabal repl` instead of `cabal new-repl`

**Comment by ocharles** [comment]
I don't think this is a doom-emacs problem, is it? More a problem of haskell-mode.

**Comment by ar1a** [comment]
i didn't look into it very much so i figured i'd put it here until more sleuthing could be done

**Comment by hlissner** [comment]
I haven't looked at Haskell or its ecosystem in a while (and when I do it's with intero). How should I go about detecting whether to use the old or new command? Should that even be Doom's responsibility? I'm open to suggestions.

`SPC o r` invokes `+eval/open-repl`, which uses `+haskell-repl-buffer` (the [registered repl handler for haskell-mode et co](https://github.com/hlissner/doom-emacs/blob/develop/modules/lang/haskell/config.el#L19)), which has a [very simple definition](https://github.com/hlissner/doom-emacs/blob/develop/modules/lang/haskell/autoload.el#L4-L8):

```elisp
;; modules/lang/haskell/autoload.el
(defun +haskell-repl-buffer (&optional arg)
  "Returns the appropriate Haskell REPL buffer."
  (if (featurep! +intero)
      (intero-repl-buffer arg)
    (haskell-session-interactive-buffer (haskell-session))))
```

**Comment by ar1a** [comment]
actually i'm not using intero with this, i'm using dante if that wasn't clear

**Comment by ar1a** [comment]
and i think theres a few files that only show up when using new-style builds, i couldn't tell you which though

**Comment by jdnavarro** [comment]
It seems it's not documented in `haskell-mode`, but you can set `haskell-process-type` to `'cabal-new-repl`. I haven't tried it in doom emacs but works properly for me in Spacemacs.

**Comment by hlissner** [comment]
@ar1a @jdnavarro Do you think `(setq haskell-process-type 'cabal-new-repl)` would be a reasonable default?

**Comment by ar1a** [comment]
Probably not, because not everyone uses the new-style project. A lot of tooling still only supports the old style.

**Comment by hlissner** [comment]
As of ffe297b `cabal-new-repl` is mentioned in lang/haskell's [README](https://github.com/hlissner/doom-emacs/blob/ffe297bc7f49be3dd751b7a5ed1978a350d268ed/modules/lang/haskell/README.org#using-the-new-style-cabal-repl), so I'll consider this resolved. Thanks for bringing this to my attention.
