### ISSUE TITLE
M-RET in org mode no longer Insert a new heading or item

### ISSUE THREAD

**Issue by itainoam** [hlissner/doom-emacs#1146]
### Observed behavior

M-RET in org mode no longer Insert a new heading or item.

### Expected behavior
M-RET should be bound to org-meta-return

### Steps to reproduce
Press M-RET in a `[ ]` list.

**Comment by hlissner** [comment]
What is `M-RET` bound to? `SPC h k M-RET` from an org-mode buffer should tell you.

**Comment by itainoam** [comment]
`default/newline-below`

**Comment by areinisc** [comment]
Please be aware that (at least for some mac users) the command and alt/option keys were renamed recently in Doom. Please also be aware that `M-RET` has a different behavior when invoked in normal state as compared to insert state. When I press 'M-RET' (now alt+return on my computer) from insert mode while my cursor is in a checkmark list, a new item is inserted as expected.

**Comment by itainoam** [comment]
@areinisc, you're right it does insert checkmark item in insert mode. Thanks!

I was not expecting it would behave differently in insert mode. I guess you get used to it?

**Comment by hlissner** [comment]
It should behave the same from normal mode. I'll look into a fix for this soon.

**Comment by hlissner** [comment]
As of b461c99, command+RET should behave correctly and consistently across normal and insert mode in org-mode. Please update and let me know if this is what you expected.

**Comment by itainoam** [comment]
Fixed. Thanks for your awesome work!
