### ISSUE TITLE
Treemacs open error

### ISSUE THREAD

**Issue by GinGin3203** [hlissner/doom-emacs#1151]
### Observed behavior

When trying to open Treemacs (`M-x treemacs` or `M-x +treemacs/toggle`), it outputs 

`Opening output file: No such file or directory, /home/username/.emacs.d/.cache/treemacs-persist-at-last-error`

I'm using the default `.emacs.d` directory, and there actually is no `.emacs.d/.cache` directory, but there is a `.emacs.d/.local/cache` directory which contains `treemacs-persist` file, and in `.emacs.d/modules/ui/treemacs/config.el` there are lines

`treemacs-persist-file (concat doom-cache-dir "treemacs-persist")`
`treemacs--last-error-persist-file (concat doom-cache-dir "treemacs-persist-at-last-error"))`,

so maybe there is an issue with `doom-cache-dir`.

### Expected behavior

Open Treemacs window.

### Steps to reproduce

`M-x treemacs`

### System information

<details>
<summary>Click to expand</summary>

```
- OS: gnu/linux (x86_64-pc-linux-gnu)
- Emacs: 26.1 (Jul 05, 2018)
- Doom: 2.0.9 (develop bd9df22f9951e36ba74b61a3619bcc40906ca1d9)
- Graphic display: t (daemon: nil)
- System features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LIBSYSTEMD LCMS2
- Details:
  ```elisp
  elc count: 0
  uname -a:  Linux username 4.20.6-arch1-1-ARCH #1 SMP PREEMPT Thu Jan 31 08:22:01 UTC 2019 x86_64 GNU/Linux
  modules:   (:feature eval (evil +everywhere) file-templates (lookup +docsets) snippets spellcheck syntax-checker workspaces :completion company ivy :ui deft doom doom-dashboard doom-quit evil-goggles fci hl-todo nav-flash neotree treemacs (popup +all +defaults) unicode vc-gutter vi-tilde-fringe window-select :editor format multiple-cursors rotate-text :emacs dired ediff electric hideshow imenu term vc :tools editorconfig ein gist make magit password-store pdf rgb terraform tmux :lang assembly (cc +irony +rtags) coq data elixir emacs-lisp go (java +meghanada) javascript julia latex markdown (org +attach +babel +capture +export +present) php python scala (sh +fish) :app email twitter write :config default)
  packages:  n/a
  exec-path: (~/.scripts/cron ~/.scripts/pix ~/.scripts/statusbar ~/.scripts/tools ~/.scripts/i3cmds ~/.scripts/.getkeys ~/.scripts/ /usr/local/sbin /usr/local/bin /usr/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /usr/lib/emacs/26.1/x86_64-pc-linux-gnu)
```

**Comment by hlissner** [comment]
As of 3fd1548 this should be resolved. Please update and let me know if that isn't the case and I'll reopen this issue. Thanks for letting me know!

**Comment by GinGin3203** [comment]
Yep, it works!
