### ISSUE TITLE
Solidity loading packages

### ISSUE THREAD

**Issue by Emiller88** [hlissner/doom-emacs#1152]
When opening a solidity file
```
Error (use-package): Cannot load solidity-flycheck
Error (use-package): Cannot load company-solidity
```
Only occurs when first opening the second time it just opens it with no error.

**Comment by hlissner** [comment]
Have you run `bin/doom refresh` recently? Or `bin/doom update`? It's possible a package failed to install correctly. At worst you may have to delete those two packages manually from `~/.emacs.d/.local/packages/elpa`

**Comment by Emiller88** [comment]
I think the issue is that they're no longer packaged seperately, they're just rolled into solidity mode.

**Comment by hlissner** [comment]
Now that #1157 has been merged, I'll consider this resolved. Thanks for letting me know and again for the PR!
