### ISSUE TITLE
Strange behavior on terminal input when j is pressed

### ISSUE THREAD

**Issue by zeronone** [hlissner/doom-emacs#1156]
### Observed behavior

Write a simple program that reads input from stdin and prints it back. I tried [this](https://stackoverflow.com/questions/13780209/user-input-c-programming) and [this](https://doc.rust-lang.org/book/ch02-00-guessing-game-tutorial.html). After running the program, if the `j` key is pressed, a `^?j` is also entered at the same time.

<img width="517" alt="screen shot 2019-02-06 at 23 21 01" src="https://user-images.githubusercontent.com/1908865/52347695-eeebb900-2a65-11e9-8e3d-81585916d6f6.png">

- It doesn't happen in normal terminal emulator
- It still happens even if I change the shell, (tried both bas, zsh)
- Describe key shows that `j` like other keys is mapped to `term-send-raw`

### System information

<details>
<summary>Click to expand</summary>

- OS: darwin (x86_64-apple-darwin17.5.0)
- Emacs: 26.1 (May 30, 2018)
- Doom: 2.0.9 (develop 1676cc56e314053ffc4205e175f151e56905a678)
- Graphic display: t (daemon: nil)
- System features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS
- Details:
  ```elisp
  elc count: 0
  uname -a:  Darwin LF02Q331602A90M.local 18.0.0 Darwin Kernel Version 18.0.0: Wed Aug 22 20:13:40 PDT 2018; root:xnu-4903.201.2~1/RELEASE_X86_64 x86_64
  modules:   (:feature eval (evil +everywhere) file-templates (lookup +devdocs +docsets) (syntax-checker +childframe) workspaces :completion company (ivy +fuzzy +childframe) :ui deft doom doom-dashboard doom-modeline evil-goggles fci hl-todo nav-flash treemacs (popup +all +defaults) unicode vi-tilde-fringe vc-gutter window-select :editor format multiple-cursors rotate-text :emacs dired ediff electric hideshow imenu term vc :tools ansible docker editorconfig gist macos make magit pdf tmux upload wakatime :lang cc common-lisp data emacs-lisp go (myhaskell +hie) idris javascript lua (markdown +pandoc) nix ocaml (org +attach +babel +capture +export +present) perl purescript python rest ruby rust scala (sh +fish) swift web :config default)
  packages:  (company-lsp (evil-matchit :recipe (evil-matchit :fetcher github :repo redguardtoo/evil-matchit :commit 7d65b4167b1f0086c2b42b3aec805e47a0d355c4)) haskell-mode lsp-haskell lsp-mode lsp-ui (org-wiki :recipe (org-wiki :fetcher github :repo caiorss/org-wiki)))
  exec-path: (~/.cargo/bin/ /usr/local/bin/ /usr/bin/ /bin/ /usr/sbin/ /sbin/ /opt/X11/bin/ /Applications/Wireshark.app/Contents/MacOS/ ~/.sdkman/candidates/springboot/current/bin/ ~/.sdkman/candidates/maven/current/bin/ ~/.sdkman/candidates/java/current/bin/ ~/.sdkman/candidates/gradle/current/bin/ ~/.gem/ruby/2.5.0/bin/ /usr/local/opt/mysql@5.6/bin/ ~/.gem/bin/ ~/scripts/ /usr/local/opt/coreutils/libexec/gnubin/ ~/.cargo/bin/ ~/.cabal/bin/ ~/.ghcup/bin/ ~/.local/bin/ ~/bin/ ~/Library/Android/sdk/tools/ ~/Library/Android/sdk/platform-tools/ ~/n/bin/ /usr/local/opt/go/libexec/bin/ ~/go/bin/ /usr/local/Cellar/emacs-plus/26.1/libexec/emacs/26.1/x86_64-apple-darwin17.5.0/)
  ```
</details>

**Comment by hlissner** [comment]
As an evil user, it's possible that evil-escape is to blame. Try adding `(after! evil-escape (add-to-list 'evil-escape-excluded-major-modes 'term-mode))` to your `~/.doom.d/config.el` and see if this resolves your issue.

**Comment by zeronone** [comment]
That indeed solved the problem. Thanks a lot.

**Comment by hlissner** [comment]
Happy to help! As of 02a3f81 this fix is included in Doom. Thanks for letting me know!
