### ISSUE TITLE
Where is "doom refresh"

### ISSUE THREAD

**Issue by haji-ali** [hlissner/doom-emacs#1158]
Hello, the wiki says that whenever I modify the `doom!` block. But there doesn't seem to be a doom executable in bin. Is the documentation old? If so, what should I do when changing my `doom!` block? How do I make sure the autloads are regenerated?

**Comment by hlissner** [comment]
It sounds like you're on the `master` branch, where the `bin/doom` executable doesn't exist. I'd recommend switching over to `develop`. It is over 4k commits ahead of master; many issues have been resolved there.

If you're dead set on sticking to `master`, the equivalent to `bin/doom refresh` is to run `make` from `~/.emacs.d`.

**Comment by haji-ali** [comment]
Thanks, I didn't notice that develop is the active branch.

**Comment by Hitomi98** [comment]
how do I switch over to the develop branch?

**Comment by hlissner** [comment]
`git clone https://github.com/hlissner/doom-emacs ~/.emacs.d`

If it still clones `master`, you have some odd configuration in your `~/.gitconfig`. In which case, be explicit about what branch you want:

```
git clone -b develop https://github.com/hlissner/doom-emacs ~/.emacs.d
```

For an already-cloned repo:

```
cd ~/.emacs.d
git checkout develop
```
