### ISSUE TITLE
mu4e spell check

### ISSUE THREAD

**Issue by haji-ali** [hlissner/doom-emacs#1167]
I have the email app enabled in Doom with spell-checking and I noticed that when composing a message if  my pointer moves from the text body to the message header, spell checking is disabled, but then if my pointer moves back to the text body, spell checking is enabled again (because of the hook in `mu4e-compose-mode-hook`). Because flyspell is very slow, this means that for long messages I have to wait while the buffer is being scanned before gaining back control of emacs.

Is there a way to fix this? Spell checking should really be enabled only once when first entering compose mode.

**Comment by hlissner** [comment]
It appears org-mu4e is to blame. It switches the buffer to org-mode when your cursor is below `--text follows this line--`. If you are willing to get rid of this feature, this is easily resolved (at the cost of writing your emails in org-mode) with:

```elisp
(remove-hook 'mu4e-compose-mode-hook #'org-mu4e-compose-org-mode)
```

I'm afraid there's little else that can be done. Switching major modes is a very destructive operation; it deletes a lot of buffer-local state, making it impractical to persist minor modes through major mode changes, so Emacs simply disables them. So long as flyspell-mode has to be restarted, you will feel that pause as it initializes.

A possible alternative: write them in markdown and [using mu4e-action-view-in-browser to preview your messages beforehand](https://emacs.stackexchange.com/questions/44657/render-markdown-in-mu4e-buffers).

**Comment by haji-ali** [comment]
Thanks. I opted to disable org-mode editing as you suggested. However, I just want to check, in my case the "pause" while spell-checking is a second or so while the pointer visually traverses every character in my buffer. 
My machine is not slow by any stretch. So is this normal?

**Comment by hlissner** [comment]
It is normal, unfortunately. It's a combination of flyspell's design, the slow-to-initialize background processes (ispell/aspell/hunspell) that flyspell employs, and Emacs lacking a decent mechanism for concurrency. Your machine definitely isn't the bottleneck here.
