### ISSUE TITLE
Org-mode errors on fresh install.

### ISSUE THREAD

**Issue by haji-ali** [hlissner/doom-emacs#1169]
I am having a very weird problem on my emacs 26.1, and the latest version of doom on `develop` branch.
I have the following `~/.doom.d/init.el` file

```
(doom!  :lang org)
```

I then ran `doom quickstart` and installed all the packages. Then I create a file `tmp.org` and typed

```
* One
* Two
```

Finally, I moved my pointer to `One` and called `org-refile` but got the following error.

```
Debugger entered--Lisp error: (invalid-function org-preserve-local-variables)
  org-preserve-local-variables("Copied: Subtree(s) with 6 characters")
  org-copy-subtree(1 nil t)
  org-refile(nil)
  funcall-interactively(org-refile nil)
  call-interactively(org-refile record nil)
  command-execute(org-refile record)
  execute-extended-command(nil "org-refile" #("org-refil" 0 9 (ws-butler-chg chg)))
  funcall-interactively(execute-extended-command nil "org-refile" #("org-refil" 0 9 (ws-butler-chg chg)))
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```

Is anyone else experiencing this issue?

**Comment by hlissner** [comment]
It sounds like a byte-compilation issue. Try `bin/doom compile :plugins` to recompile the org-plus-contrib package.

**Comment by haji-ali** [comment]
Indeed. That fixed it!

Could you please explain what you think the issue was? I tried multiple times to clean my doom directory and running `doom quickstart` but with the same result. It seems I *have* to compile the plugins afterwards.
