### ISSUE TITLE
Projectile-files search results are "reversed"

### ISSUE THREAD

**Issue by CThuleHansen** [hlissner/doom-emacs#1172]
First of all, thank you for a great editor. I switched from spacemacs, and the freezing has stopped! I am most grateful!

Now to my issue - I am using helm as search engine (the default config when I started using doom emacs), and the search results when using projectile-find-files seems to be reversed somehow. For example, if I search for KAL, then I get the following order of search results:
```
src/data/haskellKAL/Internal/file.hs
src/data/haskellKAL/Internal/file2.hs
src/data/haskellKAL/Internal/headers/file3.h
src/haskellKAL.hs
```

I would expect `src/haskellKAL.hs` to be the first, or for the cursor to start at the bottom.
Is it some configuration that I have overlooked in doom-emacs? It seems like something most people would be annoyed about, so it makes me wonder whether I am doing something wrong.

**Comment by CodyWilson** [comment]
Reversing the order seems to be something on the Helm "won't fix" list.
https://github.com/emacs-helm/helm/issues/362

That said, some redditor created a method to do it, you might give it a try.
https://www.reddit.com/r/emacs/comments/3asbyn/new_and_very_useful_helm_feature_enter_search/

**Now, here's another alternative**.

Use Ivy instead.

`+ivy/projectile-find-file` from what I've seen already puts it in the order you want.

And if you want to flip it, there's a variable to flip it.
https://github.com/abo-abo/swiper/commit/9b13aa466e3370b52e536c7c1a290d924d488ee9

At least I think anyway.

**Comment by CThuleHansen** [comment]
So ivy does actually not do it in the way I desire, it does the same.
However, with ivy I can go to the last entry by going over the top, which was not possible with helm. Thank you!
