### ISSUE TITLE
Wrong type argument: windowp, popup

### ISSUE THREAD

**Issue by EHaake** [hlissner/doom-emacs#1173]
Hi there, intermediate vimmer here attempting to move to emacs, hopefully for the last time.  My issues may be simply due to extreme ignorance so please be gentle. I love everything about DOOM emacs and so desperately want to get it to be my editor of choice.

I'm on a mac os Mojave (10.14.3) and installed emacs and DOOM via the instructions on the DOOM emacs [Getting Started](https://github.com/hlissner/doom-emacs/wiki/Getting-Started) page. I'm on the develop branch btw.

I've searched far and wide before submitting this issue, but I'm not perfect so I may have missed something.  I've also installed and reinstalled emacs-plus via homebrew.

### Observed behavior

Upon opening emacs, I get the DOOM emacs splash screen with no errors and everything looks great. But the moment I try to run almost any command, including the ones of the splash screen such as 'open org-agenda' with SPC o a, or even simply typing 'M-x', I get an empty minibuffer with the error: 

**Wrong type argument: windowp, popup**

![image](https://user-images.githubusercontent.com/20587371/52895160-5216d300-316b-11e9-97be-91e66643792d.png)

![image](https://user-images.githubusercontent.com/20587371/52895248-73c48a00-316c-11e9-87e1-c1f4ae52b98b.png)

<details>
<summary>Running Doom Doctor results in ...</summary>

```

Emacs v26.1
Doom v2.0.9 (81e30dc1)
shell: /bin/zsh
Compiled with:
  JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS
  MODULES THREADS LCMS2
uname -a:
  Darwin Eriks-MacBook-Pro.local 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20
  20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64

Checking your OS...
Checking your fonts...
Checking gnutls/openssl...
Testing your root certificates...
Checking for GNU/BSD tar...
Checking your enabled modules...


Everything seems fine, happy Emacs’ing!
```
</details>

<details>
<summary> Running 'make autoloads' results in:</summary>

```
Initializing modules
Deleted old autoloads.el
Generating new autoloads.el
✓ Scanned core/autoload/ui.el
✓ Scanned core/autoload/scratch.el
✓ Scanned core/autoload/projects.el
✓ Scanned core/autoload/packages.el
✓ Scanned core/autoload/message.el
⚠ Ignoring core/autoload/line-numbers.el
✓ Scanned core/autoload/hydras.el
✓ Scanned core/autoload/help.el
✓ Scanned core/autoload/files.el
✓ Scanned core/autoload/editor.el
✓ Scanned core/autoload/debug.el
✓ Scanned core/autoload/cli.el
✓ Scanned core/autoload/cache.el
✓ Scanned core/autoload/buffers.el
✓ Scanned modules/completion/company/autoload.el
✓ Scanned modules/completion/helm/autoload/posframe.el
✓ Scanned modules/completion/helm/autoload/helm.el
✓ Scanned modules/completion/helm/autoload/evil.el
✓ Scanned modules/config/default/autoload/evil.el
✓ Scanned modules/config/default/autoload/default.el
✓ Scanned modules/editor/multiple-cursors/autoload/evil-mc.el
✓ Scanned modules/editor/rotate-text/autoload.el
✕ Nothing in modules/emacs/electric/autoload.el
✓ Scanned modules/emacs/hideshow/autoload.el
✓ Scanned modules/emacs/vc/autoload/vc.el
✓ Scanned modules/emacs/vc/autoload/evil.el
✓ Scanned modules/feature/eval/autoload/settings.el
✓ Scanned modules/feature/eval/autoload/repl.el
✓ Scanned modules/feature/eval/autoload/evil.el
✓ Scanned modules/feature/eval/autoload/eval.el
✓ Scanned modules/feature/evil/autoload/folds.el
✓ Scanned modules/feature/evil/autoload/files.el
✓ Scanned modules/feature/evil/autoload/evil.el
✓ Scanned modules/feature/evil/autoload/advice.el
✓ Scanned modules/feature/file-templates/autoload.el
✓ Scanned modules/feature/lookup/autoload/lookup.el
✓ Scanned modules/feature/lookup/autoload/evil.el
✓ Scanned modules/feature/lookup/autoload/docsets.el
✓ Scanned modules/feature/snippets/autoload/snippets.el
✕ Nothing in modules/feature/snippets/autoload/settings.el
✓ Scanned modules/feature/snippets/autoload/evil.el
✓ Scanned modules/feature/syntax-checker/autoload.el
✓ Scanned modules/feature/workspaces/autoload/workspaces.el
✓ Scanned modules/feature/workspaces/autoload/evil.el
✓ Scanned modules/lang/emacs-lisp/autoload.el
✓ Scanned modules/lang/markdown/autoload.el
✓ Scanned modules/lang/org/autoload/tables.el
✓ Scanned modules/lang/org/autoload/org.el
✓ Scanned modules/lang/org/autoload/org-present.el
✓ Scanned modules/lang/org/autoload/org-link.el
✓ Scanned modules/lang/org/autoload/org-capture.el
✓ Scanned modules/lang/org/autoload/org-attach.el
⚠ Ignoring modules/lang/org/autoload/ipython.el
✓ Scanned modules/lang/sh/autoload.el
✓ Scanned modules/ui/doom-dashboard/autoload.el
✓ Scanned modules/ui/doom-modeline/autoload.el
✓ Scanned modules/ui/hl-todo/autoload.el
✓ Scanned modules/ui/nav-flash/autoload.el
✓ Scanned modules/ui/popup/autoload/settings.el
✓ Scanned modules/ui/popup/autoload/popup.el
✓ Scanned modules/ui/treemacs/autoload.el
✓ Scanned modules/ui/vc-gutter/autoload.el
✓ Scanned modules/ui/vi-tilde-fringe/autoload.el
✓ Expanded module autoload paths
✓ Generated autodefs
✓ Clean up autoloads

Deleted old autoloads.pkg.el
Initializing modules
✓ Cached package state
✓ Package autoloads included
✓ Removed load-path/auto-mode-alist entries

Finished!
```
</details>

### Expected behavior

Something other than the error **Wrong type argument: windowp, popup** and an empty minibuffer appearing after entering a command such as **SPC f d** or even simply **M-x**

### Steps to reproduce
1.  install emacs and DOOM emacs via the instructions on the DOOM emacs [Getting Started](https://github.com/hlissner/doom-emacs/wiki/Getting-Started) page. 

2. Run emacs

3. enter a command such as **SPC f d** or **M-x**

**Comment by hlissner** [comment]
Could you do `M-x toggle-debug-on-error` and then recreate the error? This will pop up a backtrace buffer. Please copy the contents of that buffer here (or into a pastebin, preferably).

**Comment by EHaake** [comment]
The problem is I can't, since even invoking ```M-x``` on it's own results in the error I described.

**Comment by hlissner** [comment]
Then try starting emacs with `emacs --debug-init`; that will be equivalent to `M-x toggle-debug-on-error`

**Comment by EHaake** [comment]
Ok I tried running emacs with ```emacs --debug-init``` and then trying ``` SPC f r ``` and I just see an empty buffer like this: 
![image](https://user-images.githubusercontent.com/20587371/52895429-31e91300-316f-11e9-8284-8a7d88f43622.png)

**Comment by EHaake** [comment]
I'm thinking it may be a problem with my system, but I have no idea what.  I've successfully installed spacemacs in the past but am having major problems with it now as well...

**Comment by hlissner** [comment]
Ah, I found the issue. 93132e4 should fix it. Please update and let me know if that isn't the case.

```sh
cd ~/.emacs.d
git pull
bin/doom refresh
```

**Comment by EHaake** [comment]
That worked! Thanks so much!
