### ISSUE TITLE
doom|highlight-non-default-indentation breaks coloring in helm 

### ISSUE THREAD

**Issue by haji-ali** [hlissner/doom-emacs#1179]
I just updated to the latest version of develop and all coloring in helm buffers seem to be gone.
I pinned it down the commit to this one e051909 (if I checkout to the commit right before it, helm coloring comes back). But I am not sure of the exact reason. 

I think this piece of code breaks helm coloring, but before that particular commit, it wasn't being executed on my setup because I have `indent-tabs-mode` is `nil` (the default value).

Right now, I fixed it like this
```
(remove-hook 'after-change-major-mode-hook #'doom|highlight-non-default-indentation)
```

**Comment by hlissner** [comment]
cee851f should hopefully address this. I've modified `doom|highlight-non-default-indentation` to be less aggressive. Please update and let me know if that isn't the case and I'll reopen this issue.

Thanks for letting me know!
