### ISSUE TITLE
FAQ: Typos

### ISSUE THREAD

**Issue by duianto** [hlissner/doom-emacs#1180]
Found a typo in the FAQ, a quick spell check of the whole FAQ found some more. A quick check of the other wiki pages didn't find any more.

## 1

https://github.com/hlissner/doom-emacs/wiki/FAQ#why-such-a-complicated-package-management-system

In the second sentence of:
> 3. Stability: I used Cask before this. It would error out with cyrptic errors depending on the version of Emacs I used and the alignment of the planets. No more.

cyrptic -> cryptic

## 2

https://github.com/hlissner/doom-emacs/wiki/FAQ#why-such-a-complicated-package-management-system

The first word in:
> 5. Seperation of concerns: I want package management and configuration to be separate. It makes it easier to grok modules and their dependencies.

Seperation -> Separation

## 3

https://github.com/hlissner/doom-emacs/wiki/FAQ#how-is-dooms-startup-so-fast

In the forth bullet points first sub bullet point. In the second sentence:
>Emacs won’t load your packages’ autoloads files. This may be distastrous to some especially silly geese, but not to Doom. Doom defines its own with use-package.

distastrous -> disastrous

## 4

https://github.com/hlissner/doom-emacs/wiki/FAQ#remove-vimevil-for-a-more-vanilla-emacs-experience

The third word from the end:
2. Run make to clean up lingering dependencies and refresh yuor autoloads file.

yuor -> your

**Comment by hlissner** [comment]
I've fixed these typos. Thanks for bringing them to my attention!
