### ISSUE TITLE
cc module feature +lsp work wrong

### ISSUE THREAD

**Issue by chengyi** [hlissner/doom-emacs#1187]
My private config doesn't have `+lsp` feature, but it install cquery and other package.

My private config is https://github.com/chengyi/doom-emacs-private-config

**Comment by chengyi** [comment]
I check the code:
``` emacs-lisp
(if (featurep! +lsp)
    (package! cquery)
  (when (package! irony)
    (package! irony-eldoc)
    (when (featurep! :feature syntax-checker)
      (package! flycheck-irony))
    (when (featurep! :completion company)
      (package! company-irony)
      (package! company-irony-c-headers)))
  (when (package! rtags)
    (when (featurep! :completion ivy)
      (package! ivy-rtags))
    (when (featurep! :completion helm)
      (package! helm-rtags))))
```

if `lsp` feature is not enabled, it will install irony rtags releated packages. can make this package optional again?

**Comment by hlissner** [comment]
I haven't figured out how to deal with the flags, but in the meantime you disable irony/rtags with: 

```elisp
(package! irony :disable t)
(package! rtags :disable t)
;; or
(disable-packages! irony rtags)
```

in `~/.doom.d/packages.el`.

**Comment by chengyi** [comment]
@hlissner thanks a lot
