### ISSUE TITLE
Workspace buffer not showing all buffers

### ISSUE THREAD

**Issue by haji-ali** [hlissner/doom-emacs#1189]
I noticed that calling `+ivy/switch-workspace-buffer` does not show all the buffers that I opened in the current workspace. Specifically, any temporary buffers are not included (for example buffers that are created when I edit a block with Org-mode). Is there a way to include these buffers in `+ivy/switch-workspace-buffer`?

**Comment by hlissner** [comment]
It is intentional that persp-mode not include "unreal" buffers in the workspace. If you try `SPC b B` (`ivy-switch-buffer`), it'll show you all buffers. 

You can try adding this to your `~/.doom.d/config.el` to include temporary buffers in the current workspace:

```elisp
(after! persp-mode
  (remove-hook 'persp-add-buffer-on-after-change-major-mode-filter-functions #'doom-unreal-buffer-p))
```
