### ISSUE TITLE
calfw grid does not extend to the whole buffer

### ISSUE THREAD

**Issue by Pentaquark1** [hlissner/doom-emacs#1190]
I tried the =Calendar App. This is what it looks like for me:
![screen](https://user-images.githubusercontent.com/42049801/53277593-e6051380-3704-11e9-87b7-9921c1591158.png)

Unfortunately the grid does not dynamically extend to the whole buffer, as would be expected from the vanilla version.
This also occurs if one does not use the calendar app, but instead only installs the calfw package. 
It seems like some other package is messing with the layout here, any idea how to fix this?

**Comment by hlissner** [comment]
Are you able to reproduce this in vanilla Emacs? Here's how you can easily test it (from GUI Emacs):

1. Open the vanilla sandbox (`SPC h E` or `M-x doom/open-vanilla-sandbox`)
2. Type in:

   ```elisp
   (require 'calfw)
   ```
3. Press `C-c C-c` to open the vanilla instance of Emacs
4. Open calfw

**Comment by haji-ali** [comment]
I have the opposite problem where the calendar is so big that part of the month is hidden. I tried with vanilla emacs and didn't have an issue there.

**Comment by Pentaquark1** [comment]
This is really confusing. If I follow the above steps, and the problem with the static grid persists.
I tried it yesterday without any doom, just a fresh new .emacs.d and getting calfw from melpa.
There the grid will adept to buffer size..

**Comment by hlissner** [comment]
As of #1294, this has been resolved. Let me know if that isn't the case!

Thanks to @jscott22 for looking into this.
