### ISSUE TITLE
Open private configuration doesn't work if directory is a symlink

### ISSUE THREAD

**Issue by zeronone** [hlissner/doom-emacs#1191]
### Observed behavior

Invoking `default/find-in-config` from doom dashboard `SPC f p` doesn't work if `~/.doom.d` is a symlink. My `~/.doom.d` is configured as `doom.d -> myfiles/dotfiles/config/home/.doom.d`. It shows the following message.

```
Directory `~/myfiles/dotfiles/home/.doom.d/' does not exist! Create it? (y or n) n
```

### Expected behavior

Can it follow the symlink if any directories on the path is symlinked?

### System information

<details>
<summary>Click to expand</summary>

- OS: darwin (x86_64-apple-darwin17.5.0)
- Emacs: 26.1 (May 30, 2018)
- Doom: 2.0.9 (develop 88f50bbdec4e59dce7c122148c7a2c7d65bcacb9)
- Graphic display: t (daemon: nil)
- System features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS
- Details:
  ```elisp
  elc count: 0
  uname -a:  Darwin LF02Q331602A90M.local 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64
  modules:   (:feature eval (evil +everywhere) file-templates (lookup +devdocs +docsets) (syntax-checker +childframe) workspaces :completion company (ivy +fuzzy +childframe) :ui deft doom doom-dashboard doom-modeline evil-goggles fci hl-todo nav-flash treemacs (popup +all +defaults) unicode vi-tilde-fringe vc-gutter window-select :editor format multiple-cursors rotate-text fold :emacs dired electric imenu term vc :tools ansible docker editorconfig gist macos make magit pdf tmux upload lsp :lang cc common-lisp data emacs-lisp go (myhaskell +hie) idris (javascript +lsp) lua (markdown +pandoc) nix ocaml (org +attach +babel +capture +export +present) perl purescript python rest ruby (rust +lsp) scala (sh +fish) swift web :config default)
  packages:  (company-lsp (evil-matchit :recipe (evil-matchit :fetcher github :repo redguardtoo/evil-matchit :commit 7d65b4167b1f0086c2b42b3aec805e47a0d355c4)) haskell-mode lsp-haskell lsp-mode lsp-ui (org-wiki :recipe (org-wiki :fetcher github :repo caiorss/org-wiki)))
  exec-path: (~/.cargo/bin/ /usr/local/bin/ /usr/bin/ /bin/ /usr/sbin/ /sbin/ /opt/X11/bin/ /Applications/Wireshark.app/Contents/MacOS/ ~/.sdkman/candidates/springboot/current/bin/ ~/.sdkman/candidates/maven/current/bin/ ~/.sdkman/candidates/java/current/bin/ ~/.sdkman/candidates/gradle/current/bin/ ~/.gem/bin/ ~/scripts/ /usr/local/opt/coreutils/libexec/gnubin/ ~/.cargo/bin/ ~/.cabal/bin/ ~/.ghcup/bin/ ~/.local/bin/ ~/bin/ ~/Library/Android/sdk/tools/ ~/Library/Android/sdk/platform-tools/ ~/n/bin/ /usr/local/opt/go/libexec/bin/ ~/go/bin/ /usr/local/Cellar/emacs-plus/26.1/libexec/emacs/26.1/x86_64-apple-darwin17.5.0/)
  ```
</details>

**Comment by ar1a** [comment]
It works fine for me. Maybe macos specific?

https://ptpb.pw/CD2i.webm

**Comment by haji-ali** [comment]
Maybe you're missing the '.' in the symlink name

**Comment by ar1a** [comment]
`.doom.d -> dotfiles/emacs/.doom.d`

**Comment by zeronone** [comment]
I tried it on Ubuntu, and it worked fine; so I think mac specific.

**Comment by hlissner** [comment]
@zeronone Are you certain it's a symlink and not an alias?

**Comment by zeronone** [comment]
I use `stow` to manage the symlinks. Just to double confirm, I manually created the symlink, and the issue still persisted.

<img width="919" alt="screen shot 2019-02-24 at 10 29 55" src="https://user-images.githubusercontent.com/1908865/53293851-51430880-381f-11e9-9593-f7910bdb1b38.png">

I have only tested with emacs 26.1 though.

**Comment by zeronone** [comment]
I am sorry, it seems to be cache problem. I changed the directory structure once, the one showing in doom was the old one. I deleted the `recentf` file from `.local/cache`, but the old directory was still there.

It was my mistake. I will close the issue.

**Comment by zeronone** [comment]
Deleting the whole `.local/cache` directory, did remove the old pointer to the `.doom.d/init.el` file :)
