### ISSUE TITLE
Disable +flycheck-popup-mode in lsp-ui buffers.

### ISSUE THREAD

**Issue by ar1a** [hlissner/doom-emacs#1192]
with lsp-ui, lsp-ui-sideline displays the error on the side of the screen. with popup-mode on, it displays in a popup AND on the side of the screen.

Considering the popup is often misaligned and whatnot, I think the sensible choice would be to disable popups.

A quick hack was 
```lisp
(after! rust-mode
  (remove-hook! flycheck-mode #'+flycheck-popup-mode))
```

**Comment by hlissner** [comment]
Good catch. Try this and let me know if it works just as well:

```elisp
    (defun +lsp|disable-flycheck-popup-mode-maybe ()
      "TODO"
      (when (and (bound-and-true-p lsp-ui-mode) lsp-ui-sideline-enable)
        (+flycheck-popup-mode -1)))
    (add-hook '+flycheck-popup-mode-hook #'+lsp|disable-flycheck-popup-mode-maybe)
```

**Comment by delan** [comment]
Works for me! (thanks @ar1a for opening this on my behalf)

**Comment by hlissner** [comment]
Understood. This is now in Doom as of 899c4b8. Thanks for bringing this to my attention!
