### ISSUE TITLE
Missing character sets during various make installs of brew Emacs

### ISSUE THREAD

**Issue by Vvkmnn** [hlissner/doom-emacs#1198]
### Observed behavior

Been testing `doom make` on a bunch of emacs builds to see what works with software like [chunkwm](https://github.com/koekeishiya/chunkwm), and discovered the following errors on this formulae:

### Expected behavior

This looks more like the fault of the guy who built it leaving some extra shit in the path, but I'm not smart enough to figure out how to sidestep it or clean it up. Maybe there's a way to find the charsets dependency locally? 

### Steps to reproduce

* [`emacs-mac-spacemacs-icon`](https://github.com/railwaycat/homebrew-emacsmacport/blob/master/Casks/emacs-mac-spacemacs-icon.rb) 

Cask of a [Macport buid](https://github.com/railwaycat/homebrew-emacsmacport), best compatability, won't play nice with Doom:

```bash

~/.emacs.d remotes/origin/develop~1
$  make
Warning: arch-dependent data dir '/Users/travis/build/railwaycat/build-macport/emacs-source/tmproot/libexec/em
Warning: arch-independent data dir '/Users/travis/build/railwaycat/build-macport/emacs-source/tmproot/share/em
Warning: Lisp directory '/Users/travis/build/railwaycat/build-macport/emacs-source/tmproot/share/emacs/26.1/li
Error: charsets directory not found:
/Users/travis/build/railwaycat/build-macport/emacs-source/tmproot/share/emacs/26.1/etc/charsets
Emacs will not function correctly without the character map files.
Please check your installation!
make: *** [all] Error 1
```

* [`emacs-mac-spacemacs-icon-snapshot`](https://github.com/railwaycat/homebrew-emacsmacport/blob/master/Casks/emacs-mac-spacemacs-icon.rb)

Similar issue, more Arch-y flavor.

```bash
~/.emacs.d remotes/origin/develop~1
$  make                                                                                         
Warning: arch-dependent data dir '/Users/travis/build/railwaycat/build-macport/emacs-head/tmproot/libexec/emacs/26.1.92/x86_64-apple-darwin16.7.0/': No such file or directory
Warning: arch-independent data dir '/Users/travis/build/railwaycat/build-macport/emacs-head/tmproot/share/emacs/26.1.92/etc/': No such file or directory
Warning: Lisp directory '/Users/travis/build/railwaycat/build-macport/emacs-head/tmproot/share/emacs/26.1.92/lisp': No such file or directory
Error: charsets directory not found:
/Users/travis/build/railwaycat/build-macport/emacs-head/tmproot/share/emacs/26.1.92/etc/charsets
Emacs will not function correctly without the character map files.
Please check your installation!
make: *** [all] Error 1
```

* [`emacs`](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/emacs.rb)

Smoothest install by far, with added default open into GUI from CLI with `emacs` and `emacsclient`. 

* [`emacs-plus`](https://github.com/d12frosted/homebrew-emacs-plus)

Same as above but no CLI, but with better decoration.

### System information

<details>
<summary>Click to expand</summary>

```
Doom Doctor
Emacs v26.1
Doom v2.0.9 (n/a)
shell: /usr/local/bin/zsh
Compiled with:
  NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS
uname -a:
  Darwin vBook 18.5.0 Darwin Kernel Version 18.5.0: Sun Feb 10 23:38:43 PST 2019;
  root:xnu-4903.250.336.0.1~14/RELEASE_X86_64 x86_64

Checking your OS...
Checking your fonts...
Checking gnutls/openssl...
Testing your root certificates...
Checking for GNU/BSD tar...
Checking your enabled modules...
Loading /Users/v/.emacs.d/core/autoload/cache...


Everything seems fine, happy Emacs’ing!
```
</details>

**Comment by jbharat** [comment]
I got the charset error as well on railwaycat emacsmacport. To get rid of it I had to install the cask version `brew cask install emacs-mac`. But it still didn't play well with doom-emacs. 

The best is emacs-plus at the moment I think. But mouse-over in chunkwm wont work(well it works if you move the mouse very slowly over the edges of emacs) with emacs-plus.

**Comment by hlissner** [comment]
I believe this is a known issue upstream: https://github.com/railwaycat/homebrew-emacsmacport/issues/21

**Comment by hlissner** [comment]
It appears the issue has been resolved upstream. Let me know if that isn't the case and I'll reopen this issue.
