### ISSUE TITLE
:cd not working

### ISSUE THREAD

**Issue by cosarara** [hlissner/doom-emacs#1208]
### Observed behavior

The :cd command doesn't work, and instead gives the following error:

    funcall-interactively: Wrong number of arguments: ((t) nil "Change `default-directory' with `cd'." (interactive (list (if (evil-ex-p) (progn (evil-ex-file-arg))))) (cd input)), 1 [2 times]

I'm using the develop branch, and I have a clean clone & quickstart from today.

`M-x cd` does work.

### Expected behavior

:cd should change directory like in vim.

### Steps to reproduce

1. Clone repo
2. switch to `develop` branch
3. `~/.emacs.d/bin/doom quickstart`
4. Run emacs
5. type `:cd whatever`, then return. `:cd` with no arguments fails the same way.

### System information

<details>
<summary>Click to expand</summary>

```
- OS: gnu/linux (x86_64-pc-linux-gnu)
- Emacs: 26.1 (Jul 05, 2018)
- Doom: 2.0.9 (develop d0533fe99cf30c54ea0cd9006c1ee6f46d55e5f3)
- Graphic display: t (daemon: nil)
- System features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LIBSYSTEMD LCMS2
- Details:
  ```elisp
  elc count: 0
  uname -a:  Linux evangelion 4.20.11-zen2-1-zen #1 ZEN SMP PREEMPT Fri Feb 22 13:13:05 UTC 2019 x86_64 GNU/Linux
  modules:   (:feature debugger eval (evil +everywhere) file-templates (lookup +docsets) snippets workspaces :completion company ivy :ui doom doom-dashboard doom-modeline doom-quit evil-goggles hl-todo nav-flash treemacs (popup +all +defaults) vc-gutter vi-tilde-fringe window-select :editor fold multiple-cursors rotate-text :emacs dired electric imenu vc :tools flycheck flyspell :lang common-lisp data elixir emacs-lisp javascript lua markdown (org +attach +babel +capture +export +present) perl php python racket rust (sh +fish) web :config default)
  packages:  n/a
  exec-path: (~/.nix-profile/bin ~/.local/share/perl5/bin ~/.local/share/perl5/perls/perl-5.28.0/bin ~/perl5/bin ~/.cargo/bin ~/.cargo/bin ~/.rakudobrew/bin ~/coses/go/bin ~/.gem/ruby/2.6.0/bin ~/.npm-packages/bin ~/.local/bin ~/bin ~/.gem/ruby/2.1.0/bin /opt/devkitpro/tools/bin /bin /usr/bin /usr/local/bin /usr/local/sbin ~/.local/share/flatpak/exports/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /usr/lib/plan9/bin ~/dotfiles/nvim/fzf/bin /usr/lib/emacs/26.1/x86_64-pc-linux-gnu)
```
</details>

**Comment by hlissner** [comment]
Good catch. Looks like a typo was to blame! I've pushed a fix in aa9c4f6. Please update and let me know if that isn't the case.

Thanks for letting me know!

**Comment by cosarara** [comment]
`:cd` with no arguments should probably be equivalent to `:cd ~` instead of giving an error (as it is in vim, or the shell). But yes, it works with arguments now, thank you.

**Comment by hlissner** [comment]
Good idea! It's been rectified in ad837e6.
