### ISSUE TITLE
Restart emacs commands don't focus the new instance

### ISSUE THREAD

**Issue by flatwhatson** [hlissner/doom-emacs#1210]
I have the following at the top of `~/.doom.d/init.el` to auto-focus the frame at startup:

    (select-frame-set-input-focus (selected-frame))

This fixes `M-x restart-emacs` leaving the new emacs instance in the background.  Maybe it should go somewhere in doom's init?

**Comment by hlissner** [comment]
Try adding this to your config.el:

```elisp
(defun +workspaces-restore-last-session (&rest _)
  (select-frame-set-input-focus (selected-frame))
  (add-hook 'emacs-startup-hook #'+workspace/load-session :append))
```

**Comment by flatwhatson** [comment]
That works for `+workspace/restart-emacs-then-restore`, but not `restart-emacs`.

**Comment by hlissner** [comment]
I've investigated this issue again and tested `restart-emacs` on MacOS and a few distros of linux to find that focus is not an issue. What OS are you experiencing this issue on?

**Comment by flatwhatson** [comment]
Interesting!  I'm using KDE on ArchLinux, no custom window-managers or unusual focus settings.  I've re-tested with the latest doom develop and a fresh quickstart, definitely still experience the issue.  Focus is left with whatever I was using previously, ie. alt-tabbing between emacs and firefox, running `doom/restart` in emacs, I'm left back in firefox with the new emacs instance in the background.

**Comment by hlissner** [comment]
I believe this was resolved some time ago, when I reactivated the menubar for macOS users (when disabled, macOS assumes the window is non-application frame, and so won't automatically give it focus). Let mw know if that isn't the case and I'll reopen it.
