### ISSUE TITLE
Symbol's value as variable is void: after-init-time at installation

### ISSUE THREAD

**Issue by andyafter** [hlissner/doom-emacs#1212]
When I was running `make install` I got `Symbol's value as variable is void: after-init-time`. Any ideas?

**Comment by hlissner** [comment]
`after-init-time` is a C variable defined in Emacs. The only possibilities I can think of are a) you have the wrong (and/or old version of) `emacs` in your `PATH` or b) your build of Emacs is broken.

**Comment by andyafter** [comment]
Yeah, sorry for asking again, but in OSX how could I point emacs to the newly installed emacs. I installed it with what I downloaded from GNU. But it seems that the terminal always point it to /usr/bin/emacs, even if I set alias, `make install` still fails.

**Comment by jbharat** [comment]
@andyafter The best way to install emacs on osx is to use emacs-plus from https://github.com/d12frosted/homebrew-emacs-plus. Make sure you remove all previous emacs first. brew will set it up in the right path. You just need to link it to /Applications folder to see it as an application.

**Comment by hlissner** [comment]
You can point to a specific Emacs binary when using `bin/doom` using the `EMACS` envvar:

```sh
EMACS=/usr/local/bin/emacs doom install
```

But you need a more permanent solution. I'd suggest installing Emacs through homebrew, as it sets everything up correctly.

That, or add the `emacs` executable of your currently installed Emacs to your `PATH`.
