### ISSUE TITLE
Installing a private local package

### ISSUE THREAD

**Issue by haji-ali** [hlissner/doom-emacs#1213]
How do I add a local package using doom's "package!"? I tried the following line in my `/.doom.d/packages.el`

     (package! my-private-package :recipe (:fetcher file :path (eval 'doom-private-dir))

and I have "my-private-package.el" in `/.doom.d/`. Then I ran `doom refresh` successfully. But then when I restarted emacs I got the error

    condition-case: Error in a Doom startup hook: doom|init-theme, (error "Unable to find theme file for ‘doom-one’")

To fix the issue, I had to remove the `package!` line from my `packages.el` and rerun `doom refresh`

Am I doing something wrong?

**Comment by hlissner** [comment]
That's an unconventional use for `package!`, and will break in subtle ways that are a tad long to list here. I don't think this is what you want to do, so here are a few alternatives:

### 1. Using `load!`

1. Put the package in `~/.doom.d/lisp/my-private-package.el`
2. And from `~/.doom.d/config.el` load it with `(load! "lisp/my-private-package")`

### 2. Using `require`

Assuming it's a package with proper structure (has all the required package headers and a `(provide 'my-private-package)`), then:

1. Put the package in `~/.doom.d/lisp/my-private-package.el`
2. In `~/.doom.d/config.el`, add `~/.doom.d/lisp` to `load-path`: `(add-to-list 'load-path (expand-file-name "lisp" doom-private-dir))`
3. And require it `(require 'my-private-package)`.

### 3. Use `def-package!` (or `use-package`, either is fine)

The same as no. 2, except you load it with `def-package!`:

```elisp
(def-package my-private-package
  :config
  ;; configure your package here
  )
```

### 4. Symlink/copy packages into subfolders

Copy or symlink packages into subdirectories under `~/.doom.d/lisp`, e.g. 

```
~/.doom.d/
    lisp/
        package-1/*.el
        package-2/*.el
        package-3/*.el
```

Add these packages to your `load-path`:

```elisp
(let ((default-directory doom-private-dir))
  (normal-top-level-add-to-load-path "packages"))
```

And now they can be loaded with `require` or `def-package!`/`use-package`.
