### ISSUE TITLE
Don't display messages when the minibuffer is active

### ISSUE THREAD

**Issue by Luis-Henriquez-Perez** [hlissner/doom-emacs#1215]
During `doom-debug-mode` a lot of messages pop up during startup about what DOOM is doing, which is great. I love that.

Particularly during incremental loading, however, I don't like it when messages pop up while the minibuffer is active. I find it disorienting.

So I thought that maybe doing something this is a good idea:
`(let ((inhibit-message (active-minibuffer-window)) (message "Incrementally Loading..."))`

This way if you're doing something in the minibuffer messages are logged but not displayed. Otherwise, messages are displayed as normal.

Does this sound like a good idea?

**Comment by hlissner** [comment]
I've been playing with a log function that would do exactly this. You've inspired me to commit it. f6cc264 should resolve this issue for you. Thanks for bringing it to my attention!
