### ISSUE TITLE
doom-modeline showing buffer is modified when it's not

### ISSUE THREAD

**Issue by haji-ali** [hlissner/doom-emacs#1224]
I just pulled the latest changes and the `doom-modeline` seems to be working in almost all situations. However, there are various cases that trip it. One situation I was able to pin down is the following

Open a new file, writing some long text, call `fill-paragraph` on the text, buffer is modified and `doom-modeline` reflects that, save the file, buffer is not modified and `doom-modeline` reflects that. Now, if I call `fill-paragraph` again on the same text, `doom-modeline` shows that the buffer was modified (even though the text hasn't changed), now if save the buffer a message shows "(No changes need to be saved)" but `doom-modeline` keeps showing that the buffer is modified no matter how many times I save.

I am not sure where to report this, but since I use `doom`, I am not 100% sure if the source of the issue is `doom-modeline` by itself or some combination of features in `doom`.

**Comment by hlissner** [comment]
The issue indeed originates from [in the doom-modeline package](https://github.com/seagle0128/doom-modeline). Please report it there. I'll investigate it over the weekend and send in a PR if I figure it out. That is, if seagle0128 doesn't fix it first.

**Comment by haji-ali** [comment]
Fixed in latest doom-modeline [commit](https://github.com/seagle0128/doom-modeline/commit/a35a403c9930192e38a916eb33168aca511be919)
