### ISSUE TITLE
lookup definition work abnormal

### ISSUE THREAD

**Issue by chengyi** [hlissner/doom-emacs#1226]
Hi @hlissner ,
I wrote the code below to use gtags as my backend:
``` emacs-lisp
(set-lookup-handlers! '(c-mode c++-mode java-mode)
    :definition #'helm-gtags-find-tag-other-window
    :references #'helm-gtags-find-rtag)
```

but recently i find when I cancel the gtags lookup pop window use `ctrl-g`, emacs pop up `xref-find-definition` again. It seems strange, please give me a hand.

**Comment by chengyi** [comment]
@hlissner I find de4b18a commit lead to this behavior, when i press `ctrl-g`, emacs consider the lookup failed, then it runs next function.

**Comment by hlissner** [comment]
This will work around the issue:

```elisp
  (set-lookup-handlers! '(c-mode c++-mode java-mode)
    :async t
    :definition #'helm-gtags-find-tag-other-window
    :references #'helm-gtags-find-rtag)
```

The reason for this is, if you abort from the command, the lookup module will assume the handler has failed and try the next. I'll have to come up with a way for it to detect getting aborted.

**Comment by chengyi** [comment]
@hlissner sorry, add `:async t` doesn't work around this issue

**Comment by hlissner** [comment]
As of 8bfa5a3, this should be resolved. C-g/ESC should abort lookup commands properly. Please update and let me know if that isn't the case then I'll reopen this issue. Thanks for bringing it to my attention!

**Comment by chengyi** [comment]
@hlissner sorry, this fix doesn't complete work for this issue. it only works when the minibuffer show, but after press `enter`, the popup window shows, then press `ctrl-g`, emacs still run next hook. :-<

**Comment by hlissner** [comment]
Is this still an issue? I am unable to reproduce it.

**Comment by chengyi** [comment]
@hlissner in the latest code, as said above, add `:async t` solve this issue. Thank you.:rofl:
