### ISSUE TITLE
flycheck keeps reporting c++11 errors

### ISSUE THREAD

**Issue by haji-ali** [hlissner/doom-emacs#1230]
I have the `:lang cc` and `:tools flycheck` modules enabled. If I open a C++ file I get many flycheck errors about c++11 features. According to `lang/cc/README.org` the `+cc-default-compiler-options` should have the c++11 compile options, which it does. Its value is:
```
((c-mode)
 (c++-mode "-std=c++1z")
 (objc-mode))
```

I also tried adding a hook to set the flycheck standard
```
(add-hook 'c++-mode-hook (lambda () (setq
                                     flycheck-gcc-language-standard "c++11"
                                     flycheck-clang-language-standard "c++11")))
```

But nothing seems to work. I have no JSON database file.

**Comment by hlissner** [comment]
Is this still an issue?

**Comment by haji-ali** [comment]
I am not sure to be honest. It's a problem that I noticed while writing C++ code which I haven't done in a while and I can't remember the project that caused this problem.

I will close the issue for now and reopen it if it comes up again (next time with more details).
