### ISSUE TITLE
All menu items list as "prefix"

### ISSUE THREAD

**Issue by huyiqun** [hlissner/doom-emacs#1240]
Hello! I just cloned the develop branch of doom emacs and did a fresh reinstall on Mac. When pressing SPC, the popping menu shows `prefix` instead of a particular item name for all prefix alphabets, e.g. `f` used to show `file`, `q` used to show `session`, now they are all just `prefix`

![image](https://user-images.githubusercontent.com/10877536/54092226-09180000-4360-11e9-84de-e1f98fed700d.png)

I tried with doom doctor, but it says everything is fine. I also tried a fresh install on Linux, same thing happened. Any idea?

**Comment by shanavas786** [comment]
related to #1234

**Comment by hlissner** [comment]
As of dadcd29 this should be resolved. Let me know if that isn't the case and I'll reopen this issue. Thanks for letting me know!

**Comment by DonHugo69** [comment]
The issue seems to persist, however only the `doom-leader-alt-key` keybinds seem to be affected.
![image](https://user-images.githubusercontent.com/10484857/56125800-0a010a80-5f7a-11e9-8a3f-3b4c1feee36d.png)
