### ISSUE TITLE
markdown-mode steals m-b when using plain key bindings

### ISSUE THREAD

**Issue by enko** [hlissner/doom-emacs#1241]
### Observed behavior

I'm using doom without any fancy key rebindings (just plain old emacs keybindings) and markdown-mode uses `m-b` for `markdown-insert-bold` (https://github.com/hlissner/doom-emacs/blob/develop/modules/lang/markdown/config.el#L33). `m-b` is normaly bound to `backward-word` which I use very very often when composing markdown files.

### Expected behavior

I would expect the cursor to go one word backward when pressing m-b.

### Steps to reproduce

Use the attached [init.el.txt](https://github.com/hlissner/doom-emacs/files/2951580/init.el.txt) and open a markdown file, go to the end of file and press m-b.

### System information

- OS: gnu/linux (x86_64-pc-linux-gnu)
- Emacs: 26.1.91 (Jan 11, 2019)
- Doom: 2.0.9 (develop c4ed1031a5ea12b192cf41f61cc8858b3790c0de)
- Graphic display: t (daemon: nil)
- System features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS LIBSYSTEMD LCMS2
- Details:
  ```elisp
  elc count: 0
  uname -a:  Linux fly-tsc 4.20.11-1-MANJARO #1 SMP PREEMPT Wed Feb 20 23:19:36 UTC 2019 x86_64 GNU/Linux
  modules:   (:feature eval file-templates (lookup +docsets) :tools flyspell flycheck :feature workspaces :completion company (ivy +fuzzy) :ui doom doom-dashboard doom-modeline doom-quit evil-goggles fci hl-todo nav-flash (popup +all +defaults) pretty-code vc-gutter vi-tilde-fringe window-select :editor multiple-cursors rotate-text :emacs dired electric imenu vc :tools ansible docker editorconfig gist magit rgb vterm :lang data emacs-lisp (haskell +intero) javascript markdown (org +attach +babel +capture +export +present) (sh +zsh) :config default)
  packages:  (activity-watch-mode calfw calfw-org dockerfile-mode emojify forge org-alert org-super-agenda ripgrep wakatime-mode wanderlust)
  exec-path: (/usr/local/sbin /usr/local/bin /usr/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /usr/lib/emacs/26.1.91/x86_64-pc-linux-gnu ~/.nvm/versions/node/v10.14.1/bin)
  ```

**Comment by hlissner** [comment]
As of cdd6587 this should be fixed. Thanks for letting me know!

**Comment by enko** [comment]
Thanks for fixing this so swiftly!
