### ISSUE TITLE
Icons in initial menu are broken on Archlabs Linux

### ISSUE THREAD

**Issue by atmichalak** [hlissner/doom-emacs#1248]
### Observed behavior

When I load doom emacs, the icons in the landing page are incorrect. I have some sort of conflict with my install of Archlabs Linux.

https://imgur.com/a/WfmyEh7

### Expected behavior
Icons should be as shown in the github page. My Manjaro install has the correct icons.

### Steps to reproduce

You might need an Archlabs installation to reproduce or a similar Arch spin.

### System information

<details>
<summary>Click to expand</summary>
- OS: gnu/linux (x86_64-pc-linux-gnu)
- Emacs: 26.1 (Jul 05, 2018)
- Doom: 2.0.9 (develop 093dddff4a169f1f657b03d0bb83dea84f6fe1be)
- Graphic display: t (daemon: nil)
- System features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LIBSYSTEMD LCMS2
- Details:
  ```elisp
  elc count: 0
  uname -a:  Linux nordvind 5.0.0-arch1-1-ARCH #1 SMP PREEMPT Mon Mar 4 14:11:43 UTC 2019 x86_64 GNU/Linux
  modules:   (:feature eval (evil +everywhere) file-templates (lookup +docsets) snippets :tools flyspell flycheck :feature workspaces :completion company helm :ui doom doom-dashboard modeline doom-quit evil-goggles hl-todo nav-flash treemacs (popup +all +defaults) vc-gutter vi-tilde-fringe window-select :editor multiple-cursors rotate-text :emacs dired electric :editor fold :emacs imenu vc :lang data emacs-lisp markdown (org +attach +babel +capture +export +present) (sh +fish) :config default)
  packages:  n/a
  exec-path: (/usr/lib/jgmenu ~/bin ~/.cargo/bin /usr/local/bin /usr/bin /bin /usr/local/sbin /opt/flutter/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /opt/flutter/bin /sbin /usr/sbin /usr/lib/emacs/26.1/x86_64-pc-linux-gnu)
  ```
</details>

**Comment by hlissner** [comment]
Did you run `M-x all-the-icons-install-fonts` after installing Doom?

If you're using other means to install the same fonts, I'm afraid I can't help you there.

**Comment by FirstLoveLife** [comment]
all-the-icons-install-fonts failed to install some fonts on my manjaro in the past. I fix the icon issue via installinging from aur/github(manually). Maybe you can give them a try

**Comment by hlissner** [comment]
@FirstLoveLife The all-the-icons project was recently acquired a new maintainer. During this transitional period, `all-the-icons-install-fonts` was broken, but has since been fixed.

**Comment by FirstLoveLife** [comment]
@hlissner Good to know! https://github.com/domtronn/all-the-icons.el/issues/133

**Comment by hlissner** [comment]
I will close this, since this was resolved upstream. If that isn't the case, feel free to follow up here.
