### ISSUE TITLE
Warning: couldn’t find the :emacs ediff module

### ISSUE THREAD

**Issue by bittopaz** [hlissner/doom-emacs#1251]
### Observed behavior

I get "Warning: couldn’t find the :emacs ediff module" every time I run `doom u`

### Expected behavior

No warning.

### Steps to reproduce

run `doom u` on my MacBook.

### System information

<details>
<summary>Click to expand</summary>

Warning: couldn’t find the :emacs ediff module
Generating Doom info...
Warning: couldn’t find the :emacs ediff module
- OS: darwin (x86_64-apple-darwin18.2.0)
- Emacs: 26.1 (Mar 04, 2019)
- Doom: 2.0.9 (develop 093dddff4a169f1f657b03d0bb83dea84f6fe1be)
- Graphic display: nil (daemon: nil)
- System features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2
- Details:
  ```elisp
  elc count: 0
  uname -a:  Darwin FVFXG11XHV2J 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64
  modules:   (:feature eval (evil +everywhere) file-templates (lookup +docsets) snippets workspaces :completion company ivy :ui doom doom-dashboard evil-goggles hl-todo modeline nav-flash treemacs (popup +all +defaults) pretty-code vc-gutter vi-tilde-fringe window-select :editor fold (format +onsave) multiple-cursors rotate-text :emacs dired electric eshell imenu term vc :tools docker editorconfig flycheck flyspell lsp magit terraform :lang data emacs-lisp (go +lsp) javascript latex markdown (org +attach +babel +capture +export +present) python ruby (sh +fish) web :app rss :config default)
  packages:  ((go-rename :modules ((:private))) (puppet-mode :modules ((:private))))
  exec-path: (/usr/local/bin /usr/bin /bin /usr/sbin /sbin /usr/local/sbin ~/.emacs.d/bin ~/go/bin /usr/local/Cellar/emacs-plus/26.1/libexec/emacs/26.1/x86_64-apple-darwin18.2.0)
  ```
</details>

**Comment by hlissner** [comment]
This is because the ediff config has been merged into Doom core; the module no longer exists. Remove `:emacs ediff` from your `doom!` block in `~/.doom.d/init.el` and this warning will go away.
