### ISSUE TITLE
Key sequence M-j starts with non-prefix key ESC (on M-x and some SPC prefixes)

### ISSUE THREAD

**Issue by xstrtok** [hlissner/doom-emacs#1255]
### Observed behavior

After commit 1f23eecdc877d3ece2330fb8ac4fbbe30c00e5a0, I keep getting this error, for example when issuing `SPC f r`, `SPC p p` or `M-x`.

For now, I just apply the following:

```
diff --git a/modules/config/default/+evil-bindings.el b/modules/config/default/+evil-bindings.el
index ae0f578a..6bbb90eb 100644
--- a/modules/config/default/+evil-bindings.el
+++ b/modules/config/default/+evil-bindings.el
@@ -278,7 +278,7 @@
             "C-j"     #'company-select-next-or-abort
             "C-k"     #'company-select-previous-or-abort
             "C-s"     (λ! (company-search-abort) (company-filter-candidates))
-            "ESC"     #'company-search-abort)
+            [escape]     #'company-search-abort)
           ;; TAB auto-completion in term buffers
           :map comint-mode-map "TAB" #'company-complete))
```
and it seems that it's working fine.

### Expected behavior

Not get the error.

### Steps to reproduce

After a new `git clone`, follow the appropriate steps and issue `SPC f r` or `M-x`.

### System information

<details>
OpenBSD 6.5 GENERIC.MP#760 amd64

```
- OS: berkeley-unix (x86_64-unknown-openbsd)
- Emacs: 26.1 (Mar 01, 2019)
- Doom: 2.0.9 (develop a669406cad46f96ac842906f150391d5a5886ebf)
- Graphic display: t (daemon: nil)
- System features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK DBUS GSETTINGS NOTIFY GNUTLS LIBXML2 FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK2 X11 THREADS LCMS2
- Details:
  ```elisp
  elc count: 0
  uname -a:  OpenBSD morgoth.lan 6.5 GENERIC.MP#760 amd64
  modules:   (:feature eval (evil +everywhere) file-templates (lookup +docsets) snippets workspaces :completion company (helm +fuzzy) :ui doom doom-dashboard doom-quit evil-goggles hl-todo indent-guides modeline nav-flash treemacs (popup +all +defaults) unicode vc-gutter vi-tilde-fringe window-select :editor fold multiple-cursors parinfer rotate-text :emacs dired electric eshell imenu vc :tools editorconfig flycheck flyspell magit password-store pdf :lang clojure data emacs-lisp latex markdown (org +attach +babel +capture +export +present +publish) perl (sh +fish) :app email irc :config default)
  packages:  ((geiser :modules ((:private))) (paredit :modules ((:private))) (pretty-mode :modules ((:private))) (w3m :modules ((:private))) (wttrin :modules ((:private))) (evil-leader :modules ((:private))) (nov :modules ((:private))) (chicken-scheme :modules ((:private))) (scheme-complete :modules ((:private))) (vlf :modules ((:private))) (ranger :modules ((:private) (:emacs . dired))) (transmission :modules ((:private))) (mu4e-alert :modules ((:private))) (helm-lobsters :modules ((:private))) (poet-theme :modules ((:private))) (tao-theme :modules ((:private))) (restclient :modules ((:private))) (request-deferred :modules ((:private))) (spacemacs-theme :modules ((:private))) (nyan-mode :modules ((:private))))
  exec-path: (~/bin /bin /sbin /usr/bin /usr/sbin /usr/X11R6/bin /usr/local/bin /usr/local/sbin /usr/games /usr/local/plan9/bin ~/.local/bin ~/go/bin ~/.emacs.d-doom/bin /usr/local/jdk-1.8.0/bin /usr/local/libexec/emacs/26.1/amd64-unknown-openbsd)
  ```

</details>

p.s. As I have the opportunity, thank you for this truly amazing setup.
While I'm getting into scheme, I still don't have the knowledge to hack elisp code (yet). I suspect somehow the issue is PEBCAC.

[edit]: fix code block

**Comment by wudang-monk** [comment]
I had a similar issue that made emacs unusable but the cause was not the same. It was because of some tweaks I had in place for evil-collections. It did happen in the company package though, guessing some change in evil-collections made my key translations screw things up.

**Comment by xstrtok** [comment]
> I had a similar issue that made emacs unusable but the cause was not the same. It was because of some tweaks I had in place for evil-collections. It did happen in the company package though, guessing some change in evil-collections made my key translations screw things up.
> 
> This only happened on macos though, no issues in linux.

Thank you for pointing me to the right direction. It was indeed something in my config related to evil-collection. I managed to pinpoint the problem when I was calling `(evil-collection-init)`.

Confirming that when commenting the above, I get no errors.

Once more, thank you so much and sorry for the noise.
