### ISSUE TITLE
expand-region keybinding is missing 

### ISSUE THREAD

**Issue by chengyi** [hlissner/doom-emacs#1256]
after split evil/emacs keybinding, the origin `v/vtrl-v` seems was deleted.  I create #1243 to fix it.
@hlissner

**Comment by hlissner** [comment]
Sorry to say, expand-region was removed from Doom core in 4fbf7a26 and restored only for non-evil users in 66d75936. As the package doesn't exist for evil users, it doesn't make sense to have default keybinds associated with it for evil users.

**Comment by chengyi** [comment]
thanks for your reply. I got it. @hlissner

**Comment by ferhaterata** [comment]
Could you explain how to expand and contract region in evil mode?

**Comment by ocharles** [comment]
It's probably worth saying what the alternative is here: use things like `va(`.
