### ISSUE TITLE
projectile-ag: Package ’ag’ is not available

### ISSUE THREAD

**Issue by shuxiao9058** [hlissner/doom-emacs#1260]
as title.

**Comment by hlissner** [comment]
Do you have either `:completion ivy` or `:completion helm` activated? Ivy+counsel provides `counsel-ag`, which is superior, and helm provides `helm-ag`. Both are available through `SPC / p` (i.e. `M-x +ivy/project-search` or `M-x +helm/project-search`).

**Comment by shuxiao9058** [comment]
my config:
```
       :completion
       (company
        +auto)          ; the ultimate code completion backend
       ivy               ; a search engine for love and life

```

**Comment by shuxiao9058** [comment]
> Both are available through `SPC / p` (i.e. `M-x +ivy/project-search` or `M-x +helm/project-search`)
works fine. but `projectile-ag` failed.

**Comment by ar1a** [comment]
from what i remember projectile-ag never worked, and counsel-ag and helm-ag were superior, and did the same thing anyways

**Comment by UndeadKernel** [comment]
Checking the obvious just in case:
The family of `ag` commands need the following binary installed: `the_silver_searcher`. I assume you have correctly installed it?

**Comment by shuxiao9058** [comment]
> Checking the obvious just in case:
> The family of `ag` commands need the following binary installed: `the_silver_searcher`. I assume you have correctly installed it?

of course, installed.

**Comment by thiagokokada** [comment]
I added `(package! ag)` and `(package! ripgrep)` to my `packages.el` or I would get `Package 'ag' is not available` or `Package 'ripgrep' is not available` while calling `projectile-ag` or `projectile-rg`. Of course, I have the binaries installed in my system.

I tought this was expect, bu maybe it is not.

**Comment by hlissner** [comment]
The issue is that Doom doesn't promote the use of `projectile-ag` or `projectile-rg`, because they are inferior to the ones it does promote: `+ivy/project-search` and `+helm/project-search`. I haven't decided what to do about this though.

**Comment by shelper** [comment]
i think `+ivy/ag` does not work as shown below, i am not sure if this is an issue with ivy or doom. 
confirmed on mac os and ubuntu,

<img width="594" alt="Screen Shot 2019-06-13 at 10 15 49 AM" src="https://user-images.githubusercontent.com/546163/59440057-545d0700-8dc4-11e9-9808-400a51723317.png">

**Comment by hlissner** [comment]
@shelper This will typically happen when the ag/rg process takes too long to respond, which can be the case if your shell config is especially slow to initialize (it has to fire off a new shell every time it invokes ag/rg to refresh your ivy results).

Common culprits for this are rbenv and pyenv. If you happen to use either (or any *env program), instead of `rbenv init` -- which is very slow to start -- use `rbenv init --no-rehash` instead.

**Comment by shelper** [comment]
i actually dont use either of them. 

projectile-ag actually works fine after install package ag.el

**Comment by hlissner** [comment]
@shelper Try this and let me know if it fixes your issue:

```elisp
;; in ~/.doom.d/config.el
(defun use-basic-shell (orig-fn &rest args)
  (let ((shell-file-name (or (executable-find "dash")
                             (executable-find "sh")
                             shell-file-name)))
    (apply orig-fn args)))
(advice-add #'+ivy-file-search :around #'use-basic-shell)
```

**Comment by shelper** [comment]
seems still cannot search with ag. 
just curious, so `ivy:ag` works with out `ag.el` right?

i remember it works on my system and recently the only thing i did is upgrade to emacs 26.2...

**Comment by hlissner** [comment]
Yes, `+ivy/project-search`, `+ivy/rg`, `+ivy/ag`, `+ivy:rg`, `+ivy:ag`, and so on all work without ag.el. Or at least, they should. They use the `counsel` package as their backend.

Perhaps you should try installing `ripgrep` and see if `+ivy/rg` works for you. It's possible this is an issue with `ag`.

**Comment by shelper** [comment]
yeah, you are right, ripgrep works

**Comment by hlissner** [comment]
Are you still experiencing those issues?
