### ISSUE TITLE
[feature request]TabNine

### ISSUE THREAD

**Issue by shuxiao9058** [hlissner/doom-emacs#1268]
[TabNine](https://tabnine.com/)

https://github.com/syl20bnr/spacemacs/issues/11867

**Comment by hlissner** [comment]
While impressive in theory, in practice I didn't find tabnine to be fast or useful enough to warrant including in Doom by default. Its config was also rather trivial (and thus, easy for users to set up themselves).

```elisp
(use-package! company-tabnine
  :after company
  :config
  (cl-pushnew 'company-tabnine (default-value 'company-backends)))
```

So I'm going to refuse this feature request. Perhaps I'll revisit it again in the future, once the project is more mature. Thanks for bringing it to my attention!
