### ISSUE TITLE
How to add global company-backend

### ISSUE THREAD

**Issue by shuxiao9058** [hlissner/doom-emacs#1269]
like TabNine, it seems  that

```
(with-eval-after-load 'company-mode
  (add-to-list 'company-backends #'company-tabnine)
)

```
not work.

**Comment by hlissner** [comment]
The package is `company`, not `company-mode`:

```elisp
(after! company
  (add-to-list 'company-backends 'company-tabnine))
```

**Comment by shuxiao9058** [comment]
no works with golang.

```
Value:
(company-lsp
 (:separate company-capf company-yasnippet)
 company-capf)
Original value was 
(company-bbdb company-eclim company-semantic company-clang company-xcode company-cmake company-capf company-files
              (company-dabbrev-code company-gtags company-etags company-keywords)
              company-oddmuse company-dabbrev)
Local in buffer main.go; global value is (company-capf)
```
My solution is:
```
(dolist (mode (list
               'c-mode
               'c++-mode
               'swift-mode
               'lisp-mode
               'emacs-lisp-mode
               'sh-mode
               'lua-mode
               'haskell-mode
               'go-mode
               'java-mode
               'python-mode
               ))
  (with-eval-after-load mode
    (add-to-list 'company-backends #'company-tabnine))
  )
```

**Comment by hlissner** [comment]
There are two problems with this. 

1. `with-eval-after-load`'s first argument is a package symbol, not a mode.

   + `c-mode`, `c++-mode` and `java-mode` are in the `cc-mode` package
   + `python-mode` is in the `python` package
   + `sh-mode` is in the `sh-script` package

   Many of these will not work.

2. You are adding to the global value of `company-backends`. You only need to add it once, not every time a package loads. Perhaps you meant to add it in a hook instead?

```elisp
(defun add-company-tabnine ()
  (add-to-list (make-local-variable 'company-backends) 'company-tabnine))

(add-hook 'c-mode-hook #'add-company-tabnine)
(add-hook 'c++-mode-hook #'add-company-tabnine)
(add-hook 'swift-mode-hook #'add-company-tabnine)
(add-hook 'lisp-mode-hook #'add-company-tabnine)
(add-hook 'emacs-lisp-mode-hook #'add-company-tabnine)
(add-hook 'sh-mode-hook #'add-company-tabnine)
(add-hook 'lua-mode-hook #'add-company-tabnine)
(add-hook 'haskell-mode-hook #'add-company-tabnine)
(add-hook 'go-mode-hook #'add-company-tabnine)
(add-hook 'java-mode-hook #'add-company-tabnine)
(add-hook 'python-mode-hook #'add-company-tabnine)
```

---

Anyway, I simply did `(setq company-backends '(company-tabnine company-capf))` and it worked fine. If it doesn't work, then likely something else in your config is interfering.

**Comment by fistR** [comment]
I'm having the same issue, i tried all of the above but no matter what I do the global company-backends is overridden by appending (anaconda-mode) to the beginning of it. I have (setq company-backends '(company-tabnine company-anaconda company-capf)) but the list always becomes ((company-anaconda) company-capf company-yasnippet company-tabnine company-anaconda). I can manually do kill-local-variable and then it will work fine but i can't seem to add kill-local-variable as a hook to python-mode, anaconda-mode, company-mode or anything else so far since what appends that always happens after. Any ideas?

**Comment by KVAnton-WEB** [comment]
its work: `(set-company-backend! 'c-mode-hook '(company-gtags))`
