### ISSUE TITLE
  projectile shows last project files list when switch to new project

### ISSUE THREAD

**Issue by chengyi** [hlissner/doom-emacs#1274]
### Observed behavior

  projectile shows last project files list when switch to new project

### Expected behavior

 projectile shows files of correct project

### Steps to reproduce

1. Open project A
2. Open project B using `SPC p p`

### System information

<details>
<summary>Click to expand</summary>

- OS: gnu/linux (x86_64-pc-linux-gnu)
- Emacs: 26.1 (7月 05, 2018)
- Doom: 2.0.9 (develop a085a8ccfa05a8f2f8ec2f254fd1d97f0ea1377b)
- Graphic display: t (daemon: nil)
- System features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LIBSYSTEMD LCMS2
- Details:
  ```elisp
  elc count: 0
  uname -a:  Linux prow-dev 4.19.28-1-MANJARO #1 SMP PREEMPT Sun Mar 10 08:32:42 UTC 2019 x86_64 GNU/Linux
  modules:   (:feature eval (evil +everywhere) file-templates (lookup +docsets) snippets workspaces :completion company helm :ui doom doom-dashboard doom-quit evil-goggles fci hl-todo modeline nav-flash treemacs (popup +all +defaults) vc-gutter vi-tilde-fringe window-select :editor fold multiple-cursors rotate-text :emacs dired electric imenu term vc :tools magit :lang cc data emacs-lisp java lua markdown (org +attach +babel +capture +export +present) python rust (sh +zsh) :config default)
  packages:  (gruvbox-theme helm-gtags cnfonts blog-admin (irony :disable t) (rtags :disable t))
  exec-path: (/usr/local/bin /usr/bin /bin /usr/local/sbin /opt/android-ndk /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /usr/lib/emacs/26.1/x86_64-pc-linux-gnu)
  ```

</details>

**Comment by chengyi** [comment]
@hlissner seems it's helm or helm-projectile's bug, because I switch to ivy, this bug disappeared

**Comment by ShaneKilkelly** [comment]
I have the same issue :+1:

**Comment by chengyi** [comment]
@hlissner I switch to prelude emacs, and it doesn't have this issue with same helm & helm-projectile-version

**Comment by chengyi** [comment]
@hlissner f18e1c0 introduce this issue

**Comment by hlissner** [comment]
I can reproduce this issue, but I do not understand it. Helm is somehow invoked from the wrong buffer or perspective. Ivy behaves correctly, `doom-project-find-file` behaves correctly, but helm is adament to ignore `default-directory`.

A possible workaround is:

```lisp
(setq +workspaces-switch-project-function #'ignore)
```

This way there is no problem, but you won't be immediately prompted to open a file after switching projects. You'd have to do so manually, with <kbd>SPC</kbd><kbd>SPC</kbd> (`+helm/projectile-find-file`).

**Comment by hlissner** [comment]
Also, reverting to/past f18e1c0 does not fix the issue. Nothing in that commit (or any of the adjacent ones) should cause this behavior.

**Comment by zeronone** [comment]
Might be related. When treemacs is open `SPC o p`, moving to a new workspace, (creating a new workspace doesn't change the project). (I use ivy)

**Comment by hlissner** [comment]
Are you still experiencing this issue? I can no longer reproduce this issue so I assume it's been fixed somewhere along the way.

**Comment by chengyi** [comment]
@hlissner in the latest code, this issue is fixed.
