### ISSUE TITLE
`emacs-snippets` to `~/.doom.d/snippets`: Workaround issues

### ISSUE THREAD

**Issue by pet-ro** [hlissner/doom-emacs#1275]
_Originally posted by @hlissner in https://github.com/hlissner/doom-emacs/issues/812#issuecomment-414508317_:
```
2. Clone https://github.com/hlissner/emacs-snippets to `~/.doom.d/snippets`
3. Run `~/.emacs.d/bin/doom refresh` (or `make` in `~/.emacs.d`)
```
When I tried this I get on OS Windows a warning:

```
>git clone https://github.com/hlissner/emacs-snippets  snippets
Cloning into 'snippets'...
[…]
Checking out files: 100% (2555/2555), done.
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'org-mode/struct_C'
  'org-mode/struct_c'
  'org-mode/struct_E'
  'org-mode/struct_e'
```

I recommend a renaming like. 
```
  'org-mode/struct_c_shifted'
  'org-mode/struct_c'
  'org-mode/struct_e_shifted'
  'org-mode/struct_e'
```` 

It seems to be a emacs convention to use lowercases first. 
That is the reason, why only uppercases get renamed here.

**Comment by hlissner** [comment]
This should've been reported [in the emacs-snippets repo](https://github.com/hlissner/emacs-snippets). That said, I've addressed it there by renaming these templates (hlissner/emacs-snippets@2c3b11e). Thanks for letting me know!
