### ISSUE TITLE
`set-popup-rule` interacts unfortunately with `flycheck`

### ISSUE THREAD

**Issue by Ptival** [hlissner/doom-emacs#1276]
On `develop` branch.

I tried to resize the default size of the `*Flycheck errors*` buffer with the following line in my `config.el`:
```
(set-popup-rule! "^\\*Flycheck errors\\*$" :side 'bottom :size 0.4)
```

While it works at resizing the buffer when it pops up, it has the unfortunate consequence of not focusing the buffer. That is, when there is a warning/error, and you type `SPC c x`:

- without this line in `config`, the `*Flycheck errors*` buffer takes the focus (i.e. your cursor moves to its first line),

- with this line in `config`, it does not appear to take focus, the cursor stays in the file that has the error.

I'm not sure whether the focus ever shifts, but gets stolen back, or whether the rule prevents the focus from shifting altogether.

<details>

```
- OS: darwin (x86_64-apple-darwin17.7.0)
- Emacs: 26.1 (Dec 16, 2018)
- Doom: 2.0.9 (develop 5e3c8c5f92ad724401f604802723467258de75b3)
- Graphic display: t (daemon: nil)
- System features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS
- Details:
  ```elisp
  elc count: 0
  uname -a:  Darwin machop 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64
  modules:   (:feature eval (evil +everywhere) file-templates (lookup +docsets) snippets workspaces :completion company ivy :ui doom doom-dashboard doom-quit evil-goggles hl-todo modeline nav-flash treemacs (popup +all +defaults) vc-gutter vi-tilde-fringe window-select :editor fold multiple-cursors rotate-text :emacs dired electric imenu vc :tools flycheck magit :lang assembly (cc +irony +rtags) coq data emacs-lisp (haskell +intero) idris javascript latex markdown nix ocaml (org +attach +babel +capture +export +present) purescript python racket rust (sh +fish) web :config default)
  packages:  n/a
  exec-path: (/usr/local/bin/ /usr/bin/ /bin/ /usr/sbin/ /sbin/ ~/.nix-profile/bin/ /nix/store/n2pvd392zqiaz75mwy4rpag44k3sb6cb-emacs-26.1/libexec/emacs/26.1/x86_64-apple-darwin17.7.0/)
  ```

</details>

**Comment by measpear** [comment]
You can try the following which shifts the focus to the flycheck popup window 
(set-popup-rule! "^\\*Flycheck errors\\*$" :side 'bottom :size 0.4 :select t)
