### ISSUE TITLE
How to add a lsp backends properly?

### ISSUE THREAD

**Issue by shuxiao9058** [hlissner/doom-emacs#1279]
such as lua lsp-backends? I add the lsp backends as follow:
``` elisp
(after! lsp
  (lsp-register-client
   (make-lsp-client :new-connection (lsp-stdio-connection (list
                                                           ;; "JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_192.jdk/Contents/Home"
                                                           "/usr/bin/java"
                                                           "-cp"
                                                            (expand-file-name (concat doom-private-dir "/.local/bin/EmmyLua-LS-all.jar" ))
                                                           "com.tang.vscode.MainKt"))
                    :major-modes '(lua-mode)
                    :server-id 'emmy-lua
                    :priority 0))
``` 

is this right?
and how to add hook to enable lsp mode?
``` elisp
(after! lua-mode
    (add-hook 'lua-mode-hook #'lsp!))
```
or add 
``` elisp
 (add-hook 'lua-mode-hook #'lsp!)
```
in config file.

**Comment by hlissner** [comment]
I'm not terribly familiar with defining LSP backends, so my insight is limited, but it looks correct to me.

As for enabling lsp, `(add-hook 'lua-mode-hook #'lsp!)` is good enough. `add-hook` doesn't require the hook to be defined.

**Comment by shuxiao9058** [comment]
```
(after! lua-mode
    (add-hook 'lua-mode-hook #'lsp!))
```
and 
```
 (add-hook 'lua-mode-hook #'lsp!)
```
which is best? The first one with `after!`sometimes  not works fine.

**Comment by hlissner** [comment]
The answer to your question was in my last response.

> As for enabling lsp, `(add-hook 'lua-mode-hook #'lsp!)` is good enough. add-hook doesn't require the hook to be defined

There is no need for `after!`.

**Comment by shuxiao9058** [comment]
thanks a lot！

**Comment by adamkruszewski** [comment]
You probably want to use (after! lsp-clients ...), it may not work with "after! lsp" alone.
