### ISSUE TITLE
No Info-scroll-up keybindings for info mode

### ISSUE THREAD

**Issue by SteamedFish** [hlissner/doom-emacs#1280]
`Info-scroll-up` is very important when reading emacs manuals. 

evil collection [bind this function](https://github.com/emacs-evil/evil-collection/blob/master/evil-collection-info.el#L53) to the <kbd>SPC</kbd> key.

How ever <kdb>SPC</kbd> is is used as leader key in doom emacs and this keybinding is unavaliable. 

An alternative way is to use <kbd>gj</kbd>, which binds to `Info-next`, to go to the next node. However when at the end of chapter the next node of the current chapter is unavaliable and there's no quick way to go to the first node of the next chapter, without `Info-scroll-up`.

**Comment by hlissner** [comment]
Evil provides `C-u` (up) and `C-d` (down) for scrolling in half-screens, and `C-f` (down) and `C-b` (up) for scrolling page-wise.

In fact, many of vim's scroll commands are made available by evil: http://vimdoc.sourceforge.net/htmldoc/scroll.html

**Comment by SteamedFish** [comment]
The differences between `evil-scroll-down` and `Info-scroll-up` is that `Info-scroll-up`  considering all nodes as one sequence while `evil-scroll-down` is not.

If I'm at the last section of chapter 3, and I want to jump to the first section of chapter 4, both `evil-scroll-down` and `Info-next` cannot do it, while `Info-scroll-up` can do it.

**Comment by SteamedFish** [comment]
personally I do things like this. But this is a very persional configuration. 

```lisp
  (map!
   :map Info-mode-map
   :n "j"    (lambda!
              (condition-case nil
                  (evil-next-line)
                (error (Info-scroll-up))))
   :n "k"    (lambda!
              (condition-case nil
                  (evil-previous-line)
                (error (Info-scroll-down))))
```
