### ISSUE TITLE
ivy cause emacs hangup

### ISSUE THREAD

**Issue by chengyi** [hlissner/doom-emacs#1281]
I use `ivy`, press `SPC f .` under home directory , it tries to index all files in `home`, cause too may disk io requests that make emacs hang up, is there any ideas to solve this?

**Comment by hlissner** [comment]
I suggest using <kbd>SPC</kbd> <kbd>.</kbd> instead, or remap <kbd>SPC</kbd> <kbd>f</kbd> <kbd>.</kbd> to `find-file`. 

<kbd>SPC</kbd> <kbd>f</kbd> <kbd>.</kbd> invokes `counsel-file-jump`, which will recursively search the file tree under the current directory.
