### ISSUE TITLE
feature: out of the box copy support on Windows

### ISSUE THREAD

**Issue by pet-ro** [hlissner/doom-emacs#1284]
# Observed behavior
- *copy and paste* on Windows does not work out of the box

# Fixed via  this add on to `/.doom/.config.el` 

```
(defmacro with-system (type &rest body)
  "Evaluate BODY if `system-type' equals TYPE."
  (declare (indent defun))
  `(when (eq system-type ',type)
     ,@body))

(with-system windows-nt
     ;; based on https://rufflewind.com/2014-07-20/pasting-unicode-in-emacs-on-windows
  (set-selection-coding-system 'utf-16-le) ; required to paste unicode in emacs on windows
     ;;
  (message "end of windows-nt specific configs."))
```

# Qs
- What would be the right place to embed this to the `doom-emacs` source,
   that this can work out of the box.

**Comment by hlissner** [comment]
37525bb should hopefully address this issue. Please update and let me know!
