### ISSUE TITLE
Javascript project requires git to be initialised in order for LSP to work

### ISSUE THREAD

**Issue by LoveSponge** [hlissner/doom-emacs#1295]
### Observed behavior

Nice and easy; I was trying to get LSP working, to no avail, looking at *Messages* i can see that TSServer was successfully started but complained "LSP :: app.js not in project".

I'm not an emacs guru at all but i'd imagine there is a setting somewhere that is telling LSP to look for the '.git' folder in order to initialise.

I've google for this for hours and found nothing, so i'm creating this issue.

### Expected behavior

LSP should initialise on the file? not the folder. If the file happens to be in a directory with other files of the same type then use them to add to itself.

I don't know...

*ahem*

Just that LSP should initialise with OR without the enclosing folder being a git project.

### Steps to reproduce

1. Create a folder with a JS file inside it.
2. Open the JS file (with typescript-language-server & typescript already installed with NPM)

See the *Messages* buffer *LSP :: x.js not in project*

3. run git init on the folder
4. restart emacs

LSP is working as expected.

## UPDATE

So while writing this i tried to reproduce the error - and deleted my .git folder, restarted emacs and LSP is working?!

I'm not sure if this is good or bad.

Confirmed the bug is prevalent on a fresh directory, thank god.

**Comment by hlissner** [comment]
LSP uses projectile to resolve the current project root. Projectile does this by looking for certain files and folders to indicate a project's root; `.git` is one of them. The `projectile-project-root-files`, `projectile-project-root-files-bottom-up` and `projectile-project-root-files-top-down-recurring` variables control what files it will search for and their precedence.

Here are two possible solutions to try:

1. `(add-to-list 'projectile-project-root-files "package.json")` 
2. `(setq lsp-auto-guess-root nil)` (then LSP will prompt you to specify a project root manually when it can't find one)

**Comment by hlissner** [comment]
After 3eaa57c and #1303, projectile should now recognize package.json as a project root indicator, which should resolve your issue. Let me know if that isn't the case and I will reopen this issue.

Thanks for bringing it to my attention!

**Comment by LoveSponge** [comment]
amazing - thank you so much!
