### ISSUE TITLE
Hang when scrolling with mouse

### ISSUE THREAD

**Issue by asamwow** [hlissner/doom-emacs#1301]
### Observed behavior
 
Emacs slows down when I scroll with mouse, and completely hangs when I scroll a lot.

### Expected behavior

Snappy scrolling with mouse.

### Steps to reproduce

1. Open file that is a couple pages long
2. attempt to scroll through it with the mouse quickly

### Profiler

Running emacs with the -q argument solves the issue, so I ran the profiler to see what was going wrong, but I think something is wrong with the profiler.

```
- command-execute                                                2212  97%
 - call-interactively                                            2212  97%
  - funcall-interactively                                        2212  97%
   - mwheel-scroll                                               2195  97%
    - scroll-down                                                  29   1%
     - eval                                                        26   1%
        doom-modeline-segment--buffer-position                      7   0%
      - doom-modeline-format--main                                  6   0%
       - format-mode-line                                           3   0%
        - eval                                                      3   0%
           doom-modeline-segment--major-mode                        3   0%
        doom-modeline-segment--major-mode                           3   0%
   + doom/toggle-profiler                                          17   0%
+ ...                                                              42   1%
  flycheck-popup-tip-delete-popup                                   4   0%

```

### System information

<details>
<summary>Click to expand</summary>

```
- OS: gnu/linux (x86_64-pc-linux-gnu)
- Emacs: 26.1 (Mar 17, 2019)
- Doom: 2.0.9 (develop cf4818e68915772150ca6d860fa0221c4cbe93b8)
- Graphic display: t (daemon: nil)
- System features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LIBSYSTEMD LCMS2
- Details:
  ```elisp
  elc count: 0
  uname -a:  Linux verulent 5.0.4-arch1-1-ARCH #1 SMP PREEMPT Sat Mar 23 21:00:33 UTC 2019 x86_64 GNU/Linux
  modules:   (:feature eval file-templates (lookup +docsets) snippets workspaces :completion company ivy :ui doom doom-dashboard modeline doom-quit evil-goggles hl-todo nav-flash treemacs (popup +all +defaults) vc-gutter vi-tilde-fringe window-select :editor fold format multiple-cursors rotate-text :emacs dired electric eshell imenu term vc :tools editorconfig flycheck flyspell magit password-store pdf vterm :lang cc clojure common-lisp csharp data emacs-lisp (java +meghanada) javascript latex lua markdown (org +attach +babel +capture +export +present) plantuml python qt (sh +fish) web :app email (write +wordnut +langtool) :config literate default)
  packages:  n/a
  exec-path: (/usr/local/bin /usr/bin /bin /usr/local/sbin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl ~/.rvm/bin /usr/lib/emacs/26.1/x86_64-pc-linux-gnu)
  ```
```
</details>

**Comment by UndeadKernel** [comment]
Scrolling in emacs can be CPU intensive depending on quite many factors.
Let's figure out what's causing the slowdowns for you:
1) The modeline: try disabling the modeline with `doom-modeline-mode` and scroll.
2) The fontification: disable fontification with `font-lock-mode` and scroll.

Did you see improvements with any of these two things?

**Comment by asamwow** [comment]
Thank you. Good ideas. I tried both of them, and performance is a little better and now the profiler makes more sense. However, something is still feels very wrong when compared to default emacs. Even with those two modes turned off, when I scroll with my scroll wheel it hangs or clearly drops frames. I also commented out my config file to make sure it was not a problem there.

**Comment by hlissner** [comment]
What major mode(s) are you testing this in? Does it occur in other modes? Some modes are faster than others.

Try disabling `highlight-numbers-mode` and `highlight-escape-sequences-mode`, then (if they are enabled) disable `rainbow-delimiters-mode` and `highlight-quoted-mode`, and see if that helps.

Other possibilities include: `flycheck-mode`, `visual-line-mode` (a big source of slow downs),  `git-gutter-mode`, `fill-column-indicator-mode`, and `highlight-indent-guides-mode` -- if they're enabled in that buffer.

> compared to default emacs

I'm afraid this isn't a helpful benchmark. The gap in complexity between vanilla Emacs and Doom is too wide. What's worse, Emacs scales quite poorly, so it's difficult to determine whether this is a failure of Emacs to perform at a base level, too much bloat stacked on by Doom, or your expectations are too high (e.g. you came from a modern editor).

**Comment by asamwow** [comment]
I appreciate your input. Your completely right. I was using fundamental, but the real problem is I should really be scrolling with the keyboard more and I have a terrible cpu. Thank you.
