### ISSUE TITLE
Marking within comment and doom/forward-to-last-non-comment-or-eol

### ISSUE THREAD

**Issue by ijacquez** [hlissner/doom-emacs#1306]
### Observed behavior

In `COMMIT_EDITMSG` (committing via *magit*), within the comments, marking (`C-space`), specifically after `#`, `C-e` does not move the cursor to the end of line.

I believe this is due to `doom/forward-to-last-non-comment-or-eol`.

Use case is to copy the filename of the file(s) to committed.

```
|# This is a comment inside COMMIT_EDITMSG
^
|
 \  Cursor is here. C-space then C-e works fine
```

```
#| This is a comment inside COMMIT_EDITMSG
 ^
 |
  \  Cursor is here. C-space then C-e works does NOT work. Nor does it work after any chars after the #.
```

### Expected behavior

`C-e` should work within comments (after `#`).

### Steps to reproduce

Explained above.

### System information

<details>
<summary>Click to expand</summary>

- OS: darwin (x86_64-apple-darwin18.0.0)
  
- Emacs: 26.1 (Oct 04, 2018)

- Doom: 2.0.9 (develop 390edee702f86d6f8c20d5934764a22c7b8959f8)
  
- Graphic display: t (daemon: nil)

- System features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2

<details>

  ```elisp
  env bootstrapper: envvar-file
  elc count: 0
  uname -a:  Darwin --- 18.0.0 Darwin Kernel Version 18.0.0: Wed Aug 22 20:13:40 PDT 2018; root:xnu-4903.201.2~1/RELEASE_X86_64 x86_64
  modules:   (:feature eval file-templates (lookup +docsets) snippets workspaces :completion company ivy :ui doom doom-quit evil-goggles hl-todo modeline nav-flash treemacs (popup +all +defaults) unicode vc-gutter vi-tilde-fringe window-select :editor fold multiple-cursors rotate-text :emacs dired electric imenu vc :tools editorconfig flycheck flyspell magit rgb :lang assembly common-lisp csharp data emacs-lisp lua markdown (org +attach +babel +capture +export +present) python (sh +fish) :config default)
  packages:  (window-numbering highlight-symbol magit-gitflow page-break-lines)
  exec-path: (/usr/local/bin /usr/bin /bin /usr/sbin /sbin /usr/local/share/dotnet ~/.dotnet/tools /Library/Frameworks/Mono.framework/Versions/Current/Commands /usr/local/Cellar/emacs-plus/26.1/libexec/emacs/26.1/x86_64-apple-darwin18.0.0/)
```

</details>

**Comment by hlissner** [comment]
I see the issue. `git-commit-mode` doesn't mark those as comments, it merely highlights them as such. consider that a `git-commit-mode` bug.

As of 2346737 this should be fixed. Let me know if that isn't the case and I will reopen this issue.

Thank you for the detailed bug report and for bringing it to my attention!
