### ISSUE TITLE
Unable to append keybindings for existing leader prefixes

### ISSUE THREAD

**Issue by siddharthshekar** [hlissner/doom-emacs#1308]
### Observed behavior

Some recent change over the last few days has removed the ability to add keybindings to existing prefixes. For example, `SPC c` has code related keybindings and I have code in my `config.org` to make `SPC c l` toggle commenting. Other pre-existing definitions `SPC c` disappear once config.el gets loaded.

### Expected behavior

Existing keybindings should not be overwritten. New keybindings should be appended to a given prefix.

### Steps to reproduce

1. Add the following line to config.el:
```  
      (map! :leader
        (:prefix ("c" . "code")
          :desc "Toggle comment" "l" #'evilnc-comment-or-uncomment-lines
          :desc "Copy and comment lines" "y" #'evilnc-copy-and-comment-lines))
```
2. Restart Emacs.
3. Press `SPC c`.

### System information

<details>
<summary>Click to expand</summary>

```
- OS: darwin (x86_64-apple-darwin18.2.0)
- Emacs: 26.1 (Feb 22, 2019)
- Doom: 2.0.9 (develop b7585e37aa16ac964e0a45f04d4c57476897c31e)
- Graphic display: t (daemon: nil)
- System features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2
- Details:
  elisp
  env bootstrapper: nil
  elc count: 0
  uname -a:  Darwin Siddharths-Work-MacBook-Pro.local 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64
  modules:   (:feature eval (evil +everywhere) file-templates (lookup +docsets) snippets workspaces :completion company helm :ui deft doom doom-dashboard doom-quit evil-goggles hl-todo modeline nav-flash treemacs (popup +all +defaults) vc-gutter vi-tilde-fringe window-select :editor fold multiple-cursors rotate-text :emacs dired electric imenu term vc :tools flycheck lsp magit :lang data emacs-lisp latex markdown (org +attach +babel +capture +present) (python +pyenv) (sh +fish) :config literate (default +bindings +snippets +evil-commands) sid)
  packages:  n/a
  exec-path: (/usr/bin /bin /usr/sbin /sbin /usr/local/Cellar/emacs-plus/26.1/libexec/emacs/26.1/x86_64-apple-darwin18.2.0)
```
</details>

**Comment by siddharthshekar** [comment]
Looks like ea3d9e2 is the offending commit.

**Comment by hlissner** [comment]
Judging from your `doom/info` you do not have `evil-nerd-commenter` installed, nor is it installed by Doom, and `map!` will ignore leader keybinds if the command doesn't exist (i.e. defined or autoloaded).

Side note: Doom uses the `evil-commentary` package for commenting, so `evil-nerd-commenter` isn't necessary. You can accomplish the same with:

```elisp
(map! :leader
      (:prefix "c"
        :desc "Toggle comment"         "l" #'evil-commentary-line
        :desc "Copy and comment lines" "y" #'evil-commentary-yank-line))
```

**Comment by hlissner** [comment]
I reverted ea3d9e2. This won't necessarily fix your problem. If you bind commands that are undefined, you will get void-function/commandp errors when you use that keybind, unless it is loaded by that point.

In any case, I'll consider this issue resolved. Let me know if you think that isn't the case and I will reopen it.

**Comment by siddharthshekar** [comment]
I do have evil-nerd-commenter installed in my packages.el and the commands work properly. Perhaps I was unclear in my description but these screenshots should help. They were both taken after pressing `SPC c`.
Before ea3d9e2
<img width="576" alt="Screen Shot 2019-04-06 at 11 09 11 AM" src="https://user-images.githubusercontent.com/1447996/55673428-f3adcd00-585c-11e9-9e7b-97f30eeaff87.png">

After ea3d9e2
<img width="477" alt="Screen Shot 2019-04-06 at 11 10 18 AM" src="https://user-images.githubusercontent.com/1447996/55673430-fa3c4480-585c-11e9-9273-e2d0f6405dcf.png">

It appears that this issue is still present in the latest develop so perhaps the revert didn't happen properly?

**Comment by hlissner** [comment]
I just pushed 1fab389, which should resolve this issue. Please update and let me know.

**Comment by siddharthshekar** [comment]
Works as intended now!
