### ISSUE TITLE
map! macro cause non-prefix error

### ISSUE THREAD

**Issue by chengyi** [hlissner/doom-emacs#1313]
after last update, emacs start with error 
`Error in private config: config.el, (error Key sequence u b starts with non-prefix key u)`  
because I add a keybinding in my config.el. the code is below:

``` emacs-lisp
    (map! :leader
          (:prefix ("u" . "personal")
            :desc "Open blog admin" "b" #'blog-admin-start))
```

is there a new keybinding method?

**Comment by hlissner** [comment]
`SPC u` is already bound to `universal-argument`. You'll need to unbind it first:

```elisp
(map! :leader
      "u" nil
      (:prefix ("u" . "personal")
        :desc "Open blog admin" "b" #'blog-admin-start))
```

**Comment by chengyi** [comment]
@hlissner got it! seems last update fix some bugs. :+1::+1:
