### ISSUE TITLE
Magit help (SPC g g ?) stopped working

### ISSUE THREAD

**Issue by thiagokokada** [hlissner/doom-emacs#1319]
### Observed behavior

Magit help (using `?` inside a Magit buffer `SPC g g`) stopped working with following error:

```
transient--ensure-infix-command: Suffix magit-ediff-dwim is not defined or autoloaded as a command
```

### Expected behavior

It should open a popup window with help showing Magit keys.

### Steps to reproduce

1. Open a Magit buffer with `SPC g g`
2. Call help with `?`

### System information

<details>
<summary>Click to expand</summary>

- OS: gnu/linux (x86_64-pc-linux-gnu)
- Emacs: 26.1 (mar 30, 2019)
- Doom: 2.0.9 (develop 138248ed03a0c4cfea5d4f8f9c2e5949f2054d95)
- Graphic display: t (daemon: nil)
- System features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LIBSYSTEMD
- Details:
  ```elisp
  env bootstrapper: nil
  elc count: 0
  uname -a:  Linux mikudayo-nubank 4.14.109 #1-NixOS SMP Wed Mar 27 05:13:56 UTC 2019 x86_64 GNU/Linux
  modules:   (:feature eval (evil +everywhere) file-templates (lookup +docsets) snippets workspaces :completion company (ivy +fuzzy) :ui doom doom-dashboard evil-goggles hl-todo indent-guides modeline nav-flash neotree (popup +all +defaults) vc-gutter vi-tilde-fringe window-select :editor fold (format +onsave) multiple-cursors rotate-text :emacs dired electric eshell imenu term vc :tools ansible docker editorconfig flycheck magit make rgb terraform :lang cc clojure data elixir emacs-lisp hy javascript markdown nix (org +attach +babel +capture +export +present) python ruby (sh +zsh) web :config default)
  packages:  (company-emoji emidje evil-lisp-state flymd lispyville sort-words uuidgen xterm-color (frame-fns :recipe (frame-fns :fetcher github :repo emacsmirror/frame-fns)) (frame-cmds :recipe (frame-cmds :fetcher github :repo emacsmirror/frame-cmds)) (zoom-frm :recipe (zoom-frm :fetcher github :repo emacsmirror/zoom-frm)))
  exec-path: (~/dev/nu/ios-cli ~/dev/nu/nucli ~/dev/nu/nudev ~/.npm-packages/bin ~/.emacs.d/bin ~/.local/bin /nix/store/waryasrlh7llcj1kjpar67hhjl036ifm-kitty-0.13.3/bin /nix/store/x677bgqzi5aj1fqiprhv3aqz1v6gg2f4-imagemagick-6.9.9-34/bin /nix/store/lvvb9q2dwr1q31lwvmby0242k83va8gq-xsel-unstable-2016-09-02/bin ~/bin /run/wrappers/bin ~/.nix-profile/bin /nix/var/nix/profiles/default/bin /run/current-system/sw/bin /etc/profiles/per-user/thiagoko/bin /nix/store/2icdl3lfyfsm8jj5ajxww1gy8vyvpmj5-emacs-26.1/libexec/emacs/26.1/x86_64-pc-linux-gnu)
  ```
</details>

**Comment by hlissner** [comment]
I cannot reproduce this, but it looks like a package issue. Make sure you've updated your packages and refreshed Doom:

```sh
doom update
doom refresh
```

Then see if the problem persists.

**Comment by thiagokokada** [comment]
Yeah, maybe this is a issue with upstream (I actually had done an update just before having this problem). Magit seems to pretty broken for now.

Trying to open `magit-status` (`SPC g g`) on a freshly open instance o Emacs I got:

```
command-execute: Wrong type argument: commandp, magit-status
```

After doing a `M-x magit-status`, and going back the file buffer using `C-o`, `SPC g g` works again.

**Comment by thiagokokada** [comment]
@hlissner BTW, one question. Is there some way to pin package versions?

**Comment by hlissner** [comment]
I've updated to the latest version of magit and do not see these issues. 

Did you try `doom refresh`? It should fix that commandp issue.

>BTW, one question. Is there some way to pin package versions?

You can install a specific commit with:

```elisp
(package! magit
  :recipe (:fetcher github
           :repo "magit/magit"
           :commit "..."))
```

**Comment by thiagokokada** [comment]
> Did you try doom refresh? It should fix that commandp issue, at least.

Yeah. Maybe it is some issue with my `config.el`. For now I did the nuclear option of cleaning my whole `~/.emacs.d` directory and I am starting from zero.

> You can install a specific commit with

Cool!

**Comment by thiagokokada** [comment]
After a full refresh everything is working. I think maybe a some corruption somewhere.

Thanks @hlissner.
