### ISSUE TITLE
`SPC *`  work abnormal under helm feature

### ISSUE THREAD

**Issue by chengyi** [hlissner/doom-emacs#1320]
when press `SPC *`, the emacs says: `helm-get-candidates: Candidates function ‘helm-ag--do-ag-candidate-process’ should run a process`.

**Comment by hlissner** [comment]
I cannot reproduce this. 

1. Make sure helm is up-to-date,
2. Please create a backtrace from it (`M-x toggle-debug-on-error` then recreate the error)

**Comment by hlissner** [comment]
Nevermind, I found the issue. 3c01de8 should resolve this issue. Let me know if that isn't the case and I will reopen this. Thanks for reporting this issue.

**Comment by chengyi** [comment]
@hlissner :rofl::rofl:
