### ISSUE TITLE
[SPC p p] Projectile Switching Projects not working

### ISSUE THREAD

**Issue by JMSantos94** [hlissner/doom-emacs#1323]
### Observed behavior

Whenever I open emacs, I am presented with the following error:

```
*ERROR*: Symbol’s value as variable is void: projectile-project-root
```

Afterwards if I try to switch to any of my projects using `SPC p p`, it will throw the following error:

```
Not in a valid workspace (nil)
```

Reverting the following commit fixes the issue: [d3a12a3914956e83040d50e52fa2ff5ee57081bd](https://github.com/hlissner/doom-emacs/commit/d3a12a3914956e83040d50e52fa2ff5ee57081bd)

I tried this in two different `MacBook Pro` machines, and the error seems to be pretty consistent.

Let me know if I can be of any help troubleshooting this issue!

### Expected behavior

`SPC p p` should let an user switch between projects.

### System information

OS: MacOS Mojave 10.14.4
Emacs: 26.1 (emacs-plus)

**Comment by cole-h** [comment]
I ran into this error recently while running Emacs in daemon mode on Arch Linux (Emacs 26.1 from the repos as well). Connecting with emacsclient showed that error in stdout, but there were no problems when running Emacs standalone (i.e. without the `--daemon` arg). I can confirm reverting that commit fixes the issue for me as well.

**Comment by JMSantos94** [comment]
I should have been more specific, I am running emacs as a daemon. @cole-h  explains exactly how I run emacs :)

**Comment by hlissner** [comment]
Try adding `(defvar projectile-project-root nil)` to your `~/.doom.d/init.el` and let me know if that resolves the issue.

**Comment by cole-h** [comment]
> Try adding `(defvar projectile-project-root nil)` to your `~/.doom.d/init.el` and let me know if that resolves the issue.

Fixed it for me.

**Comment by JMSantos94** [comment]
Fixed for me as well. Thanks @hlissner !

**Comment by hlissner** [comment]
I've merged it in with 4727d0a. Thanks for letting me know!

**Comment by JMSantos94** [comment]
@hlissner I think I found another issue after the change. If use `SPC p p` and select a different project. It will prompt me to select a file, but not from this other project. The prompt will be for the current project's files.

Let me know if you need a more detailed description.

**Comment by cole-h** [comment]
I can't reproduce that on develop HEAD (c1bc899). I did the following to try and reproduce:

1. Open Doom
2. `SPC TAB n` for a new workspace (so I don't affect my current work)
3. `SPC p p` and select a project and open a file
4. `SPC p p` and select a different project and notice it is indeed showing files from this newly select project

**Comment by hlissner** [comment]
@JMSantos94 This has been reported before. I had hoped that d3a12a3 had fixed it. Is Doom up-to-date?

If it is up-to-date, please open a new issue for it.

**Comment by JMSantos94** [comment]
I updated to latest and deleted any cached files. Now it works like a charm! 
Thanks for checking @cole-h and @hlissner !

Sorry for any inconveniece.
