### ISSUE TITLE
Issue with DOOM = "bin/doom" in branch develop on windows

### ISSUE THREAD

**Issue by crazyvan** [hlissner/doom-emacs#1325]
On windows 10, make install in develop fails with

'bin' is not recognised as an internal or external command,
operable program or batch file.
make: *** [Makefile:25: install] Error 1

Changed it to DOOM = "bin\doom" and then make install only installed 45 packages:

![image](https://user-images.githubusercontent.com/4249798/56052087-7c8aa400-5d48-11e9-8ec5-f27557f23b24.png)

![image](https://user-images.githubusercontent.com/4249798/56052153-9deb9000-5d48-11e9-8316-506189508c0b.png)

![image](https://user-images.githubusercontent.com/4249798/56052193-b360ba00-5d48-11e9-8b27-71af112bd82d.png)

Running emacs then loads 45 packages:

![image](https://user-images.githubusercontent.com/4249798/56052232-ca9fa780-5d48-11e9-9def-bc48089470e8.png)

**Comment by hlissner** [comment]
There are two separate issues here.

> 'bin' is not recognised as an internal or external command,

I'll look into a fix for this.

> Changed it to DOOM = "bin\doom" and then make install only installed 45 packages:

It sounds like you do not have a private directory (or Emacs cannot find it). Did you run `make quickstart` first? If not, have you copied =~/.emacs.d/init.example.el` to `~/.doom.d/init.el`?

**Comment by crazyvan** [comment]
Yes you are correct, got carried away after the initial issue in the Makefile :)

Just tried this:
- clone into .emacs.d; checkout develop
- change first line in Makefile to `DOOM = "bin\doom"`
- create .doom.d folder; copy init.example.el into it and rename to init.el
- run `make install`
- packages install with no errors
- when I run emacs 'Doom loaded 45 packages' appears at the bottom:

![image](https://user-images.githubusercontent.com/4249798/56083658-e32ec100-5e1f-11e9-81e1-fa1e1149783b.png)

If I repeat the same steps in master, when I run emacs a few hundred packages are loaded, albeit with one error that has been fixed in develop.
This is the issue: https://github.com/hlissner/doom-emacs/issues/146

**Comment by crazyvan** [comment]
I have also tried this guide:

https://github.com/hlissner/doom-emacs/wiki/Getting-Started
 
`doom quickstart` runs without error.

When I run Emacs the following error appears:

![image](https://user-images.githubusercontent.com/4249798/56083956-fa6fad80-5e23-11e9-87db-7311fa8387eb.png)

On windows this is probably caused by the forward slashes in
modules/feature/evil/config.el

The config.el file is actually at that path.
