### ISSUE TITLE
Workspace buffers being killed when new buffers are opened, switched or windows are closed

### ISSUE THREAD

**Issue by danielmt** [hlissner/doom-emacs#1330]
### Observed behavior

Opening new files in a workspace with `SPC SPC` (`(+helm/projectile-find-file)`) or `SPC .` (`(helm-find-files ARG)`) is closing the current open buffer in most situations. When multiple files are opened in sequence, it kills buffers randomly.

Cycling buffers with `SPC b n` (`(next-buffer)`) kills the previous buffer and `SPC b p` (`(previous-buffer)`) kills the next buffer.

Closing a window with `SPC w c` (`(+workspace/close-window-or-workspace)`) kills the loaded buffer.

### Expected behavior

Opening any new buffers should not kill current opened buffer in a frame. Cycling buffers should not kill any buffers. Closing a window should not kill its buffer.

### Steps to reproduce

1. Open any file in a projectile workspace
2. Open another file with `SPC SPC` or `SPC .`
3. Try to get to previous buffer with `SPC b p` and it's gone, list currently open buffers with `SPC b b` and only the last one remains open.

### System information

<details>
<summary>Click to expand</summary>

```
Emacs v26.2
Doom v2.0.9 (7885cbb4)
shell: /usr/local/bin/zsh
Compiled with:
  NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS LCMS2
uname -a:
  Darwin vader.local 18.5.0 Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT
  2019; root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64 i386 MacBookPro14,3 Darwin

Checking your OS...
Checking your fonts...
Checking gnutls/openssl...
Testing your root certificates...
Checking for GNU/BSD tar...
Checking Doom core for irregularities...
Checking your enabled modules...
  > (:lang cc) Couldn’t find the rtag client and/or server programs
    (rdm). Disabling rtags support
  > (:lang cc) Irony server isn’t installed. Run M-x
    irony-install-server
  > (:lang cc) Couldn’t find glslangValidator. GLSL code completion
    is disabled


There are 5 warnings!
No RTags process running (rdm)...
```
</details>

**Comment by mfiano** [comment]
This may be related, but I am constantly battling against a very similar problem. If I `+popup/raise` a popup window and then open it in a regular window, the modifying the window layout (deleting windows, creating new splits, etc) has a good chance (but not always) of making the old popup window an actual popup window again, closing the window that it was in automatically.

**Comment by hlissner** [comment]
Does this resolve the issue for you?

```elisp
;; in ~/.doom.d/config.el
(setq +popup-default-display-buffer-actions '(+popup-display-buffer-stacked-side-window))
```

**Comment by hlissner** [comment]
@danielmt Does this resolve your issue?

```elisp
(setq persp-autokill-buffer-on-remove nil)
```

**Comment by danielmt** [comment]
@hlissner Nope, almost same behaviour. When I open a new buffer, it doesn't kill the previous one, but, switching buffers with next/previous-buffer kills them. Creating a new window (`SPC w H`), opening a buffer, and, closing the window, still kills the buffer as well.

**Comment by hlissner** [comment]
I cannot reproduce this. Does the issue persist in vanilla Doom? e.g.

`SPC h E` to open the vanilla sandbox. then `C-c C-p` to open an instance of Doom + enabled modules but without your private config.

**Comment by danielmt** [comment]
@hlissner I can't reproduce using the vanilla sandbox. I've just did another cleanup of .emacs.d, using `git clean -dfx`, and proceeded to `make && make autoloads compile-core`, and, the issue is gone. Might've been related to some left-over after updating doom and/or packages, but, the first cleanup didn't work, I think I used `make quickstart autoloads compile-core`
