### ISSUE TITLE
doom-leader-alt-key shows "+prefix"

### ISSUE THREAD

**Issue by DonHugo69** [hlissner/doom-emacs#1332]
Similar to [this issue](https://github.com/hlissner/doom-emacs/issues/1240), but seems to affect only the `doom-leader-alt-key` keybinds.
![image](https://user-images.githubusercontent.com/10484857/56186779-df1dc180-6020-11e9-8e4d-54f72c6bb0ee.png)

**Comment by hlissner** [comment]
As of 068a324 this should be resolved. Let me know if that isn't the case and I will reopen this. Thanks for bringing this to my attention!

**Comment by DonHugo69** [comment]
Thanks a lot!
