### ISSUE TITLE
use directory local variable change module load behavior

### ISSUE THREAD

**Issue by chengyi** [hlissner/doom-emacs#1334]
Hi, @hlissner 

I have add gtags to doom-emacs. Now I want to implement some feature as description below:

1. when open a project, detect whether `gtags-enable-for-this-project` is defined.
2. if it is not defined, ask user "whether use gtags", then write user's option to directory local variable
`gtags-enable-for-this-project`
3. if `gtags-enable-for-this-project` is `t`, enable gtags and disable lsp

my question is how I could make `gtags-enable-for-this-project` available before related module is loaded. e.g. change the `cc` module load behavior due to `gtags-enable-for-this-project`.

**Comment by hlissner** [comment]
Sorry for the late response. Perhaps something like this?

```elisp
(defun check-gtags ()
  (when (memq major-mode '(c-mode c++-mode objc-mode))
    (unless (bound-and-true-p gtags-enable-for-this-project)
      (setq gtags-enable-for-this-project
            (y-or-n-p "Enable gtags?")))
    (when gtags-enable-for-this-project
      (gtags-mode +1)
      (lsp-mode -1))))
(add-hook 'hack-local-variables-hook #'check-gtags)
```

Using `hack-local-variables-hook` means the function is a) after changing a major-mode and b) after file/dir-local variables are read.

**Comment by chengyi** [comment]
@hlissner thanks for you help. doom-emacs is the best emacs config that I ever used.
