### ISSUE TITLE
org-mode refile causes Emacs on MAC crash

### ISSUE THREAD

**Issue by whjiang** [hlissner/doom-emacs#1340]
Here is the error report I filed on emacs mac build:  [issue report](https://github.com/railwaycat/homebrew-emacsmacport/issues/169). 

I am not sure whether it is an emacs issue or due to wrong configuration.

**Comment by kumo** [comment]
I now have the same thing, and also sparse-tree match crashes too, but only if I run the windowed app. If I run emacs from the terminal, then it works.

**Comment by hlissner** [comment]
Are you still experiencing this issue? If so, please include your `M-x doom/info`.

**Comment by whjiang** [comment]
Refiling works fine now for me.
