### ISSUE TITLE
How to press key to call ivy-occur?

### ISSUE THREAD

**Issue by shuxiao9058** [hlissner/doom-emacs#1342]
https://github.com/hlissner/doom-emacs/blob/cf7ef0f99ff03238c5660381d0e6ec918bd86e5f/modules/completion/ivy/autoload/hydras.el#L43

Because no prefix key defined, How the hydra works?

**Comment by hlissner** [comment]
While an ivy is open, `M-o` will open the hydra, then `o` will invoke ivy-occur.

**Comment by shuxiao9058** [comment]
Thanks for your reply.

**Comment by shuxiao9058** [comment]
@hlissner With this keystrokes the ivy-occur does not work yet.

![output-2019-04-20-11:17:57](https://user-images.githubusercontent.com/3312525/56451439-3c39b000-635e-11e9-92b6-83917f1158ba.gif)

**Comment by hlissner** [comment]
After another look, it's a bug. In the meantime, `C-c C-o` should open an occur buffer as well.

**Comment by shuxiao9058** [comment]
yes, it works with `C-c C-o` now.
