### ISSUE TITLE
'No such file or directory' when starting doom on windows

### ISSUE THREAD

**Issue by crazyvan** [hlissner/doom-emacs#1354]
I cloned branch develop again on windows 10.
After running doom quickstart (174 packages were downloaded), running emacs throws the following error:

![image](https://user-images.githubusercontent.com/4249798/56600479-a9647400-65f0-11e9-8fdf-afd1b5ad688c.png)

Failed to load deferred package server: (file-missing Cannot open load file No such file or directory ~/EmacsConf/.emacs.d/core/autoload/buffers)

**Comment by Simon-Thompson** [comment]
(note: I'm new to Emacs and Doom, so more experienced people feel free to bring corrections)

Seems to be a default-directory issue. When running from the windows shortcut for emacs, mine gave 
```
Failed to load deferred package server: (file-missing Cannot open load file No such file or directory ~/AppData/Roaming/.emacs.d/core/autoload/buffers)
```
When running emacs from a bash shell inside of `"C:\Users\Simon\AppData\Roaming\.emacs.d"`, Doom opens correctly and runs without error (though it can't seem to find the all-the-icons fonts, even after installing them). This is thanks to emacs setting the default-directory to the directory you're in when starting from the command line.

If you want that behaviour when you start it from anywhere, add this to your `.emacs.d/init.el` file:
```
(setq default-directory "C:/Users/YOUR_USER/.emacs.d")
```
Replacing your_user with your own user, of course.

With this change, I can start Doom Emacs from bash while in any directory =]

**Comment by hlissner** [comment]
Does `doom refresh` not resolve this issue for you?

**Comment by Simon-Thompson** [comment]
Negative, I tried `doom refresh` many times, along with `make`, and neither made a difference =\

**Comment by Simon-Thompson** [comment]
*as an addendum, I was able to make the fonts work by first downloading them, then going to that directory in explorer and doing right-click -> install (the default windows way of installing fonts)

**Comment by crazyvan** [comment]
thanks for the tips. I've got it working on windows (fonts too!)

**Comment by enko** [comment]
What I do on my windows setups, that I set a env variable `HOME` to `%USERPROFILE%`, that whay emacs works in a more unix-ish way and expects the `.emacs.d` folder in `%USERPROFILE` and not in `%APPDATA%`.

**Comment by hlissner** [comment]
@crazyvan What did you do to get it working?

**Comment by blackfalconru** [comment]
I had this exact problem(Win 10/Emacs 26.2/env `HOME` set to `%APPDATA%`), while `doom refresh` did not resolve at first, what I did to solve this:
Delete `~/.emacs.d/.local`
Run `doom refresh`
That was it. I can't reproduce this error anymore.
