### ISSUE TITLE
S-k does not work in clojure-mode

### ISSUE THREAD

**Issue by thiagokokada** [hlissner/doom-emacs#1357]
### Observed behavior

`S-k` (`K`) returns `Couldn't find documentation for 'thing'` instead of showing documentation for the thing at point. Calling `cider-doc` directly works, as also `SPC m h d` works too.

### Expected behavior

`S-k` would call `cider-doc` in `clojure-mode` and show documentation.

### Steps to reproduce

1. Open CIDER REPL
2. Eval any Clojure buffer
3. Use `S-k` to try to get documentation from something (like a  function)

### System information

<details>
<summary>Click to expand</summary>

- OS: gnu/linux (x86_64-pc-linux-gnu)
- Emacs: 26.1 (abr 08, 2019)
- Doom: 2.0.9 (HEAD -> develop, origin/develop 768d6e9c 2019-04-23 23:05:53 -0400)
- Graphic display: t (daemon: nil)
- System features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LIBSYSTEMD
- Details:
  ```elisp
  env bootstrapper: nil
  elc count: 0
  uname -a:  Linux 4.19.35 #1-NixOS SMP Wed Apr 17 06:38:55 UTC 2019 x86_64
  modules:   (:feature eval (evil +everywhere) file-templates (lookup +docsets) snippets workspaces :completion company (ivy +fuzzy) :ui doom hl-todo indent-guides modeline nav-flash neotree ophints (popup +all +defaults) vc-gutter vi-tilde-fringe window-select :editor fold (format +onsave) multiple-cursors rotate-text :emacs dired electric eshell imenu term vc :tools ansible docker editorconfig flycheck magit make rgb terraform :lang cc clojure data elixir emacs-lisp hy javascript markdown nix (org +attach +babel +capture +export +present) python ruby (sh +zsh) web :config default)
  packages:  (company-emoji evil-collection evil-lisp-state flymd lispyville sort-words uuidgen xterm-color (frame-fns :recipe (frame-fns :fetcher github :repo emacsmirror/frame-fns)) (frame-cmds :recipe (frame-cmds :fetcher github :repo emacsmirror/frame-cmds)) (zoom-frm :recipe (zoom-frm :fetcher github :repo emacsmirror/zoom-frm)))
  exec-path: (~/dev/nu/ios-cli ~/dev/nu/nucli ~/dev/nu/nudev ~/.npm-packages/bin ~/.emacs.d/bin ~/.local/bin /nix/store/xf59s14j0x8l34agxiq6n1rn54wia3b1-kitty-0.13.3/bin /nix/store/4y5lv3a8s42wd0w0wga9sfflf6x0s5wg-imagemagick-6.9.9-34/bin /nix/store/k1gmlgblqqywmnzqxzlm0a2473r14zx5-xsel-unstable-2018-01-10/bin ~/bin /run/wrappers/bin ~/.nix-profile/bin /nix/var/nix/profiles/default/bin /run/current-system/sw/bin /etc/profiles/per-user/thiagoko/bin /nix/store/z6x936aa6kfnwpz8fb34z28qng5prrp9-emacs-26.1/libexec/emacs/26.1/x86_64-pc-linux-gnu)
  ```
</details>

**Comment by gsnewmark** [comment]
`gd` also started working incorrectly: it tries to lookup definition using TAGS insted of calling `cider-find-dwim`. But `gD` works correctly (calls `cljr-find-usages`), so I think it's possible that [setting references lookup handler in clj-refactor package definition](https://github.com/hlissner/doom-emacs/blob/768d6e9c69cd48eb00d41f2301461961119dd83c/modules/lang/clojure/config.el#L108-L109) overwrites [previously configured documentation & definition lookup handlers](https://github.com/hlissner/doom-emacs/blob/768d6e9c69cd48eb00d41f2301461961119dd83c/modules/lang/clojure/config.el#L15-L17).

Maybe it's related to these changes https://github.com/hlissner/doom-emacs/commit/8a5af077a64d7bcaaea272f8b6ea9949c7af0539, but I didn't actually debug it yet :see_no_evil:

**Comment by thiagokokada** [comment]
I can confirm that `gd` also does not work, however since it didn't work when I started to use `doom` (that is, very recently), I just thought this was expected and manually remapped `gd` to `'#cider-find-var` :sweat_smile: .
