### ISSUE TITLE
When open emacs 26.2 on MAC in terminal, an error reported "Symbol's value as variable is void: after-init-time"

### ISSUE THREAD

**Issue by whjiang** [hlissner/doom-emacs#1358]
My emacs 26.2 was a build from https://github.com/railwaycat/homebrew-emacsmacport. If I open emacs in GUI, everything is fine. But, if I open emacs in terminal, an error "Symbol's value as variable is void: after-init-time" will be reported in *Messages*.

**Comment by hlissner** [comment]
This sounds like you have the wrong version of Emacs in your PATH. Running `emacs --version` will likely produce `22.1.1` (the version that is included with Emacs).

What Doom should have done is emit an error about using a version of Emacs Doom doesn't support -- that I will fix soon -- but to resolve your issue, you need to adjust your PATH in your shell configuration. e.g.

```sh
# in ~/.zshenv or ~/.bash_profile, iirc
export PATH="/usr/local/bin:$PATH"
```

**Comment by whjiang** [comment]
@hlissner  you are right. The railwaycat mac build has only GUI version, the terminal one is still emacs 22. I use an alias to point to the emacs 26. I don't know why the alias suddenly not working. After fixing the alias, everything is OK now.
