### ISSUE TITLE
gd does not work with methods that ends with !

### ISSUE THREAD

**Issue by thiagokokada** [hlissner/doom-emacs#1360]
### Observed behavior

In Clojure you generally puts an `!` and the end of a function to indicate that it have side effects (like `(ns/function! arg0 arg1)`). However, if you do a `gd` in those functions, it first asks a `Jump to: ns/function` (note, without the `!`).

`cider-find-var` (`, g g`) works correctly in those cases, going directly to the function.

P.S.: This may be a more general issue, however I only tested it in Clojure.

### Expected behavior

`gd` should works like `, g g`.

### Steps to reproduce

1. Open CIDER REPL
2. Open Clojure buffer
3. Find a function with a `!` in the end and `g d` it

### System information

<details>
<summary>Click to expand</summary>

- OS: gnu/linux (x86_64-pc-linux-gnu)
- Emacs: 26.1 (abr 08, 2019)
- Doom: 2.0.9 (HEAD -> develop, _upgrade/develop 52eed893 2019-04-24 13:01:53 -0400)
- Graphic display: t (daemon: nil)
- System features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LIBSYSTEMD
- Details:
  ```elisp
  env bootstrapper: nil
  elc count: 0
  uname -a:  Linux 4.19.35 #1-NixOS SMP Wed Apr 17 06:38:55 UTC 2019 x86_64
  modules:   (:feature eval (evil +everywhere) file-templates (lookup +docsets) snippets workspaces :completion company (ivy +fuzzy) :ui doom hl-todo indent-guides modeline nav-flash neotree ophints (popup +all +defaults) vc-gutter vi-tilde-fringe window-select :editor fold (format +onsave) multiple-cursors rotate-text :emacs dired electric eshell imenu term vc :tools ansible docker editorconfig flycheck magit make rgb terraform :lang cc clojure data elixir emacs-lisp hy javascript markdown nix (org +attach +babel +capture +export +present) python ruby (sh +zsh) web :config default)
  packages:  (company-emoji evil-lisp-state flymd lispyville sort-words uuidgen xterm-color (frame-fns :recipe (frame-fns :fetcher github :repo emacsmirror/frame-fns)) (frame-cmds :recipe (frame-cmds :fetcher github :repo emacsmirror/frame-cmds)) (zoom-frm :recipe (zoom-frm :fetcher github :repo emacsmirror/zoom-frm)))
  exec-path: (~/dev/nu/ios-cli ~/dev/nu/nucli ~/dev/nu/nudev ~/.npm-packages/bin ~/.emacs.d/bin ~/.local/bin /nix/store/xf59s14j0x8l34agxiq6n1rn54wia3b1-kitty-0.13.3/bin /nix/store/4y5lv3a8s42wd0w0wga9sfflf6x0s5wg-imagemagick-6.9.9-34/bin /nix/store/k1gmlgblqqywmnzqxzlm0a2473r14zx5-xsel-unstable-2018-01-10/bin ~/bin /run/wrappers/bin ~/.nix-profile/bin /nix/var/nix/profiles/default/bin /run/current-system/sw/bin /etc/profiles/per-user/thiagoko/bin /nix/store/z6x936aa6kfnwpz8fb34z28qng5prrp9-emacs-26.1/libexec/emacs/26.1/x86_64-pc-linux-gnu)
  ```
</details>

**Comment by hlissner** [comment]
This appears to either:

1. Be a cider issue with `cider-find-dwim`, which uses `cider--find-dwim-interactive` to prompt you and grabs the symbol at point with `(thing-at-point 'filename)` (which won't capture the `!` in the symbol name) instead of `(thing-at-point 'symbol)` (which would).
2. Be an issue with Doom's choice to use `cider-find-dwim` for `gd`. Is this not the correct command to use to jump to definitions? Should Doom use `cider-find-var` instead? If so, will that work with symbols other than variables?

**Comment by gsnewmark** [comment]
It also doesn't work correctly with functions ending with `?` (used to mark predicates in Clojure) with same observed behavior.

`cider-find-dwim` is supposed to be a more generic version of the `cider-find-var`, which jumps not only into vars, but also into (file) resources/keywords/namespaces. But it looks like it actually [doesn't support keywords & namespace jumping at the moment](https://github.com/clojure-emacs/cider/issues/2508), so by switching to the `cider-find-var` we won't lose much. It's quite subjective, but ability to quickly jump into the side effecting functions & predicates is much more useful than ability to jump into resources.

**Comment by hlissner** [comment]
This does seem like an upstream issue, but I'll incorporate a temporary fix. Before I do, could you check if this resolve the issue:

```elisp
(defun +clojure-lookup-definition-handler (symbol)
  (interactive (list (+lookup--symbol-or-region)))
  (cider-find-dwim symbol))

(after! cider
  (set-lookup-handlers! 'cider-mode
    :definition #'+clojure-lookup-definition-handler
    :documentation #'cider-doc))
```

**Comment by gsnewmark** [comment]
@hlissner `gd` works correctly for me with you workaround applied :+1:

**Comment by hlissner** [comment]
I've incorporated this workaround in 237e14a. Let me know if the issue persists and I'll reopen this. Thanks for bringing it to my attention!

**Comment by gsnewmark** [comment]
@hlissner sorry, I had local changes (namely switch of `gd` to `cider-find-var` instead of `cider-find-dwim`) I forgot about :man_facepalming: With clean checkout of config without the local customization jumping still doesn't work for vars with trailing `!` / `?` even with your workaround.

**Comment by thiagokokada** [comment]
@hlissner @gsnewmark Seems the new workaround work for me. I will test more today and report it back if it doesn't work.

**Comment by gsnewmark** [comment]
:see_no_evil: just tried it in another Clojure project and now it works for me too, not sure why it stopped working earlier today.
