### ISSUE TITLE
doom-dashboard navigation keys not working

### ISSUE THREAD

**Issue by ragone** [hlissner/doom-emacs#1365]
### Observed behavior

The navigation function `+doom-dashboard/forward-button` for the `doom-dashboard-widget-shortmenu` doesn't work and is not bound to any key in the `doom-dashboard-mode-map`.

### Expected behavior

To be able to navigate `forward` and `backward` on the dashboard.

### Steps to reproduce

1. Call `+doom-dashboard/open`
2. Try to navigate up or down with either the arrow keys, `C-n/p`, `j/k` or by calling the `+doom-dashboard/forward-button` function interactively.

### System information

<details>
<summary>Click to expand</summary>

- OS: gnu/linux (x86_64-pc-linux-gnu)
- Emacs: 26.2 (Apr 13, 2019)
- Doom: 2.0.9 (HEAD -> develop, hlissner/develop c79cf3c8 2019-04-25 22:20:31 -0400)
- Graphic display: t (daemon: nil)
- System features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2
- Details:
  ```elisp
  env bootstrapper: exec-path-from-shell
  elc count: 0
  uname -a:  Linux 5.0.9-arch1-1-ARCH #1 SMP PREEMPT Sat Apr 20 15:00:46 UTC 2019 x86_64
  modules:   (:completion company ivy :ui deft doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor evil file-templates fold multiple-cursors parinfer rotate-text snippets :emacs dired electric imenu term vc :tools docker editorconfig eval flycheck flyspell (lookup +docsets) magit password-store pdf vterm :lang clojure data emacs-lisp javascript latex ledger markdown (org +attach +babel +capture +export +habit +present +protocol) php plantuml rest rust (sh +fish) web :app email irc (rss +org) :config literate (default +bindings +smartparens))
  packages:  (gruvbox-theme org-present request atomic-chrome org-clock-convenience js-doc sx phpcbf php-cs-fixer exec-path-from-shell tldr ox-clip ov deft org-jira vlf hackernews paradox org-mime vagrant-tramp gif-screencast terraform-mode excorporate nov cargo ox-jira language-detection terminal-here expand-region xterm-color (evil-matchit :recipe (evil-matchit :fetcher github :repo redguardtoo/evil-matchit :commit 7d65b4167b1f0086c2b42b3aec805e47a0d355c4)))
  exec-path: (~/bin/ /home/linuxbrew/.linuxbrew/bin/ /home/linuxbrew/.linuxbrew/sbin/ /opt/google-cloud-sdk/bin/ /usr/local/bin/ /usr/bin/ /bin/ /usr/local/sbin/ /usr/lib/jvm/default/bin/ /usr/bin/site_perl/ /usr/bin/vendor_perl/ /usr/bin/core_perl/ /sbin/ /usr/sbin/ ~/.config/composer/vendor/bin/ ~/go/bin/ ~/.cargo/bin/ ~/.gem/ruby/2.6.0/bin/ ~/.yarn/bin/ /usr/lib/emacs/26.2/x86_64-pc-linux-gnu/)
  ```
</details>

**Comment by hlissner** [comment]
12a3ada should resolve this issue. Let me know if that isn't the case and I'll reopen this. Thanks for bringing this to my attention!
