### ISSUE TITLE
Tab does not work well with org-mode in terminal

### ISSUE THREAD

**Issue by shuxiao9058** [hlissner/doom-emacs#1367]
Tab in org-mode work as `better-jumper-jump-forward`, but not `org-cycle`

**Comment by hlissner** [comment]
This is because C-i is bound to better-jumper-jump-forward, and in TTY emacs, the tab key triggers `C-i`.

Try adding this to `~/.doom.d/init.el`:

```elisp
(setq evil-want-C-i-jump nil)
```
