### ISSUE TITLE
Broken fresh install; doesn't install evil + other oddities

### ISSUE THREAD

**Issue by Capt0r** [hlissner/doom-emacs#1368]
### Observed behavior
After a clean install of latest `develop` branch Emacs starts in barebones mode with an exception:
`Error in an autoloads file: autoloads.el, (void-function after!)`

### Expected behavior

After a clean install Emacs should start in full Doom mode with no errors.

### Steps to reproduce

Here's the short relevant log of happened (full log **and solution** below):

```
git clone https://github.com/hlissner/doom-emacs.git ~/.emacs.d
.emacs.d/bin/doom quickstart
...
✓ Clean up autoloads

In toplevel form:
../../../autoloads.el:1368:1:Error: Symbol’s value as variable is void: hydra-ivy/heads
✓ Cached package state
✓ Package autoloads included
✓ Removed load-path/auto-mode-alist entries
Download and install all-the-icon's fonts? (y or n) y
...
Finished!

If you have a running Emacs Session, you will need to restart it or
reload Doom for changes to take effect:

  M-x doom/restart-and-restore
  M-x doom/restart
  M-x doom/reload
########################
emacs&
Error in an autoloads file: autoloads.el, (void-function after!)
```

```
zsh> ./doom doctor
Doom Doctor
Emacs v26.1
Doom v2.0.9 (grafted, HEAD -> develop, origin/develop, origin/HEAD 8e45346
2019-04-26 17:43:45 -0400)
shell: /bin/zsh
Compiled with: JPEG NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS
  THREADS
uname -msrv: Darwin 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT
  2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64

Checking Emacs
  Checking your Emacs version is 25.3 or newer...
  Checking if your version of Emacs has changed recently...
  Checking for Emacs config conflicts...
  Checking for private config conflicts...
  Checking for stale elc files...
Checking your system...
  Checking your fonts...
  Checking gnutls/openssl...
  Testing your root certificates...
  Checking for GNU/BSD tar...
  Warning: BSD tar detected
    > QUELPA (through package-build) uses the system tar to build plugins, but it
      expects GNU tar. BSD tar *could* cause errors during package installation or
      updating from non-ELPA sources.  MacOS users can install gnu-tar via
      homebrew: brew install gnu-tar
Checking DOOM Emacs...
Attempt to load DOOM failed (autoloads.el (void-function after!))
```

### Solution

Fortunately after some quick investigation I managed to fix it ie. got a zero-errors full Doom install working.

First I tried rebuilding `doom autoloads` (log attached) - it completed successfully (with weird warnings) but now I had a different error: that `evil` cannot be found!

```
zsh> ./bin/doom doctor
Doom Doctor
Emacs v26.1
Doom v2.0.9 (grafted, HEAD -> develop, origin/develop, origin/HEAD 8e45346
2019-04-26 17:43:45 -0400)
shell: /bin/zsh
Compiled with: JPEG NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS
  THREADS
uname -msrv: Darwin 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT
  2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64

Checking Emacs
  Checking your Emacs version is 25.3 or newer...
  Checking if your version of Emacs has changed recently...
  Checking for Emacs config conflicts...
  Checking for private config conflicts...
  Checking for stale elc files...
Checking your system...
  Checking your fonts...
  Checking gnutls/openssl...
  Testing your root certificates...
  Checking for GNU/BSD tar...
Checking DOOM Emacs...
Attempt to load DOOM failed (modules/editor/evil/config.el (file-missing
  Cannot open load file No such file or directory evil))


There is 1 warning!
```

At this point I ran `./doom install evil` (log attached) and now everything is up and running with no further issues (...that I have come across so far on day 2 of my first `doom` experience 😢).

[install.evil.log.txt](https://github.com/hlissner/doom-emacs/files/3125746/install.evil.log.txt)
[quickstart.log.txt](https://github.com/hlissner/doom-emacs/files/3125747/quickstart.log.txt)

### To investigate

In order of importance:
- why `autoloads` needed to be regenerated immediately after being triggered as part of `quickstart`?
- why `evil` wasn't installed as part of `quickstart`?
- why an error during install wasn't handled/didn't abort the install, and, worse, gave a false message of a successful install?
- why an explicit `install evil` installs missing dependencies (which maybe should be dependencies of `quickstart` core instead? because...) and yet `evil` itself seems to be already installed?
```
Installing evil
⚠ ALREADY INSTALLED
```
- why `install evil` installs `evil-anzu` and `evil-goggles` *before* `evil`? (which might explain why at that point it complains that `evil` is already installed)
- perhaps this is known, unavoidable or just a minor issue, but while I'm at it, for completeness I'm including these duplicate dependencies that showed up:

during `quickstart`:
```
Installing avy
⚠ ALREADY INSTALLED
```
during `install evil`:
```
Installing evil-surround
⚠ ALREADY INSTALLED
Installing swiper
⚠ ALREADY INSTALLED
Installing markdown-mode
⚠ ALREADY INSTALLED
Installing htmlize
⚠ ALREADY INSTALLED
```

### System information

<details>
<summary>Click to expand</summary>

- OS: darwin (x86_64-apple-darwin17.7.0)
- Emacs: 26.1 (Nov 16, 2018)
- Doom: 2.0.9 (grafted, HEAD -> develop, origin/develop, origin/HEAD 8e45346 2019-04-26 17:43:45 -0400)
- Graphic display: nil (daemon: nil)
- System features: JPEG NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS THREADS
- Details:
  ```elisp
  env bootstrapper: envvar-file
  elc count: 0
  uname -a:  Darwin 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64
  modules:   (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor evil file-templates fold multiple-cursors rotate-text snippets :emacs dired electric imenu vc :tools eval flycheck (lookup +docsets) magit :lang data emacs-lisp markdown (org +attach +babel +capture +export +habit +present +protocol) (sh +fish) :config default)
  packages:  n/a
  exec-path: (~/.local/bin ~/.asdf/bin ~/.asdf/shims ~/.yarn/dist/bin ~/.local/etc/yarn/global/node_modules/.bin ~/.fzf/bin ~/go/bin ~/Blake/bs/bin/ /Applications/Postgres.app/Contents/Versions/latest/bin /usr/local/Cellar/mysql@5.6/5.6.37/bin /opt/local/bin /opt/bin /usr/local/bin /usr/local/sbin /usr/bin /usr/sbin /bin /sbin /usr/bin /bin /usr/sbin /sbin /usr/local/bin /Library/TeX/texbin /opt/X11/bin /Applications/Postgres.app/Contents/Versions/latest/bin ~/.local/bin ~/.asdf/bin ~/.asdf/shims ~/.yarn/dist/bin ~/.local/etc/yarn/global/node_modules/.bin ~/.fzf/bin ~/go/bin ~/Blake/bs/bin/ /usr/local/Cellar/mysql@5.6/5.6.37/bin /opt/local/bin /opt/bin /usr/local/sbin ~/Blake/bx/bin ~/Blake/bd/bin ~/Blake/bx/bin ~/Blake/bd/bin /usr/local/Cellar/emacs/26.1_1/libexec/emacs/26.1/x86_64-apple-darwin17.7.0)
 ```

**Comment by iceiceiceJack** [comment]
same problem

**Comment by iceiceiceJack** [comment]
1.  remove (evil+everything) in ~/.doom.d/init.el
2. make
3. add (evil+everything) in ~/.doom.d/init.el
4. make
then it seems ok now

**Comment by hlissner** [comment]
`doom quickstart` wasn't reading init.el after it was copied. Running `doom refresh` (or `make`, same thing) would've gotten around it, but after e0e82ffb this shouldn't be an issue anymore. Let me know if that isn't the case and I will reopen this. Thanks for bringing it to my attention!

**Comment by shuxiao9058** [comment]
The same error with the latest develop branch.

**Comment by hlissner** [comment]
@shuxiao9058 Please create a new issue. The issue reported here is so old that you are guaranteed to _not_ have the same error messages.
