### ISSUE TITLE
org mode+table.el: Error running timer ‘table--update-cell’: (wrong-type-argument number-or-marker-p nil) 

### ISSUE THREAD

**Issue by whjiang** [hlissner/doom-emacs#1369]
In org mode, 
1. I created a table.
2. I pressed `c-c ~` to convert table to table.el based.
3. I pressed `c-c '` to edit the table.
4. during editing, it reports error
```
Error running timer ‘table--update-cell’: (wrong-type-argument number-or-marker-p nil) [5 times]
```

**Comment by hlissner** [comment]
I cannot reproduce this. Could you produce a backtrace from it? e.g. `M-x toggle-debug-on-error` then recreate the error.

**Comment by whjiang** [comment]
After restart my emacs, I also can't reproduce it.
