### ISSUE TITLE
'Setting current directory No such file' when opening files over SSH

### ISSUE THREAD

**Issue by orausch** [hlissner/doom-emacs#1372]
### Observed behavior
A message appears with the content
```
apply: Setting current directory: No such file or directory, /home/user/
```
While editing the file, similar messages appear unpredictably. For example:
```
File local-variables error: (file-missing Setting current directory No such file or directory /home/user/)
```
```
Failed to load ’git-commit’ package incrementally, because: (file-missing Setting current directory No such file or directory /ssh:user@host:/home/user/)
```
```
dired-insert-directory: Setting current directory: No such file or directory, /ssh:user@host:~/
```
### Expected behavior
The messages do not appear.

### Steps to reproduce

1. Open a dired buffer on a remote host `(dired "/ssh:user@host:~/")`
2. Press return on any python file.
3. The file does not open the first time, and the message is displayed. The file opens on the second time.
### Debug trace
```
Debugger entered--Lisp error: "File local-variables error: (file-missing Setting current directory No such file or directory /home/user/)"
  message("File local-variables error: %s" (file-missing "Setting current directory" "No such file or directory" "/home/user/"))
  run-mode-hooks(python-mode-hook)
  python-mode()
  set-auto-mode-0(python-mode nil)
  set-auto-mode()
  normal-mode(t)
  after-find-file(nil t)
  #f(compiled-function (buf filename nowarn rawfile truename number) #<bytecode 0x1b4b5f>)(#<buffer file.py> "/ssh:user@host:/home/user/file.py" nil nil "/ssh:user@host:/home/user/file.py" ((98 . 2243) (-1 . 1)))
  apply(#f(compiled-function (buf filename nowarn rawfile truename number) #<bytecode 0x1b4b5f>) (#<buffer file.py> "/ssh:user@host:/home/user/file.py" nil nil "/ssh:user@host:/home/user/file.py" ((98 . 2243) (-1 . 1))))
  find-file-noselect-1(#<buffer file.py> "/ssh:user@host:/home/user/file.py" nil nil "/ssh:user@host:/home/user/file.py" ((98 . 2243) (-1 . 1)))
  find-file-noselect("/ssh:user@host:/home/user/file.py" nil nil nil)
  find-file("/ssh:user@host:/home/user/file.py")
  dired-find-file()
  funcall-interactively(dired-find-file)
  call-interactively(dired-find-file nil nil)
  command-execute(dired-find-file)

```
### System information

<details>
<summary>Click to expand</summary>

- OS: gnu/linux (x86_64-pc-linux-gnu)
- Emacs: 26.2 (Apr 20, 2019)
- Doom: 2.0.9 (HEAD -> develop, origin/develop 8e453462 2019-04-26 17:43:45 -0400)
- Graphic display: t (daemon: nil)
- System features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD LCMS2
- Details:
  ```elisp
  env bootstrapper: envvar-file
  elc count: 0
  uname -a:  Linux 4.19.0-4-amd64 #1 SMP Debian 4.19.28-2 (2019-03-15) x86_64
  modules:   (:tools eval :editor evil file-templates :tools lookup :editor snippets :ui workspaces :completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) treemacs vc-gutter vi-tilde-fringe window-select :editor fold multiple-cursors rotate-text :emacs dired electric imenu vc :tools flycheck magit :lang cc data emacs-lisp latex markdown (org +attach +babel +capture +export +habit +present +protocol) python (sh +fish) :config default)
  packages:  n/a
  exec-path: (/usr/local/bin /usr/bin /bin /usr/local/games /usr/games ~/.fzf/bin ~/.local/bin ~/.emacs.d/bin /usr/lib/x86_64-linux-gnu/emacs/26.2/x86_64-linux-gnu/)
  ```
</details>

**Comment by hlissner** [comment]
Do you still have this issue? I'm hoping that a1c1d881 will have addressed this.

**Comment by orausch** [comment]
No, I can unfortunately still reproduce the issue (following the same steps as detailed above).

**Comment by AlexLewandowski** [comment]
Having the same problem, here's the trace:

`
Debugger entered--Lisp error: (file-missing "Setting current directory" "No such file or directory" "/home/user/")
  make-process(:name "doom-modeline-env" :buffer nil :command ("/usr/bin/python" "--version"))
  apply(make-process (:name "doom-modeline-env" :buffer nil :command ("/usr/bin/python" "--version")))
  start-process("doom-modeline-env" nil "/usr/bin/python" "--version")
  apply(start-process ("doom-modeline-env" nil "/usr/bin/python" "--version"))
  (let ((proc (apply (quote start-process) (append (list "doom-modeline-env" nil prog) args))) (parser callback)) (set-process-filter proc (function (lambda (_proc line) (condition-case nil (progn (funcall parser line)) (error nil))))))
  doom-modeline-env--get("/usr/bin/python" ("--version") (closure ((buffer . #<buffer py.py>) t) (prog-version) (save-current-buffer (set-buffer buffer) (setq doom-modeline-env--version (funcall doom-modeline-env--parser prog-version)) (run-hooks (quote doom-modeline-after-update-env-hook)))))
  (let ((default-directory (doom-modeline-project-root)) (buffer (current-buffer))) (run-hooks (quote doom-modeline-before-update-env-hook)) (setq doom-modeline-env--version doom-modeline-load-string) (doom-modeline-env--get doom-modeline-env--command doom-modeline-env--command-args (function (lambda (prog-version) (save-current-buffer (set-buffer buffer) (setq doom-modeline-env--version (funcall doom-modeline-env--parser prog-version)) (run-hooks (quote doom-modeline-after-update-env-hook)))))))
  (progn (let ((default-directory (doom-modeline-project-root)) (buffer (current-buffer))) (run-hooks (quote doom-modeline-before-update-env-hook)) (setq doom-modeline-env--version doom-modeline-load-string) (doom-modeline-env--get doom-modeline-env--command doom-modeline-env--command-args (function (lambda (prog-version) (save-current-buffer (set-buffer buffer) (setq doom-modeline-env--version (funcall doom-modeline-env--parser prog-version)) (run-hooks (quote doom-modeline-after-update-env-hook))))))))
  (if (and doom-modeline-env-version doom-modeline-env--command (executable-find doom-modeline-env--command) doom-modeline-env--command-args doom-modeline-env--parser) (progn (let ((default-directory (doom-modeline-project-root)) (buffer (current-buffer))) (run-hooks (quote doom-modeline-before-update-env-hook)) (setq doom-modeline-env--version doom-modeline-load-string) (doom-modeline-env--get doom-modeline-env--command doom-modeline-env--command-args (function (lambda (prog-version) (save-current-buffer (set-buffer buffer) (setq doom-modeline-env--version ...) (run-hooks ...))))))))
  doom-modeline-update-env()
  (progn (setq doom-modeline-env--command exe doom-modeline-env--command-args (cdr command-list) doom-modeline-env--parser doom-modeline-env-python-parser-fn) (doom-modeline-update-env))
  (if exe (progn (setq doom-modeline-env--command exe doom-modeline-env--command-args (cdr command-list) doom-modeline-env--parser doom-modeline-env-python-parser-fn) (doom-modeline-update-env)))
  (let* ((command-list (and t (funcall doom-modeline-env-python-command))) (exe (and command-list (executable-find (car command-list))))) (if exe (progn (setq doom-modeline-env--command exe doom-modeline-env--command-args (cdr command-list) doom-modeline-env--parser doom-modeline-env-python-parser-fn) (doom-modeline-update-env))))
  (progn (let* ((command-list (and t (funcall doom-modeline-env-python-command))) (exe (and command-list (executable-find (car command-list))))) (if exe (progn (setq doom-modeline-env--command exe doom-modeline-env--command-args (cdr command-list) doom-modeline-env--parser doom-modeline-env-python-parser-fn) (doom-modeline-update-env)))))
  (if doom-modeline-env-enable-python (progn (let* ((command-list (and t (funcall doom-modeline-env-python-command))) (exe (and command-list (executable-find (car command-list))))) (if exe (progn (setq doom-modeline-env--command exe doom-modeline-env--command-args (cdr command-list) doom-modeline-env--parser doom-modeline-env-python-parser-fn) (doom-modeline-update-env))))))
  doom-modeline-env-update-python()
  run-hooks(hack-local-variables-hook)
  hack-local-variables-apply()
  hack-local-variables(no-mode)
  run-mode-hooks(python-mode-hook)
  python-mode()
  set-auto-mode-0(python-mode nil)
  set-auto-mode()
  normal-mode(t)
  after-find-file(nil t)
  #f(compiled-function (buf filename nowarn rawfile truename number) #<bytecode 0x230147>)(#<buffer py.py> "/ssh:gh0st@204.191.189.57#7070:/home/gh0st/py.py" nil nil "/ssh:gh0st@204.191.189.57#7070:/home/gh0st/py.py" (263812 (-1 . 1)))
  apply(#f(compiled-function (buf filename nowarn rawfile truename number) #<bytecode 0x230147>) (#<buffer py.py> "/ssh:gh0st@204.191.189.57#7070:/home/gh0st/py.py" nil nil "/ssh:gh0st@204.191.189.57#7070:/home/gh0st/py.py" (263812 (-1 . 1))))
  find-file-noselect-1(#<buffer py.py> "/ssh:gh0st@204.191.189.57#7070:/home/gh0st/py.py" nil nil "/ssh:gh0st@204.191.189.57#7070:/home/gh0st/py.py" (263812 (-1 . 1)))
  find-file-noselect("/ssh:gh0st@204.191.189.57#7070:/home/gh0st/py.py" nil nil nil)
  find-file("/ssh:gh0st@204.191.189.57#7070:/home/gh0st/py.py")
  dired-find-file()
  funcall-interactively(dired-find-file)
  call-interactively(dired-find-file nil nil)
  command-execute(dired-find-file)
`

**Comment by orausch** [comment]
After updating all packages and doom the issue was resolved. Thanks!
