### ISSUE TITLE
[BUG] `g d` using `dumb-jump-go` instead of `cider-find-dwin` in clojure-mode

### ISSUE THREAD

**Issue by thiagokokada** [hlissner/doom-emacs#1378]
**Describe the bug**

`g d` stopped to call `cider-find-dwin` in `clojure-mode` and is using `dumb-jump-go` instead. So instead of `g d` going directly to the function definition, it opens a minibuffer in ivy with `Jump to`.

Using `, g g` works as it should.

My config: https://github.com/thiagokokada/dotfiles/tree/master/doom-emacs/.doom.d

Also, it seems that the new issue template is not working :sweat_smile: (had to get the file directly).

<details>
<pre>
**Steps to reproduce**
1. Open a Clojure file, start Cider REPL (`SPC m '`) and eval a file (`M-x cider-eval-buffer`)
2. Use `g d` on a function

**Expected behavior**
It should use `cider-find-dwin` or `cider-find-var`, instead it is using `dumb-jump-go`.

**System information**
- OS: gnu/linux (x86_64-pc-linux-gnu)
- Emacs: 26.1 (abr 08, 2019)
- Doom: 2.0.9 (HEAD -> develop, _upgrade/develop 9fc87049 2019-05-01 21:02:29 -0400)
- Graphic display: t (daemon: nil)
- System features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LIBSYSTEMD
- Details:
  ```elisp
  env bootstrapper: nil
  elc count: 0
  uname -a:  Linux 5.0.9 #1-NixOS SMP Sat Apr 20 07:17:05 UTC 2019 x86_64
  modules:   (:completion company (ivy +fuzzy) :ui doom hl-todo modeline nav-flash ophints (popup +all +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor evil file-templates fold (format +onsave) multiple-cursors rotate-text snippets :emacs dired electric eshell imenu term vc :tools ansible docker eval flycheck (lookup +docsets) magit make rgb terraform :lang cc clojure data elixir emacs-lisp hy javascript markdown nix (org +attach +babel +capture +export +habit +present +protocol) python ruby (sh +zsh) web :config default)
  packages:  (flymd lispyville sort-words uuidgen xterm-color (frame-fns :recipe (frame-fns :fetcher github :repo emacsmirror/frame-fns)) (frame-cmds :recipe (frame-cmds :fetcher github :repo emacsmirror/frame-cmds)) (zoom-frm :recipe (zoom-frm :fetcher github :repo emacsmirror/zoom-frm)))
  exec-path: (~/dev/nu/ios-cli ~/dev/nu/nucli ~/dev/nu/nudev ~/.npm-packages/bin ~/.emacs.d/bin ~/.local/bin /nix/store/xf59s14j0x8l34agxiq6n1rn54wia3b1-kitty-0.13.3/bin /nix/store/4y5lv3a8s42wd0w0wga9sfflf6x0s5wg-imagemagick-6.9.9-34/bin /nix/store/k1gmlgblqqywmnzqxzlm0a2473r14zx5-xsel-unstable-2018-01-10/bin ~/bin /run/wrappers/bin ~/.nix-profile/bin /nix/var/nix/profiles/default/bin /run/current-system/sw/bin /etc/profiles/per-user/thiagoko/bin /nix/store/z6x936aa6kfnwpz8fb34z28qng5prrp9-emacs-26.1/libexec/emacs/26.1/x86_64-pc-linux-gnu)
  ```

**Comment by hlissner** [comment]
Ah, my mistake. This was a regression from a recent change to `set-lookup-handlers!`. 0f21e2b should fix this. Let me know if that isn't the case and I will reopen this issue. Thanks for bringing it to my attention!

Also, wrt the issue templates, I was surprised by that as well. Perhaps it's because we're still on the develop branch that they haven't taken effect? According to the github documentation, they're in the right place. I'll look into it.
