### ISSUE TITLE
Whitespace coloring

### ISSUE THREAD

**Issue by haji-ali** [hlissner/doom-emacs#1384]
A recent update to doom-theme (that I still cannot find) trailing white space in red. How can I disable this? I thought I can control it with 'show-trailing-whitespace' but that variable is already nil.

ws-butler automatically removes these whitespaces on disk (even though it keeps showing them in some cases) making the alert unnecessary.

**Comment by hlissner** [comment]
You're right. This was redundant with `show-trailing-whitespace` (which is now on by default as of 72e8178e). This should be resolved as of 47f0f77. Let me know if that isn't the case and I will reopen this issue. Thanks for bringing it to my attention!
