### ISSUE TITLE
"M-." in Normal mode

### ISSUE THREAD

**Issue by iceiceiceJack** [hlissner/doom-emacs#1386]
im using the default config. "M-." in insert mode is  evil-goto-definition, but in normal mode it becomes evil-repeat-pop. i alway use "M-," and "M-." to view code. is that right?

**Comment by hlissner** [comment]
Evil binds `M-.` to `evil-repeat-pop-next`, so that is as expected. I suggest using `gd` (instead of `M-.`) and `C-o` (instead of `M-,`).

**Comment by iceiceiceJack** [comment]
Thanks, I'll get used to it.
