### ISSUE TITLE
[QUESTION] org-capture-templates

### ISSUE THREAD

**Issue by iceiceiceJack** [hlissner/doom-emacs#1391]
(setq org-capture-templates
      '(("d" "Dream" entry
         (file+headline +org-capture-todo-file "Dream")
         "* TODO %?\n  :PROPERTIES:\n  :CATEGORY: dream\n  :END:\n   %i\n"
         :prepend t :kill-buffer t))

I add above in my ~/.doom.d/config.el. When I startup the emacs, the org-capture-templates is current.After press "SPC X",  org-capture-templates become the default value. How can I change it

**Comment by UndeadKernel** [comment]
Doom adds it's own templates. Your template is therefore overwritten when org is started.
The solution is to add your capture to the list of templates after org loads.
Put the following in your `config.el`:
```lisp
(after! org
  (add-to-list 'org-capture-templates
             '(("d" "Dream" entry
               (file+headline +org-capture-todo-file "Dream")
               "* TODO %?\n :PROPERTIES:\n :CATEGORY: dream\n :END:\n %i\n"
               :prepend t :kill-buffer t))
```

**Comment by iceiceiceJack** [comment]
> Doom adds it's own templates. Your template is therefore overwritten when org is started.
> The solution is to add your capture to the list of templates after org loads.
> Put the following in your `config.el`:
> 
> ```lisp
> (after! org
>   (add-to-list 'org-capture-templates
>              '(("d" "Dream" entry
>                (file+headline +org-capture-todo-file "Dream")
>                "* TODO %?\n :PROPERTIES:\n :CATEGORY: dream\n :END:\n %i\n"
>                :prepend t :kill-buffer t))
> ```

I got it. Thanks
