### ISSUE TITLE
Doom theme not loaded

### ISSUE THREAD

**Issue by GavinFrazar** [hlissner/doom-emacs#1397]
When I start an emacs daemon and connect to it with emacsclient, the default doom-one theme is not loaded. Before 17e337a4348331816d24ba70a5b5d3e7b68af1d9 I could start a daemon and connect to it, and the doom-one theme would be loaded. I got around this by adding `(load-theme doom-one t)` to my config.el. On another note, this is the first issue I have ever submitted to a project like this. Is there anything I should have done that I did not do?

**Comment by hlissner** [comment]
> this is the first issue I have ever submitted to a project like this. Is there anything I should have done that I did not do?

Your report was perfectly fine! Normally, I'd want people to follow the [issue templates](https://github.com/hlissner/doom-emacs/tree/develop/docs/ISSUE_TEMPLATE), but they aren't working at the moment, so I'll overlook that. Fortunately, this was a simple issue, so I didn't need any more information.

Anyhow, e088a21 should resolve this issue. Let me know if that isn't the case and I will reopen this. Thanks for bringing it to my attention!
