### ISSUE TITLE
Can't change imenu-list-position

### ISSUE THREAD

**Issue by lvicentesanchez** [hlissner/doom-emacs#1402]
Hi! I'm trying to change the position of the imenu-list buffer but I have failed again and again. I have added this to my config.el:

```
(after! imenu
  (setq
    imenu-list-position 'left))
```

I have also tried with
```
(after! imenu-list
  (setq
    imenu-list-position 'left))
```

But the imenu-list allways appear on the right.

**Comment by hlissner** [comment]
The popup manager is opening the imenu-list window on the right, as per the popup rule in the emacs/imenu module:

```elisp
(set-popup-rule! "^\\*Ilist"
  :side 'right :size 35 :quit nil :select nil :ttl 0)
```

To change it to appear on the left, add this to your ~/.doom.d/config.el:

```elisp
(after! imenu-list
  (set-popup-rule! "^\\*Ilist"
    :side 'left :size 35 :quit nil :select nil :ttl 0))
```

I'll look into making the popup manager obey `imenu-list-position`.

**Comment by lvicentesanchez** [comment]
Thanks! That did the trick.
