### ISSUE TITLE
Different theme for gui and terminal

### ISSUE THREAD

**Issue by jbharat** [hlissner/doom-emacs#1403]
I have tried to switch themes for emacs gui and terminal. I run `emacs --daemon`.   I have the following code. 

in package.el

```
(package! nord-theme)
```

in config.el
```
(if (not (display-graphic-p))
      (load-theme 'nord t)
  (load-theme 'doom-one t)
  )
```

Running emacsclient in terminal loads nord theme correctly. But running emacsclient with frame never sets doom-one theme. It sets the stock emacs theme.

Is there a way to achieve this?

emacsclient frame screenshot
<img width="804" alt="Screen Shot 2019-05-11 at 12 06 13 pm" src="https://user-images.githubusercontent.com/6837979/57563773-47c04a00-73e5-11e9-9e42-a48a5fd09d5e.png">

**Comment by hlissner** [comment]
Unfortunately, there is no way to have different themes per frame. In Emacs, themes are global. You can only have one theme loaded at a time.

When the daemon is involved, it is possible to spawn GUI and TTY frames from the same session, and while the daemon is starting up `display-graphic-p` returns `nil`, and there is no way to predict what kind of frames the user will open in the future.

The closest you can get is to create a hook for `after-make-frame-functions` that will change the active frame depending on the display device:

```elisp
(defun reload-theme (frame)
  (with-selected-frame frame
    (if (display-graphic-p)
        (load-theme 'doom-one t)
      (load-theme 'nord t))))

(add-hook 'after-make-frame-functions #'reload-theme)
```

However, this will change the theme for all frames. So if you have a GUI frame and a TTY frame side by side, the theme change will affect both.

**Comment by hlissner** [comment]
Alternatively, you can avoid the daemon and open new instances of Emacs (with `emacs -nw`). Doom, out of the box, starts up fast enough that the daemon isn't really necessary. Though, it may be inconvenient if you want to modify the same buffers open in another session.

**Comment by jbharat** [comment]
Doom does start fast. But cmd+` wont switch between multiple emacs instances, when running multiple projects in each instance. I can use workspace module. But behaves weird with chunkwm. It creates an empty emacs window.

**Comment by jbharat** [comment]
I will close this anyway as its not possible with emacs at the moment. Thanks
