### ISSUE TITLE
ivy recent files

### ISSUE THREAD

**Issue by haji-ali** [hlissner/doom-emacs#1406]
For some reason, a new update in ivy seems to restrict virtual buffer to `caller`'s being `ivy-switch-buffer` or `counsel-switch-buffer`. This means that doom's buffer switcher cannot have virtual buffers (like recent files) enabled since its caller is `+ivy--switch-buffer`.

**Comment by flatwhatson** [comment]
This is caused by: https://github.com/abo-abo/swiper/commit/a9e81f8aaf15fd7e4b74b2889dc4ce57b4b55a3f
