### ISSUE TITLE
Purpose of +dired|sort-directories-first

### ISSUE THREAD

**Issue by haji-ali** [hlissner/doom-emacs#1414]
The function `+dired|sort-directories-first` is called to sort "List directories first in dired buffers." However, I thought the flag `--group-directories-first` in `dired-listing-switches` is doing this already?

The problem with `+dired|sort-directories-first` is that it sorts symbolic links before directories. 
Moreover, if `dired-omit-mode` is off, the two directories `.` and `..` appear after symbolic links rather than at the top.

PS: I fix this with
```(remove-hook 'dired-after-readin-hook #'+dired|sort-directories-first)```
but you might want to remove the hook from doom.

**Comment by hlissner** [comment]
I've removed the hook in 7577775. However, BSD `ls` does not support `--group-directories-first`, so BSD users won't get this sorting, which is acceptable (for now). Thanks for bringing it to my attention.
