### ISSUE TITLE
lsp-rename binding is missed

### ISSUE THREAD

**Issue by myrgy** [hlissner/doom-emacs#1417]
Hi @hlissner ,

**lsp-rename** shortcut is missed. Would you mind if we'll bind it to `SPS-c-r` while REPL would be binded to `SPS-c-R`?

**Comment by hlissner** [comment]
Sorry for the tremendously late response. I'm still not quite sold on these keybinds, but lsp-rename is now bound to `SPC c r`, as requested, so I'll consider this resolved. Thanks for bringing it to my attention!
