### ISSUE TITLE
Enable flyspell for prog modes

### ISSUE THREAD

**Issue by myrgy** [hlissner/doom-emacs#1418]
Hi @hlissner ,
Emacs allows to perform spell check only for comments in prog-mode.
this feature could be enabled using 
```lisp
  (add-hook 'prog-mode-hook 'flyspell-prog-mode)
```

Please, let me know if you are interested in MR.
Thank you in advance.

**Comment by hlissner** [comment]
I am aware of `flyspell-prog-mode`, but I do not want it enabled by default. Flyspell is notoriously and unavoidably slow, so I'll leave it to users to enable if they desire it.

**Comment by myrgy** [comment]
What about optional switch that will allow to enable it?
(Flyspell +prog) 
?

**Comment by hlissner** [comment]
I went with that and added +prog in 10cef7a. Thanks for bringing it to my attention!

**Comment by myrgy** [comment]
Thanks a lot!
