### ISSUE TITLE
How to bind custom function to keys?

### ISSUE THREAD

**Issue by forrestchang** [hlissner/doom-emacs#1419]
I have a function in `+bindings.el` in `.doom.d` called `jiayuan/org-capture-inbox`, and I want to bind it to `SPC I`, here is my code:

```elisp
(map! :leader
      :desc "Capture Inbox"                            "I" #'jiayuan/org-capture-inbox
      )
```

```elisp
;;;###autoload
(defun jiayuan/org-capture-inbox ()
  "Direct capture tasks to inbox"
  (lambda () (interactive) (org-capture nil "t")))
```

But when I use this key, I have this error message: 

```
command-execute: Wrong type argument: commandp, jiayuan/org-capture-inbox
```

And I can't use `M-x` to run my function. Do I miss something with lazy loading?

**Comment by hlissner** [comment]
The problem is that `jiayuan/org-capture-inbox` is not an interactive function, it is a function that _returns_ an interactive function. Here's what you want:

```elisp
(defune jiayuan/org-capture-inbox ()
  "Direct capture tasks to inbox"
  (interactive)
  (org-capture nil "t"))

(map! :leader :desc "Capture Inbox" "I" #'jiayuan/org-capture-inbox)
```

OR

```elisp
(map! :leader :desc "Capture Inbox" "I" (λ! (org-capture nil "t")))
```

**Comment by forrestchang** [comment]
@hlissner Thanks, it works now!
