### ISSUE TITLE
EIN Keybindings not working

### ISSUE THREAD

**Issue by coolsidd** [hlissner/doom-emacs#1420]
I enabled and set up the EIN module. Most of it works fine but the default bindings don't seem to work.
I don't use the custom evil bindings that are provided with doom. I continuously face this issue of default bindings not working in modules.
Is this the intended behavior? Are there any workarounds, so that I can get the default emacs bindings globally. Currently, I have defined a lot of custom bindings in config.el but it is getting tedious to do for each new module.

**Comment by hlissner** [comment]
If you are not an evil user, I recommend disabling the `:editor evil` module by commenting it out in your `doom!` block in `~/.doom.d/init.el`. Remember to run `bin/doom refresh` to ensure everything is set up correctly before restarting Emacs.

**Comment by coolsidd** [comment]
I have done so, yet the default bindings of EIN still dont work. This happens for nearly every module, including the ones that come with doom.

**Comment by coolsidd** [comment]
Example C-c C-c for execute cell.

**Comment by hlissner** [comment]
Ah, then it's possible this is a bug with [the emacs keybinds](https://github.com/hlissner/doom-emacs/blob/develop/modules/config/default/+emacs-bindings.el). Try adding this to your `~/.doom.d/config.el`:

```lisp
(setq doom-leader-alt-key "C-c d")
```

**Comment by coolsidd** [comment]
Solved it!. Thanks a lot for bearing with me. I was stuck on it for so long. Especially for something so trivial. I am closing this now... Really made my day!
