### ISSUE TITLE
Cannot automode into pug-mode

### ISSUE THREAD

**Issue by slipsnip** [hlissner/doom-emacs#1422]
I have installed your emacs-pug-mode plugin via packages.el and inside my config.el I have 
`(require 'pug-mode)
(setq
 projectile-project-search-path '("~/slipsnip/" "~/wip/")
 auto-mode-alist
   (cons '("\\.pug$" . text-mode) auto-mode-alist)
)`

However when I open and edit a .pug file, the mode is fundamental.  I can change into pug-mode with <SPC>-: pug-mode without problems but I would like for this to be automatic.  Completely a emacs virgin coming from vim.  What am I doing wrong or is this a problem with doom emacs?

**Comment by slipsnip** [comment]
My goodness, silly me I forgot to replace text-mode with pug-mode.  Please ignore my ignorance it is working now.

**Comment by hlissner** [comment]
No problem! But just to let you know, the `:lang web` module installs and configures pug-mode for you. You can enable it by uncommenting `web` under `:lang` in your `doom!` block (in `~/.doom.d/init.el`).

**Comment by slipsnip** [comment]
> No problem! But just to let you know, the `:lang web` module installs and configures pug-mode for you. You can enable it by uncommenting `web` under `:lang` in your `doom!` block (in `~/.doom.d/init.el`).

Thank you hlissner you are awesome,  I will do that now.  Was wondering about that I looked all over init.el but did not see any pug and assumed it was not there but now I realise its layers im activating.  I will be more careful in the future.  I can see it now in http://bit.ly/web-layer
