### ISSUE TITLE
"exec-path" problem on Windows. 

### ISSUE THREAD

**Issue by smallzhan** [hlissner/doom-emacs#1423]
Since the PATH separator on windows is ";" rather than ":",  after initialized, I've found that the variable 'exec-path' is set to something like 

> ("D" "\\Git\\usr\\bin;C" "\\WINDOWS\\system32;C" ...)

results that the command 'git' can't be found in my Emacs, thus "magit" failed.

I've checked the code, found in "core/core.el", the exec-path is sed by 
``` emacs-lisp
      (setq exec-path (append (split-string (getenv "PATH") ":")
```
which should be 
``` emacs-lisp
      (setq exec-path (append (split-string (getenv "PATH") ";")
```
on windows instead.

**Comment by hlissner** [comment]
Good catch. As of 0383e50 we now use the correct path separator. Let me know if it doesn't resolve the issue and I will reopen this. Thanks for bringing this to my attention.
