### ISSUE TITLE
(:lang markdown) Couldn't find "marked". ...

### ISSUE THREAD

**Issue by flyingns** [hlissner/doom-emacs#1424]
$ make doctor

I have already installed marked 2, why do I also prompt me with this information:

(:lang markdown) Couldn't find "marked". markdown-preview command won't work.

I installed marked 2 through the `mac app store` and `brew cask`.
All prompted the same information.

**Comment by hlissner** [comment]
It's referring to [marked](https://github.com/markedjs/marked), which can be acquired with `npm install -g marked`. I don't know if there is any relation to the MacOS App. I will update the lang/markdown readme.

**Comment by hlissner** [comment]
It is now documented in [lang/markdown's readme](https://github.com/hlissner/doom-emacs/blob/develop/modules/lang/markdown/README.org#markedjs), so I'll consider this resolved. Thanks for bringing it to my attention!
