### ISSUE TITLE
doom-big-font-mode doesn't use a separate font anymore

### ISSUE THREAD

**Issue by magnetophon** [hlissner/doom-emacs#1428]
Before my last doom up I could have a separate font for doom-big-font-mode.
Now I get the same font with just the size toggling.

I found the old behavior usefull because I like bitmap fonts for the normal font and truetype fonts for the big one.

I have:
```
(setq doom-font (font-spec :family "Dina" :size 8))
(setq doom-big-font (font-spec :family "RobotoMono Nerd Font" :size 26 :weight 'regular))
```
in my config, and that breaks doom-big-font-mode with the error: ``Cannot change font size`` , presumably because Dina doesn't have a big version.

Generating Doom info...
- OS: gnu/linux (x86_64-pc-linux-gnu)
- Emacs: 26.2 (mei 22, 2019)
- Doom: 2.0.9 (HEAD -> develop, origin/develop, origin/HEAD, _upgrade/develop 34b4ff12 2019-05-22 05:35:37 -0400)
- Graphic display: nil (daemon: nil)
- System features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2
- Details:
  ```elisp
  env bootstrapper: envvar-file
  elc count: 0
  uname -a:  Linux 4.19.44 #1-NixOS SMP Thu May 16 17:41:32 UTC 2019 x86_64
  modules:   (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor evil file-templates fold multiple-cursors rotate-text snippets :emacs dired electric vc :tools editorconfig eval flycheck flyspell (lookup +docsets) magit :lang data emacs-lisp markdown nix (org +attach +babel +capture +export +habit +present +protocol) sh :email mu4e :app irc :config default)
  packages:  (helm-mu mu4e-conversation)
  exec-path: (~/bin /run/wrappers/bin ~/.nix-profile/bin /nix/var/nix/profiles/default/bin /run/current-system/sw/bin /etc/profiles/per-user/bart/bin ~/.fzf/bin /nix/store/d190sssdr2pl541ndlsxyr6q7mz31685-emacs-26.2/libexec/emacs/26.2/x86_64-pc-linux-gnu)
  ```

**Comment by magnetophon** [comment]
Before my last ``doom up`` I could have a separate font for ``doom-big-font-mode``.
Now I get the same font with just the size toggling.

I found the old behavior usefull because I like bitmap fonts for the normal font and truetype fonts for the big one.

I have:
```
(setq doom-font (font-spec :family "Dina" :size 8))
(setq doom-big-font (font-spec :family "RobotoMono Nerd Font" :size 26 :weight 'regular))
```
in my config, and that breaks doom-big-font-mode with the error: ``Cannot change font size`` , presumably because Dina doesn't have a big version.

**Comment by hlissner** [comment]
I've brought back `doom-big-font-mode` in 977d587. It will fall back to it `doom-big-font-increment` if `doom-big-font` isn't set.

**Comment by magnetophon** [comment]
Wow, that was quick!  :1st_place_medal:  Thanks!
