### ISSUE TITLE
Org module private config error about key sequence

### ISSUE THREAD

**Issue by Atreus-Tantalus** [hlissner/doom-emacs#1431]
When i run ` doom/reload` i get this error:

`PRIVATE CONFIG ERROR: (doom-module-error modules/lang/org/config.el (error Key sequence SPC m d starts with non-prefix key SPC))`

**Comment by hlissner** [comment]
As of c949303, this issue should be resolved. Let me know if that isn't the case and I will reopen his issue. Thanks for bringing it to my attention.
