### ISSUE TITLE
featurep evil returns disabled even when enabled

### ISSUE THREAD

**Issue by drym3r** [hlissner/doom-emacs#1432]
Hi
Today I upgraded to the last commit (febeed252629cad0874bf0b76e82aae6cd6f63aa) and my configuration broke. My summarized configuration is:
```emacs-lisp
(doom! :config (default +smartparens +evil +bindings))
```
This won't work because it doesn't detect that the evil feature is enabled. In this line, instead to load the evil configuration, it loads the emacs one. When I added to my configuration the `:feature evil` parameter, it worked like a charm. My guess is that `featurep` searchs the `:feature` parameter, but I haven't investigated it.

Thanks for your work, doom is very cool!

**Comment by iceiceiceJack** [comment]
+evil is not a flag of **default**  module. evil load in **:editor evil**

**Comment by hlissner** [comment]
You need to either have the `:editor evil` module enabled, or evil installed and loaded by the time the `:config default` module loads. The `:config default` module does not check for an `+evil` flag.
