### ISSUE TITLE
Eshell reports error with Emacs 25.3.1 and CentOS 7

### ISSUE THREAD

**Issue by whjiang** [hlissner/doom-emacs#1442]
I tried to run eshell on Mac with Emacs 26.2, and everything is fine. 

But, when I running eshell on CentOS 7 with Emacs 25.3.1, any command I tried in eshell will report error:
`Symbol's function definition is void: eshell-input-filter-initial-space`.

**Comment by hlissner** [comment]
Could you produce a backtrace for this error? i.e. `M-x toggle-debug-on-error`, then reproduce the error.

**Comment by whjiang** [comment]
![image](https://user-images.githubusercontent.com/5162753/58602565-00c8c480-82c0-11e9-86f5-63b421487a66.png)
![image](https://user-images.githubusercontent.com/5162753/58602769-ad0aab00-82c0-11e9-8be5-92efe5339e9b.png)

**Comment by hlissner** [comment]
Looks like `eshell-input-filter-initial-space` was introduced in Emacs 26. I've inlined it in a583d69 which should resolve your issue. If that isn't the case, let me know and I will reopen the issue. Thanks for bringing it to my attention!
