### ISSUE TITLE
Error on startup - develop

### ISSUE THREAD

**Issue by shanavas786** [hlissner/doom-emacs#1447]
Doom emacs fails to start up with error
```
condition-case: Error in a Doom startup hook: +doom-dashboard|init, (error "objed-state is not a defined segment")
```
commit [0c743afcfd](https://github.com/hlissner/doom-emacs/commit/0c743afcfd31f5bd586759eb427093baab86cb7b)

**Comment by flatwhatson** [comment]
You need to run `doom update` to get a recent version of doom-modeline which has this segment defined.

**Comment by shanavas786** [comment]
Thanks. That fixes it.
