### ISSUE TITLE
Can't create new file with  "C-x C-f <file-name> RET"

### ISSUE THREAD

**Issue by smallzhan** [hlissner/doom-emacs#1450]
A minimal  init.el is as follows, just enable ivy and childframe.

```emacs-lisp
(doom! :completion
       (ivy
       +childframe)

       :ui
       doom
       doom-dashboard)
```

C-x C-f binds to counsel-find-file, but I've found that when creating a new file with C-x C-f,  after input the filename, nothing happened with RET typed.  When type `C-M-j` instead, the file can be created.    

I've also tried an `emacs -q` with next minimal config, `C-x C-f` create new files smoothly.

```emacs-lisp
;;; some load-path config.
;;; (add-to-list 'load-path .....)

(require 'ivy)
(ivy-mode +1)

(require 'counsel)
(require 'posframe)
(require 'ivy-posframe)
(setq ivy-display-function #'ivy-posframe-display)
(ivy-posframe-enable)
```

**Comment by hlissner** [comment]
Either of these should work:

+ `C-x C-f new-file RET RET`
+ `(setq confirm-nonexistent-file-or-buffer nil)`
+ `(setq confirm-nonexistent-file-or-buffer 'after-completion)`

**Comment by smallzhan** [comment]
> * `C-x C-f new-file RET RET`

The first method can't work with `(ivy +childframe)`, seems `RET` action can't be received by child frame.  With `ivy` instead of `(ivy +childframe)` in init file, after first `RET`, there is a `confirm` in minibuffer and the second `RET`, the file created.

> * `(setq confirm-nonexistent-file-or-buffer nil)`
> * `(setq confirm-nonexistent-file-or-buffer 'after-completion)` ; the vanilla default

These two methods,  new file could be created successfully with a single `RET`.

**Comment by smallzhan** [comment]
I've tried `(setq confirm-nonexistent-file-or-buffer t)` with `emacs -q` and only to find that `C-x C-f new-file RET` can't create new file either.  So maybe it's something wrong with `ivy` or `ivy-posframe`.

**Comment by smallzhan** [comment]
Just now I've updated the package `ivy-posframe` from `20190530` to `20190601`,  the issue solved.   
`C-x C-f new-file RET RET` now works smoothly.
