### ISSUE TITLE
`doom upgrade` needs a `doom refresh` if a module is updated

### ISSUE THREAD

**Issue by thiagokokada** [hlissner/doom-emacs#1453]
After commit https://github.com/hlissner/doom-emacs/commit/93876028b47ae2bea961201a71ba6e3b42c30b94, `doom upgrade` works for package updating too. However, If you run `doom upgrade` and some package updates, running Emacs afterwards will return a message asking you to run `doom refresh` because it is missing some modules.

So I aliased `doom-upgrade` to `doom upgrade && doom refresh`, however I don't think this should be necessary and `doom upgrade` itself should take care of refreshing its packages.

**Comment by hlissner** [comment]
A `doom refresh` should not be necessary after package updates, because a partial `doom refresh` _ought_ to be performed by all of `bin/doom`'s package management commands, as necessary. If that isn't happening, something strange is certainly going on here. I'll look into it soon.

**Comment by seanfarley** [comment]
This is also happening to me. Running `doom upgrade` gave me the following error when opening emacs:

```
: Your package autoloads are missing! Run ‘bin/doom refresh’ to regenerate them
```

Commit:

```
$ git show
commit 32e266cfb4be41951c8bbffd516ccf9456beeeb8 (HEAD -> develop, origin/develop, _upgrade/develop)
Merge: 0c743afc aa64cf94
Author: Henrik Lissner <henrik@lissner.net>
Date:   Fri May 31 22:01:10 2019 -0400

    Merge pull request #1446 from siddharthshekar/kill-current-buffer-fix

    Replace kill-this-buffer with kill-current-buffer
```

**Comment by bittopaz** [comment]
same here

**Comment by ashkan-leo** [comment]
same here

**Comment by tchajed** [comment]
I've also run into this. I believe it happened when the set of dependency packages changed, since when I ran `doom refresh` to fix it new packages were installed (or deleted).

**Comment by hlissner** [comment]
As of 29293aa this should be resolved. Let me know if that isn't the case and I will reopen the issue. Thanks for bringing it to my attention!
