### ISSUE TITLE
The hint for finishing table.el editing is quite confusing

### ISSUE THREAD

**Issue by whjiang** [hlissner/doom-emacs#1455]
![image](https://user-images.githubusercontent.com/5162753/58755768-1555c880-851d-11e9-831d-44a63cb4e757.png)

At the top, the hint says "Edit, then exit with 'C-c C-c'". But, when I finishing editing and pressed C-c C-c, I got the menu at the bottom. From it, I don't know how to save and exit table editing mode.

**Comment by hlissner** [comment]
Are you still experiencing this issue? If so, please include your `M-x doom/info`.

**Comment by whjiang** [comment]
I can't reproduce this issue now.
