### ISSUE TITLE
emacs server hangs when opening new frame

### ISSUE THREAD

**Issue by bricewge** [hlissner/doom-emacs#1456]
When using emacs server, opening a new frame can hangs without any text displayed or mini-buffer available. Even after #1451 and https://github.com/wbolster/emacs-direnv/issues/45 are applied.

It comes from the `+doom-dashboard-pwd-policy` which change the dashboard `pwd` to the last visited project by default. Setting to`nil` doesn't work even though it's documented as "default-directory will never change". Fortunately setting it to `"~"` seems to do the trick even if the dashboard's `default-directory` keep changing...

To reproduce it, it's the same as https://github.com/hlissner/doom-emacs/issues/1444#issuecomment-497369100:
1. Opening a file as sudo and entering correct password
2. `sudo --remove-timestamp`
3. `tramp-cleanup-all-connections`
4. Close the current frame
4. Open a new frame, emacs will ask for the credentials silently (present in logs) but doesn't display it nor inform us about it

**Comment by hlissner** [comment]
Now that #1451 (and #1444) have been resolved, I'm hoping this one has too. Please update and see if this is still an issue.

**Comment by bricewge** [comment]
No it's is still present. Even though it's somewhat related to the two 2 issue you linked it's specific to `doom-dashboard`. What happen is when the new frame is opened, emacs is waiting for TRAMP's credentials to accede to the `default-directory`, because the credentials have been removed or expired. But for whatever reason nothing is displayed until the credentials are entenred, which can't be done.

**Comment by hlissner** [comment]
1. What is the value of `+doom-dashboard--last-cwd` when this happens? 
2. Are you perhaps opening this frame from a remote file?
3. Does this fix your issue:

```elisp
(defun +doom-dashboard*reload-maybe ()
  (cond ((+doom-dashboard-p (current-buffer))
         (let (+doom-dashboard-inhibit-refresh)
           (ignore-errors (+doom-dashboard-reload))))
        ((and (not (file-remote-p default-directory))
              (doom-real-buffer-p (current-buffer)))
         (setq +doom-dashboard--last-cwd default-directory)
         (+doom-dashboard-update-pwd))))
(advice-add #'+doom-dashboard|reload-maybe :override #'+doom-dashboard*reload-maybe)
```

**Comment by bricewge** [comment]
1. Something like `"/sudo:root@localhost:/etc/hostname"` 
2. I don't understand the question. I used this command `emacsclient -nc -a ""`
3. Yes it fixes it! Thanks!
