### ISSUE TITLE
Customize keybinding delay

### ISSUE THREAD

**Issue by Npahlfer** [hlissner/doom-emacs#1465]
E.g. pressing `SPC` and then closing the which-key menu with `ESC` and then `/` to search for something. Then I get "SPC M-/  is undefined".

Is it possible to customize that delay for when it's listening for the next keybinding? 
Currently it feels a bit slow.

I have set `(setq which-key-idle-delay 0)`.

Thanks in advance!

**Comment by hlissner** [comment]
As far as I know, Emacs cannot "time out" incomplete key sequences. If it perceives a key to be a prefix key (which ESC is in terminal Emacs -- a special one), then it will wait forever for you to supply the rest of the key sequence.

To terminal Emacs, ESC + x is equivalent to Meta+. You're better off using `C-g` to "cancel" a key sequence instead. Mind you, neither ESC nor C-g truly cancel the current key sequence (when they work), we merely rely on the fact that a) Emacs will stop waiting for keys once we complete the key sequence, b) an undefined keybind will effectively do nothing (besides complain ineffectually) and c) ESC or C-g are unlikely to be bound at the end of any key sequence (though that isn't the case for ESC in terminal Emacs).

**Comment by d1egoaz** [comment]
@Npahlfer 

This worked for me: `which-key-idle-delay 0.1`

I would not recommend using `0`, see variable docs:
```lisp
(defcustom which-key-idle-delay 1.0
  "Delay (in seconds) for which-key buffer to popup. This
 variable should be set before activating `which-key-mode'.

A value of zero might lead to issues, so a non-zero value is
recommended
(see https://github.com/justbur/emacs-which-key/issues/134)."
  :group 'which-key
  :type 'float)
```

**Comment by Npahlfer** [comment]
@hlissner I found out that which-key has a abort function:
 `:desc "Which key abort"  "ESC" #'which-key-abort` so I ended up using that as a keybinding under leader and a few other prefixes. 

Thank you @d1egoaz I updated that and along with the above; it's working as I wanted it to.
