### ISSUE TITLE
can't use a fork of doom-themes

### ISSUE THREAD

**Issue by bricewge** [hlissner/doom-emacs#1466]
Trying to use a fork of `doom-themes`, at startup I get: `(error "Unable to find theme file for ‘doom-one’")`. To reproduce, add to `packages.el`:
``` elisp
(package! doom-themes
  :recipe (:fetcher github :repo "bricewge/emacs-doom-themes" :branch "hl-fill-column"))
```

https://github.com/hlissner/doom-emacs/issues/374 would probably help

**Comment by hlissner** [comment]
Please see my response in #1469, regarding the `:files` property.

**Comment by bricewge** [comment]
Oh thank you! Tweaking your snippet with `:files ("*.el" "themes/*.el")` fixed it.

It didn't occur to me that the file loading behavior was different betwen `elpa` and `quelpa`. Hopefully this quirk will go away when switching to `straight.el`.

**Comment by hlissner** [comment]
>It didn't occur to me that the file loading behavior was different betwen elpa and quelpa

@bricewge I'm not sure what you mean. Elpa is incapable of downloading straight from a git repo and this _is_ quelpa behavior we're talking about, but I'm glad it solved your issue.
