### ISSUE TITLE
All Melpa Packages are available for Doom Emacs?

### ISSUE THREAD

**Issue by ofenerci** [hlissner/doom-emacs#1468]
Hello, 
I tried to install a package named  company-reftex from Melpa Repository  ` s://melpa.org/#/company-reftex`. The package doesn't show itself with a command `M-x list-packages`. I wonder why this is so?

**Comment by Tiv0w** [comment]
Hey,
Have you tried to run `M-x package-refresh-contents` before doing `M-x list-packages` ?

**Comment by ofenerci** [comment]
Hello, 
you are right. My mistake!

**Comment by Tiv0w** [comment]
You're welcome :+1:
