### ISSUE TITLE
How to install a package from github repo?

### ISSUE THREAD

**Issue by ofenerci** [hlissner/doom-emacs#1469]
Hello, 
Today my doom-emacs day! I am just figuring out how to use it. I am trying to install some packages which is not in MELPA packages. I put the line below inside `packages.el` file. 

> (package! another-package :recipe (:fetcher github :repo "madsdk/yasnippets-latex"))

But I am getting the error below:

```
Looking for packages to install...
Installing another-package
  FATAL ERROR: (error Failed to checkout ‘another-package’: ‘No matching file(s) found in /home/ofenerci/.doom-emacs/.local/packages/quelpa/build/another-package/: (*.el *.el.in dir *.info *.texi *.texinfo doc/dir doc/*.info doc/*.texi doc/*.texinfo (:exclude .dir-locals.el test.el tests.el *-test.el *-tests.el))’)
  Run again with the -d flag for detail

I think the error is related with my extra line of code. I remove the line, the error goes away! 
```

**Comment by hlissner** [comment]
By default, quelpa will only grab `{package-name}.el` from the specified repo. To include other files, like the `snippets/` subdirectory, you must specify `:files`:

```elisp
(package! another-package 
  :recipe (:fetcher github :repo "madsdk/yasnippets-latex" :files ("*.el" "snippets/"))
```

However, I took a peek at [madsdk/yasnippets-latex](https://github.com/madsdk/yasnippets-latex) and noticed there is no yasnippets-latex.el file, which may cause problems. Quelpa may not be able to install a package that lacks an elisp file (and subsequently, a package header with the needed package metadata). If that's the case, you'll have no choice but to clone it yourself and either symlink `snippets` to `~/.doom.d/snippets/latex-mode`, or add the path to `snippets` to `yas-snippet-dirs`:

```elisp
;; in ~/.doom.d/config.el
(after! yasnippet
  (add-to-list 'yas-snippet-dirs "path/to/yasnippets-latex/snippets"))
```
``

**Comment by hlissner** [comment]
I'll consider this issue resolved. Let me know if that isn't so and I will reopen the issue. Feel free to follow up here in any case.
