### ISSUE TITLE
Newest version of format-all doesn't work with doom (private function names changed)

### ISSUE THREAD

**Issue by Strayer** [hlissner/doom-emacs#1470]
Commit https://github.com/lassik/emacs-format-all-the-code/commit/f3ed09c430c80d17fcc34f130f32072177f4ef2b changed some function names in format-all and this apparently causes doom-emacs to break with the following error message:

`let*: Autoloading file /Users/strayer/.emacs.d/.local/packages/elpa/format-all-20190606.853/format-all.elc failed to define function format-all-probe`

See https://github.com/lassik/emacs-format-all-the-code/issues/36#issuecomment-499544541 for reference.

**Comment by nate** [comment]
pinning the package to the commit before the changes upstream fixed it for me: 

```elisp
(package! format-all :recipe (:fetcher github :repo "lassik/emacs-format-all-the-code" :commit "7ab5345d83dad3df1f162c24e6f28cb7307975fd"))
```

Once #1477 is rolled out this could be removed.
