### ISSUE TITLE
How do I make debugger work with pdb?

### ISSUE THREAD

**Issue by chris-transloc** [hlissner/doom-emacs#1471]
The module definition has limited the commands to only a small subset of what realgud supports. How do I tell it not to limit them?

**Comment by chris-transloc** [comment]
Never mind, I found the `:pdb` command. I was trying to use `realgud:pdb` which is the one doom hides for some reason.

**Comment by hlissner** [comment]
I'm afraid the :tools debugger module is incomplete, has been neglected for a couple years and is overdue for a rewrite. For the time being, you can autoload additional commands by adding a `def-package!` statement to `~/.doom.d/config.el`:

```elisp
(def-package! realgud
  :commands realgud:pdb)
```
