### ISSUE TITLE
Pulling dune repo fails with "would clobber existing tag", requires manual intervention

### ISSUE THREAD

**Issue by tchajed** [hlissner/doom-emacs#1473]
`doom upgrade` fails on the dune package (from the OCaml module) because of a force-pushed tag, with the error

```
From https://github.com/ocaml/dune
 ! [rejected]          1.10.0     -> 1.10.0  (would clobber existing tag)
```

To get around this you need to force pull the repo manually:

```
cd ~/.emacs.d/.local/packages/quelpa/build/dune
git pull --tags --force
```

**Comment by brabalan** [comment]
Thank you for the workaround, this was leaving me stumped!

**Comment by hlissner** [comment]
I'm not sure what can be done about this. Doom uses [quelpa](https://framagit.org/steckerhalter/quelpa) to handle the git side of things. It doesn't expose an option to force pulls/fetches, much less modify the shell command arguments for any of its backends. A `--force` could be injected [here](https://framagit.org/steckerhalter/quelpa/blob/master/quelpa.el#L880), so perhaps it should be PRed/requested upstream.

I've got [straight](https://github.com/raxod502/straight.el) in my crosshairs too, to replace package.el+quelpa, but skimming it briefly, I don't think it can handle this case either.

**Comment by rgrinberg** [comment]
I'll use this chance to apologize again for tagging 1.10 twice in dune. Will hopefully not happen again once our new release process is in place.

@hlissner Indeed, I'm eager to see straight inside doom. I believe it wouldn't be that hard to make straight handle this. It just would require some user confirmation to make sure any user created tags aren't overwritten.

**Comment by brabalan** [comment]
It happened again (on `develop`). I guess it is time to jump to the `straight` branch.

**Comment by rprimus** [comment]
Tue Aug  6 10:43:56 BST 2019

Now happening with `ocamlformat`.

```
rror in Doom Emacs core: error, "Failed to checkout ‘ocamlformat’: ‘Command ’(env LC_ALL=C /usr/local/bin/timeout -k 60 600 git fetch --all --tags)’ exited with non-zero status 1: Fetching origin
HEAD is now at 48f1936 Enable literal replacement. Otherwise, replacement including backslashes acts weird.
'2011-12-04 10:39:07 +0900'Fetching origin
HEAD is now at 40cc1ac Generalize org-yt-display-inline-images
'2018-05-27 02:45:13 +0200'Fetching origin
HEAD is now at 8b4f0aa Merge pull request #1 from notetiene/master
'2017-10-15 22:35:19 +0200'Fetching origin
From https://github.com/ocaml-ppx/ocamlformat
   8c06ec4..eca35f1  master     -> origin/master
 + 73c610b...bdf73a6 v0.11.0    -> origin/v0.11.0  (forced update)
 ! [rejected]        0.11.0     -> 0.11.0  (would clobber existing tag)
error: Could not fetch origin
```

**Comment by hlissner** [comment]
Now that we're using straight, this issue and issues like it have been resolved. Let me know if that isn't the case and I will reopen it. Thanks for bringing it to my attention!
