### ISSUE TITLE
Issue when trying to `doom compile-core`

### ISSUE THREAD

**Issue by finnkauski** [hlissner/doom-emacs#1475]
# Error
Having this error when trying to compile with `doom compile-core`:
https://gist.github.com/finnkauski/37412d3c4c551c3b188824ff76a12a3e

## OS: 
MacOS
## Emacs Version:
This is GNU Emacs, a part of the GNU operating system.

GNU Emacs 26.2 (build 1, x86_64-apple-darwin17.7.0, NS appkit-1561.60 Version 10.13.6 (Build 17G4015))
 of 2019-06-07
Copyright (C) 2019 Free Software Foundation, Inc.

## Installed with: 
brew install emacs-plus

**Comment by hlissner** [comment]
Sorry for the late response. A lot has changed since this was opened. Is it still an issue?
