### ISSUE TITLE
How to use Latexmk?

### ISSUE THREAD

**Issue by isentropic** [hlissner/doom-emacs#1478]
The #391 issue was about support of the latexmk, however, I could not find guidelines on using it. Could anyone help out with that?

**Comment by hlissner** [comment]
I am not familiar with latexmk personally, but adding the `+latexmk` flag to `:lang latex` in your doom! block (in `~/.doom.d/init.el`) will enable support for it. e.g. `:lang (latex +latexmk)`.

Using it beyond that I cannot help with.

**Comment by isentropic** [comment]
For anyone interested, press `C-c` and  `C-c` to open compiler menu and then select latexmk, first make sure to get everything updated with doom binaries.
