### ISSUE TITLE
" SPC * " wrong-type-argument 

### ISSUE THREAD

**Issue by iceiceiceJack** [hlissner/doom-emacs#1479]
when i use `SPC *`,   (wrong-type-argument char-or-string-p nil)

**Comment by iceiceiceJack** [comment]
Debugger entered--Lisp error: (wrong-type-argument char-or-string-p nil)
  ivy--done(nil)
  ivy-done()
  funcall-interactively(ivy-done)
  call-interactively(ivy-done nil nil)
  command-execute(ivy-done)
  read-from-minibuffer("[tx_plus_proj] grep: " "boolNeedPostProcess" (keymap (keymap (C-return closure (t) nil (interactive) (ivy-set-action (function +ivy-git-grep-other-window-action)) (setq ivy-exit (quote done)) (exit-minibuffer)) (67108896 . ivy-call-and-recenter) (24 keymap (4 . counsel-cd)) (67108903 . swiper-avy) (27 keymap (113 . counsel-git-grep-query-replace)) (12 . ivy-done)) keymap (12 . ivy-alt-done) (67108896 . ivy-call-and-recenter) (33554443 . scroll-down-command) (33554442 . scroll-up-command) (11 . previous-line) (2 . backward-word) (1 . move-beginning-of-line) (26 closure (t) nil (interactive) (condition-case nil (progn (call-interactively (function undo))) (error nil))) (escape . abort-recursive-edit) (36 . ivy-magic-read-file-env) (3 keymap (5 . +ivy/woccur) (19 . ivy-rotate-sort) (1 . ivy-toggle-ignore) (15 . ivy-occur)) (67108903 . ivy-avy) (33554464 . ivy-restrict-to-matches) (15 . ivy-dispatching-done-hydra) (22 . yank) (prior . ivy-scroll-down-command) (next . ivy-scroll-up-command) (7 . minibuffer-keyboard-quit) (right . ivy-forward-char) (32 . self-insert-command) (18 . evil-paste-from-register) (19 . counsel-minibuffer-history) (remap keymap (describe-mode . ivy-help) (kill-ring-save . ivy-kill-ring-save) (kill-whole-line . ivy-kill-whole-line) (kill-line . ivy-kill-line) (scroll-down-command . ivy-scroll-down-command) (scroll-up-command . ivy-scroll-up-command) (end-of-buffer . ivy-end-of-buffer) (beginning-of-buffer . ivy-beginning-of-buffer) (kill-word . ivy-kill-word) (forward-char . ivy-forward-char) (delete-char . ivy-delete-char) (backward-kill-word . ivy-backward-kill-word) (backward-delete-char-untabify . ivy-backward-delete-char) (delete-backward-char . ivy-backward-delete-char) (previous-line . ivy-previous-line) (next-line . ivy-next-line)) (9 . ivy-partial-or-done) (10 . next-line) (27 keymap (1 . ivy-read-action) (15 . ivy-dispatching-call) (111 . hydra-ivy/body) (105 . ivy-insert-current) (106 . ivy-yank-word) (114 . ivy-toggle-regexp-quote) (16 . ivy-previous-line-and-call) (14 . ivy-next-line-and-call) (118 . ivy-scroll-down-command) (112 . ivy-previous-history-element) (110 . ivy-next-history-element) (10 . ivy-immediate-done) (13 . ivy-call)) (mouse-3 . ivy-mouse-dispatching-done) (mouse-1 . ivy-mouse-done) (down-mouse-1 . ignore) (13 . ivy-done)) nil counsel-git-grep-history)
  ivy-read("[tx_plus_proj] grep: " counsel-projectile-grep-function :initial-input "boolNeedPostProcess" :dynamic-collection t :keymap (keymap (C-return closure (t) nil (interactive) (ivy-set-action (function +ivy-git-grep-other-window-action)) (setq ivy-exit (quote done)) (exit-minibuffer)) (67108896 . ivy-call-and-recenter) (24 keymap (4 . counsel-cd)) (67108903 . swiper-avy) (27 keymap (113 . counsel-git-grep-query-replace)) (12 . ivy-done)) :history counsel-git-grep-history :action (1 ("o" counsel-git-grep-action "default") ("p" counsel-projectile-grep-action-switch-project "switch project")) :unwind #f(compiled-function () #<bytecode 0x487b0ce1>) :caller counsel-projectile-grep)
  counsel-projectile-grep(" -R")
  (if all-files (let* ((vnew (symbol-function (function ignore))) (vnew (symbol-function (function ignore))) (old (symbol-function (function projectile-ignored-files-rel))) (old (symbol-function (function projectile-ignored-directories-rel)))) (unwind-protect (progn (fset (function projectile-ignored-files-rel) vnew) (fset (function projectile-ignored-directories-rel) vnew) (counsel-projectile-grep args)) (fset (function projectile-ignored-files-rel) old) (fset (function projectile-ignored-directories-rel) old))) (counsel-projectile-grep args))
  (let ((args (if recursive " -R")) (counsel-projectile-grep-initial-input query)) (if all-files (let* ((vnew (symbol-function (function ignore))) (vnew (symbol-function (function ignore))) (old (symbol-function (function projectile-ignored-files-rel))) (old (symbol-function (function projectile-ignored-directories-rel)))) (unwind-protect (progn (fset (function projectile-ignored-files-rel) vnew) (fset (function projectile-ignored-directories-rel) vnew) (counsel-projectile-grep args)) (fset (function projectile-ignored-files-rel) old) (fset (function projectile-ignored-directories-rel) old))) (counsel-projectile-grep args)))
  (cond ((eq engine (quote grep)) (let ((args (if recursive " -R")) (counsel-projectile-grep-initial-input query)) (if all-files (let* ((vnew (symbol-function ...)) (vnew (symbol-function ...)) (old (symbol-function ...)) (old (symbol-function ...))) (unwind-protect (progn (fset ... vnew) (fset ... vnew) (counsel-projectile-grep args)) (fset (function projectile-ignored-files-rel) old) (fset (function projectile-ignored-directories-rel) old))) (counsel-projectile-grep args)))) ((eq engine (quote ag)) (let ((args (concat (if all-files " -a") (if recursive nil " --depth 1")))) (counsel-ag query directory args (format prompt args)))) ((eq engine (quote rg)) (let ((args (concat (if all-files " -uu") (if recursive nil " --maxdepth 1")))) (counsel-rg query directory args (format prompt args)))) ((eq engine (quote pt)) (let ((counsel-pt-base-command (concat counsel-pt-base-command (if all-files " -U") (if recursive nil " --depth=1"))) (default-directory directory)) (counsel-pt query))) (t (error "No search engine specified")))
  (let ((ivy-more-chars-alist (if query (quote ((t . 1))) ivy-more-chars-alist))) (cond ((eq engine (quote grep)) (let ((args (if recursive " -R")) (counsel-projectile-grep-initial-input query)) (if all-files (let* ((vnew ...) (vnew ...) (old ...) (old ...)) (unwind-protect (progn ... ... ...) (fset ... old) (fset ... old))) (counsel-projectile-grep args)))) ((eq engine (quote ag)) (let ((args (concat (if all-files " -a") (if recursive nil " --depth 1")))) (counsel-ag query directory args (format prompt args)))) ((eq engine (quote rg)) (let ((args (concat (if all-files " -uu") (if recursive nil " --maxdepth 1")))) (counsel-rg query directory args (format prompt args)))) ((eq engine (quote pt)) (let ((counsel-pt-base-command (concat counsel-pt-base-command (if all-files " -U") (if recursive nil " --depth=1"))) (default-directory directory)) (counsel-pt query))) (t (error "No search engine specified"))))
  (let* ((project-root (or (doom-project-root) default-directory)) (directory (or in project-root)) (default-directory directory) (engine (or engine (let* ((--cl-var-- +ivy-project-search-engines) (tool nil) (--cl-var-- t) --cl-var--) (while (and (consp --cl-var--) (progn ... ...)) (setq --cl-var-- (cdr --cl-var--))) --cl-var--) (and (or (executable-find "grep") (executable-find "git")) (quote grep)) (error "No search engine specified (is ag, rg, pt or git installed?)"))) (query (or (if query (rxt-quote-pcre query)) (if (use-region-p) (progn (let (... ...) (if ... ...)))))) (prompt (format "%s%%s %s" (symbol-name engine) (cond ((equal directory default-directory) "./") ((equal directory project-root) (projectile-project-name)) ((file-relative-name directory project-root)))))) (require (quote counsel)) (let ((ivy-more-chars-alist (if query (quote ((t . 1))) ivy-more-chars-alist))) (cond ((eq engine (quote grep)) (let ((args (if recursive " -R")) (counsel-projectile-grep-initial-input query)) (if all-files (let* (... ... ... ...) (unwind-protect ... ... ...)) (counsel-projectile-grep args)))) ((eq engine (quote ag)) (let ((args (concat ... ...))) (counsel-ag query directory args (format prompt args)))) ((eq engine (quote rg)) (let ((args (concat ... ...))) (counsel-rg query directory args (format prompt args)))) ((eq engine (quote pt)) (let ((counsel-pt-base-command (concat counsel-pt-base-command ... ...)) (default-directory directory)) (counsel-pt query))) (t (error "No search engine specified")))))
  (progn (let ((--cl-keys-- --cl-rest--)) (while --cl-keys-- (cond ((memq (car --cl-keys--) (quote (:query :in :all-files :recursive :allow-other-keys))) (setq --cl-keys-- (cdr (cdr --cl-keys--)))) ((car (cdr (memq ... --cl-rest--))) (setq --cl-keys-- nil)) (t (error "Keyword argument %s not one of (:query :in :all-files :recursive)" (car --cl-keys--)))))) (let* ((project-root (or (doom-project-root) default-directory)) (directory (or in project-root)) (default-directory directory) (engine (or engine (let* ((--cl-var-- +ivy-project-search-engines) (tool nil) (--cl-var-- t) --cl-var--) (while (and ... ...) (setq --cl-var-- ...)) --cl-var--) (and (or (executable-find "grep") (executable-find "git")) (quote grep)) (error "No search engine specified (is ag, rg, pt or git installed?)"))) (query (or (if query (rxt-quote-pcre query)) (if (use-region-p) (progn (let ... ...))))) (prompt (format "%s%%s %s" (symbol-name engine) (cond ((equal directory default-directory) "./") ((equal directory project-root) (projectile-project-name)) ((file-relative-name directory project-root)))))) (require (quote counsel)) (let ((ivy-more-chars-alist (if query (quote (...)) ivy-more-chars-alist))) (cond ((eq engine (quote grep)) (let ((args ...) (counsel-projectile-grep-initial-input query)) (if all-files (let* ... ...) (counsel-projectile-grep args)))) ((eq engine (quote ag)) (let ((args ...)) (counsel-ag query directory args (format prompt args)))) ((eq engine (quote rg)) (let ((args ...)) (counsel-rg query directory args (format prompt args)))) ((eq engine (quote pt)) (let ((counsel-pt-base-command ...) (default-directory directory)) (counsel-pt query))) (t (error "No search engine specified"))))))
  (let* ((query (car (cdr (plist-member --cl-rest-- (quote :query))))) (in (car (cdr (plist-member --cl-rest-- (quote :in))))) (all-files (car (cdr (plist-member --cl-rest-- (quote :all-files))))) (recursive (car (cdr (or (plist-member --cl-rest-- (quote :recursive)) (quote (nil t))))))) (progn (let ((--cl-keys-- --cl-rest--)) (while --cl-keys-- (cond ((memq (car --cl-keys--) (quote ...)) (setq --cl-keys-- (cdr ...))) ((car (cdr ...)) (setq --cl-keys-- nil)) (t (error "Keyword argument %s not one of (:query :in :all-files :recursive)" (car --cl-keys--)))))) (let* ((project-root (or (doom-project-root) default-directory)) (directory (or in project-root)) (default-directory directory) (engine (or engine (let* (... ... ... --cl-var--) (while ... ...) --cl-var--) (and (or ... ...) (quote grep)) (error "No search engine specified (is ag, rg, pt or git installed?)"))) (query (or (if query (rxt-quote-pcre query)) (if (use-region-p) (progn ...)))) (prompt (format "%s%%s %s" (symbol-name engine) (cond (... "./") (... ...) (...))))) (require (quote counsel)) (let ((ivy-more-chars-alist (if query (quote ...) ivy-more-chars-alist))) (cond ((eq engine (quote grep)) (let (... ...) (if all-files ... ...))) ((eq engine (quote ag)) (let (...) (counsel-ag query directory args ...))) ((eq engine (quote rg)) (let (...) (counsel-rg query directory args ...))) ((eq engine (quote pt)) (let (... ...) (counsel-pt query))) (t (error "No search engine specified")))))))
  +ivy-file-search(grep :query "boolNeedPostProcess" :in nil :all-files nil)
  +ivy/grep(nil "boolNeedPostProcess" nil)
  funcall(+ivy/grep nil "boolNeedPostProcess" nil)
  +ivy/project-search(nil "boolNeedPostProcess")
  (cond (t (+ivy/project-search nil (rxt-quote-pcre symbol))) (nil (+helm/project-search nil (rxt-quote-pcre symbol))) ((rgrep (regexp-quote symbol))))
  (let ((default-directory (if arg (let* ((projects (and t ...))) (if projects (completing-read "Switch to project: " projects nil t nil nil (doom-project-root)) (user-error "There are no known projects"))) default-directory))) (cond (t (+ivy/project-search nil (rxt-quote-pcre symbol))) (nil (+helm/project-search nil (rxt-quote-pcre symbol))) ((rgrep (regexp-quote symbol)))))
  +default/search-project-for-symbol-at-point(nil "boolNeedPostProcess")
  funcall-interactively(+default/search-project-for-symbol-at-point nil "boolNeedPostProcess")
  call-interactively(+default/search-project-for-symbol-at-point nil nil)
  command-execute(+default/search-project-for-symbol-at-point)

**Comment by iceiceiceJack** [comment]
if i use `SPC / p`, after i type the key word, nothing happened.

**Comment by hlissner** [comment]
As of 750d762 this should be resolved. The fallback git-grep backend was broken. I'd highly recommend installing rg (or ag), however, as these backends are much faster and better supported. In any case, let me know if you still have issues and I will reopen this thread. Thanks for bringing it to my attention.

**Comment by iceiceiceJack** [comment]
I'll try rg first, thanks for your solution
