### ISSUE TITLE
How to disable git-gutter in org-mode

### ISSUE THREAD

**Issue by forrestchang** [hlissner/doom-emacs#1482]
I have tried:

```elisp
(after! vc-gutter
  (remove-hook! org-mode #'+version-control|git-gutter-maybe)
  )
```

and

```eslip
(after! git-gutter
  (setq git-gutter:disabled-modes '(org-mode image-mode)))
```

Both not work in org-mode, I think something in Doom Emacs core finally activate the git-gutter-mode.

**Comment by hlissner** [comment]
77a7b76 makes `+version-control|git-gutter-maybe` respect `git-gutter:disabled-modes`, which should allow your second snippet to work. Let me know if that isn't the case and I will reopen this issue. Thanks for bringing it to my attention.

**Comment by forrestchang** [comment]
![image](https://user-images.githubusercontent.com/7857126/59398285-37bfcf80-8dc2-11e9-8d0b-a8a1a6855bf1.png)

@hlissner The second one doesn't work. I write it in `.doom.d/config.el`.

**Comment by hlissner** [comment]
After 0f58634 give this a try: 

```elisp
(after! git-gutter
  (setq git-gutter:disabled-modes '(org-mode image-mode)))
```

**Comment by forrestchang** [comment]
@hlissner After update doom emacs at develop branch. I can't use ivy any more. The mistake message is :

```
Symbol's value as variable is void: ivy-posframe-display-functions-alist
```
