### ISSUE TITLE
Localleader not working in org-agenda

### ISSUE THREAD

**Issue by f0086** [hlissner/doom-emacs#1483]
When I open the agenda view with ```SPACE o A a``` and hit ```SPACE m s``` (for schedduling a todo), nothing happens. Same for ```SPACE m``` ("SPACE m is undefined"). I've enabled all org-related features.

When I try to add my own localleader bindings, it also did not work:

```
(after! org
  (map! :map org-mode-map
    :localleader
    "s" #'some-fn))
```

How can I debug this further?

**Comment by hlissner** [comment]
Does this resolve the issue?

```elisp
(add-hook 'org-agenda-mode-hook #'evil-normalize-keymaps)
```

**Comment by f0086** [comment]
No, sorry.
I can reproduce my problem with a freshly installed doom-emacs:

```
rm -rf .doom.d .emacs.d
git clone https://github.com/hlissner/doom-emacs ~/.emacs.d
~/.emacs.d/bin/doom quickstart
y
y
emacs
SPACE o A a (open org-agenda)
SPACE m (hitting leader key ... but nothing happens ("SPC m is undefined"))
```

Same problem exists when I add the ```evil-normalize-keymaps``` hook in my config.el.

**Comment by hlissner** [comment]
11bfb17 should fix this issue. Please update and let me know if that isn't the case and I will reopen the issue.

**Comment by f0086** [comment]
Thank you a lot! Works perfectly!
