### ISSUE TITLE
`SPC *` escaping too much

### ISSUE THREAD

**Issue by thiagokokada** [hlissner/doom-emacs#1486]
Using `SPC *` on something with a `.` in the middle causes it to escape too much. For example:

![2019-06-12_11-59-19-screenshot](https://user-images.githubusercontent.com/844343/59362279-92492500-8d09-11e9-919c-467bf7cbbd18.png)

Note that it is trying to escape `.` with `\\\.` instead of only `\.` that gives the correct result in this case:

![2019-06-12_12-00-31-screenshot](https://user-images.githubusercontent.com/844343/59362370-b573d480-8d09-11e9-85b3-10058848ddfc.png)

**Comment by thiagokokada** [comment]
Another case that it escapes wrong:
![2019-06-12_14-04-43-screenshot](https://user-images.githubusercontent.com/844343/59371320-148e1500-8d1b-11e9-8368-89a85259ce0a.png)

In this case it should escape `!` with `\!`, or it will be ignored by the regular expression.

**Comment by hlissner** [comment]
4ef345f should fix this. Let me know if that isn't the case and I'll reopen this. Thanks for bringing it to my attention.
