### ISSUE TITLE
format-all doesn't find project root for Elixir files

### ISSUE THREAD

**Issue by Strayer** [hlissner/doom-emacs#1489]
format-all now includes logic to find the project root of Elixir files to run the formatter from there instead of the buffers directory. This is required because `mix format` only applies its config (`.formatter.exs`) if it is in the current working directory, this file is located in the project root. format-all tries to find the project root by going upwards until it finds a `mix.exs`, which is always in the root directory of Elixir projects.

It seems that dooms modifications of format-all somehow break this logic, since format-all always thinks the buffers directory is the project root, see https://github.com/lassik/emacs-format-all-the-code/issues/36#issuecomment-499064762 for more details.

Example with format-all-debug enabled:

```
*Messages*
Format-All: Running: /Users/work/.asdf/shims/mix format -
Format-All: Directory: /Users/work/dev/redacted/redacted-backend/lib/redacted_web/
Formatted (mix-format)
```

Project layout:
```
~/dev/redacted/redacted-backend/lib/redacted_web
❯ file mix.exs
mix.exs: cannot open `mix.exs' (No such file or directory)

~/dev/redacted/redacted-backend/lib/redacted_web
❯ file ../mix.exs
../mix.exs: cannot open `../mix.exs' (No such file or directory)

~/dev/redacted/redacted-backend/lib/redacted_web
❯ file ../../mix.exs
../../mix.exs: Ruby script text, ASCII text # (no idea why file thinks this is a ruby script)
```

The relevant commit in format-all that added this logic is this one: https://github.com/lassik/emacs-format-all-the-code/commit/4f458bd8f67ec6032e7e25e9c2be2dea0d978d78

**Comment by hlissner** [comment]
13f5a76 _should_ resolve this issue. Please update and let me know if that isn't the case and I will reopen this issue. Thanks for letting me know (and for the detailed bug report -- it was a huge help)!
