### ISSUE TITLE
Debugging emacs problems

### ISSUE THREAD

**Issue by haji-ali** [hlissner/doom-emacs#1490]
I have been noticing that while editing my C++ files, the speed degrades after a few days of usage (I rarely restart my emacs). I suspect that there's some packages that are being loaded which is slowing down my emacs but it is difficult to debug this since I don't know when these packages get loaded.

Is there a way to force doom to load all packages at startup. I know this will slow the startup time significantly but I would like to be able to troubleshoot these speed problems.

**Comment by hlissner** [comment]
A few things you can try:

```elisp
(dolist (package (doom-package-list))
  (with-demoted-errors (format "ERROR (%s) %%s" (car package))
    (require (car package) nil t)))
```

Or `SPC h T` (`doom/toggle-profiler`)

Another possibility is garbage collection. Try tweaking `gc-cons-threshold` (Doom sets it to 16mb). Perhaps try `(add-hook 'focus-in-hook #'garbage-collect)`, or running `garbage-collect` on a timer.

**Comment by haji-ali** [comment]
Mm.. Loading all packages did not slow my emacs. I am not sure what the reason is. I had to restart emacs but I will investigate your other suggestions once the problem comes up again.

**Comment by hlissner** [comment]
Have you had this issue since?

**Comment by haji-ali** [comment]
Sorry for not updating this earlier. I haven't had this recently. I suspect it got fixed someway or another. I will update if I experience it again.
