### ISSUE TITLE
Buggy shortcuts

### ISSUE THREAD

**Issue by thiagokokada** [hlissner/doom-emacs#1491]
`M-t` (`workspace/new`) doesn't work in Clojure/Elisp major modes (probably in more Lisp major modes too). Opens `transpose-sexps` instead:
 https://github.com/hlissner/doom-emacs/blob/b1ecd68381647c3ee5921b52850497d40ad00d5c/modules/config/default/%2Bevil-bindings.el#L325

`M-f` calls `forward-word`, instead of `swiper` like in the documentation:
https://github.com/hlissner/doom-emacs/blob/a1b47648aabe99e026adc873703c6632ec5c0f2c/modules/completion/ivy/README.org#L115

**Comment by hlissner** [comment]
I cannot reproduce this is either clojure-mode or emacs-lisp-mode. Could you supply your `M-x doom/info`?

The completion/ivy readme is outdated, however. I will correct it soon.

**Comment by thiagokokada** [comment]
- OS: gnu/linux (x86_64-pc-linux-gnu)
- Emacs: 26.1 (mai 21, 2019)
- Doom: 2.0.9 (HEAD -> develop, _upgrade/develop 4ef345fe 2019-06-12 20:17:47 +0200)
- Graphic display: t (daemon: nil)
- System features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LIBSYSTEMD
- Details:
  ```elisp
  env bootstrapper: nil
  elc count: 0
  uname -a:  Linux 4.19.48 #1-NixOS SMP Tue Jun 4 06:02:35 UTC 2019 x86_64
  modules:   (:completion company (ivy +fuzzy +prescient) :ui doom fill-column hl-todo modeline nav-flash neotree ophints (popup +all +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor evil file-templates fold (format +onsave) multiple-cursors rotate-text snippets :emacs dired electric vc :term eshell term :tools ansible docker eval flycheck (lookup +docsets) lsp magit terraform :lang cc clojure data elixir emacs-lisp hy javascript markdown nix (org +attach +babel +capture +export +habit +present +protocol) python ruby (sh +zsh) web :config default)
  packages:  (flymd lispyville sort-words uuidgen xterm-color)
  exec-path: (~/.opam/default/bin ~/dev/nu/ios-cli ~/dev/nu/nucli ~/dev/nu/nudev ~/.npm-packages/bin ~/.emacs.d/bin ~/.local/bin /nix/store/simzf4z8qsy90yx31vvxng1br64fg6nv-kitty-0.13.3/bin /nix/store/12mp3wv5va3fgamqdaf1ipng95k67mgs-imagemagick-6.9.9-34/bin /nix/store/5yiablfx93lia1w2b3cdx568jb8vixmc-xsel-unstable-2018-01-10/bin ~/bin /run/wrappers/bin ~/.nix-profile/bin /nix/var/nix/profiles/default/bin /run/current-system/sw/bin /etc/profiles/per-user/thiagoko/bin /nix/store/saw6s66lqf2kfmw7iimn8mg9h13a2qzb-aspcud-1.9.4/bin /nix/store/anarykvhq3f7n5w3jnbc4kaqczsfpk91-unzip-6.0/bin /nix/store/z7cj8bw37vby6gywwc1g4frz293f93zb-curl-7.64.0-bin/bin /nix/store/lwqq7jqp75vzgkrs371zjv2iacyp3dsl-bubblewrap-0.3.1/bin /nix/store/i13djlc0xgamglzdqz1cyxrcz87r93zl-getconf-1003.1-2008/bin /nix/store/jk935pwdp9m5cs8bdi29p3ivbvvbnf00-emacs-26.1/libexec/emacs/26.1/x86_64-pc-linux-gnu)
  ```

Just found that `M-t` is from `lispyville`, this is why it is happening only for me. Sorry.

**Comment by hlissner** [comment]
No worries. I see you've installed lispyville yourself. Is `M-t` overwritten if you use the `:editor lispy` module? (It uses lispyville if evil is installed)

**Comment by thiagokokada** [comment]
Let me try, however I use `lispyville` directly exactly because I can avoid the parinfer-like shortcuts.

**Comment by thiagokokada** [comment]
@hlissner With `lispy` activated I have the exactly same problem.

**Comment by thiagokokada** [comment]
The fault seems to be `lispyville` Additional Key theme: https://github.com/noctuid/lispyville#additional-key-theme

**Comment by hlissner** [comment]
As of 0643630 I've moved `M-{t,T}` to `C-{t,T}` for windows/linux users and `s-{t,T}` (cmd + {t,T}), which should indirectly resolve this issue (to be more in line with tab shortcuts in browsers). Thanks for bringing it to my attention!
