### ISSUE TITLE
doom:term-popup breaks workspaces

### ISSUE THREAD

**Issue by intpl** [hlissner/doom-emacs#1492]
When switching workspaces when term-popup is visible, it breaks target workspace

steps to reproduce:
1. open any file (workspace [1])
2. switch to other project / create workspace (e.g. using `SPC p p`) (workspace [2])
3. open term-popup using `SPC o t` in workspace [2]
4. switch to workspace [1] using Alt-1 (`+workspace/switch-to-0`)

results with:

 `Attempt to delete main window of frame #<frame *doom:term-popup*> - Doom Emacs` 
workspace [1] overwrites with windows and buffers from workspace [2].

**Comment by hlissner** [comment]
7ce4a25 and 80958c0 should resolve this issue. Let me know if that isn't the case and I will reopen this. Thanks for the detailed bug report and for bringing it to my attention.

**Comment by intpl** [comment]
it works like a charm now. thanks!

**Comment by intpl** [comment]
wait. it does not, now you can't close (toggle) term:popup with `SPC o t`

**Comment by hlissner** [comment]
Ah, my bad. 3e4f0a9 should fix the closing issue. Please update and let me know if that worked.

**Comment by intpl** [comment]
now i noticed two things:
1. closing term using `SPC o t` is very slow (closing is fast, but then it freezes for 3 seconds)
2.  i cannot close term at first try after being in another workspace:
  steps to reproduce:
  a). workspace [1] -> `SPC o t`
  b) `SPC p p` -> another workspace
  c) back to [1] using Alt-1
  d) try to close using `SPC o t` (works the second time)

**Comment by hlissner** [comment]
`SPC o t` will select the term popup if it isn't focused. It will only close it if it is focused. Is that not the case?

As for the slowness, that's odd. Perhaps it's taking a while to kill the term process? I'm not sure why it would take so long, however. What OS are you on?

**Comment by intpl** [comment]
1. `SPC o t` does not work the first time after workspace change even when term is focused. see 'steps to reproduce' in my previous comment. i leave term focused when workspace switching happens.

2. i found yet another weird behavior in term:popup. it's when you have `SPC o t` opened in two workspaces and then close one term:popup window. the one in other workspace becomes zombie, because it was the same shell process. maybe you could restrict `SPC o t` to a workspace? that would be really great.

3. way to reproduce a slow term:popup closing:
 - open Emacs
 - press `SPC o t` to open term, then ESC to trigger normal mode and `SPC o t` to close the term
 - Emacs is frozen for couple of seconds (try to move using j/k right away) and error shows: "error in process filter: Selected deleted buffer"

My OS is Ubuntu 19.04, kernel 5.0.0-16-generic without any mods (vanilla Ubuntu package), fish shell (closing shell in any terminal emulator is very fast), here is `doom/info`:


- OS: gnu/linux (x86_64-pc-linux-gnu)
- Emacs: 27.0.50 (cze 12, 2019)
- Doom: 2.0.9 (HEAD -> develop, origin/develop, origin/HEAD c705ceeb 2019-06-15 00:38:13 +0200)
- Graphic display: t (daemon: nil)
- System features: XPM JPEG TIFF GIF PNG SOUND DBUS GSETTINGS GLIB NOTIFY INOTIFY LIBSELINUX GNUTLS FREETYPE HARFBUZZ XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS PDUMPER GMP
- Details:
  ```elisp
  env bootstrapper: nil
  elc count: 0
  uname -a:  Linux 5.0.0-16-generic #17-Ubuntu SMP Wed May 15 10:52:21 UTC 2019 x86_64
  modules:   (:completion company (ivy +fuzzy) :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) tabbar treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor evil file-templates fold multiple-cursors rotate-text snippets :emacs dired electric vc :term term :tools direnv editorconfig eval flycheck flyspell (lookup +docsets) magit pdf rgb tmux upload :lang common-lisp crystal data erlang elixir emacs-lisp go (haskell +intero) javascript markdown (org +attach +babel +capture +export +habit +present +protocol) php python rest ruby rust (sh +fish) web :config default)
  packages:  (rvm robe yari goto-gem projectile-rails ruby-tools company-tabnine auto-complete zoom graphql-mode graphql company-flx evil-anzu (evil-snipe :disable t) (solaire-mode :disable t) (forge :disable t) (evil-escape :disable t))
  exec-path: (~/.rvm/rubies/ruby-2.5.3/bin/ ~/.rvm/gems/ruby-2.5.3/bin ~/.rvm/gems/ruby-2.5.3@global/bin ~/.rvm/rubies/ruby-2.5.3/bin /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /usr/games /usr/local/games /snap/bin ~/.rvm/bin /usr/local/libexec/emacs/27.0.50/x86_64-pc-linux-gnu)
  ```

**Comment by intpl** [comment]
"cze" means June

**Comment by hlissner** [comment]
43615c4 makes the dedicated term popups workspace-local, and should (indirectly) fix your freezing issue (`SPC o t` no longer kills the process when closing the popup -- the terminal will persist until the workspace is killed or process manually exited). Please update and let me know if it works for you.

**Comment by intpl** [comment]
perfect. works like a charm. thanks! :)

**Comment by hlissner** [comment]
And done. 2835314 should fix the blank term problem.

**Comment by intpl** [comment]
you, sir, are a life saver. thanks!
