### ISSUE TITLE
's' in org mode does not act as it does elsewhere

### ISSUE THREAD

**Issue by scowan1995** [hlissner/doom-emacs#1493]
Normally in vim pressing s deletes the character that the cursor is centred on and enters insert mode. This works is a normal buffer but not in an org document. It seems to do some sort of search with "2>" appearing at the bottom. 

  I can't find a list of packages doom uses but I am assuming that it uses [this package for org mode evil keybindings](https://github.com/Somelauw/evil-org-mode). The linked package doesn't mention changing what s does.

**Comment by hlissner** [comment]
This is a duplicate of #1307, please see [my explanation there](https://github.com/hlissner/doom-emacs/issues/1307#issuecomment-480211208).
