### ISSUE TITLE
Can't launch ipython/jupyter repl with conda environment

### ISSUE THREAD

**Issue by pmercatoris** [hlissner/doom-emacs#1494]
I am not able to launch ipython or jupyter repl which only exist in my conda environment (I am able to launch the python repl, but that is the root interpreter, not the env). I have setup conda-anaconda-home in config.el and have activated through condo-env-activate. But once trying to launch repl it says that the conda-env-location is not set. Any help? I'm completely new to doom wbarely any knowledge of elisp...

Thank you!

<img width="1247" alt="image" src="https://user-images.githubusercontent.com/8655813/59538938-ad7b8680-8efb-11e9-876c-b9d3d37002ca.png">

**Comment by hlissner** [comment]
c705cee should fix this issue. Please update and let me know if this is the case.

**Comment by pmercatoris** [comment]
Awesome! That fixed it! Thanks again for the great work!
