### ISSUE TITLE
dante and .dir-locals.el do not work correctly

### ISSUE THREAD

**Issue by Ptival** [hlissner/doom-emacs#1495]
Because of:
https://github.com/jyp/dante/issues/58

It seems that `.dir-locals.el` variables are reset, supposedly because the `flycheck-mode` hook and the `dante-mode` hook are called in the wrong order?

Does doom support a way of specifying the order of those modes? It seems ugly/hacky, but might be necessary... :(

**Comment by hlissner** [comment]
Are you sure this is an issue in Doom?

1. Doom uses `global-flycheck-mode`, which assures flycheck-mode is enabled on `after-change-major-mode-hook` (runs after a mode's hooks, e.g. `haskell-mode-hook`).
2. Doom has `dante-mode` on `haskell-mode-local-vars-hook`, a special Doom-specific hook that runs _after_ `after-change-major-mode-hook` (unless you have `enable-local-variables` disabled, in which case it runs at the end of `after-change-major-mode-hook`).

To summarize, the hooks and modes run in this order: `haskell-mode-hook` -> `after-change-major-mode-hook` (enables `flycheck-mode`) -> `haskell-mode-local-vars-hook` (enables `dante-mode`).

So flycheck-mode should be enabled _before_ dante-mode, which, if I understood hyp/dante#58 correctly is what we want to avoid this problem.

You can quickly test if this is true with:

```elisp
(add-hook! 'flycheck-mode-hook
  (message "Enabled flycheck-mode in %s" (current-buffer)))

(add-hook! 'dante-mode-hook
  (message "Enabled dante-mode in %s" (current-buffer)))
```

Then open a haskell buffer, check your \*Messages\* (`SPC h e` or `M-x view-echo-area-messages`) and inspect the order of those messages.

**Comment by Ptival** [comment]
No it's actually working correctly, I guess I did not quite get the correct syntax in my `.dir-locals.el` the first time around! Sorry for the disturbance.

**Comment by Ptival** [comment]
I got confused because, even though the local variables seem set correctly for dante, when I do `M-: <variable>` or `M-x apropos <variable>` it shows it still as `nil`. But the rest of the behavior is fine...
