### ISSUE TITLE
format module will trigger confirmation before closing the temp buffer

### ISSUE THREAD

**Issue by zhuhaow** [hlissner/doom-emacs#1498]
I'm on be3f6fb.

I enabled format module, and if I format the buffer, I'll see a confirmation asking 
`Buffer  *temp*-54891 modified; kill anyway? (y or n) y`.

I understand that the format works by piping stuff to a temp buffer, run it with the formatter, in this case, rustfmt, and then kill the temp buffer.

I checked the recent change in format module and I doubt that's because of something with the format-all-mode? Maybe that changed the behavior of the temp buffer?

**Comment by zhuhaow** [comment]
Got a feeling that is a bug with format-all

**Comment by hlissner** [comment]
This is a regression caused by https://github.com/hlissner/doom-emacs/commit/13f5a7627858ba784b57864f137f8e086d8e83f3. A fix will be up shortly.

**Comment by hlissner** [comment]
9bba39b should resolve this issue. Let me know if that isn't the case and I will reopen this thread. Thanks for bringing it to my attention!
