### ISSUE TITLE
No `doom reload` referenced by `doom env`

### ISSUE THREAD

**Issue by mikeonly** [hlissner/doom-emacs#1499]
After running `doom env enable`, the [output references](https://github.com/hlissner/doom-emacs/blob/be3f6fb38fff00dc72ad64d0119f863b9b4f8e36/core/cli/env.el#L12) the command `doom reload` which “will now refresh your envvar file”. However, there is no `doom reload` command in the bin. Maybe you meant something else?

There is `doom/reload` and `doom/reload-env` available in the Emacs, but I am not sure which one actually updates the `envvar` file. Hope this report helps.

**Comment by hlissner** [comment]
Ah, my mistake. It should be `doom refresh`. I'll correct this shortly.

**Comment by mikeonly** [comment]
Thanks! And slightly off-topic, thank you for maintaining this awesome project.

**Comment by hlissner** [comment]
With 4773969 this issue is resolved. Thanks for bringing it to my attention and for the kind words! I'm glad Doom can be useful to you. What use is madness if it can't be shared?
