### ISSUE TITLE
ivy-posframe font isn't adjusted after changing global font size

### ISSUE THREAD

**Issue by andresilva** [hlissner/doom-emacs#1500]
Reproduce:
* Configure ivy to use `+childframe`;
* Increase font size globally with `doom/increase-font-size`;
* Open an ivy menu and the font size should not match the rest of the UI.

**Comment by andresilva** [comment]
`ivy-posframe` seems to have a config variable to set the font size used. By default it's `nil` and it should fallback to the frame's font. The code to adjust font size in doom is a bit hairy (I didn't know about any of this xlfd stuff) so I couldn't find a fix for this in a reasonably short time (and given my lack of knowledge).

**Comment by hlissner** [comment]
d27c148 should fix this issue. Please update and let me know if that isn't the case and I will reopen this issue. Thanks for bringing it to my attention!

**Comment by andresilva** [comment]
Wow, from issue report to fix in less than an hour. Thanks! :heart:

**Comment by andresilva** [comment]
This seems to be happening again. `doom/decrease-font-size` doesn't affect child frames.

**Comment by hlissner** [comment]
As of 2dc50f4 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
