### ISSUE TITLE
doom-doctor fails to check BSD/GNU tar

### ISSUE THREAD

**Issue by nwolfe** [hlissner/doom-emacs#1501]
The latest change to doom-doctor (https://github.com/hlissner/doom-emacs/commit/798e10c4f2bfaee75c889935e1b7e49152628d8a) seems to have broken the BSD/GNU tar check. 

Or at least, it changed its behavior; maybe it was broken before and now it's working correctly?

I have had gnu-tar installed via brew for a while and doom-doctor has not complained, until today. Now it thinks I don't have gnu-tar available.

When I revert the changes around `sh` and `format` in that doom-doctor commit above, the warning goes away.

I noticed that it seems no other calls to `sh` in doom-doctor use that secondary `&rest` argument; the BSD/GNU tar check is the only place that appears to use that form.

**Comment by hlissner** [comment]
My bad, a brain fart snuck into 798e10c. With 710a18d this should be resolved. Let me know if that isn't the case and I will reopen this issue. Thanks for bringing it to my attention!

**Comment by nwolfe** [comment]
🎉That worked! Thanks for the quick fix ❤️

And thank you for Doom Emacs!
