### ISSUE TITLE
Modify (or disable) self-closing tags in org-mode

### ISSUE THREAD

**Issue by gragusa** [hlissner/doom-emacs#1502]
I am trying to change the behavior of matching tags in org-mode. In addressing #576, matching tag are much better, but I still have problems when typying mathematics. For instance, inserting _  after X^{2} results in X_{i}__. Same issue with =. I tried to add this to my config.el

```elisp
(after! smartparens
  (defun sp-org-point-after-curlybracket-p (id action _context)
    "Return t if point follows a backslash, nil otherwise.
This predicate is only tested on \"insert\" action.
ID, ACTION, CONTEXT."
    (when (eq action 'insert)
      (let ((trigger (sp-get-pair id :trigger)))
        (looking-back (concat "\\}" (regexp-quote (if trigger trigger id))) nil))))

  (sp-with-modes 'org-mode
    (sp-local-pair "_" "_" :unless '(:add sp-point-before-word-p +org-sp-point-at-bol-p sp-org-point-after-curlybracket-p))
    (sp-local-pair "=" "=" :unless '(:add sp-point-before-word-p +org-sp-point-at-bol-p sp-org-point-after-curlybracket-p))))
```

However, the behavior of _ and = is unchanged (I removed `(!after smartparens` to no avail). I also tried to completely disable them with 

```elisp
  (sp-with-modes 'org-mode
    (sp-local-pair "_" "_" :actions nil)
    (sp-local-pair "=" "=" :actions nil))
```

They are still active. If I evaluate the expressions while a `org-mode` buffer is open, then I get the expected behavior.

**Comment by hlissner** [comment]
Could you try wrapping that in `(after! (:and org smartparens) ...)` instead?

**Comment by gragusa** [comment]
Yes, wrapping everything in `(after! (:and org smartparens) ...)` did it. 

What I ended up adding is the following:

```elisp
(after! (:and org smartparens)

(sp-with-modes 'org-mode
    (sp-local-pair "_" "_" :unless '(:add sp-point-before-word-p sp-in-math-p sp-point-after-word-p +org-sp-point-at-bol-p))
    (sp-local-pair "=" "=" :unless '(:add sp-point-before-word-p sp-in-math-p sp-point-after-word-p +org-sp-point-at-bol-p))))
```

**Comment by hlissner** [comment]
Understood. I'll merge your suggestion into lang/org in a couple days; I'm working on a big refactor of the module.

**Comment by hlissner** [comment]
And done. As of 11bfb17, I've merged this into lang/org proper. Thanks for bringing it to my attention!
