### ISSUE TITLE
org mode :RESET_CHECK_BOXES: property bug

### ISSUE THREAD

**Issue by forrestchang** [hlissner/doom-emacs#1503]
Here is the situation, I have a repeat todo item with some checkboxes under it, I want to reset the checkbox when this todo item marked as DONE. I use `RESET_CHECK_BOXES` property to do that and it worked. However, this behaviour will remove other headlines' cookie (todo count in `[/]`). I don't know if this is the bug of Doom Emacs or org-mode.

![image](https://user-images.githubusercontent.com/7857126/59772088-b397ab80-92dd-11e9-903e-6d22cb3a7efc.png)

Then I set the repeat task to DONE:

![image](https://user-images.githubusercontent.com/7857126/59772187-e93c9480-92dd-11e9-9b16-1d7988c0b753.png)

You can see the FTW subtree's cookie is be reseted!

**Comment by hlissner** [comment]
Do you have `org-checklist` in `org-modules`? e.g.

```elisp
(add-to-list 'org-modules 'org-checklist)
```

**Comment by forrestchang** [comment]
@hissner Yes, and it doesn't work.
