### ISSUE TITLE
Can't `C-w o` (doom/window-enlargen) a minibuffer in mixed horizontal/vertical splits

### ISSUE THREAD

**Issue by thiagokokada** [hlissner/doom-emacs#1509]
To reproduce it:
- Open Emacs
- `C-w v` and `C-w s` to open 3 windows
- Open a minibuffer (for example,  `SPC o t` to open a term)

This is how it should look:
![2019-06-24_13-41-26-screenshot](https://user-images.githubusercontent.com/844343/60036529-cb788200-9685-11e9-92be-086a368264c6.png)

Now try to expand the minibuffer using `C-w o`. You get the following error:
```
Failed to apply resizing #<window 10 on *doom:term-popup:main*>
```

**Comment by hlissner** [comment]
As of 26da625 this should be resolved. Let me know if that isn't the case and I will reopen this issue. Thanks for bringing it to my attention!

**Comment by thiagokokada** [comment]
@hlissner While this works now in term, it stopped worked in a CIDER minibuffer.

When I used a `C-w o` in a CIDER minibuffer before it used to enlargen, now it simply doesn't work (even with only 1 window opened). There is also no errors at all in tis case.

**Comment by hlissner** [comment]
6317fa0 shoudl fix the issue with CIDER (including other popups and repls). Let me know if that isn't the case and I will reopen the issue.
