### ISSUE TITLE
]e and [e don't work unless you enable flycheck

### ISSUE THREAD

**Issue by ocharles** [hlissner/doom-emacs#1511]
As mentioned on Discord - `]e` and `[e` don't work unless you've enabled flycheck, but it should work without that (as `SPC p c` for example performs compilation).

**Comment by rgrinberg** [comment]
Also, is it possible for the compilation errors not to be overwritten by flycheck errors?

**Comment by hlissner** [comment]
As of 0290b68, the original issue should be fixed so I'll consider this resolved.

@rgrinberg I'll look into it.
