### ISSUE TITLE
emacs won't open as doom-emacs after installation

### ISSUE THREAD

**Issue by jogacex** [hlissner/doom-emacs#1512]
Hello everyone. I recently learned about the existence of doom-emacs and I am having issues to run it. I followed the steps on the git site and everything seemed to have installed properly. I have my .emacs.d/ and .doom.d/ folders created after a fresh emacs installs. However, when I run emacs, it opens without doom. It runs like it was never installed. 

Please, help me! 
Thanks in advance. Let me know what you might need from me.

**Comment by hlissner** [comment]
Welcome aboard! To get to the bottom of this, I'll need to know exactly what you've done to install Doom Emacs. The instructions merely two commands, entered into your command line. They are:

```sh
git clone https://github.com/hlissner/doom-emacs ~/.emacs.d
~/.emacs.d/bin/doom quickstart
```

Which should be all you need to get up and running. If you did these, does a `~/.emacs` file exist on your system? Emacs will ignore all other configuration if this file exists. If it does, delete it, run `doom refresh` and try opening Emacs once again.

**Comment by jogacex** [comment]
Wow, you are the man! 

I found the .emacs file in my directory so I deleted it. I now have Doom running on my computer. 

Thank you very much! :)

**Comment by hlissner** [comment]
Happy to help! I'm glad we could figure it out.

**Comment by EvgeniGenchev** [comment]
Hello I have the same problem but I don't have the ~/.emacs folder. 
I did install doom emacs like with the provided commands. I have my .doom.d/ and .emacs.d/ contains your README so I know I installed it successfully. However, I still open doom emacs.
