### ISSUE TITLE
Regarding org-mode and doom-emacs (shortcuts) 

### ISSUE THREAD

**Issue by jogacex** [hlissner/doom-emacs#1513]
Good evening everyone, 

I am not sure if this is off-topic or not. If so, please point me in the right direction. 

I used emacs' org-mode a lot for school papers. I did some research and found that doom-emacs is better for writing longer papers (thesis, business proposals, etc.). I was able to launch and I am trying to become familiar with the shortcuts but I am a little confused. Is there a newbie guide I can follow specifically for writing papers in LaTeX? Is there something you guys recommend for me to do to become better with this program? 

Thanks in advance again.

**Comment by hlissner** [comment]
Hi there! I'm afraid there isn't much in the way of workflow documentation for Doom (yet), or in general, really. I'm working on it, but it's an uphill struggle against issue triage, general maintenance, traveling and other work. 

That said, you will find Doom users [on our discord](https://discord.gg/bcZ6P3y) who use Doom this way that may be able to help. I, myself, use org-mode to write papers and fiction, but my workflows are quite unsophisticated -- I'm still new to this side of Emacs. In any case, the Discord is likely to be your best resource.

**Comment by jogacex** [comment]
I see. Thank you for the reply. 

I noticed that some of the shortcuts on org-mode are different from the default ones I am used to. For example, to create a new bullet-point I used to use Alt+Enter. Haven't figured out how to do it in doom ^_^. 

Is there a way to find the shortcuts in doom?

Thanks in advance.

**Comment by hlissner** [comment]
`C-RET` (ctrl+return) will do that for you. 

Doom tries to standardize the behavior of C-RET and C-S-RET (ctrl + shift + return) to "add new item below/above" (cmd+RET and cmd+shift+RET on macos), respectively, and M-RET and M-S-RET to "add new empty line below/above".

**Comment by AlexLewandowski** [comment]
Just to chime-in a bit, alt-enter should work in org mode to insert a bullet at the same level. For latex,  keybindings are the AUCTeX default but easy enough to change with map!

**Comment by jogacex** [comment]
Thank you for the prompt replies. I'm kind of new to this World and I'm surprised at how active you guys are! :)

I will check on those really soon.

**Comment by hlissner** [comment]
Happy to help! I'll consider the original issue resolved and close this, but feel free to follow up here (or on Discord).
