### ISSUE TITLE
[ui] sidebar icon size not consistent, low resolution

### ISSUE THREAD

**Issue by AlexXiong97** [hlissner/doom-emacs#1514]
1. Some icons for different files in the sidebar are not the same, thus can appear to be messy sometimes. (e.g. `Cargo.lock` below)
2. Also, those images seem to have very low resolution. (e.g. `.rs` file below, also icons like docker file icon, etc are quite blurry)

Example:
<img width="233" alt="Screenshot 2019-06-27 at 4 50 52 PM" src="https://user-images.githubusercontent.com/20514086/60251766-c0c72280-98fb-11e9-9f58-7e2d3b6134a2.png">

**Comment by AlexXiong97** [comment]
@hlissner May I ask if there's something I missed or should do regarding `treemacs` config or `all-the-icons` config?

I'm sure I installed `all-the-icons-font` exactly like the "getting started" guide and icons shown normally on the home/Doom page.

Thanks for your attention.

**Comment by hlissner** [comment]
This is a known issue with the doom-themes package. An [issue exists there for it](https://github.com/hlissner/emacs-doom-themes/issues/288).

There were changes upstream, in treemacs, which broke the icon customizations in doom-themes. I haven't gotten around to addressing it yet.

I'm currently traveling and won't be able to address the issue until after the weekend, at the latest.

**Comment by AlexXiong97** [comment]
@hlissner Thanks for the info. Looking forward to the update.

**Comment by kreisys** [comment]
> @hlissner Thanks for the info. Looking forward to the update.

You can try this in the meanwhile: https://github.com/hlissner/emacs-doom-themes/issues/288#issuecomment-506739326

**Comment by hlissner** [comment]
I've pushed a fix upstream, so this issue should be resolved once MELPA indexes the change and you update with `doom update`. Let me know if that issue persists afterwards and I will reopen this issue. Thanks for bringing it to my attention!
