### ISSUE TITLE
+smartparens breaks scala-mode scaladoc indentation

### ISSUE THREAD

**Issue by jsravn** [hlissner/doom-emacs#1515]
First of all, thanks for doom-emacs - I'm really enjoying it as a long time emacs user.

I'm running into a small minor snag with scala-mode.

When `+smartparens` is in my `~/.doom.d/init.el`, scaladoc indentation doesn't seem to work properly. E.g. when I try to do a multiline doc, it does this:

```scala
/** MyClass
/** <broken>
class MyClass {
```

When it should do
```scala
/** MyClass
  * next line
  */
class MyClass {
```

This seems to be caused by https://github.com/hlissner/doom-emacs/blob/81cf6080bf800e74be5b218b71e1cdf90c222c04/modules/config/default/config.el#L141

Which causes the indent to duplicate the prior `/**` incorrectly.

For now I've disabled it completely by adding to my `.doom.d/config.el`:
```elisp
;; Disable smartparens comment continuation behaviour
(after! smartparens
  (advice-remove #'newline-and-indent #'+default*newline-indent-and-continue-comments))
```

I wonder if there is a better way though? Is there a benefit to this has over just letting the major mode do its work? It doesn't seem related to smartparens either. Thanks!

**Comment by hlissner** [comment]
`+default*newline-indent-and-continue-comments` marries `newline-and-indent` and `comment-indent-and-newline`, which leaves it up to the major mode to best decide how to continue and indent comments. It consults `comment-line-break-function` under the assumption that the major mode has set one and, if it has, it does it's job correctly.

For the majority of C-style languages (that are derived from the cc-mode family) this is the case, but scala-mode does not define a `comment-line-break-function`, so it falls back to the generic `comment-indent-new-line` function, which produces the undesirable behavior you're seeing.

Therefore, we either need a better `comment-line-break-function` or make do with standard newline-and-indent behavior, which produces this:

```scala
/**
  next line
 */
```

Which we want

```scala
/**
 * next line
 */
```

So, here's my quick stab at a solution. Please try inserting the following into your `~/.doom.d/config.el` and let me know if it resolves your issue:

```elisp
(defun +scala-comment-indent-new-line (&rest _)
  "TODO"
  (let* ((state (syntax-ppss))
         (comment-start-pos (nth 8 state))
         prev-line)
    (save-match-data
      (cond ((and (integerp (nth 4 state))
                  ;; Ensure that we're inside a scaladoc comment
                  (string-match-p "^/\\*\\*?[^\\*]?"
                                  (buffer-substring-no-properties
                                   comment-start-pos
                                   (min (+ comment-start-pos 4)
                                        (point-max))))
                  (progn
                    (setq prev-line (buffer-substring-no-properties
                                     (line-beginning-position 0)
                                     (line-end-position 0)))
                    (or (string-match "^\\s-*\\*" prev-line)
                        (string-match "\\s-*/*" prev-line))))
             (newline)
             (indent-according-to-mode)
             (insert (make-string (max 0 (- (1- (match-end 0))
                                            (match-beginning 0)))
                                  ? )
                     "*")
             (scala-indent:indent-on-scaladoc-asterisk))
            ((sp-point-in-comment)
             (call-interactively #'comment-indent-new-line))))))

(setq-hook! 'scala-mode-hook comment-line-break-function #'+scala-comment-indent-new-line)
```

I'm not sure if this is something that should be merged upstream. Probably so, but it'd have to be generalized. This solution depends too much on smartparens.

**Comment by jsravn** [comment]
Yes, that works great! Although I had to change it to `(setq scala-indent:use-javadoc-style nil)` to get scaladoc style.

I also tried something like:
```elisp
(setq-hook! 'scala-mode-hook comment-line-break-function #'(lambda (&rest _)
                                                              (progn
                                                                (newline)
                                                                (scala-indent:insert-asterisk-on-multiline-comment))))
```
But it doesn't handle `//` then. I'm guessing this is close to how we could generalize it in scala-mode itself.

**Comment by hlissner** [comment]
But with `scala-indent:use-javadoc-style` set to nil, it indents like so:

```scala
/**
  *
  */
```

Rather than

```scala
/**
 *
 */
```

Is that what you wanted?

**Comment by hlissner** [comment]
I've merged the above suggestion (plus a few tweaks) in 08e125d. Let me know if it doesn't resolve your issue and I will reopen this. In any case, thanks for helping me figure it out and for bringing it to my attention!
