### ISSUE TITLE
lang/lua: set-project-type! throws an error

### ISSUE THREAD

**Issue by filalex77** [hlissner/doom-emacs#1516]
Introduced by 22cc519ac194e6ab3aa5a2416398d86da3b370c9 (bisected).

**How to reproduce:** start Emacs, or do `make clean compile-core`.

**What happened**:

<details>
<pre>
Debugger entered--Lisp error: (error "Keyword argument (map! :localleader :map +lua-love-mode-map b (function +lua/run-love-game)) not one of (:modes :files :when :match :add-hooks :on-load :on-enter :on-exit)")
  signal(error ("Keyword argument (map! :localleader :map +lua-love-mode-map b (function +lua/run-love-game)) not one of (:modes :files :when :match :add-hooks :on-load :on-enter :on-exit)"))
  error("Keyword argument %s not one of (:modes :files :when :match :add-hooks :on-load :on-enter :on-exit)" (map! :localleader :map +lua-love-mode-map "b" (function +lua/run-love-game)))
  (cond ((memq (car --cl-keys--) (quote (:modes :files :when :match :add-hooks :on-load :on-enter :on-exit :allow-other-keys))) (setq --cl-keys-- (cdr (cdr --cl-keys--)))) ((car (cdr (memq (quote :allow-other-keys) --cl-rest--))) (setq --cl-keys-- nil)) (t (error "Keyword argument %s not one of (:modes :files :when :match :add-hooks :on-load :on-enter :on-exit)" (car --cl-keys--))))
  (while --cl-keys-- (cond ((memq (car --cl-keys--) (quote (:modes :files :when :match :add-hooks :on-load :on-enter :on-exit :allow-other-keys))) (setq --cl-keys-- (cdr (cdr --cl-keys--)))) ((car (cdr (memq (quote :allow-other-keys) --cl-rest--))) (setq --cl-keys-- nil)) (t (error "Keyword argument %s not one of (:modes :files :when :match :add-hooks :on-load :on-enter :on-exit)" (car --cl-keys--)))))
  (let ((--cl-keys-- --cl-rest--)) (while --cl-keys-- (cond ((memq (car --cl-keys--) (quote (:modes :files :when :match :add-hooks :on-load :on-enter :on-exit :allow-other-keys))) (setq --cl-keys-- (cdr (cdr --cl-keys--)))) ((car (cdr (memq (quote :allow-other-keys) --cl-rest--))) (setq --cl-keys-- nil)) (t (error "Keyword argument %s not one of (:modes :files :when :match :add-hooks :on-load :on-enter :on-exit)" (car --cl-keys--))))))
  (progn (let ((--cl-keys-- --cl-rest--)) (while --cl-keys-- (cond ((memq (car --cl-keys--) (quote (:modes :files :when :match :add-hooks :on-load :on-enter :on-exit :allow-other-keys))) (setq --cl-keys-- (cdr (cdr --cl-keys--)))) ((car (cdr (memq ... --cl-rest--))) (setq --cl-keys-- nil)) (t (error "Keyword argument %s not one of (:modes :files :when :match :add-hooks :on-load :on-enter :on-exit)" (car --cl-keys--)))))) (let ((init-var (intern (format "%s-init" name)))) (cons (quote progn) (cons (if on-load (cons (quote defvar) (cons init-var (quote ...)))) (cons (list (quote define-minor-mode) name "A project minor mode generated by `def-project-mode!'." (quote :init-value) nil (quote :lighter) "" (quote :keymap) (quote (make-sparse-keymap)) (list (quote if) (list ... name) on-exit (list ... ... ... name) (if on-load ...) on-enter)) (append (let* (... ... ...) (while ... ... ... ...) (nreverse --cl-var--)) (list (if ... ...))))))))
  (let* ((modes (car (cdr (plist-member --cl-rest-- (quote :modes))))) (files (car (cdr (plist-member --cl-rest-- (quote :files))))) (when (car (cdr (plist-member --cl-rest-- (quote :when))))) (match (car (cdr (plist-member --cl-rest-- (quote :match))))) (add-hooks (car (cdr (plist-member --cl-rest-- (quote :add-hooks))))) (on-load (car (cdr (plist-member --cl-rest-- (quote :on-load))))) (on-enter (car (cdr (plist-member --cl-rest-- (quote :on-enter))))) (on-exit (car (cdr (plist-member --cl-rest-- (quote :on-exit)))))) (progn (let ((--cl-keys-- --cl-rest--)) (while --cl-keys-- (cond ((memq (car --cl-keys--) (quote ...)) (setq --cl-keys-- (cdr ...))) ((car (cdr ...)) (setq --cl-keys-- nil)) (t (error "Keyword argument %s not one of (:modes :files :when :match :add-hooks :on-load :on-enter :on-exit)" (car --cl-keys--)))))) (let ((init-var (intern (format "%s-init" name)))) (cons (quote progn) (cons (if on-load (cons (quote defvar) (cons init-var ...))) (cons (list (quote define-minor-mode) name "A project minor mode generated by `def-project-mode!'." (quote :init-value) nil (quote :lighter) "" (quote :keymap) (quote ...) (list ... ... on-exit ... ... on-enter)) (append (let* ... ... ...) (list ...))))))))
  (closure (t) (name &rest --cl-rest--) "Define a project minor-mode named NAME (a symbol) and declare where and how\nit is activated. Project modes allow you to configure 'sub-modes' for\nmajor-modes that are specific to a folder, project structure, framework or\nwhatever arbitrary context you define. These project modes can have their own\nsettings, keymaps, hooks, snippets, etc.\n\nThis creates NAME-hook and NAME-map as well.\n\nA project can be enabled through .dir-locals.el too, by setting `doom-project'.\n\nPLIST may contain any of these properties, which are all checked to see if NAME\nshould be activated. If they are *all* true, NAME is activated.\n\n  :modes MODES -- if buffers are derived from MODES (one or a list of symbols).\n\n  :files FILES -- if project contains FILES; takes a string or a form comprised\n    of nested (and ...) and/or (or ...) forms. Each path is relative to the\n    project root, however, if prefixed with a '.' or '..', it is relative to the\n    current buffer.\n\n  :match REGEXP -- if file name matches REGEXP\n\n  :when PREDICATE -- if PREDICATE returns true (can be a form or the symbol of a\n    function)\n\n  :add-hooks HOOKS -- HOOKS is a list of hooks to add this mode's hook.\n\n  :on-load FORM -- FORM to run the first time this project mode is enabled.\n\n  :on-enter FORM -- FORM is run each time the mode is activated.\n\n  :on-exit FORM -- FORM is run each time the mode is disabled.\n\nRelevant: `doom-project-hook'.\n\n(fn NAME &key MODES FILES WHEN MATCH ADD-HOOKS ON-LOAD ON-ENTER ON-EXIT)" (let* ((modes (car (cdr (plist-member --cl-rest-- (quote :modes))))) (files (car (cdr (plist-member --cl-rest-- (quote :files))))) (when (car (cdr (plist-member --cl-rest-- (quote :when))))) (match (car (cdr (plist-member --cl-rest-- (quote :match))))) (add-hooks (car (cdr (plist-member --cl-rest-- (quote :add-hooks))))) (on-load (car (cdr (plist-member --cl-rest-- (quote :on-load))))) (on-enter (car (cdr (plist-member --cl-rest-- (quote :on-enter))))) (on-exit (car (cdr (plist-member --cl-rest-- (quote :on-exit)))))) (progn (let ((--cl-keys-- --cl-rest--)) (while --cl-keys-- (cond ((memq ... ...) (setq --cl-keys-- ...)) ((car ...) (setq --cl-keys-- nil)) (t (error "Keyword argument %s not one of (:modes :files :when :match :add-hooks :on-load :on-enter :on-exit)" ...))))) (let ((init-var (intern (format "%s-init" name)))) (cons (quote progn) (cons (if on-load (cons ... ...)) (cons (list ... name "A project minor mode generated by `def-project-mode!'." ... nil ... "" ... ... ...) (append ... ...))))))))(+lua-love-mode :modes (lua-mode markdown-mode json-mode) :files (and "main.lua" "conf.lua") :on-load (set-project-type! (quote love2d) :predicate (function +lua-love-project-root) :run (function +lua/run-love-game)) (map! :localleader :map +lua-love-mode-map "b" (function +lua/run-love-game)))
  (def-project-mode! +lua-love-mode :modes (lua-mode markdown-mode json-mode) :files (and "main.lua" "conf.lua") :on-load (set-project-type! (quote love2d) :predicate (function +lua-love-project-root) :run (function +lua/run-love-game)) (map! :localleader :map +lua-love-mode-map "b" (function +lua/run-love-game)))
  eval-buffer(#<buffer  *load*-831406> nil "/home/brightone/.emacs.d.doom/modules/lang/lua/config.el" nil t)  ; Reading at buffer position 974
  load-with-code-conversion("/home/brightone/.emacs.d.doom/modules/lang/lua/config.el" "/home/brightone/.emacs.d.doom/modules/lang/lua/config.el" t nil)
  load("/home/brightone/.emacs.d.doom/modules/lang/lua/config" t nil)
  (condition-case e (load (expand-file-name "config" (plist-get plist :path)) t nil) ((debug doom-error) (signal (car e) (cdr e))) ((debug error) (let* ((source (file-name-sans-extension (expand-file-name "config" (plist-get plist :path)))) (err (cond ((file-in-directory-p source doom-core-dir) (cons ... doom-core-dir)) ((file-in-directory-p source doom-private-dir) (cons ... doom-private-dir)) ((cons ... doom-emacs-dir))))) (signal (car err) (list (file-relative-name (concat source ".el") (cdr err)) e)))))
  (let ((doom--current-module key) (doom--current-flags (plist-get plist :flags))) (condition-case e (load (expand-file-name "config" (plist-get plist :path)) t nil) ((debug doom-error) (signal (car e) (cdr e))) ((debug error) (let* ((source (file-name-sans-extension (expand-file-name "config" ...))) (err (cond (... ...) (... ...) (...)))) (signal (car err) (list (file-relative-name (concat source ".el") (cdr err)) e))))))
  (closure ((force-p) t) (key plist) (let ((doom--current-module key) (doom--current-flags (plist-get plist :flags))) (condition-case e (load (expand-file-name "config" (plist-get plist :path)) t nil) ((debug doom-error) (signal (car e) (cdr e))) ((debug error) (let* ((source (file-name-sans-extension ...)) (err (cond ... ... ...))) (signal (car err) (list (file-relative-name ... ...) e)))))))((:lang . lua) (:flags nil :path "/home/brightone/.emacs.d.doom/modules/lang/lua/"))
  maphash((closure ((force-p) t) (key plist) (let ((doom--current-module key) (doom--current-flags (plist-get plist :flags))) (condition-case e (load (expand-file-name "config" (plist-get plist :path)) t nil) ((debug doom-error) (signal (car e) (cdr e))) ((debug error) (let* ((source ...) (err ...)) (signal (car err) (list ... e))))))) #<hash-table equal 76/87 0x119291d>)
  (if noninteractive nil (maphash (function (lambda (key plist) (let ((doom--current-module key) (doom--current-flags (plist-get plist :flags))) (condition-case e (load (expand-file-name "config" ...) t nil) ((debug doom-error) (signal ... ...)) ((debug error) (let* ... ...)))))) doom-modules) (run-hook-wrapped (quote doom-init-modules-hook) (function doom-try-run-hook)) (condition-case e (load (expand-file-name "config" doom-private-dir) t nil) ((debug doom-error) (signal (car e) (cdr e))) ((debug error) (let* ((source (file-name-sans-extension (expand-file-name "config" doom-private-dir))) (err (cond (... ...) (... ...) (...)))) (signal (car err) (list (file-relative-name (concat source ".el") (cdr err)) e))))))
  (progn (setq doom-init-modules-p t) (maphash (function (lambda (key plist) (let ((doom--current-module key) (doom--current-flags (plist-get plist :flags))) (condition-case e (load (expand-file-name "init" ...) t nil) ((debug doom-error) (signal ... ...)) ((debug error) (let* ... ...)))))) doom-modules) (run-hook-wrapped (quote doom-before-init-modules-hook) (function doom-try-run-hook)) (if noninteractive nil (maphash (function (lambda (key plist) (let ((doom--current-module key) (doom--current-flags ...)) (condition-case e (load ... t nil) (... ...) (... ...))))) doom-modules) (run-hook-wrapped (quote doom-init-modules-hook) (function doom-try-run-hook)) (condition-case e (load (expand-file-name "config" doom-private-dir) t nil) ((debug doom-error) (signal (car e) (cdr e))) ((debug error) (let* ((source (file-name-sans-extension ...)) (err (cond ... ... ...))) (signal (car err) (list (file-relative-name ... ...) e)))))))
  (if (and (or force-p (not doom-init-modules-p)) (not (setq doom-modules nil)) (condition-case e (load (expand-file-name "init" doom-private-dir) t nil) ((debug doom-error) (signal (car e) (cdr e))) ((debug error) (let* ((source (file-name-sans-extension ...)) (err (cond ... ... ...))) (signal (car err) (list (file-relative-name ... ...) e)))))) (progn (setq doom-init-modules-p t) (maphash (function (lambda (key plist) (let ((doom--current-module key) (doom--current-flags ...)) (condition-case e (load ... t nil) (... ...) (... ...))))) doom-modules) (run-hook-wrapped (quote doom-before-init-modules-hook) (function doom-try-run-hook)) (if noninteractive nil (maphash (function (lambda (key plist) (let (... ...) (condition-case e ... ... ...)))) doom-modules) (run-hook-wrapped (quote doom-init-modules-hook) (function doom-try-run-hook)) (condition-case e (load (expand-file-name "config" doom-private-dir) t nil) ((debug doom-error) (signal (car e) (cdr e))) ((debug error) (let* ((source ...) (err ...)) (signal (car err) (list ... e))))))))
  doom-initialize-modules()
  (if noninteractive nil (doom-initialize-modules))
  eval-buffer(#<buffer  *load*-308679> nil "/home/brightone/.emacs.d/core/core.el" nil t)  ; Reading at buffer position 21049
  load-with-code-conversion("/home/brightone/.emacs.d/core/core.el" "/home/brightone/.emacs.d/core/core.el" nil t)
  require(core "/home/brightone/.emacs.d/core/core")
  eval-buffer(#<buffer  *load*> nil "/home/brightone/.emacs.d/init.el" nil t)  ; Reading at buffer position 4522
  load-with-code-conversion("/home/brightone/.emacs.d/init.el" "/home/brightone/.emacs.d/init.el" t t)
  load("/home/brightone/.emacs.d/init" t t)
  #f(compiled-function () #<bytecode 0x1dd9f1>)()
  command-line()
  normal-top-level()
</pre>
</details>

**What was expected to happen**: error-free startup.

**System information:**

<details>
<pre>
Generating Doom info...
- OS: gnu/linux (x86_64-pc-linux-gnu)
- Shell: /bin/zsh
- Emacs: 26.2 (Jun 22, 2019)
- Doom: 2.0.9 (HEAD -> develop 412dabab 2019-06-27 20:00:21 +0300)
- Graphic display: nil (daemon: nil)
- System features: XPM JPEG TIFF GIF PNG RSVG SOUND GPM DBUS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE XFT ZLIB GTK3 X11 XDBE XIM MODULES THREADS LCMS2
- Details:
  env bootstrapper: nil
  elc count: 0
  uname -a:  Linux 5.1.10-gentoo #1 SMP Fri Jun 21 11:05:14 EEST 2019 x86_64
  modules:   (:app calendar regex (rss +org) (write +wordnut +langtool) :collab impatient-mode :completion company (ivy +prescient +fuzzy) :editor evil file-templates fold (format +onsave) lispy multiple-cursors rotate-text snippets :emacs dired electric :email mu4e :lang cc clojure csharp data (elixir +lsp) emacs-lisp erlang go (haskell +intero) (java +meghanada) (javascript +lsp) kotlin latex ledger lua markdown nim (org +alert +attach +babel +capture +export +present) python (ruby +rails) (rust +lsp) sh web :term eshell term :tools debugger docker editorconfig ein eval (flycheck +childframe) flyspell gist (lookup +devdocs) lsp (magit +forge) make pass pdf wakatime :ui doom doom-dashboard doom-quit fill-column hl-todo modeline nav-flash ophints (popup +all +defaults) (pretty-code +fira) treemacs unicode vc-gutter vi-tilde-fringe window-select workspaces :config literate (default +bindings +smartparens +snippets +evil-commands))
  packages:  (anaphora dash dash-functional org-super-agenda)
  exec-path: [omitted for brevity]
</pre>
</details>

**Comment by filalex77** [comment]
I think that `(def-project-mode! :on-load)` takes a `FORM` (as per documentation), so we can wrap the two forms into a `progn`. Just tested, fixes the problem.

**Comment by hlissner** [comment]
Ah, my mistake. Thanks for PR!
