### ISSUE TITLE
Flycheck shows Unicode 0xEC5A in modeline, displays when using emacs-mac

### ISSUE THREAD

**Issue by Ptival** [hlissner/doom-emacs#1519]
This is a minor inconvenience, but I just switched from the emacs distributed by nix, to the emacs-mac fork that still supports the display of emoticons.

Almost everything works perfectly, except that, whereas with emacs-nix, my modeline looks empty when my file flychecks correctly, with emacs-mac, it shows an unmapped Unicode code point:

<img width="169" alt="image" src="https://user-images.githubusercontent.com/478606/60299897-a5035280-98e2-11e9-88f7-4e4be06fb4cc.png">

Is this something I should look into upstream in flycheck? I'm not quite sure which code is responsible for putting that icon in the mode line, instead of the usual Flycheck text.

**Comment by hlissner** [comment]
It looks like your git icon is incorrect too. Are you sure the `all-the-icons` fonts are installed?

**Comment by Ptival** [comment]
Well, nevermind, it was that simple! I had assumed that was just a weird icon the whole time! :-D

Thanks!
