### ISSUE TITLE
How to auto disable ivy posframe buffer in terminal?

### ISSUE THREAD

**Issue by forrestchang** [hlissner/doom-emacs#1520]
When I use Emacs in Terminal, I got the error:

```
Error in post-command-hook (ivy-queue-exhibit): (error no  buffer named *ivy-posframe-buffer*)
```

**Comment by gagbo** [comment]
I opened a PR to fix this behaviour upstream (in ivy-posframe) https://github.com/tumashu/ivy-posframe/pull/53

If you're okay with the fork (you can check differences with upstream [here](https://github.com/tumashu/ivy-posframe/pull/53/files)) you can probably apply the patch directly on your `~/.emacs.d/.local/packages/elpa/ivy-posframe*/ivy-posframe.el` file to fix this.

The other solution is to actually deactivate ivy-posframe-mode (manually or with a hook) when you enter a tty emacsen

**Comment by hlissner** [comment]
tumashu/ivy-posframe#53 has been merged. Once MELPA has absorbed the change, update ivy-posframe with `doom update`. I will consider this resolved; if that isn't the case, let me know and I will reopen this issue. Thanks for bringing it to my attention!
