### ISSUE TITLE
lang:go use lcp-find-defintion if lcp package installed

### ISSUE THREAD

**Issue by idanko** [hlissner/doom-emacs#1521]
Hi, since Language Server Protocol for Go namely `gopls` is quite mature (despite the fact it is under active development) and I also found it faster than `guru` or `godef`, I would suggest using `lcp-find-definition` as a definition tool on set-lookup-handlers when lsp package is provided.

**Comment by hlissner** [comment]
The lookup module [already uses lsp-find-{definitions,references} as its lookup handlers](https://github.com/hlissner/doom-emacs/blob/develop/modules/tools/lsp/config.el#L27-L29) when lsp-mode is enabled. [As well as `lsp-describe-thing-at-point`](https://github.com/hlissner/doom-emacs/blob/develop/modules/tools/lsp/config.el#L9-L10).

Perhaps you haven't enabled the `+lsp` flag for the `:lang go` module?

**Comment by idanko** [comment]
@hlissner Ok, I found that I disabled the lsp-ui package for personal reasons (mostly because it is quite verbose for me), and just use lsp-mode for completion and, so far, for goto definition property (by overriding guru's one). I noticed this setup pretty functional.

**Comment by hlissner** [comment]
As of 2f268e8, the module now falls back to `lsp-find-{definition,references}` when lsp-ui-mode isn't present/enabled, so I'll consider this issue resolved. Let me know if that isn't the case and I will reopen this. Thanks for bringing it to my attention!

**Comment by idanko** [comment]
@hlissner hi, looks like the behavior is not changed. What I've done:

## Setup
doom.d/init.el has lsp and go modules
doom.d/package.el has `(package! lsp-ui :disable t)`

## Flow to reproduce
* cd ~/.emacs.d
* git pull (develop branch)
* doom upgrade && doom re
* open some go file
* press `gd` on `os.Exit()` to fire up goto definition of os stdlib package and Exit() function

## Expected behavior
`lsp-find-definition` run by starting the lsp server

## Actual
guru run

**Comment by hlissner** [comment]
@idanko Are there any warnings/errors in \*Messages\*? (See `SPC h e`). For instance, did the LSP server successfully start?

**Comment by idanko** [comment]
@hlissner aren't, the *Messages* buffer hasn't any lsp messages, even if manually turn on lsp mode, the behavior doesn't change.

**Comment by hlissner** [comment]
I cannot reproduce this. I've tried both `M-x lsp-ui-mode` to disable it on the fly, and disabling the package  with `(package! lsp-ui :disable t)`. In both cases, `+lookup/definition` correctly falls back to `lsp-find-definition`.

Did you remember to run `doom refresh` after disabling the package?

**Comment by hlissner** [comment]
Oh, wait, I see the problem.

> doom.d/package.el has (package! lsp-ui :disable t)

This should be `.doom.d/packages.el`, plural.

**Comment by idanko** [comment]
@hlissner  yy apologies, it's plural, just a typo

**Comment by idanko** [comment]
@hlissner I've fixed the issue on my local machine. Please, check it out if I did well

**Comment by idanko** [comment]
@hlissner my apologies, it's plural, just a typo. After setting (go +lsp) on init.el I found that the lsp server has started but lookup run via go-guru. So lsp is prioritized over guru. Please take a look

**Comment by idanko** [comment]
fixed
