### ISSUE TITLE
LSP breaks org html export

### ISSUE THREAD

**Issue by Foldex** [hlissner/doom-emacs#1524]
Enabling LSP in init.el and then trying to org-html-export-as-html an org file fails with
`Symbol's value as a variable is void: lsp-auto-configure`
Probably caused by https://github.com/hlissner/doom-emacs/commit/a9ca62070c818206874213f0a90b29efc0b84700

**Comment by hlissner** [comment]
As of 8de5e98 this should be resolved. Let me know if that isn't the case and I will reopen this issue. Thanks for bringing it to my attention!
