### ISSUE TITLE
Treemacs doesn't use PNG anymore

### ISSUE THREAD

**Issue by qhuyduong** [hlissner/doom-emacs#1526]
Hi @hlissner ,

After updating doom-emacs and treemacs, I can no longer use PNG icons in Treemacs
![image](https://user-images.githubusercontent.com/16358771/60408900-0b41eb00-9beb-11e9-917a-0a4249e68ffc.png)
Was able to use PNGs with `(setq doom-treemacs-use-generic-icons nil)`.

**Comment by hlissner** [comment]
Treemacs has a new API for themes. You can switch the default icon theme with:

 ```elisp
(after! treemacs
  (treemacs-load-theme "Default"))
```

**Comment by qhuyduong** [comment]
Thank you!
