### ISSUE TITLE
can't search with rg --no-ignore

### ISSUE THREAD

**Issue by bricewge** [hlissner/doom-emacs#1531]
I would like a way to search a directory or a project through `ripgrep` using the option `--no-ignore`. 

For example `+default/search-from-cwd` use `+ivy/project-search-from-cwd` which search all files when passing the universal argument but the doom's wrapper never pass the argument forward instead it use it to specify a directory to search from. Maybe there should be different functions for searching in the current directory/project and another one where you need to specify the directory/project first.

**Comment by hlissner** [comment]
By passing the prefix argument to `SPC / d` and `SPC / p` you will be prompted for the directory/project to search:

+ `SPC u SPC / d` will let you select a directory to search from
+ `SPC u SPC / p` will prompt you for what known project to search

As for the your `--no-ignore` issue, simply start your search with `--no-ignore -- <search terms>`. Or, a shorter version: `-u -- <search terms>`

**Comment by bricewge** [comment]
Oh, nice! Writing the parameters in the search field is good enough for me. Thanks again.

**Comment by hlissner** [comment]
Happy to help! As a side note: 9ffb740 adds `SPC / D` and `SPC / P` as aliases for `SPC u SPC / d` and `SPC u SPC / p`.
