### ISSUE TITLE
org-mode export backends are not being initialized

### ISSUE THREAD

**Issue by robbert-vdh** [hlissner/doom-emacs#1535]
I noticed a lot of export options were missing from the `C-c C-e` prompt in org-mode. It looks like these should have been added by the [`+org|init-export`](https://github.com/hlissner/doom-emacs/blob/33aef74da09ee3d967bca5cacd57a637414063c3/modules/lang/org/config.el#L378) function, but it never gets called anywhere. This is on the latest develop branch commit (33aef74da09ee3d967bca5cacd57a637414063c3).

**Comment by hlissner** [comment]
My bad. This should be fixed in fbf58aa. Thanks for bringing it to my attention!
