### ISSUE TITLE
ESS: C-return triggers default newline-below instead of ess-eval-region-or-line-visibly-and-step

### ISSUE THREAD

**Issue by hliebert** [hlissner/doom-emacs#1541]
When editing a `.r` file using doom and ESS, pressing `C-return` triggers `(newline-below)` instead of `(ess-eval-line)`. I have to delete or comment the following keymap in `modules/config/default/config.el` to get the expected behavior.

```(map! :gni [C-return]    #'+default/newline-below)```

**Comment by hliebert** [comment]
I have tested this using the sandbox (Doom + modules) and the error persists. Is it to do with ESS?

**Comment by hliebert** [comment]
Fixed as of 724413d88f3ab317cbcc8349e3fc18cace86d886.

**Comment by hlissner** [comment]
Ah, this issue slipped by me. Thanks for letting me know!
