### ISSUE TITLE
module term/vterm count not be  "insert mode" during initialization

### ISSUE THREAD

**Issue by cnsunyour** [hlissner/doom-emacs#1543]
last commit to the  term/vterm module has  removed evil config. bu I cannot enter insert mode during open vterm window with "SPC o t". so,  these codes don't seem to be removed.
```
(when (featurep! :editor evil)
    (evil-set-initial-state 'vterm-mode 'insert)
    (setq-hook! 'vterm-mode-hook evil-move-cursor-back nil))
```

**Comment by hlissner** [comment]
The evil configuration in term/vterm was absorbed completely by [evil-collection-vterm](https://github.com/emacs-evil/evil-collection/blob/master/evil-collection-vterm.el#L79-L115). Your `evil-collection` is likely out of date; please update it with `doom update`.

**Comment by hlissner** [comment]
Ah, nevermind. I hadn't updated `evil-collection-mode-list`. As of d45b934 this should be resolved. Update Doom (and evil-collection, if you haven't already) and the issue should go away. If that isn't the case let me know and I will reopen the issue. Thanks for bringing it to my attention!

**Comment by cnsunyour** [comment]
Sure enough, I solved this problem after updating to the latest version, thank you very much.
