### ISSUE TITLE
auth-source-pass-new is not installed.

### ISSUE THREAD

**Issue by flyingns** [hlissner/doom-emacs#1544]
When I `make doctor` always prompts `(:tools pass) auth-source-pass-new is not installed` What the hell? `auth-source-pass` package has been installed.

MacOS mojave
Emacs-plus 26.2

**Comment by flyingns** [comment]
Oh, sorry, I didn't read the instructions carefully. Delete `auth-source-pass` and `mke` will do.

**Comment by flyingns** [comment]
Is a Bug? um um ...

**Comment by hlissner** [comment]
d9f4b13 should fix this issue. The good doctor wasn't taking into account that packages could have psuedonyms. Now it does. Let me know if the issue persists and I'll reopen this. Thanks for bringing it to my attention!
