### ISSUE TITLE
Fringes where?

### ISSUE THREAD

**Issue by sooqua** [hlissner/doom-emacs#1547]
See these tiny-tiny dots at the right side? Is this how am I supposed to know when a line is continuing beyond window size?
![1](https://user-images.githubusercontent.com/4979209/60944023-57c6ae00-a2f0-11e9-8884-36997a3fb0f3.png)
Now, if I do M-: `(set-window-fringes nil 10 10 fringes-outside-margins)` I get something that can _sometimes_ be noticed with a naked eye:
![2](https://user-images.githubusercontent.com/4979209/60944334-31554280-a2f1-11e9-8da8-7bb6dbefdef2.png)
How do I make this change permanent? I tried adding it at the end of my init.el but apparently Doom overrides it. What hook can I use for this, or is there a better solution? Also how do I change the size/color of fringes?

**Comment by hlissner** [comment]
`set-window-fringes` is not going to work from your config. It only sets the fringes for a single window (in this case the "current" window). What is the "current" window while Emacs is starting up?

Add `(fringe-mode NEWSIZE)` to `~/.doom.d/config.el` instead. The default size is `4`, so change it to whatever you like. 8 or 12, perhaps?

As for the color, the `fringe` face controls its looks. You can change its background with:

```elisp
;; in ~/.doom.d/config.el
(custom-set-faces!
  '(fringe :background "#000000")
  '(solaire-fringe-face :background "#000000"))
```

**Comment by sooqua** [comment]
That worked, thanks. But, why are they so tiny by default? Is my system misconfigured (because I didn't change anything in Doom configuration, aside from enabling javascript module)? I don't think you would intentionally make it of size almost invisible after replacing default fringes with those fancy ones.

**Comment by hlissner** [comment]
The size is intentional. The color is not. I'll look into making it a little more visible from https://github.com/hlissner/emacs-doom-themes. 

Besides that, all the other indicators are very visible and don't need any more than 4 pixels of space.

In any case, I'll consider this resolved.
