### ISSUE TITLE
can't start on windows.

### ISSUE THREAD

**Issue by smallzhan** [hlissner/doom-emacs#1548]
with commit c99c184,  it shows  `let: Cannot open load file: Invalid argument, ~/.emacs.d/core/autoload/buffers` and start failed.

I've checked the commits with `git bisect`, and found that the error is introduced by commit 9a02bd8

**Comment by hlissner** [comment]
Could you produce a backtrace from this error?

To do so, enable debug mode in one of these ways:

1. `SPC h d d`
2. `M-x toggle-debug-on-error`
3. Start emacs like so: `emacs --debug-init`

Then reproduce the error.

**Comment by smallzhan** [comment]
emacs 27.0.50, no backtrace shown  with `emacs --debug-init`, Messages buffers are:

> DOOM Running doom hook: doom|init-theme
DOOM Running doom hook: window-divider-mode
Doom loaded 202 packages across 0 modules in 0.581s
DOOM Loading deferred package savehist from doom|transient-hook--load-savehist
DOOM Loading deferred package winner from doom|transient-hook--load-winner
Entering debugger...
doom|protect-fallback-buffer: Cannot open load file: Invalid argument, ~/.emacs.d/core/autoload/buffers
DOOM Incrementally loading tree-widget
DOOM Incrementally loading recentf
Loading d:/smallqiang/.emacs.d/.local/cache/recentf...done
DOOM Finished incremental loading
doom|auto-revert-buffers: Cannot open load file: Invalid argument, ~/.emacs.d/core/autoload/buffers
DOOM Loading deferred package better-jumper from doom|transient-hook--load-better-jumper
DOOM Loading deferred package server from doom|transient-hook--load-server
Entering debugger...
DOOM Loading deferred package undo-tree from doom|transient-hook--load-undo-tree
DOOM Loading deferred package smartparens from doom|transient-hook--load-smartparens
DOOM Loading deferred package paren from doom|transient-hook--load-paren
Failed to load deferred package server: (file-error Cannot open load file Invalid argument ~/.emacs.d/modules/tools/magit/autoload)
DOOM Loading deferred package which-key from doom|transient-hook--load-which-key

**Comment by hlissner** [comment]
Please update to cb401c8, run `doom refresh` and let me know if that resolves the issue.

**Comment by smallzhan** [comment]
It works! 
Thank you
