### ISSUE TITLE
Can't encode with `locale-coding-system` on startup

### ISSUE THREAD

**Issue by SevereOverfl0w** [hlissner/doom-emacs#1549]
```
error: Can’t encode ‘FZF_DEFAULT_OPTS=--bind 'alt-j:jump-accept' --bind 'alt-a:select-all' --prompt='\342\235\257 '’ with ‘locale-coding-system’

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.
```

I couldn't figure out how to get emacs to ignore this either. I tried `unset` in my terminal, but had no luck.

**Comment by SevereOverfl0w** [comment]
removed manually from `~/.emacs.d/.local/env` after reading the source.

**Comment by hlissner** [comment]
A quick workaround for this is to add this to `~/.doom.d/init.el`:

```elisp
(after! core-cli
  (add-to-list 'doom-env-ignored-vars "^FZF_"))
```

In the meantime, I'll look into a proper fix.

**Comment by SevereOverfl0w** [comment]
Thanks!

**Comment by hlissner** [comment]
Try updating to b4d004a (and remove the snippet I gave you above) and see if your issue is resolved.

**Comment by SevereOverfl0w** [comment]
Looks good! Thanks!
