### ISSUE TITLE
How to change treemacs font face? (Looks ugly by default but not in the screenshot)

### ISSUE THREAD

**Issue by azbshiri** [hlissner/doom-emacs#1551]
Amazing distro. and minimal but I'm wondering how can I change treemacs font face same as in the screenshot?

**Comment by hlissner** [comment]
Thannks! The doom-themes package forces treemacs to use a variable-pitch font. You can change this font in Doom by changing `doom-variable-pitch-font`, or disalbe doom-themes' behavior by changing `doom-themes-treemacs-enable-variable-pitch`:

```elisp
(setq doom-variable-pitch-font (font-spec :family "Noto Sans" :size 13))

;; or

(setq doom-themes-treemacs-enable-variable-pitch nil)
```

Hope that helps!

**Comment by azbshiri** [comment]
Thanks for the quick response.
