### ISSUE TITLE
Fuzzy search for projectile find file

### ISSUE THREAD

**Issue by AlexanderArvidsson** [hlissner/doom-emacs#1552]
I'm currently in the process of switching over to Doom from Spacemacs, and one of the most important thing for me is fuzzy matching when switching files using find-file.

How can I configure doom to have the same behavior as I had in spacemacs.
In spacemacs:
![image](https://user-images.githubusercontent.com/2972103/60980656-2b815080-a335-11e9-9c0b-d60415ebb7ec.png)

This does not even match in doom:
![image](https://user-images.githubusercontent.com/2972103/60980730-4bb10f80-a335-11e9-9da2-519823fd0012.png)

I have to write this in order to find the file:
![image](https://user-images.githubusercontent.com/2972103/60980756-5b305880-a335-11e9-80c2-b3679f6ed0fa.png)

**Comment by hlissner** [comment]
You have two options:

**Disable Ivy, enable helm and fuzzy search:**

In your `doom!` block in `~/.doom.d/init.el`:

1. Uncomment `:completion helm`
2. Enable the `+fuzzy` flag: `:completion (helm +fuzzy)`
3. Comment `:completion ivy`
4. Run `~/.emacs.d/bin/doom refresh`
5. Restart Emacs.

**Or enable fuzzy support for ivy**

```diff
   :completion
-  ivy
+  (ivy +fuzzy +prescient)
```

Then run `~/.emacs.d/bin/doom refresh` and restart Emacs.

**Comment by AlexanderArvidsson** [comment]
Thanks, works great!
Quick question though, is there a way to customize the colors when searching?
![image](https://user-images.githubusercontent.com/2972103/60984959-e234ff00-a33c-11e9-8540-986736952435.png)

**Comment by ocharles** [comment]
I would note you don't _need_ `+prescient` - and I've actually found it to be considerably worse than the default.

**Comment by hlissner** [comment]
The relevant faces are:

```
    ivy-minibuffer-match-face-1
    ivy-minibuffer-match-face-2
    ivy-minibuffer-match-face-3
    ivy-minibuffer-match-face-4
```

You can look up their definition with `SPC h F`. A simple way to change them is with `custom-set-faces!`:

```elisp
(custom-set-faces!
  '(ivy-minibuffer-match-face-1 :background "#000000")
  '(ivy-minibuffer-match-face-2 :background "#0000FF")
  ...)
```

In any case, I'll consider the original issue resolved.
