### ISSUE TITLE
Org +ipython language not found

### ISSUE THREAD

**Issue by smsegal** [hlissner/doom-emacs#1553]
When trying to evaluate or edit an ipython org src block, the language cannot be found. In addition, there is no code highlighting.
This appears to be a regression after 468e630110e0e5. 
`No org-babel-execute function for ipython!` when trying to evaluate a src block
`No such language mode: ipython-mode` when trying to edit-special

**Comment by hlissner** [comment]
Have you enabled the `+ipython` flag for the `:lang org` module?

If you have (and you've run `doom refresh`) and it still doesn't work, please include your `M-x doom/info`.

**Comment by smsegal** [comment]
I've enabled the `+ipython `flag in org and I've run doom refresh - still no dice :( 
Here is the relevant org-snippet just in case I'm doing something odd there:
```
#+BEGIN_SRC ipython :session data-loading :results raw drawer
import pandas as pd
import numpy as np
from pathlib import Path
from pprint import pprint
from itertools import compress
#+END_SRC
```

Here is the output from doom/info:

```
- OS: gnu/linux (x86_64-pc-linux-gnu)
- Shell: /usr/bin/fish
- Emacs: 26.2 (Apr 12, 2019)
- Doom: 2.0.9 (HEAD -> develop 69ba8bb6 2019-07-09 21:33:02 +0200)
- Graphic display: t (daemon: nil)
- System features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD LCMS2
- Details:
  ```elisp
  env bootstrapper: nil
  elc count: 0
  uname -a:  Linux 4.4.0-18932-Microsoft #1000-Microsoft Fri Jun 28 16:50:00 PST 2019 x86_64
  modules:   (:completion company (ivy +icons) :ui doom doom-dashboard hl-todo modeline nav-flash ophints (popup +all +defaults) treemacs vc-gutter vi-tilde-fringe window-select :editor evil file-templates fold format multiple-cursors rotate-text snippets :emacs dired electric vc :term vterm :tools direnv docker editorconfig ein eval flycheck flyspell gist (lookup +docsets) lsp magit make pdf tmux :lang data emacs-lisp (javascript +lsp) julia latex markdown (org +attach +babel +ipython +capture +export +habit +present +protocol) (python +lsp +pyenv) (sh +fish) :config default)
  packages:  (magic-latex-buffer all-the-icons-ivy evil-lion shell-pop lorem-ipsum (term-cursor :recipe (term-cursor :repo h0d/term-cursor.el :fetcher github)) yasnippet-snippets kaolin-themes)
  exec-path: (~/development/data_exploration/.venv/bin/ ~/.asdf/shims/ ~/.asdf/bin/ ~/dotfiles/doom/.emacs.d/bin/ ~/.gem/ruby/2.6.0/bin/ ~/.local/bin/ ~/.cargo/bin/ ~/.poetry/bin/ ~/anaconda3/bin/ ~/.fzf/bin/ ~/dotfiles/doom/.emacs.d/bin/ ~/.gem/ruby/2.6.0/bin/ ~/.local/bin/ ~/.cargo/bin/ ~/.poetry/bin/ ~/anaconda3/bin/ /usr/local/sbin/ /usr/local/bin/ /usr/sbin/ /usr/bin/ /sbin/ /bin/ /usr/games/ /usr/local/games/ /mnt/c/WINDOWS/system32/ /mnt/c/WINDOWS/ /mnt/c/WINDOWS/System32/Wbem/ /mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/ /mnt/c/Program/ Files/dotnet/ /mnt/c/Program/ Files/Microsoft/ SQL/ Server/130/Tools/Binn/ /mnt/c/Program/ Files/ (x86)/Microsoft/ SQL/ Server/Client/ SDK/ODBC/130/Tools/Binn/ /mnt/c/Program/ Files/ (x86)/Microsoft/ SQL/ Server/140/Tools/Binn/ /mnt/c/Program/ Files/ (x86)/Microsoft/ SQL/ Server/140/DTS/Binn/ /mnt/c/Program/ Files/ (x86)/Microsoft/ SQL/ Server/140/Tools/Binn/ManagementStudio/ /mnt/c/WINDOWS/System32/OpenSSH/ /mnt/c/Program/ Files/Microsoft/ VS/ Code/bin/ /mnt/c/HashiCorp/Vagrant/bin/ /mnt/c/ProgramData/chocolatey/bin/ /mnt/c/Program/ Files/ (x86)/dotnet/ /mnt/c/Program/ Files/ (x86)/Microsoft/ SQL/ Server/140/DAC/bin/ /mnt/c/Program/ Files/ (x86)/GtkSharp/2.12/bin/ /mnt/c/Program/ Files/ (x86)/Intel/Intel(R)/ Management/ Engine/ Components/DAL/ /mnt/c/Program/ Files/Intel/Intel(R)/ Management/ Engine/ Components/DAL/ /mnt/c/Program/ Files/Git/cmd/ /mnt/c/Program/ Files/nodejs/ /mnt/c/Program/ Files/ (x86)/Yarn/bin/ /mnt/c/Users/ssegal/AppData/Local/Microsoft/WindowsApps/ /mnt/c/Users/ssegal/AppData/Roaming/npm/ /mnt/c/Program/ Files/Oracle/VirtualBox/ /mnt/c/Users/ssegal/AppData/Local/Yarn/bin/ /usr/lib/x86_64-linux-gnu/emacs/26.2/x86_64-linux-gnu/)
  ```
```

**Comment by hlissner** [comment]
As of eee147f this should be resolved. Let me know if that isn't the case and I will reopen this issue. Thanks for bringing this to my attention!

**Comment by smsegal** [comment]
Thanks for the quick action on this issue. This fix is almost complete, the only thing now is that when attempting to eval a cell, the output is opened in a side window and not in the results drawer in the org buffer. I've pasted an example buffer below as well as a screenshot of the results. 

```
#+BEGIN_SRC ipython :session data-loading :results raw drawer
import numpy as np

print(list(reversed(sorted(10*np.random.randn(10)))))
#+END_SRC

#+RESULTS:
:results:
# Out[12]:
:end:
```
![image](https://user-images.githubusercontent.com/7110093/60998504-11d90c80-a327-11e9-921c-bbec7782f1a1.png)


(Also, as you can probably see from the screenshot I'm running Emacs through WSL, although I don't think that should be contributing to this)

**Comment by smsegal** [comment]
Doing some more investigating, it looks like this issue can be partially attributed to ob-ipython, as returning a result from the code block will output to the results drawer. 

However, every eval still results in a side window being opened, which is suboptimal.

**Comment by hlissner** [comment]
Could you get me the name of that popup buffer? i.e. focus it and run `M-; (buffer-name)`?

**Comment by smsegal** [comment]
the buffer that the results are printed to is `*ob-ipython-out*`. 
I've also noticed that REPL buffers(`*ob-ipython-kernel-<session-name>*`) are also being created for each session defined, and the system is also hanging excessively after each code block eval.

**Comment by hlissner** [comment]
I'm having some trouble figuring out if this behavior is intended (by the ob-ipython package) or if one of our advice functions is causing it.

Please try inserting the following into your `~/.doom.d/config.el`:

```elisp
(after! ob-ipython
  (advice-remove #'ob-ipython--create-repl  #'+org*ob-ipython--create-repl)
  (advice-remove #'org-babel-edit-prep:ipython  #'+org*babel-edit-prep:ipython)
  (advice-remove #'org-babel-execute:ipython  #'+org*babel-execute:ipython)
  (advice-remove #'org-babel-ipython-initiate-session  #'+org*ob-ipython-initiate-session))
```

And see if it behaves correctly afterwards.

**Comment by smsegal** [comment]
I've read through the documentation, and what I was reporting as an error above is actually a *feature* from ob-ipython. 
The relevant snippet from the documentation is:
"Stdout/err from code evaluation is displayed in a popup buffer. This is great for debugging or getting verbose output that is best left out of documents (e.g progress updates). If you wish to capture output in your document use the :results output SRC block header."  [See the fourth bullet point here.](https://github.com/gregsexton/ob-ipython#what-features-are-there-outside-of-org-src-block-evaluation)

Ahh, I see I already put you through doing all the work before I could tell you not to bother. Thanks for all the help.

**Comment by hlissner** [comment]
I'm glad we could figure it out. Happy to help! 

As a side note: if you'd like that popup to be more discreet you can create popup rules for them. [These are the defaults](https://github.com/hlissner/doom-emacs/blob/develop/modules/lang/org/contrib/ipython.el#L21-L27).

**Comment by smsegal** [comment]
Oh, popup rules are something I haven't really explored yet. Thanks for the tip!
