### ISSUE TITLE
multi-term / term-mode keybinds don't kick in

### ISSUE THREAD

**Issue by ct-emil** [hlissner/doom-emacs#1554]
Hello,

I am having a problem applying custom keybinds to multi-term and term-mode. I am currently using this approach though I have tried others (including def-package-hook with all pre-config, post-config and post-init):

```emacs-lisp
(map! ...
      :map term-mode-map
      :i "C-y" #'term-paste
      :map term-raw-map
      :i "C-y" #'term-paste)
```

However, on init of multi-term, the binding is not set. I also tried this:

```emacs-lisp
(map! ...
     (:after multi-term
          :map term-mode-map
          :i "C-y" #'term-paste
          :map term-raw-map
          :i "C-y" #'term-paste))
```

But it doesn't catch. However, if I evaluate this after init directly in the config file, then it works.

Sorry if there is something obvious I've overlooked, but I tried :after multi-term, term-mode, term, etc, with no luck. I've tried using term-mode-hook and disregarding the doom configuration macros, but that also didn't work (On startup, without evaluating the settings above).

Can anyone offer me advice or a hint on how I am supposed to set these keyboard bindings without manually evaluating the code?

Thank you for reading.

**Comment by hlissner** [comment]
Have you tried `(:after term ...)`?

**Comment by ct-emil** [comment]
I did try it, in my org literate config. I have just one map! command.

Then, if I run `multi-term` as the first thing after starting Emacs, and C-h k "C-y", I get `term-send-raw`.

This is my relevant map! section now:

```emacs-lisp
      (:after term
        :map term-mode-map
        :i "C-y" #'term-paste
        :map term-raw-map
        :i "C-y" #'term-paste))
```

Ah I see your edit - thank you @hlissner. Do you have a Patreon or a "coffee me pls" site?

**Comment by ct-emil** [comment]
It worked - thank you very much.

**Comment by hlissner** [comment]
Great! Happy to help!

> Do you have a Patreon or a "coffee me pls" site?

Thank you, I appreciate the sentiment! I just added a sponsor button to the project (top of the page).
