### ISSUE TITLE
C-h paging not showing in SPC w

### ISSUE THREAD

**Issue by szhang104** [hlissner/doom-emacs#1555]
In the "window" pop up after pressing `SPC w`, `C-h` does not bring up the paging menu like in the other popups. Instead, it acts like an `h` is pressed.

```
- OS: gnu/linux (x86_64-pc-linux-gnu)
- Shell: /bin/zsh
- Emacs: 26.2 (Apr 12, 2019)
- Doom: 2.0.9 (HEAD -> develop, _upgrade/develop cb401c83 2019-07-10 16:05:40 +0200)
```

**Comment by hlissner** [comment]
I'm afraid there's no way around this. The paging menu key (`C-h`) is hard-coded into [which-key](https://github.com/justbur/emacs-which-key), it won't work for any prefix with a `C-h` keybind and `C-w C-h` is bound to `evil-window-left`, which I'm not willing to sacrifice.

If paging is more important to you, it can be undone:

```elisp
(map! :map evil-window-map "C-h" nil)
```
