### ISSUE TITLE
What font been used in the screenshot?

### ISSUE THREAD

**Issue by azbshiri** [hlissner/doom-emacs#1557]
I was wondering what font been used in the screenshot? M+ or is it a patched version?

**Comment by gagbo** [comment]
I'd guess [Fira Code + Noto Sans](https://github.com/hlissner/doom-emacs-private/blob/master/config.el#L19)

**Comment by hlissner** [comment]
Fira Code + Noto Sans is what I'm using today (shown here):

![image](https://user-images.githubusercontent.com/510883/61040997-f24aee00-a3d1-11e9-96a2-0931e34f6290.png)

But the screenshot on the README is at least two years old. I believe I was either using [Inconsolata](https://www.levien.com/type/myfonts/inconsolata.html) or [Input Mono Narrow](http://input.fontbureau.com/), and the variable-pitch font in the treemacs sidebar is Input Sans (from the same bundle as Input Mono).

I'd still be using Input if it were easier to automate its installation on NixOS.

**Comment by azbshiri** [comment]
Thanks, that's it.
