### ISSUE TITLE
[BUG] Navigating to end of line does not work in comments

### ISSUE THREAD

**Issue by haji-ali** [hlissner/doom-emacs#1558]
**Describe the issue**
In the line (in C++ mode for example)
```
^  |   // This is a comment$
```
where `^` is the beginning of the line, `$` is the end and `|` is the cursor position. Pressing `C-e` which calls `doom/forward-to-last-non-comment-or-eol` does not do anything. On the other hand
```
^     |// This is a comment$
```
and
```
^|     // This is a comment$
```
moves the cursor to the end-of-line as expected.

**System information**
<details><pre>
- OS: gnu/linux (x86_64-pc-linux-gnu)
- Shell: /bin/zsh
- Emacs: 26.1 (Feb 11, 2019)
- Doom: 2.0.9 (HEAD -> develop, origin/develop 774956d8 2019-06-30 13:21:06 +0200)
- Graphic display: t (daemon: nil)
- System features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 THREADS
- Details:
  ```elisp
  env bootstrapper: envvar-file
  elc count: 32
  uname -a:  Linux 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64
  modules:   (:completion company (ivy +icons) :ui workspaces doom hl-todo modeline treemacs vc-gutter (window-select +switch-window) :editor fold multiple-cursors rotate-text snippets :term eshell term :emacs dired electric :tools eval (lookup +docsets) flycheck flyspell magit make :lang cc data emacs-lisp (latex +latexmk) markdown (org +attach +babel +capture) python (sh +fish) swift :email mu4e :app calendar regex :config literate (default +bindings +smartparens))
  packages:  (mu4e-alert hungry-delete yasnippet-snippets edit-server org-clock-today beacon dired-subtree dired-single fancy-narrow org-super-agenda xterm-color openwith fill-column-indicator)
  exec-path: (/opt/mono/bin /opt/texlive/current/bin/x86_64-linux /usr/lib64/qt-3.3/bin /opt/mono/bin /opt/icub/bin /opt/rh/devtoolset-7/root/usr/bin ~/.local/bin /usr/local/bin /usr/bin /bin ~/bin /usr/local/sbin /usr/sbin /opt/ns-2.35/bin /usr/hosts ~/bin ~/.local/libexec/emacs/26.1/x86_64-pc-linux-gnu/)
  ```
</pre></details>

**Comment by hlissner** [comment]
f0abd10 should fix this. Let me know if that isn't the case and I will reopen this issue. Thanks for bringing it to my attention, and for the detailed bug report!

**Comment by haji-ali** [comment]
You are welcome and thanks for fixing the bug. 

This is not incredibly important but I think I will include it here since it is relevant. If I again have the line 

```
^  |   // This is a comment$
```

Then press `C-e` then the cursor position will alternate between the beginning and the end of the line. This is consistent with having text like this

```
^  |Some_code;   // This is a comment$
```
where the cursor would jump between the ends of the un-commented and commented texts. However, since the "un-commented" text is empty in my example above, `C-e` jumps to the beginning of the line which is counter intuitive.

**Comment by hlissner** [comment]
Agreed. I've changed their behavior when called in between indent/bol and eol/beginning-of-comment in 17d7130. Let me know how it fares.

**Comment by haji-ali** [comment]
I am not sure what changed. Here's what currently happens in my setup

```
^  |   // This is a comment$
```

Pressing `C-e`

```
^     // This is a comment$|
```

Pressing `C-e` again the cursor returns to its position.

```
^  |   // This is a comment$
```

In fact it seems that after the recent update this (`C-e` moving the cursor between the eol and the previous position) happens in any line commented or not. Is this the intended behavior?

**Comment by hlissner** [comment]
This is the intended behavior, yes. The logic of the command is to alternate between two points:

a. The end of the line (ignoring comments) and
b. The end of the line (including comments)

If there the line (ignoring comments) is empty, it will use your current position (rather than move the cursor to the beginning of the line -- which is likely to be before the cursor). I thought it was this behavior that you were saying was unintuitive.

**Comment by haji-ali** [comment]
Ah. I misunderstood. Yes, indeed moving the cursor to the beginning of the line was unintuitive. 
I guess moving the cursor back to the current position is useful. I was just surprised by it and thought it was unintended behavior. 

My initial expectation of the command (reading the documentation) was that if the text is`Code/Comment` then `C-e` would alternate between the two ends, otherwise it would behave as a normal `C-e` (i.e., `move-end-of-line`) and move to the end of the line without moving back. But I could see myself using the additional functionality.  With that begin said, shouldn't `C-a` also mirror this functionality as well?

Also, I am noticing some weird behavior with this. The text
```
import test
import string

def main():
    pass
```

If I go to the middle of `import test` and press `C-e` a few times the cursor alternates between the end and the middle. Then if I press `C-n` to go to the empty line and `C-e` the cursor alternate between the beginning and end of the first line `import test`!
This also happens in some other cases where the cursor jumps to some random line when I press `C-e` instead of alternating the cursor position in the current line. But I cannot pinpoint a case scenario.
