### ISSUE TITLE
[BUG] void-function org-outline-overlay-data

### ISSUE THREAD

**Issue by peng051410** [hlissner/doom-emacs#1559]
**Describe the issue**
Start with a brief 1 or 2 sentence summary of issue.

in org file, when i run er/expand-region, it can't work, error message:
`Debugger entered--Lisp error: (void-function org-outline-overlay-data)
  org-outline-overlay-data(t)
  er/save-org-mode-excursion(#f(compiled-function () #<bytecode 0x484774c5>))
  er--expand-region-1()
  er/expand-region(1)
  funcall-interactively(er/expand-region 1)
  call-interactively(er/expand-region nil nil)
  command-execute(er/expand-region)`

**System information**
<details><pre>
- OS: darwin (x86_64-apple-darwin18.2.0)
- Shell: /bin/zsh
- Emacs: 26.2 (Apr 22, 2019)
- Doom: 2.0.9 (HEAD -> develop, upstream/develop, _upgrade/develop c99c184f 2019-07-09 23:30:59 +0200)
- Graphic display: t (daemon: nil)
- System features: JPEG RSVG IMAGEMAGICK GLIB NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2
- Details:
  ```elisp
  env bootstrapper: nil
  elc count: 0
  uname -a:  Darwin 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64
  modules:   (:completion company (ivy +childframe) :ui workspaces vc-gutter doom doom-dashboard modeline hl-todo nav-flash ophints treemacs (popup +all +defaults) window-select :editor evil file-templates snippets rotate-text :emacs vc dired electric :term eshell term :tools lookup eval ein editorconfig gist flyspell flycheck magit :term vterm :tools reference pdf :lang lsp rest data (python +conda) ess (latex +latexmk +zathura) (org +attach +babel +capture +present) (org-private +todo +babel +capture +latex +export +style) emacs-lisp (java +meghanada) javascript markdown sh web :app sx rss :email mu4e :app write :config default)
  packages:  (helpful esup (dired-k :disable t) (flycheck-popup-tip :disable t) (flycheck-pos-tip :disable t) (ob-mongo :disable t) (ob-sql-mode :disable t) (ob-translate :disable t) (prettify-utils :recipe (prettify-utils :fetcher github :repo Ilazki/prettify-utils.el :files (*))) prescient company-prescient flycheck-posframe ov evil-collection shr-tag-pre-highlight orgit org-kanban alert pinentry zmq websocket simple-httpd academic-phrases ivy-yasnippet tldr ess electric-operator (emacs-snippets :recipe (emacs-snippets :fetcher github :repo hlissner/emacs-snippets :files (*))) lispy lispyville sed-mode function-args snakemake-mode deadgrep)
  exec-path: (/usr/local/bin /usr/bin /bin /usr/sbin /sbin /Applications/VMware Fusion.app/Contents/Public /Library/TeX/texbin /opt/X11/bin /Applications/Wireshark.app/Contents/MacOS /usr/local/Cellar/emacs-plus/26.2/libexec/emacs/26.2/x86_64-apple-darwin18.2.0)
  ```
</pre></details>

**Comment by hlissner** [comment]
I cannot reproduce this. Could you reproduce this in vanilla Doom? i.e.

1. `SPC h E` (or `M-x doom/sandbox`)
2. Type in

```elisp
(require 'expand-region)
(require 'org)

(find-file "some/org/file.org")
```

3. `C-c C-p` to launch vanilla Doom (minus your config)
4. `M-x er/expand-region`

If you cannot reproduce it, then the issue is likely in your private config. Do you have a link to your config?

**Comment by peng051410** [comment]
Hi, i use https://github.com/syl20bnr/spacemacs/issues/12099#issuecomment-490600059 to solve it.

**Comment by peng051410** [comment]
> I cannot reproduce this. Could you reproduce this in vanilla Doom? i.e.
> 
> 1. `SPC h E` (or `M-x doom/sandbox`)
> 2. Type in
> 
> ```emacs-lisp
> (require 'expand-region)
> (require 'org)
> 
> (find-file "some/org/file.org")
> ```
> 
> 1. `C-c C-p` to launch vanilla Doom (won't load your config)
> 2. `M-x er/expand-region`
> 
> If you cannot reproduce it, then the issue is likely in your private config. Do you have a link to your config?

i cannot reproduce it.

**Comment by hlissner** [comment]
> Hi, i use syl20bnr/spacemacs#12099 (comment) to solve it.

Ah, that makes sense. In the future, `doom compile :plugins` will re-byte-compile plugins. Thanks for letting me know!
