### ISSUE TITLE
[BUG] doom/set-indent-width breaks with some modes

### ISSUE THREAD

**Issue by robbert-vdh** [hlissner/doom-emacs#1561]
**Describe the issue**
It seems like `editorconfig-indentation-alist` has two different specifications. It contains either `(mode var1 var2 ...)` lists containing variable names or `(mode . fn)` cons cells with a function that sets the correct variables for us. The new (and incredibly useful!) `doom/set-indent-width` function doesn't yet handle the second case.

**Steps to reproduce**
1. Open a Python file
2. `M-x doom/set-indent-width 4 <RET>`

**System information**
<details><pre>
- OS: gnu/linux (x86_64-pc-linux-gnu)
- Shell: /usr/bin/fish
- Emacs: 27.0.50 (apr 13, 2019)
- Doom: 2.0.9 (HEAD -> develop, origin/develop 18758c39 2019-07-12 16:24:01 +0200)
- Graphic display: t (daemon: nil)
- System features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER LCMS2 GMP
- Details:
  ```elisp
  env bootstrapper: nil
  elc count: 191
  uname -a:  Linux 5.1.16-1-MANJARO #1 SMP PREEMPT Thu Jul 4 20:32:22 UTC 2019 x86_64
  modules:   (:completion company (helm +fuzzy) :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor evil file-templates fold (format +onsave) multiple-cursors rotate-text snippets :emacs dired electric vc :term eshell vterm :tools debugger direnv docker editorconfig ein eval (flycheck +childframe) flyspell gist (lookup +docsets) lsp magit make pdf rgb :lang agda (cc +lsp) csharp data emacs-lisp ess (haskell +intero) javascript (latex +latexmk) markdown (org +gnuplot +dragndrop +ipython +pandoc +present) (php +lsp) python rest (rust +lsp) (sh +fish +lsp) (web +lsp) :app write :config default)
  packages:  (academic-phrases ein evil-lion ggtags kotlin-mode ob-ipython page-break-lines phpcbf pkgbuild-mode)
  exec-path: (~/.cargo/bin ~/.local/bin ~/.cargo/bin ~/.dotfiles/bin ~/.local/bin /usr/local/sbin /usr/local/bin /usr/bin /opt/cuda/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /var/lib/snapd/snap/bin /usr/lib/emacs/27.0.50/x86_64-pc-linux-gnu)
  ```
</pre></details>

**Comment by hlissner** [comment]
Good catch! I had glossed over it. As of f3fa1b0 this should be resolved. Let me know if that isn't the case and I'll reopen the issue. Thanks for bringing it to my attention!
