### ISSUE TITLE
[BUG] restclient not work with ob-restclient

### ISSUE THREAD

**Issue by peng051410** [hlissner/doom-emacs#1563]
**Describe the issue**
I use ob-restclient. but restclient mode not work in org file.

<details><pre>
`Debugger entered--Lisp error: (error "Restclient encountered an error")
  signal(error ("Restclient encountered an error"))
  error("Restclient encountered an error")
  org-babel-execute:restclient("   :common-test-host = https://ptcommon.reader.qq.com\n   :common-online-host = https://newcommon.reader.qq.com\n\n   :androidHeader =<<\n   supportmh: 1\n   os: android\n   nosid: 1\n   sid: 154475513467327\n   gselect: 1\n   themeid: 1000\n   qimei: 352284040670808\n   qrem: 1\n   qrtm: 1547523947\n   loginType: 1\n   cookie: ywkey=yw0UT3jZ5rGy\n   qrsy: FA6E79D59B12FB5568258ED718917696\n   ckey: 000110010010\n   ywguid: 979299714\n   qqnum: 979299714\n   ywkey: yw0UT3jZ5rGy\n   c_platform: android\n   supportTS: 2\n   ua: unknown#TAG-TL00C01B156#19\n   tinkerid: qqreader_7.0.1.0888_android-common-363342\n   server_sex: 1\n   c_version: qqreader_7.0.1.0888_android\n   channel: 00000\n   safekey: 70F5EBAA2762BE4871379A56DBCC9950\n   mversion: 7.0.1\n   Connection: Keep-Alive\n   User-Agent: okhttp/3.6.0\n   #\n\n   :iosHeader =<<\n   server_sex: 1\n   Cookie: book_sid=3496855f04bf4d3ca64af8f17f951dd1; pgv_pvi=9190629376\n   User-Agent: QQReaderUI/10239 CFNetwork/976 Darwin/18.2.0\n   ywguid: 979299714\n   Accept-Encoding: br, gzip, deflate\n   safkey: 2469e703444b2ba94cff7b65a9662491\n   sex: 0\n   qrtm: 1550818370\n   ua: iPhone7,1-iOS12.1.4\n   version: qqreader_7.0.1.0266_iphone\n   sid: 1550193095476992\n   net_type: 1\n   platform: ioswp\n   Connection: keep-alive\n   qrsy: af54e0ecf497d2d9c454a9c275dd9ffd\n   jailbreak: 0\n   Accept-Language: zh-cn\n   nosid: 1\n   gselect: 0\n   qrem: 0\n   themeid: 2000\n   Accept: */*\n   ywkey: ywMPGhjAmgbV\n   loginType: 1\n   text_type: 1\n   qimei: 923aeb73-7907-4ca9-907b-7d7498ced792\n\n   #request\n   GET :common-online-host/common/growlevel/monthGiftList?debug=1&uin=964141718\n   :iosHeader" ((:colname-names) (:rowname-names) (:result-params "replace" "raw") (:result-type . value) (:results . "replace raw") (:exports . "code") (:session . "none") (:cache . "no") (:noweb . "no") (:hlines . "no") (:tangle . "no")))
  org-babel-execute-src-block(nil ("restclient" "   :common-test-host = https://ptcommon.reader.qq.com\n   :common-online-host = https://newcommon.reader.qq.com\n\n   :androidHeader =<<\n   supportmh: 1\n   os: android\n   nosid: 1\n   sid: 154475513467327\n   gselect: 1\n   themeid: 1000\n   qimei: 352284040670808\n   qrem: 1\n   qrtm: 1547523947\n   loginType: 1\n   cookie: ywkey=yw0UT3jZ5rGy\n   qrsy: FA6E79D59B12FB5568258ED718917696\n   ckey: 000110010010\n   ywguid: 979299714\n   qqnum: 979299714\n   ywkey: yw0UT3jZ5rGy\n   c_platform: android\n   supportTS: 2\n   ua: unknown#TAG-TL00C01B156#19\n   tinkerid: qqreader_7.0.1.0888_android-common-363342\n   server_sex: 1\n   c_version: qqreader_7.0.1.0888_android\n   channel: 00000\n   safekey: 70F5EBAA2762BE4871379A56DBCC9950\n   mversion: 7.0.1\n   Connection: Keep-Alive\n   User-Agent: okhttp/3.6.0\n   #\n\n   :iosHeader =<<\n   server_sex: 1\n   Cookie: book_sid=3496855f04bf4d3ca64af8f17f951dd1; pgv_pvi=9190629376\n   User-Agent: QQReaderUI/10239 CFNetwork/976 Darwin/18.2.0\n   ywguid: 979299714\n   Accept-Encoding: br, gzip, deflate\n   safkey: 2469e703444b2ba94cff7b65a9662491\n   sex: 0\n   qrtm: 1550818370\n   ua: iPhone7,1-iOS12.1.4\n   version: qqreader_7.0.1.0266_iphone\n   sid: 1550193095476992\n   net_type: 1\n   platform: ioswp\n   Connection: keep-alive\n   qrsy: af54e0ecf497d2d9c454a9c275dd9ffd\n   jailbreak: 0\n   Accept-Language: zh-cn\n   nosid: 1\n   gselect: 0\n   qrem: 0\n   themeid: 2000\n   Accept: */*\n   ywkey: ywMPGhjAmgbV\n   loginType: 1\n   text_type: 1\n   qimei: 923aeb73-7907-4ca9-907b-7d7498ced792\n\n   #request\n   GET :common-online-host/common/growlevel/monthGiftList?debug=1&uin=964141718\n   :iosHeader" ((:colname-names) (:rowname-names) (:result-params "raw" "replace") (:result-type . value) (:results . "raw replace") (:exports . "code") (:tangle . "no") (:hlines . "no") (:noweb . "no") (:cache . "no") (:session . "none")) "" nil 62862 "(ref:%s)"))
  org-ctrl-c-ctrl-c(nil)
  funcall-interactively(org-ctrl-c-ctrl-c nil)
  call-interactively(org-ctrl-c-ctrl-c nil nil)
  command-execute(org-ctrl-c-ctrl-c)`
</pre></details>

**Steps to reproduce**
1. go to .org file
2. select an org restclient item
3. C-c C-c

**System information**
<details><pre>
- OS: darwin (x86_64-apple-darwin18.2.0)
- Shell: /bin/zsh
- Emacs: 26.2 (Apr 22, 2019)
- Doom: 2.0.9 (HEAD -> develop, origin/develop, origin/HEAD f90c0b80 2019-07-12 18:25:28 +0200)
- Graphic display: t (daemon: nil)
- System features: JPEG RSVG IMAGEMAGICK GLIB NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2
- Details:
  ```elisp
  env bootstrapper: envvar-file
  elc count: 0
  uname -a:  Darwin 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64
  modules:   (:completion company ivy :ui deft doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor evil file-templates fold multiple-cursors rotate-text snippets :emacs dired electric vc :tools eval flycheck (lookup +docsets) magit :lang clojure data emacs-lisp (java +meghanada) markdown (org +dragndrop +ipython +pandoc +present) rest sh :config default)
  packages:  n/a
  exec-path: (~/.nix-profile/bin /usr/local/bin /usr/bin /bin /usr/local/sbin ~/github/dotfiles/script ~/Library/Python/3.7/bin /usr/local/opt/mysql@5.7/bin ~/.jenv/bin /usr/local/opt/grep/libexec/gnubin ~/go/bin ~/.ihsec/doom/bin /usr/local/texlive/2019/bin/x86_64-darwin /usr/local/opt/fzf/bin /usr/local/Cellar/emacs-plus/26.2/libexec/emacs/26.2/x86_64-apple-darwin18.2.0/)
  ```
</pre></details>

**Comment by hlissner** [comment]
I cannot reproduce this. Please include an example src block that fails for you.

**Comment by peng051410** [comment]
`* Inbox
  :PROPERTIES:
  :ID:       A42D23AB-7638-4B95-8391-B34E2C1CFAEC
  :END:
  #+BEGIN_SRC restclient
  GET http://www.baidu.com
  #+END_SRC`

when i send C-c ', it not show the restclient style, and restclient-mode command not work. my normal restclient style like this:
![image](https://user-images.githubusercontent.com/5512326/61190567-e19bc000-a6d0-11e9-85a5-8739f2cacfc6.png)
in the .http file, resclient is good

**Comment by peng051410** [comment]
Maybe my machine problem?

**Comment by peng051410** [comment]
My machine problem.
