### ISSUE TITLE
[HOWTO] use PCRE in searches

### ISSUE THREAD

**Issue by sooqua** [hlissner/doom-emacs#1564]
**What I want to achieve**
Use perl compatible regular expressions in searches.

Let's say I have this in my buffer:
`foo bar`
I press
`/(?<=foo)\s*bar`
I get [search failed].
I tried adding `\` before parentheses and other characters but it didn't work.

**System information**
<details><pre>
- OS: gnu/linux (x86_64-pc-linux-gnu)
- Shell: /usr/bin/zsh
- Emacs: 26.2 (Apr 12, 2019)
- Doom: 2.0.9 (HEAD -> develop, origin/develop, origin/HEAD c99c184f 2019-07-09 23:30:59 +0200)
- Graphic display: t (daemon: nil)
- System features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2
- Details:
  ```elisp
  env bootstrapper: envvar-file
  elc count: 0
  uname -a:  Linux 5.1.16-arch1-1-ARCH #1 SMP PREEMPT Wed Jul 3 20:23:07 UTC 2019 x86_64
  modules:   (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor evil file-templates fold multiple-cursors rotate-text snippets :emacs dired electric vc :tools eval flycheck (lookup +docsets) magit :lang data emacs-lisp javascript markdown (org +dragndrop +ipython +pandoc +present) sh :config default)
  packages:  n/a
  exec-path: (/usr/local/bin /usr/bin /bin /usr/local/sbin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /usr/lib/emacs/26.2/x86_64-pc-linux-gnu/)
  ```
</pre></details>

**Comment by sooqua** [comment]
I don't understand how to invoke [=regex](https://github.com/hlissner/doom-emacs/blob/develop/modules/app/regex/config.el#L13)
If entered as a `:` command it just outputs **1**, no "regex window" popup.
No match in `M-x`
Symbol's function definition is void in `M-:`

**Comment by hlissner** [comment]
Sorry to say, you won't find native PCRE _inside_ Emacs. It has [its own regex engine](https://www.gnu.org/software/emacs/manual/html_node/elisp/Regular-Expressions.html) with its own quirks. That said, you do have two options:

1. `pcre-mode` will get you close:

   ```elisp
   ;; ~/.doom.d/config.el
   (pcre-mode +1)
   ```

   pcre-mode does some magic behind the scenes to convert PCRE entered into some commands (like `evil-search`) into Emacs' flavor of regular expressions. _However,_ you still won't have lookaround assertions (e.g. `(?<=foo)`) -- Emacs simply doesn't support it.

2. Clone [emacs-pcre](https://github.com/syohex/emacs-pcre) somewhere, compile pcre-core.c, and load pcre.el. This loads PCRE bindings that you could now use to advise `evil-search` to get it to use them. Then you'd get native PCRE in Emacs.

However, this requires a build of Emacs with support for dynamic modules.

3. Use Emacs regex; search for `foo\s-*bar` instead.

> I don't understand how to invoke =regex

Normally, you'd have to enable the `:app regex` module first (then run `doom refresh` and restart Emacs) for `=regex` to become available, but the `:app regex` module is incomplete and not terribly functional. That is why there is no entry for it in [init.example.el](https://github.com/hlissner/doom-emacs/blob/develop/init.example.el) or [modules/README.org](https://github.com/hlissner/doom-emacs/blob/develop/modules/README.org). I don't recommend using it. https://regexr.com is a good alternative.

----

Ultimately, I'd suggest learning Emacs' flavor of regex. Even if you manage to bring PCRE to Emacs, perfect coverage will be an uphill battle.

**Comment by sooqua** [comment]
Got it. Thanks for the reply.

**Comment by cameronraysmith** [comment]
Has anyone had luck using the recommendation at https://www.emacswiki.org/emacs/RegularExpression#toc8 to use https://github.com/benma/visual-regexp-steroids.el for this purpose?
