### ISSUE TITLE
[BUG] Errors after recent update

### ISSUE THREAD

**Issue by haji-ali** [hlissner/doom-emacs#1566]
After a recent update I am getting the following error on `doom refresh`

```
Contacting host: elpa.gnu.org:443
gnutls.el: (err=[-50] The request is invalid.) boot: (:priority NORMAL:-VERS-TLS1.3 :hostname elpa.gnu.org :loglevel 0 :min-prime-bits 256 :trustfiles (/etc/pki/tls/certs/ca-bundle.crt) :crlfiles nil :keylist nil :verify-flags nil :verify-error t :callbacks nil)
Trying again (gnutls-error elpa.gnu.org -50)
```

when trying to install the new doom-snippets package.

I am also getting the following error on `doom compile :core`:
```
Cannot load all-the-icons: (user-error "all-the-icons-icon-for-file is already memoized")
```

and many `Unused lexical variable/argument` warnings.

Apologies if this is caused by a mistake that I made while updating. But I am not sure how to trace it.

**Comment by jdnavarro** [comment]
Something similar was happening to me because my local `gnutls-utils` didn't support TLS1.3. I could fix it by setting gnutls algorithm priority to TLS-1.2: `(setq gnutls-algorithm-priority "NORMAL:-VERS-TLS1.2")`.

**Comment by Oreodave** [comment]
I'm getting the same issue as well. 

@jdnavarro where are you supposed to put that code snip for it to work? init.el?

**Comment by vharish** [comment]
@Oreodave I've simply did a git grep got gnutls and replaced 1.3 with 1.2. It was there at a couple of places. I'm sure you can do so in the config.el as well.

@jdnavarro Thanks for the tip.

**Comment by haji-ali** [comment]
It seems to be in two places: [here](https://github.com/hlissner/doom-emacs/blob/854d8ce00aa96c41bfe901d6b274d6f95615ba13/core/autoload/packages.el#L28) and [here](https://github.com/hlissner/doom-emacs/blob/854d8ce00aa96c41bfe901d6b274d6f95615ba13/modules/tools/lookup/config.el#L153)

I have been trying to avoid modifying doom (opting instead for my own config.org files on top of it), but this modification seems unavoidable on my work computer.

**Comment by credmp** [comment]
Just to chime in. I am running Ubuntu 18.04 LTS and it does not support TLS1.3. You will get the above error when trying to quickstart/refresh your doom packages.

I changes the 2 mentions of TLS1.3 in the elisp files and it is working OK now.  I would think we should look at capabilities of the installed system before setting a specific TLS version. I would think LTS systems will have issues with TLS1.3 as a default.

**Comment by hlissner** [comment]
I've just published the `straight` branch, which replaces our current package manager (package.el + quelpa) with [straight.el](https://github.com/raxod502/straight.el). This should address this issue. If you're feeling adventurous, [I talk about what to expect going into it in another thread](https://github.com/hlissner/doom-emacs/issues/374#issuecomment-513627824).

**Comment by credmp** [comment]
Tested the straight branch on Ubuntu 18.04 LTS, it works correctly for a standard install (doom install and doom refresh).

**Comment by hlissner** [comment]
Now that straight is on `develop`, I'll consider this resolved. Thanks for bringing this to my attention!

**Comment by igorlakic** [comment]
I get this warning (gnutls.el: (err=[-50] The request is invalid) and I'm unable to fix it. Can I get a bit help?

I'm on Ubuntu 18.04 and I've installed emacs26 from ppa:kelleyk/emacs

**Comment by hlissner** [comment]
@igorlakic Please open a new issue for that; don't forget to include your `M-x doom/info`.

It's likely that https://github.com/hlissner/doom-emacs/pull/2763 may be causing your issues, but you shouldn't be using package.el to begin with, so more investigation is needed.

**Comment by igorlakic** [comment]
@hlissner Thanks for fast reply! Ok, I'm going to open a new issue (I thought it's related to this issue so I didn't want to make duplicates).
