### ISSUE TITLE
[HOWTO] How to disable rust building informations on the modeline

### ISSUE THREAD

**Issue by forrestchang** [hlissner/doom-emacs#1567]
**What I want to achieve**
I want to disable the building informations on the modeline because it's too annoying.

![2019-07-15 21 46 38](https://user-images.githubusercontent.com/7857126/61221220-9a521580-a74a-11e9-8bae-115bfc1420e9.gif)

**System information**
<details><pre>
- OS: darwin (x86_64-apple-darwin18.5.0)
- Shell: /bin/zsh
- Emacs: 27.0.50 (Jul 02, 2019)
- Doom: 2.0.9 (HEAD -> develop, origin/develop, origin/HEAD feb9799f 2019-07-12 01:08:41 +0200)
- Graphic display: nil (daemon: nil)
- System features: RSVG IMAGEMAGICK GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS XWIDGETS JSON PDUMPER LCMS2 GMP
- Details:
  ```elisp
  env bootstrapper: envvar-file
  elc count: 2
  uname -a:  Darwin 18.5.0 Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64
  modules:   (:completion company (ivy +fuzzy +childframe) :ui nav-flash deft doom doom-dashboard doom-quit hl-todo indent-guides modeline (popup +all +defaults) treemacs unicode vc-gutter vi-tilde-fringe (window-select +switch-window +numbers) workspaces :editor evil fold format multiple-cursors snippets :input chinese :emacs dired electric vc :term eshell term vterm :tools ansible debugger docker editorconfig ein eval (flycheck +childframe) flyspell gist (lookup +docsets) lsp macos magit make pdf prodigy rgb terraform tmux upload wakatime :lang rust assembly cc clojure common-lisp erlang elixir elm emacs-lisp ess go haskell java javascript julia kotlin latex lua markdown (org +attach +habit +babel +capture +export +present +ipython +protocol) php python scala sh web :email mu4e :config default :private my-org my-python)
  packages:  (writeroom-mode py-isort protobuf-mode py-yapf calfw rfc-mode applescript-mode rainbow-identifiers keyfreq exec-path-from-shell org-pomodoro org-gcal org-super-agenda ox-hugo org-journal org-attach-screenshot lsp-python-ms flycheck-pycheckers)
  exec-path: (/usr/local/bin /usr/bin /bin /usr/sbin /sbin /usr/local/mysql/bin /usr/local/opt/sqlite/bin /Library/Tex/texbin ~/.dotfiles/zsh/functions ~/.cargo/bin ~/.local/bin ~/.ghcup/bin /usr/local/Cellar/emacs-plus/HEAD-b35f378/libexec/emacs/27.0.50/x86_64-apple-darwin18.5.0)
  ```

</pre></details>

**Comment by hlissner** [comment]
Sorry for the late response. I've been unable to zero in on the cause of this, but recently Doom replaced `rust-mode` with `rustic-mode` for Emacs 26+ users. Are you still experiencing this issue?

**Comment by filalex77** [comment]
I'm using `rustic` on the `straight` branch now, and it does the same thing in the modeline.

**Comment by hlissner** [comment]
I cannot determine where the mode-line is being modified. There are no references to `mode-line` or `global-mode-string` in rust-mode, rustic, doom-modeline, cargo or any of the other rust module plugins. 

Could either of you check the values of `after-save-hook` and `global-mode-string` in a rust buffer?

**Comment by filalex77** [comment]
`after-save-hook`:

```emacs-lisp
(lsp-on-save
 wakatime-save
 flycheck-handle-save
 rustic-after-save-hook
 t
 ws-butler-after-save)
```

`global-mode-string`:

```emacs-lisp
(((t lsp-clients-rust-progress-string))
 (pyvenv-virtual-env-name
  (" venv:" pyvenv-virtual-env-name " ")))
```

---

I came up with this to disable this behavior:

```emacs-lisp
(setq-hook! 'rustic-mode-hook
  global-mode-string
  (seq-remove
   (lambda (modespec)
     (and (listp (car modespec))
          (eq (cadar modespec)
              'lsp-clients-rust-progress-string)))
   global-mode-string))
```

Pretty hacky, but does the job.

**Comment by hlissner** [comment]
Ah, lsp, of course. I find this line in lsp-rust.el:

```elisp
(add-to-list 'global-mode-string (list '(t lsp-clients-rust-progress-string)))
```

So, to reverse it:

```elisp
(after! lsp-rust
  (setq global-mode-string
        (delete '((t lsp-clients-rust-progress-string))
                global-mode-string)))
```
