### ISSUE TITLE
Improve the lang/java

### ISSUE THREAD

**Issue by vsr625** [hlissner/doom-emacs#157]
I know this is asking too much from your side, but I would really love if you can add more features to the lang/java like code completion, refactoring,optimizing imports, generating getters, setters, and constructors.
The current config provides only company suggestions for the snippets in java. Spacemacs develop branch has a lot of stuff that I have mentioned, but I don't want to switch and don't know how to configure it. It would really great if you or anyone else who has already implemented those things can help me out here. Thanks

**Comment by hlissner** [comment]
Code completion should be available now (through meghanada), but I'm working on a module (`feature/refactor`) to provide a common interface for registering and invoking refactoring commands. Once that is done I will extend support for Java.

**Comment by hlissner** [comment]
I am reopening this because I haven't finished delivering the promised improvements to the java module. I have a couple in the works, including optional eclim support. I'll announce it here once I'm done.
