### ISSUE TITLE
[BUG] "Doom" on initial screen looks bad after change font size

### ISSUE THREAD

**Issue by przemyslawjanpietrzak** [hlissner/doom-emacs#1572]
**Describe the issue**
 "Doom" on initial screen looks bad after change font size [screenshot]

**Steps to reproduce**
Add `(setq doom-font (font-spec :size 14))` to `config.el` and restart emacs

![Screenshot 2019-07-18 at 09 32 03](https://user-images.githubusercontent.com/9966695/61438223-3e041700-a93f-11e9-91e1-7ff273c58800.png)

**Comment by hlissner** [comment]
Without a `:family` specified in that `font-spec`, I'm not sure what font Emacs falls back to, but it is one of your system defaults. In this case, it's a variable-width font (i.e. a non-monospace font). The dashboard (and most of Emacs, for that matter), expects characters to have a fixed width.

To fix this, specify a monospace font:

```elisp
(setq doom-font (font-spec :family "Fira Code" :size 14))
```

Or change your system default font.

**Comment by przemyslawjanpietrzak** [comment]
You're right! after add `:family "Fira Code"` `DOOM` looks beautiful. Thanks a lot!
