### ISSUE TITLE
[BUG] +default/search-project-for-symbol-at-point breaks if nothing at point

### ISSUE THREAD

**Issue by Gollum999** [hlissner/doom-emacs#1575]
**Describe the issue**
I bound <kbd>SPC / p</kbd> to [`+default/search-project-for-symbol-at-point`](https://github.com/hlissner/doom-emacs/blob/ba71d95066a067aa9d59631554809993809d10d6/modules/config/default/autoload/default.el#L266) instead of of the default `+default/search-project`.  However, I found that this throws an error if there is no symbol under the cursor.  I think the more sensible behavior would be to fall back to `""` (that is, the behavior of `+default/search-project`) if there is nothing at the current point.

<details><pre>
Debugger entered--Lisp error: (wrong-type-argument arrayp nil)
  replace-regexp-in-string("[$(-+.?[-^{-}]" "\\\\\\&" nil)
  rxt-string->pcre(#s(rxt-string :chars nil :case-fold nil))
  rxt-adt->pcre/lev(#s(rxt-string :chars nil :case-fold nil))
  rxt-adt->pcre(#s(rxt-string :chars nil :case-fold nil))
  rxt-quote-pcre(nil)
  (+ivy/project-search nil (rxt-quote-pcre symbol))
  (cond (t (+ivy/project-search nil (rxt-quote-pcre symbol))) (nil (+helm/project-search nil (rxt-quote-pcre symbol))) ((rgrep (regexp-quote symbol))))
  (let ((default-directory (if arg (let* ((projects (and t ...))) (if projects (completing-read "Switch to project: " projects nil t nil nil (doom-project-root)) (user-error "There are no known projects"))) default-directory))) (cond (t (+ivy/project-search nil (rxt-quote-pcre symbol))) (nil (+helm/project-search nil (rxt-quote-pcre symbol))) ((rgrep (regexp-quote symbol)))))
  +default/search-project-for-symbol-at-point(nil nil)
  funcall-interactively(+default/search-project-for-symbol-at-point nil nil)
  call-interactively(+default/search-project-for-symbol-at-point nil nil)
  command-execute(+default/search-project-for-symbol-at-point)
</pre></details>

**Steps to reproduce**
1. Call `+default/search-project-for-symbol-at-point` when there is no symbol at the current point

**System information**
<details><pre>
- OS: gnu/linux (x86_64-pc-linux-gnu)
- Shell: /bin/zsh
- Emacs: 26.2 (May 14, 2019)
- Doom: 2.0.9 (HEAD -> develop, _upgrade/develop d697cb7e 2019-06-26 19:18:04 +0200)
- Graphic display: t (daemon: nil)
- System features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS
- Details:
  ```elisp
  env bootstrapper: envvar-file
  elc count: 0
  uname -a:  Linux 3.10.0-693.17.1.el7.x86_64 #1 SMP Thu Jan 25 20:13:58 UTC 2018 x86_64
  modules:   (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor evil file-templates fold multiple-cursors rotate-text snippets :emacs dired electric vc :term eshell term :tools debugger eval flycheck (lookup +docsets) lsp magit :lang cc data emacs-lisp (java +meghanada) javascript markdown (org +attach +babel +capture +export +habit +present +protocol) python sh web :config default :private common tradebot nil)
  packages:  (centered-cursor-mode dired-narrow dired-subtree flycheck-mypy mwim pyenv-mode)
  exec-path: (~/bin /opt/bwtk/2018.1/bin ~/.nvm/versions/node/v9.7.0/bin ~/.local/bin /usr/lib64/qt-3.3/bin /usr/lib64/ccache /usr/local/bin /usr/local/sbin /usr/bin /usr/sbin /bin /sbin /opt/hadoop/bin /opt/spark/bin /opt/omni414/bin /opt/pg/bin /opt/toolchain/clang-5.0.0/bin /opt/toolchain/gcc-7.2.0/bin /opt/qt/bin ~/.emacs.d/bin ~/scripts ~/src/python3/bld/release_static/bin ~/src/python3/tradebot/Binaries/java ~/src/python3/tradebot/python/prog ~/src/python3/tradebot/python/tb/tools/tsanders ~/src/master/bld/release_static/bin ~/src/master/tradebot/Binaries/java ~/src/master/tradebot/python/prog ~/src/master/tradebot/scripts ~/src/master/tradebot/python/tb/tools/tsanders /usr/local/libexec/emacs/26.2/x86_64-pc-linux-gnu/)
  ```
</pre></details>

**Comment by triklsbg** [comment]
As of today the command bound to =SPC *= is not smart enough to come up with a useful search string in a for example empty line. It gives an error message "Wrong type argument:  arrayp, nil"

**Comment by hlissner** [comment]
Sorry for the late response. I'm not sure exactly at what point this was fixed, but I can no longer reproduce it since the introduction of `doom-thing-at-point-or-region`, which `SPC *` now uses, so I'll consider this resolved. Thanks for bringing it to my attention!
