### ISSUE TITLE
[BUG] RTags is unable to start rdm-process

### ISSUE THREAD

**Issue by WhatDothLife** [hlissner/doom-emacs#1579]
After a recent upgrade (rtags-start-process-unless-running) fails, since it can't find the rdm-binary. The exact output reads as follows:

RTags: Can’t start the process ‘/home/michael/.emacs.d/.local/etc/rtags//rtags-2.33/bin/’. Please check the value of the variables ‘rtags-path’ and ‘rtags-rdm-binary-name’. 

Steps to reproduce:
1. Activate the cc module
2. Run M-x rtags-install
3. Invoke (rtags-start-process-unless-running)

- OS: gnu/linux (x86_64-pc-linux-gnu)
- Shell: /bin/zsh
- Emacs: 26.2 (Apr 12, 2019)
- Doom: 2.0.9 (HEAD -> develop, origin/develop, origin/HEAD 8b27d19e 2019-07-20 11:05:52 +0200)
- Graphic display: t (daemon: nil)
- System features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2
- Details:
  ```elisp
  env bootstrapper: nil
  elc count: 0
  uname -a:  Linux 5.2.1-gnu-1 #1 SMP PREEMPT Thu Jul 18 22:08:45 UTC 2019 x86_64
  modules:   (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) treemacs vc-gutter vi-tilde-fringe window-select :editor evil file-templates fold (format +onsave) multiple-cursors rotate-text :emacs dired electric :term term :emacs vc :tools eval flycheck flyspell (lookup +docsets) magit make pdf :lang cc data emacs-lisp ess markdown (org +attach +babel +capture +export +habit +present +protocol) sh :email mu4e :config default)
  packages:  n/a
  exec-path: (~/.local/bin/ /usr/local/sbin /usr/local/bin /usr/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /usr/lib/emacs/26.2/x86_64-pc-linux-gnu)
  ```

**Comment by hlissner** [comment]
This is likely due to `rtags-rc-binary-name` and/or `rtags-rdm-binary-name` being blank, which is a bug on the `develop` branch, but has been resolved on the `straight` branch (which will be merged over the weekend).

As a temporary workaround try the following:

```elisp
(after! rtags
  (setq rtags-rc-binary-name (or rtags-rc-binary-name "rc")
        rtags-rdm-binary-name (or rtags-rdm-binary-name "rdm")))
```
