### ISSUE TITLE
How to disable magit-todo in some git projects?

### ISSUE THREAD

**Issue by FirstLoveLife** [hlissner/doom-emacs#1583]
I have some projects, like linux kernel, have too many todos which'll make emacs hang too long. How to disable magit-todo in such projects?

**Comment by magnetophon** [comment]
I fully disabled it, for the same reason:
```
(package! magit-todos :disable t)
```

**Comment by hlissner** [comment]
What @magnetophon suggested is a good option. Here are three more:

1. You can speed up magit-todos-mode by limiting how deep it searches: `(setq magit-todos-depth 2)`

2. Install ripgrep, if you haven't already. magit-todos will use it if it's available and it's _much_ faster than the git-grep and find backends.

**Comment by FirstLoveLife** [comment]
@hlissner @magnetophon thanks for your suggestions, they are really helpful. 
Two questions left:
- is it possible to disable magit-todos locally with `.dir-locals.el`
- how to set `(setq magit-todos-depth 2)` in `.dir-locals.el`? 
putting
```
(require 'magit-todos)
(setq magit-todos-depth 1)
```
in `dir-locals.el` doesn't take effects.

**Comment by ckruse** [comment]
`.dir-locals.el` file should contain a mapping of major mode to alists, you can't put regular elisp into it. This should work for you:

~~~elisp
((nil . ((magit-todos-depth . t))))
~~~

this maps all major modes (because of the `nil`).

**Comment by alphapapa** [comment]
See also command `add-dir-local-variable`.

**Comment by FirstLoveLife** [comment]
```
((nil . ((magit-todos-depth . t))))
```

Thanks for suggenstion. But magit-todos still take effect with this line in `.dir-locals.el`.

**Comment by ckruse** [comment]
Sorry, typo. `1` instead of `t`.

Have a look at <https://endlessparentheses.com/a-quick-guide-to-directory-local-variables.html>, Artur is the author of Paradox and writes some interesting stuff about emacs. The linked article is a quick start guide to directory local variables.
