### ISSUE TITLE
[HOWTO] disable solaire mode

### ISSUE THREAD

**Issue by madhat2r** [hlissner/doom-emacs#1586]
**What I want to achieve**
Disable `solaire-mode`

I have tried in config.el
```
(def-package-hook! solaire-mode
   :pre-init
   (setq solaire-global-mode nil))
(after! solaire-mode (solaire-global-mode))

```
Also tried this in packages.el:
```
(package! solaire-mode :disable t) ;;wont disable it??

```
**System information**
<details><pre>
- OS: gnu/linux (x86_64-pc-linux-gnu)
- Shell: /usr/bin/zsh
- Emacs: 26.2 (Apr 12, 2019)
- Doom: 2.0.9 (HEAD -> develop, _upgrade/develop 8b27d19e 2019-07-20 11:05:52 +0200)
- Graphic display: t (daemon: nil)
- System features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2
- Details:
  ```elisp
  env bootstrapper: nil
  elc count: 0
  uname -a:  Linux 4.19.46-1-lts #1 SMP Sun May 26 13:54:01 CEST 2019 x86_64
  modules:   (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) (pretty-code +iosevka) treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor evil file-templates fold multiple-cursors rotate-text snippets :emacs dired electric vc :term vterm :tools eval flycheck flyspell gist (lookup +docsets) lsp magit pass pdf upload :lang clojure common-lisp data emacs-lisp hy javascript markdown (org +dragndrop +ipython +pandoc +present) plantuml python sh web :app mail (write +wordnut +langtool) :config default)
  packages:  (smartparens (solaire-mode :disable t) evil-cleverparens)
  exec-path: (/opt/pyenv/plugins/pyenv-virtualenv/shims ~/.pyenv/shims ~/.pyenv/bin ~/bin ~/perl5/bin ~/.rbenv/shims ~/.rbenv/bin /usr/local/sbin /usr/local/bin /usr/bin /usr/local/sbin /usr/local/bin /usr/bin /usr/bin/vendor_perl /usr/bin/core_perl /opt/cuda/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /usr/lib/emacs/26.2/x86_64-pc-linux-gnu)
  ```
</pre></details>

**Comment by hlissner** [comment]
> (setq solaire-global-mode nil)

Setting the variable doesn't actually disable a minor mode.

> (after! solaire-mode (solaire-global-mode))

If you don't pass `-1` to a minor mode function, it won't disable it, it will only make sure it's enabled. This would work:

```elisp
(after! solaire-mode
  (solaire-global-mode -1))
```

> (package! solaire-mode :disable t) ;;wont disable it??

Did you run `doom refresh` and restart Emacs afterwards?

**Comment by madhat2r** [comment]
@hlissner yes I did run `doom refresh` and restarted emacs. Then i started down the other path of trying to turn it off.

I thought that setting the var would stop the initial turning it on. 

```
(after! solaire-mode
  (solaire-global-mode -1))
```
Works as in it disables it globally. 

The strange thing is that now when buffers open they are bright, then when I enable it again via `M-x solaire-global-mode` the main buffers dim back. But it is just the opposite when it is enabled. I am using the `doom-nord` theme so maybe it is an issue with that instead of solaire.

Can anyone you reproduce this or is it just my mis-configuration?

**Comment by madhat2r** [comment]
@hlissner nevermind, now when I restart it using `(after! solaire-mode (solaire-global-mode -1))` it starts with no bright buffers. Not sure why must have been user error. Sorry for the noise. And thanks for your help.

**Comment by hlissner** [comment]
solaire-mode is configured to swap the backgrounds for some themes. I'm confused as to why the `package!` solution didn't work, but I'm glad you figured it out.
