### ISSUE TITLE
[BUG] Ctrl-K in Ivy history kills buffer

### ISSUE THREAD

**Issue by intpl** [hlissner/doom-emacs#1598]
This is similar to this I reported some time ago, except after invoking Ivy, you need to launch it's history (using C-s): https://github.com/hlissner/doom-emacs/issues/1538

**Steps to reproduce**
SPC / p
C-s
C-k (expected: move up, actual: kill buffer)

**System information**

- OS: gnu/linux (x86_64-pc-linux-gnu)
- Shell: /usr/bin/fish
- Emacs: 27.0.50 (lip 15, 2019)
- Doom: 2.0.9 (HEAD -> develop, origin/develop, origin/HEAD f754d4ff 2019-07-23 18:23:17 +0200)
- Graphic display: t (daemon: nil)
- System features: XPM JPEG TIFF GIF PNG RSVG SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD PDUMPER LCMS2 GMP
- Details:
  ```elisp
  env bootstrapper: nil
  elc count: 0
  uname -a:  Linux 5.0.0-21-generic #22-Ubuntu SMP Tue Jul 2 13:27:33 UTC 2019 x86_64
  modules:   (:completion company (ivy +fuzzy) :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) tabbar treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor evil file-templates fold multiple-cursors rotate-text snippets :emacs dired electric vc :term term :tools editorconfig eval flycheck flyspell (lookup +docsets) magit pdf rgb tmux upload :lang common-lisp crystal data erlang elixir emacs-lisp go (haskell +intero) javascript markdown (org +attach +babel +capture +export +habit +present +protocol) php python rest ruby rust (sh +fish) web :config default)
  packages:  (rvm robe yari goto-gem projectile-rails ruby-tools auto-complete zoom graphql-mode graphql company-flx evil-anzu helm-dash zeal-at-point google-translate solarized-theme (evil-snipe :disable t) (solaire-mode :disable t) (forge :disable t) (evil-escape :disable t))
  exec-path: (~/.rvm/rubies/ruby-2.5.3/bin/ ~/.fzf/bin ~/go/bin ~/.rvm/gems/ruby-2.5.3/bin ~/.rvm/gems/ruby-2.5.3@global/bin ~/.rvm/rubies/ruby-2.5.3/bin ~/.rvm/bin /bin ~/.fzf/bin /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /usr/games /usr/local/games /snap/bin /usr/local/libexec/emacs/27.0.50/x86_64-pc-linux-gnu)
  ```

**Comment by intpl** [comment]
oh and btw, while we are on it: what is the Doom way to kill a buffer in Ivy minibuffer (SPC ,)? C-w does not work for me

**Comment by hlissner** [comment]
This is a known issue that has been addressed on the `straight` branch. It will be merged sometime late next week. If you'd like to give it a try, sooner, [check out this thread](https://github.com/hlissner/doom-emacs/issues/374#issuecomment-513627824).

> what is the Doom way to kill a buffer in Ivy minibuffer (SPC ,)?

All "alternative" actions in ivy/counsel commands are available under the `C-o` prefix. `C-o k` will kill the selected buffer in `SPC ,`.
