### ISSUE TITLE
[BUG] org-decrypt-entry error

### ISSUE THREAD

**Issue by flyingns** [hlissner/doom-emacs#1606]
![Screen Shot 2019-07-28 at 12 06 57 ](https://user-images.githubusercontent.com/16456728/62002211-f4cb7880-b131-11e9-8bed-5e20372d0577.png)

The above org-crypt-entry runs correctly

![Screen Shot 2019-07-28 at 12 07 21 ](https://user-images.githubusercontent.com/16456728/62002232-44aa3f80-b132-11e9-8855-1ccabb9d0baf.png)

But when I run org-decrypt-entry, I get an error.

![Screen Shot 2019-07-28 at 12 07 43 ](https://user-images.githubusercontent.com/16456728/62002238-73c0b100-b132-11e9-896a-3b12d7461461.png)

There used to be no problem when using gnupg@1.4.

Now I used gnupg 2.2.16 to report this error.

--
macos mojave
emacs-plus 26.2
gnupg 2.2.16

**Comment by flyingns** [comment]
Switching from gnupg@1.4 to gnupg 2.2.16 is because when I use gnupg@1.4, epa-decrypt-file will get an error:

`Gpg: invalid option "--pinentry-mode" error`

Therefore, gnupg@1.4 and gnupg@2.2 have errors in different situations.

**Comment by hlissner** [comment]
I cannot reproduce the error on linux and don't have a mac handy for testing atm. As far as I'm aware, Doom uses org-crypt's default settings, all except for:

```elisp
(setq org-crypt-key user-mail-address)
```

If setting this back to its default with `(after! org (setq org-crypt-key ""))` does not work, then I'm inclined to suspect that this is an external misconfiguration. I've barely used org-crypt so I won't be of much help, unfortunately.

**Comment by flyingns** [comment]
Not related to the above settings.

After testing, GUI emacs directly encrypt will report an error. I am running in iterm:

`$ emacs ~/test.org`

When org-decrypt-entry is in the open emacs window, this will pop up in the iterm window:

![Screen Shot 2019-07-28 at 20 58 38 ](https://user-images.githubusercontent.com/16456728/62007107-2d903f80-b17c-11e9-8b6e-604d9890403d.png)


Enter the password here to decrypt the org entry.
Later, in the emacs of the GUI, I can use decrypt normally.

This is really strange! Very...

**Comment by flyingns** [comment]
It still seems to be a bit problematic.

Uh...

**Comment by hlissner** [comment]
You need to install either one of the other `pinentry-*` packages on your system, e.g. `pinentry-gtk`, so that your passphrase prompt opens outside of the shell that runs those gpg commands (which won't be visible from Emacs).

**Comment by flyingns** [comment]
According to this [link](https://www.emacswiki.org/emacs/EasyPG) , installing [MacGPG2](https://gpgtools.org/) has solved this annoying problem.
