### ISSUE TITLE
[BUG] Emacs upgrades are not handled in the straight branch

### ISSUE THREAD

**Issue by jboyens** [hlissner/doom-emacs#1607]
**Describe the issue**
A new version of Emacs on the straight branch has an uncaught error on `upgrade`. 
`(no-catch . No catch for tag: emacs-version-changed, nil)`

I build Emacs from source and refresh from source control about once a week. I recently switched to the straight branch and noticed this as I was doing my `doom upgrade`

To fix I tried just about every seemingly applicable doom command:
1. `upgrade` again
2. `rebuild`
3. `purge`
4. `clean`

The final "fix" was to `rm -rf ~/.emacs.d/.local/straight`

**Comment by hlissner** [comment]
a9c1968 should fix the `doom upgrade` command, however, the `emacs-version-changed` error is caused by straight being compiled with a different version of Emacs. I'll work on improving the UX of that contingency, but `doom build -f` should fix the issue (it will recompile all packages).

**Comment by hlissner** [comment]
Doom should now handle the emacs-version-changed error with slightly more grace (with a more descriptive error message). With a9c1986, which fixes the `doom upgrade` command, I will consider this resolved. Let me know if that isn't the case and I will reopen the issue. Thanks for bringing it to my attention!
