### ISSUE TITLE
[BUG] straight branch: `progn: Symbol’s function definition is void: straight--reset-caches` when calling `doom/reload-packages`

### ISSUE THREAD

**Issue by ckruse** [hlissner/doom-emacs#1618]
When calling `doom/reload-packages` I get this error message:

~~~
progn: Symbol’s function definition is void: straight--reset-caches
~~~

Backtrace:

<details><pre>
Debugger entered--Lisp error: (void-function straight--reset-caches)
  (straight--reset-caches)
  (progn (if doom-debug-mode (progn (let ((inhibit-message (active-minibuffer-window))) (message #("DOOM Initializing straight" 0 5 (face font-lock-comment-face)))))) (setq doom-init-packages-p t) (straight--reset-caches) (mapc (function straight-use-recipes) doom-core-package-sources) (straight-register-package (list (quote straight) (quote :type) (quote git) (quote :host) (quote github) (quote :repo) (format "%s/straight.el" straight-repository-user) (quote :files) (quote ("straight*.el")) (quote :branch) straight-repository-branch)) (mapc (function straight-use-package) doom-core-packages) (if noninteractive (progn (add-hook (quote kill-emacs-hook) (function doom--finalize-straight)))) (let ((--dolist-tail-- (straight--directory-files (straight--build-dir)))) (while --dolist-tail-- (let ((package (car --dolist-tail--))) (let* ((var (directory-file-name ...))) (if (memql var load-path) (with-no-warnings load-path) (setq load-path (cons var load-path)))) (setq --dolist-tail-- (cdr --dolist-tail--))))))
  (if (or force-p (not doom-init-packages-p)) (progn (if doom-debug-mode (progn (let ((inhibit-message (active-minibuffer-window))) (message #("DOOM Initializing straight" 0 5 (face font-lock-comment-face)))))) (setq doom-init-packages-p t) (straight--reset-caches) (mapc (function straight-use-recipes) doom-core-package-sources) (straight-register-package (list (quote straight) (quote :type) (quote git) (quote :host) (quote github) (quote :repo) (format "%s/straight.el" straight-repository-user) (quote :files) (quote ("straight*.el")) (quote :branch) straight-repository-branch)) (mapc (function straight-use-package) doom-core-packages) (if noninteractive (progn (add-hook (quote kill-emacs-hook) (function doom--finalize-straight)))) (let ((--dolist-tail-- (straight--directory-files (straight--build-dir)))) (while --dolist-tail-- (let ((package (car --dolist-tail--))) (let* ((var ...)) (if (memql var load-path) (with-no-warnings load-path) (setq load-path ...))) (setq --dolist-tail-- (cdr --dolist-tail--)))))))
  doom-initialize-packages(t)
  doom/reload-packages()
  funcall-interactively(doom/reload-packages)
  call-interactively(doom/reload-packages record nil)
  command-execute(doom/reload-packages record)
  helm-M-x(nil #("doom/reload-packages" 0 20 (match-part "doom/reload-packages")))
  funcall-interactively(helm-M-x nil #("doom/reload-packages" 0 20 (match-part "doom/reload-packages")))
  call-interactively(helm-M-x nil nil)
  command-execute(helm-M-x)
</pre></details>

**Steps to reproduce**

1. Start emacs
2. do a `./bin/doom update` while emacs is running
3. call `M-x doom/reload-packages`

**System information**

<details>

```
emacs   version    26.2
        features   JPEG RSVG IMAGEMAGICK GLIB NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2
        build      Apr 23, 2019
        buildopts  (--disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus/26.2/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus/26.2 --with-xml2 --without-dbus --with-gnutls --with-imagemagick --with-modules --with-rsvg --with-ns --disable-ns-self-contained)
doom    version    2.0.9
        build      HEAD -> straight 40eb9cf1 2019-07-29 21:23:51 +0200
system  type       darwin
        config     x86_64-apple-darwin18.5.0
        shell      /usr/local/bin/zsh
        uname      Darwin 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64
        path       (~/dev/emacs/elixir-ls/release ~/.rbenv/shims ~/.rbenv/shims ~/.rbenv/shims /usr/local/bin /usr/bin /bin /usr/sbin /sbin /usr/local/MacGPG2/bin /usr/local/opt/go/libexec/bin /usr/local/opt/go/libexec/bin /usr/local/opt/go/libexec/bin /usr/local/Cellar/emacs-plus/26.2/libexec/emacs/26.2/x86_64-apple-darwin18.5.0/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company (helm +fuzzy) :ui doom doom-dashboard doom-quit hl-todo indent-guides modeline nav-flash ophints (popup +all +defaults) treemacs vc-gutter vi-tilde-fringe window-select :editor file-templates fold (format +onsave) multiple-cursors rotate-text snippets :emacs dired vc :tools ansible editorconfig eval flycheck (lookup +docsets) lsp macos magit :lang data erlang (elixir +lsp) emacs-lisp (javascript +lsp) markdown (org +attach +babel +capture +export +habit +present +protocol) (ruby +lsp) sh (web +lsp) :config default)
        packages   (mwim org-projectile (alchemist-company :disable t) (alchemist :disable t) (tide :disable t) (magit-todos :disable t) (enh-ruby-mode :disable t) move-text flycheck-mix ripgrep)
```
</details>

**Comment by hlissner** [comment]
Now that #1619 has been merged, I'll consider this issue resolved. If that isn't the case let me know and I will reopen the issue. Thanks for bringing this to my attention, and thanks to @filalex77 for resolving it!
