### ISSUE TITLE
[BUG] doom doc reports libvterm missing even though it exists

### ISSUE THREAD

**Issue by agraul** [hlissner/doom-emacs#1629]
**Describe the issue**
`doom doctor` reports that it can't find libvterm, but libvterm is installed and vterm can be used in Emacs.

Output of `doom doctor`:
```
Checking your enabled modules...
    (:term vterm) Couldn't find libvterm. Vterm module won't compile
```

I expect `doom doc` to report the presence of libvterm correctly. I've looked at `term/vterm/doctor.el` and saw that it checks for the presence of `vterm-ctrl`.

On my system, which is openSUSE Tumbleweed (Snapshot 20190730), `vterm-ctrl` is available in a package called `libvterm-tools` while the library itself is in `libvterm-devel`. I guess that only the latter is required as I was able to use vterm in emacs without any obvious issues. After I installed `libvterm-tools`, `doom doctor` did not complain anymore, but I did not spot a different within emacs.

**System information**
<details><pre>
((emacs
  (version . "26.2")
  (features . "XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD")
  (build . "Aug 02, 2019")
  (buildopts "--disable-build-details --without-pop --with-mailutils --without-hesiod --with-gameuser=:games --with-kerberos --with-kerberos5 --with-file-notification=inotify --with-modules --enable-autodepend --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --datadir=/usr/share --localstatedir=/var --sharedstatedir=/var/lib --libexecdir=/usr/lib --enable-locallisppath=/usr/share/emacs/26.2/site-lisp:/usr/share/emacs/site-lisp --with-x --with-xim --with-sound --with-xpm --with-jpeg --with-tiff --with-gif --with-png --with-rsvg --with-dbus --with-xft --without-gpm --with-x-toolkit=gtk3 --with-toolkit-scroll-bars --x-includes=/usr/include --x-libraries=/usr/lib64 --with-libotf --with-m17n-flt --with-xwidgets --build=x86_64-suse-linux 'CFLAGS=-O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -flto=3 -g -D_GNU_SOURCE -DGDK_DISABLE_DEPRECATION_WARNINGS -DGLIB_DISABLE_DEPRECATION_WARNINGS -pipe -Wno-pointer-sign -Wno-unused-variable -Wno-unused-label -fno-optimize-sibling-calls -fno-PIE -DSYSTEM_PURESIZE_EXTRA=55000    -DSITELOAD_PURESIZE_EXTRA=10000 ' LDFLAGS=-Wl,-O2"))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> straight, origin/straight 40eb9cf1 2019-07-29 21:23:51 +0200"))
 (system
  (type . gnu/linux)
  (config . "x86_64-suse-linux-gnu")
  (shell . "/usr/bin/zsh")
  (uname . "Linux 5.2.3-1-default #1 SMP Fri Jul 26 08:52:13 UTC 2019 (f5296b5) x86_64")
  (path "~/.rbenv/shims" "~/bin" "~/.cargo/bin" "~/.yarn/bin" "~/.rbenv/bin" "~/.cabal/bin/" "~/.emacs.d/bin/" "~/.local/bin" "/usr/local/bin" "/usr/local/sbin" "/usr/bin" "/usr/sbin" "/bin" "/sbin" "~/.fzf/bin" "/usr/lib/emacs/26.2/x86_64-suse-linux"))
 (config
  (envfile)
  (elc-files . 32)
  (modules :completion company (ivy +icons +fuzzy) :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor evil file-templates fold multiple-cursors rotate-text snippets :emacs dired electric vc :term vterm :tools editorconfig eval flycheck flyspell (lookup +docsets) lsp magit :lang data emacs-lisp (haskell +intero) (javascript +lsp) latex markdown (org +attach +babel +capture +export +habit +present +protocol) perl plantuml (python +lsp) rest (ruby +rbenv) (rust +lsp) sh web :config literate (default +bindings +smartparens))
  (packages "dockerfile-mode" "salt-mode")))
</pre></details>

```
$ rpm -ql libvterm-tools
/usr/bin/unterm
/usr/bin/vterm-ctrl
/usr/bin/vterm-dump

$ rpm -ql libvterm-devel
/usr/include/vterm.h
/usr/include/vterm_keycodes.h
/usr/lib64/libvterm.so
/usr/lib64/pkgconfig/vterm.pc
```

**Comment by akermu** [comment]
`libvterm` is build during the build process of `emacs-libvterm`, so it doesn't have to be installed on the system.

**Comment by alexandergraul** [comment]
> `libvterm` is build during the build process of `emacs-libvterm`, so it doesn't have to be installed on the system.

Are you saying this `doom doctor` check is wrong and there are no checks needed if  `libvterm` is installed since launching `vterm` takes care of it anyway?

**Comment by filalex77** [comment]
@alexandergraul `libvterm` is built when you launch `vterm` for the first time. `doom doc` doesn't know about that, and it seems to be designed to find *possible* wrong-doings, not all of them being true. If you know that it is wrong - please ignore the warnings for now, after asserting everything works the way you want.

**Comment by alexandergraul** [comment]
> `doom doc `doesn't know about that, and it seems to be designed to find *possible* wrong-doings, not all of them being true.

What I am trying to get at is that checking if `vterm-ctrl` exists is not a useful check for `doom doc` (unless it enables some extra features that I have not come across yet). The report is misleading, since libvterm **does** compile even if `vterm-ctrl` is missing. Looking at https://github.com/akermu/emacs-libvterm/blob/master/CMakeLists.txt#L36 it seems that these headers are used: https://github.com/neovim/libvterm/tree/master/include - and they do not depend on `vterm-ctrl`. Therefore I think this check can be removed from `doom doc`.

> If you know that it is wrong - please ignore the warnings for now, after asserting everything works the way you want.

Sorry, but I think this is the wrong approach. I think `doom doctor` should be fixed instead of telling its users to ignore warnings - once you go into that direction you can't expect anyone to trust it for *any output*.

**Comment by filalex77** [comment]
Your points are valid and well-researched, and this I can agree upon. Feel free to submit a PR with the proposed change for @hlissner to review it when possible.

**Comment by hlissner** [comment]
@alexandergraul I agree that the doctor should be fixed. The check was a naive heuristic I came up with while unaware that `vterm-ctrl` was a soft dependency. I would greatly appreciate a PR if you can think of a better check. I'm afraid I'm not familiar enough with libvterm enough to offer a solution (and haven't figured out how to properly install it after switching to NixOS, for that matter).

**Comment by hlissner** [comment]
Sorry for the late response. The vterm-ctrl check was removed in 6cd601cf0f42, so I'll consider this resolved.
