### ISSUE TITLE
[HOWTO] Add a flycheck linter to LaTeX

### ISSUE THREAD

**Issue by fabio-oesch** [hlissner/doom-emacs#1635]
I want to add a custom [flycheck-textlint](https://github.com/kisaragi-hiu/flycheck-textlint) when working with LaTeX documents.

After creating a file in `~/.config/textlint/textlintrc.json` I added the following code to my `config.el` file:
```elisp
(setq flycheck-textlint-config "~/.config/textlint/textlintrc.json")
```
This worked as expected and the extra linter could be used when writing in markdown and text files. But I was trying to make it work with LaTeX and so I added, as suggested in the above link, the line:
```elisp
(add-to-list 'flycheck-textlint-plugin-alist '(tex-mode . "latex")))
```
Error: <details><pre>
Debugger entered--Lisp error: (void-variable flycheck-textlint-plugin-alist)
  (member (quote (tex-mode . "latex")) flycheck-textlint-plugin-alist)
  (if (member (quote (tex-mode . "latex")) flycheck-textlint-plugin-alist) flycheck-textlint-plugin-alist (setq flycheck-textlint-plugin-alist (cons (quote (tex-mode . "latex")) flycheck-textlint-plugin-alist)))
  eval-buffer(#<buffer  *load*-390762> nil "/home/olearry/.doom.d/config.el" nil t)  ; Reading at buffer position 567
  load-with-code-conversion("/home/olearry/.doom.d/config.el" "/home/olearry/.doom.d/config.el" t nil)
  load("/home/olearry/.doom.d/config" t nil)
  (condition-case e (load (expand-file-name "config" doom-private-dir) t nil) ((debug doom-error) (signal (car e) (cdr e))) ((debug error) (let* ((source (file-name-sans-extension (expand-file-name "config" doom-private-dir))) (err (cond ((file-in-directory-p source doom-core-dir) (cons ... doom-core-dir)) ((file-in-directory-p source doom-private-dir) (cons ... doom-private-dir)) ((cons ... doom-emacs-dir))))) (signal (car err) (list (file-relative-name (concat source ".el") (cdr err)) e)))))
  (if noninteractive nil (maphash (function (lambda (key plist) (let ((doom--current-module key) (doom--current-flags (plist-get plist :flags))) (condition-case e (load (expand-file-name "config" ...) t nil) ((debug doom-error) (signal ... ...)) ((debug error) (let* ... ...)))))) doom-modules) (run-hook-wrapped (quote doom-init-modules-hook) (function doom-try-run-hook)) (condition-case e (load (expand-file-name "config" doom-private-dir) t nil) ((debug doom-error) (signal (car e) (cdr e))) ((debug error) (let* ((source (file-name-sans-extension (expand-file-name "config" doom-private-dir))) (err (cond (... ...) (... ...) (...)))) (signal (car err) (list (file-relative-name (concat source ".el") (cdr err)) e))))) (if custom-file nil (setq custom-file (concat doom-local-dir "custom.el"))) (if (stringp custom-file) (progn (load custom-file t t t))))
  (progn (setq doom-init-modules-p t) (maphash (function (lambda (key plist) (let ((doom--current-module key) (doom--current-flags (plist-get plist :flags))) (condition-case e (load (expand-file-name "init" ...) t nil) ((debug doom-error) (signal ... ...)) ((debug error) (let* ... ...)))))) doom-modules) (run-hook-wrapped (quote doom-before-init-modules-hook) (function doom-try-run-hook)) (if noninteractive nil (maphash (function (lambda (key plist) (let ((doom--current-module key) (doom--current-flags ...)) (condition-case e (load ... t nil) (... ...) (... ...))))) doom-modules) (run-hook-wrapped (quote doom-init-modules-hook) (function doom-try-run-hook)) (condition-case e (load (expand-file-name "config" doom-private-dir) t nil) ((debug doom-error) (signal (car e) (cdr e))) ((debug error) (let* ((source (file-name-sans-extension ...)) (err (cond ... ... ...))) (signal (car err) (list (file-relative-name ... ...) e))))) (if custom-file nil (setq custom-file (concat doom-local-dir "custom.el"))) (if (stringp custom-file) (progn (load custom-file t t t)))))
  (if (and (or force-p (not doom-init-modules-p)) (not (setq doom-modules nil)) (condition-case e (load (expand-file-name "init" doom-private-dir) t nil) ((debug doom-error) (signal (car e) (cdr e))) ((debug error) (let* ((source (file-name-sans-extension ...)) (err (cond ... ... ...))) (signal (car err) (list (file-relative-name ... ...) e)))))) (progn (setq doom-init-modules-p t) (maphash (function (lambda (key plist) (let ((doom--current-module key) (doom--current-flags ...)) (condition-case e (load ... t nil) (... ...) (... ...))))) doom-modules) (run-hook-wrapped (quote doom-before-init-modules-hook) (function doom-try-run-hook)) (if noninteractive nil (maphash (function (lambda (key plist) (let (... ...) (condition-case e ... ... ...)))) doom-modules) (run-hook-wrapped (quote doom-init-modules-hook) (function doom-try-run-hook)) (condition-case e (load (expand-file-name "config" doom-private-dir) t nil) ((debug doom-error) (signal (car e) (cdr e))) ((debug error) (let* ((source ...) (err ...)) (signal (car err) (list ... e))))) (if custom-file nil (setq custom-file (concat doom-local-dir "custom.el"))) (if (stringp custom-file) (progn (load custom-file t t t))))))
  doom-initialize-modules()
  (if noninteractive nil (doom-initialize-modules))
  eval-buffer(#<buffer  *load*-319551> nil "/home/olearry/.emacs.d/core/core.el" nil t)  ; Reading at buffer position 21286
  load-with-code-conversion("/home/olearry/.emacs.d/core/core.el" "/home/olearry/.emacs.d/core/core.el" nil t)
  require(core "/home/olearry/.emacs.d/core/core")
  eval-buffer(#<buffer  *load*> nil "/home/olearry/.emacs.d/init.el" nil t)  ; Reading at buffer position 4798
  load-with-code-conversion("/home/olearry/.emacs.d/init.el" "/home/olearry/.emacs.d/init.el" t t)
  load("/home/olearry/.emacs.d/init" t t)
  #f(compiled-function () #<bytecode 0x1e4371>)()
  command-line()
  normal-top-level()
</pre></details>
But when I restart doom it will tell me that the variable is void. Which I believe means that flycheck wasn't initiated at that time. So I tried to use the `def-package!` command to configure the flycheck. But I am not entirely certain which package I should hook into because it seems there are a lot of options.

The final code looked something like this:
```elisp
;;; in config.el
(def-package! flycheck-mode
  :config
  (setq flycheck-textlint-config "~/.config/textlint/textlintrc.json")
  (add-to-list 'flycheck-textlint-plugin-alist '(tex-mode . "latex")))
```
Error:<details><pre>
Debugger entered--Lisp error: (file-missing "Cannot open load file" "No such file or directory" "flycheck-mode")
  require(flycheck-mode nil nil)
  eval-buffer(#<buffer  *load*-14002> nil "/home/olearry/.doom.d/config.el" nil t)  ; Reading at buffer position 608
  load-with-code-conversion("/home/olearry/.doom.d/config.el" "/home/olearry/.doom.d/config.el" t nil)
  load("/home/olearry/.doom.d/config" t nil)
  (condition-case e (load (expand-file-name "config" doom-private-dir) t nil) ((debug doom-error) (signal (car e) (cdr e))) ((debug error) (let* ((source (file-name-sans-extension (expand-file-name "config" doom-private-dir))) (err (cond ((file-in-directory-p source doom-core-dir) (cons ... doom-core-dir)) ((file-in-directory-p source doom-private-dir) (cons ... doom-private-dir)) ((cons ... doom-emacs-dir))))) (signal (car err) (list (file-relative-name (concat source ".el") (cdr err)) e)))))
  (if noninteractive nil (maphash (function (lambda (key plist) (let ((doom--current-module key) (doom--current-flags (plist-get plist :flags))) (condition-case e (load (expand-file-name "config" ...) t nil) ((debug doom-error) (signal ... ...)) ((debug error) (let* ... ...)))))) doom-modules) (run-hook-wrapped (quote doom-init-modules-hook) (function doom-try-run-hook)) (condition-case e (load (expand-file-name "config" doom-private-dir) t nil) ((debug doom-error) (signal (car e) (cdr e))) ((debug error) (let* ((source (file-name-sans-extension (expand-file-name "config" doom-private-dir))) (err (cond (... ...) (... ...) (...)))) (signal (car err) (list (file-relative-name (concat source ".el") (cdr err)) e))))) (if custom-file nil (setq custom-file (concat doom-local-dir "custom.el"))) (if (stringp custom-file) (progn (load custom-file t t t))))
  (progn (setq doom-init-modules-p t) (maphash (function (lambda (key plist) (let ((doom--current-module key) (doom--current-flags (plist-get plist :flags))) (condition-case e (load (expand-file-name "init" ...) t nil) ((debug doom-error) (signal ... ...)) ((debug error) (let* ... ...)))))) doom-modules) (run-hook-wrapped (quote doom-before-init-modules-hook) (function doom-try-run-hook)) (if noninteractive nil (maphash (function (lambda (key plist) (let ((doom--current-module key) (doom--current-flags ...)) (condition-case e (load ... t nil) (... ...) (... ...))))) doom-modules) (run-hook-wrapped (quote doom-init-modules-hook) (function doom-try-run-hook)) (condition-case e (load (expand-file-name "config" doom-private-dir) t nil) ((debug doom-error) (signal (car e) (cdr e))) ((debug error) (let* ((source (file-name-sans-extension ...)) (err (cond ... ... ...))) (signal (car err) (list (file-relative-name ... ...) e))))) (if custom-file nil (setq custom-file (concat doom-local-dir "custom.el"))) (if (stringp custom-file) (progn (load custom-file t t t)))))
  (if (and (or force-p (not doom-init-modules-p)) (not (setq doom-modules nil)) (condition-case e (load (expand-file-name "init" doom-private-dir) t nil) ((debug doom-error) (signal (car e) (cdr e))) ((debug error) (let* ((source (file-name-sans-extension ...)) (err (cond ... ... ...))) (signal (car err) (list (file-relative-name ... ...) e)))))) (progn (setq doom-init-modules-p t) (maphash (function (lambda (key plist) (let ((doom--current-module key) (doom--current-flags ...)) (condition-case e (load ... t nil) (... ...) (... ...))))) doom-modules) (run-hook-wrapped (quote doom-before-init-modules-hook) (function doom-try-run-hook)) (if noninteractive nil (maphash (function (lambda (key plist) (let (... ...) (condition-case e ... ... ...)))) doom-modules) (run-hook-wrapped (quote doom-init-modules-hook) (function doom-try-run-hook)) (condition-case e (load (expand-file-name "config" doom-private-dir) t nil) ((debug doom-error) (signal (car e) (cdr e))) ((debug error) (let* ((source ...) (err ...)) (signal (car err) (list ... e))))) (if custom-file nil (setq custom-file (concat doom-local-dir "custom.el"))) (if (stringp custom-file) (progn (load custom-file t t t))))))
  doom-initialize-modules()
  (if noninteractive nil (doom-initialize-modules))
  eval-buffer(#<buffer  *load*-770168> nil "/home/olearry/.emacs.d/core/core.el" nil t)  ; Reading at buffer position 21286
  load-with-code-conversion("/home/olearry/.emacs.d/core/core.el" "/home/olearry/.emacs.d/core/core.el" nil t)
  require(core "/home/olearry/.emacs.d/core/core")
  eval-buffer(#<buffer  *load*> nil "/home/olearry/.emacs.d/init.el" nil t)  ; Reading at buffer position 4798
  load-with-code-conversion("/home/olearry/.emacs.d/init.el" "/home/olearry/.emacs.d/init.el" t t)
  load("/home/olearry/.emacs.d/init" t t)
  #f(compiled-function () #<bytecode 0x1e4371>)()
  command-line()
  normal-top-level()
</pre></details>
But it tells me now that the file is missing (the same error happens when I put `(setq ...)` outside of the `def-package!` block. I am certain I am making an easy mistake somewhere and I would appreciate some help.

**System information**
<details><pre>
- OS: gnu/linux (x86_64-redhat-linux-gnu)
- Emacs: 26.2 (Apr 30, 2019)
- Doom: 2.0.9 (HEAD -> develop, origin/develop, origin/HEAD 32e266cf 2019-05-31 22:01:10 -0400)
- Graphic display: t (daemon: nil)
- System features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LCMS2
- Details:
  ```elisp
  env bootstrapper: envvar-file
  elc count: 0
  uname -a:  Linux 5.1.20-300.fc30.x86_64 #1 SMP Fri Jul 26 15:03:11 UTC 2019 x86_64
  modules:   (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor evil file-templates fold multiple-cursors rotate-text snippets :emacs dired electric vc :tools eval flycheck (lookup +docsets) magit :lang data emacs-lisp markdown (org +attach +babel +capture +export +habit +present +protocol) sh :config default)
  packages:  n/a
  exec-path: (/usr/share/Modules/bin /usr/local/bin /usr/local/sbin /usr/bin /usr/sbin /usr/libexec/emacs/26.2/x86_64-redhat-linux-gnu/)
  ```
</pre></details>

**Comment by filalex77** [comment]
Here's how I would do it:

*.doom.d/packages.el*
```emacs-lisp
(package! flycheck-textlint)
```
*.doom.d/config.el*
```emacs-lisp
(def-package! flycheck-textlint
  :after (flycheck latex)
  :config
  (setq flycheck-textlint-config "~/.config/textlint/textlintrc.json")
  (add-to-list 'flycheck-textlint-plugin-alist '(tex-mode . "latex")))
```

An explanation of above setup will be provided shortly.
This is untested and hypothetical for now; if this doesn't work out, I can check on a real `textlint` installation.

**Comment by fabio-oesch** [comment]
This seems to work for the most part but now it has issues finding my rules. Since it cannot find them either in a txt files anymore either. So if I take it out of the `(setq ...)` part it works again for text files but the latex part still does not work correctly. It doesn't give me an error message either. I tried updating doom and its packages as well. The rule itself shouldn't be wrong since it works when I take `(setq ...)` out of the config part. I'm not sure at this point if it's a problem with the config or with the linter.

**Comment by filalex77** [comment]
Okay, let me try to wrap my head around this.

How I understand this currently: if `setq` is *outside* the `def-package! :config` block, it works, but only if you load `flycheck-textlint` by yourself later on, and doesn't work if it's in the `def-package! :config`.

Try separating the concerns further with an `after!` block (basically the same as the built-in `with-eval-after-load`):

*.doom.d/config.el*
```emacs-lisp
(after! flycheck-textlint
  (setq flycheck-textlint-config "~/.config/textlint/textlintrc.json")
  (add-to-list 'flycheck-textlint-plugin-alist '(tex-mode . "latex"))
```

If this doesn't work, please wait for a bit: the Elisp-fu guru @hlissner is currently unavailable. I'll try to work out more possible solutions in the meantime.

**Comment by fabio-oesch** [comment]
@filalex77 thank you for all your help. I really appreciate it. So what I was trying to say is that if I have it like this:
```elisp
(setq flycheck-textlint-config "~/.config/textlint/textlintrc.json")
(def-package! flycheck-textlint
  :after (flycheck latex)
  :config
  (add-to-list 'flycheck-textlint-plugin-alist '(tex-mode . "latex")))
```
then it works like it worked before and the linter works for txt files and md files. But it still doesn't do anything for latex. But now it does not give me any errors.
If I have it like this:
```elisp
(def-package! flycheck-textlint
  :after (flycheck latex)
  :config
  (setq flycheck-textlint-config "~/.config/textlint/textlintrc.json")
  (add-to-list 'flycheck-textlint-plugin-alist '(tex-mode . "latex")))
```
then it will tell me that a suspicious state is being found and returns with exit code 1 but no errors were being found. It then tells me that no rules were found. I just checked the variable `flycheck-textlint-config` which gave me the value `textlintrc.json`. Should this not be a path to the file? As in `~/.config/textlint/textlintrc.json`?

**Comment by filalex77** [comment]
Did you, by chance, install `textlint-plugin-latex` (as per [documentation for `textlint`](https://github.com/textlint/textlint/blob/master/docs/plugin.md))? That needs to be accessible by Emacs.

**Comment by hlissner** [comment]
@fabio-oesch As a side-note: this small correction to your `def-package!` block might help the incorrect value for `flycheck-textlint-config` (and ensure it is set anywhere flycheck-textlint is used).

```elisp
(def-package! flycheck-textlint
  :after flycheck
  :init (setq flycheck-textlint-config "~/.config/textlint/textlintrc.json")
  :config (add-to-list 'flycheck-textlint-plugin-alist '(tex-mode . "latex")))
```

**Comment by fabio-oesch** [comment]
Sorry for not responding for ages. I've just tried how you told me @hlissner. You're correct that the error message disappears and it seems that the variable `flycheck-textlint-config` is set correctly. But it still does not seem to use the linter though. It does work though with txt files again. I do not know now why it doesn't show the error correctly.
