### ISSUE TITLE
[BUG] make doctor report: (:lang common-lisp) Couldn't find your `inferior-lisp-program' (lisp).

### ISSUE THREAD

**Issue by flyingns** [hlissner/doom-emacs#1636]
I have set or not set:
`(after! lisp (setq inferior-lisp-program "/usr/local/bin/sbcl"))`

When I run `make doctor` it will report:
`(:lang common-lisp) Couldn't find your 'inferior-lisp-program' (lisp). Is it installed?`

Both the develop and straight branches are like this. Is this a bug?

**Comment by filalex77** [comment]
Try `after! lisp-mode` instead.

**Comment by flyingns** [comment]
I set the `set after! lisp-mode`, the development branch has no errors, and the straight branch still reports an error.

**Comment by hlissner** [comment]
As of fde4d11 this should be resolved. Let me know if that isn't the case and I will reopen the issue. Thanks for bringing it to my attention!
