### ISSUE TITLE
[BUG] M-x +plantuml/install Certificate validation failed

### ISSUE THREAD

**Issue by flyingns** [hlissner/doom-emacs#1637]
The develop branch was previously installed, no problem.

When switching to the straight branch, M-x +plantuml/install, it is reported:

`Contacting host: kent.dl.sourceforge.net:443`

`gnutls-negotiate: Certificate validation failed kent.dl.sourceforge.net, verification code 402`

**Comment by hlissner** [comment]
#1639 was merged, which should resolve this issue. Let me know if that isn't the case and I will reopen this issue. Thanks for bringing it to my attention!
