### ISSUE TITLE
[BUG] +evil `SPC w c` hardcoded to #'+workspace/close-window-or-workspace

### ISSUE THREAD

**Issue by alexandergraul** [hlissner/doom-emacs#1640]
**Describe the issue**
Disabling `:ui workspaces` breaks `SPC w c` and `C-w c` (using evil keybindings).

The problem is in https://github.com/hlissner/doom-emacs/blob/develop/modules/config/default/%2Bevil-bindings.el#L143:
```lisp
(:map evil-window-map
  "c" #'+workspace/close-window-or-workspace)
```

I expect this binding to use `evil-window-delete` by default.I guess the current binding should be in the  `featurep! :ui workspaces` further down in the file.

If no one minds I'll send a PR with theses changes.

**Comment by hlissner** [comment]
Now that #1641 is merged, I'll consider this resolved. Thanks for bringing it to my attention and again for fixing it!
