### ISSUE TITLE
[HOWTO] use map! properly to remap key

### ISSUE THREAD

**Issue by vakker** [hlissner/doom-emacs#1643]
**What I want to achieve**
I'm trying to map some `avy` commands to keys that are being used like:
```
(map!
 [C-f] #'avy-goto-char
 [C-s] #'avy-goto-char-2
 [C-d] #'avy-goto-line
 )
```

But `<C-f>` is mapped by default to `evil-scroll-page-down` and if I do a `SPC h k C-f` then it tells me that it is mapped to `evil-scroll-page-down`.
However if I do a `SPC h w avy-goto-char` the it tells me: `avy-goto-char is remapped to evil-avy-goto-char which is on <C-f>` so it's a bit confusing. 

I also tried setting them to `nil` first, but that didn't help either. I think I'm doing something wrong, but then I could map other stuff successfully, like:
```
(map!
 [C-next]  #'next-buffer
 [C-prior] #'previous-buffer
 )
```

**System information**
```
Generating Doom info...
- OS: gnu/linux (x86_64-pc-linux-gnu)
- Shell: /usr/bin/zsh
- Emacs: 26.2 (Apr 12, 2019)
- Doom: 2.0.9 (HEAD -> develop, origin/develop, origin/HEAD f754d4ff 2019-07-23 18:23:17 +0200)
- Graphic display: nil (daemon: nil)
- System features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD LCMS2
- Details:
  ```elisp
  env bootstrapper: nil
  elc count: 0
  uname -a:  Linux 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64
  modules:   (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor evil file-templates fold multiple-cursors rotate-text snippets :emacs dired electric vc :tools eval flycheck (lookup +docsets) magit :lang data emacs-lisp markdown (org +dragndrop +ipython +pandoc +present) python sh :config default)
  packages:  ((smartparens :recipe (smartparens :fetcher github :repo Fuco1/smartparens)) ag highlight-indent-guides yapfify py-isort avy)
  exec-path: (~/.emacs.d/bin ~/.local/bin ~/bin ~/.local/bin ~/bin ~/miniconda3/bin ~/miniconda3/condabin ~/.local/bin ~/bin /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /usr/games /usr/local/games /snap/bin /usr/local/go/bin ~/go/bin /usr/local/go/bin ~/go/bin /usr/local/go/bin ~/go/bin /usr/lib/x86_64-linux-gnu/emacs/26.2/x86_64-linux-gnu)
  ```
```

**Comment by hlissner** [comment]
Try the following instead:

```elisp
(map!
 "C-f" #'avy-goto-char
 "C-s" #'avy-goto-char-2
 "C-d" #'avy-goto-line
 )
```

Emacs is picky about the format of vectored key sequences (e.g. `[C-f]`, `[C-s]`, `[C-d]`). The correct format would've been `[?\C-f]`, `[?\C-s]`, etc because `C-f` is not a special or named input event, unlike `next` and `prior`.

**Comment by vakker** [comment]
Thanks, I changed it, but now it still says that `C-f` bound to `evil-scroll-page-down`, however for `where-is avy-goto-char` not it says: `avy-goto-char is not on any key`

**Comment by hlissner** [comment]
Ah, that is because of evil-mode; it uses both `C-f` and `C-d` in normal and visual modes (which have higher precedence than the "global" keymap). You'll need to rebind them on the normal/visual mode keymaps instead:

```elisp
(map!
 :nv "C-f" #'avy-goto-char
 :nv "C-s" #'avy-goto-char-2
 :nv "C-d" #'avy-goto-line
 )
```

I did it for `C-s` for consistency; it wasn't strictly.

As a side note, the functionality of avy-goto-char, avy-goto-char-2 and avy-goto-line are already available on the `gsf`, `gss`, and `gsj`/`gsk` keys, respectively.

**Comment by vakker** [comment]
Yep, that works, thanks. Tbh, it wasn't entirely clear to me how `:nv` (and similar) work.
Also, thanks for pointing out the `evil-easymotion` bindings, I was only looking for `avy` stuff so I completely overlooked them.

**Comment by hlissner** [comment]
> Tbh, it wasn't entirely clear to me how :nv (and similar) work.

That's totally understandable. It seems to be a common hurdle; something I'll need to document better. You can find what other states `map!` supports in its documentation, accessed with `SPC h f map!`. I should mention, the order of the states in the keyword doesn't matter. `:nv` and `:vn` are both recognized.

> Also, thanks for pointing out the evil-easymotion bindings

Happy to help! In case you're looking for more, you'll find many avy-ified evil motions on the `gs` prefix, e.g. `gsw`, `gsa` (jump to an argument in a comma-delimited argument list), and (a community favorite) `g s SPC`, which invokes `avy-goto-char-timer` across all open windows. There's also `gs/` for `avy-goto-char-timer` restricted to the current window.
