### ISSUE TITLE
[HOWTO] put ag search result in a new buffer

### ISSUE THREAD

**Issue by AlexXiong97** [hlissner/doom-emacs#1650]
**What I want to achieve**
I use `ivy/ag` to search in project files, but don't know how to put all search result into a new buffer so that I could return to it conveniently and iterate through all links without having to type out the search regex everytime?

**Comment by ckruse** [comment]
I have the same question for `helm/rg` ;-)

**Comment by Emantor** [comment]
For `ivy/ag` you should be able to use `C-c C-o` to open an occur buffer and save this.
