### ISSUE TITLE
[BUG] doom update error ... (straight branch)

### ISSUE THREAD

**Issue by flyingns** [hlissner/doom-emacs#1653]
**Describe the issue**
When I `doom update`, it reported the following error:

<details><pre>
Output:
/dev/null

--------------------------------------------------

There was an unexpected error:
  Wrong type argument (wrong-type-argument)
Wrong type argument: listp, "Wrong type argument: characterp, :type"
</pre></details>

Then I `doom -d update`, get the following information:

<details><pre>
Loading /Users/mls/.emacs.d/core/cli/install.el (source)...
Loading /Users/mls/.emacs.d/core/cli/debug.el (source)...
Loading /Users/mls/.emacs.d/core/autoload/debug.el (source)...
Loading /Users/mls/.emacs.d/core/cli/test.el (source)...
Loading /Users/mls/.emacs.d/core/cli/env.el (source)...
Loading /Users/mls/.emacs.d/core/cli/upgrade.el (source)...
Loading /Users/mls/.emacs.d/core/cli/packages.el (source)...
Loading /Users/mls/.emacs.d/core/cli/autoloads.el (source)...
Loading /Users/mls/.emacs.d/core/cli/patch-macos.el (source)...
Loading /Users/mls/.emacs.d/core/cli/byte-compile.el (source)...
DOOM Initializing
DOOM Initializing doom-packages
Loading /Users/mls/.doom.d/init.el (source)...
DOOM Ignoring built-in package so-long
DOOM Ignoring built-in package vc
DOOM Ignoring built-in package vc-annotate
DOOM Ignoring built-in package smerge-mode
DOOM Ignoring built-in package elisp-mode
DOOM Ignoring built-in package vterm
WARNING: The :fetcher property was used for the taskpaper-mode package.
This property is deprecated. Replace it with :host.
WARNING: The :fetcher property was used for the emacs-guess-word-game package.
This property is deprecated. Replace it with :host.
WARNING: The :fetcher property was used for the org-super-agenda package.
This property is deprecated. Replace it with :host.
Loading /Users/mls/.doom.d/init.el (source)...
Loading /Users/mls/.doom.d/modules/private/myorg/init.el (source)...
Loading /Users/mls/.doom.d/modules/private/misc/init.el (source)...
> Checking core autoloads file
  ✓ Skipping core autoloads, they are up-to-date
> Scanning for outdated packages (this may take a while)...
  . 0%
  .
  .
  .
  .
  .
  .
  .
  .
  .
  .
  .
  .
  .
  .
  .
  .
  .
  .
  .
  .
  .

Debugger entered--Lisp error: (wrong-type-argument characterp :type)
  mapconcat(identity ((:type git :host github :repo "melpa/melpa" :no-build t :package "melpa" :local-repo "melpa") (:type git :host github :repo "emacs/gnu-elpa-mirror" :no-build t :package "gnu-elpa-mirror" :local-repo "gnu-elpa-mirror") (:type git :host github :repo "emacs/emacsmirror-mirror" :no-build t :package "emacsmirror-mirror" :local-repo "emacsmirror-mirror") (:type git :host github :repo "raxod502.el" :files (*.el") :branch "master" :package " :local-repo .el") (:flavor melpa :files ("bind-key.el" "bind-key-pkg.el") :package "bind-key" :local-repo "use-package" :type git :repo "jwiegley/use-package" :host github) (:type git :flavor melpa :host github :repo "jwiegley/emacs-async" :package "async" :local-repo "emacs-async") (:type git :flavor melpa :host github :repo "preetpalS/emacs-dotenv-mode" :package "dotenv-mode" :local-repo "emacs-dotenv-mode") (:type git :flavor melpa :host github :repo "joewreschnig/auto-minor-mode" :package "auto-minor-mode" :local-repo "auto-minor-mode") (:type git :flavor melpa :files (:defaults "data" "all-the-icons-pkg.el") :host github :repo "domtronn/all-the-icons.el" :package "all-the-icons" :local-repo "all-the-icons.el") (:type git :flavor melpa :host github :repo "hlissner/emacs-hide-mode-line" :package "hide-mode-line" :local-repo "emacs-hide-mode-line") (:type git :flavor melpa :host github :repo "Fanael/highlight-numbers" :package "highlight-numbers" :local-repo "highlight-numbers") (:type git :flavor melpa :host github :repo "Fanael/rainbow-delimiters" :package "rainbow-delimiters" :local-repo "rainbow-delimiters") (:type git :flavor melpa :host github :repo "iqbalansari/restart-emacs" :package "restart-emacs" :local-repo "restart-emacs") (:type git :flavor melpa :host github :repo "gilbertw1/better-jumper" :package "better-jumper" :local-repo "better-jumper") (:type git :flavor melpa :host github :repo "lewang/command-log-mode" :package "command-log-mode" :local-repo "command-log-mode") (:type git :flavor melpa :host github :repo "jscheid/dtrt-indent" :package "dtrt-indent" :local-repo "dtrt-indent") (:type git :flavor melpa :host github :repo "Wilfred/helpful" :package "helpful" :local-repo "helpful") (:type git :flavor melpa :host github :repo "purcell/ns-auto-titlebar" :package "ns-auto-titlebar" :local-repo "ns-auto-titlebar") (:type git :flavor melpa :files ("pcre2el.el" "pcre2el-pkg.el") :host github :repo "joddie/pcre2el" :package "pcre2el" :local-repo "pcre2el") (:type git :flavor melpa :host github :repo "Fuco1/smartparens" :package "smartparens" :local-repo "smartparens") (:repo "https://git.savannah.gnu.org/git/so-long.git" :package "so-long" :type git :local-repo "so-long") (:type git :flavor melpa :host github :repo "joddie/osx-clipboard-mode" :package "osx-clipboard" :local-repo "osx-clipboard-mode") (:type git :host github :repo "emacs/undo-tree" :package "undo-tree" :local-repo "undo-tree") (:type git :flavor melpa :host github :repo "lewang/ws-butler" :package "ws-butler" :local-repo "ws-butler") (:type git :host github :repo "emacs/xclip" :package "xclip" :local-repo "xclip") (:type git :flavor melpa :files ("projectile.el" "projectile-pkg.el") :host github :repo "bbatsov/projectile" :package "projectile" :local-repo "projectile") (:type git :flavor melpa :host github :repo "noctuid/general.el" :package "general" :local-repo "general.el") (:type git :flavor melpa :host github :repo "justbur/emacs-which-key" :package "which-key" :local-repo "emacs-which-key") (:type git :flavor melpa :host github :repo "jschaf/esup" :package "esup" :local-repo "esup") (:type git :flavor melpa :host github :repo "emacs-jp/migemo" :package "migemo" :local-repo "migemo") (:type git :flavor melpa :host github :repo "momomo5717/avy-migemo" :package "avy-migemo" :local-repo "avy-migemo") (:flavor melpa :files ("cdb.el" "cdb-pkg.el") :package "cdb" :local-repo "ddskk" :type git :repo "skk-dev/ddskk" :host github) (:type git :flavor melpa :host github :repo "coldnew/pangu-spacing" :package "pangu-spacing" :local-repo "pangu-spacing") (:type git :flavor melpa :host github :repo "company-mode/company-mode" :package "company" :local-repo "company-mode") (:type git :flavor melpa :host github :repo "hlissner/emacs-company-dict" :package "company-dict" :local-repo "emacs-company-dict") (:flavor melpa :files ("prescient.el" "prescient-pkg.el") :package "prescient" :local-repo "prescient.el" :type git :repo "raxod502/prescient.el" :host github) (:type git :flavor melpa :files ("*.el" "emacs-helm.sh" (:exclude "helm.el" "helm-lib.el" "helm-source.el" "helm-multi-match.el" "helm-core-pkg.el") "helm-pkg.el") :host github :repo "emacs-helm/helm" :package "helm" :local-repo "helm") (:type git :flavor melpa :host github :repo "syohex/emacs-helm-ag" :package "helm-ag" :local-repo "emacs-helm-ag") (:type git :flavor melpa :host github :repo "emacs-jp/helm-c-yasnippet" :package "helm-c-yasnippet" :local-repo "helm-c-yasnippet") (:type git :flavor melpa :host github :repo "Sodel-the-Vociferous/helm-company" :package "helm-company" :local-repo "helm-company") (:type git :flavor melpa :host github :repo "emacs-helm/helm-describe-modes" :package "helm-describe-modes" :local-repo "helm-describe-modes") (:type git :flavor melpa :host github :repo "bbatsov/helm-projectile" :package "helm-projectile" :local-repo "helm-projectile")) ", ")
  string-join(((:type git :host github :repo "melpa/melpa" :no-build t :package "melpa" :local-repo "melpa") (:type git :host github :repo "emacs/gnu-elpa-mirror" :no-build t :package "gnu-elpa-mirror" :local-repo "gnu-elpa-mirror") (:type git :host github :repo "emacs/emacsmirror-mirror" :no-build t :package "emacsmirror-mirror" :local-repo "emacsmirror-mirror") (:type git :host github :repo "raxod502.el" :files (*.el") :branch "master" :package " :local-repo .el") (:flavor melpa :files ("bind-key.el" "bind-key-pkg.el") :package "bind-key" :local-repo "use-package" :type git :repo "jwiegley/use-package" :host github) (:type git :flavor melpa :host github :repo "jwiegley/emacs-async" :package "async" :local-repo "emacs-async") (:type git :flavor melpa :host github :repo "preetpalS/emacs-dotenv-mode" :package "dotenv-mode" :local-repo "emacs-dotenv-mode") (:type git :flavor melpa :host github :repo "joewreschnig/auto-minor-mode" :package "auto-minor-mode" :local-repo "auto-minor-mode") (:type git :flavor melpa :files (:defaults "data" "all-the-icons-pkg.el") :host github :repo "domtronn/all-the-icons.el" :package "all-the-icons" :local-repo "all-the-icons.el") (:type git :flavor melpa :host github :repo "hlissner/emacs-hide-mode-line" :package "hide-mode-line" :local-repo "emacs-hide-mode-line") (:type git :flavor melpa :host github :repo "Fanael/highlight-numbers" :package "highlight-numbers" :local-repo "highlight-numbers") (:type git :flavor melpa :host github :repo "Fanael/rainbow-delimiters" :package "rainbow-delimiters" :local-repo "rainbow-delimiters") (:type git :flavor melpa :host github :repo "iqbalansari/restart-emacs" :package "restart-emacs" :local-repo "restart-emacs") (:type git :flavor melpa :host github :repo "gilbertw1/better-jumper" :package "better-jumper" :local-repo "better-jumper") (:type git :flavor melpa :host github :repo "lewang/command-log-mode" :package "command-log-mode" :local-repo "command-log-mode") (:type git :flavor melpa :host github :repo "jscheid/dtrt-indent" :package "dtrt-indent" :local-repo "dtrt-indent") (:type git :flavor melpa :host github :repo "Wilfred/helpful" :package "helpful" :local-repo "helpful") (:type git :flavor melpa :host github :repo "purcell/ns-auto-titlebar" :package "ns-auto-titlebar" :local-repo "ns-auto-titlebar") (:type git :flavor melpa :files ("pcre2el.el" "pcre2el-pkg.el") :host github :repo "joddie/pcre2el" :package "pcre2el" :local-repo "pcre2el") (:type git :flavor melpa :host github :repo "Fuco1/smartparens" :package "smartparens" :local-repo "smartparens") (:repo "https://git.savannah.gnu.org/git/so-long.git" :package "so-long" :type git :local-repo "so-long") (:type git :flavor melpa :host github :repo "joddie/osx-clipboard-mode" :package "osx-clipboard" :local-repo "osx-clipboard-mode") (:type git :host github :repo "emacs/undo-tree" :package "undo-tree" :local-repo "undo-tree") (:type git :flavor melpa :host github :repo "lewang/ws-butler" :package "ws-butler" :local-repo "ws-butler") (:type git :host github :repo "emacs/xclip" :package "xclip" :local-repo "xclip") (:type git :flavor melpa :files ("projectile.el" "projectile-pkg.el") :host github :repo "bbatsov/projectile" :package "projectile" :local-repo "projectile") (:type git :flavor melpa :host github :repo "noctuid/general.el" :package "general" :local-repo "general.el") (:type git :flavor melpa :host github :repo "justbur/emacs-which-key" :package "which-key" :local-repo "emacs-which-key") (:type git :flavor melpa :host github :repo "jschaf/esup" :package "esup" :local-repo "esup") (:type git :flavor melpa :host github :repo "emacs-jp/migemo" :package "migemo" :local-repo "migemo") (:type git :flavor melpa :host github :repo "momomo5717/avy-migemo" :package "avy-migemo" :local-repo "avy-migemo") (:flavor melpa :files ("cdb.el" "cdb-pkg.el") :package "cdb" :local-repo "ddskk" :type git :repo "skk-dev/ddskk" :host github) (:type git :flavor melpa :host github :repo "coldnew/pangu-spacing" :package "pangu-spacing" :local-repo "pangu-spacing") (:type git :flavor melpa :host github :repo "company-mode/company-mode" :package "company" :local-repo "company-mode") (:type git :flavor melpa :host github :repo "hlissner/emacs-company-dict" :package "company-dict" :local-repo "emacs-company-dict") (:flavor melpa :files ("prescient.el" "prescient-pkg.el") :package "prescient" :local-repo "prescient.el" :type git :repo "raxod502/prescient.el" :host github) (:type git :flavor melpa :files ("*.el" "emacs-helm.sh" (:exclude "helm.el" "helm-lib.el" "helm-source.el" "helm-multi-match.el" "helm-core-pkg.el") "helm-pkg.el") :host github :repo "emacs-helm/helm" :package "helm" :local-repo "helm") (:type git :flavor melpa :host github :repo "syohex/emacs-helm-ag" :package "helm-ag" :local-repo "emacs-helm-ag") (:type git :flavor melpa :host github :repo "emacs-jp/helm-c-yasnippet" :package "helm-c-yasnippet" :local-repo "helm-c-yasnippet") (:type git :flavor melpa :host github :repo "Sodel-the-Vociferous/helm-company" :package "helm-company" :local-repo "helm-company") (:type git :flavor melpa :host github :repo "emacs-helm/helm-describe-modes" :package "helm-describe-modes" :local-repo "helm-describe-modes") (:type git :flavor melpa :host github :repo "bbatsov/helm-projectile" :package "helm-projectile" :local-repo "helm-projectile")) ", ")
  (doom--format-class (quote warn) "A thread has timed out. The following packages were skipped:\n\n  %s" (string-join (cdr (car futures)) ", "))
  (format (doom--format-class (quote warn) "A thread has timed out. The following packages were skipped:\n\n  %s" (string-join (cdr (car futures)) ", ")))
  (doom--format (format (doom--format-class (quote warn) "A thread has timed out. The following packages were skipped:\n\n  %s" (string-join (cdr (car futures)) ", "))))
  (doom--format-print (doom--format (format (doom--format-class (quote warn) "A thread has timed out. The following packages were skipped:\n\n  %s" (string-join (cdr (car futures)) ", ")))))
  (progn (doom--format-print (doom--format (format (doom--format-class (quote warn) "A thread has timed out. The following packages were skipped:\n\n  %s" (string-join (cdr (car futures)) ", "))))) (throw (quote timeout) t))
  (if (> time timeout) (progn (doom--format-print (doom--format (format (doom--format-class (quote warn) "A thread has timed out. The following packages were skipped:\n\n  %s" (string-join (cdr ...) ", "))))) (throw (quote timeout) t)))
  (while (not (async-ready (car (car futures)))) (if (> time timeout) (progn (doom--format-print (doom--format (format (doom--format-class (quote warn) "A thread has timed out. The following packages were skipped:\n\n  %s" (string-join ... ", "))))) (throw (quote timeout) t))) (sleep-for 2) (setq time (1+ time)) (doom--format-print (doom--format (format "."))))
  (catch (quote timeout) (while (not (async-ready (car (car futures)))) (if (> time timeout) (progn (doom--format-print (doom--format (format (doom--format-class ... "A thread has timed out. The following packages were skipped:\n\n  %s" ...)))) (throw (quote timeout) t))) (sleep-for 2) (setq time (1+ time)) (doom--format-print (doom--format (format ".")))) (let* ((result (or (async-get (car (car-safe ...))) (cons nil nil))) (status (if result (car-safe (prog1 result (setq result ...))) (signal (quote wrong-number-of-arguments) (list nil (length result)))))) (cond ((null status) (error "Thread returned an invalid result: %S" errors)) ((eq status (quote error)) (error "There were errors:\n\n%s" (cond ((and ... ...) (prin1-to-string result)) ((stringp result) result) ((mapconcat ... result "\n"))))) ((eq status (quote ok)) (doom--format-print (doom--format (format (doom--format-class ... "Appended %S to package list") (or result "nothing")))) (setq specs (append specs result))) ((error "Thread returned a non-standard status: %s\n\n%s" status result)))))
  (let ((time 0)) (catch (quote timeout) (while (not (async-ready (car (car futures)))) (if (> time timeout) (progn (doom--format-print (doom--format (format ...))) (throw (quote timeout) t))) (sleep-for 2) (setq time (1+ time)) (doom--format-print (doom--format (format ".")))) (let* ((result (or (async-get (car ...)) (cons nil nil))) (status (if result (car-safe (prog1 result ...)) (signal (quote wrong-number-of-arguments) (list nil ...))))) (cond ((null status) (error "Thread returned an invalid result: %S" errors)) ((eq status (quote error)) (error "There were errors:\n\n%s" (cond (... ...) (... result) (...)))) ((eq status (quote ok)) (doom--format-print (doom--format (format ... ...))) (setq specs (append specs result))) ((error "Thread returned a non-standard status: %s\n\n%s" status result))))))
  (while futures (doom--format-print (doom--format (format ". %.0f%%" (* (/ (- total (length futures)) (float total)) 100)))) (let ((time 0)) (catch (quote timeout) (while (not (async-ready (car (car futures)))) (if (> time timeout) (progn (doom--format-print (doom--format ...)) (throw (quote timeout) t))) (sleep-for 2) (setq time (1+ time)) (doom--format-print (doom--format (format ".")))) (let* ((result (or (async-get ...) (cons nil nil))) (status (if result (car-safe ...) (signal ... ...)))) (cond ((null status) (error "Thread returned an invalid result: %S" errors)) ((eq status (quote error)) (error "There were errors:\n\n%s" (cond ... ... ...))) ((eq status (quote ok)) (doom--format-print (doom--format ...)) (setq specs (append specs result))) ((error "Thread returned a non-standard status: %s\n\n%s" status result)))))))
  (let (specs) (while futures (doom--format-print (doom--format (format ". %.0f%%" (* (/ (- total ...) (float total)) 100)))) (let ((time 0)) (catch (quote timeout) (while (not (async-ready (car ...))) (if (> time timeout) (progn (doom--format-print ...) (throw ... t))) (sleep-for 2) (setq time (1+ time)) (doom--format-print (doom--format (format ".")))) (let* ((result (or ... ...)) (status (if result ... ...))) (cond ((null status) (error "Thread returned an invalid result: %S" errors)) ((eq status ...) (error "There were errors:\n\n%s" ...)) ((eq status ...) (doom--format-print ...) (setq specs ...)) ((error "Thread returned a non-standard status: %s\n\n%s" status result))))))) (doom--format-print (doom--format (format ". 100%%"))) (terpri) (let* ((specs (and t (delq nil specs)))) (if specs (if (not (or auto-accept-p (y-or-n-p (doom--format ...)))) (ignore (doom--format-print (doom--format (format ...)))) (terpri) --make-package-modifications-available) (let (--packages-to-rebuild (make-hash-table :test ...)) --packages-not-to-rebuild (make-hash-table :test ...))) (let ((--dolist-tail-- specs) spec) (while --dolist-tail-- (setq spec ...) (let* ... ...) (setq --dolist-tail-- ...))) (doom--finalize) (doom-packages-rebuild auto-accept-p)) t) (progn (doom--format-print (doom--format (format (doom--format-class ... "No packages to update")))) nil))))
  (condition-case e (let (specs) (while futures (doom--format-print (doom--format (format ". %.0f%%" (* (/ ... ...) 100)))) (let ((time 0)) (catch (quote timeout) (while (not (async-ready ...)) (if (> time timeout) (progn ... ...)) (sleep-for 2) (setq time (1+ time)) (doom--format-print (doom--format ...))) (let* ((result ...) (status ...)) (cond (... ...) (... ...) (... ... ...) (...)))))) (doom--format-print (doom--format (format ". 100%%"))) (terpri) (let* ((specs (and t (delq nil specs)))) (if specs (if (not (or auto-accept-p (y-or-n-p ...))) (ignore (doom--format-print (doom--format ...))) (terpri) --make-package-modifications-available) (let (--packages-to-rebuild ...) --packages-not-to-rebuild ...)) (let (... spec) (while --dolist-tail-- ... ... ...)) (doom--finalize) (doom-packages-rebuild auto-accept-p)) t) (progn (doom--format-print (doom--format (format ...))) nil)))) ((debug error) (message "Output:\n%s" --process-get-output)) (signal (car e) (error-message-string e))))
  (let* ((futures (or (let* ((--cl-var-- (seq-partition ... ...)) (group nil) (future nil) (--cl-var-- nil)) (while (consp --cl-var--) (setq group (car --cl-var--)) (setq future (doom--packages-remove-outdated-f group)) (if (processp future) (progn ...) (doom--format-print ...)) (setq --cl-var-- (cdr --cl-var--))) (nreverse --cl-var--)) (error (doom--format (format "Failed to create any threads"))))) (total (length futures)) (timeout 20)) (condition-case e (let (specs) (while futures (doom--format-print (doom--format (format ". %.0f%%" (* ... 100)))) (let ((time 0)) (catch (quote timeout) (while (not ...) (if ... ...) (sleep-for 2) (setq time ...) (doom--format-print ...)) (let* (... ...) (cond ... ... ... ...))))) (doom--format-print (doom--format (format ". 100%%"))) (terpri) (let* ((specs (and t (delq nil specs)))) (if specs (if (not (or auto-accept-p ...)) (ignore (doom--format-print ...)) (terpri) --make-package-modifications-available) (let (... ...) (let ... ...) (doom--finalize) (doom-packages-rebuild auto-accept-p)) t) (progn (doom--format-print (doom--format ...)) nil)))) ((debug error) (message "Output:\n%s" --process-get-output)) (signal (car e) (error-message-string e)))))
  (let ((doom-format-indent (+ 2 doom-format-indent))) (let* ((futures (or (let* ((--cl-var-- ...) (group nil) (future nil) (--cl-var-- nil)) (while (consp --cl-var--) (setq group ...) (setq future ...) (if ... ... ...) (setq --cl-var-- ...)) (nreverse --cl-var--)) (error (doom--format (format "Failed to create any threads"))))) (total (length futures)) (timeout 20)) (condition-case e (let (specs) (while futures (doom--format-print (doom--format (format ". %.0f%%" ...))) (let ((time 0)) (catch (quote timeout) (while ... ... ... ... ...) (let* ... ...)))) (doom--format-print (doom--format (format ". 100%%"))) (terpri) (let* ((specs (and t ...))) (if specs (if (not ...) (ignore ...) (terpri) --make-package-modifications-available) (let ... ... ... ...) t) (progn (doom--format-print ...) nil)))) ((debug error) (message "Output:\n%s" --process-get-output)) (signal (car e) (error-message-string e))))))
  doom-packages-update(nil)
  (progn -check-all) (doom-packages-update doom-auto-accept))
  (if (progn -check-all) (doom-packages-update doom-auto-accept)) (progn (doom-reload-package-autoloads (quote force-p))))
  (progn (doom-reload-core-autoloads) (if (progn -check-all) (doom-packages-update doom-auto-accept)) (progn (doom-reload-package-autoloads (quote force-p)))) t)
  doom-cli-update()
  apply(doom-cli-update nil)
  (and t (apply fn args))
  (let* ((ret (and t (apply fn args)))) (if ret (progn (doom--format-print (doom--format (format "\n%s" (doom--format-class (quote success) "Finished! (%.4fs)" (float-time ...))))) (run-hooks (quote doom-cli-post-execute-hook)) ret) nil))
  (unwind-protect (let* ((ret (and t (apply fn args)))) (if ret (progn (doom--format-print (doom--format (format "\n%s" (doom--format-class ... "Finished! (%.4fs)" ...)))) (run-hooks (quote doom-cli-post-execute-hook)) ret) nil)) (run-hooks (quote doom-cli-post-error-execute-hook)))
  (let ((start-time (current-time))) (run-hooks (quote doom-cli-pre-execute-hook)) (unwind-protect (let* ((ret (and t (apply fn args)))) (if ret (progn (doom--format-print (doom--format (format "\n%s" ...))) (run-hooks (quote doom-cli-post-execute-hook)) ret) nil)) (run-hooks (quote doom-cli-post-error-execute-hook))))
  (if show-help (doom--dispatch-help fn args) (let ((start-time (current-time))) (run-hooks (quote doom-cli-pre-execute-hook)) (unwind-protect (let* ((ret (and t (apply fn args)))) (if ret (progn (doom--format-print (doom--format ...)) (run-hooks (quote doom-cli-post-execute-hook)) ret) nil)) (run-hooks (quote doom-cli-post-error-execute-hook)))))
  (let ((fn (doom--dispatch-command cmd))) (if (fboundp fn) nil (user-error "%S is not any command *I* know!" cmd)) (if show-help (doom--dispatch-help fn args) (let ((start-time (current-time))) (run-hooks (quote doom-cli-pre-execute-hook)) (unwind-protect (let* ((ret (and t ...))) (if ret (progn (doom--format-print ...) (run-hooks ...) ret) nil)) (run-hooks (quote doom-cli-post-error-execute-hook))))))
  doom-dispatch("u" nil)
  (condition-case e (doom-dispatch (car args) (cdr args)) (user-error (print! (error "%s\n") (error-message-string e)) (print! (yellow "See 'doom help %s' for documentation on this command.") (car args))) ((debug error) (message "--------------------------------------------------\n") (message "There was an unexpected error:") (message "  %s (%s)" (get (car e) (quote error-message)) (car e)) (let ((--dolist-tail-- (cdr e)) item) (while --dolist-tail-- (setq item (car --dolist-tail--)) (message "  %s" item) (setq --dolist-tail-- (cdr --dolist-tail--)))) (if debug-on-error nil (message (concat "\nRun the command again with the -d (or --debug) option to enable debug\n" "mode and, hopefully, generate a stack trace. If you decide to file a bug\n" "report, please include it!\n\n" "Emacs outputs to standard error, so you'll need to redirect stderr to\n" "stdout to pipe this to a file or clipboard!\n\n" "  e.g. doom -d install 2>&1 | clipboard-program")) (signal (quote doom-error) e))))
  (let ((default-directory emacs-dir)) (setq argv nil noninteractive (quote doom)) (condition-case e (doom-dispatch (car args) (cdr args)) (user-error (print! (error "%s\n") (error-message-string e)) (print! (yellow "See 'doom help %s' for documentation on this command.") (car args))) ((debug error) (message "--------------------------------------------------\n") (message "There was an unexpected error:") (message "  %s (%s)" (get (car e) (quote error-message)) (car e)) (let ((--dolist-tail-- (cdr e)) item) (while --dolist-tail-- (setq item (car --dolist-tail--)) (message "  %s" item) (setq --dolist-tail-- (cdr --dolist-tail--)))) (if debug-on-error nil (message (concat "\nRun the command again with the -d (or --debug) option to enable debug\n" "mode and, hopefully, generate a stack trace. If you decide to file a bug\n" "report, please include it!\n\n" "Emacs outputs to standard error, so you'll need to redirect stderr to\n" "stdout to pipe this to a file or clipboard!\n\n" "  e.g. doom -d install 2>&1 | clipboard-program")) (signal (quote doom-error) e)))))
  (cond ((not noninteractive) (doom-run-all-startup-hooks-h)) ((and (not (cdr args)) (member (car args) (quote ("help" "h")))) (usage)) ((not args) (print! (error "No command detected.\n")) (usage)) ((let ((default-directory emacs-dir)) (setq argv nil noninteractive (quote doom)) (condition-case e (doom-dispatch (car args) (cdr args)) (user-error (print! (error "%s\n") (error-message-string e)) (print! (yellow "See 'doom help %s' for documentation on this command.") (car args))) ((debug error) (message "--------------------------------------------------\n") (message "There was an unexpected error:") (message "  %s (%s)" (get (car e) (quote error-message)) (car e)) (let ((--dolist-tail-- ...) item) (while --dolist-tail-- (setq item ...) (message "  %s" item) (setq --dolist-tail-- ...))) (if debug-on-error nil (message (concat "\nRun the command again with the -d (or --debug) option to enable debug\n" "mode and, hopefully, generate a stack trace. If you decide to file a bug\n" "report, please include it!\n\n" "Emacs outputs to standard error, so you'll need to redirect stderr to\n" "stdout to pipe this to a file or clipboard!\n\n" "  e.g. doom -d install 2>&1 | clipboard-program")) (signal (quote doom-error) e)))))))
  (let ((args (cdr (cdr (cdr command-line-args)))) (emacs-dir (or (getenv "EMACSDIR") (expand-file-name "../" (file-name-directory (file-truename load-file-name)))))) (while (condition-case nil (progn (string-prefix-p "-" (car args))) (error nil)) (let* ((val (car-safe (prog1 args (setq args ...))))) (cond ((member val (quote ("--help" "-h"))) (setq args (cons "help" args))) ((member val (quote ("--debug" "-d"))) (setenv "DEBUG" "1") (message "Debug mode on")) ((member val (quote ("--insecure" "-i"))) (setenv "INSECURE" "1") (message "Insecure mode on")) ((member val (quote ("--private" "-p"))) (setq doom-private-dir (expand-file-name (concat ... "/"))) (setenv "DOOMDIR" doom-private-dir) (message "DOOMDIR changed to %s" doom-private-dir) (or (file-directory-p doom-private-dir) (message "Warning: %s does not exist" (abbreviate-file-name doom-private-dir)))) ((member val (quote ("--local" "-l"))) (setq doom-local-dir (expand-file-name (concat ... "/"))) (setenv "DOOMLOCALDIR" doom-local-dir) (message "DOOMLOCALDIR changed to %s" doom-local-dir)) ((member val (quote ("--emacsd" "-e"))) (setq emacs-dir (expand-file-name (concat ... "/"))) (message "Emacs directory changed to %s" emacs-dir)) ((member val (quote ("--yes" "-y"))) (setenv "YES" "1") (message "Auto-yes mode on")) (t nil)))) (if (file-directory-p emacs-dir) nil (error "%s does not exist" emacs-dir)) (load (expand-file-name "init" emacs-dir) nil (quote nomessage)) (cond ((not noninteractive) (doom-run-all-startup-hooks-h)) ((and (not (cdr args)) (member (car args) (quote ("help" "h")))) (usage)) ((not args) (print! (error "No command detected.\n")) (usage)) ((let ((default-directory emacs-dir)) (setq argv nil noninteractive (quote doom)) (condition-case e (doom-dispatch (car args) (cdr args)) (user-error (print! (error "%s\n") (error-message-string e)) (print! (yellow "See 'doom help %s' for documentation on this command.") (car args))) ((debug error) (message "--------------------------------------------------\n") (message "There was an unexpected error:") (message "  %s (%s)" (get ... ...) (car e)) (let (... item) (while --dolist-tail-- ... ... ...)) (if debug-on-error nil (message ...) (signal ... e))))))))
  eval-buffer(#<buffer  *load*> nil "/Users/mls/.emacs.d/bin/doom" nil t)  ; Reading at buffer position 5447
  load-with-code-conversion("/Users/mls/.emacs.d/bin/doom" "/Users/mls/.emacs.d/bin/doom" nil t)
  load("/Users/mls/.emacs.d/bin/doom" nil t t)
  command-line-1(("-scriptload" "bin/doom" "--" "u"))
  command-line()
  normal-top-level()
</pre></details>

**System information**
<details><pre>
emacs   version    26.2
straight ef4424bd 2019-08-07 23:36:21 -0400
macos mojave
</pre></details>

**Comment by hlissner** [comment]
As of c266680 this should be resolved. The error message it _should_ have been giving you was that the async process timed out, which it is known to do in a few elusive edge cases I haven't tracked down yet. In any case, let me know if the error persists and I will reopen the issue. Thanks for bringing it to my attention!
