### ISSUE TITLE
[HOWTO] set directory for deft

### ISSUE THREAD

**Issue by viocost** [hlissner/doom-emacs#1659]
I want to change default directory for deft notes.
I tried 

```
(use-package-hook! deft
  :pre-config
  ...
  (setq deft-directory "~/notes")
  ...
)
```

Also tried the same thing with :post-config :pre-init and :post-init

**Comment by viocost** [comment]
Heh, solution was simple.
Instead of use-package-hook! I used use-package! and placed code under :init

**Comment by hlissner** [comment]
In that case, `use-package!` and `use-package-hook!` aren't necessary. You could simply do `(setq deft-directory "~/notes")`.
