### ISSUE TITLE
[HOWTO] Disable symbolic links expanding

### ISSUE THREAD

**Issue by Svadkos** [hlissner/doom-emacs#1660]
I was trying to disable symbolic links expanding and ended up with this mess
![Screenshot](https://user-images.githubusercontent.com/9449246/62822565-c3f93380-bb74-11e9-95f6-f9c24a6cbd14.png)
It affects directories with git, and works without problems in normal dirs.

I did it with `(setq-default find-file-visit-truename nil)` in doom/config.el 

**System information**
<details><pre>
Generating Doom info...
- OS: gnu/linux (x86_64-pc-linux-gnu)
- Shell: /usr/bin/zsh
- Emacs: 27.0.50 (May 05, 2019)
- Doom: 2.0.9 (HEAD -> develop, _upgrade/develop f754d4ff 2019-07-23 18:23:17 +0200)
- Graphic display: nil (daemon: nil)
- System features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP
- Details:
  ```elisp
  env bootstrapper: nil
  elc count: 0
  uname -a:  Linux 5.2.7-arch1-1-ARCH #1 SMP PREEMPT Wed Aug 7 02:00:26 UTC 2019 x86_64
  modules:   (:completion company ivy :ui doom doom-dashboard fill-column hl-todo modeline nav-flash ophints (popup +all +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor evil file-templates fold multiple-cursors rotate-text snippets :emacs dired electric vc :term vterm :tools editorconfig eval flycheck flyspell (lookup +docsets) magit :lang data emacs-lisp markdown (org +attach +babel +capture +export +habit +protocol) sh geiser :app write :config default)
  packages:  ((hl-line :disable t) evil-terminal-cursor-changer)
  exec-path: (/usr/lib/ccache/bin/ /usr/local/bin /usr/local/sbin /usr/bin /opt/android-ndk /opt/android-sdk/tools /opt/android-sdk/tools/bin /var/lib/flatpak/exports/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /usr/lib/emacs/27.0.50/x86_64-pc-linux-gnu)
  ```
</pre></details>

**Comment by hlissner** [comment]
This appears to be an bug with [doom-modeline](https://github.com/seagle0128/doom-modeline), please bring this up there.

**Comment by Svadkos** [comment]
Resolved.
