### ISSUE TITLE
How to let doom refresh use local emacs?

### ISSUE THREAD

**Issue by FirstLoveLife** [hlissner/doom-emacs#1662]
For some reason, there is a system-wise emacs25.1 installed via apt on my company's server, but doom doesn't support 25.1. 

What I did: 
```
git clone https://github.com/hlissner/doom-emacs/ ~/chenli/.emacs.d
git clone https://github.com/FirstLoveLife/Black-RX ~/.doom.d
```

My local emacs27(build from source): `~/chenli/emacs/src/emacs`
`cd ~/chenli/emacs.d/bin/; ./doom refresh` will always `/usr/bin/emacs`. How to let doom use my local emacs27?

**Comment by filalex77** [comment]
You just need to add your `"$HOME/emacs/src/"` to your `$PATH` before the system `$PATH`.

For example, in your `.bashrc`/`.zshrc`/etc.:

```sh
export PATH="$HOME/emacs/src:$PATH"
```

**Comment by FirstLoveLife** [comment]
@filalex77 Sorry I didn't clarify that I have tried this way but doom still prefer /usr/bin/emacs

**Comment by hlissner** [comment]
bin/doom consults the EMACS environment variable, if it is set. This should work for you:

```
EMACS=~/chenli/emacs/src/emacs doom refresh
```
