### ISSUE TITLE
[QUESTION] def-package-hook! which-key Doesn't fire

### ISSUE THREAD

**Issue by sooqua** [hlissner/doom-emacs#1663]
I'm trying to put `which-key-idle-delay` in a hook, because just `setq`ing it in `.doom.d/init.el` or `.doom.d/config.el` as suggested [here](https://github.com/hlissner/doom-emacs/issues/454#issuecomment-371024204) didn't work. For the testing purpose, placing this in my `init.el`...
```elisp
(def-package-hook! which-key
  :pre-config
  (kill-emacs)
  nil)
```
...doesn't kill emacs. Replacing `which-key` with `doom-themes` as in [example](https://github.com/hlissner/doom-emacs/wiki/Customization) works. **Why?** `def-package` is called [right there](https://github.com/hlissner/doom-emacs/blob/master/core/core-keybinds.el#L26).

Would replacing this with a duplicate `def-package!` in my config.el be a "good" solution? Because it works, and seem to preserve all the settings from `core-keybinds.el`. My guess is that it reloads the package, but the variables remain intact, so it reads my configuration overriding `which-key-idle-delay`. I may be completely wrong though.

**Comment by sooqua** [comment]
I guess it's because
```
The overall load order of Doom is as follows:
  ~/.emacs.d/init.el
  ~/.emacs.d/core/core.el
  ~/.doom.d/init.el
  Module init.el files
  `doom-before-init-modules-hook'
  Module config.el files
  ~/.doom.d/config.el
  `doom-init-modules-hook'
  `after-init-hook'
  `emacs-startup-hook'
  `doom-init-ui-hook'
  `window-setup-hook'
```
And `def-package! which-key` is in the core =\\
Any workaround?

**Comment by filalex77** [comment]
Great research on the topic. I can agree with putting another `def-package!` block in your config - it should just reload the package, and `which-key` is not that expensive to load. It's really annoying that you can't just change the delay *after* `which-key` has loaded, but oh well.

**Comment by sooqua** [comment]
Using this atm:
```
(add-hook 'window-setup-hook
  (setq which-key-idle-delay 0.01)
  (which-key-mode +1))
```
I think this should be a bit faster than reloading the whole package and should preserve all of `core-keybinds.el` configurations. <sub><sup>there is a cleaner solution, right? ;(</sup></sub>

**Comment by filalex77** [comment]
Yes, this should work well enough. Maybe @hlissner would have some Emacs Lisp magic to help you.

**Comment by hlissner** [comment]
Your assessment is correct. This is a load order issue. You can't reconfigure a core package with `def-package-hook!`, because it has to run before a package's `def-package!` block.

```lisp
(add-hook 'window-setup-hook
  (progn
    (setq which-key-idle-delay 0.01)
    (which-key-mode +1)))
```

This won't work the way you're expecting. The progn block evaluates immediately and returns `t`, which is what gets added to `window-setup-hook`, and does nothing (if it doesn't throw an error).

This is probably what you want:

```elisp 
(after! which-key 
  (setq which-key-idle-delay 0.01)
  (which-key-mode +1))
```

However, what I don't understand is why this doesn't work:

```eliso
(setq which-key-idle-delay 0.01)
```

I can reproduce this issue, but for whatever reason which-key ignores it on first invokation. This would appear to be a which-key bug. I'll look into it.
