### ISSUE TITLE
[HOWTO] Persistent scratch

### ISSUE THREAD

**Issue by haji-ali** [hlissner/doom-emacs#1669]
I want to have a persistent scratch for my notes. The package `persistent-scratch` does this perfectly and I enable it like this
```
(use-package! persistent-scratch
  :config (persistent-scratch-setup-default))
```

However, it adds around 2 seconds to my load time. Is there a better way to load this package? Or is there a faster package?

**Comment by filalex77** [comment]
@haji-ali Did you add `(package! persistent-scratch)` to `~/.doom.d/packages.el` and run `doom refresh`, or do you only have this `use-package!` block in your config?

Also, please post your `M-x doom-info RET`. Thanks!

**Comment by hlissner** [comment]
@haji-ali Is there any reason you're not using the scratch buffer built into Doom? They persist across sessions and come in two flavors: a global and project scratch buffers.

+ To open a global scratch buffer in a popup: `SPC x` or `SPC b x`
+ To open a global scratch buffer in the current window: `SPC b X`
+ To open a project scratch buffer in a popup: `SPC p x`
+ To open a project scratch buffer in the current window: `SPC p X`

They current only persist when Emacs is correctly quit, but I'll improve it to persist more frequently soon.

**Comment by haji-ali** [comment]
@hlissner, I didn't know about doom scratch buffers. These look great! I will definitely use them now. 

Is it possible to make the `*scratch*` buffer a global `*doom:scratch*` buffer? So that it persists.
Since it's a fallback buffer that is always open and I would prefer not to have two scratch buffers.

**Comment by hlissner** [comment]
> Is it possible to make the *scratch* buffer a global *doom:scratch* buffer?

It may be a little difficult because I do not control the life cycle of the `*scratch*` buffer, unlike `*doom:scratch*` buffers. I also don't know what side-effects affecting the `*scratch*` buffer this way could have. That said, I'll look into it.   

In the meantime, I'll consider this issue resolved. Feel free to follow up here if you like, however.

**Comment by TotNotTac** [comment]
How would you go about correctly closing these doom scratch buffers? Everytime I close them (SPC b k) they lose all the changed content.
