### ISSUE TITLE
[QUESTION] How to remove some not use packages

### ISSUE THREAD

**Issue by taigacute** [hlissner/doom-emacs#1676]
What would you like to know?
Thank you for your great work, I am a vimmer, now come to emacs,Doom is great, but it adds a lot of packages that I don't use, although I can disable them, but they still exist on my hard drive., I want to streamline it,I hope I can use Doom like my vim config [ThinkVim](https://github.com/hardcoreplayers/ThinkVim). I am not very familiar with elisp, the doom core code is very complicated. I hope to get your help, how to remove the package I don't use, and I don't like to use `.doom.d`, how to set up the package list? i copy the init.example.el content to init.el， but it didnt work. doom dosent load package list.. How does doom get all the packages and then load them?

**Comment by hlissner** [comment]
To remove a package, add `(package! packagename :disable t)` to `~/.doom.d/packages.el` and run `~/.emacs.d/bin/doom refresh` to remove all disabled packages and ensure Doom is in a working state.

> I don't like to use .doom.d

You must if you want to customize Doom. You can also put it in `~/.config/doom`.

> i copy the init.example.el content to init.el

It must be copied to ~/.doom.d/init.el. It will not work in ~/.emacs.d. Doom was designed to be customized out of `~/.doom.d` (or `~/.config/doom`). There is no alternative.

> How does doom get all the packages and then load them?

It reads the `package!` declarations in every enabled module's packages.el file. The `doom!` block in ~/.doom.d/init.el (after copying init.example.el there) determines what modules are enabled and in what order.

------

Hope that helps!

**Comment by taigacute** [comment]
Thank you for your reply, I want to make changes based on the core of doom. But it is very difficult at the moment.

**Comment by hlissner** [comment]
> Can I not rely on doom.d

You must use doom.d. Without it, Doom's modules and their dependencies cannot be installed.

> by the way i removed some folders that in moudles/lang/.only keep the moudles/lang/go

I don't understand the problem. If you install doom normally, doom will only load what you use, nothing more, nothing less. It will not load everything. You do not have to do all this manual work. You are only making it more difficult for yourself.

I would not recommend modifying `~/.emacs.d` if you'd like to use Doom for an extended period of time. It will exclude you from getting updates, may break things if you don't know what you're doing, and I can't offer help if Doom is in an unpredictable state.

> i had removed them, only have go ..but them still exist ...

I don't understand what you've done, what you're trying to do and what you're showing me. You deleted the folders in modules/lang/, but have you commented them out in your doom! block? What still exists? Did you end up copying init.example.el to ~/.doom.d/init.el, as I suggested? From the snippet, you do not have go uncommented.

**Comment by taigacute** [comment]
thanks.i will use doom to lean emacs.

**Comment by taigacute** [comment]
@hlissner  hi  bro. Do you have an idea to extract the core code of doom out of a configuration framework? Users can add their own packages on this configuration framework. I think this will be great to help many vimers.

**Comment by ckruse** [comment]
For reference: he asked a similar question here: <https://www.reddit.com/r/emacs/comments/cr2in6/how_to_build_a_emacs_conifg_based_on_doom/>

**Comment by hlissner** [comment]
I do not plan to do this, because you can already do this. Install Doom and use as many (or as few) of its modules as you like. You can use none of the modules if you want, then you'd only be using Doom core.
