### ISSUE TITLE
[HOWTO] Not add trailing whitespaces on newlines in js2-mode?

### ISSUE THREAD

**Issue by sooqua** [hlissner/doom-emacs#1679]
**What I want to achieve**
elisp mode (good):
![Peek 2019-08-18 05-47](https://user-images.githubusercontent.com/4979209/63219539-4046d480-c17c-11e9-8947-6622f927f249.gif)
js2-mode (bad):
![Peek 2019-08-18 05-33](https://user-images.githubusercontent.com/4979209/63219535-391fc680-c17c-11e9-9fe4-a627ccf9dcfa.gif)

How can I achieve the same behavior in js2-mode as in elisp? I want enter key to add newlines at the same indentation level but don't keep the trailing whitespace on the previous.

**System information**
<details><pre>
- OS: gnu/linux (x86_64-pc-linux-gnu)
- Shell: /usr/bin/zsh
- Emacs: 26.2 (Apr 12, 2019)
- Doom: 2.0.9 (HEAD -> develop, _upgrade/develop f754d4ff 2019-07-23 18:23:17 +0200)
- Graphic display: t (daemon: nil)
- System features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2
- Details:
  ```elisp
  env bootstrapper: envvar-file
  elc count: 0
  uname -a:  Linux 5.2.8-arch1-1-ARCH #1 SMP PREEMPT Fri Aug 9 21:36:07 UTC 2019 x86_64
  modules:   (:completion company ivy :ui doom hl-todo modeline nav-flash ophints (popup +all +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor evil file-templates fold multiple-cursors rotate-text snippets :emacs dired electric vc :tools eval flycheck (lookup +docsets) magit :lang cc data emacs-lisp javascript lua markdown (org +dragndrop +ipython +pandoc +present) sh web :config default)
  packages:  n/a
  exec-path: (/usr/local/bin /usr/bin /bin /usr/local/sbin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /usr/lib/emacs/26.2/x86_64-pc-linux-gnu/)
  ```
</pre></details>

**Comment by sooqua** [comment]
And why is this not working?
```
(defun +javascript/newline-and-indent ()
  "TODO"
  (interactive)
  (doom/backward-delete-whitespace-to-column)
  (newline-and-indent)
  )
(map! :map js2-mode-map [remap newline] #'+javascript/newline-and-indent)
```
`C-h k <enter>` still shows `(newline-and-indent)`. Why is map! not working here? This is taken from [here](https://github.com/hlissner/doom-emacs/issues/498#issuecomment-377725944).

**Comment by sooqua** [comment]
This is the only thing that works:
```elisp
(defun +javascript/newline-and-indent ()
  "TODO"
  (doom/backward-kill-to-bol-and-indent))
(advice-add #'newline-and-indent :before #'+javascript/newline-and-indent)
```
But it overrides `newline-and-indent` for every mode. Is there a better way?

**Comment by hlissner** [comment]
Try this instead:

```ekuso
(map! :map js2-mode-map [remap newline-and-indent] #'+javascript/newline-and-indent)
```

**Comment by hlissner** [comment]
That said, Doom enables ws-butler by default. It will clean up trailing whitespace (on lines you've touched) when you save, so is manually cleaning it up necessary?

**Comment by sooqua** [comment]
Well it leaves that trailing red block behind, as if it's telling "something is wrong", until I save. This is a bit distracting. I changed the value of `indent-line-function` in js2-mode from `rjsx-indent-line` to `indent-relative` as in elisp-mode, but it just inserts 2 spaces where it needs to be 4 and then continues on column 0 (doesn't keep indentation).
What can I write in `+javascript/newline-and-indent`? Sorry I'm new to elisp. I just need a way to check if a line is empty and to reset the indentation, but I can probably use `evil-shift-left` for that...

**Comment by sooqua** [comment]
This worked for me:
`(advice-add 'newline-and-indent :override #'reindent-then-newline-and-indent)`

**Comment by hlissner** [comment]
You can detect if the current line is empty with any of the following:

```elisp
(save-excursion
  (beginning-of-line)
  (looking-at-p "[ \t]*$"))
```

Or use the `(sp-point-in-blank-line)` function (essentially does the above).

**Comment by sooqua** [comment]
Wait! It's [this override](https://github.com/hlissner/doom-emacs/blob/develop/modules/config/default/autoload/default.el#L112) that's causing the issue! It doesn't call `(delete-horizontal-space t)` before `(newline nil t)` like original `newline-and-indent` does.

**Comment by hlissner** [comment]
I could've sworn there was a good reason for that, but the advise was written so many years ago I don't remember anymore. I've added the `delete-horizontal-space` call back to `+default*newline-indent-and-continue-comments`, which I hope resolves your issue. If that isn't the case, let me know and I will reopen this issue. Thanks for bringing it to my attention!
