### ISSUE TITLE
[BUG] Modeline going past edge of window

### ISSUE THREAD

**Issue by juliandemille** [hlissner/doom-emacs#1680]
**Describe the issue**
The modeline has data that goes past the edge of the window, shown here:
![2019-08-18-133210_1920x1080_scrot](https://user-images.githubusercontent.com/8127111/63228099-9c314d80-c1bc-11e9-8bb5-d3209444962c.png)

**Steps to reproduce**
Unknown, this has always been an issue for me.

**System information**
<details><pre>
((emacs
  (version . "26.2")
  (features . "XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2")
  (build . "Apr 12, 2019")
  (buildopts "--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-modules 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now"))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> straight, origin/straight 58fb9faf 2019-08-17 16:04:41 -0400"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/usr/bin/fish")
  (uname . "Linux 5.2.8-1-MANJARO #1 SMP PREEMPT Fri Aug 9 19:34:20 UTC 2019 x86_64")
  (path "~/.local/bin" "~/.cargo/bin" "~/.dotnet/tools" "~/.yarn/bin" "~/.gem/ruby/2.6.0/bin" "~/.emacs.d/bin/" "~/.rbenv/shims" "/usr/local/bin" "/usr/bin" "/bin" "/usr/local/sbin" "/usr/bin/site_perl" "/usr/bin/vendor_perl" "/usr/bin/core_perl" "/usr/lib/emacs/26.2/x86_64-pc-linux-gnu"))
 (config
  (envfile)
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard doom-quit hl-todo indent-guides modeline nav-flash ophints (popup +all +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor evil file-templates fold multiple-cursors rotate-text snippets :emacs dired electric vc :term eshell :tools debugger docker editorconfig ein eval flycheck (lookup +docsets) lsp magit pdf tmux :lang assembly (cc +lsp) csharp data emacs-lisp ess fsharp (haskell +intero) (java +lsp) (javascript +lsp) julia kotlin latex markdown (org +dragndrop +ipython +pandoc +present) (python +lsp +pyenv) qt (ruby +lsp +rbenv) (rust +lsp) sh (web +lsp) :app write :config default)
  (packages "exec-path-from-shell")))
</pre></details>

**Comment by hlissner** [comment]
This is an issue for [the doom-modeline package](https://github.com/seagle0128/doom-modeline). It is typically caused by the combination of variable width icon fonts and variable-pitch whitespace in the modeline.

**Comment by even4void** [comment]
A quick workaround would be to put the Flycheck indicator (`checker`) at the leftmost part of the right modeline. This involves redefining your modeline in your `config.el` file, e.g.:

```
(after! doom-modeline
  (doom-modeline-def-modeline 'my/modeline
    '(bar matches buffer-info remote-host buffer-position parrot selection-info)
    '(misc-info minor-modes checker input-method buffer-encoding major-mode process vcs))
  (defun setup-custom-doom-modeline ()
    (doom-modeline-set-modeline 'my/modeline 'default))
  (add-hook 'doom-modeline-mode-hook 'setup-custom-doom-modeline))
```

**Comment by hlissner** [comment]
Since this not quite a Doom issue (either an issue with doom-modeline or with missing or oversized icon fonts (for which a decent solution [is mentioned in the doom-modeline FAQ](https://github.com/seagle0128/doom-modeline#faq), involving a tweak to the fontsize in the modeline), I'll consider this resolved.
