### ISSUE TITLE
[BUG] setting doom-leader-alt-key has not effect without evil

### ISSUE THREAD

**Issue by y-usuzumi** [hlissner/doom-emacs#1684]
**Describe the issue**
Note: I am on the straight branch, but I don't think it is anything different.

I have this at the bottom of my ~/.doom.d/init.el:

```lisp
(setq doom-leader-key "M-m"
      doom-leader-alt-key "M-m"
      doom-localleader-key "M-m m"
      doom-localleader-alt-key "M-m m")
```
I also have commented out evil.

Now M-m still triggers back-to-indentation. C-h v doom-leader-alt-key reveals that it still has the default value of "C-c", likewise doom-localleader-alt-key "C-c l"

It works fine with evil enabled.

**System information**
<details><pre>
emacs   version    26.2
        features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2
        build      4月 13, 2019
        buildopts  (--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-modules 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now)
doom    version    2.0.9
        build      HEAD -> straight 58fb9faf3 2019-08-17 16:04:41 -0400
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /usr/bin/fish
        uname      Linux 5.2.9-zen1-1-zen #1 ZEN SMP PREEMPT Fri Aug 16 11:32:38 UTC 2019 x86_64
        path       (~/.local/bin ~/.cargo/bin ~/.cabal/bin ~/.ghcup/bin ~/go/bin ~/.emacs.d/bin /usr/local/sbin /usr/local/bin /usr/bin /opt/cuda/bin /opt/cxoffice/bin /var/lib/flatpak/exports/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /usr/lib/emacs/26.2/x86_64-pc-linux-gnu)
config  envfile    nil
        elc-files  0
        modules    (:completion company helm :ui doom doom-dashboard hl-todo modeline nav-flash ophints (popup +all +defaults) treemacs unicode vc-gutter vi-tilde-fringe window-select workspaces :editor file-templates fold multiple-cursors rotate-text snippets :emacs dired electric vc :tools eval flycheck (lookup +docsets) magit :lang data emacs-lisp (haskell +intero) markdown (org +dragndrop +ipython +pandoc +present) python rust (sh +fish) :config default)
        packages   (mwim multiple-cursors)
</pre></details>

**Comment by hlissner** [comment]
It appears the docstring for those variables is outdated. Try setting those variables in your config.el, instead of your init.el.

**Comment by y-usuzumi** [comment]
Hi! After moving the variables into config.el, most others have gone under M-m, while the persp and projectile keymaps are still bound to C-c.

**Comment by y-usuzumi** [comment]
Hi, sorry I read emacs-bindings.el and found it was by design different from evil-bindings.

I think it would be good if emacs-bindings is made consistent but it is beyond the scope of this issue.

Thank you!
