### ISSUE TITLE
[HOWTO] Override C-j global map

### ISSUE THREAD

**Issue by rsheasby** [hlissner/doom-emacs#1685]
I'm attempting to override C-j and C-k to inertial scrolling, but I can't seem to be able to override the C-j global map for `electric-newline-and-maybe-indent`. I've tried the following:
```
;; Error in private config: config.el, (void-variable kbd)
(map! :map global-map (kbd "C-j") #'inertias-up)

;; Doesn't remap, leaves C-j as unbound.
(define-key global-map (kbd "C-j") nil)
(map! :nv (kbd "C-j") #'inertias-up)
 ```

I'm struggling to understand what the correct way to do this is.

**System information**
<details><pre>
Generating Doom info...
- OS: gnu/linux (x86_64-pc-linux-gnu)
- Shell: /usr/bin/fish
- Emacs: 26.2 (Apr 12, 2019)
- Doom: 2.0.9 (HEAD -> develop, origin/develop, origin/HEAD f754d4ff 2019-07-23 18:23:17 +0200)
- Graphic display: nil (daemon: nil)
- System features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2
- Details:
  ```elisp
  env bootstrapper: envvar-file
  elc count: 0
  uname -a:  Linux 5.2.8-arch1-1-ARCH #1 SMP PREEMPT Fri Aug 9 21:36:07 UTC 2019 x86_64
  modules:   (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor evil file-templates fold multiple-cursors rotate-text snippets :emacs dired electric vc :tools eval flycheck (lookup +docsets) magit :lang data emacs-lisp go markdown (org +dragndrop +ipython +pandoc +present) sh :config default)
  packages:  (ox-twbs (inertial-scroll :recipe (inertial-scroll :fetcher github :repo kiwanami/emacs-inertial-scroll)))
  exec-path: (/usr/local/sbin /usr/local/bin /usr/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl ~/go/bin/ ~/go/bin/ /usr/lib/emacs/26.2/x86_64-pc-linux-gnu)
  ```
</pre></details>

**Comment by hlissner** [comment]
The problem is the use of `kbd` in `map!`. All (string) arguments are implicitly wrapped in `kbd`. This should work for you:

```elisp
(map "C-j" #'inertias-up)
```

The :map global-map is unnecessary as well. If no state/:map is provided, global-map is implied.

**Comment by rsheasby** [comment]
Aha! That works perfectly. Strangely enough though the keymap worked fine for C-k even when wrapped in kbd. I gotta say, the macros included in doom are really handy, especially for config readability, but the documentation could definitely be better to explain the intricacies. Anyway, thanks for the help!
