### ISSUE TITLE
[QUESTION] something wrong with company-tabnine

### ISSUE THREAD

**Issue by chengyi** [hlissner/doom-emacs#1686]
@hlissner I try to intergrate `company-tabnine` into doom-emacs,  the company doesn't auto popup as I type, I run `M-x company-tabnine`, the company popup shows. Please give me a hand, thank you.

config.el:
```emacs-lisp
(defun add-company-tabnine ()
  (add-to-list (make-local-variable 'company-backends) 'company-tabnine))

(def-package! company-tabnine
  :config
  (add-hook! (c-mode
              c++-mode
              emacs-lisp-mode
              python-mode)
    #'add-company-tabnine))
```

package.el:
``` emacs-lisp
(when (featurep! :completion company)
  (package! company-tabnine))
```

init.el:
```emacs-lisp
(def-package-hook! company
  :post-init
  (setq  company-idle-delay 0
         company-show-numbers t))
```

**Comment by AlexXiong97** [comment]
same problem here.

**Comment by hlissner** [comment]
Is this still an issue?

If so, please try the following:

```elisp
(defun add-company-tabnine ()
  (add-to-list (make-local-variable 'company-backends) 'company-tabnine))

(def-package! company-tabnine
  :config
  (setq company-idle-delay 0
        company-show-numbers t)
  (add-hook! (c-mode-local-vars
              c++-mode-local-vars
              emacs-lisp-mode-local-vars
              python-mode-local-vars)
    #'add-company-tabnine))
```

**Comment by chengyi** [comment]
@hlissner as @alxiong says, after using your code snippet, tabnine still does not show up

**Comment by sbstnc** [comment]
@chengyi I'm using the following config and am seeing tabnine suggestions.

`init.el`
```elisp
(use-package-hook! company
  :post-init
  (setq +lsp-company-backend '(company-lsp :with company-tabnine :separate)
        company-idle-delay 0
        company-show-numbers t))
```

`package.el`
```elisp
(when (featurep! :completion company)
  (package! company-tabnine))
```

No modifications in `config.el`.

**Comment by hlissner** [comment]
Avoid `use-package-hook!` if you don't have to use it.

```elisp
;;; config.el
(setq +lsp-company-backend '(company-lsp :with company-tabnine :separate))
(after! company
  (setq company-idle-delay 0
        company-show-numbers t))
```

**Comment by CarlQLange** [comment]
I still can't really get TabNine and LSP to play nice together. My TabNine specific config is only

``` elisp
(use-package! company-tabnine
  :after company
  :when (featurep! :completion company)
  :config
  (cl-pushnew 'company-tabnine (default-value 'company-backends))
  )
(setq +lsp-company-backend '(company-lsp :with company-tabnine :separate))
```

but unless I manually call `company-tabnine` the TabNine results don't appear. `company-backends` appears to be set to `(company-capf company-yasnippet company-tabnine company-css company-web-html)`, but tabnine results never show in the box. Maybe I'm missing a useful shortcut or something to switch the default backend?

**Comment by CarlQLange** [comment]
Ah, `+lsp-company-backend` was removed in https://github.com/hlissner/doom-emacs/commit/b3c957065c036ad677b21aafcea5f726c303d653 so no wonder it doesn't work.

**Comment by chengyi** [comment]
> 
> 
> Ah, `+lsp-company-backend` was removed in [b3c9570](https://github.com/hlissner/doom-emacs/commit/b3c957065c036ad677b21aafcea5f726c303d653) so no wonder it doesn't work.

Tuning emacs is a hard work

**Comment by msafarulla** [comment]
make sure to enable the python language in the **init.el**

Then what @hlissner suggested worked for me. 

;;; config.el
(setq +lsp-company-backend '(company-lsp :with company-tabnine :separate))
(after! company
  (setq company-idle-delay 0
        company-show-numbers t))

**Comment by hlissner** [comment]
I re-introduced the `+lsp-company-backend` variable yesterday, so the original fix should work again.

**Comment by SebastienWae** [comment]
I think this can be closed, TabNine works perfectly now, but you have to add it to `+lsp-company-backends` (as @hlissner said) if you want to use it when `lsp-mode` is active.
```emacs-lisp
(setq +lsp-company-backends '(company-tabnine company-capf))
```

**Comment by chengyi** [comment]
perfect! close it.

**Comment by donneyluck** [comment]
when press SPC . to create a new file on workspace Lua-mode
lsp-mode not enable 
tabnine and lsp-mode cannot work util restart doom
