### ISSUE TITLE
[QUESTION] Can't get company-yasnippet to work in js2-mode

### ISSUE THREAD

**Issue by sooqua** [hlissner/doom-emacs#1687]
It's a weird issue related to the problem that I've stumbled upon before, but didn't open an issue. Some code is executed only when you first enter insert mode. Because of that, this doesn't work:
```elisp
(after! js2-mode
  (setq company-backends '((company-tide :with company-yasnippet))))
```
Once I open a js file, I can eval (`M-:`) `company-backends` and I can see `((company-tide :with company-yasnippet))`, but as I enter insert mode to start typing my snippet, I can't see it in autocompletion. Once I exit insert mode and eval `company-backends` again, the output is this:
`(company-tide company-capf company-yasnippet (company-tide :with company-yasnippet))`
I tried finding the package that overrides my settings once I enter insert mode, but so far none of this worked:
```elisp
(after! tide-mode
  (setq company-backends '((company-tide :with company-yasnippet))))
(after! company-mode
  (setq company-backends '((company-tide :with company-yasnippet))))
(after! yas-minor-mode
  (setq company-backends '((company-tide :with company-yasnippet))))
```
Same with `set-company-backend!`...

**Comment by hlissner** [comment]
There are two misunderstandings at work here:

1. `(after! PACKAGE BODY...)` runs `BODY...` the first time PACKAGE is loaded. PACKAGE is not a mode, it's a package's name. `tide-mode` is a minor mode belonging to the `tide` package. `yas-minor-mode` is a minor mode belonging to the `yasnippet` package. `company-mode` belongs to the `company` package.

2. You cannot use `after!` to set buffer-local variables. There is no guarantee that the `BODY...` of an `after!` call is evaluated in the context of any particular buffer. Even if there were some guarantee, it would only affect the very first buffer; an `after!` block is only evaluated once, _after_ the package is loaded. 

   It will, at best, affect the global default value of `company-backends`, which is quickly replaced with a new, buffer-local value of `(company-tide company-capf company-yasnippet (company-tide :with company-yasnippet))` by the `+company-init-backends-h` function, which runs when company loads or before a major-mode's hooks are run (on `change-major-mode-after-body-hook`).

To correctly modify a buffer-local variable, use a hook:

```elisp
(add-hook! 'js2-mode-hook
  (setq company-backends '((company-tide :with company-yasnippet))))

;; or

(setq-hook! 'js2-mode-hook
  company-backends '((company-tide :with company-yasnippet)))
```

Or use `set-company-backend!` (just be aware this needs to run *after* the default `set-company-backend!` calls in each module, other your settings won't overwrite Doom's defaults). For example:

```elisp
;; `js2-mode` happens to have the same name as the package that defines it
(after! js2-mode
  (set-company-backend! 'js2-mode '(company-tide :with company-yasnippet)))
```

**Comment by sooqua** [comment]
None of the examples work. Same issue with entering insert mode for the first time overriding my `company-backends`

**Comment by sooqua** [comment]
Got pretty close with
```elisp
(after! tide
  (setq company-backends '((company-tide :with company-yasnippet))))
(after! company
  (setq company-backends '((company-tide :with company-yasnippet))))
(after! yasnippet
  (setq company-backends '((company-tide :with company-yasnippet))))
```
though. Now after entering insert mode company-backends are:
`(company-tide (company-tide :with company-yasnippet))`
Adding `company-tide` to the list doesn't work, and `company` is already there. What is the last one that's changing my settings, hmm.

**Comment by sooqua** [comment]
Just a quick question, is this a performance enhancement that some code is offloaded until I enter insert mode. If so, is it possible to hook into it?

**Comment by sooqua** [comment]
All of this combined doesn't work =\
```elisp
(after! js2-mode
  (set-company-backend! 'js2-mode '(company-tide :with company-yasnippet)))

(setq-hook! 'js2-mode-hook
  company-backends '((company-tide :with company-yasnippet)))
(setq-hook! 'company-mode-hook
  company-backends '((company-tide :with company-yasnippet)))
(setq-hook! 'tide-mode-hook
  company-backends '((company-tide :with company-yasnippet)))
(setq-hook! 'yas-minor-mode-hook
  company-backends '((company-tide :with company-yasnippet)))

(add-hook! 'js2-mode-hook
  (setq company-backends '((company-tide :with company-yasnippet))))
(add-hook! 'company-mode-hook
  (setq company-backends '((company-tide :with company-yasnippet))))
(add-hook! 'tide-mode-hook
  (setq company-backends '((company-tide :with company-yasnippet))))
(add-hook! 'yas-minor-mode-hook
  (setq company-backends '((company-tide :with company-yasnippet))))
```

**Comment by sooqua** [comment]
How do I do this? Because of [this](https://github.com/hlissner/doom-emacs/blob/develop/modules/completion/company/config.el#L22), I can't hook `js2-mode-hook` and be done with it, because something overrides my settings (apparently [this](https://github.com/ananthakumaran/tide/blob/master/tide.el#L1529)). The only thing that works is this:
```elisp
(add-hook! 'company-mode-hook
    (setq company-backends (append '((company-tide :with company-yasnippet)) '(company-tide))))
```
I thought adding `(company-tide)` at the end of the list will prevent it from adding it to the beginning:
> This macro inserts x at the front of the list stored in place, but only if x was not eql to any existing element of the list.

But it moves it to the beginning if I replace `company-mode-hook` with `js2-mode-hook`.

**Comment by sooqua** [comment]
Look at this ugly workaround, I can't do any better:
```elisp
(setq +js/js2-mode-buffers-list '())

(add-hook 'js2-mode-hook
          (lambda ()
            (cl-pushnew (current-buffer) +js/js2-mode-buffers-list)))

(add-hook 'company-mode-hook
          (lambda ()
            (let ((buf (current-buffer)))
              (when (member buf +js/js2-mode-buffers-list)
                (make-local-variable 'company-backends)
                (setq company-backends (append '((company-tide :with company-yasnippet)) '(company-tide)))
                (delq! buf +js/js2-mode-buffers-list)))))
```

**Comment by sooqua** [comment]
Yaay, found something less ugly:
```elisp
;; Enable yasnippet completion in js mode
(when (featurep! :lang javascript)
  (after! js2-mode
    (def-project-mode! +javascript-company-yasnippet-mode
      :modes '(web-mode js-mode coffee-mode css-mode haml-mode pug-mode)
      :add-hooks '(company-mode-hook)
      :on-enter
      (setq company-backends (append '((company-tide :with company-yasnippet)) '(company-tide))))))
```
