### ISSUE TITLE
[HOWTO] Disable " autofix in tex-mode

### ISSUE THREAD

**Issue by rsheasby** [hlissner/doom-emacs#1688]
It seems that tex-mode is automatically interpreting and replacing " characters with ``'' quotes for tex. I realize this is common practice, but in my case I really do need to disable this. I've tried the following:
```
(setq tex-open-quote "\"")
(setq tex-close-quote "\"")
```

But alas this is only a partial fix, as quotes inside a `\verb!!` are still modified. I've tried remapping the `"` key to disable this behavior entirely, as suggested here: https://emacs.stackexchange.com/a/52234/24221 but with still no luck. I've tried the same remap with `emacs -q` and it works perfectly, so I've narrowed the problem down to something included in doom-emacs.

What is the correct way to disable this functionality?

**System information**
<details><pre>
Generating Doom info...
- OS: gnu/linux (x86_64-redhat-linux-gnu)
- Shell: /usr/bin/fish
- Emacs: 26.2 (Apr 30, 2019)
- Doom: 2.0.9 (HEAD -> develop, origin/develop, origin/HEAD f754d4ff 2019-07-23 18:23:17 +0200)
- Graphic display: nil (daemon: nil)
- System features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LCMS2
- Details:
  ```elisp
  env bootstrapper: nil
  elc count: 0
  uname -a:  Linux 5.2.7-200.fc30.x86_64 #1 SMP Thu Aug 8 05:35:29 UTC 2019 x86_64
  modules:   (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor evil file-templates fold multiple-cursors rotate-text snippets :emacs dired electric vc :tools eval flycheck (lookup +docsets) magit :lang data emacs-lisp go markdown (org +dragndrop +ipython +pandoc +present) sh :config default)
  packages:  (ox-twbs (inertial-scroll :recipe (inertial-scroll :fetcher github :repo kiwanami/emacs-inertial-scroll)))
  exec-path: (/usr/local/bin /usr/local/sbin /usr/bin /usr/sbin /usr/libexec/emacs/26.2/x86_64-redhat-linux-gnu)
  ```
</pre></details>

**Comment by hlissner** [comment]
Have you tried `(setq TeX-quote-after-quote t)`? Doom installs and uses auctex.

**Comment by rsheasby** [comment]
Yep, I've tried that with no luck. I've even remapped `"` to `self-insert-command` and verified that it has mapped correctly with `C-h k "`, yet for some reason the quotes are still being changed. It does seem that `(setq TeX-quote-after-quote t)` does do *something*, as the quotes inserted when typing a quote are now `''` instead of ``` `` ```, but regardless, it's still not fixing the issue.

**Comment by hlissner** [comment]
It appears to be smartparens doing. This combination should work:

```elisp
(map! :after tex
      :map TeX-mode-map
      "\"" nil)

(after! smartparens-latex
  (sp-local-pair modes "``" "''" :actions :rem))
```

**Comment by rsheasby** [comment]
Hmm, when I add this:
```
(after! smartparens-latex
  (sp-local-pair modes "``" "''" :actions :rem))
```
It completely breaks all the tex/latex modes. I'm unable to enter any of them. When opening a tex file now, it just puts me in Fundamental mode, and if I try manually switch to one of the tex modes using `M-x`, it just shows the following error: `Symbol's value as variable is void: modes`
I've narrowed it down to that snippet by removing everything else except that. As soon as I remove that snippet, my tex modes work again.

**Comment by rsheasby** [comment]
Aha! After some playing around, I was able to get it working properly. Here's my full solution:
```
(map! :map tex-mode-map
      :i "\"" 'self-insert-command)

(after! smartparens-latex
  (sp-local-pair '(
                   tex-mode
                   plain-tex-mode
                   latex-mode
                   LaTeX-mode
                   ) "``" "''" :actions :rem))
```
For some reason it wasn't finding the `modes` variable you were referencing in your snippet... Manually describing all the tex modes makes it work properly. The map you added for the quote key also didn't seem to work, as it was still mapped to tex-insert-quote. I just modified it a bit and now it seems to work.
