### ISSUE TITLE
[BUG] Org agenda kills existing org buffers (sometimes)

### ISSUE THREAD

**Issue by siddharthshekar** [hlissner/doom-emacs#1689]
**Description**
Summoning `org-agenda` kills already open org buffers (sometimes).

This behavior is observed using existing keybindings such as `SPC o a t` as well as with a custom `org-agenda` command. I've found that this mostly happens when the file being opened is part of the files that agenda looks through. I've never been able to reproduce this when summoning org-agenda from a non-agenda file.

**Steps to reproduce**
1. Open an org file (that contains TODO tasks that will be read by `org-agenda`)
2. Summon `org-agenda`, e.g. by pressing `SPC o a t`

**System information**
<details><pre>
- OS: darwin (x86_64-apple-darwin18.6.0)
- Shell: /bin/bash
- Emacs: 27.0.50 (Jul 26, 2019)
- Doom: 2.0.9 (HEAD -> develop, origin/develop f754d4ff9 2019-07-23 18:23:17 +0200)
- Graphic display: t (daemon: nil)
- System features: RSVG IMAGEMAGICK GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS JSON PDUMPER LCMS2 GMP
- Details:
  ```elisp
  env bootstrapper: exec-path-from-shell
  elc count: 0
  uname -a:  Darwin 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64
  modules:   (:completion company (ivy +childframe) :ui deft doom doom-dashboard hl-todo modeline nav-flash ophints (popup +all +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor evil file-templates fold multiple-cursors rotate-text snippets :emacs dired electric vc :term eshell term :tools eval flycheck (lookup +docsets) lsp macos magit :lang data emacs-lisp latex markdown (org +dragndrop +ipython +pandoc +present) perl (python +lsp +pyenv) (sh +lsp +fish) :config literate (default +bindings +smartparens +snippets +evil-commands) sid)
  packages:  n/a
  exec-path: (~/.pyenv/shims ~/.pyenv/shims/ ~/bin/ ~/Library/Python/3.7/bin/ /usr/local/opt/python/libexec/bin/ /usr/local/bin/ /usr/bin/ /bin/ /usr/sbin/ /sbin/ ~/.pyenv/shims/ ~/bin/ ~/Library/Python/3.7/bin/ /usr/local/opt/python/libexec/bin/ ~/Documents/buildAnalysis/bin/ ~/Documents/buildAnalysis/bin/ /usr/local/Cellar/emacs-plus/HEAD-e3575ee/libexec/emacs/27.0.50/x86_64-apple-darwin18.6.0/)
  ```
</pre></details>

**Comment by siddharthshekar** [comment]
Observation: This seems to happen only when I invoke `org-agenda` from within a workspace containing the buffer that is about to be killed.

**Comment by hlissner** [comment]
[This](https://github.com/hlissner/doom-emacs/blob/straight/modules/lang/org/config.el#L466-L474) is the cause. Its purpose is to clean up buffers that `org-agenda` opens. This *should* leave buffers that were already opened alone though. I'll look into it.

**Comment by hlissner** [comment]
As of de223e7 this issue should be resolved. Let me know if that isn't the case and I will reopen it. Thanks for bringing it to my attention!
