### ISSUE TITLE
[QUESTION] Using avy-* instead of evil-avy-*

### ISSUE THREAD

**Issue by mjmeintjes** [hlissner/doom-emacs#1690]
Is there a reason for using avy-goto-char-timer instead of evil-avy-goto-char-timer at https://github.com/hlissner/doom-emacs/blob/c54509f99c6dfeb5f0aee1c76c719c2086cf4457/modules/config/default/%2Bevil-bindings.el#L165?

The evil variant seems to work better with evil-jump.

**Comment by hlissner** [comment]
No reason. I _think_ `evil-avy-goto-char-timer` didn't exist when the keybind was first introduced. I've changed it to use it in 18cefa0. Thanks for bringing it to my attention!
