### ISSUE TITLE
[BUG] clojure + common-lisp: can't load init.el, void-variable sly-contribs error

### ISSUE THREAD

**Issue by nesadi** [hlissner/doom-emacs#1691]
This is on the latest straight branch with a fresh init.el. If I uncomment clojure and common-lisp and refresh, consequently Emacs is no longer able to load the config with the following error:

> Warning (initialization): An error occurred while loading ‘/home/ameyer/.emacs.d/init.el’:
> 
> Error in an autoloads file: autoloads.pkg.el, (void-variable sly-contribs)

Running doom doctor gives me:

> Doom Doctor
> Emacs v26.2
> Doom v2.0.9 (nil)
> shell: /bin/zsh
> Compiled with:
>   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2
> uname -msrv:
>   Linux 5.2.8-1-MANJARO #1 SMP PREEMPT Fri Aug 9 19:34:20 UTC 2019 x86_64
> 
> Checking Emacs
>   Checking your Emacs version is 25.3 or newer...
>   Checking if your version of Emacs has changed recently...
>   Checking for Emacs config conflicts...
>   Checking for private config conflicts...
>   Checking for stale elc files...
> Checking your system...
> 
> Checking DOOM Emacs...
> Attempt to load DOOM failed
>   (autoloads.pkg.el (void-variable sly-contribs))

**Comment by hlissner** [comment]
I cannot reproduce this. The sly package autoloads the definition of sly-contribs. If it cannot find this definition, then either package failed to install correctly, or it wasn't indexed for whatever reason by Doom's autoloads scanner.

Try running `doom refresh -f` to forcibly regenerate your autoloads file (and install sly if it wasn't already).

**Comment by levitanong** [comment]
I had this issue, and running `doom refresh -f` did indeed fix this problem.

**Comment by Azd325** [comment]
I had the same issue. `doom refresh -f` was helping too.

I had first clojure enabled and and then later I enabled common-lisp the issue appeared.

**Comment by hlissner** [comment]
In that case I'll consider this resolved. If that isn't the case, let me know and I'll reopen the issue. Thanks for bringing it to my attention!
