### ISSUE TITLE
[BUG] Org todo buffer has a modeline that covers the buffer

### ISSUE THREAD

**Issue by BrandonShega** [hlissner/doom-emacs#1692]
When toggling the `TODO` portion of an item in org mode, the buffer that pops up to display which options you can set the todo to is covered by the modeline.  Someone in Discord mentioned that the modeline should probably not be there.

Steps to reproduce:

1. Open an org file
2. `SPC m t` to change the TODO tag

![Imgur](https://i.imgur.com/Pc3swj2.png)

OS: Mac OS Catalina
Emacs: 26.2.90
Doom: v2.0.9 (straight)

**Comment by flyingns** [comment]
I have the same problem.

**Comment by nbk9** [comment]
I have the same issue

OS: Manjaro Gnome
Emacs: 26.2.90
Doom: Doom v2.0.9 (develop)

**Comment by hlissner** [comment]
As of 43d80dc this should be resolved. Let me know if that isn't the case and I will reopen this issue. Thanks for bringing it to my attention!

**Comment by BrandonShega** [comment]
Thank you @hlissner !
