### ISSUE TITLE
[BUG]When I open the epub document, got an error: not: Wrong type argument: stringp, nil

### ISSUE THREAD

**Issue by flyingns** [hlissner/doom-emacs#1694]
**Describe the issue**
I read the epub document with nov and use the default settings of nov.
The `straight` branch is updated to f4a11fd43.

I got this error when I opened an epub document. However, the `develop` branch is completely normal and there is no error.

**emacs --debug-init:**
<details><pre>
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  file-exists-p(nil)
  (not (file-exists-p (buffer-file-name)))
  (and (not (file-exists-p (buffer-file-name))) (not buffer-read-only) (bobp) (eobp) (not (string-match-p "^ *\\*" (buffer-name))))
  (if (and (not (file-exists-p (buffer-file-name))) (not buffer-read-only) (bobp) (eobp) (not (string-match-p "^ *\\*" (buffer-name)))) (progn (let* ((rule (and t (cl-find-if (function +file-template-p) +file-templates-alist)))) (if rule (apply (function +file-templates--expand) rule) nil))))
  +file-templates-check-h()
  run-hooks(find-file-hook)
  #f(compiled-function (&optional error warn noauto after-find-file-from-revert-buffer nomodes) "Called after finding a file and by the default revert function.\nSets buffer mode, parses file-local and directory-local variables.\nOptional args ERROR, WARN, and NOAUTO: ERROR non-nil means there was an\nerror in reading the file.  WARN non-nil means warn if there\nexists an auto-save file more recent than the visited file.\nNOAUTO means don't mess with auto-save mode.\nFourth arg AFTER-FIND-FILE-FROM-REVERT-BUFFER is ignored\n(see `revert-buffer-in-progress-p' for similar functionality).\nFifth arg NOMODES non-nil means don't alter the file's modes.\nFinishes by calling the functions in `find-file-hook'\nunless NOMODES is non-nil." #<bytecode 0x40095583>)(nil t)
  apply(#f(compiled-function (&optional error warn noauto after-find-file-from-revert-buffer nomodes) "Called after finding a file and by the default revert function.\nSets buffer mode, parses file-local and directory-local variables.\nOptional args ERROR, WARN, and NOAUTO: ERROR non-nil means there was an\nerror in reading the file.  WARN non-nil means warn if there\nexists an auto-save file more recent than the visited file.\nNOAUTO means don't mess with auto-save mode.\nFourth arg AFTER-FIND-FILE-FROM-REVERT-BUFFER is ignored\n(see `revert-buffer-in-progress-p' for similar functionality).\nFifth arg NOMODES non-nil means don't alter the file's modes.\nFinishes by calling the functions in `find-file-hook'\nunless NOMODES is non-nil." #<bytecode 0x40095583>) (nil t))
  #f(advice-wrapper :before #f(compiled-function (&optional error warn noauto after-find-file-from-revert-buffer nomodes) "Called after finding a file and by the default revert function.\nSets buffer mode, parses file-local and directory-local variables.\nOptional args ERROR, WARN, and NOAUTO: ERROR non-nil means there was an\nerror in reading the file.  WARN non-nil means warn if there\nexists an auto-save file more recent than the visited file.\nNOAUTO means don't mess with auto-save mode.\nFourth arg AFTER-FIND-FILE-FROM-REVERT-BUFFER is ignored\n(see `revert-buffer-in-progress-p' for similar functionality).\nFifth arg NOMODES non-nil means don't alter the file's modes.\nFinishes by calling the functions in `find-file-hook'\nunless NOMODES is non-nil." #<bytecode 0x40095583>) doom--after-call-paren-h)(nil t)
  apply(#f(advice-wrapper :before #f(compiled-function (&optional error warn noauto after-find-file-from-revert-buffer nomodes) "Called after finding a file and by the default revert function.\nSets buffer mode, parses file-local and directory-local variables.\nOptional args ERROR, WARN, and NOAUTO: ERROR non-nil means there was an\nerror in reading the file.  WARN non-nil means warn if there\nexists an auto-save file more recent than the visited file.\nNOAUTO means don't mess with auto-save mode.\nFourth arg AFTER-FIND-FILE-FROM-REVERT-BUFFER is ignored\n(see `revert-buffer-in-progress-p' for similar functionality).\nFifth arg NOMODES non-nil means don't alter the file's modes.\nFinishes by calling the functions in `find-file-hook'\nunless NOMODES is non-nil." #<bytecode 0x40095583>) doom--after-call-paren-h) (nil t))
  #f(advice-wrapper :before #f(advice-wrapper :before #f(compiled-function (&optional error warn noauto after-find-file-from-revert-buffer nomodes) "Called after finding a file and by the default revert function.\nSets buffer mode, parses file-local and directory-local variables.\nOptional args ERROR, WARN, and NOAUTO: ERROR non-nil means there was an\nerror in reading the file.  WARN non-nil means warn if there\nexists an auto-save file more recent than the visited file.\nNOAUTO means don't mess with auto-save mode.\nFourth arg AFTER-FIND-FILE-FROM-REVERT-BUFFER is ignored\n(see `revert-buffer-in-progress-p' for similar functionality).\nFifth arg NOMODES non-nil means don't alter the file's modes.\nFinishes by calling the functions in `find-file-hook'\nunless NOMODES is non-nil." #<bytecode 0x40095583>) doom--after-call-paren-h) doom--after-call-recentf-h)(nil t)
  apply(#f(advice-wrapper :before #f(advice-wrapper :before #f(compiled-function (&optional error warn noauto after-find-file-from-revert-buffer nomodes) "Called after finding a file and by the default revert function.\nSets buffer mode, parses file-local and directory-local variables.\nOptional args ERROR, WARN, and NOAUTO: ERROR non-nil means there was an\nerror in reading the file.  WARN non-nil means warn if there\nexists an auto-save file more recent than the visited file.\nNOAUTO means don't mess with auto-save mode.\nFourth arg AFTER-FIND-FILE-FROM-REVERT-BUFFER is ignored\n(see `revert-buffer-in-progress-p' for similar functionality).\nFifth arg NOMODES non-nil means don't alter the file's modes.\nFinishes by calling the functions in `find-file-hook'\nunless NOMODES is non-nil." #<bytecode 0x40095583>) doom--after-call-paren-h) doom--after-call-recentf-h) (nil t))
  #f(advice-wrapper :before #f(advice-wrapper :before #f(advice-wrapper :before #f(compiled-function (&optional error warn noauto after-find-file-from-revert-buffer nomodes) "Called after finding a file and by the default revert function.\nSets buffer mode, parses file-local and directory-local variables.\nOptional args ERROR, WARN, and NOAUTO: ERROR non-nil means there was an\nerror in reading the file.  WARN non-nil means warn if there\nexists an auto-save file more recent than the visited file.\nNOAUTO means don't mess with auto-save mode.\nFourth arg AFTER-FIND-FILE-FROM-REVERT-BUFFER is ignored\n(see `revert-buffer-in-progress-p' for similar functionality).\nFifth arg NOMODES non-nil means don't alter the file's modes.\nFinishes by calling the functions in `find-file-hook'\nunless NOMODES is non-nil." #<bytecode 0x40095583>) doom--after-call-paren-h) doom--after-call-recentf-h) doom--after-call-saveplace-h)(nil t)
  apply(#f(advice-wrapper :before #f(advice-wrapper :before #f(advice-wrapper :before #f(compiled-function (&optional error warn noauto after-find-file-from-revert-buffer nomodes) "Called after finding a file and by the default revert function.\nSets buffer mode, parses file-local and directory-local variables.\nOptional args ERROR, WARN, and NOAUTO: ERROR non-nil means there was an\nerror in reading the file.  WARN non-nil means warn if there\nexists an auto-save file more recent than the visited file.\nNOAUTO means don't mess with auto-save mode.\nFourth arg AFTER-FIND-FILE-FROM-REVERT-BUFFER is ignored\n(see `revert-buffer-in-progress-p' for similar functionality).\nFifth arg NOMODES non-nil means don't alter the file's modes.\nFinishes by calling the functions in `find-file-hook'\nunless NOMODES is non-nil." #<bytecode 0x40095583>) doom--after-call-paren-h) doom--after-call-recentf-h) doom--after-call-saveplace-h) (nil t))
  #f(advice-wrapper :before #f(advice-wrapper :before #f(advice-wrapper :before #f(advice-wrapper :before #f(compiled-function (&optional error warn noauto after-find-file-from-revert-buffer nomodes) "Called after finding a file and by the default revert function.\nSets buffer mode, parses file-local and directory-local variables.\nOptional args ERROR, WARN, and NOAUTO: ERROR non-nil means there was an\nerror in reading the file.  WARN non-nil means warn if there\nexists an auto-save file more recent than the visited file.\nNOAUTO means don't mess with auto-save mode.\nFourth arg AFTER-FIND-FILE-FROM-REVERT-BUFFER is ignored\n(see `revert-buffer-in-progress-p' for similar functionality).\nFifth arg NOMODES non-nil means don't alter the file's modes.\nFinishes by calling the functions in `find-file-hook'\nunless NOMODES is non-nil." #<bytecode 0x40095583>) doom--after-call-paren-h) doom--after-call-recentf-h) doom--after-call-saveplace-h) doom--after-call-smartparens-h)(nil t)
  apply(#f(advice-wrapper :before #f(advice-wrapper :before #f(advice-wrapper :before #f(advice-wrapper :before #f(compiled-function (&optional error warn noauto after-find-file-from-revert-buffer nomodes) "Called after finding a file and by the default revert function.\nSets buffer mode, parses file-local and directory-local variables.\nOptional args ERROR, WARN, and NOAUTO: ERROR non-nil means there was an\nerror in reading the file.  WARN non-nil means warn if there\nexists an auto-save file more recent than the visited file.\nNOAUTO means don't mess with auto-save mode.\nFourth arg AFTER-FIND-FILE-FROM-REVERT-BUFFER is ignored\n(see `revert-buffer-in-progress-p' for similar functionality).\nFifth arg NOMODES non-nil means don't alter the file's modes.\nFinishes by calling the functions in `find-file-hook'\nunless NOMODES is non-nil." #<bytecode 0x40095583>) doom--after-call-paren-h) doom--after-call-recentf-h) doom--after-call-saveplace-h) doom--after-call-smartparens-h) (nil t))
  #f(advice-wrapper :before #f(advice-wrapper :before #f(advice-wrapper :before #f(advice-wrapper :before #f(advice-wrapper :before #f(compiled-function (&optional error warn noauto after-find-file-from-revert-buffer nomodes) "Called after finding a file and by the default revert function.\nSets buffer mode, parses file-local and directory-local variables.\nOptional args ERROR, WARN, and NOAUTO: ERROR non-nil means there was an\nerror in reading the file.  WARN non-nil means warn if there\nexists an auto-save file more recent than the visited file.\nNOAUTO means don't mess with auto-save mode.\nFourth arg AFTER-FIND-FILE-FROM-REVERT-BUFFER is ignored\n(see `revert-buffer-in-progress-p' for similar functionality).\nFifth arg NOMODES non-nil means don't alter the file's modes.\nFinishes by calling the functions in `find-file-hook'\nunless NOMODES is non-nil." #<bytecode 0x40095583>) doom--after-call-paren-h) doom--after-call-recentf-h) doom--after-call-saveplace-h) doom--after-call-smartparens-h) doom--after-call-so-long-h)(nil t)
  apply(#f(advice-wrapper :before #f(advice-wrapper :before #f(advice-wrapper :before #f(advice-wrapper :before #f(advice-wrapper :before #f(compiled-function (&optional error warn noauto after-find-file-from-revert-buffer nomodes) "Called after finding a file and by the default revert function.\nSets buffer mode, parses file-local and directory-local variables.\nOptional args ERROR, WARN, and NOAUTO: ERROR non-nil means there was an\nerror in reading the file.  WARN non-nil means warn if there\nexists an auto-save file more recent than the visited file.\nNOAUTO means don't mess with auto-save mode.\nFourth arg AFTER-FIND-FILE-FROM-REVERT-BUFFER is ignored\n(see `revert-buffer-in-progress-p' for similar functionality).\nFifth arg NOMODES non-nil means don't alter the file's modes.\nFinishes by calling the functions in `find-file-hook'\nunless NOMODES is non-nil." #<bytecode 0x40095583>) doom--after-call-paren-h) doom--after-call-recentf-h) doom--after-call-saveplace-h) doom--after-call-smartparens-h) doom--after-call-so-long-h) (nil t))
  #f(advice-wrapper :before #f(advice-wrapper :before #f(advice-wrapper :before #f(advice-wrapper :before #f(advice-wrapper :before #f(advice-wrapper :before #f(compiled-function (&optional error warn noauto after-find-file-from-revert-buffer nomodes) "Called after finding a file and by the default revert function.\nSets buffer mode, parses file-local and directory-local variables.\nOptional args ERROR, WARN, and NOAUTO: ERROR non-nil means there was an\nerror in reading the file.  WARN non-nil means warn if there\nexists an auto-save file more recent than the visited file.\nNOAUTO means don't mess with auto-save mode.\nFourth arg AFTER-FIND-FILE-FROM-REVERT-BUFFER is ignored\n(see `revert-buffer-in-progress-p' for similar functionality).\nFifth arg NOMODES non-nil means don't alter the file's modes.\nFinishes by calling the functions in `find-file-hook'\nunless NOMODES is non-nil." #<bytecode 0x40095583>) doom--after-call-paren-h) doom--after-call-recentf-h) doom--after-call-saveplace-h) doom--after-call-smartparens-h) doom--after-call-so-long-h) doom--after-call-undo-tree-h)(nil t)
  apply(#f(advice-wrapper :before #f(advice-wrapper :before #f(advice-wrapper :before #f(advice-wrapper :before #f(advice-wrapper :before #f(advice-wrapper :before #f(compiled-function (&optional error warn noauto after-find-file-from-revert-buffer nomodes) "Called after finding a file and by the default revert function.\nSets buffer mode, parses file-local and directory-local variables.\nOptional args ERROR, WARN, and NOAUTO: ERROR non-nil means there was an\nerror in reading the file.  WARN non-nil means warn if there\nexists an auto-save file more recent than the visited file.\nNOAUTO means don't mess with auto-save mode.\nFourth arg AFTER-FIND-FILE-FROM-REVERT-BUFFER is ignored\n(see `revert-buffer-in-progress-p' for similar functionality).\nFifth arg NOMODES non-nil means don't alter the file's modes.\nFinishes by calling the functions in `find-file-hook'\nunless NOMODES is non-nil." #<bytecode 0x40095583>) doom--after-call-paren-h) doom--after-call-recentf-h) doom--after-call-saveplace-h) doom--after-call-smartparens-h) doom--after-call-so-long-h) doom--after-call-undo-tree-h) (nil t))
  #f(advice-wrapper :before #f(advice-wrapper :before #f(advice-wrapper :before #f(advice-wrapper :before #f(advice-wrapper :before #f(advice-wrapper :before #f(advice-wrapper :before #f(compiled-function (&optional error warn noauto after-find-file-from-revert-buffer nomodes) "Called after finding a file and by the default revert function.\nSets buffer mode, parses file-local and directory-local variables.\nOptional args ERROR, WARN, and NOAUTO: ERROR non-nil means there was an\nerror in reading the file.  WARN non-nil means warn if there\nexists an auto-save file more recent than the visited file.\nNOAUTO means don't mess with auto-save mode.\nFourth arg AFTER-FIND-FILE-FROM-REVERT-BUFFER is ignored\n(see `revert-buffer-in-progress-p' for similar functionality).\nFifth arg NOMODES non-nil means don't alter the file's modes.\nFinishes by calling the functions in `find-file-hook'\nunless NOMODES is non-nil." #<bytecode 0x40095583>) doom--after-call-paren-h) doom--after-call-recentf-h) doom--after-call-saveplace-h) doom--after-call-smartparens-h) doom--after-call-so-long-h) doom--after-call-undo-tree-h) doom--after-call-ws-butler-h)(nil t)
  apply(#f(advice-wrapper :before #f(advice-wrapper :before #f(advice-wrapper :before #f(advice-wrapper :before #f(advice-wrapper :before #f(advice-wrapper :before #f(advice-wrapper :before #f(compiled-function (&optional error warn noauto after-find-file-from-revert-buffer nomodes) "Called after finding a file and by the default revert function.\nSets buffer mode, parses file-local and directory-local variables.\nOptional args ERROR, WARN, and NOAUTO: ERROR non-nil means there was an\nerror in reading the file.  WARN non-nil means warn if there\nexists an auto-save file more recent than the visited file.\nNOAUTO means don't mess with auto-save mode.\nFourth arg AFTER-FIND-FILE-FROM-REVERT-BUFFER is ignored\n(see `revert-buffer-in-progress-p' for similar functionality).\nFifth arg NOMODES non-nil means don't alter the file's modes.\nFinishes by calling the functions in `find-file-hook'\nunless NOMODES is non-nil." #<bytecode 0x40095583>) doom--after-call-paren-h) doom--after-call-recentf-h) doom--after-call-saveplace-h) doom--after-call-smartparens-h) doom--after-call-so-long-h) doom--after-call-undo-tree-h) doom--after-call-ws-butler-h) (nil t))
  #f(advice-wrapper :before #f(advice-wrapper :before #f(advice-wrapper :before #f(advice-wrapper :before #f(advice-wrapper :before #f(advice-wrapper :before #f(advice-wrapper :before #f(advice-wrapper :before #f(compiled-function (&optional error warn noauto after-find-file-from-revert-buffer nomodes) "Called after finding a file and by the default revert function.\nSets buffer mode, parses file-local and directory-local variables.\nOptional args ERROR, WARN, and NOAUTO: ERROR non-nil means there was an\nerror in reading the file.  WARN non-nil means warn if there\nexists an auto-save file more recent than the visited file.\nNOAUTO means don't mess with auto-save mode.\nFourth arg AFTER-FIND-FILE-FROM-REVERT-BUFFER is ignored\n(see `revert-buffer-in-progress-p' for similar functionality).\nFifth arg NOMODES non-nil means don't alter the file's modes.\nFinishes by calling the functions in `find-file-hook'\nunless NOMODES is non-nil." #<bytecode 0x40095583>) doom--after-call-paren-h) doom--after-call-recentf-h) doom--after-call-saveplace-h) doom--after-call-smartparens-h) doom--after-call-so-long-h) doom--after-call-undo-tree-h) doom--after-call-ws-butler-h) doom--after-call-git-commit-h)(nil t)
  apply(#f(advice-wrapper :before #f(advice-wrapper :before #f(advice-wrapper :before #f(advice-wrapper :before #f(advice-wrapper :before #f(advice-wrapper :before #f(advice-wrapper :before #f(advice-wrapper :before #f(compiled-function (&optional error warn noauto after-find-file-from-revert-buffer nomodes) "Called after finding a file and by the default revert function.\nSets buffer mode, parses file-local and directory-local variables.\nOptional args ERROR, WARN, and NOAUTO: ERROR non-nil means there was an\nerror in reading the file.  WARN non-nil means warn if there\nexists an auto-save file more recent than the visited file.\nNOAUTO means don't mess with auto-save mode.\nFourth arg AFTER-FIND-FILE-FROM-REVERT-BUFFER is ignored\n(see `revert-buffer-in-progress-p' for similar functionality).\nFifth arg NOMODES non-nil means don't alter the file's modes.\nFinishes by calling the functions in `find-file-hook'\nunless NOMODES is non-nil." #<bytecode 0x40095583>) doom--after-call-paren-h) doom--after-call-recentf-h) doom--after-call-saveplace-h) doom--after-call-smartparens-h) doom--after-call-so-long-h) doom--after-call-undo-tree-h) doom--after-call-ws-butler-h) doom--after-call-git-commit-h) (nil t))
  #f(advice-wrapper :before #f(advice-wrapper :before #f(advice-wrapper :before #f(advice-wrapper :before #f(advice-wrapper :before #f(advice-wrapper :before #f(advice-wrapper :before #f(advice-wrapper :before #f(advice-wrapper :before #f(compiled-function (&optional error warn noauto after-find-file-from-revert-buffer nomodes) "Called after finding a file and by the default revert function.\nSets buffer mode, parses file-local and directory-local variables.\nOptional args ERROR, WARN, and NOAUTO: ERROR non-nil means there was an\nerror in reading the file.  WARN non-nil means warn if there\nexists an auto-save file more recent than the visited file.\nNOAUTO means don't mess with auto-save mode.\nFourth arg AFTER-FIND-FILE-FROM-REVERT-BUFFER is ignored\n(see `revert-buffer-in-progress-p' for similar functionality).\nFifth arg NOMODES non-nil means don't alter the file's modes.\nFinishes by calling the functions in `find-file-hook'\nunless NOMODES is non-nil." #<bytecode 0x40095583>) doom--after-call-paren-h) doom--after-call-recentf-h) doom--after-call-saveplace-h) doom--after-call-smartparens-h) doom--after-call-so-long-h) doom--after-call-undo-tree-h) doom--after-call-ws-butler-h) doom--after-call-git-commit-h) doom--after-call-editorconfig-h)(nil t)
  apply(#f(advice-wrapper :before #f(advice-wrapper :before #f(advice-wrapper :before #f(advice-wrapper :before #f(advice-wrapper :before #f(advice-wrapper :before #f(advice-wrapper :before #f(advice-wrapper :before #f(advice-wrapper :before #f(compiled-function (&optional error warn noauto after-find-file-from-revert-buffer nomodes) "Called after finding a file and by the default revert function.\nSets buffer mode, parses file-local and directory-local variables.\nOptional args ERROR, WARN, and NOAUTO: ERROR non-nil means there was an\nerror in reading the file.  WARN non-nil means warn if there\nexists an auto-save file more recent than the visited file.\nNOAUTO means don't mess with auto-save mode.\nFourth arg AFTER-FIND-FILE-FROM-REVERT-BUFFER is ignored\n(see `revert-buffer-in-progress-p' for similar functionality).\nFifth arg NOMODES non-nil means don't alter the file's modes.\nFinishes by calling the functions in `find-file-hook'\nunless NOMODES is non-nil." #<bytecode 0x40095583>) doom--after-call-paren-h) doom--after-call-recentf-h) doom--after-call-saveplace-h) doom--after-call-smartparens-h) doom--after-call-so-long-h) doom--after-call-undo-tree-h) doom--after-call-ws-butler-h) doom--after-call-git-commit-h) doom--after-call-editorconfig-h) (nil t))
  #f(advice-wrapper :before #f(advice-wrapper :before #f(advice-wrapper :before #f(advice-wrapper :before #f(advice-wrapper :before #f(advice-wrapper :before #f(advice-wrapper :before #f(advice-wrapper :before #f(advice-wrapper :before #f(advice-wrapper :before #f(compiled-function (&optional error warn noauto after-find-file-from-revert-buffer nomodes) "Called after finding a file and by the default revert function.\nSets buffer mode, parses file-local and directory-local variables.\nOptional args ERROR, WARN, and NOAUTO: ERROR non-nil means there was an\nerror in reading the file.  WARN non-nil means warn if there\nexists an auto-save file more recent than the visited file.\nNOAUTO means don't mess with auto-save mode.\nFourth arg AFTER-FIND-FILE-FROM-REVERT-BUFFER is ignored\n(see `revert-buffer-in-progress-p' for similar functionality).\nFifth arg NOMODES non-nil means don't alter the file's modes.\nFinishes by calling the functions in `find-file-hook'\nunless NOMODES is non-nil." #<bytecode 0x40095583>) doom--after-call-paren-h) doom--after-call-recentf-h) doom--after-call-saveplace-h) doom--after-call-smartparens-h) doom--after-call-so-long-h) doom--after-call-undo-tree-h) doom--after-call-ws-butler-h) doom--after-call-git-commit-h) doom--after-call-editorconfig-h) doom--after-call-flycheck-h)(nil t)
  apply(#f(advice-wrapper :before #f(advice-wrapper :before #f(advice-wrapper :before #f(advice-wrapper :before #f(advice-wrapper :before #f(advice-wrapper :before #f(advice-wrapper :before #f(advice-wrapper :before #f(advice-wrapper :before #f(advice-wrapper :before #f(compiled-function (&optional error warn noauto after-find-file-from-revert-buffer nomodes) "Called after finding a file and by the default revert function.\nSets buffer mode, parses file-local and directory-local variables.\nOptional args ERROR, WARN, and NOAUTO: ERROR non-nil means there was an\nerror in reading the file.  WARN non-nil means warn if there\nexists an auto-save file more recent than the visited file.\nNOAUTO means don't mess with auto-save mode.\nFourth arg AFTER-FIND-FILE-FROM-REVERT-BUFFER is ignored\n(see `revert-buffer-in-progress-p' for similar functionality).\nFifth arg NOMODES non-nil means don't alter the file's modes.\nFinishes by calling the functions in `find-file-hook'\nunless NOMODES is non-nil." #<bytecode 0x40095583>) doom--after-call-paren-h) doom--after-call-recentf-h) doom--after-call-saveplace-h) doom--after-call-smartparens-h) doom--after-call-so-long-h) doom--after-call-undo-tree-h) doom--after-call-ws-butler-h) doom--after-call-git-commit-h) doom--after-call-editorconfig-h) doom--after-call-flycheck-h) (nil t))
  after-find-file(nil t)
  find-file-noselect-1(#<buffer Python.epub> "/Volumes/Noname/ebook/epub/Python.epub" nil nil "/Volumes/Noname/ebook/epub/Python.epub" (1811446 16777230))
  find-file-noselect("/Volumes/Noname/ebook/epub/Python.epub" nil nil nil)
  find-file("/Volumes/Noname/ebook/epub/Python.epub")
  counsel-find-file-action("/Volumes/Noname/ebook/epub/Python.epub")
  ivy-call()
  ivy-read("Find file: " read-file-name-internal :matcher counsel--find-file-matcher :initial-input nil :action counsel-find-file-action :preselect nil :require-match confirm-after-completion :history file-name-history :keymap (keymap (96 lambda (&optional arg) "nil (`nil')" (interactive "p") (if (string= "" ivy-text) (execute-kbd-macro (kbd "M-o b")) (self-insert-command arg))) (C-backspace . counsel-up-directory) (67108991 . counsel-up-directory)) :caller counsel-find-file)
  counsel--find-file-1("Find file: " nil counsel-find-file-action counsel-find-file)
  counsel-find-file()
  funcall-interactively(counsel-find-file)
  call-interactively(counsel-find-file nil nil)
  command-execute(counsel-find-file)
</pre></details>

**System information**
<details><pre>
emacs   version    26.2
doom    version    2.0.9
        build      HEAD -> straight, origin/straight f4a11fd4 2019-08-21 00:29:12 -0400
system  type       darwin
        config     x86_64-apple-darwin17.7.0
        shell      /bin/zsh
</pre></details>

**Comment by hlissner** [comment]
This was a regression caused by fb619bdb0. I've fixed it in 8f1de7c. Let me know if that isn't the case and I'll reopen this issue. Thanks for bringing it to my attention.
