### ISSUE TITLE
[BUG] "ambiguous argument 'origin/master'" error on 'doom update'

### ISSUE THREAD

**Issue by flyingns** [hlissner/doom-emacs#1697]
**Describe the issue**
`straight` branch `8f01abeb` commit, `doom update` error:

<details><pre>
  .
  .
  .
  . 12%
  .
  .
  .
  . 18%
  . 24%
  . 29%
  . 35%
  . 41%
  . 47%
  . 53%
  . 59%

Output:
/dev/null

--------------------------------------------------

There was an unexpected error:
  error (error)
Wrong type argument: listp, "There were errors:

   - ensime: ((error Failed to run \"git\"; see buffer *straight-process*) fatal: ambiguous argument 'origin/master': unknown revision or path not in the working tree.
  Use '--' to separate paths from revisions, like this:
  'git <command> [<revision>...] -- [<file>...]')"
</pre></details>

**System information**
<details><pre>
emacs   version    26.2
doom    version    2.0.9
        build      HEAD -> straight, origin/straight 8f01abeb
</pre></details>

**Comment by hlissner** [comment]
Just this once, you'll need to delete `~/.emacs.d/.local/straight/repo/straight.el` and run `doom refresh`. I changed the recipe for straight, and as of yet, Doom's package manager can't quite handle changes in recipe for packages yet, much less for core packages like straight.el.

**Comment by flyingns** [comment]
Mine is not `~/.emacs.d/.local/straight/repo/straight.el`, it is `~/.emacs.d/.local/straight/repos/straight.el/`.

I deleted it, and `doom refresh`, and then `doom update`, still report error.

**Comment by rassie** [comment]
Can confirm, deleting `.local` completely still doesn't solve the problem.

**Comment by rassie** [comment]
The problem seems to be that `ensime/ensime-emacs` doesn't have a `master` branch.

**Comment by flyingns** [comment]
The fault has been resolved, thank you for everything.
