### ISSUE TITLE
[HOWTO] Get kubenetes-el popup defaults to motion mode

### ISSUE THREAD

**Issue by zhuhaow** [hlissner/doom-emacs#1700]
I tried to set up https://github.com/chrisbarrett/kubernetes-el.

With a few configurations, everything seems good except for the key bindings.

```
(def-package! kubernetes
  :config
  (set-popup-rule!
    "^\\*kubernetes" :ignore t))

(def-package! kubernetes-evil
  :after kubernetes)
```

The problem is, the [kubernetes-evil](https://github.com/chrisbarrett/kubernetes-el/blob/master/kubernetes-evil.el) binds keys to motion state while I don't know why, but the default state for the pop up is normal state. I checked with  `SPC h v evil-state`.

In init.el I have `(evil +everywhere)`, removing `+everywhere` makes no difference.

Any help would be appreciated.

**Comment by hlissner** [comment]
Sorry for the late response. Are you still experiencing this issue? Judging from these in kubernetes-evil:

```elisp
(evil-set-initial-state 'kubernetes-mode 'motion)
(evil-set-initial-state 'kubernetes-display-thing-mode 'motion)
(evil-set-initial-state 'kubernetes-log-line-mode 'motion)
(evil-set-initial-state 'kubernetes-logs-mode 'motion)
(evil-set-initial-state 'kubernetes-overview-mode 'motion)
```

They should always start in motion state. Try to see if you can reproduce it in vanilla Emacs (the [Doom Sandbox](https://gist.github.com/hlissner/3910fcf5ef14ab77657f269ba9b37f94) might help with that).

If you can reproduce it there then the issue should be raised the kubernetes-evil guys.

**Comment by zhuhaow** [comment]
I tried start the sandbox with 
```
(use-package kubernetes
  :commands (kubernetes-overview))

(use-package kubernetes-evil
  :after kubernetes)
```
and C-c C-d, and everything worked as expected.

Even if I switched to motion state by call `evil-motion-state`, the kep binding still did not working. I checked key map [kubernetes-mode-map](https://github.com/chrisbarrett/kubernetes-el/blob/master/kubernetes-evil.el#L39) and the binding was there.

**Comment by hlissner** [comment]
Do you see any errors or warnings in \*Messages\*? (see `SPC h e`). I tried your code and I discovered:

1. if I launch `M-x kubernetes-overview`, `kubernetes-evil` does not get loaded. Perhaps due to errors. Since I do not have a kubernetes environment, I cannot accurately test this.

2. If I load it with `M-x load-library RET kubernetes`, then `kubernetes-evil` loads correctly.

**Comment by zhuhaow** [comment]
Yes. I notice there is error "Error in private config: config.el, (file-missing Cannot open load file No such file or directory kubernetes-evil)". 

How can I load kubernetes-evil in this case?

**Comment by hlissner** [comment]
Do you have both of these in packages.el?

```elisp
(package! kubernetes)
(package! kubernetes-evil)
```

And did you run `doom refresh` after adding them?

(Could you also include your `M-x doom/info`?)

**Comment by zhuhaow** [comment]
Adding `(package! kubernetes-evil)` fixed it!

Thank you!
