### ISSUE TITLE
[REQUEST] Making doom-core into a package

### ISSUE THREAD

**Issue by wurosh** [hlissner/doom-emacs#1708]
**Describe the feature**
Separating doom bootstrap code from the super optimized doom utilities in doom core would make them accessible to the wider community.

**Extended explanation**
- There are a lot of handy defuns and macros in doom. They're the perfect Emacs glue. A bunch of people I encountered (including myself, I switch between doom and my own config) flat out copy paste `map!`, `def-package!` etc. for their utility, because doom core makes certain assumptions about the config that are only true when using doom directly.
- Removing those assumptions (i.e. putting them in separate files), such as `doom-private-dir`, the doom package management system (e.g. I prefer using `straight.el`), and adding dependency information into the docs, so MELPA can work it's magic, would make these utilities separately installable.
- It conforms closely to Doom's *opinionated, but not stubborn* mantra, namely the "Use as little or as much of Doom as you like." part.
- I do not want to actually change any of the code (even the features you disabled such as `:ensure` could stay disabled, keeping the Doom spirit is key), merely re-arrange it, add annotations, and make a MELPA recipe. 

Would you be interested in a PR like this at all? Of course, given that I would be hacking on the very heart of Doom, I would make sure every change I make is absolutely necessary, and triple confirm that is the case with you.

**Comment by tonylotts** [comment]
Nice idea.  In theory, this would make it possible to declaratively install Doom as a package, using the Nix package manager.

**Comment by hlissner** [comment]
Sorry for the late response. I don't mind extracting bits and bobs from Doom's core, but I don't think it would make a good MELPA package, and if it became one, I don't think Doom Emacs would use it. I doubt I would even maintain it.

Reason being, the assumptions my code base makes affords me a lot of leeway, as a maintainer. I'm only one guy. Doom's core only has to accommodate Doom Emacs users, and the scope that that entails. To create a package out of Doom's core will inevitably require an effort to generalize it; it would need to accommodate more use cases and environments -- and requests to do so will creep in -- I already have my hands full maintaining Doom, and don't want to (or have time to) expand its scope.

Additionally, the folks who manage MELPA will frown upon the rampant advising Doom does, our unique naming conventions, and the fact that it wouldn't be a conventional package -- they themselves may disqualify it, unless we conform; work I'd like to avoid.

> There are a lot of handy defuns and macros in doom. They're the perfect Emacs glue. A bunch of people I encountered (including myself, I switch between doom and my own config) flat out copy paste map!, def-package! etc. for their utility, because doom core makes certain assumptions about the config that are only true when using doom directly.

I don't agree. There are a number of packages that provide APIs that are quite similar, from general.el, to dash.el, to use-package itself, etc -- and none of those are bogged down by Doom's assumptions. Some of Doom's API makes no sense outside of doom, like `def-package!` -- its only purpose is to no-op if a package is disabled via Doom's package manager.

In any case, I don't think Doom is the answer here.

> Removing those assumptions (i.e. putting them in separate files), such as doom-private-dir, the doom package management system (e.g. I prefer using straight.el), and adding dependency information into the docs, so MELPA can work it's magic, would make these utilities separately installable.

Doom uses straight.el now, by the way. That aside, I'm not sure how exactly you'd pull that off. I can't imagine any scenario where dismantling Doom's opinionated web won't be at the expense of Doom Emacs users, performance-wise. Many of Doom's bigger optimizations are tightly coupled with its command-line interface (bin/doom), with our extensions to `use-package`, and the very assumptions that assume Doom's core will only ever be used from within a Doom Emacs config.

You'd either have a massive project ahead of you, lifting Doom's nervous system out of its body, or be forced to clip its proverbial wings, which will split the two projects further apart and (in my opinion) diminish the value of Doom's-core-as-a-package.

> It conforms closely to Doom's opinionated, but not stubborn mantra, namely the "Use as little or as much of Doom as you like." part.

I think Doom accomplishes this already. Install Doom and disable all its modules. Done, all you have left is Doom's core. You could use Doom's package management system if you wanted, or don't. You could use Doom's conventions and API, or don't. You could write your own library of modules, use Doom's or somewhere in between.

> Would you be interested in a PR like this at all? Of course, given that I would be hacking on the very heart of Doom, I would make sure every change I make is absolutely necessary, and triple confirm that is the case with you.

I'm interested to know what you had in mind, I just cannot imagine this would be feasible. If there are particular parts of Doom's core you'd like to see become their own packages, I'd be happy to look into it (e.g. #1895).

**Comment by jjzmajic** [comment]
Honestly, your argument leaves me convinced. The 2 features I personally find most appealing are the following (let me know which ones are worth opening issues for):

- The `use-package` handlers for `:defer-incrementally`  and `after-call`. Especially `:defer-incrementally`
- The convenient multiple `:infix` specification of `map!`. `general-def` only supports one per call and is significantly more verbose. I just find map more readable with `:description` and such.

There were also the dooms handler abstractions, but I'm actually fairly happy with how [my implementation](https://gitlab.com/jjzmajic/handle) worked out. Lmk if you have any suggestions for improvements if you're interested.
