### ISSUE TITLE
[BUG]In helm, when I create or edit a link by pressing C-c C-l, there is no description prompt.

### ISSUE THREAD

**Issue by flyingns** [hlissner/doom-emacs#1710]
**Describe the issue**
In helm, when I create or edit a link by pressing C-c C-l, there is no description prompt.

Ivy does not have this problem.

**Comment by hlissner** [comment]
As of 87c6e89 this issue should be resolved. Let me know if that isn't the case and I'll reopen this. Thanks for bringing it to my attention!
