### ISSUE TITLE
[BUG] Clojure Repl choosing the wrong buffer

### ISSUE THREAD

**Issue by UndeadKernel** [hlissner/doom-emacs#1714]
The function `+eval/open-repl-other-window` in clojure does not work as expected: The first time the function is called, a REPL buffer is opened as expected. Subsequent calls to the function do not open or focus the REPL buffer. Instead, the point of the current buffer is moved to the end.

This happens because `+clojure/repl` (called by `+eval/open-repl-other-window`) is supposed to return the buffer of the REPL. Instead, `clojure/repl` return the current buffer.

The issue is not as simple to solve (that's why this issue) given that `clojure/repl` creates the REPL asynchronously. `+eval/open-repl-other-window` expects a REPL buffer synchronously.

Any clue, @hlissner, how this could be addressed?

**Comment by hlissner** [comment]
It appears `cider-jack-in` returns the repl process, so does this work for you?

```elisp
(defadvice! +clojure-fix-repl-a (&optional arg)
  :override #'+clojure/repl
  (interactive "P")
  (process-buffer (cider-jack-in arg)))
```

**Comment by UndeadKernel** [comment]
Clojure uses a client-server architecture for the repl. It creates a repl server buffer and possibly multiple client repl buffers. The function `cider-repl-create` is responsible for creating the buffer for the client. The function in turn is called by `cider-nrepl-connect`.
