### ISSUE TITLE
[BUG] let*: Error in a Doom module: "modules/completion/ivy/config.el", (void-function map!)

### ISSUE THREAD

**Issue by seldomworks** [hlissner/doom-emacs#1724]
On a fresh install of doom, today, I am seeing an error in the ivy module.
Emacs is installed using brew emacs-plus

Here is info from messages
For information about GNU Emacs and the GNU system, type C-h C-a.
let*: Error in a Doom module: "modules/completion/ivy/config.el", (void-function map!)
Error running timer ‘require’: (void-function define-key!)
Failed to load deferred package ivy: (void-function define-key!)
C-x C-g is undefined
Quit
Mark set

Output from doom run --debug-init is below
<details><pre>
Debugger entered--Lisp error: (void-function map!)
  (map! [remap apropos] (function counsel-apropos) [remap bookmark-jump] (function counsel-bookmark) [remap describe-face] (function counsel-faces) [remap describe-function] (function counsel-describe-function) [remap describe-variable] (function counsel-describe-variable) [remap describe-bindings] (function counsel-descbinds) [remap set-variable] (function counsel-set-variable) [remap execute-extended-command] (function counsel-M-x) [remap find-file] (function counsel-find-file) [remap find-library] (function counsel-find-library) [remap info-lookup-symbol] (function counsel-info-lookup-symbol) [remap imenu] (function counsel-imenu) [remap recentf-open-files] (function counsel-recentf) [remap org-capture] (function counsel-org-capture) [remap swiper] (function counsel-grep-or-swiper) [remap evil-ex-registers] (function counsel-evil-registers) [remap yank-pop] (function counsel-yank-pop))
  eval-buffer(#<buffer  *load*-302735> nil "/Users/anish/.emacs.d/modules/completion/ivy/config.el" nil t)  ; Reading at buffer position 11453
  load-with-code-conversion("/Users/anish/.emacs.d/modules/completion/ivy/config.el" "/Users/anish/.emacs.d/modules/completion/ivy/config.el" t nil)
  load("/Users/anish/.emacs.d/modules/completion/ivy/config" t nil)
  (condition-case e (load (expand-file-name "config" (plist-get plist :path)) t nil) ((debug doom-error) (signal (car e) (cdr e))) ((debug error) (let* ((source (file-name-sans-extension (expand-file-name "config" (plist-get plist :path)))) (err (cond ((file-in-directory-p source doom-core-dir) (cons ... doom-core-dir)) ((file-in-directory-p source doom-private-dir) (cons ... doom-private-dir)) ((cons ... doom-emacs-dir))))) (signal (car err) (list (file-relative-name (concat source ".el") (cdr err)) e)))))
  (let ((doom--current-module key) (doom--current-flags (plist-get plist :flags))) (condition-case e (load (expand-file-name "config" (plist-get plist :path)) t nil) ((debug doom-error) (signal (car e) (cdr e))) ((debug error) (let* ((source (file-name-sans-extension (expand-file-name "config" ...))) (err (cond (... ...) (... ...) (...)))) (signal (car err) (list (file-relative-name (concat source ".el") (cdr err)) e))))))
  (closure ((force-p) t) (key plist) (let ((doom--current-module key) (doom--current-flags (plist-get plist :flags))) (condition-case e (load (expand-file-name "config" (plist-get plist :path)) t nil) ((debug doom-error) (signal (car e) (cdr e))) ((debug error) (let* ((source (file-name-sans-extension ...)) (err (cond ... ... ...))) (signal (car err) (list (file-relative-name ... ...) e)))))))((:completion . ivy) (:flags nil :path "/Users/anish/.emacs.d/modules/completion/ivy/"))
  maphash((closure ((force-p) t) (key plist) (let ((doom--current-module key) (doom--current-flags (plist-get plist :flags))) (condition-case e (load (expand-file-name "config" (plist-get plist :path)) t nil) ((debug doom-error) (signal (car e) (cdr e))) ((debug error) (let* ((source ...) (err ...)) (signal (car err) (list ... e))))))) #<hash-table equal 33/44 0x410bb88d>)
  (progn (maphash (function (lambda (key plist) (let ((doom--current-module key) (doom--current-flags (plist-get plist :flags))) (condition-case e (load (expand-file-name "config" ...) t nil) ((debug doom-error) (signal ... ...)) ((debug error) (let* ... ...)))))) doom-modules))
  (if doom-modules (progn (maphash (function (lambda (key plist) (let ((doom--current-module key) (doom--current-flags ...)) (condition-case e (load ... t nil) (... ...) (... ...))))) doom-modules)))
  (if noninteractive nil (if doom-modules (progn (maphash (function (lambda (key plist) (let (... ...) (condition-case e ... ... ...)))) doom-modules))) (run-hook-wrapped (quote doom-init-modules-hook) (function doom-try-run-hook)) (condition-case e (load (expand-file-name "config" doom-private-dir) t nil) ((debug doom-error) (signal (car e) (cdr e))) ((debug error) (let* ((source (file-name-sans-extension (expand-file-name "config" doom-private-dir))) (err (cond (... ...) (... ...) (...)))) (signal (car err) (list (file-relative-name (concat source ".el") (cdr err)) e))))))
  (progn (if doom-modules (progn (maphash (function (lambda (key plist) (let (... ...) (condition-case e ... ... ...)))) doom-modules))) (run-hook-wrapped (quote doom-before-init-modules-hook) (function doom-try-run-hook)) (if noninteractive nil (if doom-modules (progn (maphash (function (lambda (key plist) (let ... ...))) doom-modules))) (run-hook-wrapped (quote doom-init-modules-hook) (function doom-try-run-hook)) (condition-case e (load (expand-file-name "config" doom-private-dir) t nil) ((debug doom-error) (signal (car e) (cdr e))) ((debug error) (let* ((source (file-name-sans-extension ...)) (err (cond ... ... ...))) (signal (car err) (list (file-relative-name ... ...) e)))))))
  (if (condition-case e (load (expand-file-name "init" doom-private-dir) t nil) ((debug doom-error) (signal (car e) (cdr e))) ((debug error) (let* ((source (file-name-sans-extension (expand-file-name "init" doom-private-dir))) (err (cond (... ...) (... ...) (...)))) (signal (car err) (list (file-relative-name (concat source ".el") (cdr err)) e))))) (progn (if doom-modules (progn (maphash (function (lambda (key plist) (let ... ...))) doom-modules))) (run-hook-wrapped (quote doom-before-init-modules-hook) (function doom-try-run-hook)) (if noninteractive nil (if doom-modules (progn (maphash (function (lambda ... ...)) doom-modules))) (run-hook-wrapped (quote doom-init-modules-hook) (function doom-try-run-hook)) (condition-case e (load (expand-file-name "config" doom-private-dir) t nil) ((debug doom-error) (signal (car e) (cdr e))) ((debug error) (let* ((source ...) (err ...)) (signal (car err) (list ... e))))))))
  (progn (setq doom-init-modules-p t doom-modules nil) (if (condition-case e (load (expand-file-name "init" doom-private-dir) t nil) ((debug doom-error) (signal (car e) (cdr e))) ((debug error) (let* ((source (file-name-sans-extension ...)) (err (cond ... ... ...))) (signal (car err) (list (file-relative-name ... ...) e))))) (progn (if doom-modules (progn (maphash (function (lambda ... ...)) doom-modules))) (run-hook-wrapped (quote doom-before-init-modules-hook) (function doom-try-run-hook)) (if noninteractive nil (if doom-modules (progn (maphash (function ...) doom-modules))) (run-hook-wrapped (quote doom-init-modules-hook) (function doom-try-run-hook)) (condition-case e (load (expand-file-name "config" doom-private-dir) t nil) ((debug doom-error) (signal (car e) (cdr e))) ((debug error) (let* (... ...) (signal ... ...))))))))
  (if (or force-p (not doom-init-modules-p)) (progn (setq doom-init-modules-p t doom-modules nil) (if (condition-case e (load (expand-file-name "init" doom-private-dir) t nil) ((debug doom-error) (signal (car e) (cdr e))) ((debug error) (let* ((source ...) (err ...)) (signal (car err) (list ... e))))) (progn (if doom-modules (progn (maphash (function ...) doom-modules))) (run-hook-wrapped (quote doom-before-init-modules-hook) (function doom-try-run-hook)) (if noninteractive nil (if doom-modules (progn (maphash ... doom-modules))) (run-hook-wrapped (quote doom-init-modules-hook) (function doom-try-run-hook)) (condition-case e (load (expand-file-name "config" doom-private-dir) t nil) ((debug doom-error) (signal ... ...)) ((debug error) (let* ... ...))))))))
  doom-initialize-modules()
  (let ((args (cdr (cdr (cdr command-line-args))))) (while (condition-case nil (progn (string-prefix-p "-" (car args))) (error nil)) (let* ((val (car-safe (prog1 args (setq args ...))))) (cond ((member val (quote ("--help" "-h"))) (setq args (cons "help" args))) ((member val (quote ("--debug" "-d"))) (setenv "DEBUG" "1") (message "Debug mode on")) ((member val (quote ("--insecure" "-i"))) (setenv "INSECURE" "1") (message "Insecure mode on")) ((member val (quote ("--private" "-p"))) (setq doom-private-dir (expand-file-name (concat ... "/"))) (setenv "DOOMDIR" doom-private-dir) (message "DOOMDIR changed to %s" doom-private-dir) (or (file-directory-p doom-private-dir) (message "Warning: %s does not exist" (abbreviate-file-name doom-private-dir)))) ((member val (quote ("--local" "-l"))) (setq doom-local-dir (expand-file-name (concat ... "/"))) (setenv "DOOMLOCALDIR" doom-local-dir) (message "DOOMLOCALDIR changed to %s" doom-local-dir)) ((member val (quote ("--emacsd" "-e"))) (setq user-emacs-directory (expand-file-name (concat ... "/"))) (message "Emacs directory changed to %s" user-emacs-directory)) ((member val (quote ("--yes" "-y"))) (setenv "YES" "1") (message "Auto-yes mode on")) (t nil)))) (if (file-directory-p user-emacs-directory) nil (error "%s does not exist" user-emacs-directory)) (load (expand-file-name "core/core.el" user-emacs-directory) nil (quote nomessage)) (doom-initialize (quote force-p)) (doom-initialize-modules) (cond ((not noninteractive) (doom-run-all-startup-hooks-h)) ((and (not (cdr args)) (member (car args) (quote ("help" "h")))) (usage)) ((not args) (print! (error "No command detected.\n")) (usage)) ((require (quote core-cli)) (let ((default-directory user-emacs-directory)) (setq argv nil) (condition-case e (doom-dispatch (car args) (cdr args)) (user-error (print! (error "%s\n") (error-message-string e)) (print! (yellow "See 'doom help %s' for documentation on this command.") (car args))) ((debug error) (message "--------------------------------------------------\n") (message "There was an unexpected error:") (message "  %s (%s)" (get ... ...) (car e)) (let (... item) (while --dolist-tail-- ... ... ...)) (if debug-on-error nil (message ...) (signal ... e))))))))
  eval-buffer(#<buffer  *load*> nil "/Users/anish/.emacs.d/bin/doom" nil t)  ; Reading at buffer position 5501
  load-with-code-conversion("/Users/anish/.emacs.d/bin/doom" "/Users/anish/.emacs.d/bin/doom" nil t)
  load("/Users/anish/.emacs.d/bin/doom" nil t)
  command-line-1(("--no-splash" "-l" "bin/doom"))
  command-line()
  normal-top-level()
</pre></details>

**Steps to reproduce**
git clone https://github.com/hlissner/doom-emacs ~/.emacs.d
~/.emacs.d/bin/doom install
doom run

**System information**
<details><pre>
<details>

```
emacs   version    26.2
	features   JPEG RSVG IMAGEMAGICK GLIB NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2
	build      Apr 17, 2019
	buildopts  (--disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus/26.2/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus/26.2 --with-xml2 --without-dbus --with-gnutls --with-imagemagick --with-modules --with-rsvg --with-ns --disable-ns-self-contained)
doom    version    2.0.9
	build      HEAD -> develop, origin/develop, origin/HEAD b141b4bb 2019-08-28 16:49:06 -0400
system  type       darwin
	config     x86_64-apple-darwin18.5.0
	shell      /bin/zsh
	uname      Darwin 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64
	path       (~/google-cloud-sdk/bin ~/.emacs.d/bin /Library/TeX/texbin/ /Library/TeX/texbin/ ~/anaconda3/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /opt/X11/bin /usr/texbin ~ /usr/local/Cellar/emacs-plus/26.2/libexec/emacs/26.2/x86_64-apple-darwin18.5.0/)
config  envfile    envvar-file
	elc-files  0
	modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor evil file-templates fold multiple-cursors rotate-text snippets :emacs dired electric vc :tools eval flycheck (lookup +docsets) magit :lang data emacs-lisp markdown (org +dragndrop +ipython +pandoc +present) sh :config default)
	packages   (n/a)
	elpa-packages (n/a)
```
</details>
</pre></details>

**Comment by hlissner** [comment]
This appears to be an issue with `doom run`. Does Doom run fine if run normally? Via `emacs`?

**Comment by hlissner** [comment]
As of 081f09a this should be resolved. Let me know if that isn't the case and I'll reopen the issue. Thanks for bringing it to my attention!

**Comment by seldomworks** [comment]
Thank you @hlissner! It did run fine via emacs and doom run works correctly after a doom upgrade
