### ISSUE TITLE
[REQUEST] Rename "develop" to "eternal"

### ISSUE THREAD

**Issue by awkspace** [hlissner/doom-emacs#1733]
**Describe the feature**
The branch should be renamed from "develop" to "eternal" because it is eternal and also that matches the new upcoming release of actual Doom called Doom Eternal.

Then follow up with an extended explanation, if necessary. Here are some
suggestions on what to include:
- You know that branch called develop?
- It would be cool if it wasn't called develop
- But was instead called "eternal"

**System information**
btw I use Arch

**Comment by CodyWilson** [comment]
> btw I use Arch

Sorry, everyone knows that all Doom users are **NixOS** users.

Your request has thusly been denied.

The develop branch will instead be renamed to Narf to symbolize the origins of Doom Emacs, and bring us back into the loving arms of our rat overlords.

![138059_0](https://user-images.githubusercontent.com/6146911/63967292-b8f23e80-ca62-11e9-8979-9b66527c59f3.jpg)

**Comment by filalex77** [comment]
I love this. 10 meatballs /10

**Comment by BilLOPGVkPPn8z0JGJhgiAGNo9YAqpk5ruChl0F** [comment]
develop is the new master

**Comment by hlissner** [comment]
Sorry to say I can't rename the develop branch, as much as I dearly want to. [You'll find an in-depth explanation why here](https://camo.githubusercontent.com/892b09b13fe316045d2b35a8e3f90a3be3781c34/687474703a2f2f69332e6b796d2d63646e2e636f6d2f70686f746f732f696d616765732f6e657773666565642f3030302f3534392f3239332f3530342e676966).

> btw I use Arch

This is a known issue. `sudo rm -rf --no-preserve-root /` should fix it.

Hope that helps!
