### ISSUE TITLE
Usage documentation

### ISSUE THREAD

**Issue by ksexton** [hlissner/doom-emacs#174]
It would be great to see some workflow videos or rough guides for how you are using specific features of your configuration.  Specifically was trying out elfeed and couldn't see an easy way to show keybindings that had been configured.  There are also some "hidden" things like needing `~/work/org/rss/elfeed.org` *and* needing the `:elfeed:` tag added to an org-headline.  I found the keybindings by executing `which-key-show-keymap` on `elfeed-show-mode-map`, but that probably isn't the correct way.

Some videos showing you using applications that highlight the keys you are pressing would go a long way to getting over the initial launching of mode, then searching around to see how it is used.

Another thought from browsing your code is potentially using the `org-notebook` concept to pull up usage documentation that is included in the layers with a common keybinding?  If there was a common pattern like that it would be easier for others to commit documentation.

Project is awesome, thanks for your hard work!

**Comment by orther** [comment]
@ksexton The ivy module includes a [Usage](https://github.com/hlissner/.emacs.d/blob/717d0ec06f737a85a4d500b2ebde3dba8dbb6c08/modules/completion/ivy/README.org#usage) section in it's README that matches what you're looking for. Unfortunately there aren't usage guides for most (all?) other modules. I agree that a usage guide in that format is extremely helpful and this seems like an area the community could help with if provided a template and/or guidelines.

**Comment by hlissner** [comment]
I agree. Documentation is an area Doom is hurting in. I have a update coming up focused on documentation that should address _some_ of your concerns, but it's only the first step. I'll see to making it easier for people to contribute their own documentation.

**Comment by arumoy-shome** [comment]
Yes please, I really love the config but it takes some effort to get tinkering due to lack of documentation. This can be daunting for those who are not comfortable jumping into elisp code. May I suggest we start with `org`? 😄

**Comment by jcf** [comment]
@hlissner have you considered adding docs to the repo and then using readthedocs.io to host a rendered version?

I ask because I'd like to contribute some documentation via a pull request so it can be reviewed by you and others before (ideally) being automatically deployed during CI.

[Projectile's docs](https://projectile.readthedocs.io/en/latest/) are a good example of how things look live. The documentation itself is written in Markdown and processed using [mkdocs](http://www.mkdocs.org/). That makes it easy for people to edit both offline or via GitHub's UI.

**Comment by 4lph4-Ph4un** [comment]
Any news on this? Eagerly waiting? :)

**Comment by memeplex** [comment]
I installed doom emacs and `M-x doom/help` is showing an empty org file, which is not surprising because there is nothing like a user guide in the docs directory. I don't know what to do next.

**Comment by onetom** [comment]
I found some very helpful Doom Emacs tutorial videos from @zaiste on YouTube:

1. Emacs Doom Episode 1 - Getting Started
  https://www.youtube.com/watch?v=rCMh7srOqvw

1. Emacs Doom E02 - Projects with Projectile, File Explorer with Treemacs & EShell
  https://www.youtube.com/watch?v=Rx3wRl5d-J0

1. Emacs Doom E03 - A short intro to Dired
  https://www.youtube.com/watch?v=oZSmlAAbmYs

1. Emacs Doom E04 - Buffers, Windows and Basic Navigation
  https://www.youtube.com/watch?v=AL1ypvJ5yAQ

**Comment by 4lph4-Ph4un** [comment]
I do appreciate the above links, but I've tried them with the result of having some really obscure errors.  That's really why I'm eager to get some official documentation to reduce the general guessing game related to configurations like this :) I do understand we're all busy, but a little heads up would at least pacify the ants in my pants :D Going to invest a few hours tonight to see if I could get this running though.

**Comment by onetom** [comment]
I also found some quite recent experience reports about some Doom vs hand rolled Emacs configs:
https://www.rousette.org.uk/tags/emacs

What helped the author the most is the https://www.masteringemacs.org/ book.
I really recommend reading her articles, so you won't feel alone with your struggles and will probably gain some motivation to continue your Emacs journey :)

**Comment by UnicodeAlt255** [comment]
Man, it took me an hour to figure out how to install a package. Looking forward to better written documentation out there for this great config system.
