### ISSUE TITLE
doom install failure with void-variable error[BUG] 

### ISSUE THREAD

**Issue by zqtheu** [hlissner/doom-emacs#1749]
**Describe the issue**
I clone the repo and install follow the instruction from main page, it gives me the error:

<details><pre>
~/.emacs.d/bin/doom install -i
Using a proxy for https...
Debugger entered--Lisp error: (void-variable </html>)
  eval(</html> nil)
  elisp--eval-last-sexp(t)
  eval-last-sexp(t)
  eval-print-last-sexp()
  (save-current-buffer (set-buffer (url-retrieve-synchronously (format "https://raw.githubusercontent.com/raxod502/straight.el/%s/install.el" straight-repository-branch) (quote silent) (quote inhibit-cookies))) (goto-char (point-max)) (eval-print-last-sexp))
  (if (or (require (quote straight) nil t) (file-readable-p bootstrap-file)) nil (save-current-buffer (set-buffer (url-retrieve-synchronously (format "https://raw.githubusercontent.com/raxod502/straight.el/%s/install.el" straight-repository-branch) (quote silent) (quote inhibit-cookies))) (goto-char (point-max)) (eval-print-last-sexp)))
  (if (featurep (quote straight)) nil (if (or (require (quote straight) nil t) (file-readable-p bootstrap-file)) nil (save-current-buffer (set-buffer (url-retrieve-synchronously (format "https://raw.githubusercontent.com/raxod502/straight.el/%s/install.el" straight-repository-branch) (quote silent) (quote inhibit-cookies))) (goto-char (point-max)) (eval-print-last-sexp))) (load bootstrap-file nil t))
  (let* ((user-emacs-directory straight-base-dir) (bootstrap-file (doom-path straight-base-dir "straight/repos/straight.el/straight.el")) (bootstrap-version 5)) (make-directory (doom-path straight-base-dir "straight/build") (quote parents)) (if (featurep (quote straight)) nil (if (or (require (quote straight) nil t) (file-readable-p bootstrap-file)) nil (save-current-buffer (set-buffer (url-retrieve-synchronously (format "https://raw.githubusercontent.com/raxod502/straight.el/%s/install.el" straight-repository-branch) (quote silent) (quote inhibit-cookies))) (goto-char (point-max)) (eval-print-last-sexp))) (load bootstrap-file nil t)))
  doom-ensure-straight()
  (if (fboundp (quote straight--reset-caches)) nil (doom-ensure-straight) (require (quote straight)))
  (progn (if doom-debug-mode (progn (let ((inhibit-message (active-minibuffer-window))) (message #("DOOM Initializing straight" 0 5 (face font-lock-comment-face)))))) (setq doom-init-packages-p t) (if (fboundp (quote straight--reset-caches)) nil (doom-ensure-straight) (require (quote straight))) (straight--reset-caches) (mapc (function straight-use-recipes) doom-core-package-sources) (straight-register-package (cons (quote straight) (cons (quote :type) (cons (quote git) (cons (quote :host) (cons (quote github) (cons ... ...))))))) (mapc (function straight-use-package) doom-core-packages) (if noninteractive (progn (add-hook (quote kill-emacs-hook) (function doom--finalize-straight)))))
  (if (or force-p (not doom-packages)) (progn (if doom-debug-mode (progn (let ((inhibit-message (active-minibuffer-window))) (message #("DOOM Initializing straight" 0 5 (face font-lock-comment-face)))))) (setq doom-init-packages-p t) (if (fboundp (quote straight--reset-caches)) nil (doom-ensure-straight) (require (quote straight))) (straight--reset-caches) (mapc (function straight-use-recipes) doom-core-package-sources) (straight-register-package (cons (quote straight) (cons (quote :type) (cons (quote git) (cons (quote :host) (cons ... ...)))))) (mapc (function straight-use-package) doom-core-packages) (if noninteractive (progn (add-hook (quote kill-emacs-hook) (function doom--finalize-straight))))))
  doom-initialize-packages(force-p)
  (if (and core-autoloads-p (not force-p)) (progn (eval-after-load (quote package) (function (lambda nil (require (quote core-packages))))) (eval-after-load (quote straight) (function (lambda nil (require (quote core-packages)) (doom-initialize-packages))))) (mapc (doom-rpartial (function load) (quote noerror) (quote nomessage)) (file-expand-wildcards (concat doom-core-dir "autoload/*.el"))) (let ((--dolist-tail-- (list doom-local-dir doom-etc-dir doom-cache-dir doom-elpa-dir))) (while --dolist-tail-- (let ((dir (car --dolist-tail--))) (if (file-directory-p dir) nil (make-directory dir (quote parents))) (setq --dolist-tail-- (cdr --dolist-tail--))))) (require (quote core-packages)) (doom-initialize-packages force-p))
  (let ((core-autoloads-p (doom-load-autoloads-file doom-autoload-file)) (pkg-autoloads-p (if noninteractive nil (doom-load-autoloads-file doom-package-autoload-file)))) (if (and core-autoloads-p (not force-p)) (progn (eval-after-load (quote package) (function (lambda nil (require (quote core-packages))))) (eval-after-load (quote straight) (function (lambda nil (require (quote core-packages)) (doom-initialize-packages))))) (mapc (doom-rpartial (function load) (quote noerror) (quote nomessage)) (file-expand-wildcards (concat doom-core-dir "autoload/*.el"))) (let ((--dolist-tail-- (list doom-local-dir doom-etc-dir doom-cache-dir doom-elpa-dir))) (while --dolist-tail-- (let ((dir (car --dolist-tail--))) (if (file-directory-p dir) nil (make-directory dir (quote parents))) (setq --dolist-tail-- (cdr --dolist-tail--))))) (require (quote core-packages)) (doom-initialize-packages force-p)) (if (or (and core-autoloads-p pkg-autoloads-p) force-p noninteractive) nil (if core-autoloads-p nil (message "Your Doom core autoloads file is missing")) (if pkg-autoloads-p nil (message "Your package autoloads file is missing")) (user-error "Run `bin/doom refresh' to generate them")))
  (progn (setq doom-init-p t) (setq exec-path doom--initial-exec-path load-path doom--initial-load-path process-environment doom--initial-process-environment) (require (quote core-lib)) (require (quote core-modules)) (if (and (or (display-graphic-p) (daemonp)) (file-exists-p doom-env-file)) (progn (doom-load-envvars-file doom-env-file))) (let ((core-autoloads-p (doom-load-autoloads-file doom-autoload-file)) (pkg-autoloads-p (if noninteractive nil (doom-load-autoloads-file doom-package-autoload-file)))) (if (and core-autoloads-p (not force-p)) (progn (eval-after-load (quote package) (function (lambda nil (require ...)))) (eval-after-load (quote straight) (function (lambda nil (require ...) (doom-initialize-packages))))) (mapc (doom-rpartial (function load) (quote noerror) (quote nomessage)) (file-expand-wildcards (concat doom-core-dir "autoload/*.el"))) (let ((--dolist-tail-- (list doom-local-dir doom-etc-dir doom-cache-dir doom-elpa-dir))) (while --dolist-tail-- (let ((dir ...)) (if (file-directory-p dir) nil (make-directory dir ...)) (setq --dolist-tail-- (cdr --dolist-tail--))))) (require (quote core-packages)) (doom-initialize-packages force-p)) (if (or (and core-autoloads-p pkg-autoloads-p) force-p noninteractive) nil (if core-autoloads-p nil (message "Your Doom core autoloads file is missing")) (if pkg-autoloads-p nil (message "Your package autoloads file is missing")) (user-error "Run `bin/doom refresh' to generate them"))))
  (if (or force-p (not doom-init-p)) (progn (setq doom-init-p t) (setq exec-path doom--initial-exec-path load-path doom--initial-load-path process-environment doom--initial-process-environment) (require (quote core-lib)) (require (quote core-modules)) (if (and (or (display-graphic-p) (daemonp)) (file-exists-p doom-env-file)) (progn (doom-load-envvars-file doom-env-file))) (let ((core-autoloads-p (doom-load-autoloads-file doom-autoload-file)) (pkg-autoloads-p (if noninteractive nil (doom-load-autoloads-file doom-package-autoload-file)))) (if (and core-autoloads-p (not force-p)) (progn (eval-after-load (quote package) (function (lambda nil ...))) (eval-after-load (quote straight) (function (lambda nil ... ...)))) (mapc (doom-rpartial (function load) (quote noerror) (quote nomessage)) (file-expand-wildcards (concat doom-core-dir "autoload/*.el"))) (let ((--dolist-tail-- (list doom-local-dir doom-etc-dir doom-cache-dir doom-elpa-dir))) (while --dolist-tail-- (let (...) (if ... nil ...) (setq --dolist-tail-- ...)))) (require (quote core-packages)) (doom-initialize-packages force-p)) (if (or (and core-autoloads-p pkg-autoloads-p) force-p noninteractive) nil (if core-autoloads-p nil (message "Your Doom core autoloads file is missing")) (if pkg-autoloads-p nil (message "Your package autoloads file is missing")) (user-error "Run `bin/doom refresh' to generate them")))))
  doom-initialize(force-p)
  (if (not noninteractive) (progn (load (expand-file-name "init.el" user-emacs-directory) nil (quote nomessage)) (doom-run-all-startup-hooks-h)) (load (expand-file-name "core/core.el" user-emacs-directory) nil (quote nomessage)) (doom-initialize (quote force-p)) (doom-initialize-modules) (cond ((and (not (cdr args)) (member (car args) (quote ("help" "h")))) (usage)) ((not args) (print! (error "No command detected.\n")) (usage)) ((require (quote core-cli)) (let ((default-directory user-emacs-directory)) (setq argv nil) (condition-case e (doom-dispatch (car args) (cdr args)) (user-error (print! (error "%s\n") (error-message-string e)) (print! (yellow "See 'doom help %s' for documentation on this command.") (car args))) ((debug error) (message "--------------------------------------------------\n") (message "There was an unexpected error:") (message "  %s (%s)" (get ... ...) (car e)) (let (... item) (while --dolist-tail-- ... ... ...)) (if debug-on-error nil (message ...) (signal ... e))))))))
  (let ((args (cdr (cdr (cdr command-line-args))))) (while (condition-case nil (progn (string-prefix-p "-" (car args))) (error nil)) (let* ((val (car-safe (prog1 args (setq args ...))))) (cond ((member val (quote ("--help" "-h"))) (let nil (setq args (cons "help" args)))) ((member val (quote ("--debug" "-d"))) (let nil (setenv "DEBUG" "1") (message "Debug mode on"))) ((member val (quote ("--insecure" "-i"))) (let nil (setenv "INSECURE" "1") (message "Insecure mode on"))) ((member val (quote ("--private" "-p"))) (let nil (setq doom-private-dir (expand-file-name ...)) (setenv "DOOMDIR" doom-private-dir) (message "DOOMDIR changed to %s" doom-private-dir) (or (file-directory-p doom-private-dir) (message "Warning: %s does not exist" ...)))) ((member val (quote ("--local" "-l"))) (let nil (setq doom-local-dir (expand-file-name ...)) (setenv "DOOMLOCALDIR" doom-local-dir) (message "DOOMLOCALDIR changed to %s" doom-local-dir))) ((member val (quote ("--emacsd" "-e"))) (let nil (setq user-emacs-directory (expand-file-name ...)) (message "Emacs directory changed to %s" user-emacs-directory))) ((member val (quote ("--yes" "-y"))) (let nil (setenv "YES" "1") (message "Auto-yes mode on"))) (t nil)))) (if (file-directory-p user-emacs-directory) nil (error "%s does not exist" user-emacs-directory)) (if (not noninteractive) (progn (load (expand-file-name "init.el" user-emacs-directory) nil (quote nomessage)) (doom-run-all-startup-hooks-h)) (load (expand-file-name "core/core.el" user-emacs-directory) nil (quote nomessage)) (doom-initialize (quote force-p)) (doom-initialize-modules) (cond ((and (not (cdr args)) (member (car args) (quote ("help" "h")))) (usage)) ((not args) (print! (error "No command detected.\n")) (usage)) ((require (quote core-cli)) (let ((default-directory user-emacs-directory)) (setq argv nil) (condition-case e (doom-dispatch (car args) (cdr args)) (user-error (print! ... ...) (print! ... ...)) ((debug error) (message "--------------------------------------------------\n") (message "There was an unexpected error:") (message "  %s (%s)" ... ...) (let ... ...) (if debug-on-error nil ... ...))))))))
  eval-buffer(#<buffer  *load*> nil "/home/qingtiaz/.emacs.d/bin/doom" nil t)  ; Reading at buffer position 5670
  load-with-code-conversion("/home/qingtiaz/.emacs.d/bin/doom" "/home/qingtiaz/.emacs.d/bin/doom" nil t)
  load("/home/qingtiaz/.emacs.d/bin/doom" nil t t)
  command-line-1(("-scriptload" "/home/qingtiaz/.emacs.d/bin/doom" "--" "install" "-i"))
  command-line()
  normal-top-level()

**System information**
<details><pre>
got the same error as above if run doom info
</pre></details>

**Comment by hlissner** [comment]
What do the following shell commands output?

- `curl https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el`

- `emacs --batch --eval '(with-current-buffer (url-retrieve-synchronously "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el") (prin1 (buffer-string)))'`

**Comment by zqtheu** [comment]
curl https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el
;;; install.el --- Install straight.el from scratch -*- lexical-binding: t -*-

;; Caution: this file contains copious amounts of magic. You have been
;; warned.

;; For the sake of sanity, here is the issue. We want to install
;; straight.el, but to do that we need to figure out what repository
;; to install it from. That requires parsing the recipe that the user
;; has provided, if any. But not only is that logic a part of
;; straight.el itself, but the logic changes depending on the version
;; of straight.el. It would seem to be impossible to get straight.el
;; to correctly install any version of itself, without hardcoding the
;; repository. Not so!
;;
;; We start out by making sure that a recipe version identifier is
;; saved in the version lockfiles whenever they are saved. We put the
;; version identifier in the lockfiles because if the lockfiles are
;; absent, then we are just installing the latest version of
;; straight.el anyway, so there is no need for the version identifier
;; in that case.
;;
;; Then we look for lockfiles, and determine the version identifier.
;; This is automatically translated into a branch name for
;; straight.el. The idea is that while there are lots of revisions of
;; straight.el, only a few actually change the interpretation of
;; recipe fetch keywords. And so we can actually use a rather
;; coarse-grained selection of revisions to get all the versions of
;; straight.el that we need in order to parse any given recipe format.
;;
;; After we get the appropriate branch name, we directly download that
;; branch's revision of straight.el (the file) from the official
;; GitHub repository, raxod502/straight.el. Now, one of the goals of
;; this implementation is that forking straight.el does not require
;; any changes to this file as long as you do not make divergent
;; changes to the interpretation of recipe fetch keywords. The fact
;; that we download from the source rather than whatever fork is
;; specified does not actually violate this goal, if you think about
;; it. If the fork *does* make divergent changes to recipe
;; interpretation, then all it needs to do is update the version
;; identifier in `straight-freeze-versions', tag a new branch with a
;; unique version identifier, and override the hardcoded
;; raxod502/straight.el to the fork (this last part being necessary
;; because otherwise the new branch could not be found; all previous
;; branches would still be available, though).
;;
;; After we get a copy of straight.el, it's just a matter of using it
;; to parse the recipe for straight.el itself, taking into account all
;; user-set variables. But of course evaluating straight.el will mess
;; up the environment, so we have to do this in a child Emacs
;; instance.
;;
;; Previous versions of straight.el expected a symlink for
;; bootstrap.el, in order for the bootstrap snippet to be able to
;; identify the name of the local repository for straight.el. I
;; decided later that this was more trouble than it was worth, and
;; that users wishing to rename the repository can reasonably be
;; expected to update their bootstrap snippet. We still create the
;; symlink, though, for backwards compatibility (this script should
;; work for all versions of straight.el, present and past).
;;
;; IMPORTANT: When referring to newly introduced variables in
;; straight.el, *always* use `bound-and-true-p' so as to avoid
;; regressions with old versions of straight.el that did not define
;; those variables; see
;; <https://github.com/raxod502/straight.el/issues/407>.

;; We have to wrap everything in a single form so that this file can
;; be evaluated with `eval-print-last-sexp', rather than
;; `eval-buffer', since the latter forcibly swallows all errors(!) and
;; turns them into warnings.
(progn
  (message "Bootstrapping straight.el...")

  ;; Any errors in this Emacs go directly to the user's init-file and
  ;; abort init. Errors in the child Emacs spawned below create a
  ;; non-zero exit code, and are re-thrown.
  (let ((min-version "24.4"))
    (when (version< emacs-version min-version)
      (error (concat "straight.el requires at least Emacs %s, "
                     "but you are running Emacs %s")
             min-version emacs-version)))

  ;; Load some libraries.
  (require 'cl-lib)
  (require 'url-http)

  ;; Because `url-http' is weird, it doesn't properly define its
  ;; variables. So we have to do this.
  (defvar url-http-end-of-headers)
  (defvar url-http-response-status)

  (let ((version nil)
        (straight-profiles (if (boundp 'straight-profiles)
                               straight-profiles
                             '((nil . "default.el"))))
        (straight-install-dir (or (bound-and-true-p straight-base-dir)
                                  user-emacs-directory)))
    ;; The only permissible error here is for a lockfile to be absent
    ;; entirely. Anything else triggers an abort so that we don't
    ;; accidentally do something the user doesn't expect (like if they
    ;; forked straight.el and made incompatible divergent changes to
    ;; the recipe specification, and forgot to update which repository
    ;; their init-file downloaded install.el from).
    (dolist (lockfile-name (mapcar #'cdr straight-profiles))
      (let ((lockfile-path (concat straight-install-dir
                                   "straight/versions/"
                                   lockfile-name)))
        (when (file-exists-p lockfile-path)
          (condition-case nil
              (with-temp-buffer
                (insert-file-contents-literally lockfile-path)
                (read (current-buffer))
                (let ((alleged-version (read (current-buffer))))
                  (cond
                   (version
                    (unless (eq alleged-version version)
                      (error (concat "Incompatible recipe versions specified "
                                     "in version lockfiles: %S and %S")
                             version alleged-version)))
                   ((keywordp alleged-version)
                    (setq version alleged-version))
                   (t (error
                       (concat "Invalid recipe version specified "
                               "in version lockfile: %S")
                       alleged-version)))))
            ;; Prevent end-of-file errors from being swallowed (they
            ;; are ignored by default by the debugger).
            (end-of-file
             (error "Malformed version lockfile: %S" lockfile-name))))))
    (unless version
      ;; If no lockfile present, use latest version.
      (setq version :alpha))
    (with-current-buffer
        (url-retrieve-synchronously
         (format
          (concat "https://raw.githubusercontent.com/"
                  "raxod502/straight.el/install/%s/straight.el")
          (substring (symbol-name version) 1))
         'silent 'inhibit-cookies)
      ;; In case of 404, that means the version identifier is unknown.
      ;; This will happen when I screw up, or if the user forks
      ;; straight.el and changes the version identifier, but forgets
      ;; to push a corresponding branch and override the repository
      ;; here.
      (unless (equal url-http-response-status 200)
        (error "Unknown recipe version: %S" version))
      ;; Delete the evil HTTP headers.
      (delete-region (point-min) url-http-end-of-headers)
      ;; All of the following code is actually executed by the child
      ;; Emacs.
      (goto-char (point-min))
      (print
       `(progn
          ;; Pass relevant variables into the child Emacs, if they
          ;; have been set.
          ,@(let* ((vars nil)
                   (regexps '("bootstrap-version"
                              "straight-[a-z-]+"
                              "user-emacs-directory"))
                   (regexp (format "^\\(%s\\)$"
                                   (mapconcat #'identity regexps "\\|"))))
              (mapatoms
               (lambda (sym)
                 (when (and (boundp sym)
                            (string-match-p regexp (symbol-name sym))
                            (not (string-match-p "--" (symbol-name sym))))
                   (push sym vars))))
              (mapcar (lambda (var)
                        `(setq ,var ',(symbol-value var)))
                      vars)))
       (current-buffer))
      (goto-char (point-max))
      (print
       `(progn
          ;; Don't worry, this recipe will be overridden by
          ;; `straight-recipe-overrides' if that variable has been
          ;; set. We're just mirroring bootstrap.el. (But note that
          ;; `:files' doesn't have to be specified, since we're
          ;; skipping the build phase.)
          (straight-use-package-no-build
           `(straight :type git :host github
                      :repo ,(format
                              "%s/straight.el"
                              (or (bound-and-true-p straight-repository-user)
                                  "raxod502"))
                      :branch ,(or (bound-and-true-p
                                    straight-repository-branch)
                                   "master")))
          (unless (and (boundp 'bootstrap-version)
                       (integerp bootstrap-version)
                       (>= bootstrap-version 3))
            ;; Make a bootstrap.el symlink, for backwards compatibility
            ;; (bootstrap snippets versioned 2 and lower expect this
            ;; symlink to exist).
            (let* ((recipe (gethash "straight" straight--recipe-cache))
                   (local-repo (plist-get recipe :local-repo))
                   ;; This is a relative symlink. It won't break if you
                   ;; (for some silly reason) move your
                   ;; `user-emacs-directory'.
                   (link-target (concat "repos/" local-repo "/bootstrap.el"))
                   (link-name (concat straight-install-dir
                                      "straight/bootstrap.el")))
              (ignore-errors
                ;; If it's a directory, the linking will fail. Just let
                ;; the user deal with it in that case, since they are
                ;; doing something awfully weird.
                (delete-file link-name))
              ;; Unfortunately, there appears to be no way to get
              ;; `make-symbolic-link' to overwrite an existing file,
              ;; like 'ln -sf'. Providing the OK-IF-ALREADY-EXISTS
              ;; argument just makes it fail silently in the case of an
              ;; existing file. That's why we have to `delete-file'
              ;; above.
              (if (bound-and-true-p straight-use-symlinks)
                  (if (executable-find "cmd")
                      (call-process "cmd" nil nil nil "/c" "mklink"
                                    (subst-char-in-string ?/ ?\\ link-name)
                                    (subst-char-in-string ?/ ?\\ link-target))
                    (make-symbolic-link link-target link-name))
                (with-temp-file link-name
                  (print
                   `(load (expand-file-name
                           ,link-target (file-name-directory load-file-name))
                          nil 'nomessage)
                   (current-buffer)))))))
       (current-buffer))
      (let ((temp-file (make-temp-file "straight.el~")))
        (write-region nil nil temp-file nil 'silent)
        (with-temp-buffer
          (unless (= 0
                     (call-process
                      ;; Taken with love from package `restart-emacs'.
                      (let ((emacs-binary-path
                             (expand-file-name
                              invocation-name invocation-directory))
                            (runemacs-binary-path
                             (when (memq system-type '(windows-nt ms-dos))
                               (expand-file-name
                                "runemacs.exe" invocation-directory))))
                        (if (and runemacs-binary-path
                                 (file-exists-p runemacs-binary-path))
                            runemacs-binary-path
                          emacs-binary-path))
                      nil '(t t) nil
                      "--batch" "--no-window-system" "--quick"
                      "--load" temp-file))
            (error "straight.el bootstrap failed: %s" (buffer-string)))))))

  (message "Bootstrapping straight.el...done"))

emacs --batch --eval '(with-current-buffer (url-retrieve-synchronously "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el") (prin1 (buffer-string)))'
Using a proxy for https...
Contacting host: 135.245.48.34:8000
"HTTP/1.1 502 Bad Gateway
Connection: close
Content-Type: text/html
Cache-Control: no-cache
Content-Length: 2210

<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01//EN\">
<html>
  <head>
    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">
    <style type=\"text/css\">
      html,body{
        height:100%;
        padding:0;
        margin:100;
      }
      .oc{
        display:table;
        width:100%;
        height:100%;
      }
      .ic{
        display:table-cell;
        vertical-align:middle;
        height:100%;
      }
      div.msg{
        display:block;
        border:1px solid #30c;
        padding:0;
        width:500px;
        font-family:helvetica,sans-serif;
        margin:10px auto;
      }
      h1{
        font-weight:bold;
        color:#fff;
        font-size:14px;
        margin:0;
        padding:2px;
        text-align:center;
        background: #30c;
      }
      p{
        font-size:12px;
        margin:15px auto;
        width:75%;
        font-family:helvetica,sans-serif;
        text-align:left;
      }
    </style>
    <title>
      502 Bad Gateway
    </title>
  </head>
  <body>
    <div class=\"oc\">
      <div class=\"ic\">
        <div class=\"msg\">
          <h1>
            502 Bad Gateway
          </h1>
          <p>
            <p>
              The proxy server reported that an error occurred while trying to access the website.  Please click 
              <u>
                <a href=\"javascript:history.back()\">
                  here
                </a>
              </u>
              to return to the previous page.
            </p>
            <p>
              Proxy service: ussvg9101-prx001
            </p>
            <p>
              URL = https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el
              <br />
              <br/>
              Client IP: 135.242.107.116
              <br/>
              Server IP: 199.232.4.133
              <br/>
              User name: 
              <br/>
              Group name: 
              <br/>
              Proxy name: ussvg9101-prx001
              <br/>
              Proxy internal IP: 10.202.5.26
              <br />
              Proxy external IP: 135.245.48.86
            </p>
          </p>
        </div>
      </div>
    </div>
  </body>
</html>

is that caused by behind a proxy?
how to set the proxy when install?

**Comment by hlissner** [comment]
This is indeed an issue with your proxy. You'll have to either turn off your proxy while installing Doom or address the issue with your proxy.

I'm not familiar with proxies and Emacs, but here are a few variables you could look into. You'd have to set them in `~/.doom.d/init.el` for them to take effect while `bin/doom` is installing packages:

- `url-proxy-services` (maybe set to `nil`?)
- `url-using-proxy` (maybe set to `nil`?)

**Comment by zqtheu** [comment]
Thanks so much!
It can't connect without the proxy. 
It's interesting that why the curl can work but emacs can't work behind this proxy.
I will try to install doom in at home and copy .emacs.d to workstation. 
Do you think it's a correct way?

**Comment by hlissner** [comment]
If your proxy blocks raw.githubusercontent.com, you could try installing straight manually (as discussed in #1766), like so:

```sh
mkdir -p ~/.emacs.d/.local/straight/repos
git clone -b develop https://github.com/raxod502/straight.el ~/.emacs.d/.local/straight/repos/straight.el
```

Then you can use `doom refresh` (assuming your proxy doesn't block github.com)
