### ISSUE TITLE
peculiar error

### ISSUE THREAD

**Issue by chriskaukis** [hlissner/doom-emacs#175]
As mentioned in the Reddit post I would try again and post an issue. I spent a couple hours trying to get it running again. Ran into Melpa issues for every Emacs in Homebrew except one, but after that was working I get this `peculiar error` message.

```
~/.emacs.d ❯❯❯ DEBUG=1 make doctor                                                                                                                                                                                                   master ✱
DOOM Doctor
Running Emacs v25.2.1, commit e1f7efdf1d73af0da596c7c449c0de2224e33e8a

Compiled with:
  JPEG NOTIFY ACL LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES
uname -a:
  Darwin Chriss-Mac 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15
  17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64

Attempt to load DOOM: success! Loaded v2.0.4
Revision e1f7efdf1d73af0da596c7c449c0de2224e33e8a

----

peculiar error
make: *** [doctor] Error 255
```

Any suggestions? would love to help get this worked out for me (and you).

**Comment by orther** [comment]
I had that same `peculiar error` after installing **emacs-plus** from Homebrew today (which I had installed in the past). 

After running `brew reinstall emacs-plus` that error went away. If you still get error I recommend running `brew doctor` and look for anything related to *emacs* or *imagemagick*.

Here's the emacs-plus issue related to this: https://github.com/d12frosted/homebrew-emacs-plus/issues/44

**Comment by orther** [comment]
I'm curious @chriskaukis did you ever get this figured out?

**Comment by chriskaukis** [comment]
@orther I gave up and switched back to Spacemacs for now. I'll give it a go soon again though.

**Comment by hlissner** [comment]
I believe this has to do with gnutls. Assuming you're installing emacs through the `emacs` recipe via homebrew, you need to supply `--with-gnutls` when installing. e.g `brew install emacs --with-gnutls`.

emacs-plus includes this setting automatically. That said, I'll work on including a gnutls check in the doctor.

**Comment by hlissner** [comment]
Phew, it's been a while, but I think I've finally tracked this "peculiar error" business down to faulty error handling in the doctor script. This _should_ resolve this issue. As it is an old issue I'll close this issue, but feel free to reopen it if this most peculiar of errors rears its head again.

**Comment by chriskaukis** [comment]
Awesome, thanks and glad you found the issue. 👍
