### ISSUE TITLE
[BUG] forge not working with magit

### ISSUE THREAD

**Issue by insipx** [hlissner/doom-emacs#1751]
**Describe the issue**
whenever trying to run forge-specific commands ie `forge-pull`, I get an error `Wrong type argument: (or eieio-object-class), nil, obj

<details><pre>

Debugger entered--Lisp error: (wrong-type-argument (or eieio-object class) nil obj)
  signal(wrong-type-argument ((or eieio-object class) nil obj))
  #f(compiled-function (obj slot) "Return the value in OBJ at SLOT in the object vector." #<bytecode 0x194b285>)(nil id)
  eieio-oref--closql-oref(#f(compiled-function (obj slot) "Return the value in OBJ at SLOT in the object vector." #<bytecode 0x194b285>) nil id)
  apply(eieio-oref--closql-oref #f(compiled-function (obj slot) "Return the value in OBJ at SLOT in the object vector." #<bytecode 0x194b285>) (nil id))
  eieio-oref(nil id)
  byte-code("\300\301\302!\303\"C\207" [eieio-oref forge-get-repository t id] 3)
  call-interactively(forge-list-pullreqs nil nil)
  command-execute(forge-list-pullreqs)

**Steps to reproduce**
1. open doom emacs into a git project
2. try running forge-pull

**System information**
<details><pre>
PopOs/Ubuntu with kernel 5.2 64bit
</pre></details>

**Comment by hlissner** [comment]
I believe this occurs because emacsql isn't being build. Try running `M-x eval-expression RET (emacsql-sqlite-compile 2)`, then check `*Messages*` (`SPC h e` or `C-h e`) for warnings/errors.

If it built successfully, try forge-pull again and let me know the results.

**Comment by socksy** [comment]
I had exactly the same issue and `(emacsql-sqlite-compile 2)` got it to work with no warnings/errors, and `forge-pull` worked correctly afterwards.

**Comment by insipx** [comment]
Indeed this worked

Thanks guys!

**Comment by socksy** [comment]
This keeps happening to me, possibly after each time I restart (haven't nailed down exactly when)

**Comment by bersace** [comment]
Hi. Looks like emacsql is not there :

```
Debugger entered--Lisp error: (void-function emacsql-sqlite-compile)
  (emacsql-sqlite-compile 2)
  eval((emacsql-sqlite-compile 2) t)
```

How to get it installed ? `(magit +forge)` ?

**Comment by bersace** [comment]
That's odd because of

```
$ find .local/ -name "*emacsql*"
...
.local/straight/repos/emacsql/emacsql-sqlite.el
...
```

**Comment by huos3203** [comment]
> I believe this occurs because emacsql isn't being built. Try running `M-x eval-expression RET (emacsql-sqlite-compile 2)`, then check `*Messages*` (`SPC h e` or `C-h e`) for warnings/errors. You may want to check the `*Compile-Log*` buffer as well to see that the compilation succeeded.
> 
> If it built successfully, try forge-pull again and let me know the results.
I try `(emacsql-sqlite-compile 2)`,log:
```
Compiling EmacSQL SQLite binary ...
nil
```

**Comment by hlissner** [comment]
@huos3203 The package doesn't log compilation results to \*Messages\*. Look for a `*Compile-Log*` buffer in your buffer list (see `SPC b B`). It should have more information.

@bersace Try deleting `~/.emacs.d/.local/straight/build/emacsql-sqlite`, run `doom refresh` then reopen magit to allow it to recompile.

**Comment by huos3203** [comment]
@hlissner thanks
I see `SPC b B compile-log`
```
  Referenced from: /Users/itboyer/Downloads/Xcode.app/Contents/Developer/usr/bin/xcodebuild
  Reason: image not found
cc: error: unable to locate xcodebuild, please make sure the path to the Xcode folder is set correctly!
cc: error: You can set the path to the Xcode folder using /usr/bin/xcode-select -switch
```
I solved the problem by doing this：
```
xcode-select -s /Applications/Xcode.app
```
and eval:`(emacsql-sqlite-compile 2)` built successfully.

**Comment by huos3203** [comment]
@hlissner 
I run `forge-pull` log:
```
Save auth info to file /Users/itboyer/.emacs.d/.local/etc/authinfo.gpg? [y/n/N/e/?] y
epg-context--make: GPG error: "no usable configuration", OpenPGP
```
i select [`y`],but i can't find this `autoinfo.gpg` file in `.emacs.d/.local/etc` folder.

**Comment by hlissner** [comment]
@huos3203 Have you [set `user-mail-address` or `user-full-name`](https://github.com/hlissner/doom-emacs-private/blob/master/config.el#L3-L4) (It needsto match your GPG key recipient)? Is `epa-file-encrypt-to` set to the correct GPG recipient? [Is GPG set up correctly](https://wooledge.org/~greg/crypto/node41.html)?

It cannot create the authinfo file correctly without GPG set up.

Alternative (and I wouldn't recommend it), you could store that sensitive info in plaintext:

```elisp
(setq auth-sources (list (expand-file-name "authinfo" doom-etc-dir)))
```

**Comment by huos3203** [comment]
@hlissner thanks
After I install GPG, execute `forge-pull` and configure GPG. it is OK.
```
brew install gnupg
```
