### ISSUE TITLE
[BUG] README links

### ISSUE THREAD

**Issue by A1rPun** [hlissner/doom-emacs#1755]
**Describe the issue**
When you click on [hlissner/doom-emacs#getting-help](https://github.com/hlissner/doom-emacs#getting-help) in the **Table of Contents** there is no anchor found with that id.
I think the intented link is [hlissner/doom-emacs#troubleshooting](https://github.com/hlissner/doom-emacs#troubleshooting).

**Edit:**
It seems like the [Visit our FAQ](https://github.com/hlissner/doom-emacs/blob/develop/docs/faq.org) link in the last bullet point of **Troubleshooting** is not redirecting to the right file.

**Steps to reproduce**
1. Click on [hlissner/doom-emacs#getting-help](https://github.com/hlissner/doom-emacs#getting-help) 
2. See the url change to https://github.com/hlissner/doom-emacs#getting-help
3. ?????
4. No Help!

**System information**
<details><pre>
((emacs
  (version . "26.3")
  (features . "XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2")
  (build . "Aug 29, 2019")
  (buildopts "--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-modules 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now"))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD f6b8807e 2019-09-05 14:20:50 -0400"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/bin/bash")
  (uname . "Linux 5.0.4-arch1-1-ARCH #1 SMP PREEMPT Sat Mar 23 21:00:33 UTC 2019 x86_64")
  (path "/usr/local/sbin" "/usr/local/bin" "/usr/bin" "/usr/lib/jvm/default/bin" "/usr/bin/site_perl" "/usr/bin/vendor_perl" "/usr/bin/core_perl" "/usr/lib/emacs/26.3/x86_64-pc-linux-gnu"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor evil file-templates fold multiple-cursors rotate-text snippets :emacs dired electric vc :tools eval flycheck (lookup +docsets) magit :lang data emacs-lisp markdown (org +dragndrop +ipython +pandoc +present) sh :config default)
  (packages "n/a")
  (elpa-packages "n/a")))
</pre></details>

**Comment by iboyperson** [comment]
Additionally under https://github.com/hlissner/doom-emacs#contributing the link: "[Contributing Guidelines](https://github.com/hlissner/doom-emacs/blob/develop/docs/contribute.org)" gives a 404

**Comment by hlissner** [comment]
As of 38bed2d, 3f6decf and 4b2447f the README links have been fixed (or rather, the files they point at have been published). Thanks for bringing this to my attention!
