### ISSUE TITLE
[BUG] Warning (fcitx.el): `fcitx-remote' is not avaiable.

### ISSUE THREAD

**Issue by jingkangy91** [hlissner/doom-emacs#1758]
After I start emacs.app from Alfred (MacOS), it shows the information below:

> Warning (fcitx.el): `fcitx-remote' is not avaiable. Please check your fcitx installtion.

The fcitx.el was included in packages.el by (package! fcitx), and fcitx-remote-for-osx worked fine before. This warning information has been shown after updating. As a result, the function of fcitx-remote cannot be used.

But if I open emacs from terminal, there is no warning. I wonder if there is something wrong in doom emacs or my local configuration. I use zsh by the way.

![emacs_with_fcitx_warning](https://user-images.githubusercontent.com/8621874/64434730-cc04ae80-d0f3-11e9-86c6-2a3c1b9c5432.png)

**System information**
<details><pre>
((emacs
  (version . "26.3")
  (features . "NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS")
  (build . "Sep 02, 2019")
  (buildopts "--with-ns '--enable-locallisppath=/Library/Application Support/Emacs/${version}/site-lisp:/Library/Application Support/Emacs/site-lisp' --with-modules"))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD ac5168f8 2019-09-06 01:32:20 -0400"))
 (system
  (type . darwin)
  (config . "x86_64-apple-darwin18.2.0")
  (shell . "/bin/zsh")
  (uname . "Darwin 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64")
  (path "/usr/local/opt/ruby/bin" "/usr/local/lib/ruby/gems/2.6.0/bin" "/usr/local/anaconda3/bin" "/usr/local/bin" "/usr/bin" "/bin" "/usr/sbin" "/sbin" "/Library/TeX/texbin" "/opt/X11/bin" "/Applications/Emacs.app/Contents/MacOS/bin-x86_64-10_14" "/Applications/Emacs.app/Contents/MacOS/libexec-x86_64-10_14" "/Applications/Emacs.app/Contents/MacOS/libexec" "/Applications/Emacs.app/Contents/MacOS/bin"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor evil file-templates fold multiple-cursors rotate-text snippets :emacs dired electric vc :tools eval flycheck (lookup +docsets) magit :lang data emacs-lisp latex markdown (org +dragndrop +ipython +pandoc +present) python sh :config default)
  (packages "fcitx")
  (elpa-packages "fcitx")))
</pre></details>

**Comment by hlissner** [comment]
Have you refreshed your envvar file since installing fcitx-remote? You can do so by running `doom refresh` (or `doom env`).

**Comment by jingkangy91** [comment]
> Have you refreshed your envvar file since installing fcitx-remote? You can do so by running `doom refresh` (or `doom env`).

Thanks for your reply.

Yes, I've done `doom refresh` every time after `doom update`. And I have installed fcitx-remote before, it worked fine with doom until the latest updating.

By the way, after recent updates, the highlights for modified lines of git files won't be shown correctly until I save the file twice. After saving the first time, the highlight bar on the left side of emacs won't change. I'm not sure is it worth to open another issue.

**Comment by cnsunyour** [comment]
> > Have you refreshed your envvar file since installing fcitx-remote? You can do so by running `doom refresh` (or `doom env`).
> 
> Thanks for your reply.
> 
> Yes, I've done `doom refresh` every time after `doom update`. And I have installed fcitx-remote before, it worked fine with doom until the latest updating.
> 
> By the way, after recent updates, the highlights for modified lines of git files won't be shown correctly until I save the file twice. After saving the first time, the highlight bar on the left side of emacs won't change. I'm not sure is it worth to open another issue.

You can try to run `doom env` alone before you runing `doom refresh`.I found that sometimes the envvar file will be lost after `doom update`. At this time, only executing `doom refresh` will not generate a new envvar file. You must first execute `doom env`.

**Comment by jingkangy91** [comment]
Thanks, it does happen what you said. And after updating doom today, the warning won't show up. However, the highlight of git still needs the second save to show. Fortunately, it won't bother too much.

**Comment by hlissner** [comment]
Two days ago, in 280a2407a, I published a fix for `doom env` that may have caused your issue. For the time being, I'll consider the original issue resolved. Let me know if that isn't the case.

As for the double-save issue for git-gutter, I can't reproduce this. Can you reproduce it in vanilla Doom (see [how to use the sandbox](https://gist.github.com/hlissner/3910fcf5ef14ab77657f269ba9b37f94))? If so, please create a new issue for it.

**Comment by jingkangy91** [comment]
Thanks hlissner, this issue was resolved.
As for the double-save issue for git-gutter, I'll try to reproduce it in vanilla Doom, and create another issue.
