### ISSUE TITLE
[QUESTION] Alternative for "doom quickstart"?

### ISSUE THREAD

**Issue by ezchi** [hlissner/doom-emacs#1766]
`raw.githubusercontent.com` is blocked by proxy. So is it an alternative for "doom quckstart"?
 elpa and github repo clone are all fine.

**Comment by hlissner** [comment]
If you run `~/.emacs.d/bin/doom help install` (`doom install` replaced `doom quickstart` in later versions of Doom Emacs), it will list what exactly this command does. To quote it:

```
  1. Creates DOOMDIR at ~/.doom.d,
  2. Copies ~/.emacs.d/init.example.el to DOOMDIR/init.el (if it doesn't exist),
  3. Creates dummy files for DOOMDIR/{config,packages}.el,
  4. Prompts you to generate an envvar file (same as 'doom env'),
  5. Installs any dependencies of enabled modules (specified by DOOMDIR/init.el),
  6. And prompts to install all-the-icons' fonts
```

Here is what it'd look like translated into shell commands:

```sh
git clone https://github.com/hlissner/doom-emacs ~/.emacs.d
mkdir -p ~/.doom.d
cp ~/.emacs.d/init.example.el ~/.doom.d/init.el
~/.emacs.d/bin/doom refresh
~/.emacs.d/bin/doom env   # if you need an envvar file, 
                          # see `doom help env` for details
```

Then run emacs and run `M-x all-the-icons-install-fonts` to install icon fonts, if you'd like.

**Comment by ezchi** [comment]
Bad news is the "doom refresh" command also tries to get straight.el from `raw.gthbusercontent.com`.

Using a proxy for https...
Error: (error (void-variable peer))
  (eval peer nil)
  (elisp--eval-last-sexp t)
  (eval-last-sexp t)
  (eval-print-last-sexp)
  (save-current-buffer (set-buffer (url-retrieve-synchronously (format "https://raw.githubusercontent.com/raxod502/straight.el/%s/install.el" straight-repository-branch) 'silent 'inhibit-cookies)) (goto-char (point-max)) (eval-print-last-sexp))

**Comment by ezchi** [comment]
I found a workaround. Just clone the `straight.el` to `<doom-emacs>/.local/straight/repos/`. Then everything works.

**Comment by hlissner** [comment]
Then try this:

```sh
git clone https://github.com/hlissner/doom-emacs ~/.emacs.d
mkdir -p ~/.doom.d
cp ~/.emacs.d/init.example.el ~/.doom.d/init.el

# Install straight manually
mkdir -p ~/.emacs.d/.local/straight/repos/straight.el
git clone -b develop https://github.com/raxod502/straight.el ~/.emacs.d/.local/straight/repos/straight.el

~/.emacs.d/bin/doom refresh
~/.emacs.d/bin/doom env   # if you need an envvar file, 
                          # see `doom help env` for details
```
