### ISSUE TITLE
[HOWTO] Only add projects manually?

### ISSUE THREAD

**Issue by sooqua** [hlissner/doom-emacs#1768]
I'm tired of clearing my projects from random projects that appear to have a .git folder inside of them. I'm not sure if this is the right place to ask but I couldn't find a similar issue in projectile or doom's issues nor could I find a solution by looking at the source files or projectile's variables.

**System information**
**doom/info: Symbol’s function definition is void: doom--format**

**Comment by hlissner** [comment]
Would this work for you?

```elisp
(setq projectile-track-known-projects-automatically nil)
```

**Comment by sooqua** [comment]
I think so. Thank you very much!
