### ISSUE TITLE
[BUG] =mu4e: Cannot open load file: No such file or directory, mu4e

### ISSUE THREAD

**Issue by WhatDothLife** [hlissner/doom-emacs#1769]
The load-path list seems incomplete for mu4e.

**Comment by hlissner** [comment]
Have you installed mu on your system? See [email/mu4e/README.org](https://github.com/hlissner/doom-emacs/blob/develop/modules/email/mu4e/README.org#prerequisites)

**Comment by WhatDothLife** [comment]
Thank you for the quick reply.

mu is properly installed. I just figured out that the mu4e.el is installed into `/usr/share/emacs/site-lisp/mu4e/`. 
I'm uncertain whether this is always the default directory and thus adding it to the load-path by default is save, but at least there should be some hint in the README.org, that load-path may have to be adjusted.

**Comment by hlissner** [comment]
Adjusting your load-path shouldn't be necessary. Emacs should pre-populate `load-path` with the directories in /usr/share/emacs/site-lisp/* (but you need to run `doom refresh` to ensure this new value for `load-path` is correctly cached).

**Comment by WhatDothLife** [comment]
That was probably it. I didn't run `doom refresh`!
