### ISSUE TITLE
[BUG] lsp-python-ms should download executable to doom-local-dir

### ISSUE THREAD

**Issue by iboyperson** [hlissner/doom-emacs#1776]
`lsp-python-ms` downloads the language server to `.emacs.d/mspyls` by default. This should likely be moved to `doom-etc-dir`. This can be done by setting `lsp-python-ms-dir`.

**Comment by hlissner** [comment]
As of b1f9965 this should be resolved. Let me know if that isn't the case and I'll reopen this. Thanks for bringing it to my attention!
