### ISSUE TITLE
[BUG] restoring desktop kills some key bindings

### ISSUE THREAD

**Issue by scaba** [hlissner/doom-emacs#1781]
After I exit Emacs with the desktop automatically saving, after restart I cannot perform certain actions including C-x C-c to quit Emacs. Even macOS's CMD + Q doesn't work. I have to Force Quit. If I launch Emacs again _without_ restoring the desktop, everything works as expected, only I have to re-open and rearrange all of my frames and buffers.

**When I first launch I get this (from *Messages*)**:
Desktop: 1 frame, 4 buffers restored.
Doom loaded 223 packages across 44 modules in 50.423s
better-jumper--get-struct-jump-list: Wrong type argument: better-jumper-jump-list-struct, "Unprintable entity"

**After than any key binding that is broken produces this:**
user-error: Not in a valid workspace (Unprintable entity) [3 times]

**I have in my config.el:**
`(desktop-save-mode 1)`

I've done `doom up`, `doom autoloads` and `doom refresh -f` and the behavior persists when restoring the desktop

**Comment by hlissner** [comment]
Do not use `desktop-save-mode` (or desktop.el, manually). It does not work with Doom at the moment.

Doom has its own session persistence library, powered by a modded desktop.el OR by persp-mode (if you have the ui/workspaces module enabled).

You can save the session with `M-x doom/quicksave-session` (bound to `SPC q S`) and load the last saved session with `M-x doom/quickload-session` (bound to `SPC q L`).

Remove `(desktop-save-mode 1)` from your config and either:

1. Manually restore sessions with `SPC q L` (`doom/quickload-session`)
2. Or use `(add-hook 'window-setup-hook #'doom/quickload-session)`

**Comment by scaba** [comment]
Thanks, that fixed the issue of killing the keybindings. However the frame/window layout isn't restored. The correct windows open within the frame, but the frame opens to the tiny default size. I know I can add a line or two to my init to cause it to open to a certain size, but I would rather it open to the size it was when it was closed. Is this possible with ui/workspaces, which I do have enabled?

**Comment by zzamboni** [comment]
I only recently started using Doom Emacs, and I'm slowly migrating from my previous hand-crafted Emacs config (I'm on macOS, using [emacs-mac](https://github.com/railwaycat/homebrew-emacsmacport). One of the things I'm still missing is the auto-recover of my previous session (including window layout) upon startup. `doom/quickload-session` works fine when I invoke it by hand (e.g. with `C-c f L`, I'm using Emacs bindings). I added `(add-hook 'window-setup-hook #'doom/quickload-session)` to my `config.el` file, but it it doesn't seem to do anything - upon startup I still get the dashboard buffer. Upon examination, `doom/quickload-session` is shown in `window-setup-hook`.

Am I missing something? Thanks for any feedback.

Finally, any pointers for whether it's possible to automatically recover the previous window layout (as `desktop-save-mode` does)?

@hlissner thanks for all your work on Emacs Doom! I'm really enjoying it so far.

**Comment by basedness** [comment]
it should be `(add-hook! 'window-setup-hook #'doom/quickload-session)` as you can see the `!` is missing.
It's worth noting that while it works, you're still gonna start on the splash screen, I don't know how to disable it (if anyone knows please tell me)


@zzamboni

**Comment by zzamboni** [comment]
@basedness thanks - for this simple case, `add-hook` and `add-hook!` are identical, but you are right - it was always working, I was misled by the fact that the dashboard was still shown. Another weird side effect is that my fonts are not loaded properly - maybe the session is being restored before the fonts are configured? Not sure.

What would be nice is to have lazy loading like `desktop-save-mode` does - load right away only the file you had last opened, and then in the background restore the rest of them.

However, in the meantime I'm used to reloading things as needed by hand, and I really enjoy how fast Doom starts up, so I don't miss it too much.

**Comment by darth10** [comment]
Is it possible to restore frame layout like `desktop-save-mode`?
