### ISSUE TITLE
[BUG]  Doom upgrade fails since d1a299b9f5

### ISSUE THREAD

**Issue by teehemkay** [hlissner/doom-emacs#1783]
Running `doom up` fails with the following error message:

<pre>
There was an unexpected error:
  Symbol's value as variable is void (void-variable)
  doom-interactive-mode
</pre>

I had to run several commands to get an hopefully informative log, search for `### command` in the gist below:

https://gist.github.com/teehemkay/6773a5b93ec8de5612cb2dfcd5a66d96

I've tried upgrading several times since then with the same error message.
Last try was with version doom-emacs a736158dae

**System information**
<details><pre>
((emacs
  (version . "26.2")
  (features . "NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS")
  (build . "Jul 11, 2019")
  (buildopts "--prefix=/nix/store/0zrl3kh7adq2brwnpq0kjf6xxjf2jnvy-emacs-mac-26.2-7.6 LDFLAGS=-L/nix/store/sdr42j6ifycczh9hqniwnkf75f1lza3y-ncurses-6.1-20190112/lib --with-xml2=yes --with-gnutls=yes --with-mac --with-modules '--enable-mac-app=$$out/Applications' CFLAGS=-O3"))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD d1a299b9f 2019-08-29 20:05:34 -0400"))
 (system
  (type . darwin)
  (config . "x86_64-apple-darwin17.7.0")
  (shell . "/run/current-system/sw/bin/fish")
  (uname . "Darwin 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64")
  (path "~/.emacs.d/bin" "~/.nix-profile/bin" "/run/current-system/sw/bin" "/nix/var/nix/profiles/default/bin" "/usr/local/bin" "/usr/bin" "/usr/sbin" "/bin" "/sbin" "/nix/store/0zrl3kh7adq2brwnpq0kjf6xxjf2jnvy-emacs-mac-26.2-7.6/libexec/emacs/26.2/x86_64-apple-darwin17.7.0"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company (ivy +icons +prescient) :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) pretty-code treemacs unicode vc-gutter vi-tilde-fringe (window-select +numbers) workspaces :editor evil file-templates fold (format +onsave) multiple-cursors rotate-text snippets :emacs dired electric vc :term eshell :tools direnv editorconfig eval (flycheck +childframe) (lookup +docsets) lsp macos magit pdf :lang data emacs-lisp (javascript +lsp) ledger markdown nix (org +dragndrop +ipython +pandoc +present) racket sh (web +lsp) :config default)
  (packages "n/a")
  (elpa-packages "n/a")))
</pre></details>

**Comment by hlissner** [comment]
This is a strange error; I cannot reproduce it. `doom-interactive-mode` is defined in core.el, the first file that Doom loads during startup (besides `~/.emacs.d/init.el`).

Please try deleting `~/.emacs.d/.local/autoloads.*` manually, then upgrade manually:

```sh
cd ~/.emacs.d
git pull --rebase
bin/doom refresh -f
bin/doom update
```

If that doesn't work, try deleting `~/.emacs.d/.local`, then run `bin/doom refresh -f`.

If that _still_ doesn't work, try deleting `~/.emacs.d`, recloning, then run `bin/doom refresh -f` once more.

**Comment by teehemkay** [comment]
I proceeded as you suggested and I'm happy to report that the second step, deleting `~/.emacs.d/.local`, and then running `bin/doom refresh -f` did the trick.

Thanks a lot for you help, it's much appreciated.
