### ISSUE TITLE
Link description not shown in Org files

### ISSUE THREAD

**Issue by kandread** [hlissner/doom-emacs#1790]
When adding a link to an Org file, the address is displayed instead of the descriptive text. `org-link-descriptive` is `t`. 

**Steps to reproduce**
1. Open a new file `test.org`
2. Run `org-insert-link` (`C-c C-l`)
3. Type an address and a description at the prompt. E.g. https://github.com/hlissner/doom-emacs/issues and `Issues` respectively.

Expected to see 

> Issues

but instead see

> https://github.com/hlissner/doom-emacs/issues

Running without an init file (`emacs -q`) has the expected behavior (I assume that the expected behavior is to actually display the descriptive text).

**System information**
<details><pre>
((emacs
  (version . "26.3")
  (features . "NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS")
  (build . "Sep 02, 2019")
  (buildopts "--with-ns '--enable-locallisppath=/Library/Application Support/Emacs/${version}/site-lisp:/Library/Application Support/Emacs/site-lisp' --with-modules")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD 42df2eaf8 2019-09-15 19:24:51 -0400"))
 (system
  (type . darwin)
  (config . "x86_64-apple-darwin18.2.0")
  (shell . "/bin/zsh")
  (uname . "Darwin 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64")
  (path "/usr/local/miniconda3/condabin" "/usr/local/bin" "/usr/bin" "/bin" "/usr/sbin" "/sbin" "/opt/X11/bin" "/Library/TeX/texbin" "." "/Applications/Emacs.app/Contents/MacOS/bin-x86_64-10_14" "/Applications/Emacs.app/Contents/MacOS/libexec-x86_64-10_14" "/Applications/Emacs.app/Contents/MacOS/libexec" "/Applications/Emacs.app/Contents/MacOS/bin"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard hl-todo modeline nav-flash ophints (popup +all +defaults) treemacs unicode vc-gutter vi-tilde-fringe window-select workspaces :editor evil file-templates fold multiple-cursors rotate-text snippets word-wrap :emacs dired electric vc :term eshell :tools docker eval flycheck flyspell (lookup +docsets) macos magit pdf :lang data emacs-lisp julia markdown (org +dragndrop +ipython +pandoc +present) python sh :email mu4e :app calendar :config default)
  (packages "(org-ref :recipe (:host github :repo \"jkitchin/org-ref\"))" org-pomodoro org-fancy-priorities)
  (elpa "n/a")))
</pre></details>

**Comment by flyingns** [comment]
I only have this problem in helm mode, ivy mode does not exist.

[#1710](https://github.com/hlissner/doom-emacs/issues/1710)

**Comment by filalex77** [comment]
Can't reproduce on any of the `doom/sandbox` presets:
- vanilla emacs
- only doom core
- doom + modules - config
- doom + modules + config

**Comment by kandread** [comment]
Might be something specific with my config then. I'll go ahead and close the issue.

**Comment by cmiquelon** [comment]
@kandread I had the same issue. I disabled the `+dragndrop` flag in my `.doom.d/init.el` and it solved it.

**Comment by alphapapa** [comment]
See https://lists.gnu.org/archive/html/emacs-orgmode/2019-09/msg00162.html
