### ISSUE TITLE
[Bug] doom/help opens empty buffer

### ISSUE THREAD

**Issue by benjaminbauer** [hlissner/doom-emacs#1795]
**Describe the issue**
When tying `SPC h D`, a buffer opens for a new file `~/.emacs.d/docs/index.org`

The only file that exists in docs is api.org. Is the keybinding wrong and there is not index.org on purpose? Or is the keybinding intended and the index.org does not exist (yet)?

**Comment by filalex77** [comment]
Yeah, I think it's the latter.

`doom/help` was added in April, and I'm pretty sure the docs haven't improved *a lot* since then. It's WIP :)

**Comment by hlissner** [comment]
docs/index.org simply doesn't exist yet. I'll keep this thread open until it's up.

**Comment by hlissner** [comment]
As of 38bed2d this is resolved. Let me know if that isn't the case and I'll reopen the issue. Thanks for bringing it to my attention!
