### ISSUE TITLE
[BUG] SPC b b broken after Emacs update

### ISSUE THREAD

**Issue by vakker** [hlissner/doom-emacs#1796]
**Describe the issue**
My config worked fine (with Emacs 26.something), but I updated Emacs (now 26.3) and also pulled the latest version of doom-emacs.
After starting Emacs, I tried `SPC b b`, but instead of showing the buffer I got the message: `Symbol’s function definition is void: +workspace-contains-buffer-p`

**Backtrace**
<details><pre>
Debugger entered--Lisp error: (void-function +workspace-contains-buffer-p)
  (+workspace-contains-buffer-p buffer)
  (and (not (eq buffer (current-buffer))) (+workspace-contains-buffer-p buffer))
  (let ((buffer (car buffer))) (if (stringp buffer) (progn (setq buffer (get-buffer buffer)))) (and (not (eq buffer (current-buffer))) (+workspace-contains-buffer-p buffer)))
  +ivy--is-workspace-other-buffer-p((" *Minibuf-1*" . #<buffer  *Minibuf-1*>))
  internal-complete-buffer("" +ivy--is-workspace-other-buffer-p t)
  all-completions("" internal-complete-buffer +ivy--is-workspace-other-buffer-p)
  ivy--buffer-list("" nil +ivy--is-workspace-other-buffer-p)
  ivy--reset-state(#s(ivy-state :prompt "Switch to workspace buffer: " :collection internal-complete-buffer :predicate +ivy--is-workspace-other-buffer-p :require-match nil :initial-input nil :history nil :preselect "*doom*" :keymap (keymap (33554443 . scroll-down-command) (33554442 . scroll-up-command) (10 . next-line) (18 . evil-paste-from-register) (2 . backward-word) (1 . move-beginning-of-line) (26 closure (t) nil (interactive) (condition-case nil (progn (call-interactively (function undo))) (error nil))) (22 . yank) (escape . abort-recursive-edit) (19 . counsel-minibuffer-history) (11 . previous-line)) :update-fn nil :sort nil :frame #<frame test.py – Doom Emacs 0x1434c30> :window #<window 3 on test.py> :buffer #<buffer test.py> :text nil :action (1 ("o" ivy--switch-buffer-action "default") ("i" #f(compiled-function (x) #<bytecode 0x17dcbbd>) "insert") ("w" #f(compiled-function (x) #<bytecode 0x17dcbc9>) "copy") ("f" ivy--find-file-action "find file") ("j" ivy--switch-buffer-other-window-action "other window") ("k" ivy--kill-buffer-action "kill") ("r" ivy--rename-buffer-action "rename") ("x" counsel-open-buffer-file-externally "open externally")) :unwind nil :re-builder nil :matcher ivy--switch-buffer-matcher :dynamic-collection nil :display-transformer-fn ivy-rich--ivy-switch-buffer-transformer :directory "/home/vince/workspace/trading/bitcoin-p1/" :caller ivy-switch-buffer :current nil :def nil :ignore t :multi-action nil))
  ivy-read("Switch to workspace buffer: " internal-complete-buffer :action ivy--switch-buffer-action :predicate +ivy--is-workspace-other-buffer-p :update-fn nil :unwind nil :preselect "*doom*" :matcher ivy--switch-buffer-matcher :keymap (keymap (33554443 . scroll-down-command) (33554442 . scroll-up-command) (10 . next-line) (18 . evil-paste-from-register) (2 . backward-word) (1 . move-beginning-of-line) (26 closure (t) nil (interactive) (condition-case nil (progn (call-interactively (function undo))) (error nil))) (22 . yank) (escape . abort-recursive-edit) (19 . counsel-minibuffer-history) (11 . previous-line)) :caller ivy-switch-buffer)
  (let ((current (not other)) prompt action filter update unwind) (cond ((and workspace current) (setq prompt "Switch to workspace buffer: " action (function ivy--switch-buffer-action) filter (function +ivy--is-workspace-other-buffer-p))) (workspace (setq prompt "Switch to workspace buffer in other window: " action (function ivy--switch-buffer-other-window-action) filter (function +ivy--is-workspace-buffer-p))) (current (setq prompt "Switch to buffer: " action (function ivy--switch-buffer-action))) ((setq prompt "Switch to buffer in other window: " action (function ivy--switch-buffer-other-window-action)))) (if +ivy-buffer-preview (progn (cond ((not (and ivy-use-virtual-buffers (eq +ivy-buffer-preview ...))) (setq update (function +ivy--switch-buffer-preview) unwind (function +ivy--switch-buffer-unwind))) ((setq update (function +ivy--switch-buffer-preview-all) unwind (function +ivy--switch-buffer-unwind)))))) (ivy-read prompt (quote internal-complete-buffer) :action action :predicate filter :update-fn update :unwind unwind :preselect (buffer-name (other-buffer (current-buffer))) :matcher (function ivy--switch-buffer-matcher) :keymap ivy-switch-buffer-map :caller (function ivy-switch-buffer)))
  +ivy--switch-buffer(t nil)
  +ivy/switch-workspace-buffer(nil)
  funcall-interactively(+ivy/switch-workspace-buffer nil)
  call-interactively(+ivy/switch-workspace-buffer nil nil)
  command-execute(+ivy/switch-workspace-buffer)
</pre></details>

**`emacs doctor` output**:
<details><pre>
Doom Doctor
Emacs v26.3
Doom v2.0.9 (nil)
shell: /usr/bin/zsh
Compiled with:
  XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD LCMS2
uname -msrv:
  Linux 4.15.0-64-generic #73-Ubuntu SMP Thu Sep 12 13:16:13 UTC 2019 x86_64

Checking Emacs
  Checking your Emacs version is 25.3 or newer...
  Checking for Emacs config conflicts...
  Checking for private config conflicts...
  Checking for stale elc files...
Checking your system...

Checking DOOM Emacs...
WARNING: The :fetcher property was used for the smartparens package.
This property is deprecated. Replace it with :host.
  Initialized Doom Emacs 2.0.9
Garbage collecting...
Garbage collecting...done
  Initialized 39 modules
  Initialized 161 packages
  Checking Doom core for irregularities...
Garbage collecting...
Garbage collecting...done
Garbage collecting...
Garbage collecting...done
Garbage collecting...
Garbage collecting...done
    Found font material
    Found font wicon
    Found font octicon
    Found font faicon
    Found font fileicon
    Found font alltheicon
  Checking for stale elc files in your DOOMDIR...
  Checking your enabled modules...
Garbage collecting...
Garbage collecting...done
Garbage collecting...
Garbage collecting...done
(Shell command succeeded with no output)

Everything seems fine, happy Emacs'ing!
</pre></details>

**System information**
<details><pre>
WARNING: The :fetcher property was used for the smartparens package.
This property is deprecated. Replace it with :host.
WARNING: The :fetcher property was used for the smartparens package.
This property is deprecated. Replace it with :host.
((emacs
  (version . "26.3")
  (features . "XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD LCMS2")
  (build . "Sep 16, 2019")
  (buildopts "--build=x86_64-linux-gnu --prefix=/usr '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' --sysconfdir=/etc --localstatedir=/var --disable-silent-rules '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' --disable-maintainer-mode --disable-dependency-tracking --prefix=/usr --sharedstatedir=/var/lib --program-suffix=26 --with-modules --with-file-notification=inotify --with-mailutils --with-x=yes --with-x-toolkit=gtk3 --with-xwidgets --with-lcms2 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/emacs26-TP6iDo/emacs26-26.3~1.git96dd019=. -fstack-protector-strong -Wformat -Werror=format-security -no-pie' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro -no-pie'")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD 42df2eaf8 2019-09-15 19:24:51 -0400"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/usr/bin/zsh")
  (uname . "Linux 4.15.0-64-generic #73-Ubuntu SMP Thu Sep 12 13:16:13 UTC 2019 x86_64")
  (path "~/.emacs.d/bin" "~/.local/bin" "~/bin" "~/.emacs.d/bin" "~/.local/bin" "~/bin" "~/miniconda3/bin" "~/miniconda3/condabin" "~/.emacs.d/bin" "~/.local/bin" "~/bin" "/usr/local/sbin" "/usr/local/bin" "/usr/sbin" "/usr/bin" "/sbin" "/bin" "/usr/games" "/usr/local/games" "/snap/bin" "/usr/local/go/bin" "~/go/bin" "/usr/local/go/bin" "~/go/bin" "/usr/local/go/bin" "~/go/bin" "/usr/lib/x86_64-linux-gnu/emacs/26.3/x86_64-linux-gnu"))
 (config
  (envfile)
  (elc-files . 34)
  (modules :completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor evil file-templates fold multiple-cursors rotate-text snippets :emacs dired electric vc :tools docker eval flycheck flyspell (lookup +docsets) magit pdf :lang data emacs-lisp (latex +latexmk) markdown (org +dragndrop +ipython +pandoc +present) python sh :config default)
  (packages ag highlight-indent-guides yapfify "(smartparens :recipe (:repo \"Fuco1/smartparens\" :host github))" py-isort org-ref org-fancy-priorities org-super-agenda "(persp-mode :disable t)")
  (elpa "n/a")))
</pre></details>

**Comment by filalex77** [comment]
Does `doom clean; doom refresh` help?

**Comment by vakker** [comment]
Thanks for the suggestion, it doesn't help.

I also tried starting from a completely clean install (`git clone`, `doom install`, `doom refresh`) and it was the same.

**Comment by hlissner** [comment]
@vakker It appears you have the `:ui workspaces` module enabled, but the `persp-mode` package disabled (with `(package! persp-mode :disable t)` in `~/.doom.d/packages.el`). `+workspace-contains-buffer-p` is an alias for `persp-contain-buffer-p`, which won't exist because the plugin is disabled.

Since `persp-mode` is essential to the `:ui workspaces` module, I'd suggest disabling the module altogether, instead.

**Comment by vakker** [comment]
Ah, thanks, that was it. It's weird why it stopped working suddenly, I totally forgot about disabling it.
