### ISSUE TITLE
[HOWTO] Unmap keys with prefix

### ISSUE THREAD

**Issue by haji-ali** [hlissner/doom-emacs#1797]
I just updated to the latest version of doom and some of my key bindings are being shadowed by dooms keybindings. I am wondering how I can unbind these.

In particular, the key bindings "C-c t t" and "C-c t T" in the default `+emacs-bindings` open the terminal which shadows my binding "C-c t" to do something else.
I tried doing

```
(unmap! "C-c t t" "C-c t T")
```
but I am getting the error

```
(error "Key sequence C-c t t starts with non-prefix key C-c t")
```

How do I do this correctly?

**Comment by hlissner** [comment]
To use unmap! you'd have to target the `doom-leader-map` keymap:

```lisp
(unmap! doom-leader-map "C-c t t" "C-c t T")
```

Otherwise, I suggest using `map!`:

```elisp
(map! :leader
      "t t" nil 
      "t T" nil)
```

Another alternative is to add `(general-auto-unbind-keys)` to the top of your config.el. This will force general to auto-unbind keys rather than throw `Key sequence ... starts with non-prefix key ...` errors.

Hope that helps.

**Comment by haji-ali** [comment]
Thanks! That definitely takes care of the error. I then tried doing

```
(map! "C-c t" #'my-foo)
```

Thinking I can rebind the key sequence, but now I get `which-key: There are no keys to show`.

I am guessing `C-c t` was registered as a prefix but I couldn't figure out how to undo this when I looked at the source of `+emacs-binding`.

**Comment by hlissner** [comment]
I'm assuming you are not an evil user, in which case your leader key is `C-c`. Try `(map! :leader "t" #'my-foo)` instead.

**Comment by haji-ali** [comment]
Thanks everything works. Sorry for the trivial questions!
