### ISSUE TITLE
[BUG] doom/forward-to-last-non-comment-or-eol 

### ISSUE THREAD

**Issue by haji-ali** [hlissner/doom-emacs#1802]
I don't quite understand how `doom/forward-to-last-non-comment-or-eol` is supposed to work. I expected that if I have the code
```
Function(); //Comment
```

Then the cursor should behave as follows (pressing `C-e`) for every line (`|` is the cursor location)
```
Fun|ction();      //Comment
Function();|      //Comment
Function();      //Comment|
Function();|      //Comment
```

However, if the cursor starts somewhere inside the comment then I get
```
Function(); //Co|mment
Function(); //Comment|
Function(); //Co|mment
Function(); //Comment|
```

and if I don't have a space between the code and comment, I get

```
|Function();//Comment
Function()|;//Comment
Function();//Comment|
Function()|;//Comment
```
Note that the cursor is one character before the end of line (before the comments starts)

I hope the bug report is clear, let me know if I am something needs clarifying or if I am doing something wrong.

**Comment by hlissner** [comment]
Sorry for the tremendously late response. Does https://github.com/hlissner/doom-emacs/issues/1558 help to understand the logic of this command?

**Comment by haji-ali** [comment]
The behavior described in #1558, concerns empty comment lines. I guess it also applies to non-empty comment lines if the starting position is inside the comments? 

I still think that there's unintended behavior in this case.
```
|Function();//Comment
Function()|;//Comment
Function();//Comment|
Function()|;//Comment
```
Since in this case the cursor jumps to right before the last character when hitting `Ctrl-e` (when there is no empty space between the code and the comment).

**Comment by hlissner** [comment]
Oh I see what you mean. I'll look into it.

**Comment by hlissner** [comment]
As of 2ef0ed9 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
