### ISSUE TITLE
[BUG] Error when installing doom

### ISSUE THREAD

**Issue by teehemkay** [hlissner/doom-emacs#1806]
**Describe the issue**
Start with a brief 1 or 2 sentence summary of issue.

I tried to upgrade doom and got an error message. 

I removed `˜/.emacs.d/.local` and did a `bin/doom -f refresh` and got an error message (see below)
I removed `~/.emacs.d/`, clone the repo and `bin/doom -f refresh` and got  an error message (see below)
I removed `~/.emacs.d/` and `~/.config/doom`, cloned the repo and `~/.emacs.d/bin/doom install` and go the same error message

<details><pre>
  → Building doom-modeline → Cloning shrink-path.el...
--------------------------------------------------

There was an unexpected error:
  Error with packages (doom-package-error)
  (error Failed to run "git"; see buffer *straight-process*)
  Cloning into '/Users/<user>/.emacs.d/.local/straight/repos/shrink-path.el'...
fatal: unable to access 'https://gitlab.com/bennya/shrink-path.el.git/': Couldn't connect to server

Run the command again with the -d (or --debug) option to enable debug
mode and, hopefully, generate a stack trace. If you decide to file a bug
report, please include it!

Emacs outputs to standard error, so you’ll need to redirect stderr to
stdout to pipe this to a file or clipboard!

  e.g. doom -d install 2>&1 | clipboard-program
Error in Doom Emacs core: doom-package-error, (error "Failed to run \"git\"; see buffer *straight-process*"), "Cloning into '/Users/<user>/.emacs.d/.local/straight/repos/shrink-path.el'...
fatal: unable to access 'https://gitlab.com/bennya/shrink-path.el.git/': Couldn't connect to server
</pre></details>

I tried running the command with in debug mode and this is what I got

<details><pre>
❯ ~/.emacs.d/bin/doom -d install 2>&1                                                                                                                     
Loading /Users/<user>/.emacs.d/core/cli/install.el (source)...
Loading /Users/<user>/.emacs.d/core/cli/debug.el (source)...
Loading /Users/<user>/.emacs.d/core/autoload/debug.el (source)...
Loading /Users/<user>/.emacs.d/core/cli/test.el (source)...
Loading /Users/<user>/.emacs.d/core/cli/env.el (source)...
Loading /Users/<user>/.emacs.d/core/cli/upgrade.el (source)...
Loading /Users/<user>/.emacs.d/core/cli/packages.el (source)...
Loading /Users/<user>/.emacs.d/core/cli/autoloads.el (source)...
Loading /Users/<user>/.emacs.d/core/cli/patch-macos.el (source)...
Loading /Users/<user>/.emacs.d/core/cli/byte-compile.el (source)...
DOOM Initializing package.el
DOOM Initializing straight
DOOM Initializing doom-packages
Loading /Users/<user>/.doom.d/init.el (source)...
DOOM Ignoring built-in package so-long
DOOM Ignoring built-in package vc
DOOM Ignoring built-in package vc-annotate
DOOM Ignoring built-in package smerge-mode
DOOM Ignoring built-in package elisp-mode
Loading /Users/<user>/.doom.d/init.el (source)...
Installing Doom Emacs!

> Creating .doom.d/
✓ Created .doom.d/
! init.el already exists, skipping
! config.el already exists, skipping
! packages.el already exists, skipping

DOOM Initializing package.el
DOOM Initializing straight
DOOM Initializing doom-packages
DOOM Ignoring built-in package so-long
DOOM Ignoring built-in package vc
DOOM Ignoring built-in package vc-annotate
DOOM Ignoring built-in package smerge-mode
DOOM Ignoring built-in package elisp-mode
Generate an env file? (see `doom help env` for details) (y or n) y
> Regenerating envvars file at "~/.emacs.d/.local/env"
- Scraping shell environment with 'fish -ic env'
  - Warnings:
  
      <W> fish: Could not send job 5 ('echo "begin; $argv "\n" ;end <&3 3<&-" | source 3<&0') with pgid 7466 to foreground
      tcsetpgrp: Inappropriate ioctl for device
      <W> fish: Could not send job 5 ('echo "begin; $argv "\n" ;end <&3 3<&-" | source 3<&0') with pgid 7466 to foreground
      tcsetpgrp: Inappropriate ioctl for device
      <W> fish: Could not send job 4 ('echo "begin; $argv "\n" ;end <&3 3<&-" | source 3<&0') with pgid 7547 to foreground
      tcsetpgrp: Inappropriate ioctl for device
      <W> fish: Could not send job 4 ('echo "begin; $argv "\n" ;end <&3 3<&-" | source 3<&0') with pgid 7547 to foreground
      tcsetpgrp: Inappropriate ioctl for device
  
  - Ignoring DEBUG
  - Ignoring PWD
  - Ignoring SSH_AGENT_PID
  - Ignoring SSH_AUTH_SOCK
  - Ignoring __CF_USER_TEXT_ENCODING
  - Ignoring __NIX_DARWIN_SET_ENVIRONMENT_DONE
  - Ignoring __fish_nixos_env_preinit_sourced
✓ Successfully generated "~/.emacs.d/.local/env"
Installing plugins
> Installing & building packages...

  → Building doom-modeline...
  → Building doom-modeline → Cloning shrink-path.el...
...
  (progn (if (or manual straight--transaction-alist) nil (straight--transaction-finalize-on-idle)) (if (assq id straight--transaction-alist) nil (setq straight--transaction-alist (cons (cons id later) straight--transaction-alist)) (if now (progn (funcall now)))))
  (progn (let ((--cl-keys-- --cl-rest--)) (while --cl-keys-- (cond ((memq (car --cl-keys--) (quote (:now :later :manual :allow-other-keys))) (setq --cl-keys-- (cdr (cdr --cl-keys--)))) ((car (cdr (memq ... --cl-rest--))) (setq --cl-keys-- nil)) (t (error "Keyword argument %s not one of (:now :later :manual)" (car --cl-keys--)))))) (progn (if (or manual straight--transaction-alist) nil (straight--transaction-finalize-on-idle)) (if (assq id straight--transaction-alist) nil (setq straight--transaction-alist (cons (cons id later) straight--transaction-alist)) (if now (progn (funcall now))))))
  (let* ((now (car (cdr (plist-member --cl-rest-- (quote :now))))) (later (car (cdr (plist-member --cl-rest-- (quote :later))))) (manual (car (cdr (plist-member --cl-rest-- (quote :manual)))))) (progn (let ((--cl-keys-- --cl-rest--)) (while --cl-keys-- (cond ((memq (car --cl-keys--) (quote ...)) (setq --cl-keys-- (cdr ...))) ((car (cdr ...)) (setq --cl-keys-- nil)) (t (error "Keyword argument %s not one of (:now :later :manual)" (car --cl-keys--)))))) (progn (if (or manual straight--transaction-alist) nil (straight--transaction-finalize-on-idle)) (if (assq id straight--transaction-alist) nil (setq straight--transaction-alist (cons (cons id later) straight--transaction-alist)) (if now (progn (funcall now)))))))
  straight--transaction-exec(use-package-\(:type\ git\ :flavor\ melpa\ :host\ github\ :repo\ \"seagle0128/doom-modeline\"\ :package\ \"doom-modeline\"\ :local-repo\ \"doom-modeline\"\)-nil-nil :now (closure ((type . git) (local-repo . "doom-modeline") (package . "doom-modeline") (plist :type git :flavor melpa :host github :repo "seagle0128/doom-modeline" :package "doom-modeline" :local-repo "doom-modeline") (recipe :type git :flavor melpa :host github :repo "seagle0128/doom-modeline" :package "doom-modeline" :local-repo "doom-modeline") (interactive) (cause . " ") (no-build) (no-clone) (melpa-style-recipe . doom-modeline) straight--profile-cache use-package-pre-ensure-function use-package-keywords use-package-ensure-function use-package-defaults t) nil (let ((already-registered (gethash package straight--success-cache)) (available (or (null local-repo) (straight--repository-is-available-p recipe)))) (if (if (let ((object no-clone)) (and (not ...) (functionp object))) (funcall no-clone package available) no-clone) (progn (throw (quote --cl-block-straight-use-package--) nil))) (if available nil (straight--clone-repository recipe cause)) (straight--make-build-cache-available) (let* ((no-build (or (null local-repo) (plist-get recipe :no-build) (if ... ... no-build))) (modified (or (and straight--packages-to-rebuild ... ... ...) (straight--package-might-be-modified-p recipe no-build)))) (let ((func (intern ...)) (table (gethash ... straight--recipe-lookup-cache))) (if (or modified (not ...) (not ...)) (progn (remhash ... straight--recipe-lookup-cache)))) (if no-build nil (straight--add-package-to-load-path recipe)) (run-hook-with-args (quote straight-use-package-prepare-functions) package) (if (and modified (not no-build)) (progn (run-hook-with-args (quote straight-use-package-pre-build-functions) package) (straight--build-package recipe cause))) (straight--declare-successful-build recipe) (if no-build nil (let ((--dolist-tail-- ...)) (while --dolist-tail-- (let ... ... ...))) (straight--add-package-to-info-path recipe) (straight--activate-package-autoloads recipe)) (if (and interactive (not already-registered)) (progn (message (concat "If you want to keep %s, put " "(straight-use-package %s%S) " "in your init-file.") package "'" (intern package))))) (puthash package t straight--success-cache) t)))
  (let* ((plist recipe) (package (plist-get plist :package)) (local-repo (plist-get plist :local-repo)) (type (plist-get plist :type))) (if (eq type (quote built-in)) (progn (throw (quote --cl-block-straight-use-package--) t))) (straight--transaction-exec (intern (format "use-package-%S-%S-%S" recipe (if (let ((object no-clone)) (and (not ...) (functionp object))) (random) no-clone) (if (let ((object no-build)) (and (not ...) (functionp object))) (random) no-build))) :now (function (lambda nil (let ((already-registered (gethash package straight--success-cache)) (available (or ... ...))) (if (if (let ... ...) (funcall no-clone package available) no-clone) (progn (throw ... nil))) (if available nil (straight--clone-repository recipe cause)) (straight--make-build-cache-available) (let* ((no-build ...) (modified ...)) (let (... ...) (if ... ...)) (if no-build nil (straight--add-package-to-load-path recipe)) (run-hook-with-args (quote straight-use-package-prepare-functions) package) (if (and modified ...) (progn ... ...)) (straight--declare-successful-build recipe) (if no-build nil (let ... ...) (straight--add-package-to-info-path recipe) (straight--activate-package-autoloads recipe)) (if (and interactive ...) (progn ...))) (puthash package t straight--success-cache) t)))))
  (let ((recipe (straight--convert-recipe (or (straight--get-overridden-recipe (if (listp melpa-style-recipe) (car melpa-style-recipe) melpa-style-recipe)) melpa-style-recipe) cause))) (straight--register-recipe recipe) (let* ((plist recipe) (package (plist-get plist :package)) (local-repo (plist-get plist :local-repo)) (type (plist-get plist :type))) (if (eq type (quote built-in)) (progn (throw (quote --cl-block-straight-use-package--) t))) (straight--transaction-exec (intern (format "use-package-%S-%S-%S" recipe (if (let (...) (and ... ...)) (random) no-clone) (if (let (...) (and ... ...)) (random) no-build))) :now (function (lambda nil (let ((already-registered ...) (available ...)) (if (if ... ... no-clone) (progn ...)) (if available nil (straight--clone-repository recipe cause)) (straight--make-build-cache-available) (let* (... ...) (let ... ...) (if no-build nil ...) (run-hook-with-args ... package) (if ... ...) (straight--declare-successful-build recipe) (if no-build nil ... ... ...) (if ... ...)) (puthash package t straight--success-cache) t))))))
  (catch (quote --cl-block-straight-use-package--) (let ((recipe (straight--convert-recipe (or (straight--get-overridden-recipe (if ... ... melpa-style-recipe)) melpa-style-recipe) cause))) (straight--register-recipe recipe) (let* ((plist recipe) (package (plist-get plist :package)) (local-repo (plist-get plist :local-repo)) (type (plist-get plist :type))) (if (eq type (quote built-in)) (progn (throw (quote --cl-block-straight-use-package--) t))) (straight--transaction-exec (intern (format "use-package-%S-%S-%S" recipe (if (let ... ...) (random) no-clone) (if (let ... ...) (random) no-build))) :now (function (lambda nil (let (... ...) (if ... ...) (if available nil ...) (straight--make-build-cache-available) (let* ... ... ... ... ... ... ... ...) (puthash package t straight--success-cache) t)))))))
  straight-use-package(doom-modeline nil nil " ")
  (and (straight-use-package (intern package) nil nil " ") (not existed-p) (file-directory-p (straight--repos-dir package)) (setq n (1+ n)))
  (condition-case e (and (straight-use-package (intern package) nil nil " ") (not existed-p) (file-directory-p (straight--repos-dir package)) (setq n (1+ n))) ((debug error) (signal (quote doom-package-error) (list e (straight--process-get-output)))))
  (let ((existed-p (file-directory-p (straight--repos-dir package)))) (condition-case e (and (straight-use-package (intern package) nil nil " ") (not existed-p) (file-directory-p (straight--repos-dir package)) (setq n (1+ n))) ((debug error) (signal (quote doom-package-error) (list e (straight--process-get-output))))))
  (let* ((plist (gethash package straight--recipe-cache)) (local-repo (plist-get plist :local-repo))) (let ((existed-p (file-directory-p (straight--repos-dir package)))) (condition-case e (and (straight-use-package (intern package) nil nil " ") (not existed-p) (file-directory-p (straight--repos-dir package)) (setq n (1+ n))) ((debug error) (signal (quote doom-package-error) (list e (straight--process-get-output)))))))
  (straight--with-plist (gethash package straight--recipe-cache) (local-repo) (let ((existed-p (file-directory-p (straight--repos-dir package)))) (condition-case e (and (straight-use-package (intern package) nil nil " ") (not existed-p) (file-directory-p (straight--repos-dir package)) (setq n (1+ n))) ((debug error) (signal (quote doom-package-error) (list e (straight--process-get-output)))))))
  (while --dolist-tail-- (setq package (car --dolist-tail--)) (straight--with-plist (gethash package straight--recipe-cache) (local-repo) (let ((existed-p (file-directory-p (straight--repos-dir package)))) (condition-case e (and (straight-use-package (intern package) nil nil " ") (not existed-p) (file-directory-p (straight--repos-dir package)) (setq n (1+ n))) ((debug error) (signal (quote doom-package-error) (list e (straight--process-get-output))))))) (setq --dolist-tail-- (cdr --dolist-tail--)))
  (let ((--dolist-tail-- (hash-table-keys straight--recipe-cache)) package) (while --dolist-tail-- (setq package (car --dolist-tail--)) (straight--with-plist (gethash package straight--recipe-cache) (local-repo) (let ((existed-p (file-directory-p (straight--repos-dir package)))) (condition-case e (and (straight-use-package (intern package) nil nil " ") (not existed-p) (file-directory-p (straight--repos-dir package)) (setq n (1+ n))) ((debug error) (signal (quote doom-package-error) (list e ...)))))) (setq --dolist-tail-- (cdr --dolist-tail--))))
  (let ((n 0)) (let ((--dolist-tail-- (hash-table-keys straight--recipe-cache)) package) (while --dolist-tail-- (setq package (car --dolist-tail--)) (straight--with-plist (gethash package straight--recipe-cache) (local-repo) (let ((existed-p (file-directory-p ...))) (condition-case e (and (straight-use-package ... nil nil " ") (not existed-p) (file-directory-p ...) (setq n ...)) ((debug error) (signal ... ...))))) (setq --dolist-tail-- (cdr --dolist-tail--)))) (if (= n 0) (ignore (print! (success "No packages need to be installed"))) (print! (success "Installed & built %d packages") n) t))
  (let ((doom-format-indent (+ 2 doom-format-indent))) (let ((n 0)) (let ((--dolist-tail-- (hash-table-keys straight--recipe-cache)) package) (while --dolist-tail-- (setq package (car --dolist-tail--)) (straight--with-plist (gethash package straight--recipe-cache) (local-repo) (let ((existed-p ...)) (condition-case e (and ... ... ... ...) (... ...)))) (setq --dolist-tail-- (cdr --dolist-tail--)))) (if (= n 0) (ignore (print! (success "No packages need to be installed"))) (print! (success "Installed & built %d packages") n) t)))
  (print-group! (let ((n 0)) (let ((--dolist-tail-- (hash-table-keys straight--recipe-cache)) package) (while --dolist-tail-- (setq package (car --dolist-tail--)) (straight--with-plist (gethash package straight--recipe-cache) (local-repo) (let ((existed-p ...)) (condition-case e (and ... ... ... ...) (... ...)))) (setq --dolist-tail-- (cdr --dolist-tail--)))) (if (= n 0) (ignore (print! (success "No packages need to be installed"))) (print! (success "Installed & built %d packages") n) t)))
  doom-packages-install(nil)
  (if (member "--no-install" args) (print! (warn "- Not installing plugins, as requested")) (print! "Installing plugins") (doom-packages-install doom-auto-accept))
  (let ((default-directory (doom-path "~"))) (if (member "--no-config" args) (print! (warn "Not copying private config template, as requested")) (print! "> Creating %s" (relpath doom-private-dir)) (make-directory doom-private-dir (quote parents)) (print! (success "Created %s") (relpath doom-private-dir)) (mapc (function (lambda (file) (let* ((fn file) (filename ...)) (if (file-exists-p! filename doom-private-dir) (print! ... filename) (print! ... ... filename) (let ... ...) (print! ...))))) (quote (("init.el" lambda nil (insert-file-contents (doom-path doom-emacs-dir "init.example.el"))) ("config.el" lambda nil (insert! ";;; %sconfig.el -*- lexical-binding: t; -*-\n\n" ";; Place your private configuration here\n" (...))) ("packages.el" lambda nil (insert! ";; -*- no-byte-compile: t; -*-\n;;; %spackages.el\n\n" ";;; Examples:\n" ";; (package! some-package)\n" ";; (package! another-package :recipe (:host github :repo \"username/repo\"))\n" ";; (package! builtin-package :disable t)\n" (...))))))) (doom-initialize-packages (quote force-p)) (if (member "--no-env" args) (print! (warn "- Not generating envvars file, as requested")) (if (or doom-auto-accept (y-or-n-p "Generate an env file? (see `doom help env` for details)")) (progn (doom-reload-env-file (quote force-p))))) (if (member "--no-install" args) (print! (warn "- Not installing plugins, as requested")) (print! "Installing plugins") (doom-packages-install doom-auto-accept)) (print! "Regenerating autoloads files") (doom-reload-autoloads nil (quote force-p)) (if (member "--no-fonts" args) (print! (warn "- Not installing fonts, as requested")) (if (or doom-auto-accept (y-or-n-p "Download and install all-the-icon's fonts?")) (progn (require (quote all-the-icons)) (let ((window-system (cond ... ...))) (all-the-icons-install-fonts (quote yes)))))) (print! (success "\nFinished! Doom is ready to go!\n")) (let ((temp-buffer (generate-new-buffer " *temp*"))) (save-current-buffer (set-buffer temp-buffer) (unwind-protect (progn (doom-template-insert "QUICKSTART_INTRO") (print! (buffer-string))) (and (buffer-name temp-buffer) (kill-buffer temp-buffer))))))
  doom-cli-install()
  apply(doom-cli-install nil)
  (and t (apply fn args))
  (let* ((ret (and t (apply fn args)))) (if ret (progn (print! "\n%s" (success "Finished! (%.4fs)" (float-time (time-subtract (current-time) start-time)))) (run-hooks (quote doom-cli-post-execute-hook)) ret) nil))
  (unwind-protect (let* ((ret (and t (apply fn args)))) (if ret (progn (print! "\n%s" (success "Finished! (%.4fs)" (float-time (time-subtract ... start-time)))) (run-hooks (quote doom-cli-post-execute-hook)) ret) nil)) (run-hooks (quote doom-cli-post-error-execute-hook)))
  (let ((start-time (current-time))) (run-hooks (quote doom-cli-pre-execute-hook)) (unwind-protect (let* ((ret (and t (apply fn args)))) (if ret (progn (print! "\n%s" (success "Finished! (%.4fs)" (float-time ...))) (run-hooks (quote doom-cli-post-execute-hook)) ret) nil)) (run-hooks (quote doom-cli-post-error-execute-hook))))
  (if show-help (doom--dispatch-help fn args) (let ((start-time (current-time))) (run-hooks (quote doom-cli-pre-execute-hook)) (unwind-protect (let* ((ret (and t (apply fn args)))) (if ret (progn (print! "\n%s" (success "Finished! (%.4fs)" ...)) (run-hooks (quote doom-cli-post-execute-hook)) ret) nil)) (run-hooks (quote doom-cli-post-error-execute-hook)))))
  (let ((fn (doom--dispatch-command cmd))) (if (fboundp fn) nil (user-error "%S is not any command *I* know!" cmd)) (if show-help (doom--dispatch-help fn args) (let ((start-time (current-time))) (run-hooks (quote doom-cli-pre-execute-hook)) (unwind-protect (let* ((ret (and t ...))) (if ret (progn (print! "\n%s" ...) (run-hooks ...) ret) nil)) (run-hooks (quote doom-cli-post-error-execute-hook))))))
  doom-dispatch("install" nil)
  (condition-case e (doom-dispatch (car args) (cdr args)) (user-error (print! (error "%s\n") (error-message-string e)) (print! (yellow "See 'doom help %s' for documentation on this command.") (car args))) ((debug error) (message "--------------------------------------------------\n") (message "There was an unexpected error:") (message "  %s (%s)" (get (car e) (quote error-message)) (car e)) (let ((--dolist-tail-- (cdr e)) item) (while --dolist-tail-- (setq item (car --dolist-tail--)) (message "  %s" item) (setq --dolist-tail-- (cdr --dolist-tail--)))) (if debug-on-error nil (message (concat "\nRun the command again with the -d (or --debug) option to enable debug\n" "mode and, hopefully, generate a stack trace. If you decide to file a bug\n" "report, please include it!\n\n" "Emacs outputs to standard error, so you'll need to redirect stderr to\n" "stdout to pipe this to a file or clipboard!\n\n" "  e.g. doom -d install 2>&1 | clipboard-program")) (signal (quote doom-error) e))))
  (cond ((or (not args) (and (not (cdr args)) (member (car args) (quote ("help" "h"))))) (if args nil (print! (error "No command detected.\n"))) (usage)) ((require (quote core-cli)) (setq argv nil) (condition-case e (doom-dispatch (car args) (cdr args)) (user-error (print! (error "%s\n") (error-message-string e)) (print! (yellow "See 'doom help %s' for documentation on this command.") (car args))) ((debug error) (message "--------------------------------------------------\n") (message "There was an unexpected error:") (message "  %s (%s)" (get (car e) (quote error-message)) (car e)) (let ((--dolist-tail-- (cdr e)) item) (while --dolist-tail-- (setq item (car --dolist-tail--)) (message "  %s" item) (setq --dolist-tail-- (cdr --dolist-tail--)))) (if debug-on-error nil (message (concat "\nRun the command again with the -d (or --debug) option to enable debug\n" "mode and, hopefully, generate a stack trace. If you decide to file a bug\n" "report, please include it!\n\n" "Emacs outputs to standard error, so you'll need to redirect stderr to\n" "stdout to pipe this to a file or clipboard!\n\n" "  e.g. doom -d install 2>&1 | clipboard-program")) (signal (quote doom-error) e))))))
  (if (not noninteractive) (let ((doom-interactive-mode t)) (load (expand-file-name "init.el" user-emacs-directory) nil (quote nomessage)) (doom-run-all-startup-hooks-h)) (load (expand-file-name "core/core.el" user-emacs-directory) nil (quote nomessage)) (doom-initialize (quote force-p)) (doom-initialize-modules) (cond ((or (not args) (and (not (cdr args)) (member (car args) (quote ("help" "h"))))) (if args nil (print! (error "No command detected.\n"))) (usage)) ((require (quote core-cli)) (setq argv nil) (condition-case e (doom-dispatch (car args) (cdr args)) (user-error (print! (error "%s\n") (error-message-string e)) (print! (yellow "See 'doom help %s' for documentation on this command.") (car args))) ((debug error) (message "--------------------------------------------------\n") (message "There was an unexpected error:") (message "  %s (%s)" (get (car e) (quote error-message)) (car e)) (let ((--dolist-tail-- ...) item) (while --dolist-tail-- (setq item ...) (message "  %s" item) (setq --dolist-tail-- ...))) (if debug-on-error nil (message (concat "\nRun the command again with the -d (or --debug) option to enable debug\n" "mode and, hopefully, generate a stack trace. If you decide to file a bug\n" "report, please include it!\n\n" "Emacs outputs to standard error, so you'll need to redirect stderr to\n" "stdout to pipe this to a file or clipboard!\n\n" "  e.g. doom -d install 2>&1 | clipboard-program")) (signal (quote doom-error) e)))))))
  (let ((args (cdr (cdr (cdr command-line-args))))) (while (condition-case nil (progn (string-prefix-p "-" (car args))) (error nil)) (let* ((val (car-safe (prog1 args (setq args ...))))) (cond ((member val (quote ("--help" "-h"))) (setq args (cons "help" args))) ((member val (quote ("--debug" "-d"))) (setenv "DEBUG" "1") (message "Debug mode on")) ((member val (quote ("--insecure" "-i"))) (setenv "INSECURE" "1") (message "Insecure mode on")) ((member val (quote ("--private" "-p"))) (setq doom-private-dir (expand-file-name (concat ... "/"))) (setenv "DOOMDIR" doom-private-dir) (message "DOOMDIR changed to %s" doom-private-dir) (or (file-directory-p doom-private-dir) (message "Warning: %s does not exist" (abbreviate-file-name doom-private-dir)))) ((member val (quote ("--local" "-l"))) (setq doom-local-dir (expand-file-name (concat ... "/"))) (setenv "DOOMLOCALDIR" doom-local-dir) (message "DOOMLOCALDIR changed to %s" doom-local-dir)) ((member val (quote ("--emacsd" "-e"))) (setq user-emacs-directory (expand-file-name (concat ... "/"))) (message "Emacs directory changed to %s" user-emacs-directory)) ((member val (quote ("--yes" "-y"))) (setenv "YES" "1") (message "Auto-yes mode on")) (t nil)))) (if (file-directory-p user-emacs-directory) nil (error "%s does not exist" user-emacs-directory)) (if (not noninteractive) (let ((doom-interactive-mode t)) (load (expand-file-name "init.el" user-emacs-directory) nil (quote nomessage)) (doom-run-all-startup-hooks-h)) (load (expand-file-name "core/core.el" user-emacs-directory) nil (quote nomessage)) (doom-initialize (quote force-p)) (doom-initialize-modules) (cond ((or (not args) (and (not (cdr args)) (member (car args) (quote ...)))) (if args nil (print! (error "No command detected.\n"))) (usage)) ((require (quote core-cli)) (setq argv nil) (condition-case e (doom-dispatch (car args) (cdr args)) (user-error (print! (error "%s\n") (error-message-string e)) (print! (yellow "See 'doom help %s' for documentation on this command.") (car args))) ((debug error) (message "--------------------------------------------------\n") (message "There was an unexpected error:") (message "  %s (%s)" (get ... ...) (car e)) (let (... item) (while --dolist-tail-- ... ... ...)) (if debug-on-error nil (message ...) (signal ... e))))))))
  eval-buffer(#<buffer  *load*> nil "/Users/<user>/.emacs.d/bin/doom" nil t)  ; Reading at buffer position 5614
  load-with-code-conversion("/Users/<user>/.emacs.d/bin/doom" "/Users/<user>/.emacs.d/bin/doom" nil t)
  load("/Users/<user>/.emacs.d/bin/doom" nil t t)
  command-line-1(("-scriptload" "/Users/<user>/.emacs.d/bin/doom" "--" "install"))
  command-line()
  normal-top-level()

~ 7s
❯    
</pre></details>

I've tested using a browser that my Mac does indeed have access to the gitlab repo, and it does.

Any idea what's going on?

**Comment by hlissner** [comment]
It seems like a simple connection issue. Reinstalling Doom shouldn't have any any effect. Not sure if there's anything that can be done about this.

**Comment by teehemkay** [comment]
Thanks for looking into it. 
Yeah, the error seems to indicate some kind of network connection issue indeed.

Maybe my terminal was borked in some way. I'll try restarting it and installing again.

**Comment by teehemkay** [comment]
Yep, the problem was with my terminal. 
Restarted it and the install went like a cinch.
Sorry for the false alarm
