### ISSUE TITLE
[BUG] lorri overlays in direnv README.org is broken (on MacOS)

### ISSUE THREAD

**Issue by teehemkay** [hlissner/doom-emacs#1808]
**Describe the issue**

The overlay as documented in the README won't build on MacOS (didn't test on Linux of NixOS).

Switching to `import` instead of `callPackage` fixes the issue (FWIW that's what `lorri` itself does in its `release.nix` ).

The snippet below build correctly. I also updated `rev` and `sha256` below to the latest (from branch `rolling-release`).

```nix
nixpkgs.overlays = [
  (self: super: {
    lorri =
      let src = (super.fetchFromGitHub {
            owner = "target";
            repo = "lorri";
            rev = "38eae3d487526ece9d1b8c9bb0d27fb45cf60816";
            sha256 = "11k9lxg9cv6dlxj4haydvw4dhcfyszwvx7jx9p24jadqsy9jmbj4";
          });
      in import src { inherit src; };
  })
];

```

**Comment by hlissner** [comment]
I've updated the readme in efbc57a. The old snippet worked for me on NixOS, but not with the new rev+sha256. Thanks for bringing it to my attention!
