### ISSUE TITLE
[BUG] emacs-lisp-mode show same doc

### ISSUE THREAD

**Issue by iamburning** [hlissner/doom-emacs#1809]
**Describe the issue**
doom sandbox without private config
in emacs-lisp-mode with ":lang emacs-lisp"
press "F1" always show the same doc

**Comment by zhelezov** [comment]
`F1` is the `help-command` prefix key, bound also to `C-h` or `SPC h` in normal mode. So yeah, it is always the same by definition, it is a prefix key.

**Comment by iamburning** [comment]
with (company +childframe) (setq company-box-doc-enable t) 
same doc too

**Comment by hlissner** [comment]
I don't understand the issue. Can you include a screenshot/cast?

**Comment by iamburning** [comment]
![Peek 2019-09-23 08-18](https://user-images.githubusercontent.com/17723587/65396653-09975600-dddb-11e9-8e8c-bd41a7e6355d.gif)
