### ISSUE TITLE
[BUG] `doom run -p <something>` not working as expected

### ISSUE THREAD

**Issue by UndeadKernel** [hlissner/doom-emacs#1814]
After trying to test the configuration of a fellow Doomer, I saw that the `run` command of the `doom` script does not do what it's supposed to do:
- If the command `doom run -p <something>` is run (as stated in the help), the `-p` option will be ignored and passed to emacs directly. This happend because [this while](https://github.com/hlissner/doom-emacs/blob/5deb9b2ce96a45b4d27e8ae6e1655dd70e7a7df1/bin/doom#L52) assumes that the `args` start with a command (i.e., something with `-`). However, `args` start with the name of the program (even after the `shift` bash command).
- If the command `doom -p <something> run` is run, the `-p` option is parsed correctly but then emacs is not started correctly. Emacs will just quit immediately.

I tried fixing it and sending a PR but noticed that I would have to make a lot of changes. It's probably better that you take a look at it @hlissner.

**Comment by hlissner** [comment]
Doom's command line interface is overdue a rewrite, to address a number of issues, including this one. It'll take a while for me to get to it, so for the time being it's best you use the `DOOMDIR` environment variable instead:

```sh
DOOMDIR=new/doom.d/location doom run
```

**Comment by UndeadKernel** [comment]
Hi Henrik,

If you tell me which issues you'd like to address (and if you want to trust
me [no disrespect if you don't]), I'd be happy to rewrite the `doom` CLI
according to your specifications.

Otherwise, I'll patiently wait playing around with my thumbs :D

**Comment by hlissner** [comment]
bin/doom no longer has a `-p` switch. The `DOOMDIR` and `EMACSDIR` envvars are now the canonical way to change those paths for `bin/doom`. Since I have no plans to reinstate it I think I'll consider this resolved.
