### ISSUE TITLE
[BUG] eldoc and company for Rust library crate

### ISSUE THREAD

**Issue by alxiong** [hlissner/doom-emacs#1822]
**Describe the issue**
eldoc not supported in rust-mode for library crate, nor does the company auto-complete works

*NOTE that:* auto-complete and eldoc works perfectly fine with binary crate.
[see rust book for def of crate](https://doc.rust-lang.org/book/ch07-01-packages-and-crates.html):
 > A crate is a binary or library

**Steps to reproduce**
1. create a new rust package: `cargo new --lib bug`
2. try autocomplete by editing `bug/src/lib.rs`: 
```rust
mod tests {
    #[test]
    fn it_works() {
        assert_eq!(2 + 2, 4);
    }
    fn test() {
        it_works(); // as you type this line, no auto-completion
    }
}
```
3. now testing eldoc, appending this to the file, moving cursor over `Rectangle`, no eldoc
```rust
mod random {
    struct Rectangle {
        width: u32,
        height: u32,
    }
}
```
4. `M-x eldoc-mode` will gives an msg: `There is no ElDoc support in this buffer`
5. moreover, `format(+onsave)` or particularly with `rustic-cargo-fmt` is not autofmting either.

Thanks for the help

**Comment by hlissner** [comment]
1. Can you reproduce this in vanilla Emacs and/or vanilla Doom [using the sandbox](https://gist.github.com/hlissner/3910fcf5ef14ab77657f269ba9b37f94)?

2. Have you installed rls on your system?

3. Please include your `M-x doom/info`. _Always_ include your `M-x doom/info` for bug reports.

4. Does rustic-mode have eldoc support at all? If `M-x eldoc-mode` reports no support, it generally means there is no support.

> moreover, format(+onsave) or particularly with rustic-cargo-fmt is not autofmting either.

5. What happens when you do `M-x format-all-buffer`?

6. What does `M-; (executable-find "rustfmt")` return?

**Comment by alxiong** [comment]
sorry... stupid mistake on my side, forget I didn't install `rls`, false alarm

Thanks for the reply, will pay attention for future bug report on the format. thanks!

**Comment by zhelezov** [comment]
No eldoc support here either, it doesn't matter if it's binary or library crate. eldoc doesn't complain about not having any support, `M-x eldoc-mode` toggles it with with no visible effect. `rls` is found and started. If I run vanilla Emacs sandbox and load lsp, eldoc signatures are there though.

My `doom/info`:
<details>

```
emacs   version    26.2
        features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LCMS2
        build      Apr 30, 2019
        buildopts  (--build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-dbus --with-gif --with-jpeg --with-png --with-rsvg --with-tiff --with-xft --with-xpm --with-x-toolkit=gtk3 --with-gpm=no --with-xwidgets --with-modules build_alias=x86_64-redhat-linux-gnu host_alias=x86_64-redhat-linux-gnu 'CFLAGS=-DMAIL_USE_LOCKF -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection' LDFLAGS=-Wl,-z,relro PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig)
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop 89242f83 2019-09-23 13:40:16 -0400
system  type       gnu/linux
        config     x86_64-redhat-linux-gnu
        shell      /bin/bash
        uname      Linux 5.2.15-200.fc30.x86_64 #1 SMP Mon Sep 16 15:17:36 UTC 2019 x86_64
        path       (~/.local/lib/perl5/bin ~/.pyenv/shims ~/.pyenv/bin ~/.emacs.d/bin ~/.local/bin ~/.cargo/bin ~/.cabal/bin ~/.perl6/bin ~/Source/go/bin ~/.local/lib/npm/bin /usr/share/Modules/bin /usr/local/bin /usr/local/sbin /usr/bin /usr/sbin /sbin /usr/libexec/emacs/26.2/x86_64-redhat-linux-gnu)
config  envfile    nil
        elc-files  0
        modules    (:completion company (ivy +prescient +icons) :ui deft doom doom-dashboard doom-quit hl-todo hydra modeline nav-flash ophints (popup +all +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor evil file-templates fold format multiple-cursors rotate-text snippets word-wrap :emacs dired electric vc :term eshell vterm :tools eval (flycheck +childframe) (flyspell +hunspell) (lookup +docsets) lsp magit (pass +auth) pdf :lang assembly (cc +lsp) common-lisp data emacs-lisp (haskell +intero) (latex +latexmk) ledger markdown (org +dragndrop +ipython +pandoc +present) perl (python +lsp) (rust +lsp) scheme sh :email mu4e :app write :config default)
        packages   (n/a)
        elpa       (n/a)
```
</details>

**Comment by A6GibKm** [comment]
Can confirm, eldoc-mode is not doing anything.

**Comment by hlissner** [comment]
Just pushed 364cec34e a while ago, which may fix your issue. Please update and let me know.
