### ISSUE TITLE
Elfeed filter binding

### ISSUE THREAD

**Issue by thequantumcat** [hlissner/doom-emacs#183]
When using Elfeed, I can't seem to filter specific tags. From the code I saw that `elfeed-search-live-filter` has been bound to `s`, but this only invokes evil-snipe. I had the same issue in my manually installed  version of Ranger, where `s` was also bound to a function from evil-snipe.

**Comment by hlissner** [comment]
I've been struggling with this issue in evil-snipe for a while. If it isn't too much trouble, please try the following:

```emacs-lisp
(push 'elfeed-show-mode evil-snipe-disabled-modes)
(push 'elfeed-search-mode evil-snipe-disabled-modes)
```

This isn't expected to work, but if it magically does, I'd like to know.

If it doesn't, add this to the above:

```emacs-lisp
(defun evil-snipe-inhibit-hook ()
  (when (and (or evil-snipe-local-mode evil-snipe-override-local-mode)
             (not (eq major-mode 'fundamental-mode))
             (apply #'derived-mode-p evil-snipe-disabled-modes))
    (when evil-snipe-local-mode (evil-snipe-local-mode -1))
    (when evil-snipe-override-local-mode (evil-snipe-override-local-mode -1))))
(add-hook 'evil-snipe-local-mode-hook #'evil-snipe-inhibit-hook)
(add-hook 'evil-snipe-override-local-mode-hook #'evil-snipe-inhibit-hook)
```

This is a bit of a hack, but this problem has plagued evil-snipe for a while, and if it solves the problem, I suppose it's better than nothing. If it works, I'll push it to evil-snipe upstream.

Let me know!

**Comment by thequantumcat** [comment]
After  the addition of: 
```elisp
(setq evil-snipe-disabled-modes '(magit-mode elfeed-show-mode elfeed-search-mode))
```
in your latest commit, together with 
```elisp
(push 'elfeed-show-mode evil-snipe-disabled-modes)
(push 'elfeed-search-mode evil-snipe-disabled-modes)
```
it  did the trick. Thank you!

**Comment by hlissner** [comment]
Ah, I forgot to update this. Yeah, the recent evil-snipe commit fixed this problem. Glad it helped!
