### ISSUE TITLE
[BUG] the python completion give imperfection hint

### ISSUE THREAD

**Issue by xiaozhu1337** [hlissner/doom-emacs#1833]
**Describe the issue**
when I use (https://github.com/seagle0128/.emacs.d),I have right hint in python completion(,this startkit use ms-lsp),this startkit identified the "text" is an object's property. But when I use doom emacs(whether add lsp feature or not), the "text" is identified as a function
![image](https://user-images.githubusercontent.com/50901869/65827600-4f18bf00-e2c4-11e9-9c04-3a91bfba9829.png)
![image](https://user-images.githubusercontent.com/50901869/65827601-550ea000-e2c4-11e9-91cf-698d799162f8.png)

**Steps to reproduce**

**System information**

**Comment by hlissner** [comment]
These are using different company frontends to display the results. Centaur Emacs is using company-box. Enable `:completion (company +childframe)` to use company-box in Doom.

**Comment by hlissner** [comment]
Looks like the issue was that a different LSP backend is being used. Centaur Emacs uses (and auto-installs) mspyls by default. Doom does not auto-install it. It will use it if it is available, however. `M-x lsp-python-ms-setup` will install it.
