### ISSUE TITLE
[BUG] `doom update` hangs, errors & timeouts

### ISSUE THREAD

**Issue by CGenie** [hlissner/doom-emacs#1837]
**Describe the feature**
When module git branch (eg. `org-ql`) has a hard reset and new commits on top of it, `doom update` just hangs. I need to manually go to `$HOME/.emacs.d/.local/straight/repos/<module>`, do `git reset --hard HEAD~50`, and then `doom update` works fine.

Least doom should do is report such an issue and proceed with upgrading of next module.

**System information**
<details><pre>
((emacs
  (version . "26.3")
  (features . "XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2")
  (build . "Aug 29, 2019")
  (buildopts "--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-modules 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop 3f7e0fd10 2019-09-29 23:12:43 -0400"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/usr/bin/zsh")
  (uname . "Linux 5.3.1-arch1-1-ARCH #1 SMP PREEMPT Sat Sep 21 11:33:49 UTC 2019 x86_64")
  (path "~/.nix-profile/bin" "~/.local/bin" "~/go/bin" "~/.opam/azuracast-stats/bin" "/tmp/fnm-shell-240216/bin" "~/.gem/ruby/2.2.0/bin" "~/perl5/bin" "~/.gem/ruby/2.1.0/bin" "~/bin" "~/.cabal/bin" "~/.cargo/bin" "~/.nix-profile/bin" "~/.local/bin" "~/go/bin" "~/.opam/azuracast-stats/bin" "/tmp/fnm-shell-9408123/bin" "~/.gem/ruby/2.2.0/bin" "~/perl5/bin" "~/.gem/ruby/2.1.0/bin" "~/bin" "~/.cabal/bin" "~/.cargo/bin" "/usr/local/sbin" "/usr/local/bin" "/usr/bin" "/opt/android-ndk" "/opt/android-sdk/platform-tools" "/usr/lib/emscripten" "/usr/lib/jvm/default/bin" "/usr/bin/site_perl" "/usr/bin/vendor_perl" "/usr/bin/core_perl" "/usr/lib/emacs/26.3/x86_64-pc-linux-gnu" "~/.nvm/versions/node/v8.10.0/bin" "~/.nvm/versions/node/v8.10.0/bin"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company (ivy +fuzzy) :ui doom doom-dashboard doom-quit hl-todo indent-guides modeline nav-flash neotree ophints (popup +all +defaults) pretty-code treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold multiple-cursors parinfer rotate-text snippets :emacs (dired +ranger +icons) electric vc :term eshell :tools direnv docker eval flycheck gist (lookup +docsets) lsp magit make pass pdf :lang data erlang emacs-lisp fsharp go (haskell +intero) hy javascript latex lua markdown nix ocaml (org +dragndrop +ipython +pandoc +present) perl purescript python racket rust sh web :email notmuch :app calendar irc :config (default +bindings +smartparens))
  (packages add-node-modules-path doom-themes emms helm-org-rifle hledger-mode keyfreq ledger-mode general golden-ratio org-mime org-ql "(org-sidebar :recipe (:host github :repo \"alphapapa/org-sidebar\"))" posframe reason-mode repl-toggle salt-mode tuareg "(vc-fossil :recipe (:host github :repo \"venks1/emacs-fossil\" :branch \"trunk\"))")
  (elpa "s" "posframe" "general" "async")))
</pre></details>

**Comment by zhelezov** [comment]
Yep, happened a couple of times for me too and a `git reset` to the parent commit was the fix.

**Comment by hlissner** [comment]
Folks have reported several issues with `doom upgrade`. 

I am aware of these and am working on a solution, and have decided to use this issue as a catch-all for them. For the time being, here are the common issues and their respective workarounds:

### `doom upgrade` hangs indefinitely while updating some packages

You'll need to delete said package(s) manually from `~/.emacs.d/.local/straight/{build,repos}/`, then run `doom refresh -f`.

### "No upstream configured for branch" errors

<details><summary>Example:</summary>

```
There was an unexpected error:
  error (error)
Wrong type argument: listp, "There were errors:

   - company-anaconda: ((error Failed to run \"git\"; see buffer *straight-process*) fatal: no upstream configured for branch 'master')
   - anaconda-mode: ((error Failed to run \"git\"; see buffer *straight-process*) fatal: no upstream configured for branch 'master')"
```

</details>

Same solution as above: delete the listed packages manually.

### Threads time out frequently.

<details><summary>Example:</summary>
```
 .
  .
  ! A thread has timed out. The following packages were skipped: melpa, gnu-elpa-mirror, emacsmirror-mirror, straight, bind-key, async, dotenv-mode, auto-minor-mode, all-the-icons, hide-mode-line, highlight-numbers, rainbow-delimiters, restart-emacs, better-jumper, dtrt-indent, helpful, ns-auto-titlebar, pcre2el, smartparens, so-long, osx-clipboard, undo-tree, ws-butler, projectile
  . 11%
  . 22%
  . 33%
  . 44%
```

</details>

For this, you'll need to either:

+ Increase the timeout (from the default 45s): `doom upgrade -t 160` or 
+ Delete the packages listed in the "thread has timed out" message from `~/.emacs.d/.local/straight/{build,repos}/`, then run `doom refresh -f`. 

### Doom throws "file-missing" errors at startup after `doom upgrade`

This means the autoloads files weren't generated correctly. `doom refresh -f` should address this. If not, run `doom rebuild -f`.

----

I'll keep you posted.

**Comment by CGenie** [comment]
Thank you for your hard work on the whole project!

Przemek

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
