### ISSUE TITLE
How to set evil normal state cursor color

### ISSUE THREAD

**Issue by forrestchang** [hlissner/doom-emacs#1848]
What would you like to know?

How to change cursor color?

I tried:

```elisp
(set-cursor-color "#FF6F65")

(evil-set-cursor-color "#FF6F65")

(setq +evil--default-cursor-color "#FF6F65")

(setq +evil--emacs-cursor-color "#FF6F65")

(custom-set-faces '(cursor ((t (:background "#FF6F65")))))
```

None of them works.

**Comment by nitros12** [comment]
I've found ```elisp
(setq evil-normal-state-cursor '(box "light blue")
      evil-insert-state-cursor '(bar "medium sea green")
      evil-visual-state-cursor '(hollow "orange"))
```
To work for me
