### ISSUE TITLE
[BUG] +latex/LaTeX-indent-item breaks fill-paragraph

### ISSUE THREAD

**Issue by jonathye** [hlissner/doom-emacs#1849]
**Describe the issue**
In the latex module, `+latex/Latex-indent-item` is defined and added to `LaTeX-indent-envvironment-list`. While it provides a better indentation for certain environments, it also breaks `fill-paragraph` in `\item`s.
I believe this function is taken from [this stackoverflow post](https://emacs.stackexchange.com/a/3100). The OP also confirmed that `fill-paragraph` doesn't work anymore in a follow-up comment.
I found a solution in [this github repo](https://github.com/thisirs/dotemacs), and adapted it in my private config. It works like a charm, although I don't know auctex enough to understand it.
```emacs-lisp
  (defun LaTeX-fill-region-as-paragraph-fix (oldfun from to &optional justify-flag)
    (let ((LaTeX-indent-environment-list LaTeX-indent-environment-list))
      (setq LaTeX-indent-environment-list
            (remove '("enumerate" +latex/LaTeX-indent-item) LaTeX-indent-environment-list))
      (setq LaTeX-indent-environment-list
            (remove '("itemize" +latex/LaTeX-indent-item) LaTeX-indent-environment-list))
      (funcall oldfun from to justify-flag)))

  (advice-add 'LaTeX-fill-region-as-paragraph
              :around
              'LaTeX-fill-region-as-paragraph-fix)

  (defun LaTeX-fill-region-as-para-do-fix (oldfun from end-marker justify-flag)
    (let ((LaTeX-indent-environment-list LaTeX-indent-environment-list))
      (add-to-list 'LaTeX-indent-environment-list '("itemize" +latex/LaTeX-indent-item))
      (add-to-list 'LaTeX-indent-environment-list '("enumerate" +latex/LaTeX-indent-item))
      (funcall oldfun from end-marker justify-flag)))

  (advice-add 'LaTeX-fill-region-as-para-do
              :around
              'LaTeX-fill-region-as-para-do-fix)
```

**Steps to reproduce**
1. Open a latex file.
2. Add an enumerate environment with a long line item.
For example:
```latex
\begin{enumerate}
  \item Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas scelerisque nisl in faucibus commodo. Phasellus vestibulum quis leo ac interdum. Donec diam dolor, blandit id pretium nec, pellentesque vel felis. Proin vel lacus nec ante ultrices facilisis at sollicitudin est. Etiam non ipsum id arcu bibendum mollis ut et enim. Quisque viverra sem eu eros gravida, vel ullamcorper dui viverra. Cras vel mauris vehicula, luctus mi id, sagittis nulla. Curabitur tincidunt, erat at rhoncus ornare, dolor quam rhoncus nisl, nec sagittis urna sapien at justo. Curabitur accumsan sem quam, vitae rhoncus lorem feugiat eu. 
\end{enumerate}
```
3. Run `fill-paragraph` (`M-q`) or `LaTeX-fill-paragraph` on this item.
4. That item remains a long line.

**System information**
<details>

```
emacs   version    26.3
        features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2
        build      Aug 29, 2019
        buildopts  (--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-modules 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now)
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop 3f7e0fd10 2019-09-29 23:12:43 -0400
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/bash
        uname      Linux 5.3.1-arch1-1-ARCH #1 SMP PREEMPT Sat Sep 21 11:33:49 UTC 2019 x86_64
        path       (~/.opam/ocaml-base-compiler.4.07.1/bin ~/.local/bin ~/.cargo/bin /usr/local/bin /usr/local/sbin /usr/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /usr/lib/emacs/26.3/x86_64-pc-linux-gnu)
config  envfile    nil
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline ophints (popup +all +defaults) vi-tilde-fringe window-select workspaces :editor (evil +everywhere) fold multiple-cursors rotate-text snippets :emacs dired electric vc :tools editorconfig eval flycheck flyspell (lookup +docsets) magit :lang coq data emacs-lisp (latex +latexmk) markdown org (sh +fish) :config (default +bindings +smartparens))
        packages   (n/a)
        elpa       (n/a)
```
</details>

**Comment by hlissner** [comment]
How about this:

```elisp
;; Is there any problem with making these global defaults?
(pushnew! LaTeX-indent-environment-list
          '("itemize" +latex/LaTeX-indent-item)
          '("enumerate" +latex/LaTeX-indent-item))

(defadvice! +latex--dont-indent-itemize-and-enumerate-a (orig-fn &rest args)
  :around #'LaTeX-fill-region-as-paragraph
  (let ((LaTeX-indent-environment-list LaTeX-indent-environment-list))
    (delq! "itemize" LaTeX-indent-environment-list 'assoc)
    (delq! "enumerate" LaTeX-indent-environment-list 'assoc)
    (apply orig-fn args)))
```

**Comment by jonathye** [comment]
Thanks for your quick response. The behavior of this fix is not quite the same as the fix I mentioned though.
Running `fill-paragraph` on the example paragraph results in:
```latex
\begin{enumerate}
  \item Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas
  scelerisque nisl in faucibus commodo. Phasellus vestibulum quis leo ac
  interdum. Donec diam dolor, blandit id pretium nec, pellentesque vel felis.
  Proin vel lacus nec ante ultrices facilisis at sollicitudin est. Etiam non
  ipsum id arcu bibendum mollis ut et enim. Quisque viverra sem eu eros gravida,
  vel ullamcorper dui viverra. Cras vel mauris vehicula, luctus mi id, sagittis
  nulla. Curabitur tincidunt, erat at rhoncus ornare, dolor quam rhoncus nisl,
  nec sagittis urna sapien at justo. Curabitur accumsan sem quam, vitae rhoncus
  lorem feugiat eu.
\end{enumerate}
```
while the fix I pasted actually produces:
```latex
\begin{enumerate}
  \item Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas
    scelerisque nisl in faucibus commodo. Phasellus vestibulum quis leo ac
    interdum. Donec diam dolor, blandit id pretium nec, pellentesque vel felis.
    Proin vel lacus nec ante ultrices facilisis at sollicitudin est. Etiam non
    ipsum id arcu bibendum mollis ut et enim. Quisque viverra sem eu eros
    gravida, vel ullamcorper dui viverra. Cras vel mauris vehicula, luctus mi
    id, sagittis nulla. Curabitur tincidunt, erat at rhoncus ornare, dolor quam
    rhoncus nisl, nec sagittis urna sapien at justo. Curabitur accumsan sem
    quam, vitae rhoncus lorem feugiat eu.
\end{enumerate}
```

But that might just be personal taste, as there is no standard latex coding style to my knowledge. Feel free to close this issue if you think the current indentation style is good enough to be the default.

**Comment by hlissner** [comment]
I'm not sure why that is. The two snippets should be functionally equivalent, mine is simply more concise. I don't have a latex environment to test any of these things out, however. Are you sure you don't have extra configuration that may be interfering?

**Comment by jonathye** [comment]
Hmm... I am pretty sure it is not functional equivalent.
Here is how I reproduce it: I cloned a fresh doom-emacs to .emacs.d and used the default init.el without any configuration. Then I added latex and do `doom re`.
However, testing in this fresh environment still has that undesirable indentation.

**Comment by jonathye** [comment]
In my original post, the solution I pasted has two `advice-add`. I guess you missed one of them?
Adding the following snippet fixes the issue for me (following your style).
```emacs-list
  (defadvice! +latex--re-indent-itemize-and-enumerate-a (orig-fn &rest args)
    :around #'LaTeX-fill-region-as-para-do
    (let ((LaTeX-indent-environment-list LaTeX-indent-environment-list))
      (add-to-list 'LaTeX-indent-environment-list '("itemize" +latex/LaTeX-indent-item))
      (add-to-list 'LaTeX-indent-environment-list '("enumerate" +latex/LaTeX-indent-item))
      (apply orig-fn args)))
```

**Comment by hlissner** [comment]
No, I noticed it. I just made these apply globally:

```lisp 
      (add-to-list 'LaTeX-indent-environment-list '("itemize" +latex/LaTeX-indent-item))
      (add-to-list 'LaTeX-indent-environment-list '("enumerate" +latex/LaTeX-indent-item))
```

Then LaTeX-fill-region-as-para-do would run with the exact same state as it would've in `+latex--re-indent-itemize-and-enumerate-a`.

I do not understand why they behave differently however, and I don't have a latex environment to test this in.

**Comment by jonathye** [comment]
I took a peek at the auctex package. `LaTeX-fill-region-as-para-do` function is actually called by `LaTeX-fill-region-as-paragraph`, which is also the only caller. So `LaTeX-fill-region-as-para-do` would run with the same state as `LaTeX-fill-region-as-paragraph` does, if I understand correctly.

**Comment by jonathye** [comment]
As far as I can tell, `LaTeX-fill-region-as-paragraph` fills and indents a region. But it has a weird behavior that it would not do the filling if an environment is in `LaTeX-indent-environment-list`. It would only indent this environment according to the associated indent function in `LaTeX-indent-environment-list`. But what we want is not just to indent using the associated function in `LaTeX-indent-environment-list`, but also to fill the environment. So in the original solution, we remove "itemize" and "enumerate" from `LaTeX-indent-environment-list` before calling `LaTeX-fill-region-as-paragraph`, so that it does the filling. But it then calls `LaTeX-fill-region-as-para-do` to do the indentation. We have to recover `LaTeX-indent-environment-list` so `LaTeX-fill-region-as-para-do` indents as expected.

**Comment by hlissner** [comment]
Sorry for the late response. I understand now what you meant. This should be fixed as of 237d2d3. Let me know if that isn't the case and I'll reopen this issue. Thanks for bringing it to my attention!

**Comment by jonathye** [comment]
You use the same name for the advice. I believe you should rename one of them. Maybe the first one should be `+latex--re-indent-itemize-and-enumerate-a` or what not?

https://github.com/hlissner/doom-emacs/blob/237d2d3c3a28ba97fec8fde26ffa34013ea2947b/modules/lang/latex/config.el#L96-L110

**Comment by hlissner** [comment]
Ack! My bad. It should be fixed now. Thanks for letting me know!
