### ISSUE TITLE
[BUG] coq installation broken

### ISSUE THREAD

**Issue by qcfu-bu** [hlissner/doom-emacs#1854]
Cannot install coq on latest version of doom.

There was an unexpected error:
  Error in an autoloads file (doom-autoload-error)
  /Users/qianchengfu/.emacs.d/.local/autoloads.el
  (wrong-type-argument stringp nil)

Not sure how to resolve.

**Comment by hlissner** [comment]
c21607a should resolve this issue. Let me know if that isn't the case and I'll reopen this. Thanks for bringing it to my attention!

**Comment by qcfu-bu** [comment]
Thanks!

**Comment by j-hui** [comment]
I'm encountering the same issue, despite already having that commit.. 

I'm still very new to elisp, but seems like the problem is coming from this code:
```
(setq pg-init--script-full-path (locate-library "proof-general")       
      pg-init--pg-root (file-name-directory pg-init--script-full-path))
```

as in, the error disappears when i comment this out, but `proof-general` also does not seem to install any more without it

**Comment by hlissner** [comment]
@j-hui Did you run `doom refresh` on the command line after enabling the `:lang coq` module? I that doesn't fix it, try `doom build`.

**Comment by j-hui** [comment]
ok that was it, i forgot to run `doom refresh`

this is incredible, thanks!
