### ISSUE TITLE
[QUESTION] multi-term is not available in +helm/workspace-buffer-list

### ISSUE THREAD

**Issue by FirstLoveLife** [hlissner/doom-emacs#1855]
I often open a term via `multi-term` in a workspace, but I notice the term buffer is not available `+helm/workspace-buffer-list` and it results that I cannot go back to that term after I switch to other buffer in this workspace conveniently.

**Comment by hlissner** [comment]
It sounds like you aren't using the `:term term` module. Either enable it or add the following to your private config:

```elisp
;; borrowed from the :term term module
(add-hook 'term-mode-hook #'doom-mark-buffer-as-real-h)
```

The issue is that Doom doesn't associate "unreal" buffers with workspaces. The above will get them to be considered real.
