### ISSUE TITLE
[HOWTO] delete/load private snippets

### ISSUE THREAD

**Issue by WeissP** [hlissner/doom-emacs#1857]
my `yas-snippet-dirs` is `(+snippets-dir doom-snippets-dir +file-templates-dir)` 
`+snippets-dir` is `"/home/weiss/.doom.d/snippets/"`  
`doom-snippets-dir` is `"/home/weiss/.emacs.d/.local/straight/build/doom-snippets/snippets"` . 
And the pictures shows the files in the Folder `snippets`.
![image](https://user-images.githubusercontent.com/38898031/66266642-feefae80-e827-11e9-9496-e384b3c8872c.png)

But wenn I in a `.el` file type `SPC s f`, it shows an additional snippet "test", which I have already deleted in filemanager:
![image](https://user-images.githubusercontent.com/38898031/66266668-5e4dbe80-e828-11e9-81b0-5e3d44712416.png)
Also strange is that the snippet `package!` works fine but `weissblockcomment` doesn't work until I open this snippet and type `C-c C-c`, but next time I open Doom Emacs, it doesn't work again.

Both `snippets-reload` and `doom refresh` have I tried but don't work.

**Comment by hlissner** [comment]
Please try removing those blank `uuid` fields and see if it resolves the issue.

**Comment by hlissner** [comment]
> But wenn I in a .el file type SPC s f, it shows an additional snippet "test", which I have already deleted in filemanager:

This is because `SPC s f` is cached. Do `SPC u SPC s f` to refresh the cache.

**Comment by WeissP** [comment]
Thanks! Both problems were solved : )
But in fact the blank `uuid` in snippet "package!", which always works fine, is also not removed, do you know why?

**Comment by hlissner** [comment]
I've never tested it myself, but if 2+ snippets have the same uuid (e.g. a blank one), I think they'll overwrite each other.

In any case, glad to know the issue is resolved.
