### ISSUE TITLE
[BUG] org agenda `t d`: funcall-interactively: Wrong type argument: stringp, nil

### ISSUE THREAD

**Issue by flyingns** [hlissner/doom-emacs#1858]
**Describe the issue**
In org agenda, `t d` feedback `funcall-interactively: Wrong type argument: stringp, nil`

**System information**
<details><pre>
mac mojave
emacs plus 26.3
doom commit `fac6eabd`
</pre></details>

**Comment by flyingns** [comment]
Or `M-x org-agenda-todo`, have the same error.

**Comment by hlissner** [comment]
Please [produce a backtrace](https://gist.github.com/hlissner/780774021756d0fb6bb8b85e1c312526) from these errors.

**Comment by flyingns** [comment]
<pre>
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  org-agenda-todo(nil)
  funcall-interactively(org-agenda-todo nil)
  call-interactively(org-agenda-todo nil nil)
  command-execute(org-agenda-todo)
</pre>

This is the problem with `org`.

**Comment by flyingns** [comment]
Still a commit error, I fall back to commit `3f7e0fd` and no longer complain about this error.

**Comment by hlissner** [comment]
As of de223e7 this issue should be resolved. Let me know if that isn't the case and I will reopen it. Thanks for bringing it to my attention!
