### ISSUE TITLE
[QUESTION] How to say 'yes' for "Are you sure you want to continue connecting (yes/no/[fingerprint])? "

### ISSUE THREAD

**Issue by FirstLoveLife** [hlissner/doom-emacs#1863]
When push to a new git repo in magit, it requires `yes/no/[fingerprint]`:
<pre>
Pushing to git@git.sh.sndu.cn:chenli/testcases-for-OpenMP-MPI-and-other-libraries.git
The authenticity of host 'git.sh.sndu.cn (10.2.10.140)' can't be established.
ECDSA key fingerprint is SHA256:sIvC2SfzSz/zS5/8NzMB8JRxLAEgtxCFgEDclbNTa/Q.
Are you sure you want to continue connecting (yes/no/[fingerprint])? 
</pre>
But I cannot type `yes` or somethingelse in `$`(`magit-process-buffer`)

**Comment by hlissner** [comment]
Can you reproduce this [in vanilla emacs](https://gist.github.com/hlissner/3910fcf5ef14ab77657f269ba9b37f94)?

If so, then this is a magit issue, not a Doom issue.

**Comment by hlissner** [comment]
That seems like an ssh issue, rather than a magit one. I don't think magit is able to suppress confirmation prompts propagated by `ssh`. You can, however, disable host key checks by adding this to `~/.ssh/config`:

```
Host *
   StrictHostKeyChecking no
   UserKnownHostsFile=/dev/null
```

It may be better to limit its scope to, say, 10.2.0.0/16

```
Host 10.2.*.*
   StrictHostKeyChecking no
   UserKnownHostsFile=/dev/null
```
