### ISSUE TITLE
Determining color for package features based on current theme

### ISSUE THREAD

**Issue by orther** [hlissner/doom-emacs#187]
I have set custom colors for several JavaScript packages I have in my private module. Now that I plan to move these features into the core lang/javascript module (see #185) I'm wondering if I can lean on the theme for color decision. My current colors are based on trying different colors until I found something I liked.

I'd like to base these colors on the current theme if this is makes sense. I have not looked at how theming work so please bear with my ignorance. I'm not sure if this is something usually dealt with at the Emacs level or if there are doom specific facilities for this. I plan to look at how existing modules define colors for features (e.g. Magit's diff) as my first step investigating how I should approach this. 

I'd appreciate any guidance even if it's just, "Look at how it's done here." I won't be getting into fixing this color stuff until I get the other pieces ported but I figured I'd ask early.

**Comment by orther** [comment]
I show this more for fun than anything but it is an example of what I experienced after changing my theme with hard coded code coverage overlay background colors. So I'd like to avoid needing to wear a welding mask when testing light/dark themes if possible.

![image](https://user-images.githubusercontent.com/126236/30036668-3d34ed3e-916a-11e7-8620-5099b3ff08d6.png)

**Comment by hlissner** [comment]
It looks like a coverlay.el uses two hardcoded variables: `coverlay:untested-line-background-color` and `coverlay:tested-line-foreground-color`. My [doom-themes](https://github.com/hlissner/emacs-doom-theme) plugin offers the `(doom-color COLOR &optional TYPE)` function for retrieving colors from the theme.

E.g. if you want red and green:

```emacs-lisp
(setq coverlay:untested-line-background-color (doom-color 'red)
      coverlay:tested-line-background-color (doom-color 'green))
```

_However_, those colors will be too harsh, so I recommend a shade that blends into the background a little better (taken from doom-themes' face definitions for magit):

```emacs-lisp
(setq coverlay:untested-line-background-color (doom-blend (doom-color 'red) (doom-color 'bg) 0.1)
      coverlay:tested-line-background-color (doom-blend (doom-color 'green) (doom-color 'bg) 0.1))
```

You can see what symbols `doom-color` accepts at the top of each doom theme, e.g. [doom-one](https://github.com/hlissner/emacs-doom-themes/blob/master/themes/doom-one-theme.el#L36) -- I try to keep them consistent.

-----

Sidenote, I've just pushed a patch for doom-themes to let `doom-blend` resolve color symbols, so this will work once you've updated that plugin:

```emacs-lisp
(setq coverlay:untested-line-background-color (doom-blend 'red 'bg 0.1)
      coverlay:tested-line-background-color (doom-blend 'green 'bg 0.1))
```

-----

If those colors work out for you let me know and I'll add them to doom-themes upstream.

**Comment by orther** [comment]
Thanks this is really great. Will keep you posted.
