### ISSUE TITLE
[REQUEST] Make treemacs window-splitting keybinds consistent with evil's C-w prefix

### ISSUE THREAD

**Issue by Arahnoid** [hlissner/doom-emacs#1875]
The  key bindings for splitting buffers using evil key binding and treemacs are inconsistent.
In evil `SPC w v` means put a Vertical cut in the current buffer.
It treemacs `o v` means open the file as next buffer placed Vertically (under current buffer).
So in result user gets bewildered about the meaning of what Vertical means.

```                             
                             
 From buffer     From treemacs  
                                
 ┌─────────┐    ┌─┬─────────┐   
 │         │    │█│         │   
 │         │    │█│         │   
 │         │    │█│         │   
 └─────────┘    └─┴─────────┘   
      │               │         
      ▼               ▼         
 ┌─────────┐    ┌───────────┐   
 │ SPC w v │    │    o v    │   
 └─────────┘    └───────────┘   
      │               │         
      ▼               ▼         
 ┌─────────┐    ┌─┬─────────┐   
 │    │    │    │█│         │   
 │    │    │    │█│ ─────── │   
 │    │    │    │█│         │   
 └─────────┘    └─┴─────────┘   
```                             

Perhaps would be great to remap treemacs keys to:
- `o v` to behave same as `SPC w v` 

and optionally (makes less sense)
- `o h` to `o s` to behave same as `SPC w s`

**Comment by hlissner** [comment]
I agree, these are confusing. However, these keybinds are treemacs' defaults, not Doom's. This should perhaps [be brought up upstream](https://github.com/Alexander-Miller/treemacs), and perhaps addressed [in treemacs-evil](https://github.com/Alexander-Miller/treemacs/blob/master/src/extra/treemacs-evil.el).

**Comment by hlissner** [comment]
I've added `o v` and `o s` keybinds in 44eb11c to make them consistent for the time being, but please go ahead and report this upstream. I'd like to keep it open until they explicitly refuse or fix the issue there.

**Comment by Arahnoid** [comment]
Thanks a lot :)

**Comment by hlissner** [comment]
I'm not sure this will be adopted upstream, but I'll close this since it has been resolved Doom-side.
