### ISSUE TITLE
[BUG] Failed to load ’magit’ package incrementally, because: (error Key sequence C-c l e H H starts with non-prefix key C-c l e H)

### ISSUE THREAD

**Issue by cxb811201** [hlissner/doom-emacs#1879]
**Describe the issue**

Failed to load ’magit’ package incrementally, because: (error Key sequence C-c l e H H starts with non-prefix key C-c l e H)
Failed to load ’org’ package incrementally, because: (error Key sequence C-c l e H H starts with non-prefix key C-c l e H)
Failed to load ’org-agenda’ package incrementally, because: (error Key sequence C-c l e H H starts with non-prefix key C-c l e H)
Failed to load ’org-capture’ package incrementally, because: (error Key sequence C-c l e H H starts with non-prefix key C-c l e H)
Failed to load ’org’ package incrementally, because: (error Key sequence C-c l e H H starts with non-prefix key C-c l e H)

**Steps to reproduce**

Emacs startup

**System information**
<details><pre>
((emacs
  (version . "27.0.50")
  (features . "XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP")
  (build . "Oct 11, 2019")
  (buildopts "--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --mandir=/usr/share/man --with-gameuser=:games --with-sound=alsa --with-modules --without-gconf --without-gsettings --enable-link-time-optimization --with-x-toolkit=gtk3 --without-xaw3d --without-m17n-flt --with-cairo --without-compress-install 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -flto=jobserver -fuse-linker-plugin -fuse-ld=gold' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD 586243e29 2019-10-10 22:22:21 -0400"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/usr/bin/zsh")
  (uname . "Linux 5.3.5-arch1-1-ARCH #1 SMP PREEMPT Mon Oct 7 19:03:08 UTC 2019 x86_64")
  (path "~/.gem/ruby/2.6.0/bin" "~/.go/bin" "~/.cargo/bin" "~/.jenv/shims" "~/.jenv/bin" "~/.emacs.d/bin" "~/.local/bin" "~/.nvm/versions/node/v12.10.0/bin" "/usr/local/bin" "/usr/local/sbin" "/usr/bin" "/usr/lib/jvm/default/bin" "/usr/bin/site_perl" "/usr/bin/vendor_perl" "/usr/bin/core_perl" "~/.antigen/bundles/robbyrussell/oh-my-zsh/lib" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/git" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/gitfast" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/git-remote-branch" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/colored-man-pages" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/history" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/z" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/extract" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/encode64" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/web-search" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/urltools" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/tmux" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/docker" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/docker-compose" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/archlinux" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/cargo" "~/.antigen/bundles/djui/alias-tips" "~/.antigen/bundles/zdharma/fast-syntax-highlighting" "~/.antigen/bundles/zsh-users/zsh-autosuggestions" "~/.antigen/bundles/hlissner/zsh-autopair" "~/.antigen/bundles/romkatv/powerlevel10k" "/usr/lib/emacs/27.0.50/x86_64-pc-linux-gnu"))
 (config
  (envfile)
  (elc-files . 7)
  (modules :input chinese :completion company (ivy +prescient +fuzzy +childframe) :ui doom doom-quit hl-todo hydra modeline nav-flash neotree ophints (popup +all +defaults) vc-gutter (window-select +numbers) workspaces centered-cursor :editor file-templates lispy multiple-cursors rotate-text snippets :emacs (dired +ranger +icons) electric vc :term eshell :tools docker editorconfig eval (flycheck +childframe) lookup lsp magit (youdao +childframe) :lang data emacs-lisp (go +lsp) (java +lsp) (javascript +lsp) markdown (org +dragndrop +hugo +ipython +pandoc +present +journal) plantuml rest (scala +lsp) sh (web +lsp) :config (default +bindings +smartparens))
  (packages "(fcitx :disable t)" "(pangu-spacing :disable t)" "(tide :disable t)" "(liberime-config :recipe (:host github :repo \"xhcoding/liberime\" :files (\"liberime-config.el\" \"src\" \"CMakeLists.txt\" \"Makefile\")))" "(company-english-helper :recipe (:host github :repo \"manateelazycat/company-english-helper\"))" "(insert-translated-name :recipe (:host github :repo \"manateelazycat/insert-translated-name\"))" cal-china-x exec-path-from-shell hungry-delete go-rename "(go-impl :recipe (:host github :repo \"cxb811201/emacs-go-impl\"))" sqlup-mode dap-mode)
  (elpa "n/a")))
</pre></details>

**Comment by hlissner** [comment]
>   (elc-files . 7)

It also appears you have byte-compiled files. Run `doom clean` to make sure your issue isn't due to stale bytecode.

**Comment by flyingns** [comment]
(elc-file. 0) I have the same problem:

```
Failed to load ’magit’ package incrementally, because: (error Key sequence SPC m e H H starts with non-prefix key SPC m e H)
Error running timer ‘require’: (error "Key sequence SPC m e H H starts with non-prefix key SPC m e H") [6 times]
Failed to load ’org’ package incrementally, because: (error Key sequence SPC m e H H starts with non-prefix key SPC m e H)
Failed to load ’org-agenda’ package incrementally, because: (error Key sequence SPC m e H H starts with non-prefix key SPC m e H)
Failed to load ’org-capture’ package incrementally, because: (error Key sequence SPC m e H H starts with non-prefix key SPC m e H)
Failed to load ’org’ package incrementally, because: (error Key sequence SPC m e H H starts with non-prefix key SPC m e H)
```

**Comment by cxb811201** [comment]
C-c l e H is not bound in my configuration, and I still have this problem running **doom clean** and **doom install**

**Comment by AloisJanicek** [comment]
Newly added (https://github.com/hlissner/doom-emacs/commit/f8fe6f3a80dbb26d064531ac7fa79df1dc1a9e67) html export bindings conflicts with [those already in `+hugo`](https://github.com/hlissner/doom-emacs/blob/develop/modules/lang/org/contrib/hugo.el#L11)

**Comment by hlissner** [comment]
As of 22b0b43 this should be resolved. Let me know if that isn't the case and I'll reopen the issue. Thanks for bringing it to my attention!
