### ISSUE TITLE
[BUG] custom-initialize-reset: Unknown option ‘--restore’

### ISSUE THREAD

**Issue by rgrinberg** [hlissner/doom-emacs#1893]
I'm getting this error on startup:

```
custom-initialize-reset: Unknown option ‘--restore’
```

I'm not sure the reason for this, but I see a `--restore` argument in the doom codebase, and it seems like it's no longer usable.

**Comment by hlissner** [comment]
Does `doom refresh -f` fix it? The `--restore` argument is handled [here](https://github.com/hlissner/doom-emacs/blob/develop/core/autoload/sessions.el#L69-L72), and loaded early in the startup process.

**Comment by rgrinberg** [comment]
> Does doom refresh -f fix it? The --restore argument is handled here 

I tried it but it did not work for me.

**Comment by hlissner** [comment]
As of ea936d9 this should be resolved. Let me know if that isn't the case and I'll reopen the issue. Thanks for bringing it to my attention!
