### ISSUE TITLE
[QUESTION] Would you be willing to separate out env.el as a separate package?

### ISSUE THREAD

**Issue by michaelbogdan** [hlissner/doom-emacs#1895]
I was looking for alternatives to `exec-path-from-shell` as it was a bit slow and I stumbled over `doom`'s own `env.el`. It would be a great alternative as a separate package for people that don't want to load `doom` but build their own configuration.

If not, what is the proper etiquette and procedure should I want to do this myself, at least as a learning experience?

**Comment by hlissner** [comment]
Sorry for the late response: I'd be happy to do so. I'll look into doing so within the next week or two. I'll keep you posted.
