### ISSUE TITLE
[REQUEST] Add binding for which-key-show-top-level under help

### ISSUE THREAD

**Issue by hliebert** [hlissner/doom-emacs#1896]
I find myself calling `M-x` `which-key-show-top-level` to check the top level key bindings for a specific mode more often than any other help function in Emacs/Doom. I think it is one of the most helpful ways to discover functionality in Doom. 

Would you be open to adding a keybind for this? `SPC h t` is already taken by the tutorial, but maybe that could be mapped to something else? Having this available might ease transition for people new to Emacs (and maybe preempt more simple usage questions popping up in chat or on here.)

**Comment by jonathye** [comment]
Have you tried `SPC h b` (`counsel-descbinds)? I consider this as a better alternative to `which-key-show-top-level` since it also allows you to filter the commands/bindings.

**Comment by hliebert** [comment]
I actually didn't know about `counsel-descbinds`, thanks. I think I prefer `which-key-show-top-level` for discovery, as it's easier to see bindings side by side rather than scrolling, and omits the `SPC` prefix bindings. But since both have similar functionality feel free to close this you think it is unnecessary.
