### ISSUE TITLE
Getting an error in `doom|init-ui` this morning (after `make update`)

### ISSUE THREAD

**Issue by Ptival** [hlissner/doom-emacs#191]
Sorry to open yet another issue, but this morning trying on a different computer, I keep getting the following error upon startup:

`Error (doom-post-init-hook): error in ’doom|init-ui’ -> Lisp nesting exceeds ‘max-lisp-eval-depth’`

I tried nuking my entire `.emacs.d` and using the vanilla `init.example.el`, and it's still around. I wonder if it has to do with some recent update in some package. I did `make update` prior to this problem happening.

Anyone else affected, or am I doing something stupid again? :(

**Comment by russmatney** [comment]
I'm seeing the same following an update, digging into what might be a cause or fix for now.

If it helps, my updated packages were:

```
+ ace-link             20170528.1158  -> 20170904.340
+ counsel              20170830.1025  -> 20170904.1246
+ counsel-projectile   20170816.200   -> 20170905.330
+ doom-themes          20170903.748   -> 20170905.402
+ dumb-jump            20170821.13    -> 20170904.1624
+ evil                 20170902.759   -> 20170904.1346
+ gorepl-mode          20170904.126   -> 20170905.245
+ helm                 20170904.308   -> 20170904.922
+ highlight-numbers    20170815.1412  -> 20170905.342
+ hy-mode              20170903.2234  -> 20170904.1538
+ ivy                  20170902.234   -> 20170904.1254
+ tuareg               20170903.2000  -> 20170904.831
```

**Comment by Ptival** [comment]
I wonder if it's related to this commit:

https://github.com/hlissner/emacs-doom-themes/commit/d27d44c617500ed08968089f2f7a7dfc95e1c9d1

**Comment by russmatney** [comment]
If there's a simple way to version-pin the sub modules, i'd love to set these back! Will keep digging in this evening

**Comment by orther** [comment]
It is the commit @Ptival pointed to. It is due to the fact that the new conditional uses `symbolp` which results in `nil` being treated like a color since `nil` is a symbol. This should be super quick fix just a matter of @hlissner getting online is my guess.

## Temp Hack Fix
For a temp hack fix you can edit local package file and change lines 36-37.

Edit file: `~/.emacs.d/.local/packages/elpa/doom-themes-20170905.402/doom-one-theme.el`


```elisp
 ;; replace lines 36-37 with the following
 ((bg         '("#282c34" "black"   "black"        ))
  (bg-alt     '("#21242b" "black"   "black"        ))
```

**Comment by hlissner** [comment]
I just spotted this myself and have pushed a fix. Sorry about that!

**Comment by orther** [comment]
That fixed it! Thx
