### ISSUE TITLE
Cannot enter python-mode

### ISSUE THREAD

**Issue by Ludvins** [hlissner/doom-emacs#1914]
I've just installed doom emacs and it doesn't enter python-mode when openning a .py file. I've python uncommented in the init.el file. Im getting this error.

```File mode specification error: (file-missing Cannot open load file No such file or directory anaconda-mode)```

 If I try to enter it manually it says it cannot open file or directory pyimport. How do I fix this?

**Comment by hlissner** [comment]
Does running `doom refresh -f` fix the issue?

**Comment by Ludvins** [comment]
That fixed it. Thank you.
