### ISSUE TITLE
Theme selection

### ISSUE THREAD

**Issue by guillegalor** [hlissner/doom-emacs#1915]
Is there any form of setting a theme that's not from https://github.com/hlissner/emacs-doom-themes ?
I've installed https://github.com/Greduan/emacs-theme-gruvbox, but it doesn't appear the option to select any of theese thems from the load theme command. 

Thanks in advance!

**Comment by hlissner** [comment]
Hopefully, [this answer](https://github.com/hlissner/doom-emacs/blob/develop/docs/faq.org#how-do-i-change-the-theme) and the one immediately after can answer your question.

**Comment by guillegalor** [comment]
Thank you so much, that works perfectly!
