### ISSUE TITLE
[BUG]  write-file is always asking for file name

### ISSUE THREAD

**Issue by myrgy** [hlissner/doom-emacs#1923]
**Describe the issue**
Before that change https://github.com/hlissner/doom-emacs/commit/5215b79f7a3521656d4f352ed61269a57ac5f815

![image](https://user-images.githubusercontent.com/2340958/67188155-6abf4300-f3f4-11e9-83ed-14cde362541a.png)

`SPS f s` keybinding was a  convenient way to save changes. But now it 's always sking for file name, even if file exists.

Command label is still "Save file", while it behaves as "Save as".
I would propose to revert original behaviour and ass `SPS f S` keybinding that will works as "Save as"

Thanks!

**Comment by hlissner** [comment]
`SPC f s` was changed to differentiate itself from save-buffer on `SPC b s`. Is there any reason you can't use that?

**Comment by flatwhatson** [comment]
Personally I find the `SPC f s` slightly easier to type than `SPC b s`, and used it for that reason alone.

**Comment by hlissner** [comment]
As of #1924, the change has been reversed (thanks to @flatwhatson). Sorry for the noise!
