### ISSUE TITLE
[BUG] Auto package-intialise

### ISSUE THREAD

**Issue by kris-singh** [hlissner/doom-emacs#1927]
**Describe the issue**
Start with a brief 1 or 2 sentence summary of issue.
Install some package ie "elpy", after reloading the package can be seen in the installed packages, but the package is not initalised by default. Hence you can load or enable the mode ie elpy-mode. You have to do a package-initialize after which things work fine. I am using emacs 26.3, some googling around I was able to get through the issue by doing 
(when (version< emacs-version "27.0") (package-initialize))
(require 'package)

in doom.d/init.el file. 

Then follow with a longer explanation, if necessary. Here are some suggestions
on what to include:
- What you expected vs what actually happened
- Screenshots/casts of your issue
- A link to your private config
- Labels for any keys you reference (use `SPC h k` to inspect a key)
- Any warnings or errors logged to \*Messages\* (`SPC h e` or `M-x
  view-echo-area-messages`).

<details><pre>
If available, please a backtrace of the error here.

To acquire a backtrace, enable `debug-on-error` then recreate the error. Here
are ways to enable `debug-on-error`:
- `M-x toggle-debug-on-error`,
- Start Emacs with `emacs --debug-init`
- If the error occurred while using `bin/doom`, use the `-d`/`--debug`
- switches or the `DEBUG` environment variable.
</pre></details>

**Steps to reproduce**
1. Select these example steps,
2. Delete them,
3. And replace them with precise steps to reproduce your issue.
4. Fill in "system information" below.

**System information**
<details><pre>
Place the output of `M-x doom/info` or `~/.emacs.d/bin/doom info` here.
</pre></details>

**Comment by hlissner** [comment]
If you want to use package.el, it is on you to initialize package.el yourself. Doom doesn't use package.el, and intentionally avoids initializing it as such. Instead of installing your packages with it, I'd suggest using Doom's package manager, see: https://github.com/hlissner/doom-emacs/blob/develop/docs/faq.org#how-do-i-install-a-package-from-elpa
