### ISSUE TITLE
[QUESTION] Consider changing lsp-auto-guess-root to nil by default

### ISSUE THREAD

**Issue by jsravn** [hlissner/doom-emacs#1928]
https://github.com/hlissner/doom-emacs/blob/7b45b398608b920cf8babb02257f4057b4367400/modules/tools/lsp/config.el#L11 sets `lsp-auto-guess-root` to `t`. This caused me no end of confusion until I discovered what this setting was doing.

By default lsp-mode disables this feature - and lsp-mode docs say "Do not use this setting unless you are familiar with lsp-mode internals and you are sure that all of your projects are following projectile=/=project.el conventions."

The main problem I experienced is when I have subprojects within a single repository. lsp-mode starts failing without giving a lot of indication about what's wrong. This happens because it automatically selects the repo root as the workspace root, when it needs to select the subproject folder.

If this setting is disabled, the first time you open a file in the subproject for a new lsp type, it asks you where the root is (using projectile for the default). This is a lot more understandable to a new user I think.

**Comment by hlissner** [comment]
That would be frustrating, but I find LSP's pestering more inconvenient. How about if I tweaked LSP to more visibly log the project root when it is activated? e.g.

![image](https://user-images.githubusercontent.com/510883/67241169-e931da00-f420-11e9-9c73-d5b957902cdb.png)

Would this be an acceptable compromise?

Or perhaps only prompt when it can't find a project at all?

**Comment by jsravn** [comment]
The other issue I found is that `lsp-workspace-folder-remove`/`lsp-workspace-folder-add` seem to be ignored when `lsp-auto-guess-root t` is set. This is confusing because the LSP docs describe these commands as how to correctly set the workspace.

Is there a way to set the lsp workspace folder correctly to a project subfolder when `lsp-auto-guess-root` is set? I think if that is possible, and perhaps with the additional logging, then it would reduce the new user confusion. Or is the intention to always create a new projectile project for projects in subfolders?

**Comment by jadestrong** [comment]
This commit  https://github.com/hlissner/doom-emacs/commit/bf8ee34c19fc392656e0bf53bcff752a65ae65c5 will prompt me for the project root every time I open a new file.
When I revert this commit , it can works correctly.


![Kapture 2019-11-09 at 23 18 55](https://user-images.githubusercontent.com/18475217/68530883-7cd33800-0347-11ea-9b96-7bdfe306b9e9.gif)

**Comment by jsravn** [comment]
> That would be frustrating, but I find LSP's pestering more inconvenient. How about if I tweaked LSP to more visibly log the project root when it is activated? e.g.
> 
> ![image](https://user-images.githubusercontent.com/510883/67241169-e931da00-f420-11e9-9c73-d5b957902cdb.png)
> 
> Would this be an acceptable compromise?
> 
> And/or perhaps only prompt when it can't find a project at all (instead of falling back to `default-directory`)?

@hlissner how do you handle a project with multiple LSP roots? I agree the pestering is annoying - but I can't figure out a way to set lsp roots without disabling lsp-auto-guess-root. Any tips?

**Comment by jsravn** [comment]
I guess this won't happen so going to close it.

**Comment by hlissner** [comment]
Oh, my bad. Forgot to link it. This was reverted last year in 8c3f24f14c14.
