### ISSUE TITLE
[BUG] Renaming in `dired` fails because icons and filename get mixed up

### ISSUE THREAD

**Issue by ckruse** [hlissner/doom-emacs#1929]
When trying to rename a file in `dired` (by leaving the read-only mode with `C-x C-q` and changing a filename and then `C-c C-c`) dired prepends the icon to the filename and fails to rename the file because, obviously, it can't find a file with this name (e.g. ` 20191012150607_create_mail_threads.exs`)

<img width="1283" alt="Bildschirmfoto 2019-10-22 um 07 15 08" src="https://user-images.githubusercontent.com/175095/67260452-b24cda00-f49b-11e9-89d8-6cf622e65c50.png">

<details><pre>
Tue Oct 22 07:15:53 2019	Buffer ‘repo’
Rename ‘/Users/ckruse/Code/termitel/termitool/backend/priv/repo/ 20191012150607_create_mail_threads.exs’ to ‘/Users/ckruse/Code/termitel/termitool/backend/priv/repo/ 20191021150607_create_mail_threads.exs’ failed:
(file-missing Renaming No such file or directory /Users/ckruse/Code/termitel/termitool/backend/priv/repo/ 20191012150607_create_mail_threads.exs /Users/ckruse/Code/termitel/termitool/backend/priv/repo/ 20191021150607_create_mail_threads.exs)

1 rename actions failed
</pre></details>

**Steps to reproduce**
1. Open a `dired` buffer
2. leave read-only mode with `C-x C-q`
3. change a filename with an icon pepended
4. press `C-c C-c`

**System information**
<details>

```
emacs   version    27.0.50
        features   RSVG IMAGEMAGICK GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS JSON PDUMPER LCMS2 GMP
        build      Sep 02, 2019
        buildopts  (--disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus/HEAD-dd162a3/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus/HEAD-dd162a3 --with-xml2 --without-dbus --with-gnutls --with-imagemagick --with-json --with-modules --with-rsvg --with-ns --disable-ns-self-contained)
        windowsys  ns
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop cba645be0 2019-10-21 19:01:57 -0400
system  type       darwin
        config     x86_64-apple-darwin18.7.0
        shell      /usr/local/bin/zsh
        uname      Darwin 19.0.0 Darwin Kernel Version 19.0.0: Wed Sep 25 20:18:50 PDT 2019; root:xnu-6153.11.26~2/RELEASE_X86_64 x86_64
        path       (~/Code/emacs/elixir-ls/release ~/.rbenv/shims/ ~/.rbenv/shims/ ~/.rbenv/shims/ /usr/local/bin/ /usr/bin/ /bin/ /usr/sbin/ /sbin/ /Library/Apple/usr/bin/ /Library/Apple/bin/ /usr/local/MacGPG2/bin/ /usr/local/opt/go/libexec/bin/ /usr/local/opt/go/libexec/bin/ /usr/local/opt/go/libexec/bin/ /usr/local/Cellar/emacs-plus/HEAD-dd162a3/libexec/emacs/27.0.50/x86_64-apple-darwin18.7.0/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company (helm +fuzzy) :ui doom doom-dashboard doom-quit hl-todo indent-guides modeline nav-flash ophints (popup +all +defaults) treemacs vc-gutter vi-tilde-fringe window-select :editor file-templates fold (format +onsave) multiple-cursors rotate-text snippets :emacs (dired +icons) vc :tools ansible editorconfig eval flycheck (lookup +docsets) lsp macos magit :lang data erlang (elixir +lsp) emacs-lisp (javascript +lsp) markdown (org +attach +babel +capture +export +habit +present +protocol) (ruby +lsp) sh (web +lsp) :config (default +bindings +smartparens))
        packages   (n/a)
        elpa       (n/a)
```

</details>

**Comment by hlissner** [comment]
This seems like a bug with all-the-icons-dired. Are you able to reproduce it in vanilla Emacs? (Doom's [sandbox](https://gist.github.com/hlissner/3910fcf5ef14ab77657f269ba9b37f94) can help you test it)

**Comment by hlissner** [comment]
I cannot reproduce this on 26.3, in standard Doom or vanilla Emacs. This may actually be an Emacs 27 issue.

**Comment by ckruse** [comment]
Hum. I did not think about this. Will checkout a fresh version of Emacs first to verify the bug still exists.

**Comment by hlissner** [comment]
It appears there is an issue open for it: https://github.com/jtbm37/all-the-icons-dired/issues/18 -- it appears that my suspicions are correct:

```
This seems to be a regression between emacs 27 (HEAD) and emacs 26. It works in emacs 26 but not in emacs 27.
```

**Comment by ckruse** [comment]
No, I did not. My doom configuration is at <https://github.com/ckruse/doom>. Will check if a solution from this thread works, thanks for the pointer (and sorry for the noise!)

**Comment by ckruse** [comment]
Yes, using the advice from <https://github.com/jtbm37/all-the-icons-dired/pull/19> (from your link above) works. It disables all-the-icons for wdired and re-enables it when leaving

**Comment by hlissner** [comment]
It doesn't look like https://github.com/jtbm37/all-the-icons-dired/pull/19 will be merged so I've merged that advice into 0ccf316 (for 27+ users), so I'll consider this resolved. Thanks for bringing it to my attention!

**Comment by ckruse** [comment]
Thanks for fixing!

**Comment by yoavm448** [comment]
I've just ran into this issue. I dug around and it seems that the advice ([here](https://github.com/hlissner/doom-emacs/blob/ac87afe34be86bd2a1e50b728c9c5638ede209b7/modules/emacs/dired/config.el#L122)) is never called, because the function its supposed to run after (`+wdired-before-start-advice`) is not defined... What happened?

**Comment by hlissner** [comment]
@yoavm448 Just pushed a fix for that. Let me know if that fails to address the issue.

**Comment by terlar** [comment]
I believe this has been fixed upstream now, via this refactoring: https://github.com/jtbm37/all-the-icons-dired/commit/8f0858a02fd19f6e63ab8403f6e877da4e01919c#diff-1cb694fb78131dbb71ce622763d9e08c
