### ISSUE TITLE
Weird symbols when coping cyrillic from Emacs terminal

### ISSUE THREAD

**Issue by UtamaruMonster** [hlissner/doom-emacs#193]
Example:
String: Привет мой друг
In clipboard: –ü—Ä–∏–≤–µ—Ç –º–æ–π –¥—Ä—É–≥
Im on MacOS terminal, same in iTerm

**Comment by hlissner** [comment]
For clarification, you're copying _from_ an Emacs terminal (I assume `term`, not `eshell` or `ansi-term`) to either Terminal.app or iTerm.app? Or vice versa?

Have you tried enabling `:ui unicode`?

**Comment by UtamaruMonster** [comment]
I copy from emacs, launched with emacs -nw(from Terminal.app the default one that comes with MacOS) to some application, lets say chrome or slack and get weird symbols.

I have ```:ui unicode``` in init.el

**Comment by UtamaruMonster** [comment]
Same problem with Czech language. I guess it will be same with every language that has diacritics.

**Comment by hlissner** [comment]
I've struggled to reproduce this. I've tried copying text from term, ansi-term and eshell buffers on MacOS to iterm/terminal without problem. 

+ How you are copying things from your Emacs terminal? As in, what commands, and from what kind of terminal buffer. Are you using `evil-yank` or `kill`? Perhaps you're piping the text to `pbcopy`?
+ Are you using terminal or GUI emacs?

**Comment by UtamaruMonster** [comment]
Don't use ```evil-mode```.
I use ```M-w``` or ```C-w``` or  ```kill ``` or ```pbcopy```  same result.
Only Terminal no GUI. Using default terminal app supplied with MacOS.

**Comment by UtamaruMonster** [comment]
Looked around it says to do ```C-x RET x``` then ```selection-coding-system``` to ```compound-text-with-extensions``` but it does not help T_T
