### ISSUE TITLE
[REQUEST] Searching load path & loaded files

### ISSUE THREAD

**Issue by rgrinberg** [hlissner/doom-emacs#1935]
When debugging Emacs, it's quite useful to be able to search through two sets of `.el` files:

1) .el files that have already been loaded
2) .el files that exist in the load path.

For point 1), elisp-refs exists however it has some serious issues with speed. Also, regular expression search is sometimes more desirable.

Here's a prototype for solving 2)

```emacs
(defun region-or-symbol-at-point ()
  (if mark-active
      (buffer-substring-no-properties (region-beginning) (region-end))
    (or (symbol-name (symbol-at-point)) "")))

(defun +grep-load-path (query)
  (interactive
   (let ((query (read-string
                 (format "Grep (default %s): " (region-or-symbol-at-point))
                 nil 'git-grep (region-or-symbol-at-point))))
     (list query)))
  (grep-find
   (mapconcat
    #'shell-quote-argument
    `("rg" "--search-zip" "--no-heading" "--color=never"
      ,query ,@(cl-remove-if-not #'file-directory-p load-path))
    " ")))
```
To solve 1), we just need to replace `load-path` with `(elisp-refs--loaded-paths)`. This is a function from `elisp-refs` that calculates the loaded set of files. It's definition is quite simple so we can just copy paste it, but it's a good package to use anyways.

I could turn this into a PR myself, but I'm sure you'll want to refactor my code a bit anyway. In particular, the way you handle the region or symbol-at-point is slightly different. It would be nice if there was a uniform to handle this and doom let us easily define such interactive functions.

**Comment by hlissner** [comment]
This was added in 0df480bf8, so I'll consider this resolved. Thanks for bringing it to my attention!
