### ISSUE TITLE
[REQUEST] Make dired reuse buffers by default

### ISSUE THREAD

**Issue by rgrinberg** [hlissner/doom-emacs#1937]
By default using `RET` to navigate directories in dired leaves a lot of buffer pollution. Every `RET` command creates a new dired buffer which is rarely desirable. There's even an entire wiki page devoted to disabling this annoying behavior: https://www.emacswiki.org/emacs/DiredReuseDirectoryBuffer

The most convincing approach for how to do this seems to be Xah Lee's:

```
(define-key dired-mode-map (kbd "RET") 'dired-find-alternate-file) ; was dired-find-file

(define-key dired-mode-map (kbd "^") (lambda () (interactive) (find-alternate-file "..")))  ; was dired-up-directory
```

We just remap the offending commands into their non offending versions.

**Comment by hlissner** [comment]
And fixed! Thanks for bringing all these neat ideas to my attention!
