### ISSUE TITLE
[BUG] first workspace after start does not change name from 'main'

### ISSUE THREAD

**Issue by askurihin** [hlissner/doom-emacs#1942]
**Describe the issue**
Start with a brief 1 or 2 sentence summary of issue.

Then follow with a longer explanation, if necessary. Here are some suggestions
on what to include:
- What you expected vs what actually happened
- Screenshots/casts of your issue
- A link to your private config
- Labels for any keys you reference (use `SPC h k` to inspect a key)
- Any warnings or errors logged to \*Messages\* (`SPC h e` or `M-x
  view-echo-area-messages`).

<details><pre>
If available, please a backtrace of the error here.

To acquire a backtrace, enable `debug-on-error` then recreate the error. Here
are ways to enable `debug-on-error`:
- `M-x toggle-debug-on-error`,
- Start Emacs with `emacs --debug-init`
- If the error occurred while using `bin/doom`, use the `-d`/`--debug`
- switches or the `DEBUG` environment variable.
</pre></details>

**Steps to reproduce**
1. Select these example steps,
2. Delete them,
3. And replace them with precise steps to reproduce your issue.
4. Fill in "system information" below.

**System information**
<details><pre>
Place the output of `M-x doom/info` or `~/.emacs.d/bin/doom info` here.
</pre></details>

**Comment by hlissner** [comment]
I'm sorry, but this is not an acceptable bug report. You haven't filled out any of the needed information and the title is vague. How do I reproduce your issue? Could you provide your `M-x doom/info`? Could you explain what you've tried and what you've observed? Can you link to your private config?

These are all things asked for in the issue template. Please fill it out.

> first workspace after start does not change name from 'main'

Why are you expecting its name to change? Are you trying to rename it? What do you do to rename it that failed? Is there something you're doing at startup that would cause it to be renamed? How does it fail? With an error message? Is anything logged to \*Messages\* (see `SPC h e`)?

**Comment by hlissner** [comment]
> I'm sorry for the bad bug report.
> Something went wrong with github, I should have checked.

Thanks perfectly alright. The bug report that followed was excellent! As of 4ccb69d this issue should be resolved. Let me know if that isn't the case and I will reopen the issue. Thanks for bringing it to my attention!
