### ISSUE TITLE
[BUG] Lsp mode cannot be enabled on a javascript file without .js extension

### ISSUE THREAD

**Issue by mihai-dinu** [hlissner/doom-emacs#1943]
**Describe the issue**
Editing a javascript file that has no .js extension will not enable lsp-mode for that buffer. The file (script) has a `#!/usr/bin/env node` header that should let the editor know what type of file it is what it does enable `Javascript IDE` mode which apparently is an extension of the `js2-mode`, but the language server (typescript-language-server) is not started. I get the following error: 

`LSP :: No LSP server for js2-mode(check *lsp-log*).`

**Steps to reproduce**
To reproduce this, unzip the attached file [lsp-problem.zip](https://github.com/hlissner/doom-emacs/files/3761891/lsp-problem.zip) and open the `bla/script` file in emacs. Next set the cursor on the logSmth() function call and try to go to definition. You will get this stacktrace from `tsserver` in the messages buffer:
```
Error: No Project.
    at Object.ThrowNoProject (/home/mihdin/.emacs.d/.local/straight/repos/tide/tsserver/tsserver.js:127999:23)
    at ProjectService.doEnsureDefaultProjectForFile (/home/mihdin/.emacs.d/.local/straight/repos/tide/tsserver/tsserver.js:130936:131)
    at ProjectService.ensureDefaultProjectForFile (/home/mihdin/.emacs.d/.local/straight/repos/tide/tsserver/tsserver.js:130931:75)
    at IOSession.Session.getFileAndProjectWorker (/home/mihdin/.emacs.d/.local/straight/repos/tide/tsserver/tsserver.js:134484:87)
    at IOSession.Session.getFileAndProject (/home/mihdin/.emacs.d/.local/straight/repos/tide/tsserver/tsserver.js:134467:29)
    at IOSession.Session.getDiagnosticsWorker (/home/mihdin/.emacs.d/.local/straight/repos/tide/tsserver/tsserver.js:134159:31)
    at IOSession.Session.getSyntacticDiagnosticsSync (/home/mihdin/.emacs.d/.local/straight/repos/tide/tsserver/tsserver.js:134285:29)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/home/mihdin/.emacs.d/.local/straight/repos/tide/tsserver/tsserver.js:133672:61)
    at /home/mihdin/.emacs.d/.local/straight/repos/tide/tsserver/tsserver.js:135162:88
    at IOSession.Session.executeWithRequestId (/home/mihdin/.emacs.d/.local/straight/repos/tide/tsserver/tsserver.js:135153:28)
    at IOSession.Session.executeCommand (/home/mihdin/.emacs.d/.local/straight/repos/tide/tsserver/tsserver.js:135162:33)
    at IOSession.Session.onMessage (/home/mihdin/.emacs.d/.local/straight/repos/tide/tsserver/tsserver.js:135185:35)
    at Interface.<anonymous> (/home/mihdin/.emacs.d/.local/straight/repos/tide/tsserver/tsserver.js:136500:27)
    at Interface.emit (events.js:198:13)
    at Interface._onLine (readline.js:308:10)
    at Interface._normalWrite (readline.js:451:12)
    at Socket.ondata (readline.js:165:10)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

On the flip side, if you rename the `bla/script` file to `bla/script.js` and re-open it in emacs, then the language server is properly started and everything works as expected.

**System information**
<details><pre>
```
emacs   version    27.0.50
        features   XPM JPEG TIFF GIF PNG RSVG SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD PDUMPER LCMS2 GMP
        build      okt 20, 2019
        buildopts  (--build=x86_64-linux-gnu --prefix=/usr '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' --sysconfdir=/etc --localstatedir=/var --disable-silent-rules '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' --disable-maintainer-mode --disable-dependency-tracking --prefix=/usr --sharedstatedir=/var/lib --program-suffix=-snapshot --with-modules=yes --with-x=yes --with-x-toolkit=gtk3 --with-xwidgets=yes 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/emacs-snapshot-FTRCy_/emacs-snapshot-98972=. -fstack-protector-strong -Wformat -Werror=format-security' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro')
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop, origin/develop, origin/HEAD fac6eabd7 2019-10-04 17:29:02 -0400
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /usr/bin/zsh
        uname      Linux 5.0.0-31-generic #33-Ubuntu SMP Mon Sep 30 18:51:59 UTC 2019 x86_64
        path       (~/.local/bin /snap/bin /usr/local/bin/ ~/.local/bin /snap/bin /usr/local/bin/ ~/.nvm/versions/node/v10.16.0/bin ~/.local/bin /snap/bin /usr/local/bin/ ~/.local/bin /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /usr/games /usr/local/games /snap/bin ~/.local/share/fzf/bin /usr/lib/x86_64-linux-gnu/emacs/27.0.50/x86_64-linux-gnu/)
config  envfile    envvar-file
        elc-files  2
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) treemacs vc-gutter window-select workspaces :editor (evil +everywhere) file-templates fold (format +onsave) multiple-cursors rotate-text snippets :emacs dired electric vc :tools ansible docker eval flycheck (lookup +docsets) lsp magit pass :lang common-lisp data emacs-lisp (javascript +lsp) markdown (org +dragndrop +ipython +pandoc +present) python sh :config (default +bindings +smartparens))
        packages   (n/a)
        elpa       (n/a)
```
</pre></details>

**Comment by hlissner** [comment]
> it does enable Javascript IDE mode

I cannot reproduce this. `node` in the shebang line [is associated with `js2-mode` by the :lang javascript module](https://github.com/hlissner/doom-emacs/blob/develop/modules/lang/javascript/config.el#L36). When I open the `bin/script` I get `js2-mode`, which is what lsp is bound to (Doom doesn't use `js-mode`).

Check the value of `interpreter-mode-alist` (`SPC h v interpreter-mode-alist`). Is `("node" . js2-mode)` higher in the list than `("node" . js-mode)` (or on the list at all)?

>  which apparently is an extension of the js2-mode

It's the other way around. `js2-mode` is an extension of `js-mode`.

> Error: No Project.

This is standard operating procedure for the two available javascript LSP servers I'm aware of (typescript-language-server and typescript-language-server). If a JS file isn't in a valid project, LSP will not start.

However, it would be puzzling if the exact same file in the same location, but with a `.js` extension, successfully spawns an LSP server. It's possible that LSP caches project roots.

I also notice your example in lsp-problem.zip has no `package.json` file or `.git` directory. These are two of the main markers that the `projectile.el` package uses to determine a project's root. If LSP can't determine the project correctly, you will also get this issue.

> HEAD -> develop, origin/develop, origin/HEAD fac6eabd7 2019-10-04 17:29:02 -0400

It looks like your version of Doom is roughly a month old. Quite a bit has changed, so I suggest you update. In particular, there were improvements to the LSP module. i.e. it will prompt you to select a project if none was found. It will also log the detected project root in \*Messages\*, which makes it easier to determine if it succeeded at doing so or not.

**Comment by mihai-dinu** [comment]
Thank you for your detailed reply. I updated Doom and now the major mode for `bla/script` (without any `.js` extension) is `js2-mode`, but lsp stil doesn't want to behave. 

I ran `git init` as well as `npm init` in the folder that I attached earlier and lsp is still complaining that it can't find a project root. 

> However, it would be puzzling if the exact same file in the same location, but with a .js extension, successfully spawns an LSP server. It's possible that LSP caches project roots.

Having both `bla/script` and `bla/script.js` in the same project and opening the roof of the project, these are the messages logs for opening both files: 

`bla/script`
```
Loading /home/mihdin/.emacs.d/.local/cache/recentf...done
Note: js2-basic-offset, tab-width, evil-shift-width adjusted to 2
Package cl is deprecated
LSP :: No LSP server for js2-mode(check *lsp-log*).
sort: Args out of range: [nil :family :foundry :swidth :height :weight :slant :underline :inverse :foreground ...], 19
```
(can't find any *lsp-log* buffer...)

`bla/script.js`
```
Loading /home/mihdin/.emacs.d/.local/cache/recentf...done
Note: js2-basic-offset, tab-width, evil-shift-width adjusted to 2
Package cl is deprecated
LSP :: Guessed project root is /tmp/testtypescript/
LSP :: Connected to [ts-ls:30229 status:starting].
sort: Args out of range: [nil :family :foundry :swidth :height :weight :slant :underline :inverse :foreground ...], 19
LSP :: ts-ls:30229 initialized successfully
```

This is the part that I don't really get. Here's the project with both files and `.git` and `package.json` files included in the root: [lsp-problem-new.zip](https://github.com/hlissner/doom-emacs/files/3764155/lsp-problem-new.zip)

**Comment by hlissner** [comment]
After some digging, I've learned that the lsp-mode configuration for both javscript lsp clients check for a file extension, and will refuse to carry on if one doesn't exist. [These are the offending lines](https://github.com/emacs-lsp/lsp-mode/blob/master/lsp-clients.el#L145-L147).

I've temporarily included a temporary fix for it in Doom, but please bring this up to the [lsp-mode](https://github.com/emacs-lsp/lsp-mode) guys. I'll leave this issue open until they have addressed it or explicitly refused to.

**Comment by mihai-dinu** [comment]
So I logged a bug to `lsp-mode` and it looks like it's already fixed. All you guys move super fast. I love it :D

**Comment by hlissner** [comment]
Great! Thanks for letting me know!
