### ISSUE TITLE
[REQUEST] ESC keystroke (aka, evil-force-normal-state) drops REPL buffers

### ISSUE THREAD

**Issue by randomizedthinking** [hlissner/doom-emacs#1944]
**Describe the feature**
When using repl for python development, I found that pressing `ESC` in the edit buffer will drop the open repl buffer. It is quite undesirable since I might have many work in the repl, and they just disappeared without my notice. Since we might press `ESC` frequently, an accidental key press might make repl buffers go away.

A little bit research found that the `ESC` triggers the `evil-force-normal-state` call. My understanding is that REPL is considered a popup buffer. For some popups, yes, we would like them to go away when pressing ESC. Yet, for repl buffers, I would like them to stick around.

I wonder whether we can set a flag for repl so they will survive the `evil-force-normal-state` call?

This issue is not only for python repl, and is observed on shell repl too. I suspect it is a general issue for any repl in doom emacs.

- How is it helpful?

This is a useful feature for a repl workflow.

**System information**
<details><pre>
emacs   version    26.1
        features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 THREADS LIBSYSTEMD LCMS2
        build      Feb 03, 2019
        buildopts  (--build x86_64-linux-gnu --prefix=/usr --sharedstatedir=/var/lib --libexecdir=/usr/lib --localstatedir=/var/lib --infodir=/usr/share/info --mandir=/usr/share/man --enable-libsystemd --with-pop=yes --enable-locallisppath=/etc/emacs:/usr/local/share/emacs/26.1/site-lisp:/usr/local/share/emacs/site-lisp:/usr/share/emacs/26.1/site-lisp:/usr/share/emacs/site-lisp --with-sound=alsa --without-gconf --with-mailutils --build x86_64-linux-gnu --prefix=/usr --sharedstatedir=/var/lib --libexecdir=/usr/lib --localstatedir=/var/lib --infodir=/usr/share/info --mandir=/usr/share/man --enable-libsystemd --with-pop=yes --enable-locallisppath=/etc/emacs:/usr/local/share/emacs/26.1/site-lisp:/usr/local/share/emacs/site-lisp:/usr/share/emacs/26.1/site-lisp:/usr/share/emacs/site-lisp --with-sound=alsa --without-gconf --with-mailutils --with-x=yes --with-x-toolkit=gtk3 --with-toolkit-scroll-bars 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/emacs-26.1+1=. -fstack-protector-strong -Wformat -Werror=format-security -Wall' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' LDFLAGS=-Wl,-z,relro)
        windowsys  nil
        daemonp    daemon
doom    version    2.0.9
        build      HEAD -> develop, origin/develop, origin/HEAD e6094f262 2019-10-23 18:30:03 -0400
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/zsh
        uname      Linux 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2 (2019-08-28) x86_64
        path       (/usr/local/bin/ /usr/local/sbin/ /usr/bin/ /bin/ /usr/games/ /usr/lib/surfraw/ ~/.fzf/bin/ ~/02-computing/linux/bin/ ~/.local/bin/ ~/.emacs.d/bin/ /usr/lib/emacs/26.1/x86_64-linux-gnu/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company (ivy +fuzzy) :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold (format +onsave) multiple-cursors rotate-text snippets :emacs dired electric vc :term eshell term :tools eval flycheck (lookup +docsets) magit make tmux :lang cc clojure data emacs-lisp ess javascript markdown (org +dragndrop +ipython +pandoc +present) python sh :config (default +bindings +smartparens))
        packages   (n/a)
        elpa       (n/a)
</pre></details>

**Comment by hlissner** [comment]
The answer to this would be to set a popup rule for your particular REPL buffer, but as of 0b67251 I've created a catch-all rule for all REPLs (opened through `SPC o r` and `SPC o R`) which will prevent ESC/C-g from closing the popup, so I'll consider this resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by randomizedthinking** [comment]
It works like a charm... thanks!
