### ISSUE TITLE
Can't add a package.

### ISSUE THREAD

**Issue by kartik-ynwa** [hlissner/doom-emacs#195]
I am trying to install writeroom-mode. I added a line `(package! writeroom-mode)` to `~/.emacs.d/private/modules/$USER/packages.el`. Then did `make install` in `~/.emacs.d`. The new package was installed but it doesn't show up as an option when I do `M-x`.

What am I missing?

**Comment by babygau** [comment]
Because the package is lazy-installed and not initialised when started emacs. You will have to config it in `$USER/config.el`

```lisp
(def-package! writeroom-mode
  :demand t
  :config
  ;; Your configurations....
  )
```

**Comment by kartik-ynwa** [comment]
That did it! Thank you for educating me.
