### ISSUE TITLE
[ROADMAP] rst plugins watch

### ISSUE THREAD

**Issue by gagbo** [hlissner/doom-emacs#1952]
# Plugins regarding ReST on melpa

I'm still not sure about what would be needed in a [:lang rst](https://github.com/hlissner/doom-emacs/projects/3#card-21772931) module, so I went ahead to look for the packages currently on melpa to see what they provide on top of emacs' bundled rst-mode.

## Org export

There's [ox-rst](https://github.com/msnoigrs/ox-rst/tree/master). Great README file which shows what to expects regarding the export, so reading that should be enough.

## Sphinx compilation

ReST documentation can be formatted into html or latex using this [Sphinx frontend package](https://github.com/kostafey/sphinx-frontend/tree/master).

Sphinx seems special since it has a python configuration file and all, but converting markup text to another markup text format seems also like something pandoc would handle well.

## Completion

There's only a completion source for auto-complete, [auto-complete-rst](https://github.com/tkf/auto-complete-rst/tree/master). I didn't find anything for company sadly.

That auto-complete plugin takes a list of path to Sphinx extension files, so I assume this provides project-aware completion depending on the extensions in use

**Comment by hlissner** [comment]
What #2020 merged, I'll consider this resolved. Thanks for bringing it to my attention!
