### ISSUE TITLE
straight.el cannot download packages using http proxy.

### ISSUE THREAD

**Issue by nasoundead** [hlissner/doom-emacs#1957]
Only http/https proxy configed in my company's office environment. 
Straint.el using git:// or ssh:// protocal to interact with github?
Is there a way to config to use http:// protocal ? I don't want to config another proxy like ssh.

**System information**
<details><pre>
`~/.emacs.d/bin/doom quickstart info` 
Using a proxy for https...
Bootstrapping straight.el...
no other print here
</pre></details>

**Comment by hlissner** [comment]
Straight uses `https`, not `http`. If you have something like this in `~/.ssh/config`, it would cause it to use the other protocols:

```gitconfig
[url "ssh://git@github.com/"]
    insteadOf = https://github.com/
[url "ssh://git@gitlab.com/"]
    insteadOf = https://gitlab.com/
```

Or have you changed `straight-vc-git-default-protocol` (default value: `'https`)?

**Comment by hlissner** [comment]
Oh, straight itself is installed through https. I'll look into fixing that. For the time being, maybe this can help: https://github.com/hlissner/doom-emacs/issues/1766#issuecomment-529272636

**Comment by nasoundead** [comment]
@hlissner Thanks! For now it works after cloned 'straint.el' manually.
