### ISSUE TITLE
[BUG] doom upgrade fails with evil-org no upstream configured

### ISSUE THREAD

**Issue by zeronone** [hlissner/doom-emacs#1961]
**Describe the issue**
Start with a brief 1 or 2 sentence summary of issue.

`doom upgrade` fails with following error:
```
Wrong type argument: listp, "There were errors:

   - evil-org: ((error Failed to run \"git\"; see buffer *straight-process*) fatal: no upstream configured for branch 'master')"
```

**Comment by gagbo** [comment]
It's a known issue :
- `rm -rf ~/.emacs.d/.local/straight/{repos,build}/{evil-org,evil-org-mode}`
- `~/.emacs.d/bin/doom upgrade` should work again.

Delete the repos and the packages from `.local/straight` everytime you have this error

**Comment by zeronone** [comment]
Oh thanks, that worked. 🙇

**Comment by hlissner** [comment]
For future reference, there is an open issue for this: https://github.com/hlissner/doom-emacs/issues/1721#issuecomment-539221633
