### ISSUE TITLE
[BUG] Setting some of org mode's variables via usepackage! has no effect.

### ISSUE THREAD

**Issue by RBckmnn** [hlissner/doom-emacs#1969]
**Describe the issue**
Start with a brief 1 or 2 sentence summary of issue.

I noticed that setting some org mode variables in one's private config file via usepackage! has no effect. The value of such a variable always seems to be the value assigned to it in
`+org-init-appearance-h`.

<details><pre>
emacs   version    26.2
        features   XPM JPEG TIFF GIF PNG RSVG SOUND GPM DBUS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE XFT ZLIB GTK3 X11 XDBE XIM THREADS XWIDGETS LCMS2
        build      Jul 01, 2019
        buildopts  (--prefix=/usr --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu --mandir=/usr/share/man --infodir=/usr/share/info --datadir=/usr/share --sysconfdir=/etc --localstatedir=/var/lib --disable-silent-rules --docdir=/usr/share/doc/emacs-26.2 --htmldir=/usr/share/doc/emacs-26.2/html --libdir=/usr/lib64 --program-suffix=-emacs-26 --includedir=/usr/include/emacs-26 --infodir=/usr/share/info/emacs-26 --localstatedir=/var --enable-locallisppath=/etc/emacs:/usr/share/emacs/site-lisp --without-compress-install --without-hesiod --without-pop --with-file-notification=inotify --enable-acl --with-dbus --without-modules --without-gameuser --with-gpm --without-kerberos --without-kerberos5 --with-lcms2 --with-xml2 --without-mailutils --without-selinux --with-gnutls --without-libsystemd --with-threads --without-wide-int --with-zlib --with-sound=alsa --with-x --without-ns --without-gconf --without-gsettings --without-toolkit-scroll-bars --with-gif --with-jpeg --with-png --with-rsvg --with-tiff --with-xpm --without-imagemagick --with-xft --without-cairo --without-libotf --without-m17n-flt --with-x-toolkit=gtk3 --with-xwidgets 'CFLAGS=-march=native -O2 -pipe' CPPFLAGS= 'LDFLAGS=-Wl,-O1 -Wl,--as-needed')
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop, origin/develop, origin/HEAD a122dfd6a 2019-10-27 14:03:45 -0400
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/bash
        uname      Linux 4.19.72-gentoo #1 SMP Sun Sep 15 15:57:57 CEST 2019 x86_64
        path       (/usr/lib/llvm/8/bin/ /usr/local/sbin/ /usr/local/bin/ /usr/sbin/ /usr/bin/ /sbin/ /bin/ /opt/bin/ ~/.emacs.d/bin/ /usr/libexec/emacs/26.2/x86_64-pc-linux-gnu/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company helm :ui doom doom-dashboard hl-todo modeline nav-flash ophints (popup +all +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold multiple-cursors rotate-text snippets :emacs (dired +icons) electric ibuffer vc :term term :tools (eval +overlay) flycheck (lookup +docsets) lsp magit :lang data emacs-lisp (javascript +lsp) markdown (org +dragndrop +ipython +pandoc +present) sh web :config literate (default +bindings +smartparens))
        packages   (n/a)
        elpa       (n/a)
</pre></details>

**Steps to reproduce**

1. Put the following in your private config:
```
(use-package! org
  :config
  (setq org-refile-targets 'Foo))
```

2. Restart doom
3. Issue a org refile command
4. Inspect the org-refile-targets variable

Behaviour:
The variable's value is
```
((nil :maxlevel . 3)
 (org-agenda-files :maxlevel . 3))
```
Expected behaviour:
The variable has the value assigned to it in step 1.

Further observations:
1. Changing :config to :init in step 1 yields the same behaviour.
2. I encountered the same behaviour also with the following code in my private config:

```
  (use-package! org-src
    :config
    (setq org-src-preserve-indentation nil))
```

**Comment by hlissner** [comment]
This is due to the perfect storm of unfortunate events.

1. Org's settings are re-run when a theme is loaded
2. Your `use-package!` config for org is *not* deferred. It loads org immediately and sets `org-refile-targets` too late. The same happens with your `org-src` block.
3. The theme is loaded later in the startup process.
4. Your settings get overwritten.

The proper fix for this is to reconfigure org correctly, without eager-loading it, like so:

```elisp
(after! org
  (setq org-refile-targets 'Foo))
```

Otherwise, if you're set on using `use-package!` for some reason, defer it:

```lisp
(use-package! org
  :defer t
  :config
  (setq org-refile-targets 'Foo))
```

These two blocks are equivalent.

**Comment by RBckmnn** [comment]
Thanks a lot your suggestions indeed resolved the issue for me.

Somehow I was under the impression that :config implied :defer t... I'm a little bit wiser now.

As a bonus... doom now starts even faster :-)

**Comment by hlissner** [comment]
Great! Glad I could help.

> Somehow I was under the impression that :config implied :defer t... I'm a little bit wiser now.

If it's helpful: `:hook`, `:commands`, `:after`, and `:bind` are the deferring keywords (and `:defer`, obviously). As well as `:after-call` and `:defer-incrementally` -- but are only available in Doom).
