### ISSUE TITLE
[BUG] Can't clear visual selection after changing to another workspace

### ISSUE THREAD

**Issue by Svadkos** [hlissner/doom-emacs#1973]
![screen](https://user-images.githubusercontent.com/9449246/67672377-b41d0e80-f96f-11e9-8949-f6e33e31b40f.png)

I've tried to use `redraw-display` and it didn't work.
Also the problem doesn't occur when I select only one line with `V`. That way editor doesn't change to the normal mode and it only place the cursor to the next line for some reason.

**Steps to reproduce**
1. select some text with `v`
2. switch to another workspace without clearing selection
3. switch back and clear the selection
4. the selection stays, but editor is back to the normal mode

**System information**
<details><pre>
((emacs
  (version . "27.0.50")
  (features . "XPM JPEG TIFF GIF PNG RSVG CAIRO IMAGEMAGICK SOUND GPM DBUS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP")
  (build . "Sep 11, 2019")
  (buildopts "--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --mandir=/usr/share/man --with-gameuser=:games --with-sound=alsa --with-modules --without-gconf --without-gsettings --enable-link-time-optimization --with-x-toolkit=gtk3 --without-xaw3d --without-m17n-flt --with-imagemagick --with-cairo --without-compress-install 'CFLAGS=-march=native -O2 -pipe -fstack-protector-strong -fno-plt -flto=jobserver -fuse-linker-plugin -flto=jobserver -fuse-linker-plugin -fuse-ld=gold' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop b1e8ee717 2019-10-26 04:15:32 -0400"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/usr/bin/zsh")
  (uname . "Linux 5.3.7-arch1-1-ARCH #1 SMP PREEMPT Fri Oct 18 00:17:03 UTC 2019 x86_64")
  (path "/usr/lib/ccache/bin/" "/usr/local/bin" "/usr/local/sbin" "/usr/bin" "/opt/android-ndk" "/opt/android-sdk/tools" "/opt/android-sdk/tools/bin" "/var/lib/flatpak/exports/bin" "/usr/lib/jvm/default/bin" "/usr/bin/site_perl" "/usr/bin/vendor_perl" "/usr/bin/core_perl" "/usr/lib/emacs/27.0.50/x86_64-pc-linux-gnu"))
 (config
  (envfile)
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard fill-column hl-todo hydra modeline nav-flash ophints (popup +all +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold multiple-cursors rotate-text snippets word-wrap :emacs (dired +ranger) electric vc :term vterm :tools editorconfig eval flycheck flyspell (lookup +docsets) magit make rgb :lang data emacs-lisp javascript ledger markdown (org +dragndrop +ipython +pandoc +present) php python scheme sh web :email (mu4e +gmail) :app (write +wordnut +langtool) :config (default +bindings +smartparens))
  (packages "(hl-line :ignore nil :recipe nil :disable t)" "(evil-terminal-cursor-changer :ignore nil :recipe nil)" "(pkgbuild-mode :ignore nil :recipe nil)" "(vimrc-mode :ignore nil :recipe nil)")
  (elpa "n/a")))

</pre></details>

**Comment by hlissner** [comment]
This appears to be an Emacs 27 issue. Try this:

```elisp
(add-hook 'persp-before-deactivate-functions (lambda (_) (evil-force-normal-state)))
```

**Comment by krathdog** [comment]
I've been seeing this too for some time and I'm on 26.2. I tried the suggested fix but it didn't help. For me it happens with `v` or `V` selections.

**Comment by krathdog** [comment]
Using that, when I try to open new project `SPC p p` I get:

run-hook-with-args: Wrong number of arguments: ((t) nil (evil-normal-state 1)), 1

I can see the new workspace with `SPC TAB TAB` but I can't switch to it with any of the usual ways.

**Comment by hlissner** [comment]
@krathdog Sorry, I changed the snippet in my last response right after I submitted it. Please try the new version.

**Comment by krathdog** [comment]
That one still doesn't fix the issue. I can also test any suggested fix via discord if you prefer (@kdog).

**Comment by hlissner** [comment]
As of d347574 this should be resolved. Let me know if that isn't the case and I'll reopen this. Thanks for bringing it to my attention!
