### ISSUE TITLE
[BUG] projectile-find-file ignores .projectile in a multi-project git repository

### ISSUE THREAD

**Issue by danielmt** [hlissner/doom-emacs#1974]
In a multi-project git repository, using `SPC SPC` (`projectile-find-file`) is not respecting `.projectile` file anymore, and filters through the whole repository. This behavior started 1 to 2 weeks ago.

**System information**
<details><pre>
((emacs
  (version . "26.2")
  (features . "XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LCMS2")
  (build . "Apr 30, 2019")
  (buildopts "--build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-dbus --with-gif --with-jpeg --with-png --with-rsvg --with-tiff --with-xft --with-xpm --with-x-toolkit=gtk3 --with-gpm=no --with-xwidgets --with-modules build_alias=x86_64-redhat-linux-gnu host_alias=x86_64-redhat-linux-gnu 'CFLAGS=-DMAIL_USE_LOCKF -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection' LDFLAGS=-Wl,-z,relro PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD dca401500 2019-10-27 14:27:29 -0400"))
 (system
  (type . gnu/linux)
  (config . "x86_64-redhat-linux-gnu")
  (shell . "/bin/zsh")
  (uname . "Linux 5.3.7-200.fc30.x86_64 #1 SMP Fri Oct 18 20:13:59 UTC 2019 x86_64")
  (path "~/.pyenv/shims" "~/.pyenv/bin" "~/.nvm/versions/node/v10.16.3/bin" "~/bin/linux" "/usr/local/go/bin" "/home/linuxbrew/.linuxbrew/bin" "/home/linuxbrew/.linuxbrew/sbin" "~/bin" "~/.emacs.d/bin" "~/.local/bin" "~/go/bin" "~/.pyenv/shims" "~/.pyenv/bin"  "~/bin/linux" "/usr/local/go/bin" "/home/linuxbrew/.linuxbrew/bin" "/home/linuxbrew/.linuxbrew/sbin" "~/bin" "~/.emacs.d/bin" "~/.local/bin" "~/go/bin" "/usr/local/bin" "/usr/local/sbin" "/usr/bin" "/usr/sbin" "~/.fzf/bin" "/usr/libexec/emacs/26.2/x86_64-redhat-linux-gnu"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion (company +auto) (helm +fuzzy) :ui deft doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere +commands) fold multiple-cursors rotate-text :emacs (dired +ranger +icons) electric ibuffer vc :tools direnv docker editorconfig (eval +overlay) flycheck (lookup +docsets) magit :lang cc data emacs-lisp go javascript markdown (org +pandoc +present) (python +pyenv) rest rust sh web :private personal gtd jsx web :config (default +bindings +smartparens))
  (packages "n/a")
  (elpa "n/a")))
</pre></details>

**Comment by hlissner** [comment]
This is intentional. I replaced its recognition for `.projectile` files with `.project` files, for two reasons:

1. Doom will eventually drop the `projectile` package in favor of the built-in `project.el` (just waiting for it to mature -- or for me to have time to change it to suit our needs).
2. I don't believe project markers should be tied to editor. `.project` is more generic.

If you're stuck with `.projectile` files, you can restore recognition for it with:

```elisp
(after! projectile
  (add-to-list 'projectile-project-root-files-bottom-up ".projectile"))
```
