### ISSUE TITLE
[BUG] C-u mapped to doom/backward-kill-to-bol-and-indent under normal mode

### ISSUE THREAD

**Issue by randomizedthinking** [hlissner/doom-emacs#1975]
**Describe the issue**
I revert the `C-u` key back to the emacs definition since I don't use it under evil-mode, and would like to have `C-u` functionalities under org-mode. Yet after the setting, the key is now bound to `doom/backward-kill-to-bol-and-indent`.

I would consider it as a minor bug, since `C-u` is defined as backward-kill-to-bol-and-indent only under insert mode as in vim. Under the default setting, it seems fine because `C-u` is masked by the `evil-scroll-up`.

**Steps to reproduce**
1. Add the following configuration in the beginning of `~/.doom.d/init.el`.

   ```
   (setq evil-want-C-u-scroll nil
         evil-want-C-d-scroll nil)
   ```

2. Open emacs, `SPC h k` then `C-u`.

   Then one can see the keybinding.

**System information**
<details><pre>
Place the output of `M-x doom/info` or `~/.emacs.d/bin/doom info` here.
</pre></details>

**Comment by hlissner** [comment]
As of ba7b8d6 `C-u` should no longer be bound globally like that, which should resolve your issue. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by randomizedthinking** [comment]
It works out greatly. Much appreciated...

**Comment by NightMachinary** [comment]
@hlissner Is there a way to get it back to default only in insert mode? It's currently bound like this for me in insert mode:

```
evil-delete-back-to-indentation is an interactive and compiled
function defined in evil-commands.el.

Signature
(evil-delete-back-to-indentation)

Documentation
Delete back to the first non-whitespace character.

If point is before the first non-whitespace character of a
current line then delete from the point to the beginning of the
current line.  If point is on the beginning of the line, behave
according to evil-backspace-join-lines.

Key Bindings
evil-insert-state-map C-u
evil-surround-read-tag-map C-u
ivy-minibuffer-map C-u
ivy-switch-buffer-map C-u
minibuffer-local-map C-u
```

**Comment by hlissner** [comment]
> Is there a way to get it back to default only in insert mode? 
@NightMachinary I'm not certain which "default" you want? `evil-delete-back-to-indentation` is the default for evil users, in insert mode.

Did you want the univeral argument? Or `doom/backward-kill-to-bol-and-indent`?

**Comment by NightMachinary** [comment]
@hlissner I want “universal-argument.” I did it myself with “map!”. Thanks!

**Comment by hlissner** [comment]
Understood. For future reference, `C-u` is being overridden by evil due to [these two settings in the evil module](https://github.com/hlissner/doom-emacs/blob/develop/modules/editor/evil/config.el#L22-L23):

```elisp
(defvar evil-want-C-u-scroll t)  ; moved the universal arg to <leader> u
(defvar evil-want-C-u-delete t)
```

And can be reversed by adding these lines to `~/.doom.d/config.el`:

```elisp
(setq! evil-want-C-u-scroll nil
       evil-want-C-u-delete nil)
```
