### ISSUE TITLE
[REQUEST]  Add taskrunner integration

### ISSUE THREAD

**Issue by chrunchyjesus** [hlissner/doom-emacs#1978]
There is [Taskrunner](https://github.com/emacs-taskrunner/emacs-taskrunner), which can scrap the current project for runnable tasks (e.g. from gradle, package.json and so on). I think integrating it into doom can improve the workflow for many of us.

Potential usage:
- `<leader> p T t` to open the mini buffer with all available tasks, from which one can be selected to run. [ivy-taskrunner](https://github.com/emacs-taskrunner/ivy-taskrunner) has an example as to how it will look like.
- `<leader> p T r` to refresh the cache.
- `<leader> p T d` to delete the cache.

Avaiable integrations into completion frameworks:
- ivy: https://github.com/emacs-taskrunner/ivy-taskrunner
- helm: https://github.com/emacs-taskrunner/helm-taskrunner
- ido: https://github.com/emacs-taskrunner/ido-taskrunner

Documentation can be found here: https://github.com/emacs-taskrunner/emacs-taskrunner/blob/master/api-doc.org

**Comment by hlissner** [comment]
I do like the sound of that. I had already considered throwing together a build management system of some sort, so this makes life easier. It's also a step toward dropping projectile (our current build "system" is essentially projectile's compile commands). I'll investigate this further once I have some time. Thanks for bringing it to my attention!
