### ISSUE TITLE
[BUG] Failed to update packages when using doom upgrade on Windows

### ISSUE THREAD

**Issue by pulcinello** [hlissner/doom-emacs#1981]
**Describe the issue**
Running `doom upgrade` fails every time with the following error message:
```
Output:
nil
--------------------------------------------------

There was an unexpected error:
  File error (file-error)
Wrong type argument: listp, "Spawning child process: Exec format error"
```

Notice that I'm using doom on windows 10. The installation is quite smooth, but I don't know why
it happens during the upgrading process.

**System information**
<details><pre>
((emacs
  (version . "26.3")
  (features . "XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2")
  (build . "Aug 29, 2019")
  (buildopts "--without-dbus --host=x86_64-w64-mingw32 --without-compress-install 'CFLAGS=-O2 -static -g3'")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop 762c37419 2019-10-29 18:19:02 -0400"))
 (system
  (type . windows-nt)
  (config . "x86_64-w64-mingw32")
  (shell . "C:/Users/black/scoop/apps/emacs/current/libexec/emacs/26.3/x86_64-w64-mingw32/cmdproxy.exe")
  (uname . "n/a")
  (path "c:/WINDOWS/system32" "C:/WINDOWS" "C:/WINDOWS/System32/Wbem" "C:/WINDOWS/System32/WindowsPowerShell/v1.0/" "C:/WINDOWS/System32/OpenSSH/" "C:/ProgramData/chocolatey/bin" "C:/Program Files/dotnet/" "C:/Program Files/PowerShell/7-preview/preview" "C:/Users/black/AppData/Roaming/.emacs.d/bin" "C:/Users/black/scoop/apps/nu/current/Plugins" "C:/Users/black/scoop/apps/yarn/current/Yarn/bin" "C:/Users/black/scoop/apps/yarn/current/global/node_modules/.bin" "C:/Users/black/scoop/apps/nodejs/current/bin" "C:/Users/black/scoop/apps/nodejs/current" "C:/Users/black/.poetry/bin" "C:/Users/black/scoop/shims" "C:/Python37/Scripts/" "C:/Python37/" "C:/Users/black/AppData/Local/Microsoft/WindowsApps" "C:/Users/black/AppData/Local/Programs/Microsoft VS Code/bin" "C:/Users/black/AppData/Local/hyper/app-2.0.0/resources/bin" "C:/Users/black/.dotnet/tools" "C:/tools/neovim/Neovim/bin" "C:/Users/black/AppData/Local/Microsoft/WindowsApps" "C:/Users/black/Softwares/gtags/bin" "C:/Users/black/AppData/Roaming/cabal/bin" "C:/ProgramData/chocolatey/lib/ghc/tools/ghc-8.8.1/bin" "C:/tools/msys64" "C:/Program Files/Chez Scheme 9.5.2/bin/ta6nt" "c:/Users/black/scoop/apps/emacs/current/libexec/emacs/26.3/x86_64-w64-mingw32"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company (ivy +icons +fuzzy) :emacs dired electric vc :ui nav-flash (popup +all +defaults) vc-gutter doom hl-todo indent-guides modeline ophints window-select treemacs workspaces :editor (evil +commands +everywhere) file-templates fold (format +onsave) multiple-cursors rotate-text snippets :tools (flycheck +childframe) (lookup +docsets) (eval +overlay) flyspell magit lsp pdf :lang haskell python (org +attach +ref +babel +capture +latex +present) emacs-lisp scheme markdown :config (default +snippets +bindings +commands) :private my-lang my-completion)
  (packages "n/a")
  (elpa "n/a")))
</pre></details>

**Comment by pulcinello** [comment]
Update: After following the documentation and adding `HOME` system variable, I got doom emacs reinstalled. This time, I got the following error when I try to update packages by using `doom upgrade`:

```
Output:
nil
--------------------------------------------------

There was an unexpected error:
  error (error)
Wrong type argument: listp, "Command failed: find \"c:/Users/black/.emacs.d/.local/straight/repos/drag-stuff.el/\" \"c:/Users/black/.emacs.d/.local/straight/repos/ace-link/\" \"c:/Users/black/.emacs.d/.local/straight/repos/avy/\"...
```

**Comment by pulcinello** [comment]
Seems it's a same issue with #1695

**Comment by xeijin** [comment]
I am getting this issue now too, on Windows

**Comment by hlissner** [comment]
I'm hoping that 873fc5c has resolved this issue. Please update and let me know if that is the case.

**Comment by pulcinello** [comment]
Now I get the following error:
```
> Preparing to upgrade Doom Emacs and its packages...

--------------------------------------------------

There was an unexpected error:
  Symbol's function definition is void (void-function)
  doom-sh
```

**Comment by pulcinello** [comment]
After the latest commit, everything works just fine. Really appreciate your hard working!
