### ISSUE TITLE
[BUG] Failed to load ’with-editor’ package incrementally, because: (error Lisp nesting exceeds ‘max-lisp-eval-depth’)

### ISSUE THREAD

**Issue by cxb811201** [hlissner/doom-emacs#1986]
**Describe the issue**

Package cl is deprecated
Loading /home/chenxianbin/.emacs.d/.local/cache/recentf...done
Failed to load ’with-editor’ package incrementally, because: (error Lisp nesting exceeds ‘max-lisp-eval-depth’)
Failed to load ’git-commit’ package incrementally, because: (error Lisp nesting exceeds ‘max-lisp-eval-depth’)
Failed to load ’magit’ package incrementally, because: (error Lisp nesting exceeds ‘max-lisp-eval-depth’)
Failed to load ’org’ package incrementally, because: (error Lisp nesting exceeds ‘max-lisp-eval-depth’)
Failed to load ’org-agenda’ package incrementally, because: (error Lisp nesting exceeds ‘max-lisp-eval-depth’)
Failed to load ’org-capture’ package incrementally, because: (error Lisp nesting exceeds ‘max-lisp-eval-depth’)
Failed to load ’org’ package incrementally, because: (error Lisp nesting exceeds ‘max-lisp-eval-depth’)

No problem with spacemacs(develop)
No problem with emacs-26.3

**Steps to reproduce**
1. Initial installation,
2. First,

**System information**
<details><pre>
((emacs
  (version . "27.0.50.139255")
  (features . "XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP")
  (build . "Oct 30, 2019")
  (buildopts "--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --mandir=/usr/share/man --with-gameuser=:games --with-sound=alsa --with-modules --without-gconf --without-gsettings --enable-autodepend --enable-link-time-optimization --with-x-toolkit=gtk3 --without-xaw3d --without-m17n-flt --with-cairo --without-compress-install 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -flto' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now")
  (windowsys . batch)
  (daemonp))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD d407b3355 2019-10-30 00:03:39 -0400"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/usr/bin/zsh")
  (uname . "Linux 5.3.7-arch1-2-ARCH #1 SMP PREEMPT @1572002934 x86_64")
  (path "~/.gem/ruby/2.6.0/bin" "~/.go/bin" "~/.cargo/bin" "~/.jenv/shims" "~/.jenv/bin" "~/.emacs.d/bin" "~/.local/bin" "~/.nvm/versions/node/v12.10.0/bin" "/usr/local/bin" "/usr/local/sbin" "/usr/bin" "/usr/lib/jvm/default/bin" "/usr/bin/site_perl" "/usr/bin/vendor_perl" "/usr/bin/core_perl" "~/.antigen/bundles/robbyrussell/oh-my-zsh/lib" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/git" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/gitfast" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/git-remote-branch" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/colored-man-pages" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/history" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/z" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/extract" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/encode64" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/web-search" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/urltools" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/tmux" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/docker" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/docker-compose" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/archlinux" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/cargo" "~/.antigen/bundles/djui/alias-tips" "~/.antigen/bundles/zdharma/fast-syntax-highlighting" "~/.antigen/bundles/zsh-users/zsh-autosuggestions" "~/.antigen/bundles/hlissner/zsh-autopair" "~/.antigen/bundles/romkatv/powerlevel10k" "/usr/lib/emacs/27.0.50/x86_64-pc-linux-gnu"))
 (config
  (envfile)
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold multiple-cursors rotate-text snippets :emacs dired electric ibuffer vc :tools (eval +overlay) flycheck (lookup +docsets) magit :lang data emacs-lisp markdown (org +dragndrop +ipython +pandoc +present) sh :config (default +bindings +smartparens))
  (packages "n/a")
  (elpa "n/a")))
</pre></details>

**Comment by AloisJanicek** [comment]
As I build emacs 27 from AUR once or twice a month I noticed that last package which works for me with doom is from Oct 24 and that package I build on Nov 7 causes `max-lisp-eval-depth` error as reported above.
So somewhere in this range https://github.com/emacs-mirror/emacs/compare/61223a046c37d44f67e6600909439d32f8dd34f9...82323253378c310c71cfea393d228321d1fc51f4 something happened which affects using doom emacs with latest emacs from master.

**Comment by jadestrong** [comment]
https://github.com/hlissner/doom-emacs/issues/1990  Maybe you need update your doom-emacs and reinstall all packages.

**Comment by hlissner** [comment]
I believe this is the same issue as #1990, so I'll mark this as duplicate. If it doesn't turn out to be the case let me know and I'll reopen it.

**Comment by AloisJanicek** [comment]
> reinstall all packages.

That did it, thanks for the tip @jadestrong ! 🚀
