### ISSUE TITLE
[Emacs Lisp Question] How to transformed a malformed plist into a hash table of cons cells?

### ISSUE THREAD

**Issue by babygau** [hlissner/doom-emacs#199]
@hlissner,
As a progress of learning `emacs` by grokking your `.emacs.d`, I found one of your macros very interesting. It's `doom!` macro at `/core-packages.el`. So far, I've learned about `list`, `alist`, `clist` and `hash table` through `gnu manual`. Your macro strike me dumb. Could you pls care to guide me through your macro with example?
I also post a [stackoverflow question](https://stackoverflow.com/q/46135037/1305817), would be appreciated to have you look at that

**Comment by hlissner** [comment]
There is only one line in the `doom!` macro that's important, and it is:

```emacs-lisp
(doom-initialize-modules modules)
```

`modules` is an mplist. `doom-initialize-modules` iterates through it and uses `doom-enable-module MODULE SUBMODULE` to add entries to the `doom-modules` hash-table with key `'(MODULE . SUBMODULE)` and value `t`.

This is a simplified version of its algorithm:

```emacs-lisp
;; initialize the hash table if necessary
(unless doom-modules
  (setq doom-modules (make-hash-table :test #'equal :size (+ 5 (length mplist)))))

(let (key)
  (dolist (val mplist)
    (if (keywordp val)
        (setq key val)
      ;; (puthash KEY VALUE HASH-TABLE)
      (puthash (cons key val) t doom-modules))))
```

Afterwards you can look up modules with `(gethash '(:lang . python) doom-modules)` or iterate through the hash-table entries with `(maphash (lambda (key val) ...) doom-modules)`. Elisp hash tables allow me to use cons cell as keys. For alists, I'd have to resort to `assoc` or `member` for lookups, which are much slower (above a certain input size).

If you have other questions, feel free to ask!

**Comment by babygau** [comment]
It's great answer. You just made my day. Many thanks @hlissner. Sure I will put another question soon. Your codes are beautiful and well thought but esoteric to new learner like me. But I think its a great place to learn elisp ❤️
