### ISSUE TITLE
[BUG] mu4e: last added account is always the default

### ISSUE THREAD

**Issue by agraul** [hlissner/doom-emacs#1992]
**Describe the issue**
`set-email-account!` accepts a boolean parameter to indicate if this account should be the default mu4e-context. This setting does not have the expected effect: When I add two accounts, the *last* one is always the mu4e-context I end up in when launching mu4e via `=mu4e`, even if the first one has `t` as the last parameter.

**Further observations**
I've tried to hunt this down a bit. `set-email-account!` sets `mu4e-context-current` to the correct account/context (the one that has the bool set to true). Launching mu4e either via `=mu4e` or via `M-s mu4e` causes a mu4e-context switch (I see "[mu4e] Switched to `$non-default-but-lastly-added-context`" in `*Messages*`).

**Possible reason**
`=mu4e` calls `mu4e~start`, which calls `(mu4e~context-autoswitch nil mu4e-context-policy)`. 
`mu4e~context-autoswitch` then uses `(mu4e-context-determine nil mu4e-context-policy)` to determine what context to switch to. `mu4e-context-determine` then looks at `mu4e-context-policy`, which is set to  `'pick-first`. It then returns the first policy (i.e. the one that was `push`ed to `mu4e-contexts` last. Note that `mu4e-context-current` is not used in this chain of events.

It is possible that I overlooked something, but my conclusion is that the variable `mu4e-context-current` is not used anywhere. There is a function with the same name and a variable `mu4e~context-current`, but I am not sure how they are related / if they could be used instead.

**Comment by hlissner** [comment]
`mu4e-context-switch` appears to consult `mu4e~context-current`. It seems to me that [this](https://github.com/hlissner/doom-emacs/blob/develop/modules/email/mu4e/autoload/email.el#L40) is simply a typo, no?

```diff
       (push context mu4e-contexts)
       (when default-p
-        (setq-default mu4e-context-current context))
+        (setq-default mu4e~context-current context))
       context)))
```

**Comment by hlissner** [comment]
I can't think of a decent way to reimplement `set-email-account!`'s `default-p` argument, and I can't easily acquire and test mu4e at the moment (nor do I use mu4e anymore). I'm open to suggestions.

**Comment by Emiller88** [comment]
I had this also when I was testing mu4e. I just put the context that I wanted first, last in the list.

@hlissner If that's not a good solution I can dig up my nix module if you'd like to test it further.

**Comment by alexandergraul** [comment]
For me as a mu4e user, I don't think having to put the default last is an issue. I think removing  the `default-p` argument from `set-email-account!` and updating its documentation (and putting a hint in mu4e module docs) is good enough. The inconsistency is the bigger problem than not allowing arbitrary orders in my opinion.
If that is how you want to proceed, I am happy to help and can do cleanup and documentation change @hlissner
