### ISSUE TITLE
[BUG] doom-dracula theme is error-prone

### ISSUE THREAD

**Issue by WhatDothLife** [hlissner/doom-emacs#1995]
I'm experiencing some troubles with the background colors of the doom-dracula theme:

  * After starting Emacs, the *dashboard buffer*, the *minibuffer* and the *modeline* are all in the same color (modeline color). This issue can be solved by calling `doom/reload-theme`.

  * Yet, calling `doom//refresh` reverses the change. Moreover, it switches the colors of buffer and minibuffer in regular buffers like el-files.

**System information**
<details><pre>
<details>

```
emacs   version    26.3
        features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD LCMS2
        build      Sep 16, 2019
        buildopts  (--build=x86_64-linux-gnu --prefix=/usr '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' --sysconfdir=/etc --localstatedir=/var --disable-silent-rules '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' --disable-maintainer-mode --disable-dependency-tracking --prefix=/usr --sharedstatedir=/var/lib --program-suffix=26 --with-modules --with-file-notification=inotify --with-mailutils --with-x=yes --with-x-toolkit=gtk3 --with-xwidgets --with-lcms2 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/emacs26-TP6iDo/emacs26-26.3~1.git96dd019=. -fstack-protector-strong -Wformat -Werror=format-security -no-pie' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro -no-pie')
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop, origin/develop, origin/HEAD dca401500 2019-10-27 14:27:29 -0400
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/bash
        uname      Linux 5.0.0-32-generic #34~18.04.2-Ubuntu SMP Thu Oct 10 10:36:02 UTC 2019 x86_64
        path       (/usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /usr/games /usr/local/games /snap/bin /usr/lib/x86_64-linux-gnu/emacs/26.3/x86_64-linux-gnu)
config  envfile    nil
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold format multiple-cursors rotate-text snippets :emacs dired electric :term term :emacs vc :tools editorconfig eval flycheck flyspell (lookup +docsets) magit make pass pdf :lang cc data emacs-lisp ess lua markdown (org +attach +babel +capture +export +habit +present +protocol) sh :email mu4e :app calendar :config (default +bindings +smartparens))
        packages   (n/a)
        elpa       (n/a)
```
</details>
</pre></details>

**Comment by hlissner** [comment]
I cannot reproduce this.

![image](https://user-images.githubusercontent.com/510883/67983609-6e747600-fbfb-11e9-8e3c-93abcbc54c97.png)

Can you provide screenshots? Are there any errors/messages in \*Messages\* (see `SPC h e`)? Is `doom-themes` up to date? Can you reproduce this without your private config ([doom's sandbox can help you test this quickly](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#testing-in-dooms-sandbox)).

**Comment by WhatDothLife** [comment]
There are two warnings and an error:

`WARNING (:emacs term) module was moved to (:term term)
WARNING (:tools password-store) module was moved to (:tools pass)
Error setting doom-big-font-mode: (user-error ‘doom-font’ must be set to a valid font)`

![doom](https://user-images.githubusercontent.com/33008303/67984690-937ede00-fc27-11e9-95f4-2d60fac4b381.png)
![doom1](https://user-images.githubusercontent.com/33008303/67984841-db9e0080-fc27-11e9-9d84-b1eafd486bbb.png)
![doom2](https://user-images.githubusercontent.com/33008303/67984844-de98f100-fc27-11e9-82ea-9d394c9cb54b.png)

**Comment by WhatDothLife** [comment]
Running the sandbox doesn't work for me. I get the message: `Symbol’s function definition is void: nlinum-mode`

**Comment by hlissner** [comment]
> Error setting doom-big-font-mode: (user-error ‘doom-font’ must be set to a valid font)

This error is suspect. Errors at startup tend to short circuit other functionality in Emacs. I'm guessing you are activating `doom-big-font-mode` in your private config. Try removing that and see if it resolves your issue.

**Comment by WhatDothLife** [comment]
I'm not messing around with `doom-big-font-mode` in my config. Still I find it suspicious that I get this error even though I set `doom-font` to a valid font manually. As demanded, [here](https://github.com/WhatDothLife/doom-config) is my private config.

**Comment by hlissner** [comment]
> I'm not messing around with doom-big-font-mode in my config.

You're right, but you're still seeing that error, which doesn't happen unless `doom-big-font-mode` is activated without a valid `doom-font` set. I don't understand this either.

> `(add-to-list 'load-path "~/.doom.d/")`

I highly recommend against this. It can cause naming collisions between your private files and Emacs packages. Use the `load!` macro that Doom provides to load files relative to your private config:

```diff
-(load "+bindings")
+(load! "+bindings")
-(load "+mu4e")
+(load! "+mu4e")
-(load "+popup")
+(load! "+popup")
```

> `(add-hook 'shell-mode-hook #'doom-mark-buffer-as-real-h)`

This isn't necessary. [Doom already does it for you](https://github.com/hlissner/doom-emacs/blob/develop/modules/term/shell/config.el#L4), so long as the `:term shell` module is enabled.

> `(org-clock-persistence-insinuate)`

Doom also does this for you [here](https://github.com/hlissner/doom-emacs/blob/develop/modules/lang/org/config.el#L803-L810) and [here](https://github.com/hlissner/doom-emacs/blob/develop/modules/lang/org/config.el#L815).

----

Maybe with some luck, the two fixes above will indirectly address the `doom-big-font-mode` issue.

**Comment by hlissner** [comment]
It looks like your config is missing a `+mu4e.el` file. It is possible the problem lies there.
