### ISSUE TITLE
[QUESTION] Is it a good idea to use elpy with python mode in doom emacs?

### ISSUE THREAD

**Issue by randomizedthinking** [hlissner/doom-emacs#1997]
Now I use doom emacs for org-mode and it works out greatly. I would like to extend the usage to python development as well.

After testing the built-in python support in doom, I am not so satisfied: I admit that I didn't know the system well. Meanwhile I am also looking at `elpy`. My question is whether it is a good idea to combine `elpy` with the current python support?

I am glad if everyone can share your experience.

**Comment by hlissner** [comment]
I don't know much about elpy, and it's been years since I last tested it (I wasn't impressed with it at the time). I'd suggest trying `:lang (python +lsp)` and installing the ms-python-lsp server first, however. It's hard to imagine elpy could beat that. If all else fails, doesn't hurt to try!

**Comment by randomizedthinking** [comment]
Thanks for the input.. will check out lsp soon.

**Comment by randomizedthinking** [comment]
I will close it for now since it is rather an open question... will test drive the doom python environment.

**Comment by NightMachinary** [comment]
https://github.com/jorgenschaefer/elpy/issues/1797
