### ISSUE TITLE
[BUG] `:wq` error in org-src-mode

### ISSUE THREAD

**Issue by yunhao94** [hlissner/doom-emacs#2002]
**Describe the issue**
`:wq` error in org-src-mode after https://github.com/hlissner/doom-emacs/commit/fb2858679502f189b36e399cfc615421d238c30c

<details><pre>
Debugger entered--Lisp error: (wrong-number-of-arguments #f(compiled-function (command) (interactive nil) #<bytecode 0x2531f85>) 0)
  evil-org-edit-src-exit()
  funcall-interactively(evil-org-edit-src-exit)
  call-interactively(evil-org-edit-src-exit)
  evil-ex-call-command(nil #("wq" 0 1 (ex-index 1) 1 2 (ex-index 2)) nil)
  eval((evil-ex-call-command nil #("wq" 0 1 (ex-index 1) 1 2 (ex-index 2)) nil))
  evil-ex-execute(#("wq" 0 1 (ex-index 1) 1 2 (ex-index 2)))
  #f(compiled-function (&optional initial-input) (interactive (list (let ((s (concat (cond ... ... ...) evil-ex-initial-input))) (and (> (length s) 0) s)))) #<bytecode 0x1605dad>)(nil)
  apply(#f(compiled-function (&optional initial-input) (interactive (list (let ((s (concat ... evil-ex-initial-input))) (and (> (length s) 0) s)))) #<bytecode 0x1605dad>) nil)
  (let ((completion-in-region-function (function completion--in-region))) (apply orig-fn args))
  +ivy--inhibit-completion-in-region-a(#f(compiled-function (&optional initial-input) (interactive (list (let ((s (concat ... evil-ex-initial-input))) (and (> (length s) 0) s)))) #<bytecode 0x1605dad>) nil)
  apply(+ivy--inhibit-completion-in-region-a #f(compiled-function (&optional initial-input) (interactive (list (let ((s (concat ... evil-ex-initial-input))) (and (> (length s) 0) s)))) #<bytecode 0x1605dad>) nil)
  evil-ex(nil)
  funcall-interactively(evil-ex nil)
  call-interactively(evil-ex nil nil)
  command-execute(evil-ex)
</pre></details>

**Steps to reproduce**
1. press <kbd>C-c '</kbd> to edit a org source code block
2.  `:wq` or `ZZ` to call `org-edit-src-exit`

**Comment by hlissner** [comment]
This was fixed in hlissner/evil-org-mode@3949bc5. Let me know if that isn't the case and I'll reopen the issue. Thanks for bringing it to my attention!
