### ISSUE TITLE
[HOWTO] How to open neotree?

### ISSUE THREAD

**Issue by LukasDrsman** [hlissner/doom-emacs#2007]
How do I open neotree?

**Comment by facelesspanda** [comment]
`<leader> o p`

**Comment by hlissner** [comment]
1. Enable the `:ui neotree` module (FAQ: [how do I enable or disable a doom module](https://github.com/hlissner/doom-emacs/blob/develop/docs/faq.org#how-do-i-enable-or-disable-a-doom-module))
2. Run `doom refresh` to sync Doom with your config
3. Restart Emacs.

For evil users it can be opened with `SPC o p` and `SPC o P` will focus the current file in neotree.

For non-evil users it's on `<F9>` and `<C-F9>` respectively.

Hope that helps!

**Comment by LukasDrsman** [comment]
how do I run `doom refresh`?

**Comment by hlissner** [comment]
@LukasDrsman On the command line. The same place where you ran `doom install` when you set up Doom for the first time.
