### ISSUE TITLE
Is the inital setuo missing Neotree evil keybindings?

### ISSUE THREAD

**Issue by kartik-ynwa** [hlissner/doom-emacs#201]
Neotree didn't work out of the box for me. It did after I added the keybindings suggested in the emacs wiki. But I did remove some lines from hlissner's private module so I am not sure. Thanks.

**Comment by babygau** [comment]
unless you post your config to see your prob, it's hard to know if it's a bug. I don't have prob with `Neotree`

**Comment by hlissner** [comment]
The default keybinding (from [my private module](https://github.com/hlissner/doom-emacs/blob/master/modules/private/hlissner/%2Bbindings.el#L234)) is `SPC o n`. You can also toggle it with `M-x +neotree/toggle` -- which is the only way to access it if you've removed the keybinding (in which case, you'll need to bind your own).

**Comment by kartik-ynwa** [comment]
Opening Neotree works great. I couldn't open folders or files in it with space, return or tab. I should have been clear about it.

**Comment by kartik-ynwa** [comment]
Nevermind I am dumb. Sorry for creating this. The keybindings are specific in modules/private/hlissner/+bindings.el
