### ISSUE TITLE
[BUG] +shell/here Fails to process command argument

### ISSUE THREAD

**Issue by chaorace** [hlissner/doom-emacs#2014]
**Describe the issue**
Executing the +shell/here function with a command argument produces a shell bufffer as if no command were provided.

I am testing using a server/emacs-client environment, but I am able to reproduce when operating normally.

**Steps to reproduce**
1. Summon eval line (SPC ;)
2. Supply any command, for example...
``(+shell/here "echo foo")``
3. This produces a shell prompt with nothing executing, as if the command argument were discarded.

**System information**
<details><pre>
emacs   version    26.3
        features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2
        build      Aug 29, 2019
        buildopts  (--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-modules 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now)
        windowsys  x
        daemonp    daemon
doom    version    2.0.9
        build      HEAD -> develop dca401500 2019-10-27 14:27:29 -0400
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/bash
        uname      Linux 4.14.149-1-MANJARO #1 SMP PREEMPT Fri Oct 11 19:42:00 UTC 2019 x86_64
        path       (~/.local/bin/ ~/.local/bin/ /usr/local/bin/ /usr/bin/ /bin/ /usr/local/sbin/ /usr/lib/jvm/default/bin/ /usr/bin/site_perl/ /usr/bin/vendor_perl/ /usr/bin/core_perl/ /usr/lib/jvm/default/bin/ /usr/bin/site_perl/ /usr/bin/vendor_perl/ /usr/bin/core_perl/ ~/.emacs.d/bin/ ~/.emacs.d/bin/ /usr/lib/emacs/26.3/x86_64-pc-linux-gnu/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company ivy :ui deft doom doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) pretty-code treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold multiple-cursors rotate-text snippets word-wrap :emacs dired electric vc :term shell :tools editorconfig eval flycheck flyspell gist (lookup +docsets) magit :lang data emacs-lisp javascript markdown (org +dragndrop +ipython +pandoc +present) sh web :email notmuch :config (default +bindings +smartparens))
        packages   (n/a)
        elpa       (n/a)
</pre></details>

**Comment by hlissner** [comment]
Sorry for the late response. As of f0abb32 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by chaorace** [comment]
Thanks for the fix, just tested it and it works like a charm.
The work you do on this config is fantastic, I'm a big fan! :smiley:
