### ISSUE TITLE
After latest update of packages counsel-ag stopped working

### ISSUE THREAD

**Issue by UtamaruMonster** [hlissner/doom-emacs#202]
Error that i get
```Error in post-command-hook (ivy--exhibit): (void-variable counsel--git-grep-dir)```

**Comment by hlissner** [comment]
Have you updated recently? I fixed this very recently in https://github.com/hlissner/doom-emacs/commit/55b9788351591de0ffadf41c634339a44d043e04 on Sep 8.

**Comment by UtamaruMonster** [comment]
Sorry about that. Closed. :)
