### ISSUE TITLE
[BUG]  Racket smart-open-bracket-mode has to be manually enabled

### ISSUE THREAD

**Issue by vikigenius** [hlissner/doom-emacs#2023]
In Racket pressing '[' leads to an error saying: ``wrong command type argument: commandp`` and nothing is inserted in the buffer

I have to manually enable racket-smart-open-bracket-mode for this to work.

**Comment by hlissner** [comment]
Could you [provide a **backtrace](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#how-to-extract-a-backtrace-from-an-error)** for this error?

**Comment by vikigenius** [comment]
```
Debugger entered--Lisp error: (wrong-type-argument commandp racket-smart-open-bracket)
  call-interactively(racket-smart-open-bracket nil nil)
  command-execute(racket-smart-open-bracket)
```

**Comment by hlissner** [comment]
Can this be reproduced [in the sandbox](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#testing-in-dooms-sandbox)? (In vanilla emacs)

I suspect this is an upstream issue. If you can reproduce it in vanilla Emacs, it should be reported to [racket-mode](https://github.com/greghendershott/racket-mode). In fact, this could be the product of [a very recent change](https://github.com/greghendershott/racket-mode/commit/8049267e4c733715f62101bc11d0187d73459ea4).

**Comment by vikigenius** [comment]
I just tested it, I can't seem to reproduce it in vanilla emacs

I use this to launch the sandbox:

```
(require 'racket-mode)
(require 'racket-smart-open)
(add-hook 'racket-mode-hook 'racket-smart-open-bracket-mode)
(find-file "~/Projects/racket/trees/bst.rkt")
```

**Comment by vikigenius** [comment]
Ok it seems like they have made the change to implement racket-smart-open as a minor mode, but the racket config in doom seems to just use the original version as a keymap. What do you think?

**Comment by hlissner** [comment]
Ah I see the problem. Thanks for the PR! I will accept it soon.
