### ISSUE TITLE
[HOWTO] disable (format +onsave) prettier when prettierrc is missing.

### ISSUE THREAD

**Issue by Npahlfer** [hlissner/doom-emacs#2027]
**What I want to achieve**
This is specific to javascript.
I want the automated formatting to be disabled when there is not prettierrc file present in the project.

**System information**
<details><pre>
WARNING (:emacs eshell) module was moved to (:term eshell)
WARNING Couldn’t find the :emacs imenu module
WARNING (:emacs term) module was moved to (:term term)
WARNING (:app email) module was moved to (:email mu4e)
WARNING: The :fetcher property was used for the evil-matchit package.
This property is deprecated. Replace it with :host.
((emacs
  (version . "26.1")
  (features . "NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS")
  (build . "May 31, 2018")
  (buildopts "--with-ns '--enable-locallisppath=/Library/Application Support/Emacs/${version}/site-lisp:/Library/Application Support/Emacs/site-lisp' --with-modules")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD e0cd71e25 2019-10-31 14:35:24 -0400"))
 (system
  (type . darwin)
  (config . "x86_64-apple-darwin14.5.0")
  (shell . "/bin/zsh")
  (uname . "Darwin 18.5.0 Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64")
  (path "/usr/local/opt/pyenv/shims" "~/.pyenv/bin" "/usr/local/bin" "~/.rbenv/shims" "/usr/local/opt/pyenv/shims" "~/.pyenv/bin" "/usr/local/bin" "/usr/bin" "/bin" "/usr/sbin" "/sbin" "~/.fzf/bin" "/Applications/Emacs.app/Contents/MacOS/bin-x86_64-10_10" "/Applications/Emacs.app/Contents/MacOS/libexec-x86_64-10_10" "/Applications/Emacs.app/Contents/MacOS/libexec" "/Applications/Emacs.app/Contents/MacOS/bin"))
 (config
  (envfile)
  (elc-files . 0)
  (modules :completion company helm :ui doom doom-dashboard hl-todo modeline neotree ophints (popup +all +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold (format +onsave) multiple-cursors rotate-text snippets :emacs dired electric :term eshell term :emacs vc :tools debugger editorconfig eval flycheck (lookup +docsets) magit wakatime :lang clojure common-lisp data emacs-lisp javascript lua markdown (org +attach +babel +capture +export +habit +protocol) php python (sh +zsh) web :email (mu4e +gmail +gmail) :config (default +bindings))
  (packages "(evil-matchit :ignore nil :recipe (:fetcher github :repo \"redguardtoo/evil-matchit\"))" "(editorconfig :ignore nil :recipe nil)" "(eslint-fix :ignore nil :recipe nil)" "(ripgrep :ignore nil :recipe nil)" "(projectile-ripgrep :ignore nil :recipe nil)" "(rg :ignore nil :recipe nil)" "(apropospriate-theme :ignore nil :recipe nil)" "(exec-path-from-shell :ignore nil :recipe nil)" "(company-tabnine :ignore nil :recipe nil)")
  (elpa "prettier-js" "exec-path-from-shell")))
</pre></details>

**Comment by hlissner** [comment]
How about:

```elisp
(add-hook! 'js2-mode-hook
  (unless (locate-dominating-file default-directory ".prettierrc")
    (format-all-mode -1)))
```

**Comment by Npahlfer** [comment]
It kind of works. I realized I had a fallback .prettierrc file that was picked up, but I'll tweak it a bit to make it work. Thank you!
