### ISSUE TITLE
[BUG] Formatter functions get the wrong buffer name

### ISSUE THREAD

**Issue by facelesspanda** [hlissner/doom-emacs#2036]
**Describe the issue**
If a formatter set with `set-formatter!` inspects the variable `buffer-file-name`, it gets an incoherent value

The actual case you can currently see this is with the ocamlformat integration:
it formats `.ml` and `.mli` files differently by inspecting `buffer-file-name`.
When you format a `.mli` file that contains module definitions, an error is reported by ocamlformat because it tried to format it as a `.ml` file, if the first file formatted in the current session was an `.ml` file.

If it serves any purpose, my config is available at https://github.com/facelesspanda/.doom.d

**Steps to reproduce**
 1. Enable `:editor format` and `ocaml` (or any formattable language module) in `init.el`
 2. Add an advice to `ocamlformat` (or the formatter defined by the module chosen in step 1) to print the current buffer name:
```lisp
(defadvice! +ocamlformat-fn-a () :before 'ocamlformat
  (message buffer-file-name))
```
 3. Launch doom
 4. Open an ocaml project with several files (or another project type according to the language chosen in step 1)
 5. Modify and format several files with `+format/buffer-or-region`
 6. Open the messages buffer and see all names being wrong

**System information**<details>

```
emacs   version    26.3
        features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2
        build      Aug 29, 2019
        buildopts  (--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-modules 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now)
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop 135e7ffc8 2019-11-08 17:48:16 -0500
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/bash
        uname      Linux 5.3.8-arch1-1 #1 SMP PREEMPT @1572357769 x86_64
        path       (~/dev/react-inkml/_opam/bin ~/bin /usr/local/bin /usr/bin /bin /usr/local/sbin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl)
config  envfile    nil
        elc-files  0
        modules    (:completion (company +childframe) ivy :ui doom doom-dashboard doom-quit fill-column hl-todo indent-guides modeline nav-flash neotree ophints (popup +all +defaults) (pretty-code +iosevka) unicode vc-gutter vi-tilde-fringe (window-select +switch-window) workspaces :editor (evil +everywhere) file-templates fold (format +onsave) multiple-cursors rotate-text snippets :emacs dired electric ibuffer vc :tools eval flycheck (lookup +docsets) magit make rgb :lang data emacs-lisp javascript latex markdown ocaml (org +dragndrop +ipython +pandoc +present) python rust sh :app calendar (write +wordnut +langtool) :config (default +bindings +smartparens))
        packages   (n/a)
        elpa       (n/a)
```
</details>

**Comment by hlissner** [comment]
As of #2388 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
