### ISSUE TITLE
[BUG] org-agenda-goto and org-agenda-clock-goto don't make sense in org mode

### ISSUE THREAD

**Issue by rgrinberg** [hlissner/doom-emacs#2042]
The following bindings:

```
          "a" #'org-agenda-goto
          "A" #'org-agenda-clock-goto
```

don't make sense in org-mode. These are bindings for org-agenda-mode.

**Comment by hlissner** [comment]
Agreed. I removed them in d3d51e3. Thanks for bringing them to my attention.
