### ISSUE TITLE
[BUG] 873fc5c broke doom for me

### ISSUE THREAD

**Issue by alexandergraul** [hlissner/doom-emacs#2046]
**Describe the issue**
Since 873fc5c, I can't start doom anymore. This happens with a fresh Doom installation (fresh `git clone`) and my [config](https://gitlab.com/agraul/dotfiles/tree/8c4ff703ce6ce11cd57da0fa89f3d9ea761e8ee1/emacs-doom/.doom.d).

This morning I updated [(diff)](https://github.com/hlissner/doom-emacs/compare/9cb535043c3a27ff2296ee75765b56e06f7c51e1...c297d091bd72c4c3b90ba5f21dbb05ccf3aabdd0) doom and it fails to load a few things at startup. I can't do anything, not even `C-x C-c` to quit, I have to `kill -9` it every time. I used `git bisect` to find out which commit is responsible and I found out that 873fc5c is the first bad commit.

There are multiple errors that things can't be found during startup. `emacs --debug-init` only shows this error (see "Details"), but there are more (for all kinds of packages, e.g. "~/.emacs.d/modules/editor/evil/autoload/advice")

<details><pre>
Debugger entered--Lisp error: (file-missing "Cannot open load file" "No such file or directory" "~/.emacs.d/.local/straight/build/doom-modeline/doom-modeline")
  doom-modeline-mode()
  run-hooks(after-init-hook delayed-warnings-hook)
  command-line()
  normal-top-level()

These are the contents in that directory:

➜ ls ~/.emacs.d/.local/straight/build/doom-modeline
doom-modeline-autoloads.el  doom-modeline.el@      doom-modeline-env.elc
doom-modeline-core.el@      doom-modeline.elc      doom-modeline-segments.el@
doom-modeline-core.elc      doom-modeline-env.el@  doom-modeline-segments.elc

</pre></details>

When I try to switch buffer (`C-x C-b`) I get a "Cannot open load file: No such file or directory, ~/.emacs.d/.local/straight/build/company/company". I could not access \*Messages\* due to this. 

**System information**
<details><pre>
(emacs
  (version . "26.3")
  (features . "XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD")
  (build . "Nov 11, 2019")
  (buildopts "--disable-build-details --without-pop --with-mailutils --without-hesiod --with-gameuser=:games --with-kerberos --with-kerberos5 --with-file-notification=inotify --with-modules --enable-autodepend --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --datadir=/usr/share --localstatedir=/var --sharedstatedir=/var/lib --libexecdir=/usr/lib --enable-locallisppath=/usr/share/emacs/26.3/site-lisp:/usr/share/emacs/site-lisp --with-x --with-xim --with-sound --with-xpm --with-jpeg --with-tiff --with-gif --with-png --with-rsvg --with-dbus --with-xft --without-gpm --with-x-toolkit=gtk3 --with-toolkit-scroll-bars --x-includes=/usr/include --x-libraries=/usr/lib64 --with-libotf --with-m17n-flt --with-xwidgets --build=x86_64-suse-linux 'CFLAGS=-O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -g -D_GNU_SOURCE -DGDK_DISABLE_DEPRECATION_WARNINGS -DGLIB_DISABLE_DEPRECATION_WARNINGS -pipe -Wno-pointer-sign -Wno-unused-variable -Wno-unused-label -fno-optimize-sibling-calls -fno-PIE -DSYSTEM_PURESIZE_EXTRA=55000 	 -DSITELOAD_PURESIZE_EXTRA=10000 ' LDFLAGS=-Wl,-O2")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD, refs/bisect/bad 873fc5c0d 2019-11-08 16:02:06 -0500"))
 (system
  (type . gnu/linux)
  (config . "x86_64-suse-linux-gnu")
  (shell . "/usr/bin/zsh")
  (uname . "Linux 5.3.8-1-default #1 SMP Wed Oct 30 07:12:05 UTC 2019 (ea4c828) x86_64")
  (path "~/.rbenv/shims" "~/go/bin" "~/bin" "~/.cargo/bin" "~/.yarn/bin" "~/.rbenv/bin" "~/.cabal/bin/" "~/.emacs.d/bin/" "~/.local/bin" "~/bin" "/usr/local/bin" "/usr/bin" "/bin" "~/.fzf/bin" "/usr/lib/emacs/26.3/x86_64-suse-linux"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company (ivy +icons) :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold format multiple-cursors rotate-text snippets word-wrap :emacs (dired +icons) electric vc :term vterm :tools (eval +overlay) flycheck flyspell (lookup +docsets) lsp magit :lang data emacs-lisp (javascript +lsp) latex markdown (org +pandoc) plantuml (ruby +rbenv) sh web :email mu4e :config literate (default +bindings +smartparens))
  (packages "(dockerfile-mode :ignore nil :recipe nil)" "(salt-mode :ignore nil :recipe nil)" "(evil-escape :ignore nil :recipe nil :disable t)")
  (elpa "n/a")))
</pre></details>

**Comment by hlissner** [comment]
Does `doom refresh -f` or `doom build` change anything?

**Comment by alexandergraul** [comment]
No, I tried those out a few times, but they did not fix anything (starting from the bad commit). I also tried a smaller config. With that I did not have the problems. (package.el and config.el are empty, this is init.el:
```lisp
(doom!
  :completion

  company
  ivy

  :ui
  doom
  doom-dashboard
  doom-quit
  hl-todo
  modeline
  nav-flash
  ophints
  (popup
    +all
    +defaults)
  window-select
  workspaces
  :editor
  (evil +everywhere)
  :lang
  emacs-lisp
  :config
  (default +bindings))
```

If I have time I will bisect my proper init.el tomorrow and see if that changes something. I compared it to the init.example.el but could not find anything that would lead me to believe my config is not compatible anymore.

**Comment by alexandergraul** [comment]
I found the problem in my config.el, I called `doom-load-envvars-file` to load an additional env file (for my ssh agent). I wrapped that call in an `(after! +doom-dashboard-mode ..) [block](https://gitlab.com/agraul/dotfiles/blob/master/emacs-doom/.doom.d/config.org#L40), now it works! 

Sorry for wasting your time.

**Comment by alexandergraul** [comment]
@hlissner the root of the issue still exists, it just does not stop doom from starting anymore. Whenever I try to read my env file, I get the same behavior. This is how I load it:
```lisp
(defun my-doom/load-private-envvars ()
    (interactive)
    (doom-load-envvars-file (concat doom-private-dir "env")))
```
and this is the content of said `env` file:
```
# Doom requires a newline before it starts reading KEY=VALUE pairs    
SSH_AUTH_SOCK=/tmp/ssh-vw5KZzu492p5/agent.7671    
SSH_AGENT_PID=7673 
```
The values of those two keys are written to that `env` file automatically when I unlock my ssh key, generally after I open Doom. If you know of a different approach how to expose the ssh-agent to emacs, I could also use that instead.

**Comment by hlissner** [comment]
How about this: where-ever you start `ssh-agent`, you pipe its output to an envvar file on your local system. e.g.

```sh
eval $(ssh-agent)
echo SSH_AUTH_SOCK="$SSH_AUTH_SOCK" > ~/.ssh/env
echo SSH_AGENT_PID="$SSH_AGENT_PID" >> ~/.ssh/env
```

Then you can load that envvar file:

```elisp
(doom-load-envvar-file "~/.ssh/env")
```

**Comment by alexandergraul** [comment]
That is very similar to how I do it:
```sh
DOOM_ENV="$HOME/.doom.d/env"    
function ssh_vars_to_file {    
    echo "# Doom requires a newline before it starts reading KEY=VALUE pairs    
SSH_AUTH_SOCK=${SSH_AUTH_SOCK}    
SSH_AGENT_PID=${SSH_AGENT_PID}" > "$DOOM_ENV";    
}    
```
`ssh_vars_to_file` is run automatically after `ssh-add`. This leads me to my problem, once I call the "my-doom" function above Doom essentially breaks. I get "Cannot open load file:" errors for all kinds of things (ivy, popup, counsel-projectile,debug).

**Comment by hlissner** [comment]
@alexandergraul a6e2520 should fix your issue. `doom-load-envvars-file` was replacing the value of `process-environment` entirely, instead of replacing each individual envvar.
