### ISSUE TITLE
[REQUEST] doom doctor to warn if using outdated module flags

### ISSUE THREAD

**Issue by xeijin** [hlissner/doom-emacs#2048]
**Describe the feature**

warn users who are still using outdated module flags when running `doom doctor`

e.g. most of the flags in the image below no longer valid, but wasn't aware until I checked the module doc for org

![image](https://user-images.githubusercontent.com/291385/68616527-21c35180-04bd-11ea-88ab-e90a2bb875b2.png)

**Comment by hlissner** [comment]
I've moved this and many other issues to #4273. Please keep track of it there.
