### ISSUE TITLE
Error (doom-ui): Failed to set Fonts.

### ISSUE THREAD

**Issue by justinant** [hlissner/doom-emacs#205]
I installed Gnu Emacs25 onto Ubuntu 17.04 AMD/64 using 'apt-get', selecting 'emacs25'.

Followed the Doom Emacs install instructions as per:

https://github.com/hlissner/doom-emacs

Executed Emacs25, and saw the "Fonts" issue. Followed the instructions at: 

https://github.com/hlissner/doom-emacs/wiki/FAQ#troubleshooting

That partially fixed the issue. I then had to edit ~/.emacs.d/init.el to uncomment ;; unicode, redid 'make install', restart Emacs25.

Doom Emacs loads but in the lower message buffer I am getting a warning message:

"Error (doom-ui): Failed to set fonts because Font not available: #<font-spec nil nil Fira\ Mono nil etc"

Closed Doom Emacs, re-opened, in ~/.emacs.d, ran 'make doctor". The Doctor report states that Doom Emacs is installed correctly.

Screenshot of Error Warning and "make doctor" attached.

![screenshot from 2017-09-14 11-07-26](https://user-images.githubusercontent.com/25677949/30405372-86c1ec36-993f-11e7-9a97-3d9d403e89a5.png)

For your information.

**Comment by babygau** [comment]
It's also happened to me (I used `Operator Mono`instead). Actually I don't know the root of the problem, but chances are some how `make install` stick with `hlissner` module, he clearly set `Fira Mono` in his private `imit.el`. If I use my own private module, the problem is gone after recompiling.

**Comment by jcrotts** [comment]
I'm running  into the same issue on Ubuntu 17.04 AMD/64, what did  you do to fix it @babygau ?

**Comment by babygau** [comment]
As I mentioned above, I created my own private module. As I'm learning emacs, so I just copy *hlissner module* and use what I could understand.

```emacs-lisp
;; /private/$USER/init.el
(set! :font "Operator Mono" :size 18)
(set! :big-font "Operator Mono" :size 18)
(set! :variable-font "Operator Mono" :size 18)
(set! :unicode-font "Operator Mono" :size 18)

;; .emacs.d/init.el
(doom! 
  :private $USER)
```
And then, I run

```bash
make compile
make autoloads
```

**Comment by mromyers** [comment]
The root of the problem is that those fonts are set in `modules/ui/doom/config.el`. That should probably be moved to hlissner's private module.

**Comment by hlissner** [comment]
2.0.7 is now in master. `ui/doom` no longer sets a default font; it leaves it to you to set them in your private module. This should resolve your issue. Feel free to reopen this if that isn't the case.

**Comment by NicoloZorzetto** [comment]
I have this problem, only on MacOS (both linux and windows work fine). I resolved commenting this part 


```
 (setq doom-font (font-spec :family "monospace" :size 14)
       doom-variable-pitch-font (font-spec :family "sans"

```

  of the config.el file. Fonts, icons and color are all the same. Something wrong with either the finding of files around (very possible, we're talking about MacOS) or in the install itself (it gave no errors but who knows).
Everything working fine now
