### ISSUE TITLE
helm-easymenu can't download

### ISSUE THREAD

**Issue by paopaol** [hlissner/doom-emacs#2050]
Package error: (error Could not find package helm-easymenu in recipe repositories: (org-elpa melpa gnu-elpa-mirror emacsmirror-mirror))

what should i do?

**Comment by hlissner** [comment]
The explanation is in the error: the `helm-easymenu` package does not exist on MELPA, elpa or emacsmirror.

After looking it up, the package exists in the helm package, which is installed by the helm module. So enable the `:completion helm` module and add `(require 'helm-easymenu)` to `~/.doom.d/config.el`.

See [how to enable or disable modules](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#how-to-enable-or-disable-modules) if you don't know how.
