### ISSUE TITLE
[BUG] Eglot in doom-modeline: symbol's function definition is void: eglot--current-server

### ISSUE THREAD

**Issue by Y61104** [hlissner/doom-emacs#2051]
**Describe the issue**
Using Eglot I got this error message: ```doom-modeline/doom-modeline-segments.el: Symbol's function is void: eglot--current-server```

This is due to a recent removal of the above function in eglot/eglot-tests.el

That function was replaced by ```eglot-current-server```. After modifying the original doom-modeline-segments.el file (lines 110 and 1773) with the name of the new function everything is ok again.

**Comment by gagbo** [comment]
This is an upstream issue, I'll link it to seagle0128/doom-modeline

**Comment by hlissner** [comment]
This was fixed upstream in https://github.com/seagle0128/doom-modeline/commit/0553a3f34890745e6fe8e4fd27a66f5380856f2e. Update your packages with `doom update`.
