### ISSUE TITLE
[REQUEST] add nov.el to apps

### ISSUE THREAD

**Issue by Guillawme** [hlissner/doom-emacs#2053]
**Add nov.el as an app**

nov.el is a major mode that implements an epub reader for Emacs.

https://github.com/wasamasa/nov.el

**Comment by darth10** [comment]
I actually use `nov.el`, but there's not a lot of configuration needed for it apart from setting a path for it's cache. 
I'm sure there's more that can be customized.

Here's my config apart from the `(package! nov)` declaration:
```lisp
(use-package! nov
  :mode ("\\.epub\\'" . nov-mode)
  :config
  (setq nov-save-place-file (concat doom-cache-dir "nov-places")))

```

**Comment by Guillawme** [comment]
Thank you, very helpful. 👍
