### ISSUE TITLE
[HOWTO] Handling custom set variables changed by setq-local

### ISSUE THREAD

**Issue by vikigenius** [hlissner/doom-emacs#2059]
Let's take an example consider the variable ``company-minimum-prefix-length``

It is being set to 2 in here:
https://github.com/hlissner/doom-emacs/blob/6599388f006b1cd7e050a2415511e2462ebda24f/modules/completion/company/config.el#L7

Now when I try to change the variable using the customize interface, and save it for future sessions, when i reload emacs it is still the original value.

Of course it works when i use setq myself in my private config file

Is this intended? What's the point of customize then?

**Comment by vikigenius** [comment]
I chose the wrong example, I think the variable that doesn't work is

``flycheck-check-syntax-automatically``

Which is being set to nil by lsp-ui-flycheck.el using setq-local
and even though I change it using customize which has the value

```
 '(flycheck-check-syntax-automatically (quote (save)))
```

It is still somehow nill when i open a python buffer

**Comment by hlissner** [comment]
This is intended. Doom was designed to be configured from your config files, not through `M-x customize`. Doom doesn't support it and never will.

```lisp
(after! flycheck
  (setq flycheck-check-syntax-automatically 'save))
```

**Comment by vikigenius** [comment]
Cool, I was just trying to learn a bit of elisp and I came across advise saying that i should avoid using setq to edit custom variables because they might have a setter or something, that's why I was trying out stuff like this.

**Comment by hlissner** [comment]
That's true, it does require that you be vigilant of variables with special setters. There aren't many. At least, there aren't many that need to be triggered if you're just configuring the package at startup (setters are usually designed to accommodate variable changes long after startup, not first-time configuration).

That said, if a variable has one that you really want to trigger, use the `setq!` macro:

```elisp
(after! flycheck
  (setq! flycheck-check-syntax-automatically '(save)))
```

That said, `flycheck-check-syntax-automatically` doesn't have a setter, so this case is no different to `setq`.
