### ISSUE TITLE
doom emacs's mode-line conflict with window-numbering-mode?

### ISSUE THREAD

**Issue by sunznx** [hlissner/doom-emacs#206]

**Comment by hlissner** [comment]
I assume you're referring to the lack of window numbers in the mode-line when window-numbering-mode is enabled. This is the unfortunate consequence of my heavily customized mode-line and is, at the moment, not trivial to fix.

The long way around fixing it would be:

```emacs-lisp
;; place this in modules/private/$USER/config.el
(def-modeline-segment! window-number
  (when (bound-and-true-p window-numbering-mode)
    (concat " " (window-numbering-get-number-string) ")")))

(def-modeline! main
  (bar window-number matches " " buffer-info "  %l:%c %p  " selection-info)
  (buffer-encoding major-mode vcs flycheck))
```

Alternatively, I suggest you look at `ace-window` which is already in Doom and serves the same purpose as window-numbering-mode. It is bound to `C-w C-w` and `SPC w C-w` by default.

**Comment by sunznx** [comment]
no fix. My Mode line is black

**Comment by hlissner** [comment]
I just released 2.0.6 today. Please update and let me know if your mode-line is still black with the above snippet.

If it is black, use `M-x view-echo-area-messages` and tell me if there are any error messages.

**Comment by hlissner** [comment]
Is this still an issue? It's been a while, 2.1 is about to go up and I've been unable to reproduce this.

**Comment by seagle0128** [comment]
I got this error. Is it a clue?
```elisp
Error during redisplay: (eval (:eval (window-numbering-get-number-string))) signaled (void-function :eval) [7 times]
```

**Comment by seagle0128** [comment]
I believe it's related to `window-numering` and `doom-modeline`.
BTW, similar issue with `ace-window-display-mode`, since both will update the modeline. Seems some conflicts with doom.

```elisp
(defun doom-modeline (key)
  "Returns a mode-line configuration associated with KEY (a symbol). Throws an
error if it doesn't exist."
  (let ((fn (intern (format "doom-modeline-format--%s" key))))
    (when (functionp fn)
      `(:eval (,fn)))))
```

**Comment by hlissner** [comment]
I looked into the plugin. The way it tries to change the mode-line is naive and is likely causing this error. Try the following (in your config.el files):

```elisp
(advice-add #'window-numbering-install-mode-line :override #'ignore)
(advice-add #'window-numbering-clear-mode-line :override #'ignore)

(def-modeline-segment! window-number
  (when (bound-and-true-p window-numbering-mode)
    (propertize (concat " " (window-numbering-get-number-string) " ")
                'face 'doom-modeline-panel)))

(def-modeline! main
  (window-number bar matches " " buffer-info "  %l:%c %p  " selection-info)
  (buffer-encoding major-mode vcs flycheck))
```

**Comment by seagle0128** [comment]
The snippets work for me. Thanks a lot!
Only one minor issue here. If disabling `window-numering-mode`, the buffer info disappears. Otherwise everything is fine.
