### ISSUE TITLE
[BUG] lsp-ui flycheck checker stops working after save

### ISSUE THREAD

**Issue by vikigenius** [hlissner/doom-emacs#2060]
**Describe the issue**
lsp-ui flycheck checker stops working after save

When lsp-mode is enabled saving the python buffers causes the linting warnings to disappear

**Steps to reproduce**
1. Configure flycheck to check syntax automatically using
 ```
(after! flycheck
  (setq
   flycheck-check-syntax-automatically '(mode-enabled save idle-change)))
```
2. Use lsp-mode with the microsoft python language server
3. Make sure to have linting erros like unused variables in python code, note the underlined warnings
4. Make a random change and save the buffer.
5. Flycheck does not check errors anymore and the existing warnings disappeared even though you did not fix them
6. Describe variable ``flycheck-check-syntax-automatically`` is now nil

**Comment by vikigenius** [comment]
@hlissner  As a workaround how can I permanently disable the lsp-ui checker so that the other checkers like flake8 work fine?

**Comment by hlissner** [comment]
Try

```lisp
(after! lsp-ui
  (setq lsp-prefer-flymake :none))
```

**Comment by vikigenius** [comment]
cool that seems to have worked.

**Comment by ashkan-leo** [comment]
I also have this issue.
However, I have not configured flycheck to check syntax automatically. Whenever I open a python file, I see all the errors reported. When I modify and save, the errors go away.
Also, the workaround doesn't have any effect for me.

**Comment by ashkan-leo** [comment]
I also tried with pyls and am getting the same behavior

**Comment by vakker** [comment]
@ashkan-leo I had a similar problem and it turned out that flycheck was calling pylint on opening the file and then it didn't call pyls at all.
I don't know if you're experiencing the same, but you can see what's being run by running `ps aux | grep 'pyls'` and ps aux | grep 'pylint'` in a terminal.

**Comment by yleteigner** [comment]
I am also facing the same issue, where the flycheck errors disappear as soon as I modify the buffer.
My temp workaround is to run M-x flycheck-verify-setup and select a checker for the buffer.
https://www.flycheck.org/en/latest/user/troubleshooting.html

I need to rerun it every time I re-open a buffer though..

**Comment by dakyskye** [comment]
Facing the same issue, with Golang

**Comment by monadplus** [comment]
Did anyone found a workaround?

**Comment by vikigenius** [comment]
Closing, since this issue is no longer relevant with so many changes to lsp and doom.
