### ISSUE TITLE
Opening a directory [HOWTO] 

### ISSUE THREAD

**Issue by a5l3** [hlissner/doom-emacs#2062]
MacOS Catalina Update
- cannot open ``` SPC f e d``` due to some permission issues with emacs on osx
- this is not a doom issue, although I use doom
- has anyone found a solution for this?

**Comment by hlissner** [comment]
This is a Catalina issue. I don't know much about it, but others have told me that https://gist.github.com/dive/f64c645a9086afce8e5dd2590071dbf9 resolved the issue for them (either the script or the suggestions in the comments).

Hope that helps!

**Comment by a5l3** [comment]
@hlissner it works! thanks
