### ISSUE TITLE
[BUG] Modeline characters broken despite following FAQ

### ISSUE THREAD

**Issue by vakker** [hlissner/doom-emacs#2066]
**Describe the issue**
Modeline characters seems to be broken despite running `all-the-icons-install-fonts`.

![modeline1](https://user-images.githubusercontent.com/3268882/68992794-55f59400-0868-11ea-948d-7c635e3b1fb4.png)

![modeline2](https://user-images.githubusercontent.com/3268882/68992798-5a21b180-0868-11ea-944b-f90e204d8fbe.png)

I followed [this](https://github.com/hlissner/doom-emacs/blob/develop/docs/faq.org#strange-or-incorrect-icons-are-displayed-everywhere) in the FAQ, and other people seem to have the same issue, e.g. [here](https://www.reddit.com/r/emacs/comments/c9ic18/doommodeline_unicode_characters/).

**System information**
<details><pre>
WARNING: The :fetcher property was used for the smartparens package.
This property is deprecated. Replace it with :host.
Package error: (error Could not find package irony-server in recipe repositories: (org-elpa melpa gnu-elpa-mirror emacsmirror-mirror))
((emacs
  (version . "26.3")
  (features . "XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD LCMS2")
  (build . "Sep 16, 2019")
  (buildopts "--build=x86_64-linux-gnu --prefix=/usr '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' --sysconfdir=/etc --localstatedir=/var --disable-silent-rules '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' --disable-maintainer-mode --disable-dependency-tracking --prefix=/usr --sharedstatedir=/var/lib --program-suffix=26 --with-modules --with-file-notification=inotify --with-mailutils --with-x=yes --with-x-toolkit=gtk3 --with-xwidgets --with-lcms2 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/emacs26-TP6iDo/emacs26-26.3~1.git96dd019=. -fstack-protector-strong -Wformat -Werror=format-security -no-pie' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro -no-pie'")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD ab0a90cd2 2019-11-15 02:17:08 -0500"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/usr/bin/zsh")
  (uname . "Linux 4.15.0-70-generic #79-Ubuntu SMP Tue Nov 12 10:36:11 UTC 2019 x86_64")
  (path "~/.emacs.d/bin" "~/.local/bin" "~/bin" "~/.emacs.d/bin" "~/.local/bin" "~/bin" "~/miniconda3/bin" "~/miniconda3/condabin" "~/.emacs.d/bin" "~/.local/bin" "~/bin" "/usr/local/sbin" "/usr/local/bin" "/usr/sbin" "/usr/bin" "/sbin" "/bin" "/usr/games" "/usr/local/games" "/snap/bin" "/usr/local/go/bin" "~/go/bin" "/usr/local/go/bin" "~/go/bin" "~/.fzf/bin" "/usr/local/go/bin" "~/go/bin" "/usr/lib/x86_64-linux-gnu/emacs/26.3/x86_64-linux-gnu"))
 (config
  (envfile)
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold multiple-cursors rotate-text snippets :emacs dired electric vc :tools docker eval flycheck flyspell (lookup +docsets) magit pdf :lang data emacs-lisp (latex +latexmk) markdown (org +dragndrop +ipython +pandoc +present) python sh :config (default +bindings +smartparens))
  (packages "(ag :ignore nil :recipe nil)" "(irony :ignore nil :recipe nil)" "(irony-server :ignore nil :recipe nil)" "(irony-eldoc :ignore nil :recipe nil)" "(flycheck-irony :ignore nil :recipe nil)" "(company-irony :ignore nil :recipe nil)" "(highlight-indent-guides :ignore nil :recipe nil)" "(yapfify :ignore nil :recipe nil)" "(smartparens :ignore nil :recipe (:fetcher github :repo \"Fuco1/smartparens\"))" "(py-isort :ignore nil :recipe nil)" "(org-ref :ignore nil :recipe nil)" "(org-fancy-priorities :ignore nil :recipe nil)" "(org-super-agenda :ignore nil :recipe nil)" "(platformio-mode :ignore nil :recipe nil)")
  (elpa "n/a")))
</pre></details>

**Comment by even4void** [comment]
I got somewhat in a similar situation when I reinstalled Doom Emacs from scratch few weeks ago. Are you sure the Material Icon fonts were installed in the correct place? In my case (macOS), it appears that `all-the-icons-install-fonts` didn't do the job well and I hadn't to manually install the font in `~/Library/Fonts`.

**Comment by vakker** [comment]
Thanks a lot for the tip, I looked into the fonts properly and it seems like on Ubuntu the font cache is not updated properly. It's places the files under `~/.local/share/fonts` (which is fine), but for some reason the system didn't see the Material Icon fonts despite Doom reporting that `fc-cache -f -v` went fine.

The solution was to run `sudo fc-cache -f -v` manually. Maybe without `sudo` it doesn't work properly?

**Comment by hlissner** [comment]
> The solution was to run sudo fc-cache -f -v manually. Maybe without sudo it doesn't work properly?

In that case I'll consider this resolved. If it is a recurring issue, perhaps it should be reported to [all-the-icons.el](https://github.com/domtronn/all-the-icons.el) upstream.

**Comment by dimsuz** [comment]
I found that my modeline didn't render some icons (specifically a flycheck "check" icon) due to a missing `$HOME/.local/share/fonts/material-design-icons.ttf` font. The file was there, but it was 0 length. So all material icons didn't load. The `M-x all-the-icons-insert-material` gave me a hint that I've a problem with material icons only.

This happened on 2 distinct Linux machines while installing doom-emacs from scratch. Perhaps this is some problem with `doom install` script?

Running `M-x all-the-icons-install-fonts` form a running emacs + restart fixed things for me, ttf was downloaded successfully this time.
