### ISSUE TITLE
[BUG] project search doesn't work

### ISSUE THREAD

**Issue by jsravn** [hlissner/doom-emacs#2071]
**Describe the issue**
Can't search project files anymore with ripgrep after updating today.

<details><pre>
Debugger entered--Lisp error: (void-variable all-files-p)
  (if all-files-p (progn "-z -uu"))
  (list "rg --no-heading --line-number --color never" "-S" (if all-files-p (progn "-z -uu")) (if recursive-p nil "--maxdepth 1"))
  (let* ((project-root (or (doom-project-root) default-directory)) (directory (or in project-root)) (default-directory directory) (helm-ag--default-directory directory) (helm-ag--default-target (list directory)) (query (or query (if (use-region-p) (progn (let (... ...) (if ... ...)))) "")) (prompt (format "[rg %s] " (cond ((file-equal-p directory project-root) (projectile-project-name)) ((file-equal-p directory default-directory) "./") ((file-relative-name directory project-root))))) (command (list "rg --no-heading --line-number --color never" "-S" (if all-files-p (progn "-z -uu")) (if recursive-p nil "--maxdepth 1"))) (helm-ag-base-command (string-join command " "))) (helm-attrset (quote name) (format "[rg %s] Searching %s" (string-join (delq nil (cdr command)) " ") (abbreviate-file-name directory)) helm-source-do-ag) (helm-attrset (quote +helm-command) command helm-source-do-ag) (let* ((vnew (function (lambda nil (helm :sources (quote ...) :prompt prompt :buffer "*helm-rg*" :keymap helm-do-ag-map :input query :history (quote helm-ag--helm-history))))) (old (symbol-function (quote helm-do-ag--helm)))) (unwind-protect (progn (fset (quote helm-do-ag--helm) vnew) (helm-do-ag directory)) (fset (quote helm-do-ag--helm) old))))
  (progn (if (executable-find "rg") nil (user-error "Couldn't find ripgrep in your PATH")) (require (quote helm-ag)) (helm-ag--init-state) (let* ((project-root (or (doom-project-root) default-directory)) (directory (or in project-root)) (default-directory directory) (helm-ag--default-directory directory) (helm-ag--default-target (list directory)) (query (or query (if (use-region-p) (progn (let ... ...))) "")) (prompt (format "[rg %s] " (cond ((file-equal-p directory project-root) (projectile-project-name)) ((file-equal-p directory default-directory) "./") ((file-relative-name directory project-root))))) (command (list "rg --no-heading --line-number --color never" "-S" (if all-files-p (progn "-z -uu")) (if recursive-p nil "--maxdepth 1"))) (helm-ag-base-command (string-join command " "))) (helm-attrset (quote name) (format "[rg %s] Searching %s" (string-join (delq nil (cdr command)) " ") (abbreviate-file-name directory)) helm-source-do-ag) (helm-attrset (quote +helm-command) command helm-source-do-ag) (let* ((vnew (function (lambda nil (helm :sources ... :prompt prompt :buffer "*helm-rg*" :keymap helm-do-ag-map :input query :history ...)))) (old (symbol-function (quote helm-do-ag--helm)))) (unwind-protect (progn (fset (quote helm-do-ag--helm) vnew) (helm-do-ag directory)) (fset (quote helm-do-ag--helm) old)))))
  (progn (let ((--cl-keys-- --cl-rest--)) (while --cl-keys-- (cond ((memq (car --cl-keys--) (quote (:query :in :all-files :recursive :allow-other-keys))) (setq --cl-keys-- (cdr (cdr --cl-keys--)))) ((car (cdr (memq ... --cl-rest--))) (setq --cl-keys-- nil)) (t (error "Keyword argument %s not one of (:query :in :all-files :recursive)" (car --cl-keys--)))))) (progn (if (executable-find "rg") nil (user-error "Couldn't find ripgrep in your PATH")) (require (quote helm-ag)) (helm-ag--init-state) (let* ((project-root (or (doom-project-root) default-directory)) (directory (or in project-root)) (default-directory directory) (helm-ag--default-directory directory) (helm-ag--default-target (list directory)) (query (or query (if (use-region-p) (progn ...)) "")) (prompt (format "[rg %s] " (cond (... ...) (... "./") (...)))) (command (list "rg --no-heading --line-number --color never" "-S" (if all-files-p (progn "-z -uu")) (if recursive-p nil "--maxdepth 1"))) (helm-ag-base-command (string-join command " "))) (helm-attrset (quote name) (format "[rg %s] Searching %s" (string-join (delq nil (cdr command)) " ") (abbreviate-file-name directory)) helm-source-do-ag) (helm-attrset (quote +helm-command) command helm-source-do-ag) (let* ((vnew (function (lambda nil ...))) (old (symbol-function (quote helm-do-ag--helm)))) (unwind-protect (progn (fset (quote helm-do-ag--helm) vnew) (helm-do-ag directory)) (fset (quote helm-do-ag--helm) old))))))
  (let* ((query (car (cdr (plist-member --cl-rest-- (quote :query))))) (in (car (cdr (plist-member --cl-rest-- (quote :in))))) (all-files (car (cdr (plist-member --cl-rest-- (quote :all-files))))) (recursive (car (cdr (or (plist-member --cl-rest-- (quote :recursive)) (quote (nil t))))))) (progn (let ((--cl-keys-- --cl-rest--)) (while --cl-keys-- (cond ((memq (car --cl-keys--) (quote ...)) (setq --cl-keys-- (cdr ...))) ((car (cdr ...)) (setq --cl-keys-- nil)) (t (error "Keyword argument %s not one of (:query :in :all-files :recursive)" (car --cl-keys--)))))) (progn (if (executable-find "rg") nil (user-error "Couldn't find ripgrep in your PATH")) (require (quote helm-ag)) (helm-ag--init-state) (let* ((project-root (or (doom-project-root) default-directory)) (directory (or in project-root)) (default-directory directory) (helm-ag--default-directory directory) (helm-ag--default-target (list directory)) (query (or query (if ... ...) "")) (prompt (format "[rg %s] " (cond ... ... ...))) (command (list "rg --no-heading --line-number --color never" "-S" (if all-files-p ...) (if recursive-p nil "--maxdepth 1"))) (helm-ag-base-command (string-join command " "))) (helm-attrset (quote name) (format "[rg %s] Searching %s" (string-join (delq nil ...) " ") (abbreviate-file-name directory)) helm-source-do-ag) (helm-attrset (quote +helm-command) command helm-source-do-ag) (let* ((vnew (function ...)) (old (symbol-function ...))) (unwind-protect (progn (fset ... vnew) (helm-do-ag directory)) (fset (quote helm-do-ag--helm) old)))))))
  +helm-file-search(:query nil :in nil :all-files nil)
  +helm/project-search(nil)
  funcall-interactively(+helm/project-search nil)
  call-interactively(+helm/project-search)
  (let ((default-directory (if arg (let* ((projects (and t ...))) (if projects (completing-read "Search project: " projects nil t nil nil (doom-project-root)) (user-error "There are no known projects"))) default-directory))) (call-interactively (cond (nil (function +ivy/project-search)) (t (function +helm/project-search)) ((function projectile-grep)))))
  +default/search-project(nil)
  funcall-interactively(+default/search-project nil)
  call-interactively(+default/search-project nil nil)
  command-execute(+default/search-project)
</pre></details>

**Steps to reproduce**
1. Use `SPC-s-p` from within a project, and get the error `void variable: all-files-p`.

**System information**
<details><pre>
emacs   version    26.3
        features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2
        build      Aug 29, 2019
        buildopts  (--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-modules 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now)
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop d2092ae44 2019-11-17 17:56:25 -0500
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /usr/bin/zsh
        uname      Linux 5.3.11-arch1-1 #1 SMP PREEMPT Tue, 12 Nov 2019 22:19:48 +0000 x86_64
        path       (~/.nvm/versions/node/v10.15.3/bin ~/.pyenv/shims ~/.jabba/jdk/adopt@1.8.0-222/bin ~/.pyenv/bin ~/.cargo/bin ~/.cabal/bin ~/.local/bin ~/go/bin ~/godev/bin ~/.emacs.d/bin /opt/google-cloud-sdk/bin /usr/local/bin /usr/local/sbin /usr/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /usr/lib/emacs/26.3/x86_64-pc-linux-gnu)
config  envfile    nil
        elc-files  0
        modules    (:completion company helm :ui doom doom-dashboard doom-quit fill-column hl-todo modeline nav-flash ophints (popup +all +defaults) (pretty-code +iosevka) treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold format multiple-cursors rotate-text snippets :emacs dired electric vc :term term :tools docker editorconfig eval flycheck (lookup +docsets) lsp magit make terraform :lang data emacs-lisp (go +lsp) javascript markdown (org +dragndrop +ipython +pandoc +present) (python +lsp +pyenv) (scala +lsp) sh :config (default +bindings +smartparens))
        packages   (n/a)
        elpa       (n/a)
</pre></details>

**Comment by hlissner** [comment]
As of fd979d8 this should be resolved. Let me know if that isn't the case and I'll reopen this issue. Thanks for bringing it to my attention!
