### ISSUE TITLE
[BUG] After clean install exec-path only contains emacs directory

### ISSUE THREAD

**Issue by teehemkay** [hlissner/doom-emacs#2077]
**Describe the issue**
I did a first install of doom.
Didn't make any change to the configuration.
Launched doom and saw the following error messages:

```
Doom loaded 173 packages across 34 modules in 0.886s
Error running timer ‘mac-setup-help-topics’: (error "Uncompression program ‘sh’ not found")
Error in menu-bar-update-hook (mac-setup-help-topics): (error "Uncompression program ‘sh’ not found")
apply: Searching for program: No such file or directory, git
```

Doom seems unable to find any executable.
`exec-path` only value is emacs directory `("/nix/store/bbviadvsbgj1i0ypvryz6b2d70hvhmjx-emacs-mac-26.3-7.7/libexec/emacs/26.3/x86_64-apple-darwin17.7.0/")`

FYIW, `doom--initial-exec-path` is `("/usr/local/bin" "/usr/bin" "/bin" "/usr/sbin" "/sbin" "/Applications/VMware Fusion.app/Contents/Public" "/nix/store/bbviadvsbgj1i0ypvryz6b2d70hvhmjx-emacs-mac-26.3-7.7/libexec/emacs/26.3/x86_64-apple-darwin17.7.0")`

This behaviour is only observed when in "graphical" mode.
When using emacs in terminal mode, everything works normally.

**Steps to reproduce**
```sh
git clone https://github.com/hlissner/doom-emacs ~/.emacs.d
~/.emacs.d/bin/doom install
```

**System information**
<details><pre>
((emacs
  (version . "26.3")
  (features . "NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS")
  (build . "Nov 04, 2019")
  (buildopts "--prefix=/nix/store/bbviadvsbgj1i0ypvryz6b2d70hvhmjx-emacs-mac-26.3-7.7 LDFLAGS=-L/nix/store/s8lxmd7rysm0y54s7lhgdcw9li1gh3la-ncurses-6.1-20190112/lib --with-xml2=yes --with-gnutls=yes --with-mac --with-modules '--enable-mac-app=$$out/Applications' CFLAGS=-O3")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD 24efd5b90 2019-11-18 19:10:24 -0500"))
 (system
  (type . darwin)
  (config . "x86_64-apple-darwin17.7.0")
  (shell . "/run/current-system/sw/bin/fish")
  (uname . "Darwin 18.5.0 Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64")
  (path "~/.emacs.d/bin" "~/.nix-profile/bin" "/run/current-system/sw/bin" "/nix/var/nix/profiles/default/bin" "/usr/local/bin" "/usr/bin" "/usr/sbin" "/bin" "/sbin" "/nix/store/bbviadvsbgj1i0ypvryz6b2d70hvhmjx-emacs-mac-26.3-7.7/libexec/emacs/26.3/x86_64-apple-darwin17.7.0"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold multiple-cursors rotate-text snippets :emacs dired electric ibuffer vc :tools (eval +overlay) flycheck (lookup +docsets) magit :lang data emacs-lisp markdown (org +dragndrop +ipython +pandoc +present) sh :config (default +bindings +smartparens))
  (packages "n/a")
  (elpa "n/a")))
</pre></details>

**Comment by hlissner** [comment]
Does running `doom env` fix the issue? And if not, what is the value of PATH in `~/.emacs.d/.local/env`?

**Comment by teehemkay** [comment]
Nope, it does not. I’ll confirm the value in `PATH` tomorrow when I’m in front of my work computer. But it should be the same as the one I mentioned on the ‘help’ discord channel : (`PATH=/Users/<userid>/.emacs.d/bin:/Users/<userid>/.nix-profile/bin:/run/current-system/sw/bin:/nix/var/nix/profiles/default/bin:/usr/local/bin:/usr/bin:/usr/sbin:/bin:/sbin`).

**Comment by hlissner** [comment]
As of 304506e this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by teehemkay** [comment]
I can confirm that this issue is fixed. Thanks for the quick turnaround!
