### ISSUE TITLE
[Question] How to open emacs manual in vertical window?

### ISSUE THREAD

**Issue by babygau** [hlissner/doom-emacs#208]
Currently `SPC h i` give me info manual in horizontal window, how to open it in vertical window?

<img width="1311" alt="open info manual in vertical mode" src="https://user-images.githubusercontent.com/1514823/30509152-bb6120c0-9aec-11e7-8768-c3a170609e38.png">

**Comment by hlissner** [comment]
The default rule for info-mode is `:align 'below :size 0.5 :select t :autokill t`. The relevant property is `:align`. You can change its rule with:

```emacs-lisp
;; put this in private/$USER/config.el
(set! :popup "*info*" :align 'right :size 0.5 :select t :autokill t) 
;; you can change 'right to 'left
```

Besides that, there is no way to move a live popup window yet -- I'm working on that.

**Comment by babygau** [comment]
Tks @hlissner, problem is solved 👍
