### ISSUE TITLE
[REQUEST] Use term for repl implementation

### ISSUE THREAD

**Issue by randomizedthinking** [hlissner/doom-emacs#2080]
**Describe the feature**
REPL is an important part of a user workflow. My understanding is that the current repl (or eval) implementation in doom uses eshell (or shell?). I find many issues when testing it with my workflows. My request is: whether we can use `term` for repl/eval implementation, while only use eshell (or shell) for elisp.

Below is one example of issues of using repl for python. It seems like a bug in eshell/shell.

**Steps to reproduce**
1. Open any python file;
2. SPC o R (I use ipython3 as repl interpreter);
3. Enter a simple function manually:
    ```python
    def test():
        print("hello")
    ```
4. See the error as screenshot below.
![image](https://user-images.githubusercontent.com/5283430/69175809-53d64400-0ab9-11ea-9661-ea64c90af5c5.png)

Then follow up with an extended explanation, if necessary. Here are some
suggestions on what to include:
- How is it helpful?

It is useful to make an ideal repl environment.

**System information**
<details><pre>
emacs   version    26.1
        features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 THREADS LIBSYSTEMD LCMS2
        build      Sep 22, 2019
        buildopts  (--build x86_64-linux-gnu --prefix=/usr --sharedstatedir=/var/lib --libexecdir=/usr/lib --localstatedir=/var/lib --infodir=/usr/share/info --mandir=/usr/share/man --enable-libsystemd --with-pop=yes --enable-locallisppath=/etc/emacs:/usr/local/share/emacs/26.1/site-lisp:/usr/local/share/emacs/site-lisp:/usr/share/emacs/26.1/site-lisp:/usr/share/emacs/site-lisp --with-sound=alsa --without-gconf --with-mailutils --build x86_64-linux-gnu --prefix=/usr --sharedstatedir=/var/lib --libexecdir=/usr/lib --localstatedir=/var/lib --infodir=/usr/share/info --mandir=/usr/share/man --enable-libsystemd --with-pop=yes --enable-locallisppath=/etc/emacs:/usr/local/share/emacs/26.1/site-lisp:/usr/local/share/emacs/site-lisp:/usr/share/emacs/26.1/site-lisp:/usr/share/emacs/site-lisp --with-sound=alsa --without-gconf --with-mailutils --with-x=yes --with-x-toolkit=gtk3 --with-toolkit-scroll-bars 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/emacs-StqULU/emacs-26.1+1=. -fstack-protector-strong -Wformat -Werror=format-security -Wall' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' LDFLAGS=-Wl,-z,relro)
        windowsys  nil
        daemonp    daemon
doom    version    2.0.9
        build      HEAD -> develop, origin/develop, origin/HEAD c1b912598 2019-11-17 22:56:51 -0800
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/zsh
        uname      Linux 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2 (2019-08-28) x86_64
        path       (/usr/local/bin /usr/local/sbin /usr/bin /bin /usr/games /usr/lib/surfraw ~/.fzf/bin ~/02-computing/linux/bin ~/.local/bin ~/.emacs.d/bin /usr/lib/emacs/26.1/x86_64-linux-gnu)
config  envfile    nil
        elc-files  0
        modules    (:completion company (ivy +fuzzy) :ui doom doom-dashboard hl-todo modeline nav-flash ophints (popup +all +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold (format +onsave) multiple-cursors rotate-text snippets :emacs dired electric vc :term eshell shell term :tools eval flycheck (lookup +docsets) lsp magit make tmux :lang cc clojure data emacs-lisp ess javascript markdown (org +dragndrop +ipython +pandoc +present) python sh :config (default +bindings +smartparens))
        packages   (n/a)
        elpa       (n/a)
</pre></details>

**Comment by hlissner** [comment]
I don't understand what you're asking. The current repl/eval implement uses neither eshell or term. For `python-mode` buffers it uses `inferior-python`, which uses comint. For `emacs-lisp-mode` buffers it uses `ielm`. 

If you're asking for a command to "send to term/eshell", that's non-trivial to implement and not really within the scope of the eval/repl module, as they are not really REPLs. Unlike REPLs, there's no way to tell if a term/eshell popup is associated with a certain buffer or not, which will create ambiguity if evaluating code across multiple buffers in different modes.

**Comment by randomizedthinking** [comment]
I see and thanks for the clarification. Given the information, then what shown above is a bug in the system. I also tested the inferior python mode in a vanilla emacs installation, and confirmed that it does not have the issue.

I will do some digging on my end and report back. Thanks.

**Comment by randomizedthinking** [comment]
This issue would have something to do with the interaction between python-mode and the approach doom uses to handle eval. Many hacks are used in python.el to implement code completion and send-code-to-repl etc -- which is not nice. Below is a screenshot of the issue:

![image](https://user-images.githubusercontent.com/5283430/69666388-06ba1b00-1041-11ea-9737-82dd302e16d3.png)

We can see that some codes were inserted at wrong places, which break the logic.

**Comment by randomizedthinking** [comment]
I will close this issue since it is largely a python-mode problem. Solutions built on python-mode, such as spacemacs python layer, elpy, etc, all have certain drawbacks and instabilities.
