### ISSUE TITLE
[HOWTO] Disable `+default--newline-indent-and-continue-comments-a` in Coq mode

### ISSUE THREAD

**Issue by Ptival** [hlissner/doom-emacs#2081]
**What I want to achieve**
`+default--newline-indent-and-continue-comments-a` is infuriating in Coq mode. Coq comments are not line comments, and I really doubt anyone writes comments like those:

```
(** Start of a sentence *)
(** that continues on *)
(** other lines. *)
```

Instead, this is enough:

```
(** Start of a sentence
    that continues on
    other lines. *)
```

and allows itself better to things like `g q`...

I don't know how to disable this feature, either globally, or simply in Coq mode.

Alternatively, is there a way to force a newline character? Sadly, the `Ctrl V` trick inserts `^M`.

**Comment by hlissner** [comment]
The correct fix for this would be PR a better `comment-line-break-function` for `coq-mode` upstream, but for the time being, this should work around the issue:

```elisp
(setq-hook! 'coq-mode-hook comment-line-break-function nil)
```

**Comment by Ptival** [comment]
Sounds good. Thank you for preserving my sanity! <3
