### ISSUE TITLE
[BUG] tramp-histfile-override error when using tramp

### ISSUE THREAD

**Issue by dinkonin** [hlissner/doom-emacs#2085]
**Describe the issue**
after ed3408d839c09ddc64babba2572dc67aeb636c5f
I get `tramp-signal-hook-function: (‘tramp-histfile-override’ uses invalid file ‘/home/USER/.emacs.d/.local/cache/tramp-histfile.el’)
` using tramp in elisp scripts

**Steps to reproduce**
eval this 
  `(copy-file "/ssh:server:/tmp/file" "/tmp/file" t)`

Tried it on linux emacs 26 and 27. 
If I reset `tramp-histfile-override` the problem dissapears.

**Comment by hlissner** [comment]
As of a4fcbb4 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
