### ISSUE TITLE
[BUG] file-missing Cannot open load file No such file or directory org-version.el

### ISSUE THREAD

**Issue by flyingns** [hlissner/doom-emacs#2089]
**Describe the issue**
Update to commit `b63e62e` and restart emacs to report:

<details><pre>
Error running timer ‘require’: (file-missing "Cannot open load file" "No such file or directory" "org-version.el")
Loading /Users/mls/.emacs.d.new/.local/cache/recentf...done
Error running timer ‘require’: (file-missing "Cannot open load file" "No such file or directory" "org-version.el") [3 times]
Failed to load ’magit’ package incrementally, because: (file-missing Cannot open load file No such file or directory org-version.el)
Failed to load ’org’ package incrementally, because: (file-missing Cannot open load file No such file or directory org-version.el)
Failed to load ’org-agenda’ package incrementally, because: (file-missing Cannot open load file No such file or directory org-version.el)
Failed to load ’org-capture’ package incrementally, because: (file-missing Cannot open load file No such file or directory org-version.el)
Failed to load ’org’ package incrementally, because: (file-missing Cannot open load file No such file or directory org-version.el)
</pre></details>

**Comment by ckruse** [comment]
`./bin/doom build` fixes this issue

**Comment by flyingns** [comment]
OK, Thanks.

I was a bit confused and didn't think about it in time.
