### ISSUE TITLE
[Question] How to disable fringe completely?

### ISSUE THREAD

**Issue by babygau** [hlissner/doom-emacs#209]
Using  either 
`(global-vi-tilde-fringe-mode -1)` 
or
`(package! vi-tilde-fringe :ignore t)`
doesn't hide the tildes in number column.

**Comment by hlissner** [comment]
`(fringe-mode 0)` is all you need.

You don't need to, but if you want to be complete you can disable all the fringe plugins too:

```emacs-lisp
;; private/$USER/config.el
(def-package-hook! vi-tilde-fringe :disable)
(def-package-hook! git-gutter-fringe :disable)

;; private/$USER/packages.el
(package! vi-tilde-fringe :ignore t)
(package! git-gutter-fringe :ignore t)
```

**Comment by babygau** [comment]
Tks @hlissner 👍, 
Problem is partly solved as I'm still able to see tiny tildes in `neotree` though it's not too important.

**Comment by hlissner** [comment]
Oh, I made a mistake. Put those `def-package-hook!` calls in `private/$USER/init.el`, not `config.el`. That should solve your neotree issue.
