### ISSUE TITLE
Cannot change theme with `M-x customize-themes`

### ISSUE THREAD

**Issue by TotNotTac** [hlissner/doom-emacs#2090]
# What I did
`M-x customize-themes` Click on doom-snazzy and relaunch emacs

# What I get
Following message in the minibuffer:  `Loading a theme can  run Lisp code. Really load? (y or n)`

# What I tried
I tried filling in y and no. I also tried first pressing i and then y and n. I tried editting .doom.d/init.el to load doom-dracula instead. That fixes Emacs. But I'd rather use doom-snazzy.

**Comment by TotNotTac** [comment]
My discord username is Totoro

**Comment by hlissner** [comment]
See https://github.com/hlissner/doom-emacs/blob/develop/docs/faq.org#how-do-i-change-the-theme

I'd recommend you do not use `M-x customize`. It is not supported by Doom and is not the correct way to customize your theme in Doom.

Hope that helps!
