### ISSUE TITLE
[QUESTION]  format-project

### ISSUE THREAD

**Issue by alienzj** [hlissner/doom-emacs#2091]
Hello, doom-emacs hacker,
Can I use doom-emacs to format all source code files under the entire project at once without opening all the project files ?

**Comment by hlissner** [comment]
Not easily. Your best bet is to run your formatter on the command line on all your source files.

If you're dead set on doing it in Emacs, you can try something like this:

```elisp
(dolist (file (doom-files-in "path/to/project" :match "\\.py$"))
  (with-current-buffer (find-file-noselect file)
    (call-interactively #'format-all-buffer)
    (save-buffer)))
```

But it'd be *incredibly* slow, depending on project size.

**Comment by alienzj** [comment]
So nice !
Thanks very much.
I will try it !
