### ISSUE TITLE
[QUESTION]  Add video tutorial to README.md

### ISSUE THREAD

**Issue by myrgy** [hlissner/doom-emacs#2093]
Hi @hlissner ,

would you mind adding link to that video tutorials to main project link:
https://www.youtube.com/playlist?list=PLhXZp00uXBk4np17N39WvB80zgxlZfVwj

I think it could be really helpful for new doom-emacs users.

Thank you in advance!

**Comment by hlissner** [comment]
It is already in Doom's documentation: https://github.com/hlissner/doom-emacs/blob/develop/docs/index.org#tutorials--guides
