### ISSUE TITLE
[BUG] (void-variable dir) when toggling shell after deleting its buffer

### ISSUE THREAD

**Issue by WhatDothLife** [hlissner/doom-emacs#2095]
The `dir` variable gets lost when the shell popup buffer is closed by killing the buffer.

1. Open a shell popup buffer
2. Delete its buffer
3. Invoke `+shell/toggle`

This could be reproduced without my private config.

Below are the debug output and my system stats.

<details><pre>

Debugger entered--Lisp error: (void-variable dir)
  (cd dir)
  (if (not (eq major-mode (quote shell-mode))) (shell buffer) (erase-buffer) (cd dir))
  (save-current-buffer (set-buffer (pop-to-buffer buffer)) (if (not (eq major-mode (quote shell-mode))) (shell buffer) (erase-buffer) (cd dir)) (let ((process (get-buffer-process (current-buffer)))) (set-process-sentinel process (function +shell--sentinel)) (if command (progn (comint-send-string process command)))))
  (if win (if (eq (selected-window) win) (let (confirm-kill-processes) (set-process-query-on-exit-flag (get-buffer-process buffer) nil) (delete-window win) (condition-case nil (progn (kill-buffer buffer)) (error nil))) (select-window win) (if (and (boundp (quote evil-local-mode)) evil-local-mode) (progn (evil-change-to-initial-state))) (goto-char (point-max))) (save-current-buffer (set-buffer (pop-to-buffer buffer)) (if (not (eq major-mode (quote shell-mode))) (shell buffer) (erase-buffer) (cd dir)) (let ((process (get-buffer-process (current-buffer)))) (set-process-sentinel process (function +shell--sentinel)) (if command (progn (comint-send-string process command))))))
  (let* ((win (and t (get-buffer-window buffer)))) (if win (if (eq (selected-window) win) (let (confirm-kill-processes) (set-process-query-on-exit-flag (get-buffer-process buffer) nil) (delete-window win) (condition-case nil (progn (kill-buffer buffer)) (error nil))) (select-window win) (if (and (boundp (quote evil-local-mode)) evil-local-mode) (progn (evil-change-to-initial-state))) (goto-char (point-max))) (save-current-buffer (set-buffer (pop-to-buffer buffer)) (if (not (eq major-mode (quote shell-mode))) (shell buffer) (erase-buffer) (cd dir)) (let ((process (get-buffer-process (current-buffer)))) (set-process-sentinel process (function +shell--sentinel)) (if command (progn (comint-send-string process command)))))))
  (let ((buffer (get-buffer-create (format "*doom:shell-popup:%s*" (if (and (boundp ...) persp-mode) (safe-persp-name (get-current-persp)) "main"))))) (let* ((win (and t (get-buffer-window buffer)))) (if win (if (eq (selected-window) win) (let (confirm-kill-processes) (set-process-query-on-exit-flag (get-buffer-process buffer) nil) (delete-window win) (condition-case nil (progn (kill-buffer buffer)) (error nil))) (select-window win) (if (and (boundp (quote evil-local-mode)) evil-local-mode) (progn (evil-change-to-initial-state))) (goto-char (point-max))) (save-current-buffer (set-buffer (pop-to-buffer buffer)) (if (not (eq major-mode (quote shell-mode))) (shell buffer) (erase-buffer) (cd dir)) (let ((process (get-buffer-process ...))) (set-process-sentinel process (function +shell--sentinel)) (if command (progn (comint-send-string process command))))))))
  +shell/toggle()
</pre></details>

<details><pre>

```
emacs   version    26.3
        features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2
        build      Aug 29, 2019
        buildopts  (--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-modules 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now)
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop 83090894d 2019-11-21 00:50:25 -0500
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/bash
        uname      Linux 5.3.11-1-MANJARO #1 SMP PREEMPT Wed Nov 13 12:21:14 UTC 2019 x86_64
        path       (~/.local/bin /usr/local/bin /usr/local/sbin /usr/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /var/lib/snapd/snap/bin /usr/lib/emacs/26.3/x86_64-pc-linux-gnu)
config  envfile    nil
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold format multiple-cursors rotate-text snippets :emacs dired electric ibuffer vc :term shell term :tools editorconfig ein (eval +overlay) flycheck flyspell (lookup +docsets) magit make pass pdf :lang cc data emacs-lisp latex markdown (org +dragndrop +ipython +pandoc +present) python sh :email mu4e :app calendar :config (default +bindings +smartparens))
        packages   (n/a)
        elpa       (n/a)
```

</pre></details>

**Comment by hlissner** [comment]
As of 0212bb9 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
