### ISSUE TITLE
how to load some setting in private/USER/config.el

### ISSUE THREAD

**Issue by sunznx** [hlissner/doom-emacs#210]
in my config.el, I use these
```
(def-package! hungry-delete
  :commands
  (global-hungry-delete-mode)
  :config
  (global-hungry-delete-mode 1)
  )


(load! +appearance)
(load! +misc-setting)
```

seem no effected, After I restart emacs and use "eval buffer", and everything is ok

**Comment by hlissner** [comment]
This suggests your private module isn't being loaded. What is the file path to your private module?

Your private module must be named after your username (see `user-login-name` or run `whoami` in the terminal). e.g. `modules/private/sunznx/...`

As long as the names match your private module will be automatically loaded.

**Comment by sunznx** [comment]
whether
