### ISSUE TITLE
[BUG] visible modeline and missing prompt after deleting and toggling the shell popup

### ISSUE THREAD

**Issue by WhatDothLife** [hlissner/doom-emacs#2100]
Even though the error of #2095 was solved, there are still some issues after deleting the popup buffer of the shell. The modeline is visible and the shell prompt is missing.
![shell](https://user-images.githubusercontent.com/33008303/69377566-d5da8e80-0cac-11ea-81dd-8328b3353b46.png)

**Comment by hlissner** [comment]
Please include steps to reproduce this.

**Comment by WhatDothLife** [comment]
> Please include steps to reproduce this.

1. Call `+shell/toggle`
2. Call `kill-current-buffer`
3. Again, call `+shell/toggle`

**Comment by hlissner** [comment]
This should be fixed in aa19eee. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
