### ISSUE TITLE
[HOWTO] define keybindings for logview major-mode

### ISSUE THREAD

**Issue by Pentaquark1** [hlissner/doom-emacs#2105]
logview-mode is read only, I would like to use the keybindings that were originally intended by the author (for instance jumping to next entry with "n")

I tried this way but it does not seem to work:
```
(map! :map logview-mode-map
      :nv "n" 'logview-next-entry)
```

How do I add these keybindings for logview-mode, or how do I add keybindings to existing ones?

**Comment by hlissner** [comment]
I'm assuming you're talking about https://github.com/doublep/logview and not the log-view built into Emacs.

If that is so, then your snippet should work _if_ logview-mode is indeed started in normal/visual mode. Check the value of `evil-state` while in a logview buffer to make sure this is the case. e.g. `C-h v evil-state`.

Alternatively, you could just have logview-mode start in emacs state:

```elisp
(after! logview
  (set-evil-initial-state! 'logview-mode 'emacs))
````

**Comment by Pentaquark1** [comment]
Hi, thank you for your response!

You are assuming correctly, the question is about https://github.com/doublep/logview and your suggestion to have logview-mode start in emacs state worked!

The manually defind keybinding does not yet get recognized however. ```C-h v evil-state``` does return normal, there seems to still be an issue with how I defined it.
I also tried it in the same way with a binding in org-mode-map, which did not work either:

(map! :map org-mode-map
      :n "n" 'org-next-visible-heading)	; q in normal+visual states

Both of these in bindings.el, any Iidea where Im going wrong here?

**Comment by hlissner** [comment]
For your org keybinds, try binding them to `evil-org-mode-map` instead:

```elisp
(map! :after evil-org
      :map evil-org-mode-map
      :n "n" #'org-next-visible-heading)
```

Side note: `org-next-visible-heading` and `org-previous-visible-heading` is already on `]]` and `[[`, respectively.
