### ISSUE TITLE
[BUG] doom/help-modules doesn't work

### ISSUE THREAD

**Issue by RBckmnn** [hlissner/doom-emacs#2107]
**Steps to reproduce**
1. Start new emacs session
2. Use `SPC h d m` to invoke `doom/help-modules`
3. Request e.g. help for ":editor evil"
4. The command errors out (see backtrace below)

<details><pre>
Debugger entered--Lisp error: (error "Cannot get this file-path")
  signal(error ("Cannot get this file-path"))
  error("Cannot get this file-path")
  (cond ((and (boundp (quote byte-compile-current-file)) byte-compile-current-file)) (load-file-name) ((stringp (car-safe current-load-list)) (car current-load-list)) (buffer-file-name) ((error "Cannot get this file-path")))
  file!()
  (doom-module-from-path (file!))
  (if doom--current-module (if enabled-only (and (doom-module-p (car doom--current-module) (cdr doom--current-module)) doom--current-module) doom--current-module) (doom-module-from-path (file!)))
  (if (null path) (if doom--current-module (if enabled-only (and (doom-module-p (car doom--current-module) (cdr doom--current-module)) doom--current-module) doom--current-module) (doom-module-from-path (file!))) (let* ((file-name-handler-alist nil) (path (file-truename (or path (file!))))) (let ((save-match-data-internal (match-data))) (unwind-protect (progn (cond ((string-match "/modules/\\([^/]+\\)/\\([^/]+\\)\\(?:/.*\\)?$" path) (let* ... ...)) ((file-in-directory-p path doom-core-dir) (cons :core ...)) ((file-in-directory-p path doom-private-dir) (cons :private ...)))) (set-match-data save-match-data-internal (quote evaporate))))))
  doom-module-from-path(nil)
  (let* ((module-string (completing-read "Describe module: " (doom--help-modules-list) nil t nil nil (doom--help-current-module-str))) (key (doom-module-from-path (car (get-text-property 0 (quote location) module-string))))) (list (car key) (cdr key)))
  call-interactively(doom/help-modules nil nil)
  command-execute(doom/help-modules)
</pre></details>

If one subsequently opens `core/autoload/help.el` the behaviour changes slightly. Invocation the command then gives an error with the following backtrace:

<details><pre>
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  file-readable-p(nil)
  (if (file-readable-p path) nil (error "'%s %s' isn't a valid module; it doesn't exist" category module))
  (let ((path (doom-module-locate-path category module))) (if (file-readable-p path) nil (error "'%s %s' isn't a valid module; it doesn't exist" category module)) (let* ((readme-path (and t (doom-module-locate-path category module "README.org")))) (if readme-path (find-file readme-path) (if (y-or-n-p (format "The '%s %s' module has no README file. Explore its directory?" category module)) (doom-project-browse path) (user-error "Aborted module lookup")))))
  doom/help-modules(:core help)
  funcall-interactively(doom/help-modules :core help)
  call-interactively(doom/help-modules nil nil)
  command-execute(doom/help-modules)
</pre></details>

**System information**
<details>

```
emacs   version    26.2
        features   XPM JPEG TIFF GIF PNG RSVG SOUND GPM DBUS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE XFT ZLIB GTK3 X11 XDBE XIM THREADS XWIDGETS LCMS2
        build      Jul 01, 2019
        buildopts  (--prefix=/usr --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu --mandir=/usr/share/man --infodir=/usr/share/info --datadir=/usr/share --sysconfdir=/etc --localstatedir=/var/lib --disable-silent-rules --docdir=/usr/share/doc/emacs-26.2 --htmldir=/usr/share/doc/emacs-26.2/html --libdir=/usr/lib64 --program-suffix=-emacs-26 --includedir=/usr/include/emacs-26 --infodir=/usr/share/info/emacs-26 --localstatedir=/var --enable-locallisppath=/etc/emacs:/usr/share/emacs/site-lisp --without-compress-install --without-hesiod --without-pop --with-file-notification=inotify --enable-acl --with-dbus --without-modules --without-gameuser --with-gpm --without-kerberos --without-kerberos5 --with-lcms2 --with-xml2 --without-mailutils --without-selinux --with-gnutls --without-libsystemd --with-threads --without-wide-int --with-zlib --with-sound=alsa --with-x --without-ns --without-gconf --without-gsettings --without-toolkit-scroll-bars --with-gif --with-jpeg --with-png --with-rsvg --with-tiff --with-xpm --without-imagemagick --with-xft --without-cairo --without-libotf --without-m17n-flt --with-x-toolkit=gtk3 --with-xwidgets 'CFLAGS=-march=native -O2 -pipe' CPPFLAGS= 'LDFLAGS=-Wl,-O1 -Wl,--as-needed')
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop, upstream/develop 5ece51a2a 2019-11-23 01:44:49 -0500
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/bash
        uname      Linux 4.19.82-gentoo #1 SMP Sun Nov 10 18:48:00 CET 2019 x86_64
        path       (/usr/lib/llvm/8/bin /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /opt/bin ~/.emacs.d/bin ~/.local/bin /usr/libexec/emacs/26.2/x86_64-pc-linux-gnu)
config  envfile    nil
        elc-files  0
        modules    (:completion company helm :ui doom doom-dashboard hl-todo modeline nav-flash ophints (popup +all +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold multiple-cursors rotate-text snippets :emacs (dired +icons) electric ibuffer vc :term term :tools (eval +overlay) flycheck (lookup +docsets) lsp magit :lang data emacs-lisp (javascript +lsp) markdown (org +dragndrop +ipython +pandoc +present) (python +lsp) sh web :config literate (default +bindings +smartparens))
        packages   (n/a)
        elpa       (n/a)
```
</details>

I first suspected that the extraction of text properties in the implementation of the command caused issues with helm, but the error also occurs with helm, ivy and ido disabled in my doom-block.

**Comment by hlissner** [comment]
d11902f and ebe1da4 should fix this issue. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by RBckmnn** [comment]
`doom/help-modules` now works, but only if ivy is used as the completion framework. Any other choice of framework (including none at all) leads to

> user-error: Did not select a valid module

Non-interactive calls the to command work fine though.

**Comment by hlissner** [comment]
@RBckmnn That should becorrected in a9f412b. Let me know if that isn't the case!

**Comment by RBckmnn** [comment]
Works like a charm, thanks Henrik.
