### ISSUE TITLE
[BUG] Eager macro-expansion failure: (wrong-type-argument symbolp (magithub :disable t))

### ISSUE THREAD

**Issue by meziberry** [hlissner/doom-emacs#2112]
**Describe the issue**

when i run `doom upgrade`, the following was printed: the `doom info` has the same result.

> Eager macro-expansion failure: (wrong-type-argument symbolp (magithub :disable t))
> Eager macro-expansion failure: (wrong-type-argument symbolp (magithub :disable t))
> ---------------------------------------------------------------
> 
> There was an unexpected error:
>   Error with packages (doom-package-error)
>   (:private . packages)
>   (wrong-type-argument symbolp (magithub :disable t))
> 
> Run the command again with the -d (or --debug) option to enable debug
> mode and, hopefully, generate a stack trace. If you decide to file a bug
> report, please include it!
> 
> Emacs outputs to standard error, so you'll need to redirect stderr to
> stdout to pipe this to a file or clipboard!
> 
>   e.g. doom -d install 2>&1 | clipboard-program
> 
> > Preparing to upgrade Doom Emacs and its packages...
> ✓ Doom is already up-to-date!
> Error in Doom Emacs core: doom-package-error, (:private . packages), (wrong-type-argument symbolp (magithub :disable t))
> 

HEAD is `886fa36ac`, i use doom-emacs on win10+mingw.

**Comment by hlissner** [comment]
The error indicates there is an error in your `package!` declaration in `~/.doom.d/packages.el`. Please include a link to it (or copy paste its contents here).

Without more information I can only guess that you have this in your private config somewhere:

```elisp
(package! (magithub :disable t))
```

Which is incorrect, and should be:

```elisp
(package! magithub :disable t)
```

On the other hand, `magithub` hasn't been in Doom for quite some time (possibly half a year?), so you could get rid of this altogether.

**Comment by meziberry** [comment]
> (disable-packages! (magithub :disable t))

Really，This is contained in `~/.doom.d/packages.el`.  Now, I have deleted it , `doom upgrade` is working.  Thank you for your work, i really like the doom-emacs.

**Comment by hlissner** [comment]
Ah, I see. I'm glad we could figure it out.

For posterity: `disable-packages!` takes N package symbols, but will not accept sublists. Its correct usage would've been:

```elisp
(disable-packages! magithub)
```
