### ISSUE TITLE
[BUG] Wrong type argument: hash-table-p, nil

### ISSUE THREAD

**Issue by dfischer** [hlissner/doom-emacs#2113]
**Describe the issue**
I have seen this error come out for various things but it's really messing with my flow right now on opening projects and looking for files.

<details><pre>
Debugger entered--Lisp error: (wrong-type-argument hash-table-p nil)
  gethash("/home/dfischer/Code/coresnowboardcampshugo/" nil)
  projectile-project-files("/home/dfischer/Code/coresnowboardcampshugo/")
  projectile-current-project-files()
  (let ((files (projectile-current-project-files))) (if (<= (length files) ivy-sort-max-size) (function counsel-projectile-find-file) (function projectile-find-file)))
  (cond ((or (file-equal-p default-directory "~") (let* ((proot (and t (doom-project-root)))) (if proot (file-equal-p proot "~") nil))) (function counsel-find-file)) ((doom-project-p) (let ((files (projectile-current-project-files))) (if (<= (length files) ivy-sort-max-size) (function counsel-projectile-find-file) (function projectile-find-file)))) ((function counsel-file-jump)))
  (call-interactively (cond ((or (file-equal-p default-directory "~") (let* ((proot (and t ...))) (if proot (file-equal-p proot "~") nil))) (function counsel-find-file)) ((doom-project-p) (let ((files (projectile-current-project-files))) (if (<= (length files) ivy-sort-max-size) (function counsel-projectile-find-file) (function projectile-find-file)))) ((function counsel-file-jump))))
  +ivy/projectile-find-file()
  funcall-interactively(+ivy/projectile-find-file)
  call-interactively(+ivy/projectile-find-file nil nil)
  command-execute(+ivy/projectile-find-file)

</pre></details>

1. Load emacs
2. Load project
3. Error
4. space + space
5. error

**System information**
<details><pre>

```
emacs   version    26.3
        features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS LIBSYSTEMD LCMS2
        build      Sep 23, 2019
        buildopts  (--build x86_64-linux-gnu --prefix=/usr --sharedstatedir=/var/lib --libexecdir=/usr/lib --localstatedir=/var/lib --infodir=/usr/share/info --mandir=/usr/share/man --enable-libsystemd --with-pop=yes --enable-locallisppath=/etc/emacs:/usr/local/share/emacs/26.3/site-lisp:/usr/local/share/emacs/site-lisp:/usr/share/emacs/26.3/site-lisp:/usr/share/emacs/site-lisp --with-sound=alsa --without-gconf --with-mailutils --build x86_64-linux-gnu --prefix=/usr --sharedstatedir=/var/lib --libexecdir=/usr/lib --localstatedir=/var/lib --infodir=/usr/share/info --mandir=/usr/share/man --enable-libsystemd --with-pop=yes --enable-locallisppath=/etc/emacs:/usr/local/share/emacs/26.3/site-lisp:/usr/local/share/emacs/site-lisp:/usr/share/emacs/26.3/site-lisp:/usr/share/emacs/site-lisp --with-sound=alsa --without-gconf --with-mailutils --with-x=yes --with-x-toolkit=gtk3 --with-toolkit-scroll-bars 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/emacs-wvqver/emacs-26.3+1=. -fstack-protector-strong -Wformat -Werror=format-security -Wall' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro')
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop 83090894d 2019-11-21 00:50:25 -0500
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /usr/bin/fish
        uname      Linux 5.3.0-22-generic #24+system76~1573659475~19.10~26b2022-Ubuntu SMP Wed Nov 13 20:0 x86_64
        path       (~/.scripts/ ~/.local/bin/ ~/.emacs.d/bin/ ~/.cargo/bin/ /usr/local/sbin/ /usr/local/bin/ /usr/sbin/ /usr/bin/ /sbin/ /bin/ /usr/games/ /usr/local/games/ /usr/lib/cuda/bin/ /usr/lib/emacs/26.3/x86_64-linux-gnu/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) unicode vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold (format +onsave) multiple-cursors rotate-text snippets word-wrap :emacs dired electric ibuffer vc :term eshell :tools (eval +overlay) flycheck (lookup +docsets) lsp magit pass rgb terraform :lang data emacs-lisp (go +lsp) (javascript +lsp) markdown (org +dragndrop +ipython +pandoc +present) rest rust sh (web +lsp) :app (write +wordnut +langtool) :config (default +bindings +smartparens))
        packages   (n/a)
        elpa       (n/a)
```

</pre></details>

**Comment by hlissner** [comment]
I cannot reproduce this. I'm not even sure how this error is even possible. It would seem that one of the following two variables is uninitialized when you call `+ivy/projectile-find-file`:

+ projectile-projects-cache-time
+ projectile-projects-cache

However, both variables are initialized when projectile is first loaded (and `projectile-mode` is enabled -- which is necessary in order for any of these commands to work in the first place).

1. Please check your \*Messages\* buffer for errors or warnings that may have occurred during startup or before step 2 in your steps-to-reproduce.

2. If nothing stands out, try deleting your projectile cache files manually: `~/.emacs.d/.local/cache/projectile.*`

3. If that too, doesn't work, try to reproduce it in vanilla Doom using [the `C-c C-p` option in Doom's sandbox](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#testing-in-dooms-sandbox).
