### ISSUE TITLE
[BUG] Error loading journal when Emacs starts

### ISSUE THREAD

**Issue by cxb811201** [hlissner/doom-emacs#2119]
**Describe the issue**
Error loading journal when Emacs starts

<details><pre>
Debugger entered--Lisp error: (doom-module-error "modules/lang/org/contrib/journal.el" (end-of-file "/home/chenxianbin/.emacs.d/modules/lang/org/contrib/journal.el"))
  signal(doom-module-error ("modules/lang/org/contrib/journal.el" (end-of-file "/home/chenxianbin/.emacs.d/modules/lang/org/contrib/journal.el")))
  (let* ((source (file-name-sans-extension (expand-file-name "contrib/journal" "/home/chenxianbin/.emacs.d/modules/lang/org"))) (err (cond ((not (featurep 'core)) (cons 'error (file-name-directory path))) ((file-in-directory-p source doom-core-dir) (cons 'doom-error doom-core-dir)) ((file-in-directory-p source doom-private-dir) (cons 'doom-private-error doom-private-dir)) ((cons 'doom-module-error doom-emacs-dir))))) (signal (car err) (list (file-relative-name (concat source ".el") (cdr err)) e)))
  (condition-case e (let (file-name-handler-alist) (load (expand-file-name "contrib/journal" "/home/chenxianbin/.emacs.d/modules/lang/org") nil 'nomessage)) ((debug doom-error) (signal (car e) (cdr e))) ((debug error) (let* ((source (file-name-sans-extension (expand-file-name "contrib/journal" "/home/chenxianbin/.emacs.d/modules/lang/org"))) (err (cond ((not ...) (cons ... ...)) ((file-in-directory-p source doom-core-dir) (cons ... doom-core-dir)) ((file-in-directory-p source doom-private-dir) (cons ... doom-private-dir)) ((cons ... doom-emacs-dir))))) (signal (car err) (list (file-relative-name (concat source ".el") (cdr err)) e)))))
  (condition-case-unless-debug e (let (file-name-handler-alist) (load (expand-file-name "contrib/journal" "/home/chenxianbin/.emacs.d/modules/lang/org") nil 'nomessage)) (doom-error (signal (car e) (cdr e))) (error (let* ((source (file-name-sans-extension (expand-file-name "contrib/journal" "/home/chenxianbin/.emacs.d/modules/lang/org"))) (err (cond ((not ...) (cons ... ...)) ((file-in-directory-p source doom-core-dir) (cons ... doom-core-dir)) ((file-in-directory-p source doom-private-dir) (cons ... doom-private-dir)) ((cons ... doom-emacs-dir))))) (signal (car err) (list (file-relative-name (concat source ".el") (cdr err)) e)))))
  (load! "contrib/journal")
  (if (featurep! +journal) (load! "contrib/journal"))
  (progn (defvar org-directory "~/org/") (defvar org-attach-id-dir ".attach/") (setq org-publish-timestamp-directory (concat doom-cache-dir "org-timestamps/") org-preview-latex-image-directory (concat doom-cache-dir "org-latex/")) (defvar org-modules '(ol-bibtex)) (add-hook 'org-mode-local-vars-hook #'eldoc-mode) (add-hook! 'org-mode-hook #'doom-disable-show-paren-mode-h #'doom-disable-show-trailing-whitespace-h #'+org-enable-auto-reformat-tables-h #'+org-enable-auto-update-cookies-h #'+org-unfold-to-2nd-level-or-point-h) (add-hook! 'org-load-hook #'+org-init-appearance-h #'+org-init-agenda-h #'+org-init-babel-h #'+org-init-babel-lazy-loader-h #'+org-init-capture-defaults-h #'+org-init-capture-frame-h #'+org-init-centralized-attachments-h #'+org-init-centralized-exports-h #'+org-init-custom-links-h #'+org-init-export-h #'+org-init-habit-h #'+org-init-hacks-h #'+org-init-keybinds-h #'+org-init-popup-rules-h #'+org-init-protocol-h #'+org-init-protocol-lazy-loader-h #'+org-init-smartparens-h) (if (featurep! +dragndrop) (load! "contrib/dragndrop")) (if (featurep! +ipython) (load! "contrib/ipython")) (if (featurep! +journal) (load! "contrib/journal")) (if (featurep! +pomodoro) (load! "contrib/pomodoro")) (if (featurep! +present) (load! "contrib/present")) (when (and (featurep 'org) (not doom-reloading-p) (not byte-compile-current-file)) (message "`org' was already loaded by the time lang/org load...") (run-hooks 'org-load-hook)))
  eval((progn (defvar org-directory "~/org/") (defvar org-attach-id-dir ".attach/") (setq org-publish-timestamp-directory (concat doom-cache-dir "org-timestamps/") org-preview-latex-image-directory (concat doom-cache-dir "org-latex/")) (defvar org-modules '(ol-bibtex)) (add-hook 'org-mode-local-vars-hook #'eldoc-mode) (add-hook! 'org-mode-hook #'doom-disable-show-paren-mode-h #'doom-disable-show-trailing-whitespace-h #'+org-enable-auto-reformat-tables-h #'+org-enable-auto-update-cookies-h #'+org-unfold-to-2nd-level-or-point-h) (add-hook! 'org-load-hook #'+org-init-appearance-h #'+org-init-agenda-h #'+org-init-babel-h #'+org-init-babel-lazy-loader-h #'+org-init-capture-defaults-h #'+org-init-capture-frame-h #'+org-init-centralized-attachments-h #'+org-init-centralized-exports-h #'+org-init-custom-links-h #'+org-init-export-h #'+org-init-habit-h #'+org-init-hacks-h #'+org-init-keybinds-h #'+org-init-popup-rules-h #'+org-init-protocol-h #'+org-init-protocol-lazy-loader-h #'+org-init-smartparens-h) (if (featurep! +dragndrop) (load! "contrib/dragndrop")) (if (featurep! +ipython) (load! "contrib/ipython")) (if (featurep! +journal) (load! "contrib/journal")) (if (featurep! +pomodoro) (load! "contrib/pomodoro")) (if (featurep! +present) (load! "contrib/present")) (when (and (featurep 'org) (not doom-reloading-p) (not byte-compile-current-file)) (message "`org' was already loaded by the time lang/org load...") (run-hooks 'org-load-hook))) t)
  #f(compiled-function (&rest body) "Like `progn', but evaluates the body at compile time and at\nload time.  In interpreted code, this is entirely equivalent to\n`progn', except that the value of the expression may be (but is\nnot necessarily) computed at load time if eager macro expansion\nis enabled." #<bytecode 0x1fc6e370231b>)((defvar org-directory "~/org/") (defvar org-attach-id-dir ".attach/") (setq org-publish-timestamp-directory (concat doom-cache-dir "org-timestamps/") org-preview-latex-image-directory (concat doom-cache-dir "org-latex/")) (defvar org-modules '(ol-bibtex)) (add-hook 'org-mode-local-vars-hook #'eldoc-mode) (add-hook! 'org-mode-hook #'doom-disable-show-paren-mode-h #'doom-disable-show-trailing-whitespace-h #'+org-enable-auto-reformat-tables-h #'+org-enable-auto-update-cookies-h #'+org-unfold-to-2nd-level-or-point-h) (add-hook! 'org-load-hook #'+org-init-appearance-h #'+org-init-agenda-h #'+org-init-babel-h #'+org-init-babel-lazy-loader-h #'+org-init-capture-defaults-h #'+org-init-capture-frame-h #'+org-init-centralized-attachments-h #'+org-init-centralized-exports-h #'+org-init-custom-links-h #'+org-init-export-h #'+org-init-habit-h #'+org-init-hacks-h #'+org-init-keybinds-h #'+org-init-popup-rules-h #'+org-init-protocol-h #'+org-init-protocol-lazy-loader-h #'+org-init-smartparens-h) (if (featurep! +dragndrop) (load! "contrib/dragndrop")) (if (featurep! +ipython) (load! "contrib/ipython")) (if (featurep! +journal) (load! "contrib/journal")) (if (featurep! +pomodoro) (load! "contrib/pomodoro")) (if (featurep! +present) (load! "contrib/present")) (when (and (featurep 'org) (not doom-reloading-p) (not byte-compile-current-file)) (message "`org' was already loaded by the time lang/org load...") (run-hooks 'org-load-hook)))
  (eval-and-compile (defvar org-directory "~/org/") (defvar org-attach-id-dir ".attach/") (setq org-publish-timestamp-directory (concat doom-cache-dir "org-timestamps/") org-preview-latex-image-directory (concat doom-cache-dir "org-latex/")) (defvar org-modules '(ol-bibtex)) (add-hook 'org-mode-local-vars-hook #'eldoc-mode) (add-hook! 'org-mode-hook #'doom-disable-show-paren-mode-h #'doom-disable-show-trailing-whitespace-h #'+org-enable-auto-reformat-tables-h #'+org-enable-auto-update-cookies-h #'+org-unfold-to-2nd-level-or-point-h) (add-hook! 'org-load-hook #'+org-init-appearance-h #'+org-init-agenda-h #'+org-init-babel-h #'+org-init-babel-lazy-loader-h #'+org-init-capture-defaults-h #'+org-init-capture-frame-h #'+org-init-centralized-attachments-h #'+org-init-centralized-exports-h #'+org-init-custom-links-h #'+org-init-export-h #'+org-init-habit-h #'+org-init-hacks-h #'+org-init-keybinds-h #'+org-init-popup-rules-h #'+org-init-protocol-h #'+org-init-protocol-lazy-loader-h #'+org-init-smartparens-h) (if (featurep! +dragndrop) (load! "contrib/dragndrop")) (if (featurep! +ipython) (load! "contrib/ipython")) (if (featurep! +journal) (load! "contrib/journal")) (if (featurep! +pomodoro) (load! "contrib/pomodoro")) (if (featurep! +present) (load! "contrib/present")) (when (and (featurep 'org) (not doom-reloading-p) (not byte-compile-current-file)) (message "`org' was already loaded by the time lang/org load...") (run-hooks 'org-load-hook)))
  eval-buffer(#<buffer  *load*-909900> nil "/home/chenxianbin/.emacs.d/modules/lang/org/config..." nil t)  ; Reading at buffer position 40118
  load-with-code-conversion("/home/chenxianbin/.emacs.d/modules/lang/org/config..." "/home/chenxianbin/.emacs.d/modules/lang/org/config..." t t)
  load("/home/chenxianbin/.emacs.d/modules/lang/org/config" t nomessage)
  (let (file-name-handler-alist) (load (expand-file-name "config" (plist-get plist :path)) t 'nomessage))
  (condition-case e (let (file-name-handler-alist) (load (expand-file-name "config" (plist-get plist :path)) t 'nomessage)) ((debug doom-error) (signal (car e) (cdr e))) ((debug error) (let* ((source (file-name-sans-extension (expand-file-name "config" (plist-get plist :path)))) (err (cond ((not ...) (cons ... ...)) ((file-in-directory-p source doom-core-dir) (cons ... doom-core-dir)) ((file-in-directory-p source doom-private-dir) (cons ... doom-private-dir)) ((cons ... doom-emacs-dir))))) (signal (car err) (list (file-relative-name (concat source ".el") (cdr err)) e)))))
  (let ((doom--current-module key) (doom--current-flags (plist-get plist :flags))) (condition-case e (let (file-name-handler-alist) (load (expand-file-name "config" (plist-get plist :path)) t 'nomessage)) ((debug doom-error) (signal (car e) (cdr e))) ((debug error) (let* ((source (file-name-sans-extension (expand-file-name "config" ...))) (err (cond (... ...) (... ...) (... ...) (...)))) (signal (car err) (list (file-relative-name (concat source ".el") (cdr err)) e))))))
  (closure ((force-p) t) (key plist) (let ((doom--current-module key) (doom--current-flags (plist-get plist :flags))) (condition-case e (let (file-name-handler-alist) (load (expand-file-name "config" (plist-get plist :path)) t 'nomessage)) ((debug doom-error) (signal (car e) (cdr e))) ((debug error) (let* ((source ...) (err ...)) (signal (car err) (list ... e)))))))((:lang . org) (:flags (+dragndrop +hugo +ipython +pandoc +present +pomodoro +journal) :path "/home/chenxianbin/.emacs.d/modules/lang/org/"))
  maphash((closure ((force-p) t) (key plist) (let ((doom--current-module key) (doom--current-flags (plist-get plist :flags))) (condition-case e (let (file-name-handler-alist) (load (expand-file-name "config" (plist-get plist :path)) t 'nomessage)) ((debug doom-error) (signal (car e) (cdr e))) ((debug error) (let* ((source ...) (err ...)) (signal (car err) (list ... e))))))) #<hash-table equal 47/59 0x158521ab4321>)
  (progn (maphash #'(lambda (key plist) (let ((doom--current-module key) (doom--current-flags (plist-get plist :flags))) (condition-case e (let (file-name-handler-alist) (load ... t ...)) ((debug doom-error) (signal ... ...)) ((debug error) (let* ... ...))))) doom-modules))
  (if doom-modules (progn (maphash #'(lambda (key plist) (let ((doom--current-module key) (doom--current-flags ...)) (condition-case e (let ... ...) (... ...) (... ...)))) doom-modules)))
  (progn (if doom-modules (progn (maphash #'(lambda (key plist) (let (... ...) (condition-case e ... ... ...))) doom-modules))) (run-hook-wrapped 'doom-init-modules-hook #'doom-try-run-hook) (condition-case e (let (file-name-handler-alist) (load (expand-file-name "config" doom-private-dir) t 'nomessage)) ((debug doom-error) (signal (car e) (cdr e))) ((debug error) (let* ((source (file-name-sans-extension (expand-file-name "config" doom-private-dir))) (err (cond (... ...) (... ...) (... ...) (...)))) (signal (car err) (list (file-relative-name (concat source ".el") (cdr err)) e))))))
  (if doom-interactive-mode (progn (if doom-modules (progn (maphash #'(lambda (key plist) (let ... ...)) doom-modules))) (run-hook-wrapped 'doom-init-modules-hook #'doom-try-run-hook) (condition-case e (let (file-name-handler-alist) (load (expand-file-name "config" doom-private-dir) t 'nomessage)) ((debug doom-error) (signal (car e) (cdr e))) ((debug error) (let* ((source (file-name-sans-extension ...)) (err (cond ... ... ... ...))) (signal (car err) (list (file-relative-name ... ...) e)))))))
  (progn (if doom-modules (progn (maphash #'(lambda (key plist) (let (... ...) (condition-case e ... ... ...))) doom-modules))) (run-hook-wrapped 'doom-before-init-modules-hook #'doom-try-run-hook) (if doom-interactive-mode (progn (if doom-modules (progn (maphash #'(lambda ... ...) doom-modules))) (run-hook-wrapped 'doom-init-modules-hook #'doom-try-run-hook) (condition-case e (let (file-name-handler-alist) (load (expand-file-name "config" doom-private-dir) t 'nomessage)) ((debug doom-error) (signal (car e) (cdr e))) ((debug error) (let* ((source ...) (err ...)) (signal (car err) (list ... e))))))))
  (if (condition-case e (let (file-name-handler-alist) (load (expand-file-name "init" doom-private-dir) t 'nomessage)) ((debug doom-error) (signal (car e) (cdr e))) ((debug error) (let* ((source (file-name-sans-extension (expand-file-name "init" doom-private-dir))) (err (cond (... ...) (... ...) (... ...) (...)))) (signal (car err) (list (file-relative-name (concat source ".el") (cdr err)) e))))) (progn (if doom-modules (progn (maphash #'(lambda (key plist) (let ... ...)) doom-modules))) (run-hook-wrapped 'doom-before-init-modules-hook #'doom-try-run-hook) (if doom-interactive-mode (progn (if doom-modules (progn (maphash #'... doom-modules))) (run-hook-wrapped 'doom-init-modules-hook #'doom-try-run-hook) (condition-case e (let (file-name-handler-alist) (load (expand-file-name "config" doom-private-dir) t 'nomessage)) ((debug doom-error) (signal (car e) (cdr e))) ((debug error) (let* (... ...) (signal ... ...))))))))
  (progn (setq doom-init-modules-p t doom-modules nil) (if (condition-case e (let (file-name-handler-alist) (load (expand-file-name "init" doom-private-dir) t 'nomessage)) ((debug doom-error) (signal (car e) (cdr e))) ((debug error) (let* ((source (file-name-sans-extension ...)) (err (cond ... ... ... ...))) (signal (car err) (list (file-relative-name ... ...) e))))) (progn (if doom-modules (progn (maphash #'(lambda ... ...) doom-modules))) (run-hook-wrapped 'doom-before-init-modules-hook #'doom-try-run-hook) (if doom-interactive-mode (progn (if doom-modules (progn (maphash ... doom-modules))) (run-hook-wrapped 'doom-init-modules-hook #'doom-try-run-hook) (condition-case e (let (file-name-handler-alist) (load ... t ...)) ((debug doom-error) (signal ... ...)) ((debug error) (let* ... ...))))))))
  (if (or force-p (not doom-init-modules-p)) (progn (setq doom-init-modules-p t doom-modules nil) (if (condition-case e (let (file-name-handler-alist) (load (expand-file-name "init" doom-private-dir) t 'nomessage)) ((debug doom-error) (signal (car e) (cdr e))) ((debug error) (let* ((source ...) (err ...)) (signal (car err) (list ... e))))) (progn (if doom-modules (progn (maphash #'... doom-modules))) (run-hook-wrapped 'doom-before-init-modules-hook #'doom-try-run-hook) (if doom-interactive-mode (progn (if doom-modules (progn ...)) (run-hook-wrapped 'doom-init-modules-hook #'doom-try-run-hook) (condition-case e (let ... ...) (... ...) (... ...))))))))
  doom-initialize-modules()
  (if noninteractive (doom-initialize-packages) (doom-initialize-core) (doom-initialize-modules) (add-hook 'window-setup-hook #'doom-display-benchmark-h) (add-to-list 'command-switch-alist (cons "--restore" #'doom-restore-session-handler)))
  eval-buffer(#<buffer  *load*> nil "/home/chenxianbin/.emacs.d/init.el" nil t)  ; Reading at buffer position 2899
  load-with-code-conversion("/home/chenxianbin/.emacs.d/init.el" "/home/chenxianbin/.emacs.d/init.el" t t)
  load("/home/chenxianbin/.emacs.d/init" noerror nomessage)
  startup--load-user-init-file(#f(compiled-function () #<bytecode 0x15852182e9f5>) #f(compiled-function () #<bytecode 0x15852182ea0d>) t)
  command-line()
  normal-top-level()

</pre></details>

**System information**
<details><pre>
((emacs
  (version . "27.0.50")
  (features . "XPM JPEG TIFF GIF PNG RSVG CAIRO IMAGEMAGICK SOUND GPM DBUS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER LCMS2 GMP")
  (build . "Nov 28, 2019")
  (buildopts "--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --mandir=/usr/share/man --with-gameuser=:games --with-sound=alsa --with-modules --without-gconf --without-gsettings --enable-link-time-optimization --with-x-toolkit=gtk3 --without-xaw3d --without-m17n-flt --with-imagemagick --with-cairo --with-xwidgets --without-compress-install 'CFLAGS=-march=ivybridge -O2 -pipe -fno-plt -flto -fuse-linker-plugin -fuse-ld=gold' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now")
  (windowsys . batch)
  (daemonp))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop 827e4a2a5 2019-11-27 22:13:03 -0500"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/usr/bin/zsh")
  (uname . "Linux 5.3.13-arch1-1 #1 SMP PREEMPT Sun, 24 Nov 2019 10:15:50 +0000 x86_64")
  (path "~/.gem/ruby/2.6.0/bin" "~/.go/bin" "~/.cargo/bin" "~/.jenv/shims" "~/.jenv/bin" "~/.emacs.d/bin" "~/.local/bin" "~/.nvm/versions/node/v13.1.0/bin" "/usr/local/bin" "/usr/local/sbin" "/usr/bin" "/usr/lib/jvm/default/bin" "/usr/bin/site_perl" "/usr/bin/vendor_perl" "/usr/bin/core_perl" "~/.antigen/bundles/robbyrussell/oh-my-zsh/lib" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/git" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/gitfast" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/git-remote-branch" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/colored-man-pages" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/history" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/z" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/extract" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/encode64" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/web-search" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/urltools" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/tmux" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/docker" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/docker-compose" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/archlinux" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/cargo" "~/.antigen/bundles/djui/alias-tips" "~/.antigen/bundles/zdharma/fast-syntax-highlighting" "~/.antigen/bundles/zsh-users/zsh-autosuggestions" "~/.antigen/bundles/hlissner/zsh-autopair" "~/.antigen/bundles/romkatv/powerlevel10k" "/usr/lib/emacs/27.0.50/x86_64-pc-linux-gnu"))
 (config
  (envfile)
  (elc-files . 0)
  (modules :input chinese :completion company (ivy +prescient +fuzzy +childframe) :ui doom doom-quit hl-todo hydra modeline nav-flash ophints (popup +all +defaults) treemacs vc-gutter (window-select +numbers) workspaces centered-cursor :editor file-templates lispy multiple-cursors rotate-text snippets :emacs (dired +ranger) electric (ibuffer +icons) vc :term eshell :tools docker editorconfig (eval +overlay) (flycheck +childframe) lookup lsp magit (youdao +childframe) :lang data emacs-lisp (go +lsp) (java +lsp) (javascript +lsp) markdown (org +dragndrop +hugo +ipython +pandoc +present +pomodoro +journal) plantuml rest (scala +lsp) sh (web +lsp) :config (default +bindings +smartparens))
  (packages "(fcitx :disable t)" "(pangu-spacing :disable t)" "(tide :disable t)" "(liberime-config :recipe (:host github :repo \"xhcoding/liberime\" :files (\"liberime-config.el\" \"src\" \"CMakeLists.txt\" \"Makefile\")))" "(company-english-helper :recipe (:host github :repo \"cxb811201/company-english-helper\"))" "(insert-translated-name :recipe (:host github :repo \"manateelazycat/insert-translated-name\"))" cal-china-x exec-path-from-shell hungry-delete "(go-impl :recipe (:host github :repo \"cxb811201/emacs-go-impl\"))" go-fill-struct sqlup-mode "(lsp-ivy :recipe (:host github :repo \"emacs-lsp/lsp-ivy\"))" dap-mode)
  (elpa "n/a")))
</pre></details>

**Comment by hlissner** [comment]
As of 9db8904 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by harritaylor** [comment]
@hlissner I'm getting sort of the same error but not caused by the same issue. Unsure if I should open a new bug report. 

When I first open Emacs and hit `<SPC-X, j>` to capture to journal I keep getting the error `org-find-olp: Heading not found on level 1: Inbox`. This error goes away if I open my `journal.org` file or if I open my org directory in dired (doesn't matter if the buffer is killed after opening). 

I've done the ususal troubleshooting steps but can't seem to figure out what's causing the issue.
