### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by octothorpeSpeed** [hlissner/doom-emacs#212]
Hello. 
I was curious if there is any easy way to use Python 3 in place of Python 2.
Thank you

**Comment by hlissner** [comment]
This strongly depends on how you manage python versions on your system. I use [pyenv](https://github.com/pyenv/pyenv), which lets me set the default python versions system-wide, the current shell or for specific directories, and Doom is configured to pick this up. So if you have python3 enabled, syntax checking, code evaluation, the repl, etc. should all be using python 3. You'd also be able to see it in the mode-line: 

![python version in mode-line](https://raw.githubusercontent.com/hlissner/doom-emacs/screenshots/ml-version.png)

If pyenv isn't for you, this should be enough to get everything working:

```emacs-lisp
(setq python-shell-interpreter "python3"
      flycheck-python-pycompile-executable "python3")
```

Let me know if that works for you.

**Comment by jcrotts** [comment]
[Conda](https://conda.io/docs/) is also a great way to manage python virtual environments!

**Comment by tiega** [comment]
> This strongly depends on how you manage python versions on your system. I use [pyenv](https://github.com/pyenv/pyenv), which lets me set the default python versions system-wide, for the current shell, or for specific directories, and Doom is configured to pick this up. So if you have python3 enabled, syntax checking, code evaluation, the repl, etc. should all be using python 3. You'd also be able to see it in the mode-line:
> 
> ![python version in mode-line](https://raw.githubusercontent.com/hlissner/doom-emacs/screenshots/ml-version.png)
> 
> If pyenv isn't for you, this should be enough to get everything working (assuming your python executable is named "python3"):
> 
> ```emacs-lisp
> (setq python-shell-interpreter "python3"
>       flycheck-python-pycompile-executable "python3")
> ```
> 
> Let me know if that works for you.

Hi hlissner, the command 
```
(setq python-shell-interpreter "python3"
      flycheck-python-pycompile-executable "python3")
```
did not work for me and my doom emacs still detects python2.7. I don't use pyenv and I just run `python3` to launch python3. What can I do to make doom show python3?

**Comment by hlissner** [comment]
@tiega Can you be more specific? Where does it "show python3"? If in the modeline, then add this to your config:

```elisp
(setq doom-modeline-env-python-executable "python3")
```

**Comment by tiega** [comment]
@hlissner Yes in my modeline it still shows python 2.7.17 even after adding the following to my config:

```elisp
(setq python-shell-interpreter "python3"
      flycheck-python-pycompile-executable "python3")
(setq doom-modeline-env-python-executable "python3")
```
Anything else I could try? Thanks!

**Comment by hlissner** [comment]
This alone worked for me.

```elisp
(after! python
  (setq python-shell-interpreter "python"))
```
