### ISSUE TITLE
[BUG] Error in post-command-hook (org-add-log-note): (wrong-number-of-arguments quote 3)

### ISSUE THREAD

**Issue by flyingns** [hlissner/doom-emacs#2120]
**Describe the issue**
In *Org Agenda*, When I press `t d` to switch the TODO state, I get this error.

**Comment by hlissner** [comment]
I can't reproduce it. [Please include a backtrace](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#how-to-extract-a-backtrace-from-an-error).

**Comment by flyingns** [comment]
When I updated to commit `50cab52`, there was no longer this error.
