### ISSUE TITLE
[BUG] Intero available for Haskell, but its repo states that it is deprecated.

### ISSUE THREAD

**Issue by judemille** [hlissner/doom-emacs#2121]
**Describe the issue**
Intero is set as the default engine for Haskell, but its repository reports that it is deprecated. The default should be switched. My vote is for switching to LSP as default, but I know that isn't common in this repo. Whatever the case, Intero should be phased out of doom-emacs.

**Comment by hlissner** [comment]
I wasn't aware that it is deprecated. I'll look into phasing it out of Doom.

**Comment by kenranunderscore** [comment]
Knowing the hassle lots of people have with setting up/using HIE (if that hasn't changed recently at least), I am happy to see you go with dante as a default - for the time being.

**Comment by juliandemille** [comment]
I'm keeping the issue open until Intero is fully removed from Doom, just so nobody forgets about this.

**Comment by hlissner** [comment]
As of 1cb753c, intero is no longer in Doom or a part of the haskell module. Thanks for bringing it to my attention!
