### ISSUE TITLE
org-capture bindings/commands not working

### ISSUE THREAD

**Issue by orther** [hlissner/doom-emacs#213]
I believe the bindings and commands for org-capture in your private hlissner module are broken.  The functions mapped to bindings/commands are `+org:capture` and `+org/capture` but those functions aren't defined. I do see the following functions available that seem to work: `org-capture`, `+org-capture/dwim`, `+org-capture:dwim`.

### +commands.el
[private/hlissner/+commands.el](https://github.com/hlissner/doom-emacs/blob/4454226a424184086df5020c906af7936f161689/modules/private/hlissner/%2Bcommands.el#L106) is referring to `+org:capture`

```elisp
(ex! "org"         #'+org:capture)
```

### +bindings.el
[private/hlissner/+bindings.el](https://github.com/hlissner/doom-emacs/blob/9e13ce0536c2f4dbc449b9ee5907b0ddc5c093e9/modules/private/hlissner/%2Bbindings.el#L225) is referring to `+org/capture` in two places

```elisp
;; --- <leader> -------------------------------------
(:leader
  :desc "Ex command"  :nv ";"   #'evil-ex
  :desc "M-x"         :nv ":"   #'execute-extended-command
  :desc "Pop up scratch buffer"   :nv "x"  #'doom/scratch-buffer
  :desc "Org Capture"             :nv "X"  #'+org/capture ; <---------------- HERE

;; ... skip ...

(:desc "notes" :prefix "n"  
  :desc "Find file in notes"    :n "n" #'+hlissner/find-in-notes
  :desc "Browse notes"          :n "N" #'+hlissner/browse-notes
  :desc "Org capture"           :n "x" #'+org/capture ; <-------------------- HERE
```

## Solution?
I'm not sure if I am doing something to cause those functions not to load but I can't seem to find them defined anywhere in this repo so I'm guessing `+bindings.el` and `+commands.el` are just using old or wrong function names that need to be updated. It seems calling `org-capture` would work for bindings and commands but I'm not sure.

**Comment by hlissner** [comment]
You are absolutely right, quite a few bindings were forgotten after I split the lang/org module into a bunch of org/* modules. I'll fix this soon.

**Comment by hlissner** [comment]
THis is now fixed in `develop`. I'll close this once it gets merged into master.

**Comment by orther** [comment]
👍 thanks
