### ISSUE TITLE
[BUG] rustic-mode reverts to rust-mode when `rustic-format-on-save` is set

### ISSUE THREAD

**Issue by jiahaog** [hlissner/doom-emacs#2132]
I followed #2045 and set the following line in my config:

```
(after! rustic
  (setq rustic-format-on-save t))
```

My config is empty apart from this. (except for :lang rust uncommented in the default config.el)

### Expected behavior:

Format on save works after modifying a file. Stay in `rustic-mode` before and after saving the file.

I checked the editor mode by running `M: major-mode`.

(I noticed that code completion does not work well for `rust-mode` so I'm assuming that `rust-mode` isn't supported very well and I'm supposed to be in `rustic-mode`)

### Actual Behavior

The file is formatted the first time it is saved. Subsequently it does not work. I also noticed that the mode is changed to `rust-mode` instead of `rustic-mode`.

### Steps to reproduce

1. Create a new rust project (`cargo new test-project`)
1. Open one of the rust files
1. Observe that the mode is `rustic-mode`
1. Add some whitespace and save
1. Observe that the file has been formatted; the mode has changed to `rust-mode`
1. Add some whitespace and save again
1. Observe that this time the file is not formatted

Another thing I tried to do was to `s/rust-mode/rustic-mode` in the doom emacs repo (before running `doom refresh`), but that didn't seem to work.

I'm not sure if this is a doom-emacs issue or a rustic issue, and it's actually my first time trying to use emacs. Help would be appreciated!

### System information

<details>

```
emacs   version    26.3
        features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS LIBSYSTEMD LCMS2
        build      Sep 23, 2019
        buildopts  (--build x86_64-linux-gnu --prefix=/usr --sharedstatedir=/var/lib --libexecdir=/usr/lib --localstatedir=/var/lib --infodir=/usr/share/info --mandir=/usr/share/man --enable-libsystemd --with-pop=yes --enable-locallisppath=/etc/emacs:/usr/local/share/emacs/26.3/site-lisp:/usr/local/share/emacs/site-lisp:/usr/share/emacs/26.3/site-lisp:/usr/share/emacs/site-lisp --with-sound=alsa --without-gconf --with-mailutils --build x86_64-linux-gnu --prefix=/usr --sharedstatedir=/var/lib --libexecdir=/usr/lib --localstatedir=/var/lib --infodir=/usr/share/info --mandir=/usr/share/man --enable-libsystemd --with-pop=yes --enable-locallisppath=/etc/emacs:/usr/local/share/emacs/26.3/site-lisp:/usr/local/share/emacs/site-lisp:/usr/share/emacs/26.3/site-lisp:/usr/share/emacs/site-lisp --with-sound=alsa --without-gconf --with-mailutils --with-x=yes --with-x-toolkit=gtk3 --with-toolkit-scroll-bars 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/emacs-wvqver/emacs-26.3+1=. -fstack-protector-strong -Wformat -Werror=format-security -Wall' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro')
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop, origin/develop, origin/HEAD 5baa1eb63 2019-11-30 14:45:41 -0500
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/bash
        uname      Linux 5.3.0-23-generic #25-Ubuntu SMP Tue Nov 12 09:22:33 UTC 2019 x86_64
        path       (~/.emacs.d/bin/ ~/.cargo/bin/ ~/.local/bin/ /usr/local/sbin/ /usr/local/bin/ /usr/sbin/ /usr/bin/ /sbin/ /bin/ /usr/games/ /usr/local/games/ /snap/bin/ ~/.cargo/bin/ ~/.fzf/bin/ /usr/lib/emacs/26.3/x86_64-linux-gnu/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold multiple-cursors rotate-text snippets :emacs dired electric ibuffer vc :tools (eval +overlay) flycheck (lookup +docsets) magit :lang data emacs-lisp markdown (org +dragndrop +ipython +pandoc +present) python rust sh :config (default +bindings +smartparens))
        packages   (n/a)
        elpa       (n/a)
```
</details>

**Comment by hlissner** [comment]
Does adding this to your private config.el resolve the issue?

```elisp
(after! rust-mode
  (delq! '("\\.rs\\'" . rust-mode) auto-mode-alist #'member))
```

**Comment by jiahaog** [comment]
Nope, that doesn't seem to work as well. I tried playing around with the regex (?) but it doesn't seem to help too :(

**Comment by hlissner** [comment]
Then how about:

```elisp
(after! rust-mode
  (setq auto-mode-alist (rassq-delete-all 'rust-mode auto-mode-alist)))
```

**Comment by jiahaog** [comment]
Great it worked, thanks a lot! Do you think this is a problem that only I'm having, or is it more widespread?

**Comment by hlissner** [comment]
It's not just you. If you aren't using the `+lsp` feature in the `:lang rust` module, then the module installs the `racer.el` package, which pulls in `rust-mode` along with it. When `rust-mode` loads, it adds an entry to `auto-mode-alist` to associate *.rs files with it (essentially shoving `rustic-mode` out of the way).

When the file is later formatted by rustfmt, Emacs detects a change the file has changed and reverts the buffer, "redetecting" the major mode and invoking `rust-mode` instead.

I'll merge the fix into the `:lang rust` module shortly.
