### ISSUE TITLE
How to create files using the file-templates module?

### ISSUE THREAD

**Issue by huos3203** [hlissner/doom-emacs#2134]
`file-templates` directory structure
```
.
├── __contact.org

├── __doom-readme

├── __invoice.org

└── __project.org
```
### configure
Enable `file-templates` support in`.Init.el` 
2. Set template directory
```
(setq +file-templates-dir "~/.doom.d/templates"
   max-specpdl-size 10000)
```
Create a new test.org validation configuration, and the template will be inserted automatically
```
#+TITLE: test
```
### problem
How to create a new file for the`__project.org` template?

**Comment by hlissner** [comment]
1. The file templates directory is structured like yasnippet snippets:

   ```
   {+file-templates-dir}/major-mode/{snippet-name}
   ```

   So your org templates need to be in `~/.doom.d/templates/org-mode/`.

2. You do not need to change `+file-templates-dir` (unless you want to disable all built-in file-templates). Instead, add your file templates to `~/.doom.d/snippets/{major-mode}/`.

3. You must use `set-file-template! PREDICATE &key WHEN TRIGGER MODE PROJECT IGNORE` to register new file templates. Here are some examples:

   ```elisp
   (set-file-template! "/main\\.c\\(?:c\\|pp\\)$" :trigger "__main.cpp" :mode 'c++-mode)
   (set-file-template! "/project\\.org$" :trigger "__project.org" :mode 'org-mode)
   ```

   Check out `SPC h f set-file-template\!` for documentation.

Hope that helps!

**Comment by huos3203** [comment]
> 1. The file templates directory is structured like yasnippet snippets:
>    ```
>    {+file-templates-dir}/major-mode/{snippet-name}
>    ```
>    
>    
>    So your org templates need to be in `~/.doom.d/templates/org-mode/`.
> 2. You do not need to change `+file-templates-dir` (unless you want to disable all built-in file-templates). Instead, add your file templates to `~/.doom.d/snippets/{major-mode}/`.
> 3. You must use `set-file-template! PREDICATE &key WHEN TRIGGER MODE PROJECT IGNORE` to register new file templates. Here are some examples:
>    ```emacs-lisp
>    (set-file-template! "/main\\.c\\(?:c\\|pp\\)$" :trigger "__main.cpp" :mode 'c++-mode)
>    (set-file-template! "/project\\.org$" :trigger "__project.org" :mode 'org-mode)
>    ```
>    
>    
>    Check out `SPC h f set-file-template\!` for documentation.
> 
> Hope that helps!

yes，`__project.org` is an existing template of file template. How can I create an empty file on Emacs and automatically fill in yasnippets of`__project.org`?

**Comment by hlissner** [comment]
The answer was in my last post. I'll reword it in case it wasn't clear:

1. Add this to ~/.doom.d/config.el:

   ```lisp
   (set-file-template! "/project\\.org$" :trigger "__project.org" :mode 'org-mode)
   ```

2. Put your file template in `~/.doom.d/snippets/org-mode/__project.org`.

3. Then `SPC f f path/to/nonexistent/project.org` will open a buffer with the __project.org template.

**Comment by huos3203** [comment]
> The answer was in my last post. I'll reword it in case it wasn't clear:
> 
> 1. Add this to ~/.doom.d/config.el:
>    ```lisp
>    (set-file-template! "/project\\.org$" :trigger "__project.org" :mode 'org-mode)
>    ```
> 2. Put your file template in `~/.doom.d/snippets/org-mode/__project.org`.
> 3. Do not change `+file-template-dir`.
> 4. Then `SPC f f path/to/nonexistent/project.org` will open a buffer with the __project.org template.

Thank you. That's fine.
I thought that a large number of built-in `file-templates` could be used directly without additional configuration. In fact, I also needed `set-file-template!` To set trigger configuration.

**Comment by hlissner** [comment]
> I thought that a large number of built-in file-templates could be used directly without additional configuration. 

No extra configuration is needed to use the built-in file-templates. You'll find all the default file-template rules here: https://github.com/hlissner/doom-emacs/blob/develop/modules/editor/file-templates/config.el#L11-L106.

However, if you change `+file-templates-dir`, then yasnippet will be unable to find them.

**Comment by huos3203** [comment]
YES
I found that only `__doom-readme` and`__`are set in the default configuration,and other built-in templates (`__invoice.org`\`__project.org`) require the user to use the `set-file-template!` Configuration.
```
 ;; Org
    ("/README\\.org$"
     :when +file-templates-in-emacs-dirs-p
     :trigger "__doom-readme"
     :mode org-mode)
    ("\\.org$" :trigger "__" :mode org-mode)
```

**Comment by laurentHYZ** [comment]
Hello Henrik, 
I am trying to understand file-templates and I am facing some challenges.
- My doom config are within .config/doom/
- I created the folder .config/doom/templates, then the subfolder /org-mode, hoping to store file templates there (question#1: is it normal that the folder has to be created manually?, I thought it should have been automatic)
-I went into my doom config.el and added `(set-file-template! "\\.org$" :trigger "__" :mode 'org-mode)
` (question#2: I tried `(set-file-template! "/project\\.org$" :trigger "__" :mode 'org-mode)
` but then the templates I had chosen would not be displayed, only the default template "__" would. Could you explain what the `/project` stands for here?

Most importantly though, only the templates in `.emacs.d/modules/editor/file-templates/templates/org-mode` are displayed using the code above. I suspect I did not create my templates/org-mode at the appropriate location, what did I miss? thanks!
-

**Comment by clinaresl** [comment]
Hi there Laurent,

I managed to create my own templates following Henrik's hints and as far as I can tell, it seems to me that templates should be indeed stored under `.doom.d/snippets` as explained above but it seems you are under a different directory

**Comment by hlissner** [comment]
> question#1: is it normal that the folder has to be created manually?, I thought it should have been automatic

Yes.

> `.config/doom/templates`

Put them in `.config/doom/snippets/`. Anywhere else and they won't work.

-----

If you'd like to follow up, please bring them [to our Discord](https://discord.gg/qvGgnVx), as our issue tracker (much less closed issues) are not the place for these questions.
