### ISSUE TITLE
[HOWTO] activate neotree keybinding

### ISSUE THREAD

**Issue by verajosemanuel** [hlissner/doom-emacs#2138]
Followed instructions here for activating Neotree

[https://github.com/hlissner/doom-emacs/issues/2007](https://github.com/hlissner/doom-emacs/issues/2007)

After refresh and restart, any keybinding is not working. A message is shown:

`<any key> is not defined`

System is ubuntu Eoan

**Comment by hlissner** [comment]
Duplicate of #2135.
