### ISSUE TITLE
[REQUEST] Jump to buffer with e.g. `SPC 1`

### ISSUE THREAD

**Issue by barischrooneyj** [hlissner/doom-emacs#2142]
**Describe the feature**
- What is your request?
Jump to buffer as in spacemacs e.g. `SPC 1`, `SPC 2` etc.
- How is it helpful?
When many buffers are open and you see somewhere in another open buffer that you want to navigate to it would reduce time, perhaps there is another way I am unaware of. In the screenshot below if I am in the bottom right and want to navigate to the top left, two key presses `SPC 1` would be very fast.
- How is it used?
Powerline has open buffer number. Press `SPC num` where `num` is the number in the powerline.

![Screenshot 2019-12-03 at 11 37 06](https://user-images.githubusercontent.com/6631452/70044055-de429b80-15c1-11ea-9bb8-36c86c307bd7.png)

**Comment by hlissner** [comment]
Enable the `:ui (window +numbers)` module and flag in your `doom!` block in `~/.doom.d/init.el`. Then each window will be numbered and `C-w [1-9]` or `SPC w [1-9]` will jump to them.

Hope that helps!

**Comment by barischrooneyj** [comment]
Thank you! Very helpful
