### ISSUE TITLE
[BUG] Unable to open Treemacs

### ISSUE THREAD

**Issue by alotofnoodles** [hlissner/doom-emacs#2147]
`SPC o p` returns error `Symbol’s value as variable is void: treemacs--buffer-access`.

`doom compile` returns the same error. 

<details><pre>
Debugger entered--Lisp error: (void-variable treemacs--buffer-access)
  treemacs--setup-fringe-indicator-mode()
  treemacs-fringe-indicator-mode()
  byte-code("\301\302N\204\f\0\303\301\302\304#\210\305\306\307\310\300!\205\026\0\010\307\211%\210\311\312!\204#\0\306 \210\313\314!\207" [treemacs-fringe-indicator-mode-map treemacs-fringe-indicator-mode-hook variable-documentation put "Hook run after entering or leaving `treemacs-fringe-indicator-mode'.\nNo problems result if this variable is not bound.\n`add-hook' automatically binds it.  (This is true for all hook variables.)" add-minor-mode treemacs-fringe-indicator-mode nil boundp featurep treemacs provide treemacs-fringe-indicator] 6)
  require(treemacs-fringe-indicator)
  byte-code("\300\301!\210\300\302!\210\300\303!\210\300\304!\210\300\305!\210\300\306!\210\300\307!\210\300\310!\210\300\311!\210\300\312!\210\300\313!\207" [require image pulse hl-line treemacs-core-utils treemacs-scope treemacs-themes treemacs-icons treemacs-customization treemacs-fringe-indicator inline treemacs-macros] 2)
  require(treemacs-visuals)
  byte-code("\300\301!\210\300\302!\210\300\303!\210\300\304!\210\300\305!\210\300\306!\210\300\307!\210\300\310!\210\300\311!\210\300\312!\210\300\313!\210\300\314!\210\300\315!\210\300\316!\210\300\317!\210\300\320!\210\300\321!\210\300\322!\210\300\323!\210\300\324!\210\300\325!\210\300\326!\210\300\327!\210\300\330!\210\300\331!\210\300\332!\207" [require dash s f treemacs-customization treemacs-themes treemacs-icons treemacs-faces treemacs-visuals treemacs-rendering treemacs-core-utils treemacs-scope treemacs-follow-mode treemacs-filewatch-mode treemacs-mode treemacs-interface treemacs-mouse-interface treemacs-persistence treemacs-tags treemacs-tag-follow-mode treemacs-async treemacs-compatibility treemacs-workspaces treemacs-fringe-indicator treemacs-extensions cl-lib treemacs-macros] 2)
  require(treemacs)
  +treemacs/toggle()
  funcall-interactively(+treemacs/toggle)
  call-interactively(+treemacs/toggle nil nil)
  command-execute(+treemacs/toggle)
</pre></details>

**System information**
<details>

```
emacs   version    26.2
        features   NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS
        build      Apr 13, 2019
        buildopts  (--with-ns '--enable-locallisppath=/Library/Application Support/Emacs/${version}/site-lisp:/Library/Application Support/Emacs/site-lisp' --with-modules)
        windowsys  ns
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop 50cab5276 2019-11-28 22:04:34 -0500
system  type       darwin
        config     x86_64-apple-darwin18.2.0
        shell      /bin/zsh
        uname      Darwin 19.0.0 Darwin Kernel Version 19.0.0: Wed Sep 25 20:18:50 PDT 2019; root:xnu-6153.11.26~2/RELEASE_X86_64 x86_64
        path       (~/.emacs.d/bin/ ~/.bin/ .git/safe/../../bin/ ~/.asdf/shims/ /usr/local/opt/asdf/bin/ /usr/local/sbin/ /usr/local/bin/ /usr/bin/ /bin/ /usr/sbin/ /sbin/ /Library/Apple/usr/bin/ /Library/Apple/bin/ /opt/X11/bin/ ~/.fzf/bin/ /Applications/Emacs.app/Contents/MacOS/libexec/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold multiple-cursors rotate-text snippets :emacs dired electric ibuffer vc :term shell vterm :tools direnv docker editorconfig (eval +overlay) flycheck gist (lookup +docsets) lsp macos magit make pdf :lang data elixir emacs-lisp go javascript markdown (org +dragndrop +hugo +ipython +pandoc +pomodoro +present) plantuml rest ruby scala sh web :config (default +bindings +smartparens))
        packages   (n/a)
        elpa       (n/a)
```
</details>

**Comment by hlissner** [comment]
It sounds like a byte-code issue. Run `doom build` to rebuild (byte-compile + assemble) all packages. `doom compile` is not the correct command to use here; it _only_ compiles Doom and your private config, not its packages. If that doesn't work, update your packages by running `doom update`.

**Comment by Alexander-Miller** [comment]
Definitely a byte code thing: https://github.com/Alexander-Miller/treemacs/issues/576

**Comment by alotofnoodles** [comment]
`doom build` works! Thanks
