### ISSUE TITLE
[HOWTO] open inside terminal instead new window

### ISSUE THREAD

**Issue by verajosemanuel** [hlissner/doom-emacs#2148]
I want to edit a file inside a tmux split but the usual command

emacs -nw 

Keeps opening a new window.
I'm using chemacs with doom as default profile

**Comment by hlissner** [comment]
Please include your `M-x doom/info`. The emacs config cannot change whether emacs is opened in a GUI or TTY frame. Something else on your system is the issue. Two likely possiiblities are:

1. You've aliased `emacs` to `emacsclient -c` in your shell config,
2. You are using an emacs binary provided by the Emacs cask or Emacs.app bundle on MacOS. If I remember correctly, these are wrappers around emacs and you cannot open emacs in the terminal with them,

**Comment by verajosemanuel** [comment]
Hi

No mac. 
I'm on ubuntu eoan with chemacs script to keep spacemacs and doom separated

my alias:

`alias doom="nohup emacs --with=profile doom &"`

 
```
<details>

emacs   version    26.3
        features   XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK2 X11 XDBE XIM THREADS
        build      oct 14, 2019
        buildopts  ()
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop, origin/develop, origin/HEAD 90c0dd6b3 2019-12-01 22:46:45 -0500
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /usr/bin/zsh
        uname      Linux 5.3.0-24-generic #26-Ubuntu SMP Thu Nov 14 01:33:18 UTC 2019 x86_64
        path       (~/.local/bin/ ~/bin/ /usr/local/mysql/bin/ /usr/local/sbin/ /usr/local/bin/ /usr/sbin/ /usr/bin/ /sbin/ /bin/ /usr/games/ /usr/local/games/ /snap/bin/ ~/.fzf/bin/ /usr/local/libexec/emacs/26.3/x86_64-pc-linux-gnu/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company helm ivy :ui neotree doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) pretty-code treemacs unicode vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold multiple-cursors rotate-text snippets :emacs dired electric ibuffer vc :tools (eval +overlay) flycheck (lookup +docsets) magit pass pdf :lang data emacs-lisp markdown (org +dragndrop +ipython +pandoc +present) python sh :app calendar (rss +org) write :config (default +bindings +smartparens))
        packages   (n/a)
        elpa       (n/a)
</details>
```

**Comment by verajosemanuel** [comment]
Tried a new cleaner alias. no success so far. Still opening a new window

`alias doom='emacs --with-profile doom'`

**Comment by d1egoaz** [comment]
Same issue for me, however I'm using https://github.com/railwaycat/homebrew-emacsmacport

and as @hlissner pointed out it might have issues.

That said, using `emacs -nw` opens a terminal based emacs frame
