### ISSUE TITLE
C-x b : Symbol’s function definition is void: +ivy-buffer-transformer

### ISSUE THREAD

**Issue by amoriello** [hlissner/doom-emacs#215]
Hi,

After make update,

I can no longer change buffer with C-x b.
got `Symbol’s function definition is void: +ivy-buffer-transformer`
This might be because of recent regression.

**Comment by amoriello** [comment]
Btw, I'm on master.

I tried develop, but got the same issue.

**Comment by hlissner** [comment]
I believe this was fixed in master as of https://github.com/hlissner/doom-emacs/commit/c7957c93214df5ea6a590fdfbe01a17762f33582. Have you run `make` or `make autoloads` recently?

**Comment by amoriello** [comment]
That was it! Forgot this step.

Thanks.
