### ISSUE TITLE
[REQUEST] Rust compile command

### ISSUE THREAD

**Issue by rakanalh** [hlissner/doom-emacs#2152]
**Describe the feature**

When using doom-emacs to edit rust files, pressing SPC c c (compile), the user would be prompted with the compile command. I think it would be great if the default for that would be the same as SPC m b b (which is bound to `rustic-cargo-build`).

**System information**
<details><pre>
((emacs
  (version . "26.3")
  (features . "XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2")
  (build . "Aug 29, 2019")
  (buildopts "--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-modules 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD a8fd59a05 2019-12-03 22:56:33 -0500"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/bin/zsh")
  (uname . "Linux 5.3.12-arch1-1 #1 SMP PREEMPT Wed, 20 Nov 2019 19:45:16 +0000 x86_64")
  (path "~/.pyenv/plugins/pyenv-virtualenv/shims" "~/.pyenv/shims" "~/.pyenv/bin" "/usr/local/bin" "/usr/bin" "/bin" "/usr/sbin" "/sbin" "/usr/local/git/bin" "/usr/local/go/bin" "/opt/sm/bin" "/opt/sm/pkg/active/bin" "/opt/sm/pkg/active/sbin" "platform-tools/" "/bin" "~/Code/Go/bin" "~/.bin;~/.cargo/bin" "/usr/lib/emacs/26.3/x86_64-pc-linux-gnu"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard doom-quit hl-todo hydra modeline nav-flash ophints (popup +all +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold (format +onsave) multiple-cursors rotate-text snippets :emacs dired electric ibuffer vc :tools editorconfig (eval +overlay) flycheck (lookup +docsets) magit :lang data emacs-lisp go javascript lua markdown (org +dragndrop +ipython +pandoc +present) (python +pyenv) rust sh solidity :config (default +bindings +smartparens))
  (packages "n/a")
  (elpa "n/a")))
</pre></details>

**Comment by hlissner** [comment]
Why not use `SPC m b b` then?

Alternatively, does this work for you?

```elisp
(setq-hook! 'rustic-mode-hook compile-command "cargo build")
```

**Comment by rakanalh** [comment]
Hey @hlissner,

SPC c c is shorter :stuck_out_tongue:

On a serious note, i think the default makes sense. Otherwise, i'd be happy to customize it in my own configs.

```
(setq-hook! 'rustic-mode-hook compile-command "cargo build")
```
did not do the trick unfortunately. I added it to my config.el and executed `doom refresh`.

**Comment by rakanalh** [comment]
More details:

i described `compile-command` and `rustic-compile-command` and seems like the value is set correctly. However, `SPC c c` still prompts for the compile command.

**Comment by hlissner** [comment]
Then try:

```elisp
(setq-hook! 'rustic-mode-hook 
  counsel-compile-history '("cargo build"))
```

Unfortunately, do to how many tools are involved (i.e. `compile` or `counsel-compile` or all of projectile's build/compile commands, etc), it isn't practical to set defaults for every single one of them for individual languages at the moment. I'm looking into a unified "compile" commands that would make this sort of thing easier, but my todo list is already miles long -- don't hold your breath.

**Comment by rakanalh** [comment]
Fair enough... thanks for your help.
