### ISSUE TITLE
[BUG] doom/reload error

### ISSUE THREAD

**Issue by rakanalh** [hlissner/doom-emacs#2153]
**Describe the issue**
- What did you expect to happen?
When executing `doon/reload`, i expect that my updated configs are reloaded.
- What actually happened?
```
-*- mode: compilation; default-directory: "~/dotfiles/.doom.d/" -*-
Compilation started at Thu Dec  5 00:34:03

/home/rakan/.emacs.d//bin/doom refresh -f
x Unrecognized switch "-f"

See 'doom help -f' for documentation on this command.

Compilation finished at Thu Dec  5 00:34:03
```

**Steps to reproduce**
1. `SPC :`
2. `doom/reload`

**System information**
<details><pre>
((emacs
  (version . "26.3")
  (features . "XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2")
  (build . "Aug 29, 2019")
  (buildopts "--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-modules 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD a8fd59a05 2019-12-03 22:56:33 -0500"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/bin/zsh")
  (uname . "Linux 5.3.12-arch1-1 #1 SMP PREEMPT Wed, 20 Nov 2019 19:45:16 +0000 x86_64")
  (path "~/.pyenv/plugins/pyenv-virtualenv/shims" "~/.pyenv/shims" "~/.pyenv/bin" "/usr/local/bin" "/usr/bin" "/bin" "/usr/sbin" "/sbin" "/usr/local/git/bin" "/usr/local/go/bin" "/opt/sm/bin" "/opt/sm/pkg/active/bin" "/opt/sm/pkg/active/sbin" "platform-tools/" "/bin" "~/Code/Go/bin" "~/.bin;~/.cargo/bin" "/usr/lib/emacs/26.3/x86_64-pc-linux-gnu"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard doom-quit hl-todo hydra modeline nav-flash ophints (popup +all +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold (format +onsave) multiple-cursors rotate-text snippets :emacs dired electric ibuffer vc :tools editorconfig (eval +overlay) flycheck (lookup +docsets) magit :lang data emacs-lisp go javascript lua markdown (org +dragndrop +ipython +pandoc +present) (python +pyenv) rust sh solidity :config (default +bindings +smartparens))
  (packages "n/a")
  (elpa "n/a")))</pre></details>

**Comment by hlissner** [comment]
As of 4ced3d3 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
