### ISSUE TITLE
[BUG] Tab completion does not work in python org src

### ISSUE THREAD

**Issue by alinbxSorcerer** [hlissner/doom-emacs#2154]
I set up a python org src 

    #+BEGIN_SRC python :results output
    import sys
    
    print(sys.version)
    print(sys.version_info)
    
    #+END_SRC
    
    #+RESULTS:
    : 3.7.4 (default, Aug 13 2019, 20:35:49) 
    : [GCC 7.3.0]
    : sys.version_info(major=3, minor=7, micro=4, releaselevel='final', serial=0)

After strike `C-'` to invoke a code buffer, the tab completion refused to work as intented.  

Even though activated the python-mode and lsp-mode

[![enter image description here][1]][1]

ob-ipython did not work as well.

    #+begin_src emacs-lisp :tangle yes :results output
    (print (emacs-version))
    (print (org-version))
    #+end_src
    
    #+RESULTS:
    : 
    : "GNU Emacs 26.3 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.11)
    :  of 2019-09-23, modified by Debian"
    : 
    : "9.3"

  [1]: https://i.stack.imgur.com/IaoG1.png

**Comment by hlissner** [comment]
iirc, LSP will not work without a project environment. An org src block has no file or project environment. Not sure I can do anything about this.

**Comment by C0DK** [comment]
Not sure if it is related (if not, i'll open a new issue) but when ever i press tab in a source block (which i assume is how you make it execute) it simply deletes the `#+RESULTS:` line.

Is this a bug or am i using it in the wrong way? i tried the lines as shown above.
