### ISSUE TITLE
[BUG] `magit-todos-list` error: `number-or-marker-p`

### ISSUE THREAD

**Issue by filalex77** [hlissner/doom-emacs#2155]
**Describe the issue**
Getting `set: Wrong type argument: number-or-marker-p, always` on running `magit-todos-list`.

My config: https://github.com/filalex77/nixos-home/tree/master/home/programs/emacs/.doom.d

<details><pre>
Debugger entered--Lisp error: (wrong-type-argument number-or-marker-p always)
  *(always 10)
  (set (make-local-variable (quote magit-todos-auto-group-items)) (* magit-todos-auto-group-items magit-todos-buffer-item-factor))
  magit-todos-list-refresh-buffer()
  apply(magit-todos-list-refresh-buffer nil)
  magit-refresh-buffer()
  magit-setup-buffer-internal(magit-todos-list-mode nil nil)
  (let ((default-directory directory)) (magit-setup-buffer-internal (function magit-todos-list-mode) nil (list)))
  magit-todos-list-internal("/home/brightone/dev/rust/rusteam/")
  (let ((magit--refresh-cache (list (cons 0 0)))) (setq directory (if directory (file-name-as-directory (expand-file-name directory)) default-directory)) (magit-todos-list-internal directory))
  (condition-case nil (let ((magit--refresh-cache (list (cons 0 0)))) (setq directory (if directory (file-name-as-directory (expand-file-name directory)) default-directory)) (magit-todos-list-internal directory)) ((quote magit-outside-git-repo) (let* ((vnew (function (lambda (&rest _) default-directory))) (old (symbol-function (quote magit-toplevel)))) (unwind-protect (progn (fset (quote magit-toplevel) vnew) (call-interactively (function magit-todos-list))) (fset (quote magit-toplevel) old)))))
  magit-todos-list(nil)
  funcall-interactively(magit-todos-list nil)
  call-interactively(magit-todos-list nil nil)
  command-execute(magit-todos-list)
</pre></details>

**Steps to reproduce**
1. Open a project (e.g. a `git` repository)
2. `SPC p t` (`magit-todos-list`)

**System information**
<details>

```
emacs   version    26.3
        features   XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD
        build      Dec 05, 2019
        buildopts  (--prefix=/nix/store/4jpisqd8gb83vg1s96aqj9crywjwma1g-emacs-26.3 --disable-build-details --with-modules --with-x-toolkit=gtk3 --with-xft CFLAGS=-DMAC_OS_X_VERSION_MAX_ALLOWED=101200)
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop 6bb597564 2019-12-04 21:51:59 -0500
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /run/current-system/sw/bin/zsh
        uname      Linux 5.4.1 #1-NixOS SMP Fri Nov 29 09:10:32 UTC 2019 x86_64
        path       (/nix/store/ggrxzh475czf4gb8vxcc4xwpyj1sipdr-emacs-packages-deps/bin ~/bin /run/wrappers/bin ~/.local/share/flatpak/exports/bin /var/lib/flatpak/exports/bin ~/.nix-profile/bin /etc/profiles/per-user/brightone/bin /nix/var/nix/profiles/default/bin /run/current-system/sw/bin ~/.zsh/plugins/prezto ~/.zsh/plugins/fast-syntax-highlighting /nix/store/4jpisqd8gb83vg1s96aqj9crywjwma1g-emacs-26.3/libexec/emacs/26.3/x86_64-pc-linux-gnu)
config  envfile    nil
        elc-files  0
        modules    (:app calendar (rss +org) (write +wordnut +langtool) :completion (company +auto) (ivy +fuzzy +prescient +icons) :editor (evil +everywhere) file-templates fold (format +onsave) lispy multiple-cursors rotate-text snippets word-wrap :emacs (dired +icons) electric vc :email mu4e :lang assembly (cc +lsp) crystal data erlang (elixir +lsp) emacs-lisp go (java +meghanada) (javascript +lsp) julia latex ledger lua markdown nim nix (org +dragndrop +ipython +pandoc +present) plantuml (python +lsp) racket rest (ruby +lsp +rails) (rust +lsp) sh web :term eshell term :tools ansible direnv docker editorconfig (eval +overlay) (flycheck +childframe) flyspell gist (lookup +devdocs) lsp (magit +forge) make pass pdf rgb terraform :ui doom doom-dashboard doom-quit fill-column hl-todo hydra modeline nav-flash ophints (popup +all +defaults) (pretty-code +fira) treemacs unicode vc-gutter vi-tilde-fringe (window-select +numbers) workspaces :config literate (default +bindings +smartparens))
        packages   (n/a)
        elpa       (n/a)
```
</details>

**Comment by hlissner** [comment]
This is an upstream issue. I have reported the issue: https://github.com/alphapapa/magit-todos/issues/92.

For the time being, set `magit-todos-auto-group-items` to a numerical value instead of `'always`.

**Comment by hlissner** [comment]
I'll close this issue now that it has been resolved upstream (https://github.com/alphapapa/magit-todos/commit/dc292694a555be773ed25b285be4663994f756e3). Thanks for bringing it to my attention!
