### ISSUE TITLE
[BUG] Emacs loss focus when switching desktop on macOS

### ISSUE THREAD

**Issue by nasyxx** [hlissner/doom-emacs#2156]
**Describe the issue**
- What did you expect to happen?
When switching desktop, I should be able to continue typing instead of needing to click again with the mouse.
See the `emacs -Q`: https://youtu.be/cD1SBWXYn3E

- What actually happened?
See the video: https://youtu.be/LNJzh6_G0X0

- Can you include a link to your private config?
Complete new config without evil and with this line below.
```
(add-to-list 'default-frame-alist '(alpha . (80 . 75)))
```
**System information**
<details><pre>
((emacs
  (version . "26.3")
  (features . "RSVG DBUS GLIB NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS LCMS2")
  (build . "Dec 03, 2019")
  (buildopts "--enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-mac/HEAD-03ef040/share/info/emacs --prefix=/usr/local/Cellar/emacs-mac/HEAD-03ef040 --with-mac --enable-mac-app=/usr/local/Cellar/emacs-mac/HEAD-03ef040 --with-gnutls --with-modules --with-rsvg")
  (windowsys . batch)
  (daemonp))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD 6bb597564 2019-12-04 21:51:59 -0500"))
 (system
  (type . darwin)
  (config . "x86_64-apple-darwin19.0.0")
  (shell . "/usr/local/bin/zsh")
  (uname . "Darwin 19.0.0 Darwin Kernel Version 19.0.0: Wed Oct 23 18:29:05 PDT 2019; root:xnu-6153.41.3~44/RELEASE_X86_64 x86_64")
  (path "~/.pyenv/bin" "~/.pyenv/shims" "~/.zplugin/polaris/bin" "~/.poetry/bin" "~/.pyenv/shims" "~/.pyenv/bin" "~/.cargo/bin" "~/.local/bin" "/usr/local/opt/libxml2/bin" "/usr/local/opt/ncurses/bin" "/usr/local/opt/bison/bin" "/usr/local/bin" "/usr/bin" "/bin" "/usr/sbin" "/sbin" "/Library/TeX/texbin" "/usr/local/share/dotnet" "/opt/X11/bin" "~/.dotnet/tools" "/usr/local/Cellar/emacs-mac/HEAD-03ef040/libexec/emacs/26.3/x86_64-apple-darwin19.0.0"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion (company +childframe) helm :ui doom doom-dashboard doom-quit hl-todo indent-guides modeline nav-flash ophints (popup +all +defaults) (pretty-code +fira +hasklig) treemacs vc-gutter (window-select +switch-window) workspaces :editor file-templates fold (format +onsave) multiple-cursors parinfer rotate-text snippets :emacs (dired +icons) electric (ibuffer +icons) vc :term vterm :tools ansible (eval +overlay) flycheck flyspell gist (lookup +docsets) lsp macos magit make pdf rgb :lang data emacs-lisp markdown (org +dragndrop +ipython +pandoc +present) sh :config (default +bindings +smartparens))
  (packages "n/a")
  (elpa "n/a")))
</pre></details>

**Comment by hlissner** [comment]
This seems like an issue with Emacs or MacOS; a window event isn't being received or sent at the right time. You could try:

```elisp
;; ~/.doom.d/config.el
(add-hook! 'focus-in-hook (select-frame-set-input-focus (selected-frame)))
```

You could also try [installing emacs from the emacs-mac formula](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#on-macos).

Otherwise, I'm not sure what else can be done about this at the elisp level.

**Comment by nasyxx** [comment]
`(add-hook! 'focus-in-hook (select-frame-set-input-focus (selected-frame)))` doesn't help.  It still keep losing the focus.

BTW, I am already using `emacs-mac.`

**Comment by mjlbach** [comment]
I don't think I have this issue on emacs-plus.

**Comment by nasyxx** [comment]
> I don't think I have this issue on emacs-plus.

Indeed, emacs-plus doesn't lose focus.

**Comment by chang2000** [comment]
Same problem with emacs-mac
Already turned off all windows manager and reboot my machine
Under macOS Catalina

**Comment by yelite** [comment]
On emacs-mac, `toggle-frame-fullscreen` twice and this problem goes away. 

Another observation, initially the full screen button on the title bar has a plus icon in it, and clicking it only resizes emacs without making it fullsreen and to a seaprate desktop, which is different than most of apps on mac. After `toggle-frame-fullscreen` twice it becomes normal.

Hope this can help someone find the fix.

**Comment by mjlbach** [comment]
I believe this is an issue with the emacs port rather than anything doom specific

**Comment by yelite** [comment]
> so I believe that's an issue with doom orz

emacs-mac with spacemacs has the same issue. My hypothesis is that emacs-mac has diverging behavior on some function and some package, used by both spacemacs and doom, calls it on startup

**Comment by yelite** [comment]
It's all about `menu-bar-lines`. It's stated clearly in the emacs-mac doc and previously mentioned by an answer from StackExchange https://emacs.stackexchange.com/a/28296 

>  Instead, the value of the @code{menu-bar-lines} frame
> parameter affects the system-wide full screen behavior of the frame.
> In most cases, disabling the menu bar of a particular frame by default
> means that it is a utility frame used for a subsidiary purpose
> together with other frames, rather than an ordinary frame on its own.

The corresponding source in emacs-mac is at https://bitbucket.org/mituharu/emacs-mac/src/30dcebe71bfdc5da5f8b0f7fbe530ca5a2485f58/src/macappkit.m#lines-2989

The related config in Doom is at https://github.com/hlissner/doom-emacs/blob/develop/core/core-ui.el#L282

The workaround I did is to remove `menu-bar-lines` from `default-frame-alist` in my private config.el. For emacs 27 we may need to update the early-init.el as well

**Comment by hlissner** [comment]
@yelite I can assume that [this hook](https://github.com/hlissner/doom-emacs/blob/develop/core/core-ui.el#L303-L308) isn't doing its job then?

**Comment by yelite** [comment]
@hlissner Oh I missed this hook. So the real problem is that this hook isn't called for initial frame. I tested with a vanilla doom config and subsequent frames get the menu-bar-lines 1. Not sure if this is the standard behavior or something specific to emacs-mac

**Comment by hlissner** [comment]
@yelite I added the hook to `window-setup-hook`, which runs after the initial frame is set up. Let me know if that resolves the issue.

**Comment by yelite** [comment]
@hlissner This fixes the problem! Thanks!
