### ISSUE TITLE
[BUG] bin/doom install fails

### ISSUE THREAD

**Issue by ckruse** [hlissner/doom-emacs#2157]
Today I decided to try out emacs 27 HEAD because of performance issues. So I deleted `~/.emacs.d/.local` and ran `./bin/doom install` with the new emacs version. This lead to the following error:

<details><pre>
➜ ckruse@Pug ~/.emacs.d (develop) ✗ % ./bin/doom install
Installing Doom Emacs!

> Creating Code/emacs/doom.d/
  ✓ Created Code/emacs/doom.d/
! init.el already exists, skipping
! config.el already exists, skipping
! packages.el already exists, skipping

Autoload file error: autoloads.pkg.el -> (file-missing Cannot open load file No such file or directory helm-easymenu)
Bootstrapping straight.el...
Bootstrapping straight.el...done
Looking for gnu-elpa-mirror recipe → Cloning melpa...
Looking for emacsmirror-mirror recipe → Cloning gnu-elpa-mirror...
Looking for straight recipe → Cloning emacsmirror-mirror...
Building straight...
Cloning use-package...
Building use-package...
Building use-package → Building bind-key...

Building use-package...
Cloning emacs-async...
Building async...
Cloning gcmh...
Building gcmh...

Warning (emacs): Your package autoloads file is missing
--------------------------------------------------

There was an unexpected error:
  Error in an autoloads file (doom-autoload-error)
  Run `bin/doom refresh' to generate them

Run the command again with the -d (or --debug) option to enable debug
mode and, hopefully, generate a stack trace. If you decide to file a bug
report, please include it!

Emacs outputs to standard error, so you’ll need to redirect stderr to
stdout to pipe this to a file or clipboard!

  e.g. doom -d install 2>&1 | clipboard-program

Error in Doom Emacs core: doom-autoload-error, "Run `bin/doom refresh' to generate them"
</pre></details>

After running `./bin/doom refresh` everything works as expected, even `./bin/doom install`.

**Steps to reproduce**
1. delete `~/.emacs.d/.local`
2. run `./bin/doom install`

**System information**

<details>

```
emacs   version    27.0.50
        features   RSVG IMAGEMAGICK GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS JSON PDUMPER LCMS2 GMP
        build      Dec 06, 2019
        buildopts  (--disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus/HEAD-48373e7/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus/HEAD-48373e7 --with-xml2 --without-dbus --with-gnutls --with-imagemagick --with-json --with-modules --with-rsvg --with-ns --disable-ns-self-contained)
        windowsys  ns
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop, origin/develop, origin/HEAD 318754c4d 2019-12-05 20:48:53 -0500
system  type       darwin
        config     x86_64-apple-darwin19.0.0
        shell      /usr/local/bin/zsh
        uname      Darwin 19.0.0 Darwin Kernel Version 19.0.0: Thu Oct 17 16:17:15 PDT 2019; root:xnu-6153.41.3~29/RELEASE_X86_64 x86_64
        path       (~/Code/termitel/termitool/frontend/node_modules/.bin/ ~/.rbenv/shims/ ~/.rbenv/shims/ /usr/local/bin/ /usr/bin/ /bin/ /usr/sbin/ /sbin/ /usr/local/MacGPG2/bin/ /usr/local/opt/go/libexec/bin/ ~/.fzf/bin/ /usr/local/opt/go/libexec/bin/ /usr/local/Cellar/emacs-plus/HEAD-48373e7/libexec/emacs/27.0.50/x86_64-apple-darwin19.0.0/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company (helm +fuzzy) :ui doom doom-dashboard doom-quit hl-todo indent-guides modeline nav-flash ophints (popup +all +defaults) treemacs unicode vc-gutter window-select :editor file-templates fold (format +onsave) multiple-cursors rotate-text snippets :emacs (dired +icons) vc :tools ansible editorconfig eval flycheck (lookup +docsets) lsp macos magit :lang data erlang (elixir +lsp) emacs-lisp (javascript +lsp) markdown (org +attach +babel +capture +export +habit +present +protocol) (ruby +lsp) sh (web +lsp) :config (default +bindings +smartparens))
        packages   (n/a)
        elpa       (n/a)
```
</details>

**Comment by hlissner** [comment]
As of cd158c5 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
