### ISSUE TITLE
[HOWTO] evil-default-state not honoured when opening new buffer

### ISSUE THREAD

**Issue by olofwalker** [hlissner/doom-emacs#2161]
**Describe the issue**
- What did you expect to happen?

I want to have emacs keybindings per default.

- What actually happened?

Got VIM keybindings or whatever that abomination is called ;)

- Do you have screenshots/casts of your issue?

N/A

- What commands are bound to any keys you've referenced? (use `SPC h k` to
  inspect keys)

N/A

- Can you include a link to your private config?

```
 more config.el                                               
;;; .doom.d/config.el -*- lexical-binding: t; -*-

(setq evil-default-state 'emacs)
```

- Were any warnings or errors logged to \*Messages\* (`SPC h e` or `M-x
  view-echo-area-messages` will open it).

Not that I can see.

<details><pre>
Include a backtrace of the error.

How to acquire a backtrace:
https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#how-to-extract-a-backtrace-from-an-error
</pre></details>

**Steps to reproduce**
1. Install doom
2. Append my change (above) to your private config.
3. Start emacs and open a file
4. You manually have to switch to `emacs mode` using CTRL-z

**System information**
<details><pre>
Loading /etc/emacs/site-start.d/00debian.el (source)...
Loading /etc/emacs/site-start.d/50cmake-data.el (source)...
Loading /etc/emacs/site-start.d/50dictionaries-common.el (source)...
Loading debian-ispell...
Loading /var/cache/dictionaries-common/emacsen-ispell-default.el (source)...
Loading /var/cache/dictionaries-common/emacsen-ispell-dicts.el (source)...
((emacs
  (version . "26.3")
  (features . "XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS LIBSYSTEMD LCMS2")
  (build . "sep 23, 2019")
  (buildopts "--build x86_64-linux-gnu --prefix=/usr --sharedstatedir=/var/lib --libexecdir=/usr/lib --localstatedir=/var/lib --infodir=/usr/share/info --mandir=/usr/share/man --enable-libsystemd --with-pop=yes --enable-locallisppath=/etc/emacs:/usr/local/share/emacs/26.3/site-lisp:/usr/local/share/emacs/site-lisp:/usr/share/emacs/26.3/site-lisp:/usr/share/emacs/site-lisp --with-sound=alsa --without-gconf --with-mailutils --build x86_64-linux-gnu --prefix=/usr --sharedstatedir=/var/lib --libexecdir=/usr/lib --localstatedir=/var/lib --infodir=/usr/share/info --mandir=/usr/share/man --enable-libsystemd --with-pop=yes --enable-locallisppath=/etc/emacs:/usr/local/share/emacs/26.3/site-lisp:/usr/local/share/emacs/site-lisp:/usr/share/emacs/26.3/site-lisp:/usr/share/emacs/site-lisp --with-sound=alsa --without-gconf --with-mailutils --with-x=yes --with-x-toolkit=gtk3 --with-toolkit-scroll-bars 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/emacs-wvqver/emacs-26.3+1=. -fstack-protector-strong -Wformat -Werror=format-security -Wall' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro'")
  (windowsys . batch)
  (daemonp))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD 318754c4d 2019-12-05 20:48:53 -0500"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/usr/bin/zsh")
  (uname . "Linux 5.3.0-23-generic #25-Ubuntu SMP Tue Nov 12 09:22:33 UTC 2019 x86_64")
  (path "REDACTED" "/usr/lib/emacs/26.3/x86_64-linux-gnu"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company helm ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold multiple-cursors rotate-text snippets :emacs dired electric ibuffer vc :tools (eval +overlay) flycheck (lookup +docsets) magit pass :lang data emacs-lisp markdown (org +dragndrop +ipython +pandoc +present) scala sh :app calendar :config (default +bindings +smartparens))
  (packages "n/a")
  (elpa "n/a")))

</pre></details>

**Comment by hlissner** [comment]
It doesn't seem like you want evil at all, so [why don't you disable it?](https://github.com/hlissner/doom-emacs/blob/develop/docs/faq.org#can-vimevil-be-removed-for-a-more-vanilla-emacs-experience).

If you actually want to keep it, there are some additional steps to "always starting in emacs state". To quote the documentation of `evil-default-state` (see `C-h v evil-default-state`):

> This is the state a mode comes up in **when it is not listed in evil-emacs-state-modes, evil-insert-state-modes or evil-motion-state-modes**. The value may be one of normal, insert, visual, replace, operator, motion and emacs.

You'll need:

```elisp
(setq evil-default-state 'emacs
      evil-emacs-state-modes nil
      evil-insert-state-modes nil
      evil-motion-state-modes nil
      evil-normal-state-modes nil)
```

However, some modules and packages may change evil-*-state-modes later, so this may work even better:

```elisp
(add-hook 'evil-local-mode-hook #'evil-emacs-state)
```

Hope that helps!

**Comment by olofwalker** [comment]
>It doesn't seem like you want evil at all, so why don't you disable it?.

Sorry, I missed that obvious solution.

Thanks a lot for Doom emacs, I really like it so far!
