### ISSUE TITLE
[HOWTO] Get doom generate env function into personal config?

### ISSUE THREAD

**Issue by taigacute** [hlissner/doom-emacs#2167]
Hi @hlissner ,Thanks for your greate work, i used doom some months ,now i want create my own config.In my config i used the function that generate env file from `cli/env.el`, I copied env.el and the `doom-rpartial` function into my config . but when i install i got an error ,so need your help! 
![image](https://user-images.githubusercontent.com/41671631/70388984-6971c600-19f4-11ea-844e-3f337d7a6117.png)

**Comment by hlissner** [comment]
Please produce a backtrace from the issue or show the code. As this is not a problem with Doom, I cannot guess how your version works.

**Comment by taigacute** [comment]
First i copied this function  
```elisp
(defun doom-rpartial (fn &rest args)
  "Return a function that is a partial application of FUN to right-hand ARGS.
ARGS is a list of the last N arguments to pass to FUN. The result is a new
function which does the same as FUN, except that the last N arguments are fixed
at the values with which this function was called."
  (lambda (&rest pre-args)
    (apply fn (append pre-args args))))
```

then copied env.el into my config
<details><pre>

(defvar doom-env-ignored-vars
  '("^DBUS_SESSION_BUS_ADDRESS$"
    "^GPG_AGENT_INFO$"
    "^GPG_TTY$"
    "^HOME$"
    "^PS1$"
    "^PWD$"
    "^R?PROMPT$"
    "^SSH_AGENT_PID$"
    "^SSH_AUTH_SOCK$"
    "^TERM$"
    ;; Doom envvars
    "^DEBUG$"
    "^INSECURE$"
    "^YES$"
    "^__")
  "Environment variables to not save in `doom-env-file'.
Each string is a regexp, matched against variable names to omit from
`doom-env-file'.")

(defun doom-cli-reload-env-file (&optional force-p env-file)
  "Generates `doom-env-file', if it doesn't exist (or if FORCE-P).
This scrapes the variables from your shell environment by running
`doom-env-executable' through `shell-file-name' with `doom-env-switches'. By
default, on Linux, this is '$SHELL -ic /usr/bin/env'. Variables in
`doom-env-ignored-vars' are removed."
  (let ((env-file (if env-file
                      (expand-file-name env-file)
                    doom-env-file)))
    (when (or force-p (not (file-exists-p env-file)))
      (with-temp-file env-file
        (print! (start "%s envvars file at %S")
                (if (file-exists-p env-file)
                    "Regenerating"
                  "Generating")
                (path env-file))
        (let ((process-environment doom--initial-process-environment))
          (print! (info "Scraping shell environment"))
          (print-group!
           (when doom-interactive-mode
             (user-error "'doom env' must be run on the command line, not an interactive session"))
           (goto-char (point-min))
           (insert
            (concat
             "# -*- mode: dotenv -*-\n"
             (format "# Generated from a %s shell environent\n" shell-file-name)
             "# ---------------------------------------------------------------------------\n"
             "# This file was auto-generated by `doom env'. It contains a list of environment\n"
             "# variables scraped from your default shell (excluding variables blacklisted\n"
             "# in doom-env-ignored-vars).\n"
             "#\n"
             (if (file-equal-p env-file doom-env-file)
                 (concat "# It is NOT safe to edit this file. Changes will be overwritten next time you\n"
                         "# run 'doom refresh'. To create a safe-to-edit envvar file use:\n#\n"
                         "#   doom env -o ~/.doom.d/myenv\n#\n"
                         "# And load it with (doom-load-envvars-file \"~/.doom.d/myenv\").\n")
               (concat "# This file is safe to edit by hand, but needs to be loaded manually with:\n#\n"
                       "#   (doom-load-envvars-file \"path/to/this/file\")\n#\n"
                       "# Use 'doom env -o path/to/this/file' to regenerate it."))
             "# ---------------------------------------------------------------------------\n\n"))
           ;; We assume that this noninteractive session was spawned from the
           ;; user's interactive shell, therefore we just dump
           ;; `process-environment' to a file.
           (dolist (env process-environment)
             (if (cl-find-if (doom-rpartial #'string-match-p (car (split-string env "=")))
                             doom-env-ignored-vars)
                 (print! (info "Ignoring %s") env)
               (insert env "\n")))
           (print! (success "Successfully generated %S")
                   (path env-file))
           t))))))
</pre></details>


When the program is executed  function `(doom-cli-reload-env-file)`,i got an error. seems like error in  `doom-rpartial`? what i missed? Thanks for your help.

```shell
> Generating envvars file at "~/.emacs.d/.local/env"
- Scraping shell environment
Symbol’s value as variable is void: fn
make: *** [Makefile:9: install] Error 255
```

**Comment by hlissner** [comment]
Ah, I see. It's because you don't have `lexical-binding` enabled. Add this to the top of all your *.el files:

```elisp
;; -*- lexical-binding: t -*-
```

You'll find it at the top of every elisp file in Doom. [For example](https://github.com/hlissner/doom-emacs/blob/develop/core/cli/env.el#L1).

**Comment by taigacute** [comment]
Thanks! I got it!

**Comment by taigacute** [comment]
@hlissner  sorry to bother you agin. I'm busy working on a company project recently. I didn't learn emacs. I used doom's straight installation function. It worked before, but today I got an error during installation. Sorry I'm a newbie. I used emacs --debug-init. Did not get any error prompts. Hope to get your help, thanks

## Error
![image](https://user-images.githubusercontent.com/41671631/72218468-d9d0b180-3575-11ea-8e72-16b12e1e7e53.png)

## Env
* emacs version : 28

I used this file that funcion of this file from doom

```elisp
;;; core/pacman/pacman.el -*- lexical-binding: t; -*-
;;; package management of pacmanun

(defvar pacman-init-packages-p nil
  "If non-nil, package management system has been initialized.")

(defvar pacman-packages ()
  "A list of enabled packages")

(defvar pacman-core-packages '(straight use-package)
  "A list of packages that must be installed (and will be auto-installed if
missing) and shouldn't be deleted.")

(define-error 'pacman-package-error "Error with packages" )

(defvar pacman-core-package-sources
  '((org-elpa :local-repo nil)
    (melpa
     :type git :host github
     :repo "melpa/melpa"
     :no-build t)
    (gnu-elpa-mirror
     :type git :host github
     :repo "emacs-straight/gnu-elpa-mirror"
     :no-build t)
    (emacsmirror-mirror
     :type git :host github
     :repo "emacs-straight/emacsmirror-mirror"
     :no-build t))
  "A list of recipes for straight's recipe repos.")

;;; straight
(setq straight-base-dir supremacs-local-dir
      straight-repository-branch "develop"
      straight-cache-autoloads nil ; we already do this, and better.
      straight-check-for-modifications nil
      ;; We handle package.el ourselves (and a little more comprehensively)
      straight-enable-package-integration nil
      straight-vc-git-default-clone-depth 1
      ;; Straight's own emacsmirror mirror is a little smaller and faster.
      straight-recipes-emacsmirror-use-mirror t
      ;; Prefix declarations are unneeded bulk added to our autoloads file. Best
      ;; we just don't have to deal with them at all.
      autoload-compute-prefixes nil)

(defun pacman:finalize-straight ()
  (mapc #'funcall (delq nil (mapcar #'cdr straight--transaction-alist)))
  (setq straight--transaction-alist nil))

;;; Getting straight to behave in batch mode
(when noninteractive
  ;; HACK Remove dired & magit options from prompt, since they're inaccessible
  ;;      in noninteractive sessions.
  (advice-add #'straight-vc-git--popup-raw :override #'straight--popup-raw))

;; ensure the package management 'straight installed
(defun pacman:ensure-straight ()
  "Ensure `straight' is installed and was compiled with this version of Emacs."
  (defvar bootstrap-version)
  (let* (;; Force straight to install into ~/.emacs.d/.local/straight instead of
         ;; ~/.emacs.d/straight by pretending `pacman-local-dir' is our .emacs.d.
         (user-emacs-directory straight-base-dir)
         (bootstrap-file (concat straight-base-dir "straight/repos/straight.el/straight.el"))
         (bootstrap-version 5))
    (make-directory (expand-file-name  "straight/build" straight-base-dir) 'parents)
    (unless (featurep 'straight)
      (unless (or (require 'straight nil t)
                  (file-readable-p bootstrap-file))
        (with-current-buffer
            (url-retrieve-synchronously
              (format "https://raw.githubusercontent.com/raxod502/straight.el/%s/install.el"
                     straight-repository-branch)
             'silent 'inhibit-cookies)
          (goto-char (point-max))
          (eval-print-last-sexp)))
      (load bootstrap-file nil t))))

;; package management core function
(defun pacman:core (&optional force-p)
  (unless pacman-init-packages-p
     (setq force-p t))
  (when (or force-p (not pacman-packages))
    (print! (yellow "💥 Initializing straight and core packages..."))
    (setq pacman-init-packages-p t)
    (unless (fboundp 'straight--reset-caches)
      (pacman:ensure-straight)
      (require 'straight))
    (straight--reset-caches)
    (setq straight-recipe-repositories nil)
    (mapc #'straight-use-recipes pacman-core-package-sources)
    (straight-register-package
     `(straight :type git :host github
                :repo ,(format "%s/straight.el" straight-repository-user)
                :files ("straight*.el")
                :branch ,straight-repository-branch
                :no-byte-compile t))
    (mapc #'straight-use-package  pacman-core-packages)
    (print! (green "✨ Installed straight and core packages successed...\n"))
    (watcher:log "Initializing pacman-packages")
    ; (setq pacman-packages (pacman-package-list))
    (cl-loop for (pkg . plist) in supremacs-packages
             if (not (plist-get plist :ignore))
             do (with-demoted-errors "Package error: %s"
                  (straight-register-package
                   (if-let (recipe (plist-get plist :recipe))
                       (cons pkg recipe)
                     pkg))))
    (unless supremacs-interactive-mode
      (add-hook 'kill-emacs-hook #'pacman:finalize-straight))))

(defun pacman:straight-installer ()
  (print! (yellow "💥 Installing & building packages..."))
  (print-group!
   (let ((n 0))
     (dolist (package (hash-table-keys straight--recipe-cache))
       (straight--with-plist (gethash package straight--recipe-cache)
           (local-repo)
         (let ((existed-p (file-directory-p (straight--repos-dir package))))
           (condition-case-unless-debug e
               (and (straight-use-package (intern package) nil nil (make-string (1- (or supremacs-format-indent 1)) 32))
                    (not existed-p)
                    (file-directory-p (straight--repos-dir package))
                    (cl-incf n))
             (error
              (signal 'pacman-package-error
                      (list e (straight--process-get-output))))))))
     (if (= n 0)
         (print! (success "No packages need to be installed"))
       (print! (green " ✨ Installed & built %d packages") n)
       t))))


(defun pacman:initialize()
  (pacman:core)
  (pacman:straight-installer))


(provide 'pacman)
;; pacman.el ends here
```
the packages.el 
```elisp
;;; packages.el  -*- lexical-binding: t; -*-

(defvar supremacs-packages '((async)
                             (gcmh)
                             (general)
                             (which-key)
                             (evil)
                             (evil-collection)
                             (go-mode)
                             (lsp-mode)
                             (company)
                             (company-lsp)
                             (projectile)
                             (undo-tree :recipe
                                        (:host github :repo "emacsmirror/undo-tree"))))

(provide 'packages)
```
then i used this test funcion 
```elisp
(defun test-pacman-init ()
  (supremacs:load-autoloads-file (concat supremacs-autoload-dir "format.el"))
  (watcher:try-load 'pacman)
  (watcher:try-load 'packages)
  (pacman:initialize)
)
```
when i make by `emacs -Q --batch -l 'init.el'`  i got this error，more about my config in this [repo](https://github.com/hardcoreplayers/supremacs),I ’m sorry this will take up your precious time. If you have time, I hope to get your help. If I disturb you, I ’m sorry.
