### ISSUE TITLE
Selectively installing packages and window selection module

### ISSUE THREAD

**Issue by UndeadKernel** [hlissner/doom-emacs#218]
This is a question rather than a bug report.

Is there an easy way to choose packages to install according to a module flag?
I plan to do the following and I'm looking for the best alternative: I want to create a new module called "window-select". This moddule would have a flag that lets the user choose between  "ace-window", "switch-window" or some other alternative. As you may be aware, there are many packages to switch windows and I want to create a module that allows a user to select which one to use.  Of course that would imply removing ace-window from core/editor and making it its own package.

What is your view regarding this topic?

**Comment by hlissner** [comment]
You can use the `featurep!` macro to test for module flags.

+ long form: `(featurep! :feature version-control +git)`
+ syntactic sugar: `(featurep! +git)` (only works from inside the feature/version-control module).

You can use this to conditionally install/run certain things. e.g.

```emacs-lisp
;; ~/.emacs.d/init.el
(doom! :ui (window-select +ace-window +switch-window))

;; ~/.emacs.d/modules/ui/window-select/packages.el
(and (featurep! +ace-window) (package! ace-window))
(and (featurep! +switch-window) (package! switch-window))
```

I've been tempted to switch ace-window out for switch-window, but the module approach suits me fine.

**Comment by UndeadKernel** [comment]
Good to know that you planned for "featurep!" to also work in the packages.el files.
I'll take care of this and request a pull when done.
