### ISSUE TITLE
How to set up plantuml-model-hook to support company-dabbrev in doom？

### ISSUE THREAD

**Issue by huos3203** [hlissner/doom-emacs#2181]
**What I want to achieve**
`company-dabbrev` The keywords in all currently opened buffers are displayed as complements
- What have you tried?
```el
;;(use-package! plantuml-mode
;;  :hook (plantuml-mode . (lambda ()
;;                           (set (make-local-variable 'company-backends) '(company-dabbrev)
;;                                ))))
;;(add-hook 'plantuml-mode-hook
;;           (lambda ()
;;             (setq (make-local-variable 'company-backends) '((company-dabbrev-code) company-dabbrev))
;;             ))
(after! plantuml-mode
  (add-hook 'plantuml-mode-hook
           (lambda ()
             (setq (make-local-variable 'company-backends) '((company-dabbrev-code) company-dabbrev))
             )))
```
How to set up `plantuml-model-hook` to support `company-dabbrev` in doom？

**Comment by hlissner** [comment]
1. You need to use `(set (make-local-variable ...) ...)`, not `(setq (make-local-variable ...) ...)`.

2. `((company-dabbrev-code) company-dabbrev)` is unnecessarily nested. I also suggest you use one or the other, rather than both.

3. A simpler way to change a mode's company backends is to use `set-company-backend!`:

   ```elisp
   (after! plantuml-mode
     (set-company-backend 'plantuml-mode 'company-dabbrev-code))
   ```

Hope that helps!

**Comment by huos3203** [comment]
@hlissner  
i  add this config  in ` .doom.d/config.el`
```
(after! plantuml-mode
  (set-company-backend 'plantuml-mode 'company-dabbrev-code))
```
it not ok when open a `test.plantuml` file:
```
File mode specification error: (void-function set-company-backend)
```

**Comment by hlissner** [comment]
Your first snippet is still using `setq` though?

For future reference, you can also use `setq-hook!` to do this more succinctly:

```elisp
(setq-hook! 'plantuml-mode-hook company-backends '(company-dabbrev-code))
```

But if `set-company-backend!` works for you, that is the best option.

**Comment by huos3203** [comment]
I try update this config, don't work.
```
(setq-hook! 'plantuml-mode-hook company-backends '(company-dabbrev-code))
```
