### ISSUE TITLE
[BUG] org-tree-slide mode does not show headings

### ISSUE THREAD

**Issue by dinosaur-lin** [hlissner/doom-emacs#2182]
**Describe the issue**
- What did you expect to happen?
org-tree-slide mode should show headings at the top of the slide
- What actually happened?
org-tree-slide mode does not show headings at the top of slides
- Do you have screenshots/casts of your issue?
This is the text in org file:

```org
* Introduction

  My son is reading yellow stone stories in kida-z now.

  It is a fun story
```

In the screenshot of org-tree-slide mode, there is no "Introduction"

![image](https://user-images.githubusercontent.com/1984447/70677150-4cd7c700-1c5c-11ea-924a-fc0a9be42318.png)

- What commands are bound to any keys you've referenced? (use `SPC h k` to
  inspect keys)
I just did M-x org-tree-slide-mode
- Can you include a link to your private config?
I use plain doom distribution without any changes.
- Were any warnings or errors logged to \*Messages\* (`SPC h e` or `M-x
  view-echo-area-messages` will open it).
No, I do not see any errors in \*Messages\*

**Comment by hlissner** [comment]
Iirc, this is controlled by `org-tree-slide-skip-outline-level`, which doom sets to `2` by default (as the top-level headings are treated as "slides", and subheadings are treated as the actual content of the slide).

This would reverse that:

```elisp
(after! org-tree-slide
  (setq org-tree-slide-skip-outline-level 1))
```
