### ISSUE TITLE
[HOWTO] Display the org src blocks (begin/end/content) the same background as normal org text.

### ISSUE THREAD

**Issue by triklsbg** [hlissner/doom-emacs#2185]
**What are you trying to achieve?**

Decrease visual disturbance while browsing org files
These slightly differently (more grey, less grey) horizontal bars irritate me a lot!

**What have you tried?**
Scanned the readmes for some examples.

**Comment by hlissner** [comment]
- You didn't include your `M-x doom/info`, so I'll assume you're using Doom and that this isn't a general Emacs question.
- You didn't mention what theme you're using, so I'll assume you're using `doom-one`.
- You didn't include a screenshot, so I'll assume you're talking about these:

   ![image](https://user-images.githubusercontent.com/510883/70745910-db972300-1cf2-11ea-8b73-f806ad49fd08.png)

---

Org mode controls the looks of these blocks with the `org-block`, `org-block-begin-line` and `org-block-end-line` faces. To customize them in doom, use `custom-set-faces!`:

```elisp
(custom-set-faces!
  '((org-block org-block-begin-line org-block-end-line) :background nil))
```

Hope that helps!
