### ISSUE TITLE
[BUG] Literate configuration tangling doesn't filter by language

### ISSUE THREAD

**Issue by Eiyeron** [hlissner/doom-emacs#2187]
**What did you expect to happen?**
Having a `config.org` with code blocks in other languages (as reference or example) would be skipped when tangling the file into `config.el`

**What actually happened?**
A code block I was actually using as documentation marked as `bash` was inserted into `config.el`

**Additional details:**
Here's a screenshot of the incriminated source block and the result in the `config.el` file.
![2019-12-13 001356 - ](https://user-images.githubusercontent.com/936086/70756729-99df9a00-1d3d-11ea-94e9-ec5d8d47cebe.png)

I have a quick unflexible fix: add a filter argument `'emacs-lisp` to `+literate-tangle`'s invocation of `org-babel-tangle-file`, but there *might* be situations where the user might still want those blocks or blocks of specific languages around and I haven't figured how to properly make a variable. So, I'll be linking a patch if you need a dirty fix or to locate the issue instead of making a fork for one argument in a function call. [tangle-fix.patch.txt](https://github.com/hlissner/doom-emacs/files/3958193/tangle-fix.patch.txt)

**Steps to reproduce:**
1. Enable the literate module
2. In config.org, create a source block with any language
3. On saving (or triggering the tangle), see in config.el that the incriminated block is there, regardless of the block's language.

**System information:**
<details><pre>
<details>

```
emacs   version    26.3
        features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2
        build      Aug 29, 2019
        buildopts  (--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-modules 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now)
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop 5f2e708cd 2019-12-12 03:48:25 -0500
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /usr/bin/zsh
        uname      Linux 5.3.13-arch1-1 #1 SMP PREEMPT Sun, 24 Nov 2019 10:15:50 +0000 x86_64
        path       (/usr/local/sbin/ /usr/local/bin/ /usr/bin/ /usr/bin/site_perl/ /usr/bin/vendor_perl/ /usr/bin/core_perl/ ~/.local/bin/ ~/.local/bin/ /usr/lib/emacs/26.3/x86_64-pc-linux-gnu/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) (pretty-code +pragmata-pro) vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold multiple-cursors rotate-text snippets :emacs dired electric ibuffer vc :tools editorconfig (eval +overlay) flycheck (lookup +docsets) magit :lang data emacs-lisp lua markdown (org +dragndrop +ipython +pandoc +present) sh :app (write +write-mode) :config literate (default +bindings +smartparens))
        packages   (n/a)
        elpa       (n/a)
```
</details>
</pre></details>

Thanks for reading and have a nice day.

**Comment by hlissner** [comment]
I'd rather not hard-code it like that and rob the user of options. 

You can alternatively control tangling from within the org file with `:tangle` header arguments. e.g.

1. The whitelist approach: add`#+PROPERTY: header-args :tangle no` to your config.org, and add `:tangle yes` to the particular blocks you want tangled

2. The blacklist approach: add `:tangle no` to the ones you want excluded.

3. Or set `:tangle` in a heading's property drawer so it only applies to the subtree:

```org
* Heading A
:properties:
:header-args: :tangle no
:end:

#+begin_src sh 
rm -rf /
#+end_src

* Heading B
:properties:
:header-args: :tangle ~/.doom.d/hi.el
:end:

#+begin_src elisp 
(message "Hi!")
#+end_src

* Heading C

#+begin_src elisp
(load! "hi")
#+end_src
```

**Comment by Eiyeron** [comment]
Hello. Thank you for the quick answer, I completely overlooked those options. Sorry for the misguided issue, I think I see a bit better where you're going with the project's mantra.

Have a nice day!

**Comment by hlissner** [comment]
No problem at all; I'm glad I could help!
