### ISSUE TITLE
[HOWTO] Display Chinese characters in plantuml previews in tty Emacs?

### ISSUE THREAD

**Issue by iT-Boyer** [hlissner/doom-emacs#2188]
I see this ` plantuml-mode `‘s config for support chinese that configurations officially recommended by plantuml
```
(after! on-plantuml
...
(add-to-list ‘org-babel-default-header-args:plantuml
‘(:cmdline . “-charset utf-8”)))
```
but，`CTRL + c Ctrl + c ` previewing a plantuml file containing chinese  characters , there will always be garbled code. 

![IMG_1085](https://user-images.githubusercontent.com/4022953/70803038-15008900-1dee-11ea-8409-bccbf061667a.jpeg)

**Comment by hlissner** [comment]
Are you using the plantuml executable, jar or the server? (i.e. what is the value of `plantuml-default-exec-mode`?

**Comment by huos3203** [comment]
yes
use emacs.app is ok,but it have this problem  in terminal

**Comment by hlissner** [comment]
> it have this problem in terminal

What terminal do you use? It must be capable of showing unicode. I'm not even sure Emacs can do unicode in terminal emacs. You could try enabling the `:ui unicode` module and see what happens.

**Comment by huos3203** [comment]
i use iterm2 on macosx, it default use plantuml server when preview in iterm2.
this have problem when use plantuml server on emacs.app

**Comment by hlissner** [comment]
`:ui unicode` is not a command, it is a module. To enable the module, uncomment `unicode` under `:ui` in `~/.doom.d/init.el`, as shown in https://github.com/hlissner/doom-emacs/blob/develop/docs/faq.org#how-do-i-enable-or-disable-a-doom-module

**Comment by huos3203** [comment]
i‘m sorry 
I confirm that the cause of this problem is `plantuml-set-output-type` is set to `txt`. In the terminal or emacs.app, it exists：
![](https://user-images.githubusercontent.com/4022953/70803038-15008900-1dee-11ea-8409-bccbf061667a.jpeg)

**Comment by huos3203** [comment]
i edit uncomment `unicode` under :ui in `~/.doom.d/init.el`,and `/bin/doom refresh`
this problem is exists when `plantuml-set-output-type` is `txt`.

**Comment by hlissner** [comment]
Ah I see. So the issue is resolved?

**Comment by huos3203** [comment]
no
this problem is exists when plantuml-set-output-type is txt.
