### ISSUE TITLE
[HOWTO] Project-local snippets

### ISSUE THREAD

**Issue by beojan** [hlissner/doom-emacs#2197]
**What are you trying to achieve?**
I'd like to add a snippets directory purely for a specific project, containing both snippets and file templates, and have these snippets override global snippets within that project.

**What have you tried?**
A `.dir-locals.el` file with `yas-activate-extra-mode` as described [here](https://github.com/joaotavora/yasnippet/issues/936).

This was a complete failure. The extra mode failed to activate. This also doesn't allow file templates to be included.

I also tried setting `+snippets-dir` to a local directory in `.dir-locals.el` (I'd prefer not to, to keep global snippets that aren't overriden). Again, this failed to work.

**Comment by hlissner** [comment]
You could try defining project minor modes with `def-project-mode!` (see `SPC h f def-project-mode\!` for details):

```elisp
(def-project-mode! +php-laravel-mode
  :modes '(php-mode yaml-mode web-mode nxml-mode js2-mode scss-mode)
  :files (and "artisan" "server.php"))

(def-project-mode! my-project-mode
  :match "^/path/to/your/project/.+$")
```

`def-project-mode!` uses `yas-activate-extra-mode` under the hood. If you add a snippet to `~/.doom.d/snippets/my-project-mode/*` it should only apply when that project mode is active (in `my-project-mode`'s case, whenever the filename matches the given regexp.

**Comment by beojan** [comment]
Is there any way to do this in such a way that the snippets and configuration are in the same directory as the project, so I can track them with git too?

**Comment by jcf** [comment]
@beojan if you create a project minor mode you can use the associated hook to add to Yasnippet's snippets dir with something like this:

``` emacs-lisp
(defun add-project-snippets ()
  (let ((dir (expand-file-name "snippets" projectile-project-root)))
    (when (file-directory-p dir)
      (add-to-list 'yas-snippets-dir dir))))

(add-hook 'my-project-mode-hook #'add-project-snippets)
```

I haven't tested the above code, but hopefully it helps get you started.
