### ISSUE TITLE
Error in make compile: modules/feature/version-control/config.el

### ISSUE THREAD

**Issue by Ptival** [hlissner/doom-emacs#220]
Using master:

> In toplevel form:
> modules/feature/version-control/config.el:3:1:Error: featurep! was used incorrectly (doom--module wasn’t unset)
> Failed to compile modules/feature/version-control/config.el

**Comment by Ptival** [comment]
Similar error when enabling haskell:

> In toplevel form:
> modules/lang/haskell/config.el:35:1:Error: featurep! was used incorrectly (doom--module wasn’t unset)
> Failed to compile modules/lang/haskell/config.el

**Comment by hlissner** [comment]
My bad, this was fixed in https://github.com/hlissner/doom-emacs/commit/42e7f56a1fb6fb9b0dc455e02ba0bc7f1bbac1a9 (in develop), and `develop` is far overdue for a merge. It'll happen this weekend.
