### ISSUE TITLE
[BUG] Terminal emacs dashboard screen: icon fonts not rendered correctly

### ISSUE THREAD

**Issue by randomizedthinking** [hlissner/doom-emacs#2200]
**What actually happened?**
Some fonts are not rendered correctly in the dashboard screen. Please see screenshots below.

(a) screenshot taken at commit 2019-12-16 **207ce02a3**
![image](https://user-images.githubusercontent.com/5283430/70952529-588c0a80-201b-11ea-8997-15b69d4bf313.png)

(b) screenshot taken at commit 2019-12-12 **5f2e708c**
![image](https://user-images.githubusercontent.com/5283430/70952481-32ff0100-201b-11ea-9465-db58b56e0630.png)

**Additional details:**
- Include screenshots/casts of your issue

Screenshots included. No error message, or anything particular in my config.

**Steps to reproduce:**
``` sh
cd ~/.emacs.d
git pull
doom refresh
emacs -nw
```

**System information:**
<details><pre>
emacs   version    26.3
        features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2
        build      Dec 09, 2019
        buildopts  (--with-modules --prefix=/usr/local)
        windowsys  nil
        daemonp    nil
doom    version    2.0.9
        build      HEAD -> develop 207ce02a3 2019-12-16 05:45:27 -0500
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/zsh
        uname      Linux 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2 (2019-08-28) x86_64
        path       (/usr/local/bin /usr/local/sbin /usr/bin /bin /usr/games /usr/lib/surfraw ~/.fzf/bin ~/02-computing/linux/bin ~/.local/bin ~/.emacs.d/bin /usr/local/libexec/emacs/26.3/x86_64-pc-linux-gnu)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company (ivy +fuzzy) :ui doom doom-dashboard hl-todo modeline nav-flash ophints (popup +all +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold (format +onsave) multiple-cursors rotate-text snippets :emacs dired electric vc :term eshell shell term :tools eval flycheck (lookup +docsets) lsp magit make :lang clojure data emacs-lisp ess markdown (org +dragndrop +ipython +pandoc +present) (python +lsp) sh :config (default +bindings +smartparens))
        packages   (fzf evil-terminal-cursor-changer lsp-python-ms command-log-mode jupyter)
        elpa       (n/a)
</pre></details>

**Comment by hlissner** [comment]
As of 11acc30 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by randomizedthinking** [comment]
Thanks a bunch... it works.

**Comment by randomizedthinking** [comment]
This issue resumes as of today's update: 18edebe9c.

**Comment by hlissner** [comment]
@randomizedthinking 4faa4e2 should fix this.
