### ISSUE TITLE
[HOWTO] Display continuously-updated word-count of an org-file

### ISSUE THREAD

**Issue by deshmukhs** [hlissner/doom-emacs#2201]
I want Doom Emacs to display in the mode-line a continuously updated word-count while editing an org-file.

I was expecting this to be default behavior because `doom-modeline-continuous-word-count-modes` is set to `markdown-mode, gfm-mode, org-mode`.

I have set `doom-modeline-enable-word-count` to t and sure, when I make a selection, mode-line displays the word-count.

The question is, how do I get the continuously updated word-count?

**System information**
<details><pre>
emacs   version    26.3
        features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2
        build      Aug 30, 2019
        buildopts  (--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-modules 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now)
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop, origin/develop, origin/HEAD 207ce02a3 2019-12-16 05:45:27 -0500
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/zsh
        uname      Linux 4.19.88-1-MANJARO #1 SMP PREEMPT Thu Dec 5 11:04:44 UTC 2019 x86_64
        path       (~/.local/bin/ /usr/local/bin/ /usr/local/sbin/ /usr/bin/ /usr/lib/jvm/default/bin/ /usr/bin/site_perl/ /usr/bin/vendor_perl/ /usr/bin/core_perl/ ~/texlive/2017/bin/x86_64-linux/ /usr/lib/emacs/26.3/x86_64-pc-linux-gnu/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold multiple-cursors rotate-text snippets :emacs dired electric ibuffer vc :tools (eval +overlay) flycheck (lookup +docsets) magit :lang data emacs-lisp markdown (org +dragndrop +ipython +pandoc +present) sh :config (default +bindings +smartparens))
        packages   <(doom-package-error (:core . packages) (void-function package!))>
        elpa       (n/a)
</pre></details>

**Comment by hlissner** [comment]
[doom-modeline](https://github.com/seagle0128/doom-modeline)'s `selection-info` segment only displays the word count when a selection is active. It's done this way because word-counting is generally expensive. As an evil user you can quickly select the buffer with `vig` (or the conventional `ggvG`).

Otherwise, you can either define your own segment with:

```elisp
(after! doom-modeline
  (doom-modeline-def-segment word-count
    "TODO"
    (when (eq major-mode 'org-mode)
      (format "% words" (count-words (point-min) (point-max)))))

  (doom-modeline-def-modeline 'main
    '(bar window-number matches buffer-info remote-host buffer-position selection-info word-count)
    '(objed-state misc-info persp-name irc mu4e github debug input-method buffer-encoding lsp major-mode process vcs checker)))
```

Or add it to `global-mode-string`:

```elisp
(add-hook! 'org-mode-hook
  (add-to-list (make-local-variable 'global-mode-string)
               '(:eval
                 (format "% words"
                         (count-words (point-min) (point-max))))))
```

Hope that helps!

**Comment by deshmukhs** [comment]
@hlissner  Thanks. I understood using ggvG to know the word-count. And adding `org-mode-hook` works perfectly. But then what does `doom-modeline-continuous-word-count-modes` do? From what I read, I thought it would give continuous word-count for specific modes.

**Comment by hlissner** [comment]
Oh! You're right. I wasn't aware `doom-modeline` had already implemented a `word-count` segment dedicated to displaying the word count. You can use it with the following:

```elisp
(after! doom-modeline
  (add-to-list 'doom-modeline-continuous-word-count-modes 'org-mode)

  (doom-modeline-def-modeline 'main
    '(bar window-number matches buffer-info remote-host buffer-position selection-info word-count)
    '(objed-state misc-info persp-name irc mu4e github debug input-method buffer-encoding lsp major-mode process vcs checker)))
```
