### ISSUE TITLE
[HOWTO] Override package sources with local directory

### ISSUE THREAD

**Issue by howsiwei** [hlissner/doom-emacs#2203]
**What are you trying to achieve?**

As per title. In my particular scenario, I was trying to use the `agda` module without cloning the entire [agda](https://github.com/agda/agda) repo. Since the required files already exist from homebrew installation, it would be nice to just point the package source location to the existing file location.

**What have you tried?**
Currently I just disable the `agda` module and use `use-package` as suggested in #1213. This works but doesn't come with all the  bells and whistles provided by the module.

**Additional information**
Related issues: #222, #1213, #1253, #1736

**System information**
<details><pre>
((emacs
  (version . "26.3")
  (features . "JPEG RSVG IMAGEMAGICK GLIB NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2")
  (build . "Aug 30, 2019")
  (buildopts "--disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus/26.3/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus/26.3 --with-xml2 --without-dbus --with-gnutls --with-imagemagick --with-modules --with-rsvg --with-ns --disable-ns-self-contained")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD 6ff31408e 2019-12-10 14:49:35 -0500"))
 (system
  (type . darwin)
  (config . "x86_64-apple-darwin18.5.0")
  (shell . "/usr/local/bin/zsh")
  (uname . "Darwin 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64")
  (path "/usr/local/Cellar/zplug/2.4.2/bin" "/usr/local/opt/zplug/bin" "~/bin" "~/sbin" "~/.local/bin" "/usr/local/bin" "/usr/bin" "/bin" "/usr/sbin" "/sbin" "/Library/TeX/texbin" "/opt/X11/bin" "/Applications/Wireshark.app/Contents/MacOS" "/usr/local/Cellar/emacs-plus/26.3/libexec/emacs/26.3/x86_64-apple-darwin18.5.0"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company ivy :ui doom-dashboard hl-todo modeline nav-flash (popup +all +defaults) pretty-code vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold multiple-cursors rotate-text snippets word-wrap :emacs dired electric ibuffer vc :term shell :tools (eval +overlay) flycheck (lookup +docsets) lsp macos magit :lang (cc +lsp) data emacs-lisp (latex +latexmk) markdown (org +dragndrop +ipython +pandoc +present) python sh :config (default +bindings +smartparens))
  (packages "(ccls :disable t)" solarized-theme)
  (elpa "s" "f" "dash")))
</pre></details>

**Comment by hlissner** [comment]
Try this: add the following to your `DOOMDIR/packages.el`:

```elisp
(package! agda-input :ignore t)
(package! agda2-mode :ignore t)
```

Then manually delete the packages from `~/.emacs.d/.local/straight/{build,repos}`, and add this to your `DOOMDIR/config.el`:

```elisp
(when (executable-find "agda-mode")
  (add-load-path!
    (file-name-directory (shell-command-to-string "agda-mode locate"))))

**Comment by howsiwei** [comment]
So the general strategy to override package source with local directory is to use `(package! <package-name> :ignore t)`?

It seems that adding `(require 'agda2)` to `DOOMDIR/config.el` is still required after the setup above. Is this the expected behavior?

Thanks a lot for your help!

**Comment by hlissner** [comment]
`(require 'agda2)` should not be necessary since the agda2-mode package has [autoloads](https://github.com/agda/agda/blob/master/src/data/emacs-mode/agda2-mode.el#L362-L363), meaning agda2-mode should be loaded when you open a `.l?agda` file.

If for some reason autoloads were not built for the package (probably due to its unconventional file structure), then I'll add `(require 'agda2)` to the module. Let me know.

**Comment by howsiwei** [comment]
I'm not sure why but yes, `(require 'agda2)` is needed.

**Comment by hlissner** [comment]
As of c473a7f this should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
