### ISSUE TITLE
Doom's Design Effort

### ISSUE THREAD

**Issue by MarioRicalde** [hlissner/doom-emacs#2204]
I've been working on an alternative interpretation of the project's name that is less obvious than the current one. 

Black Holes! ( Recommended video: https://www.youtube.com/watch?v=uD4izuDMUQA )

What I'd like this project to have:

- The brand is everything; let's make it a first-class citizen, whatever we go with, we stick to it.
- Splash Screen.
- Icon.
- Website.

I'm aware that this issue might be containing too much; however, it'd be good to get the conversation going and to lock the subject / vibe before going too deep into the rest. To get the ball rolling I bring the following:

![image](https://user-images.githubusercontent.com/125900/70988857-2fee2a00-2088-11ea-962f-b1565cbc9449.png)

**Comment by ar1a** [comment]
+1, good art and there has been a decent amount of support for veering off the demonic theme

really like the black hole svg

**Comment by lennertacke** [comment]
+1 love it!

**Comment by ekollof** [comment]
What the hell is wrong with Doom? (pun somewhat intended).

**Comment by barischrooneyj** [comment]
> What the hell is wrong with Doom? (pun somewhat intended).

Does something have to be wrong?

**Comment by paldepind** [comment]
I think the logo looks nice. But, I also think it looks more like a logo for Spacemacs than a logo for doom-emacs.

**Comment by PopeRigby** [comment]
I really disagree with moving away from the demonic theme. Doom is one of my favorite games, and I love having a piece of it in my editor. I also think the demonic stuff is fun, and fits the project.

**Comment by MarioRicalde** [comment]
@paldepind I see what you'd make that association; however, I disagree. I think that this is far enough from Spacemacs to have its own voice. It's not like we can't touch anything space-related because Spacemacs is the only Universe-themed game in town. 

@PopeRigby We're opposites in this. I disagree with staying with the demonic theme. Even though Doom is one of my favorite games too, I lean more towards having a cleaner more serious image for Doom that is as serious as the work that is going into it. As an attempt to make it more appealing for newcomers.

Of course this is only an idea. I invite you both to offer some ideas / proposals.

**Comment by njg** [comment]
As a doomer and as a physicist i'm down with it. 
I certainly would like to preserve the essential demonic character of doom however. 
Also, since we're discussing such crass stuff as brand identity, here's a [book](https://www.penguinrandomhouse.com/books/545019/we-have-no-idea-by-jorge-cham-and-daniel-whiteson/) and a [podcast](https://www.iheart.com/podcast/105-daniel-and-jorge-explain-t-29862087/) by a friend which will certainly be of interest at least to @MarioRicalde.

**Comment by PopeRigby** [comment]
> I lean more towards having a cleaner more serious image for Doom that is as serious as the work that is going into it. As an attempt to make it more appealing for newcomers.


I don't really see Doom as a super serious project, and that's not a bad thing. It's a relatively niche editor configuration, not a big editor meant for enterprise. I don't think a little bit of silliness is pushing away any newcomers.

**Comment by eylles** [comment]
![Screenshot at 2019-12-24 11-25-39](https://user-images.githubusercontent.com/33670677/71421431-686da500-2640-11ea-92a3-4389fa147245.png)

the project has already gained enough traction that a change of branding and character right now may end up doing more harm than good, add in that just less than a week ago DistroTube gave DOOM emacs a shoutout.

**Comment by MarioRicalde** [comment]
I give up on this issue. I don't have the longevity that some of you have in this project and I don't have the patience to go on a back and forth, if someone wants to lead this effort it should be @hlissner 

I'm more than happy to offer assistance, if needed. Until then, closing.

**Comment by KevOrr** [comment]
@MarioRicalde regardless of its place in DOOM, your logo is really cool. Do you have it available anywhere?

**Comment by alexslade** [comment]
If anyone else wants to use this, I've done a quick-and-dirty edit of @MarioRicalde's excellent image. Put it in your .doom.d folder and set the following in your init file: 

`(setq fancy-splash-image "~/.doom.d/black-hole.png")`

It's not the highest quality, but if you aren't on a hi-dpi display it looks decent. Fingers crossed that Mario can supply us with the source files :) 

![black-hole](https://user-images.githubusercontent.com/7713/81558554-cbf53680-9385-11ea-8db6-2dc6abe0c1ae.png)
