### ISSUE TITLE
[BUG] :lang csharp doctor assumes omnisharp

### ISSUE THREAD

**Issue by judemille** [hlissner/doom-emacs#2206]
**What did you expect to happen?**
...
The doctor for `:lang csharp` should only check based on `omnisharp` variables if `+lsp` is disabled

**What actually happened?**
...
The doctor has no checks, thus assuming it should check with OmniSharp, causing a doctor error when the doctor tries to run the C# check.

**Additional details:**
![image](https://user-images.githubusercontent.com/8127111/71028265-f8f53400-20da-11ea-97cf-fa53743151db.png)

**Comment by hlissner** [comment]
Sorry for the late response: as of e7f04a3 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
