### ISSUE TITLE
Errors about mu4e

### ISSUE THREAD

**Issue by Ptival** [hlissner/doom-emacs#221]
On master, with default init.example.el:

> Ignored modules/app/email/packages.el
> Cannot load mu4e: (file-error "Cannot open load file" "No such file or directory" "mu4e")
> Cannot load mu4e-maildirs-extension: (file-error "Cannot open load file" "No such file or directory" "mu4e")
> Cannot load org-mu4e: (file-error "Cannot open load file" "No such file or directory" "org-mu4e")
>

**Comment by hlissner** [comment]
This suggests that the three packages aren't installed. `mu4e-maildirs-extension` can be installed via `make install`, but `mu4e` and `org-mu4e` must be installed with `mu` through your OS's package manager. I assume you're a NixOS user, so: `nix-env -i mu` should do it, but I'm only guessing the package exists. I'm not terribly familiar with Nix.

For posterity:

+ On MacOS: `brew install mu --with-emacs`.
+ On Arch Linux: `pacman -S mu`
+ On Debian: `sudo apt-get install mu`

**Comment by Ptival** [comment]
Okay, thanks, I am indeed a NixOS user with minimal software installed by default. Will add `mu` to my list!

**Comment by hlissner** [comment]
No problem! I guess it's about time I write a README.org for app/email. Anyhow, I'll consider this resolved. Feel free to open if the issue returns.

**Comment by tasmo** [comment]
@hlissner I have the same problem again but have installed it already.

`type mu` gives the right path back.

In Spacemacs I had to set:

```lisp
   mu4e-mu-binary              "/run/current-system/sw/bin/mu"
   mu4e-installation-path      "/run/current-system/sw/share/emacs/site-lisp/mu4e"
```

In Doom Emacs this does not work. When I try to start app/email i get:
`=email: Cannot open load file: Not a directory, mu4e`
