### ISSUE TITLE
[BUG] Deft searches are case-sensitive

### ISSUE THREAD

**Issue by neildurant** [hlissner/doom-emacs#2211]
**What did you expect to happen?**
Run a Deft search using `M-x deft`, searching for a word that appears in org/md files with an upper-case letter, eg "Agenda", but enter the search term in lower-case, i.e. "agenda". This has always previously matched correctly for me, i.e. performing a case-insensitive search.

**What actually happened?**
No match found, unless I type in the search term with the exact correct case.

**Additional details:**
- No warnings appear in \*Messages\*
- Reproduced bug on Linux, but appears fine on Windows 10

**Steps to reproduce:**
1. Find a word that only appears once in files your `deft-directory`, with an initial upper case letter
2. Run `M-x deft`
3. Enter that word, but in lower-case
4. Observe the match is not found

**System information:**

<details><pre>
emacs   version    27.0.50
        features   XPM JPEG TIFF GIF PNG SOUND DBUS GSETTINGS GLIB NOTIFY INOTIFY GNUTLS FREETYPE HARFBUZZ XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS PDUMPER GMP
        build      Dec 17, 2019
        buildopts  ()
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop e6de13b4c 2019-12-17 23:31:10 -0500
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /usr/bin/fish
        uname      Linux 5.1.15-surface-linux-surface #8 SMP Thu Jun 27 12:03:55 EDT 2019 x86_64
        path       (~/.emacs.d.doom/bin/ ~/src/Tools/arcanist/bin/ /usr/local/bin/ ~/.local/bin/ /usr/local/sbin/ /usr/sbin/ /usr/bin/ /sbin/ /bin/ /usr/games/ /usr/local/games/ ~/.dotnet/tools/ ~/vmshared/src/Tools/arcanist/bin/ /usr/local/libexec/emacs/27.0.50/x86_64-pc-linux-gnu/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company ivy :ui deft doom doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold multiple-cursors rotate-text snippets :emacs dired electric ibuffer vc :term eshell shell :tools (eval +overlay) flycheck (lookup +docsets) magit make :lang csharp data emacs-lisp javascript markdown (org +dragndrop +ipython +pandoc +present) plantuml python sh :config (default +bindings +smartparens))
        packages   (dired-narrow free-keys bm default-text-scale doom-themes powershell omnisharp atomic-chrome ranger dired-hacks-utils dired-ranger dired-filter)
        elpa       (n/a)
</pre></details>

**Comment by neildurant** [comment]
Looks like it's a result of the recent "case-fold-search = nil" change in core/core.el (2f79fab99f523a6aaf761b36657762ffd8ef792b).

**Comment by ckruse** [comment]
Ah! *This* is why isearch is suddenly case sensitive

**Comment by hlissner** [comment]
As of fd3f5b5 this issue should be resolved. It was indeed the change to `case-fold-search`. I can anticipated some breakage; and had hoped packages would correctly rebind it lexically, but that was too naive and imposing, so it was reverted. Thanks for bringing it to my attention!
