### ISSUE TITLE
(wrong-number-of-arguments (3 . 3) 2) error when installing or updating haskell

### ISSUE THREAD

**Issue by qcfu-bu** [hlissner/doom-emacs#2213]
I'm trying to install the Haskell mode through doom.d init and I keep running into two consecutive lines of

`Eager macro-expansion failure: (wrong-number-of-arguments (3 . 3) 2)`
`Eager macro-expansion failure: (wrong-number-of-arguments (3 . 3) 2)`

when doom refresh attempts Installing & building packages. Quoting out haskell and refresh works normally.

The full debug message is quite long, not sure if posting that here will be of much help.

**Comment by jdnavarro** [comment]
Upstream issue: https://github.com/haskell/haskell-mode/issues/1691

**Comment by qcfu-bu** [comment]
Thank you, I'll close the issue

**Comment by hlissner** [comment]
I'll keep this open until it is resolved upstream.

**Comment by tchajed** [comment]
...and it's fixed upstream: https://github.com/haskell/haskell-mode/commit/38c512b8859c02fe13e11c558ef9feefee1674b4.

**Comment by hlissner** [comment]
Thank goodness. @tchajed Thanks for letting us know!

**Comment by asymmetric** [comment]
How do we recover from this error?

**Comment by tchajed** [comment]
You just need the latest version of the haskell-mode package. `doom update` should work for that.

**Comment by asymmetric** [comment]
`doom` update with the `haskell` module hits the error. If I remove the module, the package doesn't get updated.

**Comment by tchajed** [comment]
Then maybe manually do a `git pull` in `~/.emacs.d/.local/straight/repos/haskell-mode` followed by `doom refresh`?

You should also be able to remove `haskell`, refresh (which will delete the repo), and then add it back (which will clone it at the latest release), but that's a bit more complicated.

**Comment by asymmetric** [comment]
Thanks, `doom refresh -p` did the trick - a simple `refresh` doesn't purge orphaned repos.

**Comment by tchajed** [comment]
Ah, I didn't realize that (perhaps a change since I last needed to purge a repo). Glad you sorted that out!

So to summarize, the cleanest way to recover from a broken upstream package is to remove the relevant module from your config, delete the clone with `doom refresh -p`, then add it back to your config and run `doom refresh` to install it.

**Comment by hlissner** [comment]
@asymmetric That, or delete these two directories manually: `~/.emacs.d/.local/straight/{build,repos}/haskell-mode`
