### ISSUE TITLE
[BUG] Easymotion not loaded in org mode

### ISSUE THREAD

**Issue by ashiklom** [hlissner/doom-emacs#2218]
**What did you expect to happen?**

When I launch a fresh instance of doom emacs and open an org file, I should be able to use `evil-easymotion` bindings (`gs*`). The first time I run the easymotion binding, it should lazily load easymotion.

**What actually happened?**

The only available `gs` key sequence is `gsh` for `+org/goto-visible` -- `gs` is not autoloaded until I manually do `M-x +evil/easymotion`. After that the easymotion keys work as expected. This is _only_ a problem with `org-mode` files -- this works fine with any other file. Also, it's only an issue the first time `evil-easymotion` is loaded -- once it has been loaded, the keys work fine. 

**Additional details:**
- My private config: https://github.com/ashiklom/doom-config
- I am using doom's default keybindings for easymotion. Nothing else is bound with the prefix `gs`

**Steps to reproduce:**
1. Open a fresh instance of `doom emacs`.
2. Open an org file. (This has to be done _before_ any calls to `+evil/easymotion`).
3. Try to do any easymotion command (e.g. `gsj`)

(Possibly) related issues: #1672 #2192 #335.

**System information:**
<details><pre>
((emacs
  (version . "26.3")
  (features . "NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS")
  (build . "Sep 02, 2019")
  (buildopts "--with-ns '--enable-locallisppath=/Library/Application Support/Emacs/${version}/site-lisp:/Library/Application Support/Emacs/site-lisp' --with-modules")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop 6d40f30a0 2019-12-20 05:01:44 -0500"))
 (system
  (type . darwin)
  (config . "x86_64-apple-darwin18.2.0")
  (shell . "/bin/zsh")
  (uname . "Darwin 18.7.0 Darwin Kernel Version 18.7.0: Sun Dec  1 18:59:03 PST 2019; root:xnu-4903.278.19~1/RELEASE_X86_64 x86_64")
  (path "~/.zplug/repos/zplug/zplug/bin" "~/.zplug/bin" "~/.cargo/bin" "~/.nix-profile/bin" "/usr/local/bin" "/usr/bin" "/bin" "/usr/sbin" "/sbin" "/Library/TeX/texbin" "/opt/X11/bin" "~/.config/nvim/bundle/fzf/bin" "~/.local/bin" "~/Library/Python/3.7/bin" "~/Library/Python/2.7/bin" "." "~/.emacs.d/bin" "~/Library/Python/3.7/bin" "~/Library/Python/2.7/bin" "~/.emacs.d/bin" "/Applications/Emacs.app/Contents/MacOS/bin-x86_64-10_14" "/Applications/Emacs.app/Contents/MacOS/libexec-x86_64-10_14" "/Applications/Emacs.app/Contents/MacOS/libexec" "/Applications/Emacs.app/Contents/MacOS/bin"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold lispy multiple-cursors rotate-text snippets :emacs dired electric vc :term eshell :tools bibtex editorconfig eval flycheck flyspell (lookup +docsets) lsp macos magit :lang cc data emacs-lisp my-ess markdown (org +ipython +pandoc) polymode (python +lsp) sh web :config (default +bindings +smartparens))
  (packages dtrt-indent multi-line deadgrep pandoc-mode simpleclip)
  (elpa "n/a")))

</pre></details>

**Comment by ashiklom** [comment]
Commenting out this code fixes this bug. It seems like something about how this mapping is implemented negates the default mapping of `gs`, but I don't know enough about autoloading, laziness, and macros in Elisp to understand how. 🤷‍♂ 

https://github.com/hlissner/doom-emacs/blob/bff04ed35c794f5392d09a680842a201afaa6f66/modules/config/default/%2Bevil-bindings.el#L88-L90

**Comment by hlissner** [comment]
This is partially a regression, but also a resurfacing of a deeper issue, which was addressed in 27cabea. The issue should be resolved. Let me know if that isn't the case and I'll reopen the issue. Thanks for bringing it to my attention!

**Comment by ashiklom** [comment]
Works like a charm! Again, thanks for the near-instantaneous bugfix!
