### ISSUE TITLE
[BUG] Visual Glitches with emacsclient

### ISSUE THREAD

**Issue by Foldex** [hlissner/doom-emacs#2219]
**What actually happened?**
When connecting to an emacs daemon with emacsclient, I've run across two different instances of visual glitchiness.

1. Which-key's popup window seems to be getting cut off.
2. +workspace/kill-session runs successfully, but causes the dashboard to shift to the left.

Neither seem to happen when running doom without the daemon server.
I don't think either is a font related issue, as I've run doom without my personal config.el and both still occur.

**Additional details:**
![which-key](https://user-images.githubusercontent.com/47908676/71300165-85fcef00-2360-11ea-9c83-fd5ebf4aa8ec.png)
![dashboard](https://user-images.githubusercontent.com/47908676/71300167-86958580-2360-11ea-9ef4-b1a77a570c92.png)

**Steps to reproduce:**
1. Run emacs daemon and connect to it with emacsclient -c.
2. Hit space and wait for which-key to pop up
3. Note the cut off text at the bottom
4. M-x +workspace/kill-session
5. Note the dashboard shifts to the left

**System information:**
<details><pre>
emacs   version    26.3
        features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2
        build      Aug 29, 2019
        buildopts  (--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-modules 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now)
        windowsys  x
        daemonp    daemon
doom    version    2.0.9
        build      HEAD -> develop ebf3739cf 2019-12-20 14:04:15 -0500
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/zsh
        uname      Linux 5.3.13-arch1-1 #1 SMP PREEMPT Sun, 24 Nov 2019 10:15:50 +0000 x86_64
        path       (/usr/local/sbin/ /usr/local/bin/ /usr/bin/ ~/.scripts/ ~/.local/bin/ /usr/lib/jvm/default/bin/ /usr/bin/site_perl/ /usr/bin/vendor_perl/ /usr/bin/core_perl/ /usr/lib/emacs/26.3/x86_64-pc-linux-gnu/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo indent-guides modeline nav-flash neotree ophints (popup +all +defaults) pretty-code tabs vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold format multiple-cursors rotate-text snippets :emacs (dired +icons) electric (ibuffer +icons) vc :term vterm :tools debugger editorconfig (eval +overlay) flycheck flyspell (lookup +docsets) lsp magit pass pdf rgb :lang (cc +lsp) data emacs-lisp javascript markdown (org +dragndrop +ipython +pandoc +present) python sh web :email (mu4e +gmail) :app irc :config (default +bindings +smartparens))
        packages   (evil-lion ox-twbs)
        elpa       (n/a)
</pre></details>

**Comment by hlissner** [comment]
As of 1cb8ec6 and 0e4d25d this issue should be resolved. Let me know if that isn't the case and I'll reopen the thread. Thanks for bringing it to my attention!

**Comment by Foldex** [comment]
Unfortunately it seems like both are still occurring.

**Comment by hlissner** [comment]
Does adding `(setq window-resize-pixelwise nil)` to `~/.doom.d/init.el` fix the cut-off popup issue?

**Comment by Foldex** [comment]
Can't seem to get any combination of them to change anything.

It probably is worth noting that on one restart of the daemon, the the cutoff was seemingly gone, but came back on the next restart. Haven't been able to get it to come back though, so it might intermittently work?

**Comment by hlissner** [comment]
After some more digging, I believe I've finally found the causes, and have implemented a fix in 960f403 and 491e80a. Please update and let me know if they have resolved the issue.

**Comment by Foldex** [comment]
The dashboard issue is resolved. Thanks!
The text cutoff is more finnicky it seems though. It's fixed in doom's default font now, but setting doom-font to anything else seems to make it resurface.

**Comment by hlissner** [comment]
I believe it may be a combination of font size and `frame-resize-pixelwise`. If a frame is allowed to resize itself by the pixel, rather than by character width/height, then there's a possibility that the popup will always be off by 1 line.

Does `(setq frame-resize-pixelwise nil)` now?

**Comment by Foldex** [comment]
Having tried with a couple more fonts, still a nope.
The inconsistency of it is strange, as some fonts appeared to work fine, but trying them again led to the same result.

**Comment by Foldex** [comment]
Font issue seems to be resolved now, guess I'll close this.

**Comment by AlexLewandowski** [comment]
Just to chime in since which-key being cut off was bothering me too.

Setting `(setq window-resize-pixelwise nil)` fixes which-key being cut off.
