### ISSUE TITLE
[HOWTO] Get Rust Support

### ISSUE THREAD

**Issue by knosence** [hlissner/doom-emacs#2220]
**What are you trying to achieve?**
...
Rust Syntax highlighting and Rust support.

**What have you tried?**
...
New to emacs
Installed Rust, placed (require 'rust-mode) in config.el, googled getting rust support in emacs and doom emacs (information points towards (require 'rust-mode).

**Additional information**
- Do you have screenshots/casts of this workflow in another editor or Emacs
  distro? (If possible, include names of specific commands or functions from
  other editors/emacs distros)
- Do you have additional material or links to resources that could help clarify
  what you are trying to do?

**System information**
<details><pre>
Include the output of `M-x doom/info` or `~/.emacs.d/bin/doom info` here.
</pre></details>

**Comment by hlissner** [comment]
1. Enable the `:lang rust` module (see [docs/faq.org#how-do-i-enable-or-disable-a-doom-module](https://github.com/hlissner/doom-emacs/blob/develop/docs/faq.org#how-do-i-enable-or-disable-a-doom-module))
2. Run `doom refresh` on the command line.
3. Restart Emacs

Doom should now have rust support.

No need to `require` anything manually. Just comment/uncomment modules whose features you desire and you should be good to go.

**Comment by knosence** [comment]
Hey hlissner, 
Thanks for your help, I looked in init.el and didn't see rust selected. So I added it and ran 'doom refresh'. I just confirmed it works. Thank you!
