### ISSUE TITLE
[HOWTO] Enable LSP support for Ocaml

### ISSUE THREAD

**Issue by atmichalak** [hlissner/doom-emacs#2221]
**What did you expect to happen?**
...
Pass the +lsp flag to the ocaml language in init.el to use the ocaml-language-server in Tuareg Mode

**What actually happened?**
...
LSP: No LSP server for tuareg-mode(check *lsp-log*) 

**Additional details:**
- Include a link to your private config
- Include screenshots/casts of your issue
- If you mention key sequences, include what commands they're bound to (use `SPC
  h k KEY` or `C-h h k KEY` to inspect keys).
- Include any warnings or errors logged to \*Messages\* (use `M-x
  view-echo-area-messages` to see it).

<details><pre>
If an error message is involved include a backtrace of it.

How to acquire a backtrace:
https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#how-to-extract-a-backtrace-from-an-error
</pre></details>

**Steps to reproduce:**
1. Select these example steps,
2. Delete them,
3. And replace them with precise steps to reproduce your issue.
4. Fill in "system information" below.

**System information:**
<details><pre>
<details>

```
emacs   version    26.3
        features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LCMS2
        build      Nov 20, 2019
        buildopts  (--build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-dbus --with-gif --with-jpeg --with-png --with-rsvg --with-tiff --with-xft --with-xpm --with-x-toolkit=gtk3 --with-gpm=no --with-xwidgets --with-modules build_alias=x86_64-redhat-linux-gnu host_alias=x86_64-redhat-linux-gnu 'CFLAGS=-DMAIL_USE_LOCKF -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection' LDFLAGS=-Wl,-z,relro PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig)
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop ebf3739cf 2019-12-20 14:04:15 -0500
system  type       gnu/linux
        config     x86_64-redhat-linux-gnu
        shell      /usr/bin/zsh
        uname      Linux 5.3.16-300.fc31.x86_64 #1 SMP Fri Dec 13 17:59:04 UTC 2019 x86_64
        path       (~/.opam/4.07.1/bin ~/.nimble/bin ~/.rbenv/bin ~/.cargo/bin /usr/local/bin ~/.config ~/.local/bin ~/.nimble/bin ~/.rbenv/bin ~/.cargo/bin /usr/local/bin ~/.config ~/.local/bin ~/.cargo/bin /usr/local/bin /usr/bin /bin ~/bin /usr/local/sbin /usr/sbin)
config  envfile    nil
        elc-files  0
        modules    (:completion company helm :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) pretty-code treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold multiple-cursors rotate-text snippets :emacs dired electric ibuffer vc :tools (eval +overlay) flycheck (lookup +docsets) lsp magit :lang assembly (cc +lsp) crystal data emacs-lisp (go +lsp) (javascript +lsp) markdown nim (ocaml +lsp) (org +dragndrop +ipython +pandoc +present) (python +lsp) (ruby +lsp) (rust +lsp) (sh +lsp) :config (default +bindings +smartparens))
        packages   ((rtags :disable t))
        elpa       (n/a)
```
</details>
</pre></details>

**Comment by hlissner** [comment]
1. Please fill out the "system information" section of the issue template.

2. Did you run `doom refresh` on the command line after activating `:lang (ocaml +lsp)`?

**Comment by atmichalak** [comment]
I did run doom refresh upon adding (ocaml +lsp) but I still get the same error. The mode in the bottom right corner also shows Tuareg// instead of Tuareg (which is shown without +lsp modifier)

**Comment by hlissner** [comment]
If you open up a shell and run `which ocaml-language-server` and `which ocaml-lsp-server`, do either of these commands print out a path?

If so, then try running `~/.emacs.d/bin/doom env` to generate an envvar file (creates a snaptshot of your shell environment that doom will load at startup).

If neither do, then it would seem neither lsp server was successfully installed.

**Comment by atmichalak** [comment]
Upon reinstallation, ocaml-language-server does work but the ocaml-lsp-server does not, as it is also undergoing constant development. I'm sure once the package is officially on OPAM it will work as required.
