### ISSUE TITLE
[BUG] Disabling smartparens breaks evil--insert-newline

### ISSUE THREAD

**Issue by luisenrike** [hlissner/doom-emacs#2223]
After adding `smartparens` to the `disable-packages!` list, `evil--insert-newline` breaks.
I think it's because of the `require 'smartparens` inside the function:

```
(defun +evil--insert-newline (&optional above _noextranewline)
  (let ((pos (save-excursion (beginning-of-line-text) (point)))
        comment-auto-fill-only-comments)
    (require 'smartparens)
...
```

**What did you expect to happen?**
I could open a new line below `o`

**What actually happened?**
Got this error: `Cannot open load file: No such file or directory, smartparens`

**System information:**
<details><pre>
((emacs
  (version . "26.3")
  (features . "JPEG RSVG IMAGEMAGICK GLIB NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2")
  (build . "Aug 30, 2019")
  (buildopts "--disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus/26.3/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus/26.3 --with-xml2 --without-dbus --with-gnutls --with-imagemagick --with-modules --with-rsvg --with-ns --disable-ns-self-contained")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop ebf3739cf 2019-12-20 14:04:15 -0500"))
 (system
  (type . darwin)
  (config . "x86_64-apple-darwin18.5.0")
  (shell . "/bin/bash")
  (uname . "Darwin 18.7.0 Darwin Kernel Version 18.7.0: Sun Dec  1 18:59:03 PST 2019; root:xnu-4903.278.19~1/RELEASE_X86_64 x86_64")
  (path "~/.rvm/gems/ruby-2.6.5/bin" "~/.rvm/gems/ruby-2.6.5@global/bin" "~/.rvm/rubies/ruby-2.6.5/bin" "/usr/local/bin" "/usr/bin" "/bin" "/usr/sbin" "/sbin" "~/.rvm/bin" "~/.rvm/bin" "/usr/local/Cellar/emacs-plus/26.3/libexec/emacs/26.3/x86_64-apple-darwin18.5.0"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company (ivy +fuzzy +icons) :ui doom doom-dashboard doom-quit hl-todo indent-guides modeline nav-flash ophints treemacs vc-gutter vi-tilde-fringe :editor (evil +everywhere) file-templates fold rotate-text snippets :emacs (dired +icons) electric ibuffer vc :term term :tools (eval +overlay) flycheck (lookup +docsets) magit :lang data emacs-lisp javascript ledger markdown org (ruby +rvm) sh web :config (default +bindings))
  (packages "(smartparens :disable t)" all-the-icons-ivy dired-subtree "(evil-snipe :disable t)")
  (elpa "n/a")))
</pre></details>

**Comment by hlissner** [comment]
Do not disable core packages. If they are in core, the rest of Doom assumes they will always be available. Disable `smartparens-global-mode` instead:

```elisp
(after! smartparens
  (smartparens-global-mode -1)) 
```

I will look into making the package manager complain when core packages are disabled.

**Comment by luisenrike** [comment]
Good to know 👍
