### ISSUE TITLE
[REQUEST] Add a switch to bypass all prompts on 'doom upgrade'

### ISSUE THREAD

**Issue by PopeRigby** [hlissner/doom-emacs#2224]
Maybe something like `doom upgrade --yes`.

**Comment by hlissner** [comment]
Sadly, this isn't technically feasible at the moment. It already took [a few hacks](https://github.com/hlissner/doom-emacs/blob/develop/core/core-packages.el#L123-L178) to get straight to prompt at all (before, it would simply fail with an error, preventing folks from updating at all).

And these aren't simple yes/no confirmation prompts. There are different questions and different sets of answers depending on the problem. How a `--yes` would map to any of these answers is unclear. Perhaps we'll need a slew of new switches. I'll look into it when I can.

**Comment by PopeRigby** [comment]
I see. On another note, having a switch to bypass certain things would also be good. For example `--nodiff` to not ask for confirmation to view the diff, and just say no.

**Comment by hlissner** [comment]
To clarify, I'm talking about the prompts emitted by straight, like this one:

![image](https://user-images.githubusercontent.com/510883/71317189-68588400-244b-11ea-813e-2669dea3f811.png)

If you are talking about the `"See the differences between your current version of Doom and latest version in your browser? Yes/No"` and `"Upgrade Doom? Yes/No"` prompts, then a `--yes` switch already exists: `doom --yes upgrade`.

**Comment by PopeRigby** [comment]
Oh. Will I'll leave this up because the other thing is still an issue.

**Comment by hlissner** [comment]
As of f6852a2 the `doom upgrade` command now has a `--discard` switch, which will automatically select the options that discard local changes (private packages with a `:local-repo` will be skipped).

This should technically resolve the issue. Please update and let me know if that isn't the case.
