### ISSUE TITLE
[REQUEST] Kakoune editing support

### ISSUE THREAD

**Issue by BanchouBoo** [hlissner/doom-emacs#2231]
Support for editing in the style of [kakoune](https://github.com/mawww/kakoune/). There is currently [jmorag/kakoune.el](https://github.com/jmorag/kakoune.el), but it's nowhere near as complete an implementation of kakoune as evil is to vim. Perhaps it would be possible to build the functionality on top of evil instead, as kakoune is similar to vim.

**Comment by hlissner** [comment]
In case you haven't seen it, the `:editor objed` module offers a kakoune-esque paradigm. That said, I'm thinking these paradigms should be moved to external repos, or a third party doom modules repo, as I do not maintain them and I'd rather not have to support them, especially when they use an experimental implementation. As such, I will not be accepting new editing paradigm modules, and may likely move the ones we do have out at some point.

But do let me know if this idea comes to fruition. Once I've tied package versions to doom releases with lockfiles, I intend to add module management to `bin/doom`. This includes the ability to install remote modules. I'd happily include your module in a third-party section of the module index in docs/index.org, or however we end up organizing it.

For the time being, it's easy enough to simply clone a module to `~/.doom.d/modules/X/Y` and add `:X Y` to your `doom!` block.
