### ISSUE TITLE
[REQUEST] 

### ISSUE THREAD

**Issue by rezadiba** [hlissner/doom-emacs#2235]
**Describe the feature**
- If the feature involves new plugins, include links to them
- If the feature involves replacement of current functionality, how the new
  functionality is better?
- If the feature is implemented in another editor or Emacs distro, include:
  - Screenshots or screencasts of it
  - Links to its implementation
  - Names of relevant commands (and not only the keybinds to invoke them)

**System information**
<details><pre>
Place the output of `M-x doom/info` or `~/.emacs.d/bin/doom info` here.
</pre></details>

**Comment by rezadiba** [comment]
Hi

**Comment by hlissner** [comment]
I'm afraid the scope of this feature request is so far beyond my mortal capabilities that it encroaches on the realm of the divine, which the ancient ones prohibit. Their scorn is horror worth no task. And so I must turn down this request.

PS. hi yourself.

PPS. And Merry Christmas!
