### ISSUE TITLE
god-mode archived

### ISSUE THREAD

**Issue by MarioRicalde** [hlissner/doom-emacs#2236]
https://github.com/chrisdone/god-mode has been archived and is no longer under development, it's probably a good idea to remove it from Doom.

**Comment by hlissner** [comment]
Thanks for letting me know! I will remove it soon.

**Comment by hlissner** [comment]
@darth10 What do you think? Perhaps there's a better fork of god-mode that is still maintained out there?

**Comment by darth10** [comment]
I've reached out to @chrisdone to get ownership of god-mode transferred. Or else, I might just fork the repo and update the MELPA recipie.

**Comment by darth10** [comment]
I've created a PR to update the MELPA recipe :point_right: melpa/melpa#6642

**Comment by darth10** [comment]
god-mode is transferred to emacsorphanage and not archived now.
This issue can be closed.

**Comment by hlissner** [comment]
Thanks @darth10!
