### ISSUE TITLE
[HOWTO] Doom-Emacs without Evil mode

### ISSUE THREAD

**Issue by romatthe** [hlissner/doom-emacs#2240]
I realize plenty of people have asked this before, but I wasn't able to find a real "official" answer to this question. 

I've been maintaining my own Emacs configuration for quite a while now, and put quite a bit of effort into it, but I realize I'm never going to get a configuration as flat-out amazing as Doom.

I've been wanting to switch over to Doom for a very long time now, but every time I want to switch I struggle with how to deal with Evil. I'm not a Vimmer, and I don't think I'll ever be. What I want to do is reuse the amazing configuration effort of Doom, but stick with classic Emacs keys (and then configure them to my liking).

I realize this is very hard to maintain feature parity between these two modes, especially since Doom is essentially Henrik's personal configuration, but is there an "official" way to use Doom in the "classic" Emacs style? I would just love to use Doom, but I'm never going to get used to Modal editing.

**Comment by Renzix** [comment]
Yes you should be able to comment out the evil flag in .doom.d/init.el and run doom refresh.

**Comment by romatthe** [comment]
What about all the different packages that Doom includes? Would I then need to provide my own custom keybindings for each package? Or are there already non-evil keybindings provided?

**Comment by Renzix** [comment]
Basically all the packages should work. It also bind the leader key as C-c (same as when press space in evil mode).

Also see https://github.com/hlissner/doom-emacs/blob/develop/modules/editor/evil/README.org#removing-evil-mode

**Comment by romatthe** [comment]
Ah, I hadn't seen that document, sorry about that. I read through the quick start guide and didn't see any specific mention of Evil, so that's why I posted the question. Perhaps there should be a more clear mention of this in the main README or the quick start guide? Just a suggestion.

As a final question, from what I read at the document you linked here, I'd still need to setup my own keybindings quite a bit: 

> That means that much of Doom’s functionality will be orphaned in an evil-less setup. You’ll have to set your own keybinds.

Is there an easy way to figure out which keybindings I'd still be missing? Or should I go through each package I'd want to use one by one, and set up keybindings for myself? I'm fine with either scenario, I'm just looking for the quickest way to get started.

**Comment by romatthe** [comment]
Okay, so I'm still a little confused about this. I had a quick look at the source code, and it seems that disabling the `:editor evil` flag will still end up loading [+emacs-bindings.el](https://github.com/hlissner/doom-emacs/blob/develop/modules/config/default/%2Bemacs-bindings.el), correct? This still loads a ton of keybindings that I don't really like. Even navigation behaves rather differently in vanilla Doom with evil disabled.

Is there an easy way to get rid of all of these without overriding all of them? I really appreciate the hard work that has been put into them but I'd prefer starting from a clean vanilla emacs base in terms of keybindings, if that is at all possible.

**Comment by hlissner** [comment]
@romatthe All the default keybinds are provided by the `:config default` module. You can disable them by removing the `+bindings` flag from it in your `doom!` block (in `~/.doom.d/init.el`). Hope that helps!

**Comment by romatthe** [comment]
Awesome, yes, that helps a lot! Thank you!
