### ISSUE TITLE
[BUG] No org-babel-execute function for ledger!

### ISSUE THREAD

**Issue by luisenrike** [hlissner/doom-emacs#2241]
When I try to evaluate a ledger src block in org-mode

**What did you expect to happen?**
Evaluates the block

**What actually happened?**
Got this error: `org-babel-execute-src-block: No org-babel-execute function for ledger!`

**Steps to reproduce:**
1. Create a ledger src block in org

```
#+BEGIN_SRC ledger :cmdline bal
2019/12/24
    ACC:Some    $12
    ACC:BOM
#+END_SRC
```

2. Evaluate the block
`C-c C-c`

**System information:**
<details><pre>
emacs   version    26.3
        features   JPEG RSVG IMAGEMAGICK GLIB NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2
        build      Aug 30, 2019
        buildopts  (--disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus/26.3/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus/26.3 --with-xml2 --without-dbus --with-gnutls --with-imagemagick --with-modules --with-rsvg --with-ns --disable-ns-self-contained)
        windowsys  ns
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop 4ccfb8cf4 2019-12-24 15:11:54 -0500
        dir        ~/.doom.d/
system  type       darwin
        config     x86_64-apple-darwin18.5.0
        shell      /bin/bash
        uname      Darwin 18.7.0 Darwin Kernel Version 18.7.0: Sun Dec  1 18:59:03 PST 2019; root:xnu-4903.278.19~1/RELEASE_X86_64 x86_64
        path       (~/.rvm/gems/ruby-2.6.5/bin/ ~/.rvm/gems/ruby-2.6.5@global/bin/ ~/.rvm/rubies/ruby-2.6.5/bin/ ~/.rvm/bin/ /usr/local/bin/ /usr/bin/ /bin/ /usr/sbin/ /sbin/ ~/.rvm/bin/ /usr/local/Cellar/emacs-plus/26.3/libexec/emacs/26.3/x86_64-apple-darwin18.5.0/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company (ivy +fuzzy +icons) :ui doom doom-dashboard doom-quit hl-todo indent-guides modeline nav-flash ophints treemacs vc-gutter vi-tilde-fringe :editor (evil +everywhere) file-templates fold rotate-text snippets :emacs (dired +icons) electric ibuffer vc :term term :tools (eval +overlay) flycheck (lookup +docsets) magit :lang data emacs-lisp javascript ledger markdown org (ruby +rvm) sh web :config (default +bindings))
        packages   (all-the-icons-ivy dired-subtree ob-ledger (evil-snipe :disable t))
        elpa       (n/a)
</pre></details>

**Comment by hlissner** [comment]
As of 14c87e6 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by luisenrike** [comment]
Yes, that fixed it. Thanks for working on doom! 🎆
