### ISSUE TITLE
[BUG] "Symbol's function definition is void: +workspace+switch" when calling `=IRC`

### ISSUE THREAD

**Issue by romatthe** [hlissner/doom-emacs#2243]
**What did you expect to happen?**

I enabled to IRC module, refreshed my Doom installation with `bin/doom refresh`and ran `M-x =irc` in order to connect to IRC as described in the [module docs](https://github.com/hlissner/doom-emacs/tree/develop/modules/app/irc).

**What actually happened?**

I received the message:
> Symbol's function definition is void: +workspace+switch

This makes sense, **as I do not have the workspace module enabled**. Looking at the [the relevant code](https://github.com/hlissner/doom-emacs/blob/develop/modules/app/irc/autoload/irc.el#L17-L21), it seems no workspace is spawned when the universal argument is applied.

Calling `C-u M-x =irc` indeed works, and I'm able to continue using the IRC module.

I'm not very good at elisp at all, but having a quick glance at the good, if the universal argument is not passed, that would make `inhibit-workspace` `nil`. Therefore, looking at [the piece of code over here:](https://github.com/hlissner/doom-emacs/blob/develop/modules/app/irc/autoload/irc.el#L6-L7)

```elisp
  (unless inhibit-workspace
    (+workspace-switch +irc--workspace-name t))
```

Would this not call `+workspace-switch` regardless of the value of `(featurep! :ui workspaces)`?

**Comment by hlissner** [comment]
As of 436d36f this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
