### ISSUE TITLE
How do I get the same git gutter in Doom Emacs?

### ISSUE THREAD

**Issue by ianpan870102** [hlissner/doom-emacs#2246]
The git gutter on the left hand side looks amazing! I'm using my own configuration and would love to have the same visual effects. So far I'm using the diff-hl package but can't have it look as good as the indicators in doom emacs.
Which packages do I install and where can I find the corresponding configurations that you use?

**Comment by hlissner** [comment]
Doom users the git-gutter and git-gutter-fringe packages. They are configured [in the `:ui vc-gutter` module](https://github.com/hlissner/doom-emacs/blob/develop/modules/ui/vc-gutter/config.el).

You'll find the fringe bitmap definitions [at the bottom of the module's config.el](https://github.com/hlissner/doom-emacs/blob/develop/modules/ui/vc-gutter/config.el#L95-L111)

Hope that helps!

**Comment by ianpan870102** [comment]
@hlissner  Thanks for the reply! I'll close this issue and look into your answer.
