### ISSUE TITLE
[HOWTO] Add text below the banner

### ISSUE THREAD

**Issue by kayg04** [hlissner/doom-emacs#2250]
**What are you trying to achieve?**

I'm trying to add text below the banner in DOOM Dashboard like it's possible in [emacs-dashboard](https://github.com/emacs-dashboard/emacs-dashboard).

**What have you tried?**

Checked for variables with `SPC h v` that allow for that functionality but I couldn't find any.

**Comment by hlissner** [comment]
Check out `+doom-dashboard-functions` and the functions in it. It's a list of functions that are run in sequence to populate the dashboard.
