### ISSUE TITLE
[BUG] Top padding for banner doesn't work

### ISSUE THREAD

**Issue by kayg04** [hlissner/doom-emacs#2251]
**What did you expect to happen?**

Banner should be padded by the number of lines set in `+doom-dashboard-banner-padding`

**What actually happened?**

While padding set below the banner works, the same behaviour is not seen for top level padding.

**Additional details:**

[Relevant line in config](https://git.kayg.org/kayg/dotfiles/src/branch/master/.config/doom/config.el#L33)

![issue](https://user-images.githubusercontent.com/30401343/71461828-2318b700-27a9-11ea-80f4-0e46122c705e.png)

**Steps to reproduce:**
1. Add a banner image by setting `+doom-dashboard-banner-file`.
2. Set `+doom-dashboard-banner-padding` to a custom value.

**Comment by hlissner** [comment]
As of 934e4fc this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by kayg04** [comment]
That was wild. Let me quickly check and report back.
