### ISSUE TITLE
[BUG] Typescript mode not being activated when open .tsx files

### ISSUE THREAD

**Issue by testarossaaaaa** [hlissner/doom-emacs#2252]
**What did you expect to happen?**
Emacs activates typescript-mode for .tsx files

**What actually happened?**
Emacs activates fundamental mode for .tsx files and typescript mode for .ts files

**Additional details:**
- I use a vanilla installation of doom-emacs with the uncommented javascript and lsp modules
- No any warnings or errors logged to \*Messages\*
<img width="942" alt="image" src="https://user-images.githubusercontent.com/4533828/71470539-8de3e580-27dd-11ea-9be4-a45a441f87e9.png">
<img width="942" alt="image" src="https://user-images.githubusercontent.com/4533828/71470991-0bf4bc00-27df-11ea-91ff-f37007e62bb3.png">

**Steps to reproduce:**
1. Install doom-emacs 
2. Uncomment javascript and lsp modules
3. Run bin/doom refresh
4. Open file with .tsx extension

**System information:**
<details><pre>
emacs   version    26.3
        features   JPEG RSVG IMAGEMAGICK GLIB NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2
        build      Aug 30, 2019
        buildopts  (--disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus/26.3/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus/26.3 --with-xml2 --without-dbus --with-gnutls --with-imagemagick --with-modules --with-rsvg --with-ns --disable-ns-self-contained)
        windowsys  ns
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop 934e4fc06 2019-12-26 01:41:45 -0500
        dir        ~/.doom.d/
system  type       darwin
        config     x86_64-apple-darwin18.5.0
        shell      /bin/zsh
        uname      Darwin 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64
        path       (/usr/local/opt/node@10/bin/ /usr/local/opt/node@12/bin/ /usr/local/bin/ /usr/bin/ /bin/ /usr/sbin/ /sbin/ /usr/local/Cellar/emacs-plus/26.3/libexec/emacs/26.3/x86_64-apple-darwin18.5.0/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold multiple-cursors rotate-text snippets :emacs dired electric ibuffer vc :tools (eval +overlay) flycheck (lookup +docsets) lsp macos magit :lang data emacs-lisp javascript markdown (org +dragndrop +present) sh :config (default +bindings +smartparens))
        packages   (n/a)
        elpa       (n/a)
</pre></details>

**Comment by dubnev** [comment]
Hi @testarossaaaaa, you make this happen by adding the following to your `.doom.d/config.el`:
```elisp
(add-to-list 'auto-mode-alist '("\\.tsx\\'" . typescript-mode))
```
I'll defer to others on whether or not that should be default behavior.

**Comment by testarossaaaaa** [comment]
@dubnev Hello, thanks! It works. `.tsx` is the official typescript extension for working with JSX, so this should be the default behavior, just like in other editors.
https://www.typescriptlang.org/docs/handbook/jsx.html#basic-usage

**Comment by hlissner** [comment]
@testarossaaaaa [typescript-mode does not official support jsx/rsx](https://github.com/emacs-typescript/typescript.el/issues/4), so Doom associates *.tsx files with `web-mode` in the `:lang web` module instead. As of 5c45a9e we associate *.tsx with typescript-mode IF the `:lang web` module isn't enabled. To overcome this, you can use @dubnev's snippet.

Thanks for bringing it to my attention!
