### ISSUE TITLE
[BUG] Inserting dollar inserts the closing delimiter twice in LaTeX-mode

### ISSUE THREAD

**Issue by JSDurand** [hlissner/doom-emacs#2253]
**What did you expect to happen?**
In LaTeX-mode, when I insert a dollar, it inserts the delimiters from the variable `TeX-electric-math` and puts the cursor in between.

**What actually happened?**
It inserts the closing delimiter twice: e.g. it should insert `\(\)`, but it inserts `\(\)\)`.

**Additional details:**
- Include a link to your private config
[my .doom.d](https://github.com/JSDurand/.doom.d)
- Include screenshots/casts of your issue
![Capture d’écran 2019-12-26 à 17 40 01](https://user-images.githubusercontent.com/13595506/71470365-e2e82180-2806-11ea-8c0b-3bf41e8151df.png)

- If you mention key sequences, include what commands they're bound to (use `SPC
  h k KEY` or `C-h h k KEY` to inspect keys).
`TeX-insert-dollar`
- Include any warnings or errors logged to \*Messages\* (use `M-x
  view-echo-area-messages` to see it).
No errors or warning.

**Steps to reproduce:**
1. open sandbox,
2. enter the following,
```lisp
(require 'latex)
(setf TeX-electric-math '("\\(" . "\\)"))
(find-file "something.tex")
```
3. Run `C-c C-d`,
4. Then entering `$` in the sandboxed emacs results in `\(\)\)`.

**System information:**
<details><pre>
```
emacs   version    26.3
        features   JPEG RSVG IMAGEMAGICK DBUS GLIB NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2
        build      nov 21, 2019
        buildopts  (--disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus/26.3/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus/26.3 --with-xml2 --with-dbus --with-gnutls --with-imagemagick --with-modules --with-rsvg --without-pop --with-ns --disable-ns-self-contained)
        windowsys  ns
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop d00a0af92 2019-12-24 21:59:36 -0500
        dir        ~/.doom.d/
system  type       darwin
        config     x86_64-apple-darwin18.2.0
        shell      /usr/local/bin/zsh
        uname      Darwin 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64
        path       (~/.emacs.d/bin/ ~/.local/bin/ /usr/local/opt/texinfo/bin/ ~/.cargo/bin/ /usr/local/bin/ /usr/bin/ /bin/ /usr/sbin/ /sbin/ ~/Library/Haskell/bin/ /opt/X11/bin/ /Library/TeX/texbin/ ~/Library/Python/2.7/bin/ ~/Library/Python/3.6/bin/ /usr/local/Cellar/emacs-plus/26.3/libexec/emacs/26.3/x86_64-apple-darwin18.2.0/)
config  envfile    envvar-file
        elc-files  0
        modules    (:input chinese :completion company (ivy +childframe +fuzzy) durand-ivy :ui doom doom-dashboard durand-dashboard doom-quit hl-todo hydra modeline durand-modeline ophints (popup +all +defaults) :editor (evil +everywhere) file-templates durand-template durand-evil fold lispy snippets :emacs dired electric :term eshell :tools (eval +overlay) flycheck flyspell (lookup +dictionary +docsets) lsp magit pdf durand-pdf :lang (cc +lsp) data emacs-lisp javascript latex durand-tex markdown (org +dragndrop +pandoc +present) durand-org sh :email (mu4e +gmail) durand-mu :app calendar (rss +org) durand-rss :config (default +bindings +smartparens) durand-ideal)
        packages   ((evil-snipe :disable t) wrap-region (outline-magic :recipe (:host github :repo "tj64/outline-magic")) mu4e-alert)
        elpa       (wrap-region use-package undo-tree ts tablist s pdf-tools org-super-agenda org-plus-contrib org-pdfview mu4e-alert log4e ht goto-chg gntp evil-surround evil elfeed dash bind-key alert)
```
</pre></details>

**Comment by hlissner** [comment]
Doom uses `smartparens` to manage electrifying delimiters. Using `TeX-electric-math` is redundant and will cause duplicated delimiters, as you've observed.

Your only recourse is to either 

1. Stop using `TeX-electric-math` and [define additional smartparens rules](https://github.com/Fuco1/smartparens/wiki/Pair-management) for the latex modes, or

2. Disable smartparens mode in latex mode: `(add-hook 'TeX-mode-hook #'turn-off-smartparens-mode)`. If `TeX-mode-hook` doesn't work, try `LaTeX-mode-hook`, or `latex-mode-hook`.

**Comment by JSDurand** [comment]
Thanks. That explains the origin of the extra delimiter.
