### ISSUE TITLE
[BUG] doom--update-file fails when magit is enabled but the file is not in a git repo

### ISSUE THREAD

**Issue by dsdshcym** [hlissner/doom-emacs#2258]
**What did you expect to happen?**
Renaming file to a non-Git directory works

**What actually happened?**
`magit--not-inside-repository-error: Not inside Git repository`

<details>
stacktrace:
<pre>
(magit-outside-git-repo . "....")
  signal(magit-outside-git-repo "....")
  magit--not-inside-repository-error()
  magit-get-mode-buffer(magit-status-mode)
  magit-refresh()
  (progn (magit-refresh))
  (if (featurep 'magit) (progn (magit-refresh)))
  doom--update-file("....")
</pre></details>

**Steps to reproduce:**
1. open a file
2. call `doom/move-this-file` and move it to a directory that's not version controlled

**Comment by hlissner** [comment]
Does this resolve the issue?

```elisp
(defadvice! sandbox-magit-refresh (path)
  :override #'doom--update-file
  (when (featurep 'vc)
    (vc-file-clearprops path)
    (vc-resynch-buffer path nil t))
  (when (featurep 'magit)
    (let ((default-directory (file-name-directory path))
          (buffer-file-name path))
      (magit-refresh))))
```

**Comment by dsdshcym** [comment]
no, this doesn't fix the issue.

this fixes the issue but i'm not sure if `calling (magit-toplevel)` is too much here:
```
(defadvice! sandbox-magit-refresh (path)
  :override #'doom--update-file
  (when (featurep 'vc)
    (vc-file-clearprops path)
    (vc-resynch-buffer path nil t))
  (when (featurep 'magit)
    (if (magit-toplevel)
      (magit-refresh))))
```

**Comment by hlissner** [comment]
That bypasses the issue I'm trying to fix: we want to update the repo the file _used_ to be in.

Does this fix it? (Remove the old advice first)

```elisp
(defadvice! new-move-this-file (new-path &optional force-p)
  :override #'doom/move-this-file
  "Move current buffer's file to NEW-PATH. If FORCE-P, overwrite the destination
file if it exists, without confirmation."
  (interactive
   (list (read-file-name "Move file to: ")
         current-prefix-arg))
  (pcase (catch 'status
           (let ((old-path (buffer-file-name))
                 (new-path (expand-file-name new-path)))
             (when-let (dest (doom--copy-file old-path new-path force-p))
               (doom--forget-file old-path new-path)
               (when (file-exists-p old-path)
                 (delete-file old-path))
               (doom--update-file new-path)
               (kill-current-buffer)
               (find-file new-path)
               (message "File successfully moved to %s" dest))))
    (`overwrite-self (error "Cannot overwrite self"))
    (`aborted (message "Aborted"))
    (_ t)))
```

**Comment by dsdshcym** [comment]
> we want to update the repo the file used to be in.

then i think we should call `(doom--update-file old-path)` in `doom/move-this-file`?

The change above doesn't fix the issue, because the error was raised in `magit-refresh` when path is not in a git repo.
To fix the issue, I think we need to avoid calling `magit-refresh` in certain cases.

So, this one would fix the issue and update the old path:

```emacs-lisp
(defadvice! sandbox-magit-refresh (path)
  :override #'doom--update-file
  (when (featurep 'vc)
    (vc-file-clearprops path)
    (vc-resynch-buffer path nil t))
  (when (and (featurep 'magit) (magit-toplevel))
    (let ((default-directory (file-name-directory path))
          (buffer-file-name path))
      (magit-refresh)))))

(defadvice! new-move-this-file (new-path &optional force-p)
  :override #'doom/move-this-file
  "Move current buffer's file to NEW-PATH. If FORCE-P, overwrite the destination
file if it exists, without confirmation."
  (interactive
   (list (read-file-name "Move file to: ")
         current-prefix-arg))
  (pcase (catch 'status
           (let ((old-path (buffer-file-name))
                 (new-path (expand-file-name new-path)))
             (when-let (dest (doom--copy-file old-path new-path force-p))
               (when (file-exists-p old-path)
                 (delete-file old-path))
               (kill-current-buffer)
               (doom--forget-file old-path new-path)
               (doom--update-file old-path)
               (find-file new-path)
               (message "File successfully moved to %s" dest))))
    (`overwrite-self (error "Cannot overwrite self"))
    (`aborted (message "Aborted"))
    (_ t)))
```

**Comment by hlissner** [comment]
The goal is:

1. Run `magit-refresh` at old location's repo, _if_ it's in a repo and magit is open.
2. Run `magit-refresh` in new location's repo, _if_ it's in a repo and magit is open.

Running `doom--update-file` for both buffers would work, but we don't need to run the `vc` refresh logic there because the buffer's about to be killed anyway (and those process calls are expensive).

Also, magit-toplevel may be a good way to detect if we need to call magit at all. I'm fuzzy on the specifics and I'm a bit rushed at the moment. I'll look into this again over the holidays unless you want to take a stab at a PR.

**Comment by dsdshcym** [comment]
I'm not sure if I can achieve exactly what you want here, so I'll leave it to you. Sorry 🙏

**Comment by hlissner** [comment]
As of aad7961 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
