### ISSUE TITLE
Repository "melpa" has a merge conflict:

### ISSUE THREAD

**Issue by FirstLoveLife** [hlissner/doom-emacs#2259]
```
firstlove-pc% proxychains4 doom update
[proxychains] config file found: /etc/proxychains.conf
[proxychains] preloading /usr/lib/libproxychains4.so
[proxychains] DLL init: proxychains-ng 4.14
[proxychains] DLL init: proxychains-ng 4.14
[proxychains] DLL init: proxychains-ng 4.14
[proxychains] DLL init: proxychains-ng 4.14
[proxychains] DLL init: proxychains-ng 4.14
[proxychains] DLL init: proxychains-ng 4.14
[proxychains] DLL init: proxychains-ng 4.14
> Checking core autoloads file
  ✓ Skipping core autoloads, they are up-to-date
> Updating packages (this may take a while)...
  > Repository "melpa" has a merge conflict:
    [proxychains] DLL init: proxychains-ng 4.14

       1) Abort
       2) Abort merge

    How to proceed? (1, 2) ^C% 
```

What can I do? Is there any debug option when doom update?

**Comment by hlissner** [comment]
You'll have to resolve or abort the merge conflict by hand.

```sh
cd ~/.emacs.d/.local/straight/repos/melpa
git merge --abort

# If that's not enough
git reset --hard origin/master
```

**Comment by hlissner** [comment]
Is this still an issue?

**Comment by ruinshe** [comment]
Some investigation described below:

- when using `2 - Abort Merge`, it shows `fatal: There is no merge to abort (MERGE_HEAD missing)`.
- when the message shown, I try to access the folder and run `git ls-files --unmerged `, no dirty files shown.
- when I give up using proxychains, and use `all_proxy` environment variable, everything works well.

**Comment by hlissner** [comment]
This may be out of Doom's hands, if proxychains is to blame. Perhaps it should be mentioned on [straight](https://github.com/raxod502/straight.el), or [perhaps upstream](https://github.com/git/git/). I'm not knowledgeable enough on proxies to offer much insight into the matter, sorry to say.

**Comment by ruinshe** [comment]
Update the a tip for this bug, we can directly use `all_proxy` to skip proxychains in this case:

```
env all_proxy=socks://url-with-port .emacs.d/bin/doom upgrade
```

**Comment by FirstLoveLife** [comment]
Thanks for your help. I'll close this issue.
