### ISSUE TITLE
Changing colour of italicised text in org-mode?

### ISSUE THREAD

**Issue by kartik-ynwa** [hlissner/doom-emacs#226]
How would I go on about that? Right now it defaults to white which is okay with dark themes. But I use solarized light and it makes italic stuff illegible.

So far I have tried adding `custom-set-faces` to my private module and to the theme file I use but it doesn't work.

Thanks in advance.

**Comment by hlissner** [comment]
It sounds like you've used my private module as a base (i.e. copy-pasted).

If so, [these lines](https://github.com/hlissner/doom-emacs/blob/master/modules/private/hlissner/config.el#L37-L42) may be the culprit. You'll want to get rid of (or tweak) them.

**Comment by kartik-ynwa** [comment]
Yes that was it. I tried looking for something like that but missed it somehow. Thanks for your time.
