### ISSUE TITLE
[BUG]  Having some trouble with code navigation in c++-mode

### ISSUE THREAD

**Issue by vlurgio** [hlissner/doom-emacs#2260]
**What did you expect to happen?**
...
Jump to a definition with either `<SPC> c d` or `g d`

**What actually happened?**
...
get message `"variable name" c++ declaration not found

**Additional details:**
Both key sequences are just the stock command for lookup in any language. What's really odd is that `rtags-find-symbol-at-point` works fine. The lookup function is just not calling it. The c++-mode-hook also looks like rtags is being initiated. 
``` elisp
c++-mode-hook is a variable defined in cc-mode.el.gz.

Value
(+lookup--init-c++-mode-handlers-h
 #[0 "\300\301\302\303 #\207"
    [easy-menu-add-item nil
                        ("C++")
                        rtags-submenu-list]
    4]
 er/add-cc-mode-expansions
 +cc-fontify-constants-h
 +rotate-text-init-c++-mode-h
 +electric|init-c++-mode
 modern-c++-font-lock-mode
 +evil-embrace-angle-bracket-modes-hook-h
 +lookup|init--set-c++-mode)

```

**Steps to reproduce:**
1. open a cpp file
2. make sure `rdm` has your commands.json file indexed correctly
3. try to jump to a definition 

**System information:**
<details><pre>
```
emacs   version    26.2.90
        features   XPM JPEG TIFF GIF PNG SOUND DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS LUCID X11 XDBE XIM MODULES THREADS
        build      Aug 07, 2019
        buildopts  (--with-x --with-x-toolkit=lucid --with-modules --with-mailutils)
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop, origin/develop, origin/HEAD, _upgrade/develop 6ff31408e 2019-12-10 14:49:35 -0500
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/bash
        uname      Linux 5.3.0-24-generic #26-Ubuntu SMP Thu Nov 14 01:33:18 UTC 2019 x86_64
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company helm :ui deft doom doom-dashboard doom-quit hl-todo modeline nav-flash neotree ophints (popup +all +defaults) pretty-code treemacs unicode vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold (format +onsave) multiple-cursors rotate-text snippets :emacs (dired +ranger +icons) electric vc :term eshell vterm :tools debugger docker editorconfig ein eval flycheck (lookup +docsets) magit make tmux upload :lang cc data emacs-lisp ess go javascript latex ledger markdown (org +dragndrop +ipython +pandoc +present) (python +pyenv) rest sh web :config (default +bindings +smartparens))
        packages   (n/a)
        elpa       (n/a)
```

</pre></details>

**Comment by hlissner** [comment]
To figure out why, turn on debug mode (`SPC h d d`) and try `gd` again. If any errors occurred while running rtags, it should be logged to the \*Messages\* buffer (open it with `SPC h e`).

**Comment by vlurgio** [comment]
DOOM Looking up ’indicies’ with ’rtags-find-symbol-at-point’
DOOM [ui/doom-dashboard] Changed dashboard’s PWD to /projects/vector-storage/
I'm not sure it helps but this what the messages buffer puts out when pressing `g d` with the debugger on. So it looks like it is trying to look it up with rtags but no cursor jumping happens. (A small note I did notice it will jump to definitions within the same file. I'm guessing this is it falling back to dump-jump?) Just using `M-x` `rtags-find-symbol-at-point` continues to work though.

**Comment by hlissner** [comment]
Does this resolve the issue?

```elisp
(set-lookup-handlers! '(c-mode c++-mode) :async t
  :definition #'rtags-find-symbol-at-point
  :references #'rtags-find-references-at-point)
```

**Comment by vlurgio** [comment]
Yep, that did it thanks!

**Comment by vlurgio** [comment]
So this actually happened to me with java-mode using meghanada as well. If I use `meghanada-jump-declaration` it jumps fine and autocomplete works great as well. But if I use just `SPC c d` then it just falls back to full text search of the project.

**Comment by sophana** [comment]
> ```emacs-lisp
> (after! rtags
>   (set-lookup-handlers! '(c-mode c++-mode) :async t
>     :definition #'rtags-find-symbol-at-point
>     :references #'rtags-find-references-at-point))
> ```

Hi
I have the same problem, how do you use this code?
