### ISSUE TITLE
[HOWTO] I enabled lsp and (rust +lsp), doom will uninstall rust-mode, why then can't both exists?

### ISSUE THREAD

**Issue by locez** [hlissner/doom-emacs#2271]
**What did you expect to happen?**

I enabled lsp and `(rust +lsp)`, doom will uninstall rust-mode, why then can't both exists?

**System information:**
<details><pre>
Place the output of `M-x doom/info` or `~/.emacs.d/bin/doom info` here.
((emacs
  (version . "26.3")
  (features . "XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS GLIB NOTIFY ACL GNUTLS FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD LCMS2")
  (build . "Dec 30, 2019")
  (buildopts "--prefix=/usr --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu --mandir=/usr/share/man --infodir=/usr/share/info --datadir=/usr/share --sysconfdir=/etc --localstatedir=/var/lib --disable-silent-rules --docdir=/usr/share/doc/emacs-26.3-r1 --htmldir=/usr/share/doc/emacs-26.3-r1/html --libdir=/usr/lib64 --program-suffix=-emacs-26 --includedir=/usr/include/emacs-26 --infodir=/usr/share/info/emacs-26 --localstatedir=/var --enable-locallisppath=/etc/emacs:/usr/share/emacs/site-lisp --without-compress-install --without-hesiod --without-pop --with-file-notification=inotify --enable-acl --with-dbus --with-modules --without-gameuser --with-gpm --without-kerberos --without-kerberos5 --with-lcms2 --without-xml2 --with-mailutils --without-selinux --with-gnutls --with-libsystemd --with-threads --without-wide-int --with-zlib --with-sound=alsa --with-x --without-ns --with-gconf --with-gsettings --with-toolkit-scroll-bars --with-gif --with-jpeg --with-png --with-rsvg --with-tiff --with-xpm --with-imagemagick --with-xft --without-cairo --without-libotf --without-m17n-flt --with-x-toolkit=gtk3 --with-xwidgets 'CFLAGS=-march=native -O2 -pipe' CPPFLAGS= 'LDFLAGS=-Wl,-O1 -Wl,--as-needed'")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD e9b85997a 2019-12-27 03:33:12 -0500")
  (dir . "~/.doom.d/"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/bin/fish")
  (uname . "Linux 5.4.6-gentoo-locez #2 SMP Fri Dec 27 22:15:45 -00 2019 x86_64")
  (path "~/.local/bin" "~/.cargo/bin/" "~/go/bin" "/usr/lib/llvm/8/bin" "/usr/local/sbin" "/usr/local/bin" "/usr/sbin" "/usr/bin" "/sbin" "/bin" "/opt/bin" "/usr/libexec/emacs/26.3/x86_64-pc-linux-gnu"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :input chinese :completion (company +childframe) (ivy +icons +fuzzy) :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) pretty-code tabs treemacs vc-gutter vi-tilde-fringe (window-select +switch-window +numbers) workspaces :editor (evil +everywhere) file-templates fold multiple-cursors parinfer rotate-text snippets word-wrap :emacs dired electric ibuffer vc :term term :tools docker (eval +overlay) flycheck (lookup +docsets) lsp magit :lang data emacs-lisp (go +lsp) markdown (org +dragndrop +ipython +pandoc +present) (python +lsp) rest (ruby +lsp) (rust +lsp) sh :config (default +bindings +smartparens))
  (packages telega "(liberime-config :recipe (:host github :repo \"merrickluo/liberime\" :branch \"master\" :files (\"CMakeLists.txt\" \"Makefile\" \"src\" \"liberime-config.el\")))")
  (elpa "n/a")))
</pre></details>

**Comment by hlissner** [comment]
The `:lang rust` module doesn't use `rust-mode`, it uses [rustic-mode](https://github.com/brotzeit/rustic), a fork of `rust-mode`.

When `+lsp` is *not* enabled, the module uses `racer` to provide code completion, type info in the minibuffer (eldoc) and other features, but the racer package depends on `rust-mode`, so it must be installed (but doom still doesn't use it directly).
