### ISSUE TITLE
[HOWTO] load a package (simplenote2)

### ISSUE THREAD

**Issue by verajosemanuel** [hlissner/doom-emacs#2274]
I have no issue installing simplenote2 from melpa and working a while with their commands via M-x
But when exiting Doom and coming back in a while all disappeared. I can see the package is installed via M-x reinstall-package or listing packages but no command is available via M-x

I've included this in my config files:

**config.el**
(use-package simplenote2)

**packages.el**
(package! simplenote2)

how make package vailable when starting doom?
how to include some keybindings to most common simplenote2 functions?

**Comment by hlissner** [comment]
Doom has its own, declarative package manager. It does not use package.el. You'll find it documented here: https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#package-management

If you have a good reason not to use Doom's package manager, you'll have to initialize package.el yourself.

Otherwise:

```elisp
;; add to ~/.doom.d/packages.el
(package! simplenote2)
```

Then run `doom refresh` and restart Emacs.

**Comment by hlissner** [comment]
> how to include some keybindings to most common simplenote2 functions?

Press `SPC h f map\! RET` and you will get documentation on how to bind keys with the `map!` macro. Otherwise, you'll find [this entry in the manual on binding keys in elisp](https://www.gnu.org/software/emacs/manual/html_node/elisp/Key-Binding-Commands.html).

**Comment by verajosemanuel** [comment]
HI hlissner

> after adding this to ~/.doom.d/packages.el
> 
> (package! simplenote2)

that was done and no success so far

**Comment by hlissner** [comment]
> that was done and no success so far

Did you do the part I mentioned right after?

> Then run doom refresh and restart Emacs.

**Comment by hlissner** [comment]
I just did it myself.

1. Added `(package! simplenote2)` to `~/.doom.d/packages.el`
2. Ran `doom refresh` on the command line
3. Restarted Emacs
4. ![image](https://user-images.githubusercontent.com/510883/71579307-00004700-2aca-11ea-99d8-e9a677f7bc05.png)

**Comment by hlissner** [comment]
Check \*Messages\* for any errors/warnings that occurred at startup. You can open the messages buffer with `SPC h e` (or `C-h e`).

**Comment by verajosemanuel** [comment]
run doom refresh:

> Doom loaded 238 packages across 48 modules in 1.126s

restarted pc, no error in messages buffer  but unavailable commands from simplenote2

**Comment by hlissner** [comment]
Please provide the output of `M-x doom/info` (or `doom info` on the command line)

**Comment by hlissner** [comment]
Also, please include the output of `doom refresh`. You said:

> Doom loaded 238 packages across 48 modules in 1.126s

This is not the output of the `doom refresh` command. This is what the output should look like:

```
> Initiating a refresh of Doom Emacs...
  > (Re)generating core autoloads...
    > Generating core autoloads...
    > Byte-compiling core autoloads file...
    [32m✓ Generated .local/autoloads.elc[0m
  > Installing & building packages...
    [32m✓ No packages need to be installed[0m
  > (Re)building packages...
    [32m✓ No packages need rebuilding[0m
  > Purging orphaned packages (for the emperor)...
    - No builds to purge
    - Skipping elpa packages
    - Skipping repos
    - Skipping regrafting
  > (Re)generating package autoloads...
    > Generating package autoloads...
    > Byte-compiling package autoloads file...
    [32m✓ Generated .local/autoloads.pkg.elc[0m
  > Recompiling stale elc files...
    [32m✓ Recompiled 0/0 file(s) (180 ignored)[0m
[32m✓ Finished! (3.0213s)[0m
```

**Comment by verajosemanuel** [comment]
here:
`<details>

emacs   version    26.3
        features   XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK2 X11 XDBE XIM THREADS
        build      oct 14, 2019
        buildopts  ()
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop 6bb597564 2019-12-04 21:51:59 -0500
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /usr/bin/zsh
        uname      Linux 5.3.0-24-generic #26-Ubuntu SMP Thu Nov 14 01:33:18 UTC 2019 x86_64
        path       (~/.local/bin/ ~/bin/ /usr/local/mysql/bin/ /usr/local/sbin/ /usr/local/bin/ /usr/sbin/ /usr/bin/ /sbin/ /bin/ /usr/games/ /usr/local/games/ /snap/bin/ ~/.fzf/bin/ /usr/local/libexec/emacs/26.3/x86_64-pc-linux-gnu/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company helm ivy :ui neotree doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) pretty-code treemacs unicode vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold multiple-cursors rotate-text snippets :emacs dired electric ibuffer vc :tools docker (eval +overlay) flycheck gist (lookup +docsets) magit pass pdf :lang data emacs-lisp markdown (org +dragndrop +hugo +ipython +pandoc +pomodoro +present) python sh :app calendar (rss +org) twitter write :config (default +bindings +smartparens))
        packages   (n/a)
        elpa       (n/a)

</details>`

When I type " doom refresh" on command line, a Doom window is opened:
![doom refresh](https://user-images.githubusercontent.com/15836677/71580711-175b2680-2b02-11ea-8e01-f06130ded841.png)

**Comment by verajosemanuel** [comment]
solved removing chemacs profile for doom.
Seems that doom command was mapped to emacs executable

**Comment by hlissner** [comment]
Great! I'll consider this resolved then.
