### ISSUE TITLE
[REQUEST] projectile-rails

### ISSUE THREAD

**Issue by luisenrike** [hlissner/doom-emacs#2275]
https://github.com/asok/projectile-rails

**Comment by luisenrike** [comment]
I could make a PR if this is something you think we should have.

**Comment by hlissner** [comment]
Sure, I'll accept a PR for it.

I have far-off plans to remove projectile (and replace it with project.el) once we drop emacs 26 support -- but that's quite a while away; likely late 2021 or 2022 -- so I was conflicted about including it. That said, there doesn't seem to be any alternative to projectile-rails, so we'll cross that bridge when we get there.

**Comment by otavioschwanck** [comment]
projetile-rails is the only reason that i dont use doom emacs.  Would be very nice!
