### ISSUE TITLE
[BUG] entered--Lisp error: (void-function set-docsets!)

### ISSUE THREAD

**Issue by cxb811201** [hlissner/doom-emacs#2278]
**What did you expect to happen?**

**What actually happened?**

<details><pre>
Debugger entered--Lisp error: (void-function set-docsets!)
  (set-docsets! '(emacs-lisp-mode lisp-interaction-mode) "Emacs Lisp")
  (progn (set-repl-handler! '(emacs-lisp-mode lisp-interaction-mode) #'+emacs-lisp/open-repl) (set-eval-handler! '(emacs-lisp-mode lisp-interaction-mode) #'+emacs-lisp-eval) (set-lookup-handlers! 'emacs-lisp-mode :definition #'+emacs-lisp-lookup-definition :documentation #'+emacs-lisp-lookup-documentation) (set-docsets! '(emacs-lisp-mode lisp-interaction-mode) "Emacs Lisp") nil (set-rotate-patterns! 'emacs-lisp-mode :symbols '(("t" "nil") ("let" "let*") ("when" "unless") ("advice-add" "advice-remove") ("add-hook" "remove-hook") ("add-hook!" "remove-hook!") ("it" "xit") ("describe" "xdescribe"))) (progn (defalias 'doom--setq-tab-width-for-emacs-lisp-mode-h #'(lambda (&rest _) "tab-width = (or lisp-indent-offset 2)\n" (set (make-local-variable 'tab-width) (or lisp-indent-offset 2)))) (remove-hook 'emacs-lisp-mode-hook #'doom--setq-tab-width-for-emacs-lisp-mode-h) (add-hook 'emacs-lisp-mode-hook #'doom--setq-tab-width-for-emacs-lisp-mode-h) (defalias 'doom--setq-mode-name-for-emacs-lisp-mode-h #'(lambda (&rest _) "mode-name = \"Elisp\"" (set (make-local-variable 'mode-name) "Elisp"))) (remove-hook 'emacs-lisp-mode-hook #'doom--setq-mode-name-for-emacs-lisp-mode-h) (add-hook 'emacs-lisp-mode-hook #'doom--setq-mode-name-for-emacs-lisp-mode-h) (defalias 'doom--setq-outline-regexp-for-emacs-lisp-mode-h #'(lambda (&rest _) "outline-regexp = +emacs-lisp-outline-regexp" (set (make-local-variable 'outline-regexp) +emacs-lisp-outline-regexp))) (remove-hook 'emacs-lisp-mode-hook #'doom--setq-outline-regexp-for-emacs-lisp-mode-h) (add-hook 'emacs-lisp-mode-hook #'doom--setq-outline-regexp-for-emacs-lisp-mode-h)) (add-to-list 'doom-detect-indentation-excluded-modes 'emacs-lisp-mode nil #'eq) (advice-add #'elisp--company-doc-buffer :around #'doom-use-helpful-a) (progn (add-hook 'emacs-lisp-mode-hook #'+emacs-lisp-extend-imenu-h nil nil) (add-hook 'emacs-lisp-mode-hook #'highlight-quoted-mode nil nil) (add-hook 'emacs-lisp-mode-hook #'rainbow-delimiters-mode nil nil) (add-hook 'emacs-lisp-mode-hook #'outline-minor-mode nil nil)) (add-hook 'flycheck-mode-hook #'+emacs-lisp-reduce-flycheck-errors-in-emacs-config-h) (font-lock-add-keywords 'emacs-lisp-mode (append '(("^;;;###\\(autodef\\|if\\|package\\)[ \n]" (1 font-lock-warning-face t))) (if +emacs-lisp-enable-extra-fontification (progn '((+emacs-lisp-highlight-vars-and-faces . +emacs-lisp--face)))))) (advice-add #'elisp-def :after #'doom-recenter-a) (progn (general-define-key :major-modes t :prefix doom-localleader-alt-key :keymaps '(emacs-lisp-mode-map) "m" (list :def #'macrostep-expand :which-key "Expand macro")) (general-define-key :major-modes t :prefix doom-localleader-alt-key :keymaps '(emacs-lisp-mode-map) :infix "d" "" (list :ignore t :which-key "debug") "f" #'+emacs-lisp/edebug-instrument-defun-on "F" #'+emacs-lisp/edebug-instrument-defun-off) (general-define-key :major-modes t :prefix doom-localleader-alt-key :keymaps '(emacs-lisp-mode-map) :infix "e" "" (list :ignore t :which-key "eval") "b" #'eval-buffer "d" #'eval-defun "e" #'eval-last-sexp "r" #'eval-region "l" #'load-library) (general-define-key :major-modes t :prefix doom-localleader-alt-key :keymaps '(emacs-lisp-mode-map) :infix "g" "" (list :ignore t :which-key "goto") "f" #'find-function "v" #'find-variable "l" #'find-library)) t)
  (closure (t) nil (progn (set-repl-handler! '(emacs-lisp-mode lisp-interaction-mode) #'+emacs-lisp/open-repl) (set-eval-handler! '(emacs-lisp-mode lisp-interaction-mode) #'+emacs-lisp-eval) (set-lookup-handlers! 'emacs-lisp-mode :definition #'+emacs-lisp-lookup-definition :documentation #'+emacs-lisp-lookup-documentation) (set-docsets! '(emacs-lisp-mode lisp-interaction-mode) "Emacs Lisp") nil (set-rotate-patterns! 'emacs-lisp-mode :symbols '(("t" "nil") ("let" "let*") ("when" "unless") ("advice-add" "advice-remove") ("add-hook" "remove-hook") ("add-hook!" "remove-hook!") ("it" "xit") ("describe" "xdescribe"))) (progn (defalias 'doom--setq-tab-width-for-emacs-lisp-mode-h #'(lambda (&rest _) "tab-width = (or lisp-indent-offset 2)\n" (set (make-local-variable ...) (or lisp-indent-offset 2)))) (remove-hook 'emacs-lisp-mode-hook #'doom--setq-tab-width-for-emacs-lisp-mode-h) (add-hook 'emacs-lisp-mode-hook #'doom--setq-tab-width-for-emacs-lisp-mode-h) (defalias 'doom--setq-mode-name-for-emacs-lisp-mode-h #'(lambda (&rest _) "mode-name = \"Elisp\"" (set (make-local-variable ...) "Elisp"))) (remove-hook 'emacs-lisp-mode-hook #'doom--setq-mode-name-for-emacs-lisp-mode-h) (add-hook 'emacs-lisp-mode-hook #'doom--setq-mode-name-for-emacs-lisp-mode-h) (defalias 'doom--setq-outline-regexp-for-emacs-lisp-mode-h #'(lambda (&rest _) "outline-regexp = +emacs-lisp-outline-regexp" (set (make-local-variable ...) +emacs-lisp-outline-regexp))) (remove-hook 'emacs-lisp-mode-hook #'doom--setq-outline-regexp-for-emacs-lisp-mode-h) (add-hook 'emacs-lisp-mode-hook #'doom--setq-outline-regexp-for-emacs-lisp-mode-h)) (add-to-list 'doom-detect-indentation-excluded-modes 'emacs-lisp-mode nil #'eq) (advice-add #'elisp--company-doc-buffer :around #'doom-use-helpful-a) (progn (add-hook 'emacs-lisp-mode-hook #'+emacs-lisp-extend-imenu-h nil nil) (add-hook 'emacs-lisp-mode-hook #'highlight-quoted-mode nil nil) (add-hook 'emacs-lisp-mode-hook #'rainbow-delimiters-mode nil nil) (add-hook 'emacs-lisp-mode-hook #'outline-minor-mode nil nil)) (add-hook 'flycheck-mode-hook #'+emacs-lisp-reduce-flycheck-errors-in-emacs-config-h) (font-lock-add-keywords 'emacs-lisp-mode (append '(("^;;;###\\(autodef\\|if\\|package\\)[ \n]" (1 font-lock-warning-face t))) (if +emacs-lisp-enable-extra-fontification (progn '(...))))) (advice-add #'elisp-def :after #'doom-recenter-a) (progn (general-define-key :major-modes t :prefix doom-localleader-alt-key :keymaps '(emacs-lisp-mode-map) "m" (list :def #'macrostep-expand :which-key "Expand macro")) (general-define-key :major-modes t :prefix doom-localleader-alt-key :keymaps '(emacs-lisp-mode-map) :infix "d" "" (list :ignore t :which-key "debug") "f" #'+emacs-lisp/edebug-instrument-defun-on "F" #'+emacs-lisp/edebug-instrument-defun-off) (general-define-key :major-modes t :prefix doom-localleader-alt-key :keymaps '(emacs-lisp-mode-map) :infix "e" "" (list :ignore t :which-key "eval") "b" #'eval-buffer "d" #'eval-defun "e" #'eval-last-sexp "r" #'eval-region "l" #'load-library) (general-define-key :major-modes t :prefix doom-localleader-alt-key :keymaps '(emacs-lisp-mode-map) :infix "g" "" (list :ignore t :which-key "goto") "f" #'find-function "v" #'find-variable "l" #'find-library)) t))()
  #f(compiled-function () #<bytecode 0x15605b8cd721>)()
  funcall(#f(compiled-function () #<bytecode 0x15605b8cd721>))
  provide(elisp-mode)
  (progn (provide 'elisp-mode) (advice-remove #'emacs-lisp-mode #'doom--defer-feature-elisp-mode-a))
  (if (and emacs-lisp-mode-hook (not delay-mode-hooks)) (progn (provide 'elisp-mode) (advice-remove #'emacs-lisp-mode #'doom--defer-feature-elisp-mode-a)))
  doom--defer-feature-elisp-mode-a()
  apply(doom--defer-feature-elisp-mode-a nil)
  emacs-lisp-mode()
  set-auto-mode-0(emacs-lisp-mode nil)
  #f(compiled-function (&optional keep-mode-if-same) "Select major mode appropriate for current buffer.\n\nTo find the right major mode, this function checks for a -*- mode tag\nchecks for a `mode:' entry in the Local Variables section of the file,\nchecks if it uses an interpreter listed in `interpreter-mode-alist',\nmatches the buffer beginning against `magic-mode-alist',\ncompares the filename against the entries in `auto-mode-alist',\nthen matches the buffer beginning against `magic-fallback-mode-alist'.\n\nIf `enable-local-variables' is nil, or if the file name matches\n`inhibit-local-variables-regexps', this function does not check\nfor any mode: tag anywhere in the file.  If `local-enable-local-variables'\nis nil, then the only mode: tag that can be relevant is a -*- one.\n\nIf the optional argument KEEP-MODE-IF-SAME is non-nil, then we\nset the major mode only if that would change it.  In other words\nwe don't actually set it to the same mode the buffer already has." #<bytecode 0x1ff09bb6bcc7>)()
  apply(#f(compiled-function (&optional keep-mode-if-same) "Select major mode appropriate for current buffer.\n\nTo find the right major mode, this function checks for a -*- mode tag\nchecks for a `mode:' entry in the Local Variables section of the file,\nchecks if it uses an interpreter listed in `interpreter-mode-alist',\nmatches the buffer beginning against `magic-mode-alist',\ncompares the filename against the entries in `auto-mode-alist',\nthen matches the buffer beginning against `magic-fallback-mode-alist'.\n\nIf `enable-local-variables' is nil, or if the file name matches\n`inhibit-local-variables-regexps', this function does not check\nfor any mode: tag anywhere in the file.  If `local-enable-local-variables'\nis nil, then the only mode: tag that can be relevant is a -*- one.\n\nIf the optional argument KEEP-MODE-IF-SAME is non-nil, then we\nset the major mode only if that would change it.  In other words\nwe don't actually set it to the same mode the buffer already has." #<bytecode 0x1ff09bb6bcc7>) nil)
  #f(advice-wrapper :after #f(compiled-function (&optional keep-mode-if-same) "Select major mode appropriate for current buffer.\n\nTo find the right major mode, this function checks for a -*- mode tag\nchecks for a `mode:' entry in the Local Variables section of the file,\nchecks if it uses an interpreter listed in `interpreter-mode-alist',\nmatches the buffer beginning against `magic-mode-alist',\ncompares the filename against the entries in `auto-mode-alist',\nthen matches the buffer beginning against `magic-fallback-mode-alist'.\n\nIf `enable-local-variables' is nil, or if the file name matches\n`inhibit-local-variables-regexps', this function does not check\nfor any mode: tag anywhere in the file.  If `local-enable-local-variables'\nis nil, then the only mode: tag that can be relevant is a -*- one.\n\nIf the optional argument KEEP-MODE-IF-SAME is non-nil, then we\nset the major mode only if that would change it.  In other words\nwe don't actually set it to the same mode the buffer already has." #<bytecode 0x1ff09bb6bcc7>) auto-minor-mode-set)()
  apply(#f(advice-wrapper :after #f(compiled-function (&optional keep-mode-if-same) "Select major mode appropriate for current buffer.\n\nTo find the right major mode, this function checks for a -*- mode tag\nchecks for a `mode:' entry in the Local Variables section of the file,\nchecks if it uses an interpreter listed in `interpreter-mode-alist',\nmatches the buffer beginning against `magic-mode-alist',\ncompares the filename against the entries in `auto-mode-alist',\nthen matches the buffer beginning against `magic-fallback-mode-alist'.\n\nIf `enable-local-variables' is nil, or if the file name matches\n`inhibit-local-variables-regexps', this function does not check\nfor any mode: tag anywhere in the file.  If `local-enable-local-variables'\nis nil, then the only mode: tag that can be relevant is a -*- one.\n\nIf the optional argument KEEP-MODE-IF-SAME is non-nil, then we\nset the major mode only if that would change it.  In other words\nwe don't actually set it to the same mode the buffer already has." #<bytecode 0x1ff09bb6bcc7>) auto-minor-mode-set) nil)
  so-long--set-auto-mode(#f(advice-wrapper :after #f(compiled-function (&optional keep-mode-if-same) "Select major mode appropriate for current buffer.\n\nTo find the right major mode, this function checks for a -*- mode tag\nchecks for a `mode:' entry in the Local Variables section of the file,\nchecks if it uses an interpreter listed in `interpreter-mode-alist',\nmatches the buffer beginning against `magic-mode-alist',\ncompares the filename against the entries in `auto-mode-alist',\nthen matches the buffer beginning against `magic-fallback-mode-alist'.\n\nIf `enable-local-variables' is nil, or if the file name matches\n`inhibit-local-variables-regexps', this function does not check\nfor any mode: tag anywhere in the file.  If `local-enable-local-variables'\nis nil, then the only mode: tag that can be relevant is a -*- one.\n\nIf the optional argument KEEP-MODE-IF-SAME is non-nil, then we\nset the major mode only if that would change it.  In other words\nwe don't actually set it to the same mode the buffer already has." #<bytecode 0x1ff09bb6bcc7>) auto-minor-mode-set))
  apply(so-long--set-auto-mode #f(advice-wrapper :after #f(compiled-function (&optional keep-mode-if-same) "Select major mode appropriate for current buffer.\n\nTo find the right major mode, this function checks for a -*- mode tag\nchecks for a `mode:' entry in the Local Variables section of the file,\nchecks if it uses an interpreter listed in `interpreter-mode-alist',\nmatches the buffer beginning against `magic-mode-alist',\ncompares the filename against the entries in `auto-mode-alist',\nthen matches the buffer beginning against `magic-fallback-mode-alist'.\n\nIf `enable-local-variables' is nil, or if the file name matches\n`inhibit-local-variables-regexps', this function does not check\nfor any mode: tag anywhere in the file.  If `local-enable-local-variables'\nis nil, then the only mode: tag that can be relevant is a -*- one.\n\nIf the optional argument KEEP-MODE-IF-SAME is non-nil, then we\nset the major mode only if that would change it.  In other words\nwe don't actually set it to the same mode the buffer already has." #<bytecode 0x1ff09bb6bcc7>) auto-minor-mode-set) nil)
  set-auto-mode()
  normal-mode(t)
  #f(compiled-function (&optional error warn noauto after-find-file-from-revert-buffer nomodes) "Called after finding a file and by the default revert function.\nSets buffer mode, parses file-local and directory-local variables.\nOptional args ERROR, WARN, and NOAUTO: ERROR non-nil means there was an\nerror in reading the file.  WARN non-nil means warn if there\nexists an auto-save file more recent than the visited file.\nNOAUTO means don't mess with auto-save mode.\nFourth arg AFTER-FIND-FILE-FROM-REVERT-BUFFER is ignored\n(see `revert-buffer-in-progress-p' for similar functionality).\nFifth arg NOMODES non-nil means don't alter the file's modes.\nFinishes by calling the functions in `find-file-hook'\nunless NOMODES is non-nil." #<bytecode 0x1ff09bb7ff85>)(nil nil t nil nil)
  apply(#f(compiled-function (&optional error warn noauto after-find-file-from-revert-buffer nomodes) "Called after finding a file and by the default revert function.\nSets buffer mode, parses file-local and directory-local variables.\nOptional args ERROR, WARN, and NOAUTO: ERROR non-nil means there was an\nerror in reading the file.  WARN non-nil means warn if there\nexists an auto-save file more recent than the visited file.\nNOAUTO means don't mess with auto-save mode.\nFourth arg AFTER-FIND-FILE-FROM-REVERT-BUFFER is ignored\n(see `revert-buffer-in-progress-p' for similar functionality).\nFifth arg NOMODES non-nil means don't alter the file's modes.\nFinishes by calling the functions in `find-file-hook'\nunless NOMODES is non-nil." #<bytecode 0x1ff09bb7ff85>) (nil nil t nil nil))
  (if (setq doom-large-file-p (and buffer-file-name (not doom-large-file-p) (file-exists-p buffer-file-name) (> (nth 7 (file-attributes buffer-file-name)) (* 1024 1024 (assoc-default buffer-file-name doom-large-file-size-alist #'string-match-p))))) (prog1 (apply orig-fn args) (if (memq major-mode doom-large-file-excluded-modes) (setq doom-large-file-p nil) (if (fboundp 'so-long-minor-mode) (progn (so-long-minor-mode 1))) (message "Large file detected! Cutting a few corners to impr..."))) (apply orig-fn args))
  doom--optimize-for-large-files-a(#f(compiled-function (&optional error warn noauto after-find-file-from-revert-buffer nomodes) "Called after finding a file and by the default revert function.\nSets buffer mode, parses file-local and directory-local variables.\nOptional args ERROR, WARN, and NOAUTO: ERROR non-nil means there was an\nerror in reading the file.  WARN non-nil means warn if there\nexists an auto-save file more recent than the visited file.\nNOAUTO means don't mess with auto-save mode.\nFourth arg AFTER-FIND-FILE-FROM-REVERT-BUFFER is ignored\n(see `revert-buffer-in-progress-p' for similar functionality).\nFifth arg NOMODES non-nil means don't alter the file's modes.\nFinishes by calling the functions in `find-file-hook'\nunless NOMODES is non-nil." #<bytecode 0x1ff09bb7ff85>) nil nil t nil nil)
  apply(doom--optimize-for-large-files-a #f(compiled-function (&optional error warn noauto after-find-file-from-revert-buffer nomodes) "Called after finding a file and by the default revert function.\nSets buffer mode, parses file-local and directory-local variables.\nOptional args ERROR, WARN, and NOAUTO: ERROR non-nil means there was an\nerror in reading the file.  WARN non-nil means warn if there\nexists an auto-save file more recent than the visited file.\nNOAUTO means don't mess with auto-save mode.\nFourth arg AFTER-FIND-FILE-FROM-REVERT-BUFFER is ignored\n(see `revert-buffer-in-progress-p' for similar functionality).\nFifth arg NOMODES non-nil means don't alter the file's modes.\nFinishes by calling the functions in `find-file-hook'\nunless NOMODES is non-nil." #<bytecode 0x1ff09bb7ff85>) (nil nil t nil nil))
  after-find-file(nil nil t nil nil)
  revert-buffer--default(t nil)
  revert-buffer(t)
  funcall-interactively(revert-buffer t)
  call-interactively(revert-buffer nil nil)
  command-execute(revert-buffer)

</pre></details>

**Steps to reproduce:**
1. Select these example steps,
2. Delete them,
3. And replace them with precise steps to reproduce your issue.
4. Fill in "system information" below.

**System information:**
<details><pre>
((emacs
  (version . "28.0.50")
  (features . "XPM JPEG TIFF GIF PNG RSVG CAIRO IMAGEMAGICK SOUND GPM DBUS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER LCMS2 GMP")
  (build . "Dec 30, 2019")
  (buildopts "--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --mandir=/usr/share/man --with-gameuser=:games --with-sound=alsa --with-modules --without-gconf --without-gsettings --enable-link-time-optimization --with-x-toolkit=gtk3 --without-xaw3d --without-m17n-flt --with-imagemagick --with-cairo --with-xwidgets --without-compress-install 'CFLAGS=-march=ivybridge -O2 -pipe -fno-plt -g -flto -fuse-linker-plugin -s -fuse-ld=gold' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD 3271cd3a5 2019-12-30 18:08:11 -0500")
  (dir . "~/.doom.d/"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/usr/bin/zsh")
  (uname . "Linux 5.4.6 #1 SMP PREEMPT Mon Dec 23 12:01:48 CST 2019 x86_64")
  (path "~/.gem/ruby/2.6.0/bin" "~/.go/bin" "~/.cargo/bin" "~/.jenv/shims" "~/.jenv/bin" "~/.emacs.d/bin" "~/.local/bin" "~/.nvm/versions/node/v13.4.0/bin" "/usr/local/bin" "/usr/local/sbin" "/usr/bin" "/usr/lib/jvm/default/bin" "/usr/bin/site_perl" "/usr/bin/vendor_perl" "/usr/bin/core_perl" "~/.antigen/bundles/robbyrussell/oh-my-zsh/lib" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/git" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/gitfast" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/git-remote-branch" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/colored-man-pages" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/history" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/z" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/extract" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/encode64" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/web-search" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/urltools" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/tmux" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/docker" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/docker-compose" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/archlinux" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/cargo" "~/.antigen/bundles/djui/alias-tips" "~/.antigen/bundles/zdharma/fast-syntax-highlighting" "~/.antigen/bundles/zsh-users/zsh-autosuggestions" "~/.antigen/bundles/hlissner/zsh-autopair" "~/.antigen/bundles/romkatv/powerlevel10k" "/usr/lib/emacs/28.0.50/x86_64-pc-linux-gnu"))
 (config
  (envfile)
  (elc-files . 0)
  (modules :input chinese :completion company (ivy +prescient +fuzzy +childframe) :ui doom doom-quit hl-todo hydra modeline nav-flash ophints (popup +all +defaults) treemacs vc-gutter (window-select +numbers) workspaces centered-cursor :editor file-templates lispy multiple-cursors rotate-text snippets :emacs (dired +ranger) electric (ibuffer +icons) vc :term eshell :tools docker editorconfig (eval +overlay) (flycheck +childframe) lookup lsp magit (youdao +childframe) :lang data emacs-lisp (go +lsp) (java +lsp) (javascript +lsp) (kotlin +lsp) markdown (org +brain +dragndrop +hugo +ipython +pandoc +present +pomodoro +journal) plantuml rest (scala +lsp) sh (web +lsp) :config (default +bindings +smartparens))
  (packages "(fcitx :disable t)" "(pangu-spacing :disable t)" "(tide :disable t)" "(liberime-config :recipe (:host github :repo \"merrickluo/liberime\" :files (\"liberime-config.el\" \"src\" \"CMakeLists.txt\" \"Makefile\")))" "(company-english-helper :recipe (:host github :repo \"cxb811201/company-english-helper\"))" "(insert-translated-name :recipe (:host github :repo \"manateelazycat/insert-translated-name\"))" cal-china-x exec-path-from-shell hungry-delete "(go-impl :recipe (:host github :repo \"cxb811201/emacs-go-impl\"))" go-fill-struct sqlup-mode dap-mode)
  (elpa "n/a")))
</pre></details>

**Comment by hlissner** [comment]
Did you try `doom refresh`?

**Comment by cxb811201** [comment]
> Did you try `doom refresh`?

After I delete the autoload related files in the  .local directory, and then execute `doom refresh` again, I still have this problem

**Comment by hlissner** [comment]
Ah, it turns out this is a regression from f8ff50565. As of 7c968a8 this should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
