### ISSUE TITLE
[HOWTO] Disable rainbow-delimiters

### ISSUE THREAD

**Issue by aidermoi** [hlissner/doom-emacs#2280]
**What are you trying to achieve?**
Trying to disable rainbow-delimiters and use a different parentheses highlighter.

**What have you tried?**
I have set package.el to:
(package! rainbow-delimiters :disable t)
and doom refresh.

Now, I am getting this warning/error if I open up my C++ file:
File mode specification error: (void-function rainbow-delimiters-mode)

May I know if there is a more elegant way of disabling rainbow-delimiters? I could not find and reference of doing so. Thanks!

**Comment by hlissner** [comment]
You should not disable core packages with `package!`. If they are in core, the rest of Doom assumes it is always present. Instead, remove `rainbow-delimiters-mode` from `c-mode-common-hook`:

```lisp
(after! cc-mode
  (remove-hook 'c-mode-common-hook #'rainbow-delimiters-mode))
```

I will be moving some of these packages into modules soon.

**Comment by aidermoi** [comment]
Thanks for pointing this out! I am trying to migrate some of my settings from my vanilla Emacs setup to doom. Really like doom-emacs so far!
I have another 2 questions during the migrate process.

1. What is the recommended way for dynamically choose whether to load a module?
e.g. Only load doom's modeline if running in GUI. Otherwise, use some other modeline package.
The only way I can think of currently is to disable the module, and declare and configure the doom-modeline package manually. But, I guess that will lose some stuff in the modeline module?

2. After enabling vterm module and load up a terminal, my modeline disappears for the terminal buffer. Is it by design?

Thanks again!

**Comment by hlissner** [comment]
> What is the recommended way for dynamically choose whether to load a module?

It depends on the condition. Whenever your module list (i.e. `doom!` block) changes, you have to run `doom sync` (same as `doom refresh`). If the condition could change from startup-to-startup, without running `doom sync`, then it won't work.

If the condition are more stable, e.g. what OS you're on, or what version of Emacs you're running, you can use `:if`, `:when`, `:unless` and `:cond` [as demonstrated here](https://github.com/hlissner/doom-emacs/blob/develop/docs/api.org#doom).

> Only load doom's modeline if running in GUI. Otherwise, use some other modeline package.

In this case, you could add this to your `~/.doom.d/config.el`:

```elisp
(unless (display-graphic-p)
  (remove-hook 'after-init-hook #'doom-modeline-mode))
```

> After enabling vterm module and load up a terminal, my modeline disappears for the terminal buffer. Is it by design?

[Yes](https://github.com/hlissner/doom-emacs/blob/develop/modules/term/vterm/config.el#L16). To reverse this:

```elisp
(after! vterm
  (remove-hook 'vterm-mode-hook #'hide-mode-line-mode))
```

**Comment by aidermoi** [comment]
Thanks for helping out~ Happy new year!
