### ISSUE TITLE
[BUG] Chinese IME name is not normally displayed in doom-modeline

### ISSUE THREAD

**Issue by cxb811201** [hlissner/doom-emacs#2281]
**What did you expect to happen?**

**What actually happened?**

**Additional details:**
![image](https://user-images.githubusercontent.com/2104470/71637938-55845180-2c8c-11ea-9c6f-906df29919d6.png)

**Comment by cxb811201** [comment]
Before f8ff505, it can display normally

**Comment by cnsunyour** [comment]
since `f8ff50565ebf5ffeeac1a332715c39147894ac0f`, all Chinese are converted to utf-8 code string, so the wrong IME name is displayed.
The screenshot is a code snippet of autoload.pkg.el
![image](https://user-images.githubusercontent.com/3713312/71638775-0cd89280-2ca4-11ea-8177-6ee6e018fef1.png)

**Comment by hlissner** [comment]
As of 4a53f08 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
