### ISSUE TITLE
[BUG] org-refile may paste the wrong item on emacsclient -t

### ISSUE THREAD

**Issue by oblitzitate** [hlissner/doom-emacs#2282]
**What did you expect to happen?**
Calling `org-refile` on an item should delete it and refile (paste) it under the new position.

**What actually happened?**
Sometimes it works fine, especially on first try.

But other times, calling `org-refile` on an item will delete it just fine but will paste the **wrong item** (usually the second-last deleted, rather than the last deleted) under the new position.  This seems to only occur on `emacsclient -t` and not GUI emacs.

Sometimes the initial call of `org-refile` may spit out an error, something like:

> The kill is not a set of tree(s)

**Additional details:**
- Using vanilla doom

Refiling item 2:
![2020-01-01-020757_267x217_scrot](https://user-images.githubusercontent.com/56560015/71639172-c81b1000-2c3f-11ea-864a-f63cf99146df.png)
Below should paste "item 2" at the bottom rather than "item 1"
![2020-01-01-020810_223x170_scrot](https://user-images.githubusercontent.com/56560015/71639175-d0734b00-2c3f-11ea-8a74-e1379cbd66a9.png)

**Steps to reproduce:**
1. Run `emacsclient -t file.org`
2. Call `org-refile` on an item and refile it
3. If working fine, restart `emacs --daemon` or try on another org file
4. Call `org-refile` again

**System information:**
<details><pre>
((emacs
  (version . "26.3")
  (features . "XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2")
  (build . "Aug 29, 2019")
  (buildopts "--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-modules 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop 69a7c60c3 2019-12-31 17:46:53 -0500")
  (dir . "~/.doom.d/"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/bin/bash")
  (uname . "Linux 4.14.160-1-MANJARO #1 SMP PREEMPT Sat Dec 21 11:56:33 UTC 2019 x86_64")
  (path "~/.emacs.d/bin" "~/.cargo/bin" "~/bin" "~/.local/bin" "/usr/local/bin" "/usr/bin" "/bin" "/usr/local/sbin" "/usr/lib/jvm/default/bin" "/usr/bin/site_perl" "/usr/bin/vendor_perl" "/usr/bin/core_perl" "~/.gem/ruby/2.6.0/bin" "/usr/lib/emacs/26.3/x86_64-pc-linux-gnu"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold multiple-cursors rotate-text snippets :emacs dired electric ibuffer vc :tools (eval +overlay) flycheck (lookup +docsets) magit :lang data emacs-lisp markdown (org +dragndrop +pomodoro +present) sh :config (default +bindings +smartparens))
  (packages "n/a")
  (elpa "n/a")))
</pre></details>

**Comment by oblitzitate** [comment]
Same issue occurs with `org-copy` so it seems to be a kill ring issue.

Also I tried to get a backtrace when "the kill is a set of trees" occured but no window popped up. Had `toggle-debug-on-error` enabled.

**Comment by hlissner** [comment]
It seems I can't reproduce this. If it is a kill-ring issue, do either of these change the situation?

```lisp
;; add to ~/.doom.d/config.el
(setq save-interprogram-paste-before-kill nil)
```

or

```lisp
(remove-hook 'tty-setup-hook #'doom-init-clipboard-in-tty-emacs-h)
```

**Comment by oblitzitate** [comment]
Ah, adding either one of those seems to have fixed the issue.

**Comment by hlissner** [comment]
As of 8f5977d this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
