### ISSUE TITLE
[BUG] From fresh install, unable to find theme file

### ISSUE THREAD

**Issue by jonsterling** [hlissner/doom-emacs#2286]
**What did you expect to happen?**
...

I installed doom from scratch using the instructions, first removing my existing `.emacs.d` directory. I am using Emacs 26.3.

**What actually happened?**
...

The following error appears on startup:

    condition-case: Error in a Doom startup hook: doom-init-theme-h, (error "Unable to find theme file for ‘doom-one’")

<details><pre>
Debugger entered--Lisp error: (error "Unable to find theme file for ‘doom-one’")
  signal(error ("Unable to find theme file for ‘doom-one’"))
  error("Unable to find theme file for `%s'" doom-one)
  #f(compiled-function (theme &optional no-confirm no-enable) (interactive (list (intern (completing-read "Load custom theme: " (mapcar (quote symbol-name) (custom-available-themes)))) nil nil)) #<bytecode 0x1a9c9f>)(doom-one t)
  apply(#f(compiled-function (theme &optional no-confirm no-enable) (interactive (list (intern (completing-read "Load custom theme: " (mapcar (quote symbol-name) (custom-available-themes)))) nil nil)) #<bytecode 0x1a9c9f>) (doom-one t))
  #f(advice-wrapper :after-while #f(compiled-function (theme &optional no-confirm no-enable) (interactive (list (intern (completing-read "Load custom theme: " (mapcar (quote symbol-name) (custom-available-themes)))) nil nil)) #<bytecode 0x1a9c9f>) doom--run-load-theme-hooks-a)(doom-one t)
  apply(#f(advice-wrapper :after-while #f(compiled-function (theme &optional no-confirm no-enable) (interactive (list (intern (completing-read "Load custom theme: " (mapcar ... ...))) nil nil)) #<bytecode 0x1a9c9f>) doom--run-load-theme-hooks-a) (doom-one t))
  (progn (fset (quote locate-file) vnew) (apply orig-fn args))
  (unwind-protect (progn (fset (quote locate-file) vnew) (apply orig-fn args)) (fset (quote locate-file) old))
  (let* ((vnew (function (lambda (filename path &optional _suffixes predicate) (funcall old-locate-file filename path (quote ("c" "")) predicate)))) (old (symbol-function (quote locate-file)))) (unwind-protect (progn (fset (quote locate-file) vnew) (apply orig-fn args)) (fset (quote locate-file) old)))
  (let ((old-locate-file (symbol-function (quote locate-file)))) (let* ((vnew (function (lambda (filename path &optional _suffixes predicate) (funcall old-locate-file filename path (quote ...) predicate)))) (old (symbol-function (quote locate-file)))) (unwind-protect (progn (fset (quote locate-file) vnew) (apply orig-fn args)) (fset (quote locate-file) old))))
  (if (or (null after-init-time) doom--prefer-theme-elc) (let ((old-locate-file (symbol-function (quote locate-file)))) (let* ((vnew (function (lambda (filename path &optional _suffixes predicate) (funcall old-locate-file filename path ... predicate)))) (old (symbol-function (quote locate-file)))) (unwind-protect (progn (fset (quote locate-file) vnew) (apply orig-fn args)) (fset (quote locate-file) old)))) (apply orig-fn args))
  doom--prefer-compiled-theme-a(#f(advice-wrapper :after-while #f(compiled-function (theme &optional no-confirm no-enable) (interactive (list (intern (completing-read "Load custom theme: " (mapcar ... ...))) nil nil)) #<bytecode 0x1a9c9f>) doom--run-load-theme-hooks-a) doom-one t)
  apply(doom--prefer-compiled-theme-a #f(advice-wrapper :after-while #f(compiled-function (theme &optional no-confirm no-enable) (interactive (list (intern (completing-read "Load custom theme: " (mapcar ... ...))) nil nil)) #<bytecode 0x1a9c9f>) doom--run-load-theme-hooks-a) (doom-one t))
  load-theme(doom-one t)
  (let ((doom--prefer-theme-elc t)) (load-theme doom-theme t))
  (progn (select-frame (or frame (selected-frame)) (quote norecord)) (let ((doom--prefer-theme-elc t)) (load-theme doom-theme t)))
  (unwind-protect (progn (select-frame (or frame (selected-frame)) (quote norecord)) (let ((doom--prefer-theme-elc t)) (load-theme doom-theme t))) (if (frame-live-p old-frame) (progn (select-frame old-frame (quote norecord)))) (if (buffer-live-p old-buffer) (progn (set-buffer old-buffer))))
  (let ((old-frame (selected-frame)) (old-buffer (current-buffer))) (unwind-protect (progn (select-frame (or frame (selected-frame)) (quote norecord)) (let ((doom--prefer-theme-elc t)) (load-theme doom-theme t))) (if (frame-live-p old-frame) (progn (select-frame old-frame (quote norecord)))) (if (buffer-live-p old-buffer) (progn (set-buffer old-buffer)))))
  (progn (let ((old-frame (selected-frame)) (old-buffer (current-buffer))) (unwind-protect (progn (select-frame (or frame (selected-frame)) (quote norecord)) (let ((doom--prefer-theme-elc t)) (load-theme doom-theme t))) (if (frame-live-p old-frame) (progn (select-frame old-frame (quote norecord)))) (if (buffer-live-p old-buffer) (progn (set-buffer old-buffer))))))
  (if (and doom-theme (not (memq doom-theme custom-enabled-themes))) (progn (let ((old-frame (selected-frame)) (old-buffer (current-buffer))) (unwind-protect (progn (select-frame (or frame (selected-frame)) (quote norecord)) (let ((doom--prefer-theme-elc t)) (load-theme doom-theme t))) (if (frame-live-p old-frame) (progn (select-frame old-frame (quote norecord)))) (if (buffer-live-p old-buffer) (progn (set-buffer old-buffer)))))))
  doom-init-theme-h()
  funcall(doom-init-theme-h)
  (condition-case e (funcall hook) ((debug error) (signal (quote doom-hook-error) (list hook e))))
  doom-try-run-hook(doom-init-theme-h)
  run-hook-wrapped(doom-try-run-hook doom-init-theme-h)
  doom-init-ui-h()
  run-hooks(window-setup-hook)
  #f(compiled-function () #<bytecode 0x3eb7c9>)()
  normal-top-level()

</pre></details>

**Steps to reproduce:**

[Redundant]

**System information:**
<details><pre>
((emacs
  (version . "26.3")
  (features . "XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS LIBSYSTEMD LCMS2")
  (build . "Sep 23, 2019")
  (buildopts "--build x86_64-linux-gnu --prefix=/usr --sharedstatedir=/var/lib --libexecdir=/usr/lib --localstatedir=/var/lib --infodir=/usr/share/info --mandir=/usr/share/man --enable-libsystemd --with-pop=yes --enable-locallisppath=/etc/emacs:/usr/local/share/emacs/26.3/site-lisp:/usr/local/share/emacs/site-lisp:/usr/share/emacs/26.3/site-lisp:/usr/share/emacs/site-lisp --with-sound=alsa --without-gconf --with-mailutils --build x86_64-linux-gnu --prefix=/usr --sharedstatedir=/var/lib --libexecdir=/usr/lib --localstatedir=/var/lib --infodir=/usr/share/info --mandir=/usr/share/man --enable-libsystemd --with-pop=yes --enable-locallisppath=/etc/emacs:/usr/local/share/emacs/26.3/site-lisp:/usr/local/share/emacs/site-lisp:/usr/share/emacs/26.3/site-lisp:/usr/share/emacs/site-lisp --with-sound=alsa --without-gconf --with-mailutils --with-x=yes --with-x-toolkit=gtk3 --with-toolkit-scroll-bars 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/emacs-wvqver/emacs-26.3+1=. -fstack-protector-strong -Wformat -Werror=format-security -Wall' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro'")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD 4a53f0818 2020-01-01 03:02:05 -0500")
  (dir . "~/.config/doom/"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "zsh")
  (uname . "Linux 5.3.0-24-generic #26-Ubuntu SMP Thu Nov 14 01:33:18 UTC 2019 x86_64")
  (path "~/.opam/4.08.1/bin" "~/.npm-packages/bin" "~/.opam/4.08.1/bin" "~/Downloads/Tasky" "~/Downloads/HOL/bin" "/opt/ghc/bin" "/snap/bin" "~/Source/sml-redprl/bin" "~/.cabal/bin" "~/.local/bin" "~/.elan/bin" "~/.cargo/bin" "/usr/local/sbin" "/usr/local/bin" "/usr/sbin" "/usr/bin" "/sbin" "/bin" "/usr/games" "/usr/local/games" "/snap/bin" "~/.fzf/bin" "/usr/lib/emacs/26.3/x86_64-linux-gnu"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :editor evil :ui workspaces :completion company :ui doom-dashboard popup :tools pass :lang org web)
  (packages "n/a")
  (elpa "n/a")))

</pre></details>

**Comment by hlissner** [comment]
According to your `doom/info`, you have very few modules enabled. Not included in that list is the `:ui doom` module, which installs the `doom-themes` package, where `doom-one` is found.

I assume this isn't intentional, so there is likely a typo or error in `~/.config/doom/init.el`, in your `doom!` block.

If it was intentional, you'll have to install doom-themes manually, by adding `(package! doom-themes)` to `~/.config/doom/packages.el`, then run `doom sync` (same as `doom refresh`).

**Comment by jonsterling** [comment]
@hlissner Thanks! All I did when I set things up was to run `~/.emacs.d/bin/doom install` as the quick start instructions specified (I have not modified any `doom/init.el`). I had expected that after following these instructions, I would be able to start Emacs without errors.

Am I correct to understand that there is further setup required?

**Comment by jonsterling** [comment]
Or there is a tiny chance that I tried to install doom once before, and left behind an old config :wink:  Let me  check. If so, sorry for wasting your time! I'll update this ticket in a minute with what I find.

**Comment by jonsterling** [comment]
Looks like I just had some bad configs left over from another life! Thanks for your help and sorry for wasting your time :smile:

**Comment by hlissner** [comment]
No worries! I'm glad you figured it out!
