### ISSUE TITLE
Compile error when 'evil' is not enabled as a module

### ISSUE THREAD

**Issue by UndeadKernel** [hlissner/doom-emacs#229]
Hi @hlissner ,

When evil is not enabled as a module in init.el, "make compile" fails with the following message:
```
Compiled modules/feature/eval/autoload/evil.el
Symbol’s function definition is void: evil-define-operator
make: *** [Makefile:30: compile] Error 255
```

After running "git bisect", I found that the culprit commit was "[a2367866eca846391b52ff138b1f5fbed6bf3535](https://github.com/hlissner/doom-emacs/commit/a2367866eca846391b52ff138b1f5fbed6bf3535)". This is a very simple commit that pre loads some files for compilation. It seems that it's also loading the evil.el files in the autoloads folder even when the "evil" module is not enabled.

**Comment by hlissner** [comment]
Ah, you're right. I need a more general solution for preventing certain autoload files from being compiled/autoloaded. I'll look into this over this weekend.

**Comment by UndeadKernel** [comment]
This general solution would also get rid of warning such as:
```
Compiled modules/feature/jump/autoload/jump.el
In toplevel form:
evil.el:4:1:Warning: misplaced interactive spec: ‘(interactive "<a><!>")’
```

I'm still not very confident in my elisp-foo applied to emacs and compilation. For this reason, I'm afraid I cannot be of much support finding a solution to this issue.

**Comment by hlissner** [comment]
I've now added `if` cookies to Doom's autoloads crawler and byte-compiler.

In your particular case, autoload files that depend on evil now start with:

```
;;;###if (featurep! :feature evil)
```

Which should return false if you have evil disabled, which should resolve your issue. Feel free to reopen this if that isn't the case.
