### ISSUE TITLE
[BUG] Doom build -r does not seem to rebuild updated packages

### ISSUE THREAD

**Issue by adbrown101** [hlissner/doom-emacs#2290]
**What did you expect to happen?**
After doom update I expected the packages to be re-compiled.

**What actually happened?**
The packages are not recompiled.
Also doom build -r does not recompile the packages
doom build works as expected and fixes the problem

**Additional details:**

<details>
<pre>
$ doom doctor
The doctor will see you now...

> Checking your Emacs version...
> Checking for Emacs config conflicts...
> Checking for private config conflicts...
> Checking for stale elc files...
! ~/.emacs.d/.local/straight/build/org/ob-C.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ob-J.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ob-R.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ob-abc.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ob-asymptote.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ob-awk.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ob-calc.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ob-clojure.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ob-comint.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ob-coq.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ob-core.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ob-css.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ob-ditaa.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ob-dot.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ob-ebnf.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ob-emacs-lisp.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ob-eshell.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ob-eval.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ob-exp.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ob-forth.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ob-fortran.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ob-gnuplot.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ob-groovy.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ob-haskell.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ob-hledger.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ob-io.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ob-java.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ob-js.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ob-latex.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ob-ledger.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ob-lilypond.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ob-lisp.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ob-lob.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ob-lua.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ob-makefile.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ob-matlab.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ob-maxima.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ob-mscgen.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ob-ocaml.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ob-octave.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ob-org.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ob-perl.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ob-picolisp.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ob-plantuml.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ob-processing.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ob-python.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ob-ref.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ob-ruby.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ob-sass.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ob-scheme.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ob-screen.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ob-sed.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ob-shell.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ob-shen.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ob-sql.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ob-sqlite.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ob-stan.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ob-table.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ob-tangle.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ob-vala.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ob.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ol-bbdb.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ol-bibtex.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ol-docview.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ol-eshell.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ol-eww.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ol-gnus.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ol-info.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ol-irc.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ol-mhe.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ol-rmail.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ol-w3m.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ol.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/org-agenda.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/org-archive.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/org-attach-git.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/org-attach.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/org-capture.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/org-clock.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/org-colview.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/org-compat.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/org-crypt.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/org-ctags.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/org-datetree.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/org-duration.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/org-element.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/org-entities.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/org-faces.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/org-feed.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/org-footnote.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/org-goto.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/org-habit.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/org-id.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/org-indent.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/org-inlinetask.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/org-keys.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/org-lint.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/org-list.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/org-macro.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/org-macs.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/org-mobile.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/org-mouse.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/org-num.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/org-pcomplete.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/org-plot.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/org-protocol.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/org-src.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/org-table.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/org-tempo.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/org-timer.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/org-version.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/org.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ox-ascii.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ox-beamer.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ox-html.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ox-icalendar.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ox-latex.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ox-man.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ox-md.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ox-odt.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ox-org.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ox-publish.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ox-texinfo.elc is out-of-date
! ~/.emacs.d/.local/straight/build/org/ox.elc is out-of-date
> Checking Doom Emacs...

Compiling your literate config...
Tangled 18 code blocks from config.org

Done!
  ✓ Initialized Doom Emacs 2.0.9
  ✓ Detected 46 modules
  ✓ Detected 196 packages
  > Checking Doom core for irregularities...
    Found font material-design-icons.ttf
    Found font weathericons.ttf
    Found font octicons.ttf
    Found font fontawesome.ttf
    Found font file-icons.ttf
    Found font all-the-icons.ttf
  > Checking for stale elc files in your DOOMDIR...
  > Checking your enabled modules...
    > :lang cc
      ! Irony server isn't installed. Run M-x irony-install-server

There are 125 warnings!
✓ Finished! (237.2666s)

No RTags process running (rdm)...

$ doom build -r
Compiling your literate config...
Tangled 18 code blocks from config.org

Done!
> (Re)building packages...
  ✓ No packages need rebuilding
✓ Finished! (22.9910s)

</pre>
</details>

**Steps to reproduce:**
1. doom update
2. doom doctor
3. doom build -r
4. doom doctor
5. doom build rebuilds all of the packages and the problem goes away

**System information:**
<details><pre>

```
emacs   version    26.3
        features   XPM JPEG TIFF GIF PNG RSVG SOUND GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB LUCID X11 XDBE XIM MODULES THREADS LCMS2
        build      Aug 29, 2019
        buildopts  (--with-x-toolkit=athena --without-toolkit-scroll-bars --without-dbus --without-gconf --without-gsettings --prefix=/usr --sysconfdir=/etc --sbindir=/usr/bin --bindir=/usr/bin --mandir=/usr/share/man --infodir=/usr/share/info --localstatedir=/var --with-file-notification=inotify --with-modules --with-jpeg --with-tiff --with-gif --with-png --with-xpm --with-rsvg --without-imagemagick --with-xml2 --with-gnutls --with-sound --with-m17n-flt --host=x86_64-unknown-linux-gnu --build=x86_64-unknown-linux-gnu 'CFLAGS=-fno-PIE -mtune=generic -O2 -pipe   -g' 'CPPFLAGS=   ' 'LDFLAGS=-no-pie -Wl,--as-needed    ')
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop 4d6402198 2020-01-02 00:04:39 -0500
        dir        ~/.config/doom/
system  type       gnu/linux
        config     x86_64-unknown-linux-gnu
        shell      /bin/bash
        uname      Linux 4.4.0-17134-Microsoft #1130-Microsoft Thu Nov 07 15:21:00 PST 2019 x86_64
        path       (~/.emacs.d/bin ~/.local/share/cask/bin /c/utils/scripts/perl_scripts/symphony /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /usr/games /usr/local/games /opt/texlive/2019/bin/x86_64-linux /c/Program Files/Microsoft SQL Server/Client SDK/ODBC/110/Tools/Binn /usr/libexec/emacs/26.3/x86_64-unknown-linux-gnu)
config  envfile    nil
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces zen :editor (evil +everywhere) file-templates fold multiple-cursors rotate-text snippets :emacs (dired +ranger +icons) electric ibuffer vc :tools docker editorconfig (eval +overlay) flycheck (flyspell +hunspell) (lookup +docsets) magit pass pdf :lang cc data emacs-lisp latex markdown (org +attach +babel +capture +export +habit +hugo +pandoc +present +protocol) perl sh web :config literate (default +bindings +smartparens))
        packages   (sql-indent minions)
        elpa       (n/a)
```

</pre></details>

**Comment by adbrown101** [comment]
Having looked in more detail this looks like straight is not building org-mode. I have deleted my straight directory and run doom refresh, then doom doctor
<details>
<pre>
$ doom doctor
The doctor will see you now...

> Checking your Emacs version...
> Checking for Emacs config conflicts...
> Checking for private config conflicts...
> Checking for stale elc files...
> Checking Doom Emacs...

Compiling your literate config...
Tangled 18 code blocks from config.org

Done!
  ✓ Initialized Doom Emacs 2.0.9
  ✓ Detected 46 modules
  ✓ Detected 196 packages
  > Checking Doom core for irregularities...
    Found font material-design-icons.ttf
    Found font weathericons.ttf
    Found font octicons.ttf
    Found font fontawesome.ttf
    Found font file-icons.ttf
    Found font all-the-icons.ttf
  > Checking for stale elc files in your DOOMDIR...
  > Checking your enabled modules...
    > :lang cc
      ! Irony server isn't installed. Run M-x irony-install-server
  x org is not installed


There are 1 warnings!
✓ Finished! (141.2486s)

No RTags process running (rdm)...

</pre>
</details>

There is an org directory in the repos, but not in the build. Is this because all of the lisp is now in a sub directory
<details>
<pre>
$ ls -al ~/.emacs.d/.local/straight/repos/org
total 76
drwxr-xr-x 1 alan alan  4096 Jan  2 10:52 .
drwxr-xr-x 1 alan alan  4096 Jan  2 10:54 ..
-rw-r--r-- 1 alan alan   483 Jan  2 10:52 .dir-locals.el
drwxr-xr-x 1 alan alan  4096 Jan  2 10:52 .git
-rw-r--r-- 1 alan alan   918 Jan  2 10:52 .gitignore
-rw-r--r-- 1 alan alan    95 Jan  2 10:52 .gitmodules
-rw-r--r-- 1 alan alan 35147 Jan  2 10:52 COPYING
-rw-r--r-- 1 alan alan  3633 Jan  2 10:52 Makefile
-rw-r--r-- 1 alan alan  1225 Jan  2 10:52 README
-rw-r--r-- 1 alan alan   925 Jan  2 10:52 README_ELPA
-rw-r--r-- 1 alan alan  3368 Jan  2 10:52 README_contribute
-rw-r--r-- 1 alan alan  1426 Jan  2 10:52 README_git
-rw-r--r-- 1 alan alan  6697 Jan  2 10:52 README_maintainer
drwxr-xr-x 1 alan alan  4096 Jan  2 10:52 contrib
drwxr-xr-x 1 alan alan  4096 Jan  2 10:52 doc
drwxr-xr-x 1 alan alan  4096 Jan  2 10:52 etc
drwxr-xr-x 1 alan alan  4096 Jan  2 10:52 lisp
drwxr-xr-x 1 alan alan  4096 Jan  2 10:52 mk
-rw-r--r-- 1 alan alan    94 Jan  2 10:52 org-version.el
-rw-r--r-- 1 alan alan   980 Jan  2 10:52 request-assign-future.txt
drwxr-xr-x 1 alan alan  4096 Jan  2 10:52 testing

$ ls -al ~/.emacs.d/.local/straight/build/org
ls: cannot access '/home/alan/.emacs.d/.local/straight/build/org': No such file or directory
</pre>
</details>

**Comment by hlissner** [comment]
There is no `build/org` because it's in `build/org-plus-contrib`.

As for its failure to detect stale elc files, straight doesn't seem to check for stale bytecode, only for package changes. Running `doom build` will ensure it gets built for the time being. I'll look into whether I want to fix this in Doom, or report it upstream.

**Comment by hlissner** [comment]
Our package manager has seen a lot of work in the past month, so I'll assume the issue has been resolved. Let me know if that isn't the case.
