### ISSUE TITLE
[BUG] delete does not work with easymotion

### ISSUE THREAD

**Issue by fikovnik** [hlissner/doom-emacs#2293]
**What did you expect to happen?**
I want to delete consecutive lines so I press `d` and then activate easymotion `gsj` and then I select the letter indicating the line to which I want to delete.

It does work with `v` for example.

**What actually happened?**

Cursor moved at the beginning of the line indicated by the easymotion

**System information:**
<details><pre>
emacs   version    28.0.50
        features   XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP
        build      Jan 01, 2020
        buildopts  (--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --mandir=/usr/share/man --with-gameuser=:games --with-sound=alsa --with-modules --without-gconf --without-gsettings --enable-link-time-optimization --with-x-toolkit=gtk3 --without-xaw3d --without-m17n-flt --with-cairo --without-compress-install 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -g -flto -fuse-linker-plugin -s -fuse-ld=gold' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now)
        windowsys  nil
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop, origin/develop, origin/HEAD 4a53f0818 2020-01-01 03:02:05 -0500
        dir        ~/.doom.d/
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/zsh
        uname      Linux 5.4.2-1-MANJARO #1 SMP PREEMPT Thu Dec 5 09:55:57 UTC 2019 x86_64
        path       (~/.sdkman/candidates/scala/current/bin ~/.local/bin ~/.local/bin /usr/local/bin /usr/local/sbin ~/.local/bin /usr/local/bin /usr/bin /bin /usr/local/sbin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /usr/lib/smlnj/bin /var/lib/snapd/snap/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /usr/lib/smlnj/bin /usr/lib/emacs/28.0.50/x86_64-pc-linux-gnu)
config  envfile    envvar-file
        elc-files  2
        modules    (:completion (company +childframe) (ivy +fuzzy +prescient) :ui doom doom-dashboard fill-column hl-todo hydra modeline nav-flash ophints (popup +all +defaults) vc-gutter vi-tilde-fringe (window-select +numbers) workspaces :editor (evil +everywhere) file-templates fold multiple-cursors rotate-text snippets word-wrap :emacs dired electric ibuffer vc :tools (eval +overlay) flycheck (flyspell +aspell) (lookup +dictionary +docsets) lsp magit make pass pdf tmux :lang (agda +local) (cc +lsp) data emacs-lisp ess go (haskell +dante +lsp) idris latex markdown (org +dragndrop +pandoc +present) plantuml racket (rust +lsp) scala sh web :app write :config (default +bindings +smartparens))
        packages   (n/a)
        elpa       (n/a)

</pre></details>

Thanks a lot for doom-emacs!!

**Comment by WhatDothLife** [comment]
I was also wondering why this feature is not implemented yet. However, this is neither a bug nor should it be reported here. I think the right way to deal with this is to hop over to [evil-easymotion](https://github.com/PythonNut/evil-easymotion) and create a feature request!

**Comment by fikovnik** [comment]
I checked the evil-easymotion github and I found:

> Currently most motions are supported, and it's easy to define your own easymotions. 
> Easymotions can also be composed with operators e.g. dSPCj to delete a bunch of lines.

which is exactly what I'm after.
Perhaps just some binding is missing, but I'm new to doom-emacs and evil so I could be wrong.

**Comment by hlissner** [comment]
This is indeed an issue with the way Doom Emacs binds its keys for evil-easymotion. Specifically, how `+evil/easymotion` is designed to trigger the `easymotion` event, which evil considers the end of the current operation (thus aborting operator mode before triggering easymotion). I'm still looking into a fix and will keep you posted once I've made progress.

**Comment by hlissner** [comment]
As of fe0c5e1 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by fikovnik** [comment]
Is it the case that I need to type the combination rather quickly. It happens to me like 2 out of 3 times that it won't delete (or yank), but instead just jump if I'm not fast enough. Can I increase the delay?
