### ISSUE TITLE
[BUG] [void-function doom-syntax-ppss]

### ISSUE THREAD

**Issue by cxb811201** [hlissner/doom-emacs#2297]
**What did you expect to happen?**

**What actually happened?**
execute the `C-a` or `C-e` command in the comment line

**Additional details:**

<details><pre>
Debugger entered--Lisp error: (void-function doom-syntax-ppss)
  (doom-syntax-ppss (+ pos 2))
  (nth 4 (doom-syntax-ppss (+ pos 2)))
  (and (/= 0 (logand (lsh 1 16) s)) (nth 4 (doom-syntax-ppss (+ pos 2))))
  (or (and (/= 0 (logand (lsh 1 16) s)) (nth 4 (doom-syntax-ppss (+ pos 2)))) (and (/= 0 (logand (lsh 1 17) s)) (nth 4 (doom-syntax-ppss (+ pos 1)))) (and (/= 0 (logand (lsh 1 18) s)) (nth 4 (doom-syntax-ppss (- pos 1)))) (and (/= 0 (logand (lsh 1 19) s)) (nth 4 (doom-syntax-ppss (- pos 2)))))
  (if s (or (and (/= 0 (logand (lsh 1 16) s)) (nth 4 (doom-syntax-ppss (+ pos 2)))) (and (/= 0 (logand (lsh 1 17) s)) (nth 4 (doom-syntax-ppss (+ pos 1)))) (and (/= 0 (logand (lsh 1 18) s)) (nth 4 (doom-syntax-ppss (- pos 1)))) (and (/= 0 (logand (lsh 1 19) s)) (nth 4 (doom-syntax-ppss (- pos 2))))) nil)
  (let* ((s (and t (car (syntax-after pos))))) (if s (or (and (/= 0 (logand (lsh 1 16) s)) (nth 4 (doom-syntax-ppss (+ pos 2)))) (and (/= 0 (logand (lsh 1 17) s)) (nth 4 (doom-syntax-ppss (+ pos 1)))) (and (/= 0 (logand (lsh 1 18) s)) (nth 4 (doom-syntax-ppss (- pos 1)))) (and (/= 0 (logand (lsh 1 19) s)) (nth 4 (doom-syntax-ppss (- pos 2))))) nil))
  (or (nth 4 ppss) (nth 8 ppss) (and (< pos (point-max)) (memq (char-syntax (char-after pos)) '(60 62)) (not (eq (char-after pos) 10))) (let* ((s (and t (car (syntax-after pos))))) (if s (or (and (/= 0 (logand (lsh 1 16) s)) (nth 4 (doom-syntax-ppss (+ pos 2)))) (and (/= 0 (logand (lsh 1 17) s)) (nth 4 (doom-syntax-ppss (+ pos 1)))) (and (/= 0 (logand (lsh 1 18) s)) (nth 4 (doom-syntax-ppss (- pos 1)))) (and (/= 0 (logand (lsh 1 19) s)) (nth 4 (doom-syntax-ppss (- pos 2))))) nil)))
  (let* ((pos (or pos (point))) (ppss (syntax-ppss pos))) (or (nth 4 ppss) (nth 8 ppss) (and (< pos (point-max)) (memq (char-syntax (char-after pos)) '(60 62)) (not (eq (char-after pos) 10))) (let* ((s (and t (car (syntax-after pos))))) (if s (or (and (/= 0 (logand ... s)) (nth 4 (doom-syntax-ppss ...))) (and (/= 0 (logand ... s)) (nth 4 (doom-syntax-ppss ...))) (and (/= 0 (logand ... s)) (nth 4 (doom-syntax-ppss ...))) (and (/= 0 (logand ... s)) (nth 4 (doom-syntax-ppss ...)))) nil))))
  doom-point-in-comment-p()
  (and (doom-point-in-comment-p) (> (point) bol))
  (while (and (doom-point-in-comment-p) (> (point) bol)) (backward-char))
  (if (not comment-use-syntax) (progn (goto-char bol) (if (re-search-forward comment-start-skip eol t) (progn (or (match-end 1) (match-beginning 0))))) (goto-char eol) (while (and (doom-point-in-comment-p) (> (point) bol)) (backward-char)) (skip-chars-backward " " bol) (if (or (eq (char-after) 32) (eolp)) nil (forward-char)) (point))
  (save-excursion (if (not comment-use-syntax) (progn (goto-char bol) (if (re-search-forward comment-start-skip eol t) (progn (or (match-end 1) (match-beginning 0))))) (goto-char eol) (while (and (doom-point-in-comment-p) (> (point) bol)) (backward-char)) (skip-chars-backward " " bol) (if (or (eq (char-after) 32) (eolp)) nil (forward-char)) (point)))
  (or (save-excursion (if (not comment-use-syntax) (progn (goto-char bol) (if (re-search-forward comment-start-skip eol t) (progn (or (match-end 1) (match-beginning 0))))) (goto-char eol) (while (and (doom-point-in-comment-p) (> (point) bol)) (backward-char)) (skip-chars-backward " " bol) (if (or (eq (char-after) 32) (eolp)) nil (forward-char)) (point))) eol)
  (let* ((bol (if visual-line-mode (save-excursion (beginning-of-visual-line) (point)) (line-beginning-position))) (bot (save-excursion (goto-char bol) (skip-chars-forward " \11\15") (point))) (eol (if visual-line-mode (save-excursion (end-of-visual-line) (point)) (line-end-position))) (eot (or (save-excursion (if (not comment-use-syntax) (progn (goto-char bol) (if ... ...)) (goto-char eol) (while (and ... ...) (backward-char)) (skip-chars-backward " " bol) (if (or ... ...) nil (forward-char)) (point))) eol))) (list bol bot eot eol))
  doom--bol-bot-eot-eol(2180)
  (let* ((--cl-rest-- (doom--bol-bot-eot-eol pt)) (_bol (if (= (length --cl-rest--) 4) (car-safe (prog1 --cl-rest-- (setq --cl-rest-- (cdr --cl-rest--)))) (signal 'wrong-number-of-arguments (list '(_bol _bot eot eol) (length --cl-rest--))))) (_bot (car-safe (prog1 --cl-rest-- (setq --cl-rest-- (cdr --cl-rest--))))) (eot (car-safe (prog1 --cl-rest-- (setq --cl-rest-- (cdr --cl-rest--))))) (eol (car --cl-rest--))) (cond ((< pt eot) (goto-char eot)) ((= pt eol) (goto-char (or doom--last-forward-pt eot)) (setq doom--last-forward-pt nil)) ((>= pt eot) (setq doom--last-backward-pt pt) (goto-char eol))))
  (let ((pt (or point (point)))) (let* ((--cl-rest-- (doom--bol-bot-eot-eol pt)) (_bol (if (= (length --cl-rest--) 4) (car-safe (prog1 --cl-rest-- (setq --cl-rest-- ...))) (signal 'wrong-number-of-arguments (list '... (length --cl-rest--))))) (_bot (car-safe (prog1 --cl-rest-- (setq --cl-rest-- (cdr --cl-rest--))))) (eot (car-safe (prog1 --cl-rest-- (setq --cl-rest-- (cdr --cl-rest--))))) (eol (car --cl-rest--))) (cond ((< pt eot) (goto-char eot)) ((= pt eol) (goto-char (or doom--last-forward-pt eot)) (setq doom--last-forward-pt nil)) ((>= pt eot) (setq doom--last-backward-pt pt) (goto-char eol)))))
  doom/forward-to-last-non-comment-or-eol(2180)
  funcall-interactively(doom/forward-to-last-non-comment-or-eol 2180)
  call-interactively(doom/forward-to-last-non-comment-or-eol nil nil)
  command-execute(doom/forward-to-last-non-comment-or-eol)
</pre></details>

**Steps to reproduce:**

**System information:**
<details><pre>
((emacs
  (version . "27.0.60")
  (features . "RSVG IMAGEMAGICK GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS XWIDGETS JSON PDUMPER LCMS2 GMP")
  (build . "Jan 03, 2020")
  (buildopts "--disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus/HEAD-1420906/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus/HEAD-1420906 --with-xml2 --without-dbus --with-gnutls --with-imagemagick --with-json --with-modules --with-rsvg --without-pop --with-xwidgets --with-ns --disable-ns-self-contained")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop d426349f2 2020-01-02 21:54:28 -0500")
  (dir . "~/.doom.d/"))
 (system
  (type . darwin)
  (config . "x86_64-apple-darwin19.2.0")
  (shell . "/bin/zsh")
  (uname . "Darwin 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64")
  (path "/usr/local/opt/coreutils/libexec/gnubin" "/usr/local/opt/gnu-tar/libexec/gnubin" "/usr/local/opt/openssl/bin" "/usr/local/lib/ruby/gems/2.6.0/bin" "~/.go/bin" "~/.cargo/bin" "~/.jenv/shims" "~/.jenv/bin" "~/.emacs.d/bin" "/usr/local/bin" "/usr/bin" "/bin" "/usr/sbin" "/sbin" "~/.antigen/bundles/robbyrussell/oh-my-zsh/lib" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/git" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/gitfast" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/git-remote-branch" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/colored-man-pages" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/history" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/z" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/extract" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/encode64" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/web-search" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/urltools" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/tmux" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/docker" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/docker-compose" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/docker-machine" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/brew" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/osx" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/cargo" "~/.antigen/bundles/djui/alias-tips" "~/.antigen/bundles/zdharma/fast-syntax-highlighting" "~/.antigen/bundles/zsh-users/zsh-autosuggestions" "~/.antigen/bundles/hlissner/zsh-autopair" "~/.antigen/bundles/romkatv/powerlevel10k" "/usr/local/Cellar/emacs-plus/HEAD-1420906/libexec/emacs/27.0.60/x86_64-apple-darwin19.2.0"))
 (config
  (envfile)
  (elc-files . 0)
  (modules :input chinese :completion company (ivy +prescient +fuzzy +childframe) :ui doom doom-quit hl-todo hydra modeline nav-flash ophints (popup +all +defaults) treemacs vc-gutter (window-select +numbers) workspaces centered-cursor :editor file-templates lispy multiple-cursors rotate-text snippets :emacs (dired +ranger) electric (ibuffer +icons) vc :term eshell :tools docker editorconfig (eval +overlay) (flycheck +childframe) lookup lsp macos magit (youdao +childframe) :lang data emacs-lisp (go +lsp) (java +lsp) (javascript +lsp) (kotlin +lsp) markdown (org +dragndrop +hugo +ipython +pandoc +present +pomodoro +journal) plantuml rest (scala +lsp) sh (web +lsp) :config (default +bindings +smartparens))
  (packages "(fcitx :disable t)" "(pangu-spacing :disable t)" "(tide :disable t)" "(liberime-config :recipe (:host github :repo \"merrickluo/liberime\" :files (\"liberime-config.el\" \"src\" \"CMakeLists.txt\" \"Makefile\")))" "(company-english-helper :recipe (:host github :repo \"cxb811201/company-english-helper\"))" "(insert-translated-name :recipe (:host github :repo \"manateelazycat/insert-translated-name\"))" cal-china-x exec-path-from-shell hungry-delete "(go-impl :recipe (:host github :repo \"cxb811201/emacs-go-impl\"))" go-fill-struct sqlup-mode dap-mode)
  (elpa "n/a")))
</pre></details>

**Comment by hlissner** [comment]
As of 8857dc1 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
