### ISSUE TITLE
[BUG] execute C-a or C-e command in the comment line of go-mode, emacs is stuck

### ISSUE THREAD

**Issue by cxb811201** [hlissner/doom-emacs#2298]
**What did you expect to happen?**
execute the `C-a` or `C-e` command normally in the comment line of `go-mode`

**What actually happened?**
execute C-a or C-e command in the comment line of go-mode, emacs is stuck

only use the `C-g` command to exit

**Comment by hlissner** [comment]
Can you produce a backtrace from that? Run `M-x toggle-debug-on-quit`, then `C-g` will throw up a backtrace.

**Comment by cxb811201** [comment]
> Can you produce a backtrace from that? Run `M-x toggle-debug-on-quit`, then `C-g` will throw up a backtrace.

<pre>
Debugger entered--Lisp error: (quit)
  #f(compiled-function () #<bytecode 0x1feb3044c941>)()
  syntax-ppss(1060)
  (let ((ppss (syntax-ppss pos))) (or (nth 4 ppss) (nth 8 ppss) (and (< pos (point-max)) (memq (char-syntax (char-after pos)) '(60 62)) (not (eq (char-after pos) 10))) (let* ((s (and t (car (syntax-after pos))))) (if s (or (and (/= 0 (logand ... s)) (nth 4 (syntax-ppss ...))) (and (/= 0 (logand ... s)) (nth 4 (syntax-ppss ...))) (and (/= 0 (logand ... s)) (nth 4 (syntax-ppss ...))) (and (/= 0 (logand ... s)) (nth 4 (syntax-ppss ...)))) nil))))
  (or (run-hook-with-args-until-success 'doom-point-in-comment-functions pos) (let ((ppss (syntax-ppss pos))) (or (nth 4 ppss) (nth 8 ppss) (and (< pos (point-max)) (memq (char-syntax (char-after pos)) '(60 62)) (not (eq (char-after pos) 10))) (let* ((s (and t (car ...)))) (if s (or (and (/= 0 ...) (nth 4 ...)) (and (/= 0 ...) (nth 4 ...)) (and (/= 0 ...) (nth 4 ...)) (and (/= 0 ...) (nth 4 ...))) nil)))))
  (let ((pos (or pos (point)))) (or (run-hook-with-args-until-success 'doom-point-in-comment-functions pos) (let ((ppss (syntax-ppss pos))) (or (nth 4 ppss) (nth 8 ppss) (and (< pos (point-max)) (memq (char-syntax (char-after pos)) '(60 62)) (not (eq (char-after pos) 10))) (let* ((s (and t ...))) (if s (or (and ... ...) (and ... ...) (and ... ...) (and ... ...)) nil))))))
  doom-point-in-comment-p()
  (and (doom-point-in-comment-p) (> (point) bol))
  (while (and (doom-point-in-comment-p) (> (point) bol)) (backward-char))
  (if (not comment-use-syntax) (progn (goto-char bol) (if (re-search-forward comment-start-skip eol t) (progn (or (match-end 1) (match-beginning 0))))) (goto-char eol) (while (and (doom-point-in-comment-p) (> (point) bol)) (backward-char)) (skip-chars-backward " " bol) (if (or (eq (char-after) 32) (eolp)) nil (forward-char)) (point))
  (save-excursion (if (not comment-use-syntax) (progn (goto-char bol) (if (re-search-forward comment-start-skip eol t) (progn (or (match-end 1) (match-beginning 0))))) (goto-char eol) (while (and (doom-point-in-comment-p) (> (point) bol)) (backward-char)) (skip-chars-backward " " bol) (if (or (eq (char-after) 32) (eolp)) nil (forward-char)) (point)))
  (or (save-excursion (if (not comment-use-syntax) (progn (goto-char bol) (if (re-search-forward comment-start-skip eol t) (progn (or (match-end 1) (match-beginning 0))))) (goto-char eol) (while (and (doom-point-in-comment-p) (> (point) bol)) (backward-char)) (skip-chars-backward " " bol) (if (or (eq (char-after) 32) (eolp)) nil (forward-char)) (point))) eol)
  (let* ((bol (if visual-line-mode (save-excursion (beginning-of-visual-line) (point)) (line-beginning-position))) (bot (save-excursion (goto-char bol) (skip-chars-forward " \11\15") (point))) (eol (if visual-line-mode (save-excursion (end-of-visual-line) (point)) (line-end-position))) (eot (or (save-excursion (if (not comment-use-syntax) (progn (goto-char bol) (if ... ...)) (goto-char eol) (while (and ... ...) (backward-char)) (skip-chars-backward " " bol) (if (or ... ...) nil (forward-char)) (point))) eol))) (list bol bot eot eol))
  doom--bol-bot-eot-eol(1062)
  (let* ((--cl-rest-- (doom--bol-bot-eot-eol pt)) (_bol (if (= (length --cl-rest--) 4) (car-safe (prog1 --cl-rest-- (setq --cl-rest-- (cdr --cl-rest--)))) (signal 'wrong-number-of-arguments (list '(_bol _bot eot eol) (length --cl-rest--))))) (_bot (car-safe (prog1 --cl-rest-- (setq --cl-rest-- (cdr --cl-rest--))))) (eot (car-safe (prog1 --cl-rest-- (setq --cl-rest-- (cdr --cl-rest--))))) (eol (car --cl-rest--))) (cond ((< pt eot) (goto-char eot)) ((= pt eol) (goto-char (or doom--last-forward-pt eot)) (setq doom--last-forward-pt nil)) ((>= pt eot) (setq doom--last-backward-pt pt) (goto-char eol))))
  (let ((pt (or point (point)))) (let* ((--cl-rest-- (doom--bol-bot-eot-eol pt)) (_bol (if (= (length --cl-rest--) 4) (car-safe (prog1 --cl-rest-- (setq --cl-rest-- ...))) (signal 'wrong-number-of-arguments (list '... (length --cl-rest--))))) (_bot (car-safe (prog1 --cl-rest-- (setq --cl-rest-- (cdr --cl-rest--))))) (eot (car-safe (prog1 --cl-rest-- (setq --cl-rest-- (cdr --cl-rest--))))) (eol (car --cl-rest--))) (cond ((< pt eot) (goto-char eot)) ((= pt eol) (goto-char (or doom--last-forward-pt eot)) (setq doom--last-forward-pt nil)) ((>= pt eot) (setq doom--last-backward-pt pt) (goto-char eol)))))
  doom/forward-to-last-non-comment-or-eol(1062)
  funcall-interactively(doom/forward-to-last-non-comment-or-eol 1062)
  call-interactively(doom/forward-to-last-non-comment-or-eol nil nil)
  command-execute(doom/forward-to-last-non-comment-or-eol)

</pre>

**Comment by cxb811201** [comment]
Evil is not installed

**Comment by cxb811201** [comment]
The problem was not found after executing the doom build command again
