### ISSUE TITLE
[BUG] crash in early-init.el when emacs is started in terminal (emacs 27)

### ISSUE THREAD

**Issue by razzmatazz** [hlissner/doom-emacs#2310]
**What did you expect to happen?**
Regular startup, no error message.

**What actually happened?**
A message is shown on `*Warnings*` buffer:
```
Warning (initialization): An error occurred while loading ‘/Users/bob/.emacs.d/early-init.el’:

Symbol's function definition is void: set-scroll-bar-mode
```

Seems to be related to this commit:
 - https://github.com/hlissner/doom-emacs/commit/f78f71a74c9a64d493687a686a599ea25f5d4a57#diff-7728e6910cca741c38cb7602e3b89d13R18

The issue is that set-scroll-bar-mode is missing when emacs is compiled without GUI support.

**Steps to reproduce:**
1. launch doom in console/terminal
2. observe the crash

**System information:**
<details><pre>
((emacs
  (version . "27.0.60")
  (features . "NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB MODULES THREADS JSON PDUMPER LCMS2 GMP")
  (build . "Jan 03, 2020")
  (buildopts "--prefix=/Users/bob/.local/ --without-ns")
  (windowsys . batch)
  (daemonp))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD f26b148b2 2020-01-04 18:11:10 -0500")
  (dir . "~/.doom.d/"))
 (system
  (type . darwin)
  (config . "x86_64-apple-darwin19.2.0")
  (shell . "/bin/bash")
  (uname . "Darwin 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64")
  (path "/Library/TeX/texbin/" "/usr/local/opt/mysql-client/bin" "~/.cargo/bin" "/usr/local/share/dotnet" "/Library/TeX/texbin/" "~/.cargo/bin" "~/bin/google-cloud-sdk/bin" "~/.local/bin" "~/bin" "/usr/local/bin" "/usr/local/sbin" "/Library/Frameworks/Mono.framework/Versions/Current/bin/" "/usr/local/bin" "/usr/bin" "/bin" "/usr/sbin" "/sbin" "/Library/TeX/texbin" "/usr/local/share/dotnet" "~/.dotnet/tools" "~/.local/libexec/emacs/27.0.60/x86_64-apple-darwin19.2.0"))
 (config
  (envfile)
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash neotree ophints (popup +all +defaults) vc-gutter vi-tilde-fringe window-select :editor (evil +everywhere) file-templates fold multiple-cursors rotate-text snippets :emacs dired electric ibuffer vc :term eshell shell :tools ansible docker (eval +overlay) flycheck (lookup +docsets) magit make prodigy :lang csharp data emacs-lisp fsharp go markdown (org +dragndrop +present) python rust sh web :email (mu4e +gmail) :config (default +bindings +smartparens))
  (packages zenburn-theme)
  (elpa "n/a")))
</pre></details>

**Comment by gagbo** [comment]
Change `(set-scroll-bar-mode nil)` to `(when (fboundp 'set-scroll-bar-mode) (set-scroll-bar-mode nil))` in early-init.el file to make it work (or just delete the line altogether for that matter).

It's weird to have """built-in""" functions fail instead of `no-op`ing when the compilation flag hasn't been chosen :(

**Comment by hlissner** [comment]
As of 8a9d8f0 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
