### ISSUE TITLE
[BUG] +workspace-buffer-list doesn't order buffers by recency

### ISSUE THREAD

**Issue by howsiwei** [hlissner/doom-emacs#2315]
**What did you expect to happen?**
The documentation of `+workspace-buffer-list` claims that
```
The buffer list is ordered by recency (same as `buffer-list').
```
So one would expect that it is ordered by most recently accessed time.

**What actually happened?**
`+workspace-buffer-list` seems to be ordered by opening time, where the last opened buffer comes first.

**Comment by hlissner** [comment]
I've removed the line in its docstring in 9fce4d5. I cannot guarantee it's the load order buffers are stored in for perspectives, so I won't make those claims. Thanks for bringing it to my attention!
