### ISSUE TITLE
[BUG] completion-in-region is not using helm when evil is disabled

### ISSUE THREAD

**Issue by aidermoi** [hlissner/doom-emacs#2317]
**What did you expect to happen?**
TAB, or completion-at-point/completion-in-region should use helm if helm is enabled and evil is disasbled.
e.g. M-x gdb, then hit TAB for any partial command should invoke helm.

**What actually happened?**
HELM is not used, default emacs completion is used instead.

**Additional details:**
I used to use normal Emacs + helm without evil, and TAB completion automatically uses helm.
The helm module config in doom-emacs has following line:
`
        ;; Don't override evil-ex's completion
        helm-mode-handle-completion-in-region nil`

which assumes the user is using evil I guess?
It would be better if the config can somehow figure out whether evil module has been loaded before disable this feature. Thanks!

**Comment by hlissner** [comment]
As of b5a2793 this issue should be resolved. Helm can now handle the completion I had initially disabled for, so it isn't needed anymore. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
