### ISSUE TITLE
+evil--window-swap uses the "doom-buffer" deprecated variable

### ISSUE THREAD

**Issue by UndeadKernel** [hlissner/doom-emacs#232]
When running any of your bindings to move windows (e.g., +evil/window-move-left ()), the function +evil--window-swap is called. In line 57 of the file "modules/feature/evil/autoload/evil.el, the wrong buffer tries to be restored. The culprit line is:
```
        (with-selected-window that-window
          (switch-to-buffer doom-buffer))
```
and should probably be:
```
        (with-selected-window that-window
          (switch-to-buffer (doom-fallback-buffer)))
```

**Comment by hlissner** [comment]
Good catch! It is fixed now.
