### ISSUE TITLE
[BUG] describe-function -> org-clock-in (and some others) -> causes emacs to hang

### ISSUE THREAD

**Issue by oblitzitate** [hlissner/doom-emacs#2321]
**What did you expect to happen?**
For `describe-function` to describe a function properly without hanging.

**What actually happened?**
Running `describe-function` on `org-clock-in` (and other functions such as `org-clock-in-last` and `org-clock-cancel`) first causes emacs to hang.

It only won't hang if you call `org-clock-in` (or `org-clock-out`, or possibly any other org-clock-related commands) first, then describe the function.

**Additional details:**
- Using vanilla doom
- Occurs using `C-h f` and `SPC h f` but not using `M-x describe-function`

**Steps to reproduce:**
1. Press `C-h f` or `SPC h f` for describe-function prompt
2. Type and select `org-clock-in`

**System information:**
<details><pre>
((emacs
  (version . "26.3")
  (features . "XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2")
  (build . "Aug 29, 2019")
  (buildopts "--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-modules 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop af0139e97 2020-01-06 23:46:33 -0500")
  (dir . "~/.doom.d/"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/bin/bash")
  (uname . "Linux 4.14.160-1-MANJARO #1 SMP PREEMPT Sat Dec 21 11:56:33 UTC 2019 x86_64")
  (path "~/.emacs.d/bin" "~/.cargo/bin" "~/bin" "~/.local/bin" "/usr/local/bin" "/usr/bin" "/bin" "/usr/local/sbin" "/usr/lib/jvm/default/bin" "/usr/bin/site_perl" "/usr/bin/vendor_perl" "/usr/bin/core_perl" "~/.gem/ruby/2.6.0/bin" "/usr/lib/emacs/26.3/x86_64-pc-linux-gnu"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold multiple-cursors rotate-text snippets :emacs dired electric ibuffer vc :tools (eval +overlay) flycheck (lookup +docsets) magit :lang data emacs-lisp markdown (org +dragndrop +pomodoro +present) sh :config (default +bindings +smartparens))
  (packages "n/a")
  (elpa "n/a")))
</pre></details>

**Comment by rohitpaulk** [comment]
Can confirm that this happens for me too.

**Comment by hlissner** [comment]
This is an issue in the [helpful](https://github.com/Wilfred/helpful) package. [I have reported it upstream](https://github.com/Wilfred/helpful/issues/179#issuecomment-571459769).

**Comment by oblitzitate** [comment]
This doesn't seem to occur anymore so I will close this issue.
