### ISSUE TITLE
[HOWTO] Get roxygen comment continuation to work

### ISSUE THREAD

**Issue by paullemmens** [hlissner/doom-emacs#2327]
When writing roxygen comments (e.g. in R source files), they are prepended with `#'`. It should happen that the next line is automatically prepended with that commenting prefix. In my case that does not happen.

I discussed this with @hlissner in the Discord channel but the solution there did not solve the problem. It made it worse, unfortunately, giving an error. [There](https://discordapp.com/channels/406534637242810369/406554085794381833/657282836977549352) the suggestion was to `(setq-hook! 'ess-roxy-mode-hook comment-line-break-function #'ess-roxy-indent-on-newline)` which I implemented in an `(after! ess)` in my `config.el`.

The error that now happens is 
```
funcall: Wrong number of arguments: #[nil "`Á U
\0Â ÃyÄ `)`]b)Â ÅÆ!ÇPc" [point-after-roxy-string ess-roxy-beg-of-entry newline-and-indent 0 ess-back-to-roxy ess-roxy-guess-str t " "] 2 ("/home/nlv19419/.emacs.d/.local/straight/build/ess/ess-roxy.elc" . 29876)], 1
```

 (and no comment char or roxygen comment is created).

Because this is likely something local my `config.el`:
<details><pre>
;;; .doom.d/config.el -*- lexical-binding: t; -*-

;; Place your private configuration here

;; ----------------------------------------------------------------------------
;; Use my preferred keys for escape ,, and the , localleader from spacemacs
(setq-default
   evil-escape-key-sequence ",,"
   evil-escape-delay 0.2
   )
(setq doom-localleader-key ",")
(load! "+keybindings")
;; ----------------------------------------------------------------------------

;; ----------------------------------------------------------------------------
;; Cosmetics aspects.
(toggle-frame-maximized)

(setq doom-theme 'solarized-dark)

(setq doom-font (font-spec :family "Source Code Pro" :size 13 :weight 'regular)
      doom-variable-pitch-font (font-spec :family "Source Code Pro") ; inherits `doom-font''s :size
      doom-unicode-font (font-spec :family "Source Code Pro" :size 13)
      doom-big-font (font-spec :family "Source Code Pro" :size 19))

(setq display-line-numbers-type 'relative)

(add-hook! 'text-mode-hook 'turn-on-auto-fill)
(add-hook! '(text-mode-hook markdown-mode-hook)
          (lambda() (set-fill-column 120)))

(setq show-trailing-whitespace t)

(after! all-the-icons
  (setq all-the-icons-scale-factor 1.0))

(after! doom-modeline
  (setq
   doom-modeline-major-mode-color-icon t
   doom-modeline-minor-modes (featurep 'minions)))

(after! doom-themes
  (setq
   doom-neotree-file-icons t
   doom-themes-enable-bold t
   doom-themes-enable-italic t))

(after! solarized-emacs
  (setq solarized-use-more-italic t))
;; ----------------------------------------------------------------------------

;; ----------------------------------------------------------------------------
;; ESS related customization
(after! ess
  (set-evil-initial-state! 'ess-help-mode 'motion)

  ;; Can't get roxy comment continuation to work. See
  ;; https://discordapp.com/channels/406534637242810369/406554085794381833/657282836977549352
  ;; (setq-hook! 'ess-roxy-mode-hook comment-line-break-function #'ess-roxy-indent-on-newline)

  (setq ess-default-style 'RStudio)
  ;; Follow Hadley Wickham's R style guide
  (setq
   ess-first-continued-statement-offset 2
   ess-offset-continued 0
   ess-expression-offset 0
   ess-nuke-trailing-whitespace-p t
   )

  ;; The company backends are either not set or overwritten as `ess-mode'
  ;; inherrits from `prog-mode'
  (set-company-backend! 'ess-mode 'inferior-ess-mode 'poly-markdown+r-mode)

  ;; ESS buffers should not be cleaned up automatically
  (add-hook 'inferior-ess-mode-hook #'doom-mark-buffer-as-real-h)

  ;; Open ESS R window to the left iso bottom.
  (set-popup-rule! "^\\*R:.*\\*" :side 'left :size 0.38 :select nil :ttl nil :quit nil :modeline t)
  )
;; 
;; Set RStudio keyboard shortcut Alt+- for entering <-
(global-set-key (kbd "M--") " <- ")
;; (global-set-key (kbd "M->") " %>%")
(global-set-key (kbd "M-+") " %>%")

;; Ways to disable smartparens for specific characters or fully in a mode.
;; https://github.com/hlissner/doom-emacs/issues/576
(after! smartparens
  ;; this pair change below does not work as good as just disabling overall
  ;; (which i seem to prefer anyway)
  ;; (sp-with-modes 'markdown-mode
  ;;   (sp-local-pair "`" nil))
  ;; (add-hook 'ess-r-mode-hook    #'turn-off-smartparens-mode)
  (add-hook 'markdown-mode-hook #'turn-off-smartparens-mode))
;; ----------------------------------------------------------------------------

;; ----------------------------------------------------------------------------
;; Activate polymode when loading Rmarkdown documents.
(use-package! polymode)

(after! markdown-mode
  ;; Disable trailing whitespace stripping for Markdown mode
  (add-hook 'markdown-mode-hook #'doom-disable-delete-trailing-whitespace-h)
  ;; Doom adds extra line spacing in markdown documents
  (add-hook! 'markdown-mode-hook :append (setq line-spacing nil)))

;;(use-package! yaml-mode
  ;;:mode ("\\.yml" . yaml-mode))
;; ----------------------------------------------------------------------------

;; ----------------------------------------------------------------------------
;; Misc stuff.
;;
;; This helps in aligning operators.
(use-package! evil-lion
  :after evil
  :config (evil-lion-mode))

(setq
  +workspaces-on-switch-project-behavior t
  projectile-project-search-path '("~/projects"))
(add-hook 'treemacs-mode #'treemacs-follow-mode)
;; ----------------------------------------------------------------------------
</pre></details>

**System information**
<details><pre>
```
emacs   version    26.3
        features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD LCMS2
        build      Sep 16, 2019
        buildopts  (--build=x86_64-linux-gnu --prefix=/usr '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' --sysconfdir=/etc --localstatedir=/var --disable-silent-rules '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' --disable-maintainer-mode --disable-dependency-tracking --prefix=/usr --sharedstatedir=/var/lib --program-suffix=26 --with-modules --with-file-notification=inotify --with-mailutils --with-x=yes --with-x-toolkit=gtk3 --with-xwidgets --with-lcms2 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/emacs26-TP6iDo/emacs26-26.3~1.git96dd019=. -fstack-protector-strong -Wformat -Werror=format-security -no-pie' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro -no-pie')
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop c0116d144 2019-12-13 14:56:25 -0500
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/bash
        uname      Linux 4.4.0-17763-Microsoft #864-Microsoft Thu Nov 07 15:22:00 PST 2019 x86_64
        path       (~/bin/ /usr/local/sbin/ /usr/local/bin/ /usr/sbin/ /usr/bin/ /sbin/ /bin/ /usr/games/ /usr/local/games/ /snap/bin/ /usr/lib/x86_64-linux-gnu/emacs/26.3/x86_64-linux-gnu/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion (company +tng) (ivy +prescient +icons) :ui doom doom-dashboard hl-todo modeline nav-flash (popup +all +defaults) treemacs vc-gutter vi-tilde-fringe (window-select +numbers) workspaces :editor (evil +everywhere) fold multiple-cursors snippets :emacs dired electric ibuffer vc :term shell :tools debugger (eval +overlay) flycheck (lookup +docsets) magit pdf :lang data emacs-lisp ess markdown (org +dragndrop +ipython +pandoc +present) python sh :config (default +bindings +smartparens))
        packages   (n/a)
        elpa       (n/a)
```
</pre></details>

**Comment by hlissner** [comment]
Ah, this is because `comment-line-break-function` is passed a single argument and I assume `ess-roxy-indent-on-newline` doesn't take any. This can be fixed by wrapping it in a closure that does:

```elisp
(setq-hook! 'ess-roxy-mode-hook 
  comment-line-break-function 
  (lambda (&optional _) (ess-roxy-indent-on-newline))
```

**Comment by paullemmens** [comment]
Mmm, that gives me a `Lisp nesting exceeds 'max-lisp-eval-dept'` (and no newline at all).

**Comment by paullemmens** [comment]
Hi @hlissner may I ask to have another look at the code suggestion that you provided given the above error that I get with it?

**Comment by paullemmens** [comment]
With the new channels structure in Discord I happened to learn about the sandbox. I used that to find out that in vanilla Doom the comment continuation in Roxygen code works as expected @hlissner. However, when I switch to Doom+ (in which I have the ESS  module activated), comment continuation no longer works.

I tried reverting the code that you added to the `ess` module related to #2233 . Given my limited knowledge about Doom and elisp, however, I couldn't find a magic trick that made it work.

Help really appreciated! Thanks!

**Comment by paullemmens** [comment]
From discord for memory. Will report on yes/no works

@lappie Try:

(setq-hook! 'ess-roxy-mode-hook comment-line-break-function nil)


Not a real solution, but I'm not aware of a better alternative atm

**Comment by paullemmens** [comment]
The code suggestion in the comment from Jan 31 also doesn't appear to work. I'm planning to do a major upgrade next week and will remember to again look into this.

**Comment by paullemmens** [comment]
I finally managed to find a working solution. Still not sure why it doesn't work out of the box (@hlissner is neither as discussed on discord). @safre19 you could try and see whether the code below works for you too.

```
(map!    
  (:map ess-roxy-mode-map
     :i     "RET" #'ess-indent-new-comment-line))
```

Re-reading the #2233 bug and still feels really close. Not entirely sure whether it really is an ESS only issue. Nevertheless closing this with workaround (for at least me)
