### ISSUE TITLE
Symbol’s value as variable is void

### ISSUE THREAD

**Issue by ndowens** [hlissner/doom-emacs#2331]
**What did you expect to happen?**
Install doom-emacs

**What actually happened?**
Symbol’s value as variable is void
I get this when trying  to do anything with bin/doom
I tried running doom --debug install but it just gives same error

**System information:**
Alpine Linux

It does not give what variable is void at all
it just gives:
" Symbol’s value as variable is void: "
and that is it.

**Comment by hlissner** [comment]
I presume you've found the cause of this issue?

**Comment by ndowens** [comment]
It seems to be only a issue on Alpine vs my other distro I use

**Comment by hlissner** [comment]
Sorry to revive an old issue, but could you be more specific? Another user is reporting this same issue on Alpine edge on our Discord, and I'm out of ideas.
