### ISSUE TITLE
[BUG] save-buffer report hash-table-p

### ISSUE THREAD

**Issue by chengyi** [hlissner/doom-emacs#2334]
**What did you expect to happen?**
save buffer without error

**What actually happened?**
it reports hash-table-p wrong-type-argument

**Additional details:**
- Save buffer wtih `C-x C-s`

<details><pre>
Debugger entered--Lisp error: (wrong-type-argument hash-table-p nil)
  puthash(undo-tree-id0 #<marker at 41758 in plugin-resource-dbus.c> nil)
  undo-tree-move-GC-elts-to-pool((#<marker at 41758 in plugin-resource-dbus.c> . -1))
  #f(compiled-function () #<bytecode 0x16aa4c5>)()
  apply(#f(compiled-function () #<bytecode 0x16aa4c5>) nil)
  undo-list-transfer-to-tree()
  undo-tree-save-history(nil t)
  undo-tree-save-history-hook()
  run-hook-with-args-until-success(undo-tree-save-history-hook)
  basic-save-buffer(t)
  save-buffer(1)
  funcall-interactively(save-buffer 1)
  call-interactively(save-buffer nil nil)
  command-execute(save-buffer)

</pre></details>

**Steps to reproduce:**
1. open a file and modify it, then save. this will success without error
2. modify again.
3. save buffer. it will report error
4. save again. finally success.

**System information:**
<details><pre>
<details>

```
emacs   version    26.3
        features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2
        build      8月 30, 2019
        buildopts  (--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-modules 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now)
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop, origin/develop 31b9ded19 2020-01-08 09:47:56 +0800
        dir        ~/.doom.d/
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /usr/bin/zsh
        uname      Linux 4.19.91-1-MANJARO #1 SMP Sat Dec 21 11:18:44 UTC 2019 x86_64
        path       (~/.local/bin /usr/local/bin /usr/bin /bin /usr/local/sbin /opt/android-ndk /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /usr/lib/emacs/26.3/x86_64-pc-linux-gnu)
config  envfile    nil
        elc-files  0
        modules    (:completion company (ivy +fuzzy) prow-company :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) vc-gutter vi-tilde-fringe window-select workspaces prow-highlight prow-hydra prow-treemacs :editor file-templates fold snippets prow-edit :emacs vc :term vterm :tools eval flycheck (lookup +docsets) lsp magit gtags :lang (cc +lsp) prow-c-c++ emacs-lisp lua (org +dragndrop +ipython +pandoc +present) (python +lsp) (rust +lsp) (sh +zsh) prow-markdown :email mu4e :config (default +bindings +smartparens))
        packages   (cnfonts blog-admin jinja2-mode (mu4e-maildirs-extension :disable t) (org-mu4e :disable t) (glsl-mode :disable t) (opencl-mode :disable t) (disaster :disable t) (cuda-mode :disable t) (demangle-mode :disable t) (fzf :recipe (:host github :repo "tttuuu888/fzf.el" :branch "work-projectile-compatibility")))
        elpa       (n/a)
```
</details>
</pre></details>

**Comment by hlissner** [comment]
This issue was introduced in the latest update of [undo-tree](http://www.dr-qubit.org/Lost_undo-tree_history.html). dc22815 should fix this temporarily. I'll leave this issue open until it is fixed upstream.

**Comment by hlissner** [comment]
undo-tree 0.7.1 should have resolved this issue. Update to 15f2245 to see the changes. Let me know if that isn't the case and I'll reopen the issue. Thanks for bringing it to my attention!

**Comment by ocharles** [comment]
I'm still getting this - I ran `./bin/doom upgrade` a few minutes ago.

**Comment by hlissner** [comment]
@ocharles Open undo-tree with `SPC h P undo-tree`. At the top of the file do you see this?

```elisp
;; Version: 0.7.1
```

**Comment by ocharles** [comment]
Ah, I'm on 0.7

I see now my `doom/upgrade` wasn't clean:

```
  ! (20/200) Encountered error with undo-tree                                                                     
    x (error Cannot display prompt in batch mode: In repository "undo-tree", remote "origin" has URL
      "https://github.com/emacsmirror/undo-tree.git"                                                              
    but recipe specifies a URL of                                                                                 
      "https://github.com/emacs-straight/undo-tree.git") 
```

**Comment by ocharles** [comment]
Usually it prompts me, I dunno why it just happily carried on this time. A second `bin/doom upgrade` has prompted me again, and I've told it to delete `origin` and recreate it.
