### ISSUE TITLE
[BUG] Open treemacs window prevents undoing of doom/window-maximize-buffer

### ISSUE THREAD

**Issue by WhatDothLife** [hlissner/doom-emacs#2337]
When keeping an treemacs window open, the behavior of
`doom/window-maximize-buffer` is altered in the way, that it prevents the
restoring of the previous window layout, after calling the function a second time.

When there is no open treemacs window the command works as it should.
This has been tested without my private config.

* Steps to reproduce:
1. Split main window
2. Open treemacs
3. Call `doom/window-maximize-buffer` to maximize the current buffer
4. Call `doom/window-maximize-buffer` a second time to undo the maximization.

**Comment by hlissner** [comment]
As of 59a6cb7 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
