### ISSUE TITLE
[REQUEST] smart line join for comments

### ISSUE THREAD

**Issue by WhatDothLife** [hlissner/doom-emacs#2338]
When writing a comment that spans multiple lines there should be a smart join
function that deals with the trailing comment characters.

E.g.:

The following elisp comment
```;; This is a 
;; comment```
should be joined to 
```;; This is a comment```
instead of
```;; This is a ;; comment```

**Comment by dinkonin** [comment]
`fill-region` or `evil-fill` do that for me.

**Comment by WhatDothLife** [comment]
Awesome, thanks a lot.
