### ISSUE TITLE
SPC in go-mode bound to leader in non evil enabled configuration

### ISSUE THREAD

**Issue by nickecarlopack** [hlissner/doom-emacs#234]
Hey, first off, thanks a lot for this distribution. Its pulling me back toward Emacs after a 6 month hiatus. Much better than Spacemacs!!

I use emacs with the default key bindings so the first thing I did was comment out everything evil mode related in the init.el file aka the following two lines.

`;evil              ; come to the dark side, we have cookies`
`;evil-goggles      ; display visual hints when editing in evil`

However, while in go-mode I am unable to use the space bar at all in the code because it is bound to some other operation. I believe that maybe a remnant of the keybindings specific to evil mode bleeding through?

A nudge in the right direction would be really appreciated so I can start using emacs with your great setup!

Thanks again.

**Comment by hlissner** [comment]
The "leader" and "localleader" prefix keys in Doom are bound to the space bar, which means SPC is getting overwritten anywhere a mode map has a leader/localleader binding. In go's case, [there are four](https://github.com/hlissner/doom-emacs/blob/master/modules/lang/go/config.el#L59-L62).

To fix this, I suggest you change `doom-leader-key` and `doom-localleader-key` to something more meaningful to a vanilla Emacs user. You'll have to do this in either your public init.el (\~/.emacs.d/init.el) _before the `(doom! ...)`_ block, or in your private init.el file (\~/.emacs.d/modules/private/$USER/init.el). e.g.

```emacs-lisp
(setq doom-leader-key "C-c SPC"
      doom-localleader-key "C-c m")
```

Sorry about that, this is an oversight on my part. Making Doom more evil-agnostic is an ongoing effort.

**Comment by nickecarlopack** [comment]
Setting it in private init.el fixed it!

Thank you!

Appreciate you making your personal config available publicly. Awesome job!

**Comment by hlissner** [comment]
No problem!
