### ISSUE TITLE
[BUG] No formatter specified for cuda-mode

### ISSUE THREAD

**Issue by WhatDothLife** [hlissner/doom-emacs#2341]
Currently there is no formatter specified for cuda-mode by default. We should use
`clang-format` for this. I'd fix this myself, but don't know which variable to
modify.

**Comment by hlissner** [comment]
Will one of these two lines work?

```elisp
(after! cuda-mode
  (set-formatter! 'cuda-mode 'clang-format)
  ;; or
  (setq-hook! 'cuda-mode +format-with 'clang-format)
  )
```

**Comment by WhatDothLife** [comment]
I evaluated `(set-formatter! 'cuda-mode 'clang-format)` which returned nil. 
Then, calling `(+format/region-or-buffer)` on a cuda buffer returned *Symbol’s function definition is void: nil*. Here's the backtrace:
<details><pre>
Debugger entered--Lisp error: (void-function nil)
  nil(clang-format nil nil)
  funcall(nil clang-format nil nil)
  (let ((fn (funcall (cond ((stringp formatter) (function +format--make-shell-command)) ((listp formatter) (function +format--make-shell-command-list)) ((and (commandp formatter) (not ...)) (function +format--make-command)) ((functionp formatter) (function +format--make-function))) formatter ok-statuses error-regexp))) (progn (or (or (functionp filter) (null filter)) (signal (quote wrong-type-argument) (list (quote (or function null)) filter (quote filter)))) nil) (+format--set name :function (list (quote lambda) (quote (executable mode-result)) (if filter (list (quote apply) (list (quote function) filter) fn) fn)) :modes modes) name)
  (if (null formatter) (+format--set name :unset t :modes modes) (let ((fn (funcall (cond ((stringp formatter) (function +format--make-shell-command)) ((listp formatter) (function +format--make-shell-command-list)) ((and ... ...) (function +format--make-command)) ((functionp formatter) (function +format--make-function))) formatter ok-statuses error-regexp))) (progn (or (or (functionp filter) (null filter)) (signal (quote wrong-type-argument) (list (quote (or function null)) filter (quote filter)))) nil) (+format--set name :function (list (quote lambda) (quote (executable mode-result)) (if filter (list (quote apply) (list (quote function) filter) fn) fn)) :modes modes) name))
  (closure ((error-regexp) (ok-statuses) (filter) (modes) (--cl-rest--) (formatter . clang-format) (name . cuda-mode) t) nil (if (null formatter) (+format--set name :unset t :modes modes) (let ((fn (funcall (cond (... ...) (... ...) (... ...) (... ...)) formatter ok-statuses error-regexp))) (progn (or (or (functionp filter) (null filter)) (signal (quote wrong-type-argument) (list (quote ...) filter (quote filter)))) nil) (+format--set name :function (list (quote lambda) (quote (executable mode-result)) (if filter (list (quote apply) (list ... filter) fn) fn)) :modes modes) name)))()
  eval-after-load-helper("/home/michael/.emacs.d/.local/straight/build/format-all/format-all.elc")
  run-hook-with-args(eval-after-load-helper "/home/michael/.emacs.d/.local/straight/build/format-all/format-all.elc")
  do-after-load-evaluation("/home/michael/.emacs.d/.local/straight/build/format-all/format-all.elc")
  (format-all--probe)
  (let* ((val (format-all--probe)) (x15 (car val)) (x16 (cdr val)) (x17 (car x16)) (x18 (cdr x16))) (let ((mode-result x17) (formatter x15)) (let* ((val (+format-buffer formatter mode-result (or +format-preserve-indentation +format-region-p)))) (cond ((eq val (quote no-formatter)) (if (called-interactively-p (quote any)) (progn (message "No formatter specified for %s" major-mode))) nil) ((eq val (quote error)) (message "Failed to format buffer due to errors") nil) ((eq val (quote noop)) (message "Buffer was already formatted") nil) (t (message "Formatted (%s)" formatter) t)))))
  (let ((+format-with (or (if arg (+format-completing-read)) +format-with))) (let* ((val (format-all--probe)) (x15 (car val)) (x16 (cdr val)) (x17 (car x16)) (x18 (cdr x16))) (let ((mode-result x17) (formatter x15)) (let* ((val (+format-buffer formatter mode-result (or +format-preserve-indentation +format-region-p)))) (cond ((eq val (quote no-formatter)) (if (called-interactively-p ...) (progn ...)) nil) ((eq val (quote error)) (message "Failed to format buffer due to errors") nil) ((eq val (quote noop)) (message "Buffer was already formatted") nil) (t (message "Formatted (%s)" formatter) t))))))
  +format/buffer(nil)
  funcall-interactively(+format/buffer nil)
  call-interactively(+format/buffer)
  +format/region-or-buffer()
  funcall-interactively(+format/region-or-buffer)
  call-interactively(+format/region-or-buffer nil nil)
  command-execute(+format/region-or-buffer)
</pre></details>

Evaluating `(setq-hook! 'cuda-mode +format-with 'clang-format)` doesn't solve the issue neither. When `(+format/region-or-buffer)` is called the minibuffer reads *No formatter specified for cuda-mode*. A reason might be that cuda-mode doesn't offer a hook.
