### ISSUE TITLE
[BUG] +lookup/in-docsets and +lookup/in-all-docsets errors

### ISSUE THREAD

**Issue by JackTheMico** [hlissner/doom-emacs#2346]
**What did you expect to happen?**
+lookup/indocsets and +lookup/in-all-docsets work fine.

**What actually happened?**
Both two functions went error, seems like the function named "+lookup-symbol-or-region" is not found.

**Additional details:**
- Include a link to your private config
https://github.com/JackTheMico/mydoomemacs
- Include screenshots/casts of your issue
![Snipaste_2020-01-10_17-13-51](https://user-images.githubusercontent.com/19216598/72140960-dd750480-33cc-11ea-94e4-f6be9cc2a217.png)

- If you mention key sequences, include what commands they're bound to (use `SPC
  h k KEY` or `C-h h k KEY` to inspect keys).
- Include any warnings or errors logged to \*Messages\* (use `M-x
  view-echo-area-messages` to see it).

<details><pre>
```emacs-lisp
Debugger entered--Lisp error: (void-function +lookup-symbol-or-region)
  (+lookup-symbol-or-region)
  (or query (+lookup-symbol-or-region) "")
  (let ((dash-docs-common-docsets) (dash-docs-docsets (if arg (dash-docs-installed-docsets) (cl-remove-if-not (function dash-docs-docset-path) (or docsets dash-docs-docsets)))) (query (or query (+lookup-symbol-or-region) ""))) (if doom-debug-mode (progn (let ((inhibit-message (active-minibuffer-window))) (message #("DOOM Searching docsets %s" 0 5 (face font-lock-comment-face)) dash-docs-docsets)))) (cond (nil (helm-dash query)) (t (counsel-dash query)) ((user-error "No dash backend is installed, enable ivy or helm."))))
  +lookup/in-docsets(nil)
  funcall-interactively(+lookup/in-docsets nil)
  call-interactively(+lookup/in-docsets nil nil)
  command-execute(+lookup/in-docsets)
```
</pre></details>

**Steps to reproduce:**
1. open doom eamcs
2. open a python or a .el file
3. use SPC-s-k or SPC-s-K

**System information:**
<details><pre>
((emacs
  (version . "26.3")
  (features . "XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2")
  (build . "8月 30, 2019")
  (buildopts "--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-modules 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop f6852a2c9 2020-01-09 03:36:00 -0500")
  (dir . "~/.doom.d/"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/usr/bin/zsh")
  (uname . "Linux 4.19.84-microsoft-standard #1 SMP Wed Nov 13 11:44:37 UTC 2019 x86_64")
  (path "~/.pyenv/plugins/pyenv-virtualenv/shims" "~/.pyenv/shims" "~/.pyenv/shims" "~/.pyenv/shims" "~/bin" "/usr/local/bin" "/usr/sbin" "~/.emacs.d/bin" "~/.gem/ruby/2.6.0/bin" "~/.pyenv/bin" "~/.local/bin" "~/.pyenv/plugins/pyenv-virtualenv/shims" "~/.pyenv/shims" "~/.pyenv/shims" "~/.pyenv/shims" "~/bin" "/usr/local/bin" "/usr/sbin" "~/.emacs.d/bin" "~/.gem/ruby/2.6.0/bin" "~/.pyenv/bin" "~/.pyenv/plugins/pyenv-virtualenv/shims" "~/.pyenv/shims" "~/.pyenv/shims" "~/.pyenv/shims" "~/bin" "/usr/local/bin" "/usr/sbin" "~/.emacs.d/bin" "~/.gem/ruby/2.6.0/bin" "~/.pyenv/bin" "~/.local/bin" "/usr/local/sbin" "/usr/local/bin" "/usr/sbin" "/usr/bin" "/sbin" "/bin" "/usr/games" "/usr/local/games" "/mnt/d/Program Files/AdoptOpenJDK/jdk-11.0.4.11-hotspot/bin" "/mnt/c/WINDOWS/system32" "/mnt/c/WINDOWS" "/mnt/c/WINDOWS/System32/Wbem" "/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/" "/mnt/c/WINDOWS/System32/OpenSSH/" "/mnt/c/Program Files/Intel/WiFi/bin/" "/mnt/c/Program Files/Common Files/Intel/WirelessCommon/" "/mnt/c/ProgramData/chocolatey/bin" "/mnt/d/Program Files/TortoiseSVN/bin" "/mnt/c/Program Files (x86)/Windows Kits/8.1/Windows Performance Toolkit/" "/mnt/d/Jack Deng/salt" "/mnt/c/Program Files/OpenSSH-Win64" "/mnt/d/Program Files (x86)/Yarn/bin/" "/mnt/d/Program Files/Git/cmd" "/mnt/c/WINDOWS/system32" "/mnt/c/WINDOWS" "/mnt/c/WINDOWS/System32/Wbem" "/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/" "/mnt/c/WINDOWS/System32/OpenSSH/" "/mnt/d/Program Files/Process Lasso/" "/mnt/d/python36" "/mnt/d/python36/Scripts" "/mnt/d/python36/Library/bin" "/mnt/d/Program FIles/TortoiseSVN/bin" "/mnt/d/Microsoft VS Code/bin" "/mnt/c/Users/Jack Deng/AppData/Local/Microsoft/WindowsApps" "/mnt/d/Jack Deng/bin" "/mnt/d/Jack Deng/bin/scrcpy-win64-v1.10" "/mnt/d/cygwin64/bin" "/mnt/d/Program Files/AdoptOpenJDK/jdk-11.0.4.11-hotspot/bin" "/mnt/c/Users/Jack Deng/AppData/Local/Yarn/bin" "/mnt/c/Users/Jack Deng/AppData/Local/GitHubDesktop/bin" "/mnt/c/Users/Jack Deng/AppData/Local/Microsoft/WindowsApps" "/mnt/d/Jack Deng/bin/libav-x86_64-w64-mingw32-20180108/usr/bin" "/mnt/d/Jack Deng/bin/LxRunOffline-v3.4.0" "/usr/lib/jvm/default/bin" "/usr/bin/site_perl" "/usr/bin/vendor_perl" "/usr/bin/core_perl" "/usr/lib/jvm/default/bin" "/usr/bin/site_perl" "/usr/bin/vendor_perl" "/usr/bin/core_perl" "/usr/lib/emacs/26.3/x86_64-pc-linux-gnu"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :input chinese :completion company (ivy +icons +fuzzy +prescient) :ui deft doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) fold multiple-cursors snippets :emacs (dired +ranger +icons) electric ibuffer vc :term vterm :tools debugger docker (eval +overlay) (flycheck +childframe) (lookup +devdocs +docsets) lsp magit pdf :lang data emacs-lisp markdown (org +brain +dragndrop +babel +capture +export +habit +gnuplot +pomodoro +present) (python +pyenv +lsp) sh :email (mu4e +gmail) :config (default +bindings +smartparens))
  (packages "(nyan-mode :recipe (:host github :repo \"TeMPOraL/nyan-mode\"))" "(lsp-python-ms :recipe (:host github :repo \"emacs-lsp/lsp-python-ms\"))" "(youdao-dictionary :recipe (:host github :repo \"xuchunyang/youdao-dictionary.el\"))")
  (elpa "n/a")))

</pre></details>

**Comment by hlissner** [comment]
As of 7801001 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by hlissner** [comment]
Side-question: why are you doing all that work with `file-name-handler-alist`, `gc-cons-threshold` and GC minibuffer hooks? Those are already done for you by Doom.

**Comment by JackTheMico** [comment]
Thanks for fix. I don't know those are already done by Doom, I'll remove it from my config file.Thanks again!
