### ISSUE TITLE
Adding commands to C-c C-c for LaTeX

### ISSUE THREAD

**Issue by Ptival** [hlissner/doom-emacs#235]
Hey, this might not be related to Doom, but I'm not sure which packages are involved in what happens (maybe org? maybe ivy?).

When a .tex file is opened, running C-c C-c raises an appropriate pane with valid options like latex/pdflatex/bibtex. However, there is no xetex/xelatex, and I can't figure out a way to add those there.

I can type the command there, but that pane also has no "history", so I need to retype the command every time. Any pointers to getting this set up to my needs would be much appreciated!

**Comment by hlissner** [comment]
This is actually an issue with the latex-mode and auctex not having a xetex build command. Perhaps this SO question can help you](https://tex.stackexchange.com/questions/21200/auctex-and-xetex). Something like this should work for you:

```emacs-lisp
(add-hook! LaTeX-mode
  (add-to-list TeX-command-list '("XeLaTeX" "%`xelatex%(mode)%' %t" TeX-run-TeX nil t))
  (setq TeX-command-default "XeLaTeX"
        TeX-save-query nil
        TeX-show-compilation t))
```

I'm not familiar with xetex, so I can't say if this will work or not.

**Comment by Ptival** [comment]
Oh wow, I am stupid! I had just reset my `init.el` and had not uncommented `latex`, so it was not even using AUCTex!

AUCTeX actually offered me the option to use XeTeX out of the blue with a very intuitive menu! Nevermind me! :s
