### ISSUE TITLE
[REQUEST] Any plan to extract ui/popup?

### ISSUE THREAD

**Issue by aaronjensen** [hlissner/doom-emacs#2352]
Hi there, I've got my own Emacs config but I've been inspired by and borrowing bits and pieces from doom. It's fantastic, nice work.

I was curious if you have any plans to extract your ui/popup code into its own package. I'm wanting to something for popup management and I see that you've gone through popwin and shackle and ended up writing your own, which seems to work quite well. 

Would extracting it to its own package be feasible?

Thanks!

**Comment by hlissner** [comment]
I have no plans to do so. It's somewhat-tightly coupled with Doom. Shackle is its closest analogue (and is more general); I'd recommend that. Otherwise, these are all abstractions over `display-buffer-alist`, which you could modify directly.

**Comment by aaronjensen** [comment]
Got it, makes sense. Thank you for the recommendation. Feel free to close.

**Comment by aaronjensen** [comment]
One other question, what was your motivation for switching from shackle to rolling your own? Any limitations of shackle I should be aware of?

**Comment by aaronjensen** [comment]
@hlissner I've started extracting it, the close/restore is invaluable to me. I hope that you don't mind. It's here: 

https://github.com/aaronjensen/emacs-popup-mode/

I don't intend to release on MELPA and I would gladly hand it over if you'd like it. It actually didn't take much to do, though I still need to sort out how you've got q/C-g/esc all closing popups correctly.

**Comment by hlissner** [comment]
> One other question, what was your motivation for switching from shackle to rolling your own? Any limitations of shackle I should be aware of?

I essentially wanted lower-level control over `display-buffer-alist`. The only real limitation of shackle is that it abstracts much of the underlying machinery.

>  I hope that you don't mind.

I don't mind, feel free to do with it as you like.

>  though I still need to sort out how you've got q/C-g/esc all closing popups correctly.

That is handled by `doom/escape`, which is [defined in core-keybinds.el](https://github.com/hlissner/doom-emacs/blob/develop/core/core-keybinds.el#L35-L71), and [bound on `+popup-buffer-mode-map`](https://github.com/hlissner/doom-emacs/blob/develop/modules/ui/popup/config.el#L42-L49).

Hope that helps!

**Comment by aaronjensen** [comment]
Thank you, much appreciated. I've got it working well now. I'll let you know if I have any questions as I continue to use it.

**Comment by aaronjensen** [comment]
@hlissner I've noticed an unfavorable behavior on both doom and my extracted popup. If I have an org file open, then I edit a src block, it pops up below the org file. If I confirm or cancel it, the popup disappears as I expect.

However, if I first do a `g d` on something in that buffer, it will reuse the popup window to show the definition. Killing that buffer won't return to the edit src buffer and that window will no longer behave like a popup, even if I reselect the edit src buffer manually. In that case, confirming or canceling the edit will leave the popup window open and I have to close it manually.

Is there a way to configure things to avoid this?

**Comment by aaronjensen** [comment]
I've fixed this by making the org src window dedicated. I wonder if the popup configuration would benefit from a `:dedicated` flag for this purpose?
