### ISSUE TITLE
[HOWTO] Override doom module use-package variable configuration

### ISSUE THREAD

**Issue by howsiwei** [hlissner/doom-emacs#2355]
**What are you trying to achieve?**
```elisp
  (setq-default pdf-view-display-size 'fit-width)
```

**What have you tried?**
Add
```elisp
  (setq-default pdf-view-display-size 'fit-width)
```
to `config.el`.

However, this doesn't work as it's overridden by `pdf` module during `use-package! pdf-tools :config`.

**Comment by hlissner** [comment]
The [canonical way to configure packages](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#configuring-packages) is to wrap your configuration in `(after! PACKAGE ...)` or in `use-package` blocks, to ensure that your settings overwrite Doom's defaults.

Give this a try:

```elisp
(after! pdf-view
  (setq-default pdf-view-display-size 'fit-width))
```

**Comment by howsiwei** [comment]
Strange. I thought I have tried the `after!` method and it didn't work. Probably mistake on my behalf. Anyway it works now with the suggested code. Thank you!

**Comment by howsiwei** [comment]
`(after! pdf-view ...)` doesn't work but `(after! pdf-tools ...)` works. Thank you!
