### ISSUE TITLE
Projectile forgets projects on relaunch

### ISSUE THREAD

**Issue by teesloane** [hlissner/doom-emacs#236]
Hello!

Just got into DOOM today and have been having lots of fun learning my way through it. I'm coming from the spacemacs world for context.

One issues I'm stumbling over: it seems like projectile can't remember the projects i've opened after relaunching emacs. This might just be my lack of knowledge on projectile. In spacemacs having opened a project in projectile would then remember the project going forward. 

Steps to recreate:

- open emacs
- navigate to a file in a project using `SPC f .`
- open a file
- close emacs
- reopen, try `SPC p p` --> no projects. 

Thanks for any tips and an awesome setup!

**Comment by hlissner** [comment]
This is definitely a bug. Turns out projectile's list of known projects isn't being initialized early enough. The projects list refreshes itself once you've opened a file (any file).

In any case, this is now fixed in the `develop` branch.

**Comment by teesloane** [comment]
Awesome! Thanks for letting me know!
