### ISSUE TITLE
[BUG] org-agenda not showing TODO items with children

### ISSUE THREAD

**Issue by soedirgo** [hlissner/doom-emacs#2365]
**What did you expect to happen?**
TODO items should show up whether or not it has children.

**What actually happened?**
Only ones with children show up.

**Additional details:**
- Include a link to your private config
Tested on fresh doom installation on macOS 10.15.2 and Ubuntu 19.04
- Include screenshots/casts of your issue
<img width="703" alt="Screen Shot 2020-01-13 at 10 33 50 PM" src="https://user-images.githubusercontent.com/31685197/72264763-35726c00-3656-11ea-832e-8b6283b43d60.png">

**Steps to reproduce:**
1. Add a new org file in `~/org/`,
2. Add nested TODO items,
3. Check the agenda view with `SPC o A` `T` `TODO` `RET`.

**System information:**
<details>

```
emacs   version    26.3
        features   NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS LCMS2
        build      Aug 30, 2019
        buildopts  (--with-mac --enable-mac-app=/Users/travis/build/railwaycat/homebrew-emacsmacport/build-scripts/emacs-source/tmproot --prefix=/Users/travis/build/railwaycat/homebrew-emacsmacport/build-scripts/emacs-source/tmproot --enable-mac-self-contained --with-modules)
        windowsys  mac
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop, origin/develop, origin/HEAD 6f273ffc2 2020-01-13 01:46:43 -0500
        dir        ~/.doom.d/
system  type       darwin
        config     x86_64-apple-darwin18.5.0
        shell      /usr/local/bin/zsh
        uname      Darwin 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64
        path       (/usr/local/opt/llvm/bin/ ~/.rbenv/shims/ ~/miniconda3/bin/ ~/miniconda3/condabin/ ~/.cargo/bin/ /usr/local/bin/ /usr/bin/ /bin/ /usr/sbin/ /sbin/ /Library/TeX/texbin/ /Library/Frameworks/Mono.framework/Versions/Current/Commands/ ~/.emacs.d/bin/ /Applications/Emacs.app/Contents/MacOS/libexec/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold multiple-cursors rotate-text snippets :emacs dired electric ibuffer vc :checkers syntax :tools (eval +overlay) (lookup +docsets) magit :lang data emacs-lisp markdown (org +dragndrop +present) sh :config (default +bindings +smartparens))
        packages   (n/a)
        elpa       (n/a)
```
</details>

**Comment by alphapapa** [comment]
What you seem to mean, according to the screenshot, is that only TODOs *without children* are shown.

It would be surprising if Doom were doing something to interfere with this.

A possible discrepancy: the screenshot shows that it's showing `ALL` items, but in your step 3 you typed `TODO`, and I don't know what purpose that serves, because it doesn't appear to have had any effect.

**Comment by hlissner** [comment]
This might be because we've set `org-agenda-dim-blocked-tasks` to `'invisible` by default. This will hide TODOs that are "blocked" by child TODOs. i.e. If you haven't finished the child todo, there's no way you're done with the parent todo, so hide it. Perhaps this isn't a sensible default?

This should reverse it:

```elisp
(after! org
  (setq org-agenda-dim-blocked-tasks t))
```

**Comment by soedirgo** [comment]
I see. What I was trying to do was to show a list of projects (TODO items with the TODO keyword `PROJ`) in agenda view. Setting `org-agenda-dim-blocked-tasks` to `nil` does revert the behavior. Thanks!
