### ISSUE TITLE
[BUG] Executing `+debugger/start` always returns `no debugging session to quit` (go-mode)

### ISSUE THREAD

**Issue by cxb811201** [hlissner/doom-emacs#2367]
**What did you expect to happen?**
`+debugger/start` can execute normally

**What actually happened?**
`+debugger/start` does not execute normally
always returns `No debugging session to quit`
`dap-debug` can execute normally

**System information:**
<details><pre>
((emacs
  (version . "28.0.50")
  (features . "XPM JPEG TIFF GIF PNG RSVG CAIRO IMAGEMAGICK SOUND GPM DBUS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER LCMS2 GMP")
  (build . "Jan 14, 2020")
  (buildopts "--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --mandir=/usr/share/man --with-gameuser=:games --with-sound=alsa --with-modules --without-gconf --without-gsettings --enable-link-time-optimization --with-x-toolkit=gtk3 --without-xaw3d --without-m17n-flt --with-imagemagick --with-cairo --with-xwidgets --without-compress-install 'CFLAGS=-march=ivybridge -O2 -pipe -fno-plt -g -flto -fuse-linker-plugin -s -fuse-ld=gold' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD 12094788d 2020-01-14 03:04:26 -0500")
  (dir . "~/.doom.d/"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/usr/bin/zsh")
  (uname . "Linux 5.5.0-rc6 #1 SMP PREEMPT Mon Jan 13 11:28:29 CST 2020 x86_64")
  (path "~/.gem/ruby/2.6.0/bin" "~/.go/bin" "~/.cargo/bin" "~/.jenv/shims" "~/.jenv/bin" "~/.emacs.d/bin" "~/.local/bin" "~/.nvm/versions/node/v13.4.0/bin" "/usr/local/bin" "/usr/local/sbin" "/usr/bin" "/opt/intel/mediasdk/bin" "/usr/lib/jvm/default/bin" "/usr/bin/site_perl" "/usr/bin/vendor_perl" "/usr/bin/core_perl" "~/.antigen/bundles/robbyrussell/oh-my-zsh/lib" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/git" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/gitfast" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/git-remote-branch" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/colored-man-pages" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/history" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/z" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/extract" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/encode64" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/web-search" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/urltools" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/tmux" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/docker" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/docker-compose" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/archlinux" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/cargo" "~/.antigen/bundles/djui/alias-tips" "~/.antigen/bundles/zdharma/fast-syntax-highlighting" "~/.antigen/bundles/zsh-users/zsh-autosuggestions" "~/.antigen/bundles/hlissner/zsh-autopair" "~/.antigen/bundles/romkatv/powerlevel10k" "/usr/lib/emacs/28.0.50/x86_64-pc-linux-gnu"))
 (config
  (envfile)
  (elc-files . 0)
  (modules :input chinese :completion (company +childframe) (ivy +prescient +fuzzy +childframe) :ui doom doom-quit hl-todo hydra modeline nav-flash ophints (popup +all +defaults) treemacs vc-gutter (window-select +numbers) workspaces zen centered-cursor :editor file-templates lispy multiple-cursors rotate-text snippets :emacs (dired +ranger) electric (ibuffer +icons) vc :term eshell :checkers (syntax +childframe) :tools debugger docker editorconfig (eval +overlay) lookup lsp magit make (youdao +childframe) :lang data emacs-lisp (go +lsp) (java +lsp) (javascript +lsp) (kotlin +lsp) markdown (org +dragndrop +hugo +ipython +pandoc +present +pomodoro +journal) plantuml rest (scala +lsp) (sh +lsp) (web +lsp) :config (default +bindings +smartparens))
  (packages "(fcitx :disable t)" "(pangu-spacing :disable t)" "(centered-window :disable t :recipe (:host github :repo \"anler/centered-window-mode\"))" "(tide :disable t)" "(liberime-config :recipe (:host github :repo \"cxb811201/liberime\" :files (\"liberime-config.el\" \"src\" \"CMakeLists.txt\" \"Makefile\")))" "(company-english-helper :recipe (:host github :repo \"cxb811201/company-english-helper\"))" "(insert-translated-name :recipe (:host github :repo \"manateelazycat/insert-translated-name\"))" cal-china-x exec-path-from-shell hungry-delete "(go-impl :recipe (:host github :repo \"cxb811201/emacs-go-impl\"))" go-fill-struct sqlup-mode)
  (elpa "n/a")))

</pre></details>

**Comment by AGitBoy** [comment]
I'm having a similar problem in c-mode

**Comment by Fartiphukborzl** [comment]
Same problem in python-mode.

**Comment by mpsq** [comment]
This is also happening in java-mode.

**Comment by yuzhou721** [comment]
I think the problem is caused by symbol and I try to fix it

**Comment by he-la** [comment]
I think the error message should read something like `You specified no debugging session to start`; the message was probably copy-pasted from `+debugger/quit`, where a more friendly error would be something like `Found no debugging session to quit`.

To me it looks like this code is trying to duplicate the functionality of `dap-debug-last`, but in a buffer-local way. This will probably result in unexpected behavior for multi-file projects, where invoking `+debugger/start-last` will only work when run from the same buffer. Overall I think the `debugger` module could use some love here:

- Fix this error by essentially copying the implementation from `dap-debug`, but with buffer-local variables to get the desired semantics.
- Extend this to work on project-local variables (see [projectile-variables](https://github.com/emacs-php/projectile-variable), maybe doom also implements something like this already, not sure).

**Comment by hlissner** [comment]
With the help of @he-la this should be resolved now that #4708 was merged. Let me know if that isn't the case and I'll reopen this. Thanks for bringing this to my attention!
