### ISSUE TITLE
[REQUEST]  is it possible to be gitlab free ?

### ISSUE THREAD

**Issue by murphytalk** [hlissner/doom-emacs#2369]
**Describe the feature**

My new company has Gitlab enterprise deployed , for whatever reason the IT security guys decide to block gitlab.com ... as a result I cannot bootstrap doom emcas as it depends on quite some packages hosted on gitlab.com 

I was wondering is there a solution or workaround ?

**Comment by gagbo** [comment]
Packages installed though `melpa` recipes are just using `melpa` recipes. So if the maintainers for these packages decided to host on gitlab, there's no way to change that (apparently [116 packages now](https://github.com/melpa/melpa/search?q=%22%3Afetcher+gitlab%22&unscoped_q=%22%3Afetcher+gitlab%22) )

The best way is to either tether with a mobile device to get at least one clone on your computer, or else you'll have to download manually somehow I guess...
