### ISSUE TITLE
[BUG] I cannot override pretty-symbols list per language

### ISSUE THREAD

**Issue by soloidx** [hlissner/doom-emacs#2372]
**What did you expect to happen?**

On `init.el` I enabled `pretty-code` and `python` modules and in `config.el` I changed the configuration for the Python language:

```
(add-hook! python-mode
  (set-pretty-symbols! 'python-mode nil))
```

I expected to have the prettify symbols disabled for .py files

**What actually happened?**

The pretty symbols are active when I open a python file

**System information:**
<details><pre>
((emacs
  (version . "26.3")
  (features . "JPEG RSVG IMAGEMAGICK GLIB NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2")
  (build . "Aug 30, 2019")
  (buildopts "--disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus/26.3/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus/26.3 --with-xml2 --without-dbus --with-gnutls --with-imagemagick --with-modules --with-rsvg --with-ns --disable-ns-self-contained")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD 12094788d 2020-01-14 03:04:26 -0500")
  (dir . "~/.doom.d/"))
 (system
  (type . darwin)
  (config . "x86_64-apple-darwin18.5.0")
  (shell . "/bin/zsh")
  (uname . "Darwin 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64")
  (path "/usr/local/opt/openssl/bin" "~/.pyenv/shims" "/usr/local/sbin" "/usr/local/bin" "/usr/bin" "/bin" "/usr/sbin" "/sbin" "/usr/local/MacGPG2/bin" "/Library/Frameworks/Mono.framework/Versions/Current/Commands" "/usr/local/opt/llvm/bin" "/usr/local/opt/python/libexec/bin" "~/go/bin" "~/Library/Python/2.7/bin" "~/bin" "/Library/TeX/texbin" "~/.emacs.d/bin" "/usr/local/mysql/bin" "/usr/local/Cellar/emacs-plus/26.3/libexec/emacs/26.3/x86_64-apple-darwin18.5.0"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) pretty-code treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold multiple-cursors rotate-text snippets :emacs dired electric ibuffer vc :checkers syntax :tools (eval +overlay) (lookup +docsets) magit :lang data emacs-lisp (org +dragndrop +present) python sh :config (default +bindings +smartparens))
  (packages "n/a")
  (elpa "n/a")))
</pre></details>

**Comment by hlissner** [comment]
`set-pretty-symbols!` was not intended to be used in a hook. Try this instead:

```elisp
(after! python
  (set-pretty-symbols! 'python-mode nil))
```

**Comment by soloidx** [comment]
I also tested these solutions:

```
(after! python
  (set-pretty-symbols! 'python-mode nil))
```

and

```
(add-hook 'python-mode-hook
  '(lambda()(set-pretty-symbols! 'python-mode nil)))
```

with no results

**Comment by hlissner** [comment]
My snippet about will only turn off a subset of them, but not ligatures or whatever default symbols may already be in `prettify-symbols-alist` by default. To disable it totally for python-mode, you can also try:

```elisp
(setq +pretty-code-enabled-modes '(not python-mode))
```

**Comment by visini** [comment]
For anyone looking to disable symbols and keep ligatures, I solved it like this:

```
(add-hook 'python-mode-hook (lambda ()
    (setq +pretty-code-symbols-alist '(python-mode nil ))))
```
