### ISSUE TITLE
[BUG] Pinned packages are breaking due to clone depth

### ISSUE THREAD

**Issue by pekist** [hlissner/doom-emacs#2373]
**What did you expect to happen?**
...
Pinned packages should be able to be pulled

**What actually happened?**
...
Pinned packages are not being pulled

**Additional details:**
Increasing straight-vc-git-default-clone-depth (to 10 for example) fixes this. Is there a better solution than some heuristic? A better number?

**Steps to reproduce:**
./doom/bin install will currently break

**Comment by hlissner** [comment]
As of a9402cf package pinning is back. Let me know if you have any other issues with it. Thanks for bringing it to my attention!
