### ISSUE TITLE
Bug in search function: (SPC s d)

### ISSUE THREAD

**Issue by randomizedthinking** [hlissner/doom-emacs#2376]
**What did you expect to happen?**
Search the content of files the under current directory.

**What actually happened?**
An error message showed up instead: 

```
error in process sentinel: counsel--async-sentinel: Wrong number of arguments: (2 . 2), 3
error in process sentinel: Wrong number of arguments: (2 . 2), 3
Error in post-command-hook (ivy--queue-exhibit): (wrong-type-argument number-or-marker-p nil)
```

The same issue is encountered once searching the current project (SPC s p).

**Additional details:**
- If you mention key sequences, include what commands they're bound to: `+default/search-cwd`
- Include any warnings or errors logged to \*Messages\* (use `M-x
  view-echo-area-messages` to see it). Error messages included.

**Steps to reproduce:**
1. Install the latest version of doom emacs;
2. `doom upgrade`
3. `emacs`
4. Open any file;
5. `SPC s d`, then type a char

**System information:**
<details><pre>
emacs   version    26.3
        features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2
        build      Dec 09, 2019
        buildopts  (--with-modules --prefix=/usr/local)
        windowsys  nil
        daemonp    nil
doom    version    2.0.9
        build      HEAD -> develop, origin/develop, origin/HEAD 453e20534 2020-01-15 11:19:32 -0500
        dir        ~/02-computing/linux/dotfiles/doom.d/
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/zsh
        uname      Linux 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u1 (2019-09-20) x86_64
        path       (/usr/local/bin /usr/local/sbin /usr/bin /bin /usr/games /usr/lib/surfraw ~/.fzf/bin ~/02-computing/linux/bin ~/.local/bin ~/.emacs.d/bin /usr/local/libexec/emacs/26.3/x86_64-pc-linux-gnu)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company (ivy +fuzzy) :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold (format +onsave) multiple-cursors rotate-text snippets :emacs dired electric ibuffer vc :term shell term :checkers syntax spell :tools (eval +overlay) (lookup +docsets) lsp magit pass :lang clojure data emacs-lisp ess markdown (org +dragndrop +jupyter +pandoc +pomodoro +present) (python +lsp) sh :config (default +bindings +smartparens))
        packages   (fzf evil-terminal-cursor-changer command-log-mode (jupyter :pin "9e3c1633586982e278f072dfaaabd115fa4d19f7") (lsp-python-ms :pin "83ef84d9a4a942f8882b00d07bb78b15f716e89d"))
        elpa       (n/a)
</pre></details>

**Comment by ocharles** [comment]
I'm getting this on my laptop too, but not my desktop. My desktop is less up to date than my laptop.

**Comment by hlissner** [comment]
This should have been fixed upstream. Try `doom update` to update ivy/counsel.

**Comment by randomizedthinking** [comment]
Thanks... I confirm that the issue is resolved.
