### ISSUE TITLE
Possible to implement git gutter on the fly?

### ISSUE THREAD

**Issue by ianpan870102** [hlissner/doom-emacs#2377]
I know that doom is using git-gutter and git-gutter fringe with bitmap styling to provide the vc/git gutter when a user saves the changes. It would be nice if the gutter could appear on-the-fly, that is, without the user having to save his/her changes.
The diff-hl package provides this functionality by calling `diff-hl-flydiff-mode`. I wonder if doom's git gutter could achieve the same behaviour? Cheers!

**Comment by hlissner** [comment]
I believe setting `git-gutter:update-interval` will cause this behavior.

```elisp
(after! git-gutter
  (setq git-gutter:update-interval 0.5))
```

**Comment by ianpan870102** [comment]
Thanks, this does what I needed.
