### ISSUE TITLE
Behavior of 'delete-window' on REPL windows is not as expected

### ISSUE THREAD

**Issue by UndeadKernel** [hlissner/doom-emacs#238]
When trying to delete a window with "C-x 0" on a REPL popup, all other windows, except for the actual popup window, get deleted.

To reproduce:
1) Open a lisp file (e.g. init.el)
2) Create a second window (C-x 3)
3) Open the REPL for the mode (M-x +eval/open-repl)
4) In the REPL window, try to delete the window with "C-x 0"

**Comment by UndeadKernel** [comment]
I've identified the origin of the problem. This happens only if "evil" is **not** activated.
You've probably figured out by now that I don't use evil :D.

Anyhow, the problematic function is located in `core/autoload/popups.el`, in the function in line 234. The function reads as follows:
```
(defun doom/popup-close-maybe ()
  "Close the current popup *if* its window doesn't have a noesc parameter."
  (interactive)
  (if (doom-popup-property :noesc)
      (call-interactively
       (if (featurep 'evil)
           #'evil-force-normal-state
         #'keyboard-escape-quit))
    (delete-window)))
```
When pressing `C-x 0` this function is called. Because the REPL window has the property `:noesc`, the function `keyboard-espace-quit` will be called. I don't think this is the function we want to call. As stated by the documentation, this function " ... [goes] back to just one window (by deleting all but the selected window)". In theory, we would like to call `delete-window`, isn't it?

**Comment by hlissner** [comment]
Good catch, this is definitely the problem, but for a popup with a :noesc property, `doom/popup-close-maybe` should simply no-op. There are two problems here:

1. It may not be appropriate that I [remapped `delete-window` in core-popups.el](https://github.com/hlissner/doom-emacs/blob/develop/core/core-popups.el#L140), as `:noesc` should only inhibit ESC, so I'll remove this.

2. You are correct, `keyboard-escape-quit` isn't the correct no-op command to use. I'm thinking I may replace it with `keyboard-quit` instead. Are you aware of any side effects to that command?

**Comment by UndeadKernel** [comment]
`keyboard-quit` or simply calling nothing seems to be the appropriate choice.
I'm not aware of any side-effects of just calling `keyboard-quit` in this context.
All looks good.
