### ISSUE TITLE
Python LSP failing on NixOS

### ISSUE THREAD

**Issue by Emiller88** [hlissner/doom-emacs#2380]
**What did you expect to happen?**
The server to start up normally

**What actually happened?**
```
LSP :: Sening to process failed with the following error: Process mspyls not running
LSP :: Guessed project root is ~/src/personal/multiverse/
LSP :: Connected to [mspyls:31967 status:starting].
LSP :: mspyls has exited (exited abnormally with code 127)
Server mspyls:31967 status:starting exited with status exit. Do you want to restart it? (y or n) n
```

```
emacs   version    26.3
        features   XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD
        build      Jan 17, 2020
        buildopts  (--prefix=/nix/store/8dad0y5xhvzxgpwbv4dw66fpvghcmzdx-emacs-26.3 --disable-build-details --with-modules --with-x-toolkit=gtk3 --with-xft CFLAGS=-DMAC_OS_X_VERSION_MAX_ALLOWED=101200)
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop 453e20534 2020-01-15 11:19:32 -0500
        dir        ~/.config/doom/
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /run/current-system/sw/bin/zsh
        uname      Linux 4.19.93 #1-NixOS SMP Sat Jan 4 18:13:46 UTC 2020 x86_64
        path       (~/.local/share/cargo/bin ~/.emacs.d/bin ~/.emacs.d/cask/bin ~/bin /run/wrappers/bin ~/.nix-profile/bin /etc/profiles/per-user/emiller/bin /nix/var/nix/profiles/default/bin /run/current-system/sw/bin ~/.yarn/bin /nix/store/8dad0y5xhvzxgpwbv4dw66fpvghcmzdx-emacs-26.3/libexec/emacs/26.3/x86_64-pc-linux-gnu/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion (company +childframe) ivy :ui deft doom doom-dashboard doom-quit hl-todo hydra (modeline +light) nav-flash ophints (popup +all +defaults) vc-gutter vi-tilde-fringe window-select workspaces zen :editor (evil +everywhere) file-templates fold (format +onsave) multiple-cursors parinfer rotate-text snippets :emacs (dired +icons) electric vc :term eshell vterm :checkers syntax spell grammar :tools debugger direnv docker editorconfig eval gist (lookup +docsets +dictionary) lsp magit make pass pdf rgb terraform tmux upload :lang (cc +lsp) clojure data emacs-lisp (ess +lsp) (javascript +lsp) (latex +ref) markdown nix (org +dragndrop +hugo +journal +jupyter +pandoc +pomodoro) perl (python +lsp) rest (rust +lsp) sh solidity snakemake web :email notmuch :app irc (rss +org) :config (default +bindings +smartparnes) literate)
        packages   (edit-server ivy-yasnippet auto-org-md org-noter org-clock-csv easy-hugo graphviz-dot-mode jest vyper-mode org-gcal dired-sidebar (doct :recipe (:host github :repo "progfolio/doct")) tox emms speed-type)
        elpa       (speed-type)
```
The only thing I can think of is that I may not have `libicu` installed properly(I just have the `icu` package) 

So I followed this issue https://github.com/microsoft/python-language-server/issues/170 and disabled the icu check.

I'm guessing @hlissner has an easy solution since it's enabled in his private config.

**Comment by yoavm448** [comment]
exit code 127 means "command not found"... try running mspyls from the command line yourself and see what happens, it might just not be installed.

**Comment by Emiller88** [comment]
@yoavm448 Thanks I didn't know that. But I don't think mspyls is going to get added to my path, it's installed using `lsp-install-server`. 

For the sake of moving things forward though, `mspyls` does not work in my shell.

**Comment by yoavm448** [comment]
one way or another, `mspyls` is not installed. You could try installing it manually, or figure out if `lsp-mode` knows how to install stuff in nixos. Installing manually is simplest.

**Comment by Emiller88** [comment]
I've confirmed this on my laptop(NixOS) also that the `lsp-install-server` with `mspyls` doesn't work either. I'll dig deeper into @yoavm448 's solution if @hlissner confirms that it's working on his system normally.

**Comment by vlaci** [comment]
This is a common issue in NixOS so that binaries[ downloaded from the internet won't work](https://nixos.wiki/wiki/Packaging/Binaries). You can opt to install the nix packaged (non MS) LSP version (`python3Packages.python-language-server`) or patch the mspyls binary using the above instructions from the linked wiki page.

**Comment by mjlbach** [comment]
Microsoft's python language server is now available in nixpkgs-unstable, see: https://github.com/NixOS/nixpkgs/pull/85930

**Comment by Emiller88** [comment]
@mjlbach yep, we can close this as soon as I figure out how to get doom to use the right executable.

**Comment by Emiller88** [comment]
Per [lsp-python-ms's docs](https://github.com/emacs-lsp/lsp-python-ms#nixos), this works in my private config

```lisp
(after! lsp-python-ms
  (setq lsp-python-ms-executable (executable-find "python-language-server"))
  (set-lsp-priority! 'mspyls 1))
```

Open to anything that is better practice than that.
