### ISSUE TITLE
How to make Doom Emacs look like in Screenshot of Repository?

### ISSUE THREAD

**Issue by jkw** [hlissner/doom-emacs#2383]
**What are you trying to achieve?**
... Make Emacs look like in Screenshot.

**What have you tried?**
... Searching, configuring, etc.

**Additional information**
- Do you have screenshots/casts of this workflow in another editor or Emacs
  distro? (If possible, include names of specific commands or functions from
  other editors/emacs distros)
No.
- Do you have additional material or links to resources that could help clarify
  what you are trying to do?
That's what I'm looking for.

**System information**
<details>

```
emacs   version    26.3
        features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2
        build      aug 29, 2019
        buildopts  (--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-modules 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now)
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop, origin/develop, origin/HEAD 453e20534 2020-01-15 11:19:32 -0500
        dir        ~/.doom.d/
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/bash
        uname      Linux 5.4.6-2-MANJARO #1 SMP PREEMPT Tue Dec 24 15:55:20 UTC 2019 x86_64
        path       (~/.local/bin /usr/local/sbin /usr/local/bin /usr/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /var/lib/snapd/snap/bin /usr/lib/emacs/26.3/x86_64-pc-linux-gnu/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold multiple-cursors rotate-text snippets :emacs dired electric ibuffer vc :checkers syntax :tools (eval +overlay) (lookup +docsets) magit :lang data emacs-lisp markdown (org +dragndrop +present) sh :config (default +bindings +smartparens))
        packages   (n/a)
        elpa       (n/a)
```
</details>

**Comment by jkw** [comment]
Screenshot I refer to is:
![image](https://user-images.githubusercontent.com/388872/72641287-10d60700-396a-11ea-8820-cce938d6eaf1.png)

**Comment by BrandonShega** [comment]
What exactly are you referring to the theme (look/feel)? The layout?

**Comment by yoavm448** [comment]
If thats what you mean, opening that explorer sidebar is done with `+treemacs/toggle` (SPC o p), splitting windows with SPC w s/v)
The theme is the default one, should be already loaded, but you can change it by `counsel-load-theme` (SPC h t).

**Comment by BrandonShega** [comment]
I am curious as to how @hlissner gets his TODO list to look like that!

**Comment by jkw** [comment]
> What exactly are you referring to the theme (look/feel)? The layout?

There is no instructions on how to make Doom Emacs look like in the Screenshot.

**Comment by jkw** [comment]
> If thats what you mean, opening that explorer sidebar is done with `+treemacs/toggle` (SPC o p), splitting windows with SPC w s/v)
> The theme is the default one, should be already loaded, but you can change it by `counsel-load-theme` (SPC h t).

`SPC o p is undefined`

**Comment by jkw** [comment]
> I am curious as to how @hlissner gets his TODO list to look like that!

When a Screenshot is provided, the least one could do is include instructions on how to make it look like in the screenshot!

**Comment by BrandonShega** [comment]
You have to enable the treemacs module in your init.el then `doom re`, then you can open treemacs.

**Comment by gagbo** [comment]
> > I am curious as to how @hlissner gets his TODO list to look like that!
> 
> When a Screenshot is provided, the least one could do is include instructions on how to make it look like in the screenshot!

To be honest, having the TODO list look like that is just the theme being enabled and the `:lang org` module being enabled.

The only 2 non-obvious things I see here are :
- The tree on the left, for which you have enable `:tools neotree` or `:tools treemacs`
- The fact that the tree has a darker background than the other windows, which comes "out of the box" with `solaire-mode` and this particular theme (`doom-one`, a few others do it too, in the `emacs-doom-themes` repo bundled here)

Otherwise, it's a 3-window split (`SPC w v SPC w s` and maybe `SPC w H` to move the vertical split on the left), with 3 files opened to show how syntax highlighting looks like for different filetypes.

Knowing Henrik (and also, having asked him), he used to have a script to generate these screenshots, so I don't think there's anything fancy regarding the configuration

**Comment by jkanche** [comment]
is  there a way to set windows in the config instead of manually setting it up everytime ?

**Comment by deadpeer** [comment]
> To be honest, having the TODO list look like that is just the theme being enabled and the `:lang org` module being enabled.

This doesn't seem accurate, but I'm a total Emacs novice so I could be wrong. Out-of-the-box though, my headings don't have hash symbol, darker background, larger text, or the down arrow when folded. I'm also not sure what the "hashtags" are at the end of the todo items themselves (are these tags rendered differently?)

I think the screenshot looks a tad cleaner than my org file, so I'm interested in learning what was done to achieve the look.

**Comment by g-belmonte** [comment]
@jkanche you may try to save the window configuration on a registry: `C-x r w <reg>` where <reg> is a char. To load the registry you may use `C-x r j <reg>`.
Does that solve your issue?

**Comment by g-belmonte** [comment]
@jkw you need to `SPC f P` then open `init.el` and look for `treemacs` and uncomment it (remove the `;;`). Then close your emacs, and execute on a shell `~/.emacs.d/bin/doom sync`. Now you have Treemacs, the window on the left! Open it with `SPC o p` or `M-x treemacs`.
(there's a way of doing the `sync` without closing Emacs, but I'm new to Doom Emacs, so I'll leave this one for you to figure it out)

As for the rest, it's a big window on the left with an Elisp init file open, and two windows on the right: the upper showing some C source code; and the lower showing some Todo list on Org mode.

To split windows, do `SPC w v` to have windows side-by-side, and `SPC w s` to have one above the other.

If you are interested on Org mode, you may find lots of tutorials on the internet, i.e. [David O'Toole Org tutorial](https://orgmode.org/worg/org-tutorials/orgtutorial_dto.html)

IMHO, I don't think any tutorial is necessary to achieve a screen as the screenshot. Some basic knowledge on Emacs will get you there.
To be honest, I had the same problem when I tried Doom Emacs as my first attempt to use Emacs. I moved to Spacemacs, learnt quite a few things about emacs and elisp, got tired of the broken interface for the languages I use, then came back here. Just now these things are clear to me. Until I got used to Emacs, I had to go back to VS Code many times when I needed to be productive.

Please, don't get angry on Emacs or Doom Emacs right at the beginning. Try a little bit more, learn a few shortcuts, try some elisp, learn which packages are important to you... then you'll be at home!

Also, if you have any questions, don't hesitate to ask! The community is here to help! :smile:

**Comment by danielo515** [comment]
I have to admit that it is a bit daunting finding how to enable treemacs. I didn't knew the package name, and all tutorials I found assume that I have it already activated. Luckily I found this issue after a couple of hours and thanks to the detailed answer from @g-belmonte I activated it.

**Comment by rickyson96** [comment]
What I am unable to find out is how to customize outline symbol and folded character like the screenshot given.

The outline symbol in my emacs shows button like character rather than a hash sign (which is better imo), and the folded characters are `...` instead of `v` shaped character.

Am i missing something?

**Comment by dive** [comment]
@rickyson96, I think this is from the [private configuration](https://github.com/hlissner/doom-emacs-private/blob/master/config.el#L80-L85) of the author.

**Comment by rickyson96** [comment]
Wow thanks! @dive.
It does provide some other configurations and is worth checking out 😄
