### ISSUE TITLE
Is it possible preserve projectile projects when rm -rm ~/.emacs.d/.local && doom refresh

### ISSUE THREAD

**Issue by FirstLoveLife** [hlissner/doom-emacs#2391]
Once I rm my ~/.emacs.d/.local, the projectile-releated history will go away. Is there any way to save my projectile history and restore it after `rm ~/.emacs.d/.local && doom refresh`?

**Comment by hlissner** [comment]
Projectile's cache is kept in `~/.emacs.d/.local/cache/projectile.{cache,projects}`. Copy those first before deleting `.local`.

That said, you *really* shouldn't be deleting all of `~/.emacs.d/.local` when something goes wrong. If you must, delete `~/.emacs.d/.local/straight` and leave the other folders alone.
