### ISSUE TITLE
Light theme background not loaded in `emacs -nw`

### ISSUE THREAD

**Issue by tamasgal** [hlissner/doom-emacs#2392]
**What are you trying to achieve?**
Switch to a light time, like `doom-one-light` for both the Emacs GUI and the terminal interface. The GUI loads the colours correctly but when working in a terminal (without X, via `emacs -nw`) the background is dark and thus the text is hardly readable.

**What have you tried?**
`doom/reload-theme`, reinstalling doom emacs completely, updating it, different light themes like `doom-solarized-light`.

**Additional information**
On the left the Emacs GUI, on the right `emacs -nw` with the colour scheme `doom-one-light`.

![image](https://user-images.githubusercontent.com/1730350/72737585-26347680-3ba0-11ea-8e67-436693f5da45.png)

**System information**
<details>
<pre>
emacs   version    26.3
        features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2
        build      Aug 29, 2019
        buildopts  (--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-modules 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now)
        windowsys  nil
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop, origin/develop, origin/HEAD 12ebc58f2 2020-01-15 02:20:46 -0500
        dir        ~/.rc/doom.d/
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /usr/bin/zsh
        uname      Linux 4.14.165-1-MANJARO #1 SMP PREEMPT Wed Jan 15 08:38:28 UTC 2020 x86_64
        path       (~/.nimble/bin ~/go/bin ~/modules/software/julia/1.3.0-rc4/bin ~/opt/bin /var/lib/snapd/snap/bin ~/.local/bin /usr/local/bin /usr/bin /bin /usr/local/sbin /opt/cuda/bin /opt/intel/mediasdk/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /var/lib/snapd/snap/bin ~/.gem/ruby/2.6.0/bin ~/.emacs.d/bin /usr/lib/emacs/26.3/x86_64-pc-linux-gnu)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) treemacs unicode vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold multiple-cursors rotate-text snippets :emacs dired electric ibuffer vc :checkers syntax spell grammar :tools (eval +overlay) (lookup +docsets) lsp magit :lang data emacs-lisp erlang (haskell +dante) julia latex markdown (org +dragndrop +pandoc +present) (python +lsp) rst rust sh :app calendar :config (default +bindings +smartparens))
        packages   (n/a)
        elpa       (n/a)
</pre>
</details>

**Comment by hlissner** [comment]
This is more an "issue" for https://github.com/hlissner/emacs-doom-themes than Doom, but it is intentional: the themes in that megapack use a transparent background in the terminal, as to not break OS transparency ort paint over the user's choice of terminal background. (Try a built-in Emacs theme, like wombat or adwaita, and you'll see the background change).

To get around this you will have to change your terminal's background (it isn't obvious what terminal you're using so I can only suggest doing it through Xresources files), or specify your own in Emacs with

```elisp
(custom-set-faces! '(default :background "some-color"))
```

**Comment by tamasgal** [comment]
Thanks for the quick reply. A transparent background makes of course sense... I am btw. using `kitty` and `st`.

I tried setting the background colour to white but it seems that more tweaks are needed. I will probably set up a fixed theme or try the base16 package. Under Vim I use the base16 themes, which I can globally set (in the shell) and everything simply adopts the theme, so I can quickly switch between dark/light during live demos, depending on the situation.
This should be addressed in a separate issue, but I am wondering if there is a similar setup for emacs...

![Screenshot 2020-01-20 at 22 14 07](https://user-images.githubusercontent.com/1730350/72758154-4da43700-3bd2-11ea-8cc0-a71ab0e3c02a.png)

**Comment by hlissner** [comment]
Did you set the background of kitty/st, or Emacs? It looks like you only set Emacs' background. You should be changing kitty/st. The `hl-line` face uses the same color as the background (since few colors are available in the terminal).

**Comment by tamasgal** [comment]
The problem is I think that my setup clashes due to `base16-shell`. I'll spend a bit of time today to figure this out.

In Vim, I have a simple check of a file which is written to `.vimrc_background` by `base16` and the content is like this:

```
if !exists('g:colors_name') || g:colors_name != 'base16-unikitty-light'
  colorscheme base16-unikitty-light
endif
```

So it loads the appropriate colours upon launch.

Here is my setup with `base16-shell` and Vim which I'd like to mimic in Emacs, but I'm completely new to it (just switched to Emacs after 20 years of Vim) and not sure if there is something which already exists:

![base16](https://user-images.githubusercontent.com/1730350/72966156-74bf5c00-3dbe-11ea-966c-eb280897e8c7.gif)
