### ISSUE TITLE
Use counsel-org-tag for ivy users in org mode

### ISSUE THREAD

**Issue by codygman** [hlissner/doom-emacs#2393]
**Describe the feature**
- If the feature involves replacement of current functionality, how the new
  functionality is better?

Adding multiple tags with `org-set-tags-command` with ivy activated is "broken". Quotes because it technically adds the tags, but completion breaks after the first tag is entered.

`counsel-org-tag` brings up a users tags and at first glance doesn't look like it would solve this problem of completing past the first tag, but since `ivy-call` exists it does work. Multiple tags with completion with `counsel-org-tag` looks like:

![foo](https://user-images.githubusercontent.com/225847/72766799-15432f80-3bb7-11ea-84eb-cdfcdcd102b3.gif)

**Comment by hlissner** [comment]
As of a34cb16 I've remapped org-set-tags-commands as suggested. Let me know if that doesn't address the issue and I'll reopen it. Thanks for bringing it to my attention!
