### ISSUE TITLE
sudo edit broken?

### ISSUE THREAD

**Issue by gregf** [hlissner/doom-emacs#2399]
**What did you expect to happen?**
I ran M-x doom/sudo-find-file

**What actually happened?**
It just sits here at this screen.

![doom](https://user-images.githubusercontent.com/980/72862140-23b64780-3c9a-11ea-97e8-a56f6463056d.png)

**Additional details:**
- Include a link to your private config

https://gist.github.com/gregf/e6b752aeaca50ce35b902ab01fe9ba9d

Output from view-ech-area-messages

![doom2](https://user-images.githubusercontent.com/980/72862261-8871a200-3c9a-11ea-8212-0cc079e4d0a0.png)

**System information:**

╰─ ❯ doom info                                                                                                                                     ─╯
WARNING (:tools flycheck) module was moved to (:checkers syntax)
WARNING (:tools flyspell) module was moved to (:checkers spell)
WARNING Couldn’t find the :app write module
((emacs
  (version . "26.3")
  (features . "XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GCONF GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LCMS2")
  (build . "Jan 21, 2020")
  (buildopts "--disable-build-details --localstatedir=/var --without-gpm --with-x --enable-acl --without-cairo --with-dbus --with-gconf --with-gif --with-gnutls --with-gsettings --with-x-toolkit=gtk3 --with-jpeg --with-file-notification=kqueue --with-lcms2 --with-m17n-flt --with-imagemagick --with-mailutils --with-modules --with-sound=oss --with-libotf --with-png --with-toolkit-scroll-bars --with-rsvg --with-threads --with-tiff --with-xft --with-xim --with-xml2 --with-xpm --without-xwidgets --x-libraries=/usr/local/lib --x-includes=/usr/local/include --prefix=/usr/local --mandir=/usr/local/man --disable-silent-rules --infodir=/usr/local/share/emacs/info/ --build=amd64-portbld-freebsd13.0 'CFLAGS=-O2 -pipe  -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing ' 'CPPFLAGS=-isystem /usr/local/include' 'LDFLAGS= -fstack-protector-strong -L/usr/local/lib '")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD 8a01ef908 2020-01-20 20:17:43 -0500")
  (dir . "/usr/home/gregf/.doom.d/"))
 (system
  (type . berkeley-unix)
  (config . "amd64-portbld-freebsd13.0")
  (shell . "/usr/local/bin/zsh")
  (uname . "FreeBSD 13.0-CURRENT FreeBSD 13.0-CURRENT #0 r356767: Thu Jan 16 04:52:44 UTC 2020     root@releng1.nyi.freebsd.org:/usr/obj/usr/src/amd64.amd64/sys/GENERIC  amd64")
  (path "/bin" "/sbin" "/usr/sbin" "/usr/bin" "/usr/local/bin" "~/dev/go/bin" "~/bin" "~/.emacs.d/bin" "~/.cargo/bin" "/usr/local/bin" "/usr/lib/w3m" "/usr/local/sbin" "/usr/local/bin" "/usr/bin/core_perl" "/usr/bin" "~/.config/bspwm/panel" "~/.bin" "/usr/local/libexec/emacs/26.3/amd64-portbld-freebsd13.0"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard doom-quit fill-column hl-todo indent-guides modeline nav-flash ophints (popup +all +defaults) pretty-code treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold (format +onsave) multiple-cursors rotate-text snippets word-wrap :emacs dired electric vc :term eshell :tools ansible direnv docker editorconfig eval :checkers syntax spell :tools gist (lookup +docsets) magit rgb terraform :lang data emacs-lisp go javascript kotlin markdown (org +dragndrop +hugo +ipython +pandoc +present) perl php python ruby rust sh web :config (default +bindings +smartparens))
  (packages org-alert alert auto-sudoedit)
  (elpa "n/a")))

**Comment by gregf** [comment]
I believe this has to do with a library incompatible issue with my system currently. I'm running FreeBSD 13-current and I think something is broke. Working on fixing that, I'll close this till I know for sure it's a doom issue.

**Comment by hlissner** [comment]
Perhaps a solution could be found in https://www.emacswiki.org/emacs/TrampMode#toc7 ?
