### ISSUE TITLE
orgmode TAB cycle works different in doom emacs

### ISSUE THREAD

**Issue by FinallyFinancialFreedom** [hlissner/doom-emacs#2405]
**What did you expect to happen?**
...
org mode TAB cycle should be 

> TAB (org-cycle)
> Subtree cycling: Rotate current subtree among the states
> 
> ,-> FOLDED -> CHILDREN -> SUBTREE --.
> '-----------------------------------------'

**What actually happened?**

TAB once will show children, but TAB again it Folded, it should show subtree.
,-> FOLDED -> CHILDREN -> --.
'--------------------------------'
emacs -q works as i expected. 

**Additional details:**
- Include a link to your private config
- Include screenshots/casts of your issue
- If you mention key sequences, include what commands they're bound to (use `SPC
  h k KEY` or `C-h h k KEY` to inspect keys).
- Include any warnings or errors logged to \*Messages\* (use `M-x
  view-echo-area-messages` to see it).

<details><pre>
If an error message is involved include a backtrace of it.

How to acquire a backtrace:
https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#how-to-extract-a-backtrace-from-an-error
</pre></details>

**Steps to reproduce:**
1. Select these example steps,
2. Delete them,
3. And replace them with precise steps to reproduce your issue.
4. Fill in "system information" below.

**System information:**
<details><pre>
WARNING (:ui doom-modeline) module was moved to (:ui modeline)
((emacs
  (version . "26.2")
  (features . "JPEG RSVG IMAGEMAGICK GLIB NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2")
  (build . "Apr 21, 2019")
  (buildopts "--disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus/26.2/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus/26.2 --with-xml2 --without-dbus --with-gnutls --with-imagemagick --with-modules --with-rsvg --with-ns --disable-ns-self-contained")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD 787f65682 2020-01-20 02:30:11 -0500")
  (dir . "~/.config/doom/"))
 (system
  (type . darwin)
  (config . "x86_64-apple-darwin18.2.0")
  (shell . "/bin/zsh")
  (uname . "Darwin 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64")
  (path "~/.cargo/bin" "/usr/local/bin" "/usr/bin" "/bin" "/usr/sbin" "/sbin" "/Library/TeX/texbin" "/usr/local/opt/fzf/bin" "/usr/local/Cellar/emacs-plus/26.2/libexec/emacs/26.2/x86_64-apple-darwin18.2.0"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :input (chinese :variables chinese-enable-fcitx t) :completion company ivy :ui doom doom-dashboard hl-todo modeline nav-flash ophints (popup +all +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold multiple-cursors rotate-text snippets word-wrap :emacs dired electric ibuffer vc :checkers syntax :tools (eval +overlay) (lookup +docsets) magit :lang data emacs-lisp markdown (org +dragndrop +present) sh :config (default +bindings +smartparens))
  (packages "(pangu-spacing :disable t :pin \"f92898949ba3bf991fd229416f3bbb54e9c6c223\")")
  (elpa "n/a")))
</pre></details>

**Comment by dive** [comment]
@FinallyFinancialFreedom, from the [documentation](https://github.com/hlissner/doom-emacs/tree/8a01ef9082d6ff22b95e5fd4aada9c58e6135684/modules/lang/org#hacks) for the org module:

> TAB was changed to toggle only the visibility state of the current subtree, rather than cycle through it recursively. This can be reversed with:
``` 
(after! evil-org
  (remove-hook 'org-tab-first-hook #'+org-cycle-only-current-subtree-h))
```

**Comment by FinallyFinancialFreedom** [comment]
@dive  thank you, it's exactly what i need.
