### ISSUE TITLE
How do I override a doom snippet?

### ISSUE THREAD

**Issue by tam5** [hlissner/doom-emacs#2407]
**What are you trying to achieve?**
I'd like to keep `doom-snippets`, but override/modify some of them. Is there a way to define snippets in `~/.doom.d/snippets` and have them take precedence?

**What have you tried?**
I have tried to create a private snippet with the same trigger, and this kind of works, but it opens a list and makes me choose which snippet I want. Ideally, it would just take the one that I have in my private config.

**Comment by hlissner** [comment]
Have you enabled the `:editor snippets` module? Snippets in `~/.doom.d/snippets/MAJOR-MODE/...` should override built-in snippets if they have the same trigger (i.e. it shouldn't prompt for it). I cannot reproduce the behavior you've described.

Please include your `M-x doom/info`.

**Comment by tam5** [comment]
you are correct, not sure why it wasnt working before 🤷‍♂
