### ISSUE TITLE
LSP lsp-workspace-restart

### ISSUE THREAD

**Issue by eyingxuan** [hlissner/doom-emacs#2408]
**What did you expect to happen?**
lsp-workspace-restart to restart the workspace

**What actually happened?**
An error was thrown. 
<pre>
apply: Wrong number of arguments: ((t) (orig-fn) "Defer server shutdown for a few seconds.
This gives the user a chance to open other project files before the server is
auto-killed (which is usually an expensive process)." (if (or lsp-keep-workspace-alive (eq (lsp--workspace-shutdown-action lsp--cur-workspace) (quote restart))) (funcall orig-fn) (if (timerp +lsp--deferred-shutdown-timer) (progn (cancel-timer +lsp--deferred-shutdown-timer))) (setq +lsp--deferred-shutdown-timer (run-at-time 3 nil (function (lambda (workspace) (let ((lsp--cur-workspace workspace)) (if (lsp--workspace-buffers lsp--cur-workspace) nil (funcall orig-fn))))) lsp--cur-workspace)))), 2
</pre>

**Additional details:**
Backtrace:
<details><pre>
Debugger entered--Lisp error: (wrong-number-of-arguments ((t) (orig-fn) "Defer server shutdown for a few seconds.\nThis gives the user a chance to open other project files before the server is\nauto-killed (which is usually an expensive process)." (if (or lsp-keep-workspace-alive (eq (lsp--workspace-shutdown-action lsp--cur-workspace) (quote restart))) (funcall orig-fn) (if (timerp +lsp--deferred-shutdown-timer) (progn (cancel-timer +lsp--deferred-shutdown-timer))) (setq +lsp--deferred-shutdown-timer (run-at-time 3 nil (function (lambda (workspace) (let ... ...))) lsp--cur-workspace)))) 2)
  +lsp-defer-server-shutdown-a(#f(compiled-function (&optional restart) "Shut down the language server process for ‘lsp--cur-workspace’." #<bytecode 0x44e696e9>) t)
  apply(+lsp-defer-server-shutdown-a #f(compiled-function (&optional restart) "Shut down the language server process for ‘lsp--cur-workspace’." #<bytecode 0x44e696e9>) t)
  lsp--shutdown-workspace(t)
  lsp-workspace-restart(#s(lsp--workspace :ewoc #s(ewoc :buffer #<buffer *lsp-log: ccls:73789*> :pretty-printer lsp--log-entry-pp :header [[[[[[[[[#3 #10 #s(lsp--log-entry :timestamp "05:17:01 PM" :process-time nil :type outgoing-req :method "textDocument/documentLink" :id 10 :body ...) #<marker at 1 in *lsp-log: ccls:73789*>] #9 #s(lsp--log-entry :timestamp "05:17:01 PM" :process-time 27 :type incoming-resp :method "textDocument/documentLink" :id 10 :body [#<hash-table equal 2/65 0x40f204b1> #<hash-table equal 2/65 0x4413b955> #<hash-table equal 2/65 0x40a29075>]) #<marker at 175 in *lsp-log: ccls:73789*>] #8 #s(lsp--log-entry :timestamp "05:17:38 PM" :process-time nil :type outgoing-req :method "textDocument/documentLink" :id 11 :body ...) #<marker at 1022 in *lsp-log: ccls:73789*>] #7 #s(lsp--log-entry :timestamp "05:17:38 PM" :process-time 29 :type incoming-resp :method "textDocument/documentLink" :id 11 :body [#<hash-table equal 2/65 0x44947121> #<hash-table equal 2/65 0x447591c1> #<hash-table equal 2/65 0x4549c869>]) #<marker at 1196 in *lsp-log: ccls:73789*>] #6 #s(lsp--log-entry :timestamp "05:18:25 PM" :process-time nil :type outgoing-req :method "textDocument/documentLink" :id 16 :body ...) #<marker at 2043 in *lsp-log: ccls:73789*>] #5 #s(lsp--log-entry :timestamp "05:18:25 PM" :process-time 26 :type incoming-resp :method "textDocument/documentLink" :id 16 :body [#<hash-table equal 2/65 0x441db9ed> #<hash-table equal 2/65 0x40ead76d> #<hash-table equal 2/65 0x4485256d>]) #<marker at 2217 in *lsp-log: ccls:73789*>] #4 "" #<marker at 3064 in *lsp-log: ccls:73789*>] #3 DL-LIST #<marker at 3064 in *lsp-log: ccls:73789*>] [#3 [#4 [#5 [#6 [#7 [#8 [#9 [#10 #3 DL-LIST #<marker at 3064 in *lsp-log: ccls:73789*>] "" #<marker at 3064 in *lsp-log: ccls:73789*>] #s(lsp--log-entry :timestamp "05:18:25 PM" :process-time 26 :type incoming-resp :method "textDocument/documentLink" :id 16 :body [#<hash-table equal 2/65 0x441db9ed> #<hash-table equal 2/65 0x40ead76d> #<hash-table equal 2/65 0x4485256d>]) #<marker at 2217 in *lsp-log: ccls:73789*>] #s(lsp--log-entry :timestamp "05:18:25 PM" :process-time nil :type outgoing-req :method "textDocument/documentLink" :id 16 :body ...) #<marker at 2043 in *lsp-log: ccls:73789*>] #s(lsp--log-entry :timestamp "05:17:38 PM" :process-time 29 :type incoming-resp :method "textDocument/documentLink" :id 11 :body [#<hash-table equal 2/65 0x44947121> #<hash-table equal 2/65 0x447591c1> #<hash-table equal 2/65 0x4549c869>]) #<marker at 1196 in *lsp-log: ccls:73789*>] #s(lsp--log-entry :timestamp "05:17:38 PM" :process-time nil :type outgoing-req :method "textDocument/documentLink" :id 11 :body ...) #<marker at 1022 in *lsp-log: ccls:73789*>] #s(lsp--log-entry :timestamp "05:17:01 PM" :process-time 27 :type incoming-resp :method "textDocument/documentLink" :id 10 :body [#<hash-table equal 2/65 0x40f204b1> #<hash-table equal 2/65 0x4413b955> #<hash-table equal 2/65 0x40a29075>]) #<marker at 175 in *lsp-log: ccls:73789*>] #s(lsp--log-entry :timestamp "05:17:01 PM" :process-time nil :type outgoing-req :method "textDocument/documentLink" :id 10 :body (:textDocument (:uri "file:///Users/yingxuan/Documents/cis240-hw9/jc.c"))) #<marker at 1 in *lsp-log: ccls:73789*>] "" #<marker at 1 in *lsp-log: ccls:73789*>] :footer [[[[[[[[[#3 #10 DL-LIST #<marker at 3064 in *lsp-log: ccls:73789*>] #9 "" #<marker at 1 in *lsp-log: ccls:73789*>] #8 #s(lsp--log-entry :timestamp "05:17:01 PM" :process-time nil :type outgoing-req :method "textDocument/documentLink" :id 10 :body ...) #<marker at 1 in *lsp-log: ccls:73789*>] #7 #s(lsp--log-entry :timestamp "05:17:01 PM" :process-time 27 :type incoming-resp :method "textDocument/documentLink" :id 10 :body [#<hash-table equal 2/65 0x40f204b1> #<hash-table equal 2/65 0x4413b955> #<hash-table equal 2/65 0x40a29075>]) #<marker at 175 in *lsp-log: ccls:73789*>] #6 #s(lsp--log-entry :timestamp "05:17:38 PM" :process-time nil :type outgoing-req :method "textDocument/documentLink" :id 11 :body ...) #<marker at 1022 in *lsp-log: ccls:73789*>] #5 #s(lsp--log-entry :timestamp "05:17:38 PM" :process-time 29 :type incoming-resp :method "textDocument/documentLink" :id 11 :body [#<hash-table equal 2/65 0x44947121> #<hash-table equal 2/65 0x447591c1> #<hash-table equal 2/65 0x4549c869>]) #<marker at 1196 in *lsp-log: ccls:73789*>] #4 #s(lsp--log-entry :timestamp "05:18:25 PM" :process-time nil :type outgoing-req :method "textDocument/documentLink" :id 16 :body (:textDocument ...)) #<marker at 2043 in *lsp-log: ccls:73789*>] #3 #s(lsp--log-entry :timestamp "05:18:25 PM" :process-time 26 :type incoming-resp :method "textDocument/documentLink" :id 16 :body [#<hash-table equal 2/65 0x441db9ed> #<hash-table equal 2/65 0x40ead76d> #<hash-table equal 2/65 0x4485256d>]) #<marker at 2217 in *lsp-log: ccls:73789*>] [#3 [#4 [#5 [#6 [#7 [#8 [#9 [#10 #3 #s(lsp--log-entry :timestamp "05:18:25 PM" :process-time 26 :type incoming-resp :method "textDocument/documentLink" :id 16 :body [#<hash-table equal 2/65 0x441db9ed> #<hash-table equal 2/65 0x40ead76d> #<hash-table equal 2/65 0x4485256d>]) #<marker at 2217 in *lsp-log: ccls:73789*>] #s(lsp--log-entry :timestamp "05:18:25 PM" :process-time nil :type outgoing-req :method "textDocument/documentLink" :id 16 :body ...) #<marker at 2043 in *lsp-log: ccls:73789*>] #s(lsp--log-entry :timestamp "05:17:38 PM" :process-time 29 :type incoming-resp :method "textDocument/documentLink" :id 11 :body [#<hash-table equal 2/65 0x44947121> #<hash-table equal 2/65 0x447591c1> #<hash-table equal 2/65 0x4549c869>]) #<marker at 1196 in *lsp-log: ccls:73789*>] #s(lsp--log-entry :timestamp "05:17:38 PM" :process-time nil :type outgoing-req :method "textDocument/documentLink" :id 11 :body ...) #<marker at 1022 in *lsp-log: ccls:73789*>] #s(lsp--log-entry :timestamp "05:17:01 PM" :process-time 27 :type incoming-resp :method "textDocument/documentLink" :id 10 :body [#<hash-table equal 2/65 0x40f204b1> #<hash-table equal 2/65 0x4413b955> #<hash-table equal 2/65 0x40a29075>]) #<marker at 175 in *lsp-log: ccls:73789*>] #s(lsp--log-entry :timestamp "05:17:01 PM" :process-time nil :type outgoing-req :method "textDocument/documentLink" :id 10 :body ...) #<marker at 1 in *lsp-log: ccls:73789*>] "" #<marker at 1 in *lsp-log: ccls:73789*>] DL-LIST #<marker at 3064 in *lsp-log: ccls:73789*>] "" #<marker at 3064 in *lsp-log: ccls:73789*>] :dll [[[[[[[[[#3 #10 "" #<marker at 1 in *lsp-log: ccls:73789*>] #9 #s(lsp--log-entry :timestamp "05:17:01 PM" :process-time nil :type outgoing-req :method "textDocument/documentLink" :id 10 :body ...) #<marker at 1 in *lsp-log: ccls:73789*>] #8 #s(lsp--log-entry :timestamp "05:17:01 PM" :process-time 27 :type incoming-resp :method "textDocument/documentLink" :id 10 :body [#<hash-table equal 2/65 0x40f204b1> #<hash-table equal 2/65 0x4413b955> #<hash-table equal 2/65 0x40a29075>]) #<marker at 175 in *lsp-log: ccls:73789*>] #7 #s(lsp--log-entry :timestamp "05:17:38 PM" :process-time nil :type outgoing-req :method "textDocument/documentLink" :id 11 :body ...) #<marker at 1022 in *lsp-log: ccls:73789*>] #6 #s(lsp--log-entry :timestamp "05:17:38 PM" :process-time 29 :type incoming-resp :method "textDocument/documentLink" :id 11 :body [#<hash-table equal 2/65 0x44947121> #<hash-table equal 2/65 0x447591c1> #<hash-table equal 2/65 0x4549c869>]) #<marker at 1196 in *lsp-log: ccls:73789*>] #5 #s(lsp--log-entry :timestamp "05:18:25 PM" :process-time nil :type outgoing-req :method "textDocument/documentLink" :id 16 :body ...) #<marker at 2043 in *lsp-log: ccls:73789*>] #4 #s(lsp--log-entry :timestamp "05:18:25 PM" :process-time 26 :type incoming-resp :method "textDocument/documentLink" :id 16 :body [#<hash-table equal 2/65 0x441db9ed> #<hash-table equal 2/65 0x40ead76d> #<hash-table equal 2/65 0x4485256d>]) #<marker at 2217 in *lsp-log: ccls:73789*>] #3 "" #<marker at 3064 in *lsp-log: ccls:73789*>] [#3 [#4 [#5 [#6 [#7 [#8 [#9 [#10 #3 "" #<marker at 3064 in *lsp-log: ccls:73789*>] #s(lsp--log-entry :timestamp "05:18:25 PM" :process-time 26 :type incoming-resp :method "textDocument/documentLink" :id 16 :body [#<hash-table equal 2/65 0x441db9ed> #<hash-table equal 2/65 0x40ead76d> #<hash-table equal 2/65 0x4485256d>]) #<marker at 2217 in *lsp-log: ccls:73789*>] #s(lsp--log-entry :timestamp "05:18:25 PM" :process-time nil :type outgoing-req :method "textDocument/documentLink" :id 16 :body ...) #<marker at 2043 in *lsp-log: ccls:73789*>] #s(lsp--log-entry :timestamp "05:17:38 PM" :process-time 29 :type incoming-resp :method "textDocument/documentLink" :id 11 :body [#<hash-table equal 2/65 0x44947121> #<hash-table equal 2/65 0x447591c1> #<hash-table equal 2/65 0x4549c869>]) #<marker at 1196 in *lsp-log: ccls:73789*>] #s(lsp--log-entry :timestamp "05:17:38 PM" :process-time nil :type outgoing-req :method "textDocument/documentLink" :id 11 :body ...) #<marker at 1022 in *lsp-log: ccls:73789*>] #s(lsp--log-entry :timestamp "05:17:01 PM" :process-time 27 :type incoming-resp :method "textDocument/documentLink" :id 10 :body [#<hash-table equal 2/65 0x40f204b1> #<hash-table equal 2/65 0x4413b955> #<hash-table equal 2/65 0x40a29075>]) #<marker at 175 in *lsp-log: ccls:73789*>] #s(lsp--log-entry :timestamp "05:17:01 PM" :process-time nil :type outgoing-req :method "textDocument/documentLink" :id 10 :body (:textDocument ...)) #<marker at 1 in *lsp-log: ccls:73789*>] "" #<marker at 1 in *lsp-log: ccls:73789*>] DL-LIST #<marker at 3064 in *lsp-log: ccls:73789*>] :last-node nil :hf-pp insert) :server-capabilities #<hash-table equal 22/65 0x45500841> :registered-server-capabilities (#s(lsp--registered-capability :id "didChangeWatchedFiles" :method "workspace/didChangeWatchedFiles" :options #<hash-table equal 1/65 0x4550cf41>)) :root "/Users/yingxuan/Documents/cis240-hw9" :client #s(lsp--client :language-id nil :add-on? nil :new-connection (:connect #f(compiled-function (filter sentinel name environment-fn) #<bytecode 0x44e9abb5>) :test\? #f(compiled-function () #<bytecode 0x44e9abcd>)) :ignore-regexps nil :ignore-messages nil :notification-handlers #<hash-table equal 2/65 0x44e9abd9> :request-handlers #<hash-table equal 0/65 0x44e9aeb9> :response-handlers #<hash-table eql 0/65 0x44e9b1b1> :prefix-function nil :uri-handlers #<hash-table equal 0/65 0x44e9b4a9> :action-handlers #<hash-table equal 0/65 0x44e9b781> :major-modes (c-mode c++-mode cuda-mode objc-mode) :activation-fn nil :priority 0 :server-id ccls :multi-root nil :initialization-options #f(compiled-function () #<bytecode 0x44e7c54d>) :custom-capabilities nil :library-folders-fn nil :before-file-open-fn nil :initialized-fn nil :remote? nil :completion-in-comments? nil :path->uri-fn nil :uri->path-fn nil :environment-fn nil :after-open-fn nil :async-request-handlers #<hash-table equal 0/65 0x44e9b7a1> :download-server-fn nil :download-in-progress? nil :buffers nil) :host-root nil :proc #<process ccls> :cmd-proc #<process ccls> :buffers (#<buffer jc.c>) :semantic-highlighting-faces nil :extra-client-capabilities nil :status initialized :metadata #<hash-table equal 0/65 0x40f2f11d> :watches #<hash-table equal 0/65 0x40f2f3f5> :workspace-folders nil :last-id 0 :status-string nil :shutdown-action nil :diagnostics #<hash-table equal 0/65 0x40f2f415>))
  funcall-interactively(lsp-workspace-restart #s(lsp--workspace :ewoc #s(ewoc :buffer #<buffer *lsp-log: ccls:73789*> :pretty-printer lsp--log-entry-pp :header [[[[[[[[[#4 #11 #s(lsp--log-entry :timestamp "05:17:01 PM" :process-time nil :type outgoing-req :method "textDocument/documentLink" :id 10 :body ...) #<marker at 1 in *lsp-log: ccls:73789*>] #10 #s(lsp--log-entry :timestamp "05:17:01 PM" :process-time 27 :type incoming-resp :method "textDocument/documentLink" :id 10 :body [#<hash-table equal 2/65 0x40f204b1> #<hash-table equal 2/65 0x4413b955> #<hash-table equal 2/65 0x40a29075>]) #<marker at 175 in *lsp-log: ccls:73789*>] #9 #s(lsp--log-entry :timestamp "05:17:38 PM" :process-time nil :type outgoing-req :method "textDocument/documentLink" :id 11 :body ...) #<marker at 1022 in *lsp-log: ccls:73789*>] #8 #s(lsp--log-entry :timestamp "05:17:38 PM" :process-time 29 :type incoming-resp :method "textDocument/documentLink" :id 11 :body [#<hash-table equal 2/65 0x44947121> #<hash-table equal 2/65 0x447591c1> #<hash-table equal 2/65 0x4549c869>]) #<marker at 1196 in *lsp-log: ccls:73789*>] #7 #s(lsp--log-entry :timestamp "05:18:25 PM" :process-time nil :type outgoing-req :method "textDocument/documentLink" :id 16 :body ...) #<marker at 2043 in *lsp-log: ccls:73789*>] #6 #s(lsp--log-entry :timestamp "05:18:25 PM" :process-time 26 :type incoming-resp :method "textDocument/documentLink" :id 16 :body [#<hash-table equal 2/65 0x441db9ed> #<hash-table equal 2/65 0x40ead76d> #<hash-table equal 2/65 0x4485256d>]) #<marker at 2217 in *lsp-log: ccls:73789*>] #5 "" #<marker at 3064 in *lsp-log: ccls:73789*>] #4 DL-LIST #<marker at 3064 in *lsp-log: ccls:73789*>] [#4 [#5 [#6 [#7 [#8 [#9 [#10 [#11 #4 DL-LIST #<marker at 3064 in *lsp-log: ccls:73789*>] "" #<marker at 3064 in *lsp-log: ccls:73789*>] #s(lsp--log-entry :timestamp "05:18:25 PM" :process-time 26 :type incoming-resp :method "textDocument/documentLink" :id 16 :body [#<hash-table equal 2/65 0x441db9ed> #<hash-table equal 2/65 0x40ead76d> #<hash-table equal 2/65 0x4485256d>]) #<marker at 2217 in *lsp-log: ccls:73789*>] #s(lsp--log-entry :timestamp "05:18:25 PM" :process-time nil :type outgoing-req :method "textDocument/documentLink" :id 16 :body ...) #<marker at 2043 in *lsp-log: ccls:73789*>] #s(lsp--log-entry :timestamp "05:17:38 PM" :process-time 29 :type incoming-resp :method "textDocument/documentLink" :id 11 :body [#<hash-table equal 2/65 0x44947121> #<hash-table equal 2/65 0x447591c1> #<hash-table equal 2/65 0x4549c869>]) #<marker at 1196 in *lsp-log: ccls:73789*>] #s(lsp--log-entry :timestamp "05:17:38 PM" :process-time nil :type outgoing-req :method "textDocument/documentLink" :id 11 :body ...) #<marker at 1022 in *lsp-log: ccls:73789*>] #s(lsp--log-entry :timestamp "05:17:01 PM" :process-time 27 :type incoming-resp :method "textDocument/documentLink" :id 10 :body [#<hash-table equal 2/65 0x40f204b1> #<hash-table equal 2/65 0x4413b955> #<hash-table equal 2/65 0x40a29075>]) #<marker at 175 in *lsp-log: ccls:73789*>] #s(lsp--log-entry :timestamp "05:17:01 PM" :process-time nil :type outgoing-req :method "textDocument/documentLink" :id 10 :body (:textDocument (:uri "file:///Users/yingxuan/Documents/cis240-hw9/jc.c"))) #<marker at 1 in *lsp-log: ccls:73789*>] "" #<marker at 1 in *lsp-log: ccls:73789*>] :footer [[[[[[[[[#4 #11 DL-LIST #<marker at 3064 in *lsp-log: ccls:73789*>] #10 "" #<marker at 1 in *lsp-log: ccls:73789*>] #9 #s(lsp--log-entry :timestamp "05:17:01 PM" :process-time nil :type outgoing-req :method "textDocument/documentLink" :id 10 :body ...) #<marker at 1 in *lsp-log: ccls:73789*>] #8 #s(lsp--log-entry :timestamp "05:17:01 PM" :process-time 27 :type incoming-resp :method "textDocument/documentLink" :id 10 :body [#<hash-table equal 2/65 0x40f204b1> #<hash-table equal 2/65 0x4413b955> #<hash-table equal 2/65 0x40a29075>]) #<marker at 175 in *lsp-log: ccls:73789*>] #7 #s(lsp--log-entry :timestamp "05:17:38 PM" :process-time nil :type outgoing-req :method "textDocument/documentLink" :id 11 :body ...) #<marker at 1022 in *lsp-log: ccls:73789*>] #6 #s(lsp--log-entry :timestamp "05:17:38 PM" :process-time 29 :type incoming-resp :method "textDocument/documentLink" :id 11 :body [#<hash-table equal 2/65 0x44947121> #<hash-table equal 2/65 0x447591c1> #<hash-table equal 2/65 0x4549c869>]) #<marker at 1196 in *lsp-log: ccls:73789*>] #5 #s(lsp--log-entry :timestamp "05:18:25 PM" :process-time nil :type outgoing-req :method "textDocument/documentLink" :id 16 :body (:textDocument ...)) #<marker at 2043 in *lsp-log: ccls:73789*>] #4 #s(lsp--log-entry :timestamp "05:18:25 PM" :process-time 26 :type incoming-resp :method "textDocument/documentLink" :id 16 :body [#<hash-table equal 2/65 0x441db9ed> #<hash-table equal 2/65 0x40ead76d> #<hash-table equal 2/65 0x4485256d>]) #<marker at 2217 in *lsp-log: ccls:73789*>] [#4 [#5 [#6 [#7 [#8 [#9 [#10 [#11 #4 #s(lsp--log-entry :timestamp "05:18:25 PM" :process-time 26 :type incoming-resp :method "textDocument/documentLink" :id 16 :body [#<hash-table equal 2/65 0x441db9ed> #<hash-table equal 2/65 0x40ead76d> #<hash-table equal 2/65 0x4485256d>]) #<marker at 2217 in *lsp-log: ccls:73789*>] #s(lsp--log-entry :timestamp "05:18:25 PM" :process-time nil :type outgoing-req :method "textDocument/documentLink" :id 16 :body ...) #<marker at 2043 in *lsp-log: ccls:73789*>] #s(lsp--log-entry :timestamp "05:17:38 PM" :process-time 29 :type incoming-resp :method "textDocument/documentLink" :id 11 :body [#<hash-table equal 2/65 0x44947121> #<hash-table equal 2/65 0x447591c1> #<hash-table equal 2/65 0x4549c869>]) #<marker at 1196 in *lsp-log: ccls:73789*>] #s(lsp--log-entry :timestamp "05:17:38 PM" :process-time nil :type outgoing-req :method "textDocument/documentLink" :id 11 :body ...) #<marker at 1022 in *lsp-log: ccls:73789*>] #s(lsp--log-entry :timestamp "05:17:01 PM" :process-time 27 :type incoming-resp :method "textDocument/documentLink" :id 10 :body [#<hash-table equal 2/65 0x40f204b1> #<hash-table equal 2/65 0x4413b955> #<hash-table equal 2/65 0x40a29075>]) #<marker at 175 in *lsp-log: ccls:73789*>] #s(lsp--log-entry :timestamp "05:17:01 PM" :process-time nil :type outgoing-req :method "textDocument/documentLink" :id 10 :body ...) #<marker at 1 in *lsp-log: ccls:73789*>] "" #<marker at 1 in *lsp-log: ccls:73789*>] DL-LIST #<marker at 3064 in *lsp-log: ccls:73789*>] "" #<marker at 3064 in *lsp-log: ccls:73789*>] :dll [[[[[[[[[#4 #11 "" #<marker at 1 in *lsp-log: ccls:73789*>] #10 #s(lsp--log-entry :timestamp "05:17:01 PM" :process-time nil :type outgoing-req :method "textDocument/documentLink" :id 10 :body ...) #<marker at 1 in *lsp-log: ccls:73789*>] #9 #s(lsp--log-entry :timestamp "05:17:01 PM" :process-time 27 :type incoming-resp :method "textDocument/documentLink" :id 10 :body [#<hash-table equal 2/65 0x40f204b1> #<hash-table equal 2/65 0x4413b955> #<hash-table equal 2/65 0x40a29075>]) #<marker at 175 in *lsp-log: ccls:73789*>] #8 #s(lsp--log-entry :timestamp "05:17:38 PM" :process-time nil :type outgoing-req :method "textDocument/documentLink" :id 11 :body ...) #<marker at 1022 in *lsp-log: ccls:73789*>] #7 #s(lsp--log-entry :timestamp "05:17:38 PM" :process-time 29 :type incoming-resp :method "textDocument/documentLink" :id 11 :body [#<hash-table equal 2/65 0x44947121> #<hash-table equal 2/65 0x447591c1> #<hash-table equal 2/65 0x4549c869>]) #<marker at 1196 in *lsp-log: ccls:73789*>] #6 #s(lsp--log-entry :timestamp "05:18:25 PM" :process-time nil :type outgoing-req :method "textDocument/documentLink" :id 16 :body ...) #<marker at 2043 in *lsp-log: ccls:73789*>] #5 #s(lsp--log-entry :timestamp "05:18:25 PM" :process-time 26 :type incoming-resp :method "textDocument/documentLink" :id 16 :body [#<hash-table equal 2/65 0x441db9ed> #<hash-table equal 2/65 0x40ead76d> #<hash-table equal 2/65 0x4485256d>]) #<marker at 2217 in *lsp-log: ccls:73789*>] #4 "" #<marker at 3064 in *lsp-log: ccls:73789*>] [#4 [#5 [#6 [#7 [#8 [#9 [#10 [#11 #4 "" #<marker at 3064 in *lsp-log: ccls:73789*>] #s(lsp--log-entry :timestamp "05:18:25 PM" :process-time 26 :type incoming-resp :method "textDocument/documentLink" :id 16 :body [#<hash-table equal 2/65 0x441db9ed> #<hash-table equal 2/65 0x40ead76d> #<hash-table equal 2/65 0x4485256d>]) #<marker at 2217 in *lsp-log: ccls:73789*>] #s(lsp--log-entry :timestamp "05:18:25 PM" :process-time nil :type outgoing-req :method "textDocument/documentLink" :id 16 :body ...) #<marker at 2043 in *lsp-log: ccls:73789*>] #s(lsp--log-entry :timestamp "05:17:38 PM" :process-time 29 :type incoming-resp :method "textDocument/documentLink" :id 11 :body [#<hash-table equal 2/65 0x44947121> #<hash-table equal 2/65 0x447591c1> #<hash-table equal 2/65 0x4549c869>]) #<marker at 1196 in *lsp-log: ccls:73789*>] #s(lsp--log-entry :timestamp "05:17:38 PM" :process-time nil :type outgoing-req :method "textDocument/documentLink" :id 11 :body ...) #<marker at 1022 in *lsp-log: ccls:73789*>] #s(lsp--log-entry :timestamp "05:17:01 PM" :process-time 27 :type incoming-resp :method "textDocument/documentLink" :id 10 :body [#<hash-table equal 2/65 0x40f204b1> #<hash-table equal 2/65 0x4413b955> #<hash-table equal 2/65 0x40a29075>]) #<marker at 175 in *lsp-log: ccls:73789*>] #s(lsp--log-entry :timestamp "05:17:01 PM" :process-time nil :type outgoing-req :method "textDocument/documentLink" :id 10 :body (:textDocument ...)) #<marker at 1 in *lsp-log: ccls:73789*>] "" #<marker at 1 in *lsp-log: ccls:73789*>] DL-LIST #<marker at 3064 in *lsp-log: ccls:73789*>] :last-node nil :hf-pp insert) :server-capabilities #<hash-table equal 22/65 0x45500841> :registered-server-capabilities (#s(lsp--registered-capability :id "didChangeWatchedFiles" :method "workspace/didChangeWatchedFiles" :options #<hash-table equal 1/65 0x4550cf41>)) :root "/Users/yingxuan/Documents/cis240-hw9" :client #s(lsp--client :language-id nil :add-on? nil :new-connection (:connect #f(compiled-function (filter sentinel name environment-fn) #<bytecode 0x44e9abb5>) :test\? #f(compiled-function () #<bytecode 0x44e9abcd>)) :ignore-regexps nil :ignore-messages nil :notification-handlers #<hash-table equal 2/65 0x44e9abd9> :request-handlers #<hash-table equal 0/65 0x44e9aeb9> :response-handlers #<hash-table eql 0/65 0x44e9b1b1> :prefix-function nil :uri-handlers #<hash-table equal 0/65 0x44e9b4a9> :action-handlers #<hash-table equal 0/65 0x44e9b781> :major-modes (c-mode c++-mode cuda-mode objc-mode) :activation-fn nil :priority 0 :server-id ccls :multi-root nil :initialization-options #f(compiled-function () #<bytecode 0x44e7c54d>) :custom-capabilities nil :library-folders-fn nil :before-file-open-fn nil :initialized-fn nil :remote? nil :completion-in-comments? nil :path->uri-fn nil :uri->path-fn nil :environment-fn nil :after-open-fn nil :async-request-handlers #<hash-table equal 0/65 0x44e9b7a1> :download-server-fn nil :download-in-progress? nil :buffers nil) :host-root nil :proc #<process ccls> :cmd-proc #<process ccls> :buffers (#<buffer jc.c>) :semantic-highlighting-faces nil :extra-client-capabilities nil :status initialized :metadata #<hash-table equal 0/65 0x40f2f11d> :watches #<hash-table equal 0/65 0x40f2f3f5> :workspace-folders nil :last-id 0 :status-string nil :shutdown-action nil :diagnostics #<hash-table equal 0/65 0x40f2f415>))
  call-interactively(lsp-workspace-restart record nil)
  command-execute(lsp-workspace-restart record)
  counsel-M-x-action("lsp-workspace-restart")
  ivy-call()
  ivy-read("M-x " ("doom/toggle-debug-mode" "lsp-workspace-restart" "debug" "lsp-workspace-folders-switch" "lsp-restart-workspace" "lsp-workspace-show-log" "lsp" "describe-variable" "=calendar" "describe-function" "multi-term" "multi-term-dedicated-toggle" "flycheck-verify-setup" "org-gcal-fetch" "org-agenda-day-view" "describe-key" "org-agenda" "lsp-find-definition" "latex-preview-pane-mode" "company-yasnippet" "evil-goto-definition" "lsp-find-declaration" "lsp-mode" "org-gcal-sync" "lsp-describe-thing-at-point" "lsp-find-references" "ying/org-agenda-process-inbox-item" "projectile-discover-projects-in-directory" "toggle-word-wrap" "cfw:open-org-calendar" "describe-face" "dumb-jump-mode" "solaire-mode" "forge-pull" "describe-mode" "lsp-disconnect" "+word-wrap-mode" "lsp-ui-peek-mode" "+lookup/references" "delete-file" "lsp-describe-session" "org-revert-all-org-buffers" "utop" "dap-debug" "dumb-jump-go" "org-pomodoro" "multi-term-next" "evil-normal-state" "ein:jupyter-server-start" "projectile-remove-known-project" ...) :predicate #f(compiled-function (x) #<bytecode 0x4113eb65>) :require-match t :history counsel-M-x-history :action counsel-M-x-action :keymap (keymap (67108908 . counsel--info-lookup-symbol) (67108910 . counsel-find-symbol)) :initial-input nil :caller counsel-M-x)
  counsel-M-x()
  funcall-interactively(counsel-M-x)
  call-interactively(counsel-M-x nil nil)
  command-execute(counsel-M-x)
</pre></details>

**Steps to reproduce:**
1. M-x lsp-workspace-restart
2. Select the current lsp workspace
3. Error will be thrown

**System information:**
<details>

```
emacs   version    26.3
        features   JPEG RSVG IMAGEMAGICK GLIB NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2
        build      Dec 23, 2019
        buildopts  (--disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus/26.3/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus/26.3 --with-xml2 --without-dbus --with-gnutls --with-imagemagick --with-modules --with-rsvg --with-ns --disable-ns-self-contained)
        windowsys  ns
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop 8a01ef908 2020-01-20 20:17:43 -0500
        dir        ~/.doom.d/
system  type       darwin
        config     x86_64-apple-darwin19.0.0
        shell      /bin/zsh
        uname      Darwin 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64
        path       (~/.opam/4.09.0/bin ~/.pyenv/shims ~/.cargo/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /Applications/VMware Fusion.app/Contents/Public /Library/TeX/texbin /opt/X11/bin /Users/username/.pyenv ~/.NVM_DIR/versions/node/v11.10.1/bin /usr/local/Cellar/emacs-plus/26.3/libexec/emacs/26.3/x86_64-apple-darwin19.0.0/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard fill-column hl-todo modeline nav-flash ophints (popup +all +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold multiple-cursors rotate-text snippets (word-wrap +global-word-wrap-mode) :emacs dired electric ibuffer vc :checkers syntax spell grammar :tools debugger editorconfig ein (eval +overlay) (lookup +docsets) lsp macos magit make pdf :lang (cc +lsp) coq data emacs-lisp javascript (latex +latexmk) markdown ocaml (org +dragndrop +pomodoro +present) (python +lsp +pyenv) (rust +lsp) sh web :app calendar :config (default +bindings +smartparens))
        packages   ((proof-general :pin "bee3f802ada921fb8988edb96a8b41429f7c622c") px multi-term calfw-ical)
        elpa       (n/a)
```
</details>

**Comment by hlissner** [comment]
An upstream change broke an advice. As of 1e91c04 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by nobv** [comment]
I confirmed that it was fixed after the update!
Thanks!
