### ISSUE TITLE
too much Lag editing any file after latest upgrade

### ISSUE THREAD

**Issue by verajosemanuel** [hlissner/doom-emacs#2411]
updated / upgraded / refreshed today and Doom Emacs suddenly seems unusable.
Too much lag on editing files. I mostly use it for org mode but severaltimes lags for more than 5 seconds between keystroke and actually executing keybindings. Same for plain writing.

doom.info

`
emacs   version    26.3
        features   XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK2 X11 XDBE XIM THREADS
        build      oct 14, 2019
        buildopts  ()
        windowsys  nil
        daemonp    nil
doom    version    2.0.9
        build      HEAD -> develop 8a01ef908 2020-01-20 20:17:43 -0500
        dir        ~/Documents/Github/vim-config/.doom.d/
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /usr/bin/zsh
        uname      Linux 5.3.0-26-generic #28-Ubuntu SMP Wed Dec 18 05:37:46 UTC 2019 x86_64
        path       (~/.local/bin ~/bin /usr/local/mysql/bin /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /usr/games /usr/local/games /snap/bin ~/.fzf/bin /usr/local/libexec/emacs/26.3/x86_64-pc-linux-gnu)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company (helm +fuzzy) ivy :ui deft doom doom-dashboard doom-quit hl-todo modeline nav-flash neotree ophints (popup +all +defaults) pretty-code treemacs unicode vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold multiple-cursors rotate-text snippets :emacs dired electric ibuffer vc :tools docker (eval +overlay) :checkers syntax :tools gist (lookup +docsets) magit pass pdf :lang data emacs-lisp markdown (org +dragndrop +hugo +ipython +pandoc +pomodoro +present) python sh :email (mu4e +gmail) :app calendar (rss +org) twitter :config literate (default +bindings +smartparens))
        packages   (nyan-mode solarized tao-theme simplenote2 mu4e-alert nov)
        elpa       (uuidgen unicode-escape simplenote2 request-deferred request names gruvbox-theme deferred dash autothemer)
`

**Comment by dinkonin** [comment]
I had some performance problems related to the `pretty-code` module so I disabled it, also you are not on the latest doom:
> build HEAD -> develop 8a01ef908 2020-01-20 
Try and update to the latest, maybe this commit 0bc7fc1ab8f017ace940d86d0ec88e0bfc366e55 fixes things for you.

**Comment by verajosemanuel** [comment]
sorry but to my understanding, using ./bin doom update & upgrade is enough to keep it to the date.

Anyway, disabling mu4e seems that lags disappeared
