### ISSUE TITLE
Flycheck warning icon changes

### ISSUE THREAD

**Issue by mustaqimM** [hlissner/doom-emacs#2413]
**What did you expect to happen?**
The warning/error icon should appear:
![2020-01-23_19-02](https://user-images.githubusercontent.com/24436622/73007068-b1617680-3e03-11ea-9a9c-6c9c66f8372e.png)

**What actually happened?**
Initially, the icon looks like this:
![2020-01-23_19-00](https://user-images.githubusercontent.com/24436622/73007122-d81fad00-3e03-11ea-93cf-2b49856d9830.png)
And then oddly enough, I found that after just opening `~/.emacs.d/modules/tools/flycheck/config.el` in another frame, it changes to this:
![2020-01-23_18-58_1](https://user-images.githubusercontent.com/24436622/73007236-1d43df00-3e04-11ea-8d93-cb782bbb9482.png)
And then if I run `flycheck-verify-setup (C-c ! v)`, it changes to the expected image above.

**Steps to reproduce:**
1. Open a file with flychecker enabled,
2. Open `~/.emacs.d/modules/tools/flycheck/config.el` and the icon will change,
3. Run `flycheck-verify-setup (C-c ! v)` and the icon will move to the right.

**System information:**
<details><pre>
emacs   version    26.3
        features   XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LCMS2
        build      Aug 29, 2019
        buildopts  (--with-x-toolkit=gtk3 --with-xwidgets --prefix=/usr --sysconfdir=/etc --sbindir=/usr/bin --bindir=/usr/bin --mandir=/usr/share/man --infodir=/usr/share/info --localstatedir=/var --with-file-notification=inotify --with-modules --with-jpeg --with-tiff --with-gif --with-png --with-xpm --with-rsvg --without-imagemagick --with-xml2 --with-gnutls --with-sound --with-m17n-flt --host=x86_64-unknown-linux-gnu --build=x86_64-unknown-linux-gnu 'CFLAGS=-fno-PIE -mtune=generic -O2 -pipe   -g' 'CPPFLAGS=   ' 'LDFLAGS=-no-pie -Wl,--as-needed    ')
        windowsys  x
        daemonp    daemon
doom    version    2.0.9
        build      HEAD -> develop, origin/develop, origin/HEAD 934e4fc06 2019-12-26 01:41:45 -0500
        dir        ~/.config/doom/
system  type       gnu/linux
        config     x86_64-unknown-linux-gnu
        shell      /bin/sh
        uname      Linux 5.4.13_2 #1 SMP PREEMPT Sun Jan 19 12:22:44 UTC 2020 x86_64
        path       (~/.emacs.d/bin/ ~/.zplugin/snippets/cht.sh/ ~/.zplugin/plugins/zdharma---zsh-diff-so-fancy/bin/ ~/.zplugin/plugins/junegunn---fzf-bin/ ~/.zplugin/plugins/karan---joe/ ~/.zplugin/plugins/dylanaraps---pfetch/ ~/.zplugin/plugins/Peltoche---lsd/lsd/ ~/.zplugin/plugins/pixelb---ps_mem/ ~/.zplugin/plugins/direnv---direnv/ ~/.zplugin/plugins/sei40kr---fast-alias-tips-bin/ ~/.cargo/bin/ ~/.local/bin/sml/bin/ /usr/local/bin/ /bin/ /usr/bin/ /usr/local/sbin/ /usr/sbin/ /sbin/ /opt/texlive/2019/bin/x86_64-linux/ /usr/libexec/emacs/26.3/x86_64-unknown-linux-gnu/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold multiple-cursors rotate-text snippets :emacs dired electric ibuffer vc :tools direnv docker (eval +overlay) flycheck (lookup +docsets) magit rgb :lang data emacs-lisp latex lua markdown (org +dragndrop +present) python racket ruby rust sh :config (default +bindings +smartparens))
        packages   (sml-mode flycheck-rust flycheck-inline)
        elpa       (nand2tetris company-nand2tetris company)
</pre></details>

**Comment by hlissner** [comment]
You are on a somewhat old commit of Doom (934e4fc06). The flycheck module was moved to `:checkers syntax` and some aspects of it were rewritten. Please update and let me know if the issue persists.

**Comment by mustaqimM** [comment]
I just reinstalled doom but it still is the same

**Comment by sashvoncurtis** [comment]
This commit (b89992624b95400a6023bb27030d56a9f58d6bd6) of doom-emacs seems to be the cause. 

The warning after doom/refresh is  WARNING (:tools flycheck) module was moved to (:checkers syntax)

This means that flycheck cannot find a checker.

**Comment by hlissner** [comment]
> This commit (b899926) of doom-emacs seems to be the cause.

@sashvoncurtis That is certainly when the module was moved. The warning tells you the module has moved, but Doom is smart enough to load the module at its new location. It's still a good idea to updating your `doom!` block in init.el, however, because this is a deprecation notice.

> I just reinstalled doom but it still is the same

@mustaqimM I've so far been unable to reproduce this issue. I suspect `flycheck-inline` may have something to do with it. How are you activating it? Do you have a link to your config?

Can you reproduce this issue [in the sandbox](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#testing-in-dooms-sandbox)? Open it and press `C-c C-p` to start a new instance of Doom minus your private config, and see if you can reproduce it there.

**Comment by mustaqimM** [comment]
@hlissner I see that I no longer have this issue; if you wish, please close it

(sorry for not replying earlier; for some reason I didn't get a notification)
