### ISSUE TITLE
Error with orgit on fresh install

### ISSUE THREAD

**Issue by dylanscott** [hlissner/doom-emacs#2415]
I'm trying to install Doom on macOS with a fresh emacs-plus install and I'm running into the following error while running `doom install`, right after it seems to be installing the `orgit` package:

```
  → Building orgit...
  → Building orgit...done
x There was an unexpected error:
  Type: doom-package-error
  Message:
    Error with packages
  Data:
    "orgit"
    (file-missing "Cannot open load file" "No such file or directory" "magit-section")
    ""
```

If I rerun `doom install` it seems to start installing the next package after `orgit` and completes "successfully" but running `doom doctor` I get an error `org is not installed` and when I launch emacs I get the same error from the install displayed at the bottom:

```
Failed to load 'org' package incrementally, because: (file-missing Cannot open load file No such file or directory magit-section)
```

**Comment by dinkonin** [comment]
It's an upstream magit bug since https://emacsair.me/2020/01/23/magit-section/. Apparently Jonas Bernoulli forgot to mark magit-section as a dependency of magit.

**Comment by maxfurman** [comment]
@dylanscott you can work around this for now by adding magit-section to `.emacs.d/modules/lang/org/packages.el` at line 53 like so:

```
(when (featurep! :tools magit)
  (package! magit-section)
  (package! orgit :pin "e7cddf39e301c87c36c7de13e429dee74874d5c8"))
```
Then doom install should work for you.

**Comment by hlissner** [comment]
As of 24d804d this should be resolved. I'll keep the issue open until it is resolved upstream. Thanks for bringing it to my attention!

**Comment by dylanscott** [comment]
Confirmed the install works with 24d804da79a5a909256ea0e283ef470855a81748. Thanks all for the very quick response!

**Comment by dinkonin** [comment]
Just a heads-up, it's now fixed in upstream. https://github.com/magit/magit/commit/6bfe8c0957fa178eb15007055b5197f17ab2632f

**Comment by hlissner** [comment]
@dinkonin excellent! Thanks for letting me know!
