### ISSUE TITLE
Eldoc utilizing outdated package (gocode) instead of gopls

### ISSUE THREAD

**Issue by Proziam** [hlissner/doom-emacs#2419]
**What did you expect to happen?**
...
I expected to see information about the selected go code

**What actually happened?**
...
I receive the following error:
eldoc error: (file-missing Searching for program no such file or directory gocode)

**Additional details:**
- Include a link to your private config
Fresh install, no customizations except to uncomment go in .el files as far as I can remember.

**If an error message is involved include a backtrace of it.**
<details><pre>
Debugger entered--Lisp error: (file-missing "Searching for program" "No such file or directory" "gocode")
  call-process-region(1 2204 "gocode" "/tmp/emacsWNYUvm" #<buffer *go-eldoc*> nil "-f=emacs" "autocomplete" "/home/eric/Projects/skywalker/API/youtube/main.go" "c1735")
  apply(call-process-region 1 2204 "gocode" nil #<buffer *go-eldoc*> nil ("-f=emacs" "autocomplete" "/home/eric/Projects/skywalker/API/youtube/main.go" "c1735"))
  go-eldoc--invoke-autocomplete()
  go-eldoc--get-cursor-info((1728 . 1736))
  go-eldoc--documentation-function()
  eldoc-print-current-symbol-info()
  #f(compiled-function () #<bytecode 0x280563>)()
  apply(#f(compiled-function () #<bytecode 0x280563>) nil)
  timer-event-handler([t 0 0 500000 nil #f(compiled-function () #<bytecode 0x280563>) nil idle 0])

</pre></details>

**Steps to reproduce:**
1. open any .go file
2. place cursor on any bit of go code
3. eldoc error: (file-missing Searching for program No such file or directory gocode) shows up

**System information:**
<details><pre>
```
emacs   version    26.3
        features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD LCMS2
        build      Sep 16, 2019
        buildopts  (--build=x86_64-linux-gnu --prefix=/usr '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' --sysconfdir=/etc --localstatedir=/var --disable-silent-rules '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' --disable-maintainer-mode --disable-dependency-tracking --prefix=/usr --sharedstatedir=/var/lib --program-suffix=26 --with-modules --with-file-notification=inotify --with-mailutils --with-x=yes --with-x-toolkit=gtk3 --with-xwidgets --with-lcms2 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/emacs26-TP6iDo/emacs26-26.3~1.git96dd019=. -fstack-protector-strong -Wformat -Werror=format-security -no-pie' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro -no-pie')
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop, origin/develop, origin/HEAD 3ebdc513f 2020-01-24 05:16:09 -0500
        dir        ~/.doom.d/
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/bash
        uname      Linux 5.3.0-26-generic #28~18.04.1-Ubuntu SMP Wed Dec 18 16:40:14 UTC 2019 x86_64
        path       (~/.emacs.d/bin /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /usr/games /usr/local/games /usr/local/go/bin /usr/lib/x86_64-linux-gnu/emacs/26.3/x86_64-linux-gnu/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion (company +auto) ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash neotree ophints (popup +all +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold multiple-cursors rotate-text snippets :emacs electric ibuffer vc :term term :checkers syntax :tools (eval +overlay) (lookup +docsets) magit :lang data emacs-lisp go javascript markdown (org +dragndrop +hugo +present) sh :config (default +bindings +smartparens))
        packages   (n/a)
        elpa       (n/a)
```
</details>
</pre>

I'm absolutely loving doom and think that once I get the hang of it I'm going to love it even more. (I'm brand-new - as in yesterday - to emacs so it's totally possible my issues are due to gross lack of experience)

**Comment by hlissner** [comment]
You have to activate `:lang (go +lsp)` to enable LSP support. [Whether or not Doom uses gocode or gopls depends on it](https://github.com/hlissner/doom-emacs/blob/develop/modules/lang/go/config.el#L22-L24).

Hope that helps!

**Comment by Proziam** [comment]
Wow, that was blazing fast. Thanks a ton, the error is indeed gone!
