### ISSUE TITLE
Ruby's `bundle open` is broken

### ISSUE THREAD

**Issue by nate** [hlissner/doom-emacs#2421]
**What did you expect to happen?**

I expected `SPC m b o` and selecting a gem from the dialogue to then open a gem.

**What actually happened?**

It asks if I want to create a directory that is just the deprecation warning.

**Additional details:**

I fixed this in my fork of bundler.el .

https://github.com/nate/bundler.el/commit/10a18a9322a6d318121ac82527f5aab5374ce87b

**Steps to reproduce:**

In a ruby project with a Gemfile and the latest bundler version, attempt to do `SPC m b o` and select a gem. It will ask you if you want to create a directory called something like `[DEPRECATION] ...` which is the first line of output for the deprecated commands.

**Comment by hlissner** [comment]
Looks like a case of abandonware. I've switched to your fork in 87b33c4. I'll keep this issue open until endofunky/bundler.el#25 is merged. Thanks for bringing it to my attention!

**Comment by endofunky** [comment]
@hlissner FYI endofunky/bundler.el#25 is merged now.

> Looks like a case of abandonware.

It's not, just considered feature complete.

**Comment by hlissner** [comment]
Understood. I've reverted back to the original package in ff4a9c1. Thanks for bringing this to my attention!
