### ISSUE TITLE
What's doom's way to jump to previous point after execute +lookup/definition?

### ISSUE THREAD

**Issue by FirstLoveLife** [hlissner/doom-emacs#2422]
Say that we are at `A`, then `+lookup/definition` takes us to `B`, then `+lookup/definition` again jumps to `C`, how to go back to `B` and `C`?

**Comment by hlissner** [comment]
Pressing `C-o` (`better-jumper-jump-backward`) will travel backward in the jumplist. No guarantee it'll be exactly 3 keypresses (because a number of motions add to the jumplist), but it will get you back to B and A. Then there's `C-i` (`better-jumper-jump-forward`) to go _forward_ in the jumplist.
