### ISSUE TITLE
Run pytest with PYTHONPATH set

### ISSUE THREAD

**Issue by lccambiaghi** [hlissner/doom-emacs#2424]
**What are you trying to achieve?**
I am trying to run pytest with `python-pytest-popup` or `python-pytest-function` but pytest cannot import my modules in the PYTHONPATH.

**What have you tried?**
I have `direnv-mode` active.
In my `.envrc` I have the line `export PYTHONPATH=src`.

I added
```
(add-hook! python-mode
  (direnv-update-environment))
```
and I see in Emacs the `direnv` ouput before LSP get started (with the right python/pytest executable from the `.venv`). 

When I open a `REPL` the PYTHONPATH is set correctly and I can import my modules.
Pytest however seems to not receive the env variable.

The command is correct, if I prefix the argument `SPC u` before executing the test and I add `PYTHONPATH=src` in front of the command it works as expected.

Additional note: if I run `(getenv "PYTHONPATH)` in the `eshell` I see the env variable is set.

**System information**
<details><pre>
((emacs
  (version . "27.0.60")
  (features . "RSVG IMAGEMAGICK GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS JSON PDUMPER LCMS2 GMP")
  (build . "Jan 22, 2020")
  (buildopts "--disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus/HEAD-d02f2a7/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus/HEAD-d02f2a7 --with-xml2 --without-dbus --with-gnutls --with-imagemagick --with-json --with-modules --with-rsvg --with-ns --disable-ns-self-contained")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop 3ebdc513f 2020-01-24 05:16:09 -0500")
  (dir . "~/.doom.d/"))
 (system
  (type . darwin)
  (config . "x86_64-apple-darwin19.2.0")
  (shell . "/bin/zsh")
  (uname . "Darwin 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64")
  (path "~/.pyenv/plugins/pyenv-virtualenv/shims" "~/.pyenv/shims" "~/.pyenv/plugins/pyenv-virtualenv/shims" "~/.pyenv/shims" "/usr/local/bin" "/usr/bin" "/bin" "/usr/sbin" "/sbin" "/usr/local/MacGPG2/bin" "/usr/local/share/dotnet" "/opt/X11/bin" "~/.dotnet/tools" "~/.emacs.d/bin" "~/.poetry/bin" "~/.pyenv/bin" "/usr/local/Cellar/emacs-plus/HEAD-d02f2a7/libexec/emacs/27.0.60/x86_64-apple-darwin19.2.0"))
 (config
  (envfile . envvar-file)
  (elc-files . 32)
  (modules :completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash neotree ophints (popup +all +defaults) tabs vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) fold snippets :emacs dired electric ibuffer vc :term eshell term :checkers syntax spell :tools debugger direnv (eval +overlay) (lookup +docsets) lsp macos magit make :lang data emacs-lisp ess markdown (org +dragndrop +export +pandoc) (python +lsp) sh :config literate (default +bindings +smartparens))
  (packages org-reverse-datetree poetry exec-path-from-shell)
  (elpa "direnv" "dash")))
</pre></details>

**Comment by jimpudar** [comment]
Did you by chance try adding an empty `conftest.py` in your project's root directory? This has the side effect of allowing pytest to auto-magically recognize your project's packages without the need for modifying `PYTHONPATH`...

**Comment by lccambiaghi** [comment]
The problem seemed to be disappeared, now pytest seems to pick up the PYTHONPATH as expected. I'll close the issue.

**Comment by lccambiaghi** [comment]
So the problem reappeared. When I run `getenv "PYTHONPATH"` I see the env variable is not set in Emacs, so it is not passed to the pytest functions.

I suspect my hook is not set properly, as I read also in this issue: 
https://github.com/wbolster/emacs-direnv/issues/17

Any advice?

**Comment by lccambiaghi** [comment]
Solved it by setting an absolute PYTHONPATH and not relative to the project root!

**Comment by bersace** [comment]
Why not pick pytest from virtualenv path with `(+python-exectuable-find "pytest")` ? This avoid using a global pytest installation for all projects. Especially when mixing pythons versions.
