### ISSUE TITLE
JetBrains Mono font is horribly crunchy if set as default

### ISSUE THREAD

**Issue by FreeSalad** [hlissner/doom-emacs#2427]
**What did you expect to happen?**
Putting `(setq doom-font (font-spec :family "JetBrains Mono" :size 13.0))` in my `config.el` to choose JetBrains Mono as the default font, and have the same result as that of `M-x menu-set-font`.

**What actually happened?**
Emacs loads with a horrible render of the font, with the only solution being using `M-x menu-set-font`. ![After loading](https://i.imgur.com/o8vKmws.png)
against
![Expected](https://i.imgur.com/XU4X8Zc.png)

**Additional details:**
Other fonts such as Source Code Pro or Fira Sans do not cause that issue.

**Steps to reproduce:**
1. Put `(setq doom-font (font-spec :family "JetBrains Mono" :size 13.0))` inside `config.el`

**System information:**
<details>

```
emacs   version    26.3
        features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2
        build      Aug 29, 2019
        buildopts  (--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-modules 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now)
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop 8a01ef908 2020-01-20 20:17:43 -0500
        dir        ~/.config/doom/
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /usr/bin/zsh
        uname      Linux 5.4.10-arch1-1 #1 SMP PREEMPT Thu, 09 Jan 2020 10:14:29 +0000 x86_64
        path       (/usr/local/texlive/2019/bin/x86_64-linux /usr/local/texlive/2019/bin/x86_64-linux /usr/local/texlive/2019/bin/x86_64-linux /usr/local/texlive/2019/bin/x86_64-linux /usr/local/texlive/2019/bin/x86_64-linux /usr/local/sbin /usr/local/bin /usr/bin /usr/local/texlive/2019/bin/x86_64-linux /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /usr/lib/emacs/26.3/x86_64-pc-linux-gnu)
config  envfile    nil
        elc-files  0
        modules    (:completion (company +childframe) ivy :ui doom doom-dashboard hl-todo indent-guides modeline nav-flash ophints (popup +all +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold multiple-cursors rotate-text snippets :emacs (dired +icons) electric vc :tools docker editorconfig eval (lookup +docsets) magit pdf :lang agda data emacs-lisp (haskell +intero) (latex +latexmk) markdown (org +attach +babel +capture +export +habit +present +protocol) sh web :checkers syntax :config (default +bindings +smartparens) literate)
        packages   ((company-prescient :disable t :pin "7fd8c3b8028da4733434940c4aac1209281bef58"))
        elpa       (n/a)
```
</details>

**Comment by hlissner** [comment]
I cannot reproduce this on NixOS or in my Mojave VM with the JetBrains font. Could this be a bad fontconfig? I'll spin up an arch vm sometime over the weekend and try there.

**Comment by FreeSalad** [comment]
Just confirmed that this happens whether or not I am running on Wayland or Xorg, and the font looks fine in other applications. What is really weird is the fact that `menu-set-font` does not exhibit that behavior at all.

**Comment by iris-garcia** [comment]
I cannot reproduce it in Linux using Xorg.

**Comment by howdoicomputer** [comment]
Uh, so I had this problem on my system and I fixed it by changing the font name to "JetBrainsMono." Weird bug. Didn't look into why it was occurring and just moved on.

**Comment by robbert-vdh** [comment]
I tried JetBrains Mono yesterday for the first time and all was well, but today I was having the same issue with text looking like the first screenshot with Emacs 28 on Manjaro. Changing the font family to `JetBrainsMono` without a space indeed does resolve the issue, but I'm not sure why it did work fine yesterday.

**Comment by FreeSalad** [comment]
Using "JetBrainsMono" does indeed resolve this bug, however `fc-match` does find both of them, so it would not appear to be a fontconfig issue to me. I will close this issue as this seems to be a reliable workaround to a very specific bug.

**Comment by bersace** [comment]
I'm set JetBrainsMono from gnome-tweak-tools and it works perfectly both in Doom and terminal.
