### ISSUE TITLE
doom upgrade from within emacs does not work

### ISSUE THREAD

**Issue by codygman** [hlissner/doom-emacs#2428]
**What did you expect to happen?**
To call `M-x doom/upgrade` and upgrade successfully.

**What actually happened?**
I called `M-x doom/upgrade` and was presented with:

```
-*- mode: compilation; default-directory: "~/bsab/" -*-
Compilation started at Sat Jan 25 22:32:05

/home/cody/.emacs.d/bin/doom upgrade
Loading /nix/store/gj66vn85p4brc2z33khgaw7pl5azplz8-emacs-27.0.50/share/emacs/site-lisp/site-start.el (source)...
> Preparing to upgrade Doom Emacs and its packages...
- A new version of Doom Emacs is available!

  Old revision: 12ebc58f2e (11 days ago)
  New revision: de6732b4ae (8 hours ago)

View the comparison diff in your browser? (y or n) 
```

I hit yes and nothing happend, hit yes a second time, and then realized my focus was still in the org buffer I was in before calling upgrade.

Since you can't proceed past the yes or no question in any way, upgrading is not possible.

**System information:**
<details><pre>
((emacs
  (version . "27.0.50")
  (features . "XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GSETTINGS GLIB NOTIFY INOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER GMP")
  (build . "Jan 25, 2020")
  (buildopts "--prefix=/nix/store/gj66vn85p4brc2z33khgaw7pl5azplz8-emacs-27.0.50 --disable-build-details --with-modules --with-x-toolkit=gtk3 --with-xft CFLAGS=-DMAC_OS_X_VERSION_MAX_ALLOWED=101200")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop 12ebc58f2 2020-01-15 02:20:46 -0500")
  (dir . "~/.config/doom/"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/run/current-system/sw/bin/bash")
  (uname . "Linux 4.19.91 #1-NixOS SMP Sat Dec 21 09:57:45 UTC 2019 x86_64")
  (path "/nix/store/m9ckg7cvzv7anbygg7vyw432srcs45nd-emacs-packages-deps/bin" "/run/wrappers/bin" "~/.nix-profile/bin" "/etc/profiles/per-user/cody/bin" "/nix/var/nix/profiles/default/bin" "/run/current-system/sw/bin" "/nix/store/gj66vn85p4brc2z33khgaw7pl5azplz8-emacs-27.0.50/libexec/emacs/27.0.50/x86_64-pc-linux-gnu"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold multiple-cursors rotate-text snippets word-wrap :emacs dired electric ibuffer vc :term eshell shell :checkers syntax :tools docker (eval +overlay) (lookup +docsets) magit :lang data emacs-lisp markdown nix (org +dragndrop +present) sh :config literate (default +bindings +smartparens))
  (packages prescient "(company-prescient :pin \"7fd8c3b8028da4733434940c4aac1209281bef58\")" all-the-icons-ivy counsel-tramp peep-dired "(diredfl :pin \"83567d00affce66a4e501563eddd0bd436ac48d0\")" yasnippet-snippets apache-mode pkgbuild-mode nginx-mode ob-http systemd flycheck-checkbashisms tldr "(doom-modeline :pin \"dbd9251979de2d94073197b406fe5a72aa593e5d\")" "(anzu :pin \"592f8ee6d0b1bc543943b36a30063c2d1aac4b22\")" "(evil-anzu :pin \"9bca6ca14d865e7e005bc02a28a09b4ae74facc9\")" "(om :recipe (:repo \"https://github.com/ndwarshuis/om.el.git\"))" highlight-indent-guides org-super-agenda dired-quick-sort org-starter org-reverse-datetree org-web-tools)
  (elpa "n/a")))

</pre></details>

**Comment by hlissner** [comment]
Sorry for the late response. This was fixed in 0e851ace9ba4, back in May. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
