### ISSUE TITLE
max-lisp-eval-depth on tab-completing in GHCi when using :completion (company +tng)

### ISSUE THREAD

**Issue by tstenhaug** [hlissner/doom-emacs#2431]
I open up a `.hs`-file, and press `SPC o r` to jump to a REPL.  When I type some text and press `TAB` to complete, I get a `max-lisp-eval-depth` error.   When I don't use the `+tng` flag, completion works as expected.

**What did you expect to happen?**

Get a popup with completion candidates.

**What actually happened?**

An error message `Lisp nesting exceeds ‘max-lisp-eval-depth` and Emacs hangs.

**Additional details:**

Backtrace of the "upper" part of the infinite recursion.

<details><pre>
Debugger entered--Lisp error: (error "Lisp nesting exceeds ‘max-lisp-eval-depth’")
  (and t (gethash (cons category module) doom-modules))
  (let* ((plist (and t (gethash (cons category module) doom-modules)))) (if plist (or (null flag) (and (memq flag (plist-get plist :flags)) t)) nil))
  doom-module-p(:editor snippets)
  (cond (flag (memq flag (doom-module-get category module :flags))) (module (doom-module-p category module)) (doom--current-flags (memq category doom--current-flags)) ((let ((module (doom-module-from-path))) (if module nil (error "(featurep! %s %s %s) couldn't figure out what module it was called from (in %s)" category module flag (file!))) (memq category (doom-module-get (car module) (cdr module) :flags)))))
  (and (cond (flag (memq flag (doom-module-get category module :flags))) (module (doom-module-p category module)) (doom--current-flags (memq category doom--current-flags)) ((let ((module (doom-module-from-path))) (if module nil (error "(featurep! %s %s %s) couldn't figure out what module it was called from (in %s)" category module flag (file!))) (memq category (doom-module-get (car module) (cdr module) :flags))))) t)
  (closure (doom-disabled-packages t) (category &optional module flag) "Returns t if CATEGORY MODULE is enabled.\n\nIf FLAG is provided, returns t if CATEGORY MODULE has FLAG enabled.\n\n  (featurep! :config default)\n\nModule FLAGs are set in your config's `doom!' block, typically in\n~/.emacs.d/init.el. Like so:\n\n  :config (default +flag1 -flag2)\n\nCATEGORY and MODULE can be omitted When this macro is used from inside a module\n(except your DOOMDIR, which is a special module). e.g. (featurep! +flag)" (and (cond (flag (memq flag (doom-module-get category module :flags))) (module (doom-module-p category module)) (doom--current-flags (memq category doom--current-flags)) ((let ((module (doom-module-from-path))) (if module nil (error "(featurep! %s %s %s) couldn't figure out what module it was called from (in %s)" category module flag (file!))) (memq category (doom-module-get (car module) (cdr module) :flags))))) t))(:editor snippets)
  (featurep! :editor snippets)
  (and (featurep! :editor snippets) (bound-and-true-p yas-minor-mode) (yas-maybe-expand-abbrev-key-filter (quote yas-expand)))
  (cond ((and (featurep! :editor snippets) (bound-and-true-p yas-minor-mode) (yas-maybe-expand-abbrev-key-filter (quote yas-expand))) (function yas-expand)) ((and (featurep! :completion company +tng) (+company-has-completion-p)) (function +company/complete)) (t nil))
  (lambda (&optional _) (cond ((and (featurep! :editor snippets) (bound-and-true-p yas-minor-mode) (yas-maybe-expand-abbrev-key-filter (quote yas-expand))) (function yas-expand)) ((and (featurep! :completion company +tng) (+company-has-completion-p)) (function +company/complete)) (t nil)))(nil)
  key-binding([tab])
  company--should-complete()
  company--perform()
  company-auto-begin()
  company-manual-begin()
  (and (company-manual-begin) (= company-candidates-length 1))
  +company-has-completion-p()
  (and (featurep! :completion company +tng) (+company-has-completion-p))
  (cond ((and (featurep! :editor snippets) (bound-and-true-p yas-minor-mode) (yas-maybe-expand-abbrev-key-filter (quote yas-expand))) (function yas-expand)) ((and (featurep! :completion company +tng) (+company-has-completion-p)) (function +company/complete)) (t nil))
  (lambda (&optional _) (cond ((and (featurep! :editor snippets) (bound-and-true-p yas-minor-mode) (yas-maybe-expand-abbrev-key-filter (quote yas-expand))) (function yas-expand)) ((and (featurep! :completion company +tng) (+company-has-completion-p)) (function +company/complete)) (t nil)))(nil)
  key-binding([tab])
  company--should-complete()
  company--perform()
  company-auto-begin()
  company-manual-begin()
  (and (company-manual-begin) (= company-candidates-length 1))
  +company-has-completion-p()
  (and (featurep! :completion company +tng) (+company-has-completion-p))
  (cond ((and (featurep! :editor snippets) (bound-and-true-p yas-minor-mode) (yas-maybe-expand-abbrev-key-filter (quote yas-expand))) (function yas-expand)) ((and (featurep! :completion company +tng) (+company-has-completion-p)) (function +company/complete)) (t nil))
  (lambda (&optional _) (cond ((and (featurep! :editor snippets) (bound-and-true-p yas-minor-mode) (yas-maybe-expand-abbrev-key-filter (quote yas-expand))) (function yas-expand)) ((and (featurep! :completion company +tng) (+company-has-completion-p)) (function +company/complete)) (t nil)))(nil)
  key-binding([tab])
  company--should-complete()
  company--perform()
  company-auto-begin()
  company-manual-begin()
  (and (company-manual-begin) (= company-candidates-length 1))
  +company-has-completion-p()
</pre></details>

**Steps to reproduce:**
1. Open a .hs file (an empty one will do)
2. `SPC o r`
3. `d TAB`

**System information:**
<details>

```
emacs   version    26.3
        features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2
        build      Aug 29, 2019
        buildopts  (--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-modules 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now)
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop de6732b4a 2020-01-25 15:58:09 -0500
        dir        ~/ke/dotfiles/doom.d/
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/zsh
        uname      Linux 5.4.13-arch1-1 #1 SMP PREEMPT Fri, 17 Jan 2020 23:09:54 +0000 x86_64
        path       (~/ke/sh ~/.local/bin /usr/local/bin /usr/local/sbin /usr/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /usr/lib/emacs/26.3/x86_64-pc-linux-gnu/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion (company +tng) ivy :ui doom doom-dashboard fill-column hl-todo hydra modeline nav-flash ophints (popup +all +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold lispy multiple-cursors rotate-text snippets :emacs dired electric ibuffer vc :term term :tools (eval +overlay) :checkers syntax :tools (lookup +docsets) magit pdf rgb :lang assembly cc clojure common-lisp data emacs-lisp (haskell +dante) javascript latex markdown (org +present) (python +pyenv) sh :app calendar :config (default +bindings +smartparens))
        packages   (graphviz-dot-mode (org-download :pin "a367669384859261bcb11bac4b782f231f972353") outshine ox-reveal lorem-ipsum xah-math-input)
        elpa       (n/a)
```
</details>

**Comment by karvus** [comment]
Forgot the steps-to-reproduce part, edited now.

**Comment by karvus** [comment]
This behavior is displayed when having `(haskell +dante)` or `(haskell +lsp)` under the `:lang` section in my `doom!` block.  Not when using `(haskell +intero)` though, I don't understand how it gathers completion candidates differently.
