### ISSUE TITLE
mu4e - additional entry is marked when marking with visual mode

### ISSUE THREAD

**Issue by WhatDothLife** [hlissner/doom-emacs#2432]
**What did you expect to happen?**
I expected only the entries to be marked within the current region.

**What actually happened?**
An additional entry is marked below the current line.

**Additional details:**
[Private config](https://github.com/WhatDothLife/doom-config)
![mu4e-1](https://user-images.githubusercontent.com/33008303/73138594-be30d500-4064-11ea-8220-46da50c2e1fd.png)
![mu4e-2](https://user-images.githubusercontent.com/33008303/73138596-c25cf280-4064-11ea-8ac4-84dd0b576fa5.png)

**Steps to reproduce:**
1. Press `V` to enter visual mode and select an arbitrary number of lines
2. Mark all mails within the region with a flag, e.g. `D`

**System information:**
<details><pre>
<details>

```
emacs   version    26.3
        features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD LCMS2
        build      Sep 16, 2019
        buildopts  (--build=x86_64-linux-gnu --prefix=/usr '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' --sysconfdir=/etc --localstatedir=/var --disable-silent-rules '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' --disable-maintainer-mode --disable-dependency-tracking --prefix=/usr --sharedstatedir=/var/lib --program-suffix=26 --with-modules --with-file-notification=inotify --with-mailutils --with-x=yes --with-x-toolkit=gtk3 --with-xwidgets --with-lcms2 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/emacs26-TP6iDo/emacs26-26.3~1.git96dd019=. -fstack-protector-strong -Wformat -Werror=format-security -no-pie' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro -no-pie')
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop 12094788d 2020-01-14 03:04:26 -0500
        dir        ~/.doom.d/
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/bash
        uname      Linux 5.0.0-37-generic #40~18.04.1-Ubuntu SMP Thu Nov 14 12:06:39 UTC 2019 x86_64
        path       (~/programs/tor-browser_en-US ~/.cargo/bin /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /usr/games /usr/local/games /snap/bin /usr/lib/x86_64-linux-gnu/emacs/26.3/x86_64-linux-gnu)
config  envfile    nil
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold format multiple-cursors rotate-text snippets :emacs dired electric ibuffer vc :term eshell shell :tools ein (eval +overlay) :checkers syntax spell :tools (lookup +docsets) magit pass pdf upload :lang cc data emacs-lisp latex markdown org python sh :email mu4e :app irc :config (default +bindings +smartparens))
        packages   (academic-phrases yasnippet-snippets buffer-move)
        elpa       (n/a)
```
</details>
</pre></details>

**Comment by alexandergraul** [comment]
FWIW I can't reproduce this behavior. Only selected lines are marked for deletion for me.

**Comment by WhatDothLife** [comment]
Good to know. I was able to reproduce this without my private config, though. I'll investigate.

**Comment by brookter** [comment]
I see this behaviour both in mu4e as described, but also when using visual selection with M-x ; (comment-line). As far as I remember, it's always been that way. I just assumed it was the expected behaviour...

**Comment by WhatDothLife** [comment]
> I see this behaviour both in mu4e as described, but also when using visual selection with M-x ; (comment-line).

Try using `(comment-dwim)` instead. It works fine.

**Comment by WhatDothLife** [comment]
> FWIW I can't reproduce this behavior. Only selected lines are marked for deletion for me.

Is this also true for `(comment-line)`?

**Comment by brookter** [comment]
> > I see this behaviour both in mu4e as described, but also when using visual selection with M-x ; (comment-line).
> 
> Try using `(comment-dwim)` instead. It works fine.

DWIM should be renamed DWIYTIMIWISDM -- for some reason it thinks I always want to add comments at the end of single lines and I never do. Rather than fiddle around trying to convince it to listen to what it's being told, it's easier to use comment-line.

**Comment by WhatDothLife** [comment]
> FWIW I can't reproduce this behavior. Only selected lines are marked for deletion for me.

@agraul Are you an evil user? Does `comment-line` show the same behavior?

**Comment by tecosaur** [comment]
Just tried this, couldn't reproduce.

**Comment by WhatDothLife** [comment]
Ah, it must have been resolved in the meantime!
