### ISSUE TITLE
Coq multiple window UI from Proof General combined with ui/tabs has unusable performance

### ISSUE THREAD

**Issue by tchajed** [hlissner/doom-emacs#2436]
**What did you expect to happen?**

I expected Proof General (the package that gives Coq support) to continue to work.

**What actually happened?**

Some background on Proof General and Coq: Coq is an interactive proof assistant, which supports interactively writing proofs with feedback from Coq about the current status of the proof. It also supports interactive queries while writing code, with responses about type and definitions and such.

PG, the Coq Emacs package, implements a UI for Coq within Emacs. It splits the frame into three windows, the editor, `*goals*` (displaying interactive state for the current proof), and `*response*` (displaying responses to interactive queries). These goals and response windows are read-only output from Coq.

Proof General now has terrible performance. Emacs seems to be navigating through the three windows in PG rapidly on every keystroke or Coq interaction, resulting in flickering and high CPU usage. This might be a general problem with multiple windows, and is probably due to a misconfiguration. One important difference I noticed is that each of these windows now has centaur tabs. This is great for the editor window, but wrong for the other two, which are more like popups in other languages (although they're persistent and there's no sense in hiding them).

**Additional details:**
- My private config is at https://github.com/tchajed/dotfiles/tree/master/emacs/doom
- Here's a screen recording of the issue: https://www.dropbox.com/s/eb9bz9qj2muyfec/doom-PG-issue-2436.mov?dl=0

**Steps to reproduce:**
- Enable the `coq` language.
- Open a Coq file and start stepping through it.

**System information:**
<details><pre>
((emacs
  (version . "26.2")
  (features . "NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS")
  (build . "Apr 12, 2019")
  (buildopts "--with-ns '--enable-locallisppath=/Library/Application Support/Emacs/${version}/site-lisp:/Library/Application Support/Emacs/site-lisp' --with-modules")
  (windowsys . batch)
  (daemonp))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop 26e0e9dd2 2020-01-27 03:06:14 -0500")
  (dir . "~/.dotfiles/emacs/doom/"))
 (system
  (type . darwin)
  (config . "x86_64-apple-darwin18.2.0")
  (shell . "/bin/bash")
  (uname . "Darwin 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64")
  (path "~/code/sw/coq/_build/install/default/bin/" "." "~/.opam/4.07.1/bin" "~/doom-emacs.d/bin" "~/.gem/bin" "~/.dotfiles/bin" "~/code/sw/latexrun" "~/.cargo/bin" "~/go/bin" "~/.local/bin" "/usr/local/bin" "/usr/local/sbin" "~/.fzf/bin" "/usr/local/bin" "/usr/bin" "/bin" "/usr/sbin" "/sbin" "/opt/X11/bin" "/Applications/VMware Fusion.app/Contents/Public" "/usr/local/MacGPG2/bin" "/Library/TeX/texbin" "." "/Applications/Wireshark.app/Contents/MacOS" "/Applications/Emacs.app/Contents/MacOS/bin-x86_64-10_14" "/Applications/Emacs.app/Contents/MacOS/libexec-x86_64-10_14" "/Applications/Emacs.app/Contents/MacOS/libexec" "/Applications/Emacs.app/Contents/MacOS/bin"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard doom-quit fill-column hydra hl-todo modeline nav-flash ophints (popup +all +defaults) tabs treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold (format +onsave) multiple-cursors rotate-text snippets :emacs dired electric vc :tools editorconfig eval :checkers syntax :tools lookup lsp magit pdf :lang coq data emacs-lisp go (haskell +intero) latex lua markdown ocaml (org +export +present +protocol) python racket rust (sh +fish) web :config (default +bindings +smartparens))
  (packages default-text-scale math-symbol-lists "(frame-fns :recipe (:host github :repo \"emacsmirror/frame-fns\"))" "(frame-cmds :recipe (:host github :repo \"emacsmirror/frame-cmds\"))" "(zoom-frm :recipe (:host github :repo \"emacsmirror/zoom-frm\"))" keyfreq)
  (elpa "n/a")
  (unpin "n/a")))

</pre></details>

**Comment by tchajed** [comment]
I should add that b9f90b3a1 doesn't have the bug while 44fb8ab5944d does.

**Comment by hlissner** [comment]
This is a known and elusive issue with centaur-tabs-mode (in the :ui tabs module) -- seems you've already realized this. It appears to send window focus hooks into a tailspin and I'm not entirely sure how.

As of ad8c685 I've bumped centaur-tabs to its latest version, which may address it. Let me know if it does.

**Comment by hlissner** [comment]
As of eb69073 the performance of centaur-tabs-mode should be much better, which should resolve this issue. Let me know if that isn't the case and I'll reopen the issue. Thanks for bringing it to my attention!
