### ISSUE TITLE
Orgmode issues with calendar and `+popup-mode`

### ISSUE THREAD

**Issue by CGenie** [hlissner/doom-emacs#2438]
**What did you expect to happen?**

I use org mode schedule functionality (`SPC m s`). Usually this opened up a popup with calendar picker. However I've recently changed my configs a bit and now the whole org file gets overwritten with the calendar. So apparently for some reason the popup doesn't open in new buffer. Disabling `+popup-mode` solves the issue.

Now, I'm not sure this is a bug in emacs doom or something with my config. I didn't do any `popup` modifications. Would you have some hint on what is wrong here? It's bit tricky to debug because there is no apparent error thrown.

I'm using the recent `develop` branch.

**Comment by hlissner** [comment]
Sorry for the late response. Are you able to reproduce this [in vanilla Doom](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#testing-in-dooms-sandbox) (on `C-c C-p`)? I can't reproduce this in vanilla or full Doom, with or without +popup-mode, so I suspect it's a configuration issue. 

Could you also supply your `M-x doom/info` and a link to your private config?

**Comment by bdarcus** [comment]
I seem to have come across the same problem, which happens when I use golden-ratio, per your recommendation in #2225, and goes away when I remove it.

**Comment by CGenie** [comment]
Indeed! When I turn off the `golden-ratio` package, popups work fine. Wouldn't have guessed this without your help @bdarcus .

**Comment by bdarcus** [comment]
I do wonder where the problem is though. A bug in golden-ratio? A config
limitation in the doom integration? Something else?

**Comment by hlissner** [comment]
This may simply be an incompatibility between the two. Both golden-ratio and the popup manager are trying to manage windows. I'm a bit swamped at the moment, but I'll look into it as soon as I can.

**Comment by anihm136** [comment]
Just a thought, would it be easy to disable `golden-ratio-mode` for popups only?
