### ISSUE TITLE
Fatal error 6: Aborted

### ISSUE THREAD

**Issue by dougcoates** [hlissner/doom-emacs#244]
When I start doom-emacs I see a blue screen appear temporarily before emacs crashes and I receive the following error

```
Fatal error 6: Aborted
Backtrace:
emacs[0x50907f]
emacs[0x4eefbc]
emacs[0x509134]
emacs[0x444641]
emacs[0x444aae]
emacs[0x445d91]
emacs[0x445d91]
emacs[0x444cd1]
emacs[0x446e7e]
emacs[0x4470be]
emacs[0x45fffa]
emacs[0x463b3b]
emacs[0x562acf]
emacs[0x42e5d6]
emacs[0x450d89]
emacs[0x4fe881]
emacs[0x562a43]
emacs[0x4ef3e5]
emacs[0x5629c2]
emacs[0x4ef37d]
emacs[0x4f3d6c]
emacs[0x4f409c]
emacs[0x4148b9]
/usr/lib/libc.so.6(__libc_start_main+0xea)[0x7f344a797f6a]
```
My installation method was as follows:
 1. clone this repo, copy it to `~/.emacs.d`
 2. copy `init.example.el` to `init.el`, comment out some things
 3. copy `modules/private/hissiner` to `modules/private/my_username`
 4. make install 

I am running Arch Linux and everything is up to date as of today. The tests `make tests` all pass and doom-doctor reports no errors (apart from warnings about missing fonts).

Running emacs with `emacs -Q` launches as expected as does reverting to my previous emacs configuration.

**Comment by dougcoates** [comment]
I have found that changing the default fonts fixes this issue. 

Editing `modules/ui/doom/config.el` 
and changing the lines
```
(set! :font "Fira Mono" :size 12)
(set! :big-font "Fira Mono" :size 18)
(set! :variable-font "Fira Sans" :size 12)
(set! :unicode-font "DejaVu Sans Mono" :size 12)
```
to 
```
(set! :font "Ubuntu Mono" :size 15)
(set! :big-font "Ubuntu Mono" :size 18)
(set! :variable-font "DajaVu Sans" :size 15)
(set! :unicode-font "DejaVu Sans Mono" :size 15)
```
fixes the problem.

**Comment by hlissner** [comment]
Thanks for figuring this out! It seems my default fonts have caused a couple users some trouble, so I think I'll remove them from ui/doom and leave it to the user to set. I'll have this up in `develop` soon.

**Comment by hlissner** [comment]
This is now in master.
