### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by ryanpcmcquen** [hlissner/doom-emacs#2443]
Than you for doom-emacs! I see the project is still very active but there has not been a release for a few years ... are you still doing releases?

**Comment by WhatDothLife** [comment]
>  there has not been a release for a few years

What do you mean by "release"? Are you referring to the [Development Roadmap](https://github.com/hlissner/doom-emacs/projects/3)?

**Comment by ryanpcmcquen** [comment]
No, a GitHub release (tag):
https://github.com/hlissner/doom-emacs/releases

**Comment by hlissner** [comment]
I plan to make a release soon and return Doom to a sane release cycle, but there are some important things that need doing first. Not least of which is fix the doctor, tests+CI, and make the package manager (`bin/doom`) more reliable (and atomic). It will likely be another couple of weeks before I get there.

**Comment by ryanpcmcquen** [comment]
@hlissner, thank you for all you do!
