### ISSUE TITLE
undo-tree reports arrayp error

### ISSUE THREAD

**Issue by chengyi** [hlissner/doom-emacs#2444]
**What did you expect to happen?**
undo-tree work normal

**What actually happened?**
reports (wrong-type-argument arrayp 0)

**Additional details:**
- press `C-x u`

<details><pre>
Debugger entered--Lisp error: (wrong-type-argument arrayp 0)
  undo-tree-node-compute-widths([[nil (#1) nil nil (24111 56310 278422 589000) 0 nil] nil ((#("\n" 0 1 (fontified nil)) . 56) (undo-tree-id6 . -1) (undo-tree-id7 . -1) (undo-tree-id8 . -1) (undo-tree-id9 . -1) (undo-tree-id10 . -1) (undo-tree-id11 . -1) (undo-tree-id12 . -1) (nil ws-butler-chg nil 57 . 58) (t 24111 55479 57374 440000)) ((nil ws-butler-chg delete 57 . 58) (56 . 57)) (24111 56310 278416 463000) 0 nil])
  undo-tree-compute-widths([nil ([#1 nil ((#("\n" 0 1 (fontified nil)) . 56) (undo-tree-id6 . -1) (undo-tree-id7 . -1) (undo-tree-id8 . -1) (undo-tree-id9 . -1) (undo-tree-id10 . -1) (undo-tree-id11 . -1) (undo-tree-id12 . -1) (nil ws-butler-chg nil 57 . 58) (t 24111 55479 57374 440000)) ((nil ws-butler-chg delete 57 . 58) (56 . 57)) (24111 56310 278416 463000) 0 nil]) nil nil (24111 56310 278422 589000) 0 nil])
  undo-tree-draw-tree(#s(undo-tree :root [nil ([#2 nil ((#("\n" 0 1 (fontified nil)) . 56) (undo-tree-id6 . -1) (undo-tree-id7 . -1) (undo-tree-id8 . -1) (undo-tree-id9 . -1) (undo-tree-id10 . -1) (undo-tree-id11 . -1) (undo-tree-id12 . -1) (nil ws-butler-chg nil 57 . 58) (t 24111 55479 57374 440000)) ((nil ws-butler-chg delete 57 . 58) (56 . 57)) (24111 56310 278416 463000) 0 nil]) nil nil (24111 56310 278422 589000) 0 nil] :current [[nil (#2) nil nil (24111 56310 278422 589000) 0 nil] nil ((#("\n" 0 1 (fontified nil)) . 56) (undo-tree-id6 . -1) (undo-tree-id7 . -1) (undo-tree-id8 . -1) (undo-tree-id9 . -1) (undo-tree-id10 . -1) (undo-tree-id11 . -1) (undo-tree-id12 . -1) (nil ws-butler-chg nil 57 . 58) (t 24111 55479 57374 440000)) ((nil ws-butler-chg delete 57 . 58) (56 . 57)) (24111 56310 278416 463000) 0 nil] :size 97 :count 1 :object-pool #<hash-table eq 13/65 0x17a0795>))
  undo-tree-visualize()
  funcall-interactively(undo-tree-visualize)
  call-interactively(undo-tree-visualize nil nil)
  command-execute(undo-tree-visualize)

</pre></details>

**Steps to reproduce:**
1. edit a file 
2. press `C-x u`

**System information:**
<details><pre>
<details>

```
emacs   version    26.3
        features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2
        build      8月 30, 2019
        buildopts  (--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-modules 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now)
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> upstream, zero/develop 32e42a560 2020-01-28 00:00:33 -0500
        dir        ~/.doom.d/
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /usr/bin/zsh
        uname      Linux 4.19.98-1-MANJARO #1 SMP Thu Jan 23 10:34:28 UTC 2020 x86_64
        path       (~/.local/bin /usr/local/sbin /usr/local/bin /usr/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /usr/lib/emacs/26.3/x86_64-pc-linux-gnu)
config  envfile    nil
        elc-files  0
        modules    (:completion company (ivy +fuzzy) prow-company :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) vc-gutter vi-tilde-fringe window-select workspaces prow-highlight prow-hydra prow-treemacs :editor file-templates fold snippets prow-edit :emacs vc :term vterm :tools eval :checkers syntax :tools (lookup +docsets) lsp magit gtags :lang (cc +lsp) prow-c-c++ emacs-lisp lua (org +dragndrop +ipython +pandoc +present) (python +lsp) (rust +lsp) (sh +zsh) prow-markdown :email mu4e :config (default +bindings +smartparens))
        packages   (cnfonts blog-admin jinja2-mode (mu4e-maildirs-extension :disable t :pin "3ef4c48516") (org-mu4e :disable t) (glsl-mode :disable t :pin "43d906688a") (opencl-mode :disable t :pin "55cb49c824") (disaster :disable t :pin "10a785facc") (cuda-mode :disable t :pin "9ae9eacfdb") (demangle-mode :disable t :pin "06903d731d") (fzf :recipe (:host github :repo "tttuuu888/fzf.el" :branch "work-projectile-compatibility")))
        elpa       (n/a)
        unpin      (n/a)
```
</details>
</pre></details>

**Comment by hlissner** [comment]
As of c801a70 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by chengyi** [comment]
@hlissner it works! thanks:muscle:
