### ISSUE TITLE
[REQUEST] ESLint and tslint on .tsx files

### ISSUE THREAD

**Issue by sei40kr** [hlissner/doom-emacs#2445]
**Describe the feature**
- I want flycheck checkers `javascript-eslint`, `typescript-tslint` in `.tsx` files
    ```emacs-lisp
    (flycheck-add-mode 'javascript-eslint 'web-mode)
    ```
    This breaks `web-mode` opening a `.html` file.
    So I want another major-mode for this such like `typescript-tsx-mode`.
    Spacemacs already has implementation for this.
    - https://github.com/syl20bnr/spacemacs/blob/develop/layers/+lang/typescript/packages.el#L132
    - https://github.com/syl20bnr/spacemacs/blob/develop/layers/+lang/typescript/packages.el#L46

**System information**
<details><pre>
((emacs
  (version . "26.3")
  (features . "NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS LCMS2")
  (build . "Sep 17, 2019")
  (buildopts "--enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-mac/emacs-26.3-z-mac-7.7/share/info/emacs --prefix=/usr/local/Cellar/emacs-mac/emacs-26.3-z-mac-7.7 --with-mac --enable-mac-app=/usr/local/Cellar/emacs-mac/emacs-26.3-z-mac-7.7 --with-gnutls --with-modules")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, upstream/develop, upstream/HEAD, origin/develop 471be76ba 2020-01-27 02:05:14 -0500")
  (dir . "~/.doom.d/"))
 (system
  (type . darwin)
  (config . "x86_64-apple-darwin18.7.0")
  (shell . "/usr/local/bin/zsh")
  (uname . "Darwin 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64")
  (path "~/.zinit/plugins/starship---starship" "~/.zinit/plugins/julienXX---terminal-notifier" "~/.zinit/plugins/direnv---direnv" "~/.nvm/versions/node/v10.16.3/bin" "~/.rbenv/shims" "~/.pyenv/shims" "~/.goenv/shims" "~/.zinit/polaris/bin" "~/.local/bin" "~/.yarn/bin" "~/.gem/ruby/2.6.0/bin" "~/.rbenv/bin" "~/.pyenv/bin" "~/.poetry/bin" "~/perl5/bin" "~/perl5/perlbrew/bin" "~/.goenv/bin" "~/go/system/bin" "~/.cargo/bin" "/usr/local/bin" "/usr/local/sbin" "/usr/bin" "/bin" "/usr/sbin" "/sbin" "/Library/TeX/texbin" "/usr/local/Cellar/emacs-mac/emacs-26.3-z-mac-7.7/libexec/emacs/26.3/x86_64-apple-darwin18.7.0"))
 (config
  (envfile . envvar-file)
  (elc-files . 1)
  (modules :completion company helm :ui doom doom-dashboard fill-column hl-todo hydra indent-guides modeline nav-flash ophints (popup +all +defaults) tabs treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold (format +onsave) multiple-cursors snippets word-wrap :emacs (dired +icons) vc :term term :checkers syntax :tools ansible debugger docker editorconfig ein eval (lookup +docsets) lsp magit make rgb tmux :lang assembly (cc +lsp) data emacs-lisp ess (go +lsp) (haskell +lsp) (java +lsp) (javascript +lsp) (kotlin +lsp) (markdown +grip) (org +dragndrop +gnuplot +jupyter) perl (php +lsp) plantuml (python +lsp +pyenv) rest (ruby +lsp +rbenv) (rust +lsp) (scala +lsp) (sh +lsp) solidity (web +css +html +lsp) :config (default +bindings +smartparens))
  (packages "n/a")
  (elpa "n/a")
  (unpin "n/a")))
</pre></details>

**Comment by ckruse** [comment]
This is the reason why I added a `(add-to-list 'auto-mode-alist '("\\.tsx\\'" . typescript-mode))` to my `.doom/config.el`.

**Comment by hlissner** [comment]
I'll take inspiration from spacemacs' solution and look into improving web-mode and tsx integration. I'm currently swamped with other work however, so it may be a while until I get to this. PRs are welcome!

**Comment by sei40kr** [comment]
I'm closing this.
https://github.com/hlissner/doom-emacs/pull/3258
