### ISSUE TITLE
evil-yank-line doesn't behavior correctly inside doom's magit

### ISSUE THREAD

**Issue by akikaede6** [hlissner/doom-emacs#2446]
**What did you expect to happen?**
evil-yank-line should yank whole line in `Magit mode` in non-first character row, which isn't correctly inside doom. 

**What actually happened?**
<kbd>yy</kbd>will truncate contexts before cursor in non-first character row .

**What i did**
Verify: 
M-x: doom-sandbox
;; - vanilla Emacs (nothing loaded)         C-c C-c
jump to ~/.emacs.d
M-x magit-status
M-x evil mode
come to non-first character row then evil-yank-line(aka, <kbd>yy</kbd>), paste the contexts in clipyboard to somewhere else, terminal for example.

<kbd>yy</kbd> yank nomarlly in magit.
 
;; - Doom + modules - your private config   C-c C-p
jump to ~/.emacs.d
M-x magit-status
come to non-first character row then evil-yank-line(aka, <kbd>yy</kbd>), paste the contexts in clipyboard to somewhere else, terminal for example.

<kbd>yy</kbd> just yank context after cursor.

**Additional details:**
- Include a link to your private config
it doesn't relate to this issue. 

**How to reproduce:**
evil-yank-line can't yank the whole line in doom's Magit-mode in non-first character row.

**System information:**
<details><pre>

```
emacs   version    26.3
        features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2
        build      8月 30, 2019
        buildopts  (--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-modules 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now)
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop, origin/develop, origin/HEAD 87b33c416 2020-01-24 19:44:53 -0500
        dir        ~/.doom.d/
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/xonsh
        uname      Linux 5.3.18-1-MANJARO #1 SMP PREEMPT Wed Dec 18 18:34:35 UTC 2019 x86_64
        path       (~/.cargo/bin ~/.local/bin /usr/local/bin /usr/bin /bin /usr/local/sbin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /var/lib/snapd/snap/bin /usr/lib/emacs/26.3/x86_64-pc-linux-gnu/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold multiple-cursors rotate-text snippets :emacs dired electric ibuffer vc :checkers syntax :tools (eval +overlay) (lookup +docsets) magit :lang data emacs-lisp markdown (org +dragndrop +present) sh :config (default +bindings +smartparens))
        packages   (n/a)
        elpa       (n/a)
```
</pre></details>

**Comment by hlissner** [comment]
Sorry for the late response! This appears to be a bug upstream, in [evil-magit](https://github.com/emacs-evil/evil-magit) which binds `yy` to `evil-yank-line`. This command is what `Y` is bound to in normal mode and it respects `evil-want-Y-yank-to-eol`, which is set to `t` by default (the default behavior in vim).

Please report the issue upstream.

In the meantime, this should work around the issue:

```elisp
(after! evil-magit
  (evil-define-operator evil-magit-yank (beg end type register)
    :motion evil-line-or-visual-line
    :move-point nil
    (interactive "<R><x>")
    (evil-yank beg end type register))
  (evil-magit-define-key 'normal 'magit-mode-map "yy" #'evil-magit-yank))
```

**Comment by hlissner** [comment]
In 2f696ff I've pushed the workaround to Doom's `:tools magit` module. I'll still keep this issue open until it is dealt with upstream.

Thanks for letting me know!

**Comment by akikaede6** [comment]
Sorry for my late reply!  I broke my PC couple days ago, and submit the issue to magit just now, thank you for your workaround!

**Comment by akikaede6** [comment]
It seems to be fixed by justbur, maybe you can remove this workaround.
This is the link:
https://github.com/emacs-evil/evil-magit/issues/80

**Comment by hlissner** [comment]
And done. Thanks for letting me know!
