### ISSUE TITLE
Using Doom inside Windows Terminal hosting Ubuntu - Fonts

### ISSUE THREAD

**Issue by johnmcdowall** [hlissner/doom-emacs#2449]
**What are you trying to achieve?**
I'm not able to get the font icons working, most likely because the Doom package installs a bunch of fonts inside the Ubuntu host that isn't actually on the Windows 10 machine. That said I do have a patched Nerdfont installed on the machine, which Vim is able to use for graphical icons. 

**What have you tried?**
- Running `M-x all-the-icons-install-fonts`. 
- Tweaking the `doom-font` to say "DelugiaCode NF" which is the system installed patched Nerdfont. 

**Additional information**
This is what I see when I startup Doom: 
![image](https://user-images.githubusercontent.com/237175/73313662-abdba600-41e0-11ea-9e81-b278c96011df.png)

**System information**
<details><pre>
((emacs
  (version . "26.3")
  (features . "XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD LCMS2")
  (build . "Sep 16, 2019")
  (buildopts "--build=x86_64-linux-gnu --prefix=/usr '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' --sysconfdir=/etc --localstatedir=/var --disable-silent-rules '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' --disable-maintainer-mode --disable-dependency-tracking --prefix=/usr --sharedstatedir=/var/lib --program-suffix=26 --with-modules --with-file-notification=inotify --with-mailutils --with-x=yes --with-x-toolkit=gtk3 --with-xwidgets --with-lcms2 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/emacs26-TP6iDo/emacs26-26.3~1.git96dd019=. -fstack-protector-strong -Wformat -Werror=format-security -no-pie' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro -no-pie'")
  (windowsys . batch)
  (daemonp))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD c6518498b 2020-01-28 14:07:08 -0500")
  (dir . "~/.doom.d/"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/bin/bash")
  (uname . "Linux 4.19.84-microsoft-standard #1 SMP Wed Nov 13 11:44:37 UTC 2019 x86_64")
  (path ".git/safe/../../bin" "~/.asdf/shims" "~/.asdf/bin" "~/.bin" "/usr/local/sbin" "/usr/local/bin" "/usr/sbin" "/usr/bin" "/sbin" "/bin" "/usr/games" "/usr/local/games" "/mnt/c/Python38/Scripts/" "/mnt/c/Python38/" "/mnt/c/WINDOWS/system32" "/mnt/c/WINDOWS" "/mnt/c/WINDOWS/System32/Wbem" "/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/" "/mnt/c/WINDOWS/System32/OpenSSH/" "/mnt/c/ProgramData/chocolatey/bin" "/mnt/c/Program Files/Docker/Docker/resources/bin" "/mnt/c/ProgramData/DockerDesktop/version-bin" "/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL" "/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/DAL" "/mnt/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR" "/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common" "/mnt/c/Users/John McDowall/AppData/Local/Microsoft/WindowsApps" "/mnt/c/Users/John McDowall/AppData/Local/hyper/app-3.0.2/resources/bin" "/mnt/c/Users/John McDowall/AppData/Local/Programs/Microsoft VS Code/bin" "/mnt/c/Users/John McDowall/AppData/Local/Keybase/" "/snap/bin" "~/.fzf/bin" "/usr/lib/x86_64-linux-gnu/emacs/26.3/x86_64-linux-gnu"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold multiple-cursors rotate-text snippets :emacs dired electric ibuffer vc :checkers syntax :tools (eval +overlay) (lookup +docsets) magit :lang data emacs-lisp markdown (org +dragndrop +present) sh :config (default +bindings +smartparens))
  (packages "n/a")
  (elpa "n/a")
  (unpin "n/a")))

Thanks for all of your hard work on `doom-emacs`! 
</pre></details>

**Comment by ekollof** [comment]
Inside the WSL terminal (in -nw mode), you don't have access to the Ubuntu system fonts. So you would have to run an Xorg server on your Windows machine for that, and run emacs inside X on WSL.

**Comment by hlissner** [comment]
From your screenshot, it appears Doom thinks you're in a terminal, not in GUI Emacs. `all-the-icons` icon fonts do not work in terminal emacs (as tty Emacs is incapable of rendering multiple fonts).

**Comment by johnmcdowall** [comment]
@ekollof @hlissner Thanks so much for your time on this. I am a long time Vim user trying to make the switch to Emacs so I still have a lot of learning to do. 

I guess what I don't understand, coming from Vim where you can count on it using the terminal specified font (which in my case is a Nerdfont patched font, so it has almost every icon in existence in it), everything just...works: 

![image](https://user-images.githubusercontent.com/237175/73598276-0c255d00-44eb-11ea-82eb-29358427aef1.png)

Is there no way to have Doom / Emacs use the default terminal font for icons?

With the XServer approach, I tried using MobaXTerm and had strange results. Doom appeared to work (in the sense that I could hit SPC and popups would appear), but the theme wasn't applied:

![image](https://user-images.githubusercontent.com/237175/73598300-68887c80-44eb-11ea-827d-692bc0519931.png)

Again, thank you for your patience in helping me clear up any complete beginner mistakes / misunderstandings!

**Comment by johnmcdowall** [comment]
Oh I've also tried:

```
(setq doom-font (font-spec :family "DelugiaCode NF" :size 14))
```

In the `.doom.d/config.el` file.

Thanks!

**Comment by johnmcdowall** [comment]
Ok, so icons ARE working now that I've enabled neotree and open it up...

But still no theme or dashboard on first loading.

**Comment by johnmcdowall** [comment]
Ok! 

So I figured out how to evaluate expressions when Emacs is running, and I am able to load a theme by evaluating `(load-theme 'doom-nord t)`:

![image](https://user-images.githubusercontent.com/237175/73600211-d6d83980-4501-11ea-9da4-6ef44b31a445.png)

So not sure why the theme settings in `.doom.d/config.el` are not being respected, or the `doom-dashboard` loading on boot (still getting a scratch buffer), but I know that file is being processed because Emacs is respecting disabling the menu and tool bar.

**Comment by johnmcdowall** [comment]
@hlissner The only two definite issues I have remaining are that when starting the Emacs UI using an Xserver, the theme has to be manually applied, and the doom-dashboard does not load. Otherwise everything else works. I've reached the limits of my Elisp debugging skills :)

Do you want me to create two new separate issues for those?

**Comment by ekollof** [comment]
Remember that fonts installed in Windows do not translate over to Xorg directly. Those are two seperate subsystems. Back in the old days things could be synced up with a fontserver, but I'm not sure if Xorg supports that anymore.

**Comment by johnmcdowall** [comment]
@ekollof Thanks, I can work with the fonts used as is right now since the icons are loading when Emacs is started in X. 

The remaining issues of the theme not applying automatically and the dashboard not displaying are annoyances. I should break them out into separate issues.

**Comment by hlissner** [comment]
> Do you want me to create two new separate issues for those?

No. It is likely that your issues have the same cause. Typically, if an error occurs during startup, Emacs stops in its tracks, preventing the theme and dashboard from loading.

Are there any warnings or error messages in \*Messages\* after startup? `SPC h e` to open it.

**Comment by johnmcdowall** [comment]
@hlissner Thanks for that tip! I was able to see there was an error about how I had set the font family to `monospaced` instead of `monospace`. Fixing that, everything works!
