### ISSUE TITLE
Open terminal in root of project, not the buffer

### ISSUE THREAD

**Issue by rohitpaulk** [hlissner/doom-emacs#2455]
**Describe the feature**

 By default, `SPC o t` (open terminal popup) and `SPC o T` (replace window with terminal) invoke the terminal in the directory of the current buffer's file. 

So if I have a file `projecta/models/user.py` open, `SPC o t` will invoke the terminal with `projecta/models` as the working directory.

Most commands I want to run assume the project root as the working directory though. Examples: Make, docker-compose, git, build tooling. I almost always find myself `cd ..`ing until I reach the project root. Not sure if this is just me.

Would it better if the default was to open the terminal in the project root? Happy to send across a PR if so, feel free to close if not :+1: 

**System information**

<details>

```
emacs   version    26.3
        features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2
        build      Aug 30, 2019
        buildopts  (--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-modules 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now)
        windowsys  x
        daemonp    daemon
doom    version    2.0.9
        build      HEAD -> develop b5a279311 2020-01-07 00:14:46 -0500
        dir        ~/.dotfiles/doom-emacs/dir/
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /usr/bin/zsh
        uname      Linux 5.4.6-arch3-1 #1 SMP PREEMPT Tue, 24 Dec 2019 04:36:53 +0000 x86_64
        path       (~/.rbenv/shims/ ~/.emacs_distributions/doom-emacs/core/bin/ ~/.autojump/bin/ ~/.rbenv/bin/ ~/.local/bin/ /Users/rohitpaulk/experiments/software/geckodriver/ /usr/local/opt/gettext/bin/ ~/.gem/ruby/2.5.0/bin/ ~/.rbenv/bin/ ~/.local/bin/ /Users/rohitpaulk/experiments/software/geckodriver/ /usr/local/opt/gettext/bin/ ~/.gem/ruby/2.5.0/bin/ ~/.rbenv/shims/ ~/.emacs_distributions/doom-emacs/core/bin/ ~/.autojump/bin/ ~/.rbenv/bin/ ~/.local/bin/ /Users/rohitpaulk/experiments/software/geckodriver/ /usr/local/opt/gettext/bin/ ~/.gem/ruby/2.5.0/bin/ /usr/local/sbin/ /usr/local/bin/ /usr/bin/ ~/go/bin/ /usr/lib/jvm/default/bin/ /usr/bin/site_perl/ /usr/bin/vendor_perl/ /usr/bin/core_perl/ /usr/local/bin/ ~/go/bin/ ~/go/bin/ /usr/lib/jvm/default/bin/ /usr/bin/site_perl/ /usr/bin/vendor_perl/ /usr/bin/core_perl/ /usr/local/bin/ /usr/lib/emacs/26.3/x86_64-pc-linux-gnu/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company (ivy +fuzzy) :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold (format +onsave) multiple-cursors rotate-text snippets :emacs dired electric ibuffer vc :term term :tools debugger docker (eval +overlay) flycheck (lookup +docsets) lsp magit make terraform :lang data emacs-lisp (go +lsp) markdown (org +dragndrop +ipython +pandoc +present) (python +lsp) ruby sh (web +html) :config (default +bindings +smartparens))
        packages   ((rubocop :disable t))
        elpa       (n/a)
```
</details>

**Comment by ocharles** [comment]
I agree that project root is a better default, and usually what I'm expecting.

**Comment by danielstaleiny** [comment]
Maybe we can helper function to do this and be able to remap keys to suit everybody`s needs ? I can find myself using both, depending on what I want at the time.

**Comment by hlissner** [comment]
Considering there are tools that needs to be run on files in the current file (like some builders/transpilers; e.g. make, scss, etc), I'm not sure either is a better default. In any case, the terms define a `PROOT` envvar upon opening the popup. You could also do `cd $PROOT` to cd to the project's root. I could reverse this behavior and define a `CWD` for the current directory instead and start the term in the project root.

**Comment by bersace** [comment]
Just an idea : What if `SPC o T` opens term in project root while lowercase `SPC o t` in buffer directory ?

**Comment by randomizedthinking** [comment]
Another idea. Let the keybinding takes a universal argument, when `C-u` is pressed, open the term under the project root, otherwise the buffer directory.

If you think it is good, I can create a PR.

**Comment by bram209** [comment]
Any update on this?

**Comment by bersace** [comment]
Sadly, `SPC p t` and `SPC p T` are mapped to task and tests. That would have make sens to add terminal in project root shortcut to project namespace.

**Comment by bersace** [comment]
@randomizedthinking interesting. I'm not aware of the meaning of C-u. For me it means *repeat*. What is the full keystroke ? `SPC o C-u t` ?

**Comment by clayliddell** [comment]
As a temporary work around I added `cd ${PROOT:-~}` to my `~/.zshrc` file so that if a project root has been set, zsh will automatically `cd` into that directory. This should work with bash as well.

**Comment by bersace** [comment]
Running bf8495b4122 here with vterm. I don't have `PROOT` defined but `SPC o t` opens in project root. :suspect:
