### ISSUE TITLE
error in process sentinel: Wrong number of arguments: ((t) (buffer event) (if buffer (kill-buffer buffer))), 1 when typing 'exit' in vterm

### ISSUE THREAD

**Issue by ocharles** [hlissner/doom-emacs#2456]
**What did you expect to happen?**

My `vterm` terminal to be closed, and possibly the buffer to be killed.

**What actually happened?**

```
error in process sentinel: Wrong number of arguments: ((t) (buffer event) (if buffer (kill-buffer buffer))), 1
```

**Additional details:**

<details><pre>
Debugger entered--Lisp error: (wrong-number-of-arguments ((t) (buffer event) (if buffer (kill-buffer buffer))) 1)
  +vterm-kill-buffer-on-quit-fn(#<buffer vterm>)
  run-hook-with-args(+vterm-kill-buffer-on-quit-fn #<buffer vterm>)
  (let ((buf (process-buffer process))) (run-hook-with-args (quote vterm-exit-functions) (if (buffer-live-p buf) buf nil)))
  vterm--sentinel(#<process vterm> "finished\n")
</pre></details>

**Steps to reproduce:**

1. Enable the `vterm` module
2. Hit `SPC o T`
3. Type `exit` and hit return
4. Observe the error

**System information:**
<details><pre>
<details>

```
emacs   version    26.3
        features   XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD
        build      Jan 30, 2020
        buildopts  (--prefix=/nix/store/bqvfhil4b775r16hf7bp2pzb4wzhy4bi-emacs-26.3 --disable-build-details --with-modules --with-x-toolkit=gtk3 --with-xft CFLAGS=-DMAC_OS_X_VERSION_MAX_ALLOWED=101200)
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop c801a70ec 2020-01-29 16:37:05 -0500
        dir        ~/work/dotcharles/doom.d/
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /nix/store/11rg794bcdqic27z3pgqfxlzqsrs51dy-zsh-5.7.1/bin/zsh
        uname      Linux 4.19.91 #1-NixOS SMP Sat Dec 21 09:57:45 UTC 2019 x86_64
        path       (/nix/store/2xwxj5qrrc71asdk1wyq19nz9k845pzs-patchelf-0.9/bin/ /nix/store/291ldi6fqsbmkbvbs8is4mcg3jb64ld4-gcc-wrapper-8.3.0/bin/ /nix/store/62x7m20m7lm8y8s17cbgha0sf3cmma19-gcc-8.3.0/bin/ /nix/store/hblpx8x5w88igmwa4ydnsnb65s363lji-glibc-2.27-bin/bin/ /nix/store/9v78r3afqy9xn9zwdj9wfys6sk3vc01d-coreutils-8.31/bin/ /nix/store/gwwycf3w6cbj0gd2mpgblrdjc24f3cys-binutils-wrapper-2.31.1/bin/ /nix/store/ajrrkivdfvp8dp4vdg5hp1h5hblmanc9-binutils-2.31.1/bin/ /nix/store/hblpx8x5w88igmwa4ydnsnb65s363lji-glibc-2.27-bin/bin/ /nix/store/9v78r3afqy9xn9zwdj9wfys6sk3vc01d-coreutils-8.31/bin/ /nix/store/021yihqyplja8w3mb0xwl13gpz6x83ar-ghc-8.8.1-with-packages/bin/ ...)
config  envfile    nil
        elc-files  0
        modules    (:completion (company +childframe) (ivy +icons +prescient) :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ...)
        packages   ((magit-todos :disable t))
        elpa       (n/a)
        unpin      (n/a)
```
</details>
</pre></details>

**Comment by hlissner** [comment]
Are you sure vterm is up-to-date? Run `doom update` to make sure. `vterm-exit-functions` take two arguments; `+vterm-kill-buffer-on-quit-fn`'s signature is correct, and I've confirmed this is the case in the [version of vterm we use](https://github.com/akermu/emacs-libvterm/blob/master/vterm.el#L627-L629) it is correct.

Side-note, did you truncate your module list in your `doom/info`? I see a `...` at the end of it and a lot of modules missing?

**Comment by ocharles** [comment]
I didn't truncate anything purpose, not sure what happened there. I'll double check vterm, but it's built via NixOS which I wonder is part of the problem

**Comment by hlissner** [comment]
> built via NixOS
So is likely the issue. Doom expects a particular version (https://github.com/akermu/emacs-libvterm/commit/a65f1a84ab8a72c66ca92f895c1f355c44a5e0a2, to be exact), which is likely much newer than what's available on nixos.

A simple workaround for this is to pin the vterm package to the commit that nix uses, which, if my rudimentary scan of the nixpkgs repo was correct, should be https://github.com/akermu/emacs-libvterm/commit/58b4cc40ee9872a08fc5cbfee78ad0e195a3306c: e.g.

```elisp
;; Add to ~/.doom.d/packages.el
(package! vterm :pin "58b4cc4")
```

Then run `doom update`.

**Comment by hlissner** [comment]
Oh wait, pinning it won't help because Doom doesn't bother to install the vterm package if it is already pre-installed on the system. Hmm, not sure what to do about this.

**Comment by ocharles** [comment]
One fix is to do this:

```
nix-build -E 'with import <nixpkgs> {}; ((emacsPackagesNgGen emacs).emacsWithPackages (epkgs: [                                                                                       ~
    (epkgs.emacs-libvterm.overrideAttrs (old: { src = builtins.fetchGit https://github.com/akermu/emacs-libvterm; }))
  ]))'
```

That installs Emacs with the latest commit of https://github.com/akermu/emacs-libvterm

**Comment by hlissner** [comment]
5b242c73b should indirectly and temporarily resolve this -- your workaround is also a viable alterantive -- so I'll consider this resolved. Let me know if that isn't the case and I'll reopen this. Thanks for bringing it to my attention!

**Comment by ocharles** [comment]
LGTM, thanks!
