### ISSUE TITLE
Add +posframe to flycheck

### ISSUE THREAD

**Issue by ocharles** [hlissner/doom-emacs#2458]
**Describe the feature**

https://github.com/alexmurray/flycheck-posframe works really nicely for me in Haskell editing with `lsp-mode`. I don't like `lsp-ui-sideline-mode`, but just disabling that leaves me with:

![image](https://user-images.githubusercontent.com/20878/73453674-6f38b780-4364-11ea-9190-18719d840be0.png)

However, if I enable `flycheck-posframe` (I literally just did `M-x package-install flycheck-posframe` and then `M-x flycheck-posframe-mode`) I get this much nicer display:

![image](https://user-images.githubusercontent.com/20878/73453729-8aa3c280-4364-11ea-86a0-58f91d61b3ff.png)

I think this works much better.

**Comment by hlissner** [comment]
The `:tools flycheck` (now `:checkers syntax`) module has always supported the `+childframe` flag, like helm, ivy, and company do. I realize it's not documented. Will correct that shortly.

**Comment by ocharles** [comment]
Yay! Works for me, thanks!
