### ISSUE TITLE
(M-x term)'s colors

### ISSUE THREAD

**Issue by rotsix** [hlissner/doom-emacs#246]
Hi!

As images says more than texts, [here](https://ptpb.pw/pDWU.png) is the issue.
 
As you can see, the term isn't well colored. It comes from the theme that doesn't set the colors well.
(different background when *texted* or not)

If you want, i can edit it and make a pull request!

Thanks :)

**Comment by hlissner** [comment]
Good catch. This is actually a [doom-themes](https://github.com/hlissner/emacs-doom-themes) issue, and it should be fixed as of https://github.com/hlissner/emacs-doom-themes/commit/d91f72b83ec22f1620372574582e163f921e6796. Feel free to reopen this if that isn't the case.

**Comment by rotsix** [comment]
That's working, well played, thanks!
