### ISSUE TITLE
Add +lsp to :lang elm

### ISSUE THREAD

**Issue by ocharles** [hlissner/doom-emacs#2460]
**Describe the feature**

Elm has the https://github.com/elm-tooling/elm-language-server project, which works nicely with `lsp-mode`. Once that server is installed, all one has to do is type `M-x lsp` in an Elm file and everything just works. I propose adding `+lsp` to `:lang elm` that would add `lsp` as a hook for `elm-mode`.

**Comment by hlissner** [comment]
Should `flycheck-elm` be disabled too, in the presence of `+lsp`? Or does it play nicely with the LSP server?

**Comment by ocharles** [comment]
Thank you! I'll report back on `flycheck-elm` if it causes problems.
