### ISSUE TITLE
Add better support do Rails

### ISSUE THREAD

**Issue by otavioschwanck** [hlissner/doom-emacs#2461]
I'm a pure emacs user and i really miss some plugins:

- projectile-rails (https://github.com/asok/projectile-rails)
- rspec-mode (https://github.com/pezra/rspec-mode)
- Robe (https://github.com/dgutov/robe)

Projectile-rails is excelent for navigation and file creation.  Can navigate between test \ real file, search for models (C-c r m), controllers (C-c r c), etc.  its super complete and make all diffrence.
Rspec-mode is good to run tests.
Robe for auto-complation.

Maybe we need a Rails layer.  Its to hard to implement ?  If not, i can contribute.

**Comment by hlissner** [comment]
> I'm a pure emacs user and I really miss some plugins

I don't understand. So you don't use Doom, but you want those plugins? Or you use Doom and you want those plugins?

If the former, how is this relevant to Doom?

If the latter, Doom's `:lang ruby` module already provides robe and rspec-mode, but not rails.

> Maybe we need a Rails layer. Its to hard to implement ? If not, i can contribute.

I'd welcome rails support so long as it's lazy loaded. Go ahead and add it to the `:lang ruby` module under the `+rails` flag.

**Comment by alexandergraul** [comment]
There is also this issue open for projectile-rails support: https://github.com/hlissner/doom-emacs/issues/2275
