### ISSUE TITLE
Can we add an option to opt out of `which-key-mode`?

### ISSUE THREAD

**Issue by declanqian** [hlissner/doom-emacs#2464]
I loved the way doom install/upgrade packages. So I used it as my
Emacs package manager. And migrated all lisp config to `.doom.d` folder.

Personal I don't use `which-key-mode` which for sure would be helpful for some users.
Currently I invoke `(which-key-mode -1)` to disable the which key mode.

**Comment by hlissner** [comment]
The package can be disabled by adding `(package! which-key :disable t)` to your private `packages.el`.

**Comment by declanqian** [comment]
Nice. That will do the work. Thanks. Nice project BTW.
