### ISSUE TITLE
eyebrowse mode indicator isn't shown in mode line

### ISSUE THREAD

**Issue by amosbird** [hlissner/doom-emacs#247]
How can I redefine the doom mode line to include the eyebrowse indicator?

**Comment by hlissner** [comment]
You would need to define an `eyebrowse` segment and redefine the main modeline:

```emacs-lisp
(def-modeline-segment! eyebrowse
  (when eyebrowse-mode
    (eyebrowse-mode-line-indicator)))

(def-modeline! main
  (bar eyebrowse matches " " buffer-info "  %l:%c %p  " selection-info)
  (buffer-encoding major-mode vcs flycheck))
```

(I'm not an eyebrowse user, so that segment may need to be tweaked)

**Comment by amosbird** [comment]
Thanks! btw, the `matches` segment doesn't show the match number when highlighting words via `#` or `*` before the first invocation of evil search.

**Comment by amosbird** [comment]
This is fixed by https://github.com/hlissner/doom-emacs/pull/255
