### ISSUE TITLE
ws-butler causes org-latex-preview to fail

### ISSUE THREAD

**Issue by RyanGreenup** [hlissner/doom-emacs#2470]
**What did you expect to happen?**
On a fresh install of Doom Emacs in `org-mode` with the the point on some latex, e.g `$4x^3$`,  `org-latex-preview` fails with the error `Args out of range` rather than generating the inline image.

disabling `ws-butler` with `M-x ws-butler-global-mode Ret` fixes this and allows the LaTeX to generate as expected.

A simple fix is to disable `ws-butler` by default because it's fairly easy to use `delete-trailing-whitespace` manually.

**Additional details:**
- Default config
- All commands included above
- Debug Below:
- This is different from #515
<details><summary>Debug Output</summary><pre>
Debugger entered--Lisp error: (args-out-of-range 199 397)
  put-text-property(199 397 ws-butler-chg chg)
  ws-butler-after-change(199 397 0)
  call-process-region(16849 16849 "/usr/bin/zsh" nil #<buffer *Org Preview LaTeX Output*> nil "-c" "dvipng -D 144.0 -T tight -o /tmp/orgtexSfW6JL.png ...")
  call-shell-region(16849 16849 "dvipng -D 144.0 -T tight -o /tmp/orgtexSfW6JL.png ..." nil #<buffer *Org Preview LaTeX Output*>)
  shell-command-on-region(16849 16849 "dvipng -D 144.0 -T tight -o /tmp/orgtexSfW6JL.png ..." #<buffer *Org Preview LaTeX Output*> nil nil)
  #f(compiled-function (command &optional output-buffer error-buffer) "Execute string COMMAND in inferior shell; display output, if any.\nWith prefix argument, insert the COMMAND's output at point.\n\nInteractively, prompt for COMMAND in the minibuffer.\nIf `shell-command-prompt-show-cwd' is non-nil, show the current\ndirectory in the prompt.\n\nIf COMMAND ends in `&', execute it asynchronously.\nThe output appears in the buffer `*Async Shell Command*'.\nThat buffer is in shell mode.  You can also use\n`async-shell-command' that automatically adds `&'.\n\nOtherwise, COMMAND is executed synchronously.  The output appears in\nthe buffer `*Shell Command Output*'.  If the output is short enough to\ndisplay in the echo area (which is determined by the variables\n`resize-mini-windows' and `max-mini-window-height'), it is shown\nthere, but it is nonetheless available in buffer `*Shell Command\nOutput*' even though that buffer is not automatically displayed.\n\nTo specify a coding system for converting non-ASCII characters\nin the shell command output, use \\[universal-coding-system-argument] before this command.\n\nNoninteractive callers can specify coding systems by binding\n`coding-system-for-read' and `coding-system-for-write'.\n\nThe optional second argument OUTPUT-BUFFER, if non-nil,\nsays to put the output in some other buffer.\nIf OUTPUT-BUFFER is a buffer or buffer name, erase that buffer\nand insert the output there; a non-nil value of\n`shell-command-dont-erase-buffer' prevents the buffer from being\nerased.  If OUTPUT-BUFFER is not a buffer and not nil, insert the\noutput in current buffer after point leaving mark after it.  This\ncannot be done asynchronously.\n\nIf the command terminates without error, but generates output,\nand you did not specify \"insert it in the current buffer\",\nthe output can be displayed in the echo area or in its buffer.\nIf the output is short enough to display in the echo area\n(determined by the variable `max-mini-window-height' if\n`resize-mini-windows' is non-nil), it is shown there.\nOtherwise, the buffer containing the output is displayed.\n\nIf there is output and an error, and you did not specify \"insert it\nin the current buffer\", a message about the error goes at the end\nof the output.\n\nIf the optional third argument ERROR-BUFFER is non-nil, it is a buffer\nor buffer name to which to direct the command's standard error output.\nIf it is nil, error output is mingled with regular output.\nIn an interactive call, the variable `shell-command-default-error-buffer'\nspecifies the value of ERROR-BUFFER.\n\nIn Elisp, you will often be better served by calling `call-process' or\n`start-process' directly, since they offer more control and do not\nimpose the use of a shell (with its need to quote arguments)." (interactive #f(compiled-function () #<bytecode 0x10ffc81691451fb0>)) #<bytecode -0x169365274fe4d316>)("dvipng -D 144.0 -T tight -o /tmp/orgtexSfW6JL.png ..." #<buffer *Org Preview LaTeX Output*> nil)
  shell-command--shell-command-with-editor-mode(#f(compiled-function (command &optional output-buffer error-buffer) "Execute string COMMAND in inferior shell; display output, if any.\nWith prefix argument, insert the COMMAND's output at point.\n\nInteractively, prompt for COMMAND in the minibuffer.\nIf `shell-command-prompt-show-cwd' is non-nil, show the current\ndirectory in the prompt.\n\nIf COMMAND ends in `&', execute it asynchronously.\nThe output appears in the buffer `*Async Shell Command*'.\nThat buffer is in shell mode.  You can also use\n`async-shell-command' that automatically adds `&'.\n\nOtherwise, COMMAND is executed synchronously.  The output appears in\nthe buffer `*Shell Command Output*'.  If the output is short enough to\ndisplay in the echo area (which is determined by the variables\n`resize-mini-windows' and `max-mini-window-height'), it is shown\nthere, but it is nonetheless available in buffer `*Shell Command\nOutput*' even though that buffer is not automatically displayed.\n\nTo specify a coding system for converting non-ASCII characters\nin the shell command output, use \\[universal-coding-system-argument] before this command.\n\nNoninteractive callers can specify coding systems by binding\n`coding-system-for-read' and `coding-system-for-write'.\n\nThe optional second argument OUTPUT-BUFFER, if non-nil,\nsays to put the output in some other buffer.\nIf OUTPUT-BUFFER is a buffer or buffer name, erase that buffer\nand insert the output there; a non-nil value of\n`shell-command-dont-erase-buffer' prevents the buffer from being\nerased.  If OUTPUT-BUFFER is not a buffer and not nil, insert the\noutput in current buffer after point leaving mark after it.  This\ncannot be done asynchronously.\n\nIf the command terminates without error, but generates output,\nand you did not specify \"insert it in the current buffer\",\nthe output can be displayed in the echo area or in its buffer.\nIf the output is short enough to display in the echo area\n(determined by the variable `max-mini-window-height' if\n`resize-mini-windows' is non-nil), it is shown there.\nOtherwise, the buffer containing the output is displayed.\n\nIf there is output and an error, and you did not specify \"insert it\nin the current buffer\", a message about the error goes at the end\nof the output.\n\nIf the optional third argument ERROR-BUFFER is non-nil, it is a buffer\nor buffer name to which to direct the command's standard error output.\nIf it is nil, error output is mingled with regular output.\nIn an interactive call, the variable `shell-command-default-error-buffer'\nspecifies the value of ERROR-BUFFER.\n\nIn Elisp, you will often be better served by calling `call-process' or\n`start-process' directly, since they offer more control and do not\nimpose the use of a shell (with its need to quote arguments)." (interactive #f(compiled-function () #<bytecode 0x10ffc81691451fb0>)) #<bytecode -0x169365274fe4d316>) "dvipng -D 144.0 -T tight -o /tmp/orgtexSfW6JL.png ..." #<buffer *Org Preview LaTeX Output*>)
  apply(shell-command--shell-command-with-editor-mode #f(compiled-function (command &optional output-buffer error-buffer) "Execute string COMMAND in inferior shell; display output, if any.\nWith prefix argument, insert the COMMAND's output at point.\n\nInteractively, prompt for COMMAND in the minibuffer.\nIf `shell-command-prompt-show-cwd' is non-nil, show the current\ndirectory in the prompt.\n\nIf COMMAND ends in `&', execute it asynchronously.\nThe output appears in the buffer `*Async Shell Command*'.\nThat buffer is in shell mode.  You can also use\n`async-shell-command' that automatically adds `&'.\n\nOtherwise, COMMAND is executed synchronously.  The output appears in\nthe buffer `*Shell Command Output*'.  If the output is short enough to\ndisplay in the echo area (which is determined by the variables\n`resize-mini-windows' and `max-mini-window-height'), it is shown\nthere, but it is nonetheless available in buffer `*Shell Command\nOutput*' even though that buffer is not automatically displayed.\n\nTo specify a coding system for converting non-ASCII characters\nin the shell command output, use \\[universal-coding-system-argument] before this command.\n\nNoninteractive callers can specify coding systems by binding\n`coding-system-for-read' and `coding-system-for-write'.\n\nThe optional second argument OUTPUT-BUFFER, if non-nil,\nsays to put the output in some other buffer.\nIf OUTPUT-BUFFER is a buffer or buffer name, erase that buffer\nand insert the output there; a non-nil value of\n`shell-command-dont-erase-buffer' prevents the buffer from being\nerased.  If OUTPUT-BUFFER is not a buffer and not nil, insert the\noutput in current buffer after point leaving mark after it.  This\ncannot be done asynchronously.\n\nIf the command terminates without error, but generates output,\nand you did not specify \"insert it in the current buffer\",\nthe output can be displayed in the echo area or in its buffer.\nIf the output is short enough to display in the echo area\n(determined by the variable `max-mini-window-height' if\n`resize-mini-windows' is non-nil), it is shown there.\nOtherwise, the buffer containing the output is displayed.\n\nIf there is output and an error, and you did not specify \"insert it\nin the current buffer\", a message about the error goes at the end\nof the output.\n\nIf the optional third argument ERROR-BUFFER is non-nil, it is a buffer\nor buffer name to which to direct the command's standard error output.\nIf it is nil, error output is mingled with regular output.\nIn an interactive call, the variable `shell-command-default-error-buffer'\nspecifies the value of ERROR-BUFFER.\n\nIn Elisp, you will often be better served by calling `call-process' or\n`start-process' directly, since they offer more control and do not\nimpose the use of a shell (with its need to quote arguments)." (interactive #f(compiled-function () #<bytecode 0x10ffc81691451fb0>)) #<bytecode -0x169365274fe4d316>) ("dvipng -D 144.0 -T tight -o /tmp/orgtexSfW6JL.png ..." #<buffer *Org Preview LaTeX Output*>))
  shell-command("dvipng -D 144.0 -T tight -o /tmp/orgtexSfW6JL.png ..." #<buffer *Org Preview LaTeX Output*>)
  org-compile-file("/tmp/orgtexSfW6JL.dvi" ("dvipng -D %D -T tight -o %O %f") "png" "Please adjust `dvipng' part of `org-preview-latex-..." #<buffer *Org Preview LaTeX Output*> ((68 . "144.0") (83 . "1.0285714285714285")))
  org-create-formula-image("$\\enspace a \\enspace R \\enspace b$" "/home/ryan/.emacs.d/.local/cache/org-latex/org-ltx..." (:foreground "#bbc2cf" :background "#282c34" :scale 1.5 :html-foreground "Black" :html-background "Transparent" :html-scale 1.0 :matchers ("begin" "$1" "$" "$$" "\\(" "\\[")) forbuffer dvipng)
  org-format-latex("/home/ryan/.emacs.d/.local/cache/org-latex/org-ltx..." 16849 16883 "/home/ryan/Dropbox/Notes/Org/" overlays nil forbuffer dvipng)
  org--latex-preview-region(16849 16883)
  org-latex-preview(nil)
  funcall-interactively(org-latex-preview nil)
  call-interactively(org-latex-preview nil nil)
  command-execute(org-latex-preview)
</pre></details>

**System information:**
<details><pre>
<details>

```
emacs   version    28.0.50
        features   XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER LCMS2 GMP
        build      Jan 31, 2020
        buildopts  (--prefix= --prefix=/snap/emacs/current/usr --with-xwidgets --with-x-toolkit=gtk3 --without-xaw3d --with-modules --with-cairo 'CFLAGS= -I/build/emacs/parts/emacs/install/usr/include' 'CPPFLAGS= -I/build/emacs/parts/emacs/install/usr/include' 'LDFLAGS= -L/build/emacs/parts/emacs/install/lib -L/build/emacs/parts/emacs/install/usr/lib -L/build/emacs/parts/emacs/install/lib/x86_64-linux-gnu -L/build/emacs/parts/emacs/install/usr/lib/x86_64-linux-gnu')
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop, origin/develop, origin/HEAD 0dc173a63 2020-02-01 02:07:24 -0500
        dir        ~/.doom.d/
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /usr/bin/zsh
        uname      Linux 5.3.0-28-generic #30~18.04.1-Ubuntu SMP Fri Jan 17 06:14:09 UTC 2020 x86_64
        path       (~/.cargo/bin ~/.local/bin ~/bin ~/.nvm/versions/node/v13.6.0/bin /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /usr/games /usr/local/games /snap/bin ~/.fzf/bin /snap/emacs/current/usr/libexec/emacs/28.0.50/x86_64-pc-linux-gnu/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold multiple-cursors rotate-text snippets :emacs dired electric ibuffer vc :checkers syntax :tools (eval +overlay) (lookup +docsets) magit :lang data emacs-lisp markdown (org +dragndrop +present) sh :config (default +bindings +smartparens))
        packages   (n/a)
        elpa       (ws-butler)
        unpin      (n/a)
```
</details>
</pre></details>

**Comment by hlissner** [comment]
I need to know more about what buffer ws-butler is running in. Add this to your config:

```elisp
(defadvice! debug-log (&rest _)
  :before #'ws-butler-after-change
  (message "-- %s %s %s"
           (current-buffer)
           buffer-file-name
           major-mode))
```

Then recreate the error and let me know what it outputs (in your \*Messages\* buffer -- open it with `SPC h e`).

**Comment by RyanGreenup** [comment]
Yeah sure thing, I added that to the config file, recreated the error and then hit `SPC h e` this is what I got:
<details><summary> Debug-log </summary>
<pre>
Doom loaded 185 packages across 34 modules in 1.233s
Package cl is deprecated
Restoring session...
Attempting to load /home/ryan/Dropbox/DotFiles/DoomEmacs/.emacs.d/.local/etc/workspaces/autosave
Loading /home/ryan/Dropbox/DotFiles/DoomEmacs/.emacs.d/.local/cache/recentf...done
Session restored. Welcome back.
--  *Echo Area 0* nil fundamental-mode
Quit
--  *Echo Area 0* nil fundamental-mode [2 times]
Back to top level
--  *Minibuf-1* nil minibuffer-inactive-mode [3 times]
Quit
--  *Minibuf-1* nil minibuffer-inactive-mode [3 times]
Quit
--  *Minibuf-1* nil minibuffer-inactive-mode [35 times]
Mark set
-- AbstractAlgebraNotes.org /home/ryan/Dropbox/Notes/Org/AbstractAlgebraNotes.org org-mode [8 times]
Creating LaTeX preview...
--  *temp* /home/ryan/Dropbox/Notes/Org/AbstractAlgebraNotes.org org-mode [3 times]
-- *Org Preview LaTeX Output* nil compilation-mode [2 times]
Waiting for process to die...done
--  *Echo Area 1* nil fundamental-mode
Args out of range: 144, 287
--  *Echo Area 1* nil fundamental-mode
progn: End of buffer
SPC y is undefined
</pre>
</details>

**Comment by hlissner** [comment]
Odd. I cannot reproduce this locally. I also see `ws-butler` in your ELPA packages. Are you installing it yourself/manually? If the ELPA version is shadowing the one installed by Doom I could see that being the cause.

By default, Doom uses [my personal fork](https://github.com/hlissner/ws-butler) which has a few choice bugfixes.

**Comment by hlissner** [comment]
Another possibility is that I'm on 26.3 and you're on 28. I'll build 28 tomorrow and give it a spin then.

**Comment by RyanGreenup** [comment]
I haven't installed anything manually yet, basically today I decided to switch out of Spacemacs because it was too damn slow (and I'm really glad I did, this is waaaaay faster), I use [`stow`](https://www.gnu.org/software/stow/) so I did something to the effect of:

```bash
cd ~/Dropbox/Dotfiles
stow -D -t $HOME Spacemacs
cd ~
rm -rf .emacs*
git clone https://github.com/hlissner/doom-emacs ~/.emacs.d
~/.emacs.d/bin/doom install
mv ~/.emacs.d  ~/Dropbox/DotFiles/DoomEmacs
stow -s -t $HOME ~/Dropbox/DotFiles/DoomEmacs
```
And when I opened up an org file I couldn't view the LaTeX, disabling `ws-butler` fixes the problem but it took me like an hour to figure out why it wasn't working because I though I'd made some other mistake.

Maybe it's the newer Emacs, I'm running the latest/edge from [Snap](https://snapcraft.io/emacs).

**Comment by uberjay** [comment]
I just recently updated my Emacs (master branch built from source) and am running into a similar issue. I'm using Spacemacs (develop branch).

I bisected the emacs repo and discovered that the issue was introduced by https://github.com/emacs-mirror/emacs/commit/224e8d146485ce178086549d41fa8359dcc0e03e:
```
commit 224e8d146485ce178086549d41fa8359dcc0e03e
Author: Alan Mackenzie <acm@muc.de>
Date:   Wed Jan 22 19:50:30 2020 +0000

    Make call_process call signal_after_change.  This fixes bug #38691.

    Now, functions such as call-proess-region invoke after-change-functions
    correctly.

    * src/callproc.c (call_process): Call prepare_to_modify_buffer in a single
    place, no longer delegating the task to insert_1_both, etc.  Call
    signal_after_change in each of two code branches, such that
    before-change-functions and after-change-functions are always called in
    balanced pairs.

 src/callproc.c | 37 ++++++++++++++++++++++++++++++++++---
 1 file changed, 34 insertions(+), 3 deletions(-)
```
Seems like something about the way after-change functions are called broke ws-butler? I don't know enough about Emacs internals to say for sure, but checking out the commit immediately prior to this one fixes the issue for me! 😂

For me this happens to trigger when loading the magit summary buffer. The start of the backtrace is:
```
  put-text-property(1120 1831 ws-butler-chg chg)
  ws-butler-after-change(1120 1831 0)
  call-process("git" nil (t nil) nil "--no-pager" "-c" "core.preloadindex=true" "-c" "log.showSignature=false" "diff" "--ita-visible-in-index" "--no-ext-diff" "--no-prefix" "--")
  apply(call-process "git" nil (t nil) nil ("--no-pager" "-c" "core.preloadindex=true" "-c" "log.showSignature=false" "diff" "--ita-visible-in-index" "--no-ext-diff" "--no-prefix" "--"))
  process-file("git" nil (t nil) nil "--no-pager" "-c" "core.preloadindex=true" "-c" "log.showSignature=false" "diff" "--ita-visible-in-index" "--no-ext-diff" "--no-prefix" "--")
  apply(process-file "git" nil (t nil) nil ("--no-pager" "-c" "core.preloadindex=true" "-c" "log.showSignature=false" "diff" "--ita-visible-in-index" "--no-ext-diff" "--no-prefix" "--"))
  magit-process-file("git" nil (t nil) nil "--no-pager" "-c" "core.preloadindex=true" "-c" "log.showSignature=false" "diff" "--ita-visible-in-index" "--no-ext-diff" "--no-prefix" "--")
  apply(magit-process-file "git" nil (t nil) nil ("--no-pager" "-c" "core.preloadindex=true" "-c" "log.showSignature=false" "diff" "--ita-visible-in-index" "--no-ext-diff" "--no-prefix" "--"))
  magit-git-insert(("diff" "--ita-visible-in-index" "--no-ext-diff" "--no-prefix" "--"))
  magit-git-wash(magit-diff-wash-diffs ("diff" "--ita-visible-in-index" "--no-ext-diff" "--no-prefix" "--"))
  magit--insert-diff("diff" ("--no-ext-diff") "--no-prefix" "--" nil)
  magit-insert-unstaged-changes()
  apply(magit-insert-unstaged-changes nil)
  magit-run-section-hook(magit-status-sections-hook)
  magit-status-refresh-buffer()
```

**Comment by uberjay** [comment]
The referenced bug: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=38691

I wonder if the difference here is that after-change functions are now called for call-process generated buffers? Perhaps there's an issue with the ws-butler after-change function that was never noticed because it wasn't being called in this context?

**Comment by hlissner** [comment]
Sorry for the delay. As of c17bf49 this issue should be resolved. Let me know if that isn't the case and I'll reopen this issue. Thanks for bringing it to my attention!
