### ISSUE TITLE
[REQUEST] Add key bindings to execute Org code blocks

### ISSUE THREAD

**Issue by sei40kr** [hlissner/doom-emacs#2472]
**Describe the feature**
I want key bindings to execute Org code blocks.
https://github.com/syl20bnr/spacemacs/blob/develop/layers/+emacs/org/packages.el#L292
And I also want a binding for `jupyter-org-execute-and-next-block`.

**System information**
<details><pre>
((emacs
  (version . "26.3")
  (features . "NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS LCMS2")
  (build . "Sep 17, 2019")
  (buildopts "--enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-mac/emacs-26.3-z-mac-7.7/share/info/emacs --prefix=/usr/local/Cellar/emacs-mac/emacs-26.3-z-mac-7.7 --with-mac --enable-mac-app=/usr/local/Cellar/emacs-mac/emacs-26.3-z-mac-7.7 --with-gnutls --with-modules")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, upstream/develop, upstream/HEAD, origin/develop a12a54b28 2020-02-02 03:18:49 -0500")
  (dir . "~/.doom.d/"))
 (system
  (type . darwin)
  (config . "x86_64-apple-darwin18.7.0")
  (shell . "/usr/local/bin/zsh")
  (uname . "Darwin 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64")
  (path "~/.zinit/plugins/starship---starship" "~/.zinit/plugins/julienXX---terminal-notifier" "~/.zinit/plugins/direnv---direnv" "~/.rbenv/shims" "~/.pyenv/shims" "~/.goenv/shims" "~/.zinit/polaris/bin" "~/.local/bin" "~/.yarn/bin" "~/.gem/ruby/2.6.0/bin" "~/.rbenv/bin" "~/.pyenv/bin" "~/.poetry/bin" "~/perl5/bin" "~/perl5/perlbrew/bin" "~/.goenv/bin" "~/go/system/bin" "~/.cargo/bin" "/usr/local/bin" "/usr/local/sbin" "/usr/bin" "/bin" "/usr/sbin" "/sbin" "/Library/TeX/texbin" "/usr/local/Cellar/emacs-mac/emacs-26.3-z-mac-7.7/libexec/emacs/26.3/x86_64-apple-darwin18.7.0"))
 (config
  (envfile . envvar-file)
  (elc-files . 1)
  (modules :completion company helm :ui doom doom-dashboard fill-column hl-todo hydra indent-guides modeline nav-flash ophints (popup +all +defaults) tabs treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold (format +onsave) multiple-cursors snippets word-wrap :emacs (dired +icons) vc :term vterm :checkers (syntax +childframe) :tools ansible debugger docker editorconfig ein eval (lookup +docsets) lsp magit make rgb tmux :lang assembly (cc +lsp) data emacs-lisp (ess +lsp) (go +lsp) (haskell +lsp) (java +lsp) (javascript +lsp) (kotlin +lsp) (markdown +grip) (org +dragndrop +gnuplot +jupyter) perl (php +lsp) plantuml (python +lsp +pyenv) rest (ruby +lsp +rbenv) rust (scala +lsp) (sh +lsp) solidity (web +css +html +lsp) :config (default +bindings +smartparens))
  (packages . "<(void-function sp-point-in-string)>")
  (elpa "n/a")
  (unpin "n/a")))
</pre></details>

**Comment by dinkonin** [comment]
Add this to your config.el
```elisp
    (map! :localleader
          (:map org-mode-map
            "b e" #'org-babel-execute-maybe
            "b j" #'jupyter-org-execute-and-next-block
          ))
```
Then you can use your localleader (SPC m by default)  + b e / b j

**Comment by sei40kr** [comment]
@dinkonin 
Thanks.
Do we have any plans to implement them as default? Because it's heavily used with `emacs-jupyter`.

**Comment by hlissner** [comment]
The default keybind(s) for executing a babel block in Doom are `RET` and `C-c C-c`. There is no keybind for jupyter and none planned at the moment, but evil users also have `]c` and `[c` for jumping to next/previous babel src block.

**Comment by sei40kr** [comment]
@hlissner 
Thanks! I'm closing this.
