### ISSUE TITLE
Does not open a minified css file (one line) ~150kb 

### ISSUE THREAD

**Issue by KVAnton-WEB** [hlissner/doom-emacs#2474]
**What actually happened?**
...
Does not open a minified css file (one line) ~150kb 
100% loading of one of the cores
The same source code is normally opened in a non-minified way.

**Additional details:**
- Include a link to your private config: 
checked on a clean installation, without a user config (and the latest dev version)

**System information:**
<details><pre>
 CPU: AMD Phenom II X4 965 @ 4x 4.07GHz
 RAM:  15928MiB
</pre></details>

Place the output of `M-x doom/info` or `~/.emacs.d/bin/doom info` here.
(This is my working version. but checked on a new installation)

<details><pre>
emacs   version    26.2
        features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD LCMS2
        build      апр 12, 2019
        buildopts  (--build=x86_64-linux-gnu --prefix=/usr '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' --sysconfdir=/etc --localstatedir=/var --disable-silent-rules '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' --disable-maintainer-mode --disable-dependency-tracking --prefix=/usr --sharedstatedir=/var/lib --program-suffix=26 --with-modules --with-file-notification=inotify --with-mailutils --with-x=yes --with-x-toolkit=gtk3 --with-xwidgets --with-lcms2 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/emacs26-CYbeHB/emacs26-26.2~1.gitfd1b34b=. -fstack-protector-strong -Wformat -Werror=format-security -no-pie' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro -no-pie')
        windowsys  x
        daemonp    daemon
doom    version    2.0.9
        build      HEAD -> develop, origin/develop, origin/HEAD 18301b0b9 2020-01-10 05:59:54 -0500
        dir        ~/.config/doom/
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/bash
        uname      Linux 5.3.18-050318-generic #201912181133 SMP Wed Dec 18 16:36:09 UTC 2019 x86_64
        path       (~/.npm-packages/bin/ ~/.local/bin/ /usr/local/sbin/ /usr/local/bin/ /usr/sbin/ /usr/bin/ /sbin/ /bin/ /usr/games/ /usr/local/games/ /snap/bin/ /usr/lib/jvm/java-12-oracle/bin/ /usr/lib/jvm/java-12-oracle/db/bin/ /opt/microchip/xc8/v2.00/bin/ /opt/microchip/xc8/v2.00/bin/ ~/.config/composer/vendor/bin/ ~/.emacs.d/bin/ ~/development/flutter/bin/ ~/.fzf/bin/ /usr/lib/x86_64-linux-gnu/emacs/26.2/x86_64-linux-gnu/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion (company +auto +childframe) ivy :ui doom doom-dashboard fill-column hl-todo indent-guides modeline nav-flash ophints (popup +all +defaults) (pretty-code :variables prettify-symbols-alist (quote nil)) treemacs unicode vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold multiple-cursors rotate-text snippets :emacs (dired +ranger +icons) electric vc :term term :tools eval gist (lookup +docsets) magit :lang cc data emacs-lisp javascript markdown (org +dragndrop +ipython +pandoc +present) php sh web :config (default +bindings +smartparens +snippets +evil-commands))
        packages   (eshell-toggle rtags cmake-ide move-text format-all web-beautify add-node-modules-path prettier-js auto-highlight-symbol)
        elpa       (smarty-mode)
</pre></details>

**Comment by hlissner** [comment]
I downloaded https://github.githubassets.com/assets/frameworks-a2e2395127165506ac2d8ef1ad3cb13a.css (151kb minified css file) and opened it in doom with no problem. `so-long-mode` successfully kicked in, making it very fast to load and display.

Can you reproduce this [in vanilla Doom, using the sandbox](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#testing-in-dooms-sandbox)? If not, then the issue lies in your confi.

**Comment by KVAnton-WEB** [comment]
Sorry, now everything is working well, I don’t know what was wrong last time. (tested on two devices both times.). The problem was probably not somewhere in the emacs.
