### ISSUE TITLE
daemon bug : *ERROR*: Symbol’s value as variable is void: projectile-project-root 

### ISSUE THREAD

**Issue by gagbo** [hlissner/doom-emacs#2479]
As reported by @babariviere (I think), commit 4a5cf047611f65002f49feef9675c26bcf313ef1 seems to break the daemon and prevents it from starting with the error given in title `*ERROR*: Symbol’s value as variable is void: projectile-project-root`

**Quickfix** : add `(defvar-local projectile-project-root nil)` before the `(doom! )` macro in `~/.config/doom/init.el` file.

Creating the issue for easier search

Trying to reproduce this daemon issue didn't work for me on a recent emacs head (28.0.50)
1) starting emacs
2) `SPC h E`
3) `C-c C-p`
4) kill the first emacs instance with `kill-emacs`
5) `M-x server-start` in the sandboxed new emacs instance
6) `emacsclient -nw -c -a "" FILE` works without triggering the error
(and without starting a new user-tainted emacs process)

**Comment by hlissner** [comment]
As of 1cacfcf this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
