### ISSUE TITLE
How to define new leader key in doom?

### ISSUE THREAD

**Issue by FirstLoveLife** [hlissner/doom-emacs#2480]
**What are you trying to achieve?**
define personal leader key besides `doom-leader-key` and `doom-localleader-key`. 

**What have you tried?**
```
(defconst uos/leader "s")

(map!
 :nvm "s" #'nil
 :prefix uos/leader
 "s" #'evil-snipe-s)
```

with the code below, `s` is undefined. How to let doom know s has been my another leader key?

**Comment by FirstLoveLife** [comment]
```
(define-key evil-normal-state-map "s" nil)
  (defvar uos/leader "s")
(map!
 :prefix uos/leader
 :n "s" #'evil-snipe-s)
```
works

but defconst cannot do it...

**Comment by FirstLoveLife** [comment]
So I have tow questions here: 

## How can I unset <kbd>s</kbd> in my own module inside DOOMDIR/modules/editor/keybinding?
because I hope to use uos/leader(<kbd>s</kbd> in my modules, I cannot unset it in DOOMDIR/config.el, which is always loadded after all modules loaded. I have tried some things like `(require evil)`/`(after! evil)`/`(after evil-snipe-s)`/`(after evil-maps)` and etc, none of them can work.
2. How to unbind it permanently

**Comment by hlissner** [comment]
1. To disable `s`: [disable evil-snipe](https://github.com/hlissner/doom-emacs/blob/develop/modules/editor/evil/README.org#restoring-old-substitution-behavior-on-ss)

2. To define your own leader key:

If you a brand new, fresh leader key, then what you did will work, but is easily overwritten. If you bind it to `general-override-mode-map` will won't be overwritten.

If you want an alternative leader key (so `SPC x` and `<newleaderkey> x`) do the same thing, then:

```elisp
(map! :map general-override-mode-map
      :nvm "<newleaderkey"> #'doom/leader
      :ei "<alternative-newleaderkey"> #'doom/leader)
```
Hope that helps!

**Comment by FirstLoveLife** [comment]
Thanks! @hlissner 

Is there any keys you recommend for personal leader?
