### ISSUE TITLE
Ivy search projectile ripgrep

### ISSUE THREAD

**Issue by Pederaugust** [hlissner/doom-emacs#2481]
First and foremost, I love doom. Best editor ever.
Now to my issue
**What did you expect to happen?**
...
I expected typing something when searching would search for text in files in the project

**What actually happened?**
...
first letter I type I get the message "Error in post-command-hook (ivy--queue--exhibit):(void-function nil)" I use ivy for search and have ripgrep installed on my macbook. Typing several letters does not result in any searchresults.

**Additional details:**
- Include a link to your private config
- Include screenshots/casts of your issue
- If you mention key sequences, include what commands they're bound to (use `SPC
  h k KEY` or `C-h h k KEY` to inspect keys).
SPC s p
- Include any warnings or errors logged to \*Messages\* (use `M-x
  view-echo-area-messages` to see it).

Error during redisplay: (eval (doom-modeline-segment--modals)) signaled (void-variable when) [6 times]
QuitError during redisplay: (eval (doom-modeline-segment--modals)) signaled (void-variable when)
Error during redisplay: (eval (doom-modeline-segment--modals)) signaled (void-variable when)
Error in post-command-hook (ivy--queue-exhibit): (void-function nil)
QuitError during redisplay: (eval (doom-modeline-segment--modals)) signaled (void-variable when)
Error during redisplay: (eval (doom-modeline-segment--modals)) signaled (void-variable when)

<details><pre>
If an error message is involved include a backtrace of it.

How to acquire a backtrace:
https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#how-to-extract-a-backtrace-from-an-error
</pre></details>

**Steps to reproduce:**
1. ran git pull from branch develop
2. bin/doom update
3. bin/doom refresh
4. start emacs
5. Open any project
6. SPC s p
7. First letter you type, no error messages

**System information:**
<details><pre>
Place the output of `M-x doom/info` or `~/.emacs.d/bin/doom info` here.
</pre></details>

**Comment by valrus** [comment]
@Pederaugust I was having this problem too. `doom doctor` turned up some stale .elc files (including, notably, `ivy` and `ivy-overlay`) and I was able to rebuild them with `doom build`. This resolved the issue for me. Maybe give that a try?

**Comment by Pederaugust** [comment]
Thank you @valrus that solved my exact problem. You sir are a legend! namaste
