### ISSUE TITLE
Doom does not allow for pixel scrolling under railwaycat's mac port

### ISSUE THREAD

**Issue by kovkev** [hlissner/doom-emacs#2482]
**What did you expect to happen?**
When I scroll with my macbook touchpad, I see pixel scrolling

**What actually happened?**
When I scroll with my macbook touchpad, I see line-by-line scrolling

**Additional details:**
- I have an empty doom emacs install.
- I am able to see pixel scrolling in railwaycat's mac port after doing `mv ~/.emacs.d ~/.emacs.d.doom_restore_after` . Also, I don't have to do `M-x pixel-scroll-mode` to enable it. I can pixel scroll right away in an empty emacs install.

**System information:**
<details><pre>
emacs   version    26.3
        features   NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS
        build      Jan 29, 2020
        buildopts  (--enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-mac/emacs-26.3-z-mac-7.8/share/info/emacs --prefix=/usr/local/Cellar/emacs-mac/emacs-26.3-z-mac-7.8 --with-mac --enable-mac-app=/usr/local/Cellar/emacs-mac/emacs-26.3-z-mac-7.8 --with-gnutls)
        windowsys  mac
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop, origin/develop, origin/HEAD 58c6aea7c 2020-01-30 17:38:12 -0500
        dir        ~/.doom.d/
system  type       darwin
        config     x86_64-apple-darwin19.2.0
        shell      /bin/bash
        uname      Darwin 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64
        path       (~/.nvm/versions/node/v13.3.0/bin ~/google-cloud-sdk/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /usr/local/share/dotnet /opt/X11/bin /Library/Frameworks/Mono.framework/Versions/Current/Commands ~/kg_bin/ ~/bin /usr/local/Cellar/emacs-mac/emacs-26.3-z-mac-7.8/libexec/emacs/26.3/x86_64-apple-darwin19.2.0/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash neotree ophints (popup +all +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold multiple-cursors rotate-text snippets :emacs dired electric ibuffer vc :term eshell :checkers syntax :tools (eval +overlay) (lookup +docsets) magit :lang data emacs-lisp markdown (org +dragndrop +present) sh :config (default +bindings +smartparens))
        packages   (n/a)
        elpa       (n/a)
        unpin      (n/a)

</pre></details>

**Comment by hlissner** [comment]
[I've disable smooth scrolling](https://github.com/hlissner/doom-emacs/blob/develop/core/core-ui.el#L197) because it's slow to the point that it's unusable. Try `(setq mac-mouse-wheel-smooth-scroll t)` to restore it. Perhaps tweak `mouse-wheel-progressive-speed` as well.

**Comment by greghab** [comment]
On a fresh doom installation, enabling pixel-scroll-mode lags scrolling, and freezes doom emacs within a few seconds.
Removing the scrolling configuration in core-ui.el allows pixel-scroll-mode to work like normal. For those that want to use pixel-scroll-mode, is editing core-ui.el the optimal solution? Or is there a way to disable the added scrolling configurations specified in core-ui.el via a personal config?

**Comment by NightMachinary** [comment]
This issue is still relevant.
