### ISSUE TITLE
how do i copy url quickly?

### ISSUE THREAD

**Issue by loyalpartner** [hlissner/doom-emacs#2484]
i 'm  beginner .
i have a question, i want to copy a url under point, 
and i know something about textobjecs, we can copy a word by ```yiw```. 
Is there anyway to copy or select an url use `yiu`

**Comment by CodyWilson** [comment]
Assuming there's space or blank on both sides, `yiW` should grab it.

If it's surrounded by quotes, then `yi"` or `yi'` should get you what you want.

If it's jammed up against another symbol, and it's not surrounded by said symbol,  then you're probably stuck going to the beginning of the url, going into visual mode, and then traveling to the end of the URL.

Which can be done pretty quickly with `f`/`F`, and `E`.
Get to the first character, and then `E` to the end.

**Comment by loyalpartner** [comment]
@CodyW,Thank you very much.

**Comment by hlissner** [comment]
In 1575300 I added a `u` text object. `iu` selects the url without the protocol (`https://`) and querystring (`?a=1&b=2`). `au` selects the whole url.

**Comment by CodyWilson** [comment]
You're a god Henrik.

**Comment by hlissner** [comment]
I should also mention, `gf` will open urls at point in your browser.
