### ISSUE TITLE
my autoload function cannot be found

### ISSUE THREAD

**Issue by FirstLoveLife** [hlissner/doom-emacs#2486]
**What did you expect to happen?**
`(setf (alist-get 'file org-link-frame-setup) 'uos/org-open-other-workspace)` can find my `uos/org-open-other-workspace`

**What actually happened?**

> org-open-file: Symbol’s function definition is void: uos/org-open-other-workspace

**Additional details:**

"/home/firstlove/.config/doom/modules/mylang/org/config.el":
```
(setf (alist-get 'file org-link-frame-setup) 'uos/org-open-other-workspace)
```

"/home/firstlove/.config/doom/modules/mylang/org/autoloads.el":
```
;;; mylang/org/autoload.el -*- lexical-binding: t; -*-

;;;###autoload
(defun uos/org-open-other-workspace(filename &optional wildcards)
  (require 'f)
  (setq project-name (f-filename (projectile-project-root filename)))
  (if (+workspace-exists-p project-name)
      (+workspace/switch-to project-name)
    (+workspace/new)
    (+workspace/rename (f-filename (projectile-project-root filename)))
    )
  (find-file filename)
  )
```

**Comment by hlissner** [comment]
The issue is with the filename of your autoloads file. It needs to be `autoload.el`, without the `s`.

After renaming it, run `doom sync` (or `doom refresh` -- they are aliases) to get Doom to index it.

Let me know if that isn't the case and I'll reopen the issue.

**Comment by FirstLoveLife** [comment]
@hlissner It works! thanks a ton!
