### ISSUE TITLE
Newly created workspaces are not always placed in the right most workspace

### ISSUE THREAD

**Issue by AlexLewandowski** [hlissner/doom-emacs#2487]
**What did you expect to happen?**
I expect a new workspace to always be added to the right most space, so that already existing workspaces do not get shifted up.

In other words, if the current workspace list is `[#1]` then `SPC tab n` should yield a workspace list of ``, `[#1, #2]`.

**What actually happened?**
Newly created workspaces can sometimes be added to the first entry, shifting already existing workspaces (the workspace accessed by `SPC tab 1` can be shifted up and accessed by `SPC tab 2`).

In other words, if the current workspace list is `[#1]` then `SPC tab n` actually yields a workspace list of `[#2, #1]`.

**Additional details:**
This is reproducible in the sandbox with doom + modules

**Steps to reproduce:**

Steps to reproduce with sandbox doom instance (doom + modules).
```
SPC tab n ;; Creates workspace #1 in place 2
SPC tab 1 ;; Switch to workspace main in place 1
SPC tab d ;; delete workspace main, workspace #1 is now in place 1
SPC tab n ;; Creates workspace #2 (should be in place 2, takes place 1)
SPC tab tab ;; [#2, #1]
SPC tab n ;; Creates workspace #3 in place 3
SPC tab tab ;; [#2, #1, #3]
```
Shows that the workspace list is `[#2, #1, #3]`. i.e. the second `SPC tab n` created `workspace #2` on the left most side, instead of the right most side. But then, `workspace #3` was created on the right most side as desired. 

**System information:**
<details>

```
emacs   version    27.0.50
        features   XPM JPEG TIFF GIF PNG RSVG SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS PDUMPER LCMS2 GMP
        build      Dec 02, 2019
        buildopts  (--with-modules --with-rsvg)
        windowsys  x
        daemonp    daemon
doom    version    2.0.9
        build      HEAD -> develop, origin/develop, origin/HEAD 1575300ad 2020-02-04 13:58:43 -0500
        dir        ~/.dotfiles/emacs/.doom.d/
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      zsh
        uname      Linux 4.15.0-76-generic #86-Ubuntu SMP Fri Jan 17 17:24:28 UTC 2020 x86_64
        path       (~/anaconda3/bin ~/anaconda3/condabin ~/.emacs.d/bin ~/gems/bin ~/bin /usr/bin/applets /usr/local/bin /usr/bin /bin /opt/bin ~/.local/bin ~/.local/bin ~/bin /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /usr/games /usr/local/games /snap/bin /usr/local/libexec/emacs/27.0.50/x86_64-pc-linux-gnu)
config  envfile    nil
        elc-files  4
        modules    (:completion company (ivy +childframe) :ui doom doom-dashboard hl-todo hydra modeline nav-flash ophints (popup +all +defaults) pretty-code treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold format multiple-cursors rotate-text snippets :emacs dired electric ibuffer vc :term eshell term vterm :tools editorconfig (eval +overlay) :checkers syntax :tools (lookup +docsets) lsp magit pdf :lang data emacs-lisp julia (latex +latexmk) markdown (org +dragndrop +journal +pandoc +present) python sh :config (default +bindings +smartparens))
        packages   ((anaconda-mode :recipe (:host github :repo falloutphil/anaconda-mode)) (eshell-prompt-extras :recipe (:host github :repo AlexLewandowski/eshell-prompt-extras)) (org-gcal :recipe (:host github :repo kidd/org-gcal.el)) (yapfify) (pcomplete-extension) (pcmpl-git) (org-ref-arxiv :recipe (:host github :repo AlexLewandowski/org-ref :files (org-ref-arxiv.el org-ref-utils.el org-ref-pdf.el))) (doom-themes) (company-posframe) (org-indent :disable t) (org-babel :disable t) (exec-path-from-shell) (lsp-julia :recipe (:host github :repo non-Jedi/lsp-julia)) (material-theme))
        elpa       (n/a)
        unpin      (n/a)
```
</details>

**Comment by hlissner** [comment]
Doom doesn't do anything to affect or ensure order of workspaces, and can't, at the moment. We use [persp-mode](https://github.com/Bad-ptr/persp-mode.el) which doesn't give us that capability. It'd either need to be implemented upstream, or we'd have to abstract workspace order (and perhaps their names) from their underlying representation.

I'm currently swamped with other urgent work, so I cannot work on this. A PR is welcome, or better, a PR for persp-mode.

**Comment by AlexLewandowski** [comment]
No worries, thank you for Doom!

**Comment by hlissner** [comment]
As of 3ab70d7 this issue should be fixed. A slightly more systemic solution was needed than #2488. Let me know if the issue resurfaces and I'll reopen this. Thanks for bringing it to my attention!
