### ISSUE TITLE
how do i link a info file in org mode

### ISSUE THREAD

**Issue by loyalpartner** [hlissner/doom-emacs#2492]
**What are you trying to achieve?**

**What have you tried?**
i read this https://orgmode.org/org.html#External-Links doc.
i try to use [[info:elisp]] to link the elisp info, but it failed

**Comment by hlissner** [comment]
See `SPC h v org-modules` (or `C-h v org-modules`)

The fix: `(add-to-list 'org-modules 'ol-info)`
