### ISSUE TITLE
Personal keybind is overwritten by Doom

### ISSUE THREAD

**Issue by alinbxSorcerer** [hlissner/doom-emacs#2506]
**What did you expect to happen?**
When  C-h f "org-capture" 

```
Key Bindings
doom-leader-map n n
doom-leader-notes-map n
general-override-mode-map C-c n n
global-map C-c c
mode-specific-map c
```

**What actually happened?**

```
doom-leader-map n n
doom-leader-notes-map n
general-override-mode-map C-c n n
```
It override my personal setting of  "(global-set-key "\C-cc" 'org-capture)"

**Additional details:**

Sorry,  I have no time to read any of your docs, and promise this project dying soon.

Who do you think you are to to set priority than my personal setting.

**Comment by hlissner** [comment]
Are you having a bad day? Would you like a [puppy](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fregmedia.co.uk%2F2016%2F03%2F18%2Fshutterstock_devil_dog.jpg&f=1&nofb=1)? Or perhaps [a kitten](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fimgix.bustle.com%2Fuploads%2Fimage%2F2018%2F10%2F17%2F9f570e98-5b2d-41ae-802a-600c1cc5446f-devil-cat.jpg%3Fw%3D970%26h%3D546%26fit%3Dcrop%26crop%3Dfaces%26auto%3Dformat%26q%3D70&f=1&nofb=1)?

> Sorry, I have no time to read any of your docs

Great! I love issues that are easy to deal with!
