### ISSUE TITLE
"doom install" stuck on windows.

### ISSUE THREAD

**Issue by skywind3000** [hlissner/doom-emacs#2513]
**What did you expect to happen?**

`doom install` should work on windows.

**What actually happened?**

it was unresponsive after:

```
Installing Doom Emacs!
> Creating .doom.d/
   Created .doom.d/
- Creating .doom.d/init.el
Done!
- Creating .doom.d/config.el
Done!
- Creating .doom.d/packages.el
Done!
```

**Additional details:**

Last night for sleeping, I cloned a fresh doom into `~/.emacs.d` and ran `doom install`:

![freeze](https://user-images.githubusercontent.com/3035071/74134381-6ded7180-4c25-11ea-84f3-3a51144a9f07.png)

And this morning, it still stucked at this point. CPU usage of `emacs.exe` keeps at a high level of 12% (8 cores).

Than I pressed `CTRL+C` and gave up.

How to acquire a backtrace:
https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#how-to-extract-a-backtrace-from-an-error
</pre></details>

**Steps to reproduce:**

- windows, follow the installation instruction:

```
git clone https://github.com/hlissner/doom-emacs ~/.emacs.d
~/.emacs.d/bin/doom install
```

**System information:**
Windows 10, Emacs 26.3

**Comment by hlissner** [comment]
This is an odd one. I'm not sure how to go about debugging it, since I don't have a windows machine handy. I pushed a fix for a separate issue in https://github.com/hlissner/doom-emacs/issues/2556. Could you update and see if that resolves this one?

**Comment by skywind3000** [comment]
Yes, it was my fault. I was running emacs behind a firewall, then, following code fixed the problem:

```
set HTTP_PROXY=127.0.0.1:1080
```

**Comment by skywind3000** [comment]
It can be closed now.
