### ISSUE TITLE
Styled components behaves weird on JS files.

### ISSUE THREAD

**Issue by AdrianDorneanu** [hlissner/doom-emacs#2515]
New to Emacs here.

**What did you expect to happen?**
Syntax highlight to be displayed correctly while working on a file with JS + Styled components.

**What actually happened?**
Syntax highlight behaves weird. Code is not pleasant to the eye and it's exhausting to work day to day with this problem. 

**Additional details**
This happens only when a file have Styled Components in it. For files with only Javascript, syntax highlighting works perfectly fine

Behavior:
![Screenshot 2020-02-10 at 13 50 23](https://user-images.githubusercontent.com/26359091/74148166-7043d180-4c0d-11ea-83b4-7897f953ebef.png)

**Comment by tosiek88** [comment]
How did you solve this? for now I am using different syntax, just passing the object instead of using the interpolation. For example like this: 

```ts
const Div=styled.div({ color:"blue"});
```
It will help me for syntax, and intellisense but I can imagine if you working in the team this can be an issue.
