### ISSUE TITLE
How to use ",," in magit?

### ISSUE THREAD

**Issue by wangggong** [hlissner/doom-emacs#2519]
**What are you trying to achieve?**
In magit, I want to commit my change;

**What have you tried?**
1. (modify files in doom);
2. "SPC gg" to open magit;
3. "s" to stage change;
4. "cc" to commit;
5. Write commit comments;
6. ",," to apply -- FAILED.

**Additional information**
- Do you have screenshots/casts of this workflow in another editor or Emacs
  distro? (If possible, include names of specific commands or functions from
  other editors/emacs distros)
- Do you have additional material or links to resources that could help clarify
  what you are trying to do?

- When in Spacemacs: OK
- Searching in issues: not found

**System information**
<details><pre>
Include the output of `M-x doom/info` or `~/.emacs.d/bin/doom info` here.
</pre></details>

<details>

```
emacs   version    26.3
        features   NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS
        build      Sep 02, 2019
        buildopts  (--with-ns '--enable-locallisppath=/Library/Application Support/Emacs/${version}/site-lisp:/Library/Application Support/Emacs/site-lisp' --with-modules)
        windowsys  nil
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop ae75326a4 2020-02-10 02:39:26 -0500
        dir        ~/.doom.d/
system  type       darwin
        config     x86_64-apple-darwin18.2.0
        shell      /bin/zsh
        uname      Darwin 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64
        path       (~/.cargo/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /Applications/VMware Fusion.app/Contents/Public ~/anaconda3/bin ~/anaconda3/condabin /usr/local/opt/coreutils/libexec/gnubin ~/.cargo/bin /opt/soft/protoc/bin ~/Code/bin ~/Code/src/github.com/9fans/plan9port/bin /Library/Java/JavaVirtualMachines/jdk-13.0.1.jdk/Contents/Home/bin ~/Code/src/github.com/BurntSushi/ripgrep/target/release ~/.fzf/bin /Applications/Emacs.app/Contents/MacOS/bin-x86_64-10_14 /Applications/Emacs.app/Contents/MacOS/libexec-x86_64-10_14 /Applications/Emacs.app/Contents/MacOS/libexec /Applications/Emacs.app/Contents/MacOS/bin)
config  envfile    envvar-file
        elc-files  0
        modules    (:input chinese :completion company ivy :ui doom doom-dashboard doom-quit hl-todo indent-guides modeline nav-flash neotree ophints (popup +all +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold rotate-text snippets :emacs dired electric ibuffer vc :term vterm :checkers syntax spell :tools (eval +overlay) (lookup +docsets) magit pdf :lang data emacs-lisp go javascript markdown (org +dragndrop +present) python scheme sh web :config (default +bindings +smartparens))
        packages   (n/a)
        elpa       (n/a)
        unpin      (n/a)
```
</details>

**Comment by hlissner** [comment]
I don't understand where `,,` comes from. The keybind to commit has always been `ZZ` (for evil users) or `C-c C-c` (everyone). Or `ZX`/`C-c C-k` to abort.

Do these keys not work for you?

**Comment by Alexander-Miller** [comment]
> I don't understand where ,, comes from. 

That's how spacemacs does it :thinking:

**Comment by wangggong** [comment]
> I don't understand where `,,` comes from. The keybind to commit has always been `ZZ` (for evil users) or `C-c C-c` (everyone). Or `ZX`/`C-c C-k` to abort.
> 
> Do these keys not work for you?
> 
> EDIT: If you are asking how to bind these keys, you could try:
> 
> ```emacs-lisp
> (map! :map with-editor-mode-map :n ",," #'with-editor-finish)
> ```

Sorry, I just used ",,", and took it as granted. Got it, thanks.

**Comment by hlissner** [comment]
No worries! It just caught me by surprise -- I'm not terribly familiar with Spacemacs. In any case, glad we could figure this out! I'll consider this resolved. Cheers!
