### ISSUE TITLE
Buffer list view does not work

### ISSUE THREAD

**Issue by arpd** [hlissner/doom-emacs#252]
Present on `master` and `develop` branches; Fresh install using `init.example.el`

Attempting to open a buffer view (or however it is described) results in:
`Symbol's function definition is void: +ivy-buffer-transformer`

I attempted this using combination `<SPACE> b B`

**Comment by hlissner** [comment]
This _may_ be related to #251. Just in case, could you run `make autoloads` and let me know if the issue persists?

**Comment by arpd** [comment]
This is exactly correct! I'll close these two issues. Thanks @hlissner !
