### ISSUE TITLE
region selection on default/search-project

### ISSUE THREAD

**Issue by idanko** [hlissner/doom-emacs#2523]
**What did you expect to happen?**
The region selection still exists when default/search-project executed and the occurrence locates on the same file.

**What actually happened?**
The whole region is highlighting from the initial cursor position (at the searching token) up to the match (after default/search-project function call).

**Additional details:**
- highlight the token being searched (ensure that the same token occurs twice on the current file)
- press space + s + p (default/search-project) and select the preview from the ivy (should be on the same file).
- the backend engine is ripgrep

**Expected behavior:**
No region selection.

**Actual behavior:**
Region selection between two lates emacs marks.
Resulting search:

![doom_search_region_bug](https://user-images.githubusercontent.com/8293386/74265082-7cfa1f80-4d0a-11ea-9d01-c91f41f9737b.jpg)

**Comment by hlissner** [comment]
As of 3b6fd1b this should be fixed: the mark (visual state) is deactivated upon a successful search (but not if you abort the search). Let me know if that isn't the case and I'll reopen this issue. Thanks for bringing it to my attention!

**Comment by idanko** [comment]
key @hlissner, the issue is solved, the behavior as expected, thank you
