### ISSUE TITLE
+evil:make appends to compile-command instead of replacing it

### ISSUE THREAD

**Issue by Janfel** [hlissner/doom-emacs#2524]
**What did you expect to happen?**
Calling `:make target` runs the shell command `make target`.

**What actually happened?**
Calling `:make target` runs `make -k make target`.
Calling `:make target` again runs `make -k make target make target` and so on...

**Additional details:**
- The garbage command is saved in `compile-command`.
- `+evil:make` calls `+evil:compile` which causes this issue.
- [These lines in `+evil:make`.](https://github.com/hlissner/doom-emacs/blob/d1f4a77fbb70856a4c3dad4cacfa34cadc6cddd8/modules/editor/evil/autoload/ex.el#L113-L115)
- [These lines in `+evil:compile`.](https://github.com/hlissner/doom-emacs/blob/d1f4a77fbb70856a4c3dad4cacfa34cadc6cddd8/modules/editor/evil/autoload/ex.el#L127-L129)

**Steps to reproduce:**
1. Call `:make target` without a makefile.
1. Call it again.
2. Check the helpful error message.

**System information:**
<details><pre>
((emacs
  (version . "26.3")
  (features . "XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2")
  (build . "Aug 29, 2019")
  (buildopts "--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-modules 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD 197a3faa7 2020-02-06 19:42:35 -0500")
  (dir . "~/.config/doom/"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/usr/bin/zsh")
  (uname . "Linux 5.5.2-1-MANJARO #1 SMP PREEMPT Tue Feb 4 19:22:35 UTC 2020 x86_64")
  (path "~/bin" "/usr/local/sbin" "/usr/local/bin" "/usr/bin" "/var/lib/flatpak/exports/bin" "/usr/lib/jvm/default/bin" "/usr/bin/site_perl" "/usr/bin/vendor_perl" "/usr/bin/core_perl" "~/.local/bin" "~/.config/emacs_doom/bin" "~/.dotnet/tools" "~/var/go/bin" "~/.cabal/bin" "~/opt/ghcup/bin" "~/.gem/ruby/2.7.0/bin" "~/.local/share/cargo/bin" "/usr/lib/emacs/26.3/x86_64-pc-linux-gnu"))
 (config
  (envfile)
  (elc-files . 32)
  (modules :completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash neotree ophints (popup +all +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold fmt multiple-cursors rotate-text snippets :emacs dired electric ibuffer vc :term term vterm :checkers syntax :tools (eval +overlay) (lookup +docsets) lsp magit :lang (cc +lsp) clojure common-lisp data emacs-lisp haskell latex (lua +moonscript) markdown (org +dragndrop +jupyter +present) (python +lsp) (rust +lsp) sh :config literate (default +evil +bindings +smartparens))
  (packages . "<(void-function sp-point-in-string)>")
  (elpa "n/a")
  (unpin "n/a")))
</pre></details>

**Comment by hlissner** [comment]
My bad. As of 888d456 this should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
