### ISSUE TITLE
Upstream Org Tweaks?

### ISSUE THREAD

**Issue by wurosh** [hlissner/doom-emacs#2536]
Following up on [this comment](https://www.reddit.com/r/emacs/comments/f3ed3r/comment/fhixxjx), startup optimizations doom makes for org seem like a very useful thing to contribute to org. Especially since users don't always anticipate the languages they need or even know that they need to load them in advance. It would just make using babel so much smoother. I'd try to do it, but someone who wrote the code would probably be far better at it.

**Comment by hlissner** [comment]
I've extracted and generalized the implementation [in a gist](https://gist.github.com/hlissner/14b42de71c65945f55a31b393af0391b).

Would they accept it? It may hurt backward compatibility and introduces edge cases with babel plugins that have special load-order or configuration needs (like ob-async or jupyter), or don't match the name of the language they provide support for. For reference:

+ For [jupyter](https://github.com/hlissner/doom-emacs/blob/develop/modules/lang/org/contrib/jupyter.el#L15-L27)
+ For [ob-ipython](https://github.com/hlissner/doom-emacs/blob/develop/modules/lang/org/contrib/ipython.el#L11-L14)
+ And [ob-async](https://gist.github.com/hlissner/14b42de71c65945f55a31b393af0391b#file-org-lazy-babel-el-L42-L45)

**Comment by jjzmajic** [comment]
Thanks @hlissner! I'll try to spark discussion on the other side. For names that don't match, a simple alist should do with a fallback heuristic along the lines of the gist. It doesn't really feel like overkill to me, but that's debatable. Special configuration needs are a valid concern. I'll think on that a bit

**Comment by jjzmajic** [comment]
Besides, they don't have to remove the old mechanism, old configs should still work. After all, the pcompletions are still there for backwards compatibility and I'm pretty sure I'm one of 3 people that use those.

**Comment by jjzmajic** [comment]
[Done!](https://lists.gnu.org/archive/html/emacs-orgmode/2020-02/msg00595.html). Sorry about the bad formatting, I wasn't sure if hyperlinks would work.
