### ISSUE TITLE
Rust and smartparens

### ISSUE THREAD

**Issue by bkchr** [hlissner/doom-emacs#2543]
Hey, so I debugged today my smartparens problems in doom-emacs.

My problem is that is was not auto completing angle brackets and that it always inserted two `'` in angle brackets. 

Problem one is an upstream bug: https://github.com/Fuco1/smartparens/pull/1006

Problem two is that doom emacs sets `rustic-match-angle-brackets` to `nil` when evil is enabled. I think this behavior should at least be documented in the docs of the rust module. 

CC @sei40kr

**Comment by hlissner** [comment]
Are you suggesting `rustic-match-angle-brackets` to `nil` causes the duplicate single quote to be inserted? Or that it only failed to auto-complete angle brackets? Or both?

**Comment by bkchr** [comment]
Setting `rustic-match-angle-brackets` to `nil` causes duplicate single quotes to be inserted between angle brackets.

**Comment by wsw0108** [comment]
doom override `sp-local-pair` rule for single quote.

https://github.com/Fuco1/smartparens/blob/1f8857c5febe8b82654ba44ae43e6d2f435f4832/smartparens-rust.el#L129

**Comment by bkchr** [comment]
`sp-in-rust-lifetime-context` internally uses `rustic` to match the angle brackets, if the given config option is disabled, it just returns `false`. (I debugged this stuff)
