### ISSUE TITLE
lang cc 'irony-eldoc' error

### ISSUE THREAD

**Issue by Zuwei1** [hlissner/doom-emacs#2548]
**What did you expect to happen?**
lang cc to be enabled

**What actually happened?**
doom refresh gives me: 
  > Installing packages...
    -> Building irony-eldoc...
x There was an unexpected error:
  Type: doom-package-error
  Message:
    Error with packages
  Data:
    "irony-eldoc"
    (error "irony-eldoc.el:0:0: error: error: (Local variables entry is missing the suffix)")
    "/dev/null
    "

**Steps to reproduce:**
1. uncomment cc in .doom.d/init
2. doom refresh

**System information:**
<details><pre>
((emacs
  (version . "26.3")
  (features . "XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2")
  (build . "Aug 29, 2019")
  (buildopts "--without-dbus --host=x86_64-w64-mingw32 --without-compress-install 'CFLAGS=-O2 -static -g3'")
  (windowsys . batch)
  (daemonp))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD ca18034e3 2020-02-17 04:58:57 -0500")
  (dir . "c:/Users/zuwei/.doom.d/"))
 (system
  (type . windows-nt)
  (config . "x86_64-w64-mingw32")
  (shell . "C:\\Program Files\\Git\\usr\\bin\\bash.exe")
  (uname . "n/a")
  (path "c:/Users/zuwei/bin" "C:/Program Files/Git/mingw64/bin" "C:/Program Files/Git/usr/local/bin" "C:/Program Files/Git/usr/bin" "C:/Program Files/Git/usr/bin" "C:/Program Files/Git/mingw64/bin" "C:/Program Files/Git/usr/bin" "C:/Users/zuwei/bin" "C:/Windows/system32" "C:/Windows" "C:/Windows/System32/Wbem" "C:/Windows/System32/WindowsPowerShell/v1.0" "C:/Windows/System32/OpenSSH" "C:/Program Files/NVIDIA Corporation/NVIDIA NvDLISR" "C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common" "C:/ProgramData/chocolatey/bin" "C:/Program Files/Git/cmd" "C:/Program Files/LLVM/bin" "C:/Program Files/dotnet" "C:/Users/zuwei/AppData/Local/Microsoft/WindowsApps" "C:/Users/zuwei/AppData/Local/Programs/Microsoft VS Code/bin" "C:/Users/zuwei/AppData/.emacs.d/bin" "C:/Program Files/Git/usr/bin/vendor_perl" "C:/Program Files/Git/usr/bin/core_perl" "c:/ProgramData/chocolatey/lib/Emacs/tools/emacs/libexec/emacs/26.3/x86_64-w64-mingw32"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold multiple-cursors rotate-text snippets :emacs dired electric ibuffer vc :checkers syntax :tools (eval +overlay) (lookup +docsets) lsp magit :lang (csharp +unity) data emacs-lisp markdown (org +dragndrop +present) sh :config (default +bindings +smartparens))
  (packages . "<(void-function sp-point-in-string)>")
  (elpa "n/a")
  (unpin . "<(void-function sp-point-in-string)>")))
</pre></details>

**Comment by hlissner** [comment]
Please include your `M-x doom/info` or `bin/doom info`.

**Comment by Zuwei1** [comment]
((emacs
  (version . "26.3")
  (features . "XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2")
  (build . "Aug 29, 2019")
  (buildopts "--without-dbus --host=x86_64-w64-mingw32 --without-compress-install 'CFLAGS=-O2 -static -g3'")
  (windowsys . batch)
  (daemonp))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD ca18034e3 2020-02-17 04:58:57 -0500")
  (dir . "c:/Users/zuwei/.doom.d/"))
 (system
  (type . windows-nt)
  (config . "x86_64-w64-mingw32")
  (shell . "C:\\Program Files\\Git\\usr\\bin\\bash.exe")
  (uname . "n/a")
  (path "c:/Users/zuwei/bin" "C:/Program Files/Git/mingw64/bin" "C:/Program Files/Git/usr/local/bin" "C:/Program Files/Git/usr/bin" "C:/Program Files/Git/usr/bin" "C:/Program Files/Git/mingw64/bin" "C:/Program Files/Git/usr/bin" "C:/Users/zuwei/bin" "C:/Windows/system32" "C:/Windows" "C:/Windows/System32/Wbem" "C:/Windows/System32/WindowsPowerShell/v1.0" "C:/Windows/System32/OpenSSH" "C:/Program Files/NVIDIA Corporation/NVIDIA NvDLISR" "C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common" "C:/ProgramData/chocolatey/bin" "C:/Program Files/Git/cmd" "C:/Program Files/LLVM/bin" "C:/Program Files/dotnet" "C:/Users/zuwei/AppData/Local/Microsoft/WindowsApps" "C:/Users/zuwei/AppData/Local/Programs/Microsoft VS Code/bin" "C:/Users/zuwei/AppData/.emacs.d/bin" "C:/Program Files/Git/usr/bin/vendor_perl" "C:/Program Files/Git/usr/bin/core_perl" "c:/ProgramData/chocolatey/lib/Emacs/tools/emacs/libexec/emacs/26.3/x86_64-w64-mingw32"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold multiple-cursors rotate-text snippets :emacs dired electric ibuffer vc :checkers syntax :tools (eval +overlay) (lookup +docsets) lsp magit :lang (csharp +unity) data emacs-lisp markdown (org +dragndrop +present) sh :config (default +bindings +smartparens))
  (packages . "<(void-function sp-point-in-string)>")
  (elpa "n/a")
  (unpin . "<(void-function sp-point-in-string)>")))

**Comment by Zuwei1** [comment]
solved by adding +lsp to cc

**Comment by jfhbrook** [comment]
I have this issue on Windows 10 as well. I don't do much c programming so I just commented it out for now. I'd definitely be curious to know the cause of this issue though!

**Comment by hlissner** [comment]
I've moved this issue to #2637, since it appears to be the real root of this issue.

> solved by adding +lsp to cc
This gets around the issue because `+lsp` prevent irony-eldoc from being installed, and isn't a solution to the underlying problem.
