### ISSUE TITLE
Problem with emacs that not install

### ISSUE THREAD

**Issue by niv280** [hlissner/doom-emacs#2550]
**What are you trying to achieve?**
activate doom on emacs

**What have you tried?**
I got emacs 26 version but that emacs is not install on my linux ( i can't install in my linux ), i download the emacs and run it from the src dir.
i try to activate doom for my not installed emacs but it's not work, it's says that i dont got cl-lib.
probably because he goes to the ver 23 emacs that install ( which i can't replace it with the newer version.
Any idea what i can do?

**Additional information**
I got emacs ver 23 install and ver 26 that i am using which is not install

**Comment by hlissner** [comment]
This is because you have emacs 23 in your `PATH`. Delete it, or add emacs 26 sooner in your `PATH`.

Alternatively, use the EMACS variable to change the location:

```sh
EMACS=/path/to/emacs26 doom install
```

**Comment by niv280** [comment]
where should enter that command: "EMACS=/path/to/emacs26 doom install"

**Comment by niv280** [comment]
Oh i get it now, you meant to run it from shell.
Thanks it's working now!
