### ISSUE TITLE
"Exec format error" when using Doom's CLI on Windows 10

### ISSUE THREAD

**Issue by NickSeagull** [hlissner/doom-emacs#2556]
**What did you expect to happen?**

Run any `doom` command successfully

**What actually happened?**

All of them fail with the error:

```text
x There was an unexpected error:
  Type: file-error
  Message:
    File error
  Data:
    "Spawning child process"
    "Exec format error"
```

**Additional details:**
- Include a link to your private config

https://gist.github.com/NickSeagull/346706a83a717f52d6d03c5ba51d8039

<details><pre>
- Debug mode on

Loading c:/Users/nikit/.emacs.d/core/autoload/buffers.el (source)...
Loading c:/Users/nikit/.emacs.d/core/autoload/cache.el (source)...
Loading c:/Users/nikit/.emacs.d/core/autoload/cli.el (source)...
Loading c:/Users/nikit/.emacs.d/core/autoload/config.el (source)...
Loading c:/Users/nikit/.emacs.d/core/autoload/debug.el (source)...
Loading c:/Users/nikit/.emacs.d/core/autoload/files.el (source)...
Loading c:/Users/nikit/.emacs.d/core/autoload/fonts.el (source)...
Loading c:/Users/nikit/.emacs.d/core/autoload/format.el (source)...
Loading c:/Users/nikit/.emacs.d/core/autoload/help.el (source)...
Loading c:/Users/nikit/.emacs.d/core/autoload/packages.el (source)...
Loading c:/Users/nikit/.emacs.d/core/autoload/plist.el (source)...
Loading c:/Users/nikit/.emacs.d/core/autoload/projects.el (source)...
Loading c:/Users/nikit/.emacs.d/core/autoload/scratch.el (source)...
Loading c:/Users/nikit/.emacs.d/core/autoload/sessions.el (source)...
Loading c:/Users/nikit/.emacs.d/core/autoload/text.el (source)...
Loading c:/Users/nikit/.emacs.d/core/autoload/themes.el (source)...
Loading c:/Users/nikit/.emacs.d/core/autoload/ui.el (source)...
DOOM Initializing package.el
DOOM Initializing straight
DOOM Initializing doom-packages
DOOM Ignoring package vc
DOOM Ignoring package vc-annotate
DOOM Ignoring package smerge-mode
DOOM Ignoring package term
DOOM Ignoring package elisp-mode
> Synchronizing your config with Doom Emacs...
  > (Re)generating core autoloads...
    > Generating core autoloads...
    - Scanning core/autoload/buffers.el
    - Scanning core/autoload/cache.el
    - Scanning core/autoload/cli.el
    - Scanning core/autoload/config.el
    - Scanning core/autoload/debug.el
    - Scanning core/autoload/files.el
    - Scanning core/autoload/fonts.el
    - Scanning core/autoload/format.el
    - Scanning core/autoload/help.el
    - Scanning core/autoload/packages.el
    - Scanning core/autoload/plist.el
    - Scanning core/autoload/projects.el
    - Scanning core/autoload/scratch.el
    - Scanning core/autoload/sessions.el
    - Scanning core/autoload/text.el
    - Scanning core/autoload/themes.el
    - Scanning core/autoload/ui.el
    - Scanning modules/app/calendar/autoload.el
    - Scanning modules/app/irc/autoload/irc.el
    - Scanning modules/app/irc/autoload/settings.el
    - Scanning modules/app/regex/autoload/export.el
    - Scanning modules/app/regex/autoload/regex.el
    - Scanning modules/app/rss/autoload.el
    - Scanning modules/app/twitter/autoload.el
    - Scanning modules/checkers/spell/autoload.el
    - Scanning modules/checkers/syntax/autoload.el
    - Scanning modules/completion/company/autoload.el
    - Scanning modules/completion/helm/autoload/evil.el
    - Scanning modules/completion/helm/autoload/helm.el
    - Scanning modules/completion/helm/autoload/posframe.el
    - Scanning modules/completion/ivy/autoload/evil.el
    - Scanning modules/completion/ivy/autoload/hydras.el
    - Scanning modules/completion/ivy/autoload/ivy.el
    - Scanning modules/completion/ivy/autoload/posframe.el
    - Scanning modules/config/default/autoload/default.el
    - Scanning modules/config/default/autoload/files.el
    - Scanning modules/config/default/autoload/search.el
    - Scanning modules/config/default/autoload/text.el
    - Scanning modules/config/literate/autoload.el
    - Scanning modules/editor/evil/autoload/advice.el
    - Scanning modules/editor/evil/autoload/embrace.el
    - Scanning modules/editor/evil/autoload/evil.el
    - Scanning modules/editor/evil/autoload/ex.el
    - Scanning modules/editor/evil/autoload/files.el
    - Scanning modules/editor/evil/autoload/textobjects.el
    - Scanning modules/editor/evil/autoload/unimpaired.el
    - Scanning modules/editor/file-templates/autoload.el
    - Scanning modules/editor/fold/autoload/fold.el
    - Scanning modules/editor/fold/autoload/hideshow.el
    - Scanning modules/editor/format/autoload/evil.el
    - Scanning modules/editor/format/autoload/format.el
    - Scanning modules/editor/format/autoload/settings.el
    - Scanning modules/editor/god/autoload.el
    - Scanning modules/editor/multiple-cursors/autoload/evil-mc.el
    - Scanning modules/editor/rotate-text/autoload.el
    - Scanning modules/editor/snippets/autoload/settings.el
    - Scanning modules/editor/snippets/autoload/snippets.el
    - Scanning modules/editor/word-wrap/autoload.el
    - Scanning modules/emacs/dired/autoload.el
    - Scanning modules/emacs/electric/autoload.el
    - Scanning modules/emacs/vc/autoload/hydra.el
    - Scanning modules/emacs/vc/autoload/vc.el
    - Scanning modules/email/mu4e/autoload/email.el
    - Scanning modules/email/mu4e/autoload/evil.el
    - Scanning modules/email/notmuch/autoload.el
    - Scanning modules/email/wanderlust/autoload.el
    - Scanning modules/lang/assembly/autoload.el
    - Scanning modules/lang/cc/autoload.el
    - Scanning modules/lang/clojure/autoload.el
    - Scanning modules/lang/common-lisp/autoload/common-lisp.el
    - Scanning modules/lang/csharp/autoload.el
    - Scanning modules/lang/emacs-lisp/autoload.el
    - Scanning modules/lang/ess/autoload.el
    - Scanning modules/lang/faust/autoload.el
    - Scanning modules/lang/go/autoload.el
    - Scanning modules/lang/haskell/autoload.el
    - Scanning modules/lang/java/autoload.el
    - Scanning modules/lang/javascript/autoload.el
    - Scanning modules/lang/julia/autoload.el
    - Scanning modules/lang/kotlin/autoload.el
    - Scanning modules/lang/latex/autoload.el
    - Scanning modules/lang/lua/autoload/lua.el
    - Scanning modules/lang/lua/autoload/moonscript.el
    - Scanning modules/lang/markdown/autoload.el
    - Scanning modules/lang/nix/autoload.el
    - Scanning modules/lang/ocaml/autoload.el
    - Scanning modules/lang/org/autoload/contrib-dragndrop.el
    - Scanning modules/lang/org/autoload/contrib-ipython.el
    - Scanning modules/lang/org/autoload/contrib-present.el
    - Scanning modules/lang/org/autoload/org-attach.el
    - Scanning modules/lang/org/autoload/org-avy.el
    - Scanning modules/lang/org/autoload/org-capture.el
    - Scanning modules/lang/org/autoload/org-export.el
    - Scanning modules/lang/org/autoload/org-link.el
    - Scanning modules/lang/org/autoload/org-refile.el
    - Scanning modules/lang/org/autoload/org-tables.el
    - Scanning modules/lang/org/autoload/org.el
    - Scanning modules/lang/php/autoload.el
    - Scanning modules/lang/plantuml/autoload.el
    - Scanning modules/lang/python/autoload/conda.el
    - Scanning modules/lang/python/autoload/pyenv.el
    - Scanning modules/lang/python/autoload/python.el
    - Scanning modules/lang/qt/autoload.el
    - Scanning modules/lang/racket/autoload.el
    - Scanning modules/lang/rest/autoload.el
    - Scanning modules/lang/ruby/autoload.el
    - Scanning modules/lang/rust/autoload.el
    - Scanning modules/lang/scala/autoload.el
    - Scanning modules/lang/scheme/autoload.el
    - Scanning modules/lang/sh/autoload.el
    - Scanning modules/lang/terra/autoload.el
    - Scanning modules/lang/web/autoload/css.el
    - Scanning modules/lang/web/autoload/evil.el
    - Scanning modules/lang/web/autoload/html.el
    - Scanning modules/term/eshell/autoload/commands.el
    - Scanning modules/term/eshell/autoload/company.el
    - Scanning modules/term/eshell/autoload/eshell.el
    - Scanning modules/term/eshell/autoload/evil.el
    - Scanning modules/term/eshell/autoload/prompts.el
    - Scanning modules/term/eshell/autoload/settings.el
    - Scanning modules/term/shell/autoload.el
    - Scanning modules/term/term/autoload.el
    - Scanning modules/term/vterm/autoload.el
    - Scanning modules/tools/debugger/autoload/debugger.el
    - Scanning modules/tools/debugger/autoload/evil.el
    - Scanning modules/tools/editorconfig/autoload.el
    - Scanning modules/tools/ein/autoload/ein.el
    - Scanning modules/tools/ein/autoload/hydra.el
    - Scanning modules/tools/eval/autoload/eval.el
    - Scanning modules/tools/eval/autoload/evil.el
    - Scanning modules/tools/eval/autoload/repl.el
    - Scanning modules/tools/eval/autoload/settings.el
    - Scanning modules/tools/gist/autoload/evil.el
    - Scanning modules/tools/lookup/autoload/docsets.el
    - Scanning modules/tools/lookup/autoload/evil.el
    - Scanning modules/tools/lookup/autoload/lookup.el
    - Scanning modules/tools/lookup/autoload/online.el
    - Scanning modules/tools/lsp/autoload.el
    - Scanning modules/tools/macos/autoload.el
    - Scanning modules/tools/magit/autoload.el
    - Scanning modules/tools/make/autoload.el
    - Scanning modules/tools/pass/autoload.el
    - Scanning modules/tools/pdf/autoload/pdf.el
    - Scanning modules/tools/prodigy/autoload.el
    - Scanning modules/tools/rgb/autoload.el
    - Scanning modules/tools/tmux/autoload/evil.el
    - Scanning modules/tools/tmux/autoload/tmux.el
    - Scanning modules/ui/doom-dashboard/autoload.el
    - Scanning modules/ui/fill-column/autoload.el
    - Scanning modules/ui/hydra/autoload/windows.el
    - Scanning modules/ui/modeline/autoload.el
    - Scanning modules/ui/nav-flash/autoload.el
    - Scanning modules/ui/neotree/autoload.el
    - Scanning modules/ui/popup/autoload/popup.el
    - Scanning modules/ui/popup/autoload/settings.el
    - Scanning modules/ui/pretty-code/autoload.el
    - Scanning modules/ui/treemacs/autoload.el
    - Scanning modules/ui/unicode/autoload.el
    - Scanning modules/ui/vc-gutter/autoload.el
    - Scanning modules/ui/vi-tilde-fringe/autoload.el
    - Scanning modules/ui/workspaces/autoload/evil.el
    - Scanning modules/ui/workspaces/autoload/workspaces.el
    > Byte-compiling core autoloads file...

In toplevel form:
autoloads.el:1998:50:Warning: reference to free variable `rotate-text-words'
autoloads.el:1998:50:Warning: assignment to free variable `rotate-text-words'

In end of data:
autoloads.el:3589:1:Warning: the following functions are not known to be
    defined: restart-emacs, +evil/next-end-of-method, +org/toggle-fold,
    +org/close-fold, outline-hide-subtree, multi-term, magit-version,
    doom-modeline-def-modeline, doom-modeline-def-segment,
    doom-modeline-set-modeline, vi-tilde-fringe-mode, +workspace-p,
    perspective-p, +workspace-contains-buffer-p, persp-contain-buffer-p,
    +workspace-current, get-current-persp
    âo" Generated .local/autoloads.elc
  > Installing packages...
    - No packages need to be installed
  > (Re)building packages...
x There was an unexpected error:
  Type: file-error
  Message:
    File error
  Data:
    "Spawning child process"
    "Exec format error"
</pre></details>

**Steps to reproduce:**
1. Install Doom as specified in the getting started guide
2. Uncomment wanted packages
3. Run `doom update` or any of the commands

**System information:**
<details><pre>
((emacs
  (version . "26.3")
  (features . "XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2")
  (build . "Aug 29, 2019")
  (buildopts "--without-dbus --host=x86_64-w64-mingw32 --without-compress-install 'CFLAGS=-O2 -static -g3'")
  (windowsys . batch)
  (daemonp))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD e3d7b2662 2020-02-18 00:20:35 -0500")
  (dir . "c:/Users/nikit/.doom.d/"))
 (system
  (type . windows-nt)
  (config . "x86_64-w64-mingw32")
  (shell . "C:/ProgramData/chocolatey/lib/Emacs/tools/emacs/libexec/emacs/26.3/x86_64-w64-mingw32/cmdproxy.exe")
  (uname . "n/a")
  (path "c:/Program Files/PowerShell/7-preview" "C:/Python38/Scripts/" "C:/Python38/" "C:/ProgramData/Boxstarter" "C:/Windows/system32" "C:/Windows" "C:/Windows/System32/Wbem" "C:/Windows/System32/WindowsPowerShell/v1.0/" "C:/Windows/System32/OpenSSH/" "C:/ProgramData/chocolatey/bin" "C:/Program Files/Microsoft VS Code/bin" "C:/Program Files/Git/cmd" "C:/Program Files/nodejs/" "C:/Program Files/PowerShell/6/" "C:/HashiCorp/Vagrant/bin" "C:/Program Files/PowerShell/7-preview/preview" "C:/Program Files/Docker/Docker/resources/bin" "C:/ProgramData/DockerDesktop/version-bin" "C:/Program Files/OpenJDK/openjdk-11.0.5_10/bin" "C:/Program Files (x86)/sbt/bin" "C:/Program Files/LLVM/bin" "C:/Users/nikit/.cargo/bin" "C:/Users/nikit/AppData/Local/Microsoft/WindowsApps" "C:/Users/nikit/AppData/Roaming/npm" "C:/Users/nikit/AppData/Roaming/local/bin" "C:/Users/nikit/AppData/Roaming/cabal/bin" "C:/ProgramData/chocolatey/lib/ghc.8.6.5/tools/ghc-8.6.5/bin" "C:/tools/msys64" "C:/Users/nikit/bin" "C:/Users/nikit/.emacs.d/bin" "c:/ProgramData/chocolatey/lib/Emacs/tools/emacs/libexec/emacs/26.3/x86_64-w64-mingw32"))
 (config
  (envfile)
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard doom-quit fill-column hl-todo indent-guides modeline nav-flash ophints (popup +all +defaults) pretty-code treemacs unicode vc-gutter vi-tilde-fringe window-select workspaces zen :editor (evil +everywhere) file-templates fold multiple-cursors rotate-text snippets :emacs dired electric ibuffer vc :term term :checkers syntax spell grammar :tools (eval +overlay) (lookup +docsets) magit :lang data emacs-lisp javascript markdown (org +dragndrop +present) sh :config (default +bindings +smartparens))
  (packages . "<(void-function sp-point-in-string)>")
  (elpa "n/a")
  (unpin . "<(void-function sp-point-in-string)>")))
</pre></details>

**Comment by hlissner** [comment]
As of 71e5a55, this issue should hopefully be fixed. Please upgrade and let me know if that isn't the case and I'll reopen the issue.

**Comment by NickSeagull** [comment]
Thank you very much, it fixed it! 😄

**Comment by skywind3000** [comment]
It works on my windows 10. !!

**Comment by Bram-Boris** [comment]
For me it works!
