### ISSUE TITLE
Keybindings for alignment operations

### ISSUE THREAD

**Issue by menelaos** [hlissner/doom-emacs#2559]
What do you think about keybindings à la https://github.com/junegunn/vim-easy-align?

So far, I've found `al` and `ral` in [`modules/editor/evil/+commands.el`](https://github.com/hlissner/doom-emacs/blob/e3d7b2662c3db8dbe0939e1a73923bf1ab2b0c28/modules/editor/evil/%2Bcommands.el#L8), but
they are not quite as convenient.

Similar projects:

https://github.com/godlygeek/tabular
https://github.com/tommcdo/vim-lion

**Comment by hlissner** [comment]
I've got https://github.com/edkolev/evil-lion in my crosshairs, but am currently focused on some big stability updates to `bin/doom`, so it'll be a while until I get there. I'd accept a PR for it.

**Comment by menelaos** [comment]
Thanks a lot!
