### ISSUE TITLE
[HOWTO] Bind `evil-substitute` to `s` in normal mode.

### ISSUE THREAD

**Issue by danielakhterov** [hlissner/doom-emacs#2560]
**What are you trying to achieve?**
I want to bind `s` to `evil-substitute` which is vim's `s` key in normal mode.

**What have you tried?**
```
(map! :n "s" 'evil-substitute)
(map! :gn "s" 'evil-substitute)
(define-key evil-normal-state-map "s" 'evil-substitute)
(define-key! evil-normal-state-map "s" 'evil-substitute)
(map! "s" 'evil-substitute)
(map! :leader :n "s" 'evil-substitute)
```
The first four do not work. The fifth one doesn't work, and it breaks "s" inside the `M-x` prompt. The last one works, however, it is not a simple `s` bind, it's a `<leader>-s` bind which is not what I wanted.

**Additional information**
I'm new to emacs and even more so for doom emacs. Just started learning elisp so I might be doing something stupid that I'm not aware of. Also, the place where I wrote those previous lines is `~/.doom.d/config.el`.

**System information**
<details><pre>
emacs   version    26.3
        features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2
        build      Aug 29, 2019
        buildopts  (--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-modules 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now)
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop, origin/develop, origin/HEAD e3d7b2662 2020-02-18 00:20:35 -0500
        dir        ~/.doom.d/
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /usr/bin/fish
        uname      Linux 5.5.3-zen1-1-zen #1 ZEN SMP PREEMPT Tue, 11 Feb 2020 15:35:45 +0000 x86_64
        path       (~/.ghq/github.com/flutter/flutter/bin ~/go/bin ~/.config/scripts ~/.config/nvm/10.19.0/bin ~/go/bin ~/.fzf/bin ~/.cargo/bin ~/bin ~/.local/bin /usr/local/bin /usr/bin /bin /usr/local/sbin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /var/lib/snapd/snap/bin /usr/lib/emacs/26.3/x86_64-pc-linux-gnu/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard hl-todo modeline nav-flash ophints (popup +all +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold multiple-cursors rotate-text snippets :emacs dired electric ibuffer vc :checkers syntax :tools (eval +overlay) (lookup +docsets) magit :lang data emacs-lisp markdown (org +dragndrop +present) sh :config (default +bindings +smartparens))
        packages   ((lsp-mode) (rust-mode) (web-mode) (typescript-mode) (typescript-mode) (treemacs) (treemacs-projectile))
        elpa       (n/a)
        unpin      (n/a)
</pre></details>

**Comment by danielakhterov** [comment]
Solved by disabling `evil-snipe` with 
```
(after! evil-snipe
  (evil-snipe-mode -1))
```

**Comment by hlissner** [comment]
For posterity, this is documented in the `:editor evil` module's documentation: https://github.com/hlissner/doom-emacs/blob/develop/modules/editor/evil/README.org#restoring-old-substitution-behavior-on-ss
