### ISSUE TITLE
Create nested keybinding in doom keymap

### ISSUE THREAD

**Issue by tavurth** [hlissner/doom-emacs#2567]
**What are you trying to achieve?**
I'd like to be able to add missing keybindings into different areas of the existing keymap.

Example A:
 - I found that a commonly used command `js2-rename-var` was not mapped. 
 - I'd like to put this command under `C-c r` (in javascript mode)

Example B:
 - I found that a commonly used command `mc/mark-all-in-region` is not present
 - I'd like to put this command under `SPC m x`

**What have you tried?**
I need some help on this part

**Additional information**
Available on request

**System information**
<details>

```
emacs   version    26.3
        features   JPEG RSVG IMAGEMAGICK GLIB NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2
        build      Jan 07, 2020
        buildopts  (--disable-dependency-tracking --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-head/26.3_1/share/info/emacs --prefix=/usr/local/Cellar/emacs-head/26.3_1 --without-x --without-dbus --with-imagemagick --with-modules --with-gnutls --with-rsvg --with-xml2 --with-ns --disable-ns-self-contained)
        windowsys  ns
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop, origin/develop, origin/HEAD 92e8521e9 2020-02-16 02:50:52 -0500
        dir        ~/.doom.d/
system  type       darwin
        config     x86_64-apple-darwin18.5.0
        shell      /bin/zsh
        uname      Darwin 18.7.0 Darwin Kernel Version 18.7.0: Sun Dec  1 18:59:03 PST 2019; root:xnu-4903.278.19~1/RELEASE_X86_64 x86_64
        path       (~/.nvm/versions/node/v10.17.0/bin ~/.yarn/bin ~/.config/yarn/global/node_modules/.bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /Library/TeX/texbin /Applications/Wireshark.app/Contents/MacOS ~ /usr/local/Cellar/emacs-head/26.3_1/libexec/emacs/26.3/x86_64-apple-darwin18.5.0/)
config  envfile    envvar-file
        elc-files  10
        modules    (:completion company ivy :ui doom doom-dashboard hl-todo modeline ophints (popup +all +defaults) vc-gutter workspaces :editor file-templates (format +onsave) multiple-cursors rotate-text snippets :emacs dired electric ibuffer vc :checkers syntax :tools (eval +overlay) (lookup +docsets) magit :lang data emacs-lisp javascript markdown (org +dragndrop +present) rest sh :config (default +bindings +smartparens))
        packages   (n/a)
        elpa       (n/a)
        unpin      (n/a)
```
</details>

**Comment by hlissner** [comment]
+ 1062386 fixes the missing js2-refactor keybinds on `SPC m r`.
+ There's an evil-ex command for evil-mc: `:mc REGEXP`, which can be used to create a cursor for every match within a selection. The rest of evil-mc's keybinds are under the `gz` prefix here: <https://github.com/hlissner/doom-emacs/blob/develop/modules/config/default/+evil-bindings.el#L84-L100>

In any case, to answer the general question of binding keys, see `SPC h f map\!` for documentation on the macro and examples of its use. For the particular examples you mentioned:

+ Binding `js2-rename-var` on `C-c r`: 

  ```elisp
  (map! :after js2-mode :map js2-mode-map "C-c r" #'js2-rename-var)
  ```

+ Binding `mc/mark-all-in-region` on `SPC m x`: 

  ```elisp
  (map! :after js2-mode :map js2-mode-map :localleader "x" #'mc/mark-all-in-region)
  ```

**Comment by tavurth** [comment]
> In any case, to answer the general question of binding keys, see `SPC h f map\!` for documentation on the macro and examples of its use. For the particular examples you mentioned:
> 

Wow, thank you for such a fast reply!
This answers my questions, and I'll close this now.

Thanks again! 👍

**Comment by tavurth** [comment]
I was using `rjsx-mode` and the following fixed this for me:

```clisp
(map! :after rjsx-mode :map rjsx-mode-map "C-c C-r" #'js2r-rename-var)
```

**Comment by mhd53** [comment]
Here's an example for adding nested bindings scoped for a specific mode:

```elisp
(map! :after clojure-mode :map clojure-mode-map :localleader
      (:prefix-map ("s" . "add-sibling")
       "c" #'cider-connect-sibling-clj
       "C" #'cider-connect-sibling-cljs))
```

which will map to `SPC m s c` and  `SPC m s C`.
