### ISSUE TITLE
Idea for webpage capture/bookmark

### ISSUE THREAD

**Issue by ghost** [hlissner/doom-emacs#257]
I've been experimenting with org-capture together with Firefox bookmarks lately. By using a Firefox [addon](https://addons.mozilla.org/en-US/firefox/addon/org-capture/?src=ss) and org-protocol, links can easily be send to Emacs. In Emacs, org-capture is opened and I can save the links to a file called "links.org" in my org directory. I've configured Emacs in such a way that "links.org" will automatically be exported to links.html which I've "bookmarked" in Firefox. Furthermore, a package called [org-board ](https://github.com/scallywag/org-board) saves the html+css (using wget) file of my captured webpage, so that I'm able to view my bookmarked website without an internet connection. I've implemented the following code for this system:
```elisp
(require 'org-protocol)

(def-package! org-board
  :commands
  org-board-open
  org-board-archive
  :config
  (setq org-board-capture-file "links.org")
  (setq org-board-default-browser 'firefox)
  )

(defun do-org-board-dl-hook ()
     (when (equal (buffer-name)
             (concat "CAPTURE-" org-board-capture-file))
       (org-board-archive)
       (save-buffer)
       (org-html-export-to-html)
       ))
(add-hook 'org-capture-before-finalize-hook 'do-org-board-dl-hook)

(setq org-capture-templates `(
	("p" "Protocol" entry (file+headline ,(concat org-directory "notes.org") "Inbox")
        "* %^{Title}\nSource: %u, %:link \n #+BEGIN_QUOTE\n%i\n#+END_QUOTE\n\n\n%?")
	("L" "Protocol Link" entry (file+headline ,(concat org-directory "links.org") "Links")
        "* %?[[%:link][%:description]] \nCaptured On: %U")
    ("c" "capture through org protocol" entry
             (file+headline ,org-board-capture-file "Links")
             "* %?[[%:link][%:description]] \n:PROPERTIES:\n:URL: %:link\n:END:\n\n Captured On: %U")
))
```
However, I failed to get this to work your conform coding conventions, but that's mainly a result of my lack of Elisp knowledge. In either case, if you like this implementation, let me know :)

**Comment by hlissner** [comment]
I like the idea. I'll look into this more, closer to the new years. I have big plans for the `org` modules I need to finish before adding to its features.

**Comment by hlissner** [comment]
af4ca97 introduces org-protocol support, which I'll build better org-board/org-capture support onto later. This is a WIP, but for the time being, I'll consider this issue "resolved".
