### ISSUE TITLE
Haskell mode correct way to close repl?

### ISSUE THREAD

**Issue by qcfu-bu** [hlissner/doom-emacs#2571]
I'm currently using the Haskell mode installed through Doom emacs. My issue is that closing the repl using esc triggers a prompt "kill whole session?". Is there a way to get rid of this message or make the repl persistent like utop such that pressing esc accidentally does not kill it?

**Comment by hlissner** [comment]
The lang/ocaml module [has a popup rule to prevent ESC from auto-killing its REPL](https://github.com/hlissner/doom-emacs/blob/develop/modules/lang/ocaml/config.el#L420. You'll need something similar for haskell. I don't know what it's buffer's name is so I'll guess:

```lisp
(after! haskell-mode
  (set-popup-rule! "^\\*haskell repl\\*" :quit nil))
```

**Comment by qcfu-bu** [comment]
Thank you. Just what i was looking for.

**Comment by hlissner** [comment]
Could you share the popup rule that worked for you? I think it'd be good to add it to the `:lang haskell` module.

**Comment by qcfu-bu** [comment]
```
;; haskell-mode
(after! haskell-mode
  (set-popup-rule! "*haskell*" :quit nil))
```
