### ISSUE TITLE
Lispyville issue with terminal scrolling

### ISSUE THREAD

**Issue by bepvte** [hlissner/doom-emacs#2573]
**What did you expect to happen?**
Scrolling in lispyville-mode, in non graphical emacs, should scroll the buffer

**What actually happened?**
Many brackets appear in the buffer

**Additional details:**
- Include a link to your private config
[Here](https://github.com/bepvte/dotfiles/tree/ed738692995f27477bc04b9a325cd99474cf0232/stow/emacs/.doom.d)
- Include screenshots/casts of your issue
[![asciicast](https://asciinema.org/a/303385.svg)](https://asciinema.org/a/303385)
- If you mention key sequences, include what commands they're bound to (use `SPC
  h k KEY` or `C-h h k KEY` to inspect keys).
- Include any warnings or errors logged to \*Messages\* (use `M-x
  view-echo-area-messages` to see it).

<details><pre>
If an error message is involved include a backtrace of it.

How to acquire a backtrace:
https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#how-to-extract-a-backtrace-from-an-error
</pre></details>

**Steps to reproduce:**
1. Enable lispyville in init.el
2. Open emacs in terminal mode
3. Open a lispyville file and try to scroll the terminal (I used gnome-terminal)

**System information:**
<details><pre>
Place the output of `M-x doom/info` or `~/.emacs.d/bin/doom info` here.
<details>

```
emacs   version    26.3
        features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LCMS2
        build      Dec 10, 2019
        buildopts  (--build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-dbus --with-gif --with-jpeg --with-png --with-rsvg --with-tiff --with-xft --with-xpm --with-x-toolkit=gtk3 --with-gpm=no --with-xwidgets --with-modules build_alias=x86_64-redhat-linux-gnu host_alias=x86_64-redhat-linux-gnu 'CFLAGS=-DMAIL_USE_LOCKF -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection' LDFLAGS=-Wl,-z,relro PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig)
        windowsys  nil
        daemonp    nil
doom    version    2.0.9
        build      HEAD -> develop, origin/develop, origin/HEAD 10623868b 2020-02-19 23:41:39 -0500
        dir        ~/dotfiles/stow/emacs/.doom.d/
system  type       gnu/linux
        config     x86_64-redhat-linux-gnu
        shell      /bin/zsh
        uname      Linux 5.5.2-200.fc31.x86_64 #1 SMP Thu Feb 6 17:23:27 UTC 2020 x86_64
        path       (~/.local/bin ~/Android/Sdk/flutter/bin ~/Android/Sdk/build-tools/29.0.2 ~/Android/Sdk/emulator ~/Android/Sdk/platform-tools ~/Android/Sdk/tools/bin ~/Android/Sdk/custom/bin ~/go/bin ~/.cargo/bin /usr/share/Modules/bin /usr/lib64/ccache /usr/local/bin /usr/local/sbin /usr/bin /usr/sbin ~/bin ~/.dotnet/tools /usr/libexec/emacs/26.3/x86_64-redhat-linux-gnu)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline neotree ophints (popup +all +defaults) vc-gutter vi-tilde-fringe window-select workspaces zen :editor (evil +everywhere) file-templates fold (format +onsave) lispy multiple-cursors rotate-text snippets word-wrap :emacs dired electric ibuffer vc :checkers syntax spell :tools editorconfig (eval +overlay) (lookup +docsets) lsp magit rgb :lang (cc +lsp) data emacs-lisp (go +lsp) (javascript +lsp) markdown (org +dragndrop +present) (python +lsp) rest (rust +lsp) web :config (default +bindings +smartparens))
        packages   ((hl-line :disable t) (doom-snippets :ignore t) (lsp-python-ms :disable t) (yasnippet-snippets) (flycheck-package))
        elpa       (n/a)
        unpin      (n/a)
```
</details>
</pre></details>

**Comment by hlissner** [comment]
What do you mean by "scrolling"? With the mouse wheel/trackpad? With `j`/`k`? `C-d`/`C-u`?

**Comment by bepvte** [comment]
Mouse wheel in the terminal window

**Comment by hlissner** [comment]
Turns out this is because lispyville binds `lispyville-wrap-brackets` to `M-[`, which is the escape code terminals receive when you scroll with your mouse in the terminal.

Not sure I can -- or should -- do anything about this, necessarily. Perhaps it should be brought up upstream to be accommodated or documented?

**Comment by noctuid** [comment]
This is keybinding is not created by default, so I'm not going to change it, but I put a note in the readme.

**Comment by hlissner** [comment]
@noctuid Sounds good. Thanks!

@bepvte I've also disabled a few of the extra key themes by default in 84a525a, so I'll consider this resolved. Let me know if that isn't the case and I'll reopen this. Thanks for bringing it to my attention!
