### ISSUE TITLE
Suggested doc blip about installing all-the-icons in Windows

### ISSUE THREAD

**Issue by dstcruz** [hlissner/doom-emacs#2575]
I'm not sure where the best place would be to put this blip in the documentation, but this is what I did to get `all-the-icons` working on Windows -- which doesn't work out of the box.  Maybe under the Windows install section, where there already is some info around setting the `HOME` environment variable? The documentation for `all-the-icons` says:

> For Windows, this function will prompt for a download directory for you to install them manually.

Here are easy steps to get that done

* Start emacs
* M-x all-the-icons-install-fonts

Provide a temp directory where you'd like the fonts to be downloaded (let's call it `$tempFonts`)

Then, using Powershell, you can install them for your user with this:

```
> cd $tempFonts
> $destination = (New-Object -ComObject Shell.Application).Namespace(0x14)
> ls *.ttf | % { $destination.CopyHere($_.FullName, 0x10) }
```

This takes a couple of seconds to complete, and you should see a pop-up for each font telling you that it is being installed.

The magic `0x14` means "the special Fonts folder" (see: https://richardspowershellblog.wordpress.com/2008/03/20/special-folders/)

The magic `0x10` means "Override files" (see: https://docs.microsoft.com/en-us/previous-versions/tn-archive/ee176633(v=technet.10)?redirectedfrom=MSDN)

**Comment by reflog** [comment]
@dstcruz - thanks for the great tip, definitely should be documented

**Comment by hlissner** [comment]
Now that As of 976a601 (and a much earlier commit I don't recall), `doom install` will now let the user know that they must install fonts manually after it is done, and I've also added mention that `M-x all-the-icons-install-font` isn't enough to install fonts on Windows. So I'll consider this resolved. Thanks for bringing this to my attention!
