### ISSUE TITLE
Flags for alternative tab cycling

### ISSUE THREAD

**Issue by carlosdagos** [hlissner/doom-emacs#2576]
By default the [`tabs`](https://github.com/hlissner/doom-emacs/tree/48225b30e8a05d710fe335a021ff47f9506707d2/modules/ui/tabs) module right now uses the `centaur-tabs` default cycling:

https://github.com/ema2159/centaur-tabs/blob/96b7c90bdcb6fe3d7c5146b579ab7b9794c2a17b/centaur-tabs.el#L1158-L1169

Personally, I find this a bit cumbersome, because it requires various keystrokes for a simple tab cycle: `C-c C-left`/`C-C C-right`, etc. 

The Vim Tips Wiki has some options for remapping tab cycling: https://vim.fandom.com/wiki/Alternative_tab_navigation. Perhaps these could be adopted via flags. I find this quite useful (just adapting the _Other Customization_ section).

```lisp
(after! centaur-tabs
  (map! :n "L" 'centaur-tabs-forward)
  (map! :n "H" 'centaur-tabs-backward))
```

This overwrites the default navigation for going to the bottom and top of the screen respectively, which is ok for me because I don't use that at all, but of course that wouldn't be the case for everybody.

Anyway, just my 2c. I think it'd be useful to have options for shorter ways of cycling through tabs :smile: 

Thank you!

**System information**
<details><pre>
((emacs
  (version . "26.3")
  (features . "XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD")
  (build . "Feb 21, 2020")
  (buildopts "--prefix=/nix/store/ycn7v2safrgj6rlmx3z8y5jpyjbzfk3w-emacs-26.3 --disable-build-details --with-modules --with-x-toolkit=gtk3 --with-xft --with-xwidgets CFLAGS=-DMAC_OS_X_VERSION_MAX_ALLOWED=101200")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD 1ab9f8b99 2020-02-19 19:03:46 -0500")
  (dir . "~/.doom.d/"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/run/current-system/sw/bin/fish")
  (uname . "Linux 5.4.17 #1-NixOS SMP Sat Feb 1 09:34:53 UTC 2020 x86_64")
  (path "/nix/store/wkq0zw94mk38i9i1i68xfdgwwk90a3sw-emacs-packages-deps/bin" "~/.opam/4.08.1/bin" "~/bin" "/run/wrappers/bin" "~/.nix-profile/bin" "/etc/profiles/per-user/carlos/bin" "/nix/var/nix/profiles/default/bin" "/run/current-system/sw/bin" "/nix/store/f6y3knf5dr7vh6mx0m6ip4gnchzlzxiz-aspcud-1.9.4/bin" "/nix/store/zg6ipqwambyipywk8qdpzc9ngj3rnn86-unzip-6.0/bin" "/nix/store/a7i4hha4gh7fsbw7bfz51l2dkhgvb59a-curl-7.65.3-bin/bin" "/nix/store/q8ja04gsrymq87p7fp7msnr0qgd5qfzb-bubblewrap-0.3.3/bin" "/nix/store/ibzfa0j7piizpy8a6gfybfmgdlsvh1rp-getconf-1003.1-2008/bin" "~/.local/bin" "~/.bin" "/nix/store/ycn7v2safrgj6rlmx3z8y5jpyjbzfk3w-emacs-26.3/libexec/emacs/26.3/x86_64-pc-linux-gnu"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard doom-quit fill-column hl-todo modeline nav-flash ophints (popup +all +defaults) tabs vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold multiple-cursors rotate-text snippets :emacs dired electric ibuffer vc :checkers syntax :tools (eval +overlay) (lookup +docsets) magit :lang data emacs-lisp haskell markdown nix ocaml (org +dragndrop +present) purescript sh :config (default +bindings +smartparens))
  (packages . "<(void-function sp-point-in-string)>")
  (elpa "n/a")
  (unpin . "<(void-function sp-point-in-string)>")))

</pre></details>

**Comment by hlissner** [comment]
As of 82b1efe I've bound the canonical tab-switching `gt` and `gT` keybinds to `centaur-tabs-{forward,backward}`. For the time being I can't think of any other good keybinds (and not only do I use `H` and `L` a great deal, but they are vim defaults, so I'd rather not replace them).

Anyhow, I'll consider this issue resolved. Thanks for bringing them to my attention!

**Comment by carlosdagos** [comment]
Thanks you for the super fast response @hlissner. Happy with the canonical setting, I’ll give it a go myself and see how it feels to use L and H as per the defaults, might be something to it :) 

Cheers
