### ISSUE TITLE
Evil window across frames

### ISSUE THREAD

**Issue by jerbaroo** [hlissner/doom-emacs#2577]
**Describe the feature**
When enabling the `window-select +numbers` module you can `SPC w 1` to jump to the first buffer, even if in another frame.

It would be fantastic if this cross-frame functionality also worked for the `evil-window-left`, and similar, commands. Such that a user could `SPC w j` to move to a buffer that is on a frame in another monitor.

I realise that based on the configuration of the frames, this may not make sense (where is the next buffer on the left?), but in some configurations, e.g. a fullscreen frame per monitor, it very much does make sense and could speedup movement.

**Comment by barischrooneyj** [comment]
Personal ideal use case: I would rebind `C-j` to `evil-window-left`, and could move between buffers across all monitors really fast.

**Comment by ayyess** [comment]
This can be done with [framemove](https://github.com/emacsmirror/framemove) and `(setq framemove-hook-into-windmove t)` as evil uses windmove [internally](https://github.com/emacs-evil/evil/blob/2bc6ca3587502fde67b93e411e329fc8224c916a/evil-commands.el#L3986).
