### ISSUE TITLE
Inactive TRAMP sessions hangs emacs

### ISSUE THREAD

**Issue by Kitchi** [hlissner/doom-emacs#2578]
If I leave a tramp session inactive for some length of time (~ 20 or 30 mins), emacs basically becomes unresponsive. Holding down C-g doesn't help either. I'm not entirely sure if this is unique to doom-emacs, but tramp didn't bring down emacs in my vanilla config. I do not have a private doom config setup, since I only started using doom a couple of days ago.

**What did you expect to happen?**
...
Emacs stays responsive even if tramp times out

**What actually happened?**
...
No response from emacs, had to kill the process with `kill`, since it wouldn't respond to closing the window via GUI either.

**Steps to reproduce:**
1. SSH into a remote server via tramp
2. Leave the buffer open until tramp goes inactive
3. emacs then becomes unresponsive.

**System information:**
<details><pre>
Package cl is deprecated
((emacs
  (version . "28.0.50")
  (features . "XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD PDUMPER LCMS2 GMP")
  (build . "Feb 20, 2020")
  (buildopts "--build=x86_64-linux-gnu --prefix=/usr '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' --sysconfdir=/etc --localstatedir=/var --disable-silent-rules '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' --disable-maintainer-mode --disable-dependency-tracking --prefix=/usr --sharedstatedir=/var/lib --program-suffix=-snapshot --with-modules=yes --with-x=yes --with-x-toolkit=gtk3 --with-xwidgets=yes 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/emacs-snapshot-W1CepB/emacs-snapshot-99749=. -fstack-protector-strong -Wformat -Werror=format-security' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro'")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD e3d7b2662 2020-02-18 00:20:35 -0500")
  (dir . "~/.doom.d/"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/bin/bash")
  (uname . "Linux 5.3.0-40-generic #32-Ubuntu SMP Fri Jan 31 20:24:34 UTC 2020 x86_64")
  (path "~/src/anaconda3/bin" "~/src/anaconda3/condabin" "~/.local/bin" "~/bin" "/usr/local/sbin" "/usr/local/bin" "/usr/sbin" "/usr/bin" "/sbin" "/bin" "/usr/games" "/usr/local/games" "/snap/bin" "~/stuff/data/casa/casa-pipeline-release-5.6.1-8.el7/bin" "~/bin" "/usr/lib/x86_64-linux-gnu/emacs/28.0.50/x86_64-linux-gnu"))
 (config
  (envfile . envvar-file)
  (elc-files . 1)
  (modules :completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold multiple-cursors rotate-text snippets :emacs dired electric ibuffer vc :checkers syntax :tools (eval +overlay) (lookup +docsets) magit :lang data emacs-lisp markdown (org +dragndrop +present) sh :config (default +bindings +smartparens))
  (packages . "<(void-function sp-point-in-string)>")
  (elpa "n/a")
  (unpin . "<(void-function sp-point-in-string)>")))

</pre></details>

**Comment by Strech** [comment]
I have similar behavior, but with basic workflow. I open 2 workspaces and during `C-x C-...` it hangs, and only `kill` help.

Not sure how to provide more valuable input. Should I try run it in debug mode?

**Comment by Kitchi** [comment]
This problem seems to have disappeared for the moment - I modified my config and ran `doom sync` yesterday, and since then it hasn't been an issue. I'll update here if that changes.

**Comment by Kitchi** [comment]
False positive - the problem has resurfaced, where an inactive SSH session completely hangs emacs and has to be `kill`ed. Likewise - any assistance on what information would be useful is great.

**Comment by hlissner** [comment]
I'm told that the common cause for this is that the remote host has an unconventional prompt, and setting your prompt to `$ ` when `$TERM == "dumb"` in your shell config (on the remote machine(s)) should fix it. e.g.

```sh
if [[ "$TERM" == "dumb" ]]; then
  unset zle_bracketed_paste
  unset zle
  PS1='$ '
  return
fi
```

Could you give that a try?

**Comment by Kitchi** [comment]
@hlissner Thanks for the suggestion! I'm going to cautiously say it's worked, but I haven't tested it out too much to confirm. The prompt on the remote was the standard CentOS bash prompt, but maybe tramp had some trouble with it.

**Comment by Kitchi** [comment]
@hlissner The issue seems to be resolved most of the time with that change, which is a huge improvement! I notice now that when emacs tends to hang, there are a lot of `anaconda` processes hanging about. 

I suspect that anaconda-mode might be the issue preventing me from `C-g`-ing my way out of a hung TRAMP session. The list of processes is below, if that helps. Happy to help with further debugging.

```
krishna@compesh:~$ ps ax | grep emacs
  583 pts/14   S+     0:00 /home/krishna/src/anaconda3/bin/python3 /home/krishna/.emacs.d/.local/etc/anaconda/0.1.13/jedi-0.16.0-py3.7.egg/jedi/inference/compiled/subprocess/__main__.py /home/krishna/.emacs.d/.local/etc/anaconda/0.1.13/parso-0.6.0-py3.7.egg 3.7.6
 1484 pts/14   S+     0:00 /home/krishna/src/anaconda3/bin/python3 /home/krishna/.emacs.d/.local/etc/anaconda/0.1.13/jedi-0.16.0-py3.7.egg/jedi/inference/compiled/subprocess/__main__.py /home/krishna/.emacs.d/.local/etc/anaconda/0.1.13/parso-0.6.0-py3.7.egg 3.7.6
 2954 pts/14   S+     0:00 /home/krishna/src/anaconda3/bin/python3 /home/krishna/.emacs.d/.local/etc/anaconda/0.1.13/jedi-0.16.0-py3.7.egg/jedi/inference/compiled/subprocess/__main__.py /home/krishna/.emacs.d/.local/etc/anaconda/0.1.13/parso-0.6.0-py3.7.egg 3.7.6
 3325 pts/14   S+     0:00 /home/krishna/src/anaconda3/bin/python3 /home/krishna/.emacs.d/.local/etc/anaconda/0.1.13/jedi-0.16.0-py3.7.egg/jedi/inference/compiled/subprocess/__main__.py /home/krishna/.emacs.d/.local/etc/anaconda/0.1.13/parso-0.6.0-py3.7.egg 3.7.6
 3598 pts/14   S+     0:00 /home/krishna/src/anaconda3/bin/python3 /home/krishna/.emacs.d/.local/etc/anaconda/0.1.13/jedi-0.16.0-py3.7.egg/jedi/inference/compiled/subprocess/__main__.py /home/krishna/.emacs.d/.local/etc/anaconda/0.1.13/parso-0.6.0-py3.7.egg 3.7.6
 3722 ?        Sl     6:06 /usr/bin/emacs-snapshot
10331 ?        Rl     8:48 /usr/bin/emacs-snapshot
16564 pts/7    S+     0:00 grep --color=auto emacs
31717 pts/14   Ssl+   0:05 /home/krishna/src/anaconda3/bin/python3 -c  from __future__ import print_function  # CLI arguments.  import sys  assert len(sys.argv) > 3, 'CLI arguments: %s' % sys.argv  server_directory = sys.argv[-3] server_address = sys.argv[-2] virtual_environment = sys.argv[-1]  # Ensure directory.  import os  server_directory = os.path.expanduser(server_directory) virtual_environment = os.path.expanduser(virtual_environment)  if not os.path.exists(server_directory):     os.makedirs(server_directory)  # Installation check.  jedi_dep = ('jedi', '0.13.0') service_factory_dep = ('service_factory', '0.1.5')  missing_dependencies = []  def instrument_installation():     for package in (jedi_dep, service_factory_dep):         package_is_installed = False         for path in os.listdir(server_directory):             path = os.path.join(server_directory, path)             if path.endswith('.egg') and os.path.isdir(path):                 if path not in sys.path:                     sys.path.insert(0, path)                 if package[0] in path:                     package_is_installed = True         if not package_is_installed:             missing_dependencies.append('>='.join(package))  instrument_installation()  # Installation.  def install_deps():     import site     import setuptools.command.easy_install     site.addsitedir(server_directory)     cmd = ['--install-dir', server_directory,            '--site-dirs', server_directory,            '--always-copy','--always-unzip']     cmd.extend(missing_dependencies)     setuptools.command.easy_install.main(cmd)     instrument_installation()  if missing_dependencies:     install_deps()  del missing_dependencies[:]  try:     import jedi except ImportError:     missing_dependencies.append('>='.join(jedi_dep))  try:     import service_factory except ImportError:     missing_dependencies.append('>='.join(service_factory_dep))  # Try one more time in case if anaconda installation gets broken somehow if missing_dependencies:     install_deps()     import jedi     import service_factory  # Setup server.  assert jedi.__version__ >= jedi_dep[1], 'Jedi version should be >= %s, current version: %s' % (jedi_dep[1], jedi.__version__,)  if virtual_environment:     virtual_environment = jedi.create_environment(virtual_environment, safe=False) else:     virtual_environment = None  # Define JSON-RPC application.  import functools import threading  def script_method(f):     @functools.wraps(f)     def wrapper(source, line, column, path):         timer = threading.Timer(30.0, sys.exit)         timer.start()         result = f(jedi.Script(source, line, column, path, environment=virtual_environment))         timer.cancel()         return result     return wrapper  def process_definitions(f):     @functools.wraps(f)     def wrapper(script):         definitions = f(script)         if len(definitions) == 1 and not definitions[0].module_path:             return '%s is defined in %s compiled module' % (                 definitions[0].name, definitions[0].module_name)         return [[definition.module_path,                  definition.line,                  definition.column,                  definition.get_line_code().strip()]                 for definition in definitions                 if definition.module_path] or None     return wrapper  @script_method def complete(script):     return [[definition.name, definition.type]             for definition in script.completions()]  @script_method def company_complete(script):     return [[definition.name,              definition.type,              definition.docstring(),              definition.module_path,              definition.line]             for definition in script.completions()]  @script_method def show_doc(script):     return [[definition.module_name, definition.docstring()]             for definition in script.goto_definitions()]  @script_method @process_definitions def goto_definitions(script):     return script.goto_definitions()  @script_method @process_definitions def goto_assignments(script):     return script.goto_assignments()  @script_method @process_definitions def usages(script):     return script.usages()  @script_method def eldoc(script):     signatures = script.call_signatures()     if len(signatures) == 1:         signature = signatures[0]         return [signature.name,                 signature.index,                 [param.description[6:] for param in signature.params]]  # Run.  app = [complete, company_complete, show_doc, goto_definitions, goto_assignments, usages, eldoc]  service_factory.service_factory(app, server_address, 0, 'anaconda_mode port {port}')  ~/.emacs.d/.local/etc/anaconda/0.1.13 127.0.0.1
32311 pts/14   S+     0:00 /home/krishna/src/anaconda3/bin/python3 /home/krishna/.emacs.d/.local/etc/anaconda/0.1.13/jedi-0.16.0-py3.7.egg/jedi/inference/compiled/subprocess/__main__.py /home/krishna/.emacs.d/.local/etc/anaconda/0.1.13/parso-0.6.0-py3.7.egg 3.7.6
```

**Comment by eribertt** [comment]
Just recently i got myself connecting to remote server doom tramp mode and experienced this issue as well. After some gap of inactivity it took a good 5 minutes or so for emacs to become responsive again. I dont know if running a script in the remote shell sort of a loop ping to keep the activity will work. In my dot ssh/config file i keep ServerAliveInterval value to 5 but doesnt seem to improve things.

**Comment by edwin-koh** [comment]
I have the same problem. If the server goes down, the entire emacs will stop. Even C-g doen's work.

I got following message buffer.
`
Quit
QuitError during redisplay: (eval (doom-modeline-segment--buffer-info)) signaled (quit "")
Error during redisplay: (eval (doom-modeline-segment--buffer-info)) signaled (quit "")
Quit
Process has died
Tramp: Opening connection for root@192.168.0.29 using ssh...
Tramp: Sending command ‘exec ssh -l root  -o ControlMaster=auto -o ControlPath='tramp.%C' -o ControlPersist=no -e none 192.168.0.29’
Tramp: Waiting for prompts from remote shell...failed
Tramp: Opening connection for root@192.168.0.29 using ssh...failed
Cleaning up the recentf list...
File /ssh:root@192.168.0.29:/xxx removed from the recentf list
File ~/xxxxx removed from the recentf list
Error during redisplay: (eval (doom-modeline-segment--buffer-info)) signaled (quit "")
Tramp: Opening connection for root@192.168.0.29 using ssh...`

**Comment by dapritchard** [comment]
I am having the same issue.  Emacs goes into a period of high CPU activity for 5-10 minutes and then becomes responsive again.  Interestingly, I had two Emacs sessions connected to the same server, and both hung at the same time, and then both became responsive again at about the same time.

Using `sudo pkill -SIGUSR2 emacs` in the terminal doesn't seem to help, but when Emacs did come back I had the following backtrace.  (This backtrace seems very typical when it does happen.)
```
Debugger entered--entering a function:
* tramp-signal-hook-function(quit nil)
  tramp-get-connection-property(#<process *tramp/ssh test.stat.novisci.internal*> "check-remote-echo" nil)
  tramp-check-for-regexp(#<process *tramp/ssh test.stat.novisci.internal*> "\\(^\\|\0\\)[^#$\n]*///e1491450520ad247f723a2baea851150...")
  tramp-wait-for-regexp(#<process *tramp/ssh test.stat.novisci.internal*> nil "\\(^\\|\0\\)[^#$\n]*///e1491450520ad247f723a2baea851150...")
  tramp-wait-for-output(#<process *tramp/ssh test.stat.novisci.internal*>)
  tramp-send-command((tramp-file-name "ssh" nil nil "test.stat.novisci.internal" nil "/share/projects/P0025/users/dpritchard/R/analy-est..." nil) "/usr/bin/test -e /share/projects/P0025/users/dprit...")
  tramp-send-command-and-check((tramp-file-name "ssh" nil nil "test.stat.novisci.internal" nil "/share/projects/P0025/users/dpritchard/R/analy-est..." nil) "/usr/bin/test -e /share/projects/P0025/users/dprit...")
  tramp-sh-handle-file-exists-p("/ssh:test.stat.novisci.internal:/share/projects/P0...")
  apply(tramp-sh-handle-file-exists-p "/ssh:test.stat.novisci.internal:/share/projects/P0...")
  tramp-sh-file-name-handler(file-exists-p "/ssh:test.stat.novisci.internal:/share/projects/P0...")
  apply(tramp-sh-file-name-handler file-exists-p "/ssh:test.stat.novisci.internal:/share/projects/P0...")
  tramp-file-name-handler(file-exists-p "/ssh:test.stat.novisci.internal:/share/projects/P0...")
  file-exists-p("/ssh:test.stat.novisci.internal:/share/projects/P0...")
  doom-modeline-update-buffer-file-state-icon()
  doom-modeline-segment--buffer-info()
  eval((doom-modeline-segment--buffer-info))
  redisplay_internal\ \(C\ function\)()
```

**Comment by hlissner** [comment]
Judging from these error logs, it seems the issue is originating from the doom-modeline plugin. I'd recommend reporting it [upstream](https://github.com/seagle0128/doom-modeline) (I do not maintain that package).

**Comment by mathrick** [comment]
This also reliably breaks TRAMP on `sudo:` paths. It hangs with `Tramp: Opening connection for root@megumi using sudo...` forever. I can get out of it using <kbd>C-g</kbd>, but it renders `sudo:` unusable. Switching to light modeline fixes it.

**Comment by mathrick** [comment]
Actually, now that I went back to `doom-modeline` to verify things for the bug report, it works even after I re-enabled it and re-ran `doom sync`. I'm confused, but it seems to work fine now.

**Comment by verbal007** [comment]
> I'm told that the common cause for this is that the remote host has an unconventional prompt (which tramp can't parse), and setting your prompt to `$ ` when `$TERM == "dumb"` in your shell config (on the remote machine(s)) should fix it. e.g.

Your suggestion worked for me, **HOWEVER** I think my issue is different than what @Kitchi is experiencing, as I was trying to establish an **_initial_** connection which was hanging and eventually timing out.

**Comment by hlissner** [comment]
Is the original issue still occuring @Kitchi? I cannot reproduce it, so I figure it must've been resolved at some point upstream.

**Comment by Kitchi** [comment]
@hlissner It hasn't happened in quite some time, so I guess it must have resolved itself! Thanks your help!
