### ISSUE TITLE
Follow the `lsp-mode` performance guide?

### ISSUE THREAD

**Issue by sebastiansturm** [hlissner/doom-emacs#2589]
I'm planning to open a PR that replaces `company-lsp` with `lsp-mode`'s new `capf` backend. According to the `lsp-mode` performance guide (https://github.com/emacs-lsp/lsp-mode#performance), this should offer performance benefits over `company-lsp`.

While reading that performance guide, I noticed it also recommends increasing `read-process-output-max` from its default value of 4KB. Does it make sense to increase this parameter in general, even if the `lsp` module is not in use, or are there good reasons not to do so?

**Comment by hlissner** [comment]
Following that guide sounds like a fantastic idea. I'm all for it. I'm linking #2590 here for posterity. Please continue this conversation there -- I've responded wrt `read-process-output-max` there.
