### ISSUE TITLE
"Tailored for Arch and OSX?"

### ISSUE THREAD

**Issue by a-schaefers** [hlissner/doom-emacs#259]
Hi,

On the readme it states, 

> Important: Doom only supports Emacs >= 25.1, and is tailored for Arch Linux 4.7+ and Mac OS 10.11+.

I have skimmed the rest of the readme and main sections of the Wiki and am unable to see exactly how it has been tailored for Arch and OSX. In what ways has it been tailored for Arch and OSX that do not apply to other Linux distros or operating sytems like the BSD family?

As a FreeBSD and Spacemacs user, I was interested in also trying out your doom configuration, but am also hesitant as I am not sure if my operating system is supported? I also am curious how other Linux distro users would take this statement to mean?

Thank you.

**Comment by Dragnucs** [comment]
The assertion in question can be viewed as "Tested on macOs and Arch Linux". This does not mean it will not work on other platforms or it is strictly tied to them. The config can also work on windows and Unix based or UNIX like OSs.

**Comment by hlissner** [comment]
It's mostly a disclaimer. There is no particular reason that it wouldn't work on any distro, or even Windows. It's simply that I only use Arch and MacOS, and can't reliably test on any other system. Although, you'll find documentation for modules only include instructions for Arch Linux and MacOS (if any).

If it helps, you can do an isolated test-run of Doom with, say:

```sh
cd ~/test-emacs
make run
```

**Comment by a-schaefers** [comment]
Thank you. May I suggest a slight clarity edit on this wording. Only because I suspect there are others like me from the vim world who are also new to emacs and may have a similar question, or may even turn the other way when it may be taken as "Arch and OSX only" =)

Cheers

**Comment by hlissner** [comment]
No problem, and will do!
