### ISSUE TITLE
When enabling the workspace module, the projectile-after-switch-project-hook stops working.

### ISSUE THREAD

**Issue by patgro1** [hlissner/doom-emacs#2591]
When setuping projectile I am using the following code snippet.
```(after! projectile
  (setq projectile-indexing-mode 'alien
        projectile-project-search-path '("~/workspace")))
(defun setup_env ()
  (interactive )
  (message "In setup env"))
(add-hook! 'projectile-after-switch-project-hook #'setup_env)
```

When using enabling the workspace module, the setup_env function is never called when switching project. When I disable it, the "In setup env" message is now showed in the message buffer when switching project.

Here is my doom/info WITH the enabled workspace module.
https://pastebin.com/KW34kZ0p

**Comment by hlissner** [comment]
As of https://github.com/hlissner/doom-emacs/commit/8049914e0ed85dd32f79650fa140ea4a6c8d62c9 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by nl5887** [comment]
After e220549bb884c0b08a76096698066e0f7d67ecc0 the find file isn't being executed anymore after switching projects (helm-projectile-switch-project ).
