### ISSUE TITLE
After python project switch, find file popup won't close

### ISSUE THREAD

**Issue by OwenPriceSkelly** [hlissner/doom-emacs#2595]
**What did you expect to happen?**
After opening a python project "SPC p p" the usual popup appears to select a file from the project. when selecting a python file, the cursor moves to the file buffer.

**What actually happened?**
When selecting a python file, the cursor moves to the file buffer (as expected) but instead of closing, the find-file popup is replaced by an LSP "mspyls is analyzing" message before returning to a reopened active find-file minibuffer. 
Any subsequent key presses are stuck in the minibuffer which seems unable to close--I can open any other project files the way I normally would (navigating to the filename and pressing RET) but the minibuffer never closes. 
If I click the file buffer the cursor will update, but I can't close the minibuffer window. 

**System information:**
<details><pre>
((emacs
  (version . "26.3")
  (features . "XPM TIFF GIF PNG SOUND GSETTINGS GLIB NOTIFY FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK2 X11 XDBE XIM THREADS")
  (build . "Feb 17, 2020")
  (buildopts "--with-jpeg=no --with-gnutls=no")
  (windowsys . batch)
  (daemonp))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD a426b7350 2020-02-24 20:55:45 -0500")
  (dir . "~/.doom.d/"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/bin/bash")
  (uname . "Linux 4.14.165-133.209.amzn2.x86_64 #1 SMP Sun Feb 9 00:21:30 UTC 2020 x86_64")
  (path "~/.pyenv/shims" "~/.pyenv/bin" "~/.emacs.d/bin" "~/.pyenv/shims" "~/.pyenv/bin" "~/.emacs.d/bin" "/usr/local/bin" "/usr/bin" "/bin" "/sbin" "/usr/local/sbin" "/usr/sbin" "~/.local/bin" "~/bin" "/usr/local/libexec/emacs/26.3/x86_64-pc-linux-gnu"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company (ivy +fuzzy +prescient) :ui deft doom doom-dashboard fill-column hl-todo hydra indent-guides modeline nav-flash ophints treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +commands +everywhere) file-templates fold (format +onsave) multiple-cursors parinfer rotate-text snippets word-wrap :emacs (dired +ranger +icons) electric (ibuffer +icons) vc :term eshell shell :checkers (syntax +childframe) :tools docker ein (eval +overlay) (lookup +docsets) lsp macos magit rgb terraform :lang data emacs-lisp latex markdown (org +dragndrop +present) (python +ipython +pyenv +lsp) rest (sh +fish) :app calendar :config (default +bindings +smartparens))
  (packages . "<(void-function sp-point-in-string)>")
  (unpin "n/a")
  (elpa "n/a")))

</pre></details>

**Comment by hlissner** [comment]
With e220549 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by OwenPriceSkelly** [comment]
That fixed it! Thank you so much. I'm beyond impressed with how quickly you took care of this -- I went to the bathroom and came back and it was fixed lol
