### ISSUE TITLE
doom-modeline-icon: Wrong type argument: stringp, all-the-icons-dsilver

### ISSUE THREAD

**Issue by mattsawyer77** [hlissner/doom-emacs#2597]
**What did you expect to happen?**
I expected to be able to edit files :)

**What actually happened?**
I saw the error: `doom-modeline-icon: Wrong type argument: stringp, all-the-icons-dsilver`, and was unable to open any projects or files.

**Additional details:**
- tried pressing `SPC p p` to open a project
- tried pressing `:` to run an ex command
- tried pressing `SPC :` to execute an emacs function
- tried cleaning out doom repo entirely and reinstalling, but it didn't help. 
No stack trace visible, even with `--debug-init`. 

**Workaround:**
I took a guess on a previous good commit and did `git reset --hard f55bcdfd3`. This appears to avoid the problem.

**Steps to reproduce:**
1. from develop branch, run `bin/doom upgrade` (upgraded to commit 981ed73e6)
2. start emacs
3. try to open a project or edit a file as mentioned above

**System information:**
I'm seeing this on emacs 26.3 in both my Linux machine and my Macbook Pro. Let me know if you need any further info to diagnose.

**Comment by hlissner** [comment]
I cannot reproduce this, on 981ed73 or newer. Looks like you didn't include your `M-x doom/info`, so I can't guess much else. 

1. Please run `doom upgrade` to make sure you're on the latest, and have the latest version of doom-modeline installed.
2. Run `doom build` to ensure your packages are correctly built.

**Comment by mattsawyer77** [comment]
I traced it down to this from my config:

```elisp
(setq doom-modeline-major-mode-icon t)
```
When I comment that out, everything is fine. I saw another similar var which was set to true by default: `doom-modeline-major-mode-icon`. Are these mutually exclusive?

Anyhow, sorry for the incomplete bug report earlier but thanks for your fast response!
