### ISSUE TITLE
Symbol's value as variable is void: doom-scratch-buffer-major-mode

### ISSUE THREAD

**Issue by ocharles** [hlissner/doom-emacs#2607]
**What did you expect to happen?**

The scratch buffer would popup.

**What actually happened?**

The error in the title is thrown.

**Additional details:**

<details><pre>
Debugger entered--Lisp error: (void-variable doom-scratch-buffer-major-mode)
  (eq doom-scratch-buffer-major-mode t)
  (cond ((eq doom-scratch-buffer-major-mode t) (if (or buffer-read-only (derived-mode-p (quote special-mode)) (string-match-p "^ ?\\*" (buffer-name))) nil major-mode)) ((null doom-scratch-buffer-major-mode) nil) ((symbolp doom-scratch-buffer-major-mode) doom-scratch-buffer-major-mode))
  (doom-scratch-buffer (cond ((eq doom-scratch-buffer-major-mode t) (if (or buffer-read-only (derived-mode-p (quote special-mode)) (string-match-p "^ ?\\*" (buffer-name))) nil major-mode)) ((null doom-scratch-buffer-major-mode) nil) ((symbolp doom-scratch-buffer-major-mode) doom-scratch-buffer-major-mode)) default-directory (if project-p (progn (doom-project-name))))
  (funcall (if arg (function switch-to-buffer) (function pop-to-buffer)) (doom-scratch-buffer (cond ((eq doom-scratch-buffer-major-mode t) (if (or buffer-read-only (derived-mode-p (quote special-mode)) (string-match-p "^ ?\\*" (buffer-name))) nil major-mode)) ((null doom-scratch-buffer-major-mode) nil) ((symbolp doom-scratch-buffer-major-mode) doom-scratch-buffer-major-mode)) default-directory (if project-p (progn (doom-project-name)))))
  (let (projectile-enable-caching) (funcall (if arg (function switch-to-buffer) (function pop-to-buffer)) (doom-scratch-buffer (cond ((eq doom-scratch-buffer-major-mode t) (if (or buffer-read-only (derived-mode-p ...) (string-match-p "^ ?\\*" ...)) nil major-mode)) ((null doom-scratch-buffer-major-mode) nil) ((symbolp doom-scratch-buffer-major-mode) doom-scratch-buffer-major-mode)) default-directory (if project-p (progn (doom-project-name))))))
  doom/open-scratch-buffer(nil)
  funcall-interactively(doom/open-scratch-buffer nil)
  call-interactively(doom/open-scratch-buffer nil nil)
  command-execute(doom/open-scratch-buffer)

</pre></details>

**Steps to reproduce:**

1. Open emacs
2. From the dashboard, press: `SPC x`
3. The error is thrown.

**System information:**
<details><pre>
Loading /nix/store/527r011zvqrrq2vha95wd5gcz5zqffcy-emacs-26.3/share/emacs/site-lisp/site-start.el (source)...
((emacs
  (version . "26.3")
  (features . "XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD")
  (build . "Feb 26, 2020")
  (buildopts "--prefix=/nix/store/527r011zvqrrq2vha95wd5gcz5zqffcy-emacs-26.3 --disable-build-details --with-modules --with-x-toolkit=gtk3 --with-xft CFLAGS=-DMAC_OS_X_VERSION_MAX_ALLOWED=101200")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop 78b4c6c5d 2020-02-25 22:35:58 -0500")
  (dir . "~/sync/dotfiles/doom-emacs/"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/run/current-system/sw/bin/fish")
  (uname . "Linux 4.19.101 #1-NixOS SMP Sat Feb 1 09:37:12 UTC 2020 x86_64")
  (path "/nix/store/3nrf4wyzbnr3gi1d6sy7bpla9ycwv9hb-emacs-packages-deps/bin" "~/bin" "/run/wrappers/bin" "~/.nix-profile/bin" "/etc/profiles/per-user/ollie/bin" "/nix/var/nix/profiles/default/bin" "/run/current-system/sw/bin" "/nix/store/527r011zvqrrq2vha95wd5gcz5zqffcy-emacs-26.3/libexec/emacs/26.3/x86_64-pc-linux-gnu"))
 (config
  (envfile)
  (elc-files . 0)
  (modules :completion (company +childframe) (ivy +icons +prescient) :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) treemacs vc-gutter (window-select +switch-window) workspaces :editor (evil +everywhere) file-templates fold rotate-text :emacs dired electric ibuffer vc :term vterm :checkers (syntax +childframe) :tools direnv (lookup +docsets) lsp magit :lang data (elm +lsp) emacs-lisp (haskell +lsp) javascript markdown nix (org +attach +babel +capture +export +present) rst sh :config (default +bindings +smartparens))
  (packages . "<(void-function sp-point-in-string)>")
  (unpin "n/a")
  (elpa "n/a")))
</pre></details>

**Comment by binjo** [comment]
I think this commit leads the exception.
https://github.com/hlissner/doom-emacs/commit/9fa76836c10db1824b9d742cb3e9c666c89ff188

restore the variable might be the workaround for now...
```(setq doom-scratch-buffer-major-mode nil)```

**Comment by hlissner** [comment]
My bad. With e53ebcb this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
