### ISSUE TITLE
vterm buffer not updating contents & +vterm/here opens in popup

### ISSUE THREAD

**Issue by Shooooooooo** [hlissner/doom-emacs#2608]
I am not entirely sure whether this is an upstream issue or not, but I will post it here anyway until we understand this issue.

EDIT1: Just tried vterm in a vanilla emacs and doom-emacs without personal config, I can confirm this is not related to vterm or my personal config, at least not directly. Are you aware of any popup related change that may cause these 2 issues?
EDIT2: Looks like this is not an issue specific to vterm, but popup buffer in general, doing grep in emacs also has the same symptom. (The buffer is not updating itself unless I gave some input)

**What did you expect to happen?**
Before update, I was able to use vterm normally in terminal Emacs without evil mode.
The default keybinding C-c o t toggles popup vterm. C-c o T to open a new vterm.

**What actually happened?**
After I did an update today, 2 things no longer work for me.

1. If I open a file with emacs -nw <filename>, then open vterm by C-c o t and run a long job. (e.g. compile a project), vterm will stop updating buffer after about 1 second. And it will no longer update its content unless some input was pressed.
I don't have this issue if: I start emacs without a filename in the argument, or if I use emacs in GUI mode.

2. Also, C-c o T does not do what it supposed to anymore - "Open vterm here", it now also pops vterm into the popup buffer like C-c o t does. Not sure if this is a bug or not but I don't like the new behavior.

**Comment by aidermoi** [comment]
I may have found the issue myself..
I have enabled centaur-tabs / tabs module for my doom-emacs.
The package itself does not support no-window mode and its occupied with updating warning messages.
It would be nice if doom-emacs can by default disable centaur-tabs in no-window mode until maybe it is supported one day in the upstream.
I will disable this module in my config for now.

**Comment by AdamMarkowski** [comment]
Regarding second point - it seems it's caused by newest version of the emacs-vterm package. 
Bringing the previous versions fix the `+vterm/here` issue.

You may bring the previous version by:
`git checkout 5b242c73bbc2236bf1176b561b1d9d53cb2a2440 -- modules/term/vterm/packages.el`
then:
`bin/doom update`

**Comment by aidermoi** [comment]
Thanks @AdamMarkowski 
Since work around has been provided, closing this issue.

**Comment by hlissner** [comment]
A workaround isn't a substitute for a solution.

> The package itself does not support no-window mode and its occupied with updating warning messages.

@aidermoi This isn't easy to do when we have to accommodate daemon users. Daemon users can open terminal frames next to GUI frames, if they wanted, so there is no trivial way to disable centaur-tabs for no-window mode without polling every time the user enters the window, so I'll leave it to users to disable the features that don't work for their use case.

> Regarding the second point - it seems it's caused by the newest version of the emacs-vterm package.
Bringing the previous versions fixing the +vterm/here issue.

@AdamMarkowski Is this still the case on the latest commit of Doom?

**Comment by hlissner** [comment]
I've fixed the issue to `C-c o T`, but cannot reproduce the redrawing issue. I cannot reproduce the redrawing issue, however and have no other leads to go on. Please include your `M-x doom/info` (always include it please).

**Comment by seanfarley** [comment]
Can confirm this is a working solution for me!

**Comment by aidermoi** [comment]
Ok. Will do.
About the redraw issue, maybe I should be more clear. The redraw issue was coming from centaur-tabs itself. (It was doing some polling action with tons of errors, which may hault buffer refresh of other buffers) Turning it off resolved the redraw issue.
