### ISSUE TITLE
Can't open a projectile project w/ workspaces

### ISSUE THREAD

**Issue by jsravn** [hlissner/doom-emacs#2609]
I just updated my doom, and can no longer open projects from a fresh start.

**What did you expect to happen?**

It should open up a project in a workspace when doing `SPC-p-p` and selecting a project.

**What actually happened?**

`SPC-p-p`, select project and press enter. Nothing happens. No errors either.

**System information:**
<details>

```
emacs   version    26.3
        features   JPEG RSVG IMAGEMAGICK GLIB NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2
        build      Nov 17, 2019
        buildopts  (--disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus/26.3/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus/26.3 --with-xml2 --without-dbus --with-gnutls --with-imagemagick --with-modules --with-rsvg --with-ns --disable-ns-self-contained)
        windowsys  ns
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop 78b4c6c5d 2020-02-25 22:35:58 -0500
        dir        ~/.doom.d/
system  type       darwin
        config     x86_64-apple-darwin19.0.0
        shell      /bin/zsh
        uname      Darwin 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64
        path       (~/.pyenv/shims ~/.jabba/jdk/1.13.0-2/Contents/Home/bin ~/.pyenv/bin ~/.cargo/bin ~/.cabal/bin ~/.local/bin ~/go/bin ~/godev/bin ~/.emacs.d/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /Applications/Wireshark.app/Contents/MacOS ~/.pyenv/shims ~/.pyenv/bin ~/.cargo/bin ~/.cabal/bin ~/.local/bin ~/go/bin ~/godev/bin ~/.emacs.d/bin /usr/local/Cellar/emacs-plus/26.3/libexec/emacs/26.3/x86_64-apple-darwin19.0.0/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company helm :ui doom doom-dashboard doom-quit fill-column hl-todo modeline nav-flash ophints (popup +all +defaults) (pretty-code +pragmata-pro) treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) fold format multiple-cursors rotate-text snippets :emacs dired electric ibuffer vc :term term :checkers syntax :tools ansible docker editorconfig (eval +overlay) (lookup +docsets) lsp magit make terraform :lang data emacs-lisp (go +lsp) (java +lsp) javascript markdown (org +dragndrop +journal +pandoc +present) (python +lsp +pyenv) (scala +lsp) sh :config (default +bindings +smartparens))
        packages   ((magit-todos :disable t) (org-journal))
        unpin      (n/a)
        elpa       (n/a)
```
</details>

**Comment by EinarElen** [comment]
I have the same issue. Just tested without any of my own .doom.d and reinstalling doom from scratch. Switching from Ivy to Helm is the only thing you need to do to hit the bug. 

System info:
<details>
Im not sure hot jsravn formatted his so I just extracted some of the output of doom info. Can add more if necessary.
Emacs version "28.0.50"
 Features  "XPM JPEG TIFF GIF PNG RSVG CAIRO IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP"
Doom version 2.0.9, build HEAD -> develop, origin/develop, origin/HEAD 39a12861f 2020-02-26 13:02:19 -0500
Fedora 31
</details>

**Comment by jsravn** [comment]
I suspect #2591 broke it. I downgraded to the prior commit (`git checkout d6c81b687 && doom refresh`) and it's working again.

**Comment by nl5887** [comment]
Bisected the issue and it is related to commit e220549bb884c0b08a76096698066e0f7d67ecc0 (within #2591).

**Comment by hlissner** [comment]
Sorry about that, helm users! As of 5cc2bef this should be fixed. Let me know if that isn't the case and I'll reopen this. Thanks for bringing it to my attention!
