### ISSUE TITLE
Popup manager in its own repo

### ISSUE THREAD

**Issue by amosbird** [hlissner/doom-emacs#261]
Hi, is there a plan to do this modularization? This popup stuff brings many headaches to me and I'd like to disable it all :)

**Comment by hlissner** [comment]
It is planned for 2.0.8, but should be in `develop` sooner. I'll post here when it is.

**Comment by hlissner** [comment]
This turned out to be a larger undertaking than I had anticipated, so I've pushed this back to 2.1.

**Comment by hlissner** [comment]
This is now done. It's still a WIP, and I expect a lot of edge cases to crop up, but the popup system is no longer part of core Doom, so I'll consider this resolved. I will close it once it hits `master`.

**Comment by amosbird** [comment]
Hi @hlissner . I'm following the new popup document and add a new rule `(set! :popup "^\\*compilation" '((side . right) (size . 0.5)) '((transient . 0) (quit . t)))`. However it only affects the placement and size. `ESC/C-g` doesn't close the  window though. Am I doing it wrong?

**Comment by hlissner** [comment]
You are doing it correctly. However, the ESC key is remapped to something else in compilation-mode-map. Please try this and tell me if it works:

```emacs-lisp
;; add to private/$USER/config.el
(map! :map +popup-buffer-mode-map [escape] #'doom/escape)
```

But <kbd>C-g</kbd> does not work for you either? That is strange. It is not overwritten and works for me in the compilation buffer.

**Comment by amosbird** [comment]
nope. Neither `ESC` nor `C-g` works. and `(map! :map +popup-buffer-mode-map [escape] #'doom/escape)` doesn't help.

**Comment by hlissner** [comment]
Aaaah! I just realized that the `window-parameters` alist entry in `display-buffer BUFFER ALIST` was introduced in Emacs **26**, which means window parameters (like `transient` and `quit`) won't work in 25.x! Haha.

I'll look into this further in the morning.

**Comment by amosbird** [comment]
Great! thanks.

**Comment by hlissner** [comment]
Alright, window parameters are now mapped manually (if using Emacs 25.x), which should fix your problem. Give it a try and let me know.

**Comment by amosbird** [comment]
Thanks! It works fine now :)
