### ISSUE TITLE
Company completion with Clojure - arrow keys are closing the selection list

### ISSUE THREAD

**Issue by nirrub** [hlissner/doom-emacs#2610]
**What did you expect to happen?**

Whenever I use omnicomplete, I can use the arrow keys to select the appropriate item in the list and select it with Enter

**What actually happened?**
omnicomplete for Clojure files (with Cider connected), the arrow keys causes the caret to move up/down a line and just close the selection list

**Steps to reproduce:**
1. Use the latest doom
2. Open a clojure project
3. Cider jack-in (localleader ')
4. omnicomplete anything via ctrl-x + ctrl-o
5. Try to select an item via the up/down arrow keys

**System information:**

Attached is the sys info for the version that works doesn't have this bug - not the latest doom!
<details><pre>
WARNING (:tools flycheck) module was moved to (:checkers syntax)
((emacs
  (version . "26.1")
  (features . "NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS")
  (build . "May 31, 2018")
  (buildopts "--with-ns '--enable-locallisppath=/Library/Application Support/Emacs/${version}/site-lisp:/Library/Application Support/Emacs/site-lisp' --with-modules")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD 21db1b7c9 2020-02-13 14:45:08 -0500")
  (dir . "~/.dotfiles/.doom.d/"))
 (system
  (type . darwin)
  (config . "x86_64-apple-darwin14.5.0")
  (shell . "/bin/zsh")
  (uname . "Darwin 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64")
  (path "~/bin" "/usr/local/sbin" "/usr/local/bin" "/usr/sbin" "/usr/bin" "/sbin" "/bin" "/usr/games" "/usr/local/games" "/usr/local/sbin" "/usr/local/bin" "/usr/sbin" "/usr/bin" "/sbin" "/bin" "~/bin" "~/android-sdk-linux/tools" "~/android-sdk-linux/platform-tools" "~/.local/bin" "~/p4v/bin/" "~/.local/bin" "~/.cargo/bin" "/usr/local/share/dotnet" "/usr/local/opt/go/libexec/bin" "~/.config/nvim/plugged/vim-iced/bin" "/Applications/Emacs.app/Contents/MacOS/bin-x86_64-10_10" "/Applications/Emacs.app/Contents/MacOS/libexec-x86_64-10_10" "/Applications/Emacs.app/Contents/MacOS/libexec" "/Applications/Emacs.app/Contents/MacOS/bin"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company (ivy +fuzzy) :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) treemacs vi-tilde-fringe window-select :editor (evil +everywhere) file-templates fold multiple-cursors rotate-text snippets :emacs dired electric ibuffer vc :tools (eval +overlay) :checkers syntax :tools (lookup +docsets) magit :lang clojure data elixir emacs-lisp (java +meghanada) markdown (org +dragndrop +ipython +pandoc +present) sh :config (default +bindings +smartparens))
  (packages . "<(void-function sp-point-in-string)>")
  (elpa "n/a")
  (unpin "n/a")))</pre></details>

**Comment by nirrub** [comment]
A bit of digging shows that it's probably the same as issue #1335 

I tried the suggested fixes there, but none of them work. Any help/simple hacks will be greatly appreciated - just want to traverse my completion list via the arrow keys and select with Enter.

Thanks

**Comment by nirrub** [comment]
Managed to solve this via this link:

https://github.com/company-mode/company-quickhelp/issues/17

Essentially, my config.el now has this:

```
(after! cider
  (add-hook 'company-completion-started-hook 'ans/set-company-maps)
  (add-hook 'company-completion-finished-hook 'ans/unset-company-maps)
  (add-hook 'company-completion-cancelled-hook 'ans/unset-company-maps)

  (defun ans/unset-company-maps (&rest unused)
    "Set default mappings (outside of company).
Arguments (UNUSED) are ignored."
    (general-def
      :states 'insert
      :keymaps 'override
      "<up>" nil
      "<down>" nil))

  (defun ans/set-company-maps (&rest unused)
    "Set maps for when you're inside company completion.
Arguments (UNUSED) are ignored."
    (general-def
      :states 'insert
      :keymaps 'override
      "<down>" 'company-select-next
      "<up>" 'company-select-previous)))
```

**Comment by russmatney** [comment]
Just want to confirm that this was an issue, and the pasted workaround solved it for me - many thanks @nirrub

The strange thing was that it was only broken in clojure/cider mode - the completion bindings in elisp worked fine.
