### ISSUE TITLE
vc gutter backends, Emacs mode in vc-*-log-view-mode?

### ISSUE THREAD

**Issue by sebastiansturm** [hlissner/doom-emacs#2611]
Two minor questions relating to doom's default vc setup:

- as far as I can see, `vc-gutter` works perfectly well with mercurial repositories, but by default is only enabled for git repositories. Is there any reason not to add `hg` to `git-gutter:handled-backends` (and maybe also `svn` and `bzr` but I haven't tried those)?

- IMO, it would be useful to have some of Emacs' backend-agnostic vc functionality such as `vc-hg-log-view-mode` start up in Emacs mode by default. Do you agree? If so, I'll open a PR after my lsp pull request

**Comment by hlissner** [comment]
> such as vc-hg-log-view-mode start up in Emacs mode by default

When? If globally, I'd rather not add font-lock keywords to a session that doesn't need them.

> Is there any reason not to add hg to git-gutter:handled-backends (and maybe also svn and bzr but I haven't tried those)?

No reason. Just hadn't occurred to me. I'll accept a PR to add those.

**Comment by sebastiansturm** [comment]
> > such as vc-hg-log-view-mode start up in Emacs mode by default
> 
> When? If globally, I'd rather not add font-lock keywords to a session that doesn't need them.

don't understand how font-lock comes into play. Probably because I used the wrong words; instead of "Emacs mode" I should have said "is there a specific reason not to set the `vc-log-*-mode`'s initial evil state to `'emacs`?". `vc-log-*-mode` is not a mode that would be enabled globally; it's a number of specialized modes (one for git, one for hg, etc) that Emacs invokes when viewing a repository's version history via `vc-print-log`

> > Is there any reason not to add hg to git-gutter:handled-backends (and maybe also svn and bzr but I haven't tried those)?
> 
> No reason. Just hadn't occurred to me. I'll accept a PR to add those.

great, will do that then after the lsp pr

**Comment by hlissner** [comment]
> is there a specific reason not to set the vc-log-*-mode's initial evil state to 'emacs?

Ah, I understand. No there is no reason for it; I am falling back to evil's defaults. If it makes more sense to start those in emacs state, I'll happily do so.

> great, will do that then after the lsp pr

It was just merged!

**Comment by sebastiansturm** [comment]
great, thank you! I'll look into it now

**Comment by sebastiansturm** [comment]
opened a PR, so the issue can be closed
