### ISSUE TITLE
How can I open the directory navigation on the left?

### ISSUE THREAD

**Issue by iT-Boyer** [hlissner/doom-emacs#2613]
![屏幕快照 2020-02-26 下午11 38 18](https://raw.githubusercontent.com/hlissner/doom-emacs/screenshots/main.png)

**Comment by seanbreckenridge** [comment]
Make sure `treemacs` is enabled in your `init.el`, and then `SPC o p` to toggle the sidebar.

`SPC o P` opens treemacs (if necessary) and prompts you to search for a file.

**Comment by iT-Boyer** [comment]
YES, I open treemacs in init.el , then `doom refresh`
`SPC o P`don't open tree:
```
Cannot open load file: No such file or directory, treemacs-persp
```

**Comment by hlissner** [comment]
@iT-Boyer This is a known issue where `melpa` isn't being updated before the package is installed. Try this:

```sh
cd ~/.emacs.d/.local/straight/repos/melpa
git pull
doom sync
doom update
```

**Comment by iT-Boyer** [comment]
after `git pull`, the same error occurred while executing the `doom sync` and `doom update`
```
WARNING (:tools flycheck) module was moved to (:checkers syntax)
Package error: (error Could not find package treemacs-persp in recipe repositories: (org-elpa melpa gnu-elpa-mirror emacsmirror-mirror))
```

**Comment by lazaruslarue** [comment]
if you want to be able to open the filebrowser on the left (`SPC o p`) then you need to enable `neotree` in your `init.el`.

press `SPC f P` to get to your personal config files.

**Comment by iT-Boyer** [comment]
@lazaruslarue I try do that, it non't work.

**Comment by hlissner** [comment]
Oops, didn't mean to close this.

Anyhow, the `treemacs-persp` package has been problematic (for some reason, straight has trouble seeing it, despite the state of the local melpa repo), so as a temporary measure I've removed the package in 13aa3e8. This should resolve at least that issue.

> I try do that, it non't work.

@iT-Boyer What did you try? @lazaruslarue's instructions were spot on.

1. Enable `:ui treemacs` in `~/.doom.d/init.el`
2. Run `doom sync`
3. Restart Emacs (and your daemon, if you use it)

**Comment by iT-Boyer** [comment]
it work after  `git pull `！
thanks
