### ISSUE TITLE
Unable to paste over visual selection in TTY mode only

### ISSUE THREAD

**Issue by shanesveller** [hlissner/doom-emacs#2617]
**What did you expect to happen?**
Text within visual selection is replaced by previously-yanked text
Previous text within visual selection is yanked instead for future pasting

**What actually happened?**
Visually-selected text left intact, and yanked

**Additional details:**
OS: MacOS 10.14.6 (Mojave)
Emacs: 26.3 via Nix on `nixpkgs-darwin-19.09` channel (`nixpkgs-19.09pre194823.57a4956bc25`), also occurs with Emacs 26.3 via [emacs-plus](https://github.com/d12frosted/homebrew-emacs-plus) as well as Emacs 28.0.50 via [emacs-overlay](https://github.com/nix-community/emacs-overlay)@`ac62d6d25a13787da2b8e0b2d0cc2b84816aa7bf`.

Minimal `init.el`, `packages.el` and `config.el` emptied:
```elisp
;;; init.el -*- lexical-binding: t; -*-
(doom! :ui doom :editor evil)
```

**Steps to reproduce:**

1. `emacs test.txt`
2. Enter `"foo"\n"bar"`
3. Place point inside `foo`
4. Press `yi"`
5. Press `$p` to confirm `foo` was yanked
6. Place point inside `bar`
7. Press `vi"p` to visual-select `bar` and then attempt to paste over it
8. Press `$p` to confirm `bar` was yanked while replacing it

Unsuccessful version:
1. `emacs -nw test.txt` instead of command above, no other configuration or installation changes
1. Repeat 2-8 above
1. Final outcome:
  ```
  "foo"foo
  "bar"bar
  ```

**System information:**
<details>

```
emacs   version    26.3
        features   NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS
        build      Feb 26, 2020
        buildopts  (--prefix=/nix/store/bcnb39cgi9d0im9qpm58lhx8hcsgdxfm-emacs-26.3 --disable-build-details --with-modules --with-ns --disable-ns-self-contained CFLAGS=-DMAC_OS_X_VERSION_MAX_ALLOWED=101200)
        windowsys  ns
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop, origin/develop, origin/HEAD 9f8cede4c 2020-02-26 17:48:45 -0500
        dir        ~/.config/doom/
system  type       darwin
        config     x86_64-apple-darwin17.7.0
        shell      /bin/sh
        uname      Darwin 18.7.0 Darwin Kernel Version 18.7.0: Thu Jan 23 06:52:12 PST 2020; root:xnu-4903.278.25~1/RELEASE_X86_64 x86_64
        path       (/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin ~/.asdf/shims ~/.asdf/bin /run/current-system/sw/bin ~/.emacs.d/bin /opt/X11/bin ~/.nix-profile/bin /nix/var/nix/profiles/default/bin /usr/local/bin /usr/bin /bin /usr/local/sbin /usr/sbin /sbin ~/.cargo/bin /nix/store/bcnb39cgi9d0im9qpm58lhx8hcsgdxfm-emacs-26.3/libexec/emacs/26.3/x86_64-apple-darwin17.7.0/)
config  envfile    envvar-file
        elc-files  0
        modules    (:ui doom :editor evil)
        packages   (n/a)
        unpin      (n/a)
        elpa       (n/a)
```
</details>

**Comment by hlissner** [comment]
I can't seem to reproduce it. This suggests a communication issue between Emacs and your clipboard.

Could you check if `xclip-mode` is enabled in your tty session of Emacs? If so, try disabling it (`M-x xclip-mode`) and see if that resolves your issue.

(What `xclip-mode` does is it facilitates communication between Emacs and your clipboard. Despite it's name, it uses pbcopy/pbpaste on the mac)

**Comment by shanesveller** [comment]
Disabling `xclip-mode` does indeed seem to correct the behavior! I will try to run further with this now that I have an area to look into, and report back if I come up with anything constructive. I may just tolerate the lack of integration with OS clipboard for the interim.

Was using this in my `config.el` so I don't forget about it:
```elisp
(remove-hook 'tty-setup-hook 'doom-init-clipboard-in-tty-emacs-h)
```
Based on the existing setup [here](https://github.com/hlissner/doom-emacs/blob/9f8cede4cd6e2d9342429e66cc3ab30b4ace62bc/core/core-editor.el#L137-L142).
