### ISSUE TITLE
php-mode find references doesn't work(?)

### ISSUE THREAD

**Issue by gitbugr** [hlissner/doom-emacs#2618]
**What did you expect to happen?**
To have a list of references to method in my project

**What actually happened?**
No references found when using `<SPACE> c D`

using `<SPACE> : xref-find-references <RET>` returns `No applicable method: xref-backend-identifier-completion-table, nil`

using `<SPACE> : phpactor-find-references <RET>` opens a full screen buffer with results like this;
![screenshot](https://user-images.githubusercontent.com/6732567/75466423-161f6c00-5982-11ea-8c3d-f533af1cad92.png)

**System information:**
<details><pre>
emacs   version    26.3
        features   NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS
        build      Sep 02, 2019
        buildopts  (--with-ns '--enable-locallisppath=/Library/Application Support/Emacs/${version}/site-lisp:/Library/Application Support/Emacs/site-lisp' --with-modules)
        windowsys  ns
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop, origin/develop, origin/HEAD 9f8cede4c 2020-02-26 17:48:45 -0500
        dir        ~/.doom.d/
system  type       darwin
        config     x86_64-apple-darwin18.2.0
        shell      /bin/zsh
        uname      Darwin 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64
        path       (~/.cabal/bin ~/.ghcup/bin ~/.phpbrew/bin ~/.rvm/gems/ruby-2.6.2/bin ~/.rvm/gems/ruby-2.6.2@global/bin ~/.rvm/rubies/ruby-2.6.2/bin /usr/local/Cellar/node/13.2.0/bin /usr/local/sbin /usr/local/bin ~/.cargo/bin ~/.rvm/bin /bin /usr/local/opt/gettext/bin /usr/local/opt/gnu-sed/libexec/gnubin ~/.composer/vendor/bin ~/bin ~/.rbenv/bin /usr/local/opt/curl/bin /Library/Frameworks/Python.framework/Versions/3.6/bin ~/.cargo/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /usr/local/MacGPG2/bin /Applications/Wireshark.app/Contents/MacOS ~/.fzf/bin /Applications/Emacs.app/Contents/MacOS/bin-x86_64-10_14 /Applications/Emacs.app/Contents/MacOS/libexec-x86_64-10_14 /Applications/Emacs.app/Contents/MacOS/bin-x86_64-10_14 /Applications/Emacs.app/Contents/MacOS/libexec-x86_64-10_14 /Applications/Emacs.app/Contents/MacOS/libexec/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit fill-column hl-todo indent-guides modeline nav-flash neotree ophints (popup +all +defaults) unicode vc-gutter vi-tilde-fringe window-select workspaces zen :editor (evil +everywhere) file-templates fold multiple-cursors rotate-text snippets :emacs dired electric ibuffer vc :term term :checkers syntax :tools docker editorconfig ein (eval +overlay) gist (lookup +docsets) magit pdf rgb upload :lang assembly cc data emacs-lisp go (haskell +dante) javascript markdown (org +dragndrop +present) php python sh web :config (default +bindings +smartparens))
        packages   ((edbi))
        unpin      (n/a)
        elpa       (n/a)
</pre></details>

**Comment by hlissner** [comment]
I wasn't aware phpactor had a find references command. Does this fix the issue? (For `SPC c D` (it's also on `gD`))

```elisp
(after! phpactor
  (set-lookup-handlers! 'php-mode
    :references #'phpactor-find-references))
```

If so, I'll add it to the php module.

**Comment by gitbugr** [comment]
> I wasn't aware phpactor had a find references command. Does this fix the issue? (For `SPC c D` (it's also on `gD`))
> 
> ```emacs-lisp
> (after! phpactor
>   (set-lookup-handlers! 'php-mode
>     :references #'phpactor-find-references))
> ```

unfortunately no 😞

this looks like a possible lead? 
https://github.com/kermorgant/.emacs.d/blob/master/lang/mk-php.el

it looks like they're using a branch named `xref-experiment` in the `emacs-php/phpactor.el` repo and wrote this function to set it up?
```
(defun mk/phpactor-xref ()
  "Activates xref backend using phpactor."
  (make-local-variable 'xref-prompt-for-identifier)
  (setq xref-prompt-for-identifier nil)
  (add-hook 'xref-backend-functions #'phpactor-xref-backend nil t))
```

I'm not very well versed in lisp or emacs yet (just come from vim) so not quite sure how I'd pull this into doom
