### ISSUE TITLE
LSP :: Sending to process failed with the following error: Process clangd not running

### ISSUE THREAD

**Issue by iT-Boyer** [hlissner/doom-emacs#2620]
I edit `test.m` file and `M-x: lsp `
print this error logs:
```
Server clangd:35543 exited with status signal. Do you want to restart it? (y or n) y
LSP :: Restarting LSP in buffer test.m
LSP :: Guessed project root is ~/hsg/jhygpatrol/
LSP :: Connected to [clangd:35550 status:starting].
LSP :: clangd:35550 initialized successfully
LSP :: Sending to process failed with the following error: Process clangd not running
LSP :: clangd has exited (abort trap: 6)
```

**Comment by hlissner** [comment]
I'm not sure if this is a Doom issue or an upstream issue. Perhaps try switching to ccls instead and see if that works for you.

**Comment by iT-Boyer** [comment]
how to switch ccls？

**Comment by hlissner** [comment]
@iT-Boyer 

1. Enable the `:lang (cc +lsp)` module. ([This part of the documentation talks about toggling modules and module flags](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#modules))

2. Install `ccls` through your OS package manager. e.g. `pacman -S ccls` if you're on Arch.

3. Run `doom sync` and restart Emacs.
