### ISSUE TITLE
Documentation popup covers other popups

### ISSUE THREAD

**Issue by rakanalh** [hlissner/doom-emacs#2623]
I am currently seeing this issue while working with Rust.

**Steps to reproduce:**
The workflow as as follows:
1. Run cargo check (SPC m b c) (cursor moves to the popup itself)
2. Move cursor back to the buffer
3. Press `K` to show documentation on some Item

**What did you expect to happen?**
A new popup above/below/beside the `cargo check` popup should appear showing the documentation.

**What actually happened?**
The documentation popup is placed on top of the `cargo check` popup. Which means that pressing `ESC` to close the documentation popup, the `cargo check` popup will also disappear.

**Additional details:**
- Include a link to your private config

https://github.com/rakanalh/dotfiles/tree/master/.doom.d

- Include screenshots/casts of your issue

![Screenshot 2020-02-27 at 22 46 31](https://user-images.githubusercontent.com/195829/75489785-361b5380-59b3-11ea-8fcb-647f182fa190.png)

![Screenshot 2020-02-27 at 22 46 41](https://user-images.githubusercontent.com/195829/75489798-3b789e00-59b3-11ea-858e-011eccac3d92.png)

- If you mention key sequences, include what commands they're bound to (use `SPC
  h k KEY` or `C-h h k KEY` to inspect keys).
- Include any warnings or errors logged to \*Messages\* (use `M-x
  view-echo-area-messages` to see it).

<details><pre>
If an error message is involved include a backtrace of it.

How to acquire a backtrace:
https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#how-to-extract-a-backtrace-from-an-error
</pre></details>

**System information:**
<details><pre>
((emacs
  (version . "26.3")
  (features . "NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS")
  (build . "Sep 02, 2019")
  (buildopts "--with-ns '--enable-locallisppath=/Library/Application Support/Emacs/${version}/site-lisp:/Library/Application Support/Emacs/site-lisp' --with-modules")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop afa6b7ab9 2020-02-27 11:55:27 -0500")
  (dir . "~/dotfiles/.doom.d/"))
 (system
  (type . darwin)
  (config . "x86_64-apple-darwin18.2.0")
  (shell . "/bin/zsh")
  (uname . "Darwin 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64")
  (path "~/perl5/bin" "/usr/local/bin" "/usr/bin" "/bin" "/usr/sbin" "/sbin" "/usr/local/git/bin" "/usr/local/go/bin" "/opt/sm/bin" "/opt/sm/pkg/active/bin" "/opt/sm/pkg/active/sbin" "/bin" "~/Code/Go/bin" "~/.bin" "~/.cargo/bin" "/Applications/Emacs.app/Contents/MacOS/bin-x86_64-10_14" "/Applications/Emacs.app/Contents/MacOS/libexec-x86_64-10_14" "/Applications/Emacs.app/Contents/MacOS/libexec" "/Applications/Emacs.app/Contents/MacOS/bin"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard doom-quit hl-todo hydra modeline nav-flash ophints (popup +all +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces zen :editor (evil +everywhere) file-templates fold (format +onsave) multiple-cursors rotate-text snippets :emacs dired electric ibuffer vc :term vterm :checkers syntax :tools editorconfig (eval +overlay) (lookup +docsets) lsp magit :lang data emacs-lisp go javascript lua markdown (org +dragndrop +ipython +pandoc +present) (python +pyenv) (rust +lsp) sh solidity :config (default +bindings +smartparens))
  (packages . "<(void-function sp-point-in-string)>")
  (unpin "n/a")
  (elpa "n/a")))
</pre></details>

**Comment by hlissner** [comment]
This should be a simple matter of specifying rules for one or the other popup, with a non-zero `:slot` (so they display side-by-side) or `:vslot` (so they display stacked on top of each other).

Could you tell me what `M-: (buffer-name)` returns for the two buffers?

**Comment by rakanalh** [comment]
Sure, for `cargo check` it's `*rustic-compilation*`
and the help buffer has the name of `*lsp-help*`

**Comment by rakanalh** [comment]
I tried adding:
```
  (set-popup-rule! "rustic-compilation" :ignore nil :actions: nil :side 'bottom :width 0.5 :quit 'current :select t :slot -1)
```

And the problem is solved. Feel free to close this issue if you think this is a config-specific issue and not Doom emacs.

Many thanks @hlissner

**Comment by hlissner** [comment]
I thought this should be fixed in the module, so I've pushed a similar rule in 429dece. Thanks for bringing it to my attention!
