### ISSUE TITLE
Racket-mode not associated with .rkt files

### ISSUE THREAD

**Issue by ncihnegn** [hlissner/doom-emacs#2626]
**What did you expect to happen?**
Activate racket-mode when opening .rkt files

**What actually happened?**
Scheme-mode is activated and asking for scheme implemenation

**Additional details:**
Using develop branch, everything up to date.

**Comment by hlissner** [comment]
As of a938eb3, if you have `:lang racket` enabled, `*.rkt` should be associated with `racket-mode` instead. Let me know if that isn't the case and I'll reopen the issue. Thanks for bringing it to my attention!

**Comment by ncihnegn** [comment]
Now it works great. Thanks a lot.
