### ISSUE TITLE
Projectile projectile-known-projects-file reset after reboot.

### ISSUE THREAD

**Issue by lromor** [hlissner/doom-emacs#2629]
> Please visit our Discord server to ask how-to and workflow questions:
> https://discord.gg/qvGgnVx -- post on Doom's issue tracker as a last resort.

**What are you trying to achieve?**

I Would like doom emacs projectile to remember the projects I recently added.

**What have you tried?**
After a reboot I checked the file pointed by `projectile-known-projects-file` 
(~/.emacs.d/.local/cache/projectile.projects) and I noticed is reset every time. Is this standard behavior? I'm currently using the development branch.

**Additional information**
- Do you have screenshots/casts of this workflow in another editor or Emacs
  distro? (If possible, include names of specific commands or functions from
  other editors/emacs distros)
- Do you have additional material or links to resources that could help clarify
  what you are trying to do?

**System information**
<details><pre>
((emacs
  (version . "26.1")
  (features . "XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 THREADS LIBSYSTEMD LCMS2")
  (build . "set 23, 2019")
  (buildopts "--build x86_64-linux-gnu --prefix=/usr --sharedstatedir=/var/lib --libexecdir=/usr/lib --localstatedir=/var/lib --infodir=/usr/share/info --mandir=/usr/share/man --enable-libsystemd --with-pop=yes --enable-locallisppath=/etc/emacs:/usr/local/share/emacs/26.1/site-lisp:/usr/local/share/emacs/site-lisp:/usr/share/emacs/26.1/site-lisp:/usr/share/emacs/site-lisp --with-sound=alsa --without-gconf --with-mailutils --build x86_64-linux-gnu --prefix=/usr --sharedstatedir=/var/lib --libexecdir=/usr/lib --localstatedir=/var/lib --infodir=/usr/share/info --mandir=/usr/share/man --enable-libsystemd --with-pop=yes --enable-locallisppath=/etc/emacs:/usr/local/share/emacs/26.1/site-lisp:/usr/local/share/emacs/site-lisp:/usr/share/emacs/26.1/site-lisp:/usr/share/emacs/site-lisp --with-sound=alsa --without-gconf --with-mailutils --with-x=yes --with-x-toolkit=gtk3 --with-toolkit-scroll-bars 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/emacs-StqULU/emacs-26.1+1=. -fstack-protector-strong -Wformat -Werror=format-security -Wall' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' LDFLAGS=-Wl,-z,relro")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD 8a01ef908 2020-01-20 20:17:43 -0500")
  (dir . "~/.doom.d/"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/bin/zsh")
  (uname . "Linux 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64")
  (path "~/.yarn/bin" "~/.local/bin" "~/.cargo/bin" "/usr/local/bin" "/usr/bin" "/bin" "/usr/games" "/usr/lib/emacs/26.1/x86_64-linux-gnu"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold multiple-cursors rotate-text snippets :emacs dired electric vc :term eshell :tools eval :checkers syntax :tools (lookup +docsets) magit pdf :lang assembly cc data emacs-lisp go (haskell +intero) javascript latex markdown (org +dragndrop +ipython +pandoc +present) python rust sh web :config (default +bindings +smartparens))
  (packages prettier-js org-fancy-priorities origami org-super-agenda org-brain ascii-art-to-unicode bazel-mode dockerfile-mode)
  (elpa "n/a")))

</pre></details>

**Comment by yoavm448** [comment]
>  I'm currently using the master branch

Master was not updated for 2 years. You should really use develop.

**Comment by lromor** [comment]
Sorry, my mistake I'm using develop!

**Comment by hlissner** [comment]
This is certainly not standard behavior. Have you changed `projectile-enable-caching`? Also, you appear to be on a month-old commit of Doom. I'd suggest running `doom upgrade`, then see if the issue is still around.

**Comment by lromor** [comment]
I reinstalled everything and removed `.doom.d`. The same behavior seems to occur.
In my setup during startup I run `emacs --daemon` and sometimes I use a new instance of emacs. Do you think this could be the issue? I noticed that after adding a bunch of projects and issuing a reboot via commandline sometimes they "survive" the reboot, sometimes not. Could this behavior arise by the fact that I'm running multiple emacs instances?

**Comment by lromor** [comment]
I think the issue is related with having multiple emacs instances running at the same time (`--daemon` and without). It seems that since I started using the standalone only the issue disappeared.
