### ISSUE TITLE
Better popup toggling

### ISSUE THREAD

**Issue by gilbertw1** [hlissner/doom-emacs#263]
Hey! 

I've been in the process of rethinking popups and I feel like I've hit a really good workflow with toggling them. One of the issues I had previously is that it became a bit tough to quickly toggle specific popups in the face of multiple popups being available at once.

The solution I landed upon was a general popup toggling function `show-hide-popup-buffer` that:

1. Takes a two optional parameters: `select` and `buffer-rx`
  - `select`: if non nil tells the function to prompt the user to select a popup buffer in the event that multiple are available
  - `buffer-rx`: a regular expression that limits the scope of the function to buffers with names matching regex

2. If called while a popup buffer is visible it will close that popup buffer. In the event that multiple popups are visible it will close the most recenty displayed buffer, unless `select` is non-nil then it will prompt the user to select a popup window to close.

3. If called while no popup windows are open then it will look for any open popup buffers that are not displayed. If there is a single popup buffer, then it will open that buffer. If there are multiple popup buffers then it will either prompt the user to pick a popup buffer to open if `select` is non-nil, otherwise it will open the most recently displayed popup buffer.

4. Finally, if there are no popup buffers open period, then it will simply print a message saying so.

This makes opening and toggling a popup seamless even when multiple popups are present. Additionally, intentionally opening one of many available popups a very quick and easy task. 

One really nice side effect of using this function is that it makes it easily possible to keep around long term or persistent popups. For example, I recently made `*Messages*` a popup. Given the fact that `*Messages*` is pretty much always around, it would normally make working with popups, specifically toggling individual popups a lot more difficult. Using `show-hide-popup-buffer` and passing a non-nil `select` value, I can quickly pop open the specific buffer I want, and then I invoke it with `select` as nil to simply toggle that popup.

You can see a quick screencap of the workflow in action:

[Screencast](http://drop.bryan.sh/dnLVGb6KcF.mp4)

Here are my bindings so the screencast makes more sense:

```
 "C-`"    #'bmacs/show-hide-popup-buffer          ;; always toggle most recent
 "C-~"    (λ! (bmacs/show-hide-popup-buffer t)) ;; prompt if multiple
```

Anyways, I've been very pleased with this toggling workflow and I thought I'd push the idea your way or see if you'd be interested in a pull request implementing this functionality. You can find my [implementation here](https://github.com/gilbertw1/bmacs/blob/master/bmacs.org#buffer-functions) ... it needs A LOT of cleanup, but works pretty well as it is.

Thanks!

**Comment by hlissner** [comment]
This has been on `develop` for a while, as `+popup/toggle`, which is bound to <kbd>ctrl</kbd>+<kbd>`</kbd> and <kbd>space</kbd> <kbd>shift</kbd> <kbd>~</kbd>, so I'll consider this resolved.

Thanks again for this detailed write up and screencast!
