### ISSUE TITLE
How to set the default style of Emacs startup, such as full screen and font size。

### ISSUE THREAD

**Issue by iT-Boyer** [hlissner/doom-emacs#2652]
How to set the default style of Emacs startup, such as full screen and font size

**Comment by hlissner** [comment]
Font size: https://github.com/hlissner/doom-emacs/blob/develop/docs/faq.org#how-do-i-change-the-fonts

Full screen: `(add-hook 'window-setup-hook #'toggle-frame-fullscreen)`

**Comment by iT-Boyer** [comment]
thanks，very good。
I must install Input and Fira Fonts。

**Comment by lroolle** [comment]
Personally prefer Maximized instead of Full on macOS...

```
(add-hook 'window-setup-hook #'toggle-frame-maximized)
```

**Comment by eddiegroves** [comment]
@hlissner is this something you'd like added to the FAQs?
