### ISSUE TITLE
how do i use "gss" "evil-avy-goto-char-2" in info-mode.

### ISSUE THREAD

**Issue by loyalpartner** [hlissner/doom-emacs#2653]
i often use  "gss" "gsSPC" to locate some character,
but it didn't use in info-mode, i have type "gss" many time in info-mode.
I dont't know why not support easymotion directly it in info-mode?

**Comment by WhatDothLife** [comment]
Does `(map!  :map Info-mode-map :n "gs" #'+evil/easymotion)` work?

**Comment by loyalpartner** [comment]
@WhatDothLife 
it doesn't work when i try you code.

**Comment by WhatDothLife** [comment]
I experience the same issue. I'll create a new issue for this soon, so you may close this one.

**Comment by WhatDothLife** [comment]
I created a new issue. See [here](https://github.com/PythonNut/evil-easymotion/issues/64).
