### ISSUE TITLE
Org reveal export keybinding changed/removed?

### ISSUE THREAD

**Issue by tamasgal** [hlissner/doom-emacs#2654]
**What did you expect to happen?**
I have tons of slides which I presented via `SPC m e v b` in the past and this keybinding disappeared. I found that the reveal export is now available via `SPC m e R B` but it does not seem to understand the format characters in:

```
#+REVEAL_TITLE_SLIDE: <h1>%t</h1><a href="%u">......
```

in this case, `%u` and `%A` are not recognised anymore `Invalid format character: %u`

**Reproduce**

Create a `test.org` with this content and hit `SPC m e R B`

```
# #+REVEAL_TITLE_SLIDE: <h1>%t</h1><h3>%s</h3><p>%A %a</p><p><a href="%u">%u</a></p>

#+Title: Whatever
#+Subtitle:
#+Author: Foo
#+Email: em@il
#+REVEAL_TALK_URL: https://github.com/hlissner/doom-emacs
```

Path to my `doom.d`: https://github.com/tamasgal/rc/blob/master/doom.d

**System information:**
<details><pre>
((emacs
  (version . "26.3")
  (features . "XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2")
  (build . "Aug 29, 2019")
  (buildopts "--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-modules 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop 9f8cede4c 2020-02-26 17:48:45 -0500")
  (dir . "~/.rc/doom.d/"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/usr/bin/zsh")
  (uname . "Linux 4.14.168-1-MANJARO #1 SMP PREEMPT Mon Jan 27 16:56:25 UTC 2020 x86_64")
  (path "~/.nimble/bin" "~/go/bin" "~/modules/software/julia/1.3.0-rc4/bin" "~/opt/bin" "/var/lib/snapd/snap/bin" "~/.local/bin" "/usr/local/bin" "/usr/bin" "/bin" "/usr/local/sbin" "/opt/cuda/bin" "/usr/lib/jvm/default/bin" "/usr/bin/site_perl" "/usr/bin/vendor_perl" "/usr/bin/core_perl" "/var/lib/snapd/snap/bin" "~/.gem/ruby/2.6.0/bin" "~/.emacs.d/bin" "/usr/lib/emacs/26.3/x86_64-pc-linux-gnu"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company (ivy +fuzzy) :ui doom doom-dashboard fill-column hl-todo modeline nav-flash ophints (popup +all +defaults) tabs treemacs workspaces :editor (evil +everywhere) file-templates multiple-cursors snippets :emacs dired electric ibuffer vc :term eshell shell term vterm :checkers syntax spell grammar :tools direnv (eval +overlay) (lookup +docsets) lsp magit :lang data emacs-lisp julia (latex +latexmk) markdown (org +jupyter +pandoc +present) (python +lsp) rst sh :email mu4e :app calendar :config (default +bindings +smartparens))
  (packages . "<(void-function sp-point-in-string)>")
  (unpin "n/a")
  (elpa "n/a")))
</pre></details>

**Comment by tamasgal** [comment]
Does anyone know what happened? I have tons of slides which now do not work. I have to manually change the title and some other parts everywhere 😕

**Comment by tamasgal** [comment]
Btw. here you can see that in `org-re-reveal`, there are tons of options for the title side, this worked before:
https://gitlab.com/oer/org-re-reveal/-/raw/master/test-cases/test-title-slide.org

Now it seems that doom suddenly uses `org-reveal`? https://github.com/yjwen/org-reveal

**Comment by tamasgal** [comment]
Thanks to merK on discord for pointing out the commit a0a7c34517db81b3f8c83ac87c882c4f0b0b72ee

I now re-added `org-re-reveal` with:

```lisp
 (use-package! org-re-reveal
:after ox
:init
(setq org-re-reveal-root "https://revealjs.com"))
```

but the `SPC m e v` option does not show up...

**Comment by hlissner** [comment]
Sorry for the late response. Yes, org-re-reveal was replaced with org-reveal because it seemed like the latter was better maintained, however, org-reveal's author recently announced that he no longer maintains it and that org-re-reveal is recommended, so I've switched back in 3a370343e. Sorry for the trouble!
