### ISSUE TITLE
[REQUEST] Add chruby support  to ruby module

### ISSUE THREAD

**Issue by numbcoder** [hlissner/doom-emacs#2658]
[Chruby](https://github.com/postmodern/chruby) is another ruby version manager like rbenv and rvm.
There is also an emacs package for [chruby](https://github.com/plexus/chruby.el), and spacemacs has been supported it.

 I'm a newbie for emacs, I don't know how to add this feature to doom.
Thanks!

**Comment by otavioschwanck** [comment]
I'll do it.

**Comment by numbcoder** [comment]
@otavioschwanck Thank you！

**Comment by otavioschwanck** [comment]
https://github.com/hlissner/doom-emacs/pull/2667

@numbcoder can you test it ? I don't have chruby here.

**Comment by numbcoder** [comment]
> #2667
> 
> @numbcoder can you test it ? I don't have chruby here.

It doesn't works for me. 
When I called `M-x chruby-use-corresponding`, it could get the correct ruby version, but the status line didn't change

**Comment by otavioschwanck** [comment]
> > #2667
> > @numbcoder can you test it ? I don't have chruby here.
> 
> It doesn't works for me.
> When I called `M-x chruby-use-corresponding`, it could get the correct ruby version, but the status line didn't change

I think chruby don't show you it statusline.  I will need to add this manually.  Can you inform the value of chruby-current-ruby-name  variable?

Press SPC h v and search for `chruby-current-ruby-name `.

**Comment by numbcoder** [comment]
> > > #2667
> > > @numbcoder can you test it ? I don't have chruby here.
> > 
> > 
> > It doesn't works for me.
> > When I called `M-x chruby-use-corresponding`, it could get the correct ruby version, but the status line didn't change
> 
> I think chruby don't show you it statusline. I will need to add this manually. Can you inform the value of chruby-current-ruby-name variable?
> 
> Press SPC h v and search for `chruby-current-ruby-name `.

The variable `chruby-current-ruby-name ` not found
<img width="664" alt="WX20200305-102650@2x" src="https://user-images.githubusercontent.com/281076/75941890-d994c880-5ecb-11ea-820e-d7839b7897c5.png">

After I called `M-x chruby-use-corresponding`
<img width="747" alt="WX20200305-102259@2x" src="https://user-images.githubusercontent.com/281076/75941917-f0d3b600-5ecb-11ea-94cf-6000b60b2fa2.png">

**Comment by otavioschwanck** [comment]
@hlissner you now how can i add this variable on status-bar ?  
@numbcoder the chruby is working, just dont show on status-bar, this is a problem?

**Comment by numbcoder** [comment]
> @numbcoder the chruby is working, just dont show on status-bar, this is a problem?

No, I guess the chruby is not init(I dont kown how the emacs package loading mechanism)

chruby in spacemacs : https://github.com/syl20bnr/spacemacs/blob/develop/layers/%2Blang/ruby/packages.el#L57-L63

**Comment by otavioschwanck** [comment]
> > @numbcoder the chruby is working, just dont show on status-bar, this is a problem?
> 
> No, I guess the chruby is not init(I dont kown how the emacs package loading mechanism)
> 
> chruby in spacemacs : https://github.com/syl20bnr/spacemacs/blob/develop/layers/%2Blang/ruby/packages.el#L57-L63

i've added a update.  Can you test it ?

**Comment by numbcoder** [comment]
@otavioschwanck It works well now! 🎉

**Comment by otavioschwanck** [comment]
> @otavioschwanck It works well now!

Nice!  Now, we just need to wait the review from @hlissner
