### ISSUE TITLE
Cannot override `projectile-require-project-root`

### ISSUE THREAD

**Issue by amosbird** [hlissner/doom-emacs#266]
Hi, I saw a lot of weird projects being cached in `/home/amos/.emacs.d/.local/@t450s/cache/projectile.projects` so I decide to set projectile-require-project-root to t. I did

```
(def-package-hook! projectile
  :post-init
  (setq projectile-require-project-root t)
  t)
```

and restart emacs. However `projectile-require-project-root` is still nil.

**Comment by hlissner** [comment]
`def-package-hook!` doesn't work on packages in doom's core. However, for this specifically, just use `(setq projectile-require-project-root t)`, that should be enough.

**Comment by amosbird** [comment]
Thanks!
