### ISSUE TITLE
[HOWTO] Set org-hide-leading-stars to nil?

### ISSUE THREAD

**Issue by klorax** [hlissner/doom-emacs#2660]
**What are you trying to achieve?**
Set `org-hide-leading-stars` to `nil`, but there is no change unless manually running `eval-buffer` and opening an org file that has not yet been opened.

So how can I set it, in a clean `doom` way?

**What have you tried?**
```elisp
(after! org
(setq org-hide-leading-stars nil))
```
Also with `setq-default` and without `after! org` (just in case).

**Additional information**
This could be related (from the emacs documentation):

> Changing it requires restart of font-lock-mode to become effective
also in regions already fontified.

Note though, it is still set to non-nil `t` without `eval-buffer`.

**Comment by hlissner** [comment]
This is because `org-indent-mode` [sets `org-hide-leading-stars` buffer-locally](https://github.com/emacs-straight/org-mode/blob/master/lisp/org-indent.el#L183-L184). You'll need to do:

```lisp
(after! org
  (setq org-hide-leading-stars nil
        org-indent-mode-turns-on-hiding-stars nil))
```

**Comment by klorax** [comment]
I already had `org-startup-indented nil` so I troubleshooted this further and found out that it has to do with running emacs as a daemon. Do you know how to achieve this for a daemon setup?

Thanks!

**Comment by hlissner** [comment]
Did you remember to restart the daemon after changing your config? Whether you use a daemon or not shouldn't impact these settings.

**Comment by klorax** [comment]
Of course, I always do `save-buffers-kill-emacs` (also have done `doom sync/refresh/update/upgrade` and doctor reports no errors (except of course #2284)) in case emacs needs a restart (also this is over the course of several days/reboots).

**Comment by hlissner** [comment]
Sorry for the late response. Have you figured out this issue? Unfortunately, I have no further insight into the matter, since I don't often use the daemon.

**Comment by dpaetzel** [comment]
I experience something similar. When I use the daemon, my `org-agenda-custom-commands` aren't the ones set by `setq!` in my `config.el`. Instead, they're the ones from the time I used `spacemacs` as if there is still something cached from that old config. When I don't use the daemon everything works as expected.

**Comment by klorax** [comment]
Unfortunately, no.

I was able to find a workaround for #2666 though and it might be a similar thing.

It seems it has to do with doing stuff without a frame and the solution might be to use `after-frame-functions`. See for example [this](https://stackoverflow.com/questions/18904529/after-emacs-deamon-i-can-not-see-new-theme-in-emacsclient-frame-it-works-fr). However, this is beyond my knowledge.

**Comment by dpaetzel** [comment]
> It seems it has to do with doing stuff without a frame and the solution might be to use `after-frame-functions`. See for example [this](https://stackoverflow.com/questions/18904529/after-emacs-deamon-i-can-not-see-new-theme-in-emacsclient-frame-it-works-fr).

You're right, that thread is about behavioural differences between Emacs with or without server, too. However, it’s about Emacs visuals which seem to me to be inherently connected to Emacs's frames—which can (or, _should_?) not be said for Org-mode's config unless there is something really broken there?

**Comment by dpaetzel** [comment]
> I experience something similar. When I use the daemon, my `org-agenda-custom-commands` aren't the ones set by `setq!` in my `config.el`. Instead, they're the ones from the time I used `spacemacs` as if there is still something cached from that old config. When I don't use the daemon everything works as expected.

I finally solved the problem I described by simply clicking on `Revert` in the `Customize` buffer of `org-agenda-custom-commands` (could've thought about that earlier). I did not find out where that value was cached, though … It seems as if the Emacs daemon saves customizations somewhere else than `~/.emacs.d`.

**Comment by hlissner** [comment]
@dpaetzel Sorry for the late response. Check `~/.doom.d/custom.el` for a `custom-set-variables` block. If you're on an older version of Doom, it may be in `~/.emacs.d/.local/custom.el`, or at the bottom of `~/.doom.d/config.el`.

If you use the `M-x customize` interface for customizing Emacs (I recommend you don't), it will save its settings to one of those files, which may be overwriting your changes.

**Comment by dpaetzel** [comment]
@hlissner Thank you for your response! I had that problem when I switched from spacemacs to doom. Meaning, I had just deleted `~/.emacs.d` entirely and did not yet—and do not to this day—have a `~/.doom.d/custom.el` … I was able to fix it by using `Customize`'s `Revert`, though, so everything's fine for me.

**Comment by klorax** [comment]
Seems related to this: #3076.
