### ISSUE TITLE
Org archive doesn't save archived subtrees directly

### ISSUE THREAD

**Issue by tamasgal** [hlissner/doom-emacs#2662]
**What did you expect to happen?**
I archived a subtree in my notes by pressing `SPC m A` and I was asked to create the directory `~/Dropbox/org/archive`, I confirmed with `y`, then a message said a file was written (`subtree archived in file ~/Dropbox/org/archive/research.org`). I did this to multiple subtrees, which were delete from the original files.

**What actually happened?**
The folder `~/Dropbox/org/archive` was created but it's completely empty. 

I also created an entry with `* wtf`, archived and did a `rg wtf` but nothing showed up, so I guess the subtrees are simply deleted?!

...
![image](https://user-images.githubusercontent.com/1730350/75864864-f2857700-5e02-11ea-9ce4-3d4b28b3e7d0.png)

```
░ tgal@staticbox:~/Dropbox 
░ 10:29:10 130 > ls org/archive 

░ tgal@staticbox:~/Dropbox 
░ 10:29:13 > 
```

**Additional details:**

This is my `org`-settings:

```elisp
(setq org-directory "~/Dropbox/org/"
        org-agenda-files '("~/Dropbox/org")
        org-archive-location (concat org-directory "archive/%s::")
        org-tags-column -80
        org-priority-faces '((?A :foreground "#e45649")
                             (?B :foreground "#da8548")
                             (?C :foreground "#0098dd"))
        org-bullets-bullet-list '("❖")
        org-ellipsis " ▼ "
        org-todo-keywords '((sequence "TODO(t)" "PROG(p)" "WAIT(w)" "|" "DONE(d)" "CANC(c)"))
        org-todo-keyword-faces
        '(
          ("TODO" :foreground "#ff0000" :weight normal :underline f)
          ("PROG" :foreground "#666600" :weight normal :underline f)
          ("WAIT" :foreground "#0000ff" :weight normal :underline f)
          ("DONE" :foreground "#00ff00" :weight normal :underline f)
          ("CANC" :foreground "#666666" :weight normal :underline f)
         )
        org-re-reveal-script-files '("js/reveal.js")
        org-latex-packages-alist '(("margin=2cm" "geometry" nil))
        )
  )
```

**System information:**
<details><pre>
((emacs
  (version . "26.3")
  (features . "XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2")
  (build . "Aug 29, 2019")
  (buildopts "--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-modules 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop 9f8cede4c 2020-02-26 17:48:45 -0500")
  (dir . "~/.rc/doom.d/"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/usr/bin/zsh")
  (uname . "Linux 4.14.168-1-MANJARO #1 SMP PREEMPT Mon Jan 27 16:56:25 UTC 2020 x86_64")
  (path "~/.nimble/bin" "~/go/bin" "~/modules/software/julia/1.3.0-rc4/bin" "~/opt/bin" "/var/lib/snapd/snap/bin" "~/.local/bin" "/usr/local/bin" "/usr/bin" "/bin" "/usr/local/sbin" "/opt/cuda/bin" "/usr/lib/jvm/default/bin" "/usr/bin/site_perl" "/usr/bin/vendor_perl" "/usr/bin/core_perl" "/var/lib/snapd/snap/bin" "~/.gem/ruby/2.6.0/bin" "~/.emacs.d/bin" "/usr/lib/emacs/26.3/x86_64-pc-linux-gnu"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company (ivy +fuzzy) :ui doom doom-dashboard fill-column hl-todo modeline nav-flash ophints (popup +all +defaults) tabs treemacs workspaces :editor (evil +everywhere) file-templates multiple-cursors snippets :emacs dired electric ibuffer vc :term eshell shell term vterm :checkers syntax spell grammar :tools direnv (eval +overlay) (lookup +docsets) lsp magit :lang data emacs-lisp julia (latex +latexmk) markdown (org +jupyter +pandoc +present) (python +lsp) rst sh :email mu4e :app calendar :config (default +bindings +smartparens))
  (packages . "<(void-function sp-point-in-string)>")
  (unpin "n/a")
  (elpa "n/a")))
</pre></details>

**Comment by tamasgal** [comment]
@gagbo just pointed out that it's only added to the buffer, but not written; fortunately I found it via `SPC b i`. So it's not a bug but a (to me) confusing  behaviour since it says: `...archived in file...`, which sounds like it is written to the file at the very same moment.

**Comment by tamasgal** [comment]
Is there a setting or hook where I can force immediate writing of the file?

**Comment by AloisJanicek** [comment]
> Is there a setting or hook where I can force immediate writing of the file?

I personally advise every org command which modifies content of an org buffer like this:

``` elisp
(advice-add #'org-archive-subtree-default :after #'org-save-all-org-buffers)
```

I din't encounter any issues doing so. 
I usually do a lot of editing from agenda buffers and advising all the functions like `org-agenda-refile`, `org-agenda-todo` or `org-agenda-kill` saved me also from interacting with this kind of message:

`Save file /home/alois/org/inbox.org? (y, n, !, ., q, C-r, C-f, d or C-h) 
`

**Comment by tamasgal** [comment]
Thanks for the tip! Where do you put that call? I just added to my `config.el` but it does not to have any effect.

**Comment by AloisJanicek** [comment]
It will go inside `(after! feature-or-symbol ... )` block:
```
(after! org
...
)
```
and after re-launch it should be applied. 
If it is not, then maybe change it to `(after! org-archive ... )`

**Comment by tamasgal** [comment]
OK, I tried both but it doesn't save automatically. I am currently on Emacs 28, so that might be related to it? Tomorrow I'll downgrade to 27

**Comment by AloisJanicek** [comment]
It looks like there are two main archiving functions: `org-archive-subtree` and `org-archive-subtree-default`. You need to advise both separately. Hard to tell which one you are actually using. I am also on Emacs 28, this isn't relevant in this case.

**Comment by tamasgal** [comment]
Perfect, thanks, it was `org-archive-subtree` :)

**Comment by hlissner** [comment]
I think `(setq org-archive-subtree-save-file-p t)` will work too. I'll keep this open until I've made this our default later tonight.
