### ISSUE TITLE
Error after doing make update.

### ISSUE THREAD

**Issue by amosbird** [hlissner/doom-emacs#267]
Hi, recent commits seem to break make update in a harmless way :)
```
 ❯ make update                                                                                  (937ms)
Looking for outdated packages...
1 packages will be updated:

+ osc   20171114.2207  -> 20171114.2213

y
Updating osc
  DONE
Finished!
Reloading...
No such server: server
make: *** [Makefile:24: update] Error 255
Proceed? (y or n)
```

**Comment by rphillips** [comment]
seeing the same thing as well.

**Comment by hlissner** [comment]
Just pushed a fix for this to `develop`. I'll merge it into master this weekend.

**Comment by amosbird** [comment]
It works fine now. Thanks!

**Comment by amosbird** [comment]
It seems `make update` doesn't recompile packages. I've encountered a magit bug due to this.

**Comment by amosbird** [comment]
and `make install` results in
```
Installing ox-pandoc
  FATAL ERROR: (error) Package does not untar cleanly into directory org-20171116/
Installing ox-hugo
  FATAL ERROR: (error) Package does not untar cleanly into directory org-20171116/
Installing ox-reveal
  FATAL ERROR: (error) Package does not untar cleanly into directory org-20171116/
Installing ob-translate
  FATAL ERROR: (error) Package does not untar cleanly into directory org-20171116/
Installing ob-rust
  FATAL ERROR: (error) Package does not untar cleanly into directory org-20171116/
Installing ob-redis
  FATAL ERROR: (error) Package does not untar cleanly into directory org-20171116/
Installing ob-mongo
  FATAL ERROR: (error) Package does not untar cleanly into directory org-20171116/
Installing flycheck-rust
  FATAL ERROR: (error) Package does not untar cleanly into directory seq-2.20/
Installing company-auctex
  FATAL ERROR: (error) Package does not untar cleanly into directory auctex-11.91.0/
Installing auctex
  FATAL ERROR: (error) Package does not untar cleanly into directory auctex-11.91.0/
Installing cider
  FATAL ERROR: (error) Package does not untar cleanly into directory seq-2.20/
Proceed? (y or n)
```

**Comment by amosbird** [comment]
Does doom provide a way to customize `package-archives`?

**Comment by hlissner** [comment]
You can modify `package-archives` in `~/.emacs.d/modules/private/$USER/init.el`, and it should affect non-core packages.

>It seems make update doesn't recompile packages

It should delete old packages and install/byte-compile new ones, so recompilation should be unnecessary. If you are using multiple computers, byte-compilated code on one computer may not necessarily work on another.

In any case, I've added a new make command: `make compile-elpa` for recompiling packages. Let me know if that resolves your issue.

> and make install results in ...

This is often a sign that a package url in `package-archives` is incorrect or down, or a recent `package-refresh` downloaded faulty data. Try `DEBUG=1 make install`, which will refresh the archives and, hopefully, offer more information.

**Comment by hlissner** [comment]
The fix for the original issue is now in `master`, so I'll consider this resolved.
