### ISSUE TITLE
Clipetty for TTY users

### ISSUE THREAD

**Issue by Shooooooooo** [hlissner/doom-emacs#2671]
**Describe the feature**
Hi, TTY user here. I have always find xclip package not as ideal as I wanted. Obviously, because it requires some sort of display server running in order to get it to work.
Recently, I cam across a reddit [post](https://www.reddit.com/r/emacs/comments/esx4w4/my_first_emacs_package_clipetty/) by author of [Clipetty](https://github.com/spudlyo/clipetty), a package which utilizes OSC 52 escape sequences to forward kill-ring-save content to supported terminals directly without display server in-between.
I didn't know this terminal feature existed, but it sounded like exactly what I was hoping for. Thus, I gave it a try for about a month and it works amazing. (even through TMUX!)

This feature requires clipboard feature to be turned on in terminal emulators.
For xterm, following line should be added in ~/.Xresources
`XTerm.vt100.allowWindowOps: true`
For iTerm2, it's in Preferences/Selection/Application in terminal may access clipboard

It is picky about the terminal emulator, but I think it's much more reliable than X forward based mechanism.

Please consider adding this feature. I can also contribute if you can point me to the correct place for adding this feature. (Through editor module? or implement similar to xclip?)

Thanks!

**Comment by shanesveller** [comment]
I don't have a stance on whether this would help, but `xclip` is the surface cause of my issue #2617. Just remarking here to help link the discussions for folks.

**Comment by whjiang** [comment]
+1 for this feature.

**Comment by hlissner** [comment]
Just a heads up. As of 0a4841b Doom has a `:os tty` module for clipboard integration (also cursor-shape changing across evil states).

1. It will install `xclip` by default.
2. Enable `:os (tty +osx)` to enable `clipetty` instead (i.e. won't install xclip).
3. Or don't use it at all, if you don't like either implementation -- in either case, they are now opt-in.

Hope that's helpful!

**Comment by shanesveller** [comment]
Anecdotally I seem to be getting along very happily with the new `tty` module - thanks Henrik! 😁

**Comment by Shooooooooo** [comment]
Thanks Henrik. There is a typo in the comment above. Should've be `+osc` instead of `+osx`. XD
