### ISSUE TITLE
doom upgrade reports "Encountered error with magit"

### ISSUE THREAD

**Issue by whjiang** [hlissner/doom-emacs#2674]
After a new installation, I run `doom upgrade` and reports error:
```
> Updating packages (this may take a while)...
  ! (95/209) Encountered error with magit
    x (error Failed to run "git"; see buffer *straight-process*)
      - fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
      Use '--' to separate paths from revisions, like this:
      'git <command> [<revision>...] -- [<file>...]'
      HEAD

  > (172/209) Fetching f...
x Encountered 1 error(s), the offending packages: magit
```

**Comment by hlissner** [comment]
Sorry for the late response. Do you still have this issue? This may have been resolved in recent updates of Doom. Otherwise, try deleting `~/.emacs.d/.local/straight/{repos,build}/magit` before running `doom upgrade` again.

**Comment by whjiang** [comment]
Thanks a lot. I resolved this issue using the exact solution you mentioned.
