### ISSUE TITLE
bin/doom upgrade origin-checker doesn't account for .gitconfig rewrites

### ISSUE THREAD

**Issue by utrack** [hlissner/doom-emacs#2679]
I'm not exactly sure if Doom itself does that, but here goes:

I have a global .gitconfig with these lines for convenience:
```
[url "git://github.com/"]
    insteadOf = https://github.com/
[url "git@github.com:"]
    pushInsteadOf = "git://github.com/"
[url "git@github.com:"]
  pushInsteadOf = "https://github.com/"
```

Each time I do `bin/doom upgrade`, I get this prompt for every package I have:
```
> Updating packages (this may take a while)...
  > In repository "straight.el", remote "origin" has URL
    "git://github.com/raxod502/straight.el.git"
  but recipe specifies a URL of
    "https://github.com/raxod502/straight.el.git"

       1) Abort
       2) Rename remote "origin" to "origin-1", re-create "origin" with correct URL, and fetch
       3) Rename remote "origin" manually, re-create it with correct URL, and fetch
       4) Delete remote "origin", re-create it with correct URL, and fetch (Recommended)
       5) Delete remote "origin", re-create it with manually set URL, and fetch
```

Removing this config fixes the problem. It seems that a remote checker doesn't account for rewrites done in git-config.

**Comment by hlissner** [comment]
I'm not sure Doom can do anything about this. Perhaps it should be brought up upstream, to [straight.el](https://github.com/raxod502/straight.el)'s dev. Then again, I'm not sure it's a good idea to ignore .gitignore entirely, either, as there could be legitimate use cases (e.g. setting proxies).

On the other hand, you could try [a conditional include in your .gitconfig](https://github.com/raxod502/straight.el/issues/353#issuecomment-463805062), to disable the rewrite for Doom, specifically.

**Comment by hlissner** [comment]
Sorry for the tremendously late reply. I've added a `doom doctor` check to complain about `git://github.com`->`https://github.com` being rewritten in your gitconfig, along with an explanation for why it happens and how to address the issue. I consider this an acceptable solution, in the absence of a universal one. Thanks for bringing it to my attention!

**Comment by raxod502** [comment]
This is certainly a bug in `straight.el` and is being worked on upstream: https://github.com/raxod502/straight.el/issues/750
