### ISSUE TITLE
Org-mode agenda weekday 

### ISSUE THREAD

**Issue by UtamaruMonster** [hlissner/doom-emacs#268]
When i do C-c . the agenda view week starts from Sunday. I want it to be Monday.
Tried ```org-agenda-start-on-weekday 1``` set it in org/config.el does not work. My question is how to set or-agenda to Monday?

**Comment by dywedir** [comment]
Try `setq calendar-week-start-day 1`

**Comment by UtamaruMonster** [comment]
As pointed out by @dywedir ```setq calendar-week-start-day 1``` worked. Thank you
