### ISSUE TITLE
no org-link from Gnus inbox 

### ISSUE THREAD

**Issue by joseph-vidal-rosset** [hlissner/doom-emacs#2690]
Hello,

In my ~/.doom.d/config.el  i have this code:

```elisp
(after! org
(setq org-capture-templates
      '(("t" "todo" entry (file+headline "~/Dropbox/Orgzly/todo.org" "Tasks")
         "* TODO [#A] %?\n [[~/Dropbox/Orgzly/links.org::%(org-insert-time-stamp (org-read-date nil t \"%:date\"))]] \n* %(org-insert-time-stamp (org-read-date nil t \"%:date\")) %a " )
       ("n"      ; key
"note"   ;name
entry    ;type
(file+headline "~/Dropbox/Orgzly/notes.org" "Notes")  ;target
         "* NOTE du %(org-insert-time-stamp (org-read-date nil t \"%:date\")) \n Voir %a " ; template
                                        ))))
```

it worked in my emacs for getting Email links from my Gnus in imap, but the link is not produced with Doom Emacs:  as if the Inbox buffer was locked to be protected by Doom Emacs (there is the image of a padlock below, padlock that I did not saw with my emacs alone. 
I need help, because I tried many things, but without result.
i do not know if the explanation lies in the fact that the package org-gnus cannot be installed.  I give the doom info below. 
![Capture d’écran_2020-03-09_18-26-50](https://user-images.githubusercontent.com/8275626/76240960-645f2580-6234-11ea-8ec3-63863b2d1f5c.png)

Best wishes, 
Jo. 

**Additional information**
-  OS:  GNU/Linux Debian 10
- joseph@debian ~ $ emacs --version
GNU Emacs 26.3

- Do you have additional material or links to resources that could help clarify
  what you are trying to do?

**System information**
<details><pre>
Package error: (error Could not find package org-gnus in recipe repositories: (org-elpa melpa gnu-elpa-mirror emacsmirror-mirror))
((emacs
  (version . "26.3")
  (features . "XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK2 X11 XDBE XIM THREADS")
  (build . "févr. 15, 2020")
  (buildopts "")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD cb4f9b86c 2020-03-06 16:37:57 -0500")
  (dir . "~/.doom.d/"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/bin/bash")
  (uname . "Linux 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64")
  (path "/usr/local/bin" "/usr/bin" "/bin" "/usr/local/games" "/usr/games" "~/MEGA/Prouveurs/Athena/" "~/src/eclipse_basic/bin/x86_64_linux" "/usr/local/libexec/emacs/26.3/x86_64-pc-linux-gnu"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor file-templates fold snippets :emacs dired electric vc :term shell :checkers syntax spell grammar :tools (eval +overlay) lookup magit :lang coq data emacs-lisp latex markdown (org +dragndrop +pandoc +present) sh :config (default +bindings +smartparens))
  (packages
   (tabbar)
   (tool-bar+)
   (bm)
   (gnus-x-gm-raw)
   (org-mime)
   (gnus-alias)
   (all-the-icons-gnus)
   (w3m)
   (bbdb)
   (auto-dictionary)
   (flyspell)
   (cdlatex)
   (gnorb)
   (org-context)
   (outorg)
   (org-gnus))
  (unpin "n/a")
  (elpa "yaxception" "tabbar" "org-plus-contrib" "org-bullets" "org" "log4e" "gnus-x-gm-raw" "gnus-summary-repo" "gnus-desktop-notify" "gnus-alias" "gnorb" "bbdb")))

</pre></details>

**Comment by hlissner** [comment]
Try

```elisp
(add-to-list 'org-modules 'ol-gnus)
```

**Comment by joseph-vidal-rosset** [comment]
Many thanks it works now !
I am really happy, because I felt in love with Doom Emacs. You made a very impressive and very useful work ! THANKS !
