### ISSUE TITLE
Improve company for :lang ruby

### ISSUE THREAD

**Issue by otavioschwanck** [hlissner/doom-emacs#2693]
For some reason, the autocomplete on Doom Emacs is weaker than a vanilla emacs.

A example:

Doom Emacs:
![Captura de tela de 2020-03-09 20-11-45](https://user-images.githubusercontent.com/9551316/76253820-44832e00-6243-11ea-931a-525213885e2e.png)

Doom cant find the class name, even pressing C-SPC.

On vanilla emacs (just company + company-robe):
![Captura de tela de 2020-03-09 20-18-19](https://user-images.githubusercontent.com/9551316/76253862-582e9480-6243-11ea-9a20-970a64c4df26.png)

I'm tried to figure it out whats happening but dont find anything.

**Comment by hlissner** [comment]
What is the value of `company-backends` in vanilla emacs?

**Comment by otavioschwanck** [comment]
> What is the value of `company-backends` in vanilla emacs?

company-backends is a variable defined in ‘company.el’.
Its value is
(company-robe company-tern company-bbdb company-eclim company-semantic company-clang company-xcode company-cmake company-capf company-files
	      (company-dabbrev-code company-gtags company-etags company-keywords)
	      company-oddmuse company-dabbrev)
Original value was 
(company-bbdb company-eclim company-semantic company-clang company-xcode company-cmake company-capf company-files
	      (company-dabbrev-code company-gtags company-etags company-keywords)
	      company-oddmuse company-dabbrev)

**Comment by hlissner** [comment]
I suspect `company-robe` is simply poor at code completion, and what's really giving you `CheckIpLedgerMovements` in vanilla Emacs is the `company-dabbrev-code` backend, which collects its candidates from all open buffers in the same major mode. 

With doom, try this:

```elisp
;; add to ~/.doom.d/config.el
(after! robe
  (set-company-backend! 'enh-ruby-mode '(company-robe company-dabbrev-code)))
```

**Comment by otavioschwanck** [comment]
> ```emacs-lisp
> (after! robe
>   (set-company-backend! 'enh-ruby-mode '(company-robe company-dabbrev-code)))
> ```

It gets a little better, but only works when have another buffer with it.  On vanilla, works without it.  Maybe the reason is the tags ?

**Comment by otavioschwanck** [comment]
i added this backend in this PR https://github.com/hlissner/doom-emacs/pull/2694

**Comment by otavioschwanck** [comment]
@hlissner i noticed that when you restart the robe server (SPC m R) (robe-rails-refresh), it start to work perfectly.  Maybe we can put a hook after robe-rails-refresh to immediately runs robe-rails-refresh ?  The only issue is that robe-start command is asynchronous

**Comment by dgutov** [comment]
>  noticed that when you restart the robe server (SPC m R) (robe-rails-refresh)

That doesn't actually restart the server, just asks Rails to refresh all it knows from the disk. Also forces the autoloads to be eagerly loaded.
