### ISSUE TITLE
Limit rg line length?

### ISSUE THREAD

**Issue by sebastiansturm** [hlissner/doom-emacs#2695]
when using `+ivy-file-search` in directories containing minified JavaScript or other files with excessively long lines, Emacs can slow down to a crawl (especially when `ivy-occur` is used on the results). What do you think about adding something like `"--max-columns 200"` and `"--max-columns-preview"` to the list of default `rg` arguments?

**Comment by hlissner** [comment]
Perhaps this should be suggested [upstream](https://github.com/abo-abo/swiper)?

**Comment by sebastiansturm** [comment]
maybe, yes; I opened https://github.com/abo-abo/swiper/issues/2482, so this issue can be closed now
