### ISSUE TITLE
Running M-x +treemacs/toggle wipes all workspaces and projects

### ISSUE THREAD

**Issue by mjanonis** [hlissner/doom-emacs#2696]
**What did you expect to happen?**
Running M-x +treemacs/toggle (SPC o p) leaves all workspaces intact.

**What actually happened?**
Running M-x +treemacs/toggle (SPC o p) clears previously defined workspaces/projects.

**Additional details:**
M-x treemacs behaves normally, only M-x +treemacs/toggle clears the workspaces out.

\*Messages\* contents after running M-x +treemacs/toggle:
<details><pre>
Doom loaded 197 packages across 36 modules in 0.722s
Package cl is deprecated
Loading /home/user/.config/emacs/.local/cache/recentf...done
Buffer has been modified; could not load undo-tree history
Wrote /home/user/.config/emacs/.local/cache/undo-tree-hist/.!home!user!.config!emacs!.local!cache!treemacs-persist.~undo-tree~.zst
Wrote /home/user/.config/emacs/.local/cache/treemacs-persist
".local/cache/treemacs-persist" 3L, 92C written
Wrote /home/user/.config/emacs/.local/cache/undo-tree-hist/.!home!user!.config!emacs!.local!cache!treemacs-persist.~undo-tree~.zst [2 times]
Wrote /home/user/.config/emacs/.local/cache/treemacs-persist
".local/cache/treemacs-persist" 1L, 10C written
Wrote /home/user/.config/emacs/.local/cache/undo-tree-hist/.!home!user!.config!emacs!.local!cache!treemacs-persist.~undo-tree~.zst [2 times]
Wrote /home/user/.config/emacs/.local/cache/treemacs-persist
".local/cache/treemacs-persist" 3L, 35C written
Wrote /home/user/.config/emacs/.local/cache/undo-tree-hist/.!home!user!.config!emacs!.local!cache!treemacs-persist.~undo-tree~.zst
</pre></details>

**Steps to reproduce:**
1. Run M-x treemacs-edit-workspaces
2. Populate it with some entries
3. Restart Emacs
4. Run M-x treemacs and observe everything running normally
5. Run M-x treemacs again to close it
6. Run M-x +treemacs/toggle

**System information:**
<details><pre>
emacs   version    28.0.50
        features   XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP
        build      Mar 10, 2020
        buildopts  (--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --mandir=/usr/share/man --with-sound=alsa --with-modules --without-gconf --without-gsettings --enable-link-time-optimization --with-x-toolkit=gtk3 --without-xaw3d --without-m17n-flt --with-cairo 'CFLAGS=-march=native -O2 -pipe -fno-plt -g -flto -fuse-linker-plugin -g -flto -fuse-linker-plugin -s -fuse-ld=gold' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now)
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop 0fafba7ee 2020-03-09 14:04:25 -0400
        dir        ~/.config/doom/
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /usr/bin/zsh
        uname      Linux 5.5.8-arch1-1 #1 SMP PREEMPT Fri, 06 Mar 2020 00:57:33 +0000 x86_64
        path       (/usr/local/sbin /usr/local/bin /usr/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /usr/lib/emacs/28.0.50/x86_64-pc-linux-gnu/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold snippets :emacs dired electric vc :checkers syntax spell :tools (eval +overlay) lookup lsp magit :lang (cc +lsp) data emacs-lisp markdown (org +dragndrop +present) (python +lsp) sh :config (default +bindings +smartparens))
        packages   (n/a)
        unpin      (n/a)
        elpa       (n/a)
</pre></details>

**Comment by hlissner** [comment]
This is how `+treemacs/toggle` works. To quote its docstring (see `SPC h f +treemacs/toggle` or `C-h v +treemacs/toggle`):

```
Ensures that only the current project is present and all other projects have
been removed.

Use `treemacs' command for old functionality."
```

**Comment by mjanonis** [comment]
Well this is embarrassing, I can't believe I missed that. Thanks for the help!
