### ISSUE TITLE
How integrating all LaTeX for emails in org-mode with Doom Emacs?

### ISSUE THREAD

**Issue by joseph-vidal-rosset** [hlissner/doom-emacs#2699]
Hi Henrik,

In my previous emacs setup (i mean without Doom Emacs), I had a convenient integration of LaTeX for emails in org-mode inside Gnus.  I just tested this feature in Doom Emacs and this does not work: some macros given by LaTeX packages fail, and it is probably the same for org-ref that is more than helpful for the bibliography. I guess that something lacks in my config.el, probably the mention of a path, but I do not know what exactly, hence my post. 

All the best, 

Jo. 

PS: I just saw another similar post that makes believe that maybe you will not have the reply to my question, but there will be maybe help on Discord. My problem is that in trying Discord I saw that I was not allowed to ask questions...  I do not understand how Discord works. 

**System information**
<details><pre>
joseph@debian ~/.emacs.d/bin $ ./doom info
((emacs
  (version . "26.3")
  (features . "XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK2 X11 XDBE XIM THREADS")
  (build . "févr. 15, 2020")
  (buildopts "")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD cb4f9b86c 2020-03-06 16:37:57 -0500")
  (dir . "~/.doom.d/"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/bin/bash")
  (uname . "Linux 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64")
  (path "/usr/local/bin" "/usr/bin" "/bin" "/usr/local/games" "/usr/games" "~/MEGA/Prouveurs/Athena/" "~/src/eclipse_basic/bin/x86_64_linux" "~/MEGA/Prouveurs/Athena/" "~/src/eclipse_basic/bin/x86_64_linux" "~/MEGA/Prouveurs/Athena/" "~/src/eclipse_basic/bin/x86_64_linux" "~/MEGA/Prouveurs/Athena/" "~/src/eclipse_basic/bin/x86_64_linux" "~/MEGA/Prouveurs/Athena/" "~/src/eclipse_basic/bin/x86_64_linux" "~/MEGA/Prouveurs/Athena/" "~/src/eclipse_basic/bin/x86_64_linux" "~/MEGA/Prouveurs/Athena/" "~/src/eclipse_basic/bin/x86_64_linux" "~/MEGA/Prouveurs/Athena/" "~/src/eclipse_basic/bin/x86_64_linux" "~/MEGA/Prouveurs/Athena/" "~/src/eclipse_basic/bin/x86_64_linux" "~/MEGA/Prouveurs/Athena/" "~/src/eclipse_basic/bin/x86_64_linux" "~/MEGA/Prouveurs/Athena/" "~/src/eclipse_basic/bin/x86_64_linux" "~/MEGA/Prouveurs/Athena/" "~/src/eclipse_basic/bin/x86_64_linux" "~/MEGA/Prouveurs/Athena/" "~/src/eclipse_basic/bin/x86_64_linux" "/usr/local/libexec/emacs/26.3/x86_64-pc-linux-gnu"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor file-templates fold snippets :emacs dired electric vc :term shell :checkers syntax spell grammar :tools (eval +overlay) lookup magit :lang coq data emacs-lisp latex markdown (org +dragndrop +pandoc +present) sh :config (default +bindings +smartparens))
  (packages
   (tabbar)
   (tool-bar+)
   (bm)
   (gnus-x-gm-raw)
   (org-mime)
   (gnus-alias)
   (all-the-icons-gnus)
   (w3m)
   (bbdb)
   (auto-dictionary)
   (flyspell)
   (cdlatex)
   (gnorb)
   (org-context)
   (outorg))
  (unpin "n/a")
  (elpa "yaxception" "tabbar" "org-plus-contrib" "org-bullets" "org" "log4e" "gnus-x-gm-raw" "gnus-summary-repo" "gnus-desktop-notify" "gnus-alias" "gnorb" "bbdb")))

</pre></details>

**Comment by hlissner** [comment]
You appear to be installing a lot of packages through ELPA. This may cause conflicts. Run `doom purge && doom sync` on the command line and see if anything changes.

**Comment by hlissner** [comment]
> My problem is that in trying Discord I saw that I was not allowed to ask questions... I do not understand how Discord works.

A single channel should be visible to you called `#readme`. If you read it, it tells you how to get into the server so that you can ask questions.

**Comment by joseph-vidal-rosset** [comment]
Many thanks Henrik, 
It works better indeed. I have probably some packages to install. I have the following error message

> Creating LaTeX preview... done.
Creating LaTeX preview... done.
Creating LaTeX preview... done.
Creating LaTeX Image... [2 times]
org-compile-file: File "/tmp/orgtextkLIjn.dvi" wasn’t produced.  Please adjust ‘dvipng’ part of ‘org-preview-latex-process-alist’.
Creating LaTeX Image... [2 times]
org-compile-file: File "/tmp/orgtex5mEQKo.dvi" wasn’t produced.  Please adjust ‘dvipng’ part of ‘org-preview-latex-process-alist’.

Thanks for your kind help. Doom Emacs is terrific !

Best wishes,

Jo.

**Comment by joseph-vidal-rosset** [comment]
Hi Henrik,

I have solved the problem. The config.el file needed this part of my old init.el: 
`
(after! org
(setq org-latex-default-packages-alist
      '(("AUTO" "inputenc" t)
;;("english,francais" "babel" t)
("" "siunitx" nil)
("" "lmodern" nil)
("T1" "fontenc" t)
("" "natbib" t)
("" "graphicx" t)
("" "etex" t)
("" "xcolor" t)
("normalem" "ulem" t)
("" "textcomp" t)
("" "marvosym" t)
("" "wasysym" t)
("" "amssymb")
("" "amsmath" t)
("" "amsthm" t)
("" "qtree" t)
("" "bussproofs" t)
("" "proof" t)
("" "cancel" t)
("" "url" t)
("" "pdflscape" t)
("" "fontawesome" t)
("" "tikz" t)
 ;("" "fourier" t)
;("" "smfenum" t)
;("" "smfthm" t)
        ("linktocpage,pdfstartview=FitH,colorlinks,linkcolor=blue,anchorcolor=blue,citecolor=blue,filecolor=blue,menucolor=blue,urlcolor=blue" "hyperref" nil)
       )
      )
)
`
Now all works correctly. 
Best wishes, 
Jo.
