### ISSUE TITLE
Status of this project

### ISSUE THREAD

**Issue by vsr625** [hlissner/doom-emacs#270]
Hi @hlissner , really like this emacs configuration. I've been following this project from the past 1500 commits. and I really like the way you improved it so much over that period. 
I just wanted to know the status of this project, since you aren't updating it much lately, like if this is permanent or just temporary, I'm not trying to be rude here or asking for an ETA, i'm just asking out of curiosity.

**Comment by hlissner** [comment]
Hey there! Not at all, it's a fair question.

Doom is still active and my absence is definitely temporary. I've just returned to Canada after a 7 month stay in Denmark, came down with a cold I'm trying to sleep off, and have much preparing and work to do before the family visits for the Christmas season, so I'll be absent for, at most, another week while things settle down.
