### ISSUE TITLE
Get themes other than doom-one to be properly rendered on the terminal

### ISSUE THREAD

**Issue by ylabidi** [hlissner/doom-emacs#2701]
Hi,
I mostly use emacs on the terminal (linux / kde's konsole). And so far I've been unable to get any theme to be properly rendered on the terminal other than `doom-one`. When I do change the theme in the configuration, the change is immediate in gui-based emacs, but in the terminal, the original theme background is never rendered, and the background is always black.
Is there something I am missing ?

**Comment by hlissner** [comment]
Please do not ignore the issue template in the future. It asks you to include:

1. Your `M-x doom/info`,
2. The code and/or method you used to change the theme,
3. The exact steps to reproduce your issue.

All of which is vital information for me to diagnose your issues.

**Comment by ylabidi** [comment]
Sorry about that.
1. `M-x doom/info`:
```
emacs   version    26.3
        features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2
        build      Aug 29, 2019
        buildopts  (--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-modules 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now)
        windowsys  nil
        daemonp    daemon
doom    version    2.0.9
        build      HEAD -> develop, origin/develop, origin/HEAD 58a68adb5 2020-03-04 23:02:15 -0500
        dir        ~/.doom.d/
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /usr/bin/zsh
        uname      Linux 5.5.5-arch1-1 #1 SMP PREEMPT Thu, 20 Feb 2020 18:23:09 +0000 x86_64
        path       (/bin /usr/bin /usr/local/bin /usr/local/sbin /usr/lib/emacs/26.3/x86_64-pc-linux-gnu/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold multiple-cursors rotate-text snippets :emacs dired electric ibuffer vc :checkers syntax :tools (eval +overlay) (lookup +docsets) magit :lang data emacs-lisp markdown (org +dragndrop +present) ruby python sh :config (default +bindings +smartparens))
        packages   (n/a)
        unpin      (n/a)
        elpa       (n/a)
```
2. To change the theme, I modified `~/.doom.d/config.el`:
```
(setq doom-theme 'doom-nord-light)
```
Expectation is for the theme to be properly rendered in the terminal, matching what is rendered in the gui.
What is observed: theme background is never rendered.
3. The exact steps to reproduce the problem:
 - modify the theme as mentioned above
 - issue `~/emacs.d/bin/boom sync` to refresh
 - start emacs in the terminal. background is always black.

**Comment by hlissner** [comment]
> Expectation is for the theme to be properly rendered in the terminal, matching what is rendered in the gui.
> start emacs in the terminal. background is always black.

Ah, this is simply a limitation of the terminal. Emacs is limited to 256 colors there. In order for you to get a matching background you need to set your terminal background to the color you want (#D8DEE9, in the case of doom-nord-light). How you do that depends on what terminal you use.

**Comment by hlissner** [comment]
I'll assume due to inactivity that this issue was resolved. Feel free to follow up here if that isn't the case!
