### ISSUE TITLE
Personal function for copy class name dont work on Doom

### ISSUE THREAD

**Issue by otavioschwanck** [hlissner/doom-emacs#2702]
I've the following function from my personal .emacs (vanilla emacs):

```
(defun endless/ruby-copy-class-name ()
  (interactive)
  (save-excursion
    (let ((name nil)
          (case-fold-search nil))
      (skip-chars-backward (rx (syntax symbol)))
      (when (looking-at-p "\\_<[A-Z]")
        (setq name (endless/-ruby-symbol-at-point)))
      (while (ignore-errors (backward-up-list) t)
        (when (looking-at-p "class\\|module")
          (save-excursion
            (forward-word 1)
            (skip-chars-forward "\r\n[:blank:]")
            (setq name (if name
                           (concat (endless/-ruby-symbol-at-point) "::" name)
                         (endless/-ruby-symbol-at-point))))))
      (kill-new name)
      (message "Copied %s" name))))


(defun endless/-ruby-symbol-at-point ()
  (let ((l (point)))
    (save-excursion
      (forward-sexp 1)
      (buffer-substring l (point)))))
```

It works on vanilla emacs, but in doom dont.

It is a really good function, when have nested class names, like:
module X
 module Y
   module Z
    class N

It copy X::Y::Z::N to the clipboard, its perfect for debbuging on console.

I've debugged and the ruby-symbol-at-point returns nil.

When i make it work on doom, i'll add this to :lang ruby module.  Whats the best way to do it ?

**Comment by hlissner** [comment]
> I've debugged and the ruby-symbol-at-point returns nil.

Use `(symbol-at-point)` or `(thing-at-point 'symbol)` instead.

> When i make it work on doom, i'll add this to :lang ruby module. Whats the best way to do it ?

This would need some consideration. I don't know where it would fit in, what keybinds, what keymaps, etc.

> It is a really good function, when have nested class names, like:
> module X
> module Y
> module Z
> class N

Can you write tests for this?

-----

Could you ask future elisp/emacs questions [on our Discord](https://discord.gg/qvGgnVx). I don't want to inundate Doom's issue tracker with usage and elisp questions more than it already has.

**Comment by otavioschwanck** [comment]
> > I've debugged and the ruby-symbol-at-point returns nil.
> 
> Use `(symbol-at-point)` or `(thing-at-point 'symbol)` instead.
> 
> > When i make it work on doom, i'll add this to :lang ruby module. Whats the best way to do it ?
> 
> This would need some consideration. I don't know where it would fit in, what keybinds, what keymaps, etc.
> 
> > It is a really good function, when have nested class names, like:
> > module X
> > module Y
> > module Z
> > class N
> 
> Can you write tests for this?
> 
> Could you ask future elisp/emacs questions [on our Discord](https://discord.gg/qvGgnVx)? I don't want to inundate Doom's issue tracker with usage and elisp questions more than it already has.

How can i write tests ?
