### ISSUE TITLE
Set up GitHub Sponsor account for Doom Emacs

### ISSUE THREAD

**Issue by dive** [hlissner/doom-emacs#2703]
## Describe the feature

Doom Emacs is quite lovely and save a lot of time to me, and I am pretty sure I am not alone. So, **it would be nice to support the project** as I do for all OSS that save me time. I see that it is already possible to support it via PayPal and LiberaPay, but **GitHub Sponsor feature** is the most reliable and convenient tool from my perspective. And I know a lot of people who moved to GitHub to keep track of all the OSS projects they support. Please, set up the GitHub Sponsor feature if there is no reason not to.

If you need examples, there are some Emacs related projects with enabled GitHub Sponsor feature:

* [@abo-abo](https://github.com/sponsors/abo-abo) - Ivy/Swiper/Counsel, Hydra, etc.;
* [@bzg](https://github.com/sponsors/bzg) - org-mode;
* [@tarsius](https://github.com/sponsors/tarsius) - Magit.

## System information
<details><pre>
emacs   version    27.0.90
        features   RSVG IMAGEMAGICK GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS JSON PDUMPER LCMS2 GMP
        build      Mar 09, 2020
        buildopts  (--disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus/HEAD-4537976/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus/HEAD-4537976 --with-xml2 --without-dbus --with-gnutls --with-imagemagick --with-json --with-modules --with-rsvg --with-ns --disable-ns-self-contained)
        windowsys  ns
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop 0fafba7ee 2020-03-09 14:04:25 -0400
        dir        /Volumes/Extended/Projects/dotfiles/home/.config/doom/
system  type       darwin
        config     x86_64-apple-darwin19.3.0
        shell      /bin/zsh
        uname      Darwin 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64
        path       (/usr/local/bin /usr/bin /bin /usr/sbin /sbin /usr/local/sbin /usr/local/Cellar/emacs-plus/HEAD-4537976/libexec/emacs/27.0.90/x86_64-apple-darwin19.3.0/)
config  envfile    envvar-file
        elc-files  1
        modules    (:completion company ivy :ui doom doom-quit hl-todo modeline ophints (popup +all +defaults) pretty-code vc-gutter vi-tilde-fringe window-select workspaces zen :editor file-templates fold rotate-text snippets :emacs dired electric ibuffer vc :term eshell vterm :checkers syntax :tools (eval +overlay) (lookup +docsets) magit pdf :lang data emacs-lisp kotlin markdown (org +dragndrop +hugo +pandoc +pomodoro +present) php plantuml python ruby rust sh swift :app irc (rss +org) :config (default +bindings +smartparens))
        packages   ((org-super-agenda) (deadgrep) (pocket-reader))
        unpin      (n/a)
        elpa       (s request rainbow-identifiers pocket-reader pocket-lib ov org-web-tools kv ht esxml dash)
</pre></details>

**Comment by brotzeit** [comment]
I can understand if maintainers don't want to use github for this, but I also tend to use the github sponsor feature than patreon etc., although I use both...

**Comment by hlissner** [comment]
It's been requested a few times on our Discord. I'm on board with it, but haven't gotten around to it yet. I'll let you know once I have.

**Comment by karlicoss** [comment]
Just want to say that Liberapay supports recurring payments and is very pleasant to use. Maybe that's worth mentioning in the readme, I'd imagine many people have never seen it before :)

**Comment by kiranshila** [comment]
Another bump for this. I would also like to have my recurring sponsorships for OSS be in one place.

**Comment by jtpavlock** [comment]
I'm not sure how payment via liberapay vs github sponsor for credit cards works, but on liberapay it warned me of high fees if I setup a monthly renewal. I assume that means you'll get less of the overall donation @hlissner? If the fee structure is different/more in your favor for github sponsors that might be another reason to add it.

**Comment by hlissner** [comment]
Sorry for taking so long to do this! My Github sponsors profile [is finally up](https://github.com/sponsors/hlissner). With that, I'll consider this resolved. Thanks for the suggestion. From what I've heard and read, it seems Github Sponsors is much a better system than what liberapay offers (no fees for now and its integration with github will make it easy to add tier rewards for sponsors in the future).
