### ISSUE TITLE
Minor formatter bug?

### ISSUE THREAD

**Issue by sebastiansturm** [hlissner/doom-emacs#2704]
Updating to the latest version, I'm running into cases of undefined `format-all--mode-table` (with ocamlformat in that case, didn't investigate in detail). Unless I messed up something with my config, I guess https://github.com/lassik/emacs-format-all-the-code/commit/033d0f3c253c07d8f087a956d73e81133b78bb31 is the problem, as it changed `format-all--mode-table` to `format-all--language-table`? Also, `format/autoload/settings.el` spells `format-all-mode-table` with a single hyphen in two places

**Comment by hlissner** [comment]
Unfortunately, the problem requires a more involved solution than simply renaming the variable. I've pinned format-all to https://github.com/lassik/emacs-format-all-the-code/commit/033d0f3c253c07d8f087a956d73e81133b78bb31, before the change, which should fix the issue for you.

**Comment by sebastiansturm** [comment]
thank you!
