### ISSUE TITLE
company-files doesn't work after company-tide

### ISSUE THREAD

**Issue by sooqua** [hlissner/doom-emacs#2707]
**What did you expect to happen?**
This should work:
```elisp
(set-company-backend! 'js2-mode
    'company-files 'company-tide 'company-yasnippet)
```

**What actually happened?**
Files don't auto-complete **unless** `company-files` is **1st** on the list, but my `company-backends` is:
```elisp
(company-tide company-capf company-yasnippet company-files)
```
so it says "No completion found" for files.
I tried various hooks like `setq-hook` and `add-hook` to put `company-files` 1st on the list but it doesn't work like something is overriding it.

**System information:**
<details>

```
emacs   version    26.3
        features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2
        build      Aug 29, 2019
        buildopts  (--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-modules 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now)
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop cb4f9b86c 2020-03-06 16:37:57 -0500
        dir        ~/.config/doom/
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /usr/bin/zsh
        uname      Linux 5.5.8-arch1-1 #1 SMP PREEMPT Fri, 06 Mar 2020 00:57:33 +0000 x86_64
        path       (~/code/web/crwn-clothing/node_modules/.bin/ /usr/local/bin /usr/bin /bin /usr/local/sbin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl ~/.npm-packages/bin ~/.config/composer/vendor/bin /usr/lib/emacs/26.3/x86_64-pc-linux-gnu)
config  envfile    nil
        elc-files  0
        modules    (:completion company ivy :ui doom hl-todo indent-guides modeline nav-flash ophints (popup +all +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold multiple-cursors rotate-text snippets :emacs dired electric ibuffer vc :term eshell :checkers syntax spell :tools (eval +overlay) (lookup +docsets) magit :lang cc data emacs-lisp go javascript lua markdown (org +dragndrop +present) php sh web :config (default +bindings +smartparens))
        packages   ((pkgbuild-mode) (package-lint) (livid-mode) (js-doc) (indium) (restclient) (company-restclient) (js-react-redux-yasnippets :recipe (:host github :repo sooqua/js-react-redux-yasnippets :files (*.el snippets))))
        unpin      (n/a)
        elpa       (n/a)
```
</details>

**Comment by hlissner** [comment]
That's how company works. It tries the list of backends, in succession, until one works, then stops there.

If you want to merge the candidates of all those backends, group them:

```elisp
(after! js2-mode
  (set-company-backend! 'js2-mode
    '(company-files company-tide company-yasnippet)))
```

Alternatively, use `C-x C-f` (`company-files`) and `C-x C-s` (`company-yasnippet`) to invoke them directly.

Hope that helps.

**Comment by sooqua** [comment]
> That's how company works. It tries the list of backends, in succession, until one works, then stops there.

But then why everything works fine when `company-files` is 1st on the list, but not the opposite? The code you provide results in this value of `company-backends` in `rjsx-mode`:
```elisp
(company-tide company-capf company-yasnippet
              (company-files :with company-tide company-yasnippet))
```
Which still doesn't complete file names

**Comment by sooqua** [comment]
How do I remove the `company-tide company-capf company-yasnippet` from the beginning?

**Comment by hlissner** [comment]
> But then why everything works fine when company-files is 1st on the list, but not the opposite? The code you provide results in this value of company-backends in rjsx-mode:

Because company tries each backend in the list _until_ the first one that works, then it stops. `company-files` worked, so it stops there. If another backend was before it, and it worked instead, then it never gets to `company-files`.

> How do I remove the company-tide company-capf company-yasnippet from the beginning and make my own list for rjsx-mode?

Use this instead:

```lisp
(setq-hook! 'rjsx-mode-hook
  company-backends '((company-files :with company-tide company-yasnippet)))
```

**Comment by sooqua** [comment]
> ```lisp
> (setq-hook! 'rjsx-mode-hook
>   company-backends '((company-files :with company-tide company-yasnippet)))
> ```

This results in `company-backends` value being:
```
 (company-tide company-capf company-yasnippet)
```

I don't know why.

**Comment by sooqua** [comment]
OK this did the trick:
```elisp
(when (featurep! :lang javascript)
  ;; Configure autocompletion
  (after! js2-mode
    (defun ~+company-javascript-init-h ()
      (set-company-backend! 'rjsx-mode '(company-files company-tide :with company-yasnippet company-capf)))
    (add-hook 'rjsx-mode-hook '~+company-javascript-init-h)))
```
