### ISSUE TITLE
How fixing org-links for Gnus in Doom Emacs ?

### ISSUE THREAD

**Issue by joseph-vidal-rosset** [hlissner/doom-emacs#2708]
Hi  Henrik,

I had an org-link setup with org-capture that works well with Gnus: when I see an email that requested a task, I org-link the email and I am able to find it in IMAP in folder "[Gmail]/Tous les messages" via this org-link. In my old setup, the org-link worked correctly and the message in folder "[Gmail]/Tous les messages"   appears:
![Capture d’écran_2020-03-11_10-34-13](https://user-images.githubusercontent.com/8275626/76403608-71d7f500-6385-11ea-8387-6a77016c559b.png)
But, very strangely in Gnus inside Doom Emacs, Gnus goes to the right folder, but tells me that the message has expired (while it is in fact expired in INBOX):
![Capture d’écran_2020-03-11_10-31-39](https://user-images.githubusercontent.com/8275626/76403594-6dabd780-6385-11ea-96aa-e638f4f284b8.png) 
I guess that something in my old init.el is not in my config.el or that I need a package. The last line of my config.el is 
`(setq org-link-search-must-match-exact-headline nil)
`
But this does not solve my problem. 

 
**System information**
<details><pre>
joseph@debian ~/.emacs.d/bin $ ./doom info
((emacs
  (version . "26.3")
  (features . "XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK2 X11 XDBE XIM THREADS")
  (build . "févr. 15, 2020")
  (buildopts "")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD cb4f9b86c 2020-03-06 16:37:57 -0500")
  (dir . "~/.doom.d/"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/bin/bash")
  (uname . "Linux 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64")
  (path "/usr/local/bin" "/usr/bin" "/bin" "/usr/local/games" "/usr/games" "~/MEGA/Prouveurs/Athena/" "~/src/eclipse_basic/bin/x86_64_linux" "~/MEGA/Prouveurs/Athena/" "~/src/eclipse_basic/bin/x86_64_linux" "~/MEGA/Prouveurs/Athena/" "~/src/eclipse_basic/bin/x86_64_linux" "/usr/local/libexec/emacs/26.3/x86_64-pc-linux-gnu"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor file-templates fold snippets :emacs dired electric vc :term shell :checkers syntax spell grammar :tools (eval +overlay) lookup magit :lang coq data emacs-lisp latex markdown (org +dragndrop +pandoc +present) sh :config (default +bindings +smartparens))
  (packages
   (tabbar)
   (tool-bar+)
   (bm)
   (gnus-x-gm-raw)
   (gnus-summary-ext)
   (gnus-alias)
   (all-the-icons-gnus)
   (org-mime)
   (w3m)
   (bbdb)
   (auto-dictionary)
   (flyspell)
   (cdlatex)
   (gnorb)
   (org-context)
   (outorg)
   (vlf))
  (unpin "n/a")
  (elpa "n/a")))
</pre></details>

**Comment by joseph-vidal-rosset** [comment]
I must complete the description above. If Gnus is not open, the link open Gnus and the search in the folder fails as the previous image showed it. But once Gnus is open on the right folder, the link succeed to provide the email. It is therefore a minor "bug".

**Comment by hlissner** [comment]
I'm afraid I won't be of much help here. I've never used gnus and Doom doesn't have a gnus module. If you disable the `:lang org` module, does that fix the problem?

**Comment by joseph-vidal-rosset** [comment]
Henrik, never mind, you are very kind to reply. I am ashamed to tell you that I do not know how to disable this module, I am a real newbie with Doom Emacs, can you tell me how to do it? I apologize if I waste your time.

**Comment by joseph-vidal-rosset** [comment]
Hi Henrik, 
I persist in trying to find the solution. I have made another installation, keeping of course my ~/.doom.d/   Here is the result of ./doom doctor:

> joseph@debian ~/.emacs.d/bin $ ./doom doctor
The doctor will see you now...

> Checking your Emacs version...
> Checking for Emacs config conflicts...
> Checking for private config conflicts...
> Checking for stale elc files...
> Checking Doom Emacs...
  ✓ Initialized Doom Emacs 2.0.9
  ✓ Detected 40 modules
  ✓ Detected 157 packages
  > Checking Doom core for irregularities...
    ! Couldn't find the `fd' binary; project file searches will be slightly slower
    ! Couldn't find the `rg' binary either; project file searches will be even slower
    ! Your $HOME is recognized as a project root
      Doom will disable bottom-up root search, which may reduce the accuracy of
      project detection.
    Found font material-design-icons.ttf
    Found font weathericons.ttf
    Found font octicons.ttf
    Found font fontawesome.ttf
    Found font file-icons.ttf
    Found font all-the-icons.ttf
  > Checking for stale elc files in your DOOMDIR...
  > Checking your enabled modules...
    > :tools direnv
      ! Couldn't find direnv executable
  x org is not installed
    > :lang python
      ! Couldn't find isort. Import sorting will not work.
      ! Couldn't find pipenv. pipenv support will not work.
      ! Couldn't find nosetests. Running tests through nose will not work.
    > :lang sh
      ! Couldn't find shellcheck. Shell script linting will not work


There are 8 warnings!
✓ Finished! (3.6805s)

**Comment by hlissner** [comment]
> If you disable the :lang org module, does that fix the problem?

> can you tell me how to do it?

To disable a module open `~/.doom.d/init.el`, find these lines below `:lang` and above `:email`:

```lisp
       ;;nix               ; I hereby declare "nix geht mehr!"
       ;;ocaml             ; an objective camel
       (org              ; organize your plain life in plain text
        +dragndrop       ; drag & drop files/images into org buffers
        ;;+hugo            ; use Emacs for hugo blogging
        ;;+jupyter        ; ipython/jupyter support for babel
        ;;+pandoc          ; export-with-pandoc support
        ;;+pomodoro        ; be fruitful with the tomato technique
        +present)        ; using org-mode for presentations
       ;;perl              ; write code no one else can comprehend
       ;;php               ; perl's insecure younger brother
```

Then comment out the `(org ...)` block:

```elisp
       ;;nix               ; I hereby declare "nix geht mehr!"
       ;;ocaml             ; an objective camel
       ;;(org              ; organize your plain life in plain text
       ;; +dragndrop       ; drag & drop files/images into org buffers
       ;; ;;+hugo            ; use Emacs for hugo blogging
       ;; ;;+jupyter        ; ipython/jupyter support for babel
       ;; ;;+pandoc          ; export-with-pandoc support
       ;; ;;+pomodoro        ; be fruitful with the tomato technique
       ;; +present)        ; using org-mode for presentations
       ;;perl              ; write code no one else can comprehend
       ;;php               ; perl's insecure younger brother
```

Then run `~/.emacs.d/bin/doom sync` in your terminal and restart Emacs.

**Comment by joseph-vidal-rosset** [comment]
Thanks Henrik for your patience. Unfortunately, I have to tell you that the problem persists, and I have tried many things. That is very strange (but interesting), because I have not this problem with Gnus in my old setup (i.e. without Doom), even with the most recent org packages (I just made an upgrade to check it). I will check again my old init.el and my config.el. I will keep you informed. Again, many thanks for all. I do not give up the project to use Doom Emacs, it is a minor problem.

**Comment by hlissner** [comment]
Sorry for the tremendously late response. Do you still have this issue? If so, does this fix it?

```elisp
(after! org
  (add-to-list 'org-modules 'ol-mu4e))
```

**Comment by joseph-vidal-rosset** [comment]
Hi Henrik, no problem, do not be sorry, you are very busy and you do all that you can to help people; you are a very nice guy, no doubt. 
I had tried these lines, I remember now, but it failed. Now I am back to my previous version of emacs (without Doom, unfortunately), and I saw that there is a difference between the org version: presently in my emacs 26.3 I have org  9.1.9 built-in   . I remember that the org version in Doom is higher . And please, have a look on this email on org-mode list: https://www.mail-archive.com/emacs-orgmode@gnu.org/msg127492.html  That is why we can reasonably conclude that that is an org issue and not a Doom issue. I hope that I help in turn !

**Comment by joseph-vidal-rosset** [comment]
Feel free to close the thread if you consider that it must consequently be closed. I do not know what you prefer. And again, many thanks for your very nice work.

**Comment by helgeblod** [comment]
To chime in, I'm using Gnus with Doom and Org-mode as described, and I can confirm that the following works for me at least:

```elisp
(after! org
  (add-to-list 'org-modules 'org-id)
  (add-to-list 'org-modules 'ol-gnus))
```

**Comment by joseph-vidal-rosset** [comment]
Many thanks !

I am not using Doom at the moment, but it is probably the occasion to try it again, it is a wonderful emacs version!

Best wishes,

Jo.

---
https://www.vidal-rosset.net

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
