### ISSUE TITLE
bin/doom compile breaks down (void-function evil-define-operator)

### ISSUE THREAD

**Issue by utrack** [hlissner/doom-emacs#2709]
**What did you expect to happen?**
I've tried to run `bin/doom compile`

**What actually happened?**
Looks like #229 had reappeared - the command failed:
```
...
> Byte-compiling your config (may take a while)...
...
  ✓ Compiled modules/ui/deft/config.el
  x
  There were breaking errors.

  Reverting changes...
x There was an unexpected error:
  Type: doom-error
  Message:
    Error in Doom Emacs core
  Data:
    byte-compile
    (void-function evil-define-operator)
```
debug run:
<details><pre>
Debugger entered--Lisp error: (void-function evil-define-operator)
  (evil-define-operator +evil:apply-macro (beg end) "Apply macro to each line." :move-point nil (interactive "<r>") (let ((register (or evil-this-register (read-char))) macro) (cond ((or (and (eq register 64) (eq evil-last-register 58)) (eq register 58)) (setq macro (function (lambda nil (evil-ex-repeat nil))) evil-last-register 58)) ((eq register 64) (if evil-last-register nil (user-error "No previously executed keyboard macro.")) (setq macro (evil-get-register evil-last-register t))) ((setq macro (evil-get-register register t) evil-last-register register))) (if macro nil (user-error "No macro recorded in %c register" register)) (evil-change-state (quote normal)) (evil-with-single-undo (let ((lines (count-lines beg end))) (message "Applied macro in %c register %d times" register lines) (apply-macro-to-region-lines beg end macro) (message "Applied macro in %c register %d times...DONE" register lines)))))
  eval-buffer(#<buffer  *load*-804229> nil "/home/u/.emacs.d/modules/editor/evil/autoload/evil.el" nil t)  ; Reading at buffer position 5130
  load-with-code-conversion("/home/u/.emacs.d/modules/editor/evil/autoload/evil.el" "/home/u/.emacs.d/modules/editor/evil/autoload/evil.el" nil t)
  (set-evil-initial-state! (quote deft-mode) (quote insert))
  (progn (use-package-statistics-gather :config (quote deft) nil) (add-to-list (quote deft-extensions) "tex") (add-hook (quote deft-mode-hook) (function doom-mark-buffer-as-real-h)) (set-evil-initial-state! (quote deft-mode) (quote insert)) (general-define-key :major-modes t :prefix doom-localleader-alt-key :keymaps (quote (deft-mode-map)) "RET" (function deft-new-file-named) "a" (function deft-archive-file) "c" (function deft-filter-clear) "d" (function deft-delete-file) "f" (function deft-find-file) "g" (function deft-refresh) "l" (function deft-filter) "n" (function deft-new-file) "r" (function deft-rename-file) "s" (function deft-toggle-sort-method) "t" (function deft-toggle-incremental-search)) t (use-package-statistics-gather :config (quote deft) t))
  (closure (t) nil (progn (use-package-statistics-gather :config (quote deft) nil) (add-to-list (quote deft-extensions) "tex") (add-hook (quote deft-mode-hook) (function doom-mark-buffer-as-real-h)) (set-evil-initial-state! (quote deft-mode) (quote insert)) (general-define-key :major-modes t :prefix doom-localleader-alt-key :keymaps (quote (deft-mode-map)) "RET" (function deft-new-file-named) "a" (function deft-archive-file) "c" (function deft-filter-clear) "d" (function deft-delete-file) "f" (function deft-find-file) "g" (function deft-refresh) "l" (function deft-filter) "n" (function deft-new-file) "r" (function deft-rename-file) "s" (function deft-toggle-sort-method) "t" (function deft-toggle-incremental-search)) t (use-package-statistics-gather :config (quote deft) t)))()
  eval-after-load(deft (closure (t) nil (progn (use-package-statistics-gather :config (quote deft) nil) (add-to-list (quote deft-extensions) "tex") (add-hook (quote deft-mode-hook) (function doom-mark-buffer-as-real-h)) (set-evil-initial-state! (quote deft-mode) (quote insert)) (general-define-key :major-modes t :prefix doom-localleader-alt-key :keymaps (quote (deft-mode-map)) "RET" (function deft-new-file-named) "a" (function deft-archive-file) "c" (function deft-filter-clear) "d" (function deft-delete-file) "f" (function deft-find-file) "g" (function deft-refresh) "l" (function deft-filter) "n" (function deft-new-file) "r" (function deft-rename-file) "s" (function deft-toggle-sort-method) "t" (function deft-toggle-incremental-search)) t (use-package-statistics-gather :config (quote deft) t))))
  eval-buffer(#<buffer  *load*-254465> nil "/home/u/.emacs.d/modules/ui/deft/config.el" nil t)  ; Reading at buffer position 1501
  load-with-code-conversion("/home/u/.emacs.d/modules/ui/deft/config.el" "/home/u/.emacs.d/modules/ui/deft/config.el" t t)
  load("/home/u/.emacs.d/modules/ui/deft/config.el" t t)
  doom-cli-byte-compile(nil nil)
</pre></details>

**Additional details:**
- dotfiles: https://github.com/utrack/dotfiles/tree/master/doomemacs/.doom.d

**System information:**
<details><pre>
((emacs
  (version . "26.3")
  (features . "XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2")
  (build . "Aug 29, 2019")
  (buildopts "--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-modules 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now")
  (windowsys . batch)
  (daemonp))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD c049ada61 2020-03-11 00:57:44 -0400")
  (dir . "~/.dotfiles/doomemacs/.doom.d/"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/bin/zsh")
  (uname . "Linux 5.4.8-arch1-1 #1 SMP PREEMPT Sat, 04 Jan 2020 23:46:18 +0000 x86_64")
  (path "~/.bin" "~/go/bin" "/usr/local/bin" "/usr/local/sbin" "/usr/local/bin" "/usr/bin" "/bin" "/usr/local/sbin" "/usr/lib/jvm/default/bin" "/usr/bin/site_perl" "/usr/bin/vendor_perl" "/usr/bin/core_perl" "/usr/lib/emacs/26.3/x86_64-pc-linux-gnu"))
 (config
  (envfile . envvar-file)
  (elc-files . 4)
  (modules :completion company (ivy +childframe +fuzzy) :ui deft doom fill-column hl-todo modeline nav-flash ophints (popup +all +defaults) pretty-code treemacs vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold (format +onsave) multiple-cursors rotate-text snippets word-wrap :emacs dired electric vc :term term :checkers syntax :tools debugger editorconfig eval (lookup +docsets) lsp magit make pass pdf :lang data emacs-lisp ess (go +lsp) latex markdown (org +dragndrop +present) plantuml rest sh :app calendar :config (default +bindings +smartparens))
  (packages (ivy-rich) (counsel-tramp) (dap-mode) (zoom) (evil-snipe) (evil-visual-mark-mode) (outline-magic) (outshine) (org-journal) (poporg) (edit-indirect) (writeroom-mode) (org-roam :recipe (:host github :repo "jethrokuan/org-roam" :branch "develop")))
  (unpin "n/a")
  (elpa "n/a")))
</pre></details>

**Comment by hlissner** [comment]
Is this still a problem? I cannot reproduce it, and suspect it was indirectly fixed in the past half year.
