### ISSUE TITLE
Disabling doom modeline completely disables modeline

### ISSUE THREAD

**Issue by allforabit** [hlissner/doom-emacs#271]
I'm having an issue at the moment where it is slow to enter text and I've narrowed it down to the doom modeline. When I disable it, emacs is responsive again. I'm just wondering if there's a way to revert back to the default emacs modeline for now. Currently when I disable it no modeline shows up at all whereas I'd like it to just revert back to the default emacs modeline. When I have time, I will investigate what is causing the slowness with the doom modeline. I'm on Windows 10 so it may be a complication caused by this. In addition I'm not byte compiling as this is causing a bug on startup, again probably an issue with using on Windows (and I know this may improve performance).

**Comment by hlissner** [comment]
That is curious. Although, I am aware the modeline isn't as fast as it could be.

Assuming you've disabled ui/doom-modeline, the only thing that could cause a blank modeline is [this line in my private module](https://github.com/hlissner/doom-emacs/blob/develop/modules/private/hlissner/init.el#L12), but this file shouldn't even be executed unless your username is `hlissner`.

Try commenting that line and let me know if it helps.

**Comment by allforabit** [comment]
Hi @hlissner thanks yes did this the trick. I just used your config as the basis for mine so this line was still in there. I will get back to you if I can figure out what particular parts of the doom modeline are making it run slowly on my machine.
