### ISSUE TITLE
I separate popup module code for my personal use

### ISSUE THREAD

**Issue by loyalpartner** [hlissner/doom-emacs#2717]
@hlissner 
I like everything doom, but it's large enough and not quickly start in the windows os, so
I extracted the package out, easy to use in windows inside, But this is only
used as my personal, I'm not very understanding the opensource agreement , I
do not know whether the infringing use your code, trouble you to see What do I
need to declare it.

https://github.com/loyalpartner/doom-popup

**Comment by hlissner** [comment]
This is fine. I don't mind you extracting functionality from Doom. The MIT license is very permissive. In fact, this was already done by https://github.com/aaronjensen/emacs-popup-mode/, maybe that can help.

Although, I'd be more interested in knowing why Doom doesn't start quickly on Windows and how to fix that. If you're willing to share, please let me know.
