### ISSUE TITLE
Map same binding for different modes

### ISSUE THREAD

**Issue by ericdallo** [hlissner/doom-emacs#2718]
I would like to have different bindings for different modes.

Example: I would like that on java, I can run test with `dap`, but on `dart-mode` run flutter tests...
dap binding: https://github.com/ericdallo/dotfiles/blob/master/emacs/.doom.d/+bindings.el#L118
dart test binding: https://github.com/ericdallo/dotfiles/blob/master/emacs/.doom.d/+bindings.el#L137

What happens is that one override the other, so when I'm on java, it keeps showing to run flutter tests on the binding :/

Am I doing something wrong?

**Comment by hlissner** [comment]
Yes. `:leader` keys are global, not buffer/mode local. What you want is `:localleader`:

```lisp
(map! :localleader
      (:map java-mode-map
       "t" #'dap-java-run-test-method)
      (:map dart-mode-map
       "t" #'flutter-test-current-file))
```

This puts the key on `SPC m t`, because `SPC m` is the local leader.

**Comment by ericdallo** [comment]
Thanks! @hlissner do you know if can bind in separated `map!` functions?
Like this:
```elisp
(map! :after dap-java
      :localleader
      :prefix ("m" . "tools")

      :desc "Run method test"
      "t" #'dap-java-run-test-method)

(map! :after dart-mode
      :localleader
      :prefix ("m" . "tools")

      :desc "Run current file test"
      "t" #'flutter-test-current-file)
```

It gives me the error:
```
Error in private config: +bindings.el, (error Key sequence SPC m m t starts with non-prefix key SPC)
```

**Comment by ericdallo** [comment]
Hum, I fixed adding `:map`:
```elisp
(map! :after dap-java
      :map dap-mode-map
      :localleader
      :prefix ("m" . "tools")

      :desc "Run method test"
      "t" #'dap-java-run-test-method)

(map! :after dart-mode
      :map dart-mode-map
      :localleader
      :prefix ("m" . "tools")

      :desc "Run current file test"
      "t" #'flutter-test-current-file)
```

But it looks like it's adding a `m` prefix and using the dap-mode-map yet :/
![image](https://user-images.githubusercontent.com/7820865/76642903-d4222880-6532-11ea-839e-862f6342063c.png)

**Comment by hlissner** [comment]
Not sure i understand. You have `:prefix "m"`, so it's going to bind under `<localleader> m t`, and `<localleader>` is `SPC m`, therefore `SPC m m t`.

If this is not what you want, remove the `:prefix`.

**Comment by ericdallo** [comment]
Yeah, I didn't know that localleader is `SPC m`, sorry.

Ok, but I'm on a `dart-mode` and it's showing the `dap` bindings yet :/ It should show the dart-mode-map bindings, not the dap-mode-map.

**Comment by hlissner** [comment]
That implies you have dap-mode enabled in both buffers, in which case they are behaving correctly. Minor modes keymaps (dap-mode) have higher precedence than major mode keymaps. Perhaps instead of binding the key to `dap-mode-map`, why not `java-mode-map`?

**Comment by ericdallo** [comment]
yeah! I realized that now :man_facepalming: 

It works now, thank you very much!

**Comment by hlissner** [comment]
Glad I could help!
