### ISSUE TITLE
How do I connect to the Discord server?

### ISSUE THREAD

**Issue by powellc** [hlissner/doom-emacs#2720]
I used to be in the main discord server, but right now (and I've been trying this for the past month or so and wondered if it would resolve over time), I can't join the primary server. I'm stuck with only #readme in the channel list. Sorry if this is not the best place for this question, but a lot of great help exists only on the discord server and I'm feeling the pain of being excluded.

For what it's worth this is the link I click on: https://discord.gg/qvGgnVx

**Comment by hlissner** [comment]
> I'm stuck with only #readme in the channel list.

Click on the #readme channel, scroll to the top (if necessary) and read the first post. It will tell you how to get into the server.

**Comment by powellc** [comment]
No problem at all! Sorry I had to open a ticket to get back in :laughing:  ... you kids and your discords :)
