### ISSUE TITLE
[HOWTO] navigate to word cross line?

### ISSUE THREAD

**Issue by ZhiruiLi** [hlissner/doom-emacs#2724]
evil-forward-word-begin should jump to begin of any forward words in buffer, but in doom emacs, I found that it can only jump to forward words in current line (when hit `g s w`). Is there any settings for me to change this behiver?

![image](https://user-images.githubusercontent.com/6213647/76702630-28313680-6706-11ea-8ce4-f84239b7cea6.png)

**Comment by docbiz** [comment]
Would `avy-goto-word0` be [a fitting alternative](https://github.com/abo-abo/avy#avy-goto-word-0)?

**Comment by ZhiruiLi** [comment]
> Would `avy-goto-word0` be [a fitting alternative](https://github.com/abo-abo/avy#avy-goto-word-0)?

The tagging style of avy is different from easy-motion. In easy-motion, the matching words near the cursor will have shorter tags, such as `h`, `j`, `k`, which makes it more easy to move to lines near cursor, which is a high frequency operation. But in avy, the upper matching words will have shorter tags, that means it almost always need to hit 3 chars to go to matching words in last 1/3 buffer, no matter where the cursor is now.
But still, `avy-goto-word0` can be an alternative, however, when I tried to config it to my config.el file, I got a strength problem, as I showed in this issue #2725 .

**Comment by hlissner** [comment]
> evil-forward-word-begin should jump to begin of any forward words in buffer

This appears to be the default behavior for `gsw` et co. I would recommend reporting this to evil-easymotion. For some reason, their default scope is the current line: https://github.com/PythonNut/evil-easymotion/blob/master/evil-easymotion.el#L316-L353

Otherwise, this would work around it (albeit clumsily):

```elisp
(after! evil-easymotion 
  (put 'visible-buffer 'bounds-of-thing-at-point (lambda () (cons (window-start) (window-end))))
  (evilem-make-motion evilem-motion-forward-word-begin #'evil-forward-word-begin :scope 'visible-buffer)
  (evilem-make-motion evilem-motion-forward-WORD-begin #'evil-forward-WORD-begin :scope 'visible-buffer)
  (evilem-make-motion evilem-motion-forward-word-end #'evil-forward-word-end :scope 'visible-buffer)
  (evilem-make-motion evilem-motion-forward-WORD-end #'evil-forward-WORD-end :scope 'visible-buffer)
  (evilem-make-motion evilem-motion-backward-word-begin #'evil-backward-word-begin :scope 'visible-buffer)
  (evilem-make-motion evilem-motion-backward-WORD-begin #'evil-backward-WORD-begin :scope 'visible-buffer)
  (evilem-make-motion evilem-motion-backward-word-end #'evil-backward-word-end :scope 'visible-buffer)
  (evilem-make-motion evilem-motion-backward-WORD-end #'evil-backward-WORD-end :scope 'visible-buffer))
```

**Comment by ZhiruiLi** [comment]
> > evil-forward-word-begin should jump to begin of any forward words in buffer
> 
> This appears to be the default behavior for `gsw` et co. I would recommend reporting this to evil-easymotion. For some reason, their default scope is the current line: https://github.com/PythonNut/evil-easymotion/blob/master/evil-easymotion.el#L316-L353
> 
> Otherwise, this would work around it (albeit clumsily):
> 
> ```emacs-lisp
> (after! evil-easymotion 
>   (put 'visible-buffer 'bounds-of-thing-at-point (lambda () (cons (window-start) (window-end))))
>   (evilem-make-motion evilem-motion-forward-word-begin #'evil-forward-word-begin :scope 'visible-buffer)
>   (evilem-make-motion evilem-motion-forward-WORD-begin #'evil-forward-WORD-begin :scope 'visible-buffer)
>   (evilem-make-motion evilem-motion-forward-word-end #'evil-forward-word-end :scope 'visible-buffer)
>   (evilem-make-motion evilem-motion-forward-WORD-end #'evil-forward-WORD-end :scope 'visible-buffer)
>   (evilem-make-motion evilem-motion-backward-word-begin #'evil-backward-word-begin :scope 'visible-buffer)
>   (evilem-make-motion evilem-motion-backward-WORD-begin #'evil-backward-WORD-begin :scope 'visible-buffer)
>   (evilem-make-motion evilem-motion-backward-word-end #'evil-backward-word-end :scope 'visible-buffer)
>   (evilem-make-motion evilem-motion-backward-WORD-end #'evil-backward-WORD-end :scope 'visible-buffer))
> ```

Thank you, it works!
