### ISSUE TITLE
[HOWTO] Add keybinding but not affect the existing keybindings

### ISSUE THREAD

**Issue by ZhiruiLi** [hlissner/doom-emacs#2725]
When I try to add keybindings to existing ones, for example, add another keybinding with prefix `g s`, it seems that it will fully override all the keybindings with prefix `g s`.

```elisp
;; in my config.el
(map!
 (:prefix "g"
   (:prefix "s"
     :nv "l" #'avy-goto-word-0)))
```

![image](https://user-images.githubusercontent.com/6213647/76702764-68dd7f80-6707-11ea-9fb9-c346906acc0c.png)

Can I add keybindings without override the existing ones?

**Comment by OwenPriceSkelly** [comment]
Try just :prefix instead of :prefix-map, which I think is only supposed to be used by the default/ evil modules

**Comment by ZhiruiLi** [comment]
> Try just :prefix instead of :prefix-map, which I think is only supposed to be used by the default/ evil modules

I change `:prefix-map` to `:prefix`, but it seems still not work. The strange thing is that if I not have this `map!` call in my config file before launching emacs, then add it to my config file, then `C-x C-e` to run it, then it will works fine, both origin key binding and my customize key binding will works. But if I put this in my config file before launching emacs, the problem will occur.

**Comment by docbiz** [comment]
I can reproduce this; the suggestion in [issue 1062](https://github.com/hlissner/doom-emacs/issues/1062) just overwrites the existing `g s` bindings.

**Comment by hlissner** [comment]
To add keys to evil-easymotion, you need to add it to `evilem-keymap`.

```elisp
(map! :after evil-easymotion
      :prefix "gs"
      "l" #'avy-goto-word-0)
```

**Comment by ZhiruiLi** [comment]
> To add keys to evil-easymotion, you need to add it to `evilem-map` (with no prefix):
> 
> ```emacs-lisp
> (map! :after evil-easymotion
>       :map evilem-map
>       "l" #'avy-goto-word-0)
> ```

Thank you, it works!
