### ISSUE TITLE
Get java autocompletion

### ISSUE THREAD

**Issue by Sammyalhashe** [hlissner/doom-emacs#2728]
> Please visit our Discord server to ask how-to and workflow questions:
> https://discord.gg/qvGgnVx -- post on Doom's issue tracker as a last resort.

**What are you trying to achieve?**
Get java-lsp up and running. I just want to say that I am new to doom, and trying to migrate over from spacemacs.

**What have you tried?**
in the init.el file I have tried:
(java +lsp)
(java +lsp jdtls)
(java +eclim)

**Additional information**
- Do you have screenshots/casts of this workflow in another editor or Emacs
  distro? (If possible, include names of specific commands or functions from
  other editors/emacs distros)
- Do you have additional material or links to resources that could help clarify
  what you are trying to do?
I had previously gotten an error at the bottom that says it's unable to find the language server, but it stopped appearing. The autocompletion still doesn't work though.

**System information**
<details><pre>
((emacs
  (version . "26.3")
  (features . "JPEG RSVG IMAGEMAGICK GLIB NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2")
  (build . "Aug 30, 2019")
  (buildopts "--disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus/26.3/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus/26.3 --with-xml2 --without-dbus --with-gnutls --with-imagemagick --with-modules --with-rsvg --with-ns --disable-ns-self-contained")
  (windowsys . batch)
  (daemonp))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD 4b20c7206 2020-03-13 17:34:44 -0400")
  (dir . "~/.doom.d/"))
 (system
  (type . darwin)
  (config . "x86_64-apple-darwin18.5.0")
  (shell . "/bin/zsh")
  (uname . "Darwin 18.7.0 Darwin Kernel Version 18.7.0: Thu Jan 23 06:52:12 PST 2020; root:xnu-4903.278.25~1/RELEASE_X86_64 x86_64")
  (path "~/.sdkman/candidates/scala/current/bin" "~/google-cloud-sdk/bin" "/usr/local/bin" "/usr/local/opt/llvm/bin" "~/.cargo/bin" "/usr/local/bin" "/usr/bin" "/bin" "/usr/sbin" "/sbin" "/Library/TeX/texbin" "/opt/X11/bin" "/Applications/kitty.app/Contents/MacOS" "~/.pub-cache/bin" "~/go/bin" "~/.ant/apache-ant-1.9.14//bin" "~/bin" "/usr/local/Cellar/emacs-plus/26.3/libexec/emacs/26.3/x86_64-apple-darwin18.5.0"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold multiple-cursors rotate-text snippets :emacs dired electric ibuffer vc :term eshell :checkers syntax :tools (eval +overlay) (lookup +docsets) lsp macos magit pdf :lang (cc +lsp clangd) data emacs-lisp (java +lsp +eclim) latex markdown (org +dragndrop +present) (python +lsp) sh :config (default +bindings +smartparens))
  (packages "n/a")
  (unpin "n/a")
  (elpa "n/a")))
</pre></details>

**Comment by fgahr** [comment]
I'm currently struggling with the same thing. Unfortunately, java seems to be rather underdeveloped in doom right now.
However, to get started, consider the following lines from `.emacs.d/modules/lang/java/+lsp.el`:
`(setq lsp-java-server-install-dir (concat doom-etc-dir "eclipse.jdt.ls/server/")
      lsp-java-workspace-dir (concat doom-etc-dir "java-workspace"))`
where `doom-etc-dir` is `.emacs.d/.local/etc`. Depending on how you installed jdtls, you can probably just copy the jdtls server directory there (not sure where that would be on a Mac).
Personally, I copied the folder from my old spacemacs config, where it resided in a similar folder.
The `java-workspace` folder probably gets created automatically but I did so manually.

You might still have to enable lsp-mode in a java buffer to get things going but basic completion is possible that way (albeit a bit flaky). Not sure I can help with an overhaul of the java module but I might try a bit. Still lots to figure out here and I haven't touched Java in a while.

**Comment by Sammyalhashe** [comment]
Hey thanks man, you've given me a good idea of how to get this working. I also looked at the eclipse.jdt.ls that spacemacs downloaded and I had pretty much the same files you did. I tried copying a couple of the folders that seemed to match "/server" to be the server directory, specifically "boot-server" and "java-test/server", but none seemed to work. Did you do something like this to get it working?

**Comment by fgahr** [comment]
I tried flailing my arms a bit and somehow got something working.
Now I understand it a bit better: in a java buffer, try `M-x lsp` (to get things going). That seems to be missing from the current java setup and I'll try and figure out how to make this permanent or maybe someone else knows.
That *should* do the trick. Otherwise make sure lsp-mode is enabled and such. Good luck.

**Comment by hlissner** [comment]
> Now I understand it a bit better: in a java buffer, try M-x lsp (to get things going).

This should [already be done for you](https://github.com/hlissner/doom-emacs/blob/develop/modules/lang/java/%2Blsp.el#L7). That it isn't activating for you suggests an error may be occurring while initializing `java-mode`. Open your \*Messages\* buffer (with `SPC h e`) and see if any errors/warnings are logged after opening a java buffer.

**Comment by fgahr** [comment]
Interestingly, while (for  me) it was stable behaviour at the time, I can't replicate it anymore and everything appears to be working now with no changes made.
Only after testing did I update doom-emacs so it had nothing to do with that either (still works, of course).
This leads me to believe I made a mistake and forgot to call `doom/reload` or something like that. I might have switched openjdk versions, not sure though.
Since the java module appeared to be somewhat rudimentary and manually starting worked, it seemed like the obvious suspect. Sorry about that.
Thank you for creating doom-emacs.

**Comment by Sammyalhashe** [comment]
Personally, it tells me that LSP :: No LSP server for java-mode(check *lsp-log*). Not sure how to check this log I admit.

**Comment by kylesferrazza** [comment]
@Sammyalhashe 
The lsp log is in a buffer called `*lsp-log*`.
Press `SPC b B` (for `ivy-switch-buffer`), type `lsp-log` and hit enter to view it.

**Comment by mvarela** [comment]
The lack of auto-completion may be related to these error messages:
```
LSP :: Guessed project root is ~/tmp/java-test/java-project/src/main/java/com/mkyong
LSP :: Connected to [jdtls:94646 status:starting].
LSP :: jdtls:94646 initialized successfully
Company: An error occurred in auto-begin
Company: backend company-lsp error "Lisp nesting exceeds ‘max-lisp-eval-depth’" with args (prefix)
Company: An error occurred in auto-begin
Company: backend company-lsp error "Lisp nesting exceeds ‘max-lisp-eval-depth’" with args (prefix)
```

I get lsp-ui working (overlays, suggestions, all that), but no autocomplete.
