### ISSUE TITLE
current pinned version of lsp-ui breaks 

### ISSUE THREAD

**Issue by lccambiaghi** [hlissner/doom-emacs#2739]
**What did you expect to happen?**
...
lsp-ui mode activates

**What actually happened?**
...
lsp-ui does not activate

**Additional details:**
Description of the problem here:
https://github.com/emacs-lsp/lsp-ui/issues/421

<details><pre>
Symbol’s value as variable is void: lsp-ui-doc-winum-ignore
</pre></details>

**Steps to reproduce:**
Activate lsp-ui-mode with the current pinned versions of lsp-ui and winnum.

**Comment by hlissner** [comment]
As of 5c3d54f19 I've bumped both lsp and lsp-ui, so I'll consider this resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
