### ISSUE TITLE
Mu4e not found

### ISSUE THREAD

**Issue by l4nn1312** [hlissner/doom-emacs#2740]
**What did you expect to happen?**
I want to run mu4e since I have the module enabled.

**What actually happened?**
`no such file or directory, mu4e`

**Additional details:**
[config](https://github.com/l4nn1312/.doom.d)

**Steps to reproduce:**
1. Enable mu4e in `~/.doom.d/init.el`
2. Run `bin/doom sync`
3. Launch emacs and `M-x =mu4e`

**System information:**
<details><pre>
emacs   version    27.0.50
        features   NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS JSON PDUMPER LCMS2 GMP
        build      Nov 26, 2019
        buildopts  (--prefix=/opt/local --without-dbus --without-gconf --without-libotf --without-m17n-flt --without-gpm --with-gnutls --with-xml2 --with-modules --infodir /opt/local/share/info/emacs --with-json --without-harfbuzz --with-ns --with-lcms2 'CFLAGS=-pipe -Os -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -arch x86_64' 'CPPFLAGS=-I/opt/local/include -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk' 'LDFLAGS=-L/opt/local/lib -Wl,-headerpad_max_install_names -Wl,-no_pie -Wl,-syslibroot,/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -arch x86_64')
        windowsys  ns
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop, origin/develop, origin/HEAD 4b20c7206 2020-03-13 17:34:44 -0400
        dir        ~/.doom.d/
system  type       darwin
        config     x86_64-apple-darwin19.0.0
        shell      /opt/local/bin/zsh
        uname      Darwin 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64
        path       (~/.nix-profile/bin ~/.cargo/bin ~/.sdkman/candidates/sbt/current/bin ~/.config/yarn/bin/bin /Applications/MacPorts/Emacs.app/Contents/MacOS ~/.config/yarn/bin/bin/bin/bin ~/.config/yarn/bin/bin/bin /opt/pkg/bin /opt/local/bin /opt/local/sbin ~/.zplug/bin /opt/local/bin /opt/local/sbin ~/.cargo/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /Library/TeX/texbin /usr/local/MacGPG2/bin /opt/pkg/sbin /opt/pkg/bin /usr/local/texlive/2017/bin/x86_64-linux/ ~/.local/bin ~/go/bin /usr/local/plan9/bin /Applications/MacPorts/Emacs.app/Contents/MacOS/libexec/)
config  envfile    envvar-file
        elc-files  36
        modules    (:completion (company +icons) (ivy +icons) :ui doom doom-dashboard doom-quit hl-todo hydra indent-guides modeline nav-flash ophints (popup +defaults) pretty-code tabs treemacs unicode vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold lispy multiple-cursors parinfer snippets word-wrap :emacs (dired +icons) electric vc :checkers syntax spell grammar :tools debugger direnv docker editorconfig (eval +overlay) lookup (lsp +peek) macos magit make pdf rgb :lang cc clojure data emacs-lisp (go +lsp) (haskell +dante) (javascript +lsp) (latex +latexmk +cdlatex) markdown nix (org +dragndrop +brain +hugo +pandoc +pomodoro +present) rust sh web :email mu4e notmuch :app calendar irc :config (default +bindings +smartparens))
        packages   ((writefreely) (mu4e-alert))
        unpin      (n/a)
        elpa       (n/a)
</pre></details>

**Comment by RBckmnn** [comment]
See https://github.com/hlissner/doom-emacs/blob/develop/modules/email/mu4e/README.org

You need to install mu manually. Mu contains mu4e.

**Comment by l4nn1312** [comment]
I installed mu from macports but I'll see if installing it from homebrew fixes it

**Comment by l4nn1312** [comment]
Worked! Thanks!
