### ISSUE TITLE
Use the till modifier :t like in Vim or Spacemacs

### ISSUE THREAD

**Issue by Rareform** [hlissner/doom-emacs#2744]
**Describe the feature**
In vim and Spacemacs it is possible to copy arbitrary line (s) from one location to another with the :t modifier. For example in spacemacs with relative line numbering the command :-2t+1 (In vim you need to insert :, to make it relative I think) copies the line 2 lines above 1 line below. 
It seems , that this is not yet implemented in doom at the moment. It would be great to have the spacemacs behavior also implemented for doom emacs.

**System information**
<details><pre>
emacs   version    26.3
        features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD LCMS2
        build      Sep 16, 2019
        buildopts  (--build=x86_64-linux-gnu --prefix=/usr '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' --sysconfdir=/etc --localstatedir=/var --disable-silent-rules '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' --disable-maintainer-mode --disable-dependency-tracking --prefix=/usr --sharedstatedir=/var/lib --program-suffix=26 --with-modules --with-file-notification=inotify --with-mailutils --with-x=yes --with-x-toolkit=gtk3 --with-xwidgets --with-lcms2 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/emacs26-TP6iDo/emacs26-26.3~1.git96dd019=. -fstack-protector-strong -Wformat -Werror=format-security -no-pie' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro -no-pie')
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop 4b20c7206 2020-03-13 17:34:44 -0400
        dir        /mnt/d/Dropbox/.doom.d/
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/bash
        uname      Linux 4.4.0-18362-Microsoft #1-Microsoft Mon Mar 18 12:02:00 PST 2019 x86_64
        path       (/usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /usr/games /usr/local/games /mnt/c/ProgramData/Oracle/Java/javapath /mnt/c/Program Files (x86)/Intel/iCLS Client/ /mnt/c/Program Files/Intel/iCLS Client/ /mnt/c/Windows/system32 /mnt/c/Windows /mnt/c/Windows/System32/Wbem /mnt/c/Windows/System32/WindowsPowerShell/v1.0/ /mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL /mnt/c/Program Files/Intel/Intel(R) Management Engine Components/DAL /mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/IPT /mnt/c/Program Files/Intel/Intel(R) Management Engine Components/IPT /mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common /mnt/c/Program Files/Git/cmd /mnt/d/Dropbox/programmes/emax26.2/bin /mnt/c/WINDOWS/system32 /mnt/c/WINDOWS /mnt/c/WINDOWS/System32/Wbem /mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/ /mnt/c/WINDOWS/System32/OpenSSH/ /mnt/c/Program Files/texlive/2018/bin/win32 /mnt/c/ProgramData/chocolatey/bin /mnt/c/ProgramData/Anaconda3/Scripts/ /mnt/c/Program Files/Intel/WiFi/bin/ /mnt/c/Program Files/Common Files/Intel/WirelessCommon/ /mnt/c/Users/CLEVO/emax64ver26.3.7/bin /%CYGWIN% /mnt/c/cygwin64 /mnt/c/cygwin64/bin /mnt/c/Program Files/Git/usr/bin /mnt/c/Program Files (x86)/QuickTime/QTSystem/ /mnt/c/Program Files/LLVM/bin /mnt/c/ProgramData/Oracle/Java/javapath /mnt/c/Program Files (x86)/Intel/iCLS Client/ /mnt/c/Program Files/Intel/iCLS Client/ /mnt/c/Windows/system32 /mnt/c/Windows /mnt/d/Dropbox/programmes/emax191229/bin /mnt/c/Windows/System32/Wbem /mnt/c/Windows/System32/WindowsPowerShell/v1.0/ /mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL /mnt/c/Program Files/Intel/Intel(R) Management Engine Components/DAL /mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/IPT /mnt/c/Program Files/Intel/Intel(R) Management Engine Components/IPT /mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common /mnt/c/Program Files/Git/cmd /mnt/c/WINDOWS/system32 /mnt/c/WINDOWS /mnt/c/WINDOWS/System32/Wbem /mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/ /mnt/c/WINDOWS/System32/OpenSSH/ /mnt/c/Program Files/texlive/2018/bin/win32 /mnt/c/ProgramData/Anaconda3 /mnt/c/ProgramData/chocolatey/bin /mnt/c/ProgramData/Anaconda3/Scripts/ /mnt/c/Program Files/Intel/WiFi/bin/ /mnt/c/Program Files/Common Files/Intel/WirelessCommon/ /mnt/c/Users/CLEVO/AppData/Local/Microsoft/WindowsApps /snap/bin /usr/lib/x86_64-linux-gnu/emacs/26.3/x86_64-linux-gnu/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard hl-todo hydra indent-guides modeline nav-flash ophints (popup +defaults) tabs treemacs vc-gutter vi-tilde-fringe window-select workspaces zen :editor (evil +everywhere) file-templates fold multiple-cursors rotate-text snippets :emacs dired electric ibuffer vc :term shell :checkers syntax spell :tools (eval +overlay) lookup magit pdf :lang data emacs-lisp latex markdown (org +dragndrop +present) python sh :config (default +bindings +smartparens))
        packages   ((winum) (org-super-agenda))
        unpin      (n/a)
        elpa       (n/a)
</pre></details>

**Comment by wangggong** [comment]
It seems that just use `:-2co+1` instead of `:-2t+1` works well :D

**Comment by Rareform** [comment]
Didn't know this command, ok, than duplicating the bind for `:t` shouldn't be hard. Still, from my impression it makes sense to include `:t` command per default, since it doesn`t counteract to anything and would be consistent with regular vim.

**Comment by bandresen** [comment]
putting `(evil-ex-define-cmd "t" "copy")` into your *doom.d/config.el* file works fine. That is also the default evil definition in *evil-maps.el*

**Comment by hlissner** [comment]
> Curious why it's broken in doom.

My bad. It was because of a conflicting ex command that Doom defined. As of 169eb2d that conflict should be resolved and `:t` should be functional again. Thanks for bringing it to my attention, and for looking into it!
