### ISSUE TITLE
How do I use package! with after! in my config files?

### ISSUE THREAD

**Issue by evanleck** [hlissner/doom-emacs#2745]
**What are you trying to achieve?**

I'd like to add the package `simpleclip` and enable its global mode.

**What have you tried?**

In ~/.doom.d/packages.el: `(package! simpleclip)` and in ~/.doom.d/config.el: `(after! simpleclip (simpleclip-mode 1))`.

**Additional information**

I suspect I'm just using it wrong, but from what I gleaned from [the docs](https://github.com/hlissner/doom-emacs/blob/develop/docs/api.org) I'm doing it right. Should this be `use-package!` instead? When should `package!` be used vs. `use-package!`?

**System information**
<details><pre>
((emacs
  (version . "26.3")
  (features . "JPEG RSVG IMAGEMAGICK GLIB NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2")
  (build . "Dec 23, 2019")
  (buildopts "--disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus/26.3/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus/26.3 --with-xml2 --without-dbus --with-gnutls --with-imagemagick --with-modules --with-rsvg --with-ns --disable-ns-self-contained")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD 4b20c7206 2020-03-13 17:34:44 -0400")
  (dir . "~/.doom.d/"))
 (system
  (type . darwin)
  (config . "x86_64-apple-darwin19.2.0")
  (shell . "/bin/zsh")
  (uname . "Darwin 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64")
  (path "~/.asdf/shims" "/usr/local/opt/asdf/bin" "/usr/local/bin" "/usr/bin" "/bin" "/usr/sbin" "/sbin" "/usr/local/opt/fzf/bin" "/usr/local/Cellar/emacs-plus/26.3/libexec/emacs/26.3/x86_64-apple-darwin19.2.0"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline ophints (popup +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold snippets :emacs dired electric vc :checkers syntax :tools editorconfig (eval +overlay) lookup magit :lang data emacs-lisp javascript markdown (org +dragndrop +present) ruby sh web :config (default +bindings +smartparens))
  (packages (dockerfile-mode) (evil-matchit) (simpleclip))
  (unpin "n/a")
  (elpa "n/a")))
</pre></details>

**Comment by yoavm448** [comment]
You should just add a plain `(simpleclip-mode 1)` in your config.el to activate it; That would load the package and activate the mode.
`after!` defers the execution until after the package has loaded, which is useful if you want to modify its behavior etc. But without anything requiring the package, it would never get loaded, which is why your `after!` block was never called. 
You're using `package!` right. `use-package!` is for configuring a package, e.g setting a file type that would use the package.

**Comment by evanleck** [comment]
Alright, thanks!
