### ISSUE TITLE
+format/region-or-buffer error

### ISSUE THREAD

**Issue by agraul** [hlissner/doom-emacs#2748]
**What did you expect to happen?**
Selecting a line and then running `SPC c f` will format that line with `black` (in python-mode).

**What actually happened?**
An error occurred.

**Additional details:**
Short recording: https://gfycat.com/heavyrashhorseshoebat (taken in a `c-c c-p` sandbox).

After testing with other modes today (Ruby, Orgmode), I can report that this error is not restricted to Python.

<details><pre>
Debugger entered--Lisp error: (wrong-number-of-arguments (0 . 0) 1)
  +format/buffer(nil)
  (let ((+format-region-p t)) (+format/buffer arg))
  (save-restriction (narrow-to-region beg end) (let ((+format-region-p t)) (+format/buffer arg)))
  +format/region(55 65)
  funcall-interactively(+format/region 55 65)
  call-interactively(+format/region)
  +format/region-or-buffer()
  funcall-interactively(+format/region-or-buffer)
  call-interactively(+format/region-or-buffer nil nil)
  command-execute(+format/region-or-buffer)
</pre></details>

**Steps to reproduce:**
1. Enable `format` module
2. install `black`
3. open a python file
4. select a region (e.g. single line)
5. run `+format/region-or-buffer` (`SPC c f`)
6. error

**System information:**
<details><pre>
((emacs
  (version . "26.3")
  (features . "XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD")
  (build . "Mar 20, 2020")
  (buildopts "--disable-build-details --without-pop --with-mailutils --without-hesiod --with-gameuser=:games --with-kerberos --with-kerberos5 --with-file-notification=inotify --with-modules --enable-autodepend --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --datadir=/usr/share --localstatedir=/var --sharedstatedir=/var/lib --libexecdir=/usr/lib --enable-locallisppath=/usr/share/emacs/26.3/site-lisp:/usr/share/emacs/site-lisp --with-x --with-xim --with-sound --with-xpm --with-jpeg --with-tiff --with-gif --with-png --with-rsvg --with-dbus --with-xft --without-gpm --with-x-toolkit=gtk3 --with-toolkit-scroll-bars --x-includes=/usr/include --x-libraries=/usr/lib64 --with-libotf --with-m17n-flt --with-xwidgets --build=x86_64-suse-linux 'CFLAGS=-O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -g -D_GNU_SOURCE -DGDK_DISABLE_DEPRECATION_WARNINGS -DGLIB_DISABLE_DEPRECATION_WARNINGS -pipe -Wno-pointer-sign -Wno-unused-variable -Wno-unused-label -fno-optimize-sibling-calls -fno-PIE -DSYSTEM_PURESIZE_EXTRA=55000 	 -DSITELOAD_PURESIZE_EXTRA=10000 ' LDFLAGS=-Wl,-O2")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, upstream/develop, upstream/HEAD 4b20c7206 2020-03-13 17:34:44 -0400")
  (dir . "~/.config/doom/"))
 (system
  (type . gnu/linux)
  (config . "x86_64-suse-linux-gnu")
  (shell . "/usr/bin/zsh")
  (uname . "Linux 5.5.7-1-default #1 SMP Sun Mar 1 19:28:06 UTC 2020 (1004bce) x86_64")
  (path "~/.pyenv/shims" "~/.emacs.d/bin/" "~/bin" "~/bin" "~/go/bin" "~/.cargo/bin" "~/.yarn/bin" "~/.rbenv/bin" "~/.cabal/bin/" "~/.emacs.d/bin/" "~/.local/bin" "~/bin" "/usr/local/bin" "/usr/bin" "/bin" "/usr/lib/emacs/26.3/x86_64-suse-linux"))
 (config
  (envfile)
  (elc-files . 0)
  (modules :completion company (ivy +icons) :ui deft doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces zen :editor (evil +everywhere) file-templates fold format multiple-cursors rotate-text snippets word-wrap :emacs (dired +icons) electric vc :term vterm :checkers syntax :tools (eval +overlay) (lookup +docsets) lsp magit :lang data emacs-lisp go (javascript +lsp) latex markdown (org +dragndrop +journal +pandoc +present) plantuml (python +pyenv +lsp) (ruby +rbenv +lsp) (rust +lsp) sh web :email mu4e :config literate (default +bindings +smartparens))
  (packages (evil-escape :disable t) (org-bookmark-heading :disable t) (tao-theme :recipe (:host github :repo "alexandergraul/tao-theme-emacs")) (dockerfile-mode) (salt-mode) (excorporate) (modus-operandi-theme) (modus-vivendi-theme) (org-roam :recipe (:host github :repo "jethrokuan/org-roam")))
  (unpin "n/a")
  (elpa "n/a")))

</pre></details>

**Comment by sei40kr** [comment]
@agraul 
Does my PR fix your problem?
https://github.com/hlissner/doom-emacs/pull/2777
