### ISSUE TITLE
How can I remap one leader to another key?

### ISSUE THREAD

**Issue by qhuyduong** [hlissner/doom-emacs#2751]
> Please visit our Discord server to ask how-to and workflow questions:
> https://discord.gg/qvGgnVx -- post on Doom's issue tracker as a last resort.

**What are you trying to achieve?**
I want to remap the leader `s`(search) to another key (`/` for example) without having to create a new one and duplicate all the items under. Is it possible?

**Comment by yoavm448** [comment]
```emacs-lisp
(map! :leader
      "/" doom-leader-search-map)
```
That's possible because doom binds all of its `SPC *` commands on separate maps, so you have `doom-leader-search-map`, `doom-leader-open-map`, etc.

**Comment by qhuyduong** [comment]
It's neat! That's why I love doom. Thank you very much @yoavm448 .
