### ISSUE TITLE
Company suggestions disapear on quick-help

### ISSUE THREAD

**Issue by tecosaur** [hlissner/doom-emacs#2752]
**What did you expect to happen?**
For company suggestions to stick around after the quick-help shows up (in `emacs-lisp-mode`).

**What actually happened?**
They, they, ... _\*hic_, they **disappeared!** :sob: 

**Additional details:**
- [Private config](https://github.com/tecosaur/emacs-config/)
- Screencast:
![company-disapearing](https://user-images.githubusercontent.com/20903656/77230159-3d5a0980-6bcd-11ea-9587-81f52d3fdcfa.gif)
- Nothing interesting in `*Messages*` but here it is:
<details><pre>
Battery status not available
Loading /home/tec/.config/doom/.custom.el (source)...done
‘def-package!’ was renamed to ‘use-package!’; use that instead.
Applying colors:
((0 . #23262F) (1 . #FE655B) (2 . #7AC174) (3 . #FBCD7A) (4 . #50AEEE) (5 . #A890F0) (6 . #5BEEFE) (7 . #BAC1CE) (8 . #61676D) (9 . #FE655B) (10 . #7AC174) (11 . #FBCD7A) (12 . #50AEEE) (13 . #A890F0) (14 . #5BEEFE) (15 . #BAC1CE))
Successfully applied colors!
Doom loaded 318 packages across 57 modules in 0.898s
Loading /home/tec/.emacs.d/.local/cache/recentf...done
Wrote /home/tec/.emacs.d/.local/cache/undo-tree-hist/.!home!tec!.orhc-bibtex-cache.~undo-tree~.zst
Entities are now displayed as UTF8 characters
Starting new Ispell process hunspell with en_GBs_au_SCOWL_80_0_k_hr dictionary...
Buffer has been modified; could not load undo-tree history
Mark set
eldoc error: (void-function org-get-outline-path)
Using vacuous schema
Automatic display of crossref information was turned on
Mark set [2 times]
Type "q" to delete help window.
Searched 0/1 files
Searched 1/1 files
Wrote /home/tec/.emacs.d/.local/cache/undo-tree-hist/.!usr!share!emacs!26.3!lisp!subr.el.gz.~undo-tree~.zst
Searched 0/1 files
Searched 1/1 files
Mark set [5 times]
</pre></details>

**Steps to reproduce:**
1. Open new `emacs-lisp-mode` buffer
2. Type something suggestive
3. Trigger company
4. Observe suggestions, wait for the popup
5. Wail in sadness as you see your suggestions disappear when the quick-help arrives

**System information:**
<details><pre>
emacs   version    26.3
        features   XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GSETTINGS GLIB NOTIFY GNUTLS LIBXML2 FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD
        build      Oct 05, 2019
        buildopts  (--prefix=/usr --build=x86_64-solus-linux --libdir=/usr/lib64 --mandir=/usr/share/man --infodir=/usr/share/info --datadir=/usr/share --sysconfdir=/etc --localstatedir=/var --libexecdir=/usr/lib64/emacs --with-modules --with-xwidgets --with-x-toolkit=gtk3 'CFLAGS=-mtune=generic -march=x86-64 -g2 -O2 -pipe -fPIC -Wformat -Wformat-security -D_FORTIFY_SOURCE=2 -fstack-protector-strong --param ssp-buffer-size=32 -fasynchronous-unwind-tables -ftree-vectorize -feliminate-unused-debug-types -Wall -Wno-error -Wp,-D_REENTRANT' 'LDFLAGS=-Wl,--copy-dt-needed-entries -Wl,-O1 -Wl,-z,relro -Wl,-z,now -Wl,-z,max-page-size=0x1000 -Wl,-Bsymbolic-functions -Wl,--sort-common')
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop c049ada61 2020-03-11 00:57:44 -0400
        dir        ~/.config/doom/
system  type       gnu/linux
        config     x86_64-solus-linux-gnu
        shell      /bin/zsh
        uname      Linux 5.5.7-150.current #1 SMP PREEMPT Wed Mar 4 03:31:00 UTC 2020 x86_64
        path       (~/.local/bin /opt/SageMath ~/.pyenv/bin ~/.cargo/bin /sbin /bin /usr/sbin /usr/bin /usr/local/bin /snap/bin /usr/lib64/emacs/emacs/26.3/x86_64-solus-linux/)
config  envfile    envvar-file
        elc-files  181
        modules    (:completion (company +childframe) (ivy +icons +prescient) :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) pretty-code (tabs +centaur-tabs) treemacs vc-gutter vi-tilde-fringe (window-select +numbers) workspaces zen :editor (evil +everywhere) file-templates fold (format +onsave) multiple-cursors rotate-text snippets :emacs (dired +icons) electric (ibuffer +icons) vc :term vterm :checkers syntax spell grammar :tools ansible debugger (eval +overlay) (lookup +dictionary +docsets) lsp magit make pdf rgb upload :lang data emacs-lisp ess (javascript +lsp) (latex +latexmk +cdlatex) ledger markdown (org +dragndrop +jupyter +pandoc +gnuplot +present) (python +lsp) (rust +lsp) sh web :config literate (default +bindings +smartparens))
        packages   ((some-package) (another-package :recipe (:host github :repo username/repo)) (this-package :recipe (:host github :repo username/repo :files (some-file.el src/lisp/*.el))) (builtin-package :disable t) (builtin-package :recipe (:nonrecursive t)) (builtin-package-2 :recipe (:repo myfork/package)) (builtin-package :recipe (:branch develop)) (company-tabnine :recipe (:host github :repo TommyX12/company-tabnine :files (company-tabnine.el fetch-binaries.sh))) (prettify-utils :recipe (:host github :repo Ilazki/prettify-utils.el)) (rotate) (xkcd) (selectric-mode) (wttrin) (spray) (theme-magic) (flyspell-lazy) (calctex :recipe (:host github :repo johnbcoughlin/calctex :files (*.el))) (ess-view) (systemd) (org-pretty-table-mode :recipe (:host github :repo Fuco1/org-pretty-table)) (ox-gfm) (org-ref) (org-fragtog) (org-graph-view :recipe (:host github :repo alphapapa/org-graph-view)) (org-chef))
        unpin      (n/a)
        elpa       (n/a)
</pre></details>

**Comment by minikN** [comment]
I can confirm this. This just happens (at least for me) using `lisp-mode`.

**Comment by blw90** [comment]
Same here. If I disable `company-box-doc-enable` suggestion won't disappear without the Documentation window.

**Comment by ferhaterata** [comment]
Same problem occurs in different modes.

![Peek 2020-03-20 08-54](https://user-images.githubusercontent.com/5862659/77403642-e1d37b80-6d86-11ea-8c8e-68b8f889c067.gif)

**Comment by bandresen** [comment]
Maybe it's obvious, but for search purposes this issue exists only for (company +childframe) which uses [company-box](https://github.com/sebastiencs/company-box), which seems to be abandoned. (Last commit over a year ago, while several PRs and issues have been piling up.)

@hlissner 
I suggest to label this has:workaround or that the +childframe sets `company-box-doc-enable` to `nil`.

**Comment by tecosaur** [comment]
Sorry, maybe I'm blind, but what's the workaround?

**Comment by bandresen** [comment]
> Sorry, maybe I'm blind, but what's the workaround?
set `company-box-doc-enable` to nil.

**Comment by tecosaur** [comment]
Wait, so the workaround to a feature not working, is to turn off the feature?

**Comment by bandresen** [comment]
My understanding is that the feature is company suggestions. They disappear due to quick-help being enabled and the library responsible for quick-help not being actively maintained.

Therefor the workaround to get the feature of not having broken company completion/suggestions is to disable the quick-help popup. Another alternative to not having broken company completion is not to use +childframe and therefor skipping the unmaintained company-box library.

**Comment by ferhaterata** [comment]
I had to set it nil once I knew it. `(setq company-box-doc-enable nil)` The problem is if I use `C-h` on a suggestion, the same problem occurs again: the company box disappears. Btw, this also happens on different modes as well (e.g. `sml-mode`). I think it is not specific to `emacs-lisp-mode`.

**Comment by hlissner** [comment]
Thanks to dinkonin in Discord, I've zeroed in on the cause of this issue. As of 7e40c1e this should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by ferhaterata** [comment]
it is fixed! thanks!
