### ISSUE TITLE
M-x recover-session  not work

### ISSUE THREAD

**Issue by PengjuXu** [hlissner/doom-emacs#2754]
Steps:
1. open Doom Emacs
2. Somehow crash it
3. start again, M-x recover-session

Result:
"recover-session: No previous sessions to recover"

Expected:
Be able to recover sessions

Cause:
mismatch of these 2 vars
auto-save-list-file-prefix `~/.emacs.d/auto-save-list/.saves-`
auto-save-list-file-name   `~/.emacs.d/.local/cache/autosave`

~/.emacs.d/core/core-editor.el
auto-save-list-file-name was changed but not auto-save-list-file-prefix
which tricked recover-session

```elisp
;; Don't autosave files or create lock/history/backup files. We don't want
;; copies of potentially sensitive material floating around, and we'll rely on
;; git and our own good fortune instead. Fingers crossed!
(setq auto-save-default nil
      create-lockfiles nil
      make-backup-files nil
      ;; But have a place to store them in case we do use them...
      auto-save-list-file-name (concat doom-cache-dir "autosave")
      backup-directory-alist `(("." . ,(concat doom-cache-dir "backup/"))))
```

And default to not autosave does not seem a good idea.

**Comment by hlissner** [comment]
As of a038e77 `recover-session` should work correctly Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
