### ISSUE TITLE
Try to archive an org item, but got failure "org-archive-subtree: Symbol’s function definition is void: org-get-outline-path"

### ISSUE THREAD

**Issue by whjiang** [hlissner/doom-emacs#2757]
**What did you expect to happen?**
I tried key `C-c C-x C-s` to archive a subtree, but got failure:
```
org-archive-subtree: Symbol’s function definition is void: org-get-outline-path
```

**What actually happened?**
...

**Steps to reproduce:**
1. Select these example steps,
2. Delete them,
3. And replace them with precise steps to reproduce your issue.
4. Fill in "system information" below.

**System information:**
<details><pre>
Place the output of `M-x doom/info` or `~/.emacs.d/bin/doom info` here.
</pre></details>

**Comment by hlissner** [comment]
I cannot reproduce this. Please provide your `M-x doom/info` and more precise steps to reproduce the issue. I cannot investigate this further otherwise.

**Comment by peterhoeg** [comment]
I'm seeing something similar although in my case it is caused by eldoc trying to show the path.

If I do `(require 'org-refile)` which is where `org-get-outline-path` is defined (without an autoload) the error disappears and eldoc starts showing the path correctly.

**Comment by peterhoeg** [comment]
So on 5th Feb, this function moved from `org.el` to `org-refile.el`:

    commit f636cf91b6cbe322eca56e23283f4614548c9d65
    Author: Bastien <bzg@gnu.org>
    Date:   Wed Feb 5 15:34:06 2020 +0100

So it looks like it just isn't being required correctly.
