### ISSUE TITLE
add roam flag to org module

### ISSUE THREAD

**Issue by bdarcus** [hlissner/doom-emacs#2759]
The new `org-roam` minor mode is now on MELPA. It would be great if it could be included as a flag on the `org` module, much like the `brain` flag for the similar `org-brain`.

Installation instructions are [here](https://org-roam.readthedocs.io/en/latest/installation/#doom-emacs), based on input from @hlissner.

**Comment by hlissner** [comment]
As of f28a304 Doom's `:lang org` module now has a `+roam` flag to install org-roam, so I'll consider this resolved. Let me know if you encounter any issues using it. Thanks for bringing it to my attention!

**Comment by bdarcus** [comment]
Thank you!

I'm running into a problem, though I don't understand what's going on behind the scenes to understand where that problem lies. Hopefully this screenshot demonstrates.

I added it over at [the org-roam repo issue also](https://github.com/jethrokuan/org-roam/issues/311).

![Screenshot from 2020-03-30 09-18-27](https://user-images.githubusercontent.com/1134/77916683-721e2e80-7267-11ea-9748-c939d2849a29.png)

**Comment by bdarcus** [comment]
Looks like this is the problem, and solution.

https://github.com/hlissner/doom-emacs/commit/f28a304abd1b9e13c4e1217211bef305c5f3badc#r38132446

**Comment by bdarcus** [comment]
One other question: how do you deal with iterating these packages? When the org-roam repo is updated past the pinned commit in doom, what happens?
