### ISSUE TITLE
Disable mode-line hiding

### ISSUE THREAD

**Issue by amosbird** [hlissner/doom-emacs#276]
Sometimes normal buffers lose mode line due to unknown reasons. I'd like to disable this mode line hiding feature. I did `(advice-add #'doom-hide-modeline-mode :override #'ignore)` but it doesn't seem to work. `*Messages*` buffer still doesn't have mode line shown.

**Comment by hlissner** [comment]
>Sometimes normal buffers lose mode line due to unknown reasons

This is likely because of an issue I've been chasing where `doom-popup-mode` is being activated in non-popups.

You may have better luck with:

```emacs-lisp
(remove-hook 'doom-popup-mode-hook #'doom|hide-modeline-in-popup)
```

**Comment by amosbird** [comment]
@hlissner Hi, it's great to hear from you again :) I removed all the shackle related stuff for a while and it works quite stabler ...

**Comment by hlissner** [comment]
Fair enough. The popup system is overdue for a rewrite! In the meantime, I will close this issue.

**Comment by amosbird** [comment]
@hlissner Hello, the new popup feature hides the modeline aggresively.
Neither
```
(remove-hook 'doom-popup-mode-hook #'doom|hide-modeline-in-popup)
```
nor
```
(advice-add #'doom-hide-modeline-mode-mode :override #'ignore)
```
works

**Comment by hlissner** [comment]
`doom-popup-mode-hook` doesn't exist anymore. You want:

```emacs-lisp
(remove-hook '+popup-buffer-mode-hook #'+popup|set-modeline)
```

Or, you can change the default modeline settings for all popups:

```emacs-lisp
(map-put +popup-default-parameters 'modeline t)
```

**Comment by amosbird** [comment]
Hmm, it doesn't work. Where should I put those elisp?

**Comment by hlissner** [comment]
In `private/$USER/config.el` (not in init.el, that's too soon).

Which one did you try?

Also, I've just pushed a bunch of updates to the popup module, so you should update first.

**Comment by hlissner** [comment]
Btw, if you are testing with the scratch and messages buffer, there was a bug in ui/doom-modeline (fixed just now in https://github.com/hlissner/doom-emacs/commit/a5bb69cf6a73729d3192234f3be25ff09d3149c3) that caused them to not have a mode-line if you copied [this line that is in my private module](https://github.com/hlissner/doom-emacs-private/blob/master/init.el#L4) to yours.

**Comment by amosbird** [comment]
Hmm, I tried both just now. Still not working.

**Comment by amosbird** [comment]
Ah, removing  '(mode-line-format nil) fixes this :)
