### ISSUE TITLE
dired says hit 'g' to refresh but that does something else

### ISSUE THREAD

**Issue by vigilancetech-com** [hlissner/doom-emacs#2767]
**What did you expect to happen?**
dired should refresh or it should give the correct key sequence to refresh

**What actually happened?**
it brought up the 'g' leader key menu

**Additional details:**

- Include a link to your private config
I don't think this is necessary because I just installed and there's nothing remarkable in there.

- Include screenshots/casts of your issue

also shouldn't be necessary because everyone with a somewhat generic install should have the same issue (and with my new minimal window manager I haven't figured out how to do this yet)

- If you mention key sequences, include what commands they're bound to 

inspecting keys does no good because the 'g' is a leader key and doesn't result in a complete key sequence

- Include any warnings or errors logged to \*Messages\* (use `M-x
  view-echo-area-messages` to see it).

no warnings

<details><pre>
If an error message is involved include a backtrace of it.

no error message

How to acquire a backtrace:
https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#how-to-extract-a-backtrace-from-an-error
</pre></details>

**Steps to reproduce:**

I had a bunch of PDF files left over from windows who's names were upper case but they had internal links to each other in lower case so they didn't work in Linux.   In order to try and get these running I marked them all then did a M-x dired-downcase command on them.   Some of the file names didn't get updated in the buffer (not sure how one could reproduce this as it was probably a glitch).  I tried to go into one of the still upper case ones to see what was going on and it told me the file was no longer there and I should hit 'g' to refresh it.   When I did it just gave me the 'g' leadin key menu.   

**System information:**
<details>

```
emacs   version    26.2
        features   XPM JPEG TIFF GIF PNG RSVG SOUND GPM DBUS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE XFT ZLIB GTK3 X11 XDBE XIM THREADS LIBSYSTEMD LCMS2
        build      Jun 29, 2019
        buildopts  (--prefix=/usr --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu --mandir=/usr/share/man --infodir=/usr/share/info --datadir=/usr/share --sysconfdir=/etc --localstatedir=/var/lib --disable-silent-rules --docdir=/usr/share/doc/emacs-26.2 --htmldir=/usr/share/doc/emacs-26.2/html --libdir=/usr/lib64 --program-suffix=-emacs-26 --includedir=/usr/include/emacs-26 --infodir=/usr/share/info/emacs-26 --localstatedir=/var --enable-locallisppath=/etc/emacs:/usr/share/emacs/site-lisp --without-compress-install --without-hesiod --without-pop --with-file-notification=inotify --enable-acl --with-dbus --without-modules --without-gameuser --with-gpm --with-kerberos --with-kerberos5 --with-lcms2 --with-xml2 --without-mailutils --without-selinux --with-gnutls --with-libsystemd --with-threads --without-wide-int --with-zlib --with-sound=alsa --with-x --without-ns --without-gconf --without-gsettings --without-toolkit-scroll-bars --with-gif --with-jpeg --with-png --with-rsvg --with-tiff --with-xpm --without-imagemagick --with-xft --without-cairo --without-libotf --without-m17n-flt --with-x-toolkit=gtk3 --without-xwidgets 'CFLAGS=-O2 -march=x86-64 -pipe' CPPFLAGS= 'LDFLAGS=-Wl,-O1 -Wl,--as-needed')
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop, origin/develop, origin/HEAD 4b20c7206 2020-03-13 17:34:44 -0400
        dir        ~/.doom.d/
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/bash
        uname      Linux 5.4.0-sabayon #1 SMP Tue Feb 25 22:46:38 UTC 2020 x86_64
        path       (~/bin ~/sbin ~/.npm-global/bin ~/.emacs.d/bin /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /opt/bin /usr/lib/llvm/9/bin /usr/games/bin /usr/libexec/emacs/26.2/x86_64-pc-linux-gnu/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold snippets :emacs dired electric vc :checkers syntax spell :tools (eval +overlay) lookup magit :lang clojure csharp data emacs-lisp fsharp javascript latex factor markdown (org +dragndrop +present) racket scheme sh :config (default +bindings +smartparens))
        packages   (n/a)
        unpin      (n/a)
        elpa       (n/a)
```
</details>

**Comment by yoavm448** [comment]
FYI you can update dired with `gr`, when using evil.

**Comment by hlissner** [comment]
> it brought up the 'g' leader key menu

Not the leader key, but the `g` prefix in normal mode, which has a number of sub bindings.

In any case, we are using the `evil-collection` package, which provides "evilified" keybinds for a number of packages, including dired. It [binds `gr` to revert-buffer here](https://github.com/emacs-evil/evil-collection/blob/master/modes/dired/evil-collection-dired.el#L125), which is what you want. You'll find other keybinds there too.

Hope that helps!
