### ISSUE TITLE
How to enable fuzzy matching in ivy

### ISSUE THREAD

**Issue by vigilancetech-com** [hlissner/doom-emacs#2768]
**Describe the feature**

when searching for a command it would be great if ivy matched fuzzy, especially with regard to dashes.   For example, if you're searching for a dired command but you fail to put in the dash it just goes to zero results.   One should be able to type in 'diredre' and see everything from dired refresh to dired regexp type commands, but if you don't put in the '-' it shows nothing.

- If the feature involves new plugins, include links to them

I don't think so
- If the feature involves replacement of current functionality, how the new
  functionality is better?

it gives you a lot more chances to find the command plus it saves typing

- If the feature is implemented in another editor or Emacs distro, include:
  - Screenshots or screencasts of it

I think at one time spacemacs did this with helm but I can't currently get it running so I can't provide these.

  - Links to its implementation

I don't know where in the source code or settings this is (yet another reason I've wanted to migrate away from spacemacs)

  - Names of relevant commands (and not only the keybinds to invoke them)

I don't know.

**System information**
<details><pre>
```
emacs   version    26.2
        features   XPM JPEG TIFF GIF PNG RSVG SOUND GPM DBUS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE XFT ZLIB GTK3 X11 XDBE XIM THREADS LIBSYSTEMD LCMS2
        build      Jun 29, 2019
        buildopts  (--prefix=/usr --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu --mandir=/usr/share/man --infodir=/usr/share/info --datadir=/usr/share --sysconfdir=/etc --localstatedir=/var/lib --disable-silent-rules --docdir=/usr/share/doc/emacs-26.2 --htmldir=/usr/share/doc/emacs-26.2/html --libdir=/usr/lib64 --program-suffix=-emacs-26 --includedir=/usr/include/emacs-26 --infodir=/usr/share/info/emacs-26 --localstatedir=/var --enable-locallisppath=/etc/emacs:/usr/share/emacs/site-lisp --without-compress-install --without-hesiod --without-pop --with-file-notification=inotify --enable-acl --with-dbus --without-modules --without-gameuser --with-gpm --with-kerberos --with-kerberos5 --with-lcms2 --with-xml2 --without-mailutils --without-selinux --with-gnutls --with-libsystemd --with-threads --without-wide-int --with-zlib --with-sound=alsa --with-x --without-ns --without-gconf --without-gsettings --without-toolkit-scroll-bars --with-gif --with-jpeg --with-png --with-rsvg --with-tiff --with-xpm --without-imagemagick --with-xft --without-cairo --without-libotf --without-m17n-flt --with-x-toolkit=gtk3 --without-xwidgets 'CFLAGS=-O2 -march=x86-64 -pipe' CPPFLAGS= 'LDFLAGS=-Wl,-O1 -Wl,--as-needed')
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop, origin/develop, origin/HEAD 4b20c7206 2020-03-13 17:34:44 -0400
        dir        ~/.doom.d/
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/bash
        uname      Linux 5.4.0-sabayon #1 SMP Tue Feb 25 22:46:38 UTC 2020 x86_64
        path       (~/bin ~/sbin ~/.npm-global/bin ~/.emacs.d/bin /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /opt/bin /usr/lib/llvm/9/bin /usr/games/bin /usr/libexec/emacs/26.2/x86_64-pc-linux-gnu/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold snippets :emacs dired electric vc :checkers syntax spell :tools (eval +overlay) lookup magit :lang clojure csharp data emacs-lisp fsharp javascript latex factor markdown (org +dragndrop +present) racket scheme sh :config (default +bindings +smartparens))
        packages   (n/a)
        unpin      (n/a)
        elpa       (n/a)
```

</pre></details>

**Comment by yoavm448** [comment]
There's the `+fuzzy` flag you can give to the ivy module, which gives you fuzzy matching with [`flx`](https://github.com/lewang/flx). Otherwise, in normal ivy you can type `"dired re"` which would yield commands containing both `"dired"` and `"re"`. This is all written in the ivy module docs, `SPC h d m ivy`.

**Comment by hlissner** [comment]
Judging from your doom/info, you have not enabled the `+fuzzy` feature on the `:completion ivy` module. See the [ivy module's readme for details on its available flags](https://github.com/hlissner/doom-emacs/blob/develop/modules/completion/ivy/README.org#module-flags). See [this guide on how to enable and disable moduels and/or their flags](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#modules).
