### ISSUE TITLE
How do I enable some modes on doom startup

### ISSUE THREAD

**Issue by dessasin** [hlissner/doom-emacs#2769]
> Please visit our Discord server to ask how-to and workflow questions:
> https://discord.gg/qvGgnVx -- post on Doom's issue tracker as a last resort.

**What are you trying to achieve?**
I am web developer and I started using Doom-emacs just. I want to enable some non-global modes on doom startup, such as web-mode,rainbow,skewer,js-mode e.g.Finally, I cannot login to the discod server because I cannot pass the login stage because the bot that meets me at the entrance does not work.
...

**What have you tried?**
I tried some stackoverflow solutions but I couldn't get the result I wanted.

- [https://tinyurl.com/y4qar2wc](https://tinyurl.com/y4qar2wc)
- [https://tinyurl.com/u682l2p](https://tinyurl.com/u682l2p)
- [https://tinyurl.com/tmr2dr6](https://tinyurl.com/tmr2dr6)
...

**Additional information**
- Do you have screenshots/casts of this workflow in another editor or Emacs
  distro? (If possible, include names of specific commands or functions from
  other editors/emacs distros)
- Do you have additional material or links to resources that could help clarify
  what you are trying to do?

**System information**
<details><pre>
```
emacs   version    26.3
        features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS LIBSYSTEMD LCMS2
        build      Sep 23, 2019
        buildopts  (--build x86_64-linux-gnu --prefix=/usr --sharedstatedir=/var/lib --libexecdir=/usr/lib --localstatedir=/var/lib --infodir=/usr/share/info --mandir=/usr/share/man --enable-libsystemd --with-pop=yes --enable-locallisppath=/etc/emacs:/usr/local/share/emacs/26.3/site-lisp:/usr/local/share/emacs/site-lisp:/usr/share/emacs/26.3/site-lisp:/usr/share/emacs/site-lisp --with-sound=alsa --without-gconf --with-mailutils --build x86_64-linux-gnu --prefix=/usr --sharedstatedir=/var/lib --libexecdir=/usr/lib --localstatedir=/var/lib --infodir=/usr/share/info --mandir=/usr/share/man --enable-libsystemd --with-pop=yes --enable-locallisppath=/etc/emacs:/usr/local/share/emacs/26.3/site-lisp:/usr/local/share/emacs/site-lisp:/usr/share/emacs/26.3/site-lisp:/usr/share/emacs/site-lisp --with-sound=alsa --without-gconf --with-mailutils --with-x=yes --with-x-toolkit=gtk3 --with-toolkit-scroll-bars 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/emacs-wvqver/emacs-26.3+1=. -fstack-protector-strong -Wformat -Werror=format-security -Wall' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro')
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop, origin/develop, origin/HEAD 4b20c7206 2020-03-13 17:34:44 -0400
        dir        ~/.doom.d/
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /usr/bin/zsh
        uname      Linux 5.3.0-7642-generic #34~1584408018~19.10~21df4b1-Ubuntu SMP Tue Mar 17 13:38:51 UTC  x86_64
        path       (/usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /usr/games /usr/local/games /usr/lib/emacs/26.3/x86_64-linux-gnu/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company helm ivy :ui deft doom doom-dashboard doom-quit hl-todo indent-guides modeline nav-flash ophints (popup +defaults) pretty-code treemacs unicode vc-gutter vi-tilde-fringe window-select workspaces zen :editor (evil +everywhere) file-templates fold (format +onsave) snippets :emacs dired electric vc :term term :checkers syntax :tools (eval +overlay) lookup magit rgb :lang data emacs-lisp (haskell +dante) javascript markdown (org +dragndrop +jupyter +pomodoro +present) purescript sh web :app calendar twitter :config (default +bindings +smartparens))
        packages   ((auto-complete) (prettier-js) (stylelint))
        unpin      (n/a)
        elpa       (n/a)
```
</pre></details>

**Comment by yoavm448** [comment]
All of the modes you specified are buffer-specific. The doom modules which configure them (`:lang javascript`, `web`...) should detect the file type you open and activate them when needed. The only exception is rainbow, which isn't enabled automatically. If you want rainbow-mode on all web related buffers, that's not enabling it globally. Instead you should activate it hook-based, like it says in the links you gave. 
For example, to enable rainbow-mode whenever editing a file with web-mode:
```emacs-lisp
;; in your config.el
(add-hook 'web-mode-hook #'rainbow-mode)
```
You can adapt that for other hooks and modes. I suggest using `SPC h v` and `SPC h f` to look up hook names and mode functions. 
If you want to enable modes based on filetypes yourself, you should use `(use-package! ... :mode ..."`. `use-package!`'s documentation, like all functions, is accessible with `SPC h f`.  

---
Regarding discord, at the top of `#readme` there's an emoji reaction you have to click to get into the server. Did that not work?
![image](https://user-images.githubusercontent.com/40410676/77481836-2fa2bf00-6e2d-11ea-8d70-081eb37bf4f0.png)

**Comment by dessasin** [comment]
Thank you for helping. You can close issue right now I will try your suggestions
