### ISSUE TITLE
Cannot open large files

### ISSUE THREAD

**Issue by Macavirus** [hlissner/doom-emacs#2771]
**What did you expect to happen?**
...
#1834 appears to not be resolved for me.

**What actually happened?**
...
Open a json file ~ 5MB, emacs chokes at 100% CPU and never actually renders the file (blank window).

**Additional details:**

No error message, because emacs never completes opening the file.
Opening a file with find-file-literally works fine.

<details><pre>
If an error message is involved include a backtrace of it.

How to acquire a backtrace:
https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#how-to-extract-a-backtrace-from-an-error
</pre></details>

**Steps to reproduce:**
1. Select these example steps,
2. Delete them,
3. And replace them with precise steps to reproduce your issue.
4. Fill in "system information" below.

**System information:**
<details>

```
emacs   version    26.3
system  type       gnu/linux
config     x86_64-pc-linux-gnu
```
</details>

**Comment by innerout** [comment]
Have you tried using [vlf](https://github.com/m00natic/vlfi/tree/cc02f2533782d6b9b628cec7e2dcf25b2d05a27c)?

**Comment by Macavirus** [comment]
Looking  back at this now, the actual issue was that `So Long` mode was not activating properly. It must have been long since fixed, as I can happily open files of similar size and `So Long` activates properly now. Thanks @hlissner !
