### ISSUE TITLE
Adjust a rule's priority of evil-matchit in web-mode and html-mode

### ISSUE THREAD

**Issue by jadestrong** [hlissner/doom-emacs#2774]
https://github.com/redguardtoo/evil-matchit/issues/119
In web-mode and html-mode, evil-matchit must adjust the rule's priority,  if not, it will jump to the end of the buffer when current line has a `if` keyword.
I think this adjust can be integrated into doom.
```
(evilmi-load-plugin-rules '(web-mode) '(simple template html))
```
html-mode also need this adjust.

**Comment by hlissner** [comment]
We no longer use evil-matchit. It was removed in 5d94f048b6b7.

**Comment by jadestrong** [comment]
But `%` still bound to `evilmi-jump-items` now. Maybe `evil-collection` still use `evil-matchit` ?
```
evilmi-jump-items is an interactive and compiled function defined in
evil-matchit.el.

Signature
(evilmi-jump-items &optional NUM)

Documentation
Jump between items.

Key Bindings
evil-matchit-mode-map <normal-state> %
evil-matchit-mode-map <visual-state> %

References
evilmi-jump-items is unused in evil-matchit.el.

```

**Comment by hlissner** [comment]
`%` is bound to `evil-jump-item`. Evil-collection does not install evil-matchit. Perhaps you're on a 10+ month old commit of Doom? Or you've installed it yourself in your private config?

**Comment by jadestrong** [comment]
So sorry for this. Yes, I add this package myself, because the default `evil-jump-item` can't work with html tag.
