### ISSUE TITLE
`+ivy/projectile-find-file` hangs when called in the root of filesystem

### ISSUE THREAD

**Issue by sei40kr** [hlissner/doom-emacs#2778]
**What did you expect to happen?**
Called `+ivy/projectile-find-file` in ~home directory~ the root of filesystem.

**What actually happened?**
Emacs hanged.

**Additional details:**
Doom Emacs counts the files in a project synchronously, so Emacs hangs if there're a huge number of files in the directory.
https://github.com/hlissner/doom-emacs/blob/develop/modules/completion/ivy/autoload/ivy.el#L227

**Steps to reproduce:**
1. Open Doom Emacs
2. Press `SPC SPC`

**System information:**
<details><pre>
((emacs
  (version . "27.0.60")
  (features . "RSVG IMAGEMAGICK GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS XWIDGETS PDUMPER LCMS2 GMP")
  (build . "Feb 23, 2020")
  (buildopts "--disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus/HEAD-693749c/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus/HEAD-693749c --with-xml2 --without-dbus --with-gnutls --with-imagemagick --with-modules --with-rsvg --with-xwidgets --with-ns --disable-ns-self-contained")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> fix-region-format, origin/fix-region-format 7d1093dc2 2020-03-26 22:49:00 +0900")
  (dir . "~/.doom.d/"))
 (system
  (type . darwin)
  (config . "x86_64-apple-darwin19.3.0")
  (shell . "/usr/local/bin/zsh")
  (uname . "Darwin 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64")
  (path "~/.nvm/versions/node/v10.16.3/bin" "~/.zinit/plugins/starship---starship" "~/.zinit/plugins/julienXX---terminal-notifier" "~/.zinit/plugins/direnv---direnv" "~/.rbenv/shims" "~/.pyenv/shims" "~/.goenv/shims" "~/.zinit/polaris/bin" "~/.local/bin" "~/.yarn/bin" "~/.gem/ruby/2.6.0/bin" "~/.rbenv/bin" "~/.pyenv/bin" "~/.poetry/bin" "~/perl5/bin" "~/perl5/perlbrew/bin" "~/.goenv/bin" "~/go/system/bin" "~/.cargo/bin" "/Applications/Emacs.app/Contents/MacOS" "/Applications/Emacs.app/Contents/MacOS/bin" "/usr/local/bin" "/usr/local/sbin" "/usr/bin" "/bin" "/usr/sbin" "/sbin" "/Library/TeX/texbin" "/usr/local/Cellar/emacs-plus/HEAD-693749c/libexec/emacs/27.0.60/x86_64-apple-darwin19.3.0"))
 (config
  (envfile . envvar-file)
  (elc-files . 11)
  (modules :completion (company +childframe) ivy :ui doom doom-dashboard hl-todo hydra modeline nav-flash ophints (popup +all +defaults) tabs treemacs vc-gutter window-select workspaces :editor (evil +everywhere) file-templates (format +onsave) multiple-cursors snippets word-wrap :emacs (dired +icons) vc :term vterm :checkers (syntax +childframe) :tools ansible debugger (docker +lsp) editorconfig ein eval (lookup +docsets) lsp magit make rgb tmux :lang assembly (cc +lsp) (data +yaml-lsp) emacs-lisp (ess +lsp) (go +lsp) (haskell +lsp) (java +lsp) (javascript +lsp) (kotlin +lsp) (markdown +grip) (org +dragndrop +gnuplot +jupyter) perl (php +lsp) plantuml (python +lsp +pyenv) rest (ruby +lsp +rails +rbenv) (rust +lsp) (scala +lsp) (sh +lsp) solidity (web +css +html +lsp) :config (default +bindings +smartparens))
  (packages (company-emoji :pin "fc45b56f3e") (expand-region :pin "0fa7c2d349") (vagrant-tramp :pin "f67925928d") (pyenv-mode :disable t) (pyvenv :disable t) (rbenv :disable t))
  (unpin "n/a")
  (elpa "n/a")))
</pre></details>

**Comment by hlissner** [comment]
The real problem here is that it somehow gets past the first check:

```elisp
((or (file-equal-p default-directory "~")
     (when-let (proot (doom-project-root))
       (file-equal-p proot "~")))
 #'counsel-find-file)
```

Why? Does `(expand-file-name "~")` not match `(getenv "HOME")`?

I cannot reproduce this behavior.

**Comment by sei40kr** [comment]
@hlissner 
Sorry it was not home directory.
Somehow the default directory in the home buffer is `//` in my Emacs 27 and it equals to the root of filesystem.

**Comment by hlissner** [comment]
Ah I see. I've added a check for root in fa23a91, which should resolve this issue. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
