### ISSUE TITLE
Some keybinds seem to be inaccessible

### ISSUE THREAD

**Issue by Vimru** [hlissner/doom-emacs#2780]
**What are you trying to achieve?**
I'm trying to use the keybinds after the `SPC w` prefix:
`C-S-l`, `C-S-j`, etc.

However they seem to be impossible to use since `SPC w C-S` is it's own binding, so you can never complete `SPS w C-S-j`.

**What have you tried?**
Just tried using Emacs keybindings as normal. I'm aware I could change the keybindings in the relevant `config.el` but I'm wondering if there is actually a way to do this, or if `C-S-l` was intended to be a placeholder for user customisation?

**Additional information**
n/a

**System information**
<details>

```
emacs   version    26.3
        features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2
        build      Aug 29, 2019
        buildopts  (--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-modules 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now)
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop, origin/develop, origin/HEAD 97a3950ec 2020-03-27 05:20:02 -0400
        dir        ~/.doom.d/
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/bash
        uname      Linux 5.5.9-arch1-2 #1 SMP PREEMPT Thu, 12 Mar 2020 23:01:33 +0000 x86_64
        path       (~/.pyenv/shims /usr/local/bin /usr/local/sbin /usr/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl ~/.emacs.d/bin /usr/lib/emacs/26.3/x86_64-pc-linux-gnu/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold snippets :emacs dired electric vc :checkers syntax :tools (eval +overlay) lookup magit :lang data emacs-lisp markdown (org +dragndrop +present) python sh :config (default +bindings +smartparens))
        packages   (n/a)
        unpin      (n/a)
        elpa       (n/a)
```
</details>

**Comment by hlissner** [comment]
I'm not sure I understand the problem. By `C-S` I assume you mean `C-S-s` (ctrl+shift+s, i.e. ctrl + capital s). A `SPC w C-S-s` keybind does exist, but why would that block `SPC w C-S-j`? These are two independent key sequences that do not conflict. 

Emacs doesn't allow you to bind directly to modifier keys so by `C-S` you couldn't have meant `ctrl+shift`. Could you elaborate?

**Comment by Vimru** [comment]
Ahh I thought `C-S-s` meant ctrl + shift + s + s.

Thanks for sorting this!
