### ISSUE TITLE
irony and rdm not starting on c++ file load

### ISSUE THREAD

**Issue by jkl1337** [hlissner/doom-emacs#2789]
**What did you expect to happen?**
irony-mode and rtags to load when a C++ file is opened.

**What actually happened?**
irony and rtags/rdm do not start. 

**Additional details:**
commit 169f9a6121d moved the initialization function for irony and rtags to hooks called after-<major-mode>-mode rather than the local-vars hooks. Not sure if this is only something supported on emacs 27, but on 26.3 these never seem to run.

**Comment by hlissner** [comment]
My bad, some experimental code snuck into the commit. As of 5033215 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
