### ISSUE TITLE
TAB can't open org drawer when evil "+everywhere" is not enabled

### ISSUE THREAD

**Issue by whjiang** [hlissner/doom-emacs#2798]
For org mode, if I enabled `(evil +everywhere)`，the TAB work correctly for headlines and org drawers (PROPERTIES). I checked the mode map, TAB is mapped to `company-complete-common-or-cycle`. 

But, if I disabled `+everywhere`, just use `evil`, the TAB can only open headlines, but can NOT open org drawers. I checked the mode map, TAB is still mapped to `company-complete-common-or-cycle`. And it says TAB mapping to `org-cycle` has been overridden. 

How to make TAB work correctly without `+everywhere` enabled?

**Comment by hlissner** [comment]
I've removed the overzealous TAB keybind in b8a3cad, which should resolve this issue. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
