### ISSUE TITLE
Question: Python, nose disabled, doom doctor warns "Not executeable"; is that the normal behavior?

### ISSUE THREAD

**Issue by dastagg** [hlissner/doom-emacs#2804]
In my packages.el file:

```
;; If you'd like to disable a package included with Doom, for whatever reason,
;; you can do so here with the `:disable' property:
;(package! builtin-package :disable t)
(package! anaconda-mode  :disable t)
(package! pipenv         :disable t)
(package! pyvenv         :disable t)
(package! nose           :disable t)
(package! pyimport       :disable t)
(package! py-isort       :disable t)
```

**What did you expect to happen?**
...
When I run ./doom doctor it wouldn't show me a message about running nosetests or support for pipenv.

**What actually happened?**
...
  > :lang python
      ! Couldn't find pipenv. pipenv support will not work.
      ! Couldn't find nosetests. Running tests through nose will not work.

If this is the "normal" behavior, that's fine, I know they "will not work" because I disabled them but just wanted to make sure that I don't have something incorrect.

**Comment by hlissner** [comment]
This is normal behavior. The doctor (currently) does not behave differently if the package was disabled.

**Comment by dastagg** [comment]
Okay. Thanks for the quick response.
Should I close this or do you want to keep it open for the "pending-fix" status?

**Comment by dastagg** [comment]
Actually, I will close this and if you want to re-open it, go ahead.
