### ISSUE TITLE
Use TeX-fold in +fold/toggle for TeX documents

### ISSUE THREAD

**Issue by mpardalos** [hlissner/doom-emacs#2805]
Currently in TeX documents, +fold/toggle folds using hideshow folds. It would be nice if we could get it to use TeX-fold. This is by default bound to C-c C-o C-o. 

**System information**
<details>

```
emacs   version    26.3
        features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2
        build      Aug 29, 2019
        buildopts  (--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-modules 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now)
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop e5ac4cbff 2020-03-29 01:31:27 -0400
        dir        ~/.config/dotfiles/doom_emacs/
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/sh
        uname      Linux 5.5.13-arch1-1 #1 SMP PREEMPT Wed, 25 Mar 2020 16:04:40 +0000 x86_64
        path       (/opt/omnisharp-roslyn/ ~/.bin/ ~/.emacs.d/bin ~/.emacs.d/bin ~/.local/bin ~/.bin /usr/local/bin /usr/local/sbin /usr/bin /var/lib/flatpak/exports/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /usr/lib/emacs/26.3/x86_64-pc-linux-gnu)
config  envfile    nil
        elc-files  0
        modules    (:completion (ivy +icons +prescient +fuzzy) (company +auto) :ui doom modeline ophints hl-todo nav-flash treemacs (popup +all +defaults) (pretty-code +fira) vc-gutter vi-tilde-fringe window-select hydra zen :editor (evil +everywhere +commands) snippets file-templates multiple-cursors rotate-text fold format :emacs (dired +icons) vc :tools lookup eval make magit (lsp +peek) editorconfig pdf ein :lang (sh +fish) emacs-lisp markdown (haskell +lsp) (org +attach +babel +export) (cc +lsp) ocaml idris (web +html +css) (latex +latexmk +viewers) (python +lsp) (fsharp +lsp) (javascript +lsp) rest data :checkers grammar spell (syntax +childframe) :term vterm eshell)
        packages   ((vimrc-mode) (alloy-mode :recipe (:host github :repo dwwmmn/alloy-mode)) (fill-column-indicator) (hugo :recipe (:host github :repo aaronbieber/hugo.el)) (evil-snipe :disable t) (rebecca-theme))
        unpin      (n/a)
        elpa       (n/a)
```
</details>

**Comment by yoavm448** [comment]
I don't think you're giving the full picture here.

TeX-fold is mostly for folding LaTeX macros to unicode and to make them less intrusive, like `\alpha` to `\u0251`, `\footnote{...}` to `[f]`. It can also fold environments, but that wouldn't be the behavior `TeX-fold-dwim` (`C-c C-o C-o`) gives most of the time. Use `TeX-fold-env` instead.

AUCTeX also support outline-mode, to fold sections, subsections etc. Outline *is* targeted by `:editor fold`. I think the best solution would be to activate `outline-minor-mode` on LaTeX buffers and fold through that, instead of patching the fold module to use `TeX-fold-env`.

**Comment by mpardalos** [comment]
Ok, I didn't know about outline mode and tbh it's pretty nice for folding sections.

I was actually looking for the behaviour that `TeX-fold-env` gives, you are correct. If I use `Tex-fold-dwim` on a `\begin{...}` then it will only fold that command, not the whole env. 

Do you think it would be reasonable to incrorporate `TeX-fold-env` into `+fold/toggle`?

**Comment by yoavm448** [comment]
I'm not the one to decide on this - but I don't think it'd be reasonable to add any mode-specific functions to `:editor fold`, unless it'd be refactored to allow general registration of folding functions. Instead I think we should look into registering TeX-fold to `outline` or `hideshow` (which *are* general :)).

I'll try to look into it next week...

**Comment by yoavm448** [comment]
I managed to do it with hideshow, completely without TeX-fold's help.
![image](https://user-images.githubusercontent.com/40410676/78248294-08b34f80-74f5-11ea-8108-bea6415e460d.png)
Unless you have any remarks, I'll send a PR shortly.

**Comment by mpardalos** [comment]
That looks perfect.
