### ISSUE TITLE
Python: Pipenv minor mode not activated by default

### ISSUE THREAD

**Issue by anihm136** [hlissner/doom-emacs#2814]
**What did you expect to happen?**
...
Pipenv mode is activated automatically in python buffers, and pipenv commands are available

**What actually happened?**
...
Pipenv minor mode needs to be manually enabled before accessing commands

**Additional details:**
* Link to dotfiles: https://paste.ee/p/P3mLy

**System information:**
<details><pre>
Loading /etc/emacs/site-start.d/00debian.el (source)...
Loading /etc/emacs/site-start.d/50autoconf.el (source)...
Loading /etc/emacs/site-start.d/50cmake-data.el (source)...
Loading /etc/emacs/site-start.d/50dictionaries-common.el (source)...
Loading debian-ispell...
Loading /var/cache/dictionaries-common/emacsen-ispell-default.el (source)...
Loading /var/cache/dictionaries-common/emacsen-ispell-dicts.el (source)...
Loading /etc/emacs/site-start.d/50global.el (source)...
((emacs
  (version . "26.3")
  (features . "XAW3D XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS LUCID X11 XDBE XIM THREADS LIBSYSTEMD LCMS2")
  (build . "Sep 23, 2019")
  (buildopts "--build x86_64-linux-gnu --prefix=/usr --sharedstatedir=/var/lib --libexecdir=/usr/lib --localstatedir=/var/lib --infodir=/usr/share/info --mandir=/usr/share/man --enable-libsystemd --with-pop=yes --enable-locallisppath=/etc/emacs:/usr/local/share/emacs/26.3/site-lisp:/usr/local/share/emacs/site-lisp:/usr/share/emacs/26.3/site-lisp:/usr/share/emacs/site-lisp --with-sound=alsa --without-gconf --with-mailutils --build x86_64-linux-gnu --prefix=/usr --sharedstatedir=/var/lib --libexecdir=/usr/lib --localstatedir=/var/lib --infodir=/usr/share/info --mandir=/usr/share/man --enable-libsystemd --with-pop=yes --enable-locallisppath=/etc/emacs:/usr/local/share/emacs/26.3/site-lisp:/usr/local/share/emacs/site-lisp:/usr/share/emacs/26.3/site-lisp:/usr/share/emacs/site-lisp --with-sound=alsa --without-gconf --with-mailutils --with-x=yes --with-x-toolkit=lucid --with-toolkit-scroll-bars --without-gsettings 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/emacs-wvqver/emacs-26.3+1=. -fstack-protector-strong -Wformat -Werror=format-security -Wall' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro'")
  (windowsys . batch)
  (daemonp))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD 4434abf1f 2020-04-01 14:51:12 -0400")
  (dir . "~/.config/doom/"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/usr/bin/zsh")
  (uname . "Linux 5.3.0-40-generic #32-Ubuntu SMP Fri Jan 31 20:24:34 UTC 2020 x86_64")
  (path "~/miniconda3/condabin" "~/.cargo/bin" "~/.local/bin" "/usr/local/sbin" "/usr/local/bin" "/usr/sbin" "/usr/bin" "/sbin" "/bin" "/usr/games" "/usr/local/games" "/snap/bin" "/usr/lib/jvm/jdk-13.0.1+9/bin" "/opt/lampp/bin" "~/Applications" "~/.scripts" "~/.emacs.d/bin" "~/.antigen/bundles/robbyrussell/oh-my-zsh/lib" "~/.antigen/bundles/romkatv/powerlevel10k" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/command-not-found" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/pip" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/pipenv" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/python" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/node" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/npm" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/cargo" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/rust" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/django" "~/.antigen/bundles/esc/conda-zsh-completion" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/git" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/common-aliases" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/web-search" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/sudo" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/vi-mode" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/z" "~/.antigen/bundles/zdharma/fast-syntax-highlighting" "~/.antigen/bundles/zsh-users/zsh-completions" "~/.fzf/bin" "/usr/lib/emacs/26.3/x86_64-linux-gnu"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard hl-todo modeline nav-flash ophints (popup +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold format snippets word-wrap :emacs dired electric vc :term eshell :checkers syntax spell :tools direnv (eval +overlay) lookup lsp magit pdf :lang (cc +lsp) data emacs-lisp (java +lsp) (javascript +lsp) markdown (org +pandoc) (python +lsp +conda) (web +lsp) :config (default +bindings +smartparens))
  (packages (smart-tabs :recipe (:host github :repo "dochang/smarttabs" :branch "keep-indent-setting")) (org-wild-notifier) (aggressive-indent) (evil-unimpaired :recipe (:host github :repo "zmaas/evil-unimpaired")))
  (unpin "n/a")
  (elpa "n/a")))
</pre></details>

**Comment by anihm136** [comment]
I think the issue is that the mode-hooks that I'm defining aren't being recognised for some reason. I tried with another package (importmagic), and am facing the same issue. Further, lsp mode is also not activated by default on python buffers, though lsp module is enabled and the lsp feature for python is enabled.
I suspect I'm missing something trivial, but I'm not sure what

**Comment by hlissner** [comment]
> Pipenv minor mode needs to be manually enabled before accessing commands

Did you mean `pipenv-mode`? [It is attached to python-mode-hook](https://github.com/hlissner/doom-emacs/blob/develop/modules/lang/python/config.el#L200), so I suspect this is a config issue. A brief scan of your config.el doesn't show any issues -- although you are eagerly loading a great deal of Emacs at startup, which may or may not be causing issues.

Are there any errors or warnings in the \*Messages\* buffer (`SPC h e` to open it) after starting a python buffer? It would also explain why LSP isn't starting for you (which the module most certainly [sets up for you](https://github.com/hlissner/doom-emacs/blob/develop/modules/lang/python/config.el#L24-L25)).

> evil-unimpaired

Side question: I'm curious why you installed this package. [Doom already offers all of, if not more of, vim-unimpaired's keybinds](https://github.com/hlissner/doom-emacs/blob/develop/modules/editor/evil/config.el#L425-L472). Is there something missing?

**Comment by anihm136** [comment]
Thanks for the prompt response! I'm a newbie to doom Emacs, so I don't have a clue about best practices for config. I just stepped away for a break, will check back and let you know in a few hours.

As for unimpaired, the only thing I was really missing were the paste bindings (`[p` and `]p`). I wasn't aware that doom had unimpaired keybindings too

**Comment by anihm136** [comment]
I can confirm that the issue is with my config. I restarted a python buffer after commenting out my whole config, and both pipenv and lsp are enabled as expected.
>  Doom already offers all of, if not more of, vim-unimpaired's keybinds 
I took a look at this, and it really seems to cover all the keybinds (except the paste bindings). Would you consider adding them? I can probably remove that package anyway and just have 2 mappings for paste

**Comment by anihm136** [comment]
I think I've sorted out most of the issues. As you said, they were probably occuring due to eager loading, so I looked at how the packages are configured and am changing my config to be more like them. Thanks!
