### ISSUE TITLE
doom install not working, error: gnutls error -50

### ISSUE THREAD

**Issue by Aetiuss** [hlissner/doom-emacs#2816]
Hello, Windows 10 user here !

Recently I tried to reinstall emacs and doom in order to reset everything, 

I've reinstalled it with chocolatey like I did previously, 

I've cloned your repo and renamed it .emacs.d, 

But now when I cd .. into my emacs folder and try .\.emacs.d\bin\doom install, 

The script start to run correctly but stop after 1 seconde and return error gnutls [-50], 

Here is the output on debug mode :

```
 Debug mode on
[32mInstalling Doom Emacs!
[0m
> Creating .doom.d/
  [32mâo" Created .doom.d/[0m
[33m! init.el already exists, skipping[0m
[33m! config.el already exists, skipping[0m
[33m! packages.el already exists, skipping[0m

Loading c:/ProgramData/chocolatey/lib/Emacs/tools/emacs/.emacs.d/core/autoload/buffers.el (source)...
Loading c:/ProgramData/chocolatey/lib/Emacs/tools/emacs/.emacs.d/core/autoload/cache.el (source)...
Loading c:/ProgramData/chocolatey/lib/Emacs/tools/emacs/.emacs.d/core/autoload/cli.el (source)...
Loading c:/ProgramData/chocolatey/lib/Emacs/tools/emacs/.emacs.d/core/autoload/config.el (source)...
Loading c:/ProgramData/chocolatey/lib/Emacs/tools/emacs/.emacs.d/core/autoload/debug.el (source)...
Loading c:/ProgramData/chocolatey/lib/Emacs/tools/emacs/.emacs.d/core/autoload/files.el (source)...
Loading c:/ProgramData/chocolatey/lib/Emacs/tools/emacs/.emacs.d/core/autoload/fonts.el (source)...
Loading c:/ProgramData/chocolatey/lib/Emacs/tools/emacs/.emacs.d/core/autoload/format.el (source)...
Loading c:/ProgramData/chocolatey/lib/Emacs/tools/emacs/.emacs.d/core/autoload/help.el (source)...
Loading c:/ProgramData/chocolatey/lib/Emacs/tools/emacs/.emacs.d/core/autoload/packages.el (source)...
Loading c:/ProgramData/chocolatey/lib/Emacs/tools/emacs/.emacs.d/core/autoload/plist.el (source)...
Loading c:/ProgramData/chocolatey/lib/Emacs/tools/emacs/.emacs.d/core/autoload/projects.el (source)...
Loading c:/ProgramData/chocolatey/lib/Emacs/tools/emacs/.emacs.d/core/autoload/scratch.el (source)...
Loading c:/ProgramData/chocolatey/lib/Emacs/tools/emacs/.emacs.d/core/autoload/sessions.el (source)...
Loading c:/ProgramData/chocolatey/lib/Emacs/tools/emacs/.emacs.d/core/autoload/text.el (source)...
Loading c:/ProgramData/chocolatey/lib/Emacs/tools/emacs/.emacs.d/core/autoload/themes.el (source)...
Loading c:/ProgramData/chocolatey/lib/Emacs/tools/emacs/.emacs.d/core/autoload/ui.el (source)...
DOOM Initializing package.el
DOOM Initializing straight
gnutls.el: (err=[-50] The request is invalid.) boot: (:priority SECURE128:+SECURE192:-VERS-ALL:+VERS-TLS1.2:+VERS-TLS1.3 :hostname raw.githubusercontent.com :loglevel 0 :min-prime-bits 3072 :trustfiles nil :crlfiles nil :keylist nil :verify-flags nil :verify-error t :callbacks nil)
[31mx There was an unexpected error:[0m
  [1mType:[0m gnutls-error
  [1mMessage:[0m
    GnuTLS error
  [1mData:[0m
    #<process raw.githubusercontent.com>
    -50
```

Run the command again with the -d (or --debug) switch to enable debug
mode and (hopefully) generate a backtrace from this error:

**Comment by hlissner** [comment]
Could you open vanilla Emacs and do `M-x describe-variable RET libgnutls-version` and tell me its value?

Also, have you installed Emacs 26 or 27?

**Comment by Aetiuss** [comment]
Thanks a lot for helping me !
I'm on emacs 26.3 and the value of my libgnutls-version is 30608

**Comment by hlissner** [comment]
Seems an older version of gnutls is on Windows. Try this:

1. Modify https://github.com/hlissner/doom-emacs/blob/develop/core/core.el#L195 (I'm guessing you'll find this file in `C:\Users\USERNAME\.emacs.d\core\core.el`) like so:

   ```diff
          gnutls-algorithm-priority
          (concat "SECURE128:+SECURE192:-VERS-ALL:+VERS-TLS1.2"
   -              (if (ignore-errors (>= libgnutls-version 30605))
   +              (if (ignore-errors (> libgnutls-version 30608))
                    ":+VERS-TLS1.3"))
          ;; `gnutls-min-prime-bits' is set based on recommendations from
   ```

2. Then try `doom install` again.

**Comment by Aetiuss** [comment]
This worked perfectly thank you a lot !
@vqhuy I didn't installed gnutls personnaly but I think it came with emacs when I installed it with chocolatey.

**Comment by vqhuy** [comment]
okay, let's wait and see we see the problem again. Thanks!

**Comment by alexDarcy** [comment]
@vqhuy Actually, I removed the comment because the fix solved my issue (I used ">=" instead of "<"). Sorry for the trouble.

**Comment by dbechrd** [comment]
@hlissner this fixed it for me as well, thanks.

**Comment by mattias** [comment]
I usually run linux and have this working on my linux machines, but I wanted to have it on my windows machine as well, but got this error when I tried doom install.

The only things I've installed is as the installation instructions for windows mentions, which is:
`choco install git emacs ripgrep fd llvm`

Then I cloned the repo and went for doom install as per instructions.

Changing core.el worked for me.

**Comment by hlissner** [comment]
@alexDarcy @dbechrd @mattias What is the value of `libgnutls-version` on your systems? (See `SPC h v libgnutls-version` or `C-h v libgnutls-version`)

**Comment by dbechrd** [comment]
@hlissner 30608

**Comment by alexDarcy** [comment]
30608 as well when the issue was present. I've upgraded since to 30609.

**Comment by hlissner** [comment]
@alexDarcy And you still have the issue on 30609?

**Comment by alexDarcy** [comment]
@hlissner The fix mentioned in this thread worked for 30608 so I removed my comment asking for help. It still works after the update. 
Sorry if it was not clear.

**Comment by hlissner** [comment]
@alexDarcy I meant: does it work _without_ the fix?

**Comment by alexDarcy** [comment]
@hlissner No, I needed the fix.

**Comment by quinn-dougherty** [comment]
i had same problem as OP, switching line 195 of core.el fixed it for me.

**Comment by hlissner** [comment]
I've disabled TLS 1.3 on Windows, which should fix your issues. If that's not the case let me know.

**Comment by alexDarcy** [comment]
@hlissner  I did a reinstall to check that and it works like a charm. Thanks !
