### ISSUE TITLE
org-fontify-done-headline nil not obeyed

### ISSUE THREAD

**Issue by oskarkv** [hlissner/doom-emacs#2825]
**What did you expect to happen?**

I expected that `(setq org-fontify-done-headline nil)` would stop org from coloring the whole headline after setting a todo to done.

**What actually happened?**

In org, done todos' whole headlines are fontified with the `org-headline-done` face, even when `org-fontify-done-headline` is `nil`.

![org-fontify-done-headline not working](https://i.imgur.com/ATY5S4p.png)

Also note that the documentations has disappeared (in the screen shot) from the `org-fontify-done-headline` variable. I find that strange.

**System information:**

<details><pre>
((emacs
  (version . "26.3")
  (features . "XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD LCMS2")
  (build . "Sep 16, 2019")
  (buildopts "--build=x86_64-linux-gnu --prefix=/usr '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' --sysconfdir=/etc --localstatedir=/var --disable-silent-rules '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' --disable-maintainer-mode --disable-dependency-tracking --prefix=/usr --sharedstatedir=/var/lib --program-suffix=26 --with-modules --with-file-notification=inotify --with-mailutils --with-x=yes --with-x-toolkit=gtk3 --with-xwidgets --with-lcms2 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/emacs26-TP6iDo/emacs26-26.3~1.git96dd019=. -fstack-protector-strong -Wformat -Werror=format-security -no-pie' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro -no-pie'")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD a381f5926 2020-04-03 02:12:50 -0400")
  (dir . "~/.doom.d/"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/usr/bin/zsh")
  (uname . "Linux 4.15.0-91-generic #92-Ubuntu SMP Fri Feb 28 11:09:48 UTC 2020 x86_64")
  (path "~/.local/bin" "~/.cask/bin" "~/node_modules/.bin" "~/bin" "~/bin" "/usr/local/sbin" "/usr/local/bin" "/usr/sbin" "/usr/bin" "/sbin" "/bin" "/usr/games" "/usr/local/games" "/usr/racket/bin" "~/hy/bin" "~/.fzf/bin" "/usr/lib/x86_64-linux-gnu/emacs/26.3/x86_64-linux-gnu"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard fill-column hl-todo modeline nav-flash ophints (popup +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold (format +onsave) snippets :emacs dired electric vc :checkers syntax :tools (eval +overlay) lookup magit make pdf rgb :lang clojure data emacs-lisp markdown (org +dragndrop +present) python sh :email (mu4e +gmail) :config (default +bindings))
  (packages (command-log-mode :recipe (:host github :repo "lewang/command-log-mode")) (webpaste :recipe (:host github :repo "etu/webpaste.el")))
  (unpin "n/a")
  (elpa "n/a")))
</pre></details>

**Comment by yuchen-lea** [comment]
Same with me. I tried in sandbox:
1. vanilla Emacs (nothing loaded): `org-fontify-done-headline` is t by default, but when you change it to nil, it works
2. vanilla Doom (only Doom core): change `org-fontify-done-headline` to nil, and the done headings are colored still

**Comment by hlissner** [comment]
be4fe44 removes the org defaults from the doom-themes package, which was one thing that conflicted with your config.

The next: remember to wrap your personal configuration in `(after! org ...)` if you want your config to overwrite any of Doom's defaults.

**Comment by yuchen-lea** [comment]
Amazing speed! I followed the steps: updraded to latest version of doom, wrap your personal configuration in (after! org ...).

Sadly still it still doesn't work.

I summarize my attempts as follows:

<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">


<colgroup>
<col  class="org-left" />

<col  class="org-left" />

<col  class="org-left" />

<col  class="org-left" />

<col  class="org-left" />
</colgroup>
<thead>
<tr>
<th scope="col" class="org-left">&#xa0;</th>
<th scope="col" class="org-left">emacs -q</th>
<th scope="col" class="org-left">sandbox vanilla Emacs (nothing loaded)</th>
<th scope="col" class="org-left">sandbox vanilla Emacs (nothing loaded)</th>
<th scope="col" class="org-left">sandbox vanilla Emacs (only Doom core)</th>
</tr>
</thead>

<tbody>
<tr>
<td class="org-left">org-version</td>
<td class="org-left">9.3</td>
<td class="org-left">9.4</td>
<td class="org-left">9.4</td>
<td class="org-left">9.4</td>
</tr>


<tr>
<td class="org-left">default value</td>
<td class="org-left">nil</td>
<td class="org-left">t</td>
<td class="org-left">t</td>
<td class="org-left">t</td>
</tr>


<tr>
<td class="org-left">what I did</td>
<td class="org-left">nothing</td>
<td class="org-left">toggle nil, save for current, then org-mode</td>
<td class="org-left">org-mode, toggle nil, save for current</td>
<td class="org-left">org-mode, toggle nil, save for current</td>
</tr>


<tr>
<td class="org-left">fontify done?</td>
<td class="org-left">no</td>
<td class="org-left">no</td>
<td class="org-left">yes</td>
<td class="org-left">yes</td>
</tr>
</tbody>
</table>

Maybe something wrong with doom loading order? org-fontify-done-headline seems have to be set before org-mode.

**Comment by hlissner** [comment]
```elisp
(after! org
  (setq org-fontify-done-headline nil))
```

As I suggested works fine for me in vanilla Doom.

**Comment by hlissner** [comment]
Found the issue. Should be fixed as of 7205b72.

**Comment by yuchen-lea** [comment]
Appreciate your work. Now the checked item does't dim, but (setq org-fontify-done-headline nil) still fontify the done headlines.

I use literate and here's my config:

```
(after! org
  (setq org-hide-leading-stars nil
        org-fontify-done-headline nil
        org-fontify-whole-heading-line nil
        )
)
```

Below is the minimal demo in sandbox:

<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">


<colgroup>

<col  class="org-left" />

<col  class="org-left" />

<col  class="org-left" />
</colgroup>
<thead>
<tr>
<th scope="col" class="org-left">&#xa0;</th>
<th scope="col" class="org-left">sandbox vanilla Emacs (nothing loaded)</th>
<th scope="col" class="org-left">sandbox vanilla Emacs (nothing loaded)</th>
</tr>
</thead>

<tbody>
<tr>
<td class="org-left">org-version</td>
<td class="org-left">9.4</td>
<td class="org-left">9.4</td>
</tr>


<tr>
<td class="org-left">default value</td>
<td class="org-left">t</td>
<td class="org-left">t</td>
</tr>


<tr>
<td class="org-left">what I did</td>
<td class="org-left">toggle nil, save for current, then org-mode</td>
<td class="org-left">org-mode, toggle nil, save for current</td>
</tr>


<tr>
<td class="org-left">fontify done?</td>
<td class="org-left">no</td>
<td class="org-left">yes</td>
</tr>
</tbody>
</table>

**Comment by hlissner** [comment]
Turns out my earlier solution was incomplete. As of 03fa1d8 it should finally be fixed.

**Comment by yuchen-lea** [comment]
Yeah! It works! So many thanks!
