### ISSUE TITLE
"bibliographic" module

### ISSUE THREAD

**Issue by bdarcus** [hlissner/doom-emacs#2827]
# Description

We need a “bibtex” or “bibliographic” module, similar to the bibtex layer in spacemacs.

There’s an earlier PR #698, which started as a suggested “reference” module, but then evolved into a `+reference` flag on the `org` module, and I guess was never finished.

I would argue it would be better to have a separate module, since the functionality here needs to provide integration into document authoring workflows in `org`, `markdown` (see screeenshot below of what this looks like), and `latex`, along with support for working from bibtex and biblatex files.

![Screenshot from 2020-04-05 10-54-09](https://user-images.githubusercontent.com/1134/78501872-d93a5800-772b-11ea-8353-09f97c72c9b1.png)

# Spacemacs Implementation

What I'm proposing is similar to the spacemacs [bibtex layer](https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Blang/bibtex), which integrates the following packages:

- Auctex
- Org
- Org-ref
- Markdown-mode
- Helm-bibtex
- Biblio
- biblio-core

All of the above are on MELPA.

A doom module should obviously also integrate `ivy-bibtex` (which provides equivalent functionality to `helm-bibtex`) depending on which completion engine feature is selected.

I also wonder about two other packages:

1. `org-noter` (when the `pdf` and `org` features are selected?); #698 contemplates adding this to the pdf module, but I think it belongs here
2. `ebib` (here I'm less sure; maybe others with experience could weigh in?)

# Conclusion

I know a lot about bibliographic tools in general (I created the CSL language that is used by a lot of bibliographic tools and services), less about emacs and doom, and elisp programming. But I am doing what I can to cobble this together [here](https://github.com/bdarcus/.doom.d/blob/master/org-academic.org#bibliographic-management-and-integration), where the doom org module and org-roam support is the core.

I will continue to work on this and do what I can, but hoping someone with greater expertise than I will ultimately submit a proper doom module.

If this is an appropriate request, I can post additional details (like commands) as a needed.

**Comment by brianmcgillion** [comment]
modules/lang/latex has most of the setup. The notable exceptions are org-ref and org-noter.

**Comment by bdarcus** [comment]
Now that I'm thinking about this more, am not exactly sure how this should all fit together in the context of doom. We basically have a few areas of functionality:
1. editing and working with bib(la)tex files
2. finding and importing bibliographic data and adding to those bib(la)tex files (biblio and org-ref have overlapping functionality here)
3. browsing and inserting citations (derived from the above bib(la)tex files) into different authoring workflows; notably org, markdown, latex.

**Comment by bdarcus** [comment]
Given #2838 it would seem that "small biblio module" I mention in my last comment might start with simply providing something like this, and a few keybindings, and then expanded in time as needed?

``` elisp
(use-package! ivy-bibtex
  :when (featurep! :completion ivy)
  :commands (ivy-bibtex)
  :config
  (setq ivy-bibtex-default-action 'ivy-bibtex-insert-key)
  (add-to-list 'ivy-re-builders-alist '(ivy-bibtex . ivy--regex-plus)))

(use-package! helm-bibtex
  :when (featurep! :completion helm)
  :commands helm-bibtex)
```

**Comment by patrl** [comment]
I like this idea. I already do something like this myself in my private config. I'd suggest `SPC n b` as a reasonably mnemonic keybinding.

Regarding other possible targets for inclusion in this module:

I'm intrigued by ebib, but it looks like it will be a lot of work to create a set of keybindings for. I started putting together a doom module for it ages ago. You can find the code here, if you're interested! https://github.com/patrl/.doom.d/tree/master/modules/tools/ebib

I'm not sure org-noter really belongs here, personally. It's purely a tool for document annotation, so adding a `+noter` flag or similar to the pdf module would make more sense. One integration that could be nice would be a custom `ivy-bibtex` action that starts an `org-noter` session, just in case the `+noter` flag is active on the pdf module.

**Comment by bdarcus** [comment]
> I like this idea. I already do something like this myself in my private config. I'd suggest `SPC n b` as a reasonably mnemonic keybinding.

+1.

I modified my setup with this basic idea (though a different keybinding), [here](https://github.com/bdarcus/.doom.d/tree/master/modules/tools/biblio).

> Regarding other possible targets for inclusion in this module:
> 
> I'm intrigued by ebib, but it looks like it will be a lot of work to create a set of keybindings for. I started putting together a doom module for it ages ago. You can find the code here, if you're interested! https://github.com/patrl/.doom.d/tree/master/modules/tools/ebib
> 
> I'm not sure org-noter really belongs here, personally. It's purely a tool for document annotation, so adding a `+noter` flag or similar to the pdf module would make more sense. 

Yeah, @brianmcgillion has WIP that is going with this idea, which I fully support. Except, he puts it on the org module, which makes more sense to me.

> One integration that could be nice would be a custom `ivy-bibtex` action that starts an `org-noter` session, just in case the `+noter` flag is active on the pdf module.

Good idea!

**Comment by bdarcus** [comment]
> One integration that could be nice would be a custom `ivy-bibtex` action that starts an `org-noter` session

Do you mean an option inserted here, as a distinct option, or that if one selected "edit notes," org-noter would open if available?

![Screenshot from 2020-04-08 05-35-52](https://user-images.githubusercontent.com/1134/78769185-fd2fb080-795a-11ea-8109-73096086ecc1.png)

**Comment by patrl** [comment]
I _think_ the existing "Edit notes" action simply opens an associated org file, so starting a new noter session with that org file feels like a strictly improvement on the existing functionality - so, maybe it makes sense for this to replace the "edit notes" action. Not sure of the best way of accomplishing this however.

**Comment by bdarcus** [comment]
> I _think_ the existing "Edit notes" action simply opens an associated org file, so starting a new noter session with that org file feels like a strictly improvement on the existing functionality - so, maybe it makes sense for this to replace the "edit notes" action. Not sure of the best way of accomplishing this however.

ivy/helm-bibtex does have support for adding new actions; not sure about modifying existing ones though.

https://github.com/tmalsburg/helm-bibtex#create-new-actions

**Comment by bdarcus** [comment]
Where should a "bibilio" module go? Tools?

**Comment by patrl** [comment]
That would be the natural home I think, yes. Let me know if you want me to create the PR for whatever reason, but otherwise if you want to put something together I'd be happy to review.

**Comment by bdarcus** [comment]
Done @patrl - review away. I really don't know what I'm doing, but tried my best ;-)

**Comment by brianmcgillion** [comment]
@bdarcus maybe you could close this as the biblio module now exists and we are almost ready with the additions. https://github.com/hlissner/doom-emacs/pull/2888 ?

**Comment by bdarcus** [comment]
Done. I didn't realize it was still open.
