### ISSUE TITLE
After make update "Cannot open load file: No such file or directory, up-core"

### ISSUE THREAD

**Issue by UtamaruMonster** [hlissner/doom-emacs#283]
After ```make update``` i get ```Eager macro-expansion failure: (file-error "Cannot open load file" "No such file or directory" "up-core")```

Problem in ```use-package```

https://github.com/jwiegley/use-package/issues/533

**Comment by AloisJanicek** [comment]
It's `use-package` problem. Fix is on the way, according to [this](https://github.com/jwiegley/use-package/issues/536) issue thread.  
Temp hack would be to go to `~/.emacs.d/packages/elpa` and remove content of use-package directory and clone use-package into it:
`rm -rf use-package-20171203.1313/*`
`git clone https://github.com/jwiegley/use-package.git use-package-20171203.1313 `

**Comment by hlissner** [comment]
To avoid issues like these in the future, Doom now installs `use-package` from `melpa-stable`. Go ahead and delete `.local/pacakges/elpa/use-package-20171203.1313` and restart Doom to reinstall it.
