### ISSUE TITLE
Literate config.org interferes with ox-hugo auto-export

### ISSUE THREAD

**Issue by grszkthfr** [hlissner/doom-emacs#2833]
**What did you expect to happen?**
I use orgmode with the hugo flag and use its [auto-export](https://ox-hugo.scripter.co/doc/auto-export-on-saving/) function to live-preview my Hugo-rendered pages each time I save the org-subtree. 
This worked as expected until I switched my config.el to config.org and *activated* the `:config/literate` layer in init.el.

(Note, if I revert this, ox-hugo exports as expected.)

**What actually happened?**
No export of the subtree when saving file with pointer in subtree, but error message (see below).

**Additional details:**
`run-hooks: Symbol’s function definition is void: +literate-recompile-maybe-h`

<details><pre>

Debugger entered--Lisp error: (void-function +literate-recompile-maybe-h)
  +literate-recompile-maybe-h()
  run-hooks(after-save-hook)
  #f(compiled-function (&optional called-interactively) "Save the current buffer in its visited file, if it has been modified.\n\nThe hooks `write-contents-functions', `local-write-file-hooks'\nand `write-file-functions' get a chance to do the job of saving;\nif they do not, then the buffer is saved in the visited file in\nthe usual way.\n\nBefore and after saving the buffer, this function runs\n`before-save-hook' and `after-save-hook', respectively." (interactive (quote (called-interactively))) #<bytecode 0x1b52ef>)(t)
  apply(#f(compiled-function (&optional called-interactively) "Save the current buffer in its visited file, if it has been modified.\n\nThe hooks `write-contents-functions', `local-write-file-hooks'\nand `write-file-functions' get a chance to do the job of saving;\nif they do not, then the buffer is saved in the visited file in\nthe usual way.\n\nBefore and after saving the buffer, this function runs\n`before-save-hook' and `after-save-hook', respectively." (interactive (quote (called-interactively))) #<bytecode 0x1b52ef>) t)
  polymode-with-current-base-buffer(#f(compiled-function (&optional called-interactively) "Save the current buffer in its visited file, if it has been modified.\n\nThe hooks `write-contents-functions', `local-write-file-hooks'\nand `write-file-functions' get a chance to do the job of saving;\nif they do not, then the buffer is saved in the visited file in\nthe usual way.\n\nBefore and after saving the buffer, this function runs\n`before-save-hook' and `after-save-hook', respectively." (interactive (quote (called-interactively))) #<bytecode 0x1b52ef>) t)
  apply(polymode-with-current-base-buffer #f(compiled-function (&optional called-interactively) "Save the current buffer in its visited file, if it has been modified.\n\nThe hooks `write-contents-functions', `local-write-file-hooks'\nand `write-file-functions' get a chance to do the job of saving;\nif they do not, then the buffer is saved in the visited file in\nthe usual way.\n\nBefore and after saving the buffer, this function runs\n`before-save-hook' and `after-save-hook', respectively." (interactive (quote (called-interactively))) #<bytecode 0x1b52ef>) t)
  basic-save-buffer(t)
  save-buffer(1)
  funcall-interactively(save-buffer 1)
  call-interactively(save-buffer nil nil)
  command-execute(save-buffer)

</pre></details>

**Steps to reproduce:**
1. Activate `literate` in init.el
2. Prepare config.org
3. Restart doom
4. Try auto-export in ox-hugo

**System information:**
<details><pre>

Compiling your literate config...
Tangled 8 code blocks from config.org

Done!
((emacs
  (version . "26.3")
  (features . "XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2")
  (build . "Aug 29, 2019")
  (buildopts "--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-modules 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD 378cab0c1 2020-03-31 02:16:54 -0400")
  (dir . "~/.doom.d/"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/usr/bin/zsh")
  (uname . "Linux 5.4.27-1-MANJARO #1 SMP PREEMPT Sat Mar 21 16:33:27 UTC 2020 x86_64")
  (path "/usr/local/texlive/2019/bin/x86_64-linux" "~/.pyenv/shims" "~/.pyenv/bin" "~/.local/bin" "~/.local/bin" "/usr/local/bin" "/usr/local/sbin" "/usr/bin" "/usr/lib/jvm/default/bin" "/usr/bin/site_perl" "/usr/bin/vendor_perl" "/usr/bin/core_perl" "/var/lib/snapd/snap/bin" "/usr/lib/emacs/26.3/x86_64-pc-linux-gnu"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard doom-quit fill-column hl-todo modeline nav-flash ophints (popup +defaults) treemacs unicode vc-gutter vi-tilde-fringe window-select workspaces zen :editor (evil +everywhere) file-templates fold multiple-cursors snippets word-wrap :emacs dired electric vc :term vterm :checkers syntax spell :tools editorconfig ein (eval +overlay) lookup magit pdf rgb upload :lang data emacs-lisp ess javascript julia latex markdown (org +roam +dragndrop +hugo +jupyter +pandoc +present) python sh web :config literate (default +bindings +smartparens))
  (packages (org-ref :recipe (:host github :repo "jkitchin/org-ref")))
  (unpin "n/a")
  (elpa "n/a")))

</pre></details>

I am new to Doom Emacs (and emacs/elisp in general), so I don't understand most of the stuff in the details. Also, this is not a urgent bug/issue for me, but now you/people know it's there. :-)

**Comment by hlissner** [comment]
The function [certainly exists](https://github.com/hlissner/doom-emacs/blob/develop/modules/config/literate/autoload.el#L7-L14). Did you remember to run `doom sync` (or `doom refresh`; they're aliases) after enabling the `:config literate` module?

**Comment by grszkthfr** [comment]
Thank you for the prompt response! I did forget that. 1000 apologies! I even saw the function/file, but didn't understand it well enough... :-( 

Now, everything works as expected. :-) Thanks again!
