### ISSUE TITLE
Allow shell to be specified to `doom env`

### ISSUE THREAD

**Issue by logc** [hlissner/doom-emacs#2835]
**Describe the feature**
It would be great if `doom env` allowed to specify the shell program to use when generating or re-generating the env file. This could happen via an option, e.g. `doom env refresh -s SHELL`.

In my case, I specify the shell that I would like to use in daily work (`/usr/local/bin/fish`) as the "command" to run in iTerm, leaving the system default shell to be `/bin/bash`.  Doom Emacs then picks up an env that is not incorrect, but really outdated.

Setting the shell at the application level allows me to fall back to the system default if the shell installed via Homebrew is ever misconfigured or unable to start. That happened to me once with Macports, and I still keep the system default untouched as a safeguard.

Probably this is a corner case,  and I can work around the problem by generating my own env file, but I think this option could make sense for other situations.

**System information**
<details><pre>
((emacs
  (version . "26.3")
  (features . "JPEG RSVG IMAGEMAGICK GLIB NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2")
  (build . "Mar 30, 2020")
  (buildopts "--disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus/26.3/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus/26.3 --with-xml2 --without-dbus --with-gnutls --with-imagemagick --with-modules --with-rsvg --with-ns --disable-ns-self-contained")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop a381f5926 2020-04-03 02:12:50 -0400")
  (dir . "~/.doom.d/"))
 (system
  (type . darwin)
  (config . "x86_64-apple-darwin18.7.0")
  (shell . "/bin/bash")
  (uname . "Darwin 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64")
  (path "~/.jenv/shims" "/usr/local/opt/coreutils/libexec/gnubin" "/usr/local/bin" "/usr/local/sbin" "~/.local/bin" "~/bin" "/usr/local/opt/php@5.6/bin" "/usr/local/opt/libpq/bin" "~/Applications/bin" "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin" "/usr/bin" "/bin" "/usr/sbin" "/sbin" "/usr/local/Cellar/emacs-plus/26.3/libexec/emacs/26.3/x86_64-apple-darwin18.7.0"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold snippets :emacs dired electric vc :term eshell term :checkers syntax spell :tools docker (eval +overlay) lookup macos magit :lang cc data emacs-lisp (java +meghanada) markdown (org +journal) python scala sh :config (default +bindings +smartparens))
  (packages "n/a")
  (unpin "n/a")
</pre></details>

**Comment by logc** [comment]
Let me also thank you for all the hard work on Doom Emacs! I am really enjoying the experience 😄

**Comment by hlissner** [comment]
`doom env` doesn't spawn a shell, so there is nothing to control. It dumps the current process environment to file. Regardless of what shell is used to invoke `bin/doom`, it (the Emacs process) inherits the environment it was executed in. If you use fish and you run `doom env`, it will dump your fish shell environment, whether or not `bin/doom` has a bash shebang line.

To "force" it, you'd have to run `doom env` in the other shell:

```sh
env -i bash -ic "$HOME/.emacs.d/bin/doom env"
```

+ `env -i` runs the following command with a blank environment
+ `bash -ic` runs the command as if it were an interactive shell (hopefully sourcing your dotfiles and creating an environment)

Hope that helps!

**Comment by logc** [comment]
That sounds good. Maybe I got confused because there is a comment at the top of the generated env file that reads `# Generated from a /bin/bash shell environent`. Should it be disregarded?

**Comment by hlissner** [comment]
> # Generated from a /bin/bash shell environent

Ah! Yes, that should be disregarded. There was a time when `doom env` _did_ spawn a shell. I've removed that line in 6bc0fcf. Thanks for bringing that to my attention!

I'll consider this issue resolved, but feel free to follow up here if you have others questions on the matter!
