### ISSUE TITLE
+lookup/definiton doesn't use dante xref backend in haskell-mode

### ISSUE THREAD

**Issue by howsiwei** [hlissner/doom-emacs#2839]
**What did you expect to happen?**
When enabling dante, I expect `+lookup/definiton` to use dante xref backend.

**What actually happened?**
 However, calling `+lookup/definiton` results in
```
xargs: hasktags: No such file or directory
Tags generated.
’myHaskellFunction’ haskell  declaration not found.
```
even though `xref-find-definitions` works perfectly.

**System information:**
<details><pre>
((emacs
  (version . "27.0.60")
  (features . "RSVG IMAGEMAGICK GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS JSON PDUMPER LCMS2 GMP")
  (build . "Jan 26, 2020")
  (buildopts "--disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus/HEAD-baca81e/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus/HEAD-baca81e --with-xml2 --without-dbus --with-gnutls --with-imagemagick --with-json --with-modules --with-rsvg --with-ns --disable-ns-self-contained")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop a381f5926 2020-04-03 02:12:50 -0400")
  (dir . "~/.config/doom/"))
 (system
  (type . darwin)
  (config . "x86_64-apple-darwin19.2.0")
  (shell . "/usr/local/bin/zsh")
  (uname . "Darwin 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64")
  (path "~/.opam/default/bin" "/usr/local/bin" "/usr/bin" "/bin" "/usr/sbin" "/sbin" "/Library/TeX/texbin" "/opt/X11/bin" "/Applications/Wireshark.app/Contents/MacOS" "~/bin" "~/sbin" "~/.local/bin" "/usr/local/sbin" "/usr/local/Cellar/emacs-plus/HEAD-baca81e/libexec/emacs/27.0.60/x86_64-apple-darwin19.2.0"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company ivy :ui doom-dashboard hl-todo modeline (popup +all +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold format multiple-cursors rotate-text snippets word-wrap :emacs dired electric ibuffer vc :term shell :checkers syntax :tools editorconfig (eval +overlay) (lookup +docsets) lsp macos magit pdf :lang (agda +local) (cc +lsp) coq data emacs-lisp (haskell +dante) (latex +latexmk) lua markdown ocaml (org +dragndrop +present) (python +conda +cython +lsp) (rust +lsp) sh web :config (default +bindings +smartparens))
  (packages (solarized-theme) (pdf-view-restore) (graphviz-dot-mode) (rmsbolt) (web-beautify))
  (unpin "n/a")
  (elpa "n/a")))
</pre></details>

**Comment by hlissner** [comment]
Does this fix the issue?

```elisp
(after! dante
  (set-lookup-handlers! 'dante-mode
    :definition #'+lookup-xref-definitions-backend-fn
    :references #'+lookup-xref-references-backend-fn))
```

**Comment by hlissner** [comment]
Another thing to try:

```elisp
(after! haskell-mode
  (set-lookup-handlers! 'haskell-mode nil))
```

**Comment by howsiwei** [comment]
Neither of them fixes the issue. With
```elisp
(after! haskell-mode
  (set-lookup-handlers! 'haskell-mode nil))
```
the echo-area messages become just
```
’myHaskellFunction’ haskell  declaration not found.
```

**Comment by hlissner** [comment]
The lookup module [should fall back to xref](https://github.com/hlissner/doom-emacs/blob/develop/modules/tools/lookup/config.el#L42). That it isn't suggests that either xref is failing, or the lookup module is failing to invoke xref correctly.

Enable debug mode with `SPC h d d`, then try again (without my suggested fixes). It should log what backends it tried in \*Messages\* (`SPC h e` to open it).

If it doesn't yield anything, give this a try:

```elisp
(after! dante
  (set-lookup-handlers! 'haskell-mode :async t
    :definition #'+lookup-xref-definitions-backend-fn
    :references #'+lookup-xref-references-backend-fn))
```

**Comment by howsiwei** [comment]
Thanks for the suggestion. After enabling the debug mode it turns out that xref is indeed failing. Digging through the error message I found the bug.  The following function is called by`+lookup/definition`.
https://github.com/hlissner/doom-emacs/blob/ccd282b28ccb213f8d1d1a2a11421c9a2d4a3cf7/modules/tools/lookup/autoload/lookup.el#L169-L177.

Hoever, `xref--show-xrefs` expect the first argument to be a function that return a list of xref. So a simple fix is changing https://github.com/hlissner/doom-emacs/blob/ccd282b28ccb213f8d1d1a2a11421c9a2d4a3cf7/modules/tools/lookup/autoload/lookup.el#L174 to
```elisp
(xref--show-xrefs (lambda () xrefs) nil)
```

Btw, `xref-find-definitions` actually call `xref--show-defs` instead of `xref--show-xrefs`. The difference seems to be that `xref--show-defs` jump straight to the definition when there is one only one xref whereas `xref--show-xrefs` always show a list of xrefs.

**Comment by hlissner** [comment]
Thanks for looking into it! As of fbbc753 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
