### ISSUE TITLE
Add Vim-like keybindings for references lookup

### ISSUE THREAD

**Issue by Yumasi** [hlissner/doom-emacs#2841]
Currently, when using `+lookup/references` one must use the arrow keys to navigate the results.
Using `hjkl` results in the childframe closing itself. I think it would be better for consistency (and people who simply disables the arrow keys) if Doom had more Vim-like keybindings for reference lookup.

**System information**
<details><pre>
((emacs
  (version . "26.3")
  (features . "XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD")
  (build . "Apr 08, 2020")
  (buildopts "--prefix=/nix/store/1rx6bbd0fcw7h0shz1drrhza1flpvh0w-emacs-26.3 --disable-build-details --with-modules --with-x-toolkit=gtk3 --with-xft CFLAGS=-DMAC_OS_X_VERSION_MAX_ALLOWED=101200")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD e5ac4cbff 2020-03-29 01:31:27 -0400")
  (dir . "~/.doom.d/"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/bin/zsh")
  (uname . "Linux 5.3.0-42-generic #34~18.04.1-Ubuntu SMP Fri Feb 28 13:42:26 UTC 2020 x86_64")
  (path "/nix/store/kf6dsy4hpsy9m16vq4ilndbnh1f6z3wn-emacs-packages-deps/bin" "~/.config/zsh/scripts" "~/.emacs.d/bin" "~/.cargo/bin" "/snap/bin" "~/.nix-profile/bin" "~/.emacs.d/bin" "~/projects/go/bin" "~/.bin" "~/.cargo/bin" "/usr/local/sbin" "/usr/local/bin" "/usr/sbin" "/usr/bin" "/sbin" "/bin" "/usr/games" "/usr/local/games" "~/.config/zsh/plugins/agkozak-zsh-prompt" "~/.config/zsh/plugins/formarks" "~/.config/zsh/plugins/zsh-syntax-highlighting" "~/.config/zsh/plugins/zsh-abbrev-alias" "~/.config/zsh/plugins/zsh-autopair" "/nix/store/1rx6bbd0fcw7h0shz1drrhza1flpvh0w-emacs-26.3/libexec/emacs/26.3/x86_64-pc-linux-gnu"))
 (config
  (envfile)
  (elc-files . 0)
  (modules :completion company (ivy +childframe +icons +prescient) :ui doom doom-dashboard fill-column hl-todo indent-guides modeline nav-flash ophints (popup +defaults +all) treemacs vc-gutter vi-tilde-fringe (window-select +switch-window) workspaces zen :editor (evil +everywhere) fold (format +onsave) parinfer snippets :emacs (dired +icons) electric ibuffer vc :term vterm :checkers syntax :tools direnv docker editorconfig (eval +overlay) lookup (lsp +peek) magit make upload :lang (cc +lsp) data (go +lsp) (org +brain +journal +pandoc +pomodoro) (python +lsp) :config (default +bindings +smartparens))
  (packages (exec-path-from-shell) (meson-mode) (bitbake))
  (unpin "n/a")
  (elpa "vterm")))
</pre></details>

**Comment by oguzserbetci** [comment]
You should try using `C-j` and `C-k` (`ctrl+j/k`). These are the emacs navigations which you can use most of the time when there is input expected but navigation is possible.

**Comment by hlissner** [comment]
> Using hjkl results in the childframe closing itself. I think it would be better for consistency (and people who simply disables the arrow keys) if Doom had more Vim-like keybindings for reference lookup.

It sounds like you're referring to the childframe as if it were in normal mode, but the childframe is displaying an ivy prompt, where evil is not available. Rebinding h, j, k or l would mean the user couldn't type those characters into the prompt (which is not desirable). 

Instead, as suggested, `C-j` and `C-k` is what you want.

**Comment by Yumasi** [comment]
Didn't know it was an ivy prompt. Sadly, Using `C-j` and `C-k` does not work for me. Those shortcuts works with every ivy prompt I encounter except this one. When looking up references, it instead uses the actions bound to those shortcuts in evil's normal-mode.
