### ISSUE TITLE
How to perform a project search for a symbol for certain file types?

### ISSUE THREAD

**Issue by whjiang** [hlissner/doom-emacs#2849]
When pressing `SPC *`, I can make a search for current symbol in project very easily. This is great. However, how can I narrow down the search to a specific file type list? E.g. I want to search for a symbol declaration in .h file, but the search result contains many usages of this symbol in .cpp file. How can I narrow down the search to only .h file?

**Comment by hlissner** [comment]
Add `-- -t h` or `-- -g '*.h'` to the end of your search query. Arguments after a `--` delimiter are passed directly to `rg`. You can run `rg --type-list` to see what types (for `-t`) it supports.

-----

On a separate note: you have consistently ignored the issue templates in your issues, and disregarded requests to include your `M-x doom/info`.

**Please include your `M-x doom/info` in _every_ issue you create.**
