### ISSUE TITLE
Font is always bold if bold variant is installed

### ISSUE THREAD

**Issue by bersace** [hlissner/doom-emacs#2850]
**What did you expect to happen?**

I expect Doom Emacs to have normal and bold fonts.

**What actually happened?**

Everything in Doom Emacs is bold.

**Additional details:**

- My doom dir : https://gitlab.com/bersace/dotfiles/-/tree/master/files/.config/doom
- Screenshot : ![image](https://user-images.githubusercontent.com/542613/78795753-a7d4bd00-79b5-11ea-92af-6fe9de77f575.png)
- No warnings in `*Messages*`.
- Output of `fc-list`
  ``` console
  $ fc-list | grep -i jetbrainsmono-
  /home/bersace/.local/share/fonts/JetBrainsMono-Bold.ttf: JetBrains Mono:style=Bold
  /home/bersace/.local/share/fonts/JetBrainsMono-Regular.ttf: JetBrains Mono:style=Regular
  $
  ```
- My fontconfig:
``` xml
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
  <alias>
    <family>JetBrains Mono</family>
    <prefer>
      <family>icons-in-terminal</family>
    </prefer>
  </alias>
  <alias>
    <family>JetBrainsMono Nerd Font</family>
    <prefer>
      <family>icons-in-terminal</family>
    </prefer>
  </alias>
</fontconfig>
```
- This is how doom emacs look **before**:
  ![image](https://user-images.githubusercontent.com/542613/78796800-19613b00-79b7-11ea-92e5-4c7a7308e1ed.png)

I installed both Regular and Bold styles for Alacritty. I hit this bug once I installed Bold variant.

**Steps to reproduce:**
1. Install Bold and Regular variant of JetBrains Mono.
2. Setup console font with gnome-tweak-tools
3. Start Doom Emacs.

**System information:**
<details><pre>
Loading /etc/emacs/site-start.d/00debian.el (source)...
Loading /etc/emacs/site-start.d/50autoconf.el (source)...
Loading /etc/emacs/site-start.d/50cmake-data.el (source)...
Loading /etc/emacs/site-start.d/50dictionaries-common.el (source)...
Loading debian-ispell...
Loading /var/cache/dictionaries-common/emacsen-ispell-default.el (source)...
Loading /var/cache/dictionaries-common/emacsen-ispell-dicts.el (source)...
((emacs
  (version . "26.1")
  (features . "XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 THREADS LIBSYSTEMD LCMS2")
  (build . "sept. 23, 2019")
  (buildopts "--build x86_64-linux-gnu --prefix=/usr --sharedstatedir=/var/lib --libexecdir=/usr/lib --localstatedir=/var/lib --infodir=/usr/share/info --mandir=/usr/share/man --enable-libsystemd --with-pop=yes --enable-locallisppath=/etc/emacs:/usr/local/share/emacs/26.1/site-lisp:/usr/local/share/emacs/site-lisp:/usr/share/emacs/26.1/site-lisp:/usr/share/emacs/site-lisp --with-sound=alsa --without-gconf --with-mailutils --build x86_64-linux-gnu --prefix=/usr --sharedstatedir=/var/lib --libexecdir=/usr/lib --localstatedir=/var/lib --infodir=/usr/share/info --mandir=/usr/share/man --enable-libsystemd --with-pop=yes --enable-locallisppath=/etc/emacs:/usr/local/share/emacs/26.1/site-lisp:/usr/local/share/emacs/site-lisp:/usr/share/emacs/26.1/site-lisp:/usr/share/emacs/site-lisp --with-sound=alsa --without-gconf --with-mailutils --with-x=yes --with-x-toolkit=gtk3 --with-toolkit-scroll-bars 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/emacs-StqULU/emacs-26.1+1=. -fstack-protector-strong -Wformat -Werror=format-security -Wall' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' LDFLAGS=-Wl,-z,relro")
  (windowsys . batch)
  (daemonp))
 (doom
  (version . "2.0.9")
  (build . "HEAD, origin/develop, origin/HEAD 8d7751871 2020-04-08 04:15:16 -0400")
  (dir . "~/.config/doom/"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/bin/bash")
  (uname . "Linux 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64")
  (path "~/.gem/ruby/2.3.0/bin" "~/.poetry/bin" "~/.cache/pyenv/shims" "~/.cache/pyenv/bin" "~/.cache/gopath/bin" "~/.local/bin" "/usr/local/sbin" "/usr/local/bin" "/usr/sbin" "/usr/bin" "/sbin" "/bin" "/usr/local/games" "/usr/games" "/usr/lib/emacs/26.1/x86_64-linux-gnu"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard fill-column hl-todo indent-guides modeline nav-flash ophints (popup +all +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces zen :editor (evil +bindings +everywhere) fold multiple-cursors rotate-text snippets :emacs dired electric vc :checkers spell syntax :tools ansible direnv docker editorconfig (eval +overlay) (lookup +docsets +dictionnary) lsp magit :lang (cc +lsp) data emacs-lisp go (java +meghanada) (javascript +lsp) markdown org php (python +pyenv) rst sh web :config (default +bindings +smartparens))
  (packages "n/a")
  (unpin "n/a")
  (elpa "n/a")))
</pre></details>

Doom Emacs is awesome.

**Comment by hlissner** [comment]
This appears to be a fontconfig defaults issue and can't be "fixed" on the Emacs side of things. To fix it from Doom, you must explicitly tell Emacs what weight of the font to use by setting `doom-font`:

```lisp
;; in ~/.doom.d/config.el
(setq doom-font (font-spec :family "JetBrains Mono" :weight 'normal))
;; change `normal` to `semi-light` or `ultra-light`
```

Otherwise, the fix lies in aliasing `monospace` to the normal weight of jetbrainsmono in your fontconfig. Or fixing the ordering of their mappings in icon-in-terminal's fontconfig files.

**Comment by bersace** [comment]
I tried myself to set doom font with `(font-spec :family "JetBrains Mono" :weight "normal"))`. Thanks for pointing the right `(font-spec)`. Closing.
