### ISSUE TITLE
Possibility to have the .doom folder in `.config` folder

### ISSUE THREAD

**Issue by C0DK** [hlissner/doom-emacs#2858]
I am cleaning up in my home directory, and would love to have the emacs and doom config files, in the relevant `~/.config` folder that most modern linux distros use.
I might be wrong, but this will movement will comform better with the
**Describe the feature**
- Possibility to move `~/.doom/` to `~/.config/doom/` 

**System information**
Linux 4.19.114-1-MANJARO

**Comment by dinkonin** [comment]
This is already supported.
[https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#configure](url)

Also you can move your .emacs.d if you have Emacs27+

**Comment by C0DK** [comment]
Thanks sorry!
