### ISSUE TITLE
How do I prevent messages from showing in the minibuffer?

### ISSUE THREAD

**Issue by mindlike** [hlissner/doom-emacs#2878]
I couldn't see any channels after logging into Discord, so posting here instead.

**What are you trying to achieve?**

The minibuffer frequently displays the message "Garbage collecting...done
(0.145s)", most annoyingly on top of ivy, where it breaks my flow. 

I'd like to inhibit all messages while ivy is using the minibuffer. Also, it
would be nice to inhibit some messages permanently (like the GC one). 

**What have you tried?**

I've read about `inhibit-message`, [which apparently is used in
ivy](https://github.com/abo-abo/swiper/issues/1285). However, I'm still seeing the GC message... 

I've also looked into the GC setup to see if I could make it more rare. I'm
hesitant to tweak those settings, since being on EXWM means my whole system
stutters if the GC is configured poorly (it's currently fine). 

**System information**
<details><pre>
<details>
```
emacs   version    27.0.50
        features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GSETTINGS GLIB NOTIFY INOTIFY GNUTLS LIBXML2 FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LCMS2 GMP
        build      Jul 08, 2019
        buildopts  (--with-modules)
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> dan-dev, mindlike/dan-dev dd8d24842 2020-04-10 01:49:01 -0700
        dir        ~/.doom.d/
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/bash
        uname      Linux 5.3.0-45-generic #37~18.04.1-Ubuntu SMP Fri Mar 27 15:58:10 UTC 2020 x86_64
        path       (~/.nix-profile/bin ~/.guix-profile/bin ~/.nix-profile/bin ~/.guix-profile/bin /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /usr/games /usr/local/games /snap/bin /usr/local/libexec/emacs/27.0.50/x86_64-pc-linux-gnu/)
config  envfile    envvar-file
        elc-files  0
        modules    (:desktop exwm :completion (company +childframe) (ivy +prescient) :ui doom doom-dashboard hl-todo modeline nav-flash ophints vc-gutter zen :editor file-templates fold lispy multiple-cursors snippets word-wrap :emacs dired electric vc :term eshell :checkers syntax :tools direnv (eval +overlay) lookup (magit +forge) pass pdf :lang data emacs-lisp (haskell +dante) julia markdown (org +journal +hugo +jupyter) sh :app calendar :config literate (default +bindings +smartparens))
        packages   ((aggressive-indent) (ace-window) (key-chord) (helpful) (phi-search) (undo-tree) (dired-narrow) (deadgrep) (dmenu) (company-posframe) (org-noter) (org-roam :recipe (:host github :repo jethrokuan/org-roam)) (company-org-roam :recipe (:host github :repo jethrokuan/company-org-roam)) (smartscan) (flx) (org-ref) (google-this) (wrap-region) (edit-server) (slack))
        unpin      (n/a)
        elpa       (n/a)
```
</details>
</pre></details>

**Comment by hlissner** [comment]
> I couldn't see any channels after logging into Discord, so posting here instead.

You should see a `#readme` channel.

![image](https://user-images.githubusercontent.com/510883/79038558-2ee98700-7ba8-11ea-89dd-896f3f120522.png)

Click it, scroll to the top, then read it. It will tell you how to get into the server.

> The minibuffer frequently displays the message "Garbage collecting...done
> (0.145s)", most annoyingly on top of ivy, where it breaks my flow.

This is not normal behavior. It sounds like you have debug mode enabled. `SPC h d d` (or `C-h d d`) will toggle it. When it is enabled, the garbage collector becomes verbose (among other things).

Some possible reasons why it is enabled:

1. You have the `DEBUG` environment variable set.
2. You started Emacs with the `--debug` or `--debug-init` switches.
3. You accidentally turned it on via the keyboard shortcut and forgot to turn it off.
4. You have enabled `garbage-collection-messages` in your config.

**Comment by mindlike** [comment]
Ah, I forgot I launch doom with `-d`. Thanks!!
