### ISSUE TITLE
org-tag-column setting is ignored

### ISSUE THREAD

**Issue by deshmukhs** [hlissner/doom-emacs#2879]
In my `~/.doom.d/init.el`, there is:

```
(custom-set-variables
 '(doom-modeline-enable-word-count t)
 '(org-tags-column -80))

```
So, when I go to a heading and press` SPC u C-C C-C`, (`org-align-tags`) I expect tags to get right aligned at 80th column for the entire buffer.

But all tags are left aligned instead.

Other settings in the `~/.doom.d/init.el` like  `doom-modeline-enable-word-count t` are respected.

**Steps to reproduce:**
1. Customize org-tags-column and set it to -80
2. Create a heading in an org file and assign some tags
3. SPC u C-C C-C right aligns all tags at the 80th column as expected
4. Save all and restart Doom Emacs
5. Create a heading in an org file and assign some tags
6. SPC u C-c C-c
7. All tags are left aligned

**System information:**
<details><pre>
<details>

```
emacs   version    26.3
        features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2
        build      Aug 30, 2019
        buildopts  (--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-modules 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now)
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      fatal: not a git repository (or any of the parent directories): .git
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/zsh
        uname      Linux 5.4.30-1-MANJARO #1 SMP PREEMPT Thu Apr 2 17:31:45 UTC 2020 x86_64
        path       (~/.local/bin/ /usr/local/bin/ /usr/local/sbin/ /usr/bin/ /usr/lib/jvm/default/bin/ /usr/bin/site_perl/ /usr/bin/vendor_perl/ /usr/bin/core_perl/ /var/lib/snapd/snap/bin/ ~/texlive/2019/bin/x86_64-linux/ /usr/lib/emacs/26.3/x86_64-pc-linux-gnu/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold multiple-cursors rotate-text snippets :emacs dired electric ibuffer vc :tools (eval +overlay) flycheck (lookup +docsets) magit :lang data emacs-lisp latex markdown (org +dragndrop +ipython +pandoc +present) php sh :config (default +bindings +smartparens))
        packages   (org-transform-tree-table)
        elpa       (n/a)
```
</details></pre></details>

**Comment by peterhoeg** [comment]
I'm doing `(setq org-tags-column -80)` which works fine here.

**Comment by hlissner** [comment]
`customize-set-variables` is not the correct way to set variables in Doom. Use:

```lisp
(after! org
  (setq org-tags-column -80))
```

With the exception of file/directory variables, configuration should generally be done in an `after!` block for that package.

**Comment by deshmukhs** [comment]
> `customize-set-variables` is not the correct way to set variables in Doom. Use:
> 
> ```lisp
> (after! org
>   (setq org-tags-column -80))
> ```
> 
> With the exception of file/directory variables, configuration should generally be done in an `after!` block for that package. If a setting works without an `after!`, it's a happy accident, but could change in the future.

That worked perfectly. Is there a Doom parallel for `customize-set-variables` or do we have to set variables up manually by editing `init.el` by hand?

**Comment by hlissner** [comment]
> That worked perfectly. Is there a Doom parallel for customize-set-variables or do we have to set variables up manually by editing init.el by hand?

You have to set them yourself in config.el (not init.el), either with `setq` or `setq!` (the latter triggers setters). See https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#configuring-doom
