### ISSUE TITLE
Compilation errors (less-css-mode, ox-reveal, dante)

### ISSUE THREAD

**Issue by AloisJanicek** [hlissner/doom-emacs#288]
I was tired and I didn't noticed them when we talked yesterday in #285 .  
I am using up to date develop branch of Doom Emacs here.  
First `dante` error:

```Ignored modules/lang/haskell/packages.el
Warning (emacs): haskell-mode: couldn’t find ghc-mode
Compiled modules/lang/haskell/config.el
Compiled modules/lang/haskell/+intero.el
Cannot load dante: (file-error "Cannot open load file" "Not a directory" "dante")
Compiled modules/lang/haskell/+dante.el
Cannot open load file: Not a directory, dante
make: *** [Makefile:39: compile] Error 255
```
Compilation stops. When I comment out haskell line in `.init.el`, I can continue and I got another 255, this time `ox-reveal`:  

```Ignored modules/lang/org/packages.el
‘when-let’ is an obsolete macro (as of 26.1); use ‘when-let*’ instead.
Compiled modules/lang/org/config.el
Cannot load ox-reveal: (file-error "Cannot open load file" "Not a directory" "ox-reveal")
Cannot load org-tree-slide: (file-error "Cannot open load file" "Not a directory" "org-tree-slide")
Cannot load centered-window-mode: (file-error "Cannot open load file" "Not a directory" "centered-window-mode")
Compiled modules/lang/org/+present.el
Cannot open load file: Not a directory, ox-reveal
make: *** [Makefile:39: compile] Error 255
```

In this case helps only commenting out whole org module list in `init.el`. But it doesn't ends. I got another 255, this time in `rss/config.el` (?):  
```
Ignored modules/app/email/packages.el
Cannot load mu4e: (file-error "Cannot open load file" "Not a directory" "mu4e")
Cannot load mu4e-maildirs-extension: (file-error "Cannot open load file" "Not a directory" "mu4e")
Cannot load org-mu4e: (file-error "Cannot open load file" "Not a directory" "org-mu4e")
Compiled modules/app/email/config.el
Compiled modules/app/email/autoload/evil.el
Compiled modules/app/email/autoload/email.el
Ignored modules/app/irc/packages.el

In toplevel form:
../modules/app/irc/config.el:89:10:Warning: ‘when-let’ is an obsolete macro
    (as of 26.1); use ‘when-let*’ instead.
Compiled modules/app/irc/config.el
Compiled modules/app/irc/autoload/irc.el
Ignored modules/app/rss/packages.el
Error (use-package): elfeed-org/:config: Symbol’s value as variable is void: +org-dir
Compiled modules/app/rss/config.el
Symbol’s value as variable is void: +org-dir
make: *** [Makefile:39: compile] Error 255
```
after commenting out `app/rss`, compilations successfully ends with:
```
Compiled 158/158 file(s) (77 ignored)
```

Additionally, if I execute just `make`, I got:
```
Finished generating autoloads.el!
less-css-mode package is not installed
make: *** [Makefile:27: autoremove] Error 255
```
but make install returns `No packages to install!`.

make doctor output is exactly the same as I posted in #285

**Comment by AloisJanicek** [comment]
After recent commits, errors with `dante` and `ox-reveal` are gone.  
`less-css-mode` error after executing `make` is still present.  
And there is new (?) one in `app/irc` or in `private/hlissner`:

```
Compiled modules/lang/web/autoload/css.el
Ignored modules/app/email/packages.el
Cannot load mu4e: (file-error "Cannot open load file" "Not a directory" "mu4e")
Cannot load mu4e-maildirs-extension: (file-error "Cannot open load file" "Not a directory" "mu4e")
Cannot load org-mu4e: (file-error "Cannot open load file" "Not a directory" "org-mu4e")
Compiled modules/app/email/config.el
Compiled modules/app/email/autoload/evil.el
Compiled modules/app/email/autoload/email.el
Ignored modules/app/irc/packages.el
Cannot load circe: (error "Couldn’t find entry: irc/snoonet.org")
Compiled modules/app/irc/config.el
Compiled modules/app/irc/autoload/irc.el
Ignored modules/app/rss/packages.el
Compiled modules/app/rss/config.el

In +rss-popup-pane:
../../app/rss/autoload.el:39:4:Warning: doom-popup-buffer called with 11
    arguments, but accepts only 1-3
Compiled modules/app/rss/autoload.el
Ignored modules/app/twitter/packages.el
Compiled modules/app/twitter/config.el
Compiled modules/app/twitter/autoload.el
Compiled modules/app/write/autoload.el

In toplevel form:
../../private/hlissner/init.el:16:8:Warning: ‘system-name’ is an obsolete
    variable (as of 25.1); use (system-name) instead
Compiled modules/private/hlissner/init.el
Compiled modules/private/hlissner/config.el
Couldn’t find entry: irc/snoonet.org
make: *** [Makefile:39: compile] Error 255
```

Anyway, I don't use IRC in emacs, so I can disable it and successfully compile doom-emacs from develop.

**Comment by hlissner** [comment]
I'm still not sure what could be causing your less-css-mode error. You could try looking into `~/.emacs.d/.local/@HOSTNAME/etc/custom.el` and removing less-css-mode from the `package-selected-packages` variable there. It's possible that Emacs _thinks_ the package is installed, but isn't.

This is likely the result of all the make-gymnastics we've been doing throughout this issue! I'm afraid Doom's integration with package.el isn't as solid as I had hoped.

(That said, I've been working on replacing package.el with [straight.el](https://github.com/raxod502/straight.el). It won't be ready until 2.1, but it will fix all these package management and certificate woes that have haunted Doom for the past year, including this one. I'm so glad he wrote it, because I was going to if he wasn't!)

**Comment by AloisJanicek** [comment]
I don't have `custom.el` file there:  
```
+ ~ $ ls .emacs.d/.local/@aj-tpe/etc/
bookmarks  meghanada-server  recentf  scratch  workspaces
```   
And I remember that I was doing multiple clean installs of doom-emacs before submitting this issue, so I think that this is not result of executing those different make commands all over again.

I will do another clean install from develop and post exact sequence of commands I executed so you can be sure in case that error prevails.

**Comment by AloisJanicek** [comment]
Here are commands I just executed:  
```
rm -rf .emacs.d/
git clone https://github.com/hlissner/doom-emacs ~/.emacs.d
cd .emacs.d/
git checkout remotes/origin/develop
git checkout -b develop 
git pull
git branch --set-upstream-to=origin/develop develop
git pull
cp init.example.el init.el
vim init.el
make install
make update
make install
make compile
make # <-- results in "less-css-mode" error
```

I also attaching whole output log of those commands and fresh `make doctor` output.

[doom-log.txt](https://github.com/hlissner/doom-emacs/files/1556371/doom-log.txt)

```
+ ~/.emacs.d (develop) $ DEBUG=1 make doctor
DOOM Doctor
Running Emacs v26.0.90, commit 4560fe7163e1ff16944a70e6351c25ad2e3d3098

Compiled with:
  XPM JPEG TIFF GIF PNG RSVG SOUND DBUS NOTIFY ACL GNUTLS LIBXML2
  FREETYPE LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES XWIDGETS
  LIBSYSTEMD LCMS2
uname -a:
  Linux aj-tpe 4.14.4-1-ARCH #1 SMP PREEMPT Tue Dec 5 19:10:06 UTC 2017
  x86_64 GNU/Linux

Attempt to load DOOM: success! Loaded v2.0.7
Revision 4560fe7163e1ff16944a70e6351c25ad2e3d3098

----

test-emacs
test-windows
test-fonts
Found font material-design-icons.ttf
Found font weathericons.ttf
Found font octicons.ttf
Found font fontawesome.ttf
Found font file-icons.ttf
Found font all-the-icons.ttf
test-gnutls
test-tls
peculiar error
make: *** [Makefile:80: doctor] Error 255

```

**Comment by hlissner** [comment]
Finally tracked that pesky less-css-mode error down!  less-css-mode is included with Emacs.

`make autoremove` does a search for packages whose backend has changed (from package.el to QUELPA, or vice versa) and didn't know how to classify a built-in package, causing it to think the package wasn't installed at all.

Anyhow, the fix is now in `develop`. I'll keep this open until it hits `master`.

**Comment by AloisJanicek** [comment]
Nice work, I don't get that error message anymore.

**Comment by hlissner** [comment]
Alright, it's in master now. Feel free to reopen this if the issue resurfaces.
