### ISSUE TITLE
`+org/dwim-at-point` does not recognize a link in keyword context

### ISSUE THREAD

**Issue by brabalan** [hlissner/doom-emacs#2880]
I have this at the beginning of a file:
``` org
#+TITLE: Org-roam Documentation
#+ROAM_KEY: https://org-roam.readthedocs.io/en/master/
```

When I put the cursor on the link and hit `return`, nothing happens.

**What did you expect to happen?**
I would follow the link.

**What actually happened?**
Nothing.

**Additional details:**
The problem is here: https://github.com/hlissner/doom-emacs/blob/develop/modules/lang/org/autoload/org.el#L226. At his point, the context type is `keyword`, so this case is not entered. I looked at how `org-return` works when `org-return-follows-link` is set (in orgmode `org.el` around line 21082), and this is how they determine it's a link:
``` emacs-lisp
     ((and org-return-follows-link
	   (or (org-in-regexp org-ts-regexp-both nil t)
	       (org-in-regexp org-tsr-regexp-both nil  t)
	       (org-in-regexp org-any-link-re nil t)))
      (call-interactively #'org-open-at-point))
```

Could this be integrated in `+org/dwim-at-point` (maybe only in a `keyword` case…)?

**Comment by hlissner** [comment]
As of da427a1 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by brabalan** [comment]
It works great now, thanks!
