### ISSUE TITLE
Working directory changes when opening a new file within a project

### ISSUE THREAD

**Issue by rsheasby** [hlissner/doom-emacs#2886]
**What did you expect to happen?**
When opening a file within the current project using `SPC SPC`, the working directory should stay the same.

**What actually happened?**
It changes to the git root instead of the set working directory.

**Additional details:**
My config can be found at https://github.com/rsheasby/dotfiles/tree/master/doom-emacs
Video of behaviour here:
https://youtu.be/6_PGY5fWHPA

**System information:**
<details><pre>
emacs   version    27.0.50
        features   NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS JSON PDUMPER LCMS2 GMP
        build      Nov 26, 2019
        buildopts  (--prefix=/opt/local --without-dbus --without-gconf --without-libotf --without-m17n-flt --without-gpm --with-gnutls --with-xml2 --with-modules --infodir /opt/local/share/info/emacs --with-json --without-harfbuzz --with-ns --with-lcms2 'CFLAGS=-pipe -Os -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -arch x86_64' 'CPPFLAGS=-I/opt/local/include -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk' 'LDFLAGS=-L/opt/local/lib -Wl,-headerpad_max_install_names -Wl,-no_pie -Wl,-syslibroot,/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -arch x86_64')
        windowsys  ns
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop, origin/develop, origin/HEAD 24e35b95d 2020-04-10 02:04:00 -0400
        dir        ~/Documents/dotfiles/doom-emacs/
system  type       darwin
        config     x86_64-apple-darwin19.0.0
        shell      /usr/local/bin/fish
        uname      Darwin 19.3.0 Darwin Kernel Version 19.3.0: Fri Jan 10 21:15:49 PST 2020; root:xnu-6153.81.5~4/RELEASE_X86_64 x86_64
        path       (/opt/local/sbin /opt/local/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /usr/local/go/bin /Applications/MacPorts/Emacs.app/Contents/MacOS ~/go/bin/ /Applications/MacPorts/Emacs.app/Contents/MacOS/libexec/ ~/go/bin)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo indent-guides modeline nav-flash ophints (popup +defaults) pretty-code tabs treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold snippets :emacs dired electric vc :checkers syntax :tools (eval +overlay) lookup lsp magit :lang data emacs-lisp (go +lsp) javascript markdown org rest sh web :config (default +bindings +smartparens))
        packages   ((inertial-scroll :recipe (:host github :repo kiwanami/emacs-inertial-scroll)) (centaur-tabs))
        unpin      (n/a)
        elpa       (n/a)
</pre></details>

**Comment by rsheasby** [comment]
For clarity, the reason this is an issue is because it's affecting my use of go modules, as (go +lsp) only works correctly when the working directory contains the go.mod.

**Comment by rsheasby** [comment]
I was able to fix this using the snippet in #1974 to add `go.mod` to the list of recognized project root markers. This still seems like a hack though. Is it intended functionality for projectile to re-evaluate its project root every time you switch file, even after explicitly setting a specific directory as the project root?

**Comment by hlissner** [comment]
Projectile and `+ivy/projectile-find-file` (on `SPC SPC`) are acting as intended; they search for a file from what projectile believes to be the project's root.

It determines the project's root by [following these steps](https://github.com/hlissner/doom-emacs/blob/develop/core/core-projects.el#L46-L62). If it doesn't determine the correct root, you must either:

a. Modify `projectile-project-root-files-bottom-up`, `projectile-root-files`, or `projectile-root-top-down-recurring`, or:
b. Place a `.project` file in the correct directory.

In your case, `(add-to-list 'projectile-root-files "go.mod")` would work. Unless you want it to have priority over `.git`/`.project`, in which case use `(add-to-list 'projectile-project-root-files-bottom-up "go.mod")`.

**Comment by rsheasby** [comment]
Alright cool, thanks. Good to know.
