### ISSUE TITLE
Reconsider running the private module of the current user by default

### ISSUE THREAD

**Issue by UndeadKernel** [hlissner/doom-emacs#289]
Hi Henrik. Have you considered removing the default behavior of running the configuration of the current user even when it is not stated in the ":private" section of the init.el?

I have found that this behavior is confusing and gives problems when testing other private configurations. Picture the following scenario: I already have a private configuration. I decide that I want to test your private configuration (to play around with your bindings, for example). So I change the line:
`:private my-user`
to
`:private hlissner`

This would end up loading my configuration and your configuration at the same time, making a mess with all the bindings, font configurations and theme changes among many other things.

What do you think of this?

**Comment by AloisJanicek** [comment]
Good news, this is already implemented in develop, see https://github.com/hlissner/doom-emacs/commit/346d7bdf360f1d0a66504de721d7a1fb75f148d2 . You must explicitly state `:private my-user` to load corresponding module.

**Comment by UndeadKernel** [comment]
Before posting the issue, I checked `core/core-packages.el` of the master branch. I forgot to check the debug branch to see if the problem was still there :D

**Comment by hlissner** [comment]
You are quite right! It was also too magical for my taste, so it's been removed in develop, and should be merged into master any day now (just doing my final rounds). I'll leave this open until it has.

**Comment by Ptival** [comment]
Hey @hlissner , it seems the feature is removed in master, but init.example.el still has a comment suggesting that the feature is still present. You should consider removing it, if it's not already done in the develop branch!

**Comment by hlissner** [comment]
@Ptival Good timing! I was _just_ about to fix that. That comment has now been removed.

@UndeadKernel Thank you for the kind words, and you're very welcome! Doom has been an awesome ride, no small part owed to the awesome people like yourself that have helped me figure things out!
