### ISSUE TITLE
Defer `tty-run-terminal-initialization` for all terminal windows

### ISSUE THREAD

**Issue by JacksonGariety** [hlissner/doom-emacs#2894]
Currently, we improve the startup time of emacs (daemon) with `(advice-add #'tty-run-terminal-initialization :override #'ignore)`. This advice is removed on `window-setup-hook`.

But `tty-run-terminal-initialization` is also run after calling `emacsclient -nw`.

Is it possible to defer `tty-run-terminal-initialization` until after text appears on the screen? That way emacsclient can show us _something_ (i.e. at least the mode-line) while it's working on fontification. It makes no sense to clear the screen, fontify, and then draw text.

Browsers do it correctly. When you click a link, the current page hangs around until the new page is ready, and then as much as possible of the new page is displayed even if some assets (e.g. large images) aren't ready yet.

**Comment by hlissner** [comment]
I actually intend to disable that advice for daemon sessions (there's no need for it there, since the startup cost is front-loaded).

For the time being you can add this to `~/.doom.d/config.el`:

```lisp
(when (daemonp) 
  (advice-remove #'tty-run-terminal-initialization #'ignore))
```

**Comment by JacksonGariety** [comment]
@hlissner wait, can we defer the function on new terminal frames?

**Comment by hlissner** [comment]
Possibly with something like

```elisp
(add-transient-hook! 'server-after-make-frame-hook
  (unless (display-graphic-p)
    (tty-run-terminal-initialization (selected-frame) nil t)))
```

Though, I don't think it's needed. Isn't all that init work done when the daemon is started?

**Comment by JacksonGariety** [comment]
The work is done every time a new frame is made. See: https://github.com/emacs-mirror/emacs/blob/d0e2a341dd9a9a365fd311748df024ecb25b70ec/admin/notes/multi-tty#L332
