### ISSUE TITLE
Projectile not finding any files

### ISSUE THREAD

**Issue by Aetiuss** [hlissner/doom-emacs#2897]
Hello!

**I noticed that projectile couldn't find any files after I'm opening a folder**

**While SPC + . is working perfectly, after I open a project with `SPC p p`  or `SPC f p`, the minibuff for finding files comes up but there is not any file/folder in it**

**Additional details:**
- I'm on windows and I tried different indexing method like alien or hybrid but no results

Here are the warnings of my doom doctor output
<details><pre>
 > Checking your enabled modules...
    > [1m:lang go[0m
      [33m! Couldn't find gocode. Code completion won't work[0m
      [33m! Couldn't find gomodifytags. Manipulating struct tags will not work[0m
      [33m! Couldn't find gotests. Generating tests will not work[0m
      [33m! Couldn't find gore. REPL will not work[0m
      [33m! Couldn't find guru. Refactoring commands (go-guru-*) won't work[0m
    > [1m:lang markdown[0m
      [33m! Couldn't find a markdown compiler, `markdown-preview' won't work[0m
  [31mx org is not installed[0m
    > [1m:lang python[0m
      [33m! Couldn't find black. Code formatting will not work.[0m
      [33m! Couldn't find pyflakes. Import management will not work.[0m
      [33m! Couldn't find isort. Import sorting will not work.[0m
      [33m! Couldn't find pipenv. pipenv support will not work.[0m
      [33m! Couldn't find nosetests. Running tests through nose will not work.[0m
      [33m! Couldn't find pytest. Running tests through pytest will not work.[0m
      [33m! setuptools wasn't detected, which anaconda-mode requires[0m
    > [1m:lang sh[0m
      [33m! Couldn't find shellcheck. Shell script linting will not work[0m
</pre></details>

**Comment by hlissner** [comment]
No message at all? That's strange. Are you sure you have ripgrep installed?

**Comment by Aetiuss** [comment]
Thanks for the answer ! 

There is the prompt for finding files like that : 
![image](https://user-images.githubusercontent.com/44494858/79251594-a1948400-7e80-11ea-83bb-2ed158fd141b.png)

And yes ripgrep is indeed installed

**Comment by guraltsev** [comment]
I am having the same problem. In my personal config I had projectile working without problems with helm.

**Comment by guraltsev** [comment]
Actually, this seems to depend on the specific project. With some projects it works well. I will investigate.

**Comment by hlissner** [comment]
There was a bug that was fixed across https://github.com/hlissner/doom-emacs/commit/3202b68b01817cab3230d77ee549a850e524fb5c, https://github.com/hlissner/doom-emacs/commit/8532aa8dbe6b85738660afa13e7e3e934d9b48c5 and https://github.com/hlissner/doom-emacs/commit/681851dd85a2d3dbe821830be38ee0148f43eeff. Please update and let me know if it resolves your issues.

**Comment by altomcat** [comment]
It works for me after the update. Thanks

**Comment by guraltsev** [comment]
Actually, for me now the problem happens with all projects. In any project, `projectile-find-files` returns empty. I am under Windows using a native emacs. No errors get reported in the `message` buffer

**Comment by hlissner** [comment]
@guraltsev What is the value of `projectile-generic-command`. It should be set to a `fd`, `ripgrep` or `find` command, depending on what you have installed (ideally, you should have `fd` or `ripgrep` installed).

Try running the command you see in `M-x shell-command` and tell me what its output is.

**Comment by guraltsev** [comment]
The value for `projectile-generic-command` is 

```
projectile-generic-command is a variable defined in projectile.el.

Value
"rg -0 --files --color=never --hidden --glob '!c:/Users/guraltsev/config/common/emacs/.config/emacs/doom/.local/' --glob '!.idea' --glob '!.ensime_cache' --glob '!.eunit' --glob '!.git' --glob '!.hg' --glob '!.fslckout' --glob '!_FOSSIL_' --glob '!.bzr' --glob '!_darcs' --glob '!.tox' --glob '!.svn' --glob '!.stack-work'"

Original Value
"find . -type f -print0"
```

**Comment by guraltsev** [comment]
From `shell-command` the result is

```
(Shell command failed with code 5 and no output)
```

**Comment by guraltsev** [comment]
From `eshell` it is
```
"rg -0 --files --color=never --hidden --glob '!c:/Users/guraltsev/config/common/emacs/.config/emacs/doom/.local/' --glob '!.idea' --glob '!.ensime_cache' --glob '!.eunit' --glob '!.git' --glob '!.hg' --glob '!.fslckout' --glob '!_FOSSIL_' --glob '!.bzr' --glob '!_darcs' --glob '!.tox' --glob '!.svn' --glob '!.stack-work'"
```

**Comment by guraltsev** [comment]
So it seems that under windows the problem is that `rg` parameters should be quoted with `"` and not `'`. This snippet to be placed in `config.el`, courtesy of Henrik, solves the problem for now

```
(after! projectile
  (setq projectile-generic-command
        (mapconcat #'shell-quote-argument
                   (append (list "rg" "-0" "--files" "--follow" "--color=never" "--hidden")
                           (cl-loop for dir in projectile-globally-ignored-directories
                                    collect "--glob"
                                    collect (concat "!" dir))
                           )
                   " ")
        projectile-git-command projectile-generic-command))
```

**Comment by hlissner** [comment]
As of b51c4fc this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
