### ISSUE TITLE
Ivy and cousel not working.

### ISSUE THREAD

**Issue by samosaara** [hlissner/doom-emacs#290]
I did tried using helm and it works flawlessly over there. But on ivy I've even tried to reinstall twice to make sure I didn't mess up anything,  but (almost) all of the search related functions seems to be broken, all throwing errors like this: 

```Wrong type argument: comandp, counsel-[something]```

![Screenshot](https://i.imgur.com/kyr9VZ9.png)

All the commands on the log all just trowed the same error on the status bar. Like I said I even tried to reinstall to make sure it was not just a one off thing, but I've been able to successfully reproduce the bug:

```
git clone https://github.com/hlissner/doom-emacs ~/.emacs.d
cd ~/.emacs.d
cp init.example.el init.el
make install
```

The install log is [here](https://gist.github.com/samosaara/0e95a455691e729684394e82b108494d) I wasn't able to enable debug, it just vomits a huge error about missing packages which makes sense, it`s a fresh install after all.

I'm not experienced with Emacs nor lisp, but I also didn't change anything, it was broken out of the box. I'm on arch linux, emacs 25.3.1, doom 2.0.7. Sorry If this is a silly mistake of mine but I wasn't able to find anything related to my problem.

**Comment by samosaara** [comment]
Duplicate of #286

**Comment by AloisJanicek** [comment]
Some packages are not loading.  
Temporary fix would be to put
```
(require 'counsel)
(require 'avy)
```
into `config.el` in your private module.  
Information on private modules is on [wiki/Customization](https://github.com/hlissner/doom-emacs/wiki/Customization)

**Comment by samosaara** [comment]
Yeah I've been reading on the original issue and understood the problem. I use arch, so I'm used to living on the edge, I just decided to `git checkout -b develop`
