### ISSUE TITLE
blinking cursor for non-evil users

### ISSUE THREAD

**Issue by seanfarley** [hlissner/doom-emacs#2903]
This is more of a discussion about be412c8630043239e82f06f722f137483ff22d58. For non-evil users, should we really restore the blinking cursor? I assume for evil users, it only blinks when in insert mode but haven't verified.

**Comment by hlissner** [comment]
It blinks in all modes. I saw no compelling reason to change its default, so I leave it to the user to choose.

**Comment by seanfarley** [comment]
Ah, ok, I misunderstood. Although, I don't agree at all it's fine as a user choice :-)

**Comment by hlissner** [comment]
Some issues with blinking cursors surfaced in the past few days (see comments in 7a4ad7d), so back off it goes!

**Comment by seanfarley** [comment]
lol, fair enough
