### ISSUE TITLE
elm module work abnormal

### ISSUE THREAD

**Issue by chengyi** [hlissner/doom-emacs#2910]
**What did you expect to happen?**
...
company-elm & elm-flycheck work normally

**What actually happened?**
...
reports error

**Additional details:**

<details><pre>
Error from syntax checker elm: Wrong type argument: listp, (type . "error")
Company: An error occurred in auto-begin
Company: backend company-elm error "Args out of range: #<buffer buttons.elm>, 7, 7" with args (prefix)
eldoc error: (args-out-of-range buttons.elm 7 7)
Company: An error occurred in auto-begin
Company: backend company-elm error "Args out of range: #<buffer buttons.elm>, 7, 7" with args (prefix)
Company: An error occurred in auto-begin
Company: backend company-elm error "Args out of range: #<buffer buttons.elm>, 7, 7" with args (prefix)
eldoc error: (args-out-of-range buttons.elm 7 7)
Sole indentation [2 times]
Saving file /home/prow/Workspace/personal/imsui/src/buttons.elm...
Wrote /home/prow/Workspace/personal/imsui/src/buttons.elm
Error from syntax checker elm: Wrong type argument: listp, (type . "error")

</pre></details>

**Steps to reproduce:**
1. open a `elm` file

**System information:**
<details><pre>
<details>

```
emacs   version    26.3
        features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2
        build      8月 30, 2019
        buildopts  (--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-modules 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now)
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop, origin/develop 4b2ebcc70 2020-04-14 09:58:54 +0800
        dir        ~/.doom.d/
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /usr/bin/zsh
        uname      Linux 5.4.31-1-MANJARO #1 SMP PREEMPT Wed Apr 8 10:25:32 UTC 2020 x86_64
        path       (~/.local/bin /usr/local/bin /usr/bin /bin /usr/local/sbin /opt/android-ndk /opt/android-ndk /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /usr/lib/emacs/26.3/x86_64-pc-linux-gnu)
config  envfile    nil
        elc-files  0
        modules    (:completion company (ivy +fuzzy) :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor file-templates fold format snippets :emacs dired electric undo vc :term vterm :checkers syntax :tools (eval +overlay) (lookup +docsets) lsp magit :lang (cc +lsp) data elm emacs-lisp lua markdown (org +dragndrop +present) (python +lsp) (rust +lsp) (sh +zsh) :email mu4e :config (default +bindings +smartparens) :private prow-edit prow-c-c++ prow-misc gtags)
        packages   ((cnfonts) (jinja2-mode) (mu4e-maildirs-extension :disable t) (org-mu4e :disable t) (glsl-mode :disable t) (opencl-mode :disable t) (disaster :disable t) (cuda-mode :disable t) (demangle-mode :disable t))
        unpin      (n/a)
        elpa       (n/a)
```
</details>
</pre></details>

**Comment by hlissner** [comment]
Try adding `(package! elm-mode :pin "7782be0814")` to `~/.doom.d/packages.el`, then run `doom upgrade`.

**Comment by chengyi** [comment]
@hlissner I make it works. 
because `elm-flycheck` use elm, my filename is `buttons.elm`, but elm wants the filename to be `Buttons.elm`, otherwise elm reports error.
in `elm-mode` homepage, the author says it need to install `elm-language-server` to support completion when elm verison >= 0.19, i use 0.19.1, after I install lsp server, auto completion works.
maybe we should add `README.org` to `elm` module. :grin:
