### ISSUE TITLE
lsp-enable-links is breaking other buffers

### ISSUE THREAD

**Issue by jsravn** [hlissner/doom-emacs#2911]
**What did you expect to happen?**
lsp-enable-links should just link clickable things in the source.

**What actually happened?**
Random lines are being highlighted as links in ivy-buffer and treemacs. This is breaking both treemacs and ivy with various errors when I try to highlight/execute an affected line.

Here is an example of the ivy buffer:

![image](https://user-images.githubusercontent.com/522123/79461393-04575e00-7fee-11ea-9f6b-e1702541cdd2.png)

Treemacs looks similar.

Setting `lsp-enable-links` to `nil` seems to prevent the problem from happening.

**Additional details:**
- https://github.com/jsravn/dotfiles/tree/master/private_dot_config/doom

**System information:**
<details><pre>
emacs   version    27.0.90
        features   XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP
        build      Apr 07, 2020
        buildopts  (--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --mandir=/usr/share/man --with-gameuser=:games --with-sound=alsa --with-modules --without-gconf --without-gsettings --with-x-toolkit=gtk3 --without-xaw3d --without-m17n-flt --with-cairo --without-compress-install 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -g -flto -s -fuse-ld=gold' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now)
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop 10031153b 2020-04-16 03:37:19 -0400
        dir        ~/.config/doom/
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /usr/bin/zsh
        uname      Linux 5.6.3-arch1-1 #1 SMP PREEMPT Wed, 08 Apr 2020 07:47:16 +0000 x86_64
        path       (~/.pyenv/bin ~/.cargo/bin ~/.cabal/bin ~/.local/bin ~/go/bin ~/godev/bin ~/.emacs.d/bin /opt/google-cloud-sdk/bin /usr/local/sbin /usr/local/bin /usr/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /usr/lib/emacs/27.0.90/x86_64-pc-linux-gnu/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion (company +childframe) ivy :ui deft doom doom-dashboard hl-todo indent-guides (modeline +light) nav-flash ophints (popup +all +defaults) (pretty-code +pragmata-pro) treemacs vc-gutter vi-tilde-fringe window-select workspaces zen :editor (evil +everywhere) fold format multiple-cursors rotate-text snippets word-wrap :emacs dired electric vc :term vterm :checkers syntax spell :tools ansible docker editorconfig (eval +overlay) (lookup +docsets +dictionary) lsp magit make terraform :lang data emacs-lisp (go +lsp) (java +lsp) javascript markdown (org +dragndrop +journal +roam) (python +lsp +pyenv) (scala +lsp) sh :app calendar :config (default +bindings +smartparens))
        packages   ((magit-todos :disable t) (atomic-chrome) (org-roam :pin 4af4d2e4d5f18422fe0f90d5d83fe4c10ef1a20f))
        unpin      (n/a)
        elpa       (n/a)

</pre></details>

**Comment by hlissner** [comment]
I've disabled `lsp-enable-links` in bf65740 by default. However, I've also updated lsp in 2a93ff6. Please enable links after updating and see if this was resolved upstream.

If not, this should be reported upstream, because `lsp--document-links` is does not have the correct buffer focused when it applies those links.

**Comment by hlissner** [comment]
I've recently re-enabled `lsp-enable-links`. A cursory look over lsp's source suggests they've tackled this issue. Could you confirm?

**Comment by jsravn** [comment]
Seems to be working okay so far. Thanks for the update!
