### ISSUE TITLE
Document the change: private/{username} is no longer loaded by default

### ISSUE THREAD

**Issue by ruimams** [hlissner/doom-emacs#292]
346d7bdf360f1d0a66504de721d7a1fb75f148d2 made it so that `private/{user-login-name}` is no longer loaded by default. This change is now on `master` but there is still documentation describing the old behaviour.

As far as I could tell these are all the places that still describe the old behaviour:

- https://github.com/hlissner/doom-emacs/blob/8c4e6a267d8a61d917813eee714816347331c322/init.example.el#L133-L134
- https://github.com/hlissner/doom-emacs/wiki/Customization#load-your-private-module
- https://github.com/hlissner/doom-emacs/wiki/Modules

**Comment by hlissner** [comment]
Thanks for bringing these to my attention! The changes have been made.
