### ISSUE TITLE
Flycheck does not work in  js2 and javascript mode

### ISSUE THREAD

**Issue by Zenoe** [hlissner/doom-emacs#2928]
**What did you expect to happen?**
Flycheck work normally in js2 and javascript mode

**What actually happened?**
Flycheck does not work in  js2 and javascript mode
however, it do work in typescript mode

**Steps to reproduce:**
1. Open a  js file or a react js file, which clearly violates some of the eslint rules in javascript or js2 mode
2. Using "flycheck-next-error" to search error got "No more flycheck errors" prompt in the mini buffer.

**System information:**
<details><pre>
Package cl is deprecated
WARNING (:tools flycheck) module was moved to (:checkers syntax)
((emacs
  (version . "27.0.90")
  (features . "SOUND DBUS GSETTINGS GLIB NOTIFY INOTIFY GNUTLS LIBXML2 FREETYPE HARFBUZZ XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS PDUMPER GMP")
  (build . "Apr 11, 2020")
  (buildopts "--without-makeinfo --with-xpm=no --with-jpeg=no --with-png=no --with-gif=no --with-tiff=no")
  (windowsys . batch)
  (daemonp))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop 7615bacde 2020-04-11 00:35:07 -0400")
  (dir . "~/.doom.d/"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/usr/bin/zsh")
  (uname . "Linux 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64")
  (path "~/.nvm/versions/node/v10.16.3/bin" "~/perl5/bin" "~/perl5/bin" "/usr/local/sbin" "/usr/local/bin" "/usr/sbin" "/usr/bin" "~/bin" "/usr/local/go/bin" "~/go/bin"
 "/usr/local/maven3/bin" "/opt/gradle/latest/bin" "/opt/jdk1.8.0_181/bin" "/opt/jdk1.8.0_181/jre/bin" "~/.fzf/bin" "~/bin" "/usr/local/go/bin" "~/go/bin" "/usr/local/ma
ven3/bin" "/opt/gradle/latest/bin" "/opt/jdk1.8.0_181/bin" "/opt/jdk1.8.0_181/jre/bin" "/usr/local/libexec/emacs/27.0.90/x86_64-pc-linux-gnu"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company (helm +fuzzy) :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) vc-gutter vi-tilde-fringe windo
w-select workspaces :editor (evil +everywhere) file-templates fold multiple-cursors rotate-text snippets :emacs dired electric ibuffer vc :tools (eval +overlay) :checke
rs syntax :tools (lookup +docsets) magit :lang data emacs-lisp javascript markdown (org +dragndrop +present) sh :config (default +bindings +smartparens))
  (packages (xclip) (wgrep))
  (unpin "n/a")
  (elpa "n/a")))
</pre></details>

**Comment by hlissner** [comment]
With a `js2-mode` buffer open (we don't use `javascript-mode`), what does `M-x flycheck-verify-setup` say? It should list all the available checkers, with an explanation for ones that are disabled.

**Comment by Zenoe** [comment]
Thank you.
The **flycheck-verify-setup** tells me that I had missing or incorrect config file for eslint. 
After I regenerate .eslintrc.js file by running **npx eslint --init.** problem solved.
