### ISSUE TITLE
`use-package: Unrecognized keyword: :hook`

### ISSUE THREAD

**Issue by russmatney** [hlissner/doom-emacs#293]
I'm experiencing problems this morning with `:hook` when trying to update via `make`.

```bash
> make
Eager macro-expansion failure: (error "use-package: Unrecognized keyword: :hook")
Eager macro-expansion failure: (error "use-package: Unrecognized keyword: :hook")
Eager macro-expansion failure: (error "use-package: Unrecognized keyword: :hook")
Eager macro-expansion failure: (error "use-package: Unrecognized keyword: :hook")
Eager macro-expansion failure: (error "use-package: Unrecognized keyword: :hook")
Eager macro-expansion failure: (error "use-package: Unrecognized keyword: :hook")
Eager macro-expansion failure: (error "use-package: Unrecognized keyword: :hook")
Eager macro-expansion failure: (error "use-package: Unrecognized keyword: :hook")
use-package: Unrecognized keyword: :hook
make: *** [autoloads] Error 255
```

Reverting git to before the merge (`fd56896e`) as well as to before the hook-related commit (`2cbd1b91`) both allow `make` to run again. This leads me to think https://github.com/hlissner/doom-emacs/commit/9d81bc5a8b1be7ae03dd595cea2170dbb8edab2d is to blame.

Perhaps my local use-package needs to be updated, but can't be due to not yet having this feature? Anyway to deal with an incompatible update?

**Comment by russmatney** [comment]
Resolved! Just found https://github.com/hlissner/doom-emacs/issues/283.

Deleting my `.local/pacakges/elpa/use-package-*` and running `make` worked fine. Not sure if there's a better way to communicate hitting things like this, but i did have a months old use-package version.

**Comment by fdhenard** [comment]
this is happening for me.  I have version 2.3 from melpa-stable.  Isn't that the latest version?
