### ISSUE TITLE
clean install doom with error

### ISSUE THREAD

**Issue by cloudqq** [hlissner/doom-emacs#2930]
**What did you expect to happen?**
...

**What actually happened?**

clean install with error.
...

**Additional details:**
- Include a link to your private config
- Include screenshots/casts of your issue
- If you mention key sequences, include what commands they're bound to (use `SPC
  h k KEY` or `C-h h k KEY` to inspect keys).
- Include any warnings or errors logged to \*Messages\* (use `M-x
  view-echo-area-messages` to see it).

<details><pre>
If an error message is involved include a backtrace of it.

```
  ✓ (105/162) emacs-buttercup updated (b360e35 -> a91f282)
✓ Updated 6 package(s)
> (Re)building packages...
  → Building doom-modeline...
  → Building doom-modeline...done
  → Building yasnippet...
  → Building yasnippet...done
  → Building doom-snippets...
  → Building doom-snippets...done
  → Building dumb-jump...
  → Building dumb-jump...done
  → Building elisp-demos...
  → Building elisp-demos...done
  → Building buttercup...
  → Building buttercup...done
  ✓ Rebuilt 6 package(s)
> (Re)generating package autoloads...
  > Generating package autoloads...
  > Byte-compiling package autoloads file...
  ✓ Generated .local/autoloads.pkg.elc
✓ Done! Restart Emacs for changes to take effect.
✓ Finished! (80.3444s)
$ .emacs.d/bin/doom doctor
The doctor will see you now...

> Checking your Emacs version...
! Emacs 28.0.50 detected. Emacs HEAD is unstable and may cause errors.
> Checking for Emacs config conflicts...
> Checking for private config conflicts...
> Checking for stale elc files...
> Checking Doom Emacs...

Package cl is deprecated
evil-collection error: (file-missing Cannot open load file No such file or directory evil-collection)
  ✓ Initialized Doom Emacs 2.0.9
  ✓ Detected 32 modules
  ✓ Detected 127 packages
  > Checking Doom core for irregularities...
    ! Couldn't find the `fd' binary; project file searches will be slightly slower

evil-collection error: (file-missing Cannot open load file No such file or directory evil-collection)
evil-collection error: (file-missing Cannot open load file No such file or directory evil-collection)
evil-collection error: (file-missing Cannot open load file No such file or directory evil-collection)
! Attempt to load DOOM failed
  (Cannot open load file No such file or directory ./data/data-alltheicons.el)
```

There are 3 warnings!
✓ Finished! (1.9990s)
</pre></details>

**Steps to reproduce:**
install doom

**System information:**
<details><pre>
$ .emacs.d/bin/doom info
Package cl is deprecated
((emacs
  (version . "28.0.50")
  (features . "XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB
 TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS JSON PDUMPER LCMS2 GMP")
  (build . "2月 23, 2020")
  (buildopts "--with-modules --with-xwidgets")
  (windowsys . batch)
  (daemonp))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop afcdae4ff 2020-04-17 23:08:28 -0400")
  (dir . "~/.doom.d/"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/bin/sh")
  (uname . "Linux 4.19.84-microsoft-standard #1 SMP Wed Nov 13 11:44:37 UTC 2019 x86_64")
  (path "/usr/local/sbin" "/usr/local/bin" "/usr/sbin" "/usr/bin" "/sbin" "/bin" "/usr/local/libexec/emacs/28.0.50/x86_64-pc-linux-gnu"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +defaults) vc-gutter vi-tilde-fringe window-select
 workspaces :editor (evil +everywhere) file-templates fold snippets :emacs dired electric undo vc :checkers syntax :tools (eval +overlay) lookup magit :lang data
 emacs-lisp markdown org sh :config (default +bindings +smartparens))
  (packages "n/a")
  (unpin "n/a")
  (elpa "n/a")))

$
</pre></details>

**Comment by WhatDothLife** [comment]
I see that you're running emacs 28, while doom only supports version 27. Try downgrading and see, if the error persists.

**Comment by blasterpistol** [comment]
Have the same error with emacs v27.

**Comment by Filip62** [comment]
I am not sure if it is related but,
I installed Doom Emacs like a week ago with Emacs 27 and the message Package cl is deprecated was not there back then. Now it is.
