### ISSUE TITLE
Lost global evil leader keys on upgrade

### ISSUE THREAD

**Issue by korkeala** [hlissner/doom-emacs#2931]
**What did you expect to happen?**
I upgraded doom emacs (btw thank you for excellent project, been using doom for many months) yesterday and after global evil leader key bindings have disappered. I open an org-file and then try to open magit status with **SPC g g**, I expect that the magit status buffer would open. 

**What actually happened?**
It says **SPC g is undefined**

**Additional details:**
- When I press SPC it shows only **m-> +<localleader>** as available option.
- I also tried removing ~/.emacs.d/ and installing doom emacs again, but same result.

**System information:**
<details><pre>
```
emacs   version    26.3
        features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LCMS2
        build      Dec 10, 2019
        buildopts  (--build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-dbus --with-gif --with-jpeg --with-png --with-rsvg --with-tiff --with-xft --with-xpm --with-x-toolkit=gtk3 --with-gpm=no --with-xwidgets --with-modules build_alias=x86_64-redhat-linux-gnu host_alias=x86_64-redhat-linux-gnu 'CFLAGS=-DMAIL_USE_LOCKF -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection' LDFLAGS=-Wl,-z,relro PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig)
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop, origin/develop, origin/HEAD afcdae4ff 2020-04-17 23:08:28 -0400
        dir        ~/.doom.d/
system  type       gnu/linux
        config     x86_64-redhat-linux-gnu
        shell      /bin/bash
        uname      Linux 5.5.5-200.fc31.x86_64 #1 SMP Wed Feb 19 23:28:07 UTC 2020 x86_64
        path       (~/bin /usr/lib64/qt-3.3/bin /usr/share/Modules/bin /usr/local/bin /usr/local/sbin /usr/bin /usr/sbin  ~/.local/bin /usr/libexec/emacs/26.3/x86_64-redhat-linux-gnu/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company ivy :ui deft doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold multiple-cursors rotate-text snippets :emacs dired electric ibuffer vc :term shell :tools ansible docker (eval +overlay) :checkers syntax :tools (lookup +docsets) lsp magit make pass pdf terraform :lang clojure data emacs-lisp (java +meghanada) javascript latex ledger markdown (org +dragndrop +hugo +ipython +pandoc +pomodoro +present) plantuml python racket rest sh :email (mu4e +gmail) :app (rss +org) :config (default +bindings +smartparens))
        packages   ((org-brain) (ox-epub) (org-gcal) (org-journal) (wcheck-mode) (org-chef) (smtpmail) (org-noter) (org-ref) (org-download) (org-ql) (zetteldeft) (org-cliplink) (org-kanban) (org-superagenda) (elfeed-org) (walkman :recipe (:host github :repo abrochard/walkman)) (org-roam :recipe (:host github :repo jethrokuan/org-roam)) (htmlize :recipe (:host github :repo hniksic/emacs-htmlize :branch master)))
        unpin      (n/a)
        elpa       (n/a)
```
</pre></details>

**Comment by hlissner** [comment]
When leader keys go missing, it usually means there was an error during startup. After startup, do you see any warnings or error messages in the \*Messages\* buffer? Press `SPC h e` or `C-h e` to open it.

**Comment by korkeala** [comment]
No major errors, see below for the contents of *Messages*. This happened also with other computer, which have same operating system and setup, but slightly different user configurations.

`Loading /usr/share/emacs/site-lisp/site-start.d/asy-init.el (source)...done
Loading /usr/share/emacs/site-lisp/site-start.d/autoconf-init.el (source)...done
Loading /usr/share/emacs/site-lisp/site-start.d/clang-format.el (source)...done
Loading /usr/share/emacs/site-lisp/site-start.d/cmake-init.el (source)...done
Loading /usr/share/emacs/site-lisp/site-start.d/desktop-entry-mode-init.el (source)...done
Loading /usr/share/emacs/site-lisp/site-start.d/htmlize-init.el (source)...done
Loading /usr/share/emacs/site-lisp/site-start.d/mercurial-site-start.el (source)...done
Loading /usr/share/emacs/site-lisp/site-start.d/protobuf-init.el (source)...done
Loading /usr/share/emacs/site-lisp/site-start.d/rpmdev-init.el (source)...done
WARNING (:tools flycheck) module was moved to (:checkers syntax)
Doom loaded 304 packages across 55 modules in 3.018s
custom-initialize-reset: Autoloading file /home/user/.emacs.d/.local/straight/build/org-roam/org-roam.elc failed to define function org-roam--build-cache-async
Loading /home/user/.emacs.d/.local/cache/recentf...done
`

**Comment by hlissner** [comment]
Is your config up somewhere I can see it?

**Comment by korkeala** [comment]
No, havent published it, but I was able to find the problem in my config.el. Problems disappeared when I commented out my org-roam configurations (see below). I think it is now better integrated with doom emacs? I'll check the documentation for proper way to configure org-roam with doom. Thanks for your help!

`(use-package org-roam
      :after org
      :hook
      ((org-mode . org-roam-mode)
       (after-init . org-roam--build-cache-async) ;; optional!
       )
      :custom
      (org-roam-directory "~/org/brain")
      (org-roam-use-timestamp-as-filename nil)
      :bind
      ("C-c n l" . org-roam)
      ("C-c n t" . org-roam-today)
      ("C-c n f" . org-roam-find-file)
      ("C-c n i" . org-roam-insert)
      ("C-c n g" . org-roam-show-graph))
`

**Comment by hlissner** [comment]
@korkeala btw the `:lang org` module has a `+roam` flag.

In any case, I'll consider this resolved then.

**Comment by andythemoron** [comment]
I know this issue is closed, but I figured I'd leave a trail if anyone else runs into this problem and comes across this. I encountered this issue after I had been googling to see if it was a known (configuration) issue.

I think I ended up getting into this state after I experienced some config and/or runtime errors related to org-roam, and other things in my config. I have been using and loving Doom Emacs on my Chromebook, but I ran into this issue on my Macbook after updating the config settings, and possibly updating Doom Emacs as well. (I had been working primarily on the Chromebook for a while, so I cannot recall the exact sequence that lead to the Macbook Doom Emacs issue.) I do not see any errors in my messages on start up now (C-h e):

For information about GNU Emacs and the GNU system, type C-h C-a.
Doom loaded 163 packages across 32 modules in 3.942s

I've tried running "doom clean" and removing org-roam.db and org-roam related settings in my config, but it has not made a difference. (I had only been trying org-roam out; I had not really been using it.)

To be useful for reproducing, I'd imagine you'd need my config.el and such. I wanted to leave this here for now, but I may return with this and more information and/or try a fresh install, different versions, etc. and report back.

**Comment by Ne1c** [comment]
@andythemoron hi I faced the same problem. `(evil +everywhere)` enabled I didn't override leader key, but emacs doesn't see it. When I call evil-send-leader, the function returns `<leader> is undefined`. I tried clean, rebuild, purge, sync emacs and it didn't help. Did you manage to fix this issue?

@hlissner may be you can help?

Here is my config file:

```
(doom!
 :completion
 company
 ivy

 :ui
 doom
 doom-dashboard
 ;; doom-quit
 ligatures
 indent-guides
 hl-todo
 modeline
 ophints
 workspaces
 window-select
 treemacs
 unicode
 vc-gutter

 :term
 vterm

 :editor
 (evil +everywhere)
 snippets

 :emacs
 dired
 undo
 vc

 :checkers
 syntax
 spell
 grammar

 :tools
 lsp
 (eval +overlay)
 lookup
 magit
 make

 :os
 (:if IS-MAC macos)

 :lang
 (cc +lsp)
 (python +lsp)
 emacs-lisp
 (kotlin +lsp)
 markdown
 org
 sh

 :config
 (def +bindings +smartparens))

(setq initial-frame-alist '((top . 0.5) (left . 0.5) (width . 143) (height . 55)))
(setq company-minimum-prefix-length 1 company-idle-delay 0.0)
```

**Comment by destinf** [comment]
+1 having the same issue. Used a blank config.el and still having the same problem, getting the `<leader> is undefined` when calling `evil-send-leader` as well.

**Comment by hlissner** [comment]
@destinf @Ne1c Doom doesn't use `evil`'s leader key functionality, nor has it been set up. If you must use it, you'll have to read evil's documentation on how to do so. Otherwise, the canonical way to bind leader keys in Doom is with `(map! :leader ...)`. See `SPC h f map\!` for docs and demos.
