### ISSUE TITLE
Inline download images are broken after afca8f14

### ISSUE THREAD

**Issue by jsravn** [hlissner/doom-emacs#2932]
**What did you expect to happen?**
Inline images should work. But the recent change at https://github.com/hlissner/doom-emacs/commit/afca8f14a14d3988872aa4178d6a7a34ba6c363a breaks them. Confirmed by another user on Discord.

**What actually happened?**

![image](https://user-images.githubusercontent.com/522123/79636566-7e175500-8170-11ea-97ba-86d6d838976d.png)

Reverting the above commit locally fixes it for me and all inline images display correctly.

Backtrace:
<details><pre>
Debugger entered--entering a function:
* +org-dragndrop-image-fn("download" "db/5befb7-8e3e-4fad-a338-ee8d7be3ae44/_20200314_15..." nil)
  org-display-user-inline-images(t t 17363 18215)
  apply(org-display-user-inline-images (t t 17363 18215))
  #f(advice-wrapper :after #f(compiled-function (&optional include-linked refresh beg end) "Display inline images.\n\nAn inline image is a link which follows either of these\nconventions:\n\n  1. Its path is a file with an extension matching return value\n     from `image-file-name-regexp' and it has no contents.\n\n  2. Its description consists in a single link of the previous\n     type.  In this case, that link must be a well-formed plain\n     or angle link, i.e., it must have an explicit \"file\" type.\n\nEquip each image with the key-map `image-map'.\n\nWhen optional argument INCLUDE-LINKED is non-nil, also links with\na text description part will be inlined.  This can be nice for\na quick look at those images, but it does not reflect what\nexported files will look like.\n\nWhen optional argument REFRESH is non-nil, refresh existing\nimages between BEG and END.  This will create new image displays\nonly if necessary.\n\nBEG and END define the considered part.  They default to the\nbuffer boundaries with possible narrowing." (interactive "P") #<bytecode 0x158edd9e6ad9>) org-display-user-inline-images)(t t 17363 18215)
  apply(#f(advice-wrapper :after #f(compiled-function (&optional include-linked refresh beg end) "Display inline images.\n\nAn inline image is a link which follows either of these\nconventions:\n\n  1. Its path is a file with an extension matching return value\n     from `image-file-name-regexp' and it has no contents.\n\n  2. Its description consists in a single link of the previous\n     type.  In this case, that link must be a well-formed plain\n     or angle link, i.e., it must have an explicit \"file\" type.\n\nEquip each image with the key-map `image-map'.\n\nWhen optional argument INCLUDE-LINKED is non-nil, also links with\na text description part will be inlined.  This can be nice for\na quick look at those images, but it does not reflect what\nexported files will look like.\n\nWhen optional argument REFRESH is non-nil, refresh existing\nimages between BEG and END.  This will create new image displays\nonly if necessary.\n\nBEG and END define the considered part.  They default to the\nbuffer boundaries with possible narrowing." (interactive "P") #<bytecode 0x158edd9e6ad9>) org-display-user-inline-images) (t t 17363 18215))
  (progn (fset #'create-image vnew) (apply orig-fn args))
  (unwind-protect (progn (fset #'create-image vnew) (apply orig-fn args)) (fset #'create-image old))
  (let* ((vnew #'(lambda (file-or-data &optional type data-p &rest props) (let ((type ...)) (apply old-create-image file-or-data type data-p props)))) (old (symbol-function #'create-image))) (unwind-protect (progn (fset #'create-image vnew) (apply orig-fn args)) (fset #'create-image old)))
  (let ((old-create-image (symbol-function #'create-image))) (let* ((vnew #'(lambda (file-or-data &optional type data-p &rest props) (let (...) (apply old-create-image file-or-data type data-p props)))) (old (symbol-function #'create-image))) (unwind-protect (progn (fset #'create-image vnew) (apply orig-fn args)) (fset #'create-image old))))
  +org--fix-inline-images-for-imagemagick-users-a(#f(advice-wrapper :after #f(compiled-function (&optional include-linked refresh beg end) "Display inline images.\n\nAn inline image is a link which follows either of these\nconventions:\n\n  1. Its path is a file with an extension matching return value\n     from `image-file-name-regexp' and it has no contents.\n\n  2. Its description consists in a single link of the previous\n     type.  In this case, that link must be a well-formed plain\n     or angle link, i.e., it must have an explicit \"file\" type.\n\nEquip each image with the key-map `image-map'.\n\nWhen optional argument INCLUDE-LINKED is non-nil, also links with\na text description part will be inlined.  This can be nice for\na quick look at those images, but it does not reflect what\nexported files will look like.\n\nWhen optional argument REFRESH is non-nil, refresh existing\nimages between BEG and END.  This will create new image displays\nonly if necessary.\n\nBEG and END define the considered part.  They default to the\nbuffer boundaries with possible narrowing." (interactive "P") #<bytecode 0x158edd9e6ad9>) org-display-user-inline-images) t t 17363 18215)
  apply(+org--fix-inline-images-for-imagemagick-users-a #f(advice-wrapper :after #f(compiled-function (&optional include-linked refresh beg end) "Display inline images.\n\nAn inline image is a link which follows either of these\nconventions:\n\n  1. Its path is a file with an extension matching return value\n     from `image-file-name-regexp' and it has no contents.\n\n  2. Its description consists in a single link of the previous\n     type.  In this case, that link must be a well-formed plain\n     or angle link, i.e., it must have an explicit \"file\" type.\n\nEquip each image with the key-map `image-map'.\n\nWhen optional argument INCLUDE-LINKED is non-nil, also links with\na text description part will be inlined.  This can be nice for\na quick look at those images, but it does not reflect what\nexported files will look like.\n\nWhen optional argument REFRESH is non-nil, refresh existing\nimages between BEG and END.  This will create new image displays\nonly if necessary.\n\nBEG and END define the considered part.  They default to the\nbuffer boundaries with possible narrowing." (interactive "P") #<bytecode 0x158edd9e6ad9>) org-display-user-inline-images) (t t 17363 18215))
  org-display-inline-images(t t 17363 18215)
  (if (> (length org-inline-image-overlays) 0) (org-remove-inline-images) (org-display-inline-images t t (if (org-before-first-heading-p) (line-beginning-position) (save-excursion (org-back-to-heading) (point))) (if (org-before-first-heading-p) (line-end-position) (save-excursion (org-end-of-subtree) (point)))))
  +org--refresh-inline-images-in-subtree()
  (if (or (equal (org-element-property :type lineage) "img") (and path (image-type-from-file-name path))) (+org--refresh-inline-images-in-subtree) (org-open-at-point))
  (let* ((lineage (org-element-lineage context '(link) t)) (path (org-element-property :path lineage))) (if (or (equal (org-element-property :type lineage) "img") (and path (image-type-from-file-name path))) (+org--refresh-inline-images-in-subtree) (org-open-at-point)))
  (cond ((eq type 'headline) (cond ((and (fboundp 'toc-org-insert-toc) (member "TOC" (org-get-tags))) (toc-org-insert-toc) (message "Updating table of contents")) ((string= "ARCHIVE" (car-safe (org-get-tags))) (org-force-cycle-archived)) ((or (org-element-property :todo-type context) (org-element-property :scheduled context)) (org-todo (if (eq (org-element-property :todo-type context) 'done) (or (car ...) 'todo) 'done))) (t (+org--refresh-inline-images-in-subtree) (org-clear-latex-preview) (org-latex-preview '(4))))) ((eq type 'clock) (org-clock-update-time-maybe)) ((eq type 'footnote-reference) (org-footnote-goto-definition (org-element-property :label context))) ((eq type 'footnote-definition) (org-footnote-goto-previous-reference (org-element-property :label context))) ((memq type '(timestamp planning)) (org-follow-timestamp-link)) ((memq type '(table-row table)) (if (org-at-TBLFM-p) (org-table-calc-current-TBLFM) (condition-case nil (progn (save-excursion (goto-char (org-element-property :contents-begin context)) (org-call-with-arg 'org-table-recalculate (or arg t)))) (error nil)))) ((eq type 'table-cell) (org-table-blank-field) (org-table-recalculate) (if (and (string-empty-p (string-trim (org-table-get-field))) (and (boundp 'evil-local-mode) evil-local-mode)) (progn (evil-change-state 'insert)))) ((eq type 'babel-call) (org-babel-lob-execute-maybe)) ((eq type 'statistics-cookie) (save-excursion (org-update-statistics-cookies nil))) ((memq type '(inline-src-block src-block)) (org-babel-execute-src-block)) ((memq type '(latex-environment latex-fragment)) (org-latex-preview)) ((eq type 'link) (let* ((lineage (org-element-lineage context '(link) t)) (path (org-element-property :path lineage))) (if (or (equal (org-element-property :type lineage) "img") (and path (image-type-from-file-name path))) (+org--refresh-inline-images-in-subtree) (org-open-at-point)))) ((org-element-property :checkbox (org-element-lineage context '(item) t)) (let ((match (and (org-at-item-checkbox-p) (match-string 1)))) (org-toggle-checkbox (if (equal match "[ ]") '(16))))) (t (if (or (org-in-regexp org-ts-regexp-both nil t) (org-in-regexp org-tsr-regexp-both nil t) (org-in-regexp org-any-link-re nil t)) (call-interactively #'org-open-at-point) (+org--refresh-inline-images-in-subtree))))
  (let* ((context (org-element-context)) (type (org-element-type context))) (while (and context (memq type '(verbatim code bold italic underline strike-through subscript superscript))) (setq context (org-element-property :parent context) type (org-element-type context))) (cond ((eq type 'headline) (cond ((and (fboundp 'toc-org-insert-toc) (member "TOC" (org-get-tags))) (toc-org-insert-toc) (message "Updating table of contents")) ((string= "ARCHIVE" (car-safe (org-get-tags))) (org-force-cycle-archived)) ((or (org-element-property :todo-type context) (org-element-property :scheduled context)) (org-todo (if (eq ... ...) (or ... ...) 'done))) (t (+org--refresh-inline-images-in-subtree) (org-clear-latex-preview) (org-latex-preview '(4))))) ((eq type 'clock) (org-clock-update-time-maybe)) ((eq type 'footnote-reference) (org-footnote-goto-definition (org-element-property :label context))) ((eq type 'footnote-definition) (org-footnote-goto-previous-reference (org-element-property :label context))) ((memq type '(timestamp planning)) (org-follow-timestamp-link)) ((memq type '(table-row table)) (if (org-at-TBLFM-p) (org-table-calc-current-TBLFM) (condition-case nil (progn (save-excursion (goto-char ...) (org-call-with-arg ... ...))) (error nil)))) ((eq type 'table-cell) (org-table-blank-field) (org-table-recalculate) (if (and (string-empty-p (string-trim (org-table-get-field))) (and (boundp 'evil-local-mode) evil-local-mode)) (progn (evil-change-state 'insert)))) ((eq type 'babel-call) (org-babel-lob-execute-maybe)) ((eq type 'statistics-cookie) (save-excursion (org-update-statistics-cookies nil))) ((memq type '(inline-src-block src-block)) (org-babel-execute-src-block)) ((memq type '(latex-environment latex-fragment)) (org-latex-preview)) ((eq type 'link) (let* ((lineage (org-element-lineage context '... t)) (path (org-element-property :path lineage))) (if (or (equal (org-element-property :type lineage) "img") (and path (image-type-from-file-name path))) (+org--refresh-inline-images-in-subtree) (org-open-at-point)))) ((org-element-property :checkbox (org-element-lineage context '(item) t)) (let ((match (and (org-at-item-checkbox-p) (match-string 1)))) (org-toggle-checkbox (if (equal match "[ ]") '(16))))) (t (if (or (org-in-regexp org-ts-regexp-both nil t) (org-in-regexp org-tsr-regexp-both nil t) (org-in-regexp org-any-link-re nil t)) (call-interactively #'org-open-at-point) (+org--refresh-inline-images-in-subtree)))))
  +org/dwim-at-point()
  funcall-interactively(+org/dwim-at-point)
  call-interactively(+org/dwim-at-point nil nil)
  command-execute(+org/dwim-at-point)
</pre></details>

**Comment by jsravn** [comment]
No errors are produced in the log, and tracing through I see it correctly returns the image contents. I'm not sure why org can't handle it.

**Comment by hlissner** [comment]
As of 141a649 I've reverted the change, which should resolve this issue. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
