### ISSUE TITLE
Package posframe missing for DAP

### ISSUE THREAD

**Issue by ncihnegn** [hlissner/doom-emacs#2934]
**What did you expect to happen?**
No errors.

**What actually happened?**
```
$ doom doctor
...
! Attempt to load DOOM failed
  (config.el (error Displaying DAP controls requires that the posframe Emacs package is installed))
```

**Additional details:**

**Steps to reproduce:**

**System information:**

**Comment by hlissner** [comment]
As of 09f617d the module should install posframe for you. I wasn't aware it was a manual dependency. Keep in mind that dap-mode (and dap-ui-mode) is now behind the `+lsp` flag for the `:tools debugger` module. i.e. You'll need to enable `:tools (debugger +lsp)` for it to work.

Let me know if the issue isn't resolved and I'll reopen it. Thanks for bringing it to my attention!
