### ISSUE TITLE
File mode specification error: (void-function alchemist)

### ISSUE THREAD

**Issue by DonHansDampf** [hlissner/doom-emacs#294]
Running Sierra installed a fresh copy of Emacs (`brew install emacs-mac --with-glib --with-imagemagick --with-dbus --with-modules --with-modern-icon --with-natural-title-bar --with-xml2 --with-gnutls`), removed my old `.emacs.d`-folder, and cloned DOOM.

I copied/edited the `init.el`-file and run `make install`. Somehow it seems like the install-process skips some packages with the message `Already installed`. Also the needed alchemist-package. But i can find the alchemist packages in `.emacs.d/.local/packages/...`. 

When i open an elixir-file, i get the error message `File mode specification error: (void-function alchemist)`. Also i can't run any alchemist-commands. Output of `make doctor`:

```
~/.emacs.d [master] » make doctor
DOOM Doctor
Running Emacs v25.3.1, commit 8c4e6a267d8a61d917813eee714816347331c322

Compiled with:
  DBUS NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES
uname -a:
  Darwin MacBook-33-DOMAIN 16.7.0 Darwin Kernel Version 16.7.0: Mon
  Nov 13 21:56:25 PST 2017; root:xnu-3789.72.11~1/RELEASE_X86_64 x86_64

Attempt to load DOOM: success! Loaded v2.0.8
Revision 8c4e6a267d8a61d917813eee714816347331c322

----

Found font material-design-icons.ttf
Found font weathericons.ttf
Found font octicons.ttf
Found font fontawesome.ttf
Found font file-icons.ttf
Found font all-the-icons.ttf
Everything seems fine, happy Emacs’ing!
```

**Comment by hlissner** [comment]
The `lang/elixir` module was misconfigured, my bad. I've hotfixed a rewrite of the module into `master`, which should resolve your issues. Feel free to reopen this if it doesn't.
