### ISSUE TITLE
`C-h` does not work in `SPC w` which key pop-up 

### ISSUE THREAD

**Issue by pkazmier** [hlissner/doom-emacs#2940]
**What did you expect to happen?**
As a new Doom user (about 1 hour of use), I was exploring the various key bindings for window management in the `SPC w` map. When I press `SPC w` and pause, the pop-up appears with the first page of keys that can be pressed. At the bottom of that pop-up, it says to press `C-h` for paging options. I expected that a `C-h` would present the option to press `j` and `k` to navigate the pages.

![image](https://user-images.githubusercontent.com/747855/79719286-d56a1200-82a3-11ea-913f-37adbea3919c.png)

**What actually happened?**
When I press `C-h`, the pop-up closes with the following message:

> user-error: No window left from selected window

![image](https://user-images.githubusercontent.com/747855/79720128-8f15b280-82a5-11ea-8041-0ae13a5ef535.png)

**Additional details:**
`C-h` works as expected when I do the same with `SPC b`.

This is a brand new install and I have not made any customizations to it yet. 

**Steps to reproduce:**
1. Start Doom Emacs
2. Press `SPC w` and pause for pop-up
3. Press `C-h` and pop-up closes with error message

**System information:**
<details><pre>
emacs   version    27.0.91
        features   RSVG IMAGEMAGICK GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS PDUMPER LCMS2 GMP
        build      Apr 19, 2020
        buildopts  (--disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus/HEAD-5734339/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus/HEAD-5734339 --with-xml2 --without-dbus --with-gnutls --with-imagemagick --with-modules --with-rsvg --with-ns --disable-ns-self-contained)
        windowsys  ns
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop, origin/develop, origin/HEAD 3a5ef316f 2020-04-19 22:04:12 -0400
        dir        ~/.doom.d/
system  type       darwin
        config     x86_64-apple-darwin18.7.0
        shell      /bin/zsh
        uname      Darwin 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64
        path       (~/Library/Caches/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-caarlos0-SLASH-ports /usr/local/bin /usr/bin /bin /usr/sbin /sbin /usr/local/go/bin /Library/Frameworks/Mono.framework/Versions/Current/Commands /Applications/Wireshark.app/Contents/MacOS /Applications/kitty.app/Contents/MacOS /usr/local/bin ~/.dotfiles/bin ~/.bin /usr/local/Cellar/emacs-plus/HEAD-5734339/libexec/emacs/27.0.91/x86_64-apple-darwin18.7.0/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold snippets :emacs dired electric undo vc :checkers syntax :tools (eval +overlay) lookup magit :lang data emacs-lisp markdown org sh :config (default +bindings +smartparens))
        packages   (n/a)
        unpin      (n/a)
        elpa       (n/a)
</pre></details>

**Comment by hlissner** [comment]
This isn't a bug. The which-key package has two choices: obey the original keybinds or override `C-h` wherever it is used. It chose to do the former, which I think is the correct choice.

You can alternatively press <kbd>?</kbd> or <kbd>F1</kbd> to get the help menu.

**Comment by pkazmier** [comment]
I suppose it makes sense aside from the fact that the message at the bottom of the pop-up states one should press `C-h` for paging options. Regardless, I understand now that this is not an issue with Doom.

Thanks for the tip about the `?` working equally as well (`F1` is a nightmare on a mac laptop).
