### ISSUE TITLE
fresh install error : doom-package-error 

### ISSUE THREAD

**Issue by younlok** [hlissner/doom-emacs#2942]
**What did you expect to happen?**
i expected doom to install correctly 

**What actually happened?**

<details><pre>
x There was an unexpected error:
  Type: doom-package-error
  Message:
    Error with packages
  Data:
    "ws-butler"
    (error "Failed to run \"git\"; see buffer *straight-process*")
    "Cloning into '/home/younlok/.emacs.d/.local/straight/repos/ws-butler'...
    fatal: unable to access 'https://github.com/hlissner/ws-butler.git/': Failed to connect to github.com port 443: Connection timed out
    "
  Straight output:
    Cloning into '/home/younlok/.emacs.d/.local/straight/repos/ws-butler'...
    fatal: unable to access 'https://github.com/hlissner/ws-butler.git/': Failed to connect to github.com port 443: Connection timed out
    

Run the command again with the -d (or --debug) switch to enable debug
mode and (hopefully) generate a backtrace from this error:

  doom -d install

If you file a bug report, please include it!

</pre></details>

**Steps to reproduce:**
doom intall 

**System information:**
<details><pre>
((emacs
  (version . "26.3")
  (features . "XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2")
  (build . "Aug 29, 2019")
  (buildopts "--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-modules 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now")
  (windowsys . batch)
  (daemonp))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD 3a5ef316f 2020-04-19 22:04:12 -0400")
  (dir . "~/.doom.d/"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/bin/bash")
  (uname . "Linux 4.19.69-1-lts #1 SMP Thu Aug 29 12:06:45 CEST 2019 x86_64")
  (path "/usr/local/bin" "/usr/bin" "/bin" "/usr/local/sbin" "/usr/lib/jvm/default/bin" "/usr/bin/site_perl" "/usr/bin/vendor_perl" "/usr/bin/core_perl" "/usr/local/go/bin" "~/flutter/flutter/bin" "/usr/lib/jvm/default/bin" "/usr/bin/site_perl" "/usr/bin/vendor_perl" "/usr/bin/core_perl" "/usr/local/go/bin" "~/flutter/flutter/bin" "/usr/lib/emacs/26.3/x86_64-pc-linux-gnu"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold snippets :emacs dired electric undo vc :checkers syntax :tools (eval +overlay) lookup magit :lang data emacs-lisp markdown org sh :config (default +bindings +smartparens))
  (packages "n/a")
  (unpin "n/a")
  (elpa "n/a")))

</pre></details>

**Comment by RBckmnn** [comment]
See

https://github.com/hlissner/doom-emacs/issues/2937

for a workaround

**Comment by hlissner** [comment]
>fatal: unable to access 'https://github.com/hlissner/ws-butler.git/': Failed to connect to github.com port 443: Connection timed out

The error says the connection timed out. This is a networking issue, not an issue with Doom. Simply try `doom install` again.

Otherwise, try https://github.com/hlissner/doom-emacs/issues/2937#issuecomment-616211870
