### ISSUE TITLE
Unable to run go tests from emacs 

### ISSUE THREAD

**Issue by jijeshmohan** [hlissner/doom-emacs#2945]
**What did you expect to happen?**
...
I am using go mode + LSP . Everything is working fine including LSP rename , autocomplete. But unable to run tests `SPC m t s` or any other test methods starting with `SPC m t`

**What actually happened?**
...
I am getting the following error when I try to run tests.

`compilation-buffer-name: Symbol’s function definition is void: compilation--default-buffer-name`

**Additional details:**
- Include a link to your private config  - Not using any primate config 
- Include screenshots/casts of your issue - I can post if it required
- If you mention key sequences, include what commands they're bound to (use `SPC
  h k KEY` or `C-h h k KEY` to inspect keys).
- Include any warnings or errors logged to \*Messages\* (use `M-x
  view-echo-area-messages` to see it).
```
LSP :: Connected to [gopls:55868 status:starting].
LSP :: gopls:55868 initialized successfully
compilation-buffer-name: Symbol’s function definition is void: compilation--default-buffer-name
```

<details><pre>
 Debugger entered--Lisp error: (void-function compilation--default-buffer-name)
   compilation--default-buffer-name("compilation")
   compilation-buffer-name("compilation" compilation-mode nil)
   compilation-start("go test -run='Test_userHandler_searchUser'" nil)
   compile("go test -run='Test_userHandler_searchUser'")
   (progn (compile cmd))
   (unwind-protect (progn (compile cmd)) (internal--after-save-selected-window save-selected-window--state))
   (save-current-buffer (unwind-protect (progn (compile cmd)) (internal--after-save-selected-window save-selected-window--state)))
   (let ((save-selected-window--state (internal--before-save-selected-window))) (save-current-buffer (unwind-protect (progn (compile cmd)) (internal--after-save-selected-window sa$
   +go--spawn("go test -run='Test_userHandler_searchUser'")
   (let ((cmd (concat "go test " args))) (setq +go-test-last (concat "cd " default-directory ";" cmd)) (+go--spawn cmd))
   +go--run-tests("-run='Test_userHandler_searchUser'")
   (save-excursion (re-search-backward "^func[ ]+\\(([[:alnum:]]*?[ ]?[*]?[[:alnum:]]+)[ ]+\\)?\\(Test[[:alnum:]_]+\\)(.*)") (+go--run-tests (concat "-run" "='" (match-string-no-p$
   (if (string-match "_test\\.go" buffer-file-name) (save-excursion (re-search-backward "^func[ ]+\\(([[:alnum:]]*?[ ]?[*]?[[:alnum:]]+)[ ]+\\)?\\(Test[[:alnum:]_]+\\)(.*)") (+go-$
   +go/test-single()
   funcall-interactively(+go/test-single)
   call-interactively(+go/test-single nil nil)
   command-execute(+go/test-single)

</pre></details>

**Steps to reproduce:**
1. Enable go-mode + lsp 
2. Open any golang project 
3. Open any test file 
4. go to test func and run `SPC m t s`

**System information:**
<details><pre>
```
   4 emacs   version    28.0.50
   5         features   RSVG IMAGEMAGICK GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS JSON PDUMPER LCMS2 GMP
   6         build      Mar 01, 2020
   7         buildopts  (--enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-head/HEAD-1dd4a63_1/share/info/emacs
     --prefix=/usr/local/Cellar/emacs-head/HEAD-1dd4a63_1 --without-x --without-dbus --with-imagemagick --with-json --with-modules --with-gnutls --with-rsvg --with-xml2
     --with-harfbuzz --with-ns --disable-ns-self-contained)
   8         windowsys  nil
   9         daemonp    nil
  10 doom    version    2.0.9
  11         build      HEAD -> develop, origin/develop, origin/HEAD 0a26a22d5 2020-04-20 22:53:05 -0400
  12         dir        ~/.doom.d/
  13 system  type       darwin
  14         config     x86_64-apple-darwin19.3.0
  15         shell      /bin/zsh
  16         uname      Darwin 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64
  17         path       (~/.pyenv/shims ~/.nvm/versions/node/v10.15.3/bin ~/.cargo/bin ~/Softwares/google-cloud-sdk/bin ~/.rbenv/shims ~/.rbenv/shims ~/bin /usr/local/bin
     ~/.pyenv/shims ~/.nvm/versions/node/v10.15.3/bin ~/.cargo/bin ~/Softwares/google-cloud-sdk/bin ~/.rbenv/shims ~/.rbenv/shims ~/bin /usr/local/bin ~/.cargo/bin /usr/local/bin
     /usr/bin /bin /usr/sbin /sbin /usr/local/MacGPG2/bin  ~/Softwares/google-cloud-sdk/bin ~/.fzf/bin ~/Library/Android/sdk/tools/bin
     ~/Library/Android/sdk/platform-tools ~/Library/Android/sdk/emulator ~/Tools/flutter/bin ~/Softwares/google-cloud-sdk/bin ~/Library/Android/sdk/tools/bin
     ~/Library/Android/sdk/platform-tools ~/Library/Android/sdk/emulator ~/Tools/flutter/bin
     /usr/local/Cellar/emacs-head/HEAD-1dd4a63_1/libexec/emacs/28.0.50/x86_64-apple-darwin19.3.0)
  18 config  envfile    nil
  19         elc-files  0
  20         modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +defaults) treemacs vc-gutter vi-tilde-fringe
     window-select workspaces :editor (evil +everywhere) file-templates fold snippets :emacs dired electric vc :term vterm :checkers syntax :tools (eval +overlay) lookup lsp macos
     magit :lang data emacs-lisp (go +lsp) markdown (org +dragndrop +present) sh :config (default +bindings +smartparens))
  21         packages   (n/a)
  22         unpin      (n/a)
  23         elpa       (n/a)
 
</pre></details>

**Comment by soedirgo** [comment]
`compilation--default-buffer-name` is defined since Emacs 27. Can you check if it's still void in vanilla Emacs?

Also, keep in mind that Doom Emacs only supports up to Emacs 27. Maybe downgrading will help?

**Comment by jijeshmohan** [comment]
Thanks for the help. Downgraded to 26.3 and it is working fine
