### ISSUE TITLE
Powerthesaurus is broken because Powerthesaurus API change

### ISSUE THREAD

**Issue by d1egoaz** [hlissner/doom-emacs#2946]
It has also been reported in upstream.

https://github.com/SavchenkoValeriy/emacs-powerthesaurus/issues/11

pressing `SPC s T` on emacs, doesn't show any user feedback, no error or message at all on the messages buffer or mini-buffer.

**Comment by hlissner** [comment]
As of 27c64a3 this issue should be resolved. I'll keep this open until it is resolved upstream and we can revert back to the source package. Thanks for bringing it to my attention!

**Comment by maxchaos** [comment]
Hi. The original upstream repo has been updated so there is no longer a need for pulling from the fork.

**Comment by hlissner** [comment]
Great! @maxchaos Thanks for letting me know!
