### ISSUE TITLE
Value of gnutls-algorithm-priority prevents tsl1.3 session for some servers

### ISSUE THREAD

**Issue by RBckmnn** [hlissner/doom-emacs#2949]
I ran into this issue when sending an email using mu4e. The connection to the server of my mail provider (host: mail.gmx.net port: 587) could not be established.

I got the following backtrace/message:

Backtrace:
<details><pre>
Debugger entered--Lisp error: (error "Unable to negotiate a TLS connection with mail.gmx.net/587")
  signal(error ("Unable to negotiate a TLS connection with mail.gmx.net/587"))
  error("Unable to negotiate a TLS connection with %s/%s" "mail.gmx.net" 587)
  network-stream-open-starttls("smtpmail" #<buffer *trace of SMTP session to mail.gmx.net*> "mail.gmx.net" 587 (:type starttls :return-list t :warn-unless-encrypted nil :capability-command "EHLO merlin\015\n" :end-of-command "^[0-9]+ .*\015\n" :success "^2.*\n" :always-query-capabilities t :starttls-function #f(compiled-function (capabilities) #<bytecode 0x20a4971>) :client-certificate t :use-starttls-if-possible t))
  open-network-stream("smtpmail" #<buffer *trace of SMTP session to mail.gmx.net*> "mail.gmx.net" 587 :type starttls :return-list t :warn-unless-encrypted nil :capability-command "EHLO merlin\015\n" :end-of-command "^[0-9]+ .*\015\n" :success "^2.*\n" :always-query-capabilities t :starttls-function #f(compiled-function (capabilities) #<bytecode 0x20a4971>) :client-certificate t :use-starttls-if-possible t)
  smtpmail-via-smtp(("sokosa@gmx.de") #<buffer  smtpmail temp>)
  smtpmail-send-it()
  message-multi-smtp-send-mail()
  message-send-mail(nil)
  message-send-via-mail(nil)
  message-send(nil)
  message-send-and-exit(nil)
  funcall-interactively(message-send-and-exit nil)
  call-interactively(message-send-and-exit nil nil)
  command-execute(message-send-and-exit)
</pre></details>

Message buffer:
<details><pre>
Sending via mail...
gnutls.el: (err=[-55] An illegal parameter has been received.) boot: (:priority SECURE128:+SECURE192:-VERS-ALL:+VERS-TLS1.2:+VERS-TLS1.3 :hostname mail.gmx.net :loglevel 0 :min-prime-bits 3072 :trustfiles (/etc/ssl/certs/ca-certificates.crt) :crlfiles nil :keylist nil :verify-flags nil :verify-error t :callbacks nil)
</pre></details>

Trying to establish the connection via gnutls-cli reveals that the protocol is downgraded to tls1.2:

```
$ gnutls-cli --port=587 -s --crlf --priority SECURE128:+SECURE192:-VERS-ALL:+VERS-TLS1.2:+VERS-TLS1.3 mail.gmx.net
Processed 140 CA certificate(s).
Resolving 'mail.gmx.net:587'...
Connecting to '212.227.17.190:587'...

- Simple Client Mode:

220 gmx.com (mrgmx005) Nemesis ESMTP Service ready
ehlo test
250-gmx.com Hello test [77.11.203.249]
250-8BITMIME
250-AUTH LOGIN PLAIN
250-SIZE 69920427
250 STARTTLS
starttls
220 OK
*** Starting TLS handshake
|<1>| Detected downgrade to TLS 1.2 from TLS 1.3
*** Fatal error: An illegal parameter has been received.
*** Handshake has failed
```

It turns out, that switching TLS1.2 and TLS1.3 in the priority string resolves the connection issue in both cases (terminal/emacs). The docs of [gnutls](https://gnutls.org/manual/html_node/Priority-Strings.html) also mention that the order of items in the priority string is significant.

My knowledge about network security is quite limited. Therefore I can not tell if the server might be misconfigured but for me it would make sense to prioritize the newer protocol version.

Some more infos that might be helpful:

`libgnutls-version` is `30607`

```
$ gnutls-cli --version
gnutls-cli 3.6.13

```

**System information:**
<details>

```
emacs   version    26.3
        features   XPM JPEG TIFF GIF PNG RSVG SOUND GPM DBUS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE XFT ZLIB GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LCMS2
        build      Jan 03, 2020
        buildopts  (--prefix=/usr --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu --mandir=/usr/share/man --infodir=/usr/share/info --datadir=/usr/share --sysconfdir=/etc --localstatedir=/var/lib --disable-silent-rules --docdir=/usr/share/doc/emacs-26.3-r1 --htmldir=/usr/share/doc/emacs-26.3-r1/html --libdir=/usr/lib64 --program-suffix=-emacs-26 --includedir=/usr/include/emacs-26 --infodir=/usr/share/info/emacs-26 --localstatedir=/var --enable-locallisppath=/etc/emacs:/usr/share/emacs/site-lisp --without-compress-install --without-hesiod --without-pop --with-file-notification=inotify --enable-acl --with-dbus --with-modules --without-gameuser --with-gpm --without-kerberos --without-kerberos5 --with-lcms2 --with-xml2 --without-mailutils --without-selinux --with-gnutls --without-libsystemd --with-threads --without-wide-int --with-zlib --with-sound=alsa --with-x --without-ns --without-gconf --without-gsettings --without-toolkit-scroll-bars --with-gif --with-jpeg --with-png --with-rsvg --with-tiff --with-xpm --without-imagemagick --with-xft --without-cairo --without-libotf --without-m17n-flt --with-x-toolkit=gtk3 --with-xwidgets 'CFLAGS=-march=native -O2 -pipe' CPPFLAGS= 'LDFLAGS=-Wl,-O1 -Wl,--as-needed')
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop, upstream/develop 71c5ad500 2020-04-17 15:47:05 -0400
        dir        ~/Workspace/dotfiles/.doom.d/
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/bash
        uname      Linux 5.4.28-gentoo #1 SMP Thu Apr 16 18:43:23 CEST 2020 x86_64
        path       (/usr/lib/llvm/9/bin /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /opt/bin ~/.emacs.d/bin ~/.local/bin /usr/libexec/emacs/26.3/x86_64-pc-linux-gnu/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company helm :ui doom doom-dashboard hl-todo modeline nav-flash ophints (popup +all +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold (format +onsave) multiple-cursors rotate-text snippets :emacs (dired +icons) electric ibuffer undo vc :term vterm :checkers syntax (spell +aspell) :tools direnv (eval +overlay) (lookup +docsets) lsp magit :lang data emacs-lisp (javascript +lsp) latex markdown (org +dragndrop +present) (python +lsp) (sh +lsp) (web +lsp) :email mu4e :config literate (default +bindings +smartparens))
        packages   ((f) (org-drill) (org-super-agenda) (org-chef))
        unpin      (n/a)
        elpa       (n/a)
```
</details>

**Comment by hlissner** [comment]
As of 0c3e117 I've reversed 1.2 and 1.3's priority, which should resolve your issue. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention, and for the detailed bug report!
