### ISSUE TITLE
Circe not working without pass

### ISSUE THREAD

**Issue by DonHansDampf** [hlissner/doom-emacs#295]
Hello,

just tried `circe`, but it doesn't start without `pass`-package installed. I get the error message: `cons: Symbol’s function definition is void: +pass-get-user`. 

The reason for this is probably the private module `hlissner` which tries to load a circe config via `pass`. Dunno if this is desired, or maybe the private module should be disabled?

Greetings

**Comment by hlissner** [comment]
That is _sort of_ intended. My private module is included as a reference and some sensible defaults, but I expect folks to copy it and make it their own.

That said, I understand your frustration. I already have plans (for 2.1) to a) move my private module to a separate repo and b) replace it with a more general "defaults" module, which will only include evil-mode ex commands and keybindings.

I'll leave this issue open until this is done and merged into `master`. I'll let you know once it hits `develop`.

**Comment by DonHansDampf** [comment]
No problem. Definitely no frustration involved 😉 Also i am not sure how "open" you want to design this project. 

Reference is good, but an emacs beginner would not have any clue, why he can't use package X and simply create an issue. Would be simply a great design, when it isn't possible to break anything via changing basic config in the `init.el`.

Thanks and keep going!

**Comment by hlissner** [comment]
Just to let you know: `private/hlissner` has been [moved to another repo](https://github.com/hlissner/doom-emacs-private) and replaced with `private/default`, which is a stripped down and more general version fo my own module.

This should fix your issue (and more importantly, make Doom less troublesome out of the box). I'll keep this issue open until it gets merged into `master`.

>Reference is good, but an emacs beginner would not have any clue, why he can't use package X and simply create an issue. Would be simply a great design, when it isn't possible to break anything via changing basic config in the init.el.

I agree. Although Doom isn't _really_ targeted at beginners, I understand the importance of a good out-of-the-box experience.

**Comment by hlissner** [comment]
This is now in master.
