### ISSUE TITLE
Doctor should diagnose missing init.el, config.el, and packages.el and at least warn

### ISSUE THREAD

**Issue by nicholas-miklaucic** [hlissner/doom-emacs#2959]
**Describe the feature**
I mistakenly deleted my `init.el` file in `~/.doom.d/` (don't ask why I'm capable of that, but I digress). I eventually figured out that was the problem, but I thought it was strange that running `doom doctor` and `doom --debug refresh` wasn't especially helpful: they complain about autoloads, but as far as I know the file they point to is fine and it's just that you're missing the `init.el` file. I don't know to what degree it's possible that different users have their `init.el` named different things or in different places, but I think having a check in `doctor` that at least warned the user that their `.doom.d` setup is unusual would be a good idea.

After I got my setup back up and running, I removed the `init.el` file to test it again, and before running `doom refresh` `doom doctor` does mention something about my `init.el` file perhaps being private. But, after running `doom refresh`, running `doom doctor` again doesn't show the error.

I'm happy to write a pull request for this, it seems simple enough and not a big deal (it's just an added foolproofing measure against idiocy, which is hopefully rare among the userbase), but I just wanted to submit this first. I've been using Emacs for years but switched to Doom very recently, so I'm not too up on how Doom itself works.

Here's a demonstration: forgive the powerline characters probably not showing up correctly. I run `doom refresh` first just to show that things are normal, move the `init.el` so doom can't find it, and run `doom doctor`, which correctly diagnoses the error. Then, I show what happens if you run `doom refresh` first: it messes with the autoloads in a way that makes `doom doctor` no longer flag the missing config file as a problem. Using `--debug` gives a very unhelpful error in code that runs fine in the proper context. 

<details>

```
 nicholas@DESKTOP-DD9K4T8  ~  ~/.emacs.d/bin/doom refresh
> Synchronizing your config with Doom Emacs...
  > Regenerating envvars file at "/mnt/c/Users/nicho/.emacs.d/.local/env"
  - Scraping shell environment
    - Ignoring PWD=/home/nicholas
    - Ignoring TERM=xterm-256color
    - Ignoring HOME=/home/nicholas
    ✓ Successfully generated "/mnt/c/Users/nicho/.emacs.d/.local/env"
  > (Re)generating core autoloads...
    > Generating core autoloads...
    > Byte-compiling core autoloads file...
    ✓ Generated .local/autoloads.elc
  > Installing packages...
    - No packages need to be installed
  > (Re)building packages...
    ✓ No packages need rebuilding
  > Purging orphaned packages (for the emperor)...
    - No builds to purge
    - Skipping elpa packages
    - Skipping repos
    - Skipping regrafting
  > (Re)generating package autoloads...
    > Generating package autoloads...
    > Byte-compiling package autoloads file...
    ✓ Generated .local/autoloads.pkg.elc
✓ Finished! (6.3550s)
 nicholas@DESKTOP-DD9K4T8  ~  mv ~/.doom.d/init.el ~/.doom.d/.init.el
 nicholas@DESKTOP-DD9K4T8  ~  ~/.emacs.d/bin/doom doctor
The doctor will see you now...

> Checking your Emacs version...
> Checking for Emacs config conflicts...
> Checking for private config conflicts...
> Checking for stale elc files...
> Checking Doom Emacs...
  ✓ Initialized Doom Emacs 2.0.9
  ! Failed to load any modules. Do you have an private init.el?
  ✓ Detected 20 packages
  > Checking Doom core for irregularities...
    ! Couldn't find the `fd' binary; project file searches will be slightly slower
    ! Couldn't find the `rg' binary either; project file searches will be even slower
    Found font material-design-icons.ttf
    Found font weathericons.ttf
    Found font octicons.ttf
    Found font fontawesome.ttf
    Found font file-icons.ttf
    Found font all-the-icons.ttf
  > Checking for stale elc files in your DOOMDIR...


There are 2 warnings!
✓ Finished! (9.8630s)
 nicholas@DESKTOP-DD9K4T8  ~  ~/.emacs.d/bin/doom --debug refresh
Loading /mnt/c/Users/nicho/.emacs.d/core/autoload/buffers.el (source)...
Loading /mnt/c/Users/nicho/.emacs.d/core/autoload/cache.el (source)...
Loading /mnt/c/Users/nicho/.emacs.d/core/autoload/cli.el (source)...
Loading /mnt/c/Users/nicho/.emacs.d/core/autoload/config.el (source)...
Loading /mnt/c/Users/nicho/.emacs.d/core/autoload/debug.el (source)...
Loading /mnt/c/Users/nicho/.emacs.d/core/autoload/files.el (source)...
Loading /mnt/c/Users/nicho/.emacs.d/core/autoload/fonts.el (source)...
Loading /mnt/c/Users/nicho/.emacs.d/core/autoload/format.el (source)...
Loading /mnt/c/Users/nicho/.emacs.d/core/autoload/help.el (source)...
Loading /mnt/c/Users/nicho/.emacs.d/core/autoload/packages.el (source)...
Loading /mnt/c/Users/nicho/.emacs.d/core/autoload/plist.el (source)...
Loading /mnt/c/Users/nicho/.emacs.d/core/autoload/projects.el (source)...
Loading /mnt/c/Users/nicho/.emacs.d/core/autoload/scratch.el (source)...
Loading /mnt/c/Users/nicho/.emacs.d/core/autoload/sessions.el (source)...
Loading /mnt/c/Users/nicho/.emacs.d/core/autoload/text.el (source)...
Loading /mnt/c/Users/nicho/.emacs.d/core/autoload/themes.el (source)...
Loading /mnt/c/Users/nicho/.emacs.d/core/autoload/ui.el (source)...
DOOM Initializing package.el
DOOM Initializing straight
DOOM Initializing doom-packages
> Synchronizing your config with Doom Emacs...
  > Regenerating envvars file at "/mnt/c/Users/nicho/.emacs.d/.local/env"
  - Scraping shell environment
    - Ignoring PWD=/home/nicholas
    - Ignoring TERM=xterm-256color
    - Ignoring HOME=/home/nicholas
    - Ignoring DEBUG=1
    ✓ Successfully generated "/mnt/c/Users/nicho/.emacs.d/.local/env"
  > (Re)generating core autoloads...
    > Generating core autoloads...
    - Scanning core/autoload/buffers.el
    - Scanning core/autoload/cache.el
    - Scanning core/autoload/cli.el
    - Scanning core/autoload/config.el
    - Scanning core/autoload/debug.el
    - Scanning core/autoload/files.el
    - Scanning core/autoload/fonts.el
    - Scanning core/autoload/format.el
    - Scanning core/autoload/help.el
    - Scanning core/autoload/packages.el
    - Scanning core/autoload/plist.el
    - Scanning core/autoload/projects.el
    - Scanning core/autoload/scratch.el
    - Scanning core/autoload/sessions.el
    - Scanning core/autoload/text.el
    - Scanning core/autoload/themes.el
    - Scanning core/autoload/ui.el
    - Scanning modules/app/calendar/autoload.el
x There was an unexpected error:
  Type: wrong-type-argument
  Message:
    Wrong type argument
  Data:
    hash-table-p
    nil
 nicholas@DESKTOP-DD9K4T8  ~  ~/.emacs.d/bin/doom doctor
The doctor will see you now...

> Checking your Emacs version...
> Checking for Emacs config conflicts...
> Checking for private config conflicts...
> Checking for stale elc files...
> Checking Doom Emacs...

Autoload file error: autoloads.el -> (file-missing Cannot open load file No such file or directory /mnt/c/Users/nicho/.emacs.d/.local/autoloads)
Autoload file error: autoloads.pkg.el -> (file-missing Cannot open load file No such file or directory /mnt/c/Users/nicho/.emacs.d/.local/autoloads.pkg)
Warning (emacs): Your Doom core autoloads file is missing
Warning (emacs): Your package autoloads file is missing
! Attempt to load DOOM failed
  (Run `bin/doom refresh' to generate them)



There are 1 warnings!
✓ Finished! (4.9683s)
```
</details>

**System information**
I'm on WSL Ubuntu. One thing I'll note about my setup that may be a little unusual is that, from the perspective of Ubuntu, `~/.emacs.d/` and `~/.doom.d/` are both symlinked to a similar location on the Windows side so I can edit those files from either OS. Don't think that should matter but just in case. I can test it on Manjaro if you'd like.

<details><pre>
((emacs
  (version . "26.3")
  (features . "XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD LCMS2")
  (build . "Sep 16, 2019")
  (buildopts "--build=x86_64-linux-gnu --prefix=/usr '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' --sysconfdir=/etc --localstatedir=/var --disable-silent-rules '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' --disable-maintainer-mode --disable-dependency-tracking --prefix=/usr --sharedstatedir=/var/lib --program-suffix=26 --with-modules --with-file-notification=inotify --with-mailutils --with-x=yes --with-x-toolkit=gtk3 --with-xwidgets --with-lcms2 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/emacs26-TP6iDo/emacs26-26.3~1.git96dd019=. -fstack-protector-strong -Wformat -Werror=format-security -no-pie' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro -no-pie'")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD 0c3e11766 2020-04-21 17:08:34 -0400")
  (dir . "/mnt/c/Users/nicho/.doom.d/"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/usr/bin/zsh")
  (uname . "Linux 4.4.0-17763-Microsoft #864-Microsoft Thu Nov 07 15:22:00 PST 2019 x86_64")
  (path "~/anaconda3/condabin" "~/.cargo/bin" "/usr/local/sbin" "/usr/local/bin" "/usr/sbin" "/usr/bin" "/sbin" "/bin" "/usr/games" "/usr/local/games" "/mnt/c/Program Files/WindowsApps/CanonicalGroupLimited.UbuntuonWindows_1804.2020.5.0_x64__79rhkp1fndgsc" "/mnt/c/Program Files (x86)/Common Files/Oracle/Java/javapath" "/mnt/c/Program Files/Haskell/bin" "/mnt/c/Program Files/Haskell Platform/8.6.5/lib/extralibs/bin" "/mnt/c/Program Files/Haskell Platform/8.6.5/bin" "/mnt/c/Program Files/ImageMagick-7.0.8-Q16" "/mnt/c/Python37/Scripts" "/mnt/c/Python37" "/mnt/c/Windows/System32" "/mnt/c/Windows" "/mnt/c/Windows/System32/wbem" "/mnt/c/Windows/System32/WindowsPowerShell/v1.0" "/mnt/c/Windows/System32/OpenSSH" "/mnt/c/Program Files/Calibre2" "/mnt/c/ProgramData/chocolatey/bin" "/mnt/c/Program Files/Git/cmd" "/mnt/c/Program Files/PuTTY" "/mnt/c/Program Files/MATLAB/R2018b/runtime/win64" "/mnt/c/Program Files/MATLAB/R2018b/bin" "/mnt/c/Program Files/MiKTeX 2.9/miktex/bin/x64" "/mnt/c/Program Files/nodejs" "/mnt/c/Program Files/Haskell Platform/8.6.5/mingw/bin" "/mnt/c/Users/nicho/AppData/Roaming/npm" "/mnt/c/Program Files (x86)/Wolfram Research/WolframScript" "/mnt/c/Users/nicho/AppData/Roaming/cabal/bin" "/mnt/c/Users/nicho/haskell-stack/bin" "/mnt/c/Users/nicho/Anaconda3/Scripts" "/mnt/c/Users/nicho/.cargo/bin" "/mnt/c/Users/nicho/AppData/Local/Microsoft/WindowsApps" "/mnt/c/Users/nicho/AppData/Local/Programs/Microsoft VS Code/bin" "/mnt/c/Users/nicho/AppData/Local/GitHubDesktop/bin" "/mnt/c/Users/nicho/AppData/Local/Microsoft/WindowsApps" "/mnt/c/Program Files/JetBrains/PyCharm Community Edition 2019.2.1/bin" "/mnt/c/Program Files (x86)/Java/jdk1.8.0_241/bin" "/mnt/c/Users/nicho/AppData/Local/hyper/app-3.0.2/resources/bin" "/usr/lib/x86_64-linux-gnu/emacs/26.3/x86_64-linux-gnu"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules "n/a")
  (packages (visual-regexp-steroids))
  (unpin "n/a")
  (elpa "htmlize")))
```

</pre></details>

**Comment by hlissner** [comment]
I am currently rewriting the good doctor. The new version already performs sanity checks on the user's private config. I'll let you know when it's done.

> One thing I'll note about my setup that may be a little unusual is that, from the perspective of Ubuntu, ~/.emacs.d/ and ~/.doom.d/ are both symlinked to a similar location on the Windows side so I can edit those files from either OS. Don't think that should matter but just in case. 

Do not do this. Emacs deploys byte-code to `~/.emacs.d/.local` that is _not_ cross-platform compatible. You're better off only sharing `~/.doom.d` across systems, and cloning separate `~/.emacs.d`'s to each machine.

**Comment by nicholas-miklaucic** [comment]
Thanks for the quick reply! Good to know it's already being worked on.

> Do not do this. Emacs deploys byte-code to ~/.emacs.d/.local that is not cross-platform compatible. You're better off only sharing ~/.doom.d across systems, and cloning separate ~/.emacs.d's to each machine.

To be clear, I'm not actually running Emacs on Windows. I just symlink it so I can see the files from Windows and (in cases like these where my Emacs stops working) edit them without using a terminal editor. It's easier to symlink than it is to look at files in a random hidden folder in my AppData. Good to know, though.

**Comment by hlissner** [comment]
I've moved this and many other issues to #4273. Please keep track of it there.
