### ISSUE TITLE
Org capture - Invalid file location

### ISSUE THREAD

**Issue by bondzula** [hlissner/doom-emacs#296]
Hello,
When i try to open org capture Todo template i get `Invalid file location: nil` error, while Notes template works perfectly fine, so i checked and you defined file paths in different ways

```
(setq org-default-notes-file (concat +org-dir "notes.org")
      org-capture-templates
      '(("t" "Todo" entry
         (file+headline (expand-file-name "todo.org" +org-dir) "Inbox")
         "* [ ] %?\n%i" :prepend t :kill-buffer t)

        '("n" "Notes" entry
         (file+headline org-default-notes-file "Inbox")
         "* %u %?\n%i" :prepend t :kill-buffer t)))

```
so i applied the method you use to define notes.org path on todo.org, and it works like a charm

and i have a question, i tried to change `+org-dir` in my private module with no success, what would be a correct way to do this?

**Comment by hlissner** [comment]
Alright, a fix for `Invalid file location: nil` is now in `develop`. I'll keep this issue open until it gets into `master`.

> i tried to change +org-dir in my private module with no success, what would be a correct way to do this?

The most reliable way to do this is to set it in your private module's init.el. `lang/org` won't overwrite variables that are already defined.

However, you _should_ be able to change `+org-dir` from your private module's config.el **if** org isn't loaded yet. Could you shed light on how exactly your attempts were unsuccessful?

**Comment by hlissner** [comment]
This is now in master. Feel free to reopen if your issue resurfaces.
