### ISSUE TITLE
void-variable org-directory

### ISSUE THREAD

**Issue by ineu** [hlissner/doom-emacs#2968]
**What did you expect to happen?**
Emacs starts as usual

**What actually happened?**
Emacs throws a `void-variable org-directory)` error.
According to `git bisect` the change is 
```
8c1525e3d80d6d8a5bafc7abf6a1ec9f423a3703 is the first bad commit
commit 8c1525e3d80d6d8a5bafc7abf6a1ec9f423a3703
Author: Henrik Lissner <henrik@lissner.net>
Date:   Sat Apr 25 01:27:25 2020 -0400

    Rewrite org-download/attach systems
```

**Additional details:**
That's what I get manually running `(require 'org)`
<details><pre>
Debugger entered--Lisp error: (void-variable org-directory)
  (list org-directory)
  (setq org-agenda-files (list org-directory))
  (if org-agenda-files nil (setq org-agenda-files (list org-directory)))
  +org-init-agenda-h()
  run-hooks(org-load-hook)
  byte-code("\300\301\302\"\210\303\304!\210\305\306!\207" [add-hook org-mode-hook #f(compiled-function () #<bytecode 0x28adbf9>) provide org run-hooks org-load-hook] 3)
  require(org)
  eval((require (quote org)) nil)
  #f(compiled-function (exp &optional insert-value no-truncate char-print-limit) "Evaluate EXP and print value in the echo area.\nWhen called interactively, read an Emacs Lisp expression and\nevaluate it.  Value is also consed on to front of the variable\n`values'.  Optional argument INSERT-VALUE non-nil (interactively,\nwith a non `-' prefix argument) means insert the result into the\ncurrent buffer instead of printing it in the echo area.\n\nNormally, this function truncates long output according to the\nvalue of the variables `eval-expression-print-length' and\n`eval-expression-print-level'.  When NO-TRUNCATE is\nnon-nil (interactively, with a prefix argument of zero), however,\nthere is no such truncation.\n\nIf the resulting value is an integer, and CHAR-PRINT-LIMIT is\nnon-nil (interactively, unless given a non-zero prefix argument)\nit will be printed in several additional formats (octal,\nhexadecimal, and character).  The character format is only used\nif the value is below CHAR-PRINT-LIMIT (interactively, if the\nprefix argument is -1 or the value doesn't exceed\n`eval-expression-print-maximum-character').\n\nRuns the hook `eval-expression-minibuffer-setup-hook' on entering the\nminibuffer.\n\nIf `eval-expression-debug-on-error' is non-nil, which is the default,\nthis command arranges for all errors to enter the debugger." (interactive #f(compiled-function () #<bytecode 0x22a5d9d>)) #<bytecode 0x1ce6e3>)((require (quote org)) nil nil 127)
  apply(#f(compiled-function (exp &optional insert-value no-truncate char-print-limit) "Evaluate EXP and print value in the echo area.\nWhen called interactively, read an Emacs Lisp expression and\nevaluate it.  Value is also consed on to front of the variable\n`values'.  Optional argument INSERT-VALUE non-nil (interactively,\nwith a non `-' prefix argument) means insert the result into the\ncurrent buffer instead of printing it in the echo area.\n\nNormally, this function truncates long output according to the\nvalue of the variables `eval-expression-print-length' and\n`eval-expression-print-level'.  When NO-TRUNCATE is\nnon-nil (interactively, with a prefix argument of zero), however,\nthere is no such truncation.\n\nIf the resulting value is an integer, and CHAR-PRINT-LIMIT is\nnon-nil (interactively, unless given a non-zero prefix argument)\nit will be printed in several additional formats (octal,\nhexadecimal, and character).  The character format is only used\nif the value is below CHAR-PRINT-LIMIT (interactively, if the\nprefix argument is -1 or the value doesn't exceed\n`eval-expression-print-maximum-character').\n\nRuns the hook `eval-expression-minibuffer-setup-hook' on entering the\nminibuffer.\n\nIf `eval-expression-debug-on-error' is non-nil, which is the default,\nthis command arranges for all errors to enter the debugger." (interactive #f(compiled-function () #<bytecode 0x2465aed>)) #<bytecode 0x1ce6e3>) ((require (quote org)) nil nil 127))
  eval-expression((require (quote org)) nil nil 127)
  funcall-interactively(eval-expression (require (quote org)) nil nil 127)
  call-interactively(eval-expression nil nil)
  command-execute(eval-expression)

</pre></details>

**Steps to reproduce:**
1. Select these example steps,
2. Delete them,
3. And replace them with precise steps to reproduce your issue.
4. Fill in "system information" below.

**System information:**
<details><pre>
((emacs
  (version . "26.3")
  (features . "XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2")
  (build . "авг 29, 2019")
  (buildopts "--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-modules 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD 30dea4bf0 2020-04-25 02:55:06 -0400")
  (dir . "~/.dotfiles/ineu/.doom.d/"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/usr/bin/zsh")
  (uname . "Linux 5.6.6-arch1-1 #1 SMP PREEMPT Tue, 21 Apr 2020 10:35:16 +0000 x86_64")
  (path "~/.gem/ruby/2.7.1/bin" "~/.rubies/ruby-2.7.1/lib/ruby/gems/2.7.0/bin" "~/.rubies/ruby-2.7.1/bin" "~/.bin" "~/.bin.local" "/usr/local/bin" "/usr/bin" "/bin" "/usr/local/sbin" "/usr/lib/jvm/default/bin" "/usr/bin/site_perl" "/usr/bin/vendor_perl" "/usr/bin/core_perl" "~/.antigen/bundles/robbyrussell/oh-my-zsh/lib" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/git" "~/.deliver/bin" "~/.local/bin" "~/.node_modules/bin" "~/.emacs.d/bin" "/usr/lib/emacs/26.3/x86_64-pc-linux-gnu"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard fill-column hydra modeline nav-flash ophints (popup +all +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold multiple-cursors snippets :emacs (dired +icons) electric ibuffer undo vc :term vterm :checkers syntax :tools (eval +overlay) lookup lsp magit :lang crystal data emacs-lisp (javascript +lsp) markdown org (ruby +rails +lsp +chruby) sh :config literate (default +bindings +smartparens))
  (packages (evil-lion) (org-mru-clock) (vimrc-mode) (org-cliplink) (org-journal) (haml-mode) (dockerfile-mode) (try) (rjsx-mode) (feature-mode) (jinja2-mode) (terraform-mode) (graphviz-dot-mode) (highlight-indent-guides) (counsel-jq) (tabbar) (typescript-mode) (rubocop :disable t))
  (unpin "n/a")
  (elpa "n/a")))

</pre></details>

**Comment by howsiwei** [comment]
I have also encountered this issue after upgrading.

**System information:**
<details><pre>
((emacs
  (version . "27.0.90")
  (features . "RSVG IMAGEMAGICK GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS JSON PDUMPER LCMS2 GMP")
  (build . "Apr 08, 2020")
  (buildopts "--disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus/HEAD-f451ef9/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus/HEAD-f451ef9 --with-xml2 --without-dbus --with-gnutls --with-imagemagick --with-json --with-modules --with-rsvg --with-ns --disable-ns-self-contained")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD 30dea4bf0 2020-04-25 02:55:06 -0400")
  (dir . "~/.config/doom/"))
 (system
  (type . darwin)
  (config . "x86_64-apple-darwin19.4.0")
  (shell . "/usr/local/bin/zsh")
  (uname . "Darwin 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64")
  (path "/usr/local/miniconda3/bin" "/usr/local/miniconda3/condabin" "~/.opam/default/bin" "~/.cargo/bin" "~/perl5/bin" "/usr/local/bin" "/usr/bin" "/bin" "/usr/sbin" "/sbin" "/Library/TeX/texbin" "/opt/X11/bin" "/Applications/Wireshark.app/Contents/MacOS" "~/bin" "~/sbin" "~/.local/bin" "/usr/local/sbin" "/usr/local/Cellar/emacs-plus/HEAD-f451ef9/libexec/emacs/27.0.90/x86_64-apple-darwin19.4.0"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company ivy :ui doom-dashboard hl-todo hydra modeline (popup +all +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold format multiple-cursors rotate-text snippets word-wrap :emacs dired electric ibuffer (undo +tree) vc :term shell :checkers syntax spell grammar :tools (eval +overlay) lookup lsp macos magit make pdf :lang (agda +local) (cc +lsp) coq data emacs-lisp (haskell +dante) javascript (latex +latexmk) lua markdown ocaml (org +pandoc) (python +conda +cython +lsp) (rust +lsp) sh web :config (default +bindings +smartparens))
  (packages (solarized-theme) (pdf-view-restore) (graphviz-dot-mode) (rmsbolt) (web-beautify))
  (unpin "n/a")
  (elpa "n/a")))
</pre></details>

A workaround is to add the following line to `~/.config/doom/config.el`.
```emacs-lisp
(setq org-directory "~/org")
```

**Comment by hlissner** [comment]
As of 6cb1390 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
