### ISSUE TITLE
Toggling popup window makes it smaller

### ISSUE THREAD

**Issue by amosbird** [hlissner/doom-emacs#298]
It keeps shrinking when toggling on and off.

**Comment by hlissner** [comment]
You mean when you use `doom/popup-toggle`? And you mean it becomes smaller each time you toggle it? Or it becomes smaller the first time and stays at its new size?

**Comment by amosbird** [comment]
Hi, it becomes smaller each time when toggling

**Comment by hlissner** [comment]
Is this still an issue with the new popup system?

**Comment by amosbird** [comment]
Hmm, `+popup/toggle` only brings up the `*Message*` buffer and doesn't toggle it. It also ignores other popup windows.

**Comment by hlissner** [comment]
I've reverted a change that may have broken `+popup/toggle`, which _should_ resolve your issue. Please update and give it a try.

**Comment by amosbird** [comment]
Thanks! It works fine now.
