### ISSUE TITLE
Flashing when scrolling

### ISSUE THREAD

**Issue by piotrek-szczygiel** [hlissner/doom-emacs#2989]
When using Ctrl+D and Ctrl+U to scroll there is a visible flash for maybe like one frame. It looks like a little darker background color flash. It is especially visible, when i set my line numbering to relative and use 'j' and 'k' to scroll.

Short example of how it looks: https://i.imgur.com/Q97YQtA.mp4

I'm on the Windows 10, and didn't change anything beside the font in the configuration.
Emacs installed from here https://alpha.gnu.org/gnu/emacs/pretest/windows/emacs-27/emacs-27.0.91-x86_64-installer.exe

**Comment by hlissner** [comment]
I cannot reproduce this on Linux or macOS, so I assume it's a windows issue.

You could try adding this to `~/.doom.d/config.el`:

```elisp
(add-to-list 'default-frame-alist '(inhibit-double-buffering . t))
```

**Comment by Solver42** [comment]
I have a similar issue. Also more severe when numbers are relative. I run Gardu Linux, Alacritty and emacs-nox.

**Comment by hlissner** [comment]
Because I can't reproduce this, no new leads have come up in nearly a year, and I have little reason to suspect this is a Doom issue (more likely a Emacs issue), I will close this. Feel free to create another issue if you have reason to believe otherwise.
