### ISSUE TITLE
Couldn't `(switch-to-buffer nil)` because of a hook

### ISSUE THREAD

**Issue by sarg** [hlissner/doom-emacs#2992]
**What did you expect to happen?**
`(switch-to-buffer nil)` should switch to `(other-buffer)` as per documentation.

**What actually happened?**
`eq: Wrong type argument: stringp, nil` thrown by `get-buffer` [here](https://github.com/hlissner/doom-emacs/blob/82f9dc2566b00d10adacba8de60892e37ab11940/core/core-ui.el#L108)

**Comment by hlissner** [comment]
As of 6e8487e this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by sarg** [comment]
Hm, it's not working for me. This condition evals to false: `(eq orig-fn #'switch-to-buffer)`
Maybe it's because the function has other advices?

Anyway, do you really need to do `(eq (current-buffer) (other-buffer)`, I've fixed it with `(and buffer-or-name (eq (current-buffer) (get-buffer buffer-or-name)))` and it works for me.

**Comment by hlissner** [comment]
> Anyway, do you really need to do (eq (current-buffer) (other-buffer)

Huh, on closer inspection I suppose not. My bad.

I've removed the change in c96bbf9. Let me know if the issue persists and I'll reopen this.
