### ISSUE TITLE
pretty-code breaks statusline file modification indicator

### ISSUE THREAD

**Issue by MageJohn** [hlissner/doom-emacs#2995]
**What did you expect to happen?**
Code ligatures to only replace the correct symbols in code.

**What actually happened?**
The floppy icon on the status line indicating that the file was modified is replaced with an arrow when pretty-code is enabled (tested with +fira and +iosevka).

This seems to be because the symbolic fonts used for the ligatures and the floppy disk icon have overlapping unicode codepoints. If this is the case then it's likely that other symbols are also broken, but I haven't found them yet.

**Additional details:**
A screenshot of the issue
![A screenshot of the issue](https://user-images.githubusercontent.com/3520558/80536154-d680fa80-8999-11ea-94ec-bf42764006e9.png)

**Steps to reproduce:**
1. Enable pretty-code, with `+fira` or `+iosevka` (other fonts may have the same issue or similar ones).
2. Call `doom sync` and restart Emacs.
3. Install the symbolic fonts using `M-x +pretty-code/install-patched-font`. (Note that the links for `+fira` seem to be out of date; I'll open another issue for this. Use `+iosevka` or one of the others if it doesn't work) 
4. Open a file and make a change so the buffer becomes modified.

**System information:**
<details><pre>
emacs   version    27.0.91
        features   XPM JPEG TIFF GIF PNG RSVG SOUND GPM DBUS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP
        build      Apr 23, 2020
        buildopts  (--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-gameuser=root:games --with-x-toolkit=gtk3 --with-xft --with-modules --without-compress-install --without-gsettings --without-gconf 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now)
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop efa599f07 2020-04-23 13:08:08 -0400
        dir        ~/.config/doom/
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/bash
        uname      Linux 5.4.35-1-MANJARO #1 SMP PREEMPT Thu Apr 23 10:54:43 UTC 2020 x86_64
        path       (~/.cabal/bin ~/.ghcup/bin ~/.local/bin ~/.config/emacs/bin ~/.local/bin /usr/local/bin /usr/bin /bin /usr/local/sbin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /var/lib/snapd/snap/bin ~/.gem/ruby/2.7.0/bin /usr/lib/emacs/27.0.91/x86_64-pc-linux-gnu/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash neotree ophints (popup +defaults) (pretty-code +fira) vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold (format +onsave) rotate-text snippets word-wrap :emacs dired electric vc :term vterm :checkers syntax spell :tools editorconfig (eval +overlay) lookup lsp magit make pdf :lang (cc +lsp) data emacs-lisp (haskell +dante) (kotlin +lsp) (latex +cdlatex) markdown (org +dragndrop +present) (python +lsp) (rust +lsp) sh zig adoc :config (default +bindings +smartparens))
        packages   ((pkgbuild-mode))
        unpin      (n/a)
        elpa       (n/a)
</pre></details>

**Comment by hlissner** [comment]
This is due to a conflict between all-the-icons and the fira code ligature mappings. There's no good fix for this. Either the ligature uses lose a ligature, or the doom-modeline users lose an icon, so I've decided the former. bd58f0a should fix the issue. Let me know if that isn't the case and I'll reopen it.

Though, I anticipate a bug report one day complaining about the missing ligature. I can only pray a better solution arises in later versions of Emacs.

**Comment by hlissner** [comment]
I think I found a solution in c25f88c87 that resolves this conflict. Please update and let me know if it works.

**Comment by MageJohn** [comment]
It's working for me! I've got a save icon as well as being able to produce the ligature seen replacing it in my screenshot above. 

Thanks for fixing this, and so quickly too!
