### ISSUE TITLE
orgmode very slow with this kind of files (rss feeds)

### ISSUE THREAD

**Issue by luogni** [hlissner/doom-emacs#2998]
**What did you expect to happen?**
It should be fast to tab/cut nodes. I tried with `emacs -q` and it's very fast.

**What actually happened?**
org-cut-subtree or even cycle visibility of some nodes can take 10 seconds. I'm on a core i5 with 8GB of ram.

**Steps to reproduce:**
1. Launch `emacs feeds.org`
2. Wait lots of seconds
3. try to tab on a node
4. Wait lots of seconds

**System information:**
<details><pre>
 ./.emacs.d/bin/doom info
((emacs
  (version . "26.3")
  (features . "XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2")
  (build . "ago 29, 2019")
  (buildopts "--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-modules 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD 3a5ef316f 2020-04-19 22:04:12 -0400")
  (dir . "~/.doom.d/"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/bin/bash")
  (uname . "Linux 5.6.6-arch1-1 #1 SMP PREEMPT Tue, 21 Apr 2020 10:35:16 +0000 x86_64")
  (path "~/.cargo/bin" "~/.local/bin" "/usr/local/sbin" "/usr/local/bin" "/usr/bin" "/usr/bin/site_perl" "/usr/bin/vendor_perl" "/usr/bin/core_perl" "/usr/lib/emacs/26.3/x86_64-pc-linux-gnu"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor file-templates fold snippets :emacs dired electric vc :checkers syntax :tools docker ein (eval +overlay) lookup lsp magit :lang (cc +lsp) data emacs-lisp lua markdown (org +dragndrop +present) (python +lsp) rust sh :email mu4e :app (rss +org) :config (default +bindings +smartparens))
  (packages (pocket-reader) (theme-magic))
  (unpin "n/a")
  (elpa "n/a")))
</pre></details>

[Org file](http://178.62.192.206/feeds.org)

**Comment by hlissner** [comment]
Can't reproduce this. Please provide an example org file.

**Comment by hlissner** [comment]
This appears to be caused by `org-highlight-latex-and-related`, which performs some expensive fontification on the buffer. Try adding this to `~/.doom.d/config.el`:

```elisp
(after! org
  (setq org-highlight-latex-and-related nil))
```

**Comment by luogni** [comment]
yes thanks it's way faster now!

**Comment by hlissner** [comment]
As of f28a972 I've set org-highlight-latex-and-related to nil by default. Thanks for bringing it to my attention!
