### ISSUE TITLE
From Prelude to DOOM

### ISSUE THREAD

**Issue by Gahamelas** [hlissner/doom-emacs#2999]
I'd like to install DOOM having currently a Prelude installation.
How would this change my keybindings, etc.? 
Can I remove easily without any disturbance to my previous Prelude instalation?
Thank you, 
GM

**Comment by hlissner** [comment]
Hi! Welcome to Doom. I'm sorry, but this is a very general and vague question. Please narrow down its scope (or [join our discord](https://discord.gg/qvGgnVx) -- perhaps you'll find other ex-prelude users).

Here are some FAQ answers that I hope serve as a starting point:

1. [How do I bind my own keys (or change existing ones)?](https://github.com/hlissner/doom-emacs/blob/develop/docs/faq.org#how-do-i-bind-my-own-keys-or-change-existing-ones)
2a. See [config/default/+evil-bindings.el](https://github.com/hlissner/doom-emacs/blob/develop/modules/config/default/+evil-bindings.el) for our keybinds for evil users.
2b. See [config/default/+emacs-bindings](https://github.com/hlissner/doom-emacs/blob/develop/modules/config/default/%2Bemacs-bindings.el) for our non-evil keybinds.
3. You can disable most of doom's keybinds by disabling the `:config (default +binding)` module. [See the Modules section of the documentation](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#modules) to learn how to do that.
4. [The getting start guide](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org) is a good place to start to figure out how to install, configure and maintain a doom config.

Hope that helps.
