### ISSUE TITLE
Unable to search notes within org-directory

### ISSUE THREAD

**Issue by benmezger** [hlissner/doom-emacs#3004]
**What did you expect to happen?**
`SPC n s` should open `rg` within the `org-directory`

**What actually happened?**

If within a known projectile project, it opens `rg` within the root of the project, if not within a known project, it prompts of the project directory.

**Additional details:**

 The affected functions seems to correctly set org's directory, but I haven't had time to investigate `+default/search-project-for-symbol-at-point`.

In my understanding, when searching for a note, it should grep within the setup org-directory and if not available, then prompt for a project, correct?

- Include a link to your private config
https://github.com/benmezger/dotfiles/tree/master/doom-emacs/.doom.d

**System information:**
<details>

```
emacs   version    26.3
        features   JPEG RSVG IMAGEMAGICK GLIB NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2
        build      Nov 17, 2019
        buildopts  (--disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus/26.3/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus/26.3 --with-xml2 --without-dbus --with-gnutls --with-imagemagick --with-modules --with-rsvg --with-ns --disable-ns-self-contained)
        windowsys  ns
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> refs/heads/develop 82f9dc256 2020-04-27 17:43:29 -0400
        dir        ~/dotfiles/doom-emacs/.doom.d/
system  type       darwin
        config     x86_64-apple-darwin19.0.0
        shell      /usr/local/bin/zsh
        uname      Darwin 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64
        path       (~/.pyenv/plugins/pyenv-virtualenv/shims ~/.pyenv/shims ~/.pyenv/plugins/pyenv-virtualenv/shims ~/.pyenv/shims ~/.cargo/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /usr/local/share/dotnet /opt/X11/bin ~/.dotnet/tools /Applications/Postgres.app/Contents/Versions/latest/bin ~/.pyenv/bin ~/.rbenv/shims ~/.rbenv/bin ~/.pyenv/plugins/pyenv-virtualenv/shims ~/.pyenv/shims ~/.cargo/bin /Applications/kitty.app/Contents/MacOS ~/.bin ~/workspace/go/bin /usr/local/opt/go/libexec/bin /usr/local/Cellar/emacs-plus/26.3/libexec/emacs/26.3/x86_64-apple-darwin19.0.0/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion (company +auto +tng) (ivy +fuzzy +icons) :ui deft doom doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates (format +onsave) rotate-text snippets :emacs dired electric ibuffer vc :term eshell :checkers syntax :tools editorconfig (eval +overlay) (lookup +docsets) lsp macos magit make terraform :lang (cc +lsp) data emacs-lisp (go +lsp) markdown (org +hugo +gnuplot +pancoc +dragndrop) (python +lsp +pyenv) rest (sh +lsp) :app (rss +org) :config (default +bindings +smartparens))
        packages   ((pyenv-mode-auto) (wakatime-mode))
        unpin      (n/a)
        elpa       (n/a)
```
</details>

**Comment by Wetlize** [comment]
Can confirm, `+default/search-other-project` is broken too, at least with Ivy.

I've tried to debug this, since `SPC s P` is crucial in my workflow, and it and it looks like `+ivy-file-search` prioritizes all the time the currently active project over the one which gets let-bound from the `default-directory` [here](https://github.com/hlissner/doom-emacs/blob/c25f88c874f652ac4d6e873e3f1754def7a2c8bd/modules/completion/ivy/autoload/ivy.el#L251). Not sure if this the source of the problem though.

**Comment by hlissner** [comment]
As of ba8892d this issue should be resolved. It was a regression caused by an optimization introduced in 9acba6b26. 

Let me know if the issue persists and I'll reopen it. Thanks for bringing it to my attention!

**Comment by benmezger** [comment]
@hlissner this fixed on my side. Thank you!
