### ISSUE TITLE
Completion not working in eshell

### ISSUE THREAD

**Issue by teu5us** [hlissner/doom-emacs#3007]
**What did you expect to happen?**

Pressing `TAB` in eshell after `find-file ` or `e ` should give completions.

**What actually happened?**

Emacs outputs `Wrong type argument: stringp, nil` to the message area.

**Additional details:**

The described behaviour is seen with:

- my doom configuration;
- fresh doom with only eshell added.

Completion works with `emacs -Q`.

<details><pre>
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  string-match("\n" nil 0)
  split-string(nil "\n" t)
  fish-completion--list-completions("find-file ")
  #f(compiled-function () #<bytecode 0x1de3829>)()
  pcomplete--here(#f(compiled-function () #<bytecode 0x1de3829>) nil nil nil)
  fish-completion-complete("find-file ")
  fish-completion-shell-complete()
  pcomplete-completions()
  pcomplete(1)
  funcall-interactively(pcomplete 1)
  call-interactively(pcomplete)
  eshell-pcomplete(1)
  funcall-interactively(eshell-pcomplete 1)
  call-interactively(eshell-pcomplete nil nil)
  command-execute(eshell-pcomplete)
</pre></details>

**Steps to reproduce:**
1. Run eshell with `M-x eshell` or `SPC o e`
2. Type `find-file ` or `e ` and press `TAB`

**System information:**
<details><pre>
emacs   version    26.3
        features   XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD
        build      Apr 30, 2020
        buildopts  (--prefix=/nix/store/25gxv9zlq4c3z2hhzr2h2dmy8m2gj4n3-emacs-26.3 --disable-build-details --with-modules --with-x-toolkit=gtk3 --with-xft CFLAGS=-DMAC_OS_X_VERSION_MAX_ALLOWED=101200)
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop, origin/develop, origin/HEAD 079b74821 2020-04-29 18:32:25 -0400
        dir        ~/.doom.d/
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /run/current-system/sw/bin/zsh
        uname      Linux 5.4.35 #1-NixOS SMP Thu Apr 23 08:36:46 UTC 2020 x86_64
        path       (/run/wrappers/bin ~/.nix-profile/bin /etc/profiles/per-user/paul/bin /nix/var/nix/profiles/default/bin /run/current-system/sw/bin ~/.config/zsh/plugins/sfz ~/.config/zsh/plugins/zsh-autosuggestions ~/.config/zsh/plugins/fast-syntax-highlighting ~/.local/bin/office ~/.local/bin/dictionary ~/.local/bin/wmcmds ~/.local/bin/tools ~/.local/bin/ ~/.racket/7.3/bin/
 /nix/store/25gxv9zlq4c3z2hhzr2h2dmy8m2gj4n3-emacs-26.3/libexec/emacs/26.3/x86_64-pc-linux-gnu/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline ophints (popup +defaults) vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold snippets :emacs dired electric undo vc :term eshell :checkers syntax :tools (eval +overlay) lookup magit :lang emacs-lisp markdown org sh :config (default +bindings +smartparens))
        packages   (n/a)
        unpin      (n/a)
        elpa       (yasnippet yaml-mode xterm-color with-editor websocket web-mode web-completion-data w3m vterm-toggle vterm volatile-highlights visual-fill-column vimish-fold vi-tilde-fringe undo-tree treepy treemacs-projectile treemacs-persp treemacs-magit treemacs-evil treemacs transient tramp toc-org tco tablist sws-mode swiper-helm swiper stylus-mode spinner solaire-mode slim-mode shut-up shrink-path seq scribble-mode sass-mode s rustic reverse-im reformatter ranger rainbow-mode racket-mode quickrun pyvenv pythonic python-pytest pyimport py-isort pug-mode protobuf-mode projectile prescient posframe popup pkg-info pipenv pip-requirements pfuture persp-mode pdf-tools pcre2el parent-mode paredit-menu paredit-everywhere paredit ox-pandoc overseer orgit org-plus-contrib org-pdfview org-download org-cliplink org-bullets org-bookmark-heading org ob-translate ob-async nov nose nixos-options nix-update nix-mode nav-flash names multitran mu4e-maildirs-extension memoize math-symbol-lists markdown-toc markdown-mode magit-todos magit-popup magit-gitflow magit macrostep lv lsp-ui lsp-python-ms lsp-mode lsp-haskell let-alist latex-preview-pane kurecolor jsonnet-mode json-snatcher json-reformat json-mode ivy iedit ibuffer-vc ibuffer-projectile hydra htmlize ht hl-todo hl-fill-column highlight-quoted helm-xref helm-rg helm-projectile helm-org helm-nixos-options helm-flx helm-describe-modes helm-dash helm-css-scss helm-core helm-company helm-c-yasnippet helm-ag-r helm-ag helm haskell-mode haml-mode graphql-mode goto-chg google-translate gnuplot-mode gnuplot gitignore-mode github-review gitconfig-mode git-timemachine git-gutter-fringe git-gutter git-commit ghub geiser fringe-helper format-all forge flyspell-lazy flyspell-correct-helm flyspell-correct flycheck-posframe flycheck-popup-tip flycheck-elm flycheck-cask flycheck flx fd-dired faceup f expand-region exato evil-visualstar evil-vimish-fold evil-textobj-anyblock evil-surround evil-snipe evil-paredit evil-org evil-numbers evil-nerd-commenter evil-multiedit evil-mc evil-magit evil-lion evil-indent-plus evil-goggles evil-exchange evil-embrace evil-easymotion evil-collection evil-args evil-anzu evil esxml eshell-z eshell-up eshell-toggle eshell-prompt-extras eshell-git-prompt eshell-fringe-status eshell-fixed-prompt eshell-did-you-mean eshell-bookmark eshell-autojump equake epl emms emmet-mode embrace emacsql-sqlite emacsql elm-mode elisp-demos elisp-def dumb-jump doom-themes doom-modeline dockerfile-mode docker-tramp docker direnv diredfl dired-rsync diff-hl dhall-mode deft dash-functional dash-docs dash csv-mode company-web company-shell company-reftex company-prescient company-nixos-options company-math company-dict company-box company-auctex company closql cdlatex buttercup browse-at-remote avy auto-yasnippet auctex-latexmk auctex atomic-chrome async anzu annalist anaconda-mode all-the-icons-dired all-the-icons adaptive-wrap ace-window)
</pre></details>

**Comment by teu5us** [comment]
I guess I missed the commit in which fish completion was added. I get completion after installing fish itself, but it isn't as convenient as before with company. Can I use eshell as before fish was introduced?

**Comment by teu5us** [comment]
For some reason `:init (setq fish-completion-fallback-on-bash-p t)` in eshell module config had no effect and completion did not work without fish anyway.

**Comment by teu5us** [comment]
It seems we can actually have both company and fish, it seems to work for me. Unfortunately, I can't get directories expanded anymore (`D/co/ra` to `Documents/code/racket`, for example) even with company-only, while it used to work before.

**Comment by polaris64** [comment]
`fish-completion-mode` gets added to `eshell-mode-hook` on the following line: https://github.com/hlissner/doom-emacs/blob/7cf2109b1a0ca43f2a8567db1da0c426477c6cab/modules/term/eshell/config.el#L177

From what I can tell, the advice added just below this causes `fish-completion--list-completions-with-desc` to return `nil` when the "fish" executable doesn't exist.  The result of this function is used directly as an argument to `split-string` and subsequently `string-match` which is generating the error as it is expecting a string rather than `nil`.

I'm assuming that this advice should handle the case where "fish" isn't found, perhaps deferring to `bash-completion`?

If I disable the `fish-completion-mode` minor mode for the Eshell buffer, file and directory completions work fine.

**Comment by hlissner** [comment]
Thanks @polaris64 for zeroing in on the cause. As of 1529dca this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by polaris64** [comment]
No problem :)

Alternatively, I was looking at the `fish-completion` functions.  `fish-completion--list-completions` uses `fish-completion--list-completions-with-desc` and expects the latter to return a string, which is where this problem originated. However, the former function is allowed to return an empty list as `fish-completion-complete` (the function calling it) explicitly checks for this case and falls back to bash completion otherwise.  So, if the advice was kept the same as before but instead changed to advise `fish-completion--list-completions` then returning `nil` if "fish" is not found would be correct behaviour.

I'm not sure which is cleanest, so I'll leave that up to you, but I just wanted to let you know that this option also appears to follow a nice clean path too.
