### ISSUE TITLE
cider-eval-sexp-at-point evals wrong expression

### ISSUE THREAD

**Issue by Rende11** [hlissner/doom-emacs#3009]
**What did you expect to happen?**
When I stand on opening bracket of nested expression and use ```cider-eval-sexp-at-point```
Expression should eval.

**What actually happened?**
It evals external expression.

**Additional details:**
<img width="316" alt="Screenshot 2020-04-30 18 02 26" src="https://user-images.githubusercontent.com/10757633/80720456-f89b8980-8b0d-11ea-986b-f85e526d43ba.png">

But if I move closing bracket to new line it's works correctly!
<img width="173" alt="Screenshot 2020-04-30 18 11 35" src="https://user-images.githubusercontent.com/10757633/80720513-0ea94a00-8b0e-11ea-9509-a9c1d1281c13.png">

**Steps to reproduce:**
1. Write expression like on screen
2. Evaluate nested expression with `cider-eval-sexp-at-point`

**Comment by hlissner** [comment]
This seems like an [upstream](https://github.com/clojure-emacs/cider) issue. To verify, try reproducing this in the vanilla Emacs [using the sandbox](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#testing-in-dooms-sandbox), perhaps with something like:

```elisp
(require 'clojure-mode)
(require 'cider)
(find-file "~/test.clj")
(cider-mode +1)
```

Then try `M-x cider-eval-sexp-at-point` on that code in the new instance of Emacs.

**Comment by Rende11** [comment]
<img width="602" alt="Screenshot 2020-05-02 12 45 00" src="https://user-images.githubusercontent.com/10757633/80859553-f737a180-8c72-11ea-8c15-71641dfa5d1a.png">

I used hot-key `C-c C-v v`

**Comment by hlissner** [comment]
It turns out this is an "issue" with [these lines in evil-collection-cider](https://github.com/emacs-evil/evil-collection/blob/master/modes/cider/evil-collection-cider.el#L86-L90). They modify `cider-eval-last-sexp` et co to fix an off-by-one issue with how evil sees regions.

I'm not really certain if this was intended or not, but try filing the report with them.

A simple workaround:

```elisp
(after! cider
  (advice-remove 'cider-eval-last-sexp 'evil-collection-cider-last-sexp)
  (advice-remove 'cider-eval-last-sexp-and-replace 'evil-collection-cider-last-sexp)
  (advice-remove 'cider-eval-last-sexp-to-repl 'evil-collection-cider-last-sexp))
```

**Comment by Rende11** [comment]
Thx, this workaround works!
