### ISSUE TITLE
develop: Error if Fira font is missing

### ISSUE THREAD

**Issue by ocharles** [hlissner/doom-emacs#301]
On startup on `develop` I get:

```
Error (doom-ui): Failed to set fonts because Font not available: #<font-spec nil nil Fira\ Sans nil nil nil nil nil nil nil nil nil nil>
```

This is coming from your private layer I think, which is enabled by default. Maybe worth adding a check around this?

**Comment by hlissner** [comment]
This was _sort of_ intended, but I've done you one better: `private/hlissner` has been [moved to an external repo](https://github.com/hlissner/doom-emacs-private), and has been replaced with `private/default`, which provides a few reasonable defaults that should work out of the box.

This is in `develop` for now, but should make it into `master` sometime between Christmas and the new years. I'll leave this issue open until then.

**Comment by ocharles** [comment]
Sounds like a good move! I did at one point turn your module off, but that turns off *too much* - your module is actually a great set of default

**Comment by hlissner** [comment]
This is now in master.
