### ISSUE TITLE
eamcs can't find company-box.

### ISSUE THREAD

**Issue by TravisCao** [hlissner/doom-emacs#3018]
**What did you expect to happen?**
...
After add (+childframe) to : completion company, (I didn't add extra config of company-box) it should work fine. 

**What actually happened?**
...
Emacs shows (file missing cannot open load file No such file or directory company-box)
.
![image](https://user-images.githubusercontent.com/35266867/80785621-7bc2eb00-8bb3-11ea-8e4f-f172e5892194.png)
![image](https://user-images.githubusercontent.com/35266867/80785648-8d0bf780-8bb3-11ea-8d06-a8895316c70e.png)

![image](https://user-images.githubusercontent.com/35266867/80785702-bfb5f000-8bb3-11ea-9374-9ecdb8bfe2bd.png)

**Additional details:**
- Include a link to your private config
- Include screenshots/casts of your issue
- If you mention key sequences, include what commands they're bound to (use `SPC
  h k KEY` or `C-h h k KEY` to inspect keys).
- Include any warnings or errors logged to \*Messages\* (use `M-x
  view-echo-area-messages` to see it).

<details><pre>
If an error message is involved include a backtrace of it.

How to acquire a backtrace:
https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#how-to-extract-a-backtrace-from-an-error
</pre></details>

**Steps to reproduce:**
1. Select these example steps,
2. Delete them,
3. And replace them with precise steps to reproduce your issue.
4. Fill in "system information" below.
- System information
   - System: macOS Catalina 10.15.2 
   - Emacs: 26.3 installed by Homebrew
![image](https://user-images.githubusercontent.com/35266867/80785837-3521c080-8bb4-11ea-9e8e-8a6a8ecd7380.png)

**System information:**
<details><pre>
Place the output of `M-x doom/info` or `~/.emacs.d/bin/doom info` here.
</pre></details>

**Comment by hlissner** [comment]
1. Did you remember to run `doom sync`?
2. If you did, does https://github.com/hlissner/doom-emacs/issues/2802#issuecomment-606654151 fix your issue?
3. If not, does https://github.com/hlissner/doom-emacs/issues/2937#issuecomment-616211870 ?

**Comment by TravisCao** [comment]
OK. #2802 fix. Thx!

**Comment by sillygeniuss** [comment]
hi, @hlissner I have use the two ways you mentioned below, but i still trigger the error message.
![image](https://user-images.githubusercontent.com/59204202/90269731-ae0b0680-de8b-11ea-9fff-d19f2e504cc4.png)

**Comment by hlissner** [comment]
@sillygeniuss Include your `M-x doom/info`

**Comment by sillygeniuss** [comment]
> @sillygeniuss Include your `M-x doom/info`

![image](https://user-images.githubusercontent.com/59204202/90270351-a7c95a00-de8c-11ea-8484-37e7666606f6.png)

**Comment by sillygeniuss** [comment]
> @sillygeniuss Include your `M-x doom/info`

@hlissner Here: 
![image](https://user-images.githubusercontent.com/59204202/90270510-e9f29b80-de8c-11ea-9013-fd32f419371f.png)

**Comment by hlissner** [comment]
@sillygeniuss You do not have `:completion (company +childframe)` enabled, so naturally, `company-box` is not installed. Enable `+childframe`, run `doom sync` and restart Emacs.

**Comment by sillygeniuss** [comment]
> @sillygeniuss You do not have `:completion (company +childframe)` enabled, so naturally, `company-box` is not installed. [Enable](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#modules) `+childframe`, run `doom sync` and restart Emacs.

it seems no use😭
![image](https://user-images.githubusercontent.com/59204202/90272219-ad746f00-de8f-11ea-89a1-8925fb465bf7.png)

**Comment by hlissner** [comment]
@sillygeniuss Remove the `(package! company-box)` you added to `~/.doom.d/packages.el`, then delete the `~/.emacs.d/.local/straight/repos/company-box` directory, and run `doom sync`.

**Comment by sillygeniuss** [comment]
> @sillygeniuss Remove the `(package! company-box)` you added to `~/.doom.d/packages.el`, then delete the `~/.emacs.d/.local/straight/repos/company-box` directory, and run `doom sync`.

i did as u said, but the emacs will auto install the `company-box` when startup, and print the message "Cannot open load file..."
![image](https://user-images.githubusercontent.com/59204202/90273544-b49c7c80-de91-11ea-9c50-4eab9f26c5c5.png)

**Comment by hlissner** [comment]
@sillygeniuss Then the problem is in your config. Please move this to [our Discord](https://discord.gg/qvGgnVx).
