### ISSUE TITLE
Recent upgrade broke fira code ligatures

### ISSUE THREAD

**Issue by bshankar** [hlissner/doom-emacs#3019]
after I ran `doom upgrade` yesterday. Here's a sample before and after enabling `prettify-symbols-mode`

**Before**
![image](https://user-images.githubusercontent.com/1161104/80788447-c38f4580-8ba6-11ea-92bb-eda29e93efc7.png)

**After**
![image](https://user-images.githubusercontent.com/1161104/80788770-a9099c00-8ba7-11ea-9bed-998b0e45513e.png)

**Additional details:**
- I have `(pretty-code +fira)` in `~/.doom.d/init.el`

**System information:**
<details><pre>
((emacs
  (version . "26.3")
  (features . "XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2")
  (build . "Aug 30, 2019")
  (buildopts "--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-modules 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop 504d1388c 2020-05-01 01:22:14 -0400")
  (dir . "~/.doom.d/"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/usr/bin/fish")
  (uname . "Linux 5.6.8-arch1-1 #1 SMP PREEMPT Wed, 29 Apr 2020 16:22:56 +0000 x86_64")
  (path "~/path/name" "~/.emacs.d/bin" "~/.cargo/bin" "/usr/local/sbin" "/usr/local/bin" "/usr/bin" "/usr/bin/site_perl" "/usr/bin/vendor_perl" "/usr/bin/core_perl" "/usr/lib/emacs/26.3/x86_64-pc-linux-gnu"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company ivy :ui doom-dashboard doom-quit hl-todo modeline ophints (popup +defaults) (pretty-code +fira) vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold (format +onsave) snippets :emacs dired electric undo vc :term vterm :checkers syntax :tools (eval +overlay) lookup lsp magit :lang emacs-lisp json (javascript +lsp) org rest (rust +lsp) web :config (default +bindings +smartparens))
  (packages (chocolate-theme) (org-super-agenda))
  (unpin "n/a")
  (elpa "n/a")))

</pre></details>

**Comment by hlissner** [comment]
Are you using the patched font or Fira Code through your OS package manager? Could you try using the other? I've installed Fira Code and Fira Code Symbols through my package manager, without the patched fonts installed by `M-x +pretty-code/install-patched-font` and it appears to work out of the box:

![image](https://user-images.githubusercontent.com/510883/80789443-0119b180-8b5a-11ea-8e6e-865b8cb9bf4f.png)

**Comment by bshankar** [comment]
I use the `Fantasque sans mono` font with the ligatures of `Fira code` from the patched font. If I just switch to the Fira Code font the ligatures work.

**Comment by bp41** [comment]
@bshankar 
I had the exact same issue with `Fantasque Sans Mono`

I've built Emacs 28 from git, based on a recommendation in the [doom pretty-code docs](https://github.com/hlissner/doom-emacs/tree/develop/modules/ui/pretty-code#emacs-mac-port-or-emacs-28), removed `+fira` flag from `init.el` and my ligatures now work again.

**Comment by bshankar** [comment]
@bp41 Thanks! that worked. 

I could also get it working with emacs 26 and `+fira` by downgrading `Fantasque Sans Mono` to 1.7.
