### ISSUE TITLE
Project root won't be guessed correctly

### ISSUE THREAD

**Issue by sei40kr** [hlissner/doom-emacs#3024]
```
+ project/
  - .git/
  + simple-project/
    - Cargo.toml
    + src/
      - main.rs
```

**What did you expect to happen?**

`projectile-project-root` in `main.rs` should be `/project/simple-project`

**What actually happened?**

`projectile-project-root` in `main.rs` is `/project`. `Cargo.toml` is ignored as well as `package.json`, `pom.xml`, and so on.

**Additional details:**

For me, this solved the problem:

```emacs-lisp
(add-to-list 'projectile-project-root-files-bottom-up "Cargo.toml")
```

(we need to restart Emacs to clear the cache for project roots)

**Steps to reproduce:**
1. Create a Git repository on local
2. Create a Cargo project under a subdirectory (`cargo init simple-project`)
3. Run `(projectile-project-root)` in the project.

**System information:**
<details><pre>
((emacs
  (version . "27.0.60")
  (features . "RSVG IMAGEMAGICK GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS XWIDGETS PDUMPER LCMS2 GMP")
  (build . "Feb 23, 2020")
  (buildopts "--disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus/HEAD-693749c/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus/HEAD-693749c --with-xml2 --without-dbus --with-gnutls --with-imagemagick --with-modules --with-rsvg --with-xwidgets --with-ns --disable-ns-self-contained")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, upstream/develop, origin/develop, origin/HEAD 0edbf9cb0 2020-05-02 22:49:07 -0400")
  (dir . "~/.doom.d/"))
 (system
  (type . darwin)
  (config . "x86_64-apple-darwin19.3.0")
  (shell . "/usr/local/bin/zsh")
  (uname . "Darwin 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64")
  (path "~/.zinit/plugins/starship---starship" "~/.zinit/plugins/julienXX---terminal-notifier" "~/.zinit/plugins/direnv---direnv" "~/.rbenv/shims" "~/.pyenv/plugins/pyenv-virtualenv/shims" "~/.pyenv/shims" "~/.jenv/shims" "~/.goenv/shims" "~/.zinit/polaris/bin" "~/.local/bin" "~/.yarn/bin" "~/.rbenv/bin" "~/.gem/ruby/2.6.0/bin" "~/.poetry/bin" "~/.pyenv/bin" "~/perl5/bin" "~/perl5/perlbrew/bin" "~/.jenv/bin" "~/.goenv/bin" "~/go/system/bin" "~/.cargo/bin" "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin" "/usr/local/bin" "/usr/local/sbin" "/usr/bin" "/bin" "/usr/sbin" "/sbin" "/Library/TeX/texbin" "/usr/local/Cellar/emacs-plus/HEAD-693749c/libexec/emacs/27.0.60/x86_64-apple-darwin19.3.0"))
 (config
  (envfile . envvar-file)
  (elc-files . 11)
  (modules :input japanese :completion (company +childframe) ivy :ui doom doom-dashboard hl-todo hydra modeline nav-flash ophints (popup +all +defaults) tabs treemacs vc-gutter window-select workspaces :editor (evil +everywhere) file-templates (format +onsave) multiple-cursors snippets word-wrap :emacs dired electric vc :term vterm :checkers (syntax +childframe) spell grammar :tools ansible (debugger +lsp) (docker +lsp) editorconfig ein eval (lookup +docsets) lsp (magit +forge) make rgb tmux :lang (cc +lsp) data emacs-lisp (ess +lsp) (go +lsp) (haskell +lsp) (java +google-java-format +lsp) (javascript +lsp) (json +lsp) (kotlin +lsp) (latex +lsp) (markdown +grip) (org +dragndrop +gnuplot +jupyter) perl (php +lsp) plantuml (python +lsp +poetry) rest (ruby +lsp +rails) (rust +lsp) (scala +lsp) (sh +fish +lsp) solidity (web +css +html +lsp) (yaml +lsp) :config (default +bindings +smartparens))
  (packages (company-emoji :pin "fc45b56f3e") (expand-region :pin "0fa7c2d349") (vagrant-tramp :pin "f67925928d") (vimrc-mode :pin "13bc150a87"))
  (unpin "n/a")
  (elpa "n/a")))
</pre></details>

**Comment by hlissner** [comment]
This is not a bug. You'll find a brief description of [how projectile resolves its projects here](https://github.com/hlissner/doom-emacs/blob/develop/core/core-projects.el#L53-L69).

Projectile searches for the parent-most directory with a `.project`, `.git`, `.hg` and `.bzr` and assumes that to be the true project root, before it searches for files like `Cargo.toml`, `packages.json`, `pom.xml` etc. in the nearest parent directory.

Adding `"Cargo.toml"` to `projectile-project-root-files-bottom-up` is one way to fix this. Removing `.git` from `projectile-project-root-files-bottom-up` is another. These will have to be reconfigured (or place a `.project` file in `simple-project`) for users who organize their projects within projects. If it is common for you, perhaps do:

```elisp
(setq projectile-project-root-files (append projectile-project-root-files-bottom-up projectile-project-root-files)
      projectile-project-root-files-bottom-up nil)
```

Hope that helps!

**Comment by sei40kr** [comment]
@hlissner 
I see. Thank you for your explanation 🙇 

But Rust LSP (both RLS and rust-analyzer) needs the `Cargo.toml` placed at the LSP workspace root, and LSP uses the projectile project root as the workspace root, so RLS diagnostics and rust-analyzer won't work when the workspace is not the repository root.

This is my workaround:
```emacs-lisp
(defun +my-lsp/lsp--suggest-project-root-a ()
  "Get project root."
  (when (featurep 'projectile)
    (condition-case nil
        (let* ((projectile-project-root-files-functions '(projectile-root-bottom-up
                                                          projectile-root-top-down
                                                          projectile-root-top-down-recurring))
               (projectile-project-root-files-bottom-up (append projectile-project-root-files-bottom-up '("Cargo.toml"))))
          (projectile-project-root))
      (error nil))))
(advice-add 'lsp--suggest-project-root
            :before-until #'+my-lsp/lsp--suggest-project-root-a)
```

Can we include this workaround in Doom Emacs Rust module?
