### ISSUE TITLE
Fix minor issue with python indentation

### ISSUE THREAD

**Issue by vikigenius** [hlissner/doom-emacs#3028]
Consider multiline arguments in a python function

```
# style 1
class A(object):
    def  __init__(
        arg1,
        arg2,
    )
```

vs

```
# style 2
class A(object):
    def  __init__(
            arg1,
            arg2,
    )
```

I find that in python mode, the auto indent (or electric indent or whatever) prefers style 2. For eg: when I press enter after arg2, after forcing style 1, an extra indent level is added. How do I avoid this, and force style 1.

**Comment by hlissner** [comment]
You can fix this by changing `python-indent-def-block-scale` (default: `2`) to `1`.

```elisp
(after! python
  (setq python-indent-def-block-scale 1))
```
