### ISSUE TITLE
Find File TAB autocompletion 

### ISSUE THREAD

**Issue by vikigenius** [hlissner/doom-emacs#303]
The find file function bound to the <SPC .> in the default module is not working well with tab completion.

I was just testing your config with the default module in the develop branch, and when i tried to simply open a file in some folder using find-file <SPC .> it is showing correct autocompletion, i press tab and it successfully autocompletes the folder name, however if i press tab again for the next level folder there is no autocompletion suggestion.

If i move back, remove the forward slash and then type a forward slash again, it is showing the autocompletion. There seem to be no errors displayed in the message buffer, am i missing something?

**Comment by hlissner** [comment]
And fixed! I'll leave this issue open until it's been merged into `master`.

**Comment by hlissner** [comment]
This is now in master.
