### ISSUE TITLE
gR is not working in elfeed

### ISSUE THREAD

**Issue by sarg** [hlissner/doom-emacs#3037]
`gR` is not working in elfeed because of typo [here](https://github.com/hlissner/doom-emacs/blob/be396655c45b8ca9b05bbf585385cd17d74a58c1/modules/editor/evil/config.el#L496)

It should read as `:map elfeed-search-mode-map`

**Comment by hlissner** [comment]
Good catch! As of c1f973b this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
