### ISSUE TITLE
doom-big-font causes the modeline to be cut on the right hand side

### ISSUE THREAD

**Issue by haditim** [hlissner/doom-emacs#3040]
Hello, 
I tried my best to find a related issue, but could not find any. I apologize if this has been answered before.

**What did you expect to happen?**
When enable big-font, the modeline should be updated with the current font size and recalculate its own width and height to match the window size.

**What actually happened?**
The font updated in the modeline but the width is not recalculated forcing the modeline to be cut on the right side.

**Additional details:**
![image](https://user-images.githubusercontent.com/24245920/81075044-23a92300-8eea-11ea-8458-550718c1c4f7.png)
After switching to big font mode
![image](https://user-images.githubusercontent.com/24245920/81075118-3d4a6a80-8eea-11ea-8c49-c8c343efaa03.png)

<details><pre>
I have the following in my config file:
`(setq
 doom-font (font-spec :family "Source Code Pro" :size 14)
 doom-big-font (font-spec :family "Source Code Pro" :size 22)
 py-autopep8-options '("--max-line-length=120")
 display-line-numbers-type 'relative
 elpy-rpc-virtualenv-path 'current
)
`
</pre></details>

**Steps to reproduce:**
1. Open Doom Emacs
2. SPC t b to toggle to big font

**Comment by hlissner** [comment]
Please include your `M-x doom/info` or `~/.emacs.d/bin/doom info`

**Comment by haditim** [comment]
Sorry, totally forgot that one:
<details>

```
emacs   version    26.3
        features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2
        build      Aug 29, 2019
        buildopts  (--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-modules 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now)
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop 10031153b 2020-04-16 03:37:19 -0400
        dir        ~/.doom.d/
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /usr/bin/zsh
        uname      Linux 5.6.7-1-MANJARO #1 SMP PREEMPT Thu Apr 23 10:50:31 UTC 2020 x86_64
        path       (~/.nix-profile/bin ~/.nix-profile/bin /nix/var/nix/profiles/default/bin ~/.local/bin /usr/local/bin /usr/bin /bin /usr/local/sbin /opt/cuda/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /usr/lib/emacs/26.3/x86_64-pc-linux-gnu/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion (company +tng +auto +rust +files) helm ido ivy :ui doom doom-dashboard hl-todo modeline nav-flash ophints (popup +all +defaults) pretty-code treemacs vc-gutter vi-tilde-fringe (window-select +numbers) workspaces :editor (evil +everywhere) file-templates fold multiple-cursors rotate-text snippets :emacs dired electric ibuffer vc :term eshell shell term vterm :tools ansible docker (eval +overlay) (lookup +docsets) lsp magit make pdf rgb :lang data emacs-lisp (javascript +lsp) latex markdown (org +dragndrop +ipython +pandoc +present) perl php (python +pyenv +lsp) (rust +lsp) sh (web +lsp) :checkers syntax spell :config (default +bindings +smartparens))
        packages   ((flycheck) (elpy) (py-autopep8) (blacken) (pip-requirements) (python-pytest) (direnv) (company-jedi) (yasnippet) (arduino-mode) (docker) (dockerfile-mode) (docker-compose-mode) (ob-http) (ng2-mode) (prettier-js) (outshine) (format-all))
        unpin      (n/a)
        elpa       (n/a)
```
</details>

**Comment by hlissner** [comment]
I can't reproduce this, even with the same font, but I've made a change in 7460e9e that may fix this issue. Please update. Let me know if that isn't the case and I'll reopen the issue.

**Comment by haditim** [comment]
Thanks @hlissner, an update indeed fixed it.
