### ISSUE TITLE
Is this a typo ? 

### ISSUE THREAD

**Issue by vpothuka-eiq** [hlissner/doom-emacs#3041]
**What did you expect to happen?**
Nothing seems to be broken, but I am not sure 

**What actually happened?**

**Additional details:**
I was going through the code to fix something and I stumbled across this code. I am new to elisp but it still doesnt feel correct :) 
 : 
https://github.com/hlissner/doom-emacs/blob/develop/modules/lang/javascript/config.el#L140
The procedure name is used recursively  but instead of saying `javascript-init-lsp-or-tide-maybe-h` , `javascript-init-tide-or-lsp-maybe-h` is used. Not sure if its causing any problem.

**Comment by gagbo** [comment]
Looks like a typo to me, you can quickly check if `javascript-init-tide-or-lsp-maybe-h` is defined using `fboundp` : `SPC : (fboundp 'javascript-init-tide-or-lsp-maybe-h) RET` (replace `SPC :` with `M-:` if you're not using bindings), `t` means the function exists, `nil` means it doesn't.

**Comment by hlissner** [comment]
Good catch. I've fixed it in 348d575
