### ISSUE TITLE
Clicking links no longer opens them

### ISSUE THREAD

**Issue by seanfarley** [hlissner/doom-emacs#3044]
**What did you expect to happen?**
Clicking a link to open said link ... or do something.

**What actually happened?**
Seems like a no-op.

**Steps to reproduce:**
Not sure what changed but I noticed this in the last week or so (what is time, these days?). I've tried to install `goto-addr` and load it in a buffer with a url but still nothing. Even using `RET`, `C-c RET` don't work.

**System information:**
<details>

```
emacs   version    26.3
        features   NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS LCMS2
        build      Apr 24, 2020
        buildopts  (--enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-mac/emacs-26.3-z-mac-7.9/share/info/emacs --prefix=/usr/local/Cellar/emacs-mac/emacs-26.3-z-mac-7.9 --with-mac --enable-mac-app=/usr/local/Cellar/emacs-mac/emacs-26.3-z-mac-7.9 --with-gnutls --with-modules)
        windowsys  mac
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop, origin/develop, origin/HEAD 35591cfc4 2020-05-04 16:53:26 -0400
        dir        ~/projects/dotfiles/doom/
system  type       darwin
        config     x86_64-apple-darwin18.7.0
        shell      /usr/local/bin/bash
        uname      Darwin 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64
        path       (~/.local/bin ~/.cargo/bin ~/projects/go/bin ~/Library/Python/3.7/bin ~/.npm/bin /opt/X11/bin /usr/local/bin /usr/local/sbin /usr/local/cuda/bin /usr/local/share/dotnet /usr/local/opt/coreutils/libexec/gnubin /usr/local/opt/make/libexec/gnubin /usr/local/opt/texinfo/bin /usr/local/Cellar/qt/5.14.1/bin /Library/TeX/texbin /usr/bin /bin /usr/sbin /sbin /usr/local/Cellar/emacs-mac/emacs-26.3-z-mac-7.9/libexec/emacs/26.3/x86_64-apple-darwin18.7.0/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion (company +auto +childframe) (ivy +childframe +icons +prescient) :ui doom doom-dashboard fill-column hl-todo indent-guides modeline nav-flash ophints (popup +all +defaults) pretty-code treemacs vc-gutter vi-tilde-fringe window-select workspaces zen :editor file-templates fold multiple-cursors (objed +manual) rotate-text snippets word-wrap :emacs (dired +ranger +icons) electric ibuffer undo vc :term vterm :checkers (syntax +childframe) spell grammar :tools ansible biblio debugger docker editorconfig eval gist (lookup +docsets +dictionary) lsp macos (magit +forge) make pdf prodigy upload :lang (cc +lsp) clojure common-lisp data emacs-lisp go hy (javascript +lsp) (latex +latexmk) lua markdown nim (org +brain +dragndrop +gnuplot +hugo +journal +jupyter +pandoc +pomodoro +present +roam) (python +cython +lsp) rest rst rust scheme sh (swift +lsp) web :email mu4e :app irc twitter :config (default +bindings +smartparens +snippets))
        packages   ((ace-mc) (banner-comment) (bitwarden :recipe (:host github :repo seanfarley/emacs-bitwarden)) (col-highlight :recipe (:host github :repo emacsmirror/col-highlight)) (color-identifiers-mode) (counsel-jq) (discover-my-major) (dot-mode) (easy-hugo) (elisp-slime-nav) (embrace) (emr) (fancy-narrow) (focus) (goto-chg) (ialign) (jump-tree) (lsp-focus :recipe (:host github :repo emacs-lsp/lsp-focus)) (lsp-origami) (lsp-treemacs) (magit-circleci) (mpdel) (ivy-mpdel) (mingus) (mu4e :recipe (:local-repo ~/projects/mu/mu4e)) (mu4e-alert) (mu4e-maildirs-extension :disable t) (mu4e-patch :recipe (:host github :repo seanfarley/mu4e-patch)) (nerd-font :recipe (:host github :repo twlz0ne/nerd-fonts.el)) (nov) (org-ref) (package-lint) (page-break-lines) (persistent-scratch) (pony-mode) (resize-window) (ripgrep) (simple-httpd) (simple-mpc :recipe (:local-repo ~/projects/simple-mpc)) (sphinx-doc) (srefactor) (sx) (unfill) (webpaste) (whole-line-or-region) (which-key-posframe) (xonsh-mode :recipe (:local-repo ~/projects/xonsh-mode)) (ztree))
        unpin      (t)
        elpa       (n/a)
```
</details>

**Comment by hlissner** [comment]
`goto-addr` was disabled in https://github.com/hlissner/doom-emacs/commit/5bc86de76 to reduce non-essential fontification and because it is redundant with `gf` and `find-file-at-point` (which `gf` uses) which both understand URLs.

**Comment by seanfarley** [comment]
But shouldn’t mouse clicks still work? I mean, I try not to use the mouse but sometimes it’s the easiest and having it do nothing seems a bit... odd.

**Comment by hlissner** [comment]
That was goto-address-mode's doing. It converts urls into highlighted buttons that can be clicked. Without it, you can't click them.

**Comment by seanfarley** [comment]
Hmm, I have the links fontified (presumably by `goto-address`) but clicking doesn't work. Trying the new `C-c g f` I finally see this error message (perhaps the two are related):

`No lookup handler could find "https://confluence.atlassian.com/bitbucket/oauth-on-bitbucket-cloud-238027431.html"`

**Comment by hlissner** [comment]
The error message is a ux bug you can ignore; it should still open the file in your browser. That it isn't suggests something else is wrong and may be tied to your issue with goto-addr. What happens when you `M-x browse-url RET https://confluence.atlassian.com/bitbucket/oauth-on-bitbucket-cloud-238027431.html`?

**Comment by seanfarley** [comment]
I had just gone down that debugging route, too. The culprit is that `browse-url` (with any link given to it) spawns (and apparently dies): `#<process open https://confluence.atlassian.com/bitbucket/oauth-on-bitbucket-cloud-238027431.html>`

If I cut emacs out of the equation and just use a terminal, things work as expected. Digging further I get a weird error from `open`: `Illegal instruction: 4`.

**Comment by seanfarley** [comment]
This smells like Apple's sandboxing stuff but I've no idea at the moment.

**Comment by seanfarley** [comment]
I hesitate to point the finger at sandboxing, though, because Emacs can launch `open` correctly via libvterm (which is still owned, as far as I understand, by the emacs process). Though, via `M-x shell` and `M-x eshell` it still gives the illegal instruction.

**Comment by telotortium** [comment]
I see the error from `open` only when Emacs loads the Doom configuration. I can reproduce that this issue doesn't occur in vanilla Emacs (according to `doom/sandbox`).

**Comment by seanfarley** [comment]
Oh, good call @telotortium. I can't believe I didn't try that >_<. I can confirm that `emacs -Q` works as expected with `open`.

**Comment by hlissner** [comment]
Could this be stale environmental state? Are there envvars (perhaps `BROWSER`) in `~/.emacs.d/.local/env` that are no longer relevant? Try running `doom env` to refresh them.

**Comment by telotortium** [comment]
I had just run `doom sync`, so I presume the environment was refreshed.
However, perhaps it is an environment variable. Does the vanilla Emacs
spawned by doom include the environment variables from the doom Emacs?

**Comment by seanfarley** [comment]
We can cut `BROWSER` out of the equation entirely by using `M-x shell` and running `open https://google.com`. In vanilla emacs (`emacs -Q`) this works but in doom I get the illegal instruction bit.

**Comment by hlissner** [comment]
@telotortium Yes, it does. The child process inherits the environment from the parent process.

**Comment by telotortium** [comment]
@hlissner I've confirmed that the environment is indeed inherited, so the environment variables are probably not the primary cause.

I found two issues via Google that may be vaguely related: https://github.com/JuliaLang/julia/issues/18818, https://github.com/JuliaLang/julia/issues/24169

**Comment by seanfarley** [comment]
I stared to bisect this issue but once I removed `.local` everything started working again ;_;

**Comment by telotortium** [comment]
I was able to remove .local/env and it worked. Probably removing the right
environment variable will fix it, but I haven't determined which one it is
yet.

**Comment by seanfarley** [comment]
Aha, I think I'm able to reproduce this!

**Comment by seanfarley** [comment]
@telotortium Do you happen to have the environment variable `DYNAMIC_CWD_ELISION_CHAR` in your `env`?

**Comment by seanfarley** [comment]
@hlissner For me, that is the line / variable I was able to bisect to (removing that one variable restores the correct behavior). It is also the only line with unicode in it: `…` (not sure if that will copy / paste correctly but it's the unicode symbol for three dots).

Shooting in the dark: but maybe that is wrecking the parsing of the `env` file?

**Comment by seanfarley** [comment]
@telotortium If you don't have that variable specifically, maybe you have some other unicode line in your `env` file?

**Comment by seanfarley** [comment]
Ok, can confirm any unicode breaks `open` with the illegal instruction bit:

```
FOOBAR=😁^@
```

**Comment by telotortium** [comment]
Yes, it's the same for me. I think there's an issue with how Doom parses the `env` file - environment variables with Unicode in them don't break `open` when I call it from the terminal.

**Comment by hlissner** [comment]
See if 21fda9a fixes your issue.

**Comment by telotortium** [comment]
Yes, that works.

**Comment by seanfarley** [comment]
Seems to have fixed it for me, too! I'll go ahead and close this now; thanks for the help, everyone!
