### ISSUE TITLE
Asterisks render as question marks in org mode.

### ISSUE THREAD

**Issue by pathofnight** [hlissner/doom-emacs#3045]
I am trying to join the church of emacs and I installed it because I wanted to use the org-mode.

I am using the doom emacs distribution.

The problem I am facing is that when I put `*` and press space I see a `?` rather than a nice bullet. (See the image).

What is wrong?

Also, if you have any emacs tip for a newbie then please feel free to preach!

Thanks.

**System information**
<details><pre>
((emacs
  (version . "26.3")
  (features . "JPEG SOUND GPM DBUS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 ZLIB XIM THREADS LIBSYSTEMD LCMS2")
  (build . "Mar 26, 2020")
  (buildopts "--build x86_64-linux-gnu --prefix=/usr --sharedstatedir=/var/lib --libexecdir=/usr/lib --localstatedir=/var/lib --infodir=/usr/share/info --mandir=/usr/share/man --enable-libsystemd --with-pop=yes --enable-locallisppath=/etc/emacs:/usr/local/share/emacs/26.3/site-lisp:/usr/local/share/emacs/site-lisp:/usr/share/emacs/26.3/site-lisp:/usr/share/emacs/site-lisp --with-sound=alsa --without-gconf --with-mailutils --build x86_64-linux-gnu --prefix=/usr --sharedstatedir=/var/lib --libexecdir=/usr/lib --localstatedir=/var/lib --infodir=/usr/share/info --mandir=/usr/share/man --enable-libsystemd --with-pop=yes --enable-locallisppath=/etc/emacs:/usr/local/share/emacs/26.3/site-lisp:/usr/local/share/emacs/site-lisp:/usr/share/emacs/26.3/site-lisp:/usr/share/emacs/site-lisp --with-sound=alsa --without-gconf --with-mailutils --with-x=no --without-gsettings 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/emacs-mEZBk7/emacs-26.3+1=. -fstack-protector-strong -Wformat -Werror=format-security -Wall' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro'")
  (windowsys . batch)
  (daemonp))
 (doom
  (version . "2.0.9")
  (build . "grafted, HEAD -> develop, origin/develop, origin/HEAD 7460e9e 2020-05-05 16:28:29 -0400")
  (dir . "~/.doom.d/"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/bin/bash")
  (uname . "Linux 5.4.0-29-generic #33-Ubuntu SMP Wed Apr 29 14:32:27 UTC 2020 x86_64")
  (path "/usr/local/sbin" "/usr/local/bin" "/usr/sbin" "/usr/bin" "/sbin" "/bin" "/usr/games" "/usr/local/games" "/snap/bin" "/usr/lib/emacs/26.3/x86_64-linux-gnu"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline ophints (popup +defaults) vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold snippets :emacs dired electric undo vc :checkers syntax :tools (eval +overlay) lookup magit :lang emacs-lisp markdown org sh :config (default +bindings +smartparens))
  (packages (org-superstar :disable t))
  (unpin "n/a")
  (elpa "n/a")))

</pre></details>

![Screenshot from 2020-05-06 03-51-38](https://user-images.githubusercontent.com/49331893/81130866-dcad4300-8f66-11ea-8f22-19991302bb87.png)

**Comment by hlissner** [comment]
Hello there! Welcome to Doom! When you create a github issue on this project, github pre-fills it with a template outlining the things you should try to include in your bug reports. At the very least, please provide the output of running `~/.emacs.d/bin/doom info` on your command line.

Without any of this information I cannot determine much about your situation.

If for some reason you cannot acquire the results of `doom info`, please provide:

1. What version of Emacs you're using.
2. What OS/distro you're on.
3. How you installed Emacs (your package manager? Which recipe? Or did you compile it yourself?) 
4. What commit of Doom you're on (or the date and time you cloned the doom-emacs repo).
5. Whether you're running Emacs in the terminal or not.
6. A link to your config, if it is up somewhere.

----

Moving on to your problem, this is usually a font issue. Meaning your current font (or your terminal's font) has poor unicode support. You can either;

1. [Change fonts](https://github.com/hlissner/doom-emacs/blob/develop/docs/faq.org#how-do-i-change-the-fonts) (if you're using Emacs in the terminal, then Emacs can't control your font. You'll have reconfigure your terminal). [Fira Code](https://github.com/tonsky/FiraCode) is known to work, for instance.
2. [Disable the `org-superstar` package](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#disabling-packages), which is supposed to replace the asterisks with unicode dots. To do this, add `(package! org-superstar :disable t)` to `~/.doom.d/packages.el`, run `doom sync` on the command line, and restart Emacs.
3. If you're in terminal emacs, try changing org-superstar's bullets or fallback icon:

   ```elisp
   ;; add to ~/.doom.d/config.el
   (after! org
     (setq org-superstar-headline-bullets-list '("#")) 
   ```

----

I recommend [hopping on our Discord server](https://discordapp.com/channels/406534637242810369/579041038669447178/671244717844987904) -- there are people on there can walk you through the issue.

Hope that helps!

**Comment by pathofnight** [comment]
> Hello there! Welcome to Doom! When you create a github issue on this project, github pre-fills it with a template outlining the things you should try to include in your bug reports. At the very least, please provide the output of running `~/.emacs.d/bin/doom info` on your command line.
> 
> Without any of this information I cannot determine much about your situation.
> 
> If for some reason you cannot acquire the results of `doom info`, please provide:
> 
> 1. What version of Emacs you're using.
> 2. What OS/distro you're on.
> 3. How you installed Emacs (your package manager? Which recipe? Or did you compile it yourself?)
> 4. What commit of Doom you're on (or the date and time you cloned the doom-emacs repo).
> 5. Whether you're running Emacs in the terminal or not.
> 6. A link to your config, if it is up somewhere.
> 
> Moving on to your problem, this is usually a font issue. Meaning your current font (or your terminal's font) has poor unicode support. You can either;
> 
> 1. [Change fonts](https://github.com/hlissner/doom-emacs/blob/develop/docs/faq.org#how-do-i-change-the-fonts) (if you're using Emacs in the terminal, then Emacs can't control your font. You'll have reconfigure your terminal). [Fira Code](https://github.com/tonsky/FiraCode) is known to work, for instance.
> 2. [Disable the `org-superstar` package](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#disabling-packages), which is supposed to replace the asterisks with unicode dots. To do this, add `(package! org-superstar :disable t)` to `~/.doom.d/packages.el`, run `doom sync` on the command line, and restart Emacs.
> 3. If you're in terminal emacs, try changing org-superstar's bullets or fallback icon:
>    ```emacs-lisp
>    ;; add to ~/.doom.d/config.el
>    (after! org
>      (setq org-superstar-headline-bullets-list '("#")) 
>    ```
> 
> I recommend [hopping on our Discord server](https://discordapp.com/channels/406534637242810369/579041038669447178/671244717844987904) -- there are people on there that can walk you through the issue.
> 
> Hope that helps!

Sorry for being unclear. I am very new to this world. I have edited my post to include the `~/.emacs.d/bin/doom info` Also, I tried to follows the steps you suggested. I installed `kitty` and `Fira Code` font. I added the following lines to `~/.doom.d/config.el`

```
(setq doom-font (font-spec :family "Input Mono Narrow" :size 12 :weight 'semi-light)
      doom-variable-pitch-font (font-spec :family "Fira Sans") ; inherits `doom-font''s :size
      doom-unicode-font (font-spec :family "Input Mono Narrow" :size 12)
      doom-big-font (font-spec :family "Fira Mono" :size 19))
```
However, nothing has changed and I still see `?` instead of a bullet.

I was not able to execute Step 2 of your suggestions where you ask to disable the `org-superstar` package. The problem was that when I ran `doom sync` it did not recognize the `doom` command and gave me a few options where I could install it from, one of them was `chocolate-doom`. I happily ran `apt install chocolate-doom` and ended up installing a shooter game.

**Comment by hlissner** [comment]
> kitty and Fira Code

This implies you're running Emacs in a terminal (kitty, to be precise). In the terminal, Emacs cannot control its fonts -- that's up to kitty instead.

I'm not familiar with kitty, so the specifics elude me, but perhaps [this tutorial](https://sw.kovidgoyal.net/kitty/conf.html) can help. You need to change the font kitty uses.

> The problem was that when I ran doom sync it did not recognize the doom command

Sorry I wasn't clearer: the doom script is in `~/.emacs.d/bin`, so run `~/.emacs.d/bin/doom sync` instead.

**Comment by RyanGreenup** [comment]
I'm using kitty but I don't have this issue, this is the main reason I like kitty, I have images and unicode display in the terminal and it *just works*.

* Does it make a difference if you toggle `M-x org-superstar-mode`?
  + `M-x` means <kbd> Alt </kbd> + <kbd> x </kbd>
* What happens when you toggle `M-x org-mode`?
* Does this happen if you open emacs outside the terminal?
  + Obviously this isn't an option if you use `ssh` but generally *Emacs* is better through the GUI because you get things like latex fragments and [eaf-open](https://github.com/manateelazycat/emacs-application-framework) which makes org-mode better than markdown.
* When you press <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>u</kbd> in *Kitty* do you get popup of unicode symbols and do they all display correctly?
* Maybe try using *Emacs 27* :man_shrugging: 
  + Also if you're using the *Snap* I noticed better performance after compiling from source so you might want to consider trying that as well (remember to include `xwidget` support if you want that!)

**Comment by pathofnight** [comment]
Thanks for the response.

> * Does it make a difference if you toggle `M-x org-superstar-mode`?

The question marks become asterisks! Better but one really wants a bullet.

> * What happens when you toggle `M-x org-mode`?

The asterisks become question marks again.

> * Does this happen if you open emacs outside the terminal?

I am unable to open it outside terminal. Perhaps I have installed a version which only works on terminal. I will take some time to figure this one out.
   

> * When you press Ctrl+Shift+u in _Kitty_ do you get popup of unicode symbols and do they all display correctly?

This is what I [see](https://www.dropbox.com/s/l9dg9jbbnpzy7hx/Screenshot%20from%202020-05-12%2015-49-55.png?dl=0). I think this is correct.

**Comment by RyanGreenup** [comment]
Sorry for the late reply, I've had Assessments, I think your best bet is getting an *Emacs* that runs outside the terminal.

I've had issues with the *Snap* package on *Ubuntu* so I'd strongly recommend compiling from source, also the docs recommend using *Emacs 27* (at least I saw that somewhere) so that's what I'd also recommend using, you can download it [here](https://alpha.gnu.org/gnu/emacs/pretest/windows/emacs-27/)

The process is [documented here](https://www.gnu.org/software/emacs/manual/html_node/efaq/Installing-Emacs.html) but I would recomend using `checkinstall` rather than `install`, this will create a `deb` package so you can remove *Emacs* without it being difficult, so the process more or less would be:

1. Install Checkinstall and make sure you don't have *Emacs25*, you'll also want to put it on hold because otherwise `apt` can be a PITA with downgrading 27.
```bash
sudo apt update
sudo apt install checkinstall
sudo apt remove emacs
sudo apt remove emacs25
sudo apt-mark hold emacs
sudo apt-mark hold emacs25
```
2. Install *Emacs*
```bash
cd ~/Downloads
wget https://alpha.gnu.org/gnu/emacs/pretest/windows/emacs-27/emacs-27.0.91.tar.gz
tar -xzf emacs-27.0.91.tar.gz
rm emacs-27.0.91.tar.gz
cd emacs-27.0.91
./configure --with-xwidgets --with-mailutils
make
sudo checkinstall
```

Invariably you will be probably be missing libraries, if so, you'll want to prefix the name of the error with `lib` and suffix it with `-dev` so for example if it said that it could compile `png` you'll want to do `sudo apt install `libpng-dev`.

After that you'll need to tell doom about the update so do:

```bash
~/emacs.d/bin/doom refresh
```

And then you should be able to open emacs by doing <kbd>Alt</kbd>-<kbd>F2</kbd> `/usr/local/bin/emacs` <kbd>Enter</kbd> and then you should be set (you do generally want to use the GUI for *Emacs* unlike say *Vim* because all the cool font things and embedded pictures and [EAF](https://github.com/manateelazycat/emacs-application-framework).

**Comment by pathofnight** [comment]
> /usr/local/bin/emacs



> Sorry for the late reply, I've had Assessments, I think your best bet is getting an _Emacs_ that runs outside the terminal.
> 
> I've had issues with the _Snap_ package on _Ubuntu_ so I'd strongly recommend compiling from source, also the docs recommend using _Emacs 27_ (at least I saw that somewhere) so that's what I'd also recommend using, you can download it [here](https://alpha.gnu.org/gnu/emacs/pretest/windows/emacs-27/)
> 
> The process is [documented here](https://www.gnu.org/software/emacs/manual/html_node/efaq/Installing-Emacs.html) but I would recomend using `checkinstall` rather than `install`, this will create a `deb` package so you can remove _Emacs_ without it being difficult, so the process more or less would be:
> 
> 1. Install Checkinstall and make sure you don't have _Emacs25_, you'll also want to put it on hold because otherwise `apt` can be a PITA with downgrading 27.
> 
> ```shell
> sudo apt update
> sudo apt install checkinstall
> sudo apt remove emacs
> sudo apt remove emacs25
> sudo apt-mark hold emacs
> sudo apt-mark hold emacs25
> ```
> 
> 1. Install _Emacs_
> 
> ```shell
> cd ~/Downloads
> wget https://alpha.gnu.org/gnu/emacs/pretest/windows/emacs-27/emacs-27.0.91.tar.gz
> tar -xzf emacs-27.0.91.tar.gz
> rm emacs-27.0.91.tar.gz
> cd emacs-27.0.91
> ./configure --with-xwidgets --with-mailutils
> make
> sudo checkinstall
> ```
> 
> Invariably you will be probably be missing libraries, if so, you'll want to prefix the name of the error with `lib` and suffix it with `-dev` so for example if it said that it could compile `png` you'll want to do `sudo apt install `libpng-dev`.
> 
> After that you'll need to tell doom about the update so do:
> 
> ```shell
> ~/emacs.d/bin/doom refresh
> ```
> 
> And then you should be able to open emacs by doing Alt-F2 `/usr/local/bin/emacs` Enter and then you should be set (you do generally want to use the GUI for _Emacs_ unlike say _Vim_ because all the cool font things and embedded pictures and [EAF](https://github.com/manateelazycat/emacs-application-framework).

I followed all the steps. However, when I do `/usr/local/bin/emacs` it says "command not found." I looked into my `/usr/local/bin` folder and it was empty. But there was emacs related stuff in `/usr/lib` So I ran `/usr/lib/emacs` No error was displayed but nothing happened either. Also, using emacs from the terminal still doesn't give me bullets. I guess I have spent a lot of time on this and now I want to give it a rest.

Thank you for being so patient and your detailed responses.

**Comment by RyanGreenup** [comment]
First just double check it's installed, if you do:
```bash
sudo apt list emacs   
```
You should ideally get an output like this:

```
Listing... Done
emacs/bionic,bionic 47.0 amd64 [upgradable from: 27.0.91-1]
N: There is 1 additional version. Please use the '-a' switch to see it
```
> The "*1 additional version*" part is because of `apt-mark hold`

<details><summary><b><i>Click Me if You didn't get that</b></i></summary>
	<p>
 If you didn't get that then the issue is that it hasn't been installed, or atleast it hasn't been installed through `apt`.

* If you used `checkinstall you'll likely need to go through the installation process again and triple check everything, is it possible there was an error that you didn't catch?

* If you didn't use `checkinstall` and instead used `install` read on because you've probably installed it (it's just not through `apt` so be mindful that it's going to be a nuisance to uninstall in the future). 
   
</p>
</details>



Assuming it's installed It's possible it ended up in `usr/bin` that can happen depending on previous installs etc. so try `which emacs` in the terminal and maybe try `/usr/bin/emacs` (I'm assuming you tried `emacs` in the terminal?)

If that doesn't do it we need to try and find it so try:

```bash
## find /usr/ -executable -name emacs  | fzf ## iff fzf is installed
find /usr/ -executable -name emacs | vim -      
```

you're looking for something under a `bin` directory (probably), I've included what my system gives me and when I do `$ /usr/local/bin/emacs` it executes.

<details><summary><b>My Output </b></summary>
	<p>
    
```
/usr/local/share/emacs
/usr/local/share/cmake-3.17/editors/emacs
/usr/local/libexec/emacs
/usr/local/bin/emacs
/usr/share/logstash/vendor/jruby/lib/ruby/gems/shared/gems/test-unit-3.2.8/lib/test/unit/ui/emacs
/usr/share/emacs
/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/gyp/tools/emacs
/usr/share/doc/emacs
/usr/share/doc/emacs/doc/emacs
/usr/share/cmake-3.10/editors/emacs
/usr/lib/emacs
/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/tools/emacs
/usr/lib/node_modules/tern/emacs
/usr/lib/ruby/vendor_ruby/test/unit/ui/emacs
```

I'm on *Linux Mint* `19.3` - `tricia` which is essentially *Ubuntu* `18.04`
    
</p>
</details>

**Comment by pathofnight** [comment]
> First just double check it's installed, if you do:
> 
> ```shell
> sudo apt list emacs   
> ```
> 
> You should ideally get an output like this:
> 
> ```
> Listing... Done
> emacs/bionic,bionic 47.0 amd64 [upgradable from: 27.0.91-1]
> N: There is 1 additional version. Please use the '-a' switch to see it
> ```
> 
> > The "_1 additional version_" part is because of `apt-mark hold`
> 
> Click Me if You didn't get that
> If you didn't get that then the issue is that it hasn't been installed, or atleast it hasn't been installed through `apt`.
> 
> * If you used `checkinstall you'll likely need to go through the installation process again and triple check everything, is it possible there was an error that you didn't catch?
> * If you didn't use `checkinstall` and instead used `install` read on because you've probably installed it (it's just not through `apt` so be mindful that it's going to be a nuisance to uninstall in the future).
> 
> Assuming it's installed It's possible it ended up in `usr/bin` that can happen depending on previous installs etc. so try `which emacs` in the terminal and maybe try `/usr/bin/emacs` (I'm assuming you tried `emacs` in the terminal?)
> 
> If that doesn't do it we need to try and find it so try:
> 
> ```shell
> ## find /usr/ -executable -name emacs  | fzf ## iff fzf is installed
> find /usr/ -executable -name emacs | vim -      
> ```
> 
> you're looking for something under a `bin` directory (probably), I've included what my system gives me and when I do `$ /usr/local/bin/emacs` it executes.
> 
> My Output
> ```
> /usr/local/share/emacs
> /usr/local/share/cmake-3.17/editors/emacs
> /usr/local/libexec/emacs
> /usr/local/bin/emacs
> /usr/share/logstash/vendor/jruby/lib/ruby/gems/shared/gems/test-unit-3.2.8/lib/test/unit/ui/emacs
> /usr/share/emacs
> /usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/gyp/tools/emacs
> /usr/share/doc/emacs
> /usr/share/doc/emacs/doc/emacs
> /usr/share/cmake-3.10/editors/emacs
> /usr/lib/emacs
> /usr/lib/node_modules/npm/node_modules/node-gyp/gyp/tools/emacs
> /usr/lib/node_modules/tern/emacs
> /usr/lib/ruby/vendor_ruby/test/unit/ui/emacs
> ```
> 
> I'm on _Linux Mint_ `19.3` - `tricia` which is essentially _Ubuntu_ `18.04`

When I run `sudo apt list emacs` I get
```
emacs/focal,focal 1:26.3+1-1ubuntu2 all
```
Would it be a good idea to completely remove emacs and start afresh?

Would `sudo apt remove emacs --purge` do it or is it more complicated? 

Thank you.

**Comment by RyanGreenup** [comment]
Yeah purge should be fine, how did you go with it?

**Comment by integral-dw** [comment]
Hi, I'm the maintainer of `org-superstar`.  The issue itself is quite common, due to different unicode blocks supported by different characters.  I should probably dedicate an FAQ entry to this.  If there is anything else I can do to help, be sure to notify me.
