### ISSUE TITLE
CC module navigation

### ISSUE THREAD

**Issue by vikigenius** [hlissner/doom-emacs#305]
The README.org in the CC module mentions code navigation with irony, as far as i know, irony doesn't provide this feature.

Can you just briefly mention on how you are doing code navigation for C++. I personally had been using rtags till now, it works good, but i am not really happy with it, but you don't seem to be using it.

You seem to be using xref, but how are the tags getting built for it? I have never used it, so if you have used rtags how good is it comparatively?

**Comment by amosbird** [comment]
I have a forked version of cc module with only rtags enabled 

https://github.com/amosbird/abdoom/blob/master/cc/config.el

It works pretty well.

**Comment by vikigenius** [comment]
Cool, i will check it out, i am already on my way of doing it myself. Do you have any tips for speeding up rtags, especially some places where it pretty much takes 5-10 seconds for go-to-definition? 
It is pretty much the best indexer that is available for emacs in terms of C++ support but damn, it's slow.

**Comment by amosbird** [comment]
Yup, rtags can be quite CPU intensive. The tip is to get more hardware. I use rtags on an 40 cores machine with 256GB memory ;-)

**Comment by hlissner** [comment]
Right now, xref in Doom uses etags and gnu global as backends, but they are less than stellar. They will ask you where the TAGs/global db file is if they can't find it on first invocation.

In fact, I rely on [dumb-jump](https://github.com/jacktasia/dumb-jump) for most of my C/C++ code navigation needs (basically, set `(setq xref-backend-functions '(t))` in C/C++ buffers and use `+jump/definition` and `+jump/references`). This is not shown in Doom, since I've considered this "experimental" for a while.

It's fast and _reasonably_ accurate, minus the need to generate tags file or manage a daemon. But I understand if that isn't enough. I've considered rtags integration for a while.

I'll look into @amosbird's rtags implementation and see what i can do.

**Comment by hlissner** [comment]
I've added rtag support to `develop`, loosely based off of @amosbird's work. It needs more testing, but it'll have to wait until after new years.

**Comment by hlissner** [comment]
@amosbird What're your experiences with flycheck-rtags? Is it better than flycheck-irony? I haven't found any compelling reason to use the rtags backend over the irony one.

**Comment by amosbird** [comment]
Hi, flycheck-rtags always shows the same errors as my project building system. I remember I didn't have much luck with flycheck-irony, and I never use auto-completion in c++. It's slow.

**Comment by hlissner** [comment]
>I remember I didn't have much luck with flycheck-irony

That's odd. Irony is configured to pick up on the same compile_commands.json file as rtags, so flycheck-irony ought to produce the same errors as your build system.

**Comment by hlissner** [comment]
rtags is now integrated into Doom's master branch, so I'll consider this resolved. Let me know if the module gives you any trouble.

**Comment by vikigenius** [comment]
The rtags integration is working fine, thanks a lot for this. However there seems to be an issue with the jump settings.

I saw in the code that you have bound the jump-definition and jump-references in c/c++ mode to rtags:
```
(set! :jump '(c-mode c++-mode)
  :definition #'rtags-find-symbol-at-point
  :references #'rtags-find-references-at-point)))
```
However this does not seem to be working and throws an error
`command-execute: Wrong type argument: commandp, +jump/definition`

**Comment by hlissner** [comment]
You'll need to update. In https://github.com/hlissner/doom-emacs/commit/1371d341492c5b72e7c08365c1e55622e11b288d I replaced `feature/jump` with `feature/lookup`, and in https://github.com/hlissner/doom-emacs/commit/42cee2e046a909f7a9adde41e9aeb566cbdb61be I changed all references to the `:jump` setting across various lang modules, including lang/cc.
