### ISSUE TITLE
LSP can't format buffer when capability not provided by language server

### ISSUE THREAD

**Issue by smsegal** [hlissner/doom-emacs#3054]
**What did you expect to happen?**
Formatting a python file using `SPC c f` should result in a formatted document.

**What actually happened?**
Document is not formatted and an error message stating that the capability is not supported by the current language server is displayed in minibuffer.

I suspect that this commit: b5c4fce0b1b579f0eb4042e78bd10b11d09056df caused the regression, as prior I would be able to format using format-all's built in support for the black formatter. 

I'm using the microsoft python language server. 

Can I suggest we check for the documentFormat capability in a given language server, and fall back to format-all if it does not provide it?

**System information:**

<details>

```
emacs   version    28.0.50
        features   XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS PDUMPER LCMS2 GMP
        build      May 05, 2020
        buildopts  ()
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop b5c4fce0b 2020-05-06 02:59:53 -0400
        dir        ~/dotfiles/doom/doom.d/
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /usr/bin/zsh
        uname      Linux 5.6.8-300.fc32.x86_64 #1 SMP Wed Apr 29 19:01:34 UTC 2020 x86_64
        path       (~/.cache/pypoetry/virtualenvs/dotfiles-XgGoJcR_-py3.8/bin/ ~/.cargo/bin/ ~/.cargo/bin/ ~/.emacs.d/bin/ ~/.poetry/bin/ ~/.local/bin/ ~/.pyenv/bin/ ~/.nix-profile/bin/ ~/bin/ /usr/local/bin/ /usr/local/sbin/ /usr/bin/ /usr/sbin/ /opt/local/bin/ /opt/local/sbin/ ~/.cache/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-zpm-zsh-SLASH-colorize/bin/ /usr/local/libexec/emacs/28.0.50/x86_64-pc-linux-gnu/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion (company +childframe) (ivy +icons +fuzzy +prescient) :ui doom doom-dashboard hl-todo hydra modeline nav-flash ophints (popup +defaults) pretty-code treemacs vc-gutter vi-tilde-fringe window-select workspaces zen :editor (evil +everywhere) file-templates fold format snippets word-wrap :emacs (dired +icons) electric (ibuffer +icons) undo vc :term vterm :checkers syntax spell :tools debugger direnv docker editorconfig ein (eval +overlay) (lookup +dictionary +docsets) (lsp +peek) magit make pass pdf upload :lang clojure data elixir emacs-lisp go (haskell +dante) javascript (latex +fold +cdlatex +lsp +latexmk) markdown (org +dragndrop +jupyter +pandoc +present) (python +lsp +poetry +pyenv) (rust +lsp) (sh +fish +lsp) web yaml :config (default +bindings +smartparens))
        packages   ((lorem-ipsum) (term-cursor :recipe (:repo h0d/term-cursor.el :host github)) (yasnippet-snippets) (sublime-themes) (soothe-theme) (darktooth-theme) (grayscale-theme) (zenburn-theme) (kaolin-themes) (smart-mode-line) (modus-operandi-theme) (modus-vivendi-theme))
        unpin      (n/a)
        elpa       (n/a)
```
</details>

Thanks!

**Comment by hlissner** [comment]
Good idea. As of 200ab5b it should do exactly as you described. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by smsegal** [comment]
Incredibly fast response from you :) 
Just pulled in the latest changes, and not quite there. When I try to format the same file, I get this error:
`command-execute: Wrong type argument: commandp, +format/region-or-buffer`
I took a look, and you're missing a closing parenthesis in `modules/editor/format/autoload/format.el` line 230 at the end of the `+format/region-or-buffer` defun.

**Comment by hlissner** [comment]
Ah, my bad. Just pushed a fix. Although, the `commandp` error suggests you don't have the `:editor format` module enabled or its autoloaded files haven't been indexed yet. Did you run `doom sync` after enabling it?

**Comment by smsegal** [comment]
Yes, you’re right, I reported the commandp error and then decided to do some digging on my own when i spotted the missing paren. Had to  doom sync afterwards to get it loaded.

Thanks for the quick responses btw, although i can assume you don’t have many other places to be right now 🙃

________________________________
