### ISSUE TITLE
Make pretty-symbols an option in cc-mode

### ISSUE THREAD

**Issue by beojan** [hlissner/doom-emacs#3059]
Can you make `pretty-symbols` (but preferably not ligatures, at least in the same option) optional in `cc-mode` with `pretty-code` enabled?

The biggest problem is that `&&` for an rvalue reference gets replaced with the AND symbol. Since you can have any type name in front of that `&&`, I don't think this is easily fixable.

I'm not a fan of replacing the single character `!` with another single character `¬` either.

**Comment by howsiwei** [comment]
Try
```elisp
(setq +pretty-code-enabled-modes '(not c++-mode))
```

**Comment by beojan** [comment]
Won't that turn off pretty-code entirely for C++?

I want to keep the ligature substitution and turn off only pretty-symbols.

**Comment by howsiwei** [comment]
If I'm not wrong it would turn off ligatures.

**Comment by beojan** [comment]
You are indeed correct, thanks!
