### ISSUE TITLE
Under Windows OS emacs --daemon is more slowly than the normal way

### ISSUE THREAD

**Issue by lld2001** [hlissner/doom-emacs#3063]
**What are you trying to achieve?**
`emacs.exe --daemon`  need about 20s to strart. 
`emacs.exe` need 7s to start.
I don't know if it is normal.

**What have you tried?**

download [emacs 27.0.91](https://alpha.gnu.org/gnu/emacs/pretest/windows/emacs-27/emacs-27.0.91-x86_64.zip), 

clone from latest [doom emacs](https://github.com/hlissner/doom-emacs.git),

doom install

1. run `emacs.exe --daemon`

2. run `emacs.exe`

The first is far more slowly to start.

**System information**
<details>
<pre>
```
emacs   version    27.0.91
        features   XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY W32NOTIFY ACL GNUTLS LIBXML2 HARFBUZZ ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS PDUMPER LCMS2 GMP
        build      Apr 20, 2020
        buildopts  (--without-dbus --host=x86_64-w64-mingw32 --without-compress-install 'CFLAGS=-O2 -static')
        windowsys  w32
        daemonp    daemon
doom    version    2.0.9
        build      
        dir        ~/.doom.d/
system  type       windows-nt
        config     x86_64-w64-mingw32
        shell      E:/emacs/libexec/emacs/27.0.91/x86_64-w64-mingw32/cmdproxy.exe
        uname      n/a
        path       (D:\Python36\Scripts\ D:\Python36\ D:\Python36 f:\cygwin64\bin C:\Program Files (x86)\Common Files\Oracle\Java\javapath C:\Windows\system32 C:\Windows C:\Windows\System32\Wbem C:\Windows\System32\WindowsPowerShell\v1.0\ C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static C:\Program Files\Git\cmd C:\Program Files\nodejs\ C:\Program Files (x86)\MySQL\MySQL Utilities 1.6\ d:\Program Files\Microsoft VS Code\bin C:\Program Files\Pandoc\ C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\ C:\Program Files (x86)\Microsoft SQL Server\100\DTS\Binn\ C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\VSShell\Common7\IDE\ C:\Program Files (x86)\Microsoft Visual Studio 9.0\Common7\IDE\PrivateAssemblies\ C:\Program Files\dotnet\ e:\emacs\.doom.d\bin e:\emacs\.doom.d\bin e:\emacs\.doom.d\bin\pdf-tools e:\emacs\.doom.d\bin\mspyls D:\jdk1.6.0_37\bin D:\javaTools\apache-maven-3.2.5\bin C:\Users\hh\AppData\Roaming\npm D:\Python36 D:\Python36\Scripts C:\Program Files\Docker Toolbox C:\Program Files (x86)\WinRAR e:\emacs\bin e:\emacs\.emacs.d\bin C:\Program Files (x86)\Mozilla Firefox C:\Users\hh\.dotnet\tools e:\emacs\.doom.d\bin e:\emacs\.doom.d\bin e:\emacs\.doom.d\bin\pdf-tools e:\emacs\.doom.d\bin\mspyls ~/libexec/emacs/27.0.91/x86_64-w64-mingw32/)
config  envfile    nil
        elc-files  0
        modules    (:completion (company +auto) (ivy +icons +prescient) :ui deft doom doom-dashboard hl-todo hydra indent-guides modeline nav-flash ophints (popup +all +defaults) treemacs vc-gutter vi-tilde-fringe (window-select +numbers) workspaces zen :editor (evil +everywhere) file-templates fold lispy multiple-cursors rotate-text snippets word-wrap :emacs (dired +icons) electric ibuffer vc :tools debugger (eval +overlay) (lookup +docsets) (lsp company) magit pdf rgb upload :lang data emacs-lisp javascript ledger markdown (org +dragndrop +jupyter +pandoc +journal +pomodoro +present) php (python +lsp +pyenv +conda +peek) web :app calendar :config (default +bindings +snippets +smartparens))
        packages   ((spacemacs-theme :pin e088bff4f1) (helm) (counsel-etags) (imenu-list) (importmagic) (color-rg :recipe (:host github :repo manateelazycat/color-rg)) (baidu-translate) (posframe) (find-file-in-project) (keyfreq) (tablist) (org-learn :recipe (:host github :repo emacs-straight/org-mode :files (contrib/lisp/org-learn.el)) :pin 30d0b6e1f6) (org-drill) (org-ref) (org-noter :recipe (:local-repo ~/local/org-noter/) :ignore t) (cal-china-x) (sdcv :recipe (:local-repo ~/local/sdcv) :ignore t))
        unpin      (n/a)
        elpa       (n/a)
```
</pre>
</details>

**Comment by hlissner** [comment]
Emacs on Windows is inherently slower than it is on other OSes, unfortunately, but the 20s initializing the daemon is likely because Doom is configured to immediately load many of its most expensive packages (org, magit, helm, etc) at startup -- because it is assumed, if you use the daemon, you want to front-load the startup process.

I hadn't considered a case where a user wouldn't want this. For the time being, see if adding this to `~/.doom.d/init.el` fixes the issue:

```elisp
(defadvice! dont-load-incremental-packages-eagerly (orig-fn)
  :around #'doom-load-packages-incrementally-h
  (letf! ((#'daemonp #'ignore))
    (funcall orig-fn)))
```

This will change the `daemonp` check [here](https://github.com/hlissner/doom-emacs/blob/develop/core/core.el#L418) to always return false, and thus, defer loading as normal.

**Comment by lld2001** [comment]
Thank you very much. After adding that snippet, it take  6.975s.
`emacs --fg-daemon  --debug-init`
>
DOOM Running doom hook: evil-mode
DOOM Running doom hook: +evil--init-popup-rules-h
DOOM Running doom hook: +workspaces-init-h
Starting Emacs daemon.
DOOM Running doom hook: +doom-dashboard-init-h
DOOM Running doom hook: window-divider-mode
DOOM Running doom hook: +popup-mode
Doom loaded 274 packages across 50 modules in 7.585s
DOOM Loading deferred package savehist from doom--after-call-savehist-h
DOOM [ui/window-select] Loading deferred package winum from doom--after-call-win
um-h
DOOM [editor/evil] Initialized evil-collection-compile
DOOM [editor/evil] Initialized evil-collection-comint
DOOM [editor/evil] Initialized evil-collection-custom
DOOM [editor/evil] Initialized evil-collection-help
DOOM Loading deferred package winner from doom--after-call-winner-h
Package cl is deprecated
DOOM [editor/evil] Initialized evil-collection-which-key
DOOM Incrementally loading tree-widget
DOOM Incrementally loading recentf
Loading e:/emacs/.emacs.d/.local/cache/recentf...
Loading e:/emacs/.emacs.d/.local/cache/recentf...done
DOOM Incrementally loading yasnippet
DOOM [editor/evil] Initialized evil-collection-elisp-mode
[yas] Prepared just-in-time loading of snippets successfully.
DOOM Incrementally loading with-editor
DOOM Incrementally loading git-commit
DOOM [editor/evil] Initialized evil-collection-epa
DOOM [editor/evil] Initialized evil-collection-dired
DOOM [editor/evil] Initialized evil-collection-log-edit
DOOM Incrementally loading package
DOOM Incrementally loading lv
DOOM Incrementally loading magit
DOOM [editor/evil] Initialized evil-collection-diff-mode
DOOM [editor/evil] Initialized evil-collection-magit
DOOM [editor/evil] Initialized evil-collection-calendar
DOOM [editor/evil] Initialized evil-collection-calendar
DOOM [editor/evil] Initialized evil-collection-outline
DOOM [editor/evil] Initialized evil-collection-grep
DOOM [editor/evil] Initialized evil-collection-magit-todos
DOOM Incrementally loading org-agenda
DOOM Incrementally loading org-capture

**Comment by lld2001** [comment]
The previous is minimal config. If it test using my config, there are many `too early!` warnings.
>e:\emacs>bin\emacs --fg-daemon --debug-init
DOOM Running doom hook: evil-mode
DOOM Running doom hook: +evil--init-popup-rules-h
DOOM Running doom hook: +workspaces-init-h
DOOM [editor/evil] Initialized evil-collection-calendar (too early!)
DOOM [editor/evil] Initialized evil-collection-comint (too early!)
DOOM [editor/evil] Initialized evil-collection-custom (too early!)
DOOM [editor/evil] Initialized evil-collection-help (too early!)
DOOM [editor/evil] Initialized evil-collection-calendar (too early!)
Starting Emacs daemon.
DOOM Running doom hook: +doom-dashboard-init-h
DOOM Running doom hook: window-divider-mode
DOOM Running doom hook: +popup-mode
Doom loaded 276 packages across 49 modules in 7.097s
DOOM Loading deferred package savehist from doom--after-call-savehist-h
DOOM [ui/window-select] Loading deferred package winum from doom--after-call-wi
um-h
DOOM [editor/evil] Initialized evil-collection-compile
DOOM Loading deferred package winner from doom--after-call-winner-h
Package cl is deprecated
DOOM [editor/evil] Initialized evil-collection-which-key
DOOM Incrementally loading tree-widget
....

**Comment by hlissner** [comment]
> If it test using my config, there are many too early! warnings.

Yes, that is normal because, normally, Doom would load more at startup for daemon users.

----

As of 42a21df I added a new option you can set from `~/.doom.d/config.el`:

```elisp
(setq doom-incremental-load-immediately nil)
```

With this, you no longer need the advice I suggested.

In any case, I'll consider this resolved. Thanks for bringing it to my attention!
