### ISSUE TITLE
[BUG] void-variable lsp-java-server-install-dir

### ISSUE THREAD

**Issue by sei40kr** [hlissner/doom-emacs#3066]
**What did you expect to happen?**
* Doom Emacs starts without any error.

**What actually happened?**

Please see below.

**Additional details:**
<details><pre>
Warning (initialization): An error occurred while loading ‘/Users/sei40kr/.emacs.d/init.el’:

Error in a Doom module: modules/lang/java/+lsp.el, (void-variable lsp-java-server-install-dir)

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.
</pre></details>

**Steps to reproduce:**
1. Run up-to-date Doom Emacs with `java +lsp` module.

**System information:**
<details><pre>
((emacs
  (version . "27.0.60")
  (features . "RSVG IMAGEMAGICK GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS XWIDGETS PDUMPER LCMS2 GMP")
  (build . "Feb 23, 2020")
  (buildopts "--disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus/HEAD-693749c/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus/HEAD-693749c --with-xml2 --without-dbus --with-gnutls --with-imagemagick --with-modules --with-rsvg --with-xwidgets --with-ns --disable-ns-self-contained")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, upstream/develop, origin/develop, origin/HEAD ab0d37776 2020-05-08 06:23:28 -0400")
  (dir . "~/.doom.d/"))
 (system
  (type . darwin)
  (config . "x86_64-apple-darwin19.3.0")
  (shell . "/usr/local/bin/zsh")
  (uname . "Darwin 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64")
  (path "~/.zinit/plugins/starship---starship" "~/.zinit/plugins/julienXX---terminal-notifier" "~/.zinit/plugins/direnv---direnv" "~/.rbenv/shims" "~/.pyenv/plugins/pyenv-virtualenv/shims" "~/.pyenv/shims" "~/.jenv/shims" "~/.goenv/shims" "~/.zinit/polaris/bin" "~/.local/bin" "~/.yarn/bin" "~/.rbenv/bin" "~/.gem/ruby/2.6.0/bin" "~/.poetry/bin" "~/.pyenv/bin" "~/perl5/bin" "~/perl5/perlbrew/bin" "~/.jenv/bin" "~/.goenv/bin" "~/go/system/bin" "~/.cargo/bin" "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin" "/usr/local/bin" "/usr/local/sbin" "/usr/bin" "/bin" "/usr/sbin" "/sbin" "/Library/TeX/texbin" "/usr/local/Cellar/emacs-plus/HEAD-693749c/libexec/emacs/27.0.60/x86_64-apple-darwin19.3.0"))
 (config
  (envfile . envvar-file)
  (elc-files . 11)
  (modules :completion (company +childframe) ivy :ui doom doom-dashboard hl-todo hydra modeline nav-flash ophints (popup +all +defaults) tabs treemacs vc-gutter window-select workspaces :editor (evil +everywhere) file-templates (format +onsave) multiple-cursors snippets word-wrap :emacs (dired +icons) electric vc :term vterm :checkers (syntax +childframe) spell grammar :tools ansible (debugger +lsp) (docker +lsp) editorconfig ein eval (lookup +docsets +xwidget) lsp (magit +forge) make rgb tmux :lang (cc +lsp) data emacs-lisp (ess +lsp) (go +lsp) (haskell +lsp) (java +lsp) (javascript +lsp) (json +lsp) (kotlin +lsp) (latex +lsp) (markdown +grip) (org +dragndrop +gnuplot +jupyter) perl (php +lsp) plantuml (python +lsp +poetry) rest (ruby +lsp +rails) (rust +lsp) (scala +lsp) (sh +fish +lsp) solidity (web +css +html +lsp) (yaml +lsp) :config (default +bindings +smartparens))
  (packages (company-emoji :pin "fc45b56f3e") (expand-region :pin "0fa7c2d349") (vagrant-tramp :pin "f67925928d") (vimrc-mode :pin "13bc150a87"))
  (unpin "n/a")
  (elpa "n/a")))
</pre></details>

**Comment by hlissner** [comment]
My bad. This should be fixed in fa0d882

**Comment by sei40kr** [comment]
@hlissner Thank you!
