### ISSUE TITLE
[LaTeX] After using fill-paragraph, commands are specially indented

### ISSUE THREAD

**Issue by leonkis** [hlissner/doom-emacs#3068]
When dealing with .tex files, the editor behaves rather oddly when I apply `fill-paragraph` to a paragraph, which is turned into this:
```
Lorem ipsum dolor sit amet, 
consectetur adipiscing elit. Ut 
nec est est. \emph{Sample text 
    inside a command.} Cras 
ante nunc, bibendum sit amet 
accumsan eu, auctor ut ex. 
```
Note that only the lines following the `\emph{}` command are indented in this trailing manner, until that command is closed off by `}`. I would like to disable this sort of indentation **which occurs whenever LaTeX commands are used**. I'd rather just have it indent every line normally. Any suggestions? This perhaps has something to do with Auctex.

**Comment by yoavm448** [comment]
I get your point, but usually this indentation is what I want when defining and writing extended latex commands. Just in text paragraphs it doesn't make sense.
It would be wrong to set no indentation, since then normal latex code commands wouldn't be indented.
And there's no way to check if the point is inside a text paragraph or a block of latex commands. (Especially with TikZ which likes to omit backslashes.)
I think the best solution would be patching `fill-paragraph` to run with indent/tab width = 0, since you just wouldn't normally use that in code segments of your document. Is that acceptable?

**Comment by leonkis** [comment]
> I get your point, but usually this indentation is what I want when defining and writing extended latex commands. Just in text paragraphs it doesn't make sense.
> It would be wrong to set no indentation, since then normal latex code commands wouldn't be indented.
> And there's no way to check if the point is inside a text paragraph or a block of latex commands. (Especially with TikZ which likes to omit backslashes.)
> I think the best solution would be patching `fill-paragraph` to run with indent/tab width = 0, since you just wouldn't normally use that in code segments of your document. Is that acceptable?

Yes, that would be acceptable, how would I do that?

**Comment by yoavm448** [comment]
Actually, I'm not getting this behaviour by default. For me the text inside `emph` is unindented. Something might have changed in Emacs 28 which I'm currently using, but can anyone else try to reproduce?

**Comment by yoavm448** [comment]
Anyway, you could try to set [these variables](https://github.com/editorconfig/editorconfig-emacs/blob/19de0ec1bac67c5a76a4dd3d8ffe6c5411ace1af/editorconfig.el#L364) in a let binding around `fill-paragraph`:
```lisp
(defadvice! +latex-no-indent-on-fill-paragraph (orig-fn &rest args)
  :around #'fill-paragraph
  (let ((tex-indent-basic 0)
        (tex-indent-item 0)
        ...)
    (apply orig-fn args)))
```
(Untested, I can't reproduce.)

**Comment by leonkis** [comment]
Could you clarify a bit? Where am I supposed to put this code?

**Comment by yoavm448** [comment]
Sorry, in your `.doom.d/config.el`.
With all the variables:
```lisp
(defadvice! +latex-no-indent-on-fill-paragraph (orig-fn &rest args)
  :around #'fill-paragraph
  (let ((tex-indent-basic 0)
        (tex-indent-item 0)
        (tex-indent-arg 0)
        (TeX-brace-indent-level 0)
        (LaTeX-indent-level 0)
        (LaTeX-item-indent 0))
    (apply orig-fn args)))
```

**Comment by leonkis** [comment]
Yes, this works! Thank you so much! Could the same be done for indent level 1?

**Comment by yoavm448** [comment]
What do you mean with indent level 1? Like this?
```
nec est est. \emph{Sample text 
 inside a command.} Cras 
ante nunc, bibendum sit amet 
```
You could try to change the zeroes to 1, but I cannot test this...

**Comment by leonkis** [comment]
No, actually, what you wrote originally works beautifully. Disregard the rest. Thank you so much!
