### ISSUE TITLE
ivy-previous-history-element (M-p) selects the previous selection, instead of previous input

### ISSUE THREAD

**Issue by dsdshcym** [hlissner/doom-emacs#3069]
**What did you expect to happen?**
`M-p` (when ivy complete is active) selects the previous input, especially for `counsel-rg`.
This screenshot is what happened after hitting `M-p` in vanilla emacs with ivy: 
<img width="593" alt="image" src="https://user-images.githubusercontent.com/4723751/81415738-6a617c00-917b-11ea-9b26-fe6a328a8fa0.png">

**What actually happened?**
`M-p` selects the previous selection.
This screenshot is what actually happened after hitting `M-p` in doom: 
<img width="757" alt="image" src="https://user-images.githubusercontent.com/4723751/81415764-72b9b700-917b-11ea-9cb7-ae5d8f882d86.png">
As you can see, the previously selected result (`init.example.el:147:       ;;qt                ; the 'cutest' gui framework ever`) gets filled, not the query `test`.

Maybe this is intended, but I cannot which config in doom changes this behavior and how to get the original behavior back.

**Steps to reproduce:**
1. call `counsel-rg` or `+default/search-project`
2. type anything, and select a result
3. call `counsel-rg` again, hit `M-p`

**System information:**
<details>

```
emacs   version    27.0.91
        features   NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS JSON PDUMPER GMP
        build      Apr 27, 2020
        buildopts  (--enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-mac/HEAD-86c4d40/share/info/emacs --prefix=/usr/local/Cellar/emacs-mac/HEAD-86c4d40 --with-mac --enable-mac-app=/usr/local/Cellar/emacs-mac/HEAD-86c4d40 --with-gnutls --with-json)
        windowsys  mac
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop ab0d37776 2020-05-08 06:23:28 -0400
        dir        ~/.doom.d/
system  type       darwin
        config     x86_64-apple-darwin19.4.0
        shell      /usr/local/bin/zsh
        uname      Darwin 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64
        path       (~/.asdf/shims /usr/local/opt/asdf/bin /usr/local/opt/coreutils/libexec/gnubin ~/Projects/dotfiles/usr_local_bin /usr/local/bin /usr/local/sbin /usr/bin /bin /usr/sbin /sbin /usr/local/Cellar/emacs-mac/HEAD-86c4d40/libexec/emacs/27.0.91/x86_64-apple-darwin19.4.0/)
config  envfile    envvar-file
        elc-files  0
        modules    (:input chinese :completion company (ivy +prescient) :ui hl-todo (modeline +light) ophints (popup +defaults) pretty-code vc-gutter :editor (evil +everywhere) file-templates fold (format +onsave) multiple-cursors snippets :emacs dired electric undo vc :term vterm :checkers syntax (spell +everywhere) :tools editorconfig (eval +overlay) gist (lookup +dictionary) lsp macos magit :lang data (elixir +lsp) emacs-lisp erlang fsharp json javascript ledger lua markdown plantuml (ruby +rails +rbenv) sh web yaml :email (mu4e +gmail) :private ui org :config (default +smartparens))
        packages   ((pyim :disable t) (evil-escape :disable t) (evil-find-char-pinyin) (dash-at-point) (nov))
        unpin      (n/a)
        elpa       (use-package smartparens quelpa-use-package quelpa org-plus-contrib dash bind-key)
```
</details>

**Comment by hlissner** [comment]
Doom has never changed the `M-p` keybinding. It is bound to `ivy-previous-history-element` [upstream](https://github.com/abo-abo/swiper/blob/master/ivy.el#L438), so I imagine this is an upstream bug.

In my tests, `M-p` alternates between restoring old inputs and old selections. This should probably be taken upstream.

**Comment by dsdshcym** [comment]
Yes, you are right.
I find this bug was fixed in https://github.com/abo-abo/swiper/issues/2533

I've opened #3071 to bump the ivy version and fix this issue
