### ISSUE TITLE
Org attach errors (on DND action or after selecting pdfs via +org-attach/file fn)

### ISSUE THREAD

**Issue by AloisJanicek** [hlissner/doom-emacs#307]
Hi, when attempting to drag and drop image into emacs (from dolphin into GUI emacs) I am getting `Error: (void-function +org-attach:url)`.
Need surfaced for me to somehow manage attachments as reference to tasks, I discovered Abo-Abo's org-download, which is what Doom's configuration uses as backend, but it somehow doesn't seems to work.
From all attach commands which I found via `M-x`, only `+org-attach/file` seems to produce desired result and **only** with image files (image is embedded into buffer) - with pdf I am getting `user-error: Failed to attach file: Symbol’s function definition is void: org-attach--icon`. I guess from source that I should get file link with some fancy pdf icon, but I don't.

**Comment by hlissner** [comment]
My bad, there were two references to long-gone functions. It should be fixed in `develop` now. I'll leave this open until it's in `master`.

**Comment by AloisJanicek** [comment]
Cool, thanks, everything works now.
I really appreciate all the hard work you have put into Doom Emacs and make it accessible for beginners.

**Comment by hlissner** [comment]
You're very welcome! The fix is now in master.
