### ISSUE TITLE
Project scratch buffers never serialize their content to their bound project files

### ISSUE THREAD

**Issue by Wetlize** [hlissner/doom-emacs#3070]
**What did you expect to happen?**
Project buffers should serialize their content into `doom-scratch-current-project` file, so they can be restored back when their corresponding buffers killed.

**What actually happened?**
Content always ends-up serialized in `doom-scratch-default-file`, so you're never able to restore it back after the buffer is killed.

**Additional details:**
I've spent some time debugging this and found out that what the hell is happening. When  `doom-scratch-initial-major-mode` set to a non-nil value (in my case it's `#'org-mode`) it will switch major-mode as expected, but since the process of switching of major-mode involves the destruction of local-variables (that are not set to be `permanent-local`), the scratch buffer immediately forgets the value of `doom-scratch-current-project`.

The fix should be trivial, Doom should just set somewhere in [this file](https://github.com/hlissner/doom-emacs/tree/develop/core/autoload/scratch.el), that the variable is `permanent-local`, e.g. `(put 'doom-scratch-current-project 'permanent-local t)`.

I didn't make a PR for this, since you might end-up thinking that there's something else can going-on (that I'm not aware of), or need to be changed.

**Steps to reproduce:**
1. Open new project for which you don't have yet any scratch buffer stored.
2. `SPC p x` and write some dummy content in it.
3. Check that `doom-scratch-current-project` never set buffer-locally in the project-scratch buffer.
4. `SPC ; (doom-persist-scratch-buffer-h) RET`.
5. Check your `doom-scratch-dir` for the serialized content, it will most likely end-up in `doom-scratch-default-file`, instead of the dedicated project's file.

**Comment by hlissner** [comment]
> I didn't make a PR for this, since you might end-up thinking that there's something else can going-on (that I'm not aware of), or need to be changed.

No, you were right on the money! This should be fixed as of 4f27d8e. Thanks for looking into it and bringing it to my attention.
