### ISSUE TITLE
Configuration improvement

### ISSUE THREAD

**Issue by umbromancer** [hlissner/doom-emacs#3074]
Hi,

Thank you for Doom!

Doom includes projectile by default, which is great!
The problem is that it sets `projectile-project-root-files-bottom-up` to `.project` and as a new user I struggled to find why setting .projectile was not working. One searches around the web to get a handle on projectile and `.projectile` is bound to surface galore. I expect that this a minor problem for users (for some perhaps leading to some wasted time), but very simple and easy to solve. I propose following the projectile-mode standard of using `.projectile` and simply changing the definition of `projectile-project-root-files-bottom-up` in `core-projects.el`.

**Comment by hlissner** [comment]
This change [was intentional](https://github.com/hlissner/doom-emacs/issues/1974), but I'm coming to realize that it's a source of confusion and so I'll restore `.projectile` soon.
