### ISSUE TITLE
projectile somehow doesn't record new projects at all

### ISSUE THREAD

**Issue by amosbird** [hlissner/doom-emacs#308]
```
Projectile Track Known Projects Automatically is  on

find-file-hook is
(vimish-fold--restore-folds vimish-fold-global-mode-check-buffers evil-snipe-mode-check-buffers evil-snipe-override-mode-check-buffers recentf-track-opened-file smartparens-global-mode-check-buffers projectile-find-file-hook-function evil-mode-check-buffers global-evilified-leader-override-mode-check-buffers auto-insert global-page-break-lines-mode-check-buffers ws-butler-global-mode-check-buffers global-narrow-reindent-mode-check-buffers +upload|init-find-file +vcs|enable-smerge-mode-maybe global-undo-tree-mode-check-buffers undo-tree-load-history-hook
                            #[0 "\302\301!\210\303\304!8\211\207"
                                [buffer-file-name auto-revert-tail-pos make-local-variable 7 file-attributes]
                                3]
                            doom|enable-minor-mode-maybe doom|check-large-file global-font-lock-mode-check-buffers epa-file-find-file-hook vc-refresh-state save-place-find-file-hook)
```

`find-file-hook` contains `projectile-find-file-hook-function` which invokes `(projectile-track-known-projects-find-file-hook)`

However, when doing directory jumps, `(projectile-track-known-projects-find-file-hook)` isn't called. This issue happens recently after I update to 2.0.8.

**Comment by hlissner** [comment]
>after I update to 2.0.8

One possibility comes to mind: you've byte-compiled Doom and you're on the `develop` branch.

I've changed `doom-cache-dir` (and `doom-etc-dir`) in `develop`, so unless you run core/core.el (uncompiled), the new cache folders won't be created, and projectile won't be able to write to cache.

If this sounds right, you'll need to either:

+ Migrate your old files: `mv ~/.emacs.d/.local/$(hostname)/* ~/.emacs.d/.local/`
+ Or un-byte-compile (`make clean`) and restart doom

**Comment by amosbird** [comment]
Nope, I did a refresh update by removing the old `.emacs.d`.

**Comment by hlissner** [comment]
What do you mean by "directory jumps"? Could you provide steps to reproduce?

**Comment by amosbird** [comment]
Um, open dired-mode, entering a git repo that hasn't been tracked by projectile, and it remains untracked.

**Comment by hlissner** [comment]
Could you try

```emacs-lisp
(add-hook 'dired-mode-hook #'projectile-track-known-projects-find-file-hook)
```

And let me know if that solves your issue? If so I will add it to core-projects.el.

**Comment by amosbird** [comment]
Great. it works.

**Comment by amosbird** [comment]
The `find-file-hook` the docstring says "List of functions to be called after a buffer is loaded from a file.", and looks like it doesn't run even with just `find-file' and with a directory.

**Comment by hlissner** [comment]
Alright, fix is in `develop`. I'll leave this open until it's in `master`.

>... looks like it doesn't run even with just `find-file' and with a directory.

Yeah, if `find-file` encounters a directory, it runs through `find-directory-functions`, which hands the directory off to dired without running `find-file-hook`.

What's odd is that projectile has [this line](https://github.com/bbatsov/projectile/blob/master/projectile.el#L3954), which should address this exact problem. If only it was:

```diff
-(add-hook 'dired-before-readin-hook #'projectile-track-known-projects-find-file-hook t t)
+(add-hook 'dired-before-readin-hook #'projectile-track-known-projects-find-file-hook t)
```

then this wouldn't be an issue.

**Comment by hlissner** [comment]
The fix is now in master.
