### ISSUE TITLE
Couldn't resolve parser "php"

### ISSUE THREAD

**Issue by Epse** [hlissner/doom-emacs#3081]
**What did you expect to happen?**
When I edit a PHP file and press `SPC c f`, the file gets formatted.

**What actually happened?**
A new buffer opens up with this line: `[error} Couldn't resolve parser "php"`

**Additional details:**
`SPC c f` is bound to `+format/region-or-buffer`
Config is entirely vanilla, just enabled the web and php packages

**Steps to reproduce:**
1. Open or create a PHP file
2. Run `SPC c f`

**System information:**
<details><pre>
((emacs
  (version . "26.3")
  (features . "XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2")
  (build . "Aug 29, 2019")
  (buildopts "--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-modules 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD 2db423897 2020-05-08 01:27:08 -0400")
  (dir . "~/.doom.d/"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/usr/bin/zsh")
  (uname . "Linux 5.6.11-arch1-1 #1 SMP PREEMPT Wed, 06 May 2020 17:32:37 +0000 x86_64")
  (path "/usr/local/bin" "/usr/bin" "/bin" "/usr/local/sbin" "/opt/cuda/bin" "/usr/lib/jvm/default/bin" "/usr/bin/site_perl" "/usr/bin/vendor_perl" "/usr/bin/core_perl" "~/.gem/ruby/2.3.0/bin" "~/Documents/programming/Go/bin" "~/Android/Sdk/tools" "~/Android/Sdk/platform-tool" "~/.local/bin" "~/.config/composer/vendor/bin" "~/.gem/ruby/2.6.0/bin" "~/.platformio/packages/toolchain-atmelavr/bin" "~/.platformio/penv/bin" "~/.cargo/bin" "~/Documents/School/2019-2020/integratieproject/emsdk" "~/Documents/School/2019-2020/integratieproject/emsdk/node/12.9.1_64bit/bin" "~/Documents/School/2019-2020/integratieproject/emsdk/upstream/emscripten" "~/Documents/School/2019-2020/integratieproject/emsdk/upstream/bin" "~/.gem/ruby/2.6.0/bin" "/usr/lib/emacs/26.3/x86_64-pc-linux-gnu"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline ophints (popup +defaults) vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold snippets :emacs dired electric undo vc :term vterm :checkers syntax spell grammar :tools editorconfig (eval +overlay) lookup lsp magit pdf rgb :lang elixir emacs-lisp json javascript latex ledger markdown (org +pandoc) php python sh web :config (default +bindings +smartparens))
  (packages (evil-escape :disable t))
  (unpin "n/a")
  (elpa "n/a")))
</pre></details>

**Comment by hlissner** [comment]
Have you installed https://github.com/FriendsOfPhp/PHP-CS-Fixer?

**Comment by Epse** [comment]
I have now (maybe it should be added to `doom doctor` if it's required?) but I still get the same issue. I installed it globally using composer, if that matters, and ran `doom env` again, to make sure it had the latest PATH.

**Comment by AloisJanicek** [comment]
I fixed it by install `prettier-php` aka [plugin-php](https://github.com/prettier/plugin-php):

```
npm install -g @prettier/plugin-php
```

**Comment by hlissner** [comment]
@Epse Does that resolve the issue for you? If so I'll update the docs.

**Comment by Epse** [comment]
Yes that fixes the issue, I was very busy with a thesis and thus unable to quickly check. I suppose some docs changes (and `doctor` changes) would be a perfectly adequate fix. I'd make a PR but my elisp is shoddy and you'd have to spend more time fixing it than adding the check I presume.

**Comment by hlissner** [comment]
Sorry for the tremendously late response. I've updated lang/php's docs to mention `@prettier/plugin-php`, We may need a doctor check for it, but I'm not aware of any way to detect it from the command line atm. I'll revisit it once I look into it.

In any case, thanks for bringing it to my attention.
