### ISSUE TITLE
Dashboard enhancements

### ISSUE THREAD

**Issue by aminb** [hlissner/doom-emacs#309]
I've been thinking about this for a while, and I think it'd be nice

- if one could set the default directory for the dashboard. I tried defining a helper function for myself, something like this, but it doesn't seem to work (maybe due to `(switch-to-buffer (doom-fallback-buffer)` in `+doom-dashboard/open`?):
```elisp
(defun doom-dashboard-home ()
  "Open the Doom dashboard at ~/"
  (interactive)
  (let ((default-directory (expand-file-name "~/")))
    (progn
      (cd default-directory)
      (+doom-dashboard/open (selected-frame)))))
```

- if there was an option to disable Doom's behaviour of `cd`ing into the directory that contains the file the current buffer is visiting. I'm pretty sure Emacs by default doesn't do this, and Doom's behaviour has been a bit of an annoyance with my Magit workflow when doing `magit-status`. I have a solution for this (calling `magit-status` with a prefix arg, which forces it to ask for the repo location even if the current directory is a repo), but ideally there would be an option to disable this behaviour of Doom, either only in the dashboard (related to my previous point) or globally for all buffers.

**Comment by hlissner** [comment]
> if there was an option to disable Doom's behaviour of cding into the directory that contains the file the current buffer is visiting.

The default behavior of Doom's dashboard (when switching to it) is to cd into the project root of the last buffer you had open. I do this because it's annoying to accidentally close the last project buffer, land on the dashboard, and suddenly be in another project.

That said, I'll look into adding an option to change (and disable) this behavior.

>or globally for all buffers.

Globally? I take it you're a vimmer (as am I), and you're referring to how the cwd doesn't follow the current file. If so, I sympathize. I prefer that behavior too. Alas, this _is_ an Emacs thing that can't be changed. I've gotten used to it. I've even added `autocmd BufEnter * silent! lcd %:p:h` to my vimrc.

That said, this should not interfere with magit. Magit seeks out the nearest git root from the current directory upward. So unless you have nested git repos, I don't understand why it gives you trouble. Could you shed some more like on how it interferes with your workflow?

**Comment by hlissner** [comment]
Just added [+doom-dashboard-pwd-policy](https://github.com/hlissner/doom-emacs/blob/develop/modules/ui/doom-dashboard/config.el#L16) to ui/doom-dashboard. To replicate your `doom-dashboard-home` you can set this to a fixed path string:

```emacs-lisp
(setq +doom-dashboard-pwd-policy "~")
```

**Comment by aminb** [comment]
Perfect, thanks!

Also, yup, I do come from vim 😁 Although that was a good 3-4 years ago.

As for my workflow, I just went and dug up my old Emacs config and trying to remember my old workflow, I realized part of what I remembered about it was wrong. So on my old setup, just like Doom's, `magit-status` would open up the current git repo (if the current dir is one); so there's no difference there. But what I *did* realized differed was when closing the last buffer, I'd go back to `*scratch*`, whose cwd doesn't change (is the same one Emacs starts with, in my case `~/`, which is not a git repo), so I could easily do `magit-status` and switch to whatever other project I wanted. Whereas in Doom, closing the last buffer would bring up the dashboard which as you said, up to today, its cwd would be the project root of the last open buffer. Therefore, after closing the last buffer or invoking my "open dashboard" binding I wouldn't get to choose the git repo I'd like to switch to next.

Btw I see you made `+doom-dashboard-pwd-policy` even more flexile than my [current] preference. That's great, kudos!

**Comment by aminb** [comment]
@hlissner It seems like one of the commits in range 86f445d..HEAD (probably 86f445d itself) "broke" `+doom-dashboard-pwd-policy`, as setting it to `~/` doesn't seem to have any effects (e.g. Doom still starts with `~/.emacs.d/` as dashboard's directory). 6c3d7ad works fine though.

**Comment by hlissner** [comment]
I noticed some inconsistencies to when the dashboard decided to update the pwd, and discovered `+doom-dashboard-reload` wasn't always reloading the dashboard (a performance feature). So I moved the pwd-updating code outside of the condition and it (seem to) work perfectly now. Let me know if it gives you any trouble!

**Comment by hlissner** [comment]
Actually, this issue runs even deeper and needs further investigation, so I'll consider this issue unresolved until I make some much needed improvements to buffer management in general in Doom.

**Comment by aminb** [comment]
Thanks for the update and for looking into this. I'll keep an eye on `develop` then :)

**Comment by hlissner** [comment]
Alright, with the latest chain of updates this should be fixed. Give it a try and let me know if it gives you trouble!

**Comment by aminb** [comment]
Seems to be working great, thanks!

**Comment by aminb** [comment]
Hmm was there a change in the logic that handles closing of buffers/windows? I just noticed that doing `q` in `notmuch` doesn't close any of its buffers anymore. Same with doing `C-c C-k` in `notmuch-message-mode`, or `q` in `ibuffer` (and probably more).

**Comment by hlissner** [comment]
What is `C-c C-k` bound to?

**Comment by aminb** [comment]
Yeah, basically. it's bound to `message-kill-buffer` (from `message-mode`).

**Comment by hlissner** [comment]
Turns out this is standard Emacs behavior. In most of these buffers `q` is bound to `quit-buffer`, which doesn't kill the contained buffer. I'm tempted to add something like:

```emacs-lisp
(defun doom*quit-window (orig-fn &optional kill window)
  (funcall orig-fn (not kill) window))
(advice-add #'quit-window :around #'doom*quit-window)
```

In fact, I think I'll run with this for a while. It's rare that I _don't_ want the buffer killed with the window. 

That said, I expect corner case issues, possibly with magit. If you're a magit user, could you give this a try?

**Comment by aminb** [comment]
Hmm, what is Emacs's standard behaviour?

Adding that `advice` doesn't seem to have any effects. I still can't close various `notmuch` buffers with `q` and `message-mode` with `C-c C-k`.

Also, I just tested and it seems like `magit-status` is unaffected by this issue. However, `ibuffer` is acting weird: before this issue appeared, it didn't have Doom's modeline, and pressing `q` would quit. With this issue, pressing `q` makes the Doom modeline show up and pressing it again will quit. But with `notmuch` pressing `q` doesn't do anything.

**Comment by hlissner** [comment]
> Hmm, what is Emacs's standard behaviour?

That`q` runs `quit-window`, which doesn't kill buffers and only deletes the window.

That said, I'm looking into the `notmuch` issue. As for `ibuffer`, could you try:

```emacs-lisp
(setq ibuffer-use-other-window t)
```

This should make Doom's popup system handle ibuffer windows, which comes with the added benefit of buffer management (and removal of the mode-line) for its window.

**Comment by aminb** [comment]
> That `q` runs `quit-window`, which doesn't kill buffers and only deletes the window.

Gotcha!

I just pulled latest `develop`, and the issues I had seem to be resolved! `ibuffer` now opens up in a popup (thanks to 8134c49e) and `q` closes it without any trouble. The only thing I want to figure out now is whether I can get `ibuffer` to open the chosen buffer in the existing window (replacing the buffer I was looking at) instead of opening it in a new window.

Also, my issues with `notmuch` seem to have been resolved as well. The only difference I've noticed is that now doing `q` on the last remaining `notmuch` buffer drops me into `*scratch*` if there aren't any workspace buffers open. I think ideally quitting `notmuch` when there are no real buffers open would drop me into the Doom dashboard instead of `*scratch*`.

**Comment by hlissner** [comment]
> I just pulled latest develop, and the issues I had seem to be resolved! 

Wonderful!

> The only thing I want to figure out now is whether I can get ibuffer to open the chosen buffer in the existing window (replacing the buffer I was looking at) instead of opening it in a new window.

I just pushed a little tweak to `develop`. You could try:

```emacs-lisp
(set! :popup "*Ibuffer*" :same t :autokill t)
```

And this may get you the behavior you want. It won't open in a popup anymore, however (though, I may be able to manage this after I've done my planned rewrite of the popup management system).

> The only difference I've noticed is that now doing q on the last remaining notmuch buffer drops me into *scratch* if there aren't any workspace buffers open.

That is certainly a bug, and it may be related to your weechat issues in your emails. I'll follow up on all this there.

---

Anyhow, the fix for the original issue is now in master, so I will consider this thread resolved.

**Comment by aminb** [comment]
> This should get you the behavior you want. It won't open in a popup anymore, however (though, I may be able to manage this after I've done my planned rewrite of the popup management system).

Yup, that does it! But I might stay with the current way and keep it as a popup for now, and hope that your rewrite would give best of both worlds :p 

> That is certainly a bug, and it may be related to your weechat issues in your emails. I'll follow up on all this there.

Sounds great, thanks!
