### ISSUE TITLE
`C-i` is the same as `TAB` -- make `C-i` distinct

### ISSUE THREAD

**Issue by simendsjo** [hlissner/doom-emacs#3090]
When I check what C-i is bound to `C-h k C-i`, emacs says I've pressed `TAB`

```
Key Bindings
evil-org-mode-map <normal-state> <tab>
evil-org-mode-map <normal-state> TAB
evil-org-mode-map <visual-state> <tab>
evil-org-mode-map <visual-state> TAB
org-mode-map <tab>
org-mode-map TAB
```

This means I've lost `C-i`, and the regular "jump forward" keybinding.
Spacemacs has a workaround for this, but i guess there's more to it than just
this snippet as `C-h k C-i` reports that `<C-i>` is unbound rather than `C-i` is
unbound after using it.

```lisp
(defun spacemacs/translate-C-i (_)
  "If `dotspacemacs-distinguish-gui-tab' is non nil, the raw key
sequence does not include <tab> or <kp-tab>, and we are in the
gui, translate to [C-i]. Otherwise, [9] (TAB)."
  (interactive)
  (if (and (not (cl-position 'tab (this-single-command-raw-keys)))
           (not (cl-position 'kp-tab (this-single-command-raw-keys)))
           dotspacemacs-distinguish-gui-tab
           (display-graphic-p))
      [C-i] [?\C-i]))
(define-key key-translation-map [?\C-i] 'spacemacs/translate-C-i)
```

**Comment by hlissner** [comment]
I've added this in 63ab881. Let me know if that doesn't fix the issue and I'll reopen it. Thanks for bringing it to my attention!

**Comment by simendsjo** [comment]
> I've added this in [63ab881](https://github.com/hlissner/doom-emacs/commit/63ab88105f7c64b9b3e59546906ec5fe5857303a). Let me know if that doesn't fix the issue and I'll reopen it. Thanks for bringing it to my attention!

Unfortunately, `<C-i>` doesn't include any bindings, and trying to bind something with `map! "C-i"` doesn't work either. Does "C-i" need to be translated to `<C-i>` in `map!` or something?

**Comment by hlissner** [comment]
> Does "C-i" need to be translated to <C-i> in map! or something?

That will just break TAB.

There isn't much we can do here, unfortunately. While this workaround allows us to bind separately to `C-i` and `<C-i>`, it won't magically remap keybinds any plugins will bind to `TAB` or `C-i`.

**Comment by simendsjo** [comment]
> > Does "C-i" need to be translated to  in map! or something?
> 
> That will just break TAB.
> 
> There isn't much we can do here, unfortunately. While this workaround allows us to bind separately to `C-i` and `<C-i>`, it won't magically remap keybinds any plugins will bind to `TAB` or `C-i`.

I understand we cannot solve the issue where other plugins map to C-i, but I was thinking about in Doom. Doesn't people bind TAB when they mean tab? So mapping TAB/<tab> would still map tab, but mapping "C-i" could rather map "<C-i>"? At least I find it confusing that C-c is C-c, C-i is tab and <C-i> is C-i.

**Comment by hlissner** [comment]
People bind to `TAB` when they want terminal support for a keybind and `[tab]` for GUI Emacs exclusively (GUI Emacs will fall back on `TAB` if no `[tab]` keybind exists).

In Doom's case, I do what most plugins do: bind to both, as to mitigate the risk of upstream keybinds on [tab] overwriting our keybinds on TAB _and_ so terminal users can still enjoy those keybinds.

The situation is certainly messy, and `C-i` is the unfortunate sacrifice, but at least it's only one sacrifice.

**Comment by rodelrod** [comment]
@hlissner I understand the reasons for reverting the commit. Maybe this deserves an entry in the FAQ, with the fix and the known consequences? My use case is having `better-jumper-jump-forward` bound to `C-i` in Org files. Not sure if there are other common use cases.

**Comment by simendsjo** [comment]
I've yet to see any problems from this. Maybe we should add it back and let it be optional? I'm using it in my config at least as I need C-i to be jump-forward :) I've yet to encounter problems with it as I never want anyone to override my jump-forward.
