### ISSUE TITLE
eshell: when splitting, retain the current default-directory

### ISSUE THREAD

**Issue by UndeadKernel** [hlissner/doom-emacs#3091]
**Describe the feature**
When using either `+eshell/split-vertically` or `+eshell/split-horizontally`, the newly spawned buffers could start eshell using the same default-directory of the eshell buffer from where the splits were made.

This would be specially helpful when eshell is operating over an ssh connection: a newly split eshell window would start in the same remote location as the first terminal.

If this sounds interesting, I would even be happy to implement it myself and PR it.

**Comment by hlissner** [comment]
As of de27b2c its `default-directory` should be preserved across splits. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
