### ISSUE TITLE
Prolog / Mercury Layer

### ISSUE THREAD

**Issue by brettgilio** [hlissner/doom-emacs#3097]
I would like to propose the addition of a prolog / mercury module. There is an issue with Emacs where both prolog and mercury modes for emacs are some degree of bitrotten, which is why this was written: https://github.com/ahungry/metal-mercury-mode

**Comment by hlissner** [comment]
Hi! I'm open to new modules, but I cannot accept a module whose config is so trivial that a user could set it up themselves in one or two lines. A cursory look at metal-mercury-mode tells me there isn't enough to it to warrant a module.

Is there a larger ecosystem of Emacs plugins (or just more configuration in general) that metal-mercury-mode could benefit from? I see a [flycheck-mercury](https://github.com/flycheck/flycheck-mercury), but I'm not sure if it's bitrotten too.
