### ISSUE TITLE
org-habit graph not resized on first org-agenda launch

### ISSUE THREAD

**Issue by alarsyo** [hlissner/doom-emacs#3102]
**What did you expect to happen?**

On first open of `org-agenda`, habit graph is resized thanks to `+org-habit-resize-graph-h`.

**What actually happened?**

The hook runs when `org-agenda` is opened, but the graph doesn't seem to use the size variables until org-agenda is refreshed reloaded (for evil users, tapping `r` in the agenda buffer is enough to fix things).

It's definitely a minor problem, that only manifests itself the first time the agenda is opened. I'm guessing the problem comes from 129eebc, since the `+org-habit-resize-graph-h` is no longer run on `org-load-hook` like `+org-init-habit-h` was before this commit. I'm not good at elisp, but can't you put back the `+org-habit-resize-graph-h` function back in functions ran by `org-load-hook`, but with the `(featurep 'org-habit)` feature check ?

**Steps to reproduce:**
1. Open a new instance of emacs
2. Open org-agenda, with a habit scheduled today
3. Habit graph is not prettily sized
4. Run `org-agenda-redo` (`g r` in the agenda buffer for evil users)
5. Habit graph is correctly sized

**System information:**

<details>

```
emacs   version    26.3
        features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2
        build      Aug 29, 2019
        buildopts  (--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-modules 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now)
        windowsys  x
        daemonp    daemon
doom    version    2.0.9
        build      HEAD -> develop 1529dcaaf 2020-05-11 05:32:51 -0400
        dir        ~/.doom.d/
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /usr/bin/zsh
        uname      Linux 5.4.39-1-lts #1 SMP Wed, 06 May 2020 17:32:42 +0000 x86_64
        path       (/usr/local/texlive/2019/bin/x86_64-linux ~/.local/gcc-arm/bin ~/.node_modules/bin /usr/local/texlive/2019/bin/x86_64-linux ~/.local/gcc-arm/bin ~/.node_modules/bin /usr/local/sbin /usr/local/bin /usr/bin /opt/flutter/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl ~/.local/bin ~/.cargo/bin ~/.local/bin ~/go/bin /opt/flutter/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl ~/.cargo/bin ~/.local/bin ~/go/bin /usr/lib/emacs/26.3/x86_64-pc-linux-gnu/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company (ivy +icons) :ui doom fill-column hl-todo (modeline +light) (popup +defaults) vc-gutter :editor (evil +everywhere) fold snippets :emacs dired undo vc :checkers syntax :tools lookup lsp magit rgb :lang cc emacs-lisp (go +lsp) haskell latex markdown nix ocaml (org +journal +roam) (rust +lsp) sh yaml :config literate (default +bindings +smartparens))
        packages   ((solaire-mode :disable t))
        unpin      (n/a)
        elpa       (n/a)
```
</details>

**Comment by hlissner** [comment]
As of bc5bbb1 I've half-reverted the change. You should have this in your config though:

```elisp
(after! org
  (add-to-list 'org-modules 'org-habit))
```

Let me know if it doesn't work and I'll reopen the issue. Thanks for bringing it to my attention!

**Comment by alarsyo** [comment]
That's strange, that doesn't seem to work. I do have `(add-to-list 'org-modules 'org-habit)` in my config. Behavior is the same as before.

More precisions: if I describe variables such as `org-habit-graph-column`, or `org-habit-preceding-days` after the first opening of `org-agenda`, then run `org-agenda-redo`, then look at their new values, they've changed. So the function doesn't seem to run until the second load :/

**Comment by hlissner** [comment]
Could you provide an example org file? I'm not familiar enough with org-habit and need a test file.

**Comment by alarsyo** [comment]
Sure !

```
* TODO Hack on Doom
SCHEDULED: <2020-05-15 Fri .+1d>
:PROPERTIES:
:STYLE:    habit
:END:
```

Having something like this in an `org-agenda-file` should be sufficient

**Comment by gksbrandon** [comment]
Seeing the same issue, on reload it re-aligns. Calling org-agenda again shows it re-aligned, it's the first call that shows it incorrectly aligned.

**Comment by carlosperezm** [comment]
I report the same issue with my configuration.
