### ISSUE TITLE
Org-roam would be a nice feature

### ISSUE THREAD

**Issue by Padraic-O-Mhuiris** [hlissner/doom-emacs#3107]
[org-roam](https://github.com/org-roam/org-roam)

**Comment by hlissner** [comment]
Enable the `:lang (org +roam)` module, as [documented in org-roam's documentation](https://org-roam.readthedocs.io/en/master/installation/#doom-emacs), or [the readme for Doom's org module](https://github.com/hlissner/doom-emacs/blob/develop/modules/lang/org/README.org#module-flags).
