### ISSUE TITLE
Neotree folder structure closes when using evil-window-close

### ISSUE THREAD

**Issue by andyafter** [hlissner/doom-emacs#311]
Whenever I close window with either C-x 0 or SPC-w-c, neotree folder structure closes for some reason. Not sure if this is a feature or a bug.

**Comment by hlissner** [comment]
I'm unable to reproduce this. Please post the output of `make doctor` either here or in your other issue so I can get more insight into your Emacs environment. Also, a few more questions:

+ What command does `C-c 0` execute? (Run `M-x describe-key RET C-c 0` to find out) This binding is not in Doom and I am not aware of it.
+ Does this behavior produce any messages/errors? (`SPC h m` will pop up the messages buffer)
+ Are you running these commands from inside the neotree panel or outside it? And if outside it, how many windows do you have open?

If it isn't too much trouble can you capture a gif of the issue?

**Comment by andyafter** [comment]
Somehow it works for me well this morning.
