### ISSUE TITLE
How do I can restore last window layout quickly?

### ISSUE THREAD

**Issue by JamesYuan** [hlissner/doom-emacs#3112]
> Please visit our Discord server to ask how-to and workflow questions:
> https://discord.gg/qvGgnVx -- post on Doom's issue tracker as a last resort.

**What are you trying to achieve?**
I have two or more window layout, but focus on one of them sometime. After that, how can restore the last window layout quickly?

**What have you tried?**
M-x to search some *restore* window command, but no such one.

**Additional information**
- Do you have screenshots/casts of this workflow in another editor or Emacs
  distro? (If possible, include names of specific commands or functions from
  other editors/emacs distros)
- Do you have additional material or links to resources that could help clarify
  what you are trying to do?

**System information**
<details><pre>
Include the output of `M-x doom/info` or `~/.emacs.d/bin/doom info` here.
</pre></details>

**Comment by hlissner** [comment]
With the `:ui workspaces` module enabled, Doom has `persp-mode` installed. Here are some keys that'll help you with it:

- `SPC TAB n` creates a blank, new workspace, which you can consider an independent "layout".
- `SPC TAB 1` will switch back to the first workspace
- `SPC TAB 2` switch back to the second, and so on all the way to 9
- `SPC TAB d` will delete a workspace

**Comment by JamesYuan** [comment]
It works. Thank you @hlissner .
