### ISSUE TITLE
Can't display images inline in orgmode (Windows 10)

### ISSUE THREAD

**Issue by Aetiuss** [hlissner/doom-emacs#3114]
**Did `SPC :`  and "orgmode-display-inline-images" on an jpg link I precedently inserted but nothing happened, emacs only told me that "there is no image to display inline".**

**Tried running the command after selecting the link in visual mode but nothing either.**

**When I click on the link it opens a new buffer and display the image inside it though.**

**Additional details:**
- Windows 10
- See my config.el below
<pre><details>
;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-

;; Place your private configuration here! Remember, you do not need to run 'doom
;; sync' after modifying this file!

;; Some functionality uses this to identify you, e.g. GPG configuration, email
;; clients, file templates and snippets.
(setq user-full-name "Jules Bader"
      user-mail-address "jules.bader156@gmail.com")

;; Doom exposes five (optional) variables for controlling fonts in Doom. Here
;; are the three important ones:
;;
;; + `doom-font'
;; + `doom-variable-pitch-font'
;; + `doom-big-font' -- used for `doom-big-font-mode'; use this for
;;   presentations or streaming.
;;
;; They all accept either a font-spec, font string ("Input Mono-12"), or xlfd
;; font string. You generally only need these two:
(setq doom-font (font-spec :family "Lucida Sans Typewriter Regular" :size 18)
      doom-big-font (font-spec :family "monospace" :size 32)
      doom-variable-pitch-font (font-spec :family "monospace" :size 16))
;; There are two ways to load a theme. Both assume the theme is installed and
;; available. You can either set `doom-theme' or manually load a theme with the
;; `load-theme' function. This is the default:
(setq doom-theme 'doom-one)

;; If you use `org' and don't want your org files in the default location below,
;; change `org-directory'. It must be set before org loads!
(setq org-directory "~/org/")

;; This determines the style of line numbers in effect. If set to `nil', line
;; numbers are disabled. For relative line numbers, set this to `relative'.
(setq display-line-numbers-type 'relative)

;; Suppresses de dialog line when exite emacs
(setq confirm-kill-emacs nil)

;; Enables line wrapping according window size
(global-visual-line-mode t)

;; Change the character size of a line before auto-return
(setq-default fill-column 73)

;; Add auto-save
(setq auto-save-default t)

(setq auto-save-timeout 15)

(when window-system
  (set-frame-position (selected-frame) -1074 0) ;; 0 - left edge at
;;  left of monitor; 550 - top about halfway down the monitor
  (set-frame-size (selected-frame) 923 966 t)) ;; 115 - width full width of
;;  monitor; 13 - puts bottom at top of taskbar

(setq projectile-indexing-method 'hybrid)
(setq projectile-completion-system 'ivy)

(setq default-directory "C:/Users/Jules/Desktop/" )

;;(find-file "C:/Users/Jules/Desktop/todo-avril-2020.org")

(setq org-adapt-indentation 'nil)

;; projectile fix
(after! projectile
  (setq projectile-generic-command
        (mapconcat #'shell-quote-argument
                   (append (list "rg" "-0" "--files" "--follow" "--color=never" "--hidden")
                           (cl-loop for dir in projectile-globally-ignored-directories
                                    collect "--glob"
                                    collect (concat "!" dir))
                           )
                   " ")
        projectile-git-command projectile-generic-command))

;; Display images in orgmode
(defun do-org-show-all-inline-images ()
  (interactive)
  (org-display-inline-images t t))
(global-set-key (kbd "C-c C-x C v")
                'do-org-show-all-inline-images)

;; Keyboard Shortcuts remaping
 (map!
  (:leader
    :n ";" #'counsel-find-file
    :n "." #'pp-eval-expression
   )
;;  :n "j" #'evil-backward-char
;;  :n "k" #'evil-next-line
;;  :n "l" #'evil-previous-line
;;  :n "m" #'evil-forward-char
  )
;; Here are some additional functions/macros that could help you configure Doom:
;;
;; - `load!' for loading external *.el files relative to this one
;; - `use-package' for configuring packages
;; - `after!' for running code after a package has loaded
;; - `add-load-path!' for adding directories to the `load-path', relative to
;;   this file. Emacs searches the `load-path' when you load packages with
;;   `require' or `use-package'.
;; - `map!' for binding new keys
;;
;; To get information about any of these functions/macros, move the cursor over
;; the highlighted symbol at press 'K' (non-evil users must press 'C-c g k').
;; This will open documentation for it, including demos of how they are used.
;;
;; You can also try 'gd' (or 'C-c g d') to jump to their definition and see how
;; they are implemented.
</pre></details>

**Comment by yoavm448** [comment]
What is the exact link you pasted? Org will inline images only if the link is a file link with no description, e.g `[[file:this-image.jpg]]`.

**Comment by Aetiuss** [comment]
I just manage to inline a link with a description  `[[/root/Desktop/f.jpg][f]]` on my linux box, I don't think you right or I might have missunderstanded you.

**Comment by yoavm448** [comment]
Huh. Turns out descriptions do work, sorry. But I still need the `file:` prefix for the images to inline...

**Comment by earvingad** [comment]
Emacs on Windows displays inline images with `[[file:/path/to/the/image]]`

**Comment by Aetiuss** [comment]
Oooh I understand I had to select the file option, I was just pasting the path raw, with the file option it works perfect, thank you both very much !
