### ISSUE TITLE
What would I lose by using Doom with Emacs 26 instead of 27? (macOS)

### ISSUE THREAD

**Issue by mrbig033** [hlissner/doom-emacs#3118]
I installed Emacs 26.3 with Homebrew. I wish to install Doom Emacs, but the Readme says 27 is preferable. I'm not familiar enough with macOS, but from my short experience compiling from source would bring issues since many manual adaptations would be required.

I use a lot of packages and have many personal settings, so before install Doom I'd like to know what will I be losing exactly.

Thanks!

**Comment by hlissner** [comment]
Mainly, performance with LSP and similar external processes/servers. Specifically:

1. 27 introduces a native JSON library, which consumes less memory and performs faster than the json.el library in Emacs 26.
2. LSP servers (and others, like tide and robe) communicate in JSON, and they tend to have *much* to say to Emacs. This hits Emacs' garbage collector hard.
3. In 27 we can increase the buffer size between processes and Emacs (from its 4kb default). LSP servers (and others, like tide and robe), tend to dump a lot more than 4kb at a time, which Emacs struggles to play catch up with, over time.

That said, Emacs 26 will still work fine, and it's possible you may not run into these problems (or it won't hit you so hard).

Although, you can avoid having to build anything by installing Emacs through homebrew, via the `emacs-plus` recipe with:

```sh
brew tap d12frosted/emacs-plus
brew install emacs-plus --HEAD --with-jansson --with-emacs-27-branch
ln -s /usr/local/opt/emacs-plus/Emacs.app /Applications/Emacs.app
```

Hope that helps!

**Comment by mrbig033** [comment]
Thank you very much. I'll be mainly using Elpy for now, does that use LSP? I tried Emacs Plus before but it made Emacs "too native"... the Meta key on this package does not behave the way Emacs "wants", but just like it does in the rest of macOS: as a way to insert a bunch of characters I do not need. I use numerous Meta keybindings, either customized, native, or coming from packages. That's a deal-breaker for me, I opened an issue over there but could not resolve this, unfortunately.

**Comment by hlissner** [comment]
I would not recommend using `brew cask install emacs`, as the emacsformacosx build lacks a few features that you may need later.

Elpy doesn't use LSP, but it does communicate with a lot of processes.

> the Meta key on this package does not behave the way Emacs "wants", but just like it does in the rest of macOS: as a way to insert a bunch of exotic characters I do not need

This can be fixed inside Emacs by customizing `mac-option-modifier` or `mac-right-option-modifier`. Doom already sets these to `'meta`, and so option will not insert exotic characters, but operate as the meta modifier key.

**Comment by mrbig033** [comment]
You not only give support for your distribution but for Emacs as a whole. Awesome, thanks! I'll that. Since I'll jump from 26 anyway, couldn't I just go for 28, or that would be too much?

**Comment by hlissner** [comment]
> couldn't I just go for 28, or that would be too much?

You could try -- there are some users who do with success -- but whether or not 28 works with Doom changes from week to week, so YMMV. I can't support it because it's such a moving target, while 27 is pretty much frozen at this point (and is due to be released any week now).

**Comment by mrbig033** [comment]
Okay then, 27 it is. Thanks!

**Comment by hlissner** [comment]
Glad I could help!
