### ISSUE TITLE
Missing Perl modules on Latex formatting

### ISSUE THREAD

**Issue by Epse** [hlissner/doom-emacs#3121]
**What did you expect to happen?**
When running `SPC c f` the LaTeX buffer get's formatted.

**What actually happened?**
An error message pops up (see below). I tried installing Log4Perl via my distro's repositories, but the error starts to complain about a missing File Backend.

**Additional details:**
Vanilla config, error message below

<details><pre>
Can't locate Log/Log4perl.pm in @INC (you may need to install the Log::Log4perl module) (@INC contains: /usr/share/texmf-dist/scripts/latexindent /usr/lib/perl5/5.30/site_perl /usr/share/perl5/site_perl /usr/lib/perl5/5.30/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/5.30/core_perl /usr/share/perl5/core_perl) at /usr/share/texmf-dist/scripts/latexindent/LatexIndent/LogFile.pm line 22.
BEGIN failed--compilation aborted at /usr/share/texmf-dist/scripts/latexindent/LatexIndent/LogFile.pm line 22.
Compilation failed in require at /usr/share/texmf-dist/scripts/latexindent/LatexIndent/Document.pm line 25.
BEGIN failed--compilation aborted at /usr/share/texmf-dist/scripts/latexindent/LatexIndent/Document.pm line 25.
Compilation failed in require at /usr/bin/latexindent line 27.
BEGIN failed--compilation aborted at /usr/bin/latexindent line 27.
</pre></details>

**Steps to reproduce:**
1. Open a random LaTeX buffer
2. Run `SPC c f`

**System information:**
<details>

```
emacs   version    26.3
        features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2
        build      Aug 29, 2019
        buildopts  (--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-modules 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now)
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop, origin/develop, origin/HEAD 2db423897 2020-05-08 01:27:08 -0400
        dir        ~/.doom.d/
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /usr/bin/zsh
        uname      Linux 5.6.11-arch1-1 #1 SMP PREEMPT Wed, 06 May 2020 17:32:37 +0000 x86_64
        path       (/usr/local/bin /usr/bin /bin /usr/local/sbin /opt/cuda/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl ~/.gem/ruby/2.3.0/bin ~/Documents/programming/Go/bin ~/Android/Sdk/tools ~/Android/Sdk/platform-tool ~/.local/bin ~/.config/composer/vendor/bin ~/.gem/ruby/2.6.0/bin ~/.platformio/packages/toolchain-atmelavr/bin ~/.platformio/penv/bin ~/.cargo/bin ~/Documents/School/2019-2020/integratieproject/emsdk ~/Documents/School/2019-2020/integratieproject/emsdk/node/12.9.1_64bit/bin ~/Documents/School/2019-2020/integratieproject/emsdk/upstream/emscripten ~/Documents/School/2019-2020/integratieproject/emsdk/upstream/bin ~/.gem/ruby/2.6.0/bin /usr/lib/emacs/26.3/x86_64-pc-linux-gnu/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline ophints (popup +defaults) vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold snippets :emacs dired electric undo vc :term vterm :checkers syntax spell grammar :tools editorconfig (eval +overlay) lookup lsp magit pdf rgb :lang elixir emacs-lisp json javascript latex ledger markdown (org +pandoc) php python sh web :config (default +bindings +smartparens))
        packages   ((evil-escape :disable t))
        unpin      (n/a)
        elpa       (n/a)
```
</details>

**Comment by yoavm448** [comment]
This seems more like an issue with the installation of latexindent. Can I recommend to just use `evil-indent` (operator under `=` in normal mode)? It has roughly the same effect here while not relying on external programs.

**Comment by stkSGarcia** [comment]
Maybe you should install (via `cpan`) the following packages to fix the error message:

```
Log::Log4perl
Log::Dispatch::File
YAML::Tiny
File::HomeDir
Unicode::GCString
```

**Comment by Epse** [comment]
Thanks @stkSGarcia !

After installing these, I get a new error. This time it says in the statusbar `Wrong type argument: commandp, +format/region-or-buffer`.

**Comment by hlissner** [comment]
@Epse You'll need to [enable](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#modules) the `:editor format` module.

**Comment by Epse** [comment]
Yes, sorry I forgot to re-enable that (the auto-formatting got annoying, what with it's crashing).

It now pops up a new window with `Please enter text to be formatted: (press CTRL-D when finished)` the buffer is called `*format-all-errors*`. I do think the Perl modules fixed _something_, but there still must be something wrong...

With all my complaining out of the way, I would like to thank you for your effort, I love Doom
