### ISSUE TITLE
[BUG] org-encrypt error: wrong-type-argument

### ISSUE THREAD

**Issue by Silipwn** [hlissner/doom-emacs#3123]
**What did you expect to happen?**
Org-encrypt to run successfully and encrypt the file.

**What actually happened?**
It failed with an error, ``` (wrong-type-argument stringp stringp)```

**Additional details:**
- Private config: [Gist](https://gist.github.com/Silipwn/b028dac2fa22962684eee46af4ed8bc1)
- Include screenshots/casts of your issue
![image](https://user-images.githubusercontent.com/28289337/81935981-13dabe80-960f-11ea-835f-258a02281629.png)
- Warnings/Errors: ```apply: Wrong type argument: stringp, stringp```

<details><pre>

Debugger entered--Lisp error: (wrong-type-argument stringp stringp)
  format-message(stringp)
  apply(format-message stringp)
  error(stringp)
  org-encrypt-entry()
  funcall-interactively(org-encrypt-entry)
  call-interactively(org-encrypt-entry record nil)
  command-execute(org-encrypt-entry record)
  counsel-M-x-action("org-encrypt-entry")
  ivy-call()
  ivy-read("M-x " ("org-encrypt-entry" "doom/toggle-debug-mode" "org-encrypt-entries" "org-decrypt-entry" "cd" "5x5" "amx" "arp" "dbx" "dig" "erc" "ert" "eww" "ftp" "gdb" "irc" "jdb" "man" "mpc" "pdb" "pwd" "rsh" "sdb" "xdb" "calc" "deft" "diff" "dirs" "ffap" "gnus" "grep" "help" "ielm" "info" "life" "lsp!" "mail" "mpuz" "ping" "pong" "talk" "term" "undo" "yank" "zone" "align" "chmod" "debug" "diary" "dired" ...) :predicate #f(compiled-function (x) #<bytecode 0x298e655>) :require-match t :history counsel-M-x-history :action counsel-M-x-action :keymap (keymap (67108908 . counsel--info-lookup-symbol) (67108910 . counsel-find-symbol)) :initial-input nil :caller counsel-M-x)
  counsel-M-x()
  funcall-interactively(counsel-M-x)
  call-interactively(counsel-M-x nil nil)
  command-execute(counsel-M-x)

</pre></details>

**Steps to reproduce:**
1. Create an org file with a simple header
1. Run ```org-encrypt-entry``` on the headline

**System information:**
<details><pre>
((emacs
  (version . "26.3")
  (features . "XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2")
  (build . "Aug 30, 2019")
  (buildopts "--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-modules 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "grafted, HEAD -> develop, origin/develop, origin/HEAD 2bdc147 2020-05-14 04:31:52 -0400")
  (dir . "~/.doom.d/"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/bin/fish")
  (uname . "Linux 5.6.11-arch1-1 #1 SMP PREEMPT Wed, 06 May 2020 17:32:37 +0000 x86_64")
  (path "/usr/local/sbin" "/usr/local/bin" "/usr/bin" "/usr/bin/site_perl" "/usr/bin/vendor_perl" "/usr/bin/core_perl" " "~/.cargo/bin" "~/.local/bin" "/usr/lib/emacs/26.3/x86_64-pc-linux-gnu"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company ivy :ui deft doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +defaults) tabs vc-gutter vi-tilde-fringe workspaces zen :editor (evil +everywhere) file-templates fold snippets :emacs dired electric undo vc :term eshell :checkers syntax spell grammar :tools (eval +overlay) lookup magit make pdf :lang cc emacs-lisp latex markdown (org +dragndrop +pandoc +roam +journal +pomodoro +gnuplot +present) python sh :config (default +bindings +smartparens))
  (packages (vagrant) (arduino-mode) (activity-watch-mode))
  (unpin "n/a")
  (elpa "n/a")))

</pre></details>

**Comment by hlissner** [comment]
I can reproduce this, but this appears to be an upstream issue.

Namely, the `org-encrypt-string` function expects `epa-file-encrypt-to` to be a string, but `epa-file-encrypt-to`'s documentation says:

```
May either be a string or a list of strings.
```

And Doom sets it to a list of strings, by default.

Would you mind reporting this upstream [to the org devs](https://code.orgmode.org/bzg/org-mode/commit/48da60f47a77f4b99b4160fa620f258896ff4da3)?

----

For the time being, you can get around this with:

```elisp
;; add to ~/.doom.d/config.el
(after! epa
  (setq epa-file-encrypt-to (car epa-file-encrypt-to)))
```

**Comment by hlissner** [comment]
I've implemented a temporary workaround in 043a561. Let me know if that gives you any trouble. In the meantime, I'll keep this issue open until it is addressed upstream.

**Comment by Silipwn** [comment]
The workaround for `config.el` didn't work, nor did the current commit 043a561.
Current back-trace looks like this:
<details><pre>
Debugger entered--Lisp error: (error "Encrypt failed")
  signal(error ("Encrypt failed"))
  error("Encrypt failed")
  org-encrypt-entry()
  funcall-interactively(org-encrypt-entry)
  call-interactively(org-encrypt-entry record nil)
</pre></details>
Reported the issue upstream.

**Comment by Silipwn** [comment]
Update: A fix was added to the repo in this [commit](https://code.orgmode.org/bzg/org-mode/commit/7939da783ee543e58adf0ef31cc00c291f85e574)

**Comment by hlissner** [comment]
Excellent. I've bumped org and removed the "workaround" in e3ca1d5. Thanks for letting me know!
