### ISSUE TITLE
:tools pdf dont compile on Ubuntu - Can't press Y to confirm package installation

### ISSUE THREAD

**Issue by otavioschwanck** [hlissner/doom-emacs#3129]
Doom just freezes and can't press y.  i had to install manually the packages.

**Comment by Zerobim** [comment]
The same happened to me in Arch, I pressed `y` (no feedback) and started pressing `C-<key> RET` randomly, and in a couple seconds it started updating, maybe it was `C-v RET` what did the trick as I pressed it first.

Couldn't do anything else besides that, it was completely frozen.

**Comment by nikplx** [comment]
Have the same problem on arch currently. I cannot do anything about it though, except restarting emacs. Debug mode does not show any error. It just freezes.

**Comment by hlissner** [comment]
This has been moved to #3244.
