### ISSUE TITLE
+eval/buffer in emacs-lisp-mode doesn't eval the whole buffer

### ISSUE THREAD

**Issue by amosbird** [hlissner/doom-emacs#313]
HI, I'm not sure if this is the desired behavior. When doing `+eval/buffer` in elisp buffer, only the top first sexpr is evaluated. This is quite different from `eval-buffer`.

**Comment by hlissner** [comment]
Found and fixed the issue. `+emacs-lisp-eval` wasn't wrapping the buffer's code in a `progn`, causing only the first form to be read. The fix is now in `develop`. I'll keep this open until it's in master.

**Comment by hlissner** [comment]
The fix is now in master.
