### ISSUE TITLE
`t' used as a lambda variable

### ISSUE THREAD

**Issue by SwiftLawnGnome** [hlissner/doom-emacs#3134]
**What did you expect to happen?**
Compiling `doom compile -c -v` succeeds

**What actually happened?**
"Error: Invalid lambda variable t"

**Additional details:**
[Here](https://github.com/hlissner/doom-emacs/blob/c1bee692cf2c178e8d9695da7955143f10386943/core/cli/byte-compile.el#L124) is the problem.

**Steps to reproduce:**
`doom compile -c -v`

**Comment by SwiftLawnGnome** [comment]
That can just be eta reduced anyway to `#'doom-module-from-path`

**Comment by hlissner** [comment]
Ah, my bad. This is fixed in 3d10e98. Thanks for bringing it to my attention!
