### ISSUE TITLE
Org-mode: non-blocking inline images

### ISSUE THREAD

**Issue by telotortium** [hlissner/doom-emacs#3136]
`org-display-user-inline-images` from [`org-yt`](https://github.com/TobiasZawada/org-yt) adds `:image-data-fun`, which returns the image data to render inline. When this is called on a remote image, it blocks Emacs until the image is downloaded and displayed, which is less than helpful. It would be better if this function could be asynchronous in some way to avoid blocking Emacs. Perhaps a new `org-link` parameter could be provided for a function that, instead of returning the image data directly, returns a `url-retrieve` callback that is called once the image has been downloaded. Alternatively, this function could instead implement a promise that returns the image data, though unfortunately there are several competing implementations:

- `deferred`
- `emacs-aio`
- `emacs-async`
- Maybe Emacs native generators

**Comment by hlissner** [comment]
This request may be better targeted at the [org-yt](https://github.com/TobiasZawada/org-yt) package. I'll see what I can do on my end, if anything. I'm not sure if org's `:image-data-fun` handler can deal with async without some hackery.
