### ISSUE TITLE
Emacs freezes when `doom/help-packages`

### ISSUE THREAD

**Issue by OceanS2000** [hlissner/doom-emacs#3138]
**What did you expect to happen?**
`doom/help-packages` should give a popup listing all packages installed

**What actually happened?**
Emacs freezes, with high CPU utilisation.

**Additional details:**
After playing with `edebug` for a while, that is seemingly what happens:

- `doom/help-packages` calls [`(doom-package-list 'all)`](https://github.com/hlissner/doom-emacs/blob/375faedb1b27a8051207662418ef9610f0f1a782/core/autoload/help.el#L437) to build package list, which in turn calls [`(doom--read-packages private-packages all-p 'noerror)`](https://github.com/hlissner/doom-emacs/blob/375faedb1b27a8051207662418ef9610f0f1a782/core/core-packages.el#L361)
- As `all-p` is passed to `doom--read-package`, it goes to parse my private `packages.el` without `load`ing it.
- The parsing routine contains a [loop](https://github.com/hlissner/doom-emacs/blob/375faedb1b27a8051207662418ef9610f0f1a782/core/core-packages.el#L318) that goes like
```
(while (search-forward "(package! " nil t)
              (goto-char (match-beginning 0)) ;; (1)
              ;; do something
)
```
The line (1) makes the cursor back to the beginning of the match, which causes the next call to `search-forward` returning the same `package!` directive.

After adding `(goto-char (match-end 0))` to the end of the loop, the issue seems to be resolved for me.

**Steps to reproduce:**
1. `emacs`
2. press `SPC h p`

**System information:**
<details><pre>

```
emacs   version    26.3
        features   DBUS NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS LCMS2
        build      Mar 24, 2020
        buildopts  (--prefix=/opt/local --with-mac --enable-mac-app=/Applications/MacPorts --with-modules --without-rsvg --without-imagemagick 'CFLAGS=-pipe -Os -fobjc-arc -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -arch x86_64' 'CPPFLAGS=-I/opt/local/include -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk' 'LDFLAGS=-L/opt/local/lib -Wl,-headerpad_max_install_names -Wl,-syslibroot,/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -arch x86_64')
        windowsys  mac
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop 375faedb1 2020-05-16 05:38:20 -0400
        dir        ~/.config/doom/
system  type       darwin
        config     x86_64-apple-darwin19.3.0
        shell      /opt/local/bin/zsh
        uname      Darwin 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 21:35:29 PST 2020; root:xnu-6153.80.11.102.2~1/RELEASE_X86_64 x86_64
        path       (~/.local/bin ~/.local/share/cargo/bin /opt/local/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /Library/Apple/usr/bin /Library/Apple/bin /Applications/VMware Fusion.app/Contents/Public /usr/local/MacGPG2/bin /opt/local/sbin /Applications/Isabelle2019.app/Contents/Resources/Isabelle2019/bin /Applications/CoqIDE_8.10.0.app/Contents/Resources/bin /usr/local/sbt/bin /Library/TeX/texbin ~/.local/bin ~/.local/share/cargo/bin ~/Code/go/bin /Applications/MacPorts/EmacsMac.app/Contents/MacOS/libexec/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion (company +childframe) (ivy +prescient +childframe) :ui doom doom-dashboard doom-quit hl-todo hydra-ocean modeline nav-flash ophints (popup +all +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold format multiple-cursors snippets :checkers syntax spell :emacs dired electric vc ibuffer :term eshell vterm :tools eval (lookup +dictionary +docsets) lsp macos magit pdf :lang (cc +lsp) coq data emacs-lisp (go +lsp) latex lua markdown (org +dragndrop +noter +roam +pandoc +present) rest (rust +lsp) sh :config literate (default +bindings +smartparens))
        packages   ((org-yt :disable t))
        unpin      (n/a)
        elpa       (n/a)
```
</pre></details>

**Comment by hlissner** [comment]
Good catch! As of de78d0c this should be fixed. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention, and for the wonderful bug report!
