### ISSUE TITLE
Elisp source files not found if emacs was started with an elisp file as an argument

### ISSUE THREAD

**Issue by bepvte** [hlissner/doom-emacs#3139]
**What did you expect to happen?**
When running emacs on a file like `emacs .doom.d/init.el`, emacs should be able to show the source file of a function looked up with `SPC-h-f` or `K` while the cursor is on an elisp function.

**What actually happened?**
The documentation buffer claims that the function is defined without a source file.
This does not happen when launching emacs with no arguments, and then opening a elisp file from the doom dashboard.

**Additional info**
I can only get it to reproduce with this init.el: https://gist.github.com/bepvte/da48d1621eb6673eb6b3a3056c9ae0a9
I have tried it without the config.el and packages.el, and as well in the sandbox with my init.el to the same result. I cant figure out what module of mine is causing it.
It happens the same on emacs 26 and 27.

**Steps to reproduce:**
1. Open emacs on an elisp file: `emacs .doom.d/init.el`
2. Try looking at the documentation of an elisp function by pressing `K` while the cursor is on one.
3. See "[function] is a compiled function without a source file"

**System information:**
<details><pre>
Place the output of `M-x doom/info` or `~/.emacs.d/bin/doom info` here.
((emacs
  (version . "27.0.91")
  (features . "XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND DBUS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER LCMS2 GMP")
  (build . "May 15, 2020")
  (buildopts "--build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-dbus --with-gif --with-jpeg --with-png --with-rsvg --with-cairo --with-tiff --with-xpm --with-x-toolkit=gtk3 --with-gpm=no --with-xwidgets --with-modules --without-gconf --without-gsettings --without-xft --without-m17n-flt --enable-link-time-optimization 'CFLAGS=-DMAIL_USE_LOCKF -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -flto=auto -fuse-linker-plugin -fno-fat-lto-objects -march=native -O2' 'LDFLAGS=-Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld'")
  (windowsys . batch)
  (daemonp))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD 375faedb1 2020-05-16 05:38:20 -0400")
  (dir . "~/dotfiles/stow/emacs/.doom.d/"))
 (system
  (type . gnu/linux)
  (config . "x86_64-redhat-linux-gnu")
  (shell . "/bin/zsh")
  (uname . "Linux 5.6.13-300.fc32.x86_64 #1 SMP Thu May 14 22:51:37 UTC 2020 x86_64")
  (path "~/.local/bin" "~/Android/Sdk/flutter/bin" "~/Android/Sdk/build-tools/29.0.2" "~/Android/Sdk/emulator" "~/Android/Sdk/platform-tools" "~/Android/Sdk/tools/bin" "~/Android/Sdk/custom/bin" "~/go/bin" "~/.cargo/bin" "~/.emacs.d/bin" "/usr/share/Modules/bin" "/usr/lib64/ccache" "/usr/local/bin" "/usr/local/sbin" "/usr/bin" "/usr/sbin" "~/bin" "~/.dotnet/tools" "/usr/libexec/emacs/27.0.91/x86_64-redhat-linux-gnu"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard hl-todo modeline ophints (popup +defaults) treemacs vc-gutter window-select workspaces zen :editor (evil +everywhere) file-templates fold (format +onsave) lispy multiple-cursors rotate-text snippets word-wrap :emacs dired electric (ibuffer +icons) undo vc :term eshell vterm :checkers syntax spell :tools docker editorconfig (eval +overlay) (lookup +dictionary) lsp magit rgb :lang (cc +lsp) data emacs-lisp (go +lsp) (json +lsp) (javascript +lsp) lua markdown org rest (rust +lsp) sh web yaml :config (default +bindings +smartparens))
  (packages (hl-line :disable t) (doom-snippets :disable t) (clipetty :disable t) (yasnippet-snippets) (flycheck-package :disable t) (gtk-variant :recipe '(:host github :repo "bepvte/gtk-variant.el")))
  (unpin "n/a")
  (elpa "n/a")))
</pre></details>

**Comment by hlissner** [comment]
I'm afraid I cannot reproduce this, nor make much sense of the error message. It should only happen if you intentionally evaluated the definitions of those functions in a context where the interpret couldn't discern the current file name. I can't imagine how Emacs could put itself into that state.

Is your private config up somewhere I can see it?

What function(s) have you tested this on? Does it affect all functions?

**Comment by bepvte** [comment]
It affects all functions, macros, and symbols. I edited the gist to include my other config files, but keep in mind that the bug still happens without config.el and package.el. Only init.el seems to cause it. I feel like its a data race bug or something complicated that will go away silently with an unrelated change 😒. Its fine if this goes on the backlog, if it doesn't vanish silently I'll work on it and learn how to debug emacs and how lookup works when I graduate from high school in a few weeks 🎉.

**Comment by bepvte** [comment]
The problem mysteriously vanished. I hope it doesnt come back.
