### ISSUE TITLE
previous-buffer not work after unset 'doom'

### ISSUE THREAD

**Issue by wangggong** [hlissner/doom-emacs#3145]
**What did you expect to happen?**
...
1. `<SPC>fp`, open init.el;
2. delete doom in `doom! :ui` packages;
3. doom refresh;
4. open new emacs, try to navigate into previous buffer by `[b`;
5. Failed.

**Additional details:**
- Mac OS X, 10.15.
- Doom v2.0.9, emacs v26.3

**Comment by hlissner** [comment]
> open new emacs, try to navigate into previous buffer by [b;

In a new emacs there's only the dashboard. There is no buffer to switch to. What buffer do you want it to switch to?

**Comment by wangggong** [comment]
> > open new emacs, try to navigate into previous buffer by [b;
> 
> In a new emacs session there's only the dashboard. No previous buffer exists to switch to. What buffer do you want it to switch to?

Emmmm... Sorry I don't make it clear. In dashboard it certainly is useless; while when a project is opened, you can use `gd` to goto definition from a file to a another file, but cannot go back by `<SPC>bp` or `[b`. Hence I need to `<Ctrl>O` * n to go back.

**Comment by wangggong** [comment]
In my opinion if the `doom` package just makes emacs more "like" Doom, the functionality of the editor need not change. While after deleting `doom`, `[b`/`]b` doesn't work, and `vterm/toggle` works different.

**Comment by hlissner** [comment]
Are there any warnings/messages in \*Messages\* when you use `[b`/`]b`. Toggling the `:ui doom` module should have no relation to those commands.

**Comment by wangggong** [comment]
```
condition-case: Error in a Doom startup hook: doom-init-theme-h, (error "Unable to find theme file for ‘doom-one’")
Loading
/Users/rikka/Code/src/github.com/hlissner/doom-emacs/.local/cache/recentf...done
Open org-agenda (org-agenda)
Reload last session (doom/quickload-session)
Open org-agenda (org-agenda)
Reload last session (doom/quickload-session)
Switched to ’gateway’
Note: standard-indent, tab-width, evil-shift-width adjusted to 4
Mark set
Note: standard-indent, tab-width, evil-shift-width adjusted to 4
func (*Controller).name(...)
*xclib/common/elaps$
Quit [2 times]
Updating buffer list...
Formats have changed, recompiling...done
Updating buffer list...done
Commands: m, u, t, RET, g, k, S, D, Q; q to quit; h for help
```

No, no relative error/warnings found.

**Comment by wangggong** [comment]
Got it. I set an invalid theme. I commented the theme and it worked. Thanks.
