### ISSUE TITLE
setting localleader to `\`: "Key sequence \\ ... starts with non-prefix key \\"

### ISSUE THREAD

**Issue by NightMachinary** [hlissner/doom-emacs#3156]
I have set the localleader to:
```
(global-set-key (kbd "\\") nil)
(setq doom-localleader-key "\\")
(setq doom-localleader-alt-key "M-\\")
```

Doing `(map! :localleader "z e w" #'night/eval-line)` causes:

```
 Debugger entered--Lisp error: (error "Key sequence \\ z e w starts with non-prefix key \\")
   define-key((keymap (remap keymap (avy-goto-word-or-subword-1 . evil-avy-goto-word-or-subword-1) (avy-goto-word-1-below . e$
   evil-define-key*(motion global "\\zew" night/eval-line)
   general--define-key-dispatch(motion global ("\\zew" night/eval-line (:def night/eval-line)) (:wk-match-keys t :wk-match-bi$
   general--define-key(motion global ("\\zew" night/eval-line) ([134217820 122 101 119] night/eval-line) nil (:wk-match-keys $
   eval((general--define-key (quote motion) (quote global) (quote ("\\zew" night/eval-line)) (quote ([134217820 122 101 119] $
   general--delay((or (boundp (quote global)) (and (memq (quote global) (quote (local global))) (if (quote motion) (and (boun$
   general-define-key(:states (normal visual motion emacs insert) :major-modes t :prefix "\\" :non-normal-prefix "M-\\" "z e $
   eval((general-define-key :states (quote (normal visual motion emacs insert)) :major-modes t :prefix doom-localleader-key :$
   elisp--eval-last-sexp(nil)
   #f(compiled-function (eval-last-sexp-arg-internal) "Evaluate sexp before point; print value in the echo area.\nInteractive$
   apply(#f(compiled-function (eval-last-sexp-arg-internal) "Evaluate sexp before point; print value in the echo area.\nInter$
   eval-last-sexp(nil)
   eros-eval-last-sexp(nil)
```

**Additional details:**
- Include a link to your private config

https://github.com/NightMachinary/doom.d.git

**System information:**
<details><pre>
((emacs
  (version . "26.3")
  (features . "NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS")
  (build . "Sep 02, 2019")
  (buildopts "--with-ns '--enable-locallisppath=/Library/Application Support/Emacs/${version}/site-lisp:/Library/Application Support/Emacs/site-lisp' --with-modules")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD 220916ae1 2020-05-18 03:41:02 -0400")
  (dir . "~/doom.d/"))
 (system
  (type . darwin)
  (config . "x86_64-apple-darwin18.2.0")
  (shell . "/usr/local/bin/zsh")
  (uname . "Darwin 19.0.0 Darwin Kernel Version 19.0.0: Wed Sep 25 20:18:50 PDT 2019; root:xnu-6153.11.26~2/RELEASE_X86_64 x86_64")
  (path "~/.asdf/shims" "/usr/local/opt/asdf/bin" "/myBin/" "~/scripts//zsh/wrappers/Zath.app/Contents/Resources/MainMenu.nib/" "~/scripts//zsh/wrappers/Zath.app/Contents/Resources/" "~/scripts//zsh/wrappers/Zath.app/Contents/MacOS/" "~/scripts//zsh/wrappers/Zath.app/Contents/" "~/scripts//zsh/wrappers/Zath.app/" "~/scripts//zsh/wrappers/" "~/scripts//zsh/rss-notifier/" "~/scripts//zsh/personal/" "~/scripts//zsh/interactive/" "~/scripts//zsh/fattened/" "~/scripts//zsh/fastsyntax/" "~/scripts//zsh/expensive/" "~/scripts//zsh/exorbitant/" "~/scripts//zsh/ensure-run/" "~/scripts//zsh/bugs/" "~/scripts//zsh/basic/auto-load/" "~/scripts//zsh/basic/" "~/scripts//zsh/auto-load/tests/" "~/scripts//zsh/auto-load/others/" "~/scripts//zsh/auto-load/bugs/" "~/scripts//zsh/auto-load/" "~/scripts//zsh/aria2-helpers/" "~/scripts//zsh/" "~/scripts//sh/" "~/scripts//setup/" "~/scripts//rust/archive/" "~/scripts//rust/" "~/scripts//ruby/" "~/scripts//resources/luna/" "~/scripts//resources/" "~/scripts//python/xonsh/" "~/scripts//python/url-encode/" "~/scripts//python/telegram-send/__pycache__/" "~/scripts//python/telegram-send/" "~/scripts//python/tecast/" "~/scripts//python/ipython/" "~/scripts//python/gmail/" "~/scripts//python/genRSS/" "~/scripts//python/aria2/" "~/scripts//python/" "~/scripts//launchers/" "~/scripts//javascript/" "~/scripts//export/" "~/scripts//deactivated-launchers/" "~/scripts//dash/" "~/scripts//bin/" "~/scripts//bash/personal/" "~/scripts//bash/auto-load/" "~/scripts//bash/" "~/scripts//applescript/" "~/scripts//DOOMDIR=~/doom.d/" "~/scripts//DOOMDIR=~/" "~/scripts//" "/usr/local/opt/curl/bin" "/usr/local/opt/qt/bin" "/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home" "~/miniconda3/bin/" "~/anaconda/bin/" "~/.poetry/bin" "~/bin" "~/.gem/bin" "/usr/libexec/" "~/kscripts/" "/usr/local/opt/texinfo/bin" "~/go/bin" "/Base/- Code/Resources/" "~/.local/bin" "/usr/local/sbin" "/usr/local/bin" "/snap/bin" "~/.cargo/bin" "/Library/TeX/texbin" "~/.dotnet/tools" "~/.emacs.d.doom/bin/" "~/code/node/snips-alice" "/usr/bin" "/bin" "/usr/sbin" "/sbin" "~/Library/Caches/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-unixorn-SLASH-git-extra-commands/bin" "/Applications/Emacs.app/Contents/MacOS/bin-x86_64-10_14" "/Applications/Emacs.app/Contents/MacOS/libexec-x86_64-10_14" "/Applications/Emacs.app/Contents/MacOS/libexec" "/Applications/Emacs.app/Contents/MacOS/bin"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard hl-todo modeline nav-flash ophints (popup +defaults) unicode vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold snippets word-wrap :emacs dired electric undo vc :term vterm :checkers syntax spell :tools (eval +overlay) gist lookup lsp macos magit pdf :lang clojure coq data emacs-lisp json javascript julia lua markdown org perl python racket rst (ruby +rails) rust scala sh yaml :config (default +bindings +smartparens))
  (packages (solarized-theme) (zoom) (blacken) (lispyville) (dimmer) (google-translate))
  (unpin "n/a")
  (elpa "n/a")))
</pre></details>

**Comment by hlissner** [comment]
There are two issues here:

1. `\\` is bound to `evil-execute-in-emacs-state` in motion mode (not in the global keymap), and must be unbound:

   ```elips
   (map! :m "\\" nil)
   ```

2. To quote `SPC h f map\!`:

   ```
     :localleader [...]              bind to localleader; requires a keymap
   ```

   Localleader keybinds are not global and require a keymap. e.g.

   ```elisp
   (map! :localleader
         :map some-mode-map
         "z e w" #'night/eval-line)
   ```

**Comment by NightMachinary** [comment]
@hlissner Thanks!
