### ISSUE TITLE
How do I change the language of company-ispell?

### ISSUE THREAD

**Issue by mrbig033** [hlissner/doom-emacs#3157]
> Please visit our Discord server to ask how-to and workflow questions:
> https://discord.gg/qvGgnVx -- post on Doom's issue tracker as a last resort.

**What are you trying to achieve?**
Use `company-ispell` with another dictionary.

**What have you tried?**
`ispell-change-dictionary`will have effects on Flyspell, but not on company.

**System information**
<details><pre>
((emacs
  (version . "27.0.91")
  (features . "RSVG IMAGEMAGICK GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS JSON PDUMPER LCMS2 GMP")
  (build . "May 14, 2020")
  (buildopts "--disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus/HEAD-747e0a2/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus/HEAD-747e0a2 --with-xml2 --without-dbus --with-gnutls --with-imagemagick --with-json --with-modules --with-rsvg --with-ns --disable-ns-self-contained")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "grafted, HEAD -> develop, origin/develop, origin/HEAD a201123 2020-05-14 04:13:05 -0400")
  (dir . "~/.doom.d/"))
 (system
  (type . darwin)
  (config . "x86_64-apple-darwin18.7.0")
  (shell . "/bin/bash")
  (uname . "Darwin 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64")
  (path "/usr/local/opt/openjdk/bin" "~/.pyenv/shims" "~/.pyenv/bin" "~/.local/bin" "~/.emacs.d/bin" "~/scripts/bin" "~/.nimble/bin" "~/scripts/cline_scripts/" "~/.emacs.d/bin" "/usr/local/bin" "/usr/bin" "/bin" "/usr/sbin" "/sbin" "/Library/TeX/texbin" "/opt/X11/bin" "~" "~/.fzf/bin" "/usr/local/Cellar/emacs-plus/HEAD-747e0a2/libexec/emacs/27.0.91/x86_64-apple-darwin18.7.0"))
 (config
  (envfile . envvar-file)
  (elc-files . 682)
  (modules :completion company ivy :ui doom hl-todo hydra modeline (popup +defaults) treemacs :editor (evil +everywhere) file-templates fold snippets :emacs dired electric undo vc :checkers syntax spell grammar :tools (eval +overlay) lookup pdf :lang data emacs-lisp markdown org sh :config (default +bindings +smartparens))
  (packages (general) (pdf-tools) (org-pdfview) (org-pomodoro) (benchmark-init) (ranger) (nswbuff) (prescient) (ivy-prescient) (company-prescient) (ivy-hydra) (olivetti) (super-save) (eyebrowse) (elpy) (shut-up) (electric-operator) (ivy-hydra) (elmacro) (clipmon) (evil-god-state) (unkillable-scratch) (git-commit) (aphelia :recipe (:host github :repo "raxod502/apheleia")) (shut-up :disable t) (evil-snipe :disable t))
  (unpin "n/a")
  (elpa "n/a")))
</pre></details>

**Comment by hlissner** [comment]
A search of `company-ispell`'s source code (via `SPC h P company-ispell`) shows me [that a `company-ispell-dictionary` variable exists](https://github.com/company-mode/company-mode/blob/master/company-ispell.el#L36-L40). Try setting that instead.

**Comment by mrbig033** [comment]
Changing this variable does not work :(

**Comment by mrbig033** [comment]
I was able to solve the issue by doing the following:

1. Manually downloading the Ispell Brazilian Portuguese dictionary from https://www.ime.usp.br/~ueda/br.ispell/summary.html

2. Unpacking the tarball, copying the file `br.ispell-2.4/br.aff` to `~/.doom.d/etc/brasileiro.txt` and changing its encoding to UTF—8 using `M—x set-buffer-file-coding-system`. 

3. Adding the following setting and functions for easy access:

``` emacs-lisp
(setq! company-ispell-available t)

(defun company-ispell-brasileiro ()
  (interactive)
  (setq-local company-ispell-dictionary (file-truename "~/.doom.d/etc/brasileiro.txt")))

(defun company-ispell-english ()
  (interactive)
  (setq-local company-ispell-dictionary nil))
```
Feel free to close this issue if you feel there's no further action to be done. IMHO it may be nice to add this to the documentation at least.
