### ISSUE TITLE
Direnv configuration breaks TRAMP

### ISSUE THREAD

**Issue by ajgrf** [hlissner/doom-emacs#3158]
**What did you expect to happen?**
Calling `magit-status` while editing a TRAMP buffer should pull up the Magit status buffer.

This was working in abb9ab7674601c2e90ecf1ca29f575a1effe9a4c, but broken when I upgraded to 220916ae17fe9d561b81e7a5268d2135ec56eac6 (d697ff481e98e4eef509d1c8374eb4a85e6995ae is probably the culprit).

**What actually happened?**
Nothing happens to the UI. When I check the \*Messages\* buffer I see this:

    Waiting for git...
    Tramp: Opening connection for dotfiles using vcsh...
    Tramp: Sending command ‘exec vcsh enter dotfiles’
    Tramp: Waiting for prompts from remote shell...done
    Tramp: Found remote shell prompt on ‘dotfiles’
    Tramp: Opening connection for dotfiles using vcsh...failed
    tramp-signal-hook-function: Cannot use direnv for remote files

**Additional details:**
- My config is [here](https://github.com/ajgrf/dotfiles/tree/master/.config/doom).

<details><pre>
If an error message is involved include a backtrace of it.

How to acquire a backtrace:
https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#how-to-extract-a-backtrace-from-an-error
</pre></details>

**Steps to reproduce:**
1. Open a TRAMP connection. For example, `/sudo::/` works if you don't want to remote into a server.
2. This was enough to trigger the bug for me just now, although I originally encountered the bug using Magit. So if the TRAMP connection succeeded for you, call `magit-status` with `SPC g g`.

**System information:**
<details><pre>
((emacs
  (version . "26.3")
  (features . "XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS")
  (build . "May 18, 2020")
  (buildopts "CONFIG_SHELL=/gnu/store/pwcp239kjf7lnj5i4lkdzcfcxwcfyk72-bash-minimal-5.0.16/bin/bash SHELL=/gnu/store/pwcp239kjf7lnj5i4lkdzcfcxwcfyk72-bash-minimal-5.0.16/bin/bash --prefix=/gnu/store/da1lys4i2yxl549iwkbdg1fb7azphniw-emacs-26.3 --enable-fast-install --with-modules --disable-build-details")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop 220916ae1 2020-05-18 03:41:02 -0400")
  (dir . "~/.config/doom/"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/gnu/store/87kif0bpf0anwbsaw0jvg8fyciw4sz67-bash-5.0.16/bin/bash")
  (uname . "Linux 5.4.41 #1 SMP 1 x86_64")
  (path "/gnu/store/bngdc94ghsn7van1s0q0chzl8ag3jg5n-glib-2.62.6-bin/bin" "~/bin" "~/.local/bin" "~/.config/guix/current/bin" "~/.local/guix/profile/profile/bin" "~/.local/guix/profile/profile/sbin" "~/.local/guix/libreoffice/libreoffice/bin" "~/.local/guix/games/games/bin" "~/.local/guix/games/games/sbin" "~/.local/guix/emacs/emacs/bin" "~/.local/guix/chromium/chromium/bin" "~/.local/guix/beets/beets/bin" "~/.nix-profile/bin" "/run/setuid-programs" "~/.config/guix/current/bin" "~/.guix-profile/bin" "/run/current-system/profile/bin" "/run/current-system/profile/sbin" "/gnu/store/da1lys4i2yxl549iwkbdg1fb7azphniw-emacs-26.3/libexec/emacs/26.3/x86_64-pc-linux-gnu"))
 (config
  (envfile)
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold (format +onsave) lispy multiple-cursors snippets :emacs dired electric undo vc :term eshell shell :checkers syntax spell :tools ansible direnv (eval +overlay) lookup (magit +forge) (pass +auth) pdf :lang clojure data emacs-lisp go javascript ledger markdown org scheme sh (web +html +css) :email mu4e :app (rss +org) :config (default +bindings +smartparens))
  (packages (parchment-theme :recipe (:local-repo "~/src/parchment")) (minions :pin "c331c15161") (vimrc-mode :pin "13bc150a87") (debbugs :pin "23fa83932b") (guix :pin "c2796e6886") (mu4e-conversation :pin "98110bb9c3") (emms :pin "f4924c2e77") (emms-mode-line-cycle :pin "2c2f395e48") (tramp :recipe (:host nil :repo "https://git.savannah.gnu.org/git/tramp.git") :pin "8f851af736") (shrface :pin "c82447df5b") (aio :pin "9367005c44") (om :recipe (:host github :repo "ndwarshuis/om.el") :pin "5b3d6f2b32") (ts :pin "540f6a5ada"))
  (unpin "n/a")
  (elpa "n/a")))

</pre></details>

**Comment by hlissner** [comment]
As of b92f41b this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by ajgrf** [comment]
It works, thanks!
