### ISSUE TITLE
How do I make Org hide drawers on cycling? (restore the default behavior)

### ISSUE THREAD

**Issue by mrbig033** [hlissner/doom-emacs#3159]
> Please visit our Discord server to ask how-to and workflow questions:
> https://discord.gg/qvGgnVx -- post on Doom's issue tracker as a last resort.

**What are you trying to achieve?**
To restore Org Mode default behavior, in which it cycles through subtrees but does not open drawers.

**What have you tried?**
I added this to my init, with no success:

```
(remove-hook 'org-cycle-hook 'org-optimize-window-after-visibility-change)
(add-hook 'org-cycle-hook 'org-cycle-hide-property-drawers)

(after! evil-org
  (remove-hook 'org-tab-first-hook #'+org-cycle-only-current-subtree-h))

```
It does cycle subtrees the way I want, but the property drawers are opened by default even with `#+STARTUP: overview`.

- [My Org Settings](https://github.com/mrbig033/doom/blob/2a85f1e3725c17dd2a8dbf2e51c87d562ac2f2c9/my-lisp/my-packages.el#L188) (I also tested without them).

`emacs -Q` presents the default behavior.

**System information**
<details><pre>
((emacs
  (version . "27.0.91")
  (features . "RSVG IMAGEMAGICK GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS JSON PDUMPER LCMS2 GMP")
  (build . "May 14, 2020")
  (buildopts "--disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus/HEAD-747e0a2/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus/HEAD-747e0a2 --with-xml2 --without-dbus --with-gnutls --with-imagemagick --with-json --with-modules --with-rsvg --with-ns --disable-ns-self-contained")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "grafted, HEAD -> develop, origin/develop, origin/HEAD a201123 2020-05-14 04:13:05 -0400")
  (dir . "~/.doom.d/"))
 (system
  (type . darwin)
  (config . "x86_64-apple-darwin18.7.0")
  (shell . "/bin/bash")
  (uname . "Darwin 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64")
  (path "/usr/local/opt/openjdk/bin" "~/.pyenv/shims" "~/.pyenv/bin" "~/.local/bin" "~/.emacs.d/bin" "~/scripts/bin" "~/.nimble/bin" "~/scripts/cline_scripts/" "~/.emacs.d/bin" "/usr/local/bin" "/usr/bin" "/bin" "/usr/sbin" "/sbin" "/Library/TeX/texbin" "/opt/X11/bin" "~" "~/.fzf/bin" "/usr/local/Cellar/emacs-plus/HEAD-747e0a2/libexec/emacs/27.0.91/x86_64-apple-darwin18.7.0"))
 (config
  (envfile . envvar-file)
  (elc-files . 682)
  (modules :completion company ivy :ui doom hl-todo hydra modeline (popup +defaults) treemacs :editor (evil +everywhere) file-templates fold snippets :emacs dired electric undo vc :checkers syntax spell grammar :tools (eval +overlay) lookup pdf :lang data emacs-lisp markdown org sh :config (default +bindings +smartparens))
  (packages (general) (pdf-tools) (org-pdfview) (org-pomodoro) (benchmark-init) (ranger) (nswbuff) (prescient) (ivy-prescient) (company-prescient) (ivy-hydra) (olivetti) (super-save) (eyebrowse) (elpy) (shut-up) (electric-operator) (ivy-hydra) (elmacro) (clipmon) (evil-god-state) (unkillable-scratch) (git-commit) (aphelia :recipe (:host github :repo "raxod502/apheleia")) (shut-up :disable t) (evil-snipe :disable t))
  (unpin "n/a")
  (elpa "n/a")))
</pre></details>

**Comment by mrbig033** [comment]
It's working now with this:

```
(remove-hook 'org-cycle-hook 'org-optimize-window-after-visibility-change)
(add-hook 'org-cycle-hook 'org-cycle-hide-drawers)

(after! evil-org
  (remove-hook 'org-tab-first-hook #'+org-cycle-only-current-subtree-h))

```

I had to use `org-cycle-hide-drawers` instead of `org-cycle-hide-property-drawers`.

**Comment by hlissner** [comment]
> (after! evil-org
  (remove-hook 'org-tab-first-hook #'+org-cycle-only-current-subtree-h))

This is no longer necessary as of 31e4bfb2d (a week ago).

> To restore Org Mode default behavior, in which it cycles through subtrees but does not open drawers.

If this is supposed to be org's default behavior then perhaps this should be reported [upstream](https://code.orgmode.org/bzg/org-mode), as Doom doesn't influence this folding behavior.

**Comment by mrbig033** [comment]
> This is no longer necessary as of 31e4bfb (a week ago).

`doom upgrade` wasn't working so I did a fresh install. 

```
(after! evil-org
  (remove-hook 'org-tab-first-hook #'+org-cycle-only-current-subtree-h))
```

Is still required. `emacs -Q` does not present the behavior.

**Comment by hlissner** [comment]
Oh, my bad, I misread the function name! Carry on :P

**Comment by mrbig033** [comment]
That's cool, thanks!
