### ISSUE TITLE
Error in org.elc upon loading org-mode files

### ISSUE THREAD

**Issue by aarohijohal** [hlissner/doom-emacs#3164]
**What did you expect to happen?**
I use org-roam to manage my notes, I don't usually upgrade at all, but after an upgrade after a while, I'm seeing an error upon either issuing `org-journal-new-entry`, or loading an orgmode file.

**What actually happened?**
Error whenever I issue `org-journal-new-entry`:
```
org-babel-read: End of file during parsing: /Users/Popeye/.emacs.d/.local/straight/build/org-mode/org.elc
Failed to load ’magit’ package incrementally, because: (end-of-file /Users/Popeye/.emacs.d/.local/straight/build/org-mode/org.elc)
Failed to load ’org’ package incrementally, because: (end-of-file /Users/Popeye/.emacs.d/.local/straight/build/org-mode/org.elc)
```
Or, if I load an orgmode file:
```
File mode specification error: (end-of-file /Users/Popeye/.emacs.d/.local/straight/build/org-mode/org.elc)
```

**Additional details:**
My configuration:
- [config.el](https://gist.github.com/aarohijohal/1335f4877da9c196f8c8322eeff4884d)
- [packages.el](https://gist.github.com/aarohijohal/bbecbf35da13263f77cda53c8ca27ede)
- [init.el](https://gist.github.com/aarohijohal/80cae8cf2adf423d9e66d893f5d9da9c)

**Steps to reproduce:**
1. Copy my configurations (above) into `~/.doom.d/`
2. Clone Doom Emacs into `~/.emacs.d`.
3. Install Doom Emacs: `~/.emacs.d/bin/doom install`
4. Load Emacs.
5. Either issue `org-journal-new-entry` or open an org-mode file, and observe the errors mentioned above.

**System information:**
<details><pre>
((emacs
  (version . "26.3")
  (features . "JPEG RSVG IMAGEMAGICK GLIB NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2")
  (build . "Mar 11, 2020")
  (buildopts "--disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus/26.3/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus/26.3 --with-xml2 --without-dbus --with-gnutls --with-imagemagick --with-modules --with-rsvg --with-ns --disable-ns-self-contained")
  (windowsys . batch)
  (daemonp))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD 95547823c 2020-05-18 20:11:05 -0400")
  (dir . "~/.doom.d/"))
 (system
  (type . darwin)
  (config . "x86_64-apple-darwin18.7.0")
  (shell . "/bin/zsh")
  (uname . "Darwin 18.7.0 Darwin Kernel Version 18.7.0: Thu Jan 23 06:52:12 PST 2020; root:xnu-4903.278.25~1/RELEASE_X86_64 x86_64")
  (path "~/.cargo/bin" "~/.gem/ruby/2.3.0/bin" "/usr/local/opt/gettext/bin" "~/Code/sonar-scanner/bin" "~/.gem/ruby/2.3.0/bin" "/usr/local/bin" "/usr/local/sbin" "/usr/local/opt/cython/bin" "/usr/local/opt/sqlite/bin" "/usr/local/opt/openssl/bin" "/usr/local/opt/libiconv/bin" "/usr/local/opt/e2fsprogs/sbin" "/usr/local/opt/e2fsprogs/bin" "/usr/local/opt/openssl/bin" "/usr/local/opt/gettext/bin" "~/.poetry/bin" "~/.rbenv/shims" "~/.rbenv/bin" "/usr/local/Cellar/ruby/2.6.3/bin" "/usr/local/bin" "/usr/bin" "/bin" "/usr/sbin" "/sbin" "/Library/TeX/texbin" "/opt/X11/bin" "/Applications/Wireshark.app/Contents/MacOS" "/usr/local/bin" "/usr/local/opt/go/libexec/bin" "/usr/local/Cellar/emacs-plus/26.3/libexec/emacs/26.3/x86_64-apple-darwin18.7.0"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company (ivy +fuzzy) :ui deft doom hl-todo indent-guides modeline nav-flash ophints (popup +defaults) (pretty-code +iosevka) treemacs unicode vc-gutter vi-tilde-fringe window-select workspaces zen :editor file-templates fold snippets :emacs (dired +ranger +icons) electric undo vc :checkers (syntax +childframe) :tools (eval +overlay) (lookup +dictionary) (lsp +peek) (magit +forge) pdf :lang data emacs-lisp (javascript +lsp) (latex +latexmk +cdlatex +lsp +fold) (markdown +grip) (org +brain +noter +dragndrop +journal +roam +present) (python +lsp +pyenv +poetry) (sh +lsp) yaml :config (default +bindings +smartparens))
  (packages (emacsql-sqlite3) (org-download) (almost-mono-themes))
  (unpin "n/a")
  (elpa "n/a")))
</pre></details>

**Comment by hlissner** [comment]
This suggest that org didn't clone or byte-compile correctly. Try deleting `~/.emacs.d/.local/straight/repos/org-mode` and `~/.emacs.d/.local/straight/build/org-mode` manually, then run `doom sync`.

**Comment by aarohijohal** [comment]
Recompiled, I'm still getting an error:
<details><pre>
org-babel-read: End of file during parsing: /Users/Popeye/.emacs.d/.local/straight/build/org-mode/org.elc
Failed to load ’org’ package incrementally, because: (end-of-file /Users/Popeye/.emacs.d/.local/straight/build/org-mode/org.elc)
Failed to load ’org-agenda’ package incrementally, because: (end-of-file /Users/Popeye/.emacs.d/.local/straight/build/org-mode/org.elc)
Failed to load ’org-capture’ package incrementally, because: (end-of-file /Users/Popeye/.emacs.d/.local/straight/build/org-mode/org.elc)
Failed to load ’org’ package incrementally, because: (end-of-file /Users/Popeye/.emacs.d/.local/straight/build/org-mode/org.elc)
Mark set
</details></pre>

**Comment by hlissner** [comment]
I'm afraid this error makes little sense to me. I cannot reproduce it. A `End of file during parsing` error means there's a syntax error, but one in machine-generated, byte-compiled code? I'm stumped.

**Comment by hlissner** [comment]
You could try adding this to `~/.doom.d/packages.el`:

```elisp
(package! org-mode
  :recipe (:host github
           :repo "emacs-straight/org-mode"
           :files ("*.el" "lisp/*.el" "contrib/lisp/*.el")
           :no-byte-compile t))
```

This will prevent the org package from being byte-compiled.

**Comment by aarohijohal** [comment]
That didn't help either; the error just started being reported in the equivalent .el file.

If this helps: I seem to no longer have the error if I disable the `+roam` submodule form the `(org +...)` module in `:lang` inside `init.el`. The error persists if I install org-roam from the github repo instead too.

**Comment by hlissner** [comment]
Can you try updating to the latest commit of Doom (where I've recently bumped org-roam and others)? Perhaps it was fixed upstream.

**Comment by aarohijohal** [comment]
Caught it. One of the org files inside the org-roam notes repository looked like this:
```
#+TITLE: subject
#+ROAM_ALIAS: subject1" "subject2" "subject3"
```
Closing the quote fixed everything:
```
#+TITLE: subject
#+ROAM_ALIAS: subject1" "subject2" "subject3"
```

Goes to show how important the cleanliness of the org-roam notes really is.
Thanks for the follow-along and the suggestions, @hlissner.

**Comment by hlissner** [comment]
Ah, that would explain it. I'm glad you figured it out, and thanks for letting me know!
