### ISSUE TITLE
Can't switch project from fallback buffer

### ISSUE THREAD

**Issue by sei40kr** [hlissner/doom-emacs#3166]
**What did you expect to happen?**

1. Switch to a new project with `SPC p p`
1. New project opens in a new workspace

**What actually happened?**

1. Current project opens in a new workspace.

Maybe related:
https://github.com/hlissner/doom-emacs/issues/3205
https://github.com/hlissner/doom-emacs/issues/3288

**Additional details:**
↓ Here is my Doom config
https://github.com/sei40kr/doom.d

```emacs-lisp
;;
;; ui/workspaces

(when (featurep! :ui workspaces)
  (setq +workspaces-switch-project-function '(lambda (_))
        +workspaces-on-switch-project-behavior t)

  (after! persp-mode
    (setq persp-kill-foreign-buffer-behaviour 'kill
          persp-remove-buffers-from-nil-persp-behaviour nil)))
```

**Steps to reproduce:**
1. Customize `+workspaces-switch-project-function` so that it won't open project buffer.
2. Switch to a project by `SPC p p` (it should open fallback buffer)
3. Switch to another project again from fallback buffer by `SPC p p`
4. A new workspace is created, but `default-directory` won't change.

**System information:**
<details><pre>
((emacs
  (version . "27.0.90")
  (features . "RSVG IMAGEMAGICK GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS XWIDGETS PDUMPER LCMS2 GMP")
  (build . "Apr 01, 2020")
  (buildopts "--disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus/HEAD-ac3da1d/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus/HEAD-ac3da1d --with-xml2 --without-dbus --with-gnutls --with-imagemagick --with-modules --with-rsvg --with-xwidgets --with-ns --disable-ns-self-contained")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> taskrunner, origin/taskrunner 3f21d8267 2020-05-18 16:26:32 +0900")
  (dir . "~/.doom.d/"))
 (system
  (type . darwin)
  (config . "x86_64-apple-darwin19.3.0")
  (shell . "/usr/local/bin/zsh")
  (uname . "Darwin 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64")
  (path "~/.zinit/plugins/starship---starship" "~/.zinit/plugins/julienXX---terminal-notifier" "~/.zinit/plugins/direnv---direnv" "~/.pyenv/shims" "~/.jenv/shims" "~/.zinit/polaris/bin" "~/.local/bin" "~/.yarn/bin" "~/.rbenv/bin" "~/.rbenv/shims" "~/.gem/ruby/2.6.0/bin" "~/.poetry/bin" "~/.pyenv/bin" "~/perl5/bin" "~/perl5/perlbrew/bin" "~/.jenv/bin" "~/.goenv/bin" "~/.goenv/shims" "~/go/system/bin" "~/.cargo/bin" "/usr/local/bin" "/usr/local/sbin" "/usr/bin" "/bin" "/usr/sbin" "/sbin" "/usr/local/aria2/bin" "/usr/local/Cellar/emacs-plus/HEAD-ac3da1d/libexec/emacs/27.0.90/x86_64-apple-darwin19.3.0"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion (company +childframe) ivy :ui doom doom-dashboard hl-todo hydra modeline nav-flash ophints (popup +all +defaults) tabs treemacs vc-gutter window-select workspaces :editor (evil +everywhere) file-templates (format +onsave) multiple-cursors snippets word-wrap :emacs (dired +icons) vc :term vterm :checkers (syntax +childframe) :tools ansible (debugger +lsp) (docker +lsp) editorconfig ein eval (lookup +docsets) lsp magit make rgb taskrunner tmux :lang (cc +lsp) data emacs-lisp (ess +lsp) (go +lsp) (haskell +lsp) (java +lsp) (javascript +lsp) (json +lsp) (kotlin +lsp) (markdown +grip) (org +dragndrop +gnuplot +jupyter) perl (php +lsp) plantuml (python +lsp +pyenv) rest (ruby +lsp +rails +rbenv) (rust +lsp) (scala +lsp) (sh +lsp) solidity (web +css +html +lsp) (yaml +lsp) :config (default +bindings +smartparens))
  (packages (company-emoji :pin "fc45b56f3e") (expand-region :pin "0fa7c2d349") (vagrant-tramp :pin "f67925928d") (vimrc-mode :pin "13bc150a87") (pyenv-mode :disable t) (pyvenv :disable t) (rbenv :disable t))
  (unpin "n/a")
  (elpa "n/a")))
</pre></details>

**Comment by sei40kr** [comment]
I'm closing this.

```emacs-lisp
(setq +workspaces-switch-project-function #'(lambda (project-directory)
                                                (switch-to-buffer (doom-fallback-buffer))
                                                (setq default-directory project-directory)))
```

This works for me.

**Comment by sei40kr** [comment]
There're 2 cases of issues:
1. Directory in modeline won't change
2. Directory in modeline changes, but `+ivy/projectile-find-file` lists files in older project

**Comment by hlissner** [comment]
See if 2d4b946 fixes the issue for you.

**Comment by sei40kr** [comment]
@hlissner 
`projectile-project-root` in fallback buffer still indicates previous project root.

**Comment by sei40kr** [comment]
@hlissner 
Removing `projectile-root-local` from `projectile-project-root-files-functions` works perfectly for me.

**Comment by sei40kr** [comment]
@hlissner
https://github.com/hlissner/doom-emacs/commit/2d4b946e032765d73eaf4f48a7da5d3dc8185815
This workaround resets `projectile-project-root` but the one in temporary buffer:
```emacs-lisp
    (when projectile-before-switch-project-hook
      (with-temp-buffer
        ;; Load the project dir-local variables into the switch buffer, so the
        ;; action can make use of them
        (setq default-directory +workspaces--project-dir)
        (hack-dir-local-variables-non-file-buffer)
        (run-hooks 'projectile-before-switch-project-hook))
       ;; Resetting `projectile-project-root' here solves the problem!
       )
```

**Comment by hlissner** [comment]
As of 60ca118 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by sei40kr** [comment]
@hlissner It works fine! Thank you!
