### ISSUE TITLE
if: Need a valid session and a kernel to form a key

### ISSUE THREAD

**Issue by benneti** [hlissner/doom-emacs#3171]
**What did you expect to happen?**
execute babel code of "jupyter-julia" with session key after fresh start.

**What actually happened?**
On first execution it fails due to missing session key.
I think this is due to lazy loading of babel ignoring the session key.
<details><pre>
Debugger entered--Lisp error: (error "Need a valid session and a kernel to form a key")
  signal(error ("Need a valid session and a kernel to form a key"))
  error("Need a valid session and a kernel to form a key")
  (if (and session kernel (not (equal session "none"))) nil (error "Need a valid session and a kernel to form a key"))
  (let ((session (alist-get :session params)) (kernel (alist-get :kernel params))) (if (and session kernel (not (equal session "none"))) nil (error "Need a valid session and a kernel to form a key")) (concat session "-" kernel))
  org-babel-jupyter-session-key(((:colname-names) (:rowname-names) (:result-params "replace") (:result-type . value) (:results . "replace") (:exports . "code") (:cache . "no") (:noweb . "no") (:hlines . "no") (:tangle . "no") (:session . "jj")))
  (let* ((kernel (alist-get :kernel params)) (key (org-babel-jupyter-session-key params)) (client (gethash key org-babel-jupyter-session-clients))) (if client nil (setq client (org-babel-jupyter-initiate-client (org-babel-jupyter-parse-session session) kernel)) (puthash key client org-babel-jupyter-session-clients) (save-current-buffer (set-buffer (eieio-oref client (quote buffer))) (let ((inhibit-read-only t)) (prog1 (progn (let (...) (add-hook ... forget-client nil t))) (let ((win ...)) (if win (progn ...))))))) (eieio-oref client (quote buffer)))
  org-babel-jupyter-initiate-session-by-key("jj" ((:colname-names) (:rowname-names) (:result-params "replace") (:result-type . value) (:results . "replace") (:exports . "code") (:cache . "no") (:noweb . "no") (:hlines . "no") (:tangle . "no") (:session . "jj")))
  (if (equal session "none") (error "Need a session to run") (org-babel-jupyter-initiate-session-by-key session params))
  org-babel-jupyter-initiate-session("jj" ((:colname-names) (:rowname-names) (:result-params "replace") (:result-type . value) (:results . "replace") (:exports . "code") (:cache . "no") (:noweb . "no") (:hlines . "no") (:tangle . "no") (:session . "jj")))
  (buffer-local-value (quote jupyter-current-client) (org-babel-jupyter-initiate-session (alist-get :session params) params))
  (let* ((org-babel-jupyter-current-src-block-params params) (jupyter-current-client (buffer-local-value (quote jupyter-current-client) (org-babel-jupyter-initiate-session (alist-get :session params) params))) (kernel-lang (jupyter-kernel-language jupyter-current-client)) (vars (org-babel-variable-assignments:jupyter params kernel-lang)) (code (org-babel-expand-body:jupyter body params vars kernel-lang)) (result-params (assq :result-params params)) (async-p (or (equal (alist-get :async params) "yes") (plist-member params :async))) (req (jupyter-send-execute-request jupyter-current-client :code code))) (if (member "replace" (assq :result-params params)) (progn (org-babel-jupyter-cleanup-file-links))) (if (and (member "file" result-params) (or async-p (not (or (member "link" result-params) (member "graphics" result-params))))) (progn (org-babel-jupyter--remove-file-param params))) (cond (async-p (let (--cl-sync-on-export--) (setq --cl-sync-on-export-- (function (lambda nil (progn ... ...)))) (if (and (boundp (quote org-export-current-backend)) org-export-current-backend) (progn (add-hook (quote org-babel-after-execute-hook) --cl-sync-on-export-- t t))) (if (progn (or (and ... t) (signal ... ...)) (aref req 13)) org-babel-jupyter-async-inline-results-pending-indicator (jupyter-org-pending-async-results req)))) (t (while (null (jupyter-wait-until-idle req jupyter-long-timeout))) (if (progn (or (and (memq ... cl-struct-jupyter-org-request-tags) t) (signal (quote wrong-type-argument) (list ... req))) (aref req 13)) (car (progn (or (and ... t) (signal ... ...)) (aref req 10))) (prog1 (jupyter-org-sync-results req) (nconc (alist-get :result-params params) (list "raw")))))))
  org-babel-execute:jupyter-julia("1+1" ((:colname-names) (:rowname-names) (:result-params "replace") (:result-type . value) (:results . "replace") (:exports . "code") (:cache . "no") (:noweb . "no") (:hlines . "no") (:tangle . "no") (:session . "jj")))
  org-babel-execute-src-block(nil ("jupyter-julia" "1+1" ((:colname-names) (:rowname-names) (:result-params "replace") (:result-type . value) (:results . "replace") (:exports . "code") (:session . "jj") (:tangle . "no") (:hlines . "no") (:noweb . "no") (:cache . "no")) "" nil 15 "(ref:%s)"))
  org-ctrl-c-ctrl-c(nil)
  funcall-interactively(org-ctrl-c-ctrl-c nil)
  call-interactively(org-ctrl-c-ctrl-c nil nil)
  command-execute(org-ctrl-c-ctrl-c)
</pre></details>

**Steps to reproduce:**
1. Install Jupyter and ob-jupyter (org +jupyter) also (julia +lsp)
2. create an org src-block with a jupyter kernel (in my case Julia)
``` org
#+begin_src jupyter-julia :session jj
1+1
#+end_src
```

3. execute -> not working
4. execute again -> working

**System information:**

<details><pre>
((emacs
  (version . "26.3")
  (features . "XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2")
  (build . "Aug 29, 2019")
  (buildopts "--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-modules 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop 220916ae1 2020-05-18 03:41:02 -0400")
  (dir . "~/.doom.d/"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/usr/bin/fish")
  (uname . "Linux 5.6.13-arch1-1 #1 SMP PREEMPT Thu, 14 May 2020 06:52:53 +0000 x86_64")
  (path "~/.local/bin" "~/.local/bin" "/usr/local/bin" "/usr/local/sbin" "/usr/bin" "/usr/bin/site_perl" "/usr/bin/vendor_perl" "/usr/bin/core_perl" "~/.local/share/flatpak/exports/bin" "/usr/lib/jvm/default/bin" "/usr/bin/site_perl" "/usr/bin/vendor_perl" "/usr/bin/core_perl" "~/.local/share/flatpak/exports/bin" "/usr/lib/jvm/default/bin" "/usr/bin/site_perl" "/usr/bin/vendor_perl" "/usr/bin/core_perl" "/usr/lib/emacs/26.3/x86_64-pc-linux-gnu"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline ophints (popup +defaults) treemacs unicode vc-gutter vi-tilde-fringe (window-select +numbers +switch-window) workspaces :editor (evil +everywhere) file-templates fold rotate-text snippets word-wrap :emacs (dired +ranger +icons) electric (ibuffer +icons) undo vc :term vterm :checkers syntax spell grammar :tools editorconfig (eval +overlay) lookup lsp magit pdf :lang (cc +lsp) data emacs-lisp (go +lsp) (julia +lsp) (latex +latexmk +cdlatex +lsp +fold) markdown (org +jupyter) (python +lsp) (sh +fish +lsp) :config (default +bindings +smartparens))
  (packages (challenger-deep-theme) (org-ref) (jupyter) (ox-ipynb :recipe (:host github :repo "jkitchin/ox-ipynb")) (lsp-julia :recipe (:host github :repo "non-jedi/lsp-julia")))
  (unpin "n/a")
  (elpa "n/a")))
</pre></details>

**Comment by benneti** [comment]
An unelegant way to circumwent this is using `(after! org (require 'ob-jupyter))`.

**Comment by hlissner** [comment]
As the error suggests, don't you need a `:kernel` set? E.g. `:kernel julia-1.0`. You can set a default one by changing `org-babel-default-header-args:jupyter-julia`:

```elisp
(after! ob-jupyter
  (add-to-list 'org-babel-default-header-args:jupyter-julia '(:kernel . "julia-1.0")))
```

**Comment by benneti** [comment]
I use (in an after! ob-jupyter block or after! org)

``` emacs-lisp
(defun latest-jupyter-kernel (re &optional refresh)
    "try to guess the latest available kernelspec for a kernel according to the regular expresion re and refresh kernelspecs if refresh is non nil"
    (first
     (sort
      (cl-loop
       for kernelspec in (jupyter-find-kernelspecs re nil refresh)
       for (kernel . (_dir . spec)) = kernelspec
       collect kernel) 'string>)))
  (setq org-babel-default-header-args:jupyter-julia
        (list (cons :kernel (latest-jupyter-kernel "julia"))
              '(:async . "yes")
              '(:results . "drawer raw")
              '(:exports . "both")
              '(:eval . "no-export")
              '(:session . "jl")))
```
It still does only work from the first time executing unless I require ob-jupyter manually.

I think I am on the latest version:
```
$ doom version                 519ms
Doom v2.0.9 (HEAD -> develop d21b4e643 2020-11-16 20:22:02 -0500)
```

**Comment by hlissner** [comment]
> It still does only work from the first time executing unless I require ob-jupyter manually.

Can you expand on how it "works"? Your `latest-jupyter-kernel` likely doesn't work on first try because it's trying to use a function from jupyter's library before loading it. Perhaps `(require 'jupyter)` is needed before that `jupyter-find-kernelspecs` call?

**Comment by benneti** [comment]
This function returns the latest kernel available for language given by RE.
As this function is in an `after! ob-jupyter` block (which requieres `jupyter-kernelspec`) the `jupyter-find-kernelspecs` is availabe and therefore setting the default header args works as expected.
The only problem I see is that I need to require ob-jupyter manually after entering org-mode the first time.

I think the problem is that due to the way doom loads the babel languages (I do not fully grasp what doom does here, sorry) the appropriate setup is only loaded after the first block is executed.
If I remeber correctly the same setup of the header args worked before I switched to doom emacs which lead me to the conclusion it probably is more appropriate to be fixed in doom.

If you think these things are not possible to fix easily and requiring ob-jupyter after or is not an option, I can simply update the readme of the org layer to document how to be able to set it up such that it works.
These would be to either require manually or to use setq and set the complete variable after org (before anything of emacs-jupyter is loaded) such that  :kernel is available (nothing from ob-jupyter can be used in this case to assist the configuration).

PS: thanks for creating doom I use it everyday and really enjoy how fast and curated it is!

**Comment by Delanii** [comment]
I have the same issue as original author, that is, in `org-mode` inside `jupyter-python` source block I have to execute code block twice (C-c C-c C-c C-c) to get code result. How can I work around that?
I would consider it minor problem if it would be documented in `:lang org +jupyter` README (at least for now), because otherwise in first execution you get the stated warning.
If there is any way how I could contribute to fixing this I am very opened to help, however, I am very new to emacs and still exploring what I can or cannot do (so thats why I am "playing" with juypter in emacs) ...
Regards, Tomas

**Comment by benneti** [comment]
I think this is still relevant, can I get you any further details?
