### ISSUE TITLE
Problems with org-journal timestamping / org-journal-dir

### ISSUE THREAD

**Issue by jonathanwilner** [hlissner/doom-emacs#3173]
**What did you expect to happen?**

Expect that org-journal would work as expected when new org-journal entries are created, or org-journal is called via org-capture.

This would open a file for the day (depending on the file format choice) & then create a timestamped entry based on the time of day - as a subline that builds the daily log of the journal.

**What actually happened?**

Without reconfiguring the defaults in the journal.el additional module config, consistently get a "No Year Zero error), then the date is populated at the top of the org-file, but there is no time stamp at all - just the cursor at a sub-point of the whole date.

**Additional details:**

I can fix this error by either commenting out the line :

(rassq-delete-all 'org-journal-mode auto-mode-alist) in journal.el, which looks like it's messing with the auto-mode-alist.

OR 

by hard-coding in my directory /Users/jwilner/Dropbox/personal/journal/ into journal.el as the org-journal-directory.

If I want org-journal-dir to be the same folder (not a subfolder), I can't get the timestamping to work at all. This seems like it's another problem related to the setting of auto-mode-alist.

Output of Doom Info:

<details>

```
emacs   version    27.0.91
        features   RSVG DBUS GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS JSON PDUMPER LCMS2 GMP
        build      Apr 20, 2020
        buildopts  (--with-modules --without-makeinfo)
        windowsys  mac
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop 3fd3fc380 2020-05-18 18:20:47 -0400
        dir        ~/.doom.d/
system  type       darwin
        config     x86_64-apple-darwin19.4.0
        shell      /bin/zsh
        uname      Darwin 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64
        path       (~/opt/anaconda3/bin ~/opt/anaconda3/condabin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /Library/TeX/texbin /usr/local/share/dotnet ~/.dotnet/tools /Library/Apple/usr/bin /Library/Frameworks/Mono.framework/Versions/Current/Commands /usr/local/libexec/emacs/27.0.91/x86_64-apple-darwin19.4.0/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard hl-todo modeline nav-flash ophints (popup +all +defaults) treemacs unicode vc-gutter vi-tilde-fringe window-select workspaces zen :editor (evil +everywhere) file-templates fold (format +onsave) snippets :emacs (dired +icons) electric vc :term eshell vterm :checkers syntax spell :tools (eval +overlay) lookup lsp macos magit (pass +password-store +password-store-otp) pdf prodigy :lang data emacs-lisp (go +lsp) (javascript +lsp) latex markdown (org +dragndrop +gnuplot +habit +journal +jupyter +noter +pandoc +pdfview +pomodoro +present +roam) plantuml (python +lsp) sh (swift +lsp) web :email (mu4e +gmail) (notmuch +mail) :app twitter :config (default +bindings +smartparens))
        packages   ((slack :pin 61ff6fa71f32b58ce8cb9c5fc88b0f20b54bb0df) (ivy-emoji) (excorporate) (alert) (mu4e-alert) (virtual-auto-fill :recipe (:host github :repo luisgerhorst/virtual-auto-fill)) (org-super-agenda) (bookmarkplus :recipe (:host github :repo emacsmirror/bookmark-plus)) (counselweb :recipe (:host github :repo mnewt/counsel-web)) (org-web-tools :recipe (:host github :repo alphapapa/org-web-tools)) (ob-mermaid :recipe (:host github :repo arnm/ob-mermaid)) (modus-operandi-theme) (modus-vivendi-theme) (org-graph-view :recipe (:host github :repo alphapapa/org-graph-view)) (ox-jira) (calfw) (calfw-org) (calfw-cal) (pandoc-mode) (atomic-chrome))
        unpin      (n/a)
        elpa       (n/a)
```
</details>

**Comment by hlissner** [comment]
Does adding this to `~/.doom.d/config.el` fix the issue?

```org
(after! org
  (org-journal-update-auto-mode-alist))
```

**Comment by jonathanwilner** [comment]
Same result - "user-error" : There was no year zero.

It then creates a Datestamp at the top of the file with today's date.

**Comment by hlissner** [comment]
Can you provide more specific reproduction steps? I cannot reproduce this straight from a fresh instance of Emacs via `SPC n j j` (`org-journal-new-entry`).

**Comment by hlissner** [comment]
As of ecbd4b7 I believe the issue should be resolved. Turns out it was an unrelated issue with the `setq!` macro not triggering the setter for `org-journal-dir`. Let me know if that fixes your issue.
