### ISSUE TITLE
Error message hint could be misplaced

### ISSUE THREAD

**Issue by andyafter** [hlissner/doom-emacs#318]
![screen shot 2018-01-03 at 1 41 44 pm](https://user-images.githubusercontent.com/3354145/34510110-f8b4845e-f08b-11e7-8a66-1b98ba303a12.png)
As shown in the picture, the error message could be misplaced from time to time.

**Comment by hlissner** [comment]
I have experienced this myself on MacOS. It seems to be an issue with `pos-tip` (the package `flycheck-pos-tip`) being unable to reliably determine the absolute, pixel coordinates of the Emacs window, which I have no control over.

But now that you bring this to my attention, I have discovered a possible alternative to `flycheck-pos-tip`: https://github.com/flycheck/flycheck-popup-tip, which appears much newer. I will investigate it soon.

**Comment by hlissner** [comment]
I've added flycheck-popup-tip to `develop`. It will activate for MacOS users, reverting to `flycheck-pos-tip` for users on other platforms.

Please give it a try and let me know if it causes you any problems.

I'll leave this open until it hits `master`.
