### ISSUE TITLE
How can I make quickrun present results behave usual, with colors and links?

### ISSUE THREAD

**Issue by mrbig033** [hlissner/doom-emacs#3181]
At least when I run Python, `quickrun` usually opens a regular buffer with links to the lines where errors occurred. This buffer also has colors. On Doom Emacs, the results have no color and are not clickable. Is it possible to have the regular behavior on Emacs?

**Comment by hlissner** [comment]
Try disabling `+overlay` on the `:tools eval` module.

**Comment by mrbig033** [comment]
> Try disabling `+overlay` on the `:tools eval` module.

That would disable a bunch other stuff, right? Any way to do that exclusively for quickrun?

**Comment by hlissner** [comment]
No, that would exclusively disable popping up results in an overlay:

![image](https://user-images.githubusercontent.com/510883/82417776-07f55f00-9a4a-11ea-8a81-2e2e3f83fc05.png)

Or popup buffer (for larger buffers), and rely solely on quickrun's own ability to display output in its own popup buffer.

> I'm also not sure how to use flags.

1. Open `~/.doom.d/init.el`
2. Scroll down to `:tools`
3. Find `(eval +overlay)` somewhere beneath it
4. Replace `(eval +overlay)` with `eval`
5. Run `~/.emacs.d/bin/doom sync`
6. Restart Emacs

**Comment by mrbig033** [comment]
I see. So it would have no effect on the windows opened by Quickrun?

**Comment by mrbig033** [comment]
It did work. Closing.
