### ISSUE TITLE
High CPU usage when working on C files

### ISSUE THREAD

**Issue by gueorgui** [hlissner/doom-emacs#3192]
**What did you expect to happen?**

- Open a simple C file
- Start make some changes
- CPU usage remains normal

**What actually happened?**

- Open a simple C file
- Start make some changes
- CPU usage goes to 100% of a core as I'm typing

**Additional details:**
I ran a profiler while working on the file:

![image](https://user-images.githubusercontent.com/3792/82568140-4b4cec00-9b76-11ea-9b4c-6d466b79b7c1.png)
 

**System information:**
<details><pre>
((emacs
  (version . "27.0.91")
  (features . "XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP")
  (build . "May 09, 2020")
  (buildopts "--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --mandir=/usr/share/man --with-gameuser=:games --with-sound=alsa --with-modules --without-gconf --without-gsettings --with-x-toolkit=gtk3 --without-xaw3d --without-m17n-flt --with-cairo --without-compress-install 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -g -flto -s -fuse-ld=gold' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop a262527a7 2020-05-21 04:33:39 -0400")
  (dir . "~/.doom.d/"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/usr/bin/fish")
  (uname . "Linux 5.6.13-arch1-1 #1 SMP PREEMPT Thu, 14 May 2020 06:52:53 +0000 x86_64")
  (path "~/.nvm/versions/node/v12.16.1/bin" "~/.rbenv/shims" "~/go/bin" "~/.bin" "~/.yarn/bin" "~/.config/yarn/global/node_modules/.bin" "~/.rbenv/bin" "~/.rbenv/shims" "/usr/local/bin" "/usr/local/sbin" "/usr/bin" "/usr/lib/jvm/default/bin" "/usr/bin/site_perl" "/usr/bin/vendor_perl" "/usr/bin/core_perl" "~/go/bin" "~/.bin" "~/.yarn/bin" "~/.config/yarn/global/node_modules/.bin" "~/.rbenv/bin" "~/.rbenv/shims" "/usr/local/bin" "/usr/local/sbin" "/usr/bin" "/usr/lib/jvm/default/bin" "/usr/bin/site_perl" "/usr/bin/vendor_perl" "/usr/bin/core_perl"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company ivy :ui deft doom hl-todo hydra modeline nav-flash ophints (popup +defaults) unicode vc-gutter vi-tilde-fringe window-select workspaces zen :editor (evil +everywhere) file-templates fold multiple-cursors snippets word-wrap :emacs dired electric undo vc :term vterm :tools debugger direnv docker editorconfig (eval +overlay) gist lookup lsp magit pass pdf upload :lang (cc +lsp) common-lisp data elixir emacs-lisp erlang (go +lsp) (haskell +dante) json (javascript +lsp) (latex +latexmk +cdlatex) ledger markdown (org +roam +journal +pomodoro +pandoc) plantuml (ruby +rails +lsp) (rust +lsp) (sh +lsp) (web +lsp) yaml :email (mu4e +gmail) :config literate (default +bindings +smartparens))
  (packages (evil-matchit) (modus-operandi-theme) (modus-vivendi-theme) (org-clock-convenience))
  (unpin "n/a")
  (elpa "n/a")))
</pre></details>

**Comment by hlissner** [comment]
Odd. This should have been fixed in https://github.com/hlissner/evil-escape/commit/2c24674da900d0d9ab463c8d22646437399fcdf8

Could you please expand `evil-escape-pre-command-hook` as much as possible? And check that `~/.emacs.d/.local/straight/repos/evil-escape`'s remote is truly set to `hlissner/evil-escape`, and not `syl20bnr/evil-escape`?

**Comment by gueorgui** [comment]
Sorry for the silly question, but how do you expand the hook in the profiler? Hitting Enter just takes me to the function definition.

**Comment by yoavm448** [comment]
You can expand with `TAB`.

**Comment by gueorgui** [comment]
@yoavm448 Thank you!

I ran `doom upgrade` before profiling, but then it turned out that updating has fixed the issue.

**Comment by gueorgui** [comment]
Well, the issue returned. Here is the expanded profiler view, although the functions that take up the most resources have changed from `evil-escape-pre-command-hook` to `company`-related stuff.

![Screenshot from 2020-05-30 21-59-10](https://user-images.githubusercontent.com/3792/83338967-2157a000-a2c1-11ea-8661-9e57e66755d0.png)

The only difference I could notice between my just-after-updating attempt (with normal CPU usage) and the current attempt (high CPU usage) is that I now also have another workspace open (in another frame) that contains a large Ruby on Rails project, with LSPs running for Ruby, JS, and `web-mode`.

If I close that workspace, CPU usage in my C workspace goes back to normal.

**Comment by gueorgui** [comment]
The Ruby on Rails workspace does not have any special performance issues, except for one buffer that contains a 600-line YAML file, which suffers from terrible performance. Killing that buffer in the Rails project does bring down the CPU usage in my C buffers, but not to the same level as if the Rails project was not open at all.

For what it's worth, I'm running Emacs as a daemon (via systemd), and I have 3 `emacsclient` frames open and about 15 visible buffers across those frames.
