### ISSUE TITLE
No url found for submodule path '[submodules]' in .gitmodules /

### ISSUE THREAD

**Issue by C0DK** [hlissner/doom-emacs#3193]
**What did you expect to happen?**

I was trying to `SPC SPC` look at the files in the projectile project.

**What actually happened?**
I got the following error, because i previously had a submodule in git, but then removed it, and projectile somehow adds it to the files, but doesn't remove it correctly.. somehow.
```
call-process-shell-command: Setting current directory: No such file or directory, /home/cdk/Documents/fatal: No url found for submodule path 'org/school/soft_arch_recovery' in .gitmodules
/
```

I've had this issue before, where i was able to delete some emacs cache, which solved it, but I don't seem to remember where that cache was (essentially deleting the whole projectile cache)

**Additional details:**
- Include a [link to your private config](https://github.com/C0DK/dotfiles/tree/master/home/.config/doom)

<details><pre>
Projectile is initializing cache for /home/cdk/Documents/ ...
call-process-shell-command: Setting current directory: No such file or directory, /home/cdk/Documents/fatal: No url found for submodule path 'org/school/soft_arch_recovery' in .gitmodules
/
</pre></details>

**Steps to reproduce:**
1. create a project in doom with a git submodules
2. Delete the submodule
3. try to open a file

**System information:**
<details><pre>
((emacs
  (version . "27.0.90")
  (features . "XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP")
  (build . "Apr 13, 2020")
  (buildopts "--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --mandir=/usr/share/man --with-gameuser=:games --with-sound=alsa --with-modules --without-gconf --without-gsettings --with-x-toolkit=gtk3 --without-xaw3d --without-m17n-flt --with-cairo --without-compress-install 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -g -flto -s -fuse-ld=gold' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop 375faedb1 2020-05-16 05:38:20 -0400")
  (dir . "~/.dotfiles/home/.config/doom/"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/usr/bin/zsh")
  (uname . "Linux 4.19.121-1-MANJARO #1 SMP Wed May 6 10:52:46 UTC 2020 x86_64")
  (path "~/bin" "/usr/local/bin" "~/.local/bin" "~/go/bin" "~/.config/emacs/bin/" "~/bin" "/usr/local/bin" "~/.local/bin" "~/go/bin" "~/.config/emacs/bin/" "~/bin" "/usr/local/bin" "~/.local/bin" "~/go/bin" "~/.config/emacs/bin/" "~/.local/bin" "~/bin" "/usr/local/bin" "~/.local/bin" "~/go/bin" "~/.emacs.d/bin/" "~/.local/bin" "/usr/local/bin" "/usr/bin" "/bin" "/usr/local/sbin" "/usr/lib/jvm/default/bin" "/usr/bin/site_perl" "/usr/bin/vendor_perl" "/usr/bin/core_perl" "/usr/lib/jvm/default/bin" "/usr/bin/site_perl" "/usr/bin/vendor_perl" "/usr/bin/core_perl" "/usr/lib/emacs/27.0.90/x86_64-pc-linux-gnu"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard doom-quit hl-todo indent-guides modeline nav-flash ophints (popup +all +defaults) unicode vc-gutter vi-tilde-fringe window-select workspaces zen :editor (evil +everywhere) file-templates fold format multiple-cursors rotate-text snippets word-wrap :emacs (dired +ranger) electric ibuffer vc :term term :checkers syntax (spell +everywhere) :tools debugger editorconfig ein (eval +overlay) gist (lookup +docsets) lsp magit make pass pdf rgb :lang common-lisp csharp data emacs-lisp fsharp go (java +meghanada) javascript latex ledger markdown (org +dragndrop +capture +export +publish +present) (python +lsp) rest sh web :app calendar (rss +org) :config literate (default +bindings +smartparens))
  (packages (ox-twbs) (elfeed) (prettier-js) (ranger))
  (unpin "n/a")
  (elpa "n/a")))

</pre></details>

**Comment by hlissner** [comment]
Does `M-x projectile-cleanup-known-projects` solve this issue?

**Comment by C0DK** [comment]
sadly, it does not.

**Comment by hlissner** [comment]
What about invalidating that project's cache with `SPC p i` (`M-x projectile-invalidate-cache`).

Also, do you have ripgrep or fd installed?

**Comment by C0DK** [comment]
I did run `SPC p i` but that failed as well (gave the same error) - it, randomly disappeared now. not sure what i did though (after a week or so). it is a local bug in that project, but afaik can be replicated by adding a submodule to a project and then syncing it with git, and then removing said submodule.
