### ISSUE TITLE
Unreadably tiny fonts on Windows 10

### ISSUE THREAD

**Issue by notuntoward** [hlissner/doom-emacs#3194]
I've just installed doom-emacs on my Windows 10 machine, following the instructions [here](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#on-windows).  The problem is the fonts are all far too small to read. 

This is on a Surface Book (high DPI screen) and with emacs 26.3, downloaded by the choco package manager.  If I run emacs without the doom configs, the fonts are reasonably sized, no matter what Windows machine and display I run it on.   So it seems that the doom configs are overriding something that works sensibly on this Windows build of emacs.

**Comment by hlissner** [comment]
Open up `~/.doom.d/config.el` in another editor and find this line:

```elisp
(setq doom-font (font-spec :family "monospace" :size 14))
```

And either 

1. Change `:size 14` to, say, `:size 24`
2. Or delete the whole line altogether.

Does either fix your issue?

**Comment by notuntoward** [comment]
Thanks.  If I just comment out that line, fonts look normal again, so that fixes it for me.  

But I'm not sure what should be done for Windows users in general.

**Comment by hlissner** [comment]
In f47ec8b I've removed the default `setq` line for `doom-font`, so this should affect future Windows users. For now I'll consider this temporarily resolved, and hopefully revisit it in the future when I have time to look at improving Windows support in general. Thanks for bringing it to my attention!
