### ISSUE TITLE
Clipetty displays OSC 52 escape sequences on unsupported terminals upon yank

### ISSUE THREAD

**Issue by lzhang10** [hlissner/doom-emacs#3195]
**What did you expect to happen?**
Yanking text does not mess up terminal. 
Tested in lxterminal 0.3.1 running on CentOS 7.

**What actually happened?**
Something like this is displayed after yanking some text:
c]52;c;!]52;c;eWh0dHBzOi8vZ2l0aHViLmNvbS9obGlzc25lci9kb29tLWVtYWMK

This only happens on lxterminal 0.3.1 on CentOS7. xterm is fine.

**Additional details:**
I traced to this PR https://github.com/hlissner/doom-emacs/pull/2734 that caused this issue. The code `(global-clipetty-mode +1)` turns clipetty-mode on globally. Unfortunately in my particular lxterminal setup the OSC 52 escape sequence is not understood.

I looked up clipetty.el's source code at https://github.com/spudlyo/clipetty/blob/master/clipetty.el#L129 and found the code assumes the terminal supports OSC 52 escape sequence. It probably should have looked up terminfo instead of making such assumption.

My current solution is to disable global-clipetty-mode in my config. I wonder if global-clipetty-mode should be turned off by default, given the assumption made in the code above. Even newer version of lxterminal may support OSC 52 sequence there are many other terminals out there do not. 

**Steps to reproduce:**
I can only reproduce this on one machine running lxterminal 0.3.1 on CentOS7. lxterminal 0.3.2 running under Debian 10 or NixOS 20.03 does not have this issue. xterm also does not have this issue.

**Comment by hlissner** [comment]
As of 0a4841b clipetty is now optional (in the new [`:os tty` module](https://github.com/hlissner/doom-emacs/blob/develop/modules/os/tty/README.org), behind the `+osc` flag.

You may be interested in enabling this module _without_ the `+osc` flag -- it will use the `xclip.el` package instead (which will talk to `xclip` or `xsel` in the terminal). Let me know if that doesn't fix the problem and I'll reopen this issue. Thanks for bringing it to my attention!
