### ISSUE TITLE
go-guru-definition does not work on go import area

### ISSUE THREAD

**Issue by andyafter** [hlissner/doom-emacs#320]
When I jump the cursor to the import package name area and presses ```C-c C-o j```, it cannot jump to the package. It should be able to jump to the dired page of the package folder. As shown in the following image, it says ```no identifiers found```
<img width="508" alt="screen shot 2018-01-04 at 12 19 32 pm" src="https://user-images.githubusercontent.com/3354145/34550174-919b7534-f149-11e7-9498-725a385e6e02.png">

If you could point me where to look for I could try to fix the code and pull request. So far not very familiar with the code base.

**Comment by hlissner** [comment]
Odd. I can't tell if this is an issue with `go-guru` or Doom. If go-guru is working elsewhere in the buffer, I would imagine it's the former, but I'll look into this over the weekend.

**Comment by andyafter** [comment]
Actually it works fine in Prelude. Also not sure what could go wrong.

**Comment by andyafter** [comment]
godef-jump works fine however.

**Comment by hlissner** [comment]
Sorry for taking so long to get to this. I looked into Prelude and Spacemacs, and even into go-guru. There is no indication that any of these support jumping to imports directly. If you are still using prelude, could you see what command you are invoking to follow imports? It can't be `go-guru-definition`, as far as I can tell.
