### ISSUE TITLE
Emacs Snapshots after 20200520:100299-f0b0105~ubuntu20.04.1 break Doom

### ISSUE THREAD

**Issue by Hindol** [hlissner/doom-emacs#3203]
**What did you expect to happen?**

(I know Doom is not supported on Emacs 28+ but this might be something you are interested in.)
I expected Doom to work.

**What actually happened?**

Doom failed to load.

**Additional details:**

The last working Emacs version is [20200520:100299-f0b0105~ubuntu20.04.1](https://launchpad.net/~ubuntu-elisp/+archive/ubuntu/ppa/+packages?field.name_filter=&field.status_filter=&field.series_filter=focal)

<details><pre>
The doctor will see you now...

> Checking your Emacs version...
! Emacs 28.0.50 detected. Doom doesn't support Emacs 28/HEAD. It is unstable and may cause errors.
> Checking for Emacs config conflicts...
> Checking for private config conflicts...
> Checking for stale elc files...
> Checking Doom Emacs...

Eager macro-expansion failure: (invalid-read-syntax "Invalid byte-code object")
Eager macro-expansion failure: (invalid-read-syntax "Invalid byte-code object")
! Attempt to load DOOM failed
  (Invalid byte-code object)

There are 2 warnings!
✓ Finished! (1.6690s)
</pre></details>

**Steps to reproduce:**

1. Upgrade Emacs.
1. See Doom break.

**System information:**

<details><pre>
((emacs
  (version . "28.0.50")
  (features . "XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER LCMS2 GMP")
  (build . "May 19, 2020")
  (buildopts "--build=x86_64-linux-gnu --prefix=/usr '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' --sysconfdir=/etc --localstatedir=/var --disable-silent-rules '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' --disable-maintainer-mode --disable-dependency-tracking --prefix=/usr --sharedstatedir=/var/lib --program-suffix=-snapshot --with-modules=yes --with-x=yes --with-x-toolkit=gtk3 --with-xwidgets=yes 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/emacs-snapshot-YtYR4K/emacs-snapshot-100293=. -fstack-protector-strong -Wformat -Werror=format-security' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro'")
  (windowsys . batch)
  (daemonp))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop a262527a7 2020-05-21 04:33:39 -0400")
  (dir . "~/.doom.d/"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/bin/bash")
  (uname . "Linux 4.19.104-microsoft-standard #1 SMP Wed Feb 19 06:37:35 UTC 2020 x86_64")
  (path "~/.config/nvm/14.3.0/bin" "~/.linuxbrew/lib/ruby/gems/2.7.0/bin" "~/.emacs.d/bin" "~/.linuxbrew/bin" "~/.cargo/bin" "~/.local/bin" "~/.linuxbrew/lib/ruby/gems/2.7.0/bin" "~/.emacs.d/bin" "~/.linuxbrew/bin" "~/.cargo/bin" "~/.local/bin" "~/Code/kusto/bin" "~/.linuxbrew/lib/ruby/gems/2.7.0/bin" "~/.emacs.d/bin" "~/.linuxbrew/bin" "~/.cargo/bin" "~/.local/bin" "/usr/local/sbin" "/usr/local/bin" "/usr/sbin" "/usr/bin" "/sbin" "/bin" "/usr/games" "/usr/local/games" "/mnt/c/Program Files (x86)/Microsoft SDKs/Azure/CLI2/wbin" "/mnt/c/Program Files/Common Files/Microsoft Shared/Microsoft Online Services" "/mnt/c/Program Files (x86)/Common Files/Microsoft Shared/Microsoft Online Services" "/mnt/c/WINDOWS/system32" "/mnt/c/WINDOWS" "/mnt/c/WINDOWS/System32/Wbem" "/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/" "/mnt/c/WINDOWS/System32/OpenSSH/" "/mnt/c/Program Files/dotnet/" "/mnt/c/Program Files/Microsoft SQL Server/130/Tools/Binn/" "/mnt/c/Program Files/Microsoft/Web Platform Installer/" "/mnt/c/Program Files/Microsoft Service Fabric/bin/Fabric/Fabric.Code" "/mnt/c/Program Files/Microsoft SDKs/Service Fabric/Tools/ServiceFabricLocalClusterManager" "/mnt/c/Program Files/PowerShell/7/" "/mnt/c/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn/" "/mnt/c/Program Files/Git/cmd" "/mnt/c/Users/hiadhy/go/bin" "/mnt/c/Users/hiadhy/scoop/apps/idea/current/bin" "/mnt/c/Users/hiadhy/scoop/apps/rustup/current/.cargo/bin" "/mnt/c/Users/hiadhy/AppData/Local/CloudBuild" "/mnt/c/Users/hiadhy/scoop/apps/nvm/current/nodejs/nodejs" "/mnt/c/Users/hiadhy/scoop/apps/openjdk/current/bin" "/mnt/c/Users/hiadhy/scoop/shims" "/mnt/c/Users/hiadhy/.dotnet/tools" "/mnt/c/Users/hiadhy/AppData/Local/Microsoft/WindowsApps" "/mnt/c/Users/hiadhy/AppData/Local/Programs/Microsoft VS Code/bin" "/mnt/c/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/Common7/IDE" "/mnt/c/Program Files/Emacs/x86_64/bin" "/mnt/c/Users/hiadhy/.emacs.d/bin" "/mnt/c/Users/hiadhy/AppData/Local/Microsoft/WindowsApps" "/snap/bin" "~/.dotnet/tools" "~/.dotnet/tools" "~/.dotnet/tools" "/usr/lib/x86_64-linux-gnu/emacs/28.0.50/x86_64-linux-gnu"))
 (config
  (envfile)
  (elc-files . 139)
  (modules :completion company ivy :ui deft doom doom-dashboard doom-quit hl-todo modeline ophints (popup +defaults) pretty-code vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold lispy snippets :emacs dired electric undo vc :checkers syntax :tools (eval +overlay) lookup lsp magit :lang clojure csharp emacs-lisp (go +lsp) markdown (org +dragndrop +gnuplot +journal +pandoc +present) python sh yaml :config (default +bindings +smartparens))
  (packages "n/a")
  (unpin "n/a")
  (elpa "n/a")))
</pre></details>

**Comment by scriptmode** [comment]
Is this the error?

> Debugger entered--Lisp error: (invalid-read-syntax "Invalid byte-code object")
>   read(#<buffer  *load*-427841>)
>   eval-buffer(#<buffer  *load*-427841> nil "$DOOM_LOCAL/straight/build/use-package/use-package-core.el" nil t)  ; Reading at buffer position 39039

For this a simple update to the latest use-package is neccessary. They had some outdated code which is not working anymore on newer emacs. The fix remains working on old emacs, so there is no harm in updating.
