### ISSUE TITLE
Phpactor LSP :: No LSP server for php-mode(check *lsp-log*).

### ISSUE THREAD

**Issue by mdphoto** [hlissner/doom-emacs#3206]
Hi
Open file.php
I've the error 
LSP :: No LSP server for php-mode(check *lsp-log*).

Backtrace:
DOOM Running doom hook: lsp!
zstd uncompressing .!home!michel!Sites_WWW!pardem!Site!pardem_sh!web!.ht.router.php.~undo-tree~.zst...done
DOOM [ui/doom-dashboard] Changed dashboard’s PWD to /home/michel/Sites_WWW/pardem/Site/pardem_sh/
LSP :: No LSP server for php-mode(check *lsp-log*).
Garbage collecting...done (0.190s)

</pre></details>

**Steps to reproduce:**
Install doom emacs
In .doom/init.el active
LSP ans PHP +lsp
M-x phpactor-install-or-upgrade 'log is ok"
bin/doom sync
restart doom-emacs
open foo.
LSP :: No LSP server for php-mode(check *lsp-log*).php

**System information:**
<details>

```
emacs   version    26.3
        features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2
        build      août 29, 2019
        buildopts  (--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-modules 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now)
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      grafted, HEAD -> develop, origin/develop, origin/HEAD 4c61f22 2020-05-20 04:46:37 -0400
        dir        ~/.doom.d/
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/zsh
        uname      Linux 5.6.12-1-MANJARO #1 SMP PREEMPT Sun May 10 14:36:43 UTC 2020 x86_64
        path       (~/.composer/vendor/bin ~/.platformsh/bin ~/.config/composer/vendor/bin ~/.config/composer/vendor/felixfbecker/language-server ~/.config/composer/vendor/bin ~/.local/bin /usr/local/bin /usr/bin /bin /usr/local/sbin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /sbin /usr/sbin /usr/lib/emacs/26.3/x86_64-pc-linux-gnu/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion (company +auto +childframe) (ivy +fuzzy +prescient) :ui doom doom-dashboard doom-quit hl-todo indent-guides modeline ophints (popup +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor file-templates fold (format +onsave) snippets :emacs dired electric (undo +tree) vc :term vterm :checkers syntax :tools docker editorconfig (eval +overlay) lookup lsp magit pdf rgb :lang cc data emacs-lisp json markdown org (php +lsp) python rest sh (web +css +html +lsp) yaml :email (mu4e +gmail) :app calendar irc (rss +org) :config (default +bindings +smartparens))
        packages   ((flycheck-grammalecte) (mu4e-alert) (telega) (drupal-mode) (geben) (arduino-mode) (platformio-mode) (flycheck-phpstan) (phpactor) (flymake-css) (company-phpactor))
        unpin      (n/a)
        elpa       (n/a)
```

</details>

**Comment by AloisJanicek** [comment]
I don't see phpactor lsp being supported upstream in [emacs-lsp](https://emacs-lsp.github.io/lsp-mode/page/languages/), and in doom-emacs [phpactor.el](https://github.com/emacs-php/phpactor.el) is activated only when +lsp flag is not being enabled for php module.

You can try to point emacs-lsp to phpactor by customizing `lsp-clients-php-server-command` variable (replace second string with the absolute path to the `phpactor.php` file)
```
(after lsp-clients
  (setq lsp-clients-php-server-command '("php" "/usr/share/php/php-language-server/bin/php-language-server.php"))
)
```
and _maybe_ it will just work.

But either way, this is certainly not a doom-emacs bug. [emacs-lsp/lsp-mode](https://github.com/emacs-lsp/lsp-mode) would be the right place to ask for adding support for the 4th different php lsp server (in addition to already supported intelphense, felixbecker and serenata)

**Comment by mdphoto** [comment]
Hi,

Ok it's clearer for me phpactor is not enable if +lsp flag, I thought I understood the opposite

Sorry for Bug tag.
Thank you.
