### ISSUE TITLE
Fix minor issue with python indentation

### ISSUE THREAD

**Issue by xiangchen2011** [hlissner/doom-emacs#3211]
**What did you expect to happen?**
```python
def hello():
    print("hello")
def world():
    print("world")
```

**What actually happened?**
```python
def hello():
    print("hello")
    def world():
        print("world")
```

**Additional details:**
using snippets `def` function. When I type the second function `world`, the auto-format tool will format the second function as a subsection of the first one.
```python
def hello(): #press `tab` key to jump to content of function
    print("hello") #change the content and press `enter` at the end of line
def world():
    print("world")
```
will be formatted as follows:
```python
def hello():
    print("hello")
    def world():
        print("world")
```
But if I type `tab` to jump the end of snippets. e.g.
```python
def func_name():
    pass #always type `tab`
def fund_name():
    pass #always type `tab`
```
this situation would not be affected.

**Comment by xiangchen2011** [comment]
New discovery:
```python
def xxx():
    xxx
    xxx
    xxx
    xxx
    pass
```
When the `pass` keyword appears, the cursor will be back the upper indentation level.

**Comment by xiangchen2011** [comment]
![image](https://user-images.githubusercontent.com/13866870/82753104-b1937200-9df5-11ea-840b-cefcd55f8a62.png)

**Comment by xiangchen2011** [comment]
![image](https://user-images.githubusercontent.com/13866870/82753201-7180bf00-9df6-11ea-89c3-d1e6a71a30b8.png)

**Comment by gagbo** [comment]
[PEP 8](https://www.python.org/dev/peps/pep-0008/#blank-lines) recommends having _at least_ a blank line between functions (1 between class methods, 2 between top-level definitions).

Do you have the same behaviour when you have that blank line between hello and world ?

**Comment by xiangchen2011** [comment]
Yes.
![image](https://user-images.githubusercontent.com/13866870/82753695-37b1b780-9dfa-11ea-85f7-724d93c6c819.png)

**Comment by gagbo** [comment]
I guess the indentation just gave up :( I don't know which one is used so I don't know where we can go to patch that. I guess I had the same issue, and just bit it and manually reindented my functions when I defined them

**Comment by xiangchen2011** [comment]
Maybe the problem is the configuration of the `snippets` module. [https://github.com/hlissner/doom-snippets/blob/master/python-mode/def](url)

**Comment by hlissner** [comment]
Not really sure where to call the bug, honestly.

1. `python-mode` indents an nooping `def` (with a `pass`) differently than a non-empty function.
2. PEP 8 says you need two empty lines between functions, but `python-mode` doesn't change its indentation after the second empty line.
3. The snippets module enables `yas-also-auto-indent-first-line`, which reindents the expanded snippet entirely upon expansion.

I'll disable `yas-also-auto-indent-first-line`, but that doesn't solve 1 and 3, which should be reported upstream, to the emacs devs. I can reproduce it in vanilla Emacs.

2 on the other hand isn't really a bug, yasnippet is simply relying on faulty indent logic.
