### ISSUE TITLE
sly does not honor `sly-lisp-implementations` setting

### ISSUE THREAD

**Issue by timotheosh** [hlissner/doom-emacs#3214]
**What did you expect to happen?**
```emacs-lisp
(setq! sly-lisp-implementations
         '((sbcl ("~/programs/bin/ros" "-L" "sbcl" "-Q" "run") :coding-system utf-8-unix)
           (clisp ("~/programs/bin/ros" "-L" "clisp" "-Q" "run"))
           (clozure-cl ("~/programs/bin/ros" "-L" "ccl-bin" "-Q" "run"))
           (cmucl ("~/programs/bin/ros" "-L" "cmu-bin" "-Q" "run"))
           (ecl ("~/programs/bin/ros" "-L" "ecl" "-Q" "run") :coding-system utf-8-unix)
           (abcl ("~/programs/bin/ros" "-L" "abcl-bin" "-Q" "run"))))
```
Pressing `M-- ` followed by `M-x sly` should prompt me for `sbcl clisp clozure-cl cmucl ecl abcl`

**What actually happened?**
Only prompts me for `sbcl` as the only option. If you remove the sbcl option, it will just fail to connect.

**Additional details:**
- Include a link to your private config
This is an out-of-the-box config with `common-lisp` enabled, `evil` disabled, and the setting for `sly-lisp-implementations` posted above.

**Steps to reproduce:**
1. Run `doom install` on new drirectory
2. Uncomment `common-lisp` in init.el (I also commented out evil mode).
3. Run `doom run`
4. Evaluate a value for `sly-lisp-implementations` like above

**System information:**
<details><pre>
```
emacs   version    27.0.91
        features   XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS PDUMPER LCMS2 GMP
        build      May 11, 2020
        buildopts  (--prefix=/usr/local --with-sound=alsa --without-gconf --with-x=yes --with-x-toolkit=gtk3 --with-toolkit-scroll-bars --with-cairo --with-json --with-modules --without-pop --with-mailutils)
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop, origin/develop, origin/HEAD a262527a7 2020-05-21 04:33:39 -0400
        dir        ~/.doom-test/
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/bash
        uname      Linux 5.3.0-7648-generic #41~1586790036~18.04~600aeb5-Ubuntu SMP Mon Apr 13 17:47:15 UTC  x86_64
        path       (~/perl5/bin ~/.cargo/bin ~/bin ~/programs/share/node/bin ~/programs/lib/chicken/bin ~/programs/share/golang/bin ~/programs/sbin ~/programs/bin ~/.guix-profile/bin ~/.nix-profile/bin ~/.roswell/bin ~/.local/bin ~/perl5/bin ~/.guix-profile/bin /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /usr/games /usr/local/games /snap/bin ~/.komodoide/12.0/XRE/state /usr/local/libexec/emacs/27.0.91/x86_64-pc-linux-gnu/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company (ivy +icons) :ui doom doom-dashboard doom-quit hl-todo modeline ophints (popup +defaults) vc-gutter vi-tilde-fringe workspaces :editor file-templates fold snippets :emacs dired electric undo vc :checkers syntax :tools (eval +overlay) lookup magit :lang common-lisp emacs-lisp markdown org sh :config (default +bindings +smartparens))
        packages   (n/a)
        unpin      (n/a)
        elpa       (n/a)
```
</pre></details>

**Comment by hlissner** [comment]
Did you remember to wrap that `(setq! sly-lisp-implementations ...)` in an `(after! sly ...)` block?

**Comment by timotheosh** [comment]
> Did you remember to wrap that `(setq! sly-lisp-implementations ...)` in an `(after! sly ...)` block?

Yes, I did. Which, by the way, seems to not read the `sly-lisp-implemetations` variable at all, and does not give me a choice, but runs the sbcl on my path. That might be related. I am not sure. The way to replicate my experience is to evaluate the `setq!` after Doom starts up. Sly then prompts me for only sbcl, if it is defined, or fails to connect to any lisp if it isn't.

**Comment by hlissner** [comment]
I can't reproduce this. In vanilla Doom, I added this to `~/.doom.d/config.el`:

```lisp
(after! sly
  (setq sly-lisp-implementations
        '((sbcl ("~/programs/bin/ros" "-L" "sbcl" "-Q" "run") :coding-system utf-8-unix)
          (clisp ("~/programs/bin/ros" "-L" "clisp" "-Q" "run"))
          (clozure-cl ("~/programs/bin/ros" "-L" "ccl-bin" "-Q" "run"))
          (cmucl ("~/programs/bin/ros" "-L" "cmu-bin" "-Q" "run"))
          (ecl ("~/programs/bin/ros" "-L" "ecl" "-Q" "run") :coding-system utf-8-unix)
          (abcl ("~/programs/bin/ros" "-L" "abcl-bin" "-Q" "run")))))
```

(I've tried both `setq` and `setq!`).

I fire up Doom. `M-- M-x sly`, and I get a prompt

![image](https://user-images.githubusercontent.com/510883/82766322-16e26580-9dec-11ea-8590-02d613bd0a4b.png)

**Comment by hlissner** [comment]
Oh, hold up. Did you run `doom sync` after uncommening `common-lisp` in `~/.doom.d/init.el`?

**Comment by timotheosh** [comment]
I did, but I also found my problem. Holding ~Alt~ while pressing minus changes the font size instead of `C-u --`. If I release ~Alt~ before pressing `-`, it all works as expected. I'll close this issue.
