### ISSUE TITLE
doom-unicode-font use Noto Color Emoji instead 

### ISSUE THREAD

**Issue by alxiong** [hlissner/doom-emacs#3216]
**Describe the feature**
This is trying to make a case for replacing [default unicode font](https://github.com/hlissner/doom-emacs/blob/6a8e990459c070b29852806ed92e726233a7d603/core/core-ui.el#L47) for Linux from `Symbola` to [`Noto Color Emoji`](https://www.google.com/get/noto/#emoji-zsye-color) which seems a lot more popular with richer emoji libraries while being free to download for all.

**Comment by tecosaur** [comment]
Don't you lose a lot of symbols?

**Comment by alxiong** [comment]
Hmm.. I think [`Noto Sans`](https://www.google.com/get/noto/#sans-lgc) has all the symbols that `Symbola` got.

So maybe setting the fontface to be Noto and download a few variants ( including Noto Sans, Serif, Symbol, Color Emoji, Emoji). 

Would that work? 
(Btw, i thought the MacOS counterpart `Apple Color Emoji` is also primarily emoji, not ancient greek symbols?)

**Comment by skaven-gear** [comment]
[noto-color-emoji causes crash for Emacs within Gnu/linux](https://askubuntu.com/questions/1076735/emacs-crashes-on-pasting-the-unicode-symbol)
I experienced my self on a debian.
It is related to GTK.

**Comment by tecosaur** [comment]
> Hmm.. I think Noto Sans has all the symbols that Symbola got.

I wish I could find a nice symbola replacement, but taking a look at the two it seems Noto Sans Symbols has a way to go. Just looking at the character counts
 - Noto Sans : 2750
 - Noto Sans Symbols : 834
 - Symbola : 9568

For example, testing my current org pretty symbols, I find that in symbola I see this
![image](https://user-images.githubusercontent.com/20903656/83224524-2bd64480-a1b0-11ea-836b-e40a06fb8b2e.png)
whereas in noto sans symbols, I get this
![image](https://user-images.githubusercontent.com/20903656/83224549-398bca00-a1b0-11ea-9107-69920c262179.png)

**Comment by alxiong** [comment]
@tecosaur Oh, okay, I wasn't aware of that. I guess then this might be closure of this issue for now.
Thanks for the info.

**Comment by tecosaur** [comment]
As I said, I _wish_ there was a nice, sans-serif, good coverage symbol font. Please let us know if you find one :)
