### ISSUE TITLE
Broken backspace in the minibuffer

### ISSUE THREAD

**Issue by wedens** [hlissner/doom-emacs#3217]
**What did you expect to happen?**
Backspace always deletes a character in the minibuffer.

**What actually happened?**
At some point (probably after some spaces) backspace stops deleting and just does nothing until cursor is moved.

**Additional details:**

Removing `+default--delete-backward-char-a` advice (`(advice-remove #'delete-backward-char #'+default--delete-backward-char-a)`) fixes the problem, so something in the advice is the problem.

**Steps to reproduce:**
1. open eval or ivy minibuffer
2. type something (probably should have spaces)
3. hit backspace multiple times

**System information:**
<details><pre>
emacs   version    27.0.90
        features   XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GSETTINGS GLIB NOTIFY INOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER GMP
        build      May 26, 2020
        buildopts  (--prefix=/nix/store/qzs2ch8sbd7ddw7nk9xm0007pn6vinvj-emacs-git-20200321.0 --disable-build-details --with-modules --with-x-toolkit=gtk3 --with-xft CFLAGS=-DMAC_OS_X_VERSION_MAX_ALLOWED=101200)
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD, upstream/develop, origin/develop, origin/HEAD, develop a262527a7 2020-05-21 04:33:39 -0400
        dir        ~/dotfiles/doom/
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /run/current-system/sw/bin/zsh
        uname      Linux 5.6.7 #1-NixOS SMP Thu Apr 23 08:38:27 UTC 2020 x86_64
        path       (~/dotfiles/scripts/ ~/.local/bin/ ~/bin/ /run/wrappers/bin/ ~/.nix-profile/bin/ /etc/profiles/per-user/wedens/bin/ /nix/var/nix/profiles/default/bin/ /run/current-system/sw/bin/ /nix/store/qzs2ch8sbd7ddw7nk9xm0007pn6vinvj-emacs-git-20200321.0/libexec/emacs/27.0.90/x86_64-pc-linux-gnu/)
config  envfile    nil
        elc-files  0
        modules    (:completion (company +childframe) (ivy +prescient) :ui doom doom-dashboard hl-todo indent-guides modeline ophints (popup +defaults) vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold multiple-cursors snippets :emacs dired electric undo vc :checkers syntax :tools direnv (eval +overlay) lookup lsp magit :lang data emacs-lisp (haskell +dante) json javascript markdown nix org scala sh yaml :app rss :config (default +bindings +smartparens))
        packages   ((string-inflection :pin 1937db7513db570606ea8798916180b7dd75d3b1) (emojify :pin dfa3c6d060914c6082d6837da32df0c337330ee4) (pocket-reader :pin 86c51c65d97819e11b3df403beea424f30125d30) (alert :pin 7046393272686c7a1a9b3e7f7b1d825d2e5250a6) (org-msg :pin d8a571c720b2b7dec9115fd85b114ae46d4ac4b7) (mu4e-maildirs-extension :pin 4d2ece2226fa69a0e0bb23517a418145b92bd573) (mu4e-alert :pin 91f0657c5b245a9de57aa38391221fb5d141d9bd) (all-the-icons-ivy-rich :pin a9a4389c1930a5a071857b4d450eaecb21f4d6b9) (org-super-agenda :pin dd0d104c269fab9ebe5af7009bc1dd2a3a8f3c12) (org-randomnote :pin ea8cf4385970637efffff8f79e14576ba6d7ad13) (ox-gfm :pin 99f93011b069e02b37c9660b8fcb45dab086a07f) (counsel-tramp :pin 719b38ba2242cc1c6d1d79cab106c8c8b1afa775))
        unpin      (n/a)
        elpa       (n/a)
</pre></details>

**Comment by hlissner** [comment]
I cannot reproduce this. Are you sure Doom is up-to-date? Can you reproduce this [in vanilla Doom](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#testing-in-dooms-sandbox)? What text exactly does this occur on?

**Comment by AloisJanicek** [comment]
This happens to me too, since about 2 weeks ago. I could not figure out what exactly causing it and I can't reproduce it with vanilla doom even when I enable all the modules I have enabled in my config.

So definitely an issue with my personal configuration or with the package I installed additionally.

**Comment by wedens** [comment]
> Are you sure Doom is up-to-date?

I've updated doom to the last commit at the moment of writing this comment (07714a1). The problem is still there :(

> Can you reproduce this in vanilla Doom? 

No.

> What text exactly does this occur on?

Any text with spaces.


I think I've found the culprit - all-the-icons-ivy-rich.

```elisp
;; `add-transient-hook!' can't be used here as it'll
;; cause infinite recursion. the hook needs to be removed
;; before mode activation
(defun my/init-ivy-rich ()
  (remove-hook 'ivy-rich-mode-hook #'my/init-ivy-rich)
  (setq all-the-icons-ivy-rich-icon-size 0.85)
  (all-the-icons-ivy-rich-mode +1))
(add-hook 'ivy-rich-mode-hook #'my/init-ivy-rich)

;; counsel sets its own transformers, so we'll need to reset them
(after! counsel-projectile
  (all-the-icons-ivy-rich-mode +1))
```
I can't reproduce the problem with all-the-icons-ivy-rich without doom.

**Comment by wedens** [comment]
There is [this code](https://github.com/seagle0128/all-the-icons-ivy-rich/blob/master/all-the-icons-ivy-rich.el#L470) in all-the-icons-ivy-rich-mode. I suspect it might conflict with `+default--delete-backward-char-a` advice in doom.
```elisp
(defun all-the-icons-ivy-rich-align-icons ()
  "Set tab size to 1, to insert tabs as delimiters."
  (setq-local tab-width 1))

(add-hook 'minibuffer-setup-hook #'all-the-icons-ivy-rich-align-icons)
```

**Comment by hlissner** [comment]
As of 776663c this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
