### ISSUE TITLE
counsel--git-dir was removed from counsel

### ISSUE THREAD

**Issue by dsdshcym** [hlissner/doom-emacs#322]
Sorry for not using the default issue template here.

I'm new to doom-emacs and thanks a lot for this great framework!

`counsel--git-dir` got removed from `counsel` in https://github.com/abo-abo/swiper/commit/4f57b5a9eb3f9c971d48fb33dca54af43bd497ca

`ivy/autoload/ivy.el` is using this function, so it may need some updates. https://github.com/hlissner/doom-emacs/blob/master/modules/completion/ivy/autoload/ivy.el#L144

**Comment by hlissner** [comment]
Not a problem. And you're very welcome! The issue was fixed by #321, and is now in develop. I'll leave this open once it hits master.
