### ISSUE TITLE
Add GDScript Module

### ISSUE THREAD

**Issue by ofrank123** [hlissner/doom-emacs#3229]
**Describe the feature**
With the new GDScript language server support, and the now somewhat stable `emacs-gdscript-mode` package, I think it makes sense to combine these into a new lang module.

**Comment by hlissner** [comment]
I'm down for that, considering I use godot myself. That said, I'm swamped at the moment, so it'll be a while until I get to it. I'll keep you posted.

**Comment by NathanLovato** [comment]
If you're too busy, I'll give it a shot! I use doom emacs daily, the least I can do is contribute back.
