### ISSUE TITLE
pdf-tools-install (epdfinfo) blocks on Ubuntu waiting for [Y/n] to install packages

### ISSUE THREAD

**Issue by MarcKaufmann** [hlissner/doom-emacs#3244]
**What did you expect to happen?**

I expected pdf-tools to install properly and open the first pdf.

**What actually happened?**

It started to install the required packages (Ubuntu 18.04, apt or apt-get) and before installing them asked the usual question 

```
After this operation, 30,8 MB of additional disk space will be used.
Do you want to continue? [Y/n]
```

Then it just hangs there doing nothing, since it didn't respond to any keypresses, and I had to kill Emacs. 

My workaround was to take a screenshot of the packages needed and `apt-get install` them myself. Once all the packages were installed, it worked like a charm. 

**Additional details:**

The code for installing is at the link below and the comment states that `pdf-tools-install` is supposed to block - so my guess is that on Ubuntu the interactive mode happens after everything gets blocked, so maybe there has to be a configuration to make sure there is no question for `[Y/n]`, although I was able to type in my password.

https://github.com/hlissner/doom-emacs/blob/20cddb35656af1be92dff1ff88d1ae4322ff69dc/modules/tools/pdf/config.el#L67

**System information:**

Ubuntu 18.04, clearly related to that.

**Comment by hlissner** [comment]
This appears to be an upstream issue with pdf-tools' installer on Ubuntu [not suppressing confirmation prompts from apt-get](https://github.com/politza/pdf-tools/blob/master/server/autobuild#L320), and should be reported there. If the selected line can be changed to `PKGARGS="-y install"` then those confirmation prompts will be suppressed.

**Comment by MarcKaufmann** [comment]
Thanks a lot for the speedy response, I wasn't really sure where to report - it looks like this is already being taken care of upstream? Should I close this issue here myself or will it happen once the upstream issue is solved?

**Comment by hlissner** [comment]
Great! I'll keep this open until it's resolved upstream.

**Comment by TValentineUM** [comment]
For some reason when using `M-x pdf-tools-install` the prompt accepted the keyboard input and I was able to update. Whereas if I proceeded to update when prompted it would hang on the `Do you want to continue? [Y/n]` as described above.

I don't know any of the technical details, however i figured I might add this here for new Doom users to try.

**Comment by hlissner** [comment]
As of 7038c2e this issue should be fixed, locally. Let me know if that isn't the case and I'll reopen it. Sorry for the wait!
