### ISSUE TITLE
Terminal pane closing?

### ISSUE THREAD

**Issue by rphillips** [hlissner/doom-emacs#325]
### Observed behavior

I'm on the develop branch (73fa9ceab3471b161b1ebe5334520897407c27e0) and after opening the terminal (spc o t) then typing exit the split stays around. Trying to execute window commands within the defunct terminal elicits a `Current buffer has no process` error.

![screenshot from 2018-01-04 09-23-52](https://user-images.githubusercontent.com/1963/34570660-0deab87e-f132-11e7-9083-be06d868253b.png)

### Expected behavior

I would expect the terminal to close, or being able to execute standard window commands to close the split.

### Steps to reproduce

1. spc o t
2. type exit<cr>

### System information

<details>
<summary>Debug info
</summary>
DOOM Doctor
Running Emacs v25.3.1, commit 73fa9ceab3471b161b1ebe5334520897407c27e0

shell: /bin/zsh
Compiled with:
  XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GCONF GSETTINGS
  NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB
  TOOLKIT_SCROLL_BARS GTK3 X11 MODULES XWIDGETS
uname -a:
  Linux shrike 4.14.8-300.fc27.x86_64 #1 SMP Wed Dec 20 19:00:18 UTC
  2017 x86_64 x86_64 x86_64 GNU/Linux

Attempt to load DOOM: success! Loaded v2.0.9
Revision 73fa9ceab3471b161b1ebe5334520897407c27e0

----

test-emacs
test-windows
test-fonts
Found font material-design-icons.ttf
Found font weathericons.ttf
Found font octicons.ttf
Found font fontawesome.ttf
Found font file-icons.ttf
Found font all-the-icons.ttf
test-gnutls
test-tls
Validated https://elpa.gnu.org
Validated https://melpa.org
Successfully rejected https://self-signed.badssl.com
Successfully rejected https://wrong.host.badssl.com/
test-tar
Everything seems fine, happy Emacs’ing!
</details>

**Comment by hlissner** [comment]
I have pushed a number of updates to the popup system since that commit you referenced. Could you update and give it another try?

I am in the middle of a complete overhaul of the popup system, so I may be a day or two late addressing this specifically. With some luck, the new system will handle it right out of the box. I'll let you know.

**Comment by hlissner** [comment]
The overhaul of the popup system is now complete (in `develop`), which should resolve your issue. Give it a try and let me know.

**Comment by rphillips** [comment]
Tried the latest develop... `exit` will close the terminal, but the split hangs around and opens a file buffer.

![image](https://user-images.githubusercontent.com/1963/34655283-a943c53a-f3cc-11e7-97b0-99691aab5562.png)
