### ISSUE TITLE
Pages with Chinese is very stuttering in Org mode, with default configs

### ISSUE THREAD

**Issue by lewisliuyi** [hlissner/doom-emacs#3250]
I removed all personal configurations and reinstalled the latest doom, so my configuration is the default doom configuration. But as long as I opened an org file which was written in Chinese, swiping up and down is very stuck

**Comment by lewisliuyi** [comment]
The org file is not very big, about 300lines. Each line is truncated into 100. My system is Ubuntu 20.04.
I even re-installed the system, re-installed emacs and doom, and then used the default doom to open the org file containing Chinese, still stuck

**Comment by lewisliuyi** [comment]
But if an org file with only English, it is OK and everything works well

**Comment by HakunanMatatat** [comment]
I have the same question in win10.

**Comment by OceanS2000** [comment]
It might be a fontset issue. I used to have the same problem, and manually setting  CJK font as a [reddit thread suggests](https://www.reddit.com/r/emacs/comments/84spld/emacs_not_playing_well_with_chinese_characters/) seems to work for me:

```elisp
(dolist (charset '(kana han cjk-misc bopomofo))
  (set-fontset-font (frame-parameter nil 'font)
    charset (font-spec :family "<CJK font name>" :size 14)))
```

**Comment by HakunanMatatat** [comment]
Chinese font size is't changed when I scale the font in DOOM.Some CJK fonts take no effect that the Chinese is still stuttering.

**Comment by lewisliuyi** [comment]
> Chinese font size is't changed when I scale the font in DOOM.Some CJK fonts take no effect that the Chinese is still stuttering.

Thank you for you suggestion. But it dosen't seem to be working for me. The font I used in DOOM is Ubuntu Mono. I open the same .org file in centaul emacs with “Ubuntu Mono”, everything works well. It seems something wrong with DOOM and it's hard to detect. But DOOM is still great so I suffer from page jams to continue using DOOM.

**Comment by HakunanMatatat** [comment]
"SimSun" font works.I think it may be related with the system Chinese font style setting.

**Comment by lewisliuyi** [comment]
I've tried several fonts, and now DOOM is still a bit jarring, but it's much better than before. 

Thanks to the author of DOOM because it is really great. I hope I can become a loyal DOOM user.
