### ISSUE TITLE
Some modules overrides eglot lookup handlers

### ISSUE THREAD

**Issue by sei40kr** [hlissner/doom-emacs#3251]
**What actually happened?**
Some modules overrides eglot lookup handlers. eglot doesn't have standalone `:definition`, `:references` lookup handlers and set xref backend instead. But in some modules, there're more prioritized lookup handlers.

**Confirmed by me**

* Go

**Not confirmed but needs to confirm**

* Clojure
* Elixir
* JavaScript (sets xref backend)
* PureScript
* Ruby (support lsp-mode, but seems eglot is not supported)

**Comment by johnhamelink** [comment]
Could you provide some instructions on how to detect this? I can help with Javascript and Elixir if that's useful :)

**Comment by sei40kr** [comment]
Perhaps 6678f3833 fixes this issue, I'll look into it.

**Comment by hlissner** [comment]
#5329 was written to fix exactly this issue, so I'll consider this resolved until further notice.
