### ISSUE TITLE
Bug in `+javascript/skewer-this-buffer` ?

### ISSUE THREAD

**Issue by teehemkay** [hlissner/doom-emacs#3252]
There seems to be a bug in the `+javascript/skewer-this-buffer` where it generates an error when trying to skewer a buffer

`if: Symbol’s value as variable is void: skewer-css-mode`

Reading the source code of the function, my guess is that the culprit is in this line of code

https://github.com/hlissner/doom-emacs/blob/200fd52b617c393ca9c98a456fb5ee1bac3faa63/modules/lang/javascript/autoload.el#L63

Shouldn't this be an `or` rather than an `and`?

**Comment by hlissner** [comment]
Good catch. With 2407db0 this should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
