### ISSUE TITLE
Question: In the company-backend def-settings, why line 13?

### ISSUE THREAD

**Issue by UndeadKernel** [hlissner/doom-emacs#326]
Hi @hlissner,

This is a question rather than an "issue".
I'm working on creating a LaTeX module that has many more additions than the one currently available. I stumbled upon an issue when configuring `company-auctex` using something like:
```
(set! :company-backend 'LaTeX-mode 'company-auctex-labels)
```
The company backend will not be set correctly; however, the function created by `set!` will correctly be hooked to `LaTeX-mode-hook`. Now (**brace for horrible truth**) AUCTeX has made the dubious decision of reporting that the major mode is `latex-mode` even though the actual major mode used is `LaTeX-mode`. That is, the variable `major-mode` will be set to `latex-mode`.

There is a problem in [line 13 of modules/completion/company/config.el](https://github.com/hlissner/doom-emacs/blob/master/modules/completion/company/config.el#L13): it checks that the variable `major-mode` and the registered mode are the same. In the case of the call:
```
(set! :company-backend 'LaTeX-mode 'company-auctex-labels)
```
they will not be the same. Specifically, major mode will be `latex-mode` while the registered mode will be `LaTeX-mode`. For this reason, the company backend for AUCTeX cannot be set using `set!`.

The questions is (yes, there was a question, you see) is: Is line 13 of the company/config.el file really needed? If yes, how do you think we could solve this issue?

P.S.: I'll be AFC (away from computer) during the weekend and will probably not have time to respond.

**Comment by hlissner** [comment]
Yikes, what a mess!

> Is line 13 of the company/config.el file really needed?

That check prevents backends from bleeding into derivative modes. For instance, php-mode is derived from c-mode. I don't want my C backends active in PHP. Of course, I also assumed that major-modes would always have matching hooks! Haha.

Considering this is _very_ specific to auctex, it would be best to simply not use `:company-backend`. I will replace it with:

```emacs-lisp
(add-hook! LaTeX-mode
  (make-variable-buffer-local 'company-backends)
  (company-auctex-init))  ; fortunately provided by `company-auctex'
```

I'll leave this open until it's in `master`, and will let you know once it's in `develop`.

**Comment by UndeadKernel** [comment]
I'm currently working on improving the latex module and adding some useful
things to it. If you'd like, I can make the changes that you'd implement
and include them in what I'm working on.

I plan to send you a pull request replacing the current latex module this
Monday. I'm taking into account the things that are already there and using
them as defaults.

I've taken a look at some of the TODOs that you have and plan to integrate
those related to latex (like previe-latex).

Let me knew if this would suite you.

**Comment by hlissner** [comment]
Yes please, certainly! It has been a while since I've worked with Latex outside of org-mode, so lang/latex is quite neglected. It sure could use an update! Even better with those latex plugins!

**Comment by hlissner** [comment]
Just an fyi, I've just pushed the proposed patch into `develop` along with a minor refactor to the lang/latex (just moved them around), so I'll consider the original issue resolved. I'll leave this open until it (and/or your proposed changes) hit `master`.
