### ISSUE TITLE
Eglot fails with (void-function project-root) (when unpinned)

### ISSUE THREAD

**Issue by gagbo** [hlissner/doom-emacs#3269]
Short story : using the pinned version of eglot *should* prevent the issue

The backtrace finishes with `(void-function project-root)`, and this issue may come from 2 different problems, which were uncovered by a recent eglot change that used a new version of `project.el` with a breaking API change.

Trying to find out the correct solution (and more details are provided also) in those upstream issues : 
joaotavora/eglot#492
raxod502/straight.el#531

**Comment by gagbo** [comment]
For the time being, the fix is (*If using Emacs 27+*) to use the built-in project.el package which has a correct version theoretically :

```lisp
(package! project :recipe (:local-repo nil))
``` in `packages.el`

**Comment by OwenPriceSkelly** [comment]
Just wanted to chime in with a workaround if you're not using 27+, `project-roots` is defined even though `project-root` isn't, so you can just define the function yourself like 
``` emacs-lisp
(defun project-root (project)
    (car (project-roots project)))
```
