### ISSUE TITLE
Make compile emits error. 

### ISSUE THREAD

**Issue by zeronone** [hlissner/doom-emacs#327]
### Observed behavior

Make install gives the error `Recursive 'require' for feature 'org'`. 

`M-x org-version` gives `9.1.6-elpa`

### System information

I have also added the `("org" . "https://orgmode.org/elpa/")` package-archive.

<details>
<summary>Click to expand</summary>

```
DOOM Doctor
Running Emacs v25.3.2, commit d465c6199249fb6e6e8b49474a04f94e7d5e3cdd

shell: /bin/zsh
Compiled with:
  XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS
  NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB
  TOOLKIT_SCROLL_BARS GTK3 X11 MODULES
uname -a:
  Linux zeronone-ubuntu 4.10.0-42-generic #46~16.04.1-Ubuntu SMP Mon Dec
  4 15:57:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Attempt to load DOOM: success! Loaded v2.0.9
Revision d465c6199249fb6e6e8b49474a04f94e7d5e3cdd

----

test-emacs
test-windows
test-fonts
Found font material-design-icons.ttf
Found font weathericons.ttf
Found font octicons.ttf
Found font fontawesome.ttf
Found font file-icons.ttf
Found font all-the-icons.ttf
test-gnutls
test-tls
Validated https://elpa.gnu.org
Validated https://melpa.org
Successfully rejected https://self-signed.badssl.com
Successfully rejected https://wrong.host.badssl.com/
test-tar
Everything seems fine, happy Emacs’ing!

```
</details>

**Comment by exrok** [comment]
Having Same Issue also on Arch.

**Comment by zeronone** [comment]
@hlissner I commented it out, but it didn't fix it.

**Comment by exrok** [comment]
Commenting out the line didn't seem to help. I tried to do a fresh install of doom and the following happens during the make install, perhaps related 

```
Installing ox-reveal
  FATAL ERROR: (error) Package ‘org-20150330’ is unavailable
Installing org-tree-slide
✓ DONE
Installing centered-window-mode
✓ DONE
Installing ox-pandoc
  FATAL ERROR: (error) Package ‘org-8.2’ is unavailable
Installing ob-translate
  FATAL ERROR: (error) Package ‘org-8’ is unavailable
```

**Comment by zeronone** [comment]
@exrok I added the `("org" . "http://orgmode.org/elpa/")` to package-archives to fix that one.

**Comment by exrok** [comment]
@zeronone  Thanks that fixed that problem. However the orignal problem still stands when compiling.

**Comment by hlissner** [comment]
Odd. Neither of these fixes should be necessary. I think the underlying issue is that Doom is trying to install all these packages that _depend_ on org, _before installing `org-plus-contrib`_, which includes org 9.1.4. I will look into this.

**Comment by hlissner** [comment]
Hey. I hadn't realized orgmode.com got https support. If you add `("org" . "https://orgmode.org/elpa/")` instead, does this resolve your issues? https support is pretty much the only reason Doom doesn't use it.

**Comment by hlissner** [comment]
I've now added it in `develop`. I'll keep this open until it is in `master`.

**Comment by zeronone** [comment]
@hlissner @exrok The problem still persists even with applying https://github.com/hlissner/doom-emacs/commit/2598d48bba46435249402693edacfe65f22bdb2f and https://github.com/hlissner/doom-emacs/commit/a29bc54c63ba87f147eff1a42564d85fc837e58c 

I see that both `org` (dependency of `ox-reveal` and others ?) and `org-plus-contrib` is installed. 

I tried installing `org-plus-contrib :files ("contrib/lisp/*.el")` and also changing the order of `org` in `init.el` (first element after `:lang`); but the same error appeared in other places. 

Finally, I just added `org-plus-contrib` to `doom-core-packages` and it fixed the problem. 
```
diff --git a/core/core-packages.el b/core/core-packages.el
index d486c5f..6ae55ea 100644
--- a/core/core-packages.el
+++ b/core/core-packages.el
@@ -63,7 +63,7 @@ package's name as a symbol, and whose CDR is the plist supplied to its
 `package!' declaration. Set by `doom-initialize-packages'.")
 
 (defvar doom-core-packages
-  '(persistent-soft use-package quelpa async)
+  '(persistent-soft use-package quelpa async org-plus-contrib)
   "A list of packages that must be installed (and will be auto-installed if
 missing) and shouldn't be deleted.")
 
diff --git a/modules/lang/org/packages.el b/modules/lang/org/packages.el
index d6a7eca..2d523c1 100644
--- a/modules/lang/org/packages.el
+++ b/modules/lang/org/packages.el
@@ -2,7 +2,7 @@
 ;;; lang/org/packages.el
 
 ;; Installs a cutting-edge version of org-mode
-(package! org-plus-contrib)
+;; (package! org-plus-contrib)
 
 (package! org-bullets :recipe (:fetcher github :repo "hlissner/org-bullets"))
 (package! toc-org)
```

**Comment by zeronone** [comment]
Oh I am sorry, it didn't resolve the problem. I was mistaken.

**Comment by exrok** [comment]
@zeronone  Your patch now has fixed the problem completely, `make compile` runs fine now. However, I think the patch breaks modularity since doom's org features are supposed to be toggleable, althougth I think org-mode is pretty core to Doom. 

Before the patch if I ran `make compile-lang/org` it worked without the errors.  Also, before the patch, when running `make compile` that first weird error was `Cannot load toc-org: (void-function org-link-set-parameters)` which occoured before the reccursive require errors presumably since at that point it was using the wrong version of org-mode. Your patch enforces the correct version to load early on avoiding this problem, I think.

**Comment by hlissner** [comment]
@zeronone Could you try something else for me?

If you move that `when-let*` block back to `lang/org/config.el` and wrap it in `(eval-and-compile (when-let* ...))`, does that solve your issue?

**Comment by hlissner** [comment]
Just pushed https://github.com/hlissner/doom-emacs/commit/bd1a83ec690da3191915b1b3719296870908e683 with that block wrapped in an `eval-and-compile` block (and put the wrong bug number in the commit, derp!). This _should_ resolve these issues.

**Comment by zeronone** [comment]
@hlissner It didn't resolve the issue for me. For reference I get the following error.

<details>
  <summary>Compile log</summary>

⚠ Ignored modules/lang/clojure/packages.el
Cannot load clojure-mode: (void-function org-link-set-parameters)
Cannot load clj-refactor: (error "Recursive ‘require’ for feature ‘org’")
Cannot load cider: (error "Recursive ‘require’ for feature ‘org’")
✓ Compiled modules/lang/clojure/config.el

There were breaking errors.

Recursive ‘require’ for feature ‘org’

Reverting changes...
</details>

**Comment by hlissner** [comment]
Ah, silly me. I forgot there may be other packages that try to load org before lang/org is loaded (like cider).

Alright, new strategy. I've made it so `load-path` is modified _much_ earlier in the loading process. Let me know if that fixes the problem.

**Comment by zeronone** [comment]
@hlissner I did a fresh install from `develop` branch, but the issue still persists. I still get error in `clojure` as before.

**Comment by hlissner** [comment]
Phew! Had me worried for a bit. Anyhow, I pushed https://github.com/hlissner/doom-emacs/commit/c0680e6fa30ad80fb91be520f20e98d56076e5a3 a while ago, which should further improve Doom's reliability with org. I'll consider this fixed for now, and will leave this open until it hits `master`.

**Comment by igorvolnyi** [comment]
Make gives:
Looking for packages to install...
5 packages will be installed:

+ ob-mongo (ELPA)
+ ob-redis (ELPA)
+ ob-translate (ELPA)
+ ox-pandoc (ELPA)
+ ox-reveal (ELPA)

Proceed? (y or n) y
Refreshing package archives
Importing package-keyring.gpg...
Importing package-keyring.gpg...done
Contacting host: elpa.gnu.org:443
Contacting host: elpa.gnu.org:443
Contacting host: melpa.org:443
Package refresh done
Installing ox-reveal
  FATAL ERROR: (error) Package ‘org-20150330’ is unavailable
Installing ox-pandoc
  FATAL ERROR: (error) Package ‘org-8.2’ is unavailable
Installing ob-translate
  FATAL ERROR: (error) Package ‘org-8’ is unavailable
Installing ob-redis
  FATAL ERROR: (error) Package ‘org-8’ is unavailable
Installing ob-mongo
  FATAL ERROR: (error) Package ‘org-8’ is unavailable
Finished!

**Comment by apierz** [comment]
I'm getting the same error:

Importing package-keyring.gpg...
Importing package-keyring.gpg...done
Contacting host: elpa.gnu.org:443
Contacting host: elpa.gnu.org:443
Contacting host: melpa.org:443
Package refresh done
Installing ox-reveal
  FATAL ERROR: (error) Package ‘org-20150330’ is unavailable
Installing centered-window-mode
  FATAL ERROR: (error) Package ‘centered-window-mode-’ is unavailable
Installing ox-pandoc
  FATAL ERROR: (error) Package ‘org-8.2’ is unavailable
Installing ob-translate
  FATAL ERROR: (error) Package ‘org-8’ is unavailable
Installing ob-redis
  FATAL ERROR: (error) Package ‘org-8’ is unavailable
Installing ob-mongo
  FATAL ERROR: (error) Package ‘org-8’ is unavailable
Installing help-fns+
  FATAL ERROR: (error) Package ‘help-fns+-’ is unavailable
Finished!
Reloading active Emacs session...

**Comment by hlissner** [comment]
These issues have been fixed in `develop`. The 2.1 release is this weekend, so they will be in `master` soon.

**Comment by hlissner** [comment]
Well, it certainly didn't come out that weekend! Haha.

It'll be up this weekend. 2.1 is already on `develop` as of two days ago, minus the new documentation. That's all there is left to do. Doom's more adventurous users are putting it through its rounds now.
