### ISSUE TITLE
use-package :load-path fails to parse package

### ISSUE THREAD

**Issue by LoganBarnett** [hlissner/doom-emacs#3272]
**What did you expect to happen?**
`use-package` in conjunction with its `load-path` argument should load up my local package.

**What actually happened?**
`use-package` fails with the following error:
```
Error (use-package): Failed to parse package piper: Symbol’s value as variable is void: args
```

**Additional details:**
- [File that uses use-package and breaks](https://github.com/LoganBarnett/dotfiles/blob/master/org/piper.org)
- I think commit 0787eae27488104c8f6c5f437129fd3be05c0a9b recently made (~2hrs ago) introduced the issue. I dumbly tried to use `arg` instead of `args` and got an argument mismatch error, but I didn't dig in any further than that (apologies). Commenting out the function works for my purposes since my path is absolute.

<details><pre>
Debugger entered--Lisp error: (void-variable args)
  (funcall orig-fn args)
  (if (and (stringp arg) (not (file-name-absolute-p arg))) (let ((user-emacs-directory (dir!))) (funcall orig-fn args)) (funcall orig-fn args))
  doom--resolve-load-path-from-containg-file-a(#f(compiled-function (label arg &optional recursed) "Normalize a list of filesystem paths." #<bytecode 0x41079fc3>) ":load-path" "~/dev/emacs-piper/")
  apply(doom--resolve-load-path-from-containg-file-a #f(compiled-function (label arg &optional recursed) "Normalize a list of filesystem paths." #<bytecode 0x41079fc3>) (":load-path" "~/dev/emacs-piper/"))
  use-package-normalize-paths(":load-path" "~/dev/emacs-piper/")
  use-package-as-one(":load-path" ("~/dev/emacs-piper/") use-package-normalize-paths)
  use-package-normalize/:load-path(piper :load-path ("~/dev/emacs-piper/"))
  use-package-normalize-plist(piper (:load-path "~/dev/emacs-piper/" :config (on-doom (map! :leader (:desc "piper" :prefix "o |" :desc "other-directory" "d" (quote piper-other) :desc "piper-locally" "l" (quote piper) :desc "piper-remotely" "r" (quote piper-remote) :desc "piper-ui" "|" (quote piper-ui))) (evil-global-set-key (quote normal) (kbd "SPC |") (quote ("piper-ui" . piper-user-interface)))) (on-spacemacs (spacemacs/declare-prefix "o |" "piper") (spacemacs/set-leader-keys "|" (quote ("piper-ui" . piper-user-interface)) "o | |" (quote ("piper-locally" . piper)) "o | d" (quote ("other-directory" . piper-other)) "o | r" (quote ("piper-remotely" . piper-remote))))) nil use-package-merge-keys)
  use-package-normalize-keywords(piper (:load-path "~/dev/emacs-piper/" :config (on-doom (map! :leader (:desc "piper" :prefix "o |" :desc "other-directory" "d" (quote piper-other) :desc "piper-locally" "l" (quote piper) :desc "piper-remotely" "r" (quote piper-remote) :desc "piper-ui" "|" (quote piper-ui))) (evil-global-set-key (quote normal) (kbd "SPC |") (quote ("piper-ui" . piper-user-interface)))) (on-spacemacs (spacemacs/declare-prefix "o |" "piper") (spacemacs/set-leader-keys "|" (quote ("piper-ui" . piper-user-interface)) "o | |" (quote ("piper-locally" . piper)) "o | d" (quote ("other-directory" . piper-other)) "o | r" (quote ("piper-remotely" . piper-remote))))))
  #f(compiled-function (name &rest args) "Declare an Emacs package by specifying a group of configuration options.\n\nFor full documentation, please see the README file that came with\nthis file.  Usage:\n\n  (use-package package-name\n     [:keyword [option]]...)\n\n:init            Code to run before PACKAGE-NAME has been loaded.\n:config          Code to run after PACKAGE-NAME has been loaded.  Note that\n                 if loading is deferred for any reason, this code does not\n                 execute until the lazy load has occurred.\n:preface         Code to be run before everything except `:disabled'; this\n                 can be used to define functions for use in `:if', or that\n                 should be seen by the byte-compiler.\n\n:mode            Form to be added to `auto-mode-alist'.\n:magic           Form to be added to `magic-mode-alist'.\n:magic-fallback  Form to be added to `magic-fallback-mode-alist'.\n:interpreter     Form to be added to `interpreter-mode-alist'.\n\n:commands        Define autoloads for commands that will be defined by the\n                 package.  This is useful if the package is being lazily\n                 loaded, and you wish to conditionally call functions in your\n                 `:init' block that are defined in the package.\n:hook            Specify hook(s) to attach this package to.\n\n:bind            Bind keys, and define autoloads for the bound commands.\n:bind*           Bind keys, and define autoloads for the bound commands,\n                 *overriding all minor mode bindings*.\n:bind-keymap     Bind a key prefix to an auto-loaded keymap defined in the\n                 package.  This is like `:bind', but for keymaps.\n:bind-keymap*    Like `:bind-keymap', but overrides all minor mode bindings\n\n:defer           Defer loading of a package -- this is implied when using\n                 `:commands', `:bind', `:bind*', `:mode', `:magic', `:hook',\n                 `:magic-fallback', or `:interpreter'.  This can be an integer,\n                 to force loading after N seconds of idle time, if the package\n                 has not already been loaded.\n:after           Delay the use-package declaration until after the named modules\n                 have loaded. Once load, it will be as though the use-package\n                 declaration (without `:after') had been seen at that moment.\n:demand          Prevent the automatic deferred loading introduced by constructs\n                 such as `:bind' (see `:defer' for the complete list).\n\n:if EXPR         Initialize and load only if EXPR evaluates to a non-nil value.\n:disabled        The package is ignored completely if this keyword is present.\n:defines         Declare certain variables to silence the byte-compiler.\n:functions       Declare certain functions to silence the byte-compiler.\n:load-path       Add to the `load-path' before attempting to load the package.\n:diminish        Support for diminish.el (if installed).\n:delight         Support for delight.el (if installed).\n:custom          Call `customize-set-variable' with each variable definition.\n:custom-face     Call `customize-set-faces' with each face definition.\n:ensure          Loads the package using package.el if necessary.\n:pin             Pin the package to an archive." #<bytecode 0x41083467>)(piper :load-path "~/dev/emacs-piper/" :config (on-doom (map! :leader (:desc "piper" :prefix "o |" :desc "other-directory" "d" (quote piper-other) :desc "piper-locally" "l" (quote piper) :desc "piper-remotely" "r" (quote piper-remote) :desc "piper-ui" "|" (quote piper-ui))) (evil-global-set-key (quote normal) (kbd "SPC |") (quote ("piper-ui" . piper-user-interface)))) (on-spacemacs (spacemacs/declare-prefix "o |" "piper") (spacemacs/set-leader-keys "|" (quote ("piper-ui" . piper-user-interface)) "o | |" (quote ("piper-locally" . piper)) "o | d" (quote ("other-directory" . piper-other)) "o | r" (quote ("piper-remotely" . piper-remote)))))
  macroexpand((use-package piper :load-path "~/dev/emacs-piper/" :config (on-doom (map! :leader (:desc "piper" :prefix "o |" :desc "other-directory" "d" (quote piper-other) :desc "piper-locally" "l" (quote piper) :desc "piper-remotely" "r" (quote piper-remote) :desc "piper-ui" "|" (quote piper-ui))) (evil-global-set-key (quote normal) (kbd "SPC |") (quote ("piper-ui" . piper-user-interface)))) (on-spacemacs (spacemacs/declare-prefix "o |" "piper") (spacemacs/set-leader-keys "|" (quote ("piper-ui" . piper-user-interface)) "o | |" (quote ("piper-locally" . piper)) "o | d" (quote ("other-directory" . piper-other)) "o | r" (quote ("piper-remotely" . piper-remote))))))
  internal-macroexpand-for-load((use-package piper :load-path "~/dev/emacs-piper/" :config (on-doom (map! :leader (:desc "piper" :prefix "o |" :desc "other-directory" "d" (quote piper-other) :desc "piper-locally" "l" (quote piper) :desc "piper-remotely" "r" (quote piper-remote) :desc "piper-ui" "|" (quote piper-ui))) (evil-global-set-key (quote normal) (kbd "SPC |") (quote ("piper-ui" . piper-user-interface)))) (on-spacemacs (spacemacs/declare-prefix "o |" "piper") (spacemacs/set-leader-keys "|" (quote ("piper-ui" . piper-user-interface)) "o | |" (quote ("piper-locally" . piper)) "o | d" (quote ("other-directory" . piper-other)) "o | r" (quote ("piper-remotely" . piper-remote))))) nil)
  eval-buffer(#<buffer  *load*-529953> nil "/Users/logan/dev/dotfiles/org/piper.el" nil t)  ; Reading at buffer position 952
  load-with-code-conversion("/Users/logan/dev/dotfiles/org/piper.el" "/Users/logan/dev/dotfiles/org/piper.el" nil nil)
  #<subr load>("/Users/logan/dev/dotfiles/org/piper.el" nil nil t nil)
  apply(#<subr load> ("/Users/logan/dev/dotfiles/org/piper.el" nil nil t))
  load("/Users/logan/dev/dotfiles/org/piper.el" nil nil t)
  load-file("/Users/logan/dev/dotfiles/org/piper.el")
  org-babel-load-file("/Users/logan/dev/dotfiles/org/piper.org")
  init-org-file("piper.org")
  my/init()
  eval-buffer(#<buffer  *load*-403821> nil "/Users/logan/.doom.d/config.el" nil t)  ; Reading at buffer position 2483
  load-with-code-conversion("/Users/logan/.doom.d/config.el" "/Users/logan/.doom.d/config.el" t t)
  load("/Users/logan/.doom.d/config" t nomessage)
  (let (file-name-handler-alist) (load (expand-file-name "config" doom-private-dir) t (quote nomessage)))
  (condition-case e (let (file-name-handler-alist) (load (expand-file-name "config" doom-private-dir) t (quote nomessage))) ((debug doom-error) (signal (car e) (cdr e))) ((debug error) (doom--handle-load-error e (expand-file-name "config" doom-private-dir) doom-private-dir)))
  (if no-config-p nil (maphash (doom-module-loader doom-module-config-file) doom-modules) (run-hook-wrapped (quote doom-init-modules-hook) (function doom-try-run-hook)) (condition-case e (let (file-name-handler-alist) (load (expand-file-name "config" doom-private-dir) t (quote nomessage))) ((debug doom-error) (signal (car e) (cdr e))) ((debug error) (doom--handle-load-error e (expand-file-name "config" doom-private-dir) doom-private-dir))) (load custom-file (quote noerror) (not doom-debug-mode)))
  (progn (if doom-debug-p (progn (let ((inhibit-message (active-minibuffer-window))) (message #("DOOM Initializing user config" 0 5 (face font-lock-comment-face)))))) (maphash (doom-module-loader doom-module-init-file) doom-modules) (run-hook-wrapped (quote doom-before-init-modules-hook) (function doom-try-run-hook)) (if no-config-p nil (maphash (doom-module-loader doom-module-config-file) doom-modules) (run-hook-wrapped (quote doom-init-modules-hook) (function doom-try-run-hook)) (condition-case e (let (file-name-handler-alist) (load (expand-file-name "config" doom-private-dir) t (quote nomessage))) ((debug doom-error) (signal (car e) (cdr e))) ((debug error) (doom--handle-load-error e (expand-file-name "config" doom-private-dir) doom-private-dir))) (load custom-file (quote noerror) (not doom-debug-mode))))
  (if init-p (progn (if doom-debug-p (progn (let ((inhibit-message (active-minibuffer-window))) (message #("DOOM Initializing user config" 0 5 (face font-lock-comment-face)))))) (maphash (doom-module-loader doom-module-init-file) doom-modules) (run-hook-wrapped (quote doom-before-init-modules-hook) (function doom-try-run-hook)) (if no-config-p nil (maphash (doom-module-loader doom-module-config-file) doom-modules) (run-hook-wrapped (quote doom-init-modules-hook) (function doom-try-run-hook)) (condition-case e (let (file-name-handler-alist) (load (expand-file-name "config" doom-private-dir) t (quote nomessage))) ((debug doom-error) (signal (car e) (cdr e))) ((debug error) (doom--handle-load-error e (expand-file-name "config" doom-private-dir) doom-private-dir))) (load custom-file (quote noerror) (not doom-debug-mode)))) nil)
  (let* ((init-p (and t (condition-case e (let (file-name-handler-alist) (load (expand-file-name doom-module-init-file doom-private-dir) t (quote nomessage))) ((debug doom-error) (signal (car e) (cdr e))) ((debug error) (doom--handle-load-error e (expand-file-name doom-module-init-file doom-private-dir) doom-private-dir)))))) (if init-p (progn (if doom-debug-p (progn (let ((inhibit-message ...)) (message #("DOOM Initializing user config" 0 5 (face font-lock-comment-face)))))) (maphash (doom-module-loader doom-module-init-file) doom-modules) (run-hook-wrapped (quote doom-before-init-modules-hook) (function doom-try-run-hook)) (if no-config-p nil (maphash (doom-module-loader doom-module-config-file) doom-modules) (run-hook-wrapped (quote doom-init-modules-hook) (function doom-try-run-hook)) (condition-case e (let (file-name-handler-alist) (load (expand-file-name "config" doom-private-dir) t (quote nomessage))) ((debug doom-error) (signal (car e) (cdr e))) ((debug error) (doom--handle-load-error e (expand-file-name "config" doom-private-dir) doom-private-dir))) (load custom-file (quote noerror) (not doom-debug-mode)))) nil))
  (progn (setq doom-init-modules-p t) (if no-config-p nil (if doom-debug-p (progn (let ((inhibit-message (active-minibuffer-window))) (message #("DOOM Initializing core modules" 0 5 (face font-lock-comment-face)))))) (doom-initialize-core-modules)) (let* ((init-p (and t (condition-case e (let (file-name-handler-alist) (load ... t ...)) ((debug doom-error) (signal ... ...)) ((debug error) (doom--handle-load-error e ... doom-private-dir)))))) (if init-p (progn (if doom-debug-p (progn (let (...) (message #("DOOM Initializing user config" 0 5 (face font-lock-comment-face)))))) (maphash (doom-module-loader doom-module-init-file) doom-modules) (run-hook-wrapped (quote doom-before-init-modules-hook) (function doom-try-run-hook)) (if no-config-p nil (maphash (doom-module-loader doom-module-config-file) doom-modules) (run-hook-wrapped (quote doom-init-modules-hook) (function doom-try-run-hook)) (condition-case e (let (file-name-handler-alist) (load ... t ...)) ((debug doom-error) (signal ... ...)) ((debug error) (doom--handle-load-error e ... doom-private-dir))) (load custom-file (quote noerror) (not doom-debug-mode)))) nil)))
  (if (or force-p (not doom-init-modules-p)) (progn (setq doom-init-modules-p t) (if no-config-p nil (if doom-debug-p (progn (let ((inhibit-message ...)) (message #("DOOM Initializing core modules" 0 5 (face font-lock-comment-face)))))) (doom-initialize-core-modules)) (let* ((init-p (and t (condition-case e (let ... ...) (... ...) (... ...))))) (if init-p (progn (if doom-debug-p (progn (let ... ...))) (maphash (doom-module-loader doom-module-init-file) doom-modules) (run-hook-wrapped (quote doom-before-init-modules-hook) (function doom-try-run-hook)) (if no-config-p nil (maphash (doom-module-loader doom-module-config-file) doom-modules) (run-hook-wrapped (quote doom-init-modules-hook) (function doom-try-run-hook)) (condition-case e (let ... ...) (... ...) (... ...)) (load custom-file (quote noerror) (not doom-debug-mode)))) nil))))
  doom-initialize-modules(nil)
  (progn (setq doom-init-p t) (if doom-debug-p (progn (let ((inhibit-message (active-minibuffer-window))) (message #("DOOM Initializing Doom" 0 5 (face font-lock-comment-face)))))) (setq-default exec-path doom--initial-exec-path load-path doom--initial-load-path process-environment doom--initial-process-environment) (condition-case e (load (string-remove-suffix ".el" doom-autoload-file) nil (quote nomessage)) (file-missing (signal (quote doom-error) (list "Doom is in an incomplete state" "run 'bin/doom sync' on the command line to repair it")))) (if (or (display-graphic-p) (daemonp)) (doom-load-envvars-file doom-env-file (quote noerror))) (require (quote core-modules)) (autoload (quote doom-initialize-packages) "core-packages") (autoload (quote doom-initialize-core-packages) "core-packages") (eval-after-load (quote package) (function (lambda nil (require (quote core-packages))))) (eval-after-load (quote straight) (function (lambda nil (doom-initialize-packages)))) (add-hook (quote window-setup-hook) (function (lambda (&rest _) (add-hook (quote hack-local-variables-hook) (function doom-run-local-var-hooks-h)) (add-hook (quote after-change-major-mode-hook) (function doom-run-local-var-hooks-maybe-h) (quote append)) (add-hook (quote doom-first-input-hook) (function gcmh-mode)) (let ((fn (intern ...))) (fset fn (function (lambda ... ... ...))) (put (quote doom-first-input-hook) (quote permanent-local) t) (let ((--dolist-tail-- ...)) (while --dolist-tail-- (let ... ... ...)))) (let ((fn (intern ...))) (fset fn (function (lambda ... ... ...))) (put (quote doom-first-file-hook) (quote permanent-local) t) (let ((--dolist-tail-- ...)) (while --dolist-tail-- (let ... ... ...)))) (let ((fn (intern ...))) (fset fn (function (lambda ... ... ...))) (put (quote doom-first-buffer-hook) (quote permanent-local) t) (let ((--dolist-tail-- ...)) (while --dolist-tail-- (let ... ... ...)))))) nil nil) (add-hook (quote emacs-startup-hook) (function doom-load-packages-incrementally-h)) (add-hook (quote window-setup-hook) (function doom-display-benchmark-h) (quote append)) (if doom-debug-p (doom-debug-mode 1)) (doom-initialize-modules force-p))
  (if (or force-p (not doom-init-p)) (progn (setq doom-init-p t) (if doom-debug-p (progn (let ((inhibit-message (active-minibuffer-window))) (message #("DOOM Initializing Doom" 0 5 (face font-lock-comment-face)))))) (setq-default exec-path doom--initial-exec-path load-path doom--initial-load-path process-environment doom--initial-process-environment) (condition-case e (load (string-remove-suffix ".el" doom-autoload-file) nil (quote nomessage)) (file-missing (signal (quote doom-error) (list "Doom is in an incomplete state" "run 'bin/doom sync' on the command line to repair it")))) (if (or (display-graphic-p) (daemonp)) (doom-load-envvars-file doom-env-file (quote noerror))) (require (quote core-modules)) (autoload (quote doom-initialize-packages) "core-packages") (autoload (quote doom-initialize-core-packages) "core-packages") (eval-after-load (quote package) (function (lambda nil (require (quote core-packages))))) (eval-after-load (quote straight) (function (lambda nil (doom-initialize-packages)))) (add-hook (quote window-setup-hook) (function (lambda (&rest _) (add-hook (quote hack-local-variables-hook) (function doom-run-local-var-hooks-h)) (add-hook (quote after-change-major-mode-hook) (function doom-run-local-var-hooks-maybe-h) (quote append)) (add-hook (quote doom-first-input-hook) (function gcmh-mode)) (let ((fn ...)) (fset fn (function ...)) (put (quote doom-first-input-hook) (quote permanent-local) t) (let (...) (while --dolist-tail-- ...))) (let ((fn ...)) (fset fn (function ...)) (put (quote doom-first-file-hook) (quote permanent-local) t) (let (...) (while --dolist-tail-- ...))) (let ((fn ...)) (fset fn (function ...)) (put (quote doom-first-buffer-hook) (quote permanent-local) t) (let (...) (while --dolist-tail-- ...))))) nil nil) (add-hook (quote emacs-startup-hook) (function doom-load-packages-incrementally-h)) (add-hook (quote window-setup-hook) (function doom-display-benchmark-h) (quote append)) (if doom-debug-p (doom-debug-mode 1)) (doom-initialize-modules force-p)))
  doom-initialize()
  eval-buffer(#<buffer  *load*> nil "/Users/logan/.emacs.d/init.el" nil t)  ; Reading at buffer position 2620
  load-with-code-conversion("/Users/logan/.emacs.d/init.el" "/Users/logan/.emacs.d/init.el" t t)
  load("/Users/logan/.emacs.d/init" t t)
  #f(compiled-function () #<bytecode 0x400cbd8d>)()
  command-line()
  normal-top-level()

</pre></details>

**Steps to reproduce:**
1. Select these example steps,
2. Delete them,
3. And replace them with precise steps to reproduce your issue.
4. Fill in "system information" below.

**System information:**
<details><pre>
((emacs
  (version . "26.3")
  (features . "NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS LCMS2")
  (build . "Dec 09, 2019")
  (buildopts "--enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-mac/emacs-26.3-z-mac-7.8/share/info/emacs --prefix=/usr/local/Cellar/emacs-mac/emacs-26.3-z-mac-7.8 --with-mac --enable-mac-app=/usr/local/Cellar/emacs-mac/emacs-26.3-z-mac-7.8 --with-gnutls --with-modules")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "grafted, HEAD -> develop, origin/develop, origin/HEAD e217d77 2020-06-01 19:58:10 -0400")
  (dir . "~/.doom.d/"))
 (system
  (type . darwin)
  (config . "x86_64-apple-darwin18.7.0")
  (shell . "/bin/zsh")
  (uname . "Darwin 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64")
  (path "/usr/local/opt/gnu-sed/libexec/gnubin" "/usr/local/opt/gnupg@2.1/bin" "~/.opam/4.03.0/bin" "~/.cargo/bin" "~/.nodenv/shims" "~/.nix-profile/bin" "~/.rbenv/shims" "/usr/local/opt/jenv/shims" "/usr/local/opt/jenv" "~/.opam/system/bin" "/bin" "/usr/local/bin" "~/bin" "~/dev/dotfiles-private/bin" "/opt/local/bin" "/opt/local/sbin" "~/dev/adt-bundle-mac/sdk/platform-tools" "~/.doom-emacs.d/bin" "/usr/local/bin" "/usr/bin" "/bin" "/usr/sbin" "/sbin" "/opt/X11/bin" "/usr/local/sbin" "~/node_modules/.bin" "~/golang/bin" "/usr/local/opt/go/libexec/bin" "/usr/local/Cellar/emacs-mac/emacs-26.3-z-mac-7.8/libexec/emacs/26.3/x86_64-apple-darwin18.7.0"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline ophints (popup +defaults) vc-gutter vi-tilde-fringe :editor (evil +everywhere) file-templates fold snippets :emacs dired electric undo vc :checkers syntax :tools editorconfig (eval +overlay) lookup magit :lang emacs-lisp markdown org sh :config (default +bindings))
  (packages (auto-compile) (dap-mode) (docker) (dockerfile-mode) (feature-mode) (find-lisp) (floobits) (flycheck) (flyspell) (flyspell-correct) (elm-mode) (graphviz-dot-mode) (groovy-mode) (habitica) (highlight-parentheses) (lsp-java) (lua-mode) (js2-mode) (lsp-mode) (lsp-ui) (markdown-mode) (mu4e) (multi-line) (multi-term) (noflet) (org-indent :disable t) (org-mime) (org-mode) (org-superstar :disable t) (ox-gfm) (pinentry) (piper :recipe (:local-repo "~/dev/emacs-piper")) (plantuml-mode) (persp-mode :disable t) (prettier-js) (rainbow-identifiers) (rainbow-delimiters) (rainbow-mode) (request-deferred) (ruby-mode) (rjsx-mode) (rust-mode) (so-long) (terraform-mode) (web-beautify))
  (unpin "n/a")
  (elpa "n/a")))
</pre></details>

Thanks for maintaining such a wonderful project that really helps my Emacs experience! :)

**Comment by hlissner** [comment]
Ah, my bad! 6a85417 should resolve this. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
