### ISSUE TITLE
Install with doom-package-error "nose"

### ISSUE THREAD

**Issue by 0liu** [hlissner/doom-emacs#3273]
**What did you expect to happen?**
Install Doom Emacs.

**What actually happened?**

> x There was an unexpected error:
>   Type: doom-package-error
>   Message:
>     Error with packages
>   Data:
>     "nose"
>     (error "Failed to run \"git\"; see buffer *straight-process*")
>   Straight output:
>     Cloning into '/home/ning/code/doom-emacs/.local/straight/repos/nose'...
>     fatal: could not read Username for 'https://github.com': No such device or address

**Additional details:**
- Include a link to your private config
- Include screenshots/casts of your issue
- If you mention key sequences, include what commands they're bound to (use `SPC
  h k KEY` or `C-h h k KEY` to inspect keys).
- Include any warnings or errors logged to \*Messages\* (use `M-x
  view-echo-area-messages` to see it).

<details><pre>
If an error message is involved include a backtrace of it.

How to acquire a backtrace:
https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#how-to-extract-a-backtrace-from-an-error
</pre></details>

**Steps to reproduce:**
1. git clone --depth 1 https://github.com/hlissner/doom-emacs
2. doom install

**System information:**
<details><pre>
Place the output of `M-x doom/info` or `~/.emacs.d/bin/doom info` here.
</pre></details>

**Comment by visini** [comment]
Same issue, upgraded a few hours ago and `bin/doom sync` no longer seems to work. 

`bin/doom info` output:
```emacs-lisp
((emacs
  (version . "26.3")
  (features . "NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS")
  (build . "Sep 02, 2019")
  (buildopts "--with-ns '--enable-locallisppath=/Library/Application Support/Emacs/${version}/site-lisp:/Library/Application Support/Emacs/site-lisp' --with-modules")
  (windowsys . batch)
  (daemonp))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop 6a85417e8 2020-06-01 21:02:36 -0400")
  (dir . "~/.doom.d/"))
 (system
  (type . darwin)
  (config . "x86_64-apple-darwin18.2.0")
  (shell . "/bin/zsh")
  (uname . "Darwin 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64")
  (path "~/perl5/bin" "~/.pyenv/shims" "~/.nvm/versions/node/v12.16.1/bin" "/usr/local/bin" "/usr/bin" "/bin" "/usr/sbin" "/sbin" "/Applications/VMware Fusion.app/Contents/Public" "/Library/TeX/texbin" "/usr/local/go/bin" "~/go//bin" "/usr/local/opt/go/libexec/bin" "/Applications/Emacs.app/Contents/MacOS/bin-x86_64-10_14" "/Applications/Emacs.app/Contents/MacOS/libexec-x86_64-10_14" "/Applications/Emacs.app/Contents/MacOS/libexec" "/Applications/Emacs.app/Contents/MacOS/bin"))
 (config
  (envfile)
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline ophints (popup +defaults) treemacs vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold snippets :emacs dired electric undo vc :term vterm :checkers syntax :tools (eval +overlay) lookup magit make pdf :lang emacs-lisp (go +lsp) json javascript latex markdown (org +roam) python sh web yaml :config (default +bindings +smartparens))
  (packages (emojify) (org-ref) (org-noter) (org-roam-bibtex))
  (unpin "n/a")
  (elpa "n/a")))
((emacs
  (version . "26.3")
  (features . "NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS")
  (build . "Sep 02, 2019")
  (buildopts "--with-ns '--enable-locallisppath=/Library/Application Support/Emacs/${version}/site-lisp:/Library/Application Support/Emacs/site-lisp' --with-modules")
  (windowsys . batch)
  (daemonp))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop 6a85417e8 2020-06-01 21:02:36 -0400")
  (dir . "~/.doom.d/"))
 (system
  (type . darwin)
  (config . "x86_64-apple-darwin18.2.0")
  (shell . "/bin/zsh")
  (uname . "Darwin 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64")
  (path "~/perl5/bin" "~/.pyenv/shims" "~/.nvm/versions/node/v12.16.1/bin" "/usr/local/bin" "/usr/bin" "/bin" "/usr/sbin" "/sbin" "/Applications/VMware Fusion.app/Contents/Public" "/Library/TeX/texbin" "/usr/local/go/bin" "~/go//bin" "/usr/local/opt/go/libexec/bin" "/Applications/Emacs.app/Contents/MacOS/bin-x86_64-10_14" "/Applications/Emacs.app/Contents/MacOS/libexec-x86_64-10_14" "/Applications/Emacs.app/Contents/MacOS/libexec" "/Applications/Emacs.app/Contents/MacOS/bin"))
 (config
  (envfile)
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline ophints (popup +defaults) treemacs vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold snippets :emacs dired electric undo vc :term vterm :checkers syntax :tools (eval +overlay) lookup magit make pdf :lang emacs-lisp (go +lsp) json javascript latex markdown (org +roam) python sh web yaml :config (default +bindings +smartparens))
  (packages (emojify) (org-ref) (org-noter) (org-roam-bibtex))
  (unpin "n/a")
  (elpa "n/a")))

```

**Comment by visini** [comment]
Disabling `python` from `:lang` within `~/.doom.d/init.el` temporarily fixed the error (since all python-related packages are disabled / purged). But seems like `nose` is missing from [emacsmirror github](https://github.com/emacsmirror?q=nose&type=&language=)...

**Comment by shanyouli** [comment]
+1, @visini , Maybe you don't need to disabling python module, only need to disabling `nose` package. code:
```lisp
(disable-packages! nose)
```

**Comment by gagbo** [comment]
For the record, the issue is that the `nose` repo disappeared, so git is asking for credentials in case the repo is just hidden and you need authentification to see it.

Disabling nose as suggested above is a nice fix until nose situation is figured out I suppose

**Comment by Famiu** [comment]
I was facing the same issue, disabling nose fixed it. However, I'm still waiting for a better fix

**Comment by hlissner** [comment]
The problem is: `nose` was moved from [emacsmirror](https://github.com/emacsmirror/) to [emacsattic](https://github.com/emacsattic/), but https://github.com/emacsmirror/epkgs hasn't updated its emacsattic index yet, so straight doesn't know where to install `nose` from.

As of e916122 Doom now installs it explicitly from its emacsattic source, so I'll consider this temporarily resolved. I'll leave this open until epkgs has updated upstream.
