### ISSUE TITLE
The clang flycheck checker gets chained when using lsp-mode or eglot

### ISSUE THREAD

**Issue by robbert-vdh** [hlissner/doom-emacs#3274]
Using ccls (or clangd) with either lsp-mode or Eglot causes the `c/c++-clang` flycheck checker to be run after the LSP implementation's checker. This will result in the file getting checked twice, but since the `c/c++-clang` checker does not take the compilation database into account when editing headers this results in a lot of false positives. The behavior was introduced by #3256 for lsp-mode, and it's been part of the flycheck implementation in `modules/tools/lsp/autoloads/flycheck-eglot.el`. The obvious way around this would be to just disable these kinds of checkers when using LSP. For instance, I've added this to my personal config for disabling just this specific checker, but something similar would be needed for other languages:

```emacs-lisp
(setq-hook! '(eglot--managed-mode-hook lsp-managed-mode-hook)
  flycheck-disabled-checkers '(c/c++-clang))
```

**What did you expect to happen?**
Not seeing any kind of compiler warnings or errors when ccls does not report any.

**What actually happened?**
False positive errors show up when editing headers with LSP enabled.

**Additional details:**
- [private config](https://github.com/robbert-vdh/dotfiles/blob/master/user/emacs/) (probably not relevant)

**Steps to reproduce:**
1. Enable the `:tools lsp` module and `:lang cc` with the `+lsp` flag.
2. Edit a header file that relies in a Meson or CMake project with custom include paths and a `compile_commands.json` file.

**System information:**
<details>

```
emacs   version    28.0.50
        features   XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP
        build      mei 21, 2020
        buildopts  (--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --mandir=/usr/share/man --with-gameuser=:games --with-sound=alsa --with-modules --without-gconf --without-gsettings --with-x-toolkit=gtk3 --without-xaw3d --without-compress-install 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -flto' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now)
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop, origin/develop 6a85417e8 2020-06-01 21:02:36 -0400
        dir        ~/.dotfiles/user/emacs/.config/doom/
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /usr/bin/fish
        uname      Linux 5.6.15-1-MANJARO #1 SMP PREEMPT Wed May 27 20:38:56 UTC 2020 x86_64
        path       (~/.cargo/bin ~/.local/bin ~/.cargo/bin ~/.dotfiles/bin ~/.local/bin /opt/intel/vtune_amplifier_2019.5.0.601413/bin64 /usr/local/sbin /usr/local/bin /usr/bin /opt/cuda/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /var/lib/snapd/snap/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /usr/lib/emacs/28.0.50/x86_64-pc-linux-gnu)
config  envfile    nil
        elc-files  0
        modules    (:completion (company +auto) (ivy +prescient) :ui doom doom-dashboard doom-quit hl-todo hydra modeline nav-flash ophints (popup +all +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold (format +onsave) multiple-cursors rotate-text snippets word-wrap :emacs dired electric undo vc :term eshell vterm :checkers (syntax +childframe) (spell +everywhere) grammar :tools direnv docker editorconfig ein (eval +overlay) gist (lookup +docsets) (lsp +peek) (magit +forge) make pdf rgb taskrunner :lang (cc +lsp) csharp data emacs-lisp (json +lsp) javascript (latex +latexmk +lsp) markdown (org +gnuplot +dragndrop +jupyter +pandoc +present) (php +lsp) (python +lsp) rest rst (rust +lsp) (sh +fish) (web +lsp) (yaml +lsp) :config literate (default +bindings +smartparens))
        packages   ((academic-phrases) (ein) (ggtags) (kotlin-mode) (meson-mode) (ob-ipython) (page-break-lines) (phpcbf) (pkgbuild-mode) (magit-delta))
        unpin      (n/a)
        elpa       (n/a)
```
</details>

**Comment by tprk77** [comment]
Seconded. Just started using Doom for the first time, and for the last hour I thought I had set it up wrong. :laughing:

**Comment by hlissner** [comment]
Ah, you're right. It doesn't make sense to chain all the other checks to lsp, at least not as a general rule. As of https://github.com/hlissner/doom-emacs/commit/50f1391e86e35542d60cfa0e42356ae49d86bad4 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
