### ISSUE TITLE
Make the doom installer check for and prompt for the installation of fd and rg

### ISSUE THREAD

**Issue by ElectricCoffee** [hlissner/doom-emacs#3275]
Basically, I've noticed that running `doom doctor` after a clean installation, the doctor will complain that `fd` (fd-find) and `rg` (ripgrep) aren't installed, and that `rg` is supposedly a vital dependency.

If that's the case, how come nothing facilitates them being installed as part of the process?

Maybe prompt the user to install the packages themselves, or if `cargo` is installed, have the doom installer ask if it can do so via that. Honestly I went weeks before realising I even needed to install `rg` because I hadn't run `doctor` before.

The fact that they're written in Rust and available on crates.io makes cross-platform installation a cinch and could thus easily be accomplished by asking if cargo should be used if detected on the system.

**Comment by hlissner** [comment]
I am working on a rewrite of the CLI, which will improve the UX of `doom install`, among others. It will complain if you don't have ripgrep installed, but it is not Doom's responsibility to install these dependencies for you. That they're both rust tools is nice, but cargo isn't the only way to install or set up these packages. Rustup workflows complicate it further. Less mutable systems like Nix/Guix even more so. I won't try and guess what the user wants, and to quote one of Doom's mantras on its README:

> **Your system, your rules.** You know better. At least, Doom hopes so! It won't automatically install system dependencies (and will force plugins not to either). Rely on doom doctor to tell you what's missing.

So you can expect more warning (and hopefully better documentation), but that's as far as I will go.
