### ISSUE TITLE
`doom install` ignores arguments

### ISSUE THREAD

**Issue by sumitsahrawat** [hlissner/doom-emacs#3277]
**What did you expect to happen?**
`doom install --no-*` arguments work.

**What actually happened?**
<details><pre>
❯ rm -rf ~/.emacs.d ~/.doom.d
❯ git clone --depth=1 https://github.com/hlissner/doom-emacs ~/.emacs.d
Cloning into '/home/sums/.emacs.d'...
remote: Enumerating objects: 981, done.
remote: Counting objects: 100% (981/981), done.
remote: Compressing objects: 100% (931/931), done.
remote: Total 981 (delta 19), reused 315 (delta 9), pack-reused 0
Receiving objects: 100% (981/981), 803.89 KiB | 410.00 KiB/s, done.
Resolving deltas: 100% (19/19), done.
❯ ~/.emacs.d/bin/doom install --no-env
Installing straight...
Cloning use-package...
...
Generate an envvar file? (see `doom help env` for details) (y or n)
</pre></details>

**Additional details:**
- Include a link to your private config: Repro on a fresh install as shown above.
- Include screenshots/casts of your issue: NA
- If you mention key sequences, include what commands they're bound to (use `SPC
  h k KEY` or `C-h h k KEY` to inspect keys): NA
- Include any warnings or errors logged to \*Messages\* (use `M-x
  view-echo-area-messages` to see it): NA

**Steps to reproduce:**
Steps are mentioned in the "What happened" section above.

**System information:**
<details><pre>
((emacs
  (version . "26.3")
  (features . "XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2")
  (build . "May 19, 2020")
  (buildopts "--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-wide-int --with-modules 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now")
  (windowsys . batch)
  (daemonp))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD 6a85417e8 2020-06-01 21:02:36 -0400")
  (dir . "~/.doom.d/"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/bin/zsh")
  (uname . "Linux 5.6.15-arch1-1 #1 SMP PREEMPT Wed, 27 May 2020 23:42:26 +0000 x86_64")
  (path "~/.cargo/bin" "~/.emacs.d/bin" "~/.zinit/polaris/sbin" "~/.zinit/polaris/bin" "~/.zinit/polaris/usr/sbin" "~/.zinit/polaris/usr/bin" "/usr/local/bin" "/usr/local/sbin" "~/.cargo/bin" "~/.emacs.d/bin" "/usr/bin" "~/.bin" "/usr/lib/jvm/default/bin" "/usr/bin/site_perl" "/usr/bin/vendor_perl" "/usr/bin/core_perl" "~/.bin" "/usr/lib/emacs/26.3/x86_64-pc-linux-gnu"))
 (config
  (envfile)
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline ophints (popup +defaults) vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold snippets :emacs dired electric undo vc :checkers syntax :tools (eval +overlay) lookup magit :lang emacs-lisp markdown org sh :config (default +bindings +smartparens))
  (packages "n/a")
  (unpin "n/a")
  (elpa "n/a")))
</pre></details>

**Comment by hlissner** [comment]
I'm working on a rewrite of Doom's CLI that should properly fix this issue (it's still an issue for `doom compile`, for instance), but for now, 2a82413 should resolve this issue. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by sumitsahrawat** [comment]
Can confirm that it's working as expected. Thanks for the quick fix :+1:
