### ISSUE TITLE
repository 'https://github.com/emacsmirror/nose.git/' not found

### ISSUE THREAD

**Issue by jorschach-g** [hlissner/doom-emacs#3278]
**What did you expect to happen?**
For enabling default config with nose.git in it (which is one of the default settings in init.el), it should be cloning without further problems.

**What actually happened?**

> x There was an unexpected error:
>   Type: doom-package-error
>   Message:
>     Error with packages
>   Data:
>     "nose"
>     (error "Failed to run \"git\"; see buffer *straight-process*")
>   Straight output:
>     Cloning into '/Users/jorschach/.emacs.d/.local/straight/repos/nose'...
>     remote: Repository not found.
>     fatal: repository 'https://github.com/emacsmirror/nose.git/' not found

**Additional details:**
It should be a simple change of GitHub repo shall fix, yet I have no experience or any knowledge remotely close to how this package works in doom eamcs. 
Hopefully, this would not be too much of a hassle.

<details><pre>

> DOOM Initializing package.el
> DOOM Initializing straight.el
>   > Installing packages...
>     > Updating recipe repos...
>       > Updating recipes for melpa...nil
>       > Updating recipes for gnu-elpa-mirror...nil
>       > Updating recipes for emacsmirror-mirror...nil
>     → Cloning nose...
> x There was an unexpected error:
>   Type: doom-package-error
>   Message:
>     Error with packages
>   Data:
>     "nose"
>     (error "Failed to run \"git\"; see buffer *straight-process*")
>   Straight output:
>     Cloning into '/Users/jorschach/.emacs.d/.local/straight/repos/nose'...
>     remote: Repository not found.
>     fatal: repository 'https://github.com/emacsmirror/nose.git/' not found
>     
> 

Running "DEBUG=1 doom update" is greeted with error named:

> Cloning nose...
> x Package state is incomplete. Run ’doom sync’ first
> 

With backtracking:

> Debugger entered--Lisp error: (error "")
>   signal(error (""))
>   error("")
>   (condition-case e (if (null command) (doom-cli-execute "help") (let ((start-time (current-time))) (and (doom-cli-execute command args) (progn (run-hooks (quote doom-cli-post-hook)) t) (print! (success "Finished! (%.4fs)") (float-time (time-subtract (current-time) start-time)))))) (user-error (print! (error "%s\n") (error-message-string e)) (print! (yellow "See 'doom help %s' for documentation on this command.") (car args)) (error "")) ((debug error) (print! (error "There was an unexpected error:")) (print-group! (print! "%s %s" (bold "Type:") (car e)) (print! (bold "Message:")) (print-group! (print! "%s" (get (car e) (quote error-message)))) (print! (bold "Data:")) (print-group! (if (cdr e) (let ((--dolist-tail-- ...) item) (while --dolist-tail-- (setq item ...) (print! "%S" item) (setq --dolist-tail-- ...))) (print! "n/a"))) (if (and (and (boundp (quote straight-process-buffer)) straight-process-buffer) (string-match-p (regexp-quote straight-process-buffer) (error-message-string e))) (progn (print! (bold "Straight output:")) (print-group! (print! "%s" (straight--process-get-output)))))) (if debug-on-error nil (terpri) (print! (concat "Run the command again with the -d (or --debug) switch to enable debug\n" "mode and (hopefully) generate a backtrace from this error:\n" "\n  %s\n\n" "If you file a bug report, please include it!") (string-join (append (list (file-name-nondirectory load-file-name) "-d" command) args) " ")) (error ""))))
>   (let (print-level print-gensym print-length) (condition-case e (if (null command) (doom-cli-execute "help") (let ((start-time (current-time))) (and (doom-cli-execute command args) (progn (run-hooks (quote doom-cli-post-hook)) t) (print! (success "Finished! (%.4fs)") (float-time (time-subtract ... start-time)))))) (user-error (print! (error "%s\n") (error-message-string e)) (print! (yellow "See 'doom help %s' for documentation on this command.") (car args)) (error "")) ((debug error) (print! (error "There was an unexpected error:")) (print-group! (print! "%s %s" (bold "Type:") (car e)) (print! (bold "Message:")) (print-group! (print! "%s" (get (car e) (quote error-message)))) (print! (bold "Data:")) (print-group! (if (cdr e) (let (... item) (while --dolist-tail-- ... ... ...)) (print! "n/a"))) (if (and (and (boundp ...) straight-process-buffer) (string-match-p (regexp-quote straight-process-buffer) (error-message-string e))) (progn (print! (bold "Straight output:")) (print-group! (print! "%s" ...))))) (if debug-on-error nil (terpri) (print! (concat "Run the command again with the -d (or --debug) switch to enable debug\n" "mode and (hopefully) generate a backtrace from this error:\n" "\n  %s\n\n" "If you file a bug report, please include it!") (string-join (append (list ... "-d" command) args) " ")) (error "")))))
>   (let ((help-p (cdr (assq (quote help-p) --alist--))) (debug-p (cdr (assq (quote debug-p) --alist--))) (yes-p (cdr (assq (quote yes-p) --alist--))) (emacsdir (cdr (assq (quote emacsdir) --alist--))) (doomdir (cdr (assq (quote doomdir) --alist--))) (localdir (cdr (assq (quote localdir) --alist--))) (command (cdr (assq (quote command) --alist--))) (args (cdr (assq (quote args) --alist--)))) :bare t (if emacsdir (progn (setq user-emacs-directory (file-name-as-directory emacsdir)) (print! (info "EMACSDIR=%s") emacsdir))) (if doomdir (progn (setenv "DOOMDIR" (file-name-as-directory doomdir)) (print! (info "DOOMDIR=%s") localdir))) (if localdir (progn (setenv "DOOMLOCALDIR" (file-name-as-directory localdir)) (print! (info "DOOMLOCALDIR=%s") localdir))) (if debug-p (progn (setenv "DEBUG" "1") (setq doom-debug-p t) (print! (info "Debug mode on")))) (if yes-p (progn (setenv "YES" "1") (setq doom-auto-accept t) (print! (info "Auto-yes on")))) (if help-p (progn (if command (progn (setq args (cons command args)))) (setq command "help"))) (if (equal (user-real-uid) 0) (progn (print! (concat "WARNING: This script is running as root. This likely wasn't intentional, and\n" "is unnecessary to use this script. This will cause file permissions errors\n" "later if you use this Doom installation on a non-root account.\n")) (if (or doom-auto-accept (y-or-n-p "Continue anyway?")) nil (user-error "Aborted")))) (if (or emacsdir doomdir localdir) (progn (load! "core/core.el" user-emacs-directory))) (load! doom-module-init-file doom-private-dir t) (maphash (doom-module-loader doom-cli-file) doom-modules) (load! doom-cli-file doom-private-dir t) (run-hooks (quote doom-cli-pre-hook)) (let (print-level print-gensym print-length) (condition-case e (if (null command) (doom-cli-execute "help") (let ((start-time (current-time))) (and (doom-cli-execute command args) (progn (run-hooks ...) t) (print! (success "Finished! (%.4fs)") (float-time ...))))) (user-error (print! (error "%s\n") (error-message-string e)) (print! (yellow "See 'doom help %s' for documentation on this command.") (car args)) (error "")) ((debug error) (print! (error "There was an unexpected error:")) (print-group! (print! "%s %s" (bold "Type:") (car e)) (print! (bold "Message:")) (print-group! (print! "%s" (get ... ...))) (print! (bold "Data:")) (print-group! (if (cdr e) (let ... ...) (print! "n/a"))) (if (and (and ... straight-process-buffer) (string-match-p ... ...)) (progn (print! ...) (print-group! ...)))) (if debug-on-error nil (terpri) (print! (concat "Run the command again with the -d (or --debug) switch to enable debug\n" "mode and (hopefully) generate a backtrace from this error:\n" "\n  %s\n\n" "If you file a bug report, please include it!") (string-join (append ... args) " ")) (error ""))))))
>   (lambda (--alist--) (ignore --alist--) (let ((help-p (cdr (assq (quote help-p) --alist--))) (debug-p (cdr (assq (quote debug-p) --alist--))) (yes-p (cdr (assq (quote yes-p) --alist--))) (emacsdir (cdr (assq (quote emacsdir) --alist--))) (doomdir (cdr (assq (quote doomdir) --alist--))) (localdir (cdr (assq (quote localdir) --alist--))) (command (cdr (assq (quote command) --alist--))) (args (cdr (assq (quote args) --alist--)))) :bare t (if emacsdir (progn (setq user-emacs-directory (file-name-as-directory emacsdir)) (print! (info "EMACSDIR=%s") emacsdir))) (if doomdir (progn (setenv "DOOMDIR" (file-name-as-directory doomdir)) (print! (info "DOOMDIR=%s") localdir))) (if localdir (progn (setenv "DOOMLOCALDIR" (file-name-as-directory localdir)) (print! (info "DOOMLOCALDIR=%s") localdir))) (if debug-p (progn (setenv "DEBUG" "1") (setq doom-debug-p t) (print! (info "Debug mode on")))) (if yes-p (progn (setenv "YES" "1") (setq doom-auto-accept t) (print! (info "Auto-yes on")))) (if help-p (progn (if command (progn (setq args (cons command args)))) (setq command "help"))) (if (equal (user-real-uid) 0) (progn (print! (concat "WARNING: This script is running as root. This likely wasn't intentional, and\n" "is unnecessary to use this script. This will cause file permissions errors\n" "later if you use this Doom installation on a non-root account.\n")) (if (or doom-auto-accept (y-or-n-p "Continue anyway?")) nil (user-error "Aborted")))) (if (or emacsdir doomdir localdir) (progn (load! "core/core.el" user-emacs-directory))) (load! doom-module-init-file doom-private-dir t) (maphash (doom-module-loader doom-cli-file) doom-modules) (load! doom-cli-file doom-private-dir t) (run-hooks (quote doom-cli-pre-hook)) (let (print-level print-gensym print-length) (condition-case e (if (null command) (doom-cli-execute "help") (let ((start-time ...)) (and (doom-cli-execute command args) (progn ... t) (print! ... ...)))) (user-error (print! (error "%s\n") (error-message-string e)) (print! (yellow "See 'doom help %s' for documentation on this command.") (car args)) (error "")) ((debug error) (print! (error "There was an unexpected error:")) (print-group! (print! "%s %s" (bold "Type:") (car e)) (print! (bold "Message:")) (print-group! (print! "%s" ...)) (print! (bold "Data:")) (print-group! (if ... ... ...)) (if (and ... ...) (progn ... ...))) (if debug-on-error nil (terpri) (print! (concat "Run the command again with the -d (or --debug) switch to enable debug\n" "mode and (hopefully) generate a backtrace from this error:\n" "\n  %s\n\n" "If you file a bug report, please include it!") (string-join ... " ")) (error "")))))))(((command . "update")))
>   funcall((lambda (--alist--) (ignore --alist--) (let ((help-p (cdr (assq (quote help-p) --alist--))) (debug-p (cdr (assq (quote debug-p) --alist--))) (yes-p (cdr (assq (quote yes-p) --alist--))) (emacsdir (cdr (assq (quote emacsdir) --alist--))) (doomdir (cdr (assq (quote doomdir) --alist--))) (localdir (cdr (assq (quote localdir) --alist--))) (command (cdr (assq (quote command) --alist--))) (args (cdr (assq (quote args) --alist--)))) :bare t (if emacsdir (progn (setq user-emacs-directory (file-name-as-directory emacsdir)) (print! (info "EMACSDIR=%s") emacsdir))) (if doomdir (progn (setenv "DOOMDIR" (file-name-as-directory doomdir)) (print! (info "DOOMDIR=%s") localdir))) (if localdir (progn (setenv "DOOMLOCALDIR" (file-name-as-directory localdir)) (print! (info "DOOMLOCALDIR=%s") localdir))) (if debug-p (progn (setenv "DEBUG" "1") (setq doom-debug-p t) (print! (info "Debug mode on")))) (if yes-p (progn (setenv "YES" "1") (setq doom-auto-accept t) (print! (info "Auto-yes on")))) (if help-p (progn (if command (progn (setq args ...))) (setq command "help"))) (if (equal (user-real-uid) 0) (progn (print! (concat "WARNING: This script is running as root. This likely wasn't intentional, and\n" "is unnecessary to use this script. This will cause file permissions errors\n" "later if you use this Doom installation on a non-root account.\n")) (if (or doom-auto-accept (y-or-n-p "Continue anyway?")) nil (user-error "Aborted")))) (if (or emacsdir doomdir localdir) (progn (load! "core/core.el" user-emacs-directory))) (load! doom-module-init-file doom-private-dir t) (maphash (doom-module-loader doom-cli-file) doom-modules) (load! doom-cli-file doom-private-dir t) (run-hooks (quote doom-cli-pre-hook)) (let (print-level print-gensym print-length) (condition-case e (if (null command) (doom-cli-execute "help") (let (...) (and ... ... ...))) (user-error (print! (error "%s\n") (error-message-string e)) (print! (yellow "See 'doom help %s' for documentation on this command.") (car args)) (error "")) ((debug error) (print! (error "There was an unexpected error:")) (print-group! (print! "%s %s" ... ...) (print! ...) (print-group! ...) (print! ...) (print-group! ...) (if ... ...)) (if debug-on-error nil (terpri) (print! ... ...) (error ""))))))) ((command . "update")))
>   (if cli (funcall (progn (or (and (memq (type-of cli) cl-struct-doom-cli-tags) t) (signal (quote wrong-type-argument) (list (quote doom-cli) cli))) (aref cli 7)) (doom--cli-process cli (remq nil args))) (user-error "Couldn't find any %S command" command))
>   (let* ((cli (and t (doom-cli-get command)))) (if cli (funcall (progn (or (and (memq (type-of cli) cl-struct-doom-cli-tags) t) (signal (quote wrong-type-argument) (list (quote doom-cli) cli))) (aref cli 7)) (doom--cli-process cli (remq nil args))) (user-error "Couldn't find any %S command" command)))
>   doom-cli-execute(:main ("update"))
>   (let* ((loaddir (file-name-directory (file-truename load-file-name))) (emacsdir (getenv "EMACSDIR")) (user-emacs-directory (abbreviate-file-name (if emacsdir (file-name-as-directory emacsdir) (expand-file-name "../" loaddir))))) (load (expand-file-name "core/core.el" user-emacs-directory) nil t) (quiet! (if (> emacs-major-version 26) (progn (require (quote cl)))) (load "site-start" t t)) (doom-log "Initializing Doom CLI") (require (quote core-cli)) (defcli! :main ((help-p ["-h" "--help"] "Same as help command") (debug-p ["-d" "--debug"] "Turns on doom-debug-p (and debug-on-error)") (yes-p ["-y" "--yes"] "Auto-accept all confirmation prompts") (emacsdir ["--emacsdir" dir] "Use the emacs config at DIR (e.g. ~/.emacs.d)") (doomdir ["--doomdir" dir] "Use the private module at DIR (e.g. ~/.doom.d)") (localdir ["--localdir" dir] "Use DIR as your local storage directory") &optional command &rest args) "A command line interface for managing Doom Emacs.\n\nIncludes package management, diagnostics, unit tests, and byte-compilation.\n\nThis tool also makes it trivial to launch Emacs out of a different folder or\nwith a different private module." :bare t (if emacsdir (progn (setq user-emacs-directory (file-name-as-directory emacsdir)) (print! (info "EMACSDIR=%s") emacsdir))) (if doomdir (progn (setenv "DOOMDIR" (file-name-as-directory doomdir)) (print! (info "DOOMDIR=%s") localdir))) (if localdir (progn (setenv "DOOMLOCALDIR" (file-name-as-directory localdir)) (print! (info "DOOMLOCALDIR=%s") localdir))) (if debug-p (progn (setenv "DEBUG" "1") (setq doom-debug-p t) (print! (info "Debug mode on")))) (if yes-p (progn (setenv "YES" "1") (setq doom-auto-accept t) (print! (info "Auto-yes on")))) (if help-p (progn (if command (progn (setq args (cons command args)))) (setq command "help"))) (if (equal (user-real-uid) 0) (progn (print! (concat "WARNING: This script is running as root. This likely wasn't intentional, and\n" "is unnecessary to use this script. This will cause file permissions errors\n" "later if you use this Doom installation on a non-root account.\n")) (if (or doom-auto-accept (y-or-n-p "Continue anyway?")) nil (user-error "Aborted")))) (if (or emacsdir doomdir localdir) (progn (load! "core/core.el" user-emacs-directory))) (load! doom-module-init-file doom-private-dir t) (maphash (doom-module-loader doom-cli-file) doom-modules) (load! doom-cli-file doom-private-dir t) (run-hooks (quote doom-cli-pre-hook)) (let (print-level print-gensym print-length) (condition-case e (if (null command) (doom-cli-execute "help") (let ((start-time ...)) (and (doom-cli-execute command args) (progn ... t) (print! ... ...)))) (user-error (print! (error "%s\n") (error-message-string e)) (print! (yellow "See 'doom help %s' for documentation on this command.") (car args)) (error "")) ((debug error) (print! (error "There was an unexpected error:")) (print-group! (print! "%s %s" (bold "Type:") (car e)) (print! (bold "Message:")) (print-group! (print! "%s" ...)) (print! (bold "Data:")) (print-group! (if ... ... ...)) (if (and ... ...) (progn ... ...))) (if debug-on-error nil (terpri) (print! (concat "Run the command again with the -d (or --debug) switch to enable debug\n" "mode and (hopefully) generate a backtrace from this error:\n" "\n  %s\n\n" "If you file a bug report, please include it!") (string-join ... " ")) (error "")))))) (doom-cli-execute :main (cdr (member "--" argv))) (setq argv nil))
>   eval-buffer(#<buffer  *load*> nil "/Users/jorschach/.emacs.d/bin/doom" nil t)  ; Reading at buffer position 6208
>   load-with-code-conversion("/Users/jorschach/.emacs.d/bin/doom" "/Users/jorschach/.emacs.d/bin/doom" nil t)
>   load("/Users/jorschach/.emacs.d/bin/doom" nil t t)
>   command-line-1(("-scriptload" "/Users/jorschach/.emacs.d/bin/doom" "--" "update"))
>   command-line()
>   normal-top-level()
> 

As stated above. Hopefully, that helps.

How to acquire a backtrace:
https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#how-to-extract-a-backtrace-from-an-error
</pre></details>

**Steps to reproduce:**

All that I know is that I enabled:
* neotree
* vterm
* docker
* pdf
* tmux
* cc
* java + meghanada
* javascript
* latex
* markdown
* ocaml
* org
* python
* swift
* calendar
* rss + org

package at the same time.

I would definitely try to make this clearer, yet one would be easy to fix these issues when seeing the first part of the problem description (I presume).

**System information:**
<details><pre>
Place the output of `M-x doom/info` or `~/.emacs.d/bin/doom info` here.
</pre></details>

((emacs
  (version . "26.3")
  (features . "NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS")
  (build . "Sep 02, 2019")
  (buildopts "--with-ns '--enable-locallisppath=/Library/Application Support/Emacs/${version}/site-lisp:/Library/Application Support/Emacs/site-lisp' --with-modules")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "grafted, HEAD -> develop, origin/develop, origin/HEAD 6a85417 2020-06-01 21:02:36 -0400")
  (dir . "~/.doom.d/"))
 (system
  (type . darwin)
  (config . "x86_64-apple-darwin18.2.0")
  (shell . "/bin/bash")
  (uname . "Darwin 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64")
  (path "~/anaconda3/bin" "/usr/local/bin" "/usr/bin" "/bin" "/usr/sbin" "/sbin" "/Library/TeX/texbin" "/Applications/Emacs.app/Contents/MacOS/bin-x86_64-10_14" "/Applications/Emacs.app/Contents/MacOS/libexec-x86_64-10_14" "/Applications/Emacs.app/Contents/MacOS/libexec" "/Applications/Emacs.app/Contents/MacOS/bin"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :input chinese :completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline neotree ophints (popup +defaults) vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold snippets :emacs dired electric undo vc :term vterm :checkers syntax spell grammar :tools docker (eval +overlay) lookup magit make pdf tmux :lang cc emacs-lisp (java +meghanada) javascript latex markdown ocaml org python sh swift web yaml :app calendar (rss +org) :config (default +bindings +smartparens))
  (packages "n/a")
  (unpin "n/a")
  (elpa "n/a")))

**Comment by jorschach-g** [comment]
With further testing, I have found that in init.el under ~/.doom.d, you only have to activate the language python to recreate the issue, and nose.git might be something close to:

[https://bitbucket.org/durin42/nosemacs/src/default/nose.el](nose.el)

Which might be valuable to check out if that is the case.

Again, since it might be embedded with git, and I have little to no knowledge with the lisp, I really cannot fix this on my own.

I hope that in any way helps.

**Comment by gagbo** [comment]
Duplicate of #3273

**Comment by jorschach-g** [comment]
Solved by adding:
> (disable-packages! nose)
to my packages.el under doom.d

That does not solve the problem, yet is a valuable fix. 
Merged with the duplicates.
