### ISSUE TITLE
Upgrade seems to fetch all packages tags

### ISSUE THREAD

**Issue by bepvte** [hlissner/doom-emacs#3279]
**What did you expect to happen?**
When I run doom upgrade/update etc, I would like for each package to only fetch what it needs, and not negate the shallow clone. 

**What actually happened?**
straight.el or something in doom is not configuring git fetch to use `--no-tags`. Without `--no-tags`, instead of just the required or recent history being fetched, all the tags and their connected revisions are fetched as well. When cloning repositories, using `git clone --no-tags` writes
```
[remote "origin"]
	tagOpt = --no-tags
```
which prevents tags from being fetched in the future. Tags do not get removed with `git gc` and keep their history and associated data until removed.

This could be solved by configuring straight to clone packages with `git clone --no-tags --depth=1` or to update them with `git fetch/pull --no-tags` instead.

**Additional details:**
- Include a link to your private config: [here](https://gist.github.com/bepvte/da48d1621eb6673eb6b3a3056c9ae0a9) 
- Include screenshots/casts of your issue
- If you mention key sequences, include what commands they're bound to (use `SPC
  h k KEY` or `C-h h k KEY` to inspect keys).
- Include any warnings or errors logged to \*Messages\* (use `M-x
  view-echo-area-messages` to see it).

**Steps to reproduce:**
It seems to be hard to replicate, but It shouldn't be too hard to solve. Today after updating doom from a262527a7f...e916122750 I got notice of tags being fetched:
```
    > (222/235) Updating popup-el...
        From https://github.com/auto-complete/popup-el
           4839797..c76d516  master     -> origin/master
         * [new tag]         v0.5.7     -> v0.5.7
         * [new tag]         v0.4       -> v0.4
         * [new tag]         v0.5.0     -> v0.5.0
         * [new tag]         v0.5.1     -> v0.5.1
         * [new tag]         v0.5.2     -> v0.5.2
         * [new tag]         v0.5.3     -> v0.5.3
         * [new tag]         v0.5.4     -> v0.5.4
         * [new tag]         v0.5.5     -> v0.5.5
         * [new tag]         v0.5.6     -> v0.5.6
```

**System information:**
<details><pre>
((emacs
  (version . "27.0.91")
  (features . "XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND DBUS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER LCMS2 GMP")
  (build . "May 15, 2020")
  (buildopts "--build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-dbus --with-gif --with-jpeg --with-png --with-rsvg --with-cairo --with-tiff --with-xpm --with-x-toolkit=gtk3 --with-gpm=no --with-xwidgets --with-modules --without-gconf --without-gsettings --without-xft --without-m17n-flt --enable-link-time-optimization 'CFLAGS=-DMAIL_USE_LOCKF -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -flto=auto -fuse-linker-plugin -fno-fat-lto-objects -march=native -O2' 'LDFLAGS=-Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld'")
  (windowsys . batch)
  (daemonp))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop e91612275 2020-06-02 15:06:04 -0400")
  (dir . "~/dotfiles/stow/emacs/.doom.d/"))
 (system
  (type . gnu/linux)
  (config . "x86_64-redhat-linux-gnu")
  (shell . "/bin/zsh")
  (uname . "Linux 5.6.15-300.fc32.x86_64 #1 SMP Fri May 29 14:23:59 UTC 2020 x86_64")
  (path "~/.local/bin" "~/Android/Sdk/flutter/bin" "~/Android/Sdk/build-tools/29.0.2" "~/Android/Sdk/emulator" "~/Android/Sdk/platform-tools" "~/Android/Sdk/tools/bin" "~/Android/Sdk/custom/bin" "~/go/bin" "~/.cargo/bin" "~/.emacs.d/bin" "/usr/share/Modules/bin" "/usr/lib64/ccache" "/usr/local/bin" "/usr/local/sbin" "/usr/bin" "/usr/sbin" "~/bin" "~/.dotnet/tools" "/usr/libexec/emacs/27.0.91/x86_64-redhat-linux-gnu"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard hl-todo modeline ophints (popup +defaults) treemacs vc-gutter window-select workspaces zen :editor (evil +everywhere) file-templates fold format lispy multiple-cursors rotate-text snippets word-wrap :emacs dired electric (ibuffer +icons) undo vc :term eshell vterm :checkers syntax spell :tools docker editorconfig (eval +overlay) (lookup +dictionary) lsp magit rgb :lang (cc +lsp) data emacs-lisp (go +lsp) (json +lsp) javascript lua markdown rest (rust +lsp) sh web yaml :config (default +bindings +smartparens))
  (packages (hl-line :disable t) (doom-snippets :disable t) (clipetty :disable t) (flycheck-package :disable t) (yasnippet-snippets) (gtk-variant :recipe '(:host github :repo "bepvte/gtk-variant.el")))
  (unpin "n/a")
  (elpa "n/a")))

</pre></details>

**Comment by hlissner** [comment]
This should probably be reported upstream, to [straight](https://github.com/raxod502/straight.el), as I have no direct control over the git commands straight uses to fetch, and I'd rather not circumvent its API more than I need to. If there were an option, I'd be open to using it though. I'm down for less throughput when fetching.

**Comment by hlissner** [comment]
As an alternative, a `doom purge -g` command exists, which will regraft your git repos (i.e delete all history as if you had newly shallow-cloned the repos).

**Comment by raxod502** [comment]
I added `--no-tags --single-branch` to the shallow clone command used by `straight.el`, as noted in https://github.com/raxod502/straight.el/issues/532#issuecomment-643766458.

**Comment by bepvte** [comment]
This just needs a straight.el version bump and then can be closed.

**Comment by hlissner** [comment]
Straight was bumped a few days ago, but an [unrelated issue](https://github.com/hlissner/doom-emacs/issues/3406) may force me to temporarily revert -- will look into it further. In any case, I'll consider this resolved. Thanks for the prompt fix and letting me know!
