### ISSUE TITLE
 Symbol’s chain of function indirections contains a loop: R-mode

### ISSUE THREAD

**Issue by pmeckoni** [hlissner/doom-emacs#3283]
I use regular emacs bindings -- no evil-mode, no god-mode 
On trying to open a new file using `C-x C-f` I get an error message 

> Symbol’s chain of function indirections contains a loop: R-mode

I have the ess module enabled. disabling ess eliminates the error.

all packages and doom are updated

**Comment by hlissner** [comment]
Please include your `M-x doom/info` and [a backtrace](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#how-to-extract-a-backtrace-from-an-error) of the issue.

Please do not ignore the issue template in the future.

**Comment by pmeckoni** [comment]
forgive me, I couldn't get `M-x doom/info` output. It does not allow me to do `M-x` because of the error.

The `--debug-init` output is below:

> `Debugger entered--Lisp error: (cyclic-function-indirection r-mode)`
>  ` commandp(r-mode)`
>   `#f(compiled-function (symbol) #<bytecode 0x12d7c2d>)(r-mode)`
>  ` mapatoms(#f(compiled-function (symbol) #<bytecode 0x12d7c2d>))`
>   `amx-detect-new-commands()`
> `  amx-initialize()`
> `  counsel--M-x-externs()`
> `  counsel-M-x()`
> `  funcall-interactively(counsel-M-x)`
> `  call-interactively(counsel-M-x nil nil)`
> `  command-execute(counsel-M-x)`

**Comment by hlissner** [comment]
In that case, try running `~/.emacs.d/bin/doom info` on the command line.

**Comment by pmeckoni** [comment]
the output  of `$ ~/.emacs/bin/doom info` is in the attached file

[doom-info.txt](https://github.com/hlissner/doom-emacs/files/4733480/doom-info.txt)

**Comment by hlissner** [comment]
Whoa. You've installed a lot of packages through `package.el`. This could cause conflicts, and would explain why I can't reproduce your issue.

Doom doesn't use `package.el`, it uses `straight.el`. What's worse, half of the packages you have installed through package.el are packages already installed by Doom's modules (through straight), so you have duplicates.

This implies you have `:ensure t` in your `use-package` blocks, and/or you have a `(package-initialize)` in `~/.doom.d/config.el`. I recommend removing all of them, then running `~/.emacs.d/bin/doom sync -p` to delete all ELPA packages.

To install packages add `(package! X)` declarations to `~/.doom.d/packages.el`, where `X` is the name of the package. See [this section of our documentation about it](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#package-management). Don't forget to run `doom sync` to install packages. 

It's likely this will resolve your issue.

**Comment by hlissner** [comment]
Oh, I also see you're running Emacs 26.1. I highly recommend upgrading to, at least, 26.3. At most 27.0.91.

**Comment by pmeckoni** [comment]
I understand what your are saying. 

I'm using the emacs along with many of the elpa packages provided on Debian stable. I will try doom again later.

Thank your for your assistance.
