### ISSUE TITLE
Key stroke design philosophy

### ISSUE THREAD

**Issue by andyafter** [hlissner/doom-emacs#329]
I am a heavy emacs user but recently I have decided to migrate all my configs to doom because it is awesome. Getting familiar with evil key stokes and the design did took about a week's time. The evil way does provide a much wider space for configuration of everything. 

I have been using Prelude and tried Spacemacs a bit. But mostly Prelude because the structure is easier to understand and do dirty coding. 

So my problem is that, sometimes the evil way is creating a redundancy in a way because the tool set is actually ```stacking up```. 

For example:
When I am writing test for my program(in Golang), if I want to test a single function, I can either choose to map the key with a ```simple global-set-key```, and do a key combination. Or I can use 
the default Doom way:

```SPC m t```

which the editor then gives you a list of functions to choose from. Now in this case the function we need is ```single-test```, which is the third option, so I will also have to type:

```C-j C-j RET```
So in total I will have to at least press 6 keys in order to run a test function that I have. 

Now if I choose to write my own config and set the global key, it will make the structure into a mess. So my question is, what is the design philosophy of the design of Doom and how could I make it easier for use cases like this?

**Comment by hlissner** [comment]
That's awesome you decided to switch over! I understand how all-consuming that process can be (arguably _too_ well).

I understand your issue. Sorry to say much of Doom's keybinding scheme is a WIP, but here is what I am going for:

+ `SPC m t` = prefix for unit test commands
  + `SPC m t /` = open the unit test menu (what is currently bound to `SPC m t`)
  + `SPC m t .` = run single unit test at point
  + `SPC m t a` = run all unit tests
  + `SPC m t r` = rerun last test
+ `SPC m r` = prefix for refactoring commands
  + `SPC m r /` = open the refactoring commands menu
+ `SPC m b` = prefix for code/project building commands
  + `SPC m b /` = building commands menu
+ `SPC m h` = prefix for help/documentation/informational commands
  + `SPC m h /` = help commands menu

These are the only conventions (for localleader keybinds) that are "set in stone"; that I'd like consistent across all major modes. Whatever else makes it under those prefixes depends entirely on what is available to each major mode, which is difficult to anticipate.

In lang/go's case, it might look like:

```emacs-lisp
  (map! :map go-mode-map
        :localleader
        (:prefix "r"
          :n  "/"  #'+go/refactor-menu
          :n  "ai" #'go-import-add
          :n  "fi" #'go-remove-unused-imports
          :nv "q" #'go-fmt)
        (:prefix "b"
          "p" (exec! "go build")
          "P" (exec! "go run")
          "c" (exec! "go clean"))
        (:prefix "h"
          "i" #'go-goto-imports
          "." #'godoc-at-point
          "d" #'go-guru-describe
          [...])
        (:prefix "t" [...]))
```

**Comment by hlissner** [comment]
I'll consider this issue resolved and close it. Feel free to follow up here if you have more questions about keybinds!
