### ISSUE TITLE
hl-todo-mode in latex mode hook

### ISSUE THREAD

**Issue by haji-ali** [hlissner/doom-emacs#3290]
**What did you expect to happen?**
In a `doom` sandbox (with my modules below) I have the code
```
(after! tex
  (add-hook! LaTeX-mode 'hl-todo-mode))
```
To enable `hl-todo-mode` in LaTeX. I then visit a tex file with some TODOs in it. I expect these TODOs to be highlighted in a different color.

**What actually happened?**
The TODOs are not highlighted even though the variable `hl-todo-mode` is `t`. If I call the function `hl-todo-mode` the mode is disabled, if I call it again the mode is enabled and the TODOs are highlighted.

If I run vanilla doom instead of doom with modules, the TODOs are highlighted correctly.

**System information:**
<details>

```
emacs   version    26.3
        features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD LCMS2
        build      Sep 16, 2019
        buildopts  (--build=x86_64-linux-gnu --prefix=/usr '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' --sysconfdir=/etc --localstatedir=/var --disable-silent-rules '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' --disable-maintainer-mode --disable-dependency-tracking --prefix=/usr --sharedstatedir=/var/lib --program-suffix=26 --with-modules --with-file-notification=inotify --with-mailutils --with-x=yes --with-x-toolkit=gtk3 --with-xwidgets --with-lcms2 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/emacs26-TP6iDo/emacs26-26.3~1.git96dd019=. -fstack-protector-strong -Wformat -Werror=format-security -no-pie' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro -no-pie')
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop, origin/develop, origin/HEAD 6a85417e8 2020-06-01 21:02:36 -0400
        dir        ~/Work/Projects/dotfiles/emacs/.config/doom/
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/zsh
        uname      Linux 4.15.0-101-generic #102-Ubuntu SMP Mon May 11 10:07:26 UTC 2020 x86_64
        path       (~/.local/bin ~/.local/bin /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /usr/games /usr/local/games /snap/bin ~/.fzf/bin /usr/lib/x86_64-linux-gnu/emacs/26.3/x86_64-linux-gnu)
config  envfile    nil
        elc-files  0
        modules    (:completion company (ivy +icons) :ui doom hl-todo modeline nav-flash ophints vc-gutter vi-tilde-fringe window-select workspaces :editor file-templates fold multiple-cursors rotate-text snippets :emacs (dired +icons) electric ibuffer vc (undo +tree) :term eshell :checkers syntax spell :tools (eval +overlay) (lookup +docsets) magit make :lang (cc +irony +rtags) data emacs-lisp (latex +latexmk) markdown (org +attach +capture +dragndrop +present) python sh :email mu4e :app calendar :config literate (default +bindings +smartparens))
        packages   ((mu4e-alert) (hungry-delete) (yasnippet-snippets) (edit-server) (org-clock-today) (dired-subtree) (dired-single) (org-super-agenda) (xterm-color) (openwith) (rotate) (smartrep) (origami) (try) (el-patch))
        unpin      (n/a)
        elpa       (n/a)
```
</details>

**Comment by hlissner** [comment]
You need to put it on `TeX-mode-hook` instead (users not using the `:lang latex` module need to put it on `tex-mode-hook` instead).

**Comment by haji-ali** [comment]
I am using the `:lang (latex +latexmk)`.
Also, the hook is being executed as `hl-todo-mode` is `t` when I set `LaTeX-mode-hook` but the keywords are not highlighted.

**Comment by haji-ali** [comment]
I already tried doing that and got the same results. Did you have a different outcome?

The `LaTeX-mode-hook` is being executed (as is the `TeX-mode-hook`) and that is why the `hl-todo-mode` variable is `t`, however for some reason the keywords are not highlighted correctly.

**Comment by hlissner** [comment]
Yes. Putting it on `TeX-mode-hook` worked fine for me in vanilla emacs, vanilla doom (no modules, no config) and vanilla doom with modules (no config), with the following:

```elisp
(defun with-auctex ()
  (load "auctex")
  (require 'hl-todo)
  (add-hook 'TeX-mode-hook #'hl-todo-mode))

(defun without-auctex ()
  (require 'hl-todo)
  (add-hook 'tex-mode-hook #'hl-todo-mode))

;; Uncomment one of these
;; (with-auctex)
;; (without-auctex)

(find-file "~/test.tex")
```

**Comment by haji-ali** [comment]
Hmm.. This is really strange. I executed your code and in the sandbox with Doom (+modules) and `hl-todo-mode` worked. However, when I do the following (which is what I was doing before), it does not work:

- Open `doom/sandbox`
- Add part of your code
```
(defun with-auctex ()
  (load "auctex")
  (require 'hl-todo)
  (add-hook 'TeX-mode-hook #'hl-todo-mode))

(with-auctex)
```
Notice no `find-file`
- Open `Doom + modules - your private config` with `C-c C-p`.
- In the new Emacs instance, execute the `(find-file "~/test.tex")` command.
- `hl-todo-mode` **does not work**.

It is strange because if I had the `find-file` command in the sandbox buffer rather than execute it in the new emacs instance, then `hl-todo-mode` **does work**. If I execute vanilla doom (without the additional modules) then `hl-todo-mode` works no matter where I execute the `find-file` command.

_My guess_ is that one of the modules which get lazy loaded is causing the issue. When you execute the `find-file` command in the sandbox then that command is executed before the module is loaded and the issue does not appear.

Can you confirm if you are seeing this issue as well?

Sorry for the very specific issues.

**Comment by hlissner** [comment]
>   Open Doom + modules - your private config with C-c C-p.
>   In the new Emacs instance, execute the (find-file "~/test.tex") command.
>   hl-todo-mode does not work.

This worked fine for me on Emacs 26.3 and 27.0.91, on the latest commit of Doom, in `C-c C-p`.

Could it perhaps be the file we're testing on? I'm using [this](https://gist.github.com/hlissner/0651efcfa07fcc5a4023ed7beff79395), and the two `TODO`s in the comment and just after are highlighted just fine.

**Comment by haji-ali** [comment]
After spending way too much time debugging this, I finally found the culprit. However, I am closing the issue since it is not related to Doom. 

The reason turned out to be an auctex style hooks is automatically loaded by files inside `.auxtec-auto`. In particular, the `amsthm` style somehow interferes with `hl-todo-mode`.  I can't be bothered anymore to figure out what the exact reason is or how to fix it (it should be somewhere in `TeX-style-hook-list`).

Here's a sure way to recreate the issue
```elisp
(defun style-hook ()   ;; style hook that is normally autogenerated by auctex for files that use amsthm
  (TeX-add-style-hook "test"   ;; Important, same file name as the one to be opened
                      (lambda ()
                        (TeX-run-style-hooks "amsthm"))
                      :latex))

(defun with-auctex ()
  (load "auctex")
  (require 'hl-todo)
  (add-hook 'TeX-mode-hook #'hl-todo-mode)
  (add-hook 'TeX-mode-hook #'style-hook)  ;; Comment this line to get todo highlighting to work
)

(with-auctex)
(find-file "~/test.tex")
```

Start in doom vanilla sandbox with latex module in init file.
