### ISSUE TITLE
Fontset configuration in `config.el` gets overriden. No clear way how to make it work

### ISSUE THREAD

**Issue by guraltsev** [hlissner/doom-emacs#3298]
**What did you expect to happen?**
I expect `set-fontset-font` command to work in `config.el`

**What actually happened?**
It gets overriden (or ignored). However if you execute the `set-fontset-font` command as elisp after emacs has started, it does work!

**Steps to reproduce:**
Use the standard template `config.el`, `init.el`, and `package.el`.
Add 
```
(set-fontset-font "fontset-default" '(#x0400 . #x04FF) "Firacode NF" nil 'prepend)
```
that is supposed to set the default fontset for the Cyrillic characters to use `Firacode NF`.

Restart emacs

Open a scratch buffer and insert
```
 ;; Привет
```
Position your cursor on it the cyrillic characters and run `M-x describe-char`
Notice that a wrong font (FontAwesome) gets used.

Now insert 
```
(set-fontset-font "fontset-default" '(#x0400 . #x04FF) "Firacode NF" nil 'prepend)
```
select the line and type `(+eval/line-or-region)` and select `emacs`.
See that the font of the cyrillic text changes and works well. 

**System information:**
<details>

```
emacs   version    26.3
        features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS LCMS2
        build      Dec 25, 2019
        buildopts  (--without-compress-install --without-dbus --with-modules 'CFLAGS=-O2 -g3')
        windowsys  w32
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop, origin/develop, origin/HEAD
        dir        ~/.config/doom/
system  type       windows-nt
        config     x86_64-w64-mingw32
        shell      C:/bin/emax64-26.3/libexec/emacs/26.3/x86_64-w64-mingw32/cmdproxy.exe
        uname      n/a
        path       (c:/bin/ C:/Program Files (x86)/Common Files/Oracle/Java/javapath C:/Windows/system32 C:/Windows C:/Windows/System32/Wbem C:/Windows/System32/WindowsPowerShell/v1.0/ C:/Windows/System32/OpenSSH/ C:/ProgramData/chocolatey/bin C:/Program Files/Calibre2/ C:/Program Files (x86)/gnupg/bin C:/Program Files/TortoiseGit/bin C:/Program Files (x86)/ZeroTier/One/ C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common C:/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL C:/Program Files/Intel/Intel(R) Management Engine Components/DAL C:/Program Files/ImageMagick-7.0.10-Q16 C:/texlive/2020/bin/win32 C:/Program Files (x86)/Wolfram Research/WolframScript/ ~/AppData/Local/Microsoft/WindowsApps C:/tools/Cmder C:/Program Files/Oracle/VirtualBox ~/AppData/Local/Pandoc/ . c:/bin/emax64-26.3/libexec/emacs/26.3/x86_64-w64-mingw32)
config  envfile    nil
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline ophints (popup +defaults) vc-gutter vi-tilde-fringe workspaces :editor file-templates fold snippets :emacs dired electric undo vc :checkers syntax :tools (eval +overlay) lookup magit :lang emacs-lisp markdown org sh :config (default +bindings +smartparens))
        packages   (n/a)
        unpin      (n/a)
        elpa       (n/a)
```
</details>

**Comment by manikk** [comment]
Are there any work around for this?

**Comment by teu5us** [comment]
I used a hook for this. Now I'm using emacs 27.1 on NixOS and the hook works, unless I'm not using `emacs --daemon` to start emacs. When using daemon, `set-fontset-font` is ignored completely whenever I call it. If I run `emacs -Q --daemon` and open an emacsclient window, `set-fontset-font` works as it should.

**Comment by teu5us** [comment]
@guraltsev @manikk I have overriden `doom-init-fonts-h`, `doom-init-extra-fonts-h` and `doom/reload-font` to `(lambda () nil)` in autoload.el and put the following in my config.el:

```
(defvar used-font "monospace")
(defvar used-font-size 16)

(defun setup-cyrillic (frame)
  (with-selected-frame frame
    (set-fontset-font "fontset-default" 'windows-1251 used-font nil 'prepend))
  (remove-hook 'after-make-frame-functions #'setup-cyrillic))

(defun setup-fonts (frame)
  (with-selected-frame frame
    (set-frame-font (format "%s-%s" used-font used-font-size))))

(add-hook 'after-make-frame-functions #'setup-cyrillic)

(if (daemonp)
    (add-hook 'after-make-frame-functions #'setup-fonts)
  (progn
    (set-frame-font (format "%s-%s" used-font used-font-size))
    (add-hook 'after-make-frame-functions #'setup-fonts)))
```

Not sure that all the overrides were necessary (and I just don't use `doom/reload-font`, but that kind of fixed fonts for cyrillic characters for me. It works after the first frame with `emacs --daemon` and after the second with `emacs`

**Comment by hlissner** [comment]
Sorry for the late response. This issue slipped under my radar.

This is not a bug, this is a load order issue. `set-fontset-font` applies its changes _immediately_, and Doom applies its font settings late in the startup process (after your `config.el` is read). Any changes that aren't similarly deferred will be overwritten.

Getting around this is easy (and I highly recommend you don't overwrite `doom-init-fonts-h`/`doom-init-extra-fonts-h` unless you know what you're doing):

```lisp
;; All the "extra" fontset config Doom does happens at the end of 
;; `doom-load-theme-hook`, so appending your changes to it will work:
(add-hook! 'doom-load-theme-hook :append
  (set-fontset-font ...))
```

**Comment by hlissner** [comment]
Just a heads up, in e1c9145 `doom-init-extra-fonts-h` now triggers `after-setting-font-hook`, so you can now add your font config there instead:

```elisp
(add-hook! 'after-setting-font-hook
  (set-fontset-font ...))
```

**Comment by teu5us** [comment]
@hlissner Thank you for your response. Just reinstalled doom and tried adding `(set-fontset-font "fontset-default" 'windows-1251 "Anka/Coder" nil 'prepend)` to `'after-setting-font-hook`, which did not work out as well as `'doom-load-theme-hook`. The font used for cyrillic characters is still wrong

**Comment by teu5us** [comment]
Maybe this is relevant. Before overriding stuff, I tried just calling `(set-fontset-font...)` and `(set-frame-font...)`. It seemed to me that:

1. `set-fontset-font` has to be called first
2. another font (not already used by doom) has to be used in both cases

**Comment by hlissner** [comment]
Perhaps what you need is the `:ui unicode` module.

**Comment by teu5us** [comment]
@hlissner Now when I commented out `:ui unicode` I see the right font used

**Comment by hlissner** [comment]
Ah, that explains it. It is the culprit for your issues. The unicode module uses the [unicode-fonts](https://github.com/rolandwalker/unicode-fonts) package, which employs _a ton_ of fontset configurations on its own terms. If it's not doing what you want, best to disable it, than to wrestle with it. Unfortunately, it doesn't provide any hooks to bind customizations to, so you'd have to advise `unicode-fonts--setup-1`. e.g

```elisp
(defadvice! add-my-font-config (&rest _)
  :after #'unicode-fonts--setup-1
  (set-fontset-font ...))
```

In any case, disabling the `:ui unicode` module is the better option.

**Comment by teu5us** [comment]
I will stick to running doom without `:ui Unicode` but have to note that this is a new problem for me. Fonts were good in September
