### ISSUE TITLE
*Org Src not work (yet) in the new popup system

### ISSUE THREAD

**Issue by fuxialexander** [hlissner/doom-emacs#330]
### Observed behavior
![image](https://user-images.githubusercontent.com/8258908/34647143-631746a2-f3b5-11e7-9c98-0aea560636a5.png)
![image](https://user-images.githubusercontent.com/8258908/34647144-6c0625a8-f3b5-11e7-9d10-8f124ba012b9.png)
![image](https://user-images.githubusercontent.com/8258908/34647145-75d5244e-f3b5-11e7-9c62-f9cd95504c8f.png)

### Expected behavior
*Org Src buffer popup sanely and exit correctly.

### Steps to reproduce

0. Check value of `org-src-window-setup` (I tried `other-window / other-frame / current-window`)
1. Open any org-mode file
2. Insert a src code block
3. `C-c '` on block header and edit
4. `C-c C-c` / `C-c C-k` to exit [**Error**]: Edit buffer is not killed / buried. The code block in original buffer remains at editing state and cannot be modified.
5. Comment out `(set! :popup "^\\*" nil '((select . t)))` in popup/config.el and retry step 0-4. Turns our when `org-src-window-setup` is set to `other-frame` it can work.

### System information

<details>
<summary>Click to expand</summary>

```
DOOM Doctor
Running Emacs v27.0.50, commit fatal: Not a git repository (or any of the parent directories): .git

shell: /usr/local/bin/zsh
Compiled with:
  RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS
  MODULES LCMS2
uname -a:
  Darwin Xis-MacBook-Pro.local 17.3.0 Darwin Kernel Version 17.3.0: Thu
  Nov 9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64

Attempt to load DOOM: success! Loaded v2.0.9
Revision af58e321ddef7857f120b567228596bbef7ba699

----

test-emacs
test-windows
test-fonts
Found font material-design-icons.ttf
Found font weathericons.ttf
Found font octicons.ttf
Found font fontawesome.ttf
Found font file-icons.ttf
Found font all-the-icons.ttf
test-gnutls
test-tls
Validated https://elpa.gnu.org
Validated https://melpa.org
Successfully rejected https://self-signed.badssl.com
Successfully rejected https://wrong.host.badssl.com/
test-tar
Warning: BSD tar detected
  QUELPA (through package-build) uses the system tar to build plugins,
  but it expects GNU tar. BSD tar *could* cause errors during package
  installation or updating from non-ELPA sources. MacOS users can
  install gnu-tar via homebrew: brew install gnu-tar

----
There were issues!

Hopefully these can help you find problems. If not, run this doctor again with DEBUG=1:

  DEBUG=1 make doctor

And file a bug report with its output at https://github.com/hlissner/.emacs.d/issues

+ `M-x doom/info` (from inside Emacs)
```
</details>

**Comment by fuxialexander** [comment]
I guess you already aware of this issue, but anyway let me open it ;-)
I'll be glad to help if there is anything I can do 💪

**Comment by hlissner** [comment]
You are correct, I was aware of the issue. Org is the biggest hurdle for this module. That said, I've pushed a few fixes to `develop` to improve org compatibility, including a fix to your Org Src buffer woes. I'll keep this open until it hits `master`. Let me know if it gives you any trouble.

**Comment by fuxialexander** [comment]
It works fantastically! Thanks a lot for your effort!
