### ISSUE TITLE
+ivy-buffer-transformer is not compatible with ivy-use-virtual-buffers

### ISSUE THREAD

**Issue by dsdshcym** [hlissner/doom-emacs#331]
I used to use ivy-switch-buffer to switch to recent files (with `ivy-use-virtual-buffers` set to `t`)

But `+ivy-buffer-transformer` is not compatible with this setting.

Maybe we can use [ivy-rich](https://github.com/Yevgnen/ivy-rich) to replace `+ivy-buffer-transformer`? It's basically doing the same thing (if my understanding is correct).

**Comment by hlissner** [comment]
Yes, they are nearly the same, so I've brought ivy-rich to `develop` and built Doom's customizations on top of it, which fixes `ivy-use-virtual-buffer` compatibility.  I'll keep this open until it hits `master`

Doom simply greys out buffers that are special (`*Messages*`), virtual or in other projects.
