### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by drsnn** [hlissner/doom-emacs#3312]
hi 

i had gnu emacs. I decided to Install Doom-emacs on my mac. i installed it succesfully. 

```
 Successfully installed ‘all-the-icons’ fonts to ‘/Users/s___________n/Library/Fonts/’!
! A ~/.emacs file was detected. This conflicts with Doom and should be deleted!
✓ 
Finished! Doom is ready to go!

But before you doom yourself, here are some things you should know:

1. Don't forget to run 'doom sync', then restart Emacs, after modifying
   ~/.doom.d/init.el or ~/.doom.d/packages.el.

   This command ensures needed packages are installed, orphaned packages are
   removed, and your autoloads/cache files are up to date. When in doubt, run
   'doom sync'!

2. If something goes wrong, run `doom doctor`. It diagnoses common issues with
   your environment and setup, and may offer clues about what is wrong.

3. Use 'doom upgrade' to update Doom. Doing it any other way will require
   additional steps. Run 'doom help upgrade' to understand those extra steps.

4. Access Doom's documentation from within Emacs via 'SPC h D' or 'C-h D' (or
   'M-x doom/help')

Have fun!

✓ Finished! (533.6703s)
```

After I run emacs on my terminal 

it gives 

```UpdateRecents: about to call HIS_XPC_GetApplicationPolicyForURLs with seed 3936362071
UpdateRecents: received results from HIS_XPC_GetApplicationPolicyForURLs
UpdateRecents: ignoring results because menu isn't open
UpdateRecents: about to call HIS_XPC_GetApplicationPolicyForURLs with seed 3936362071
UpdateRecents: received results from HIS_XPC_GetApplicationPolicyForURLs
UpdateRecents: ignoring results because menu isn't open
UpdateRecents: about to call HIS_XPC_GetApplicationPolicyForURLs with seed 3936362071
UpdateRecents: received results from HIS_XPC_GetApplicationPolicyForURLs
UpdateRecents: ignoring results because menu isn't open
```
and open gnu emacs. it didnt open doom emacs. Could you help me. 

Thank you very much

**Comment by mreishus** [comment]
Note this in the command output you pasted:

```
! A ~/.emacs file was detected. This conflicts with Doom and should be deleted!
```

Try `mv ~/.emacs ~/.emacs.old`, then relaunch emacs.

**Comment by drsnn** [comment]
Hi i try your suggesstion but it didnt work. I try to reinstall it and i get this eror. Is there a way of refresh install?

´´´
___________________-Pro ~ % git clone https://github.com/hlissner/doom-emacs ~/.emacs.d
fatal: destination path '/Users/___________.emacs.d' already exists and is not an empty directory.
s________________o ~ % ~/.emacs.d/bin/doom install
dyld: Library not loaded: /usr/local/opt/jpeg/lib/libjpeg.9.dylib
  Referenced from: /usr/local/Cellar/emacs-plus/26.3/Emacs.app/Contents/MacOS/Emacs
  Reason: image not found
dyld: Library not loaded: /usr/local/opt/jpeg/lib/libjpeg.9.dylib
  Referenced from: /usr/local/Cellar/emacs-plus/26.3/Emacs.app/Contents/MacOS/Emacs
  Reason: image not found
/Users/_____________/.emacs.d/bin/doom: line 9: 11408 Abort trap: 6           $EMACS --no-site-file --script "$0" -- "$@"
s_________________o ~ % rm -rf ~/.emacs.d
s__________________o ~ % git clone https://github.com/hlissner/doom-emacs ~/.emacs.d
Cloning into '/Users/______________/.emacs.d'...
remote: Enumerating objects: 134, done.
remote: Counting objects: 100% (134/134), done.
remote: Compressing objects: 100% (104/104), done.
remote: Total 86914 (delta 60), reused 75 (delta 30), pack-reused 86780
Receiving objects: 100% (86914/86914), 21.20 MiB | 260.00 KiB/s, done.
Resolving deltas: 100% (61362/61362), done.
s___________________MacBook-Pro ~ % ~/.emacs.d/bin/doom install
dyld: Library not loaded: /usr/local/opt/jpeg/lib/libjpeg.9.dylib
  Referenced from: /usr/local/Cellar/emacs-plus/26.3/Emacs.app/Contents/MacOS/Emacs
  Reason: image not found
dyld: Library not loaded: /usr/local/opt/jpeg/lib/libjpeg.9.dylib
  Referenced from: /usr/local/Cellar/emacs-plus/26.3/Emacs.app/Contents/MacOS/Emacs
  Reason: image not found
/Users/_______________/.emacs.d/bin/doom: line 9: 11472 Abort trap: 6           $EMACS --no-site-file --script "$0" -- "$@"
s__________________________Pro ~ % 
´´´

**Comment by mreishus** [comment]
I think your general approach is fine.  You likely have another problem not related to doom going on, causing every command you run to error.  Check https://stackoverflow.com/questions/53828891/dyld-library-not-loaded-usr-local-opt-icu4c-lib-libicui18n-62-dylib-error-run

**Comment by drsnn** [comment]
Hi mreishus

I uninstall all brew apps. Then i update homebrew and reinstall it. And know it is working. Thank you very much.
