### ISSUE TITLE
[BUG]: Doom 2.0.9 indent guides cause my code to jump around like it's 1992

### ISSUE THREAD

**Issue by eccentric-j** [hlissner/doom-emacs#3320]
With the latest indent guides, especially if you are only showing the active guide, the new character seems to be changing the line height.

# Reproduction
1. Open up your config.el
2. Try configuring it as such:
    ```lisp
    (after! highlight-indent-guides
    (setq
        highlight-indent-guides-auto-enabled         nil
        highlight-indent-guides-responsive           'top
        highlight-indent-guides-delay                0
        highlight-indent-guides-highlighter-function 'j/active-guide)
    (custom-set-faces!
        '(highlight-indent-guides-top-character-face
        :foreground "#DE5356")))
    ```
3. Reload or restart emacs

## Expected
Only the active indent guide is shown, the text does not jump around depending on which lines are affected by the guide.

## Actual
Code gets real jumpy anytime the indent guide shows up, but unlike the 1992 classic ["Jump Around" by House of Pain](https://www.youtube.com/watch?v=XhzpxjuwZy0), this is a bit of a bummer.

![2020-06-07 02 53 29](https://user-images.githubusercontent.com/590297/83962494-e67adc80-a86b-11ea-97ef-f62960511d72.gif)

## Estimated Priority
🥘 4/10 - We should probably fix this?

## Environment
OS X Catalina (10.15)
Emacs 27 (emacs-plus)
Doom 2.0.9

## Workaround
```lisp
(setq highlight-indent-guides-character ?\x2502)
```

## Notes
- Experimented with changing the face :height, it makes it a bit better, no vertical jump but the horizontal jumping still exists.
- Is it a character width\height issue?
- Is there another character that could be fast but not mess with text layout?

**Comment by hlissner** [comment]
As of cc772ad this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

Side note: I appreciate the detailed, personal issue template -- it irks me to no end when folks ignore the one Doom provides -- but yours is missing your `M-x doom/info`. Please include it in future bug reports.

**Comment by eccentric-j** [comment]
@hlissner Thanks very much for fixing that. I apologize for not using your template. Your time is valuable too and we should be doing what we can to make it easier for you to provide support. 

Next time I will start with the template and add to it! 🚀
