### ISSUE TITLE
invalid relative line number when some lines folded in org-mode

### ISSUE THREAD

**Issue by wangggong** [hlissner/doom-emacs#3321]
**What did you expect to happen?**
1. `set relativenumber`;
2. Open a file with org-mode;
3. Write the following code:
```
* 1. xxx
** 1.1 xxx
** 1.2 xxx
** 1.3 xxx
* 2. xxx
** 2.1 xxx
** 2.2 xxx
** 2.3 xxx
```
4. Fold `1.`, line 2-4 folded.
5. Then `gg`, the line numbers like:
```
1 -> * 1. xxx...
4 -> * 2. xxx
5 -> ** 2.1 xxx
...
```
6. `3j`, we want to go to the line `* 2. xxx`.

**What actually happened?**

6. `3j`, we to go to the line `** 2.2 xxx`.

**Comment by hlissner** [comment]
Since Emacs 26.1, `display-line-numbers-type` supports `visual`, which is relative numbers, but numbered by screen line, rather than line number.

```elisp
(setq display-line-numbers-type 'visual)
```
