### ISSUE TITLE
smartparens f-string pairing is broken in python mode

### ISSUE THREAD

**Issue by betaprior** [hlissner/doom-emacs#3327]
**What did you expect to happen?**
When you type `f"` it should insert a closing quote to produce `f""`.  Likewise, this should work the same with Python triple quotes (`f"""` should give `f""""""`). This is the behavior in vanilla emacs w/ only smartparens loaded, Spacemacs, etc.

**What actually happened?**
No closing quote is inserted.

**Additional details:**
Note that this behavior is only with double quotes, `f'` and `f'''` give expected pairings <edit> I am actually also observing this with `f'` now.

This is, in principle, cosmetic, but f-strings are very common in modern Python code, and inconsistent pairing behavior between regular strings and f-strings is very aggravating.

The relevant `sp-pairs` entry for python-mode is different between vanilla emacs + smartparens, and doom: 
vanilla emacs: 
```
(:open "\"" :close "\"" :actions 
#6=(:add) :when #2# :unless #3# :pre-handlers #4# :post-handlers (:add sp-python-fix-tripple-quotes))
```
doom:
```
    (:open "\"" :close "\"" :actions
         (:add) :when (:add) :unless (:add) :pre-handlers (:add) :post-handlers (:add sp-python-fix-tripple-quotes))
```
Unfortunately I'm not able to locate any obvious parts in core editor config code that may be responsible for this misconfiguration.

![image](https://user-images.githubusercontent.com/338250/83987988-c3e1d580-a8f6-11ea-9145-77fa64d8a829.png)

**Comment by leoalekseyev** [comment]
This seems to be caused by the `unless-list` in `config/default/config.el` smartparens setup (or some other code there). Commenting it out and then loading smartparens defaults and `(require 'smartparens-python)` restores correct behavior. Not sure what the best fix is.  Temp workaround: ```
(after! python
  (sp-local-pair 'python-mode "f\"" "\"" :trigger "f\""))
```

**Comment by nbfalcon** [comment]
I found trigger to be unnecessary here; also, why the after! python block? AFAICS, smartparens doesn't eagerly load sp-local-pair modes.

Here is my snippet for completeness:
```emacs-lisp
;; HACK: fix python f-strings + smartparens
(after! smartparens
  (sp-local-pair '(python-mode) "f\"" "\"")
  (sp-local-pair '(python-mode) "f'" "'"))
```
(also includes single quotes)

**Comment by hlissner** [comment]
This issue should now be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

> why the after! python block?

It's a good idea to use `after!` to override any defaults that Doom's modules set, now or in the future.
