### ISSUE TITLE
unicode module ignores doom-font and doom-unicode-font

### ISSUE THREAD

**Issue by guraltsev** [hlissner/doom-emacs#3329]
**What did you expect to happen?**
`unicode-fonts` should try to use glyphs from `doom-font` or `doom-unicode-font` when building the fontset

Even though it is documented that `doom-unicode-font` gets ignored, this is not the appropriate behavior.  For now I get around this by putting this into my `config.el`
```
(setq doom-font (font-spec :family "FiraCode NF" :size 20)
      math-font (font-spec :family "DejaVu Math TeX Gyre" :size 20)
      doom-variable-pitch-font (font-spec :family "Segoe UI" :size 20))

(after! unicode-fonts
    (let ((doom-font-name (plist-get
                         (font-face-attributes doom-font) :family)))

    (dolist (unicode-fonts-fallback-font
             (list doom-font-name))
      (add-to-list 'unicode-fonts-fallback-font-list unicode-fonts-fallback-font))

    (dolist (unicode-block '("Cyrillic"
                             "Cyrillic Extended-A"
                             "Cyrillic Extended-B"
                             "Cyrillic Supplement"

                             "Greek Extended"
                             "Greek and Coptic"))
      (push doom-font-name (cadr (assoc unicode-block unicode-fonts-block-font-mapping))))

    ))
```

**What actually happened?**
The fonts to display unicode are completely unrelated to `doom-font` or `doom-unicode-font`

**Steps to reproduce:**
1. Use emacs26.3
2. enable `unicode` in init.el
3. add `(setq doom-font (font-spec :family "FiraCode NF" :size 20))` to config.el
4. start emacs
5. notice using `describe-char` that unicode symbols for Cyrillic get displayed by a working, but completely unrelated font (probably "consolas")

**System information:**
<details>

```
emacs   version    26.3
        features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS LCMS2
        build      Dec 25, 2019
        buildopts  (--without-compress-install --without-dbus --with-modules 'CFLAGS=-O2 -g3')
        windowsys  w32
        daemonp    daemon
doom    version    2.0.9
        build      HEAD -> develop, origin/develop, origin/HEAD
        dir        ~/.config/doom/
system  type       windows-nt
        config     x86_64-w64-mingw32
        shell      C:/bin/emax64-26.3/libexec/emacs/26.3/x86_64-w64-mingw32/cmdproxy.exe
        uname      n/a
        path       (c:/bin/ C:/Program Files (x86)/Common Files/Oracle/Java/javapath C:/Windows/system32 C:/Windows C:/Windows/System32/Wbem C:/Windows/System32/WindowsPowerShell/v1.0/ C:/Windows/System32/OpenSSH/ C:/ProgramData/chocolatey/bin C:/Program Files/Calibre2/ C:/Program Files (x86)/gnupg/bin C:/Program Files/TortoiseGit/bin C:/Program Files (x86)/ZeroTier/One/ C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common C:/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL C:/Program Files/Intel/Intel(R) Management Engine Components/DAL C:/Program Files/ImageMagick-7.0.10-Q16 C:/texlive/2020/bin/win32 C:/Program Files (x86)/Wolfram Research/WolframScript/ ~/AppData/Local/Microsoft/WindowsApps C:/tools/Cmder C:/Program Files/Oracle/VirtualBox ~/AppData/Local/Pandoc/ . c:/bin/emax64-26.3/libexec/emacs/26.3/x86_64-w64-mingw32)
config  envfile    nil
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard hl-todo modeline ophints (popup +defaults) pretty-code unicode vi-tilde-fringe window-select workspaces :editor file-templates fold snippets :emacs dired electric (undo +tree) vc :term eshell shell term vterm :checkers syntax :tools debugger (eval +overlay) lookup magit :lang emacs-lisp latex markdown org sh web :app calendar :config literate (default +bindings +smartparens))
        packages   ((solarized-theme) (selected) (doom-snippets :ignore t))
        unpin      (n/a)
        elpa       (n/a)
```
</details>

**Comment by guraltsev** [comment]
I am a bit confused about the specifics of `unicode-fonts` package but setting `unicode-fonts-fallback-font-list` in my snippet above seemingly has no bearing.

However the pushing of `doom-font-name` into the corresponding places of `unicode-fonts-block-font-mapping` seems to be the correct thing to do. 
I explicitly enumerate the blocks but I think one should just iterate over `unicode-fonts-blocks`. The package `unicode-fonts` should figure out if some glyphs are not supported. 

@hlissner  If you give me the ok. I can prepare a pull request that pushes the font name into `unicode-fonts-block-font-mapping` and add some documentation to the module. Do we want to use `doom-font` or `doom-unicode-font`?

**Comment by hlissner** [comment]
> If you give me the ok I can prepare a pull request that pushes the font name into unicode-fonts-block-font-mapping and add some documentation to the module. Do we want to use doom-font or doom-unicode-font?

Sure. I'd prefer it use `doom-unicode-font`, since that is its purpose.
