### ISSUE TITLE
What's doom

### ISSUE THREAD

**Issue by FirstLoveLife** [hlissner/doom-emacs#3337]
I have to switch `emacs -nw` recently and found hl-line-mode is annoying in terminal. Does doom provide modle/flag to provide? I find global-hl-line-mode is nil already.

**Comment by hlissner** [comment]
See https://github.com/hlissner/doom-emacs/blob/develop/core/core-ui.el#L428.

Disable with:

```elisp
(remove-hook! (prog-mode text-mode conf-mode special-mode) #'hl-line-mode)
```

Please ask usage/config questions on [our Discord](https://discord.gg/qvGgnVx). Our issue tracker is not the correct place to ask these questions. This will be deleted shortly.
