### ISSUE TITLE
doom/kill-this-buffer renamed?

### ISSUE THREAD

**Issue by zeronone** [hlissner/doom-emacs#334]
### Observed behavior

`develop` branch.

`SPC b k` is bound to `doom/kill-this-buffer` but it seemed to be renamed to `doom/kill-this-buffer-in-all-windows`. All occurrences should be replaced (?)

**Comment by hlissner** [comment]
Whoops! I missed that one. Fix is now live in `develop`. I'll keep this open until it hits `master`.
