### ISSUE TITLE
Every time I run doom/reload in emacs, it reports an error in pretty-code module.

### ISSUE THREAD

**Issue by h0cheung** [hlissner/doom-emacs#3343]
**What did you expect to happen?**
It should reload normally.

**What actually happened?**
It reports `let*: Error in a Doom module: "modules/ui/pretty-code/config.el", (error "At
tempt to make a chartable be its own parent") `

**Additional details:**
Emacs 28.0.50
pretty-code without any flags

**Steps to reproduce:**
Just run `doom/reload` after editing a config file.

**System information:**
<details><pre>
((emacs
  (version . "28.0.50")
  (features . "XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER LCMS2 GMP")
  (build . "6月 09, 2020")
  (buildopts "--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --mandir=/usr/share/man --with-gameuser=:games --with-sound=alsa --with-modules --without-gconf --without-gsettings --enable-autodepend --enable-link-time-optimization --with-x-toolkit=gtk3 --without-xaw3d --with-xwidgets --without-compress-install 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -flto' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O2,--sort-common,--as-needed,-z,relro,-z,now")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "grafted, HEAD -> develop, origin/develop, origin/HEAD dd8b535e 2020-06-08 01:39:49 -0400")
  (dir . "~/.doom.d/"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/usr/bin/xonsh")
  (uname . "Linux 5.6.15-zen2-1-froidzen #1 ZEN SMP PREEMPT Fri, 29 May 2020 09:46:52 +0000 x86_64")
  (path "/usr/local/sbin" "/usr/local/bin" "/usr/bin" "/opt/cxoffice/bin" "/var/lib/flatpak/exports/bin" "/usr/lib/jvm/default/bin" "/usr/bin/site_perl" "/usr/bin/vendor_perl" "/usr/bin/core_perl" "~/.local/bin" "/opt/android-sdk/platform-tools/" "~/.emacs.d/bin/" "~/bin" "/usr/lib/emacs/28.0.50/x86_64-pc-linux-gnu"))
 (config
  (envfile)
  (elc-files . 0)
  (modules :input chinese :completion (company +childframe) (ivy +childframe) :ui doom doom-dashboard doom-quit hl-todo modeline ophints (popup +defaults) pretty-code unicode vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold snippets :emacs dired electric undo vc :term eshell vterm :checkers syntax :tools debugger (eval +overlay) lookup lsp magit :lang (cc +lsp) emacs-lisp markdown org sh :config literate (default +bindings +smartparens))
  (packages (masm-mode) (google-c-style :recipe (:host github :repo "google/styleguide" :files ("google-c-style.el") :branch "gh-pages")))
  (unpin "n/a")
  (elpa "n/a")))
</pre></details>

**Comment by gagbo** [comment]
Reason : it's because the command that sets the parent table cannot be run twice in the same environment basically. No idea how to fix it right now though

**Comment by hlissner** [comment]
As of 5f3bfa1 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
