### ISSUE TITLE
evil-easymotion not being initialized ?

### ISSUE THREAD

**Issue by zeronone** [hlissner/doom-emacs#335]
### Observed behavior

In `develop` branch.

It seems that `evilem-default-keybindings` is not being run. Also the keybinding `SPC /` seems to be in conflict. I guess `SPC j` would be more suitable (?)

~I added `evilem-default-keybindings` to `def-package!` for `evil-easymotion` and also changed the keybinding prefix to `SPC j` in `modules/default`.~

Adding `:demand t` to `evil-easymotion` worked. Is there any way, I could override the `def-package` with `:demand t` in my user settings?

**Comment by hlissner** [comment]
Not simply, but this is definitely a bug, caused because I haven't lazy-loaded evil-easymotion properly. I'll look into this this weekend.

**Comment by hlissner** [comment]
And done! The fix is now in `develop`. I'll keep this open until it hits `master`.
