### ISSUE TITLE
Impossible to toggle flyspell in `notmuch-message-mode` buffers

### ISSUE THREAD

**Issue by brabalan** [hlissner/doom-emacs#3357]
**What did you expect to happen?**
Toggling flyspell using `SPC t s` would turn it on and off in `notmuch-message-mode` buffers.

**What actually happened?**
Flyspell starts off and remains off after toggling it, with the message `Flyspell mode disabled in current buffer`.

**System information:**
<details><pre>
emacs   version    26.3
        features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2
        build      May 19, 2020
        buildopts  (--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-wide-int --with-modules 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now)
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop 6a85abc9d 2020-06-10 03:01:27 -0400
        dir        ~/.doom.d/
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/zsh
        uname      Linux 5.6.15-arch1-1 #1 SMP PREEMPT Wed, 27 May 2020 23:42:26 +0000 x86_64
        path       (bin/../bin ~/.opam/why3/bin ~/bin ~/go/bin ~/.opam/why3/bin ~/bin ~/go/bin /usr/local/sbin /usr/local/bin /usr/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /usr/lib/emacs/26.3/x86_64-pc-linux-gnu/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion (company +childframe) (ivy +icons) :ui deft doom doom-dashboard doom-quit hl-todo modeline ophints (popup +defaults) vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold multiple-cursors snippets :emacs (dired +icons) electric undo vc :term eshell :checkers syntax spell :tools (eval +overlay) lookup magit make pass pdf :lang coq data emacs-lisp javascript latex ledger lua markdown ocaml (org +gnuplot +roam) sh :email notmuch :app irc (rss +org) :config literate (default +bindings +smartparens))
        packages   ((ebdb) (emojify) (org-review) (org-noter) (xah-replace-pairs) (org-ref) (gnuplot) (ts) (magit-todos :disable t) (elpher) (org-roam-bibtex) (org-roam-server) (org-journal) (leuven-theme) (unicode-fonts) (xah-math-input) (calfw) (calfw-ical))
        unpin      (n/a)
        elpa       (n/a)
</pre></details>

**Comment by Ban3** [comment]
https://github.com/rolandwalker/flyspell-lazy/issues/9

**Comment by brabalan** [comment]
I "fixed it" this way:
```emacs-lisp
(after! notmuch
  (add-hook 'notmuch-message-mode-hook (lambda () (let ((flyspell-lazy-disallow-buffers nil)) (turn-on-flyspell)))))
```

**Comment by brabalan** [comment]
This issue is still relevant. I fix it by having
```emacs-lisp
(after! notmuch (setq flyspell-lazy-disallow-buffers nil))
```
in my configuration.

**Comment by hlissner** [comment]
Sorry for the tremendously late response, but does this fix the issue for you:

```elisp
(setq-hook! 'message-mode-hook flyspell-lazy-disallow-buffers nil)
```

**Comment by brabalan** [comment]
I’ve been using
```emacs-lisp
(after! notmuch (setq flyspell-lazy-disallow-buffers nil))
```
I confirm your suggestion works as well.

(And no worry for the delay, thank you so much for your time growing doom.)

**Comment by brabalan** [comment]
It works, thanks!
