### ISSUE TITLE
lsp-metals moved out of lsp-mode

### ISSUE THREAD

**Issue by gregghz** [hlissner/doom-emacs#3362]
**What did you expect to happen?**

lsp started correctly

**What actually happened?**

Attempting to start lsp for a scala project fails because lsp-metals was moved from lsp-mode to it's own repo.

**Additional details:**

Adding `(package! lsp-metals)` to packages.el and `(use-package! lsp-metals)` to config.el restores lsp for scala (I don't actually know if the use-package is required).

It was removed from lsp-mode here: https://github.com/emacs-lsp/lsp-mode/pull/1762

**Steps to reproduce:**
1. Open a scala project
2. Note that lsp fails to start

**System information:**
<details><pre>
emacs   version    27.0.90
        features   RSVG IMAGEMAGICK GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS JSON PDUMPER LCMS2 GMP
        build      Apr 08, 2020
        buildopts  (--disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus/HEAD-18d1bc0/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus/HEAD-18d1bc0 --with-xml2 --without-dbus --with-gnutls --with-imagemagick --with-json --with-modules --with-rsvg --with-ns --disable-ns-self-contained)
        windowsys  ns
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop 9edd4f26f 2020-06-11 04:49:31 -0400
        dir        ~/.doom.d/
system  type       darwin
        config     x86_64-apple-darwin18.7.0
        shell      /usr/local/bin/zsh
        uname      Darwin 18.7.0 Darwin Kernel Version 18.7.0: Sun Dec  1 18:59:03 PST 2019; root:xnu-4903.278.19~1/RELEASE_X86_64 x86_64
        path       (/usr/local/opt/emacs-plus/bin /usr/bin /bin /usr/sbin /sbin /usr/local/bin ~/Library/Python/3.6/bin ~/bin ~/workspace/scratch/bin ~/.local/bin ~/.emacs.d/bin ~/Library/Android/sdk/emulator ~/Library/Android/sdk/tools ~/Library/Android/sdk/tools/bin ~/Library/Android/sdk/platform-tools /Applications/Dash.app/Contents/MacOS ~/Library/Application Support/Coursier/bin /usr/local/Cellar/emacs-plus/HEAD-18d1bc0/libexec/emacs/27.0.90/x86_64-apple-darwin18.7.0/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company (ivy +childframe +icons +prescient +fuzzy) :ui doom doom-dashboard doom-quit hl-todo hydra modeline nav-flash ophints (popup +defaults) treemacs vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold format multiple-cursors rotate-text snippets word-wrap :emacs (dired +icons +ranger) electric (ibuffer +icons) vc undo :checkers syntax :tools debugger (docker +lsp) (eval +overlay) (lookup +docsets) (lsp +peek) macos magit pdf :lang csharp data emacs-lisp (json +lsp) (java +lsp) (javascript +lsp) (markdown +grip) (org +dragndrop +hugo +present +journal +noter) (python +lsp) (scala +lsp) (sh +lsp) web (yaml +lsp) :config (default +bindings +smartparens))
        packages   ((restclient) (lsp-treemacs) (magit-todos) (shader-mode) (lsp-metals))
        unpin      (n/a)
        elpa       (n/a)
</pre></details>

**Comment by wedens** [comment]
I wonder why they extracted it into separate package. And with a treemacs dependency :/

**Comment by wedens** [comment]
https://github.com/emacs-lsp/lsp-metals/issues/5#issuecomment-641257469

Seems like adding more dependencies was indeed the motivation for moving it out of lsp-mode itself :disappointed:

**Comment by kurnevsky** [comment]
@wedens what's wrong with adding more dependencies to implement metals extension? We have other packages that do the same:

**Comment by wedens** [comment]
@kurnevsky IMHO, it makes the package bloated and unmodular. I don't use lsp-reemacs/treemacs, dap-mode, but I'll have to pull those dependencies just to use basic lsp-metals features.

I think it'd be better to have a basic package `lsp-metals` and extension packages like `lsp-metals-dap`, `lsp-metals-treeview`.

**Comment by kurnevsky** [comment]
It makes things harder to implement and use. See https://github.com/emacs-lsp/lsp-treemacs/blob/bf054531c278c5d41de504bec3c3df3f2e76c132/lsp-metals-treeview.el#L811 for example - we had to patch metals client definition from lsp-treemacs to add treeview capability and notification handler. And this means that if treeview is enabled after `lsp-mode` is activated it won't work. Also we had questions from users about metals lenses - they don't work without dap-mode installation. That's why `lsp-metals` was moved to a separate package with these dependencies - it is a fault of the package for not having the correct dependency chain.

**Comment by logc** [comment]
Thanks for the detailed discussion! I just noticed the missing LSP on opening a Scala project. 

I went with the solution proposed in the issue description (add `lsp-metals` as an extra package) but of course, it would be cleaner to have it as part of the Scala module ...
