### ISSUE TITLE
Having trouble opening popup windows

### ISSUE THREAD

**Issue by StanimirKolev** [hlissner/doom-emacs#3369]
Just installed Doom. When I try SPC o t to open a terminal it doesn't work, SPC o n to open Neotree still doesn't work. Am I missing something? My version is 2.0.9

**Comment by hlissner** [comment]
I'm going to guess that "doesn't work" means you get `commandp` errors. In which case, it means you haven't enabled any of Doom's `:term` modules, or the `:ui neotree` module.

See [how to enable modules](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#modules)

Side-note: please do not ignore the issue template in the future.

**Comment by StanimirKolev** [comment]
Enabling the modules solved my problem. Sorry for the stupid question.
