### ISSUE TITLE
[REQUEST] provide an option to toggle vterm pop-up window even when displayed

### ISSUE THREAD

**Issue by betaprior** [hlissner/doom-emacs#3374]
**Describe the feature**
Currently, if vterm pop-up invoked via `SPC o t` is displayed, but another buffer is selected, a subsequent invocation of `SPC o t` selects the vterm buffer. This is a sensible default behavior, however for certain usage patterns it is inconvenient. Consider, for example, the case of tailing a log file, or issuing an ad hoc command in the terminal, going back to the code buffer, and realizing the terminal is not needed anymore and wanting to dismiss it.

The current behavior, moreover, is somewhat unexpected because a command with "toggle" in its name is expected to indeed toggle some feature consistently on subsequent invocations.

Furthermore, it is quite easy to select the vterm buffer, if so desired, via user's preferred window selection commands.  An option to always hide the vterm pop-up if already displayed using the same keybinding used to show it would provide substantially improved UX over having to think about whether or not the buffer is selected, whether or not one should be using the `o t` binding or `~` binding, etc.

**Comment by leoalekseyev** [comment]
See https://github.com/hlissner/doom-emacs/pull/3375
