### ISSUE TITLE
Prevent Emacs from changing "~/.emacs.d/init.el", write changes to "~/.doom.d/config.el" instead

### ISSUE THREAD

**Issue by mrbig033** [hlissner/doom-emacs#3379]
**Describe the feature**

I noticed that when I activate a disabled command such as `scroll-left` by hitting
`<C-next>` followed by `y` to enable it permanently, Emacs will write the setting `(put 'scroll-left 'disabled nil)`to `~/.emacs.d/init.el`. This generates an error when I run `doom upgrade` regarding changes to this file that must be discarded. I believe these changes should be automatically written to `~/.doom.d/config.el` instead.

`doom doctor` is unable to detect this issue, maybe it would be a good idea for it to warn about these changes.

**System information**
<details><pre>
((emacs
  (version . "27.0.91")
  (features . "RSVG IMAGEMAGICK GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS JSON PDUMPER LCMS2 GMP")
  (build . "May 14, 2020")
  (buildopts "--disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus/HEAD-747e0a2/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus/HEAD-747e0a2 --with-xml2 --without-dbus --with-gnutls --with-imagemagick --with-json --with-modules --with-rsvg --with-ns --disable-ns-self-contained")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop 0f3bd5710 2020-06-13 03:03:11 -0400")
  (dir . "~/.doom.d/"))
 (system
  (type . darwin)
  (config . "x86_64-apple-darwin18.7.0")
  (shell . "/usr/local/bin/bash")
  (uname . "Darwin 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64")
  (path "/usr/local/opt/openjdk/bin" "~/.pyenv/shims" "~/.pyenv/bin" "~/.local/bin" "~/.emacs.d/bin" "~/scripts/bin" "~/.nimble/bin" "~/scripts/cline_scripts/" "~/.emacs.d/bin" "/usr/local/opt/sqlite/bin" "/usr/local/bin" "/usr/bin" "/bin" "/usr/sbin" "/sbin" "/Library/TeX/texbin" "/opt/X11/bin" "/Library/Frameworks/Mono.framework/Versions/Current/Commands" "~" "~/.fzf/bin" "/usr/local/Cellar/emacs-plus/HEAD-747e0a2/libexec/emacs/27.0.91/x86_64-apple-darwin18.7.0"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company (ivy +fuzzy +prescient) :ui doom modeline (popup +defaults) treemacs :editor (evil +everywhere) fold multiple-cursors snippets word-wrap :emacs (dired +ranger +icons) electric undo vc :term eshell shell :checkers syntax spell grammar :tools (eval +overlay) (lookup +dictionary +offline) magit pdf :lang emacs-lisp markdown (org +roam) sh :app irc :config (default +bindings +smartparens))
  (packages (nswbuff) (org-pomodoro) (nswbuff) (olivetti) (super-save) (eyebrowse) (elpy) (clipmon) (evil-god-state) (unkillable-scratch) (yafolding) (recursive-narrow) (git-auto-commit-mode) (electric-operator) (evil-swap-keys) (evil-god-state) (evil-smartparens) (eyebrowse) (shut-up) (super-save) (evil-better-visual-line) (apheleia :recipe (:host github :repo "raxod502/apheleia")) (evil-snipe :disable t))
  (unpin "n/a")
  (elpa "n/a")))
</pre></details>

**Comment by hlissner** [comment]
As of 1d709e3 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by mrbig033** [comment]
Thanks! Will `doom upgrade` pick up thins change already?

**Comment by hlissner** [comment]
Yup!
