### ISSUE TITLE
Finally! An Emacs icon as gnarly as Doom

### ISSUE THREAD

**Issue by eccentric-j** [hlissner/doom-emacs#3382]
Wanting something other than the Spacemacs icon that came with emacs-plus and the more generic-looking purple one, I wanted something a bit more fun and wild.

![Screen Shot 2020-06-13 at 9 08 58 PM](https://user-images.githubusercontent.com/590297/84582470-6815c180-adba-11ea-92d1-8c8681b16aa0.png)

![doom](https://user-images.githubusercontent.com/590297/84582475-795ece00-adba-11ea-9aa1-a62c308746ec.png)

[doom.icns.zip](https://github.com/hlissner/doom-emacs/files/4775711/doom.icns.zip)

The goal would be to submit a PR to emacs-plus as a `--with-doom-icon` option. 

Progress\versions can be tracked at https://github.com/eccentric-j/doom-icon

Anyway, I hope someone out there enjoys it!

**Comment by eccentric-j** [comment]
![icon_512x512@2](https://user-images.githubusercontent.com/590297/85930281-0d379c00-b889-11ea-9eb8-6f7b816b6c4a.png)

It was requested to match the original style of the image on the README. I had reached out to the original artist to ask permission to use my vectorized version but I have yet to hear from them. Instead, I made a few changes to help differentiate it from their original work so we should be able to use it more freely.

**Comment by eccentric-j** [comment]
The iconsets of both can be downloaded here https://github.com/eccentric-j/doom-icon/releases/download/0.0.2/doom-icons-0.0.2.zip

**Comment by tam5** [comment]
sorry for the spam, but i just have to say this is awesome!!

**Comment by eccentric-j** [comment]
@tam5 Thanks. I appreciate the feedback!

**Comment by elken** [comment]
@eccentric-j this icon is pretty cool, I even used it to make a [banner](https://github.com/elken/.doom.d/blob/master/banner.png)

**Comment by pkazmier** [comment]
Me too! This icon is awesome!

<img width="904" alt="image" src="https://user-images.githubusercontent.com/747855/95658277-cb9ccb00-0ade-11eb-975b-21922abe5690.png">

**Comment by iwahbe** [comment]
I love this. @eccentric-j are you still planning to open a PR for emacs-plus? I would be happy to initiate this if you don't want to.

**Comment by eccentric-j** [comment]
@iwahbe I appreciate that offer but I don't feel it should be done without @hlissner's blessing 🤔

**Comment by rivpyl-sidfyl** [comment]
Hey there. These are lovely.
I just started learning doom, and am not familiar with github publishing, but I've also made a little icon for the app.

![doom](https://user-images.githubusercontent.com/63191757/107875047-8c7bed80-6eb5-11eb-92b0-5580b2a4ec51.png)

<img width="397" alt="screenshot" src="https://user-images.githubusercontent.com/63191757/107875112-f1374800-6eb5-11eb-8fdc-2fe7d27dd755.png">

Hope you guys like it, there's .png, .ico and .icns versions in this zip:

[doom emacs icons.zip](https://github.com/hlissner/doom-emacs/files/5977604/doom.emacs.icons.zip)
