### ISSUE TITLE
TAB key mangles text while indenting when editing CSS files

### ISSUE THREAD

**Issue by exp2ipi** [hlissner/doom-emacs#3383]
**What did you expect to happen?**
`TAB` to indent the current line

**What actually happened?**
The line got indented, but garbage got inserted at point

**Discussion:**
Clearly `(+web/indent-or-yas-or-emmet-expand)` is not doing the right thing here. In general, I find that `TAB` is often bound to expand functionality that is either buggy, like in this case, or contextually inappropriate (for example, what's the use case of `TAB` being bound to yas-expand in visual mode? But it certainly breaks the expected emacs behavior of being able to select a few lines with visual-line-mode and indent at once with TAB)

**System information:**
<details><pre>
<details>

```
emacs   version    27.0.91
        features   XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP
        build      Jun 08, 2020
        buildopts  (--with-sound=alsa --without-gconf --with-mailutils --with-json --with-modules --prefix=/usr/local)
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop eece81118 2020-06-13 18:48:34 -0700
        dir        ~/.emacs.d.custom/doom.d/
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/bash
        uname      Linux 5.4.0-37-generic #41-Ubuntu SMP Wed Jun 3 18:57:02 UTC 2020 x86_64
        path       (~/bin ~/opt/miniconda3/bin ~/opt/miniconda3/condabin /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /usr/games /usr/local/games /snap/bin /usr/local/go/bin ~/go/bin ~/bin-local ~/opt/android-studio/bin ~/opt/android/sdk/platform-tools ~/.rvm/bin ~/go/src/github.com/hyperledger/fabric-ca/bin ~/.fzf/bin ~/bin-local ~/opt/android-studio/bin ~/opt/android/sdk/platform-tools /usr/local/libexec/emacs/27.0.91/x86_64-pc-linux-gnu/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +defaults) treemacs vc-gutter vi-tilde-fringe (window-select +numbers) zen :editor (evil +everywhere) file-templates fold multiple-cursors snippets :emacs dired electric (ibuffer +ibuffer-projectile) undo vc :term eshell vterm :checkers syntax :tools ein (eval +overlay) (lookup +docsets) (lsp +peek) (magit +forge) pdf tmux :lang emacs-lisp (go +lsp) json javascript markdown (org +ipython +roam) (python +lsp +conda) scheme sh web yaml :app irc :config (default +bindings +smartparens))
        packages   ((flycheck-mypy) (dired-single) (openwith) (vterm-extra :recipe (:host github :repo Sbozzolo/vterm-extra)) (vterm-toggle) (centered-cursor-mode) (helpful :disable t))
        unpin      (n/a)
        elpa       (n/a)
```
</details>
</pre></details>

![css-tab-bug](https://user-images.githubusercontent.com/338250/84584845-1a02bd00-adbe-11ea-8bae-8e615a52f303.gif)

**Comment by hlissner** [comment]
> what's the use case of TAB being bound to yas-expand in visual mode?

To expand a snippet on a selection. e.g. select all three lines in visual line mode:

```elisp
(message "hello world")
(message "hello world")
(message "hello world")
```

Then `TAB` -> select `when` snippet, and you get:

```elisp
(when t
  (message "hello world")
  (message "hello world")
  (message "hello world"))
```

> But it certainly breaks the expected emacs behavior of being able to select a few lines with visual-line-mode and indent at once with TAB

The canonical vim/evil way to reindent lines is with the `=` operator. Select those lines and `=` will do the same. Or `>`/`<` if you want to shift indentation forward/backward.

> Clearly (+web/indent-or-yas-or-emmet-expand) is not doing the right thing here.

It seems to me like it's doing the right thing, but is being called in the wrong place. It will indent the line if the cursor is at BOL or in the indentation, otherwise expand the text at point as if it's a (emmet) snippet. It's not producing the right result because the emmet expression is invalid (garbage in, garbage out).

-----

I'll see if there is a better way to reign in emmet-mode.

**Comment by rassie** [comment]
I'm having a very similar problem, which might not be a bug, but something I'd definitely consider wrong do-what-I-mean behaviour in `typescript-mode`. Hopefully, the following GIF is clear enough: 

![Peek 2020-09-02 09-15](https://user-images.githubusercontent.com/23448/91943472-ef5d3c00-ecfc-11ea-981b-4b055ff45d30.gif)

I suppose for some people that's a feature, but I'd like my TAB key to indent the line and not get smart about inserting invalid tags. It'd be nice if there were some way to disable this behaviour.

**Comment by hlissner** [comment]
With 7e565f1 emmet/snippet expansion is restricted to word boundaries (so you won't see expansion in the middle of a tag, for instance). Anywhere else, it will invoke indentation. 

With that I'll consider this issue fixed. Let me know if that's not the case and I'll reopen the issue. Thanks for bringing it to my attention.
