### ISSUE TITLE
Language Servers hanging over TRAMP

### ISSUE THREAD

**Issue by mjlbach** [hlissner/doom-emacs#3390]
**What did you expect to happen?**
mspyls and pyright seem to work fine locally, but hang the process when connected via tramp.

See: https://github.com/emacs-lsp/lsp-mode/issues/1741

**What actually happened?**
Tramp hangs indefinitely, language server refuses to start (even if manually invoking the binary via ielm over TRAMP)

**Steps to reproduce:**
1. Connect to server via TRAMP with (python +lsp) enabled
2. Open python file (observe hang)

The following patch seems to fix it, but this messes with doom's lazy initialization

```diff
diff --git a/modules/lang/python/config.el b/modules/lang/python/config.el
index 662c92bd0..875abd26f 100644
--- a/modules/lang/python/config.el
+++ b/modules/lang/python/config.el
@@ -292,10 +292,13 @@ called.")
 
 (use-package! lsp-python-ms
   :when (and (featurep! +lsp) (not (featurep! :tools lsp +eglot)))
-  :after lsp-clients
-  :preface
-  (after! python
-    (setq lsp-python-ms-python-executable-cmd python-shell-interpreter))
+  :hook (python-mode . (lambda ()
+                           (require 'lsp-python-ms)
+                           (lsp)))  ; or lsp-deferred
+  ; :after lsp-clients
+  ;  :preface
+  ;   (after! python
+  ;     (setq lsp-python-ms-python-executable-cmd python-shell-interpreter))
   :init
   ;; HACK If you don't have python installed, then opening python buffers with
   ;;      this on causes a "wrong number of arguments: nil 0" error, because of
 ```
The hook seems to be necessary.

I've reproduced this on 27/28 on mac and linux.

When called with :after python, the highlight callbacks stops working. 

**System information:**
<details><pre>
((emacs
  (version . "28.0.50")
  (features . "XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND DBUS GSETTINGS GLIB NOTIFY INOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER GMP")
  (build . "Jun 14, 2020")
  (buildopts "--prefix=/nix/store/6nqkxy8qwnpnsfqwzxnm75yar9b4gcgg-emacs-gcc-20200613.0 --disable-build-details --with-modules --with-x-toolkit=gtk3 --with-xft --with-nativecomp CFLAGS=-DMAC_OS_X_VERSION_MAX_ALLOWED=101200")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> native-comp be77d396e 2020-06-13 18:24:20 -0700")
  (dir . "~/.dotfiles/emacs/.doom.d/"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/usr/bin/zsh")
  (uname . "Linux 5.6.16-300.fc32.x86_64 #1 SMP Thu Jun 4 18:08:38 UTC 2020 x86_64")
  (path "/nix/store/sy9j14vl5prlh0509n926cx8q3p5ckg5-emacs-packages-deps/bin" "~/.nix-profile/bin" "~/.emacs.d/bin" "~/.poetry/bin" "/usr/share/Modules/bin" "/usr/local/bin" "/usr/local/sbin" "/usr/bin" "/usr/sbin" "~/n/bin" "~/bin" "~/.dotnet/tools" "~/.fzf/bin" "~/.zsh/plugins/powerlevel10k" "/nix/store/6nqkxy8qwnpnsfqwzxnm75yar9b4gcgg-emacs-gcc-20200613.0/libexec/emacs/28.0.50/x86_64-pc-linux-gnu"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline ophints (popup +defaults) vc-gutter vi-tilde-fringe window-select workspaces zen :editor (evil +everywhere) file-templates fold format multiple-cursors rotate-text snippets word-wrap :emacs dired electric undo vc :term vterm :checkers syntax :tools direnv (eval +overlay) lookup lsp macos magit :lang cc data emacs-lisp julia lua markdown nix org (python +lsp +poetry) sh :email (mu4e +gmail) :config (default +bindings +smartparens))
  (packages (nose :disable :t) (lsp-python-ms :pin "db6f2636da1037bda06d5a2d992c4857ce3ad9b0"))
  (unpin "n/a")
  (elpa "vterm")))

</pre></details>

**Comment by sggutier** [comment]
I have a very similar problem, but I use php instead.

In my config I have:
``` elisp
(after! lsp-mode  
  (lsp-register-client
   (make-lsp-client :new-connection (lsp-tramp-connection '("intelephense" "--stdio"))
                    :major-modes '(php-mode)
                    :remote? t
                    :priority -1
                    :notification-handlers (ht ("indexingStarted" #'ignore)
                                               ("indexingEnded" #'ignore))
                    :initialization-options (lambda ()
                                              (list :storagePath lsp-intelephense-storage-path
                                                    :licenceKey lsp-intelephense-licence-key
                                                    :clearCache lsp-intelephense-clear-cache))
                    :multi-root lsp-intelephense-multi-root
                    :completion-in-comments? t
                    :server-id 'iph-remote))
  )
```
I fixed it by modifying `modules/lang/php/config.el` (inspired by your solution) :
``` 
@@ -23,7 +23,8 @@
   (set-formatter! 'php-mode #'php-cs-fixer-fix)
 
   (if (featurep! +lsp)
-      (add-hook 'php-mode-local-vars-hook #'lsp!)
+      ;; (add-hook 'php-mode-local-vars-hook #'lsp!)
+      (add-hook 'php-mode-hook #'lsp)
     ;; `+php-company-backend' uses `company-phpactor', `php-extras-company' or
     ;; `company-dabbrev-code', in that order.
     (when +php--company-backends
```

**Comment by mjlbach** [comment]
The following init.el shows how you can use the a language server remotely. For some reason it hangs with doom, but not with this.
```elisp
(setq user-emacs-directory "~/.debug.emacs.d/")

(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(setq straight-use-package-by-default t)
(straight-use-package 'evil)
(straight-use-package 'ivy)
(straight-use-package 'lsp-mode)
(straight-use-package 'counsel)
(straight-use-package
 '(lsp-pyright :type git :host github :repo "emacs-lsp/lsp-pyright"))

(setq lsp-log-io t)
(setq lsp-pyright-use-library-code-for-types t)
(setq lsp-pyright-diagnostic-mode "workspace")

(require 'evil)
(evil-mode 1)

(require 'ivy)
(ivy-mode 1)
(setq ivy-use-virtual-buffers t)
(setq enable-recursive-minibuffers t)
(global-set-key "\C-s" 'swiper)
(global-set-key (kbd "C-c C-r") 'ivy-resume)
(global-set-key (kbd "<f6>") 'ivy-resume)
(global-set-key (kbd "M-x") 'counsel-M-x)
(global-set-key (kbd "C-x C-f") 'counsel-find-file)
(global-set-key (kbd "<f1> f") 'counsel-describe-function)
(global-set-key (kbd "<f1> v") 'counsel-describe-variable)
(global-set-key (kbd "<f1> o") 'counsel-describe-symbol)
(global-set-key (kbd "<f1> l") 'counsel-find-library)
(global-set-key (kbd "<f2> i") 'counsel-info-lookup-symbol)
(global-set-key (kbd "<f2> u") 'counsel-unicode-char)
(global-set-key (kbd "C-c g") 'counsel-git)
(global-set-key (kbd "C-c j") 'counsel-git-grep)
(global-set-key (kbd "C-c k") 'counsel-ag)
(global-set-key (kbd "C-x l") 'counsel-locate)
(global-set-key (kbd "C-S-o") 'counsel-rhythmbox)
(define-key minibuffer-local-map (kbd "C-r") 'counsel-minibuffer-history)

(require 'lsp-mode)
(require 'lsp-pyright)
(setq lsp-enable-snippet nil)
(setq lsp-log-io t)
(lsp-register-client
  (make-lsp-client
    :new-connection (lsp-tramp-connection (lambda ()
                                          (cons "pyright-langserver"
                                                lsp-pyright-langserver-command-args)))
    :major-modes '(python-mode)
    :remote? t
    :server-id 'pyright-remote
    :multi-root t
    :priority 3
    :initialization-options (lambda () (ht-merge (lsp-configuration-section "pyright")
                                                (lsp-configuration-section "python")))
    :initialized-fn (lambda (workspace)
                      (with-lsp-workspace workspace
                        (lsp--set-configuration
                        (ht-merge (lsp-configuration-section "pyright")
                                  (lsp-configuration-section "python")))))
    :download-server-fn (lambda (_client callback error-callback _update?)
                          (lsp-package-ensure 'pyright callback error-callback))
    :notification-handlers (lsp-ht ("pyright/beginProgress" 'lsp-pyright--begin-progress-callback)
                                  ("pyright/reportProgress" 'lsp-pyright--report-progress-callback)
                                  ("pyright/endProgress" 'lsp-pyright--end-progress-callback))))

(require 'tramp)
(add-to-list 'tramp-remote-path 'tramp-own-remote-path)
```
```bash
emacs -q -l ~/.debug.emacs.d/init.el --eval '(find-file "/ssh:host:/path/to/remote/fille.py")'
```

**Comment by mjlbach** [comment]
I've isolated the problem to the `python-mode-local-vars-hook`. If this is replaced with the `python-mode-hook` then everything works as it should.

**Comment by hlissner** [comment]
As of 7784c0b and c7513e4 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
