### ISSUE TITLE
Conflicting requirements on emacs version

### ISSUE THREAD

**Issue by pmeckoni** [hlissner/doom-emacs#3392]
I understand the confusion behind using doom-emacs on Emacs 26.1 related to #3283.

There are conflicting requirements for emacs: 

- [Readme.md](https://github.com/hlissner/doom-emacs/blob/develop/README.md#prerequisites) file mentions Emacs 26.1 

- [Getting Started Guide](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#install) mentions Emacs 26.3

**Comment by hlissner** [comment]
Sorry for the late response. Not sure when, but this was fixed sometime in the past year. Thanks for letting me know!
