### ISSUE TITLE
tty clipboard broken in develop

### ISSUE THREAD

**Issue by brettmilford** [hlissner/doom-emacs#3398]
In tty emacs yanking text doesn't get copied into the clipboard; specifically on Ubuntu 20.04 (Gnome Xorg).
Reverting f8c808d appears to fix it.
I suspect this happens on MacOS as well but I have not yet throughly checked this. 

**System information:**
<details><pre>
((emacs
  (version . "26.3")
  (features . "XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT )
  (build . "Mar 26, 2020")
  (buildopts "--build x86_64-linux-gnu --prefix=/usr --sharedstatedir=/var/lib --libexecdir=/usr/lib --localstatedir=/var/lib --infodir=/usr/share/inf)
  (windowsys . batch)
  (daemonp))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop 7a0a641ae 2020-06-16 21:35:10 +1000")
  (dir . "~/.config/doom/"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/bin/bash")
  (uname . "Linux 5.4.0-37-generic #41-Ubuntu SMP Wed Jun 3 18:57:02 UTC 2020 x86_64")
  (path "~/.local/bin" "~/.local/bin" "/usr/local/sbin" "/usr/local/bin" "/usr/sbin" "/usr/bin" "/sbin" "/bin" "/usr/games" "/usr/local/games" "/snap/)
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company ivy :ui doom hl-todo modeline nav-flash ophints (popup +all +defaults) vc-gutter vi-tilde-fringe window-select workspac)
  (packages (org-superstar :recipe (:host github :repo "integral-dw/org-superstar-mode")))
  (unpin "n/a")
  (elpa "n/a")))
</pre></details>

**Comment by wedens** [comment]
You can just add `(package! xclip)` to packages.el. 

xclip was replaced with [clippety](https://github.com/spudlyo/clipetty) which also allows using clipboard via ssh, but requires terminal with support for certain features (OSC 52 escape sequences).

**Comment by brettmilford** [comment]
@wedens this appears to be a regression in functionality unless the distribution intends to drop clipboard support for terminal emulators which don't support OSC 52 escape sequences.

**Comment by hlissner** [comment]
> unless the distribution intends to drop clipboard support for terminal emulators which don't support OSC 52 escape sequences.

This was originally the intention, but I've changed my mind. I plan to add a module for more comprehensive clipboard support and integration, but haven't gotten around to it yet. I'll let you know here once I have.

**Comment by hlissner** [comment]
Sorry for the late response. The `:os tty` module was added at some point in the past year, which fixes this issue, so I'll consider this resolved.
