### ISSUE TITLE
irony not being loaded correctly even after reloading autoloads

### ISSUE THREAD

**Issue by vikigenius** [hlissner/doom-emacs#341]
---

### Observed behavior

CC mode autocompletion not working with void-function irony-mode error upon opening a c++ source file.

### Expected behavior
No irony-mode errors and auto completion should work

### Steps to reproduce

Just tried this in both develop and master: 
1. Install doom-emacs as described in wiki.
2. Open a c++ file in a project which has compile_commands.json
3. Error message shows: void-function irony-mode
4. Auto completion not working in cc mode

Tried to repeat above steps after installing irony server, but issue is not resolved.

Also tried to resolve by make autoloads and also tried reloading autoloads from within emacs, that didn't solve the issue either.

Irony version installed is 1.2.0.

### System information

<details>
<summary>Click to expand</summary>

```
DOOM Doctor
Running Emacs v25.2.2, commit 981b63925bb41df82dfe0cae4afa449bcf9ef366

shell: /usr/bin/zsh
Compiled with:
  XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY
  ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB
  TOOLKIT_SCROLL_BARS GTK3 X11
uname -a:
  Linux shadowrealm 4.13.0-19-generic #22-Ubuntu SMP Mon Dec 4 11:58:07
  UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Attempt to load DOOM: success! Loaded v2.0.9
Revision 5dacbb7cb1c6ac246a9ccd15e6c4290def67757c

----

test-emacs
test-windows
test-fonts
Found font material-design-icons.ttf
Found font weathericons.ttf
Found font octicons.ttf
Found font fontawesome.ttf
Found font file-icons.ttf
Found font all-the-icons.ttf
test-gnutls
test-tls
Validated https://elpa.gnu.org
Validated https://melpa.org
Successfully rejected https://self-signed.badssl.com
Successfully rejected https://wrong.host.badssl.com/
test-tar
Everything seems fine, happy Emacs’ing!

```

</details>

**Comment by hlissner** [comment]
Turns out I forgot to add irony-mode to irony's :commands list when I wrote `+cc|init-irony-mode`. I've just added it to `develop` and will keep this issue open until it hits `master`.
