### ISSUE TITLE
Magit keys are not consistent

### ISSUE THREAD

**Issue by rgrinberg** [hlissner/doom-emacs#3410]
Open a magit status window and hit `%`. Observe that a magit gitflow pop up is opened.

Open a mgit help window (`?`) and hit `%`. Observe a worktree pop instead.

It's possible that this is intentional, but this seems highly inconsistent to me.

**Comment by zackteo** [comment]
@rgrinberg Not sure if it is cause I'm not using evil but I don't face this issue. 
`magit-gitflow-popup` is bound to `C-f` for me (without my own changes)

**Comment by rgrinberg** [comment]
I'm using evil, so that's probably the distinction between our setups.

**Comment by hlissner** [comment]
Seems [binding `%` solely to `magit-mode-map`](https://github.com/hlissner/doom-emacs/blob/develop/modules/tools/magit/config.el#L179) isn't enough. I'll welcome a PR to add whatever keymap will extend it to the help window.

**Comment by yyadavalli** [comment]
I don't think it's working off a keymap https://github.com/magit/magit/blob/master/lisp/magit.el#L257

The transient `magit-dispatch` needs to be modified.

**Comment by rgrinberg** [comment]
> Seems binding % solely to magit-mode-map isn't enough. I'll welcome a PR to add whatever keymap will extend it to the help window.

Which key would you suggest for worktree bindings? I assume you'd like to reserve `%` for gitflow.

**Comment by yyadavalli** [comment]
@rgrinberg I've used `*` for worktree in #3420
