### ISSUE TITLE
+dictionary flag doesn't install associated packages (MAC only)

### ISSUE THREAD

**Issue by Jonghyun-Yun** [hlissner/doom-emacs#3422]
**What did you expect to happen?**
+dictionary flag triggers installation of wordnut and synosaurus packages

**What actually happened?**
No installation of these packages.

The problem has resulted from conditional statement (IS-MAC) in 
doom-emacs-dir/modules/tools/lookup/packages.el
This is an easy fix, but sorry I don't know how to make PR.

**Comment by hlissner** [comment]
This is intentional. MacOS has a dictionary/thesaurus. The `osx-dictionary` package utilizes it on macOS, so neither wordnut and synosaurus is necessary.

**Comment by Jonghyun-Yun** [comment]
I see. Thanks for clarification.
