### ISSUE TITLE
Don't add unsaved files to Projectile cache

### ISSUE THREAD

**Issue by emdemir** [hlissner/doom-emacs#3423]
**Describe the feature**

When new files are opened within a project, Doom automatically adds an entry in the project file list cache for the file. But the problem with this is when you typo a filename, that also gets added to the project cache, and to remove the entry you must do <kbd>SPC p i</kbd> which not only deletes the incorrect entry, but also wipes your MRU list for the project, which is annoying.

A better way to save to project cache would be when the file is saved. It could also be made configurable.

**System information**
<details>
<pre>
emacs   version    26.3
        features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS LIBSYSTEMD LCMS2
        build      May 17, 2020
        buildopts  (--build x86_64-linux-gnu --prefix=/usr --sharedstatedir=/var/lib --libexecdir=/usr/lib --localstatedir=/var/lib --infodir=/usr/share/info --mandir=/usr/share/man --enable-libsystemd --with-pop=yes --enable-locallisppath=/etc/emacs:/usr/local/share/emacs/26.3/site-lisp:/usr/local/share/emacs/site-lisp:/usr/share/emacs/26.3/site-lisp:/usr/share/emacs/site-lisp --with-sound=alsa --without-gconf --with-mailutils --build x86_64-linux-gnu --prefix=/usr --sharedstatedir=/var/lib --libexecdir=/usr/lib --localstatedir=/var/lib --infodir=/usr/share/info --mandir=/usr/share/man --enable-libsystemd --with-pop=yes --enable-locallisppath=/etc/emacs:/usr/local/share/emacs/26.3/site-lisp:/usr/local/share/emacs/site-lisp:/usr/share/emacs/26.3/site-lisp:/usr/share/emacs/site-lisp --with-sound=alsa --without-gconf --with-mailutils --with-x=yes --with-x-toolkit=gtk3 --with-toolkit-scroll-bars 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/emacs-mHAik2/emacs-26.3+1=. -fstack-protector-strong -Wformat -Werror=format-security -Wall' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' LDFLAGS=-Wl,-z,relro)
        windowsys  x
        daemonp    daemon
doom    version    2.0.9
        build      HEAD -> develop 9edd4f26f 2020-06-11 04:49:31 -0400
        dir        ~/.doom.d/
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/bash
        uname      Linux 5.6.0-2-amd64 #1 SMP Debian 5.6.14-1 (2020-05-23) x86_64
        path       ;; omitted
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit fill-column hl-todo modeline nav-flash ophints (popup +defaults) pretty-code treemacs unicode vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold (format +onsave) snippets word-wrap :emacs dired electric vc :checkers syntax :tools debugger (eval +overlay) lookup (lsp +peek) magit rgb :lang (cc +lsp) common-lisp data emacs-lisp (haskell +dante) (javascript +lsp) latex markdown org (python +lsp) rest rst sh (web +lsp) :config (default +bindings +smartparens))
        packages   ((meson-mode) (po-mode) (json-mode))
        unpin      (n/a)
        elpa       (n/a)
</pre>
</details>

**Comment by hlissner** [comment]
This should be requested upstream in [projectile](https://github.com/bbatsov/projectile). Doom doesn't have any particular configuration affecting what files it does and doesn't cache.

In the meantime, this can be achieved with

```elisp
(defadvice! dont-cache-if-file-doesnt-exist-a (&rest _)
  :before-until #'projectile-cache-files-find-file-hook
  (and buffer-file-name (file-exists-p buffer-file-name)))
```

**Comment by emdemir** [comment]
Thank you for the workaround, I'll open a bug report on Projectile.
