### ISSUE TITLE
Enable flycheck's idle-change if lsp-mode is active?

### ISSUE THREAD

**Issue by sebastiansturm** [hlissner/doom-emacs#3424]
although `checkers/syntax/config.el` clearly states that idle checks are disabled on purpose, this is probably not the behavior expected by `lsp-mode` users (see https://github.com/emacs-lsp/lsp-mode/issues/1792) and the fix may not be obvious. What do you think about re-enabling `idle-change` by default if the `+lsp` flag is active?

**Comment by wedens** [comment]
Related issue: https://github.com/hlissner/doom-emacs/issues/3267#issuecomment-645498979 (but probably there are two different issues).

**Comment by wedens** [comment]
https://github.com/emacs-lsp/lsp-mode/pull/1820

> Cleanup diagnostics after the buffer has changed

**Comment by sebastiansturm** [comment]
I'm closing this as I think the issue is solved with https://github.com/emacs-lsp/lsp-mode/commit/8382cfa32175f85c2aa1cfd52ae657cc5197f9db
