### ISSUE TITLE
`doom-projectile-fd-binary` should change when using tramp

### ISSUE THREAD

**Issue by sggutier** [hlissner/doom-emacs#3425]
**What did you expect to happen?**
I have a server running Debian. I tried to use `(+ivy/projectile-find-file)` on a remote directory opened via tramp.  It should have opened the find-file frame.

**What actually happened?**
I got the following error:
```
counsel--call: fd --color=never -E .git --type file --type symlink --follow failed: 1
```

**Additional details:**
- I'm using emacs locally on MacOs.
- I have `fd` installed on MacOs.  
   - It is located in `/usr/local/bin/fd`
- My remote server uses Debian.
- I have `fd` installed on Debian.  
   - It is located in `/usr/bin/fdfind`.  
   - I installed it via `sudo apt install fd-find` .
- I'm using sshx for my remote connection.

When using `(+ivy/projectile-find-file)` on a remote server it tries to use the binary set in the variable `doom-projectile-fd-binary` inside `core/core-projects.el`.  This uses 
``` elisp
(cl-find-if #'executable-find '("fdfind" "fd")`
```
for finding the proper name for fd.

Changing the value of that variable with
```
(setq doom-projectile-fd-binary "fdfind")
```
enables `+ivy/projectile-find-file` remotely, but disables it locally.

**Steps to reproduce:**
1. Install `fd-find` on a remote server with Debian
2. Open doom-emacs in MacOs
3. In doom-emacs open a project located in the remote server with tramp using sshx.
4. Run `(+ivy/projectile-find-file)`

**System information:**
<details><pre>
((emacs
  (version . "27.0.91")
  (features . "RSVG IMAGEMAGICK GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS XWIDGETS PDUMPER LCMS2 GMP")
  (build . "Jun 19, 2020")
  (buildopts "--disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus@27/27.0.91/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus@27/27.0.91 --with-xml2 --with-gnutls --without-dbus --with-imagemagick --with-modules --with-rsvg --with-xwidgets --with-ns --disable-ns-self-contained")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "grafted, HEAD -> develop, origin/develop, origin/HEAD fdbfae3 2020-06-19 13:34:36 -0400")
  (dir . "~/.doom.d/"))
 (system
  (type . darwin)
  (config . "x86_64-apple-darwin19.5.0")
  (shell . "/bin/zsh")
  (uname . "Darwin 19.5.0 Darwin Kernel Version 19.5.0: Wed Jun  3 17:39:27 PDT 2020; root:xnu-6153.121.2~7/RELEASE_X86_64 x86_64")
  (path "/usr/local/bin" "/usr/bin" "/bin" "/usr/sbin" "/sbin" "/usr/local/Cellar/emacs-plus@27/27.0.91/libexec/emacs/27.0.91/x86_64-apple-darwin19.5.0"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company (ivy +icons) :ui deft doom doom-dashboard doom-quit hl-todo modeline ophints (popup +defaults) treemacs vc-gutter vi-tilde-fringe workspaces :editor file-templates fold multiple-cursors snippets :emacs dired electric undo vc :term vterm :checkers syntax :tools (eval +overlay) lookup lsp magit pdf :lang emacs-lisp markdown (org +pomodoro +roam +journal +org-init-protocol-lazy-loader-h) (php +lsp) (python +lsp) sh (web +lsp) :config (default +bindings +smartparens))
  (packages (org-download) (lorem-ipsum))
  (unpin "n/a")
  (elpa "n/a")))
</pre></details>

**Comment by hlissner** [comment]
As of d034bc2 this should be resolved. Let me know if that isn't the case and I'll reopen the issue. Thanks for bringing it to my attention.

**Comment by mreishus** [comment]
@hlissner 
Similar issue but not the same; if I tramp into a server without `fd` installed and run `+ivy/projectile-find-file`, I get `/bin/sh: 196: fd: not found`.  It's a work server so I can't install fd on it.    Unsure if this is a bug..
