### ISSUE TITLE
configure org-mode agenda view "stuck projects"

### ISSUE THREAD

**Issue by fladd** [hlissner/doom-emacs#3426]
**Describe the feature**
It seems that the "stuck projects" agenda view is org-mode's default of "every second level heading is a project, and if below those there is not active task, then the project is stuck". However, this will mark all months in journal.org as stuck projects, if they have no tasks (and since this is a journal that is quite likely). Furthermore, given that Doom's default config has a PROJ todo keywords, as well as a concept of (coding) projects, the "stuck projects" agenda view could potentially be better configured.

(Also, there is a shortcut for configuring this view via the Emacs configuration interface, which if I understand correctly is not something that should be exposed to a Doom user).

**System information**
<details><pre>
<details>

```
emacs   version    26.3
        features   JPEG RSVG IMAGEMAGICK GLIB NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2
        build      Jun 20, 2020
        buildopts  (--disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus@26/26.3/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus@26/26.3 --with-xml2 --with-gnutls --with-imagemagick --with-modules --with-rsvg --with-ns --disable-ns-self-contained)
        windowsys  ns
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop, origin/develop, origin/HEAD 042cc781b 2020-06-20 03:02:05 -0400
        dir        ~/.doom.d/
system  type       darwin
        config     x86_64-apple-darwin18.6.0
        shell      /bin/bash
        uname      Darwin 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64
        path       (~/.emacs.d/bin /usr/local/sbin ~/miniconda3/bin /Library/Frameworks/Python.framework/Versions/3.8/bin /usr/local/fsl/bin ~/.nix-profile/bin ~/.nix-profile/sbin /usr/local/sbin ~/miniconda3/bin /Library/Frameworks/Python.framework/Versions/3.8/bin /usr/local/fsl/bin ~/.nix-profile/bin ~/.nix-profile/sbin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /opt/local/Library/Frameworks/Python.framework/Versions/2.7/bin/ /usr/texbin /opt/X11/bin /Library/TeX/Distributions/.DefaultTeX/Contents/Programs/texbin /Library/TeX/Distributions/.DefaultTeX/Contents/Programs/texbin /usr/local/Cellar/emacs-plus@26/26.3/libexec/emacs/26.3/x86_64-apple-darwin18.6.0/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline ophints (popup +defaults) vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold snippets :emacs dired electric undo vc :checkers syntax :tools (eval +overlay) lookup magit :lang emacs-lisp markdown (org +dragndrop) python sh :config (default +bindings +smartparens))
        packages   (n/a)
        unpin      (n/a)
        elpa       (n/a)
```
</details>
</pre></details>

**Comment by hlissner** [comment]
I don't understand the request -- I'm not a heavy user of org-agenda. Can you be more specific? Perhaps touch on implementation details? 

> However, this will mark all months in journal.org as stuck projects, if they have no tasks (and since this is a journal that is quite likely).

Is this a Doom issue? Should it be brought up upstream to org-journal instead?

**Comment by fladd** [comment]
> I don't understand the request -- I'm not a heavy user of org-agenda. Can you be more specific? Perhaps touch on implementation details?

Sure. Org-agenda has a feature (in the agenda list) called "List stuck projects" (https://orgmode.org/manual/Stuck-projects.html). The idea behind this comes from the GTD methodology (https://en.wikipedia.org/wiki/Getting_Things_Done) and is to identify projects which have no "next action" (and are hence in a "stuck" state). The org manual mentions that in most cases the specifics of what make a stuck project need to be configured by the user, and that the default "assumes that all your projects are level-2 headlines, and that a project is not stuck if it has at least one entry marked with a TODO keyword ‘TODO’ or ‘NEXT’ or ‘NEXTACTION’".

> > However, this will mark all months in journal.org as stuck projects, if they have no tasks (and since this is a journal that is quite likely).
> 
> Is this a Doom issue? Should it be brought up upstream to org-journal instead?

This is unexpected behaviour as a result of the default configuration of the "stuck project" setting in org-agenda, as described above. Since the journal file is in agenda-files and since a month in the journal is a second level heading, as a consequence of this org-agenda default setting, every month in the journal in which there are no actions as defined above, will hence assumed to be a stuck project. I think that in the default org setup of Doom Emacs, there are actually notions of projects which are different to and more precise than what this rather general default assumption of org-agenda implies.

I hence suggest to configure org-agenda's "stuck projects" in a way that results in a more reasonable behaviour in the context of the default setup in Doom Emacs. For instance, a "stuck project" could be defined as every heading that either starts with the keyword `PROJ` or is a heading in `projects.org` or is in one of the local project files, **and** has not actionable sub headings (i.e. headings that start with one of the todo keywords setup by default in Doom Emacs).

**Comment by fladd** [comment]
The issue seems still valid.

**Comment by rdparker** [comment]
The answer is buried in the details of org-mode. Digging into the [Matching tags and properties](https://orgmode.org/manual/Matching-tags-and-properties.html) and [Special Properties](https://orgmode.org/manual/Special-Properties.html) section of [The Org Manual](https://orgmode.org/manual/index.html), you can use the `FILE` special property to ignore `journal.org` based upon regex matching. Adding `-FILE={\\<journal\\.org\\>}` to Doom Emacs' default `org-stuck-projects` value will skip the file.

```elisp
(setq org-stuck-projects
      '("+LEVEL=2-FILE={\\<journal\\.org\\>}/-DONE" ("TODO" "NEXT" "NEXTACTION") nil ""))
```

That said, given that Doom's org module sets `org-todo-keywords` as follows:

```elisp
  (setq org-todo-keywords
        '((sequence
           "TODO(t)"  ; A task that needs doing & is ready to do
           "PROJ(p)"  ; A project, which usually contains other tasks
           "LOOP(r)"  ; A recurring task
           "STRT(s)"  ; A task that is in progress
           "WAIT(w)"  ; Something external is holding up this task
           "HOLD(h)"  ; This task is paused/on hold because of me
           "IDEA(i)"  ; An unconfirmed and unapproved task or notion
           "|"
           "DONE(d)"  ; Task successfully completed
           "KILL(k)") ; Task was cancelled, aborted or is no longer applicable
          (sequence
           "[ ](T)"   ; A task that needs doing
           "[-](S)"   ; Task is in progress
           "[?](W)"   ; Task is being held up or paused
           "|"
           "[X](D)")  ; Task was completed
          (sequence
           "|"
           "OKAY(o)"
           "YES(y)"
           "NO(n)"))
```

The other parts of `org-stuck-projects` should probably be updated to match.

If I get it all hammered out on my install, there's a slightly greater than ε chance that I'll submit a PR.
