### ISSUE TITLE
Brace should go one line further after pressing `Enter`

### ISSUE THREAD

**Issue by andyafter** [hlissner/doom-emacs#343]
When I have a pair of new Braces {|}, normally we press `Enter` to edit what should be in the braces. When I press `Enter` it turns out to be:
{
|}

which should be
{
    |
}

**Comment by fuxialexander** [comment]
I think that's highly context-specific (in terms of languages / personal-preference / code types) and there will no solution for all. I think it should be done by user themselves.

You might want to Google `electric-layout-mode` and `c-toggle-auto-newline`

**Comment by hlissner** [comment]
I have this configured [in my private module](https://github.com/hlissner/doom-emacs-private/blob/master/config.el#L21-L26) with the following:

```emacs-lisp
  (sp-pair "{" nil :post-handlers '(("||\n[i]" "RET") ("| " " "))
           :unless '(sp-point-before-word-p sp-point-before-same-p))
  (sp-pair "(" nil :post-handlers '(("||\n[i]" "RET") ("| " " "))
           :unless '(sp-point-before-word-p sp-point-before-same-p))
  (sp-pair "[" nil :post-handlers '(("| " " "))
           :unless '(sp-point-before-word-p sp-point-before-same-p))
```

I've left it out of Doom proper because it's personal preference.

**Comment by hlissner** [comment]
I'll mention this in the FAQ soon and, perhaps, incorporate some (not all) of this into private/default. For the time being, since I consider this personal preference, I'll consider this issue resolved.

**Comment by hlissner** [comment]
Just letting you know: as of 57adae5, these settings are built into private/default.
