### ISSUE TITLE
Warning: repos that have renamed "master" branch to "main" must be fixed manually on `doom update` or `doom upgrade`

### ISSUE THREAD

**Issue by telotortium** [hlissner/doom-emacs#3435]
`doom upgrade` (and I presume `doom update`) aborts if upstream has changed the default branch name (for example, [from master to main](https://www.hanselman.com/blog/EasilyRenameYourGitDefaultBranchFromMasterToMain.aspx)). Example failure:

```    
$ doom -d upgrade -p
...
> (280/288) Fetching websocket...nil
x There was an unexpected error:
  Type: doom-package-error
  Message:
    Error with packages
  Data:
    "websocket"
    (error "Failed to run \"git\"; see buffer *straight-process*")
  Straight output:
    fatal: couldn't find remote ref refs/heads/master
```

This is because https://github.com/ahyatt/emacs-websocket has renamed their "master" branch to "main". Git doesn't handle this situation automatically if you've already cloned a local copy. It can be fixed with instructions from [the aforementioned article](https://www.hanselman.com/blog/EasilyRenameYourGitDefaultBranchFromMasterToMain.aspx):

```
$ git checkout master
$ git branch -m master main
$ git fetch
$ git branch --unset-upstream
$ git branch -u origin/main
$ git symbolic-ref refs/remotes/origin/HEAD refs/remotes/origin/main
```

**Comment by hlissner** [comment]
This should probably be reported upstream to straight. It defaults to cloning master in the absence of an explicit branch. Though, I suspect no good, general solution for this exists.

Neither Doom nor straight is able to guess what a repo's main branch is, or whether the current branch was necessarily renamed to main or some other arbitrary name.

**Comment by jcf** [comment]
@hlissner I've taken the liberty of opening a couple of issues. One over in the emacs-websocket repo where I think it'd be considerate to let people know about the breaking change, and one over in the straight.el repo.

**Comment by raxod502** [comment]
A permanent solution to this problem [has been discussed already](https://github.com/raxod502/straight.el/issues/279#issuecomment-392689678). Some nontrivial work is required, but I do not think the problem is insurmountable in principle.

**Comment by randomizedthinking** [comment]
@telotortium can you show step-by-step instructions what we need to do?

**Comment by telotortium** [comment]
@randomizedthinking My instructions above don't work?

**Comment by randomizedthinking** [comment]
@telotortium To me, websocket is a package in the middle. After running your commands inside **.emacs.d/.local/straight/repos/emacs-websocket**, I still stuck with **doom update**: I would like to update the rest of the packages after websocket, but it won't work.

**Comment by panchoh** [comment]
## Workaround (CAVEAT EMPTOR: with full rebuild)

### Assumptions:

- You already have a working set of config files (e.g.: `~/.config/doom/*`)

### Workaround proper

```sh
EMACSDIR="~/.emacs.d" # Ensure this is accurate!
mv -iv "$EMACSDIR" "$EMACSDIR".bck
git clone --depth 1 https://github.com/hlissner/doom-emacs.git "$EMACSDIR"
"$EMACSDIR"/bin/doom sync
```

`doom sync` will emit a warning:

```console
    → Building ein → Cloning emacs-websocket...

Warning (straight): Could not check out branch "master" of repository "emacs-websocket"
    → Building ein → Cloning emacs-websocket...done
```

 ... but will compile anyway:

```console
$ ls -l ~/.emacs.d/.local/straight/build/websocket/
total 68
lrwxrwxrwx 1 pancho pancho    72 Jun 23 07:04 websocket.el -> /home/luser/.emacs.d/.local/straight/repos/emacs-websocket/websocket.el
-rw-r--r-- 1 pancho pancho 62441 Jun 23 07:04 websocket.elc


```

Hope that it helps!

**Comment by raxod502** [comment]
Perhaps I am missing something, but why can you not just go into the `websocket` repository and manually `git checkout main`? The whole point of `straight.el` is that you can always do stuff manually if the package manager is not smart enough.

**Comment by panchoh** [comment]
> Perhaps I am missing something, but why can you not just go into the `websocket` repository and manually `git checkout main`? The whole point of `straight.el` is that you can always do stuff manually if the package manager is not smart enough.

That's the first thing I tried.  But in my case, the repo was already tracking `main`.  The problem happens after that, when running `doom upgrade`.  It complains about an issue with `master`, and won't cooperate.  Doing the `doom sync` route works nicely, though.

**Comment by imsodin** [comment]
I got these kind of errors also when cleaning out repos to start from scratch due to `init.defaultBranch`. I fixed that issue upstream: https://github.com/raxod502/straight.el/pull/739  
I'd appreciate if the pin could be bumped to that :)

**Comment by yeldiRium** [comment]
Stalebot strikes once again and closes a relevant and unresolved issue.
