### ISSUE TITLE
`=Calendar` App?

### ISSUE THREAD

**Issue by fuxialexander** [hlissner/doom-emacs#344]
Not sure if anyone would be interested but the setup would be like this:
- Calfw is used for display the calendar
- org-gcal is used for sync with google calendar

Currently things are hacked together and two thing need to be resolved:
1. `(map!)` seems have no effect, probably due to the internal change of keymap in one of `calfw` 's function. The default keybinding of `calfw` is very vimmy, only complain is that the `SPC` is mapped to preview entry, while I'd like to act as doom-leader.  Not sure whether there are ways to map `SPC` act as what it does in `evil-normal-state-map` while stay in other map. I may need to check more in-depth later.

2. Sync with google calendar require the `ID` of org heading to be fully controlled by `org-gcal` in the specified org file. Currently I use a hook to auto create `ID` for all headings in the file while saving. I need to find a way to exclude those calendar-org file (well, maybe just use an `if` in the hook with `(buffer-name)`). 

![image](https://user-images.githubusercontent.com/8258908/34813326-801581a6-f6e4-11e7-95a3-f2228ec87b67.png)

**Comment by hlissner** [comment]
Very cool. I am certainly interested. Could you make a PR for it, or do you have the code up somewhere I can see?

**Comment by fuxialexander** [comment]
Sure. I’m currently trying to cleaning it a bit, after that I’ll make a PR

**Comment by hlissner** [comment]
Closing this, now that it's in `develop`.
