### ISSUE TITLE
Doom upgrade (or refresh or doctor or any) does not work

### ISSUE THREAD

**Issue by mike091020** [hlissner/doom-emacs#3444]
**What did you expect to happen?**

I'm having endless problems getting things to work correctly.  I tried various of the doom commands and they stop running with various errors.  The latest is: "Cannot open load file: No such file or directory, subr-x

**What actually happened?**
I was hopiing for a refresh that would fix a bad file or something.  Doom doctor takes about  10 minutes to run then stops with an error:

```
The doctor will see you now...

> Checking your Emacs version...
> Checking for Emacs config conflicts...
> Checking for private config conflicts...
> Checking for stale elc files...
[31mx There was an unexpected error:[0m
  [1mType:[0m error
  [1mMessage:[0m
    error
  [1mData:[0m
    "Variable binding depth exceeds max-specpdl-size"

Run the command again with the -d (or --debug) switch to enable debug
mode and (hopefully) generate a backtrace from this error:

  doom -d doctor

If you file a bug report, please include it!
```

Of course, there is nothing more included by way of a backtrace or other info when I run with the option.  I'm also puzzled by the giberish mixed in with the text in the message.  (I'm running that in Ubuntu under Windows 10, and Emacs 26.3 under Windows 10).

**Additional details:**
- Include a link to your private config

I don't know what a private config is!

- Include screenshots/casts of your issue
- If you mention key sequences, include what commands they're bound to (use `SPC
  h k KEY` or `C-h h k KEY` to inspect keys).
- Include any warnings or errors logged to \*Messages\* (use `M-x
  view-echo-area-messages` to see it).

<details>
<summary>From the latest Messages</summary>

```
Doom loaded 157 packages across 29 modules in 6.001s
Failed to load git-commit package incrementally, because: (file-missing Cannot open load file No such file or directory rmail-loaddefs)
Failed to load magit package incrementally, because: (file-missing Cannot open load file No such file or directory rmail-loaddefs)
Failed to load calendar package incrementally, because: (file-missing Cannot open load file No such file or directory cal-loaddefs)
Failed to load org package incrementally, because: (file-missing Cannot open load file No such file or directory cal-loaddefs)
Failed to load org-agenda package incrementally, because: (file-missing Cannot open load file No such file or directory cal-loaddefs)
Failed to load org-capture package incrementally, because: (file-missing Cannot open load file No such file or directory cal-loaddefs)
Failed to load org package incrementally, because: (file-missing Cannot open load file No such file or directory cal-loaddefs)
```

</details>

In trying to add the info you request, I note that no version of Doom runs under my Ubunu now.  I get the same message about the subr-x directory or file missing.

**Steps to reproduce:**
1. I had a whole several days of different problems before I attempted Doom upgrade.  The problems I'm describing relate to that.  I tried Doom upgrade and doctor to try to fix a broken or missing file.  Before that I backed out configuration chages thinking that might help.  Of course, there are so many configuration/init files in so many directories I'm not sure if I got them all.  It sure would help to have a list of them all and where they are supposed to live.

This is just the latest of my battles.  Prevously I reinstalled Emacs 26.3 several times and then followed the Doom instructions to install that.  When I saw Doom Doctor I thought this might be a general fix it tool for damaged or missing files.  It does not seem to help ... though it looks like it is trying.

One thought forming in my mind now is that there may be some data entry that points to installation directories and it is getting confused because I installed so many times.  Perhaps it is just confused?  Is there some data item that I could delete that would cause Doom Doctor (or other) to realize that it can't make assumptions?

**System information:**

From doom info:

```
Warning: arch-dependent data dir 'c:/Users/mikes/.emacs.d/libexec/emacs/26.3/x86_64-w64-mingw32/': Invalid argument
Cannot open load file: No such file or directory, subr-x
Warning: arch-dependent data dir 'c:/Users/mikes/.emacs.d/libexec/emacs/26.3/x86_64-w64-mingw32/': Invalid argument
Cannot open load file: No such file or directory, subr-x
```

That's the best I can do with my level of experience and the confused mess I find this to be right now.  Any help you can provide will be appreceated.

**Comment by hlissner** [comment]
These are a lot of weird issues. Many of them complain about missing `rmail-loaddefs`, `cal-loaddefs` and `subr-x` files. I suspect a bad Emacs install, because these are all built-in libraries. i.e. They come included with Emacs.

As I'm not a Windows user, and my Emacs-on-Windows-fu is limited, I can only relay what these installation instructions from other happy Doom+WSL+Ubuntu users. Perhaps they can help:

+ Setting up Emacs + WSL: https://github.com/hubisan/emacs-wsl
+ Installing EMacs + Doom without WSL: https://earvingad.github.io/posts/doom_emacs_windows/
+ https://ethanaa.com/blog/switching-to-doom-emacs/#activate-wsl-and-install-ubuntu-18-04-lts

**Comment by hlissner** [comment]
As of 976a601 I've expended on Doom's documentation for installing Emacs and Doom on windows, which I hope will prevent issues like these in the future. In any case I will consider this resolved.
