### ISSUE TITLE
how do I recover autosave file

### ISSUE THREAD

**Issue by OrionRandD** [hlissner/doom-emacs#3445]
I have deleted my ./local/etc/workspaces/autosave files by accident
I touched a new one with

 $ touch autosave 
 
  But it did not work -> the error is: "end of file" 
  What should I put inside this file or recover the it?

**Comment by ymarco** [comment]
Nothing should happen if you just leave them deleted

**Comment by hlissner** [comment]
Once the file is deleted, you cannot retrieve it without perfectly reproducing persp-mode's data structure for its perspectives, which is non-trivial. If you have no backups, sorry to say: it is lost.
