### ISSUE TITLE
[BUG] Coq lookup references doesn't display results

### ISSUE THREAD

**Issue by tchajed** [hlissner/doom-emacs#3448]
**What did you expect to happen?**
In Coq, `SPC c D` should be the same as calling `company-coq-grep-symbol` and should display a new grep buffer with the results.

**What actually happened?**
`company-coq-grep-symbol` gets called (there's a message "Grep finished with matches found" in the echo area), but the results buffer is not shown.

**Steps to reproduce:**
1. Open any Coq project.
2. Run `SPC c D` on an identifier.
3. Compare to `M-x company-coq-grep-symbol`.

**System information:**
<details><pre>
((emacs
  (version . "27.0.91")
  (features . "RSVG IMAGEMAGICK GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS PDUMPER LCMS2 GMP")
  (build . "May 19, 2020")
  (buildopts "--disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus/HEAD-4b9fbdb/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus/HEAD-4b9fbdb --with-xml2 --with-gnutls --without-dbus --with-imagemagick --with-modules --with-rsvg --with-ns --disable-ns-self-contained")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop 99eea1d3e 2020-06-21 13:53:58 -0400")
  (dir . "~/code/dotfiles/emacs/doom/"))
 (system
  (type . darwin)
  (config . "x86_64-apple-darwin19.4.0")
  (shell . "/bin/zsh")
  (uname . "Darwin 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64")
  (path "~/code/sw/coq/bin/" "." "~/.opam/4.10.0+flambda/bin" "~/.emacs.d/bin" "/usr/local/texlive/2020/bin/x86_64-darwin" "/usr/local/Cellar/minimal-racket/7.7/bin" "~/.gem/bin" "~/.dotfiles/bin" "~/code/sw/latexrun" "~/.cargo/bin" "~/go/bin" "~/.local/bin" "/usr/local/bin" "/usr/local/sbin" "/usr/bin" "/bin" "/usr/sbin" "/sbin" "/usr/local/Cellar/emacs-plus/HEAD-4b9fbdb/libexec/emacs/27.0.91/x86_64-apple-darwin19.4.0"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard doom-quit hl-todo hydra modeline nav-flash ophints (popup +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold (format +onsave) multiple-cursors snippets :emacs dired electric ibuffer undo vc :term vterm :checkers syntax spell :tools editorconfig (eval +overlay) lookup lsp macos magit make pdf :lang coq data emacs-lisp fstar (go +lsp) (haskell +dante) latex lua markdown ocaml (org +present) python racket rust (sh +fish) web yaml :config (default +bindings +smartparens))
  (packages (default-text-scale) (math-symbol-lists) (frame-fns :recipe (:host github :repo "emacsmirror/frame-fns")) (frame-cmds :recipe (:host github :repo "emacsmirror/frame-cmds")) (zoom-frm :recipe (:host github :repo "emacsmirror/zoom-frm")))
  (unpin "n/a")
  (elpa "n/a")))
</pre></details>

**Comment by tchajed** [comment]
@cpitclaudel do you have an idea why the `company-coq-grep-symbol` results buffer wouldn't be shown? In case it helps it's being called from https://github.com/hlissner/doom-emacs/blob/99eea1d3e25d8bf6034ff31d231e4ecfc3dc628c/modules/tools/lookup/autoload/lookup.el#L282

and the handler is just set to `#'company-coq-grep-symbol`.

**Comment by cpitclaudel** [comment]
Maybe handlers are supposed to do something that company-coq doesn't do? (like return a buffer?)

**Comment by rgrinberg** [comment]
I think doom just expects them to be normal xref backends.
