### ISSUE TITLE
embrace-org-mode-hook is not called if org is loaded before evil-surround

### ISSUE THREAD

**Issue by dsdshcym** [hlissner/doom-emacs#345]
`embrace-org-mode-hook` was added in the `config` block for `evil-embrace`. See https://github.com/hlissner/doom-emacs/blob/471c68fc8a376ba1eae8ae8fe77c167fcdb65a23/modules/feature/evil/config.el#L199

But `evil-embrace` is loaded after `evil-surround`, which is loaded if its commands are called. Usually I load my org files right after I open my Emacs, which means `evil-surround` is not called yet. So I need to setup embrace-org-mode again.

I'm not sure how to solve this elegantly yet, so I'm opening this issue for your advice.

**Comment by hlissner** [comment]
I've moved the hooks to :init, and added autoloads for `embrace-add-pair` and`embrace-add-pair-regexp`, which should resolve this. Let me know if it doesn't!

**Comment by dsdshcym** [comment]
It worked as expected! Thanks!

**Comment by dsdshcym** [comment]
Sorry but I still found `evil-embrace` is not working as expected with `org-mode`

I did some investigation and found that replacing `:after evil-surround` with a `after!` can solve this issue:
```elisp
(def-package! evil-embrace
  :commands (evil-embrace-enable-evil-surround-integration embrace-add-pair embrace-add-pair-regexp)
  :hook (LaTeX-mode . embrace-LaTeX-mode-hook)
  :hook (org-mode . embrace-org-mode-hook)
  :init
  (after! evil-surround
    (evil-embrace-enable-evil-surround-integration))
```

**Comment by hlissner** [comment]
Sorry for the tremendously late followup, this issue slipped under my radar. As of 5f5874c this issue should be resolved. Let me know if that isn't the case and I will reopen this issue.
