### ISSUE TITLE
org-download package is not installed correclty

### ISSUE THREAD

**Issue by omarelashkar** [hlissner/doom-emacs#3451]
**What did you expect to happen?**
I should have org-download package commands and functionality available after the following lines added to my packages.el file.

```
(package! org-download)

;; Drag-and-drop to `dired`
(add-hook 'dired-mode-hook 'org-download-enable)
```
I then refreshed my doom configuration.

**What actually happened?**
when pressing SPC :, no org-download commands are there which indicate that the package not there. Also no copy-paste/drag-drop worked.

**System information:**
Xubuntu 20.04

<details>

```
emacs   version    26.3
        features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD LCMS2
        build      Sep 16, 2019
        buildopts  (--build=x86_64-linux-gnu --prefix=/usr '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' --sysconfdir=/etc --localstatedir=/var --disable-silent-rules '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' --disable-maintainer-mode --disable-dependency-tracking --prefix=/usr --sharedstatedir=/var/lib --program-suffix=26 --with-modules --with-file-notification=inotify --with-mailutils --with-x=yes --with-x-toolkit=gtk3 --with-xwidgets --with-lcms2 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/emacs26-TP6iDo/emacs26-26.3~1.git96dd019=. -fstack-protector-strong -Wformat -Werror=format-security -no-pie' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro -no-pie')
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      grafted, HEAD -> develop, origin/develop, origin/HEAD 45aae7f 2020-05-01 19:51:32 -0400
        dir        ~/.doom.d/
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/bash
        uname      Linux 5.4.0-37-generic #41-Ubuntu SMP Wed Jun 3 18:57:02 UTC 2020 x86_64
        path       (/Documents/datasci/toochest ~/gems/bin ~/anaconda3/bin ~/anaconda3/condabin ~/bin /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /usr/games /usr/local/games . /snap/bin ~/Documents/android/flutter/bin /usr/lib/x86_64-linux-gnu/emacs/26.3/x86_64-linux-gnu/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit fill-column hl-todo modeline nav-flash ophints (popup +defaults) pretty-code tabs treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold snippets :emacs dired electric undo vc :term eshell term :checkers syntax grammar :tools (eval +overlay) lookup magit :lang emacs-lisp ess markdown org qt sh :config (default +bindings +smartparens))
        packages   ((epc) (auto-complete) (org-pomodoro) (Pomidor) (tomatinho) (conda) (texlive-latex-extra) (org-download))
        unpin      (n/a)
        elpa       (zone-sl org-download async)
```
</details>

**Comment by wedens** [comment]
Have you tried enabling `+dragndrop` feature in doom's org module? It's enabled using `(org +dragndrop)` in init.el.

**Comment by omarelashkar** [comment]
> Have you tried enabling `+dragndrop` feature in doom's org module? It's enabled using `(org +dragndrop)` in init.el.

Yes! The idea is that I want to not only put images. You can also paste an image from clipboard and drag from browser. You don't have to worry about setting the directory of this image as it will be located in the org directory. That's why I like it

**Comment by omarelashkar** [comment]
@wedens  Actually I found something from this blog:  [https://dotdoom.rgoswami.me/config.html](https://dotdoom.rgoswami.me/config.html)

```
(use-package! org-download
  :after org
  :config
  (setq-default org-download-screenshot-method "xfce4-screenshooter -r -s %s"
                org-download-image-dir "~/myorg/"
                org-download-method 'directory
                org-download-heading-lvl 1
                )
  )
```

Now, org-download is working fine with one expectation still is that I can't manage to change the org-download-image-dir. It always points to ~/org/.attach/.....  directory. 

Strangely enough, if I disable dragndrop, it will not work!

**Comment by wedens** [comment]
Try setting `org-download-image-dir` in `:init` section of `use-package`.

**Comment by omarelashkar** [comment]
> Try setting `org-download-image-dir` in `:init` section of `use-package!`.

Nothing is working, unfortunately. Tried the following 
```
(use-package! org-download
  :after org
  :init
  (setq-default org-download-image-dir "~/myorg"
                org-download-screenshot-method "xfce4-screenshooter -r -s %s"
                org-download-method 'directory
                org-download-heading-lvl 1

                )
 )

```
```
(use-package! org-download
  :before org
  :init
  (setq-default org-download-image-dir "~/myorg"
                org-download-screenshot-method "xfce4-screenshooter -r -s %s"
                org-download-method 'directory
                org-download-heading-lvl 1

                )
 )
```

**Comment by wedens** [comment]
Try this:
```elisp
(use-package! org-download
  :init
  (setq org-download-image-dir "~/myorg")
  :config
  (setq org-download-screenshot-method "xfce4-screenshooter -r -s %s"
        org-download-method 'directory
        org-download-heading-lvl 1))
```
If you want to use your own org-download settings, without fighting doom's defaults, you can disable `+dragndrop` feature in doom's org module, add `(package! org-download)` to packages.el and the code above to config.el

**Comment by omarelashkar** [comment]
> Try this:
> 
> ```emacs-lisp
> (use-package! org-download
>   :init
>   (setq org-download-image-dir "~/myorg")
>   :config
>   (setq org-download-screenshot-method "xfce4-screenshooter -r -s %s"
>         org-download-method 'directory
>         org-download-heading-lvl 1))
> ```
> 
> If you want to use your own org-download settings, without fighting doom's defaults, you can disable `+dragndrop` feature in doom's org module, add `(package! org-download)` to packages.el and the code above to config.el

No, as I told you before. Disable dragndrop also disables org-download. This configuration did not change anything, still wrong directory and preview is disabled after quieting. I made an issue on the org-download repo. May the author knows what causes this.

**Comment by omarelashkar** [comment]
@wedens Actually it works now! I did an extensive upgrade for doom and now everything is working as expected. But the way I have not disabled dragndrop. 
Big thanks @wedens!
