### ISSUE TITLE
Magit-forge unable to create pull requests (evil-disable-insert-state-bindings is void)

### ISSUE THREAD

**Issue by rzikm** [hlissner/doom-emacs#3452]
Happens after selecting source and target branches.

**What did you expect to happen?**
A markdown buffer should open to collect the pull request message

**What actually happened?**
No window opened, error message `Symbol’s function definition is void: evil-disable-insert-state-bindings` appears in status bar.

**Additional details:**
- Include a link to your private config https://github.com/rzikm/.doom.d
- No further usable info in Messages
- Same behavior sometimes observed when manually switching to evil-markdown-mode, or even opening *.md files
- I was able to make it work after some tinkering (including forcing markdown mode in magit status buffer), but I can't recall a specific action that "fixed" it. After restarting emacs, the issue repeats.

<details><pre>
Debugger entered--Lisp error: (void-function evil-disable-insert-state-bindings)
  evil-disable-insert-state-bindings()
  byte-code("\300\301!\203\22\0\301 \203\22\0\302\303!\210\202\26\0\302\304!\210\305\306!\207" [boundp evil-disable-insert-state-bindings evil-markdown-set-key-theme (navigation textobjects additional) (navigation textobjects insert additional) provide evil-markdown] 2)
  evil-markdown-mode()
  run-hooks(change-major-mode-after-body-hook text-mode-hook markdown-mode-hook gfm-mode-hook forge-post-mode-hook)
  apply(run-hooks (change-major-mode-after-body-hook text-mode-hook markdown-mode-hook gfm-mode-hook forge-post-mode-hook))
  run-mode-hooks(forge-post-mode-hook)
  forge-post-mode()
  forge--prepare-post-buffer("new-pullreq" "Create new pull-request on ***" "origin/***")
  forge-create-pullreq("origin/***" "origin/***")
  funcall-interactively(forge-create-pullreq "origin/***" "origin/***")
  call-interactively(forge-create-pullreq nil nil)
  command-execute(forge-create-pullreq)

</pre></details>

**System information:**
<details><pre>
((emacs
  (version . "27.0.60")
  (features . "XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY W32NOTIFY ACL GNUTLS LIBXML2 HARFBUZZ ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS PDUMPER LCMS2 GMP")
  (build . "Dec 28, 2019")
  (buildopts "--without-dbus --host=x86_64-w64-mingw32 --without-compress-install -C 'CFLAGS=-O2 -static -g3'")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop 99eea1d3e 2020-06-21 13:53:58 -0400")
  (dir . "~/.doom.d/"))
 (system
  (type . windows-nt)
  (config . "x86_64-w64-mingw32")
  (shell . "C:/Program Files/Emacs/x86_64/libexec/emacs/27.0.60/x86_64-w64-mingw32/cmdproxy.exe")
  (uname . "n/a")
  (path "c:/Program Files/ConEmu/ConEmu/Scripts" "C:/Program Files/ConEmu" "C:/Program Files/ConEmu/ConEmu" "C:/Perl64/site/bin" "C:/Perl64/bin" "C:/Python38/Scripts/" "C:/Python38/" "C:/Program Files/Oculus/Support/oculus-runtime" "C:/Python37/Scripts/" "C:/Python37/" "C:/Program Files (x86)/Common Files/Oracle/Java/javapath" "C:/Program Files (x86)/Intel/Intel(R) Management Engine Components/iCLS/" "C:/Program Files/Intel/Intel(R) Management Engine Components/iCLS/" "C:/Windows/system32" "C:/Windows" "C:/Windows/System32/Wbem" "C:/Windows/System32/WindowsPowerShell/v1.0/" "C:/Windows/System32/OpenSSH/" "C:/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL" "C:/Program Files/Intel/Intel(R) Management Engine Components/DAL" "C:/Program Files (x86)/Intel/Intel(R) Management Engine Components/IPT" "C:/Program Files/Intel/Intel(R) Management Engine Components/IPT" "C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common" "C:/Program Files/Microsoft SQL Server/110/Tools/Binn/" "C:/ProgramData/chocolatey/bin" "C:/Program Files/Microsoft Windows Performance Toolkit/" "C:/Program Files/Git/cmd" "C:/Program Files (x86)/IncrediBuild" "C:/WINDOWS/system32" "C:/WINDOWS" "C:/WINDOWS/System32/Wbem" "C:/WINDOWS/System32/WindowsPowerShell/v1.0/" "C:/WINDOWS/System32/OpenSSH/" "C:/Program Files (x86)/Visual Leak Detector/bin/Win32" "C:/Program Files (x86)/Visual Leak Detector/bin/Win64" "C:/ProgramData/chocolatey/lib/maven/apache-maven-3.6.3/bin" "C:/Program Files/Java/jdk1.8.0_221/bin" "C:/Program Files/LLVM/bin" "C:/ProgramData/chocolatey/lib/maven/apache-maven-3.6.3/bin" "C:/Program Files (x86)/Gpg4win/../GnuPG/bin" "C:/Program Files/dotnet/" "C:/Program Files/TortoiseGit/bin" "C:/Program Files/TortoiseSVN/bin" "C:/Program Files/nodejs/" "C:/Program Files/Microsoft SQL Server/130/Tools/Binn/" "~/.cargo/bin" "~/scoop/shims" "~/AppData/Local/Microsoft/WindowsApps" "~/Documents/bin" "C:/Program Files/CMake/bin" "~/AppData/Local/Microsoft/WindowsApps" "~/.dotnet/tools" "C:/Program Files/Emacs/x86_64/bin" "~/AppData/Local/Pandoc/" "~/.emacs.d/bin" "~/AppData/Roaming/npm" "C:/Program Files/NASM/" "~/.dotnet/tools" "c:/Program Files/Emacs/x86_64/libexec/emacs/27.0.60/x86_64-w64-mingw32"))
 (config
  (envfile)
  (elc-files . 0)
  (modules :completion company helm :ui doom doom-dashboard doom-quit fill-column hl-todo hydra modeline nav-flash ophints (popup +all +defaults) (pretty-code +fira) tabs treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold multiple-cursors rotate-text snippets :emacs dired electric ibuffer vc :term eshell term :checkers syntax :tools (eval +overlay) gist (lookup +docsets) lsp (magit +forge) make :lang cc csharp data emacs-lisp fsharp latex markdown (org +dragndrop +present) php python rst rust sh web :email (mu4e +gmail) :app calendar :config (default +bindings +smartparens))
  (packages (undo-tree) (hydra) (git-timemachine) (evil-collection) (pos-tip) (company) (counsel) (company-quickhelp) (company-web) (yasnippet) (yasnippet-snippets) (cmake-mode) (markdown-mode) (flymd) (impatient-mode) (edit-server) (which-key) (iedit) (yaml-mode) (powershell) (column-enforce-mode) (smerge-mode) (color-theme-sanityinc-tomorrow) (dap-mode) (multi-term) (powerline) (powerline-evil))
  (unpin "n/a")
  (elpa "n/a")))
</pre></details>

**Comment by hlissner** [comment]
I cannot reproduce this nor can I find anything in forge or evil-markdown (or any other package that vanilla Doom installs) that could be calling `evil-disable-insert-state-bindings` as a function. Could you try commenting out everything in your config.el, run `doom sync` and see if your issue goes away? If not, try `doom build` instead.

Side note, I see you've installed a lot of packages that Doom installs/sets up for you.

+ undo-tree: redundant with `:emacs (undo +tree)`
+ hydra: redundant with `:ui hydra` 
+ git-timemachine: redundant with `:emacs vc`
+ evil-collection: redundant with `:editor (evil +everywhere)`
+ company, company-quickhelp & pos-tip: redundant with `:completion company`
+ company-web: redundant with `:lang web`
+ yasnippet & yasnippet-snippets: redundant with `:editor snippets`
+ cmake-mode: redundant with `:lang cc`
+ markdown-mode: redundant with `:lang markdown`
+ which-key: already installed by Doom core
+ iedit: redundant with `:editor multiple-cursors` (the evil-multiedit package, specifically) 
+ yaml-mode: redundant with `:lang yaml`
+ smerge-mode: redundant with `:emacs vc`
+ dap-mode: redundant with `:tools debugger`
+ multi-term: redundant with `:term term` 

Resolve these and see if your issue goes away.

**Comment by rzikm** [comment]
I have tried removing redundant packages (thanks for going through all of them and pointing them out!), commenting out all of config.el file, but there was no change. Interestingly, it happens only on my Windows PC, everything seems to work OK in linux.

I also tried with doom build, same result. I will try reinstalling doom form scratch and see if it helps.

**Comment by rzikm** [comment]
The issue seems to go away after I did `doom update` and `doom upgrade`.
