### ISSUE TITLE
max-lisp-eval-depth in project structure ~/.doom.d/doom-emacs/

### ISSUE THREAD

**Issue by wrachwal** [hlissner/doom-emacs#3454]
I use `chemacs` loader and want to have `doom-emacs` kept as the Git submodule of my private doom config in `~/.doom.d`.

But this setup doesn't work at all. Just after start, I don't need to do anything, I wait of a while, then I get:
```
Failed to load ... because, (error: Lisp nesting exceeds `max-lisp-eval-depth'
```
Other attempts to do do anything later on ends with similar error message. The setup is unusable.

I don't think what I need is "unique". Keeping private config along with referenced tool (doom) under Git control seems reasonable requirement.

* GNU Emacs 27.0.91
* chemacs and doom-emacs from master

**Comment by hlissner** [comment]
> chemacs and doom-emacs from master

Did you install doom-emacs from its master branch? If so, this is the issue. Use the `develop` branch. Master is almost 3 years out of date and likely broken.

If it was a typo, then I'm struggling to reproduce this. Can you provide:

1. Concrete steps on how to reproduce it? 
2. Include the output of `~/.doom.d/doom-emacs/bin/doom info`.
3. Include what happened when you ran `~/.doom.d/doom-emacs/bin/doom sync`

Please do not ignore the issue template in the future.

**Comment by wrachwal** [comment]
Sorry for misleading, in case of doom-emacs it was obviously `develop`, the default branch.

I don't remember steps which brought to this situation.. it could be some false steps during transformation from earlier setup when I had doom-emacs separate.. don't know.

Now, after complete removal of doom-emacs and re-checkout (submodule update), then ..doom sync - everything works! Closing the issue.
