### ISSUE TITLE
lsp-auto-guess-root popup is hidden

### ISSUE THREAD

**Issue by jsravn** [hlissner/doom-emacs#3458]
**What did you expect to happen?**
With `(setq lsp-auto-guess-root nil)`, I expect to see the LSP project root popup when opening up a new LSP project.

**What actually happened?**
The popup never appears. However it still blocks on accepting input as if it appeared. So I can press "I" to select the project root. 

**Additional details:**
- Include a link to your private config
- Include screenshots/casts of your issue
- If you mention key sequences, include what commands they're bound to (use `SPC
  h k KEY` or `C-h h k KEY` to inspect keys).
- Include any warnings or errors logged to \*Messages\* (use `M-x
  view-echo-area-messages` to see it).

<details><pre>
If an error message is involved include a backtrace of it.

How to acquire a backtrace:
https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#how-to-extract-a-backtrace-from-an-error
</pre></details>

**Steps to reproduce:**
1. Select these example steps,
2. Delete them,
3. And replace them with precise steps to reproduce your issue.
4. Fill in "system information" below.

**System information:**
<details>

```
emacs   version    27.0.91
        features   XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GSETTINGS GLIB NOTIFY INOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER GMP
        build      Jun 25, 2020
        buildopts  (--prefix=/nix/store/ml1v43l873j4khjxr6zdz67mi7kmd8yz-emacs-27.0.91 --disable-build-details --with-modules --with-x-toolkit=gtk3 --with-xft CFLAGS=-DMAC_OS_X_VERSION_MAX_ALLOWED=101200)
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop 99eea1d3e 2020-06-21 13:53:58 -0400
        dir        ~/.config/doom/
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /run/current-system/sw/bin/zsh
        uname      Linux 5.6.18 #1-NixOS SMP Wed Jun 10 18:22:53 UTC 2020 x86_64
        path       (/nix/store/77b1j2kpky9f3kb3yrh95hl5ch8frj5x-kitty-0.16.0/bin/ /nix/store/02px3rrvk2qhcp3kx1an34vzsckcba9m-imagemagick-6.9.10-71/bin/ /nix/store/f8kmpp5vn8d0lh5la81f3nfl5x9j4z1v-xsel-unstable-2019-08-21/bin/ /nix/store/03j792lhxkb358lzq7bmivq0n7bknva0-ncurses-6.1-20190112-dev/bin/ /nix/store/rl0zf16h9f4zmqxzyvbgkj3gkxl8izys-swaybg-1.0/bin/ /run/wrappers/bin/ ~/.config/emacs/bin/ ~/.cache/npm/bin/ ~/go/bin/ ~/.nixfiles/bin/ ~/.nix-profile/bin/ /etc/profiles/per-user/james/bin/ /nix/var/nix/profiles/default/bin/ /run/current-system/sw/bin/ /nix/store/ml1v43l873j4khjxr6zdz67mi7kmd8yz-emacs-27.0.91/libexec/emacs/27.0.91/x86_64-pc-linux-gnu/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion (company +childframe) (ivy +fuzzy +icons) :ui doom doom-dashboard hl-todo indent-guides modeline nav-flash ophints (popup +all +defaults) (pretty-code +pragmata-pro) treemacs vc-gutter vi-tilde-fringe window-select workspaces zen :editor (evil +everywhere) fold format multiple-cursors rotate-text snippets word-wrap :emacs dired electric vc :term vterm :checkers syntax spell :tools ansible docker direnv editorconfig (eval +overlay) (lookup +docsets +dictionary) (lsp +peek) (magit +forge) make terraform :lang (cc +lsp) (clojure +cider +lsp) common-lisp data emacs-lisp (go +lsp) (java +lsp) (javascript +lsp) markdown nix (org +dragndrop +journal +roam) (python +lsp +pyenv) sh scheme (yaml +lsp) :email mu4e :config literate (default +bindings +smartparens))
        packages   ((atomic-chrome) (org-roam :pin 4af4d2e4d5f18422fe0f90d5d83fe4c10ef1a20f) (org-msg) (org-alert) (caddyfile-mode))
        unpin      (lsp-mode)
        elpa       (vterm)
```
</details>

**Comment by hlissner** [comment]
I cannot reproduce this on vanilla Doom on Emacs 26 or 27, in js2-mode, rustic-mode or python-mode on NixOS or Mojave (VM).

**Comment by hlissner** [comment]
Try deleting `~/.emacs.d/.local/etc/lsp-session` manually, or bisecting (or disabling) your private config.

**Comment by jsravn** [comment]
Thanks for looking. I will try to dig further in that case.

**Comment by jsravn** [comment]
Seems to always happen with yaml-mode.

**Comment by socksy** [comment]
Have the issue too, with clojure-lsp. N.B. the popup appears fine if `lsp` is run using `SPC c l s s`, but not with a clean slate (i.e. no `.local/etc/lsp-session` set up, removed `.lsp/sqlite.1.db` in the project etc), but fails to show up when opening a file for the first time in the project.

**Comment by anihm136** [comment]
I have also faced this issue when using c++ (clangd). However, it hasn't been regularly failing (i.e, doesn't always fail when opening a new file, but sometimes it does)

**Comment by jsravn** [comment]
Just to update this is still happening in the latest doom. It happens almost every time for golang projects.

**Comment by jsravn** [comment]
Still happening for me. I haven't found a way to reliably reproduce it though :(.

**Comment by socksy** [comment]
@jsravn i think i solved this locally when i realized i had a `.git` file (but not a git repo 🤦 ) in my `$HOME` dir, perhaps worth looking into?
