### ISSUE TITLE
'doom sync' stuck at 'Building auctex'.

### ISSUE THREAD

**Issue by smallzhan** [hlissner/doom-emacs#3459]
**What did you expect to happen?**
Successful building auctex and sync.

**What actually happened?**
after building some packages, stucking at
     
     - Checked out 6abf890a485b2ff734d8f87f38393f9b8f6bbbf6
     → Building auctex...

**Steps to reproduce:**
1. uncomment the 'latex' at :lang section in init.el
2. run 'doom sync', it always stuck at `building auctex...',  when comment 'latex', 'doom sync' would succeed.  I've tried 'doom -d sync', no difference.

**System information:**
<details><pre>
((emacs
  (version . "27.0.91")
  (features . "RSVG DBUS GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS XWIDGETS JSON PDUMPER LCMS2 GMP")
  (build . " 6 23, 2020")
  (buildopts "--disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus@27/27.0.91/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus@27/27.0.91 --with-xml2 --with-gnutls --with-dbus --without-imagemagick --with-json --with-modules --with-rsvg --with-xwidgets --with-ns --disable-ns-self-contained")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop 0443eeb6a 2020-06-24 20:09:17 -0400")
  (dir . "~/.doom.d.nothing/"))
 (system
  (type . darwin)
  (config . "x86_64-apple-darwin19.5.0")
  (shell . "/bin/zsh")
  (uname . "Darwin 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64")
  (path "/usr/local/opt/qt/bin" "/usr/local/Cellar/zplug/2.4.2/bin" "/usr/local/bin" "/usr/bin" "/bin" "/usr/sbin" "/sbin" "/Library/TeX/texbin" "/Applications/Wireshark.app/Contents/MacOS" "~/.golang/bin" "/usr/local/opt/go/libexec/bin" "~/Library/Android/sdk/tools" "~/Library/Android/sdk/platform-tools" "/usr/local/opt/llvm/bin" "~/bin" "/usr/local/opt/fzf/bin" "/usr/local/Cellar/emacs-plus@27/27.0.91/libexec/emacs/27.0.91/x86_64-apple-darwin19.5.0"))
 (config
  (envfile . envvar-file)
  (elc-files . 1)
  (modules :completion company ivy :ui doom doom-dashboard doom-quit modeline ophints (popup +defaults) workspaces :emacs dired electric :checkers syntax :tools (eval +overlay) lookup magit :lang emacs-lisp latex org sh :config (default +bindings +smartparens))
  (packages "n/a")
  (unpin "n/a")
  (elpa "n/a")))

</pre></details>

**Comment by socksy** [comment]
@smallzhan I can not recreate this, auctex is building fine on my machine after uncommenting `latex` in my `init.el`.
<details><summary>The exact output</summary>
<pre>
> Synchronizing your config with Doom Emacs...
  > Installing packages...
    > Updating recipe repos...
    → Cloning auctex...s for emacsmirror-mirror...
    → Cloning auctex...done
    - Checked out 6abf890a485b2ff734d8f87f38393f9b8f6bbbf6
    → Building auctex...
    → Building auctex...done
    → Cloning adaptive-wrap...
    → Cloning adaptive-wrap...done
    - Checked out 1810c0ee8d827dd502ddeaae5bd759d4811fcbce
    → Building adaptive-wrap...
    → Building adaptive-wrap...done
    → Cloning latex-preview-pane...
    → Cloning latex-preview-pane...done
    - Checked out 5297668a89996b50b2b62f99cba01cc544dbed2e
    → Building latex-preview-pane...
    → Building latex-preview-pane...done
    → Cloning company-auctex...
    → Cloning company-auctex...done
    - Checked out 9400a2ec7459dde8cbf1a5d50dfee4e300ed7e18
    → Building company-auctex...
    → Building company-auctex...done
    → Cloning company-reftex...
    → Cloning company-reftex...done
    - Checked out 275ef708f08d3bf0eb30632148e5c6184eeaacdb
    → Building company-reftex...
    → Building company-reftex...done
    → Cloning company-math...
    → Cloning company-math...done
    - Checked out a796053590012e6a15c8b527b521ffc15d137bd0
    → Building company-math...
    → Building company-math → Cloning math-symbol-lists...
    → Building company-math → Cloning math-symbol-lists...done
    → Building company-math → Building math-symbol-lists...
    → Building company-math → Building math-symbol-lists...done
    → Building company-math...
    → Building company-math...done
    ✓ Installed 7 packages
</pre>
</details>

<details>
<summary>M-x doom/info</summary>

```
emacs   version    26.2
        features   JPEG RSVG IMAGEMAGICK GLIB NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2
        build      Apr 21, 2019
        buildopts  (--disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus/26.2/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus/26.2 --with-xml2 --without-dbus --with-gnutls --with-imagemagick --with-modules --with-rsvg --with-ns --disable-ns-self-contained)
        windowsys  ns
        daemonp    daemon
doom    version    2.0.9
        build      HEAD -> develop 0443eeb6a 2020-06-24 20:09:17 -0400
        dir        ~/.doom.d/
system  type       darwin
        config     x86_64-apple-darwin18.2.0
        shell      /bin/bash
        uname      Darwin 18.7.0 Darwin Kernel Version 18.7.0: Mon Apr 27 20:09:39 PDT 2020; root:xnu-4903.278.35~1/RELEASE_X86_64 x86_64
        path       (/usr/local/bin /usr/bin /bin /usr/sbin /sbin /Library/TeX/texbin ~/pitch-app/scripts ~/.nvm/versions/node/v10.13.0/bin ~/.nix-profile/bin ~/bin ~/.npm-packages/bin ~/go/bin ~/.emacs.d.doom/bin /usr/local/Cellar/emacs-plus/26.2/libexec/emacs/26.2/x86_64-apple-darwin18.2.0)
config  envfile    nil
        elc-files  0
        modules    (:completion company (helm +fuzzy) :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash neotree ophints (popup +all +defaults) pretty-code unicode vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold multiple-cursors rotate-text snippets :emacs (dired +icons) electric vc :term eshell :tools debugger direnv eval :checkers syntax spell :tools gist (lookup +docsets) macos magit (pass +auth) rgb upload :lang clojure data emacs-lisp markdown nix (org +dragndrop +ipython +pandoc +present) python racket rest ruby scheme sh web :email (mu4e +gmail) :app calendar (rss +org) :config (default +bindings +smartparens))
        packages   ((org-fancy-priorities) (org-super-agenda) (org-gcal) (emojify) (org-alert) (google-maps) (helm-spotify-plus) (git-link))
        unpin      (n/a)
        elpa       (n/a)
```
</details>

**Comment by hlissner** [comment]
I can't reproduce this either. Try deleting `~/.emacs.d/.local/straight/repos/auctex` manually, then run `doom sync` again.

**Comment by smallzhan** [comment]
No help of deleting `~/.emacs.d/.local/straight/repos/auctex`,  seems that the building stuck at byte-compile. Now I've add
`(packages! auctex :recpie (:no-byte-compile t))`  and them byte-compile the package manually.

**Comment by smallzhan** [comment]
Semms very strange, I've tried emacs-mac with version 26.3, and it is ok with auctex building.

**Comment by smallzhan** [comment]
Its OK on emacs 27.1 release.  Close this issue.
