### ISSUE TITLE
Bug: `M-d` shortcut of the `multiple-cursors` module

### ISSUE THREAD

**Issue by p1tt1** [hlissner/doom-emacs#3461]
**What did you expect to happen?**
- I've enabled `multiple-cursors`
- If the cursor is a single word and I use the shortcut 'M-d' repeatedly, all existing words should be selected one after the other.

**What actually happened?**
- No word is selected.
- I kept the message: I-search backward: [No previous search string]

**Additional details:**
- When I map the command `evil-multiedit-match-symbol-and-next` to the shortcut `:leader "d"` the function works as expected.

**System information:**
<details><pre>
((emacs
  (version . "26.3")
  (features . "JPEG RSVG IMAGEMAGICK GLIB NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2")
  (build . "Jun 24, 2020")
  (buildopts "--disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus@26/26.3/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus@26/26.3 --with-xml2 --with-gnutls --with-imagemagick --with-modules --with-rsvg --with-ns --disable-ns-self-contained")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD 99eea1d3e 2020-06-21 13:53:58 -0400")
  (dir . "~/.doom.d/"))
 (system
  (type . darwin)
  (config . "x86_64-apple-darwin19.5.0")
  (shell . "/usr/local/bin/fish")
  (uname . "Darwin 19.5.0 Darwin Kernel Version 19.5.0: Thu Apr 30 18:25:59 PDT 2020; root:xnu-6153.121.1~7/RELEASE_X86_64 x86_64")
  (path "~/.asdf/shims" "/usr/local/opt/asdf/shims" "/usr/local/opt/asdf/bin" "~/.emacs.d/bin/" "~/git/helpscripts/" "~/.nix-profile/bin" "/usr/local/bin" "/usr/bin" "/bin" "/usr/sbin" "/sbin" "/opt/X11/bin" "/Library/Apple/usr/bin" "/Library/TeX/texbin" "/usr/local/Cellar/emacs-plus@26/26.3/libexec/emacs/26.3/x86_64-apple-darwin19.5.0"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline ophints (popup +defaults) vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold multiple-cursors snippets :emacs dired electric undo vc :checkers syntax :tools (eval +overlay) lookup magit :lang emacs-lisp markdown org sh :config (default +bindings +smartparens))
  (packages "n/a")
  (unpin "n/a")
  (elpa "n/a")))

</pre></details>

**Comment by happysalada** [comment]
Remapping it to anything else worked for me.

If it can help anyone else, here is what I added in my config.el

```
(map! :nv
      "C-d" #'evil-multiedit-match-symbol-and-next
      "C-D" #'evil-multiedit-match-symbol-and-prev)
```

remapping it to Ctrl-d

**Comment by hlissner** [comment]
> I kept the message: I-search backward: [No previous search string]

I can't reproduce this in vanilla Doom. Can you check `SPC h k M-d` to see what is bound to it and where? 

> If it can help anyone else, here is what I added in my config.el

@happysalada Your snippet is incorrect. `:nv` only applies to the first keybind that follows it. `C-D` is being bound on the global keymap.

```elisp
(map! :nv "C-d" #'evil-multiedit-match-symbol-and-next
      :nv "C-D" #'evil-multiedit-match-symbol-and-prev)
```

**Comment by happysalada** [comment]
Thanks for the correction!

Here is what I get running your command

```
isearch-repeat-backward is an interactive and compiled function
defined in isearch.el.gz.

Signature
(isearch-repeat-backward &optional ARG)
```

I guess it's just a matter of unmapping it then, right?

**Comment by p1tt1** [comment]
working now without problems.

`(doom
  (dir . "~/.doom.d/")
  (version . "2.0.9")
  (build . "HEAD -> develop 1456108d5 2020-09-10 18:03:32 -0400")
  (elc-files . 0)`

**Comment by jonasagx** [comment]
here is my setup and the shortcut doesn't work for me

```
SYSTEM  type       darwin
        config     x86_64-apple-darwin19.5.0
        shell      /bin/zsh
        uname      Darwin 20.1.0 Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:11 PDT 2020; root:xnu-7195.50.7~2/RELEASE_X86_64 x86_64
        path       (/usr/local/Cellar/go/1.15.5/libexec ~/go ~/.emacs.d/bin/ ~/sandbox/v/ ~/.aliases.d/shims /usr/local/opt/llvm/bin ~/.local/bin ~/.local/bin ~/.cargo/bin ~/Library/Python/3.8/bin ~/.bin ~/go/bin ~/Downloads/google-cloud-sdk/bin ~/.cargo/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /Library/TeX/texbin /usr/local/go/bin /usr/local/MacGPG2/bin /opt/X11/bin /Library/Apple/usr/bin /Applications/Wireshark.app/Contents/MacOS ~/go/src/github.com/lytics/lio/bin ~/go/bin /usr/local/Cellar/emacs-plus@27/27.1/libexec/emacs/27.1/x86_64-apple-darwin19.5.0/)
EMACS   dir        ~/.emacs.d/
        version    27.1
        build      Aug 27, 2020
        buildopts  --disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus@27/27.1/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus@27/27.1 --with-xml2 --with-gnutls --without-dbus --with-imagemagick --with-modules --with-rsvg --with-ns --disable-ns-self-contained
        features   RSVG IMAGEMAGICK GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS JSON PDUMPER LCMS2 GMP
        traits     (gui server-running envvar-file)
DOOM    dir        ~/.doom.d/
        version    2.0.9
        font       #<font-spec nil nil JetBrains Mono nil nil nil nil nil 16 nil nil nil nil>
        theme      doom-snazzy
        build      grafted, HEAD -> develop, origin/develop, origin/HEAD a50db62 2020-11-29 23:25:38 -0500
        elc-files  0
        modules    (:completion (company +childframe) (ivy +fuzzy) :ui doom-dashboard hl-todo modeline nav-flash (popup +all +defaults) ophints workspaces :editor (evil +everywhere) file-templates fold (format +onsave) multiple-cursors word-wrap :emacs (dired +icons) (undo +tree) vc :term vterm :os macos tty :checkers syntax spell grammar :tools docker (eval +overlay) lookup lsp magit terraform tmux upload :lang cc data (emacs-lisp +lsp) (go +lsp) markdown :config (default +bindings +smartparens))
        packages   ((ag) (diminish) (doom-modeline) (gruvbox-theme) (jsonnet-mode) (lsp-mode) (lsp-ui) (protobuf-mode) (rainbow-identifiers) (rust-mode) (solaire-mode :disable t) (yaml-mode) (yasnippet) (fountain-mode) (almost-mono-themes) (git-link))
        unpin      (doom-themes)
        elpa       (n/a)
```

**Comment by jrasanen** [comment]
On macOS Alt-d is bound to `kill word` and Command-d to `isearch-repeat-backwards` after enabling the Lisp support I think.

![CleanShot 2021-02-23 at 08 56 47](https://user-images.githubusercontent.com/13303/108811015-195d3000-75b5-11eb-9782-cc25e1a2a5a2.png)


![CleanShot 2021-02-23 at 08 54 43](https://user-images.githubusercontent.com/13303/108810928-e1ee8380-75b4-11eb-8797-55650a8942f1.png)
