### ISSUE TITLE
+helm/project-search is broken

### ISSUE THREAD

**Issue by socksy** [hlissner/doom-emacs#3463]
**What did you expect to happen?**
When you search with `+helm/project-search`, to get results

**What actually happened?**
No results

**Additional details:**
[Pretty sure this is an upstream issue of helm-rg](https://github.com/cosmicexplorer/helm-rg/issues/26). But it's been 2 weeks now with no fix, so it's getting quite annoying. I would suggest that we either change the version in the meantime to be from the PR that fixes it (https://github.com/cosmicexplorer/helm-rg/pull/25), or to switch to another package like [emacs-helm-ag](https://github.com/bridgesense/emacs-helm-ag) (which, despite the name, supports ripgrep too).

**Comment by nujabse** [comment]
Is this fixed in Doom emacs? Looks like the upstream has fixed it, but I still cannot get any results from `+helm/project-search`.

**Comment by socksy** [comment]
Looks like Doom points at the latest commit of `helm-rg` since 4 days ago: https://github.com/hlissner/doom-emacs/commit/15f0bccde57538812e64f1c12771bc454aa254c6#diff-eb2145e36a2216a90f2806ae0f65f5ccR5

I had been holding off upgrading because of this, so I just tried it and `+helm/project-search` seems to work for me after upgrading, so I'd say that if it isn't working for you, try a `doom upgrade`. But IMO this issue can be closed as solved
