### ISSUE TITLE
How do I get Doom init time without "doom-dashboard"?

### ISSUE THREAD

**Issue by mrbig033** [hlissner/doom-emacs#3467]
I commented out `doom-dashboard` from my init, but I'd like to have access to the Doom Init values time it used display. `emacs-init-time` works, but it gives a different value so I'm not sure which one is more accurate.

Furthermore, what is the relationship between `doom-dashboard` benchmark and the value I get from `emacs-init-time`? Which is more accurate?

**Comment by hlissner** [comment]
See `SPC h v doom-init-time` (or `C-h v doom-init-time`).

It is also written to your `*Messages*` buffer (`SPC h e` / `C-h e` to open it).
