### ISSUE TITLE
Fatal error issue when installing doom

### ISSUE THREAD

**Issue by bencow98054** [hlissner/doom-emacs#3469]
**What did you expect to happen?**
...for the  'git clone https://github.com/hlissner/doom-emacs ~/.emacs.d' command to begin installation correctly

**What actually happened?**
...I received an error of this form after inputing the command 
>myusername$ git clone https://github.com/hlissner/doom-emacs ~/.emacs.d

>fatal: '/Users/myusername/.emacs.d' already exists and is not an empty directory.

Hello! I'm pretty gnu to emacs (haha sorry) and currently trying to install doom! However, I have been running into this issue where I get the above fatal error when I try running the git clone command. 
I was just wondering if anyone else has run into this issue when installing doom for the first time and or how to solve it. It looks like it isnt writing into .emacs.d directory correctly? 
It appears that the only thing currently inside the .emacs.d directory is another directory called 'auto-saved-list' but outside of that, nothing appears to be going into it....
Thanks!

**Comment by hlissner** [comment]
> fatal: '/Users/myusername/.emacs.d' already exists and is not an empty directory.

This error means that `~/.emacs.d` already exists. You can't clone to a directory that already exists. Delete it first, then run the command again. i.e.

```sh
rm -rf ~/.emacs.d
git clone https://github.com/hlissner/doom-emacs ~/.emacs.d
```

**Comment by bencow98054** [comment]
Wow. Thanks for the fast response!!!! Thank you so much!! It worked haha.
