### ISSUE TITLE
behavior of Switch Project on startup

### ISSUE THREAD

**Issue by vikigenius** [hlissner/doom-emacs#347]
I am struggling to switch project on startup.
By default emacs always seems to be cd-ing into ~/.emacs.d  : I followed the issue on https://github.com/hlissner/doom-emacs/issues/309.

And according to it, it seems that doom is supposed to automatically cd into the root of the previous project you had open?

However, my dashboard always starts on ~/.emacs.d, 

Even if i tried to execute the projectile-switch-project command and successfully switch the project and switch to the new workspace it created, the default directory still seems to be in ~/.emacs.d and browse  project files is browsing the files in my emacs directory and not the project directory.

**Comment by rphillips** [comment]
I'm seeing this issue as well.

**Comment by hlissner** [comment]
I recently switched to a new mechanism for starting the dashboard (`(setq initial-buffer-choice #'+doom-dashboard)`), which inadvertantly re-initializes the dashboard (with a default pwd of `~/.emacs.d`) everytime a new frame (or workspace+project) is opened.

The fix is now up on `develop`. Let me know if it solves the issue.

I'll keep this open until it hits `master`.

**Comment by rphillips** [comment]
I tried the latest develop, and the behavior persists.

**Comment by rphillips** [comment]
I can't find a wayland desktop recorder... If you need more steps to reproduce, just let me know.

**Comment by hlissner** [comment]
@rphillips I've made a few big changes on `develop` to the dashboard behind the scenes. Has it resolved this issue for you?

**Comment by rphillips** [comment]
it switches directories for me now correctly. The find file doesn't pop up automatically anymore - I felt that was nice. Thank you!

**Comment by hlissner** [comment]
As did I. It had to go, temporarily, to accommodate recent changes. I'll put it back in once I've figured out a good way to do so.

**Comment by hlissner** [comment]
@rphillips Just an fyi: the find-file popup is back in.

**Comment by rphillips** [comment]
thank you!
