### ISSUE TITLE
Octave Mode in Doom

### ISSUE THREAD

**Issue by alexpetrean80** [hlissner/doom-emacs#3471]
**Describe the feature**
It would be beneficial having it as a prepackaged mode in init.el, as I feel there are a lot of people who use Octave/Matlab and would like to be able to use it inside emacs. I don't know how the plotting would be done though.

**Comment by tecosaur** [comment]
`octave-mode` seems to be already present in Emacs 21 and later. Are there any packages and/or config which you think an `octave` module in doom should do?

From a quick google, I can't really see anything.
