### ISSUE TITLE
doom emacs not opening after installation...

### ISSUE THREAD

**Issue by bencow98054** [hlissner/doom-emacs#3475]
**What did you expect to happen?**
...
When I run "emacs" in the terminal command line, I expected doom emacs to load after I had successfully run and finished:
"~/.emacs.d/bin/doom sync" 

**What actually happened?**
...
Upon running the "emacs" command in terminal, it loads the default emacs environment instead of the supposedly "synced" doomemacs environment. I looked in my bin for my .emacs.d and it appears that everything installed correctly. How can I get doom emacs to run? Maybe there is a different way to restart emacs and update it but the "M-x doom/reload" comes up as "no match" in the emacs command line. Nor when I quit emacs entirely and refresh it does any change appear to happen. 
For reference: this is what is inside my ~/.emacs.d after installation

LICENSE		bin		early-init.el	modules
README.md	core		init.el		test
auto-save-list	docs		init.example.el

and this is what is inside my bin:

doom		doom.cmd	org-capture	org-tangle

After running bin/doom doctor, this is the output I got:

The doctor will see you now...

> Checking your Emacs version...
> Checking for Emacs config conflicts...
! Detected an ~/.emacs file, which may prevent Doom from loading
  If Emacs finds an ~/.emacs file, it will ignore ~/.emacs.d, where Doom is
  typically installed. If you're seeing a vanilla Emacs splash screen, this
  may explain why. If you use Chemacs, you may ignore this warning.
> Checking for private config conflicts...
> Checking for stale elc files...
> Checking Doom Emacs...
  ✓ Initialized Doom Emacs 2.0.9
  ✓ Detected 29 modules
  ✓ Detected 120 packages
  > Checking Doom core for irregularities...
    x Couldn't find the `rg' binary; this a hard dependecy for Doom, file searches may not work at all
    ! Couldn't find the `fd' binary; project file searches will be slightly slower
    Found font material-design-icons.ttf
    Found font weathericons.ttf
    Found font octicons.ttf
    Found font fontawesome.ttf
    Found font file-icons.ttf
    Found font all-the-icons.ttf
  > Checking for stale elc files in your DOOMDIR...
  > Checking your enabled modules...
    > :emacs dired
      ! Cannot find gls (GNU ls). This may cause issues with dired
    > :lang markdown
      ! Couldn't find a markdown compiler, `markdown-preview' won't work
    > :lang sh
      ! Couldn't find shellcheck. Shell script linting will not work

There are 1 errors!
There are 5 warnings!
✓ Finished! (4.7864s)

 

**Additional details:**
- Include a link to your private config
- Include screenshots/casts of your issue
- If you mention key sequences, include what commands they're bound to (use `SPC
  h k KEY` or `C-h h k KEY` to inspect keys).
- Include any warnings or errors logged to \*Messages\* (use `M-x
  view-echo-area-messages` to see it).

<details><pre>
If an error message is involved include a backtrace of it.

How to acquire a backtrace:
https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#how-to-extract-a-backtrace-from-an-error
</pre></details>

**Steps to reproduce:**
1. Select these example steps,
2. Delete them,
3. And replace them with precise steps to reproduce your issue.
4. Fill in "system information" below.

**System information:**
<details><pre>
Place the output of `M-x doom/info` or `~/.emacs.d/bin/doom info` here.
</pre></details>

**Comment by hlissner** [comment]
To quote what the doctor told you:

> ! Detected an ~/.emacs file, which may prevent Doom from loading
If Emacs finds an ~/.emacs file, it will ignore ~/.emacs.d, where Doom is
typically installed. If you're seeing a vanilla Emacs splash screen, this
may explain why. If you use Chemacs, you may ignore this warning.

**Comment by bencow98054** [comment]
Thank you!! IT WORKS!!!!
