### ISSUE TITLE
how to show icons?

### ISSUE THREAD

**Issue by kecode** [hlissner/doom-emacs#3477]
hello , I have M-x all-the-icons-install-fonts installed，but not show. What should I do? Ask for help 

my configuration is to copy your "init.example.el" .

![image](https://user-images.githubusercontent.com/23140388/85918742-02d0ce80-b898-11ea-90ad-20cd5bcff8d4.png)
![image](https://user-images.githubusercontent.com/23140388/85918887-3e1fcd00-b899-11ea-8461-910cb1ec485d.png)

**Comment by hlissner** [comment]
At a glance, it seems you're using Emacs in the terminal. Emacs doesn't support multiple fonts in the terminal and so cannot display icons. I'm afraid your only option is to use GUI Emacs or give up on icons.

Side note: please do not ignore the issue template in the future. At the very least, include your `M-x doom/info` whenever filing a bug report.

**Comment by kecode** [comment]
> At a glance, it seems you're using Emacs in the terminal. Emacs doesn't support multiple fonts in the terminal and so cannot display icons. I'm afraid your only option is to use GUI Emacs or give up on icons.
> 
> Side note: please do not ignore the issue template in the future. At the very least, include your `M-x doom/info` whenever filing a bug report.

Thank you very much, as you said. I will pay attention to the format of the questions later
