### ISSUE TITLE
Additional Variable for Personal File Template Directory

### ISSUE THREAD

**Issue by Janfel** [hlissner/doom-emacs#3482]
**Feature**
Doom should have two variables for snippet directories, analogous to `+snippets-dir` and `doom-snippets-dir`, where one points to the predefined templates, and the other points to the user’s templates, e.g. `$DOOMDIR/templates`.

**Rationale**
Currently there is only one variable describing the location of file templates, namely `+file-templates-dir`. This limits the user to one of these possibilities, if they want to use their own templates.

1. Add their templates to `+snippets-dir`, mixing snippets and templates.
1. Replace the value of `+file-templates-dir` with `$DOOMDIR/templates`, removing access to all predefined templates.
1. Adding `$DOOMDIR/templates` manually to `yas-snippet-dirs`, having a variable with a misleading name floating around.

**Steps to Implement**
- Add a variable (e.g. `+file-templates-default-dir`) that is set to the current default value of `+file-templates-dir`.
- Set the default value of `+file-templates-dir` to `nil` or `$DOOMDIR/templates`.
- Make sure both symbols are added to `yas-snippet-dirs` when initializing `:editor/file-templates`.

**Comment by hlissner** [comment]
It is intended that you put both your file templates and snippets in `~/.doom.d/snippets`. I don't want to add more "magic" directories and files to `~/.doom.d` than I have to.

Feel free to add `~/.doom.d/templates` to `yas-snippet-dirs` if you'd like another snippet directory.
