### ISSUE TITLE
File local-variables error: (doom-hook-error +cc-init-lsp-h (void-function lsp!))

### ISSUE THREAD

**Issue by ethercflow** [hlissner/doom-emacs#3486]
**What did you expect to happen?**

No error happens, when I open *.c file, the lsp-server can work as expect.

**What actually happened?**

Open a *.c file, mini buffer show: 

> File local-variables error: (doom-hook-error +cc-init-lsp-h (void-function lsp!))

and lsp server exit.

**Steps to reproduce:**
1. SPC p p to open a C project and open a *.c file

**System information:**
<details><pre>
```
emacs   version    27.0.90
        features   XPM JPEG TIFF GIF PNG SOUND GSETTINGS GLIB NOTIFY INOTIFY GNUTLS FREETYPE HARFBUZZ XFT ZLIB TOOLKIT_SCROLL_BARS GTK2 X11 XDBE XIM MODULES THREADS PDUMPER GMP
        build      Apr 14, 2020
        buildopts  ()
        windowsys  nil
        daemonp    nil
doom    version    2.0.9
        build      HEAD -> develop 25b240b9b0b0 2020-06-28 01:09:54 -0400
        dir        ~/.config/doom/
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /usr/bin/zsh
        uname      Linux 5.8.0-rc1+ #81 SMP Thu Jun 25 22:04:52 EDT 2020 x86_64
        path       (~/.cargo/bin /workspace/kernel/bin/bin ~/.cargo/bin /workspace/kernel/bin/bin /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /usr/games /usr/local/games /usr/share/bcc/tools /usr/local/go/bin /workspace/go/bin /workspace/go/src/github.com/google/syzkaller/tools ~/systemtap-4.2-40535/bin /snap/bin /opt/node-v12.16.0-linux-x64/bin /usr/share/bcc/tools /usr/local/go/bin /workspace/go/bin /workspace/go/src/github.com/google/syzkaller/tools ~/systemtap-4.2-40535/bin /snap/bin /opt/node-v12.16.0-linux-x64/bin /usr/local/libexec/emacs/27.0.90/x86_64-pc-linux-gnu)
config  envfile    nil
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold multiple-cursors rotate-text snippets :emacs dired electric ibuffer vc :term term :checkers syntax :tools docker (eval +overlay) fasd (lookup +docsets) lsp magit wakatime :lang (cc +lsp) data emacs-lisp (go +lsp) json kernel lua markdown (org +dragndrop +ipython +pandoc +present) (python +lsp) (rust +lsp) sh yaml :config (default +bindings +smartparens))
        packages   (n/a)
        unpin      (n/a)
        elpa       (n/a)
```
</pre></details>

**Comment by hlissner** [comment]
Not sure how it's possible that an autodef like `lsp!` isn't defined. An autodef is always defined, even if the containing module isn't enabled.

1. Did you remember to run `doom sync` last time you modified `~/.doom.d/init.el`?
2. Check \*Messages\* (`SPC h e` or `C-h e` to open it) for errors/warnings at startup; possibly an unrelated startup error.
3. Does `doom build` fix it?

**Comment by ethercflow** [comment]
> Not sure how it's possible that an autodef like `lsp!` isn't defined. An autodef is always defined, even if the containing module isn't enabled.
> 
> 1. Did you remember to run `doom sync` last time you modified `~/.doom.d/init.el`?
Yes, I tried it.
> 2. Check *Messages* (`SPC h e` or `C-h e` to open it) for errors/warnings at startup; possibly an unrelated startup error.
No error or warning.
> 3. Does `doom build` fix it?
No, I tried but the problem still exist.

**Comment by ethercflow** [comment]
After a clean reinstall, the problem gone. Thanks.
