### ISSUE TITLE
Update Emacs requirement in Documentation

### ISSUE THREAD

**Issue by vikigenius** [hlissner/doom-emacs#349]
Some of the window functions you are using in develop for the popup management system
are not available in emacs 25. They seem to have been added in emacs26, maybe you can avoid those functions or at least maybe update the requirement in the docs for develop, so others won't face this issue?

**Comment by UndeadKernel** [comment]
I have also experienced this same problem.
With the latest commits in develop, all window display functions are broken.

I'm using Arch with emacs 25.3-2 (the current stable version in arch).

**Comment by vikigenius** [comment]
@UndeadKernel I checked the emacs repo and git blame reveals that those functions were indeed added after emacs 26, so i switched to emacs-snapshot, and the window functions are fixed.

I will probably wait for this to be fixed and then switch back to stable emacs, Emacs snapshots do tend to give problems from time to time.

**Comment by hlissner** [comment]
You're correct. However, I'd like to retain Emacs 25.x compatibility so I've polyfilled the necessary function calls. Give it a try and let me know if you get anymore errors.

**Comment by vikigenius** [comment]
Some of the variables are undefined as well. The `window-sides-reversed` variable also seems to be added post emacs26.

**Comment by hlissner** [comment]
I believe I've polyfilled all emacs 26+ only variables and functions for emacs 25 users, so I'll consider this resolved.

Just an FYI: now that Emacs 26.1 is officially released, I'll be dropping Emacs 25.x support around the end of the year.
