### ISSUE TITLE
package! with pinning a specific commit does not update the commit in the straight repo directory.

### ISSUE THREAD

**Issue by hankook** [hlissner/doom-emacs#3490]
Hi, I'm an user of Doom Emacs. I have a question about how to manage packages with pinning.

I am currently writing a custom module and its `packages.el` is as follows:

```
(package! bibtex-completion
  :pin "f80546f92870959951deb8fb8d3cb1a24ba6cfad"
  :recipe (:host github :repo "tmalsburg/helm-bibtex"))
(package! ivy-bibtex
  :pin "f80546f92870959951deb8fb8d3cb1a24ba6cfad"
  :recipe (:host github :repo "tmalsburg/helm-bibtex"))

(package! org-roam :pin "e33c3bcb3fae6927b023212a061c2273f0b9dea7")
(package! org-roam-bibtex :pin "a9a7d232ce25d06880aa2ed16148615af7e551a7")
```

In my `.doom.d/init.el`, the `biblio` module is currently disabled and my module is enabled. However, after `bin/doom sync`, the current git commit is still `b14b628` in the straight repository `~/.emacs.d/.local/straight/repos/helm-bibtex`.

I tried to find solutions for this issue, but I failed to find them. Did I do something wrong? How to change this commit?

Thanks in advance.

**Comment by hlissner** [comment]
`doom sync` alone does not update pinned packages. I'm working on a CLI rewrite to address that, but for the time being you need to run `doom sync -u`.

**Comment by hankook** [comment]
Thanks! `doom sync -u` updates package versions correctly. You may close this issue.

**Comment by hlissner** [comment]
I've moved this and many other issues to #4273. Please keep track of it there.
