### ISSUE TITLE
un-hook-with-args-until-success: Symbol’s function definition is void: doom-set-jump-h

### ISSUE THREAD

**Issue by gdupret** [hlissner/doom-emacs#3491]
**What did you expect to happen?**
when clicking on a url, I expect the url to be open in the browser. It used to work until recently

**What actually happened?**

nothing happens but the following message:
un-hook-with-args-until-success: Symbol’s function definition is void: doom-set-jump-h

**Additional details:**

C-h f doesn't list doom-set-jump-h
I upgraded to revision 46d6d0b586, but the same problem was arising in 39bb3aa72d

<details><pre>
If an error message is involved include a backtrace of it.

How to acquire a backtrace:
https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#how-to-extract-a-backtrace-from-an-error
</pre></details>

**Steps to reproduce:**
1. click on any url in orgmode
2. nothing happens

**System information:**
<details><pre>
<details>

```
emacs   version    26.3
        features   JPEG RSVG IMAGEMAGICK GLIB NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2
        build      Nov 17, 2019
        buildopts  (--disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus/26.3/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus/26.3 --with-xml2 --without-dbus --with-gnutls --with-imagemagick --with-modules --with-rsvg --with-ns --disable-ns-self-contained)
        windowsys  ns
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop 46d6d0b58 2020-06-29 15:12:30 -0400
        dir        ~/.doom.d/
system  type       darwin
        config     x86_64-apple-darwin19.0.0
        shell      /bin/bash
        uname      Darwin 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64
        path       (~/.emacs.d/bin/../bin /opt/local/bin /opt/local/sbin ~/opt/miniconda3/bin ~/opt/miniconda3/condabin ~/.gedshared/bin /usr/local/opt/curl/bin /usr/local/opt/gnu-sed/libexec/gnubin /Library/TeX/Distributions/Programs/texbin ~/.repos/tsv-utils/bin ~/Library/Python/3.7/bin /usr/local/apache-spark/spark-2.3.0-bin-hadoop2.7/bin /Library/TeX/texbin ~/.gedshared/bin ~/Projects/libsvm_utils/feature_files /usr/local/bin /usr/bin /bin /usr/sbin /sbin /Library/TeX/texbin /opt/X11/bin /Library/Apple/usr/bin ~/.bin ~/Library/Python/2.7/bin /usr/local/opt/go/libexec/bin /usr/local/opt/gnu-sed/libexec/gnubin /usr/local/sbin ~/.emacs.d/bin /usr/local/Cellar/emacs-plus/26.3/libexec/emacs/26.3/x86_64-apple-darwin19.0.0/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company ivy :ui deft doom doom-dashboard doom-quit hl-todo indent-guides modeline ophints (popup +defaults) treemacs unicode vc-gutter vi-tilde-fringe workspaces :editor file-templates fold snippets :emacs dired electric undo vc :term eshell :checkers syntax :tools docker (eval +overlay) lookup macos magit make tmux :lang emacs-lisp ess json latex markdown org python scala sh yaml :email (mu4e +gmail) :config (default +bindings +smartparens))
        packages   ((jq-mode) (org-journal) (olivetti))
        unpin      (n/a)
        elpa       (n/a)
```
</details>
</pre></details>

**Comment by anaxonda** [comment]
I have this same problem.

**Comment by gdupret** [comment]
@anaxonda it turns out some unrelated bug in my init file caused this. Starting emacs without init (emacs -q) and trying to click on a url should offer a quick and easy way to see if you face the same problem.

**Comment by anaxonda** [comment]
Yeah, not sure what is going on. I realized that links were working if I launched emacs normally (not emacsclient).
And just logged in and out, and now emacsclient is working.

**Comment by aguadopd** [comment]
I cannot navigate Doom's Help because of this. Clicking on any link gives me `run-hook-with-args-until-success: Symbol’s function definition is void: doom-set-jump-h`

**Comment by hlissner** [comment]
As of 8e83a83 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
