### ISSUE TITLE
Is there an overlap between all-the-icons-ivy, and ivy-rich?

### ISSUE THREAD

**Issue by wurosh** [hlissner/doom-emacs#3492]
It seems like `all-the-icons-ivy` implements it's own mechanism to apply transformers going around `ivy-rich`. I have to wonder if just using [`all-the-icons-ivy-rich`](https://github.com/seagle0128/all-the-icons-ivy-rich) would be a cleaner solution. That way output remains the same, but we have a single mechanism for applying aesthetic transformers and all of them can be viewed using the same variable (`ivy-rich-display-transformers-list`).

**Comment by jjzmajic** [comment]
Compare the configuration needed for the current packages to play nice:
```elisp
(use-package! all-the-icons-ivy
  :when (featurep! +icons)
  :after ivy
  :config
  ;; `all-the-icons-ivy' is incompatible with ivy-rich's switch-buffer
  ;; modifications, so we disable them and merge them ourselves
  (setq all-the-icons-ivy-buffer-commands nil)

  (all-the-icons-ivy-setup)
  (after! counsel-projectile
    (let ((all-the-icons-ivy-file-commands
           '(counsel-projectile
             counsel-projectile-find-file
             counsel-projectile-find-dir)))
      (all-the-icons-ivy-setup))))
```

With what's needed for `all-the-icons-ivy-rich` to play nice
```
(use-package! all-the-icons-ivy-rich
  :after counsel
  :config (all-the-icons-ivy-rich-mode))
```

And if I'm not mistaken this also gives us eye-candy in more functions.
