### ISSUE TITLE
Colon and asterisk show up as weird characters

### ISSUE THREAD

**Issue by heraldofsolace** [hlissner/doom-emacs#3493]
**What did you expect to happen?**
`:` and `*` would appear as they are.

**What actually happened?**
`:` and `*` show up as weird characters.

**Additional details:**
![Screenshot_20200701_113303](https://user-images.githubusercontent.com/12252677/86208886-06619f80-bb8f-11ea-977b-b81ea43e7868.png)

Here you can see the `*` in the first line and `:` in the next line show up as some weird characters. However, if I put my cursor on them, they return to normal.
![Screenshot_20200701_113615](https://user-images.githubusercontent.com/12252677/86208974-327d2080-bb8f-11ea-89ad-9e162aa087aa.png)

**Steps to reproduce:**
1. Open a file.
2. Type `:` or `*`.
3. Move the cursor away.

**System information:**
<details><pre>
<details>

```
emacs   version    26.3
        features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2
        build      May 19, 2020
        buildopts  (--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-wide-int --with-modules 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now)
        windowsys  x
        daemonp    daemon
doom    version    2.0.9
        build      grafted, HEAD -> develop, origin/develop, origin/HEAD 042cc78 2020-06-20 03:02:05 -0400
        dir        ~/.doom.d/
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/fish
        uname      Linux 5.7.2-arch1-1 #1 SMP PREEMPT Wed, 10 Jun 2020 20:36:24 +0000 x86_64
        path       (~/.emacs.d/bin ~/flutter/bin ~/.rvm/gems/ruby-2.7.0/bin ~/.rvm/gems/ruby-2.7.0@global/bin ~/.rvm/rubies/ruby-2.7.0/bin ~/.rvm/bin ~/.local/bin ~/.deno/bin ~/.config/nvm/14.3.0/bin ~/.local/bin ~/.deno/bin ~/anaconda3/envs/py38/bin ~/anaconda3/condabin /bin ~/google-cloud-sdk/bin ~/.local/bin ~/.deno/bin /usr/local/sbin /usr/local/bin /usr/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /usr/lib/emacs/26.3/x86_64-pc-linux-gnu/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company (ivy +fuzzy +prescient +icons) :ui deft doom doom-dashboard doom-quit hl-todo hydra minimap modeline ophints (popup +defaults) (pretty-code +fira) tabs treemacs vc-gutter vi-tilde-fringe window-select workspaces zen :editor (evil +everywhere) file-templates fold (format +onsave) multiple-cursors objed snippets word-wrap :emacs (dired +ranger +icons) electric ibuffer (undo +tree) vc :term eshell shell vterm :checkers syntax spell grammar :tools debugger direnv docker editorconfig ein (eval +overlay) gist (lookup +dictionary) lsp (magit +forge) make pass pdf rgb taskrunner tmux :lang cc clojure common-lisp crystal (dart +flutter) emacs-lisp (go +lsp) (haskell +dante) json (java +meghanada) javascript julia kotlin latex lua markdown nix ocaml org php purescript (python +conda +lsp) qt rest rst (ruby +rails +lsp +rvm) rust scala scheme (sh +fish) web yaml :email (mu4e +gmail) :app calendar irc (rss +org) twitter :config (default +bindings +smartparens))
        packages   ((wakatime-mode))
        unpin      (n/a)
        elpa       (n/a)
```
</details>
</pre></details>

**Comment by heraldofsolace** [comment]
That seems like ligerature issue with Fira Code. Changing the font weight to bold from medium fixed it.

**Comment by snuffop** [comment]
Really?  its all in the pretty-code module for me.. I remove that module everything is fine.  Looks to be in the regex for subst  but I haven't dug in

**Comment by hlissner** [comment]
> Really? its all in the pretty-code module for me.

The pretty-code module is what gives us Fira ligatures.

> That seems like ligerature issue with Fira Code. Changing the font weight to bold from medium fixed it.

If there is an way to fix it from within Emacs (besides just disabling the module), I'm not aware of it, so I'll consider this a local/font issue for the time being.

**Comment by hungyiloo** [comment]
I also had this issue after enabling `pretty-code +fira` and running `+pretty-code/install-patched-font`. My fix was to install the (still missing) [Fira Code Symbol](https://github.com/tonsky/FiraCode/files/412440/FiraCode-Regular-Symbol.zip) font as described [here](https://github.com/tonsky/FiraCode/issues/211#issuecomment-239058632).

Is `+pretty-code/install-patched-font` supposed to help us install that too? 

In either case, I hope this might help others who run into the same thing I did.
