### ISSUE TITLE
no-easy-keys for doom

### ISSUE THREAD

**Issue by OrionRandD** [hlissner/doom-emacs#3508]
How do I accomplish disabling arrow keys and other keys 
to stick more to evil-mode as in this wonderful Emacs way 
package?
http://danamlund.dk/emacs/no-easy-keys.html

**Comment by WhatDothLife** [comment]
Have you tried installing the package?

**Comment by OrionRandD** [comment]
I do. It works only if I turn evil-mode off in doom. Because doom uses evil as default.
What I mean is that a package or function similar to this one in doom-evil-on...

**Comment by OrionRandD** [comment]
"added the is:invalid label" - if it is invalid why they do not point h
where in the manual it deals with this issue?

**Comment by WhatDothLife** [comment]
Using this package only makes sense, if evil is deactivated. To do so comment out the line containing `evil` in your .doom.d/init.el and call `doom sync`.

**Comment by OrionRandD** [comment]
I have tested this way.
That's why I asked about something similar to be used in doom-evil-on
Thx anyway.

**Comment by WhatDothLife** [comment]
You may close this now
