### ISSUE TITLE
helm/projectile-find-file can't find fd path 

### ISSUE THREAD

**Issue by saiberz** [hlissner/doom-emacs#3511]
**What did you expect to happen?**
...

Open projectile to find file in project:

M-x projectile-find-file

**What actually happened?**
...

Throws an error
```
Find file [zsh: 1: command not found]
```

**Additional details:**
<img width="400" alt="Screen Shot 2020-07-04 at 18 10 56" src="https://user-images.githubusercontent.com/1022999/86516569-ff05f480-be21-11ea-8fee-a0c204b99cec.png">
- No backtrace errors

<details><pre>
If an error message is involved include a backtrace of it.

<img width="569" alt="image" src="https://user-images.githubusercontent.com/1022999/86516674-037edd00-be23-11ea-9e99-dcb7470d3653.png">

It can find the actual path for fd

<img width="485" alt="image" src="https://user-images.githubusercontent.com/1022999/86516707-32954e80-be23-11ea-983f-8dce41ce6a81.png">

<img width="486" alt="image" src="https://user-images.githubusercontent.com/1022999/86516784-9ae43000-be23-11ea-9797-3dd7dbb7ac7a.png">

Related to https://github.com/hlissner/doom-emacs/issues/1617

**Steps to reproduce:**
1.) Open vanilla Doom sandbox
2.) M-x projectile-find-file
3.) Select a project 
4.) Throws error 

**System information:**
<details><pre>

```
emacs   version    26.3
        features   JPEG RSVG IMAGEMAGICK GLIB NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2
        build      Jul 04, 2020
        buildopts  (--disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus@26/26.3/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus@26/26.3 --with-xml2 --with-gnutls --with-imagemagick --with-modules --with-rsvg --with-ns --disable-ns-self-contained)
        windowsys  ns
        daemonp    server-running
doom    version    2.0.9
        build      grafted, HEAD -> develop, origin/develop, origin/HEAD 46d6d0b 2020-06-29 15:12:30 -0400
        dir        ~/.doom.d/
system  type       darwin
        config     x86_64-apple-darwin19.5.0
        shell      /bin/zsh
        uname      Darwin 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64
        path       (~/.pyenv/shims ~/.yarn/bin ~/.config/yarn/global/node_modules/.bin ~/.nvm/versions/node/v12.10.0/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /Library/Apple/usr/bin /usr/yolo ~/Library/Python/2.7/bin /usr/local/Cellar/emacs-plus@26/26.3/libexec/emacs/26.3/x86_64-apple-darwin19.5.0/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline ophints (popup +defaults) vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold snippets :emacs dired electric undo vc :checkers syntax :tools docker (eval +overlay) lookup lsp macos magit :lang elixir emacs-lisp (java +meghanada) markdown org python sh web yaml :config (default +bindings +smartparens))
        packages   (n/a)
        unpin      (n/a)
        elpa       (n/a)
```
</pre></details>

**Comment by saiberz** [comment]
Looks like this is related to #3463

**Comment by hlissner** [comment]
As of c481408 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by brendonolaney** [comment]
I'm experiencing this exact issue on a fresh install. It only seems to affect `projectile-find-file`

<details>
<summary>details</summary>
<pre>
~
❯ doom info
((emacs
  (version . "26.3")
  (features . "JPEG RSVG IMAGEMAGICK GLIB NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2")
  (build . "Feb 22, 2020")
  (buildopts "--disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus/26.3/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus/26.3 --with-xml2 --without-dbus --with-gnutls --with-imagemagick --with-modules --with-rsvg --with-ns --disable-ns-self-contained")
  (windowsys . batch)
  (daemonp))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD ffbd7b63 2020-08-02 01:33:51 -0400")
  (dir . "~/.doom.d/"))
 (system
  (type . darwin)
  (config . "x86_64-apple-darwin19.2.0")
  (shell . "/bin/zsh")
  (uname . "Darwin 19.6.0 Darwin Kernel Version 19.6.0: Sun Jul  5 00:43:10 PDT 2020; root:xnu-6153.141.1~9/RELEASE_X86_64 x86_64")
  (path "/usr/local/bin" "/usr/bin" "/bin" "/usr/sbin" "/sbin" "/Library/TeX/texbin" "~/src/dotfiles/bin" "~/.emacs.d/bin" "/usr/local/sbin" "/usr/local/opt/fzf/bin" "/usr/local/Cellar/emacs-plus/26.3/libexec/emacs/26.3/x86_64-apple-darwin19.2.0"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold multiple-cursors rotate-text snippets :emacs dired electric ibuffer vc :term term :checkers syntax spell grammar :tools editorconfig (eval +overlay) (lookup +docsets) macos magit :lang data emacs-lisp markdown (org +dragndrop +gnuplot +present) sh web :config (default +bindings +smartparens))
  (packages "n/a")
  (unpin "n/a")
  (elpa "n/a")))


~
❯ which fd
/usr/local/bin/fd

~
❯ fd --version
fd 8.1.1
</pre>
</details>

**Comment by hlissner** [comment]
@brendonolaney 

1. Run `doom env`. If that doesn't fix it:
2. What does `M-: (executable-find "fd")` return? 
3. What is the value of `doom-projectile-fd-binary` (see `SPC h v doom-projectile-fd-binary`)?

**Comment by brendonolaney** [comment]
2. `"/usr/local/bin/fd"`
3. `"fd"`

**Comment by brendonolaney** [comment]
@hlissner would it help if I opened a new issue? I've been over the code several times and there isn't anything that is popping out at me. Elisp isn't exactly my strength.

**Comment by brendonolaney** [comment]
@hlissner I ended up deleting, re-cloning the repo so that I could bisect the problem, and it started working immediately afterwards so I guess it was a local issue.
