### ISSUE TITLE
Backspace inside nested pairs deletes one-too-many of pair to right of point

### ISSUE THREAD

**Issue by fapapa** [hlissner/doom-emacs#3515]
**What did you expect to happen?**

When typing the opening character of a pair, doom emacs automatically inserts the matching closing character. However, when back-spacing, it deletes one-too-many of the closing pairs. Here's an example:

```
((|))
```

In the above, the "|" character represent `point`. When pressing backspace, I would expect the result to be the following state:

```
(|)
```

**What actually happened?**
Continuing with the above example, the resulting state is:

```
(|
```

As you can see, one too many pairs get deleted to the *right* of point.

**Additional details:**
I am on macOS Catalina, using the homebrew d12frosted version of emacs 28 (which I know is not supported) but it also happens with emacs 27. I **cannot** reproduce the problem in vanilla emacs or vanilla doom, but can reproduce it in doom - private config and doom + private config.

**Steps to reproduce:**
1. Open a scratch buffer
2. Enable smartparen-mode
3. Go into insert mode ('i')
4. Type two open parens
5. With point after the two open parens (but before the two automatically-inserted close parens), press backspace once
6. Note that one open paren remains, and no close parens remain
**System information:**
<details><pre>
emacs   version    28.0.50
        features   JPEG TIFF PNG RSVG IMAGEMAGICK GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS XWIDGETS PDUMPER LCMS2 GMP
        build      Jul 04, 2020
        buildopts  (--disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus@28/28.0.50/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus@28/28.0.50 --with-xml2 --with-gnutls --without-dbus --with-imagemagick --with-modules --with-rsvg --without-pop --with-xwidgets --with-ns --disable-ns-self-contained)
        windowsys  ns
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop, origin/develop, origin/HEAD 46d6d0b58 2020-06-29 15:12:30 -0400
        dir        ~/.doom.d/
system  type       darwin
        config     x86_64-apple-darwin19.5.0
        shell      /bin/zsh
        uname      Darwin 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64
        path       (/usr/local/sbin ~/.nodenv/shims ~/.rbenv/shims ~/.rbenv/shims /usr/local/bin /usr/bin /bin /usr/sbin /sbin /Library/TeX/texbin /opt/X11/bin ~/.nodenv/shims ~/.rbenv/shims /opt/local/bin /opt/local/sbin /usr/local/opt/qt@5.5/bin ~/bin ~/.emacs.d/bin /usr/local/opt/postgresql@10/bin /usr/local/opt/node@10/bin /usr/local/opt/sqlite/bin ~/go/bin /usr/local/opt/fzf/bin /usr/local/Cellar/emacs-plus@28/28.0.50/libexec/emacs/28.0.50/x86_64-apple-darwin19.5.0/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline ophints (popup +defaults) vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold snippets :emacs dired electric undo vc :checkers syntax :tools (eval +overlay) lookup magit :lang emacs-lisp markdown org sh :config (default +bindings +smartparens))
        packages   (n/a)
        unpin      (n/a)
        elpa       (n/a)
</pre></details>

**Comment by sorawee** [comment]
I indeed experienced this problem, but after upgrading to the latest version, this problem goes away. @fapapa, could you confirm that it is fixed now?

**Comment by fapapa** [comment]
It indeed did get resolved with an update from last week. Thank you.
