### ISSUE TITLE
Multiple doom! calls aren't really possible

### ISSUE THREAD

**Issue by jazzpi** [hlissner/doom-emacs#352]
### Observed behavior

After moving the `doom!` call in `init.el` to a private module and replacing it with `(doom! :private jazzpi)`, Emacs complains with

```
Debugger entered--Lisp error: (error "Recursive load" "/home/jasper/.emacs.d/modules/private/jazzpi/config.el" "/home/jasper/.emacs.d/modules/private/jazzpi/config.el" "/home/jasper/.emacs.d/modules/private/jazzpi/config.el" "/home/jasper/.emacs.d/modules/private/jazzpi/config.el" "/home/jasper/.emacs.d/modules/private/jazzpi/config.el" "/home/jasper/.emacs.d/init.el")
  load("/home/jasper/.emacs.d/modules/private/jazzpi/config" t t)
  ...
```

### Expected behavior

Emacs shouldn't recursively load my private module

### Steps to reproduce

1. Follow [the wiki](https://github.com/hlissner/doom-emacs/wiki/Customization#keep-my-customizations-in-version-control), except putting the `doom!` call in `init.el`, not `config.el`
2. (Optionally) put `(setq debug-on-error 't)` in `init.el` so the debugger opens
3. Start Emacs

### System information

<details>
<summary>Click to expand</summary>

```
[1mDOOM Doctor[0m
Running Emacs v[1m25.3.1[0m, commit fd56896e257888bc343fa692e3a377cdc4892881

Compiled with:
  XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS
  NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB
  TOOLKIT_SCROLL_BARS GTK3 X11 MODULES
uname -a:
  Linux jasper-latitude 4.14.12-1-ARCH #1 SMP PREEMPT Fri Jan 5 18:19:34
  UTC 2018 x86_64 GNU/Linux

[1m[32mAttempt to load DOOM: success! Loaded v2.0.7[0m[0m
Revision fd56896e257888bc343fa692e3a377cdc4892881

----

[34mtest-emacs[0m
[34mtest-windows[0m
[34mtest-fonts[0m
[1m[32mFound font material-design-icons.ttf[0m[0m
[1m[32mFound font weathericons.ttf[0m[0m
[1m[32mFound font octicons.ttf[0m[0m
[1m[32mFound font fontawesome.ttf[0m[0m
[1m[32mFound font file-icons.ttf[0m[0m
[1m[32mFound font all-the-icons.ttf[0m[0m
[34mtest-gnutls[0m
[34mtest-tls[0m
[1m[32mVerified elpa.gnu.org[0m[0m
[1m[32mVerified melpa.org[0m[0m
[1m[32mRejected https://self-signed.badssl.com (a good thing!)[0m[0m
  (error "Certificate validation failed self-signed.badssl.com,
  verification code 142")

[1m[32mRejected https://wrong.host.badssl.com/ (a good thing!)[0m[0m
  (error "The x509 certificate does not match
  \"wrong.host.badssl.com\"")

[34mtest-tar[0m

====
Have some debug information:

  + enabled modules:
    +debugger              +jasper                +eval
    +evil                  +file-templates        +jump
    +services              +snippets              +spellcheck
    +syntax-checker        +version-control       +workspaces
    +company               +ivy                   +doom
    +doom-dashboard        +doom-modeline         +doom-quit
    +hl-todo               +nav-flash             +evil-goggles
    +unicode               +vi-tilde-fringe       +window-select
    +dired                 +electric-indent       +eshell
    +gist                  +imenu                 +impatient-mode
    +make                  +neotree               +rotate-text
    +term                  +tmux                  +upload
    +assembly              +cc                    +data
    +elm                   +emacs-lisp            +java
    +javascript            +latex                 +lua
    +markdown              +php                   +plantuml
    +python                +rest                  +rust
    +sh                    +web                   +org
    +org-babel             +org-attach            +org-capture
    +org-export            +org-present           +write
    +hlissner                                     

  + enabled packages:
    evil-magit-20171018.722            

  + byte-compiled files:
    n/a                                    

  + exec-path:
    /home/jasper/.rvm/gems/ruby-2.3.1/bin
    /home/jasper/.rvm/gems/ruby-2.3.1@global/bin
    /home/jasper/.rvm/rubies/ruby-2.3.1/bin
    /home/jasper/bin
    /home/jasper/.linuxbrew/bin
    /home/jasper/bin
    /home/jasper/.linuxbrew/bin
    /home/jasper/bin
    /home/jasper/.linuxbrew/bin
    /usr/local/bin
    /bin
    /usr/bin
    /usr/local/sbin
    /usr/sbin
    /sbin
    /usr/lib/jvm/default/bin
    /usr/bin/site_perl
    /usr/bin/vendor_perl
    /usr/bin/core_perl
    /home/jasper/.gem/ruby/2.3.0/bin
    /home/jasper/.rvm/bin
    /home/jasper/.gem/ruby/2.5.0/bin
    /home/jasper/.rvm/bin
    /usr/lib/jvm/default/bin
    /usr/bin/site_perl
    /usr/bin/vendor_perl
    /usr/bin/core_perl
    /home/jasper/.gem/ruby/2.5.0/bin
    /home/jasper/.rvm/bin
    /usr/lib/emacs/25.3/x86_64-pc-linux-gnu

  + PATH:
    /home/jasper/.rvm/gems/ruby-2.3.1/bin
    /home/jasper/.rvm/gems/ruby-2.3.1@global/bin
    /home/jasper/.rvm/rubies/ruby-2.3.1/bin
    /home/jasper/bin
    /home/jasper/.linuxbrew/bin
    /home/jasper/bin
    /home/jasper/.linuxbrew/bin
    /home/jasper/bin
    /home/jasper/.linuxbrew/bin
    /usr/local/bin
    /bin
    /usr/bin
    /usr/local/sbin
    /usr/sbin
    /sbin
    /usr/lib/jvm/default/bin
    /usr/bin/site_perl
    /usr/bin/vendor_perl
    /usr/bin/core_perl
    /home/jasper/.gem/ruby/2.3.0/bin
    /home/jasper/.rvm/bin
    /home/jasper/.gem/ruby/2.5.0/bin
    /home/jasper/.rvm/bin
    /usr/lib/jvm/default/bin
    /usr/bin/site_perl
    /usr/bin/vendor_perl
    /usr/bin/core_perl
    /home/jasper/.gem/ruby/2.5.0/bin
    /home/jasper/.rvm/bin

[1m[32mEverything seems fine, happy Emacs’ing![0m[0m

```
</details>

### Workaround

I think this is caused because `doom!` always [loops over all modules](https://github.com/hlissner/doom-emacs/blob/master/core/core-packages.el#L311) in `doom-modules`, but never clears it.

I was able to fix it by prepending the second `doom!` call with `(remhash '(:private . jazzpi) doom-modules)`, but that feels like quite the ugly hack.

**Comment by hlissner** [comment]
You're right! I've pushed a fix, so recursive `doom!` calls should work now. Give it a try and let me know!

**Comment by hlissner** [comment]
Just noticed a couple regressions that this causes. Back to the drawing board!

**Comment by hlissner** [comment]
Alright, I've worked out a new method of pulling this off, instead of nested `doom!` calls, you'd do:

```emacs-lisp
;; ~/.emacs.d/init.el
(require 'core (concat user-emacs-directory "core/core"))
(require! :private hlissner)

;; modules/private/hlissner/init.el
(doom! ...)
```

This has been working great for me. Give it a try and let me know.

**Comment by Lubricy** [comment]
just tried out `(require! :private my-module)` approach in develop, and get following errors:

```
Error (doom-init-hook): error in ’+workspaces|init’ -> Required feature ‘persp-mode’ was not provided
Error (doom-init-hook): error in ’doom|init-ui’ -> Recursive load: "/Users/lubricy/.emacs.d/core/autoload/buffers.el", "/Users/lubricy/.emacs.d/core/autoload/buffers.el", "/Users/lubricy/.emacs.d/core/autoload/buffers.el", "/Users/lubricy/.emacs.d/core/autoload/buffers.el", "/Users/lubricy/.emacs.d/core/autoload/buffers.el"
Error (doom-post-init-hook): error in ’evil-goggles-mode’ -> Recursive load: "/Users/lubricy/.emacs.d/core/autoload/buffers.el", "/Users/lubricy/.emacs.d/core/autoload/buffers.el", "/Users/lubricy/.emacs.d/core/autoload/buffers.el", "/Users/lubricy/.emacs.d/core/autoload/buffers.el", "/Users/lubricy/.emacs.d/core/autoload/buffers.el", "/Users/lubricy/.emacs.d/.local/packages/elpa/evil-goggles-20180116.653/evil-goggles.elc"
Error (doom-post-init-hook): error in ’evil-snipe-mode’ -> Recursive load: "/Users/lubricy/.emacs.d/core/autoload/buffers.el", "/Users/lubricy/.emacs.d/core/autoload/buffers.el", "/Users/lubricy/.emacs.d/core/autoload/buffers.el", "/Users/lubricy/.emacs.d/core/autoload/buffers.el", "/Users/lubricy/.emacs.d/core/autoload/buffers.el", "/Users/lubricy/.emacs.d/.local/packages/elpa/evil-snipe-20170903.603/evil-snipe.elc"
Error (doom-post-init-hook): error in ’evil-escape-mode’ -> Recursive load: "/Users/lubricy/.emacs.d/core/autoload/buffers.el", "/Users/lubricy/.emacs.d/core/autoload/buffers.el", "/Users/lubricy/.emacs.d/core/autoload/buffers.el", "/Users/lubricy/.emacs.d/core/autoload/buffers.el", "/Users/lubricy/.emacs.d/core/autoload/buffers.el", "/Users/lubricy/.emacs.d/.local/packages/elpa/evil-escape-20170913.618/evil-escape.elc"
Error (doom-post-init-hook): error in ’evil-vimish-fold-mode’ -> Recursive load: "/Users/lubricy/.emacs.d/core/autoload/buffers.el", "/Users/lubricy/.emacs.d/core/autoload/buffers.el", "/Users/lubricy/.emacs.d/core/autoload/buffers.el", "/Users/lubricy/.emacs.d/core/autoload/buffers.el", "/Users/lubricy/.emacs.d/core/autoload/buffers.el", "/Users/lubricy/.emacs.d/.local/packages/elpa/evil-vimish-fold-20171030.451/evil-vimish-fold.el"
Error (use-package): auth-password-store/:catch: Required feature ‘f’ was not provided
```
<details>
<summary>DEBUG=1 make doctor reports:</summary>
<pre><code>
[1mDOOM Doctor[0m
Running Emacs v[1m25.3.1[0m, commit 2c1867caf16dcabc9f73a2feab2fb9fd43ebcb88

shell: /bin/zsh
Compiled with:
  NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS
uname -a:
  Darwin liweijiandeMacBook-Air.local 17.2.0 Darwin Kernel Version
  17.2.0: Fri Sep 29 18:27:05 PDT 2017;
  root:xnu-4570.20.62~3/RELEASE_X86_64 x86_64

[1m[32mAttempt to load DOOM: success! Loaded v2.0.9[0m[0m
Revision 2c1867caf16dcabc9f73a2feab2fb9fd43ebcb88

----

[34mtest-emacs[0m
[34mtest-windows[0m
[34mtest-fonts[0m
[1m[32mFound font material-design-icons.ttf[0m[0m
[1m[32mFound font weathericons.ttf[0m[0m
[1m[32mFound font octicons.ttf[0m[0m
[1m[32mFound font fontawesome.ttf[0m[0m
[1m[32mFound font file-icons.ttf[0m[0m
[1m[32mFound font all-the-icons.ttf[0m[0m
[34mtest-gnutls[0m
[34mtest-tls[0m
[1m[32mValidated https://elpa.gnu.org[0m[0m
[1m[32mValidated https://melpa.org[0m[0m
[1m[32mSuccessfully rejected https://self-signed.badssl.com[0m[0m
[1m[32mSuccessfully rejected https://wrong.host.badssl.com/[0m[0m
[34mtest-tar[0m

====
Have some debug information:

  + enabled modules:
    +eval                  +evil                  +file-templates
    +jump                  +services              +snippets
    +spellcheck            +syntax-checker        +version-control
    +workspaces            +company               +ivy
    +doom                  +doom-dashboard        +doom-modeline
    +doom-quit             +hl-todo               +nav-flash
    +evil-goggles          +vi-tilde-fringe       +window-select
    +dired                 +electric-indent       +eshell
    +gist                  +imenu                 +impatient-mode
    +make                  +neotree               +password-store
    +rotate-text           +term                  +tmux
    +upload                +assembly              +cc
    +crystal               +clojure               +csharp
    +data                  +elixir                +elm
    +emacs-lisp            +go                    +haskell
    +hy                    +java                  +javascript
    +julia                 +latex                 +ledger
    +lua                   +markdown              +ocaml
    +org                   +perl                  +php
    +plantuml              +purescript            +python
    +rest                  +ruby                  +rust
    +scala                 +sh                    +swift
    +typescript            +web                   +default

  + enabled packages:
    ac-alchemist-20150907.2356         ace-link-20180101.1328
    ace-window-20180119.1226           adaptive-wrap-0.5.1
    alchemist-20171029.2307            all-the-icons-20171011.324
    anaconda-mode-20171223.1118        android-mode-20170323.115
    auctex-12.1.0                      auth-password-store-20171109.1045
    auto-compile-20180111.436          auto-yasnippet-20160925.225
    avy-20171230.220                   centered-window-mode-20170528.25
    cider-20180120.324                 clj-refactor-20171117.317
    cmake-mode-20180104.1137           coffee-mode-20170324.240
    command-log-mode-20160412.2147     company-20180101.1101
    company-anaconda-20171222.342      company-auctex-20161025.24
    company-dict-20160528.53           company-ghc-20170918.133
    company-glsl-20150111.1848         company-go-20170825.943
    company-inf-ruby-20140805.1354     company-irony-20170905.1346
    company-irony-c-headers-20151018.209 company-lua-20171108.1506
    company-php-20171226.1924          company-quickhelp-20170429.1052
    company-racer-20171204.1910        company-restclient-20151202.401
    company-shell-20170517.2241        company-sourcekit-20170126.353
    company-statistics-20170210.1133   company-tern-20161004.1147
    company-web-20171111.1049          counsel-20180114.1336
    counsel-css-20170305.947           counsel-projectile-20180105.632
    crystal-mode-20180104.1920         csharp-mode-20171211.2238
    cuda-mode-20151213.1921            demangle-mode-20170923.1501
    dired-k-20170313.803               disaster-20171016.1452
    dockerfile-mode-20171124.1647      doom-themes-20180108.1934
    editorconfig-20171208.2036         eldoc-eval-20150512.506
    elixir-mode-20170918.2231          elm-mode-20180114.9
    emacs-snippets-20180102.518        emmet-mode-20161113.2158
    ensime-20171217.1730               eslintd-fix-20171128.453
    evil-20180103.2356                 evil-anzu-20170123.2318
    evil-args-20140329.1429            evil-commentary-20170413.751
    evil-easymotion-20180113.2254      evil-embrace-20160519.1129
    evil-escape-20170913.618           evil-exchange-20170510.1959
    evil-goggles-20180116.653          evil-indent-plus-20151109.1106
    evil-ledger-20170905.519           evil-matchit-20171127.245
    evil-mc-20170716.1806              evil-multiedit-20171217.2317
    evil-numbers-20140606.551          evil-snipe-20170903.603
    evil-surround-20180102.601         evil-textobj-anyblock-20170905.1207
    evil-vimish-fold-20171030.451      evil-visualstar-20160222.1648
    exec-path-from-shell-20170508.4    expand-region-20171217.2125
    flycheck-20180116.147              flycheck-cask-20160928.226
    flycheck-crystal-20171124.740      flycheck-elm-20160717.257
    flycheck-irony-20160317.1536       flycheck-ledger-20140605.1146
    flycheck-perl6-20171231.445        flycheck-plantuml-20171017.1811
    flycheck-popup-tip-20170812.1651   flycheck-pos-tip-20170504.1504
    flycheck-rust-20170404.842         flyspell-correct-20171205.940
    flyspell-correct-ivy-20161031.1134 fringe-helper-20140620.1409
    gist-20171127.2006                 git-gutter-fringe-20170112.2133
    git-link-20170603.1026             git-timemachine-20170325.220
    gitconfig-mode-20170627.854        gitignore-mode-20160319.302
    glsl-mode-20170927.736             go-eldoc-20170305.627
    go-guru-20170718.1046              go-mode-20170726.555
    gorepl-mode-20170905.245           groovy-mode-20180109.718
    haml-mode-20170923.2153            haskell-mode-20171022.26
    haxor-mode-20160618.429            help-fns+-20170223.733
    highlight-indentation-20171218.137 highlight-numbers-20170905.342
    highlight-quoted-20140916.1122     hindent-20171215.848
    hl-todo-20170621.1257              htmlize-20171017.141
    hy-mode-20180115.1230              hydra-20171120.1042
    imenu-anywhere-20170805.1155       imenu-list-20171120.1255
    impatient-mode-20170505.1921       inf-ruby-20171211.225
    intero-20180117.921                irony-20180104.1109
    irony-eldoc-20170502.1208          ivy-20180115.1555
    ivy-bibtex-20180110.1209           ivy-hydra-20171130.1143
    ivy-rich-20180109.1933             ivy-rtags-20170522.2154
    js2-mode-20171224.1833             js2-refactor-20180118.251
    json-mode-20170719.2205            julia-mode-20171116.642
    ledger-mode-20180112.1950          less-css-mode-20160930.2153
    lua-mode-20180104.626              macrostep-20161120.1306
    magit-20180120.1529                makefile-executor-20171017.438
    markdown-mode-20180115.1905        markdown-toc-20170711.1249
    meghanada-20171230.802             merlin-20170917.430
    mips-mode-20170310.2149            modern-cpp-font-lock-20180110.1231
    moonscript-20170831.1526           multi-term-20160619.233
    nasm-mode-20161216.736             nav-flash-20140508.1341
    neotree-20170522.758               nlinum-1.8.1
    nlinum-hl-20170613.1748            nlinum-relative-20160526.8
    nodejs-repl-20170722.443           nose-20140520.948
    ob-go-20170731.1057                ob-mongo-20170720.1219
    ob-redis-20160411.2013             ob-restclient-20160323.2305
    ob-rust-20170730.759               ob-sql-mode-20170213.1056
    ob-translate-20170720.1219         omnisharp-20171226.1147
    opencl-mode-20170816.549           org-bullets-20170211.510
    org-download-20171116.1045         org-plus-contrib-20180115
    org-tree-slide-20171129.2238       osx-clipboard-20141012.17
    overseer-20170207.2241             ox-pandoc-20171107.341
    ox-reveal-20161027.226             pass-20180109.201
    password-store-20170829.1633       pcre2el-20161120.1303
    perl6-mode-20161228.430            persp-mode-20180104.843
    php-boris-20130527.121             php-extras-20160518.2316
    php-mode-20180105.541              php-refactor-mode-20171123.2235
    phpunit-20171127.301               pip-requirements-20171109.1439
    plantuml-mode-20170819.1033        prodigy-20171121.512
    projectile-20180118.745            psc-ide-20180101.1421
    pug-mode-20171208.2029             purescript-mode-20180120.709
    quickrun-20170222.1715             racer-20171211.1548
    rainbow-delimiters-20170929.432    rainbow-mode-0.13
    rake-20170921.801                  restclient-20171203.1248
    rjsx-mode-20171029.1156            rotate-text-20111204.939
    rspec-mode-20171025.1606           rtags-20180107.2358
    ruby-refactor-20160214.850         rust-mode-20180109.544
    sass-mode-20161006.2326            sbt-mode-20171111.1558
    scala-mode-20170802.432            shackle-20171209.1401
    shader-mode-20180105.1500          shrink-path-20170812.1947
    skewer-mode-20170730.1241          slime-20180111.429
    smart-forward-20140430.13          smartparens-20180118.735
    smex-20151212.1409                 solaire-mode-20171209.1350
    ssh-deploy-20171211.311            stylus-mode-20150313.812
    swift-mode-20171228.2315           swiper-20180119.911
    tern-20170925.1333                 tide-20171214.543
    toc-org-20171009.156               toml-mode-20161107.1000
    tuareg-20171204.1417               typescript-mode-20180118.2305
    undo-tree-20170706.246             vi-tilde-fringe-20141027.1942
    vimrc-mode-20170814.1837           visual-fill-column-20170502.1300
    web-beautify-20161115.1447         web-mode-20180116.1247
    wgrep-20141016.1656                which-key-20180108.1930
    yaml-mode-20170727.1531            yard-mode-20170817.537
    yasnippet-20180111.1533            

  + byte-compiled files:
    n/a                                    

  + exec-path:
    /usr/local/bin/
    /usr/bin/
    /bin/
    /usr/sbin/
    /sbin/
    /Users/lubricy/.zplug/bin/
    /Users/lubricy/.homebrew/bin/
    /Users/lubricy/.homebrew/Cellar/emacs/25.3/libexec/emacs/25.3/x86_64-apple-darwin17.2.0/

  + PATH:
    /usr/local/bin
    /usr/bin
    /bin
    /usr/sbin
    /sbin
    /Users/lubricy/.zplug/bin
    /Users/lubricy/.homebrew/bin

[1m[32mEverything seems fine, happy Emacs’ing![0m[0m
</code>
</pre>
</details>

**Comment by Lubricy** [comment]
okay rename/remove `.local` and `make` from fresh solves the problem. however i'm still wondering if it is the right/necessary thing to do after switching branches? How can I keep my installed packages without download them again?

**Comment by Lubricy** [comment]
another thing to note, when using `require!` instead of `doom!`, `package!` & `use-package` declarations in that private module are not going to be detected and install properly by `make`.

**Comment by hlissner** [comment]
I've put together what I hope will be a conclusive fix for this issue. Nested `doom!` calls should now be possible.

```emacs-lisp
;; ~/.emacs.d/init.el
(require 'core (concat user-emacs-directory "core/core"))
(require! :private hlissner) ; replace with your module

;; modules/private/hlissner/init.el
(doom! ...)
```

It should also recognize `:private hlissner`'s packages.el.

> however i'm still wondering if it is the right/necessary thing to do after switching branches?

It is wise to always run `make` after changing Doom's source code. However, deleting `.local` shouldn't be necessary. Chances are your packages only need to be recompiled, which can be done with `make compile-elpa`. Let me know if that doesn't solve your problem.

**Comment by jazzpi** [comment]
Sorry for the (very) late reply, but I finally got around to testing this again:

<details>
<summary>Click to expand</summary>

```
$ git clone https://github.com/hlissner/doom-emacs .emacs.d
---SNIP---
$ cd .emacs.d
$ git checkout develop
Branch 'develop' set up to track remote branch 'develop' from 'origin'.
Switched to a new branch 'develop'
$ mkdir -p modules/private/jazzpi
$ cp init.example.el modules/private/jazzpi/config.el
$ echo "(require 'core (concat user-emacs-directory \"core/core\"))
(doom! :private jazzpi)" > init.el
$ make install
Installing core packages
Importing package-keyring.gpg...
Importing package-keyring.gpg...done
Contacting host: elpa.gnu.org:443
Contacting host: elpa.gnu.org:443
Contacting host: melpa.org:443
Package refresh done
✓ Installed persistent-soft
✓ Installed use-package
✓ Installed quelpa
✓ Installed async
Installing core packages...done
Looking for packages to install...
25 packages will be installed:

+ ace-link (ELPA)
+ ace-window (ELPA)
+ all-the-icons (ELPA)
+ avy (ELPA)
+ command-log-mode (ELPA)
+ editorconfig (ELPA)
+ expand-region (ELPA)
+ fringe-helper (ELPA)
+ helpful (ELPA)
+ hide-mode-line (ELPA)
+ highlight-indentation (ELPA)
+ highlight-numbers (ELPA)
+ hydra (ELPA)
+ nlinum (ELPA)
+ nlinum-hl (ELPA)
+ nlinum-relative (ELPA)
+ pcre2el (ELPA)
+ projectile (ELPA)
+ rainbow-delimiters (ELPA)
+ shackle (ELPA)
+ smart-forward (ELPA)
+ smartparens (ELPA)
+ undo-tree (ELPA)
+ visual-fill-column (ELPA)
+ which-key (ELPA)

Proceed? (y or n) y
Refreshing package archives
Importing package-keyring.gpg...
Importing package-keyring.gpg...done
Contacting host: elpa.gnu.org:443
Contacting host: elpa.gnu.org:443
Contacting host: melpa.org:443
Package refresh done
Installing all-the-icons
✓ DONE
Installing fringe-helper
✓ DONE
Installing hide-mode-line
✓ DONE
Installing highlight-indentation
✓ DONE
Installing highlight-numbers
✓ DONE
Installing nlinum
  FILE ERROR: https://elpa.gnu.org/packages/nlinum-1.8.1.el: Bad Request
  Trying again...
✓ DONE
Installing nlinum-hl
✓ DONE
Installing nlinum-relative
✓ DONE
Installing rainbow-delimiters
✓ DONE
Installing visual-fill-column
✓ DONE
Installing shackle
✓ DONE
Installing ace-link
✓ DONE
Installing ace-window
✓ DONE
Installing avy
⚠ ALREADY INSTALLED
Installing command-log-mode
✓ DONE
Installing editorconfig
✓ DONE
Installing expand-region
✓ DONE
Installing helpful
✓ DONE
Installing pcre2el
✓ DONE
Installing smart-forward
✓ DONE
Installing smartparens
✓ DONE
Installing undo-tree
✓ DONE
Installing projectile
✓ DONE
Installing which-key
✓ DONE
Installing hydra
✓ DONE
Finished!
$ make doctor
Doom Doctor
Emacs v25.3.1
Doom v2.0.9 (bb8304c1)
shell: /usr/bin/zsh
Compiled with:
  XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL
  GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11
  MODULES
uname -a:
  Linux archv2 4.15.11-1-ARCH #1 SMP PREEMPT Mon Mar 19 18:21:03 UTC 2018 x86_64
  GNU/Linux

----

test-emacs
test-windows
test-fonts
test-gnutls
test-tls
Validated https://elpa.gnu.org
Validated https://melpa.org
Successfully rejected https://self-signed.badssl.com
Successfully rejected https://wrong.host.badssl.com/
test-tar

----
Saving file /home/jasper/.emacs.d/.local/packages.el...
Attempt to load DOOM: success! Loaded v2.0.9
test-modules
  > (:feature eval) quickrun is not installed
  > (:feature evil) evil-visualstar is not installed
---SNIP---
  > (:lang web) rainbow-mode is not installed
  > (:config default) emacs-snippets is not installed

----
There were 226 issues!
```
</details>

It seems as though `make install` doesn't recognize any of the modules I'm loading from my private `config.el`. Taking a quick look at another install (where I installed the packages before moving my configuration to my private init.el), `(doom-get-packages)` only returns 32 packages which I think are the packages I have in `core/packages.el` and `private/modules/jazzpi/packages.el`.

**Comment by jazzpi** [comment]
This issue can be fixed by moving the `doom!` call to an `init.el` file in the private module. Now everything seems to be working, thanks!
