### ISSUE TITLE
Doom not loaded when starting

### ISSUE THREAD

**Issue by JaewonHur** [hlissner/doom-emacs#3525]
When I start doom emacs, doom is not correctly loaded? (maybe)
I followed the install manual, and used all example files in core/template.

But when I open c++ file with doom emacs, smart-parens and lsp does not start.
(even ` (default +bindings +smartparens) ` and `(cc +lsp)` are included in init.el file)

But smartparens are enabled when I reload doom. 
(Not lsp)

Does anyone knows how to fix it?

**Comment by bfrog** [comment]
Did you setup the packages for lsp and friends? did you run doom update (and maybe doom sync?)?

**Comment by JaewonHur** [comment]
What do you mean setup?

**Comment by JaewonHur** [comment]
Yes, I followed all the steps.

I resolved by using `(add-hook 'c++-mode-hook 'lsp)`.

Thanks!
