### ISSUE TITLE
Annoying error with eldoc

### ISSUE THREAD

**Issue by m0nhawk** [hlissner/doom-emacs#3534]
**What did you expect to happen?**
1. No errors.

**What actually happened?**
1. Error appear in `*Messages*`:

```
eldoc error: (wrong-number-of-arguments #[nil \303 \206\222...))
[lang eldoc-documentation-function doc-fun org-eldoc-get-breadcrumb org-eldoc-get-src-header org-eldoc-get-src-lang emacs-lisp elisp fboundp elisp-eldoc-documentation-function nil eldoc-print-current-symbol-info c C require c-eldoc t c-eldoc-print-current-symbol-info css css-eldoc css-eldoc-function php php-eldoc php-eldoc-function go golang go-eldoc go-eldoc--documentation-function org-eldoc-get-mode-local-documentation-function functionp] 5
(/Users/andrew/.doom.emacs.d/.local/straight/build/org-mode/org-eldoc.elc . 3162)] 1)
```

**Additional details:**
- This is happening with clean install of Doom Emacs

**Steps to reproduce:**
1. Open `org` file.
2. Move between lines.

**System information:**
<details>

```
emacs   version    28.0.50
        features   JPEG TIFF PNG RSVG IMAGEMAGICK GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS PDUMPER LCMS2 GMP
        build      Jul 09, 2020
        buildopts  (--disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus@28/28.0.50/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus@28/28.0.50 --with-xml2 --with-gnutls --without-dbus --with-imagemagick --with-modules --with-rsvg --with-ns --disable-ns-self-contained)
        windowsys  ns
        daemonp    server-running
doom    version    2.0.9
        build      grafted, HEAD -> develop, origin/develop, origin/HEAD 46d6d0b 2020-06-29 15:12:30 -0400
        dir        ~/.doom.d/
system  type       darwin
        config     x86_64-apple-darwin19.5.0
        shell      fish
        uname      Darwin 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64
        path       (~/.local/bin ~/.pyenv/libexec/pyenv ~/.pyenv/libexec ~/.pyenv/shims ~/.pyenv/bin /usr/local/opt/krb5/sbin /usr/local/opt/krb5/bin /usr/local/opt/qt/bin /usr/local/opt/ruby/bin /usr/local/opt/grep/libexec/gnubin /usr/local/opt/gnu-tar/libexec/gnubin /usr/local/opt/gnu-sed/libexec/gnubin /usr/local/opt/findutils/libexec/gnubin /usr/local/opt/coreutils/libexec/gnubin /usr/local/opt/make/libexec/gnubin /usr/local/opt/ncurses/bin /usr/local/opt/libxml2/bin /usr/local/opt/openssl@1.1/bin /usr/local/Cellar/pyenv-virtualenv/1.1.5/shims ~/.local/bin ~/.bin /usr/local/bin /usr/bin /bin /usr/local/sbin /usr/sbin /sbin /usr/local/Cellar/emacs-plus@28/28.0.50/libexec/emacs/28.0.50/x86_64-apple-darwin19.5.0/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline ophints (popup +defaults) vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold snippets :emacs dired electric undo vc :checkers syntax :tools (eval +overlay) lookup magit :lang emacs-lisp markdown org sh :config (default +bindings +smartparens))
        packages   (n/a)
        unpin      (n/a)
        elpa       (n/a)
```
</details>

**Comment by jonathanabennett** [comment]
I am having the same error as well. It started about 2 days ago, I am not yet able to figure out the cause. Here's the error message I'm getting. The cause for me is any movement, not just moving between lines.

`eldoc error: (wrong-number-of-arguments #[nil \303 \206\222\304 \206\222\305 \211\306\230\204\307\230\203,\310\311!\203$\311 \202\221\312\313 )\202\221\314\230\2048\315\230\203E\316\317\312\320#\205\221\321 \202\221\322\230\203X\316\323\312\320#\205\221\324 \202\221\325\230\203k\316\326\312\320#\205\221\327 \202\221\330\230\204w\331\230\203\204\316\332\312\320#\205\221\333 \202\221\334!\335
!\205\220
 ))\207 [lang eldoc-documentation-function doc-fun org-eldoc-get-breadcrumb org-eldoc-get-src-header org-eldoc-get-src-lang emacs-lisp elisp fboundp elisp-eldoc-documentation-function nil eldoc-print-current-symbol-info c C require c-eldoc t c-eldoc-print-current-symbol-info css css-eldoc css-eldoc-function php php-eldoc php-eldoc-function go golang go-eldoc go-eldoc--documentation-function org-eldoc-get-mode-local-documentation-function functionp] 5 (/Users/jonathanbennett/.emacs.d/.local/straight/build/org-mode/org-eldoc.elc . 3162)] 1)
`

**Comment by janezrom** [comment]
Look at https://www.mail-archive.com/emacs-orgmode@gnu.org/msg129341.html

Backup solution is to install emacs@27 instead of emacs@28.

**Comment by m0nhawk** [comment]
Seems like that's not a doom emacs issue.

I think it makes sense to close this one.

**Comment by George9000** [comment]
For those who don't want to downgrade to emacs@27 and use the fix to org-mode code mentioned at the mail-archive link posted above:

1) in ~/.doom.d/packages
(unpin! org-mode)
;; alternatively,
;; ((package! org-mode :pin "b2b587387e")

2) quit Emacs
3) ~/doom-emacs/bin/doom upgrade --packages

**Comment by George9000** [comment]
For those few, those hearty few, who also use ESS with Emacs 28 and run into similar eldoc errors, the ESS maintainers have posted a fix.

Here's what I did.
1. in ~/.doom.d/packages
(unpin! ess)
(package! ess :recipe (:host github :repo "emacs-ess/ESS"))

2. quit Emacs

3. doom sync

4. ~/doom-emacs/bin/doom upgrade --packages

On restart of Emacs, error disappears when editing, for example, R source.

**Comment by hlissner** [comment]
As of 6704cfd and a8a9181 I've bumped `ess` and `org`, which should resolve the issue on Doom's side. Thanks for bringing it to my attention @George9000!
