### ISSUE TITLE
Dealing with non-popup buffers with names that start with an asterisk

### ISSUE THREAD

**Issue by UndeadKernel** [hlissner/doom-emacs#354]
Many packages create buffers that are not associated to a file. Most of these buffers have names that start with an asterisk. It is often not desirable to associate these buffers with the functionality that goes on top of *popups*. More specifically, sometimes it is not desirable to have some buffer with a name that starts with an asterisk assigned the minor mode **+Popup**. This mode changes some bindings and makes other bindings related to popups affect them.

---

### Observed behavior

I'm trying to create a new module for the **ein* package. This is a package for working with IPython (aka Jupyter) notebooks. Every time a notebook is opened, the name of the notebook will be similar to:
```
*ein: http://localhost:888/notebook.ipynb*
```
These buffers, although looking like popups, should not be treated like one.

### Expected behavior

Just as the popup system now has an **:ignore** flag, maybe a **:disable** flag could be useful.

What is your take on this Mr. @hlissner?

**Comment by hlissner** [comment]
I agree. In fact, I'd like to fix `:ignore` to do what you suggest `:disable` do. That is its intention. I may have to abstract something over `display-buffer-alist` to pull it off properly. I'm looking into it.

**Comment by hlissner** [comment]
Sorry for the late follow up. The popup manager has changed drastically in all this time. The `:ignore` property now does pretty much what I had envisioned a `:disable` flag would do, so I'll consider this issue resolved. Let me know if that isn't the case and I will reopen this.
