### ISSUE TITLE
wrong type argument commandp, lsp-rename

### ISSUE THREAD

**Issue by DakshMiglani** [hlissner/doom-emacs#3563]
**What did you expect to happen?**
lsp-rename should rename the variable name

**What actually happened?**
received an error: wrong type argument commandp, lsp-rename

**Additional details:**
config: doom default
keybinding: SPC c r
language: python

**Comment by hlissner** [comment]
This means the `:tools lsp` module isn't enabled. [How to enable Doom modules](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#modules).

**Comment by DakshMiglani** [comment]
Thanks `:lang (python +lsp)` is the one that worked!
