### ISSUE TITLE
sqlite3 (from org-roam) freezing org-agenda

### ISSUE THREAD

**Issue by cantao** [hlissner/doom-emacs#3564]
I'm not sure if the problem is `(org +roam)` or specific of `org-roam`, so I'm posting here first.

I have a pretty standard setup with `org-roam`: non-roam org files go to `~/docs/org` and roam ones to `~/docs/org/roam`. Everything is working just fine, except for the agenda. `org-agenda-files` is configured as follows
``` elisp
(setq org-agenda-files (list "~/docs/org" "~/docs/org/roam"))
```

**What did you expect to happen?**
Emacs generates a list of all TODOs on both directories.

**What actually happened?**
Emacs and sqlite running forever. `ps aux | grep sqlite` shows:
``` shell
/usr/bin/sqlite3 --batch --list --separator   --nullvalue nil --noheader /home/user/docs/org/roam/org-roam.db
```

**Additional details:**
- If I disable `+roam` on `init.el` everything works as expected with the agenda.
- Can't see \*Warnings\* or \*Messages\* because Emacs is waiting for sqlite3 forever (it seems).

**Steps to reproduce:**
1. Hit `SPC o A t` to generate a list of all TODO entries
2. After a few moments, a list of all TODOs from org files on both directories

**System information:**
<details><pre>
```
emacs   version    26.3
        features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2
        build      mai 19, 2020
        buildopts  (--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-wide-int --with-modules 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now)
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop af76c873a 2020-07-15 01:11:01 -0400
        dir        ~/.doom.d/
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /usr/bin/zsh
        uname      Linux 5.7.0-3-MANJARO #1 SMP PREEMPT Wed Jun 3 03:15:33 UTC 2020 x86_64
        path       (~/.zinit/plugins/pyenv---pyenv/shims ~/.zinit/plugins/pyenv---pyenv/bin ~/.zinit/polaris/sbin ~/.zinit/polaris/bin ~/.zinit/polaris/usr/sbin ~/.zinit/polaris/usr/bin ~/local/bin ~/bin ~/.local/bin /usr/local/sbin /usr/local/bin /usr/bin ~/.config/bspwm ~/.config/bspwm/panel ~/.bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /var/lib/snapd/snap/bin ~/android/sdk/tools ~/android/sdk/platform-tools ~/android/sdk/tools/bin ~/bin /usr/lib/emacs/26.3/x86_64-pc-linux-gnu/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company (helm +fuzzy) :ui deft doom doom-dashboard doom-quit hl-todo modeline ophints (popup +defaults) vi-tilde-fringe workspaces zen :editor (evil +everywhere) file-templates fold parinfer :emacs dired electric undo :term vterm :checkers syntax :tools editorconfig (eval +overlay) lookup pdf :lang cc data (dart +flutter) emacs-lisp javascript latex markdown (org +roam) python sh :email (mu4e +gmail) :app calendar :config (default +bindings +smartparens))
        packages   ((org-ref) (org-roam-bibtex) (org-msg))
        unpin      (n/a)
        elpa       (n/a)
```
</pre></details>

**Comment by wedens** [comment]
1) It's more org-mode or org-roam issue then doom
2) Agenda can be very slow with a lot of files, so adding all roam files to agenda is infeasible. Try to rethink your notes/todos organization. Maybe add todos to some specific file in agenda like `todos.org` with references to specific notes.

**Comment by cantao** [comment]
1. Ok, I'll post on org-roam issues.
2. That's the point. With org-roam turned off the agenda is basically instantaneous. I have like 20 files (started using org-roam a few days ago). But the organization with a `todos.org` seems interesting. Thanks.

**Comment by cantao** [comment]
By the way, I'll leave the bug open for now. If I find something useful I'll post here.

**Comment by wedens** [comment]
Yeah, 20 files is not a lot, but it won't scale well as you add more notes.

**Comment by cantao** [comment]
It seems it was really a problem on org-roam. Moved to the Github version and eveything is working fine. Thanks for your time and for the amazing piece of work that is Doom Emacs!
