### ISSUE TITLE
LSP dart-analysis-server performance issue

### ISSUE THREAD

**Issue by haditim** [hlissner/doom-emacs#3567]
Hello guys. Here I am with yet another issue :D. I have read through many online PRs and tracked issue but none of them fixed the performance problem I have when coding in flutter. This issue seems to be the most relevant one for my case (https://github.com/dart-lang/sdk/issues/37060). I also tried with `Dart sdk 2.9.0.5.0.dev` in which the performance was much better but still laggy.

**What did you expect to happen?**
An acceptable performance in auto completion when coding in flutter.

**What actually happened?**
Each auto-completion takes 2-3 seconds during which the Emacs freezes.

**Additional details:**
- Include a link to your private config
https://github.com/haditim/.doom.d
- I also added the following to my config.el with no big difference:
```
(setq read-process-output-max (* 1024 1024))
(setq company-lsp-cache-candidates t
         company-lsp-filter-candidates t)
```

profiler output:
<details><pre>
**CPU**:

- ...                                                            9512  72%
 - company-calculate-candidates                                  7239  55%
  - company--fetch-candidates                                    7239  55%
   - company-call-backend-raw                                    7239  55%
    - apply                                                      7239  55%
     - company-capf                                              7239  55%
      - company-capf--candidates                                 7239  55%
       - completion-all-completions                              7239  55%
        - completion--nth-completion                             7239  55%
         - completion--some                                      7239  55%
          - #<compiled 0x2c405e5>                                7239  55%
           - completion-basic-all-completions                    7239  55%
            - completion-pcm--all-completions                    7239  55%
             - all-completions                                   7239  55%
              - #<compiled 0x3883035>                            7239  55%
               - #<compiled 0x399f38d>                           7239  55%
                - lsp-request-while-no-input                     7239  55%
                 - accept-process-output                         7022  53%
                  - #<compiled 0x2116801>                        7009  53%
                   - json-read-from-string                       6789  51%
                    - json-read                                  6789  51%
                     - json-read-object                          6789  51%
                      - json-read                                6789  51%
                       - json-read-array                         6769  51%
                        - json-read                              6739  51%
                         - json-read-object                      6393  48%
                          - json-read                            5319  40%
                           + json-read-object                    4161  31%
                             json-read-number                      20   0%
                            json-new-object                       135   1%
                            json-add-to-object                     17   0%
                     apply                                         26   0%
                 + lsp-request-async                               29   0%
   Automatic GC                                                  2228  17%
 + ad-Advice-delete-backward-char                                  17   0%
 + #<lambda 0x3d7b77558a>                                          13   0%
 + lsp--cancel-request                                              8   0%
 + #<compiled 0x19b921d>                                            7   0%
+ #<compiled 0x2116801>                                          2823  21%
+ command-execute                                                 686   5%
+ redisplay_internal (C function)                                  54   0%
+ timer-event-handler                                              22   0%

**Memory**:

- timer-event-handler                                     915,879,217  44%
 - apply                                                  915,877,105  44%
  - company-idle-begin                                    913,887,528  44%
   - company-auto-begin                                   913,887,528  44%
    - company--perform                                    913,887,528  44%
     - company--begin-new                                 913,887,528  44%
      - company-calculate-candidates                      913,875,080  44%
       - company--fetch-candidates                        913,875,080  44%
        - company-call-backend-raw                        913,875,080  44%
         - apply                                          913,875,080  44%
          - company-capf                                  913,875,080  44%
           - company-capf--candidates                     913,875,080  44%
            - completion-all-completions                  913,875,080  44%
             - completion--nth-completion                 913,875,080  44%
              - completion--some                          913,875,080  44%
               - #<compiled 0x1a5e6d5>                    913,875,080  44%
                - completion-basic-all-completions        913,860,578  44%
                 - completion-pcm--all-completions        913,860,578  44%
                  - all-completions                       913,859,470  44%
                   - #<compiled 0x429ae01>                913,859,470  44%
                    - #<compiled 0x12f4df9>               913,859,470  44%
                     - lsp-request-while-no-input         913,854,278  44%
                      - accept-process-output             861,316,755  42%
                       - #<compiled 0x2116801>            850,870,855  41%
                        - json-read-from-string           700,393,714  34%
                         - json-read                      700,378,781  34%
                          - json-read-object              700,378,781  34%
                           - json-read                    700,370,509  34%
                            - json-read-array             699,854,001  34%
                             - json-read                  699,190,137  34%
                              - json-read-object          699,190,137  34%
                               - json-read                416,103,119  20%
                                + json-read-object        382,964,437  18%
                                  json-read-number          1,852,316   0%
                                  json-read-string              1,546   0%
                                 json-new-object          254,409,496  12%
                                 json-read-string              21,000   0%
                                 json-add-to-object             4,654   0%
                              json-read-number                  5,440   0%
                            + json-read-object                  5,244   0%
                             json-new-object                    8,272   0%
                         + #<compiled 0x51674d>                 8,188   0%
                           generate-new-buffer                  5,305   0%
                          apply                            25,938,056   1%
                          mapcar                                2,096   0%
                          string-bytes                          1,445   0%
                       + xselect-convert-to-string              1,196   0%
                      + lsp-request-async                     260,907   0%
                      + input-pending-p                         2,392   0%
                     + lsp--capf-get-context                    4,136   0%
                    completion-pcm--pattern->regex              1,108   0%
                + helm-completion-all-completions               9,314   0%
                + completion-pcm-all-completions                5,188   0%
      + company-call-backend                                   12,448   0%
  + lsp--on-change-debounce                                   875,642   0%
  + #<compiled 0x2042eb>                                      642,906   0%
  + #<lambda 0x3d7b77558a>                                    290,263   0%
  + lsp--on-idle                                              168,374   0%
  + flycheck--handle-idle-trigger                              10,280   0%
    jit-lock-context-fontify                                    1,056   0%
  + show-paren-function                                         1,056   0%
 - timer-activate-when-idle                                     2,112   0%
  + timer--activate                                             2,112   0%
+ #<compiled 0x2116801>                                   631,976,181  30%
+ command-execute                                         490,430,169  24%
+ redisplay_internal (C function)                           1,944,562   0%
+ evil-escape-pre-command-hook                                 18,504   0%
+ winner-save-old-configurations                               17,776   0%
+ lsp--post-command                                            12,928   0%
+ xselect-convert-to-string                                    10,256   0%
+ ...                                                           9,244   0%
+ xselect-convert-to-targets                                    5,192   0%
+ company-post-command                                          4,224   0%
+ lsp-ui-sideline                                               3,168   0%
+ flycheck-maybe-display-error-at-point-soon                    1,280   0%
+ sp--save-pre-command-state                                    1,056   0%
+ hl-line-highlight                                             1,056   0%
+ eldoc-schedule-timer                                          1,056   0%
+ sp--pair-overlay-post-command-handler                           320   0%

</pre></details>

**Steps to reproduce:**
1. Start adding/editing a component in a flutter dart file.

**System information:**
<details>

```
emacs   version    26.3
        features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2
        build      May 19, 2020
        buildopts  (--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-wide-int --with-modules 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now)
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop 1cec7bf8b 2020-07-12 22:48:47 -0400
        dir        ~/.doom.d/
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /usr/bin/zsh
        uname      Linux 5.7.0-3-MANJARO #1 SMP PREEMPT Wed Jun 3 03:15:33 UTC 2020 x86_64
        path       (~/.emacs.d/bin/../bin ~/.pyenv/shims ~/.local/bin /usr/local/bin /usr/bin /bin /usr/local/sbin /opt/android-sdk/tools /opt/android-sdk/tools/bin /opt/flutter/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /usr/lib/emacs/26.3/x86_64-pc-linux-gnu/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion (company +auto +childframe) helm ivy :ui doom doom-dashboard hl-todo modeline nav-flash ophints (popup +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold format multiple-cursors rotate-text snippets :emacs dired electric ibuffer vc :checkers syntax spell grammar :tools ansible (docker +lsp) (eval +overlay) lookup lsp magit make pdf rgb :lang data (dart +flutter +lsp) emacs-lisp (javascript +lsp +tide) markdown org raku php (python +lsp) (rust +lsp) sh (web +lsp) yaml :config (default +bindings +smartparens))
        packages   ((flycheck) (py-autopep8) (blacken) (pip-requirements) (python-pytest) (python-pylint) (live-py-mode) (py-yapf) (direnv) (yasnippet) (arduino-mode) (dockerfile-mode) (ob-http) (ng2-mode) (prettier-js) (outshine))
        unpin      (n/a)
        elpa       (n/a)
```
</details>

**Comment by hlissner** [comment]
Try upgrading to Emacs 27 (with native json support). Emacs 26 does not have a `read-process-output-max`, and LSP is particularly memory hungry, especially the chatty servers.

I'm not a dart user though, so I'm happy to be proven wrong, but if it is still slow after that then I can only assume this is an issue with the dart server. Not all servers are created equal and will respond differently to differently sized projects.

**Comment by hlissner** [comment]
I should also mention that Doom's `:tools lsp` module optimizes `read-process-output-max`, `gc-cons-threshold` and integration with company (we don't use company-lsp, we use company-capf -- which is faster; also, lsp-mode has deprecated company-lsp), so you really don't need to optimize yourself. In fact you may be doing more damage than good that way.

**Comment by haditim** [comment]
Thanks a lot for the reply. I will give the 27 and gccemacs a try and let you know. I will also remove the optimizations I added to my config.

**Comment by ericdallo** [comment]
Actually this was kind of a bug in `dart-sdk`, in flutter 12 it was returning 5.000+ but after some refactors, flutter 1.17 was returning 26.000+ completion items where it's obvious unnecessary for a IDE completion.
After `dart-sdk` `2.9.0-19.0`, this was fixed decreasing the completion items to 800+.

c/c @haditim
