### ISSUE TITLE
Adding format package does not change auto-indent rules

### ISSUE THREAD

**Issue by pcesar22** [hlissner/doom-emacs#3568]
I added the "format" package by including it in init.el. 

In my use case, I am using C and have a .clang-format in my projectile-root. I'm using `<SPC> c f` to format my code calling `format/buffer-region` 

However, emacs still has auto indent set to another config. For example, when I type 

```typedef enum {``` and press enter, the cursor is aligned with the "t":

``` c
typedef enum { // Press enter
|<------ cursor
}
```

Where it should, according to the format rules, be indented. 

```c
typedef enum { // Press enter
  |<------ cursor should be here.
}
```

Additionally, if I highlight and press "=" to indent, the indentation is not the same as if I do `<SPC> c f`, which is fairly annoying. I would expect installing the `format` package to be consistent with `evil-indent`. 

**Steps to reproduce:**
1. Install `format` by adding it to init.el
2. In a new, empty folder, Install clang-format and run `clang-format -style=llvm -dump-config > .clang-format`
3. Create a C file and place the following code:
``` c
typedef enum {
  Cmd_Hello,
  Cmd_Write,
  Cmd_Read,
  Cmd_Invalid
} CmdType;
```
4. Highlight the region and press "="
5. The enums are now flush with the left side.
6. Highlight the region and press `<SPC> c f`
7. Observe the different alignment.

**Comment by hlissner** [comment]
Unfortunately, Doom nor any of its plugins can sync your formatting settings with your project's formatter. I'd recommend using [editorconfig](https://editorconfig.org/) (Doom also has a `:tools editorconfig` module for integration) or change the appropriate variables yourself, e.g.

```elisp
(after! cc-mode (setq c-basic-offset 2)) ; set it globally
(setq-hook! 'c++-mode-hook c-basic-offset 2) ; set it in c++-mode buffers
```

Or set them project-locally with a .dir-locals.el file in your project's root, containing

```elisp
((c++-mode . (c-basic-offset . 2)))
```

**Comment by hlissner** [comment]
Ah, and there's also `M-x doom/set-indent-width`

**Comment by robbert-vdh** [comment]
Also take a look at `c-offsets-alist`. For instance to match the `Chromium` clang-format style, I have this in my private config:

```elisp
(setq c-offsets-alist '((innamespace . 0)
                        (access-label . /)
                        (inclass . +)))

(setq-hook! '(c-mode-hook c++-mode-hook) c-basic-offset 4)
```
