### ISSUE TITLE
"(map!) could have a "override" keyword just like in general!

### ISSUE THREAD

**Issue by mrbig033** [hlissner/doom-emacs#3573]

**Comment by hlissner** [comment]
`(map! :map override ...)`

**Comment by mrbig033** [comment]
So obvious, so simple. Who could I not think of that? That's a good a idea for the documentation if not already. And again, thank you so much for all your helpful, civil, and extremely careful answers. Keep up the good work!

**Comment by hlissner** [comment]
Glad I could help! If you aren't opposed to the idea I'd recommend stopping by [our Discord](https://discord.gg/qvGgnVx) to ask usage/elisp questions of the sort, or to ask about development. 

I'd like to clean out all but bug reports from our issue tracker to make it easier for folks to search for issues. I may one day create a discourse so the community can have a more accessible knowledge base for these sorts of questions, but that's some ways away.
