### ISSUE TITLE
`doom/find-file-in-private-config` cuts off the first two characters of the file name

### ISSUE THREAD

**Issue by oakrc** [hlissner/doom-emacs#3586]
**What did you expect to happen?**
`SPC f p` and `M-x doom/find-file-in-private-config` should give a list of private config files (`config.el` `init.el` and `packages.el`) and when I choose a file by hitting enter, Doom Emacs should lead me to the right config file.

**What actually happened?**
`SPC f p` and `doom/find-file-in-private-config` gives a list of config file names but without the first two characters, for example: `nfig.el` `it.el` and `ckages.el`. I also tried pressing `SPC p p` and then selecting `~/.doom.d/` and it has the same bug. Choosing the file names would open `~/.doom.d/nfig.el` etc.

**Additional details:**
- [My config](https://gist.github.com/oakrc/dff744018d628788484cc6cc6c96c492)
- Screenshot:
![image](https://user-images.githubusercontent.com/25710522/87863711-cc282a00-c912-11ea-8645-de6df4df6d82.png)
- No warnings in `*Messages*` buffer

**Steps to reproduce:**
1. `git clone --depth 1 https://github.com/hlissner/doom-emacs ~/.emacs.d && doom install`
2. `SPC f p`
3. Observe the cut-off file names

**System information:**
<details><pre>
((emacs
  (version . "28.0.50")
  (features . "XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP")
  (build . "Jun 10, 2020")
  (buildopts "--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --mandir=/usr/share/man --with-gameuser=:games --with-sound=alsa --with-modules --without-gconf --without-gsettings --with-x-toolkit=gtk3 --without-xaw3d --without-compress-install 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -flto' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "grafted, HEAD -> develop, origin/develop, origin/HEAD 77f554c 2020-07-17 23:34:44 -0400")
  (dir . "~/.doom.d/"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/usr/bin/fish")
  (uname . "Linux 5.7.8-arch1-1 #1 SMP PREEMPT Thu, 09 Jul 2020 16:34:01 +0000 x86_64")
  (path "~/bin" "~/bin" "/usr/local/sbin" "/usr/local/bin" "/usr/bin" "/usr/bin/site_perl" "/usr/bin/vendor_perl" "/usr/bin/core_perl" "~/.local/bin" "~/.emacs.d/bin/" "~/.local/bin" "~/.emacs.d/bin/" "/usr/lib/emacs/28.0.50/x86_64-pc-linux-gnu"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :input chinese japanese :completion company (ivy +fuzzy +icons) :ui deft doom doom-dashboard doom-quit hl-todo minimap modeline ophints (popup +all +defaults) pretty-code tabs treemacs unicode vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold format multiple-cursors snippets :emacs dired electric ibuffer undo vc :term eshell vterm :checkers syntax :tools (debugger +lsp) docker ein (eval +overlay) gist (lookup +dictionary +offline) lsp (magit +forge) (pass +auth) pdf rgb tmux :lang (cc +lsp) data emacs-lisp (json +lsp) (java +lsp) (javascript +lsp) (latex +cdlatex +fold +lsp) ledger (markdown +grip) (org +present +dragndrop +hugo +noter +dragndrop +journal +jupyter +roam +pomodoro) php (python +lsp +pyenv) qt rust (sh +lsp +fish) web yaml :app calendar irc :config literate (default +bindings +smartparens))
  (packages (org-fancy-priorities) (origami) (indium) (org-roam-server) (ascii-art-to-unicode) (org-ref) (org-roam-bibtex) (ivy-bibtex) (parsebib :recipe (:files ("*.el"))) (nov) (mathpix\.el :recipe (:host github :repo "jethrokuan/mathpix.el")) (fish-mode) (systemd) (ssh-config-mode) (protobuf-mode) (calctex :recipe (:host github :repo "johnbcoughlin/calctex" :files ("calctex-pkg.el" "org-calctex/*el" "calctex*/*el"))) (org-tanglesync) (org-projectile))
  (unpin org-roam)
  (elpa "n/a")))

</pre></details>

**Comment by hlissner** [comment]
Should be fixed by 8991571. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
