### ISSUE TITLE
Evil: `x` no longer modifies register

### ISSUE THREAD

**Issue by stkSGarcia** [hlissner/doom-emacs#3588]
**What did you expect to happen?**

In normal mode, press `x`, and then press `p`. It should paste the deleted character.

**What actually happened?**

`p` pastes whatever was in register, before pressing `x`.

**Additional details:**

The related issue: https://github.com/emacs-evil/evil/issues/1335
Updating evil may solve the problem, from `(package! evil :pin "017b4421e24786a2f593d5e5c9ea0525e4ff272d")`
to `(package! evil :pin "2bc6ca3587502fde67b93e411e329fc8224c916a")`

**Comment by hlissner** [comment]
I've bumped evil in 804523, which should resolve this issue. Thanks for bringing it to my attention!
