### ISSUE TITLE
Flyspell highlights correct words

### ISSUE THREAD

**Issue by tprk77** [hlissner/doom-emacs#3592]
**What did you expect to happen?**

I would expect:

- `flyspell` to only highlight incorrect words
- `flyspell` to always agree with `ispell`

**What actually happened?**

In some situations, `flyspell` will highlight a correct word, for example "timezones". Checking the word with `ispell-word` will say the word is spelled correctly. Checking the word with `aspell` on the command line:

```
~ λ echo "timezones" | aspell -a
@(#) International Ispell Version 3.1.20 (but really Aspell 0.60.7-20110707)
& timezones 9 0: time zones, time-zones, timezone, timelines, timeline's, timeliness, Timon's, demesnes, demesne's

~ λ echo "timezones" | aspell -a --run-together
@(#) International Ispell Version 3.1.20 (but really Aspell 0.60.7-20110707)
-
```

Which seems to indicate that the issue has something to do with `--run-together`.

**Additional details:**
Please see the steps to reproduce. The issue seem to be with `--run-together` getting "randomly" removed from `ispell-extra-args`. The issue appears to be caused by this hook:

```
     (add-hook! 'text-mode-hook
       (defun +spell-remove-run-together-switch-for-aspell-h ()
         (setq-local ispell-extra-args (remove "--run-together" ispell-extra-args))))
```

I'm not really sure the purpose of this hook? Digging through Git history, I'm kind of guessing that this is old code that should have been removed at some point?

So I tried removing this hook, and it seemed to fix the issue without causing any problems. If that's an appropriate fix, I will gladly submit a pull request.

**Steps to reproduce:**
1. Open test.txt
1. Turn on flyspell-mode
1. Type "Timezones is spelled correctly?"
1. Notice that "timezones" is not highlighted
1. Check `ispell-extra-args` is `("--sug-mode=ultra" "--run-together" "--dont-tex-check-comments")`
1. Open test.org
1. Type "Timezones is spelled correctly?"
1. Notice "timezones" IS highlighted
1. Check `ispell-extra-args` is `("--sug-mode=ultra" "--dont-tex-check-comments")`
1. Close both files
1. Open test.txt
1. Type "Timezones is spelled correctly?"
1. Notice "timezones" IS highlighted
1. Check `ispell-extra-args` is `("--sug-mode=ultra" "--dont-tex-check-comments")`

**System information:**
<details><pre>
emacs   version    28.0.50
        features   XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER LCMS2
        build      Jul 18, 2020
        buildopts  (--build=x86_64-linux-gnu --prefix=/usr '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' --sysconfdir=/etc --localstatedir=/var --disable-silent-rules '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' --disable-maintainer-mode --disable-dependency-tracking --prefix=/usr --sharedstatedir=/var/lib --program-suffix=-snapshot --with-modules=yes --with-x=yes --with-x-toolkit=gtk3 --with-xwidgets=yes 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/emacs-snapshot-Zqvxib/emacs-snapshot-100629=. -fstack-protector-strong -Wformat -Werror=format-security' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro')
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop, origin/develop, origin/HEAD a8a918121 2020-07-19 00:36:37 -0400
        dir        ~/.doom.d/
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/bash
        uname      Linux 5.3.0-46-generic #38~18.04.1-Ubuntu SMP Tue Mar 31 04:17:56 UTC 2020 x86_64
        path       (~/.local/bin /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /usr/games /usr/local/games /snap/bin /usr/lib/x86_64-linux-gnu/emacs/28.0.50/x86_64-linux-gnu)
config  envfile    nil
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline ophints (popup +defaults) vc-gutter vi-tilde-fringe :editor file-templates fold snippets :emacs dired electric undo vc :term eshell term :checkers syntax spell :tools (eval +overlay) lookup lsp magit :lang (cc +lsp) common-lisp data emacs-lisp json lua markdown org python sh web yaml :config (default +bindings +smartparens))
        packages   (n/a)
        unpin      (n/a)
        elpa       (n/a)
</pre></details>

**Comment by hlissner** [comment]
Quite a few changes were made since this issue was first opened. Do you still see the problem?

**Comment by tprk77** [comment]
Sorry for the delay, I will check it out tonight.

**Comment by tprk77** [comment]
So I checked again and it's still doing the wrong thing. Words like `timezones` are highlighted as an error, but calling `(+spell/correct)` (M-$ for me) says "TIMEZONES is correct".

Before I had mentioned `ispell-extra-args` was sometimes including `--run-together` and sometimes not. It's now consistently missing `--run-together`, so now it's consistently wrong.

**Comment by tprk77** [comment]
So ignore what I said about `flyspell`, `ispell`, and `ispell-extra-args`, because I think I'm out of date on this. It seems Doom is now using `Spell-Fu` which I am not familiar with.

Regardless, it is still misbehaving as I have described above.

**Comment by tprk77** [comment]
I think I might close this ticket for #4239, which should be much more clear.

I realized "timezones" was kind of a bad example. It just so happens that "timezones" is not a word in the dictionary (on my version of Ubuntu at least). The `--run-together` option was making it appear to work, but it was also allowing nonsense words like "timezoneapple" which was undesirable. So the real issue is really about weirdness with `--run-together`.
