### ISSUE TITLE
org-re-reveal doesn't work for me

### ISSUE THREAD

**Issue by 20jam** [hlissner/doom-emacs#3595]
**What did you expect to happen?**
- Add `+present` to init
- C-c C-e v b
- Slides YAY!!

**What actually happened?**
- C-c C-e v b
- Rendered Html page of the content with no slides 

**System information:**
<details><pre>

```elisp
((emacs
  (version . "26.3")
  (features . "XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS
GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2")
  (build . "May 19, 2020")
  (buildopts "--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-wide-int
--with-modules 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD 46d6d0b 2020-06-29 15:12:30 -0400")
  (dir . "~/.doom.d/"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/bin/zsh")
  (uname . "Linux 5.7.4-arch1-1 #1 SMP PREEMPT Thu, 18 Jun 2020 16:01:07 +0000 x86_64")
  (path "~/.gem/ruby/2.7.0/bin" "~/.local/share/npm/bin" "~/.config/composer/vendor/bin" "~/.gem/ruby/2.7.0/bin" "~/.local/share/npm/bin"
"~/.config/composer/vendor/bin" "/usr/local/sbin" "/usr/local/bin" "/usr/bin" "/usr/lib/jvm/default/bin" "/usr/bin/site_perl" "/usr/bin/vendor_perl" "/usr/bin/core_perl" "~/.local/bin/util" "~/.local/bin/os" "~/.local/bin/" "~/code/suckless/bin/bar" "~/code/suckless/bin/" "~/code/zsh/bin/" "~/.emacs.d/bin/" "~/.cache/nvim/dein/repos/github.com/junegunn/fzf/bin" "/usr/lib/emacs/26.3/x86_64-pc-linux-gnu"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion ivy :ui deft doom hl-todo indent-guides ophints (popup +defaults) workspaces zen :editor (evil +everywhere) file-templates snippets :emacs undo vc :checkers syntax :tools (eval +overlay) pdf :lang emacs-lisp javascript latex markdown (org +hugo +roam +gnuplot +dragndrop +journal +noter +present) php plantuml ruby sh :config (default +bindings +smartparens))
  (packages (org-roam-server) (org-ref) (org-roam-bibtex) (helm-org)
(org-recent-headings) (org-bullets) (org-pretty-tags) (org-ql) (org-super-agenda) (org-fancy-priorities) (company-org-roam) (yasnippet-snippets :recipe (:host github :repo "AndreaCrotti/yasnippet-snippets" :files ("*"))) (emacs-snippets :recipe (:host github :repo "hlissner/emacs-snippets" :files ("*"))) (org-pdftools) (org-noter-pdftools))
  (unpin "n/a")
  (elpa "ts" "transient" "simple-httpd" "s" "popup" "peg" "parsebib"
"ov" "org-super-agenda" "org-sidebar" "org-roam-server" "org-roam-bibtex" "org-roam" "org-recent-headings" "org-ql" "org-fancy-priorities" "org" "map" "ht" "helm-org" "helm-core" "helm" "frecency" "f" "emacsql-sqlite3" "emacsql" "dash-functional" "dash" "company-org-roam" "company" "bibtex-completion" "biblio-core" "biblio" "async" "a")))
```

</pre></details>

**Comment by ezchi** [comment]
For me, the generated HTML file has all the content but just not rendered as slice. I have a workaround with local reveal.js repository (Can not make it work with https://revealjs.com).

1. Checkout reveal.js repository
`git clone https://github.com/hakimel/reveal.js.git`

2. Set reveal.js version to "4"
`(setq org-re-reveal-revealjs-version "4")`

3. Set **reveal_root** to local reveal.js, assume it is located at /tmp/reveal.js
`#+reveal_root: file:///tmp/reveal.js`

Regenerate the HTML file, it should be rendered as slice now.

**Comment by hlissner** [comment]
This appears to be an upstream issue. The link urls to https://reveal.js that org-re-reveal are no longer valid (404). I'll look into a fix or workaround.

**Comment by hlissner** [comment]
Reported: https://gitlab.com/oer/emacs-reveal/-/issues/21

I'll keep this issue open until it's resolved upstream.

**Comment by lechten** [comment]
I just updated org-re-reveal to remove the outdated URL from `org-re-reveal-root`. The following should work for now, but I do not see reveal.js advertising an official CDN location. Instead, reveal.js recommends to download a local copy. Anyways:

```
(setq org-re-reveal-root "https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.9.2"
      org-re-reveal-revealjs-version "3.8")
```

Note that the above uses an older version of reveal.js.

Also note that [emacs-reveal](https://gitlab.com/oer/emacs-reveal/) can setup reveal.js and several of its plugins.

**Comment by zzamboni** [comment]
Just in case it's useful for anyone: I put together this snippet to automatically check out `reveal.js` under `~/.emacs.d/.local`, and configure `org-re-reveal` to use it. This way you can use the latest version, with all the supported features (e.g. speaker notes work fine for me now):
```
(after! (org-re-reveal magit)
  (setq org-re-reveal-root (concat doom-local-dir "reveal.js")
        org-re-reveal-revealjs-version "4")
  (unless (file-directory-p org-re-reveal-root)
    (magit-run-git-async "clone" "https://github.com/hakimel/reveal.js.git" org-re-reveal-root)))
```

**Comment by hlissner** [comment]
Thanks to #3846 (and @zzamboni), Doom's `:lang (org +present)` submodule will default to and install revealjs v4, so enabling `+present` should be all that is needed for now.
