### ISSUE TITLE
org-roam-directory missing trailing slash(/) in Windows

### ISSUE THREAD

**Issue by lld2001** [hlissner/doom-emacs#3596]
**What did you expect to happen?**

`org-roam` require `org-roam-directory` set with a  "/" . the following forms will return wrong path if `org-roam-directory`  without trailing "/".  That can cause `org-roam-jump-to-index` wrong.
```emacs lisp
(org-roam--get-index-path)
``` 
e.g.  when `org-directory` is "E:/emacs/org", `org-roam-directory`  will be "E:/emacs/org/roam"(need trailing /),`(org-roam--get-index-path)` will return "E:/emacs/org/roamindex.org"

**Comment by hlissner** [comment]
As of #3597 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
