### ISSUE TITLE
Different Indent guides between daemon vs standalone mode

### ISSUE THREAD

**Issue by DakshMiglani** [hlissner/doom-emacs#3604]
**What did you expect to happen?**
In standalone emacs, indent guides are somewhat transparent:
![image](https://user-images.githubusercontent.com/23355449/88087484-9bf8b980-cba6-11ea-82d2-8a8c2919fe75.png)

**What actually happened?**
In emacs running as a daemon `/usr/bin/emacs --daemon` and opened as `emacsclient -c`, the indent guides look like:
![image](https://user-images.githubusercontent.com/23355449/88087569-c0ed2c80-cba6-11ea-91cb-84fb539ed9a5.png)

**Additional details:**
default doom config with indent guides on
emacs 28

**Comment by jgoerzen** [comment]
Interesting.  I also run it as a daemon and had seen the latter, and quickly turned it off.  I'd use it if it were lighter as in your first picture.

**Comment by DakshMiglani** [comment]
One thing i noticed, if you start emacs standalone (gui not daemon) first and then open emacsclient, then the transparency magically appears.

**Comment by hlissner** [comment]
Sorry for the late response. As of 3907e75 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
