### ISSUE TITLE
Add an easy way to disable smartparens

### ISSUE THREAD

**Issue by vmalloc** [hlissner/doom-emacs#3609]
Currently there doesn't seem be a way to disable smartparens globally. 

Including this in `config.el`:
```
(after! smartparens
  (smartparens-global-mode -1))
```
Seems to have no real effect (opening new files starts with smartparens mode still).
Also taking the suggestion of one of the users from Discord doesn't work:
```
(add-hook 'doom-first-buffer-hook
          (cmd!! smartparens-global-mode nil))
```
or even:
```
(add-hook 'doom-first-buffer-hook
          (lambda() (smartparens-global-mode nil)))
```

It would have been nice if there was a well documented way of disabling smartparens globally. It's not for everyone...

Thanks in advance!

**Comment by skaven-gear** [comment]
I think what you search is :

(remove-hook 'doom-first-buffer-hook #'smartparens-global-mode)

**Comment by vmalloc** [comment]
@skaven-gear indeed this solves it! Is there a place in the docs this is described in some way?

**Comment by skaven-gear** [comment]
No. I looked with `ripgred` into the doom repository and looked into the functions with `describe-function` for finding this solution.

But this make me thing there is a documentation about disabling a module in Doom :
Just delete the +smartparens flag from your init.el file under the :config key. 
It is cleaner to do so.

**Comment by vmalloc** [comment]
@skaven-gear that's the point - I don't have `+smaratparens` anywhere in my `init.el`...

**Comment by hlissner** [comment]
> Just delete the +smartparens flag from your init.el file under the :config key.
> It is cleaner to do so.

This is incorrect and will not do what you want.

The `:config default` module has a `+smartparens` flag which controls the _default configuration_ of smartparens. It does not control how or whether or not smartparens-mode is activated.
