### ISSUE TITLE
Some Ligatures not Displayed in Emacs 28.0.50 (or older)

### ISSUE THREAD

**Issue by AlessandroW** [hlissner/doom-emacs#3611]
**What did you expect to happen?**
See ligatures in python.

**What actually happened?**
Only some ligatures are displayed.
E.g. not working for `str` but also for `True`,`False` and `not` . Some are working (`lambda`, `and`..)

**Additional details:**
![image](https://user-images.githubusercontent.com/29565912/88189791-baf45b80-cc39-11ea-98ce-3362e32ac1d4.png)

![image](https://user-images.githubusercontent.com/29565912/88189533-736dcf80-cc39-11ea-9239-9a06b40f9525.png)
![image](https://user-images.githubusercontent.com/29565912/88190102-29391e00-cc3a-11ea-85c2-4a9c14478d66.png)

**Steps to reproduce:**
1. `SPC x`
2. `M-x python-mode`
3. Insert
 ```python
 if True is not False:
    return None
```

**System information:**
<details><pre>
        build      Jul 22, 2020
        buildopts  (--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --mandir=/usr/share/man --with-gameuser=:games --with-sound=alsa --with-modules --without-gconf --without-gsettings --with-x-toolkit=gtk3 --without-xaw3d --without-compress-install 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -flto' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now)
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop 200fd52b6 2020-05-28 22:01:23 -0400
        dir        ~/.doom.d/
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/zsh
        uname      Linux 5.7.9-arch1-1 #1 SMP PREEMPT Thu, 16 Jul 2020 19:34:49 +0000 x86_64
        path       (~/.emacs.d/bin ~/.pyenv/shims ~/.pyenv/bin ~/.nvm/versions/node/v12.6.0/bin ~/.npm-packages/bin /usr/local/bin /usr/bin /bin /usr/local/sbin /opt/flutter/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /var/lib/snapd/snap/bin ~/.local/bin /opt/apache-spark/bin /usr/lib/emacs/28.0.50/x86_64-pc-linux-gnu/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo hydra indent-guides minimap modeline nav-flash ophints (popup +defaults) pretty-code tabs treemacs unicode vc-gutter vi-tilde-fringe window-select workspaces zen :editor (evil +everywhere) file-templates fold (format +onsave) multiple-cursors snippets :emacs dired electric undo vc :term vterm :checkers syntax spell grammar :tools debugger editorconfig ein (eval +overlay) lookup lsp magit pdf :lang emacs-lisp json javascript markdown (org +dragndrop) (python +pyenv +poetry +lsp) sh yaml :config (default +bindings +smartparens))
        packages   ((keyfreq) (ox-hugo) (org-super-agenda))
        unpin      (n/a)
        elpa       (n/a)
```
</details>
</pre></details>

**Comment by gagbo** [comment]
It depends on your font really, it just means you're lacking the symbols in your font. you can use `(after! python-mode (set-pretty-symbols! 'python-mode nil))`

**Comment by hlissner** [comment]
This is certainly a font issue. I will close this since it isn't a Doom issue. 

As an alternative to gagbo's solution, you can disable pretty symbols in python mode with:

```elisp
(setq +pretty-code-enabled-modes '(not python-mode))
```

**Comment by AlessandroW** [comment]
Thanks for pointing out nerd-fonts but that didn't help as well..
I switched to Iosevka and the stable emacs version (26.3).
As described in https://github.com/hlissner/doom-emacs/tree/develop/modules/ui/pretty-code#not-emacs-mac-and-emacs--27 I added the `+iosevka` flag but it didn't solve the problem.
![image](https://user-images.githubusercontent.com/29565912/88455622-1fe8c500-ce77-11ea-8b4c-3ff83534fc50.png)

`M-x describe-font`
```
name (opened by): -CYEL-Iosevka-normal-normal-normal-*-19-*-*-*-d-0-iso10646-1
full name: Iosevka:pixelsize=19:foundry=CYEL:weight=normal:slant=normal:width=normal:spacing=90:scalable=true
file name: /usr/share/fonts/TTF/Iosevka Medium Nerd Font Complete.ttf
```

**Comment by hlissner** [comment]
@AlessandroW Is the Symbola font installed on your system?

**Comment by AlessandroW** [comment]
No, it was not. Installing it solved the math symbol issue.
However, for Fira Code it creates new problems.
Whether installed via doom emacs, or AUR (both standard and nerd fonts) I get these artifacts:
![image](https://user-images.githubusercontent.com/29565912/88476051-7fa5a580-cf35-11ea-84f6-33a620e0351a.png)
![image](https://user-images.githubusercontent.com/29565912/88476054-87fde080-cf35-11ea-80ea-00af6fcaef04.png)
Where `:, x` becomes a character looking like k and `!=, >=` become different characters as well..
![image](https://user-images.githubusercontent.com/29565912/88476077-c3001400-cf35-11ea-80dc-a25d671941b5.png)

When switching to Iosevka it works as expected:
![image](https://user-images.githubusercontent.com/29565912/88476136-520d2c00-cf36-11ea-936b-ccaa0610d69a.png)
![image](https://user-images.githubusercontent.com/29565912/88476139-5c2f2a80-cf36-11ea-99eb-1f78c5e441cf.png)
