### ISSUE TITLE
Org-Protocol invocation results in a non-full screen window

### ISSUE THREAD

**Issue by jmgrosen** [hlissner/doom-emacs#3614]
**What did you expect to happen?**
When I open `emacsclient` with an `org-protocol://capture` link, I expect the org-capture window to take up the whole frame.

**What actually happened?**
The org-capture window appears as a pop up window at the bottom (like it does when capturing from within an existing Emacs frame).

**Additional details:**
Screenshot: 
![org-capture pop-up window screenshot](https://user-images.githubusercontent.com/442136/88207133-5925f880-cc1d-11ea-8897-ee3a1e66e38d.png)

I think you basically want to override `pop-to-buffer` when handling `org-protocol` links to fix this. I currently have registered this advice as a workaround:
```elisp
(defadvice! org--server-visit-files-full-screen (oldfun &rest args)
  "Make org-capture from org-protocol invocation full screen.

TODO: only apply this for org-protocol"
  :around #'server-visit-files
  (letf! ((#'pop-to-buffer #'switch-to-buffer))
    (apply oldfun args)))
```
...but this applies for all `emacsclient` invocations that visit files, which is probably not what you want.

**Steps to reproduce:**
1. Configure Doom to have Org enabled.
2. Launch an Emacs daemon one way or another.
3. Open an `org-protocol` link with `emacsclient`, e.g. `emacsclient -c 'org-protocol://capture?url=foo'`

**System information:**
<details><pre>
((emacs
  (version . "26.3")
  (features . "XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD")
  (build . "Jul 22, 2020")
  (buildopts "--prefix=/nix/store/5v6xrwlwn093aaka44bq8k9dqcgz825a-emacs-26.3 --disable-build-details --with-modules --with-x-toolkit=gtk3 --with-xft CFLAGS=-DMAC_OS_X_VERSION_MAX_ALLOWED=101200")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop 042cc781b 2020-06-20 03:02:05 -0400")
  (dir . "~/.doom.d/"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/run/current-system/sw/bin/bash")
  (uname . "Linux 5.4.47 #1-NixOS SMP Wed Jun 17 14:40:38 UTC 2020 x86_64")
  (path "/run/wrappers/bin" "~/.nix-profile/bin" "/etc/profiles/per-user/john/bin" "/nix/var/nix/profiles/default/bin" "/run/current-system/sw/bin" "/nix/store/5v6xrwlwn093aaka44bq8k9dqcgz825a-emacs-26.3/libexec/emacs/26.3/x86_64-pc-linux-gnu"))
 (config
  (envfile)
  (elc-files . 0)
  (modules :completion company helm :ui deft doom doom-dashboard doom-quit fill-column hl-todo minimap modeline nav-flash ophints (popup +defaults) treemacs vc-gutter vi-tilde-fringe window-select :editor (evil +everywhere) file-templates fold snippets word-wrap :emacs dired electric undo vc :term vterm :checkers syntax spell :tools debugger ein (eval +overlay) lookup lsp magit make pass pdf :lang cc coq data emacs-lisp faust fstar (haskell +dante) json latex lean ledger markdown nix (org +noter +present +dragndrop) python racket rest (rust +lsp) scheme sh yaml :email notmuch :app calendar (rss +org) twitter :config literate (default +bindings +smartparens))
  (packages (helm-bibtex) (org-ref) (org-chef :recipe (:host nil :repo "file:///home/john/code/org-chef") :pin "160f2e5859") (org-sidebar) (helm-rg :recipe (:host github :repo "braineo/helm-rg") :pin "50b8a6f2bb91aecbb32a628cfd098b91f0f08593"))
  (unpin "n/a")
  (elpa "n/a")))
</pre></details>

**Comment by hlissner** [comment]
[A popup rule](https://github.com/hlissner/doom-emacs/blob/develop/modules/lang/org/config.el#L801) is in effect. It is tailored to folks who use org-capture within an interactive session.

To get around it use/call `+org-capture/open-frame` instead. This is what our [bin/org-capture](https://github.com/hlissner/doom-emacs/blob/develop/bin/org-capture#L36) script uses. In fact, I'd recommend you use that script anyway, instead of calling `org-capture` directly via emacsclient.

I'll close this since this is a usage/workflow question, rather than a bug report. Feel free to follow up here or [on our discord](https://discord.gg/qvGgnVx).

**Comment by hlissner** [comment]
Oh, forgot to mention, another way to get around the popup rule:

```elisp
(defadvice! open-org-capture-in-current-window (oldfun &rest args)
  :around #'org-protocol-capture
  (let (display-buffer-alist)
    (apply oldfun args)))
```
