### ISSUE TITLE
Org export to markdown

### ISSUE THREAD

**Issue by hh02** [hlissner/doom-emacs#3616]
When I export the org file to markdown, the formula `$a+b$` is converted to `\(a+b\)`, `\` is an escape character in markdown, `\\(a+b \\)` is correct.

**Comment by huihao2002** [comment]
by the way, when exporting to markdown, how to remain `$' instead of `/(` ?

**Comment by hlissner** [comment]
Did you find a solution to this?

**Comment by hh02** [comment]
@hlissner, I find it's the bug of org, not doom, 
Org mode use the function "org-format-latex" in "org.el" to process latex fragment.
org.el's path: ~/.emacs.d/.local/straight/build/org-mode/org.el"
In org.el function "org-format-latex":
``` elisp
(if (string= (match-string 0 value) "$$")
    (insert "\\[" (substring value 2 -2) "\\]")
    (insert "\\(" (substring value 1 -1) "\\)"))))
```
in markdown it should be :
``` elisp
(if (string= (match-string 0 value) "$$")
    (insert "\\\\[" (substring value 2 -2) "\\\\]")
    (insert "\\\\(" (substring value 1 -1) "\\\\)"))))
```
Obviously org-mode does not perform a specific conversion for markdown latex fraggment.

In a word, I think it's the reason that org mode does not escape the  latex delimiters for markdown, so I give up it . 

Now , I use pandoc integrated in doom, It's more powerful and adjustable. It can convert org files into markdwon in any format( such as gfm(github flavored markdown).

**Comment by hlissner** [comment]
i see. Thank you for the explanation!
