### ISSUE TITLE
A super sllimed Down version so people can opt-in on all the features instead of the opposite

### ISSUE THREAD

**Issue by mrbig033** [hlissner/doom-emacs#3624]
**Describe the feature**
- Given the target audience of this project and its highly modular nature, it seems natural to make it even more modular. Right now, the recomended installing procedure will add many packages that are possible of no use for my users.
- I proposoe a bare bones version of Doom Emacs in which the user can *previously* select which features and flags they wanna add, with a certain degre of granurality. The awesome Doom macros are perfect to make this process even easier.
- If the feature is implemented in another editor or Emacs distro, include:
  - I don't think that is the case. You can of course implement whatever you want on bare bones Emacs, but that's a big understaning. On the other hand, Spacemacs, while also great, provides too many layers of abstraction between user and Emacs, in such a way that defeats the purpose of having a highly personalized configuration.

**System information**
<details><pre>
((emacs
  (version . "27.0.91")
  (features . "RSVG IMAGEMAGICK GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS JSON PDUMPER LCMS2 GMP")
  (build . "May 14, 2020")
  (buildopts "--disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus/HEAD-747e0a2/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus/HEAD-747e0a2 --with-xml2 --without-dbus --with-gnutls --with-imagemagick --with-json --with-modules --with-rsvg --with-ns --disable-ns-self-contained")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "grafted, HEAD -> develop, origin/develop, origin/HEAD 576eb40 2020-07-16 17:38:43 -0400")
  (dir . "~/.doom.d/"))
 (system
  (type . darwin)
  (config . "x86_64-apple-darwin18.7.0")
  (shell . "/usr/local/bin/bash")
  (uname . "Darwin 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64")
  (path "~/.emacs.d/bin" "~/scripts/bin" "~/.nimble/bin" "~/scripts/cline_scripts/" "~/.emacs.d/bin" "/usr/local/opt/sqlite/bin" "~/.emacs.d/bin" "~/scripts/bin" "~/.nimble/bin" "~/scripts/cline_scripts/" "~/.emacs.d/bin" "/usr/local/opt/sqlite/bin" "/usr/local/opt/openjdk/bin" "~/.pyenv/shims" "~/.pyenv/bin" "~/.local/bin" "~/.emacs.d/bin" "~/scripts/bin" "~/.nimble/bin" "~/scripts/cline_scripts/" "~/.emacs.d/bin" "/usr/local/opt/sqlite/bin" "/usr/local/bin" "/usr/bin" "/bin" "/usr/sbin" "/sbin" "/Library/TeX/texbin" "/opt/X11/bin" "/Library/Frameworks/Mono.framework/Versions/Current/Commands" "~" "~/.fzf/bin" "/usr/local/Cellar/emacs-plus/HEAD-747e0a2/libexec/emacs/27.0.91/x86_64-apple-darwin18.7.0"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion (company +childframe) (ivy +prescient) :ui doom hydra indent-guides modeline :editor (evil +everywhere) fold multiple-cursors snippets word-wrap :emacs (dired +ranger) electric undo vc :term eshell vterm :checkers syntax spell grammar :tools (lookup +dictionary +offline) pdf :lang emacs-lisp markdown (org +pomodoro) python sh :config (default +bindings +smartparens))
  (packages (delight) (wordnut) (olivetti) (hl-sentence) (eyebrowse) (recursive-narrow) (hl-sentence) (evil-swap-keys) (google-translate) (evil-smartparens) (unkillable-scratch) (electric-operator) (zenburn-theme) (git-auto-commit-mode) (engine-mode :pin "e0910f1") (evil-better-visual-line) (bug-hunter) (org-roam :disable t) (evil-lion :disable t) (org-brain :disable t) (evil-lion :disable t) (evil-snipe :disable t))
  (unpin "n/a")
  (elpa "n/a")))
</pre></details>

**Comment by hlissner** [comment]
If I understood correctly, you want a `doom install` step that doesn't install your packages, so you can go into `init.el` and disable what you want first.

This exists. See `doom help install`, you'll find this in the docs:

```
  --no-install
    Don't auto-install packages
```

So `doom install --no-install`

With this switch, it will create your dummy `~/.doom.d` and you can modify your init.el however you like, then run `doom sync` when you're ready.

Of course, you can bypass `doom install` entirely by [installing Doom manually, as I've documented in our getting started guide](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#install-doom-manually). Doing it manually it really quite easy.

The recommended procedure exists as an easy first-time setup for beginners. If you are not a beginner, you may be better off not using it.
