### ISSUE TITLE
lispy's unintended configuration

### ISSUE THREAD

**Issue by sorawee** [hlissner/doom-emacs#3625]
**What did you expect to happen?**
The "states" position inside `atom-movement` should be something like `t`, or else there shouldn't be any "states" position at all. It's unclear which one is what you intend to use.

**What actually happened?**
The "states" position inside `atom-movement` is [`normal` and `visual`](https://github.com/hlissner/doom-emacs/blob/develop/modules/editor/lispy/config.el#L25), but this won't do what it's intended to be done, because according to the documentation:

> The states argument is repurposed to determine whether to override the WORD motions instead.

**Additional details:**

None

**Steps to reproduce:**

None

**System information:**

Not relevant.

**Comment by hlissner** [comment]
As of 3580a3f I've replaced it with a `t`, which should resolve this. Let me know if that causes any problems and I'll reopen this thread. Thanks for bringing it to my attention!
