### ISSUE TITLE
After creating a snippet with aya-persist-snippet and restarting emacs, the snippet no longer works

### ISSUE THREAD

**Issue by benjfisk** [hlissner/doom-emacs#3627]
**What did you expect to happen?**
Execute the snippet completion.

**What actually happened?**
No completion is executed.

**Steps to reproduce:**
Create a snippet then close and reopen emacs, then try execute the snippet you created.

**Comment by hlissner** [comment]
As of b2787a9 this should be resolved. In the future please remember to include your `M-x doom/info`.

Let me know if the issue resurfaces and I'll reopen it. Thanks for bringing it to my attention!
