### ISSUE TITLE
Python LSP: pyenv command "xx" not found

### ISSUE THREAD

**Issue by benmezger** [hlissner/doom-emacs#3628]
**What did you expect to happen?**
Error should not be shown when `mypy`, `pylint` etc is not found.

**What actually happened?**
When saving the buffer, it tries to run `mypy`, `pylint` giving an error if not found.
This actually happened after an upgrade from Emacs 27 to 28 and after running `doom upgrade && doom update`.

**Additional details:**
- [Private config](https://github.com/benmezger/dotfiles/blob/e887b28ca1b74512c949f9fee88c359df9cc3f8f/doom-emacs/.doom.d/config.el#L53)

Disabling flycheck-mode fixes the issue, so I am not sure if this is related to pyenv itself, or flycheck

<details><pre>
Try installing a more recent version of python-mypy, and please open a bug report if the issue persists in the latest release.  Thanks!
Debug on Error enabled globally
Quit
Suspicious state from syntax checker python-flake8: Flycheck checker python-flake8 returned 127, but its output contained no errors: pyenv: flake8: command not found

The `flake8' command exists in these Python versions:
  2.7.17/envs/pyls27
  3.5.7
  3.5.7/envs/pythonls
  3.6.0/envs/skyroam
  3.7.0
  3.7.0/envs/bank-scraper
  3.7.0/envs/banking-api
  3.7.0/envs/blog
  3.7.0/envs/boma
  3.7.0/envs/debugger
  3.7.0/envs/dip
  3.7.0/envs/pyls-dev
  3.7.0/envs/weebble
  3.7.3/envs/bakercli
  3.7.3/envs/requests
  3.7.3/envs/somos-py37
  3.7.3/envs/ward
  3.8.0/envs/engstats
  bakercli
  bank-scraper
  banking-api
  blog
  boma
  debugger
  dip
  engstats
  pyls-dev
  pyls27
  pythonls
  requests
  skyroam
  somos-py37
  ward
  weebble

Note: See 'pyenv help global' for tips on allowing both
      python2 and python3 to be found.

Try installing a more recent version of python-flake8, and please open a bug report if the issue persists in the latest release.  Thanks!
Suspicious state from syntax checker python-pylint: Flycheck checker python-pylint returned 127, but its output contained no errors: pyenv: pylint: command not found

The `pylint' command exists in these Python versions:
  2.7.17/envs/pyls27
  3.5.7
  3.5.7/envs/pythonls
  3.6.0/envs/skyroam
  3.7.0/envs/pyls-dev
  3.8.0/envs/engstats
  engstats
  pyls-dev
  pyls27
  pythonls
  skyroam

Note: See 'pyenv help global' for tips on allowing both
      python2 and python3 to be found.

Try installing a more recent version of python-pylint, and please open a bug report if the issue persists in the latest release.  Thanks!
Already formatted
Wrote /var/folders/25/cy4pgsqn2393lvfmh420gf7h0000gn/T/isortCRG1aC.py
Could not apply isort. Check *isort Errors* for details
Wrote /Users/benmezger/workspace/polar-sapiens-py/src/user/models.py
"src/user/models.py" 90L, 2695C written
Suspicious state from syntax checker python-flake8: Flycheck checker python-flake8 returned 127, but its output contained no errors: pyenv: flake8: command not found

The `flake8' command exists in these Python versions:
  2.7.17/envs/pyls27
  3.5.7
  3.5.7/envs/pythonls
  3.6.0/envs/skyroam
  3.7.0
  3.7.0/envs/bank-scraper
  3.7.0/envs/banking-api
  3.7.0/envs/blog
  3.7.0/envs/boma
  3.7.0/envs/debugger
  3.7.0/envs/dip
  3.7.0/envs/pyls-dev
  3.7.0/envs/weebble
  3.7.3/envs/bakercli
  3.7.3/envs/requests
  3.7.3/envs/somos-py37
  3.7.3/envs/ward
  3.8.0/envs/engstats
  bakercli
  bank-scraper
  banking-api
  blog
  boma
  debugger
  dip
  engstats
  pyls-dev
  pyls27
  pythonls
  requests
  skyroam
  somos-py37
  ward
  weebble

Note: See 'pyenv help global' for tips on allowing both
      python2 and python3 to be found.

Try installing a more recent version of python-flake8, and please open a bug report if the issue persists in the latest release.  Thanks!
Suspicious state from syntax checker python-pylint: Flycheck checker python-pylint returned 127, but its output contained no errors: pyenv: pylint: command not found

The `pylint' command exists in these Python versions:
  2.7.17/envs/pyls27
  3.5.7
  3.5.7/envs/pythonls
  3.6.0/envs/skyroam
  3.7.0/envs/pyls-dev
  3.8.0/envs/engstats
  engstats
  pyls-dev
  pyls27
  pythonls
  skyroam

Note: See 'pyenv help global' for tips on allowing both
      python2 and python3 to be found.

Try installing a more recent version of python-pylint, and please open a bug report if the issue persists in the latest release.  Thanks!
Suspicious state from syntax checker python-mypy: Flycheck checker python-mypy returned 127, but its output contained no errors: pyenv: mypy: command not found

The `mypy' command exists in these Python versions:
  3.5.7/envs/pythonls
  3.7.3/envs/somos-py37
  3.8.0/envs/engstats
  engstats
  pythonls
  somos-py37

Note: See 'pyenv help global' for tips on allowing both
      python2 and python3 to be found.

Try installing a more recent version of python-mypy, and please open a bug report if the issue persists in the latest release.  Thanks!
</pre></details>

**Steps to reproduce:**
1. Open a python buffer with LSP enabled and mypy/pylint not installed 
2. Save the file

**System information:**
<details><pre>
emacs   version    28.0.50
        features   JPEG TIFF GIF PNG RSVG IMAGEMAGICK GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS PDUMPER LCMS2
        build      Jul 23, 2020
        buildopts  (--disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus@28/28.0.50/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus@28/28.0.50 --with-xml2 --with-gnutls --without-dbus --with-imagemagick --with-modules --with-rsvg --with-ns --disable-ns-self-contained)
        windowsys  ns
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> refs/heads/develop aac73f4c0 2020-07-24 02:22:25 -0400
        dir        ~/dotfiles/doom-emacs/.doom.d/
system  type       darwin
        config     x86_64-apple-darwin19.5.0
        shell      /bin/zsh
        uname      Darwin 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64
        path       (~/.pyenv/plugins/pyenv-virtualenv/shims ~/.pyenv/shims /usr/local/bin /usr/bin /bin /usr/sbin /sbin /Library/TeX/texbin /usr/local/share/dotnet /opt/X11/bin ~/.dotnet/tools /Applications/Postgres.app/Contents/Versions/latest/bin ~/.pyenv/bin ~/.pyenv/plugins/pyenv-virtualenv/shims ~/.pyenv/shims ~/.bin ~/workspace/go/bin /usr/local/opt/go/libexec/bin /usr/local/opt/fzf/bin /Applications/Emacs.app/Contents/MacOS/bin-x86_64-10_14 /Applications/Emacs.app/Contents/MacOS/libexec-x86_64-10_14 /usr/local/Cellar/emacs-plus@28/28.0.50/libexec/emacs/28.0.50/x86_64-apple-darwin19.5.0/)
config  envfile    envvar-file
        elc-files  164
        modules    (:completion (company +auto +tng) (ivy +fuzzy) :ui deft doom doom-quit fill-column hl-todo modeline nav-flash ophints (popup +all +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates (format +onsave) rotate-text snippets :emacs dired electric ibuffer vc :term eshell :checkers syntax spell grammar :tools debugger editorconfig (eval +overlay) (lookup +docsets) lsp macos magit make terraform :lang (cc +lsp) (yaml +lsp) data emacs-lisp (go +lsp) markdown (org +roam +hugo +gnuplot +pancoc +dragndrop) (python +lsp +pyenv) rest (sh +lsp) :app (rss +org) :config (default +bindings +smartparens))
        packages   ((pyenv-mode-auto) (wakatime-mode) (ob-mermaid) (org-roam-server) (org-projectile) (yasnippet-snippets))
        unpin      (n/a)
        elpa       (n/a)

</pre></details>

**Comment by hlissner** [comment]
> doom upgrade && doom update.

This is redundant. Only `doom upgrade` is necessary.

> after an upgrade from Emacs 27 to 28 

Does `doom sync && doom build` fix the issue? [[Reason](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#updowngrading-emacs)]

> flake8: command not found
> pylint: command not found
> mypy: command not found

These seem like PATH or env issues, rather than Doom or Emacs issues. Perhaps your envvar file is outdated. Run `doom env` on the command line to re-dump your shell environment to a file that Doom reads at startup (or just `doom sync` will regenerate your envvar file).

**Comment by benmezger** [comment]
@hlissner the `env` file is updated, `sync/build` doesn't fix the issue. It seems that somehow it finds mypy in another python env, and tries to use it, then pyenv returns that error. Not sure what is really going on.

**Comment by benmezger** [comment]
Solved by.. randomly reinstalling Emacs
