### ISSUE TITLE
Terrible sorting of completions when using (cc +lsp).

### ISSUE THREAD

**Issue by h0cheung** [hlissner/doom-emacs#3630]
**What did you expect to happen?**
The items which are exactly matched should show up at the top. And fuzzy matches should show up below them.

**What actually happened?**
The order is terrible like this
[![abab1d42813c28cdd04a474e29d56c917cdc8e75.jpg](https://i.postimg.cc/7YbYTJpW/abab1d42813c28cdd04a474e29d56c917cdc8e75.jpg)](https://postimg.cc/TpMXz12V)

**Additional details:**
- Include a link to your private config
<https://gitlab.com/h-cheung/dotfiles/-/tree/master/doom.d>

I've searched for some discussions and I think this is more likely to be an issue about company.

**System information:**
<details><pre>
emacs   version    28.0.50
        features   XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER LCMS2
        build      7月 23, 2020
        buildopts  (--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --mandir=/usr/share/man --with-gameuser=:games --with-sound=alsa --with-modules --without-gconf --without-gsettings --with-nativecomp --with-x-toolkit=gtk3 --without-xaw3d --without-m17n-flt --with-cairo --with-xwidgets --without-compress-install 'CFLAGS=-march=native -O2 -pipe -march=native -fuse-ld=gold' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O2,--sort-common,--as-needed,-z,relro,-z,now)
        windowsys  x
        daemonp    daemon
doom    version    2.0.9
        build      HEAD -> develop afcf56a61 2020-07-24 19:27:50 -0400
        dir        ~/.doom.d/
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /usr/bin/zsh
        uname      Linux 5.7.9-zen1-1-zen-anbox #1 ZEN SMP PREEMPT Sun, 19 Jul 2020 13:08:36 +0000 x86_64
        path       (/usr/local/sbin /usr/local/bin /usr/bin /opt/cxoffice/bin /var/lib/flatpak/exports/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /usr/lib/emacs/28.0.50/x86_64-pc-linux-gnu)
config  envfile    nil
        elc-files  0
        modules    (:completion (company +childframe) (ivy +childframe +icons +prescient) :ui doom doom-dashboard doom-quit hl-todo hydra modeline ophints (popup +all +defaults) pretty-code treemacs vc-gutter vi-tilde-fringe window-select workspaces zen :editor (evil +everywhere) file-templates fold format multiple-cursors parinfer rotate-text snippets :emacs (dired +ranger +icons) electric (ibuffer +icons) undo vc :term eshell vterm :checkers (syntax +childframe) :tools (debugger +lsp) (eval +overlay) gist (lookup +dictionary +docsets) (lsp +peek) (magit +forge) make pass pdf rgb :lang (cc +lsp) emacs-lisp (json +lsp) (markdown +grip) (org +brain +dragndrop +gnuplot +hugo +journal +jupyter +pandoc +pomodoro +present) (python +lsp) qt (sh +lsp) (yaml +lsp) :config (default +bindings +smartparens) :h-cheung vterm-run chinese (telega +auto-method) tools ui cc-extra systemd pkgbuild)
        packages   (n/a)
        unpin      (n/a)
        elpa       (n/a)

</pre></details>

**Comment by ni-ko-o-kin** [comment]
`(setq company-lsp-cache-candidates nil)` used to work for me. But now that company is replaced by capf this does not work anymore. You could revert to a version were company is still supported.

**Comment by h0cheung** [comment]
> `(setq company-lsp-cache-candidates nil)` used to work for me. But now that company is replaced by capf this does not work anymore. You could revert to a version were company is still supported.

There is `(setq-local company-lsp-cache-candidates nil)` in the cc module configs.

Which package should I downgrade, ccls, lsp-mode or company? Which version is recommended?

**Comment by h0cheung** [comment]
Setting `lsp--capf-no-reordering` to `t` and `company-transformers` to `nil` can solve this.

```elisp
(defadvice! capf-no-reordering (&rest _)
  :before '(+cc-init-lsp-h)
  (setq-local lsp--capf-no-reordering t))
```
This can set `lsp--capf-no-reordering`. Maybe `(setq-local lsp--capf-no-reordering t)` should be added to `+cc-init-lsp-h` in this project.

However, `company-transformers` is always set to `(company-prescient-transformer)`. I have tried `(after! ccls (setq-local ...))`, `(after! cc-mode (setq-local ...))` and even `(setq-default ...)` to set this variable to `nil`, but none works. This is very strange. I tried the "Find all references", but only `(setq-local company-transformers nil)` in +cc-init-lsp-h was found. I'm really confused by this.

The only way useful I find is to set this variable to `nil` by hand after a cc-mode buffer is open every time.

**Comment by h0cheung** [comment]
I finally find that this shit variable is set by `company-prescient-mode`, but I don't know how to disable it in configs. Just using `(company-prescient-mode 0)` doesn't work.

**Comment by h0cheung** [comment]
I've disabled `company-prescient` package globally, and wait for a better way to solve this.

**Comment by hlissner** [comment]
> Just using (company-prescient-mode 0) doesn't work.

1. `(remove-hook 'company-mode-hook #'company-prescient-mode)`
2. `(setq-hook! 'lsp-mode-hook company-prescient-sort-length-enable nil)`
3. `(package! company-prescient :disable t)`

----

In any case, I've been considering removing company-prescient for some time, because it introduces too many edge cases like these. It is finally removed in e7c2163, so I'll consider this resolved.
