### ISSUE TITLE
setq-local: Wrong number of arguments: (2 . 2), 8 : When trying to open any file via Projectile

### ISSUE THREAD

**Issue by kirubakaran** [hlissner/doom-emacs#3632]
**What did you expect to happen?**
I expected the selected file to be opened

**What actually happened?**
`setq-local: Wrong number of arguments: (2 . 2), 8` error occurred

**Additional details:**

<details><pre>
Debugger entered--Lisp error: (wrong-number-of-arguments (2 . 2) 8)
  #f(compiled-function (var val) "Set variable VAR to value VAL in current buffer." #<bytecode 0x1fda7be68ce9>)(git-gutter:init-function #'git-gutter-fr:init git-gutter:view-diff-function #'git-gutter-fr:view-diff-infos git-gutter:clear-function #'git-gutter-fr:clear git-gutter:window-width -1)
  (setq-local git-gutter:init-function #'git-gutter-fr:init git-gutter:view-diff-function #'git-gutter-fr:view-diff-infos git-gutter:clear-function #'git-gutter-fr:clear git-gutter:window-width -1)
  (if (and (display-graphic-p) (require 'git-gutter-fringe nil t)) (setq-local git-gutter:init-function #'git-gutter-fr:init git-gutter:view-diff-function #'git-gutter-fr:view-diff-infos git-gutter:clear-function #'git-gutter-fr:clear git-gutter:window-width -1) (setq-local git-gutter:init-function 'nil git-gutter:view-diff-function #'git-gutter:view-diff-infos git-gutter:clear-function #'git-gutter:clear-diff-infos git-gutter:window-width 1))
  (progn (if (and (display-graphic-p) (require 'git-gutter-fringe nil t)) (setq-local git-gutter:init-function #'git-gutter-fr:init git-gutter:view-diff-function #'git-gutter-fr:view-diff-infos git-gutter:clear-function #'git-gutter-fr:clear git-gutter:window-width -1) (setq-local git-gutter:init-function 'nil git-gutter:view-diff-function #'git-gutter:view-diff-infos git-gutter:clear-function #'git-gutter:clear-diff-infos git-gutter:window-width 1)) (git-gutter-mode 1) (remove-hook 'after-save-hook #'+vc-gutter-init-maybe-h 'local))
  (if (and (vc-backend file-name) (progn (require 'git-gutter) (not (memq major-mode git-gutter:disabled-modes)))) (progn (if (and (display-graphic-p) (require 'git-gutter-fringe nil t)) (setq-local git-gutter:init-function #'git-gutter-fr:init git-gutter:view-diff-function #'git-gutter-fr:view-diff-infos git-gutter:clear-function #'git-gutter-fr:clear git-gutter:window-width -1) (setq-local git-gutter:init-function 'nil git-gutter:view-diff-function #'git-gutter:view-diff-infos git-gutter:clear-function #'git-gutter:clear-diff-infos git-gutter:window-width 1)) (git-gutter-mode 1) (remove-hook 'after-save-hook #'+vc-gutter-init-maybe-h 'local)))
  (when (and (vc-backend file-name) (progn (require 'git-gutter) (not (memq major-mode git-gutter:disabled-modes)))) (if (and (display-graphic-p) (require 'git-gutter-fringe nil t)) (setq-local git-gutter:init-function #'git-gutter-fr:init git-gutter:view-diff-function #'git-gutter-fr:view-diff-infos git-gutter:clear-function #'git-gutter-fr:clear git-gutter:window-width -1) (setq-local git-gutter:init-function 'nil git-gutter:view-diff-function #'git-gutter:view-diff-infos git-gutter:clear-function #'git-gutter:clear-diff-infos git-gutter:window-width 1)) (git-gutter-mode 1) (remove-hook 'after-save-hook #'+vc-gutter-init-maybe-h 'local))
  (if (null file-name) (add-hook 'after-save-hook #'+vc-gutter-init-maybe-h nil 'local) (when (and (vc-backend file-name) (progn (require 'git-gutter) (not (memq major-mode git-gutter:disabled-modes)))) (if (and (display-graphic-p) (require 'git-gutter-fringe nil t)) (setq-local git-gutter:init-function #'git-gutter-fr:init git-gutter:view-diff-function #'git-gutter-fr:view-diff-infos git-gutter:clear-function #'git-gutter-fr:clear git-gutter:window-width -1) (setq-local git-gutter:init-function 'nil git-gutter:view-diff-function #'git-gutter:view-diff-infos git-gutter:clear-function #'git-gutter:clear-diff-infos git-gutter:window-width 1)) (git-gutter-mode 1) (remove-hook 'after-save-hook #'+vc-gutter-init-maybe-h 'local)))
  (progn (if (null file-name) (add-hook 'after-save-hook #'+vc-gutter-init-maybe-h nil 'local) (when (and (vc-backend file-name) (progn (require 'git-gutter) (not (memq major-mode git-gutter:disabled-modes)))) (if (and (display-graphic-p) (require 'git-gutter-fringe nil t)) (setq-local git-gutter:init-function #'git-gutter-fr:init git-gutter:view-diff-function #'git-gutter-fr:view-diff-infos git-gutter:clear-function #'git-gutter-fr:clear git-gutter:window-width -1) (setq-local git-gutter:init-function 'nil git-gutter:view-diff-function #'git-gutter:view-diff-infos git-gutter:clear-function #'git-gutter:clear-diff-infos git-gutter:window-width 1)) (git-gutter-mode 1) (remove-hook 'after-save-hook #'+vc-gutter-init-maybe-h 'local))))
  (if (or +vc-gutter-in-remote-files (not (file-remote-p (or file-name default-directory)))) (progn (if (null file-name) (add-hook 'after-save-hook #'+vc-gutter-init-maybe-h nil 'local) (when (and (vc-backend file-name) (progn (require 'git-gutter) (not (memq major-mode git-gutter:disabled-modes)))) (if (and (display-graphic-p) (require 'git-gutter-fringe nil t)) (setq-local git-gutter:init-function #'git-gutter-fr:init git-gutter:view-diff-function #'git-gutter-fr:view-diff-infos git-gutter:clear-function #'git-gutter-fr:clear git-gutter:window-width -1) (setq-local git-gutter:init-function 'nil git-gutter:view-diff-function #'git-gutter:view-diff-infos git-gutter:clear-function #'git-gutter:clear-diff-infos git-gutter:window-width 1)) (git-gutter-mode 1) (remove-hook 'after-save-hook #'+vc-gutter-init-maybe-h 'local)))))
  (when (or +vc-gutter-in-remote-files (not (file-remote-p (or file-name default-directory)))) (if (null file-name) (add-hook 'after-save-hook #'+vc-gutter-init-maybe-h nil 'local) (when (and (vc-backend file-name) (progn (require 'git-gutter) (not (memq major-mode git-gutter:disabled-modes)))) (if (and (display-graphic-p) (require 'git-gutter-fringe nil t)) (setq-local git-gutter:init-function #'git-gutter-fr:init git-gutter:view-diff-function #'git-gutter-fr:view-diff-infos git-gutter:clear-function #'git-gutter-fr:clear git-gutter:window-width -1) (setq-local git-gutter:init-function 'nil git-gutter:view-diff-function #'git-gutter:view-diff-infos git-gutter:clear-function #'git-gutter:clear-diff-infos git-gutter:window-width 1)) (git-gutter-mode 1) (remove-hook 'after-save-hook #'+vc-gutter-init-maybe-h 'local))))
  (let ((file-name (buffer-file-name (buffer-base-buffer)))) (when (or +vc-gutter-in-remote-files (not (file-remote-p (or file-name default-directory)))) (if (null file-name) (add-hook 'after-save-hook #'+vc-gutter-init-maybe-h nil 'local) (when (and (vc-backend file-name) (progn (require 'git-gutter) (not (memq major-mode git-gutter:disabled-modes)))) (if (and (display-graphic-p) (require 'git-gutter-fringe nil t)) (setq-local git-gutter:init-function #'git-gutter-fr:init git-gutter:view-diff-function #'git-gutter-fr:view-diff-infos git-gutter:clear-function #'git-gutter-fr:clear git-gutter:window-width -1) (setq-local git-gutter:init-function 'nil git-gutter:view-diff-function #'git-gutter:view-diff-infos git-gutter:clear-function #'git-gutter:clear-diff-infos git-gutter:window-width 1)) (git-gutter-mode 1) (remove-hook 'after-save-hook #'+vc-gutter-init-maybe-h 'local)))))
  +vc-gutter-init-maybe-h()
  run-hooks(find-file-hook)
  #f(compiled-function (&optional error warn noauto after-find-file-from-revert-buffer nomodes) "Called after finding a file and by the default revert function.\nSets buffer mode, parses file-local and directory-local variables.\nOptional args ERROR, WARN, and NOAUTO: ERROR non-nil means there was an\nerror in reading the file.  WARN non-nil means warn if there\nexists an auto-save file more recent than the visited file.\nNOAUTO means don't mess with auto-save mode.\nFourth arg AFTER-FIND-FILE-FROM-REVERT-BUFFER is ignored\n(see `revert-buffer-in-progress-p' for similar functionality).\nFifth arg NOMODES non-nil means don't alter the file's modes.\nFinishes by calling the functions in `find-file-hook'\nunless NOMODES is non-nil." #<bytecode 0x1fda7be55b01>)(nil t)
  apply(#f(compiled-function (&optional error warn noauto after-find-file-from-revert-buffer nomodes) "Called after finding a file and by the default revert function.\nSets buffer mode, parses file-local and directory-local variables.\nOptional args ERROR, WARN, and NOAUTO: ERROR non-nil means there was an\nerror in reading the file.  WARN non-nil means warn if there\nexists an auto-save file more recent than the visited file.\nNOAUTO means don't mess with auto-save mode.\nFourth arg AFTER-FIND-FILE-FROM-REVERT-BUFFER is ignored\n(see `revert-buffer-in-progress-p' for similar functionality).\nFifth arg NOMODES non-nil means don't alter the file's modes.\nFinishes by calling the functions in `find-file-hook'\nunless NOMODES is non-nil." #<bytecode 0x1fda7be55b01>) (nil t))
  (if (setq doom-large-file-p (and buffer-file-name (not doom-large-file-p) (file-exists-p buffer-file-name) (condition-case nil (progn (> (nth 7 (file-attributes buffer-file-name)) (* 1024 1024 (assoc-default buffer-file-name doom-large-file-size-alist ...)))) (error nil)))) (prog1 (apply orig-fn args) (if (memq major-mode doom-large-file-excluded-modes) (setq doom-large-file-p nil) (if (fboundp 'so-long-minor-mode) (progn (so-long-minor-mode 1))) (message "Large file detected! Cutting a few corners to impr..."))) (apply orig-fn args))
  doom--optimize-for-large-files-a(#f(compiled-function (&optional error warn noauto after-find-file-from-revert-buffer nomodes) "Called after finding a file and by the default revert function.\nSets buffer mode, parses file-local and directory-local variables.\nOptional args ERROR, WARN, and NOAUTO: ERROR non-nil means there was an\nerror in reading the file.  WARN non-nil means warn if there\nexists an auto-save file more recent than the visited file.\nNOAUTO means don't mess with auto-save mode.\nFourth arg AFTER-FIND-FILE-FROM-REVERT-BUFFER is ignored\n(see `revert-buffer-in-progress-p' for similar functionality).\nFifth arg NOMODES non-nil means don't alter the file's modes.\nFinishes by calling the functions in `find-file-hook'\nunless NOMODES is non-nil." #<bytecode 0x1fda7be55b01>) nil t)
  apply(doom--optimize-for-large-files-a #f(compiled-function (&optional error warn noauto after-find-file-from-revert-buffer nomodes) "Called after finding a file and by the default revert function.\nSets buffer mode, parses file-local and directory-local variables.\nOptional args ERROR, WARN, and NOAUTO: ERROR non-nil means there was an\nerror in reading the file.  WARN non-nil means warn if there\nexists an auto-save file more recent than the visited file.\nNOAUTO means don't mess with auto-save mode.\nFourth arg AFTER-FIND-FILE-FROM-REVERT-BUFFER is ignored\n(see `revert-buffer-in-progress-p' for similar functionality).\nFifth arg NOMODES non-nil means don't alter the file's modes.\nFinishes by calling the functions in `find-file-hook'\nunless NOMODES is non-nil." #<bytecode 0x1fda7be55b01>) (nil t))
  #f(advice-wrapper :around #f(compiled-function (&optional error warn noauto after-find-file-from-revert-buffer nomodes) "Called after finding a file and by the default revert function.\nSets buffer mode, parses file-local and directory-local variables.\nOptional args ERROR, WARN, and NOAUTO: ERROR non-nil means there was an\nerror in reading the file.  WARN non-nil means warn if there\nexists an auto-save file more recent than the visited file.\nNOAUTO means don't mess with auto-save mode.\nFourth arg AFTER-FIND-FILE-FROM-REVERT-BUFFER is ignored\n(see `revert-buffer-in-progress-p' for similar functionality).\nFifth arg NOMODES non-nil means don't alter the file's modes.\nFinishes by calling the functions in `find-file-hook'\nunless NOMODES is non-nil." #<bytecode 0x1fda7be55b01>) doom--optimize-for-large-files-a)(nil t)
  apply(#f(advice-wrapper :around #f(compiled-function (&optional error warn noauto after-find-file-from-revert-buffer nomodes) "Called after finding a file and by the default revert function.\nSets buffer mode, parses file-local and directory-local variables.\nOptional args ERROR, WARN, and NOAUTO: ERROR non-nil means there was an\nerror in reading the file.  WARN non-nil means warn if there\nexists an auto-save file more recent than the visited file.\nNOAUTO means don't mess with auto-save mode.\nFourth arg AFTER-FIND-FILE-FROM-REVERT-BUFFER is ignored\n(see `revert-buffer-in-progress-p' for similar functionality).\nFifth arg NOMODES non-nil means don't alter the file's modes.\nFinishes by calling the functions in `find-file-hook'\nunless NOMODES is non-nil." #<bytecode 0x1fda7be55b01>) doom--optimize-for-large-files-a) (nil t))
  #f(advice-wrapper :before #f(advice-wrapper :around #f(compiled-function (&optional error warn noauto after-find-file-from-revert-buffer nomodes) "Called after finding a file and by the default revert function.\nSets buffer mode, parses file-local and directory-local variables.\nOptional args ERROR, WARN, and NOAUTO: ERROR non-nil means there was an\nerror in reading the file.  WARN non-nil means warn if there\nexists an auto-save file more recent than the visited file.\nNOAUTO means don't mess with auto-save mode.\nFourth arg AFTER-FIND-FILE-FROM-REVERT-BUFFER is ignored\n(see `revert-buffer-in-progress-p' for similar functionality).\nFifth arg NOMODES non-nil means don't alter the file's modes.\nFinishes by calling the functions in `find-file-hook'\nunless NOMODES is non-nil." #<bytecode 0x1fda7be55b01>) doom--optimize-for-large-files-a) doom-first-file-hook-h)(nil t)
  apply(#f(advice-wrapper :before #f(advice-wrapper :around #f(compiled-function (&optional error warn noauto after-find-file-from-revert-buffer nomodes) "Called after finding a file and by the default revert function.\nSets buffer mode, parses file-local and directory-local variables.\nOptional args ERROR, WARN, and NOAUTO: ERROR non-nil means there was an\nerror in reading the file.  WARN non-nil means warn if there\nexists an auto-save file more recent than the visited file.\nNOAUTO means don't mess with auto-save mode.\nFourth arg AFTER-FIND-FILE-FROM-REVERT-BUFFER is ignored\n(see `revert-buffer-in-progress-p' for similar functionality).\nFifth arg NOMODES non-nil means don't alter the file's modes.\nFinishes by calling the functions in `find-file-hook'\nunless NOMODES is non-nil." #<bytecode 0x1fda7be55b01>) doom--optimize-for-large-files-a) doom-first-file-hook-h) (nil t))
  after-find-file(nil t)
  find-file-noselect-1(#<buffer views.py> "~/Projects/histre/backend/mainapp/views/views.py" nil nil "~/Projects/histre/backend/mainapp/views/views.py" (18748467 66307))
  find-file-noselect("/home/kiru/Projects/histre/backend/mainapp/views/v..." nil nil nil)
  find-file("/home/kiru/Projects/histre/backend/mainapp/views/v...")
  #f(compiled-function (file) "Find FILE and run `projectile-find-file-hook'." #<bytecode 0x1e7cdf5>)("backend/mainapp/views/views.py")
  apply(#f(compiled-function (file) "Find FILE and run `projectile-find-file-hook'." #<bytecode 0x1e7cdf5>) "backend/mainapp/views/views.py")
  (let ((default-directory (ivy-state-directory ivy-last))) (apply orig-fn args))
  +ivy--run-from-ivy-directory-a(#f(compiled-function (file) "Find FILE and run `projectile-find-file-hook'." #<bytecode 0x1e7cdf5>) "backend/mainapp/views/views.py")
  apply(+ivy--run-from-ivy-directory-a #f(compiled-function (file) "Find FILE and run `projectile-find-file-hook'." #<bytecode 0x1e7cdf5>) "backend/mainapp/views/views.py")
  counsel-projectile-find-file-action("backend/mainapp/views/views.py")
  ivy-call()
  ivy-read("[histre] Find file: " ("theme/LICENSE.md" "theme/README.md" "theme/gulpfile.js" "theme/config.js" "theme/src/dashboard-alt.html" "theme/src/assets/css/theme.css" "theme/src/assets/css/theme-dark.css" "theme/src/assets/scss/theme.scss" "theme/src/assets/scss/theme-dark.scss" "theme/src/assets/scss/_user-variables.scss" "theme/src/assets/scss/dashkit/_type.scss" "theme/src/assets/scss/dashkit/_root.scss" "theme/src/assets/scss/dashkit/_navbar.scss" "theme/src/assets/scss/dashkit/_custom-forms.scss" "theme/src/assets/scss/dashkit/_variables.scss" "theme/src/assets/scss/dashkit/_nav.scss" "theme/src/assets/scss/dashkit/_utilities.scss" "theme/src/assets/scss/dashkit/_main-content.scss" "theme/src/assets/scss/dashkit/_list-group.scss" "theme/src/assets/scss/dashkit/vendors/_select2.scs..." "theme/src/assets/scss/dashkit/vendors/_flatpickr.s..." "theme/src/assets/scss/dashkit/vendors/_quill.scss" "theme/src/assets/scss/dashkit/vendors/_dropzone.sc..." "theme/src/assets/scss/dashkit/_badge.scss" "theme/src/assets/scss/dashkit/_card.scss" "theme/src/assets/scss/dashkit/_progress.scss" "theme/src/assets/scss/dashkit/_chart.scss" "theme/src/assets/scss/dashkit/_vendors.scss" "theme/src/assets/scss/dashkit/_avatar.scss" "theme/src/assets/scss/dashkit/_modal.scss" "theme/src/assets/scss/dashkit/mixins/_badge.scss" "theme/src/assets/scss/dashkit/_alert.scss" "theme/src/assets/scss/dashkit/_toasts.scss" "theme/src/assets/scss/dashkit/_breadcrumb.scss" "theme/src/assets/scss/dashkit/_code.scss" "theme/src/assets/scss/dashkit/_comment.scss" "theme/src/assets/scss/dashkit/_mixins.scss" "theme/src/assets/scss/dashkit/dark/_variables-dark..." "theme/src/assets/scss/dashkit/dark/_overrides-dark..." "theme/src/assets/scss/dashkit/_forms.scss" "theme/src/assets/scss/dashkit/_reboot.scss" "theme/src/assets/scss/dashkit/_jumbotron.scss" "theme/src/assets/scss/dashkit/_dashkit.scss" "theme/src/assets/scss/dashkit/_popover.scss" "theme/src/assets/scss/dashkit/_icon.scss" "theme/src/assets/scss/dashkit/_buttons.scss" "theme/src/assets/scss/dashkit/_dropdowns.scss" "theme/src/assets/scss/dashkit/_tables.scss" "theme/src/assets/scss/dashkit/utilities/_backgroun..." "theme/src/assets/scss/dashkit/utilities/_sizing.sc..." ...) :matcher counsel--find-file-matcher :require-match t :sort nil :action (1 ("o" counsel-projectile-find-file-action "current window") ("j" counsel-projectile-find-file-action-other-window "other window") ("x" counsel-projectile-find-file-action-extern "open externally") ("r" counsel-projectile-find-file-action-root "open as root") ("m" counsel-projectile-find-file-action-find-file-manually "find file manually") ("k" counsel-projectile-find-file-action-delete "delete") ("p" counsel-projectile-find-file-action-switch-project "switch project")) :caller counsel-projectile-find-file)
  counsel-projectile-find-file(nil)
  funcall-interactively(counsel-projectile-find-file nil)
  call-interactively(counsel-projectile-find-file)
  (cond ((and projectile-project-root (file-equal-p projectile-project-root default-directory)) (if (doom-project-p default-directory) nil (setq projectile-enable-caching nil)) (call-interactively (if (doom-module-p :completion 'ivy) #'counsel-projectile-find-file #'projectile-find-file))) ((fboundp 'counsel-file-jump) (call-interactively #'counsel-file-jump)) ((project-current) (project-find-file-in nil (list default-directory) nil)) ((fboundp 'helm-find-files) (call-interactively #'helm-find-files)) ((call-interactively #'find-file)))
  (let* ((default-directory (file-truename (expand-file-name dir))) (projectile-project-root (doom-project-root default-directory)) (projectile-enable-caching projectile-enable-caching)) (cond ((and projectile-project-root (file-equal-p projectile-project-root default-directory)) (if (doom-project-p default-directory) nil (setq projectile-enable-caching nil)) (call-interactively (if (doom-module-p :completion 'ivy) #'counsel-projectile-find-file #'projectile-find-file))) ((fboundp 'counsel-file-jump) (call-interactively #'counsel-file-jump)) ((project-current) (project-find-file-in nil (list default-directory) nil)) ((fboundp 'helm-find-files) (call-interactively #'helm-find-files)) ((call-interactively #'find-file))))
  doom-project-find-file("~/Projects/histre/")
  funcall(doom-project-find-file "~/Projects/histre/")
  (if current-prefix-arg nil (funcall +workspaces-switch-project-function +workspaces--project-dir))
  (if (and (not (null +workspaces-on-switch-project-behavior)) (or (eq +workspaces-on-switch-project-behavior t) (equal (safe-persp-name (get-current-persp)) persp-nil-name) (+workspace-buffer-list))) (let* ((persp (let ((project-name (doom-project-name +workspaces--project-dir))) (or (+workspace-get project-name t) (+workspace-new project-name)))) (new-name (progn (or (and (memq ... cl-struct-perspective-tags) t) (signal 'wrong-type-argument (list ... persp))) (aref persp 1)))) (+workspace-switch new-name) (save-current-buffer (set-buffer (doom-fallback-buffer)) (setq default-directory +workspaces--project-dir) (hack-dir-local-variables-non-file-buffer)) (if current-prefix-arg nil (funcall +workspaces-switch-project-function +workspaces--project-dir)) (+workspace-message (format "Switched to '%s' in new workspace" new-name) 'success)) (save-current-buffer (set-buffer (doom-fallback-buffer)) (setq default-directory +workspaces--project-dir) (hack-dir-local-variables-non-file-buffer) (message "Switched to '%s'" (doom-project-name +workspaces--project-dir))) (condition-case err (+workspace-rename (+workspace-current-name) (doom-project-name +workspaces--project-dir)) ((debug error) (message "Workspace error: %s" err) nil)) (if current-prefix-arg nil (funcall +workspaces-switch-project-function +workspaces--project-dir)))
  (unwind-protect (if (and (not (null +workspaces-on-switch-project-behavior)) (or (eq +workspaces-on-switch-project-behavior t) (equal (safe-persp-name (get-current-persp)) persp-nil-name) (+workspace-buffer-list))) (let* ((persp (let ((project-name ...)) (or (+workspace-get project-name t) (+workspace-new project-name)))) (new-name (progn (or (and ... t) (signal ... ...)) (aref persp 1)))) (+workspace-switch new-name) (save-current-buffer (set-buffer (doom-fallback-buffer)) (setq default-directory +workspaces--project-dir) (hack-dir-local-variables-non-file-buffer)) (if current-prefix-arg nil (funcall +workspaces-switch-project-function +workspaces--project-dir)) (+workspace-message (format "Switched to '%s' in new workspace" new-name) 'success)) (save-current-buffer (set-buffer (doom-fallback-buffer)) (setq default-directory +workspaces--project-dir) (hack-dir-local-variables-non-file-buffer) (message "Switched to '%s'" (doom-project-name +workspaces--project-dir))) (condition-case err (+workspace-rename (+workspace-current-name) (doom-project-name +workspaces--project-dir)) ((debug error) (message "Workspace error: %s" err) nil)) (if current-prefix-arg nil (funcall +workspaces-switch-project-function +workspaces--project-dir))) (run-hooks 'projectile-after-switch-project-hook) (setq +workspaces--project-dir nil))
  (progn (if projectile-before-switch-project-hook (progn (let ((temp-buffer (generate-new-buffer " *temp*"))) (save-current-buffer (set-buffer temp-buffer) (unwind-protect (progn (setq default-directory +workspaces--project-dir) (hack-dir-local-variables-non-file-buffer) (run-hooks ...)) (and (buffer-name temp-buffer) (kill-buffer temp-buffer))))))) (unwind-protect (if (and (not (null +workspaces-on-switch-project-behavior)) (or (eq +workspaces-on-switch-project-behavior t) (equal (safe-persp-name (get-current-persp)) persp-nil-name) (+workspace-buffer-list))) (let* ((persp (let (...) (or ... ...))) (new-name (progn (or ... ...) (aref persp 1)))) (+workspace-switch new-name) (save-current-buffer (set-buffer (doom-fallback-buffer)) (setq default-directory +workspaces--project-dir) (hack-dir-local-variables-non-file-buffer)) (if current-prefix-arg nil (funcall +workspaces-switch-project-function +workspaces--project-dir)) (+workspace-message (format "Switched to '%s' in new workspace" new-name) 'success)) (save-current-buffer (set-buffer (doom-fallback-buffer)) (setq default-directory +workspaces--project-dir) (hack-dir-local-variables-non-file-buffer) (message "Switched to '%s'" (doom-project-name +workspaces--project-dir))) (condition-case err (+workspace-rename (+workspace-current-name) (doom-project-name +workspaces--project-dir)) ((debug error) (message "Workspace error: %s" err) nil)) (if current-prefix-arg nil (funcall +workspaces-switch-project-function +workspaces--project-dir))) (run-hooks 'projectile-after-switch-project-hook) (setq +workspaces--project-dir nil)))
  (if (and persp-mode +workspaces--project-dir) (progn (if projectile-before-switch-project-hook (progn (let ((temp-buffer (generate-new-buffer " *temp*"))) (save-current-buffer (set-buffer temp-buffer) (unwind-protect (progn ... ... ...) (and ... ...)))))) (unwind-protect (if (and (not (null +workspaces-on-switch-project-behavior)) (or (eq +workspaces-on-switch-project-behavior t) (equal (safe-persp-name ...) persp-nil-name) (+workspace-buffer-list))) (let* ((persp (let ... ...)) (new-name (progn ... ...))) (+workspace-switch new-name) (save-current-buffer (set-buffer (doom-fallback-buffer)) (setq default-directory +workspaces--project-dir) (hack-dir-local-variables-non-file-buffer)) (if current-prefix-arg nil (funcall +workspaces-switch-project-function +workspaces--project-dir)) (+workspace-message (format "Switched to '%s' in new workspace" new-name) 'success)) (save-current-buffer (set-buffer (doom-fallback-buffer)) (setq default-directory +workspaces--project-dir) (hack-dir-local-variables-non-file-buffer) (message "Switched to '%s'" (doom-project-name +workspaces--project-dir))) (condition-case err (+workspace-rename (+workspace-current-name) (doom-project-name +workspaces--project-dir)) ((debug error) (message "Workspace error: %s" err) nil)) (if current-prefix-arg nil (funcall +workspaces-switch-project-function +workspaces--project-dir))) (run-hooks 'projectile-after-switch-project-hook) (setq +workspaces--project-dir nil))))
  (let (projectile-project-root) (if (and persp-mode +workspaces--project-dir) (progn (if projectile-before-switch-project-hook (progn (let ((temp-buffer ...)) (save-current-buffer (set-buffer temp-buffer) (unwind-protect ... ...))))) (unwind-protect (if (and (not (null +workspaces-on-switch-project-behavior)) (or (eq +workspaces-on-switch-project-behavior t) (equal ... persp-nil-name) (+workspace-buffer-list))) (let* ((persp ...) (new-name ...)) (+workspace-switch new-name) (save-current-buffer (set-buffer ...) (setq default-directory +workspaces--project-dir) (hack-dir-local-variables-non-file-buffer)) (if current-prefix-arg nil (funcall +workspaces-switch-project-function +workspaces--project-dir)) (+workspace-message (format "Switched to '%s' in new workspace" new-name) 'success)) (save-current-buffer (set-buffer (doom-fallback-buffer)) (setq default-directory +workspaces--project-dir) (hack-dir-local-variables-non-file-buffer) (message "Switched to '%s'" (doom-project-name +workspaces--project-dir))) (condition-case err (+workspace-rename (+workspace-current-name) (doom-project-name +workspaces--project-dir)) ((debug error) (message "Workspace error: %s" err) nil)) (if current-prefix-arg nil (funcall +workspaces-switch-project-function +workspaces--project-dir))) (run-hooks 'projectile-after-switch-project-hook) (setq +workspaces--project-dir nil)))))
  +workspaces-switch-to-project-h("~/Projects/histre/")
  ivy-call()
  ivy-read("[histre] Switch to project: " ("~/Projects/histre/" "~/.emacs.d/") :preselect "~/Projects/histre/" :action (1 ("o" +workspaces-switch-to-project-h "open project in new workspace") ("O" counsel-projectile-switch-project-action "jump to a project buffer or file") ("f" counsel-projectile-switch-project-action-find-file "jump to a project file") ("d" counsel-projectile-switch-project-action-find-dir "jump to a project directory") ("b" counsel-projectile-switch-project-action-switch-to-buffer "jump to a project buffer") ("m" counsel-projectile-switch-project-action-find-file-manually "find file manually from project root") ("w" counsel-projectile-switch-project-action-save-all-buffers "save all project buffers") ("k" counsel-projectile-switch-project-action-kill-buffers "kill all project buffers") ("r" counsel-projectile-switch-project-action-remove-known-project "remove project from known projects") ("c" counsel-projectile-switch-project-action-compile "run project compilation command") ("C" counsel-projectile-switch-project-action-configure "run project configure command") ("e" counsel-projectile-switch-project-action-edit-dir-locals "edit project dir-locals") ("v" counsel-projectile-switch-project-action-vc "open project in vc-dir / magit / monky") ("s" (lambda (project) (let ((projectile-switch-project-action (lambda nil ...))) (counsel-projectile-switch-project-by-name project))) "search project") ("xs" counsel-projectile-switch-project-action-run-shell "invoke shell from project root") ("xe" counsel-projectile-switch-project-action-run-eshell "invoke eshell from project root") ("xt" counsel-projectile-switch-project-action-run-term "invoke term from project root") ("X" counsel-projectile-switch-project-action-org-capture "org-capture into project")) :require-match t :sort nil :caller counsel-projectile-switch-project)
  counsel-projectile-switch-project()
  funcall-interactively(counsel-projectile-switch-project)
  call-interactively(counsel-projectile-switch-project nil nil)
  command-execute(counsel-projectile-switch-project)
</pre></details>

**Steps to reproduce:**
1. SPC p p
2. Choose any file
3. Press `Enter`

**System information:**
<details><pre>
((emacs
  (version . "27.0.50")
  (features . "XPM JPEG TIFF GIF PNG RSVG SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD PDUMPER LCMS2 GMP")
  (build . "Sep 04, 2019")
  (buildopts "--build=x86_64-linux-gnu --prefix=/usr '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' --sysconfdir=/etc --localstatedir=/var --disable-silent-rules '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' --disable-maintainer-mode --disable-dependency-tracking --prefix=/usr --sharedstatedir=/var/lib --program-suffix=-snapshot --with-modules=yes --with-x=yes --with-x-toolkit=gtk3 --with-xwidgets=yes 'CFLAGS=-g -O2 -fstack-protector-strong -Wformat -Werror=format-security' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro'")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop 69ce5d5 2020-07-26 02:59:05 -0400")
  (dir . "~/.doom.d/"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/bin/bash")
  (uname . "Linux 4.4.0-185-generic #215-Ubuntu SMP Mon Jun 8 21:53:19 UTC 2020 x86_64")
  (path "~/.poetry/bin" "~/.jenv/shims" "~/.jenv/bin" "~/.emacs.d/bin" "~/.poetry/bin" "~/opt/anaconda3/bin" "~/opt/anaconda3/condabin" "/usr/lib/dart/bin" "~/.local/bin" "~/opt/flutter/bin" "~/opt/android-studio/bin" "~/opt/idea/bin" "~/go/bin" "~/.sdkman/candidates/gradle/current/bin" "~/opt/google-cloud-sdk/bin" "~/.nvm/versions/node/v12.16.2/bin" "~/.poetry/bin" "/usr/local/sbin" "/usr/local/bin" "/usr/sbin" "/usr/bin" "/sbin" "/bin" "/usr/games" "/usr/local/games" "/snap/bin" "~/.rvm/bin" "~/.rvm/bin" "~/.pub-cache/bin" "~/.rvm/bin" "/usr/lib/x86_64-linux-gnu/emacs/27.0.50/x86_64-linux-gnu"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline ophints (popup +defaults) vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold snippets :emacs dired electric undo vc :checkers syntax :tools (eval +overlay) lookup magit :lang emacs-lisp markdown org sh :config (default +bindings +smartparens))
  (packages "n/a")
  (unpin "n/a")
  (elpa "n/a")))
</pre></details>

**Comment by hlissner** [comment]
Seems you're using an intermediate version of Emacs 27 before `setq-local` was made variadic. The simple solution would've been to upgrade to 27.0.90 (the release candidate). In any case, I've tweaked the version check to accommodate this, so I'll consider this resolved.

**Comment by kirubakaran** [comment]
Awesome, thank you so much!
