### ISSUE TITLE
Error on new installation: (void-variable magit-margin-settings)

### ISSUE THREAD

**Issue by rhstanton** [hlissner/doom-emacs#3636]
**What did you expect to happen?**

No error messages!

**What actually happened?**

I just installed Doom to try it out. It loads fine, but shortly thereafter starts giving me various error messages about not being able to load packages incrementally because  (void-variable magit-margin-settings)

**Additional details:**

This is a virgin install last night of Doom in emacs-mac-app on MacOS 10.15.6.

Here's some output from *Messages*:

```emacs
Loading /Users/stanton/doom-emacs/init.el (source)...done
Doom loaded 142 packages across 29 modules in 3.621s [2 times]
Failed to load magit package incrementally, because: (void-variable magit-margin-settings)
Failed to load org package incrementally, because: (void-variable magit-margin-settings)
Failed to load org-agenda package incrementally, because: (void-variable magit-margin-settings)
Failed to load org-capture package incrementally, because: (void-variable magit-margin-settings)
Failed to load org package incrementally, because: (void-variable magit-margin-settings)
```

**System information:**
<details><pre>
((emacs
  (version . "26.3")
  (features . "RSVG IMAGEMAGICK DBUS GLIB NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS XIM MODULES THREADS LCMS2")
  (build . "Jul 22, 2020")
  (buildopts "--prefix=/opt/local --with-mac --enable-mac-app=/Applications/MacPorts --with-modules --with-rsvg --with-imagemagick 'CFLAGS=-pipe -Os -fobjc-arc -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -arch x86_64' 'CPPFLAGS=-I/opt/local/include -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk' 'LDFLAGS=-L/opt/local/lib -Wl,-headerpad_max_install_names -Wl,-syslibroot,/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -arch x86_64'")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "grafted, HEAD -> develop, origin/develop, origin/HEAD 8dfe8840 2020-07-26 18:50:16 -0400")
  (dir . "~/.doom.d/"))
 (system
  (type . darwin)
  (config . "x86_64-apple-darwin19.6.0")
  (shell . "/bin/bash")
  (uname . "Darwin 19.6.0 Darwin Kernel Version 19.6.0: Sun Jul  5 00:43:10 PDT 2020; root:xnu-6153.141.1~9/RELEASE_X86_64 x86_64")
  (path "~/anaconda3/bin" "~/anaconda3/condabin" "~/packages/git-subrepo/lib" "." "/RHS/local/bin" "/RHS/local/openmpi/bin" "/opt/local/bin" "/opt/local/sbin" "/Applications/MacPorts/EmacsMac.app/Contents/MacOS" "/Applications/MacPorts/EmacsMac.app/Contents/MacOS/bin" "/Library/TeX/texbin" "~/anaconda3/bin" "/Applications/Stata/StataSE.app/Contents/MacOS" "/Applications/R.app/Contents/MacOS" "/Applications/Julia-0.5.app/Contents/Resources/julia/bin" "/Applications/MATLAB_R2017a.app/bin" "/usr/local/bin" "/usr/bin" "/bin" "/usr/sbin" "/sbin" "/Applications/VMware Fusion.app/Contents/Public" "/Library/TeX/texbin" "/opt/X11/bin" "/Library/Apple/usr/bin" "/Applications/MacPorts/EmacsMac.app/Contents/MacOS/libexec" "/Applications/MacPorts/EmacsMac.app/Contents/MacOS/bin"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline ophints (popup +defaults) vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold snippets :emacs dired electric undo vc :checkers syntax :tools (eval +overlay) lookup magit :lang emacs-lisp markdown org sh :config (default +bindings +smartparens))
  (packages "n/a")
  (unpin "n/a")
  (elpa "n/a")))
</pre></details>

**Comment by hlissner** [comment]
Does running `doom sync && doom build` fix the issue?

**Comment by rhstanton** [comment]
I commented out magit from the config file, then ran doom sync and noticed that some updating of magit seemed to take place. I then uncommented the package and ran doom sync again, and now the errors have gone away. I can’t say for sure which part of this solved it…!

**Comment by hlissner** [comment]
Seems like a byte-code issue, which `doom build` would've fixed, but reinstalling it is equivalent. In any case, I'll consider this resolved.
