### ISSUE TITLE
config.el is not being executed on emacsclient frames.

### ISSUE THREAD

**Issue by mmrezaie** [hlissner/doom-emacs#3639]
I have been using doom using daemon in Linux. After I found a solution to enable ESC to behave the same in terminal as in X11 I have realized that config.el is not being read when I open an emacsclient frame in the terminal. When I do “doom reload” the problem gets fixed and config.el gets executed line by line, but closing the frame and reopening the frame shows I have to re-run the config again.

One additional information is that I start the daemon using user systemd service.

**Comment by mmrezaie** [comment]
OK it just turned out only on the emacscleint frames this config.el is not being executed. When I open emacs in the terminal it is being executed and everything is fine.

**Comment by hlissner** [comment]
This can easily be tested. Add `(message "Hello")` to `~/.doom.d/config.el`, open Emacs, open \*Messages\* (`SPC h e` or `C-h e`) and see if a "Hello" appears in the log.

![image](https://user-images.githubusercontent.com/510883/88712998-9fc99600-d0e8-11ea-8c45-1b83528dd47e.png)

It works fine in vanilla Doom, so I suspect an issue in your elisp.

Since you did not follow the issue template I can't discern anything else about your situation. Please include your `M-x doom/info` and a link to your config (or at least the errant code you tried that didn't work). Please do not ignore the issue template in the future.

**Comment by mmrezaie** [comment]
This is the code:

`(defvar personal/fast-keyseq-timeout 200)

(defun personal/-tty-ESC-filter (map)
  (if (and (equal (this-single-command-keys) [?\e])
           (sit-for (/ personal/fast-keyseq-timeout 1000.0)))
      [escape] map))

(defun personal/-lookup-key (map key)
  (catch 'found
    (map-keymap (lambda (k b) (if (equal key k) (throw 'found b))) map)))

(defun personal/catch-tty-ESC ()
  "Setup key mappings of current terminal to turn a tty's ESC into `escape'."
  (when (memq (terminal-live-p (frame-terminal)) '(t pc))
    (let ((esc-binding (personal/-lookup-key input-decode-map ?\e)))
      (define-key input-decode-map
        [?\e] `(menu-item "" ,esc-binding :filter personal/-tty-ESC-filter)))))

(personal/catch-tty-ESC)
`


I tried to make the `personal/catch-tty-ESC` to be called when a new frame is being opened by emacsclient like this:

`(add-hook 'after-make-frame-functions 'personal/catch-tty-ESC)`

Unfortunately it won't work!

**Comment by hlissner** [comment]
> Unfortunately it won't work!

Likely because `personal/catch-tty-ESC` doesn't take an argument. To quote the documentation of `after-make-frame-function`:

> The functions are run with one argument, the newly created frame.

```diff
 (defvar personal/fast-keyseq-timeout 200)

 (defun personal/-tty-ESC-filter (map)
   (if (and (equal (this-single-command-keys) [?\e])
            (sit-for (/ personal/fast-keyseq-timeout 1000.0)))
       [escape] map))

 (defun personal/-lookup-key (map key)
   (catch 'found
     (map-keymap (lambda (k b) (if (equal key k) (throw 'found b))) map)))

 (defun personal/catch-tty-ESC (&optional frame)
   "Setup key mappings of current terminal to turn a tty's ESC into `escape'."
-  (when (memq (terminal-live-p (frame-terminal)) '(t pc))
+  (when (memq (terminal-live-p (or frame (selected-frame))) '(t pc))
     (let ((esc-binding (personal/-lookup-key input-decode-map ?\e)))
       (define-key input-decode-map
         [?\e] `(menu-item "" ,esc-binding :filter personal/-tty-ESC-filter)))))

-(personal/catch-tty-ESC)
+(add-hook 'after-make-frame-functions #'personal/catch-tty-ESC)

```

**Comment by mmrezaie** [comment]
Thank you very much.
