### ISSUE TITLE
Add color-identifiers-mode

### ISSUE THREAD

**Issue by innerout** [hlissner/doom-emacs#3642]
Color Identifiers is a minor mode for Emacs that highlights each source code identifier uniquely based on its name. I believe it is useful for long development sessions as it helps you spot bugs sometimes due to the color assignment on each variable.
I don't know if there are plugins in doom-emacs with similar functionality color-identifiers will replace.
Link to the plugin [color-identifiers-mode](https://github.com/ankurdave/color-identifiers-mode/tree/b399121b380a01054dd9cb3f4de310ad6c005156)

**Comment by hlissner** [comment]
Hi! Thanks for the request, but the plugin doesn't fit in any existing module, is not a reasonable default (for inclusion in Doom core), and doesn't need more than two lines of configuration, so there's nothing for Doom to do here. I'll leave it to users to set up themselves.
