### ISSUE TITLE
The 'doom upgrade' is not working, the `straight--byte-compile-package-p` is not defined.

### ISSUE THREAD

**Issue by mmajewsk** [hlissner/doom-emacs#3644]
**What did you expect to happen?**
That the doom will upgrade or sync.

**What actually happened?**
The doom upgrade command is hanging on rebuild, see details.

<details><pre>
WARNING Couldn’t find the :lang ox-gfm module
> Synchronizing your config with Doom Emacs...
  > Regenerating envvars file at "~/.emacs.d/.local/env"
    - Ignoring PWD=/home/mwm/.emacs.d
    - Ignoring SSH_AUTH_SOCK=/tmp/ssh-MU9l5qJvWstE/agent.2221
    - Ignoring TERM=xterm-256color
    - Ignoring DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
    - Ignoring HOME=/home/mwm
    - Ignoring SSH_AGENT_PID=2415
    ✓ Successfully generated "~/.emacs.d/.local/env"

DOOM Initializing package.el
DOOM Initializing straight.el
  > Installing packages...
    - No packages need to be installed
  > (Re)building packages...
x There was an unexpected error:
  Type: void-function
  Message:
    Symbol's function definition is void
  Data:
    straight--byte-compile-package-p

</pre></details>

**Steps to reproduce:**
1. Either just do `doom upgrade` or follow this instruction https://github.com/hlissner/doom-emacs/issues/2277#issuecomment-569858762 and do `doom sync`

**System information:**
<details><pre>
WARNING Couldn’t find the :lang ox-gfm module
((emacs
  (version . "26.3")
  (features . "XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD LCMS2")
  (build . "Sep 16, 2019")
  (buildopts "--build=x86_64-linux-gnu --prefix=/usr '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' --sysconfdir=/etc --localstatedir=/var --disable-silent-rules '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' --disable-maintainer-mode --disable-dependency-tracking --prefix=/usr --sharedstatedir=/var/lib --program-suffix=26 --with-modules --with-file-notification=inotify --with-mailutils --with-x=yes --with-x-toolkit=gtk3 --with-xwidgets --with-lcms2 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/emacs26-TP6iDo/emacs26-26.3~1.git96dd019=. -fstack-protector-strong -Wformat -Werror=format-security -no-pie' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro -no-pie'")
  (windowsys . batch)
  (daemonp))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD 9c1a356ad 2020-07-28 20:08:32 -0400")
  (dir . "~/.doom.d/"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/bin/bash")
  (uname . "Linux 5.3.0-40-generic #32~18.04.1-Ubuntu SMP Mon Feb 3 14:05:59 UTC 2020 x86_64")
  (path "~/.emacs.d/bin" "~/anaconda3/bin" "~/anaconda3/condabin" "~/.local/bin" "/usr/local/sbin" "/usr/local/bin" "/usr/sbin" "/usr/bin" "/sbin" "/bin" "/usr/games" "/usr/local/games" "/snap/bin" "/usr/lib/x86_64-linux-gnu/emacs/26.3/x86_64-linux-gnu"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company helm ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash neotree ophints (popup +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold multiple-cursors snippets :emacs dired electric vc :checkers syntax :tools direnv docker ein (eval +overlay) lookup magit make :lang cc data emacs-lisp latex markdown (org +dragndrop +present) sh :config (default +bindings +smartparens))
  (packages (cmake-ide) (elpy))
  (unpin "n/a")
  (elpa "spinner" "s" "pythonic" "python-environment" "ox-gfm" "ob-applescript" "markdown-mode" "lv" "lsp-python-ms" "lsp-mode" "latex-preview-pane" "jedi-core" "ht" "f" "epc" "deferred" "dash-functional" "dash" "ctable" "conda" "concurrent" "company-jedi" "company")))
</pre></details>

**Comment by hlissner** [comment]
Looks like you might be upgrading from a old version of straight. Try upgrading manually just this once:

```sh
cd ~/.emacs.d
git pull
doom sync -u
```

**Comment by mmajewsk** [comment]
> Looks like you might be upgrading from a old version of straight. Try upgrading manually just this once:
> 
> ```shell
> cd ~/.emacs.d
> git pull
> doom sync -u
> ```

The problem is still there.

```
(base) mwm@mwm-ThinkPad-X240:~$ cd ~/.emacs.d
(base) mwm@mwm-ThinkPad-X240:~/.emacs.d$ git pull
Already up to date.
(base) mwm@mwm-ThinkPad-X240:~/.emacs.d$ doom sync -u
WARNING Couldn’t find the :lang ox-gfm module
> Synchronizing your config with Doom Emacs...
  > Regenerating envvars file at "~/.emacs.d/.local/env"
    - Ignoring PWD=/home/mwm/.emacs.d
    - Ignoring SSH_AUTH_SOCK=/tmp/ssh-MU9l5qJvWstE/agent.2221
    - Ignoring TERM=xterm-256color
    - Ignoring DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
    - Ignoring HOME=/home/mwm
    - Ignoring SSH_AGENT_PID=2415
    ✓ Successfully generated "~/.emacs.d/.local/env"
  > Installing packages...
    - No packages need to be installed
  > (Re)building packages...
x There was an unexpected error:
  Type: void-function
  Message:
    Symbol's function definition is void
  Data:
    straight--byte-compile-package-p

Run the command again with the -d (or --debug) switch to enable debug
mode and (hopefully) generate a backtrace from this error:

  doom -d sync -u

If you file a bug report, please include it!

```

**Comment by mmajewsk** [comment]
I "nuked" the problem by reinstalling doom.
