### ISSUE TITLE
Expand region skips some levels of expanding

### ISSUE THREAD

**Issue by andyafter** [hlissner/doom-emacs#365]
When I expand region it always skips some region levels and go right up to the next level. Here is an example:

When I expand to the brackets of a if statement:
![screen shot 2018-01-18 at 11 16 06 am](https://user-images.githubusercontent.com/3354145/35079237-2f044010-fc41-11e7-8d67-38baafcdabf5.png)

if I expand again here is what will happen:

![screen shot 2018-01-18 at 11 16 19 am](https://user-images.githubusercontent.com/3354145/35079246-3a7e2730-fc41-11e7-942d-28ae6c3aad39.png)

And the same thing happen with the language specific expansion too. Example is go-guru-expand-region. Except it skips levels in a different behavior. 

I believe this has made the result of an expansion more unpredictable. Any idea about how I could fix this?

**Comment by hlissner** [comment]
Unfortunately, I don't think its possible to make it consistent, without some hefty effort. [expand-region](https://github.com/magnars/expand-region.el) has its own rules, even special ones for certain major modes. It doesn't appear to have specific integration with go-mode though.

Would it make sense to rebind `er/expand-region` to `go-guru-expand-region` in go-mode buffers, at least?

**Comment by andyafter** [comment]
Actually that's the interesting part. er/expand-region and go-guru-expand-region skips levels differently. go-guru-expand-region skips levels within a pair of quotes:
"here is something"
All content within quotes will be selected directly. 

I will take a look later.

**Comment by hlissner** [comment]
Since this isn't a Doom issue, I'll close this issue, but feel free to follow up on the discussion here. I'm open to any suggestions to make expand-region more predictable.
