### ISSUE TITLE
Error in a Doom startup hook: +workspaces-init-h, (void-function make-persp-internal)

### ISSUE THREAD

**Issue by Tepicurus** [hlissner/doom-emacs#3651]
Sorry Im a noob. Is above a common error? Thank you in advance!

**Comment by Tepicurus** [comment]
Sorry Im a noob. Is above a common error? Thank you in advance!

**Comment by hlissner** [comment]
No, it is not. There is no `make-persp-internal` function defined in the `persp-mode` package and Doom doesn't use that function anywhere, so I'm not sure what to make of this error.

**Comment by Tepicurus** [comment]
I reopened it properly as you asked. Thanks a lot
