### ISSUE TITLE
Cannot open load file: No such file or directory, dap-java

### ISSUE THREAD

**Issue by oakrc** [hlissner/doom-emacs#3657]
**What did you expect to happen?**
`lsp-install-server` shows a list of candidates

**What actually happened?**
"Cannot open load file: No such file or directory, dap-java"

**Additional details:**
- [Private config](https://github.com/oakrc/dotfiles/tree/master/.doom.d)
- Screenshot
![dap-java-err](https://user-images.githubusercontent.com/25710522/89009057-ac084b80-d2c0-11ea-916c-c7c67d589368.png)

**Backtrace:**
<details><pre>
Debugger entered--Lisp error: (file-missing "Cannot open load file" "No such file or directory" "dap-java")
  require(dap-java)
  mapc(require (dap-java))
  (closure ((module (:lang . java) lsp-java dap-java) (--dolist-tail-- ((:lang . java) lsp-java dap-java) ((:lang . php) php-mode dap-php) ((:lang . python) python dap-python) ((:lang . ruby) ruby-mode dap-ruby) ((:lang . rust) rust-mode dap-lldb)) t) nil (mapc #'require (cdr (cdr module))))()
  eval-after-load(lsp-java (closure ((module (:lang . java) lsp-java dap-java) (--dolist-tail-- ((:lang . java) lsp-java dap-java) ((:lang . php) php-mode dap-php) ((:lang . python) python dap-python) ((:lang . ruby) ruby-mode dap-ruby) ((:lang . rust) rust-mode dap-lldb)) t) nil (mapc #'require (cdr (cdr module)))))
  (progn (eval-after-load (nth 1 module) #'(lambda nil (mapc #'require (cdr (cdr module))))))
  (if (doom-module-p (car (car module)) (cdr (car module)) '+lsp) (progn (eval-after-load (nth 1 module) #'(lambda nil (mapc #'require (cdr (cdr module)))))))
  (let ((module (car --dolist-tail--))) (if (doom-module-p (car (car module)) (cdr (car module)) '+lsp) (progn (eval-after-load (nth 1 module) #'(lambda nil (mapc #'require (cdr ...)))))) (setq --dolist-tail-- (cdr --dolist-tail--)))
  (while --dolist-tail-- (let ((module (car --dolist-tail--))) (if (doom-module-p (car (car module)) (cdr (car module)) '+lsp) (progn (eval-after-load (nth 1 module) #'(lambda nil (mapc ... ...))))) (setq --dolist-tail-- (cdr --dolist-tail--))))
  (let ((--dolist-tail-- '(((:lang . cc) ccls dap-lldb dap-gdb-lldb) ((:lang . elixir) elixir-mode dap-elixir) ((:lang . go) go-mode dap-go) ((:lang . java) lsp-java dap-java) ((:lang . php) php-mode dap-php) ((:lang . python) python dap-python) ((:lang . ruby) ruby-mode dap-ruby) ((:lang . rust) rust-mode dap-lldb)))) (while --dolist-tail-- (let ((module (car --dolist-tail--))) (if (doom-module-p (car (car module)) (cdr (car module)) '+lsp) (progn (eval-after-load (nth 1 module) #'(lambda nil ...)))) (setq --dolist-tail-- (cdr --dolist-tail--)))))
  (progn (require 'dap-mode nil nil) (let ((--dolist-tail-- '(((:lang . cc) ccls dap-lldb dap-gdb-lldb) ((:lang . elixir) elixir-mode dap-elixir) ((:lang . go) go-mode dap-go) ((:lang . java) lsp-java dap-java) ((:lang . php) php-mode dap-php) ((:lang . python) python dap-python) ((:lang . ruby) ruby-mode dap-ruby) ((:lang . rust) rust-mode dap-lldb)))) (while --dolist-tail-- (let ((module (car --dolist-tail--))) (if (doom-module-p (car (car module)) (cdr (car module)) '+lsp) (progn (eval-after-load (nth 1 module) #'...))) (setq --dolist-tail-- (cdr --dolist-tail--))))) (if t (progn (progn (progn (if (featurep 'js2-mode) (progn (require ...) (require ...) (require ...) (if IS-WINDOWS ...)) (eval-after-load 'js2-mode #'...))) (progn (if (featurep 'typescript-mode) (progn (require ...) (require ...) (require ...) (if IS-WINDOWS ...)) (eval-after-load 'typescript-mode #'...)))))) (dap-mode 1) t (add-hook 'dap-mode-hook #'dap-tooltip-mode))
  (closure (t) nil (progn (require 'dap-mode nil nil) (let ((--dolist-tail-- '((... ccls dap-lldb dap-gdb-lldb) (... elixir-mode dap-elixir) (... go-mode dap-go) (... lsp-java dap-java) (... php-mode dap-php) (... python dap-python) (... ruby-mode dap-ruby) (... rust-mode dap-lldb)))) (while --dolist-tail-- (let ((module (car --dolist-tail--))) (if (doom-module-p (car ...) (cdr ...) '+lsp) (progn (eval-after-load ... ...))) (setq --dolist-tail-- (cdr --dolist-tail--))))) (if t (progn (progn (progn (if (featurep ...) (progn ... ... ... ...) (eval-after-load ... ...))) (progn (if (featurep ...) (progn ... ... ... ...) (eval-after-load ... ...)))))) (dap-mode 1) t (add-hook 'dap-mode-hook #'dap-tooltip-mode)))()
  eval-after-load-helper("/home/oak/.emacs.d/.local/straight/build/lsp-mode/...")
  run-hook-with-args(eval-after-load-helper "/home/oak/.emacs.d/.local/straight/build/lsp-mode/...")
  do-after-load-evaluation("/home/oak/.emacs.d/.local/straight/build/lsp-mode/...")
  #<subr autoload-do-load>((autoload "lsp-mode" nil t nil) lsp-install-server nil)
  apply(#<subr autoload-do-load> ((autoload "lsp-mode" nil t nil) lsp-install-server))
  autoload-do-load((autoload "lsp-mode" nil t nil) lsp-install-server)
  command-execute(lsp-install-server record)
  counsel-M-x-action("lsp-install-server")
  ivy-call()
  ivy-read("M-x " ("lsp-install-server" "dap-gdb-lldb-setup" "lsp-java-update-server" "=calendar" "comment-indent" "recover-this-file" "org-indent-mode" "org-change-tag-in-region" "conf-mode" "jupyter-server-list-kernels" "jupyter-server-launch-kernel" "phpactor-install-or-update" "lsp" "php-mode" "doom/retab" "org-clock-display" "ein:jupyter-server-start" "composer-setup-managed-phar" "lsp-mode" "doom/info" "html-mode" "json-mode" "org-refile" "php-mode-maybe" "composer-install" "jupyter-run-repl" "org-table-create" "+lsp/uninstall-server" "lsp-restart-workspace" "org-clock-update-time-maybe" "cd" "jb" "5x5" "amx" "arp" "dbx" "dig" "erc" "ert" "eww" "ftp" "gdb" "irc" "jdb" "man" "mpc" "orc" "orn" "oro" "orp" ...) :predicate #f(compiled-function (x) #<bytecode 0xa519f889926a0f>) :require-match t :history counsel-M-x-history :action counsel-M-x-action :keymap (keymap (67108908 . counsel--info-lookup-symbol) (67108910 . counsel-find-symbol)) :initial-input nil :caller counsel-M-x)
  counsel-M-x()
  funcall-interactively(counsel-M-x)
  call-interactively(counsel-M-x nil nil)
  command-execute(counsel-M-x)

</pre></details>

**Steps to reproduce:**
1. `git clone --depth 1 https://github.com/hlissner/doom-emacs ~/.emacs.d && cd ~/.emacs.d && bin/doom install`
2. Run `lsp-install-server`

**System information:**
<details><pre>
emacs   version    28.0.50
        features   XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP
        build      Jun 10, 2020
        buildopts  (--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --mandir=/usr/share/man --with-gameuser=:games --with-sound=alsa --with-modules --without-gconf --without-gsettings --with-x-toolkit=gtk3 --without-xaw3d --without-compress-install 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -flto' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now)
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop 4c1ad04e 2020-07-31 02:45:57 -0400
        dir        ~/.doom.d/
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /usr/bin/fish
        uname      Linux 5.7.10-arch1-1 #1 SMP PREEMPT Wed, 22 Jul 2020 19:57:42 +0000 x86_64
        path       (~/.emacs.d/bin/../bin ~/bin ~/bin /usr/local/sbin /usr/local/bin /usr/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl ~/.local/bin ~/.emacs.d/bin/ ~/.local/bin ~/.emacs.d/bin/ ~/.gem/ruby/2.7.0/bin /usr/lib/emacs/28.0.50/x86_64-pc-linux-gnu/)
config  envfile    envvar-file
        elc-files  0
        modules    (:input chinese japanese :completion company (ivy +fuzzy +icons) :ui deft doom doom-dashboard doom-quit hl-todo minimap modeline ophints (popup +all +defaults) pretty-code tabs treemacs unicode vc-gutter vi-tilde-fringe workspaces zen :editor (evil +everywhere) file-templates fold format multiple-cursors snippets :emacs (dired +icons) electric ibuffer undo vc :term eshell vterm :checkers syntax :tools (debugger +lsp) docker ein (eval +overlay) gist (lookup +dictionary +offline) lsp (magit +forge) (pass +auth) pdf rgb tmux :lang (cc +lsp) data emacs-lisp (json +lsp) (java +lsp) (javascript +lsp) (latex +cdlatex +fold +lsp) ledger (markdown +grip) (org +present +dragndrop +hugo +noter +dragndrop +journal +jupyter +roam +pomodoro) php (python +lsp +pyenv) qt rust (sh +lsp +fish) web yaml :app calendar irc :config (default +bindings +smartparens))
        packages   ((org-fancy-priorities) (origami) (indium) (org-roam-server) (ascii-art-to-unicode) (org-ref) (org-roam-bibtex) (ivy-bibtex) (parsebib :recipe (:files (*.el))) (nov) (mathpix.el :recipe (:host github :repo jethrokuan/mathpix.el)) (fish-mode) (systemd) (ssh-config-mode) (protobuf-mode) (calctex :recipe (:host github :repo johnbcoughlin/calctex :files (calctex-pkg.el org-calctex/*el calctex*/*el))) (org-tanglesync) (org-projectile) (powershell))
        unpin      (org-roam)
        elpa       (n/a)

</pre></details>

**Comment by hlissner** [comment]
Ah, `dap-java` was recently moved to `lsp-java`. As of 8b81c4c this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
