### ISSUE TITLE
Inserting dollar signs behaves differently on LaTeX files depending on whether file was opened from command line or inside emacs

### ISSUE THREAD

**Issue by quasisphere** [hlissner/doom-emacs#3658]
**What did you expect to happen?**
Opening file from command line or from inside emacs should both have working electric-math.

**What actually happened?**
If I open a LaTeX file using <SPC> f f, the automatic inserting of a second dollar upon pressing $ to enter math mode works.

If I open the same file by running "emacs <path_to_file.tex>" pressing $ only inserts one $ sign.

**Additional details:**
There is something weird going on with the TeX-electric-math variable.
In both cases the variable is nil, but if I perform a look up of the variable using `C-h v` on the session which was launched from command line, the $-sign behaviour starts to work the same way as on the other session. (Even though the variables still seem to be nil in both sessions!)

I also think that there might be other things broken with electric-math as well when opening a file from the terminal, but this is the simplest example.

**Steps to reproduce:**
1. Open a .tex file from command line > emacs test.tex.
2. Try to enter math mode by inserting $, no second $ is inserted.
4. Launch emacs again.
5. Open the file using `<SPC> f f test.tex`.
6. Enter math mode by inserting $, second $ is inserted automatically.

**System information:**
<details>

```
emacs   version    26.3
        features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2
        build      May 19, 2020
        buildopts  (--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-wide-int --with-modules 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now)
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop 8b81c4c72 2020-07-31 03:18:09 -0400
        dir        ~/.doom.d/
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /usr/bin/fish
        uname      Linux 5.7.10-arch1-1 #1 SMP PREEMPT Wed, 22 Jul 2020 19:57:42 +0000 x86_64
        path       (~/.emacs.d/bin/../bin ~/.gem/ruby/2.5.0/bin ~/context/tex/texmf-linux-64/bin ~/texlive/2020/bin/x86_64-linux ~/.emacs.d/bin /usr/local/sbin /usr/local/bin /usr/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /usr/lib/emacs/26.3/x86_64-pc-linux-gnu/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline ophints (popup +defaults) vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold snippets :emacs dired electric undo vc :checkers syntax :tools (eval +overlay) lookup magit pdf :lang cc emacs-lisp latex markdown (org +roam) rust sh :config (default +bindings +smartparens))
        packages   ((evil-escape :disable t))
        unpin      (n/a)
        elpa       (n/a)
```
</details>

**Comment by quasisphere** [comment]
Just a small comment - I think I now understand why TeX-electric-math is nil: This is probably intended as it seems like handling $'s is dedicated to smartparens-latex by lang/latex.

So perhaps for some reason smartparens-latex is not loaded when launching from command line. Still don't know what to think of `C-h v TeX-electric-math` fixing the behavior though.. it must trigger some hook I guess.

**Comment by iyefrat** [comment]
i can't reproduce this, is this still an issue on the latest version?

**Comment by quasisphere** [comment]
I can't reproduce this anymore either. I think it has been fixed at some point, so I'm closing this.
