### ISSUE TITLE
previous-buffer does not go to previous buffer

### ISSUE THREAD

**Issue by drcassar** [hlissner/doom-emacs#3664]
**What did you expect to happen?**
Create a directory with two files: a.txt and b.txt. Now open a.txt with emacs. Run the function 'counsel-find-file' (SPC .) and open b.txt. Now run the function previous-buffer (SPC b p). The file b.txt is still opened in the current buffer, not a.txt.

**What actually happened?**
I expected that the current buffer would change back to a.txt which was the previous buffer that I opened. This problem only happens with the very first file opened. If you also have a c.txt file and open it, then previous-buffer goes back to b.txt like I would expect.

**Additional details:**
Updated doom emacs yesterday and tested today.

**Steps to reproduce:**
1. Create a directory with 3 empty files: a.txt, b.txt, and c.txt.
2. Open a.txt with doom emacs.
3. Type 'SPC .' and open b.txt.
4. Type 'SPC b p' and observe that nothing happens
5. Type 'SPC .' and open c.txt.
6. Type 'SPC b p' and observe that you are back to file b.txt, which is the expected behavior.

**System information:**
<details><pre>
<details>

```
emacs   version    26.3
        features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2
        build      May 19, 2020
        buildopts  (--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-wide-int --with-modules 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now)
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      grafted, HEAD -> develop, origin/develop, origin/HEAD 16acf1a 2020-07-31 16:25:45 -0400
        dir        /data/Software/Config/stow_symbolic/doomemacs/.doom.d/
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/bash
        uname      Linux 5.7.7-arch1-1 #1 SMP PREEMPT Wed, 01 Jul 2020 14:53:16 +0000 x86_64
        path       (/usr/local/sbin /usr/local/bin /usr/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /usr/lib/emacs/26.3/x86_64-pc-linux-gnu/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo indent-guides modeline nav-flash ophints (popup +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold (format +onsave) multiple-cursors rotate-text snippets :emacs dired electric ibuffer vc :checkers syntax :tools ein (eval +overlay) (lookup +docsets) magit :lang data emacs-lisp latex markdown (org +dragndrop +brain +jupyter +pandoc +present) python sh :config (default +bindings +smartparens))
        packages   ((virtualenvwrapper) (py-yapf) (org-drill))
        unpin      (n/a)
        elpa       (n/a)
```
</details>

</pre></details>

**Comment by hlissner** [comment]
I cannot reproduce this.

1. Open Emacs
2. `SPC . a.txt`
3. `SPC . b.txt`
4. `SPC b p` switches to a.txt
5. `SPC . c.txt`
6. `SPC b p` switches to a.txt

This is on vanilla Doom (Doom with no provide config). Tested on Emacs 26.3, 27.1, 28.0.50, on Nix, Arch and Mojave.

Please check your private config. Or try to reproduce it [in Doom's sandbox](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#testing-in-dooms-sandbox).

**Comment by drcassar** [comment]
It is surely something on my end, tried with doom's sandbox and got the expected result. Thanks for your patience and sorry for adding unecessary noise to the issue tracker. Didn't know about doom's sandbox, awesome stuff!!
