### ISSUE TITLE
Support emacs HEAD

### ISSUE THREAD

**Issue by robbyoconnor** [hlissner/doom-emacs#3667]
**Describe the feature**
I'm not sure where to place this. Spacemacs has always supported Emacs HEAD and it'd be cool if Doom did as well. 

**System information**
<details><pre>
((emacs
  (version . "28.0.50")
  (features . "XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER LCMS2")
  (build . "Jul 31, 2020")
  (buildopts "--build=x86_64-linux-gnu --prefix=/usr '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' --sysconfdir=/etc --localstatedir=/var --disable-silent-rules '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' --disable-maintainer-mode --disable-dependency-tracking --prefix=/usr --sharedstatedir=/var/lib --program-suffix=-snapshot --with-modules=yes --with-x=yes --with-x-toolkit=gtk3 --with-xwidgets=yes 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/emacs-snapshot-nmh7eY/emacs-snapshot-100730=. -fstack-protector-strong -Wformat -Werror=format-security' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro'")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop e07cc77c1 2020-07-31 18:18:07 -0400")
  (dir . "~/.doom.d/"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/bin/zsh")
  (uname . "Linux 5.4.0-40-generic #44-Ubuntu SMP Tue Jun 23 00:01:04 UTC 2020 x86_64")
  (path "~/.nvm/versions/node/v12.17.0/bin" "~/.yarn/bin" "~/.config/yarn/global/node_modules/.bin" "/usr/local/bin" "/usr/local/sbin" "~/.rbenv/shims" "~/.rbenv//bin" "~/.goenv/shims" "~/.goenv/bin" "~/.pyenv/plugins/pyenv-virtualenv/shims" "~/.pyenv/shims" "~/.pyenv/bin" "~/.linuxbrew/bin" "~/.config/guix/current/bin" "~/.evm/bin" "~/.cask/bin" "/bin" "~/gocode/bin" "~/.nvm/versions/node/v12.17.0/bin" "~/android_tools/platform-tools" "~/.cabal/bin" "~/bin" "~" "/opt/chefdk/bin" "~/.yarn/bin" "~/.config/yarn/global/node_modules/.bin" "~/.rbenv/bin" "~/.local/bin" "~/QEMU/bin/" "/usr/sbin" "/usr/bin" "/sbin" "/usr/games" "/usr/local/games" "/snap/bin" "/usr/lib/jvm/java-8-oracle/bin" "/usr/lib/jvm/java-8-oracle/db/bin" "/usr/lib/jvm/java-8-oracle/jre/bin" "~/.rvm/bin" "~/bin/" "~/.cljr/bin/" "~/Android/Sdk/build-tools/25.0.0" "~/.cargo/bin" "~/scala-2.11.8/bin/" "/opt/vuze" "~/Android/Sdk/platform-tools" "/opt/apache-maven-3.5.0/bin" "/opt/acbuild-v0.4.0/" "~/doom-emacs/bin" "/usr/lib/x86_64-linux-gnu/emacs/28.0.50/x86_64-linux-gnu"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company ido ivy :ui deft doom doom-dashboard doom-quit fill-column hl-todo hydra indent-guides minimap modeline nav-flash ophints (popup +defaults) pretty-code treemacs unicode vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold (format +onsave) lispy multiple-cursors parinfer rotate-text snippets word-wrap :emacs dired electric ibuffer undo vc :term eshell shell term vterm :checkers syntax spell grammar :tools ansible debugger direnv docker editorconfig ein (eval +overlay) gist lookup lsp macos magit make pass pdf prodigy rgb taskrunner terraform tmux upload :lang cc clojure common-lisp coq crystal data (dart +flutter) emacs-lisp ess (go +lsp) (haskell +dante) idris json javascript kotlin latex lean ledger lua markdown nim org php plantuml python qt racket raku rest rst (ruby +rails) rust scala scheme sh sml terra web yaml :email (mu4e +gmail) notmuch (wanderlust +gmail) :app calendar irc (rss +org) twitter :config literate (default +bindings +smartparens))
  (packages "n/a")
  (unpin "n/a")
  (elpa "undo-tree" "goto-chg" "evil")))

</pre></details>

**Comment by hlissner** [comment]
Emacs HEAD should _generally_ work with Doom, but it's too much of a moving target; one week it'll work, the next it won't. Once we drop 26.x support (which won't happen until 27.1 is released, and has become reasonably ubiquitous across various package managers), I'll support 28.x, but until then I'm sorry to say simply cannot afford to.

**Comment by robbyoconnor** [comment]
Alrighty, no issue
