### ISSUE TITLE
How can I have ESC and evil mode to behave the same in terminal and X11, emacsclient frames

### ISSUE THREAD

**Issue by mmrezaie** [hlissner/doom-emacs#3675]
I have been using emacs daemon for a long time (as a systemd). Normally I start the daemon and an instance of x11 emacs. In my doom config I do have this line too:

```
(use-package server
  :config
  (unless (server-running-p) (server-start)))
```
Now the problem is when I open emacsclient frame in terminal, evil mode won't switch using 'ESC' key. I found a solution somewhere and it was working for me when I was opening emacs instance on terminal but not as an emacsclient frame. This solution works when emacs starts at terminal but not with emacsclient frame connecting to emacs daemon started before.

```
(defvar personal/fast-keyseq-timeout 200)

(defun personal/-tty-ESC-filter (map)
  (if (and (equal (this-single-command-keys) [?\e])
           (sit-for (/ personal/fast-keyseq-timeout 1000.0)))
      [escape] map))

(defun personal/-lookup-key (map key)
  (catch 'found
    (map-keymap (lambda (k b) (if (equal key k) (throw 'found b))) map)))

(defun personal/catch-tty-ESC (&optional frame)
  "Setup key mappings of current terminal to turn a tty's ESC into `escape'."
  (when (memq (terminal-live-p (or frame (selected-frame))) '(t pc))
    (let ((esc-binding (personal/-lookup-key input-decode-map ?\e)))
      (define-key input-decode-map
        [?\e] `(menu-item "" ,esc-binding :filter personal/-tty-ESC-filter)))))

(personal/catch-tty-ESC)
```

I was doing this to fix the issue but it doesn't work:

`(add-hook 'after-make-frame-functions #'personal/catch-tty-ESC)
`

To be sure I can execute 'personal/catch-tty-ESC' function manually and then 'ESC' key works on terminal.

How can I fix this?
Or, is there another way to get my 'ESC' back in terminal with emacsclient frames?

**Comment by mmrezaie** [comment]
I should mention that I opened a separate ticket similar to this (and I am grateful for the answers) but since I explained the question in a very bad way I decided to redo it and maybe this time a solution will come up and others can benefit from finding it through searching.

**Comment by jgoerzen** [comment]
I also use emacsclient, but have no supporting configuration in emacs itself.  Just this script:

```#!/bin/bash
exec emacsclient -c -a "" "$@"
```

which I have named "em".  I launch emacs with "em" and it just works, with both terminal and X11 sessions.  ESC works fine in both for me.  Just FWIW.

**Comment by mmrezaie** [comment]
I do the same and when for the first time this command is issued then an emacs server starts because of my configs, which also calls the functiosn I need.

The problem rises when I close the frame and open another one with the same command. But the new frame on the new terminal won't have that function being called (personal/catch-tty-ESC). Since it was supposed to be called with emacs init, and not the frame hook. But the frame's hook function never gets called. According to the documentation it should!
