### ISSUE TITLE
Prefixed actions are very slow

### ISSUE THREAD

**Issue by skosch** [hlissner/doom-emacs#3679]
**What did you expect to happen?**
Prefixed actions (is that the right term?) like `g g`, `z z`, `z a`, etc. are executed immediately.

**What actually happened?**
When I type e.g. `g g` to return to the top of a file, the first `g` first opens the minibuffer listing possible evil actions starting with `g`. This takes ~5 seconds. Only then is the second `g` processed, and the action executed.

I am ok with there being a delay before the minibuffer is shown, but if I type `g g` fast I just want that action to run instantly.

Similarly, actions like `SPC ,` take just a little bit too long (although it's not quite as bad as `g g` and `z z`).

**Additional details:**
My config includes 
```
(setq which-key-idle-delay 0.1)
(setq which-key-idle-secondary-delay 0.1)
```
Which I've come across in threads like #1317 and others, but adding/changing those lines doesn't help. My config is pretty vanilla otherwise (just some theming and indentation settings).

Profiler output after navigating to the end of a file and hitting `g g`:
![image](https://user-images.githubusercontent.com/554383/89210606-41cc0100-d575-11ea-9882-029e247cfebb.png)

There are no warnings or other problems anywhere, and I see no correlation with modes or file sizes.

I'm happy to help debug this in whatever way I can, I just don't know where to start. Thank you for this incredible project!

**System information:**
<details>

```
emacs   version    26.3
        features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD LCMS2
        build      Sep 16, 2019
        buildopts  (--build=x86_64-linux-gnu --prefix=/usr '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' --sysconfdir=/etc --localstatedir=/var --disable-silent-rules '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' --disable-maintainer-mode --disable-dependency-tracking --prefix=/usr --sharedstatedir=/var/lib --program-suffix=26 --with-modules --with-file-notification=inotify --with-mailutils --with-x=yes --with-x-toolkit=gtk3 --with-xwidgets --with-lcms2 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/emacs26-TP6iDo/emacs26-26.3~1.git96dd019=. -fstack-protector-strong -Wformat -Werror=format-security -no-pie' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro -no-pie')
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop 847bbf380 2020-06-13 17:12:23 -0400
        dir        ~/.doom.d/
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/zsh
        uname      Linux 5.6.2-050602-generic #202004020822 SMP Thu Apr 2 12:25:59 UTC 2020 x86_64
        path       (~/.nvm/versions/node/v12.13.1/bin ~/.local/kitty.app/bin ~/.local/bin /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /usr/games /usr/local/games /snap/bin ~/.fzf/bin /usr/lib/x86_64-linux-gnu/emacs/26.3/x86_64-linux-gnu/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold multiple-cursors rotate-text snippets :emacs dired electric ibuffer vc :tools (eval +overlay) :checkers syntax :tools (lookup +docsets) magit :lang data emacs-lisp markdown (org +dragndrop +ipython +pandoc +roam +present) sh :config (default +bindings +smartparens))
        packages   (n/a)
        unpin      (n/a)
        elpa       (zzz-to-char zygospore zprint-mode web-mode typescript-mode tide spinner s reason-mode prettier-js popup pkg-info org-roam org-plus-contrib org opencl-mode markdown-mode lv lsp-mode ht flycheck-elixir flycheck f epl emacsql-sqlite emacsql elixir-mode dash-functional dash company-org-roam company caml ayu-theme avy auto-complete alchemist ac-alchemist)
```
</details>

**Comment by hlissner** [comment]
> (setq which-key-idle-delay 0.1)
> (setq which-key-idle-secondary-delay 0.1)

This is only expected with delays so low. Their default is `1.0` for a reason. Increase it, and it won't trigger so quickly that you can't even type trivial key sequences without invoking it.

**Comment by skosch** [comment]
Thank you Henrik!
Hmm – this does help, but now it takes even longer for the minibuffer to come up when I do need it. Is there a reason it takes so long to load? Ideally, I do want it to pop up after a few hundred milliseconds at most, but still not block further input in the meantime. Anything I can do to speed it up?

**Comment by hlissner** [comment]
I'm surprised that it takes so long. Does it happen only the first time you invoke which-key, or every time? 

If it's the former, that's the delay of which-key loading for the first time. You _could_ get around that by loading which-key more aggressively for a small startup cost, e.g.

```elisp
;; in ~/.doom.d/config.el
(require 'which-key)
```

If the latter, then that is unusual. I see you're on a two-month old version of Doom. There were some optimizations both to Doom and to which-key (upstream) that may help out. Try upgrading (by running `doom upgrade` on the command line).

**Comment by skosch** [comment]
Thank you. It happens every time, and pre-requiring which-key beforehand didn't make a difference; neither did upgrading and reloading. What did help in the end was restarting emacs. Is it possible that after weeks of usage, something somewhere (?) accumulates that ends up slowing things down?

**Comment by hlissner** [comment]
> What did help in the end was restarting emacs. Is it possible that after weeks of usage, something somewhere (?) accumulates that ends up slowing things down?

Yes. Definitely. Memory usage, background buffers, more elisp loaded in memory -- unless you're extra careful to keep Emacs tidy every day it is generally unwise to keep it open for so long. In any case, I'll consider this resolved.
