### ISSUE TITLE
evil-repeat-keys doesn't work with evil-snipe disabled

### ISSUE THREAD

**Issue by fermata101** [hlissner/doom-emacs#3689]
**What did you expect to happen?**
Normal vim behavior would be for ";" to repeat a find (f) action and "n" to repeat a search.  It looks like the intent of Doom's +evil-repeat-keys code is for ";" to repeat whichever was the last one.

**What actually happened?**
After doing a search with "/" and then a find with "f", ";" just repeated the search, regardless of the use of "f".  

**Additional details:**
I disabled the evil-snipe package, so the set-repeater! code for evil-snipe-f (in modules/editor/evil/config.el) is never run.  The repeater setup code should probably check if snipe is disabled and if so, call set-repeater! on evil-find-char/evil-find-char-backward instead.

For now, I am doing (setq +evil-repeat-keys nil) in my private config to disable the repeater keys.

**Steps to reproduce:**
1. Make sure the evil-snipe package is disabled
2. Perform a search with "/"
3. Find a char with "f"
4. Use ";", which will repeat the search from step 2 instead of the find from step 3.

**System information:**
<details><pre>
WARNING (:lang perl) module was moved to (:lang raku)
((emacs
  (version . "26.3")
  (features . "XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2")
  (build . "May 19, 2020")
  (buildopts "--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-wide-int --with-modules 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop 46d6d0b58 2020-06-29 15:12:30 -0400")
  (dir . "~/config_share/doom/"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/bin/bash")
  (uname . "Linux 5.7.8-arch1-1 #1 SMP PREEMPT Thu, 09 Jul 2020 16:34:01 +0000 x86_64")
  (path "~/bin" "~/.cabal/bin" "~/.ghcup/bin" "~/.cargo/bin" "~/go/bin" "/usr/local/sbin" "/usr/local/bin" "/usr/bin" "/usr/lib/jvm/default/bin" "/usr/bin/site_perl" "/usr/bin/vendor_perl" "/usr/bin/core_perl" "/usr/lib/emacs/26.3/x86_64-pc-linux-gnu"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company (ivy +prescient) :ui deft doom doom-dashboard doom-quit hl-todo modeline ophints (popup +defaults) treemacs vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold multiple-cursors snippets word-wrap :emacs dired electric ibuffer undo vc :term vterm :checkers syntax :tools debugger editorconfig (eval +overlay) lookup lsp magit upload :lang cc clojure common-lisp data elixir elm emacs-lisp erlang (go +lsp) (haskell +lsp +dante) json javascript latex lua markdown nix ocaml org raku python racket (ruby +rails) (rust +lsp) scala scheme sh sml web yaml :config (default +bindings +smartparens))
  (packages (evil-easymotion :disable t) (evil-snipe :disable t) (rustic :disable t) (rust-mode) (flycheck-rust) (lsp-treemacs) (company-lsp) (ace-jump-mode))
  (unpin "n/a")
  (elpa "n/a")))
</pre></details>

**Comment by hlissner** [comment]
> I disabled the evil-snipe package, so the set-repeater! code for evil-snipe-f (in modules/editor/evil/config.el) is never run.

evil-snipe and `set-repeater!` are not related. I've intentionally reworked `;` and `,` to repeat any motion. To disable this:

```elisp
(setq +evil-repeat-keys nil)
```

**Comment by fermata101** [comment]
Right, it's not directly related to evil-snipe, it's just that the repeater setup is getting done for evil-snipe, but is not getting done for the standard find command.  The problem is that there is no call to ```set-repeater!``` for the ```evil-find-char``` function.  So once the search command has mapped the ```;``` key to ```evil-ex-search-next```, the ```f``` command will not map it back to ```evil-repeat-find-char```.  (The setup code is present for evil-snipe's ```f``` command (in the ```after! evil-snipe``` block in evil/config.el), so you will not see the issue if you have evil-snipe enabled.

I tried adding calls to ```set-repeater!``` for evil-find-char, as follows, but it didn't seem to fix it.
```
(set-repeater! evil-find-char evil-repeat-find-char evil-repeat-find-char-reverse)
(set-repeater! evil-find-char-backward evil-repeat-find-char evil-repeat-find-char-reverse)
(set-repeater! evil-find-char-to evil-repeat-find-char evil-repeat-find-char-reverse)
(set-repeater! evil-find-char-to-backward evil-repeat-find-char evil-repeat-find-char-reverse)
```

**Comment by hlissner** [comment]
Ah, my bad, I see what you mean now. I'll look into it.

**Comment by hlissner** [comment]
I've decided to do away with the universal repeater in 77fbde9, since it wasn't especially useful, and was a source of confusion for vim users. In any case, this should indirectly resolve your issue. Thanks for bringing it to my attention!
