### ISSUE TITLE
+magit/quit forcing all major mode hooks to run again

### ISSUE THREAD

**Issue by prati0100** [hlissner/doom-emacs#3691]
Hi,

I use LSP mode on my C buffers. I have added a major mode hook that enables LSP mode for all C buffers. Now when I open the magit status buffer, do something, and press q (which maps to `+magit/quit`), it triggers all the major mode hooks to run again, including my LSP mode hook. This takes almost a second to re-run all the hooks and Emacs is frozen for that period.

If I instead use `kill-current-buffer` on the magit status buffer, none of this happens and I return to my C mode buffer instantly with everything fine. The downside is that all the other magit buffers that were created are left there.

Is there any way to avoid re-running all the hooks on a buffer? I am fairly new to Emacs and Elisp so I can't figure out a fix myself. I can of course bind q to `kill-current-buffer` for all magit mode buffers but I suspect I would lose out on some optimization somewhere.

My setup:
M-x magit-version: Magit 0746bf1bacfe896d3917ccc19c7fb9d95c18b1e9, Git 2.28.0, Emacs 26.3, gnu/linux
M-x doom/info:
<details>

```
emacs   version    26.3
        features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2
        build      May 19, 2020
        buildopts  (--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-wide-int --with-modules 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now)
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop, origin/develop, origin/HEAD afcf56a61 2020-07-24 19:27:50 -0400
        dir        ~/src/dotfiles/.doom.d/
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/zsh
        uname      Linux 5.7.11-arch1-1 #1 SMP PREEMPT Wed, 29 Jul 2020 21:38:21 +0000 x86_64
        path       (/usr/local/bin /usr/bin /bin /usr/local/sbin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /usr/lib/emacs/26.3/x86_64-pc-linux-gnu/)
config  envfile    envvar-file
        elc-files  156
        modules    (:completion company helm ivy :ui doom doom-dashboard fill-column hl-todo modeline ophints (popup +defaults) vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold snippets :emacs dired electric ibuffer undo vc :checkers syntax spell grammar :tools (eval +overlay) lookup lsp magit :lang (cc +lsp) data emacs-lisp json javascript latex lua markdown nix org php python rst rust sh yaml :email notmuch :config (default +bindings +smartparens))
        packages   ((cquery) (ripgrep) (dts-mode) (kconfig-mode))
        unpin      (n/a)
        elpa       (n/a)
```
</details>

**Comment by hlissner** [comment]
> I have added a major mode hook that enables LSP mode for all C buffers.

This sounds like you've added your own hooks. If this is so, please remove them. By enabling the `:lang (cc +lsp)` module (which you have), Doom adds its own LSP specialized hook which won't restart the LSP server if `lsp-mode` is already enabled.

**Comment by hlissner** [comment]
> 2020-07-24

Ah, it appears you're on a 2-week old version of Doom as well. The "specialized hook" I mentioned were a recent addition (7784c0b6e -- 3 days ago). You'll need to update.

**Comment by prati0100** [comment]
I ran the profile and it looks like almost 75% of the time is spent in the hook `hl-fill-column-mode`. Disabling it gives a visible speed improvement. It still is not instant, but much faster than before, so thanks for the tip.

Now 51% of the time is spent in `magit-mark-stale-buffers-h`. 46% of total time is spent in the subroutine `doom--optimize-for-large-files-a`. 26% of total time is spent in `normal-mode` and 20 % in `run-hooks`. Only 3% of the time is spent in enabling LSP so yes, it is pretty fast.

This is a significant improvement, but I'd still like to make it faster if possible. I can live without `hl-fill-column-mode`, so I have disabled it for now. I think Emacs 27 will add support for a ruler so I won't have to wait long. Is there anything else I can do to speed things up?

BTW, is there a way I can copy the whole report without having to hit `TAB` on each heading to expand it? I wanted to paste the entire thing here but there are too many subsections to expand.

**Comment by hlissner** [comment]
How many windows do you have open when you invoke `+magit/quit`? The way it works is: it refreshes the visible windows, and waits on refreshing the rest of your buffers until you switch to them (one at a time). I can only imagine it taking so much time if you have, like, 10 windows open or something.

Unfortunately, when you revert a buffer it restarts the major mode, which means all the hooks on `MAJOR-MODE-hook` get run (like hl-fill-column-mode). I'll see if I can figure out a way to bypass that.

> BTW, is there a way I can copy the whole report without having to hit TAB on each heading to expand it? I wanted to paste the entire thing here but there are too many subsections to expand.

The column width can be tweaked (from their default of 50/55):

```elisp
(after! profiler
  (setf (caar profiler-report-cpu-line-format) 80
        (caar profiler-report-memory-line-format) 80))
```

Which I'll make the default soon.

Otherwise, there's no easy way I'm afraid.

**Comment by hlissner** [comment]
Could you also break down what in `doom--optimize-for-large-files-a` it's spending time on?

**Comment by prati0100** [comment]
> How many windows do you have open when you invoke `+magit/quit`? The way it works is: it refreshes the visible windows, and waits on refreshing the rest of your buffers until you switch to them (one at a time). I can only imagine it taking so much time if you have, like, 10 windows open or something.

I have either 1 or 2 windows open at any time. Rarely ever more than 2. I do have multiple workspaces open at a time, maybe 3-4. But they shouldn't count as visible I think.

> Could you also break down what in `doom--optimize-for-large-files-a` it's spending time on?

The breakdown is pasted below. This time it only took 23% but it should give you a fair idea.

```
- command-execute                                                 107  42%
 - call-interactively                                             107  42%
  - funcall-interactively                                         107  42%
   - +magit/quit                                                   66  26%
    - +magit-mark-stale-buffers-h                                  66  26%
     - +magit--revert-buffer                                       66  26%
      - revert-buffer                                              66  26%
       - revert-buffer--default                                    66  26%
        - after-find-file                                          59  23%
         - apply                                                   59  23%
          - #<compiled 0x4cbfc9>                                   59  23%
           - apply                                                 59  23%
            - #<compiled 0x4ca7b5>                                 59  23%
             - apply                                               59  23%
              - doom--optimize-for-large-files-a                   59  23%
               - apply                                             59  23%
                - #<compiled 0x1b6a7f>                             59  23%
                 - normal-mode                                     36  14%
                  - set-auto-mode                                  33  13%
                   - apply                                         33  13%
                    - #<compiled 0x1788931>                        30  12%
                     - apply                                       30  12%
                      - so-long--set-auto-mode                     30  12%
                       - apply                                     30  12%
                        - #<compiled 0x1b725b>                     30  12%
                         - set-auto-mode-0                         27  10%
                          - c-mode                                 27  10%
                           - run-mode-hooks                        24   9%
                            - apply                                13   5%
                             - run-hooks                           13   5%
                              + doom-detect-indentation-h                 10   4%
                              + my-enable-lsp                       3   1%
                            - hack-local-variables                 10   4%
                             - apply                               10   4%
                              + so-long--hack-local-variables                 10   4%
                            + run-hooks                             1   0%
                           + c-common-init                          3   1%
                           inhibit-local-variables-p                  3   1%
                    + auto-minor-mode-set                           3   1%
                  + run-hooks                                       3   1%
                 - run-hooks                                       23   9%
                  + save-place-find-file-hook                      17   6%
                  + undo-fu-session-recover-safe                    3   1%
                  + projectile-find-file-hook-function                  3   1%
          revert-buffer-insert-file-contents--default-function                  4   1%
        + run-hooks                                                 3   1%
   + doom/toggle-profiler                                          41  16%
```

**Comment by hlissner** [comment]
> including my LSP mode hook
> my-enable-lsp 

What is this `my-enable-lsp` hook? Doom should be activating LSP for you (on `c-mode-local-vars-hook`) in a more efficient manner. If you have it on a mode hook it may explain why you're seeing LSP-related slowness when reverting.
