### ISSUE TITLE
Orgmode: Archive showing it's content on buffer open

### ISSUE THREAD

**Issue by helderburato** [hlissner/doom-emacs#3693]
### What is expected

When open the `.org` files it keeps the `archive` hidden by default

### What's happening

1. When opening a `todo.org` it shows all internal archives expanded; 
2. I'm in doubt if it's a feature from orgmode or If it's DOOM;
3. I'm using the `org-archive-to-archive-sibbling` option to archive;

---

### Additional details:

<details>

```elisp
(after! org
  :config
  (setq org-log-done 'time)
  (setq org-clock-persist 'history)
  (setq org-directory "~/org/")
  (setq org-log-into-drawer t)

  (setq org-todo-keywords
    '((sequence "TODO(t)" "INPROGRESS(i!)" "HOLD(h@/!)" "|" "DONE(d!)" "CANCELLED(c@/!)"))
    org-todo-keyword-faces
    '(("TODO" :foreground "#8be9fd" :weight normal :underline t)
       ("INPROGRESS" :foreground "#bd93f9" :weight normal :underline t)
       ("HOLD" :foreground "#f1fa8c" :weight normal :underline t)
       ("DONE" :foreground "#50fa7b" :weight normal :underline t)
       ("CANCELLED" :foreground "#ff5555" :weight normal :underline t)))

  (setq org-capture-templates
    '(
       ("n" "Note" entry (file +org-capture-notes-file)
         "* %^{DESCRIPTION} \n%?\nEntered on %U\n  %i\n  %a")
       ("t" "Todo" entry (file+olp+datetree +org-capture-todo-file "Inbox")
         "* TODO %?\n  %i\n  %a")
       ("s" "Snippet" entry (file "snippets.org")
         "* %^{DESCRIPTION} %^g \n#+begin_src %^{LANG}\n%?%i\n#+end_src")
       ("c" "Changelog" entry (file+headline +org-capture-project-changelog-file "Unreleased")
         "* %U %?\n%i\n%a")
       ("j" "Journal" entry (file+olp+datetree +org-capture-journal-file)
         "* %U %?\n%i\n%a" :prepend t))
    ))

```
</details>

### System Version

<details>

```
emacs   version    28.0.50
        features   JPEG TIFF PNG RSVG IMAGEMAGICK GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS PDUMPER LCMS2
        build      Jul 30, 2020
        buildopts  (--disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus@28/28.0.50/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus@28/28.0.50 --with-xml2 --with-gnutls --without-dbus --with-imagemagick --with-modules --with-rsvg --with-ns --disable-ns-self-contained)
        windowsys  ns
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop 01c5c356 2020-08-04 18:04:15 -0400
        dir        ~/.dotfiles/emacs/.doom.d/
system  type       darwin
        config     x86_64-apple-darwin19.6.0
        shell      /usr/local/bin/zsh
        uname      Darwin 19.6.0 Darwin Kernel Version 19.6.0: Sun Jul  5 00:43:10 PDT 2020; root:xnu-6153.141.1~9/RELEASE_X86_64 x86_64
        path       (~/.emacs.d/bin/../bin ~/.nvm/versions/node/v12.18.3/bin /usr/local/sbin ~/bin /usr/local/bin ~/.emacs.d/bin /usr/bin /bin /usr/sbin /sbin /usr/local/go/bin /Library/Apple/usr/bin ~/Library/Android/sdk/emulator ~/Library/Android/sdk/tools ~/Library/Android/sdk/tools/bin ~/Library/Android/sdk/platform-tools ~/go/bin /usr/local/opt/go/libexec/bin ~/.antigen/bundles/robbyrussell/oh-my-zsh/lib ~/.antigen/bundles/mengelbrecht/slimline ~/.rvm/bin /usr/local/Cellar/emacs-plus@28/28.0.50/libexec/emacs/28.0.50/x86_64-apple-darwin19.6.0/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline ophints (popup +defaults) treemacs vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold (format +onsave) snippets :emacs dired electric undo vc :checkers syntax grammar :tools editorconfig (eval +overlay) (lookup +docsets) macos magit :lang emacs-lisp json javascript markdown (org +pomodoro) sh web yaml :config (default +bindings +smartparens))
        packages   ((ob-typescript) (indium) (prettier-js) (move-text))
        unpin      (n/a)
        elpa       (org-fancy-priorities)
```
</details>

**Comment by hlissner** [comment]
The archive is case sensitive, last I checked. Try `:ARCHIVE:` instead of `:archive:`.

**Comment by helderburato** [comment]
It seems we've the same setup this is what happening:

![doom-emacs-archive](https://user-images.githubusercontent.com/862575/89450509-07a75e80-d731-11ea-8576-db3abe552a22.gif)

**Comment by hlissner** [comment]
The mirror your actions in that gif and could not reproduce the issue, but I think I found the cause.

Add this to your `~/.doom.d/config.el` and let me know if it resolves the issue:

```elisp
(defadvice! fix-org-make-last-point-visible-h ()
  :override #'+org-make-last-point-visible-h
  (and (not org-inhibit-startup)
       (not org-inhibit-startup-visibility-stuff)
       (org-invisible-p nil 'folding-only)
       (or (not (org-on-heading-p))
           (not (member "ARCHIVE" (org-get-tags))))
       (ignore-errors
         (save-excursion
           (outline-previous-visible-heading 1)
           (org-show-subtree)))))
```

**Comment by helderburato** [comment]
> The mirror your actions in that gif and could not reproduce the issue, but I think I found the cause.
> 
> Add this to your `~/.doom.d/config.el` and let me know if it resolves the issue:
> 
> ```emacs-lisp
> (defadvice! fix-org-make-last-point-visible-h ()
>   :override #'+org-make-last-point-visible-h
>   (and (not org-inhibit-startup)
>        (not org-inhibit-startup-visibility-stuff)
>        (org-invisible-p nil 'folding-only)
>        (or (not (org-on-heading-p))
>            (not (member "ARCHIVE" (org-get-tags))))
>        (ignore-errors
>          (save-excursion
>            (outline-previous-visible-heading 1)
>            (org-show-subtree)))))
> ```
> 
> Side question: have you changed `org-agenda-inhibit-startup` in your config, somewhere?

I tried the code, but didn't work.
About `org-agenda-inhibit-startup` I didn't changed that, it's defaults to `t`.

**Comment by hlissner** [comment]
This appears to be an upstream issue, as I can reproduce this in vanilla Org 9.4. When `org-startup-folded` is set to `showeverything` (the default) [archived trees are expanded at startup due to this line](https://github.com/emacs-straight/org-mode/blob/master/lisp/org.el#L6540). Seems like an oversight.

**Comment by helderburato** [comment]
> This appears to be an upstream issue, as I can reproduce this in vanilla Org 9.4. ~When `org-startup-folded` is set to `showeverything` (the default) [archived trees are expanded at startup due to this line](https://github.com/emacs-straight/org-mode/blob/master/lisp/org.el#L6540). Seems like an oversight.~
> 
> When `org-startup-folded` is set to `showeverything`, it [org-set-startup-visibility](https://github.com/emacs-straight/org-mode/blob/master/lisp/org.el#L6537) never runs `org-cycle-hide-archived-subtrees` to hide them. So this is certainly an upstream issue.

Thanks for the quick reply!
I'll await the fix in upstream :)

**Comment by hlissner** [comment]
Whoops. d81ef69 was not a fix, just a refactor.

Anyhow, I'll mark this has `has-workaround` since `(setq org-startup-folded 'overview)` will get around this.

**Comment by helderburato** [comment]
> Whoops. [d81ef69](https://github.com/hlissner/doom-emacs/commit/d81ef695259e6e339fd5326c7e15ed0714638000) was not a fix, just a refactor.
> 
> Anyhow, I'll mark this has `has-workaround` since `(setq org-startup-folded 'overview)` will get around this.

Just to share with you, the workaround worked well 💯
