### ISSUE TITLE
How to configure +org-eval-handler to use jupyter python interpreter?

### ISSUE THREAD

**Issue by lccambiaghi** [hlissner/doom-emacs#3699]
https://github.com/hlissner/doom-emacs/commit/8ae0e799189b2685acd10632aa5ea24e573cd1a9

Before this commit, I used to execute my source blocks with `gr` and it would just work. 

Now I can `eval` a region but it is with a different interpreter than `org-ctrl-c-ctrl-c`. How can I configure it?

Thank you!

**Comment by hlissner** [comment]
Since jupyter-python blocks are likely using python's eval handlers, you should be able to set `python-shell-interpreter` to your interpreter of choice.

A more robust system is needed to accommodate wider support of more src block languages. It's a non-trivial endeavor and low priority at the moment, but I'll welcome PRs.

**Comment by lccambiaghi** [comment]
I am not really sure what functions are being called when `org-ctrl-c-ctrl-c` is called inside a `jupyter-python` source block. What I would like is to use the current "session" also when running `quickrun`. 

For now, I just mapped `gr` back to executing the code block. Thank you anyway.

**Comment by hlissner** [comment]
The original `gr` operator is used for evaluating code on the fly. As of 3b13105e0 it now has jupyter support. To use it to evaluate a src block, type `g r i e`. `gr` = the evaluate operator, `ie` = "inner element" (a src block is an element).

This differs from `C-c C-c` in how they are evaluated. `C-c C-c` will evaluate the src block conventionally, as a whole. `gr` can be used to evaluate a subset of a src block (or the entire thing if you like). It would be especially useful for folks with literate configs. They can evaluate subsets of their elisp blocks on the fly.

I would suggest using `C-c C-c` (`RET` will also conventionally execute babel blocks at point) separately from `gr`, but I'll leave that to you to decide. I'll consider this issue resolved, in any case.

**Comment by lccambiaghi** [comment]
Thank you for explaining the difference to me! It is indeed really nice to just use `gr` in my literate config!

I would like to achieve the same convenience when running `jupyter-python` code blocks. When I try to evaluate just one line of the block with `grr`, I receive the error:
```
cl-no-applicable-method: No applicable method: jupyter-send-execute-request, nil, :code, "import pandas as pd
", :store-history, nil
```
while `C-c C-c`ing a code block with just that single line works as expected.
