### ISSUE TITLE
Company-mode not completing in org-mode

### ISSUE THREAD

**Issue by nmartin84** [hlissner/doom-emacs#3700]
**What did you expect to happen?**
WIth active buffer set to org-mode, typed the abbrev for a snippet or org-roam reference and expected company-mode to provide completion.

**What actually happened?**
Company mode completion did not initiate, or provide a selection to choose from.

**Additional details:**
https://github.com/hlissner/doom-emacs/commit/3b159dda0a50369dba36ee8223759227a72eba6d

I was able to trace the issue back to this commit, specifically with this line:
`(set-company-backend! 'org-mode 'company-capf 'company-dabbrev)`

Once I commented out this line, and reloaded, company mode worked as expected.

**Steps to reproduce:**
1. Ran doom upgrade and upgraded to commit "6925909"
2. Reloaded Emacs
3. Setup one or two snippets and/or org-roam files
4. Update org-roam DB
5. Initiate new org-mode file and try typing abbrev for snippet or org-roam target

**System information:**
<details><pre>
emacs   version    28.0.50
        features   XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER LCMS2
        build      Aug 05, 2020
        buildopts  (--build=x86_64-linux-gnu --prefix=/usr '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' --sysconfdir=/etc --localstatedir=/var --disable-silent-rules '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' --disable-maintainer-mode --disable-dependency-tracking --prefix=/usr --sharedstatedir=/var/lib --program-suffix=-snapshot --with-modules=yes --with-x=yes --with-x-toolkit=gtk3 --with-xwidgets=yes 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/emacs-snapshot-lYSbck/emacs-snapshot-100814=. -fstack-protector-strong -Wformat -Werror=format-security' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro')
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      grafted, HEAD -> develop, origin/develop, origin/HEAD 1bc770e 2020-08-06 15:27:46 -0400
        dir        ~/.doom.d/
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/bash
        uname      Linux 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64
        path       (~/.local/bin /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /usr/games /usr/local/games /snap/bin /usr/lib/x86_64-linux-gnu/emacs/28.0.50/x86_64-linux-gnu/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company ivy :ui deft doom doom-dashboard doom-quit hl-todo modeline ophints (popup +defaults) vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold parinfer snippets :emacs dired electric undo vc :checkers syntax :tools (eval +overlay) lookup magit :lang data emacs-lisp json latex ledger markdown (org +roam +dragndrop +pandoc +present +gnuplot +noter) plantuml python rest rust sh yaml :config literate (default +bindings +smartparens))
        packages   ((org-roam-server) (company-org-roam) (chocolate-theme) (org-edna) (helm-org-rifle) (literate-calc-mode) (org-ql) (org-super-agenda) (elfeed) (elfeed-org) (ob-mermaid) (mermaid-mode) (ox-reveal) (ox-pandoc) (ox-twbs) (gnuplot) (gnuplot-mode) (deadgrep) (org-web-tools) (graphviz-dot-mode) (org-analyzer))
        unpin      (n/a)
        elpa       (n/a)
</pre></details>

**Comment by hlissner** [comment]
That's because `company-yasnippet` is not one of the default backends, and isn't because snippet completion has a dedicated keybind in insert mode: `C-x C-s` (ala omnicompletion in vim). Either use that, or change the default backends like so:

```elisp
;; in ~/.doom.d/config.el
(after! org
  (set-company-backend! 'org-mode 'company-capf '(company-dabbref :with comapny-yasnippet)))
```

**Comment by nmartin84** [comment]
Thanks, I'll look into it - I added this as a bug because it worked prior to updating to this commit.
