### ISSUE TITLE
How to bind two keypress without prefix

### ISSUE THREAD

**Issue by romariorobby** [hlissner/doom-emacs#3707]
is it possible to bind with 2 keypress . for instance:

```elisp
(map! :leader
      :desc "save and quit"  **"wq"** #'evil-save-and-close
      ...
```

i'm just curious is there way to do that? i hope that make sense.

**Comment by hlissner** [comment]
> (map! :leader :desc "save and quit" "wq" #'evil-save-and-close)

Did you try it?

**Comment by romariorobby** [comment]
it didn't work.

**Comment by romariorobby** [comment]
well, also have bind for "w" to write . Apparently, it didn't work when i bind at the "wq" for write and quit at the same time.

**Comment by romariorobby** [comment]
![2020-08-09_00-00](https://user-images.githubusercontent.com/40323094/89715917-5ffd8b00-d9d3-11ea-9a1e-1701ef5e2330.png)

**Comment by hlissner** [comment]
You cannot use a key as a prefix (e.g. `wq`) _and_ a keybind (e.g. `w`). It's one or the other, unless you're up to write some gnarly elisp hackery to get it working. I'd recommend just binding the latter to `ww` instead.

```lisp
(map! :leader
      "wq" #'evil-save-and-quit
      "ww" #'evil-write)
```

Or just use `SPC b s` (saves the buffer) to save and `SPC q q` (saves buffers and quits)

**Comment by romariorobby** [comment]
Oh got it. Thank you for you time!
