### ISSUE TITLE
Error when loading files from an opened project(projectile)

### ISSUE THREAD

**Issue by saidnamyzO** [hlissner/doom-emacs#3709]
I'm having issues with projectile when opening files from a project, the error reports this within the minibuffer:
```
error: The argument '--type <filetype>' was provided more than once, but cannot be used multiple times

USAGE:
fd [FLAGS/OPTIONS] [<pattern>] [<path>]

For more information try --help
```

**Comment by hlissner** [comment]
Are you sure you installed the correct `fd`? On ubuntu the `fd` package has nothing to do with [fd](https://github.com/sharkdp/fd). On there it's called `fd-find`.

----

Side note: Please, _please_, do not ignore the issue template. It will ask you to:

1. Always include your `M-x doom/info`
2. At least include the steps you used to reproduce the issue (including keys you pressed, commands you invoked -- gifs would help).
3. If possible, provide a link to your config.

**Comment by saidnamyzO** [comment]
Nothing to do with my configs, I tried the default one and I still have this issue.

Installed coreutils, fd, ripgrep...from homebrew as recommended by the macos install steps.
This happens every time I open a project with `SPC p p`
The error is displayed instead of providing the list of files for the project.
This also happens when I do `SPC SPC`to look for files within a current opened project

```
((emacs
  (version . "26.3")
  (features . "NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS")
  (build . "Sep 02, 2019")
  (buildopts "--with-ns '--enable-locallisppath=/Library/Application Support/Emacs/${version}/site-lisp:/Library/Application Support/Emacs/site-lisp' --with-modules")
  (windowsys . batch)
  (daemonp))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop 8bbac4bf 2020-08-08 03:06:26 -0400")
  (dir . "~/.doom.d/"))
 (system
  (type . darwin)
  (config . "x86_64-apple-darwin14.5.0")
  (shell . "/bin/zsh")
  (uname . "Darwin 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64")
  (path "~/bin" "/usr/local/bin" "~/.cargo/bin" "/Library/Frameworks/Python.framework/Versions/2.7/bin" "/Library/Frameworks/Python.framework/Versions/3.6/bin" "/usr/local/bin" "/usr/bin" "/bin" "/usr/sbin" "/sbin" "/opt/X11/bin" "/Library/TeX/texbin" "/Applications/Emacs.app/Contents/MacOS/bin-x86_64-10_10" "/Applications/Emacs.app/Contents/MacOS/libexec-x86_64-10_10" "/Applications/Emacs.app/Contents/MacOS/libexec" "/Applications/Emacs.app/Contents/MacOS/bin"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline ophints (popup +defaults) vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold snippets :emacs dired electric undo vc :checkers syntax :tools (eval +overlay) lookup magit :lang emacs-lisp markdown org sh :config (default +bindings +smartparens))
  (packages "n/a")
  (unpin "n/a")
  (elpa "n/a")))
```

**Comment by hlissner** [comment]
What does `man fd` say about the `--type` argument? I see this at the bottom of it:

```
This option can be used repeatedly to allow for multiple file types.
```

And yet, the error you're seeing is complaining that it is being used multiple times.

What happens when you run it by hand?

```sh
cd ~/.emacs.d
fd . -0 -H -E .git --color=never --type file --type symlink --follow core
```

**Comment by saidnamyzO** [comment]
Man page does not display that for me, it displays:
```
-t, --type filetype
              Filter search by type:

              f, file
                     regular files

              d, directories
                     directories

              s, symlink
                     symbolic links
```

Am I running the wrong version or something? I installed from homebrew as the install steps say so. I checked if I'm actually running the brew version by doing `ls -l $(which fd)` and I get
```
lrwxr-xr-x  1 ozymandias  admin  25 Aug  7 19:37 /usr/local/bin/fd -> ../Cellar/fd/6.0.0/bin/fd
```

When I run the fd command by hand with the arguments you provided I get the same error as the one I'm getting within emacs.
so, wrong exec installed?

**Comment by hlissner** [comment]
Sorry for the late response. Do you still have this issue?

**Comment by saidnamyzO** [comment]
> Sorry for the late response. Do you still have this issue?

sorry, could no longer test. I stopped using macos and was required to use vscode as my main env.
