### ISSUE TITLE
How to remove Command key as meta key

### ISSUE THREAD

**Issue by codewithovi** [hlissner/doom-emacs#3717]
How to remove Command key as a meta key. I am happy with the only option key to be my meta key and want to remove command key as meta.

**Comment by hlissner** [comment]
By changing `ns-command-modifier`, which I've fixed in https://github.com/hlissner/doom-emacs/commit/85b5103cd9c1405b80d0fb5f690588f013a86f98. Let me know if that isn't the case and I'll reopen the issue.
