### ISSUE TITLE
Treemacs doesn't load persisted workspace 'Perspective main'

### ISSUE THREAD

**Issue by SleepyBag** [hlissner/doom-emacs#3720]
**What did you expect to happen?**
Say I have a persisted treemacs file, with the following content.
```
* Default
*** qmxue
     - path :: /data/mm64/qmxue
*** tmp
     - path :: /tmp
* Perspective main
*** qmxue
     - path :: /data/mm64/qmxue
*** tmp
     - path :: /tmp
*** lib
     - path :: /lib
```
Giving that the main workspace is automatically choosed, treemacs is expected to at the `Perspective main` workspace.

**What actually happened?**
But when I open emacs, treemacs shows my current directory.

**Additional details:**
If I run `(treemacs-set-scope-type 'Perspectives)` manually, treemacs will load the right workspace.

The most weird thing is that, when I put `(message "Current treemacs workspace %s" (treemacs-current-workspace))` into `use-package! treemacs :config)` section of `.emacs.d/modules/ui/treemacs/config.el`, treemacs will just behave as I expected. It will show the workspace `Perspective main`. But I did nothing but print it! I am so confused now and need your help. Thank you!

**Comment by Alexander-Miller** [comment]
> But I did nothing but print it!

The current-workspace is lazily loaded. When you try to print it in your config you are making treemacs select it. The standard selection process is picking whichever workspace contains the current file. If there's no such workspace, or there is no file, treemacs will pick the "fallback" - the workspace at the top of the list. For you that's `Default`. You can use `treemacs-set-fallback-workspace` to move a workspace to the top, or you can use `treemacs-edit-workspaces`. 

If all the initialization happens correctly you should still start with the scope type set to perspectives. That might be a problem for doom, or for treemacs. I'll have a look at how doom handles things. 

But there's some other strange things I'm seeing here:

 - It should be two stars for project names, not three. Is that a typo?
 - You have 2 workspaces with multiple projects. AFAIK doom patches treemacs to only ever have one. How does that work out?

**Comment by SleepyBag** [comment]
> It should be two stars for project names, not three. Is that a typo?

Sorry for the typo. There should be two stars. That's because of the terminal. The terminal display two dimmed stars and one lighted stars in org-mode when there are two stars. I just copied it. There is nothing wrong in the actual file.

> You have 2 workspaces with multiple projects. AFAIK doom patches treemacs to only ever have one. How does that work out?

I just run `treemacs-add-project-to-workspace` in two different workspaces.
