### ISSUE TITLE
SPC p c ask for compile command but does not offer completion from project root dir

### ISSUE THREAD

**Issue by egils-consulting** [hlissner/doom-emacs#3721]
**What did you expect to happen?**
I expected to be able to complete the command both from the list below the prompt AND from files in the project
So by default doom lists the previous compile commands used in this project and if I start typing something else its clever enough to offer file-completion.

**What actually happened?**
entering "python doli" and pressing TAB gives no results below. Tabbing TAB again starts the compiling and renders an error because there is no "doli" file in the project root.
It seems I have to type out the whole path manually which is bad.

**System information:**
see my previous bug report here: https://github.com/hlissner/doom-emacs/issues/3714

Feel free to ask if you need more information.

**Comment by hlissner** [comment]
In the future please include your `M-x doom/info` in all bug reports. Even if they are consecutive bug reports.

----

Hi! Thanks for the suggestion, but this is not Doom's prerogative. The command on `SPC p c` is `counsel-compile`. To suggest improvements to this command, please take them [upstream](https://github.com/abo-abo/swiper).
