### ISSUE TITLE
Rename-file is the only way to move files which is counterintuitive. 

### ISSUE THREAD

**Issue by egils-consulting** [hlissner/doom-emacs#3722]
**What did you expect to happen?**
doom emacs supports common file operations out of the box without the user having to learn specialized emacs speak. 
We should have both move-file and rename-file commands (they can call the same elisp function or whatever behind the scenes). 

**What actually happened?**
M-x "move" does not give meaningful results when trying to move a file. (we only currently have move-file-to-trash it seems)

**Comment by hlissner** [comment]
Hi! Thanks for the suggestion, but Doom already has `M-x doom/move-this-file` on `SPC f R` (or `C-c f R` for non-evil users). Evil users also have `+evil:move-this-file` bound to the `:mv FILENAME` ex command.

If you want Emacs itself to provide, specifically, a `move-file` alias, I suggest bringing it up upstream, in the Emacs mailing lists.

----

Side note: in the future please include your `M-x doom/info` in all bug reports. Even if they are consecutive bug reports.

**Comment by egils-consulting** [comment]
I was not aware of that. Thanks for taking time to answer.
