### ISSUE TITLE
File operations in a dired buffer should call revert-buffer when finished succesfully

### ISSUE THREAD

**Issue by egils-consulting** [hlissner/doom-emacs#3723]
**What did you expect to happen?**
the dired buffer remains unchanged despite renaming a file in the directory it visits.

**What actually happened?**
I do not see the results of rename-file in the dired buffer I'm visiting. (In my case I moved it to another folder so it should have disappeared)

This should effect deletions, renaming, moving and creating directories, etc.

**Comment by hlissner** [comment]
Add this to `~/.doom.d/config.el` and let me know if it works for you:

```elisp
(defadvice! +dired-refresh-buffers-after-rename-a (&rest _)
    :after #'rename-file
    (dolist (buf (doom-buffers-in-mode 'dired-mode))
      (with-current-buffer buf
        (revert-buffer t t t))))
```

**Comment by hlissner** [comment]
Normally, Doom auto-reverts buffers when you focus them or their containing window, _or_ when you focus Emacs (after doing something elsewhere). This wasn't happening in non-file buffers, like dired buffers, until 9cab6a6, which should fix your issue indirectly. 

I had considered refreshing all dired buffers after any call to `rename-file`, but this could have disastrous performance implications anywhere where `rename-file` is used programmatically on a large number of files -- and there is no way to determine whether it's being used for batch renaming or one-off jobs -- so I opted for this solution instead.

**Comment by egils-consulting** [comment]
Very nice. Thank you for taking a stab at this 😀
