### ISSUE TITLE
Support bépo keyboard layout

### ISSUE THREAD

**Issue by xtab** [hlissner/doom-emacs#3728]
I’ve just had a look at Doom Emacs and it looks very promising! However, just like #767 and #783, I’m using a non-{AZ,QW}ERT{Y,Z} layout: instead, I’m using the [Bépo](http://bepo.fr/wiki/Accueil) keyboard layout and I’m used to swapping HJKL and CTSR when using either Vim or Spacemacs, along with some other keybindings (like “é” as a synonym for “w”).

Spacemacs [already natively supports](https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Bintl/keyboard-layout) such a feature.

For now, I seem to be able to have roughly what I want by creating a `bepo.el` file in my `~/.doom.d` directory like so:
 
```elisp
;;; bepo.el -*- lexical-binding: t; -*-

(map! :nvm "h" 'evil-replace
      :nvm "H" 'evil-replace-state
      :nvm "j" 'evil-find-char-to
      :nvm "J" 'evil-find-char-to-backward
      :nvm "k" 'evil-substitute
      :nvm "K" 'evil-change-whole-line
      :nvm "l" 'evil-change
      :nvm "L" 'evil-change-line

      :nvm "c" 'evil-backward-char
      :nvm "C" 'evil-window-top
      :nvm "t" 'evil-next-line
      :nvm "T" 'evil-join
      :nvm "s" 'evil-previous-line
      :nvm "r" 'evil-forward-char
      :nvm "R" 'evil-window-bottom

      :nvm "é" 'evil-forward-word-begin
      :nvm "É" 'evil-forward-WORD-begin

      :map evil-snipe-local-mode-map
      (:nm "k" 'evil-snipe-s
       :nm "K" 'evil-snipe-S
       :nm "s" nil
       :nm "S" nil)
      :map evil-snipe-override-local-mode-map
      (:m "j" 'evil-snipe-t
       :m "J" 'evil-snipe-T
       :m "t" nil
       :m "T" nil))
```

But I’m not sure if that’s sustainable, since it means that I’d need to swap hjkl and ctsr in any major mode map.

In the end, I’d just like to have `(doom! :input bepo)` in `~/.doom.d/init.el` and have my Bépo bindings ready.

**Comment by gagbo** [comment]
That's definitely not enough, all the evil collection maps, and all packages that have specific `evil-*` packages, and all other common maps (like mapping `é` to `doom-window-map` in normal mode, and possibly map «» and èà (even maybe çê) to avoid chording would be necessary.

The spacemacs layer also remaps avy keys so the targets stay on home row.

I'm slowly [creating a module](https://framagit.org/gagbo/doom-config/-/tree/feature/input-layout/modules/input/layout) to handle this, and you can steal it if you want, but knowing that Henrik definitely cannot maintain this, I'm waiting to have something better before pushing a PR

**Comment by gagbo** [comment]
Feel free to push PRs and issues if you see anything weird
