### ISSUE TITLE
dap-java-* methods not available

### ISSUE THREAD

**Issue by nipuna-perera** [hlissner/doom-emacs#3731]
**What did you expect to happen?**
When using lsp-java mode, I expect to see the dap-mode commands like dap-java-debug. 

I have (java +lsp) and (debugger +lsp) enabled. 

**What actually happened?**

None of the dap-java commands are available. 

**Additional details:**
SPC m t t does not work and I see the following.

```
condition-case: Symbol’s function definition is void: dap-java-run-test-method [2 times]
```

**System information:**
<details><pre>
(emacs
  (version . "26.3")
  (features . "NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS")
  (build . "Mar 05, 2020")
  (buildopts "--enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-mac/emacs-26.3-z-mac-7.8/share/info/emacs --prefix=/usr/local/Cellar/emacs-mac/emacs-26.3-z-mac-7.8 --with-mac --enable-mac-app=/usr/local/Cellar/emacs-mac/emacs-26.3-z-mac-7.8 --with-gnutls")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop 050ac7378 2020-08-10 23:07:21 -0400")
  (dir . "~/.doom.d/"))
 (system
  (type . darwin)
  (config . "x86_64-apple-darwin18.7.0")
  (shell . "/usr/local/bin/zsh")
  (uname . "Darwin 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64")
  (path "/var/folders/d7/d8rs7cm10zsb65q00_d9qv51mxn334/T/fnm-shell-1051100/bin" "/var/folders/d7/d8rs7cm10zsb65q00_d9qv51mxn334/T/fnm-shell-8307381/bin" "~/.dotfiles/bin" "/usr/local/sbin" "/usr/local/opt/grep/libexec/gnubin" "/usr/local/bin" "/usr/bin" "/bin" "/usr/sbin" "/sbin" "$HOME/go/bin" "~/go/bin" "/usr/local/opt/fzf/bin" "/usr/local/Cellar/emacs-mac/emacs-26.3-z-mac-7.8/libexec/emacs/26.3/x86_64-apple-darwin18.7.0"))
 (config
  (envfile)
  (elc-files . 0)
  (modules :completion (company +childframe) (ivy +fuzzy +icons +prescient +childframe) :ui deft doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) (pretty-code +fira) treemacs vc-gutter vi-tilde-fringe window-select workspaces minimap :editor (evil +everywhere) file-templates fold format snippets :emacs (dired +icons) electric (ibuffer +icons) vc :term eshell :checkers syntax :tools (debugger +lsp) (docker +lsp) editorconfig (eval +overlay) lookup (lsp +peek) macos magit pdf rgb upload :lang csharp data emacs-lisp (go +lsp) (java +lsp) javascript markdown (org +dragndrop +journal +roam +pandoc +pomodoro +present) (python +lsp) sh (web +lsp) :app (rss +org) :config (default +bindings +snippets +evil-commands +smartparens))
  (packages (groovy-mode) (k8s-mode) (groovy-imports) (org-super-agenda) (prettier-js) (deadgrep) (markdown-changelog))
  (unpin "n/a")
  (elpa "s" "pythonic" "org-fancy-priorities" "f" "elfeed" "dash" "company-anaconda" "company" "anaconda-mode")))
</pre></details>

**Comment by hlissner** [comment]
`dap-java` was moved to [lsp-java](https://github.com/emacs-lsp/lsp-java) in https://github.com/emacs-lsp/lsp-java/commit/fbd04cff52521f393408a219125d3a0727705045. Since Doom doesn't bind any `dap-java-*` keys, I assume they're bound in your config and will need to be updated.

**Comment by hlissner** [comment]
Ah, my bad. Forgot about [these](https://github.com/hlissner/doom-emacs/blob/develop/modules/lang/java/+lsp.el#L15-L18). As of ab33768 they should be fixed.
