### ISSUE TITLE
How to configure `org-download-dir`

### ISSUE THREAD

**Issue by anihm136** [hlissner/doom-emacs#3734]
When using `org-download`, by default the images are stored in a nested folder structure with the current date (for instance, `12/8/20/scr.png`). When I set the `org-download-image-dir` variable in `config.el`, the entire nested directory structure is moved into the folder I set (for instance, `images/12/8/20/scr.png`). How do I prevent the nested structure from forming and store images in a flat structure in the directory I specify? (i.e, `images/scr.png`)

P.S. Sorry for not using Discord for this, I don't have access to it right now coz I lost the phone I use for 2FA

**Comment by hlissner** [comment]
I believe `org-download-method` controls this. Try

```elisp
;; file/directory variables should be set outside of `after!` blocks.
(setq org-download-image-dir "path/to/download/dir")  ; `org-download-image-dir` defaults to `org-directory'/.attach/

(after! org-download
  (setq org-download-method 'directory))
```

**Comment by anihm136** [comment]
Ah that works! I was over-complicating things with `use-package`. Thank you!
