### ISSUE TITLE
Add symex support for lisp like languages 

### ISSUE THREAD

**Issue by gozes** [hlissner/doom-emacs#3738]
it be nice have support in doom for symex https://github.com/countvajhula/symex.el
I know there is lispy support but lispy is so hard to use with the so call key teams that it would be nice to just have support for something like symex that more strate forward

**Comment by hlissner** [comment]
Not a big fan of the hydra approach, but it looks interesting. However, it wouldn't need enough configuration to warrant its own module, and would only need two lines for end-users to add to their config, so I'll leave it to users to enable themselves.

**Comment by gozes** [comment]
maybe is just because I'm new to doom emacs but I don't see how this is two line change to get symex working well with doom emacs.
