### ISSUE TITLE
LSP is not a valid syntax checker

### ISSUE THREAD

**Issue by arandilopez** [hlissner/doom-emacs#3739]
**What did you expect to happen?**
LSP server is started when openning a file.
**What actually happened?**
LSP server wasn't started and I get this error:
```
File local-variables error: (doom-hook-error +javascript-init-lsp-or-tide-maybe-h (error lsp is not a valid syntax checker))
```
And when trying to init lsp with `M-x lsp` I get this one:
```
helm-M-x-execute-command: lsp is not a valid syntax checker
```

**Additional details:**
- My doom settings are here: https://github.com/arandilopez/.doom.d
- Pyright for python lsp
- Solargraph for ruby lsp
- typescript-language-server for js and ts files

**Debug stacktrace**
<details><pre>
Debugger entered--Lisp error: (error "lsp is not a valid syntax checker")
  signal(error ("lsp is not a valid syntax checker"))
  error("%s is not a valid syntax checker" lsp)
  flycheck-add-mode(lsp typescript-mode)
  lsp-flycheck-add-mode(typescript-mode)
  mapc(lsp-flycheck-add-mode (typescript-mode js-mode css-mode vue-html-mode))
  (closure (t) nil (mapc (function lsp-flycheck-add-mode) (quote (typescript-mode js-mode css-mode vue-html-mode))))()
  eval-after-load-helper("/home/arandilopez/.emacs.d/.local/straight/build/lsp-mode/lsp-mode.elc")
  run-hook-with-args(eval-after-load-helper "/home/arandilopez/.emacs.d/.local/straight/build/lsp-mode/lsp-mode.elc")
  do-after-load-evaluation("/home/arandilopez/.emacs.d/.local/straight/build/lsp-mode/lsp-mode.elc")
  (lsp-deferred)
  (if (and (boundp (quote lsp-mode)) lsp-mode) nil (lsp-deferred))
  (if nil (eglot-ensure) (if (and (boundp (quote lsp-mode)) lsp-mode) nil (lsp-deferred)))
  lsp!()
  (and t (lsp!))
  (or (and t (lsp!)) (if (executable-find "node") (and (require (quote tide) nil t) (progn (tide-setup) tide-mode)) (ignore (if doom-debug-p (progn (let ((inhibit-message ...)) (message #("DOOM [lang/javascript] Couldn't start tide because 'node' is missing" 0 5 (face font-lock-comment-face) 5 23 (face warning)))))))))
  (if (not buffer-file-name) (add-hook (quote after-save-hook) (function +javascript-init-lsp-or-tide-maybe-h) nil (quote local)) (or (and t (lsp!)) (if (executable-find "node") (and (require (quote tide) nil t) (progn (tide-setup) tide-mode)) (ignore (if doom-debug-p (progn (let (...) (message #("DOOM [lang/javascript] Couldn't start tide because 'node' is missing" 0 5 (face font-lock-comment-face) 5 23 (face warning))))))))) (remove-hook (quote after-save-hook) (function +javascript-init-lsp-or-tide-maybe-h) (quote local)))
  (progn (if (not buffer-file-name) (add-hook (quote after-save-hook) (function +javascript-init-lsp-or-tide-maybe-h) nil (quote local)) (or (and t (lsp!)) (if (executable-find "node") (and (require (quote tide) nil t) (progn (tide-setup) tide-mode)) (ignore (if doom-debug-p (progn (let ... ...)))))) (remove-hook (quote after-save-hook) (function +javascript-init-lsp-or-tide-maybe-h) (quote local))))
  (if (derived-mode-p (quote js-mode) (quote typescript-mode) (quote typescript-tsx-mode)) (progn (if (not buffer-file-name) (add-hook (quote after-save-hook) (function +javascript-init-lsp-or-tide-maybe-h) nil (quote local)) (or (and t (lsp!)) (if (executable-find "node") (and (require (quote tide) nil t) (progn (tide-setup) tide-mode)) (ignore (if doom-debug-p (progn ...))))) (remove-hook (quote after-save-hook) (function +javascript-init-lsp-or-tide-maybe-h) (quote local)))))
  (let ((buffer-file-name (buffer-file-name (buffer-base-buffer)))) (if (derived-mode-p (quote js-mode) (quote typescript-mode) (quote typescript-tsx-mode)) (progn (if (not buffer-file-name) (add-hook (quote after-save-hook) (function +javascript-init-lsp-or-tide-maybe-h) nil (quote local)) (or (and t (lsp!)) (if (executable-find "node") (and (require ... nil t) (progn ... tide-mode)) (ignore (if doom-debug-p ...)))) (remove-hook (quote after-save-hook) (function +javascript-init-lsp-or-tide-maybe-h) (quote local))))))
  +javascript-init-lsp-or-tide-maybe-h()
  funcall(+javascript-init-lsp-or-tide-maybe-h)
  (condition-case e (funcall hook) ((debug error) (signal (quote doom-hook-error) (list hook e))))
  doom-try-run-hook(+javascript-init-lsp-or-tide-maybe-h)
  run-hook-wrapped(doom-try-run-hook +javascript-init-lsp-or-tide-maybe-h)
  (if doom--inhibit-local-var-hooks nil (set (make-local-variable (quote doom--inhibit-local-var-hooks)) t) (run-hook-wrapped (intern-soft (format "%s-local-vars-hook" major-mode)) (function doom-try-run-hook)))
  doom-run-local-var-hooks-h()
  run-hooks(hack-local-variables-hook)
  hack-local-variables-apply()
  #f(compiled-function (&optional handle-mode) "Parse and put into effect this buffer's local variables spec.\nFor buffers visiting files, also puts into effect directory-local\nvariables.\nUses `hack-local-variables-apply' to apply the variables.\n\nIf HANDLE-MODE is nil, we apply all the specified local\nvariables.  If HANDLE-MODE is neither nil nor t, we do the same,\nexcept that any settings of `mode' are ignored.\n\nIf HANDLE-MODE is t, all we do is check whether a \"mode:\"\nis specified, and return the corresponding mode symbol, or nil.\nIn this case, we try to ignore minor-modes, and only return a\nmajor-mode.\n\nIf `enable-local-variables' or `local-enable-local-variables' is nil,\nthis function does nothing.  If `inhibit-local-variables-regexps'\napplies to the file in question, the file is not scanned for\nlocal variables, but directory-local variables may still be applied." #<bytecode 0x1b5ef7>)(no-mode)
  apply(#f(compiled-function (&optional handle-mode) "Parse and put into effect this buffer's local variables spec.\nFor buffers visiting files, also puts into effect directory-local\nvariables.\nUses `hack-local-variables-apply' to apply the variables.\n\nIf HANDLE-MODE is nil, we apply all the specified local\nvariables.  If HANDLE-MODE is neither nil nor t, we do the same,\nexcept that any settings of `mode' are ignored.\n\nIf HANDLE-MODE is t, all we do is check whether a \"mode:\"\nis specified, and return the corresponding mode symbol, or nil.\nIn this case, we try to ignore minor-modes, and only return a\nmajor-mode.\n\nIf `enable-local-variables' or `local-enable-local-variables' is nil,\nthis function does nothing.  If `inhibit-local-variables-regexps'\napplies to the file in question, the file is not scanned for\nlocal variables, but directory-local variables may still be applied." #<bytecode 0x1b5ef7>) no-mode nil)
  so-long--hack-local-variables(#f(compiled-function (&optional handle-mode) "Parse and put into effect this buffer's local variables spec.\nFor buffers visiting files, also puts into effect directory-local\nvariables.\nUses `hack-local-variables-apply' to apply the variables.\n\nIf HANDLE-MODE is nil, we apply all the specified local\nvariables.  If HANDLE-MODE is neither nil nor t, we do the same,\nexcept that any settings of `mode' are ignored.\n\nIf HANDLE-MODE is t, all we do is check whether a \"mode:\"\nis specified, and return the corresponding mode symbol, or nil.\nIn this case, we try to ignore minor-modes, and only return a\nmajor-mode.\n\nIf `enable-local-variables' or `local-enable-local-variables' is nil,\nthis function does nothing.  If `inhibit-local-variables-regexps'\napplies to the file in question, the file is not scanned for\nlocal variables, but directory-local variables may still be applied." #<bytecode 0x1b5ef7>) no-mode)
  apply(so-long--hack-local-variables #f(compiled-function (&optional handle-mode) "Parse and put into effect this buffer's local variables spec.\nFor buffers visiting files, also puts into effect directory-local\nvariables.\nUses `hack-local-variables-apply' to apply the variables.\n\nIf HANDLE-MODE is nil, we apply all the specified local\nvariables.  If HANDLE-MODE is neither nil nor t, we do the same,\nexcept that any settings of `mode' are ignored.\n\nIf HANDLE-MODE is t, all we do is check whether a \"mode:\"\nis specified, and return the corresponding mode symbol, or nil.\nIn this case, we try to ignore minor-modes, and only return a\nmajor-mode.\n\nIf `enable-local-variables' or `local-enable-local-variables' is nil,\nthis function does nothing.  If `inhibit-local-variables-regexps'\napplies to the file in question, the file is not scanned for\nlocal variables, but directory-local variables may still be applied." #<bytecode 0x1b5ef7>) no-mode)
  hack-local-variables(no-mode)
  run-mode-hooks(rjsx-mode-hook)
  rjsx-mode()
  set-auto-mode-0(rjsx-mode nil)
  #f(compiled-function (&optional keep-mode-if-same) "Select major mode appropriate for current buffer.\n\nTo find the right major mode, this function checks for a -*- mode tag\nchecks for a `mode:' entry in the Local Variables section of the file,\nchecks if it uses an interpreter listed in `interpreter-mode-alist',\nmatches the buffer beginning against `magic-mode-alist',\ncompares the filename against the entries in `auto-mode-alist',\nthen matches the buffer beginning against `magic-fallback-mode-alist'.\n\nIf `enable-local-variables' is nil, or if the file name matches\n`inhibit-local-variables-regexps', this function does not check\nfor any mode: tag anywhere in the file.  If `local-enable-local-variables'\nis nil, then the only mode: tag that can be relevant is a -*- one.\n\nIf the optional argument KEEP-MODE-IF-SAME is non-nil, then we\nset the major mode only if that would change it.  In other words\nwe don't actually set it to the same mode the buffer already has." #<bytecode 0x1b5abb>)()
  apply(#f(compiled-function (&optional keep-mode-if-same) "Select major mode appropriate for current buffer.\n\nTo find the right major mode, this function checks for a -*- mode tag\nchecks for a `mode:' entry in the Local Variables section of the file,\nchecks if it uses an interpreter listed in `interpreter-mode-alist',\nmatches the buffer beginning against `magic-mode-alist',\ncompares the filename against the entries in `auto-mode-alist',\nthen matches the buffer beginning against `magic-fallback-mode-alist'.\n\nIf `enable-local-variables' is nil, or if the file name matches\n`inhibit-local-variables-regexps', this function does not check\nfor any mode: tag anywhere in the file.  If `local-enable-local-variables'\nis nil, then the only mode: tag that can be relevant is a -*- one.\n\nIf the optional argument KEEP-MODE-IF-SAME is non-nil, then we\nset the major mode only if that would change it.  In other words\nwe don't actually set it to the same mode the buffer already has." #<bytecode 0x1b5abb>) nil)
  so-long--set-auto-mode(#f(compiled-function (&optional keep-mode-if-same) "Select major mode appropriate for current buffer.\n\nTo find the right major mode, this function checks for a -*- mode tag\nchecks for a `mode:' entry in the Local Variables section of the file,\nchecks if it uses an interpreter listed in `interpreter-mode-alist',\nmatches the buffer beginning against `magic-mode-alist',\ncompares the filename against the entries in `auto-mode-alist',\nthen matches the buffer beginning against `magic-fallback-mode-alist'.\n\nIf `enable-local-variables' is nil, or if the file name matches\n`inhibit-local-variables-regexps', this function does not check\nfor any mode: tag anywhere in the file.  If `local-enable-local-variables'\nis nil, then the only mode: tag that can be relevant is a -*- one.\n\nIf the optional argument KEEP-MODE-IF-SAME is non-nil, then we\nset the major mode only if that would change it.  In other words\nwe don't actually set it to the same mode the buffer already has." #<bytecode 0x1b5abb>))
  apply(so-long--set-auto-mode #f(compiled-function (&optional keep-mode-if-same) "Select major mode appropriate for current buffer.\n\nTo find the right major mode, this function checks for a -*- mode tag\nchecks for a `mode:' entry in the Local Variables section of the file,\nchecks if it uses an interpreter listed in `interpreter-mode-alist',\nmatches the buffer beginning against `magic-mode-alist',\ncompares the filename against the entries in `auto-mode-alist',\nthen matches the buffer beginning against `magic-fallback-mode-alist'.\n\nIf `enable-local-variables' is nil, or if the file name matches\n`inhibit-local-variables-regexps', this function does not check\nfor any mode: tag anywhere in the file.  If `local-enable-local-variables'\nis nil, then the only mode: tag that can be relevant is a -*- one.\n\nIf the optional argument KEEP-MODE-IF-SAME is non-nil, then we\nset the major mode only if that would change it.  In other words\nwe don't actually set it to the same mode the buffer already has." #<bytecode 0x1b5abb>) nil)
  #f(advice-wrapper :around #f(compiled-function (&optional keep-mode-if-same) "Select major mode appropriate for current buffer.\n\nTo find the right major mode, this function checks for a -*- mode tag\nchecks for a `mode:' entry in the Local Variables section of the file,\nchecks if it uses an interpreter listed in `interpreter-mode-alist',\nmatches the buffer beginning against `magic-mode-alist',\ncompares the filename against the entries in `auto-mode-alist',\nthen matches the buffer beginning against `magic-fallback-mode-alist'.\n\nIf `enable-local-variables' is nil, or if the file name matches\n`inhibit-local-variables-regexps', this function does not check\nfor any mode: tag anywhere in the file.  If `local-enable-local-variables'\nis nil, then the only mode: tag that can be relevant is a -*- one.\n\nIf the optional argument KEEP-MODE-IF-SAME is non-nil, then we\nset the major mode only if that would change it.  In other words\nwe don't actually set it to the same mode the buffer already has." #<bytecode 0x1b5abb>) so-long--set-auto-mode)()
  apply(#f(advice-wrapper :around #f(compiled-function (&optional keep-mode-if-same) "Select major mode appropriate for current buffer.\n\nTo find the right major mode, this function checks for a -*- mode tag\nchecks for a `mode:' entry in the Local Variables section of the file,\nchecks if it uses an interpreter listed in `interpreter-mode-alist',\nmatches the buffer beginning against `magic-mode-alist',\ncompares the filename against the entries in `auto-mode-alist',\nthen matches the buffer beginning against `magic-fallback-mode-alist'.\n\nIf `enable-local-variables' is nil, or if the file name matches\n`inhibit-local-variables-regexps', this function does not check\nfor any mode: tag anywhere in the file.  If `local-enable-local-variables'\nis nil, then the only mode: tag that can be relevant is a -*- one.\n\nIf the optional argument KEEP-MODE-IF-SAME is non-nil, then we\nset the major mode only if that would change it.  In other words\nwe don't actually set it to the same mode the buffer already has." #<bytecode 0x1b5abb>) so-long--set-auto-mode) nil)
  set-auto-mode()
  normal-mode(t)
  #f(compiled-function (&optional error warn noauto after-find-file-from-revert-buffer nomodes) "Called after finding a file and by the default revert function.\nSets buffer mode, parses file-local and directory-local variables.\nOptional args ERROR, WARN, and NOAUTO: ERROR non-nil means there was an\nerror in reading the file.  WARN non-nil means warn if there\nexists an auto-save file more recent than the visited file.\nNOAUTO means don't mess with auto-save mode.\nFourth arg AFTER-FIND-FILE-FROM-REVERT-BUFFER is ignored\n(see `revert-buffer-in-progress-p' for similar functionality).\nFifth arg NOMODES non-nil means don't alter the file's modes.\nFinishes by calling the functions in `find-file-hook'\nunless NOMODES is non-nil." #<bytecode 0x1b52df>)(nil t)
  apply(#f(compiled-function (&optional error warn noauto after-find-file-from-revert-buffer nomodes) "Called after finding a file and by the default revert function.\nSets buffer mode, parses file-local and directory-local variables.\nOptional args ERROR, WARN, and NOAUTO: ERROR non-nil means there was an\nerror in reading the file.  WARN non-nil means warn if there\nexists an auto-save file more recent than the visited file.\nNOAUTO means don't mess with auto-save mode.\nFourth arg AFTER-FIND-FILE-FROM-REVERT-BUFFER is ignored\n(see `revert-buffer-in-progress-p' for similar functionality).\nFifth arg NOMODES non-nil means don't alter the file's modes.\nFinishes by calling the functions in `find-file-hook'\nunless NOMODES is non-nil." #<bytecode 0x1b52df>) (nil t))
  (if (setq doom-large-file-p (and buffer-file-name (not doom-large-file-p) (file-exists-p buffer-file-name) (condition-case nil (progn (> (nth 7 (file-attributes buffer-file-name)) (* 1024 1024 (assoc-default buffer-file-name doom-large-file-size-alist ...)))) (error nil)))) (prog1 (apply orig-fn args) (if (memq major-mode doom-large-file-excluded-modes) (setq doom-large-file-p nil) (if (fboundp (quote so-long-minor-mode)) (progn (so-long-minor-mode 1))) (message "Large file detected! Cutting a few corners to improve performance..."))) (apply orig-fn args))
  doom--optimize-for-large-files-a(#f(compiled-function (&optional error warn noauto after-find-file-from-revert-buffer nomodes) "Called after finding a file and by the default revert function.\nSets buffer mode, parses file-local and directory-local variables.\nOptional args ERROR, WARN, and NOAUTO: ERROR non-nil means there was an\nerror in reading the file.  WARN non-nil means warn if there\nexists an auto-save file more recent than the visited file.\nNOAUTO means don't mess with auto-save mode.\nFourth arg AFTER-FIND-FILE-FROM-REVERT-BUFFER is ignored\n(see `revert-buffer-in-progress-p' for similar functionality).\nFifth arg NOMODES non-nil means don't alter the file's modes.\nFinishes by calling the functions in `find-file-hook'\nunless NOMODES is non-nil." #<bytecode 0x1b52df>) nil t)
  apply(doom--optimize-for-large-files-a #f(compiled-function (&optional error warn noauto after-find-file-from-revert-buffer nomodes) "Called after finding a file and by the default revert function.\nSets buffer mode, parses file-local and directory-local variables.\nOptional args ERROR, WARN, and NOAUTO: ERROR non-nil means there was an\nerror in reading the file.  WARN non-nil means warn if there\nexists an auto-save file more recent than the visited file.\nNOAUTO means don't mess with auto-save mode.\nFourth arg AFTER-FIND-FILE-FROM-REVERT-BUFFER is ignored\n(see `revert-buffer-in-progress-p' for similar functionality).\nFifth arg NOMODES non-nil means don't alter the file's modes.\nFinishes by calling the functions in `find-file-hook'\nunless NOMODES is non-nil." #<bytecode 0x1b52df>) (nil t))
  #f(advice-wrapper :around #f(compiled-function (&optional error warn noauto after-find-file-from-revert-buffer nomodes) "Called after finding a file and by the default revert function.\nSets buffer mode, parses file-local and directory-local variables.\nOptional args ERROR, WARN, and NOAUTO: ERROR non-nil means there was an\nerror in reading the file.  WARN non-nil means warn if there\nexists an auto-save file more recent than the visited file.\nNOAUTO means don't mess with auto-save mode.\nFourth arg AFTER-FIND-FILE-FROM-REVERT-BUFFER is ignored\n(see `revert-buffer-in-progress-p' for similar functionality).\nFifth arg NOMODES non-nil means don't alter the file's modes.\nFinishes by calling the functions in `find-file-hook'\nunless NOMODES is non-nil." #<bytecode 0x1b52df>) doom--optimize-for-large-files-a)(nil t)
  apply(#f(advice-wrapper :around #f(compiled-function (&optional error warn noauto after-find-file-from-revert-buffer nomodes) "Called after finding a file and by the default revert function.\nSets buffer mode, parses file-local and directory-local variables.\nOptional args ERROR, WARN, and NOAUTO: ERROR non-nil means there was an\nerror in reading the file.  WARN non-nil means warn if there\nexists an auto-save file more recent than the visited file.\nNOAUTO means don't mess with auto-save mode.\nFourth arg AFTER-FIND-FILE-FROM-REVERT-BUFFER is ignored\n(see `revert-buffer-in-progress-p' for similar functionality).\nFifth arg NOMODES non-nil means don't alter the file's modes.\nFinishes by calling the functions in `find-file-hook'\nunless NOMODES is non-nil." #<bytecode 0x1b52df>) doom--optimize-for-large-files-a) (nil t))
  #f(advice-wrapper :before #f(advice-wrapper :around #f(compiled-function (&optional error warn noauto after-find-file-from-revert-buffer nomodes) "Called after finding a file and by the default revert function.\nSets buffer mode, parses file-local and directory-local variables.\nOptional args ERROR, WARN, and NOAUTO: ERROR non-nil means there was an\nerror in reading the file.  WARN non-nil means warn if there\nexists an auto-save file more recent than the visited file.\nNOAUTO means don't mess with auto-save mode.\nFourth arg AFTER-FIND-FILE-FROM-REVERT-BUFFER is ignored\n(see `revert-buffer-in-progress-p' for similar functionality).\nFifth arg NOMODES non-nil means don't alter the file's modes.\nFinishes by calling the functions in `find-file-hook'\nunless NOMODES is non-nil." #<bytecode 0x1b52df>) doom--optimize-for-large-files-a) doom-first-file-hook-h)(nil t)
  apply(#f(advice-wrapper :before #f(advice-wrapper :around #f(compiled-function (&optional error warn noauto after-find-file-from-revert-buffer nomodes) "Called after finding a file and by the default revert function.\nSets buffer mode, parses file-local and directory-local variables.\nOptional args ERROR, WARN, and NOAUTO: ERROR non-nil means there was an\nerror in reading the file.  WARN non-nil means warn if there\nexists an auto-save file more recent than the visited file.\nNOAUTO means don't mess with auto-save mode.\nFourth arg AFTER-FIND-FILE-FROM-REVERT-BUFFER is ignored\n(see `revert-buffer-in-progress-p' for similar functionality).\nFifth arg NOMODES non-nil means don't alter the file's modes.\nFinishes by calling the functions in `find-file-hook'\nunless NOMODES is non-nil." #<bytecode 0x1b52df>) doom--optimize-for-large-files-a) doom-first-file-hook-h) (nil t))
  after-find-file(nil t)
  find-file-noselect-1(#<buffer InstructionalTooltip.js> "~/Code/osom/mirza_webapp/resources/js/elements/InstructionalTooltip.js" nil nil "~/Code/osom/mirza_webapp/resources/js/elements/InstructionalTooltip.js" (26345577 64769))
  find-file-noselect("/home/arandilopez/Code/osom/mirza_webapp/resources/js/elements/InstructionalTooltip.js" nil nil nil)
  find-file("/home/arandilopez/Code/osom/mirza_webapp/resources/js/elements/InstructionalTooltip.js")
  #f(compiled-function (candidate) "Open file CANDIDATE or open helm marked files in separate windows.\nCalled with one prefix arg open files in separate windows in a\nvertical split.\nCalled with two prefix arg open files in background without\nselecting them." #<bytecode 0x144c5ad>)("/home/arandilopez/Code/osom/mirza_webapp/resources/js/elements/InstructionalTooltip.js")
  apply(#f(compiled-function (candidate) "Open file CANDIDATE or open helm marked files in separate windows.\nCalled with one prefix arg open files in separate windows in a\nvertical split.\nCalled with two prefix arg open files in background without\nselecting them." #<bytecode 0x144c5ad>) "/home/arandilopez/Code/osom/mirza_webapp/resources/js/elements/InstructionalTooltip.js")
  helm-find-file-or-marked("/home/arandilopez/Code/osom/mirza_webapp/resources/js/elements/InstructionalTooltip.js")
  helm-execute-selection-action-1()
  helm-execute-selection-action()
  helm-internal((helm-source-projectile-dired-files-list helm-source-projectile-files-list) nil "[mirza_webapp] Find file: " nil nil "*helm projectile: mirza_webapp*" nil nil nil)
  apply(helm-internal ((helm-source-projectile-dired-files-list helm-source-projectile-files-list) nil "[mirza_webapp] Find file: " nil nil "*helm projectile: mirza_webapp*" nil nil nil))
  helm((helm-source-projectile-dired-files-list helm-source-projectile-files-list) nil "[mirza_webapp] Find file: " nil nil "*helm projectile: mirza_webapp*" nil nil nil)
  apply(helm ((helm-source-projectile-dired-files-list helm-source-projectile-files-list) nil "[mirza_webapp] Find file: " nil nil "*helm projectile: mirza_webapp*" nil nil nil))
  helm(:sources (helm-source-projectile-dired-files-list helm-source-projectile-files-list) :buffer "*helm projectile: mirza_webapp*" :truncate-lines nil :prompt "[mirza_webapp] Find file: ")
  helm-projectile-find-file(nil)
  funcall-interactively(helm-projectile-find-file nil)
  call-interactively(helm-projectile-find-file)
  +helm/projectile-find-file()
  funcall-interactively(+helm/projectile-find-file)
  call-interactively(+helm/projectile-find-file nil nil)
  command-execute(+helm/projectile-find-file)
</pre></details>

**Steps to reproduce:**
1. Configure `+lsp` on javascript
2. `doom sync`
3. `npm install -g typescript-language-server`
4. Open a javascript file

**System information:**
<details><pre>
((emacs
  (version . "26.3")
  (features . "XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS LIBSYSTEMD LCMS2")
  (build . "Mar 26, 2020")
  (buildopts "--build x86_64-linux-gnu --prefix=/usr --sharedstatedir=/var/lib --libexecdir=/usr/lib --localstatedir=/var/lib --infodir=/usr/share/info --mandir=/usr/share/man --enable-libsystemd --with-pop=yes --enable-locallisppath=/etc/emacs:/usr/local/share/emacs/26.3/site-lisp:/usr/local/share/emacs/site-lisp:/usr/share/emacs/26.3/site-lisp:/usr/share/emacs/site-lisp --with-sound=alsa --without-gconf --with-mailutils --build x86_64-linux-gnu --prefix=/usr --sharedstatedir=/var/lib --libexecdir=/usr/lib --localstatedir=/var/lib --infodir=/usr/share/info --mandir=/usr/share/man --enable-libsystemd --with-pop=yes --enable-locallisppath=/etc/emacs:/usr/local/share/emacs/26.3/site-lisp:/usr/local/share/emacs/site-lisp:/usr/share/emacs/26.3/site-lisp:/usr/share/emacs/site-lisp --with-sound=alsa --without-gconf --with-mailutils --with-x=yes --with-x-toolkit=gtk3 --with-toolkit-scroll-bars 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/emacs-mEZBk7/emacs-26.3+1=. -fstack-protector-strong -Wformat -Werror=format-security -Wall' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro'")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop 03162466c 2020-08-11 19:22:32 -0400")
  (dir . "~/.doom.d/"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/bin/zsh")
  (uname . "Linux 5.4.0-7634-generic #38~1596560323~20.04~7719dbd-Ubuntu SMP Tue Aug 4 19:12:34 UTC 2 x86_64")
  (path "~/.asdf/shims" "~/.asdf/bin" "/usr/local/bin" "/usr/local/sbin" "~/.dotfiles/bin" "~/.bin" "~/.config/composer/vendor/bin" "~/Android/Sdk/tools" "~/Android/Sdk/tools/bin" "~/Android/Sdk/emulator" "~/Android/Sdk/platform-tools" "~/Android/Sdk/build-tools/28.0.3" "/usr/local/bin" "/usr/local/sbin" "~/.dotfiles/bin" "~/.bin" "~/.config/composer/vendor/bin" "~/Android/Sdk/tools" "~/Android/Sdk/tools/bin" "~/Android/Sdk/emulator" "~/Android/Sdk/platform-tools" "~/Android/Sdk/build-tools/28.0.3" "/usr/local/bin" "/usr/local/sbin" "~/.dotfiles/bin" "~/.bin" "~/.config/composer/vendor/bin" "~/Android/Sdk/tools" "~/Android/Sdk/tools/bin" "~/Android/Sdk/emulator" "~/Android/Sdk/platform-tools" "~/Android/Sdk/build-tools/28.0.3" "~/.local/bin" "/usr/local/sbin" "/usr/local/bin" "/usr/sbin" "/usr/bin" "/sbin" "/bin" "/usr/games" "/usr/local/games" "/snap/bin" "~/.emacs.d/bin" "~/.local/bin" "~/.emacs.d/bin" "~/.local/bin" "~/.emacs.d/bin" "~/.local/bin" "/usr/lib/emacs/26.3/x86_64-linux-gnu"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company (helm +fuzzy) :ui doom doom-dashboard doom-quit hl-todo hydra indent-guides modeline nav-flash ophints (popup +all +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces zen :editor (evil +everywhere) file-templates fold (format +onsave) multiple-cursors rotate-text snippets word-wrap :emacs dired electric ibuffer vc :checkers syntax spell :tools editorconfig (eval +overlay) (lookup +docsets) (lsp +peek) macos magit make pdf rgb :lang (cc +lsp) data (elixir +lsp) emacs-lisp (javascript +lsp) markdown (org +dragndrop +pandoc +present) (php +lsp) (python +lsp +pyright) (ruby +rails +lsp) sh (web +lsp) yaml :config (default +bindings +smartparens))
  (packages (atom-one-dark-theme) (haml-mode) (wakatime-mode) (pomidor) (vue-mode))
  (unpin "n/a")
  (elpa "vue-mode" "vue-html-mode" "ssass-mode" "mmm-mode" "edit-indirect")))
</pre></details>

**Comment by hlissner** [comment]
I cannot reproduce this, nor do I see any issue with your config. Run `doom sync -u && doom build` and see if that resolves your issue.

**Comment by arandilopez** [comment]
> I cannot reproduce this, nor do I see any issue with your config. Run `doom sync -u && doom build` and see if that resolves your issue.

Nope, that didn't work. I will try to read source code to figure out more about this.

**Comment by robbert-vdh** [comment]
I haven't looked into `+javascript-init-lsp-or-tide-maybe-h`, but it may be related to https://github.com/emacs-lsp/lsp-mode/pull/1990. That change also broke all my uses of `(add-next-checker 'lsp ...)` because now lsp-mode's flycheck checker doesn't exist until it gets actually used.

**Comment by arandilopez** [comment]
> I haven't looked into `+javascript-init-lsp-or-tide-maybe-h`, but it may be related to [emacs-lsp/lsp-mode#1990](https://github.com/emacs-lsp/lsp-mode/pull/1990). That change also broke all my uses of `(add-next-checker 'lsp ...)` because now lsp-mode's flycheck checker doesn't exist until it gets actually used.

Well, it seems like that a issue. I downgraded to a previous commit and lsp started the server when opening the file
```elisp
(package! lsp-mode :pin "8e0f3f945e912572653d6d458ed2de428ebe439c")
```

**Comment by arandilopez** [comment]
Well, after reading a little of code in lsp-mode and based on @robbert-vdh comment I found that my issue was in my settings, exactly here:
```elisp
(with-eval-after-load 'lsp-mode
  (mapc #'lsp-flycheck-add-mode '(typescript-mode js-mode css-mode vue-html-mode)))
```

Thanks for your help guys
