### ISSUE TITLE
add a +cleverparens to support evil-cleverparens for lisp like languages

### ISSUE THREAD

**Issue by gozes** [hlissner/doom-emacs#3743]
it be great to to have the an + option to enable evil-cleverparens for lisp like language. this will make editing lisp like language  easier and will provide way less overhead then something like lispy 
https://github.com/luxbock/evil-cleverparens

**Comment by hlissner** [comment]
Hi! Thanks for the suggestion, but as the package can be installed in 2 lines, it is too trivial to warrant its own module or inclusion, so I leave it to users to install:

```elisp
;; in ~/.doom.d/packages.el
(package! evil-cleverparens)

;; in ~/.doom.d/config.el
(add-hook 'lisp-mode-hook #'evil-cleverparens-mode)
```
