### ISSUE TITLE
M-x doom/reload fails

### ISSUE THREAD

**Issue by prashantnag93** [hlissner/doom-emacs#3751]
**What did you expect to happen?**
M-x doom-reload to complete successfully

**What actually happened?**

```
Completion function pcomplete-completions-at-point uses a deprecated calling convention
Comint finished
Eager macro-expansion failure: (void-variable bibtex-completion-find-note-functions) [2 times]
error in process sentinel: let*: Error in a Doom module: "modules/lang/org/config.el", (void-variable bibtex-completion-find-note-functions)
error in process sentinel: Error in a Doom module: "modules/lang/org/config.el", (void-variable bibtex-completion-find-note-functions)
```

**System information:**
<details><pre>
emacs   version    26.3
        features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD LCMS2
        build      Dec 24, 2019
        buildopts  (--build=x86_64-linux-gnu --prefix=/usr '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' --sysconfdir=/etc --localstatedir=/var --disable-silent-rules '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' --disable-maintainer-mode --disable-dependency-tracking --prefix=/usr --sharedstatedir=/var/lib --program-suffix=26 --with-modules --with-file-notification=inotify --with-mailutils --with-x=yes --with-x-toolkit=gtk3 --with-xwidgets --with-lcms2 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/emacs26-XQGPla/emacs26-26.3~1.git96dd019=. -fstack-protector-strong -Wformat -Werror=format-security -no-pie' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro -no-pie')
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop, upstream/develop, upstream/HEAD, origin/develop 702fb6e95 2020-08-14 02:13:37 -0400
        dir        ~/.doom.d/
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/bash
        uname      Linux 5.4.0-44-generic #48-Ubuntu SMP Tue Aug 11 06:38:48 UTC 2020 x86_64
        path       (~/.emacs.d/bin/ ~/.emacs.d/bin/ ~/.emacs.d/bin/ ~/.emacs.d/bin/../bin/../bin/../bin/../bin/../bin/../bin/../bin/../bin/../bin/../bin/../bin/../bin/../bin/../bin/../bin/../bin/../bin/../bin ~/.emacs.d/bin/../bin/../bin/../bin/../bin/../bin/../bin/../bin/../bin/../bin/../bin/../bin/../bin/../bin/../bin/../bin/../bin/../bin ~/.emacs.d/bin/../bin/../bin/../bin/../bin/../bin/../bin/../bin/../bin/../bin/../bin/../bin/../bin/../bin/../bin/../bin/../bin ~/.emacs.d/bin/../bin/../bin/../bin/../bin/../bin/../bin/../bin/../bin/../bin/../bin/../bin/../bin/../bin/../bin/../bin ~/.emacs.d/bin/../bin/../bin/../bin/../bin/../bin/../bin/../bin/../bin/../bin/../bin/../bin/../bin/../bin/../bin ~/.emacs.d/bin/../bin/../bin/../bin/../bin/../bin/../bin/../bin/../bin/../bin/../bin/../bin/../bin/../bin ~/.emacs.d/bin/../bin/../bin/../bin/../bin/../bin/../bin/../bin/../bin/../bin/../bin/../bin/../bin ~/.emacs.d/bin/../bin/../bin/../bin/../bin/../bin/../bin/../bin/../bin/../bin/../bin/../bin ~/.emacs.d/bin/../bin/../bin/../bin/../bin/../bin/../bin/../bin/../bin/../bin/../bin ~/.emacs.d/bin/../bin/../bin/../bin/../bin/../bin/../bin/../bin/../bin/../bin ~/.emacs.d/bin/../bin/../bin/../bin/../bin/../bin/../bin/../bin/../bin ~/.emacs.d/bin/../bin/../bin/../bin/../bin/../bin/../bin/../bin ~/.emacs.d/bin/../bin/../bin/../bin/../bin/../bin/../bin ~/.emacs.d/bin/../bin/../bin/../bin/../bin/../bin ~/.emacs.d/bin/../bin/../bin/../bin/../bin ~/.emacs.d/bin/../bin/../bin/../bin ~/.emacs.d/bin/../bin/../bin ~/.emacs.d/bin/../bin ~/.emacs.d/bin ~/anaconda3/bin ~/anaconda3/condabin ~/.poetry/bin /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /usr/games /usr/local/games /snap/bin /usr/local/texlive/2020/bin/x86_64-linux /usr/local/go/bin /usr/local/texlive/2020/bin/x86_64-linux /usr/lib/x86_64-linux-gnu/emacs/26.3/x86_64-linux-gnu/)
config  envfile    envvar-file
        elc-files  0
        modules    (:desktop exwm :completion (company +auto +childframe) helm (ivy +childframe +prescient +icons +fuzzy) :ui deft doom doom-dashboard doom-quit fill-column hl-todo hydra indent-guides modeline nav-flash ophints (popup +all +defaults) pretty-code treemacs unicode vc-gutter vi-tilde-fringe (window-select +switch-window +numbers) workspaces zen :editor (evil +everywhere) file-templates fold (format +onsave) multiple-cursors rotate-text snippets word-wrap :emacs (dired +ranger +icons) electric (ibuffer +icons) vc :term eshell vterm :checkers (syntax +childframe) :tools direnv (eval +overlay) gist (lookup +docsets +dictionary +offline +wordnet) lsp magit make pass pdf rgb upload :lang (cc +lsp) clojure common-lisp data emacs-lisp ess javascript (latex +latexmk +cdlatex +fold +lsp) ledger markdown (org +dragndrop +pandoc +roam +gnuplot +jupyter +journal +noter +pandoc +present) (python +conda +lsp) scheme sh web :email (mu4e +gmail) :app calendar (rss +org) :config literate (default +bindings +smartparens))
        packages   ((company-org-roam :recipe (:host github :repo jethrokuan/company-org-roam)) (org-roam-bibtex :recipe (:host github :repo org-roam/org-roam-bibtex)) (org-ref) (zotxt) (yasnippet-snippets :recipe (:host github :repo AndreaCrotti/yasnippet-snippets :files (*))) (dired-narrow) (beacon) (org-protocol-capture-html :recipe (:host github :repo alphapapa/org-protocol-capture-html)) (theme-magic) (org-roam-server :recipe (:host github :repo org-roam/org-roam-server :files (*))) (popup-kill-ring) (helm-org-rifle) (org-ref-ox-hugo :recipe (:host github :repo jethrokuan/org-ref-ox-hugo :branch custom/overrides)))
        unpin      (org-roam)
        elpa       (tablist pdf-tools org-pdftools org-noter-pdftools org-noter)
```

</pre></details>

**Comment by hlissner** [comment]
Can you reproduce this in vanilla Doom? i.e. With your config.el commented out and private packages disabled?

**Comment by prashantnag93** [comment]
> Can you reproduce this in [vanilla Doom](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#testing-in-dooms-sandbox)? i.e. Without your private config.

It is successfully in vanilla Doom.

**Comment by hlissner** [comment]
Then the issue is in your private config (in `~/.doom.d`). Doom does not set nor touch `bibtex-completion-find-note-functions` or `bibtex-completion-find-note-functions`. Do you have a link to your private config?

**Comment by prashantnag93** [comment]
It is automatically resolved after doom upgrade. Thank you @hlissner
