### ISSUE TITLE
 Doom installation is successful, but there is no beautiful interface of doom

### ISSUE THREAD

**Issue by kecode** [hlissner/doom-emacs#3753]
➜  .emacs.d git:(develop) ✗ bin/doom sync
> Synchronizing your config with Doom Emacs...
  > Regenerating envvars file at "~/.emacs.d/.local/env"
    - Ignoring PWD=/home/kehenghao/.emacs.d
    - Ignoring GPG_AGENT_INFO=/run/user/1000/gnupg/S.gpg-agent:0:1
    - Ignoring SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
    - Ignoring TERM=xterm-256color
    - Ignoring DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
    - Ignoring HOME=/home/kehenghao
    - Ignoring SSH_AGENT_PID=2068
    ✓ Successfully generated "~/.emacs.d/.local/env"
  > Installing packages...
    - No packages need to be installed
  > (Re)building packages...
    ✓ No packages need rebuilding
  > Purging orphaned packages (for the emperor)...
    - No builds to purge
    - Skipping elpa packages
    - Skipping repos
    - Skipping regrafting
  > (Re)generating autoloads file...
    > Generating autoloads file...
    > Byte-compiling autoloads file...
    ✓ Generated .local/autoloads.elc
  - Restart Emacs or use 'M-x doom/reload' for changes to take effect
✓ Finished! (2.4985s)

emacs alse is The most primitive interface, doom don't work.

➜  .emacs.d git:(develop) ✗ uname -a
Linux kecode 5.0.0-32-generic #34~18.04.2-Ubuntu SMP Thu Oct 10 10:36:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

What should I do? Can you give me some guidance？3q.

**Comment by hlissner** [comment]
https://github.com/hlissner/doom-emacs/blob/develop/docs/faq.org#i-get-the-vanilla-emacs-splash-screen-at-startup
