### ISSUE TITLE
How to disable all-the-icons completely, from modeline, from buffer, from any other packages like neotree

### ISSUE THREAD

**Issue by c02y** [hlissner/doom-emacs#3757]
**Describe the feature**
- If the feature involves new plugins, include links to them
NO
- If the feature involves replacement of current functionality, how the new
  functionality is better?
No replacement
- If the feature is implemented in another editor or Emacs distro, include:
  - Screenshots or screencasts of it
  - Links to its implementation
  - Names of relevant commands (and not only the keybinds to invoke them)

I'm not a fan of a fancy editor, all I need is text, font and color, and considering of performance issue, I tried to avoid icons anywhere in my Emacs/Vim editors, you can treat me like I use Doom Emacs inside terminal, so the fancy fonts and icons are not working inside my terminal, so how can I disable all-the-icons from working completely, I googled and searched inside Github, it seems no one mentioned this topic.

BTW: 

I came from Spacemacs, since Spacemacs has serious performance and weird bugs when editing my code from time to time, so I just tried to install Doom Emacs, and because of my network problem, it failed to install all-the-icons stuff anyway, now my modeline is like the following image(I didn't touch any configuration except enabled some modules), I guess the height and icon in the modeline issues are the problem of lacking of all-the-icons stuff, if it is not, tell me how to fix it, otherwise please tell me how to completely disable all-the-icons since I really don't want it anyway:

![Screenshot_20200815_180128](https://user-images.githubusercontent.com/2135996/90310151-6df66300-df21-11ea-8aad-5f8d25da2a6e.png)

**System information**

```
emacs   version    28.0.50
        features   XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2
        build      Aug 04, 2020
        buildopts  (--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --mandir=/usr/share/man --with-gameuser=:games --with-sound=alsa --with-modules --without-gconf --without-gsettings --with-x-toolkit=gtk3 --without-xaw3d --without-compress-install 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -flto' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now)
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      grafted, HEAD -> develop, origin/develop, origin/HEAD 702fb6e 2020-08-14 02:13:37 -0400
        dir        ~/.doom.d/
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /usr/bin/fish
        uname      Linux 5.7.14-1-MANJARO #1 SMP PREEMPT Fri Aug 7 10:12:32 UTC 2020 x86_64
        path       (~/.local/bin ~/go/bin ~/.npms/bin ~/.cargo/bin /usr/local/bin /bin /sbin /usr/bin /usr/sbin ~/anaconda3/condabin ~/.fzf/bin /usr/local/sbin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /var/lib/snapd/snap/bin /usr/lib/emacs/28.0.50/x86_64-pc-linux-gnu/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo (modeline +light) ophints (popup +defaults) pretty-code vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold (format +onsave) multiple-cursors objed snippets :emacs dired electric undo vc :term eshell :checkers syntax spell :tools ein (eval +overlay) lookup lsp magit :lang (cc +lsp) emacs-lisp (go +lsp) json lua markdown org (python +lsp) (rust +lsp) sh :config (default +bindings +smartparens))
        packages   ((all-the-icons :disable t))
        unpin      (n/a)
        elpa       (n/a)
```
</details>

**Comment by wedens** [comment]
To disable modeline icons, add this in config.el:
```elisp
(after! doom-modeline
  (setq doom-modeline-icon nil))
```

**Comment by c02y** [comment]
> ```emacs-lisp
> (after! doom-modeline
>   (setq doom-modeline-icon nil))
> ```

Thanks for you reply, but what I mean is to disable all-the-icons completely from anywhere, I know how to disable the icon on the doom-modeline since the README file of https://github.com/seagle0128/doom-modeline/ already mentioned it. If I disable the modeline icons, the icons are still there such as in the buffer like **doom** in my image of attachment.

I mean to disable it even from installing.

After reading the whole get-started page and ui modules, it seems doom-dashboard must require it.

**Comment by wedens** [comment]
You can disable a dashboard by commenting the `doom-dashboard` in init.el. I don't think there is an easy way to just disable icons.

You can try doing something like this, if you don't want to remove doom-dashboard:

```lisp
(after! all-the-icons
  (defun my/disable-all-the-icons (&rest args)
    nil)

  (dolist (fn '(all-the-icons-octicon
                all-the-icons-material
                all-the-icons-faicon
                all-the-icons-fileicon
                all-the-icons-wicon
                all-the-icons-alltheicon))
    (advice-add fn :override #'my/disable-all-the-icons)))
```

**Comment by hlissner** [comment]
At the moment there is no clean way to do so. I'm working on moving all-the-icons support out of Doom core, but for the time being you'll need to advise `all-the-icons-*` functions as weden's suggested. 

```elisp
(defadvice! doom--disable-all-the-icons-in-tty-a (&rest _)
  :override '(all-the-icons-octicon all-the-icons-material
              all-the-icons-faicon all-the-icons-fileicon
              all-the-icons-wicon all-the-icons-alltheicon)
  "")
```

This is what Doom does in terminal emacs anyhow.

**Comment by c02y** [comment]
> Plugins like treemacs and neotree have their own, independent configuration. See `SPC h v neo-theme` for neotree and the `treemacs-load-theme` function for treemacs.

I thought they are using all-the-icons, it seems I was wrong, anyhow, I don't use neotree or treemacs at all.

And thanks for you solution.
