### ISSUE TITLE
Cannot toggle line number styles if initially disable it

### ISSUE THREAD

**Issue by nightire** [hlissner/doom-emacs#376]
I put this setting in private module to not display line number after emacs startup:

```elisp
(setq doom-line-numbers-style nil)
```

it works as I expected, however `SPC t l` cannot toggle line number afterwards.

I think `doom-line-numbers-style` implies ppl to *change* the style of line number, but it actually *turn off* the line number completely.

It doesn't make sense to me, or I misused this variable completely?

Another related question is: how to switch to relative line number mode by using `SPC t l`?

**Comment by averrin** [comment]
And maybe its other bug, but if i set it to `'relative` its completely off. Then when i press `spc t l` emacs said "no line numbers plugin found"…

**Comment by tasmo** [comment]
Have exactly the same issue like @averrin.

The space for displaying line number is added but with the buffer's default background and no content.

**Comment by hlissner** [comment]
This was a bug. The fix is now in `develop`. `doom/toggle-line-numbers` now:

+ Cycles through the three styles of line numbers (normal, relative and disabled), starting from `doom-line-numbers-style`'s initial value, and
+ Properly enables the line numbers if `doom-line-numbers-style` is nil.

Let me know if it still gives you trouble!

**Comment by dsdshcym** [comment]
There is a new style for `display-line-numbers-mode`: `visual`, which is basically like `relative` but counts screen lines instead of buffer lines.

**Comment by hlissner** [comment]
Just added support for `visual`, but with a separate variable: `doom-line-numbers-visual-style`. Set this to non-nil, and `display-line-numbers` will use `visual` behind the scenes.

On another note, how new is `visual`? Was that introduced in 26 or 27?

**Comment by dsdshcym** [comment]
It was introduced in 26, basically at the same time as `display-line-numbers`

**Comment by tasmo** [comment]
After pulling the develop branch (Emacs 25.3) and executing `make` I get the following error message:

```shellmake
Deleted old autoloads.el
File mode specification error: (void-function nlinum-relative-on)
```

In my `private/ui/init.el` I have:

```lisp
(setq doom-line-numbers-style 'relative)
```

**Comment by hlissner** [comment]
Ah, my mistake, forgot to update nlinum-relative's autoloads. It is now fixed.
