### ISSUE TITLE
`SPC m d` is bound to dap-hydra in Org Mode

### ISSUE THREAD

**Issue by oakrc** [hlissner/doom-emacs#3760]
**What did you expect to happen?**
Use the `SPC m d` prefix for Org date/deadline commands

**What actually happened?**
`SPC m d` is bound to `(dap-hydra)` instead

**Additional details:**
- [Config](https://github.com/oakrc/dotfiles/blob/master/.doom.d/config.el)
- Screenshot
  
![scrnsh](https://user-images.githubusercontent.com/25710522/90324834-8e75eb80-df28-11ea-8b98-7af846c0fb34.png)

**Steps to reproduce:**
The steps below might work.

1. Open any source code and the LSP server should start automatically (C++ for me)
2. Delete the workspace
3. Wait until the LSP server shutdown message
4. Visit an Org file
5. `SPC m d`

**System information:**
<details><pre>
emacs   version    28.0.50
        features   XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2
        build      Aug 03, 2020
        buildopts  (--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --mandir=/usr/share/man --with-gameuser=:games --with-sound=alsa --with-modules --without-gconf --without-gsettings --with-x-toolkit=gtk3 --without-xaw3d --without-compress-install 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -flto' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now)
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop 9a8fc46c7 2020-08-15 15:13:50 -0400
        dir        ~/.doom.d/
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /usr/bin/fish
        uname      Linux 5.7.12-arch1-1 #1 SMP PREEMPT Fri, 31 Jul 2020 17:38:22 +0000 x86_64
        path       (~/.pyenv/shims ~/.emacs.d/bin/../bin ~/bin ~/bin /usr/local/sbin /usr/local/bin /usr/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl ~/.local/bin ~/.emacs.d/bin/ ~/.gem/ruby/2.7.0/bin ~/.local/bin ~/.emacs.d/bin/ ~/.gem/ruby/2.7.0/bin /usr/lib/emacs/28.0.50/x86_64-pc-linux-gnu/)
config  envfile    envvar-file
        elc-files  0
        modules    (:input chinese japanese :completion company (ivy +fuzzy +icons) :ui deft doom doom-dashboard doom-quit hl-todo minimap modeline ophints (popup +all +defaults) pretty-code tabs treemacs unicode vc-gutter vi-tilde-fringe workspaces zen :editor (evil +everywhere) file-templates fold format multiple-cursors snippets :emacs (dired +icons) electric ibuffer undo vc :term eshell vterm :checkers syntax spell grammar :tools (debugger +lsp) docker ein (eval +overlay) gist (lookup +dictionary +offline) lsp (magit +forge) (pass +auth) pdf rgb tmux :lang (cc +lsp) data emacs-lisp (json +lsp) (java +meghanada) (javascript +lsp) (latex +cdlatex +fold +lsp) ledger (markdown +grip) (org +pretty +present +hugo +noter +dragndrop +journal +jupyter +roam +pomodoro) php (python +lsp +pyenv) qt rust (sh +lsp +fish) web yaml :email (mu4e +gmail) :app calendar irc :config (default +bindings +smartparens))
        packages   ((org-fancy-priorities) (origami) (indium) (org-roam-server) (ascii-art-to-unicode) (org-ref) (org-roam-bibtex) (ivy-bibtex) (parsebib :recipe (:files (*.el))) (nov) (mathpix.el :recipe (:host github :repo jethrokuan/mathpix.el)) (fish-mode) (systemd) (ssh-config-mode) (protobuf-mode) (calctex :recipe (:host github :repo johnbcoughlin/calctex :files (calctex-pkg.el org-calctex/*el calctex*/*el))) (org-tanglesync) (org-projectile) (powershell))
        unpin      (n/a)
        elpa       (n/a)

</pre></details>

**Comment by hlissner** [comment]
As of bf4929f, `SPC m d` will only be available when a debugger is active, which should resolve this issue. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
