### ISSUE TITLE
M-x org-cycle calls different functions in inser-/visual-mode.

### ISSUE THREAD

**Issue by Jonghyun-Yun** [hlissner/doom-emacs#3766]
'org-cycle' in insert-mode calls 'org-metashift', and in visual-mode it calls 'yas-insert-snippet'.
Can you teach me how to make `org-cycle` works as it is?

**Comment by hlissner** [comment]
> in visual-mode it calls 'yas-insert-snippet'.

```elisp
(after! org
  (remove-hook 'org-tab-first-hook #'+org-yas-expand-maybe-h))
```

> 'org-cycle' in insert-mode calls 'org-metashift'

No command called `org-metashift` exists or is bound. Can't help you there.

----

Please divert questions about usage/configuration to [our Discord](https://discord.gg/qvGgnVx). Our issue tracker is not the place for them.
