### ISSUE TITLE
After clicking on ivy-posframe, `ivy-mode-map` is no longer respected.

### ISSUE THREAD

**Issue by snyball** [hlissner/doom-emacs#3769]
**What did you expect to happen?**
For the `ivy-mode-map` to be respected, instead of keys running their regular
evil-bindings inside the window.

**What actually happened?**
After clicking on the window (usually by accident,) the ivy-buffer is being
edited by any keypresses, rather than key-presses being entered into the search
field.

This is especially problematic in Window Managers like SwayWm, where you don't
even have to accidentally click the ivy window when Emacs is open, any press of
the mouse in the general area, in /other/ applications, where ivy pops up causes
the bug (might be an Xwayland issue.)

**Additional details:**
I run a custom fork of `ivy-posframe` with some fixes, but the same behaviour is
observed with stock `ivy-posframe`, can also reproduce when personal
configurations are removed.

In order to revert the `ivy-posframe` buffer back to normal, do the following "revert-recipe":

1. `M-x`
2. Click on Emacs, but outside of the `ivy-posframe` buffer.
3. Press `ESC`
4. `ivy-posframe` now behaves normally.

This issue was not present approx. 9 days ago (when I last updated,) but the
issue is present in the current `HEAD` as of upgrading today.

Correction: The issue where clicking on the `ivy-posframe` window /while open/
causing the mode map curfuffle was present 9 days ago (still have the session
running) but /only/ if the `ivy-posframe-window` is open. What has changed is
that:

1. The change in mappings is persistent, until the "revert-recipe" is followed, previously the issue would not persist in the next posframe to be opened.
2. You only need to click in the general area of the window, even when closed.

Specific commits:

```
  Old revision: 8bbac4bfb3 (9 days ago)
  New revision: 8fa5b9406c (15 hours ago)
```

**Steps to reproduce:**
1. `M-x`
2. Click on `ivy-posframe` window
3. Type ma
4. The buffer is marked
5. Type cl
6. The `ivy` buffer is modified

**System information:**
<details>

```
emacs   version    28.0.50
        features   XPM JPEG TIFF GIF PNG RSVG CAIRO IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES NATIVE_COMP THREADS LIBSYSTEMD JSON PDUMPER LCMS2
        build      aug. 03, 2020
        buildopts  (--prefix=/home/sanoj/.local/opt --with-x-toolkit=gtk3 --with-imagemagick --with-cairo --with-nativecomp --with-xft)
        windowsys  x
        daemonp    daemon
doom    version    2.0.9
        build      HEAD -> develop, origin/develop, origin/HEAD 8fa5b9406 2020-08-16 21:14:50 -0400
        dir        ~/.config/doom/
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /usr/bin/fish
        uname      Linux 5.4.44-1-MANJARO #1 SMP PREEMPT Wed Jun 3 14:48:07 UTC 2020 x86_64
        path       (~/.local/bin ~/.local/share/gem/bin ~/.local/share/cargo/bin ~/.local/go/bin /usr/local/sbin /usr/local/bin /usr/bin ~/.local/opt/bin/ /var/lib/flatpak/exports/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl ~/.local/opt/libexec/emacs/28.0.50/x86_64-pc-linux-gnu)
config  envfile    nil
        elc-files  0
        modules    (:completion (company +childframe) (ivy +childframe +prescient +icons) :ui doom doom-dashboard doom-quit hl-todo modeline popup treemacs unicode vc-gutter window-select workspaces hydra zen ophints :editor (evil +everywhere) file-templates fold lispy multiple-cursors rotate-text snippets :emacs undo (dired +ranger +icons) electric vc :term eshell shell term vterm :checkers (syntax +childframe) (spell +childframe) :tools ein (eval +overlay) gist (lookup +docsets) lsp (magit +forge) make pdf rgb docker :lang (rust +lsp) (cc +lsp) (ruby +lsp) (haskell +intero +lsp) (python +lsp) (java +lsp) (javascript +lsp) lua emacs-lisp scheme ess julia (sh +fish) data latex markdown (org +dragndrop +ipython +pandoc +gnuplot +pretty +roam +present) web yaml json :app calendar :email mu4e :config (default +smartparens))
        packages   ((nginx-mode) (vimrc-mode) (smart-semicolon) (ox-json) (strace-mode) (meson-mode) (pkgbuild-mode) (ssh-config-mode) (string-inflection) (ace-link) (jq-mode) (systemd) (pcre2el) (matrix-client) (hydra-posframe :recipe (:repo https://github.com/Ladicle/hydra-posframe.git)))
        unpin      (n/a)
        elpa       (n/a)
```
</details>

**Comment by hlissner** [comment]
This appears to be an issue with some window managers on Linux. The posframe library [hints to the window environment that its childframes should never receive focus](https://github.com/tumashu/posframe/blob/master/posframe.el#L328), but it is entirely up to the window manager to obey those hints or not. To quote [the documentation on the no-accept-focus frame parameter](https://www.gnu.org/software/emacs/manual/html_node/elisp/Management-Parameters.html#Management-Parameters):

> no-accept-focus
>       If non-nil, this means that the frame does not want to receive input focus via explicit mouse clicks or when moving the mouse into it either via focus-follows-mouse (see Input Focus) or mouse-autoselect-window (see Mouse Window Auto-selection). This may have the unwanted side-effect that a user cannot scroll a non-selected frame with the mouse. **Some window managers may not honor this parameter.**

So unless this is a bug in Emacs itself, or [posframe](https://github.com/tumashu/posframe), our only recourse is to ping the devs of our window managers to respect this hint.

In any case, since this is not an issue with Doom I will close this.

**Comment by snyball** [comment]
For anyone coming across this issue, the [pgtk-nativecomp](https://github.com/fejfighter/emacs/tree/pgtk-nativecomp) fork works well with Wayland.
