### ISSUE TITLE
Transparency so agressive I can barely see anything

### ISSUE THREAD

**Issue by Msouza91** [hlissner/doom-emacs#3771]
I just installed Doom and I cannot use it, tryed setting my xresources tranparency to 1, but it is a GUI application, so as expected it didn't do anything, never had Emacs installed on this machine, I don't know where to start to debug this.
Maybe you can see what I'm talking about here:
![pic-full-200817-2040-01](https://user-images.githubusercontent.com/19522556/90454650-68e11180-e0e3-11ea-9e69-59862796bfa6.png)

**Comment by limaco** [comment]
Perhaps
(set-frame-parameter (selected-frame) 'alpha '(99 . 90))
(add-to-list 'default-frame-alist '(alpha . (99 . 90)))

**Comment by Msouza91** [comment]
> Perhaps
> (set-frame-parameter (selected-frame) 'alpha '(99 . 90))
> (add-to-list 'default-frame-alist '(alpha . (99 . 90)))

I'm a complete noob, where do I set these parameters?

**Comment by limaco** [comment]
in ~/.doom.d/config.el

**Comment by Msouza91** [comment]
> in ~/.doom.d/config.el

I'm starting to think that my instalation borked some way, I don't have a doom command on my path. Do I have to do it manually, where is the script?

**Comment by Msouza91** [comment]
> > in ~/.doom.d/config.el
> 
> I'm starting to think that my instalation borked some way, I don't have a doom command on my path. Do I have to do it manually, where is the script?

I'm an idiot for not finding the doom command, the config you suggested fixed it for me, thanks!

**Comment by limaco** [comment]
Glad to have helped!

**Comment by Msouza91** [comment]
> Glad to have helped!

It is strange because it starts transparent and then the config kicks in... But it works now so, thanks again!

**Comment by limaco** [comment]
it seems that something is messing with your GUI, but I can bet it's not emacs (or Doom) related

**Comment by Msouza91** [comment]
It is probably some weirdness with the compositor, it is unlikely to be doom related, but I can't be bothered rn haha
