### ISSUE TITLE
Upgrade broken with reference to doom-reloading-p

### ISSUE THREAD

**Issue by honuonhval** [hlissner/doom-emacs#3772]
**What did you expect to happen?**
doom upgrade to go as expected

**What actually happened?**
Unexpected error while upgrading

**Additional details:**

<details><pre>
> Preparing to upgrade Doom Emacs and its packages...
- A new version of Doom Emacs is available!

  Old revision: 702fb6e95d (4 days ago)
  New revision: ed25ab76f9 (2 hours ago)

View the comparison diff in your browser? (y or n) y
- Opened github in your browser.
Proceed with upgrade? (y or n) y
> Upgrading Doom Emacs...
  > Cleaning .elc files
    - No elc files to clean
  - From https://github.com/hlissner/doom-emacs
   * branch                develop    -> FETCH_HEAD
   * [new branch]          develop    -> _upgrade/develop
- Reloading Doom Emacs
> Synchronizing your config with Doom Emacs...
  > Installing packages...
    - No packages need to be installed
  > (Re)building packages...
x There was an unexpected error:
  Type: void-variable
  Message:
    Symbol's value as variable is void
  Data:
    doom-reloading-p

Run the command again with the -d (or --debug) switch to enable debug
mode and (hopefully) generate a backtrace from this error:

  doom -d upgrade -p

If you file a bug report, please include it!

</pre></details>

**Steps to reproduce:**
1. run doom upgrade

**System information:**
<details><pre>
((emacs
  (version . "28.0.50")
  (features . "XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES NATIVE_COMP THREADS LIBSYSTEMD JSON PDUMPER LCMS2")
  (build . "Aug 15, 2020")
  (buildopts "--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --mandir=/usr/share/man --with-gameuser=:games --with-sound=alsa --with-modules --without-gconf --without-gsettings --with-nativecomp --with-x-toolkit=gtk3 --without-xaw3d --without-m17n-flt --with-cairo --without-compress-install 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -g -fuse-ld=gold' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now")
  (windowsys . batch)
  (daemonp))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop ed25ab76f 2020-08-18 00:46:41 -0400")
  (dir . "/mnt/synced/setup/doom.d/"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/bin/bash")
  (uname . "Linux 5.8.1-arch1-1 #1 SMP PREEMPT Wed, 12 Aug 2020 18:50:43 +0000 x86_64")
  (path "~/.local/bin" "~/.emacs.d/bin" "~/.rbenv/shims" "~/.nvm/versions/node/v14.8.0/bin" "/usr/local/sbin" "/usr/local/bin" "/usr/bin" "/usr/lib/jvm/default/bin" "/usr/bin/site_perl" "/usr/bin/vendor_perl" "/usr/bin/core_perl" "/usr/lib/emacs/28.0.50/x86_64-pc-linux-gnu"))
 (config
  (envfile)
  (elc-files . 0)
  (modules :completion company ivy :ui deft doom doom-dashboard doom-quit hl-todo modeline ophints (popup +defaults) unicode vc-gutter vi-tilde-fringe (window-select +numbers) workspaces :editor (evil +everywhere) file-templates fold snippets :emacs dired electric undo vc :term vterm :checkers syntax :tools docker (eval +overlay) lookup lsp macos magit make pdf rgb epub :lang (cc +lsp) clojure data emacs-lisp (gdscript +lsp) json (java +lsp) (javascript +lsp) latex markdown (org +hugo +journal +roam +dragndrop +gnuplot +pandoc) plantuml (python +lsp) rest (ruby +rails) (rust +lsp) sh web yaml :app (rss +org) :config (default +bindings +smartparens))
  (packages (modus-operandi-theme) (modus-vivendi-theme))
  (unpin "n/a")
  (elpa "n/a")))

</pre></details>

**Comment by honuonhval** [comment]
I forgot to add that I'm using native-comp (gccemacs)

**Comment by hlissner** [comment]
As of 3d62210 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by honuonhval** [comment]
Still having trouble upgrading

- Debug mode on
> Synchronizing your config with Doom Emacs...

DOOM Initializing package.el
DOOM Initializing straight.el
  > Installing packages...
    - No packages need to be installed
  > (Re)building packages...
x There was an unexpected error:
  Type: void-variable
  Message:
    Symbol's value as variable is void
  Data:
    comp-eln-load-path

Run the command again with the -d (or --debug) switch to enable debug
mode and (hopefully) generate a backtrace from this error:

  doom -d upgrade -p

If you file a bug report, please include it!

**Comment by hlissner** [comment]
Fixed in 58af4ae.

**Comment by honuonhval** [comment]
Thank you! That was amazingly fast
