### ISSUE TITLE
Installation issues 

### ISSUE THREAD

**Issue by mhibti** [hlissner/doom-emacs#3774]
**What did you expect to happen?**
Installation fails.

**What actually happened?**

```
─[17:56]$ ./bin/doom install
Installing Doom Emacs!

> Creating .doom.d/
  ✓ Created .doom.d/
! init.el already exists, skipping
! config.el already exists, skipping
! packages.el already exists, skipping
- Envvar file already exists, skipping
Installing plugins
> Installing packages...
  > Updating recipe repos...
  → Cloning gcmh...pes for emacsmirror-mirror...
x There was an unexpected error:
  Type: doom-package-error
  Message:
    Error with packages
  Data:
    "gcmh"
    (error "Failed to run \"git\"; see buffer *straight-process*")
  Straight output:
    Clonage dans '/home/user/.emacs.d/.local/straight/repos/gcmh'...
    fatal: unable to access 'https://gitlab.com/koral/gcmh.git/': Received HTTP code 503 from proxy after CONNECT
```
    
**System information:**
<details><pre>
(emacs
  (version . "27.1.50")
  (features . "XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GSETTINGS GLIB NOTIFY INOTIFY GNUTLS LIBXML2 FREETYPE HARFBUZZ XFT ZLIB TOOLKIT_SCROLL_BARS GTK2 X11 XDBE XIM MODULES THREADS PDUMPER LCMS2 GMP")
  (build . "août 18, 2020")
  (buildopts "--with-mailutils")
  (windowsys . batch)
  (daemonp))
 (doom
  (version . "2.0.9")
  (build . "grafted, HEAD -> develop, origin/develop, origin/HEAD 58af4ae 2020-08-18 02:51:53 -0400")
  (dir . "~/.doom.d/"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/bin/csh")
  (uname . "Linux 4.9.0-13-amd64 #1 SMP Debian 4.9.228-1 (2020-07-05) x86_64")
  (path "~/.config/emacs/bin" "~/anaconda3/bin" "~/anaconda3/condabin" "~/ePublic/RECHERCHE/PSA-GITLAB/Andromeda/WebApi/Code/lib/jython/bin" "/local00/home/C76950/bin" "~/Public/apache-maven-3.2.3/bin" "~/bin" "/usr/local/bin" "/usr/bin" "/bin" "/usr/local/games" "/usr/games" "/snap/bin" "/usr/local/libexec/emacs/27.1.50/x86_64-pc-linux-gnu"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company helm ivy :ui doom doom-dashboard doom-quit hl-todo ophints (popup +defaults) vc-gutter workspaces zen :editor (evil +everywhere) file-templates fold lispy snippets :emacs dired electric ibuffer undo vc :term term :checkers syntax grammar :tools (eval +overlay) lookup magit :lang emacs-lisp markdown org sh :config (default +bindings +smartparens))
  (packages "n/a")
  (unpin "n/a")
  (elpa "n/a")))

</pre></details>

**Comment by mhibti** [comment]
many individual packages in gitlab seems unreachable

**Comment by hlissner** [comment]
> Received HTTP code 503 from proxy after CONNECT

This appears to be a network issue on your end. Perhaps your proxy has blocked gitlab?

**Comment by mhibti** [comment]
Thanks It seems the case (tried to reach the url in the browser without success)
