### ISSUE TITLE
Evil-shift-width is broken everywhere in a project.

### ISSUE THREAD

**Issue by mmenzyns** [hlissner/doom-emacs#3775]
**What did you expect to happen?**
Tab width being 4 as I think this width is default in Doom, or Doom detecting the rest of the file has tab width of 3, and setting it to 3. Or setting tab size manually in config.el would actually change tab size.

**What actually happened?**
Tab width is 8.

**Additional details:**
- This issue is on completely clean, new and default configuration.
- Enabling editorconfig also doesn't affect tab width, even though the project has editorconfig configuration available.
- Setting `(setq tab-width 3)` and `(setq evil-shift-width 3)` in `config.el` doesn't affect the tab width.
- If `evil-shift-width` is set inside emacs (`set-variable evil-shift-width 3`), this changes the shift width succesfully, but I failed to find a way how to makes this permanent.

**Steps to reproduce:**
1. Clone this repository: https://gitlab.freedesktop.org/mesa
2. In that repository, open any file where tab width can be checked. Preferably a C/C++ file from `src` folder.
3. Try using `<<` and `>>` (`evil-shift-left`, `evil-shift-right`) on a line with a text.
4. Observe how many spaces it shifts.

**System information:**
<details><pre>
emacs   version    26.3
        features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LCMS2
        build      Jan 28, 2020
        buildopts  (--build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-dbus --with-gif --with-jpeg --with-png --with-rsvg --with-tiff --with-xft --with-xpm --with-x-toolkit=gtk3 --with-gpm=no --with-xwidgets --with-modules build_alias=x86_64-redhat-linux-gnu host_alias=x86_64-redhat-linux-gnu 'CFLAGS=-DMAIL_USE_LOCKF -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection' LDFLAGS=-Wl,-z,relro PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig)
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      grafted, HEAD -> develop, origin/develop, origin/HEAD 58af4ae 2020-08-18 02:51:53 -0400
        dir        ~/.doom.d/
system  type       gnu/linux
        config     x86_64-redhat-linux-gnu
        shell      /bin/bash
        uname      Linux 5.7.15-200.fc32.x86_64 #1 SMP Tue Aug 11 16:36:14 UTC 2020 x86_64
        path       (~/.local/bin ~/bin /usr/local/bin /usr/local/sbin /usr/bin /usr/sbin ~/.composer/vendor/bin /var/lib/snapd/snap/bin /usr/libexec/emacs/26.3/x86_64-redhat-linux-gnu/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline ophints (popup +defaults) vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold snippets :emacs dired electric undo vc :checkers syntax :tools (eval +overlay) lookup magit :lang emacs-lisp markdown org sh :config (default +bindings +smartparens))
        packages   (n/a)
        unpin      (n/a)
        elpa       (n/a)
</pre></details>

**Comment by mmenzyns** [comment]
`Guessing offset for /home/mmenzyns/Repositories/mesa/src/gallium/drivers/nouveau/nvc0/nvc0_program.c

Elapsed time for analysis: 0.011 seconds

Total relevant lines: 682 out of 1023 (limit: 2000)

Histogram:

   335x   3 spaces
   204x   6 spaces
   102x   9 spaces
    36x  12 spaces
     5x  15 spaces

Analysis:

  offset 3 works for 100.00% of relevant lines, matching 5 distinct offsets - CONSIDERED
  offset 2 works for  35.19% of relevant lines, matching 2 distinct offsets - merged with offset 6 (0.00% deviation, limit 20.00%)
  offset 6 works for  35.19% of relevant lines, matching 2 distinct offsets - CONSIDERED
  offset 4 works for   5.28% of relevant lines, matching 1 distinct offsets - merged with offset 8 (5.28% deviation, limit 20.00%)
  offset 5 works for   0.73% of relevant lines, matching 1 distinct offsets - CONSIDERED
  offset 7 works for   0.00% of relevant lines, matching 0 distinct offsets - rejected: too few distinct matching offsets (1 required)
  offset 8 works for   0.00% of relevant lines, matching 0 distinct offsets - rejected: too few distinct matching offsets (1 required)

Summary:

  Best guess is offset 3 with 100.00% matching lines (80.00% required)
  Hard tab percentage: 0.00% (0 lines), -100.00% superior to soft tabs (threshold 300.00%)
  Soft tab percentage: 100.00% (682 lines), inf% superior to hard tabs (threshold 300.00%)

Conclusion:

  Guessed offset 3 with 100% confidence.
  Change indent-tab-setting: yes, to nil`

One of the files.

**Comment by aakropotkin** [comment]
I've got this exact same issue, it's driving me nuts.

Do you have a patch for your config?

**Comment by hlissner** [comment]
This is not a Doom bug. The mesa/mesa project, for example, [has a .dir-locals.el file](https://gitlab.freedesktop.org/mesa/mesa/-/blob/master/.dir-locals.el#L4) that hardocdes the tab-width to `8`.
