### ISSUE TITLE
Installing doom in an own HOME should be mentioned in the readme and supported

### ISSUE THREAD

**Issue by triklsbg** [hlissner/doom-emacs#378]
Having a bash alias like:
``
alias doom='HOME=/home/tom1/EMACS/doom emacs &'
``
is one way for me which works so far.

>
DOOM Doctor
Running Emacs v26.0.91, commit 5dacbb7cb1c6ac246a9ccd15e6c4290def67757c

shell: /bin/bash
Compiled with:
  XPM JPEG TIFF GIF PNG RSVG SOUND GPM DBUS GSETTINGS NOTIFY ACL GNUTLS
  LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11
  THREADS LIBSYSTEMD LCMS2
uname -a:
  Linux achse 4.14.15-1-ARCH #1 SMP PREEMPT Tue Jan 23 21:49:25 UTC 2018
  x86_64 GNU/Linux

Attempt to load DOOM: success! Loaded v2.0.9
Revision 5dacbb7cb1c6ac246a9ccd15e6c4290def67757c
>

**Comment by hlissner** [comment]
Why do you need Doom to have its own HOME? 

If it's to isolate it from other Emacs configs, I suggest either:

+ `cd ~/EMACS/doom` and...
  + `make run` or
  + `emacs --eval '(setq user-emacs-directory default-directory)' -q -l init.el` (what `make run` does under the hood)

**Comment by triklsbg** [comment]
Thank you!
