### ISSUE TITLE
[BUG]: sql-indent does not work in sql SRC_BLOCKS in org-mode

### ISSUE THREAD

**Issue by eccentric-j** [hlissner/doom-emacs#3787]
**What did you expect to happen?**
Pressing TAB, = or invoking indent-region while selecting the source block:
```
#+BEGIN_SRC sql
SELECT
  id,
  name
  FROM articles
 WHERE id > 1000
   AND published
 ORDER BY id DESC;
#+END_SRC
```

**What actually happened?**
Pressing TAB, = or invoking indent-region while selecting the source block:
```
#+BEGIN_SRC sql
SELECT
id,
name
FROM articles
WHERE id > 1000
AND published
ORDER BY id DESC;
#+END_SRC
```

![2020-08-19 22 18 16](https://user-images.githubusercontent.com/590297/90718522-1721be00-e280-11ea-9bdb-123fb659aed5.gif)

**Additional details:**
- Investigated the issue pretty thoroughly and found the cause
- Used instructions from https://github.com/alex-hhh/emacs-sql-indent/issues/96 to load emacs without any doom config and loaded sql-indent: worked fine.
- Tried using the latest org-mode: worked fine.
- Enable the org-mode module: BROKEN
- Found culprit 
https://github.com/hlissner/doom-emacs/blob/2c25ffab54bd350074f22dba9649c55c2133800e/modules/lang/org/config.el#L222-L235
- Caused by advice to prevent triggering any major-mode hooks which prevented `sqlind-minor-mode` from firing.

**Temporary solution:**
```emacs-lisp
(after! org
  (advice-remove #'org-src--edit-element #'+org-inhibit-mode-hooks-a))
```
- I understand why the hooks are disabled but it's creating this unexpected behavior so I'm not sure what a better long-term solution would be. What would you recommend?

**Steps to reproduce:**
1. Install sql-indent `(package! sql-indent)` in your packages.el
2. Run `doom sync` then reload or restart doom 
3. Create a new org-mode buffer
4. Create a SQL src-block:
```
#+BEGIN_SRC sql
SELECT
id,
name
FROM articles
WHERE id > 1000
AND published
ORDER BY id DESC;
#+END_SRC
```
5. Select the SQL code within the source block
6. Invoke indent-region. Either from `M-x indent-region`, `TAB`, or `=` in evil normal state

**System information:**
<details><pre>
((emacs
  (version . "28.0.50")
  (features . "JPEG TIFF GIF PNG RSVG IMAGEMAGICK GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS XWIDGETS JSON PDUMPER LCMS2 GMP")
  (build . "Jun 09, 2020")
  (buildopts "--disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus@28/28.0.50/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus@28/28.0.50 --with-xml2 --with-gnutls --without-dbus --with-imagemagick --with-json --with-modules --with-rsvg --without-pop --with-xwidgets --with-ns --disable-ns-self-contained")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "grafted, HEAD -> develop, origin/develop, origin/HEAD ed264dc 2020-08-19 16:39:04 -0400")
  (dir . "~/dotfiles/client/doom.d/"))
 (system
  (type . darwin)
  (config . "x86_64-apple-darwin18.7.0")
  (shell . "/usr/local/bin/fish")
  (uname . "Darwin 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 18 20:50:10 PDT 2020; root:xnu-4903.278.43~1/RELEASE_X86_64 x86_64")
  (path "~/.luarocks/bin" "/usr/local/bin" "~/.emacs.d/bin" "~/.npm-global/bin" "~/bin" "~/.yarn/bin" "~/.config/yarn/global/node_modules/.bin" "/usr/local/bin" "/usr/bin" "/bin" "/usr/sbin" "/sbin" "/usr/local/share/dotnet" "~/.dotnet/tools" "/usr/local/MacGPG2/bin" "/Library/TeX/texbin" "~/.luarocks/bin" "~/.emacs.d/bin" "~/.npm-global/bin" "~/bin" "~/.yarn/bin" "~/.config/yarn/global/node_modules/.bin" "~/.emacs.d/bin/" "/usr/local/Cellar/emacs-plus@28/28.0.50/libexec/emacs/28.0.50/x86_64-apple-darwin18.7.0"))
 (config
  (envfile . envvar-file)
  (elc-files . 173)
  (modules :completion (company +childframe) (ivy +childframe) :ui doom doom-dashboard doom-quit fill-column hl-todo hydra indent-guides modeline ophints (popup +defaults) tabs treemacs vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold lispy multiple-cursors snippets :emacs dired electric undo vc :term vterm :checkers (syntax +childframe) :tools direnv docker editorconfig (eval +overlay) gist lookup lsp macos magit rgb tmux :lang clojure emacs-lisp fennel json (javascript +lsp) markdown (org +journal) (python +lsp) racket sh (web +lsp) yaml :email (wanderlust +gmail) :config (default +bindings +smartparens))
  (packages (anakondo) (evil-lisp-state) (fish-mode) (inf-clojure) (sql-indent))
  (unpin "n/a")
  (elpa "n/a")))
</pre></details>

**Comment by hlissner** [comment]
> I understand why the hooks are disabled but it's creating this unexpected behavior so I'm not sure what a better long-term solution would be. What would you recommend?

Hmm, that's tricky. Perhaps if I modified `+org-inhibit-mode-hooks-a` to trigger a special hook, e.g. `MAJOR-MODE-org-src-hook`, then you could do:

```elisp
(add-hook 'sql-mode-org-src-hook #'sql-indent-mode)
```

Edited version of the advise:

```elisp
(defadvice! +org-inhibit-mode-hooks-a (orig-fn datum name &optional initialize &rest args)
  "Prevent potentially expensive mode hooks in `org-babel-do-in-edit-buffer' ops."
  :around #'org-src--edit-element
  (apply orig-fn datum name
         (if (and (eq org-src-window-setup 'switch-invisibly)
                  (functionp initialize))
             ;; org-babel-do-in-edit-buffer is used to execute quick, one-off
             ;; logic in the context of another major mode. Initializing this
             ;; major mode can be terribly expensive (particular its mode
             ;; hooks), so we inhibit them.
             (lambda ()
               (prog1 (quiet! (delay-mode-hooks (funcall initialize)))
                 (unless (eq major-mode 'fundamental-mode)
                   (run-hooks (intern-soft (format "%s-org-src-hook" major-mode))))))
           initialize)
         args))
```

**Comment by eccentric-j** [comment]
Wow that's a pretty good idea! I'll try that tomorrow and confirm it.

Unfortunately it's an atypical case because the maintainer of the official
sql-mode does not like the sql-indent indentation and so will not merge it
upstream. Thus it will have to remain a separate package for the
foreseeable future.

This solution seems solid though and would be flexible for other issues
like this should they arise. I can't think of any major drawbacks other
than requiring additional configuration... but then again the advice-remove
call is also additional configuration with a bigger performance penalty.

**Comment by hlissner** [comment]
I've decided to go with a slightly different approach:

The advice will now only inhibit `MAJOR-MODE-local-vars-hook` functions. This is a Doom-specific hook that runs after `MAJOR-MODE-hook`, and is where Doom conventionally places all a mode's most expensive functions. This should solve the original problem the advice was meant to solve (#3660) and your issue as well.

Let me know if that isn't the case and I'll reopen this. Thanks for bringing it to my attention!
