### ISSUE TITLE
Setting popup rules for eldoc makes it not recognize that an eldoc buffer is active

### ISSUE THREAD

**Issue by NightMachinary** [hlissner/doom-emacs#3789]
**Steps to reproduce:**
1. Add `(set-popup-rule! "^\\*eldoc.*\\*$" :ttl 60 :height 0.3 :width 0.3 :side 'right)` to config.
2. Now press `SPC h .` on a symbol to raise the eldoc buffer.
3. Move point on another symbol. Now there are both an active eldoc buffer and eldoc in the minibuffer:
![image](https://user-images.githubusercontent.com/36224762/90774766-3adf1580-e30d-11ea-8af2-523dcd01b4fc.png)

Eldoc should obviously not be active in the minibuffer.

**System information:**
<details><pre>
((emacs
  (version . "27.1")
  (features . "RSVG IMAGEMAGICK GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS XWIDGETS PDUMPER LCMS2 GMP")
  (build . "Aug 18, 2020")
  (buildopts "--disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus@27/27.1/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus@27/27.1 --with-xml2 --with-gnutls --without-dbus --with-imagemagick --with-modules --with-rsvg --with-xwidgets --with-ns --disable-ns-self-contained")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop 702fb6e95 2020-08-14 02:13:37 -0400")
  (dir . "~/doom.d/"))
 (system
  (type . darwin)
  (config . "x86_64-apple-darwin19.0.0")
  (shell . "/usr/local/bin/zsh")
  (uname . "Darwin 19.0.0 Darwin Kernel Version 19.0.0: Wed Sep 25 20:18:50 PDT 2019; root:xnu-6153.11.26~2/RELEASE_X86_64 x86_64")
  (path "~/.nix-profile/bin" "/myBin/" "~/scripts//zsh/wrappers/Zath.app/Contents/Resources/MainMenu.nib/" "~/scripts//zsh/wrappers/Zath.app/Contents/Resources/" "~/scripts//zsh/wrappers/Zath.app/Contents/MacOS/" "~/scripts//zsh/wrappers/Zath.app/Contents/" "~/scripts//zsh/wrappers/Zath.app/" "~/scripts//zsh/wrappers/" "~/scripts//zsh/rss-notifier/" "~/scripts//zsh/personal/" "~/scripts//zsh/interactive/fuzzy/" "~/scripts//zsh/interactive/" "~/scripts//zsh/fattened/" "~/scripts//zsh/fastsyntax/" "~/scripts//zsh/expensive/" "~/scripts//zsh/exorbitant/" "~/scripts//zsh/ensure-run/" "~/scripts//zsh/bugs/" "~/scripts//zsh/basic/auto-load/" "~/scripts//zsh/basic/" "~/scripts//zsh/auto-load/tests/" "~/scripts//zsh/auto-load/others/clojure/" "~/scripts//zsh/auto-load/others/" "~/scripts//zsh/auto-load/bugs/" "~/scripts//zsh/auto-load/" "~/scripts//zsh/aria2-helpers/" "~/scripts//zsh/" "~/scripts//sh/" "~/scripts//setup/" "~/scripts//rust/archive/" "~/scripts//rust/" "~/scripts//ruby/" "~/scripts//resources/luna/" "~/scripts//resources/audio/" "~/scripts//resources/" "~/scripts//python/xonsh/" "~/scripts//python/url-encode/" "~/scripts//python/telegram-send/__pycache__/" "~/scripts//python/telegram-send/" "~/scripts//python/tecast/" "~/scripts//python/ipython/" "~/scripts//python/gmail/" "~/scripts//python/genRSS/" "~/scripts//python/autogui/" "~/scripts//python/aria2/" "~/scripts//python/" "~/scripts//launchers/" "~/scripts//javascript/" "~/scripts//export/" "~/scripts//deactivated-launchers/" "~/scripts//dash/" "~/scripts//configFiles/handbrake/" "~/scripts//configFiles/" "~/scripts//clojure/" "~/scripts//bin/" "~/scripts//bash/personal/" "~/scripts//bash/examples/" "~/scripts//bash/auto-load/" "~/scripts//bash/" "~/scripts//applescript/chrome/" "~/scripts//applescript/" "~/scripts//DOOMDIR=~/doom.d/" "~/scripts//DOOMDIR=~/" "~/scripts//" "/usr/local/opt/curl/bin" "/usr/local/opt/qt/bin" "/Library/Java/JavaVirtualMachines/openjdk.jdk/Contents/Home" "~/bin" "~/miniconda3/bin/" "~/anaconda/bin/" "~/.nimble/bin" "~/.poetry/bin" "~/.gem/bin" "/usr/libexec/" "~/kscripts/" "/usr/local/opt/texinfo/bin" "~/go/bin" "/Base/- Code/Resources/" "~/.local/bin" "/usr/local/sbin" "/usr/local/bin" "/snap/bin" "~/.cargo/bin" "/Library/TeX/texbin" "~/.dotnet/tools" "~/.emacs.d.doom/bin/" "~/code/node/snips-alice" "/Applications/SuperCollider.app/Contents/MacOS/" "/Applications/SuperCollider.app/Contents/Resources/" "/usr/sbin" "/usr/bin" "/bin" "/sbin" "~/Library/Caches/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-unixorn-SLASH-git-extra-commands/bin" "~/Library/Caches/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-unixorn-SLASH-git-extra-commands/bin" "/usr/local/Cellar/emacs-plus@27/27.1/libexec/emacs/27.1/x86_64-apple-darwin19.0.0"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion (company +tng) (ivy +fuzzy +icons) :ui doom doom-dashboard hl-todo hydra indent-guides modeline nav-flash ophints (popup +defaults) unicode vc-gutter vi-tilde-fringe :editor (evil +everywhere) file-templates fold snippets word-wrap :emacs dired electric undo vc :term vterm :checkers syntax :tools (eval +overlay) gist (lookup +dictionary +docsets +offline) macos magit pdf :lang clojure coq data emacs-lisp json javascript julia lua markdown (org +dragndrop +pandoc +gnuplot +jupyter +noter +present +roam) raku racket rst (ruby +rails) rust scala sh yaml :config (default +bindings))
  (packages (solarized-theme) (zoom) (blacken) (elpy) (pyvenv) (lispyville) (google-translate) (move-text) (rg) (deadgrep) (git-link) (neuron-mode) (nov) (hungry-delete) (ob-tmux) (julia-mode) (julia-repl) (eglot) (eglot-jl))
  (unpin julia-mode julia-repl)
  (elpa "n/a")))
</pre></details>

**Comment by hlissner** [comment]
`eglot` recently changes its "lookup documentation" strategy from "open documentation is a popup buffer" to "forcibly trigger eldoc", which has been problematic. I've tried to ride that wave and instead open the eldoc buffer in a popup, but this turned out dreadfully buggy due to eldoc's asynchronous nature, i.e. it's difficult to predict when its contents are changed -- and it is changed often.

Anyhow, I've reimplemented eglot's `eglot-help-at-point` in 9e9b95f49. This should fix your issue (by side-stepping eldoc entirely). Let me know if that isn't the case and I'll reopen the issue. Thank you for bringing it to my attention.
