### ISSUE TITLE
In case of an own HOME installation the additional fonts are not found? by fc-cache

### ISSUE THREAD

**Issue by triklsbg** [hlissner/doom-emacs#379]
message buffer shows:
``
Successfully installed ‘all-the-icons’ fonts to ‘/home/tom1/EMACS/doom/.local/share/fonts/’!
``
the running instance of doom finds them aka displays them but i'm not sure if this is a in general useful location for the fonts. I copied them to REALHOME/.local/share/fonts and did an <fc-cache -v -f>.
Results in:
>
tom1 ~ $ fc-list | grep octi --->
/home/tom1/.local/share/fonts/octicons.ttf: github\-octicons:style=Regular
tom1 ~ $ 
>
>
DOOM Doctor
Running Emacs v26.0.91, commit 5dacbb7cb1c6ac246a9ccd15e6c4290def67757c

shell: /bin/bash
Compiled with:
  XPM JPEG TIFF GIF PNG RSVG SOUND GPM DBUS GSETTINGS NOTIFY ACL GNUTLS
  LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11
  THREADS LIBSYSTEMD LCMS2
uname -a:
  Linux achse 4.14.15-1-ARCH #1 SMP PREEMPT Tue Jan 23 21:49:25 UTC 2018
  x86_64 GNU/Linux

Attempt to load DOOM: success! Loaded v2.0.9
Revision 5dacbb7cb1c6ac246a9ccd15e6c4290def67757c
>

**Comment by hlissner** [comment]
Judging from #378, you've got a different $HOME. That's the issue here. `all-the-icons` determines where to install the fonts using this code (which is out of my control):

```emacs-lisp
(cl-case window-system
  (x  (concat (or (getenv "XDG_DATA_HOME")            ;; Default Linux install directories
                  (concat (getenv "HOME") "/.local/share"))
              "/fonts/"))
  (mac (concat (getenv "HOME") "/Library/Fonts/" ))
  (ns (concat (getenv "HOME") "/Library/Fonts/" )))
```

You could try setting `XDG_DATA_HOME`, in your shell or in emacs (eg. `(setenv "XDG_DATA_HOME" "/home/tom1/.local/share")`).
