### ISSUE TITLE
Problems when running org-beamer-export-to-pdf

### ISSUE THREAD

**Issue by lmiekina** [hlissner/doom-emacs#3794]
**What did you expect to happen?**
...
The org-mode file should first be converted to a tex file and then to pdf

**What actually happened?**
...
The org-mode file is converted to a tex file, but no pdf is produced. The error message is displayed: Symbol's function definition is void: letf.

**Additional details:**
[doom.zip](https://github.com/hlissner/doom-emacs/files/5104171/doom.zip)

- I used both SPC m e l P and M-x org-beamer-export-to-pdf

I recently changed my OS from NixOS to Ubuntu 20.04. Under NixOS it was working, with a slightly older version.
I subsequently can manually produce pdf, with the command 'pdflatex  -synctex=1 -shell-escape Git.tex'.

- Include any warnings or errors logged to \*Messages\* (use `M-x
  view-echo-area-messages` to see it).

<details><pre>
Loading /etc/emacs/site-start.d/00debian.el (source)...done
Loading /etc/emacs/site-start.d/50asymptote.el (source)...done
Loading /etc/emacs/site-start.d/50dictionaries-common.el (source)...
Loading debian-ispell...
Loading /var/cache/dictionaries-common/emacsen-ispell-default.el (source)...done
Loading debian-ispell...done
Loading /var/cache/dictionaries-common/emacsen-ispell-dicts.el (source)...done
Loading /etc/emacs/site-start.d/50dictionaries-common.el (source)...done
Loading /etc/emacs/site-start.d/50erlang-mode.el (source)...done
Loading /etc/emacs/site-start.d/50latex-cjk-common.el (source)...
Loading /usr/share/emacs/site-lisp/latex-cjk-common/cjk-enc.el (source)...done
Loading /etc/emacs/site-start.d/50latex-cjk-common.el (source)...done
Loading /etc/emacs/site-start.d/50latex-cjk-thai.el (source)...done
Loading /etc/emacs/site-start.d/50latexmk.el (source)...done
Loading /etc/emacs/site-start.d/50texlive-lang-english.el (source)...done
Doom loaded 176 packages across 40 modules in 1.333s
Loading /home/lm/.emacs.d/.local/cache/recentf...done
Automatic display of crossref information was turned on
Applying style hooks...
Restarting server
Loading /home/lm/.emacs.d/.local/straight/build/auctex/style/inputenc.elc...done
Loading /home/lm/.emacs.d/.local/straight/build/auctex/style/fontenc.elc...done
Loading /home/lm/.emacs.d/.local/straight/build/auctex/style/graphicx.elc...done
Loading /home/lm/.emacs.d/.local/straight/build/auctex/style/longtable.elc...done
Loading /home/lm/.emacs.d/.local/straight/build/auctex/style/wrapfig.elc...done
Loading /home/lm/.emacs.d/.local/straight/build/auctex/style/ulem.elc...done
Loading /home/lm/.emacs.d/.local/straight/build/auctex/style/amsmath.elc...done
Loading /home/lm/.emacs.d/.local/straight/build/auctex/style/amstext.elc...done
Loading /home/lm/.emacs.d/.local/straight/build/auctex/style/amsbsy.elc...done
Loading /home/lm/.emacs.d/.local/straight/build/auctex/style/amsopn.elc...done
Loading /home/lm/.emacs.d/.local/straight/build/auctex/style/textcomp.elc...done
Loading /home/lm/.emacs.d/.local/straight/build/auctex/style/amssymb.elc...done
Loading /home/lm/.emacs.d/.local/straight/build/auctex/style/amsfonts.elc...done
Loading /home/lm/.emacs.d/.local/straight/build/auctex/style/hyperref.elc...done
Loading /home/lm/.emacs.d/.local/straight/build/auctex/style/url.elc...done
Loading /home/lm/.emacs.d/.local/straight/build/auctex/style/nameref.elc...done
Loading /home/lm/.emacs.d/.local/straight/build/auctex/style/listings.elc...done
Loading /home/lm/.emacs.d/.local/straight/build/auctex/style/color.elc...done
Applying style hooks...done
Wrote /home/lm/Documents/Informatyka/Wyklad-POIO/Git/Test.tex
save-excursion: Symbol’s function definition is void: letf
Mark set
</pre></details>

**Steps to reproduce:**
1. Load a file Test.org
2. Press SPC m e l P

**System information:**
<details><pre>

```
emacs   version    26.3
        features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS LIBSYSTEMD LCMS2
        build      mar 26, 2020
        buildopts  (--build x86_64-linux-gnu --prefix=/usr --sharedstatedir=/var/lib --libexecdir=/usr/lib --localstatedir=/var/lib --infodir=/usr/share/info --mandir=/usr/share/man --enable-libsystemd --with-pop=yes --enable-locallisppath=/etc/emacs:/usr/local/share/emacs/26.3/site-lisp:/usr/local/share/emacs/site-lisp:/usr/share/emacs/26.3/site-lisp:/usr/share/emacs/site-lisp --with-sound=alsa --without-gconf --with-mailutils --build x86_64-linux-gnu --prefix=/usr --sharedstatedir=/var/lib --libexecdir=/usr/lib --localstatedir=/var/lib --infodir=/usr/share/info --mandir=/usr/share/man --enable-libsystemd --with-pop=yes --enable-locallisppath=/etc/emacs:/usr/local/share/emacs/26.3/site-lisp:/usr/local/share/emacs/site-lisp:/usr/share/emacs/26.3/site-lisp:/usr/share/emacs/site-lisp --with-sound=alsa --without-gconf --with-mailutils --with-x=yes --with-x-toolkit=gtk3 --with-toolkit-scroll-bars 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/emacs-mEZBk7/emacs-26.3+1=. -fstack-protector-strong -Wformat -Werror=format-security -Wall' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro')
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      grafted, HEAD -> develop, origin/develop, origin/HEAD f6f90c97 2020-08-20 03:54:44 -0400
        dir        ~/.doom.d/
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/bash
        uname      Linux 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64
        path       (~/bin/kotlin-language-server-master/server/build/install/server/bin ~/.emacs.d/bin/ ~/bin /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /usr/games /usr/local/games /snap/bin /usr/lib/emacs/26.3/x86_64-linux-gnu/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces zen :editor (evil +everywhere) file-templates fold multiple-cursors rotate-text snippets word-wrap :emacs dired electric ibuffer vc :term eshell :tools (eval +overlay) :checkers syntax :tools (lookup +docsets) magit make pdf :lang data emacs-lisp latex (org +dragndrop +present) sh :config (default +bindings +smartparens))
        packages   ((lsp-treemacs))
        unpin      (n/a)
        elpa       (n/a)
```
</pre></details>

**Comment by hlissner** [comment]
The issue is in your config.el: you have two `letf` calls on lines 142 and 220. Unless you load the (deprecated) `cl` library, Emacs renamed `letf` to `cl-letf` in 26.x. So change your `letf` calls to `cl-letf`.

-----

For future reference, the _full_ error message should have save something like:

```
Error in private config: config.el, (void-function letf)
```

The `Error in private config: config.el` tells you where to look.

Hope that helps.
