### ISSUE TITLE
Doom fail to init with emacs-27.1

### ISSUE THREAD

**Issue by ncihnegn** [hlissner/doom-emacs#3800]
**What actually happened?**
```
[emacs-27.1] doom sync
Installing straight...
Cloning use-package...
Cloning use-package...done
Building use-package...
Building use-package → Building bind-key...
Building use-package → Building bind-key...done
Building use-package...
use-package.el:0:0: error: file-error: (Getting attributes Too many levels of symbolic links /home/ncihnegn/.emacs.d/.local/straight/build/use-package/use-package.el)
```
```
[emacs-27.1] doom info                                                 
Building use-package...
Getting attributes: Too many levels of symbolic links, /home/ncihnegn/.emacs.d/.local/straight/build/use-package/use-package-bind-key.el
```
**Additional details:**
<details><pre>
If an error message is involved include a backtrace of it.

How to acquire a backtrace:
https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#how-to-extract-a-backtrace-from-an-error
</pre></details>

**System information:**
<details><pre>
OS: CentOS 6.1
emacs: 27.1 built from source
works fine with 26.3 built from source

</pre></details>

**Comment by hlissner** [comment]
Try this:

1. Delete `~/.emacs.d/.local/straight` manually, 
2. Make sure Doom is up-to-date (run `git -C ~/.emacs.d pull`),
3. Run `doom sync`

I'm not entirely sure how straight could cause a circular symlink. I've never seen this before.

**Comment by ncihnegn** [comment]
This is an Emacs issue. Only on RHEL 6.
