### ISSUE TITLE
Can't redo w/ C-r

### ISSUE THREAD

**Issue by ncihnegn** [hlissner/doom-emacs#3808]
**What did you expect to happen?**
C-r for redo

**What actually happened?**

Error message when editing a long .tex file

Works fine on a new file on Fundamental mode
Same error on a new .c file

Try removing config.el but the error persists.

**Additional details:**

<details><pre>
C-r bound to undo-fu-only-redo

Message: command-execute: Wrong type argument: commandp, redo
</pre></details>

**Steps to reproduce:**
1. enter some texts
2. u to undo
3. C-r to redo

**System information:**
<details><pre>
emacs   version    27.1
        features   NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS JSON PDUMPER GMP
        build      Aug 16, 2020
        buildopts  (--enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacsmac/8.0_1/share/info/emacs --prefix=/usr/local/Cellar/emacsmac/8.0_1 --with-mac --enable-mac-app=/usr/local/Cellar/emacsmac/8.0_1 --with-gnutls --with-json)
        windowsys  mac
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop, origin/develop, origin/HEAD 4bc70a853 2020-08-18 20:32:34 -0400
        dir        ~/.doom.d/
system  type       darwin
        config     x86_64-apple-darwin19.6.0
        shell      /bin/zsh
        uname      Darwin 19.6.0 Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64
        path       (~/.local/bin /usr/local/sbin /usr/local/Cellar/emacsmac/8.0_1/libexec/emacs/27.1/x86_64-apple-darwin19.6.0/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard hl-todo modeline nav-flash ophints (popup +defaults) pretty-code vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold format snippets :emacs dired electric undo vc :checkers syntax spell :tools (debugger +lsp) ein (eval +overlay) (lookup +docsets) lsp macos magit :lang agda (cc +lsp) clojure coq csharp data (dart +flutter) elixir elm emacs-lisp erlang ess fsharp fstar (haskell +lsp) idris (javascript +lsp) json julia kotlin latex lean lua markdown nim nix ocaml org purescript (python +lsp) racket (ruby +rails) (rust +lsp) scala scheme sh sml swift web yaml :config (default +bindings +smartparens))
        packages   ((agda-input :pin 8eb0d01811) (agda2-mode :pin 8eb0d01811) (graphviz-dot-mode) (groovy-mode) (cmm-mode) (counsel-gtags) (flycheck-haskell) (ggtags) (helm-gtags) (helm-hoogle) (hlint-refactor) (ormolu) (vimrc-mode))
        unpin      (n/a)
        elpa       (graphviz-dot-mode)

;;; .doom.d/config.el -*- lexical-binding: t; -*-

;; Place your private configuration here
(if (display-graphic-p)
    (toggle-scroll-bar -1))

(setq confirm-kill-emacs nil)

(setq doom-font (font-spec :family "Ligalex Mono" :size 12 :weight 'Regular)
      doom-unicode-font (font-spec :family "DejaVu Sans Mono"))

(if (eq window-system 'mac) ;; mac port
    (mac-auto-operator-composition-mode t))

(setq evil-ex-search-case 'sensitive)

(use-package! agda2-mode
  :defer t
  :config
  (setq agda2-program-name "stack-agda"))

(use-package! cc-mode
  :defer t
  :config
  (setq c-basic-offset 2))

(use-package! ccls
  :after cc-mode
  :config
  (setq ccls-sem-highlight-method 'font-lock)
  (ccls-use-default-rainbow-sem-highlight)
  (when IS-MAC
    (setq ccls-initialization-options
          '(:compilationDatabaseDirectory "build" ;;))))
            :clang (:extraArgs ["-isystem/usr/local/include"
                                "-isystem/Library/Developer/CommandLineTools/usr/include/c++/v1"
                                "-isystem/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include"
                                ]
                    :resourceDir "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.3")))))

(use-package! dash-docs
  :defer t
  :config
  (set-docsets! 'c-mode "C")
  (set-docsets! 'cpp-mode "C++")
  (set-docsets! 'rust-mode "Rust"))

(use-package! dired
  :defer t
  :config
  (when (eq system-type 'darwin)
    (setq dired-use-ls-dired nil)))

(use-package! geiser-mode
  :defer t
  :config
  (setq geiser-default-implementation 'chez))

(use-package! graphviz-dot-mode
  :config
  (setq graphviz-dot-indent-width 2))

(use-package! company-graphviz-dot)

(use-package! groovy-mode
  :defer t
  :mode "\\.groovy\\'")

(use-package! lsp-mode
  :defer t
  :config
  (dolist (dir '(
                 "[/\\\\]\\.ccls-cache$"
                 "[/\\\\]\\build$"
                 "[/\\\\]\\cmake-build-debug$"
                 "[/\\\\]\\cmake-build-release$"
                 "[/\\\\]\\CMakeFiles$"
                 ))
    (push dir lsp-file-watch-ignored)))

(use-package! org
  :defer t
  :config
  (add-hook 'org-mode-hook (lambda ()
                             "Beautify Org Checkbox Symbol"
                             (push '("[ ]" .  "☐") prettify-symbols-alist)
                             (push '("[X]" . "☑" ) prettify-symbols-alist)
                             (push '("[-]" . "❍" ) prettify-symbols-alist)
                             (prettify-symbols-mode)))
  (add-hook 'org-mode-hook 'turn-off-auto-fill)
  (add-hook 'org-mode-hook 'turn-on-visual-line-mode)
  (defun sacha/org-html-checkbox (checkbox)
    "Format CHECKBOX into HTML."
    (case checkbox (on "<span class=\"check\">&#x2611;</span>") ; checkbox (checked)
          (off "<span class=\"checkbox\">&#x2610;</span>")
          (trans "<code>[-]</code>")
          (t "")))
  (defadvice org-html-checkbox (around sacha activate)
    (setq ad-return-value (sacha/org-html-checkbox (ad-get-arg 0)))))

(after! haskell-mode
  (map! :localleader
        :map haskell-mode-map
        "f" #'ormolu-format-buffer
        "h" #'hoogle
        "H" #'haskell-hoogle-lookup-from-local
        "r" #'hlint-refactor-refactor-at-point
        "R" #'hlint-refactor-refactor-buffer))

(use-package! vimrc-mode
  :mode "\\.vim[rc]?\\'"
  :mode "_vimrc\\'")

Messages post-startup
Doom loaded 355 packages across 73 modules in 4.678s [2 times]
</pre></details>

**Comment by ncihnegn** [comment]
I find it depends on how I open the file:
* If I open emacs then open the file, C-r is working fine;
* If I open the file on command line, C-r is broken.
```
$ emacs test.c
```
My alias
```
emacs=/Applications/Emacs.app/Contents/MacOS/Emacs.sh
```

**Comment by peterhoeg** [comment]
I was noticing this as well. The quick workaround:

```elisp
(map!
 (:when (not (featurep! :emacs undo +tree))
  :n "C-r" #'undo-fu-only-redo))
```

**Comment by hlissner** [comment]
Sorry for the late response, this should be resolved now that evil has changed its undo abstraction. Let me know if that isn't the case and I'll reopen this. Thanks for bringing it to my attention!
