### ISSUE TITLE
Autoload fails to create the +default/browse-* functions

### ISSUE THREAD

**Issue by jcrono** [hlissner/doom-emacs#381]
### Observed behavior

All the `+default/browse-` functions fails.

for example trying to execute `+default/browse-project` fails with:
`Autoloading failed to define function +default/browse-project`

However that also creates the function: `default/browse-project` (without the `+`) that works as expected.

### Expected behavior

I expect the `+` variants to work directly.

### Steps to reproduce

1. Run any of the `+defualt/browse-` functions,

I think there might be an issue with the macro `+default--def-browse-in!` That creates those functions. 

I wish I could be more useful but I am honestly new to elisp and I cant quite understand how the marco works. 

### System information

<details>
<summary>Click to expand</summary>

```
DOOM Doctor
Running Emacs v25.3.1, commit 84218386d88111d7447324b7157cd5c9159bc77f

shell: /bin/zsh
Compiled with:
  XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS
  NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB
  TOOLKIT_SCROLL_BARS GTK3 X11 MODULES
uname -a:
  Linux Ki 4.14.15-1-ARCH #1 SMP PREEMPT Tue Jan 23 21:49:25 UTC 2018
  x86_64 GNU/Linux

Attempt to load DOOM: success! Loaded v2.0.9
Revision 84218386d88111d7447324b7157cd5c9159bc77f

----

test-emacs
test-windows
test-fonts
Found font material-design-icons.ttf
Found font weathericons.ttf
Found font octicons.ttf
Found font fontawesome.ttf
Found font file-icons.ttf
Found font all-the-icons.ttf
test-gnutls
test-tls
Validated https://elpa.gnu.org
Validated https://melpa.org
Successfully rejected https://self-signed.badssl.com
Successfully rejected https://wrong.host.badssl.com/
test-tar
Everything seems fine, happy Emacs’ing!

```
</details>

**Comment by jcrono** [comment]
After trying for a few more minutes I found the issue:

on the `+default--def-browse-in!` marco definition in line 14 of the modules/private/autoload/default.el:

`(format "%s/browse-%s" prefix name)` should be `(format "+%s/browse-%s" prefix name)`

Found out by comparing to the next marco on the same file.

**Comment by hlissner** [comment]
Good catch! I've pushed a fix to `develop`. I'll leave this open until it hits `master`. Thanks for letting me know!
