### ISSUE TITLE
`envrc` breaks `ob-jupyter`

### ISSUE THREAD

**Issue by lccambiaghi** [hlissner/doom-emacs#3812]
In the switch from `direnv` to `envrc` I lost the ability to run `jupyter-python` source blocks. 

I suspect it is because `ob-jupyter` tries to execute `jupyter kernelspec list` to retrieve available jupyter kernels. When using `direnv`, the command is successfully executed in the virtual environment. With the new `envrc`, the command gets executed in the "global python" and fails.

For now I solved it by switching back to `direnv` but it would be nice to get it to work :)

**Comment by hlissner** [comment]
As of 6444662 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by lccambiaghi** [comment]
Unfortunately it does not fix the issue for me!

**Comment by hlissner** [comment]
How about:

```elisp
;; add to ~/.doom.d/config.el
(require 'envrc)
(remove-hook 'change-major-mode-after-body-hook #'+direnv-init-h)
(envrc-global-mode +1)
```

**Comment by hlissner** [comment]
Nevermind that suggestion, it won't work. Give this a try instead:

```elisp
;; add to ~/.doom.d/config.el
(defvar +direnv--old-process-environment nil)
(defadvice! +direnv--persist-environment-in-org-babel-execution-a (orig-fn &rest args)
  :around #'org-babel-execute-src-block
  (if +direnv--old-process-environment
      (apply orig-fn args)
    (setq-default +direnv--old-process-environment (default-value 'process-environment)
                  process-environment process-environment)
    (unwind-protect (apply orig-fn args)
      (setq-default process-environment +direnv--old-process-environment
                    +direnv--old-process-environment nil))))
```

**Comment by lccambiaghi** [comment]
Yes, that worked! Thanks a lot!!

**Comment by hlissner** [comment]
Great! I'll push this upstream soon. I'll leave this open until I have.
