### ISSUE TITLE
Consider making spell-fu package optional

### ISSUE THREAD

**Issue by mskorzhinskiy** [hlissner/doom-emacs#3813]
I would like to request making spell-fu as an optional package, not as a single-choice option. The major reason of this is that spell-fu is still relatively fresh package with a lot of rough edges. For my case I have two unavoidable problems:

1. This package do not support dictionaries with affix expansion. Making it practically unusable for any language with it. (e.g. German or Russian)
2. This package do not support multi-languages dictionaries. E.g. "en_GB,ru_RU" will do spell check buffer for both English and Russian. This doesn't work with spell-fu.

I can prepare a pull request if you agree. A flag that will switch from spell-fu back to flyspell default checker. For example two flags: +spellfu and +flyspell. The same as in +ispell +hunspell.

**Comment by hlissner** [comment]
I've add a `+flyspell` flag to the `:checkers spell` module in e3750db, so I'll consider this resolved. Let me know if it causes any issues and I'll reopen this.
