### ISSUE TITLE
`0r` Doesn't Filter ALL in Org Mode TODO

### ISSUE THREAD

**Issue by typkrft** [hlissner/doom-emacs#3818]
**What did you expect to happen?**
... 1r 2r 3r 4r 5r ETC - All Filter their expected keywords, however when I type `0r` it does not set the ALL Filter. Instead if i type any number greater than 11 and press r which is an unlisted filter it returns to ALL. 

**Additional details:**
I have not changed any configs and this is a brand new install of emacs. This also happens with emacs-plus  both installed with brew. This happens in Terminal Emacs and GUI Emacs.

Key Bindings
evil-org-agenda-mode-map <motion-state> K
org-agenda-keymap +
org-agenda-keymap <S-up>
org-agenda-keymap C-c C-x <up>
org-agenda-mode-map +
org-agenda-mode-map <S-up>
org-agenda-mode-map C-c C-x <up>

```shell
Installation: 
$ brew install emacs-plus
$ git clone --depth 1 https://github.com/hlissner/doom-emacs ~/.emacs.d
$ cd .emacs.d
$ git checkout develop # Already in Develop
$ cd bin
$ ./doom install
$ ./doom sync # Not Sure if Needed before first run
$ ./doom doctor # Just curious 
> Checking your enabled modules...
  > :emacs dired
    ! Cannot find gls (GNU ls). This may cause issues with dired
  > :lang markdown
    ! Couldn't find a markdown compiler, `markdown-preview' won't work
  > :lang sh
    ! Couldn't find shellcheck. Shell script linting will not work
$ emacs
``` 

Nothing in the shown in debug, except that it is rebuilding....done, but the filter doesn't change.  

Removing .emacs.d and then running `emacs` works as expected. 

**System information:**
<detail>

```
((emacs
  (version . "27.1")
  (features . "RSVG IMAGEMAGICK GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS PDUMPER LCMS2 GMP")
  (build . "Aug 24, 2020")
  (buildopts "--disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus@27/27.1/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus@27/27.1 --with-xml2 --with-gnutls --without-dbus --with-imagemagick --with-modules --with-rsvg --with-ns --disable-ns-self-contained")
  (windowsys . batch)
  (daemonp))
 (doom
  (version . "2.0.9")
  (build . "grafted, HEAD -> develop, origin/develop, origin/HEAD e3750db 2020-08-23 18:48:50 -0400")
  (dir . "~/.doom.d/"))
 (system
  (type . darwin)
  (config . "x86_64-apple-darwin19.6.0")
  (shell . "/bin/zsh")
  (uname . "Darwin 19.6.0 Darwin Kernel Version 19.6.0: Sun Jul  5 00:43:10 PDT 2020; root:xnu-6153.141.1~9/RELEASE_X86_64 x86_64")
  (path "~/.zplug/bin" "~/Library/Python/3.8/bin" "~/.config/bin" "/usr/local/sbin" "~/.cargo/bin" "/usr/local/bin" "/usr/bin" "/bin" "/usr/sbin" "/sbin" "~/.zplug/repos/zpm-zsh/colorize/bin" "/usr/local/opt/fzf/bin" "/usr/local/Cellar/emacs-plus@27/27.1/libexec/emacs/27.1/x86_64-apple-darwin19.6.0"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline ophints (popup +defaults) vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold snippets :emacs dired electric undo vc :checkers syntax :tools (eval +overlay) lookup magit :os macos :lang emacs-lisp markdown org sh :config (default +bindings +smartparens))
  (packages "n/a")
  (unpin "n/a")
  (elpa "n/a")))
```

</details>

**Comment by typkrft** [comment]
I was just looking at https://github.com/Somelauw/evil-org-mode/blob/master/doc/keythemes.org

Could it be that Evil Org Mode binds 0 as the beginning of the line like in vim? Sorry I'm completely new to lisp and emacs, is there away I can either temporarily disable evil-org-mode or its keybindings, or is it possible to disable keybindings on a selected buffer? Also could be completely way off.

**Comment by Nsidorenco** [comment]
Evil rebinds 0 to begging of line. 

If you want to to type an actual 0 in normal mode you can use the universal argument (`spc u 0`)

**Comment by typkrft** [comment]
Yeah, that's what I saw when I was reading the the documentation. I think I'm just going to create a function to rebind that keybinding on that buffer if I can find a good hook to do so. Personally I have no need to go to the beg of a line on that buffer. I didn't know about `spc u 0` though so thanks for that.

**Comment by hlissner** [comment]
The issue was upstream, in evil-org. As of d4e34c7 `0` will be the digit argument if the cursor is already at BOL, and will go to BOL otherwise. With that, this can be considered resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
