### ISSUE TITLE
File local-variables error: (doom-hook-error lsp! (void-variable flyspell-delayed-commands))

### ISSUE THREAD

**Issue by cxb811201** [hlissner/doom-emacs#3827]
**What actually happened?**
File local-variables error: (doom-hook-error lsp! (void-variable flyspell-delayed-commands))

<details><pre>
Debugger entered--Lisp error: (void-variable flyspell-delayed-commands)
  #f(compiled-function () #<bytecode 0x1da5a70c1b05ff09>)()
  funcall(#f(compiled-function () #<bytecode 0x1da5a70c1b05ff09>))
  mapc(funcall (#f(compiled-function () #<bytecode 0x1da5a70c1b05ff09>)))
  do-after-load-evaluation("/home/chenxianbin/.emacs.d/modules/checkers/spell/...")
  load-with-code-conversion("/home/chenxianbin/.emacs.d/modules/checkers/spell/..." "/home/chenxianbin/.emacs.d/modules/checkers/spell/..." nil t)
  (set-flyspell-predicate! '(markdown-mode gfm-mode) #'+markdown-flyspell-word-p)
  (progn (set-flyspell-predicate! '(markdown-mode gfm-mode) #'+markdown-flyspell-word-p) (set-lookup-handlers! '(markdown-mode gfm-mode) :file '(markdown-follow-thing-at-point :async t)) (sp-local-pair '(markdown-mode gfm-mode) "`" "`" :unless '(:add sp-point-before-word-p sp-point-before-same-p)) (progn (defalias 'doom--setq-fill-nobreak-predicate-for-markdown-mode-h #'(lambda (&rest _) "fill-nobreak-predicate = (cons #'markdown-code-blo..." (set (make-local-variable 'fill-nobreak-predicate) (cons #'markdown-code-block-at-point-p fill-nobreak-predicate)))) (remove-hook 'markdown-mode-hook #'doom--setq-fill-nobreak-predicate-for-markdown-mode-h) (add-hook 'markdown-mode-hook #'doom--setq-fill-nobreak-predicate-for-markdown-mode-h)) (progn (defalias '+markdown-disable-front-matter-fontification-a #'(lambda (&rest _) (ignore (goto-char (point-max))))) (let ((--dolist-tail-- (list (cons :override (doom-enlist ...))))) (while --dolist-tail-- (let ((targets (car --dolist-tail--))) (let ((--dolist-tail-- ...)) (while --dolist-tail-- (let ... ... ...))) (setq --dolist-tail-- (cdr --dolist-tail--)))))) (progn (general-define-key :major-modes t :prefix doom-localleader-alt-key :keymaps '(markdown-mode-map) "'" #'markdown-edit-code-block "o" #'markdown-open "p" #'markdown-preview "e" #'markdown-export) (if t (progn (general-define-key :major-modes t :prefix doom-localleader-alt-key :keymaps '(markdown-mode-map) "p" #'grip-mode))) (general-define-key :major-modes t :prefix doom-localleader-alt-key :keymaps '(markdown-mode-map) :infix "i" "" (list :ignore t :which-key "insert") "t" #'markdown-toc-generate-toc "i" #'markdown-insert-image "l" #'markdown-insert-link)) t)
  (closure (t) nil (progn (set-flyspell-predicate! '(markdown-mode gfm-mode) #'+markdown-flyspell-word-p) (set-lookup-handlers! '(markdown-mode gfm-mode) :file '(markdown-follow-thing-at-point :async t)) (sp-local-pair '(markdown-mode gfm-mode) "`" "`" :unless '(:add sp-point-before-word-p sp-point-before-same-p)) (progn (defalias 'doom--setq-fill-nobreak-predicate-for-markdown-mode-h #'(lambda (&rest _) "fill-nobreak-predicate = (cons #'markdown-code-blo..." (set (make-local-variable ...) (cons ... fill-nobreak-predicate)))) (remove-hook 'markdown-mode-hook #'doom--setq-fill-nobreak-predicate-for-markdown-mode-h) (add-hook 'markdown-mode-hook #'doom--setq-fill-nobreak-predicate-for-markdown-mode-h)) (progn (defalias '+markdown-disable-front-matter-fontification-a #'(lambda (&rest _) (ignore (goto-char ...)))) (let ((--dolist-tail-- (list (cons :override ...)))) (while --dolist-tail-- (let ((targets ...)) (let (...) (while --dolist-tail-- ...)) (setq --dolist-tail-- (cdr --dolist-tail--)))))) (progn (general-define-key :major-modes t :prefix doom-localleader-alt-key :keymaps '(markdown-mode-map) "'" #'markdown-edit-code-block "o" #'markdown-open "p" #'markdown-preview "e" #'markdown-export) (if t (progn (general-define-key :major-modes t :prefix doom-localleader-alt-key :keymaps '(markdown-mode-map) "p" #'grip-mode))) (general-define-key :major-modes t :prefix doom-localleader-alt-key :keymaps '(markdown-mode-map) :infix "i" "" (list :ignore t :which-key "insert") "t" #'markdown-toc-generate-toc "i" #'markdown-insert-image "l" #'markdown-insert-link)) t))()
  eval-after-load-helper("/home/chenxianbin/.emacs.d/.local/straight/build/m...")
  run-hook-with-args(eval-after-load-helper "/home/chenxianbin/.emacs.d/.local/straight/build/m...")
  do-after-load-evaluation("/home/chenxianbin/.emacs.d/.local/straight/build/m...")
  require(markdown-mode)
  byte-code("\300\301!\210\300\302!\210\300\303!\210\300\304!\210\300\305!\210\300\306!\210\300\307!\210\300\310!\210\300\311!\210\300\312!\210\300\313!\210\300\314!\210\300\315..." [require bindat cl-generic cl-lib compile dash dash-functional ewoc f filenotify files ht imenu inline json lv markdown-mode network-stream pcase rx s seq spinner subr-x tree-widget url-parse url-util widget xref minibuffer yasnippet nil t lsp-protocol] 4)
  (lsp-deferred)
  (if (and (boundp 'lsp-mode) lsp-mode) nil (lsp-deferred))
  (if nil (eglot-ensure) (if (and (boundp 'lsp-mode) lsp-mode) nil (lsp-deferred)))
  lsp!()
  #<subr funcall-interactively>(lsp!)
  apply(#<subr funcall-interactively> lsp!)
  funcall-interactively(lsp!)
  #<subr call-interactively>(lsp! record nil)
  apply(#<subr call-interactively> (lsp! record nil))
  explain-pause--wrap-call-interactively(#<subr call-interactively> lsp! record nil)
  apply(explain-pause--wrap-call-interactively #<subr call-interactively> (lsp! record nil))
  call-interactively(lsp! record nil)
  command-execute(lsp! record)
  counsel-M-x-action("lsp!")
  #f(compiled-function (x) #<bytecode -0x1cb26585754cd23>)("lsp!")
  ivy-call()
  #f(compiled-function (arg1 arg2 &rest rest) "Read a string in the minibuffer, with completion.\n\nPROMPT is a string, normally ending in a colon and a space.\n`ivy-count-format' is prepended to PROMPT during completion.\n\nCOLLECTION is either a list of strings, a function, an alist, or\na hash table, supplied for `minibuffer-completion-table'.\n\nPREDICATE is applied to filter out the COLLECTION immediately.\nThis argument is for compatibility with `completing-read'.\n\nWhen REQUIRE-MATCH is non-nil, only members of COLLECTION can be\nselected.\n\nIf INITIAL-INPUT is non-nil, then insert that input in the\nminibuffer initially.\n\nHISTORY is a name of a variable to hold the completion session\nhistory.\n\nKEYMAP is composed with `ivy-minibuffer-map'.\n\nPRESELECT, when non-nil, determines which one of the candidates\nmatching INITIAL-INPUT to select initially.  An integer stands\nfor the position of the desired candidate in the collection,\ncounting from zero.  Otherwise, use the first occurrence of\nPRESELECT in the collection.  Comparison is first done with\n`equal'.  If that fails, and when applicable, match PRESELECT as\na regular expression.\n\nDEF is for compatibility with `completing-read'.\n\nUPDATE-FN is called each time the candidate list is re-displayed.\n\nWhen SORT is non-nil, `ivy-sort-functions-alist' determines how\nto sort candidates before displaying them.\n\nACTION is a function to call after selecting a candidate.\nIt takes one argument, the selected candidate. If COLLECTION is\nan alist, the argument is a cons cell, otherwise it's a string.\n\nMULTI-ACTION, when non-nil, is called instead of ACTION when\nthere are marked candidates. It takes the list of candidates as\nits only argument. When it's nil, ACTION is called on each marked\ncandidate.\n\nUNWIND is a function of no arguments to call before exiting.\n\nRE-BUILDER is a function transforming input text into a regex\npattern.\n\nMATCHER is a function which can override how candidates are\nfiltered based on user input.  It takes a regex pattern and a\nlist of candidates, and returns the list of matching candidates.\n\nDYNAMIC-COLLECTION is a boolean specifying whether the list of\ncandidates is updated after each input by calling COLLECTION.\n\nEXTRA-PROPS is a plist that can be used to store\ncollection-specific session-specific data.\n\nCALLER is a symbol to uniquely identify the caller to `ivy-read'.\nIt is used, along with COLLECTION, to determine which\ncustomizations apply to the current completion session." #<bytecode 0x13ea6a63bebf452f>)("M-x " ("lsp!" "global-command-log-mode" "command-log-mode" "revert-buffer" "vterm-module-compile" "pdf-tools-install" "lsp-install-server" "lsp-treemacs-java-deps-list" "browse-url" "+fold/close" "doom/window-maximize-buffer" "hl-line-mode" "solaire-mode" "avy-goto-line" "+fold/open-all" "global-hl-line-mode" "toggle-debug-on-error" "calc" "calendar" "dap-hydra" "protobuf-mode" "+fold/previous" "fundamental-mode" "insert-kbd-macro" "browse-url-chrome" "proxy-http-enable" "proxy-http-toggle" "org-mark-ring-goto" "name-last-kbd-macro" "lsp-treemacs-symbols" "lsp-treemacs-errors-list" "cd" "5x5" "amx" "arp" "dbx" "dig" "erc" "ert" "eww" "ftp" "gdb" "irc" "jdb" "lsp" "man" "mpc" "pdb" "pwd" "rsh" ...) :predicate #f(compiled-function (x) #<bytecode 0xa2bde741cbf48f>) :require-match t :history counsel-M-x-history :action counsel-M-x-action :keymap (keymap (67108908 . counsel--info-lookup-symbol) (67108910 . counsel-find-symbol)) :initial-input nil :caller counsel-M-x :sort t)
  apply(#f(compiled-function (arg1 arg2 &rest rest) "Read a string in the minibuffer, with completion.\n\nPROMPT is a string, normally ending in a colon and a space.\n`ivy-count-format' is prepended to PROMPT during completion.\n\nCOLLECTION is either a list of strings, a function, an alist, or\na hash table, supplied for `minibuffer-completion-table'.\n\nPREDICATE is applied to filter out the COLLECTION immediately.\nThis argument is for compatibility with `completing-read'.\n\nWhen REQUIRE-MATCH is non-nil, only members of COLLECTION can be\nselected.\n\nIf INITIAL-INPUT is non-nil, then insert that input in the\nminibuffer initially.\n\nHISTORY is a name of a variable to hold the completion session\nhistory.\n\nKEYMAP is composed with `ivy-minibuffer-map'.\n\nPRESELECT, when non-nil, determines which one of the candidates\nmatching INITIAL-INPUT to select initially.  An integer stands\nfor the position of the desired candidate in the collection,\ncounting from zero.  Otherwise, use the first occurrence of\nPRESELECT in the collection.  Comparison is first done with\n`equal'.  If that fails, and when applicable, match PRESELECT as\na regular expression.\n\nDEF is for compatibility with `completing-read'.\n\nUPDATE-FN is called each time the candidate list is re-displayed.\n\nWhen SORT is non-nil, `ivy-sort-functions-alist' determines how\nto sort candidates before displaying them.\n\nACTION is a function to call after selecting a candidate.\nIt takes one argument, the selected candidate. If COLLECTION is\nan alist, the argument is a cons cell, otherwise it's a string.\n\nMULTI-ACTION, when non-nil, is called instead of ACTION when\nthere are marked candidates. It takes the list of candidates as\nits only argument. When it's nil, ACTION is called on each marked\ncandidate.\n\nUNWIND is a function of no arguments to call before exiting.\n\nRE-BUILDER is a function transforming input text into a regex\npattern.\n\nMATCHER is a function which can override how candidates are\nfiltered based on user input.  It takes a regex pattern and a\nlist of candidates, and returns the list of matching candidates.\n\nDYNAMIC-COLLECTION is a boolean specifying whether the list of\ncandidates is updated after each input by calling COLLECTION.\n\nEXTRA-PROPS is a plist that can be used to store\ncollection-specific session-specific data.\n\nCALLER is a symbol to uniquely identify the caller to `ivy-read'.\nIt is used, along with COLLECTION, to determine which\ncustomizations apply to the current completion session." #<bytecode 0x13ea6a63bebf452f>) ("M-x " ("lsp!" "global-command-log-mode" "command-log-mode" "revert-buffer" "vterm-module-compile" "pdf-tools-install" "lsp-install-server" "lsp-treemacs-java-deps-list" "browse-url" "+fold/close" "doom/window-maximize-buffer" "hl-line-mode" "solaire-mode" "avy-goto-line" "+fold/open-all" "global-hl-line-mode" "toggle-debug-on-error" "calc" "calendar" "dap-hydra" "protobuf-mode" "+fold/previous" "fundamental-mode" "insert-kbd-macro" "browse-url-chrome" "proxy-http-enable" "proxy-http-toggle" "org-mark-ring-goto" "name-last-kbd-macro" "lsp-treemacs-symbols" "lsp-treemacs-errors-list" "cd" "5x5" "amx" "arp" "dbx" "dig" "erc" "ert" "eww" "ftp" "gdb" "irc" "jdb" "lsp" "man" "mpc" "pdb" "pwd" "rsh" ...) :predicate #f(compiled-function (x) #<bytecode 0xa2bde741cbf48f>) :require-match t :history counsel-M-x-history :action counsel-M-x-action :keymap (keymap (67108908 . counsel--info-lookup-symbol) (67108910 . counsel-find-symbol)) :initial-input nil :caller counsel-M-x :sort t))
  ivy-read("M-x " ("lsp!" "global-command-log-mode" "command-log-mode" "revert-buffer" "vterm-module-compile" "pdf-tools-install" "lsp-install-server" "lsp-treemacs-java-deps-list" "browse-url" "+fold/close" "doom/window-maximize-buffer" "hl-line-mode" "solaire-mode" "avy-goto-line" "+fold/open-all" "global-hl-line-mode" "toggle-debug-on-error" "calc" "calendar" "dap-hydra" "protobuf-mode" "+fold/previous" "fundamental-mode" "insert-kbd-macro" "browse-url-chrome" "proxy-http-enable" "proxy-http-toggle" "org-mark-ring-goto" "name-last-kbd-macro" "lsp-treemacs-symbols" "lsp-treemacs-errors-list" "cd" "5x5" "amx" "arp" "dbx" "dig" "erc" "ert" "eww" "ftp" "gdb" "irc" "jdb" "lsp" "man" "mpc" "pdb" "pwd" "rsh" ...) :predicate #f(compiled-function (x) #<bytecode 0xa2bde741cbf48f>) :require-match t :history counsel-M-x-history :action counsel-M-x-action :keymap (keymap (67108908 . counsel--info-lookup-symbol) (67108910 . counsel-find-symbol)) :initial-input nil :caller counsel-M-x)
  counsel-M-x()
  #<subr funcall-interactively>(counsel-M-x)
  apply(#<subr funcall-interactively> counsel-M-x)
  funcall-interactively(counsel-M-x)
  #<subr call-interactively>(counsel-M-x nil nil)
  apply(#<subr call-interactively> (counsel-M-x nil nil))
  explain-pause--wrap-call-interactively(#<subr call-interactively> counsel-M-x nil nil)
  apply(explain-pause--wrap-call-interactively #<subr call-interactively> (counsel-M-x nil nil))
  call-interactively(counsel-M-x nil nil)
  command-execute(counsel-M-x)
</pre></details>

**System information:**
<details><pre>
((system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/usr/bin/zsh")
  (uname . "Linux 5.8.3 #1 SMP PREEMPT Mon Aug 24 11:07:52 CST 2020 x86_64")
  (path "~/.gem/ruby/2.6.0/bin" "~/.go/bin" "~/.cargo/bin" "~/.jenv/shims" "~/.jenv/bin" "~/.local/share/coursier/bin" "~/.emacs.d/bin" "~/.local/bin" "~/.nvm/versions/node/v13.12.0/bin" "/usr/local/bin" "/usr/local/sbin" "/usr/bin" "/usr/lib/jvm/default/bin" "/usr/bin/site_perl" "/usr/bin/vendor_perl" "/usr/bin/core_perl" "~/.antigen/bundles/robbyrussell/oh-my-zsh/lib" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/git" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/gitfast" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/colored-man-pages" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/history" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/z" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/extract" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/encode64" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/web-search" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/urltools" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/tmux" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/docker" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/docker-compose" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/archlinux" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/cargo" "~/.antigen/bundles/djui/alias-tips" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/mvn" "~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/sbt" "~/.antigen/bundles/zdharma/fast-syntax-highlighting" "~/.antigen/bundles/zsh-users/zsh-autosuggestions" "~/.antigen/bundles/hlissner/zsh-autopair" "~/.antigen/bundles/romkatv/powerlevel10k" "/usr/lib/emacs/28.0.50/x86_64-pc-linux-gnu"))
 (emacs
  (dir . "~/.emacs.d/")
  (version . "28.0.50")
  (build . "Aug 25, 2020")
  (buildopts . "--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --mandir=/usr/share/man --with-gameuser=:games --with-sound=alsa --with-modules --without-gconf --without-gsettings --with-x-toolkit=gtk3 --without-xaw3d --with-xwidgets --without-compress-install 'CFLAGS=-march=ivybridge -O2 -pipe -fno-plt -flto' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now")
  (features . "XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER LCMS2")
  (traits batch))
 (doom
  (dir . "~/.doom.d/")
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD 0dfee56e3 2020-08-24 23:22:57 -0400")
  (elc-files . 0)
  (modules :completion (company +childframe) (ivy +prescient +fuzzy +icons) :ui doom doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) treemacs vc-gutter window-select workspaces :editor file-templates fold format multiple-cursors snippets word-wrap :emacs dired electric (ibuffer +icons) undo vc :term vterm :checkers (syntax +childframe) (spell +aspell) :tools (debugger +lsp) docker editorconfig (eval +overlay) lookup (lsp +peek) magit make pdf :lang data emacs-lisp (go +lsp) json (java +lsp) (javascript +lsp) (markdown +grip) (org +dragndrop +hugo +pandoc +present +pomodoro +journal +pretty) plantuml rest (scala +lsp) sh (web +lsp) yaml :config (default +bindings +smartparens) :my (&user chinese +childframe) (&user ui) (&user editor) (&user calendar) (&user dired) (&user magit) (&user translate +childframe) (&user tools) (&user debugger) (&user lsp) (&user markdown) (&user plantuml) (&user protobuf) (&user go) (&user java +google-java-format) (&user scala) (&user sql) (&user keybindings))
  (packages "n/a")
  (unpin
   (:ui doom)
   (:lang java))
  (elpa "n/a")))
</pre></details>

**Comment by innerout** [comment]
I can confirm this behavior in my configuration too.

**Comment by hlissner** [comment]
Enable the `+flyspell` flag on `:checkers spell`.

flyspell was replaced with spell-fu a few days ago and is now gated behind this flag. It's likely you're referring to `flyspell-delayed-commands` somewhere in your config.

**Comment by innerout** [comment]
Although I have upgraded doom to the latest commit and I added in init.el `(spell +flyspell)`  but the error is still printed.

**Comment by hlissner** [comment]
Ah, found the issue. I've fixed it in bfd71a8. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by zackteo** [comment]
Yeap the fix works for me!
