### ISSUE TITLE
org-download-clipboard

### ISSUE THREAD

**Issue by gksbrandon** [hlissner/doom-emacs#3830]
https://github.com/abo-abo/org-download

Hi everyone, I believe this has been implemented in the original package already, can we get it on doom emacs?

Makes it easier on the workflow, saving screenshots to clipboard and just loading from there is more convenient than having to be in emacs to invoke the org-capture-screenshot command.

Thanks!

**Comment by hlissner** [comment]
As of bdbeb8f `org-download-clipboar` is now bound to `SPC m a p` in org-mode.
