### ISSUE TITLE
bin/doom: line 7: [: : integer expression expected

### ISSUE THREAD

**Issue by zzamboni** [hlissner/doom-emacs#3831]
**What actually happened?**

`bin/doom` has started producing the following error every time it runs:
```
/Users/taazadi1/.emacs.d/bin/doom: line 7: [: : integer expression expected
```

**Additional details:**
- I think this was introduced by commit 63a03848a3e026498c2e25348b2288ccca2f7ad8, since it was not happening before.

**Steps to reproduce:**
1. Run `doom`

**Comment by hlissner** [comment]
As of 239516a this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
