### ISSUE TITLE
It'd Be Extremely Cool If Doom Had A Notarised Binary For macOS!

### ISSUE THREAD

**Issue by Ezirius** [hlissner/doom-emacs#3832]
**We need a binary, a notarised binary, for macOS, please.**

This is very important in a era where security is and needs to be foremost in our minds. The lack of a notarised binary will deter people from trying the application and hinder adoption. Neither Homebrew nor MacPorts, although easy installation mechanisms, are **secure and thus safe** installation mechanisms.

**Comment by shanesveller** [comment]
This sounds like a responsibility for Emacs itself, notarizing a shell script (for the `doom` CLI) doesn't sound like a constructive use of time or energy.

**Comment by tecosaur** [comment]
Prompted by Shane's comment, I feel the need to add: this is something that Emacs should do far more than Doom. My comment is intended as: "if this is possible without too much hassle, it might be nice"

**Comment by ymarco** [comment]
If I've understood correctly, it should be possible to use pdump to create an emacs binary with all the doom packages loaded. (Though I have zero experience in this and I'm not sure it'd work on Mac). But is it a good idea? One of the nice promises doom is the package management and the doom cli tool.

**Comment by ymarco** [comment]
Actually, a self-updating binary could be cool. Since all the doom 'framework' would be packed into the binary I don't see what would stop it from updating and recompiling a new version of itself.

**Comment by hlissner** [comment]
While it's a cool idea, there are too many obstacles. I don't think it's practical. I'm not an apple developer and all I have is a shaky mojave vm to do any testing on.

I'm open to working _with_ an apple dev to figure something out, but my macOS know-how is a decade out of date, and I am not interested in refreshing it. A greater issue here is that Emacs itself isn't notarized (or signed?). That is definitely their jurisdiction more than mine.

Here are some other concerns:

+ Licensing: Doom is MIT. Emacs and its plugins are (mostly) GPL. I can't statically link GPLed code without conforming to the GPL myself, and I do not plan to change Doom's license.
+ If emacs isn't signed, can you notarize a container that uses it? Doom's binary would never pass the validation process. What about all the shared libraries Emacs depends on? Jansson, harfbuzz, gnutls, openssl, etc. How thorough is the notarizing process? What do I become responsible for, bundling all this together?
+ I don't know what kind of restrictions a "hardened runtime" is subject to. Documentation on the matter is vague. For something as complex as Emacs, this could introduce a whole class of bugs I'm not prepared to support.
+ Great effort is needed to restructure Doom for portability. It just isn't built for that. Emacs bytecode isn't portable. Its plugins sometimes bake in absolute paths when compiled at installation. 

   Another minor issur: Emacs is stubborn about where it reads its init files from. i.e. `~/.emacs`, `~/.emacs.d` or `~/.config/emacs` (as of Emacs 27.1). A Doom binary would have to deploy a bootloader to the user's $HOME, or suffer a substantial startup and stability hit to properly run out of `/Applications/DoomEmacs.app`. _Or_ rely on users to do their own bootstrapping in `~/.emacs.d`.

   If emacs introduced a `--config DIR` switch this would be no issue. And I haven't even gotten to how much this complicates Doom's CLI workflow.

If adoption is the problem. Perhaps it would be better to focus on improving `doom install`; make it more user friendly. I'm already working on a) a web-based configurator for Doom on doomemacs.org and b) improving `doom install`. This should make things much easier for beginners, but it'll be a while until either is finished.

All in all, I don't think this will happen. I'll close this for now, but feel free to follow up here.
