### ISSUE TITLE
Some font ligatures shrink in size or get replaced

### ISSUE THREAD

**Issue by bshankar** [hlissner/doom-emacs#3837]
**What did you expect to happen?**
The arrow ligature to be correctly sized. (like in this screenshot)
![arrow_ligature_correct](https://user-images.githubusercontent.com/1161104/91268473-09de6500-e793-11ea-9dce-209bc6cca99e.png)

**What actually happened?**
When I move my mouse away, it gets replaced by a tiny arrow.
![arrow_ligature_wrong](https://user-images.githubusercontent.com/1161104/91268497-14006380-e793-11ea-8586-f694162795d2.png)

**Additional details:**
- Emacs 28 with native comp enabled.
- My ligatures specific config is `(ligatures +extra)`
- I use `JetBrains Mono` font.

<details><pre>
((system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/bin/bash")
  (uname . "Linux 5.8.3-arch1-1 #1 SMP PREEMPT Fri, 21 Aug 2020 16:54:16 +0000 x86_64")
  (path "~/.cargo/bin" "~/.emacs.d/bin" "/usr/local/sbin" "/usr/local/bin" "/usr/bin" "/usr/lib/jvm/default/bin" "/usr/bin/site_perl" "/usr/bin/vendor_perl" "/usr/bin/core_perl" "/usr/lib/emacs/28.0.50/x86_64-pc-linux-gnu"))
 (emacs
  (dir . "~/.emacs.d/")
  (version . "28.0.50")
  (build . "Aug 26, 2020")
  (buildopts . "--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --mandir=/usr/share/man --with-gameuser=:games --with-sound=alsa --with-modules --without-gconf --without-gsettings --with-nativecomp --with-x-toolkit=gtk3 --without-xaw3d --without-m17n-flt --with-cairo --without-compress-install 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -g -fuse-ld=gold' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now")
  (features . "XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES NATIVE_COMP THREADS LIBSYSTEMD JSON PDUMPER LCMS2")
  (traits batch server-running))
 (doom
  (dir . "~/.doom.d/")
  (version . "2.0.9")
  (build . "grafted, HEAD -> develop, origin/develop, origin/HEAD 1c99aed 2020-08-25 21:22:56 -0400")
  (elc-files . 0)
  (modules :completion (company +tng) (ivy +fuzzy +prescient +icons) :ui doom doom-dashboard doom-quit hl-todo (modeline +light) ophints (popup +defaults) (ligatures +extra) treemacs vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold (format +onsave) multiple-cursors snippets word-wrap :emacs dired electric undo vc :checkers syntax spell grammar :tools (eval +overlay) lookup lsp magit :lang emacs-lisp json (javascript +lsp) markdown (org +roam +pretty) rest (rust +lsp) (web +lsp) (yaml +lsp) :config (default +bindings +smartparens))
  (packages (magit-delta) (emojify))
  (unpin "n/a")
</pre></details>

**Steps to reproduce:**
1. Open a javascript file. 
2. Write an arrow function and move the mouse away from `=>` 

**System information:**
<details><pre>
((system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/bin/bash")
  (uname . "Linux 5.8.3-arch1-1 #1 SMP PREEMPT Fri, 21 Aug 2020 16:54:16 +0000 x86_64")
  (path "~/.cargo/bin" "~/.emacs.d/bin" "/usr/local/sbin" "/usr/local/bin" "/usr/bin" "/usr/lib/jvm/default/bin" "/usr/bin/site_perl" "/usr/bin/vendor_perl" "/usr/bin/core_perl" "/usr/lib/emacs/28.0.50/x86_64-pc-linux-gnu"))
 (emacs
  (dir . "~/.emacs.d/")
  (version . "28.0.50")
  (build . "Aug 26, 2020")
  (buildopts . "--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --mandir=/usr/share/man --with-gameuser=:games --with-sound=alsa --with-modules --without-gconf --without-gsettings --with-nativecomp --with-x-toolkit=gtk3 --without-xaw3d --without-m17n-flt --with-cairo --without-compress-install 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -g -fuse-ld=gold' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now")
  (features . "XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES NATIVE_COMP THREADS LIBSYSTEMD JSON PDUMPER LCMS2")
  (traits batch server-running))
 (doom
  (dir . "~/.doom.d/")
  (version . "2.0.9")
  (build . "grafted, HEAD -> develop, origin/develop, origin/HEAD 1c99aed 2020-08-25 21:22:56 -0400")
  (elc-files . 0)
  (modules :completion (company +tng) (ivy +fuzzy +prescient +icons) :ui doom doom-dashboard doom-quit hl-todo (modeline +light) ophints (popup +defaults) (ligatures +extra) treemacs vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold (format +onsave) multiple-cursors snippets word-wrap :emacs dired electric undo vc :checkers syntax spell grammar :tools (eval +overlay) lookup lsp magit :lang emacs-lisp json (javascript +lsp) markdown (org +roam +pretty) rest (rust +lsp) (web +lsp) (yaml +lsp) :config (default +bindings +smartparens))
  (packages (magit-delta) (emojify))
  (unpin "n/a")
</pre></details>

**Comment by hlissner** [comment]
This is an issue with the JetBrains Mono font. I use the same font and see it, but don't see it with Fira Code. I am not aware of any fix for this besides changing the font. I'll close this since it isn't a Doom issue.

**Comment by bshankar** [comment]
@hlissner 
I have the same issue with Fira Code too but the difference is less noticeable.

![fira_wrong](https://user-images.githubusercontent.com/1161104/91280514-744bd100-e7a4-11ea-8d70-bb26b87d9a6d.png)
![fira_right](https://user-images.githubusercontent.com/1161104/91280519-76159480-e7a4-11ea-8344-53a0d7ae99f5.png)

**Comment by ShadyAlfred** [comment]
![image](https://user-images.githubusercontent.com/3685582/96321335-57e64b00-1015-11eb-8c0a-9dbbd6cb05cc.png)
I am having the same issue with Hasklig on Windows in JavaScript files

**Comment by hlissner** [comment]
A workaround for javascript modes was posted in #6907 by @GuessWhatBBQ:

```elisp
(after! js
  (setq-default js--prettify-symbols-alist '()))
```

Since it isn't a fix and I still don't have reason to suspect this is a Doom issue I haven't reopened this. You may also want to try https://github.com/doomemacs/doomemacs/pull/5082, which my indirectly address this issue.

**Comment by GuessWhatBBQ** [comment]
My absolutely uneducated guess regarding why this happened is that the `js-mode` devs added their own ligatures using `js--prettify-symbols-alist`. You can see how it overwrites `prettify-symbols-alist` later on in the `js-mode` function in the builtin js package.

The issue here, I think, was that it uses unicode characters directly (i.e the ⇒, ≥, ≤ characters) which only takes up one character width of space. Hovering the cursor over the character however, makes it render the way ligature.el intends for some reason.

This is just to outline the research I did going down this OCD infused rabbit hole.
