### ISSUE TITLE
spell-fu utf8 not used?

### ISSUE THREAD

**Issue by FrancoisBrucker** [hlissner/doom-emacs#3838]
using spell-fu (SPC t-s) in french doesn't seem to work. Even if french words like "anticonstitutionnellement" are recognized, any accentuated words (and french have many)  like "donnée" for instance are not recognized. 

Since using  aspell with french dictionary in terminal or using M-x flycheck-buffer inside emacs recognize those accentuated words, it seems that it is a spell-fu and/or doom issue. Maybe not using utf-8?

**Comment by hlissner** [comment]
This is a spell-fu issue. It has issues with non-English dictionaries afaik. I'd recommend you enable `:checkers (spell +flyspell)` to use flyspell instead. I'll leave this open until a solution is found in Doom or implemented upstream.

**Comment by FrancoisBrucker** [comment]
thanks ! This workaround works fine. 
It's rather sad that spell-fu don't work with non-english languages.

**Comment by fbob** [comment]
Confirm this
Thanks for the advice.

**Comment by R0flcopt3r** [comment]
The PR https://github.com/hlissner/doom-emacs/pull/4803 fixes this.

**Comment by hlissner** [comment]
Was resolved in af90333.
