### ISSUE TITLE
evil-collection keybindings clash, eg. IBuffer

### ISSUE THREAD

**Issue by pszynk** [hlissner/doom-emacs#3854]
I'm not sure if this should be a "How do I..." or a "Bug". Don't really know what the expected behaviour should be.

#### What did you expect to happen?
Open the `IBuffer` and use keybindings for `ibuffer-filter-*` (`s *`) and `ibuffer-redisplay` (`gr`) as they are declared in [evil-collection](https://github.com/emacs-evil/evil-collection) package.

#### What actually happened?
* `s` binding is reserved for [evil-snipe](https://github.com/hlissner/evil-snipe) package
* `gr` executes `+eval:region`

#### Steps to reproduce:
Open `IBuffer` and click away

#### The question:

I this case, for `ibuffer-mode`, both `evil-snipe` and `+eval:region` are not very useful (I think). Filtering and redisplay, on the other hand, are basic `ibuffer` functions and should be bounded.

I know I could manually redefine those keybindings, but is there a way to configure a more "fine-grain" integration of `doom` and `evil-collection`? I've read the comments in `doom-emacs/modules/editor/evil/init.el` and understood that `evil-collection` can be problematic. But overall, the idea to keep unified keybindings for `evil` sounds good.

What I would like to know is:
1. Is there a way to override `doom` keybindings with `evil-collection` keybindings for a given mode?
2. Is there a smart way to detect possible keybindings clashes? 

P.S.
Hope this is not a duplicate or know issue, I'm new to doom and not much of an expert in emacs.
Thanks for all the work put in this awesome project.

#### System info
<details>

```
SYSTEM  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/zsh
        uname      Linux 5.8.3-arch1-1 #1 SMP PREEMPT Fri, 21 Aug 2020 16:54:16 +0000 x86_64
        path       (~/.pyenv/shims ~/.zplug/repos/zplug/zplug/bin ~/.zplug/bin ~/.local/share/bin ~/.yarn/bin /usr/local/sbin /usr/local/bin /usr/bin /usr/lib/jvm/default/bin /opt/nfsen/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl ~/.zplug/repos/unixorn/git-extra-commands/bin /usr/lib/emacs/27.1/x86_64-pc-linux-gnu/)
EMACS   dir        ~/.emacs.d/
        version    27.1
        build      sie 13, 2020
        buildopts  --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-wide-int --with-modules 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
        features   XPM JPEG TIFF GIF PNG RSVG SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP
        traits     (server-running envvar-file)
DOOM    dir        ~/.config/doom/
        version    2.0.9
        build      grafted, HEAD -> develop, origin/develop, origin/HEAD 098f1030 2020-08-27 03:11:46 -0400
        elc-files  0
        modules    (:completion company (ivy +prescient +icons) :ui doom doom-dashboard doom-quit hl-todo modeline ophints (popup +defaults) treemacs vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold (format +onsave) rotate-text snippets word-wrap :emacs (dired +icons) electric (ibuffer +icons) undo vc :term eshell vterm :checkers syntax spell grammar :tools ansible debugger docker editorconfig (eval +overlay) lookup lsp magit make pdf tmux :lang emacs-lisp (go +lsp) json javascript latex markdown org python rst sh yaml :config (default +bindings +smartparens))
        packages   ((atomic-chrome))
        unpin      (n/a)
        elpa       (n/a)
```
</details>

**Comment by jonbarksdale** [comment]
@hlissner - this appears to still be an issue, possible to reopen and get back in the list?
