### ISSUE TITLE
Doom's hydra for Ivy is not used/loaded

### ISSUE THREAD

**Issue by pszynk** [hlissner/doom-emacs#3859]
**What did you expect to happen?**
`M-o` in `ivy` buffer opens hydra defined in `modules/completion/ivy/autoload/hydras.el`

**What actually happened?**
Default `hydra-ivy/body` from `ivy-hydra` package appears.

**Additional details:**
It looks like there is a problem with `autoload` and `defhydra+` macro. If you move the autoloaded code from `hydras.el` to `config.el` proper hydra is loaded on `M-o`. I'm not sure what's happening but it looks like keybinding `M-o` calls an old
version (`ivy-hydra` standard impl.) of the function `hydra-ivy/body` before `defhydra+` modified it.  
<pre>
      | Call         | Cancel | Options | Action w/s/a: [1/20] open project in new workspace
------+--------------+--------+---------+----------------------------
  k   | follow occUr | insert | c: calling off   Case-fold: auto      
h + l | done         | oops   | M: matcher other Truncate: t          
  j   | go           |        | </>: shrink/grow Definition of this menu
</pre>

Calling `:hydra-ivy/body` by hand shows proper looking hydra. 

<pre>
 Move      | Call          | Cancel | Options | Action w/s/a: [1/20] open project in new workspace
-----------+---------------+--------+---------+---------------------------------
 g   k   u | forward occur | insert | calling: off     Case-fold: auto      
 ↨ h + l ↕ | RET done      | quit   | matcher: other   truncate: t          
 G   j   d | TAB alt-done  |        | </>: shrink/grow
</pre>

**Steps to reproduce:**
1. `C-h v`
2. `M-o`

**System information:**
<details><pre>
```
SYSTEM  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /usr/bin/zsh
        uname      Linux 5.8.3-arch1-1 #1 SMP PREEMPT Fri, 21 Aug 2020 16:54:16 +0000 x86_64
        path       (/opt/pyenv/plugins/pyenv-virtualenv/shims ~/.pyenv/shims ~/.zplug/repos/zplug/zplug/bin ~/.zplug/bin /opt/google-cloud-sdk/bin ~/.local/share/bin /usr/local/sbin /usr/local/bin /usr/bin ~/.go/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl ~/.zplug/repos/horosgrisa/zsh-dropbox/bin ~/.zplug/repos/unixorn/git-extra-commands/bin /usr/lib/emacs/27.1/x86_64-pc-linux-gnu/)
EMACS   dir        ~/.emacs.d_doom/
        version    27.1
        build      sie 13, 2020
        buildopts  --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-wide-int --with-modules 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
        features   XPM JPEG TIFF GIF PNG RSVG SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP
        traits     (server-running chemacs envvar-file)
DOOM    dir        ~/.config/doom/
        version    2.0.9
        build      HEAD -> develop b6a6f4102 2020-08-27 14:42:29 -0400
        elc-files  0
        modules    (:completion company (ivy +prescient +icons) :ui doom doom-dashboard doom-quit fill-column hl-todo hydra indent-guides minimap modeline nav-flash ophints (popup +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces zen :editor (evil +everywhere) file-templates fold (format +onsave) rotate-text snippets word-wrap :emacs (dired +icons) electric (ibuffer +icons) undo vc :term eshell vterm :checkers syntax spell grammar :tools ansible debugger docker editorconfig (eval +overlay) lookup magit pdf tmux :lang emacs-lisp (go +lsp) json latex markdown org python rst sh yaml :config (default +bindings +smartparens))
        packages   ((atomic-chrome))
        unpin      (n/a)
        elpa       (n/a)
```
</pre></details>

**Comment by exp2ipi** [comment]
This should be fixed because Doom's default minibuffer maps clobber ivy's page up / page down bindings.  Without this hydra there's no way to efficiently navigate a long list of ivy matches, which is pretty bad.

**Comment by hlissner** [comment]
> clobber ivy's page up / page down bindings.

They're on `C-S-j` and `C-S-k` for evil users, btw.

**Comment by exp2ipi** [comment]
> @exp2ipi They're on `C-S-j` and `C-S-k` for evil users, btw.

Ah, thanks for pointing that out. I kept grepping for `ivy-scroll-up-command` and totally missed the default minibuffer map definitions.

**Comment by hlissner** [comment]
As of 961f551 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
