### ISSUE TITLE
ispell configuration not loaded with +flyspell option

### ISSUE THREAD

**Issue by pszynk** [hlissner/doom-emacs#3863]
**What did you expect to happen?**
Wanted to use `+hunspell` with `+flyspell`

**What actually happened?**
`ispell-program-name == "/usr/bin/aspell"`

**Additional details:**
With `flyspell` the configuration block `(after! ispell...` is not executed (I've also check variable `ispell-skip-region-alist`).
If I run `(require 'ispell)` manually, configuration is loaded.

It looks like `flycheck-mode` is not loading `ispell`, and `after!` block is ignored?

**Steps to reproduce:**
1. Add `(spell +flyspell)` to `init.el`, sync config.
2. Run emacs
3. Toggle `flyspell-mode`  `(SPC t s)`
4. Check the value of variable `ispell-skip-region-alist` 
e.g. this should be missing `'(":\\(PROPERTIES\\|LOGBOOK\\):" . ":END:")`, ergo `after!` block wasn't executed.

**System information:**
<details><pre>
```
SYSTEM  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /usr/bin/zsh
        uname      Linux 5.8.3-arch1-1 #1 SMP PREEMPT Fri, 21 Aug 2020 16:54:16 +0000 x86_64
        path       (/opt/pyenv/plugins/pyenv-virtualenv/shims ~/.pyenv/shims ~/.zplug/repos/zplug/zplug/bin ~/.zplug/bin /opt/google-cloud-sdk/bin ~/.local/share/bin /usr/local/sbin /usr/local/bin /usr/bin ~/.go/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl ~/.zplug/repos/horosgrisa/zsh-dropbox/bin ~/.zplug/repos/unixorn/git-extra-commands/bin /usr/lib/emacs/27.1/x86_64-pc-linux-gnu)
EMACS   dir        ~/.emacs.d_doom/
        version    27.1
        build      Aug 13, 2020
        buildopts  --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-wide-int --with-modules 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
        features   XPM JPEG TIFF GIF PNG RSVG SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP
        traits     (server-running chemacs)
DOOM    dir        ~/.config/doom/
        version    2.0.9
        build      HEAD -> develop, origin/develop, origin/HEAD b3077c962 2020-08-28 04:34:56 -0400
        elc-files  0
        modules    (:completion company (ivy +prescient +icons) :ui doom doom-dashboard doom-quit fill-column hl-todo hydra indent-guides minimap modeline nav-flash ophints (popup +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces zen :editor (evil +everywhere) file-templates fold (format +onsave) rotate-text snippets word-wrap :emacs (dired +icons) electric (ibuffer +icons) undo vc :term eshell vterm :checkers syntax (spell +flyspell +hunspell) grammar :tools ansible debugger docker editorconfig (eval +overlay) lookup lsp (magit +forge) make pdf tmux :lang emacs-lisp (go +lsp) json latex markdown org python rst sh yaml :config (default +bindings +smartparens))
        packages   ((atomic-chrome))
        unpin      (n/a)
        elpa       (n/a)
```
</pre></details>

**Comment by t-e-r-m** [comment]
`+flyspell` was added back because `spell-fu` had inconsistent behavior.

For a temporary solution, you should copy over the folder `~/.emacs.d/modules/checkers/spell` (from the commit before `spell-fu` was added) to `~/.doom.d/modules/private`. Then add `:private (spell +hunspell)` to `init.el` and comment out the `spell` under `checkers`. This will use the last good `spell` configuration as a private module (Remember to run `doom sync` after).

And this is related: https://github.com/hlissner/doom-emacs/pull/3870

**Comment by pszynk** [comment]
Thanks for help, I'll give it a try.

> +flyspell was added back because spell-fu had inconsistent behavior.

Yep, found some info in previous issues. I too could't force it to work properly with non-English dictionaries. 
Switching to `spell-fu` would be nice I guess (at least that's what I read online, not that experienced emacs user to make such claims myself). But this package still need some work, hope they'll add `hunspell` support.

**Comment by hlissner** [comment]
As of 79c1fce this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by pszynk** [comment]
79c1fce solved the issue for me, thanks!
