### ISSUE TITLE
doom-autoload-error when running doom-emacs for the first time.

### ISSUE THREAD

**Issue by ThoshHub** [hlissner/doom-emacs#3871]
**What did you expect to happen?**
1. I downloaded emacs
2. I git cloned the doom config to USER/AppData/Roaming/.emacs.d
3. I ran bin/runemacs for the first time
I expected doom to run.

(I am using windows by the way, not a linux distribution)

**What actually happened?**
I got the following error:
"Symbol's function definition is void: doom-autoload-error" when I tried to run emacs immediately after git cloning the config into my USER/AppData/Roaming/.emacs.d folder
![image](https://user-images.githubusercontent.com/24558466/91678962-f295d380-eb14-11ea-9ad8-8a5b02b3072e.png)

<details><pre>
Here is the backtrace:
Debugger entered--Lisp error: (void-function doom-autoload-error)
  doom-autoload-error(file-missing "Cannot open load file" "No such file or directory" "c:/Users/Thosh/AppData/Roaming/.emacs.d/.local/autoloads")
  apply(doom-autoload-error (file-missing "Cannot open load file" "No such file or directory" "c:/Users/Thosh/AppData/Roaming/.emacs.d/.local/autoloads"))
  (if (equal (nth 3 e) doom-autoloads-file) (signal (quote doom-error) (list "Doom is in an incomplete state" "run 'doom sync' on the command line to repair it")) (apply (function doom-autoload-error) e))
  (condition-case e (load (string-remove-suffix ".el" doom-autoloads-file) nil (quote nomessage)) (file-missing (if (equal (nth 3 e) doom-autoloads-file) (signal (quote doom-error) (list "Doom is in an incomplete state" "run 'doom sync' on the command line to repair it")) (apply (function doom-autoload-error) e))))
  (progn (setq doom-init-p t) (if doom-debug-p (progn (let ((inhibit-message (active-minibuffer-window))) (message #("DOOM Initializing Doom" 0 5 (face font-lock-comment-face)))))) (setq-default exec-path doom--initial-exec-path load-path doom--initial-load-path process-environment doom--initial-process-environment) (condition-case e (load (string-remove-suffix ".el" doom-autoloads-file) nil (quote nomessage)) (file-missing (if (equal (nth 3 e) doom-autoloads-file) (signal (quote doom-error) (list "Doom is in an incomplete state" "run 'doom sync' on the command line to repair it")) (apply (function doom-autoload-error) e)))) (if (or (display-graphic-p) (daemonp)) (doom-load-envvars-file doom-env-file (quote noerror))) (require (quote core-modules)) (autoload (quote doom-initialize-packages) "core-packages") (autoload (quote doom-initialize-core-packages) "core-packages") (eval-after-load (quote package) (function (lambda nil (require (quote core-packages))))) (eval-after-load (quote straight) (function (lambda nil (doom-initialize-packages)))) (add-hook (quote window-setup-hook) (function (lambda (&rest _) (add-hook (quote hack-local-variables-hook) (function doom-run-local-var-hooks-h)) (add-hook (quote after-change-major-mode-hook) (function doom-run-local-var-hooks-maybe-h) (quote append)) (add-hook (quote doom-first-input-hook) (function gcmh-mode)) (let ((fn (intern ...))) (fset fn (function (lambda ... ... ...))) (put (quote doom-first-input-hook) (quote permanent-local) t) (let ((--dolist-tail-- ...)) (while --dolist-tail-- (let ... ... ...)))) (let ((fn (intern ...))) (fset fn (function (lambda ... ... ...))) (put (quote doom-first-file-hook) (quote permanent-local) t) (let ((--dolist-tail-- ...)) (while --dolist-tail-- (let ... ... ...)))) (let ((fn (intern ...))) (fset fn (function (lambda ... ... ...))) (put (quote doom-first-buffer-hook) (quote permanent-local) t) (let ((--dolist-tail-- ...)) (while --dolist-tail-- (let ... ... ...)))))) nil nil) (add-hook (quote emacs-startup-hook) (function doom-load-packages-incrementally-h)) (add-hook (quote window-setup-hook) (function doom-display-benchmark-h) (quote append)) (if doom-debug-p (doom-debug-mode 1)) (doom-initialize-modules force-p))
  (if (or force-p (not doom-init-p)) (progn (setq doom-init-p t) (if doom-debug-p (progn (let ((inhibit-message (active-minibuffer-window))) (message #("DOOM Initializing Doom" 0 5 (face font-lock-comment-face)))))) (setq-default exec-path doom--initial-exec-path load-path doom--initial-load-path process-environment doom--initial-process-environment) (condition-case e (load (string-remove-suffix ".el" doom-autoloads-file) nil (quote nomessage)) (file-missing (if (equal (nth 3 e) doom-autoloads-file) (signal (quote doom-error) (list "Doom is in an incomplete state" "run 'doom sync' on the command line to repair it")) (apply (function doom-autoload-error) e)))) (if (or (display-graphic-p) (daemonp)) (doom-load-envvars-file doom-env-file (quote noerror))) (require (quote core-modules)) (autoload (quote doom-initialize-packages) "core-packages") (autoload (quote doom-initialize-core-packages) "core-packages") (eval-after-load (quote package) (function (lambda nil (require (quote core-packages))))) (eval-after-load (quote straight) (function (lambda nil (doom-initialize-packages)))) (add-hook (quote window-setup-hook) (function (lambda (&rest _) (add-hook (quote hack-local-variables-hook) (function doom-run-local-var-hooks-h)) (add-hook (quote after-change-major-mode-hook) (function doom-run-local-var-hooks-maybe-h) (quote append)) (add-hook (quote doom-first-input-hook) (function gcmh-mode)) (let ((fn ...)) (fset fn (function ...)) (put (quote doom-first-input-hook) (quote permanent-local) t) (let (...) (while --dolist-tail-- ...))) (let ((fn ...)) (fset fn (function ...)) (put (quote doom-first-file-hook) (quote permanent-local) t) (let (...) (while --dolist-tail-- ...))) (let ((fn ...)) (fset fn (function ...)) (put (quote doom-first-buffer-hook) (quote permanent-local) t) (let (...) (while --dolist-tail-- ...))))) nil nil) (add-hook (quote emacs-startup-hook) (function doom-load-packages-incrementally-h)) (add-hook (quote window-setup-hook) (function doom-display-benchmark-h) (quote append)) (if doom-debug-p (doom-debug-mode 1)) (doom-initialize-modules force-p)))
  doom-initialize()
  eval-buffer(#<buffer  *load*> nil "c:/Users/Thosh/AppData/Roaming/.emacs.d/init.el" nil t)  ; Reading at buffer position 2620
  load-with-code-conversion("c:/Users/Thosh/AppData/Roaming/.emacs.d/init.el" "c:/Users/Thosh/AppData/Roaming/.emacs.d/init.el" t t)
  load("c:/Users/Thosh/AppData/Roaming/.emacs.d/init" t t)
  #f(compiled-function () #<bytecode 0x1000baab9>)()
  command-line()
  normal-top-level()

![image](https://user-images.githubusercontent.com/24558466/91679312-f70ebc00-eb15-11ea-89e2-ee3b2086799b.png)

**Steps to reproduce:**
1. I downloaded emacs
2. I git cloned the doom config to USER/appdata/roaming/.emacs.d
3. I ran bin/runemacs for the first time
4. I got the following error

**System information:**
<details><pre>
The doom info file does not exist in the bin folder, presumably because it was not generated since this is the first time I ran doom emacs.
but I am using windows 10 64 bit, build 1809 LTSC
</pre></details>

**Comment by hlissner** [comment]
As of 8f64a0e this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by JasonMFry** [comment]
fwiw I just followed the installation instructions for the first time, but I encountered this same kind of error on macOS. Running `doom sync` seems to have fixed it. Perhaps I did something out of order in which case, user error 🤷

**Comment by Hitomi98** [comment]
> fwiw I just followed the installation instructions for the first time, but I encountered this same kind of error on macOS. Running `doom sync` seems to have fixed it. Perhaps I did something out of order in which case, user error 🤷 But I put this here in case someone else finds this helpful.

how can I run doom sync on windows?
