### ISSUE TITLE
How to remove first line indentation in org-mode, in the editor?

### ISSUE THREAD

**Issue by leonkis** [hlissner/doom-emacs#3872]
In org, whenever I create a new tree and make a new line, the editor automatically indents only this first line, like so:

![1](https://user-images.githubusercontent.com/36603614/91693622-990cc380-eb6b-11ea-851b-f6d194e96a5f.png)

And only the first line remains indented:

![2](https://user-images.githubusercontent.com/36603614/91693975-294b0880-eb6c-11ea-858d-be255856ca22.png)

I'd like the editor to behave so that it does not automatically indent that first line.

**I have `org-indent-mode` disabled.**

**Comment by hlissner** [comment]
> I have org-indent-mode disabled.

You say that, but this _is_ the work of org-indent-mode. Try this:

```elisp
(after! org
  (setq org-startup-indented nil))
```

**Comment by hlissner** [comment]
Unless you meant this occurs when you press `RET` on a new line. In which case, that's electric-indent-mode.

```elisp
(electric-indent-mode -1)
;; or
(add-hook! 'org-mode-hook (electric-indent-local-mode -1))
```

**Comment by hlissner** [comment]
More alternatives:

```elisp
;; if you use evil
(map! :after evil-org
      :map evil-org-mode-map
      :i [return] #'+default/newline
      :i "RET" #'+default/newline)

;; if you don't
(map! :after org
      :map org-mode-map
      [return] #'+default/newline
      "RET" #'+default/newline)
```

You didn't include your `M-x doom/info`, so I can't assume anything about your config.

**Comment by leonkis** [comment]
> Unless you meant this occurs when you press `RET` on a new line. In which case, that's electric-indent-mode.
> 
> ```emacs-lisp
> (electric-indent-mode -1) ; globally
> ;; or
> (add-hook! 'org-mode-hook (electric-indent-local-mode -1))
> ```

This is what I meant, yes. Thank you, this works for whenever I press `RET`. However, when I press `o` (new line below) from the heading, it still indents. Should I just map `o` in the way you suggested in your last reply?

**Comment by leonkis** [comment]
Also, a new issue arose: whenever I promote a heading into level 2, 3, etc., the heading gets indented by one, and so does the first line of every paragraph.

**Comment by leonkis** [comment]
This is my `doom/info`:

<details>

```
SYSTEM  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /usr/bin/zsh
        uname      Linux 5.4.0-42-generic #46~18.04.1-Ubuntu SMP Fri Jul 10 07:21:24 UTC 2020 x86_64
        path       (~/.emacs.d/bin /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /usr/games /usr/local/games /snap/bin /usr/local/libexec/emacs/27.1.50/x86_64-pc-linux-gnu/)
EMACS   dir        ~/.emacs.d/
        version    27.1.50
        build      kol 30, 2020
        buildopts  --with-json --with-modules --with-harfbuzz --with-compress-install --with-threads --with-included-regex --with-zlib --without-sound --without-xpm --without-jpeg --without-tiff --without-gif --without-png --without-rsvg --without-imagemagick --without-toolkit-scroll-bars --without-gpm --without-dbus --without-makeinfo --without-pop --without-mailutils --without-gsettings --without-pop --without-mailutils
        features   GLIB NOTIFY INOTIFY GNUTLS FREETYPE HARFBUZZ XFT ZLIB GTK3 X11 XDBE XIM MODULES THREADS JSON PDUMPER GMP
        traits     (server-running envvar-file)
DOOM    dir        ~/.doom.d/
        version    2.0.9
        build      grafted, HEAD -> develop, origin/develop, origin/HEAD b3077c9 2020-08-28 04:34:56 -0400
        elc-files  0
        modules    (:completion ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +defaults) ligatures treemacs unicode vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold multiple-cursors snippets word-wrap :emacs dired electric vc :tools (eval +overlay) lookup magit pdf :lang data emacs-lisp javascript latex markdown org python sh :config (default +bindings +smartparens))
        packages   ((centered-cursor-mode) (latex-preview-pane) (evil-escape :disable t) (writeroom-mode) (visual-fill-column))
        unpin      (n/a)
        elpa       (n/a)
```
</details>

**Comment by hlissner** [comment]
Is this still an issue?

**Comment by felipelalli** [comment]
> Unless you meant this occurs when you press `RET` on a new line. In which case, that's electric-indent-mode.
> 
> ```emacs-lisp
> (electric-indent-mode -1) ; globally
> ;; or
> (add-hook! 'org-mode-hook (electric-indent-local-mode -1))
> ```

Thank you SO MUCH! This weird behavior started to annoying in the recent versions of Emacs/ORG.

**Comment by felipelalli** [comment]
This is SO USEFUL that I put it here:

https://emacs.stackexchange.com/questions/63618/how-to-remove-first-line-indentation-in-org-mode-in-the-editor

Thank you @hlissner .
