### ISSUE TITLE
A way to map multiple evil-escape sequences

### ISSUE THREAD

**Issue by tem** [hlissner/doom-emacs#3875]
This is something I really appreciate about Vim. Vim allows you to map multiple key sequences to <Esc>. You can map not only `jj` to <Esc>, but also `kj`, `jh`, etc. 

Currently, it seems Doom can only map one key to escape the Insert state. 

Is it possible to provide this functionality in Doom?

**Comment by hlissner** [comment]
Defining (and supporting) key chords can be a messy affair in Emacs. A simple way to define more is with a package like https://github.com/emacsorphanage/key-chord, but I can't guarantee they'll work with macros or multiple cursors.

If you want [evil-escape](https://github.com/syl20bnr/evil-escape) to support more key sequences, you'll have to bring it up there. It is the package Doom uses to give us the `jk` key sequence. It can be changed to another key sequence by adjusting `evil-escape-key-sequence`.

You could also do `(setq evil-escape-unordered-key-sequence t)`, then both `jk` and `kj` will work.
