### ISSUE TITLE
`latex`: too many unwanted configuration

### ISSUE THREAD

**Issue by junwei-wang** [hlissner/doom-emacs#3877]
In the configuration `latex`, there are too many unwanted configuration made.
If I don't want to enable them, what should I do?
For instance, I don't think everyone like to indent `\item`.

https://github.com/hlissner/doom-emacs/blob/c55391d4ac937569ed8be8e658020b33edd98ce4/modules/lang/latex/config.el#L133

**Comment by iyefrat** [comment]
The easiest way is to copy paste the LaTeX module to `$DOOMDIR/modules/lang/latex` (`$DOOMDIR` is probably `$HOME/.doom.d` if you haven't changed it), and just delete the stuff you don't like. When doom looks for modules it first looks in your doom directory so you can override them if you want.

**Comment by junwei-wang** [comment]
Glad to know this workaround.

But I am more considering it as a global issue. How about add some option or flags for those optional hacks?

**Comment by iyefrat** [comment]
That isn't really for me to decide, but what options do you think should be off by default other than the `\item` indentation?

**Comment by junwei-wang** [comment]
Now, it is only `\item` indentation. I am used to other after a few hours of using.

**Comment by hlissner** [comment]
> If I don't want to enable them, what should I do?
> For instance, I don't think everyone like to indent \item.

Can't this be disabled with `(setq +latex-indent-level-item-continuation 0)`?

**Comment by hlissner** [comment]
As of 98826f3 I've redone how item continuation indentation is handled. To disable it, use `(setq +latex-indent-item-continuation-offset nil)`. See `SPC h v +latex-indent-item-continuation-offset` for details.

With that I'll consider this resolved. Let me know if you don't think this is the case and I'll reopen it. Thanks for bringing it to my attention.

**Comment by junwei-wang** [comment]
OK to close it.
