### ISSUE TITLE
counsel-projectile-switch-project  works error

### ISSUE THREAD

**Issue by driftcrow** [hlissner/doom-emacs#388]
projectile-switch-project works error in develop branch. 

---

### Observed behavior

1. just can switch project at first time run it ,then always echo "A workspace named 'xxx' already exists"
2. first time  switch project can complete, but it find project file 2 times. and error message with  "+workspace-message: Symbol’s value as variable is void: new-name
"

### Expected behavior

switch project smoothly and no error message.

### Steps to reproduce

1. SPC p p (M-x counsel-projectile-switch-project ) more than 2 times 
### System information

<details>
<summary>Click to expand</summary>

```
DOOM Doctor
Running Emacs v25.3.50.2, commit fatal: Not a git repository (or any parent up to mount point /home/liubin)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

shell: /usr/bin/zsh
Compiled with:
  XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS
  NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB
  TOOLKIT_SCROLL_BARS GTK3 X11 MODULES XWIDGETS
uname -a:
  Linux office 4.10.0-38-generic #42~16.04.1-Ubuntu SMP Tue Oct 10
  16:32:20 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Attempt to load DOOM: success! Loaded v2.0.9
Revision 9d82318d279b98061ceaf966d2da78677d3d3f5b

----

test-emacs
test-windows
test-fonts
Found font material-design-icons.ttf
Found font weathericons.ttf
Found font octicons.ttf
Found font fontawesome.ttf
Found font file-icons.ttf
Found font all-the-icons.ttf
test-gnutls
test-tls
Validated https://elpa.gnu.org
Validated https://melpa.org
Successfully rejected https://self-signed.badssl.com
Successfully rejected https://wrong.host.badssl.com/
test-tar
Everything seems fine, happy Emacs’ing!

```
</details>

**Comment by hlissner** [comment]
Found and fixed in `develop`. I'll leave this open until it hits `master`. Let me know if it doesn't resolve your issue.

**Comment by driftcrow** [comment]
Nice job, thanks for your hard work. It's unbelievable rapid. It's works fine now .
