### ISSUE TITLE
Error with `evil-tex` when running `doom up` on macOS

### ISSUE THREAD

**Issue by apanda** [hlissner/doom-emacs#3881]
I encountered an error when running `doom up` on macOS upgrading from

```
> Preparing to upgrade Doom Emacs and its packages...
- A new version of Doom Emacs is available!

  Old revision: 46d6d0b586 (9 weeks ago)
  New revision: c55391d4ac (26 hours ago)
```

The error was:

```
> Checking for stale elc files...
> Checking Doom Emacs...
  x There was an unexpected error
    Message: error
    Data: (error . "Could not find package evil-tex in recipe repositories: (org-elpa melpa gnu-elpa-mirror emacsmirror-mirror)")
    Backtrace:
      (signal error ("Could not find package evil-tex in recipe repositories: (o
      (error "Could not find package %S in recipe repositories: %S" evil-tex (or
      (if (straight--package-built-in-p melpa-style-recipe) (throw '--cl-block-s
      (or (straight-recipes-retrieve melpa-style-recipe nil cause) (if (straight
      (if recipe-specified-p melpa-style-recipe (or (straight-recipes-retrieve m
      (let* ((recipe-specified-p (listp melpa-style-recipe)) (full-melpa-style-r
      (or (and (symbolp melpa-style-recipe) (gethash (symbol-name melpa-style-re
      (catch '--cl-block-straight--convert-recipe-- (if (memq melpa-style-recipe
      (straight--convert-recipe evil-tex " ")
      (let ((recipe (straight--convert-recipe (or (straight--get-overridden-reci
  ! Extended backtrace logged to .emacs.d/.local/doom.error.log
```

**System information:**
<details><pre>
((system
  (type . darwin)
  (config . "x86_64-apple-darwin19.5.0")
  (shell . "/bin/zsh")
  (uname . "Darwin 19.6.0 Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64")
  (path "~/.opam/default/bin" "~/.emacs.d/bin" "~/.gem/ruby/2.7.0/bin" "~/.rbenv/shims" "~/.gem/ruby/2.7.0/bin" "~/.rbenv/shims" "~/.opam/default/bin" "~/.cargo/bin" "/usr/local/bin" "/usr/bin" "/bin" "/usr/sbin" "/sbin" "/Library/TeX/texbin" "~/.gem/ruby/2.7.0/bin" "~/.rbenv/shims" "~/.opam/default/bin" "~/.cargo/bin" "/usr/local/Cellar/emacs-plus@28/28.0.50/libexec/emacs/28.0.50/x86_64-apple-darwin19.5.0"))
 (emacs
  (dir . "~/.emacs.d/")
  (version . "28.0.50")
  (build . "Jul 03, 2020")
  (buildopts . "--disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus@28/28.0.50/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus@28/28.0.50 --with-xml2 --with-gnutls --without-dbus --with-imagemagick --with-modules --with-rsvg --with-ns --disable-ns-self-contained")
  (features . "JPEG TIFF PNG RSVG IMAGEMAGICK GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS PDUMPER LCMS2 GMP")
  (traits batch))
 (doom
  (dir . "~/.doom.d/")
  (version . "2.0.9")
  (build . "HEAD -> develop c55391d4a 2020-09-01 06:59:33 -0400")
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard doom-quit fill-column hl-todo modeline ophints (popup +defaults) vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold snippets word-wrap :emacs dired electric undo vc :term vterm :checkers syntax spell :tools (eval +overlay) lookup :os macos :tools magit pdf :lang elixir emacs-lisp (haskell +dante) latex markdown org racket rust sh yaml :config (default +bindings +smartparens))
  (packages "n/a")
  (unpin "n/a")
  (elpa "n/a")))
</pre></details>

**Comment by ymarco** [comment]
https://github.com/hlissner/doom-emacs/issues/3773#issuecomment-675620546

**Comment by apanda** [comment]
@ymarco Yep, that was the problem. Thanks!!!
