### ISSUE TITLE
'C-o' does not pop marks all the way back

### ISSUE THREAD

**Issue by ezchi** [hlissner/doom-emacs#3886]
**What did you expect to happen?**
When use `g d` to jump to definitions, the `C-o` should pop in the reverse order all the way back to where the first `g d` is applied. 

**What actually happened?**
The `C-o` will go into a dead loop in the middle of the pop stacks

**Steps to reproduce:**
1. open `~/.emacs.d/modules/tools/lookup/config.el`
2. go to line `  (add-hook 'dumb-jump-after-jump-hook #'better-jumper-set-jump))`
3. put curser on `better-jumper-set-jump` and do `g d`
4. go to line `  (unless (or (region-active-p)`
5. put curser on `region-active-p` and do `g d`
6. go to line `       (progn (cl-assert (mark)) t)))`
7. put cursor on `cl-assert` and do `g d`
8. Now do `C-o` multiple times, it just jumps between `cl-assert` and `region-active-p`, but I expect it leads me back to `better-jumper-set-jump`.

**System information:**
<details><pre>
((system
  (type . darwin)
  (config . "x86_64-apple-darwin19.6.0")
  (shell . "/bin/zsh")
  (uname . "Darwin 19.6.0 Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64")
  (path "~/bin" "/usr/local/sbin" "/usr/local/opt/llvm/bin" "~/go/bin" "~/.emacs.d/bin" "/usr/local/Cellar/pyenv-virtualenv/1.1.5/shims" "~/.pyenv/shims" "/usr/local/bin" "/usr/bin" "/bin" "/usr/sbin" "/sbin" "/opt/X11/bin" "/Library/TeX/texbin" "~/bin" "/usr/local/Cellar/emacs-plus@27/HEAD-16f4f26/libexec/emacs/27.1.50/x86_64-apple-darwin19.6.0"))
 (emacs
  (dir . "~/.emacs.d/")
  (version . "27.1.50")
  (build . "Aug 14, 2020")
  (buildopts . "--disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus@27/HEAD-16f4f26/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus@27/HEAD-16f4f26 --with-xml2 --with-gnutls --without-dbus --with-imagemagick --with-json --with-modules --with-rsvg --with-ns --disable-ns-self-contained")
  (features . "RSVG IMAGEMAGICK GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS JSON PDUMPER LCMS2 GMP")
  (traits batch server-running envvar-file))
 (doom
  (dir . "~/.doom.d/")
  (version . "2.0.9")
  (build . "HEAD -> develop ae3a2fa8c 2020-09-02 14:23:11 -0400")
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard doom-quit hl-todo hydra modeline ophints (popup +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold (format +onsave) multiple-cursors snippets :emacs dired ele
ctric (undo +tree) vc :term vterm :checkers syntax spell :tools (eval +overlay) lookup (lsp +peek) magit pdf upload :lang (cc +lsp) emacs-lisp (go +lsp) json (latex +lsp +fold) markdown (org +jupyter +pomodoro +present +roam) plantuml (python +lsp +pyright +pyenv) rest rust sh yaml :email (mu4e +gmail) :config literate (default +bindings +smartparens))
  (packages (ob-http :recipe (:host github :repo "zweifisch/ob-http")) (org-gcal) (org-pandoc-import :recipe (:host github :repo "tecosaur/org-pandoc-import" :files ("*.el" "filters" "preprocessors"))) (rg))
  (unpin "n/a")
  (elpa "n/a")))
</pre></details>

**Comment by ericdallo** [comment]
Same problem here, anyone has some workaround?
