### ISSUE TITLE
doom upgrade fail

### ISSUE THREAD

**Issue by aalexei** [hlissner/doom-emacs#3887]
Hi, I'm trying to do a `doom upgrade` (on the develop branch) but the upgrade fails on a package (org-roam) and I get:
```
> In repository "org-roam", HEAD (on branch "master") has diverged from branch "develop"

         1) Abort
         2) Merge HEAD to branch "develop"
         3) Reset branch "develop" to HEAD
         4) Reset HEAD to branch "develop" (Recommended)
         5) Rebase HEAD onto branch "develop" and fast-forward "develop" to HEAD

      How to proceed? (1, 2, 3, 4, 5)
```

The problem is that none of the options allow you to proceed. 1 aborts the whole process, 3 and 5 immediately redisplay the menu with no other output, 2 and 4 give the following error and abort:
```
x There was an unexpected package error
        error: pathspec 'develop' did not match any file(s) known to git
```
While actual error seems to be on the org-roam package but it shouldn't kill the upgrade process for all of doom, and it would be nice to have a hint on how to resolve the issue manually.

**Comment by hlissner** [comment]
Delete `~/.emacs.d/.local/straight/repos/org-roam` manually, then run `doom sync`.

**Comment by aalexei** [comment]
That's much more elegant than what I tried, which was deleting all of `.local` :)

The issue is that the upgrade process gets through 192/234 packages before hitting org-roam and stopping. There should be an option to skip rogue packages and continue with the rest.

**Comment by aalexei** [comment]
Any idea on how to fix this manually? I don't know enough about git and what doom expects to fix it. i.e. How do I manually `Reset HEAD to branch "develop"` so that `doom upgrade` is happy?

**Comment by aalexei** [comment]
Fixed. I had 
```
(package! org-roam  :recipe (:host github :repo "jethrokuan/org-roam" :branch "develop"))
```
in `packages.el`
changed to 
```
(package! org-roam)
```
