### ISSUE TITLE
Something lock git repository

### ISSUE THREAD

**Issue by averrin** [hlissner/doom-emacs#389]
### Observed behavior

After some dir with git repo was opened in emacs, every git command said that index.lock file exist and must be removed before continue.

### Expected behavior

nothing

### Steps to reproduce

1. emacs .
2. git commit

### System information

<details>
<summary>Click to expand</summary>

```
DOOM Doctor
Running Emacs v26.0.91, commit 6689494243cb68a9aef97db23e1438b2b33025d9

shell: /usr/bin/zsh
Compiled with:
  XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GSETTINGS NOTIFY GNUTLS LIBXML2
  FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 THREADS
uname -a:
  Linux spb-anabrodov 4.4.0-109-generic #132-Ubuntu SMP Tue Jan 9
  19:52:39 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Attempt to load DOOM: success! Loaded v2.0.9
Revision 6689494243cb68a9aef97db23e1438b2b33025d9

----

test-emacs
test-windows
test-fonts
Found font material-design-icons.ttf
Found font weathericons.ttf
Found font octicons.ttf
Found font fontawesome.ttf
Found font file-icons.ttf
Found font all-the-icons.ttf
test-gnutls
test-tls
Validated https://elpa.gnu.org
Validated https://melpa.org
Successfully rejected https://self-signed.badssl.com
Successfully rejected https://wrong.host.badssl.com/
test-tar
Everything seems fine, happy Emacs’ing!
No RTags process running (rdm)...

```
</details>

**Comment by ocharles** [comment]
I've seen this quite a few times and it's baffled me. I wonder if it's git-gutter interfering?

**Comment by hlissner** [comment]
`dired-k` is a prime suspect, because it uses `kill-process` to abruptly kill git processes, rather than `interrupt-process`. I just pushed a fix advising dired-k to use the latter. Let me know if that resolves your issue.

**Comment by averrin** [comment]
Cannot reproduce after update. Thanks.
