### ISSUE TITLE
lsp, Flycheck checker and Autocomplete don't work if file is passed as an argument to Emacs

### ISSUE THREAD

**Issue by shans10** [hlissner/doom-emacs#3891]
**What did you expect to happen?**
I have enabled lsp for python and C/C++ and it works flawlessly if I manually open associated files in emacs but whenever I open it using **emacs "filename"** or **emacs -nw "filename"** from terminal lsp and flycheck should work. 

**What actually happened?**
When filename is given as argument in terminal Flycheck, lsp and autocomplete do not work and I have to enable them manually!

**Steps to reproduce:**
1. Open a terminal and type emacs "filename" or emacs -nw "filename".
2. Flycheck, lsp and autocomplete are disabled, need to enble them manually.

**System information:**
<details><pre>
((system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/usr/bin/fish")
  (uname . "Linux 5.8.5-arch1-1 #1 SMP PREEMPT Thu, 27 Aug 2020 18:53:02 +0000 x86_64")
  (path "~/.config/xmobar/scripts/" ".bin/" ".cargo/bin/" ".emacs.d/bin/" "/usr/local/sbin" "/usr/local/bin" "/usr/bin" "/usr/bin/site_perl" "/usr/bin/vendor_perl" "/usr/bin/core_perl" "/usr/lib/emacs/27.1/x86_64-pc-linux-gnu"))
 (emacs
  (dir . "~/.emacs.d/")
  (version . "27.1")
  (build . "Aug 28, 2020")
  (buildopts . "--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-wide-int --with-modules --with-cairo --with-harfbuzz 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now")
  (features . "XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP")
  (traits batch envvar-file))
 (doom
  (dir . "~/.doom.d/")
  (version . "2.0.9")
  (build . "grafted, HEAD -> develop, origin/develop, origin/HEAD ae3a2fa 2020-09-02 14:23:11 -0400")
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline neotree ophints (popup +defaults) vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold snippets :emacs dired electric ibuffer undo vc :term vterm :checkers syntax :tools (eval +overlay) lookup lsp magit :lang (cc +lsp) emacs-lisp json (javascript +lsp) (lua +lsp) markdown org (python +lsp) (rust +lsp) sh :config (default +bindings +smartparens))
  (packages "n/a")
  (unpin "n/a")
  (elpa "n/a")))

</pre></details>

**Comment by innerout** [comment]
I can confirm this behavior too. It affects at least python, bash, and docker files too.

**Comment by innerout** [comment]
If I add in my config.el`(add-hook! python-mode LSP)`, then python works as it should even if I invoke 
`emacs filename` . I guess the generic solution is to add the relevant line for each mode when LSP is enabled in init.el. @hlissner

**Comment by hlissner** [comment]
As of b461f76 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by shans10** [comment]
> As of [b461f76](https://github.com/hlissner/doom-emacs/commit/b461f76b0d7b101772333de97745164efd9f1b30) this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

Thank you very much, my issue is resolved now and its working as expected! :)
