### ISSUE TITLE
Ivy's fuzzy mode is not order-independent

### ISSUE THREAD

**Issue by NightMachinary** [hlissner/doom-emacs#3898]
I have `(ivy +fuzzy +icons)` enabled, but the fuzzy mathcing is still nowhere as good as `fzf`, in particular, the results are order dependent:
![image](https://user-images.githubusercontent.com/36224762/92303046-a8827700-ef86-11ea-9ec6-2862d3643777.png)

![image](https://user-images.githubusercontent.com/36224762/92303048-ac15fe00-ef86-11ea-90e5-b8af8d71f24f.png)

**Comment by t-e-r-m** [comment]
Modify `prescient-filter-method`.

**Comment by NightMachinary** [comment]
I solved this by using `fzf.el`. I recommend adding it as a module.
