### ISSUE TITLE
doom can't find functions when using native compile

### ISSUE THREAD

**Issue by tgbugs** [hlissner/doom-emacs#3901]
**What did you expect to happen?**
Run `EMACSDIR=/path/to/doom-emacs/ /path/to/doom-emacs/bin/doom run -q -l /path/to/doom-emacs/init.el`
and have doom load as normal.

**What actually happened?**
`load: Symbol’s value as variable is void: +magit--ignore-version-a`

**Additional details:**

<details><pre>
Debugger entered--Lisp error: (void-variable +magit--ignore-version-a)
  byte-code("\306\307\310\311#\210\312\10\313\11\314\n!\315\316\n\205%\0\317\320\321\322\33\323\324!)\206 \0\325\f\15$\n\"\326&\6\"\207" [IS-WINDOWS +magit--ignore-version-a print-dest magit-git-debug emacs-version system-type put set-lsp-priority! doom-module (:tools . lsp) when! defadvice! &optional :override magit-version princ format "Magit (unknown), Git %s, Emacs %s, %s" #f(compiled-function (err) #<bytecode 0xac01554eb8d2951>) magit-git-version t "(unknown)" nil] 13)
  load("/home/tom/git/NOFORK/doom-emacs/.local/autoloads" nil nomessage)
  (condition-case e (load (string-remove-suffix ".el" doom-autoloads-file) nil 'nomessage) (file-missing (if (equal (nth 3 e) doom-autoloads-file) (signal 'doom-error (list "Doom is in an incomplete state" "run 'doom sync' on the command line to repair it")) (signal 'doom-autoload-error e))))
  (progn (setq doom-init-p t) (if doom-debug-p (progn (let ((inhibit-message (active-minibuffer-window))) (message #("DOOM Initializing Doom" 0 5 (face font-lock-comment-face)))))) (progn (set-default 'exec-path doom--initial-exec-path) (set-default 'load-path doom--initial-load-path) (set-default 'process-environment doom--initial-process-environment)) (condition-case e (load (string-remove-suffix ".el" doom-autoloads-file) nil 'nomessage) (file-missing (if (equal (nth 3 e) doom-autoloads-file) (signal 'doom-error (list "Doom is in an incomplete state" "run 'doom sync' on the command line to repair it")) (signal 'doom-autoload-error e)))) (if (or (display-graphic-p) (daemonp)) (doom-load-envvars-file doom-env-file 'noerror)) (require 'core-modules) (autoload 'doom-initialize-packages "core-packages") (autoload 'doom-initialize-core-packages "core-packages") (eval-after-load 'package #'(lambda nil (require 'core-packages))) (eval-after-load 'straight #'(lambda nil (doom-initialize-packages))) (add-hook 'window-setup-hook #'(lambda (&rest _) (add-hook 'hack-local-variables-hook #'doom-run-local-var-hooks-h) (add-hook 'after-change-major-mode-hook #'doom-run-local-var-hooks-maybe-h 'append) (add-hook 'doom-first-input-hook #'gcmh-mode) (let ((fn (intern ...))) (fset fn #'(lambda ... ... ...)) (put 'doom-first-input-hook 'permanent-local t) (let ((--dolist-tail-- ...)) (while --dolist-tail-- (let ... ... ...)))) (let ((fn (intern ...))) (fset fn #'(lambda ... ... ...)) (put 'doom-first-file-hook 'permanent-local t) (let ((--dolist-tail-- ...)) (while --dolist-tail-- (let ... ... ...)))) (let ((fn (intern ...))) (fset fn #'(lambda ... ... ...)) (put 'doom-first-buffer-hook 'permanent-local t) (let ((--dolist-tail-- ...)) (while --dolist-tail-- (let ... ... ...))))) nil nil) (add-hook 'emacs-startup-hook #'doom-load-packages-incrementally-h) (add-hook 'window-setup-hook #'doom-display-benchmark-h 'append) (if doom-debug-p (doom-debug-mode 1)) (doom-initialize-modules force-p))
  (if (or force-p (not doom-init-p)) (progn (setq doom-init-p t) (if doom-debug-p (progn (let ((inhibit-message (active-minibuffer-window))) (message #("DOOM Initializing Doom" 0 5 (face font-lock-comment-face)))))) (progn (set-default 'exec-path doom--initial-exec-path) (set-default 'load-path doom--initial-load-path) (set-default 'process-environment doom--initial-process-environment)) (condition-case e (load (string-remove-suffix ".el" doom-autoloads-file) nil 'nomessage) (file-missing (if (equal (nth 3 e) doom-autoloads-file) (signal 'doom-error (list "Doom is in an incomplete state" "run 'doom sync' on the command line to repair it")) (signal 'doom-autoload-error e)))) (if (or (display-graphic-p) (daemonp)) (doom-load-envvars-file doom-env-file 'noerror)) (require 'core-modules) (autoload 'doom-initialize-packages "core-packages") (autoload 'doom-initialize-core-packages "core-packages") (eval-after-load 'package #'(lambda nil (require 'core-packages))) (eval-after-load 'straight #'(lambda nil (doom-initialize-packages))) (add-hook 'window-setup-hook #'(lambda (&rest _) (add-hook 'hack-local-variables-hook #'doom-run-local-var-hooks-h) (add-hook 'after-change-major-mode-hook #'doom-run-local-var-hooks-maybe-h 'append) (add-hook 'doom-first-input-hook #'gcmh-mode) (let ((fn ...)) (fset fn #'...) (put 'doom-first-input-hook 'permanent-local t) (let (...) (while --dolist-tail-- ...))) (let ((fn ...)) (fset fn #'...) (put 'doom-first-file-hook 'permanent-local t) (let (...) (while --dolist-tail-- ...))) (let ((fn ...)) (fset fn #'...) (put 'doom-first-buffer-hook 'permanent-local t) (let (...) (while --dolist-tail-- ...)))) nil nil) (add-hook 'emacs-startup-hook #'doom-load-packages-incrementally-h) (add-hook 'window-setup-hook #'doom-display-benchmark-h 'append) (if doom-debug-p (doom-debug-mode 1)) (doom-initialize-modules force-p)))
  doom-initialize()
  eval-buffer(#<buffer  *load*> nil "/home/tom/git/NOFORK/doom-emacs/init.el" nil t)  ; Reading at buffer position 2620
  load-with-code-conversion("/home/tom/git/NOFORK/doom-emacs/init.el" "/home/tom/git/NOFORK/doom-emacs/init.el" nil t)
  command-line-1(("-l" "/home/tom/git/NOFORK/doom-emacs/init.el"))
  command-line()
  normal-top-level()
</pre></details>

**Steps to reproduce:**
1. Install emacs from feature/native-comp at https://github.com/emacs-mirror/emacs/commit/67c53691560616598f746491347bd223480e6172
2. Launch doom
3. Let it compile all the things.
4. Try to launch doom again.
5. It will fail with `load: Symbol’s value as variable is void: +magit--ignore-version-a`
6. You can temporarily fix this by removing /path/to/doom-emacs/.local/cache/eln but it will happen again next time you launch.

**System information:**
<details>

```
SYSTEM  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/bash
        uname      Linux 5.7.0-gentoo #1 SMP Sun Jun 7 23:25:28 PDT 2020 x86_64
        path       (~/git/NOFORK/doom-emacs/bin/ ~/bin ~/bin ~/.nix-profile/bin ~/.nix-profile/bin /nix/var/nix/profiles/default/bin /usr/local/bin /usr/bin /bin /usr/lib/llvm/6/bin /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /opt/bin /usr/lib/llvm/10/bin /usr/lib/llvm/9/bin /opt/nvidia-cg-toolkit/bin /usr/libexec/emacs/28.0.50/x86_64-pc-linux-gnu)
EMACS   dir        ~/git/NOFORK/doom-emacs/
        version    28.0.50
        build      Sep 05, 2020
        buildopts  --prefix=/usr --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu --mandir=/usr/share/man --infodir=/usr/share/info --datadir=/usr/share --sysconfdir=/etc --localstatedir=/var/lib --disable-silent-rules --docdir=/usr/share/doc/emacs-28.0.9999-r1 --htmldir=/usr/share/doc/emacs-28.0.9999-r1/html --libdir=/usr/lib64 --program-suffix=-emacs-28-vcs --includedir=/usr/include/emacs-28-vcs --infodir=/usr/share/info/emacs-28-vcs --localstatedir=/var --enable-locallisppath=/etc/emacs:/usr/share/emacs/site-lisp --without-compress-install --without-hesiod --without-pop --with-dumping=pdumper --with-file-notification=inotify --enable-acl --without-dbus --with-modules --without-gameuser --with-libgmp --without-gpm --with-json --without-kerberos --without-kerberos5 --without-lcms2 --with-xml2 --without-mailutils --with-nativecomp --without-selinux --with-gnutls --without-libsystemd --with-threads --without-wide-int --with-zlib --with-sound=alsa --with-x --without-ns --without-gconf --without-gsettings --without-toolkit-scroll-bars --with-gif --with-jpeg --with-png --with-rsvg --with-tiff --with-xpm --without-imagemagick --with-xft --without-cairo --with-harfbuzz --without-libotf --without-m17n-flt --with-x-toolkit=lucid --with-xaw3d 'CFLAGS=-march=core-avx2 -O2 -pipe' CPPFLAGS= 'LDFLAGS=-Wl,-O1 -Wl,--as-needed'
        features   XAW3D XPM JPEG TIFF GIF PNG RSVG SOUND GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ XFT ZLIB LUCID X11 XDBE XIM MODULES NATIVE_COMP THREADS JSON PDUMPER
        traits     (server-running)
DOOM    dir        ~/.doom.d/
        version    2.0.9
        build      HEAD -> develop, origin/develop, origin/HEAD c2e921177 2020-09-05 01:55:51 -0400
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold snippets :emacs dired electric vc :checkers syntax :tools (eval +overlay) lookup magit :lang clojure common-lisp data emacs-lisp hy latex markdown (org +dragndrop +present) python racket scheme sh :config (default +bindings +smartparens))
        packages   (n/a)
        unpin      (n/a)
        elpa       (n/a)
```
</details>

**Comment by orialb** [comment]
I just encountered exactly the same issue (with `+magit--ignore-version-a` being the culprit as well). 
running `doom sync` resolves this for one launch (I guess maybe it deletes the cache mentioned in point 6 above), but it comes back again. 
@tgbugs  did you find any workaround for this? 
I've seen a few other posts in the discord channel about this, but I couldn't understand whether someone managed to solve it.

**Comment by orialb** [comment]
Ok, I did some more digging and I found out that in my case the problem was because I was using [chemacs](https://github.com/plexus/chemacs), and it ignores doom's `early-init.el` file where `comp-deferred-compilation` is set to `nil`. So maybe you can try to check if in your case `comp-deferred-compilation` is for some reason not set to `nil`.

**Comment by tgbugs** [comment]
I'm running emacs built at https://github.com/emacs-mirror/emacs/tree/89a2e79b7d9fa9dc640951bbb3cb0d78dbfbc310, and I still see the behavior, but your discovery that `doom sync` can temporarily fix the issue is a good starting point for finding the underlying cause.

`doom sync` definitely does not delete the cache mentioned in point 6 since that would force a complete recompile of hundreds of files.

Here is a new repro on my end.

1. `EMACSDIR=/path/to/doom-emacs/ /path/to/doom-emacs/bin/doom sync`
2. `/path/to/doom-emacs/bin/doom run -q -l /path/to/doom-emacs/early-init.el -l /path/to/doom-emacs/init.el`
3. repeat 2 as many times as you like it will continue to work, so long as `comp-deferred-compilation` is always `nil`.
4. Run `/path/to/doom-emacs/bin/doom run -q -l /path/to/doom-emacs/init.el` or change `comp-deferred-compilation` to `t`.
5. Repeat step 2 (`comp-deferred-compilation` should be `nil` again).
6. The problem will appear.

So it looks like `doom sync` is a permanent fix so long as `comp-deferred-compilation` is never accidentally set to `t`.
However, this does not explain how loading with `comp-deferred-compilation` `t` somehow manages to permanently break
things.

As a side note `comp-deferred-compilation` must be set in `early-init.el`, it cannot be set in `init.el` otherwise there is a moment where it will activate causing the issue.

Maybe something gets stuck in custom.el that sync wipes? Not sure.

**Comment by hlissner** [comment]
Seems https://github.com/plexus/chemacs2 just came out. May be worth switching over.

**Comment by hlissner** [comment]
As of 29b12de this issue should be resolved, chemacs2 or not. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by orialb** [comment]
Thanks @hlissner for the fix and for all your hard work on doom in general!

**Comment by tgbugs** [comment]
Confirming fixed on my end. Many thanks!

**Comment by Kingpatzer** [comment]
I am just trying to install doom emacs and I get this error for install

```
david@laptop bin [develop] % ./doom install
Symbol’s value as variable is void: comp-deferred-compilation-deny-list
```

**Comment by hlissner** [comment]
@Kingpatzer See <https://github.com/hlissner/doom-emacs/issues/4400>
