### ISSUE TITLE
Setting up doom-emacs as a IDE for python.

### ISSUE THREAD

**Issue by apoorv569** [hlissner/doom-emacs#3903]
I'm very new to `emacs` and `doom-emacs` and Python as well, I'm trying to setup `doom-emacs` as a `vscodium` replacement, I got most of the things setup like color scheme, linting and auto completion, but I can't seem to figure out how do I execute the `.py` file, like in `vscodium` I just press the play button, and it executes it in a console window below. Do I need some package or plugin to enable such feature in `doom-emacs`. Sorry if this has been already asked.

**Comment by Gilgamesh98** [comment]
Look at [#1997](https://github.com/hlissner/doom-emacs/issues/1997)
I personally use elpy to run the python code by `C-c C-c`, you can also use an eshell and manually run `python foo.py`

**Comment by apoorv569** [comment]
> Look at [#1997](https://github.com/hlissner/doom-emacs/issues/1997)
> I personally use elpy to run the python code by `C-c C-c`, you can also use an eshell and manually run `python foo.py`

`C-c C-c` opens `python` interpreter, is that elpy? `eshell` seems like a good option. Is there no native way of running/executing the `.py` files, like Vscodium has, just press some key combination or button or something to run the program.

**Comment by Gilgamesh98** [comment]
> `C-c C-c` opens `python` interpreter, is that elpy? `eshell` seems like a good option. Is there no other way of running/executing the `.py` files, like Vscodium has, just press some key combination or button or something to run the program.

Apologies, I forgot to mention that you need to add elpy to packages.el to install it, check [the documentation for elpy](https://elpy.readthedocs.io/en/latest/introduction.html).
`C-c C-c` should then evaluate the code instead of just opening the interpreter, this should be your key combination code execution, Doom Emacs doesn't really have buttons.

**Comment by apoorv569** [comment]
> > `C-c C-c` opens `python` interpreter, is that elpy? `eshell` seems like a good option. Is there no other way of running/executing the `.py` files, like Vscodium has, just press some key combination or button or something to run the program.
> 
> Apologies, I forgot to mention that you need to add elpy to packages.el to install it, check [the documentation for elpy](https://elpy.readthedocs.io/en/latest/introduction.html).
> `C-c C-c` should then evaluate the code instead of just opening the interpreter, this should be your key combination code execution, Doom Emacs doesn't really have buttons.

I added these lines to end of the of `packages.el`
```
(use-package elpy
  :ensure t
  :init
  (elpy-enable))
```
and it gave me errors
```
❯ ~/.emacs.d/bin/doom sync
> Synchronizing your config with Doom Emacs...
  > Regenerating envvars file at "~/.emacs.d/.local/env"
    - Ignoring DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
    - Ignoring TERM=alacritty
    - Ignoring HOME=/home/apoorv
    - Ignoring PWD=/home/apoorv
    ✓ Successfully generated "~/.emacs.d/.local/env"
Ignoring ’:ensure t’ in ’elpy’ config
  x There was an unexpected error
    Message: Symbol's function definition is void
    Data: (void-function . elpy-enable)
    Backtrace:
      (elpy-enable)
      (condition-case err (elpy-enable) ((debug error) (funcall use-package--war
      (progn (condition-case err (elpy-enable) ((debug error) (funcall use-packa
      (condition-case err (progn (condition-case err (elpy-enable) ((debug error
      (eval-buffer #<buffer  *load*-365026> nil "/home/apoorv/.doom.d/packages.e
      (load-with-code-conversion "/home/apoorv/.doom.d/packages.el" "/home/apoor
      (load "/home/apoorv/.doom.d/packages.el" noerror nomessage nosuffix)
      (if (not noeval) (load file noerror 'nomessage 'nosuffix) (if (file-exists
      (progn (if (not noeval) (load file noerror 'nomessage 'nosuffix) (if (file
      (unwind-protect (progn (if (not noeval) (load file noerror 'nomessage 'nos
  ! Extended backtrace logged to .emacs.d/.local/doom.error.log
~
```
According the [documentation](https://elpy.readthedocs.io/en/latest/introduction.html), it says to add the lines to `init.el`, but adding the lines to `init.el` does nothing.

**Comment by Gilgamesh98** [comment]
> According the [documentation](https://elpy.readthedocs.io/en/latest/introduction.html), it says to add the lines to `init.el`, but adding the lines to `init.el` does nothing.

Installing packages in Doom is different, just add `(package! elpy)` to `packages.el` then run `M-x doom/reload`
Here's what I am doing
I have this in my `config.el` for configuration
```
(use-package elpy
  :ensure t
  :init
  (elpy-enable)
  )
(setq elpy-rpc-virtualenv-path "~/Environments/emacs_main/")
(setq elpy-rpc-python-command "python3")
(setq python-shell-interpreter "~/Environments/emacs_main/bin/python3") ;; This is what `C-c C-c` will use
```
Don't forget to run `pyvenv activate` and select your environment

**Comment by apoorv569** [comment]
> > According the [documentation](https://elpy.readthedocs.io/en/latest/introduction.html), it says to add the lines to `init.el`, but adding the lines to `init.el` does nothing.
> 
> Installing packages in Doom is different, just add `(package! elpy)` to `packages.el` then run `M-x doom/reload`
> Here's what I am doing
> I have this in my `config.el` for configuration
> 
> ```
> (use-package elpy
>   :ensure t
>   :init
>   (elpy-enable)
>   )
> (setq elpy-rpc-virtualenv-path "~/Environments/emacs_main/")
> (setq elpy-rpc-python-command "python3")
> (setq python-shell-interpreter "~/Environments/emacs_main/bin/python3") ;; This is what `C-c C-c` will use
> ```
> 
> Don't forget to run `pyvenv activate` and select your environment

Ah! I see what is happening, it also opens python interpreter. I was expecting more like console execution. And also it opens in a horizontal split rather than vertical split.
