### ISSUE TITLE
Formatting in scratch buffer and inside org src code buffer not working

### ISSUE THREAD

**Issue by akrger** [hlissner/doom-emacs#3905]
**What did you expect to happen?**
Formatting should work inside scratch buffers and also inside org src code buffers (the temporary ones, which one opens with `org-edit-special`).

**What actually happened?**
Formatting does not work in these mentioned buffers

**Additional details:**
<details>
 <summary>init.el</summary>

```
;;; init.el -*- lexical-binding: t; -*-

(doom! :completion
       company
       ivy

       :ui
       doom
       doom-dashboard
       doom-quit
       hl-todo
       modeline
       ophints
       (popup +defaults)
       vc-gutter
       vi-tilde-fringe
       workspaces

       :editor
       (evil +everywhere)
       file-templates
       fold
       (format +onsave)
       snippets

       :emacs
       dire
       electric
       undo
       vc

       :checkers
       syntax

       :tools
       (eval +overlay)
       lookup
       lsp
       magit

       :os
       (:if IS-MAC macos)

       :lang
       emacs-lisp
       (javascript +lsp)
       markdown
       org
       (rust +lsp)
       sh
       (web +lsp)

       :config
       literate
       (default +bindings +smartparens))
```
</details>

<details>
 <summary>Stack trace</summary>
<pre>
Debugger entered--Lisp error: (error "Don’t know how to format lisp-interaction-mode code")
  signal(error ("Don’t know how to format lisp-interaction-mode code"))
  error("Don't know how to format %S code" lisp-interaction-mode)
  format-all-buffer()
  #<subr funcall-interactively>(format-all-buffer)
  apply(#<subr funcall-interactively> format-all-buffer)
  funcall-interactively(format-all-buffer)
  #<subr call-interactively>(format-all-buffer record nil)
  apply(#<subr call-interactively> (format-all-buffer record nil))
  explain-pause--wrap-call-interactively(#<subr call-interactively> format-all-buffer record nil)
  apply(explain-pause--wrap-call-interactively #<subr call-interactively> (format-all-buffer record nil))
  call-interactively(format-all-buffer record nil)
  command-execute(format-all-buffer record)
  counsel-M-x-action("format-all-buffer")
  ivy-call()
  ivy-read("M-x " ("doom/sandbox" "emacs-lisp-mode" "lisp-mode" "rustic-mode" "+evil:open-scratch-buffer" "format-all-buffer" "format-all-mode" "org-edit-special" "eval-buffer" "+format/buffer" "org-html-export-to-html" "describe-variable" "cd" "5x5" "amx" "arp" "dbx" "dig" "erc" "ert" "eww" "ftp" "gdb" "irc" "jdb" "lsp" "man" "mpc" "pdb" "pwd" "rsh" "sdb" "xdb" "calc" "diff" "dirs" "ffap" "gnus" "grep" "help" "ielm" "info" "life" "lsp!" "mail" "mpuz" "ping" "pong" "talk" "term" ...) :predicate #f(compiled-function (x) #<bytecode 0x1fe8b060cac9>) :require-match t :history counsel-M-x-history :action counsel-M-x-action :keymap (keymap (67108908 . counsel--info-lookup-symbol) (67108910 . counsel-find-symbol)) :initial-input nil :caller counsel-M-x)
  counsel-M-x()
  #<subr funcall-interactively>(counsel-M-x)
  apply(#<subr funcall-interactively> counsel-M-x)
  funcall-interactively(counsel-M-x)
  #<subr call-interactively>(counsel-M-x nil nil)
  apply(#<subr call-interactively> (counsel-M-x nil nil))
  explain-pause--wrap-call-interactively(#<subr call-interactively> counsel-M-x nil nil)
  apply(explain-pause--wrap-call-interactively #<subr call-interactively> (counsel-M-x nil nil))
  call-interactively(counsel-M-x nil nil)
  command-execute(counsel-M-x)
</pre>
</details>

**Steps to reproduce:**
1. Open a sandbox with my config with `C-c C-p`
2. Navigate to the scratch buffer,
3. Try to run `format-all-buffer`
4. This should fail and produce a similar stack trace like the one I provided.
5. Also try out a org mode source block.
6. Point to a source block, and then call `org-special-edit`.
7. Inside this new buffer, call `format-all-buffer`.
8. It should also fail.

**System information:**
<details>

```
SYSTEM  type       darwin
        config     x86_64-apple-darwin18.7.0
        shell      /bin/zsh
        uname      Darwin 19.6.0 Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64
        path       (~/.emacs.d/bin/ ~/.rvm/gems/ruby-2.6.3/bin ~/.rvm/gems/ruby-2.6.3@global/bin ~/.rvm/rubies/ruby-2.6.3/bin ~/.cargo/bin ~/Library/Android/sdk/platform-tools /usr/local/bin /usr/bin /bin /usr/sbin /sbin /Library/TeX/texbin /usr/local/share/dotnet ~/.dotnet/tools /Library/Apple/usr/bin /Library/Frameworks/Mono.framework/Versions/Current/Commands ~/.rvm/bin ~/Library/Android/sdk/tools ~/Library/Android/sdk/platform-tools /Applications/Emacs.app/Contents/MacOS/bin-x86_64-10_14 /Applications/Emacs.app/Contents/MacOS/libexec-x86_64-10_14 /Applications/Emacs.app/Contents/MacOS/libexec/)
EMACS   dir        ~/.emacs.d/
        version    27.1
        build      Aug 12, 2020
        buildopts  --with-ns '--enable-locallisppath=/Library/Application Support/Emacs/${version}/site-lisp:/Library/Application Support/Emacs/site-lisp' --with-modules
        features   NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS JSON PDUMPER
        traits     (server-running envvar-file)
DOOM    dir        ~/.dotfiles/.doom.d/
        version    2.0.9
        build      grafted, HEAD -> develop, origin/develop, origin/HEAD c2e92117 2020-09-05 01:55:51 -0400
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline ophints (popup +defaults) vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold format snippets :emacs (&nopath dire) electric undo vc :checkers syntax :tools (eval +overlay) lookup lsp magit :os macos :lang emacs-lisp (javascript +lsp) markdown org (rust +lsp) sh (web +lsp) :config literate (default +bindings +smartparens))
        packages   (n/a)
        unpin      (n/a)
        elpa       (n/a)
```
</details>

**Comment by akrger** [comment]
Seems to be that the format-all package is outdated. When I remove `(format +onsave)` and install format-all in my custom packages.el, `format-all-buffer` works for the elisp scratch buffer.

**Comment by hlissner** [comment]
As of dec573c this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
