### ISSUE TITLE
Company mode misbehaving for addresses in notmuch

### ISSUE THREAD

**Issue by bjonnh** [hlissner/doom-emacs#3908]
**What did you expect to happen?**
I expect the address to match and be replaced fully by the address given by notmuch-address

**What actually happened?**

When typing an address, the beginning of the matched address is replace by what I typed.

Lets say I have
"Foo Bar" <foo@bar.com>   in my address book

if I type bar
I will get 
baro Bar" <foo@bar.com>  

inside company, so of course the address is invalid and I have to rewrite it.

**Additional details:**
The notmuch company backend is set in the config by:
(set-company-backend! 'notmuch-message-mode
    '(notmuch-company :with company-ispell company-yasnippet))

Removing company-ispell here solve the issue.

**Steps to reproduce:**
1. Start typing in address (using company mode!)
2. Look at the beginning of the address

**System information:**
<details><pre>
((system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/bin/bash")
  (uname . "Linux 5.8.1-arch1-1 #1 SMP PREEMPT Wed, 12 Aug 2020 18:50:43 +0000 x86_64")
  (path "/usr/local/bin" "/usr/local/sbin" "/usr/bin" "/usr/lib/jvm/default/bin" "/usr/bin/site_perl" "/usr/bin/vendor_perl" "/usr/bin/core_perl" "/usr/lib/emacs/27.1/x86_64-pc-linux-gnu"))
 (emacs
  (dir . "~/.emacs.d/")
  (version . "27.1")
  (build . "Aug 28, 2020")
  (buildopts . "--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-wide-int --with-modules --with-cairo --with-harfbuzz 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now")
  (features . "XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP")
  (traits batch server-running envvar-file))
 (doom
  (dir . "~/.doom.d/")
  (version . "2.0.9")
  (build . "HEAD -> develop c2e921177 2020-09-05 01:55:51 -0400")
  (elc-files . 0)
  (modules :completion company ivy :ui deft doom doom-dashboard doom-quit hl-todo modeline ophints (popup +defaults) treemacs unicode vc-gutter vi-tilde-fringe window-select workspaces zen (&nopath file-templates) (&nopath fold) (&nopath snippets) :emacs dired electric undo vc :term vterm :checkers syntax spell grammar :tools docker (eval +overlay) lookup magit pdf :lang data emacs-lisp kotlin markdown (org +dragndrop +pandoc +pomodoro) plantuml python sh yaml :email notmuch :app calendar :config (default +bindings +smartparens))
  (packages (notdeft :recipe (:host github :repo "hasu/notdeft")) (calfw-org))
  (unpin "n/a")
  (elpa "n/a")))
</pre></details>

**Comment by PhDyellow** [comment]
The issue is that company-ispell returns `'keep-prefix` for `ignore-case`, while `'notmuch-company` does not define `ignore-case`, so company uses `'keep-prefix`.  Since `'notmuch-company` matches anywhere, not just the beginning of the candidates, we get the buggy behaviour you describe, where the prefix overwrites the start of the candidate.

Since I never want to complete dictionary words in the email header, and `'notmuch-company` will never match outside of the email header, the following tweak works for me:

```
  (set-company-backend! 'notmuch-message-mode
    'notmuch-company '(company-ispell company-yasnippet))
```

Now `notmuch-company` is given a chance to return candidates. If we are not in an email header, it will return `nil` and the `'(company-ispell company-yasnippet)` group will be given an opportunity to return candidates. Don't forget to set up the `spell` module.

**Comment by bjonnh** [comment]
That's better than leaving ispell out. Thanks!

**Comment by PhDyellow** [comment]
I agree that this is a bug in the notmuch module, but I'm still new to doom so I won't make a pull request. In the mean time, anyone having this issue, add the following snippet to your`config.el`:

```
(after! notmuch
        (set-company-backend! 'notmuch-message-mode
        'notmuch-company '(company-ispell company-yasnippet))
)
```

**Comment by hlissner** [comment]
Sorry for the late response, I was on break all of September. 

As of f102063 this issue should be resolved (I followed @PhDyellow's advice). Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
