### ISSUE TITLE
Bold font rendering glitch

### ISSUE THREAD

**Issue by connorhodes** [hlissner/doom-emacs#3911]
**What did you expect to happen?**
Text typed in org-mode headings and other bold text will be all one color and will remain one color when selected with the cursor. This also happens in 

**What actually happened?**
Bold text displays with blotchy coloring. This applies to org-mode bolded text, org-mode headings, and text that is highlighed as bold in code (tested with a bash script.) When the cursor is moved off the line, the coloring becomes consistent. When the cursor is moved onto the line/over the characters, their coloring becomes blotchy (see screenshot and video)

**Additional details:**
- private config 
[private_config.zip](https://github.com/hlissner/doom-emacs/files/5188478/private_config.zip)

- screenshot
![20200908_080446](https://user-images.githubusercontent.com/64938337/92481368-e0b6cf00-f1ab-11ea-825b-8c655bc2bca5.png)

- org-mode screencast
![Peek 2020-09-08 08-24](https://user-images.githubusercontent.com/64938337/92482363-29bb5300-f1ad-11ea-8f19-8df0d621af93.gif)

- bash script screencast
*notice that the glitching happens on the bold text but not on the colored non-bolded text.*
![Peek 2020-09-08 09-00](https://user-images.githubusercontent.com/64938337/92486640-f29b7080-f1b1-11ea-9590-880ea00453f8.gif)

**Steps to reproduce:**
1. Open or create an org-mode document (or other document with bold formatting/syntax highlighting.)
2. Insert bold text or a heading and observe glitches in the font.
3. Move cursor off the line and observe the font return to normal.
4. Move cursor back onto the line and over the text to observe the glitch again.

**System information:**

<details>
```
SYSTEM  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/zsh
        uname      Linux 5.4.60-2-MANJARO #1 SMP PREEMPT Sat Aug 22 14:35:41 UTC 2020 x86_64
        path       (~/.local/bin /usr/local/sbin /usr/local/bin /usr/bin /var/lib/flatpak/exports/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl ~/bin ~/.local/config_nosync/bin /usr/lib/emacs/27.1/x86_64-pc-linux-gnu/)
EMACS   dir        ~/.emacs.d/
        version    27.1
        build      Aug 13, 2020
        buildopts  --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-wide-int --with-modules 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
        features   XPM JPEG TIFF GIF PNG RSVG SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP
        traits     (daemon server-running envvar-file)
DOOM    dir        ~/.doom.d/
        version    2.0.9
        build      HEAD -> develop c2e921177 2020-09-05 01:55:51 -0400
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard hl-todo :editor (evil +everywhere) file-templates fold snippets :emacs dired electric undo :checkers syntax :lang data emacs-lisp org sh :config (default +bindings +smartparens))
        packages   ((eshell :disable t) (org-superstar :disable t) (flyspell-lazy :disable t) (org-table-wrap-functions :recipe (:host github :repo analyticd/org-table-wrap-functions)) (zoom-window))
        unpin      (n/a)
        elpa       (n/a)
```
</details>

**Comment by connorhodes** [comment]
At first I thought this issue was confined to org-mode. Then I realized it applies to all text that is displayed as bold. I updated the issue to reflect this.

**Comment by tiZero** [comment]
I am facing a similar issue ([see here](https://github.com/seagle0128/doom-modeline/issues/328)) in the doom mode-line, where the mode-line icons misbehave the same way when inheriting a bold face.

**Comment by connorhodes** [comment]
**I found a solution to my issue. The issue is related to my system monospace font.**

I had:
```elisp
(setq doom-font (font-spec :family "monospace" :size 24))
```
in my **`config.el`**. 
I ran `fc-match monospace` and got the result `DroidSansMono.ttf: "Droid Sans Mono" "Regular"`

### Solution 1: Manually specify Nerd Font Variant
I installed the nerd-fonts-complete package from the AUR (I'm on Manjaro Linux,) and changed my default font in my **`config.el`** to:
```elisp
(setq doom-font (font-spec :family "DroidSansMono Nerd Font" :size 24))
```
### Solution 2: Change system-wide monospace font to Nerd Font variant
On linux, create **`~/.config/fontconfig/fonts.conf`** and place this text inside:
```xml
 <match target="pattern">
  <test name="family" qual="any">
   <string>monospace</string>
  </test>
  <edit binding="strong" mode="prepend" name="family">
   <string>DroidSansMono Nerd Font</string>
  </edit>
 </match>
```
This will change the system-wide monospace font to the Nerd Font variant of Droid Sans Mono.

### Conclusion

Now I have no font rendering issues. This issue may be related to using a ".ttf" font vs a ".otf" font. I'm not sure. In any case, It appears to be an upstream issue since I can replicate the issue in vanilla Emacs by changing to DroidSansMono with M-x menu-select-font, and I can then fix the issue by changing to "DroidSansMono Nerd Font Book" in the same menu. I'm going to close this issue because I found a solution. Hopefully my solution will also fix others with similar issues.
