### ISSUE TITLE
helm-bibtex doesn't open actions anymore after upgrading

### ISSUE THREAD

**Issue by LyteFM** [hlissner/doom-emacs#3916]
**What did you expect to happen?**

Pressing `TAB` or `C-i` when a reference is selected in `helm-bibtex` should display the available options.

**What actually happened?**

Both commands perform the default action, they do the same as `RET`. No errors.

**Additional details:**
- [private config](https://github.com/LyteFM/doom.d) (no packages outside of doom emacs, just some options for org and aucTeX)

Previously, I had Doom Emacs from early August and only `helm-bibtex` without the `biblio` module installed. That worked. After upgrading Doom, neither that setup nor switching to the `biblio` module would display the other options.
According to `doom doctor`, everything is fine.

**Steps to reproduce:**
1. Install current version of doom emacs (27 or 26, same behaviour)
2. Perform basic and recommended configuration of [helm-bibtex](https://github.com/tmalsburg/helm-bibtex#minimal-configuration)
3. Run `helm-bibtex`, select an entry and press `TAB`

**System information:**
<details><pre>
SYSTEM  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /usr/bin/zsh
        uname      Linux 5.4.0-47-generic #51-Ubuntu SMP Fri Sep 4 19:50:52 UTC 2020 x86_64
        path       (/usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /usr/games /usr/local/games ~/Android/Sdk/tools ~/Android/Sdk/platform-tools /opt/gradle/current/bin /snap/bin /usr/local/libexec/emacs/27.1.50/x86_64-pc-linux-gnu)
EMACS   dir        ~/.emacs.d/
        version    27.1.50
        build      Sep 09, 2020
        buildopts  --with-json --with-modules -prefix=/usr/local
        features   XPM JPEG TIFF GIF PNG SOUND DBUS GSETTINGS GLIB NOTIFY INOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS JSON PDUMPER GMP
        traits     (server-running)
DOOM    dir        ~/.doom.d/
        version    2.0.9
        build      HEAD -> develop c2e921177 2020-09-05 01:55:51 -0400
        elc-files  0
        modules    (:completion company helm :ui doom doom-dashboard hl-todo modeline ophints (popup +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold snippets :emacs dired electric undo vc :term term :checkers syntax :tools biblio editorconfig (eval +overlay) lookup magit :lang emacs-lisp json javascript latex markdown org yaml :config (default +bindings +smartparens))
        packages   (n/a)
        unpin      (n/a)
        elpa       (n/a)
</pre></details>

**Comment by myshevchuk** [comment]
I can't confirm this on my system. Both `TAB` and `C-i` are working as expected. Maybe just purge your straight build directory `~/.doom/.local/straight/build` and run `doom sync`?

**Comment by LyteFM** [comment]
Unfortunately, that didn't help. I've [disabled some more packages and removed everything](https://github.com/LyteFM/doom.d/tree/debug) from my `config.el` except the necessary variables for `helm-bibtex`.

I've also tried a full reinstall after removing `.doom.d` and `.emacs.d`:

1. installed doom emacs
2. disabled ivy, enabled helm and biblio
3. run `doom sync`
4. added minimal config for `helm-bibtex`, setting the path to bibliography file, pdfs and notes

I still get the same behaviour. The overview opens and correctly indicates whether a pdf or note is present, but `TAB` doesn't open the menu.

With `ivy-bibtex` I can cycle through the actions with `s` after `M-o`, though.

**Comment by myshevchuk** [comment]
Yeah, I got it now. Previously I had Ivy set up as completion, while helm was still loaded with other packages. So it hasn't been touched by Doom.

After purging Ivy and setting completion to Helm, this really seems to be the case.

Moreover, it's so by design:
from `.doom/modules/config/default/+evil-bindings.el`

``` elisp
        ;; Swap TAB and C-z
        "TAB"      #'helm-execute-persistent-action
        [tab]      #'helm-execute-persistent-action
        "C-z"      #'helm-select-action
```

You just have to remap these keys back to their original bindings in your `config.el`

``` elisp
(map! :after helm
           :map helm-map
           "TAB"      #'helm-select-action
            [tab]      #'helm-select-action
            "C-z"      #'helm-execute-persistent-action)
```

**Comment by LyteFM** [comment]
Thank you, that works! And now I know where to look if some other keybinding are different than expected. Closing since this is by design.
