### ISSUE TITLE
Flycheck doesn't work when both web and js modules are enabled

### ISSUE THREAD

**Issue by kuba-orlik** [hlissner/doom-emacs#3918]
**What did you expect to happen?**

I expected the errors to be highlighted by Flycheck in tsx files when both `js` and `web` modules are enabled

**What actually happened?**

The errors were not highlighted. Disabling the `web` module fixes the issue

**Additional details:**
- [my private config](https://git.kuba-orlik.name/kuba/doom-emacs-config)

**Steps to reproduce:**
1. enable web module
2. enable js module
3. open a tsx file
4. write nonsense like `const a:string = 2`
5. watch it not being highlighted as an error

**System information:**
<details><pre>
((system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/bin/bash")
  (uname . "Linux 5.4.60-2-MANJARO #1 SMP PREEMPT Sat Aug 22 14:35:41 UTC 2020 x86_64")
  (path "~/bin" "~/.emacs.d/bin" "~/.npm-global/bin" "~/bin" "~/bin" "~/.npm-global/bin" "~/bin" "~/.local/bin" "/usr/local/bin" "/usr/local/sbin" "/usr/bin" "/usr/lib/jvm/default/bin" "/usr/bin/site_perl" "/usr/bin/vendor_perl" "/usr/bin/core_perl" "/usr/lib/emacs/27.1/x86_64-pc-linux-gnu"))
 (emacs
  (dir . "~/.emacs.d/")
  (version . "27.1")
  (build . "sie 13, 2020")
  (buildopts . "--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-wide-int --with-modules 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now")
  (features . "XPM JPEG TIFF GIF PNG RSVG SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP")
  (traits batch server-running envvar-file))
 (doom
  (dir . "~/.doom.d/")
  (version . "2.0.9")
  (build . "grafted, HEAD -> develop, origin/develop, origin/HEAD c2e9211 2020-09-05 01:55:51 -0400")
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard doom-quit hl-todo minimap modeline nav-flash ophints (popup +defaults) vc-gutter vi-tilde-fringe :editor file-templates fold snippets :emacs dired electric undo vc :checkers syntax spell grammar :tools (eval +overlay) lookup magit :lang emacs-lisp json javascript ledger markdown org php python sh web yaml :email (mu4e +gmail) :config (default +bindings +smartparens))
  (packages "n/a")
  (unpin "n/a")
  (elpa "n/a")))

</pre></details>

**Comment by osenvosem** [comment]
I am also experiencing this issue.

**Comment by Giesch** [comment]
Adding the following to my config seems to resolve the issue:

    (after! (:and flycheck tide) 
      (flycheck-add-mode 'typescript-tide 'typescript-tsx-mode))

Would a PR adding this to [the tsx mode setup here](https://github.com/hlissner/doom-emacs/blob/develop/modules/lang/javascript/config.el#L123) be welcome? What's the correct way to also do this for lsp mode?
