### ISSUE TITLE
Formatter function for terragrunt

### ISSUE THREAD

**Issue by abeluck** [hlissner/doom-emacs#3921]
The terraform module works very well.

There's a wrapper around terraform, [terragrunt](https://terragrunt.gruntwork.io/), that has its [own format command](https://terragrunt.gruntwork.io/docs/reference/cli-options/#hclfmt) for it's `.hcl` files.

It should be relatively simple to write a formatter function for this, as the formatter takes 0 arguments. But I've tried and failed :( 

* command: `terragrunt hclfmt` from the pwd of the file
* applies to `*.hcl` files

**System information**
<details><pre>
((system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/usr/bin/zsh")
  (uname . "Linux 4.19.132-1.pvops.qubes.x86_64 #1 SMP Tue Jul 14 03:42:21 UTC 2020 x86_64")
  (path "~/.local/bin" "/usr/local/bin" "/usr/bin" "/bin" "/usr/local/games" "/usr/games" "/usr/lib/emacs/26.1/x86_64-linux-gnu"))
 (emacs
  (dir . "~/.emacs.d/")
  (version . "26.1")
  (build . "Sep 23, 2019")
  (buildopts . "--build x86_64-linux-gnu --prefix=/usr --sharedstatedir=/var/lib --libexecdir=/usr/lib --localstatedir=/var/lib --infodir=/usr/share/info --mandir=/usr/share/man --enable-libsystemd --with-pop=yes --enable-locallisppath=/etc/emacs:/usr/local/share/emacs/26.1/site-lisp:/usr/local/share/emacs/site-lisp:/usr/share/emacs/26.1/site-lisp:/usr/share/emacs/site-lisp --with-sound=alsa --without-gconf --with-mailutils --build x86_64-linux-gnu --prefix=/usr --sharedstatedir=/var/lib --libexecdir=/usr/lib --localstatedir=/var/lib --infodir=/usr/share/info --mandir=/usr/share/man --enable-libsystemd --with-pop=yes --enable-locallisppath=/etc/emacs:/usr/local/share/emacs/26.1/site-lisp:/usr/local/share/emacs/site-lisp:/usr/share/emacs/26.1/site-lisp:/usr/share/emacs/site-lisp --with-sound=alsa --without-gconf --with-mailutils --with-x=yes --with-x-toolkit=gtk3 --with-toolkit-scroll-bars 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/emacs-StqULU/emacs-26.1+1=. -fstack-protector-strong -Wformat -Werror=format-security -Wall' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' LDFLAGS=-Wl,-z,relro")
  (features . "XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 THREADS LIBSYSTEMD LCMS2")
  (traits batch server-running envvar-file))
 (doom
  (dir . "~/.doom.d")
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD c2e921177 2020-09-05 01:55:51 -0400")
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold format lispy multiple-cursors rotate-text snippets :emacs dired electric ibuffer vc :term eshell :checkers syntax :tools ansible docker editorconfig (eval +overlay) (lookup +docsets) magit terraform :lang clojure data emacs-lisp javascript markdown (org +dragndrop +present) sh sql web :config (default +bindings +smartparens))
  (packages "n/a")
  (unpin "n/a")
  (elpa "n/a")))

</pre></details>

**Comment by hlissner** [comment]
Our format module only works with formatters that operate on one file at a time, not "project" formatters like `terragrunt hclfmt` seems to be). You may have better luck asking for this [upstream](https://github.com/lassik/emacs-format-all-the-code), as this is out of scope for Doom.

Alternatively, use `M-x compile` or `M-x projectile-compile-project` to invoke terragrunt.

Hope that helps!
