### ISSUE TITLE
Some key bindings not effect in popup windows.

### ISSUE THREAD

**Issue by driftcrow** [hlissner/doom-emacs#393]
### Observed behavior

Some key bindings not effect in popup windows.

### Expected behavior

I want map! macro can define key binding for all window type stability.

### Steps to reproduce

1. open a buffer in popup window(M-x doom/open-scratch-window, "gd"...)
2. switch to that windows:scrach/message/help... (someone switch automatic)
3. then some key binding not effect. typical is I can't switch workspace with M-1..9
4. if i C-` toggle popup window , switch workspace action seems unnormally.

### System information

<details>
<summary>Click to expand</summary>

```
DOOM Doctor
Running Emacs v25.3.50.2, commit 4dbca5b21fa0e380b70ae83d286ad56416d218b1

shell: /usr/bin/zsh
Compiled with:
  XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS
  NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB
  TOOLKIT_SCROLL_BARS GTK3 X11 MODULES XWIDGETS
uname -a:
  Linux office 4.10.0-38-generic #42~16.04.1-Ubuntu SMP Tue Oct 10
  16:32:20 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Attempt to load DOOM: success! Loaded v2.0.9
Revision 4dbca5b21fa0e380b70ae83d286ad56416d218b1

----

test-emacs
test-windows
test-fonts
Found font material-design-icons.ttf
Found font weathericons.ttf
Found font octicons.ttf
Found font fontawesome.ttf
Found font file-icons.ttf
Found font all-the-icons.ttf
test-gnutls
test-tls
Validated https://elpa.gnu.org
Validated https://melpa.org
Successfully rejected https://self-signed.badssl.com
Successfully rejected https://wrong.host.badssl.com/
test-tar
Everything seems fine, happy Emacs’ing!

```
</details>

**Comment by hlissner** [comment]
The dashboard is now back in normal mode, by default, which should fix many of these keys. A better solution will be needed later (because these keys may still break for non-evil users), but it should fix your issue. Let me know if it didn't!

**Comment by driftcrow** [comment]
dashboard work fine, but the key issue is when focus in windows with popup property especially *doom:scratch*/*message*... then switch workspace key binding invalid, and can't split window in frame.

**Comment by driftcrow** [comment]
yeah, It works fine,thx
