### ISSUE TITLE
Org agenda doesn't start on today

### ISSUE THREAD

**Issue by kuba-orlik** [hlissner/doom-emacs#3937]
**What did you expect to happen?**

I expected the org agenda to start at the current day

**What actually happened?**

The agenda shows tasks from 3 days earlier. Pressing `.` changes the view to `today`

**Additional details:**
- Include a link to your private config: https://git.kuba-orlik.name/kuba/doom-emacs-config

**Steps to reproduce:**
1. Create an agenda
2. Set `org-agenda-span` variable to 1
3. Display the agenda
4. The agenda view is set to the date that is not the current date.

**System information:**
<details><pre>
SYSTEM  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/bash
        uname      Linux 5.4.62-1-MANJARO #1 SMP PREEMPT Thu Sep 3 14:38:22 UTC 2020 x86_64
        path       (~/bin ~/.emacs.d/bin ~/.npm-global/bin ~/bin ~/.local/bin /usr/local/bin /usr/local/sbin /usr/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /usr/lib/emacs/27.1/x86_64-pc-linux-gnu/)
EMACS   dir        ~/.emacs.d/
        version    27.1
        build      sie 28, 2020
        buildopts  --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-wide-int --with-modules --with-cairo --with-harfbuzz 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
        features   XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP
        traits     (server-running envvar-file)
DOOM    dir        ~/.doom.d/
        version    2.0.9
        build      grafted, HEAD -> develop, origin/develop, origin/HEAD c2e9211 2020-09-05 01:55:51 -0400
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo minimap modeline nav-flash ophints (popup +defaults) vc-gutter vi-tilde-fringe :editor file-templates fold snippets :emacs dired electric undo vc :checkers syntax spell grammar :tools (eval +overlay) lookup magit :lang common-lisp emacs-lisp json javascript ledger markdown (org +dragndrop) php python sh yaml :email mu4e :config (default +bindings +smartparens))
        packages   ((prettier-js))
        unpin      (n/a)
        elpa       (n/a)
</pre></details>

**Comment by RBckmnn** [comment]
Take a look at the `org-agenda-start-day` variable

**Comment by kuba-orlik** [comment]
Thanks, it worked! I've added `(setq org-agenda-start-day "-0d")` to the `(after! org` block in `config.el` and now it works the way I remember it.

I think it's strange that Doom sets the variable to -3d:

https://github.com/hlissner/doom-emacs/blob/848cc117c4555c424fcd7f16d363b5da8118f36d/modules/lang/org/config.el#L90

But glad yo've helped me find a way to fix it
