### ISSUE TITLE
mu4e: account-specific gmail flag

### ISSUE THREAD

**Issue by loafofpiecrust** [hlissner/doom-emacs#3943]
**Describe the feature**
Currently, the `+gmail` feature flag applies to the whole `mu4e` module. I am trying to setup `mu4e` with an outlook account for a University email, then a Gmail account for personal use. The changes made by the `+gmail` feature work great for my actual gmail account but cause duplicate emails in outlook when I delete or refile. I propose using a per-context variable to determine whether that context should use the gmail integration code.

This snippet does some of the work but requires gmail contexts to contain `"gmail"` in the name:
```el
  (defun my-mu4e-mark-seen (orig docid msg target)
    (if (string-match "gmail" target)
        (funcall orig docid msg target)
      (mu4e~proc-move docid
                      (mu4e~mark-check-target target)
                      "-N")))
  (advice-add '+mu4e--mark-seen :around #'my-mu4e-mark-seen)

  (defun my-mu4e-gmail-fix (orig mark msg)
    (when (string-match "gmail" (mu4e-context-name (mu4e-context-determine msg 'pick-first)))
      (funcall orig mark msg)))
  (advice-add '+mu4e-gmail-fix-flags-h :around #'my-mu4e-gmail-fix)
```

**System information**
<details><pre>
SYSTEM  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /run/current-system/sw/bin/fish
        uname      Linux 5.4.62 #1-NixOS SMP Thu Sep 3 09:27:11 UTC 2020 x86_64
        path       (~/dotfiles/emacs/.config/emacs/bin/ ~/.netlify/helper/bin ~/.config/emacs/bin ~/.go/bin ~/.cargo/bin ~/.npm/bin ~/bin /run/wrappers/bin ~/.nix-profile/bin /etc/profiles/per-user/$USER/bin /nix/var/nix/profiles/default/bin /run/current-system/sw/bin /nix/store/p0h2193gnsczaahqzz1zlz85ixmjfig6-emacs-27.1/libexec/emacs/27.1/x86_64-pc-linux-gnu/)
EMACS   dir        ~/dotfiles/emacs/.config/emacs/
        version    27.1
        build      Sep 14, 2020
        buildopts  --prefix=/nix/store/p0h2193gnsczaahqzz1zlz85ixmjfig6-emacs-27.1 --disable-build-details --with-modules --with-x-toolkit=gtk3 --with-xft --with-cairo CFLAGS=-DMAC_OS_X_VERSION_MAX_ALLOWED=101200
        features   XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND DBUS GSETTINGS GLIB NOTIFY INOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER GMP
        traits     (server-running envvar-file)
DOOM    dir        ~/dotfiles/emacs/.config/doom/
        version    2.0.9
        build      HEAD -> develop, origin/develop, origin/HEAD 1456108d5 2020-09-10 18:03:32 -0400
        elc-files  0
        modules    (:input chinese :desktop (&user window-manager) :completion (company +childframe) (ivy +childframe +prescient +icons) :ui doom doom-dashboard hl-todo hydra ophints (popup +defaults) ligatures treemacs unicode vc-gutter window-select workspaces :editor (evil +everywhere) file-templates fold (format +onsave) multiple-cursors :emacs (dired +icons) electric (undo +tree) vc :term eshell vterm :checkers (syntax +childframe) (spell +aspell +everywhere) :tools direnv editorconfig (eval +overlay) lookup lsp (magit +forge) make pdf terraform :lang (cc +lsp) data emacs-lisp (go +lsp) (json +lsp) (javascript +lsp) kotlin (latex +lsp) lua markdown nix (org +dragndrop +pomodoro) php (python +lsp) racket rest (rust +lsp) scheme (sh +fish +lsp) (swift +lsp) (web +lsp) (yaml +lsp) :email (mu4e +gmail) :config (default +bindings +smartparens))
        packages   ((tree-sitter :recipe (:host github :repo ubolonton/emacs-tree-sitter :files (lisp/*.el src Cargo.toml Cargo.lock))) (tree-sitter-langs :recipe (:host github :repo ubolonton/emacs-tree-sitter :files (langs/*.el langs/queries))) (emojify) (theme-changer :pin 61945695a30d678e6a5d47cbe7c8aff59a8c30ea) (ewal) (ewal-doom-themes) (bazel-mode :disable t) (graphql-mode) (polymode) (poly-markdown) (poly-org) (org-fragtog :disable t) (literate-calc-mode) (magit-delta :disable t) (evil-owl) (flycheck-inline :recipe (:host github :repo loafofpiecrust/flycheck-inline :branch moving-point)) (valign :disable t :recipe (:host github :repo casouri/valign)) (explain-pause-mode :disable t :recipe (:host github :repo lastquestion/explain-pause-mode)) (flycheck-posframe :disable t) (flycheck-popup-tip :disable t) (org-msg :disable t) (mu4e-alert) (mu4e-send-delay :disable t :recipe (:host github :repo bennyandresen/mu4e-send-delay)) (olivetti) (org-ref) (citeproc-org) (transmission :disable t) (exwm-edit :recipe (:no-native-compile t)) (desktop-environment) (mini-modeline) (anzu) (evil-anzu) (mini-frame :disable t) (mount-mode :recipe (:host github :repo zellerin/mount-mode)) (ivy-posframe :recipe (:no-native-compile t)) (org-cv :recipe (:host gitlab :repo Titan-C/org-cv)) (highlight-numbers :disable t) (fcitx :disable t) (bitwarden :recipe (:host github :repo seanfarley/emacs-bitwarden)))
        unpin      (n/a)
        elpa       (n/a)
</pre></details>

**Comment by innerout** [comment]
This issue will be resolved when #3971 merges into master.
