### ISSUE TITLE
Install failing with "Error reading from stdin"

### ISSUE THREAD

**Issue by jwbaldwin** [hlissner/doom-emacs#3944]
**What did you expect to happen?**
Running a fresh install:
```bash
git clone --depth 1 https://github.com/hlissner/doom-emacs ~/.emacs.d
~/.emacs.d/bin/doom install
```

Expect to complete.

**What actually happened?**
```bash
❯ Installing Doom Emacs!

> Creating .doom.d/
  ✓ Created .doom.d/
! init.el already exists, skipping
! config.el already exists, skipping
! packages.el already exists, skipping
Generate an envvar file? (see `doom help env` for details) (y or n) x There was an unexpected error
  Message: error
  Data: (error . "Error reading from stdin")
  Backtrace:
    (read-string "Generate an envvar file? (see `doom help env` for details) (
    (y-or-n-p "Generate an envvar file? (see `doom help env` for details)")
    (or doom-auto-accept (y-or-n-p "Generate an envvar file? (see `doom help e
    (if (or doom-auto-accept (y-or-n-p "Generate an envvar file? (see `doom he
    (if (file-exists-p doom-env-file) (doom--print (doom--format (format (doom
    (if noenv-p (doom--print (doom--format (format (doom--output-class 'warn "
    (let ((default-directory (doom-path "~"))) (if noconfig-p (doom--print (do
    (let ((noconfig-p (cdr (assq 'noconfig-p --alist--))) (noenv-p (cdr (assq
    ((closure ((plist) (aliases i) (name . install) t) (--alist--) (ignore --a
```

Received error about stdin

**Additional details:**
Also tried piping:

`~/.emacs.d/bin/doom -y install`
`yes | ~/.emacs.d/bin/doom install`

Both failed :/

**Steps to reproduce:**
1. Fresh install of emacs
2. Clone doom-emacs as instructed
3. Run install command as instructed

**System information:**
macOS Catalina
10.15.6

**Comment by anlsh** [comment]
What version of emacs (version number and [where you installed it from](https://www.emacswiki.org/emacs/EmacsForMacOS#toc2)) are you using? I can't reproduce this on Ubuntu 18.04 using GNU Emacs 27.0.60, so perhaps this is OSX specific?

**Comment by rubin55** [comment]
I'm having this exact same issue, on Gentoo, Emacs 27.1 (installed using emerge); definitely not OS X specific.

**Comment by jwbaldwin** [comment]
@anlsh Using GNU Emacs 27.1 from [emacs-mac](https://bitbucket.org/mituharu/emacs-mac/src/master/), though as @rubin55 points out it looks to be platform independent.
