### ISSUE TITLE
C-h q help-quit submenu does not work

### ISSUE THREAD

**Issue by SebastianCallh** [hlissner/doom-emacs#3945]
Thank you very much for your hard work on this project!

**What did you expect to happen?**
I hit `C-h q`, wait a second for the help menu to open, then hit `r` (for instance) to restart, and Emacs restarts.

**What actually happened?**
I hit `C-h q` and wait, but the help menu never opens. Hitting `r`  simply enters it into the current buffer instead of being interpreted as a command.

**Additional details:**
- [private config](https://github.com/SebastianCallh/.doom.d)
- Other shortcuts work from `C-h`
- Running `M-x doom/restart` works as expected

**Steps to reproduce:**
Unfortunately I do not know what configuration causes this behaviour. But the steps are simply
1. Enter `C-h q`
2. Expect the help-quit window to open
3. Hit `r`
4. Expect Emacs to restart

**System information:**
<details><pre>

```
SYSTEM  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/zsh
        uname      Linux 5.4.0-45-generic #49-Ubuntu SMP Wed Aug 26 13:38:52 UTC 2020 x86_64
        path       (~/.emacs.d/bin/ ~/.emacs.d/bin/ /snap/bin ~/anaconda3/bin ~/anaconda3/condabin /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /usr/games /usr/local/games /snap/emacs/current/usr/libexec/emacs/27.1/x86_64-pc-linux-gnu/)
EMACS   dir        ~/.emacs.d/
        version    27.1
        build      Aug 26, 2020
        buildopts  --prefix= --prefix=/snap/emacs/current/usr --with-xwidgets --with-x-toolkit=gtk3 --without-xaw3d --with-modules --with-cairo 'CFLAGS= -isystem/build/emacs/parts/emacs/install/usr/include -O2' 'CPPFLAGS= -isystem/build/emacs/parts/emacs/install/usr/include' 'LDFLAGS= -L/build/emacs/parts/emacs/install/lib -L/build/emacs/parts/emacs/install/usr/lib -L/build/emacs/parts/emacs/install/lib/x86_64-linux-gnu -L/build/emacs/parts/emacs/install/usr/lib/x86_64-linux-gnu'
        features   XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER LCMS2 GMP
        traits     (server-running envvar-file)
DOOM    dir        ~/.doom.d/
        version    2.0.9
        build      HEAD -> develop 1456108d 2020-09-10 18:03:32 -0400
        elc-files  0
        modules    (:completion company (ivy +prescient +icons) :ui doom doom-dashboard hl-todo modeline ophints (popup +defaults) vc-gutter vi-tilde-fringe workspaces zen :editor file-templates :emacs (dired +icons +diff-hl) electric undo :term vterm :checkers syntax spell :tools (docker +lsp) ein (eval +overlay) lookup lsp (magit +forge) pdf rgb :lang data emacs-lisp ess (haskell +dante) (julia +lsp) markdown (org +roam +jupyter +hugo +present +pretty) (python +lsp) sh yaml :app calendar :config literate (default +bindings +smartparens))
        packages   ((mixed-pitch) (company-box) (restclient) (solaire-mode :disable t))
        unpin      (n/a)
        elpa       (n/a)
```
</pre></details>

**Comment by anlsh** [comment]
I don't think this is a bug per-se. If you use `SPC h d f help-quit` to inspect help-quit's definition, you'll find that it has [the following 
definition](https://github.com/emacs-mirror/emacs/blob/ee3e432300054ca488896e39fca57b10d733330a/lisp/help.el#L121-L124)

```
(defun help-quit ()
  "Just exit from the Help command's command loop."
  (interactive)
  nil)
```

As you can see, it's meant to quit the help menu: not help you with ways to quit.

You can make `C-h q` do what you're looking for with the following snippet

```
(define-key! help-map
  "q" nil
  "qd" #'+default/restart-server
  "qf" #'delete-frame
  "qF" #'doom/kill-all-buffers
  "qK" #'save-buffers-kill-emacs
  "qq" #'save-buffers-kill-terminal
  "qQ" #'evil-quit-all-with-error-code
  "qs" #'doom/quicksave-session
  "ql" #'doom/quickload-session
  "qS" #'doom/save-session
  "qL" #'doom/load-session
  "qr" #'doom/restart-and-restore
  "qR" #'doom/restart)
```

I don't really like this solution though: it pretty much duplicates the stuff [here](https://github.com/hlissner/doom-emacs/blob/1456108d5bef89195b2b63f962e0ae9d24f4c652/modules/config/default/%2Bevil-bindings.el#L592-L604). I think that ideally we'd have some `evil-quit-map` storing the bindings like

```
{
   "d" : ("some description here", #'+default/restart-server),
    "f": ("delete current frame", #'delete-frame), 
    etc...
}
```

And you could just bind `q` in `help-map` to `evil-quit-map` (`evil-bindings.el` could also do something similar). I'm not very knowledgeable about emacs keybinds though, so perhaps this functionality already exists in Emacs or in General?

**Comment by SebastianCallh** [comment]
Oh, but of course! Thank you very much for clearing up my confusion. The source of this seems to be me confusing the key bind for `M-x doom/restart` with the hint in the help menu. The correct key bind is `C-c q r` and not `C-h q r`.
