### ISSUE TITLE
bug in `set-ligatures!` from `:ui ligatures`

### ISSUE THREAD

**Issue by mcncm** [hlissner/doom-emacs#3948]
**What did you expect to happen?**
When given `nil` as its second argument, the `set-ligatures!` function of the ` ligatures` module should clear the list of ligatures associated with the mode given as its first argument.

**What actually happened?**
However, it seems to only do this when said mode is not the car of `+ligatures-extra-alist`.

**Additional details:**
If you care to take a look (this could be my mistake, rather than a genuine bug!), my private config can be found [here](https://github.com/mcncm/.doom.d).

**Steps to reproduce:**
1. Include the `:ui ligatures` module in your `init.el`
2. Observe the nonempty values plist associated with the _first_ key (e.g. `python-mode`) in `+ligatures-extra-alist`.
3. Try to clear this key by evaluating `(set-ligatures! 'python-mode nil)`. Observe that it has no effect.
4. Insert a _new_ key in the first position by evaluating _e.g._`(set-ligatures! 'ruby-mode :lambda "lambda")`. You can also try clearing this, and seeing that it doesn’t work, either.
5. Finally, try clearing the original first key by again evaluating `(set-ligatures! 'python-mode nil)`. This time it works.

**System information:**
<details>

```
SYSTEM  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/bash
        uname      Linux 5.8.8-arch1-1 #1 SMP PREEMPT Wed, 09 Sep 2020 18:59:45 +0000 x86_64
        path       (~/.dotfiles/main/.emacs.d.doom/bin/ ~/.cargo/bin /opt/google-cloud-sdk/bin /usr/local/sbin /usr/local/bin /usr/bin /opt/cuda/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl ~/bin ~/.local/bin ~/.scripts ~/.cargo/bin ~/.cabal/bin ~/.emacs.d/bin /usr/lib/emacs/27.1/x86_64-pc-linux-gnu/)
EMACS   dir        ~/.dotfiles/main/.emacs.d.doom/
        version    27.1
        build      Aug 28, 2020
        buildopts  --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-wide-int --with-modules --with-cairo --with-harfbuzz 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
        features   XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP
        traits     (server-running envvar-file)
DOOM    dir        ~/.doom.d/
        version    2.0.9
        build      HEAD -> develop 1456108d 2020-09-10 18:03:32 -0400
        elc-files  0
        modules    (:completion (company +childframe) (ivy +icons +prescient) :ui deft doom doom-dashboard doom-quit hl-todo (ligatures +extra) modeline nav-flash ophints (popup +all +defaults) workspaces zen :editor (evil +everywhere) fold snippets :emacs (dired +icons) electric undo vc :term shell vterm :checkers syntax spell grammar :tools (eval +overlay) (lookup +dictionary +offline +docsets) lsp magit pass pdf :lang (cc +lsp) common-lisp coq emacs-lisp (haskell +dante +lsp) idris json javascript (latex +lsp +fold) markdown nix (org +roam +journal +jupyter +present +noter) (python +lsp) (rust +lsp) sh yaml :email (mu4e +gmail) :app irc :config literate (default +bindings +smartparens) :private biblio)
        packages   ((ewal-doom-themes) (olivetti) (org-variable-pitch) (org-superstar) (org-pretty-tags) (org-wild-notifier) (org-roam-server) (ivy-bibtex) (zotxt) (mu4e-alert) (nov) (google-translate))
        unpin      (n/a)
        elpa       (n/a)
```
</details>

**Comment by clayscode** [comment]
Can confirm, updated to the latest commit and ran into the same issue. Unfortunately this breaks python-mode for me, which is a must have :/

**Comment by hlissner** [comment]
Sorry for the late response; I was on break. 

As of 002f511 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
