### ISSUE TITLE
When creating a new file on treemacs after a rename of a file you can't create the new one

### ISSUE THREAD

**Issue by djnesmith** [hlissner/doom-emacs#3949]
when i rename a file with its old name like 'foo-old' and then i go to create a new file with 'c f' with the name "foo" it keeps selecting the "foo-old" and saying that file already exists

**What did you expect to happen?**
to be able to create the new file with a name similar to the one i just renamed

**What actually happened?**
keeps selecting the old file name and trying to create that old file name

**Additional details:**
- Screencast: https://files.gitter.im/5cdfc9cdd73408ce4fc0a585/iwbF/Sep-14-2020-09-19-51.gif

**Steps to reproduce:**
1. Open Treemacs for some project
2. Select a file and press R to rename it to foo-old
3. Press c f to create a new file
4. Try to create a file named "foo"

CC: @alexander-miller

**Comment by karvus** [comment]
I think this is because `RET` is accepting the suggestion you are presented with.  Try typing what you want your new file to be called, then press `C-M j`  -- usually control + alt + j

**Comment by djnesmith** [comment]
yep! that works. 👍   But I do think maybe there should be another selection for the new file you want to create?

**Comment by karvus** [comment]
It's just how ivy works by default I think.  Look at https://oremacs.com/swiper/ and search for `ivy-immediate-done`

**Comment by djnesmith** [comment]
oh wow, and it says it right there about matching an existing file
