### ISSUE TITLE
Add ReasonML/ReScripts support to Doom Emacs

### ISSUE THREAD

**Issue by helderburato** [hlissner/doom-emacs#3951]
## Description

I started to configure [reason-mode](https://github.com/reasonml-editor/reason-mode) on Doom Emacs and I made the following steps:

Add to `packages.el`
```
(package! reason-mode
  :recipe (:host github :repo "reasonml-editor/reason-mode"))
```

After that, the reason-mode has been installed.

## Hook

I saw in the reason-mode docs [this part of code](https://github.com/reasonml-editor/reason-mode#features) to enable the `auto-format` hook.

I added the following code to `config.el`:
```
(after! reason-mode
  (add-hook 'reason-mode-hook (lambda ()
                                (add-hook 'before-save-hook #'refmt-before-save))))
```

Is there okay to enable the hook?

## Reason LSP

I searched for `org-babel` to ReasonML/ReScripts but doesn't find anything. Anyone else has enabled the mode and org-babel to work with this language on Doom and evaluate in orgmode?

Only found [this one](https://github.com/jaredly/reason-language-server) but I don't know if this can be applied to Doom.

## System Info
<details>

```
SYSTEM  type       darwin
        config     x86_64-apple-darwin18.7.0
        shell      /bin/zsh
        uname      Darwin 19.6.0 Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64
        path       (/usr/local/sbin ~/.nvm/versions/node/v12.18.4/bin ~/bin /usr/local/bin ~/.emacs.d/bin ~/workspace/emacs-lsp/lsp-reason /usr/bin /bin /usr/sbin /sbin /Library/Apple/usr/bin ~/Library/Android/sdk/emulator ~/Library/Android/sdk/tools ~/Library/Android/sdk/tools/bin ~/Library/Android/sdk/platform-tools ~/.antigen/bundles/robbyrussell/oh-my-zsh/lib ~/.antigen/bundles/mengelbrecht/slimline ~/.rvm/bin /usr/local/Cellar/emacs-plus@28/28.0.50/libexec/emacs/28.0.50/x86_64-apple-darwin18.7.0/)
EMACS   dir        ~/.emacs.d/
        version    28.0.50
        build      Aug 20, 2020
        buildopts  --disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus@28/28.0.50/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus@28/28.0.50 --with-xml2 --with-gnutls --without-dbus --with-imagemagick --with-modules --with-rsvg --with-ns --disable-ns-self-contained
        features   JPEG TIFF PNG RSVG IMAGEMAGICK GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS PDUMPER LCMS2
        traits     (server-running envvar-file)
DOOM    dir        ~/.dotfiles/emacs/.doom.d/
        version    2.0.9
        build      HEAD -> develop 1456108d5 2020-09-10 18:03:32 -0400
        elc-files  0
        modules    (:completion company ivy :ui deft doom doom-dashboard doom-quit hl-todo modeline ophints (popup +defaults) vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold (format +onsave) snippets :emacs dired electric (undo +tree) vc :os macos :tools editorconfig (eval +overlay) (lookup +docsets +dictionary) lsp magit :lang clojure emacs-lisp (go +lsp) json (javascript +lsp) markdown (org +pomodoro +journal +hugo) sh web yaml :app (rss +org) :config (default +bindings +smartparens))
        packages   ((ob-typescript) (prettier-js) (move-text) (js-doc) (reason-mode))
        unpin      (n/a)
        elpa       (n/a)
```
</details>

**Comment by qhuyduong** [comment]
You can try my settings to enable Reason + LSP in Doom:
* `package.el`

`(package! reason-mode)`

* `config.el`

```
(after! lsp-mode
  (lsp-register-client
   (make-lsp-client :new-connection (lsp-stdio-connection
                                     (-const "reason-language-server"))
                    :major-modes '(reason-mode)
                    :notification-handlers (ht ("client/registerCapability" 'ignore))
                    :priority 1
                    :server-id 'reason-ls)))

(after! reason-mode
  (add-hook! reason-mode #'lsp)
  (add-hook! reason-mode (add-hook 'before-save-hook #'lsp-format-buffer nil t)))
```

Note to place the `reason-language-server` binary in your `$PATH`

Happy coding!

**Comment by helderburato** [comment]
> You can try my settings to enable Reason + LSP in Doom:
> 
> * `package.el`
> 
> `(package! reason-mode)`
> 
> * `config.el`
> 
> ```
> (after! lsp-mode
>   (lsp-register-client
>    (make-lsp-client :new-connection (lsp-stdio-connection
>                                      (-const "reason-language-server"))
>                     :major-modes '(reason-mode)
>                     :notification-handlers (ht ("client/registerCapability" 'ignore))
>                     :priority 1
>                     :server-id 'reason-ls)))
> 
> (after! reason-mode
>   (add-hook! reason-mode #'lsp)
>   (add-hook! reason-mode (add-hook 'before-save-hook #'lsp-format-buffer nil t)))
> ```
> 
> Note: Enable `lsp` module in `init.el` and place the `reason-language-server` binary in your `$PATH`.
> 
> Happy coding!

Thank you @qhuyduong!

The language server worked and reason-mode as well.

The unique thing I don't found how to enable is the org source language for Reason, do you have any experience with it?

**Comment by helderburato** [comment]
@qhuyduong did you notice delay problems when saving files?

**Comment by qhuyduong** [comment]
@helderburato No I don't see the delay. Are you using Emacs 27? Native JSON parser in Emacs 27 would result in significant improvement for LSP.

**Comment by qhuyduong** [comment]
> The unique thing I don't found how to enable is the org source language for Reason, do you have any experience with it?
Sorry I haven't use org babel with Reason yet.

**Comment by helderburato** [comment]
> @helderburato No I don't see the delay. Are you using Emacs 27? Native JSON parser in Emacs 27 would result in significant improvement for LSP.

I use *Emacs 28.0.50*.

My *system info*:
<details>

```
SYSTEM  type       darwin
        config     x86_64-apple-darwin18.7.0
        shell      /bin/zsh
        uname      Darwin 19.6.0 Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64
        path       (/usr/local/sbin ~/.nvm/versions/node/v12.18.4/bin ~/bin /usr/local/bin ~/.emacs.d/bin ~/workspace/emacs-lsp/lsp-reason /usr/bin /bin /usr/sbin /sbin /Library/Apple/usr/bin ~/Library/Android/sdk/emulator ~/Library/Android/sdk/tools ~/Library/Android/sdk/tools/bin ~/Library/Android/sdk/platform-tools ~/.antigen/bundles/robbyrussell/oh-my-zsh/lib ~/.antigen/bundles/mengelbrecht/slimline ~/.rvm/bin /usr/local/Cellar/emacs-plus@28/28.0.50/libexec/emacs/28.0.50/x86_64-apple-darwin18.7.0/)
EMACS   dir        ~/.emacs.d/
        version    28.0.50
        build      Aug 20, 2020
        buildopts  --disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus@28/28.0.50/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus@28/28.0.50 --with-xml2 --with-gnutls --without-dbus --with-imagemagick --with-modules --with-rsvg --with-ns --disable-ns-self-contained
        features   JPEG TIFF PNG RSVG IMAGEMAGICK GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS PDUMPER LCMS2
        traits     (server-running envvar-file)
DOOM    dir        ~/.dotfiles/emacs/.doom.d/
        version    2.0.9
        build      HEAD -> develop 1456108d5 2020-09-10 18:03:32 -0400
        elc-files  0
        modules    (:completion company ivy :ui deft doom doom-dashboard doom-quit hl-todo modeline ophints (popup +defaults) vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold (format +onsave) snippets :emacs dired electric (undo +tree) vc :os macos :tools editorconfig (eval +overlay) (lookup +docsets +dictionary) lsp magit :lang clojure emacs-lisp (go +lsp) json (javascript +lsp) markdown (org +pomodoro +journal +hugo) sh web yaml :app (rss +org) :config (default +bindings +smartparens))
        packages   ((ob-typescript) (prettier-js) (move-text) (js-doc) (reason-mode))
        unpin      (n/a)
        elpa       (n/a)
```
</details>

**Comment by helderburato** [comment]
I'll close the issue because now the language mode is enabled on Doom and has support to autocomplete with LSP.

Thanks for all the support @qhuyduong!

**Comment by rashkov** [comment]
This is super helpful, thanks everyone. I would just recommend adding `(customize-set-variable
        'flycheck-check-syntax-automatically '(save idle-change idle-buffer-switch mode-enabled))` to the `after! reason-mode` block. That way you'll see error message pop up when you introduce them, instead of only when you save the document. 

Any chance of this getting its own official module?
