### ISSUE TITLE
macOS left option key not triggering meta

### ISSUE THREAD

**Issue by yiglas** [hlissner/doom-emacs#3952]
**What did you expect to happen?**
Holding the left option key on a macOS keyboard should trigger the meta key. Example: `M-:` to bring up the `eval-expression`. 

**What actually happened?**
What is happening: if you use the left option key and click `:`, `…` is printed to the screen. This goes for any key clicked while holding down the left option key. for example: `M-x` prints `≈` instead of trying to bring up the `M-x command`.

**Additional details:**
The right option key works as expected. Loading emacs with an empty config (i.e. not using doom) the left option key works as expected.

**System information:**
<details><pre>
```
SYSTEM  type       darwin
        config     x86_64-apple-darwin18.7.0
        shell      /bin/zsh
        uname      Darwin 18.7.0 Darwin Kernel Version 18.7.0: Mon Apr 27 20:09:39 PDT 2020; root:xnu-4903.278.35~1/RELEASE_X86_64 x86_64
        path       (~/.nvm/versions/node/v12.18.1/bin ~/.gem/ruby/2.3.0/bin /usr/local/Cellar/ruby/2.4.1_1/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /usr/local/share/dotnet ~/.dotnet/tools /Library/Frameworks/Mono.framework/Versions/Current/Commands /Applications/Xamarin Workbooks.app/Contents/SharedSupport/path-bin ~/.sqlpackage ~/.rvm/bin /usr/local/Cellar/emacs-plus@27/27.1/libexec/emacs/27.1/x86_64-apple-darwin18.7.0/)
EMACS   dir        ~/.emacs.d/
        version    27.1
        build      Aug 24, 2020
        buildopts  --disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus@27/27.1/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus@27/27.1 --with-xml2 --with-gnutls --without-dbus --with-imagemagick --with-json --with-modules --with-rsvg --with-ns --disable-ns-self-contained
        features   RSVG IMAGEMAGICK GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS JSON PDUMPER LCMS2 GMP
        traits     (server-running envvar-file)
DOOM    dir        ~/.doom.d/
        version    2.0.9
        build      HEAD -> develop c55391d4a 2020-09-01 06:59:33 -0400
        elc-files  0
        modules    (:completion (company +childframe) ivy :ui doom doom-dashboard hl-todo modeline nav-flash ophints (popup +defaults) (ligatures +fira) treemacs vc-gutter vi-tilde-fringe workspaces (window-select +switch-window) :editor file-templates fold parinfer snippets :emacs dired electric undo vc :checkers syntax (spell +prog +aspell) :tools editorconfig (eval +overlay) gist lookup (lsp +peek) magit :lang clojure common-lisp (csharp +lsp) emacs-lisp javascript markdown org sh :config (default +bindings +smartparens))
        packages   ((prettier-js))
        unpin      (n/a)
        elpa       (n/a)
```
</pre></details>

**Comment by zzamboni** [comment]
It would seem the Option key is being intercepted by macOS and interpreted according to its keyboard rules to generate special symbols - i.e. if you type those key combinations in TextEdit or any other Mac app, you will see the same symbols.

This might depend on the Emacs build you are using. I have not used `emacs-super`, but I used the `emacs-mac` port in the past and it did something similar - e.g. pressing Option-Command-Space brought up the Emoji chooser instead of being processed by Emacs.

I normally map Meta to the Command key, and that seems to work well:
```
(cond (IS-MAC
       (setq mac-command-modifier      'meta
             mac-option-modifier       'alt
             mac-right-option-modifier 'super)))
```

**Comment by yiglas** [comment]
Yeah, it is really strange. Adding that code to my .doom.d config hasn't corrected the issue :(.

Another note: It worked correctly about a month ago when I thought it would be a good time to update to EMACS 27.1 and update doom to the latest develop version. But I don't remember what doom develop version I was on prior to that.

**Comment by matheus208** [comment]
I'm having the same issue. But only when I remap the modifier keys on the OS level (I'm using an external PC keyboard, and I remapped the Windows key to options (meta) and the alt key to command (super). `Super` works but pressing Meta+whatever sends symbols instead of the modifier keys to Emacs.

**Comment by alanthird** [comment]
This is probably a known [bug in Emacs](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=34984). It occurs when the system properties have been used to rebind the modifier keys and an external keyboard is in use.

For some reason macOS reports all the rebound modifiers on the external keyboard as "right" modifiers, even if you're using the "left" modifiers.

Doom is binding ns-right-option-modifier to 'none, so in this situation neither of the option keys on the external keyboard will act as 'meta.

**Comment by zzamboni** [comment]
@alanthird thanks for the link! Funny, through trial and error I figured this was happening and patched my config just the other day to account for it: https://github.com/zzamboni/dot-doom/commit/16b2860ddcd7bc2ec6d52a2221819c94a47575b1#diff-f57e50a2a2368839dc58a0b4aa48a140d9fb40bd25fa482704eb3ea1c9586011

**Comment by hlissner** [comment]
These are Doom's defaults

```elisp
(setq mac-command-modifier      'super
             ns-command-modifier       'super
             mac-option-modifier       'meta
             ns-option-modifier        'meta
             mac-right-option-modifier 'none
             ns-right-option-modifier  'none)
```

From these, they should trigger meta. If you are experiencing otherwise, it's likely because of your own settings for these variables, so I'll consider this a local issue.

Note: Mitsuharu Yamamoto's Emacs fork for MacOS uses `mac-*` variables and the NS/Darwin build uses `ns-*`. You have to set the right variable depending on which build you're using (or just set them both, as Doom does).
