### ISSUE TITLE
Private autoloads don't work when .doom.d's contents are symlinked

### ISSUE THREAD

**Issue by ricklupton** [hlissner/doom-emacs#3955]
**What did you expect to happen?**
Autoloads in `~/.doom.d/autoload/misc.el` would be autoloaded.

**What actually happened?**
They are not autoloaded, and don't appear in ` ~/.emacs.d/.local/autoloads.el`

**Additional details:**
The files within my `~/.doom.d` are symlinked to the actual files in `~/.dotfiles/doom.d`.

**Steps to reproduce:**
1. Have an autoloads file in .doom.d symlinked as above
2. Run `doom sync`
3. Any autoloads in the symlinked file are not collected

**System information:**
<details><pre>
((system
  (type . darwin)
  (config . "x86_64-apple-darwin19.5.0")
  (shell . "/bin/zsh")
  (uname . "Darwin 19.6.0 Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64")
  (path "~/bin" "/usr/local/opt/mysql@5.7/bin" "~/.poetry/bin" "/usr/local/bin" "/usr/bin" "/bin" "/usr/sbin" "/sbin" "/Applications/VMware Fusion.app/Contents/Public" "/Library/TeX/texbin" "/opt/X11/bin" "/Applications/Wireshark.app/Contents/MacOS" "~/.poetry/bin" "~/.local/bin" "~/.local/bin" "~/.emacs.d/bin" "~/Library/Python/3.8/bin" "/usr/local/Cellar/emacs-mac/emacs-27.1-mac-8.0/libexec/emacs/27.1/x86_64-apple-darwin19.5.0"))
 (emacs
  (dir . "~/.emacs.d/")
  (version . "27.1")
  (build . "Aug 20, 2020")
  (buildopts . "--enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-mac/emacs-27.1-mac-8.0/share/info/emacs --prefix=/usr/local/Cellar/emacs-mac/emacs-27.1-mac-8.0 --with-mac --enable-mac-app=/usr/local/Cellar/emacs-mac/emacs-27.1-mac-8.0 --with-gnutls --with-modules")
  (features . "NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS JSON PDUMPER GMP")
  (traits batch server-running envvar-file))
 (doom
  (dir . "~/.doom.d/")
  (version . "2.0.9")
  (build . "HEAD -> develop 1456108d5 2020-09-10 18:03:32 -0400")
  (elc-files . 0)
  (modules :completion company (helm +fuzzy) :ui deft doom doom-dashboard doom-quit hl-todo hydra minimap modeline ophints (popup +defaults) treemacs vc-gutter vi-tilde-fringe (window-select +switch-window) workspaces :editor (evil +everywhere) file-templates fold (format +onsave) multiple-cursors snippets word-wrap :emacs dired electric undo vc :term vterm :checkers syntax spell :tools biblio direnv (eval +overlay) (lookup +dictionary +offline) lsp (magit +forge) pdf :lang clojure data emacs-lisp json javascript (latex +cdlatex) lua markdown (org +roam +jupyter +present +pomodoro) (python +lsp) sh yaml :email mu4e :os macos :config literate (default +bindings +smartparens))
  (packages (org-ref :pin "9465ab") (graphviz-dot-mode :pin "3642a0a") (org-roam-bibtex :pin "89e9121f26cf03bb7820d257cd9d9106916cd1e9" :recipe (:host github :repo "org-roam/org-roam-bibtex")) (org-roam :pin "89e9121f26cf03bb7820d257cd9d9106916cd1e9") (org-roam-server :pin "fe0364ef63928337f442c1d987d17cfe9619df2d") (sparql-mode :pin "62f198256453265af48bef3a0207e80143fbff1e") (ttl-mode :pin "b8f0a3f5125542ec411e4def1f64c4ac087e0140" :recipe (:host github :repo "jeeger/ttl-mode")) (deadgrep) (org-re-reveal :pin "27a0ce45523255b66e7b14567837f0358a747d09"))
  (unpin org-roam org-roam-bibtex company-org-roam bibtex-completion helm-bibtex ivy-bibtex)
  (elpa "n/a")))</pre></details>

**Comment by ricklupton** [comment]
I think this is due to the use of `file-truename` [here](https://github.com/hlissner/doom-emacs/blob/e632871a115528a9c1ce90d7d2147873009716eb/core/core-modules.el#L221). This is applied to the autoloads path but not to `doom-private-dir`, so [this test](https://github.com/hlissner/doom-emacs/blob/e632871a115528a9c1ce90d7d2147873009716eb/core/core-modules.el#L231) always fails.

This could also be the cause of https://github.com/hlissner/doom-emacs/issues/2288

**Comment by gagbo** [comment]
It shouldn’t matter. [file-in-directory-p](https://github.com/emacs-mirror/emacs/blob/44ad4a15a0099285a16018ad790419cb60df5815/lisp/files.el#L5625) uses `file-truename on both its arguments`, as stated in the [documentation](https://www.gnu.org/software/emacs/manual/html_node/elisp/Truenames.html#Truenames)

**Comment by ricklupton** [comment]
I guess more specifically there is a problem because `doom-private-dir` is not symlinked, but the files within it are (this is the default result of using [rcm](https://github.com/thoughtbot/rcm) to manage dotfiles).

```elisp
(file-truename "~/.doom.d/autoload/misc.el")
;; "/Users/xxx/.dotfiles/doom.d/autoload/misc.el"

doom-private-dir
;; "~/.doom.d/"

(file-truename doom-private-dir)
;; "/Users/xxx/.doom.d/"

(file-in-directory-p (file-truename "~/.doom.d/autoload/misc.el") doom-private-dir)
;; nil
```

I'd like the last test to return true so that my autoload file is recognised by Doom. I'm not sure if there's any automatic way of fixing this; perhaps I just need to set `doom-private-dir` manually to the target of the symlink (~/.dotfiles/doom.d).

**Comment by hlissner** [comment]
> perhaps I just need to set doom-private-dir manually to the target of the symlink (~/.dotfiles/doom.d).

I think this is your only choice. By linking the contents of `~/.dotfiles/doom.d` instead of the folder itself, you have created a non-standard directory structure. Accommodating this is non-trivial (much more complicated than simply removing that `file-truename` call, and that `file-in-directory-p` uses `file-truename` works against us here) and would require a redesign of Doom's core (and sacrifice of some of our optimizations -- resolving symlinks can be expensive in the long run), unfortunately, which is exceptionally low priority when a workaround for non-standard setups already exists (an explicit `DOOMDIR`).

**Comment by ricklupton** [comment]
Makes sense, thank you.

I only have it set up this way because that’s what rcm does so perhaps the solution is to use a different tool to manage dot files.

**Comment by jedahan** [comment]
Is this also the case if `~/.emacs.d` is symlinked even if ~/.config/doom is not?

**Comment by hlissner** [comment]
@jedahan No. It doesn't matter if `~/.emacs.d`, `~/.config/emacs`, `~/.doom.d` or `~/.config/doom` are symlinks. What matters if the files _inside_ those directories are symlinked. Accommodating every permutation of symlink arrangment _inside_ those directories is impossible.

**Comment by jedahan** [comment]
ahh thanks for clarification, awesome
