### ISSUE TITLE
Turning off Big Font mode reset the font size

### ISSUE THREAD

**Issue by jsmestad** [hlissner/doom-emacs#3958]
**Describe the feature**

When turning on big font mode with `SPC t b` everything works as expected. However when you toggle it off by running `SPC t b` again, the font does not reset to normal size it just stays at the big font size. It would be great if this would reset the font back to normal non big font size so it behaves like a toggle.

**Comment by thevirtuoso1973** [comment]
This sounds like a bug, although I cannot reproduce it. It acts like a toggle for me. 
Can you specify if it occurs with a specific file type/mode? Can you provide your config/init.el?

**Comment by jsmestad** [comment]
@thevirtuoso1973 my config for fonts can be found [here](https://github.com/jsmestad/dfiles/blob/master/.doom.d/config.el#L12-L25).

This happens in any mode. [Here is a video](https://www.youtube.com/watch?v=4q68787s028&feature=youtu.be) I recorded showing it in a fresh Doom Emacs window

**Comment by thevirtuoso1973** [comment]
@jsmestad Okay I'm able to reproduce the bug with your config. 
This appears to occur when you don't set the `:size` argument in your `font-spec`. (It's possible that that isn't a valid font spec but I'm not sure.) 
Anyway, try adding `:size 10.0`, for example, to your font-specs on line 24 & 25. This should fix it for now.

**Comment by jsmestad** [comment]
Awesome that seems to do the trick.

Height is part of font-spec, so is this a bug or should we just close this out?

**Comment by thevirtuoso1973** [comment]
We could change the issue to 'bug' so this gets a bit more attention. Either way: we should probably be notified if it's an invalid font-spec, and if it's not, then there's a bug in Big Font mode.
