### ISSUE TITLE
Back to indentation and beginning of line woes while in visual-line-mode

### ISSUE THREAD

**Issue by UndeadKernel** [hlissner/doom-emacs#396]
### Observed behavior

When in visual-line-mode, the function `doom/backward-to-bol-or-indent` does not properly move between the indentation and beginning of line.

### Expected behavior

When in visual-line-mode, the function `doom/backward-to-bol-or-indent` should move the cursor between the indentation point and the beginning of line.

### Cause

The function is currently defined as follows:
```lisp
(defun doom/backward-to-bol-or-indent ()
  "Move back to the current line's indentation. If already there, move to the
beginning of the line instead. If at bol, do nothing."
  (interactive)
  (if (bound-and-true-p visual-line-mode)
      (beginning-of-visual-line)
    (let ((ci (current-indentation))
          (cc (current-column)))
      (cond ((or (> cc ci) (= cc 0))
             (back-to-indentation))
            ((<= cc ci)
             (beginning-of-visual-line))))))
```
`beginning-of-visual-line` does not take into account indentation.
Questions: isn't the last call to `beginning-of-visual-line` not adequate? That is, the `if` statement checks if visual-line-mode is on or not, if it's not, the function `beginning-of-visual-line` might still be executed. Is this desired?

### System information

<details>
<summary>Click to expand</summary>

```
DOOM Doctor
Running Emacs v25.3.1, commit 523c6ae4ccf07070a9728ac21e1dad00cbb8a61b

shell: /bin/zsh
Compiled with:
  XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS
  NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB
  TOOLKIT_SCROLL_BARS GTK3 X11 MODULES
uname -a:
  Linux OfficeZombie 4.14.15-1-ARCH #1 SMP PREEMPT Tue Jan 23 21:49:25
  UTC 2018 x86_64 GNU/Linux

Attempt to load DOOM: success! Loaded v2.0.9
Revision 523c6ae4ccf07070a9728ac21e1dad00cbb8a61b

----

test-emacs
test-windows
test-fonts
Found font material-design-icons.ttf
Found font weathericons.ttf
Found font octicons.ttf
Found font fontawesome.ttf
Found font file-icons.ttf
Found font all-the-icons.ttf
test-gnutls
test-tls
Validated https://elpa.gnu.org
Validated https://melpa.org
Successfully rejected https://self-signed.badssl.com
Successfully rejected https://wrong.host.badssl.com/
test-tar
Everything seems fine, happy Emacs’ing!

```
</details>

**Comment by hlissner** [comment]
I've rewritten both `doom/backward-to-bol-or-indent` and `doom/forward-to-last-non-comment-or-eol` to improve visual-line-mode support. Let me know if it doesn't work for you.
