### ISSUE TITLE
"SPC u SPC s p" search another project instead of search current project include ignored files

### ISSUE THREAD

**Issue by ezchi** [hlissner/doom-emacs#3960]
**What did you expect to happen?**
According to the `ivy` module REAME, prefixing `SPC s p` should search current project including ignored files. 

**What actually happened?**
But with prefixing, it asks for another project.

**Steps to reproduce:**
1. `SPC u SPC s p`
2. expect to ask for search pattern, but instead it ask for another project.

**Comment by hlissner** [comment]
The docs are outdated. Will fix this soon.

To include ignored files in your search either:

1. Prefix your search with `-u -- ` to search (git)ignored files. `-uu -- ` to search hidden (dot) files/folders.
2. Or suffix them: `query -- -u` or `query -- -uu`.
