### ISSUE TITLE
(setq rmh-elfeed-org-files (list "~/.doom.d/org-notes/elfeed.org"))

### ISSUE THREAD

**Issue by iT-Boyer** [hlissner/doom-emacs#3965]
I config for elfeed by this:
```
(setq rmh-elfeed-org-files (list "~/.doom.d/org-notes/elfeed.org"))
```
when run `M-x elfeed-update` but ,it don't work.

**Comment by hlissner** [comment]
When filing a bug report please include as much information about the issue as possible. If you don't, I likely won't be able to help you.

1. Never assume "it doesn't work" is enough of an explanation. _Why_ do you think it doesn't work? What happened when you tried it? Any errors/warnings in \*Messages\* (`SPC h e` or `C-h e` to open it) after `M-x elfeed-update`?

2. Always include information about your system. If there is an issue template (and there is for this project), _please do not ignore it_. Ours asked you to include the output of `M-x doom/info` or running `~/.emacs.d/bin/doom info` on the command line. This tells us vital information about your system.

3. If you have links to your private configuration, or to the tutorial you tried to follow that got you here, those would help tremendously.

-----

As it is, this is not an acceptable bug report. Please edit your original post and add this crucial information.
