### ISSUE TITLE
load-theme, when called with 'noconfirm, misbehaves.

### ISSUE THREAD

**Issue by t-e-r-m** [hlissner/doom-emacs#3967]
I'm using Emacs 28/native-comp on Debian Stable. With modus-themes (modus-operandi-theme and modus-vivendi-theme on MELPA), setting the `modus-vivendi-theme-override-colors-alist` and `modus-operandi-theme-override-colors-alist` has no effect. This is an issue with DOOM, and maybe specifically with Emacs 28. This can not be replicated on vanilla emacs.

Changing / loading the theme via `customize-themes` does not present this issue.

**What did you expect to happen?**
I expected the alist to be applied to the current theme

**What actually happened?**
Nothing changed.

**Additional details / possible fix:**
It seems to be an issue with the following:
https://github.com/hlissner/doom-emacs/blob/1456108d5bef89195b2b63f962e0ae9d24f4c652/core/autoload/themes.el#L58
Changing it to
```elisp
(load-theme doom-theme)
```
Fixes the issue.

**Steps to reproduce:**
1. `(package! modus-vivendi-theme)`
2. Set custom colors. The following are easily distinguishable:
https://gitlab.com/protesilaos/modus-themes/blob/master/doc/modus-themes.org#L995-1020
3. Reload theme / set theme using DOOM's custom theme functions (`(setq doom-theme name)` and then `(doom/reload-theme)`)

**System information:**
<details>

```
SYSTEM  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/bash
EMACS   dir        ~/.emacs.d/
        version    28.0.50
        features   XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND DBUS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES NATIVE_COMP THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER LCMS2
        traits     (server-running chemacs)
DOOM    dir        ~/.doom.d/
        version    2.0.9
        elc-files  0
        unpin      (n/a)
        elpa       (n/a)
```
</details>

**Comment by ppoloskov** [comment]
Hi @t-e-r-m We have a discussion about a similar issue at https://gitlab.com/protesilaos/modus-themes/-/issues/102
Could you please try the recipe that worked for me - set the theme as safe via `(custom-safe-themes...)` and load it using `(after-init-hook)`?

The example that works for me (depending on the version of the theme yours `(custom-safe-themes...)` might be different):

``` emacs-lisp 
(leaf modus-operandi-theme
  :ensure t
  :setq
  (modus-operandi-theme-slanted-constructs . t)
  (modus-operandi-theme-override-colors-alist .
                                              '(("bg-main" . "#fbf8ef")))
  :config
  (add-hook 'after-init-hook (lambda ()
			       (load-theme 'modus-operandi)
			       ))
  )
(custom-set-variables
 '(custom-safe-themes
   '("b72ffe34e9ff6ec347cb8fc86d3f214e999363d46022e784324f2a4fe60dcff4" default))
)

```

**Comment by hlissner** [comment]
With Doom, so long as the package is installed this is all you need:

```elisp
;; in ~/.doom.d/packages.el
(package! modus-operandi-theme)

;; in ~/.doom.d/config.el
(setq doom-theme 'modus-operandi)
```

Remember to run `doom sync` and restart Emacs (to ensure the package is installed).

-----

As for setting `modus-operandi-theme-override-colors-alist`, this won't ever work because it is only used in `modus-operandi-theme-with-color-variables` (a macro), which is expanded at compile time. When modus-operandi-theme is byte-compiled (when it is installed), the colors are baked in. This could be considered an upstream issue.

Only way around it is to change `modus-operandi-theme-with-color-variables` from `~/.doom.d/init.el`, uninstall the package, then reinstall it.

**Comment by t-e-r-m** [comment]
> set the theme as safe via `(custom-safe-themes...)`

That's exactly what I've been using. It does mitigate the issue for me.



> As for setting `modus-operandi-theme-override-colors-alist`, this won't ever work because it is [only used in modus-operandi-theme-with-color-variables](https://gitlab.com/protesilaos/modus-themes/blob/master/modus-operandi-theme.el#L1336) (a macro), which is expanded at compile time later in the file (not within an eval-and-compile). When modus-operandi-theme is byte-compiled (when it is installed), the colors are baked in. This could be considered an upstream issue.
> 
> Only way around it is to change `modus-operandi-theme-with-color-variables` from `~/.doom.d/init.el`, uninstall the package, then reinstall it. Changes in init.el are in scope of the package manager.

Thanks for the explanation! Wouldn't have guessed it. I'll just download it to my themes folder, and update when necessary.
