### ISSUE TITLE
How to disable childframe in tty, it is broken

### ISSUE THREAD

**Issue by tami5** [hlissner/doom-emacs#3968]
Hay there, I want to disable childframe in tty mode, it breaks. Any suggestions?

**Comment by even4void** [comment]
Just my 2¢: I don't think this is specific to the `tty` module, and there are various packages that implement so-called "childframe" (e.g., `ivy-posframe`, `company-box`). You're better off deactivating those packages (or removing hooks when available) when running in a terminal.

**Comment by hlissner** [comment]
Childframes do not work in the terminal. Remove the `+childframe` flag from the [modules that support it](https://github.com/hlissner/doom-emacs/blob/develop/docs/modules.org).
