### ISSUE TITLE
Feature request: https://github.com/elkowar/rnix-lsp

### ISSUE THREAD

**Issue by magnetophon** [hlissner/doom-emacs#3973]
A WIP Language Server for Nix!

It uses https://github.com/mlvzk/manix, a fast CLI documentation searcher for Nix.

**Comment by ymarco** [comment]
Should be forwarded to [lsp-mode](https://github.com/emacs-lsp/lsp-mode), once its supported there adding it to Doom should be trivial

**Comment by magnetophon** [comment]
Done: https://github.com/emacs-lsp/lsp-mode/issues/2209

**Comment by numkem** [comment]
I’m really not an expert but I got it working by doing something like this:

```(after! lsp-mode
 (add-to-list 'lsp-language-id-configuration '(nix-mode . "nix"))
 (lsp-register-client
  (make-lsp-client :new-connection (lsp-stdio-connection '("rnix-lsp"))
                   :major-modes '(nix-mode)
                   :server-id 'nix)))

(use-package! nix-mode
 :interpreter ("\\(?:cached-\\)?nix-shell" . +nix-shell-init-mode)
 :mode "\\.nix\\'"
 :init
 (add-hook! 'nix-mode-local-vars-hook #'lsp!)
 :config
 (set-repl-handler! 'nix-mode #'+nix/open-repl)

 (map! :localleader
     :map nix-mode-map
     "f" #'nix-update-fetch
     "p" #'nix-format-buffer
     "r" #'nix-repl-show
     "s" #'nix-shell
     "b" #'nix-build
     "u" #'nix-unpack
     "o" #'+nix/lookup-option))```

**Comment by magnetophon** [comment]
@numkem Thanks a lot!

Unfortunately,I'm even less of an exert then you are, and I'm having a few problems:

There seems to be an extra `)` on the line with `server-id`.

More importantly, I get the following error:
```
Warning (initialization): An error occurred while loading ‘/home/bart/.emacs.d/init.el’:

Error in private config: config.el, (void-variable lsp-language-id-configuration)

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.
```

Any ideas?

**Comment by nbfalcon** [comment]
@magnetophon try wrapping the entire thing in `(after! lsp)`. Doom tries hard to lazy-load everything, so that variable isn't defined when your config is loaded.

**Comment by magnetophon** [comment]
@nbfalcon Thanks, that was it!  :)

**Comment by hlissner** [comment]
I don't recall when, but lsp-mode apparently added support for rnix-lsp [back in August](https://github.com/emacs-lsp/lsp-mode/commit/87033228302d8319e1cb68ce7a704f18b6e1beb0#diff-32a52f22910769f3a77dc26a6b03e754d28fc65eae884e25431b7500e810821f) so I'll consider this resolved. Thanks for bringing it to my attention!
