### ISSUE TITLE
[nativecomp] sandbox behaves weirdly

### ISSUE THREAD

**Issue by A6GibKm** [hlissner/doom-emacs#3975]
**What did you expect to happen?**
Running `doom/sandbox` (Doom + modules - your private config) should open a sandboxed instance of doom without my personal doom`config.

**What actually happened?**
Sometimes it works, sometimes it throws errors. In any case, once it opens, emacs will try to natively compile packages, producing a state in which you can't use Emacs normally again without running `doom sync`.

A possible error I get while running the sandox instance is
```
(void-variable +magit--ignore-version-a)
```
Afterwards running `emacs` will throw the same error until `doom sync` is executed.

**Additional details:**
- Using nativecomp build.
- Fedora Silverblue 32
- Doom: HEAD -> develop 1456108d 2020-09-10 18:03:32 -0400 (latest commit)

**Comment by tgbugs** [comment]
This is probably related to https://github.com/hlissner/doom-emacs/issues/3901.

**Comment by hlissner** [comment]
As of b29b865 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
