### ISSUE TITLE
org-pdftools slows down org-mode significantly

### ISSUE THREAD

**Issue by stites** [hlissner/doom-emacs#3979]
**What did you expect to happen?**

Given the following configs on debian buster (not a frankendebian) with emacs-27.1 (installed via nix derivation), I expect the org-capture pane to take < 20s to appear: 

config.el:
```lisphttps://github.com/hlissner/doom-emacs/issues/3979
;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-

(setq user-full-name "Sam"
      user-mail-address "Sam's email")
```

init.el:
```lisp
(doom! :input
       :ui
       doom              ; what makes DOOM look the way it does
       doom-dashboard    ; a nifty splash screen for Emacs

       :editor
       (evil +everywhere); come to the dark side, we have cookies

       :tools
       pdf      ;;;; <<< this is the problem

       :lang
       (org +capture)
       :config
       (default +bindings))
```
package.el: none

Empirically, this not only effects org-capture but a lot of org-functionality (collapsing a TODO, was another). It is also worth pointing out that this change happened after a recent update of doom.

**What actually happened?**

org-capture takes >20s (maybe more like 1-2min) to appear. Screen capture can be found here:

https://s3-us-west-1.amazonaws.com/static.stites.io/Screencast_fixed.mp4

**Steps to reproduce:**
- nuke everything
- add configs from above
- doom purge && doom sync
- open emacs
- open capture with `SPC X`

<details>
  <summary>profile-report points to `org-pdftools-store-link`</summary>
<pre>
Function                                                                                CPU samples    %
- command-execute                                                                             33506  99%
 - call-interactively                                                                         33506  99%
  - funcall-interactively                                                                     33496  99%
   - org-capture                                                                              33492  99%
    - org-store-link                                                                          33472  99%
     - org-pdftools-store-link                                                                33462  99%
      - load-with-code-conversion                                                             33462  99%
       - eval-buffer                                                                          33462  99%
        - require                                                                             33460  99%
         - byte-code                                                                          33447  99%
          - require                                                                           33447  99%
           - byte-code                                                                        33354  99%
              char-displayable-p                                                              33336  99%
            + require                                                                            12   0%
</pre>
</details>

**System information:**
<details><pre>
((system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/bin/bash")
  (uname . "Linux 4.19.0-10-amd64 #1 SMP Debian 4.19.132-1 (2020-07-24) x86_64")
  (path "/nix/store/fvkwfry7q5v9n422839qwdi5sn7j90k4-emacs-packages-deps/bin" "~/.nix-profile/bin" "/opt/anaconda/bin" "/opt/anaconda/condabin" "~/.cargo/bin" "~/.local/bin" "/usr/local/sbin" "/usr/sbin" "~/.tmuxifier/bin" "~/.emacs.d/bin" "~/.local/bin" "~/.nix-profile/bin" "~/.nix-profile/bin" "/usr/local/bin" "/usr/bin" "/bin" "/usr/local/games" "/usr/games" "/snap/bin" "/nix/store/i2afxpb95rl38h1a8362w0sby8gp5x8w-emacs-unstable-emacs-27.1/libexec/emacs/27.1/x86_64-pc-linux-gnu"))
 (emacs
  (dir . "~/.emacs.d/")
  (version . "27.1")
  (build . "Sep 25, 2020")
  (buildopts . "--prefix=/nix/store/i2afxpb95rl38h1a8362w0sby8gp5x8w-emacs-unstable-emacs-27.1 --disable-build-details --with-modules --with-x-toolkit=gtk3 --with-xft --with-cairo CFLAGS=-DMAC_OS_X_VERSION_MAX_ALLOWED=101200")
  (features . "XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND DBUS GSETTINGS GLIB NOTIFY INOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP")
  (traits batch server-running))
 (doom
  (dir . "~/.config/doom/")
  (version . "2.0.9")
  (build . "HEAD -> develop 1456108d 2020-09-10 18:03:32 -0400")
  (elc-files . 0)
  (modules :ui doom doom-dashboard :editor (evil +everywhere) :tools pdf :lang (org +capture) :config (default +bindings))
  (packages "n/a")
  (unpin "n/a")
  (elpa "vterm")))

</pre></details>

**Comment by tecosaur** [comment]
One minor issue:
![image](https://user-images.githubusercontent.com/20903656/94355489-05b9a600-00b7-11eb-8afd-113f6c683214.png)

Also `char-displayable-p` seems to check if a character can be found in your system fonts. What does `find /usr/share/fonts/ -type f | wc -l` give?

**Comment by stites** [comment]
```
$ find /usr/share/fonts/ -type f | wc -l
4661
```
RE: broken image -- very weird! It looks like this works on chromium, but not firefox. I'll fix this in a bit.

**Comment by robbert-vdh** [comment]
Regarding the video, the pixel format is `yuv444p` and Firefox [doesn't support these kinds of videos](https://bugzilla.mozilla.org/show_bug.cgi?id=1368063) because even though ffmpeg can decode them just fine, the system decoders on macOS and Windows can't so they've disabled playback for these kinds of videos on all platforms.

**Comment by stites** [comment]
Ah, the unexplored world of video encoding -- good to know! I think this version should do the trick. I'll edit the issue as well/

https://s3-us-west-1.amazonaws.com/static.stites.io/Screencast_fixed.mp4

Of note:
- from 0:00 -> 2:30, this is just me showing the steps I took to reproduce the error
- around 2:30 shows emacs becoming unresponsive
- 2:50ish shows some `strace` outputs -- this goes on until about 4:50
- after this, pdf tools needs to compile its dependency.
- at ~5:26 I basically just do everything all over again to demonstrate that every first capture after boot produces the same result and this isn't dependent on the pdf-tools dependency not being present.

**Comment by stites** [comment]
I've narrowed down the issue to https://github.com/hlissner/doom-emacs/blob/ea3502376571b18c66c690e7cfda832e2bd850a3/modules/lang/org/config.el#L936 but I'm not sure what this function does and why it is being triggered on org-capture.

**Comment by hlissner** [comment]
I cannot reproduce this by mirroring your config or steps, using the same emacs 27.1 build on nixpkgs stable. It invokes the org-capture popup instantly, and without issue.

It appears to hang on `char-displayable-p`, which would imply a font or encoding issue. Perhaps reinstalling Emacs is your best bet. Or running `doom build`. I'm afraid I don't know where else to look for this.

**Comment by stites** [comment]
Thanks for looking into this @hlissner -- closing this since it can't be reproduced.

I'll look into font issues next and report back here if I find the problem.
