### ISSUE TITLE
Failed to download ‘gnu’ archive behind proxy

### ISSUE THREAD

**Issue by yuanl** [hlissner/doom-emacs#398]
### Observed behavior
I do have a working proxy setup for other program(e.g. curl, browser, python). But doom-emacs failed to install.
`INSECURE=1 make install` wouldn't help.
<details>
<summary>stdout: click to expand</summary>

```
make --trace install
Makefile:87: target '.local/autoloads.el' does not exist
emacs --quick --batch --eval '(setq user-emacs-directory default-directory)' -l core/core.el -f doom-initialize-autoloads
Installing core packages
Importing package-keyring.gpg...
Importing package-keyring.gpg...done
Using a proxy for https...
Contacting host: localhost:3128
Failed to download ‘gnu’ archive.
Package refresh done
Failed to download ‘melpa’ archive.
Eager macro-expansion failure: (error "Package ‘persistent-soft-’ is unavailable")
Installing core packages
Importing package-keyring.gpg...
Importing package-keyring.gpg...done
Failed to download ‘gnu’ archive.
Package refresh done
Failed to download ‘melpa’ archive.
Eager macro-expansion failure: (error "Package ‘persistent-soft-’ is unavailable")
Installing core packages
Importing package-keyring.gpg...
Importing package-keyring.gpg...done
Contacting host: localhost:3128
Failed to download ‘gnu’ archive.
Package refresh done
Failed to download ‘melpa’ archive.
Package ‘persistent-soft-’ is unavailable
Makefile:87: recipe for target '.local/autoloads.el' failed
make: *** [.local/autoloads.el] Error 255

```
</details>

### Steps to reproduce

1. export https_proxy=http://localhost:3128
1. git clone https://github.com/hlissner/doom-emacs ~/.emacs.d
1. cd ~/.emacs.d
1. cp init.example.el init.el  # maybe edit init.el
1. make install

### System information

<details>
<summary>Click to expand</summary>

```
DOOM Doctor
Running Emacs v25.3.2, commit 5dacbb7cb1c6ac246a9ccd15e6c4290def67757c

shell: /bin/bash
Compiled with:
  XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS
  NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB
  TOOLKIT_SCROLL_BARS GTK3 X11 MODULES
uname -a:
  Linux cnbjlx23123 4.4.0-112-generic #135-Ubuntu SMP Fri Jan 19
  11:48:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Attempt to load DOOM: failed
  (Cannot open load file No such file or directory async-autoloads)

----

test-emacs
test-windows
test-fonts
test-gnutls
test-tls
Validated https://elpa.gnu.org
Validated https://melpa.org
Validated https://self-signed.badssl.com (this shouldn’t happen!)
Validated https://wrong.host.badssl.com/ (this shouldn’t happen!)
test-tar

====
Have some debug information:

  + byte-compiled files:
    n/a                                    

  + exec-path:
    /home/CORPUSERS/288xxxxxx/bin
    /home/CORPUSERS/288xxxxxx/.local/bin
    /usr/local/sbin
    /usr/local/bin
    /usr/sbin
    /usr/bin
    /sbin
    /bin
    /usr/games
    /usr/local/games
    /usr/lib/x86_64-linux-gnu/emacs/25.3/x86_64-linux-gnu

  + PATH:
    /home/CORPUSERS/288xxxxxx/bin
    /home/CORPUSERS/288xxxxxx/.local/bin
    /usr/local/sbin
    /usr/local/bin
    /usr/sbin
    /usr/bin
    /sbin
    /bin
    /usr/games
    /usr/local/games

----
There were issues!
```
</details>

**Comment by yuanl** [comment]
The install goes well if I forward tcp traffic to a local transparent proxy.
It can't go through the https_proxy for some reason.

**Comment by driftcrow** [comment]
I use proxychains ,It work fine.

**Comment by hlissner** [comment]
Do the answers in https://stackoverflow.com/questions/1595418/emacs-behind-http-proxy#1595673 help you? I've never used Emacs behind a proxy, so I'm afraid I know little about it, but the link above looked promising.

**Comment by yuanl** [comment]
Thanks for the suggestion.
Answer in the link above do not help. I feel like it is our cooperate proxy that causing this trouble. Emacs did picking up the proxy setting from environment.

**Comment by Vezill** [comment]
So I've run into this issue but was able to solve it by adding in the proxy information at the top of early-init.el. The problem now is that if I want to pull the latest commits I need to remove then add this code back each time, and attempting to add it to my own config.el stops the doom script from using the proxy. Is there a preferred/better way to add user customizations to early-init @hlissner ?

**Comment by hlissner** [comment]
@Vezill Will adding them to `~/.doom.d/init.el` not work?

**Comment by Vezill** [comment]
I originally had them in ~/.doom.d/config.el, but moving it into the top of ~/.doom.d/init.el looks like it worked, thanks for the tip. I originally didn't want to modify that file to make diffing it with the example one easier, but this works fine.
