### ISSUE TITLE
Cannot install doom using current (2020-09-24 or newer) gccEmacs

### ISSUE THREAD

**Issue by vlaci** [hlissner/doom-emacs#3983]
Doom cannot be installed in a clean environment if gccEmacs is compiled from https://github.com/emacs-mirror/emacs/commit/db354ffd578a46d898cac161ea1de1b42f96d2a0 or newer revisions.

**Steps to reproduce:**
The easiest way to reproduce is to use [this](https://hub.docker.com/r/andreacorallo/emacs-nativecomp) docker image:
```terminal
$ docker run -ti --network host andreacorallo/emacs-nativecomp
# apt update
# apt install git
# git clone --depth 1 https://github.com/hlissner/doom-emacs ~/.emacs.d
#  ~/.emacs.d/bin/doom -y install
```

After a while, doom install will stall, and the compiler worker processes are exited.
A workaround is to ctrl+c and run `doom install` again.

Aplying the following patch to Emacs also gets rid of the problem:

```patch
diff --git a/lisp/emacs-lisp/comp.el b/lisp/emacs-lisp/comp.el
index cac63a5978..6b7616ccba 100644
--- a/lisp/emacs-lisp/comp.el
+++ b/lisp/emacs-lisp/comp.el
@@ -2597,7 +2597,7 @@ Return the its filename if found or nil otherwise."
 ;;;###autoload
 (defun comp-subr-safe-advice (subr-name)
   "Make SUBR-NAME effectively advice-able when called from native code."
-  (unless (or (memq subr-name comp-never-optimize-functions)
+  (unless (or t (memq subr-name comp-never-optimize-functions)
               (gethash subr-name comp-installed-trampolines-h))
     (let ((trampoline-sym (comp-trampoline-sym subr-name)))
       (cl-assert (subr-primitive-p (symbol-function subr-name)))
```

**Additional details:**
Tracing the build process with strace reveals that the builders exit because of a `native-compiler-error-empty-byte` signal during compiling autoloads. 

I am aware that this issue may be with gccEmacs and not Doom itself but I am yet to reproduce it outside of Doom.

**Comment by AndreaCorallo** [comment]
Do you know what's `subr-name` in the last call to `comp-subr-safe-advice` before crashing?
May be sufficient to just add like `(message "XXX %s" subr-name)` at the beginning of  `comp-subr-safe-advice` and see what's the sequence of calls.

**Comment by vlaci** [comment]
subr-name is `make-process`.

**Comment by FilipeAzero** [comment]
Had the same problem with 28/native-comp. Now it's working pretty fine

**Comment by Karrq** [comment]
I just installed doom with gccemacs on my arch linux:
I installed `emacs-native-comp-git` package from the AUR then did the normal doom installation...

**Comment by vlaci** [comment]
I too could not reproduce this issue anymore. Thanks for checking!
