### ISSUE TITLE
Error in a Doom startup hook: recentf-mode, (end-of-file "/home/user/.emacs.d/.local/cache/recentf"

### ISSUE THREAD

**Issue by ThePrivacyGuide** [hlissner/doom-emacs#3985]
**What did you expect to happen?**
Open Recent file, Open Bookmarks, just various normal things

**What actually happened?**
Nothing opened, just a message down below saying: Error in a Doom startup hook: recentf-mode, (end-of-file "/home/user/.emacs.d/.local/cache/recentf"

When I retry one or two times, usually everything open up normally.

**Additional details:**

```
Open org-agenda (org-agenda)
Recently opened files (recentf-open-files)
Open project (projectile-switch-project)
Recently opened files (recentf-open-files)
Loading /home/user/.emacs.d/.local/cache/recentf...
eval-buffer: End of file during parsing: /home/user/.emacs.d/.local/cache/recentf
Loading /home/user/.emacs.d/.local/cache/recentf...
eval-buffer: End of file during parsing: /home/user/.emacs.d/.local/cache/recentf
Loading /home/user/.emacs.d/.local/cache/recentf...
eval-buffer: End of file during parsing: /home/user/.emacs.d/.local/cache/recentf
Open project (projectile-switch-project)
Jump to bookmark (bookmark-jump)
Open project (projectile-switch-project)
Recently opened files (recentf-open-files)
Loading /home/user/.emacs.d/.local/cache/recentf...
condition-case: Error in a Doom startup hook: recentf-mode, (end-of-file "/home/user/.emacs.d/.local/cache/recentf")
```

Backtrace:

```
Debugger entered--Lisp error: (doom-hook-error recentf-mode (end-of-file "/home/user/.emacs.d/.local/cache/recentf"))
  signal(doom-hook-error (recentf-mode (end-of-file "/home/user/.emacs.d/.local/cache/recentf")))
  (condition-case e (funcall hook) ((debug error) (signal 'doom-hook-error (list hook e))))
  doom-try-run-hook(recentf-mode)
  run-hook-wrapped(doom-try-run-hook recentf-mode)
  doom-first-file-hook-h(nil t)
  apply(doom-first-file-hook-h (nil t))
  #f(advice-wrapper :before #f(advice-wrapper :around #f(compiled-function (&optional error warn noauto after-find-file-from-revert-buffer nomodes) "Called after finding a file and by the default revert function.\nSets buffer mode, parses file-local and directory-local variables.\nOptional args ERROR, WARN, and NOAUTO: ERROR non-nil means there was an\nerror in reading the file.  WARN non-nil means warn if there\nexists an auto-save file more recent than the visited file.\nNOAUTO means don't mess with auto-save mode.\nFourth arg AFTER-FIND-FILE-FROM-REVERT-BUFFER is ignored\n(see `revert-buffer-in-progress-p' for similar functionality).\nFifth arg NOMODES non-nil means don't alter the file's modes.\nFinishes by calling the functions in `find-file-hook'\nunless NOMODES is non-nil." #<bytecode 0x1fd39502b749>) doom--optimize-for-large-files-a) doom-first-file-hook-h)(nil t)
  apply(#f(advice-wrapper :before #f(advice-wrapper :around #f(compiled-function (&optional error warn noauto after-find-file-from-revert-buffer nomodes) "Called after finding a file and by the default revert function.\nSets buffer mode, parses file-local and directory-local variables.\nOptional args ERROR, WARN, and NOAUTO: ERROR non-nil means there was an\nerror in reading the file.  WARN non-nil means warn if there\nexists an auto-save file more recent than the visited file.\nNOAUTO means don't mess with auto-save mode.\nFourth arg AFTER-FIND-FILE-FROM-REVERT-BUFFER is ignored\n(see `revert-buffer-in-progress-p' for similar functionality).\nFifth arg NOMODES non-nil means don't alter the file's modes.\nFinishes by calling the functions in `find-file-hook'\nunless NOMODES is non-nil." #<bytecode 0x1fd39502b749>) doom--optimize-for-large-files-a) doom-first-file-hook-h) (nil t))
  after-find-file(nil t)
  find-file-noselect-1(#<buffer bookmarks> "~/.emacs.d/.local/etc/bookmarks" nil nil "~/.emacs.d/.local/etc/bookmarks" (6553996 65024))
  find-file-noselect("/home/user/.emacs.d/.local/etc/bookmarks")
  bookmark-load("/home/user/.emacs.d/.local/etc/bookmarks" t t)
  bookmark-maybe-load-default-file()
  bookmark-all-names()
  counsel-bookmark()
  #<subr funcall-interactively>(counsel-bookmark)
  apply(#<subr funcall-interactively> counsel-bookmark)
  funcall-interactively(counsel-bookmark)
  #<subr call-interactively>(counsel-bookmark nil nil)
  apply(#<subr call-interactively> (counsel-bookmark nil nil))
  explain-pause--wrap-call-interactively(#<subr call-interactively> counsel-bookmark nil nil)
  apply(explain-pause--wrap-call-interactively #<subr call-interactively> (counsel-bookmark nil nil))
  call-interactively(counsel-bookmark nil nil)
  command-execute(counsel-bookmark)
```

**Steps to reproduce:**
1. open emacs
2. Space Ret to open bookmark or Space o A to open agenda
3. breaks here
4. Retry => now works

**System information:**
<details><pre>
SYSTEM  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/bash
        uname      Linux 5.8.10-arch1-1 #1 SMP PREEMPT Thu, 17 Sep 2020 18:01:06 +0000 x86_64
        path       (~/.bin /usr/local/bin /usr/bin /bin /usr/local/sbin /usr/lib/emacs/27.1/x86_64-pc-linux-gnu/)
EMACS   dir        ~/.emacs.d/
        version    27.1
        build      Aug 28, 2020
        buildopts  --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-wide-int --with-modules --with-cairo --with-harfbuzz 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
        features   XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP
        traits     (server-running envvar-file)
DOOM    dir        ~/.doom.d/
        version    2.0.9
        build      grafted, HEAD -> develop, origin/develop, origin/HEAD 1456108 2020-09-10 18:03:32 -0400
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline ophints (popup +defaults) vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold snippets :emacs dired electric undo vc :checkers syntax :tools (eval +overlay) lookup magit pdf :lang elixir emacs-lisp erlang (haskell +dante) latex markdown org sh :config (default +bindings +smartparens))
        packages   ((pdf-tools))
        unpin      (n/a)
        elpa       (n/a)
```
</details>
</pre></details>

**Comment by ThePrivacyGuide** [comment]
No I tried to delete the contents of recentf and it seems to be working. Not sure though how this happened and if it's going to happen again. I'll update this thread if it does.

**Comment by jerbaroo** [comment]
Also having trouble with this right now.

**Comment by hlissner** [comment]
This means recentf wrote a file with a syntax error in it. Perhaps one of the entries has a double quote in it? Hard to say without a look at the cache file (at `~/.emacs.d/.local/cache/recentf`).

@jerbaroo Can you post yours?

**Comment by ThePrivacyGuide** [comment]
Thanks @hlissner for your reply:) It never happened again for me, but how I solved the problem was to delete the contents of recentf. Now the contents of recentf looks normal again with just file paths and stuff, but when I deleted it when it wasn't working, it was full of gibberish. Sadly I don't have it anymore, but it had the same character (not a letter, some other character) repeated like 200 times.

**Comment by jerbaroo** [comment]
@hlissner Here you go https://gist.github.com/jerbaroo/5b060623ce9630840cc72e3ce465ea6e

The error extracted from the *Messages* buffer is:

```
condition-case: Error in a Doom startup hook: recentf-mode, (void-variable mail\.com/docs/jobs/cv/)
```

This makes sense when line 137 in the gist is examined.

**Comment by jerbaroo** [comment]
Thanks Henrik, I deleted lines after 137, so my problem is fixed. Though I would not consider this issue closed.
