### ISSUE TITLE
Inconsistent capitalization of "x" in markdown checkboxes

### ISSUE THREAD

**Issue by MithicSpirit** [hlissner/doom-emacs#3997]
**What did you expect to happen?**
The markdown and format modules should be consistent about using lowercase (preferred) or capital `x`s in checkboxes.

**What actually happened?**
The markdown module allows you to "push" the buttons in checkboxes to toggle them, which will swap between `[ ]` and `[X]`, but the format module converts checkboxes to `[x]`, making the capitalization of the `x` inconsistent.

**Additional details:**
`.doom.d` folder: https://github.com/MithicSpirit/dotfiles/tree/60c2dd95397379483c0c5ec9d6005ba232eb0d73/.doom.d

**Steps to reproduce:**
(0. Enable markdown and format +onsave)
1. Create/open a markdown file
2. Make a checkbox (`[ ]`)
3. Click on it, it should become `[X]`
4. Save the file so that the formatter activates, it should change to `[x]`

**System information:**
<details><pre>
((system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/usr/bin/zsh")
  (uname . "Linux 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64")
  (path "~/.nvm/versions/node/v12.18.2/bin" "~/.local/bin" "~/bin" "/usr/local/bin" "~/.local/bin" "/usr/local/sbin" "/usr/local/bin" "/usr/sbin" "/usr/bin" "/sbin" "/bin" "/usr/games" "/usr/local/games" "/snap/bin" "/usr/lib/emacs/26.3/x86_64-linux-gnu"))
 (emacs
  (dir . "~/.emacs.d/")
  (version . "26.3")
  (build . "Mar 26, 2020")
  (buildopts . "--build x86_64-linux-gnu --prefix=/usr --sharedstatedir=/var/lib --libexecdir=/usr/lib --localstatedir=/var/lib --infodir=/usr/share/info --mandir=/usr/share/man --enable-libsystemd --with-pop=yes --enable-locallisppath=/etc/emacs:/usr/local/share/emacs/26.3/site-lisp:/usr/local/share/emacs/site-lisp:/usr/share/emacs/26.3/site-lisp:/usr/share/emacs/site-lisp --with-sound=alsa --without-gconf --with-mailutils --build x86_64-linux-gnu --prefix=/usr --sharedstatedir=/var/lib --libexecdir=/usr/lib --localstatedir=/var/lib --infodir=/usr/share/info --mandir=/usr/share/man --enable-libsystemd --with-pop=yes --enable-locallisppath=/etc/emacs:/usr/local/share/emacs/26.3/site-lisp:/usr/local/share/emacs/site-lisp:/usr/share/emacs/26.3/site-lisp:/usr/share/emacs/site-lisp --with-sound=alsa --without-gconf --with-mailutils --with-x=yes --with-x-toolkit=gtk3 --with-toolkit-scroll-bars 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/emacs-mEZBk7/emacs-26.3+1=. -fstack-protector-strong -Wformat -Werror=format-security -Wall' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro'")
  (features . "XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS LIBSYSTEMD LCMS2")
  (traits batch envvar-file))
 (doom
  (dir . "~/.doom.d/")
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD 1456108d5 2020-09-10 18:03:32 -0400")
  (elc-files . 172)
  (modules :completion company ivy :ui doom doom-dashboard doom-quit hl-todo indent-guides (ligatures +fira) minimap modeline ophints (popup +defaults) treemacs vc-gutter vi-tilde-fringe workspaces zen :editor (evil +everywhere) file-templates fold (format +onsave) multiple-cursors snippets word-wrap :emacs dired electric undo vc :term term :checkers syntax spell grammar :tools debugger ein (eval +overlay) lookup magit pdf rgb :lang cc emacs-lisp json javascript latex markdown org purescript python sh yaml :email (mu4e +gmail) :app calendar irc :config (default +bindings +smartparens))
  (packages "n/a")
  (unpin "n/a")
  (elpa "rtags")))
</pre></details>

**Comment by MithicSpirit** [comment]
This can be fixed with by simply deleting the following line (or setting it to `nil`): https://github.com/hlissner/doom-emacs/blob/1456108d5bef89195b2b63f962e0ae9d24f4c652/modules/lang/markdown/config.el#L26 (That will change the markdown module to use lowercase `x`s by default.)
While it does state that it is done for compatibility with org-mode, I find compatibility with the formatter more important than with an entirely different markup language (also lowercases `x`s look nicer in checkboxes IMO).

**Comment by hlissner** [comment]
Sorry for the late response; I was on break. 

As of 2f91183 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
