### ISSUE TITLE
How to edit a word / symbol in multiple files in a project, at the same time ?

### ISSUE THREAD

**Issue by MrMic** [hlissner/doom-emacs#3998]
I would like to refactor like in Spacemacs, but do not find any doc
about this.

Thanks for the help.
Rgds,

**Comment by ymarco** [comment]
Use something like `SPC s p`, `SPC *` or `SPC s b` to start a search. `C-c C-e` to open a wgrep buffer with the results. Make your modifications. `C-c C-c` (or `ZZ`) to commit your changes.

**Comment by MrMic** [comment]
HI,

Indeed, that what I was looking for.
Thank you very much.

Rgds,

**Comment by MrMic** [comment]
SOLVED
