### ISSUE TITLE
[BUG]: Pressing enter in a code buffer results in wrong-type-argument: frame-live-p after killing session

### ISSUE THREAD

**Issue by eccentric-j** [hlissner/doom-emacs#4000]
**What did you expect to happen?**
When pressing return\enter in an org-buffer I expect it to add a new line.

**What actually happened?**
When enter\return is pressed, I see an error flash in the mini buffer:

**Additional details:**
- Config: https://github.com/eccentric-j/dotfiles/blob/a3ece7e9d3eaaa5a29910d8b8351148244ec2f34/client/doom.d/config.el
- If I disable company mode either for a buffer or globally, the errors don't come up and enter behaves normally but I lose autocomplete (which is expected when turning it off)

<details><pre>
Debugger entered--Lisp error: (wrong-type-argument frame-live-p #<dead frame  0x7f7f2d1f7a30>)
  make-frame-invisible(#<dead frame  0x7f7f2d1f7a30>)
  company-box-hide()
  company-box-frontend(hide)
  company-call-frontends(hide)
  company-cancel(abort)
  company-abort()
  company-select-mouse((mouse-1 (#<window 168 on 20200930215240-org_mode_index.org> 73 (914 . 548) 625862194 nil 73 (114 . 3) nil (874 . 500) (8 . 16))))
  company-complete-mouse((mouse-1 (#<window 168 on 20200930215240-org_mode_index.org> 73 (914 . 548) 625862194 nil 73 (114 . 3) nil (874 . 500) (8 . 16))))
  funcall-interactively(company-complete-mouse (mouse-1 (#<window 168 on 20200930215240-org_mode_index.org> 73 (914 . 548) 625862194 nil 73 (114 . 3) nil (874 . 500) (8 . 16))))
  call-interactively(company-complete-mouse nil nil)
  command-execute(company-complete-mouse)
</pre></details>

**Steps to reproduce:**
1. Enable childframe in doom company module
2. Restart doom
3. Open a file, then delete the session `SPC TAB x`
4. Open another file, I'm working with an org file but it's happened to me with JS, Python, and Clojure files as well.
5. Press enter or try editing a file like normal. 

**System information:**

<details>
```
SYSTEM  type       darwin
        config     x86_64-apple-darwin18.7.0
        shell      /usr/local/bin/fish
        uname      Darwin 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 18 20:50:10 PDT 2020; root:xnu-4903.278.43~1/RELEASE_X86_64 x86_64
        path       (/usr/local/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /Library/TeX/texbin /usr/local/MacGPG2/bin /usr/local/share/dotnet ~/.dotnet/tools /usr/local/Cellar/emacs-mac/HEAD-493abe4/libexec/emacs/27.1/x86_64-apple-darwin18.7.0)
EMACS   dir        ~/.emacs.d/
        version    27.1
        build      Aug 20, 2020
        buildopts  --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-mac/HEAD-493abe4/share/info/emacs --prefix=/usr/local/Cellar/emacs-mac/HEAD-493abe4 --with-mac --enable-mac-app=/usr/local/Cellar/emacs-mac/HEAD-493abe4 --with-gnutls --with-modules
        features   NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS JSON PDUMPER GMP
        traits     (server-running)
DOOM    dir        ~/dotfiles/client/doom.d/
        version    2.0.9
        build      HEAD -> develop, origin/develop, origin/HEAD 1456108d 2020-09-10 18:03:32 -0400
        elc-files  0
        modules    (:os macos tty :completion (company +childframe) (ivy +childframe) :ui doom doom-dashboard doom-quit fill-column hl-todo hydra indent-guides modeline ophints (popup +defaults) tabs treemacs vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold lispy multiple-cursors snippets :emacs dired electric undo vc :term vterm :checkers (syntax +childframe) :tools direnv docker editorconfig (eval +overlay) gist lookup lsp magit rgb tmux :lang clojure emacs-lisp (&user fennel) json (javascript +lsp) markdown (org +roam) (python +lsp) racket sh (web +lsp) yaml :email (wanderlust +gmail) :config (default +bindings +smartparens))
        packages   ((anakondo) (evil-lisp-state) (fish-mode) (inf-clojure) (sql-indent) (ox-gfm) (tmux-pane) (org-roam-server))
        unpin      (n/a)
        elpa       (n/a)
```
</details>

**Comment by eccentric-j** [comment]
## My hypothesis:

We have what's called an **"eager reaper"**, if it's not called that, we definitely should. Even if you open one buffer and kill the session, many windows, buffers, and a couple of other things get reaped according to the summary so likely some of those is likely used by company to render the child frame.

**Comment by hlissner** [comment]
Your hypothesis is right. Also, company-box does not make sure its two childframes (one for the completions and one for documentation) are alive before trying to use them. I consider this an upstream issue, and should be reported upstream.

In any case, as of 15d9761 this issue should be (temporarily) resolved. I will leave this open until it is resolved upstream.

**Comment by eccentric-j** [comment]
Confirming the update works. Thanks for the fix!
