### ISSUE TITLE
How do I make tabnine working?

### ISSUE THREAD

**Issue by MrMic** [hlissner/doom-emacs#4005]
Hi,

I have install tabnine and the binary that come along.
I also use lsp.
But I cannot make it works with this config in, config.el:

(after! company
  (setq company-idle-delay 0.3
        company-minimum-prefix-length 3
        company-dabbrev-code-everywhere t
        company-dabbrev-code-other-buffers 'all
        company-quickhelp-delay 0.4))

(after! company
  (setq company-backends '(company-tabnine company-capf company-yasnippet)))
  ;; (use-package company-tabnine :ensure t)
  ;; (setq company-begin-backend '(company-tabnine)))

;; (after! company
  ;; (add-to-list 'company-backends 'company-tabnine))

I have read a lot on the web and tryed many options, as you can see.
Nothing work, but it does with vim and VS Code, almost out of the box!

Can someone give me the correct configuration?
I would like to have tabnine in first place in my suggestions.

Thanks.
Rgds,

Michaël C.

**Comment by qhuyduong** [comment]
I used to make it work using this. You can have a try. 
https://github.com/qhuyduong/dotfiles/commit/3b2a0a9ac33eded3c373d948f56af05e692584c2

**Comment by MrMic** [comment]
Thank you! I will.
