### ISSUE TITLE
[BUG] Cannot save large C file

### ISSUE THREAD

**Issue by zwass** [hlissner/doom-emacs#4006]
**What did you expect to happen?**
1. Open sqlite3.c amalgamation file (8.1MB file)
2. Make any edit
3. Save (complete successfully)

**What actually happened?**
Save has not yet completed in ~5 minutes

**Additional details:**

Save works fine if mode switched to `fundamental-mode` beforehand.

**Steps to reproduce:**
1. Open [sqlite3.c amalgamation file](https://raw.githubusercontent.com/android/platform_external_sqlite/master/dist/sqlite3.c) (8.1MB file)
2. Make any edit
3. Save (C-x C-s)

**System information:**
<details><pre>
((system
  (type . darwin)
  (config . "x86_64-apple-darwin18.5.0")
  (shell . "/usr/local/bin/zsh")
  (uname . "Darwin 18.7.0 Darwin Kernel Version 18.7.0: Mon Aug 31 20:53:32 PDT 2020; root:xnu-4903.278.44~1/RELEASE_X86_64 x86_64")
  (path "~/.ebcli-virtual-env/executables" "~/.rbenv/shims" "/usr/local/bin" "/usr/bin" "/bin" "/usr/sbin" "/sbin" "~/dev/go/bin" "~/Library/Android/sdk/emulator" "~/Library/Android/sdk/tools" "~/Library/Android/sdk/tools/bin" "~/Library/Android/sdk/platform-tools" "/usr/local/Cellar/emacs-plus/26.3/libexec/emacs/26.3/x86_64-apple-darwin18.5.0"))
 (emacs
  (dir . "~/.emacs.d/")
  (version . "26.3")
  (build . "Aug 30, 2019")
  (buildopts . "--disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus/26.3/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus/26.3 --with-xml2 --without-dbus --with-gnutls --with-imagemagick --with-modules --with-rsvg --with-ns --disable-ns-self-contained")
  (features . "JPEG RSVG IMAGEMAGICK GLIB NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2")
  (traits batch server-running envvar-file))
 (doom
  (dir . "~/.doom.d/")
  (version . "2.0.9")
  (build . "HEAD -> develop 1456108d5 2020-09-10 18:03:32 -0400")
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor file-templates fold (format +onsave) multiple-cursors rotate-text snippets word-wrap :emacs dired electric ibuffer vc :term eshell :checkers syntax spell grammar :tools docker editorconfig (eval +overlay) (lookup +docsets) :os macos :tools magit make rgb :lang data emacs-lisp go javascript markdown (org +dragndrop +hugo +present) python sh web :config (default +bindings))
  (packages (ace-jump-mode) (telephone-line) (doom-modeline))
  (unpin "n/a")
  (elpa "n/a")))

</pre></details>

**Comment by peterhoeg** [comment]
Confirmed.

**Comment by hlissner** [comment]
It appears you have `:editor (format +onsave)` enabled. Does the issue go away if you disable it?

**Comment by peterhoeg** [comment]
No difference for me without (I also had `(format +onsave)`). OP?

**Comment by hlissner** [comment]
@peterhoeg Could you try profiling this? `SPC h T` (`M-x doom/toggle-profiler`) to start the profiler, save the large c file, after some time mash `C-g` to break out of it, then `SPC h T` again to produce a report.

**Comment by zwass** [comment]
I commented out `(format +onsave)` in my `init.el` file, restarted emacs, and tried again. It still hangs. While it hangs I see `clang-format` using 100% of a CPU.

Is there something else I need to do to disable that?

**Comment by hlissner** [comment]
> I commented out (format +onsave) in my init.el file, restarted emacs, and tried again.

Did you remember to run `doom sync` before restarting Emacs?

> While it hangs I see clang-format using 100% of a CPU.

This sounds like `:editor (format +onsave)` was not correctly disabled (or `doom sync` was forgotten).

**Comment by innerout** [comment]
Maybe [vlf](https://github.com/m00natic/vlfi/tree/cc02f2533782d6b9b628cec7e2dcf25b2d05a27c) can solve the issue since it can save chunks when working with big files.
