### ISSUE TITLE
Buggy code completion for C

### ISSUE THREAD

**Issue by variemai** [hlissner/doom-emacs#4008]
Hello, I am having a terrible issue with code completion.
 As you can see in this picture only **host** variable appears in the completion menu. I was expecting both **host** and **host_ptr** variables to be shown in completion menu.
![emacs_debug](https://user-images.githubusercontent.com/9337642/94882771-8d196780-0471-11eb-8706-d93b1f684263.png)

In the next picture you see that in the completion menu the variable is of a wrong type:
![emacs_debug2](https://user-images.githubusercontent.com/9337642/94883178-a242c600-0472-11eb-8eb7-ad457d104010.png)
It should have type **slurm_step_layout_t*** instead of **int*** as it is shown.

Thank you for your time and for this excellent distro for Emacs, I hope to find a fix or a workaround.
**System information:**
<details><pre>((system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/bin/zsh")
  (uname . "Linux 5.8.11-gentoo #1 SMP Wed Sep 30 17:51:10 EEST 2020 x86_64")
  (path "~/.local/bin" "~/bin" "/usr/local/bin" "/usr/lib/ccache/bin" "/usr/local/sbin" "/usr/local/bin" "/usr/sbin" "/usr/bin" "/sbin" "/bin" "/opt/bin" "/usr/lib/llvm/10/bin" "~/SimGrid/bin" "~/scotch/bin" "~/slurm/bin" "~/slurm/sbin" "/usr/libexec/emacs/27.1/x86_64-pc-linux-gnu"))
 (emacs
  (dir . "~/.emacs.d/")
  (version . "27.1")
  (build . "Sep 21, 2020")
  (buildopts . "--prefix=/usr --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu --mandir=/usr/share/man --infodir=/usr/share/info --datadir=/usr/share --sysconfdir=/etc --localstatedir=/var/lib --disable-silent-rules --docdir=/usr/share/doc/emacs-27.1-r1 --htmldir=/usr/share/doc/emacs-27.1-r1/html --libdir=/usr/lib64 --program-suffix=-emacs-27 --includedir=/usr/include/emacs-27 --infodir=/usr/share/info/emacs-27 --localstatedir=/var --enable-locallisppath=/etc/emacs:/usr/share/emacs/site-lisp --without-compress-install --without-hesiod --without-pop --with-dumping=pdumper --with-file-notification=inotify --enable-acl --with-dbus --without-modules --without-gameuser --with-libgmp --with-gpm --with-json --without-kerberos --without-kerberos5 --with-lcms2 --with-xml2 --without-mailutils --without-selinux --with-gnutls --with-libsystemd --with-threads --without-wide-int --with-zlib --with-sound=alsa --with-x --without-ns --without-gconf --without-gsettings --without-toolkit-scroll-bars --with-gif --with-jpeg --with-png --with-rsvg --with-tiff --with-xpm --without-imagemagick --with-xft --with-cairo --without-harfbuzz --without-libotf --without-m17n-flt --with-x-toolkit=gtk3 --without-xwidgets 'CFLAGS=-march=native -pipe -pipe -fno-stack-protector -O2' CPPFLAGS= 'LDFLAGS=-march=native -pipe -pipe -fno-stack-protector -Wl,--hash-style=gnu -O2'")
  (features . "XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE ZLIB GTK3 X11 XDBE XIM THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP")
  (traits batch server-running envvar-file))
 (doom
  (dir . "~/.doom.d/")
  (version . "2.0.9")
  (build . "grafted, HEAD -> develop, origin/develop, origin/HEAD 1456108d 2020-09-10 18:03:32 -0400")
  (elc-files . 0)
  (modules :completion (company + auto) helm ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash neotree ophints (popup +defaults) vc-gutter vi-tilde-fringe window-select :editor (evil +everywhere) file-templates fold snippets :emacs dired electric undo vc :term eshell (&nopath gtags) :checkers spell :tools (eval +overlay) lookup magit make :lang (&nopath assembly) cc data emacs-lisp latex markdown org python sh :email mu4e :config (default +bindings +smartparens))
  (packages (mu4e-alert) (evil-mu4e) (mu4e-overview) (beacon) (rtags) (pinentry) (org-bullets))
  (unpin "n/a")
  (elpa "n/a")))
</pre></details>

**Comment by variemai** [comment]
I have disabled irony mode and company-irony and used rtags for code completion. But it seems that company does not prefer company-rtags as a backend. I have to manualy use company-rtags for for code completion. I cannot find a way to make company-completion use company-rtags.

**Comment by hlissner** [comment]
I'd recommend you use ccls (or clangd) instead, by [activating LSP support](https://github.com/hlissner/doom-emacs/blob/develop/docs/faq.org#how-do-i-enable-lsp-support-for-insert-language-here) for `:lang cc` and installing one or the other server. Its completion capabilities are vastly superior to irony's (and rtags).

As this is more an issue with (or misconfiguration of) irony I don't consider this a bug.

**Comment by variemai** [comment]
> I'd recommend you use ccls (or clangd) instead, by [activating LSP support](https://github.com/hlissner/doom-emacs/blob/develop/docs/faq.org#how-do-i-enable-lsp-support-for-insert-language-here) for `:lang cc` and installing one or the other server. Its completion capabilities are vastly superior to irony's (and rtags).
> 
> As this is more an issue with (or misconfiguration of) irony I don't consider this a bug.

I switched to rtags completion and works fine. Indeed, its an issue with irony server. You can close this thread, thank you for your response

**Comment by peterhoeg** [comment]
@variemai as you opened the issue, you should have an option to close the issue as well.
