### ISSUE TITLE
Visual bugs with non-childframe company completion menus

### ISSUE THREAD

**Issue by ludwj61** [hlissner/doom-emacs#4013]
**What did you expect to happen?**
Completion menu to show up with causing visual bugs

**What actually happened?**
When using any theme (except default emacs themes) there is a visual bug where the completion menu causes some background weird color to appear around text and to the end of the buffer.

This does not occur when using company with my own/non doom config.

**Additional details:**
I posted about this issue at the company repo first, the maintainer seems to think it is a doom issue (https://github.com/company-mode/company-mode/issues/1013)
![image](https://user-images.githubusercontent.com/42984254/94981162-e0d19280-04fd-11eb-8633-4d405c505d35.png)
![image](https://user-images.githubusercontent.com/42984254/94981168-eb8c2780-04fd-11eb-929a-6746a9582cd4.png)

**Steps to reproduce:**
1. Enable company completion
2. Trigger completion anywhere, preferably a place with a large amount of completion as the bug is most apparent in those cases.

**System information:**
This occurs on all emacs versions I've tried (27.1, native comp, pgtk)
<details><pre>
SYSTEM  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/bash
        uname      Linux 5.8.13-arch1-1 #1 SMP PREEMPT Thu, 01 Oct 2020 20:40:35 +0000 x86_64
        path       (~/.opam/default/bin ~/.emacs.d/bin /usr/local/bin /usr/bin /bin /usr/local/sbin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /usr/lib/emacs/28.0.50/x86_64-pc-linux-gnu/)
EMACS   dir        ~/.emacs.d/
        version    28.0.50
        build      Oct 02, 2020
        buildopts  --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --mandir=/usr/share/man --with-gameuser=:games --with-sound=alsa --with-modules --without-gconf --without-gsettings --with-nativecomp --with-pgtk --with-x-toolkit=gtk3 --without-xaw3d --without-m17n-flt --with-cairo --with-xwidgets --without-compress-install 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -g -fuse-ld=gold' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
        features   JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 PGTK XIM MODULES NATIVE_COMP THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER LCMS2
        traits     (server-running envvar-file)
DOOM    dir        ~/.doom.d/
        version    2.0.9
        build      grafted, HEAD -> develop, origin/develop, origin/HEAD 1456108 2020-09-10 18:03:32 -0400
        elc-files  0
        modules    (:completion (company +childframe) ivy :ui doom doom-dashboard doom-quit hl-todo (modeline +light) ophints (popup +defaults) treemacs vc-gutter workspaces :editor (evil +everywhere) file-templates fold (format +onsave) snippets :emacs dired electric undo vc :term vterm :checkers (syntax +childframe) :tools (debugger +lsp) (eval +overlay) lookup lsp magit pdf :lang emacs-lisp (java +lsp) latex markdown ocaml (org +dragndrop) (python +lsp +pyright) (rust +lsp) sh :config (default +bindings +smartparens))
        packages   ((yasnippet-snippets))
        unpin      (doom-themes company-box)
        elpa       (n/a)

</pre></details>

**Comment by hlissner** [comment]
This is an upstream issue with company, I mention it [in solaire-mode's issue tracker](https://github.com/hlissner/emacs-solaire-mode/issues/37#issuecomment-685246002) and it has been reported in https://github.com/company-mode/company-mode/issues/1019.

I'll leave this issue open until it is resolved upstream.

**Comment by hlissner** [comment]
The PR was merged. As of c5605e9 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by ludwj61** [comment]
Seems to be fixed! Thanks!
