### ISSUE TITLE
Couldn't find the `rg' binary; this a hard dependecy for Doom, file searches may not work at all

### ISSUE THREAD

**Issue by QuantDimension** [hlissner/doom-emacs#4021]
**What did you expect to happen?**
Ran "doom doctor" and get no errors

**What actually happened?**
Ran "doom doctor" and this error came up

**Additional details:**

```
> Checking Doom core for irregularities...
    x Couldn't find the `rg' binary; this a hard dependecy for Doom, file searches may not work at all
```

**Steps to reproduce:**
1. doom doctor

**System information:**
<details><pre>
((system
  (type . darwin)
  (config . "x86_64-apple-darwin19.5.0")
  (shell . "/bin/zsh")
  (uname . "Darwin 19.6.0 Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64")
  (path "~/.emacs.d/bin" "/usr/local/opt/curl/bin" "/usr/local/sbin" "/usr/local/Cellar/pyenv-virtualenv/1.1.5/shims" "~/.pyenv/shims" "/usr/local/bin" "/usr/bin" "/bin" "/usr/sbin" "/sbin" "/usr/local/Cellar/emacs-plus@27/27.1/libexec/emacs/27.1/x86_64-apple-darwin19.5.0"))
 (emacs
  (dir . "~/.emacs.d/")
  (version . "27.1")
  (build . "Aug 27, 2020")
  (buildopts . "--disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus@27/27.1/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus@27/27.1 --with-xml2 --with-gnutls --without-dbus --with-imagemagick --with-modules --with-rsvg --with-ns --disable-ns-self-contained")
  (features . "RSVG IMAGEMAGICK GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS JSON PDUMPER LCMS2 GMP")
  (traits batch envvar-file))
 (doom
  (dir . "~/.doom.d/")
  (version . "2.0.9")
  (build . "HEAD -> develop 0769b47cc 2020-09-19 14:43:53 -0400")
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard doom-quit fill-column hl-todo indent-guides minimap modeline neotree ophints (popup +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold snippets :emacs dired electric ibuffer undo vc :term vterm :checkers syntax :tools docker ein (eval +overlay) lookup lsp magit make pdf :os macos tty :lang (cc +irony) data emacs-lisp json javascript markdown org php (python +lsp +pyenv +ipython) rest sh yaml :config (default +bindings +smartparens))
  (packages "n/a")
  (unpin "n/a")
  (elpa "n/a")))
</pre></details>

**Comment by hlissner** [comment]
So... is ripgrep (rg) installed? See [Doom's dependencies](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#install).
