### ISSUE TITLE
Keybind for preview pane in LaTeX mode

### ISSUE THREAD

**Issue by MithicSpirit** [hlissner/doom-emacs#4022]
**Describe the feature**
There should be an easier way to open `latex-preview-pane-mode` when in LaTeX mode than using `M-x` then searching for it.

**System information**
<details><pre>
((system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/usr/bin/zsh")
  (uname . "Linux 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64")
  (path "~/.nvm/versions/node/v12.18.2/bin" "~/.cargo/bin" "~/.local/bin" "~/bin" "/usr/local/bin" "~/.local/bin" "/usr/local/sbin" "/usr/local/bin" "/usr/sbin" "/usr/bin" "/sbin" "/bin" "/usr/games" "/usr/local/games" "/snap/bin" "/usr/lib/emacs/27.1/x86_64-linux-gnu"))
 (emacs
  (dir . "~/.emacs.d/")
  (version . "27.1")
  (build . "Sep 19, 2020")
  (buildopts . "--build=x86_64-linux-gnu --prefix=/usr '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' --sysconfdir=/etc --localstatedir=/var --disable-silent-rules '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' --disable-maintainer-mode --disable-dependency-tracking --prefix=/usr --sharedstatedir=/var/lib --libexecdir=/usr/lib --localstatedir=/var/lib --infodir=/usr/share/info --mandir=/usr/share/man --enable-locallisppath=/etc/emacs:/usr/local/share/emacs/27.1/site-lisp:/usr/local/share/emacs/site-lisp:/usr/share/emacs/27.1/site-lisp:/usr/share/emacs/site-lisp --program-suffix=27 --with-modules --with-file-notification=inotify --with-mailutils --with-harfbuzz --with-json --with-x=yes --with-x-toolkit=gtk3 --with-lcms2 --with-cairo --with-xpm=yes --with-gif=yes --with-gnutls=yes --with-jpeg=yes --with-png=yes --with-tiff=yes --with-xwidgets 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/emacs27-bifpWT/emacs27-27.1~1.git86d8d76aa3=. -fstack-protector-strong -Wformat -Werror=format-security -no-pie' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro -no-pie'")
  (features . "XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER LCMS2 GMP")
  (traits batch server-running envvar-file))
 (doom
  (dir . "~/.doom.d/")
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD, master 0769b47cc 2020-09-19 14:43:53 -0400")
  (elc-files . 189)
  (modules :completion company (ivy +prescient +icons) :ui doom doom-dashboard doom-quit hl-todo indent-guides (ligatures +extra) minimap modeline nav-flash ophints (popup +defaults) treemacs unicode vc-gutter vi-tilde-fringe workspaces zen :editor (evil +everywhere) file-templates fold (format +onsave) multiple-cursors snippets word-wrap :emacs (dired +icons) electric undo vc :term eshell vterm :checkers syntax (spell +everywhere) grammar :tools debugger ein eval (lookup +dictionary +offline) lsp (magit +forge) pdf rgb :lang (cc +lsp) emacs-lisp (json +lsp) (javascript +lsp) (latex +latexmk +lsp +fold) (markdown +grip) (org +pretty) (python +lsp +poetry) (sh +lsp) (yaml +lsp) :email (mu4e +gmail) :app calendar irc :config (default +bindings +smartparens))
  (packages "n/a")
  (unpin "n/a")
  (elpa "n/a")))
</pre></details>

**Comment by tecosaur** [comment]
In my config I have
```elisp
  (map!
   :map LaTeX-mode-map
   :localleader
   :desc "View" "v" #'TeX-view)
```
Which works quite nicely as far as I can tell.
