### ISSUE TITLE
Symbol’s function definition is void: persp-mode-start-and-remove-from-make-frame-hook

### ISSUE THREAD

**Issue by RobinMarchart** [hlissner/doom-emacs#4025]
**What did you expect to happen?**
emacsclient -c fails with 
`*ERROR*: Symbol’s function definition is void: persp-mode-start-and-remove-from-make-frame-hook`

**What actually happened?**
frame opens without displaying error messages

**Additional details:**
this seems to be caused by [This recent change in persp-mode](https://github.com/Bad-ptr/persp-mode.el/commit/f826e515e4efcebf3691dc810dac6505963dd2ad#diff-ad587a8d68b99fcd1d26681ee77cccffL1272)

**Steps to reproduce:**
1. add ui:workspaces module
2. start emacs daemon
3. run emacsclient -c

**System information:**
<details><pre>
((system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/usr/bin/zsh")
  (uname . "Linux 5.8.13-zen1-2-zen #1 ZEN SMP PREEMPT Fri, 02 Oct 2020 15:14:58 +0000 x86_64")
  (path "~/.bin" "~/.emacs.d/bin" "~/.local/bin" "~/.cargo/bin" "~/.pyenv/shims" "~/.nix-profile/bin" "/nix/var/nix/profiles/default/bin" "/usr/local/sbin" "/usr/local/bin" "/usr/bin" "/usr/lib/jvm/default/bin" "/usr/bin/site_perl" "/usr/bin/vendor_perl" "/usr/bin/core_perl" "~/.pyenv/bin" "/usr/lib/emacs/27.1/x86_64-pc-linux-gnu"))
 (emacs
  (dir . "~/.emacs.d/")
  (version . "27.1")
  (build . "Aug 28, 2020")
  (buildopts . "--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-wide-int --with-modules --with-cairo --with-harfbuzz 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now")
  (features . "XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP")
  (traits batch server-running envvar-file))
 (doom
  (dir . "~/.doom.d/")
  (version . "2.0.9")
  (build . "HEAD -> develop 5b2b660ee 2020-10-04 23:25:53 -0400")
  (elc-files . 0)
  (modules :completion (company +childframe) (ivy +childframe +icons +prescient +fuzzy) :ui deft doom doom-dashboard doom-quit hl-todo hydra modeline nav-flash ophints (popup +defaults) tabs treemacs unicode vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold format lispy multiple-cursors parinfer snippets word-wrap :emacs (dired +icons) electric (ibuffer +icons) (undo +tree) vc :term vterm :checkers syntax (spell +hunspell +everywhere +flyspell) grammar :tools biblio debugger direnv (docker +lsp) editorconfig ein (eval +overlay) gist (lookup +docsets +dictionary +offline) (lsp +peek) (magit +forge) (pass +auth) pdf rgb taskrunner upload :lang (cc +lsp) common-lisp (csharp +lsp) data emacs-lisp (json +lsp) (java +meghanada) (javascript +lsp) (latex +latexmk +cdlatex +fold) (markdown +grip) nix (org +dragndrop +gnuplot +jupyter +pandoc +present) (python +lsp) rest (&nopath B) (rust +lsp) sh (web +lsp) (yaml +lsp) :app calendar :config (default +bindings +smartparens) :os tty)
  (packages (meson-mode) (org-fragtog) (evil-tutor) (ein) (elcord) (realgud-node-inspect) (lsp-jedi))
  (unpin "n/a")
  (elpa "n/a")))
</pre></details>

**Comment by sseneca** [comment]
I've been having this issue as well, can confirm the commit above fixed it

**Comment by AnurupDey** [comment]
Like @sseneca has pointed out, the fix by @RobinMarchart allows emacsclient to show up, but all other functionality of the `ui: workspace` module is not working, like creating, switching and loading workspaces.

However, everything continues to work just fine if a new instance of emacs is started.

**Comment by AnurupDey** [comment]
https://github.com/sornas/doom-emacs/commit/f6bfd59fb99e5007ded8f7325d1d294ae5d9b47d#commitcomment-42973414

Temporary fix is to roll back persp-mode.
