### ISSUE TITLE
+web/indent-or-yas-or-emmet-expand doen't work

### ISSUE THREAD

**Issue by otavioschwanck** [hlissner/doom-emacs#4027]
**What did you expect to happen?**
when press tab, expand the tag on web-mode

**What actually happened?**
add a tab to at the end of file

**Additional details:**
- https://github.com/otavioschwanck/doom_emacs_dotfiles
![emmet expand bug](https://user-images.githubusercontent.com/9551316/95081526-0c1bd380-06f0-11eb-8a14-f2cd7c36ed8f.gif)

**System information:**
<details><pre>
SYSTEM  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /usr/bin/zsh
        uname      Linux 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64
        path       (~/Projetos/grafeno-pagamentos/node_modules/.bin/ ~/.pyenv/versions/3.7.2/bin ~/.yarn/bin ~/.config/yarn/global/node_modules/.bin ~/.nvm/versions/node/v12.18.1/bin ~/.rbenv/plugins/ruby-build/bin ~/.rbenv/shims ~/.rbenv/bin ~/.local/bin /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /usr/games /usr/local/games /snap/bin /usr/lib/x86_64-linux-gnu/emacs/28.0.50/x86_64-linux-gnu/)
EMACS   dir        ~/.emacs.d/
        version    28.0.50
        build      set 24, 2020
        buildopts  --build=x86_64-linux-gnu --prefix=/usr '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' --sysconfdir=/etc --localstatedir=/var --disable-silent-rules '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' --disable-maintainer-mode --disable-dependency-tracking --prefix=/usr --sharedstatedir=/var/lib --program-suffix=-snapshot --with-modules=yes --with-x=yes --with-x-toolkit=gtk3 --with-xwidgets=yes 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/emacs-snapshot-UkrRyl/emacs-snapshot-101710=. -fstack-protector-strong -Wformat -Werror=format-security' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro'
        features   XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER LCMS2
        traits     (server-running envvar-file)
DOOM    dir        ~/.doom.d/
        version    2.0.9
        build      HEAD -> develop 1456108d 2020-09-10 18:03:32 -0400
        elc-files  0
        modules    (:completion company (ivy +childframe +fuzzy +prescient) :ui doom doom-dashboard doom-quit hl-todo modeline ophints (popup +defaults +all) vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold (format +onsave) multiple-cursors snippets :emacs dired electric undo vc :term shell :checkers syntax spell :tools docker (eval +overlay) lookup lsp magit :lang emacs-lisp javascript markdown org (ruby +rails +rbenv +lsp) sh web yaml :config (default +bindings +smartparens))
        packages   (n/a)
        unpin      (n/a)
        elpa       (n/a)

</pre></details>

**Comment by hlissner** [comment]
As of 0e7d5b5 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by rassie** [comment]
I'll test it at the next possibility. Thank you!
