### ISSUE TITLE
Larger window dividers remain after exiting writeroom-mode

### ISSUE THREAD

**Issue by pkazmier** [hlissner/doom-emacs#4028]
**What did you expect to happen?**
After I exit `writeroom-mode`, `SPC t z`, I expect the size of the window dividers to return to the size they were prior to entering `writeroom-mode`. Using `doom-rouge` as an example, I would expect this:

<img width="723" alt="image" src="https://user-images.githubusercontent.com/747855/95091756-76cb1000-06ec-11eb-8b7f-ac873485dd71.png">

**What actually happened?**
Instead, after I exit `writeroom-mode`, my window looks like this:

<img width="723" alt="image" src="https://user-images.githubusercontent.com/747855/95091881-9d894680-06ec-11eb-91a9-30e13b668305.png">

**Additional details:**
There are no error messages in the echo area.

**Steps to reproduce:**
1. Start emacs.
2. Select a theme with a visible window divider such as `doom-rouge`. The problem still occurs with `doom-one`, but it's just harder to spot with the eye.
3. From doom dashboard screen, enter `writeroom-mode` (`SPC t z`) and then exit `writeroom-mode` (`SPC t z`).

**System information:**
<details>

```
SYSTEM  type       darwin
        config     x86_64-apple-darwin19.6.0
        shell      /bin/zsh
        uname      Darwin 19.6.0 Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64
        path       (~/bin ~/go/bin ~/.emacs.d/bin ~/.dotfiles/bin /usr/local/bin ~/.cache/zsh4humans/bin ~/.cache/zsh4humans/junegunn/fzf/bin /usr/bin /bin /usr/sbin /sbin /Library/TeX/texbin /usr/local/go/bin /usr/local/Cellar/emacs-plus@27/27.0.91/libexec/emacs/27.0.91/x86_64-apple-darwin19.6.0/)
EMACS   dir        ~/.emacs.d/
        version    27.0.91
        build      Aug 08, 2020
        buildopts  --disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus@27/27.0.91/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus@27/27.0.91 --with-xml2 --with-gnutls --without-dbus --with-imagemagick --with-modules --with-rsvg --with-ns --disable-ns-self-contained
        features   RSVG IMAGEMAGICK GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS PDUMPER LCMS2 GMP
        traits     (server-running envvar-file)
DOOM    dir        ~/.doom.d/
        version    2.0.9
        build      HEAD -> develop 5b2b660e 2020-10-04 23:25:53 -0400
        elc-files  0
        modules    (:completion (company +childframe) ivy :ui doom doom-dashboard doom-quit hl-todo (ligatures +pragmata-pro) modeline nav-flash ophints (popup +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces zen :editor (evil +everywhere) file-templates fold (format +onsave) multiple-cursors snippets :emacs dired electric (ibuffer +icons) undo vc :term vterm :checkers syntax :tools (eval +overlay) lookup lsp magit :lang data emacs-lisp (go +lsp) markdown (org +dragndrop +pretty) (python +lsp) sh yaml :app calendar (rss +org) :config (default +bindings +smartparens))
        packages   ((org-super-agenda) (ox-twbs))
        unpin      (doom-themes)
        elpa       (n/a)
```
</details>

**Comment by hlissner** [comment]
As of c94ea8e this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by pkazmier** [comment]
Thanks and confirmed it works on my end.
