### ISSUE TITLE
doom/find-file-in-private-config runs into an error if doom-private-dir is a symlink

### ISSUE THREAD

**Issue by RBckmnn** [hlissner/doom-emacs#4029]
**What did you expect to happen?**
If `doom-private-dir` is a symlink to a directory, `doom/find-file-in-private-config` should prompt for a file in the target directory.

**What actually happened?**
`doom/find-file-in-private-config` runs into an error (see backtrace below).

**Additional details:**
The error appeared a few days ago, just after I upgraded to Emacs 27.1.

**Backtrace:**
<details><pre>
Debugger entered--Lisp error: (cl-no-applicable-method project-roots nil)
  signal(cl-no-applicable-method (project-roots nil))
  cl-no-applicable-method(#s(cl--generic :name project-roots :dispatches ((0 #s(cl--generic-generalizer :name cl--generic-head-generalizer :priority 80 :tagcode-function #f(compiled-function (name &rest _) #<bytecode 0x1fce2ae9a67d>) :specializers-function #f(compiled-function (tag &rest _) #<bytecode 0x1fce2ae9a66d>)) #s(cl--generic-generalizer :name cl--generic-t-generalizer :priority 0 :tagcode-function #f(compiled-function (name &rest _) #<bytecode 0x1fce2ae0dc67>) :specializers-function #f(compiled-function (tag &rest _) #<bytecode 0x1fce2ae0dc57>)))) :method-table (#s(cl--generic-method :specializers ((head vc)) :qualifiers nil :uses-cnm nil :function #f(compiled-function (project) #<bytecode 0x1578bcb9ed81>)) #s(cl--generic-method :specializers ((head transient)) :qualifiers nil :uses-cnm nil :function #f(compiled-function (project) #<bytecode 0x1578bc5feab1>))) :options nil) nil)
  apply(cl-no-applicable-method #s(cl--generic :name project-roots :dispatches ((0 #s(cl--generic-generalizer :name cl--generic-head-generalizer :priority 80 :tagcode-function #f(compiled-function (name &rest _) #<bytecode 0x1fce2ae9a67d>) :specializers-function #f(compiled-function (tag &rest _) #<bytecode 0x1fce2ae9a66d>)) #s(cl--generic-generalizer :name cl--generic-t-generalizer :priority 0 :tagcode-function #f(compiled-function (name &rest _) #<bytecode 0x1fce2ae0dc67>) :specializers-function #f(compiled-function (tag &rest _) #<bytecode 0x1fce2ae0dc57>)))) :method-table (#s(cl--generic-method :specializers ((head vc)) :qualifiers nil :uses-cnm nil :function #f(compiled-function (project) #<bytecode 0x1578bcb9ed81>)) #s(cl--generic-method :specializers ((head transient)) :qualifiers nil :uses-cnm nil :function #f(compiled-function (project) #<bytecode 0x1578bc5feab1>))) :options nil) nil)
  #f(compiled-function (&rest args) #<bytecode 0x1578bcd07cad>)(nil)
  apply(#f(compiled-function (&rest args) #<bytecode 0x1578bcd07cad>) nil nil)
  project-roots(nil)
  project--dir-ignores(nil "/home/gwydion/Workspace/dotfiles/.doom.d/")
  #f(compiled-function (dir) #<bytecode 0x1578be64c12d>)("/home/gwydion/Workspace/dotfiles/.doom.d/")
  mapcan(#f(compiled-function (dir) #<bytecode 0x1578be64c12d>) ("/home/gwydion/Workspace/dotfiles/.doom.d/"))
  cl-mapcan(#f(compiled-function (dir) #<bytecode 0x1578be64c12d>) ("/home/gwydion/Workspace/dotfiles/.doom.d/"))
  #f(compiled-function (project &optional dirs) #<bytecode 0x1578bc5feadd>)(nil ("/home/gwydion/Workspace/dotfiles/.doom.d/"))
  apply(#f(compiled-function (project &optional dirs) #<bytecode 0x1578bc5feadd>) nil ("/home/gwydion/Workspace/dotfiles/.doom.d/"))
  project-files(nil ("/home/gwydion/Workspace/dotfiles/.doom.d/"))
  project-find-file-in(nil ("/home/gwydion/Workspace/dotfiles/.doom.d/") nil)
  (cond ((and projectile-project-root (file-equal-p projectile-project-root default-directory)) (if (doom-project-p default-directory) nil (setq projectile-enable-caching nil)) (call-interactively (if (doom-module-p :completion 'ivy) #'counsel-projectile-find-file #'projectile-find-file))) ((fboundp 'counsel-file-jump) (call-interactively #'counsel-file-jump)) ((project-current) (project-find-file-in nil (list default-directory) nil)) ((fboundp 'helm-find-files) (call-interactively #'helm-find-files)) ((call-interactively #'find-file)))
  (let* ((default-directory (file-truename (expand-file-name dir))) (projectile-project-root (doom-project-root default-directory)) (projectile-enable-caching projectile-enable-caching)) (cond ((and projectile-project-root (file-equal-p projectile-project-root default-directory)) (if (doom-project-p default-directory) nil (setq projectile-enable-caching nil)) (call-interactively (if (doom-module-p :completion 'ivy) #'counsel-projectile-find-file #'projectile-find-file))) ((fboundp 'counsel-file-jump) (call-interactively #'counsel-file-jump)) ((project-current) (project-find-file-in nil (list default-directory) nil)) ((fboundp 'helm-find-files) (call-interactively #'helm-find-files)) ((call-interactively #'find-file))))
  doom-project-find-file("~/.doom.d/")
  doom/find-file-in-private-config()
  funcall-interactively(doom/find-file-in-private-config)
  call-interactively(doom/find-file-in-private-config nil nil)
  command-execute(doom/find-file-in-private-config)

</pre></details>

**Steps to reproduce:**
1. Make `doom-private-dir` a symlink to another directory (Maybe relevant: in my case, the target dir is also contained in a git repo)
2. Issue `SPC f p` to execute `doom/find-file-in-private-config`
3. Observe the above error

If I replace the symlink with an actual directory, the error does not occur.

**System information:**
<details>

```
SYSTEM  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/bash
        uname      Linux 5.4.66-gentoo #1 SMP Tue Sep 29 21:07:25 CEST 2020 x86_64
        path       (~/.emacs.d.doom.fork/bin/ /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /opt/bin /usr/lib/llvm/10/bin ~/.emacs.d/bin ~/.local/bin ~/bin /usr/libexec/emacs/27.1/x86_64-pc-linux-gnu/)
EMACS   dir        ~/.emacs.d.doom.fork/
        version    27.1
        build      Sep 29, 2020
        buildopts  --prefix=/usr --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu --mandir=/usr/share/man --infodir=/usr/share/info --datadir=/usr/share --sysconfdir=/etc --localstatedir=/var/lib --disable-silent-rules --docdir=/usr/share/doc/emacs-27.1-r1 --htmldir=/usr/share/doc/emacs-27.1-r1/html --libdir=/usr/lib64 --program-suffix=-emacs-27 --includedir=/usr/include/emacs-27 --infodir=/usr/share/info/emacs-27 --localstatedir=/var --enable-locallisppath=/etc/emacs:/usr/share/emacs/site-lisp --without-compress-install --without-hesiod --without-pop --with-dumping=pdumper --with-file-notification=inotify --enable-acl --with-dbus --with-modules --without-gameuser --with-libgmp --with-gpm --without-json --without-kerberos --without-kerberos5 --with-lcms2 --with-xml2 --without-mailutils --without-selinux --with-gnutls --without-libsystemd --with-threads --without-wide-int --with-zlib --with-sound=alsa --with-x --without-ns --without-gconf --without-gsettings --without-toolkit-scroll-bars --with-gif --with-jpeg --with-png --with-rsvg --with-tiff --with-xpm --without-imagemagick --with-xft --with-cairo --without-harfbuzz --without-libotf --without-m17n-flt --with-x-toolkit=gtk3 --with-xwidgets 'CFLAGS=-march=native -O2 -pipe' CPPFLAGS= 'LDFLAGS=-Wl,-O1 -Wl,--as-needed'
        features   XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE ZLIB GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS PDUMPER LCMS2 GMP
        traits     (server-running envvar-file)
DOOM    dir        ~/Workspace/dotfiles/.doom.d/
        version    2.0.9
        build      HEAD -> develop, upstream/develop f335d4294 2020-10-05 14:55:08 -0400
        elc-files  0
        modules    (:completion company helm :ui doom doom-dashboard hl-todo modeline nav-flash ophints (popup +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold (format +onsave) multiple-cursors snippets :emacs (dired +icons) electric undo vc :term vterm :checkers syntax (spell +flyspell +aspell) :tools direnv (eval +overlay) (lookup +docsets) lsp magit pdf :lang data emacs-lisp (javascript +lsp) (latex +cdlatex) markdown (org +roam +noter) (python +lsp) (sh +lsp) (web +lsp) :email mu4e :config literate (default +bindings +smartparens))
        packages   ((f) (org-drill) (org-super-agenda) (org-chef) (org-ref) (org-roam-bibtex))
        unpin      (n/a)
        elpa       (n/a)
```
</details>

P.S.: Thanks for your great work

**Comment by hlissner** [comment]
Cannot reproduce this. My `~/.config/doom` is a symlink as well, which presents no issue.

What's strange is that this error is coming from project.el, which Doom does not use (we use projectile). Perhaps you have some private configuration trying to substitute projectile for project.el?

**Comment by hlissner** [comment]
Give 1aa48ce a try. It should hopefully address this issue. Let me know if that isn't the case and I'll reopen it.

**Comment by RBckmnn** [comment]
AFAICT, there is nothing suspicious going on in my private config (with regards to project and projectile). I have only set `projectile-ignored-project-function` and `projectile-project-search-path`. Anyways, you change fixed the issue for me :-). 

Thanks a lot!
