### ISSUE TITLE
Deactivating doom-debug-mode enables explain-pause-mode

### ISSUE THREAD

**Issue by Janfel** [hlissner/doom-emacs#4033]
In [this line](https://github.com/hlissner/doom-emacs/blob/64922dd3011eca0c263d900c5f2100af761df8bf/core/autoload/debug.el#L53) `explain-pause-mode` gets enabled regardless of `doom-debug-mode` because an argument of `nil` enables a mode from Elisp. Please change `(explain-pause-mode enabled)` to something like `(explain-pause-mode (if enabled +1 -1))`.

**Comment by hlissner** [comment]
As of 3cb7458 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
