### ISSUE TITLE
Toggle "Fill Column Indicator" only works in one direction

### ISSUE THREAD

**Issue by panchoh** [hlissner/doom-emacs#4035]
**What did you expect to happen?**
Pressing `SPC t c` would toggle (both on and off) the fill column indicator.
Feature just merged, [PR#3982](https://github.com/hlissner/doom-emacs/pull/3982)

**What actually happened?**
On a text buffer, the column indicator is shown as a vertical bar (as expected).
`SPC t c` *has no effect*.  Note that `SPC t` shows the ivy menu offering `c -> Fill Column Indicator`) as an option.
Workaround: Typing `SPC : display-fill-column-indicator-mode` disables the fill column indicator. At this point, `SPC t c` enables the fill column indicator correctly, but typing `SPC t c` again has not the desired effect.

**Additional details:**
`:ui fill-column` enabled @ doom/init.el.
I've tried doing a `git clean -fxd; rm -rf .local` to get a clean slate, but that didn't help.

**Steps to reproduce:**
1. Create and save a text buffer with a line that exceeds 80 columns, like this:
```sh
emacs sample.txt
```
Add this content:
```txt
This is a text buffer with a line long enough to trigger the fill column character display.
It will be shown only after *saving* the buffer, though (`SPC f s`).
```
2. Save the buffer to disk, with `SPC f s`
3. Observe the fill column indicator being shown in the 80th column
4. Type `SPC t c` to try and disable the aforementioned column indicator.  Notice perplexed (or aghast, either-or) how nothing happens.

**System information:**
Running current `emacs 27.1` on Archlinux.
<details><pre>
((system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/usr/bin/fish")
  (uname . "Linux 5.8.13-arch1-1 #1 SMP PREEMPT Thu, 01 Oct 2020 20:40:35 +0000 x86_64")
  (path "~/.pyenv/bin" "~/.nix-profile/bin" "~/.nix-profile/bin" "/nix/var/nix/profiles/default/bin" "~/.local/bin" "~/go/bin" "/usr/local/bin" "/usr/bin" "/bin" "/usr/local/sbin" "/usr/lib/jvm/default/bin" "/usr/bin/site_perl" "/usr/bin/vendor_perl" "/usr/bin/core_perl" "~/.config/emacs/bin" "/usr/lib/emacs/27.1/x86_64-pc-linux-gnu"))
 (emacs
  (dir . "~/.config/emacs/")
  (version . "27.1")
  (build . "Aug 28, 2020")
  (buildopts . "--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-wide-int --with-modules --with-cairo --with-harfbuzz 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now")
  (features . "XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP")
  (traits batch))
 (doom
  (dir . "~/.config/doom/")
  (version . "2.0.9")
  (build . "HEAD -> develop 0feacd4ce 2020-10-06 00:20:17 -0400")
  (elc-files . 196)
  (modules :completion company (ivy +icons) :ui doom doom-dashboard fill-column hl-todo minimap modeline nav-flash ophints (popup +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces zen :editor (evil +everywhere) file-templates fold format snippets word-wrap :emacs dired electric ibuffer undo vc :term vterm :checkers syntax spell grammar :tools ansible docker editorconfig ein (eval +overlay) lookup (lsp +eglot) (magit +forge) make pdf terraform :lang cc data emacs-lisp (go +lsp) (haskell +lsp) json (javascript +lsp) latex (markdown +grip) nix (org +hugo +pandoc +pomodoro +present +dragndrop) (python +lsp +pyenv) raku rest rst rust scheme sh web yaml :config (default +bindings +smartparens))
  (packages (flycheck-popup-tip :disable t) (hide-lines) (ivy-avy))
  (unpin "n/a")
  (elpa "n/a")))
</pre></details>

**Comment by hlissner** [comment]
As of 729e8d8 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
