### ISSUE TITLE
Improve visual balance of the output when updating

### ISSUE THREAD

**Issue by rassie** [hlissner/doom-emacs#4036]
I would like to propose to move an empty line in `doom up`'s output. It currently looks like this:

![image](https://user-images.githubusercontent.com/23448/95166441-2fa55380-07ae-11eb-99e8-eaa814f2d883.png)

As you can see, the lines I've drawn mark logical separation points, i.e. where an update of a package begins and where it ends. However, the included empty lines create a totally different balance and confuse at the first glance, e.g. they suggest that `lsp-ivy` has been updated *with the following commits* (which actually belong to `haskell-mode`). If the empty line coming before `$package updated` would move to after `$package updated` and before `Updating $package`, the visual balance would be less confusing.

**Comment by hlissner** [comment]
As of c841270 the commit log is now displayed below the "updated" message, e.g.

![image](https://user-images.githubusercontent.com/510883/95244523-161cff80-07e0-11eb-8f13-51878d7ba24d.png)

I'll consider this resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
