### ISSUE TITLE
`ui: workspaces` is broken when using `emacsclient`

### ISSUE THREAD

**Issue by AnurupDey** [hlissner/doom-emacs#4037]
**What did you expect to happen?**
using `emacsclient`, the following things:
Pressing `SPC` `TAB` `TAB` should display the workspace names in the minibuffer.
Pressing `SPC o m` should open `mu4e`
Pressing `SPC TAB n` should create a new workspace
Pressing `SPC TAB`  etc... should actually do stuff

**What actually happened?**
None of the `SPC TAB` functions work when in `emacsclient`. 

Though using `emacs` (non daemon) works just fine.

**Steps to reproduce:**
1. enable `ui:workspaces`
2. start emacs daemon
3. connect via `emacsclient -c`
4. press `SPC TAB TAB` or anything related to `ui:workspace`

**System information:**
<details><pre>
SYSTEM  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/bash
        uname      Linux 5.8.11-1-MANJARO #1 SMP PREEMPT Wed Sep 23 14:35:40 UTC 2020 x86_64
        path       (~/.local/bin /usr/local/bin /usr/bin /bin /usr/local/sbin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /var/lib/snapd/snap/bin ~/tools/flutter/bin ~/.config/emacs/bin/ /usr/lib/emacs/27.1/x86_64-pc-linux-gnu/)
EMACS   dir        ~/.config/emacs/
        version    27.1
        build      Aug 28, 2020
        buildopts  --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-wide-int --with-modules --with-cairo --with-harfbuzz 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
        features   XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP
        traits     (daemon server-running envvar-file)
DOOM    dir        ~/.config/doom/
        version    2.0.9
        build      HEAD -> develop 29b12de8 2020-10-06 02:08:17 -0400
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo hydra indent-guides modeline ophints (popup +defaults) treemacs unicode vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold (format +onsave) multiple-cursors snippets :emacs dired electric undo vc :term vterm :checkers syntax :tools debugger (eval +overlay) lookup lsp (magit +forge) :lang (cc +lsp) (dart +lsp +flutter) emacs-lisp markdown (org +pretty +dragndrop) sh web (yaml +lsp) :email (mu4e +gmail) :config (default +bindings +smartparens))
        packages   ((dart-snippets :recipe (:host github :repo MYDavoodeh/dart-snippets :files (*.el (snippets snippets/*)))) (impatient-mode))
        unpin      (n/a)
        elpa       (n/a)
</pre></details>

**Comment by AnurupDey** [comment]
I suppose  #4025 is related.

**Comment by hlissner** [comment]
As of 8afba81 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by AnurupDey** [comment]
Confirmed that this fixes the issue. Thanks!
