### ISSUE TITLE
Upgrading causes git error

### ISSUE THREAD

**Issue by ElectricCoffee** [hlissner/doom-emacs#4038]
Running `doom upgrade` causes the following error under the 'updating packages' step:
```
In repository "persp-mode.el", HEAD (on branch "remove-byte-compile") is ahead of branch "master"
```
No amount of asking the tool to fast-forward resolves the issue

![Screenshot at 2020-10-06 09-17-42](https://user-images.githubusercontent.com/1515791/95170636-15bb3f00-07b5-11eb-8f43-93748f466cf7.png)

**Comment by ymarco** [comment]
Not sure what's the cause of this, but its solvable by
```sh
rm -rf .emacs.d/.local/straight/{repos,build}/persp-mode.el
```

**Comment by jperras** [comment]
The solution proposed by @ymarco fixed it for me!
