### ISSUE TITLE
Compose mail buffer in mu4e is not in org-msg-mode

### ISSUE THREAD

**Issue by pkazmier** [hlissner/doom-emacs#4043]
**What did you expect to happen?**
When composing an email from mu4e, I expect the compose buffer to be in OrgMsg mode like this:

<img width="839" alt="image" src="https://user-images.githubusercontent.com/747855/95228188-a2b9c480-07c4-11eb-9ad7-2525024846b2.png">

**What actually happened?**
Instead, when I compose an email from mu4e, my compose buffer looks like this:

<img width="839" alt="image" src="https://user-images.githubusercontent.com/747855/95228119-8fa6f480-07c4-11eb-9573-2cd7a99bcc53.png">

**Additional details:**
To workaround the issue, after the compose buffer opens without OrgMsg mode, I can do the following:

1. Kill the buffer.
2. Disable `org-msg-mode`.
3. Enable `org-msg-mode`.
4. Compose a new email and it will open in OrgMsg mode.

While testing other things, I also noticed that if I press `C-x m` (`compose-mail`) immediately after emacs starts up, that the compose buffer is not in the OrgMsg mode either. But, if I start emacs and wait for about 15 seconds, _then_ press `C-x m`, the buffer opens in OrgMsg mode.

**Steps to reproduce:**
1. Start emacs.
2. Press `SPC o m` to open mu4e.
3. Press `C` to compose a new message.

**System information:**
<details>

```
SYSTEM  type       darwin
        config     x86_64-apple-darwin19.5.0
        shell      /bin/zsh
        uname      Darwin 19.6.0 Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64
        path       (~/.emacs.d/bin/ ~/bin ~/go/bin ~/.emacs.d/bin ~/.dotfiles/bin /usr/local/bin ~/.cache/zsh4humans/bin ~/.cache/zsh4humans/junegunn/fzf/bin /usr/bin /bin /usr/sbin /sbin /Library/TeX/texbin /usr/local/go/bin /usr/local/Cellar/emacs-plus@27/27.1/libexec/emacs/27.1/x86_64-apple-darwin19.5.0/)
EMACS   dir        ~/.emacs.d/
        version    27.1
        build      Aug 27, 2020
        buildopts  --disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus@27/27.1/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus@27/27.1 --with-xml2 --with-gnutls --without-dbus --with-imagemagick --with-modules --with-rsvg --with-ns --disable-ns-self-contained
        features   RSVG IMAGEMAGICK GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS JSON PDUMPER LCMS2 GMP
        traits     (server-running envvar-file)
DOOM    dir        ~/.doom.d/
        version    2.0.9
        build      HEAD -> develop 29b12de8 2020-10-06 02:08:17 -0400
        elc-files  0
        modules    (:completion (company +childframe) ivy :ui doom doom-dashboard doom-quit hl-todo (ligatures +pragmata-pro) modeline nav-flash ophints (popup +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces zen :editor (evil +everywhere) file-templates fold (format +onsave) multiple-cursors snippets :emacs dired electric (ibuffer +icons) undo vc :term vterm :checkers syntax :tools (eval +overlay) lookup lsp magit :lang data emacs-lisp (go +lsp) markdown (org +dragndrop +pretty) (python +lsp) sh yaml :email mu4e :app calendar (rss +org) :config (default +bindings +smartparens))
        packages   ((org-super-agenda) (ox-twbs))
        unpin      (doom-themes)
        elpa       (n/a)
```
</details>

**Comment by hlissner** [comment]
As of dbe09f9 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by pkazmier** [comment]
Confirmed. Thanks for fixing.

**Comment by jperras** [comment]
I hate to re-open a discussion on a closed issue, but it seems as though this fix has now made it so that mu4e always opens in `org-msg-mode` for myself, and I don't use org-mode at all.

Is there something I can do to have it open in mu4e compose mode by default?

**Comment by pkazmier** [comment]
Looks like that feature is coming in #3971

**Comment by seanfarley** [comment]
I also came here wondering who broke my mail setup. Is `org-msg` supposed to be the default? I don't ever want to send html emails so can we have some setting that says, "no really, I only want text"?

**Comment by pkazmier** [comment]
I guess the question is whether or not the original author intended org-msg mode to be enabled by default. If it was supposed to be, then the fix is appropriate. If it was not supposed to be, then how was one supposed to enable this before?

Since I'm the only one that seemed the expect org-msg to be enabled by default, and many others are depending on the old behavior, it's probably best to undo this "fix". I'll just add the hook to `mu4e-compose-pre` in my private config.

**Comment by aghitza** [comment]
As pointed out by others here, org-msg strays so far from sane email behavior that it should not be forced as default on everyone, please.

**Comment by pkazmier** [comment]
@hlissner looks like we need to undo this change as it broke existing behavior for several folks.

**Comment by jperras** [comment]
I just realized that this may not be obvious for some, but in case you run into the aforementioned issue with `org-msg-mode` you can disable the hook with:

```elisp
(remove-hook! 'mu4e-compose-pre-hook #'org-msg-mode)
```

until/if it is changed in `master`.

**Comment by hlissner** [comment]
Please move this discussion to #3971, as it isn't related to OP's original issue.
