### ISSUE TITLE
After today upgrade, code complete work incorrectly!

### ISSUE THREAD

**Issue by chenyidao110** [hlissner/doom-emacs#4046]
**What did you expect to happen?**
...After today upgrade, there is something wrong in code complete while edit python/c/c++ source files.

**What actually happened?**
...
Upgrade doom-emacs as follow:
~/.emacs.d/bin/doom upgrade, then edit python/c/c++ with emacs,but code complete cannot work normally
![Snipaste_2020-10-07_13-34-35](https://user-images.githubusercontent.com/14362421/95292101-6c9f4200-08a3-11eb-9b89-567d90fc0f50.png)

**Additional details:**
message buffer: 
Company: An error occurred in auto-begin
Company: backend company-capf error "Symbol’s function definition is void: :interrupted" with args (candidates std)

<details><pre>
If an error message is involved include a backtrace of it.
![Snipaste_2020-10-07_13-34-35](https://user-images.githubusercontent.com/14362421/95291944-1cc07b00-08a3-11eb-93ef-38a10d6977b5.png)

How to acquire a backtrace:
https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#how-to-extract-a-backtrace-from-an-error
</pre></details>

**Steps to reproduce:**
1. Select these example steps,
2. Delete them,
3. And replace them with precise steps to reproduce your issue.
4. Fill in "system information" below.

**System information:**
<details>

```
SYSTEM  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /usr/bin/zsh
        uname      Linux 4.19.104-microsoft-standard #1 SMP Wed Feb 19 06:37:35 UTC 2020 x86_64
        path       (~/.local/bin /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /usr/games /usr/local/games /snap/bin
/usr/local/emacs271/libexec/emacs/27.1/x86_64-pc-linux-gnu)
EMACS   dir        ~/.emacs.d/
        version    27.1
        build      Oct 07, 2020
        buildopts  --prefix=/usr/local/emacs271
        features   XPM JPEG TIFF GIF PNG SOUND DBUS GSETTINGS GLIB NOTIFY INOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES
THREADS PDUMPER GMP
        traits     (envvar-file)
DOOM    dir        ~/.$USER.d/
        version    2.0.9
        build      HEAD -> develop d807a7513 2020-10-06 17:16:37 -0400
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline ophints (popup +defaults) vc-gutter vi-tilde-fringe workspaces :editor (evil
+everywhere) file-templates fold snippets :emacs dired electric undo vc :checkers syntax :tools (eval +overlay) lookup lsp magit :lang (cc +lsp) emacs-lisp json markdown org (python
+lsp) sh :config (default +bindings +smartparens))
        packages   (n/a)
        unpin      (n/a)
        elpa       (n/a)
```
</details>

**Comment by hlissner** [comment]
Did you find a solution to this?

**Comment by chenyidao110** [comment]
>  you find a solut

Delete lsp-mode,install again.Then it works normally
