### ISSUE TITLE
mu4e-header-highlight-face not applied when viewing messages

### ISSUE THREAD

**Issue by pkazmier** [hlissner/doom-emacs#4048]
**What did you expect to happen?**
After selecting a message to view `RET` in the mu4e headers buffer, I expect the view buffer to open beneath the headers buffer with the currently selected message. More importantly, I expect the currently selected message in the headers buffer to remain highlighted in the `mu4e-header-highlight-face`. Below is an image of what I expect to see. Note: the message in the top buffer is _still_ highlighted to reflect which message is opened in the view buffer:
<img width="615" alt="image" src="https://user-images.githubusercontent.com/747855/95353387-d5c58c00-0888-11eb-9e85-c6a1593eef21.png">

**What actually happened?**
Instead, when viewing a specific message, the highlighted message in the headers buffer is no longer highlighted, so it is not possible to determine which message one is viewing in the other buffer:
<img width="615" alt="image" src="https://user-images.githubusercontent.com/747855/95353546-00174980-0889-11eb-8ad0-40f56974d472.png">
If I swap back and forth between buffers using `other-window` several times, eventually, the message will remain highlighted in the headers view. But if you continue to do so, it will lose its highlighting again. Without being able to see what message is currently selected, it is not possible to use mu4e.

**Additional details:**
I used the Doom Sandbox to help isolate issue. The problem does not occur when starting with vanilla Emacs `C-c C-c`. After moving up the stack to vanilla Doom `C-c C-d`, the problem manifested itself. I used the following config when testing:

<details><pre>
(require 'mu4e)
(setq mu4e-mu-binary         "/usr/local/bin/mu"
      mu4e-maildir           "~/.mail"
      mu4e-sent-folder       "/Sent"
      mu4e-drafts-folder     "/Drafts"
      mu4e-trash-folder      "/Trash"
      mu4e-refile-folder     "/Archive")
</pre></details>

There are no error messages other than the following, but this error message was present even when using vanilla Emacs where the problem did not occur:

```
Source file ‘/usr/local/share/emacs/site-lisp/mu/mu4e/mu4e-meta.el’ newer than byte-compiled file; using older file
```

**Steps to reproduce:**
1. Start emacs.
2. Open mu4e `SPC o m`.
3. Jump to a maildir.
4. Use arrow keys to different messages and watch highlight follow.
5. Select currently highlighted message `RET` to open view buffer. Watch highlight disappear from the headers buffer.

**System information:**
<details>

```
SYSTEM  type       darwin
        config     x86_64-apple-darwin19.5.0
        shell      /bin/zsh
        uname      Darwin 19.6.0 Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64
        path       (~/.emacs.d/bin/ ~/bin ~/go/bin ~/.emacs.d/bin ~/.dotfiles/bin /usr/local/bin ~/.cache/zsh4humans/bin ~/.cache/zsh4humans/junegunn/fzf/bin /usr/bin /bin /usr/sbin /sbin /Library/TeX/texbin /usr/local/go/bin /usr/local/Cellar/emacs-plus@27/27.1/libexec/emacs/27.1/x86_64-apple-darwin19.5.0/)
EMACS   dir        ~/.emacs.d/
        version    27.1
        build      Aug 27, 2020
        buildopts  --disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus@27/27.1/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus@27/27.1 --with-xml2 --with-gnutls --without-dbus --with-imagemagick --with-modules --with-rsvg --with-ns --disable-ns-self-contained
        features   RSVG IMAGEMAGICK GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS JSON PDUMPER LCMS2 GMP
        traits     (server-running envvar-file)
DOOM    dir        ~/.doom.d/
        version    2.0.9
        build      HEAD -> develop d807a751 2020-10-06 17:16:37 -0400
        elc-files  0
        modules    (:completion (company +childframe) ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces zen :editor (evil +everywhere) file-templates fold (format +onsave) multiple-cursors snippets :emacs dired electric (ibuffer +icons) undo vc :term vterm :checkers syntax :tools (eval +overlay) lookup lsp magit :lang data emacs-lisp (go +lsp) markdown (org +dragndrop +pretty) (python +lsp) sh yaml :email mu4e :app calendar (rss +org) :config (default +bindings +smartparens))
        packages   ((org-super-agenda) (ox-twbs))
        unpin      (doom-themes)
        elpa       (n/a)
```
</details>

**Comment by gilbertw1** [comment]
Just checked up on this and this appears to be due to Doom's setting of `hl-line-sticky-flag` to `nil`. When this setting is `nil` only the currently selected buffer shows the highlighted line. When it's set to `t` all visible buffers have their current line highlighted.

Since mu4e uses hl-line, this setting unhighlights the selected message in headers view buffer when it's no longer active. Unfortunately it doesn't appear that there is any buffer level setting available that will allow you to selectively keep a specific buffer (like the mu4e headers view) highlighted individually while keeping `hl-line-sticky-flag` set to `nil`.

You can easily fix the problem by setting `hl-line-sticky-flag` to `t`, however you'll have to live with having line highlights shown in all currently visible buffers. I imagine this probably isn't something Doom will want to change at the default level.

**Comment by pkazmier** [comment]
Wow, thanks for researching this as it was driving me nuts! I think I'm able to get the desired behavior as it seems that this variable is a buffer-local variable. I added this to my `config.el` and it seems to work exactly how I wanted. Sticky for only that one buffer, but no others. Thanks again for the help! If someone with a bit more Elisp experience confirms this is the right approach, I'm more that happy to submit a simple PR for mu4e doom module's README.

```
(add-hook! mu4e-headers-mode
  (setq-local hl-line-sticky-flag t))
```

**Comment by gilbertw1** [comment]
No problem!

That was the first approach I took and unfortunately it didn't seem to work. Are you sure it solves the problem for you?

Looking at the source for the function that unhighlights the line, I came to the conclusion that you'd need that buffer local overridden on the buffer you're jumping to. From what I gather when you jump to a new buffer a function runs that deactivates the last buffer's highlight.

Source: https://github.com/emacs-mirror/emacs/blob/master/lisp/hl-line.el#L183

**Comment by gilbertw1** [comment]
I think it'll work successfully for you if you use this:

```elisp
(add-hook! mu4e-header-mode
   (setq-local hl-line-sticky-flag t))

(add-hook! mu4e-loading-mode
   (setq-local hl-line-sticky-flag t))

(add-hook! mu4e-view-mode
   (setq-local hl-line-sticky-flag t))
```

Basically, when you select a message in `mu4e-header-mode` it goes to a buffer with the `mu4e-loading-mode`, then it opens the message in `mu4e-view-mode`. By setting it to sticky for all three of these modes, it never disables the highlight on the previous buffer in `mu4e-header-mode`.

**Comment by pkazmier** [comment]
I only need the first hook and things seem to work okay for me. There are occasional blips but that seems to be with Doom as it happens in the sandbox with vanilla doom. Open two buffers, go back and forth between them, and sometimes the hl-line remains highlighted in the former. Weird.

**Comment by gilbertw1** [comment]
Cool glad it works. It seemed to me to be some type of race condition that would keep the highlight in place roughly 25% of the time. It could be related to when that unhighlight function is called. Either way, if it starts to seem spotty adding all three hooks seems to solve it 100% of the time.

**Comment by pkazmier** [comment]
I think Doom has inconsistent behavior with hL-line as I was able to reproduce in vanilla doom sandbox (no mu4e involved). Take any two buffers and jump back and forth several times and you’ll see the highlight line sometimes remains highlighted in other buffer. I’ll open a bug later when I have time.
