### ISSUE TITLE
Trouble with ssh-ident package (perhaps similar issues apply to any GitHub package where repo and package names are different?)

### ISSUE THREAD

**Issue by ailiop** [hlissner/doom-emacs#4051]
**What did you expect to happen?**

After adding the `ssh-ident` package [(link)](https://github.com/arthurcgusmao/emacs-ssh-ident) to my Doom Emacs configuration, when using magit and trying to pull from a remote host, ssh-ident should ask for my passphrase (or use the cached identity if I had already supplied it earlier).  Similarly for other actions that require communication with the remote host.

**What actually happened?**

I cannot communicate with the remote host and get the following echo in \*Messages\*:
```
run-hooks: Symbol’s function definition is void: ssh-ident-grab-passphrase
```

**Additional details:**

I notice that if I try to inspect the package with `C-h d p p ssh-ident RET` or `(doom/help-packages ssh-ident)` the "Build:" field is empty and I get the following echo in \*Messages\*:
```
apply: Setting current directory: No such file or directory, /home/ailiop/.emacs.d/.local/straight/repos/ssh-ident/
```
And when I search for the offending function (`ssh-ident-grab-passphrase`) I find it at `/home/ailiop/.emacs.d/.local/straight/repos/emacs-ssh-ident/ssh-ident.el` (notice the `emacs-` in the repo directory).

This leads me to suspect that there may be an issue with GitHub packages whose name does not match the repo name.  In this case, the repo name is `emacs-ssh-ident` but the package is `ssh-ident`.

- [config.el](https://www.dropbox.com/s/5z6uleah76gf2lj/config.el?dl=0)
- [packages.el](https://www.dropbox.com/s/r9p54qtx14wtk8j/packages.el?dl=0)
- [screenshot](https://www.dropbox.com/s/9pru209j0878z7u/screenshot_doom_emacs_ssh-ident.png?dl=0)

**Error backtrace**
<details><pre>
Debugger entered--Lisp error: (void-function ssh-ident-grab-passphrase)
  ssh-ident-grab-passphrase()
  run-hooks(magit-credential-hook)
  magit-pull-from-upstream(nil)
  #<subr funcall-interactively>(magit-pull-from-upstream nil)
  apply(#<subr funcall-interactively> (magit-pull-from-upstream nil))
  funcall-interactively(magit-pull-from-upstream nil)
  #<subr call-interactively>(magit-pull-from-upstream nil nil)
  apply(#<subr call-interactively> (magit-pull-from-upstream nil nil))
  explain-pause--wrap-call-interactively(#<subr call-interactively> magit-pull-from-upstream nil nil)
  apply(explain-pause--wrap-call-interactively #<subr call-interactively> (magit-pull-from-upstream nil nil))
  call-interactively(magit-pull-from-upstream nil nil)
  command-execute(magit-pull-from-upstream)
</pre></details>

**Steps to reproduce:**
1. Enable `magit` module in init.el
2. Install `ssh-ident` package.  In packages.el: `(package! ssh-ident :recipe (:host github :repo "arthurcgusmao/emacs-ssh-ident"))`
3. Visit a file in a Git repository and run `magit-pull` from a remote branch (e.g., `C-x g F u`).

**System information:**
<details><pre>
((system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/usr/local/bin/fishlogin")
  (uname . "Linux 4.19.104-microsoft-standard #1 SMP Wed Feb 19 06:37:35 UTC 2020 x86_64")
  (path "~/.emacs.d/bin" "~/.local/bin" "/usr/local/sbin" "/usr/local/bin" "/usr/sbin" "/usr/bin" "/sbin" "/bin" "/usr/games" "/usr/local/games" "/mnt/c/Windows/system32" "/mnt/c/Windows" "/mnt/c/Windows/System32/Wbem" "/mnt/c/Windows/System32/WindowsPowerShell/v1.0/" "/mnt/c/Windows/System32/OpenSSH/" "/mnt/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR" "/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common" "/mnt/c/Program Files/PowerShell/7/" "/mnt/c/Program Files/Docker/Docker/resources/bin" "/mnt/c/ProgramData/DockerDesktop/version-bin" "/mnt/c/Program Files/CrashPlan/jre/bin/server/" "/mnt/c/Program Files/CrashPlan/jre/bin/" "/mnt/c/Users/alexi/AppData/Local/Microsoft/WindowsApps" "/mnt/c/Users/alexi/AppData/Local/Programs/Microsoft VS Code/bin" "/snap/bin" "/usr/lib/emacs/26.3/x86_64-linux-gnu"))
 (emacs
  (dir . "~/.emacs.d/")
  (version . "26.3")
  (build . "Mar 26, 2020")
  (buildopts . "--build x86_64-linux-gnu --prefix=/usr --sharedstatedir=/var/lib --libexecdir=/usr/lib --localstatedir=/var/lib --infodir=/usr/share/info --mandir=/usr/share/man --enable-libsystemd --with-pop=yes --enable-locallisppath=/etc/emacs:/usr/local/share/emacs/26.3/site-lisp:/usr/local/share/emacs/site-lisp:/usr/share/emacs/26.3/site-lisp:/usr/share/emacs/site-lisp --with-sound=alsa --without-gconf --with-mailutils --build x86_64-linux-gnu --prefix=/usr --sharedstatedir=/var/lib --libexecdir=/usr/lib --localstatedir=/var/lib --infodir=/usr/share/info --mandir=/usr/share/man --enable-libsystemd --with-pop=yes --enable-locallisppath=/etc/emacs:/usr/local/share/emacs/26.3/site-lisp:/usr/local/share/emacs/site-lisp:/usr/share/emacs/26.3/site-lisp:/usr/share/emacs/site-lisp --with-sound=alsa --without-gconf --with-mailutils --with-x=yes --with-x-toolkit=gtk3 --with-toolkit-scroll-bars 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/emacs-mEZBk7/emacs-26.3+1=. -fstack-protector-strong -Wformat -Werror=format-security -Wall' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro'")
  (features . "XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS LIBSYSTEMD LCMS2")
  (traits batch server-running envvar-file))
 (doom
  (dir . "~/.doom.d/")
  (version . "2.0.9")
  (build . "HEAD -> develop d807a7513 2020-10-06 17:16:37 -0400")
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline ophints (popup +defaults) treemacs vc-gutter vi-tilde-fringe workspaces :editor file-templates fold snippets :emacs dired electric ibuffer undo vc :term term :checkers syntax spell :tools editorconfig (eval +overlay) lookup magit :lang cc emacs-lisp (haskell +dante) julia (latex +latexmk) markdown (org +pandoc) python sh sml :config (default +bindings +smartparens))
  (packages (matlab-mode) (meson-mode) (floobits :recipe (:host github :repo "Floobits/floobits-emacs")) (ninja-mode) (ox-gfm) (ssh-ident :recipe (:host github :repo "arthurcgusmao/emacs-ssh-ident")) (glsl-mode :disable t) (company-glsl :disable t))
  (unpin "n/a")
  (elpa "rtags")))
</pre></details>

**Comment by hlissner** [comment]
> This leads me to suspect that there may be an issue with GitHub packages whose name does not match the repo name. In this case, the repo name is emacs-ssh-ident but the package is ssh-ident.

This is not the case. Straight (our package manager) clones the repo to `~/.emacs.d/.local/straight/repos/emacs-ssh-ident`, then builds the package into `~/.emacs.d/.local/straight/build/ssh-ident` <-- this is where the package that Emacs sees will live.

If you can't find that directory, then it failed to build when you ran `doom sync`, after adding that `package!` statement to your packages.el.

I threw that exact statement into my private packages.el, ran `doom sync`, booted up Emacs, and `C-h P ssh-ident` takes me to `~/.emacs.d/.local/straight/build/ssh-ident`, without issue.

-----

After a closer look, the issue is in ssh-ident. It only [autoloads the add-hook call](https://github.com/arthurcgusmao/emacs-ssh-ident/blob/master/ssh-ident.el#L76), without autoloading the `ssh-ident-grab-passphrase` function. This means the hook is registered, but Emacs will never know where to find the hook when it runs.

This should be reported upstream, but a quick way around this would be to add one of the following to your config.el (which you choose is personal preference, they are equivalent):

```elisp
(autoload 'ssh-ident-grab-passphrase "ssh-ident")

;; or 

(use-package! ssh-ident
  :commands ssh-ident-grab-passphrase)
```

**Comment by ailiop** [comment]
@hlissner Thanks a lot for your help!  Everything you wrote makes perfect sense.

I wasn't sure what went wrong since it was working fine with `(require 'ssh-ident)` before I switched to Doom Emacs a couple of days ago, but clearly I ended up barking up the wrong tree.  😅 

Also, a big thanks for your work with Doom Emacs.  It is brilliant!
