### ISSUE TITLE
I would like to change org-capture-templates in my config.el, but doom's org/config.el will override it

### ISSUE THREAD

**Issue by margaro95** [hlissner/doom-emacs#4055]
I would like to configure that variable in my config.el as I do with all org variables, that is

```
(use-package! org
  :defer t
  :custom
  (org-directory "~/Dropbox/org")
  ;; Python executable for source blocks
  (org-babel-python-command "python3")
  (org-habit-graph-column 67)
  (org-log-into-drawer t)
  (org-modules '(ol-bibtex org-habit))
  )
```
Unfortunately, if I try to customize org-capture-templates, anything that I write in my config will be overriden by this [doom's org config.el](https://github.com/hlissner/doom-emacs/blob/77646c5f42ef1d3586af7526c06af932d1340ca5/modules/lang/org/config.el#L290).

Configuring these variables that Doom reasonably setups should be an easy task, but right now, the only way of fixing it that I came up was to write this in my config.el
```
(setq org-load-hook (append org-load-hook (list (lambda () (setq org-capture-templates '(("a" "My custom todo" entry
                                                                                     (file+headline +org-capture-todo-file "Inbox")
                                                                                     "* [ ] %?
%i
%a" :prepend t)))))))
```
which is kind of hacky, but gets the job done.

What would be the stylish way to go in Doom Emacs? Is there any consensus over this topic of configuring Doom's setup?

Thank you very much :smile:

**Comment by hlissner** [comment]
If you want to override Doom's defaults, use `(after! org ...)`. This is how all packages should be configured.

```lisp
(after! org
  (setq org-capture-templates ...))
```
