### ISSUE TITLE
cant install anything

### ISSUE THREAD

**Issue by ergpopler** [hlissner/doom-emacs#4057]
I cant install rust mode, rustic, ANYTHING, the version of rustic that comes preinstalled doesnt work and says to update it, but i cannot even after 6 hours of trying...

also when i load a .rs file it says lsp server not running.

./.emacs.d/bin/doom displays:

```
Importing package-keyring.gpg...
Importing package-keyring.gpg...done
Contacting host: elpa.gnu.org:443
Contacting host: elpa.gnu.org:443
Contacting host: melpa.org:443
Contacting host: orgmode.org:443
Package refresh done
((system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/bin/bash")
  (uname . "Linux 5.4.0-7642-generic #46~1598628707~20.04~040157c-Ubuntu SMP Fri Aug 28 18:02:16 UTC  x86_64")
  (path "~/.cargo/bin" "~/.local/bin" "/usr/local/sbin" "/usr/local/bin" "/usr/sbin" "/usr/bin" "/sbin" "/bin" "/usr/games" "/usr/local/games" "/snap/bin" "/usr/lib/cuda/bin" "/usr/lib/emacs/26.3/x86_64-linux-gnu"))
 (emacs
  (dir . "~/.emacs.d/")
  (version . "26.3")
  (build . "Mar 26, 2020")
  (buildopts . "--build x86_64-linux-gnu --prefix=/usr --sharedstatedir=/var/lib --libexecdir=/usr/lib --localstatedir=/var/lib --infodir=/usr/share/info --mandir=/usr/share/man --enable-libsystemd --with-pop=yes --enable-locallisppath=/etc/emacs:/usr/local/share/emacs/26.3/site-lisp:/usr/local/share/emacs/site-lisp:/usr/share/emacs/26.3/site-lisp:/usr/share/emacs/site-lisp --with-sound=alsa --without-gconf --with-mailutils --build x86_64-linux-gnu --prefix=/usr --sharedstatedir=/var/lib --libexecdir=/usr/lib --localstatedir=/var/lib --infodir=/usr/share/info --mandir=/usr/share/man --enable-libsystemd --with-pop=yes --enable-locallisppath=/etc/emacs:/usr/local/share/emacs/26.3/site-lisp:/usr/local/share/emacs/site-lisp:/usr/share/emacs/26.3/site-lisp:/usr/share/emacs/site-lisp --with-sound=alsa --without-gconf --with-mailutils --with-x=yes --with-x-toolkit=gtk3 --with-toolkit-scroll-bars 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/emacs-mEZBk7/emacs-26.3+1=. -fstack-protector-strong -Wformat -Werror=format-security -Wall' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro'")
  (features . "XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS LIBSYSTEMD LCMS2")
  (traits batch envvar-file))
 (doom
  (dir . "~/.doom.d/")
  (version . "2.0.9")
  (build . "grafted, HEAD -> develop, origin/develop, origin/HEAD 0769b47 2020-09-19 14:43:53 -0400")
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline ophints (popup +defaults) vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold snippets :emacs dired electric undo vc :checkers syntax :tools (eval +overlay) lookup magit :lang emacs-lisp org rust sh yaml :config (default +bindings +smartparens))
  (packages (rustic))
  (unpin "n/a")
  (elpa "n/a")))
```

installed via the instructions in the readme.
Ubuntu 20.04

**Comment by hlissner** [comment]
When filing a bug report please include as much information about the issue as possible. If you don't, we likely won't be able to help you.

1. Always include what you tried and what happened when you tried it. What shell commands did you run? What did they output? Please copy it all into your bug report in a code-fenced section like so:

   \`\`\`
   output goes here
   \`\`\`

2. Always include information about your system. If there is an issue template (and there is for this project), _please do not ignore it_. Ours asked you include the output of running `~/.emacs.d/bin/doom info` on the command line. This tells us vital information about your system.

   If somehow you can't provide that, tell us how you acquired Doom, where you're installing it, and what OS you're on.

3. If you have links to your private configuration, or to the tutorial you tried to follow that got you here, those would help tremendously.

-----

As it is, this is not an acceptable bug report. Please edit your original post and add this crucial information.

**Comment by hlissner** [comment]
What does `~/.emacs.d/bin/doom install` output?

**Comment by hlissner** [comment]
1. Run the following commands:

   ```sh
   rm -rf ~/.emacs.d ~/.doom.d
   git clone https://github.com/hlissner/doom-emacs ~/.emacs.d
   ~/.emacs.d/bin/doom install
   ```

2. Open `~/.doom.d/init.el`

3. Scroll down to `;rust` under `:lang` and replace it with `(rust +lsp)`

4. Scroll up to `;lsp` under `:tools` and remove the semicolon in front of it.

5. Install rustup by running this shell command: `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`

6. Install rls with `rustup component add rls rust-analysis rust-src`

7. Run `~/.emacs.d/bin/doom env`

8. Run `~/.emacs.d/bin/doom sync`

9. Start Emacs

And you should be good to go.

**Comment by ergpopler** [comment]
You. Are. The. Best.

It works, thank you.

**Comment by ergpopler** [comment]
Works on Ubuntu but not on Arch, it says **Error from the Language Server: Rust-analyzer is still loading... (Unkown Error)** then never loads.. I've tried everything at https://github.com/hlissner/doom-emacs/issues/2195 to no avail.
