### ISSUE TITLE
Typing j followed by k in input mode deletes j and returns to normal mode

### ISSUE THREAD

**Issue by endragor** [hlissner/doom-emacs#4059]
**What did you expect to happen?**
`jk` entered in input mode should result in `jk` added to the current position without leaving the input mode.

**What actually happened?**
Entering `jk` (notice that `k` should be typed instantly after `j`, otherwise this doesn't reproduce) deletes the first 'j' and leaves input mode.

**Additional details:**

- Reproduced in sandbox without the private config. 

**System information:**
<details><pre>
SYSTEM  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      tmux
        uname      Linux 4.19.0-11-amd64 #1 SMP Debian 4.19.146-1 (2020-09-17) x86_64
        path       (~/.emacs.d/bin/ ~/.cargo/bin ~/.cargo/bin ~/.cargo/bin ~/.cargo/bin /usr/local/bin /usr/bin /bin /usr/games ~/.emacs.d/bin ~/.nimble/bin ~/.emacs.d/bin ~/.nimble/bin /usr/local/libexec/emacs/27.1.50/x86_64-pc-linux-gnu)
EMACS   dir        ~/.emacs.d/
        version    27.1.50
        build      Oct 05, 2020
        buildopts  
        features   XPM JPEG TIFF GIF PNG RSVG SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP
        traits     (server-running)
DOOM    dir        ~/.doom.d/
        version    2.0.9
        build      grafted, HEAD -> develop, origin/develop, origin/HEAD 5b2b660 2020-10-04 23:25:53 -0400
        elc-files  0
        modules    (:input (&nopath russian) :completion (company +tng) ivy :ui doom doom-dashboard doom-quit hl-todo indent-guides modeline ophints (popup +defaults) treemacs vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold multiple-cursors snippets :emacs dired electric undo vc :term eshell vterm :checkers syntax :tools docker (eval +overlay) lookup lsp (magit +forge) tmux :lang cc emacs-lisp gdscript json markdown nim org python (rust +lsp) sh yaml :config (default +bindings +smartparens))
        packages   ((reverse-im :recipe (:host github :repo a13/reverse-im.el)) (flycheck-nim :disable t) (flycheck-nimsuggest :disable t))
        unpin      (n/a)
        elpa       (n/a)
</pre></details>

**Comment by hlissner** [comment]
This is not a bug. This is [evil-escape](https://github.com/syl20bnr/evil-escape) doing its job. Quickly typing j then k = a shortcut to exit insert mode.

To disable this:

1. `(package! evil-escape :disable t)` in `~/.doom.d/packages.el`, then `doom sync` and restart Emacs.
2. Change `evil-escape-key-sequence` (default is `jk`). Maybe you prefer `fd`, or something else?
3. Decrease `evil-escape-delay` (default is `0.15` in seconds). If it's shorter, the chance of invoking evil-escape on `jk` is lower.
4. `(after! evil-escape (evil-escape-mode -1))`
