### ISSUE TITLE
conside change private-repo to seperate directory 

### ISSUE THREAD

**Issue by driftcrow** [hlissner/doom-emacs#406]
### Observed behavior

private repo include private init.el and some private module, thou if I add private module I need link to .emacs.d/... manually. and if I want try anothers config ,then I shoud unlink all my private repo init.el and module dir. then  link others all assets.  when restore then repeate do again .it's  inconvenient.

### Expected behavior

 please conside seperate these private file in one directory like spacemacs for VC and switch  handly.

**Comment by xarthurx** [comment]
upvote.

**Comment by hlissner** [comment]
As of b3dcba5, if you have `:config private` enabled, you can now put your private module in `~/.doom.d` (and sub-modules in `~/.doom.d/modules/`). 

If you'd like to adhere to XDG conventions, use the `+xdg` flag: `(doom! :config (private +xdg))`.

It's still a little experimental. Let me know if it gives you trouble.

**Comment by driftcrow** [comment]
thanks for code, it works fine
