### ISSUE TITLE
open .sql file show the error

### ISSUE THREAD

**Issue by vinurs** [hlissner/doom-emacs#4060]
**What did you expect to happen?**
open sql file correctly

**What actually happened?**
it shows the error, and not auto enable sql-mode, i have to enable sql-mode manually
```
File mode specification error: (error Autoloading file /Users/vinurs/.emacs.d/.local/straight/build/sql-indent/sql-indent.el failed to define function sql-indent)
```

**Comment by hlissner** [comment]
This is a private config issue. From the sound of it you are calling a `sql-indent` function, but one does not exist. I looked up the source code there is no `sql-indent` function.

Perhaps you meant to call `sql-indent-enable`?
