### ISSUE TITLE
Incorrect use of `plist-put` in documentation

### ISSUE THREAD

**Issue by MithicSpirit** [hlissner/doom-emacs#4061]
### What did you expect to happen?
Using `plist-put` as shown in [modules/ui/ligatures/README.org](https://github.com/hlissner/doom-emacs/blob/develop/modules/ui/ligatures/README.org#changing-ligatures) to change the default ligatures (as a workaround for #4054) should work fine:
```elisp
(plist-put +ligatures-extra-symbols
  '(:map           "→"
    :return        "↦"
    :yield         "↤"
    :tuple         "⊗"))
```

### What actually happened?
There is an error that I'm passing the wrong number of arguments to `plist-put`. Looking at the documentation for `plist-put` it appears that each new property must be added individually; also, it says that it should be stored back into the `plist` because it "is modified by side effects." This is the supposed correct way to use `plist-put`: 
```elisp
(setq PLIST (plist-put PLIST PROP1 VAL1))
(setq PLIST (plist-put PLIST PROP2 VAL2))
```

### Additional details:
- [.doom.d in my dotfiles repo](https://github.com/MithicSpirit/dotfiles/tree/aceb4cb36757205e8054cbafa7ea972b3440bf0a/.doom.d)
- Error message: `error in process sentinel: Error in private config: "config.el", (wrong-number-of-arguments plist-put 2)`

#### Backtrace
<details><pre>
Debugger entered--Lisp error: (wrong-number-of-arguments plist-put 2)
  (plist-put +ligatures-extra-symbols '(:map "→" :return "↦" :yield "↤" :union "∪" :tuple "⊗"))
  #<subr eval-buffer>(#<buffer  *load*> nil "/home/mithic/.doom.d/config.el" nil t)
  apply(#<subr eval-buffer> (#<buffer  *load*> nil "/home/mithic/.doom.d/config.el" nil t))
  eval-buffer(#<buffer  *load*> nil "/home/mithic/.doom.d/config.el" nil t)  ; Reading at buffer position 4545
  load-with-code-conversion("/home/mithic/.doom.d/config.el" "/home/mithic/.doom.d/config.el" t t)
  #<subr load>("/home/mithic/.doom.d/config" t nomessage nil nil)
  apply(#<subr load> ("/home/mithic/.doom.d/config" t nomessage))
  load("/home/mithic/.doom.d/config" t nomessage)
  doom-initialize-modules(force)
  doom-initialize(force)
  #f(compiled-function (buf status) #<bytecode 0xbee5a1>)(#<buffer *compilation*> "finished\n")
  run-hook-with-args(#f(compiled-function (buf status) #<bytecode 0xbee5a1>) #<buffer *compilation*> "finished\n")
  compilation-handle-exit(exit 0 "finished\n")
  compilation-sentinel(#<process comint> "finished\n")
</pre></details>

### Steps to reproduce
1. Try to use `plist-put` as suggested in [modules/ui/ligatures/README.org](https://github.com/hlissner/doom-emacs/blob/develop/modules/ui/ligatures/README.org#changing-ligatures)
2. Restart EMACS or use `SPC h r r` to reload
3. There should be an error at the bottom of the window

### System information
<details><pre>
((system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/usr/bin/zsh")
  (uname . "Linux 5.4.0-47-generic #51-Ubuntu SMP Fri Sep 4 19:50:52 UTC 2020 x86_64")
  (path "~/.nvm/versions/node/v12.18.2/bin" "~/.local/bin" "~/bin" "/usr/local/bin" "~/.local/bin" "/usr/local/sbin" "/usr/local/bin" "/usr/sbin" "/usr/bin" "/sbin" "/bin" "/usr/games" "/usr/local/games" "/snap/bin" "/usr/lib/emacs/27.1/x86_64-linux-gnu"))
 (emacs
  (dir . "~/.emacs.d/")
  (version . "27.1")
  (build . "Sep 19, 2020")
  (buildopts . "--build=x86_64-linux-gnu --prefix=/usr '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' --sysconfdir=/etc --localstatedir=/var --disable-silent-rules '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' --disable-maintainer-mode --disable-dependency-tracking --prefix=/usr --sharedstatedir=/var/lib --libexecdir=/usr/lib --localstatedir=/var/lib --infodir=/usr/share/info --mandir=/usr/share/man --enable-locallisppath=/etc/emacs:/usr/local/share/emacs/27.1/site-lisp:/usr/local/share/emacs/site-lisp:/usr/share/emacs/27.1/site-lisp:/usr/share/emacs/site-lisp --program-suffix=27 --with-modules --with-file-notification=inotify --with-mailutils --with-harfbuzz --with-json --with-x=yes --with-x-toolkit=gtk3 --with-lcms2 --with-cairo --with-xpm=yes --with-gif=yes --with-gnutls=yes --with-jpeg=yes --with-png=yes --with-tiff=yes --with-xwidgets 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/emacs27-bifpWT/emacs27-27.1~1.git86d8d76aa3=. -fstack-protector-strong -Wformat -Werror=format-security -no-pie' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro -no-pie'")
  (features . "XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER LCMS2 GMP")
  (traits batch server-running envvar-file))
 (doom
  (dir . "~/.doom.d/")
  (version . "2.0.9")
  (build . "HEAD -> develop 8ba2f15c7 2020-10-08 16:39:45 -0400")
  (elc-files . 184)
  (modules :completion company (ivy +prescient +icons) :ui doom doom-dashboard doom-quit fill-column hl-todo indent-guides (ligatures +fira +extra) minimap modeline nav-flash ophints (popup +defaults) treemacs unicode vc-gutter vi-tilde-fringe workspaces zen :editor (evil +everywhere) file-templates fold (format +onsave) multiple-cursors snippets word-wrap :emacs (dired +icons) electric undo vc :term vterm :checkers syntax (spell +everywhere) grammar :tools debugger ein eval (lookup +dictionary +offline) lsp (magit +forge) pdf rgb :lang (cc +lsp) emacs-lisp (json +lsp) (javascript +lsp) (latex +latexmk +lsp +fold) (markdown +grip) (org +pretty) (python +lsp +poetry) (sh +lsp) (yaml +lsp) :email (mu4e +gmail) :app calendar irc :config (default +bindings +smartparens))
  (packages "n/a")
  (unpin "n/a")
  (elpa "n/a")))
</pre></details>

**Comment by gilbertw1** [comment]
I'm thinking this might be a typo in the documentation. There's a macro available that shadows the built-in function: `plist-put!` that looks as though it functions like you expect. Source here:

https://github.com/hlissner/doom-emacs/blob/develop/core/autoload/plist.el#L25

**Comment by hlissner** [comment]
#4063 was merged, which should resolve this issue. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
