### ISSUE TITLE
Disable ws-butler

### ISSUE THREAD

**Issue by Adnios** [hlissner/doom-emacs#4071]
How do I disable ws-butler mode?

I write "(setq ws-butler-global-mode nil)" in .doom.d/config.el, but it doesn't take affect.

**Comment by legendary-mich** [comment]
If you want to get rid of ws-butler for good, you can put (as I did) these lines in your `.doom.d/packages.el` and run `doom sync`.
```emacs-lisp
;; ws-butler spoils the undo history when you save a file while having the cursor on a freshly added new line.
;; editorconfig handles whitespaces just fine, so I don't need the broken sophistication anyway.
(package! ws-butler :disable t)
```

If you want to disable it only in some buffers than I don't know.

**Comment by Adnios** [comment]
> If you want to get rid of ws-butler for good, you can put (as I did) these lines in your `.doom.d/packages.el` and run `doom sync`.
> 
> ```emacs-lisp
> ;; ws-butler spoils the undo history when you save a file while having the cursor on a freshly added trailing whitespace.
> ;; editorconfig handles whitespaces just fine, so I don't need the broken sophistication anyway.
> (package! ws-butler :disable t)
> ```
> 
> If you want to disable it only in some buffers then I don't know.

thx, it helped

**Comment by hlissner** [comment]
> ;; ws-butler spoils the undo history when you save a file while having the cursor on a freshly added trailing whitespace.
> ;; editorconfig handles whitespaces just fine, so I don't need the broken sophistication anyway.

@legendary-mich Seems like this was never reported anywhere. Could you turn it back on and see if `(setq ws-butler-keep-whitespace-before-point nil)` fixes it?

**Comment by legendary-mich** [comment]
Hey @hlissner 
Yes, `(setq ws-butler-keep-whitespace-before-point nil)` seems to fix it.

If you want to reproduce the issue, take a look at the screenshots.
- Add a line with two "aa"
- Add a line with two "bb"
- Go a few lines up
- Add some whitespaces at the end of the line (The more spaces you add, the more apparent the problem will be)
- Save the file
- Undo the changes a few times
You can see the result on the second screenshot.

![ws-butler-before](https://user-images.githubusercontent.com/7064526/95674934-d8d7b980-0bb3-11eb-9b6f-cf768b3a7a39.jpg)
![ws-butler-after-undo](https://user-images.githubusercontent.com/7064526/95674937-dd03d700-0bb3-11eb-8560-c2533eff75f5.jpg)
