### ISSUE TITLE
fancy-splash-image background not transparent with svg image

### ISSUE THREAD

**Issue by bryanhonof** [hlissner/doom-emacs#4077]
**What did you expect to happen?**
I expected the dashboard image to be transparent when setting the `fancy-splash-image` to an svg with the following code.
```lisp
(setq fancy-splash-image "~/.config/doom/Emacs-logo.svg")
```

**What actually happened?**
The actual image is displayed correctly but with a white background instead of a transparent one.
I also checked the *Messages* buffer but nothing of note is found in there.
![image](https://user-images.githubusercontent.com/5932804/95680352-5661f080-0bd9-11eb-8f74-6279a0e6a3d3.png)

Is this know behavior? If so I would be willing to update the documentation making user aware of this.
If not, could it have something to do that I am running NixOS?
The svg I am using can be found over [here](https://commons.wikimedia.org/wiki/File:Emacs-logo.svg)

**System information:**
<details>

```
SYSTEM  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /run/current-system/sw/bin/bash
        uname      Linux 5.8.13 #1-NixOS SMP Thu Oct 1 15:36:35 UTC 2020 x86_64
        path       (~/.config/emacs/bin/ /run/wrappers/bin ~/.nix-profile/bin /etc/profiles/per-user/$USER/bin /nix/var/nix/profiles/default/bin /run/current-system/sw/bin /nix/store/a8rrv9jfmj7fc8jyf9sn2qmv0zhyr28s-emacs-gcc-20201010.0/libexec/emacs/28.0.50/x86_64-pc-linux-gnu/)
EMACS   dir        ~/.config/emacs/
        version    28.0.50
        build      Oct 11, 2020
        buildopts  --prefix=/nix/store/a8rrv9jfmj7fc8jyf9sn2qmv0zhyr28s-emacs-gcc-20201010.0 --disable-build-details --with-modules --with-x-toolkit=gtk3 --with-xft --with-cairo --with-nativecomp CFLAGS=-DMAC_OS_X_VERSION_MAX_ALLOWED=101200
        features   XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND DBUS GSETTINGS GLIB NOTIFY INOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES NATIVE_COMP THREADS LIBSYSTEMD JSON PDUMPER
        traits     (server-running envvar-file)
DOOM    dir        ~/.config/doom/
        version    2.0.9
        build      HEAD -> develop 3e2c98a0a 2020-10-10 23:19:06 -0400
        elc-files  0
        modules    (:completion (company +childframe) ivy :ui doom doom-dashboard doom-quit hl-todo indent-guides modeline ophints (popup +defaults) treemacs unicode vc-gutter vi-tilde-fringe workspaces :editor file-templates fold (format +onsave) multiple-cursors snippets :emacs dired electric undo vc :term vterm :checkers syntax spell grammar :tools (debugger +lsp) direnv editorconfig (eval +overlay) lookup (lsp +peek) magit make pass pdf rgb :lang (cc +lsp) clojure common-lisp data emacs-lisp erlang gdscript (haskell +dante) hy json (java +lsp) javascript julia latex lua nix (org +roam +pretty) php (python +lsp +pyright) qt scala scheme sh yaml :config (default +bindings +smartparens))
        packages   ((org-ref) (platformio-mode) (gradle-mode) (org-scrum) (tree-sitter :recipe (:host github :repo ubolonton/emacs-tree-sitter :files (lisp/*.el))) (tree-sitter-langs :recipe (:host github :repo ubolonton/emacs-tree-sitter :files (langs/*.el langs/queries))))
        unpin      (n/a)
        elpa       (n/a)
```
</details>

**Comment by bryanhonof** [comment]
Ok, the plot thickens. When evaluating the piece of code in buffer with `C-x C-e`, (yes I use the default emacs bindings, forgive me for I have sinned) And than opening the buffer with `+doom-dashboard/open` it does display the image with a transparent background instead of the white one.

However, in the *Messages* buffer there seems to be nothing of interest.
![image](https://user-images.githubusercontent.com/5932804/95681790-09364c80-0be2-11eb-80d7-b52c5ca637b4.png)

**Comment by hlissner** [comment]
I suspect this may be an upstream issue (with Emacs 28). I cannot reproduce this on Emacs 27.1.

**Comment by snyball** [comment]
@bryanhonof Also experiencing this on Emacs 28, however you don't need to evaluate code with `C-x C-e`, switching to another buffer and back to the splash-screen is enough to make the background transparent.

**Comment by bryanhonof** [comment]
Honestly not quite sure what ended up fixing this. But, I haven't noticed this behavior for quite some time now. So I think it's time to close this issue :).
