### ISSUE TITLE
ccls-initialization-options  can't be specified in ~/.doom.d/config.el

### ISSUE THREAD

**Issue by myrgy** [hlissner/doom-emacs#4083]
**What did you expect to happen?**

`~/.doom.d/config.el`
```
(setq ccls-initialization-options `(:copmileDefinitionsDirectory "build"))
```

**What actually happened?**
That configuration doesn't work.
It was broken with: https://github.com/hlissner/doom-emacs/pull/3879

We need to call 
```
(setq ccls-initialization-options
      (append ccls-initialization-options
...
````

@gagbo

**Comment by gagbo** [comment]
If you want to overwrite it use `(after! ccls (setq ccls-initialization-options …))`.

In anycase there's no easy function to merge those plist properly (i.e. what happens if you want to add/change some keys in `:index`). So if you want to change the init options, it's best to wrap them in `after! ccls` (or in `.dir-locals.el`) and assume that you want to overwrite everything

**Comment by hlissner** [comment]
As gagbo suggested, it must be wrapped in `(after! ccls ...)`. The canonical way to configure packages (and have your configuration override defaults) has always been to use `(after! PACKAGE ...)`.

If keystrokes are the issue, you could do one of the following (should be wrapped in `(after! ccls ...)`):

1. `(plist-put ccls-initialization-options :compileDefinitionsDirectory "build")`
2. `(appendq! ccls-initialization-options '(:compileDefinitionsDirectory "build"))`

As this isn't a bug I will close this.

Hope that helps!

**Comment by myrgy** [comment]
Thanks a lot!

**Comment by myrgy** [comment]
@hlissner , @gagbo  I can't use `after!` because  options are applied at ` :config`
as a result my after! configuration is executed before and overridden with the default settings

```
(use-package! ccls
  :when (featurep! +lsp)
  :unless (featurep! :tools lsp +eglot)
  :after lsp-mode
  :init
  (after! projectile
...
  :config
  (add-hook 'lsp-after-open-hook #'ccls-code-lens-mode)
  (set-evil-initial-state! 'ccls-tree-mode 'emacs)
  (setq ccls-sem-highlight-method 'font-lock)
  (when (or IS-MAC IS-LINUX)
    (let ((cpu-count-command (cond (IS-MAC '("sysctl" "-n" "hw.ncpu"))
                                   (IS-LINUX '("nproc"))
                                   (t (error "unreachable code")))))
      (setq ccls-initialization-options
            `(:index (:trackDependency 1
                      :threads ,(max 1 (/ (string-to-number (cdr (apply #'doom-call-process cpu-count-command))) 2)))))))
  (when IS-MAC
...
```

**Comment by hlissner** [comment]
@myrgy Please update Doom, this was fixed yesterday.

**Comment by myrgy** [comment]
Works fine for me. Thanks!
