### ISSUE TITLE
Company-Mode not working in elixir/alchemist files

### ISSUE THREAD

**Issue by DonHansDampf** [hlissner/doom-emacs#409]
Greetings,

running the most recent master branch company-mode seems not to work in alchemist-mode. Company-mode seems to be enabled. When i open a .ex-file for the first time, i get the error message `Error (use-package): elixir-mode/:config: Wrong type argument: consp, nil`. 

Running macOS 10.12.16 with DOOM v2.0.9.

**Comment by hlissner** [comment]
Are you on `develop` or `master`?

**Comment by DonHansDampf** [comment]
I am on master. But i think there is in general something wrong with the alchemist-mode. Using the built-in REPL will often freeze emacs completely. For example i simply opened up a project REPL (`alchemist-iex-project-run`) changed my project code, and wanted to recompile `alchemist-iex-reload-module` which used the command `r()` and froze emacs.

**Comment by hlissner** [comment]
Can you get out of it by pressing `C-g` (maybe multiple times)?

Unfortunately, I know little about Elixir, so I can't offer much insight. Perhaps this issue is relevant to https://github.com/tonini/alchemist.el/issues/326?

**Comment by DonHansDampf** [comment]
Can't replicate the issue at the moment. But i will do so later. Thanks for the linked issue!

Do you have any clue why company-mode doesn't work?

**Comment by dsdshcym** [comment]
This PR fixed this issue. https://github.com/tonini/alchemist.el/pull/314

But alchemist.el seems to be inactive for a long time, so it hasn't got merged. I've been using this fork for some time, and it worked fine for me.

**Comment by hlissner** [comment]
I haven't decided whether to put the fork in Doom or not, but in the meantime, something like this added to your private module's packages.el file should work:

```elisp
(package! alchemist :recipe (:fetcher github :repo "whysoserious/alchemist.el" :branch "prevent-alchemist-iex-buffer-from-hanging"))
```

> Do you have any clue why company-mode doesn't work?

I suspect that consp error is related to the smartparens config in lang/elixir. Could you comment out https://github.com/hlissner/doom-emacs/blob/master/modules/lang/elixir/config.el#L8-L14 and tell me if that resolves your issue?

**Comment by DonHansDampf** [comment]
> I haven't decided whether to put the fork in Doom or not, but in the meantime, something like this added to your private module's packages.el file should work:

Will try this out, thanks!

> I suspect that consp error is related to the smartparens config in lang/elixir. Could you comment out https://github.com/hlissner/doom-emacs/blob/master/modules/lang/elixir/config.el#L8-L14 and tell me if that resolves your issue?

Emacs will not start up probably with these lines commented out:

```
Warning (initialization): An error occurred while loading ‘/Users/marcel/.emacs.d/init.el’:

End of file during parsing: /Users/marcel/.emacs.d/modules/lang/elixir/config.el
```

**Comment by hlissner** [comment]
That's because there's now a missing closing parenthesis. You'll need to comment those lines out and add a `)` after them.

**Comment by DonHansDampf** [comment]
Sorry, missed that one. 

Emacs loads up now fine, and i also don't get the `Error (use-package): elixir-mode/:config: Wrong type argument: consp, nil` displayed. 

Autocomplete now works after pressing `C-SPC` but i think this is behaviour intented https://github.com/hlissner/doom-emacs/issues/77

**Comment by hlissner** [comment]
Ah, that's what you meant. Yes, _auto_ completion is disabled by default. In `master`, you can develop it by adding this to your private module:

```elisp
(require 'company)
(setq company-idle-delay 0.2)
```

**Comment by DonHansDampf** [comment]
Am on `master` and added `(require 'company) \n (setq company-idle-delay 0.2)` to my `.emacs.d/modules/private/default/config.el`-file. But i still only get autocompletion after the keybinding. 

The private module gets loaded, since i already changed some settings.

**Comment by nresni** [comment]
Hi,
After updating `develop` I have the following error:

> No file named /home/marcel/.emacs.d/.local/packages/elpa/alchemist-20180219.937/alchemist-server/run.exs

**Comment by hlissner** [comment]
@nresni Sorry about that, the quelpa recipe I was using was incomplete. I just fixed it. However, you'll need to delete alchemist manually for the fix to work:

This should do it:

```bash
rm -rf ~/.emacs.d/.local/packages/elpa/achemist-2*
```

Then run `make` in `~/.emacs.d` to reinstall it.

**Comment by nresni** [comment]
Yes it works ! thank you
