### ISSUE TITLE
Manually adjust fontSize, company throw "Invalid face" error

### ISSUE THREAD

**Issue by jadestrong** [hlissner/doom-emacs#4092]
<details><pre>
Debugger entered--Lisp error: (error "Invalid face")
  internal-get-lisp-face-attribute(nil :background nil)
  face-attribute(nil :background nil t)
  company--face-attribute(nil :background)
  company--face-attribute((:height 1.2) :background)
  #f(compiled-function (f) #<bytecode 0x1ffce4f62cef91>)((:height 1.2))
  company--face-attribute(((:height 1.2) solaire-default-face) :background)
  company--face-attribute(default :background)
  company--replacement-string((... ... ... ... ... ... ... ... ... ... ... ... ... ...) (... ... ... ... ... ... ... ... ... ... ... "" ... ...) 7 nil nil)
  company-pseudo-tooltip-show(47 7 0)
  company-pseudo-tooltip-show-at-point(4513 3)
  company-pseudo-tooltip-frontend(post-command)
  company-call-frontends(post-command)
  company-post-command()
  company-idle-begin(#<buffer index.tsx> #<window 3 on index.tsx> 5483 4513)
  apply(company-idle-begin (#<buffer index.tsx> #<window 3 on index.tsx> 5483 4513))
  timer-event-handler([t 24454 37917 292455 nil company-idle-begin (#<buffer index.tsx> #<window 3 on index.tsx> 5483 4513) nil 0])

</pre></details>

**Steps to reproduce:**
1.  use `Ctrl +` manually adjust fontSize;
2. Then company will throw this error

**System information:**
<details>

```
SYSTEM  type       darwin
        config     x86_64-apple-darwin19.6.0
        shell      /usr/local/bin/fish
        uname      Darwin 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64
        path       (~/Documents/$USER/uniswap-interface/node_modules/.bin/ ~/.nix-profile/bin ~/.emacs.d/bin ~/.cargo/bin /run/current-system/sw/bin ~/.nvm/versions/node/v10.16.3/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /Library/Apple/usr/bin /nix/store/qvhrkfslnpcq7qpz87195kqfksb31b8w-emacsGccDarwin/libexec/emacs/28.0.50/x86_64-apple-darwin19.6.0/)
EMACS   dir        ~/.emacs.d/
        version    28.0.50
        build      Oct 14, 2020
        buildopts  --prefix=/nix/store/qvhrkfslnpcq7qpz87195kqfksb31b8w-emacsGccDarwin --disable-build-details --with-modules --with-ns --disable-ns-self-contained --with-nativecomp --with-ns CFLAGS=-DMAC_OS_X_VERSION_MAX_ALLOWED=101200
        features   JPEG TIFF PNG RSVG GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES NATIVE_COMP THREADS JSON PDUMPER
        traits     (server-running envvar-file)
DOOM    dir        ~/dotfiles/home/.doom.d/
        version    2.0.9
        build      HEAD -> develop 0b480a6aa 2020-10-13 21:51:11 -0400
        elc-files  0
        modules    (:input (&user chinese) :completion company ivy :ui deft doom doom-quit hl-todo modeline ophints (popup +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold format multiple-cursors rotate-text snippets word-wrap :emacs dired electric ibuffer undo vc :checkers syntax :tools docker editorconfig (eval +overlay) lookup lsp magit :os macos :lang data emacs-lisp json (javascript +lsp) markdown (org +pretty +brain +dragndrop +hugo +journal +roam +present) (python +lsp) (rust +lsp) sh (web +lsp) :config (default +bindings +smartparens))
        packages   ((js-doc) (react-snippets) (evil-matchit) (leetcode :recipe (:host github :repo jadestrong/leetcode.el)) (insert-translated-name :recipe (:host github :repo manateelazycat/insert-translated-name)) (company-tabnine :recipe (:host github :repo TommyX12/company-tabnine)) (eslintd-fix) (tsc :recipe (:host github :repo ubolonton/emacs-tree-sitter :files (core/*.el))) (tree-sitter :recipe (:host github :repo ubolonton/emacs-tree-sitter :files (lisp/*.el))) (tree-sitter-langs :recipe (:host github :repo ubolonton/emacs-tree-sitter :files (langs/*.el langs/queries))))
        unpin      (n/a)
        elpa       (n/a)
```
</details>

**Comment by hlissner** [comment]
This issue originations from company-mode (one of my PRs, it seems). I've PRed a fix for it. I'll keep this issue open until it is merged.

Here is a workaround for the time being:

```elisp
(defadvice! fix-company--face-attribute (orig-fn face attr)
  :around #'company--face-attribute
  (unless (null face)
    (funcall orig-fn face attr)))
```

**Comment by jadestrong** [comment]
It works. Thanks!

**Comment by jadestrong** [comment]
I also have another question, after adjust font-size, only the edit area' font-size changed, but mode-line and mini-buffer remain the same?

**Comment by hlissner** [comment]
@jadestrong That's how text-scale works. It only operates in the current buffer. Use `doom/increase-font-size` (`M-C-=`) and `doom/decrease-font-size` (`M-C--`) to change font across the entire frame.
 `C-+` will reset this (and text-scale).

**Comment by hlissner** [comment]
As of 963f96b this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
