### ISSUE TITLE
org-capture gives error when using org-set-tags

### ISSUE THREAD

**Issue by omarelashkar** [hlissner/doom-emacs#4098]
**What did you expect to happen?**
...
I am trying to use org-set-tags, or org-set-tags-command on org-template instead of cousel-org-tag that is fired by %^g. 

By the way, both cousel-org-tag and org-set-tag-command are mapped to SPC-m-q, as I prefer the latter for productivity, I would suggest to bind it to SPC-m-Q!

Back to the main problem, I am trying to implement the following template and I expect to be prompted to select tags.
```
(after! org
  (setq org-capture-templates
("s" "Tasks" entry
           (file "~/org/tasks.org")
           "*  %(org-set-tags) \n"
           )
))
```
Reload and restart, then press SPC-X s 

**What actually happened?**
...
When the capture buffer fires up, I got heading as follows:

```
* %![Error: (wrong-number-of-arguments (1 . 1) 0)] 
```

emacs version:  23.6
doom version: 2.0.9
org version: 9.4

**Comment by hlissner** [comment]
Your code a) has a syntax error and b) does not use `org-set-tags` correctly. Try:

```elisp
(after! org
  (setq org-capture-templates
        '(("s" "Tasks" entry
           (file "~/org/tasks.org")
           "*  %(org-set-tags '("tag1" "tag2" "tag3")) \n"))))
```

> emacs version: 23.6

I _think_ you meant 26.3, right? Doom only supports 26.x and above.

> * %![Error: (wrong-number-of-arguments (1 . 1) 0)] 

If the above solution does not work [please produce a backtrace from this error.](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#how-to-extract-a-backtrace-from-an-error), and please include a backtrace whenever you have an error message.

> emacs version: 23.6
> doom version: 2.0.9
> org version: 9.4

This is normally not enough information to go on. If the above solution work please also include your `M-x doom/info` or the output of `~/.emacs.d/bin/doom info`.

----

These are suggested to you in the issue template. Kindly, do not ignore it in the future.

Hope that helps!
