### ISSUE TITLE
How to doom setup Emacs as IDE.

### ISSUE THREAD

**Issue by RohitSingh107** [hlissner/doom-emacs#4100]
I am new to Emacs and big fan your distribution, Doom Emacs. I want to setup emacs as Python IDE but don't known how. Please add how to setup doom emacs as IDE in Documentation, It will be really helpful for beginners like me. Thanks in advance 🙂.

**Comment by hlissner** [comment]
+ [How to enable LSP support for \<insert language here\>](https://github.com/hlissner/doom-emacs/blob/develop/docs/faq.org#how-do-i-enable-lsp-support-for-insert-language-here)
+ [Python prerequisites](https://github.com/hlissner/doom-emacs/blob/develop/modules/lang/python/README.org#prerequisites)
+ [Don't know how to enable modules?](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#modules)
