### ISSUE TITLE
company mode +childframe displays only one column

### ISSUE THREAD

**Issue by terinjokes** [hlissner/doom-emacs#4101]
**What did you expect to happen?**
When the company completion menu appears with `+childframe`, I expect to be able to read the text contained within the menu.

**What actually happened?**
Only one column appears, as seen below.

<details>
<img src="https://user-images.githubusercontent.com/273509/96184346-3b4ef380-0eed-11eb-8b95-edeb7593a11e.png" />
</details>

**Additional details:**
- I can reproduce this in eshell in the `C-c C-p` sandbox with the following modules provided in the system info below.
- Removing `+childframe` restores correct behavior.

**Steps to reproduce:**
1. Enable `+childframe`
2. `M-x eshell` (this is reproducible in other modes too, but this is the easiest to reproduce)
3. Begin typing a command and hit `TAB` to invoke company, be unable to see items in the menu.

**System information:**
<details><pre>
((system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/run/current-system/sw/bin/zsh")
  (uname . "Linux 5.4.69 #1-NixOS SMP Thu Oct 1 11:19:27 UTC 2020 x86_64")
  (path "/nix/store/kksb5p22fxsdhd937lyrk9jihjfr7jla-emacs-packages-deps/bin" "/run/wrappers/bin" "~/.nix-profile/bin" "/run/current-system/sw/bin" "/nix/store/733vncig2mn6nbvzdxndj6d06qdy6syl-emacs-26.3/libexec/emacs/26.3/x86_64-pc-linux-gnu"))
 (emacs
  (dir . "~/.emacs.d/")
  (version . "26.3")
  (build . "Oct 15, 2020")
  (buildopts . "--prefix=/nix/store/733vncig2mn6nbvzdxndj6d06qdy6syl-emacs-26.3 --disable-build-details --with-modules --with-x-toolkit=gtk3 --with-xft CFLAGS=-DMAC_OS_X_VERSION_MAX_ALLOWED=101200")
  (features . "XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD")
  (traits batch server-running))
 (doom
  (dir . "~/.doom.d/")
  (version . "2.0.9")
  (build . "grafted, HEAD -> develop, origin/develop, origin/HEAD 5eb7e6ed 2020-10-15 03:59:12 -0400")
  (elc-files . 0)
  (modules :completion (company +childframe) (ivy +prescient +fuzzy) :ui doom doom-dashboard doom-quit hl-todo modeline ophints (popup +defaults) vc-gutter vi-tilde-fringe (window-select +numbers) workspaces :editor (evil +everywhere) file-templates fold (format +onsave) snippets :emacs dired electric undo vc :term eshell vterm :checkers syntax (spell +aspell +flyspell) :tools direnv (eval +overlay) lookup lsp magit pdf :lang emacs-lisp (go +lsp) javascript markdown nix (org +pretty) sh yaml :config (default +bindings +smartparens))
  (packages (atomic-chrome) (keychain-environment))
  (unpin "n/a")
  (elpa "vterm")))
</pre></details>

**Comment by hlissner** [comment]
Judging from your `M-x doom/info` `:completion (company +childframe)` is not enabled. Did you remember to run `doom sync` (and restart Emacs) after enabling it?

**Comment by terinjokes** [comment]
Sorry, I disabled it to fix this issue, and forgot to reenable it before filing this bug.

**Comment by hlissner** [comment]
I cannot reproduce this in vanilla Doom.

![image](https://user-images.githubusercontent.com/510883/96189866-4fa3e800-0f0f-11eb-8a3b-258b088870d0.png)

In fact, TAB does not even bring up company's posframe. `C-SPC` does.

![image](https://user-images.githubusercontent.com/510883/96189968-719d6a80-0f0f-11eb-88ef-81fad8f597f9.png)

TAB brings up the pcomplete overlay.

I have mirrored your config, except that I'm using Emacs 27.1. Maybe upgrading will fix it the issue?

**Comment by terinjokes** [comment]
Upgrading to 27.1 works fine, so if I wanted a few more days for 20.09 I probably would have been fine.
