### ISSUE TITLE
Make doom/delete-this-file respect trash settings.

### ISSUE THREAD

**Issue by Janfel** [hlissner/doom-emacs#4103]
**Describe the feature**
Emacs provides the variable `delete-by-moving-to-trash` which specifies what to do when the TRASH argument to `delete-file` or `delete-directory` is non-nil. Both `delete-file` and `delete-directory` set TRASH to `t` when called interactively, and to `nil` when called with a prefix argument. `doom/delete-this-file` does not follow this convention and always deletes the specified file regardless of the value of `delete-by-moving-to-trash`. This behavior is counterintuitive and may lead to data loss.

**Comment by hlissner** [comment]
As of b6fe731 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
