### ISSUE TITLE
org-roam.db location

### ISSUE THREAD

**Issue by pawel-ziecina** [hlissner/doom-emacs#4108]
Hi, recently in ea575e3 commit `org-roam-db-location` was set to be inside `org-roam-directory`, while most recent `org-roam` release (1.2.2) moves it to `user-emacs-directory` (https://github.com/org-roam/org-roam/pull/1164).

Change in the `org-roam` project makes sense for me, as it resolves likely paths conflict saved in DB while synchronizing `org-roam-directory` between workstations.

Is it possible to keep the default `org-roam` behavior?

@hlissner

**Comment by hlissner** [comment]
As of 077bab4 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
