### ISSUE TITLE
Magit status buffer sometimes loses the ability to be closed by +magit/quit

### ISSUE THREAD

**Issue by RBckmnn** [hlissner/doom-emacs#4111]
This is definitely a minor issue. I just wanted to put it on the issue tracker so that it finds its way into the backlog.

Here are the steps to reproduce:

1. Invoke `magit-status` (`SPC g g`) to open the status buffer for a git repo that has at least one unstaged change
2. In the status buffer, navigate to a file with unstaged changes and press `RET` to visit that file
3. Kill the new buffer using `kill-current-buffer` (`SPC b k`).
4. You should be back in the magit status buffer.
5. Invoking `+magit/quit` (`q`) has no effect

Some observations:
If one does not kill the buffer in 3. but merely switches back to the status buffer, the status buffer is killed as expected.

<details>

```
SYSTEM  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/bash
        uname      Linux 5.4.66-gentoo #1 SMP Tue Sep 29 21:07:25 CEST 2020 x86_64
        path       (~/Workspace/Coding/doom_fork/bin/ /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /opt/bin /usr/lib/llvm/10/bin ~/.config/emacs/bin ~/.local/bin ~/bin /usr/libexec/emacs/27.1/x86_64-pc-linux-gnu/)
EMACS   dir        ~/Workspace/Coding/doom_fork/
        version    27.1
        build      Sep 29, 2020
        buildopts  --prefix=/usr --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu --mandir=/usr/share/man --infodir=/usr/share/info --datadir=/usr/share --sysconfdir=/etc --localstatedir=/var/lib --disable-silent-rules --docdir=/usr/share/doc/emacs-27.1-r1 --htmldir=/usr/share/doc/emacs-27.1-r1/html --libdir=/usr/lib64 --program-suffix=-emacs-27 --includedir=/usr/include/emacs-27 --infodir=/usr/share/info/emacs-27 --localstatedir=/var --enable-locallisppath=/etc/emacs:/usr/share/emacs/site-lisp --without-compress-install --without-hesiod --without-pop --with-dumping=pdumper --with-file-notification=inotify --enable-acl --with-dbus --with-modules --without-gameuser --with-libgmp --with-gpm --without-json --without-kerberos --without-kerberos5 --with-lcms2 --with-xml2 --without-mailutils --without-selinux --with-gnutls --without-libsystemd --with-threads --without-wide-int --with-zlib --with-sound=alsa --with-x --without-ns --without-gconf --without-gsettings --without-toolkit-scroll-bars --with-gif --with-jpeg --with-png --with-rsvg --with-tiff --with-xpm --without-imagemagick --with-xft --with-cairo --without-harfbuzz --without-libotf --without-m17n-flt --with-x-toolkit=gtk3 --with-xwidgets 'CFLAGS=-march=native -O2 -pipe' CPPFLAGS= 'LDFLAGS=-Wl,-O1 -Wl,--as-needed'
        features   XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE ZLIB GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS PDUMPER LCMS2 GMP
        traits     (server-running envvar-file)
DOOM    dir        ~/Workspace/dotfiles/.doom.d/
        version    2.0.9
        build      HEAD -> develop, upstream/develop bba035a1a 2020-10-16 23:42:59 -0400
        elc-files  0
        modules    (:completion company helm :ui doom doom-dashboard hl-todo modeline nav-flash ophints (popup +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold (format +onsave) multiple-cursors snippets :emacs (dired +icons) electric undo vc :term vterm :checkers syntax (spell +flyspell +aspell) :tools direnv (eval +overlay) (lookup +docsets) lsp magit pdf :lang data emacs-lisp (javascript +lsp) (latex +cdlatex) markdown (org +roam +noter) (python +lsp) (sh +lsp) (web +lsp) :email mu4e :config literate (default +bindings +smartparens))
        packages   ((f) (org-drill) (org-super-agenda) (org-chef) (org-ref) (org-roam-bibtex))
        unpin      (n/a)
        elpa       (n/a)
```
</details>

Thanks for all the hard work you're putting into this great project... :-)

**Comment by hlissner** [comment]
I cannot reproduce this issue in vanilla Doom with those steps. Are you able [to reproduce this in vanilla doom](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#testing-in-dooms-sandbox).

Make sure Doom is up-to-date when you try.

**Comment by RBckmnn** [comment]
I have been able to reproduce the issue on the latest commit of Doom in the (Doom + modules - your private config)-sandbox with the following steps:

1. Start the sandbox instance
2. Use `SPC u SPC g g` to directly open the magit-status buffer for a repo that has an unstaged change
3. Proceed as above.

I dug a little deeper into the issue and traced it down to the following:

When the magit-status buffer is opened initially, the window has a `quit-restore` parameter as follows:

```
(other
 (#<buffer *doom*> 1 #<marker at 1569 in *doom*> 120)
 #<window 3 on magit: gtd> #<buffer magit: gtd>)
```
After visiting the file and killing the buffer, the window's `quit-restore` parameter changed to:

```
(other
 (#<buffer magit: gtd> 1 #<marker at 127 in magit: gtd> 120)
 #<window 3 on magit: gtd> #<killed buffer>)
```

Now, invoking `+magit/quit` leads to a call of `quit-restore-window`. As fas as I understood the documentation at https://www.gnu.org/software/emacs/manual/html_node/elisp/Quitting-Windows.html#Quitting-Windows the value of the `quit-restore` parameter keeps the magit-status buffer displayed in the window.

There is some additional cleanup code in `+magit/quit`:

```
(defun +magit/quit (&optional kill-buffer)
  "Clean up magit buffers after quitting `magit-status' and refresh version
control in buffers."
  (interactive "P")
  (funcall magit-bury-buffer-function kill-buffer)
  (unless (delq nil
                (mapcar (lambda (win)
                          (with-selected-window win
                            (eq major-mode 'magit-status-mode)))
                        (window-list)))
    (mapc #'+magit--kill-buffer (magit-mode-get-buffers))
    (+magit-mark-stale-buffers-h)))
```

but it is never executed since the initial magit-status buffer is still around.

**Comment by aldanor** [comment]
@hlissner Bumped into this as well in freshly installed doom 2.0.9, Emacs 27.1.

It's not just the status window and the unstaged changes, but any windows that magit spawns this way - for example if you browse through the log and try to view the commits.

E.g., split windows via `SPC w v`, open magit status buffer on the left side via `SPC g g`, go to the log `l l`, choose any commit and press `RET`, this will open commit buffer in the other window. Now close that via magit's `q` and the focus should be back to the magit log buffer – however it's not.

(I wouldn't personally classify this as minor as it makes magit very hard to use if you tend to often open commits for viewing as you have to manually navigate back to magit's buffer every time)

**Comment by aldanor** [comment]
(Apologies, I've misread the original issue - mine is that quitting magit-spawned windows doesn't return you to magit's status buffer which is  a separate one.)
