### ISSUE TITLE
How to turn off the full-link of orgmode headline in minibuffer when point on a headline?

### ISSUE THREAD

**Issue by icezyj** [hlissner/doom-emacs#4112]
when headline full-links of orgmode show,different heights of levels cause the minibuffer jump.
How to turn off, or modifer it?

**Comment by hlissner** [comment]
Enable `:lang org` module. It contains [a fix for "different heights of levels"](https://github.com/hlissner/doom-emacs/blob/develop/modules/lang/org/config.el#L546-L559).
