### ISSUE TITLE
composing message with mu4e does not provide keyboard shutcuts

### ISSUE THREAD

**Issue by ofyildiz** [hlissner/doom-emacs#4114]
**What did you expect to happen?**
When composing a message with mu4e, I expected to be directed to a mu4e:compose frame with all the accompanied keyboard shortcuts (SPC m s for sending, etc.).

**What actually happened?**
I get directed into an org msg frame without keyboard shortcuts.

**Additional details:**
I retraced the problem to the following commit:
https://github.com/hlissner/doom-emacs/commit/dbe09f9b434c40211c3dcb87f53139e540889e65
Reverting this commit, solves the problem for me, but may not be a sufficient solution.

**Comment by ofyildiz** [comment]
It looks like, this issue has already been raised in the discussion around the mu4e module rework, see here:
https://github.com/hlissner/doom-emacs/pull/3971
It looks like this issue will most likely be resolved once the changes are merged.

**Comment by jperras** [comment]
You can [remove the hook](https://github.com/hlissner/doom-emacs/issues/4043#issuecomment-707983761) until then. I ran into the same issue.

**Comment by hlissner** [comment]
#3971 was merged a few days ago, so this can be considered resolved. Thanks for bringing it to my attention!
