### ISSUE TITLE
When all project workspaces have been deleted, the project directory belonging to the last workspace persists

### ISSUE THREAD

**Issue by clayliddell** [hlissner/doom-emacs#4117]
**What did you expect to happen?**
When all project workspaces in the current frame have been deleted, the `main` workspace's directory should be set to the current users home directory.

**What actually happened?**
The directory belonging to the last opened workspace persists. 

**Additional details:**
Private config: https://github.com/clayliddell/DotFiles/tree/master/.doom.d
Screencast of issue: https://imgur.com/a/OTHF31k
\*Messages\* log:
```
Loading /home/clayton/doom-emacs/init.el (source)...
Ignoring ’:ensure t’ in ’dired’ config
Loading /home/clayton/doom-emacs/init.el (source)...done
Doom loaded 215 packages across 44 modules in 0.853s
Switched to ’doom-emacs’
Loading /home/clayton/doom-emacs/.local/cache/recentf...done
No buffers to kill
 [1] main  | Deleted 'doom-emacs' workspace
```

**Steps to reproduce:**
1. Open emacs.
2. Open a new project using projectile (`SPC p p`).
3. Delete the newly created workspace for the project (`SPC TAB d`).
4. Observe that the current workspace's directory is the same as the last opened workspace.

**System information:**
<details><pre>
SYSTEM  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /usr/bin/zsh
        uname      Linux 4.15.18-041518-generic #201804190330 SMP Thu Apr 19 07:34:21 UTC 2018 x86_64
        path       (~/.cargo/bin ~/.cargo/bin ~/.cabal/bin ~/.local/bin /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /usr/games /usr/local/games /snap/bin ~/doom-emacs/bin ~/.cargo/bin ~/Documents/Work/scripts /usr/lib/x86_64-linux-gnu/emacs/26.3/x86_64-linux-gnu/)
EMACS   dir        ~/doom-emacs/
        version    26.3
        build      Dec 24, 2019
        buildopts  --build=x86_64-linux-gnu --prefix=/usr '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' --sysconfdir=/etc --localstatedir=/var --disable-silent-rules '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' --disable-maintainer-mode --disable-dependency-tracking --prefix=/usr --sharedstatedir=/var/lib --program-suffix=26 --with-modules --with-file-notification=inotify --with-mailutils --with-x=yes --with-x-toolkit=gtk3 --with-xwidgets --with-lcms2 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/emacs26-XQGPla/emacs26-26.3~1.git96dd019=. -fstack-protector-strong -Wformat -Werror=format-security -no-pie' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro -no-pie'
        features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD LCMS2
        traits     (server-running chemacs envvar-file)
DOOM    dir        ~/.doom.d/
        version    2.0.9
        build      HEAD -> develop 9929883bf 2020-10-19 01:25:47 -0400
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo indent-guides minimap modeline ophints (popup +defaults) treemacs vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold snippets word-wrap :emacs dired electric undo vc :term vterm :checkers syntax :tools (eval +overlay) lookup lsp magit rgb :lang emacs-lisp (haskell +dante) json javascript markdown org php python rust sh web yaml :config (default +bindings +smartparens))
        packages   (n/a)
        unpin      (n/a)
        elpa       (n/a)
</pre></details>

**Comment by hlissner** [comment]
This is not a bug. If you don't like this behavior tweak `+doom-dashboard-pwd-policy`. See `SPC h v +doom-dashboard-pwd-policy` for documentation.

**Comment by clayliddell** [comment]
@hlissner Apologies. Thanks for this quick response!
