### ISSUE TITLE
Scala lsp format on save

### ISSUE THREAD

**Issue by regadas** [hlissner/doom-emacs#4121]
Hello!

**What did you expect to happen?**
For `scala +lsp` I would expect that `format +onsave` would pick the lsp format capability.

**What actually happened?**
It's using the CLI scalafmt tool.

If I do `SPC c f` it works as expected.

**Additional details:**
https://github.com/regadas/doom.d/

Thanks for this awesome project!

**Comment by regadas** [comment]
I just noticed this #4120 It might be related.

**Comment by systemctl603** [comment]
Yeah, that PR was meant to solve this issue.
Also, this may be a duplicate of #3626

**Comment by hlissner** [comment]
#4120 was merged. Please update and let me know if that has resolved your issue.

**Comment by regadas** [comment]
Hi @hlissner that fixed it! Thanks

@systemctl603 Thanks as well for the PR!
