### ISSUE TITLE
lsp-ui-mode and line-number-mode is not loaded after entering rustic-mode and lsp

### ISSUE THREAD

**Issue by sephiron99** [hlissner/doom-emacs#4124]
**What did you expect to happen?**
When I loaded files like .org, .el and others, `line-number-mode` and its config of `~/.doom.d/config.el` are applied well.
I also use the rust module of doom emacs as use of ide for rust lang.
So I expect `rustic-mode` would show line numbers, and load `lsp-ui-mode` automatically.

**What actually happened?**
Whenever I open a .rs file, `line-number-mode` is loaded as well, but line numbers are not shown. I have to toggle it with `SPC t l`.

Not exactly same as above, whenever I open a .rs file, `lsp-mode` is loaded as well as rustic-mode, but `lsp-ui-mode` is not. I have to load it with `M-x lsp-ui-mode`.
Can I make `lsp-ui-mode` and `line-number-mode` loaded as well when .rs files are opened?

**Additional details:**
 - only `lsp` and `(rust +lsp)` enabled in `~/.doom.d/init.el`
 - No other private config

**Steps to reproduce:**
1. Clean install of Doom Emacs and rust lang environments.
2. only `lsp` and `(rust +lsp)` enabled in `~/.doom.d/init.el`
3. No other private config
4. open a .rs file in a cargo project.

**System information:**
<details><pre>
```
SYSTEM  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /usr/bin/zsh
        uname      Linux 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020 x86_64
        path       (~/.cargo/bin /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /usr/games /usr/local/games /mnt/c/WINDOWS/system32 /mnt/c/WINDOWS /mnt/c/WINDOWS/System32/Wbem /mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/ /mnt/c/WINDOWS/System32/OpenSSH/ /mnt/c/Program Files/Git/cmd /mnt/c/Users/sephi/AppData/Local/Microsoft/WindowsApps /mnt/c/Program Files/Bandizip/ /usr/lib/emacs/26.3/x86_64-linux-gnu/)
EMACS   dir        ~/.emacs.d/
        version    26.3
        build      Mar 26, 2020
        buildopts  --build x86_64-linux-gnu --prefix=/usr --sharedstatedir=/var/lib --libexecdir=/usr/lib --localstatedir=/var/lib --infodir=/usr/share/info --mandir=/usr/share/man --enable-libsystemd --with-pop=yes --enable-locallisppath=/etc/emacs:/usr/local/share/emacs/26.3/site-lisp:/usr/local/share/emacs/site-lisp:/usr/share/emacs/26.3/site-lisp:/usr/share/emacs/site-lisp --with-sound=alsa --without-gconf --with-mailutils --build x86_64-linux-gnu --prefix=/usr --sharedstatedir=/var/lib --libexecdir=/usr/lib --localstatedir=/var/lib --infodir=/usr/share/info --mandir=/usr/share/man --enable-libsystemd --with-pop=yes --enable-locallisppath=/etc/emacs:/usr/local/share/emacs/26.3/site-lisp:/usr/local/share/emacs/site-lisp:/usr/share/emacs/26.3/site-lisp:/usr/share/emacs/site-lisp --with-sound=alsa --without-gconf --with-mailutils --with-x=yes --with-x-toolkit=gtk3 --with-toolkit-scroll-bars 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/emacs-mEZBk7/emacs-26.3+1=. -fstack-protector-strong -Wformat -Werror=format-security -Wall' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro'
        features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS LIBSYSTEMD LCMS2
        traits     (server-running envvar-file)
DOOM    dir        ~/.doom.d/
        version    2.0.9
        build      grafted, HEAD -> develop, origin/develop, origin/HEAD 664937a 2020-10-20 23:25:36 -0400
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline ophints (popup +defaults) vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold snippets :emacs dired electric undo vc :checkers syntax :tools (eval +overlay) lookup lsp magit :lang emacs-lisp markdown org rust sh :config (default +bindings +smartparens))
        packages   (n/a)
        unpin      (n/a)
        elpa       (n/a)
```
</pre></details>

**Comment by hlissner** [comment]
Did you find a solution?

**Comment by sephiron99** [comment]
No, I clo

**Comment by hlissner** [comment]
I cannot reproduce this. `*.rs` files open with line numbers in vanilla Doom fine.

Please check \*Messages\* for errors or warnings (`SPC h e` or `C-h e` to open it).

**Comment by sephiron99** [comment]
> Loading /etc/emacs/site-start.d/00debian.el (source)...done
Doom loaded 145 packages across 31 modules in 1.141s
Quit [5 times]
LSP :: Guessed project root is ~/prj/web-finance-scrapper
File mode specification error: (void-variable read-process-output-max)
LSP :: rls:6804 initialized successfully
Mark set

I did following commands to do clean-install.

1. `$ rm ~/.doom.d ~/.emacs.d -rf`
2. `$ git clone --depth 1 https://github.com/hlissner/doom-emacs ~/.emacs.d`
3. `$ ~/.emacs.d/bin/doom install`
4. `$ vi ~/.doom.d/init.el` and enabled `lsp` `(rust +lsp)`
5. `$ ~/.emacs.d/bin/doom sync`
6. `$ ~/.emacs.d/bin/doom env `
7. `$ emacs`

**Comment by sephiron99** [comment]
All of problems get removed, as I moved to Emacs27. Thank you for your help!

**Comment by hlissner** [comment]
Turns out the cause is that I'm referencing a variable that isn't defined until Emacs 27. As of 1811cae this issue should be resolved for 26 users. Upgrading to 27 will work too. In any case, thanks for bringing it to my attention!
