### ISSUE TITLE
eshell and other default key bindings not present on macos.

### ISSUE THREAD

**Issue by blmhemu** [hlissner/doom-emacs#4125]
**What did you expect to happen?**
SPC o e : Should open eshell
Similarly SPC o p should open side tree.
But it says undefined. I know that i can map them in my private config but it should be default.

**What actually happened?**
Undefined Keybinding.
![image](https://user-images.githubusercontent.com/19410501/96746027-656c4e00-13e4-11eb-95a6-3c25bf0cb42e.png)

**Additional details:**
- It is a new emacs setup.
- Environment : MacOS (Installed using the doom emacs wiki)

**System information:**
![image](https://user-images.githubusercontent.com/19410501/96746372-bbd98c80-13e4-11eb-906a-c32eebb545ae.png)

**Comment by hlissner** [comment]
You forgot [to enable their modules](https://github.com/hlissner/doom-emacs/blob/develop/docs/modules.org).

> SPC o e : Should open eshell

Enable the `:term eshell` module.

> Similarly SPC o p should open side tree.

Enable one of the `:ui treemacs` or `:ui neotree` modules.
