### ISSUE TITLE
cc-mode ENTER behaviour

### ISSUE THREAD

**Issue by azy2** [hlissner/doom-emacs#413]
Hi, I'm very used to electric-pair-mode while coding C++. You're config is slightly different and I don't know emacs-lisp well enough to correct the behavior. Could you help? The behavior I don't like occurs when hitting enter after typing a curly brace. My code might look like this (bar is my cursor):

```
if (cond) |
```

and usually I will hit '{' 'enter' and I want it to do:

```
if (cond) {
    |
}
```

but instead I get:

```
if (cond) {
|}
```

Is there a simple way to change this?

**Comment by robbert-vdh** [comment]
I'm not sure whether this is the correct way to set it up, but [smartparens](https://github.com/Fuco1/smartparens/wiki/Permissions#pre-and-post-action-hooks) can do it for you. I've added this to my config.el:

```elisp
(after! smartparens
  ;; Automatically indent a block when pressing enter inside curly braces,
  ;; square brackets or parentheses
  (dolist (brace '("(" "{" "["))
    (sp-pair brace nil :post-handlers '(:add ("||\n[i]" "RET")))))
```

**Comment by hlissner** [comment]
I don't include this in Doom because it's personal preference. Follow @robbert-vdh's suggestion; it is the correct way to enable this behavior and it is what I use.

**Comment by azy2** [comment]
This works great! Thank you guys.

**Comment by hlissner** [comment]
Just letting you know: as of 57adae5, these settings are built into the private/default module.
