### ISSUE TITLE
Can't find the `rg' binary. 

### ISSUE THREAD

**Issue by k96331** [hlissner/doom-emacs#4131]
Why can't I use `sync'`or `upgrade` to solve this?
I deleted the DOOMDIR and EMACSDIR and tried to reinstall doom emacs.
then I failed to complete the installation.  With some `doom sync` and `doom upgrade', I got this:
> ➜  ~ doom doctor 
> The doctor will see you now...
> 
> > Checking your Emacs version...
> > Checking for Emacs config conflicts...
> > Checking for private config conflicts...
> > Checking for stale elc files...
> > Checking Doom Emacs...
> Note, built-in variable ‘overflow-newline-into-fringe’ not bound
>   ✓ Initialized Doom Emacs 2.0.9
>   ✓ Detected 38 modules
>   ✓ Detected 166 packages
>   > Checking Doom core for irregularities...
>     x Couldn't find the `rg' binary; this a hard dependecy for Doom, file searches may not work at all
>     ! Couldn't find the `fd' binary; project file searches will be slightly slower
>     Found font material-design-icons.ttf
>     Found font weathericons.ttf
>     Found font octicons.ttf
>     Found font fontawesome.ttf
>     Found font file-icons.ttf
>     Found font all-the-icons.ttf
>   > Checking for stale elc files in your DOOMDIR...
>   > Checking your enabled modules...
>     > :emacs dired
>       ! Cannot find gls (GNU ls). This may cause issues with dired
>     > :lang cc
>       ! Couldn't find glslangValidator. GLSL code completion is disabled
>       ! Irony server isn't installed. Run M-x irony-install-server
>       ! Couldn't find the rtag client and/or server programs (rdm rc). Disabling rtags support
>     > :lang markdown
>       ! Couldn't find a markdown compiler, `markdown-preview' won't work
>     > :lang python
>       ! Couldn't find isort. Import sorting will not work.
>       ! Couldn't find pipenv. pipenv support will not work.
>       ! Couldn't find nosetests. Running tests through nose will not work.
>     > :lang sh
>       ! Couldn't find shellcheck. Shell script linting will not work
> 
> There are 1 errors!
> There are 10 warnings!
> ✓ Finished in 3.1746s
> No RTags process running (rdm)...

What should I do?

**Comment by brongulus** [comment]
Install ripgrep via your package manager.
It is mentioned that it's a dependency for doom, https://github.com/hlissner/doom-emacs/#prerequisites

**Comment by k96331** [comment]
It works，thank you！
I forget to install these dependency: https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org
