### ISSUE TITLE
Status bar garbled on mac

### ISSUE THREAD

**Issue by 354651432** [hlissner/doom-emacs#4132]
![image](https://user-images.githubusercontent.com/8469080/96889119-ded57080-14b8-11eb-88b8-ee18c3209589.png)

**Comment by hlissner** [comment]
`M-x all-the-icons-install-fonts` and restart Emacs.

**Comment by 354651432** [comment]
@hlissner  it does not work
![image](https://user-images.githubusercontent.com/8469080/97004298-74333c00-156f-11eb-8ed5-499957eae264.png)
 `fc-cache -f -v` executed and restarted
