### ISSUE TITLE
Haskell +lsp lookup/documentation broken

### ISSUE THREAD

**Issue by jmontag43** [hlissner/doom-emacs#4134]
**What did you expect to happen?**
+lookup/documentation to find the lsp-describe-thing-at-point function and display its results.

**What actually happened?**
it does not find the lsp-describe-thing-at-point function and instead displays a generic "Search on: " buffer.

**Additional details:**
- in the debugger a "No lookup handler selected" message was shown

**Steps to reproduce:**
1. Enable lsp +peek, haskell +lsp
2. Place your cursor over an identifier in Haskell mode
3. Run +lookup/documentation to receive the generic "Search on: " buffer
4. The expected behavior can be seen by running lsp-describe-thing-at-point

**System information:**
<details><pre>
```
SYSTEM  type       darwin
        config     x86_64-apple-darwin18.2.0
        shell      /bin/zsh
        uname      Darwin 19.6.0 Darwin Kernel Version 19.6.0: Sun Jul  5 00:43:10 PDT 2020; root:xnu-6153.141.1~9/RELEASE_X86_64 x86_64
        path       (~/.cabal/bin ~/.ghcup/bin ~/.local/bin ~/bin /usr/local/bin ~/.pyenv/shims /usr/local/bin /usr/bin /bin /usr/sbin /sbin /Applications/Wireshark.app/Contents/MacOS /Applications/Emacs.app/Contents/MacOS/bin-x86_64-10_14 /Applications/Emacs.app/Contents/MacOS/libexec-x86_64-10_14 /Applications/Emacs.app/Contents/MacOS/libexec/)
EMACS   dir        ~/.emacs.d/
        version    26.3
        build      Sep 02, 2019
        buildopts  --with-ns '--enable-locallisppath=/Library/Application Support/Emacs/${version}/site-lisp:/Library/Application Support/Emacs/site-lisp' --with-modules
        features   NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS
        traits     (server-running envvar-file)
DOOM    dir        ~/.doom.d/
        version    2.0.9
        build      grafted, HEAD -> develop, origin/develop, origin/HEAD ff6699e 2020-10-21 12:04:52 -0400
        elc-files  0
        modules    (:completion company (ivy +fuzzy +prescient) :ui doom doom-dashboard doom-quit hl-todo modeline ophints (popup +defaults) treemacs vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold snippets :emacs dired electric undo vc :term eshell vterm :checkers syntax :tools ansible (eval +overlay) lookup (lsp +peek) (magit +forge) terraform :os macos :lang data emacs-lisp (haskell +lsp) json markdown (org +pandoc +present) yaml :config (default +bindings))
        packages   ((ormolu))
        unpin      (n/a)
        elpa       (n/a)
```
</pre></details>

**Comment by wraithm** [comment]
(OP's co-worker here) We tried `lsp-describe-thing-at-point` (via `SPC c l h h`) and that worked just fine. `lsp` is working properly and displays what's expected. It's that `+lookup/documentation` (via `K` over an identifier) does not run `lsp-describe-thing-at-point`. It shows the "online search" stuff instead. We double checked the `lsp` module code, and it's definitely running the `set-lookup-handlers!` stuff, as far as we could tell.

**Comment by jmontag43** [comment]
After noticing how out of date my emacs was, I upgraded it to 27.1, and the issue appears to have been resolved for this version.

**Comment by hlissner** [comment]
Sorry for the late response. I'll be dropping 26.x support from Doom very soon (before or by March), so I will consider this "resolved". There's also a large chance this issue has been resolved since the original report was made. In any case, thanks for bringing it to my attention!
