### ISSUE TITLE
Mouse wheel doesn't scroll with tty module enabled. 

### ISSUE THREAD

**Issue by smsegal** [hlissner/doom-emacs#4137]
**What did you expect to happen?**
...
For the mouse to scroll the window when emacs is opened in the terminal with the `:os tty` module enabled. 

**What actually happened?**
...
Error messages in the minibuffer saying that `<mouse-4>` and `<mouse-5>` are undefined. 
When the `tty` module is disabled, the window does indeed scroll with the mouse wheel. 

**Additional details:**
I added what I thought was a new feature to the `tty` module in  #4136. Looking at the fix I introduced there compared to the existing scroll behaviour when the `tty` module is disabled, I would qualify the mouse scrolling I introduced as feeling qualitatively better. The existing implementation moves the point down and scrolls once the point reaches the edge of the window, whereas my PR causes the scrolling to happen immediately, feeling much more similar to how it does in a graphical frame. 
 
I should mention that this is occuring with the gccemacs-pgtk branch from the AUR, so it is possible that it is an upstream bug. I'll test with emacs27.1 later to see. 

**Steps to reproduce:**
1. Try and scroll with the `tty` module enabled. 
2. Observe no scrolling and the undefined key error messages in the minibuffer. 

**System information:**
<details><pre>
```
SYSTEM  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /usr/bin/zsh
        uname      Linux 5.9.1-zen2-1-zen #1 ZEN SMP PREEMPT Sun, 18 Oct 2020 02:45:20 +0000 x86_64
        path       (~/.poetry/bin ~/.local/bin ~/.config/emacs/bin ~/.pyenv/bin ~/.pyenv/shims /usr/local/bin /usr/local/sbin /usr/bin /usr/sbin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl ~/.cache/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-zpm-zsh-SLASH-colorize/bin /usr/lib/emacs/28.0.50/x86_64-pc-linux-gnu)
EMACS   dir        ~/dotfiles/doom/emacs/
        version    28.0.50
        build      Oct 21, 2020
        buildopts  --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --mandir=/usr/share/man --with-gameuser=:games --with-sound=alsa --with-modules --without-gconf --without-gsettings --with-nativecomp --with-pgtk --with-x-toolkit=gtk3 --without-xaw3d --without-m17n-flt --with-cairo --with-xwidgets --without-compress-install 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -g -fuse-ld=gold' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
        features   JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 PGTK XIM MODULES NATIVE_COMP THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER LCMS2
        traits     (server-running envvar-file)
DOOM    dir        ~/dotfiles/doom/doom/
        version    2.0.9
        build      HEAD -> develop, myfork/develop 42208fa27 2020-10-22 15:01:49 -0400
        elc-files  0
        modules    (:completion (company +childframe) (ivy +icons +fuzzy +prescient) :ui doom doom-dashboard hl-todo hydra minimap modeline nav-flash ophints (popup +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces zen :editor (evil +everywhere) file-templates fold format multiple-cursors snippets word-wrap :emacs (dired +icons) electric (undo +tree) vc :term vterm :checkers syntax (spell +enchant +flyspell) grammar :tools debugger direnv (eval +overlay) (lookup +dictionary +offline +docsets) lsp (magit +forge) pdf taskrunner :os tty :lang (cc +lsp) data emacs-lisp (json +lsp) (latex +latexmk +lsp +fold +cdlatex) (markdown +grip) (org +dragndrop +jupyter +gnuplot +pandoc +pretty) (python +lsp +poetry) (sh +lsp +fish) (yaml +lsp) :config (default +bindings +smartparens))
        packages   ((lorem-ipsum) (yasnippet-snippets) (magit-delta) (sublime-themes) (smart-mode-line) (modus-operandi-theme) (modus-vivendi-theme) (solaire-mode :disable t) (vimrc-mode) (systemd) (imenu-list) (atomic-chrome) (tree-sitter :recipe (:host github :repo ubolonton/emacs-tree-sitter :files (lisp/*.el))) (tree-sitter-langs :recipe (:host github :repo ubolonton/emacs-tree-sitter :files (langs/*.el langs/queries))) (super-save) (visual-fill-column))
        unpin      (n/a)
        elpa       (n/a)
```

</pre></details>

**Comment by Barbarossa93** [comment]
I have this same issue. If you disable `xterm-mouse-mode` then scrolling resumes (while the tty module is enabled). Oddly, placing `(xterm-mouse-mode -1)` in my config.el doesn't work. I have to manually call it every time.

**Comment by hlissner** [comment]
Seems like your terminals don't support the terminal codes xterm-mouse-mode is emitting for scrolling. In that case, disable it:

```elisp
(remove-hook 'tty-setup-hook #'xterm-mouse-mode)
```

Since there's simple way to determine terminal support in Emacs I'll leave it to the user to disable. If you can think of an alternative, I welcome PRs for a more graceful solution. Thanks for bringing it to my attention!
