### ISSUE TITLE
Spellcheck with aspell broken on NixOS 20.09

### ISSUE THREAD

**Issue by loafofpiecrust** [hlissner/doom-emacs#4138]
**What did you expect to happen?**
I'm using the `spell-fu` module for spellchecking. Misspelled words are highlighted in a buffer, and when I try to correct it with `z =`, I should be prompted for potential correction values.

**What actually happened?**
I am not shown potential spellings, instead I get this error:
```
Starting new Ispell process aspell with english dictionary...done
ispell-init-process: Error: /home/snead/dotfiles/emacs/.config/emacs/.local/etc/ispell/english.pws: The language "english" is not known. This is probably because: the file "/nix/store/k464ys45mnr740p28vzcbd7fhn911l2f-aspell-0.60.8/lib/aspell/english.dat" can not be opened for reading.
```
It looks like `aspell` doesn't store its dictionaries there anyway. On NixOS, the dictionary packages store files in their own directories in the nix store.

**Additional details:**
- I'm running NixOS 20.09 and Emacs 28 (native-comp).
-  I've used spell-fu for spellcheck for a couple of months now, and it worked before I upgraded NixOS not long ago.
- I have set the `ispell` binary to be `aspell` instead, and have the `en_US` dictionary installed.

<details><pre>
Debugger entered--Lisp error: (error "Error: /home/snead/dotfiles/emacs/.config/emacs/.l...")
  error("%s" "Error: /home/snead/dotfiles/emacs/.config/emacs/.l...")
  ispell-init-process()
  ispell-buffer-local-words()
  ispell-accept-buffer-local-defs()
  (save-current-buffer (ispell-accept-buffer-local-defs))
  +spell/correct()
  funcall-interactively(+spell/correct)
  call-interactively(+spell/correct nil nil)
  command-execute(+spell/correct)
</pre></details>

**Steps to reproduce:**
1. Move point to a misspelled word in a buffer
2. Invoke `+spell/correct`

**System information:**
<details><pre>
SYSTEM  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /run/current-system/sw/bin/fish
        uname      Linux 5.4.72 #1-NixOS SMP Sat Oct 17 08:11:24 UTC 2020 x86_64
        path       (~/dotfiles/emacs/.config/emacs/bin/ ~/.netlify/helper/bin ~/.config/emacs/bin ~/.go/bin ~/.cargo/bin ~/.npm/bin ~/dotfiles/emacs/.config/emacs/bin/ ~/dotfiles/emacs/.config/emacs/bin/ ~/dotfiles/emacs/.config/emacs/bin/ ~/dotfiles/emacs/.config/emacs/bin/ ~/bin /run/wrappers/bin ~/.nix-profile/bin /etc/profiles/per-user/$USER/bin /nix/var/nix/profiles/default/bin /run/current-system/sw/bin /nix/store/32brvk4wvs0rw342b6a4iilqxqwvzdwk-emacs-gcc-20201015.0/libexec/emacs/28.0.50/x86_64-pc-linux-gnu/)
EMACS   dir        ~/dotfiles/emacs/.config/emacs/
        version    28.0.50
        build      Oct 22, 2020
        buildopts  --prefix=/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-emacs-gcc-20201015.0 --disable-build-details --with-modules --with-x-toolkit=gtk3 --with-xft --with-cairo --with-xwidgets --with-nativecomp CFLAGS=-DMAC_OS_X_VERSION_MAX_ALLOWED=101200
        features   XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND DBUS GSETTINGS GLIB NOTIFY INOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES NATIVE_COMP THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER
        traits     (server-running envvar-file)
DOOM    dir        ~/dotfiles/emacs/.config/doom/
        version    2.0.9
        build      HEAD -> develop adff1aa68 2020-10-22 02:10:59 -0400
        elc-files  0
        modules    (:input chinese :desktop (&user window-manager) :completion (company +childframe) (ivy +childframe +prescient +icons) :ui doom doom-dashboard hl-todo hydra indent-guides ophints (popup +defaults) (ligatures +extra) treemacs unicode vc-gutter window-select workspaces (emoji +github +unicode) :editor (evil +everywhere) file-templates fold (format +onsave) multiple-cursors :emacs (dired +icons +ranger) electric undo vc :term vterm :checkers (syntax +childframe) (spell +aspell +everywhere) :tools direnv editorconfig (eval +overlay) lookup lsp (magit +forge) make pdf terraform :lang (cc +lsp) data emacs-lisp (go +lsp) json (javascript +lsp) kotlin (latex +lsp) ledger lua markdown nix (org +pretty +dragndrop +pomodoro) php (python +lsp) racket rest (rust +lsp) (sh +fish) (swift +lsp) (web +lsp) yaml :email mu4e :app calendar :config (default +bindings +smartparens))
        packages   ((tsc :pin f5fec6dcf3959cd5b9857c887e2425a17e1a54fb :recipe (:host github :repo ubolonton/emacs-tree-sitter :files (core/*.el))) (tree-sitter :pin f5fec6dcf3959cd5b9857c887e2425a17e1a54fb :recipe (:host github :repo ubolonton/emacs-tree-sitter :files (lisp/*.el src Cargo.toml Cargo.lock))) (tree-sitter-langs :pin f5fec6dcf3959cd5b9857c887e2425a17e1a54fb :recipe (:host github :repo ubolonton/emacs-tree-sitter :files (langs/*.el langs/queries))) (theme-changer :pin 61945695a30d678e6a5d47cbe7c8aff59a8c30ea) (ewal) (ewal-doom-themes) (graphql-mode) (polymode) (poly-markdown) (poly-org) (literate-calc-mode) (string-inflection) (evil-owl) (flycheck-inline :recipe (:host github :repo loafofpiecrust/flycheck-inline :branch moving-point)) (flycheck-posframe :disable t) (flycheck-popup-tip :disable t) (org-msg :disable t) (mu4e-alert) (mu4e-send-delay :recipe (:host github :repo cacology/mu4e-send-delay)) (olivetti) (org-ref) (citeproc-org) (transmission :disable t) (exwm-edit) (desktop-environment) (mini-modeline) (anzu) (evil-anzu) (mini-frame :disable t) (mount-mode :recipe (:host github :repo zellerin/mount-mode)) (ivy-posframe) (ivy-avy) (org-cv :recipe (:host gitlab :repo Titan-C/org-cv)) (fcitx :disable t) (solaire-mode :disable t) (bitwarden :recipe (:host github :repo seanfarley/emacs-bitwarden)) (zoom) (highlight-numbers :disable t) (magit-todos) (emms) (pdf-tools :recipe (:no-native-compile t)) (dired-show-readme :recipe (:host gitlab :repo kisaragi-hiu/dired-show-readme)) (pdf-continuous-scroll-mode :recipe (:host github :repo dalanicolai/pdf-continuous-scroll-mode.el)) (oauth2) (spotify :recipe (:host github :repo danielfm/spotify.el)))
        unpin      (n/a)
        elpa       (xelb vterm use-package undo-tree tablist pdf-tools let-alist ivy-fuz ivy fuz exwm cl-generic bind-key)
</pre></details>

**Comment by wakira** [comment]
Have you tried (`aspellWithDicts`? Does that work?

**Comment by pkazmier** [comment]
BTW, I have the same issue on MacOS Catalina. Unfortunately, I cannot confirm if this is a new issue as I just enabled `spell` yesterday using the default `spell-fu` with `aspell`. I'm running emacs-plus@28 as another data point.

**Comment by hlissner** [comment]
I'm afraid I can't reproduce this. I am on NixOS 20.09 and am [using aspell's dictionaries](https://github.com/hlissner/dotfiles/blob/master/modules/editors/emacs.nix#L41-L43) without issue.

**Comment by loafofpiecrust** [comment]
I was not using `aspellWithDicts` before, I have changed my config to use that function but I still get the same error.

**Comment by hlissner** [comment]
You may need to delete the old cache to give it a chance to regenerate them: `rm -rf ~/.emacs.d/.local/etc/spell-fu`

**Comment by loafofpiecrust** [comment]
Okay, problem solved for me!
Relevant piece of Nix config:
```nix
{
  environment.systemPackages = with pkgs; [
    (aspellWithDicts (dicts: with dicts; [ en en-computers en-science ]))
  ];
}
```
And then I had to run (per @hlissner's suggestion)
```sh
rm -rf ~/.config/emacs/.local/etc/ispell
```
Thanks!

**Comment by carlosperezm** [comment]
I am also having the same issue with Ubuntu 20.04

It used to work correctly before, but I am not sure which commit broke the functionality. I will add more information if I find it later.

**System information:**
<details><pre>
```
SYSTEM  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /usr/bin/fish
        uname      Linux 5.4.0-52-generic #57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020 x86_64
        path       (~/.pyenv/plugins/pyenv-virtualenv/shims ~/.pyenv/shims /usr/local/meson/ ~/go/bin /usr/local/go/bin ~/.emacs.d/bin ~/.local/bin ~/.pub-cache/bin ~/flutter/bin /usr/local/clang_10.0.0/bin ~/.pyenv/bin ~/.poetry/bin ~/.fzf/bin /usr/local/meson/ ~/go/bin /usr/local/go/bin ~/.emacs.d/bin ~/.local/bin ~/.pub-cache/bin ~/flutter/bin /usr/local/clang_10.0.0/bin ~/.nix-profile/bin ~/.cargo/bin ~/.local/bin /opt/texbin /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /usr/games /usr/local/games /snap/bin /snap/emacs/current/usr/libexec/emacs/27.1/x86_64-pc-linux-gnu/)
EMACS   dir        ~/.emacs.d/
        version    27.1
        build      Aug 26, 2020
        buildopts  --prefix= --prefix=/snap/emacs/current/usr --with-xwidgets --with-x-toolkit=gtk3 --without-xaw3d --with-modules --with-cairo 'CFLAGS= -isystem/build/emacs/parts/emacs/install/usr/include -O2' 'CPPFLAGS= -isystem/build/emacs/parts/emacs/install/usr/include' 'LDFLAGS= -L/build/emacs/parts/emacs/install/lib -L/build/emacs/parts/emacs/install/usr/lib -L/build/emacs/parts/emacs/install/lib/x86_64-linux-gnu -L/build/emacs/parts/emacs/install/usr/lib/x86_64-linux-gnu'
        features   XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER LCMS2 GMP
        traits     (server-running envvar-file)
DOOM    dir        ~/dotfiles/emacs/.doom.d/
        version    2.0.9
        build      HEAD -> develop fcdd23829 2020-11-01 16:25:38 -0500
        elc-files  0
        modules    (:completion company ivy :ui deft doom doom-dashboard doom-quit (emoji +ascii +github +unicode) fill-column hl-todo hydra modeline nav-flash ophints (popup +all +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces zen :editor (evil +everywhere) file-templates fold format multiple-cursors rotate-text snippets word-wrap :emacs dired electric ibuffer vc undo :term eshell shell :checkers syntax (spell +aspell) grammar :tools (&user biblio) (debugger -lsp) ein (eval +overlay) (lookup +docsets +dictionary) lsp (magit +forge) pdf :lang (cc +lsp) data (dart +lsp +flutter) emacs-lisp (haskell +dante) (javascript +lsp) (json +lsp) (latex +latexmk +cdlatex +lsp) ledger markdown nix (org +dragndrop +hugo +jupyter +journal +pandoc +pomodoro +present +roam +noter) (php +lsp) (python +lsp +conda +pyenv +poetry) (sh +lsp +fish) (web +html +css +lsp +wordpress) (yaml +lsp) :app calendar :config (default +bindings +smartparens))
        packages   ((ox-word :recipe (:host github :repo jkitchin/scimax :files (ox-word.el) :nonrecursive t)) (nov :recipe (:host github :repo wasamasa/nov.el)) (emacs-gif-screencast :recipe (:host gitlab :repo ambrevar/emacs-gif-screencast)) (citeproc-org) (git-auto-commit-mode))
        unpin      (n/a)
        elpa       (n/a)
```
</pre></details>

**Comment by lunik1** [comment]
I am having the same issue with the `en_GB` dictionary, for me it is caused by adding words to my custom dictionary with `zg`.

**Comment by TheGhostHuCodes** [comment]
@lunik1, @pkazmier, I had the same issue on macOS Catalina 10.15.5, emacs 27.1

The error said that `/usr/local/Cellar/aspell/0.60.8/lib/aspell-0.60/english.dat` can not be opened for reading, but for me the file doesn't even exist. A file that does exist is `/usr/local/Cellar/aspell/0.60.8/lib/aspell-0.60/en.dat`. I then took a look at my `~/.emacs.d/.local/etc/ispell/english.pws` file and noticed that the header shows:

```
personal_ws-1.1 english 2
```

I replaced it with

```
personal_ws-1.1 en 2
```

and the spell check suggestions show up again.

**Comment by pkazmier** [comment]
@TheGhostHuCodes  Thanks! This fixed it for me too!

**Comment by carlosperezm** [comment]
@TheGhostHuCodes solution also woked for me, thanks!

**Comment by TheGhostHuCodes** [comment]
Hi @hlissner, 

First of all thanks for your work on doom-emacs I'm really enjoying using it.

Seems like the issue that @carlosperezm, @pkazmier, and I ran into is slightly different from NixOS issue described in this issue. Should I open a new issue to track it?

We've figured out a [hack around the problem](https://github.com/hlissner/doom-emacs/issues/4138#issuecomment-725187904), but I don't know how to debug this issue further. Sorry, I'm fairly new to doom-emacs and the emacs ecosystem in general.

**Comment by slackorama** [comment]
https://github.com/hlissner/doom-emacs/blob/develop/modules/checkers/spell/config.el#L36

doom sets the `ispell-dictionary` to "english" but all the files needed for english with aspell use `en` (at least on Ubuntu). I added:

    (setq ispell-dictionary "en")

to my `config.el` to fix it. I guess this is the same thing that @TheGhostHuCodes did essentially.

**Comment by lunik1** [comment]
I set `ispell-dictionary` to `"en_GB"` in my config but still have the issue.

**Comment by miguelmartin75** [comment]
> `(setq ispell-dictionary "en")`

same issue on macos
