### ISSUE TITLE
Magit - Opening org-mode files

### ISSUE THREAD

**Issue by benmezger** [hlissner/doom-emacs#4149]
**What did you expect to happen?**
Open magit fast and without trying to open (?) my orgmode files

**What actually happened?**
When opening Emacs for the first time, and running `magit-status` it is very slow at the first time. It seems that `magit` is trying to open up my `orgmode` files before loading. I am not sure if this is strictly a Emacs doom issue. 

**Additional details:**
- https://github.com/benmezger/dotfiles/tree/main/dot_doom.d
- Include any warnings or errors logged to \*Messages\* (use `M-x
  view-echo-area-messages` to see it).

The following is `*Messages*` and setup.hugo is a orgmode `SETUPFILE` I have in all my org files. 
```
C-x g is undefined [2 times]
Spell-fu generating words: "words_english.txt"
Spell-fu generating cache: "words_english.el.data"
Unable to read file "/Users/seds/hugo.setup" [196 times]
Running /usr/local/bin/git commit --
Diffing changes to be committed (C-g to abort diffing)
```

**Steps to reproduce:**
1. Close emacs and reopen it
2. Go to a git repository project
3. Run `magit-status` or `C-g`

**System information:**
<details><pre>
SYSTEM  type       darwin
        config     x86_64-apple-darwin19.6.0
        shell      /bin/zsh
        uname      Darwin 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64
        path       (~/.emacs.d/bin/ /usr/local/bin /usr/bin /bin /usr/sbin /sbin /usr/local/Cellar/emacs-plus@28/28.0.50/libexec/emacs/28.0.50/x86_64-apple-darwin19.6.0/)
EMACS   dir        ~/.emacs.d/
        version    28.0.50
        build      Oct 24, 2020
        buildopts  --disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus@28/28.0.50/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus@28/28.0.50 --with-xml2 --with-gnutls --without-dbus --with-imagemagick --with-modules --with-rsvg --with-ns --disable-ns-self-contained
        features   JPEG TIFF PNG RSVG IMAGEMAGICK GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS JSON PDUMPER LCMS2
        traits     (server-running envvar-file)
DOOM    dir        ~/.doom.d/
        version    2.0.9
        build      HEAD -> refs/heads/develop, refs/remotes/origin/develop, refs/remotes/origin/HEAD adff1aa68 2020-10-22 02:10:59 -0400
        elc-files  0
        modules    (:completion (company +auto +tng) (ivy +fuzzy) :ui deft doom doom-quit fill-column hl-todo modeline nav-flash ophints (popup +all +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates (format +onsave) rotate-text snippets :emacs (undo +tree) dired electric ibuffer vc :term eshell :checkers spell grammar :tools debugger editorconfig (eval +overlay) (lookup +docsets) lsp (magit +forge) make terraform :lang (cc +lsp) (yaml +lsp) data emacs-lisp (go +lsp) latex markdown (org +roam +hugo +journal +gnuplot +pancoc +dragndrop +journal) (python +lsp +pyenv) rest (sh +lsp) :email (mu4e +gmail) :app (rss +org) :config (default +bindings +smartparens) :os macos)
        packages   ((pyenv-mode-auto) (wakatime-mode) (ob-mermaid) (org-roam-server) (yasnippet-snippets))
        unpin      (n/a)
        elpa       (n/a)
</pre></details>

**Comment by hlissner** [comment]
[Magit loads org](https://github.com/emacs-straight/org-mode/blob/master/lisp/org.el#L92-L96), but Doom doesn't load any org files when org is loaded, so I can only assume this is a local configuration issue. Please check your config.
