### ISSUE TITLE
Italic font in Org Mode works on terminal but not on GUI

### ISSUE THREAD

**Issue by lytex** [hlissner/doom-emacs#4150]
**What did you expect to happen?**
Inside an org file, `/text in italics/` should be rendered as _/text in italics/_

**What actually happened?**
Italic font doesn't work on emacs GUI (left on the image below), even though on the terminal the italics work fine (right)
![image](https://user-images.githubusercontent.com/32138262/97102701-050d3300-16a8-11eb-912e-677623aa17a5.png)

I suspect emacs is using escape characters like this `echo "\e[3mitalics\e[m"` which prints the text in italics when I run it on my terminal

What is the "doom way" to get the italics working on GUI as well? Is a bug or a misconfiguration?

[My doom config](https://github.com/lytex/doom.d)

**Comment by tecosaur** [comment]
Have you checked that the font used in the GUI actually has italics? I know that not all mono fonts do.

**Comment by lytex** [comment]
Yes, I know it has no italics, so that it would have to be generated like that of the terminal. The font used in the terminal is exactly the same as the one used on the GUI.

There is no way to display italic on GUI unless the font already has it?
