### ISSUE TITLE
"C-o" / better-jumper-jump-backward cycles between the last two jumps

### ISSUE THREAD

**Issue by Manu-Tran** [hlissner/doom-emacs#4155]
**What did you expect to happen?**
better-jumper-jump-backward to navigate backward in the jump list

**What actually happened?**
Jumps to the previous jump (as intended) but the when called again, returns to the first location. (And then cycles again)

**Steps to reproduce:**
1. Open a project
2. Open 3 files
3. Call "better-jumper-jump-backward" twice -> Should return to the first buffer

**System information:**
<details><pre>
((system
  (type . darwin)
  (config . "x86_64-apple-darwin19.5.0")
  (shell . "/bin/zsh")
  (uname . "Darwin 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64")
  (path "/usr/local/opt/coreutils/libexec/gnubin" "/snap/bin" "~/Scripts" "~/snap" "~/bin" "/usr/local/bin" "~/.local/bin" "~/opt/miniconda3/envs/torch/bin" "~/opt/miniconda3/condabin" "/usr/local/Cellar/emacs/27.1/libexec/emacs/27.1/x86_64-apple-darwin19.5.0"))
 (emacs
  (dir . "~/.emacs.d/")
  (version . "27.1")
  (build . "Sep 04, 2020")
  (buildopts . "--disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs/27.1/share/info/emacs --prefix=/usr/local/Cellar/emacs/27.1 --with-gnutls --without-x --with-xml2 --without-dbus --with-modules --without-ns --without-imagemagick")
  (features . "NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB MODULES THREADS JSON PDUMPER GMP")
  (traits batch server-running envvar-file))
 (doom
  (dir . "~/my-config/doom.d/")
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD 1456108d 2020-09-10 18:03:32 -0400")
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard doom-quit hl-todo indent-guides modeline nav-flash ophints (popup +all +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold (format +onsave) multiple-cursors rotate-text snippets word-wrap :emacs dired electric ibuffer undo vc :term eshell :checkers syntax spell :tools debugger docker ein (eval +overlay) lookup (lsp +peek) magit make :os macos :lang cc data emacs-lisp (go +lsp) (java +meghanada) latex markdown (org +dragndrop +jupyter +pomodoro +present) (python +conda +lsp) sh yaml :email (mu4e +gmail) :app calendar :config (default +bindings +smartparens))
  (packages (org-noter) (clang-format) (spotify) (org-super-agenda) (walkman) (evil-replace-with-register) (company-lsp) (fill-column-indicator) (jupyter) (ob-async) (ob-ipython))
  (unpin "n/a")
  (elpa "zmq" "websocket" "simple-httpd" "jupyter")))
</pre></details>

**Comment by gilbertw1** [comment]
This is fixed in the most up to date version of `better-jumper`. It was caused by an update to `evil` which modified it's jumping behavior. If you update your packages the problem should go away.

**Comment by Manu-Tran** [comment]
Great thanks ! I should have upgraded doom before raising an issue. I'll think about that next time !
