### ISSUE TITLE
LSP code formating has wrong indentation

### ISSUE THREAD

**Issue by loafofpiecrust** [hlissner/doom-emacs#4158]
**What did you expect to happen?**
I have the `(format +onsave)` module enabled and `lsp` enabled for `typescript`. For a particular project, I have an `.editorconfig` file that defines `tab-width` as `2`. I expect saving a `.ts` file to then auto-format with an indent width of 2 spaces.

**What actually happened?**
Now that formatting uses LSP when available, the LSP formatter ignores the value of `tab-width` set by `editorconfig` and the `"tabWidth": 2` definition in my `prettier` config. It gets formatted with an indent size of 4 spaces instead. If I call `format-all-buffer` manually, it does what I expect.

**Steps to reproduce:**
1. Open a `.ts` or `.js` file in a project with an `.editorconfig` where `indent_size = 2`
2. Modify the buffer
3. Save the buffer

**System information:**
<details><pre>
SYSTEM  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /run/current-system/sw/bin/fish
        uname      Linux 5.4.72 #1-NixOS SMP Sat Oct 17 08:11:24 UTC 2020 x86_64
        path       (~/.netlify/helper/bin ~/.config/emacs/bin ~/.go/bin ~/.cargo/bin ~/.npm/bin ~/dotfiles/emacs/.config/emacs/bin/ ~/dotfiles/emacs/.config/emacs/bin/ ~/dotfiles/emacs/.config/emacs/bin/ ~/dotfiles/emacs/.config/emacs/bin/ ~/dotfiles/emacs/.config/emacs/bin/ ~/bin /run/wrappers/bin ~/.nix-profile/bin /etc/profiles/per-user/$USER/bin /nix/var/nix/profiles/default/bin /run/current-system/sw/bin /nix/store/8ks6a6y5jj06sp64znw611zzsr2nwrk6-emacs-gcc-20201025.0/libexec/emacs/28.0.50/x86_64-pc-linux-gnu/)
EMACS   dir        ~/dotfiles/emacs/.config/emacs/
        version    28.0.50
        build      Oct 26, 2020
        buildopts  --prefix=/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-emacs-gcc-20201025.0 --disable-build-details --with-modules --with-x-toolkit=gtk3 --with-xft --with-cairo --with-xwidgets --with-nativecomp CFLAGS=-DMAC_OS_X_VERSION_MAX_ALLOWED=101200
        features   XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND DBUS GSETTINGS GLIB NOTIFY INOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES NATIVE_COMP THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER
        traits     (server-running envvar-file)
DOOM    dir        ~/dotfiles/emacs/.config/doom/
        version    2.0.9
        build      HEAD -> develop adff1aa68 2020-10-22 02:10:59 -0400
        elc-files  0
        modules    (:input chinese :desktop (&user window-manager) :completion (company +childframe) (ivy +childframe +prescient +icons) :ui doom doom-dashboard hl-todo hydra ophints (popup +defaults) (ligatures +extra) treemacs unicode vc-gutter window-select workspaces (emoji +github +unicode) :editor (evil +everywhere) file-templates fold (format +onsave) multiple-cursors snippets :emacs (dired +icons +ranger) electric undo vc :term vterm :checkers (syntax +childframe) (spell +aspell +everywhere) :tools direnv editorconfig (eval +overlay) lookup lsp (magit +forge) make pdf terraform :lang (cc +lsp) data emacs-lisp (go +lsp) json (javascript +lsp) kotlin (latex +lsp) ledger lua markdown nix (org +pretty +dragndrop +pomodoro) php (python +lsp) racket rest (rust +lsp) (sh +fish) (swift +lsp) (web +lsp) yaml :email mu4e :app calendar :config (default +bindings))
        packages   ((tsc :pin f5fec6dcf3959cd5b9857c887e2425a17e1a54fb :recipe (:host github :repo ubolonton/emacs-tree-sitter :files (core/*.el))) (tree-sitter :pin f5fec6dcf3959cd5b9857c887e2425a17e1a54fb :recipe (:host github :repo ubolonton/emacs-tree-sitter :files (lisp/*.el src Cargo.toml Cargo.lock))) (tree-sitter-langs :pin f5fec6dcf3959cd5b9857c887e2425a17e1a54fb :recipe (:host github :repo ubolonton/emacs-tree-sitter :files (langs/*.el langs/queries))) (theme-changer :pin 61945695a30d678e6a5d47cbe7c8aff59a8c30ea) (ewal) (ewal-doom-themes) (ewal-evil-cursors) (string-inflection) (evil-owl) (olivetti) (graphql-mode) (polymode) (poly-markdown) (poly-org) (literate-calc-mode) (flycheck-inline) (flycheck-posframe :disable t) (flycheck-popup-tip :disable t) (org-msg :disable t) (mu4e-alert) (mu4e-send-delay :recipe (:host github :repo cacology/mu4e-send-delay)) (org-ref) (citeproc-org) (transmission :disable t) (desktop-environment) (mini-modeline) (anzu) (evil-anzu) (mini-frame :disable t) (mount-mode :disable t :recipe (:host github :repo zellerin/mount-mode)) (ivy-posframe) (ivy-avy) (org-cv :recipe (:host gitlab :repo Titan-C/org-cv)) (fcitx :disable t) (solaire-mode :disable t) (bitwarden :recipe (:host github :repo seanfarley/emacs-bitwarden)) (zoom) (highlight-numbers :disable t) (pdf-tools :recipe (:no-native-compile t)) (dired-show-readme :recipe (:host gitlab :repo kisaragi-hiu/dired-show-readme)) (pdf-continuous-scroll-mode :recipe (:host github :repo dalanicolai/pdf-continuous-scroll-mode.el)) (oauth2) (spotify :recipe (:host github :repo danielfm/spotify.el)) (calibredb) (ace-window :recipe (:host github :repo loafofpiecrust/ace-window :branch posframe)))
        unpin      (n/a)
        elpa       (xelb vterm use-package undo-tree tablist pdf-tools let-alist ivy-fuz ivy fuz exwm cl-generic bind-key)
</pre></details>

**Comment by innerout** [comment]
As the [format](https://github.com/hlissner/doom-emacs/tree/develop/modules/editor/format#disabling-the-lsp-formatter) module documentation says, you can disable the LSP formatter globally or in one mode that you want.

To disable this behavior universally, use: `(setq +format-with-lsp nil)`
To disable this behavior in one mode: `(setq-hook! 'python-mode-hook +format-with-lsp nil)`

**Comment by loafofpiecrust** [comment]
I've now disabled LSP formatting for those problematic modes, but this still seems like an issue. Should I make one upstream at `lsp-mode`? I know that `lsp-mode` sends the value of `tab-width` to the language server, so I guess the TS server isn't respecting it.

**Comment by innerout** [comment]
Well I would suggest joining the gitter channel of `lsp-mode` and talk with the maintainers. They will tell you from there what you should do.

**Comment by sagittaros** [comment]
@loafofpiecrust I had the same issue, fixed it by adding these in my `config.el`

```elisp
;; for .ts, i use prettier 
(setq-hook! 'typescript-mode-hook +format-with-lsp nil)

;; for .tsx, i use lsp for formatting, so this is not needed
;; (setq-hook! 'typescript-tsx-mode-hook +format-with-lsp nil)

```

Before adding, `+format/buffer` would complain something like 'no formatting changes'. Now, it should say "Already formatted

**Comment by sagittaros** [comment]
Nowadays, I no longer use prettier but instead relying on lsp formatter.

You can create `tsfmt.json` with this content:
```
{
  "tabSize": 2,
  "indentSize": 2,
  "convertTabsToSpaces": true
}
```

See [here](https://github.com/vvakame/typescript-formatter)
