### ISSUE TITLE
project switching display bug

### ISSUE THREAD

**Issue by masukomi** [hlissner/doom-emacs#4159]
apologies if this isn't actually doom's fault. Not sure where the responsible code lies.

setup: 
I have splits I want to switch to a different project in one of them. 

```
SPACE p p
```
(default binding) 

**What did you expect to happen?**

I _expected_ the picker to a) only appear in the currently active split b) only replace the contents of the currently active split.

**What actually happened?**

The full window is taken over (doom default page on top and picker on bottom)  and after choosing a file the current full window is replaced with whatever file i chose. This appears to be a new workspace as indicated by `SPACE TAB TAB`  (default binding)

**Additional details:**
- Include a link to your private config: [my .doom.d directory](https://github.com/masukomi/masuconfigs/tree/master/.doom.d)

<details><pre>
If an error message is involved include a backtrace of it.

How to acquire a backtrace:
https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#how-to-extract-a-backtrace-from-an-error
</pre></details>

**Steps to reproduce:**
1. edit a file. 
2. create a split (vertical or horizontal, doesn't matter)
3. `SPACE p p` to a different project and choose a file

**System information:**
<details>

```
emacs   version    27.1
        features   RSVG IMAGEMAGICK GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS JSON PDUMPER LCMS2 GMP
        build      Aug 27, 2020
        buildopts  (--disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus@27/27.1/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus@27/27.1 --with-xml2 --with-gnutls --without-dbus --with-imagemagick --with-modules --with-rsvg --with-ns --disable-ns-self-contained)
        windowsys  ns
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> masukomi, origin/masukomi 2b43ce6c9 2020-09-21 15:36:04 -0400
        dir        ~/.doom.d/
system  type       darwin
        config     x86_64-apple-darwin19.5.0
        shell      /usr/local/bin/fish
        uname      Darwin 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64
        path       (/usr/local/opt/openssl@1.1/bin/ ~/.rbenv/shims/ ./ ~/bin/ ~/bin/git-scripts/ /usr/local/bin/ ~/perl5/perlbrew/bin/ /usr/local/bin/ /usr/bin/ /bin/ /usr/sbin/ /sbin/ /usr/local/MacGPG2/bin/ /usr/local/Cellar/node/13.6.0/bin/ /Applications/ /usr/local/opt/coreutils/libexec/gnubin/ ~/.iterm2/ ~/Applications/ ~/workspace/gpup/ ~/workspace/git_accessories/ ~/workspace/gocode/bin/ ~/.cargo/bin/ ~/.local/bin/ /usr/local/Cellar/chicken/5.0.0/bin/ /Applications/Racket v7.7/bin/ /usr/local/opt/go/libexec/bin/ /Applications/Racket v7.7/bin/ /usr/local/Cellar/emacs-plus@27/27.1/libexec/emacs/27.1/x86_64-apple-darwin19.5.0/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company (ivy +fuzzy +prescient) :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold multiple-cursors rotate-text snippets :emacs dired electric ibuffer vc :tools (eval +overlay) flycheck (lookup +docsets) magit :lang crystal data elixir emacs-lisp go javascript markdown (org +dragndrop +present) racket ruby rust scheme sh :config (default +bindings +smartparens))
        packages   (darktooth-theme ruby-hash-syntax nlinum-relative buffer-move)
        elpa       (rainbow-mode powerline nlinum-relative nlinum centaur-tabs)
```
</details>

**Comment by hlissner** [comment]
The workspaces module is configured to create a new workspace when you switch projects like that. 

1. If you only want to open a file in another project, use `SPC p F`. Lets you open a file from an arbitrary project in the current window.
2. If you never want `SPC p p` to create a new workspace, then add `(setq +workspaces-on-switch-project-behavior nil)` (see `SPC h v +workspaces-on-switch-project-behavior` for an explanation of this variable).

Hope that helps!
