### ISSUE TITLE
How do I set default font to some size?

### ISSUE THREAD

**Issue by gazedash** [hlissner/doom-emacs#4161]
This is not covered in docs, :size doesn't work without specifying the specific font.
I could use "Zoom" mode, it works for me, how do I set it in config to be applied on start up?
How to syntax highlight? 

":syntax on" doesn't work

P.S. Thanks for great effort

**Comment by hlissner** [comment]
> :size doesn't work without specifying the specific font.

Then specify the font family.

```elisp
(setq doom-font (font-spec :family "monospace" :size 20))
```

`doom-big-font-mode` isn't meant to be used at startup, but if you must: `(add-hook 'window-setup-hook #'doom-big-font-mode)`

**Comment by gazedash** [comment]
@hlissner why not, though? It's not too uncommon to give a talk and switch between terminal and editor

Thx tho
