### ISSUE TITLE
Error in private config: config.el, (void-variable ￼)

### ISSUE THREAD

**Issue by DoubleClick7** [hlissner/doom-emacs#4163]
```
Warning (initialization): An error occurred while loading ‘/home/kon5oul/.emacs.d/init.el’:

Error in private config: config.el, (void-variable ￼)
```

This is what I get when I start emacs. I am using the feature/native-comp branch of emacs 28.

How do I troubleshoot?

**Comment by hlissner** [comment]
The error is occurring in your `~/.doom.d/config.el`. Your only bet is to check it for weird characters. Maybe you're trying to load an encrypted file from your config?

**Comment by DoubleClick7** [comment]
https://pastebin.com/5XqkEiet

**Comment by innerout** [comment]
@DoubleClick7 It seems line 45 has a special character can you delete that line and try again?

**Comment by DoubleClick7** [comment]
@innerout That was the issue, thanks!!
