### ISSUE TITLE
Treemacs stopped showing icons after the very first load

### ISSUE THREAD

**Issue by Ivanknmk** [hlissner/doom-emacs#4167]
**What did you expect to happen?**
I installed treemacs and the first time I loaded it, it did it great. Icons where there and life was beautiful. 

**What actually happened?**
After the second and subsequent loads treemacs stopped showing icons.
![Screen Shot 2020-10-27 at 11 37 55](https://user-images.githubusercontent.com/1672248/97340000-df6b5f80-1848-11eb-9a4a-8cf677c7eee3.png)

**Additional details:**
- No custom configs are being loaded.
- Echo area is empty.
- This is probably not helpful but it's my own noob ability to know what's useful or not.

**Steps to reproduce:**
1. Start with a fresh doom emacs install.
2. Open treemacs
3. See treemacs but no fancy icons.

**System information:**
<details><pre>
```
SYSTEM  type       darwin
        config     x86_64-apple-darwin19.6.0
        shell      /bin/zsh
        uname      Darwin 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64
        path       (/usr/local/php5/bin ~/.local/bin /usr/local/sbin ~/.pyenv/shims ~/.cargo/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /Applications/Wireshark.app/Contents/MacOS /usr/local/Cellar/emacs-plus@27/27.1/libexec/emacs/27.1/x86_64-apple-darwin19.6.0/)
EMACS   dir        ~/.emacs.d/
        version    27.1
        build      Aug 22, 2020
        buildopts  --disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus@27/27.1/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus@27/27.1 --with-xml2 --with-gnutls --without-dbus --without-imagemagick --with-json --with-modules --with-rsvg --with-xwidgets --with-ns --disable-ns-self-contained
        features   RSVG GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS XWIDGETS JSON PDUMPER LCMS2 GMP
        traits     (server-running envvar-file)
DOOM    dir        ~/.doom.d/
        version    2.0.9
        build      HEAD -> develop fe37a590c 2020-10-26 05:52:30 -0400
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo ligatures modeline nav-flash ophints (popup +defaults) treemacs vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold snippets :emacs dired electric undo vc :checkers syntax :tools (eval +overlay) lookup lsp magit :os macos :lang emacs-lisp json javascript markdown org php (python +lsp) rust sh web :config (default +bindings +smartparens))
        packages   (n/a)
        unpin      (n/a)
        elpa       (n/a)
```
</pre></details>

**Comment by destroyer449** [comment]
I know that you can instead you neotree and then enable a flag that forces fancy icons for everything. If you comment treemacs and init.el and uncomment neotree, doom will automatically reassign keybinding to use neotree. I would recommend doing this as neotree seems faster and is easier to configure.

**Comment by hlissner** [comment]
`(setq doom-themes-treemacs-theme "doom-colors")` for a per-filetype icon theme.

`(remove-hook 'doom-load-theme-hook #'doom-themes-treemacs-config)` to turn off all of Doom's icon modifications (default treemacs icons).
