### ISSUE TITLE
Golang autocomplete not working - LSP Error from language server: no packages

### ISSUE THREAD

**Issue by surendrand** [hlissner/doom-emacs#4168]
**What did you expect to happen?**
Golang autocomplete to work

**What actually happened?**
GoLang autocomplete stopped working

Getting following error when I try to open any go file.

`LSP :: Error from the Language Server: no packages (Unknown error)

**Additional details:**
log from lsp-log shows following issues

```
2020/10/28 00:27:23 DocumentSymbols failed: getting file for DocumentSymbols: no packages
	URI=file:////Users/user-name/src/main.go

2020/10/28 00:27:23 failed to compute document links: no packages
	URI=file:////Users/user-name/src/main.go

```

autocomplete was working perfectly but stopped working, No changes done to .doom.d configs, except for brew update which updated golang version 1.15.3

`my doom info`

```
SYSTEM  type       darwin
        config     x86_64-apple-darwin18.7.0
        shell      /usr/local/bin/bash
        uname      Darwin 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64
        path       (~/go/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /Library/Apple/usr/bin ~/flutter/bin ~/.emacs.d/bin /Applications/Emacs.app/Contents/MacOS/libexec/)
EMACS   dir        ~/.emacs.d/
        version    27.1
        build      Aug 12, 2020
        buildopts  --with-ns '--enable-locallisppath=/Library/Application Support/Emacs/${version}/site-lisp:/Library/Application Support/Emacs/site-lisp' --with-modules
        features   NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS JSON PDUMPER
        traits     (server-running envvar-file)
DOOM    dir        ~/.doom.d/
        version    2.0.9
        build      grafted, HEAD -> develop, origin/develop, origin/HEAD adff1aa 2020-10-22 02:10:59 -0400
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo nav-flash ophints (popup +defaults) vc-gutter vi-tilde-fringe workspaces :editor file-templates fold snippets word-wrap :emacs dired electric undo vc :term eshell :checkers syntax :tools editorconfig (eval +overlay) lookup lsp magit :os macos :lang emacs-lisp (go +lsp) json markdown org python sh yaml :config (default +bindings +smartparens))
        packages   ((gotest) (zenburn-theme) (guru-mode) (telephone-line))
        unpin      (n/a)
        elpa       (n/a)
```

**Comment by af-yamada** [comment]
When I start command-line emacs with the -nw option on the directory with a go.mod file, the gopls works.
When i start GUI emacs without the -nw option on the directory with a go.mod file, the gopls also works.

But when I start GUI emacs from the dock of MacOS, then the gopls doesn't work.
So it looks some path problems, I guess.

**Comment by hlissner** [comment]
> When I start command-line emacs with the -nw option on the directory with a go.mod file, the gopls works.
When i start GUI emacs without the -nw option on the directory with a go.mod file, the gopls also works.

@af-yamada This was fixed some time ago. Please update doom by running `doom upgrade`.

**Comment by hlissner** [comment]
@surendrand Please do not ignore the issue template. It asks you to include your `M-x doom/info`. There is very little I can determine about your issue without it. Please edit your original post and include it.

Also, please make sure Doom is up-to-date.

**Comment by surendrand** [comment]
@hlissner updated my with `M-x doom/info`

**Comment by surendrand** [comment]
@hlissner 
I did a` doom upgrade` and it resolved my issue. 
Thank you.
