### ISSUE TITLE
native-comp with vterm module on freezes emacs

### ISSUE THREAD

**Issue by innerout** [hlissner/doom-emacs#4169]
**What did you expect to happen?**
Expected to doom upgrade / build my configuration.

**What actually happened?**
The with-editor plugin triggers the vterm-module to be built, vterm asks the user if it should be built and because the question is not accessible to the user emacs hangs indefinitely.

**Additional details:**
- Include a link to your private config [my confiig](https://github.com/innerout/Emacs/tree/master/.doom.d)

**Steps to reproduce:**
1. Activate vterm in init.el.
2. Use native-comp branch.
3. Run doom build/upgrade.

**System information:**
<details><pre>
SYSTEM  type       gnu/linux
	config     x86_64-pc-linux-gnu
	shell      /usr/bin/zsh
	uname      Linux 5.9.1-zen2-1-zen #1 ZEN SMP PREEMPT Sun, 18 Oct 2020 02:45:20 +0000 x86_64
	path       (~/.cargo/bin /opt/draw.io ~/.local/bin /other/things/in/path /usr/local/bin /usr/local/sbin /usr/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /var/lib/snapd/snap/bin ~/.emacs.d/bin/ /usr/lib/emacs/28.0.50/x86_64-pc-linux-gnu)
EMACS   dir        ~/.emacs.d/
	version    28.0.50
	build      Oct 27, 2020
	buildopts  --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --mandir=/usr/share/man --with-gameuser=:games --with-sound=alsa --with-modules --without-gconf --without-gsettings --with-nativecomp --with-x-toolkit=gtk3 --without-xaw3d --without-m17n-flt --with-cairo --without-compress-install 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -g -fuse-ld=gold' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
	features   XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES NATIVE_COMP THREADS LIBSYSTEMD JSON PDUMPER LCMS2
	traits     (batch server-running envvar-file)
DOOM    dir        ~/.doom.d/
	version    2.0.9
	build      HEAD -> develop fe37a590c 2020-10-26 05:52:30 -0400
	elc-files  0
	modules    (:completion (company +childframe) (ivy +fuzzy +childframe +icons) :ui doom doom-dashboard doom-quit (emoji +github +unicode) hl-todo indent-guides modeline nav-flash ophints (popup +all +defaults) unicode vc-gutter vi-tilde-fringe workspaces :editor file-templates fold multiple-cursors snippets word-wrap :emacs (dired +icons) electric undo vc :checkers syntax (spell +flyspell) grammar :tools (debugger +lsp) docker (eval +overlay) lookup (lsp +peek) magit pdf :os tty :lang (cc +lsp) data emacs-lisp (latex +lsp) (markdown +grip) (org +attach +babel +capture +export) (python +lsp +pyright) (scala +lsp) (sh +lsp) (yaml +lsp) :email (mu4e +gmail) :config (default +bindings +smartparens))
	packages   ((drag-stuff :disable t) (mu4e-maildirs-extension) (mu4e-alert) (color-identifiers-mode) (cmake-font-lock) (eldoc-cmake) (gitconfig-mode) (gitignore-mode) (goto-addr) (goto-line-preview) (flycheck-clang-tidy) (whole-line-or-region) (gitlab-ci-mode) (gitlab-ci-mode-flycheck) (beacon) (i3wm-config-mode) (clang-format) (spacemacs-theme))
	unpin      (n/a)
	elpa       (n/a)
</pre></details>

**Comment by DoubleClick7** [comment]
Something similar happens to me. When I run `doom sync && doom build`, it asks for building vterm-module. It successfully compiles but a bit after that throws a build error. Also, on opening [emacs](https://github.com/hlissner/doom-emacs/issues/4171), this message is shown.

**Comment by icmor** [comment]
I have the exact same issue running emacs 27.

**Comment by hlissner** [comment]
I believe this was fixed at some point, between Doom and an update to native-comp. Please update both and let me know.
