### ISSUE TITLE
Issues with with-editor

### ISSUE THREAD

**Issue by DoubleClick7** [hlissner/doom-emacs#4171]
```
/home/kon5oul/.emacs.d/.local/straight/build/with-editor/with-editor.elc failed to provide feature ‘with-editor’)
Failed to load org package incrementally, because: (error Loading file /home/kon5oul/.emacs.d/.local/straight/build/with-editor/with-editor.elc failed to provide feature ‘with-editor’)
Failed to load org-agenda package incrementally, because: (error Loading file /home/kon5oul/.emacs.d/.local/straight/build/with-editor/with-editor.elc failed to provide feature ‘with-editor’)
Failed to load org-capture package incrementally, because: (error Loading file /home/kon5oul/.emacs.d/.local/straight/build/with-editor/with-editor.elc failed to provide feature ‘with-editor’)
Failed to load org package incrementally, because: (error Loading file /home/kon5oul/.emacs.d/.local/straight/build/with-editor/with-editor.elc failed to provide feature ‘with-editor’)
```

I get these messages on starting Emacs. I am using feature/native-comp branch of Emacs 28. And `doom sync && doom build` returns [this](https://pastebin.com/sKpzWkdk).

**Comment by ncihnegn** [comment]
```rm -rf ~/.emacs.d/.local/straight/build/with-editor && doom sync``` fixes it.

**Comment by digizeph** [comment]
This happened to me after a fresh `doom upgrade`. Thank you @DoubleClick7 for posting this question and @ncihnegn for answering it.

**Comment by JHerseth** [comment]
I had to do `rm -rf ~/.emacs.d/.local/straight/build-27.1/with-editor && doom sync` to fix this.

**Comment by tigger04** [comment]
Same,

> rm -rf ~/.emacs.d/.local/straight/build/with-editor && doom sync fixes it.

no change

> I had to do rm -rf ~/.emacs.d/.local/straight/build-27.1/with-editor && doom sync to fix this.

this worked

**Comment by jcguu95** [comment]
> `rm -rf ~/.emacs.d/.local/straight/build*/with-editor && doom sync` fixes it.

It didn't for me today. However, the following did (thanks Hendrik!)

```
rm -rf ~/.emacs.d/.local/straight && doom sync
```
