### ISSUE TITLE
Build for multiple versions of Emacs

### ISSUE THREAD

**Issue by ncihnegn** [hlissner/doom-emacs#4172]
Spacemacs stores packages for different versions of emacs in different directories.
So users can switch between versions ruing the previous version's build.
https://github.com/syl20bnr/spacemacs/pull/5410

**Comment by hlissner** [comment]
Doom already accomplishes this with its declarative package manager (and by relying on straight.el). All its packages are cloned directly from the source as well. This means you could:

1. Change what branch or commit is used by adding a `package!` statement to your `~/.doom.d/packages.el`. e.g. `(package! X :pin "newcommithash")` or `(package! X :recipe (:branch "develop"))` then `doom sync -u` and restart Emacs.
2. If you wanted, you could `cd` into the repo directly and check out a specific commit there.

As such, this is not an issue for Doom.

**Comment by ncihnegn** [comment]
I mean to switch between emacs versions, like 27 and 28.

**Comment by hlissner** [comment]
Oh hold up. I think I misread your initial post (sorry, it's 5am). You want me to store packages in different directories per Emacs version. My bad.

**Comment by hlissner** [comment]
As of d784509 and 9ce9c68, packages are built to `~/.emacs.d/.local/straight/build-{emacs-version}` and Doom's autoloads file is written to `~/.emacs.d/.local/autoloads.{emacs-version}.el`. This should resolve your issue.

That said, some extra work is needed to make `doom purge` capable of cleaning up builds across Emacs versions. I'll work on that.

Thanks for bringing it to my attention!

**Comment by jcbird** [comment]
Hi all and thank you for adding this functionality. I have a emacs-26-3 on my main system but did a user install using --prefix of emacs-28 with native install. I am unsure of how to get doom to 'see' the emacs-28 binary even though it is on my path (but named 'emacs-28.0') . Any help would be appreciated and apologies if this is a very naive question.
