### ISSUE TITLE
doom/help ('C-h d') does not appear in hydra on pressing 'C-h'

### ISSUE THREAD

**Issue by bhepple** [hlissner/doom-emacs#4177]
**What did you expect to happen?**

On pressing 'C-h' (on the way to 'C-h d h') I expected to be given a hydra menu including the 'd' option

**What actually happened?**

a - apropros
c - describe-key-briedfly
e - view-echo-area-messages
.../ etc

ie no 'd'

**System information:**
<details><pre>
Place the output of `M-x doom/info` or `~/.emacs.d/bin/doom info` here.
```
SYSTEM  type       gnu/linux
        config     x86_64-redhat-linux-gnu
        shell      /bin/bash
        uname      Linux 5.6.19-200.fc31.x86_64 #1 SMP Wed Jun 17 16:54:35 UTC 2020 x86_64
        path       (~/bin /usr/local/bin /usr/bin /usr/local/sbin /usr/sbin /usr/libexec/emacs/26.3/x86_64-redhat-linux-gnu/)
EMACS   dir        ~/.emacs.d/
        version    26.3
        build      Dec 11, 2019
        buildopts  --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-dbus --with-gif --with-jpeg --with-png --with-rsvg --with-tiff --with-xft --with-xpm --with-x-toolkit=gtk3 --with-gpm=no --with-xwidgets --with-modules build_alias=x86_64-redhat-linux-gnu host_alias=x86_64-redhat-linux-gnu 'CFLAGS=-DMAIL_USE_LOCKF -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection' LDFLAGS=-Wl,-z,relro PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig
        features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LCMS2
        traits     (server-running envvar-file)
DOOM    dir        ~/.doom.d/
        version    2.0.9
        build      grafted, HEAD -> develop, origin/develop, origin/HEAD fe37a59 2020-10-26 05:52:30 -0400
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline ophints (popup +defaults) vc-gutter workspaces :editor file-templates fold snippets :emacs dired electric undo vc :checkers syntax :tools (eval +overlay) lookup magit :lang cc emacs-lisp markdown org python sh :config (default +bindings +smartparens))
        packages   ((key-chord) (browse-kill-ring) (outline-magic) (ibuffer-vc))
        unpin      (n/a)
        elpa       (n/a)
```
</pre></details>

**Comment by hlissner** [comment]
This is which-key, not hydra. Also, prefixes are listed at the end, not at the beginning.

![image](https://user-images.githubusercontent.com/510883/97529260-e6e45300-1985-11eb-881d-80c01ee67f21.png)

Tweak `which-key-sort-order` to change their order.

**Comment by bhepple** [comment]
Ah! Thanks for that. Clearly I'm new to doom (since yesterday).

Unfortunately, I can't see the full set of suggestions from 'which-key' unless emacs is full screen - normally I have it half-screen.
![dump](https://user-images.githubusercontent.com/6417002/97531025-09668280-19ff-11eb-8ccc-b8104cbd9d70.png)

If I try to scroll the 'which-key' display with the scrollbar, it disappears (of course!).

emacs is just too horrible to use full screen - window geometry is too unstable - popups split the screen this way and that. 'C-x 3' splits don't last long (eg the split disappears after a buffer-menu as I never remember to hit 'e' instead of RET). Help screens popup in whatever window it wants to and focus goes wherever! 'C-x 5 2' just doesn't work for me. 

I've never been able to tame it so I resign myself to a half-screen emacs plus a terminal. Sigh! 35 years and I'm still not quite happy with emacs even if it's my daily driver.

**Comment by bhepple** [comment]
I see you made a patch! It works - now it's just the more obscure keys from 'C-h C-n' and up being invisible.

**Comment by hlissner** [comment]
You can "scroll" the which-key window by pressing `C-h` followed by `C-n` (next page) or `C-p` (previous page). You have to wait for the prompt to appear, however:

![image](https://user-images.githubusercontent.com/510883/97541023-d7233980-199a-11eb-9f8b-d03e3a9ca535.png)

You may have better luck searching keybinds with `C-c b b`, if you're hunting for keybinds.

**Comment by bhepple** [comment]
Thanks again! That does work.
What I'm grappling with at the moment is comprehending the doom tutorials as I need to translate from evil to holy (if I may use that term).
I had got hold of the idea that substituting C-c for SPC would map directly - but that's quite wrong apparently. It would be nice if I could see the pattern but it's going to take some study. The hard thing is that the tutorials don't give elisp function names, they just say "Press SPC w w" - and since my emacs is not in evil mode I can't look it up with something like 'C-h k'
