### ISSUE TITLE
Error in Latex module

### ISSUE THREAD

**Issue by oedon23** [hlissner/doom-emacs#4189]
**What did you expect to happen?**
...
Latex module loads on emacs startup

**What actually happened?**
...
Latex module prevents emacs to startup correctly

<details><pre>
Error in Doom module: modules/lang/latex/config.el, (invalid-read-syntax ))
</pre></details>

**Steps to reproduce:**
1. deactivate latex in init.el and emacs loads up
2. activate latex in init.el and emacs does not load up correct

**System information:**
<details><pre>
DOOM
version 2.0.9
build HEAD -> develop c96e901b6 2020-10-31 03:43:55 -0400
</pre></details>

**Comment by elken** [comment]
Looks to be fixed with #4188

**Comment by oedon23** [comment]
Yes deleting the extra ) in line 101 in module latex fixed the problem.

**Comment by hlissner** [comment]
#4188 was merged. Thanks for bringing it to my attention!
