### ISSUE TITLE
doctor.el for doom-private-dir

### ISSUE THREAD

**Issue by danilevy1212** [hlissner/doom-emacs#4190]
**Detect doctor.el in doom-private-dir**
I was wondering if anybody would like this feature. Basically, It would be nice if I could use a "doctor.el" in my "doom-private-dir"
so I could document the dependencies of my packages with doom doctor. For example, I am using nvm.el and I was making a doctor.el with this code:

``` elisp
;;; $DOOMDIR/doctor.el -*- lexical-binding: t; -*-

(unless (or (file-directory-p "~/.nvm") (getenv "NVM_DIR"))
  (warn! "Can't find the nvm directory, nvm package won't work."))
```

And I was surprised to find that doom doctor didn't pick up on this. Then I looked at the defcli! definition of doctor and saw that it only checks inside modules for the doctor.el file. I was a bit surprised because autoloads are looked for inside of doom-private-dir, so I just assumed it would be the same for doctor.el files.  Anyway, I think I could do this myself (I want a good excuse to contribute to this awesome project), however, I also would like to know if maybe I am missing something or if there is any factor that would make this feature unnecesary.

**Comment by danilevy1212** [comment]
I was looking at this a little bit more, and I think I identified the change that would have to be made:

``` elisp
;;; line: 166 doctor.el
       (print! (start "Checking for stale elc files in your DOOMDIR..."))
       (when (file-directory-p doom-private-dir)
         (print-group!
          (elc-check-dir doom-private-dir)))

       (when doom-modules
         (print! (start "Checking your enabled modules..."))
         (advice-add #'require :around #'doom-shut-up-a)
         (maphash (lambda (key plist)
                    (let (doom-local-errors
                          doom-local-warnings)
                      (let (doom-errors
                            doom-warnings)
                        (condition-case-unless-debug ex
                            (let ((doctor-file   (doom-module-path (car key) (cdr key) "doctor.el"))
                                  (packages-file (doom-module-path (car key) (cdr key) "packages.el")))
                              (cl-loop with doom-output-indent = 6
                                       for name in (let (doom-packages
                                                         doom-disabled-packages)
                                                     (load packages-file 'noerror 'nomessage)
                                                     (mapcar #'car doom-packages))
                                       unless (or (doom-package-get name :disable)
                                                  (eval (doom-package-get name :ignore))
                                                  (plist-member (doom-package-get name :recipe) :local-repo)
                                                  (doom-package-built-in-p name)
                                                  (doom-package-installed-p name))
                                       do (print! (error "Missing emacs package: %S") name))
                              (let ((inhibit-message t))
                                (load doctor-file 'noerror 'nomessage)))
                          (file-missing (error! "%s" (error-message-string ex)))
                          (error (error! "Syntax error: %s" ex)))
                        (when (or doom-errors doom-warnings)
                          (print-group!
                           (print! (start (bold "%s %s")) (car key) (cdr key))
                           (print! "%s" (string-join (append doom-errors doom-warnings) "\n")))
                          (setq doom-local-errors doom-errors
                                doom-local-warnings doom-warnings)))
                      (appendq! doom-errors doom-local-errors)
                      (appendq! doom-warnings doom-local-warnings)))
                  doom-modules)))
```

I figure that the logic inside the lambda can be reused, I think what could work is to not iterate through doom-modules but through a list of (doctor-file package-file), derived from the keys of doom modules.

Then, the lambda could be rewritten into a helper method:

``` elisp
(defun check-dir-health (doctor-file package-file)
  ;; TODO
)
```

The code of the lambda would be the same expect we would need to remove the let binding write after the condition-case-unless-debug to use the arguments of the function instead.
``` elisp
(let ((doctor-file   (doom-module-path (car key) (cdr key) "doctor.el"))
                                  (packages-file (doom-module-path (car key) (cdr key) "packages.el")))
```

Then add to the part where there are checks of doom-private-dir
``` elisp
(when (file-directory-p doom-private-dir)
         (print-group!
          (elc-check-dir doom-private-dir))
         (check-dir-health (expand-file-name "doctor.el" doom-private-dir) (expand-file-name "packages.el" doom-private-dir)))
```
Any recommendations or glaring errors?

**Comment by hlissner** [comment]
I'm working on a rewrite of the CLI, which includes a rewrite of the doctor that already sources `$DOOMDIR/doctor.el` if it exists. It'll be some time til its up, but save yourself the trouble. I won't be accepting PRs for the CLI until it's done. Thanks for bringing it to my attention!

**Comment by danilevy1212** [comment]
Awesome! Thanks for the work and I'll be on the look out for more stuff :+1: , my pleasure.

**Comment by hlissner** [comment]
I've moved this and many other issues to #4273. Please keep track of it there.
