### ISSUE TITLE
Errors when changing buffers - wrong type argument: stringp, nil

### ISSUE THREAD

**Issue by offbyone** [hlissner/doom-emacs#4196]
**What did you expect to happen?**
I expected Helm's buffer switcher to appear

**What actually happened?**
As described on Discord:

> [12:28 PM] Chris R: @helpme I'm having a weird issue where `C-x b` -- which apparently is mapped to `+helm/workspace-mini` -- is spitting out `helm-buffers-list--init: Wrong type argument: stringp, nil`
> [12:45 PM] Chris R: ... and then I tried toggling `debug-on-error` and now I get `run-hook-with-args: Selecting deleted buffer`
> [12:46 PM] Chris R: I can still change buffers using ibuffer, but helm's change buffer is borked.

**Additional details:**

debug-on-error doesn't seem to work either, FWIW; I could not get the traceback to appear until I _exit_ emacs, at which point the traceback for the _second_ error pops up (but not the first). To date I have not managed to get a traceback for that one. I'm going to see if I can make a reproduction case for it, and if I do I'll comment with that and the traceback here.

** Traceback **
<details><pre>
Debugger entered--Lisp error: (error "Selecting deleted buffer")
  #f(compiled-function (s-f) #<bytecode 0x1fe499df693d>)((lambda (buffer) (when (funcall (with-no-warnings '(lambda (buffer &rest rest-args) (when ... ...))) buffer) (let ((vars-list (with-current-buffer buffer (cl-delete-if-not ... ... :key ...)))) (funcall (with-no-warnings '(closure ... ... ...)) buffer 'def-indirect-buffer vars-list)))))
  cl--position(nil ((lambda (buffer) (when (funcall (with-no-warnings '(lambda ... ...)) buffer) (let ((vars-list (with-current-buffer buffer ...))) (funcall (with-no-warnings '...) buffer 'def-indirect-buffer vars-list)))) (lambda (buffer) (when (funcall (with-no-warnings '(lambda ... ...)) buffer) (let ((vars-list (with-current-buffer buffer ...))) (list 'def-compilation-buffer (buffer-name buffer) vars-list)))) (lambda (buffer) (when (funcall (with-no-warnings '(lambda ... ...)) buffer) (let ((vars-list (with-current-buffer buffer ...))) (list 'def-eshell-buffer (buffer-name buffer) vars-list)))) #f(compiled-function (b) #<bytecode 0x1fe49ded8bb1>) persp-tramp-save-buffer #f(compiled-function (b) #<bytecode 0x1fe49ded8bcd>) #f(compiled-function (b) #<bytecode 0x1fe49ded8be5>)) 0 nil nil)
  cl-position(nil ((lambda (buffer) (when (funcall (with-no-warnings '(lambda ... ...)) buffer) (let ((vars-list (with-current-buffer buffer ...))) (funcall (with-no-warnings '...) buffer 'def-indirect-buffer vars-list)))) (lambda (buffer) (when (funcall (with-no-warnings '(lambda ... ...)) buffer) (let ((vars-list (with-current-buffer buffer ...))) (list 'def-compilation-buffer (buffer-name buffer) vars-list)))) (lambda (buffer) (when (funcall (with-no-warnings '(lambda ... ...)) buffer) (let ((vars-list (with-current-buffer buffer ...))) (list 'def-eshell-buffer (buffer-name buffer) vars-list)))) #f(compiled-function (b) #<bytecode 0x1fe49ded8bb1>) persp-tramp-save-buffer #f(compiled-function (b) #<bytecode 0x1fe49ded8bcd>) #f(compiled-function (b) #<bytecode 0x1fe49ded8be5>)) :if #f(compiled-function (sl) #<bytecode 0x1fe499df6929>) :key #f(compiled-function (s-f) #<bytecode 0x1fe499df693d>))
  apply(cl-position nil ((lambda (buffer) (when (funcall (with-no-warnings '(lambda ... ...)) buffer) (let ((vars-list (with-current-buffer buffer ...))) (funcall (with-no-warnings '...) buffer 'def-indirect-buffer vars-list)))) (lambda (buffer) (when (funcall (with-no-warnings '(lambda ... ...)) buffer) (let ((vars-list (with-current-buffer buffer ...))) (list 'def-compilation-buffer (buffer-name buffer) vars-list)))) (lambda (buffer) (when (funcall (with-no-warnings '(lambda ... ...)) buffer) (let ((vars-list (with-current-buffer buffer ...))) (list 'def-eshell-buffer (buffer-name buffer) vars-list)))) #f(compiled-function (b) #<bytecode 0x1fe49ded8bb1>) persp-tramp-save-buffer #f(compiled-function (b) #<bytecode 0x1fe49ded8bcd>) #f(compiled-function (b) #<bytecode 0x1fe49ded8be5>)) (:if #f(compiled-function (sl) #<bytecode 0x1fe499df6929>) :key #f(compiled-function (s-f) #<bytecode 0x1fe499df693d>)))
  cl-find(nil ((lambda (buffer) (when (funcall (with-no-warnings '(lambda ... ...)) buffer) (let ((vars-list (with-current-buffer buffer ...))) (funcall (with-no-warnings '...) buffer 'def-indirect-buffer vars-list)))) (lambda (buffer) (when (funcall (with-no-warnings '(lambda ... ...)) buffer) (let ((vars-list (with-current-buffer buffer ...))) (list 'def-compilation-buffer (buffer-name buffer) vars-list)))) (lambda (buffer) (when (funcall (with-no-warnings '(lambda ... ...)) buffer) (let ((vars-list (with-current-buffer buffer ...))) (list 'def-eshell-buffer (buffer-name buffer) vars-list)))) #f(compiled-function (b) #<bytecode 0x1fe49ded8bb1>) persp-tramp-save-buffer #f(compiled-function (b) #<bytecode 0x1fe49ded8bcd>) #f(compiled-function (b) #<bytecode 0x1fe49ded8be5>)) :if #f(compiled-function (sl) #<bytecode 0x1fe499df6929>) :key #f(compiled-function (s-f) #<bytecode 0x1fe499df693d>))
  apply(cl-find nil ((lambda (buffer) (when (funcall (with-no-warnings '(lambda ... ...)) buffer) (let ((vars-list (with-current-buffer buffer ...))) (funcall (with-no-warnings '...) buffer 'def-indirect-buffer vars-list)))) (lambda (buffer) (when (funcall (with-no-warnings '(lambda ... ...)) buffer) (let ((vars-list (with-current-buffer buffer ...))) (list 'def-compilation-buffer (buffer-name buffer) vars-list)))) (lambda (buffer) (when (funcall (with-no-warnings '(lambda ... ...)) buffer) (let ((vars-list (with-current-buffer buffer ...))) (list 'def-eshell-buffer (buffer-name buffer) vars-list)))) #f(compiled-function (b) #<bytecode 0x1fe49ded8bb1>) persp-tramp-save-buffer #f(compiled-function (b) #<bytecode 0x1fe49ded8bcd>) #f(compiled-function (b) #<bytecode 0x1fe49ded8be5>)) :if #f(compiled-function (sl) #<bytecode 0x1fe499df6929>) (:key #f(compiled-function (s-f) #<bytecode 0x1fe499df693d>)))
  cl-find-if(#f(compiled-function (sl) #<bytecode 0x1fe499df6929>) ((lambda (buffer) (when (funcall (with-no-warnings '(lambda ... ...)) buffer) (let ((vars-list (with-current-buffer buffer ...))) (funcall (with-no-warnings '...) buffer 'def-indirect-buffer vars-list)))) (lambda (buffer) (when (funcall (with-no-warnings '(lambda ... ...)) buffer) (let ((vars-list (with-current-buffer buffer ...))) (list 'def-compilation-buffer (buffer-name buffer) vars-list)))) (lambda (buffer) (when (funcall (with-no-warnings '(lambda ... ...)) buffer) (let ((vars-list (with-current-buffer buffer ...))) (list 'def-eshell-buffer (buffer-name buffer) vars-list)))) #f(compiled-function (b) #<bytecode 0x1fe49ded8bb1>) persp-tramp-save-buffer #f(compiled-function (b) #<bytecode 0x1fe49ded8bcd>) #f(compiled-function (b) #<bytecode 0x1fe49ded8be5>)) :key #f(compiled-function (s-f) #<bytecode 0x1fe499df693d>))
  #f(compiled-function (b) #<bytecode 0x1fe499d8799d>)(#<killed buffer>)
  mapcar(#f(compiled-function (b) #<bytecode 0x1fe499d8799d>) (#<buffer magit-revision: infra> #<buffer magit-diff: infra> #<buffer magit: infra> #<killed buffer> #<buffer main.yml<3>> #<buffer main.yml<2>> #<buffer playbook-default.yml> #<buffer pi.yml> #<buffer hosts> #<buffer dashboard.yml> #<buffer all.yml> #<buffer playbook-telegraf.yml> #<buffer main.yml> #<buffer playbook-init-pi.yml> #<buffer nuc.yml> #<buffer requirements.yml> #<buffer playbook-nuc.yml> #<buffer playbook-nuc-dokku.yml>))
  persp-buffers-to-savelist(#s(perspective :name "main" :buffers (#<buffer magit-revision: infra> #<buffer magit-diff: infra> #<buffer magit: infra> #<killed buffer> #<buffer main.yml<3>> #<buffer main.yml<2>> #<buffer playbook-default.yml> #<buffer pi.yml> #<buffer hosts> #<buffer dashboard.yml> #<buffer all.yml> #<buffer playbook-telegraf.yml> #<buffer main.yml> #<buffer playbook-init-pi.yml> #<buffer nuc.yml> #<buffer requirements.yml> #<buffer playbook-nuc.yml> #<buffer playbook-nuc-dokku.yml>) :window-conf (((min-height . 4) (min-width . 10) (min-height-ignore . 3) (min-width-ignore . 4) (min-height-safe . 1) (min-width-safe . 2) (min-pixel-height . 56) (min-pixel-width . 70) (min-pixel-height-ignore . 40) (min-pixel-width-ignore . 22) (min-pixel-height-safe . 14) (min-pixel-width-safe . 14)) leaf (pixel-width . 892) (pixel-height . 1057) (total-width . 127) (total-height . 75) (normal-height . 1.0) (normal-width . 1.0) (parameters (better-jumper-struct . #s(better-jumper-jump-list-struct :ring (0 2 . [... ... nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil ...]) :idx -1))) (buffer "*Messages*" (selected . t) (hscroll . 0) (fringes 4 4 t nil) (margins nil) (scroll-bars nil 0 t nil 0 t nil) (vscroll . 0) (dedicated) (point . 13611) (start . 10668)) (prev-buffers ("*Messages*" 10668 13611) ("*Ibuffer*" 1 2738) ("magit: infra" 1 715) ("playbook-telegraf.yml" 1 269) ("main.yml<2>" 1 181) ("nuc.yml" 1222 1757) ("playbook-default.yml" 1 694) ("pi.yml" 1 1289) ("hosts" 417 671) ("playbook-init-pi.yml" 1 373) ("all.yml" 1 1) ("main.yml" 1 770) ("playbook-nuc-dokku.yml" 1 66) ("requirements.yml" 1 106) ("*doom*" 1 1577) ("*scratch*" 1 1))) :parameters nil :weak nil :auto nil :hidden nil))
  persp-to-savelist(#s(perspective :name "main" :buffers (#<buffer magit-revision: infra> #<buffer magit-diff: infra> #<buffer magit: infra> #<killed buffer> #<buffer main.yml<3>> #<buffer main.yml<2>> #<buffer playbook-default.yml> #<buffer pi.yml> #<buffer hosts> #<buffer dashboard.yml> #<buffer all.yml> #<buffer playbook-telegraf.yml> #<buffer main.yml> #<buffer playbook-init-pi.yml> #<buffer nuc.yml> #<buffer requirements.yml> #<buffer playbook-nuc.yml> #<buffer playbook-nuc-dokku.yml>) :window-conf (((min-height . 4) (min-width . 10) (min-height-ignore . 3) (min-width-ignore . 4) (min-height-safe . 1) (min-width-safe . 2) (min-pixel-height . 56) (min-pixel-width . 70) (min-pixel-height-ignore . 40) (min-pixel-width-ignore . 22) (min-pixel-height-safe . 14) (min-pixel-width-safe . 14)) leaf (pixel-width . 892) (pixel-height . 1057) (total-width . 127) (total-height . 75) (normal-height . 1.0) (normal-width . 1.0) (parameters (better-jumper-struct . #s(better-jumper-jump-list-struct :ring (0 2 . [... ... nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil ...]) :idx -1))) (buffer "*Messages*" (selected . t) (hscroll . 0) (fringes 4 4 t nil) (margins nil) (scroll-bars nil 0 t nil 0 t nil) (vscroll . 0) (dedicated) (point . 13611) (start . 10668)) (prev-buffers ("*Messages*" 10668 13611) ("*Ibuffer*" 1 2738) ("magit: infra" 1 715) ("playbook-telegraf.yml" 1 269) ("main.yml<2>" 1 181) ("nuc.yml" 1222 1757) ("playbook-default.yml" 1 694) ("pi.yml" 1 1289) ("hosts" 417 671) ("playbook-init-pi.yml" 1 373) ("all.yml" 1 1) ("main.yml" 1 770) ("playbook-nuc-dokku.yml" 1 66) ("requirements.yml" 1 106) ("*doom*" 1 1577) ("*scratch*" 1 1))) :parameters nil :weak nil :auto nil :hidden nil))
  mapcar(persp-to-savelist (#s(perspective :name "main" :buffers (#<buffer magit-revision: infra> #<buffer magit-diff: infra> #<buffer magit: infra> #<killed buffer> #<buffer main.yml<3>> #<buffer main.yml<2>> #<buffer playbook-default.yml> #<buffer pi.yml> #<buffer hosts> #<buffer dashboard.yml> #<buffer all.yml> #<buffer playbook-telegraf.yml> #<buffer main.yml> #<buffer playbook-init-pi.yml> #<buffer nuc.yml> #<buffer requirements.yml> #<buffer playbook-nuc.yml> #<buffer playbook-nuc-dokku.yml>) :window-conf (((min-height . 4) (min-width . 10) (min-height-ignore . 3) (min-width-ignore . 4) (min-height-safe . 1) (min-width-safe . 2) (min-pixel-height . 56) (min-pixel-width . 70) (min-pixel-height-ignore . 40) (min-pixel-width-ignore . 22) (min-pixel-height-safe . 14) (min-pixel-width-safe . 14)) leaf (pixel-width . 892) (pixel-height . 1057) (total-width . 127) (total-height . 75) (normal-height . 1.0) (normal-width . 1.0) (parameters (better-jumper-struct . #s(better-jumper-jump-list-struct :ring (0 2 . ...) :idx -1))) (buffer "*Messages*" (selected . t) (hscroll . 0) (fringes 4 4 t nil) (margins nil) (scroll-bars nil 0 t nil 0 t nil) (vscroll . 0) (dedicated) (point . 13611) (start . 10668)) (prev-buffers ("*Messages*" 10668 13611) ("*Ibuffer*" 1 2738) ("magit: infra" 1 715) ("playbook-telegraf.yml" 1 269) ("main.yml<2>" 1 181) ("nuc.yml" 1222 1757) ("playbook-default.yml" 1 694) ("pi.yml" 1 1289) ("hosts" 417 671) ("playbook-init-pi.yml" 1 373) ("all.yml" 1 1) ("main.yml" 1 770) ("playbook-nuc-dokku.yml" 1 66) ("requirements.yml" 1 106) ("*doom*" 1 1577) ("*scratch*" 1 1))) :parameters nil :weak nil :auto nil :hidden nil)))
  persps-to-savelist(#<hash-table equal 2/10 0x1fe49dee657d>)
  persp-save-state-to-file()
  #f(compiled-function (&optional interactive-query) #<bytecode 0x1fe49deddb61>)(t)
  apply(#f(compiled-function (&optional interactive-query) #<bytecode 0x1fe49deddb61>) t)
  (progn (apply orig-fn args))
  (if (doom-real-buffer-list) (progn (apply orig-fn args)))
  +workspaces-autosave-real-buffers-a(#f(compiled-function (&optional interactive-query) #<bytecode 0x1fe49deddb61>) t)
  apply(+workspaces-autosave-real-buffers-a #f(compiled-function (&optional interactive-query) #<bytecode 0x1fe49deddb61>) t)
  persp-asave-on-exit(t)
  persp-kill-emacs-query-function()
  run-hook-with-args-until-failure(persp-kill-emacs-query-function)
  save-buffers-kill-emacs(nil)
  save-buffers-kill-terminal(nil)
  funcall-interactively(save-buffers-kill-terminal nil)
  call-interactively(save-buffers-kill-terminal nil nil)
  command-execute(save-buffers-kill-terminal)</pre></details>

** Messages history just before **
```
Git finished
Running /usr/local/bin/git push -v origin refs/heads/mainline:refs/heads/mainline
Git finished
user-error: No window right from selected window
helm-buffers-list--init: Wrong type argument: stringp, nil            <---- this is the first instance of the error
line-move-visual: End of buffer [5 times]
helm-buffers-list--init: Wrong type argument: stringp, nil
Debug on Error enabled globally
run-hook-with-args: Selecting deleted buffer [2 times]
```

**System information:**
<details><pre>
```
SYSTEM  type       darwin
        config     x86_64-apple-darwin19.6.0
        shell      /bin/bash
        uname      Darwin 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64
        path       (~/.pyenv/shims /usr/local/bin /usr/bin /bin /usr/sbin /sbin /Library/Frameworks/Mono.framework/Versions/Current/Commands ~/.local/bin ~/.cargo/bin ~/.emacs.d/bin ~/git-scripts ~/extensions/git-cal ~/extensions/git-flow ~/extensions/git-hg ~/extensions/git-hooks ~/extensions/git-hub ~/extensions/git-remote-hg /usr/local/Cellar/emacs-head@27/27.1_1/libexec/emacs/27.1/x86_64-apple-darwin19.6.0/)
EMACS   dir        ~/.emacs.d/
        version    27.1
        build      Oct 10, 2020
        buildopts  --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-head@27/27.1_1/share/info/emacs --prefix=/usr/local/Cellar/emacs-head@27/27.1_1 --without-x --without-dbus --with-imagemagick --with-modules --with-gnutls --with-rsvg --with-xml2 --with-ns --disable-ns-self-contained --with-harfbuzz
        features   RSVG IMAGEMAGICK GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS JSON PDUMPER LCMS2 GMP
        traits     (server-running envvar-file)
DOOM    dir        ~/.doom.d/
        version    2.0.9
        build      HEAD -> develop 57ef63d6b 2020-10-29 05:42:10 -0400
        elc-files  0
        modules    (:completion company (helm +fuzzy) :ui doom doom-dashboard doom-quit fill-column hl-todo hydra minimap modeline ophints (popup +defaults) unicode vc-gutter vi-tilde-fringe window-select workspaces :editor file-templates fold (format +onsave) snippets :emacs dired electric ibuffer undo vc :checkers syntax :tools ansible direnv docker editorconfig (eval +overlay) gist lookup lsp magit make terraform tmux :os macos :lang emacs-lisp (go +lsp) json (java +lsp) javascript kotlin markdown (org +brain +journal +pandoc +pretty +present +roam) plantuml (python +lsp +poetry +pyenv) (ruby +rails) rust sh web yaml :config (default +bindings +smartparens))
        packages   ((git-auto-commit-mode) (windmove) (chezmoi :recipe (:host github :repo tuh8888/chezmoi.el)) (csv-mode))
        unpin      (n/a)
        elpa       (n/a)
```
</pre></details>

**Comment by hlissner** [comment]
Add this to `~/.doom.d/config.el` and let me know if it fixes your issue:

```elisp
(defadvice! +workspaces-remove-dead-buffers-a (persp)
  :before #'persp-buffers-to-savelist
  (when (persp-p persp)
    (setf (persp-buffers persp)
          (cl-remove-if-not #'buffer-live-p
                            (persp-buffers persp)))))
```

**Comment by offbyone** [comment]
If this is going to work, how would I confirm it? Is there a series of actions I can take to confirm it?

**Comment by hlissner** [comment]
Unfortunately, I haven't been able to reliably reproduce this. You'd have to add it and see if it ever comes up again.

In any case, I've upstreamed it in 7d60318, so I'll consider this resolved for the time being. If it resurfaces, let me know.
