### ISSUE TITLE
is eldoc-eval necessary?

### ISSUE THREAD

**Issue by aaronjensen** [hlissner/doom-emacs#420]
Hi there,

I found out about eldoc-eval while porting your modeline to my spacemacs config. I was curious if it is still necessary now that eldoc actually has a similar functionality built in to it. It appears that the primary difference is that w/ eldoc-eval you can define your modeline and/or your display function manually instead of relying on eldoc's default behavior of prepending the eldoc to the modeline.

Any way, I was just curious, so I thought I'd ask. Feel free to close this issue 😄 

Thanks for the great mode-line and other ideas in this repo!

**Comment by hlissner** [comment]
You're right, it isn't really necessary anymore. I don't recall eldoc having that behavior though. Would you happen to know how recently that was added?

**Comment by aaronjensen** [comment]
```
+2013-03-17  Leo Liu  <sdl.web@gmail.com>
+
+	Extend eldoc to display info in the mode-line.  (Bug#13978)
+	* emacs-lisp/eldoc.el (eldoc-post-insert-mode): New minor mode.
+	(eldoc-mode-line-string): New variable.
+	(eldoc-minibuffer-message): New function.
+	(eldoc-message-function): New variable.
+	(eldoc-message): Use it.
+	(eldoc-display-message-p)
+	(eldoc-display-message-no-interference-p): Support
+	eldoc-post-insert-mode.
+
+	* simple.el (eval-expression-minibuffer-setup-hook): New hook.
+	(eval-expression): Run it.
+
```

**Comment by hlissner** [comment]
Huh, it's been around for a lot longer than Doom. Well, I've removed it in `develop`. I'll keep this open until it hits `master`. Thanks for letting me know!

**Comment by aaronjensen** [comment]
You bet!
