### ISSUE TITLE
Doom is broken with latest pull

### ISSUE THREAD

**Issue by apwrv** [hlissner/doom-emacs#4204]
**Doom is broken with the latest pull.**

**Background:** trying to setup doom emacs from scratch on my new VM and running the `bin/doom install` fails with `Wrong number of arguments: (1 . 1), 2` at the very first step.

The following is the output from the VM

~
❯ git clone --depth 1 https://github.com/hlissner/doom-emacs ~/.emacs.d
Cloning into '/home/krishna/.emacs.d'...
remote: Enumerating objects: 1014, done.
remote: Counting objects: 100% (1014/1014), done.
remote: Compressing objects: 100% (959/959), done.
remote: Total 1014 (delta 20), reused 350 (delta 13), pack-reused 0
Receiving objects: 100% (1014/1014), 870.39 KiB | 2.93 MiB/s, done.
Resolving deltas: 100% (20/20), done.

~
❯ cd ~/.emacs.d/

.emacs.d on  develop
❯ bin/doom install
Installing straight...
Wrong number of arguments: (1 . 1), 2

The configuration of this VM is as follows;
OS: Ubuntu 20.10
Emacs: GNU Emacs 26.3
ripgrep: 12.1.1
git: 2.27
find: 4.7.0
fd-find: 8.1.1

Can you please fix this?

Thank you.

**Comment by hlissner** [comment]
As of 65be692 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by apwrv** [comment]
Thank you very much for the super fast fix!

Installation went through without any issues.
