### ISSUE TITLE
No way to interrupt direnv when running it takes ages

### ISSUE THREAD

**Issue by tobiasBora** [hlissner/doom-emacs#4208]
**What did you expect to happen?**

I'm using `direnv` together with Nix in order to provide all my tools in a console. This is great that doom automatically runs direnv when using the `direnv` module, but sometimes I'd like to be able to cancel this. The reason is that it can sometimes take ages to compile a given direnv environment, and sometimes I just want to edit quickly a file. In the terminal I can press `C-c` to stop direnv, would it be possible to provide a similar command inside doom? 

**Steps to reproduce:**
1. Install and configure direnv. For example, I use nix and home-manager, configured using:
```
{ config, pkgs, ... }:
# https://rycee.gitlab.io/home-manager/
{
  # Let Home Manager install and manage itself.
  programs.home-manager.enable = true;

  # Direnv
  programs.bash.enable = true;
  programs.direnv.enable = true;
  programs.direnv.enableNixDirenvIntegration = true;
}
```
2. Create a `.envrc` that takes some time to be generated, for example using `echo "sleep 20" > .envrc` (in real-life, this comes from `shell.nix` files that takes lots of time to build the packages)
3. Allow that folder to use direnv, by running `direnv allow`
4. Try to open with doom-emacs, with the module `:tool direnv` enabled, the file `.envrc` for example. Note that I think that you need to run emacs from another folder than the one where you created your `direnv` environment, otherwise I don't think it runs direnv.
![image](https://user-images.githubusercontent.com/2164118/97998769-d0595400-1dea-11eb-9dfd-8e519d52f993.png)

Note that pressing `C-g` does not just stop direnv, but it cancel the whole file openning.
 
**System information:**
<details><pre>
```
SYSTEM  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /run/current-system/sw/bin/bash
        uname      Linux 5.4.66 #1-NixOS SMP Thu Sep 17 11:47:56 UTC 2020 x86_64
        path       (/run/wrappers/bin ~/.nix-profile/bin /etc/profiles/per-user/$USER/bin /nix/var/nix/profiles/default/bin /run/current-system/sw/bin /nix/store/ih9bwzlkp0r5p999fnrdx1m1xkm0kfb6-emacs-26.3/libexec/emacs/26.3/x86_64-pc-linux-gnu/)
EMACS   dir        ~/Documents/Informatique/Emacs_configurations/2020_doom/dot_emacs_dot_d/
        version    26.3
        build      nov. 03, 2020
        buildopts  --prefix=/nix/store/ih9bwzlkp0r5p999fnrdx1m1xkm0kfb6-emacs-26.3 --disable-build-details --with-modules --with-x-toolkit=gtk3 --with-xft CFLAGS=-DMAC_OS_X_VERSION_MAX_ALLOWED=101200
        features   XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD
        traits     (server-running envvar-file)
DOOM    dir        ~/Documents/Informatique/Emacs_configurations/2020_doom/dot_doom_dot_d/
        version    2.0.9
        build      grafted, HEAD -> develop, origin/develop, origin/HEAD 807f00a 2020-11-02 23:56:43 -0500
        elc-files  0
        modules    (:completion company (ivy +fuzzy +prescient +icons) :ui doom doom-dashboard doom-quit (emoji +unicode) hl-todo minimap modeline ophints (popup +defaults) vc-gutter vi-tilde-fringe :editor file-templates fold snippets :emacs dired electric undo vc :checkers syntax spell grammar :tools direnv (eval +overlay) lookup lsp magit :os tty :lang cc emacs-lisp (haskell +dante) (latex +latexmk +cdlatex +lsp +fold) lua markdown nix ocaml org rst sh web :config (default +bindings +smartparens))
        packages   (n/a)
        unpin      (n/a)
        elpa       (n/a)
```
</pre></details>

**Comment by hlissner** [comment]
As of d45155aec, direnv will no longer run more than once in some buffers. As of f7293fb, aborting direnv won't abort opening the file. With this your issue should be resolved. 
Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by tobiasBora** [comment]
Works perfectly, thank you so much!
