### ISSUE TITLE
[ LaTeX ] Error automatically indenting inside itemize environment

### ISSUE THREAD

**Issue by juanscr** [hlissner/doom-emacs#4209]
**What did you expect to happen?**
Normally, I would indent the text inside an itemize list using the `M-q (fill-paragraph)` command to automatically indent the text inside the environment.

**What actually happened?**
Got the error
```
LaTeX-indent-calculate: Symbol’s function definition is void: +latex/LaTeX-indent-item
```
The indentation was not made automatically.

**Suggested Workaround:**
 I saw that in [this commit](https://github.com/hlissner/doom-emacs/commit/98826f33d003e0a5e218246c8f4381a2a27b8355#diff-e05c02d900f1c13c70c61e00aa8d57359e61a814461fe0ecb3833b717540d46f) some changes where realized on how indentation is formatted, since this commit the automatic indentation stopped working.

Therefore to fix this just change these lines in the [config.el](https://github.com/hlissner/doom-emacs/blob/develop/modules/lang/latex/config.el):
```elisp
 (let ((LaTeX-indent-environment-list
           (append LaTeX-indent-environment-list
                   '(("itemize"   +latex/LaTeX-indent-item)
                     ("enumerate" +latex/LaTeX-indent-item)))))
```

to this:
```elisp
 (let ((LaTeX-indent-environment-list
           (append LaTeX-indent-environment-list
                   '(("itemize"   +latex-indent-item-fn)
                     ("enumerate" +latex-indent-item-fn)))))
```

**Comment by hlissner** [comment]
As of 4fc084e this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
