### ISSUE TITLE
No completion in .ts files

### ISSUE THREAD

**Issue by osenvosem** [hlissner/doom-emacs#4213]
**What did you expect to happen?**
Completion open.

**What actually happened?**
No completion.

**Additional details:**
![Screenshot 2020-11-04 at 20 42 12](https://user-images.githubusercontent.com/6762673/98149755-aed99480-1ede-11eb-835b-c771f2e636e7.jpg)

<details><pre>
No completion found
</pre></details>

**Steps to reproduce:**
1. Open .ts file.
2. Write something that must have completion like `document.` and press Ctrl+Space

**System information:**
<details><pre>
SYSTEM  type       darwin
        config     x86_64-apple-darwin19.5.0
        shell      /bin/zsh
        uname      Darwin 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64
        path       (~/Documents/dev/node-sandbox/node_modules/.bin/ ~/Dropbox/appdata/.config/doom.d/bin/ /var/folders/1t/d2tthcgx6pqd831qg5nbc5vm0000gn/T/fnm_multishell_42728_1604507206760/bin ~/.cargo/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /Library/Apple/usr/bin /usr/local/opt/mongodb-community@4.2/bin ~/.gem/ruby/2.6.0/bin ~/Library/Android/sdk/emulator ~/.cargo/bin /usr/local/sbin ~/.config/doom.d/bin ~/.fzf/bin /usr/local/Cellar/emacs-plus@27/27.1/libexec/emacs/27.1/x86_64-apple-darwin19.5.0/)
EMACS   dir        ~/Dropbox/appdata/.config/doom.d/
        version    27.1
        build      Aug 27, 2020
        buildopts  --disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus@27/27.1/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus@27/27.1 --with-xml2 --with-gnutls --without-dbus --with-imagemagick --with-modules --with-rsvg --with-ns --disable-ns-self-contained
        features   RSVG IMAGEMAGICK GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS JSON PDUMPER LCMS2 GMP
        traits     (server-running chemacs envvar-file)
DOOM    dir        ~/Dropbox/appdata/.config/doom/
        version    2.0.9
        build      HEAD -> develop 5d5d94d49 2020-11-04 03:02:01 -0500
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo ligatures minimap modeline ophints (popup +defaults) treemacs vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold (format +onsave) snippets :emacs dired electric undo vc :term vterm :checkers syntax :tools (eval +overlay) lookup lsp magit :os macos :lang emacs-lisp (json +lsp) (javascript +lsp) markdown org rest sh (web +lsp) yaml :config (default +bindings +smartparens))
        packages   (n/a)
        unpin      (n/a)
        elpa       (n/a)
</pre></details>

**config.el**
<details><pre>
;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-

;; Place your private configuration here! Remember, you do not need to run 'doom
;; sync' after modifying this file!

;; Some functionality uses this to identify you, e.g. GPG configuration, email
;; clients, file templates and snippets.
(setq user-full-name "Samsonov Sergey"
      user-mail-address "osenvosem@gmail.com")

;; Doom exposes five (optional) variables for controlling fonts in Doom. Here
;; are the three important ones:
;;
;; + `doom-font'

;; + `doom-variable-pitch-font'
;; + `doom-big-font' -- used for `doom-big-font-mode'; use this for
;;   presentations or streaming.
;;
;; They all accept either a font-spec, font string ("Input Mono-12"), or xlfd
;; font string. You generally only need these two:
;; (setq doom-font (font-spec :family "monospace" :size 12 :weight 'semi-light)
;;       doom-variable-pitch-font (font-spec :family "sans" :size 13))
(setq doom-font (font-spec :family "JetBrains Mono" :size 14))

;; There are two ways to load a theme. Both assume the theme is installed and
;; available. You can either set `doom-theme' or manually load a theme with the
;; `load-theme' function. This is the default:
(setq doom-theme 'doom-one)

;; If you use `org' and don't want your org files in the default location below,
;; change `org-directory'. It must be set before org loads!
(setq org-directory "~/org/")

;; This determines the style of line numbers in effect. If set to `nil', line
;; numbers are disabled. For relative line numbers, set this to `relative'.
(setq display-line-numbers-type t)

;; Here are some additional functions/macros that could help you configure Doom:
;;
;; - `load!' for loading external *.el files relative to this one
;; - `use-package!' for configuring packages
;; - `after!' for running code after a package has loaded
;; - `add-load-path!' for adding directories to the `load-path', relative to
;;   this file. Emacs searches the `load-path' when you load packages with
;;   `require' or `use-package'.
;; - `map!' for binding new keys
;;
;; To get information about any of these functions/macros, move the cursor over
;; the highlighted symbol at press 'K' (non-evil users must press 'C-c c k').
;; This will open documentation for it, including demos of how they are used.
;;
;; You can also try 'gd' (or 'C-c c d') to jump to their definition and see how
;; they are implemented.

;; Save frame dimensions
(when-let (dims (doom-store-get 'last-frame-size))
  (cl-destructuring-bind ((left . top) width height fullscreen) dims
    (setq initial-frame-alist
          (append initial-frame-alist
                  `((left . ,left)
                    (top . ,top)
                    (width . ,width)
                    (height . ,height)
                    (fullscreen . ,fullscreen))))))

(defun save-frame-dimensions ()
  (doom-store-put 'last-frame-size
                  (list (frame-position)
                        (frame-width)
                        (frame-height)
                        (frame-parameter nil 'fullscreen))))

(add-hook 'kill-emacs-hook #'save-frame-dimensions)
</pre></details>

**init.el**
<details><pre>
;;; init.el -*- lexical-binding: t; -*-

;; This file controls what Doom modules are enabled and what order they load
;; in. Remember to run 'doom sync' after modifying it!

;; NOTE Press 'SPC h d h' (or 'C-h d h' for non-vim users) to access Doom's
;;      documentation. There you'll find a "Module Index" link where you'll find
;;      a comprehensive list of Doom's modules and what flags they support.

;; NOTE Move your cursor over a module's name (or its flags) and press 'K' (or
;;      'C-c c k' for non-vim users) to view its documentation. This works on
;;      flags as well (those symbols that start with a plus).
;;
;;      Alternatively, press 'gd' (or 'C-c c d') on a module to browse its
;;      directory (for easy access to its source code).

(doom! :input
       ;;chinese
       ;;japanese
       ;;layout            ; auie,ctsrnm is the superior home row

       :completion
       company           ; the ultimate code completion backend
       ;;helm              ; the *other* search engine for love and life
       ;;ido               ; the other *other* search engine...
       ivy               ; a search engine for love and life

       :ui
       ;;deft              ; notational velocity for Emacs
       doom              ; what makes DOOM look the way it does
       doom-dashboard    ; a nifty splash screen for Emacs
       doom-quit         ; DOOM quit-message prompts when you quit Emacs
       ;;(emoji +unicode)  ; 🙂
       ;;fill-column       ; a `fill-column' indicator
       hl-todo           ; highlight TODO/FIXME/NOTE/DEPRECATED/HACK/REVIEW
       ;;hydra
       ;;indent-guides     ; highlighted indent columns
       ligatures         ; ligatures and symbols to make your code pretty again
       minimap           ; show a map of the code on the side
       modeline          ; snazzy, Atom-inspired modeline, plus API
       ;;nav-flash         ; blink cursor line after big motions
       ;;neotree           ; a project drawer, like NERDTree for vim
       ophints           ; highlight the region an operation acts on
       (popup +defaults)   ; tame sudden yet inevitable temporary windows
       ;;tabs              ; a tab bar for Emacs
       treemacs          ; a project drawer, like neotree but cooler
       ;;unicode           ; extended unicode support for various languages
       vc-gutter         ; vcs diff in the fringe
       vi-tilde-fringe   ; fringe tildes to mark beyond EOB
       ;;window-select     ; visually switch windows
       workspaces        ; tab emulation, persistence & separate workspaces
       ;;zen               ; distraction-free coding or writing

       :editor
       (evil +everywhere); come to the dark side, we have cookies
       file-templates    ; auto-snippets for empty files
       fold              ; (nigh) universal code folding
       (format +onsave)  ; automated prettiness
       ;;god               ; run Emacs commands without modifier keys
       ;;lispy             ; vim for lisp, for people who don't like vim
       ;;multiple-cursors  ; editing in many places at once
       ;;objed             ; text object editing for the innocent
       ;;parinfer          ; turn lisp into python, sort of
       ;;rotate-text       ; cycle region at point between text candidates
       snippets          ; my elves. They type so I don't have to
       ;;word-wrap         ; soft wrapping with language-aware indent

       :emacs
       dired             ; making dired pretty [functional]
       electric          ; smarter, keyword-based electric-indent
       ;;ibuffer         ; interactive buffer management
       undo              ; persistent, smarter undo for your inevitable mistakes
       vc                ; version-control and Emacs, sitting in a tree

       :term
       ;;eshell            ; the elisp shell that works everywhere
       ;;shell             ; simple shell REPL for Emacs
       ;;term              ; basic terminal emulator for Emacs
       vterm             ; the best terminal emulation in Emacs

       :checkers
       syntax              ; tasing you for every semicolon you forget
       ;;spell             ; tasing you for misspelling mispelling
       ;;grammar           ; tasing grammar mistake every you make

       :tools
       ;;ansible
       ;;debugger          ; FIXME stepping through code, to help you add bugs
       ;;direnv
       ;;docker
       ;;editorconfig      ; let someone else argue about tabs vs spaces
       ;;ein               ; tame Jupyter notebooks with emacs
       (eval +overlay)     ; run code, run (also, repls)
       ;;gist              ; interacting with github gists
       lookup              ; navigate your code and its documentation
       lsp
       magit               ; a git porcelain for Emacs
       ;;make              ; run make tasks from Emacs
       ;;pass              ; password manager for nerds
       ;;pdf               ; pdf enhancements
       ;;prodigy           ; FIXME managing external services & code builders
       ;;rgb               ; creating color strings
       ;;taskrunner        ; taskrunner for all your projects
       ;;terraform         ; infrastructure as code
       ;;tmux              ; an API for interacting with tmux
       ;;upload            ; map local to remote projects via ssh/ftp

       :os
       (:if IS-MAC macos)  ; improve compatibility with macOS
       ;;tty               ; improve the terminal Emacs experience

       :lang
       ;;agda              ; types of types of types of types...
       ;;cc                ; C/C++/Obj-C madness
       ;;clojure           ; java with a lisp
       ;;common-lisp       ; if you've seen one lisp, you've seen them all
       ;;coq               ; proofs-as-programs
       ;;crystal           ; ruby at the speed of c
       ;;csharp            ; unity, .NET, and mono shenanigans
       ;;data              ; config/data formats
       ;;(dart +flutter)   ; paint ui and not much else
       ;;elixir            ; erlang done right
       ;;elm               ; care for a cup of TEA?
       emacs-lisp          ; drown in parentheses
       ;;erlang            ; an elegant language for a more civilized age
       ;;ess               ; emacs speaks statistics
       ;;faust             ; dsp, but you get to keep your soul
       ;;fsharp            ; ML stands for Microsoft's Language
       ;;fstar             ; (dependent) types and (monadic) effects and Z3
       ;;gdscript          ; the language you waited for
       ;;(go +lsp)         ; the hipster dialect
       ;;(haskell +dante)  ; a language that's lazier than I am
       ;;hy                ; readability of scheme w/ speed of python
       ;;idris             ; a language you can depend on
       (json +lsp)             ; At least it ain't XML
       ;;(java +meghanada) ; the poster child for carpal tunnel syndrome
       (javascript +lsp)        ; all(hope(abandon(ye(who(enter(here))))))
       ;;julia             ; a better, faster MATLAB
       ;;kotlin            ; a better, slicker Java(Script)
       ;;latex             ; writing papers in Emacs has never been so fun
       ;;lean
       ;;factor
       ;;ledger            ; an accounting system in Emacs
       ;;lua               ; one-based indices? one-based indices
       markdown          ; writing docs for people to ignore
       ;;nim               ; python + lisp at the speed of c
       ;;nix               ; I hereby declare "nix geht mehr!"
       ;;ocaml             ; an objective camel
       org               ; organize your plain life in plain text
       ;;php               ; perl's insecure younger brother
       ;;plantuml          ; diagrams for confusing people more
       ;;purescript        ; javascript, but functional
       ;;python            ; beautiful is better than ugly
       ;;qt                ; the 'cutest' gui framework ever
       ;;racket            ; a DSL for DSLs
       ;;raku              ; the artist formerly known as perl6
       rest              ; Emacs as a REST client
       ;;rst               ; ReST in peace
       ;;(ruby +rails)     ; 1.step {|i| p "Ruby is #{i.even? ? 'love' : 'life'}"}
       ;;rust              ; Fe2O3.unwrap().unwrap().unwrap().unwrap()
       ;;scala             ; java, but good
       ;;scheme            ; a fully conniving family of lisps
       sh                ; she sells {ba,z,fi}sh shells on the C xor
       ;;sml
       ;;solidity          ; do you need a blockchain? No.
       ;;swift             ; who asked for emoji variables?
       ;;terra             ; Earth and Moon in alignment for performance.
       (web +lsp)               ; the tubes
       yaml              ; JSON, but readable

       :email
       ;;(mu4e +gmail)
       ;;notmuch
       ;;(wanderlust +gmail)

       :app
       ;;calendar
       ;;irc               ; how neckbeards socialize
       ;;(rss +org)        ; emacs as an RSS reader
       ;;twitter           ; twitter client https://twitter.com/vnought

       :config
       ;;literate
       (default +bindings +smartparens))
</pre></details>

**Comment by SebastienWae** [comment]
When the `+lsp` flag is enabled for `javascript` the completion is handled by the lsp server instead of  `tide`, have you installed the `typescript-language-server`?
`npm i -g typescript-language-server; npm i -g typescript`
https://emacs-lsp.github.io/lsp-mode/page/lsp-typescript/

**Comment by osenvosem** [comment]
@SebastienWae yes, I have installed the language server and completion works in .js, .jsx, .tsx files.

**Comment by SebastienWae** [comment]
Is this an issue for all your .ts files? have you tried with an other project?

Do you have any other errors in your `*Messages*` buffer beside `No completion found`? and your `*lsp-log*` buffer?
You can also check the value of `company-backends` (`SPC h v company-backends`)

And finally you can call `lsp-toggle-trace-io` to check if the completions requests/responses are working.

**Comment by osenvosem** [comment]
> Is this an issue for all your .ts files? have you tried with an other project?
No, not for all .ts files, for some of them it works but I do not see any reason yet.

> Do you have any other errors in your *Messages* buffer beside No completion found? 
This is what I have when starting the editor from scratch and open the file with issues.

*Messages*
<details><pre>
Loading /Users/serg/Dropbox/appdata/.config/doom.d/.local/cache/recentf...done
Note: typescript-indent-level, tab-width, evil-shift-width adjusted to 4
LSP :: Guessed project root is ~/Documents/Projects/ufr-izk-ui
LSP :: Connected to [ts-ls:17020 status:starting][eslint:17021 status:starting].
LSP :: ts-ls:17020 initialized successfully
LSP :: eslint:17021 initialized successfully
</pre></details>

*lsp-log*
<details><pre>
Command "/var/folders/1t/d2tthcgx6pqd831qg5nbc5vm0000gn/T/fnm_multishell_42728_1604507206760/bin/typescript-language-server --tsserver-path /Users/serg/Documents/Projects/ufr-izk-ui/node_modules/.bin/tsserver --stdio" is present on the path.
Command "/var/folders/1t/d2tthcgx6pqd831qg5nbc5vm0000gn/T/fnm_multishell_42728_1604507206760/bin/typescript-language-server --tsserver-path /Users/serg/Documents/Projects/ufr-izk-ui/node_modules/.bin/tsserver --stdio" is present on the path.
Found the following clients for /Users/serg/Documents/Projects/ufr-izk-ui/src/configure-store.ts: (server-id eslint, priority -1), (server-id ts-ls, priority -2)
The following clients were selected based on priority: (server-id ts-ls, priority -2), (server-id eslint, priority -1)
ESLint server running in node v14.2.0
Creating watch for /Users/serg/Documents/dev/node-sandbox
Creating watch for /Users/serg/Documents/dev/node-sandbox/.log
Creating watch for /Users/serg/Documents/dev/node-sandbox/src
Creating watch for //Users/serg/Documents/Projects/ufr-izk-ui
Creating watch for //Users/serg/Documents/Projects/ufr-izk-ui/.build
Creating watch for //Users/serg/Documents/Projects/ufr-izk-ui/.build/assets
Creating watch for //Users/serg/Documents/Projects/ufr-izk-ui/.build/assets/static
Creating watch for //Users/serg/Documents/Projects/ufr-izk-ui/.build/assets/static/media
Creating watch for //Users/serg/Documents/Projects/ufr-izk-ui/.log
Creating watch for //Users/serg/Documents/Projects/ufr-izk-ui/__tests__
Creating watch for //Users/serg/Documents/Projects/ufr-izk-ui/config
Creating watch for //Users/serg/Documents/Projects/ufr-izk-ui/coverage
Creating watch for //Users/serg/Documents/Projects/ufr-izk-ui/src
Creating watch for //Users/serg/Documents/Projects/ufr-izk-ui/src/components
Creating watch for //Users/serg/Documents/Projects/ufr-izk-ui/src/components/AlreadyClientPage
Creating watch for //Users/serg/Documents/Projects/ufr-izk-ui/src/components/AlreadyClientPage/images
Creating watch for //Users/serg/Documents/Projects/ufr-izk-ui/src/components/ApplicationDownloadPage
Creating watch for //Users/serg/Documents/Projects/ufr-izk-ui/src/components/ChangeServicePackagePage
Creating watch for //Users/serg/Documents/Projects/ufr-izk-ui/src/components/ChangeServicePackagePage/components
Creating watch for //Users/serg/Documents/Projects/ufr-izk-ui/src/components/ChangeServicePackagePage/components/CardListItem
Creating watch for //Users/serg/Documents/Projects/ufr-izk-ui/src/components/ChangeServicePackagePage/components/CardToCloseListItem
Creating watch for //Users/serg/Documents/Projects/ufr-izk-ui/src/components/ChangeServicePackagePage/components/TermListItem
Creating watch for //Users/serg/Documents/Projects/ufr-izk-ui/src/components/ClientLandingPage
Creating watch for //Users/serg/Documents/Projects/ufr-izk-ui/src/components/ClientLandingPage/components
Creating watch for //Users/serg/Documents/Projects/ufr-izk-ui/src/components/ClientLandingPage/components/BenefitsListItem
Creating watch for //Users/serg/Documents/Projects/ufr-izk-ui/src/components/ClientLandingPage/images
Creating watch for //Users/serg/Documents/Projects/ufr-izk-ui/src/components/Info404
Creating watch for //Users/serg/Documents/Projects/ufr-izk-ui/src/components/LandingPage
Creating watch for //Users/serg/Documents/Projects/ufr-izk-ui/src/components/LandingPage/components
Creating watch for //Users/serg/Documents/Projects/ufr-izk-ui/src/components/LandingPage/components/BenefitsListItem
Creating watch for //Users/serg/Documents/Projects/ufr-izk-ui/src/components/LandingPage/images
Creating watch for //Users/serg/Documents/Projects/ufr-izk-ui/src/components/Root
Creating watch for //Users/serg/Documents/Projects/ufr-izk-ui/src/redux
Creating watch for //Users/serg/Documents/Projects/ufr-izk-ui/src/redux/user
Creating watch for //Users/serg/Documents/Projects/ufr-izk-ui/src/server
Creating watch for //Users/serg/Documents/Projects/ufr-izk-ui/src/server/extensions
Creating watch for //Users/serg/Documents/Projects/ufr-izk-ui/src/server/mocks
Creating watch for //Users/serg/Documents/Projects/ufr-izk-ui/src/server/mocks/documents
Creating watch for //Users/serg/Documents/Projects/ufr-izk-ui/src/server/plugins
Creating watch for //Users/serg/Documents/Projects/ufr-izk-ui/src/server/plugins/api
Creating watch for //Users/serg/Documents/Projects/ufr-izk-ui/src/server/plugins/pages
Creating watch for //Users/serg/Documents/Projects/ufr-izk-ui/src/server/plugins/pages/indexPage
Creating watch for //Users/serg/Documents/Projects/ufr-izk-ui/src/server/public
Creating watch for //Users/serg/Documents/Projects/ufr-izk-ui/src/server/utils
Creating watch for //Users/serg/Documents/Projects/ufr-izk-ui/src/services
Creating watch for //Users/serg/Documents/Projects/ufr-izk-ui/src/utils
Creating watch for /Users/serg/Documents/dev/patterns
Creating watch for /Users/serg/Documents/dev/patterns/.log
Creating watch for /Users/serg/Documents/dev/patterns/build
Creating watch for /Users/serg/Documents/dev/patterns/src
Creating watch for /Users/serg/Documents/dev/patterns/src/1 constructor
Creating watch for /Users/serg/Documents/dev/patterns/src/10 mixin
Creating watch for /Users/serg/Documents/dev/patterns/src/11 decorator
Creating watch for /Users/serg/Documents/dev/patterns/src/12 flyweight
Creating watch for /Users/serg/Documents/dev/patterns/src/2 module
Creating watch for /Users/serg/Documents/dev/patterns/src/3 singleton
Creating watch for /Users/serg/Documents/dev/patterns/src/4 observer
Creating watch for /Users/serg/Documents/dev/patterns/src/5 mediator
Creating watch for /Users/serg/Documents/dev/patterns/src/6 prototype
Creating watch for /Users/serg/Documents/dev/patterns/src/7 command
Creating watch for /Users/serg/Documents/dev/patterns/src/8 facade
Creating watch for /Users/serg/Documents/dev/patterns/src/9 factory
Creating watch for /Users/serg/Documents/Projects/ufr-izk-ui
Creating watch for /Users/serg/Documents/Projects/ufr-izk-ui/.build
Creating watch for /Users/serg/Documents/Projects/ufr-izk-ui/.build/assets
Creating watch for /Users/serg/Documents/Projects/ufr-izk-ui/.build/assets/static
Creating watch for /Users/serg/Documents/Projects/ufr-izk-ui/.build/assets/static/media
Creating watch for /Users/serg/Documents/Projects/ufr-izk-ui/.log
Creating watch for /Users/serg/Documents/Projects/ufr-izk-ui/__tests__
Creating watch for /Users/serg/Documents/Projects/ufr-izk-ui/config
Creating watch for /Users/serg/Documents/Projects/ufr-izk-ui/coverage
Creating watch for /Users/serg/Documents/Projects/ufr-izk-ui/src
Creating watch for /Users/serg/Documents/Projects/ufr-izk-ui/src/components
Creating watch for /Users/serg/Documents/Projects/ufr-izk-ui/src/components/AlreadyClientPage
Creating watch for /Users/serg/Documents/Projects/ufr-izk-ui/src/components/AlreadyClientPage/images
Creating watch for /Users/serg/Documents/Projects/ufr-izk-ui/src/components/ApplicationDownloadPage
Creating watch for /Users/serg/Documents/Projects/ufr-izk-ui/src/components/ChangeServicePackagePage
Creating watch for /Users/serg/Documents/Projects/ufr-izk-ui/src/components/ChangeServicePackagePage/components
Creating watch for /Users/serg/Documents/Projects/ufr-izk-ui/src/components/ChangeServicePackagePage/components/CardListItem
Creating watch for /Users/serg/Documents/Projects/ufr-izk-ui/src/components/ChangeServicePackagePage/components/CardToCloseListItem
Creating watch for /Users/serg/Documents/Projects/ufr-izk-ui/src/components/ChangeServicePackagePage/components/TermListItem
Creating watch for /Users/serg/Documents/Projects/ufr-izk-ui/src/components/ClientLandingPage
Creating watch for /Users/serg/Documents/Projects/ufr-izk-ui/src/components/ClientLandingPage/components
Creating watch for /Users/serg/Documents/Projects/ufr-izk-ui/src/components/ClientLandingPage/components/BenefitsListItem
Creating watch for /Users/serg/Documents/Projects/ufr-izk-ui/src/components/ClientLandingPage/images
Creating watch for /Users/serg/Documents/Projects/ufr-izk-ui/src/components/Info404
Creating watch for /Users/serg/Documents/Projects/ufr-izk-ui/src/components/LandingPage
Creating watch for /Users/serg/Documents/Projects/ufr-izk-ui/src/components/LandingPage/components
Creating watch for /Users/serg/Documents/Projects/ufr-izk-ui/src/components/LandingPage/components/BenefitsListItem
Creating watch for /Users/serg/Documents/Projects/ufr-izk-ui/src/components/LandingPage/images
Creating watch for /Users/serg/Documents/Projects/ufr-izk-ui/src/components/Root
Creating watch for /Users/serg/Documents/Projects/ufr-izk-ui/src/redux
Creating watch for /Users/serg/Documents/Projects/ufr-izk-ui/src/redux/user
Creating watch for /Users/serg/Documents/Projects/ufr-izk-ui/src/server
Creating watch for /Users/serg/Documents/Projects/ufr-izk-ui/src/server/extensions
Creating watch for /Users/serg/Documents/Projects/ufr-izk-ui/src/server/mocks
Creating watch for /Users/serg/Documents/Projects/ufr-izk-ui/src/server/mocks/documents
Creating watch for /Users/serg/Documents/Projects/ufr-izk-ui/src/server/plugins
Creating watch for /Users/serg/Documents/Projects/ufr-izk-ui/src/server/plugins/api
Creating watch for /Users/serg/Documents/Projects/ufr-izk-ui/src/server/plugins/pages
Creating watch for /Users/serg/Documents/Projects/ufr-izk-ui/src/server/plugins/pages/indexPage
Creating watch for /Users/serg/Documents/Projects/ufr-izk-ui/src/server/public
Creating watch for /Users/serg/Documents/Projects/ufr-izk-ui/src/server/utils
Creating watch for /Users/serg/Documents/Projects/ufr-izk-ui/src/services
Creating watch for /Users/serg/Documents/Projects/ufr-izk-ui/src/utils
</pre></details>

It seems like LSP actually works, at least I see errors
![Screenshot 2020-11-06 at 09 28 06](https://user-images.githubusercontent.com/6762673/98333730-720eba00-2012-11eb-86b0-900982e83f22.jpg)

**Comment by SebastienWae** [comment]
This is an issue with `lsp-mode` not enabling `lsp-completion-mode` when multiple servers are used at the same time. [emacs-lsp/lsp-mode/issues#2244](https://github.com/emacs-lsp/lsp-mode/issues/2244)

Luckily this was fixed a few hours ago. [emacs-lsp/lsp-mode/commit#bd5c782](https://github.com/emacs-lsp/lsp-mode/commit/bd5c782cbecddde88c9e054b53a3db745fb6d8d7)

So you can either pin the new commit `(package! lsp-mode :pin "bd5c782cbecddde88c9e054b53a3db745fb6d8d7")` then run `doom sync -u` or make a hook to enable `lsp-completion-mode` automatically until Doom update its pinned commit for `lsp-mode`. (you should probably leave this issue open so @hlissner sees it, or even better send a PR yourself)

**Comment by osenvosem** [comment]
Thank you for your help.

**Comment by hlissner** [comment]
As of aa02dc1 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by shackra** [comment]
somehow I'm experiencing this.

```
generated    may 14, 2021 21:45:12
distro       "Arch Linux" Linux 5.11.16-arch1-1 x86_64
emacs        28.0.50 master a9fc30e6c ~/.emacs.d/ -> ~/.emacs.d/
doom         2.0.9 HEAD -> develop e68c83fd4 2021-05-03 13:27:20 -0400 ~/.doom.d/ -> ~/.doom.d/
shell        /bin/zsh
features     ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GPM HARFBUZZ JPEG JSON LCMS2 LIBOTF LIBSYSTEMD LIBXML2 M17N_FLT MODULES NATIVE_COMP NOTIFY INOTIFY PDUMPER PNG RSVG SECCOMP SOUND THREADS TIFF TOOLKIT_SCROLL_BARS X11 XDBE XIM XPM XWIDGETS GTK3 ZLIB
traits       gui server-running envvar-file custom-file byte-compiled-config
custom       safe-local-variable-values custom-safe-themes
modules      :completion (company +childframe) (ivy +childframe +prescient +icons) :ui doom doom-dashboard doom-quit hl-todo hydra (ligatures +fira +extra) modeline nav-flash ophints (popup +defaults) treemacs unicode vc-gutter vi-tilde-fringe window-select workspaces (&nopath tree-sitter) :editor file-templates fold (&nopath reformat) lispy multiple-cursors snippets :emacs dired electric undo vc :term vterm :checkers syntax (spell +flyspell) grammar :tools (eval +overlay) lookup (lsp +peek) magit pdf :lang data (dart +flutter +lsp) emacs-lisp (gdscript +lsp) (go +lsp) json (javascript +lsp) (latex +lsp) markdown (org +dragndrop +pretty +noter +pomodoro +present) (python +lsp) (rust +lsp) (sh +lsp) (web +lsp) yaml (&nopath rego) (&nopath pkgbuild) (&nopath nginx) :email mu4e :config literate (default +bindings +jorge)
packages     (hungry-delete :recipe (:host github :repo nflath/hungry-delete) :pin 0513152525c38519a5597db2d6495b56dd9cc3f0) (rego-mode :recipe (:host github :repo psibi/rego-mode) :pin be110e6cef5d34eef0529a8739c68e619cf15310 :disable (not (featurep! :lang rego))) (highlight-escape-sequences :recipe (:host github :repo dgutov/highlight-escape-sequences) :pin fae976568c04b6fe8a9f2d854c8fe23b357a6878) (pkgbuild-mode :recipe (:host github :repo juergenhoetzel/pkgbuild-mode) :pin 8a5e95c8514315cb40c47f1acdb68a4ace921497 :disable (not (featurep! :lang pkgbuild))) (tree-sitter :recipe (:host github :repo ubolonton/emacs-tree-sitter :files (lisp/*.el (:exclude lisp/tree-sitter-tests.el))) :pin 3a600d769bd5da95bf46bec58893934370c6c04f :disable (not (functionp 'module-load))) (tree-sitter-langs :recipe (:host github :repo ubolonton/tree-sitter-langs :files (*.el queries/)) :pin 5d362ce98dcf656d7a55fcad6ae21c0a2caca861 :disable (not (functionp 'module-load))) (tsc :recipe (:host github :repo ubolonton/emacs-tree-sitter :files (core/*.el core/Cargo.toml core/Cargo.lock core/src)) :pin 3a600d769bd5da95bf46bec58893934370c6c04f :disable (not (functionp 'module-load))) (nginx-mode :recipe (:host github :repo ajc/nginx-mode :files (*.el)) :pin a2bab83c2eb233d57d76b236e7c141c2ccc97005) (apheleia :recipe (:host github :repo raxod502/apheleia :files (apheleia.el)) :pin 87115f5cda2a6c0653fc0ac69bbbc7d39a253f11)
```

**Comment by hlissner** [comment]
@shackra Please create a new issue.
