### ISSUE TITLE
Default emacs theme

### ISSUE THREAD

**Issue by AlexDaniel** [hlissner/doom-emacs#4214]
In emacs, I use the default dark theme, which I really like. When switching to doom emacs I was unable to find a way to use the exact same theme, and honestly I couldn't find an alternative that looks similarly or as good. Perhaps it's a good idea to have a theme with similar/same colors?

FWIW, there was a similar issue in spacemacs and people seemed to have a lot of interest in it: https://github.com/syl20bnr/spacemacs/issues/4723

**Comment by hlissner** [comment]
As of 03b0a83 you can set `doom-theme` to `'default`. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by AlexDaniel** [comment]
It works, thanks! That was fantastically quick :)

That said, I'm not entirely sure if using no theme at all is the best option for doom emacs. For syntax highlighting it works great, but any other element (that emacs doesn't have by default) can be miscolored.

For example, here's how it now looks when the window is not in focus:
![image](https://user-images.githubusercontent.com/5507503/98184950-4ad1c300-1f14-11eb-8392-73938aa13a2e.png)


That looks perfect to me. However, here's code completion:

![image](https://user-images.githubusercontent.com/5507503/98185000-62a94700-1f14-11eb-9e32-a1c2cfa36260.png)

And here's the modeline when the window is in focus:

![image](https://user-images.githubusercontent.com/5507503/98185056-81a7d900-1f14-11eb-8816-540f2d6329ec.png)

Both are lacking some contrast (a bit of fg and bg color mismatch).

I sort of expected this to happen, which is why I filed the ticket against emacs-doom-themes :) Basically, what's needed is a theme with same syntax highlighting colors + some extra color definitions for other elements. That said, I know nothing about emacs themes so please ignore me if it doesn't make sense.
