### ISSUE TITLE
Csharp autocompletion

### ISSUE THREAD

**Issue by bondzula** [hlissner/doom-emacs#422]
### Observed behavior

After writing few characters and invoking `<C-Space>` I get `No completions found`, then after writing something like `Console.` i get a different error, saying `Wrong type argument: hash-table-p, nil`. Invoking `M-x company-omnisharp` returns `Cannot complete at point`. My first thought was that it's server problem because omnisharp-roslyn doesn' support Arch Linux, however, omnisharp functions work perfectly fine and running `M-x omnisharp-check-alive-status` returns `Server is alive and well. Happy coding!` and `M-x omnisharp-add-dot-and-auto-complete` returns a autocomplete pop-up with a prompt

![2018-02-16_125124_919579880](https://user-images.githubusercontent.com/18123522/36306478-2efc51fa-1318-11e8-9ba9-05cafbdd2a0a.png)

### Expected behavior

Normal company autocompletion :)

### Steps to reproduce

1. Download and extract [omnisharp-roslyn](https://github.com/OmniSharp/omnisharp-roslyn/releases)
2. Point to server executable with `(after! omnisharp
  (setq omnisharp-server-executable-path "~/omnisharp/run"))`
3. Open `.cs` file and start omnisharp-server

### System information

<details>
<summary>Click to expand</summary>

```
DOOM Doctor
Running Emacs v25.3.1, commit 5dacbb7cb1c6ac246a9ccd15e6c4290def67757c

shell: /usr/bin/zsh
Compiled with:
  XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS
  NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB
  TOOLKIT_SCROLL_BARS GTK3 X11 MODULES
uname -a:
  Linux shittywok 4.15.3-1-ARCH #1 SMP PREEMPT Mon Feb 12 23:01:17 UTC
  2018 x86_64 GNU/Linux

Attempt to load DOOM: success! Loaded v2.0.9
Revision 5dacbb7cb1c6ac246a9ccd15e6c4290def67757c

----

test-emacs
test-windows
test-fonts
Found font material-design-icons.ttf
Found font weathericons.ttf
Found font octicons.ttf
Found font fontawesome.ttf
Found font file-icons.ttf
Found font all-the-icons.ttf
test-gnutls
test-tls
Validated https://elpa.gnu.org
Validated https://melpa.org
Successfully rejected https://self-signed.badssl.com
Successfully rejected https://wrong.host.badssl.com/
test-tar
Everything seems fine, happy Emacs’ing!
```

**Comment by hlissner** [comment]
> because omnisharp-roslyn doesn't support Arch Linux

It's odd you say that. I use roslyn on Arch Linux without problem.

----

Would you mind trying out `develop`? I've made a number of changes to the lang/csharp module. Unfortunately, complications in the upcoming release have delayed the merge into master, so we're in an odd limbo where `develop` is more stable than `master`.

**Comment by hlissner** [comment]
Oh, I should mention, if you try `develop`, you should re-copy `init.example.el` -- there have been a couple changes.

**Comment by bondzula** [comment]
Okej, I switched to `develop` branch and re-copied `init.example.el` like you suggested. Company autocompletion now works perfectly fine, however, I had few minor issues. 
Mainly if I set `omnisharp-server-executable-path` to my custom folder, I get `Omnisharp server isn't installed, completion won't work` even tho I'm able to start the server and completion does work. And this is because it checks `omnisharp--server-installation-path`.
So I did try to use `omnisharp-install-server` witch froze my laptop, and forced me to reboot, but this is probably a bug with `omnisharp` package.
Ultimately I manually extracted omnisharp-roslyn to `~/.emacs.d/.local/cache/omnisharp/server/v1.26.3/` witch fixed the issue. 
I do have a question tho, where do you recommend we keep private config files, `~/.doom.d/`, `~/.config/doom`, `~/.emacs.d/modules/private/` or `~/.emacs.d/modules/config/private`, also does this project have slack, discord, irc, matrix or gitter channel?

**Comment by hlissner** [comment]
> does this project have slack, discord, irc, matrix or gitter channel?

We have a discord server: https://discord.gg/bcZ6P3y

> Mainly if I set omnisharp-server-executable-path to my custom folder, I get Omnisharp server isn't installed ... this is because it checks omnisharp--server-installation-path.

I've discovered why this happens; 8af46aa should fix this issue.
