### ISSUE TITLE
+org/toggle-last-clock raises an error when run with no clock setup

### ISSUE THREAD

**Issue by offbyone** [hlissner/doom-emacs#4220]
**What did you expect to happen?**
whatever `+org/toggle-last-clock` is supposed to do. I don't actually know, I only hit the key accidentally :)

**What actually happened?**
```
Debugger entered--Lisp error: (void-function org-clocking-p)
```

**Additional details:**

<details><pre>
  (org-clocking-p)
  (cond ((org-clocking-p) (if arg (org-clock-cancel) (org-clock-out))) ((and (null org-clock-history) (or (org-on-heading-p) (org-at-item-p)) (y-or-n-p "No active clock. Clock in on current item?")) (org-clock-in)) ((org-clock-in-last arg)))
  +org/toggle-last-clock(nil)
  funcall-interactively(+org/toggle-last-clock nil)
  call-interactively(+org/toggle-last-clock nil nil)
  command-execute(+org/toggle-last-clock)
</pre></details>

**Steps to reproduce:**
1. Select these example steps,
2. Delete them,
3. And replace them with precise steps to reproduce your issue.
4. Fill in "system information" below.

**System information:**
<details><pre>
SYSTEM  type       darwin
        config     x86_64-apple-darwin19.6.0
        shell      /bin/bash
        uname      Darwin 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64
        path       (~/.emacs.d/bin/ ~/.pyenv/shims /usr/local/bin /usr/bin /bin /usr/sbin /sbin /Library/Apple/usr/bin /Library/Frameworks/Mono.framework/Versions/Current/Commands /Library/TeX/texbin ~/.local/bin ~/.cargo/bin ~/work/go/bin ~/.emacs.d/bin ~/git-scripts ~/extensions/git-cal ~/extensions/git-flow ~/extensions/git-hg ~/extensions/git-hooks ~/extensions/git-hub ~/extensions/git-remote-hg /usr/local/Cellar/emacs-head@27/27.1_1/libexec/emacs/27.1/x86_64-apple-darwin19.6.0/)
EMACS   dir        ~/.emacs.d/
        version    27.1
        build      Oct 10, 2020
        buildopts  --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-head@27/27.1_1/share/info/emacs --prefix=/usr/local/Cellar/emacs-head@27/27.1_1 --without-x --without-dbus --with-imagemagick --with-modules --with-gnutls --with-rsvg --with-xml2 --with-ns --disable-ns-self-contained --with-harfbuzz
        features   RSVG IMAGEMAGICK GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS JSON PDUMPER LCMS2 GMP
        traits     (server-running envvar-file)
DOOM    dir        ~/.doom.d/
        version    2.0.9
        build      HEAD -> develop, upstream/develop, upstream/HEAD, origin/develop 03b0a834d 2020-11-04 19:49:35 -0500
        elc-files  0
        modules    (:completion company (helm +fuzzy) :ui doom doom-dashboard doom-quit fill-column hl-todo hydra minimap modeline ophints (popup +defaults) unicode vc-gutter vi-tilde-fringe window-select workspaces :editor file-templates fold (format +onsave) snippets :emacs dired electric ibuffer undo vc :checkers syntax :tools ansible direnv docker editorconfig (eval +overlay) gist lookup lsp magit make terraform tmux :os macos :lang emacs-lisp (go +lsp) json (java +lsp) javascript kotlin markdown (org +brain +journal +pandoc +pretty +present +roam) plantuml (python +lsp +poetry +pyenv) (ruby +rails) rust sh web yaml :config (default +bindings +smartparens))
        packages   ((git-auto-commit-mode) (windmove) (chezmoi :recipe (:host github :repo tuh8888/chezmoi.el)) (csv-mode))
        unpin      (n/a)
        elpa       (n/a)
</pre></details>

**Comment by hlissner** [comment]
As of 68b1594 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
