### ISSUE TITLE
consider extracting doom-hide-modeline-mode to its own package

### ISSUE THREAD

**Issue by waymondo** [hlissner/doom-emacs#423]
I am married to my own hand-rolled emacs setup, but I stumbled upon doom-emacs and I'm really impressed with a lot of your ideas and features. 

Would you consider extracting doom-hide-modeline-mode to its own package on MELPA? A defacto minor mode package for hiding the mode-line for certain modes seems like a useful feature to emacs users beyond only doom-emacs users.

**Comment by hlissner** [comment]
I could've sworn there _was_ one on MELPA, but it seems I misremembered. Sure, I can do that. It'll take a while to get to it though; around two weeks I'm guessing, while I deal with other commitments.

**Comment by hlissner** [comment]
Alright, it is now [in its own repo](https://github.com/hlissner/emacs-hide-mode-line) and [submitted to MELPA](https://github.com/melpa/melpa/pull/5344).

I'll keep this open until it's been accepted.

**Comment by hlissner** [comment]
And it's been merged! So I'll consider this resolved.
