### ISSUE TITLE
Cannot switch to the help window

### ISSUE THREAD

**Issue by searene** [hlissner/doom-emacs#4232]
**Steps to reproduce:**
1. Open Emacs
2. `C-h f setq <Enter>` to open the help window
3. `C-x o` to jump to the original window, no problem.
4. `C-x o` to jump back to the help window, an error is shown: `No other window to select`, and the jump failed.

**What did you expect to happen?**
I should be able to switch to the help window by using `C-x o`

**What actually happened?**
"No other window to select" is shown and I'm not able to switch to the help window

**Additional details:**
- Include a link to your private config: https://github.com/searene/demos/tree/master/doom-emacs-config
- Include screenshots/casts of your issue
  
![image](https://user-images.githubusercontent.com/3351317/98443284-5821c400-2145-11eb-8bbe-fb91a0d6fd6c.png)

- If you mention key sequences, include what commands they're bound to: `C-x o` is bound to `other-window`
- Include any warnings or errors logged to \*Messages\*: `No other window to select`

**System information:**
<details><pre>
Place the output of `M-x doom/info` or `~/.emacs.d/bin/doom info` here.
```
SYSTEM  type       gnu/linux
	config     x86_64-pc-linux-gnu
	shell      /bin/bash
	uname      Linux 5.4.74-1-lts #1 SMP Sun, 01 Nov 2020 12:58:27 +0000 x86_64
	path       (~/.emacs.d/bin ~/.yarn/bin ~/apps/VSCode-linux-x64/bin ~/apps/JetBrains/WebStorm-181.5540.11/bin ~/apps/JetBrains/idea-IU-181.5087.20/bin ~/apps/JetBrains/DataGrip-2018.1.5/bin/datagrip.sh ~/apps/JetBrains/pycharm-community-2019.1.3/bin/pycharm.sh ~/apps/JetBrains/android-studio/bin ~/apps/JetBrains/clion-2018.2.1/bin ~/bin ~/.local/bin ~/.yarn/bin ~/apps/VSCode-linux-x64/bin ~/apps/JetBrains/WebStorm-181.5540.11/bin ~/apps/JetBrains/idea-IU-181.5087.20/bin ~/apps/JetBrains/DataGrip-2018.1.5/bin/datagrip.sh ~/apps/JetBrains/pycharm-community-2019.1.3/bin/pycharm.sh ~/apps/JetBrains/android-studio/bin ~/apps/JetBrains/clion-2018.2.1/bin ~/bin ~/.local/bin /opt/google-cloud-sdk/bin /usr/local/bin /usr/bin /bin /usr/local/sbin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl ~/Android/Sdk/tools ~/Android/Sdk/tools/bin ~/Android/Sdk/platform-tools ~/.npm/bin ~/apps/gradle-5.4.1/bin ~/apps ~/Android/Sdk/tools ~/Android/Sdk/tools/bin ~/Android/Sdk/platform-tools ~/.npm/bin ~/apps/gradle-5.4.1/bin ~/apps /usr/lib/emacs/27.1/x86_64-pc-linux-gnu)
EMACS   dir        ~/.emacs.d/
	version    27.1
	build      Aug 29, 2020
	buildopts  --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-wide-int --with-modules --with-cairo --with-harfbuzz 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
	features   XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP
	traits     (batch server-running envvar-file)
DOOM    dir        ~/.doom.d/
	version    2.0.9
	build      grafted, HEAD -> develop, origin/develop, origin/HEAD 92c9127 2020-11-07 00:20:07 -0500
	elc-files  0
	modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline ophints (popup +defaults) vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold snippets :emacs dired electric undo vc :checkers syntax :tools (eval +overlay) lookup magit :lang emacs-lisp markdown org sh :config (default +bindings +smartparens))
	packages   (n/a)
	unpin      (n/a)
	elpa       (n/a)
```

</pre></details>

**Comment by innerout** [comment]
This bug also affects emacs 28 native-comp. I guess it is not version-specific but something in the doom core.

**Comment by searene** [comment]
By the way, it works correctly in vanilla Emacs(Starting with `Emacs -Q`). I can switch between the main window and the help window correctly in vanilla Emacs.

**Comment by innerout** [comment]
Doom is using the helpful package so you can't reproduce it in vanilla.

**Comment by jethrokuan** [comment]
You can use `C-x p` instead to switch to that window, I think it's a popup in Doom's packaging.

**Comment by innerout** [comment]
@jethrokuan `C-x p` Works as expected!

**Comment by hlissner** [comment]
This is not a bug. Popup windows are [intentionally given a non-nil `no-other-window` property](https://github.com/hlissner/doom-emacs/blob/develop/modules/ui/popup/config.el#L20) which prevents `other-window` and its ilk from selecting it. This is to prevent Emacs from unwittingly using those popups to display new buffers (e.g. with `find-file-other-window` or `emacsclient`).

Using `C-x p` (`+popup/other` or `other-popup`) or the `windmove-{left,down,up,right}` commands (or `evil-window-{left,down,up,right}` for evil users, on `C-w {h,j,k,l}`) are the correct way to focus them.
