### ISSUE TITLE
Company: backend company-capf error "Symbol’s function definition is void: :interrupted" with args (candidates en)"

### ISSUE THREAD

**Issue by forrestchang** [hlissner/doom-emacs#4235]
**What did you expect to happen?**
Autocomplete with company in golang-mode.

**What actually happened?**
```
Company: An error occurred in auto-begin
Company: backend company-capf error "Symbol’s function definition is void: :interrupted" with args (candidates en)
```

**Additional details:**

Debug info:

```
Debugger entered--Lisp error: (void-function :interrupted)
  :interrupted(nil)
  #f(compiled-function () #<bytecode 0x13bdf89a1b259968>)()
  #f(compiled-function (probe pred action) #<bytecode -0x1dc8157e961d9f95>)("if" nil t)
  all-completions("if" #f(compiled-function (probe pred action) #<bytecode -0x1dc8157e961d9f95>) nil)
  completion-pcm--all-completions("" ("if" point) #f(compiled-function (probe pred action) #<bytecode -0x1dc8157e961d9f95>) nil)
  completion-basic-all-completions("if" #f(compiled-function (probe pred action) #<bytecode -0x1dc8157e961d9f95>) nil 2)
  #f(compiled-function (style) #<bytecode 0x19180d370858de01>)(basic)
  completion--some(#f(compiled-function (style) #<bytecode 0x19180d370858de01>) (basic partial-completion emacs22))
  completion--nth-completion(2 "if" #f(compiled-function (probe pred action) #<bytecode -0x1dc8157e961d9f95>) nil 2 (metadata (category . lsp-capf) (display-sort-function . identity)))
  completion-all-completions("if" #f(compiled-function (probe pred action) #<bytecode -0x1dc8157e961d9f95>) nil 2 (metadata (category . lsp-capf) (display-sort-function . identity)))
  company-capf--candidates("if")
  company-capf(candidates "if")
  apply(company-capf (candidates "if"))
  company-call-backend-raw(candidates "if")
  company--fetch-candidates("if")
  company-calculate-candidates("if" nil)
  company--begin-new()
  company--perform()
  company-auto-begin()
  company-idle-begin(#<buffer comment_filter_controller.go> #<window 3 on comment_filter_controller.go> 355 30833)
  apply(company-idle-begin (#<buffer comment_filter_controller.go> #<window 3 on comment_filter_controller.go> 355 30833))
  timer-event-handler([t 24487 25491 981324 nil company-idle-begin (#<buffer comment_filter_controller.go> #<window 3 on comment_filter_controller.go> 355 30833) nil 0])
```

run `company-diag`:

```
Emacs 28.0.50 (x86_64-apple-darwin19.5.0) of 2020-09-17 on C02D316PMD6R
Company 0.9.13

company-backends: (company-capf company-yasnippet)

Used backend: company-capf
Value of c-a-p-f: (lsp-completion-at-point)
Major mode: go-mode
Prefix: ""
Completions: none(error fetching)
```

**Comment by C0DK** [comment]
Same issue in python.

**Comment by C0DK** [comment]
@forrestchang did you solve it?

**Comment by hlissner** [comment]
Did https://github.com/hlissner/doom-emacs/commit/4e7ce478257455f14f82f0ca8d3cce49e5ec73f4 fix this issue?

**Comment by bl1nk** [comment]
Thanks for looking into it! 

> Did [4e7ce47](https://github.com/hlissner/doom-emacs/commit/4e7ce478257455f14f82f0ca8d3cce49e5ec73f4) fix this issue?

I used `M-x doom/upgrade` to upgrade to f7293fb67 which should include 4e7ce47.

```
Doom v2.0.9 (HEAD -> develop f7293fb67 2020-11-11 20:33:27 -0500)
```

It did not fix the issue for me when editing Go.

**Comment by martijnjanssen** [comment]
I'm encountering the same issue with rust-analyzer, just did a `doom-upgrade` but this did not resolve the issue.

**Comment by andkazakov** [comment]
I have the same problem with code completion in python-mode 
`Doom v2.0.9 (HEAD -> develop f7293fb67 2020-11-11 20:33:27 -0500)`

But is fixed after reinstall `lsp-mode`. 
Just remove `lsp` from `init.el` and run `doom sync && doom purge`

**Comment by eryx67** [comment]
> I have the same problem with code completion in python-mode
> `Doom v2.0.9 (HEAD -> develop f7293fb67 2020-11-11 20:33:27 -0500)`
> 
> But is fixed after reinstall `lsp-mode`.
> Just remove `lsp` from `init.el` and run `doom sync && doom purge`

Yes, there is the same problem with other `lsp` dependent modes and reinstalling `lsp` helps.

**Comment by hlissner** [comment]
In that case I'll consider a local byte-compilation error and close this. Perhaps some stale bytecode that wasn't cleaned up across upgrades. 

Removing `~/.emacs.d/.local/straight/repos/lsp-mode` manually and run `doom sync` appears to be the fix.

**Comment by ccressent** [comment]
A quick note for whoever ends up here after searching for this error: I had exactly the same error as @forrestchang reported, under the following `doom version`:
```
Doom v2.0.9 (HEAD -> develop, origin/develop c83e5e75e 2020-11-21 14:09:08 -0500)
```

@hlissner's suggestion was not enough though and I had to remove `lsp-ui` and `lsp-ivy` on top of `lsp-mode` before issuing a `doom sync`. That fixed the issue. @andkazakov's approach above of removing the lsp module, syncing then re-adding the lsp module is probably the way to go.
