### ISSUE TITLE
Consider bringing back the Perl module

### ISSUE THREAD

**Issue by sarna** [hlissner/doom-emacs#4240]
Hi! I've seen that the Perl module got deprecated in favor of the Raku module. Meanwhile Perl and Raku are more like C and C++, rather than Python 2 and 3. Can we please have the Perl module back?

**Comment by gagbo** [comment]
Quoting Henrik ([Discord link](https://discord.com/channels/406534637242810369/406624667496087572/718533488315203714)) :
> I mean, there's no perl5 config at all in Doom. So there'd be nothing to put in the supposed, new :lang perl module.

I don't think there's any bias against bringing *back* a perl5 module, since apparently there were not really any to begin with

**Comment by sarna** [comment]
Oh, hmm. The previous module had "adds support for Perl 6, and flycheck support for all versions of Perl" in the description. In #3308 the description changed, but the packages did not. That's kinda confusing.

But yeah, if we don't have anything that could be brought back - this issue is invalid. Sorry for the fuss :)
