### ISSUE TITLE
Setting doom local leader key to "," conflicts with evil-snipe

### ISSUE THREAD

**Issue by pspencil** [hlissner/doom-emacs#4242]
**What did you expect to happen?**
local leader taking priority over other keymaps.

I found [this issue](https://github.com/hlissner/doom-emacs/issues/4231) but the symptom here isn't exactly the same.

**What actually happened?**
When I press `,` in normal mode, I got "nothing to repeat". I tried `SPC h k` and it is still bound to `evil-snipe-repeat-reverse`

**Additional details:**
- Include a link to your private config: 
  - [here](https://github.com/pspencil/doom.d) I commented out the line setting the loca lleader.
- Include screenshots/casts of your issue
- If you mention key sequences, include what commands they're bound to (use `SPC
  h k KEY` or `C-h h k KEY` to inspect keys).
- Include any warnings or errors logged to \*Messages\* (use `M-x
  view-echo-area-messages` to see it): 
  - It says "nothing to repeat".

<details><pre>
If an error message is involved include a backtrace of it.

How to acquire a backtrace:
https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#how-to-extract-a-backtrace-from-an-error
</pre></details>

**Steps to reproduce:**
Do `(setq doom-localleader-key ",")`. 
Press `,` in normal mode.j

**System information:**
<details><pre>
```
SYSTEM  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/bash
        uname      Linux 4.19.154-1-MANJARO #1 SMP Fri Oct 30 10:25:08 UTC 2020 x86_64
        path       (~/.emacs.d/bin/ ~/.emacs.d/bin/ ~/.emacs.d/bin/ ~/.emacs.d/bin/ /home/$USERpencil/perl5/bin ~/.local/bin /home/$USERpencil/perl5/bin ~/.local/bin ~/.local/bin /usr/local/bin /usr/bin /bin /usr/local/sbin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /bin /opt/google/chrome/ ~/go/bin ~/matlab/bin ~/.gem/ruby/2.7.0/bin ~/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /bin /opt/google/chrome/ ~/go/bin ~/matlab/bin ~/.gem/ruby/2.7.0/bin ~/bin /usr/lib/emacs/27.1/x86_64-pc-linux-gnu/)
EMACS   dir        ~/.emacs.d/
        version    27.1
        build      Aug 28, 2020
        buildopts  --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-wide-int --with-modules --with-cairo --with-harfbuzz 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
        features   XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP
        traits     (server-running envvar-file)
DOOM    dir        ~/.doom.d/
        version    2.0.9
        build      grafted, HEAD -> develop, origin/develop, origin/HEAD 7205b72 2020-11-06 21:16:04 -0500
        elc-files  0
        modules    (:completion (company +childframe) (ivy +fuzzy +icons) :ui doom doom-dashboard doom-quit fill-column hl-todo (ligatures +extra +hasklig) modeline nav-flash ophints (popup +defaults) vc-gutter vi-tilde-fringe (window-select +numbers) workspaces :editor (evil +everywhere) file-templates fold (format +onsave) multiple-cursors snippets word-wrap :emacs dired electric undo vc :term vterm :checkers syntax :tools (eval +overlay) lookup magit :lang emacs-lisp markdown org sh :config literate (default +bindings +smartparens))
        packages   ((keyfreq) (org-bullets))
        unpin      (n/a)
        elpa       (n/a)
```
</pre></details>

**Comment by pspencil** [comment]
Btw, I also tried unbinding `,` from evil-snipe keymaps and `evil-motion-state-keymaps` but then `,` doesn't seem to be bound to anything.

**Comment by hlissner** [comment]
Add `(setq evil-snipe-override-evil-repeat-keys nil)` to `~/.doom.d/config.el` (not in an `after!` block, it needs to be set before the package loads).

Hope that helps!

**Comment by pspencil** [comment]
Hi, thanks for helping! I tried that and now "," is bound to the normal evil search reverse instead of the local leader.

Here are the relevant config:
```
(setq evil-snipe-override-evil-repeat-keys nil)
(setq doom-localleader-key ",")
(setq doom-localleader-alt-key "M-,")
```

**Comment by pspencil** [comment]
Also, I managed to reproduce this in vanilla doom, + modules, - private config and just entering above 3 lines.

**Comment by pspencil** [comment]
Oh, just to add on to this:

I was testing in my `config.org` which is in org mode, which surprisingly does not have any local keybindings. I tried in elisp mode and settings local leader works as expected. Thanks!

**Comment by betaprior** [comment]
@pspencil this is a bug. Org mode _does_ have local keybinds, which used to work with local leader, and indeed are still available under `SPC m`. This should be reopened.

**Comment by hlissner** [comment]
> Edit: (add-hook! 'org-mode-hook #'+org-init-keybinds-h) fixes this, but this should really work out of the box.

@betaprior I cannot reproduce the issue in vanilla Doom. `+org-init-keybinds-h` is [already on org-load-hook](https://github.com/hlissner/doom-emacs/blob/develop/modules/lang/org/config.el#L1113) and appears to work as intended. Please provide what code you're using to reproduce this.

**Comment by pspencil** [comment]
Note that I observed the behaviour in [above comment](https://github.com/hlissner/doom-emacs/issues/4242#issuecomment-724892885) 10 days ago and it somehow fixes itself. So maybe it got fixed in one of the commits committed recently. 

@betaprior perhaps you can try upgrading the doom?

**Comment by pspencil** [comment]
Related issue: https://github.com/hlissner/doom-emacs/issues/4247

**Comment by betaprior** [comment]
In my system, this appears to be triggered by org-roam.  In particular, having the following code in my config reliably triggers leader-on-comma breakage.  Adding `(add-hook! 'org-mode-hook #'+org-init-keybinds-h) `  at some point after that code block restores correct behavior.

```
(after! org-roam
  (require 'org-roam-protocol)
  (setq org-roam-directory "~/Dropbox/org/roam")
  ;;https://github.com/zaeph/.emacs.d/blob/0f4bf9a500ef6397b93c41cb51602bea9ab9a4c3/init.el#L3804
  ;; [[https://copingmechanism.com/2020/keeping-org-roam-daily-notes-in-a-separate-folder/][Keeping Org-roam Daily Notes in a separate folder – Coping Mechanism]]
  (setq org-roam-dailies-capture-templates '(("d" "daily" plain (function org-roam-capture--get-point) ""
                                              :immediate-finish t
                                              :file-name "dailies/%<%Y-%m-%d>-${slug}"
                                              :head "#+TITLE: %<%Y-%m-%d>-${slug}\n#+created: %u\n#+last_modified: %U\n\n")))
)

(use-package! org-roam-server
  :config
  (setq org-roam-server-port 8091
        org-roam-server-export-inline-images t
        org-roam-server-authenticate nil
        org-roam-server-network-poll t
        org-roam-server-network-arrows nil
        org-roam-server-network-label-truncate t
        org-roam-server-network-label-truncate-length 60
        org-roam-server-network-label-wrap-length 20))
```

I am running a very recent Doom (110d70bdff12c6).

**Comment by tsoernes** [comment]
I have the same issue, I've tried this in my config:
```
(add-hook! 'org-mode-hook #'+org-init-keybinds-h)
(setq evil-snipe-override-evil-repeat-keys nil)
(setq doom-localleader-key ",")
(setq doom-localleader-alt-key "M-,")
```
