### ISSUE TITLE
How I can change C comment style?

### ISSUE THREAD

**Issue by route616** [hlissner/doom-emacs#4244]
By default, Doom Emacs type a next pattern in case beginning comment:
```c
/*
** multi
** line
** comment
*/
```
How I can change comment block style on C default:
```c
/*
 * block
 * comment
 */
```
or:
```c
/**
 * documentation
 * comments
 */
```

**Comment by hlissner** [comment]
I _just_ fixed this earlier today in b96b6ed64. Please update.
