### ISSUE TITLE
When I attempt to open magit, I get 'Symbol's function definition is void: prettier-js-mode'

### ISSUE THREAD

**Issue by cabanabanana** [hlissner/doom-emacs#4250]
**What did you expect to happen?**
When I press SPC-g-g I expect to get the magic status buffer open.

**What actually happened?**
Symbol's function definition is void: prettier-js-mode is printed at the bottom of the emacs window.

**Additional details:**
I have a standard doom config, I have enable vterm, javascript, c, tmux modules.
SPC-g-g to open magit. In other projects, for example a Vanilla JS project, this opens correctly.

In messages, I get the same error as above along with `Doom loaded 198 packages across 39 modules in 0.624s` and `package cl is deprecated`.

**Comment by hlissner** [comment]
Since Doom doesn't install `prettier-js-mode`, this can only be cause by our private config. Make sure you are [installing the package correctly](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#package-management) and have run `doom sync`.
