### ISSUE TITLE
How do I create a new window when opening doom emacs

### ISSUE THREAD

**Issue by Sebastopaul** [hlissner/doom-emacs#4259]
Hello there. So, I just reinstalled everything on my computer (including the OS) and I wanted to reinstall doom emacs, but when I tried to use it, it didn't open in a new window, it opened directly in the terminal instead, just like normal emacs, but with doom emacs configs. I can't understand why nor how to make it work properly... Could somebody help, please ?
Just in case, I'm using Fedora 32, and I installed everything just like the installation guide says, prerequisites included.

**Comment by hlissner** [comment]
Depends on the Emacs package you installed. If you installed `emacs-nox`, you will have a build of Emacs that is incapable of displaying in a GUI window.

+ To run Emacs in the terminal, `emacs -nw`.
+ To launch GUI Emacs you run the command `emacs`.

If running `emacs` opens emacs in the terminal, then you either have a shell alias to remap it (`alias emacs='emacs -nw'`) or you've installed a version of Emacs without graphical support, in which case I cannot help you -- I am not familiar with Fedora or its ecosystem. You'll find more help on the subject on of the following:

+ [Our Discord](https://doomemacs.org/discord)
+ [On r/emacs](https://www.reddit.com/r/emacs/)
+ [On r/orgmode](https://reddit.com/r/orgmode/)
+ [The relevant StackOverflow sites](https://www.emacswiki.org/emacs/EmacsStackExchange)
+ [One of the Emacs IRC channels](https://www.emacswiki.org/emacs/EmacsChannel)
