### ISSUE TITLE
Failing to add private modules

### ISSUE THREAD

**Issue by dariooddenino** [hlissner/doom-emacs#426]
I think I'm missing the last step on how to use private modules. Here's what I've done:

1. Cloned the develop branch.
2. Set the `init.el` file to:
```
(require 'core (concat user-emacs-directory "core/core"))

(doom! :config
        (private +xdg))
```
3. Copied `init.example.el` to a `.config/doom/init.el` without the `private` section of `:config`
4. Ran `make install`
5. Open emacs and everything works like a charm.

Now it's where I'm stuck. I tried creating a simple module called `a` like the one in issue #424.
If I add the module `a` to `.emacs.d/init.el` nothing happens. If I add `(private :private a)` to `.config/doom/init.el` I get a `Recursive load` error:
```
Debugger entered--Lisp error: (error "Recursive load" "/home/dario/.emacs.d/modules/config/private/init.el" "/home/dario/.config/doom/init.el" "/home/dario/.emacs.d/modules/config/private/init.el" "/home/dario/.config/doom/init.el" "/home/dario/.emacs.d/modules/config/private/init.el" "/home/dario/.config/doom/init.el" "/home/dario/.emacs.d/modules/config/private/init.el" "/home/dario/.config/doom/init.el" "/home/dario/.emacs.d/modules/config/private/init.el" "/home/dario/.emacs.d/init.el")
  load("/home/dario/.emacs.d/modules/config/private/init" t nil)
...
```
Thanks :)

**Comment by hlissner** [comment]
When you say you created a module called `a` like in #424, I hope you didn't mean you put it in `~/.config/doom/modules/a`. It _should_ be in `~/.config/doom/modules/private/a`.

And by `(private :private a)`, I hope you meant `(doom! :private a)`. If you activated the `private` module again from `~/.config/doom/init.el` then that is what is causing the recursive load error.

Assuming that your files look something like:

```emacs-lisp
;; ~/.emacs.d/init.el
(require 'core (concat user-emacs-directory "core/core"))
(doom! :config (private +xdg))

;; ~/.config/doom/init.el
(doom! :private a)

;; ~/.config/doom/modules/private/a
(message "ding!")
```

Then everything should work fine. If you want a reference for a private module, [you can also check out mine](https://github.com/hlissner/doom-emacs-private). Let me know!

**Comment by dariooddenino** [comment]
Thanks, the issue was that I was using `(private :private a)` instead of just `:private a`. It works correctly this way.
And thanks for doom-emacs too :)

**Comment by ocharles** [comment]
@hlissner your above comment would be a great addition to the FAQ or something I think. I've seen a few reports that result in the `Recursive load` error, and I ran into it myself. It's a bit fiddly to work out where things go, but that comment is perfect.

**Comment by hlissner** [comment]
@ocharles I agree. However, I'm in the middle of a complete rewrite and restructure of Doom's documentation for what _should've_ been last week's 2.1 release — it's taking a lot longer than anticipated due to other commitments. 

Sorry to say, you'll have to put up with it _just_ a little longer.

**Comment by ocharles** [comment]
Oh gosh, that was not a request to have that done yesterday - sorry if it
came across like that! Just a suggestion that you may want to add to what
sounds like an already impressive to-do list.

**Comment by hlissner** [comment]
Haha, no worries. I didn't take it that way. Just wanted you know the FAQ isn't forgotten, just neglected.
