### ISSUE TITLE
REPL Handler for fennel-mode is broken

### ISSUE THREAD

**Issue by Janfel** [hlissner/doom-emacs#4263]
In [this line](https://github.com/hlissner/doom-emacs/blob/f7293fb67ef701244a421fd3bfc04b8e12689edc/modules/lang/lua/config.el#L69) the function `fennel-repl` is set as the REPL handler for `fennel-mode`. But `fennel-repl` does not satisfy the requirements for `set-repl-handler!` because it does not return the repl buffer when one doesn’t exist already. [There is a pull request addressing this issue](https://gitlab.com/technomancy/fennel-mode/-/merge_requests/14), but for now there should be a workaround. From my own config:

```elisp
(defadvice! +fennel--return-repl-buffer-from-fennel-repl-a (&rest _)
  :filter-return #'fennel-repl
  (get-buffer inferior-lisp-buffer))
```

**Comment by hlissner** [comment]
As of 120530e this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
