### ISSUE TITLE
flycheck-rebar3 (package not found) has been merged into flycheck

### ISSUE THREAD

**Issue by berbiche** [hlissner/doom-emacs#4264]
**What did you expect to happen?**

Compiling my doom emacs configuration with [vlaci/nix-doom-emacs](https://github.com/vlaci/nix-doom-emacs) fails because the package `flycheck-rebar3` no longer exists in MELPA.

**What actually happened?**

https://github.com/flycheck/flycheck/pull/1144

https://github.com/melpa/melpa/issues/6110

https://github.com/hlissner/doom-emacs/blob/f2ecfcec92ae6d52c732cedece7b30f78982cfd5/modules/lang/erlang/packages.el#L5-L6
https://github.com/hlissner/doom-emacs/blob/f7293fb67ef701244a421fd3bfc04b8e12689edc/modules/lang/erlang/config.el#L12-L15

**Additional details:**
N/A

**Steps to reproduce:**
N/A

**System information:**
N/A

**Comment by hlissner** [comment]
As of 62c1e5b this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by berbiche** [comment]
Thanks for the quick fix!
