### ISSUE TITLE
Double click selection broken in evil-mode

### ISSUE THREAD

**Issue by Janfel** [hlissner/doom-emacs#4268]
**What did you expect to happen?**
If you have a buffer like this,
```
one two three
```
double clicking the word `two` should create a selection like this
```
one [two] three
```
where the selection extends from `[` to `]`.

**What actually happened?**
With `:editor evil` enabled, this selection is created:
```
one [two ]three
```
In other words, the selection created by double clicking always includes one character too much.

**Additional details:**
I suspect this is caused by [this line](https://github.com/hlissner/doom-emacs/blob/3265c258217aaf0d8fee78e55d766271d88c95b2/modules/editor/evil/config.el#L78). Evil causes the selection to include the character under point. Normally, `evil-mode` uses a custom version of `mouse-drag-region` called `evil-mouse-drag-region` bound to `<down-mouse-1>` to circumvent this issue. The line in question removes this binding.

The easiest way I found to fix this, while still keeping the standard `mouse-drag-region`, would be something like this:

```elisp
(defadvice! +evil--fix-mouse-start-end-a (orig-fn start end mode)
  "Make `mouse-start-end' handle the `evil-mode' point/region convention.
Without this, double-click selection in `evil-mode' extends one
character too far."
  :around #'mouse-start-end
  (if (and (= mode 1)
           (bound-and-true-p evil-local-mode)
           (not (or (evil-insert-state-p) (evil-emacs-state-p))))
      (cl-destructuring-bind (start end) (funcall orig-fn start end mode)
        (list start (1- end)))
    (funcall orig-fn start end mode)))
```

**Steps to reproduce:**
1. Enable `:editor evil`.
2. Write into an empty buffer `one two three`.
3. Double click on `two`.

**Comment by hlissner** [comment]
As of a14fb64 this issue should be resolved. I've removed the line you mentioned in the evil module. The original issue no longer exists, so I assume it's been resolved at some point in the past few years. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
