### ISSUE TITLE
Hide/deprioritize file template yasnippet snippets in company-yasnippet

### ISSUE THREAD

**Issue by czikus** [hlissner/doom-emacs#4272]
**Describe the feature**

Currently `company-yasnippet` will show snippets starting with `__` before any other snippet. This makes it difficult to immediately see available snippets. File templates are usually not invoked using company and could be hidden or at the very least included at the bottom of the list.

**Comment by hlissner** [comment]
`company-yasnippet` displays snippets in lexicographical order. Unfortunately, `_` has higher precedence in this case. If you want to change their order or add some sort of filter either advise [company-yasnippet--candidates](https://github.com/company-mode/company-mode/blob/master/company-yasnippet.el#L74) or request this [upstream](https://github.com/company-mode/company-mode).

Company doesn't provide any simple way to pre-filter/sort results from particular backends, and I don't think this is a problem so I don't intend to add our own machinery to do so.
