### ISSUE TITLE
How do I disable bottom (minibuffer) documentation popping up?

### ISSUE THREAD

**Issue by smyrgeorge** [hlissner/doom-emacs#4278]
Hello,

Is there any way to disable bottom minibuffer to display documentation automatically?
I think is very distracting, especially in cases you choose a completion form company box.

![image](https://user-images.githubusercontent.com/5221146/99360916-fa664800-28b9-11eb-9035-9e7e02a0186b.png)

I'm using `(company +childframe)` and `(ivy +prescient)`

Regards
George S.

**Comment by danilevy1212** [comment]
Hello, I am guessing you are referring to the documentation provided by `lsp`. `lsp` has several several [settings](https://emacs-lsp.github.io/lsp-mode/page/settings/) for customization. In particular, I think that you may be interested in changing `lsp-eldoc-render-all` to nil in you config.el, as such

```lisp
(after! lsp
     (setq lsp-eldoc-render-all nil))
```

**Comment by smyrgeorge** [comment]
Thanks for your quick reply.
Finally i found it.

```
(setq lsp-signature-render-documentation nil)
```
