### ISSUE TITLE
Commit e1c9145 overrides cursor background

### ISSUE THREAD

**Issue by svaiter** [hlissner/doom-emacs#4286]
**What did you expect to happen?**
...
I expect doom-theme cursor configuration to be respected.

**What actually happened?**
Whatever theme is selected, the cursor background is white.

**Additional details:**
Happen also in doom sandbox.
The culprits seems to be line 593:
`(run-hooks 'after-setting-font-hook)`
Commenting this command leads to proper behaviour.

**Steps to reproduce:**
Update to HEAD and run emacs

**System information:**
<details><pre>
```
SYSTEM  type       darwin
        config     x86_64-apple-darwin20.1.0
        shell      /bin/zsh
        uname      Darwin 20.1.0 Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:11 PDT 2020; root:xnu-7195.50.7~2/RELEASE_X86_64 x86_64
        path       (~/.emacs.d/bin/ ~/opt/anaconda3/bin ~/opt/anaconda3/condabin ~/bin ~ .emacs.d/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /Library/TeX/texbin /Library/Apple/usr/bin /Applications/Emacs.app/Contents/MacOS/libexec/)
EMACS   dir        ~/.emacs.d/
        version    28.0.50
        build      Nov 16, 2020
        buildopts  --with-ns --with-modules '--enable-locallisppath=/Library/Application Support/Emacs/${version}/site-lisp:/Library/Application Support/Emacs/site-lisp' --with-xwidgets --with-nativecomp 'CFLAGS=-I/usr/local/opt/gcc/include -O2 -march=native' 'LDFLAGS=-L/usr/local/opt/gcc/lib/gcc/10 -L/usr/local/opt/libgccjit/lib/gcc/10 -L/usr/local/opt/gcc/lib/gcc/10/gcc/x86_64-apple-darwin19/10.2.0 -I/usr/local/opt/gcc/include -I/usr/local/opt/libgccjit/include'
        features   JPEG TIFF GIF PNG RSVG GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES NATIVE_COMP THREADS XWIDGETS JSON PDUMPER LCMS2
        traits     (gui server-running envvar-file)
DOOM    dir        ~/.doom.d/
        version    2.0.9
        font       #<font-spec nil nil SF Mono nil nil nil nil nil 18 nil nil nil nil>
        theme      doom-one-light
        build      HEAD -> develop 110d70bdf 2020-11-19 00:50:57 -0500
        elc-files  0
        modules    (:completion (company +childframe) (ivy +icons) :ui doom doom-dashboard hl-todo modeline ophints (popup +defaults) treemacs vc-gutter workspaces :editor (evil +everywhere) file-templates (format +onsave) snippets :emacs undo vc :term eshell vterm :checkers syntax spell grammar :tools biblio (eval +overlay) lookup lsp magit :os macos :lang (latex +latexmk) markdown (org +dragndrop +pretty +roam) rst (cc +lsp) emacs-lisp (javascript +lsp) julia (python +lsp +pyright +conda +cython) sh web data json yaml :config literate (default +bindings +smartparens))
        packages   ((magit-delta :pin b8526f8) (mixed-pitch :pin d305108f) (org-ref :pin 2a91b6f))
        unpin      (n/a)
        elpa       (goto-chg evil-tutor evil)
```
</pre></details>

**Comment by sarna** [comment]
I can reproduce this. I thought it was some issue with stale packages so I removed `~/.emacs.d/.local/straight` and reran `doom install` - didn't help.

**Comment by hlissner** [comment]
I cannot reproduce this.

> The culprits seems to be line 593: (run-hooks 'after-setting-font-hook)

This indicates to me that you have added a hook to `after-setting-font-hook` that resets your cursor color, somehow. Please check your config. The proposed fix is likely only addressing the symptom, not the cause.

**Comment by ajgrf** [comment]
I have the same issue and I haven't added anything to `after-setting-font-hook`. Its value on my system is:

    (+modeline-resize-for-font-h
     doom-modeline-refresh-bars
     doom-modeline-refresh-font-width-cache)

I'm using Emacs 27.1 on NixOS 12.09. My [doom config is here](https://github.com/ajgrf/dotfiles/tree/master/.doom.d).

**Comment by svaiter** [comment]
The value of my hook is 
`(+modeline-resize-for-font-h
 doom-modeline-refresh-bars
 doom-modeline-refresh-font-width-cache)`

Using "Doom + modules - your private config   C-c C-p" sandbox leads to the same issue.
I will try to understand which module could be the culprit.

**Comment by svaiter** [comment]
Removing `:ui modeline` leads to correct behaviour, both with my config and with the doom sandbox.

**Comment by sarna** [comment]
Same here, and I can confirm that `(modeline +light)` makes the cursor normal again.

**Comment by quasisphere** [comment]
Just for what it's worth, I have the same issue as well. However in my case changing to `(modeling +light)` or removing `:ui modeline` had no effect.

**Comment by hlissner** [comment]
As of 16344d0 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
