### ISSUE TITLE
Descriptions not displaying correctly in LaTeX mode map

### ISSUE THREAD

**Issue by tamasgal** [hlissner/doom-emacs#4288]
**What did you expect to happen?**
The descriptions of the `LaTeX-mode-map` `localleader` bindings should be displayed correctly.

**What actually happened?**
Instead of the description (set via `:desc`), the function name is displayed.
When hitting `SPC m` in LaTeX mode, this is what I see:

![Screenshot 2020-11-19 at 11 40 01](https://user-images.githubusercontent.com/1730350/99655388-f70ac200-2a5b-11eb-81e5-df0fe29a5e41.png)

However, it should display `View` instead of the function name `TeX-view`.

**Additional details:**

I have only `(latex +latexmk)` set in my `init.el` and discovered it when I tried to add my own key bindings, which work but also only display the function name instead of the description. Keybindings in different modes show the description correctly though!

This is what initially tried when I discovered this behaviour, copied from the original LaTeX module https://github.com/hlissner/doom-emacs/blob/110d70bdff12c61fb4bfebf8e9f6b3a18684076d/modules/lang/latex/config.el#L101

```lisp
(map! :map LaTeX-mode-map
      :localleader                  ; Use local leader
      :desc "View" "v" #'TeX-view ; Add which-key description
      :desc "Preview pane" "p" #'latex-preview-pane-mode
      :desc "Update preview" "u" #'latex-preview-pane-update
      :desc "Compile" "c" #'TeX-command-master
      :desc "Run all" "r" #'TeX-command-run-all
      :desc "Environment" "e" #'LaTeX-environment
      )
```

**Steps to reproduce:**
1. Enable the LaTeX in `init.el`
2. Hit `SPC m`

**System information:**
<details><pre>
SYSTEM  type       darwin
	config     x86_64-apple-darwin18.7.0
	shell      /bin/zsh
	uname      Darwin 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64
	path       (~/.nimble/bin ~/.pyenv/shims ~/.pyenv/bin /usr/local/opt/python/libexec/bin ~/opt/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /opt/X11/bin ~/.cabal/bin /usr/local/MacGPG2/bin /usr/local/sbin /Applications/DevDesktop/drush /usr/local/texlive/2016/bin/x86_64-darwin /Library/TeX/texbin ~/.emacs.d/bin /Applications/Emacs.app/Contents/MacOS/bin-x86_64-10_14 /Applications/Emacs.app/Contents/MacOS/libexec-x86_64-10_14 /Applications/Emacs.app/Contents/MacOS/libexec /Applications/Emacs.app/Contents/MacOS/bin)
EMACS   dir        ~/.emacs.d/
	version    27.1
	build      Aug 12, 2020
	buildopts  --with-ns '--enable-locallisppath=/Library/Application Support/Emacs/${version}/site-lisp:/Library/Application Support/Emacs/site-lisp' --with-modules
	features   NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS JSON PDUMPER
	traits     (batch server-running envvar-file)
DOOM    dir        ~/.rc/doom.d/
	version    2.0.9
	build      HEAD -> develop, origin/develop, origin/HEAD 5d5d94d49 2020-11-04 03:02:01 -0500
	elc-files  0
	modules    (:completion company (ivy +fuzzy) :ui doom fill-column hl-todo modeline ophints (popup +defaults) vc-gutter workspaces :editor (evil +everywhere) file-templates format snippets :emacs dired electric ibuffer undo vc :term vterm :checkers syntax spell :tools docker (eval +overlay) lookup (magit +forge) make pass :lang cc data emacs-lisp go javascript julia (latex +latexmk) markdown (org +jupyter +pandoc +present) python rst sh :email mu4e :app calendar :config (default +bindings))
	packages   (n/a)
	unpin      (n/a)
	elpa       (n/a)
</pre></details>

**Comment by hlissner** [comment]
Does changing `LaTeX-mode-map` to `latex-mode-map` help?

**Comment by tamasgal** [comment]
Yes, that's it!

Why is it like this?

**Comment by tamasgal** [comment]
Ah wait, I was too fast...

I now have this:

```lisp
(map! :map latex-mode-map
      :localleader                  ; Use local leader
      :desc "View" "v" #'TeX-view ; Add which-key description
      :desc "Preview pane" "p" #'latex-preview-pane-mode
      :desc "Update preview" "u" #'latex-preview-pane-update
      :desc "Compile" "c" #'TeX-command-master
      :desc "Run all" "a" #'TeX-command-run-all
      :desc "Environment" "n e" #'LaTeX-environment
      :desc "Section" "n s" #'LaTeX-section
      )
```

But only `View` and `reftex-toc` are displayed:

![Screenshot 2020-11-19 at 18 32 53](https://user-images.githubusercontent.com/1730350/99702062-a44dfc00-2a95-11eb-9db1-0631ead81e6f.png)

**Comment by hlissner** [comment]
I'm afraid that's to be expected. Labels on minor mode keymaps (like `reftex-mode-map`, where that `;` keybind lives) isn't supported yet. At the very least, I'll change `LaTeX-mode-map` to `latex-mode-map` in the module after some testing.

**Comment by tamasgal** [comment]
Alright, thanks! I can certainly live with that, I just thought this might be some kind of a misconfiguration...

**Comment by hlissner** [comment]
As of 0d6c32f I've fixed the `TeX-view` keybind label, which should resolve your issue.

> Why is it like this?

We use [auctex](https://github.com/emacs-straight/auctex) to provide latex support in Emacs. Unfortunately, this is a very old package, filled with anachronisms and backward compatibility hacks that make it one of the more obtuse packages in the Emacs ecosystem.

One of those oddities is that it has multiple aliases for its major modes, like `LaTeX-mode`, `latex-mode`, `tex-mode`, and `TeX-mode`. I can hardly remember which is which, but when you're in a latex buffer, the `major-mode` variable contains `latex-mode`, which is (sort of) what which-key looks for when displaying mode-local labels, so we have to be careful about which keymap we assign our labels to (`latex-mode-map`, `LaTeX-mode-map`, etc).

**Comment by tamasgal** [comment]
Oh I see. I hope it still keeps working because I failed to integrate the org-latex-thing into my workflow. So many features I miss from auctex :(
