### ISSUE TITLE
show-paren-mode fails on Rust code with angle brackets

### ISSUE THREAD

**Issue by loafofpiecrust** [hlissner/doom-emacs#4304]
**What did you expect to happen?**
In `.rs` files (`rustic-mode`), pairs of parentheses, curly braces, and angle brackets should highlight their corresponding pair when point is on them.

**What actually happened?**
After the first pair of angle brackets in a file, `show-paren-mode` is thrown off and thinks every brace is unmatched and highlighted red. If I use `show-smartparens-mode` instead, it works as expected for all types of braces.

**Additional details:**
![2020-11-23-111301_760x340_scrot](https://user-images.githubusercontent.com/3489148/99986199-e40a3180-2d7c-11eb-8e2f-02add38e7792.png)
![2020-11-23-111253_750x308_scrot](https://user-images.githubusercontent.com/3489148/99986215-e9677c00-2d7c-11eb-8a85-d665f2f470f1.png)
![2020-11-23-111241_730x308_scrot](https://user-images.githubusercontent.com/3489148/99986229-ec626c80-2d7c-11eb-8ccc-58af0cc7f454.png)

**Steps to reproduce:**
1. Open a Rust file, for example: [this one](https://github.com/NEU-DSG/dailp-encoding/blob/main/migration/src/spreadsheets.rs).
2. Search for an opening angle bracket `<`
3. Place point on the angle bracket.

**System information:**
<details><pre>
SYSTEM  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /run/current-system/sw/bin/fish
        uname      Linux 5.4.73 #1-NixOS SMP Thu Oct 29 08:58:11 UTC 2020 x86_64
        path       (~/.netlify/helper/bin ~/.config/emacs/bin ~/.go/bin ~/.cargo/bin ~/.npm/bin ~/dotfiles/emacs/.config/emacs/bin/ ~/dotfiles/emacs/.config/emacs/bin/ ~/dotfiles/emacs/.config/emacs/bin/ ~/dotfiles/emacs/.config/emacs/bin/ ~/dotfiles/emacs/.config/emacs/bin/ ~/dotfiles/emacs/.config/emacs/bin/ ~/bin /run/wrappers/bin ~/.nix-profile/bin /etc/profiles/per-user/$USER/bin /nix/var/nix/profiles/default/bin /run/current-system/sw/bin /nix/store/7fplpyfwr0qbrssiffm1r9b24gm5if7d-emacs-gcc-20201108.0/libexec/emacs/28.0.50/x86_64-pc-linux-gnu/)
EMACS   dir        ~/dotfiles/emacs/.config/emacs/
        version    28.0.50
        build      Nov 23, 2020
        buildopts  --prefix=/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-emacs-gcc-20201108.0 --disable-build-details --with-modules --with-x-toolkit=gtk3 --with-xft --with-cairo --with-xwidgets --with-nativecomp CFLAGS=-DMAC_OS_X_VERSION_MAX_ALLOWED=101200
        features   XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND DBUS GSETTINGS GLIB NOTIFY INOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES NATIVE_COMP THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER
        traits     (gui server-running envvar-file)
DOOM    dir        ~/dotfiles/emacs/.config/doom/
        version    2.0.9
        font       #<font-spec nil nil monospace nil nil normal nil nil 15 nil nil nil nil>
        theme      ewal-doom-dark
        build      HEAD -> develop c83e5e75e 2020-11-21 14:09:08 -0500
        elc-files  0
        modules    (:input chinese :desktop (&user window-manager) (&user polybar) :completion (company +childframe) (ivy +prescient +icons +childframe) :ui doom doom-dashboard hl-todo hydra indent-guides ophints (popup +defaults) (ligatures +extra) treemacs unicode vc-gutter window-select workspaces (emoji +github +unicode) :editor (evil +everywhere) file-templates fold (format +onsave) multiple-cursors snippets :emacs (dired +icons +ranger) electric undo vc :term vterm :checkers (syntax +childframe) (spell +aspell +everywhere) :tools direnv editorconfig (eval +overlay) lookup lsp (magit +forge) make pdf terraform :lang (cc +lsp) data emacs-lisp (go +lsp) json (javascript +lsp) kotlin ledger lua markdown nix (org +pretty +dragndrop +pomodoro) php (python +lsp) racket rest (rust +lsp) (sh +fish) (swift +lsp) (web +lsp) yaml :email mu4e :app calendar :config (default +bindings))
        packages   ((tsc :pin dc9094b5066ec3c4ad583ed285c282f5811323b5 :recipe (:host github :repo ubolonton/emacs-tree-sitter :files (core/*.el))) (tree-sitter :pin dc9094b5066ec3c4ad583ed285c282f5811323b5 :recipe (:host github :repo ubolonton/emacs-tree-sitter :files (lisp/*.el src Cargo.toml Cargo.lock))) (tree-sitter-langs :pin dc9094b5066ec3c4ad583ed285c282f5811323b5 :recipe (:host github :repo ubolonton/emacs-tree-sitter :files (langs/*.el langs/queries))) (theme-changer :pin 61945695a30d678e6a5d47cbe7c8aff59a8c30ea) (ewal) (ewal-doom-themes) (ewal-evil-cursors) (string-inflection) (evil-owl :pin ed5a98644a9cf321de213b50df6473de9f3a71ed) (olivetti :pin b76a020aedb57a6a7d0ae61cde13434f5c802a44) (graphql-mode) (polymode) (poly-markdown) (poly-org) (literate-calc-mode) (flycheck-inline :pin 0662c314bd819f9b46f8b2b13f0c650445b3a8c5) (flycheck-posframe :disable t) (flycheck-popup-tip :disable t) (org-msg :disable t) (mu4e-alert :pin 91f0657c5b245a9de57aa38391221fb5d141d9bd) (mu4e-send-delay :recipe (:host github :repo cacology/mu4e-send-delay)) (org-ref) (citeproc-org) (transmission :disable t) (anzu :pin 7b8688c84d6032300d0c415182c7c1ad6cb7f819) (evil-anzu :pin d3f6ed4773b48767bd5f4708c7f083336a8a8a86) (posframe) (mini-frame) (all-the-icons-ivy :pin 937ca700c6e9ad4cd957480b12e480cbd5c44175 :recipe (:branch overwrite-args)) (selectrum) (embark :recipe (:host github :repo oantolin/embark)) (mount-mode :disable t :recipe (:host github :repo zellerin/mount-mode)) (ivy-avy) (org-cv :recipe (:host gitlab :repo Titan-C/org-cv)) (fcitx :disable t) (solaire-mode :disable t) (bitwarden :recipe (:host github :repo seanfarley/emacs-bitwarden)) (zoom :pin a373e7eed59ad93315e5ae88c816ca70404d2d34) (vterm :built-in 'prefer) (undo-tree :built-in 'prefer) (plantuml-mode :built-in 'prefer) (highlight-numbers :disable t) (dired-show-readme :recipe (:host gitlab :repo kisaragi-hiu/dired-show-readme)) (pdf-tools :built-in 'prefer) (pdf-continuous-scroll-mode :recipe (:host github :repo dalanicolai/pdf-continuous-scroll-mode.el)) (oauth2) (spotify :recipe (:host github :repo danielfm/spotify.el)) (calibredb) (ace-window :pin 57977baeba15b92c987eb7bf824629a9c746a3c8 :recipe (:host github :repo loafofpiecrust/ace-window :branch posframe)))
        unpin      (n/a)
        elpa       (vterm use-package undo-tree tablist plantuml-mode pdf-tools let-alist ivy-fuz ivy fuz dash bind-key)
</pre></details>

**Comment by hlissner** [comment]
I cannot reproduce this. 

![screencast](https://user-images.githubusercontent.com/510883/100000838-2c7f1a80-2d90-11eb-95f0-c4618e821018.gif)

Perhaps an unbalanced paren actually exists elsewhere in your file?

**Comment by loafofpiecrust** [comment]
Well, since we're both testing on the same bit of code in the same file, and it works for you and compiles fine, I don't think there's an unbalanced pair in there. I am on `native-comp`, maybe that makes a difference here. It is inconsistent though, sometimes when I open the same file it's fine. But when I do see the issue it seems to maybe start around instances of two adjacent closing angle brackets like so: `Vec<Vec<String>>`.

**Comment by loafofpiecrust** [comment]
Since I'm using `native-comp` Emacs 28 and a font with programming ligatures, could `show-paren-mode` be getting confused by `>:` and `>>` for example getting "ligaturized"?
