### ISSUE TITLE
Configuration of shackle mode in .config.el not loaded

### ISSUE THREAD

**Issue by IsaacPhys** [hlissner/doom-emacs#4307]
I want the syntax checker to pop up at the bottom so I use the shackle mode. I wrote this in the .config.el but I have to M-x eval-buffer everytime when I start Emacs. Otherwise these code seems to make nothing.

```elisp
(use-package! shackle
  :hook (python-mode . shackle-mode)
  :demand t
  :config
  (setq shackle-default-rule nil
        shackle-rules '(("\\`\\*ein: .+?\\.ipynb\\*\\'" :regexp t :same t)
                        (flycheck-error-list-mode :align 'below :size 0.22)
                                        ;	(ein:run :align 'right :size 0.5)
                        (ein:run :popup)
                        (ein:notebooklist-open :popup)))
  (shackle-mode 1))
```

**Comment by hlissner** [comment]
Doom's `:ui popup` module provides what shackle does. Use this instead:

```elisp
;; add to ~/.doom.d/config.el
(after! python
  (set-popup-rule! "^\\*ein: .+?\\.ipynb\\*" :size 0.22))

;; :side 'below is the default, so I omitted it
```

Please use [the discord](https://discord.gg/qvGgnVx) for configuration questions in the future.

-----

And for future reference, use code fences to post code blocks:

\`\`\`lisp
;; code goes here
\`\`\`

You did

\`
;; code goes here
\`

Which made your code unreadable.
