### ISSUE TITLE
Backspace too hungry

### ISSUE THREAD

**Issue by azy2** [hlissner/doom-emacs#431]
The function doom/delete-backward-char misbehaves when the point is at the beginning of the line and next to the closing brace. For instance, in emacs-lisp mode type:
```
(Some example text
|)
```
With | as your cursor, hit backspace. This deletes all of the text in the braces. This is particularly annoying when you're typing out a list in emacs-lisp and you hit enter by accident. Hitting backspace will delete your entire list.

The errant code is core/autoload/editor.el:200:203

I have it commented out but I imagine you'd want to change it to only delete back to the nearest non-whitespace character.

**Comment by hlissner** [comment]
Ah, I've had the fix for this sitting in my local repo for a while. Forgot I hadn't pushed it! It should be fixed now.
