### ISSUE TITLE
"Selecting deleted buffer" error when trying to load magit status buffer

### ISSUE THREAD

**Issue by jsravn** [hlissner/doom-emacs#4311]
**What did you expect to happen?**
...

**What actually happened?**
```
Debugger entered--Lisp error: (error "Selecting deleted buffer")
  #f(compiled-function (connection) "Return true if the end of the buffer has a properly-formatted prompt." #<bytecode 0xfdfc81>)(#<forge-database forge-database-1496b48>)
  apply(#f(compiled-function (connection) "Return true if the end of the buffer has a properly-formatted prompt." #<bytecode 0xfdfc81>) #<forge-database forge-database-1496b48> nil)
  emacsql-waiting-p(#<forge-database forge-database-1496b48>)
  #f(compiled-function (connection &optional timeout) "Block until CONNECTION is waiting for further input." #<bytecode 0xfdd475>)(#<forge-database forge-database-1496b48>)
  apply(#f(compiled-function (connection &optional timeout) "Block until CONNECTION is waiting for further input." #<bytecode 0xfdd475>) #<forge-database forge-database-1496b48> nil)
  emacsql-wait(#<forge-database forge-database-1496b48>)
  #f(compiled-function (#<forge-database forge-database-1496b48> (:file "/home/james/.config/emacs/.local/etc/forge/forge-d..."))
  apply(#f(compiled-function 
  #f(compiled-function (&rest args) #<bytecode 0x1bab5ed>)(#<forge-database forge-database-1496b48> (:file "/home/james/.config/emacs/.local/etc/forge/forge-d..."))
  apply(#f(compiled-function (&rest args) #<bytecode 0x1bab5ed>) #<forge-database forge-database-1496b48> (:file "/home/james/.config/emacs/.local/etc/forge/forge-d..."))
  initialize-instance(#<forge-database forge-database-1496b48> (:file "/home/james/.config/emacs/.local/etc/forge/forge-d..."))
  #f(compiled-function (class &rest slots) "Default constructor for CLASS `eieio-default-superclass'.\nSLOTS are the initialization slots used by `initialize-instance'.\nThis static method is called when an object is constructed.\nIt allocates the vector used to represent an EIEIO object, and then\ncalls `initialize-instance' on that object." #<bytecode 0x184c66d>)(forge-database :file "/home/james/.config/emacs/.local/etc/forge/forge-d...")
  apply(#f(compiled-function (class &rest slots) "Default constructor for CLASS `eieio-default-superclass'.\nSLOTS are the initialization slots used by `initialize-instance'.\nThis static method is called when an object is constructed.\nIt allocates the vector used to represent an EIEIO object, and then\ncalls `initialize-instance' on that object." #<bytecode 0x184c66d>) forge-database (:file "/home/james/.config/emacs/.local/etc/forge/forge-d..."))
  make-instance(forge-database :file "/home/james/.config/emacs/.local/etc/forge/forge-d...")
  #f(compiled-function (class &optional variable file debug) #<bytecode 0x12f5d05>)(forge-database forge--db-connection "/home/james/.config/emacs/.local/etc/forge/forge-d..." t)
  apply(#f(compiled-function (class &optional variable file debug) #<bytecode 0x12f5d05>) forge-database (forge--db-connection "/home/james/.config/emacs/.local/etc/forge/forge-d..." t))
  closql-db(forge-database forge--db-connection "/home/james/.config/emacs/.local/etc/forge/forge-d..." t)
  forge-db()
<snip>
  #<subr call-interactively>(magit-status nil nil)
  apply(#<subr call-interactively> (magit-status nil nil))
  explain-pause--wrap-call-interactively(#<subr call-interactively> magit-status nil nil)
  apply(explain-pause--wrap-call-interactively #<subr call-interactively> (magit-status nil nil))
  call-interactively(magit-status nil nil)
  command-execute(magit-status)

```

Started happening after I just updated.

**Additional details:**
- Include a link to your private config
- Include screenshots/casts of your issue
- If you mention key sequences, include what commands they're bound to (use `SPC
  h k KEY` or `C-h h k KEY` to inspect keys).
- Include any warnings or errors logged to \*Messages\* (use `M-x
  view-echo-area-messages` to see it).

<details><pre>
If an error message is involved include a backtrace of it.

How to acquire a backtrace:
https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#how-to-extract-a-backtrace-from-an-error
</pre></details>

**Steps to reproduce:**
1. Select these example steps,
2. Delete them,
3. And replace them with precise steps to reproduce your issue.
4. Fill in "system information" below.

**System information:**
<details><pre>
SYSTEM  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /run/current-system/sw/bin/zsh
        uname      Linux 5.4.78 #1-NixOS SMP Wed Nov 18 18:20:34 UTC 2020 x86_64
        path       (~/.config/emacs/bin/ ~/.config/emacs/bin/ /nix/store/pgrvv3g7ijgfrn4hxla8v51j79ab8060-patchelf-0.12/bin /nix/store/n3r351j7vfr2bv95fp6miz3l8741jdb4-gcc-wrapper-9.3.0/bin /nix/store/58q0ygc01jba5cf5zghc0dlhx187mskk-gcc-9.3.0/bin /nix/store/azv0jpirgc6kwcy3fs59jpp2mdl2k2g5-glibc-2.32-bin/bin /nix/store/ffw9vziqw2p4rpm2zwgi5r3ymynd54d8-coreutils-8.32/bin /nix/store/rqhvcy5zmlypr9qfa43npsyxsxjg7jxa-binutils-wrapper-2.31.1/bin /nix/store/79rshjqnibwcx468m4i31wnmasaj6nf4-binutils-2.31.1/bin /nix/store/azv0jpirgc6kwcy3fs59jpp2mdl2k2g5-glibc-2.32-bin/bin /nix/store/ffw9vziqw2p4rpm2zwgi5r3ymynd54d8-coreutils-8.32/bin /nix/store/n3r351j7vfr2bv95fp6miz3l8741jdb4-gcc-wrapper-9.3.0/bin /nix/store/58q0ygc01jba5cf5zghc0dlhx187mskk-gcc-9.3.0/bin /nix/store/azv0jpirgc6kwcy3fs59jpp2mdl2k2g5-glibc-2.32-bin/bin /nix/store/ffw9vziqw2p4rpm2zwgi5r3ymynd54d8-coreutils-8.32/bin /nix/store/rqhvcy5zmlypr9qfa43npsyxsxjg7jxa-binutils-wrapper-2.31.1/bin /nix/store/79rshjqnibwcx468m4i31wnmasaj6nf4-binutils-2.31.1/bin /nix/store/azv0jpirgc6kwcy3fs59jpp2mdl2k2g5-glibc-2.32-bin/bin /nix/store/ffw9vziqw2p4rpm2zwgi5r3ymynd54d8-coreutils-8.32/bin /nix/store/kzdxdj5lis8d9lwjhmgzdxqbnhjhg277-gnumake-4.3/bin /nix/store/22qh56vyj2j2d8zfyv11dc1j9vlszc29-python3.8-ansible-2.10.0/bin /nix/store/18656kvqazm74bj7k3mdkwmdlqfyf581-python3-3.8.6/bin /nix/store/18656kvqazm74bj7k3mdkwmdlqfyf581-python3-3.8.6/bin /nix/store/9p7mmghw7b4v1dd84kf6mjfd8rwzrkg0-python3.8-setuptools-47.3.1/bin /nix/store/nc5gvyqd8ng1k1cfrarl5d9kacnxmkca-python3.8-netaddr-0.8.0/bin /nix/store/w4b0x0f09drp9qdp2ipvqj45jqq7qi4n-python3.8-jmespath-0.10.0/bin /nix/store/3jfc57g7gxa2615wqy8a5v4ivclskgc1-python3.8-chardet-3.0.4/bin /nix/store/07p1q3jc35c8g3c0j7w30ij158ghfclw-go-1.15.5/bin /nix/store/gi67bml6cv7549hsr3i3pjhb6s0z7had-adoptopenjdk-hotspot-bin-11.0.7/bin /nix/store/k8p1c7wkrk5lbwmq6c5j93000gmgqjkx-buildkit-0.7.2/bin /nix/store/vrfxzbalzcdbmwz8nsgxhd4w6c2lpn7i-kustomize-3.8.7/bin /nix/store/h0kdi5kmyrdggxkal6czrk4dvwisdpzd-gradle-6.7/bin /nix/store/6v2msiwfz8k721arjd3l9fhb7aa8cx0f-jq-1.6-bin/bin /nix/store/8kin1757hhp4pmarkg4hgqf88mzhyglr-keepassx2-2.0.3/bin /nix/store/qsh9v4a10jgwxqlkhrfv24604g16z0fa-mkcert-1.4.2/bin /nix/store/8l7srzvhvjmn28s36kajrjxkfvhsl81b-protobuf-3.13.0/bin /nix/store/n0ci0xh4rlng1ivzi31hn0ph441a11rw-openssl-1.1.1h-bin/bin /nix/store/zk5r4z8n7mvna59pmijzpjrpf5z4ghk1-zip-3.0/bin /nix/store/ffw9vziqw2p4rpm2zwgi5r3ymynd54d8-coreutils-8.32/bin /nix/store/vxmv30pp7cl4mshviy4jl5bjm680mjd5-findutils-4.7.0/bin /nix/store/lj53hvg0pdsl2r4n39lgg7pzmnnsxb0b-diffutils-3.7/bin /nix/store/qqnjk28kc8dcl3rijmgkvb057dfzl4cn-gnused-4.8/bin /nix/store/8i43g3cfkryp23ppgl7cllpqjdrdfcya-gnugrep-3.5/bin /nix/store/dkkd92l7h98fn33miglvbda91365dx6q-gawk-5.1.0/bin /nix/store/kg7i58vnbs4q877hnil4d4d2y72fa8g6-gnutar-1.32/bin /nix/store/b0309s68b8jcx5axw2hnsmh3lwdh2kfd-gzip-1.10/bin /nix/store/kw21b552xi7fsvgzppnd1ws6qy8q8wbl-bzip2-1.0.6.0.1-bin/bin /nix/store/kzdxdj5lis8d9lwjhmgzdxqbnhjhg277-gnumake-4.3/bin /nix/store/y0sw8sxkr7kwlsndwixyf4s4snlfhjh1-bash-4.4-p23/bin /nix/store/53nwh281zm213kg505mrp3g5qwdsnjbs-patch-2.7.6/bin /nix/store/xzyl3phpyiq43l7bc5aqg3bqzllj0zid-xz-5.2.5-bin/bin /nix/store/j9g43bsmz0697fv3gq4jcl6pn6m9p5k9-kitty-0.19.2/bin /nix/store/95g0faaqpwjbch0qmcw3c824xl3rrka7-imagemagick-6.9.11-29/bin /nix/store/bhc7zx69a1xrcx60bmkgfnlf4wc5qm9i-xsel-unstable-2020-05-27/bin /nix/store/1fxrzg39nc27grgbcxc2zljzzs4pgcqy-ncurses-6.2-dev/bin /run/wrappers/bin ~/.config/emacs/bin ~/go/bin ~/.dotfiles/bin ~/.local/bin ~/.nix-profile/bin /etc/profiles/per-user/$USER/bin /nix/var/nix/profiles/default/bin /run/current-system/sw/bin /nix/store/778c0nzn0qcpp4ar9rbgk3fgxmq0d95x-emacs-unstable-emacs-27.1/libexec/emacs/27.1/x86_64-pc-linux-gnu/)
EMACS   dir        ~/.config/emacs/
        version    27.1
        build      Nov 24, 2020
        buildopts  --prefix=/nix/store/778c0nzn0qcpp4ar9rbgk3fgxmq0d95x-emacs-unstable-emacs-27.1 --disable-build-details --with-modules --with-x-toolkit=gtk3 --with-xft --with-cairo CFLAGS=-DMAC_OS_X_VERSION_MAX_ALLOWED=101200
        features   XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND DBUS GSETTINGS GLIB NOTIFY INOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER GMP
        traits     (gui server-running envvar-file)
DOOM    dir        ~/.config/doom/
        version    2.0.9
        font       #<font-spec nil nil PragmataPro Liga nil nil nil nil nil 16 nil nil nil nil>
        theme      doom-one
        build      HEAD -> develop c83e5e75e 2020-11-21 14:09:08 -0500
        elc-files  0
        modules    (:completion (company +childframe) (ivy +prescient +icons) :ui doom doom-dashboard hl-todo indent-guides modeline nav-flash ophints (popup +all +defaults) (ligatures +pragmata-pro) treemacs vc-gutter vi-tilde-fringe window-select workspaces zen :editor (evil +everywhere) fold format multiple-cursors rotate-text snippets word-wrap :emacs dired electric vc :term vterm :checkers syntax :tools ansible docker direnv editorconfig (eval +overlay) (lookup +docsets +dictionary) (lsp +peek) (magit +forge) make terraform :lang (cc +lsp) (clojure +cider +lsp) common-lisp data emacs-lisp (go +lsp) (java +lsp) (javascript +lsp) markdown nix (org +dragndrop +journal +roam +pretty) (python +lsp +pyenv) sh scheme yaml :email mu4e :config literate (default +bindings +smartparens))
        packages   ((atomic-chrome) (org-alert) (caddyfile-mode) (protobuf-mode))
        unpin      (org-roam lsp-mode)
        elpa       (vterm)

</pre></details>

**Comment by jsravn** [comment]
I can't reproduce after blowing away the local folder and doom sync -u again. Something got messed up in the forge DB after upgrade and I'm not sure why.

**Comment by dschrempf** [comment]
Did you ever encounter this problem again? I am also facing this, now for the second time within a week. I do not even use Doom but Spacemacs.

**Comment by jsravn** [comment]
@dschrempf Nope, never happened again after I removed the forge DB.

**Comment by dschrempf** [comment]
Thanks. I am using NixOS, and I expect this is happening because the `emacsql-sqlite` binary compiled by Emacs stops working when upgrading NixOS. I included `emacsql` now into the Nix expression, so that it get's rebuilt when dependencies change. So far, everything works fine. Maybe this information is useful to someone.
