### ISSUE TITLE
Use counsel-grep-or-swiper instead of swiper?

### ISSUE THREAD

**Issue by casouri** [hlissner/doom-emacs#432]
As folks discussed in abo-abo/swiper#416. `counsel-grep-or-swiper` seems to be a better solution than `swiper` because it uses swiper on small files and buffers without files and uses counsel-grep(faster) on larger files.

**Comment by hlissner** [comment]
I agree. `swiper` is now remapped to `counsel-grep-or-swiper` in `develop`.

**Comment by forrestchang** [comment]
@hlissner How to undo this change in personal configs? I want swiper in all situations.

**Comment by hlissner** [comment]
@forrestchang `(map! [remap swiper] nil)`

**Comment by ianpan870102** [comment]
[Question] 
I'm rather new to the ivy/counsel package family. Why would one prefer swiper over counsel-grep? The latter seems significantly faster than the former. 
The only obvious advantage of swiper that I noticed is the better syntax highlighting -- is this all?
