### ISSUE TITLE
 How to change theme style

### ISSUE THREAD

**Issue by kecode** [hlissner/doom-emacs#4324]
I prefer the following theme to red.
![image](https://user-images.githubusercontent.com/23140388/100339852-5c8b1f80-3015-11eb-9616-b5a6c10838ce.png)

![image](https://user-images.githubusercontent.com/23140388/100339906-6dd42c00-3015-11eb-9f39-587ec670024e.png)

**Comment by hlissner** [comment]
https://github.com/hlissner/doom-emacs/blob/develop/docs/faq.org#how-do-i-change-the-theme

https://github.com/hlissner/doom-emacs/blob/develop/docs/faq.org#how-do-i-customize-a-theme-or-faces
