### ISSUE TITLE
Creating new rails classes dont capitalize the initials on Ruby f iles

### ISSUE THREAD

**Issue by otavioschwanck** [hlissner/doom-emacs#4326]
![image](https://user-images.githubusercontent.com/9551316/100362807-a7d40c80-2fda-11eb-9c58-d989db3dabd5.png)

The expected is `FindByMonthReport` but it is filling with `Findbymonthreport` i don't know if its a doom thing or a projectile-rails problem.  It start to happen a few weeks ago.

Other problem is don't have identation when create the file.

**Comment by ymarco** [comment]
Steps to reproduce? Are you referring to file templates?

**Comment by otavioschwanck** [comment]
> Steps to reproduce? Are you referring to file templates?

Yes, just create a Ruby classe in a nested folder in rails project, like:

app/services/reports/sales/find_by_month_report.rb

**Comment by hlissner** [comment]
[This is the file-template you're talking about](https://github.com/hlissner/doom-emacs/blob/develop/modules/editor/file-templates/templates/ruby-mode/__module). A PR would be appreciated.

**Comment by otavioschwanck** [comment]
> [This is the file-template you're talking about](https://github.com/hlissner/doom-emacs/blob/develop/modules/editor/file-templates/templates/ruby-mode/__module). A PR would be appreciated.

@hlissner 

I did some tests, modifed this template and nothing happens, then, disabled the `file-templates` module, did the sync, and the template is still be created in the wrong way.

I think for ruby, the template is getting from  elsewhere (maybe projectile-rails or robe).

I don't know how to solve :(
