### ISSUE TITLE
go/test-menu commands does't load .bash files anymore 

### ISSUE THREAD

**Issue by andyafter** [hlissner/doom-emacs#433]
When I use go/test-menu, it always loads all the environment params that I preset in the .bash_profile with 
```
if [ -r ~/.bashrc ]; then
    . ~/.bashrc
fi
```

now it doesn't do that anymore. Not sure if it is because of osx update or doom emacs. My tests can no longer find environment parameters in emacs

**Comment by hlissner** [comment]
I've made some changes to what (and how) Doom pulls from your shell config. Please update and let me know if this resolves your issue with `+go/test-menu`.
