### ISSUE TITLE
It doesn't add closing bracket in INSERT mode with smartparens strict mode enabled

### ISSUE THREAD

**Issue by vganshin** [hlissner/doom-emacs#4337]
`|` is my cursor.

**What did you expect to happen?**

In INSERT mode

```
(comment

|my-func

)
```
When I type `(` I expect that closing round bracket will be added.
```
(comment

(|)my-func

)
```

**What actually happened?**
It doesn't
```
(comment

(|my-func

)
```

**Additional details:**
- I have enabled smartparens global strict mode.

Basically it happens only if next symbol after cursor is not a space or `\n`, but some character.

**Comment by vganshin** [comment]
Additional:
When then I type closing bracket it just move existing one to the end of word

```
(comment

(my-func)|
```
If I press closing bracket again it says 'we can not insert unbalanced closing delimiter in strict mode'

**Comment by hlissner** [comment]
The original issue is [not a bug](https://github.com/hlissner/doom-emacs/blob/develop/modules/config/default/config.el#L103-L104). Please familiarize yourself with the default smartparens config in the same file and tweak as you like. e.g.

```elisp
(after! smartparens
  (sp-pair "(" nil :unless '(:rem sp-point-before-word-p)))
```
