### ISSUE TITLE
Magit error

### ISSUE THREAD

**Issue by leoxiaobin** [hlissner/doom-emacs#4338]
**What did you expect to happen?**
Init doom emacs successly

**What actually happened?**
Have an error when open emacs (error . "magit-dispatch is not a transient command")

**Additional details:**
Just follow the document to install doom, and do nothing for private config

<details><pre>
  x There was an unexpected error
    Message: error
    Data: (error . "magit-dispatch is not a transient command")
    Backtrace:
      (signal error ("magit-dispatch is not a transient command"))
      (error "%s is not a transient command" magit-dispatch)
      (transient--layout-member magit-worktree magit-dispatch)
      (transient--insert-suffix magit-dispatch magit-worktree ("%" "Gitflow" mag
      (transient-replace-suffix magit-dispatch magit-worktree ("%" "Gitflow" mag
      (eval-buffer #<buffer  *load*-59180> nil "/home/bixi/.emacs.d/modules/tool
      (load-with-code-conversion "/home/bixi/.emacs.d/modules/tools/magit/config
      (load "/home/bixi/.emacs.d/modules/tools/magit/config" t nomessage)
      (let (file-name-handler-alist) (load (expand-file-name file (plist-get pli
      (condition-case e (let (file-name-handler-alist) (load (expand-file-name f
</pre></details>

**Steps to reproduce:**
Just follow the document to install doom, and do nothing for private config

**System information:**
<details><pre>
```
SYSTEM  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /usr/bin/zsh
        uname      Linux 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020 x86_64
        path       (/usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /usr/games /usr/local/games /mnt/c/Program Files/WindowsApps/Microsoft.WindowsTerminal_1.4.3243.0_x64__8wekyb3d8bbwe /mnt/c/windows/system32 /mnt/c/windows /mnt/c/windows/System32/Wbem /mnt/c/windows/System32/WindowsPowerShell/v1.0/ /mnt/c/windows/System32/OpenSSH/ /mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common /mnt/c/Program Files/NVIDIA Corporation/NVIDIA NGX /mnt/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR /mnt/c/Program Files (x86)/HP/HP Performance Advisor /mnt/c/Program Files/dotnet/ /mnt/c/ProgramData/chocolatey/bin /mnt/c/Users/$USER/scoop/shims /mnt/c/Users/$USER/AppData/Local/Microsoft/WindowsApps /mnt/c/Users/$USER/AppData/Local/Programs/Microsoft VS Code/bin /usr/local/libexec/emacs/27.1/x86_64-pc-linux-gnu)
EMACS   dir        ~/.emacs.d/
        version    27.1
        build      Nov 29, 2020
        buildopts
        features   XPM JPEG TIFF GIF PNG RSVG SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP
        traits     (batch envvar-file)
DOOM    dir        ~/.doom.d/
        version    2.0.9
        build      grafted, HEAD -> develop, origin/develop, origin/HEAD 2828281a 2020-11-29 15:19:21 -0500
        elc-files  0
        modules    (:completion company ivy :ui deft doom doom-dashboard doom-quit hl-todo modeline ophints (popup +defaults) treemacs vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold snippets :emacs dired electric undo vc :term eshell shell :checkers syntax :tools (eval +overlay) lookup (magit +forge) tmux :lang cc common-lisp emacs-lisp latex markdown org python sh yaml :config (default +bindings +smartparens))
        packages   (n/a)
        unpin      (n/a)
        elpa       (n/a)
```
</pre></details>

**Comment by sirenko** [comment]
+1, mac os, emacs 27.1 from nix packages

```
Debugger entered--Lisp error: (error "magit-dispatch is not a transient command")
  signal(error ("magit-dispatch is not a transient command"))
  error("%s is not a transient command" magit-dispatch)
  transient--layout-member(magit-worktree magit-dispatch)
  transient--insert-suffix(magit-dispatch magit-worktree ("%" "Gitflow" magit-gitflow-popup) replace)
  transient-replace-suffix(magit-dispatch magit-worktree ("%" "Gitflow" magit-gitflow-popup))
[..skip...]
```

**Comment by gagbo** [comment]
#4339 fixes it

run `git fetch origin refs/pull/4339/head && git checkout FETCH_HEAD` until it's merged
(run `git checkout develop && git pull` once it's merged)

**Comment by gagbo** [comment]
(Don't mind the doom-bot message, Discourse is not public yet)

**Comment by leoxiaobin** [comment]
#4339 Fixes it. It works for me.

**Comment by gagbo** [comment]
Can you keep it open until the fix is merged please ? It'll help other people find the issue and the resolution more quickly

**Comment by hlissner** [comment]
#4339 has been merged. Sorry for the trouble!
