### ISSUE TITLE
Searching for program : no such file or directory : gnuplot 

### ISSUE THREAD

**Issue by cakarmustactalone** [hlissner/doom-emacs#4354]
I added +gnuplot     lang : org  , but still outputs this , I have istalled gnuplot, and gnuplot-mode but still same , I m newbie in linux and emacs btw 

Ty

**Comment by iyefrat** [comment]
did you do `doom sync`?

**Comment by cakarmustactalone** [comment]
> did you do `doom sync`?

yes ofc

**Comment by hlissner** [comment]
If you're certain `gnuplot` is in your `PATH`, run `doom env` and restart Emacs. See `doom help env` for what this does. You only need to do this anytime your shell environment changes and you want Emacs do be able to see those changes.

**Comment by cakarmustactalone** [comment]
> If you're certain `gnuplot` is in your `PATH`, run `doom env` and restart Emacs. See `doom help env` for what this does. You only need to do this when your shell environment changes and you want Emacs do be able to see those changes.
> 
> Also, in the future, **please do not ignore the issue template.** It asks you to include your `M-x doom/info`.

SYSTEM  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/bash
        uname      Linux 5.4.0-56-generic #62-Ubuntu SMP Mon Nov 23 19:20:19 UTC 2020 x86_64
        path       (~/.emacs.d/bin /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /usr/games /usr/local/games /snap/bin /usr/lib/emacs/26.3/x86_64-linux-gnu/)
EMACS   dir        ~/.emacs.d/
        version    26.3
        build      Mar 26, 2020
        buildopts  --build x86_64-linux-gnu --prefix=/usr --sharedstatedir=/var/lib --libexecdir=/usr/lib --localstatedir=/var/lib --infodir=/usr/share/info --mandir=/usr/share/man --enable-libsystemd --with-pop=yes --enable-locallisppath=/etc/emacs:/usr/local/share/emacs/26.3/site-lisp:/usr/local/share/emacs/site-lisp:/usr/share/emacs/26.3/site-lisp:/usr/share/emacs/site-lisp --with-sound=alsa --without-gconf --with-mailutils --build x86_64-linux-gnu --prefix=/usr --sharedstatedir=/var/lib --libexecdir=/usr/lib --localstatedir=/var/lib --infodir=/usr/share/info --mandir=/usr/share/man --enable-libsystemd --with-pop=yes --enable-locallisppath=/etc/emacs:/usr/local/share/emacs/26.3/site-lisp:/usr/local/share/emacs/site-lisp:/usr/share/emacs/26.3/site-lisp:/usr/share/emacs/site-lisp --with-sound=alsa --without-gconf --with-mailutils --with-x=yes --with-x-toolkit=gtk3 --with-toolkit-scroll-bars 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/emacs-mEZBk7/emacs-26.3+1=. -fstack-protector-strong -Wformat -Werror=format-security -Wall' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro'
        features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS LIBSYSTEMD LCMS2
        traits     (gui server-running envvar-file)
DOOM    dir        ~/.doom.d/
        version    2.0.9
        font       #<font-spec nil nil monospace nil nil semi-light nil nil 12 nil nil nil nil>
        theme      doom-palenight
        build      HEAD -> develop f622d5171 2020-12-01 18:09:43 -0500
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard hl-todo modeline ophints (popup +defaults) vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold snippets :emacs (dired +icons) electric undo vc :checkers syntax :tools (eval +overlay) lookup magit :lang cc emacs-lisp markdown (org +pretty +present +gnuplot) sh :config (default +bindings +smartparens))
        packages   ((evil-tutor) (org-super-agenda) (gnuplot))
        unpin      (n/a)
        elpa       (tablist shadchen seethru pdf-tools gnuplot-mode gnuplot)
```
I got this output when I `M-x doom/info`, what to do I dunno , I runned doom env  and restarted still same sorry for my less-knowledge .

**Comment by hlissner** [comment]
Ah, I think I see the problem. You've installed `gnuplot` multiple times, once with `:lang org`'s `+gnuplot` module, again with a `package!` statement in `~/.doom.d/packages.el, and again with `package.el` (e.g. `M-x package-install`?). This will confuse Emacs if you don't know what you're doing.

1. Remove any `:ensure t` or `package-install` lines in your config.el.
2. Have the `:lang (org +gnuplot)` module enabled.
3. Remove any `(package! gnuplot)` lines in `~/.doom.d/packages.el`
4. Run `doom sync -p` to resync your config and purge your ELPA packages.

Then restart Emacs and see if the issue has fixed itself.

**Comment by cakarmustactalone** [comment]
Still same error ,  In my /.doom.d directory "custom.el" exist now noticed it , anyway my /.doom.d/config.el file:

`;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-

;; Place your private configuration here! Remember, you do not need to run 'doom
;; sync' after modifying this file!

(setq
    org-superstar-headline-bullets-list '("⁖" "◉" "○" "✸" "✿")
)

(setq doom-theme 'doom-palenight)

;; Some functionality uses this to identify you, e.g. GPG configuration, email
;; clients, file templates and snippets.
(setq user-full-name "John Doe"
      user-mail-address "john@doe.com")

;; Doom exposes five (optional) variables for controlling fonts in Doom. Here
;; are the three important ones:
;;
;; + `doom-font'
;; + `doom-variable-pitch-font'
;; + `doom-big-font' -- used for `doom-big-font-mode'; use this for
;;   presentations or streaming.
;;
;; They all accept either a font-spec, font string ("Input Mono-12"), or xlfd
;; font string. You generally only need these two:
 (setq doom-font (font-spec :family "monospace" :size 12 :weight 'semi-light)
       doom-variable-pitch-font (font-spec :family "sans" :size 15))

;; There are two ways to load a theme. Both assume the theme is installed and
;; available. You can either set `doom-theme' or manually load a theme with the
;; `load-theme' function. This is the default:
;;(setq doom-theme 'doom-one)

;; If you use `org' and don't want your org files in the default location below,
;; change `org-directory'. It must be set before org loads!
(setq org-directory "~/org/")

;; This determines the style of line numbers in effect. If set to `nil', line
;; numbers are disabled. For relative line numbers, set this to `relative'.
(setq display-line-numbers-type t)

`

**Comment by hlissner** [comment]
Then an error was likely missed when you first ran `doom install`. Delete `~/.emacs.d/.local/straight`, run `doom sync`, and see if the issue goes away.

**Comment by cakarmustactalone** [comment]
Still same error and when I start I got this:

> Warning (initialization): An error occurred while loading ‘/home/user/.emacs.d/init.el’:

>End of file during parsing: /home/user/.doom.d/custom.el

>To ensure normal operation, you should investigate and remove the
>cause of the error in your initialization file.  Start Emacs with
>the ‘--debug-init’ option to view a complete error backtrace.

.

I think re-installation of doom-emacs can be helpfull, shoul I do ? and deleting .doom.d and .emacs.d after reinstallation can be performed?

**Comment by hlissner** [comment]
> End of file during parsing: /home/user/.doom.d/custom.el

This is an unrelated error. You'll have to inspect custom.el. In fact, I suggest you delete it (and avoid using `M-x customize` or other `customize-*` commands in the future).

> I think re-installation of doom-emacs can be helpfull, shoul I do ?

May as well try. Although, deleting `~/.emacs.d/.local/straight` and running `doom sync` is close to reinstalling Doom anyway.

**Comment by cakarmustactalone** [comment]
Sorry for late response, had some pandemic stuffs. 
I have re-installed emacs 27 and doom emacs , after running doom doctor, it says this errors too;

`:lang markdown
      ! Couldn't find a markdown compiler, `markdown-preview' won't work
    > :lang org
      ! Couldn't find gnuplot. org-plot/gnuplot will not work
    > :lang sh
      ! Couldn't find shellcheck. Shell script linting will not work
`
Actually I dont care markdown and shellcheck , but gnuplot would be good. If no-solution method for this anymore, please close that issue, I do not want to take your time .

**Comment by nbfalcon** [comment]
@cakarmustactalone can you run `gnuplot` from your normal OS terminal? And can you do the same from `M-x eshell`?

**Comment by cakarmustactalone** [comment]
> @cakarmustactalone can you run `gnuplot` from your normal OS terminal? And can you do the same from `M-x eshell`?

actually no, should I install it via `sudo apt-get install gnuplot` ? I thought that it is installed  by  `+gnuplot ` code into the `(org +gnuplot) ` , am I wrong ?

**Comment by nbfalcon** [comment]
@cakarmustactalone yes, you need to install that program separately. (org +gnuplot) only installs plugins to aid in using it.

**Comment by cakarmustactalone** [comment]
> @cakarmustactalone yes, you need to install that program separately. (org +gnuplot) only installs plugins to aid in using it.

thanks mate , I m  grateful to you , really need that for my works .
