### ISSUE TITLE
Accepting completion with enter does not display documentation in bottom bar until deleting and retyping the parentheses

### ISSUE THREAD

**Issue by rsheasby** [hlissner/doom-emacs#4355]
**What did you expect to happen?**
When accepting an autocompletion suggestion using enter, the bottom bar should immediately show the documentation for the newly completed function.

**What actually happened?**
The bottom bar does not show the documentation until you delete and retype the parentheses.

**Additional details:**
You can see a video of the issue displayed here:
https://www.youtube.com/watch?v=-zWZbtN9YIg

**Steps to reproduce:**
1. Select an autocompletion using enter
2. Observe that documentation is not shown in bottom bar.
3. ...
4. Profit?

**System information:**
<details><pre>
SYSTEM  type       darwin
        config     x86_64-apple-darwin20.1.0
        shell      /usr/local/bin/fish
        uname      Darwin 20.1.0 Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:11 PDT 2020; root:xnu-7195.50.7~2/RELEASE_X86_64 x86_64
        path       (/opt/local/bin /Applications/MacPorts/Emacs.app/Contents/MacOS ~/go/bin/ /usr/local/bin /usr/bin /bin /usr/sbin /sbin /usr/local/go/bin /usr/local/MacGPG2/bin /Applications/MacPorts/Emacs.app/Contents/MacOS/libexec/ ~/go/bin)
EMACS   dir        ~/.emacs.d/
        version    27.1
        build      Dec 02, 2020
        buildopts  --prefix=/opt/local --disable-silent-rules --without-dbus --without-gconf --without-libotf --without-m17n-flt --with-gmp --with-gnutls --with-json --with-xml2 --with-modules --infodir /opt/local/share/info/emacs --with-ns --with-lcms2 --without-harfbuzz --without-imagemagick --without-xaw3d --with-rsvg 'CFLAGS=-pipe -Os -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk -arch x86_64' 'CPPFLAGS=-I/opt/local/include -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk' 'LDFLAGS=-L/opt/local/lib -Wl,-headerpad_max_install_names -Wl,-no_pie -Wl,-syslibroot,/Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk -arch x86_64'
        features   RSVG GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS XIM NS MODULES THREADS JSON PDUMPER LCMS2 GMP
        traits     (gui server-running envvar-file)
DOOM    dir        ~/Documents/dotfiles/doom-emacs/
        version    2.0.9
        font       #<font-spec nil nil Hack nil nil nil nil nil 14 nil nil nil nil>
        theme      doom-dracula
        build      HEAD -> develop, origin/develop, origin/HEAD cb32e459e 2020-11-29 19:34:54 -0500
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline ophints (popup +defaults) vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold snippets :emacs dired electric undo vc :checkers syntax :tools (eval +overlay) lookup lsp magit :os macos :lang emacs-lisp (go +lsp) markdown org sh :config (default +bindings +smartparens))
        packages   ((inertial-scroll :recipe (:host github :repo kiwanami/emacs-inertial-scroll)) (centaur-tabs))
        unpin      (n/a)
        elpa       (n/a)
</pre></details>

**Comment by hlissner** [comment]
Seems [there's an old issue open for this in the company-mode project](https://github.com/company-mode/company-mode/issues/797).

Try adding this to your config.el:

```elisp
(after! eldoc
  (eldoc-add-command-completions "company-"))
```

**Comment by rsheasby** [comment]
Just tried that and no luck unfortunately. How can I debug this further?

**Comment by rsheasby** [comment]
It seems that only a strangely small subset of the company commands are actually being added to eldoc-message-commands:

```
[evil-window-split evilem-motion-find-char evilem-motion-search-word-backward company-dabbrev-code evilem--motion-function-evil-backward-arg company-css evilem-motion-search-word-forward evilem-motion-search-previous evilem-motion-find-char-backward evil-avy-goto-line evilem-motion-backward-sentence-begin evil-snipe-S evilem-motion-forward-section-begin evilem-motion-next-line evil-window-increase-width company-bbdb evilem-motion-forward-sentence-begin evilem-motion-next-line-first-non-blank evilem-motion-backward-word-begin evilem-motion-backward-WORD-begin company-abbrev lsp-ui-peek-jump-forward evilem-motion-search-next evilem-motion-find-char-to-backward evilem-motion-previous-line evil-snipe-repeat-reverse evilem-motion-backward-word-end evilem-motion-previous-visual-line lsp-ui-peek-jump-backward evilem-motion-find-char-to evilem-motion-backward-WORD-end]
```

Notably, it's not adding the company-complete* commands to the list. Could this be a plugin interaction problem?

**Comment by hlissner** [comment]
Oh, there was a load order issue in the snippet I gave you. Update Doom to a9f57f1 and see if it fixes your issue.

**Comment by rsheasby** [comment]
No luck I'm afraid. There are a few more company- commands this time around, but still not all the company-complete commands are being added.

```
[evil-window-split evilem-motion-find-char evilem-motion-search-word-backward company-dabbrev-code evilem--motion-function-evil-backward-arg company-css evilem-motion-search-word-forward evilem-motion-search-previous evilem-motion-find-char-backward evil-avy-goto-line evilem-motion-backward-sentence-begin company-complete-selection evilem-motion-forward-section-begin evilem-motion-next-line evil-window-increase-width company-bbdb company-abort evilem-motion-next-line-first-non-blank evilem-motion-backward-word-begin evilem-motion-backward-WORD-begin company-abbrev lsp-ui-peek-jump-forward evilem-motion-search-next evilem-motion-find-char-to-backward evil-surround-line evil-snipe-repeat-reverse evilem-motion-backward-word-end evilem-motion-previous-visual-line lsp-ui-peek-jump-backward evilem-motion-find-char-to evilem-motion-backward-WORD-end]
```

I can get even more of the company commands added to the list by doing the following:
```
(after! eldoc
  (after! company
    (eldoc-add-command-completions "company-")))
```

Which I assume waits for both eldoc and company to be properly loaded, but even this doesn't work. Here's the list after doing that:

```
[company-select-next-or-abort yas-expand-from-keymap company-select-next-if-tooltip-visible-or-complete-selection company-dabbrev-code yas-next-field-or-maybe-expand company-css company-tng-configure-default company-next-page company-search-delete-char evil-avy-goto-line company-manual-begin company-complete company-select-next company-complete-common-or-cycle company-search-keypad company-show-location company-shell company-search-repeat-backward company-search-mode company-dict company-abbrev lsp-ui-peek-jump-forward yas-expand company-ispell evil-surround-line company-filter-candidates company-begin-backend company-search-printing-char lsp-ui-peek-jump-backward company-search-candidates yas-prev-field]
```

**Comment by hlissner** [comment]
> but still not all the company-complete commands are being added.

So you did or you didn't update Doom? I'm only adding three commands in a9f57f1.

Try whitelisting `company-capf` and `company-go`. If that doesn't work I'm stumped -- I can no longer reproduce the issue after a9f57f1 in other LSP-enabled major modes, and I don't have an MVE setup for go to test further.

**Comment by rsheasby** [comment]
Yup. I updated to the latest develop. I've tried whitelisting company-capf and company-go too, but still no luck whatsoever. Could there be another plugin that's hijacking the echo area immediately after company writes to it?
