### ISSUE TITLE
Current buffer has no process bug

### ISSUE THREAD

**Issue by azy2** [hlissner/doom-emacs#436]
I'm running into a bug in which buffers associated with processes are getting their process killed after a few seconds. Reproducing this is easy enough on my machine:

1. Start emacs
2. M-x multi-term
3. Hold a key down for a few seconds

At some point it will stop and say "Current buffer has no process" in the echo area.

I've found that commenting out `+all` in the `popup` section of init.el seems to get rid of the problem. So that may be somewhere to start looking. I'll let you know if I find anything else.

**Comment by hlissner** [comment]
I'm having trouble reproducing this. The `feature/popup` module _does_ have a popup/process cleanup function, but it only runs after a popup window has been closed (and only for the specific buffer of the window that was closed).

`M-x multi-term` doesn't open a popup, however. So there is no concievable way for it to trigger that functionality.

**Comment by azy2** [comment]
Hmmm, I can't get multi-term to work anymore either. I think it might have something to do with being excluded from persp-mode because recently I started adding multi-term buffers to persp-mode.

But I can reproduce the bug another way. If you delete your rtags install folder and visit a C/C++ file it will complain that rtags isn't installed. Run `M-x rtags-install` and sometimes the process will get killed in the middle of the install. Sometimes immediately for me, sometimes not at all. I'm sorry I'm having trouble finding a more consistent example.

**Comment by hlissner** [comment]
I think I know what you are describing. I've experienced myself; it's difficult to reproduce, but I am almost sure of its cause.

I've pushed a possible fix for it, but it needs more testing. Please update and let me know if the issue resurfaces.

**Comment by UndeadKernel** [comment]
I'm experiencing this same problem when using `+term/open-popup` or `multi-term`.
I think I've found a way to reproduce it:

1) Open a `+term/open-popup`.
2) Check the keybinding associated with `C-p` (non-evil emacs: `C-h k`)
3) Quit the help buffer
4) Check the keybinding associated with `C-n` (non-evil emacs: `C-h k`)
5) Quit the help buffer
6) Try to display the last CLI command with `M-p (for non-evil users), which calls `term-send-up`

After these steps, the term buffer will no longer have a process alive.

**Comment by hlissner** [comment]
@UndeadKernel Thank you! That was exactly what I needed to solve this elusive bug. As of a77a967 this should be resolved. Let me know if the issue resurfaces!
