### ISSUE TITLE
git-gutter not shown

### ISSUE THREAD

**Issue by y0105w49** [hlissner/doom-emacs#4369]
**What did you expect to happen?**
The git status colour indicator in the fringe should be shown.

**What actually happened?**
Nothing is shown.

**Additional details:**
- This worked for me until recently (sometime in the last month).  Updating doom today didn't fix it.
- Also occurs in sandbox mode (with doom+modules)
- The only way I could get it to work again is by setting `fringe-mode` to at least 8, but this makes the fringe too wide, as there's now a black strip to the left of the status indicator as you can see in this screenshot: ![image](https://user-images.githubusercontent.com/1349935/101122590-dba5c800-35c0-11eb-9eb3-12a6ab10716c.png)
- `git-gutter:popup-hunk` still works, so this seems to only be a display issue
- Nothing related in \*Messages\*
- Re-enabling `{global-,}git-gutter-mode` doesn't fix it

**Steps to reproduce:**
1. Open any git-tracked file

**System information:**
<details><pre>
SYSTEM  type       darwin
        config     x86_64-apple-darwin19.5.0
        shell      /nix/store/sk74ylfycb7kmkmrc1wy78n8g5kv64l0-bash-interactive-4.4-p23/bin/bash
        uname      Darwin 20.1.0 Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:11 PDT 2020; root:xnu-7195.50.7~2/RELEASE_X86_64 x86_64
        path       (~/.idris2/bin ~/Library/Python/3.8/bin ~/.emacs.d/bin ~/Dropbox/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /Library/Apple/usr/bin /Library/TeX/texbin ~/.nix-profile/bin /etc/profiles/per-user/$USER/bin /run/current-system/sw/bin /nix/var/nix/profiles/default/bin /usr/local/Cellar/emacs-plus@27/27.1/libexec/emacs/27.1/x86_64-apple-darwin19.5.0/)
EMACS   dir        ~/.emacs.d/
        version    27.1
        build      Aug 27, 2020
        buildopts  --disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus@27/27.1/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus@27/27.1 --with-xml2 --with-gnutls --without-dbus --with-imagemagick --with-modules --with-rsvg --with-ns --disable-ns-self-contained
        features   RSVG IMAGEMAGICK GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS JSON PDUMPER LCMS2 GMP
        traits     (gui server-running envvar-file)
DOOM    dir        /nix/store/7l58dfynkq6fixk271xafixvkxy0am21-hm_doom/
        version    2.0.9
        font       #<font-spec nil nil Source Code Pro nil nil nil nil nil 14 nil nil nil nil>
        theme      doom-one
        build      HEAD -> develop d88e0795b 2020-12-02 17:58:10 -0500
        elc-files  0
        modules    (:completion (company +tng) ivy :ui doom doom-dashboard doom-quit hl-todo indent-guides modeline nav-flash ophints (popup +defaults) treemacs unicode vc-gutter vi-tilde-fringe window-select workspaces zen :editor (evil +everywhere) file-templates fold multiple-cursors snippets word-wrap :emacs dired electric undo vc :checkers syntax (spell +everywhere +flyspell +hunspell) grammar :tools biblio docker editorconfig (eval +overlay) lookup lsp magit :os macos tty :lang cc data emacs-lisp idris (latex +latexmk) ledger markdown nix ocaml org python sh yaml :config (default +bindings +smartparens))
        packages   ((company-tabnine) (idris-mode :pin f2c00bd8065f141bb08ea5c3c57c805b4b0fad09 :recipe (:host github :repo scotek/idris-mode)) (ebib))
        unpin      (n/a)
        elpa       (n/a)
</pre></details>

**Comment by yogsototh** [comment]
I put that in my `config.el` as workaround:

```elisp
;; set left margin to show git-gutter again
(setq-default left-margin-width 1)
(set-window-buffer nil (current-buffer))
```

**Comment by dmcardle** [comment]
I am also running into this (or a similar issue) with Emacs 27.1 on macOS 11.2.1.

I used to see the version control gutter, but at some point in the last few weeks it disappeared. Unfortunately, @yogsototh's workaround didn't work for me.

Here's my workaround:

``` elisp
;; config.el
(add-hook! 'doom-init-ui-hook (fringe-mode nil))
```

**Comment by duduribeiro** [comment]
I tried both @dmcardle and @yogsototh solutions and it did not work for me. I'm was on osx with emacs-plus@27

Installing emacs-plus@28 worked fine

**Comment by Cerebus** [comment]
> I tried both @dmcardle and @yogsototh solutions and it did not work for me. I'm was on osx with emacs-plus@27
> 
> Installing emacs-plus@28 worked fine

Same here.  emacs-plus@27 -- no fringe.  emacs-plus@28 -- fringe.
