### ISSUE TITLE
Loading a custom doom theme seems to be switching bg and a base

### ISSUE THREAD

**Issue by Ultramann** [hlissner/doom-emacs#4379]
This seems to be close to a duplicate of the final misbehavior in #2732; aka, my theme is loading, but my background color is only on the current line, and the rest of the background is base...4 (I think? I can find out if needed).

**Repro steps:**
1. made a custom theme based off of a random one in [emacs-doom-themes](https://github.com/hlissner/emacs-doom-themes)
1. updated the theme name in all the places
1. mapped the required faces
1. overrode`line-numbers`
1. saved the theme in `.doom.d/themes`
1. added `(setq doom-theme 'my-theme)` in my `.doom.d/config.el`

This resulted in the theme not being loaded and what I think is the default emacs dark theme to load? So I added a `provide-theme` at the bottom of my theme file. Things looked good on load, the doom home screen seemed to have the right theme, background color and all; same with a dired buffer. But when I opened a file I found a buffer with the primary background color being one of the bases. This happens for all text files I've tried to open so far, and is consistent after restarting emacs.

**What did you expect to happen?**
The color I define for `bg`, black, in my custom doom-theme to be the primary background when editing a file.

**Additional details:**
Here's a dired buffer:
![image](https://user-images.githubusercontent.com/9347171/101271200-51876c00-3746-11eb-9e4a-988a45b83b04.png)
And part of my theme file:
![image](https://user-images.githubusercontent.com/9347171/101271186-39175180-3746-11eb-8dc3-d157182f47a7.png)

I just started playing with doom today coming from vanilla emacs and am loving it so far. Many thanks for all the work done by contributors to this project and thanks for any help in advance!

**System information:**
<details><pre>
SYSTEM  type       darwin
	config     x86_64-apple-darwin19.5.0
	shell      /usr/local/bin/bash
	uname      Darwin 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64
	path       (/usr/local/Cellar/pyenv-virtualenv/1.1.5/shims ~/.pyenv/shims ~/.pyenv/bin ~/.emacs.d/bin /usr/local/Cellar/pyenv-virtualenv/1.1.5/shims ~/.pyenv/shims ~/.pyenv/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /usr/local/Cellar/emacs-plus@27/27.1/libexec/emacs/27.1/x86_64-apple-darwin19.5.0)
EMACS   dir        ~/.emacs.d/
	version    27.1
	build      Nov 14, 2020
	buildopts  --disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus@27/27.1/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus@27/27.1 --with-xml2 --with-gnutls --without-dbus --with-imagemagick --with-modules --with-rsvg --with-ns --disable-ns-self-contained
	features   RSVG IMAGEMAGICK GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS JSON PDUMPER LCMS2 GMP
	traits     (batch server-running envvar-file)
DOOM    dir        ~/.doom.d/
	version    2.0.9
	build      HEAD -> develop, origin/develop, origin/HEAD d88e0795b 2020-12-02 17:58:10 -0500
	elc-files  0
	modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo ophints (popup +defaults) vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold snippets :emacs dired electric undo vc :term vterm :checkers syntax spell :tools (eval +overlay) lookup magit :os macos :lang emacs-lisp markdown org python sh yaml :config (default +bindings +smartparens))
	packages   (n/a)
	unpin      (n/a)
	elpa       (swiper rainbow-mode ivy hydra counsel company)
</pre></details>

**Comment by hlissner** [comment]
This is not a bug. This is [solaire-mode](https://github.com/hlissner/emacs-solaire-mode)'s work. Disable it, or disable the `:ui doom` module if you're not using a Doom theme.

**Comment by Ultramann** [comment]
Ah. That make sense. Thanks again!
