### ISSUE TITLE
LSP :: Error from the Language Server: Rust Analyzer is still loading... (Unknown error)

### ISSUE THREAD

**Issue by sseneca** [hlissner/doom-emacs#4380]
**What did you expect to happen?**

`rust-analyzer` to start.

**What actually happened?**

`LSP :: Error from the Language Server: Rust Analyzer is still loading... (Unknown error) [5 times]`

**Additional details:**
- [Configs here](https://git.ssene.ca/sseneca/dotfiles/src/branch/main/dot_config/doom) (nothing interesting relating to Rust apart from enabling it and doing `+lsp` in `init.el`).
- Messages:

```
LSP :: Connected to [rust-analyzer:16305 status:starting].
Note: rustic-indent-offset, tab-width, evil-shift-width adjusted to 4
Error in rustic-flycheck-setup: (user-error "/usr/bin/cargo metadata --no-deps --manifest-path /home/sseneca/documents/programming/eldiro/Cargo.toml --format-version 1 exited with 1.") [2 times]
LSP :: rust-analyzer:16305 initialized successfully
Error in rustic-flycheck-setup: (user-error "/usr/bin/cargo metadata --no-deps --manifest-path /home/sseneca/documents/programming/eldiro/Cargo.toml --format-version 1 exited with 1.")
LSP :: rust-analyzer failed to load workspace: "cargo" "--version" failed, exit code: 1
stderr:
error: no override and no default toolchain set

LSP :: Error from the Language Server: Rust Analyzer is still loading... (Unknown error) [5 times]
```

`no default toolchain set` is weird because I *have* run `rustup default stable`.

I can't get a backtrace because when I open a Rust file in debug mode emacs will completely lock up, though the mini-buffer will cycle between "Garbage collecting" and "LSP :: Error from the Language Server: Rust Analyzer is still loading... (Unknown error)".

**Steps to reproduce:**
1. Install `rust-analyzer` backend
2. Try to open a Rust project

**System information:**
<details><pre>
```
SYSTEM  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /usr/bin/zsh
        uname      Linux 5.9.12-gnu-1 #1 SMP PREEMPT Wed, 02 Dec 2020 22:55:25 +0000 x86_64
        path       (/usr/local/bin /usr/bin /usr/lib/emacs/27.1/x86_64-pc-linux-gnu)
EMACS   dir        ~/.config/emacs/
        version    27.1
        build      Aug 28, 2020
        buildopts  --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-wide-int --with-modules --with-cairo --with-harfbuzz 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
        features   XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP
        traits     (gui daemon server-running)
DOOM    dir        ~/.config/doom/
        version    2.0.9
        font       #<font-spec nil nil Source Code Pro nil nil nil nil nil 20 nil nil nil nil>
        theme      doom-one
        build      HEAD -> develop, origin/develop, origin/HEAD 9137cbaaa 2020-12-05 16:57:31 -0500
        elc-files  0
        modules    (:completion company ivy :ui deft doom doom-dashboard doom-quit hl-todo indent-guides ligatures minimap modeline ophints (popup +defaults) tabs treemacs unicode vc-gutter vi-tilde-fringe workspaces zen :editor (evil +everywhere) file-templates fold (format +onsave) multiple-cursors snippets word-wrap :emacs (dired +ranger +icons) electric undo vc :term vterm :checkers syntax spell grammar :tools docker editorconfig (eval +overlay) lookup lsp magit make pdf :os tty :lang cc data emacs-lisp json (javascript +lsp) latex markdown (org +hugo +pandoc +roam) (python +lsp) (rust +lsp) sh yaml :email mu4e :config (default +bindings +smartparens))
        packages   ((mu4e-alert) (renpy))
        unpin      (n/a)
        elpa       (n/a)
```

</pre></details>

I tried out Emacs 28 for a bit and assumed that was why I was having trouble but even after downgrading to Emacs 27 (and running `doom sync` and `doom build` the error persists).

**Comment by vikigenius** [comment]
I can reproduce the Rust Analyzer is still loading error on Emacs 27

**Comment by chunningham** [comment]
With the same steps this can be reproduced with gccemacs and causes a fatal crash.

**Comment by yaabdalla** [comment]
Running on emacs native-comp branch (gccemacs), +1 on repro.

**Comment by hlissner** [comment]
I cannot reproduce this and cannot find any leads within Doom. Enable debug mode (`SPC h d d` or `C-h d d`) then check the `*lsp-log*` buffer (`SPC b B` or `C-x b`) to switch to it.

If you can't find any leads there, try to reproduce the issue in [vanilla Emacs](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#testing-in-dooms-sandbox).

I suspect this is an external issue and may need to be brought up to one of the lsp-mode or rust-analyzer projects.

**Comment by sseneca** [comment]
No leads with from `*lsp-lop*`:

```
Command "rls" is present on the path.
Command "/usr/bin/rust-analyzer" is present on the path.
Command "rls" is present on the path.
Command "/usr/bin/rust-analyzer" is present on the path.
Found the following clients for /home/sseneca/documents/programming/hola/src/main.rs: (server-id rls, priority -1), (server-id rust-analyzer, priority 1)
The following clients were selected based on priority: (server-id rust-analyzer, priority 1)
```

I don't know how vanilla Emacs works (I opened `main.rs` and whilst it loaded it into the editor, I don't think LSP loaded, nothing else happened), but I did try vanilla Doom and the same exact issue happened there. So I'll probably open an issue with rust-analyzer or lsp-mode (probably rust-analyzer first).

Not sure if this issue should be closed or if it should remain tracked until the culprit is found?

**Comment by katticot** [comment]
I had the same issue.
Add a cargo.toml with cargo init solved my problem.

**Comment by vikigenius** [comment]
@katticot I already have a Cargo.toml file in my root directory? Do you mean to say that this issue is solved only if you add it using cargo init ?

**Comment by nerrons** [comment]
@katticot Yes I also can't solve the issue with Cargo.toml already there.

**Comment by vikigenius** [comment]
I think the only possibility I see is that, Rust Analyzer actually takes a while to fully load (I can actually see the progressbar sometimes) and it sends this message to indicate that it's loading. But somehow the lsp-client interpets it as an error.

**Comment by Sparkenstein** [comment]
Had the same issue, I bootstrapped the project with `cargo new proj`.
but it was giving the same error. after reading @katticot s solution, I ran `cargo init` from vterm anyway. after that 
it started working normally. not sure what's going wrong here if multiple people are having same problem

**Comment by bjornmossa** [comment]
@sseneca, did rusr-analyzer works withiut emacs? (for ex. : rust-analyzer analysis-stats . )?

**Comment by sseneca** [comment]
The original bug is from about 6 months ago. I don't think I ever ran that command back then but I have been using rust-analyzer with neovim since and I've had no issues, so I can only assume it was an issue specific to emacs.

Seeing as I don't use emacs any more and it doesn't look like this issue is going anywhere, I'm closing this.

**Comment by pkazmier** [comment]
I had this same error having come back to rust coding after quite some time. For me, it turned out that rust-analyzer was panicking (seen in the `*rust-analyzer::stderr*` buffer). I then installed the latest version of rust-analyzer from source, and the problem went away.
