### ISSUE TITLE
mu server won't be killed when quit mu4e

### ISSUE THREAD

**Issue by chengyi** [hlissner/doom-emacs#4385]
**What did you expect to happen?**
`mu` server quits when quitting mu4e while `*mu4e-update*` buffer showing.

**What actually happened?**
when I hit `U` to receive email, while the `*mu4e-update*` buffer showing, press `q`, then mu4e quits. 
finally re-enter `mu4e`, it report
```
error in process filter: mu4e-error-handler: Error 1: cannot open database @ /home/xxx/.cache/mu/xapian; already running? if not, please try 'mu init '
error in process filter: Error 1: cannot open database @ /home/xxx/.cache/mu/xapian; already running? if not, please try 'mu init '
error in process sentinel: mu4e~proc-sentinel: Mu server process ended with exit code 1
error in process sentinel: Mu server process ended with exit code 1

```

obviously, `mu` server is not quit, but just waiting  `*mu4e-update*` buffer disappear, then press `q`, this error disappears too.

**Additional details:**

<details><pre>
Debugger entered--Lisp error: (error "Error 1: cannot open database @ /home/xxxx/.cache/...")
  signal(error ("Error 1: cannot open database @ /home/xxxx/.cache/..."))
  error("Error %d: %s" 1 "cannot open database @ /home/xxxx/.cache/mu/xapian...")
  mu4e-error-handler(1 "cannot open database @ /home/xxxx/.cache/mu/xapian...")
  mu4e~proc-filter(#<process  *mu4e-proc*> "\37679\377(:error 1 :message \"cannot open database @ /ho...")
  apply(mu4e~proc-filter (#<process  *mu4e-proc*> "\37679\377(:error 1 :message \"cannot open database @ /ho..."))
  explain-pause--wrap-callback(#s(explain-pause-command-record :command process-filter :native nil :parent #s(explain-pause-command-record :command " *mu4e-proc*" :native nil :parent #s(explain-pause-command-record :command =mu4e :native nil :parent #s(explain-pause-command-record :command root-emacs :native nil :parent nil :executing-time 1777 :entry-snap (24526 65158 3713 416000) :too-slow nil :is-profiled nil :under-profile nil :profile nil :depth 0) :executing-time 2 :entry-snap (24526 65158 321 400000) :too-slow nil :is-profiled nil :under-profile nil :profile nil :depth 1) :executing-time 0 :entry-snap nil :too-slow nil :is-profiled nil :under-profile nil :profile nil :depth 2) :executing-time 0 :entry-snap nil :too-slow nil :is-profiled nil :under-profile nil :profile nil :depth 3) mu4e~proc-filter #<process  *mu4e-proc*> "\37679\377(:error 1 :message \"cannot open database @ /ho...")
  apply(explain-pause--wrap-callback #s(explain-pause-command-record :command process-filter :native nil :parent #s(explain-pause-command-record :command " *mu4e-proc*" :native nil :parent #s(explain-pause-command-record :command =mu4e :native nil :parent #s(explain-pause-command-record :command root-emacs :native nil :parent nil :executing-time 1777 :entry-snap (24526 65158 3713 416000) :too-slow nil :is-profiled nil :under-profile nil :profile nil :depth 0) :executing-time 2 :entry-snap (24526 65158 321 400000) :too-slow nil :is-profiled nil :under-profile nil :profile nil :depth 1) :executing-time 0 :entry-snap nil :too-slow nil :is-profiled nil :under-profile nil :profile nil :depth 2) :executing-time 0 :entry-snap nil :too-slow nil :is-profiled nil :under-profile nil :profile nil :depth 3) mu4e~proc-filter (#<process  *mu4e-proc*> "\37679\377(:error 1 :message \"cannot open database @ /ho..."))
  #f(compiled-function (&rest callback-args) #<bytecode 0x1582432a1fc9>)(#<process  *mu4e-proc*> "\37679\377(:error 1 :message \"cannot open database @ /ho...")

</pre></details>

**Steps to reproduce:**
1. open `mu4e`
2. press `U`
3. quit `mu4e` when `*mu4e-update*` buffer exists.
4. re-enter `mu4e`

**System information:**
<details><pre>
```
SYSTEM  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /usr/bin/zsh
        uname      Linux 5.4.80-2-MANJARO #1 SMP PREEMPT Sat Nov 28 09:58:18 UTC 2020 x86_64
        path       (~/.local/bin /usr/local/bin /usr/bin /bin /usr/local/sbin /opt/android-ndk /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /usr/lib/emacs/27.1/x86_64-pc-linux-gnu)
EMACS   dir        ~/.emacs.d/
        version    27.1
        build      8月 29, 2020
        buildopts  --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-wide-int --with-modules --with-cairo --with-harfbuzz 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
        features   XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP
        traits     (gui server-running)
DOOM    dir        ~/.doom.d/
        version    2.0.9
        font       #<font-object -SAJA-Cascadia Code-normal-normal-normal-*-13-*-*-*-m-0-iso10646-1>
        theme      doom-miramare
        build      HEAD -> develop, origin/develop bc49b02dc 2020-12-07 14:04:52 +0800
        elc-files  0
        modules    (:completion company (ivy +fuzzy) :ui deft doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor file-templates fold format snippets :emacs dired electric undo vc :term vterm :checkers syntax :tools (eval +overlay) (lookup +docsets) lsp magit :lang (cc +lsp) data emacs-lisp javascript lua markdown org (python +lsp) (rust +lsp) (sh +zsh) (web +html +css) :email mu4e :config (default +bindings +smartparens) :private (&user prow-edit) (&user prow-c-c++) (&user prow-misc) (&user gtags))
        packages   ((cnfonts) (jinja2-mode) (mu4e-maildirs-extension :disable t) (org-mu4e :disable t) (glsl-mode :disable t) (opencl-mode :disable t) (disaster :disable t) (cuda-mode :disable t) (demangle-mode :disable t))
        unpin      (n/a)
        elpa       (n/a)
```

</pre></details>

**Comment by tecosaur** [comment]
Just tried this, couldn't reproduce.

**Comment by yevhenshymotiuk** [comment]
You should initialize your database first (`mu init -m <path-to-your-mail-directory>`). And then fill a database with your messages (`mu index`)
