### ISSUE TITLE
dired-do-find-regexp not working properly

### ISSUE THREAD

**Issue by thiagotps** [hlissner/doom-emacs#4386]
**What did you expect to happen?**
When I type **A** in a dired buffer with multiple files marked and enter a regex, I expect to popup a new buffer showing all the files that contains that regex.

**What actually happened?**
It says that no matching was found even when some of the files definitely contains the regex.

**Additional details:**
![cast](https://user-images.githubusercontent.com/8174647/101478347-4e9b9f80-392f-11eb-93eb-ded640d67b67.gif)

As showed in the gif above, with doom emacs the command fails while with "standard emacs"(i.e: emacs -Q) the command
performs correctly.

**Steps to reproduce:**
1. Go to a folder with multiple different files,
2. mark some of them,
3. press A and enter the desired regex and press enter.

**System information:**
```
SYSTEM  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /usr/bin/zsh
        uname      Linux 5.4.80-2-lts #1 SMP Sat, 28 Nov 2020 15:11:01 +0000 x86_64
        path       (~/.emacs.d/bin/ ~/.emacs.d/bin/ ~/.config/composer/vendor/bin ~/.emacs.d/bin ~/bin ~/.local/bin /usr/local/sbin /usr/local/bin /usr/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /usr/lib/emacs/27.1/x86_64-pc-linux-gnu/)
EMACS   dir        ~/.emacs.d/
        version    27.1
        build      Aug 16, 2020
        buildopts  --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=lucid --with-xft --without-gconf --without-gsettings --with-modules '--program-transform-name=s/^ctags$/ctags.emacs/' 'CFLAGS=-march=native -mtune=native -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
        features   XPM JPEG TIFF GIF PNG RSVG SOUND GPM DBUS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS LUCID X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP
        traits     (gui daemon server-running envvar-file)
DOOM    dir        ~/dotfiles/doom_emacs/.config/doom/
        version    2.0.9
        font       nil
        theme      doom-dracula
        build      HEAD -> develop 9137cbaaa 2020-12-05 16:57:31 -0500
        elc-files  0
        modules    (:completion (company +tng) ivy :ui doom doom-dashboard hl-todo modeline ophints (popup +defaults) window-select workspaces :editor (evil +everywhere) file-templates fold snippets :emacs dired electric ibuffer undo :term eshell vterm :checkers syntax :tools (eval +overlay) lookup lsp magit pdf :lang (cc +lsp) emacs-lisp (haskell +lsp) json (javascript +lsp) latex org (php +lsp) (python +lsp) (rust +lsp) (sh +lsp) web yaml :app (rss +org) :config literate (default +bindings +smartparens))
        packages   (n/a)
        unpin      (n/a)
        elpa       (n/a)
```

**Comment by hlissner** [comment]
This appears to be a bug with the [ivy-xref](https://github.com/alexmurray/ivy-xref) plugin calling `fetcher` twice [in ivy-xref-show-xrefs](https://github.com/alexmurray/ivy-xref/blob/master/ivy-xref.el#L90). The first time causes side-effects that impact the second execution (where it fails, throwing an error). 

I've employed a temporary workaround in fc9dd57 but please report this issue upstream, as it should be addressed there.
