### ISSUE TITLE
Failed to load module "canberra-gtk-module"

### ISSUE THREAD

**Issue by GiulioCentorame** [hlissner/doom-emacs#4388]
This might be two different problems, please tell me if that is the case and I will open two different issues.

**What did you expect to happen?**
Doom startup time normal (if not faster), no error messages via terminal on startup.
No issues on Doom on terminal during `doom sync`.

**What actually happened?**
I recently switched to gccemacs 28.0.50-110.0218ca6. While installing Doom, `doom sync` reported several errors and whenever I launch Emacs, it is sensibly slower and the terminal shows up an error related to `canberra-gtk-module`.

**Additional details:**
- [Private config](https://github.com/GiulioCentorame/.doom.d/tree/dev)
- No warnings with `M-x view-echo-area-messages`

<details><pre>

[`doom -d sync`](https://bin.idrix.fr/?18198d9a946d86b3#2es6CnHeie7ExMwWbfxHKksrhAVCzdaiZLU4rqVScRkn)

Running Emacs:
```
emacs --debug-init

(process:268759): Gtk-WARNING **: 16:20:06.121: Locale not supported by C library.
	Using the fallback 'C' locale.
Gtk-Message: 16:20:06.297: Failed to load module "canberra-gtk-module"
Gtk-Message: 16:20:06.297: Failed to load module "canberra-gtk-module"

```
</pre></details>

**Steps to reproduce:**
1. Download [gccemacs](https://www.dropbox.com/sh/0n6cv0j7ube83cj/AABe7ovZLRjz-jPWxYGE8oTfa?dl=0&preview=emacs-pgtk-native-comp-28.0.50-110.0218ca6-guix-pack.tar.xz)
2. `mkdir emacs-native-comp && cd emacs-native-comp`
3. `tar xf ~/emacs-pgtk-native-comp-28.0.50-110.0218ca6-guix-pack.tar.xz`
4. `export PATH="$PWD/bin:$PATH`
5. `cd ~/.emacs.d/bin`
6. `./doom sync && doom build`
7. `emacs`

**System information:**
<details><pre>
  ~/.emacs.d/bin/doom info
WARNING (:ui pretty-code) module was moved to (:ui ligatures)
```
SYSTEM  type       gnu/linux
	config     x86_64-pc-linux-gnu
	shell      /bin/bash
	uname      Linux 4.19.160-1-MANJARO #1 SMP Tue Nov 24 18:41:45 UTC 2020 x86_64
	path       (~/emacs-native-comp/bin ~/.local/bin /usr/local/bin /usr/bin /bin /usr/local/sbin /var/lib/flatpak/exports/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /var/lib/snapd/snap/bin /gnu/store/azyr3icd6bz7g3v968jn0ysdymqgvsz4-emacs-pgtk-native-comp-28.0.50-109.436b933/libexec/emacs/28.0.50/x86_64-pc-linux-gnu)
EMACS   dir        ~/.emacs.d/
	version    28.0.50
	build      Dec 08, 2020
	buildopts  CONFIG_SHELL=/gnu/store/pwcp239kjf7lnj5i4lkdzcfcxwcfyk72-bash-minimal-5.0.16/bin/bash SHELL=/gnu/store/pwcp239kjf7lnj5i4lkdzcfcxwcfyk72-bash-minimal-5.0.16/bin/bash --prefix=/gnu/store/azyr3icd6bz7g3v968jn0ysdymqgvsz4-emacs-pgtk-native-comp-28.0.50-109.436b933 --enable-fast-install --with-pgtk --with-xwidgets --with-nativecomp --with-modules --with-cairo --disable-build-details
	features   JPEG TIFF GIF PNG RSVG CAIRO SOUND DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 PGTK XIM MODULES NATIVE_COMP THREADS XWIDGETS JSON PDUMPER
	traits     (batch server-running envvar-file)
DOOM    dir        ~/.doom.d/
	version    2.0.9
	build      HEAD -> develop, origin/develop, origin/HEAD 9137cbaaa 2020-12-05 16:57:31 -0500
	elc-files  0
	modules    (:completion company ivy :ui deft doom doom-dashboard doom-quit fill-column hl-todo indent-guides minimap modeline ophints (popup +defaults) ligatures treemacs unicode vc-gutter vi-tilde-fringe window-select workspaces zen :editor (evil +everywhere) file-templates fold multiple-cursors snippets word-wrap :emacs (dired +ranger) electric ibuffer undo vc :term eshell vterm :checkers syntax (spell +flyspell) grammar :tools (eval +overlay) lookup (magit +forge) (pdf +pdf-tools) tmux :lang data emacs-lisp (ess +lintr) (latex +latexmk +cdlatex) markdown (org +roam +journal) python sh yaml :app (rss +org) :config (default +bindings +smartparens))
	packages   ((org-super-agenda) (org-ref) (org-noter) (helm-bibtex) (org-roam-server :recipe (:host github :repo org-roam/org-roam-server :files (*))) (evil-tutor) (wakatime-mode) (zotxt) (ox-pandoc) (org-fancy-priorities) (info-colors) (org-roam-bibtex :recipe (:host github :repo org-roam/org-roam-bibtex)))
	unpin      (org-roam company-org-roam bibtex-completion helm-bibtex ivy-bibtex)
	elpa       (n/a)
```
</pre></details>

**Comment by hlissner** [comment]
> and the terminal shows up an error related to canberra-gtk-module

These are GTK warnings, so this is not a Doom issue, or anything that can be addressed from Doom's end.

I assume `canberra-gtk-module` is a gtk dependency, which [a google search](https://askubuntu.com/questions/342202/failed-to-load-module-canberra-gtk-module-but-already-installed) tells me is available through your OS package manager. e.g. On ubuntu: `sudo apt install libcanberra-gtk-module libcanberra-gtk3-module`.

If that doesn't fix it, you'll have to seek help elsewhere.

> it is sensibly slower

[Can you reproduce this in vanilla Doom](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#testing-in-dooms-sandbox)? If not, the issue in your config. You are likely eagerly loading packages, rather than deferring them. I'm sorry, I'm too swamped at the moment to look through your config.

**Comment by GiulioCentorame** [comment]
I will look into the GTK dependency issue, thank you.

The slowdown is still present with vanilla Doom on startup from the sandbox.
I tried playing around a bit and noticed that vanilla Emacs is definitely faster (almost instant), whereas vanilla Doom takes a good 5-10 secs to start up.

My config is absolutely far from ideal and likely to contribute to the problem, thanks for the heads up.
