### ISSUE TITLE
evil-vimish-fold takes over "z" key in org-agenda buffer

### ISSUE THREAD

**Issue by AloisJanicek** [hlissner/doom-emacs#439]
### Observed behavior
![Doom and "z" key in org-agenda](https://thumbs.gfycat.com/HelplessPaltryIcterinewarbler-size_restricted.gif)
Pressing `"z"` key in org-agenda buffer activates evil-vimish-fold instead of _tweak display_ action, as it is intended by evil-org for [org-agenda](https://github.com/Somelauw/evil-org-mode/tree/491b0b302b95d44ceb73d291dedbb9d5517ccee2#agenda).  
evil-vimish-fold doesn't make sense for org-agenda, but it looks like it is global minor mode and I am having hard time disabling it on per buffer/mode basis.

### Expected behavior

Pressing `"z"` key in org-agenda activates _tweak display_ action.
### Steps to reproduce

1. Open org-agenda and navigate yourself on some taks
2. Press `"z"` key
3. Instead of _tweak display_ popup, evil-vimish-fold is active

### System information

<details>
<summary>Click to expand</summary>

`branch: develop`
</details>

**Comment by dsdshcym** [comment]
evil-vimish-fold also takes over "z" key in magit buffers (with evil-magit enabled)

**Comment by hlissner** [comment]
I've reduced evil-vimish-fold's ubiquity, which should resolve your issue. Let me know if that isn't the case.

**Comment by AloisJanicek** [comment]
Now every command in `org-agenda` works as intended.
