### ISSUE TITLE
layout +bepo breaks org-insert-link

### ISSUE THREAD

**Issue by brabalan** [hlissner/doom-emacs#4393]
**What did you expect to happen?**
I'm using `layout +bepo` and when I type `org-insert-link` I get an error.

**What actually happened?**
`Debugger entered--Lisp error: (error "Key sequence C-l ! starts with non-prefix key C-l")`

**Additional details:**
backtrace:
<details><pre>
define-key((keymap (100663483) (100663467) (100663529) (67109051) (67109035) (67109097 . doom/delete-backward-word) (187) (171) (201) (233) (33554451 . scroll-down-command) (33554452 . scroll-up-command) (20 . next-line) (75) (107) (74) (106) (83) (115) (84) (116) (33554444) (33554440) (12 . backward-delete-char-untabify) (76) (108) (72) (104) (33554450) (33554435) (3 . backward-delete-char-untabify) (82) (114) (67) (99) (8 . evil-paste-from-register) (insert-state keymap (11 . previous-line) (10 . next-line) "Auxiliary keymap for Insert state") (33554443 . scroll-down-command) (33554442 . scroll-up-command) (11 . counsel-minibuffer-history) (10 . next-line) (26 closure (t) (&rest _) (interactive) (condition-case nil (progn (call-interactively #'undo)) (error nil))) (23 . doom/delete-backward-word) (22 . yank) (21 . evil-delete-back-to-indentation) (18) (1 . move-beginning-of-line) (escape . abort-recursive-edit) (19 . previous-line) ...) "\f!" org-time-stamp-inactive)
  (let ((enable-recursive-minibuffers t) (minibuffer-local-completion-map (copy-keymap minibuffer-local-completion-map))) (define-key minibuffer-local-completion-map " " 'self-insert-command) (define-key minibuffer-local-completion-map "?" 'self-insert-command) (define-key minibuffer-local-completion-map (cond ((eq doom-bepo-cr-rotation-style 'ergodis) (kbd "C-l !")) (t (kbd "C-h !"))) 'org-time-stamp-inactive) (apply #'completing-read args))
  doom-bepo--org-completing-read("Link: " ("doom-repo:" "wolfram:" "wikipedia:" "duckduckgo:" "gmap:" "gimages:" "google:" "youtube:" "github:" "printindex:" "index:" "bibentry:" "Autocites:" "autocites:" "supercites:" "Textcites:" "textcites:" "Smartcites:" "smartcites:" "footcitetexts:" "footcites:" "Parencites:" "parencites:" "Cites:" "cites:" "fnotecite:" "Pnotecite:" "pnotecite:" "Notecite:" "notecite:" "footfullcite:" "fullcite:" "citeurl:" "citedate*:" "citedate:" "citetitle*:" "citetitle:" "Citeauthor*:" "Autocite*:" "autocite*:" "Autocite:" "autocite:" "supercite:" "parencite*:" "cite*:" "Smartcite:" "smartcite:" "Textcite:" "textcite:" "footcitetext:" ...) nil nil nil org-link--history "notmuch:id:87v9dbsm9n.fsf@dorothy.carcosa.net")
  apply(doom-bepo--org-completing-read ("Link: " ("doom-repo:" "wolfram:" "wikipedia:" "duckduckgo:" "gmap:" "gimages:" "google:" "youtube:" "github:" "printindex:" "index:" "bibentry:" "Autocites:" "autocites:" "supercites:" "Textcites:" "textcites:" "Smartcites:" "smartcites:" "footcitetexts:" "footcites:" "Parencites:" "parencites:" "Cites:" "cites:" "fnotecite:" "Pnotecite:" "pnotecite:" "Notecite:" "notecite:" "footfullcite:" "fullcite:" "citeurl:" "citedate*:" "citedate:" "citetitle*:" "citetitle:" "Citeauthor*:" "Autocite*:" "autocite*:" "Autocite:" "autocite:" "supercite:" "parencite*:" "cite*:" "Smartcite:" "smartcite:" "Textcite:" "textcite:" "footcitetext:" ...) nil nil nil org-link--history "notmuch:id:87v9dbsm9n.fsf@dorothy.carcosa.net"))
  org-completing-read("Link: " ("doom-repo:" "wolfram:" "wikipedia:" "duckduckgo:" "gmap:" "gimages:" "google:" "youtube:" "github:" "printindex:" "index:" "bibentry:" "Autocites:" "autocites:" "supercites:" "Textcites:" "textcites:" "Smartcites:" "smartcites:" "footcitetexts:" "footcites:" "Parencites:" "parencites:" "Cites:" "cites:" "fnotecite:" "Pnotecite:" "pnotecite:" "Notecite:" "notecite:" "footfullcite:" "fullcite:" "citeurl:" "citedate*:" "citedate:" "citetitle*:" "citetitle:" "Citeauthor*:" "Autocite*:" "autocite*:" "Autocite:" "autocite:" "supercite:" "parencite*:" "cite*:" "Smartcite:" "smartcite:" "Textcite:" "textcite:" "footcitetext:" ...) nil nil nil org-link--history "notmuch:id:87v9dbsm9n.fsf@dorothy.carcosa.net")
  org-insert-link(nil)
  funcall-interactively(org-insert-link nil)
</pre></details>

**Comment by hlissner** [comment]
@gagbo The org module sets up `C-{h,j,k,l}` for navigating table cells. I guess those will have to be either unbound (or rebound) for bepo users?

**Comment by gagbo** [comment]
I remember having that, I thought I fixed that :( this should be simpler to fix than notmuch.

**Comment by gagbo** [comment]
happened in #3806

**Comment by gagbo** [comment]
And now I understand the issue, I think I’ll change the advice to use another key altogether then

**Comment by gagbo** [comment]
> @gagbo The org module sets up `C-{h,j,k,l}` for navigating table cells. I guess those will have to be either unbound (or rebound) for bepo users?

Where is this done ? If it comes from `evil-org`, it should be handled by [these lines](https://github.com/hlissner/doom-emacs/blob/febf960c4e6247f20946fd0a832bf5d3c3febaf3/modules/input/layout/%2Bbepo.el#L62-L65) already

**Comment by hlissner** [comment]
It's done [in the lang/org module](https://github.com/hlissner/doom-emacs/blob/develop/modules/lang/org/config.el#L989-L996), but bound to evil-org-mode-map. The bepo module chokes when it tries to remap them (probably because `C-l` is already a prefix by that point). I'll look into it over the weekend.

**Comment by gagbo** [comment]
I never touch `evil-org-mode-map` actually, I only modify the movement keys. I might choose to stop using this interface, and just manually run all my remapping functions on all evil-org maps

**Comment by brabalan** [comment]
Thank you for the investigation. Please let me know if I can help in any way.

**Comment by brabalan** [comment]
This was a bug in my config. I was remapping `C-h` to backspace.
