### ISSUE TITLE
Update lsp-mode to a new version

### ISSUE THREAD

**Issue by idanko** [hlissner/doom-emacs#4396]
Following this thread https://github.com/emacs-lsp/lsp-mode/issues/2359 it would be nice to update the lsp-mode's pin to the new version: `(package! lsp-mode :pin "44fc98e60b3a6435ab921aefdb09f005204449ba")`. This will fix the annoying `LSP :: unexpected <provider> setting "<provider>"` message.

**Comment by hlissner** [comment]
As of 46ac419 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by darwin67** [comment]
wow, that was fast. thanks for the quick response.
