### ISSUE TITLE
Resizing window with `C-w |` / `SPC w |` freezes Emacs

### ISSUE THREAD

**Issue by frankjonen** [hlissner/doom-emacs#4404]
`SPC w |` freezes the entire session and I have to force-quit and restart Emacs.

I just switched from Spacemacs and I've spent about an hour now of trying to get it to work in Doom. It'd be great if someone could give me a few pointers on how to do it here.

**What I do:**
- Hit Space
- then w
- then |

**What I expected:**
- Some sort of input to type in the window width
- The active window gets resized to that value and the other windows in the frame adjust for it.

**What actually happened:**
- The drawer remains and Emacs stops reacting.

Thanks for any pointers.

**Comment by hlissner** [comment]
`[N] SPC w |` or `[N] C-w |` to set a window's width to `N`.

I cannot reproduce the freeze. Try `M-x toggle-debug-on-quit`, then mash `C-g` when it freezes until you break out of it, or run `pkill -USR2 emacs` in the terminal to force it out of the freeze and produce a backtrace.

Side note: in the future, _please_ do not ignore the issue template. It asks you to include your `M-x doom/info`.

**Comment by frankjonen** [comment]
I was holding it wrong. I didn't prepend the count and was expecting a widget asking for the count.
When I prepend it works.

I couldn't break out of the freeze with `C-g` so I guess the debug info is lost since `pkill -SIGUSR2 emacs` ran without result. Only thing that works is a system level force-quit. I'm guessing it runs into a loop.



```
SYSTEM  type       darwin
        config     x86_64-apple-darwin18.7.0
        shell      /bin/bash
        uname      Darwin 18.7.0 Darwin Kernel Version 18.7.0: Mon Aug 31 20:53:32 PDT 2020; root:xnu-4903.278.44~1/RELEASE_X86_64 x86_64
        path       (/usr/local/Cellar/opencolorio/1.1.1_3/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /Library/TeX/texbin /opt/X11/bin /usr/local/opt/imagemagick@6/bin ~/.tools /usr/local/opt/python@3.8/bin ~/go/bin /usr/local/opt/go/libexec/bin /usr/local/Cellar/emacs-plus@27/27.1/libexec/emacs/27.1/x86_64-apple-darwin18.7.0/)
EMACS   dir        ~/.emacs.d/
        version    27.1
        build      Nov 19, 2020
        buildopts  --disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus@27/27.1/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus@27/27.1 --with-xml2 --with-gnutls --without-dbus --with-imagemagick --with-modules --with-rsvg --with-xwidgets --with-ns --disable-ns-self-contained
        features   RSVG IMAGEMAGICK GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS XWIDGETS JSON PDUMPER LCMS2 GMP
        traits     (gui server-running envvar-file)
DOOM    dir        ~/.doom.d/
        version    2.0.9
        font       #<font-spec nil nil Input Mono nil nil nil nil nil 18 nil nil nil nil>
        theme      doom-tomorrow-night
        build      grafted, HEAD -> develop, origin/develop, origin/HEAD 9137cba 2020-12-05 16:57:31 -0500
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline ophints (popup +defaults) vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold snippets :emacs dired electric undo vc :checkers syntax :tools (eval +overlay) lookup magit :os macos :lang emacs-lisp markdown org sh :config (default +bindings +smartparens))
        packages   (n/a)
        unpin      (n/a)
        elpa       (n/a)
```

**Comment by ArchCST** [comment]
Same issue here, I can adjust the window width several times, then the GUI emacs freezed.
