### ISSUE TITLE
Open package readme file

### ISSUE THREAD

**Issue by ngharrison** [hlissner/doom-emacs#4406]
**Describe the feature**
A way to open the readme file of a package included in the distribution/configuration. Doom has a way to open the "package help" (SPC h p) and the library itself (SPC h P), but accessing the documentation requires browsing the package folders. I guess I was expecting the documentation to be linked from within the package help buffer or through access similar to getting the documentation of a Doom module.

**System information**
<details><pre>
SYSTEM  type       windows-nt
        config     x86_64-w64-mingw32
        shell      C:/Program Files/emacs-27.1-x86_64/libexec/emacs/27.1/x86_64-w64-mingw32/cmdproxy.exe
        uname      n/a
        path       (C:\Users\$USER\Anaconda3\condabin C:\Program Files\emacs-27.1-x86_64\bin C:\Users\$USER\.emacs.d\bin C:\Users\$USER\Anaconda3\Scripts C:\Users\$USER\Anaconda3 C:\Ruby26-x64\msys64\mingw64\bin C:\Ruby26-x64\msys64\usr\bin C:\Strawberry\c\bin C:\Strawberry\perl\site\bin C:\Strawberry\perl\bin C:\Program Files\ImageMagick-7.0.7-Q16 C:\ProgramData\Oracle\Java\javapath C:\Program Files (x86)\Intel\iCLS Client\ C:\Program Files\Intel\iCLS Client\ C:\WINDOWS\system32 C:\WINDOWS C:\WINDOWS\System32\Wbem C:\WINDOWS\System32\WindowsPowerShell\v1.0\ C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL C:\Program Files\Intel\Intel(R) Management Engine Components\DAL C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT C:\Program Files\Intel\Intel(R) Management Engine Components\IPT C:\Program Files\Intel\WiFi\bin\ C:\Program Files\Common Files\Intel\WirelessCommon\ C:\Program Files\nodejs\ C:\Program Files\Git\cmd\ C:\Users\$USER\AppData\Local\Android\sdk\platform-tools C:\Program Files\Java\jdk1.8.0_271\bin C:\Program Files\MATLAB\R2019a\runtime\win64 C:\Program Files\MATLAB\R2019a\bin C:\Program Files\PuTTY\ C:\Program Files (x86)\PDFtk\bin\ C:\Program Files\Sublime Text 3 C:\WINDOWS\System32\OpenSSH\ C:\Program Files (x86)\Wolfram Research\WolframScript\ C:\Program Files\CMake\bin C:\WINDOWS\system32 C:\WINDOWS C:\WINDOWS\System32\Wbem C:\WINDOWS\System32\WindowsPowerShell\v1.0\ C:\WINDOWS\System32\OpenSSH\ C:\Program Files\MiKTeX 2.9\miktex\bin\x64\ C:\Program Files\SumatraPDF C:\Program Files\Julia-1.4.0\bin C:\Program Files\Neovim\bin C:\Program Files\Pandoc\ C:\Installers\libxml2-2.9.3-win32-x86_64\bin C:\Program Files\ripgrep\ripgrep-12.1.1-x86_64-pc-windows-msvc C:\Program Files\fd\fd-v8.1.1-x86_64-pc-windows-msvc C:\Program Files (x86)\sqlite C:\Ruby26-x64\bin C:\Users\$USER\AppData\Local\Microsoft\WindowsApps C:\Users\$USER\AppData\Roaming\npm C:\Users\$USER\AppData\Local\Box\Box Edit\ C:\Program Files (x86)\Oni C:\Users\$USER\AppData\Local\Programs\Microsoft VS Code\bin c:/Program Files/emacs-27.1-x86_64/libexec/emacs/27.1/x86_64-w64-mingw32/)
EMACS   dir        ~/.emacs.d/
        version    27.1
        build      Aug 21, 2020
        buildopts  --without-dbus --host=x86_64-w64-mingw32 --without-compress-install 'CFLAGS=-O2 -static'
        features   XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY W32NOTIFY ACL GNUTLS LIBXML2 HARFBUZZ ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS JSON PDUMPER LCMS2 GMP
        traits     (gui server-running envvar-file)
DOOM    dir        ~/.doom.d/
        version    2.0.9
        font       #<font-object -outline-Courier New-normal-normal-normal-mono-17-*-*-*-c-*-iso8859-1>
        theme      doom-oceanic-next
        build      HEAD -> develop, origin/develop, origin/HEAD aa02dc14a 2020-11-14 18:42:31 -0500
        elc-files  0
        modules    (:completion (company +childframe) (ivy +prescient +icons) :ui doom doom-dashboard hl-todo hydra minimap modeline ophints (popup +defaults) treemacs vc-gutter vi-tilde-fringe (window-select +numbers) workspaces zen :editor (evil +everywhere) file-templates fold multiple-cursors rotate-text snippets word-wrap :emacs (dired +icons) electric (ibuffer +icons) undo vc :term eshell :checkers syntax (spell +aspell) :tools ein (eval +overlay) (lookup +dictionary) magit pdf :lang data emacs-lisp kotlin latex markdown (org +jupyter +roam +present) (python +conda) sh yaml :config (default +bindings +smartparens))
        packages   ((flycheck-pyflakes) (sublimity))
        unpin      (n/a)
        elpa       (n/a)
</pre></details>

**Comment by hlissner** [comment]
This functionality already exists: `M-x doom/help-package-homepage` (on `SPC h d p h` or `C-h d p h`)

**Comment by ngharrison** [comment]
@hlissner Thanks, that is helpful. Is there not something currently to open the README.org file itself from within Emacs? Again, akin to `SPC h m` to get to the module readme.
