### ISSUE TITLE
Packages can't be installed, npm returns 254

### ISSUE THREAD

**Issue by DoubleClick7** [hlissner/doom-emacs#4411]
**What did you expect to happen?**
html-ls and css-ls to get installed 

**What actually happened?**
```
LSP :: Download html-ls started.
LSP :: Server html-ls install process failed with the following error message: Async process '/usr/bin/npm' failed with exit code 254.
Check `*lsp-install*' and `*lsp-log*' buffer.
```

**System information:**
<details><pre>```
SYSTEM  type       gnu/linux
	config     x86_64-pc-linux-gnu
	shell      /usr/bin/zsh
	uname      Linux 5.9.11-zen2-1-zen #1 ZEN SMP PREEMPT Sat, 28 Nov 2020 02:08:52 +0000 x86_64
	path       (~/chromedriver/chromedriver ~/.emacs.d/bin ~/.local/bin /usr/local/sbin /usr/local/bin /usr/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /var/lib/snapd/snap/bin /usr/lib/emacs/28.0.50/x86_64-pc-linux-gnu)
EMACS   dir        ~/.emacs.d/
	version    28.0.50
	build      Nov 25, 2020
	buildopts  --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --mandir=/usr/share/man --with-gameuser=:games --with-sound=alsa --with-modules --without-gconf --without-gsettings --with-nativecomp --with-x-toolkit=gtk3 --without-xaw3d --without-m17n-flt --with-cairo --without-compress-install 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -g -fuse-ld=gold' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
	features   XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES NATIVE_COMP THREADS LIBSYSTEMD JSON PDUMPER LCMS2
	traits     (batch server-running envvar-file)
DOOM    dir        ~/.config/doom/
	version    2.0.9
	build      HEAD -> develop fbb8d1b99 2020-12-08 23:01:07 -0500
	elc-files  0
	modules    (:completion company ivy :ui doom doom-dashboard doom-quit (emoji +unicode) hl-todo indent-guides ligatures minimap (modeline +light) neotree ophints (popup +defaults) vi-tilde-fringe window-select workspaces zen :editor (evil +everywhere) file-templates fold multiple-cursors snippets :emacs dired electric ibuffer undo :term eshell shell term vterm :checkers syntax :tools (eval +overlay) lookup magit make rgb lsp :os tty :lang (cc +lsp) (emacs-lisp +lsp) (javascript +lsp) markdown org php (python +lsp) sh (web +lsp) :email (mu4e +gmail) :config (default +bindings +smartparens))
	packages   ((ewal-doom-themes) (with-editor) (ewal) (fira-code-mode) (prettier) (sublimity) (spacemacs-theme) (webpaste) (zone-nyan) (nyan-mode) (evil-commentary) (evil-tutor) (web-mode) (sublime-themes) (cyberpunk-theme) (ample-theme) (ample-zen-theme) (afternoon-theme))
	unpin      (n/a)
	elpa       (web-mode spacemacs-theme ewal-spacemacs-themes ewal-doom-themes ewal doom-themes)
```

</pre></details>

**Output of doom doctor**
The doctor will see you now...

> Checking your Emacs version...
! Emacs 28.0.50 detected. Doom doesn't support Emacs 28/HEAD. It is unstable and may cause errors.
> Checking for Emacs config conflicts...
> Checking for great Emacs features...
> Checking for private config conflicts...
> Checking for stale elc files...
> Checking Doom Emacs...
No dtrt-indent override to undo in this buffer
  ✓ Initialized Doom Emacs 2.0.9
  ✓ Detected 50 modules
  ✓ Detected 206 packages
  > Checking Doom core for irregularities...
    ! Your $HOME is recognized as a project root
      Doom will disable bottom-up root search, which may reduce the accuracy of
      project detection.
    Found font material-design-icons.ttf
    Found font weathericons.ttf
    Found font octicons.ttf
    Found font fontawesome.ttf
    Found font file-icons.ttf
    Found font all-the-icons.ttf
  > Checking for stale elc files in your DOOMDIR...
  > Checking your enabled modules...
    > :lang markdown
      ! Couldn't find a markdown compiler, `markdown-preview' won't work

There are 3 warnings!
✓ Finished in 2.0459s

**Comment by hlissner** [comment]
This error appears to be coming from npm and doesn't appear related to Doom. [Perhaps this stackoverflow question will help?](https://stackoverflow.com/questions/49656445/npm-i-running-command-failed-exit-code-254) In any case, I will close this as it's not a Doom issue.
