### ISSUE TITLE
Doom install fails against Emacs 28.0.50 native-comp 

### ISSUE THREAD

**Issue by Kingpatzer** [hlissner/doom-emacs#4417]
**What did you expect to happen?**
...
./.emacs.d/bin/doom install -> installs doom

**What actually happened?**
...
./.emacs.d/bin/doom install returns:
Symbol’s value as variable is void: comp-deferred-compilation-deny-list

**Additional details:**
- no private config yet installed

<details><pre>
If an error message is involved include a backtrace of it.

How to acquire a backtrace:
doom --debug install returns the same error

**Steps to reproduce:**
start with a clean install of Emacs 28.0.50 native-comp
git clone doom into home director
cd to ./.emacs.d/bin
./doom install

**System information:**
./doom info produces the same error

**Comment by pspencil** [comment]
Duplicate? [#4400](https://github.com/hlissner/doom-emacs/issues/4400)
