### ISSUE TITLE
How do I find out which files trigger "Large file" message

### ISSUE THREAD

**Issue by lytex** [hlissner/doom-emacs#4419]
I'm getting a message "Large file detected! Cutting a few corners to improve performance..." when performing operatations that go through all my org files.
(see https://github.com/hlissner/doom-emacs/blob/develop/core/core-editor.el#L57)

Is there a way to know which files are triggering this message with some elisp snippet?

**Comment by lytex** [comment]
If I understand correctly, since `doom-large-file-size-alist` is set to `(("." . 1.0))` that would mean files larger than 1MB are considered "large"

All my org mode files are below 200KiB. While I do have some pdf files which are well above this 1MB limit, since `doom-large-file-excluded-modes` include `doc-view-mode doc-view-mode-maybe pdf-view-mode`, this files shouldn't be considered by doom, I'm quite puzzled

Maybe by customizing the `doom-large-file-size-alist` I can exclude pdf files if they are getting included for some reason

**Comment by hlissner** [comment]
There are two things that trigger this. 

1. File size (which isn't the case here)
2. Line length (lines longer than `so-long-threshold` == "long file")

Line length seems to be your issue. Text files tend to have long lines. Enable `visual-line-mode` in org-mode and so-long will bow out. Otherwise, enable `auto-fill-mode` and make sure none of your lines are more than 400 characters long (doom's default value for `so-long-threshold`).

**Comment by lytex** [comment]
Yes, it seems some files are above this 400 characters, mostly content copy-pasted from webpages or downloaded using alphapapas [org-web-tools](https://github.com/alphapapa/org-web-tools).

For a bit of context, I've just discovered an issue in [org-transclusion](https://github.com/nobiot/org-transclusion/issues/19) is likely due to some lines being above this character limit. Since some background process (probably org-roam) is openning these files, any change that I make to the current buffer won't disable so-long (the "Large file" is still showing up)

Is there a way to raise this `so-long-threshold`? I haven't been able to modify its value in `config.el` nor `init.el`

**Comment by hlissner** [comment]
```elisp
(after! so-long
  (setq so-long-threshold ...))
```

As with any lazy loaded package, you need to use `after!`, `eval-after-load`, or `with-eval-after-load` to run your code after the package (and its defaults) has loaded.

**Comment by lytex** [comment]
Yes, I understand that raising this level will make emacs slower, but I just want to get org-transclusion working to check that the issue I mentioned earlier is due to files with long lines. However the settings don't seem to be working. Maybe a package is overriding this options?

I have both at the very beggining and end of both my config.el and init.el the following snippet:

```lisp
(after! so-long
  (setq so-long-threshold 2305843009213693951)
  (setq doom-large-file-size-alist '(("." . 2305843009213693951)))
  (delq! 'text-mode so-long-target-modes))
  ```

  Yet, the "Large file detected" is still showing up!

**Comment by wailedpancakes** [comment]
I'm having the same problem. I have about a dozen org files in my directory and I get 9 `Large file detected!` messages. I checked all of my files and I removed any long lines and it didn't change the messages. I used the codes provided to turn so-long off and it didn't change. I used just one org file and it still gave me the error. The file is only 380 lines. The longest line is 86 characters. So it's not large at all. Here are the two errors I'm getting together. I don't know if they're related:

`No dtrt-indent override to undo in this buffer`
`Large file detected! Cutting a few corners to improve performance...`

**Comment by slackorama** [comment]
Isn't the problem that `doom-large-file-p` is always set to `t` in some advice in the org config?

      (defadvice! +org--exclude-agenda-buffers-from-recentf-a (orig-fn file)
        "Prevent temporarily opened agenda buffers from polluting recentf."
        :around #'org-get-agenda-file-buffer
        (let ((recentf-exclude (list (lambda (_file) t)))
             (doom-large-file-p t)
              find-file-hook
              org-mode-hook)
          (funcall orig-fn file)))

From https://github.com/hlissner/doom-emacs/blob/develop/modules/lang/org/config.el#L609

**Comment by lytex** [comment]
I added a `(message "Large file %s" (buffer-file-name))` to print which files are being detected as "large", and practically every single org file I have is marked as "large"!

For example, the following small file is marked as large:

[20201018141652-flow.txt](https://github.com/hlissner/doom-emacs/files/5717903/20201018141652-flow.txt)

I have also files that were split up into lines under 80 characters using `fill-paragraph` which are also marked as large:

[20201204093159-xy_problem.txt](https://github.com/hlissner/doom-emacs/files/5717907/20201204093159-xy_problem.txt)

Also an error is thrown for each org file with this structure:

```
Undo-Fu-Session discarding undo data: file length mismatch for "/home/julian/org/Inbox.org"
Large file /home/julian/org/Inbox.org
No dtrt-indent override to undo in this buffer
Large file detected! Cutting a few corners to improve performance...
```

**Comment by hlissner** [comment]
> Isn't the problem that doom-large-file-p is always set to t in some advice in the org config?

Yes, it is. I already have a fix sitting in my local branch. I'll push it soon.
