### ISSUE TITLE
doom-escape/keyboard-quit keybinding doesn't trigger undo-fu--disable-checkpoint

### ISSUE THREAD

**Issue by natask** [hlissner/doom-emacs#4421]
**What did you expect to happen?**
undo-fu prompts the user to press C-g  (keyboard-quit/doom-escape) for unconstricted undo. I expected pressing C-g  (keyboard-quit/doom-escape) to trigger unconstrained undo.

**What actually happened?**
However, pressing C-g which is bound to doom-escape/keyboard-quit doesn't trigger unconstrained undo. Moreover, executing keyboard-quit from M-x triggers unconstrained undo while executing doom-escape does not.

**What I have tried.**
- doesn't work :: ***(global-set-key (kbd "C-g") #'keyboard-quit)***
- doesn't work :: *** (add-function :after (doom/escape) #'undo-fu--checkpoint-disable)***
- works :: ***(global-set-key (kbd "C-g") #'undo-fu-disable-checkpoint)***

**Steps to reproduce:**
1. trigger re-do until prompt **user-error: Redo without undo step (C-g (keyboard-quit) to ignore) [4 times]** appears,
2. press C-g (keyboard-quit) to trigger unconstrained undo

**System information:**
<details><pre>
```
SYSTEM  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/bash
        path       (~/.local/bin ~/bin ~/.local/bin /usr/local/sbin /usr/local/bin /usr/bin /opt/android-sdk/tools /opt/android-sdk/tools/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /var/lib/snapd/snap/bin /usr/lib/emacs/28.0.50/x86_64-pc-linux-gnu)
EMACS   dir        ~/doom-emacs/
        version    28.0.50
        build      Aug 20, 2020
        buildopts  --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --mandir=/usr/share/man --with-gameuser=:games --with-sound=alsa --with-modules --without-gconf --without-gsettings --with-x-toolkit=gtk3 --without-xaw3d --without-compress-install 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -flto' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
        features   XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2
        traits     (gui server-running chemacs)
DOOM    dir        ~/.doom.d/
        version    2.0.9
        font       #<font-object -1ASC-Droid Sans Mono-normal-normal-normal-*-17-*-*-*-m-0-iso10646-1>
        theme      doom-one-light
        build      HEAD -> develop eea47093 2020-12-12 15:56:36 -0500
        elc-files  0
```
</pre></details>

**Comment by hlissner** [comment]
Does this fix it?

```elisp
(add-hook! 'doom-escape-hook
  (defun +undo--disable-checkpoint-maybe-h ()
    (when (undo-fu--was-undo-or-redo)
      (undo-fu-disable-checkpoint))))
```

**Comment by natask** [comment]
unfortunately no. I also tried with a bare config file.

**Comment by hlissner** [comment]
Try this instead:

```elisp
(after! undo-fu
  (add-hook! 'doom-escape-hook
    (defun +undo--disable-checkpoint-maybe-h ()
      (when (memq last-command '(evil-redo undo-fu-only-redo))
        (undo-fu-disable-checkpoint)
        t))))
```

**Comment by natask** [comment]
interesting. Doesn't fully work. It now brings up a message "Undo checkpoint disabled for next undo action!" just as running `undo-fu-disable-checkpoint` from M-x would but doesn't enable unconstrained undo/redo. Maybe undo-fu has an internal state that needs to be triggered?

Thanks for the speedy response btw, you are awesome.

**Comment by hlissner** [comment]
Try adding `(setq undo-fu-ignore-keyboard-quit t)` to your config.

**Comment by hlissner** [comment]
Also, change the previous snippet to:

```elisp
(add-hook! 'doom-escape-hook
  (defun +undo--disable-checkpoint-maybe-h ()
    (when (memq last-command '(evil-redo evil-undo undo-fu-only-redo undo-fu-only-undo))
      (undo-fu-disable-checkpoint)
      t)))
```

**Comment by hlissner** [comment]
Found a more general fix. As of 5d34965 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by natask** [comment]
I will try the new commit And report back. Thanks For the speedy handling of the bug.

**Comment by natask** [comment]
out of curiosity, are you interacting with github issues from emacs? I am just very surprised with the speed that you handled this bug?

**Comment by natask** [comment]
I can verify that the commit worked.

**Comment by hlissner** [comment]
> out of curiosity, are you interacting with github issues from emacs? I am just very surprised with the speed that you handled this bug?

I am, using [forge](https://github.com/magit/forge) (available via the `:tools (magit +forge)` module). 

Our discord server also has a github feed, and notifications for new issues/PRs go straight to my phone, so I hear about them pretty quick.
