### ISSUE TITLE
org archive action fails when no prior archive file exists

### ISSUE THREAD

**Issue by maciekk** [hlissner/doom-emacs#4426]
**What did you expect to happen?**

Org archive subtree operation (e.g., "SPACE m A") would work.

**What actually happened?**

If prior foo_archive.org exists, then archiving works.

If prior archive file does not exist, then get error below, no archiving occurs:
    apply: Wrong number of arguments: (0 . 0), 1

**Additional details:**

Note that I've seen this problem for a while, with much (months?) older Doom Emacs, but only dug into the issue today. (i.e., even though I synched my Doom Emacs to HEAD today, it is not recent issue)

<details><pre>

Debugger entered--Lisp error: (wrong-number-of-arguments (0 . 0) 1)
  #f(compiled-function () (interactive nil) #<bytecode 0x1fe8914b541d>)(toggle)
  apply(#f(compiled-function () (interactive nil) #<bytecode 0x1fe8914b541d>) toggle)
  org-mode(toggle)
  funcall-interactively(org-mode toggle)
  call-interactively(org-mode)
  org-archive-subtree(nil)
  funcall-interactively(org-archive-subtree nil)
  call-interactively(org-archive-subtree nil nil)
  command-execute(org-archive-subtree)
</pre></details>

**Steps to reproduce:**
1. create new file, foo.org
2. create an item (e.g., "* TODO archive me")
3. with cursor on item, "SPACE m A" to archive
4. error manifests

**System information:**
<details><pre>
```
SYSTEM  type       darwin
        config     x86_64-apple-darwin18.7.0
        shell      /bin/zsh
        uname      Darwin 19.6.0 Darwin Kernel Version 19.6.0: Thu Oct 29 22:56:45 PDT 2020; root:xnu-6153.141.2.2~1/RELEASE_X86_64 x86_64
        path       (~/.emacs.d/bin/ /Applications/Emacs.app/Contents/MacOS/ /Library/Frameworks/Python.framework/Versions/3.8/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /usr/local/go/bin /Applications/Emacs.app/Contents/MacOS/bin-x86_64-10_14 /Applications/Emacs.app/Contents/MacOS/libexec-x86_64-10_14 /Applications/Emacs.app/Contents/MacOS/libexec/)
EMACS   dir        ~/.emacs.d/
        version    27.1
        build      Aug 12, 2020
        buildopts  --with-ns '--enable-locallisppath=/Library/Application Support/Emacs/${version}/site-lisp:/Library/Application Support/Emacs/site-lisp' --with-modules
        features   NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS JSON PDUMPER
        traits     (gui server-running envvar-file)
DOOM    dir        ~/.doom.d/
        version    2.0.9
        font       #<font-spec nil nil Input Mono nil nil nil nil nil 16 nil nil nil nil>
        theme      doom-spacegrey
        build      HEAD -> develop 2e61fbbf0 2020-12-13 00:21:10 -0500
        elc-files  169
        modules    (:completion company ivy :ui deft doom doom-dashboard doom-quit hl-todo hydra modeline nav-flash ophints (popup +all +defaults) ligatures treemacs vc-gutter vi-tilde-fringe window-select workspaces zen :editor (evil +everywhere) file-templates fold multiple-cursors rotate-text snippets :emacs dired electric ibuffer vc :term eshell :checkers syntax :tools (eval +overlay) (lookup +docsets) :os macos :tools magit :lang common-lisp data emacs-lisp go (haskell +dante) markdown (org +dragndrop +present +roam) python sh :config (default +bindings +smartparens))
        packages   ((org-super-agenda) (org-bookmark-heading :disable t) (org-fancy-priorities) (beacon) (org-superstar))
        unpin      (n/a)
        elpa       (n/a)
```
</pre></details>

**Comment by maciekk** [comment]
Two quick additions:

- I got naming wrong above: "foo_archive.org" was supposed to be "foo.org_archive", according to archive naming scheme.

**Comment by maciekk** [comment]
Second point (hit Cmd-Enter... premature submit):

- If I create a foo.org_archive" file manually beforehand, archiving begins working for foo.org.

**Comment by hlissner** [comment]
This sounds like an upstream issue. Try [unpinning](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#pinning-packages-to-specific-commits) `org-mode`, then run `doom sync -u` and see if the issue goes away.

**Comment by hlissner** [comment]
Actually, I cannot reproduce this behavior in vanilla Doom.

**Comment by maciekk** [comment]
> Actually, I cannot reproduce this behavior in vanilla Doom.
> 
> But I have noticed that you've byte-compiled your config. Run `doom clean`, restart Emacs, and see if the problem persists. If it does, run `doom sync -u && doom build` and check again.

Reviving as ran into this issue again, and it would be nice to understand it rather than always relying on the manual workaround.

Update: I tried both of these with no effect, and likewise I followed the unpinning instructions, again to no effect.

Looking at stack trace, it seems weird to me that call-interactively is adding a "toggle" parameter when calling org-mode, which presumably is the source of the error (i.e, "(0 . 0)" expecting precisely zero arguments, as I would expect)

Here is the stack trace, fwiw:

Debugger entered--Lisp error: (wrong-number-of-arguments (0 . 0) 1)
  #f(compiled-function () (interactive nil) #<bytecode 0x1ff266cfd3b1>)(toggle)
  apply(#f(compiled-function () (interactive nil) #<bytecode 0x1ff266cfd3b1>) toggle)
  org-mode(toggle)
  funcall-interactively(org-mode toggle)
  call-interactively(org-mode)
  org-archive-subtree(nil)
  funcall-interactively(org-archive-subtree nil)
  call-interactively(org-archive-subtree nil nil)
  command-execute(org-archive-subtree)

1. IIUC, call-interactively is a C-compiled fn within Emacs, so can't see source easily. How can call-interactively add an argument like this?

2. Could my config be somehow leading to introduction of this superfluous argument? I don't see how, but given you cannot reproduce, and other mitigations didn't help...
