### ISSUE TITLE
User inputs gets trapped in teal ivy-actions hydra which hides itself but does not exit after first action is executed

### ISSUE THREAD

**Issue by AloisJanicek** [hlissner/doom-emacs#4427]
**What did you expect to happen?**
When being presented with ivy actions after calling `C-o` (`ivy-dispatching-done`) from `ivy` I expect the available actions menu to de-active itself after I execute one of its actions OR to stay visible (less convenient but predictable) so its visibility reminds me I should close it by one of the listed keys.

**What actually happened?**
After the https://github.com/hlissner/doom-emacs/commit/c4a0174fe2d02741df73e1ff97fa56b2c3ea2a42 the action menu went from buggy minibuffer menu which notoriously refuses to show all action candidates (even with the `ivy-read-action-format-columns`) to `teal` hydra which hides itself after user executes one of the listed actions but still somehow remains active and traps all user keystrokes which leads to all kids of unpredictable and dangerous behavior. This invisible teal hydra can be exited only by one of the keys listed in `ivy-dispatching-done-hydra-exit-keys`, which currently are `M-o` and `C-g`.

**Steps to reproduce:**
1. `SPC f r` for `counsel-recentf`
2. `C-o` on the desired candidate
3. chose `j` "other window" action on desired candidate
4. [files opens, hydra disappears, user input remains trapped]
5. pressing `j` to navigate one line down in newly opened file leads to **complete buffer content deletion** with an error:
```
ivy--done: No catch for tag: exit, nil
```
6. pressing any other key which is not listed in the teal ivy-actions hydra leads to:
```
An amaranth Hydra can only exit through a blue head
```

**System information:**
<details><pre>
```
SYSTEM  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/bash
        uname      Linux 5.9.13-zen1-1-zen #1 ZEN SMP PREEMPT Tue, 08 Dec 2020 12:10:52 +0000 x86_64
EMACS   dir        ~/.doom-vanilla/.emacs.d/
        version    28.0.50
        build      Dec 08, 2020
        buildopts  --with-nativecomp CC=clang --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --mandir=/usr/share/man --with-gameuser=:games --with-sound=alsa --with-modules --without-gconf --without-gsettings --with-nativecomp --enable-autodepend --enable-link-time-optimization --with-x-toolkit=gtk3 --without-xaw3d --without-m17n-flt --with-cairo --without-compress-install 'CFLAGS=-march=native -O3 -pipe -fstack-protector-strong -fno-plt -g -flto' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
        features   XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES NATIVE_COMP THREADS LIBSYSTEMD JSON PDUMPER LCMS2
        traits     (batch envvar-file)
DOOM    dir        ~/.doom-vanilla/.doom.d/
        version    2.0.9
        build      HEAD -> develop, origin/develop, origin/HEAD 2e61fbbf0 2020-12-13 00:21:10 -0500
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo (modeline +light) nav-flash ophints (popup +defaults) vc-gutter vi-tilde-fringe window-select workspaces zen :editor (evil +everywhere) file-templates fold snippets :emacs dired electric vc undo :term vterm :checkers syntax :tools (eval +overlay) lookup magit pdf :lang data emacs-lisp latex markdown (org +dragndrop +pandoc +hugo +pomodoro +roam) sh :config (default +bindings +smartparens))
        packages   (n/a)
        unpin      (n/a)
        elpa       (n/a)
```

</pre></details>

**(not) possible solutions**
- at least adding `ESC` to `ivy-dispatching-done-hydra-exit-keys` since not every `evil` users knows about `C-g` to lower the confusion
- overriding `ivy-hydra-read-action` with alternative which generates `blue` headed hydra prevents the endless user input entrapment but still doesn't solve the issue of hydra going invisible but remaining actively listening for user input. In case of `blue` hydra there will be an error when user presses key which corresponds to `blue` head, but at least that error will be last and hydra will go away after that.

**Comment by hlissner** [comment]
> to teal hydra which hides itself after user executes one of the listed actions but still somehow remains active and traps all user keystrokes which leads to all kids of unpredictable and dangerous behavior

This sounds like an upstream issue and should probably be reported there.

In the meantime, this is a dangerous bug, so I've reverted to using `ivy-read-action-format-columns` instead, which should solve the original "can't see all the options" issue, without `ivy-hydra-read-action`'s wierdness.

**Comment by AloisJanicek** [comment]
[Reported upstream](https://github.com/abo-abo/swiper/issues/2759), bug occurs with vanilla config and stable emacs 27.1 too

**Comment by AloisJanicek** [comment]
So the issue is solved @hlissner 
there is a difference between `ivy-read-action-function` and `ivy-read-action-format`

in https://github.com/hlissner/doom-emacs/commit/c4a0174fe2d02741df73e1ff97fa56b2c3ea2a42 you assigned action function to format variable and that lead to bugs 

following is the correct way of having ivy action hydra and having fail safe insurance that it will format itself to more columns when there is a possibility of some actions not fitting to screen.

```lisp
(setq ivy-read-action-function #'ivy-hydra-read-action)
(setq ivy-read-action-format-function #'ivy-read-action-format-columns)
```

no issues with trapped user input whatsoever after setting it this way.
