### ISSUE TITLE
comp-deferred-compilation-deny-list and autoloads

### ISSUE THREAD

**Issue by t0ster** [hlissner/doom-emacs#4432]
https://github.com/hlissner/doom-emacs/blob/49f3bc193a4984f0b5a01a71ad91bb26f643c6d8/core/cli/autoloads.el#L13
Shouldn't this be `comp-deferred-compilation-deny-list` now?

Best regards,
Roman

**Comment by hlissner** [comment]
As of 8c39790 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
