### ISSUE TITLE
Emacs fails to install packages from Melpa

### ISSUE THREAD

**Issue by alexdao3** [hlissner/doom-emacs#444]
### Observed behavior

I can't seem to install any packages via `M-x` -> `package-install`. I keep getting the following error:

```
Contacting host: melpa.org:443
package-install-from-archive: Certificate validation failed melpa.org, verification code 142
```

On `package-refresh-contents`, I also get the following:

```
Contacting host: elpa.gnu.org:443
Failed to download ‘gnu’ archive.
Failed to download ‘melpa’ archive.
Package refresh done
Failed to download ‘org’ archive.
```

I just did a fresh emacs install with `brew install emacs --with-cocoa --with-gnutls` as described [here](https://github.com/hlissner/doom-emacs/issues/80#issuecomment-327000863)

Describe what happened. Any aids you can include (that you think could be relevant) are a tremendous help; like a screencast gif, video, or link to your customizations for Doom (e.g. a repo or a pastebin).

### Expected behavior

Expect to be able to install a package

### Steps to reproduce

1. Open Emacs
2. `M-x`
3. Select `package-install`
4. Select any package i.e. `magit git-flow`

### System information

Mac OS High Sierra (10.13.1)
emacs 25.3.1

```
DOOM Doctor
Running Emacs v25.3.1, commit fatal: Not a git repository (or any of the parent directories): .git

shell: /bin/zsh
Compiled with:
  JPEG NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS
uname -a:
  Darwin Alexs-MBP.localdomain 17.2.0 Darwin Kernel Version 17.2.0: Fri
  Sep 29 18:27:05 PDT 2017; root:xnu-4570.20.62~3/RELEASE_X86_64 x86_64

Attempt to load DOOM: success! Loaded v2.0.9
Revision 5d3cf4ca2ba4bafe8663bb1ffc7add273e739f10

----

test-emacs
test-windows
test-fonts
Found font material-design-icons.ttf
Found font weathericons.ttf
Found font octicons.ttf
Found font fontawesome.ttf
Found font file-icons.ttf
Found font all-the-icons.ttf
test-gnutls
test-tls
Validated https://elpa.gnu.org
Validated https://melpa.org
Successfully rejected https://self-signed.badssl.com
Successfully rejected https://wrong.host.badssl.com/
test-tar
Everything seems fine, happy Emacs’ing!
ls does not support --dired; see ‘dired-use-ls-dired’ for more details.
```
</details>

**Comment by hlissner** [comment]
Do you get these issues if you run `M-x package-initialize` before doing either `package-install` or `package-refresh-contents`?

**Comment by rsangole** [comment]
I get the exact same issue.

**Comment by alexdao3** [comment]
Hi Henrik, I ran the package-initialize command, but still encounter the
same issues with package-initialize and package-refresh-contents

**Comment by jawatech** [comment]
@hlissner M-x package-initialize before package-install seems to solve this issue. Would you please tell us why?

**Comment by hlissner** [comment]
Doom avoids `package-initialize` to halve its startup time. `package-*` commands requires some state that this function intializes.

In the lastest update (on `develop`), I've ensured that this state is initialied before you call any of the package commands. Let me know if that resolves your issue.

**Comment by hlissner** [comment]
Is this still an issue? Doom has evolved a great deal since this was first posted, including better package.el compatibility.

**Comment by RodrigoLeiteF** [comment]
Hey, I'm still having this issue on the `develop` branch. Any ideas?

**Comment by hlissner** [comment]
@RodrigoLeiteF What version of Emacs are you on?

**Comment by RodrigoLeiteF** [comment]
GNU Emacs 26.1

**Comment by RodrigoLeiteF** [comment]
Seems to have fixed itself. It was probably some restriction on the connection I was using at the time.

**Comment by stratacast** [comment]
I'm getting this issue now too. doom-doctor output:

```
Doom Doctor
Emacs v26.1
Doom v2.0.9 (nil)
shell: /bin/bash
Compiled with: JPEG SOUND GPM DBUS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 ZLIB
  THREADS LIBSYSTEMD LCMS2
uname -msrv: Linux 4.19.0-5-amd64 #1 SMP Debian 4.19.37-5 (2019-06-19) x86_64

Checking Emacs
  Checking your Emacs version is 25.3 or newer...
  Checking if your version of Emacs has changed recently...
  Checking for Emacs config conflicts...
  Checking for private config conflicts...
  Checking for stale elc files...
Checking your system...
  Checking gnutls/openssl...
  Testing your root certificates...
  Checking for GNU/BSD tar...
Checking DOOM Emacs...
Attempt to load DOOM failed (modules/editor/evil/config.el (file-missing
  Cannot open load file No such file or directory evil)) 


There is 1 warning!
```

When doing quickstart, I have a few packages it simply cannot grab because they're unavailable:

* xclip-
* undo-tree-
* gnu-elpa-keyring-update-
csv-mode-

**Comment by hlissner** [comment]
@stratacast It does seem like a connection issue. Occasionally, the sites go down. Unfortunately, there's little I can do about that besides find mirrors. I'm considering a switch to [straight](https://github.com/raxod502/straight.el) or creating my own Doom-based mirrors for these ELPA repos.

In any case, I'll consider the original issue resolved and close this. Feel free to follow up here if you have more to add.

**Comment by thetonyrom** [comment]
Hi @hlissner It would be helpful to have doom-based mirror.

**Comment by calumks** [comment]
If anyone is having problems downloading from https://elpa.gnu.org/packages/, change the mirror to https://mirrors.163.com/elpa/gnu/ in core/core-packages.el. Seems like 163.com is owned by some [Chinese tech company](https://en.wikipedia.org/wiki/NetEase). Not sure if safe or not so use at own risk.

credit: https://www.reddit.com/r/emacs/comments/cdf48c/failed_to_download_gnu_archive/ettq14z

**Comment by hlissner** [comment]
[I mention some better alternatives in another thread](https://github.com/hlissner/doom-emacs/issues/1582#issuecomment-513629151). I would recommend them over employing an uncertain mirror.

**Comment by vityafx** [comment]
Have the same on emacs 25.2, emacs 26.2, latest develop branch by today.
Had to run with `emacs --insecure`, nothing else helped.

**Comment by freshpassport** [comment]
> If anyone is having problems downloading from https://elpa.gnu.org/packages/, change the mirror to https://mirrors.163.com/elpa/gnu/ in core/core-packages.el. Seems like 163.com is owned by some [Chinese tech company](https://en.wikipedia.org/wiki/NetEase). Not sure if safe or not so use at own risk.
> 
> credit: https://www.reddit.com/r/emacs/comments/cdf48c/failed_to_download_gnu_archive/ettq14z

excellent
