### ISSUE TITLE
Clean install not working

### ISSUE THREAD

**Issue by antoniojkim** [hlissner/doom-emacs#4440]
**What did you expect to happen?**
Trying to do a fresh install on a new machine. I have all the prerequisites met. I cloned the repo as mentioned in the README. Tried to run `~/.emacs.d/bin/doom install`

**What actually happened?**
Running `~/.emacs.d/bin/doom install` prints the following and then nothing happens afterwards
```
Recursive load: "/opt/emacs-27.1/share/emacs/27.1/lisp/jka-compr.el.gz", "/opt/emacs-27.1/share/emacs/27.1/lisp/jka-compr.el.gz", "/opt/emacs-27.1/share/emacs/27.1/lisp/jka-compr.el.gz", "/opt/emacs-27.1/share/emacs/27.1/lisp/jka-compr.el.gz", "/opt/emacs-27.1/share/emacs/27.1/lisp/jka-compr.el.gz", "/opt/emacs-27.1/share/emacs/27.1/lisp/obsolete/cl.el.gz", "~/.emacs.d/bin/doom"
```
I don't remember this being the behavior when I installed it previously. When I open emacs, I'm greeted by the standard emacs, not doom-emacs. 

**System information:**
<details><pre>
Trying to run `~/.emacs.d/bin/doom info` yields the same results as above. System info using `lsb_release -l` is 
```
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.8.2003 (Core)
Release:        7.8.2003
Codename:       Core
```
</pre></details>

**Comment by t-e-r-m** [comment]
Have you tried purging and re-installing Emacs?
