### ISSUE TITLE
org-fancy-priorities not working in org-mode

### ISSUE THREAD

**Issue by wang1zhen** [hlissner/doom-emacs#4446]
**What did you expect to happen?**
...

customized priorities list for org-mode and agenda

![Imgur](https://imgur.com/JLNuTcJ.png)

**What actually happened?**
...

customized priorities list not loaded

![imgur](https://imgur.com/kbbOFzI.png)

`C-h v org-fancy-priorites-list` gives

```
org-fancy-priorities-list is a variable defined in
org-fancy-priorities.el.

Value
("⚑" "⬆" "■")

Original Value
("❗" "⬆" "⬇" "☕")
```

**Additional details:**
configs related:
```elisp
(after! org
  (setq
   org-fancy-priorities-list '("[A]" "[B]" "[C]")
   org-priority-faces
   '((?A :foreground "red" :weight bold)
     (?B :foreground "green" :weight bold)
     (?C :foreground "grey" :weight bold))
   ))
```

**System information:**
Archlinux on WSL2.

**Comment by hlissner** [comment]
Replace `(after! org ...)` with `(after! org-fancy-priorities ...)`

**Comment by wang1zhen** [comment]
> 
> 
> Replace `(after! org ...)` with `(after! org-fancy-priorities ...)`

I find out that the `org-agenda-mode` does not load `org-fancy-priorities-mode` by default, is it supposed to be so?
If you simply launch Emacs and `SPC o A a`, the priorities in agenda do not look right.
 After I put
```
(add-hook 'org-agenda-mode-hook 'org-fancy-priorities-mode)
```
it works.

**Comment by ChauhanT** [comment]
Hi, I am facing a similar issue. The relevant parts of my `config.el` read: 

```
(after! org-fancy-priorities
  (setq
   org-todo-keywords '((sequence "TODO(t)" "DONE(d!)"))
   org-startup-folded 'content
   org-priority-highest '?A
   org-priority-lowest  '?D
   org-priority-default '?D
   org-priority-start-cycle-with-default t
   org-priority-faces '((?A :foreground "#F54768")
                        (?B :foreground "#F5C747")
                        (?C :foreground "#62A6EB")
                        (?D :foreground "#A0A0A0"))
   org-fancy-priorities-list '("🅐","🅑","🅒","🅓")))

(add-hook 'org-agenda-mode-hook 'org-fancy-priorities-mode)
```
While I can see the proper faces in all .org files, I the org-agenda mode `Spc o A n` does not show the proper faces. The right symbols are picked up though. Any help/tips? 

Cheers!
