### ISSUE TITLE
How do i find out the list of buffers in current workspace

### ISSUE THREAD

**Issue by shelper** [hlissner/doom-emacs#4451]
in the workspace feature description it says: 

> When persp-mode is active, doom-buffer-list becomes workspace-restricted. You can overcome this by using buffer-list.

However i didnt find a way to show this doom-buffer-list that is workspace restricted. there is no global variable called `doom-buffer-list`
is there a way to show the list of buffers for current workspace?

**Comment by pspencil** [comment]
I think by default it is bound to `SPC b b`?

**Comment by shelper** [comment]
Yeah that gives you a selection but what is the variable contains that list
