### ISSUE TITLE
Symbol’s value as variable is void: all-the-icons-install-fonts

### ISSUE THREAD

**Issue by in-in** [hlissner/doom-emacs#4452]
**What did you expect to happen?**
Successfully installed ‘all-the-icons’
...

**What actually happened?**
Symbol’s value as variable is void: all-the-icons-install-fonts
...

**Additional details:**
- Include a link to your private config: I don't have one.
- Include screenshots/casts of your issue
![203541608380215](https://user-images.githubusercontent.com/8797432/102689208-569bef00-420d-11eb-8849-1de938b783f2.png)

**Steps to reproduce:**
1. Open terminal and run `emacs --batch -f all-the-icons-install-fonts`

According to the [documentation](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#install-doom-manually) the last step of the manual installation should be `emacs --batch -f all-the-icons-install-fonts`, but this command doesn't work.
![image](https://user-images.githubusercontent.com/8797432/102689419-0a51ae80-420f-11eb-9529-8291cf110f5e.png)

**System information:**
<details><pre>
SYSTEM  type       gnu/linux
	config     x86_64-pc-linux-gnu
	shell      /usr/bin/zsh
	uname      Linux 5.4.0-58-generic #64-Ubuntu SMP Wed Dec 9 08:16:25 UTC 2020 x86_64
	path       (~/.config/emacs/bin ~/.nvm/versions/node/v14.15.1/bin ~/.local/bin ~/bin /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /usr/games /usr/local/games /snap/bin /usr/lib/emacs/27.1/x86_64-linux-gnu)
EMACS   dir        ~/.config/emacs/
	version    27.1
	build      Sep 19, 2020
	buildopts  --build=x86_64-linux-gnu --prefix=/usr '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' --sysconfdir=/etc --localstatedir=/var --disable-silent-rules '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' --disable-maintainer-mode --disable-dependency-tracking --prefix=/usr --sharedstatedir=/var/lib --libexecdir=/usr/lib --localstatedir=/var/lib --infodir=/usr/share/info --mandir=/usr/share/man --enable-locallisppath=/etc/emacs:/usr/local/share/emacs/27.1/site-lisp:/usr/local/share/emacs/site-lisp:/usr/share/emacs/27.1/site-lisp:/usr/share/emacs/site-lisp --program-suffix=27 --with-modules --with-file-notification=inotify --with-mailutils --with-harfbuzz --with-json --with-x=yes --with-x-toolkit=gtk3 --with-lcms2 --with-cairo --with-xpm=yes --with-gif=yes --with-gnutls=yes --with-jpeg=yes --with-png=yes --with-tiff=yes --with-xwidgets 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/emacs27-bifpWT/emacs27-27.1~1.git86d8d76aa3=. -fstack-protector-strong -Wformat -Werror=format-security -no-pie' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro -no-pie'
	features   XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER LCMS2 GMP
	traits     (batch envvar-file)
DOOM    dir        ~/.config/doom/
	version    2.0.9
	build      grafted, HEAD -> develop, origin/develop, origin/HEAD 0c92564 2020-12-15 04:14:40 -0500
	elc-files  0
	modules    (:completion company ivy :ui doom doom-dashboard hl-todo modeline ophints (popup +defaults) vc-gutter vi-tilde-fringe workspaces :editor file-templates fold snippets :emacs dired electric undo vc :checkers syntax :tools ansible editorconfig (eval +overlay) lookup magit :lang emacs-lisp json javascript markdown org sh web yaml :config (default +bindings +smartparens))
	packages   (n/a)
	unpin      (n/a)
	elpa       (n/a)
</pre></details>

**Comment by karlicoss** [comment]
Same problem, I was trying to automate doom install (in Ansible-like environment).
I don't see how it could work before to be honest, I think `--batch` argument also implies it won't load doom config, so it makes sense that it doesn't know of this function.

A hack I came up with for now: `emacs --daemon --eval '(all-the-icons-install-fonts t)' --eval '(save-buffers-kill-terminal)' || true`

- `--daemon` so it doesn't try to allocate TTY (otherwise fails with 'standard input is not a tty' error)
- - `--eval '(save-buffers-kill-terminal)'` so the daemon doesn't linger around
- `|| true` to make the exist code of command 0 (otherwise it's 1 because daemon fails to start)

if anyone has suggestions how to simplify it, would be great!

**Comment by hlissner** [comment]
You have to load `all-the-icons` before you call its functions. Use `emacs --batch -l ~/.emacs.d/init.el -f all-the-icons-install-font`

Since this is not a Doom issue I will close this, but feel free to follow up here.

**Comment by hlissner** [comment]
> A hack I came up with for now: emacs --daemon --eval '(all-the-icons-install-fonts t)' --eval '(save-buffers-kill-terminal)' || true

@karlicoss This works because you're starting a daemon (effectively the same as loading `~/.emacs.d/init.el`). See my answer above.

**Comment by karlicoss** [comment]
This is great, thanks, didn't realize simply loading init.el would be enough, that's why tried the `--daemon` thing! I updated the docs to reflect it https://github.com/hlissner/doom-emacs/pull/4883/files
