### ISSUE TITLE
doom strips links within headlines

### ISSUE THREAD

**Issue by natask** [hlissner/doom-emacs#4460]
I often leave links within headlines and search by their description through org-rifle. however, I found that doom stripped links from headlines.
I found by looking at #2117 that it is caused by advice `+org--strip-properties-from-outline-a` on `org-format-outline-path`
It has a section at https://github.com/hlissner/doom-emacs/blob/0c9256411d6bdb6cfc920bcce2216d99ff28a0c5/modules/lang/org/config.el#L559-L560 which I believe is the root of this issue.

```
~/d/.l/s/build-28.0.50/org-mode [develop] λ (advice-add 'org-format-outline-path :around '+org--strip-properties-from-outline-a)

~/d/.l/s/build-28.0.50/org-mode [develop] λ (org-format-outline-path '("Head" "[[link]]"))
Head/

~/d/.l/s/build-28.0.50/org-mode [develop] λ (advice-remove 'org-format-outline-path '+org--strip-properties-from-outline-a)

~/d/.l/s/build-28.0.50/org-mode [develop] λ (org-format-outline-path '("Head" "[[link]]"))
Head/[[link]]
```
Is there a reason to why doom does this by default?

**Comment by hlissner** [comment]
This was originally done to reduce noise in the breadcumbs displayed by eldoc in the minibuffer, but it looks like org 9.5 now does its own cleanup prior to `org-format-outline-path` being called, so this may not be necessary anymore. However, if that's so it may indicate that `org-rifle` will need to adapt. Disable the advise and see if `org-rifle` still works.

```elisp
;; add to ~/.doom.d/config.el
(after! org
  (advice-remove 'org-format-outline-path '+org--strip-properties-from-outline-a))
```

**Comment by hlissner** [comment]
As of 12d8691 the links are no longer stripped out of the outline path (by Doom, anyway), which should resolve your issue if Org isn't doing its own cleanup. If it is, you may need to report this upstream, to `org-rifle`'s dev.

**Comment by natask** [comment]
I can confirm that removing this hook or atleast removing the specific line
within the hook function allows org rifle to function properly.
Thanks
