### ISSUE TITLE
xref-pop-marker-stack won't bind to a key

### ISSUE THREAD

**Issue by obelhe** [hlissner/doom-emacs#4463]
**What did you expect to happen?**
...
I expected the command `xref-pop-marker-stack` to work but it doesn't. It works fine when I call it with `M-x` in the mini buffer, but when I bind it to a key, that key doesn't seem to call it. The default key is `M-,` I tried using it as is as well as changing the keymap

**Comment by hlissner** [comment]
This is not a bug. `xref-pop-marker-stack` [is remapped to `better-jumper-jump-backward`](https://github.com/hlissner/doom-emacs/blob/develop/core/core-editor.el#L359), which is meant to supercede it (it's our "universal" jumplist).

For evil users this is bound to `C-o`. For non-evil users it's on `M-,`. `C-h k M-,` should report that it's remapped to `better-jumper-jump-backward`.

If you must undo this remapping, then use:

```lisp
;; add to ~/.doom.d/config.el
(map! [remap xref-pop-marker-stack] nil)
```
