### ISSUE TITLE
Insert mode dot auto indent

### ISSUE THREAD

**Issue by Matthieu-OD** [hlissner/doom-emacs#4464]
Hello everyone,

This is my first issue report, I will modify it to give you more informations but for the moment I don't know what informations will help you to fix my problem.

When I want to write a dot in a JS file (I tried in python files but I wasn't able to reproduce this behaviour) between brackets "(", "{" or "[" it auto indent my line and I don't want it to happen.

Thank you for your help

**Comment by hlissner** [comment]
This is due to `electric-indent-mode`. You have three options:

1. Disable `electric-indent-mode` globally: add `(electric-indent-mode -1)` to `~/.doom.d/config.el`.
2. Un-register the electric characters in js2-mode only: 

  ```lisp
  ;; add to ~/.doom.d/config.el
  (after! js2-mode
    (set-electric! 'js2-mode nil))
  ```

Hope that helps.

**Comment by Matthieu-OD** [comment]
Thank you very much ! I will test your answer in the days to come !
