### ISSUE TITLE
How do I force Doom to shift lines including cursor line

### ISSUE THREAD

**Issue by mmajewsk** [hlissner/doom-emacs#4465]
So lets say we have this in python

![image](https://user-images.githubusercontent.com/5279578/102895803-a8d74d00-4465-11eb-80f2-756cd30cad29.png)

And I want shift one width everythin right with ">" in visual mode, when my cursor is on the letter "T".
Then this happens;
![image](https://user-images.githubusercontent.com/5279578/102895889-d6bc9180-4465-11eb-850f-c819cbe1cf47.png)
But i expect to move all of the lines same width.
Like this;
![image](https://user-images.githubusercontent.com/5279578/102895934-e8059e00-4465-11eb-9da3-6667eb327145.png)

How to force that behaviour without constant need of pressing zero to move to the first column?

**Comment by WhatDothLife** [comment]
Press `V` to enter visual-line-mode and select the two lines. Then try pressing `>` again. Questions like this should be asked on reddit, or on the Doom discord channel. I think this issue tracker is no the right place to ask. Still hope that helps.

**Comment by mmajewsk** [comment]
> Press `V` to enter visual-line-mode and select the two lines. Then try pressing `>` again. Questions like this should be asked on reddit, or on the Doom discord channel. I think this issue tracker is no the right place to ask. Still hope that helps.

Please read the question again and see the images.
It does not work.

**Comment by mmajewsk** [comment]
@WhatDothLife  what i want to have is "If" line shifting right, without a need of going to the start of the line first.

https://user-images.githubusercontent.com/5279578/102980921-92360200-4508-11eb-83a8-795347f48dce.mp4

**Comment by pspencil** [comment]
Press "V" instead of "v". Then select both lines. This is really a vim
question.

**Comment by WhatDothLife** [comment]
> > Press `V` to enter visual-line-mode and select the two lines. Then try pressing `>` again. Questions like this should be asked on reddit, or on the Doom discord channel. I think this issue tracker is no the right place to ask. Still hope that helps.
> 
> Please read the question again and see the images.
> It does not work properly.
> 
> _EDIT_ I see what you mean, but I still would like to have the same behaviour as in vim

I read your question again, saw your images and still tell you the same. It'd be surprising, if the behavior is different than in vim, but I never used vim. Anyways what's the problem, with pressing `V` instead of `v`?

**Comment by pspencil** [comment]
Interesting. I didn't realise this is different from vanilla vim. Not sure if this is a problem with evil or doom.

`>` is bound to

```
;;;###autoload
(defun +evil/visual-indent ()
  "vnoremap < <gv"
  (interactive)
  (evil-shift-right (region-beginning) (region-end))
  (evil-normal-state)
  (evil-visual-restore))
```

**Comment by hlissner** [comment]
This was indeed an oversight I made when writing those wrappers. As of 6970903 this should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by mmajewsk** [comment]
> This was indeed an oversight I made when writing those wrappers. As of [6970903](https://github.com/hlissner/doom-emacs/commit/6970903a4386bab42746a9f22c9f48c111f7832c) this should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

Works better, many thanks!
