### ISSUE TITLE
#'org-agenda-list returns (error "Selecting deleted buffer")

### ISSUE THREAD

**Issue by jcguu95** [hlissner/doom-emacs#4468]
**What did you expect to happen?**
Call #'org-agenda-list without error.

**What actually happened?**
Call #'org-agenda-list, but the debugger complains. "(error "Selecting deleted buffer")"

**Additional details:**
- (I will provide specific part if needed as my config contains personal info. Thank you :) )

<details><pre>
If an error message is involved include a backtrace of it.

How to acquire a backtrace:
https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#how-to-extract-a-backtrace-from-an-error
</pre></details>

**Steps to reproduce:**
1. Start emacs with `--debug-init`.
2. Evaluate   (org-agenda-list nil "TODAY" 1 nil).
3. Observe that it's nice and smooth.
4. Kill org-agenda buffer.
5. Evaluate   (org-agenda-list nil "TODAY" 1 nil) again.
6. Org-agenda shows as expected, but the debugger complains:

```
Debugger entered--Lisp error: (error "Selecting deleted buffer")
  set-buffer(#<killed buffer>)
  (save-current-buffer (set-buffer buffer) (add-hook 'doom-switch-buffer-hook #'+org--restart-mode-h nil 'local))
  (let ((buffer (car --dolist-tail--))) (save-current-buffer (set-buffer buffer) (add-hook 'doom-switch-buffer-hook #'+org--restart-mode-h nil 'local)) (setq --dolist-tail-- (cdr --dolist-tail--)))
  (while --dolist-tail-- (let ((buffer (car --dolist-tail--))) (save-current-buffer (set-buffer buffer) (add-hook 'doom-switch-buffer-hook #'+org--restart-mode-h nil 'local)) (setq --dolist-tail-- (cdr --dolist-tail--))))
  (let ((--dolist-tail-- org-agenda-new-buffers)) (while --dolist-tail-- (let ((buffer (car --dolist-tail--))) (save-current-buffer (set-buffer buffer) (add-hook 'doom-switch-buffer-hook #'+org--restart-mode-h nil 'local)) (setq --dolist-tail-- (cdr --dolist-tail--)))))
  +org-defer-mode-in-agenda-buffers-h()
  run-hooks(org-agenda-finalize-hook)
  org-agenda-finalize()
  org-agenda-list(nil "TODAY" 1 nil)
```

**System information:**
<details><pre>
SYSTEM  type       gnu/linux
	config     x86_64-pc-linux-gnu
	shell      /bin/zsh
	uname      Linux 5.4.83-1-lts #1 SMP Sat, 12 Dec 2020 14:36:47 +0000 x86_64
	path       (~/.+PLUGS/Local/.emacs.d/bin/ ~/.cabal/bin ~/.ghcup/ghc/8.8.3/bin ~/.ghcup/bin /usr/local/sbin /usr/local/bin /usr/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl ~/.local/bin/cron ~/.local/bin/i3cmds ~/.local/bin/statusbar ~/.local/bin/ ~/.scripts ~/.scripts/bin ~/.scripts/dictionary ~/.gem/ruby/2.7.0/bin ~/.emacs.d/bin /usr/lib/emacs/27.1/x86_64-pc-linux-gnu)
EMACS   dir        ~/.+PLUGS/Local/.emacs.d/
	version    27.1
	build      Aug 28, 2020
	buildopts  --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-wide-int --with-modules --with-cairo --with-harfbuzz 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
	features   XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP
	traits     (batch server-running envvar-file)
DOOM    dir        ~/.+PLUGS/tilde/.config/doom/
	version    2.0.9
	build      HEAD -> develop 0c9256411 2020-12-15 04:14:40 -0500
	elc-files  0
	modules    (:input chinese :completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline ophints workspaces :editor (evil +everywhere) fold :emacs dired electric ibuffer undo vc :term eshell vterm :checkers (spell +aspell) :tools debugger (eval +overlay) lookup lsp (magit +forge) pass pdf :os tty :lang common-lisp emacs-lisp (latex +latexmk +cdlatex +fold) ledger markdown (org +roam +pandoc +gnuplot +noter +dragndrop) (sh +lsp) (yaml +lsp) :email notmuch :app irc :config (default +bindings +smartparens))
	packages   ((org-superstar :disable t) (org-download) (org-super-agenda) (org-noter) (emms) (ob-sagemath) (slime) (gnuplot) (paredit) (org-ql) (emojify) (origami))
	unpin      (n/a)
	elpa       (n/a)

</pre></details>

**Comment by Delanii** [comment]
This happens to me too during closing + saving a file (via `:x` command). It happens seemingly randomly, with any file, not specifically org-agenda. For me it is a minor problem, I just isuue the command `:x` again and it works.

Just wanted to say that someone is experiencing something simillarr too :)

I hope that it is not a spam :)

**Comment by jcguu95** [comment]
I'd say it's minor to me too. It did not break other things.. the `:x` trick did not work for me, as the same error shows up after I do that. Thanks for sharing anyway :)

**Comment by jcguu95** [comment]
This issue isn't minor anymore, as I noticed it breaks `origami-mode`'s behaviour.

**Comment by jcguu95** [comment]
I think this is the issue of `org-agenda`, but rather of doomemacs.

The correct way to exit `org-agenda` is to use the elisp function `org-agenda-exit`. Killing the agenda buffer directly from `ibuffer-mode` results an error.

**Solution**: 

1. Exist `org-agenda` by invoking `org-agenda-exit`.
2. Reload `org-agenda`.
