### ISSUE TITLE
Doom not installing on windows.

### ISSUE THREAD

**Issue by SirAxolot** [hlissner/doom-emacs#4474]
**What did you expect to happen?**
I expected Doom to install normally, in accordance with [this guide](https://earvingad.github.io/posts/doom_emacs_windows/).

**What actually happened?**
Doom did not install properly, and something got messed up.

**Additional details:**
- I have done nothing except attempt to install Doom.
- [This is what happened when I invoked Emacs from the command line](https://imgur.com/a/aBENcy8).
- When I got to the point of running `./doom install`, it returned `Can't find emacs in your PATH`.
- If you remember, the command `emacs` does work bc I added it to PATH.

**Steps to reproduce:**
1. Follow Earvingad's guide up to `./doom install`
2. Run said command
3. Witness how it doesn't work.

**System information:**
<details><pre>
 I have no idea how to do this if doom is not installed.
</pre></details>

**Comment by matzesc** [comment]
Hi @SirAxolot,

It seems that you don't have `emacs` in your PATH variable.

I assume that you tried to run `doom install` from Git bash. What happens when you run `which emacs` from Git bash?

**Comment by hlissner** [comment]
This is being closed because it hasn't received a response. Feel free to follow up and I'll reopen it.

Side note: `Can't find emacs in your PATH` means that `emacs` cannot be found in your `PATH`. Set the `EMACS` environment variable to specify the full path of the executable.
