### ISSUE TITLE
Trigger leader mode map in emacs-state

### ISSUE THREAD

**Issue by benj02** [hlissner/doom-emacs#448]
Hi All,

I'm looking for a way to set a binding that would trigger the leader mode-map in buffers without evil, or in evil's emacs-state, like dired, comin, man page, and other modes. Basically where I'd normally type "SPC o n" in these buffers I'd instead type "M-m o n" or similar like in spacemacs. I'm sure there's an easy way to do this, I just need it pointed out.

Thanks in advance for the help :smile:

**Comment by hlissner** [comment]
You can change `doom-leader-key` (<kbd>SPC</kbd>) and `doom-localleader-key` (<kbd>SPC m</kbd>). e.g.

```elisp
(setq doom-leader-key "M-m"
      doom-localleader-key "M-S-m")
```

I suggest putting this in one of your `init.el` files. For example: `~/.emacs.d/init.el` or `~/.doom.d/init.el`.

Hope that helps!

**Comment by benj02** [comment]
Hmm, that's not quite it. I'd still like to be able to use the normal leader key "SPC", just have an additional leader key to use in non evil buffers

**Comment by hlissner** [comment]
Ah, I see what you mean. An alias for the leader key. Unfortunately, there's no simple way to do this.

I plan to redesign the keybind system after 2.1 goes up (to use general.el behind the scenes). I suspect this change will make your request possible, but it may be a while until I get there (until May, I think).

**Comment by benj02** [comment]
Thanks for the answer! In the interim, I'm gonna see if i can play around with the `map!` macro and convince it to make two bindings for every binding it declares, one beginning with leader and one with "M-m". Will update this ticket if I get it working!

**Comment by hlissner** [comment]
Now that general is in Doom, we've got four variables for controlling leader/localleader keys in evil and non-evil sessions and states:

These are used in evil normal, visual and motion states:

+ `doom-leader-key` (default: `"SPC"`)
+ `doom-localleader-key` (`"SPC m"`)

And these are used in insert and emacs states, as well as non-evil sessions:

+ `doom-leader-alt-key` (`"M-SPC"`)
+ `doom-localleader-alt-key` (`"M-SPC m"`)

Change them as early as possible (in `~/.doom.d/init.el`) for the new keys to take effect.

With that I'll consider this issue resolved. Let me know if there's anything else you need help with.
