### ISSUE TITLE
How could I use chemacs to have two distinct doom instalations on the same system?

### ISSUE THREAD

**Issue by mrbig033** [hlissner/doom-emacs#4480]
This is not clear for me. Thanks.

**Comment by Delanii** [comment]
You should ask this on discord server ...

**Comment by hlissner** [comment]
1. Clone this repo to `~/doom-emacs1` and again to `~/doom-emacs2`.
2. Create `~/doom-emacs-private1` and `~/doom-emacs-private2` for your private configs (unless you want to have the same one).
3. Put the following in `~/.emacs-profiles.el`:

   ```lisp
   (("doom1" . ((user-emacs-directory . "~/doom-emacs1")
                (env . (("DOOMDIR" . "~/doom-emacs-private1")))))

    ("doom2" . ((user-emacs-directory . "~/doom-emacs2")
                (env . (("DOOMDIR" . "~/doom-emacs-private2"))))))
   ```
4. Launch them. e.g. `emacs --profile doom2`

You'll have to sync/upgrade them independently: `~/doom-emacs1/bin/doom sync` and `~/doom-emacs2/bin/doom sync` though.
