### ISSUE TITLE
enabling cli auto confirmations quits doom cli script on Windows

### ISSUE THREAD

**Issue by RoryO** [hlissner/doom-emacs#4486]
**What did you expect to happen?**
Running `doom -y upgrade` on Windows performs the upgrade unattended

**What actually happened?**
CLI tool prints `- Confirmations auto-accept enabled` and exits.

**Additional details:**

```
PS C:\Users\r\AppData\Roaming\.emacs.d\bin> ./doom -y upgrade
- Confirmations auto-accept enabled
PS C:\Users\r\AppData\Roaming\.emacs.d\bin> cmd
Microsoft Windows [Version 10.0.19042.685]
(c) 2020 Microsoft Corporation. All rights reserved.

C:\Users\r\AppData\Roaming\.emacs.d\bin>doom -y upgrade
- Confirmations auto-accept enabled

C:\Users\r\AppData\Roaming\.emacs.d\bin>
```

Additionally, adding the `-y` switch at the end as suggested in #4199 is a parse error

```
PS C:\Users\r\AppData\Roaming\.emacs.d\bin> ./doom upgrade -y
! Unrecognized switch "-y"
PS C:\Users\r\AppData\Roaming\.emacs.d\bin> ./doom upgrade -yes
! Unrecognized switch "-y"
PS C:\Users\r\AppData\Roaming\.emacs.d\bin> cmd
Microsoft Windows [Version 10.0.19042.685]
(c) 2020 Microsoft Corporation. All rights reserved.

C:\Users\r\AppData\Roaming\.emacs.d\bin>doom upgrade -y
! Unrecognized switch "-y"

C:\Users\r\AppData\Roaming\.emacs.d\bin>doom upgrade -yes
! Unrecognized switch "-y"
```

**Steps to reproduce:**
1. Run `doom -y upgrade` on Windows with either Powershell or cmd
2. Gentlemen, behold!

**System information:**
<details><pre>
SYSTEM  type       windows-nt
        config     x86_64-w64-mingw32
        shell      a:/emacs27/libexec/emacs/27.1/x86_64-w64-mingw32/cmdproxy.exe
        uname      n/a
        path       (C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\bin\HostX64\x64 C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\IDE\VC\VCPackages C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\IDE\CommonExtensions\Microsoft\TestWindow C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\bin\Roslyn C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x64 C:\Program Files (x86)\Windows Kits\10\bin\x64 C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\\MSBuild\Current\Bin C:\Windows\Microsoft.NET\Framework64\v4.0.30319 C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\IDE\ C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\Tools\ C:\Program Files\PowerShell\7 C:\VulkanSDK\1.2.154.1\Bin C:\VulkanSDK\1.2.135.0\Bin C:\VulkanSDK\1.1.130.0\Bin C:\WINDOWS\system32 C:\WINDOWS C:\WINDOWS\System32\Wbem C:\WINDOWS\System32\WindowsPowerShell\v1.0\ C:\WINDOWS\System32\OpenSSH\ C:\ProgramData\chocolatey\bin C:\Program Files\PowerShell\7-preview\preview C:\Program Files\PowerShell\7\ C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\ C:\Program Files\dotnet\ C:\Users\$USER\scoop\apps\nodejs\current\bin C:\Users\$USER\scoop\apps\nodejs\current C:\Users\$USER\scoop\apps\python\current\Scripts C:\Users\$USER\scoop\apps\python\current C:\Users\$USER\scoop\apps\elixir\current\bin C:\Users\$USER\scoop\apps\ruby\current\gems\bin C:\Users\$USER\scoop\apps\ruby\current\bin C:\Users\$USER\scoop\shims C:\Program Files\CMake\bin C:\msys64\mingw64\bin\ C:\msys64\usr\local\bin C:\msys64\usr\bin C:\Users\$USER\AppData\Local\Programs\Python\Python38-32\Scripts\ C:\Users\$USER\AppData\Local\Programs\Python\Python38-32\ C:\Users\$USER\AppData\Local\Microsoft\WindowsApps C:\Users\$USER\AppData\Local\Programs\Microsoft VS Code\bin a:\bin a:\emacs27\bin C:\Program Files\LLVM\bin C:\Users\$USER\AppData\Local\Keybase\ C:\Users\$USER\AppData\Local\GitHubDesktop\bin C:\Users\$USER\elixir-ls C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja a:/emacs27/libexec/emacs/27.1/x86_64-w64-mingw32/)
EMACS   dir        ~/.emacs.d/
        version    27.1
        build      Aug 21, 2020
        buildopts  --without-dbus --host=x86_64-w64-mingw32 --without-compress-install 'CFLAGS=-O2 -static'
        features   XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY W32NOTIFY ACL GNUTLS LIBXML2 HARFBUZZ ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS JSON PDUMPER LCMS2 GMP
        traits     (gui server-running envvar-file)
DOOM    dir        a:/dotfiles/.doom.d/
        version    2.0.9
        font       #<font-spec nil nil Consolas nil nil nil nil nil 36 nil nil nil nil>
        theme      doom-material
        build      HEAD -> develop 0c9256411 2020-12-15 04:14:40 -0500
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard hl-todo modeline nav-flash ophints (popup +all +defaults) vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) fold snippets :emacs dired electric ibuffer undo :checkers syntax (spell +flyspell +hunspell) grammar :tools (eval +overlay) lookup lsp :lang (cc +lsp) data emacs-lisp markdown org :config (default +bindings +smartparens))
        packages   ((writeroom-mode) (zig-mode) (evil-markdown :disable t))
        unpin      (n/a)
        elpa       (n/a)
</pre></details>

**Comment by hlissner** [comment]
It's a known issue on Windows. I'm afraid I don't know the cause, nor do I have a Windows system to test on. Probably related to #3844 or #3746.

In any case, I've moved this to #4273 since it falls under the umbrella of issues I hope the rewrite will solve.
