### ISSUE TITLE
Python autocompletion not working

### ISSUE THREAD

**Issue by zihenlin** [hlissner/doom-emacs#4496]
**What did you expect to happen?**
...
completion menu shows while coding.

**What actually happened?**
...
No completion menu shows up at all. 

<details><pre>
deferred error : (error "\"TypeError('__init__() takes from 1 to 2 positional arguments but 5 positional arguments (and 1 keyword-only argument) were given')\"") 

This happened for both anaconda and jedi.

For Elpy, it shows:

In:Metric() without any completion menu.
</pre></details>

**Steps to reproduce:**
1. Fresh install doom emacs, enable python in init.el
2. edit a .py file and try out the completion menu.

**System information:**
<details><pre>
SYSTEM  type       gnu/linux
	config     x86_64-slackware-linux-gnu
	shell      /usr/bin/fish
	uname      Linux 5.4.84 #1 SMP Fri Jan 1 12:27:47 HKT 2021 x86_64
	path       (~/.local/bin ~/.emacs.d/bin /usr/local/bin /usr/bin /bin /usr/games /usr/share/ant/bin /usr/lib64/libreoffice/program /usr/lib64/java/bin /usr/lib64/java/jre/bin /usr/lib64/java/jre/bin /usr/lib64/qt5/bin /usr/local/bin /bin /usr/bin /usr/libexec/emacs/27.1/x86_64-slackware-linux)
EMACS   dir        ~/.emacs.d/
	version    27.1
	build      Aug 12, 2020
	buildopts  --prefix=/usr --sysconfdir=/etc --localstatedir=/var --program-prefix= --program-suffix= --mandir=/usr/man --infodir=/usr/info --without-gconf --without-gsettings --with-modules --with-x --with-x-toolkit=gtk3 --build=x86_64-slackware-linux 'CFLAGS=-O2 -fPIC'
	features   XPM JPEG TIFF GIF PNG RSVG SOUND GPM DBUS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS JSON PDUMPER LCMS2 GMP
	traits     (batch server-running envvar-file)
DOOM    dir        ~/.doom.d/
	version    2.0.9
	build      grafted, HEAD -> develop, origin/develop, origin/HEAD 0c92564 2020-12-15 04:14:40 -0500
	elc-files  0
	modules    (:input chinese :completion company ivy :ui doom doom-dashboard doom-quit hl-todo ligatures modeline neotree ophints (popup +defaults) vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold (format +onsave) snippets :emacs dired electric undo vc :term vterm :checkers syntax spell :tools (eval +overlay) lookup magit :lang data emacs-lisp json (java +meghanada) javascript markdown org python sh web yaml :config (default +bindings +smartparens))
	packages   ((elpy) (jedi) (yapfify) (anaconda-mode :disable t))
	unpin      (n/a)
	elpa       (yapfify)

anaconda was disabled to try out other python autocompletion backend.
</pre></details>

**Comment by althusky** [comment]
You may try downgrade jedi  version 0.17.2 working well.
```
pip3 uninstall jedi
pip3 install jedi==0.17.2
```

**Comment by tobinstultiens** [comment]
Downgrading to that version of jedi had no impact on the error. Although my error was a bit different.

<details>
<summary>Error</summary>

> Server error: TypeError('__init__() takes from 1 to 2 positional arguments but 5 positional arguments (and 1 keyword-only argument) were given') - see *anaconda-mode* for more information.

</details>

**Comment by hlissner** [comment]
This is because we had an old version of `anaconda-mode` installed, which installs an outdated version of anaconda. As of 4aed841 I've bumped anaconda. Update Doom+packages with `doom upgrade` and the issue should go away.

**Comment by 354651432** [comment]
I have upgrade doom to the latest version, but it doesn't work as well 
```
Server error: TypeError('__init__() takes from 1 to 2 positional arguments but 5 positional arguments (and 1 keyword-only argument) were given') - see *anaconda-mode* for more information. [4 times]
```

**Comment by elmehalawi** [comment]
@354651432 Are you sure you ran this:

```
~/.emacs/bin/doom upgrade
```

And then restarted? Because that did it for me.
