### ISSUE TITLE
What is the correct way to profile Doom startup?

### ISSUE THREAD

**Issue by mrbig033** [hlissner/doom-emacs#4498]
I usually use `benchmark-init`, but with Doom it doesn't give any data. Probably because of Doom's unique features. Is there a way to get the loading times for each package so I can optimize my startup?

**Comment by hlissner** [comment]
1. Add `(package! benchmark-init)` to `~/.doom.d/packages.el`
2. Add this to `~/.doom.d/init.el`

   ```elisp
   (require 'benchmark-init)
   (add-hook 'doom-first-input-hook #'benchmark-init/deactivate)
   ```
3. Restart Emacs
4. `M-x benchmark-init/show-durations-tabuled` or `M-x benchmark-init/show-durations-tree`

This worked fine for me.
