### ISSUE TITLE
option to disable ivy/project-compile overrides on projectile commands

### ISSUE THREAD

**Issue by samwhitlock** [hlissner/doom-emacs#4499]
Currently the use of ivy as the completion framework [overrides projectile-compile-project](https://github.com/hlissner/doom-emacs/blob/develop/modules/completion/ivy/config.el#L198).

This override uses `counsel-compile` to execute the compile command. Although `projectile-project-root` is added to `counsel-compile-root-functions` to aid in the Ivy suggestions, the actual compile commands are not taken from projectile. Instead, counsel relies on its own suggestions (in `counsel-compile-local-builds`), which is not as smart as projectile's suggestions.

I propose a boolean custom variable about whether this one override should happen or not. For my workflow at least (and I suspect others), Projectile already tracks the correct directories and compile commands.

If this is not ideal, I can try to work on a PR that interposes on this (e.g. by adding another function to `counsel-compile-local-builds`), but trying to hack counsel to do what projectile already does seems like a last resort compared to just not overriding in the first place.

**Comment by jozefl** [comment]
I'm not sure if below is the best way to do achieve this, but I worked around this issue by adding the following snippet to my .doom.d/config.el:
```
(use-package! counsel
  :defer t
  :init
  (define-key!
    [remap projectile-compile-project] #'projectile-compile-project))
```
Now `projectile-compile-project` (`SPC-p-c`) autofills the argument with `compile-command`, (`make` in  my case).
