### ISSUE TITLE
Getting an ugly blue color as background in terminal

### ISSUE THREAD

**Issue by lincoln177** [hlissner/doom-emacs#4500]
**What did you expect to happen?**
I want to make emacs use the same background color as my terminal. I'm trying to do that like this:
```
(custom-set-faces
  '(default ((t (:background "#282a36"))))
 )
```

**What actually happened?**
Instead of the grey [color](https://www.colorhexa.com/282a36) that actually is, I get a [blue](https://www.colorhexa.com/00005f).

**Additional details:**
I've read on through some of the issues and it seems like the issue is solaire-mode.
I've tried putting this in my packages.el:
```
(package! solaire-mode :disable t)
```
and this in my config.el:
```
(after! solaire-mode
  (solaire-global-mode -1))
```
I tried both individually, I restarted the emacs daemon every time and also doom synced every time, without any apparent effect.

**System information:**
<details><pre>
SYSTEM  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/zsh
        uname      Linux 5.9.14-arch1-1 #1 SMP PREEMPT Sat, 12 Dec 2020 14:37:12 +0000 x86_64
        path       (~/.emacs.d/bin/ /usr/local/bin /usr/bin /bin /usr/local/sbin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl ~/.rvm/bin ~/.gem/ruby/2.7.0/bin/ ~/.rvm/bin /usr/lib/emacs/27.1/x86_64-pc-linux-gnu/)
EMACS   dir        ~/.emacs.d/
        version    27.1
        build      Aug 28, 2020
        buildopts  --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-wide-int --with-modules --with-cairo --with-harfbuzz 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
        features   XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP
        traits     (tty daemon server-running envvar-file)
DOOM    dir        ~/.config/doom/
        version    2.0.9
        font       nil
        theme      doom-dracula
        build      grafted, HEAD -> develop, origin/develop, origin/HEAD 0c92564 2020-12-15 04:14:40 -0500
        elc-files  0
        modules    (:completion company (&nopath +tng) (ivy +fuzzy +prescient +icons) :ui doom doom-dashboard doom-quit (emoji +unicode) hl-todo modeline ophints (popup +defaults) treemacs unicode vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold format multiple-cursors snippets word-wrap :emacs dired electric undo vc :term vterm :checkers syntax (spell +flyspell +everywhere +hunspell) :tools editorconfig (eval +overlay) lookup lsp magit rgb :os tty :lang (cc +lsp) crystal (csharp +lsp) data emacs-lisp (go +lsp) (json +lsp) (java +meghanada) (javascript +lsp) latex (ledger +lsp) lua markdown (org +journal +gnuplot +pandoc +present +pretty +dragndrop) (python +lsp) (ruby +lsp +rails) (rust +lsp) (sh +lsp) (web +lsp) (yaml +lsp) :email notmuch :config literate (default +bindings +smartparens))
        packages   ((solaire-mode :disable t) (peep-dired) (atomic-chrome))
        unpin      (n/a)
        elpa       (websocket atomic-chrome)
</pre></details>

**Comment by gagbo** [comment]
Your terminal is not handling truecolor properly, or Emacs doesn't know. Check the readme of `:os tty` module and https://gist.github.com/sindresorhus/bed863fb8bedf023b833c88c322e44f9

**Comment by lincoln177** [comment]
My terminal is definitely handling true colour properly, it works flawlessly in all other programs. 
I had read the :os tty documentation, but dismissed it because of this

> This advice only applies to Emacs 26.x. True color support is built into 27.1+ and newer.

Since I'm using 27.1, but the instructions there actually did fix my problem. Thanks.
