### ISSUE TITLE
GolangCI-lint doesn't look right

### ISSUE THREAD

**Issue by blithefeng** [hlissner/doom-emacs#4522]
**What did you expect to happen?**
I have defined an exported variable in go file, and GolangCI-lint should report an error like this:
`manager.go:35:2: exported const LocalVariable should have comment (or a comment on this block) or be unexported (golint)`

**What actually happened?**
In Doom, there was no error. But I got message:
`Suspicious state from syntax checker golangci-lint: Flycheck checker golangci-lint returned 1, but its output contained no errors: 
Try installing a more recent version of golangci-lint, and please open a bug report if the issue persists in the latest release.  Thanks!`

**Additional details:**
I use `flycheck-golangci-lint` package in config.el
```emacs-lisp
(setq flycheck-golangci-lint-fast t)
(setq flycheck-golangci-lint-enable-linters '("golint"))
(eval-after-load 'flycheck
  '(add-hook 'flycheck-mode-hook #'flycheck-golangci-lint-setup))
```

GolangCI-lint is the latest version
```
golangci-lint has version 1.35.2 built from 1da5701 on 2021-01-11T02:54:03Z
```

**Steps to reproduce:**
1. Enable flycheck-golangci-lint package
2. Create a go file and define an exported variable or function
3. Check whether checker reports an error or not

**System information:**
<details><pre>
```
SYSTEM  type       darwin
	config     x86_64-apple-darwin18.7.0
	shell      /bin/zsh
	uname      Darwin 19.6.0 Darwin Kernel Version 19.6.0: Tue Nov 10 00:10:30 PST 2020; root:xnu-6153.141.10~1/RELEASE_X86_64 x86_64
	path       (~/go/bin /usr/local/opt/llvm/bin /usr/local/opt/texinfo/bin /usr/local/bin /usr/bin /bin /usr/sbin  /Library/TeX/texbin /usr/local/go/bin /usr/local/share/dotnet ~/.dotnet/tools /Library/Frameworks/Mono.framework/Versions/Current/Commands /Applications/Wireshark.app/Contents/MacOS /Applications/Emacs.app/Contents/MacOS/bin-x86_64-10_14 /Applications/Emacs.app/Contents/MacOS/libexec-x86_64-10_14 /Applications/Emacs.app/Contents/MacOS/libexec /Applications/Emacs.app/Contents/MacOS/bin)
EMACS   dir        ~/.emacs.d/
	version    27.1
	build       8 12, 2020
	buildopts  --with-ns '--enable-locallisppath=/Library/Application Support/Emacs/${version}/site-lisp:/Library/Application Support/Emacs/site-lisp' --with-modules
	features   NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS JSON PDUMPER
	traits     (batch server-running envvar-file)
DOOM    dir        ~/.doom.d/
	version    2.0.9
	build      HEAD -> develop b03fdabe 2021-01-13 14:07:47 -0500
	elc-files  150
	modules    (:completion company ivy :ui doom doom-dashboard hl-todo modeline ophints (popup +defaults) tabs treemacs vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold snippets :emacs dired electric undo vc :checkers syntax :tools (eval +overlay) lookup lsp magit :os macos :lang cc emacs-lisp (go +lsp) (java +meghanada) latex lua markdown org python scala sh :config (default +bindings +smartparens))
	packages   (n/a)
	unpin      (n/a)
	elpa       (n/a)
```
</pre></details>

**Comment by hlissner** [comment]
This doesn't seem like a Doom issue. Also,  Check `M-x flycheck-verify-setup` for any additional information from the checker, then report this [upstream](https://github.com/weijiangan/flycheck-golangci-lint). 

Also, remove your `eval-after-load` block, it's [redundant](https://github.com/hlissner/doom-emacs/blob/develop/modules/lang/go/config.el#L78).

**Comment by blithefeng** [comment]
Thanks!
I have resolved it by explicitly set the `flycheck-checker` to golangci-lint.
