### ISSUE TITLE
Doom breaks Org-Roam Backlink Buffer Links Functionality

### ISSUE THREAD

**Issue by AlexxHD** [hlissner/doom-emacs#4524]
**What did you expect to happen?**
If you use Org-Roam in Doom, using the Org-Roam backlink buffer should allow you to follow links in this buffer which open files in the window you are using. 

**What actually happened?**
The backlink in the Org-Roam backlink buffer opens the file correctly the first time it is used. Subsequently, however, clicking a backlink will split the main window so that it is in two, and backlinks open the files they reference alternating between these two windows. 

Interestingly, if you toggle the backlink section on and off again, the behaviour will reset, and the next backlink you use will work correctly (although from then onwards the behaviour will be defective until you toggle buffer closed and open again)

**Additional details:**

I have explored this issue a bit already with the Org-Roam forum. https://org-roam.discourse.group/t/help-implementing-the-opening-internal-links-in-the-same-window-frame-work-around-fix/1151

**Steps to reproduce:**
1) Install Org-Roam, with a few example notes
2) use the backlink buffer to navigate between them, and it will split the main window after using the backlinks once. This is the defective behaviour

**System information:**
<details><pre>
```
SYSTEM  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/bash
        uname      Linux 4.19.0-13-amd64 #1 SMP Debian 4.19.160-2 (2020-11-28) x86_64
        path       (~/.emacs.d/bin/ /usr/local/Zotero_linux-x86_64 ~/.emacs.d/bin /usr/local/bin /usr/bin /bin /usr/local/games /usr/games /sbin /usr/sbin ~/.emacs.d/bin/doom /usr/lib/emacs/26.1/x86_64-linux-gnu/)
EMACS   dir        ~/.emacs.d/
        version    26.1
        build      Sep 23, 2019
        buildopts  --build x86_64-linux-gnu --prefix=/usr --sharedstatedir=/var/lib --libexecdir=/usr/lib --localstatedir=/var/lib --infodir=/usr/share/info --mandir=/usr/share/man --enable-libsystemd --with-pop=yes --enable-locallisppath=/etc/emacs:/usr/local/share/emacs/26.1/site-lisp:/usr/local/share/emacs/site-lisp:/usr/share/emacs/26.1/site-lisp:/usr/share/emacs/site-lisp --with-sound=alsa --without-gconf --with-mailutils --build x86_64-linux-gnu --prefix=/usr --sharedstatedir=/var/lib --libexecdir=/usr/lib --localstatedir=/var/lib --infodir=/usr/share/info --mandir=/usr/share/man --enable-libsystemd --with-pop=yes --enable-locallisppath=/etc/emacs:/usr/local/share/emacs/26.1/site-lisp:/usr/local/share/emacs/site-lisp:/usr/share/emacs/26.1/site-lisp:/usr/share/emacs/site-lisp --with-sound=alsa --without-gconf --with-mailutils --with-x=yes --with-x-toolkit=gtk3 --with-toolkit-scroll-bars 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/emacs-StqULU/emacs-26.1+1=. -fstack-protector-strong -Wformat -Werror=format-security -Wall' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' LDFLAGS=-Wl,-z,relro
        features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 THREADS LIBSYSTEMD LCMS2
        traits     (gui server-running envvar-file)
DOOM    dir        ~/.doom.d/
        version    2.0.9
        font       #<font-spec nil nil monospace nil nil semi-light nil nil 20 nil nil nil nil>
        theme      doom-one
        build      HEAD -> develop b03fdabe4 2021-01-13 14:07:47 -0500
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo minimap modeline neotree ophints (popup +defaults) treemacs vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold snippets word-wrap :emacs dired electric undo vc :term eshell shell :checkers syntax :tools (eval +overlay) lookup magit pdf :lang emacs-lisp (haskell +dante) markdown org sh :config (default +bindings +smartparens))
        packages   ((org-roam) (org-ref) (org-download) (org-bullets))
        unpin      (n/a)
        elpa       (vimgolf s org-roam org-download org f emms emacsql-sqlite3 emacsql dash async)
```

</pre></details>

**Comment by hlissner** [comment]
Does this help?

```elisp
;; add to ~/.doom.d/config.el
(add-hook! 'org-roam-backlinks-mode
  (make-local-variable 'org-link-frame-setup)
  (setf (alist-get 'file org-link-frame-setup) #'find-file-other-window))
```

**Comment by AlexxHD** [comment]
Unfortunately not Hlissner

**Comment by jethrokuan** [comment]
Not really a Doom bug, this is an ongoing issue in Org-roam itself.

**Comment by AlexxHD** [comment]
Are there any temporary work arounds for this problem @jethrokuan that people have had any success with?

**Comment by AlexxHD** [comment]
probably not appropriate for doom-emacs github, am still interested in a workaround solution, if anyone can find one.

**Comment by nobiot** [comment]
@jethrokuan, I cannot reproduce the behaviour reported in my vanilla config, but I can if I install Doom; that is, with vanilla, following a link in the org-roam buffer replaces the note buffer.

What do you think is the issue in Org-roam?

We have done some more digging in this [Org-roam forum](https://org-roam.discourse.group/t/help-implementing-the-opening-internal-links-in-the-same-window-frame-work-around-fix/1151) (as AlexxHD sites).

I cannot be certain, but Doom behaviour changed when I fiddled with these -- but could not make it work like vanilla does.
```
   (setq +org-roam-open-buffer-on-find-file nil)  ;; with +roam, it defaults to t                                
  (setq org-roam-buffer-window-parameters nil)  ;; with +roam, it has some value                 
  (setq org-open-at-point-functions '(org-roam-open-id-at-point)) ;; Looks like Doom puts something related to `jump` something, which I don't fully understand
```
