### ISSUE TITLE
Apple M1

### ISSUE THREAD

**Issue by ryanpeach** [hlissner/doom-emacs#4527]
**What did you expect to happen?**
...

`doom install` should install.

**What actually happened?**
...

"This Application Will Not Run On Your Computer. Sorry!"

**Additional details:**

What do you think the steps will be to get this running on an M1 Macintosh? Are there any compilation instructions you'd like me to try to follow?

I can't live without my doom.

**Comment by hlissner** [comment]
This appears to be an Emacs issue, rather than a Doom issue. Perhaps [this article can help](https://amitp.blogspot.com/2020/11/building-emacs-27-on-apple-arm-m1.html). I also believe the `emacs-mac` formula on homebrew should have ARM support for M1 macs.

**Comment by ryanpeach** [comment]
Actually it seems to be related to this https://apple.stackexchange.com/questions/281267/symlinks-to-executables-in-applications-cannot-run

**Comment by ryanpeach** [comment]
Right here https://github.com/caldwell/build-emacs/blob/master/launch.rb

**Comment by ryanpeach** [comment]
Ok so I don’t think it’s an emacs for Mac issue because I finally got one of my stable Elisp configs running on an M1 emacs I got from brew. Only doom gives me this error.

**Comment by ryanpeach** [comment]
I think it mostly has something to do with running emacs from the command line or from some missing os feature in my terminal.

**Comment by techdiary** [comment]
I was able to install emac-plus and but not able to link emas.app to Applications/. Just like @ryanpeach mentioned [stackexchange ticket](https://apple.stackexchange.com/questions/281267/symlinks-to-executables-in-applications-cannot-run).

**Comment by shroomist** [comment]
my 5c:
1. using emacs from emacs for Mac
2. running `doom install` from terminal in rosetta mode.
3. I had to install `ripgrep` using x86 brew in rosetta, now I see it's available on native brew for silicon.

**Comment by msanders** [comment]
> This appears to be an Emacs issue, rather than a Doom issue. Perhaps this article can help. And I think the emacs-mac formula on homebrew has ARM support for M1 macs, judging from this commit.

I'm successfully running Doom on an M1 using emacs-mac. It just needs to be installed via the formula rather than the cask for a native build. See https://github.com/railwaycat/homebrew-emacsmacport/issues/230#issuecomment-745714414.

**Comment by balloneij** [comment]
I had no trouble installing all my packages, `emacs-plus@28`, `ripgrep`, and `fd`, through `brew install`. Afterwards I was able to follow the normal Doom installation no problem, and I haven't run into any issues yet
