### ISSUE TITLE
Question - SPC+.... functionality

### ISSUE THREAD

**Issue by rsangole** [hlissner/doom-emacs#454]
Hello,

Fantastic work! I'm just getting into emacs (short-medium time VIM user) and have been exploring various installations - spacemacs, [buildfunthings](https://gitlab.com/buildfunthings/emacs-config/blob/master/loader.org), or your setup. I like things from all of these setups, and am inclined to build me own. I'm primarily an R/Python coder and thus I have some special cases I want to customize to.

To that end, the functionality where:
1. We press SPC and the menu pops up at the bottom with shortcuts
2. We start typing in M-x and it gives a continuously reducing list

Are these scripts you've written yourself, or are these packages I can import in a new emacs setup?

Thanks for all your (obsessively delightfully detailed) work!

**Comment by hlissner** [comment]
Thank you! And you're very welcome!

The functionality you've listed are both provided by plugins:

1) The shortcut popup comes from the [which-key](https://github.com/justbur/emacs-which-key) plugin. You'll find Doom's config for it [here in core/core-keybinds.el](https://github.com/hlissner/doom-emacs/blob/develop/core/core-keybinds.el#L46-L57).

2) The completion functionality you see on M-x is provided by a combination of ivy and counsel, both plugins are [housed in the same repository](https://github.com/abo-abo/swiper). Ivy provides the interactive fuzzy searching that you described, and counsel provides more specialized integration with commands where using ivy makes sense (like M-x).

However, the _bare minimum_ you need for this to work is `ivy`:

```elisp
(require 'ivy)
(ivy-mode)
```

And you should get what you see in Doom.

You'll find doom's config for ivy/counsel [in the completion/ivy module](https://github.com/hlissner/doom-emacs/tree/develop/modules/completion/ivy).

Hope that helps!

**Comment by hlissner** [comment]
Oh, I suppose i should mention, if all you want is the interactive fuzzy search in M-x, there's also the  [ido-vertical](https://github.com/creichert/ido-vertical-mode.el) plugin, which is much simpler than ivy.

**Comment by rsangole** [comment]
Super! I'm going to try it out myself. 

Your shortcuts for the todo/notes is also a great addition.

Ok, now I'm questioning if I should even bother trying things out on my own.  😃

**Comment by rsangole** [comment]
On pressing SPC, there is ~2s delay on my laptop. Is that a processing issue, or is that a feature that can be tuned someplace?

**Comment by nealot** [comment]
That is a [which-key](https://github.com/justbur/emacs-which-key) variable. You can set the delay to 0 by placing this in your init.el file: 
`(setq which-key-idle-delay 0)`

**Comment by rsangole** [comment]
@nealot lovely, worked perfectly

**Comment by hlissner** [comment]
Since the original question has been answered, I'll close this, but feel free to use this thread if you have more questions.

(@nealot Thanks for your response!)
