### ISSUE TITLE
Open Doom Emacs as maximized way

### ISSUE THREAD

**Issue by helderburato** [hlissner/doom-emacs#4541]
## Description

I have a doubt about how I can set Emacs to always open as the maximized way I already have [this](https://github.com/helderburato/dotfiles/blob/main/emacs/.doom.d/config.el#L14) on my dotfiles but stay opening such as:
<img width="1680" alt="Screenshot 2021-01-19 at 10 28 41" src="https://user-images.githubusercontent.com/862575/105022014-22e8fa80-5a41-11eb-8e7d-0fe9c617640a.png">

Does anyone have the same problem?

**Comment by drocha87** [comment]
```emacs
(set-frame-parameter (selected-frame) 'fullscreen 'maximized)
(add-to-list 'default-frame-alist '(fullscreen . maximized))
```

To me this piece of code above works perfectly.

**Comment by AloisJanicek** [comment]
There is also `-mm` emacs command line option:
```
 --maximized, -mm                make the first frame maximized
```

**Comment by VIVelev** [comment]
I have the same issue, even after trying all the proposed solutions. I am on macOS too.

**Comment by helderburato** [comment]
I tried the ways mentioned above, but without success.

**Comment by samuelematias** [comment]
> I tried the ways mentioned above, but without success.

Try this (both code together in your config.el):

```el
(set-frame-parameter (selected-frame) 'fullscreen 'maximized)
(add-to-list 'default-frame-alist '(fullscreen . maximized))

(when window-system
  (set-frame-position (selected-frame) 330 88)
  (set-frame-size (selected-frame) 184 54))
```

For me, works.

<img width="1920" alt="Screen Shot 2021-01-20 at 11 28 54" src="https://user-images.githubusercontent.com/5155386/105188532-c1915c00-5b12-11eb-9850-4dfe387fd250.png">

**Comment by VIVelev** [comment]
Hmm @samuelematias that's a pretty peculiar behavior to me.

Nevertheless, I found that simply putting the following in your `config.el` works:
```emacs-lisp
(add-to-list 'default-frame-alist '(fullscreen . maximized))
```

Does it work for you too? @helderburato

**Comment by helderburato** [comment]
> Hmm @samuelematias that's a pretty peculiar behavior to me.
> 
> Nevertheless, I found that simply putting the following in your _config.el_ works:
> 
> ```emacs-lisp
> (add-to-list 'default-frame-alist '(fullscreen . maximized))
> ```
> 
> Does it work for you too? @helderburato
> 
> Seems like something with `selected-frame` is off, which I believe is a doom emacs thing, correct me if I am wrong.
> The solution above is a pure emacs way to change the initial frame size.

It works! Thanks for your help.
