### ISSUE TITLE
Bridge to Matrix

### ISSUE THREAD

**Issue by Evidlo** [hlissner/doom-emacs#4554]
Thanks for the great project.  I've been using Spacemacs for years and Doom is way faster.

I was wondering if you might set up a Matrix room and bridge it into the `#help` channel on the Discord?  I know there's a few individuals that prefer FOSS communication methods over Discord.

[Matrix project website](https://matrix.org)

[Matrix-Discord Bridge](https://t2bot.io/discord/)

**Comment by MithicSpirit** [comment]
I believe the plan is to move to Discourse soon, so this probably won't be necessary.

**Comment by Evidlo** [comment]
Discourse is asynchronous, no?

**Comment by hlissner** [comment]
To quote [our FAQ](https://github.com/hlissner/doom-emacs/blob/develop/docs/faq.org#is-discord-the-only-option-for-interacting-with-your-community):

> Yes. Discord is already woven into my social and work life, and was selected to maximize my availability to the community. I don’t want to juggle multiple platforms (like Matrix, IRC or Slack), or add bridges for them, even if they are better suited to the task. I already have my hands full managing the one.
> 
> I am considering a discourse, so we have a public knowledge base of workflows and inter-user support (since Discord isn’t a great archive), but it will be some time until this is set up.
> 
> Email is a possible alternative, but is constantly swamped; expect a turn-around time of weeks.

I'm sorry, but I have no intention of maintaining additional platforms. I have enough on my plate with the one (and soon, the Discourse).
