### ISSUE TITLE
ace-window fails when initially called from treemacs project sidebar

### ISSUE THREAD

**Issue by jkachmar** [hlissner/doom-emacs#4555]
**What did you expect to happen?**

It should be possible to open a file or directory from the Treemacs project sidebar before using `ace-window` elsewhere within an Emacs session.

**What actually happened?**

On a clean install of Doom with `window-select` and `treemacs` enabled in `init.el`, opening the Treemacs project sidebar and attempting to open the file/directory into a selected window (i.e. `o a a: open ace`) fails with the error `Symbol's value as variable is void: aw-ignored-buffers`.

However, if `ace-window` has been invoked in a window already (e.g. `SPC w C-w`) it will execute successfully both within the window and afterwards within Treemacs for the remainder of that Emacs session.

**Steps to reproduce:**
1. Open a clean Emacs session
2. Navigate to a project and open a Treemacs project sidebar
3. Attempt to open a file/directory in the project via Ace (e.g. `o a a`)
4. Observe the error message `Symbol's value as variable is void: aw-ignored-buffers`
5. Navigate to a non-Treemacs window and invoke `ace-window` (e.g. `SPC w C-w`)
6. Observe that this succeeds, and that `o a a` from within Treemacs should now succeed for the remainder of the session

**System information:**
<details><pre>
```
SYSTEM  type       darwin
        config     x86_64-apple-darwin17.7.0
        shell      /bin/zsh
        uname      Darwin 19.6.0 Darwin Kernel Version 19.6.0: Thu Oct 29 22:56:45 PDT 2020; root:xnu-6153.141.2.2~1/RELEASE_X86_64 x86_64
        path       (~/.nix-profile/bin /run/current-system/sw/bin /nix/var/nix/profiles/default/bin /usr/local/bin /usr/bin /usr/sbin /bin /sbin /nix/store/h3ri6pm9mql15pj2j23g10yzx4hyjg2d-emacs-mac-27.1-8.0/libexec/emacs/27.1/x86_64-apple-darwin17.7.0/)
EMACS   dir        ~/.emacs.d/
        version    27.1
        build      Dec 19, 2020
        buildopts  --prefix=/nix/store/h3ri6pm9mql15pj2j23g10yzx4hyjg2d-emacs-mac-27.1-8.0 LDFLAGS=-L/nix/store/n4pr2i4mnjamhms56063ipl5pz6v48r0-ncurses-6.2/lib --with-xml2=yes --with-gnutls=yes --with-mac --with-modules '--enable-mac-app=$$out/Applications' CFLAGS=-O3
        features   NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS PDUMPER GMP
        traits     (gui server-running envvar-file)
DOOM    dir        ~/.doom.d/
        version    2.0.9
        font       #<font-spec nil nil JetBrains Mono nil nil nil nil nil 14 nil nil nil nil>
        theme      doom-one
        build      grafted, HEAD -> develop, origin/develop, origin/HEAD 2ad1eab 2021-01-18 19:59:18 -0500
        elc-files  0
        modules    (:completion company (ivy +icons +prescient) :ui deft doom doom-dashboard doom-quit (emoji +unicode) fill-column hl-todo hydra ligatures minimap modeline nav-flash ophints (popup +all +defaults) (tabs +centaur-tabs) treemacs unicode vc-gutter vi-tilde-fringe (window-select +numbers) workspaces zen :editor (evil +everywhere) file-templates fold (format +onsave) multiple-cursors rotate-text snippets :emacs dired electric (ibuffer +icons) (undo +tree) vc :term vterm :checkers syntax spell grammar :tools debugger direnv editorconfig (eval +overlay) (lookup +dictionary +docsets) lsp (magit +forge) make pdf rgb upload :os macos tty :lang emacs-lisp haskell json markdown nix (org +pretty +dragndrop +journal +pomodoro +present +roam) purescript python rust sh web (&nopath yam) :app calendar :config (default +bindings +smartparens))
        packages   ((org-super-agenda) (ormolu))
        unpin      (n/a)
        elpa       (vterm emacsql-sqlite emacsql)
```
</pre></details>

**Comment by stratacast** [comment]
Exact same issue here...good thing I have a backup. I'll have to revert back to it

**Comment by Alexander-Miller** [comment]
Problem is not reproducible with treemacs' clean-start or my own config, so it must be doom specific.

Possible culprit is treemacs no longer eagerly requiring ace-window and relying on autoloads instead: https://github.com/Alexander-Miller/treemacs/commit/9b49abf13bf10d1d9095a2d2411ed17201d34c96

**Comment by Dantara** [comment]
The same problem. Manual downgrading of `treemacs` to the last tag (2.8) and rebuilding packages via `doom build` temporary solved the issue.

**Comment by howdoicomputer** [comment]
You can also `(require 'ace-window)` in your `config.el`.
