### ISSUE TITLE
How do I define a path to Doom in WSL2

### ISSUE THREAD

**Issue by sbacelar** [hlissner/doom-emacs#4557]
I have installed Doom-emacs both on Windows 10 and WSL 2 (Ubuntu 20.04) on the same PC.
I have no problem with the path to Doom on Windows 10 version.
But in the WSL2 version when I print the $PATH I see `/home/myname/.emacs.d/bin` but I can't execute any command starting by `doom`. 
When I do for example `doom sync` I get `/usr/bin/env: ‘sh\r’: No such file or directory`.
To obtain the right result I have to do from home `.emacs.d/bin/doom sync`.

**Comment by hlissner** [comment]
Windows and Linux have different line endings. If you clone in cmd.exe, you'll get one style. If you clone in WSL you'll get another. The error you're seeing is `/bin/sh` not understanding how to interpret the line endings of the `bin/doom` script.

You need to convert those line endings. If you don't know how to do that, you're better off re-cloning the doom-emacs repo in WSL2.

**Comment by MithicSpirit** [comment]
I think that your issue may also be that the windows executable is earlier in your path than the WSL one (iirc WSL inherits your Windows path), since running `~/.emacs.d/bin/doom` works, so your should also try changing the order of the items in your path in your `.bashrc`.

**Comment by sbacelar** [comment]
I have recloned doom-emacs in WSL2 but the problem is the same.
I also tried to change the order of the items in my path in `.bashrc` but when I print $PATH "/home/sbac/.emacs.d/bin" keeps coming in the last place and I don't know how to change that order.

**Comment by sbacelar** [comment]
When I do `export PATH=/home/sbac/.emacs.d/bin:$PATH` this item comes first in the $PATH file and `doom sync` works.But I can't keep it constant because even if I put in the `.bashrc` file in first place it doesn't work the same way.

**Comment by sbacelar** [comment]
Good idea @MithicSpirit . Thank you. It finally works!
