### ISSUE TITLE
Doom package management without Doom

### ISSUE THREAD

**Issue by haji-ali** [hlissner/doom-emacs#4560]
**Describe the feature**
I _love_ Doom package management (with modules, autoload feature and the CLI) and want to use it for my emacs init which I want to build from the ground up.

However, I don't want Doom specific configurations (those in `core-ui`, `core-projects`, `core-editor`, `core-keybinds`.. etc) but there doesn't seem to be a way to use Doom without its customizations. It would be great if Doom provides fine control of those configurations like it does of other modules in `init.el`. Perhaps a "doom-core" module that can be selectively removed.

**System information**
<details><pre>```
SYSTEM  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/zsh
        uname      Linux 5.4.0-62-generic #70-Ubuntu SMP Tue Jan 12 12:45:47 UTC 2021 x86_64
        path       (~/perl5/bin ~/.cargo/bin ~/.local/share/texlive//bin/x86_64-linux ~/.local/bin ~/.local/opt/llvm/bin /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /usr/games /usr/local/games /snap/bin ~/.local/libexec/emacs/27.1/x86_64-pc-linux-gnu)
EMACS   dir        ~/Work/Projects/dotfiles/emacs/.emacs.d/
        version    27.1
        build      Sep 14, 2020
        buildopts  --prefix=/home/abdo/.local/ --with-json --with-modules --with-harfbuzz --with-compress-install --with-threads --with-included-regex --with-zlib --with-sound=alsa --without-gconf --with-mailutils --with-xft --with-xml2 --with-cairo --with-gconf --with-xwidgets --without-toolkit-scroll-bars 'CFLAGS=-O3 -mtune=native -march=native -fomit-frame-pointer -I/usr/lib/gcc/x86_64-linux-gnu/9/include/ -L/usr/lib/gcc/x86_64-linux-gnu/9'
        features   XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GCONF GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER LCMS2 GMP
        traits     (gui server-running)
DOOM    dir        ~/Work/Projects/dotfiles/emacs/.config/doom/
        version    2.0.9
        font       #<font-object -DAMA-Ubuntu Mono-normal-normal-normal-*-17-*-*-*-m-0-iso10646-1>
        theme      doom-one
        build      HEAD -> develop 2ad1eab6e 2021-01-18 19:59:18 -0500
        elc-files  0
        modules    (:completion ivy :ui doom hl-todo modeline window-select :emacs dired ibuffer undo :checkers spell :tools magit pdf :os tty :lang emacs-lisp (latex +latexmk) markdown yaml :email mu4e :config literate (default +bindings) :my-apps (&user org) (&user org-agenda) (&user email) (&user dired) (&user latex) (&user shell) (&user magit) :my-completion (&user ivy) :my-emacs (&user wind-mgmt) (&user paren))
        packages   ((hungry-delete) (openwith) (origami) (lsp-origami) (el-patch) (explain-pause-mode :disable t) (selectrum) (focus) (ace-jump-mode) (iedit) (aggressive-indent) (eglot) (flyspell-correct))
        unpin      (n/a)
        elpa       (n/a)
```
</pre></details>

**Comment by cbio-mannyschneck** [comment]
You can remove these modules from your `init.el` and include only your own modules that you have written with doom's management facilities.

**Comment by jeetelongname** [comment]
you can disable any package using the function in your packages.el `(package! PACKAGE :disable t)` this will disable all of the configuration of these packages as well. 

as for disabling core and all of the requisite files. as they are loaded by the init.el you can't feasibly edit them without editing the init.el (which is not recommended). I would recommend first disabling most to all of the modules too see if you get the effect you want but if you find doom still does too much you can read through the source or try to maintain your own fork of doom (This could get messy tho)

**Comment by hlissner** [comment]
Moving much of Doom's core functionality out into modules is planned. So is moving Doom's CLI + package manager to a separate repo. Unfortunately I have a long list of TODOs between then and now, so it'll be some months before I get there, but they won't be forgotten.

Since this issue doesn't present anything immediately actionable, and I'm currently in the process of cleaining up the Github so we use Discourse as our issue tracker, I'll close this, but feel free to follow up here.
