### ISSUE TITLE
colon is display as a flying trashcan on MacOs

### ISSUE THREAD

**Issue by shackra** [hlissner/doom-emacs#4562]
**What did you expect to happen?**
to display `:`

**What actually happened?**
a trashcan is display in its place:

![Captura de Pantalla 2021-01-22 a la(s) 16 50 23](https://user-images.githubusercontent.com/1055216/105557574-3232a700-5cd2-11eb-8ae7-48a6d13711be.png)

**Additional details:**
- my config: https://github.com/shackra/emacs/blob/master/config.org

**System information:**
```
SYSTEM  type       darwin
        config     x86_64-apple-darwin19.5.0
        shell      /bin/zsh
        uname      Darwin 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64
        path       (~/.emacs.d/bin/ ~/.cask/bin ~/.gem/ruby/2.4.0/bin ~/.gem/ruby/2.6.0/bin ~/.emacs.d/bin ~/.local/bin ~/opt/prey-node-client/bin ~/.node_modules/bin ~/go/bin ~/go ~/protoc/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /usr/local/opt/node@14/bin /Library/Apple/usr/bin ~/.zplug/bin /usr/local/Cellar/emacs-plus@27/27.1/libexec/emacs/27.1/x86_64-apple-darwin19.5.0/)
EMACS   dir        ~/.emacs.d/
        version    27.1
        build      Nov 14, 2020
        buildopts  --disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus@27/27.1/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus@27/27.1 --with-xml2 --with-gnutls --without-dbus --with-imagemagick --with-modules --with-rsvg --with-ns --disable-ns-self-contained
        features   RSVG IMAGEMAGICK GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS JSON PDUMPER LCMS2 GMP
        traits     (gui server-running envvar-file)
DOOM    dir        ~/.doom.d/
        version    2.0.9
        font       #<font-spec nil nil Fira Code nil nil nil nil nil 15 nil nil nil nil>
        theme      doom-gruvbox
        build      grafted, HEAD -> develop, origin/develop, origin/HEAD 2ad1eab 2021-01-18 19:59:18 -0500
        elc-files  0
        modules    (:completion (company +childframe) (ivy +childframe +prescient +icons) :ui doom doom-dashboard doom-quit hl-todo hydra (ligatures +fira +extra) modeline nav-flash ophints (popup +defaults) treemacs unicode vc-gutter vi-tilde-fringe window-select workspaces :editor file-templates fold (format +onsave) lispy multiple-cursors snippets :emacs dired electric undo vc :term vterm :checkers syntax (spell +flyspell) grammar :tools (eval +overlay) lookup (lsp +peek) magit pdf :os macos :lang data (dart +flutter) emacs-lisp (gdscript +lsp) (go +lsp) json (javascript +lsp) (latex +lsp) markdown (org +dragndrop +pretty) (python +lsp) (rust +lsp) (sh +lsp) (web +lsp) yaml :config literate (default +bindings +smartparens))
        packages   ((reformatter))
        unpin      (n/a)
        elpa       (n/a)
```

**Comment by haji-ali** [comment]
Probably related to `doom-font` and `doom-big-font` in your [config](https://github.com/shackra/emacs/blob/master/config.org#tipograf%C3%ADa). Maybe try removing this `setq`?

**Comment by MithicSpirit** [comment]
I had this issue using the Fira Code font with ligatures before (which appears to be your case). You need to get a version of the font patched for symbols IIRC.

**Comment by shackra** [comment]
> Probably related to `doom-font` and `doom-big-font` in your [config](https://github.com/shackra/emacs/blob/master/config.org#tipograf%C3%ADa). Maybe try removing this `setq`?

how then do I set the font I want to use or is this done automagically done by Doom?

**Comment by shackra** [comment]
> Probably related to `doom-font` and `doom-big-font` in your [config](https://github.com/shackra/emacs/blob/master/config.org#tipograf%C3%ADa). Maybe try removing this `setq`?

did that, didn't work 🤔

**Comment by shackra** [comment]
> I had this issue using the Fira Code font with ligatures before (which appears to be your case). You need to get a version of the font patched for symbols IIRC.
> EDIT: [found it](https://github.com/tonsky/FiraCode/issues/211#issuecomment-239058632).
> (alternatively, you can also try using Emacs 28/HEAD, which has proper ligature support through Harfbuzz)

Installing the font on that linked issue addressed the issue. Leaving (or removing, for that matter) my `setq` for `doom-font` and `doom-big-font` did nothing to produce the bug.
