### ISSUE TITLE
Buffer is always read-only

### ISSUE THREAD

**Issue by daankata** [hlissner/doom-emacs#4568]
**What actually happened?**
Every time I start Doom it opens only a read-only buffer. When I try to open any file (even a 777 file) it shows me "Note: file is write protected". I need to manually change the buffer with `C-x C-q` every time before opening a file so it isn't read-only. The only thing that fixes this is to start a clean Emacs with `emacs -Q` and then it opens the buffer normally and every file is writable.

**Additional details:**
- Fresh installation of Doom Emacs
- Tested with Emacs 26.3-27.1
- ArchLinux

`doom doctor` returned 3 warnings:
- ! Couldn't find the `fd' binary; project file searches will be slightly slower
- ! Couldn't find a markdown compiler, `markdown-preview' won't work
- ! Couldn't find shellcheck. Shell script linting will not work

**Steps to reproduce:**
1. Delete `.emacs.d` and `.doom`
2. Install with `git clone --depth 1 repo ~/.emacs.d` and `~/.emacs.d/bin/doom install`. The installation does not show any warnings or errors.
3. Start Emacs

The problem could very well be in my system. How could I fix this issue?

Thank you!

**System information:**

```
SYSTEM  type       gnu/linux
	config     x86_64-pc-linux-gnu
	shell      /bin/zsh
	uname      Linux 5.10.9-arch1-1 #1 SMP PREEMPT Tue, 19 Jan 2021 22:06:06 +0000 x86_64
	path       (/usr/local/sbin /usr/local/bin /usr/bin /usr/lib/jvm/default/bin /usr/lib/emacs/27.1/x86_64-pc-linux-gnu)
EMACS   dir        ~/.emacs.d/
	version    27.1
	build      Aug 28, 2020
	buildopts  --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-wide-int --with-modules --with-cairo --with-harfbuzz 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
	features   XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP
	traits     (batch server-running envvar-file)
DOOM    dir        ~/.doom.d/
	version    2.0.9
	build      grafted, HEAD -> develop, origin/develop, origin/HEAD fd70732 2021-01-23 22:37:28 -0500
	elc-files  0
	modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline ophints (popup +defaults) vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold snippets :emacs dired electric undo vc :checkers syntax :tools (eval +overlay) lookup magit :lang emacs-lisp markdown org sh :config (default +bindings +smartparens))
	packages   (n/a)
	unpin      (n/a)
	elpa       (n/a)
```

**Comment by hlissner** [comment]
I cannot reproduce this and is likely caused by an unrelated error. Check the contents of your \*Messages\* log buffer (`SPC h e` or `C-h e` to access it) for warnings or error messages after startup.

**Comment by daankata** [comment]
Thank you very much for the fast reply. The problem was indeed on my system. The problem was related to AppArmor/Firejail which apparently opened every file as read-only. Sorry for the trouble.
