### ISSUE TITLE
:lang clojure: No reader function for tag dbg

### ISSUE THREAD

**Issue by davidh38** [hlissner/doom-emacs#4578]
**What did you expect to happen?**
I start Doom Emacs in Ubuntu 20.04
I open a clojure file.

```
(defn hello-world []
  (str "hello world")
)

(hello-world)

```
I open the REPL with SPC o r
I evaluate the buffer with SPC m e b
I evaluate at point with SPC u SPC m e d at the function call (hello-world)
I expect the debugger to start.

**What actually happened?**
An Exception ocurred:
java.lang.RuntimeException
   No reader function for tag dbg

<details><pre>
3. Unhandled clojure.lang.ExceptionInfo
   (No message)
   {:clojure.error/phase :read-source}
                  main.clj:  433  clojure.main/repl/read-eval-print/fn
                  main.clj:  432  clojure.main/repl/read-eval-print
                  main.clj:  458  clojure.main/repl/fn
                  main.clj:  458  clojure.main/repl
                  main.clj:  368  clojure.main/repl
               RestFn.java: 1523  clojure.lang.RestFn/invoke
    interruptible_eval.clj:   79  nrepl.middleware.interruptible-eval/evaluate
    interruptible_eval.clj:   55  nrepl.middleware.interruptible-eval/evaluate
    interruptible_eval.clj:  142  nrepl.middleware.interruptible-eval/interruptible-eval/fn/fn
                  AFn.java:   22  clojure.lang.AFn/run
               session.clj:  171  nrepl.middleware.session/session-exec/main-loop/fn
               session.clj:  170  nrepl.middleware.session/session-exec/main-loop
                  AFn.java:   22  clojure.lang.AFn/run
               Thread.java:  834  java.lang.Thread/run

2. Caused by clojure.lang.LispReader$ReaderException
   java.lang.RuntimeException: No reader function for tag dbg
   {:clojure.error/line 8, :clojure.error/column 14}
           LispReader.java:  314  clojure.lang.LispReader/read
           LispReader.java:  216  clojure.lang.LispReader/read
           LispReader.java:  205  clojure.lang.LispReader/read
                  core.clj: 3768  clojure.core/read
                  core.clj: 3741  clojure.core/read
    interruptible_eval.clj:   99  nrepl.middleware.interruptible-eval/evaluate/fn
                  main.clj:  433  clojure.main/repl/read-eval-print/fn
                  main.clj:  432  clojure.main/repl/read-eval-print
                  main.clj:  458  clojure.main/repl/fn
                  main.clj:  458  clojure.main/repl
                  main.clj:  368  clojure.main/repl
               RestFn.java: 1523  clojure.lang.RestFn/invoke
    interruptible_eval.clj:   79  nrepl.middleware.interruptible-eval/evaluate
    interruptible_eval.clj:   55  nrepl.middleware.interruptible-eval/evaluate
    interruptible_eval.clj:  142  nrepl.middleware.interruptible-eval/interruptible-eval/fn/fn
                  AFn.java:   22  clojure.lang.AFn/run
               session.clj:  171  nrepl.middleware.session/session-exec/main-loop/fn
               session.clj:  170  nrepl.middleware.session/session-exec/main-loop
                  AFn.java:   22  clojure.lang.AFn/run
               Thread.java:  834  java.lang.Thread/run

1. Caused by java.lang.RuntimeException
   No reader function for tag dbg

**System information:**
<details><pre>
SYSTEM  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /usr/bin/zsh
        uname      Linux 5.8.0-40-generic #45~20.04.1-Ubuntu SMP Fri Jan 15 11:35:04 UTC 2021 x86_64
        path       (~/.nvm/versions/node/v15.0.1/bin ~/.pyenv/bin ~/.nix-profile/bin /nix/var/nix/profiles/default/bin /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /usr/games /usr/local/games /snap/bin ~/bin /opt/multilogin ~/.local/bin /snap/emacs/current/usr/libexec/emacs/27.1/x86_64-pc-linux-gnu/)
EMACS   dir        ~/.emacs.d/
        version    27.1
        build      Nov 30, 2020
        buildopts  --prefix=/snap/emacs/current/usr --with-x-toolkit=gtk3 --without-xaw3d --with-modules --with-cairo 'CFLAGS=-isystem/build/emacs/parts/emacs/install/usr/include -O2' CPPFLAGS=-isystem/build/emacs/parts/emacs/install/usr/include 'LDFLAGS=-L/build/emacs/parts/emacs/install/lib -L/build/emacs/parts/emacs/install/usr/lib -L/build/emacs/parts/emacs/install/lib/x86_64-linux-gnu -L/build/emacs/parts/emacs/install/usr/lib/x86_64-linux-gnu'
        features   XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP
        traits     (gui server-running envvar-file)
DOOM    dir        ~/.doom.d/
        version    2.0.9
        font       #<font-object -PfEd-DejaVu Sans Mono-normal-normal-normal-*-12-*-*-*-m-0-iso10646-1>
        theme      doom-one
        build      HEAD -> develop 91ced7997 2020-12-12 13:49:05 -0500
        elc-files  0
        modules    (:completion (company +tng) ivy :ui deft doom doom-dashboard doom-quit hl-todo indent-guides modeline neotree ophints (popup +defaults) vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold (&nopath t) snippets :emacs dired electric undo vc :term (vterm +tramp) :checkers syntax :tools (debugger +lsp) (eval +overlay) lookup (lsp +peek) magit :lang clojure emacs-lisp javascript markdown (org +dragndrop +hugo +jupyter +roam) (python +lsp +pyright) (ruby +rails) sh :email (mu4e +gmail) :app irc :config (default +bindings +smartparens))
        packages   ((anki-editor) (evil-tutor) (realgud-ipdb) (request))
        unpin      (n/a)
        elpa       (request)
</pre></details>

**Comment by hlissner** [comment]
Has this worked before? Can you reproduce it [in the sandbox](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#testing-in-dooms-sandbox)?

**Comment by davidh38** [comment]
I have never tried it before, but the same problem existed in cider:
https://github.com/clojure-emacs/cider/issues/1218

The problem exist in the sandbox starting doom + modules - private config

**Comment by davidh38** [comment]
I should have read the cider documentation more carefully. The cider debugger was originally written to work with leiningen. In order to make it write either use leiningen or there needs to be some other configuration.
https://docs.cider.mx/cider/index.html
