### ISSUE TITLE
emacs plist indentation break formatting in org-mode src blocks

### ISSUE THREAD

**Issue by andreyorst** [hlissner/doom-emacs#4581]
After change from:
https://github.com/hlissner/doom-emacs/blob/a634e2c8125ed692bb76b2105625fe902b637998/modules/lang/emacs-lisp/autoload.el#L239
to:
https://github.com/hlissner/doom-emacs/blob/b03fdabe4fa8a07a7bd74cd02d9413339a485253/modules/lang/emacs-lisp/autoload.el#L91

Indentation in org mode src blocks began to break upon pressing Enter key. Org mode src blocks are indented by two spaces by default, and when editing those without acutually entering src block with `C-c '` pressing Enter increases indentation by two more spaces. Sometimes. And often pressing pressing enter key puts cursors those two spaces behind needed position. This only happens when editing org mode src blocks with emacs lisp in those as far as I'm concerned.

**Comment by hlissner** [comment]
Please, _please_, do not ignore the issue template. It asks you to:

1. Show what you expected to happen and what actually happened (please include text examples of the errant indentation you're describing).
2. Include precise steps to reproduce the issue, from opening Emacs, to the error occurring.
3. Include your `M-x doom/info` or the output of `bin/doom info`.

**Comment by andreyorst** [comment]
>  1. Show what you expected to happen and what actually happened (please include text examples of the errant indentation you're describing).

Unzip and `command emacs -q -l repro-init.el bug.org` then follow instruction in the file `bug.org`
[bug.zip](https://github.com/hlissner/doom-emacs/files/5899651/bug.zip)

The part of increasing indentation is random as it seems.
 
>  2. Include precise steps to reproduce the issue, from opening Emacs, to the error occurring.

Steps were kinda given, just not as a list.

>  3. Include your `M-x doom/info` or the output of `bin/doom info`.

I don't use DOOM Emacs, just some DOOM goodies from here and there, like a lot of other Emacs users do.

**Comment by hlissner** [comment]
> Unzip and command emacs -q -l repro-init.el bug.org then follow instruction in the file bug.org bug.zip

Excellent work. Thanks for the repro kit!

> I don't use DOOM Emacs, just some DOOM goodies from here and there

Ah, that explains why I couldn't reproduce it. Start with that next time.

What you were missing was `(setq org-src-preserve-indentation t)`, otherwise `org-mode` will never consult `+emacs-lisp-indent-function` (or any major-mode local value for `lisp-indent-function`).

**Comment by andreyorst** [comment]
This variable doesn't make Org consult indent function, Org does it by default, it just preserves leading whitespaces of the code:

```
If non-nil preserve leading whitespace characters on export.

If non-nil leading whitespace characters in source code blocks
are preserved on export, and when switching between the org
buffer and the language mode edit buffer.

When this variable is nil, after editing with ‘M-x org-edit-src-code’,
the minimum (across-lines) number of leading whitespace characters
are removed from all lines, and the code block is uniformly indented
according to the value of ‘org-edit-src-content-indentation’.
```

Which means that code, indented with two spaces by default will keep these spaces in indirect buffer, and if there's no spaces org will not insert additional ones on committing changes from indirect buffer.

Yes, setting this variable fixes the issue, but I now think that this is a bug in org mode, because without this variable, org removes indent when passing information to indent function, which results in indentation not having this two extra spaces added by org. Given that what happens in `emacs -q`:


https://user-images.githubusercontent.com/19470159/106421059-12874580-646d-11eb-95c0-224069acabd7.mp4

I think that this should be reported to Org mode instead. Sorry for the noise here

**Comment by hlissner** [comment]
Perhaps `org-edit-src-content-indentation` is what you want to tweak then (it defaults to `2`).

**Comment by andreyorst** [comment]
FYI I've workaround the issue by adding these two advices:

``` emacs-lisp
(define-advice org-return (:around (f &optional indent arg interactive) aorst:org-return)
  (let ((org-src-preserve-indentation t))
    (funcall f indent arg interactive)))
(define-advice org-cycle (:around (f &optional arg) aorst:org-cycle)
  (let ((org-src-preserve-indentation t))
    (funcall f arg)))
```
