### ISSUE TITLE
mu4e message sending error

### ISSUE THREAD

**Issue by martin3141** [hlissner/doom-emacs#4584]
**What did you expect to happen?**

After composing an e-mail and pressing c-c c-c the message will send, be stored in the sent mail folder and the editor will close.

**What actually happened?**

Message is sent but, the following error appears in the minibuffer:

```
Wrong number of arguments: (lambda (path maildir) “Add the message at PATH to the database.
With MAILDIR set to the maildir this message resides in,
e.g. ‘/drafts’.

 if this works, we will receive (:info add :path <path> : docid
<docid> :fcc <path>).” (mu4e~proc-send-command “cmd:sent path:%s maildir:%s” (mu4e~escape maildir))), 1
```
the message is not moved to sent messages and the editor remains open.

**Additional details:**

Backtrace:

```
Debugger entered--Lisp error: (wrong-number-of-arguments (lambda (path maildir) "Add the message at PATH to the database.\nWith MAIL..." (mu4e~proc-send-command "cmd:sent path:%s maildir:%s" (mu4e~escape path) (mu4e~escape maildir))) 1)
  mu4e~proc-sent("/home/martin/.mail/mailbox/Drafts/cur/1611904356.3f9bfa7c215675f5.x1c:2,DS")
  #f(compiled-function () #<bytecode 0x21939bd>)()
  run-hooks(message-sent-hook)
  message-send(nil)
  message-send-and-exit()
  apply(message-send-and-exit nil)
  org-msg-mua-call(send-and-exit message-send-and-exit)
  org-msg-ctrl-c-ctrl-c()
  run-hook-with-args-until-success(org-msg-ctrl-c-ctrl-c)
  org-ctrl-c-ctrl-c(nil)
  funcall-interactively(org-ctrl-c-ctrl-c nil)
  call-interactively(org-ctrl-c-ctrl-c nil nil)
  command-execute(org-ctrl-c-ctrl-c)
```
I used the same mail config with vanilla emacs and the message sent fine - so seems like a doom specific issues.

**Comment by kcurtet** [comment]
Its a bug related to `org-msg.el`. I think a pull request its already made

**Comment by martin3141** [comment]
`(package! org-msg :disable t)`

seems to be a reasonable workaround for now. Thanks @kcurtet.

**Comment by hlissner** [comment]
#3971 was merged recently, which resolves this issue. Thanks for bringing it to my attention!
