### ISSUE TITLE
C-h in insert-state in org-mode calls org-beginning-of-line

### ISSUE THREAD

**Issue by Janfel** [hlissner/doom-emacs#4589]
**What did you expect to happen?**
Pressing `C-h` in `insert-state` in `org-mode` starts the `C-h` keychord.

**What actually happened?**
Pressing `C-h` in `insert-state` in `org-mode` calls `org-beginning-of-line`.

**Additional details:**
- Reproducible in `M-x doom/sandbox C-c C-p`.

**Steps to reproduce:**
1. `M-x doom/sandbox C-c C-p`
2. Open a new buffer `SPC b N`
3. `M-x org-mode`
4. Enter insert state
5. Press `M-SPC h k C-h` and see `org-beginning-of-line`.

**System information:**
<details><pre>
SYSTEM  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /usr/bin/zsh
        uname      Linux 5.10.7-3-MANJARO #1 SMP PREEMPT Fri Jan 15 21:11:34 UTC 2021 x86_64
        path       (~/bin ~/opt/bin /usr/local/sbin /usr/local/bin /usr/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl ~/.local/bin ~/.dotnet/tools ~/var/go/bin ~/.local/share/cabal/bin ~/opt/ghcup/bin ~/.gem/ruby/2.7.0 ~/.local/share/cargo/bin /usr/lib/emacs/27.1/x86_64-pc-linux-gnu/)
EMACS   dir        ~/opt/doom-emacs/
        version    27.1
        build      Aug 28, 2020
        buildopts  --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-wide-int --with-modules --with-cairo --with-harfbuzz 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
        features   XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP
        traits     (gui server-running envvar-file)
DOOM    dir        ~/.config/doom-emacs/
        version    2.0.9
        font       #<font-spec nil nil Source Code Pro nil nil nil nil nil 13 nil nil nil nil>
        theme      doom-one
        build      HEAD -> develop, origin/develop, origin/HEAD 2ad1eab6e 2021-01-18 19:59:18 -0500
        elc-files  0
        modules    (:completion (company +childframe) ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash neotree ophints (popup +defaults) vc-gutter window-select workspaces :editor (evil +everywhere) file-templates fold (&user fmt +define) rotate-text snippets :emacs dired electric ibuffer undo vc :term vterm :checkers syntax :tools editorconfig (eval +overlay) lookup lsp magit make :lang data emacs-lisp markdown org sh yaml (&user arduino) (&user basic) (cc +lsp) clojure common-lisp elixir (&user fennel) (haskell +dante) latex (lua +moonscript) (python +lsp) (rust +lsp) scheme web :config (&user literate) (default +evil +bindings +smartparens))
        packages   ((meson-mode) (moonscript :pin ac5d35d3a1970db958c687991a1f2c49f7921150 :recipe (:fork (:host github :repo Janfel/moonscript-mode))) (php-mode) (async) (flycheck-clang-tidy) (evil-escape :disable t) (evil-matchit) (form-feed) (highlight-indent-guides) (hungry-delete) (company-quickhelp) (company-jedi))
        unpin      (n/a)
        elpa       (n/a)
</pre></details>

**Comment by ymarco** [comment]
The intended more useful behavior for `C-h` in Org is to move left in table cells. `org-beginning-of-line` is the fallback for when the cursor isn't in a table. (see [the code](https://github.com/hlissner/doom-emacs/blob/develop/modules/lang/org/config.el#L979-L980).)
I don't know if it's possible to to dispatch keymaps in `menu-item`, which is used by `general-predicate-dispatch`, which in turn is used by `cmds!` in the source code, but you can try :)

**Comment by Janfel** [comment]
Thanks for pointing me to the code so I know where to change this. I was confused because `C-h` didn’t appear anywhere in the "Key Bindings" section of `C-h f org-beginning-of-line`.
