### ISSUE TITLE
 Doom Emacs can't find yasnippet - now Magit doesn't work

### ISSUE THREAD

**Issue by squarepegsys** [hlissner/doom-emacs#4597]
**What did you expect to happen?**
After an upgrade to Doom I expect to checking files with Magit use yasnippet (via doom-snippets)

**What actually happened?**
 I try to commit files with  Magit and I get an error

```
hint: Waiting for your editor to close the file...
Waiting for Emacs...
*ERROR*: Cannot open load file: No such file or directory, yasnippet-snippets
error: There was a problem with the editor '/Applications/MacPorts/EmacsMac.app/Contents/MacOS/bin/emacsclient --socket-name=/var/folders/w6/_r897gfx27b3bqj9_zvckvth0000gn/T/emacs501/server68600'.
Please supply the message using either -m or -F option.
```

Also yasnippet it not working

**Additional details:**

My messages:

```
Ignoring ’:ensure t’ in ’easy-kill’ config
Ignoring ’:ensure t’ in ’deft’ config
Doom loaded 214 packages across 40 modules in 2.329s [2 times]
Switched to ’voterinformation3’
Loading /Users/mikeh/.emacs.d/.local/cache/recentf...done
File mode specification error: (file-missing Cannot open load file No such file or directory yasnippet-snippets)
Saving file /Users/mikeh/Projects/voterinformation3/tester.py...
Wrote /Users/mikeh/Projects/voterinformation3/tester.py
Mark set
user-error: Already staged [2 times]
Running /opt/local/bin/git commit --
File mode specification error: (file-missing Cannot open load file No such file or directory yasnippet-snippets)
Failed to load yasnippet package incrementally, because: (file-missing Cannot open load file No such file or directory yasnippet-snippets)
There was a problem with the editor '/Applications/MacPorts/EmacsMac.app/Contents/MacOS/bin/emacsclient --socket-name=/var/folders/w6/_r897gfx27b3bqj9_zvckvth0000gn/T/emacs501/server68600'. ... [Hit $ to see buffer magit-process: voterinformation3 for details]
Mark set
```

**Steps to reproduce:**
1. Start Emacs
2. To go Project via Projectile
3. open Magit
4. commit files
5.  See above

**System information:**

<details><pre>
Doom info:
      build      Nov 12, 2020
        buildopts  --prefix=/opt/local --with-mac --enable-mac-app=/Applications/MacPorts --with-modules --without-rsvg --without-imagemagick --without-harfbuzz --with-json 'CFLAGS=-pipe -Os -fobjc-arc -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -arch x86_64' 'CPPFLAGS=-I/opt/local/include -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk' 'LDFLAGS=-L/opt/local/lib -Wl,-headerpad_max_install_names -Wl,-syslibroot,/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -arch x86_64'
        features   DBUS NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS JSON PDUMPER LCMS2 GMP
        traits     (gui server-running envvar-file)
DOOM    dir        ~/.doom.d/
        version    2.0.9
        font       #<font-spec nil nil IBM Plex Mono nil iso10646-1 nil normal normal 13 nil 100 0 ((:user-spec . IBM Plex Mono))>
        theme      doom-one
        build      HEAD -> develop 56e9d273e 2021-01-28 21:23:07 -0500
        elc-files  0
        modules    (:completion company helm :ui deft doom doom-dashboard doom-quit modeline nav-flash ophints (popup +defaults) tabs vc-gutter vi-tilde-fringe workspaces :editor file-templates fold rotate-text snippets :emacs dired electric undo vc :term vterm :checkers syntax :tools direnv editorconfig (eval +overlay) lookup lsp magit tmux :lang emacs-lisp (go +lsp) markdown (org +roam +journal +notes) (python +lsp +blacken) rest sh (yaml +lsp) :config (default +bindings +smartparens))
        packages   <(file-missing "Cannot open load file" "No such file or directory" "yasnippet-snippets")>
        unpin      <(file-missing "Cannot open load file" "No such file or directory" "yasnippet-snippets")>
        elpa       (transient todoist s ripgrep multiple-cursors json-sn

Emacs info:
GNU Emacs 27.1 (build 1, x86_64-apple-darwin18.7.0, Carbon Version 158 AppKit 1671.6)
 of 2020-11-12
(install via macport with port install emacs-app
</pre></details>

**Comment by squarepegsys** [comment]
I am 100% sure if we can figure out what yasnippet folder got delete (or is just missing) this would Just Work(tm)

**Comment by hlissner** [comment]
Did you install `yasnippet-snippets` with `(package! yasnippet-snippets)` in `~/.doom.d/packages.el`, then run `doom sync`?

If you used `M-x package-install`, you didn't read [the documentation on package management in Doom](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#package-management). Run `doom purge` to clean up ELPA packages first.

**Comment by squarepegsys** [comment]
Well this worked for months but I removed the lines about yasnipet after doing a doom purge (I don't remember how I installed it... seriously, it's been months) and now it works.
