### ISSUE TITLE
setting doom-font with font-spec doesn't work with emacs-native

### ISSUE THREAD

**Issue by dradetsky** [hlissner/doom-emacs#4601]
**What did you expect to happen?**

Since I was able to use
```
(setq doom-font (font-spec :family "gohufont" :size 14))
```
to set my font with emacs 27.1, I expected this to continue to work with the pgtk/native build, version 28.0.50.

More specifically, 28.0.50.146652-1, off of aur/emacs-pgtk-native-comp-git

**What actually happened?**

error

```
Font ‘-*-gohufont-*-*-*-*-14-*-*-*-*-*-*-*’ is not defined
```

**Additional details:**

I was able to work around this by changing it to
```
(setq doom-font "Gohu GohuFont:pixelsize=14")
```
So this isn't super high-priority

The backtrace doesn't seem very helpful, but:

```
Debugger entered--Lisp error: (error "Font ‘-*-gohufont-*-*-*-*-14-*-*-*-*-*-*-*’ is not...")
  frame-notice-user-settings()
  #f(compiled-function () #<bytecode 0x125c510e5f7ae6dc>)()
  normal-top-level()
```

**Comment by hlissner** [comment]
This means it can't find the font. `Gohu` or `gohufont` are likely not the correct names. Use `fc-list | grep gohu` to look up it's real name.

**Comment by dradetsky** [comment]
`counsel-fonts` produces `Gohu GohuFont`. And replacing with

```
(setq doom-font
      (font-spec :family "Gohu GohuFont" :size 14))
```
worked. thanks
