### ISSUE TITLE
Buffer switching is broken

### ISSUE THREAD

**Issue by fredrikatmainspringenergy** [hlissner/doom-emacs#4607]
**What did you expect to happen?**
In emacs mode:

Given an open file buffer (a "real" buffer)
When I split buffer with `C-x 3`
Then a new buffer is open with the content of the original buffer
When I switch to the new buffer with `C-x o`
Then I move to the new buffer
When I switch to the original buffer with `C-x o`
Then I move to the original buffer

**What actually happened?**

Given an open file buffer (a "real" buffer)
When I split buffer with `C-x 3`
Then a new buffer is open with the content of the original buffer
When I switch to the new buffer with `C-x o`
Then I move to the new buffer
When I switch to the original buffer with `C-x o`
Then I REMAIN IN THE NEW buffer

**Additional details:**
- Include a link to your private config
https://github.com/fredrikatmainspringenergy/doom-emacs-config.git

- Include screenshots/casts of your issue
n/a

- If you mention key sequences, include what commands they're bound to (use `SPC
  h k KEY` or `C-h h k KEY` to inspect keys).

`C-h h` is undefined

- Include any warnings or errors logged to \*Messages\* (use `M-x
  view-echo-area-messages` to see it).

```
No other window to select
```

<details><pre>
If an error message is involved include a backtrace of it.

How to acquire a backtrace:
https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#how-to-extract-a-backtrace-from-an-error
</pre></details>

```
Debug on Error enabled globally
You can run the command ‘toggle-debug-on-error’ with M-x t-er RET
Debug on Error enabled globally
No other window to select
Updating buffer list...done
Commands: m, u, t, RET, g, k, S, D, Q; q to quit; h for help
Mark set
```

**Steps to reproduce:**
1. Select these example steps,

C-x 3 ; split a "real" buffer
C-x o ; move to the new buffer
C-x o ; move back to the original buffer (this fails)

2. Delete them,

C-x C-b ; get list of buffers 
Arrows + Enter ; select the original buffer
C-x 1 ; just this buffer

3. And replace them with precise steps to reproduce your issue.

C-x 3 ; split the "real" buffer
C-x o ; move to the new buffer
C-x o ; move back to the original buffer (this fails)

4. Fill in "system information" below.

**System information:**
<details><pre>
Place the output of `M-x doom/info` or `~/.emacs.d/bin/doom info` here.
</pre></details>

 ```
 SYSTEM  type       gnu/linux
         config     x86_64-pc-linux-gnu
         shell      /bin/zsh
         uname      Linux 5.4.0-1037-aws #39~18.04.1-Ubuntu SMP Fri Jan 15 02:48:42 UTC 2021 x86_64
         path       (~/.emacs.d/bin ~/go/bin /usr/local/go/bin . /snap/bin /usr/local/opt/gnu-getopt/bin /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /usr/games /usr/local/games /snap/bin /snap/emacs/current/usr/libexec/emacs/27.1/x86_6$
 EMACS   dir        ~/.emacs.d/
         version    27.1
         build      Nov 30, 2020
         buildopts  --prefix=/snap/emacs/current/usr --with-x-toolkit=gtk3 --without-xaw3d --with-modules --with-cairo 'CFLAGS=-isystem/build/emacs/parts/emacs/install/usr/include -O2' CPPFLAGS=-isystem/build/emacs/parts/emacs/install/usr/include 'LDFL$
         features   XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 G$
         traits     (tty envvar-file)
 DOOM    dir        ~/.doom.d/
         version    2.0.9
         font       nil
         theme      doom-one
         build      grafted, HEAD -> develop, origin/develop, origin/HEAD 3a7be7b 2021-02-01 02:45:45 -0500
         elc-files  0
         modules    (:completion company ido :ui doom doom-dashboard doom-quit hl-todo modeline ophints (popup +defaults) vc-gutter vi-tilde-fringe workspaces :editor file-templates fold snippets :emacs dired electric undo vc :checkers syntax :tools (e$
         packages   (n/a)
         unpin      (n/a)
         elpa       (n/a)
 ```

**Comment by fredrikatmainspringenergy** [comment]
Could this be related to that I open files (not necessarily this particular file) from an "unreal" buffer (ie, `*compilation*`)?

Would a workaround be to disable the "real/unreal" buffer feature? (if possible)

**Comment by hlissner** [comment]
The instructions are unclear. What do you mean by "move" in "move to the new buffer", and what do you mean by "new buffer"? Please show exact key sequences.

**Comment by fredrikatmainspringenergy** [comment]
"move to the new buffer" => change the buffer that has the cursor / switch to the new buffer ... so that text I type goes into the new buffer.

The exact key sequences is provided in the "Steps to reproduce".
