### ISSUE TITLE
(package! :ignore t) doesn't seem to be working

### ISSUE THREAD

**Issue by hexane360** [hlissner/doom-emacs#4608]
**What did you expect to happen?**
I'm trying to work on a local copy of a package, `julia-mode`. However, I can't seem to get doom to not install its own version. I started by purging the package from `.emacs.d/.local/straight`, and then put the following in `packages.el`:

```elisp
(package! julia-mode :ignore t)
(add-load-path! "develop/julia-emacs")
```

I expect this to suppress doom's installation of `julia-mode`.

**What actually happened?**
However, instead, `doom sync` just reinstalls the packages:
```
> Synchronizing your config with Doom Emacs...
  > Installing packages...
    -> Cloning julia-emacs (for julia-mode)...
    -> Cloning julia-emacs (for julia-mode)...done
    -> Building julia-mode...
    -> Building julia-mode...done
    âo" Installed 1 packages
  > (Re)building packages...
    âo" No packages need rebuilding
  > Purging orphaned packages (for the emperor)...
    - No builds to purge
    - Skipping elpa packages
    - Skipping repos
    - Skipping regrafting
  > (Re)generating autoloads file...
    > Generating autoloads file...
    > Byte-compiling autoloads file...
    âo" Generated .local/autoloads.26.2.elc
  - Restart Emacs or use 'M-x doom/reload' for changes to take effect
```

Using `:local-repo` seems to work, with the downside that I need to `doom sync` every time I make changes.

**Steps to reproduce:**
1. Get a fresh install of doom emacs
2. Purge julia-mode from `.emacs.d/.local/straight/`
2. Add `(package! julia-mode :ignore t)` to `packages.el`
3. `doom sync`

**System information:**
```
> doom info
SYSTEM  type       windows-nt
        config     x86_64-w64-mingw32
        shell      C:/Program Files/emacs/libexec/emacs/26.2/x86_64-w64-mingw32/cmdproxy.exe
        uname      n/a
EMACS   dir        ~/.emacs.doom/
        version    26.2
        build      Apr 13, 2019
        buildopts  --without-dbus --host=x86_64-w64-mingw32 --without-compress-install 'CFLAGS=-O2 -static -g3'
        features   XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2
        traits     (batch)
DOOM    dir        ~/.doom.d/
        version    2.0.9
        build      HEAD -> develop f622d5171 2020-12-01 18:09:43 -0500
        elc-files  0
        modules    (:completion company ivy :ui doom hl-todo modeline ophints (popup +defaults) treemacs unicode vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold snippets :emacs dired electric ibuffer undo vc :term vterm :checkers syntax spell :tools (eval +overlay) lookup lsp magit :lang cc data emacs-lisp (go +lsp) json javascript (julia +lsp) latex markdown org (python +lsp) rst (ruby +rails) (rust +lsp) sh yaml :config (default +bindings))
        packages   ((spacemacs-theme) (base16-theme) (jupyter) (lsp-mode :recipe (:host github :repo emacs-lsp/lsp-mode) :pin 4db1151dbf1fe84769433d841e90803448b0b354) (lsp-julia :recipe (:host github :repo non-jedi/lsp-julia)) (smart-tabs-mode))
        unpin      (n/a)
        elpa       (coverlay)
```

**Comment by hlissner** [comment]
Use this instead:

```lisp
(package! julia-mode :recipe (:local-repo "develop/julia-emacs" :no-byte-compile t))
```

`:ignore` isn't quite functioning correctly atm and am working on a larger fix in #4273.

**Comment by hexane360** [comment]
Thanks for the quick response. Is there any easy way to develop with that, such that I don't need to constantly sync between the local repo and the one in `~/emacs.d/.local/straight`?

**Comment by hlissner** [comment]
> Thanks for the quick response. Is there any easy way to develop with that, such that I don't need to constantly sync between the local repo and the one in `~/emacs.d/.local/straight`?

`straight` recently removed the `:no-byte-compile` parameter, so it no longer inhibiting byte-compilation (thus forcing you to `doom sync` every time you change the package. I've updated the original snippet above to use the new `:build` parameter. Use that to fix your issue.

**Comment by hlissner** [comment]
I will close this since it is being tracked in #4273.
