### ISSUE TITLE
"Save as" command works incorrectly with projectile

### ISSUE THREAD

**Issue by akamaus** [hlissner/doom-emacs#4611]
**What did you expect to happen?**
Saving a buffer under new name in a directory of a project should make it part of the current project.

**What actually happened?**
Invoking `write-file` command (with SPC f S by default) allows you to save a buffer under a new name. Unfortunately, this file is not indexed by projectile and remains invisible e.g. for `projectile-find-file` (SPC SPC)

**Steps to reproduce:**
1. Create a new project
2. Create a new file in it. (Make sure it's a part of a project with SPC-SPC)
3. Save it under a new name with SPC f S
4. Change something inside it, just to be sure, save with :w
5. Observe file if missing from list shown by SPC-SPC.

**System information:**
<details><pre>
```
SYSTEM  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/zsh
        uname      Linux 4.15.0-108-generic #109-Ubuntu SMP Fri Jun 19 11:33:10 UTC 2020 x86_64
        path       (~/venvs/tb1.8/bin ~/.nix-profile/bin /nix/var/nix/profiles/default/bin ~/remote/tools ~/.local/bin /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /usr/games /usr/local/games /nix/store/505vc08hq9yl4b3i4cddq0ia2q509vxa-emacs-27.1/libexec/emacs/27.1/x86_64-pc-linux-gnu/)
EMACS   dir        ~/.emacs.d/
        version    27.1
        build      Feb 04, 2021
        buildopts  --prefix=/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-emacs-27.1 --disable-build-details --with-modules --with-x-toolkit=gtk3 --with-xft --with-cairo CFLAGS=-DMAC_OS_X_VERSION_MAX_ALLOWED=101200
        features   XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND DBUS GSETTINGS GLIB NOTIFY INOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER GMP
        traits     (gui server-running envvar-file)
DOOM    dir        ~/.doom.d/
        version    2.0.9
        font       #<font-object -PfEd-DejaVu Sans Mono-normal-normal-normal-*-13-*-*-*-m-0-iso10646-1>
        theme      doom-one
        build      HEAD -> develop, origin/develop, origin/HEAD b03fdab 2021-01-13 14:07:47 -0500
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo minimap modeline ophints (popup +defaults) treemacs vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold snippets :emacs dired electric undo vc :checkers syntax :tools (eval +overlay) lookup lsp magit :lang emacs-lisp markdown org (python +lsp +pyvenv) sh :config (default +bindings +smartparens))
        packages   (n/a)
        unpin      (n/a)
        elpa       (n/a)
```
</pre></details>

**Comment by hlissner** [comment]
There are two incorrect assumptions here.

1. `write-file` writes a file to another file, but it doesn't open the file. Projectile won't recognize a new file until you open it.
2. `projectile-find-file` is cached. Run `SPC p i` (`projectile-invalidate-cache`) or `SPC u` immediately before `SPC SPC` to invalid the cache.

Here are some alternatives:

1. If you want to change the name of the current file "in place", then use `SPC f R` (`doom/move-this-file`) or the `:mv NEWNAME` ex command. It handles 
2. If you want to copy the current file to a new one, use `SPC f C` (`doom/copy-this-file`) or the `:cp NEWNAME` ex command.
3. If you find projectile's caching too annoying, then I recommend `(setq projectile-files-cache-expire 10)`. The cache will expire relatively frequently, without impacting its performance when used consecutively by projectile or Doom's internals.

Both 1 and 2 will refresh projectile's cache for you (also magit's and vc's).

Hope that helps!
