### ISSUE TITLE
Starting eshell produces: Symbol's value as variable is void: eshell-modules-list 

### ISSUE THREAD

**Issue by jgoerzen** [hlissner/doom-emacs#4616]
**What did you expect to happen?**

I ran M-x eshell RET, and I expected eshell to start.

**What actually happened?**

Just got this error.  I tried a `doom upgrade` and now it's worse; can't even open org files; I get:

Error in a Doom startup hook: global-git-commit-mode, (void-variable eshell-modules-list)

I ran `rm .local/autoloads.26.1.el` 

**Additional details:**

I have eshell uncommented in the :term section of ~/.doom.d/init.el. 

<details><pre>
Debugger entered--Lisp error: (void-variable eshell-modules-list)
  (member 'eshell-tramp eshell-modules-list)
  (if (member 'eshell-tramp eshell-modules-list) eshell-modules-list (setq eshell-modules-list (cons 'eshell-tramp eshell-modules-list)))
  (if (featurep 'esh-module) (if (member 'eshell-tramp eshell-modules-list) eshell-modules-list (setq eshell-modules-list (cons 'eshell-tramp eshell-modules-list))) (eval-after-load 'esh-module (function (lambda nil (if (member 'eshell-tramp eshell-modules-list) eshell-modules-list (setq eshell-modules-list (cons 'eshell-tramp eshell-modules-list)))))))
  (progn (if (featurep 'esh-module) (if (member 'eshell-tramp eshell-modules-list) eshell-modules-list (setq eshell-modules-list (cons 'eshell-tramp eshell-modules-list))) (eval-after-load 'esh-module (function (lambda nil (if (member 'eshell-tramp eshell-modules-list) eshell-modules-list (setq eshell-modules-list (cons 'eshell-tramp eshell-modules-list))))))))
  (progn (setq eshell-banner-message '(format "%s %s\n" (propertize (format " %s " (string-trim (buffer-name))) 'face 'mode-line-highlight) (propertize (current-time-string) 'face 'font-lock-keyword-face)) eshell-scroll-to-bottom-on-input 'all eshell-scroll-to-bottom-on-output 'all eshell-kill-processes-on-exit t eshell-hist-ignoredups t eshell-input-filter (function (lambda (input) (not (string-match-p "\\`\\s-+" input)))) eshell-prompt-regexp "^.* λ " eshell-prompt-function (function +eshell-default-prompt-fn) eshell-glob-case-insensitive t eshell-error-if-no-glob t) (add-hook 'eshell-mode-hook (function doom-mark-buffer-as-real-h)) (add-hook 'eshell-mode-hook (function +eshell-init-h)) (add-hook 'eshell-exit-hook (function +eshell-cleanup-h)) (add-hook 'eshell-mode-hook (function smartparens-mode)) (if nil (progn (add-hook 'persp-activated-functions (function +eshell-switch-workspace-fn)) (add-hook 'persp-before-switch-functions (function +eshell-save-workspace-fn)))) (progn (defalias '+eshell-remove-fringes-h (function (lambda nil (set-window-fringes nil 0 0) (set-window-margins nil 1 nil)))) (defalias '+eshell-enable-text-wrapping-h (function (lambda nil (visual-line-mode 1) (set-display-table-slot standard-display-table 0 32)))) (add-hook 'eshell-mode-hook (function +eshell-enable-text-wrapping-h) nil nil) (add-hook 'eshell-mode-hook (function +eshell-remove-fringes-h) nil nil)) (add-hook 'eshell-mode-hook (function hide-mode-line-mode)) (advice-add (function eshell-write-aliases-list) :override (function ignore)) (progn (if (featurep 'esh-module) (if (member 'eshell-tramp eshell-modules-list) eshell-modules-list (setq eshell-modules-list (cons 'eshell-tramp eshell-modules-list))) (eval-after-load 'esh-module (function (lambda nil (if (member 'eshell-tramp eshell-modules-list) eshell-modules-list (setq eshell-modules-list (cons 'eshell-tramp eshell-modules-list)))))))) (progn (if (featurep 'em-term) (let ((--dolist-tail-- (list "tmux" "htop" "vim" "nvim" "ncmpcpp"))) (while --dolist-tail-- (let ((result (car --dolist-tail--))) (setq eshell-visual-commands (if (member result eshell-visual-commands) eshell-visual-commands (cons result eshell-visual-commands))) (setq --dolist-tail-- (cdr --dolist-tail--)))) (with-no-warnings eshell-visual-commands)) (eval-after-load 'em-term (function (lambda nil (let ((--dolist-tail-- (list "tmux" "htop" "vim" "nvim" "ncmpcpp"))) (while --dolist-tail-- (let ((result (car --dolist-tail--))) (setq eshell-visual-commands (if (member result eshell-visual-commands) eshell-visual-commands (cons result eshell-visual-commands))) (setq --dolist-tail-- (cdr --dolist-tail--)))) (with-no-warnings eshell-visual-commands))))))) (progn (if (featurep 'em-alias) (setq +eshell--default-aliases eshell-command-aliases-list eshell-command-aliases-list (append eshell-command-aliases-list +eshell-aliases)) (eval-after-load 'em-alias (function (lambda nil (setq +eshell--default-aliases eshell-command-aliases-list eshell-command-aliases-list (append eshell-command-aliases-list +eshell-aliases))))))))
  (closure (t) nil (progn (setq eshell-banner-message '(format "%s %s\n" (propertize (format " %s " (string-trim (buffer-name))) 'face 'mode-line-highlight) (propertize (current-time-string) 'face 'font-lock-keyword-face)) eshell-scroll-to-bottom-on-input 'all eshell-scroll-to-bottom-on-output 'all eshell-kill-processes-on-exit t eshell-hist-ignoredups t eshell-input-filter (function (lambda (input) (not (string-match-p "\\`\\s-+" input)))) eshell-prompt-regexp "^.* λ " eshell-prompt-function (function +eshell-default-prompt-fn) eshell-glob-case-insensitive t eshell-error-if-no-glob t) (add-hook 'eshell-mode-hook (function doom-mark-buffer-as-real-h)) (add-hook 'eshell-mode-hook (function +eshell-init-h)) (add-hook 'eshell-exit-hook (function +eshell-cleanup-h)) (add-hook 'eshell-mode-hook (function smartparens-mode)) (if nil (progn (add-hook 'persp-activated-functions (function +eshell-switch-workspace-fn)) (add-hook 'persp-before-switch-functions (function +eshell-save-workspace-fn)))) (progn (defalias '+eshell-remove-fringes-h (function (lambda nil (set-window-fringes nil 0 0) (set-window-margins nil 1 nil)))) (defalias '+eshell-enable-text-wrapping-h (function (lambda nil (visual-line-mode 1) (set-display-table-slot standard-display-table 0 32)))) (add-hook 'eshell-mode-hook (function +eshell-enable-text-wrapping-h) nil nil) (add-hook 'eshell-mode-hook (function +eshell-remove-fringes-h) nil nil)) (add-hook 'eshell-mode-hook (function hide-mode-line-mode)) (advice-add (function eshell-write-aliases-list) :override (function ignore)) (progn (if (featurep 'esh-module) (if (member 'eshell-tramp eshell-modules-list) eshell-modules-list (setq eshell-modules-list (cons 'eshell-tramp eshell-modules-list))) (eval-after-load 'esh-module (function (lambda nil (if (member 'eshell-tramp eshell-modules-list) eshell-modules-list (setq eshell-modules-list (cons 'eshell-tramp eshell-modules-list)))))))) (progn (if (featurep 'em-term) (let ((--dolist-tail-- (list "tmux" "htop" "vim" "nvim" "ncmpcpp"))) (while --dolist-tail-- (let ((result (car --dolist-tail--))) (setq eshell-visual-commands (if (member result eshell-visual-commands) eshell-visual-commands (cons result eshell-visual-commands))) (setq --dolist-tail-- (cdr --dolist-tail--)))) (with-no-warnings eshell-visual-commands)) (eval-after-load 'em-term (function (lambda nil (let ((--dolist-tail-- (list "tmux" "htop" "vim" "nvim" "ncmpcpp"))) (while --dolist-tail-- (let ((result (car --dolist-tail--))) (setq eshell-visual-commands (if (member result eshell-visual-commands) eshell-visual-commands (cons result eshell-visual-commands))) (setq --dolist-tail-- (cdr --dolist-tail--)))) (with-no-warnings eshell-visual-commands))))))) (progn (if (featurep 'em-alias) (setq +eshell--default-aliases eshell-command-aliases-list eshell-command-aliases-list (append eshell-command-aliases-list +eshell-aliases)) (eval-after-load 'em-alias (function (lambda nil (setq +eshell--default-aliases eshell-command-aliases-list eshell-command-aliases-list (append eshell-command-aliases-list +eshell-aliases)))))))))()
  eval-after-load-helper("/usr/share/emacs/26.1/lisp/eshell/eshell.elc")
  run-hook-with-args(eval-after-load-helper "/usr/share/emacs/26.1/lisp/eshell/eshell.elc")
  do-after-load-evaluation("/usr/share/emacs/26.1/lisp/eshell/eshell.elc")
  require(eshell)
  byte-code("\300\301!\210\302\303!\210\302\304!\210\305\306\307\310\311\312\313\303&\007\210\314\315\307\316#\210\317\320\321\322\323DD\324\325\326\313\306&\007\210\317\327\321\322\330DD\331\325\332\333\311\334E\335\336\337\335\340\341\306!\"\342\"\"\343#\313\306&\007\207" [provide esh-module require eshell esh-util custom-declare-group eshell-module nil "The `eshell-module' group is for Eshell extension modules, which\nprovide optional behavior which the user can enable or disable by\ncustomizing the variable `eshell-modules-list'." :tag "Extension modules" :group load "esh-groups" nomessage custom-declare-variable eshell-module-unload-hook funcall function #f(compiled-function () #<bytecode 0x12d9ad5>) "A hook run when `eshell-module' is unloaded." :type hook eshell-modules-list #f(compiled-function () #<bytecode 0x12d9ae5>) "A list of optional add-on modules to be loaded by Eshell.\nChanges will only take effect in future Eshell buffers." append set "Supported modules" mapcar #f(compiled-function (modname) #<bytecode 0x12d9b0d>) sort symbol-name eshell-subgroups string-lessp ((repeat :inline t :tag "Other modules" symbol))] 14)
  require(esh-module)
  byte-code("\300\301!\210\302\303!\210\302\304!\210\302\305!\210\302\306!\210\302\307!\210\310\311\312\313\314\315\316\317&\007\210\320\321\322\323\324DD\325\326\327\316\311&\007\210\320\330\322\323\331DD\332\326\327\316\311&\007\210\320\333\322\323\334DD\335\326\327\316\311&\007\210\320\336\322\323\337DD\340\341\342\326\327\316\311&\011\210\320\343\322\323\344DD\345\326\346\316\311&\007\210\320\347\322\323\350DD\351\326\327\316\311&\007\210\320\352\322\323\353DD\354\326\346\316\311&\007\210\320\355\322\323\356DD\357\326\327\316\311&\007\210\320\360\322\323\361DD\362\326\363\316\311&\007\210\320\364\322\323\365DD\366\326\367\316\311&\007\210\320\370\322\323\371DD\372\326\346\316\311&\007\210\320\373\322\323\374DD\375\326\376\316\311&\007\210\320\377\322\323\201@\0\ DD\201A\0\326\327\316\311&\007\210\320\201B\0\322\323\201C\0\ DD\201D\0\326\327\316\311&\007\210\320\201E\0\322\323\201F\0\ DD\201G\0\326\201H\0\316\311&\007\210\320\201I\0\322\323\201J\0\ DD\201K\0\326\201L\0\316\311&\007\210\201M\0\201N\0\201O\0\312#\210\201P\0\211\203i\001\211@\201N\0\001N\203b\001\201O\0\001N\204b\001\201Q\0\201O\0\002\201N\0\004N#\210\001A\266\202\202>\001\210\201R\0\201N\0\201O\0\201S\0#\210\320\201O\0\322\323\201T\0\ DD\201U\0\326\346\316\311&\007\207" [provide esh-mode require esh-util esh-module esh-cmd esh-io esh-var custom-declare-group eshell-mode nil "This module contains code for handling input from the user." :tag "User interface" :group eshell custom-declare-variable eshell-mode-unload-hook funcall function #f(compiled-function () #<bytecode 0x1b4b3ed>) "A hook that gets run when `eshell-mode' is unloaded." :type hook eshell-mode-hook #f(compiled-function () #<bytecode 0x1b4b3fd>) "A hook that gets run when `eshell-mode' is entered." eshell-first-time-mode-hook #f(compiled-function () #<bytecode 0x1b4b40d>) "A hook that gets run the first time `eshell-mode' is entered.\nThat is to say, the first time during an Emacs session." eshell-exit-hook #f(compiled-function () #<bytecode 0x1b4b41d>) "A hook that is run whenever `eshell' is exited.\nThis hook is only run if exiting actually kills the buffer." :version "24.1" eshell-kill-on-exit #f(compiled-function () #<bytecode 0x1b4b42d>) "If non-nil, kill the Eshell buffer on the `exit' command.\nOtherwise, the buffer will simply be buried." boolean eshell-input-filter-functions #f(compiled-function () #<bytecode 0x1b4b43d>) "Functions to call before input is processed.\nThe input is contained in the region from `eshell-last-input-start' to\n`eshell-last-input-end'." eshell-send-direct-to-subprocesses #f(compiled-function () #<bytecode 0x1b4b44d>) "If t, send any input immediately to a subprocess." eshell-expand-input-functions #f(compiled-function () #<bytecode 0x1b4b45d>) "Functions to call before input is parsed.\nEach function is passed two arguments, which bounds the region of the\ncurrent input text." eshell-scroll-to-bottom-on-input #f(compiled-function () #<bytecode 0x1b4b46d>) "Controls whether input to interpreter causes window to scroll.\nIf nil, then do not scroll.  If t or `all', scroll all windows showing\nbuffer.  If `this', scroll only the selected window.\n\nSee `eshell-preinput-scroll-to-bottom'." (radio (const :tag "Do not scroll Eshell windows" nil) (const :tag "Scroll all windows showing the buffer" all) (const :tag "Scroll only the selected window" this)) eshell-scroll-to-bottom-on-output #f(compiled-function () #<bytecode 0x1b4b47d>) "Controls whether interpreter output causes window to scroll.\nIf nil, then do not scroll.  If t or `all', scroll all windows showing\nbuffer.  If `this', scroll only the selected window.  If `others',\nscroll only those that are not the selected window.\n\nSee variable `eshell-scroll-show-maximum-output' and function\n`eshell-postoutput-scroll-to-bottom'." (radio (const :tag "Do not scroll Eshell windows" nil) (const :tag "Scroll all windows showing the buffer" all) (const :tag "Scroll only the selected window" this) (const :tag "Scroll all windows other than selected" others)) eshell-scroll-show-maximum-output #f(compiled-function () #<bytecode 0x1b4b48d>) "Controls how interpreter output causes window to scroll.\nIf non-nil, then show the maximum output when the window is scrolled.\n\nSee variable `eshell-scroll-to-bottom-on-output' and function\n`eshell-postoutput-scroll-to-bottom'." eshell-buffer-maximum-lines #f(compiled-function () #<bytecode 0x1b4b49d>) "The maximum size in lines for eshell buffers.\nEshell buffers are truncated from the top to be no greater than this\nnumber, if the function `eshell-truncate-buffer' is on\n`eshell-output-filter-functions'." integer eshell-output-filter-functions #f(compiled-function () #<bytecode 0x1b4b4ad>) "Functions to call before output is displayed.\nThese functions are only called for output that is displayed\ninteractively, and not for output which is redirected." eshell-preoutput-filter-functions #f(compiled-function () #<bytecode 0x1b4b4bd>) "Functions to call before output is inserted into the buffer.\nThese functions get one argument, a string containing the text to be\ninserted.  They return the string as it should be inserted." eshell-password-prompt-regexp #f(compiled-function () #<bytecode 0x1b4b4d5>) "Regexp matching prompts for passwords in the inferior process.\nThis is used by `eshell-watch-for-password-prompt'." regexp eshell-skip-prompt-function #f(compiled-function () #<bytecode 0x1b4b4e5>) "A function called from beginning of line to skip the prompt." (choice (const nil) function) defvaralias eshell-status-in-modeline eshell-status-in-mode-line (saved-value saved-variable-comment) put make-obsolete-variable "24.3" #f(compiled-function () #<bytecode 0x1b4b4f5>) "If non-nil, let the user know a command is running in the mode line."] 10)
  require(esh-mode)
  byte-code("\300\301!\210\300\302!\210\303\304\305\306\307\310\311\312\313\314&\011\207" [require esh-util esh-mode custom-declare-group eshell nil "Command shell implemented entirely in Emacs Lisp.\nIt invokes no external processes beyond those requested by the\nuser, and is intended to be a functional replacement for command\nshells such as bash, zsh, rc, 4dos." :link (info-link "(eshell)Top") :version "21.1" :group applications] 10)
  require(eshell nil t)
  (progn (require 'dired nil t) (require 'eshell nil t) (require 'term nil t) (condition-case err (require 'vterm nil t) (error (message "Error(vterm): %S" err))) (require 'warnings nil t))
  (progn (progn (require 'dired nil t) (require 'eshell nil t) (require 'term nil t) (condition-case err (require 'vterm nil t) (error (message "Error(vterm): %S" err))) (require 'warnings nil t)))
  eval((progn (progn (require 'dired nil t) (require 'eshell nil t) (require 'term nil t) (condition-case err (require 'vterm nil t) (error (message "Error(vterm): %S" err))) (require 'warnings nil t))) t)
  #f(compiled-function (&rest body) "Like `progn', but evaluates the body at compile time if you're compiling.\nThus, the result of the body appears to the compiler as a quoted\nconstant.  In interpreted code, this is entirely equivalent to\n`progn', except that the value of the expression may be (but is\nnot necessarily) computed at load time if eager macro expansion\nis enabled." #<bytecode 0x1a1c1f>)((progn (require 'dired nil t) (require 'eshell nil t) (require 'term nil t) (condition-case err (require 'vterm nil t) (error (message "Error(vterm): %S" err))) (require 'warnings nil t)))
  (eval-when-compile (progn (require 'dired nil t) (require 'eshell nil t) (require 'term nil t) (condition-case err (require 'vterm nil t) (error (message "Error(vterm): %S" err))) (require 'warnings nil t)))
  eval-buffer(#<buffer  *load*> nil "/home/jgoerzen/.emacs.d/.local/straight/build-26.1/with-editor/with-editor.el" nil t)  ; Reading at buffer position 3991
  load-with-code-conversion("/home/jgoerzen/.emacs.d/.local/straight/build-26.1/with-editor/with-editor.el" "/home/jgoerzen/.emacs.d/.local/straight/build-26.1/with-editor/with-editor.el" nil t)
  require(with-editor)
  byte-code("\300\301!\210\300\302!\210\300\303\304\305#\210\300\306\304\305#\210\300\307!\210\300\310!\210\300\311!\210\300\312!\210\300\313!\210\314\315\304\316\317\320\321\322\323\324&\011\210\325\326\327\330\331DD\332\333\334\335\336\323\315\337\340&\013\207" [require dash log-edit magit-git nil t magit-utils ring rx server transient with-editor custom-declare-group git-commit "Edit Git commit messages." :prefix "git-commit-" :link (info-link "(magit)Editing Commit Messages") :group tools custom-declare-variable global-git-commit-mode funcall function #f(compiled-function () #<bytecode 0x12f45c5>) "Non-nil if Global Git-Commit mode is enabled.\nSee the `global-git-commit-mode' command\nfor a description of this minor mode.\nSetting this variable directly does not take effect;\neither customize it (see the info node `Easy Customization')\nor call the function `global-git-commit-mode'." :set custom-set-minor-mode :initialize #f(compiled-function (symbol exp) #<bytecode 0x12f45dd>) :type boolean] 12)
  global-git-commit-mode()
  funcall(global-git-commit-mode)
  (condition-case e (funcall hook) ((debug error) (signal 'doom-hook-error (list hook e))))
  doom-try-run-hook(global-git-commit-mode)
  run-hook-wrapped(doom-try-run-hook global-git-commit-mode)
  (progn (run-hook-wrapped hook-var (function doom-try-run-hook)) (set hook-var nil))
  (if after-init-time (progn (run-hook-wrapped hook-var (function doom-try-run-hook)) (set hook-var nil)))
  doom-first-file-hook-h(t t)
  apply(doom-first-file-hook-h (t t))
  after-find-file(t t)
  find-file-noselect-1(#<buffer foo.org> "/tmp/foo.org" nil nil "/tmp/foo.org" nil)
  find-file-noselect("/tmp/foo.org" nil nil nil)
  find-file("/tmp/foo.org")
  (cond ((and counsel-find-file-speedup-remote (file-remote-p ivy--directory)) (let ((find-file-hook nil)) (find-file (expand-file-name x ivy--directory)))) ((member (file-name-extension x) counsel-find-file-extern-extensions) (counsel-find-file-extern x)) (t (find-file (expand-file-name x ivy--directory))))
  counsel-find-file-action("/tmp/foo.org")
  ivy-call()
  ivy-read("Find file: " read-file-name-internal :matcher counsel--find-file-matcher :initial-input nil :action counsel-find-file-action :preselect nil :require-match confirm-after-completion :history file-name-history :keymap (keymap (remap keymap (undo . counsel-find-file-undo)) (67108960 lambda (&optional arg) "nil (`nil')" (interactive "p") (if (string= "" ivy-text) (execute-kbd-macro (kbd "M-o b")) (self-insert-command arg))) (96 . counsel-file-jump-from-find) (C-backspace . counsel-up-directory) (67108991 . counsel-up-directory)) :caller counsel-find-file)
  (let ((default-directory (if (eq major-mode 'dired-mode) (dired-current-directory) default-directory))) (ivy-read prompt (function read-file-name-internal) :matcher (function counsel--find-file-matcher) :initial-input initial-input :action action :preselect (counsel--preselect-file) :require-match 'confirm-after-completion :history 'file-name-history :keymap counsel-find-file-map :caller caller))
  counsel--find-file-1("Find file: " nil counsel-find-file-action counsel-find-file)
  counsel-find-file()
  funcall-interactively(counsel-find-file)
  call-interactively(counsel-find-file nil nil)
  command-execute(counsel-find-file)

</pre></details>

**Steps to reproduce:**
Just open any .org file with the current doom, or attempt to launch eshell with the older one.

**Workaround**
Adding `(setq eshell-modules-list (list))` to config.el at least allows org-mode to work again.  But now, trying to launch eshell says `Invalid function: pcomplete-here`.

**System information:**
<details><pre>
```
SYSTEM  type       gnu/linux
	config     x86_64-pc-linux-gnu
	shell      /bin/bash
	uname      Linux 5.9.0-0.bpo.5-amd64 #1 SMP Debian 5.9.15-1~bpo10+1 (2020-12-31) x86_64
	path       (~/.cargo/bin /usr/local/bin /usr/bin /bin /usr/local/games /usr/games ~/bin /usr/lib/emacs/26.1/x86_64-linux-gnu)
EMACS   dir        ~/.emacs.d/
	version    26.1
	build      Sep 22, 2019
	buildopts  --build x86_64-linux-gnu --prefix=/usr --sharedstatedir=/var/lib --libexecdir=/usr/lib --localstatedir=/var/lib --infodir=/usr/share/info --mandir=/usr/share/man --enable-libsystemd --with-pop=yes --enable-locallisppath=/etc/emacs:/usr/local/share/emacs/26.1/site-lisp:/usr/local/share/emacs/site-lisp:/usr/share/emacs/26.1/site-lisp:/usr/share/emacs/site-lisp --with-sound=alsa --without-gconf --with-mailutils --build x86_64-linux-gnu --prefix=/usr --sharedstatedir=/var/lib --libexecdir=/usr/lib --localstatedir=/var/lib --infodir=/usr/share/info --mandir=/usr/share/man --enable-libsystemd --with-pop=yes --enable-locallisppath=/etc/emacs:/usr/local/share/emacs/26.1/site-lisp:/usr/local/share/emacs/site-lisp:/usr/share/emacs/26.1/site-lisp:/usr/share/emacs/site-lisp --with-sound=alsa --without-gconf --with-mailutils --with-x=yes --with-x-toolkit=gtk3 --with-toolkit-scroll-bars 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/emacs-StqULU/emacs-26.1+1=. -fstack-protector-strong -Wformat -Werror=format-security -Wall' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' LDFLAGS=-Wl,-z,relro
	features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 THREADS LIBSYSTEMD LCMS2
	traits     (batch server-running)
DOOM    dir        ~/.doom.d/
	version    2.0.9
	build      HEAD -> develop d62c82ddb 2021-02-04 07:41:54 -0500
	elc-files  0
	modules    (:completion company (ivy +fuzzy) :ui deft doom doom-dashboard hl-todo modeline ophints (popup +defaults) vc-gutter vi-tilde-fringe :editor (evil +everywhere) file-templates fold multiple-cursors snippets :emacs dired electric undo vc :term eshell shell term :checkers syntax spell :tools (eval +overlay) (lookup +dictionary +offline) lsp (magit +forge) make pdf :lang cc data emacs-lisp json latex markdown (org +roam +journal) (rust +lsp) sh yaml :email mu4e :config literate (default +bindings +smartparens))
	packages   ((mu4e-maildirs-extension) (org-roam-server) (evil-tutor) (inform-mode) (bbdb) (org-msg :disable t))
	unpin      (n/a)
	elpa       (use-package undo-tree spinner org-bullets goto-chg evil diminish bind-key)
```

</pre></details>

**Comment by hlissner** [comment]
Upgrade to Emacs 26.3 at least. Doom doesn't support 26.2 or earlier. In fact, I recommend upgrading to 27.1 as we'll be dropping support in the next few months.

**Comment by jgoerzen** [comment]
Ouch.   I can understand the hassle of maintaining for older version... but I, and all my systems, are on what's available in Debian stable.  I did see the warning from bin/doom about 27.1 becoming required but it didn't complain about 26.1.

**Comment by hlissner** [comment]
Sorry about that! Eshell, especially, has undergone many changes across 26.1, 26.3, 27.1 and onwards, so it's been a real pain to support. The `eshell-modules-list` error can be worked around with:

```elisp
(defvar eshell-modules-list 
  '(eshell-alias
    eshell-banner
    eshell-basic
    eshell-cmpl
    eshell-dirs
    eshell-glob
    eshell-hist
    eshell-ls
    eshell-pred
    eshell-prompt
    eshell-script
    eshell-term
    eshell-unix))
```

But the `pcomplete-here` I'm not sure about. I don't have 26.1 handy to test on, but I assume it isn't present in 26.1, however, there are many packages (org, nix-mode, eshell-z, fish-completion, erc, etc) that use it. Try [producing a backtrace from the error](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#how-to-extract-a-backtrace-from-an-error), it may tell you more about where it's being called from, then that package could [be disabled](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#disabling-packages).
