### ISSUE TITLE
How do I enable Jenkins mode

### ISSUE THREAD

**Issue by helderburato** [hlissner/doom-emacs#4617]
I was reading the `init.el` if has the commented option to `jenkins`.

And, if the https://github.com/john2x/jenkinsfile-mode is the best option to use Jenkinsfiles.

**Comment by notarock** [comment]
It seems like you are asking how to get syntax highlight for a jenkinsfile, [which appears to be groovy](https://www.jenkins.io/doc/book/pipeline/jenkinsfile/). I think what you are looking for is `groovy-mode`, which gets installed by the the [java module](https://github.com/hlissner/doom-emacs/tree/develop/modules/lang/java). Have you tried uncommenting the `java` module in `init.el`?

**Comment by helderburato** [comment]
Thanks, @notarock! It worked.
