### ISSUE TITLE
TypeScript language server crashing just after opening a file

### ISSUE THREAD

**Issue by g-belmonte** [hlissner/doom-emacs#4619]
**What did you expect to happen?**

I expected to open a TS/JS file and work on it normally.

**What actually happened?**

Whenever I open a TS/JS file, after a few seconds I receive the following message:
![image](https://user-images.githubusercontent.com/27803734/107073230-dd108e00-67c5-11eb-991a-a2d3ec6bb67a.png)
This happens at least once every minute. After a few crashes, then this message starts to pop up too:
![image](https://user-images.githubusercontent.com/27803734/107073408-1a751b80-67c6-11eb-960a-a5b157f42f48.png)

I use Doom Emacs with LSP on other languages without any problems. This only happens in TS/JS.

**Additional details:**
- Include a link to your private config: https://github.com/g-belmonte/configs/tree/master/.doom.d
- Include any warnings or errors logged to \*Messages\* (use `M-x
  view-echo-area-messages` to see it).:
  
![image](https://user-images.githubusercontent.com/27803734/107074616-bc493800-67c7-11eb-9864-c0da0d4eee3a.png)

If an error message is involved include a backtrace of it:
![image](https://user-images.githubusercontent.com/27803734/107074938-32e63580-67c8-11eb-84bb-98f3dc58eb4e.png)
The "ts-ls exited with status exit" message doesn't leave any backtrace.

**Steps to reproduce:**
1. Open a project
2. Open a TypeScript file
3. Wait a few seconds

**System information:**
<details><pre>
```
SYSTEM  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/zsh
        uname      Linux 5.10.10-arch1-1 #1 SMP PREEMPT Sat, 23 Jan 2021 23:59:48 +0000 x86_64
        path       (~/.nix-profile/bin ~/.nix-profile/bin /nix/var/nix/profiles/default/bin /usr/local/bin /usr/local/sbin /usr/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl ~/.local/bin ~/go/bin ~/.gem/ruby/2.7.0/bin ~/.npm_globals/bin ~/.fzf/bin /usr/lib/emacs/27.1/x86_64-pc-linux-gnu/)
EMACS   dir        ~/.emacs.d/
        version    27.1
        build      ago 28, 2020
        buildopts  --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-wide-int --with-modules --with-cairo --with-harfbuzz 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
        features   XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP
        traits     (gui server-running envvar-file)
DOOM    dir        ~/.doom.d/
        version    2.0.9
        font       #<font-spec nil nil Source Code Pro nil nil nil nil nil 14 nil nil nil nil>
        theme      doom-one
        build      HEAD -> develop 3a7be7bb 2021-02-01 02:45:45 -0500
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard hl-todo minimap modeline nav-flash ophints (popup +all +defaults) treemacs unicode vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold multiple-cursors rotate-text snippets :emacs (dired +ranger +icons) electric undo (ibuffer +icons) vc :term eshell vterm :checkers syntax (spell +aspell) :tools (debugger +lsp) (docker +lsp) (eval +overlay) lookup (lsp +peek) magit :lang (cc +lsp) common-lisp data (elixir +lsp) (elm +lsp) emacs-lisp (erlang +lsp) (go +lsp) (haskell +lsp) (json +lsp) (javascript +lsp) markdown nix (org +gnuplot +pretty +present) (purescript +lsp) rest (rust +lsp) (sh +lsp) web (yaml +lsp) :config (default +bindings +smartparens))
        packages   (n/a)
        unpin      (n/a)
        elpa       (n/a)
```

</pre></details>

If there is anything else I could do to give more details on this issue, please let me know!

**Comment by vikigenius** [comment]
Try unpinning the `lsp-mode` package and then upgrade doom with `doom sync -u`

**Comment by g-belmonte** [comment]
@vikigenius what do you mean by unpinning the package?

One thing I tried was to I remove the `+lsp` from `javascript` on `config.el`. The code completion gets way better (faster and shows type information in TypeScript) and it does not crash, but then there is no LSP functionality, like `lsp-rename` or `lsp-format-buffer`. Can I somehow get LSP without its crapy code-completion too? :sweat_smile:

**Comment by vikigenius** [comment]
https://github.com/hlissner/doom-emacs/blob/c3c001ad7ded36216682c8cd6ece90734e89f8a0/docs/getting_started.org#pinning-packages-to-specific-commits

If you are on emacs 27, lsp code completion for JS/TS is actually pretty fast. But if you don't want to use lsp doom has inbuilt ways for buffer formatting on save at least using something like prettier.

**Comment by g-belmonte** [comment]
ok, I added `(unpin! (:tools lsp))` to `packages.el`, updated lsp-mode and lsp-ui, then I opened my project and after a few seconds I had the same crash I was having before, and no code completion. Then I had the brilliant idea of hitting `C-Space` to see the autocomplete box, and the fans of my computer are going crazy, just like as if my pc was trying to fly... 5 minutes and counting :joy:

**Comment by g-belmonte** [comment]
got tired of waiting, hit `C-g` and got this message again:
![image](https://user-images.githubusercontent.com/27803734/107099383-44433800-67f0-11eb-8215-eb63c1c68346.png)

**Comment by g-belmonte** [comment]
Just as a follow up, on the [lsp-mode site](https://emacs-lsp.github.io/lsp-mode/) we can see two backends for JavaScript/TypeScript:
- [javascript-typescript-langserver](https://emacs-lsp.github.io/lsp-mode/page/lsp-typescript-javascript/) (project has been archived)
- [typescript-language-server](https://emacs-lsp.github.io/lsp-mode/page/lsp-typescript/)

Since the first has been archived in favor of the second, I installed and tried to use the second - and I was having a bunch of issues. A few days ago I got curious and installed the first one, and suddenly everything started to work as expected.

Now I got a question: is it possible to configure the JS/TS backend for lsp? I was looking at the variables (`SPC h v`) and I couldn't find anything meaningful to tweak, nor could I find a hint for that [on the config files](https://github.com/hlissner/doom-emacs/tree/develop/modules/lang/javascript).

**Comment by hlissner** [comment]
Is this still an issue? I cannot reproduce any issues with either LSP server.

>  is it possible to configure the JS/TS backend for lsp? 

Yes. [Check out lsp-mode's docs](https://emacs-lsp.github.io/lsp-mode/page/adding-new-language/).

**Comment by g-belmonte** [comment]
To be honest I had the problem in my personal computer, and I've been using my work computer with VSCode for all JS/TS related things lately.

I just tested in my work computer and everything seems fine. I'll test later today in my personal computer and see what happens. If everything is ok, then I'll close the issue.

@hlissner thanks for your time!

**Comment by g-belmonte** [comment]
Everything seems to be working fine in my personal computer too. Closing this issue.
