### ISSUE TITLE
`SPC X` refile bug

### ISSUE THREAD

**Issue by xarthurx** [hlissner/doom-emacs#462]
Hi, just doc here in case this bug was missed in the discussion channel.

when refile an entry from `org-capture` using `SPC X`, the modeline asks the files has been modified and should I kill it.

**Comment by AloisJanicek** [comment]
I worked around this by advising `org-refile` function like this:  
``` elisp
  ;; Autsave org buffers after refile
  (advice-add 'org-refile :after
              (lambda (&rest _)
                (org-save-all-org-buffers)))
```
(note: maybe also `org-capture-refile` needs this advice too, I don't remember exactly now)
