### ISSUE TITLE
clangd instead of ccls?

### ISSUE THREAD

**Issue by ergpopler** [hlissner/doom-emacs#4628]
Hello, I cannot figure out how to use clangd autocompletion instead of the ccls one, can anyone point me in the right direction.

**Comment by innerout** [comment]
In the documentation of the cc module, you can see how to [setuo clangd](https://github.com/hlissner/doom-emacs/tree/develop/modules/lang/cc#lsp-mode-with-clangd). The last line sets the priority of the lsp server, if you copy the code block in your config it should set clangd as the default server.
