### ISSUE TITLE
Default install failure WRT org packages

### ISSUE THREAD

**Issue by jwintz** [hlissner/doom-emacs#463]
Hi @hlissner,

Emacs poweruser, Doom newbie, dropping my ten years custom `emacs.d` in favor of your _awesome_ work. Just starting out. FYI, the first steps provides the following error:

```bash
No unused packages to remove
Looking for packages to install...
7 packages will be installed:

+ centered-window-mode (ELPA)
+ help-fns+ (ELPA)
+ ob-mongo (ELPA)
+ ob-redis (ELPA)
+ ob-translate (ELPA)
+ ox-pandoc (ELPA)
+ ox-reveal (ELPA)

Proceed? (y or n) y
Refreshing package archives
Contacting host: elpa.gnu.org:443
Contacting host: melpa.org:443
Package refresh done
Installing ox-reveal
  FATAL ERROR: (error) Package ‘org-20150330’ is unavailable
Installing centered-window-mode
  FATAL ERROR: (error) Package ‘centered-window-mode-’ is unavailable
Installing ox-pandoc
  FATAL ERROR: (error) Package ‘org-8.2’ is unavailable
Installing ob-translate
  FATAL ERROR: (error) Package ‘org-8’ is unavailable
Installing ob-redis
  FATAL ERROR: (error) Package ‘ob-redis-’ is unavailable
Installing ob-mongo
  FATAL ERROR: (error) Package ‘org-8’ is unavailable
Installing help-fns+
  FATAL ERROR: (error) Package ‘help-fns+-’ is unavailable
Finished!
Reloading active Emacs session...
```

Where are `org-*` package supposed to be fetched from ?

**Comment by jwintz** [comment]
Trying `develop` branch. See https://github.com/hlissner/emacs-doom-themes/issues/147.

**Comment by jwintz** [comment]
Switching from `master` to `develop`:

```bash
Looking for orphaned packages...
12 packages will be deleted:

+ company-ghc (ELPA)
+ counsel-css (QUELPA->ELPA)
+ dumb-jump (ELPA)
+ eldoc-eval (ELPA)
+ ghc (ELPA)
+ ghub (ELPA)
+ git-commit (ELPA)
+ ivy-xref (ELPA)
+ magit (ELPA)
+ magit-popup (ELPA)
+ ob-restclient (ELPA)
+ xref-js2 (ELPA)
```

There is no way I want `magit` removed. So I'll try with a fresh clone, on the `develop` branch.

1. Setup init.el
2. Remove `evil` feature
3. make
4. Find out where and how to setup leader key and what it means

**Comment by jwintz** [comment]
Love the new fallback mechanism to .doom.do.

Mush easier to keep its additions & overrides in the same repo !

**Comment by hlissner** [comment]
> There is no way I want magit removed
You'll need to re-copy `init.example.el`. Magit has been moved to the `tools/magit` module.

**Comment by jwintz** [comment]
Did that, with the fresh clone. Makefile is building. So far so good :-)

**Comment by jwintz** [comment]
Ow, but is commented out by default. What a surprise. I'll have to rebuild.

**Comment by jwintz** [comment]
Proceeding. Just wondering if beside `which-key`, there is a way to discover keybindings.

Usually, after a `M-x neotree`, Emacs used to give message including the shortcut.

**Comment by jwintz** [comment]
`org` stuff works just fine in `develop`.

**Comment by hlissner** [comment]
> Just wondering if beside which-key, there is a way to discover keybindings.

There are two other ways. If you have `:completion ivy` enabled, `M-x` will list commands with (one of) their keybindings next to them.

Otherwise, if you know the command, `SPC h f doom/escape` (for instance) will invoke `helpful-function`, which lists all keys it is bound to in a "Key Bindings" section.

But mainly, I'd suggest looking at `modules/config/default/+bindings.el` for a complete view of most of Doom's keybindings.

**Comment by jwintz** [comment]
Many thanks ! BTW, the develop branch works like a charm.

Tomorrow, I'll start my very own customisations as suggested in the Wiki pages.

Why isn't the startup buffer persistent ?

**Comment by hlissner** [comment]
No problem! [Hop on discord](https://discord.gg/bcZ6P3y) if you need any help. There are a few minor discrepancies between wiki and the `develop` branch.

**Comment by jwintz** [comment]
Awesome, thanks for the invite. Doom is getting more and more polished and famous, very excited about that.
