### ISSUE TITLE
Doom Invitation not accepted

### ISSUE THREAD

**Issue by Subcomediante** [hlissner/doom-emacs#4632]
**What did you expect to happen?**
Be permitted to join Doom Emacs Discord.

I note that this issue came up in 2019 [https://github.com/hlissner/doom-emacs/issues/1884](url), but the hypothesized solution (logging into one's browser) has not worked for me with Chrome. I've been logged in while trying this. 

**What actually happened?**
I clicked the link for Doom Emacs Discord server which took me to a Discord page with a pop-up  containing a link to "Accept Invite." Using Chrome, I clicked on the link to accept the invite and another pop-up appears saying, "Whoops. Unable to accept invite." With Safari following the same steps, Safari delivers and error message (see attached), saying that it can't open the specified address because MacOS doesn't recognize addresses starting with "discord." 

I've tried this on two machines and two different browsers on each machine. Same result.

**Additional details:**
- Include a link to your private config
- Include screenshots/casts of your issue
- If you mention key sequences, include what commands they're bound to (use `SPC
  h k KEY` or `C-h h k KEY` to inspect keys).
- Include any warnings or errors logged to \*Messages\* (use `M-x
  view-echo-area-messages` to see it).

<details><pre>
If an error message is involved include a backtrace of it.

How to acquire a backtrace:
https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#how-to-extract-a-backtrace-from-an-error
</pre></details>

**Steps to reproduce:**
1. Click on Discord Server link [https://discord.gg/qvGgnVx](url) in Doom Emacs Documentation [https://github.com/hlissner/doom-emacs/blob/develop/docs/index.org#community-resources](url).
2. Click on "Accept Invite" on the Discord Doom Emacs landing page.

**System information:**
<details><pre>
Place the output of `M-x doom/info` or `~/.emacs.d/bin/doom info` here.
</pre></details>

**Comment by hlissner** [comment]
Sounds like an issue with your network? Your DNS servers or ISP? The discord invite is still valid (it has no expiry date), and we have users signing up every day, so there's no issue there. Perhaps the discord servers were down for a brief window? It may resolve itself in a couple hours.

**Comment by Subcomediante** [comment]
I'm in now. Thank you very much. What worked, I guess, was opening the link in another tab.
