### ISSUE TITLE
parinfer-mode has been deprecated

### ISSUE THREAD

**Issue by johanthoren** [hlissner/doom-emacs#4635]
[parinfer-mode](https://github.com/DogLooksGood/parinfer-mode) has been deprecated and will no longer be updated by the author. Consider moving to [parinfer-rust](https://github.com/eraserhd/parinfer-rust) and [parinfer-rust-mode](https://github.com/justinbarclay/parinfer-rust-mode) which is recommended by the author of parinfer-mode.

From the author:

> Deprecated
This project is no longer maintained. I have no success for a fast enough implementation in Emacs Lisp.
Fortunately, there’s a parinfer-rust-mode!

**Comment by gagbo** [comment]
Note: parinfer-rust-mode _needs_ dynamic modules compiled in, as the name suggests

**Comment by hlissner** [comment]
Is it a drop-in replacement? If so, I'm open to silently activating it if the library + dynamic module support are available, but still keep `parinfer-mode` as a fallback. Otherwise, I'd rather hide it behind a flag.

That said, I use neither, so it'll be some time until I get around to this, so PRs welcome!

**Comment by johanthoren** [comment]
> Is it a drop-in replacement? If so, I'm open to silently activating it if the library + dynamic module support are available, but still keep `parinfer-mode` as a fallback. Otherwise, I'd rather hide it behind a flag.
It's similar alright, but it's not a pure drop-in replacement. It defaults to 'smart-mode', which I don't think was ever implemented in parinfer-mode.

If hiding it behind a flag, should that flag be '+rust'?

**Comment by hlissner** [comment]
> If hiding it behind a flag, should that flag be '+rust'?

That makes sense to me, yeah.

**Comment by johanthoren** [comment]
I'm trying out the following in config.el:
```emacs-lisp
(if (featurep! +rust)
    (use-package! parinfer-rust-mode
      :hook ((emacs-lisp-mode
              clojure-mode
              scheme-mode
              lisp-mode
              racket-mode
              hy-mode) . parinfer-rust-mode)
      :init
      (setq! parinfer-rust-library (concat user-emacs-directory
                                          ".local/etc/parinfer-rust/"
                                          parinfer-rust--lib-name))
      :config
      (map! :map parinfer-rust-mode-map
            :localleader
            :desc "Switch parinfer-rust-mode" "m" #'parinfer-rust-switch-mode
            :desc "Temporarily disable parinfer-rust-mode" "M"
                  #'parinfer-rust-switch-mode))
  (use-package! parinfer
    :hook ((emacs-lisp-mode
            clojure-mode
            scheme-mode
            lisp-mode
            racket-mode
            hy-mode) . parinfer-mode)
    :init
    (setq parinfer-extensions
          '(defaults
            pretty-parens
            smart-tab
            smart-yank))
    (when (featurep! :editor evil +everywhere)
      (push 'evil parinfer-extensions))
    :config
    (map! :map parinfer-mode-map
          "\"" nil  ; smartparens handles this
          :i "<tab>"     #'parinfer-smart-tab:dwim-right-or-complete
          :i "<backtab>" #'parinfer-smart-tab:dwim-left
          :localleader
          :desc "Toggle parinfer-mode" "m" #'parinfer-toggle-mode)))

```
And this in packages.el:
```emacs-lisp
(if (featurep! +rust)
    (package! parinfer-rust-mode :pin "67eed38129c28f087c0b5dffe8a790978d41a8c1")
  (package! parinfer :pin "8659c99a9475ee34af683fdf8f272728c6bebb3a"))
```
But when parinfer-rust-mode is downloading the library, it still gets put in `~/.emacs.d/parinfer-rust` and not `~/.emacs.d/.local/etc/parinfer-rust`. I inspect the variable `parinfer-rust-library`and it's set to `/home/user/.emacs.d/parinfer-rust/parinfer-rust-linux.so`. Why is the variable set in config.el not respected?

I've also posted a question in https://github.com/justinbarclay/parinfer-rust-mode/issues/35.

**Comment by johanthoren** [comment]
@justinbarclay has confirmed that the above was caused by a bug or an unexpected behavior. This integration will have to wait until it has been resolved.

**Comment by johanthoren** [comment]
@justinbarclay has merged a fix to the above problem and it is now part of `parinfer-rust-mode`. I've opened #4671 to include this through the module flag `+rust`.

Thanks @justinbarclay for quickly dealing with this.

**Comment by hackeryarn** [comment]
It might be a good idea to make this a full replacement for `parinfer`. I recently started getting the error from https://github.com/hlissner/doom-emacs/issues/4323. Changing load order doesn't seem to have any effect, and the error causes other issues as well. 

For example, with Common Lisp, the connection does not start automatically. I have to run `M-x sly` manually to get a connect going. After starting the connection, when I switch files/packages `sly-mode` does not activate in the new file. If I activate it manually, with `M-x sly-mode`, it only partially work. I don't get `eldoc` at the bottom as I type, and some forms like `with-` macros don't get formatted correctly.

After disabling `parinfer`, everything  works as expected with `sly`.

**Comment by montchr** [comment]
I've also started getting the error described in #4323. Currently, this happens every time I use the default `SPC c f` binding to call `+format/region-or-buffer`.

**Comment by hlissner** [comment]
Looks like parinfer was removed from melpa and emacsmirror (though it's in the [attic](https://github.com/emacsattic/parinfer)). Should we continue supporting it? If so, we'll need to provide a full `:recipe` for it.

> For example, with Common Lisp, the connection does not start automatically. I have to run M-x sly manually to get a connect going. After starting the connection, when I switch files/packages sly-mode does not activate in the new file. If I activate it manually, with M-x sly-mode, it only partially work. I don't get eldoc at the bottom as I type, and some forms like with- macros don't get formatted correctly.

Not sure how this is related to this post, but you're likely seeing an error at startup. Check \*Messages\*. If this is not the case, create a new issue please.

> I've also started getting the error described in #4323. Currently, this happens every time I use the default SPC c f binding to call +format/region-or-buffer.

Please don't cross post. This belongs in #4323.

**Comment by johanthoren** [comment]
I think it would be better do decommission parinfer in favor of parinfer-rust-mode which has an active and responsive developer.

**Comment by gagbo** [comment]
> Looks like parinfer was removed from melpa and emacsmirror (though it's in the [attic](https://github.com/emacsattic/parinfer)). Should we continue supporting it? If so, we'll need to provide a full `:recipe` for it.

If not, we’ll need to add a `doctor` check for the dynamic module feature. Either way it looks like #4671 will need some changes

**Comment by johanthoren** [comment]
> If not, we’ll need to add a `doctor` check for the dynamic module feature. Either way it looks like #4671 will need some changes
I can modify it so that parinfer-rust-mode is the default choice for the module, if that is what is wanted by @hlissner. But the doctor stuff and how to transition users that already have parinfer enabled, I'm not sure how to do.
