### ISSUE TITLE
lagg in insert mode

### ISSUE THREAD

**Issue by ujjwal3067** [hlissner/doom-emacs#4638]
**what I was I doing**
- was editing simple python file that's all. 

- recently made a switch from neovim
- So far so great but insert mode is extremely laggy when typing fast not sure why and I have made zero config changes except enabling few inbuilt settings. 

operating system : macOS
Hardware : 16 inch version ( maxed out ) 

NOTE : it's snappy most of the time except  in insert mode. 
- I don't use any autocomplete ( I tend to rely on my typing speed and memory )

**Comment by ujjwal3067** [comment]
Fixed it. Was some problem with a package.

**Comment by ymarco** [comment]
In case anyone else has that issue, what problem with what package?
