### ISSUE TITLE
Build stuck at magit with native-comp

### ISSUE THREAD

**Issue by steven-lang** [hlissner/doom-emacs#4644]
**What did you expect to happen?**
- Run `doom build`
- Finish successfully

**What actually happened?**
- `doom build` gets stuck waiting for async processes to finish magit

`ps aux | grep emacs` shows:
```
tak        82406  1.5  0.5 559656 81748 pts/150  Ssl+ 09:52   0:03 /usr/bin/emacs --batch -l /tmp/emacs-async-comp-evil-collection-magit-dcCAH3.el
tak        82407  1.8  0.5 562928 84952 pts/151  Ssl+ 09:52   0:04 /usr/bin/emacs --batch -l /tmp/emacs-async-comp-evil-collection-magit-todos-c0zUfb.el
tak        82713  1.6  0.4 557144 78956 pts/5    Ssl+ 09:53   0:02 /usr/bin/emacs --batch -l /tmp/emacs-async-comp-git-commit-xbIgPE.el
tak        83025  1.1  0.4 555392 76868 pts/14   Ssl+ 09:54   0:01 /usr/bin/emacs --batch -l /tmp/emacs-async-comp-magit-ndGNDl.el
tak        83033  0.9  0.4 555344 77060 pts/4    Ssl+ 09:54   0:01 /usr/bin/emacs --batch -l /tmp/emacs-async-comp-magit-worktree-UqkrR9.el
tak        83034  1.1  0.4 555372 77016 pts/13   Ssl+ 09:54   0:01 /usr/bin/emacs --batch -l /tmp/emacs-async-comp-magit-wip-jLXORu.el
tak        83047  0.8  0.4 555264 77020 pts/12   Ssl+ 09:54   0:01 /usr/bin/emacs --batch -l /tmp/emacs-async-comp-magit-transient-Bv4ruB.el
tak        83052  0.8  0.4 555456 77092 pts/15   Ssl+ 09:54   0:00 /usr/bin/emacs --batch -l /tmp/emacs-async-comp-magit-tag-yAQV2Y.el
```

[This user](https://github.com/hlissner/doom-emacs/issues/4517#issuecomment-770417081) seems to have the same issue

**Additional details:**
- Include a link to your private config: https://github.com/steven-lang/dotfiles/tree/master/configs/emacs/.doom.d

**Steps to reproduce:**
1. Use Emacs 28 with `feature/native-comp`
2. Run `doom build`

**System information:**
<details><pre>
SYSTEM  info       ("Fedora release 33 (Thirty Three)" . Linux 5.10.13-200.fc33.x86_64 x86_64)
	shell      /bin/bash
	path       (~/.conda/condabin ~/bin ~/.gem/ruby/bin /usr/local/bin /usr/local/sbin /usr/bin /usr/sbin ~/bin/ ~/.emacs.d/bin/ ~/.antigen/bundles/robbyrussell/oh-my-zsh/lib ~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/git ~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/z ~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/fzf ~/.antigen/bundles/zsh-users/zsh-autosuggestions ~/.antigen/bundles/zsh-users/zsh-syntax-highlighting ~/.antigen/bundles/zsh-users/zsh-history-substring-search ~/.antigen/bundles/zsh-users/zsh-completions ~/.antigen/bundles/kutsan/zsh-system-clipboard ~/.antigen/bundles/mafredri/zsh-async ~/.antigen/bundles/sindresorhus/pure ~/.antigen/bundles/esc/conda-zsh-completion ~/.fzf/bin /usr/local/sbin /usr/local/bin /usr/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl ~/.local/bin ~/bin/ ~/.cargo/bin/ /opt/android-sdk/platform-tools/ /usr/bin/julia ~/.emacs.d/bin /usr/libexec/emacs/28.0.50/x86_64-redhat-linux-gnu)
EMACS   dir        ~/.emacs.d/
	version    (28.0.50 Feb 03, 2021)
	buildopts  --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-dbus --with-gif --with-jpeg --with-png --with-rsvg --with-tiff --with-xft --with-xpm --with-gpm=no --with-xwidgets --with-modules --with-harfbuzz --with-cairo --with-json --with-pgtk --with-nativecomp --enable-link-time-optimization build_alias=x86_64-redhat-linux-gnu host_alias=x86_64-redhat-linux-gnu CC=gcc 'CFLAGS=-DMAIL_USE_LOCKF -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection' LDFLAGS=-Wl,-z,relro PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig
	features   ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GSETTINGS HARFBUZZ JPEG JSON LCMS2 LIBOTF LIBSELINUX LIBSYSTEMD LIBXML2 MODULES NATIVE_COMP NOTIFY INOTIFY PDUMPER PGTK PNG RSVG SOUND THREADS TIFF TOOLKIT_SCROLL_BARS XIM XWIDGETS GTK3 ZLIB
	traits     (batch server-running envvar-file)
DOOM    dir        ~/.doom.d/
	version    (2.0.9 HEAD -> develop, origin/develop, origin/HEAD 0ff85015f 2021-02-11 23:33:28 -0500)
	modules    (:private (&user python) (&user emacs-lisp) (&user evil) (&user latex) (&user lsp) (&user org) (&user pdf) (&user ui +circadian) :completion (company +childframe) (ivy +flx +icons +prescient) :ui deft doom doom-dashboard hl-todo hydra modeline nav-flash ophints (popup +all +defaults) vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold format snippets word-wrap :emacs dired electric undo vc :term vterm :checkers syntax (spell +flyspell +aspell) grammar :tools (debugger +lsp) direnv (eval +overlay) (lookup +docsets) (lsp +peek) magit pdf rgb :lang data emacs-lisp (latex +latexmk +cdlatex +lsp) markdown (org +dragndrop +roam +pomodoro +present) (python +lsp +conda +pyright) (sh +lsp) :app everywhere :config (default +bindings +smartparens))
	packages   ((s) (yasnippet-snippets) (lorem-ipsum) (ssh-agency) (cuda-mode) (dockerfile-mode) (yaml-mode) (helm) (crux) (powerthesaurus))
	unpin      (n/a)
	elpa       (n/a)
</pre></details>

**Comment by CaderHancock** [comment]
These are not the only packages that cause this to hang. I have also been hanging on forge.

**Comment by steven-lang** [comment]
@CaderHancock which native-comp commit are you on? I've just built from source with the latest commit and the issues vanished. Closing this now.

**Comment by CaderHancock** [comment]
I was on some jan18 commit that was given to me by the AUR. I saw your PR close and am now building from the latest on the branch. Will let you know if it works after the ~10 hours my x220 takes to build it.
