### ISSUE TITLE
How do I authenticate gpg within Emacs ?

### ISSUE THREAD

**Issue by Benjamin-Philip** [hlissner/doom-emacs#4647]
# The Issue

I am unable to get pinentry within emacs working. Whenever I have to authenticate (to commit),  I get the following error (except when the password is cached):

```
128 git --no-pager --literal-pathspecs -c core.preloadindex\=true -c log.showSignature\=false -c color.ui\=false -c color.diff\=false commit --
17:22:50.743823 git.c:442               trace: built-in: git commit --
hint: Waiting for your editor to close the file...
17:22:50.764559 run-command.c:663       trace: run_command: '/usr/bin/emacsclient.emacs --socket-name=/tmp/emacs1000/server' /mnt/d/Benjamin/Documents/themes/textbook/.git/COMMIT_EDITMSG
Waiting for Emacs...
17:23:43.455558 run-command.c:663       trace: run_command: gpg2 --status-fd=2 -bsau <my gpg key>
error: gpg failed to sign the data
fatal: failed to write commit object
```

And nothing happens when I try to open a `.gpg` file (No prompt for password to decrypt).

# Expected behavior

pinentry to just work after following documentation

# What have I tried ?

As per the [ELPA documentation](https://elpa.gnu.org/packages/pinentry.html), I have added `allow-emacs-pinentry` to my `~/.gnupg/gpg-agent.conf`. I have also installed pinentry.el and have started the pinentry-server.

Here is my `gpg-agent.conf`:

```conf
# Keyboard control
no-grab

# PIN entry program
allow-emacs-pinentry
allow-loopback-pinentry
enable-ssh-support
```

This is my `~/.doom.d/packages.el` (I have a week old install):

```elisp
(package! pinentry)
```

And this is my `~/.doom.d/config.el`:

```elisp
(use-package! pinentry
        :init (setq epa-pinentry-mode `loopback)
               (pinentry-start))
```

# System details

gnupg2 :

```bash
ben@frodo:~$ gpg2 --version
gpg (GnuPG) 2.2.20
libgcrypt 1.8.5
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: /home/ben/.gnupg
Supported algorithms:
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2
```
pinentry:

```bash
ben@frodo:~$ pinentry-tty --version
pinentry-tty (pinentry) 1.1.0
Copyright (C) 2016 g10 Code GmbH
License GPLv2+: GNU GPL version 2 or later <https://www.gnu.org/licenses/>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

Emacs:

```bash
ben@frodo:~$ emacs --version
GNU Emacs 26.3
Copyright (C) 2019 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of GNU Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
```

Doom's current `HEAD`:

```bash
ben@frodo:~/.emacs.d$ git log -1 --stat > foo.txt && cat foo.txt
commit 0ff85015f8734f81f71fe188e156b2aea2a86981
Author: Henrik Lissner <henrik@lissner.net>
Date:   Thu Feb 11 23:33:28 2021 -0500

    s/defadvice!/advice-add in comp config block

    Part 2 of 811099282.

    The latest build of native-comp appears to eagerly load comp very early,
    so defadvice! won't be defined when this block runs, causing this error.

 core/core.el | 6 +++---
 1 file changed, 3 insertions(+), 3 deletions(-)
```

And Ubuntu:

```
ben@frodo:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.10
Release:        20.10
Codename:       groovy
```

**Comment by hlissner** [comment]
Sorry for the late response. Is this still an issue?

1. Do you have `pinentry-emacs` installed (via your system package manager)?
2. Can you reproduce this [in vanilla Emacs?](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#testing-in-dooms-sandbox)

**Comment by Benjamin-Philip** [comment]
@hlissner, yes it's still an issue.  I currently am just using vim whenever I need to write commit messages and etc.

> Can you reproduce this in vanilla Emacs?

Yes I can reproduce it in vanilla emacs (I renamed the `doom-emacs ` directory, and had setup a fresh `.emacs.d`. Didn't notice doom sandbox.)

For some reason, if I started emacs from bash, I was able to use gpg's curses prompt from my terminal. However, if I started emacs from zsh, gpg's tty prompt was illegible and unusable.

> Do you have pinentry-emacs installed (via your system package manager)?

I use ubuntu, and they don't have a `pinentry-emacs` package in their package repository (nor does Debian).  So, in order to have `pinentry-emacs`, I'll have to rebuild `pinentry` with emacs support, and then install with `dpkg` (the package manager that `apt` is built on.)  Or, I'll have have to find a pinentry-emacs PPA.

I was hoping not to rebuild `pinentry` and expected some emacs lisp or shell solution, given that Debian and it's derivatives are the most popular distos now. I found quite hard to believe **all** the debian emacsers  would rebuild `pinentry` for this. (Maybe I should just use Fedora or Arch ?)

Just wondering, what do other debian users do ?

**Comment by hackerb9** [comment]
> I was hoping not to rebuild `pinentry` and expected some emacs lisp or shell solution, given that Debian and it's derivatives are the most popular distos now. I found it quite hard to believe that **all** the debian emacsers would rebuild `pinentry` for this. (Maybe I should just use Fedora or Arch ?)
> 
> What do other debian users do ?

It just works for me with vanilla GNU Emacs, Debian stable. I followed the ELPA instructions, only deviating in that I set epa-pinentry-mode and run pinentry-start in my .emacs file.  

> I most likely won't rebuild `pinentry`. I hope that's ok with you.

You do not need to rebuild pinentry. I believe since around 2015 the default pinentry already knows the emacs protocol.
