### ISSUE TITLE
suggestion: ignore `evil-forward-char` and `evil-backward-char` in dashboard

### ISSUE THREAD

**Issue by Luis-Henriquez-Perez** [hlissner/doom-emacs#465]
I remapped `evil-forward-char` and `evil-backward-char` to `ignore` as well because they don't seem necessary for the dashboard. In fact when I end up accidentally leaving an icon they can throw me off track a bit. What do you think?

    (map! :map +doom-dashboard-mode-map
      "n" #'+doom-dashboard/next-button
      "p" #'+doom-dashboard/previous-button
      "N" #'+doom-dashboard/last-button
      "P" #'+doom-dashboard/first-button
    ;;; my changes
      [remap evil-forward-char] #'ignore
      [remap evil-backward-char] #'ignore
    ;; end of changes
      [remap evil-insert]  #'ignore
      [remap evil-replace] #'ignore
      [remap evil-change]  #'ignore
      [remap evil-visual-char]  #'ignore
      [remap evil-visual-line]  #'ignore
      (:when (featurep! :feature evil)
        :em "j" #'+doom-dashboard/next-button
        :em "k" #'+doom-dashboard/previous-button
        :em "gg" #'+doom-dashboard/first-button
        :em "G"  #'+doom-dashboard/last-button))

**Comment by hlissner** [comment]
I'll happily accept these changes, but I have to wonder if there's a better way to handle this. Perhaps a custom evil stats for the dashboard or something

**Comment by hlissner** [comment]
I've improved on this method by adding a `post-command-hook` to the dashboard buffer that keeps the point inside buttons. This should effectively resolve the issue. Let me know if it gives you any trouble.

I'll keep this open until it hits `master`.

**Comment by Luis-Henriquez-Perez** [comment]
Good point. I'll give implementing that a go and get back to you.

**Comment by Luis-Henriquez-Perez** [comment]
It seems OK. I noticed that it's still possible to move the cursor forward as long as `point` is within the button label. I think it would be slightly better for the point to be contained only in the icon. But, then again, it's a minor point as it's still possible to press the button and moving to the next/previous button is still fine. It may just be a matter of taste. 

I'll look into ways of doing that and share what I find.

**Comment by Luis-Henriquez-Perez** [comment]
To achieve it I first added an extra condition:

    (defun +doom-dashboard|reposition-point ()
      "Trap the point in the buttons."
      (unless (and (button-at (point))
                   (equal (plist-get (get-char-property (point) 'face) :family)
                      "github-octicons"))
      (or (+doom-dashboard/previous-button)
           (+doom-dashboard/first-button))))

This almost works, but you can still get to a label but using `evil-backward-char` on the beginning on a button that's not the first button. So I also had to modify `doom-dashboard/previous-button`.

(defun +doom-dashboard/previous-button ()
  "Jump to the previous button after cursor."
  (interactive)
  (ignore-errors (goto-char (button-start (previous-button (point))))))

Maybe makes this makes the code look less nice. Also it would only work for `github-octicons`.  What do you think?

**Comment by hlissner** [comment]
Unfortunately, that wouldn't work in terminal Emacs. That said, only a small adjustment to `+doom-dashboard|reposition-point` was required. The cursor should now be properly trapped at the beginning of buttons.

**Comment by Luis-Henriquez-Perez** [comment]
nice! For fun, here's an alternative I was about to post:

    (defun +void-dashboard|reposition-point ()
     "Trap the point in the buttons."
     (unless (and (button-at (point))
               (= (point) (button-start (button-at (point)))))
     (or (+void-dashboard/previous-button)
        (+void-dashboard/first-button))))

I'm glad I could contribute =)
