### ISSUE TITLE
native-comp doom install fails on latest version

### ISSUE THREAD

**Issue by CaderHancock** [hlissner/doom-emacs#4652]
**What did you expect to happen?**
I expected doom install to function normally on feature/native-comp commit 
31416495ad9b2c84473f72ad99e2adc87dd66e5a
(the most recent as of this post)

**What actually happened?**
.emacs.d/bin/doom install

Installing straight...

Debugger entered--Lisp error: (void-variable comp-ctxt)
(type-of comp-ctxt)
(memq (type-of comp-ctxt) cl-struct-comp-cstr-ctxt-tags)
(and (memq (type-of comp-ctxt) cl-struct-comp-cstr-ctxt-tags) t)
(progn (and (memq (type-of comp-ctxt) cl-struct-comp-cstr-ctxt-tags) t))

Full paste: https://pastebin.com/rp5at9Vp

<details><pre>
If an error message is involved include a backtrace of it.

How to acquire a backtrace:
https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#how-to-extract-a-backtrace-from-an-error
</pre></details>

**Steps to reproduce:**
Checkout 31416495ad9b2c84473f72ad99e2adc87dd66e5a
autogen.sh
configure.sh
make
sudo make install
normal doom install

**System**
up to date Arch Linux

**Comment by CaderHancock** [comment]
Wow, I'm dumb. I didn't realize I needed to 

./configure --with-nativecomp

I will close this now.

**Comment by adwhit** [comment]
For anyone else who comes across this problem, note that the flag has changed and lots of the references on the web are now out of date. the correct way to configure is
```
./configure --with-native-compilation
```
ref: https://lists.gnu.org/archive/html/emacs-devel/2021-02/msg02011.html

**Comment by cdegroot** [comment]
@adwhit thanks for that. If we'd be on Reddit, I'd give you some gold right now. My Doom emacs got borked in this way after an Emacs+Doom upgrade, and otherwise I wouldn't have made the code show-and-tell demo that is starting in ten minutes with a working dev env ;-)
