### ISSUE TITLE
Disable Prettier for Specific Projects/Folders

### ISSUE THREAD

**Issue by helderburato** [hlissner/doom-emacs#4657]
## Context

I've prettier-js enabled as default in my Doom Emacs you can see more [here](https://github.com/helderburato/dotfiles/blob/main/emacs/.doom.d/config.el#L149).

## Question

I'm working on some projects who don't use `Prettier` but my default configs are triggering format on save.

I would like to know if has any way to disable just in specific projects or folders when open buffers with JS/TS?

**Comment by hlissner** [comment]
See https://doomemacs.discourse.group/t/file-and-directory-local-settings/161#directory-or-project-local-variables for instruction on how to set up a `.dir-locals.el` file for your project (allowing you to set project-specific settings).

Use it to either set `+format-with` to the id of the formatter you want to use in that project, or to `:none` to disable it altogether.

**Comment by helderburato** [comment]
Thanks for the reply @hlissner!

I made the following to just enable when has `.prettierrc` or `.prettierrc.json`:
```lisp
(defun maybe-use-prettier ()
  "Enable prettier-js-mode if .prettierrc or .prettierrc.json file is located."
  (if (locate-dominating-file default-directory ".prettierrc")
    (prettier-js-mode +1))
  (if (locate-dominating-file default-directory ".prettierrc.json")
    (prettier-js-mode +1)))

(use-package! prettier-js)
(after! prettier-js
  :config
  (setq! prettier-js-args '(
                             "--trailing-comma" "all"
                             "--bracket-spacing" "true"
                             )))
(add-hook! '(
              js2-mode-hook
              rjsx-mode-hook
              web-mode-hook
              typescript-mode-hook
              typescript-tsx-mode-hook) 'maybe-use-prettier)
```

-----

The unique thing I'm trying to do now is to disable `format +onsave` to specific projects, I tried creating the file `.dir-locals.el` and disable `flycheck`, such as:
```lisp
;;; Directory Local Variables
;;; For more information see (info "(emacs) Directory Variables")

(js2-mode (eval (flycheck-mode -1)))
```

Can you help with that?
