### ISSUE TITLE
Tramp not working

### ISSUE THREAD

**Issue by MicLennartz** [hlissner/doom-emacs#4658]
Hi,

with the current version of doom-emacs (v2.0.9) and emacs 27.1 (brew install emacs-plus), I can't get tramp working for opening remote files via SSH/SCP on a Mac.

As soon as I start to type any remote URL, like '/ssh:' or '/scp:' or '/-:', I get a dialog from my keychain to unlock access to some password entry (which is a random one and not related to the URL).

When I allow the access to the keychain entry, I can still do a C-g. But when I reject the keychain access, Emacs freezes. Only a kill -9 is possible then.

I've tried to install a more recent version of tramp, which is promising to fix this issue, I get blocking errors with doom and helm:

my config:
```(package! tramp)```

causing this persistent error:
```
Error in pre-command-hook (doom-first-input-hook-h): (doom-hook-error helm-mode (void-function tramp-register-crypt-file-name-handler))
tramp-register-file-name-handlers: Symbol’s function definition is void: tramp-register-crypt-file-name-handler
```

Since this is a major issue for me, any hint would be very appreciated.

Br,
Michael

**Comment by hlissner** [comment]
Do not try to install a new version of tramp. The new error indicates you've broken tramp by doing so. The freeze indicates tramp is working, just not getting past a certain roadblock to do with interfacing with or interpreting the response from your keychain.

What's more, you ignored the server template, so much of a the important information I need is absent, so we'll have to do this interrogation dance. **Please do not ignore the server template in the future.**

1. Please include your `M-x doom/info` in your issue.
2. Have you enabled the `:os macos` module? It activates special integration with keychain that may fix your issue.
3. Next time you experience this freeze, send a `USR2` single to Emacs to force it to throw up a backtrace. e.g. `kill -USR2 $pid`. Include that backtrace.

This is unlikely to be a Doom issue, and I don't use MacOS so my insight ends there. 

Hope that helps.
