### ISSUE TITLE
node command not found (node installed with nvm)

### ISSUE THREAD

**Issue by drocha87** [hlissner/doom-emacs#4659]
**What did you expect to happen?**
I expect that emacs use the current node version defined by nvm

**What actually happened?**
node is not found 

<details><pre>
/usr/bin/env: ‘node’: No such file or directory
</pre></details>

**Steps to reproduce:**
1. Install node using nvm
2. enable `(format +onsave)` 
3. Save a file that depends of node to format the code

**Extra information**
If I run `M-x shell` the command `node --version` shows me the correct node version but `M-x eshell` don't. 

**Possible solution**
The recommended solution is to install [`purcell/exec-path-from-shell`](https://github.com/purcell/exec-path-from-shell) and execute it before `package-initialize` but I don't know how is the correct way to do that in `doom emacs` or even if this is necessary.

**System information:**
<details><pre>
```
SYSTEM  info       ("Manjaro Linux" . Linux 5.9.16-1-MANJARO x86_64)
	shell      /bin/zsh
	path       (~/.nvm/versions/node/v12.20.2/bin ~/.cargo/bin ~/.local/bin /usr/local/bin /usr/bin /bin /usr/local/sbin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /var/lib/snapd/snap/bin /usr/lib/emacs/27.1/x86_64-pc-linux-gnu)
EMACS   dir        ~/.emacs.d/
	version    (27.1 ago 28, 2020)
	buildopts  --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-wide-int --with-modules --with-cairo --with-harfbuzz 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
	features   XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP
	traits     (batch server-running envvar-file)
DOOM    dir        ~/.doom.d/
	version    (2.0.9 grafted, HEAD -> develop, origin/develop, origin/HEAD 5e8a668 2021-02-14 21:14:07 -0500)
	modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline ophints (popup +defaults) vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold (format +onsave) snippets :emacs dired electric ibuffer undo vc :checkers syntax :tools editorconfig (eval +overlay) lookup lsp magit :lang cc emacs-lisp (go +lsp) json javascript markdown org rust sh (web +lsp) :config (default +bindings +smartparens))
	packages   ((modus-themes) (dired-subtree))
	unpin      (n/a)
	elpa       (n/a)
```
</pre></details>

**Comment by bnjmnt4n** [comment]
I believe you can try running `doom env` to capture your shell's environment variables: https://github.com/hlissner/doom-emacs/blob/develop/docs/faq.org#doom-cant-find-my-executablesdoesnt-inherit-the-correct-path.

**Comment by drocha87** [comment]
@bnjmnt4n thanks for the fast reply, It works as suggested!
