### ISSUE TITLE
Can't find buffer/file name in modeline

### ISSUE THREAD

**Issue by jingxlim** [hlissner/doom-emacs#4661]
This is a cross post from `doom-modeline`, as suggested by its maintainer: https://github.com/seagle0128/doom-modeline/issues/415#issue-808099809.

**What did you expect to happen?**
I expected to find the buffer/file name when files are open / being edited.

**What actually happened?**
I can't find the buffer/file name in my modeline when viewing `.el`, `.py`, `.org` and probably any other file.  Interestingly, the file name displays fine on the Doom splash screen.

**Additional details:**
As the issue persist even after a fresh install of `doom-emacs` (new clone of the repo and new `~/.doom.d`), the default config files are also causing me this error.

<details><pre>
No error messages except that 'cl' is deprecated.
</pre></details>

**Steps to reproduce:**
1. Opened doom, saw `~/doom.d/` displaying fine on the modeline.
![image](https://user-images.githubusercontent.com/16644710/107891346-0d55dc00-6eec-11eb-9d57-96dc2a643d3d.png)

2. Opened my doom `config.el` file but don't see file name in the modeline.
![image](https://user-images.githubusercontent.com/16644710/107891317-d2ec3f00-6eeb-11eb-80a8-744d2aa02081.png)

3. Launched doom emacs in a sandbox Doom + modules - your private config (M-x doom/sandbox C-c C-p) and then opened `config.el` as above -- was able to see file name in the modeline. At this point, I thought this issue has something do with my my private config files, so I sought to obtain a fresh install of doom.

4. Fresh install of doom (I followed instructions for using Doom emacs alongside other distributions: https://github.com/hlissner/doom-emacs/blob/develop/docs/faq.org#how-do-i-use-doom-alongside-other-emacs-configs). At this point, I have fresh emacs-doom directory and default .doom.d `config.el`, `packages.el` and `init.el` files.

5. Opened `config.el` and still was not able to find file name in the modeline.

6. Once again, tried to launch doom emacs in sandbox and was able to once again find file name in the modeline.

Comparison of (left) fresh install of doom and (right) sandbox:

![image](https://user-images.githubusercontent.com/16644710/107894947-7004a300-6eff-11eb-89a5-fffe228f7ae3.png)

I did notice that the red debug spider is also missing...

**System information:**
<details><pre>
 - OS and version: Windows 10 running Ubuntu 20.04 on WSL 1
 - Emacs Version: 27.1
 - doom ui/modeline v2.0.9

`M-x doom/info`: https://pastebin.com/T1sgUus6
</pre></details>

**Comment by hlissner** [comment]
1. Open the sandbox: `M-x doom/sandbox`
2. Type the following in the sandbox buffer:

```elisp
(require 'doom-modeline)
(doom-modeline-mode +1)
```
3. Press `C-c C-c` to launch vanilla Emacs (no Doom, no private config).
4. Can you reproduce the issue?

**Comment by jingxlim** [comment]
This is the result -- I was able to see the buffer/file name:

![image](https://user-images.githubusercontent.com/16644710/108468347-9c4c5680-7254-11eb-8164-cd580b75361b.png)
