### ISSUE TITLE
PDF annotations in evil closes window when you hit escape

### ISSUE THREAD

**Issue by znewman01** [hlissner/doom-emacs#4665]
Possibly related: #1970

**What did you expect to happen?**

When annotating a PDF, I expect `ESC` (`evil-force-normal-state`) to be idempotent, putting me in normal mode.

**What actually happened?**

`ESC` from normal mode closes the PDF annotation popup.

**Additional details:**
- My [Emacs config](https://github.com/znewman01/dotfiles/tree/master/emacs) (but I've reproduced in the sandbox)
- No relevant warnings/errors/messages
- Screencast at end of issue (keypress overlay is in the way but I think you can see through it)

**Steps to reproduce:**
(in "Vanilla Doom Plus" sandbox)
1. Open PDF file (I've verified the behavior with several)
2. Add a text annotation `C-c C-a t` (`pdf-annot-add-text-annotation`)
3. Click to add the text annotation; click to open the text annotation.
3. Hit `ESC` (or, more realistically: enter insert mode, type something, then hit `ESC ESC`)

**System information:**
```
SYSTEM  info       (NixOS 20.09.2642.88f00e7e12d (Nightingale) . Linux 5.9.16 x86_64)
        shell      /run/current-system/sw/bin/bash
        path       (~/bin /run/wrappers/bin ~/.nix-profile/bin /etc/profiles/per-user/$USER/bin /nix/var/nix/profiles/default/bin /run/current-system/sw/bin /nix/store/09vvj9zhppcr0mjkby37w4rrs5y92040-emacs-27.1/libexec/emacs/27.1/x86_64-pc-linux-gnu)
EMACS   dir        ~/.emacs.d/
        version    (27.1 Feb 16, 2021)
        buildopts  --prefix=/nix/store/09vvj9zhppcr0mjkby37w4rrs5y92040-emacs-27.1 --disable-build-details --with-modules --with-x-toolkit=gtk3 --with-xft CFLAGS=-DMAC_OS_X_VERSION_MAX_ALLOWED=101200
        features   XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GSETTINGS GLIB NOTIFY INOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER GMP
        traits     (gui daemon server-running)
DOOM    dir        ~/.doom.d/
        version    (2.0.9 fatal: not a git repository (or any of the parent directories): .git)
        font       #<font-spec nil nil Roboto Mono nil nil semi-light nil nil nil nil nil nil ((:height . 80))>
        theme      base16-zjn
        modules    (:completion company ivy :ui deft doom doom-dashboard hl-todo modeline ophints (popup +all) vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) fold (format +onsave) snippets :emacs dired undo vc :checkers syntax :tools biblio direnv (eval +overlay) lookup lsp magit pdf terraform :lang emacs-lisp latex markdown nix (org +roam +pretty) (python +lsp +pyright) (rust +lsp) sh :email mu4e :app rss :config (default +bindings +smartparens))
        packages   ((org-ref) (csv-mode) (nix-mode :recipe (:host github :repo znewman01/nix-mode :flavor github) :pin nil) (org-msg :recipe (:host github :repo jeremy-compostella/org-msg :branch master :flavor github) :pin nil) (org-roam-bibtex :recipe (:host github :repo org-roam/org-roam-bibtex)) (mixed-pitch) (org-fancy-priorities :disable t) (org-starless :recipe (:host github :repo TonCherAmi/org-starless)) (org-padding :recipe (:host github :repo TonCherAmi/org-padding)) (org-fragtog) (base16-theme))
        unpin      (nix-mode org-msg org-roam company-org-roam bibtex-completion helm-bibtex ivy-bibtex)
        elpa       (use-package bind-key)
```

The "not a git repository" is because I manage my Doom install in Nix; I verified that the issue is still present in latest Doom ([28b3ad](https://github.com/hlissner/doom-emacs/commits/28b3ad452979669abbb1a2903dfaa51e304765b5))

![recording](https://user-images.githubusercontent.com/873857/108141824-77a88100-7092-11eb-8394-a302836f8707.gif)

**Comment by hlissner** [comment]
Sorry for the late response. See if this fixes your issue:

```elisp
;; add to ~/.doom.d/config.el
(after! pdf-tools
  (set-popup-rule! "^\\*Edit Annotation " :quit nil))
```

**Comment by znewman01** [comment]
That works perfectly for me; I'll leave this issue open so you can decide whether to address within Doom.

Thank you!

**Comment by hlissner** [comment]
As of 36d186d this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by znewman01** [comment]
Just upgraded Doom and it seems to be working perfectly; thanks for the fix and all your work on this project!
