### ISSUE TITLE
Confusing text about removing evil

### ISSUE THREAD

**Issue by dabrahams** [hlissner/doom-emacs#4666]
These two things, written right next to one another in https://github.com/hlissner/doom-emacs/blob/develop/modules/editor/evil/README.org#removing-evil-mode, seem mutually contradictory.  Either when removing evil I need to reassign these variables, or I can ignore them, but I don't understand how to do both at once.  Also AFAICT they are bound to `M-SPC` and `M-SPC m`, not `C-c` and `C-c l`.  I'd suggest a fix if I had any idea what the right thing to say was…

```
You must do two things to remove Evil:
...
3. [OPTIONAL] You may want to assign new values to ~doom-leader-alt-key~ and
   ~doom-localleader-alt-key~. These are bound to =C-c= and =C-c l= by default.

#+begin_quote
Ignore ~doom-leader-key~ and ~doom-localleader-key~, they don't apply to
non-evil sessions.
#+end_quote

```

**Comment by hlissner** [comment]
> Also AFAICT they are bound to M-SPC and M-SPC m

[They are bound to `C-c` and `C-c l` when evil is disabled.](https://github.com/hlissner/doom-emacs/blob/develop/modules/config/default/+emacs-bindings.el#L4-L5)

> These two things, written right next to one another in https://github.com/hlissner/doom-emacs/blob/develop/modules/editor/evil/README.org#removing-evil-mode, seem mutually contradictory

Sounds like you misread. 

+ `doom-leader-key` != `doom-leader-alt-key` and `doom-localleader-key` != `doom-localleader-alt-key`.
+ `doom-leader-key` and `doom-localleader-key` are not used when evil is disabled, as the quote says.
+ You may want to change `doom-leader-alt-key` (default: `C-c`) and `doom-localleader-alt-key` (default: `C-c l`) if you don't like their defaults. If you don't mind the defaults, you don't have to. Seems clear to me.

----

As this seems like a misinterpretation, I'll close this. In any case, our docs are undergoing a rewrite, so this will likely resolve itself in time anyway.

**Comment by dabrahams** [comment]
I see. Yes, it's a misinterpretation, which points to the need to more clearly distinguish the different variables.  If, as you say, the “docs are undergoing a rewrite,” should I stop trying to submit improvements?  I'm trying to be helpful, not annoying ;-)
