### ISSUE TITLE
[BUG] Go-to-end non-ideal behavior

### ISSUE THREAD

**Issue by clyfe** [hlissner/doom-emacs#4676]
**What did you expect to happen?**
In elisp mode, given line: `^|;;; a-comment$` (special chars are beginning, cursor, and end of line),
running `doom/forward-to-last-non-comment-or-eol` I'd expect it to go **straight to the end** in this case (given I'm at the beginning of the comment).

**What actually happened?**
- first run does: `^;|;; a-comment$`,
- only **second** run does: `^;;; a-comment|$`.

**Comment by hlissner** [comment]
As of d76d50c this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
