### ISSUE TITLE
anzu and iedit packages vanish together with evil ones ...

### ISSUE THREAD

**Issue by jwintz** [hlissner/doom-emacs#468]
... they could however test `feature-p evil` and still be very useful to anyone *not* using `evil`, which I must say, for one day of full switch to `doom`, works out of the box (except for a small warning cause magit package also assume some evilness).

**Comment by hlissner** [comment]
I'm afraid I've little experience with vanilla Emacs, so I have few opportunities to explore non-evil usecases. 

iedit is a dependency of [evil-multiedit](https://github.com/hlissner/evil-multiedit) in `feature/evil`, as is anzu, but with [evil-anzu](https://github.com/syohex/emacs-evil-anzu) in `:ui doom-modeline`. Both are designed for evil. I don't doubt that `iedit` and `anzu` work without their evil variants, but as of yet, they are not configured to stand alone in Doom.

**Comment by jwintz** [comment]
Ok, I’ll add them to my personal config then. Any clues on making the modeline work in this case ?

**Comment by jwintz** [comment]
Fixed. Thanks.
