### ISSUE TITLE
phpactor does't work

### ISSUE THREAD

**Issue by 354651432** [hlissner/doom-emacs#4684]
**What did you expect to happen?**
`company-phpactor` works

**What actually happened?**
`company-backends` can't change to `company-phpactor` and does't work, but I can use `company-phpactor` to complete manually

**Additional details:**
- Include a link to your private config
```elisp
(setq phpactor-executable "/home/dual/code/phpactor/bin/phpactor")
(add-hook 'php-mode-hook ((lambda () (interactive)
      (setq-local company-backends '((company-phpactor company-files))))))

```
- Include screenshots/casts of your issue
`phpactor-status`
![image](https://user-images.githubusercontent.com/8469080/108825833-792bf900-75fe-11eb-94bc-ec6b292955e7.png)
![image](https://user-images.githubusercontent.com/8469080/108825343-da070180-75fd-11eb-8ac9-8c8884d667ee.png)
![image](https://user-images.githubusercontent.com/8469080/108825628-3bc76b80-75fe-11eb-8257-b1d5049718e5.png)

- If you mention key sequences, include what commands they're bound to (use `SPC
  h k KEY` or `C-h h k KEY` to inspect keys).
- Include any warnings or errors logged to \*Messages\* (use `M-x
  view-echo-area-messages` to see it).
```
No completion found
<mode-line> <down-mouse-1>-  which-key: There are no keys to show
No completion found
Auto-saving...
No completion found
```
<details><pre>
If an error message is involved include a backtrace of it.

How to acquire a backtrace:
https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#how-to-extract-a-backtrace-from-an-error
</pre></details>

**Steps to reproduce:**
```
SYSTEM  info       ("Manjaro Linux" . Linux 5.4.80-2-MANJARO x86_64)
        shell      /usr/bin/zsh
        path       (~/.emacs.d/bin/ ~/.local/bin /usr/local/bin /usr/local/sbin /usr/bin ~/Android/Sdk/platform-tools /var/lib/flatpak/exports/bin /opt/flutter-sdk/bin /usr/lib/jvm/default/bin /var/lib/snapd/snap/bin /opt/docker /opt/node/bin /opt/node/bin /usr/lib/emacs/28.0.50/x86_64-pc-linux-gnu/)
EMACS   dir        ~/.emacs.d/
        version    (28.0.50 90bd6d8ba66bde8d9626f3dd05d14372734e6ce5 1月 22, 2021)
        buildopts  --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --mandir=/usr/share/man --with-gameuser=:games --with-sound=alsa --with-modules --without-gconf --without-gsettings --enable-link-time-optimization --with-x-toolkit=gtk3 --without-xaw3d --without-compress-install 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -flto -fuse-linker-plugin' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
        features   ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GPM HARFBUZZ JPEG JSON LCMS2 LIBOTF LIBSYSTEMD LIBXML2 M17N_FLT MODULES NOTIFY INOTIFY PDUMPER PNG RSVG SOUND THREADS TIFF TOOLKIT_SCROLL_BARS X11 XDBE XIM XPM GTK3 ZLIB
        traits     (gui server-running envvar-file)
DOOM    dir        ~/.doom.d/
        version    (2.0.9 HEAD -> develop 3f4cc77d2a 2021-02-21 14:44:59 -0500)
        font       #<font-spec nil nil Fira Code nil nil semi-light nil nil 23 nil nil nil nil>
        theme      doom-one
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline neotree ophints (popup +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold format snippets :emacs (dired +ranger) electric undo vc :term eshell shell term vterm :tools (eval +overlay) lookup lsp magit :os tty :lang emacs-lisp (go +lsp) json javascript markdown org php python sh web :app twitter :config (default +bindings +smartparens))
        packages   ((youdao-dictionary) (posframe) (emmet-mode) (chinese-wbim) (cnfonts) (multiple-cursors) (pyim) (pyim-wbdict) (helm) (org-appear :recipe (:repo https://github.com/awth13/org-appear.git)) (py-autopep8) (company-jedi) (org-bullets) (ligature :recipe (:repo https://github.com/mickeynp/ligature.el)) (company-phpactor) (php-mode))
        unpin      (n/a)
        elpa       (xwwp-follow-link-helm xwwp pretty-mode popwin popup hl-anything helm-core helm async)
```

**System information:**
<details><pre>
Place the output of `M-x doom/info` or `~/.emacs.d/bin/doom info` here.
</pre></details>

**Comment by prsdta** [comment]
```elisp
(add-hook 'php-mode-hook ((lambda () (interactive)
      (setq-local company-backends '((company-phpactor company-files))))))
```
This bit your config is unnecessary, Doom's `php` module already takes care of this. Maybe it's actually causing conflicts here.

**Comment by 354651432** [comment]
> ```emacs-lisp
> (add-hook 'php-mode-hook ((lambda () (interactive)
>       (setq-local company-backends '((company-phpactor company-files))))))
> ```
> 
> This bit your config is unnecessary, Doom's `php` module already takes care of this. Maybe it's actually causing conflicts here.

phpactor does't work and then I add it .this should be not the problem
