### ISSUE TITLE
`projectile-replace` stops if it encounters a match in a buffer that's already open

### ISSUE THREAD

**Issue by Ruin0x11** [hlissner/doom-emacs#4687]
**What did you expect to happen?**
Running `projectile-replace` will replace all occurrences of a phrase across the entire project.

**What actually happened?**
If a file containing a match is contained in an active buffer, the replacement will stop there, leaving half of the matches changed and the rest unchanged. This is really dangerous when refactoring code for dynamically typed languages.

`(projectile-replace-regex)` doesn't have this problem, but it instead tries to search through every single file in the repository, including binary files, which takes far longer, and it can also outright fail midway if it can't open one of files in the project.

**Steps to reproduce:**
1. Run `(projectile-replace)` interactively and enter a phrase/replacement.
2. Press `Y` to replace the rest of the matches.

**System information:**
<details><pre>
((emacs
  (version . "27.1")
  (features . "XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP")
  (build . "Aug 28, 2020")
  (buildopts "--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-wide-int --with-modules --with-cairo --with-harfbuzz 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop 9cab6a6fd 2020-08-13 22:49:35 -0400")
  (dir . "~/.doom.d/"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/bin/zsh")
  (uname . "Linux 5.10.10-arch1-1 #1 SMP PREEMPT Sat, 23 Jan 2021 23:59:48 +0000 x86_64")
  (path "~/.opam/default/bin" "~/.cargo/bin" "/usr/lib/go/bin/" "~/.bin" "~/.cargo/bin" "/usr/lib/go/bin/" "/usr/local/sbin" "/usr/local/bin" "/usr/bin" "/opt/android-sdk/platform-tools" "/opt/android-sdk/tools" "/opt/android-sdk/tools/bin" "/usr/lib/jvm/default/bin" "/opt/openresty/bin" "/opt/openresty/nginx/sbin" "/usr/bin/site_perl" "/usr/bin/vendor_perl" "/usr/bin/core_perl" "~/.local/bin" "~/.gem/ruby/2.6.0/bin" "~/.gem/ruby/2.7.0/bin" "~/.luarocks/bin" "/sbin" "/usr/sbin" "~/build/go/bin" "~/miniconda3/bin" "/home/ruin/.gem/ruby/2.5.0/bin" "~/build/elona-next" "~/build/util/doom-emacs/bin" "~/build/go/bin" "~/miniconda3/bin" "/home/ruin/.gem/ruby/2.5.0/bin" "~/build/elona-next" "~/build/util/doom-emacs/bin" "/usr/lib/emacs/27.1/x86_64-pc-linux-gnu"))
 (config
  (envfile)
  (elc-files . 0)
  (modules :input japanese :completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +defaults) vc-gutter vi-tilde-fringe :editor (evil +everywhere) file-templates fold snippets :emacs dired electric undo vc :checkers syntax :tools docker (eval +overlay) lookup lsp magit :lang clojure csharp elixir emacs-lisp json lua markdown ocaml org rust sh yaml :config (default +bindings +smartparens))
  (packages (cider :recipe (:local-repo "~/build/cider" :files ("*.el" "src/lisp/*.el"))) (hsp-mode :recipe (:local-repo "~/.doom.d/site-lisp" :files ("hsp-mode.el"))) (rainbow-mode) (csv-mode) (string-inflection) (dtrt-indent :disable t) (clang-format) (arduino-mode) (sed-mode) (kurecolor) (buffer-move) (lispy))
  (unpin "n/a")
  (elpa "n/a")))
</pre></details>

**Comment by hlissner** [comment]
Check \*Messages\* for errors/warnings after the failure. If you spot an error, [produce a backtrace from it](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#how-to-extract-a-backtrace-from-an-error). If not, [try to reproduce it in the sandbox](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#testing-in-dooms-sandbox). 

If it can be reproduced in vanilla Emacs, this is an issue with [projectile](https://github.com/bbatsov/projectile) and should be raised there.
