### ISSUE TITLE
Wrong UTF-8 character spacing when unicode is enabled

### ISSUE THREAD

**Issue by ronisbr** [hlissner/doom-emacs#4689]
**What did you expect to happen?**

With `unicode` disabled, all the unicode characters seems to have the same spacing:

<img width="710" alt="Captura de Tela 2021-02-24 às 17 06 06" src="https://user-images.githubusercontent.com/1068295/109059093-96c29680-76c2-11eb-9549-747f0ef2e5dd.png">

**What actually happened?**

When I enabled the `unicode`, I get this:

<img width="703" alt="Captura de Tela 2021-02-24 às 17 07 21" src="https://user-images.githubusercontent.com/1068295/109059213-c2de1780-76c2-11eb-9328-8dfef9987099.png">

Notice how the alignment has changed. All the other option remained the same.

The code to reproduce the problem is:

```
# Compute the SGP4 algorithm considering all variables in a state vector.
function _sgp4_si(Δt, sgp4_gc, epoch, r_TEME::AbstractVector, v_TEME::AbstractVector)
    orb_TEME = rv_to_kepler(r_TEME, v_TEME, epoch)

    # Obtain the required mean elements to initialize the SGP4.
    a₀ = orb_TEME.a/sgp4_gc.R0  # ......................... Semi-major axis [ER]
    e₀ = orb_TEME.e             # ............................. Excentricity [ ]
    i₀ = orb_TEME.i             # ............................ Inclination [rad]
    Ω₀ = orb_TEME.Ω             # ................................... RAAN [rad]
    ω₀ = orb_TEME.ω             # ........................ Arg. of perigee [rad]
    M₀ = f_to_M(e₀, orb_TEME.f) # ........................... Mean anomaly [rad]
```

**Comment by hlissner** [comment]
This is how the unicode-fonts package works, by mapping different fonts to different code points to cover as much of the unicode spec as possible. Please raise this [upstream](https://github.com/rolandwalker/unicode-fonts) instead. As this is not a Doom issue I will close it.

**Comment by ronisbr** [comment]
Oh I see, sorry then! Thanks for the detailed explanation.
