### ISSUE TITLE
Evil variable in the new magit tool module

### ISSUE THREAD

**Issue by UndeadKernel** [hlissner/doom-emacs#469]
### Observed behavior

The new magit module does not shield an "evil" variables from non evil users.

Line 11 of `tools/magit/config.el` reads:
``
 (push 'magit-repolist-mode evil-snipe-disabled-modes)
``

### Expected behavior
The variable `evil-snipe-disabled-modes` should only be referenced if evil is enabled.

P.S.: I love evil puns :D

**Comment by rphillips** [comment]
username checks out :)

**Comment by hlissner** [comment]
Whoops! My bad. Just pushed a fix to `develop`!
