### ISSUE TITLE
persistent delete-selection-mode

### ISSUE THREAD

**Issue by colormotor** [hlissner/doom-emacs#4694]
Hi, 

I have a recurring issue with `delete-selection-mode` getting disabling. 
This occurs in different modes, such as org (with jupyter), AuTex and C++.

I found one mention of this issue here:
<https://stackoverflow.com/questions/14954490/emacs-delete-selection-mode-disables-itself>
and it seems to be caused by an error occuring in the given mode.

I am wandering, is this issue common and is there a way to to set `delete-selection-mode` in the config, so it remains persistent also after errors?

**Comment by hlissner** [comment]
> I am wandering, is this issue common and is there a way to to set delete-selection-mode in the config, so it remains persistent also after errors?

By fixing the error. Look for errors in \*Messages\* (`SPC h e` or `C-h e` to open). [A backtrace will help you find the source](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#how-to-extract-a-backtrace-from-an-error).

**Comment by hlissner** [comment]
As this is not truly a Doom issue I will close this, but feel free to follow up here.
