### ISSUE TITLE
Format only modifications to current buffer

### ISSUE THREAD

**Issue by daniel-grumberg** [hlissner/doom-emacs#4698]
**Why tracking only modifications to the current buffer**
The crux of it is that reformatting the entire buffer has negative effects on version control history. The point is that you have to commit white-space changes to chunks of code you did not actually modify, In turn this leads to inaccurate history making the output of tools like git-blame less useful.

**How to implement this**
I am new to doom so I don't feel super comfortable jumping in with such a big change, any guidance would be appreciated. The plan would be to track changed lines in a similar way to ws-butler. Essentially, it would need to add hooks to `after-change-functions` and `before-revert-hook` and `after-revert-hook` to track the changes made to the buffer. When triggering a formatting operation, we can run the formatting tool on each edited region and replace the contents.

We could consolidate this infrastructure to tracking changed region to use with other things, like modifying ws-butler to using the same information as the format module.

Let me know if this is something you would be interested in having.

**Comment by hlissner** [comment]
Thanks for the suggestion, but I'm afraid Doom is not the authority in this space. This is a question you should raise upstream, to Emacs' community of formatter integration plugins (like [format-all](https://github.com/lassik/emacs-format-all-the-code) (which we currently use and may soon replace), [apheleia](https://github.com/raxod502/apheleia) (an alternative that I am eyeing), and so on. All Doom does is install and use them. This may even be a question for the formatters themselves (prettier, clang-format, etc). As far as I know very few of them support partial reformatting (most of them are designed with reformatting whole files -- sometimes whole projects -- as their primary use case. In any case, Doom plays no part in their development, so there is little I can offer to this conversion.

**Comment by daniel-grumberg** [comment]
Fair enough, I'll raise the issue upstream. FTR you definitely don't need LSP for this as most reformatting changes are very local and should be handled by the formatter. What I will suggest upstream is to use region reformatting capabilities when possible but the general solution is to reformat the whole buffer in a temporary buffer, do a diff with the original and apply the hunks where that intersect with the saved regions. Thanks for the help!

**Comment by daniel-grumberg** [comment]
I had a play with it and I understand what you mean, if the formatter itself doesn't understand range based formatting then it becomes impossible to soundly figure out what diffs should be (because approximating the relevant diffs is not ok in save hook). Nevertheless I implemented the feature privately for now and it works great with LSP for servers that support region based formatting. If you are interested in this for language servers that support range based formatting I am happy to contribute a patch. If upstream providers agree to support this to some degree I am happy to maintain the integrations.
