### ISSUE TITLE
Inspect "*straight-process*" buffer from doom CLI

### ISSUE THREAD

**Issue by haji-ali** [hlissner/doom-emacs#4699]
**Describe the feature**
This is also a potential bug-report but it's first and foremost a feature-request so that I can troubleshoot the error myself.

I think it would be great if there's a way to inspect the output of the buffer `*straight-process*` that is generated during the run of doom CLI. I have been trying to replace the auctex package with my own version, using 

```elisp
(unpin! auctex)
(package! auctex
  :recipe '(:host github
            :depth full
            :repo "haji-ali/auctex"
            :branch "tex-build-only"
            :pre-build
            (("./autogen.sh")
             ("./configure" "--without-texmf-dir" "--with-lispdir=.") ;; Use local directory
             ("make"))))
```

and I keep getting `Warning (straight): Failed to run "./autogen.sh"; see buffer *straight-process*`, but there's no way to see the buffer to troubleshoot the error is (If I use `use-package` in a running Emacs session everything works, so I can't figure out what the issue with Doom's `package!` and I can't troubleshoot it).

**System information**
<details><pre>
```
SYSTEM  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/zsh
        uname      Linux 5.4.0-65-generic #73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021 x86_64
        path       (~/perl5/bin ~/.cargo/bin ~/.local/share/texlive//bin/x86_64-linux ~/.local/bin ~/.local/opt/llvm/bin /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /usr/games /usr/local/games /snap/bin ~/.local/libexec/emacs/27.1/x86_64-pc-linux-gnu)
EMACS   dir        ~/Work/Projects/dotfiles/emacs/.emacs.d/
        version    27.1
        build      Sep 14, 2020
        buildopts  --prefix=/home/abdo/.local/ --with-json --with-modules --with-harfbuzz --with-compress-install --with-threads --with-included-regex --with-zlib --with-sound=alsa --without-gconf --with-mailutils --with-xft --with-xml2 --with-cairo --with-gconf --with-xwidgets --without-toolkit-scroll-bars 'CFLAGS=-O3 -mtune=native -march=native -fomit-frame-pointer -I/usr/lib/gcc/x86_64-linux-gnu/9/include/ -L/usr/lib/gcc/x86_64-linux-gnu/9'
        features   XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GCONF GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER LCMS2 GMP
        traits     (gui server-running)
DOOM    dir        ~/Work/Projects/dotfiles/emacs/.config/doom/
        version    2.0.9
        font       #<font-object -DAMA-Ubuntu Mono-normal-normal-normal-*-17-*-*-*-m-0-iso10646-1>
        theme      doom-one
        build      HEAD -> develop, _upgrade_develop e08c5f537 2021-02-07 23:57:44 -0500
        elc-files  0
        modules    (:completion ivy :ui doom hl-todo modeline window-select :emacs dired ibuffer undo :checkers spell :tools magit pdf :os tty :lang emacs-lisp (latex +latexmk) markdown yaml :email mu4e :config literate (default +bindings) :my-apps (&user org) (&user org-agenda) (&user email) (&user dired) (&user latex) (&user shell) (&user magit) :my-completion (&user ivy) :my-emacs (&user wind-mgmt) (&user paren))
        packages   ((hungry-delete) (openwith) (origami) (lsp-origami) (el-patch) (explain-pause-mode :disable t) (selectrum) (focus) (ace-jump-mode) (iedit) (aggressive-indent) (eglot) (flyspell-correct))
        unpin      (n/a)
        elpa       (n/a)
```
</pre></details>

**Comment by hlissner** [comment]
The CLI is [already designed to spit out the contents of straight's process buffer](https://github.com/hlissner/doom-emacs/blob/develop/core/core-cli.el#L258-L265) if a straight error occurs. If it doesn't emit anything, straight didn't produce any output.

In any case, this is covered by #4273 so I'll close this as a duplicate.

**Comment by haji-ali** [comment]
Thanks @hlissner, sorry if I should have discussed this issue in #4273

It is true that when an error occurs, the straight process buffer is printed. However, it seems that a warning by straight, which is what seems to happen when a build step fails, does not produce a similar output.

See the output below that I am getting once I have the `package!` statement that I included above (it is definitely weird that my "auctex" build commands seem to be called for other packages other than `auctex`, but that's why I want to inspect the content of `*straight-buffer*` to check what is happening).

<details><pre>
> Compiling your literate config...
  - Tangled 12 code blocks from config.org.yrEeDA
  - Restarting...
> Synchronizing your config with Doom Emacs...
  > Installing packages...
    - Checked out dired-git-info: b47f2b0c3a6cb9b7a62a4ee2605a492e512d40a9
    → Building dired-git-info...
Warning (straight): Failed to run "./autogen.sh"; see buffer *straight-process*
Warning (straight): Failed to run "./configure"; see buffer *straight-process*
Failed to run "make": make: *** No targets specified and no makefile found. Stop.
Warning (straight): Failed to run "make"; see buffer *straight-process*
    → Building dired-git-info...done
    - Checked out xclip: 2951c6b62b29780c7a35c64601a59999b83aa145
    → Building xclip...
Warning (straight): Failed to run "./autogen.sh"; see buffer *straight-process*
Warning (straight): Failed to run "./configure"; see buffer *straight-process*
Failed to run "make": make: *** No targets specified and no makefile found. Stop.
Warning (straight): Failed to run "make"; see buffer *straight-process*
    → Building xclip...done
    > Updating recipe repos...
    → Cloning auctex...s for emacsmirror-mirror...
    → Cloning auctex...done
    → Building auctex...
    → Building auctex...done
    - Checked out adaptive-wrap: 91e939b48a8129f696f45a7a3963fe09cbfa3a2d
    → Building adaptive-wrap...
Warning (straight): Failed to run "./autogen.sh"; see buffer *straight-process*
Warning (straight): Failed to run "./configure"; see buffer *straight-process*
Failed to run "make": make: *** No targets specified and no makefile found. Stop.
Warning (straight): Failed to run "make"; see buffer *straight-process*
    → Building adaptive-wrap...done
    → Building windresize...
Warning (straight): Failed to run "./autogen.sh"; see buffer *straight-process*
Warning (straight): Failed to run "./configure"; see buffer *straight-process*
Failed to run "make": make: *** No targets specified and no makefile found. Stop.
Warning (straight): Failed to run "make"; see buffer *straight-process*
    → Building windresize...done
    → Building jsonrpc...
Warning (straight): Failed to run "./autogen.sh"; see buffer *straight-process*
Warning (straight): Failed to run "./configure"; see buffer *straight-process*
Failed to run "make": make: *** No targets specified and no makefile found. Stop.
Warning (straight): Failed to run "make"; see buffer *straight-process*
    → Building jsonrpc...done
    → Building flymake...
Warning (straight): Failed to run "./autogen.sh"; see buffer *straight-process*
Warning (straight): Failed to run "./configure"; see buffer *straight-process*
Failed to run "make": make: *** No targets specified and no makefile found. Stop.
Warning (straight): Failed to run "make"; see buffer *straight-process*
    → Building flymake → Building eldoc...
Warning (straight): Failed to run "./autogen.sh"; see buffer *straight-process*
Warning (straight): Failed to run "./configure"; see buffer *straight-process*
Failed to run "make": make: *** No targets specified and no makefile found. Stop.
Warning (straight): Failed to run "make"; see buffer *straight-process*
    → Building flymake → Building eldoc...done
    → Building flymake...
    → Building flymake...done
    → Building project...
Warning (straight): Failed to run "./autogen.sh"; see buffer *straight-process*
Warning (straight): Failed to run "./configure"; see buffer *straight-process*
Failed to run "make": make: *** No targets specified and no makefile found. Stop.
Warning (straight): Failed to run "make"; see buffer *straight-process*
    → Building project → Building xref...
Warning (straight): Failed to run "./autogen.sh"; see buffer *straight-process*
Warning (straight): Failed to run "./configure"; see buffer *straight-process*
Failed to run "make": make: *** No targets specified and no makefile found. Stop.
Warning (straight): Failed to run "make"; see buffer *straight-process*
    → Building project → Building xref...done
    → Building project...
    → Building project...done
    ✓ Installed 10 packages
  > (Re)building packages...
    - No packages need rebuilding
  > Purging orphaned packages (for the emperor)...
    - No builds to purge
    - Skipping elpa packages
    - Skipping repos
    - Skipping regrafting
  > (Re)generating autoloads file...
    > Generating autoloads file...
    > Byte-compiling autoloads file...
    ✓ Generated .local/autoloads.27.1.elc
  - Restart Emacs or use 'M-x doom/reload' for changes to take effect
✓ Finished in 1m4s
</pre></details>
