### ISSUE TITLE
Magit buffers restored as blank buffers when I hit C-c w L

### ISSUE THREAD

**Issue by pashazz** [hlissner/doom-emacs#4703]
**Describe the feature**
I'd like to see a desktop-save-mode integration. I tried doom-emacs and it's great but the doom internal session mechanism won't allow me to save the window (frame) positions as well as some visited buffers, e.g. magit. I'd love to see a way of injecting this mode into doom-emacs configuration

**System information**
<details><pre>
```
SYSTEM  info       (MacOS  . Darwin 19.6.0 x86_64)
        shell      /bin/zsh
        path       (~/doom-emacs/bin/ /usr/local/opt/bison/bin ~/bin /opt/local/bin /usr/local/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /Applications/ApacheMaven3.6/bin /Applications/Emacs.app/Contents/MacOS/libexec/)
EMACS   dir        ~/.emacs.d/
        version    (27.1 2003451b61ad44108eedae74fc34b4d7b47d5756 Nov 22, 2020)
        buildopts  --with-mac --enable-mac-app=/Users/travis/build/railwaycat/homebrew-emacsmacport/build-scripts/emacs-source/tmproot --prefix=/Users/travis/build/railwaycat/homebrew-emacsmacport/build-scripts/emacs-source/tmproot --enable-mac-self-contained --with-modules
        features   NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS JSON PDUMPER LCMS2 GMP
        traits     (gui server-running envvar-file)
DOOM    dir        ~/.doom.d/
        version    (2.0.9 HEAD -> develop 3f4eccaec 2021-02-26 22:16:00 -0500)
        font       #<font-spec nil nil Monaco nil nil semi-light nil nil 15 nil nil nil nil>
        theme      tangotango
        modules    (:completion company ivy :ui deft doom doom-dashboard doom-quit hl-todo hydra minimap modeline ophints (popup +defaults) vc-gutter vi-tilde-fringe window-select :editor file-templates fold (format +onsave) snippets (&user history) :emacs dired electric ibuffer undo vc :checkers syntax :tools (eval +overlay) lookup lsp magit :os macos :lang emacs-lisp markdown org sh :app calendar :config (default +bindings +smartparens))
        packages   ((dashboard) (tangotango-theme) (reverse-im) (char-fold))
        unpin      (n/a)
        elpa       (n/a)
```

</pre></details>

**Comment by hlissner** [comment]
[Doom already falls back to desktop.el](https://github.com/hlissner/doom-emacs/blob/develop/core/autoload/sessions.el#L60-L62) when the `:ui workspaces` module is disabled. `C-c w L` (`doom/load-session`) invokes desktop in this case.

>  the doom internal session mechanism won't allow me to save the window (frame) positions

Then use this:

```elisp
;; add to ~/.doom.d/config.el
(when-let (dims (doom-store-get 'last-frame-size))
  (cl-destructuring-bind ((left . top) width height fullscreen) dims
    (setq initial-frame-alist
          (append initial-frame-alist
                  `((left . ,left)
                    (top . ,top)
                    (width . ,width)
                    (height . ,height)
                    (fullscreen . ,fullscreen))))))

(defun save-frame-dimensions ()
  (doom-store-put 'last-frame-size
                  (list (frame-position)
                        (frame-width)
                        (frame-height)
                        (frame-parameter nil 'fullscreen))))

(add-hook 'kill-emacs-hook #'save-frame-dimensions)
```

> as well as some visited buffers, e.g. magit

Neither can desktop.el. It and persp-mode are incapable of "saving" magit buffers or any special non-file-visiting buffer with a similarly specialized initialization process. `persp-mode` lets you write specialized handlers with `persp-def-buffer-save/load`. Desktop has no such facility.

----

As this is a feature request for a package Doom already uses, and the other issues are matters of configuration I will close this, but feel free to follow up here.

**Comment by pashazz** [comment]
> Neither can desktop.el. It and persp-mode are incapable of "saving" magit buffers or any special non-file-visiting buffer with a similarly specialized initialization process. `persp-mode` lets you write specialized handlers with `persp-def-buffer-save/load`. Desktop has no such facility.

Looks like persp can't as well: https://github.com/hlissner/doom-emacs/issues/3558#issuecomment-658427761
