### ISSUE TITLE
Fix lsp-ui-sideline-actions-icon for EMACS27+

### ISSUE THREAD

**Issue by pepperblue** [hlissner/doom-emacs#4704]
**What did you expect to happen?**
Icon is displayed in front of code-action

**What actually happened?**
No Icon is shown, error-message is: "[lsp-ui-sideline]: Error with actions icon: (error Invalid image specification)"

**Proposed solution:**
`lsp-ui-sideline-actions-icon` expects an icon-file so set it to `lsp-ui-sideline-actions-icon-default` in case of `EMACS27+`

**Comment by hlissner** [comment]
My bad! This was fixed in de924da. Thanks for bringing it to my attention!
