### ISSUE TITLE
keyboard macro does not record after escape

### ISSUE THREAD

**Issue by Luis-Henriquez-Perez** [hlissner/doom-emacs#471]
A keyboard macro stops recording after pressing `escape`, or more specifically, after calling `doom/escape`. This happens even when `doom-escape-hook` is nil. Interestingly, the macro still _seems_ as if it's recording correctly because it still messages "macro is recording" and "macro defined" at the right times.

To reproduce I used the following lines.

  (add-hook 'evil-replace-state-entry-hook #'turn-off-smartparens-mode)
  (add-hook 'evil-replace-state-exit-hook  #'turn-on-smartparens-mode)

I suspect any reproduction of the problem that makes some changes to text, uses `escape`, and makes some more changes before defining the keyboard macro will produce the bug. But he's what I specifically did to test it:

I used forward-char until I reach the `a` from add-hook and use `ciW` to change the word to `hi` and press `escape` then I do `forward-char` until I reach the `e` from `evil-replace-state-entry-hook` and change it to `bye` (still using `ciW`). Then I move to the second line with `evil-next-line` and use `0` to go to the beginning of the line and end the macro. Then try `@q` to execute it.

I get this result after executing the macro on the second line:

     (hi 'bye #'turn-off-smartparens-mode)
     (hi 'evil-replace-state-exit-hook  #'turn-on-smartparens-mode)

The second line should be:

     (hi 'bye  #'turn-on-smartparens-mode)

As you can see it executed everything up until I pressed escape.

Removing the `doom/escape` advice from `evil-force-normal-state` produced the expected results. 

One warning: I do not use DOOM, however I have the exact same code in my config for everything involving `doom/escape` (defining doom/escape and adding it as a hook for evil-force-normal-state). When I tested this the only difference between a working keyboard macro and non-working one was whether `evil-force-normal-state` was advised with `doom/escape` or not.

**Comment by Luis-Henriquez-Perez** [comment]
I've tried to debug this. I can't believe what I found. In the `void-escape`, when I change the last condition from `(t (keyboard-quit))` to `(t nil)`, it works. But this doesn't make any sense because in a keyboard macro, this condition should never be reached -- and it isn't reached because the keyboard macro is not aborted. However when I make this change and nothing else, it works.

    (defun doom/escape ()
      "Run the 'void-escape-hook'"
      (interactive)
      (cond
       ((minibuffer-window-active-p (minibuffer-window))
        ;; quit the minibuffer if open.
        (abort-recursive-edit))
       ;; run all escap ehooks
       ((run-hook-with-args-until-success 'doom-escape-hook))
       ;; don't abort macro
       (defining-kbd-macro nil)
       ;; back to the default
       ;; before  --> (t (keyboard-quit))
       (t nil)))

**Comment by hlissner** [comment]
I believe I've found the fix. Could you change `doom/escape`'s definition to:

```diff
 (defun doom/escape ()
   "Run the `doom-escape-hook'."
   (interactive)
   (cond ((minibuffer-window-active-p (minibuffer-window))
          ;; quit the minibuffer if open.
          (abort-recursive-edit))
         ;; Run all escape hooks. If any returns non-nil, then stop there.
         ((run-hook-with-args-until-success 'doom-escape-hook))
         ;; don't abort macros
-        (defining-kbd-macro nil)
+        ((or defining-kbd-macro executing-kbd-macro) nil)
         ;; Back to the default
         (t (keyboard-quit))))
```

And let me know if that resolves your issue. If so, I'll merge it into develop.

**Comment by Luis-Henriquez-Perez** [comment]
This works! Ah, I should have realized it was another macro variable.

**Comment by hlissner** [comment]
Excellent. It is now in develop! I'll leave this open until it hits master.
