### ISSUE TITLE
Add "skip" option for uncommited changes during update

### ISSUE THREAD

**Issue by rosekunkel** [hlissner/doom-emacs#4712]
**Describe the feature**
Currently, when `doom sync -u` encounters a package repo with uncommitted changes, it presents three options:
```
> Repository "some-repo" has a dirty worktree:
    
    M foo.el
    M bar.el

      1) Abort
      2) Stash changes
      3) Discard changes (Recommended)

  How to proceed? (1, 2, 3)
```
None of these options are convenient when actively working on that repo: your best option is to stash the changes, but then you have to re-apply them right after doing the update. It would be much more convenient if there were a fourth option:
```
4) Skip update for this repository
````
This option would simply leave the repository unchanged and continue to the next repository.

**System information**
<details><pre>
SYSTEM  info       ("Arch Linux" . Linux 5.10.18-hardened1-1-hardened x86_64)
	shell      /usr/bin/zsh
	path       (~/.local/share/pyenv/shims ~/.local/share/pyenv/shims ~/.local/share/pyenv/shims ~/.nix-profile/bin ~/.ghcup/bin ~/.config/emacs/bin ~/.local/bin /usr/local/sbin /usr/local/bin /usr/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /usr/lib/jvm/default/bin /usr/lib/jvm/default/bin /usr/lib/emacs/27.1/x86_64-pc-linux-gnu)
EMACS   dir        ~/.config/emacs/
	version    (27.1 Aug 28, 2020)
	buildopts  --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-wide-int --with-modules --with-cairo --with-harfbuzz 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
	features   XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP
	traits     (batch)
DOOM    dir        ~/.config/doom/
	version    (2.0.9 HEAD -> develop, origin/develop 88e18fc7c 2021-02-27 23:56:15 -0500)
	modules    (:completion (company +childframe) (&user selectrum) :ui doom doom-dashboard fill-column hl-todo (ligatures +pragmata-pro) (&user telephone-line) nav-flash ophints (popup +all +defaults) unicode vc-gutter vi-tilde-fringe (window-select +switch-window) workspaces :editor (evil +everywhere) file-templates fold format lispy rotate-text snippets word-wrap :emacs (dired +icons +ranger) electric (ibuffer +icons) undo vc :term vterm :checkers grammar (spell +aspell +everywhere) (syntax +childframe) :tools biblio debugger direnv editorconfig eval (lookup +dictionary +docsets +offline) (lsp +eglot) magit make prodigy rgb taskrunner (&user tree-sitter) :os tty :lang (cc +lsp) data emacs-lisp (haskell +dante) (javascript +lsp) (json +lsp) (latex +cdlatex +latexmk +lsp) (markdown +grip) nix (org +pandoc) (python +lsp +pyenv) (rust +lsp) scheme (sh +lsp) (&user systemd) (&user vue) web (yaml +lsp) :config (default +bindings +smartparens))
	packages   (n/a)
	unpin      (n/a)
	elpa       (n/a)
</pre></details>

**Comment by hlissner** [comment]
Moved to #4273.
