### ISSUE TITLE
minibuffer very chatty about python code

### ISSUE THREAD

**Issue by hoosierEE** [hlissner/doom-emacs#4714]
**What did you expect to happen?**
Minibuffer is quiet like before.

**What actually happened?**
Minibuffer contains lots of weird junk whenever I let my cursor sit on some python code for more than 1 second.

**Additional details:**

I am having a similar issue to #3242, but with *any* python code (not just in an org-babel code block). This started after adding `(setq org-babel-python-command "/opt/anaconda3/bin/python3")` to my doom/config.el file. Unfortunately, if I comment this setting out and reload Doom, the behavior does not go away.

![image](https://user-images.githubusercontent.com/4307625/109584098-f78d0d00-7ace-11eb-925b-cf95e9528c9d.png)

**Steps to reproduce:**
1. put this in doom/config.el: `(setq org-babel-python-command "/opt/anaconda3/bin/python3")`
2. reload doom
3. put cursor on python code
4. wait 1 second to see minibuffer text

**System information:**
<details>

```
SYSTEM  type       darwin
        config     x86_64-apple-darwin18.2.0
        shell      /bin/bash
        uname      Darwin 18.7.0 Darwin Kernel Version 18.7.0: Tue Jan 12 22:04:47 PST 2021; root:xnu-4903.278.56~1/RELEASE_X86_64 x86_64
        path       (~/bin ~/.emacs.d/bin ~/.local ~/.cargo /Applications/Racketv7.4/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /opt/X11/bin /Applications/Wireshark.app/Contents/MacOS /Applications/Emacs.app/Contents/MacOS/bin-x86_64-10_10 /Applications/Emacs.app/Contents/MacOS/libexec-x86_64-10_10 /Applications/Emacs.app/Contents/MacOS/libexec/)
EMACS   dir        ~/.emacs.d/
        version    26.2
        build      Apr 12, 2019
        buildopts  --with-ns '--enable-locallisppath=/Library/Application Support/Emacs/${version}/site-lisp:/Library/Application Support/Emacs/site-lisp' --with-modules
        features   NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS
        traits     (server-running envvar-file)
DOOM    dir        ~/.doom.d/
        version    2.0.9
        build      grafted, HEAD -> develop, origin/develop, origin/HEAD b3077c9 2020-08-28 04:34:56 -0400
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline ophints (popup +defaults) vc-gutter vi-tilde-fringe workspaces zen :editor (evil +everywhere) snippets :emacs dired electric undo vc :checkers syntax spell grammar :tools docker (eval +overlay) lookup magit :os macos :lang emacs-lisp latex markdown org :config (default +bindings +smartparens))
        packages   ((doom-snippets :ignore t) (color-identifiers-mode) (org-ref) (dockerfile-mode :recipe (:host github :repo spotify/dockerfile-mode)) (ox-ipynb :recipe (:host github :repo jkitchin/ox-ipynb)))
        unpin      (n/a)
        elpa       (n/a)
```
</details>

**Comment by hlissner** [comment]
I cannot reproduce this on 27.1 or 28.0.50, on NixOS, Arch, MacOS or Windows. 

1. You appear to be using a version of Doom dated `2020-08-28`. This is very old, considering Doom has seen thousands of updates and bugfixes in the past 5 months alone. Please update.
2. You don't have the `:lang python` module enabled, therefore Doom is not configuring python at all, so the issue must originate from one of your private packages or your private config. `ox-ipynb` is the only suspicious package I see.
3. You're on Emacs 26.2. I highly recommend you upgrade to Emacs 27.1. Doom will be dropping 26.x support later this year, and as of earlier this year, our minimum supported version is 26.3.

**Comment by hoosierEE** [comment]
Thanks for the quick reply. I'll reopen this if it persists after updating ... all that. :)
