### ISSUE TITLE
Mixed pitch font not being applied in org-mode after update

### ISSUE THREAD

**Issue by prasoon2211** [hlissner/doom-emacs#4729]
**What did you expect to happen?**
When I open an org file, I have a hook to turn on `writeroom-mode`. Because of this, `mixed-pitch` mode automatically gets called (see`:ui zen`) and should enable mixed-pitch mode. This should use the `doom-variable-pitch-font` (in my case, `ETBembo`) for the text

**What actually happened?**
Writeroom mode turns on correctly but emacs is using `doom-font` instead of `doom-variable-pitch-font`, presumably because `mixed-pitch-mode` ins't being applied correctly.

**Additional details:**
- This happened after I ran `doom upgrade` yesterday
- My config hasn't changed
- After some debugging, I think I've established that removing the call to `text-scale-set` solves this issue
    - I did this by removing zen mode and manually adding back writeroom mode and mixed pitch mode in my `config.el`
    - Then, I tried to replicate zen mode by copying the config
    - As soon as I call `text-scale-set` in the org-mode hook, I see this problem
    - Similarly, then I turned on zen mode but went in the `config.el` in zen model and commented out the `text-scale-set` function. This also fixes the problem (text is too small though)
- The problem only happens if I do text scaling in a hook. If I call it interactively after opening the org-mode buffer, the text size increases without any problems
- `mixed-pitch-mode` seems to stay on - calling `mixed-pitch-mode` from `M-x` first displays a message saying `mixed-pitch-mode disabled` and then, when calling it again, I get the message `mixed-pitch-mode enabled`.

**Steps to reproduce:**
1. Update to latest doom emacs
2. Turn on zen mode
3. Set
```
(setq doom-font (font-spec :family "Fira Code" :size 14 :weight 'semi-light)
      doom-variable-pitch-font (font-spec :family "ETBembo" :size 15))
```
4. Add writeroom-mode to org-mode hook
5. Open an org file (see screenshots)

**System information:**
doom info throws an error: `helm-M-x-execute-command: Symbol’s value as variable is void: distro`
I'm on MacOS Big Sur. Using Emacs 27.1
`doom version` : `Doom v2.0.9 (HEAD -> develop d5019f0b5 2021-03-02 23:48:54 -0500`

**Screenshots**
1. How it looks when I open an org-file:
![image](https://user-images.githubusercontent.com/2565248/109980824-9b113400-7d00-11eb-91c6-411a4caa5b82.png)

2. How it should look (I manually disable and enable mixed-pitch mode)
![image](https://user-images.githubusercontent.com/2565248/109981075-d875c180-7d00-11eb-956e-bb1a3360849a.png)

3. How this same image looks if I cooment-out `text-scale-set` from the doom files in `.emacs.d/modules/ui/zen/config.el`, then restart emacs, and open an org file (basically, scaling doesn't happen so text is small):
![image](https://user-images.githubusercontent.com/2565248/109981451-373b3b00-7d01-11eb-8526-a2a87f6eec77.png)

**Comment by hlissner** [comment]
I cannot reproduce this. Please update Doom, then check \*Messages\* for errors or warnings after activating `mixed-pitch-mode`.

That you have to toggle `mixed-pitch-mode` again, to get it to work, indicates that an error occurred when zen mode was first activated. Any error can short circuit elisp is unpredictable ways.

**Comment by TS-CUBED** [comment]
I had a similar issue. I narrowed it down to two things (both break it):

1. I had a non-doom theme (base16 theme)
2. I have a :custom-face section in my use-package! org config (have tried this and a custom-set-faces section) 

Both break the mixed/variable pitch mode in org (and seemingly in doom emacs in general). Both worked before the last upgrade.

For now I have disabled both and get the correct mixed mode in both org-mode and writeroom mode, but have not found a way to change the faces ouside of `changing doom-variable-pitch-font`

**Comment by prasoon2211** [comment]
@TS-CUBED Didn't fix it for me 😞

I was using `doom-nord-light` theme which I removed (so using the default theme now) and I also removed the call to `(doom-themes-org-config)`. Further, I removed all `custom-set-face` calls and deleted my `custom.el` file. My org mode config now looks like:
```
(use-package! org
  :hook
  (org-mode . writeroom-mode)
)
```
And still, while `writeroom-mode` gets enabled, `mixed-pitch` fonts don't seem to be applied even though I can see `mixed-pitch` in the minor modes. I see no errors in `*Messages*` so I enabled `toggle-debug-on-error` and switching to `org` buffers doesn't show a traceback so I'm assuming there are no errors

**Comment by hlissner** [comment]
This may be due to `solaire-mode`, which remaps faces. Many themes don't support it like Doom's themes do.

Disable the solaire-mode package with: 

```lisp
;; ~/.doom.d/packages.el
(package! solaire-mode :disable t)
```

Then `doom sync` and restart Emacs.

**Comment by dm19** [comment]
I'm seeing the same the issue with doom-dark+, which of course does support solaire-mode. After enabling variable-pitch mode in an org file I have to toggle solaire-mode off and on to get the font to change. This happens whether or not I have custom faces set.

I'm using the emacs 28 pgtk+native-comp package from AUR.

**Comment by hlissner** [comment]
@dm19 Try `(add-hook 'mixed-pitch-mode-hook #'solaire-mode-reset)`
