### ISSUE TITLE
Aborting a org-roam-capture-ref still saves the file

### ISSUE THREAD

**Issue by seanfarley** [hlissner/doom-emacs#4733]
**What did you expect to happen?**
Pressing `C-c C-k` when capturing an org-ref (e.g. from a browser using org protocol) to not create an empty org-roam file.

**What actually happened?**
Empty org-roam file was created.

**Additional details:**
It seems [org-roam #310](https://github.com/org-roam/org-roam/issues/310) they added some logic via `org-capture-after-finilize-hook`. So far, so good. I noticed that even when I abort, though, I'm still getting that behavior. After some digging around, it appears the culprit is `+popup--delete-window`'s logic that accidentally saves the buffer since there is `buffer-file-name` associated with this org capture popup. Below is a stack trace, if you're interested.

<details><pre>

  (let ((modp (buffer-modified-p)) (make-backup-files (or (and make-backup-files (not (eq arg 0))) (memq arg '(16 64))))) (and modp (memq arg '(16 64)) (setq buffer-backed-up nil)) (if (and modp (buffer-file-name) (not noninteractive) (not save-silently)) (message "Saving file %s..." (buffer-file-name))) (basic-save-buffer (called-interactively-p 'any)) (and modp (memq arg '(4 64)) (setq buffer-backed-up nil)))
  save-buffer()
  (save-current-buffer (set-buffer buffer) (save-buffer))
  (and (or (buffer-file-name buffer) (let* ((base-buffer (and t (buffer-base-buffer buffer)))) (if base-buffer (buffer-file-name base-buffer) nil))) (buffer-modified-p buffer) (let ((autosave (+popup-parameter 'autosave window))) (cond ((eq autosave 't)) ((null autosave) (y-or-n-p "Popup buffer is modified. Save it?")) ((functionp autosave) (funcall autosave buffer)))) (save-current-buffer (set-buffer buffer) (save-buffer)))
  (let ((buffer (window-buffer window)) (inhibit-quit t)) (and (or (buffer-file-name buffer) (let* ((base-buffer (and t (buffer-base-buffer buffer)))) (if base-buffer (buffer-file-name base-buffer) nil))) (buffer-modified-p buffer) (let ((autosave (+popup-parameter 'autosave window))) (cond ((eq autosave 't)) ((null autosave) (y-or-n-p "Popup buffer is modified. Save it?")) ((functionp autosave) (funcall autosave buffer)))) (save-current-buffer (set-buffer buffer) (save-buffer))) (let ((ignore-window-parameters t)) (let* ((wconf (and t (window-parameter window 'saved-wconf)))) (if wconf (set-window-configuration wconf) (delete-window window)))) (if (window-live-p window) nil (save-current-buffer (set-buffer buffer) (set-buffer-modified-p nil) (+popup-buffer-mode -1) (if +popup--inhibit-transient nil (let ((ttl (+popup-parameter ... window))) (if (eq ttl 't) (progn (setq ttl ...))) (cond ((null ttl)) ((functionp ttl) (funcall ttl buffer)) ((not ...) (signal ... ...)) ((= ttl 0) (+popup--kill-buffer buffer 0)) ((add-hook ... ... nil t) (setq +popup--timer ...))))))))
  +popup--delete-window(#<window 357 on CAPTURE-20210304170401-aborting_a_capture_should_not_leave_an_empty_file_issue_310_org_roam_org_roam.org>)
  delete-window(#<window 357 on CAPTURE-20210304170401-aborting_a_capture_should_not_leave_an_empty_file_issue_310_org_roam_org_roam.org>)
  window--delete(#<window 357 on CAPTURE-20210304170401-aborting_a_capture_should_not_leave_an_empty_file_issue_310_org_roam_org_roam.org> t t)
  replace-buffer-in-windows(#<buffer CAPTURE-20210304170401-aborting_a_capture_should_not_leave_an_empty_file_issue_310_org_roam_org_roam.org>)
  kill-buffer(#<buffer CAPTURE-20210304170401-aborting_a_capture_should_not_leave_an_empty_file_issue_310_org_roam_org_roam.org>)
  apply(#f(compiled-function (&optional stay-with-capture) "Finalize the capture process.\nWith prefix argument STAY-WITH-CAPTURE, jump to the location of the\ncaptured item after finalizing." (interactive "P") #<bytecode 0x1fe49500c841>) nil)
  org-capture-finalize()
  org-capture-kill()
  funcall-interactively(org-capture-kill)
  call-interactively(org-capture-kill nil nil)
  ad-Advice-command-execute(#f(compiled-function (cmd &optional record-flag keys special) "Execute CMD as an editor command.\nCMD must be a symbol that satisfies the `commandp' predicate.\nOptional second arg RECORD-FLAG non-nil\nmeans unconditionally put this command in the variable `command-history'.\nOtherwise, that is done only if an arg is read using the minibuffer.\nThe argument KEYS specifies the value to use instead of (this-command-keys)\nwhen reading the arguments; if it is nil, (this-command-keys) is used.\nThe argument SPECIAL, if non-nil, means that this command is executing\na special event, so ignore the prefix argument and don't clear it." #<bytecode 0x42dd91a9>) org-capture-kill)
  apply(ad-Advice-command-execute #f(compiled-function (cmd &optional record-flag keys special) "Execute CMD as an editor command.\nCMD must be a symbol that satisfies the `commandp' predicate.\nOptional second arg RECORD-FLAG non-nil\nmeans unconditionally put this command in the variable `command-history'.\nOtherwise, that is done only if an arg is read using the minibuffer.\nThe argument KEYS specifies the value to use instead of (this-command-keys)\nwhen reading the arguments; if it is nil, (this-command-keys) is used.\nThe argument SPECIAL, if non-nil, means that this command is executing\na special event, so ignore the prefix argument and don't clear it." #<bytecode 0x42dd91a9>) org-capture-kill)
  command-execute(org-capture-kill)

</pre></details>

**Steps to reproduce:**
1. Enable `org-roam`
2. Run `emacsclient "org-protocol://roam-ref?template=r&ref=https%3A%2F%2Fgithub.com%2Fsprig%2Forg-capture-extension&title=sprig%2Forg-capture-extension3A%20A%20Chrome%20and%20firefox%20extension%20facilitating%20org-capture%20in%20emacs&body=asdf-foo"`
3. Cancel the capture, `C-c C-k`
4. Observer the org-roam note was still created.

**System information:**
N.B. stack trace when running but I'm on MacOS Big Sur, Emacs 27.1 (stack trace below)
<details><pre>
x There was an unexpected error
  Message: Symbol's value as variable is void
  Data: (void-variable . distro)
  Backtrace:
    (eq distro 'windows)
    (cond ((eq distro 'windows) (format "Windows %s" "Unknown")) ((eq distro '
    (let ((disto (doom-system-distro))) (cond ((eq distro 'windows) (format "W
    (progn (fset #'sh vnew) (ignore sh) (let ((disto (doom-system-distro))) (c
    (unwind-protect (progn (fset #'sh vnew) (ignore sh) (let ((disto (doom-sys
    (let* ((vnew #'(lambda (&rest args) (cdr (apply #'doom-call-process args))
    (let ((sh (symbol-function #'sh))) (let* ((vnew #'(lambda (&rest args) (cd
    (doom-system-distro-version)
    (cons (doom-system-distro-version) (sh "uname" "-msr"))
    (cons 'info (cons (doom-system-distro-version) (sh "uname" "-msr")))
! Extended backtrace logged to .local/doom.error.log
</pre></details>

**Comment by hlissner** [comment]
See if this fixes the issue:

```elisp
(after! org-capture
  (set-popup-rule! "^CAPTURE-.*\\.org$" :size 0.25 :quit nil :select t))
```

Please test it with vanilla org-capture targets, in case it breaks those.

**Comment by seanfarley** [comment]
This seems to work :-) Now it prompts me `Popup buffer is modified. Save it? (y or n) n`, is that expected?

Vanilla org-capture seems to work but I'm not sure what I should be testing besides `C-c C-k`.

**Comment by seanfarley** [comment]
Ah, I just needed to add `:autosave 'ignore` to the rule. That does seem indeed to fix the behavior; shall I make a PR to add this to the `org-roam` doom configuration?

**Comment by hlissner** [comment]
That's fine; I was already on a Doom commit spree, one more won't hurt. With 08de185 this should be fixed. Let me know if that isn't the case and I'll reopen it. Thanks for the help!

**Comment by seanfarley** [comment]
Woo! 🎉
