### ISSUE TITLE
Problem during Doom upgrade

### ISSUE THREAD

**Issue by ujjwal3067** [hlissner/doom-emacs#4740]
I tried Doom upgrade today and this popped up. Not sure which option to choose
![Screen Shot 2021-03-05 at 8 49 42 PM](https://user-images.githubusercontent.com/28984548/110191142-ec025480-7df4-11eb-9e5e-92950129c7d9.png)

**Comment by hlissner** [comment]
How about the one that says "(Recommend)"?

**Comment by ujjwal3067** [comment]
> How about the one that is in green and says "(Recommended)"?

lol I completely skimmed over recommended part , smh. 
my bad
thanks for help. appreciate it

**Comment by ujjwal3067** [comment]
- Did the recommended part and got this error 
![Screen Shot 2021-03-05 at 9 22 25 PM](https://user-images.githubusercontent.com/28984548/110191875-e3138200-7df8-11eb-8e68-0af452c1e8c3.png)

**Comment by hlissner** [comment]
This appears to be a git error. You'll just have to try the command again. If you can't get past that, try deleting `~/.emacs.d/.local/straight/repos/rtags` manually, then try again.

**Comment by ujjwal3067** [comment]
works ! I deleted manually. 
Thanks for help @hlissner
