### ISSUE TITLE
How to configure find-file to display in floating box style？

### ISSUE THREAD

**Issue by iT-Boyer** [hlissner/doom-emacs#4741]
![截屏2021-03-06 上午10 24 09](https://user-images.githubusercontent.com/4022953/110192008-98c8ea00-7e66-11eb-8aa7-aa0916155a2e.png)

**Comment by hlissner** [comment]
See the `+childframe` flag in https://github.com/hlissner/doom-emacs/blob/develop/modules/completion/ivy/README.org#module-flags
