### ISSUE TITLE
recentf fails if org-agenda is the first visited buffer: "Defining as dynamic an already lexical var"

### ISSUE THREAD

**Issue by kuba-orlik** [hlissner/doom-emacs#4745]
Open Dom Emacs, run `C-c n a` to open an org agenda, pick an agenda view.

**What did you expect to happen?**

I expected the agenda view to open

**What actually happened?**
An error pops up: "Defining as dynamic an already lexical var". Here's the backtrace: https://pastebin.com/yVpmKRKZ

**Additional details:**
- Include a link to your private config: https://git.kuba-orlik.name/kuba/doom-emacs-config
- Include screenshots/casts of your issue: https://video.kuba-orlik.name/videos/watch/12d44c8e-0ead-4e6b-a914-0c24a46d10c2
- If you mention key sequences, include what commands they're bound to: `C-c n a` is bound to `org-agenda`

**Steps to reproduce:**
1. Open Doom Emacs
2. Open org-agenda without visiting any other buffers
3. See error
4. Close Doom Emacs again
5. Now run recentf first
6. Open org-agenda now
7. No error

**System information:**

I can't run `doom/info`, as it throws another error: `format: Wrong type argument: listp, unpin`, with backtrace: https://pastebin.com/RUEcVXxC

I'm running GNU Emacs 28.0.50, native-comp

**Comment by hlissner** [comment]
Found the issue and fixed it in 5069d95. Let me know if that isn't the case and I'll reopen this. Thanks for bringing it to my attention, and for the detailed bug report!

> I can't run doom/info, as it throws another error: format: Wrong type argument: listp, unpin, with backtrace: https://pastebin.com/RUEcVXxC

Please update Doom. This was fixed within the last 24 hours.
