### ISSUE TITLE
Magit opens with a vertical split on home page

### ISSUE THREAD

**Issue by azy2** [hlissner/doom-emacs#475]
### Steps to reproduce

1. Open emacs (maximized)
2. SPC g S
3. Navigate to and open any git repo on your sytsem

### Observed behavior

Magit opens with a vertical split (that is it takes up the bottom half of the frame)

### Expected/desired behavior

I would prefer magit to open with a horizontal split (that is I want it to take up the right half of the frame)

### System information
My config can be found here: https://github.com/azy2/doom-emacs-private in-case this is my fault.

Any help would be appreciated.

**Comment by fuxialexander** [comment]
That's the default setting. To open with horizontal split, add the following to your config:
```lisp
(set! :popup "^.*magit" '((slot . -1) (side . right) (size . 80)) '((modeline . nil) (select . t)))
  (set! :popup "^\\*magit.*popup\\*" '((slot . 0) (side . right)) '((modeline . nil) (select . t)))
  (set! :popup "^.*magit-revision:.*" '((slot . 2) (side . right) (window-height . 0.6)) '((modeline . nil) (select . t)))
  (set! :popup "^.*magit-diff:.*" '((slot . 2) (side . right) (window-height . 0.6)) '((modeline . nil) (select . nil)))
```
You can tweak the `size` (window width) to the value you want.

**Comment by jcf** [comment]
Will the above snippet help with Magit popping up alongside a Cider REPL buffer (they are implemented with the custom popup code in Doom believe?).

![2018-03-24-15 18 37-ad0590676fcc](https://user-images.githubusercontent.com/18374/37865597-a6b1af72-2f76-11e8-90e9-4147abfee209.png)

Magit is unusable at this size for me. Closing the Cider REPL window and running `magit-status` again fixes things with Magit showing up in one of my other splits.

**Comment by hlissner** [comment]
A small tweak to @fuxialexander's rules should do the trick:

```elisp
(set! :popup "^.*magit" '((slot . -1) (vslot . 1) (side . right) (size . 80)) '((select . t)))
(set! :popup "^\\*magit.*popup\\*" '((slot . 0) (vslot . 1) (side . right)) '((select . t)))
(set! :popup "^.*magit-revision:.*" '((slot . 2) (vslot . 1) (side . right) (window-height . 0.6)) '((select . t)))
(set! :popup "^.*magit-diff:.*" '((slot . 2) (vslot . 1) (side . right) (window-height . 0.6)) '((select)))
```

The property to pay attention to is `vslot`, which determines where (vertically) the popup is opened. vslot defaults to `0`, and any two popups with the same vslot will be shown side-by-side, like you are seeing. A higher vslot means "further away from the center of the frame", and a lower vslot (including negative numbers) means "closer to the center of the frame".

Hope that helps!

**Comment by UndeadKernel** [comment]
I believe the latest magit update changed the name of some buffers and removed the "*" in the names.
If running the latest magit, you might need these rules instead:
```lisp
(set! :popup "magit" '((slot . -1) (vslot . 1) (side . right) (size . 80)) '((select . t)))
```

Notice that `^.*magit` has changed to `"magit"`. You might need to adapt more names.

**Comment by fuxialexander** [comment]
@UndeadKernel `^.*magit` should works, the `*` here is not a escaped `\\*`, it's for greedy matching.

**Comment by missy187** [comment]
Whats the attraction of constantly administering and not letting me have
control of my everyday personal happenings. All of you fuck off. 😊

**Comment by hlissner** [comment]
@azy2 Can I consider this issue resolved?

**Comment by azy2** [comment]
Yes! Thanks everyone for the help.
