### ISSUE TITLE
pdf-tools isearch no highlighting

### ISSUE THREAD

**Issue by michaelmyc** [hlissner/doom-emacs#4750]
`isearch-forward` is only highlighting as the word is typed in, but not when the search entry is submitted. When I press enter and browse to the different occurrences with `n` or `N`, the pdf focuses on the relevant area but does not highlight found entries.

**What did you expect to happen?**
Matching entries should be highlighted just like when I was typing in the search term. 

**What actually happened?**
No highlighting. 

**Additional details:**
Related issue in pdf-tools: https://github.com/politza/pdf-tools/issues/654

Default doom [init file](https://github.com/hlissner/doom-emacs/blob/235c386368f0814671131d0d77e32be450c92cbc/init.example.el) with `tools:pdf` enabled is sufficient to reproduce this issue. 

**Steps to reproduce:**
1. Open any pdf file
2. Search with "/"
3. Type any search term, you will see matching words being highlighted
4. Hit "RET", highlighting disappears
5. Hit either "n" or "N" to navigate to other searches, the screen focus changes, but no highlighting. 

**System information:**
There seems to be a bug and it's complaining `list: Args out of range: "", 0, 9` when I run `M-x doom/info`.

**Comment by hlissner** [comment]
As of fe6981b we've switched to the latest commit of vedang/pdf-tools (we were on [a PR for the original politza/pdf-tools](https://github.com/politza/pdf-tools/pull/588) before then, which is a dozen or so commits behind).

Let me know if this fixes the issue.

**Comment by brabalan** [comment]
I’ve given it a try and it does not fix the issue. Highlighting disappears as soon as the `enter` key is hit.

**Comment by hlissner** [comment]
> I’ve given it a try and it does not fix the issue. Highlighting disappears as soon as the `enter` key is hit.

Isn't that how isearch is supposed to work? If you want to traverse the matches, `C-s` to invoke isearch, then keep pressing `C-s` (or `C-S-s`) until you find the match you want. Pressing RET ends the isearch.

This is how isearch functions in vanilla Emacs.

**Comment by hlissner** [comment]
Perhaps the expectation here is that isearch function like evil-search and persist highlights? If so, ywhjou'd have to request that upstream.

Otherwise, try `M-s o` to invoke a more "permanent" search (results are displayed in an occur buffer).

**Comment by michaelmyc** [comment]
The `doom/info` command still doesn't seem to work after `doom upgrade`. It's now complaining `format: Wrong type argument: listp, unpin`.

**Comment by brabalan** [comment]
> Isn't that how isearch is supposed to work? If you want to traverse the matches, `C-s` to invoke isearch, then keep pressing `C-s` (or `C-S-s`) until you find the match you want. Pressing RET ends the isearch.

In this case I can confirm it’s working as expected. Highlighting remains visible. (I was in a vi state of mind when trying this, doing a `/stringRET` followed by `n` to go to next match.)
