### ISSUE TITLE
How to get org-agenda/org-capture to prefer split-window-right

### ISSUE THREAD

**Issue by ustcpxy** [hlissner/doom-emacs#476]
Although I have used `
(setq  split-width-threshold 0)`, the agenda view buffer is still split horizontally like below. but I prefer to split things vertically (new window on the right). 

![screenshot_2018-03-24_11-15-36](https://user-images.githubusercontent.com/11225919/37859905-6ae9d610-2f56-11e8-902a-a8d66e09333c.png)
 below is the current info:
```
(list split-height-threshold split-width-threshold)
    ⇒ (80 0)

(list (window-height) (window-width))
    ⇒ (38 116)
````

**Comment by hlissner** [comment]
This is the work of the `:feature popup` module, which tries to unify the behavior of popups in Emacs.

The rule affecting \*Agenda Commands\* popups is:

```elisp
(set! :popup "^ ?\\*\\(?:Agenda Com\\|Calendar\\|Org \\(?:Links\\|Export Dispatcher\\|Select\\)\\)"
  '((slot . -1) (vslot . -1) (size . +popup-shrink-to-fit))
  '((transient . 0)))
```

To get it to pop up on the right, you'll want to add something like this to your private config to override the above:

```elisp
(set! :popup "^ \\*Agenda Com"
  '((side . right) (size . +popup-shrink-to-fit))
  '((transient . 0)))
```

**Comment by ustcpxy** [comment]
Hi hlissner,
Thanks for your quickly reply. 
I add the code to my private config, but it takes no affect. (I aslo make the doom-emacs again)

**Comment by hlissner** [comment]
Ah, my bad. It needs to be defined _after_ org loads, i.e.

```elisp
(after! org
  (set! :popup "^ \\*Agenda Com"
    '((slot . -1) (vslot . -1) (size . +popup-shrink-to-fit) (side . right))
    '((transient . 0))))
```

**Comment by ustcpxy** [comment]
Thanks. it works well now.

**Comment by hlissner** [comment]
Since this issue has been referred to by new users, and we've since replaced the popup API, i've hidden all of my obsolete answers. Here is the up-to-date answer)

```elisp
(after! org
  (set-popup-rule! "^ \\*Agenda Com"
    :slot -1 :vslot -1 :size #'+popup-shrink-to-fit :side 'right :ttl 0))
```
