### ISSUE TITLE
piping a line to xclip with ex evil commands freezes emacs

### ISSUE THREAD

**Issue by honestSalami** [hlissner/doom-emacs#4765]
**What did you expect to happen?**
the current line would be piped to the X11 clipboard, and I would continue editing my files normally.

**What actually happened?**
the current line was indeed piped, but emacs froze, and did not respond to any command. Emacs had to be sigtermed and started manually.

**Additional details:**

the command was ```:.!xclip```, using evil mode. No warnings were issued, no errors either.

**Steps to reproduce:**
open any file with default configuration and evil
go to any line
run ```:.!xclip```
see emacs freeze.

**System information:**

https://pastebin.com/h2yWVfPr

**Comment by honestSalami** [comment]
I got emacs to unfreeze by typing ```C-g```, but the selected line is deleted. I expected the command to just run and exit, without needing any further input.

I suspect this is more of an issue with evil than doom specifically, but I don't know where else to post this.

**Comment by hlissner** [comment]
I can reproduce this [in vanilla Emacs + evil](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#testing-in-dooms-sandbox), so this is an issue with evil. Please raise this [upstream](https://github.com/emacs-evil/evil).

**Comment by honestSalami** [comment]
Thanks so much!

**Comment by honestSalami** [comment]
to anyone who has this same problem: ```xsel -bio``` behaves as expected. So ```xclip``` interacting with emacs is the problem.

from an ex command, run:
```:.!xsel -bio```
and the line will be copied to the x-clipboard, and piped back to the line.
