### ISSUE TITLE
Not able to add remote projects to projectile-known-projects anymore

### ISSUE THREAD

**Issue by prashantvithani** [hlissner/doom-emacs#4768]
**What did you expect to happen?**
`(projectile-add-known-project "/ssh:user@host:/path/to/project")` should add the project to the list of known projects (`projectile-known-projects`).

**What actually happened?**
Because of the changes introduced in f8d181a8c41b1858c4a082ef0c7f2b07d1b96723, any project from remote host is now ignored. All my projects are in the remote container and I access the projects through TRAMP which is now not working as expected.

I feel there should be a flag that suggests whether to ignore remote projects or not. Any thoughts?

**System information:**
https://pastebin.com/kAtFQjtx

**Comment by hlissner** [comment]
7870350 should resolve your issue. Sorry for the trouble and thanks for bringing it to my attention.

**Comment by prashantvithani** [comment]
Oh, I thought that change was intended. Thanks for fixing it :)
