### ISSUE TITLE
I can export Latex and Html but not pdf

### ISSUE THREAD

**Issue by iT-Boyer** [hlissner/doom-emacs#4776]
I can export Latex and Html but not pdf:
```sh
Processing LaTeX file 20210306164202-碎片化的知识付费和学习能力.tex...
zsh:1: command not found: pdflatex [3 times]
org-compile-file: File "/Users/jhmac/ResilioSync/org/org-roam/20210306164202-碎片化的知识付费和学习能力.pdf" wasn’t produced.  See "*Org PDF LaTeX Output*" for details
```

**Comment by hlissner** [comment]
> zsh:1: command not found: pdflatex

It can't find the `pdflatex` program. Install it through your OS package manager.

> See "*Org PDF LaTeX Output*" for details

Did you **see "*Org PDF LaTeX Output*" for details**?

---

[**Please do not ignore the server template in the future.**](https://www.deepl.com/translator#en/zh/*Please%20do%20not%20ignore%20the%20server%20template%20in%20the%20future)

**Comment by iT-Boyer** [comment]
I'm very sorry for being confused by the question and failing to comply with the norms.

I install pdflatex by use `brew install basictex`:
```
which pdflatex
/Library/TeX/texbin/pdflatex
``
but this issue still exist。

I don't know how to find this "Org PDF LaTeX Output" log information. :-(

**Comment by iT-Boyer** [comment]
I'm very sorry for being confused by the question and failing to comply with the norms.

I install pdflatex by use `brew install basictex`:
```
which pdflatex
/Library/TeX/texbin/pdflatex
``
but this issue still exist。

I don't know how to find this "Org PDF LaTeX Output" log information. :-(
