### ISSUE TITLE
`doom info` emits "wrong-type-argument: listp" error

### ISSUE THREAD

**Issue by cxb811201** [hlissner/doom-emacs#4777]
**What did you expect to happen?**
`doom info` executed successfully

**What actually happened?**
`doom info` executed error

**Additional details:**
https://pastebin.com/6F5dRKyQ

**Comment by hlissner** [comment]
As of abec863 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
