### ISSUE TITLE
doom sync stuck

### ISSUE THREAD

**Issue by cxb811201** [hlissner/doom-emacs#4778]
**What did you expect to happen?**
doom sync executed successful

**What actually happened?**
When I used the Emacs version compiled by the `native-comp` branch, the execution of `doom sync` stuck.
I looked at the Emacs process and saw that it couldn't finish compiling `magit`
After I delete `doom--straight-inject-load-path-a` in `core-cli.el` file,  follow the steps below to execute `doom sync` successfully

**Additional details:**
- My private [config](https://github.com/cxb811201/.doom.d)
- Emacs process info
```
  70735 pts/275  Ssl+   0:02 /usr/bin/emacs --batch -l /tmp/emacs-async-comp-git-commit-oCru3P.el
  70737 pts/277  Ssl+   0:01 /usr/bin/emacs --batch -l /tmp/emacs-async-comp-magit-sA7ooK.el
  72007 pts/276  Ssl+   0:01 /usr/bin/emacs --batch -l /tmp/emacs-async-comp-magit-worktree-pYy48V.el
  72008 pts/278  Ssl+   0:01 /usr/bin/emacs --batch -l /tmp/emacs-async-comp-magit-wip-HX58P4.el
  72010 pts/280  Ssl+   0:01 /usr/bin/emacs --batch -l /tmp/emacs-async-comp-magit-transient-YsijtJ.el
  72011 pts/281  Ssl+   0:02 /usr/bin/emacs --batch -l /tmp/emacs-async-comp-magit-tag-SC9RrZ.el
  72012 pts/282  Ssl+   0:01 /usr/bin/emacs --batch -l /tmp/emacs-async-comp-magit-subtree-hhQjfx.el
  72036 pts/1    Ssl+   0:01 /usr/bin/emacs --batch -l /tmp/emacs-async-comp-magit-submodule-GMfiVE.el
- Output message
     Building pkgbuild-mode...
     Building pkgbuild-mode...done
     Waiting for 2354 async jobs...
```

**Steps to reproduce:**
1. Delete eln cache directory, ,
2. Delete build-28.0.50 directory under straight,
3. Exec `doom sync`.

**System information:**
...

**Comment by hlissner** [comment]
> After I delete doom--straight-inject-load-path-a in core-cli.el file, follow the steps below to execute doom sync successfully

But does `doom build` run successfully after removing it?

**Comment by zauster** [comment]
Had the same problem, is fixed for me now. Thanks a bunch!

**Comment by cxb811201** [comment]
@hlissner After deleting doom--straight-inject-load-path-a, `doom build` and `doom install` are not executed successfully

**Comment by cxb811201** [comment]
@hlissner Thanks

**Comment by hlissner** [comment]
> doom build and doom install are not executed successfully

Correct me if I'm wrong, but I'm assuming that you meant "`doom build` and `doom install` are **now** executed successfully" and mark this resolved. Thanks for bringing it to my attention!
