### ISSUE TITLE
Unbalanced parens

### ISSUE THREAD

**Issue by jcf** [hlissner/doom-emacs#478]
### Observed behavior

Same problem as reported here: https://github.com/hlissner/doom-emacs/issues/181

Typing an opening paren to the left of another paren inserts a single paren, which results in unbalanced parentheses.

```
|(+ 1 2 3)
```

Type `(`:

```
(|(+ 1 2 3)
```

### Expected behavior

```
(|)(+ 1 2 3)
```

### Steps to reproduce

I haven't customised Smartparens at all. I've tried to `make clean` assuming there was some byte compiled configuration somewhere but that didn't help.

### System information

<details>
<summary>Click to expand</summary>

- OS: gnu/linux (x86_64-pc-linux-gnu)
- Emacs: 25.3.1 (Feb 08, 2018)
- Doom: 2.0.9 (develop https://github.com/hlissner/doom-emacs/commit/e13fb0c74f394d352635b390830de7a5c8ca1390)
- Graphic display: t (daemon: t)
- System features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES
- Details:
  ```elisp
  uname -a:  Linux op 4.15.11-1-ARCH #1 SMP PREEMPT Mon Mar 19 18:21:03 UTC 2018 x86_64 GNU/Linux
  modules:   (:config :feature (eval nil) (evil nil) (file-templates nil) (lookup (+devdocs +docsets)) (snippets nil) (spellcheck nil) (syntax-checker nil) (version-control nil) (workspaces nil) :completion (ivy nil) :ui (doom-dashboard nil) (doom-modeline nil) (doom-quit nil) (hl-todo nil) (nav-flash nil) (evil-goggles nil) (vi-tilde-fringe nil) (window-select nil) :tools (electric-indent nil) (imenu nil) (magit nil) (neotree nil) (rotate-text nil) :lang (crystal nil) (clojure nil) (data nil) (emacs-lisp nil) (go nil) (haskell (+intero)) (javascript nil) (lua nil) (markdown nil) (org (+attach +babel +capture +export +present)) (python nil) (rest nil) (ruby nil) (rust nil) (sh nil) (web nil) :app :config)
  packages:  (ace-link ace-window all-the-icons anaconda-mode async auto-compile auto-yasnippet avy (centered-window :recipe (centered-window :fetcher github :repo anler/centered-window-mode)) cider circe circe-notifications clj-refactor cmake-mode coffee-mode command-log-mode company company-anaconda company-dict (company-glsl :recipe (company-glsl :fetcher github :repo Kaali/company-glsl)) company-go company-inf-ruby company-irony company-irony-c-headers company-lua company-quickhelp company-racer company-restclient company-shell company-statistics company-tern company-web counsel counsel-css counsel-dash counsel-projectile crystal-mode cuda-mode demangle-mode devdocs dired-k disaster dockerfile-mode doom-themes dumb-jump editorconfig (emacs-snippets :recipe (emacs-snippets :fetcher github :repo hlissner/emacs-snippets :files (*))) emmet-mode eslintd-fix evil evil-anzu evil-args evil-collection evil-commentary evil-easymotion evil-embrace evil-escape evil-exchange evil-goggles evil-indent-plus evil-magit evil-matchit evil-mc evil-multiedit evil-numbers evil-org evil-snipe evil-surround evil-textobj-anyblock evil-vimish-fold evil-visualstar (exec-path-from-shell :ignore t) expand-region flycheck flycheck-cask flycheck-crystal flycheck-irony flycheck-popup-tip flycheck-pos-tip flycheck-rust flyspell-correct flyspell-correct-ivy fringe-helper git-gutter-fringe git-link git-timemachine gitconfig-mode gitignore-mode glsl-mode go-eldoc go-guru go-mode gorepl-mode haml-mode haskell-mode helpful hide-mode-line highlight-indentation highlight-numbers highlight-quoted hindent hl-todo htmlize hydra imenu-anywhere imenu-list inf-crystal inf-ruby intero irony irony-eldoc ivy ivy-hydra ivy-rich ivy-rtags ivy-xref js2-mode js2-refactor json-mode less-css-mode lua-mode macrostep magit magithub markdown-mode markdown-toc modern-cpp-font-lock moonscript nav-flash neotree nlinum nlinum-hl nlinum-relative nodejs-repl nose ob-crystal ob-go ob-mongo ob-rust ob-sql-mode ob-translate opencl-mode (org-bullets :recipe (org-bullets :fetcher github :repo Kaligule/org-bullets)) org-download org-plus-contrib org-tree-slide (osx-clipboard :ignore t) overseer ox-pandoc ox-reveal pcre2el persistent-soft persp-mode pip-requirements projectile pug-mode quelpa quickrun racer rainbow-delimiters rainbow-mode rake restclient rjsx-mode (rotate-text :recipe (rotate-text :fetcher github :repo debug-ito/rotate-text.el)) rspec-mode rtags ruby-refactor rust-mode sass-mode shackle shrink-path skewer-mode slime smart-forward smartparens smex solaire-mode stylus-mode swiper tern toc-org toml-mode undo-tree use-package vi-tilde-fringe vimrc-mode visual-fill-column web-beautify web-mode wgrep which-key ws-butler xref-js2 yaml-mode yard-mode yasnippet)
  elc dirs:  n/a
  exec-path: (/usr/local/sbin /usr/local/bin /usr/bin /usr/lib/emacs/25.3/x86_64-pc-linux-gnu)
   ```
</details>

I have a private fork of Doom that I can retire now that I'm aware of the `private` module feature. Here's the output from `git diff upstream/develop` where upstream is your repo and I'm on my develop branch:

``` patch
diff --git a/init.el b/init.el
new file mode 100644
index 00000000..1393c235
--- /dev/null
+++ b/init.el
@@ -0,0 +1,32 @@
+;;; init.el -*- lexical-binding: t; -*-
+;;
+;; Author:  Henrik Lissner <henrik@lissner.net>
+;; URL:     https://github.com/hlissner/.emacs.d
+;;
+;;   =================     ===============     ===============   ========  ========
+;;   \\ . . . . . . .\\   //. . . . . . .\\   //. . . . . . .\\  \\. . .\\// . . //
+;;   ||. . ._____. . .|| ||. . ._____. . .|| ||. . ._____. . .|| || . . .\/ . . .||
+;;   || . .||   ||. . || || . .||   ||. . || || . .||   ||. . || ||. . . . . . . ||
+;;   ||. . ||   || . .|| ||. . ||   || . .|| ||. . ||   || . .|| || . | . . . . .||
+;;   || . .||   ||. _-|| ||-_ .||   ||. . || || . .||   ||. _-|| ||-_.|\ . . . . ||
+;;   ||. . ||   ||-'  || ||  `-||   || . .|| ||. . ||   ||-'  || ||  `|\_ . .|. .||
+;;   || . _||   ||    || ||    ||   ||_ . || || . _||   ||    || ||   |\ `-_/| . ||
+;;   ||_-' ||  .|/    || ||    \|.  || `-_|| ||_-' ||  .|/    || ||   | \  / |-_.||
+;;   ||    ||_-'      || ||      `-_||    || ||    ||_-'      || ||   | \  / |  `||
+;;   ||    `'         || ||         `'    || ||    `'         || ||   | \  / |   ||
+;;   ||            .===' `===.         .==='.`===.         .===' /==. |  \/  |   ||
+;;   ||         .=='   \_|-_ `===. .==='   _|_   `===. .===' _-|/   `==  \/  |   ||
+;;   ||      .=='    _-'    `-_  `='    _-'   `-_    `='  _-'   `-_  /|  \/  |   ||
+;;   ||   .=='    _-'          '-__\._-'         '-_./__-'         `' |. /|  |   ||
+;;   ||.=='    _-'                                                     `' |  /==.||
+;;   =='    _-'                                                            \/   `==
+;;   \   _-'                                                                `-_   /
+;;    `''                                                                      ``'
+;;
+;; These demons are not part of GNU Emacs.
+;;
+;;; License: MIT
+
+(require 'core (concat user-emacs-directory "core/core"))
+
+(doom! :config (private +xdg))
diff --git a/modules/lang/clojure/config.el b/modules/lang/clojure/config.el
index 8cc08d1d..71e4f2a2 100644
--- a/modules/lang/clojure/config.el
+++ b/modules/lang/clojure/config.el
@@ -2,6 +2,7 @@
 
 (def-package! clojure-mode
   :mode "\\.clj$"
+  :mode "\\.edn$"
   :mode ("\\.cljs$" . clojurescript-mode)
   :mode ("\\.cljc$" . clojurec-mode)
   :config
@@ -15,7 +16,7 @@
   (nconc cljr-magic-require-namespaces
          '(("re-frame" . "re-frame.core")
            ("reagent"  . "reagent.core")
-           ("str"      . "clojure.str"))))
+           ("str"      . "clojure.string"))))
 
 
 (def-package! cider
```

**Comment by hlissner** [comment]
Actually this is intentional; I've configured smartparens not to auto-close braces if the cursor is followed by another of the same brace.

+ `| ()` => <kbd>(</kbd> => `() ()`
+ Whereas: `|()` => <kbd>(</kbd> => `(()`
+ Also: `|abc` => <kbd>(</kbd> => `(abc`

Here is the relevant default smartparens config:

```elisp
;; from modules/config/default/config.el
(dolist (brace '("(" "{" "["))
  (sp-pair brace nil
           :post-handlers '(("||\n[i]" "RET") ("| " "SPC"))
           ;; I likely don't want a new pair if adjacent to a word or opening brace
           :unless '(sp-point-before-word-p sp-point-before-same-p)))
```

Note the `:unless ...` clause. Auto-pairing doesn't occur if the point is before a word character (sp-point-before-word-p) or before another of the same delimiter (sp-point-before-same-p).

So to restore the behavior you want, we need to remove those conditional clauses:

```elisp
;; in ~/.doom.d/config.el (for example)
(after! smartparens
  (dolist (brace '("(" "{" "["))
    (sp-pair brace nil :unless '(:rem sp-point-before-word-p sp-point-before-same-p))))
```

My reasoning for this default is (I thought) that if the point precedes a word character or another of the same delimiter, you are likely focused on editing the delimiters and their balance, rather than adding a new form.

Hope that helps!

**Comment by jcf** [comment]
> It also seemed like bad form to have no space in between forms in Lisp-like languages.

Agreed regarding whitespace, but I insert new parens right before existing ones hundreds of times a day, and then use structural editing (e.g. `sp-forward-slurp-sexp` to move things around).

I've found Doom unbalances parens a lot. Enough that I've gotten quite annoyed because it really interrupts my flow and forces me to do silly things like yank a close paren and paste because typing <kbd>)</kbd> jumps to the end of the unbalanced expression rather than inserting a correction where I need it. I've also noticed <kbd>f ]</kbd> seems to jump to `)` sometimes - not something I have a repro case for and maybe just my fat thumbs… /rant 

Rather than give up I'm trying to fix/improve things. I've added the following mappings for Smartparens to my config as I haven't found anything like this in Doom, yet:

``` emacs-lisp
   ;; ...
   (:desc "sexp" :prefix "k"
     :desc "Barf forward"  :n "b" #'sp-forward-barf-sexp
     :desc "Raise"         :n "r" #'sp-raise-sexp
     :desc "Slurp forward" :n "s" #'sp-forward-slurp-sexp
     :desc "Split"         :n "o" #'sp-split-sexp)
   ;; ...
```

How do you edit Lisp, @hlissner? Maybe I'm missing a trick?

**Comment by jcf** [comment]
Happy to close this if you are @hlissner?

**Comment by hlissner** [comment]
> also noticed f ] seems to jump to ) sometimes

This is responsible for that behavior:

```elisp
;; in modules/feature/evil/config.el line 343
(setq evil-snipe-aliases
      '((?\[ "[[{(]")
        (?\] "[]})]")
        (?\; "[;:]")))
```

The option allows you to set regex aliases for certain characters. In this case, `?\]`. I no longer believe these are reasonable defaults, so I will remove the `?\[` and `?\]` aliases.

> How do you edit Lisp, @hlissner? Maybe I'm missing a trick?

No tricks here! I'm just fluent with vim/evil's motion keys.

It's not that I don't understand the appeal (and benefits) of using packages like lispyville, smartparens and parinfedit for navigating lisps; in fact, Doom may adopt lispyville for that purpose, but I've done fine without.

> I've found Doom unbalances parens a lot.

Even with my snippet above?

```elisp
;; in ~/.doom.d/config.el (for example)
(after! smartparens
  (dolist (brace '("(" "{" "["))
    (sp-pair brace nil :unless '(:rem sp-point-before-word-p sp-point-before-same-p))))
```

**Comment by jcf** [comment]
I'll pull in the removal of `[` and `]` from evil-snipe aliases and do some more work with Clojure today. I think your suggestion for 'fixing' (in my opinion) the insertion of parens next to parens and https://github.com/hlissner/doom-emacs/commit/653caf4e736abfa67a80fe3d8b8b426864308e9f will appease me. :wink:

> No tricks here! I'm just fluent with vim/evil's motion keys.

I've done a fair bit of Vim golf in the past, and came from Vim/MacVim to Emacs. I definitely prefer structural editing as it takes fewer keystrokes, which is good for my occassional pinky pain.

> It's not that I don't understand the appeal (and benefits) of using packages like lispyville, smartparens and parinfedit for navigating lisps; in fact, Doom may adopt lispyville for that purpose, but I've done fine without.

I would love to see Lispyville added to Doom! I was planning on doing this myself and would be happy to collaborate if you want.

**Comment by jcf** [comment]
Since adding Lispy and Lispyville I have zero complaints. Everything is always balanced.

**Comment by jcf** [comment]
Closing this because with Lispy and Lispyville I can fix most of the issues I was experiencing.

The only problem I have is with inserting nested double quotes and trying to delete them, but that's not down to Doom. :smile: 

Thanks, Henrik!
