### ISSUE TITLE
An error when trying to delete a message from mu4e `mu4e-error: [mu4e] Invalid mark delete`

### ISSUE THREAD

**Issue by abougouffa** [hlissner/doom-emacs#4785]
Hello,

First, let me thank you for this beautiful project.

I have an issue with `mu4e`, on the `*mu4e-headers*` buffer, when I try to delete a message by pressing the `D` key, I get an error:

```elisp
mu4e-error: [mu4e] Invalid mark delete
```

**What did you expect to happen?**
Delete the mail when I press `D`.

**What actually happened?**
The message was not deleted as I would expect, an error is produced:

```elisp
mu4e-error: [mu4e] Invalid mark delete
```

**Additional details:**
When I enable `debug-on-error` and I try to delete a mail with `D`, I get this traceback:

```elisp
Debugger entered--Lisp error: (error #("[mu4e] Invalid mark delete" 1 5 (face mu4e-title-face)))
  error("%s" #("[mu4e] Invalid mark delete" 1 5 (face mu4e-title-face)))
  mu4e-error("Invalid mark %S" delete)
  mu4e-mark-at-point(delete nil)
  mu4e-mark-set(delete)
  mu4e-headers-mark-and-next(delete)
  mu4e-headers-mark-for-delete()
  funcall-interactively(mu4e-headers-mark-for-delete)
  command-execute(mu4e-headers-mark-for-delete)
```

**Steps to reproduce:**
1. `SPC o m`
2. `J` and select a maildir,
3. Navigate to the mail you want to delete,
4. Press `D` (**capital D** for delete, not small `d` for trash)

**System information:**
https://pastebin.com/dhkDct16

**Comment by abougouffa** [comment]
**UPDATE:**
I think I figured what causes this problem, it is caused by the `+gmail` feature, It was enabled in my `.doom.d/init.el`. 

I think this what causes the problem:

https://github.com/hlissner/doom-emacs/blob/fa4f03de22b07c529ea8e84bffdc66d9ab697238/modules/email/mu4e/config.el#L140

I have to mention that, even when using `mu4e` with several non-gmail accounts, the error occurs when the `+gmail` is enabled.

**Comment by hlissner** [comment]
[A large PR to rewrite the mu4e module is underway here](https://github.com/hlissner/doom-emacs/pull/3971), which should contain a fix for this issue. I'd suggest switching to it for now, as I will not be maintaining the one on `develop`. It will be merged sometime this weekend.

I will close this issue once it has been merged.

**Comment by abougouffa** [comment]
Great! Thank you very much @hlissner
