### ISSUE TITLE
Unable to leave directory after joining it using find-file

### ISSUE THREAD

**Issue by innerout** [hlissner/doom-emacs#4793]
**What did you expect to happen?**
I expected to be able to join any directory in my filesystem.

**What actually happened?**
I was able to access files in the directory I joined and its subdirectories. I was blocked from accessing parent directories.

**Additional details:**
Link to my [config](https://github.com/innerout/Emacs).
Screenshot showing the problem.
![image](https://user-images.githubusercontent.com/11080614/111034170-fb992300-841c-11eb-81c6-43de89ca395d.png)

M-x view-echo-area-messaeges 
sp-backward-delete-char: Text is read-only

**Steps to reproduce:**
1. Open Emacs 28 without native compilation using my config.
2. Join a directory using find-file
3. Try to access a parent directory and you will get blocked since the text is read only

**System information:**
https://pastebin.com/0Rhw41r3

**Comment by innerout** [comment]
I want to mention that this behavior also occurs when I open emacs inside a directory from a terminal. There also, I cannot access a parent directory. This does not happen with ivy and ivy-posframe in a vanilla emacs configuration.

**Comment by hlissner** [comment]
I cannot reproduce this in vanilla Doom so I suspect the issue lies in your config. Potentially because you've enabled `smartparens-global-strict-mode`. Try disabling it and see if the issue goes away.

**Comment by innerout** [comment]
You are right `smartparens-global-strict-mode` causes the bug.
