### ISSUE TITLE
"Noel's crash course" link in documentation is dead

### ISSUE THREAD

**Issue by anshukla** [hlissner/doom-emacs#4799]
**What did you expect to happen?**
...
Clicking on "Noel’s crash course on Doom Emacs" in https://github.com/hlissner/doom-emacs/blob/0769b47cc84f15f9f546df0b6cd82c90c23d6b21/docs/index.org takes me to website

**What actually happened?**
...
404

Can be reproduced from the GitHub link as well

**Comment by jonathanabennett** [comment]
A bit of Googling brings me to https://noelwelsh.com/posts/doom-emacs/ as the correct link

**Comment by hlissner** [comment]
Duplicate of #4709
