### ISSUE TITLE
FATAL ERROR in make install 

### ISSUE THREAD

**Issue by fbob** [hlissner/doom-emacs#480]
### Observed behavior

Installing ox-reveal
  FATAL ERROR: (error) Need package ‘org-20150330’, but only 9.1.7 is available
Installing centered-window-mode
  FATAL ERROR: (error) Package ‘centered-window-mode-’ is unavailable
Installing ob-redis
  FATAL ERROR: (error) Package ‘ob-redis-’ is unavailable
Installing org-bullets
  FATAL ERROR: (error) Invalid version syntax: ‘Command ’(env LC_ALL=C /usr/bin/timeout -k 60 600 git clone https://github.com/hlissner/org-bullets.git /home/fbob/.emacs.d/.local/packages/quelpa/build/org-bullets/)’ exited with non-zero status 128: Cloning into ’/home/fbob/.emacs.d/.local/packages/quelpa/build/org-bullets’...
fatal: could not read Username for ’https://github.com’: No such device or address
’ (must start with a number)
Installing auth-password-store
  FATAL ERROR: (error) Package ‘auth-password-store-’ is unavailable
Installing help-fns+
  FATAL ERROR: (error) Package ‘help-fns+-’ is unavailable

### Expected behavior

A fresh install of doom-emacs :)

### Steps to reproduce

git clone https://github.com/hlissner/doom-emacs ~/.emacs.d
cd ~/.emacs.d
cp init.example.el init.el  # maybe edit init.el
make install

### System information
GNU Emacs 25.3.50.2 (x86_64-pc-linux-gnu, GTK+ Version 3.22.11)
 of 2017-09-15
Ubuntu 17.10

```
Replace this line with the output of *one* of these commands:

+ DOOM Doctor
Running Emacs v25.3.50.2, commit 5dacbb7cb1c6ac246a9ccd15e6c4290def67757c

shell: /usr/bin/zsh
Compiled with:
  XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS
  NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB
  TOOLKIT_SCROLL_BARS GTK3 X11 MODULES XWIDGETS
uname -a:
  Linux dylan 4.10.0-42-generic #46-Ubuntu SMP Mon Dec 4 14:38:01 UTC
  2017 x86_64 x86_64 x86_64 GNU/Linux

Attempt to load DOOM: success! Loaded v2.0.9
Revision 5dacbb7cb1c6ac246a9ccd15e6c4290def67757c

----

test-emacs
test-windows
test-fonts
Found font material-design-icons.ttf
Found font weathericons.ttf
Found font octicons.ttf
Found font fontawesome.ttf
Found font file-icons.ttf
Found font all-the-icons.ttf
test-gnutls
test-tls
Validated https://elpa.gnu.org
Validated https://melpa.org
Successfully rejected https://self-signed.badssl.com
Successfully rejected https://wrong.host.badssl.com/
test-tar
Everything seems fine, happy Emacs’ing!

+ `DEBUG=1 make doctor` (command line)

 
DOOM Doctor

Running Emacs v25.3.50.2, commit 5dacbb7cb1c6ac246a9ccd15e6c4290def67757c

shell: /usr/bin/zsh
Compiled with:
  XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS
  NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB
  TOOLKIT_SCROLL_BARS GTK3 X11 MODULES XWIDGETS
uname -a:
  Linux dylan 4.10.0-42-generic #46-Ubuntu SMP Mon Dec 4 14:38:01 UTC
  2017 x86_64 x86_64 x86_64 GNU/Linux

Attempt to load DOOM: success! Loaded v2.0.9
Revision 5dacbb7cb1c6ac246a9ccd15e6c4290def67757c

----

test-emacs
test-windows
test-fonts
Found font material-design-icons.ttf
Found font weathericons.ttf
Found font octicons.ttf
Found font fontawesome.ttf
Found font file-icons.ttf
Found font all-the-icons.ttf
test-gnutls
test-tls
Validated https://elpa.gnu.org
Validated https://melpa.org
Successfully rejected https://self-signed.badssl.com
Successfully rejected https://wrong.host.badssl.com/
test-tar
Everything seems fine, happy Emacs’ing!

**Comment by hlissner** [comment]
Please switch to the `develop` branch. These issues have been fixed and are due to be merged into master soon.

**Comment by fbob** [comment]
Great thanks.
Avewome work : doom-emacs rules :+1:

**Comment by a-y-u-s-h** [comment]
On `develop` branch, everything else installs except for auth-password-store. I'm getting this : 

```bash
Looking for packages to install...
1 packages will be installed:

+ auth-password-store (ELPA)

Proceed? (y or n) y
Refreshing package archives
Importing package-keyring.gpg...
Importing package-keyring.gpg...done
Contacting host: elpa.gnu.org:443
Contacting host: elpa.gnu.org:443
Contacting host: melpa.org:443
Contacting host: orgmode.org:443
Package refresh done
Installing auth-password-store
  FATAL ERROR: (error Package ‘auth-password-store-’ is unavailable)
Finished!


```

**Comment by hlissner** [comment]
Ack, looks like they changed the name of the package upstream. I'll fix this soon.

**Comment by hlissner** [comment]
@a-y-u-s-h Just pushed the fix. This should be resolved in the latest develop.

**Comment by a-y-u-s-h** [comment]
Thanks!

**Comment by aladine** [comment]
auth-source-pass is a package in melpa now, 
not available in elpa anymore. Could you help to update? 
[Melpa](https://melpa.org/#/?q=auth-)

**Comment by hlissner** [comment]
@aladine It is already built into Emacs 26.1+, and is installed from MELPA if you are using Emacs 25.x.
