### ISSUE TITLE
In Windows `doom-load-envvars-file` failed load env because of search regexp. 

### ISSUE THREAD

**Issue by lld2001** [hlissner/doom-emacs#4802]
In Windows 7,  `doom-load-envvars-file` failed load vars from env file. I found that the problem is the following function return nil in env file.
``` emacs-lisp
(re-search-forward "\0\n *\\([^#= \n]*\\)=" nil t)
```
which can be fixed by delete "\0". But I dont know what's the difference of "\n" and "\0\n".

**Comment by hlissner** [comment]
`\0\n` is what Doom's envvar file uses to delimit envvars and is needed for it to parse them correctly. Windows is likely decoding the file "incorrectly". Windows uses `\r\n` for newline and linux uses `\n`.

Could you try deleting [this line](https://github.com/hlissner/doom-emacs/blob/develop/core/core.el#L482) from `doom-load-envvars-file` and see if that fixes your issue?

**Comment by lld2001** [comment]
I open the env file(fundamental-mode) which created by doom. And return to the begining, eval this form `(re-search-forward "\0\n *\\([^#= \n]*\\)=" nil t)`. It's result is `nil`.

**Comment by lld2001** [comment]
The previous works ok.
```emacs-lisp
(defun doom-load-envvars-file (file &optional noerror)
  "Read and set envvars from FILE.
 If NOERROR is non-nil, don't throw an error if the file doesn't exist or is
 unreadable. Returns the names of envvars that were changed."
  (if (not (file-readable-p file))
      (unless noerror
        (signal 'file-error (list "Couldn't read envvar file" file)))
    (let (envvars environment)
      (with-temp-buffer
        (save-excursion
          (insert "\n")
          (insert-file-contents file))
        (while (re-search-forward "\n *\\([^#= \n]*\\)=" nil t)
          (push (match-string 1) envvars)
          (push (buffer-substring
                 (match-beginning 1)
                 (1- (or (save-excursion
                           (when (re-search-forward "^\\([^= ]+\\)=" nil t)
                             (line-beginning-position)))
                         (point-max))))
                environment)))
      (when environment
        (setq process-environment
              (append (nreverse environment) process-environment)
              exec-path
              (if (member "PATH" envvars)
                  (append (split-string (getenv "PATH") path-separator t)
                          (list exec-directory))
                exec-path)
              shell-file-name
              (if (member "SHELL" envvars)
                  (or (getenv "SHELL") shell-file-name)
                shell-file-name))
        envvars))))
```

**Comment by lld2001** [comment]
> Could you try deleting [this line](https://github.com/hlissner/doom-emacs/blob/develop/core/core.el#L482) from `doom-load-envvars-file` and see if that fixes your issue?

I tested as your tip, but it still fails. I edebug this fun, found this because `when (re-search-forward "\0\n *\\([^#= \n]*\\)=" nil t)` return `nil`.

**Comment by hlissner** [comment]
As of 763d0b6 this should be resolved. Please update Doom with `doom upgrade` and regenerate your envvar file with `doom env`. If it throws an error you may need to delete `~/.emacs.d/.local/env` by hand then try again. Thanks for letting me know!
