### ISSUE TITLE
I can't install quelpa packages

### ISSUE THREAD

**Issue by yuchenyang1994** [hlissner/doom-emacs#481]
Looking for packages to install...
7 packages will be installed:

+ centered-window (QUELPA)
+ company-glsl (QUELPA)
+ emacs-snippets (QUELPA)
+ goenv (QUELPA)
+ org-bullets (QUELPA)
+ rotate-text (QUELPA)
+ yapfify (QUELPA)

Proceed? (y or n) y
Installing rotate-text
✕ FAILED
Installing company-glsl
✕ FAILED
Installing goenv
✕ FAILED
Installing org-bullets
✕ FAILED
Installing centered-window
✕ FAILED
Installing yapfify
✕ FAILED
Installing emacs-snippets
✕ FAILED
Finished!

## make doctoDoom Doctor
Emacs v25.3.1
Doom v2.0.9 (c87122e6)
shell: /usr/bin/zsh
Compiled with:
  XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL
  GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11
  MODULES
uname -a:
  Linux yuchenyang-pc 4.14.29-1-MANJARO #1 SMP PREEMPT Wed Mar 21 16:48:46 UTC
  2018 x86_64 GNU/Linux

----

test-emacs
test-windows
test-fonts
test-gnutls
test-tls
Validated https://elpa.gnu.org
Validated https://melpa.org
Successfully rejected https://self-signed.badssl.com
Successfully rejected https://wrong.host.badssl.com/
test-tar

----
Attempt to load DOOM: success! Loaded v2.0.9
test-modules
  > (:tools rotate-text) rotate-text is not installed
  > (:lang cc) company-glsl is not installed
  > (:lang cc) Couldn’t find the rtag client and/or server programs
    (rdm rc). Disabling rtags support
  > (:lang cc) Irony server isn’t installed. Run M-x
    irony-install-server
  > (:lang cc) Couldn’t find glslangValidator. GLSL code completion
    is disabled
  > (:lang go) goenv is not installed
  > (:lang org) centered-window is not installed
  > (:lang org) org-bullets is not installed
  > (:lang org-private) org-bullets is not installed
  > (:lang python) yapfify is not installed
  > (:config default) emacs-snippets is not installed

----
## package.el
```
(package! yapfify :recipe (:fetcher github :repo "JorisE/yapfify"))


```

**Comment by yuchenyang1994** [comment]
The quelpa is refactored,.update quelpa . close this issues, thanks for you

**Comment by dariooddenino** [comment]
I have the same issue, could you elaborate on how you solved it? Thanks :)

**Comment by hlissner** [comment]
@dariooddenino There was a recent update to package-build, which broke quelpa. To fix this you need to manually delete the quelpa package in `~/.emacs.d/.local/packages/elpa/quelpa-*` then run any make command.

That will update quelpa and should resolve your issue.

**Comment by dariooddenino** [comment]
Thanks, it worked
