### ISSUE TITLE
Org-mode should link correctly info:title

### ISSUE THREAD

**Issue by kcurtet** [hlissner/doom-emacs#4811]
When I add a link to an org file, in the completion I don't see `info:` type of link then I type myself the `info:elisp` link with a description.

**What did you expect to happen?**
I expect org-mode links me to Emacs Lisp info manual. It's the normal Emacs behavior.

**What actually happened?**
Org-mode tries to create a new heading in the current file. Maybe I need to load some org module.

**Additional details:**
- Link to your private config, if possible
https://github.com/kcurtet/doom.d
- Include screenshots/casts of your issue
![captura](https://user-images.githubusercontent.com/3438361/111304497-199d9800-8656-11eb-93d9-5186bf65d323.gif)

- Replace key sequences in your steps to reproduce, use commands
C-c C-l org-link

**System information:**
https://pastebin.com/ucdEYJV9

**Comment by hlissner** [comment]
To activate support for info links you need to activate the `ol-info` org module:

```elisp
(after! org
  (add-to-list 'org-modules 'ol-info))
```

Since this is a configuration issue and not a Doom one I will close this, but feel free to follow up here.
