### ISSUE TITLE
`git-gutter:disabled-modes` not respected

### ISSUE THREAD

**Issue by jhacksworth** [hlissner/doom-emacs#4815]
Adding `org-mode` to `git-gutter:disabled-modes` has no effect.

From my tests, it appears that 15f7a26be6e7e366ff0c4d99456bfb32ed0ff92a is the cause. It no longer checks for `git-gutter:disabled-modes`.

Reverting that commit, along with d9dac055a64a9505a0652f07015c81b81d8b14f6, to avoid conflicts, fixed the issue.

**What did you expect to happen?**

To have git-gutter disabled in `org-mode` files when adding it to `git-gutter:disabled-modes`.

**What actually happened?**

`git-gutter` is enabled.

**Steps to reproduce:**

1. In doom-sandbox with the following setup: `Doom + modules - your private config   C-c C-p`
2. Add `org-mode` to  `git-gutter:disabled-modes`. Example code: `(add-to-list 'git-gutter:disabled-modes 'org-mode)`
3. Open an Org file under git source control.
4. Edit and save the file.
5. `git-gutter` is enabled in the fringe.

**Comment by hlissner** [comment]
As of 2b3dd9d this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
