### ISSUE TITLE
local-repo autoloads created but never updated

### ISSUE THREAD

**Issue by saysjonathan** [hlissner/doom-emacs#4816]
When using a `package!` declaration with `local-repo`, a package autoload file is created with the module. When using `:build (:not compile)`, the autoloads file is never updated. To update the package, you must first remove `.emacs.d/.local/straight/build-$version/$package`.

When using compilation, the autoloads file is updated.

**What did you expect to happen?**
When using `:build (:not compile)`, an autoloads file should not be created or should be automatically updated when a local-repo is changed.

**What actually happened?**
Autoloads is created but never updated. Package must be removed from `straight` in order to be updated.

**Additional details:**
```elisp
(package! foo-bar
  :recipe (:local-repo "~/proj/foo-bar"
           :build (:not compile)))
```

**Steps to reproduce:**
1. Setup a local-repo package
2. Make change to package, like adding a new autoloaded function
3. Try to use function
4. Try to update module using `doom sync`, `doom sync -u`, `doom/reload-packages`, etc

**System information:**
```
  generated  Mar 17, 2021 17:49:45
     distro  MacOS 11.2.3 Darwin 20.3.0 arm64
      emacs  27.1 ~/.emacs.d/
       doom  2.0.9 HEAD -> develop 46dedb3e 2021-03-13 16:35:21 -0500 ~/.doom.d/ -> ~/.doom.d/
      shell  /opt/homebrew/bin/zsh
   features  NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB MODULES THREADS JSON PDUMPER GMP
     traits  batch
    modules  :completion company ivy :ui deft doom (emoji +unicode) hl-todo ligatures modeline ophints (popup +default) vc-gutter (&nopath vc-tilder-fringe) workspaces :editor (evil +everywhere) file-templates fold (format +onsave) snippets :emacs dired electric undo vc :term eshell vterm :checkers syntax :tools (eval +overlay) lookup magit rgb :os macos tty :lang cc data emacs-lisp json javascript ledger markdown (org +present +roam) python rest rust scheme sh swift (web +html +css) yaml :config (default +bindings +smartparens)
   packages  (org-roam-server) (epresent) (org-ql) (org-cook :recipe (:local-repo ~/proj/org-cook :build (:not compile)))
        nil
       elpa  n/a
```

**Comment by hlissner** [comment]
I've moved this to #4273, which chronicles the rewrite of Doom's CLI and tracks its known issues.
