### ISSUE TITLE
Literate config module `doom sync` can't create file

### ISSUE THREAD

**Issue by markgdawson** [hlissner/doom-emacs#4817]
**What did you expect to happen?**
I freshly installed doom with the git clone suggested in the repo. I changed the ~/.doom.d/init.el file to include the modules I wanted, including the `literate` module.

I ran `doom sync`. I was expecting the modules to be initialised.

**What actually happened?**
In fact I got an error:
```
~/.emacs.d/bin/doom sync
> Compiling your literate config...
  x There was an unexpected error
    Message: File is missing
    Data: (file-missing . "Opening input file")
    Backtrace:
      (insert-file-contents "~/.doom.d/config.org")
      (save-current-buffer (set-buffer temp-buffer) (insert-file-contents target
      (prog1 (save-current-buffer (set-buffer temp-buffer) (insert-file-contents
      (unwind-protect (prog1 (save-current-buffer (set-buffer temp-buffer) (inse
      (let ((temp-file backup) (temp-buffer (generate-new-buffer " *temp file*" 
      (unwind-protect (let ((temp-file backup) (temp-buffer (generate-new-buffer
      (let ((doom-output-indent (+ doom-output-indent-increment doom-output-inde
      (progn (doom--print (doom--format (format (doom--output-class 'start "Comp
      (progn (fset #'message vnew) (ignore message) (progn (doom--print (doom--f
      (unwind-protect (progn (fset #'message vnew) (ignore message) (progn (doom
  ! Extended backtrace logged to ~/.emacs.d/.local/doom.error.log
```

Creating the config.org file manually allowed the installation to continue.

Note, I did all this from within the emacs session I had running before installing doom.

**Comment by destroyer449** [comment]
The literate module is not designed to turn your config into an org file, but assumes that you wish to use a literate config file. This means that instead of having a `config.el`, you have a `config.org` that gets turned into the former on sync. So if you are using literate, you would not usually suffer from this problem, as you would already have an org file set up.

**Comment by AnilJoshi** [comment]
I have the same problem. I never used org mode nor did I do literate programming. I would like to start with tecosaur's README.org, edit that and go from there. How should I proceed?

**Comment by MarkusSagen** [comment]
@AnilJoshi as can be seen from the error message when running `doom sync` with the literate module enabled, Doom Emacs will try to find your config not in the file ~/.doom.d/config.el, but instead at ~/.doom.d/config.org. If that org file does not exist, you will get an error.  

Everything in the org-babel source blocks will be exported to your config.
Ex:
```lisp
#+begin_src emacs-lisp
(setq doom-theme 'doom-palenight)
#+end_src
```
