### ISSUE TITLE
Add support for updating xterm title

### ISSUE THREAD

**Issue by ajgrf** [hlissner/doom-emacs#4819]
**Describe the feature**
It would be cool if Doom updated the xterm frame title. Currently I do this with the following code in my `config.el`:

```emacs-lisp
(when (featurep! :os tty)
  (add-hook! after-init :append
    (use-package! term/xterm
      :if (and (not window-system)
               (not noninteractive))
      :hook (post-command . xterm-set-window-title))))
```

There are probably further edge cases to handle, but it works for me in tmux and multiple terminal emulators. I think something like this should be added to the `:os tty` module.

**Comment by hlissner** [comment]
As of c9056dd the `:os tty` module should update xterm window titles. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
