### ISSUE TITLE
doom install fails on Windows 10 when user profile contains Baltic letters

### ISSUE THREAD

**Issue by itomti** [hlissner/doom-emacs#4822]
When user profile (C:\Users\\{User}) on Windows contains Baltic characters (š, č, į, etc), doom install fails.

**What did you expect to happen?**
To successfully install doomemacs

**What actually happened?**
doom install failed with error

**Additional details:**
- https://pastebin.com/4uFrpU3x

**Steps to reproduce:**
1. Have a user profile on Windows with Baltic language letters (ą, č, ę, ė, į, š, ų, ū)
2. Clone doomemacs 
3. Install pre-requisites (fd, ripgrep, git, emacs)
3. Navigate to .emacs.d/bin
4. Type ./doom install

Temporary workaround is to create a symbolic link to the user profile without Baltic letters, then doom install works.

**Comment by hlissner** [comment]
Please include the contents of `~/.emacs.d/.local/doom.error.log` (which should be produced after seeing the error). This appears to be a `git` error rather than a Doom issue.

**Comment by itomti** [comment]
@hlissner,

The contents of ~/.emacs.d/.local/doom.error.log are: https://pastebin.com/jYVuYKUZ.
