### ISSUE TITLE
Use doom with straight

### ISSUE THREAD

**Issue by haji-ali** [hlissner/doom-emacs#4823]
I know that Doom has its own package management system which relies on `package!` statements and the packages are installed later through the CLI. 

However, it would helpful if Doom can work with packages installed directly with `straight`. My reason for this is that I am writing configurations that work with or without Doom. This mostly works until I run Doom CLI which keeps purging the packages that are not specified in `packages.el`.

As far as I can see all that needs to be done is allow the user to specify a package in `packages.el` that is not managed (i.e., cloned, built and compiled) by Doom but should not be purged by its CLI.

Right now this is somewhat doable, but then I have to replicate the recipe in both the config file and the `packges.el` file.

**Comment by hlissner** [comment]
Does adding `(package! X :ignore t)` for each package you are installing manually accomplish this?

**Comment by haji-ali** [comment]
Brilliant. You really did think of everything!

**Comment by haji-ali** [comment]
Apologies. This turned out to not work 100%

The packages are indeed not managed by Doom when ignored, but it seems that Doom adds them to `straight-recipe-overrides` with a `:type built-in` which makes cloning the package fail (if not already cloned).
I am fixing this by setting `straight-recipe-overrides` to nil. But I am re-opening this issue in case this is unintended.

**Comment by hlissner** [comment]
In that case I'll defer this to #4273, which already has a "fix `package!`'s `:ignore` parameter"
