### ISSUE TITLE
flycheck-eglot: due to a race condition, "lsp-eglot-prefer-flycheck-h" becomes ineffective after eglot has started an LSP server

### ISSUE THREAD

**Issue by HouzuoGuo** [hlissner/doom-emacs#4828]
**What did you expect to happen?**
I'm using `eglot` as the LSP plugin in doom-emacs. Though `eglot` recommends `flymake`, I am reluctant to abandon `flycheck` which seems to work better for me.

So I ended up with the following snippet in `config.el`:

```
:tools
(lsp +eglot)
...
:lang
       (cc +lsp)                ; C/C++/Obj-C madness
       data              ; config/data formats
       emacs-lisp        ; drown in parentheses
       (go +lsp)         ; the hipster dialect
       json              ; At least it ain't XML
       javascript        ; all(hope(abandon(ye(who(enter(here))))))
       markdown          ; writing docs for people to ignore
       (python +lsp +pyright)            ; beautiful is better than ugly
       rest              ; Emacs as a REST client
       (sh +lsp +fish +powershell)                ; she sells {ba,z,fi}sh shells on the C xor
       (web +lsp)               ; the tubes
       yaml              ; JSON, but readable
```

Thankfully, doom-emacs already helps to integrate `flycheck` with `eglot` so that findings from `flycheck` will continue to show up as `eglot` becomes the major mode of an opened file:

https://github.com/hlissner/doom-emacs/blob/develop/modules/tools/lsp/autoload/flycheck-eglot.el#L56

**What actually happened?**

When opening a shell script file, eglot becomes the main mode (as intended), and thanks to doom-emacs flycheck kicks in as well. Flycheck findings show up almost immediately as the document opens, however, then the following messages show up in the messages buffer:

```
Doom loaded 248 packages across 52 modules in 2.587s
Switched to ’laitos’
Loading /root/.emacs.d/.local/cache/recentf...done
Setting up indent for shell type bash
Indentation variables are now local.
Indentation setup for shell type bash
Analyzing the buffer...done
Guessing...done
Local rules set
Note: sh-basic-offset, tab-width, evil-shift-width adjusted to 2
Starting new Ispell process aspell with english dictionary...
Loading eldoc...done
[eglot] Connected! Server `EGLOT (laitos/sh-mode)' now managing `sh-mode' buffers in project `laitos'.
```

As eglot announces its success joyfully, flycheck findings immediately disappear and never show up again, as if the `lsp-eglot-prefer-flycheck-h` function doom-emacs authored for flycheck becomes ineffective. I suspected that there was a race condition involved. Looking at line 56 in `flycheck-eglot.el`:

```
(add-hook! 'eglot-managed-mode-hook
  (defun +lsp-eglot-prefer-flycheck-h ()
    (when eglot--managed-mode
...
```

`eglot` offers two hooks - `eglot-server-initialized-hook` and `eglot-managed-mode-hook`. Just to tinker around, I installed the function `lsp-eglot-prefer-flycheck-h` to the `eglot-server-initialized-hook` as well:

```
(add-hook! 'eglot-server-initialized-hook
  (defun +lsp-eglot-prefer-flycheck-temp-copy ()
    (when eglot--managed-mode
      (when-let ((current-checker (flycheck-get-checker-for-buffer)))
        (unless (equal current-checker 'eglot)
          (flycheck-add-next-checker 'eglot current-checker)))
      (flycheck-add-mode 'eglot major-mode)
      (flycheck-mode 1)
      (flymake-mode -1))))
```

My knowledge of emacs-lisp is limited, but that seems to solve the issue - the flycheck findings not only stay, but new findings show up as well, even after the `[eglot] Connected!` announcement.

Would you mind to hook the `lsp-eglot-prefer-flycheck-h` function to `eglot-server-initialized-hook`? Thanks!

**Comment by gagbo** [comment]
That won’t fix the core issue anyway and your diagnostics won’t be synchronized with the server. It’s been summarized [there](https://github.com/joaotavora/eglot/issues/596) and you can also check the issue in [this repo](https://github.com/hlissner/doom-emacs/pull/4471) if you want more details (but it’s unedited messy discussion).

If you really want to fix flycheck-eglot integration, you’d need to add a timer that polls eglot regularly to get the list of diagnostics. I didn’t want to do that for 2 reasons :
- setting a poll delay for such a wide user-base is a nightmare (don’t want to create a new `company-idle-delay` stream of issues/discord questions)
- we kind of agreed that the root cause of the regression is something that should be fixed on eglot side to avoid having to dig into eglot’s internals

**Comment by HouzuoGuo** [comment]
@gagbo wow - that goes deep into a rabbit hole, looks like i have to be content with workarounds for a now.

**Comment by gagbo** [comment]
Another possibility is to add a `(package! eglot :pin "bb51d47dd6e59e5bef1bfb393a39a73a7811d0ee")` in your `~/.config/doom/packages.el` and run `doom sync -p`. But to be honest I’m not sure if rolling back Eglot won’t have other problems, I didn’t test it

**Comment by HouzuoGuo** [comment]
I had the doom-emacs module `:checkers syntax` enabled up until that point, flycheck appeared to me as disabled as soon as eglot successfully connects to its server:

- `SPC c x ` brought up an empty box.
- No text were marked with underscore that would indicate a checker's finding's been made on that line.

Then, purely out of curiosity I disabled the module `:chekcers syntax`, after a `doom sync -p` things surprisingly worked better..

- `SPC c x` brings up a box filled with FlyMake findings - e.g. compilation errors (understandably) and other hints (I am unsure where FlyMake gets this information)
- Text related to FlyMake's findings are displayed with underscore.
- FlyCheck remains enabled somehow! `C-c ! l` brings up FlyCheck's findings from the usual set of checkers! These findings do not overlap with FlyMake's findings.
- Text related to FlyCheck's findings are displayed with underscore.
- FlyCheck's findings are constantly updated according to the text.

So that turned out to be surprisingly handy! I can use the muscle memory of `SPC c x` to look at the more serious findings made by Eglot+FlyMake, and develop new muscle memory `C-c ! l` to look at FlyCheck's findings.

It seems hard to be sure whether this is the intended strat or components not working together. But I can definitely cope with this for now.

**Comment by HouzuoGuo** [comment]
This is the totally unexpected & weirdly functional setup in action:

![image](https://user-images.githubusercontent.com/563872/111883870-9322e680-89c6-11eb-8514-aef904d1fd87.png)

**Comment by gagbo** [comment]
It got discussed on Discord, javascript module pulls `tide` which pulls `flycheck` as a dependency. That’s why you still have both when you deactivated `:checkers syntax`. That also means you might have issues finding diagnostics for JS, but maybe not. If it works that’s cool though

**Comment by HouzuoGuo** [comment]
I managed to make the language server work with lsp-mode instead of eglot by adding the languge server as a lsp-mode backend, so eglot is now out of the equation.
