### ISSUE TITLE
`SPC w C-c` is bound to undefined command `ace-delete-window`

### ISSUE THREAD

**Issue by cubranic** [hlissner/doom-emacs#4831]
**What did you expect to happen?**

I expected to be able to select a window to delete.

**What actually happened?**

"Undefined command" error.

**Additional details:**

It looks like `ace` is either not installed or not active, because none of its commands are defined in my Emacs session. I've just recently installed Doom and don't have any customizations in my `.doom.d`.

Messages buffer:
```
## after pressing SPC w C-c:
command-execute: Wrong type argument: commandp, ace-delete-window
## after pressing F1 k SPC w C-c:
user-error: SPC w C-c is bound to ace-delete-window which is not a command
```
**System information:**

https://pastebin.com/70XFKbEk

**Comment by bnjmnt4n** [comment]
Looks like `ace-window` is installed as part of the [`:ui window-select` module](https://github.com/hlissner/doom-emacs/blob/0769b47cc84f15f9f546df0b6cd82c90c23d6b21/modules/ui/window-select/README.org). Maybe that code was leftover, and should be ported to the `:ui window-select` module as well?
