### ISSUE TITLE
LSP clangd indexing: too much precision for progress percentage

### ISSUE THREAD

**Issue by aurabindo** [hlissner/doom-emacs#4843]
**Expected**
Project indexing progress should be reported with at most two decimal digits

**Observed**
Progress being reported with 10+ digits after decimal

**Steps to reproduce:**
1. Install clangd 12
2. Open a C project and build to generate compile_commands.json
3. Enable lsp for cc mode in doom config
4. Set clangd as preferred server
4. Open project in Emacs for initial index to build

**System information:**

https://pastebin.com/eWQc6qHp

**Comment by hlissner** [comment]
This seems like an issue for [lsp-mode](https://github.com/emacs-lsp/lsp-mode/issues). Do you have any reason to suspect this is a Doom issue?

**Comment by aurabindo** [comment]
No, I will open a bug report with lsp-mode. Thanks
