### ISSUE TITLE
lua lsp server unzip filed on macOS

### ISSUE THREAD

**Issue by donneyluck** [hlissner/doom-emacs#4846]
macOS 11.2  
emacs 27.2

*message* buffer

```
LSP :: Download lua-language-server started.
LSP :: Starting to download https://marketplace.visualstudio.com/_apis/public/gallery/publishers/sumneko/vsextensions/lua/1.17.4/vspackage to /Users/donney/.emacs.d/.local/etc/lsp/lua-language-server/vs-lua.zip...
Contacting host: marketplace.visualstudio.com:443
Wrote /Users/donney/.emacs.d/.local/etc/lsp/lua-language-server/vs-lua.zip
LSP :: Finished downloading /Users/donney/.emacs.d/.local/etc/lsp/lua-language-server/vs-lua.zip...
LSP :: Decompressing /Users/donney/.emacs.d/.local/etc/lsp/lua-language-server/vs-lua.zip...
[/Users/donney/.emacs.d/.local/etc/lsp/lua-language-server/vs-lua.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /Users/donney/.emacs.d/.local/etc/lsp/lua-language-server/vs-lua.zip or
        /Users/donney/.emacs.d/.local/etc/lsp/lua-language-server/vs-lua.zip.zip, and cannot find /Users/donney/.emacs.d/.local/etc/lsp/lua-language-server/vs-lua.zip.ZIP, period.
LSP :: Decompressed /Users/donney/.emacs.d/.local/etc/lsp/lua-language-server/vs-lua...
LSP :: Server lua-language-server install process failed with the following error message: (file-missing Doing chmod No such file or directory /Users/donney/.emacs.d/.local/etc/lsp/lua-language-server/bin/macOS).
Check `*lsp-install*' and `*lsp-log*' buffer.
```

can't unzip vs-lua.zip   so lua lsp can't work

**Comment by innerout** [comment]
Without being sure, I think this is not a doom-emacs problem. It seems from your output that lsp-mode cant unzip vs-lua.zip. If you check the directories, that unzip searches for the file. Do you find the file there?

**Comment by donneyluck** [comment]
> Without being sure, I think this is not a doom-emacs problem. It seems from your output that lsp-mode cant unzip vs-lua.zip. If you check the directories, that unzip searches for the file. Do you find the file there?

yes file download success
but cant unzip 
not a zipfile

**Comment by hlissner** [comment]
As of c77cebf this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by donneyluck** [comment]
<img width="2368" alt="WeChatbd844edd86a2f419c69e18967dddf2cb" src="https://user-images.githubusercontent.com/60682638/114818643-b5a1f700-9dee-11eb-8d90-ac03e0327a5a.png">
<img width="2426" alt="WeChat5f871b4a329dbf90435d09107a95f4b4" src="https://user-images.githubusercontent.com/60682638/114818752-e41fd200-9dee-11eb-9996-27b6cfa73a9d.png">

**Comment by donneyluck** [comment]
I think the problem is   the download file lsp-server not zip file. not a doom-emacs problem
so what I can do
