### ISSUE TITLE
In eshell normal-mode using layout bepo, `c` is bound to `evil-collection-eshell-evil-change`

### ISSUE THREAD

**Issue by brabalan** [hlissner/doom-emacs#4847]
**What did you expect to happen?**
In eshell, normal-mode, using layout bepo, I would expect `c` to be bound to `evil-backward-char`.

**What actually happened?**
`c` is bound to `evil-collection-eshell-evil-change`.

**Additional details:**
These are the bindings for `c` in `eshell-mode`.
```
evil-collection-eshell-evil-change is an interactive function defined
in evil-collection-eshell.el.

Signature
(evil-collection-eshell-evil-change BEG END &optional TYPE REGISTER YANK-HANDLER DELETE-FUNC)

Documentation
Like evil-change but will not delete/copy the prompt.

Key Bindings
eshell-mode-map <normal-state> c
```

All three other movement keys (`t`, `s`, and `r`) are fine.

**Steps to reproduce:**
1. open an eshell
2. enter normal-mode
3. hit `c`

**System information:**
https://pastebin.com/pL15stRd

**Comment by hlissner** [comment]
@gagbo is the maintainer of the :input (layout +bepo) submodule. Hopefully he can offer some insight into this.

**Comment by gagbo** [comment]
The absence of a `eshell-mode-map-evil-collection-backup-map` in that `describe-key` _probably_ means that the evil-collection-hook did not run on eshell-map. I'll try to check that later, but I'll probably have a go first at info-mode

**Comment by gagbo** [comment]
It probably doesn’t run because the `setup` function doesn’t eagerly set the bindings but adds a [hook instead](https://github.com/emacs-evil/evil-collection/blob/master/modes/eshell/evil-collection-eshell.el#L141). Adding another hook that rotates the keymap on that `'eshell-first-time-mode-hook` might be the solution
