### ISSUE TITLE
In info-mode using bepo layout, `t` and `s` have wrong bindings

### ISSUE THREAD

**Issue by brabalan** [hlissner/doom-emacs#4848]
**What did you expect to happen?**
In info-mode using layout bepo, I would expect `t` to be bound to `evil-next-line` and `s` to be bound to `evil-previous-line`.

**What actually happened?**
`t` is bound to `Info-top-node` and `s` is bound to `Info-search`.

**Additional details:**
These are the bindings for `t` in `info-mode`.
```
Info-top-node is an interactive and compiled function without a source
file.

Signature
(Info-top-node)

Documentation
Go to the Top node of this file.

Key Bindings
Info-mode-map <
Info-mode-map <normal-state> g t
Info-mode-map t
evil-collection-Info-mode-map-normal-state-backup-map g t
```

And the ones for `s`.
```
Info-search is an interactive and compiled function without a source
file.

Signature
(Info-search REGEXP &optional BOUND NOERROR COUNT DIRECTION)

Documentation
Search for REGEXP, starting from point, and select node it's found in.

If DIRECTION is backward, search in the reverse direction.

Key Bindings
Info-mode-map <normal-state> k
Info-mode-map s
evil-collection-Info-mode-map-normal-state-backup-map s
```

The other movement keys (`c` and `r`) are fine.

**Steps to reproduce:**
1. open info
3. hit `t` or hit `s`

**System information:**
https://pastebin.com/pL15stRd

**Comment by hlissner** [comment]
@gagbo is the maintainer of the `:input (layout +bepo)` submodule. Hopefully he can offer some insight into this.

**Comment by gagbo** [comment]
Can you try unmapping t and s from Info mode map :
```lisp
(map! :map Info-mode-map "s" nil)
(map! :map Info-mode-map "t" nil)
```
It looks like the same kind of issue as the magit one

https://github.com/hlissner/doom-emacs/blob/51864a731eea0b9b9e7a186aa47c031bc3b5f84e/modules/input/layout/%2Bbepo.el#L191-L204

**Comment by brabalan** [comment]
Removing the bindings work, but the `after!` does not trigger (I have to evaluate the `map!` directly).

**Comment by gagbo** [comment]
I probably didn't choose the correct feature, I'll search
