### ISSUE TITLE
Device 1 is not a termcap terminal device

### ISSUE THREAD

**Issue by dorneanu** [hlissner/doom-emacs#4849]
**What did you expect to happen?**

I wanted to call M-X in order to select a capture template.  My org-capture settings:

```
(after! org-capture
    (setq org-capture-templates
          '(("t" "Todo" entry (file+headline "~/work/sync/org/inbox.org" "Tasks")
             "* TODO  %?\n")

            ("m" "Meeting" entry (file+headline "~/work/sync/org/inbox.org" "Meetings")
             "* MEETING  %?\nSCHEDULED: %t\n%U\n%a\n")

            ("b" "Bookmark (Clipboard)" entry (file+headline "~/work/sync/org/bookmarks.org" "Bookmarks")
             "** %(org-web-tools-insert-link-for-clipboard-url)\n:PROPERTIES:\n:TIMESTAMP: %t\n:END:\n%?"  :prepend t)

            ("s" "Code Snippet" entry
             (file+headline "~/work/sync/org/inbox.org" "Snippets")
             "* %?\t%^g\n#+BEGIN_SRC %^{language}\n\n#+END_SRC")

            ("j" "Journal" entry (file+olp+datetree "~/work/sync/org/journal.org")
             "*  %?\n")))
)

```

**What actually happened?**

When I try to select t for TODO I get:

```
Device 1 is not a termcap terminal device
```

**Additional details:**

**Steps to reproduce:**

1. `M-X` 
2. Select `t` 

**System information:**
https://pastebin.com/rBGF71mP

**Comment by hlissner** [comment]
Your steps to reproduce are incomplete. I assumed you mean `M-x org-todo` then `t`.

In which case, I cannot reproduce this. I suspect this is a private config issue. Please [try to reproduce the issue in the sandbox](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#testing-in-dooms-sandbox) without your private config. I will reopen this once I have more leads to investigate it.

**Comment by dorneanu** [comment]
Sorry, I've meant `SPC X` then I see `Select a capture template` and select `t`. But after restarting emacs, the problem is gone. I'll try to provide steps you can also reproduce.
