### ISSUE TITLE
Initial quotes in LaTeX documents are not being inserted correctly

### ISSUE THREAD

**Issue by UndeadKernel** [hlissner/doom-emacs#485]
When inserting quotes in LaTeX documents using the `"` character, it is expected that the characters `` `` `` are first inserted. Instead, the characters ` ``` ` are inserted.

I suspect that `smartparens-mode` is interacting in strange ways here.

**Comment by hlissner** [comment]
Odd. I've [disabled smartparens-latex in lang/latex](https://github.com/hlissner/doom-emacs/blob/develop/modules/lang/latex/config.el#L22-L26). Perhaps this is no longer effective?

Please check two things for me:

1. That `sp-pairs` _doesn't_ contain an entry to `latex-mode`, `LaTeX-mode`, `tex-mode` or `plain-tex-mode`,
2. If adding `(provide 'smartparens-latex)` to your init.el or config.el resolves your issue.

**Comment by UndeadKernel** [comment]
There does not seem to be any references to those modes you mention. You can find the contents of `sp-pairs` [here](https://pastebin.com/tEs5S1dT). I warn you, the formatting is a mess.

I have also tried option 2 without success.

In case it matters, I have copied the `smartparens` settings you have in your private config. Of course I also tried disabling those changes without effect.

**Comment by hlissner** [comment]
Thanks for tracking this down! I'll look into it soon.

**Comment by hlissner** [comment]
Sorry for the late followup. The lang/latex module has changed a great deal. Are you still experiencing this issue?

**Comment by hlissner** [comment]
Due to inactivity, I'll assume this issue has been resolved. Feel free to follow up here if that isn't the case.
