### ISSUE TITLE
`dd` command does not remove last line of buffer in org-mode when the line is empty

### ISSUE THREAD

**Issue by DNLZ** [hlissner/doom-emacs#4859]
**What did you expect to happen?**
When using the delete line command (`dd`) on the last line of a buffer in org-mode, the line is not deleted.

Note: this only happens when the last line of the file is empty.

**What actually happened?**

https://user-images.githubusercontent.com/1908828/114769779-df441b00-9d27-11eb-97ae-43e90c5bf4fd.mov

Notice a few lines of text are deleted, but the delete-line command stops working when the end of the file is reached.

**Additional details:**
This used to work fine in previous versions. I encountered this issue both on my Mac and Linux machines.

**Steps to reproduce:**
See above 

**System information:**
https://pastebin.com/50Nfy9LC

**Comment by hlissner** [comment]
Duplicate of https://github.com/hlissner/doom-emacs/issues/2447

Caused by an upstream issue in evil.

Quick fix: https://github.com/hlissner/doom-emacs/issues/2447#issuecomment-792832677

**Comment by hlissner** [comment]
Actually, this may be an issue with [evil-org](https://github.com/hlissner/evil-org-mode) rather than evil or Doom, since I can reproduce it regardless of `evil-respect-visual-line-mode`'s value. 

I'll reopen this for now.

**Comment by DNLZ** [comment]
Interesting. The quick fix of adding `(setq evil-respect-visual-line-mode nil)` to `init.el` fixed the issue for me.
