### ISSUE TITLE
Scheme - geiser doesn't seem to work

### ISSUE THREAD

**Issue by cmcclellen** [hlissner/doom-emacs#4863]
It looks like geiser cannot start a REPL.  It seems to assume that one has installed a submodule named geiser-XXXX,
ie geiser-chez, geiser-mit  etc in order to start a repl.

if you add (package! geiser-chez) or any of the other geiser submodules, Doom will fail to initialize.

**What did you expect to happen?**
Doom should come up and be able to start a scheme repl with Geiser

**What actually happened?**
Doom starts with the error: 

```
Symbol's function definition is void: geiser-impl--add-to-alist
```

Each geiser-XXX submodule causes a slightly different error, but it is usually the same type (void definition), but just for different symbols.  It is probably dying on the first geiser-impl symbol in each geiser submodule.

**Additional details:**

**Steps to reproduce:**
1.  Enable scheme in init.el
2. add (package! geiser-chez) to packages.el
3. doom sync
4. run emacs

**System information:**
https://pastebin.com/2E2iTqRi

**Comment by hlissner** [comment]
Seems the recent reworking of geiser kind of broke all our support for it. As of 32cf114 the `:lang scheme` now has flags for each of the implementations. e.g. `:lang (scheme +mit)` will install geiser-mit` for you, and should resolve this issue in particular.

In any case this issue can now be considered resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by cmcclellen** [comment]
Thanks for that.  It seems to work fine, however when I ran doom sync after a successful install of (scheme +chez),
I get:

```
x There was an unexpected error
    Message: Symbol's function definition is void
    Data: (void-function . geiser-impl--add-to-alist)
    Backtrace:
      (geiser-impl--add-to-alist 'regexp "\\.def$" 'chez t)
      (eval-buffer #<buffer  *load*-788256> nil "/Users/cmcclellen/.emacs.d/.loc
      (load-with-code-conversion "/Users/cmcclellen/.emacs.d/.local/straight/bui
      (load "/Users/cmcclellen/.emacs.d/.local/straight/build-27.2/geiser-chez/g
      (progn (load autoloads-file nil 'nomessage))
      (if (file-exists-p autoloads-file) (progn (load autoloads-file nil 'nomess
      (let ((autoloads-file (straight--autoloads-file package))) (if (file-exist
      (straight--load-package-autoloads "geiser-chez")
      (let ((name (symbol-name package))) (add-to-list 'load-path (directory-fil
      (let ((package (car --dolist-tail--))) (straight-register-package package)
```

The solution for now is to comment out scheme; sync; uncomment scheme; sync again.

**Comment by hlissner** [comment]
65bc279 should fix your new issue.

**Comment by cmcclellen** [comment]
You are awesome!

**Comment by hlissner** [comment]
Ack, as it turns out this is not the perfect fix. Really, this is an upstream issue, with `geiser-chez` using `geiser-impl--add-to-alist` in its autoloads file, but `geiser` no longer autoloads this function, so `geiser-chez` won't know where to look for it. There are a pile of hacks I could tack onto the `:lang scheme` module to workaround this, but the proper solution would be to remove the `;;;###autoload` over [this line](https://gitlab.com/emacs-geiser/chez/-/blob/master/geiser-chez.el#L256) in `geiser-chez`.

I'll formulate a PR for this when I can, but am currently swamped. Feel free to snipe the opportunity if you'd like.

**Comment by cmcclellen** [comment]
I submitted a merge request ([here](https://gitlab.com/emacs-geiser/geiser/-/merge_requests/1).  I wasn't able to get the defsubst working for whatever reason, but the autoload in geiser-impl did the trick.

**Comment by hlissner** [comment]
@cmcclellen Thanks for the fix!

I've bumped geiser in c370a0b, so this issue should be resolved. Let me know if that isn't the case and I'll reopen it.
