### ISSUE TITLE
Warning: Use keywords rather than deprecated positional arguments to `define-minor-mode' on Emacs 28

### ISSUE THREAD

**Issue by gjm** [hlissner/doom-emacs#4865]
I have this warning when starting Emacs 28:

```
modules/tools/debugger/config.el: Warning: Use keywords rather than deprecated positional arguments to `define-minor-mode'
```

I know Doom doesn't officially support Emacs 28 but here's the report, for future actions...

**System information:**

https://pastebin.com/ps8rQngD

**Comment by hlissner** [comment]
As of 9218473 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
