### ISSUE TITLE
Unable to get the scheme repl with geiser

### ISSUE THREAD

**Issue by abhi18av** [hlissner/doom-emacs#4869]
**What did you expect to happen?**
Launch the chez scheme repl.

**What actually happened?**
I came across the error 'Cannot find chez implementation`.

Upon launching the `run-geiser` command it prompts correctly for `which scheme` however, once I select the `chez` (or `guile`) it displays the error message.

**Additional details:**
- I have simply uncommented the `scheme` lang in the `init.el` file.
- I have tried the solution outlined in https://github.com/hlissner/doom-emacs/issues/2263 but not much 
- I noticed that recently the `geiser` package has been split into multiple sub-projects like `geiser`, `geiser-chez`, `geiser-guile` as observed here https://gitlab.com/emacs-geiser

**Steps to reproduce:**
1. Open any file with `scm` suffix
2. Execute `run-geiser` and select the 

**System information:**

```
  generated  Apr 15, 2021 12:02:58
     distro  MacOS 10.15.6 Darwin 19.6.0 x86_64
      emacs  27.1 ~/.emacs.d/
       doom  2.0.9 grafted, HEAD -> develop, origin/develop, origin/HEAD ce65645 2021-03-27 18:27:19 -0400 ~/.doom.d/ -> ~/.doom.d/
      shell  /usr/local/bin/bash
   features  RSVG IMAGEMAGICK GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS XIM NS MODULES THREADS JSON PDUMPER LCMS2 GMP
     traits  batch server-running envvar-file
    modules  :completion company ivy :ui deft doom doom-dashboard doom-quit fill-column hl-todo hydra indent-guides ligatures modeline nav-flash ophints (popup +defaults) tabs treemacs unicode vc-gutter vi-tilde-fringe window-select workspaces zen :editor (evil +everywhere) file-templates fold multiple-cursors parinfer rotate-text snippets word-wrap :emacs dired electric ibuffer undo vc :term eshell vterm :checkers syntax :tools debugger direnv docker editorconfig ein (eval +overlay) gist lookup lsp magit make prodigy rgb taskrunner tmux upload :os macos :lang cc clojure data emacs-lisp ess json julia markdown ocaml org python racket rest rst scheme sh yaml :app calendar :config (default +bindings +smartparens)
   packages  (dired-hacks-utils) (dired-filter) (dired-avfs) (dired-open) (dired-rainbow) (dired-subtree) (dired-ranger) (powershell) (shx) (kubernetes) (kubernetes-evil) (org-ql) (golden-ratio) (tree-sitter) (tree-sitter-langs) (groovy-mode) (nextflow-mode :recipe (:host github :repo emiller88/nextflow-mode))
       elpa  which-key undo-tree rainbow-mode expand-region easy-kill diff-hl company avy ace-window


```

**Comment by hlissner** [comment]
`geiser` has changed recently and the `:lang scheme` module had to change to adapt. It now offers flags for each of the implementations.

Enable `:lang (scheme +chez)`.

**Comment by abhi18av** [comment]
Wow, it's always great to find something that's already fixed 😊 

Thanks for the awesome work @hlissner !

**Comment by abhi18av** [comment]
Just a quick follow-up, could you please point me to the right direction to fix the auto-completion for `scheme`?

```
Company: An error occurred in auto-begin
Company: backend company-capf error "No Geiser REPL for this buffer (try M-x run-geiser)" with args (prefix)
```

**Comment by hlissner** [comment]
You need an open REPL for completion to work. Try `M-x run-geiser`.

**Comment by abhi18av** [comment]
Hmm, yes I tried out that suggestion. However, I have realised that this is working as expected only for `guile` only and not for `chez`, therefore it probably isn't related to the `doom` configs or setup but rather something specific to `geiser-chez`. I'll initiate the conversation here https://gitlab.com/emacs-geiser/chez.

**Comment by abhi18av** [comment]
Hmm, and the plot thickens 🤔 

Upon enabling 
```
:lang (scheme +chez)
```

The first time I run `doom sync`, it works fine and downloads the correct packages. However, once I start tweaking, for example adding `(setq geiser-chez-binary (executable-find "chez"))` to my `config.el` and doing the `doom sync` again (while tweaking something else), I run into the following error 

```
x There was an unexpected error
    Message: Symbol's function definition is void
    Data: (void-function . geiser-impl--add-to-alist)
    Backtrace:
      (geiser-impl--add-to-alist 'regexp "\\.def$" 'chez t)
      (eval-buffer #<buffer  *load*-263938> nil "/Users/eklavya/.emacs.d/.local/
      (load-with-code-conversion "/Users/eklavya/.emacs.d/.local/straight/build-
      (load "/Users/eklavya/.emacs.d/.local/straight/build-27.1/geiser-chez/geis
      (progn (load autoloads-file nil 'nomessage))
      (if (file-exists-p autoloads-file) (progn (load autoloads-file nil 'nomess
      (let ((autoloads-file (straight--autoloads-file package))) (if (file-exist
      (straight--load-package-autoloads "geiser-chez")
      (let ((name (symbol-name package))) (add-to-list 'load-path (directory-fil
      (let ((package (car --dolist-tail--))) (straight-register-package package)

```


I've attached the full `doom.error.log` here. 

[doom.error.log](https://github.com/hlissner/doom-emacs/files/6321384/doom.error.log)

**Comment by hlissner** [comment]
65bc279 should fix your new issue.

**Comment by abhi18av** [comment]
Yeah, this patch fixed the `doom sync` issue  🎉 

The completion error for `chez` https://github.com/hlissner/doom-emacs/issues/4869#issuecomment-820644404  is something I guess I should report to the `geiser-chez` repo

**Comment by NightMachinary** [comment]
I still get `geiser-impl--set-buffer-implementation: Cannot find chez implementation` even after setting `(setq geiser-chez-binary (executable-find "chez"))` (which will be set to `"/usr/local/bin/chez"`).

**Comment by hlissner** [comment]
@NightMachinary Please create a new issue.
