### ISSUE TITLE
Difficulty in customizing keybindings for elixir-mode/alchemist

### ISSUE THREAD

**Issue by bitwalker** [hlissner/doom-emacs#487]
### Observed behavior

I'm newly converted to doom, thanks so much for this great project! I've been looking to escape Spacemacs and get deeper into a configuration that I can actually understand, and so far I feel very at home with what you've built!

The one thing I've been trying to get set up though is keybindings for a number of `alchemist` commands to work via the localleader, it seems by default there are no elixir-mode/alchemist keybindings bound to the localleader, so `SPC-m` just says it isn't bound inside an Elixir buffer.

I've tried a couple things to make this work (inside `init.el` of my private module):

```elisp
(def-package-hook! alchemist
  :post-config
  (map! :map elixir-mode-map
            :localleader
            :n "c" #'alchemist-compile-this-buffer))
```

This never worked for me, I also tried `:pre-config`, returning `t` at the end, but no joy. I was able to verify that the hook was called by using `(message ...)` but the keybindings never seemed to work.

I also tried using `after!` and `after-hook!`, but again, no joy. However if I added the keybinding inside the `def-package!` config block for `alchemist`, it _did_ work. I assume I'm doing something stupid here, or using something wrong, but after reading through a lot of the doom source, I don't feel like I'm any closer to understanding why the `map!` call is being ignored. It's probably because I still don't fully understand some parts of Emacs, so bear with me if this is an obvious mistake on my part

P.S.: I just updated develop to `8a74a081` and now any `map!` or `after-hook!` calls in my private `init.el` file are resulting in "Symbol's function definition is void" errors. No matter what `make` command I run, other than `doctor`, it fails with this.

### Expected behavior

Basically, I want to `SPC-m c` in my Elixir buffers (to use the example binding from above) to compile the buffer. I would expect that the keybinding that I've defined, in one of the various ways I've tried above, would have that effect. Assuming I've missed something here, some pointers to dealing with keybindings like this would be a great addition to the docs (for which I'm happy to help via PR!).

### Steps to reproduce

1. Use one of the methods above to try to bind `<localleader> c` to the `alchemist-compile-this-buffer` command in Elixir buffers
2. Open an Elixir buffer with the following code in it for funsies:
```elixir
defmodule Foo do
  def hello(name), do: IO.puts "Hello #{name}"
end
Foo.hello("bitwalker")
```
3. Try to compile the buffer with `<localleader> c`

### System information

macOS 10.12.6

```
﻿Doom Doctor
Emacs v25.3.1
Doom v2.0.9 (8a74a081)
shell: /bin/bash
Compiled with:
  JPEG RSVG IMAGEMAGICK DBUS NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS
  MODULES
uname -a:
  Darwin ogier.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT
  2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64

----

test-emacs
test-windows
test-fonts
test-gnutls
test-tls
Validated https://elpa.gnu.org
Validated https://melpa.org
Successfully rejected https://self-signed.badssl.com
Successfully rejected https://wrong.host.badssl.com/
test-tar
Warning: BSD tar detected
  QUELPA (through package-build) uses the system tar to build plugins, but it
  expects GNU tar. BSD tar *could* cause errors during package installation or
  updating from non-ELPA sources.  MacOS users can install gnu-tar via homebrew:
  brew install gnu-tar

----
Attempt to load DOOM: success! Loaded v2.0.9
test-modules
Loading /Users/paulschoenfelder/.emacs.d/modules/feature/snippets/packages.el (source)...
  > (:lang cc) Couldn’t find the rtag client and/or server programs
    (rdm rc). Disabling rtags support
Loading /Users/paulschoenfelder/.emacs.d/.local/cache/company-stats-cache.el (source)...
  > (:lang cc) Irony server isn’t installed. Run M-x
    irony-install-server
  > (:lang cc) Couldn’t find glslangValidator. GLSL code completion
    is disabled
  > (:lang crystal) Couldn’t find icr. REPL will not work
  > (:lang go) Couldn’t find guru. Refactoring commands (go-guru-*)
    won’t work
  > (:lang go) Couldn’t find gore. REPL will not work
  > (:lang go) Couldn’t find gocode. Code completion won’t work
  > (:lang haskell) Couldn’t find stack. Intero will not work
  > (:lang plantuml) Couldn’t find plantuml.jar. Install it with-x
    +plantuml/install
  > (:lang rust) Couldn’t find the racer binary at ‘racer-cmd’
  > (:lang rust) Couldn’t find Rust’s source code at RUST_SRC_PATH
    or ‘racer-rust-src-path’.

----
There were 12 issues!
```

**Comment by hlissner** [comment]
I have discovered what the issue is: `map!` is expanded really early, and when it's called from your private init.el (which is loaded before any modules are), you can be guaranteed that `evil` isn't loaded yet. When `map!` detects that evil isn't present, it simply ignores evil keybinds.

A revision of the keybinding system is planned, so this won't be addressed yet, but getting around it is simple enough (see below).

> P.S.: I just updated develop to 8a74a081 and now any map! or after-hook! calls in my private init.el file are resulting in "Symbol's function definition is void" errors.

This suggests that you have tried to bind to `elixir-mode-map` before elixir-mode has been loaded. Try wrapping it in an after! block, either:

```elisp
;; in your private config.el
(after! elixir-mode
  (map! :map elixir-mode-map
        :n "c" #'alchemist-compile-this-buffer))
;; OR
(map! :after elixir-mode
      :map elixir-mode-map
      :n "c" #'alchemist-compile-this-buffer)
;; OR
(map! :after elixir-mode
      :map elixir-mode-map
      :n "c" #'alchemist-compile-this-buffer)
```

(Also, when you said `after-hook!` calls, I assume you meant `add-hook!`, because `after-hook!` doesn't exist)

**Comment by hlissner** [comment]
Side-note: perhaps you should try:

```elisp
;; config.el
(setq alchemist-key-command-prefix (kbd doom-localleader-key))
```

This will bind [all of these alchemists keys](https://github.com/tonini/alchemist.el/blob/master/alchemist.el#L129-L210) to the localleader.

**Comment by bitwalker** [comment]
Ah nice, your last comment is more or less what I was looking for :)

I should've mentioned that the void function in the error message was `map!` the first time, but you are correct, I typo'd `after-hook!` instead of `add-hook!` so that was my bad. Not sure why `map!` was failing with that error as well, but I think you are correct about the `elixir-mode-map` bit. I had tried `:after` before (as well as `after!`) with no luck in getting the keybindings to work, but binding the alchemist prefix was ultimately all I needed for now, so I'm content to wait for the revisions you have planned!

Thanks for the quick response! I'll close this for now and keep an eye out for those changes you mentioned.
