### ISSUE TITLE
show gitgutter for dotfiles in git bare repos like yadm, dotbare

### ISSUE THREAD

**Issue by pasha009** [hlissner/doom-emacs#4871]
I am trying to activate gitgutter for buffers where the file opened is managed by [`yadm`](https://github.com/TheLocehiliosan/yadm).

**How can i tell gitgutter to look for the git directory in my custom folder ?**

I tried changing `GIT_DIR` and `magit-git-global-arguments` locally if the file is managed by yadm.
The variables are changed correctly depending on the buffer but i don't see a change in gitgutter.

```elisp
(defun yadm-file-hook ()
  (make-local-variable 'magit-git-global-arguments)
  ;; (make-local-variable 'process-environment)
  (when (-contains?
         (cl-delete-if-not
          #'file-exists-p
          (process-lines "yadm-full")) (buffer-file-name))
    (add-to-list 'magit-git-global-arguments "--git-dir=/home/pasha/.local/share/yadm/repo.git")
    (add-to-list 'magit-git-global-arguments "--work-tree=/home/pasha/")
    ;; (setq process-environment
    ;;       (cons "GIT_DIR=/home/pasha/.local/share/yadm/repo.git" process-environment))
    ))

(add-hook 'find-file-hook 'yadm-file-hook)
```
Note:  `yadm-full` just adds /home/pasha/ to the start of filenames (i couldn't do it in elisp)
```bash
#!/usr/bin/zsh
cd
yadm ls-files | awk '{print "/home/pasha/"$0}'
```

**Comment by hlissner** [comment]
Not an issue with Doom. Please ask upstream or on reddit.
