### ISSUE TITLE
Broken icons on the dashboard

### ISSUE THREAD

**Issue by savageCW** [hlissner/doom-emacs#4876]
**What did you expect to happen?**
Fresh install of doom emacs on gentoo. I have installed doom emacs on other distro's and they seem to work well. I believe I have all the requirements installed and there were errors upon installation. I have checked all the broken icon bug reports and tried all the solutions (fonts exist and tried doom sync, doom install, doom build), however, this time it is not working.

**What actually happened?**
![image](https://user-images.githubusercontent.com/9919271/115098068-40aafa80-9f71-11eb-87e6-1ea9d513a865.png)

**Additional details:**

no errors or warning from (M-x view-echo-area-messages)
Doom loaded 138 packages across 29 modules in 1.416s

**Steps to reproduce:**
1. Select these example steps,
2. Delete them,
3. Replace them with precise steps to reproduce your issue.
4. Include code samples, keybinds, and commands.
5. Please don't skimp on details.
6. Then fill in "system information" below or this issue will be deleted.

**System information:**
  generated  Apr 17, 2021 11:29:44
     distro  Gentoo/Linux Linux 5.10.27-gentoo x86_64
      emacs  27.1 ~/.emacs.d/
       doom  2.0.9 grafted, HEAD -> develop, origin/develop, origin/HEAD ce65645 2021-03-27 18:27:19 -0400 ~/.doom.d/ -> ~/.doom.d/
      shell  /bin/bash
   features  XPM JPEG TIFF GIF PNG RSVG SOUND GPM DBUS GLIB NOTIFY INOTIFY ACL GNUTLS ZLIB GTK3 X11 XDBE XIM THREADS PDUMPER LCMS2 GMP
     traits  gui server-running envvar-file
    modules  :completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline ophints (popup +defaults) vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold snippets :emacs dired electric undo vc :checkers syntax :tools (eval +overlay) lookup magit :lang emacs-lisp markdown org sh :config (default +bindings +smartparens)
       elpa  ht emojify dash

**Comment by hlissner** [comment]
See https://github.com/hlissner/doom-emacs/blob/develop/docs/faq.org#strange-or-incorrect-icons-are-displayed-everywhere

**Comment by TheGreatMcPain** [comment]
@savageCW

In order for the fonts to render correctly on Gentoo you need to enable the `xft` use-flag for `app-editors/emacs`.

This can be done like so...

```
# echo "app-editors/emacs xft" >> /etc/portage/package.use/emacs
```
