### ISSUE TITLE
Dired no longer sorts directories first

### ISSUE THREAD

**Issue by jpcima** [hlissner/doom-emacs#4877]
After the commit 33af1f9 which fixes the issue #3939, dired no longer sorts the directories first.

The introduced condition `(not (bound-and-true-p ls-lisp-use-insert-directory-program))` evaluates to true.
It's because the package `ls-lisp` was not loaded, hence `ls-lisp-use-insert-directory-program` is not bound.

Loading `ls-lisp` is the obvious workaround, but without a doubt this would be better explicitly written in code.

GNU Emacs 27.2

**Comment by hlissner** [comment]
As of dec1583 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
