### ISSUE TITLE
Doc: envar file

### ISSUE THREAD

**Issue by ShalokShalom** [hlissner/doom-emacs#4880]
Why do you prompt me into a y/n and then give me no indication, why I could choose one or the other?

I strongly suggest to make clear, what is a good default.

![Screenshot_2021-04-17-21-41-32-39_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/6344099/115125040-f9028e00-9fc5-11eb-9296-72568882410f.jpg)

**Comment by hlissner** [comment]
Moved to #4273
