### ISSUE TITLE
+lookup/file opens URLs twice

### ISSUE THREAD

**Issue by io12** [hlissner/doom-emacs#4882]
**What did you expect to happen?**

When the cursor is over a URL, `g f RET` should open the URL once, and not have any second prompt on the minibuffer.

**What actually happened?**
The "Find file or URL" prompt opens twice, and the URL is opened twice if `RET` is pressed for both.

**Additional details:**

I think this is technically defined behavior, since the docs for `+lookup/file` contains
```
Each function in +lookup-file-functions is tried until one changes the point
or the current buffer.

Otherwise, falls back on find-file-at-point.
```

Since opening a URL in the browser doesn't move the point or the current buffer, that explains this behavior, but the defaults lead to URLs being opened twice.

**Steps to reproduce:**
1. Enter a URL in fundamental-mode
2. Move point over URL
3. `g f RET RET`
4. URL is opened twice in a browser

**Comment by hlissner** [comment]
As of d7de911 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by io12** [comment]
I can confirm it's resolved, thanks!
