### ISSUE TITLE
Getting error when trying to install doom emacs 

### ISSUE THREAD

**Issue by vivek-ram** [hlissner/doom-emacs#4884]
I was getting an error when trying to install doom emacs on Mac
Fatal error 4: Illegal instruction
/Users/vivekd/.emacs.d/bin/doom: line 5: 10547 Abort trap: 6           $EMACS --no-site-file --script "$0" -- "$@"

**Comment by hlissner** [comment]
Try rebuilding/reinstalling Emacs. This is a macOS error that occurs when you run a program (emacs, in this case) that was built for an older version of macOS. As I'm not a macOS expert, I have no more insight on the matter.

Since this is not a Doom issue I will close this.
