### ISSUE TITLE
`+ivy-buffer-preview` doesn't work on `SPC b B`

### ISSUE THREAD

**Issue by FollieHiyuki** [hlissner/doom-emacs#4886]
**What did you expect to happen?**
Press `SPC b B` and get buffer previewing

**What actually happened?**
`M-x +ivy/switch-buffer` has buffer previewing while `SPC b B` (ivy-switch-buffer) doesn't.

**Additional details:**

**Steps to reproduce:**
1. Install vanilla doom-emacs
2. Put `(setq +ivy-buffer-preview t)`  into config.el
3. Reload doom emacs

**System information:**

https://pastebin.com/iEH7YxKA

**Comment by hlissner** [comment]
As of a0de71d this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by FollieHiyuki** [comment]
Thanks. The key bind works correctly now.
