### ISSUE TITLE
Doom Emacs freezes when I try to touch or open a C/C++ file.

### ISSUE THREAD

**Issue by lisboaigor** [hlissner/doom-emacs#4887]
Hi guys! Doom Emacs is freezing when I try to touch or open a C/C++ file through dired.
I tried to disable the C/C++ support on my init.el and rebuild the configuration but still freezes.
I also tried to remove Doom Emacs and test this issue on default Emacs, it worked correctly. '-'

I belive this is a bug. Can someone help me get around this issue?

**Comment by gagbo** [comment]
Hello,

If you don’t follow the issue template before posting, it’ll get closed. Just a heads up.

**Comment by lisboaigor** [comment]
> Hello,
> 
> If you don’t follow the issue template before posting, it’ll get closed. Just a heads up.

Ok, I'm new here. Sorry.
