### ISSUE TITLE
bin/doom upgrade: fails while updating packages; failing to resolve hosts during git fetch

### ISSUE THREAD

**Issue by ChemiKyle** [hlissner/doom-emacs#4888]
**What did you expect to happen?**
`./bin/doom upgrade` completes on first try.

**What actually happened?**
`./bin/doom upgrade` fails (randomly?) while fetching packages.  
stdout states (angle brackets mine):

```
The package manager threw an error
      fatal: unable to access 'https://<host>/<user>/<repo>.git/': Could not resolve host: <host>
```

The package it fails on is different every time, and is not limited to github as I occasionally observe failures for gitlab. If I'm very unlucky, it fails on one of the recipes, e.g. https://github.com/emacs-straight/ repos. Repeatedly running eventually updates all packages.

**Additional details:**

#### Updating packages
Here's the [doom.error.log file](https://pastebin.com/wKhDquTD) for it failing on `epl`, [another](https://pastebin.com/7KsWEgXP) where it failed on `hydra`, and [one more](https://pastebin.com/R7NkpYD3) where it failed on `shrink-path.el`.  
These logs are largely similar, but the last one fails to resolve gitlab and occurred during an actual upgrade to Doom Emacs

#### Updating recipe repos
Slightly different is [a recipe failure](https://pastebin.com/Df8N3Pkg) for `gnu-elpa-mirror`

**Steps to reproduce:**
1. Run `doom upgrade` from a terminal
1. Observe failure

**System information:**

I am reporting this on my Debian Testing machine, but this also occurs on my Manjaro laptop (and maybe my work Macbook).

[Debian PC](https://pastebin.com/eALwH6qh)  
[Manjaro laptop](https://pastebin.com/YtaXYuLd)

**Comment by hlissner** [comment]
This seems like a networking issue. Not sure there's much I or Doom can do here. All straight (our package manager) does is call `git clone`. At most, it could be a misconfiguration of git, any involved proxies/VPNs, or [github credentials aren't set up correctly](https://docs.github.com/en/github/getting-started-with-github/updating-credentials-from-the-macos-keychain).

Until I have reason to suspect this is Doom issue I will close this, but feel free to continue the discussion here.

(This project will soon adopt [Discourse](https://discourse.doomemacs.org) as our primary issue tracker, so I am closing in-actionable or unverif{ied,iable} issues on our Github)

**Comment by ChemiKyle** [comment]
@hlissner thanks for the quick response! I'd suspected a network issue as well, but since it fails randomly - and doesn't fail at all on my work laptop - I figured I would log an issue just in case.
