### ISSUE TITLE
Modifying a package! recipe can leave in an inconsistent state

### ISSUE THREAD

**Issue by indigoviolet** [hlissner/doom-emacs#4893]
**What did you expect to happen?**

I modified a recipe to point at a different fork/branch to test a PR:

`(package! annotate :recipe (:host github :repo "bastibe/annotate.el"))`

to 

`(package! annotate :recipe (:host github :repo "cage2/annotate.el" :branch "prevent-prompt-annotating-newline"))`

I would have expected this to purge the old repo directory and build the new one, but nothing happens (since it thinks no changes are needed).

If I comment out the `package!` line, `doom sync`, then it says `purged build/annotate`, and then uncomment and sync again, it uses the old checkout and builds from there, so that the build is not actually matching the recipe. This is somewhat insidious because there isn't any messaging that would warn about it.

**What actually happened?**

The build no longer matched the recipe.

**Additional details:**

**Steps to reproduce:**
1. Start with a package! recipe that uses git
2. sync
3. now change the recipe to point to a fork or a branch (`:fork` or `:branch`) or a different host
4. sync --> no changes will be detected by the build
5. comment out the recipe and sync --> build will be purged (but not repo)
6. uncomment the recipe and sync --> build will use the old repo

**System information:**
https://pastebin.com/pRRvb59L

**Comment by hlissner** [comment]
To quote "[Changing a recipe for an included package](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#changing-a-recipe-for-an-included-package)" in the docs:

> IMPORTANT: Remember to run doom sync -u after changing recipes for existing packages. At the time of writing, doom sync alone will not pick up on recipe changes.

After #4273 is done, `doom sync` alone will be enough to detect recipe changes, but for now `-u` is necessary.

**Comment by indigoviolet** [comment]
Thanks and sorry for the noise, I searched the issues but didn't find a dupe - should've looked in the docs. (Noticed the `delete me` label on this issue, might be worth keeping around to avoid this scenario)
