### ISSUE TITLE
+lookup/references doesn't go to the found reference

### ISSUE THREAD

**Issue by thiagokokada** [hlissner/doom-emacs#4894]
**What did you expect to happen?**

`g D` (`+lookup/references`) finds a reference but when you select a reference by using `Enter` key it doesn't go to the reference (unless this reference is on the same file). `lsp-find-references` works as expected.

Not sure if it is only happening with `+lsp`, but I use `(clojure +lsp)` so this maybe the cause.

Same report as this [issue's comment](https://github.com/hlissner/doom-emacs/issues/4771#issuecomment-798942656), however I am posting again since the other issue is closed.

**What actually happened?**

Stays in the same file instead of going to the reference.

**Additional details:**

- [Private config](https://github.com/thiagokokada/dotfiles/tree/master/doom-emacs/.config/doom)

**Steps to reproduce:**
1. **Not sure if needed** Open a `.clj` file with `+lsp` enabled
2. Wait it to index the files
3. Go to a function used somewhere else and do a `g D`
4. Select any other usage of this function

**System information:**

https://pastebin.com/Bix73KGZ

**Comment by andreaskremser** [comment]
Can be reproduced with (cc +lsp), clangd and c files

**Comment by gfredtech** [comment]
Can also be reproduced with `(go +lsp)` and `(javascript +lsp)`

**Comment by razzmatazz** [comment]
(csharp +lsp) is affected too

**Comment by bram209** [comment]
same for `(rust +lsp)`

**Comment by devinalvaro** [comment]
Because `lsp-find-references` works, for a temporary fix you can alias `+lookup/references` as it by adding

```elisp
(add-hook! lsp-mode
  (defalias '+lookup/references 'lsp-find-references))
```

into `config.el`.

**Comment by razzmatazz** [comment]
> ```emacs-lisp
> (add-hook! lsp-mode
>   (defalias '+lookup/references 'lsp-find-references))
> ```

Thanks, that helped!

**Comment by jonasagx** [comment]
FYI The destination buffer is created, but the focus is not directed to it.

**Comment by yoav-za** [comment]
The specific issue is cause by the wrong handling of the point-marker by `+lookup--run-handlers` [here](https://github.com/hlissner/doom-emacs/blob/b65d8ae3acd4d5b1f822a59b0e3b678756ac29cc/modules/tools/lookup/autoload/lookup.el#L136).

**Comment by hlissner** [comment]
Does this fix the issue?

```elisp
;; add to ~/.doom.d/config.el
(defadvice! fix-lookup-handlers (ret)
  :filter-return '(+lsp-lookup-references-handler +lsp-lookup-definition-handler)
  (when ret 'deferred))
```

**Comment by ashton** [comment]
> Does this fix the issue?
> 
> ```emacs-lisp
> ;; add to ~/.doom.d/config.el
> (defadvice! fix-lookup-handlers (ret)
>   :filter-return '(+lsp-lookup-references-handler +lsp-lookup-definition-handler)
>   (when ret 'deferred))
> ```

works for me!

**Comment by andreaskremser** [comment]
Looks like that snippet fixes the issue on my system. Thanks!

**Comment by devinalvaro** [comment]
Fixed it on mine too, thanks!

**Comment by hlissner** [comment]
As of 9da4ac0 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by codercodingthecode** [comment]
Im not sure if this would be the best thread. If not, I can open another issue.

But the issue I have currently is, if I'm on the master branch. It finds all the references and live code preview. Works gd and gD.
When I change to any branch other than master. gD and gd can't find any reference to external files in the project [same that can be found in master branch], sometimes only in the own file, if there is any reference to it within.
The code snippet above doesn't work for me.
Using (vertico+icons) and Emacs 27.2
