### ISSUE TITLE
Jumping to change with Magit does not reveal point in org-mode.

### ISSUE THREAD

**Issue by Janfel** [hlissner/doom-emacs#4895]
**What did you expect to happen?**
Jumping into a folded section of an `org-mode` file using `magit-diff-visit-file` should call `org-reveal` so the user can actually see the part of the file they jumped to.

**What actually happened?**
The cursor is placed on the headline hiding the subtree that contains the target location. While `(point)` is set to the right position, the user does not see anything but the headline.

**Additional details:**
This snippet fixes the issue for me.
```elisp
(add-hook! 'org-mode-hook
  (defun *magit--call-org-reveal-h ()
    "Add `org-reveal' to `magit-diff-visit-file-hook' to reveal point."
    (add-hook 'magit-diff-visit-file-hook #'org-reveal nil 'local)))
```

**Steps to reproduce:**
1. Open an `org-mode` file under version control.
2. Change something under some headline or sub-headline.
3. Fold the document up using `TAB` or the like so your change is hidden.
4. Call `magit-status` on `SPC g g`.
5. Move the cursor onto the diff created by your change.
6. Call `magit-diff-visit-file` by pressing `RET`.
7. See the issue.

**System information:**
https://pastebin.com/YbCbyWeg

**Comment by hlissner** [comment]
As of 3e425ab this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
