### ISSUE TITLE
+lookup/definition in init.el breaks when using :if, :cond etc.

### ISSUE THREAD

**Issue by Janfel** [hlissner/doom-emacs#4896]
**What did you expect to happen?**
Calling `+lookup/definition` in `$DOOMDIR/init.el` works on all symbols in the `(doom!)` block.

**What actually happened?**
The function does not work on symbols where there is an instance of the `(:if condition module)` construct between the symbol and the corresponding module keyword. To be more exact, the helper function `+emacs-lisp--module-at-point` when called on `lang/emacs-lisp` returns `(:if emacs-lisp nil)` instead of `(:lang emacs-lisp nil)`.

**Additional details:**

**Steps to reproduce:**
1. Open `$DOOMDIR/init.el`.
2. Change the `lang/cc` line from `cc` to `(:if t cc)`.
3. Position the cursor on `emacs-lisp` on the `lang/emacs-lisp` line such that the `lang/cc` line is between the `lang/emacs-lisp` line and the `:lang` line.
4. Call `+lookup/documentation`.
5. Evaluate `(+emacs-lisp--module-at-point)`

**System information:**
https://pastebin.com/YbCbyWeg

**Comment by hlissner** [comment]
I'm aware of this, but unfortunately am swamped with more pressing issues at the moment. I'll welcome any PRs to fix the issue in the meantime.
