### ISSUE TITLE
"Wrong type argument: arrayp, 112" error on org-brain-visualize

### ISSUE THREAD

**Issue by slebedev** [hlissner/doom-emacs#4899]
**What did you expect to happen?**
org-brain works as expected by `org-brain-visualize` command

**What actually happened?**
org-brain doesn't launch, error "Wrong type argument: arrayp, 112" is shown in messages.

**Additional details:**
* It seems like the issue was introduced by [this commit](https://github.com/hlissner/doom-emacs/commit/71d4748bcffa172cf9c7ec9d45de416432e8e7f5); when I comment lines 21-41 I'm able to launch org-brain.

* Backtrace: https://pastebin.com/4kADzTWR

**Steps to reproduce:**
1. Install recent doom-emacs
2. Enable `:lang (org +brain)` feature
3. Try to launch org-brain by `M-x org-brain-visualize`

**System information:**
https://pastebin.com/EqYJ4DfL

**Comment by vigilancetech-com** [comment]
I also would like to see a solution to this.

**Comment by flyingns** [comment]
> I also would like to see a solution to this.

me too.

**Comment by hlissner** [comment]
Does this fix your issue?

```lisp
;; add to ~/.doom.d/config.el
(defadvice fixed-org--evilify-map (map)
  :override #'+org--evilify-map
  (let (keys)
    (map-keymap (lambda (event function)
                  (push function keys)
                  (push (vector event) keys))
                map)
    (apply #'evil-define-key* 'normal map keys)))
```

**Comment by slebedev** [comment]
> Does this fix your issue?
> 
> ```lisp
> ;; add to ~/.doom.d/config.el
> ;; Must be top-level!
> (defadvice fixed-org--evilify-map (map)
>   :override #'+org--evilify-map
>   (let (keys)
>     (map-keymap (lambda (event function)
>                   (push function keys)
>                   (push (vector event) keys))
>                 map)
>     (apply #'evil-define-key* 'normal map keys)))
> ```

```
Warning (initialization): An error occurred while loading ‘/Users/drago/.emacs.d/init.el’:

Error in private config: config.el, (error defadvice: Invalid advice class: map)
```

**Comment by hlissner** [comment]
Fixed the typo in my snippet above (`s/defadvice/defadvice!`). Please try again.

**Comment by slebedev** [comment]
@hlissner Henrik, thank you! This workaround also helps, with the following side effect though:

```
File mode specification error: (doom-hook-error org-mode-hook org-fancy-priorities-mode (end-of-buffer))
```

**Comment by hlissner** [comment]
As of a7d5d97, the original issue is fixed.

> @hlissner Henrik, thank you! This workaround also helps, with the following side effect though:
> 
> ```
> File mode specification error: (doom-hook-error org-mode-hook org-fancy-priorities-mode (end-of-buffer))
> ```

That's an unrelated issue. Please create a new issue for it. Please include a backtrace with the error when you do.
