### ISSUE TITLE
Scratch buffer inherits the major mode of the underlying buffer, making it non-editable in many situations

### ISSUE THREAD

**Issue by UndeadKernel** [hlissner/doom-emacs#490]
If the scratch buffer is opened while, for example, in the DOOM dashboard, the scratch buffer will inherit all the keymaps of the dashboard. This makes the scratch buffer non-editable. One has to manually switch to another mode.

I would like to start a discussion on this topic. Would it not be better to start the scratch buffer in `fundamental-mode` and let the user manually change the mode? The mode would then stick to whichever selection the user made when the scratch is closed and opened some other time.

**Comment by hlissner** [comment]
That certainly is an oversight on my part.

Though I'm not totally opposed to removing this functionality, how about if I simply made it a little smarter: don't let it inherit major modes that aren't editing modes (or whose buffers are read-only).

Despite this, users can still override the major mode in persistent scratch buffers with a local variable:

```elisp
# -*- mode: python-mode -*-
```

Or something like that, still, users can change the major mode after the fact.

Do you think that's an acceptable compromise?

**Comment by UndeadKernel** [comment]
I have the feeling that the scratch buffer's mode should be independent of
any other buffer. The purpose of this buffer is mostly to scribble things
in it, take temporary notes or quickly execute some lisp code. I have the
feeling that if the scratch buffer changes modes depending on what I'm
looking at, things will only get confusing/annoying for the user.

I'd be interested to know how others feel about it though.

**Comment by hlissner** [comment]
I've added the `doom-scratch-buffer-major-mode` variable, which is now set to `nil` by default. This means scratch buffers default to fundamental-mode. It also accepts `t` (the old behavior of inheriting the major mode of the buffer you were looking at), and any major-mode symbol.

If anything more complex is needed, I suggest keeping this set to `nil` and adding a hook to `doom-scratch-buffer-hook`.

**Comment by benlind** [comment]
I was able to change Doom's default scratch buffer mode with this line in my config.el:

```lisp
(setq-default doom-scratch-initial-major-mode 'text-mode)
```
