### ISSUE TITLE
Jsonnet formatting is messed when using the * (asterisk) character in config file

### ISSUE THREAD

**Issue by vikigenius** [hlissner/doom-emacs#4900]
**What did you expect to happen?**
Jsonnet formatting should work fine.

**What actually happened?**
Jsonnet formatting/indendation is messed up when the file contains an asterisk.

**Additional details:**

My private config contains the following

```
;;; .doom.d/packages.el
(package! jsonnet-mode)

;;; .doom.d/config.el
(use-package! jsonnet-mode
  :defer t
  :config
  (set-electric! 'jsonnet-mode :chars '(?\n ?: ?{ ?})))
```

**Steps to reproduce:**
1. Open jsonnet file.
2. Paste the following
```
local data_base_path = 'path/to/data/';
{
    "data_pattern": data_base_path + "*.tsv",
    "key1": "value1",
    "key2": "value2",
}
```
3. Indent Region now.

Everything after the line containing the asterisk (*) becomes messed up and is indented by a large number of spaces.

**System information:**
https://pastebin.com/esPEm2UL

**Comment by hlissner** [comment]
I followed the reproduction steps in vanilla Doom on Emacs 27.2 and 28, on Arch and NixOS, and the result was:

```jsonnet
local data_base_path = 'path/to/data/';
{
  "data_pattern": data_base_path + "*.tsv",
  "key1": "value1",
  "key2": "value2",
}
```

I don't see any issue, so I'll close this until I find a new lead. Feel free to follow up here in any case.

**Comment by vikigenius** [comment]
@hlissner thanks for taking a look, for a correct way to reproduce this you can use the following snippet:

```
local data_base_path = 'path/to/data/';
{
  "data_pattern": data_base_path + "train/*.tsv",
  "key1": "value1",
  "key2": "value2",
}
```


 see https://github.com/tminor/jsonnet-mode/issues/26

**Comment by vikigenius** [comment]
For future reference setting `jsonnet-use-smie` fixed the issue.

Here is the modified config

```
(use-package! jsonnet-mode
  :defer t
  :config
  (set-electric! 'jsonnet-mode :chars '(?\n ?: ?{ ?}))
  (setq jsonnet-use-smie t))
```
