### ISSUE TITLE
[misfeature] using edit alters current working directory

### ISSUE THREAD

**Issue by masukomi** [hlissner/doom-emacs#4902]
**What did you expect to happen?**

in vim using `:edit path/to/file` leaves the current working directory untouched. 
in doom it changes to, i think, the directory of the file you just opened.

What i expect to happen is to be able to say `:edit path/to/file/a` and then `:edit path/to/file/b` and have the second edit work (to open a file in the same series of subdirectories as `a`

**What actually happened?**
the current working directory changed and the second command asked if i wanted to create a new file. 

**Additional details:**

private config: my `.doom.d` dir [is available on github](https://github.com/masukomi/masuconfigs/tree/master/.doom.d)

**Steps to reproduce:**

1. open doom from the root of your project
2. use `:edit` to open a file multiple directories down
3. attempt to use `:edit` to edit a file in the root of your project WITHOUT using `../`  
4. fail
5. 😞 disappointment

**System information:**

https://pastebin.com/XDQ3jkxy

**Comment by hlissner** [comment]
This is [a fundamental difference between Emacs and Vim](https://nullprogram.com/blog/2017/08/22/), and not something I intend to change (and can't be changed trivially). You can get the same behavior in vim with `set autochdir`.

There is no bug here, so I will close this.

You could try to hack around this with something like

```elisp
(defconst my-emacs-start-directory default-directory)

(defun my-apply-func-with-start-directory (orig-fun &rest args)
  (let ((default-directory my-emacs-start-directory))
    (apply orig-fun args)))

(advice-add 'find-file-read-args :around #'my-apply-func-with-start-directory)
(advice-add 'ivy-read :around #'my-apply-func-with-start-directory)
```

But it may have side effects. Good luck!
