### ISSUE TITLE
:vsp doesn't tab-complete

### ISSUE THREAD

**Issue by sverona** [hlissner/doom-emacs#4909]
While editing a file, `:sp TAB` pulls up an autocomplete file list. So does `:vsplit TAB`.

**What did you expect to happen?**
Executing `:vsp TAB` while editing a file should exhibit the same behavior.

**What actually happened?**
Instead it fails with `user-error: Unknown command: 'vsp'`, even though the `:vsp` command is known to Doom and will work if the file name is entered manually.

Reproducing after `M-x toggle-debug-on-error` does not spawn a window or give any kind of indication that an error happened.

**Steps to reproduce:**
1. While editing a file, type `:vsp` and press `TAB`.

**System information:**
https://pastebin.com/bStZdypX

**Comment by hlissner** [comment]
This is an evil bug and should be reported [upstream](https://github.com/emacs-evil/evil).

[Here is how the ex command is defined](https://github.com/emacs-evil/evil/blob/1b3db6349d04adfc68f707b0edd800f5ab3cb374/evil-maps.el#L483).

+ `:vs <TAB>` will invoke completion
+ `:vsplit <TAB>` will invoke completion
+ Anything in between (though a valid command) does not.

As this is not a Doom issue I will close this.
