### ISSUE TITLE
Common interface for running tests etc.

### ISSUE THREAD

**Issue by jcf** [hlissner/doom-emacs#493]
Hey @hlissner, 

Not a bug, but a feature request/idea I wanted to run by you.

I've added custom bindings for running tests to my Clojure modes via Cider, and kept the bindings under `SPC m t ...`.

A lot of languages/frameworks have test infrastructure and Projectile has tried to define how to run tests but can't do things like run a test at point or for the current namespace etc.

What do you think about introducing a convention and maybe a function that can dispatch tests based on project type? Would such an abstraction be welcome or even make sense in Doom or should this be something added on a mode-by-mode basis in private modules?

**Comment by hlissner** [comment]
I would like a unified interface for unit tests, but it is a non-trivial endeavor. At the moment, there _is_ a convention that I am striving for. I'd like to bind `SPC m t` to a unit test dispatcher (in all major modes that support it) powered by Doom's `def-menu!` system.

Unfortunately, go-mode is the only mode where the convention is followed (thus far).

```elisp
  (def-menu! +go/test-menu
    "Test commands for `go-mode' buffers."
    '(("Last test"   :exec +go/test-rerun)
      ("All tests"   :exec +go/test-all)
      ("Single test" :exec +go/test-single)
      ("Nested test" :exec +go/test-nested))
    :prompt "Run test: ")

  (map! :map go-mode-map
        :localleader
        ...
        :n  "t" #'+go/test-menu
        ...)
```

`def-menu!` is used elsewhere, particularly for project building and refactoring commands, as well as help commands, here are go-mode's:

```elisp
  (def-menu! +go/refactor-menu
    "Refactoring commands for `go-mode' buffers."
    '(("Add import"            :exec go-import-add            :region nil)
      ("Remove unused imports" :exec go-remove-unused-imports :region nil)
      ("Format buffer (gofmt)" :exec go-gofmt))
    :prompt "Refactor: ")

  (def-menu! +go/build-menu
    "Build/compilation commands for `go-mode' buffers."
    '(("Build project" :exec "go build")
      ("Build & run project" :exec "go run")
      ("Clean files" :exec "go clean"))
    :prompt "Run test: ")

(def-menu! +go/help-menu
    "Help and information commands for `go-mode' buffers."
    '(("Go to imports" :exec go-goto-imports)
      ("Lookup in godoc" :exec godoc-at-point)
      ("Describe this" :exec go-guru-describe)
      ("List free variables" :exec go-guru-freevars)
      ("What does this point to" :exec go-guru-pointsto)
      ("Implements relations for package types" :exec go-guru-implements :region nil)
      ("List peers for channel" :exec go-guru-peers)
      ("List references to object" :exec go-guru-referrers)
      ("Which errors" :exec go-guru-whicerrs)
      ("What query" :exec go-guru-what)
      ("Show callers of this function" :exec go-guru-callers :region nil)
      ("Show callees of this function" :exec go-guru-callees :region nil)))
```

I think we have the foundation of a unified dispatcher, and it needs work, but this is where Doom is at the moment.

**Comment by jcf** [comment]
@hlissner thanks! I'll follow that same pattern for Cider/Clojure, and share the results once I've had time to try things out.

Also wondering about a hydra or menu for structural editing. Using evil-repeat works okay, but maybe [Lispyville](https://github.com/noctuid/lispyville) is the way to go there.

**Comment by jcf** [comment]
BTW, do you have a Gitter room or IRC where you'd prefer I bug you with stuff like this?

**Comment by UndeadKernel** [comment]
Hi @jcf, are you aware of the DOOM's [Discord channel](https://discord.gg/bcZ6P3y)?
A bunch of DOOM users (including Henrik) gather there.

**Comment by jcf** [comment]
@UndeadKernel I am now! Thanks!

**Comment by jcf** [comment]
I've tried the menu approach, and I find it a little laborious. I prefer a binding that does exactly what I want to a list of completions, but maybe that's just me.

For something where there are too many actions to sensibly bind to individual sequences I understand the use of a menu, but for five or six test bindings I like the prefixed-map approach.

Happy to close this if you are, @hlissner.

**Comment by hlissner** [comment]
I agree, it is laborious for so few options. I wouldn't mind reverting to keybinds for unit tests, since there are often so few commands. I'll think more on it.

**Comment by hlissner** [comment]
Since I last responded to this issue, I've switched back to localleader keybinds and phased out `def-menu`, so this issue is now wildly outdated. I'll consider it resolved and close it.
