### ISSUE TITLE
Disable prettier in typescript files and only use eslint?

### ISSUE THREAD

**Issue by tavurth** [hlissner/doom-emacs#4931]
I'm working with a company who doesn't want to use prettier in their `.ts` (typescript) files, how could I disable prettier and use `eslint` on save instead?

**Comment by forty** [comment]
Have you looked at this https://github.com/hlissner/doom-emacs/tree/develop/modules/editor/format#defining-your-own-formatters? It looks like this should allow to register your own formatter. However I have no idea what function you should call to call eslint.

**Comment by hlissner** [comment]
See `SPC h f set-formatter\!` (or `C-h f set-formatter\!`) for docs on how to define a formatter.

-----

In the future, please ask questions like these on our [Discord](https://doomemacs.org/discord) or, when it's up, [our Discourse](https://discourse.doomemacs.org), as our issue tracker is for bugs and feature requests, not how-to-questions.

**Comment by tavurth** [comment]
Thank you!

Sorry, saw this and assumed it was the correct place:
<img width="600" alt="Screenshot 2021-05-02 at 01 27 46" src="https://user-images.githubusercontent.com/100964/116796501-9b9e2f00-aae5-11eb-94bd-8ab22e495bf1.png">

**Comment by tavurth** [comment]
Note that I finally managed to use:

`(set-formatter! 'eslint "eslint --stdin" :modes '(typescript-mode))`

However it's very buggy and slow. 
I am now trying to figure out how to simply disable prettier for typescript files.

**Comment by tavurth** [comment]
The above was not a good solution for me I ended up using:

`(setq +format-on-save-enabled-modes '(not emacs-lisp-mode sql-mode tex-mode latex-mode typescript-mode))`

Which disables formatting in typescript.

Note that `(format-all-mode -1)` does not seem to work for Typescript buffers (Bug?)
