### ISSUE TITLE
doom cli on mac not working with error "env: sh\r: No such file or directory" 

### ISSUE THREAD

**Issue by QinBa** [hlissner/doom-emacs#4934]
Not sure if anyone has reported this already. I did a doom update on my mac and, as the title suggests,  doom cli started to fail with the following error message 
`env: sh\r: No such file or directory`

The cause is due to "windows line endings in the file" and the fix is straightforward, see
https://stackoverflow.com/questions/18172405/getting-error-usr-bin-env-sh-no-such-file-or-directory-when-running-command-p

**Comment by QinBa** [comment]
Did an update and sync with CLI with the fix. It now seems to be working. Not sure what happened. Will close the issue.

**Comment by QinBa** [comment]
The issue appeared again after I did a "doom upgrade -f". The following is the logs:
```
> Executing 'doom upgrade -f' with Emacs 27.2 at 2021-06-30 11:51:03
  > Preparing to upgrade Doom Emacs and its packages...
  - You have local modifications in Doom's source. Discarding them...
  ✓ Doom is already up-to-date!
  Doom is up-to-date!
  > Compiling your literate config...
    - Tangled 23 code blocks from config.org
    - Restarting...
env: sh\r: No such file or directory
```

It appears to me that after update, the file "bin/doom" ends up with a window line endings. I have to do "dos2unix bin/doom" in order to perform any doom command.

**Comment by John15321** [comment]
its still an issue on macOS, please fix it

**Comment by tommy-hansen** [comment]
Maybe check your git `core.autocrlf` setting.
