### ISSUE TITLE
Regarding the support for only Emacs 26.3 and up.

### ISSUE THREAD

**Issue by samarthkulshrestha** [hlissner/doom-emacs#4939]
Hey Henrik!
Great work with Doom Emacs!

I had this issue regarding the fact that only Emacs version 26.3 and above are supported. I recently switched from Arch To Debian (all the new kernels caused random system freezes), and I'm very happy with Debain, except the fact that Debain Stable offers Emacs version 26.1. That is a huge hit since Doom is an integral part of my workflow. And considering the fact that Debian is in no way an 'obscure' distro, this decision could harm Doom as a project. 

Anyways, I'm no one to tell you about such stuff, but, my problem is, that I had to install Emacs using the Nix package manager, which puts the binary in ```~/.nix-profile/bin/emacs```. Everything has worked fine until today, when I started out to install mu4e. ```emacsen-common``` which is a dependency for mu4e, requires emacs, but it couldn't find it because it was not in the root user's path. I tried adding it to the root user's path but that didn't work. In any case I shouldn't have to hack-together a solution for something this simple.

I understand that maintaining the project for older versions of Emacs could be difficult, or even impossible, but I just wanted to bring it to your mind.
Anyways, I hope you're doing well. Amazing work with the project one again, and good luck!

**Comment by gagbo** [comment]
Hello,

Aren’t you allowed to use `buster-backports` ? It has [Emacs 27](https://packages.debian.org/buster-backports/editors/emacs)

I think Henrik is trying to keep the compatibility cliff compliant with major distributions, I’d be surprised if there were no way to install a version of emacs that’s at least 26.3 on a buster machine

**Comment by samarthkulshrestha** [comment]
I can use backports, YES! Thanks! But I'm gonna check out Debian testing I think. Thank you!
