### ISSUE TITLE
doom upgrade error - void-function straight--process-buffer

### ISSUE THREAD

**Issue by danilevy1212** [hlissner/doom-emacs#4950]
When running `doom upgrade` on emacs 28.0.50 pgtk-native-comp, emacs fails with a `void-function` error.

**What did you expect to happen?**
...
For doom to upgrade packages and build them.

**What actually happened?**
...
Doom does not upgrade with the following error:
```sh
> Preparing to upgrade Doom Emacs and its packages...
✓ Doom is already up-to-date!
Doom is up-to-date!
> Compiling your literate config...
  - Tangled 143 code blocks from config.org.b9lnKD
  - Restarting...
> Preparing to upgrade Doom Emacs and its packages...
✓ Doom is already up-to-date!
Doom is up-to-date!
> Synchronizing your config with Doom Emacs...
  > Regenerating envvars file at "~/.config/emacs/.local/env"
    ✓ Successfully generated "~/.config/emacs/.local/env"
  > Installing packages...
Package cl is deprecated
    - No packages need to be installed
  > (Re)building packages...
    - No packages need rebuilding
  > Updating recipe repos...
    x There was an unexpected error
      Message: Symbol's function definition is void
      Data: (void-function . straight--process-buffer)
      Backtrace:
        (straight--process-buffer)
        (let* ((buffer (straight--process-buffer)) (start (save-current-buffer (se
        (let ((alist (let* ((buffer (stra")) (ref (straight-vc-get-commit typcurre
        (let* ((--cl-rest-- (append (list :recipe recipe) recipe)) (recipe (car (c
        (while --dolist-tail-- (setq recipe (car --dolist-tail--)) (let* ((--cl-re
        (let ((--dolist-tail-- recipes) recipe) (while --dolist-tail-- (setq recip
        (let* ((recipes (delq nil (mapcar (doom-rpartial #'gethash straight--repo-
        (let ((doom-output-indent (+ doom-output-indent-increment doom-output-inde
        (if doom--cli-updated-recipes nil (straight--make-build-cache-available) (
    ! Extended backtrace logged to .config/emacs/.local/doom.error.log
```

**Additional details:**
Doom Error Log
https://pastebin.pl/view/00e6d0a8

**Steps to reproduce:**
1. Open a terminal
2. `doom upgrade`

**System information:**

https://pastebin.com/SuWexNX1

**Comment by strider** [comment]
Same on GNU Emacs 27.2.

**Comment by gagbo** [comment]
You need to manually upgrade straight :

```
rm -r .local/straight/repos/straight.el
doom sync -up
```

There's no way around this to automate it, it just happens that sometimes breaking changes go out of sync

**Comment by danilevy1212** [comment]
That seems to have fixed it, thank you! It would be nice if that appeared in the FAQ somewhere in the package management section. It's unfortunate that it cannot be automated.

**Comment by kawaiier** [comment]
Hi!
I did `rm -r .local/straight/repos/straight.el` and it deleted lots of files and now I can't do any **doom** command as I get 

`(file-missing "Cannot open load file")
(require straight "/Users/kawaiier/.emacs.d/.local/straight/repos/straight.el/straight.el")`

**Comment by hlissner** [comment]
As of https://github.com/hlissner/doom-emacs/commit/48322af02020eba6dd88e11819d330235d09deed, issues like these shouldn't happen again. Unfortunately, it doesn't help folks upgrading _to_ this point.
