### ISSUE TITLE
How do I  eagerly load the packages in daemon

### ISSUE THREAD

**Issue by lld2001** [hlissner/doom-emacs#4959]
In Windows 7, all packages load very slow. So I use Doom in daemon. But there are some packages loading after first mouse click(or key event) that will freeze emacs nearly 10s. It's very annoying. How do I  continue load these packages right after `emacs-init-time` displayed.

**Comment by lld2001** [comment]
loading time:

Doom loaded 238 packages across 33 modules in 80.366s

**Comment by hlissner** [comment]
```lisp
(add-hook! 'after-init-hook
  (run-hooks 'doom-first-input-hook 'doom-first-buffer-hook 'doom-first-file-hook))
```

**Comment by lld2001** [comment]
It works. Thank you very much.
