### ISSUE TITLE
How do i customize some faces of a theme

### ISSUE THREAD

**Issue by shelper** [hlissner/doom-emacs#4965]
e.g., I want to change the color of the outlines, I saw, for example, in the doom-gruvbox-theme.el, it contains:
```
   ((outline-1 &override) :foreground yellow)
   ((outline-2 &override) :foreground cyan)
   ((outline-3 &override) :foreground magenta)
```
i tried to use default foreground colors instead of the specified ones above. i tried:
```
(custom-theme-set-faces
 'doom-gruvbox
 '(outline-1 :foreground fg)
 '(outline-2 :foreground fg)
 '(outline-3 :foreground fg)
 )
```
but seems it does not work...

also, i am new to elisp, and could not figure out what is the `&override` for, i saw in line 166 of `doom-themes.el` it reads:
```
...
             unless (memq action '(&inherit &extend &override))
             do (error "Invalid operation (%s) for '%s' face" action face)
...
```
other than that, i dont find where this override is defined, and something like `(outline-1 &override)` can not be evaluated as elisp s-expression: "Debugger entered--Lisp error: (void-function outline-1)"

**Comment by jeetelongname** [comment]
doom does not endorse or reccomend the custom api. you want to use `custom-set-faces!` which is a doom function. You can look at the documentation for it @ `SPC h f custom-set-faces!`

**Comment by hlissner** [comment]
Incorrect use of `custom-theme-set-faces`. Use either:

```elisp
;; the `doom-gruvbox` theme MUST be loaded before calling this
(custom-theme-set-faces
 'doom-gruvbox
 `(outline-1 ((t (:foreground ,(doom-color 'fg)))))
 `(outline-2 ((t (:foreground ,(doom-color 'fg)))))
 `(outline-3 ((t (:foreground ,(doom-color 'fg))))))
```

Or use Doom's `custom-theme-set-faces!` macro:

```elisp
;; doesn't matter if `doom-gruvbox` is loaded before or after
(custom-theme-set-faces!
 'doom-gruvbox
 `(outline-1 :foreground ,(doom-color 'fg))
 `(outline-2 :foreground ,(doom-color 'fg))
 `(outline-3 :foreground ,(doom-color 'fg)))
```

You can find documentation and more usage examples in `SPC h f custom-theme-set-faces\!` (`C-h f` if you have evil disabled).

-----

In the future, please ask questions like these on our [Discord](https://doomemacs.org/discord) or, when it's up, [our Discourse](https://discourse.doomemacs.org), as our issue tracker is for bugs and feature requests, not how-to-questions.
