### ISSUE TITLE
How do I switch to `flycheck-list-errors` buffer/window/minibuffer?

### ISSUE THREAD

**Issue by Ivanknmk** [hlissner/doom-emacs#4969]
Also posted in: https://emacs.stackexchange.com/questions/64672/how-to-switch-to-flycheck-list-errors-buffer-window-minibuffer

Posting it here in case there's something weird going on.

Here's the scenario:

I have a python/perl/js buffer and flycheck-mode activated. Flycheck does its job and tells me that there are some errors that need attention. I go and do `M-x flycheck-list-errors (or SPC c x). I have 2 spaces now: One with my code (which I believe is a window) and another something (buffer/window/minibuffer?) with the list of errors.

Question is: How do I switch to that something without using the mouse?

I've tried next-buffer, previous-buffer, C-x o, and I simply don't know how to focus on it.

Appreciate your help as It's driving me crazy! It shouldn't be that hard, right?

**Comment by hlissner** [comment]
If you are using evil, `C-w j` will select the next window to the south of the current window.

If you aren't using evil, `M-x windmove-down`, or whatever that command is bound to.

Alternatively, `M-x +popup/other` (or `M-x other-popup`) on `C-x p`

-----

In the future, please _please_ please do not ignore the issue template.

**Comment by Ivanknmk** [comment]
@hlissner I'm sorry and thank you for making an exception and invest time to answer. I really appreciate it!

Having said that, I'll be more careful next time.
