### ISSUE TITLE
Org mode issue

### ISSUE THREAD

**Issue by firebone-be** [hlissner/doom-emacs#4970]
When trying to open or create org files I get the following error after updating Doom emacs.

```
Failed to load magit package incrementally, because: (void-variable org-babel-tangle-lang-exts)
Failed to load org-src package incrementally, because: (void-variable org-babel-tangle-lang-exts)
Failed to load ob package incrementally, because: (void-variable org-babel-tangle-lang-exts)
Failed to load org package incrementally, because: (void-variable org-babel-tangle-lang-exts)
Failed to load org-agenda package incrementally, because: (void-variable org-babel-tangle-lang-exts)
Failed to load org-capture package incrementally, because: (void-variable org-babel-tangle-lang-exts)
Failed to load org package incrementally, because: (void-variable org-babel-tangle-lang-exts)
Loading /home/bone/.emacs.d/.local/cache/recentf...done
(New file)
File mode specification error: (void-variable org-babel-tangle-lang-exts)
```

Tried deleting the local/straight folder and syncing doom but to no avail.

**What actually happened?**
Org mode won't load.

**Additional details:**
[Backtrace Pastebin](https://pastebin.com/7fzSvw6N)

**Steps to reproduce:**
Create new org file or open existing org file.

**System information:**
[Doom/info pastebin](https://pastebin.com/UZukvPGg)

**Comment by ztlevi** [comment]
@hlissner  Same issue, cased by this line https://github.com/hlissner/doom-emacs/blob/develop/modules/lang/rust/config.el#L16

**Comment by crogre** [comment]
@ztlevi I can confirm, commenting out that line resolves this issue.

**Comment by linuxfranz** [comment]
can also confirm that commenting out the line that @ztlevi identified fixes the issue
