### ISSUE TITLE
non-nil `xterm-set-window-title` emits `Device 2 is not a termcap terminal device` errors with daemon + GUI frames

### ISSUE THREAD

**Issue by rburchell** [hlissner/doom-emacs#4977]
I have os/tty enabled, and upgraded doom recently to include #4819.

I run emacs in daemon mode, using `/usr/bin/emacs --fg-daemon`, and use emacsclient to open new frames as needed, both in the terminal, and UI, using a .desktop file. Terminal usage is fine, but I initially noticed that UI sessions were failing sometimes. Digging into my logs, I was seeing things like this:

`May 04 20:25:23 xxx nautilus[114491]: Waiting for Emacs...*ERROR*: Device 2 is not a termcap terminal device`
(sometimes, it's Device 1, too, I think)

I have the cause of this tracked down, now, I think. First, I found a way to reproduce it reliably:

* Kill off all running emacs processes
* Relaunch the server
* Open a terminal session (using e.g. `emacsclient -t --alternate-editor='' -c foo`)
* Notice that all subsequent attempts to open a GUI frame using the .desktop file fail

I then had a hunch that this might somehow be related to a terminal frame having been detected, but wasn't quite sure how, so I started again, but rather than opening a GUI session, I ran this, to simulate a process with no "regular" attached stdout/stdin: `emacsclient -c </dev/null |& cat`, and I got a window with an intriguing error message: `Error in post-command-hook (xterm-set-window-title): (error "Device 2 is not a termcap terminal device")`

Grepping through doom, I found the `(setq xterm-set-window-title t)` in modules/os/tty/config.el, and figured that might be the culprit. It seems to be, as adding:

```
(after! xterm
  (setq xterm-set-window-title nil))
````
  
  to my config seems to fix the problem, at the cost of no longer having terminal titles updated, naturally.

(Excuse me for not using the template, I had gathered most of this before I knew there was one, but hopefully I have included enough information. If not, I'll happily provide more.)

**Comment by hlissner** [comment]
> (Excuse me for not using the template, I had gathered most of this before I knew there was one, but hopefully I have included enough information. If not, I'll happily provide more.)

Thank you for the detailed bug report. I don't mind if folks eschew the template so long as they provide what's asked, but you forgot to include your system information. i.e. A [pastebin](https://pastebin.com) url to your `M-x doom/info`. Please include it, in case my suggestion below doesn't work for you, and please use the template in the future.

-----

Does this fix the issue for you?

```elisp
(setq xterm-set-window-title t)
(defadvice! fix-xterm-set-window-title (&optional terminal)
  :before-while #'xterm-set-window-title
  (not (display-graphic-p terminal)))
```

`xterm-set-window-title` shouldn't trigger for UI frames, but perhaps it was an oversight upstream. This advice will suppress the escape codes when not in a terminal (hopefully).

**Comment by rburchell** [comment]
Yes, that seems to fix it, thank you!

**Comment by hlissner** [comment]
As of 52fba3f the fix is now in the `:os tty` module. Thanks for bringing it to my attention!

**Comment by rburchell** [comment]
@hlissner Out of the box, this still seems to be broken as of 425f6a12641ae653a9c419be1df80b00b5e36ebd. I still have to keep the suggested hack from https://github.com/hlissner/doom-emacs/issues/4977#issuecomment-832191442 in my config.el otherwise I'm not able to launch a GUI session.

**Comment by rburchell** [comment]
I notice that your suggestion (which I am using) was `:before-while #'xterm-set-window-title` while the code in modules/os/tty/config.el is `:before-until #'xterm-set-window-title` - I'm not sure what the implication of that is...

**Comment by hlissner** [comment]
Sorry for the late response! As of 99ecc26 this issue should now be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by rburchell** [comment]
Thanks very much for the fix, and no worries about the time, the workaround meant it wasn't a huge problem! I'll try upgrade soon and report back if there's any problem, but I doubt there will be now. :-)
