### ISSUE TITLE
Formatter closes new workspace when using daemon

### ISSUE THREAD

**Issue by Dekker1** [hlissner/doom-emacs#4981]
**What did you expect to happen?**
I expect the file to be formatted and saved to the disk.

**What actually happened?**
My issue occurs when I open a file (in a mode that has a defined formatter with the emacs daemon `emacsclient -nw`), I make any changes, and then save the file.

The workspace is close and I'm asked  "Buffer [FILE] modified; kill anyway? (y or n)".

Answering `y` will remove all changes to the file.

Answering `n` will keep the changes and allow me to reopen the buffer in another workspace. I am then able to continue working on the file and everything will function as normal.

**Additional details:**
*Messages* shows the following when the file is saved:
```
Invalid face attribute :background nil
Invalid face reference: hl-line
...
Invalid face attribute :background nil
Invalid face reference: hl-line
Buffer tiny_test.py modified; kill anyway? (y or n) y
 [1] main  | Deleted '#1' workspace
Already formatted
Invalid face attribute :background nil
Invalid face reference: hl-line
...
Invalid face attribute :background nil
Invalid face reference: hl-line
QuitInvalid face attribute :background nil
Invalid face reference: hl-line
Invalid face attribute :background nil
...
Invalid face attribute :background nil
Invalid face reference: hl-line
```

These `Invalid` message seem concerning, but also occur when the problem doesn't occur.

This issue is quite annoying since I often work with formatters. Please let me know if there is any other information that I can provide

**Steps to reproduce:**
1. Install new version of Doom Emacs
2. Enable the `(format +onsave)` and `python` lines in `init.el`
3. Make sure `black` is available on the `PATH`.
4. Start emacs daemon (`emacs --debug-init --fg-daemon`)
3. Create or open Python file (`emacsclient -nw tiny_test.py`).
4. Make any change.
5. Save file (`SPC f s`)
6. Workspace will be closed and will 

Note that this is an issue with any mode with a formatter, not just Python. This issue also doesn't occur when using `emacs` directly.

**System information:**
https://pastebin.com/jfXwrAhA

**Comment by oivvio** [comment]
I'm seeing this same issue.

**Comment by oivvio** [comment]
For me this started happening after I moved to emacs 27 from emacs 25
