### ISSUE TITLE
doom upgrade aborted

### ISSUE THREAD

**Issue by smogstate** [hlissner/doom-emacs#4984]
Hi, i am trying to upgrade doom:

`./bin/doom upgrade`

This is what i get:

```
> Preparing to upgrade Doom Emacs and its packages...
✓ Doom is already up-to-date!
Doom is up-to-date!
> Synchronizing your config with Doom Emacs...
  > Regenerating envvars file at "~/.emacs.d/.local/env"
    ✓ Successfully generated "~/.emacs.d/.local/env"
  > Installing packages...
Package cl is deprecated
    - No packages need to be installed
  > (Re)building packages...
    - No packages need rebuilding
  > Updating recipe repos...
  > Updating packages (this may take a while)...
    > In repository "gcmh", failed to get status:
    
      Failed to get unambiguous name for "master"
      fatal: Needed a single revision

         1) Abort
```

Any thoughts?

PS sync is working fine.

PPS: recently i got this issue: https://github.com/hlissner/doom-emacs/issues/4950 
solved it by manually deleting the directory.

**Comment by hlissner** [comment]
1. `rm -rf ~/.emacs.d/.local/straight/repos/gcmh`
2. `doom sync`
3. Restart Emacs

**Comment by LPGhatguy** [comment]
On my upgrade, I ran into this issue on around 40 of the repositories tracked by straight.el.

For future travelers, the recommendation I got from the Discord server that worked is:

1. `rm -rf ~/.emacs.d/.local/straight`
2. `doom sync`
3. Restart Emacs

**Comment by kevin-friedheim** [comment]
@hlissner I ran into a very similar issue to this (mine was with `emacs-counsel-css`) this issue and the other more popular one (`straight--process-buffer`).

Seems like this class of issue is almost always solved w/ a forced nuke of the local repo? Maybe that can be an option in addition to abort (for doom upgrade)? Just a thought. Odds are you've already had this thought.

**Comment by hlissner** [comment]
@kevin-friedheim I'm aware. I'm working on a solution, but it's not as trivial as it sounds.
