### ISSUE TITLE
Symbol’s function definition is void: set-fontset-font

### ISSUE THREAD

**Issue by clay-f** [hlissner/doom-emacs#4992]
**What did you expect to happen?**
I'm edit a file on terminal using emacs, it is should open file on emacs

**What actually happened?**

<img width="355" alt="Screen Shot 2021-05-06 at 22 20 27" src="https://user-images.githubusercontent.com/16079417/117314366-441f0b00-aeb9-11eb-8344-a0210d18a561.png">

<img width="909" alt="Screen Shot 2021-05-06 at 22 20 56" src="https://user-images.githubusercontent.com/16079417/117314531-703a8c00-aeb9-11eb-98cf-1d51b4932d5b.png">

but it show emacs startup view, left corner show Symbol’s function definition is void: set-fontset-font.

I'm try delete .emacs.d .doom.d, and refresh install.

```
git clone --depth 1 https://github.com/hlissner/doom-emacs ~/.emacs.d
~/.emacs.d/bin/doom install
```

still get same issue.

system macOS 11.3.1 
emacs 27.2

**Comment by kpritam** [comment]
I am also facing same issue.

**Comment by hlissner** [comment]
As of a98c2ec this should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
