### ISSUE TITLE
Many `comp-*` variables were renamed to `native-comp-*` on Emacs HEAD

### ISSUE THREAD

**Issue by erik-overdahl** [hlissner/doom-emacs#4995]
This breaks [`doom--comp-use-all-cores`](https://github.com/hlissner/doom-emacs/blob/48322af02020eba6dd88e11819d330235d09deed/core/core.el#L187).

Several other native-comp related variables were renamed from `comp-*` to `native-comp-*` in the last day or so. See commits from [May 5 and 6](https://github.com/emacs-mirror/emacs/commits?author=AndreaCorallo). But only `comp-async-jobs-number` seems to have been blocking me from running `doom-sync`.

**What did you expect to happen?**
Expected `doom upgrade` and `doom sync` to work

**What actually happened?**
`(void-variable comp-async-jobs-number)`

**Additional details:**
[Here is the relevant commit](https://github.com/emacs-mirror/emacs/commit/d8f84a1c00ebf3020e201587e182cc8e4bc4a170)

**Steps to reproduce:**
1. Pull/build latest changes from emacs master
2. Try to do anything using doom

**Comment by erik-overdahl** [comment]
Looks like `comp-eln-load-path` is affected as well
https://github.com/hlissner/doom-emacs/search?q=comp-eln-load-path

**Comment by hlissner** [comment]
To quote Andrea:

> Hi all,
> 
> just to mention that as suggested in bug#48025 I've pushed a bunch of
> commits to perform the following renamings:
> 
> comp-eln-load-path → native-comp-eln-load-path
> comp-warning-on-missing-source -> native-comp-warning-on-missing-source
> comp-native-driver-options → native-comp-driver-options
> comp-async-query-on-exit → native-comp-async-query-on-exit
> comp-async-report-warnings-errors -> native-comp-async-report-warnings-errors
> comp-async-env-modifier-form → native-comp-async-env-modifier-form
> comp-async-all-done-hook → native-comp-async-all-done-hook
> comp-async-cu-done-functions → native-comp-async-cu-done-functions
> comp-async-jobs-number → native-comp-async-jobs-number
> comp-never-optimize-functions → native-comp-never-optimize-functions
> comp-bootstrap-deny-list → native-comp-bootstrap-deny-list
> comp-always-compile → native-comp-always-compile
> comp-verbose -> native-comp-verbose
> comp-debug -> native-comp-debug
> comp-speed -> native-comp-speed
> comp-limple-mode -> native-comp-limple-mode
> 
> Hopefully I'm not creating too much breakage.
> 
> Regards
> 
>   Andrea

I'm aware of this issue and will address it soon.

**Comment by hlissner** [comment]
As of 856f8b6 this should be resolved. Let me know if that isn't the case and I'll reopen the issue. Thanks for bringing it to my attention!

**Comment by goderich** [comment]
Was experiencing this bug yesterday after an update. Reinstalled Doom today after the fix, and everything works! Thank you @hlissner !

**Comment by Janfel** [comment]
The following changes have recently (2021-05-11) been added:
```
comp-deferred-compilation -> native-comp-deferred-compilation
comp-deferred-compilation-deny-list -> native-comp-deferred-compilation-deny-list
```

**Comment by hlissner** [comment]
> The following changes have recently (2021-05-11) been added:
> 
> ```
> comp-deferred-compilation -> native-comp-deferred-compilation
> comp-deferred-compilation-deny-list -> native-comp-deferred-compilation-deny-list
> ```

6adf406 adds support for these changes. Thanks for letting me know!

**Comment by Janfel** [comment]
While investigating #5038 I have also found some instances of `comp-deferred-compilation-black-list` in `core/autoload/sandbox.el`, which you must have missed when `comp-deferred-compilation-black-list` was renamed to `comp-deferred-compilation-deny-list` some time ago.
