### ISSUE TITLE
`+format-buffer-h` error when email is sent with mu4e/org-msg and `(format +onsave)` is enabled

### ISSUE THREAD

**Issue by edgar-vincent** [hlissner/doom-emacs#5001]
With the `(format +onsave)` module enabled, sending an email with `mu4e` (and `org-msg`) triggers the following error:
```
Error (before-save-hook): Error running hook +format-buffer-h because: (error Don’t know how to format org-msg-edit-mode code) Disable showing Disable logging
```
This does not occur when my private configuration contains:
```
(setq +format-on-save-enabled-modes
      '(not emacs-lisp-mode
           sql-mode
           tex-mode
           latex-mode
           rustic-mode
           org-msg-edit-mode))
```
Should this be the default value, at least temporarily?

**What did you expect to happen?**

There should be no error when sending an email with `mu4e` when `(format +onsave)` is enabled.

**What actually happened?**

The following error appears in a new window at the bottom of the frame:
```
Error (before-save-hook): Error running hook +format-buffer-h because: (error Don’t know how to format org-msg-edit-mode code) Disable showing Disable logging
```

**Additional details:**
- Backtrace: https://pastebin.com/B78g3q9V

**Steps to reproduce:**
1. Enable `mu4e` and `(format +onsave)` modules, and configure `mu4e`.
2. Open mu4e with `SPC-o-m`
3. Compose a new message with `C`
4. Add a recipient.
5. Send the message with `C-c C-c`.

**System information:**
https://pastebin.com/hjnKGcjK

Thanks a lot!

**Comment by hlissner** [comment]
As of 61376a2 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by edgar-vincent** [comment]
It seems to work perfectly! As always, thanks a lot for your responsiveness, Henrik.

**Comment by edgar-vincent** [comment]
@hlissner I just realised you might want to add `mu4e-compose-mode` to the list too. By default, `org-msg` is not enabled when replying to a plaintext email and `mu4e-compose-mode` is used instead, which triggers a `format-buffer` error when the email is sent.

Thanks a lot!

**Comment by x6rulin** [comment]
@hlissner The same error also occurs while saving changes in the scheme-mode, which perhaps should be appended to the not form `+format-on-save-enabled-modes` by default.

**Comment by ja0nz** [comment]
> @hlissner The same error also occurs while saving changes in the `scheme-mode`, which perhaps should be appended to the not form `+format-on-save-enabled-modes` by default.

`(add-to-list '+format-on-save-enabled-modes 'scheme-mode t)`

I ran into this issue with racket-mode

**Comment by rburchell** [comment]
`text-mode`, for me.

@hlissner Perhaps +format/buffer should work more like format-all-buffer--from-hook, in that it first queries for a formatter, and only tries to format if it can find one? That would also presumably mean that 57e9b89b80d1e9961be725bc08f88525681ca0b9 would not be necessary.

**Comment by hlissner** [comment]
@rburchell Calling +format/buffer _should_ throw the error, because it's called deliberately and directly. 

It's the before-save-hook hook that should gracefully bow out if no formatter is registered for the current mode, as I've done in 57e9b89. 

In any case, this should no longer need an issue. At least until I get around to rewriting this module

**Comment by rburchell** [comment]
Ah, or did you mean 857d266e7216279b40b3df66b7f537c1e30db6e0 perhaps? That looks promising!
