### ISSUE TITLE
t and s are not mapped properly in the bepo layout module

### ISSUE THREAD

**Issue by gvannoye** [hlissner/doom-emacs#5002]
**What did you expect to happen?**
When using the layout module with bepo, pressing `t` and `s` should respectively call `evil-next-visual-line` and `evil-previous-visual-line` (as `j` and `k` do when not using the layout module).

**What actually happened?**
`t` and `s` respectively call `evil-next-line` and `evil-previous-line`.

**Additional details:**
I also noticed that in `text-mode` (and all "submodes" like `org-mode` and `latex-mode`), `j` is still mapped to `evil-next-visual-line` (whereas `k` is not). Perhaps it is linked (I will open a new issue concerning this only if we discover it is not linked)

**Steps to reproduce:**
1. Add `(layout +bepo)` in the `:input` section of `init.el`
2. Quit emacs and run doom sync
3. Launch emacs
4. Press `SPC h k`
5. Press `t`
6. A buffer will open indicating that the `t` key is mapped to `evil-next-line`

**System information:**
https://pastebin.com/HVVXAGBT

**Comment by gagbo** [comment]
Hi !

I’ll try to take a look at this when I have time, just meanwhile can you paste the whole output of your `SPC h k t` manipulation ? It should list all the bindings and the maps on which `evil-next-line` is bound

**Comment by gvannoye** [comment]
Thank you. Here are the keys bound to `evil-next-line`:
```
evil-collection-evil-motion-state-map-backup-map <down>
evil-collection-evil-motion-state-map-backup-map j
evil-collection-ivy-occur-grep-mode-map-visual-state-backup-map j
evil-collection-magit-blame-read-only-mode-map-normal-state-backup-map j
evil-collection-magit-mode-map-backup-map <normal-state> t
evil-collection-magit-mode-map-backup-map <visual-state> t
evil-collection-magit-mode-map-normal-state-backup-map j
evil-collection-magit-mode-map-visual-state-backup-map j
evil-motion-state-map <down>
evil-motion-state-map t
ivy-occur-grep-mode-map <visual-state> t
magit-blame-read-only-mode-map <normal-state> t
magit-diff-mode-map <normal-state> j
magit-diff-mode-map <visual-state> j
magit-log-mode-map <normal-state> j
magit-log-mode-map <visual-state> j
magit-mode-map <normal-state> t
magit-mode-map <visual-state> t
magit-process-mode-map <normal-state> j
magit-status-mode-map <normal-state> j
magit-status-mode-map <visual-state> j
```

**Comment by gagbo** [comment]
`t` is bound to `evil-next-line` because `j` was [to begin with](https://github.com/emacs-evil/evil/blob/master/evil-maps.el#L190). It looks like maybe trying to rotate keys from [`visual-line-mode`](https://github.com/emacs-evil/evil/blob/7d00c23496c25a66f90ac7a6a354b1c7f9498162/evil-integration.el#L478-L501) would help as well but I’m really not sure

**Comment by gvannoye** [comment]
Indeed, without the bepo module `j` is bound to `evil-next-visual-line` only when `visual-line-mode` is on. I will try your fix as soon as possible
