### ISSUE TITLE
+magit/quit kills buffers still in use

### ISSUE THREAD

**Issue by lukemaurer** [hlissner/doom-emacs#5003]
**What did you expect to happen?**

With multiple Git-related windows for the same project on screen (a log view and a status view) to perform a delicate multi-step rebase operation, I hit `q` to close down the status screen, expecting it to only affect the current buffer, as is conventional for the `q` key.

**What actually happened?**

All Git views were killed.

**Additional details:**

I take it from the fact that `q` is remapped from `magit-bury-this-buffer` that this was not intentional. Regardless, destroying this much state should be something that is hard to do by accident, especially where well-established conventions are involved.

**Steps to reproduce:**
1. Split the window using `evil-window-split`.
2. Open a Magit status view using `magit-status`.
3. Switch windows using `evil-window-down`.
4. Open a Magit log view using `magit-log`.
5. Switch back using `evil-window-up`.
6. Close the status view using `+magit/quit` (notably mapped by default to `q`).

```
doom         2.0.9 grafted, HEAD -> develop, origin/develop, origin/HEAD f621ff8 2021-04-21 21:45:04 -0400 ~/.doom.d/ -> ~/.doom.d/
shell        /bin/bash
features     XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER LCMS2 GMP
traits       gui server-running envvar-file
modules      :completion company ivy :ui doom doom-dashboard doom-quit (emoji +unicode) hl-todo (ligatures +fira) minimap modeline nav-flash ophints (popup +defaults) tabs treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold snippets :emacs dired electric undo vc :checkers syntax :tools (eval +overlay) lookup magit :lang data emacs-lisp json latex markdown ocaml org python sh yaml :config (default +bindings +smartparens)
```

**Comment by hlissner** [comment]
As of 195ad0f this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
