### ISSUE TITLE
[ SOLVED ] Cannot upgrade for more than 1 week

### ISSUE THREAD

**Issue by MrMic** [hlissner/doom-emacs#5010]
### 

- [X] I have searched [the FAQ](https://doomemacs.org/docs/faq.org) and [the documentation](https://doomemacs.org/docs/getting_started.org) for solutions.
- [X] I have searched [the issue tracker](https://github.com/hlissner/doom-emacs/issues) for similar issues (the closed issues too).
- [X] I can reproduce my issue on [the latest commit](https://github.com/hlissner/doom-emacs/commit) of Doom Emacs.

### What did you expect to happen?

When I try: doom upgrade

### What actually happened?

~/.emacs.d/bin/doom upgrade
> Preparing to upgrade Doom Emacs and its packages...
- A new version of Doom Emacs is available!

  Old revision: 8bb54a95f6 (il y a 7 jours)
  New revision: 1c549f21d6 (il y a 2 heures)

Link to diff: https://github.com/hlissner/doom-emacs/compare/8bb54a95f672591571d7e092cb75570466dbc943...1c549f21d688f78a129d27d4c417f4fae2b227ce
View the comparison diff in your browser? (y or n) n
Proceed with upgrade? (y or n) y
> Upgrading Doom Emacs...
  > Cleaning .elc files
    - No elc files to clean
  - Depuis https://github.com/hlissner/doom-emacs
   * [nouvelle branche]    develop    -> _upgrade_develop
   * [nouvelle branche]    develop    -> _upgrade/develop
- Reloading Doom Emacs
> Synchronizing your config with Doom Emacs...
  > Regenerating envvars file at "~/.emacs.d/.local/env"
    ✓ Successfully generated "~/.emacs.d/.local/env"
  > Installing packages...
Package cl is deprecated
    - No packages need to be installed
  > (Re)building packages...
    - No packages need rebuilding
  > Updating recipe repos...
    x There was an unexpected error
      Message: Symbol's function definition is void
      Data: (void-function . straight--process-buffer)
      Backtrace:
        (straight--process-buffer)
        (let* ((buffer (straight--process-buffer)) (start (save-current-buffer (se
        (let ((alist (let* ((buffer (stra")) (ref (straight-vc-get-commit typcurre
        (let* ((--cl-rest-- (append (list :recipe recipe) recipe)) (recipe (car (c
        (while --dolist-tail-- (setq recipe (car --dolist-tail--)) (let* ((--cl-re
        (let ((--dolist-tail-- recipes) recipe) (while --dolist-tail-- (setq recip
        (let* ((recipes (delq nil (mapcar (doom-rpartial #'gethash straight--repo-
        (let ((doom-output-indent (+ doom-output-indent-increment doom-output-inde
        (if doom--cli-updated-recipes nil (straight--make-build-cache-available) (

### Steps to reproduce

1. doom upgrade

### System Information

https://pastebin.com/RvSP879f

**Comment by iyefrat** [comment]
See:
https://github.com/hlissner/doom-emacs/issues/4950#issuecomment-829944410

**Comment by DrWowa** [comment]
I got same error on fresh installation of doom, so, 'doom sync -up' not help, obviously.
Basically, doom not installable atm.

**Comment by MrMic** [comment]
That does not fix the bug, for me ....
Remove the .emacs.d directory end try to install from scratch, and I got:

~/.emacs.d/bin/doom install
Installing Doom Emacs!

> Creating .doom.d/
  ✓ Created .doom.d/
! init.el already exists, skipping
! config.el already exists, skipping
! packages.el already exists, skipping
- Envvar file already exists, skipping
Installing plugins
> Installing packages...
  > Updating recipe repos...
  → Cloning gcmh...pes for emacsmirror-mirror...
  x The package manager threw an error
  x Last 25 lines of straight's error log:
    $ git merge-base --is-ancestor origin/master master
    [Return code: 0]
    $ cd /home/mic/.emacs.d/.local/straight/repos/emacsmirror-mirror/
    $ git rev-parse HEAD
    1c24bceb43e0e475656be908133a8eb6df3bf973
    [Return code: 0]
    $ cd /home/mic/.emacs.d/.local/straight/repos/gcmh/
    $ git init
    Dépôt Git vide initialisé dans /home/mic/.emacs.d/.local/straight/repos/gcmh/.git/
    [Return code: 0]
    $ cd /home/mic/.emacs.d/.local/straight/repos/gcmh/
    $ git remote add origin https\://gitlab.com/koral/gcmh.git
    [Return code: 0]
    $ cd /home/mic/.emacs.d/.local/straight/repos/gcmh/
    $ git branch -r
    [Return code: 0]
    $ cd /home/mic/.emacs.d/.local/straight/repos/gcmh/
    $ git remote show origin
    fatal: unable to access 'https://gitlab.com/koral/gcmh.git/': The requested URL returned error: 503
    [Return code: 128]
    $ cd /home/mic/.emacs.d/.local/straight/repos/
    $ git clone --origin origin --no-checkout https\://gitlab.com/koral/gcmh.git /home/mic/.emacs.d/.local/straight/repos/gcmh/ --no-single-branch
    Clonage dans '/home/mic/.emacs.d/.local/straight/repos/gcmh'...
    fatal: impossible d'accder  'https://gitlab.com/koral/gcmh.git/': The requested URL returned error: 503
    [Return code: 128]

Even install from scratch does not work !!!

**Comment by iyefrat** [comment]
@MrMic this is a different error, caused by connectivity issues to gitlab. If you try again there is a good chance it'll work.

**Comment by iyefrat** [comment]
@DrWowa when running a fresh install I get the second error that @MrMic reported, that doesn't have to do with doom emacs, it's because gitlab is running upgrades so it's temporarily unavailable. Are you sure you get the error reported in the original post?

**Comment by MrMic** [comment]
Well, I have tried: doom sync -up , as explain but got an issue.
That is why I removed all and try a fresh install ...

**Comment by DrWowa** [comment]
@iyefrat yes, i got same error, but while trying resolve that i accidentally delete old doom installation. my bad :(
Await for working gitlab and see, how it goes with fresh install.

**Comment by iyefrat** [comment]
@MrMic @DrWowa gitlab maintenance is done, try now.

**Comment by DrWowa** [comment]
@iyefrat fresh install work now. Sadly, cannot reproduce initial error :(

**Comment by MrMic** [comment]
Install from scratch finally is OK.
Try basic commands:
- doom sync
- doom doctor
- doom upgrade
and all seems OK.
No more issue. :))
I close the ticket.
Thanks for the quick troubleshooting.
Rgds,

**Comment by hlissner** [comment]
Diplicate of #4950.

Please don't check ` I have searched the issue tracker for similar issues (the closed issues too)` if you haven't actually done it. Thanks.
