### ISSUE TITLE
File missing "Cannot open load file" when upgrading after removing .local/straight/repos/straight.el

### ISSUE THREAD

**Issue by kuleje** [hlissner/doom-emacs#5011]
### 

- [X] I have searched [the FAQ](https://doomemacs.org/docs/faq.org) and [the documentation](https://doomemacs.org/docs/getting_started.org) for solutions.
- [X] I have searched [the issue tracker](https://github.com/hlissner/doom-emacs/issues) for similar issues (the closed issues too).
- [X] I can reproduce my issue on [the latest commit](https://github.com/hlissner/doom-emacs/commit) of Doom Emacs.

### What did you expect to happen?

I wanted to upgrade packages using `doom upgrade` but I ran into the same problem as mentioned in #4950. I tried to solve it by running 

``` zsh
# In your .config/emacs or .emacs.d directory
rm -r .local/straight/repos/straight.el
./bin/doom sync -up
```

### What actually happened?

By mistake I ran `doom upgrade` rather than `doom sync - up`. 
First I got an error about master branch in `lsp-treemacs` to whiich my only option available was `abort`. 

### Describe your attempts to resolve the issue

I assumed I did something wrong in the previous process so I tried to do it again:

``` zsh
# In your .config/emacs or .emacs.d directory
rm -r .local/straight/repos/straight.el
./bin/doom sync -up
```
It prompted me about deleting some write-only files and I agreed to everything. 
when I did, I got a new error abour a file missing. Backtrace is available below. 

[doom.error.log](https://github.com/hlissner/doom-emacs/files/6445752/doom.error.log)

### Steps to reproduce

1. run `doom upgrade` and get an error
2. cd do to emacs directory
3. run `rm-r .local/straight/repos/straight.el`
4. run `doom upgrade` 
5. run `.local/straight/repos/straight.el`
6. run `doom sync-up` 
7. get a new error

### System Information

https://pastebin.com/dvxLnGvf

**Comment by hlissner** [comment]
You've fallen into an error state after a mistake. This is uncharted territory. Your best bet is to simply:

```sh
cd ~/.emacs.d
rm -rf .local/straight
git pull
doom sync -up
```

As this is not really a bug, or anything I can address directly (that won't be addressed by #4273) I'll close this, but feel free to follow up here.
