### ISSUE TITLE
Make Magit more compact / fancy?

### ISSUE THREAD

**Issue by bandresen** [hlissner/doom-emacs#502]
Hey,

by default the `magit log` looks like the following:
![normal view](https://i.imgur.com/9bP9lAh.png)

Using inspiration / code from other blogs I've modified it to look like this:
![compact view](https://i.imgur.com/CQSYwyw.png)

Is this something you want to include in the `vcs` module? As this has the best effect when the project you're viewing is adhering to a specific standard for commit messages then this yields the IMO best effect:

Normal:
![normal](https://i.imgur.com/VSlXEgC.png)
Fancy:
![full log example](https://i.imgur.com/kzxF8bB.png)

Discussion welcome. I've noticed some new magit behavior with the branch color, so this is not yet fully ready it seems. But I think it's quite nice, especially if `origin` doesn't automatically translate to `github`.

P.S. I also have some code that forces me to adhere to the commit style. Also not yet production ready.

**Comment by bandresen** [comment]
RE: P.S.
I had to redo the way it works. It seems to be an unsupported interaction between the various modes.

But this is how it looks like:
[![gfycat](https://thumbs.gfycat.com/LawfulIdenticalDouglasfirbarkbeetle-size_restricted.gif)](https://gfycat.com/LawfulIdenticalDouglasfirbarkbeetle)
(click for playback controls)

**Comment by teesloane** [comment]
that fancy screenshot looks lovely. Nice work! Can you link some details on what git commit style's you're following to achieve this?

**Comment by bandresen** [comment]
It was all inspired by this blog post: http://www.modernemacs.com/post/pretty-magit/
Initially I also took the code from there but I changed it around a bit to for example allow the remotes to identify if they are gitlab, github, bitbucket or other.

Also see the [HN discussion linked at the bottom](https://news.ycombinator.com/item?id=13889155) for a discussion.
And [AngularJS's git commit message conventions](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commits).

**Comment by UndeadKernel** [comment]
I imagine this could be a module option for magit. With a statement like
```lisp
(doom! :tools (magit +fancy))
```
we could get an optional fancy interface.

**Comment by hliebert** [comment]
I might be in the minority on this, but I personally find this look quite distracting and would not consider this an improvement. Making it optional is perfectly fine, I don't think it makes a great default imho.
