### ISSUE TITLE
Improve Zig Flavor Text

### ISSUE THREAD

**Issue by Cons-Cat** [hlissner/doom-emacs#5022]
**Describe the feature**
Currently, the Zig module is labelled like so:
```zig               ; C, but simpler```
This is, in my humble opinion, **critically lame** compared to many other modules in `init.el`.

It is a pet peeve of mine to see a language described as "simpler" than another, because that doesn't mean anything. There are many different kinds of "simple". Is it simpler in one lang to write FizzBuzz, or is it simpler for writing a multi-threaded regex parser that traverses several thousand files per second? These are often mutually exclusive "simpler"s.

In a lot of ways, Zig is more complex than C. It has more keywords than C, it makes a programmer think more actively about compile-time vs runtime behavior (that's simpler for some programs, but more complex for others), it has more data types, it has standard coroutines, it generally inhibits simply `malloc`ing data, it has optionals rather than null semantics (simpler in some ways, more complex in others), it has pattern matching, it makes mutability more explicit, etc.

Moreover, Zig has several unique characteristics to identify it with. It's the most popular language to provide such explicit delineation of comptime vs runtime behavior, except _arguably_ C++20. It is technically a wrapper around Clang, which you don't see every day. Its marketing has cute lizards everywhere ([this one](https://dev.to/stein/bio-all-your-parentheses-are-belong-to-us-25lo) is my favorite). And it sort of already has a tagline, which it generates in lieu of 'hello world' for initializing projects: `All your code are belong to us`

There's gotta be _something_ in there. Not that I have any ideas.

**System information**
```
C:\Users\wgooc>doom info
←[31mx There was an unexpected error←[0m
  ←[1mMessage:←[0m File is missing
  ←[1mData:←[0m (file-missing . "Searching for program")
  ←[1mBacktrace:←[0m
    (call-process "uname" nil t nil "-msr")
    (apply call-process "uname" nil t nil "-msr")
    (or (apply #'call-process command nil t nil (remq nil args)) -1)
    (cons (or (apply #'call-process command nil t nil (remq nil args)) -1) (st
    (progn (cons (or (apply #'call-process command nil t nil (remq nil args))
    (unwind-protect (progn (cons (or (apply #'call-process command nil t nil (
    (save-current-buffer (set-buffer temp-buffer) (unwind-protect (progn (cons
    (let ((temp-buffer (generate-new-buffer " temp"))) (save-current-buffer
    (doom-call-process "uname" "-msr")
    (apply doom-call-process ("uname" "-msr"))
←[33m! Extended backtrace logged to .local/doom.error.log←[0m
```

**Comment by hlissner** [comment]
I don't use zig (yet), and I didn't write the module so a better one-liner will have to come from you or someone more qualified. PRs welcome!

**Comment by bnjmnt4n** [comment]
I guess that's my fault that I couldn't think of a good tagline which is as snarky as the rest when adding the module. I really like the `all your codebase are belong to us` tagline though. Feel free to provide suggestions.
