### ISSUE TITLE
Beancount file error (file specification error, lsp not detected)

### ISSUE THREAD

**Issue by wangkev** [hlissner/doom-emacs#5035]
### 

- [X] I have searched [the FAQ](https://doomemacs.org/docs/faq.org) and [the documentation](https://doomemacs.org/docs/getting_started.org) for solutions.
- [X] I have searched [the issue tracker](https://github.com/hlissner/doom-emacs/issues) for similar issues (the closed issues too).
- [X] I can reproduce my issue on [the latest commit](https://github.com/hlissner/doom-emacs/commit) of Doom Emacs.
- [X] I have searched [the Discourse](https://discourse.doomemacs.org/docs) for solutions.
- [X] I have read [How to Debug Issues](https://discourse.doomemacs.org/how2debug) and found no solution.

### What did you expect to happen?

When opening a beancount file, expect beancount-mode to work properly and lsp to be detected (beancount-langserver is installed).

### What actually happened?

When opening a beancount file, hit an error and lsp is not detected

```
File mode specification error: (error Autoloading file /Users/wangkev/.config/emacs/.local/straight/build-27.2/beancount/beancount.elc failed to define function beancount)
```

### Describe your attempts to resolve the issue

Tried the following:
- manually enable beancount-mode afterwards, this works
- uninstall and reinstall beancount and lsp modules (comment out/in, and doom build)

### Steps to reproduce

1. Open emacs
2. Enable beancount and lsp (:lang (beancount +lsp) :tools lsp)
3. Apply changes (doom sync, M-x doom/reload)
4. Open beancount file
5. Hit error

### System Information

https://pastebin.com/nN7i3KE5

**Comment by hlissner** [comment]
I cannot reproduce any errors with your test case.

+ You're also reporting two different errors: a `beancount.elc failed to define function beancount` in your report and ` lsp not detected` in the issue title. Which is it?
+ Please provide backtraces for all error messages, as requested in the issue form.
+ Can you reproduce the issue with everything else in your config disabled?

**Comment by wangkev** [comment]
Thanks, that did the trick! Appears that the `lsp` issue was unrelated/still persists. I'll dig deeper into it and open another ticket if necessary.
