### ISSUE TITLE
omnisharp-emacs is no longer being developed, remove?

### ISSUE THREAD

**Issue by Ruin0x11** [hlissner/doom-emacs#5036]
### Describe your request

The `omnisharp` package has been deprecated in favor of `lsp-mode` and is no longer being maintained.

https://github.com/OmniSharp/omnisharp-emacs/blob/master/README.md#depreciation-notice

Should the `omnisharp` integration for `:lang csharp` be dropped entirely?

### Briefly explain its use-case

Currently`omnisharp` is non-functional with the latest Emacs 28, and throws errors on starting the server. It doesn't make sense to have it around if nobody is going to fix it in the future. It's also confusing because if it's still integrated with `doom-emacs` then people (like me) might mistakenly believe that it's still being maintained.

**Comment by hlissner** [comment]
As of ad7c087 omnisharp-emacs has been removed, which should resolve this request. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
