### ISSUE TITLE
Launching `vanilla Doom (only Doom Core)` sandbox hits error

### ISSUE THREAD

**Issue by wangkev** [hlissner/doom-emacs#5042]
### 

- [X] I have searched [the FAQ](https://doomemacs.org/docs/faq.org) and [the documentation](https://doomemacs.org/docs/getting_started.org) for solutions.
- [X] I have searched [the issue tracker](https://github.com/hlissner/doom-emacs/issues) for similar issues (the closed issues too).
- [X] I have searched [the Discourse](https://discourse.doomemacs.org/docs) for any errors and solutions.
- [X] I can reproduce my issue on [the latest commit](https://github.com/hlissner/doom-emacs/commit) of Doom Emacs.
- [X] I have read [How to Debug Issues](https://discourse.doomemacs.org/how2debug) and found no solution.

### What did you expect to happen?

When launching an empty sandbox with `vanilla Doom (only Doom core)`, should launch a sandbox emacs with vanilla doom.

### What actually happened?

Hit an error when launching the sandbox:

```
setq: Symbol’s function definition is void: doom-system-cpus
```

(not sure if there is a way to get backtrace for this?)

### Describe your attempts to resolve the issue

Saw https://github.com/hlissner/doom-emacs/issues/4715, thought it might have been related. Updated to latest commit as of writing (https://github.com/hlissner/doom-emacs/commit/ce11a98b70027462f207aadc59d26ca95ca03325), and `doom clean` and `doom sync`-ed, but but issue persists.

### Steps to reproduce

1. Open emacs
2. Open sandbox (`SPC h E`)
3. Try to open `vanilla Doom (only Doom core)` (`C-c C-d`)

### System Information

https://pastebin.com/XcqNAwJH

**Comment by hlissner** [comment]
As of 6d2c6b4 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by wangkev** [comment]
Can confirm the fix resolved the issue, thanks!
