### ISSUE TITLE
doom upgrade fails on nav-flash

### ISSUE THREAD

**Issue by gregghz** [hlissner/doom-emacs#5043]
### 

- [X] I have searched [the FAQ](https://doomemacs.org/docs/faq.org) and [the documentation](https://doomemacs.org/docs/getting_started.org) for solutions.
- [X] I have searched [the issue tracker](https://github.com/hlissner/doom-emacs/issues) for similar issues (the closed issues too).
- [X] I have searched [the Discourse](https://discourse.doomemacs.org/docs) for any errors and solutions.
- [X] I can reproduce my issue on [the latest commit](https://github.com/hlissner/doom-emacs/commit) of Doom Emacs.
- [X] I have read [How to Debug Issues](https://discourse.doomemacs.org/how2debug) and found no solution.

### What did you expect to happen?

I expected doom upgrade to just work.

### What actually happened?

doom upgrade fails with:

```
  > Updating packages (this may take a while)...
    > In repository "nav-flash", failed to get status:

      Failed to get unambiguous name for "master"
      fatal: Needed a single revision

         1) Abort

      How to proceed? (1)
```

### Describe your attempts to resolve the issue

I tried deleting .local/straight/build-28.0.50/nav-flash but it had no effect.

### Steps to reproduce

1. From bin/ run `./doom upgrade`
2. See nav-flash fail to get updated.

### System Information

https://pastebin.com/L9Zq6TuT

**Comment by hlissner** [comment]
I am aware of this issue, and am working on a fix for this in #4273. For the time being, you'll have to delete packages manually to fix this issue. e.g.

```sh
rm -rf ~/.emacs.d/.local/straight/repos/nav-flash
doom upgrade
```

Sorry for the trouble!
