### ISSUE TITLE
+workspace/display broken after saving file in project

### ISSUE THREAD

**Issue by pgrond** [hlissner/doom-emacs#5050]
### 

- [X] I have searched [the FAQ](https://doomemacs.org/docs/faq.org) and [the documentation](https://doomemacs.org/docs/getting_started.org) for solutions.
- [X] I have searched [the issue tracker](https://github.com/hlissner/doom-emacs/issues) for similar issues (the closed issues too).
- [X] I have searched [the Discourse](https://discourse.doomemacs.org/docs) for any errors and solutions.
- [X] I can reproduce my issue on [the latest commit](https://github.com/hlissner/doom-emacs/commit) of Doom Emacs.
- [X] I have read [How to Debug Issues](https://discourse.doomemacs.org/how2debug) and found no solution.

### What did you expect to happen?

Pressing `SPC Tab Tab` shows the active projects.

### What actually happened?

Nothing happens.

### Describe your attempts to resolve the issue

Enabled `toggle-debug-on-error` but there are no messages or errors.

### Steps to reproduce

1. Open Emacs
2. Open a project
3. Make a change to a file and save
4. Press `SPC Tab Tab`

### System Information

https://pastebin.com/raw/d3G81syc

**Comment by hlissner** [comment]
This seems like a misunderstanding of what `+workspace/display` is supposed to display. It doesn't display "active projects", it displays open workspaces (or in persp-mode parlance: perspectives). With the steps you provided, you should only have one workspace open: the main one, which Doom starts up with. Whether or not you save a buffer does not change this.

In any case, following your steps, I see the expected result:

![image](https://user-images.githubusercontent.com/510883/118200798-fad43b80-b423-11eb-9893-32592c4d0593.png)

The lone workspace is listed in the minibuffer.

Can you expand on "nothing happens"? What exactly you were expecting to see?

**Comment by pgrond** [comment]
Thanks for the quick response and sorry for the confusion. I do mean the open workspaces. Is hould have said create a new workspace (by opening a project for example).

You are correct that initially the workspaces show:
![1620976660](https://user-images.githubusercontent.com/1938132/118236100-f3e61100-b495-11eb-8564-803bb1c728a3.png)

Opening a project, the title changes to the name of the project:
![1620976694](https://user-images.githubusercontent.com/1938132/118236153-05c7b400-b496-11eb-92c2-8ffc10755907.png)

Saving a file in the project, triggering the `+workspace/display` does nothing:
![1620976721](https://user-images.githubusercontent.com/1938132/118236248-21cb5580-b496-11eb-8e48-83c6b0059ce5.png)

The *Messages* buffer has no warnings or errors.

**Comment by pgrond** [comment]
Hmm, trying to bisect what is going on,still didn't find what it is, but it seems to be in a package outside of doom.
