### ISSUE TITLE
Composed `?.` ligature in the middle of typescript-tsx-mode code

### ISSUE THREAD

**Issue by shackra** [hlissner/doom-emacs#5053]
### 

- [X] I have searched [the FAQ](https://doomemacs.org/docs/faq.org) and [the documentation](https://doomemacs.org/docs/getting_started.org) for solutions.
- [X] I have searched [the issue tracker](https://github.com/hlissner/doom-emacs/issues) for similar issues (the closed issues too).
- [X] I have searched [the Discourse](https://discourse.doomemacs.org/docs) for any errors and solutions.
- [X] I can reproduce my issue on [the latest commit](https://github.com/hlissner/doom-emacs/commit) of Doom Emacs.
- [X] I have read [How to Debug Issues](https://discourse.doomemacs.org/how2debug) and found no solution.

### What did you expect to happen?

I did not expect any ligature, or, in this case, that the ligature didn't screw readability

### What actually happened?

in typescript-tsx-mode you can see the follow if you write `?.`

![image](https://user-images.githubusercontent.com/1055216/118347845-6214ed00-b503-11eb-83ba-d4e69dc7cf11.png)

### Describe your attempts to resolve the issue

I haven't touch my configuration for these ligatures, so I don't really know how to solve it

### Steps to reproduce

1. open Emacs
2. open a `.tsx` file
3. write `data?.`
4. voila

### System Information

https://pastebin.com/SVA4K7AE

**Comment by hlissner** [comment]
Try modifying [this line](https://github.com/hlissner/doom-emacs/blob/develop/modules/ui/ligatures/config.el#L191) in `~/.emacs.d/modules/ui/ligatures/config.el`:

```diff
       (dolist (char-regexp +ligatures-composition-alist)
         (set-char-table-range
          +ligature--composition-table
-         (car char-regexp) `([,(cdr char-regexp) 0 font-shape-gstring])))
+         (car char-regexp) `([,(concat "." (cdr char-regexp)) 0 font-shape-gstring])))
       (set-char-table-parent +ligature--composition-table composition-function-table))))
```

And see if it fixes your issue.

**Comment by shackra** [comment]
yes, it does fix the issue

**Comment by hlissner** [comment]
As of 5406745 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
