### ISSUE TITLE
Roll back previous treemacs navigation key bindings h/l 

### ISSUE THREAD

**Issue by Arahnoid** [hlissner/doom-emacs#5056]
### 

- [X] I have read the [contributing guide](https://discourse.doomemacs.org/how2contribute).
- [X] I have searched [the issue tracker](https://github.com/hlissner/doom-emacs/issues?q=label%3A%221.+request%22+) for similar requests.
- [X] I have searched [the module list](https://doomemacs.org/docs/modules.org) in case my feature was already implemented.
- [X] I have confirmed that updating Doom won't fulfill my request.

### Describe your request

The treemacs commit [01c27dc3dbe65e5b4a93cbe2a8fbfa65ab511a54](https://github.com/Alexander-Miller/treemacs/commit/01c27dc3dbe65e5b4a93cbe2a8fbfa65ab511a54#diff-7835adffcdc554933e5309b4918da9f10bb4d18501e70f97be647119f6faac75) updated previous key bindings <kbd>h</kbd>`treemacs-root-up` and <kbd>l</kbd> `treemacs-root-down` to a more complex  and inconvenient key chord.  Now the same can be achieved with <kbd>Alt</kbd><kbd>Shift</kbd><kbd>h</kbd> and <kbd>Alt</kbd><kbd>Shift</kbd><kbd>l</kbd> accordingly which is not convinient.

Would it be possible to restore previous behavior?

### Briefly explain its use-case

Issue caused upstream.

**Comment by hlissner** [comment]
As of 5c46a5e I've restored these two keys. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by Arahnoid** [comment]
Unfortunately the key bindings still have same behaviour. I did `doom up` and tried `doom sync` after and `doom sync -up` just in case.
- If the cursor is on the root folder I get an message`[Treemacs] There is no parent to move up to.`
- If I'm on sub folder inside project the folders collapses/expands

**Comment by hlissner** [comment]
On second review, I've realized the new keybinds are perfectly sensible, and the old commands error out when you have multiple projects in a treemacs workspace, so I will leave it to users to customize. Throwing this into `~/.doom.d/config.el` should fix your issue:

```elisp
(after! treemacs-evil
  (evil-define-key 'treemacs treemacs-mode-map
    "h" #'treemacs-root-up
    "l" #'treemacs-root-down))
```

**Comment by Arahnoid** [comment]
Thank you this will work for me 👍
