### ISSUE TITLE
I get incorrect results opening zip archives

### ISSUE THREAD

**Issue by jgm** [hlissner/doom-emacs#5057]
### 

- [X] I have searched [the FAQ](https://doomemacs.org/docs/faq.org) and [the documentation](https://doomemacs.org/docs/getting_started.org) for solutions.
- [X] I have searched [the issue tracker](https://github.com/hlissner/doom-emacs/issues) for similar issues (the closed issues too).
- [X] I have searched [the Discourse](https://discourse.doomemacs.org/docs) for any errors and solutions.
- [X] I can reproduce my issue on [the latest commit](https://github.com/hlissner/doom-emacs/commit) of Doom Emacs.
- [X] I have read [How to Debug Issues](https://discourse.doomemacs.org/how2debug) and found no solution.

### What did you expect to happen?

When I open a zip file (or docx, which is also a zip archive), I expect its contents to be displayed.  This works perfectly with `emacs -q` (no config), and it worked until recently with Doom.

### What actually happened?

Now when I open a docx, I see
```
M Filemode      Length  Date         Time      File
- ----------  --------  -----------  --------  --------
- ----------  --------  -----------  --------  --------
                     0                         0 files
```
(Same thing happens if I rename it with a zip extension.)
In this case `unzip -l r.docx` shows
```
Archive:  r.docx
  Length      Date    Time    Name
---------  ---------- -----   ----
     1830  05-15-2021 18:18   [Content_Types].xml
      724  05-15-2021 18:18   _rels/.rels
      724  05-15-2021 18:18   docProps/app.xml
      595  05-15-2021 18:18   docProps/core.xml
      242  05-15-2021 18:18   docProps/custom.xml
     8125  05-15-2021 18:18   word/document.xml
     2494  05-15-2021 18:18   word/fontTable.xml
     1135  05-15-2021 18:18   word/footnotes.xml
      626  05-15-2021 18:18   word/comments.xml
     2157  05-15-2021 18:18   word/numbering.xml
     1785  05-15-2021 18:18   word/settings.xml
      199  05-15-2021 18:18   word/webSettings.xml
    14555  05-15-2021 18:18   word/styles.xml
     1367  05-15-2021 18:18   word/_rels/document.xml.rels
      301  05-15-2021 18:18   word/_rels/footnotes.xml.rels
     7674  05-15-2021 18:18   word/theme/theme1.xml
---------                     -------
    44533                     16 files
```

### Describe your attempts to resolve the issue

I've tried reinstalling both Doom and emacs (27.2).  I've also tried with an empty config.el.  Same problem.   And I've tried reverting my config to the way it was in November, when I know this worked. Same problem. That all points to some recentish change in Doom, perhaps.

Yet with `emacs -q` it works fine, so this does seem related somehow to my config.  Messages buffer doesn't reveal anything.

I'm on macOS Catalina, by the way.  But, no major updates in my OS or userspace since the time when this worked.

### Steps to reproduce

```
$ touch a.txt
$ touch b.txt
$ zip -r my.zip a.txt b.txt
$ emacs my.zip
```
This shows me an empty archive. But:
```
$ unzip -qq -l my.zip
       12  05-15-2021 13:21   a.txt
        7  05-15-2021 13:21   b.txt
```

### System Information
https://pastebin.com/ajgWQH5t

**Comment by hlissner** [comment]
I cannot reproduce this in vanilla Doom on Emacs 27.1, 27.2 or 28.0.50 on NixOS, Arch Linux or MacOS, out of the box, following your exact steps. 

Docx files open as expected:

![image](https://user-images.githubusercontent.com/510883/118377482-79071e00-b59b-11eb-9a6b-dbb6c26dc3d5.png)

As do zip files:

![image](https://user-images.githubusercontent.com/510883/118377491-802e2c00-b59b-11eb-9637-0904fb8c2764.png)

**Comment by jgm** [comment]
Okay, thanks for checking, and feel free to close this.  I will try to track it down.  If you have any ideas for where the problem might lie, let me know.

**Comment by jgm** [comment]
By bisecting my init.el, I found the culprit: enabling "editorconfig" breaks this, and disabling fixes it again.

**Comment by jgm** [comment]
It's completely bizarre; I have no idea why editorconfig should affect this.  But I don't need editorconfig, so this is an adequate solution for me.

**Comment by hlissner** [comment]
Odd. Enabling the editorconfig module did not change the behavior for me. What does your root `~/.editorconfig` look like? Are there any errors/warnings in \*Messages\* after you open a docx/zip file? (`C-h e` to open the \*Messages\* buffer)

**Comment by jgm** [comment]
The .editorconfig in the directory containing the docx I'm trying to open is
```
root = true

[*]
charset = utf-8
end_of_line = lf
indent_style = space
indent_size = 2
insert_final_newline = true
trim_trailing_whitespace = true

[*.{markdown,md}]
trim_trailing_whitespace = false

[test/*]
insert_final_newline = false
trim_trailing_whitespace = false
```

Messages just says
```
Parsing archive file...done.
Parsing archive file...done.
Starting a new list of tags tables
```

Note that when I copy to the docx to `~/tmp`, which does not have an `.editorconfig`, it works fine.

Aha!  Deleting the line `charset = utf-8` fixes the issue.
I don't actually know much about editorconfig, but apparently it's a mistake to use this line if you plan to open binary files in your editor!

**Comment by jgm** [comment]
Adding this to my `.editorconfig` seemed to fix things:
```
[*.{zip,docx}]
charset =
end_of_line =
indent_style =
indent_size =
insert_final_newline =
trim_trailing_whitespace =
```

**Comment by hlissner** [comment]
Does this fix the issue?

```elisp
(after! editorconfig
  (add-to-list 'editorconfig-exclude-modes 'archive-mode))
```

**Comment by jgm** [comment]
No, that doesn't seem to help.

**Comment by hlissner** [comment]
How about:

```elisp
(add-to-list 'editorconfig-exclude-regexps "\\.\\(zip\\|docx\\)\\'")
```

Sorry for the trouble, even with `charset = utf-8` I can't reproduce this.

**Comment by jgm** [comment]
That works!

**Comment by hlissner** [comment]
Alright, I've added these zip/docx/pptx/xlsx extensions to `editorconfig-exclude-regexps` in 5bed0a6, so I'll consider this resolved. Thanks for bringing it to my attention!

**Comment by jgm** [comment]
Thanks very much for the fix!  I'm already using it and it works well.
