### ISSUE TITLE
[BUMP] rainbow-delimiters

### ISSUE THREAD

**Issue by bladrome** [hlissner/doom-emacs#5059]
### 

- [X] There are no other bump requests for this package [on the issue tracker](https://github.com/hlissner/doom-emacs/pulls?q=is%3Apr+is%3Aopen+label%3A%221.+update%29%22+).
- [X] The package(s) I want bumped are not in [the do-not-PR list](https://discourse.doomemacs.org/do-not-pr) list.
- [X] These packages still need to be bumped on the [latest commit of Doom](https://github.com/hlissner/doom-emacs/commit).
- [X] I've tested the new versions of these packages myself and can report on its issues (if any).

### What package(s) should be bumped?

rainbow-delimiters

### Why should Doom bump these packages early?

Clean install doom: 
x There was an unexpected error
  Message: Symbol's value as variable is void
  Data: (void-variable . rainbow-delimiters:)
  Backtrace:
    (load-with-code-conversion "/home/bladrome/.config/emacs/.local/straight/b
    (load "/home/bladrome/.config/emacs/.local/straight/build-28.0.50/rainbow-
    (progn (load autoloads-file nil 'nomessage))
    (if (file-exists-p autoloads-file) (progn (load autoloads-file nil 'nomess
    (let ((autoloads-file (straight--autoloads-file package))) (if (file-exist
    (straight--load-package-autoloads "rainbow-delimiters")
    (let ((name (symbol-name package))) (add-to-list 'load-path (directory-fil
    (let ((package (car --dolist-tail--))) (straight-register-package package)
    (while --dolist-tail-- (let ((package (car --dolist-tail--))) (straight-re
    (let ((--dolist-tail-- (cl-delete-duplicates packages :test #'equal))) (wh
! Extended backtrace logged to .config/emacs/.local/doom.error.log

[This commit](https://github.com/Fanael/rainbow-delimiters/commit/7919681b0d883502155d5b26e791fec15da6aeca) Fix this.

**Comment by hlissner** [comment]
I've bumped rainbow-delimiters in 62c231e, so this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
