### ISSUE TITLE
Reenabling make-backup-files with no backup dirs defined prevent emacs from saving

### ISSUE THREAD

**Issue by xrogaan** [hlissner/doom-emacs#5060]
### 

- [X] I have searched [the FAQ](https://doomemacs.org/docs/faq.org) and [the documentation](https://doomemacs.org/docs/getting_started.org) for solutions.
- [X] I have searched [the issue tracker](https://github.com/hlissner/doom-emacs/issues) for similar issues (the closed issues too).
- [X] I have searched [the Discourse](https://discourse.doomemacs.org/docs) for any errors and solutions.
- [X] I can reproduce my issue on [the latest commit](https://github.com/hlissner/doom-emacs/commit) of Doom Emacs.
- [X] I have read [How to Debug Issues](https://discourse.doomemacs.org/how2debug) and found no solution.

### What did you expect to happen?

By default Emacs saves backup files under the original name with a tilde `~` appended. Doom override that behavior. My intent is to restore the defaults.

### What actually happened?

emacs complains: `find-backup-file-name: Wrong type argument: stringp, nil`, and the file isn't saved.

A backtrace:
```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  file-name-all-completions("59b53184df42ce48598f0e8d361f010a250d3aa5.~" nil)
  find-backup-file-name("/home/bellu/.doom.d/config.el")
  backup-buffer()
  basic-save-buffer-2()
  basic-save-buffer-1()
  basic-save-buffer(t)
  save-buffer(1)
  #<subr funcall-interactively>(save-buffer 1)
  apply(#<subr funcall-interactively> (save-buffer 1))
  funcall-interactively(save-buffer 1)
  #<subr call-interactively>(save-buffer nil nil)
  apply(#<subr call-interactively> (save-buffer nil nil))
  explain-pause--wrap-call-interactively(#<subr call-interactively> save-buffer nil nil)
  apply(explain-pause--wrap-call-interactively #<subr call-interactively> (save-buffer nil nil))
  call-interactively(save-buffer nil nil)
  command-execute(save-buffer)
```

### Describe your attempts to resolve the issue

Defining `backup-directory-alist` to `'(("." . "."))` partially solves the issue. A backup file is created, but not under the name of the original file.

Vanilla emacs (running `emacs -Q` do not have this problem.)

### Steps to reproduce

Use the following snippet in your doom.d/config.el:
```elisp
(setq create-lockfiles t
      make-backup-files t
      backup-directory-alist nil  ; Problematic line
      backup-by-copying t         ; don't clobber symlinks
      kept-new-versions 1         ; keep n latest versions
      kept-old-versions 0         ; don't bother with old versions
      delete-old-versions t       ; don't ask about deleting old versions
      version-control nil     ; number backups
      vc-make-backup-files t)     ; backup version controlled files
```

1. Open an existing file with emacs
2. Write some change
3. try to save

### System Information

https://gist.github.com/xrogaan/e2bf5553d93b589372058400347747e1

**Comment by hlissner** [comment]
As of 69beabe this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
