### ISSUE TITLE
Ibuffer should open buffers in their respective workspaces

### ISSUE THREAD

**Issue by isentropic** [hlissner/doom-emacs#5061]
### Describe your request

Currently ibuffer (analogue to dired for buffers) is a great way of overviewing all buffers. Buffers are grouped by workspaces which is great. Though, when opening a buffer that belongs to a different workspace, the current workspace does not auto switch to that workspace. I could not find a way to implement this myself, but I assume that it should not be difficult.

### Briefly explain its use-case

1. Open ibuffer
2. switch to a buffer
3. expect the workspace to be switched too

**Comment by isentropic** [comment]
Ibuffer content:

Workspace A [current workspace]
buffer 1  [currently here]
buffer 2
Workspace B
buffer 3  [buffer I want to switch to]
buffer 4

*clicks buffer 3*


Workspace A [current workspace]
buffer 1  
buffer 2
Workspace B [I wish the current workspace was this now]
buffer 3  [currently here]
buffer 4

**Comment by petr-tik** [comment]
hey, i want this feature as well, can you please assign it to me and I will try working on it?

**Comment by hlissner** [comment]
This issue should now be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
