### ISSUE TITLE
Flycheck Symbol is out of view in doom modeline when running Emacs Client and frame is maximized

### ISSUE THREAD

**Issue by shans10** [hlissner/doom-emacs#5067]
### 

- [X] I have searched [the FAQ](https://doomemacs.org/docs/faq.org) and [the documentation](https://doomemacs.org/docs/getting_started.org) for solutions.
- [X] I have searched [the issue tracker](https://github.com/hlissner/doom-emacs/issues) for similar issues (the closed issues too).
- [X] I have searched [the Discourse](https://discourse.doomemacs.org/docs) for any errors and solutions.
- [X] I can reproduce my issue on [the latest commit](https://github.com/hlissner/doom-emacs/commit) of Doom Emacs.
- [X] I have read [How to Debug Issues](https://discourse.doomemacs.org/how2debug) and found no solution.

### What did you expect to happen?

When I run doom emacs normally everything works fine and doom modeline is rendered correctly. I expected the same when running emacs client.

![Screenshot from 2021-05-18 18-17-47](https://user-images.githubusercontent.com/28944997/118659177-b6251780-b80a-11eb-8d59-c787e09db4b5.png)

As seen in the above image the flycheck symbol is in view when emacs is run normally.

### What actually happened?

When I run emacs as client the doom modeline is rendered correctly for 80 column frame width but when frame is maximized the flycheck symbol goes partially out of view as seen in the below screenshot(bottom right corner).

![Screenshot from 2021-05-18 18-16-59](https://user-images.githubusercontent.com/28944997/118659504-013f2a80-b80b-11eb-952c-ec04d084607b.png)

### Steps to reproduce

1. Start emacs daemon.
2. Run emacsclient - "emacsclient -c"
3. Maximize the window.
4. The rightmost flycheck symbol goes partially out of view.

### System Information

https://pastebin.com/kpVJbmxD

**Comment by hlissner** [comment]
See https://github.com/hlissner/doom-emacs/blob/develop/modules/ui/modeline/README.org#the-right-side-of-the-modeline-is-cut-off
