### ISSUE TITLE
M-? opens both lsp-ui peek and xref (with php intelephense)

### ISSUE THREAD

**Issue by gjm** [hlissner/doom-emacs#5069]
### 

- [X] I have searched [the FAQ](https://doomemacs.org/docs/faq.org) and [the documentation](https://doomemacs.org/docs/getting_started.org) for solutions.
- [X] I have searched [the issue tracker](https://github.com/hlissner/doom-emacs/issues) for similar issues (the closed issues too).
- [X] I have searched [the Discourse](https://discourse.doomemacs.org/docs) for any errors and solutions.
- [X] I can reproduce my issue on [the latest commit](https://github.com/hlissner/doom-emacs/commit) of Doom Emacs.
- [X] I have read [How to Debug Issues](https://discourse.doomemacs.org/how2debug) and found no solution.

### What did you expect to happen?

When pressing `M-?` the peek `lsp-ui` should appear.

### What actually happened?

Both `lsp-ui` and `xref` popups appear.
![Screenshot from 2021-05-19 17-31-21](https://user-images.githubusercontent.com/77360/118849944-25147600-b8c8-11eb-8759-e3a8b0cf65c7.png)

### Steps to reproduce

1. Open emacs
2. Open a PHP file
3. Select a method name
4. Press `M-?`

### System Information

https://pastebin.com/UjSVu64t

**Comment by samwhitlock** [comment]
I was just having the same problem with C++! I think my linked PR should fix it for this too.
