### ISSUE TITLE
find-file: pressing DEL when line is empty don't move up one directory

### ISSUE THREAD

**Issue by shackra** [hlissner/doom-emacs#5081]
### 

- [X] I have searched [the FAQ](https://doomemacs.org/docs/faq.org) and [the documentation](https://doomemacs.org/docs/getting_started.org) for solutions.
- [X] I have searched [the issue tracker](https://github.com/hlissner/doom-emacs/issues) for similar issues (the closed issues too).
- [X] I have searched [the Discourse](https://discourse.doomemacs.org/docs) for any errors and solutions.
- [X] I can reproduce my issue on [the latest commit](https://github.com/hlissner/doom-emacs/commit) of Doom Emacs.
- [X] I have read [How to Debug Issues](https://discourse.doomemacs.org/how2debug) and found no solution.

### What did you expect to happen?

DEL on empty string should move up one directory

### What actually happened?

Emacs complains with `[Text is read-only]`, then I have to write `..` to move up one directory instead.

### Describe your attempts to resolve the issue

None, it was like this some commits ago

### Steps to reproduce

1. Open Emacs
2. Press `C-x C-f`
3. Move down to any directory
4. then press DEL (backspace)

### System Information

https://pastebin.com/cy7E34nR

**Comment by hlissner** [comment]
Cannot reproduce this in vanilla Doom.

**Comment by shackra** [comment]
> Cannot reproduce this in vanilla Doom.

The rest of my configuration is here https://github.com/shackra/emacs

I don't have anything ivy-specific that could mess with `find-file`

**Comment by shackra** [comment]
Alright, the culprit is `hungry-delete`

```
(package! hungry-delete
  :recipe (:host github :repo "nflath/hungry-delete")
  :pin "0513152525c38519a5597db2d6495b56dd9cc3f0")
```

Doom Emacs is not providing this package so I guess the bug is irrelevant to the project

**Comment by shackra** [comment]
Updating to commit `d919e555e5c13a2edf4570f3ceec84f0ade71657` of hungry-delete fixes this issue

**Comment by hlissner** [comment]
Thanks for letting me know!
