### ISSUE TITLE
Issue when trying to install org roam server

### ISSUE THREAD

**Issue by alphaQ314** [hlissner/doom-emacs#5084]
### 

- [X] I have searched [the FAQ](https://doomemacs.org/docs/faq.org) and [the documentation](https://doomemacs.org/docs/getting_started.org) for solutions.
- [X] I have searched [the issue tracker](https://github.com/hlissner/doom-emacs/issues) for similar issues (the closed issues too).
- [X] I have searched [the Discourse](https://discourse.doomemacs.org/docs) for any errors and solutions.
- [X] I can reproduce my issue on [the latest commit](https://github.com/hlissner/doom-emacs/commit) of Doom Emacs.
- [X] I have read [How to Debug Issues](https://discourse.doomemacs.org/how2debug) and found no solution.

### What did you expect to happen?

I was trying to install org roam server by pasting its code in the packages.el file. Now doom doctor is showing an error, which, I'm not able to resolve. Can you please help me out?

### What actually happened?

1. I was trying to install `org-roam-server` package by pasting the following code in the packages.el file. 
```
(use-package org-roam-server
  :ensure t
  :config
  (setq org-roam-server-host "127.0.0.1"
        org-roam-server-port 8080
        org-roam-server-authenticate nil
        org-roam-server-export-inline-images t
        org-roam-server-serve-files nil
        org-roam-server-served-file-extensions '("pdf" "mp4" "ogv")
        org-roam-server-network-poll t
        org-roam-server-network-arrows nil
        org-roam-server-network-label-truncate t
        org-roam-server-network-label-truncate-length 60
        org-roam-server-network-label-wrap-length 20))
```

2.  Then I closed emacs and ran doom sync. 
3. Now every time I open emacs, I started getting the following error:

```
Warning (initialization): An error occurred while loading ‘/home/vedant/.emacs.d/init.el’:

Error in private config: config.el, (file-missing Cannot open load file No such file or directory org-roam-server)

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.

```

### Describe your attempts to resolve the issue

1. I tried deleting the org-roam-server code from the packages.el file, but I'm still getting the same error. 
2. I tried running doom doctor and got the following error:

```
The doctor will see you now...

> Checking your Emacs version...
! Emacs 26.3 detected. Doom is dropping Emacs 26.x support very soon. Consider upgrading to Emacs 27.1.
> Checking for Emacs config conflicts...
> Checking for private config conflicts...
> Checking for stale elc files...
> Checking for problematic git global settings...
> Checking Doom Emacs...
  x There was an unexpected error
    Message: Invalid read syntax
    Data: (invalid-read-syntax . "#")
    Backtrace:
      (read #<buffer  *load*-524906>)
      (eval-buffer #<buffer  *load*-524906> nil "/home/vedant/.doom.d/custom.el"
      (load-with-code-conversion "/home/vedant/.doom.d/custom.el" "/home/vedant/
      (load "~/.doom.d/custom.el" noerror t)
      (progn (load custom-file (quote noerror) (not doom-debug-mode)))
      (if custom-file (progn (load custom-file (quote noerror) (not doom-debug-m
      (if no-config-p nil (maphash (doom-module-loader doom-module-config-file) 
      (progn (if doom-debug-p (progn (let ((inhibit-message (active-minibuffer-w
      (if init-p (progn (if doom-debug-p (progn (let ((inhibit-message (active-m
      (let* ((init-p (and t (condition-case e (let (file-name-handler-alist) (lo
  ! Extended backtrace logged to .local/doom.error.log

```

### Steps to reproduce

1. Run "doom doctor" in terminal

### System Information

https://pastebin.com/AnkkLeqt

**Comment by iyefrat** [comment]
This is not how you install packages in doom, please refer to the [getting started guide](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org) in general, but in this specific case:

add the following to your `packages.el`:
```lisp
(package! org-roam-server)
```
this installs the package for you, then write the following in your `config.el` in order to configure it:
```lisp
(use-package org-roam-server
  :config
  (setq org-roam-server-host "127.0.0.1"
        org-roam-server-port 8080
        org-roam-server-authenticate nil
        org-roam-server-export-inline-images t
        org-roam-server-serve-files nil
        org-roam-server-served-file-extensions '("pdf" "mp4" "ogv")
        org-roam-server-network-poll t
        org-roam-server-network-arrows nil
        org-roam-server-network-label-truncate t
        org-roam-server-network-label-truncate-length 60
        org-roam-server-network-label-wrap-length 20))
```
as the `:ensure t` key tries to install the package for you, but is generally less robust that `straight.el`, which powers doom's package management. In general copy pasting install instructions from readme's is not the best idea, since sometimes they interfere with doom's built in package management. But whenever you do, put it in your `config.el`, since `packages.el` should only contain package install declarations, but again, I highly suggest you read the [getting started guide](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org) in full.

**Comment by iyefrat** [comment]
Oh also remember to give your issues a relevant title and not "Briefly summarize your issue here"

**Comment by RBckmnn** [comment]
Do not use `ensure` to install packages. Packages you want to have installed go into `packages.el`.

See the "Installing packages" section in the FAQ

**Comment by alphaQ314** [comment]
> This is not how you install packages in doom, please refer to the [getting started guide](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org) in general, but in this specific case:
> 
> add the following to your `packages.el`:
> 
> ```lisp
> (package! org-roam-server)
> ```
> 
> this installs the package for you, then write the following in your `config.el` in order to configure it:
> 
> ```lisp
> (use-package org-roam-server
>   :config
>   (setq org-roam-server-host "127.0.0.1"
>         org-roam-server-port 8080
>         org-roam-server-authenticate nil
>         org-roam-server-export-inline-images t
>         org-roam-server-serve-files nil
>         org-roam-server-served-file-extensions '("pdf" "mp4" "ogv")
>         org-roam-server-network-poll t
>         org-roam-server-network-arrows nil
>         org-roam-server-network-label-truncate t
>         org-roam-server-network-label-truncate-length 60
>         org-roam-server-network-label-wrap-length 20))
> ```
> 
> as the `:ensure t` key tries to install the package for you, but is generally less robust that `straight.el`, which powers doom's package management. In general copy pasting install instructions from readme's is not the best idea, since sometimes they interfere with doom's built in package management. But whenever you do, put it in your `config.el`, since `packages.el` should only contain package install declarations, but again, I highly suggest you read the [getting started guide](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org) in full.

Thank you so much for your response. I managed to get org-roam-server running with your help. However, I'm still getting the following error when I launch emacs:
```
Warning (initialization): An error occurred while loading ‘/home/vedant/.emacs.d/init.el’:

Invalid read syntax: #

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.

```
And running doom doctor gets the same error as mentioned in the original post.

**Comment by iyefrat** [comment]
As the error says, in these situations you should:
```
To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.
```
In this case it's likely you used `#` as a comment by accident somewhere, or just left one lying around. Did that happen? elisp uses `;` for comments.

**Comment by alphaQ314** [comment]
There were some `#` in there. I'm not sure how they ended up there. Anyway, deleting those `#` got another error with the fonts, and managed to get rid of that one on my own. Thank you so much for your help @iyefrat 

I have been trying to learn emacs for a while now. I hope I can improve the quality of my questions and maybe one day even solve other noob queries. Thank your patience mate. Cheers.
