### ISSUE TITLE
Unable to install doom

### ISSUE THREAD

**Issue by bnjmnt4n** [hlissner/doom-emacs#5088]
### 

- [X] I have searched [the FAQ](https://doomemacs.org/docs/faq.org) and [the documentation](https://doomemacs.org/docs/getting_started.org) for solutions.
- [X] I have searched [the issue tracker](https://github.com/hlissner/doom-emacs/issues) for similar issues (the closed issues too).
- [X] I have searched [the Discourse](https://discourse.doomemacs.org/docs) for any errors and solutions.
- [X] I can reproduce my issue on [the latest commit](https://github.com/hlissner/doom-emacs/commit) of Doom Emacs.
- [X] I have read [How to Debug Issues](https://discourse.doomemacs.org/how2debug) and found no solution.

### What did you expect to happen?

I performed a fresh install of Doom as per https://github.com/hlissner/doom-emacs#install.

### What actually happened?

Install command:

```
❯ doom install
Installing straight...
x There was an unexpected error
  Message: File is missing
  Data: (file-missing . "Cannot open load file")
  Backtrace:
    (require straight "/home/bnjmnt4n/.emacs.d/.local/straight/repos/straight.
    (let ((repo-dir (doom-path straight-base-dir "straight/repos/straight.el")
    (doom--ensure-straight (:host github :repo "raxod502/straight.el" :branch
    (let* ((--cl-rest-- (alist-get 'straight packages)) (recipe (car (cdr (pli
    (let ((packages (doom-package-list nil 'core))) (let* ((--cl-rest-- (alist
    (progn (if doom-debug-p (progn (let ((inhibit-message (active-minibuffer-w
    (if (or force-p (null (and (boundp 'straight-recipe-repositories) straight
    (doom-initialize-core-packages)
    (load-with-code-conversion "/home/bnjmnt4n/.emacs.d/core/core-cli.el" "/ho
    (require core-cli)
! Extended backtrace logged to .local/doom.error.log
No catch for tag: exit, 255
```

Backtrace: https://pastebin.com/YGnjk5Ew

### Describe your attempts to resolve the issue

My guess is this could be related to https://github.com/hlissner/doom-emacs/commit/6321b3a249077d02fa67a0d4b60ff40e914d4c05 from looking at the backtrace.

### Steps to reproduce

```
git clone --depth 1 https://github.com/hlissner/doom-emacs ~/.emacs.d
~/.emacs.d/bin/doom install
```

### System Information

NixOS unstable, Emacs GCC + PGTK

**Comment by zeroDivisible** [comment]
I'm getting the same issue for a fresh installation on doom. OSX as the operating system.

**Comment by hlissner** [comment]
```sh
rm -rf ~/.emacs.d/.local/straight
doom sync
```

**Comment by espentrydal** [comment]
I am getting the same error on PopOS (Ubuntu). Removing .local/straight or the whole installation and reinstalling did not fix it. `doom sync` gives the same error as `doom install`.

**Comment by bnjmnt4n** [comment]
I've tried that as well. I initially performed a doom upgrade with the following diff: https://github.com/hlissner/doom-emacs/compare/abbbc9eafe22ec47db6c512ec960189aed4f4476...3a1aaacbad1b778a2d0d765947a4e0c7c5f069ee, which caused the error I posted initially. Performing the removal and `doom sync` also led to the same error, at which point I tried a fresh install of doom after `rm -rf ~/.emacs.d`. My guess is that https://github.com/hlissner/doom-emacs/commit/6321b3a249077d02fa67a0d4b60ff40e914d4c05 might have affected the installation here: https://github.com/hlissner/doom-emacs/blob/6321b3a249077d02fa67a0d4b60ff40e914d4c05/core/core-packages.el#L122-L142
although I'm not completely sure, and don't have a lot of emacs-lisp experience yet.

**Comment by espentrydal** [comment]
Newest pull still gives an error, though different:

```
> Installing straight...

error: unknown switch `b'
usage: git init [-q | --quiet] [--bare] [--template=<template-directory>] [--shared[=<permissions>]] [<directory>]

    --template <template-directory>
                          directory from which templates will be used
    --bare                create a bare repository
    --shared[=<permissions>]
                          specify that the git repository is to be shared amongst several users
    -q, --quiet           be quiet
    --separate-git-dir <gitdir>
                          separate git dir from working tree
    --object-format <hash>
                          specify the hash algorithm to use
fatal: remote origin already exists.
fatal: remote error: upload-pack: not our ref e46292db6910e8e7701d53acaf188de0101ae30f
fatal: the remote end hung up unexpectedly
fatal: Could not parse object 'e46292db6910e8e7701d53acaf188de0101ae30f'.
  ✓ Done!
x There was an unexpected error
  Message: File is missing
  Data: (file-missing . "Cannot open load file")
  Backtrace:
    (require straight "/home/espen/.emacs.d/.local/straight/repos/straight.el/
    (let ((repo-dir (doom-path straight-base-dir "straight/repos/straight.el")
    (doom--ensure-straight (:host github :repo "raxod502/straight.el" :branch
    (let* ((--cl-rest-- (alist-get 'straight packages)) (recipe (car (cdr (pli
    (let ((packages (doom-package-list nil 'core))) (let* ((--cl-rest-- (alist
    (progn (if doom-debug-p (progn (let ((inhibit-message (active-minibuffer-w
    (if (or force-p (null (and (boundp 'straight-recipe-repositories) straight
    (doom-initialize-core-packages)
    (load-with-code-conversion "/home/espen/.emacs.d/core/core-cli.el" "/home/
    (require core-cli)
! Extended backtrace logged to .emacs.d/.local/doom.error.log
No catch for tag: exit, 255
```

**Comment by alexeiz** [comment]
I had to reset it to change e5b52e2 to make install work.

**Comment by bnjmnt4n** [comment]
Thanks @hlissner as always for the quick fix!

@espentrydal Seems like the `git init -b` command used is only available in Git 2.28: https://stackoverflow.com/questions/64787301/git-init-b-branch-name-command-in-terminal-is-throwing-an-unknown-switch

**Comment by hlissner** [comment]
> @espentrydal Seems like the `git init -b` command used is only available in Git 2.28: https://stackoverflow.com/questions/64787301/git-init-b-branch-name-command-in-terminal-is-throwing-an-unknown-switch

Thanks for letting me know! Since straight already uses it, it's not trivial for Doom to be backwards compatible, so I've updated the minimum required version of git in our docs.

**Comment by marcbowes** [comment]
I updated doom today and it broke. I'm not 100% sure this issue is related, but it's in the diff and related to straight! I'm on Emacs28 with nativecomp.

```
❯ doom upgrade
> Preparing to upgrade Doom Emacs and its packages...
- A new version of Doom Emacs is available!

  Old revision: b0e59ccdcc (2 weeks ago)
  New revision: daa50557a4 (13 hours ago)

Link to diff: https://github.com/hlissner/doom-emacs/compare/b0e59ccdcc133baa111f28eec488a8a4aab05c6d...daa50557a4f2b2c5f712e17fbe146ade973ee5aa
View the comparison diff in your browser? (y or n) n
Proceed with upgrade? (y or n) y
> Upgrading Doom Emacs...
  > Cleaning .elc files
    - No elc files to clean
  - Preparing straight for an update
  - From https://github.com/hlissner/doom-emacs
   * [new branch]          develop    -> _upgrade_develop
   * [new branch]          develop    -> _upgrade/develop
- Reloading Doom Emacs
> Installing straight...

Initialized empty Git repository in /Users/$me/doom-emacs/.local/straight/repos/straight.el/.git/

From https://github.com/raxod502/straight.el
 * branch            e46292db6910e8e7701d53acaf188de0101ae30f -> FETCH_HEAD
HEAD is now at e46292d Properly manage `native-comp-deferred-compilation-deny-list'. (#761)
  ✓ Done!
> Executing 'doom upgrade -p' 2021-05-25 10:16:09
  > Synchronizing your config with Doom Emacs...
    > Regenerating envvars file at "~/doom-emacs/.local/env"
      ✓ Successfully generated "~/doom-emacs/.local/env"
      Eager macro-expansion failure: (file-missing "Cannot open load file" "No such file or directory" "use-package-core")
      Eager macro-expansion failure: (file-missing "Cannot open load file" "No such file or directory" "use-package-core")
    x There was an unexpected error
      Message: File is missing
      Data: (file-missing . "Cannot open load file")
      Backtrace:
        (use-package ox-gfm :after org)
        (use-package! ox-gfm :after org)
        (load-with-code-conversion "/Users/$me/.doom.d/packages.el" "/Users/$me
        (load "/Users/$me/.doom.d/packages.el" noerror nomessage nosuffix)
        (if (not noeval) (load file noerror 'nomessage 'nosuffix) (if (file-exists
        (progn (if (not noeval) (load file noerror 'nomessage 'nosuffix) (if (file
        (unwind-protect (progn (if (not noeval) (load file noerror 'nomessage 'nos
        (save-current-buffer (set-buffer temp-buffer) (unwind-protect (progn (if (
        (let ((temp-buffer (generate-new-buffer " *temp*" t))) (save-current-buffe
        (condition-case e (let ((temp-buffer (generate-new-buffer " *temp*" t))) (
    ! Extended backtrace logged to ~/doom-emacs/.local/doom.error.log
```

**Comment by mbosley** [comment]
@marcbowes, I was running into this problem as well on Mac OS Big Sur. The problem was caused by an outdated version of Git not accepting the -b flag. In my case, my anaconda install was causing version clash with my homebrew install of Git. Once I fixed that and had my path pointing at the correct version of Git, I removed my .straight directory as per @hlissner's instructions and `bin/doom sync`, and things proceeded as expected. Hope this helps!

**Comment by marcbowes** [comment]
I have 2.28.0 which supports `git init -b`. It's possible some other version of git is being run by doom. I'll look into that, thanks @mbosley.

**Comment by hlissner** [comment]
@marcbowes This is an unrelated issue. It seems you have a `use-package!` block in `~/.doom.d/packages.el`. That is not the correct place for those. [Read our docs on how to do package management in Doom](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#package-management).
