### ISSUE TITLE
Literate config conditional tangling doesn't work

### ISSUE THREAD

**Issue by DominikMendel** [hlissner/doom-emacs#5089]
### 

- [X] I have searched [the FAQ](https://doomemacs.org/docs/faq.org) and [the documentation](https://doomemacs.org/docs/getting_started.org) for solutions.
- [X] I have searched [the issue tracker](https://github.com/hlissner/doom-emacs/issues) for similar issues (the closed issues too).
- [X] I have searched [the Discourse](https://discourse.doomemacs.org/docs) for any errors and solutions.
- [X] I can reproduce my issue on [the latest commit](https://github.com/hlissner/doom-emacs/commit) of Doom Emacs.
- [X] I have read [How to Debug Issues](https://discourse.doomemacs.org/how2debug) and found no solution.

### What did you expect to happen?

In my literate Doom config.org my tangle conditions result in the tangle being completely ignored. In the snippet below the org-journal-dir should be either one or the other based on the OS type.

* Org journal per system 1
#+begin_src elisp :tangle (if (eq (doom-system-distro) 'arch) "yes" "no")
(setq org-journal-dir "~/Dropbox/org/journal")
#+end_src

* Org journal per system 2
#+begin_src elisp :tangle (if (eq (doom-system-distro) 'arch) "no" "yes")
(setq org-journal-dir "~/Dropbox/org/work/journal")
#+end_src

### What actually happened?

Both tangle attempts are completely ignored and not added into the config.el. 

### Describe your attempts to resolve the issue

Tried tangling with other functions. 
Tried using a "when" instead of "if". 
Asked the Doom Emacs Discord twice. 

### Steps to reproduce

1. Have a literate Doom Emacs config.org.
2. Input the code snippet provided to tangle. 
3. Run Doom Sync.
4. Restart Doom Emacs.
5. Config.el should have been updated correctly based on the tangling. 

### System Information

https://pastebin.com/R0iWRbmi

**Comment by DominikMendel** [comment]
The pastebin is useless information. I couldn't extract what I think you would need. I tried running M-x doom/info and it failed due to emacs-repository-branch is void.

**Comment by hlissner** [comment]
Try this

```org
#+begin_src elisp :tangle (if (eq (doom-system-distro) 'arch) "config.el" "no")
(setq org-journal-dir "~/Dropbox/org/journal")
#+end_src
```

```
#+begin_src elisp :tangle (if (eq (doom-system-distro) 'arch) "no" "config.el")
(setq org-journal-dir "~/Dropbox/org/work/journal")
#+end_src
```

As our issue tracker isn't for how-to questions I will close this and later delete this thread, but feel to follow up here (or better, on the Discord).

**Comment by DominikMendel** [comment]
Thanks for the quick response, and sorry I thought this was a Doom issue with how the config.el was made. 

Sadly, this did not work. Neither block gets tangled into the "config.el". I feel quite stuck on this topic

**Comment by hlissner** [comment]
Odd. I'm using 

```
#+BEGIN_SRC elisp :tangle (if (eq (doom-system-distro) 'nixos) "config.el" "no")
...
#+END_SRC
```

And this is tangling to config.el as expected.

**Comment by DominikMendel** [comment]
I got it to work. It was a battle with Babel itself and what I think was different stages of overwriting the tangles. 

#+PROPERTY: header-args+ :tangle config.el
That at the top of my config.org file did it + your changes. Thank you!

**Comment by hlissner** [comment]
I've simplified the tangle process in 8424e0a, which should indirectly fix your earlier use case.
