### ISSUE TITLE
Recursive load error in buffers.el

### ISSUE THREAD

**Issue by zeronone** [hlissner/doom-emacs#509]
### Observed behavior
Latest develop branch gives the following error and fails to start emacs.
<img width="783" alt="screen shot 2018-04-05 at 12 37 47" src="https://user-images.githubusercontent.com/1908865/38346183-61f8d8b8-38ce-11e8-8fbe-9ef48cd84c8b.png">

### Steps to reproduce

1. `make clean`
2. `make install && make compile`
3. `emacs`

### System information

- Mac OSX 10.12
- GNU Emacs 25.3.1

**Comment by hlissner** [comment]
I've so far been unable to reproduce this on Emacs 25.3.1 in OSX 10.11 (don't have a newer mac to test on).

What does your `~/.emacs.d/init.el` and private config look like? Is it on github somewhere where I can see it?

**Comment by timHau** [comment]
Can confirm the issue on Emacs 25.3.1 in OSX 10.13.4 on latest develop. 
`make doctor` says that everything seems fine though.

Master seems to work fine so far for me. But I got an (maybe) related `recursive load` error when i run `org-mode`

<img width="1317" alt="bildschirmfoto 2018-04-23 um 10 10 49" src="https://user-images.githubusercontent.com/12029285/39114602-9c1b5cea-46df-11e8-906c-1cebcfd0ce4f.png">

**Comment by hlissner** [comment]
@timHau How did you install Emacs? And if through homebrew, which recipe?

**Comment by timHau** [comment]
@hlissner I installed it via https://emacsformacosx.com/

**Comment by mattly** [comment]
I'm seeing this too. I thought I'd give doom another shot recently, saw how far ahead develop is, and then had the same problem as described above. Fresh config, no customization. MacOS 10.13.4, emacs-plus 25.3

**Comment by hlissner** [comment]
The common link here seems to be High Sierra (or newer). I can't reproduce this on El Capitan or Linux.

Could one you try the `emacs-plus` recipe? e.g. `brew install emacs-plus` (gnutls or cocoa are enabled by default, so no flags necessary).

I'll look into this and try to get High Sierra going in a VM.

**Comment by mattly** [comment]
I had tried it with emacs-plus.

I don't yet have High Sierra on my work Mac (corporate IT BS and laziness), and didn't encounter any problems with doom on that computer, so I concur that it's a High Sierra-specific problem.

**Comment by timHau** [comment]
I tracked the error down to commit 2933142d (first bad commit)
after i read your commit message i did

`mkdir ~/.doom.d
 cp ~/.emacs.d/init.el ~/.doom.d/init.el`

now i get this error:

<img width="680" alt="bildschirmfoto 2018-04-30 um 14 59 59" src="https://user-images.githubusercontent.com/12029285/39428317-37ac67e2-4c87-11e8-85ea-a2e4dc8cd85a.png">

I hope that will help to fix it. By the way, is there some documentation about the breaking changes in develop?

**Comment by hlissner** [comment]
You have to copy init.example.el, not init.el, to ~/.doom.d/init.el. 

Unfortunately, documentation is really light, and will be until the 2.1 release sometime next week. Sorry about that!

Hop on our discord, if you haven't already. Quite a few helpful folks are privacy to the changes on develop and would be happy to help.

**Comment by timHau** [comment]
I got it working doing the following:

1. created a directory ~/.doom.d
2. copied my modules/private/custom module to ~/.doom.d
3. copied init.example.el to ~/.doom.d/init.el

thanks :)

**Comment by hlissner** [comment]
@zeronone I was hoping that b76addd may have resolved your issue. Could you let me know if that's the case?

**Comment by zeronone** [comment]
@hlissner I tried the specific commit and the most recent revision of `develop`. The problem still persists on emacs 25.3.1.

**Comment by yogsototh** [comment]
I'm still having this issue using the GUI, not in the terminal.

~~~
 emacs --version
GNU Emacs 25.3.2
Copyright (C) 2017 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of GNU Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
~~~

It is fixed after upgrading to emacs 26, installed through [`nix`](https://nixos.org/nix/)

~~~
> nix-env -i emacs-26.1
> nix-env -i emacs-mac-26.1-7.0
> cp -r /nix/store/*-emacs-mac-26.1-7.0/Applications/Emacs.app /Applications/
~~~

**Comment by hlissner** [comment]
Recently, on the `develop` branch, I've made some changes to the load order of a couple hooks that I suspect were causing recursive load issues on Emacs 25.x. Please update and let me know if that resolves this issue for you guys.
