### ISSUE TITLE
doom doctor fails to parse git version on MacOS

### ISSUE THREAD

**Issue by paolo** [hlissner/doom-emacs#5093]
### 

- [X] I have searched [the FAQ](https://doomemacs.org/docs/faq.org) and [the documentation](https://doomemacs.org/docs/getting_started.org) for solutions.
- [X] I have searched [the issue tracker](https://github.com/hlissner/doom-emacs/issues) for similar issues (the closed issues too).
- [X] I have searched [the Discourse](https://discourse.doomemacs.org/docs) for any errors and solutions.
- [X] I can reproduce my issue on [the latest commit](https://github.com/hlissner/doom-emacs/commit) of Doom Emacs.
- [X] I have read [How to Debug Issues](https://discourse.doomemacs.org/how2debug) and found no solution.

### What did you expect to happen?

When I run `doom doctor` It attempts to validate my currently installed git version, which is: `git version 2.30.1 (Apple Git-130)`, since this version if greater than `2.28` I expect it to pass the validation.

### What actually happened?

When I run `doom doctor` I get the following output instead:
```
> Executing 'doom doctor' 2021-05-25 08:59:39
  The doctor will see you now...

  > Checking your Emacs version...
  > Checking for Doom's prerequisites...
    x There was an unexpected error
      Message: error
      Data: (error . "Invalid version syntax: ‘2.30.1 (Apple Git-130)’")
      Backtrace:
        (signal error ("Invalid version syntax: ‘2.30.1 (Apple Git-130)’"))
        (error "Invalid version syntax: `%s'" "2.30.1 (Apple Git-130)")
        (version-to-list "2.30.1 (Apple Git-130)")
        (version< "2.30.1 (Apple Git-130)" "2.28")
        (if (version< version "2.28") (progn (progn (if inhibit-message nil (doom-
        (let ((version (car (cdr (split-string (cdr (doom-call-process "git" "vers
        (if (not (executable-find "git")) (progn (if inhibit-message nil (doom--pr
        (let ((doom-output-indent (+ doom-output-indent-increment doom-output-inde
        (let nil :bare t (doom--print (doom--format (format "The doctor will see y
        ((closure ((plist :bare t :group "Diagnostics") (aliases doc) (name . doct
    ! Extended backtrace logged to .emacs.d/.local/doom.error.log
```

### Describe your attempts to resolve the issue

I believe the problem was introduced in this file: `https://github.com/hlissner/doom-emacs/blob/develop/core/cli/doctor.el` at line 65.

If I manually run this statement:
```
(cadr (split-string (cdr (doom-call-process "git" "version")) " version "))
```
I get this result:
```
"2.30.1 (Apple Git-130)"
```
Which I'm guessing that `version<` or rather `version-to-list` is unable to parse.

### Steps to reproduce

Required: MacOS
1. `doom up`
2. `doom doctor`

### System Information

https://pastebin.com/rmjHVfWw

**Comment by hlissner** [comment]
As of 7b5baf3 the git version check should be robust enough to address this issue. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
