### ISSUE TITLE
Cannot open any file because `global-git-commit-mode` cannot find `magit-section`

### ISSUE THREAD

**Issue by danilevy1212** [hlissner/doom-emacs#5095]
### 

- [X] I have searched [the FAQ](https://doomemacs.org/docs/faq.org) and [the documentation](https://doomemacs.org/docs/getting_started.org) for solutions.
- [X] I have searched [the issue tracker](https://github.com/hlissner/doom-emacs/issues) for similar issues (the closed issues too).
- [X] I have searched [the Discourse](https://discourse.doomemacs.org/docs) for any errors and solutions.
- [X] I can reproduce my issue on [the latest commit](https://github.com/hlissner/doom-emacs/commit) of Doom Emacs.
- [X] I have read [How to Debug Issues](https://discourse.doomemacs.org/how2debug) and found no solution.

### What did you expect to happen?

A file to open.

### What actually happened?

File wont open, an error will be produced similar to this: https://pastebin.pl/view/4e7415b4

### Describe your attempts to resolve the issue

Not much I can do since I cannot open any file.

### Steps to reproduce

1. Open emacs
2. Open any file.

### System Information

https://pastebin.com/wAL4ytEn

**Comment by hlissner** [comment]
Cannot access https://pastebin.pl/view/4e7415b4. Please upload it to pastebin.com instead.

**Comment by danilevy1212** [comment]
My bad, updated the pastebin link: https://pastebin.com/wAL4ytEn

**Comment by kaelte** [comment]
I see this error already by starting emacs without opening a file.
I cannot open any file either but I can start Gnus to read my Email, using `M-x gnus`.

**Comment by nchisholm** [comment]
I ran into the same issue after a recent `doom upgrade`. I also tried reinstalling fresh to see if the problem would go away, but it did not.

A workaround was to simply add `(package! magit-section)` to `packages.el`.  Is this a dependency that was missed?

**Comment by kaelte** [comment]
Thanks @nchisholm for pointing out the workaround.
Another "solution" is to comment out `magit` in `init.el`:
```;;magit             ; a git porcelain for Emacs```

**Comment by hlissner** [comment]
Seems I had the bad luck to land on a broken commit in the middle of a refactor upstream. I've bumped magit et co in 364e74a, which should resolve this issue. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by Macavirus** [comment]
Just for some anecdata -- I had the same problem and your fix resolved it @hlissner . I think this issue can be closed

The update I ran with `doom upgrade` fast-forwarded the following commits:
```
doom updated 54067455e7 -> 69ea5c2020
magit updated (e378827 -> b68a760)
```
