### ISSUE TITLE
Mint Module (lang)

### ISSUE THREAD

**Issue by jgarte** [hlissner/doom-emacs#5097]
### 

- [X] I have read the [contributing guidelines](https://discourse.doomemacs.org/how2contribute).
- [X] I have searched [the issue tracker](https://github.com/hlissner/doom-emacs/issues?q=label%3A%221.+request%22+) for similar requests.
- [X] I have searched [the module list](https://doomemacs.org/docs/modules.org) in case my feature was already implemented.
- [X] I have confirmed that my request remains unfulfilled on [the latest commit of Doom](https://github.com/hlissner/doom-emacs/commit).

### Describe your request

I want to open up discussion about adding a [mint](https://www.mint-lang.com/) layer to spacemacs:

### Briefly explain its use-case

Here are some potential pieces to the layer:

https://github.com/creatorrr/emacs-mint-mode

## Language Server Protocol

The language server for mint is built into the language itself. 

See here:

https://github.com/mint-lang/mint/tree/df3ac8b3ef81a2f3a5e46ccc09d8a1b3cd16066e/src/ls

and here:

https://spectrum.chat/mint-lang/development/language-server-support~227be091-fb65-40fb-ab60-952be791b28d

**Comment by hlissner** [comment]
Thanks for the request, but the configuration required for `mint-mode` is too trivial to warrant its own module. When this changes I'll gladly reconsider.
