### ISSUE TITLE
{{{ Fresh installation error (Windows) }}}

### ISSUE THREAD

**Issue by limaco** [hlissner/doom-emacs#5099]
### 

- [X] I have searched [the FAQ](https://doomemacs.org/docs/faq.org) and [the documentation](https://doomemacs.org/docs/getting_started.org) for solutions.
- [X] I have searched [the issue tracker](https://github.com/hlissner/doom-emacs/issues) for similar issues (the closed issues too).
- [X] I have searched [the Discourse](https://doomemacs.org/d/docs) for any errors and solutions.
- [X] I can reproduce my issue on [the latest commit](https://github.com/hlissner/doom-emacs/commit) of Doom Emacs.
- [X] I have read [How to Debug Issues](https://doomemacs.org/d/how2debug) and found no solution.

### What did you expect to happen?

After problems with doom upgrade, I proceeded to delete .emacs.d folder and reinstall doom emacs

### What actually happened?

Installation unsuccessful, file missing
[doom.error.log](https://github.com/hlissner/doom-emacs/files/6546556/doom.error.log)

Carlos@Despacho-casa MINGW64 ~/.emacs.d/bin (develop)
$ doom doctor
> Installing straight...
x There was an unexpected error
  Message: File is missing
  Data: (file-missing . "Cannot open load file")
  Backtrace:
    (require straight "c:/Users/Carlos/.emacs.d/.local/straight/repos/straight
    (let ((repo-dir (doom-path straight-base-dir "straight/repos/straight.el")
    (doom--ensure-straight (:host github :repo "raxod502/straight.el" :branch
    (let* ((--cl-rest-- (alist-get 'straight packages)) (recipe (car (cdr (pli
    (let ((packages (doom-package-list nil 'core))) (let* ((--cl-rest-- (alist
    (progn (if doom-debug-p (progn (let ((inhibit-message (active-minibuffer-w
    (if (or force-p (null (and (boundp 'straight-recipe-repositories) straight
    (doom-initialize-core-packages)
    (eval-buffer #<buffer  *load*-236067> nil "c:/Users/Carlos/.emacs.d/core/c
    (load-with-code-conversion "c:/Users/Carlos/.emacs.d/core/core-cli.el" "c:
! Extended backtrace logged to ~/.emacs.d/.local/doom.error.log
No catch for tag: exit, 255

### Describe your attempts to resolve the issue

Tried the same procedure with:
Git bash
CMD
Powershell
Ubuntu TLS for windows

### Steps to reproduce

1. Delete .emacs.d folder
2. git clone https://github.com/hlissner/doom-emacs ~/.emacs.d
3. ~/.emacs.d/bin/doom install

### System Information

https://pastebin.com/9DtN0q5Y

**Comment by destroyer449** [comment]
I'm not positive this is the issue, but the official instructions say that you need to clone with the option `--depth 1`

**Comment by hlissner** [comment]
This was fixed in b0741336d. Update Doom.

Also, I could not access your doom/info link.

**Comment by limaco** [comment]
> 
> 
> This was fixed in [b074133](https://github.com/hlissner/doom-emacs/commit/b0741336d182a4917447cd515077e18794bdf428). Update Doom.
> 
> Also, I could not access your doom/info link.

as far as it can't be installed, there is possibility to generate a doom/info
