### ISSUE TITLE
open brace indentation in cc-mode

### ISSUE THREAD

**Issue by ustcpxy** [hlissner/doom-emacs#510]
I am writing a few C programs and I noticed that the default brace indentation is as follows:
```
if ( a < b )
    {
        // code 
    }
```

How would I go about modifying this behaviour to achieve the following instead:
```
if ( a < b )
{
    // code
}
```

BTW:
I add below code in my private config but it takes no effect. 
```
(add-to-list 'c-offsets-alist '(substatement-open . 0))
```

**Comment by scturtle** [comment]
Cause:
https://github.com/hlissner/doom-emacs/blob/5dacbb7cb1c6ac246a9ccd15e6c4290def67757c/modules/lang/cc/config.el#L87-L88
Hot fix:
```lisp
(after! cc-mode
  (map! :after cc-mode :mode c-mode-base "{" #'c-electric-brace))
```

**Comment by hlissner** [comment]
@scturtle That should have no baring on line indentation in cc modes. These settings are present in the `:config default` module, which are meant to replace electric keys in the C modes:

```elisp
  (dolist (brace '("(" "{" "["))
    (sp-pair brace nil
             :post-handlers '(("||\n[i]" "RET") ("| " "SPC"))
             ;; I likely don't want a new pair if adjacent to a word or opening brace
             :unless '(sp-point-before-word-p sp-point-before-same-p)))
```

@ustcpxy The default style used is [an adjusted version of the `linux` style](https://github.com/hlissner/doom-emacs/blob/develop/modules/lang/cc/config.el#L72-L99).

Have you changed `c-default-style`?

**Comment by hlissner** [comment]
Scratch that, I see the problem now. @scturtle's solution works:

```elisp
(map! :after cc-mode
      :map c-mode-base-map
      "{" #'c-electric-brace)
```

I'll look into this to see if I can find a better solution.

**Comment by ustcpxy** [comment]
@hlissner I don't change the `c-default-style`.

**Comment by ustcpxy** [comment]
yes, @scturtle's solution works for me. Thanks.

**Comment by hlissner** [comment]
I've merged @scturtle's solution into `develop`, so I'll consider this fixed. Let me know if that isn't the case.
