### ISSUE TITLE
format +onsave fails with void function -- +format-lsp-enable-on-save-maybe-h

### ISSUE THREAD

**Issue by ChrisDavison** [hlissner/doom-emacs#5104]
### 

- [X] I have searched [the FAQ](https://doomemacs.org/docs/faq.org) and [the documentation](https://doomemacs.org/docs/getting_started.org) for solutions.
- [X] I have searched [the issue tracker](https://github.com/hlissner/doom-emacs/issues) for similar issues (the closed issues too).
- [X] I have searched [the Discourse](https://doomemacs.org/d/docs) for any errors and solutions.
- [X] I can reproduce my issue on [the latest commit](https://github.com/hlissner/doom-emacs/commit) of Doom Emacs.
- [X] I have read [How to Debug Issues](https://doomemacs.org/d/how2debug) and found no solution.

### What did you expect to happen?

Emacs would start. Code would format on save.

### What actually happened?

+format-lsp-enable-on-save-maybe-h seems to be a void function inside `modules/editor/format/config.el`

This seems to have been introduced in commit `6e7a19a2f`

On startup, emacs errors, and then proceeds to error with subsequent commands until `init.el` is modified externally, emacs killed, reloaded, and restarted.

Screenshot of normal startup
![20210527T093028--_doom_ – Doom Emacs](https://user-images.githubusercontent.com/2690868/119794784-5d6b1400-bec7-11eb-8229-cec53b6a8190.png)

Screenshot of `--debug-init` startup (had to envoke a command, in my case an org agenda shortcut, to encourage emacs to continue doing something)
![20210527T093115--_Backtrace_ – Doom Emacs](https://user-images.githubusercontent.com/2690868/119794785-5e03aa80-bec7-11eb-8c75-9961355137b2.png)

### Describe your attempts to resolve the issue

- Disabling `format` (obviously works)
- `format` without `+onsave` works.
- Renaming `+format-lsp-enable-on-save-maybe-h` to `+format-enable-for-lsp-on-save-maybe-h` - doesn't work (edit: this was a blind guess looking at the source for format)

### Steps to reproduce

- Use newest doom.
- Have `(format +onsave)` in init
- Reload doom
- Enter a document that should have 'onsave'

### System Information

https://pastebin.com/wWeVDZd2

**Comment by TheEros** [comment]
(format +onsave) => (format ), delete +onsave emporary repair

**Comment by andreasknoepfle** [comment]
Looks a lot like it was introduced with this https://github.com/hlissner/doom-emacs/commit/6e7a19a2f42baba16870a06f6187da9ee290fa29 

Rolling back to the commit before that work just fine for me.

**Comment by abougouffa** [comment]
The same problem here, occurred today after upgrade

**Comment by hlissner** [comment]
As of c9653ba this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by LennyPhoenix** [comment]
I'm getting this issue on a clean install upon initialisation:
![image](https://user-images.githubusercontent.com/57148878/119892158-be2f3680-bf31-11eb-95be-cf327032a1c0.png)

**Comment by hlissner** [comment]
Whoops, missed a reference. Should be fixed in 005a71e.

**Comment by LennyPhoenix** [comment]
Can confirm that this is working now 👍
