### ISSUE TITLE
Ligatures stopped working (Emacs 28)

### ISSUE THREAD

**Issue by gjm** [hlissner/doom-emacs#5106]
### 

- [X] I have searched [the FAQ](https://doomemacs.org/docs/faq.org) and [the documentation](https://doomemacs.org/docs/getting_started.org) for solutions.
- [X] I have searched [the issue tracker](https://github.com/hlissner/doom-emacs/issues) for similar issues (the closed issues too).
- [X] I have searched [the Discourse](https://doomemacs.org/d/docs) for any errors and solutions.
- [X] I can reproduce my issue on [the latest commit](https://github.com/hlissner/doom-emacs/commit) of Doom Emacs.
- [X] I have read [How to Debug Issues](https://doomemacs.org/d/how2debug) and found no solution.

### What did you expect to happen?

When I type a sequence of characters that should be replaced by a ligature (like `->`) I expect the ligature to apear.

### What actually happened?

Ligatures don't show up as expected
![ligatures](https://user-images.githubusercontent.com/77360/119844568-7512be80-bf00-11eb-9081-f5f60309c54a.png)

### Describe your attempts to resolve the issue

Checked the `ligatures` module was enabled (didn't change de config).

### Steps to reproduce

1. Open emacs
2. Ensure `ligatures` module is enabled
3. Open a file in a programming mode
4. Check if ligatures are displayed

### System Information

https://pastebin.com/Xtt5p8tm

**Comment by MithicSpirit** [comment]
Does your font support ligatures? Also what commit of Emacs 28 are you building from (maybe they did something that broke ligatures)?

**Comment by gjm** [comment]
I'm using JetBrains Mono. Ligatures where working just fine until today when I upgraded Doom. I'm using the daily emacs snapshot. Just updated and the issue is still there.

**Comment by hlissner** [comment]
As of 54067455e, our ligatures module is broken. I'm working on a fix.

**Comment by hlissner** [comment]
This was fixed temporarily in 50e71ce76, while I work on merging #5082.
