### ISSUE TITLE
Switching windows with C-x <left> and C-x <right> does not work 

### ISSUE THREAD

**Issue by scovit** [hlissner/doom-emacs#5109]
### 

- [X] I have searched [the FAQ](https://doomemacs.org/docs/faq.org) and [the documentation](https://doomemacs.org/docs/getting_started.org) for solutions.
- [X] I have searched [the issue tracker](https://github.com/hlissner/doom-emacs/issues) for similar issues (the closed issues too).
- [X] I have searched [the Discourse](https://doomemacs.org/d/docs) for any errors and solutions.
- [X] I can reproduce my issue on [the latest commit](https://github.com/hlissner/doom-emacs/commit) of Doom Emacs.
- [X] I have read [How to Debug Issues](https://doomemacs.org/d/how2debug) and found no solution.

### What did you expect to happen?

Premise: I disabled evil and removed the custom keybindings from the config. I am accustomed to vanilla emacs enough that I don't mind about the standard keybindings

I was expecting to be able to switch windows

### What actually happened?

Nothing happens

### Steps to reproduce

1. Remove `+bindings` flag from the bottom of `doom!` block (in ~/.doom.d/init.el).
2. Comment out `(evil +everywhere);` in the same file
3. open two files with emacs
4. `C-x 1`
5. `C-x <left>`

### System Information

https://pastebin.com/eH5dseNd

**Comment by hlissner** [comment]
What do you mean by "switch windows"?

I load up vanilla Emacs and `C-x <left>`/`C-x <right>` are bound to `{next,previous}-buffer`.

In Doom without evil bindings, `C-x <left>`/`C-x <right>` are again bound to `{next,previous}-buffer`.

Seems everything is in order?

**Comment by scovit** [comment]
Hello, you understand very well. They are bound to `{next,previous}-buffer`, rarely they work. Most of the time (particularly just after startup) they don't work. In vanilla Emacs they always work.

**Comment by hlissner** [comment]
The issue was that files opened early weren't associated with the active workspace at startup. As of 84e1554 this should be fixed. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
