### ISSUE TITLE
"q" text object selects parenthesis at first usage 

### ISSUE THREAD

**Issue by otavioschwanck** [hlissner/doom-emacs#5113]
### 

- [X] I have searched [the FAQ](https://doomemacs.org/docs/faq.org) and [the documentation](https://doomemacs.org/docs/getting_started.org) for solutions.
- [X] I have searched [the issue tracker](https://github.com/hlissner/doom-emacs/issues) for similar issues (the closed issues too).
- [X] I have searched [the Discourse](https://doomemacs.org/d/docs) for any errors and solutions.
- [X] I can reproduce my issue on [the latest commit](https://github.com/hlissner/doom-emacs/commit) of Doom Emacs.
- [X] I have read [How to Debug Issues](https://doomemacs.org/d/how2debug) and found no solution.

### What did you expect to happen?

Select always inside quotes.

### What actually happened?

At first usage after open doom, it selects inside parenthesis.

![viq bug](https://user-images.githubusercontent.com/9551316/120096162-3d726500-c100-11eb-8f2a-95612f351adf.gif)

### Steps to reproduce

create a file with SPC b N

add:

```
# Keys = viq



def my_function(first_time_i_use_goes_here)
  "After, always goes here"
end
```

press viq

### System Information

https://pastebin.com/rJJi3ecY

**Comment by hlissner** [comment]
As of bd94250 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
