### ISSUE TITLE
Replace parinfer-mode with parinfer-rust-mode

### ISSUE THREAD

**Issue by e3bc54b2** [hlissner/doom-emacs#5114]
### 

- [X] I have searched [the FAQ](https://doomemacs.org/docs/faq.org) and [the documentation](https://doomemacs.org/docs/getting_started.org) for solutions.
- [X] I have searched [the issue tracker](https://github.com/hlissner/doom-emacs/issues) for similar issues (the closed issues too).
- [X] I have searched [the Discourse](https://doomemacs.org/d/docs) for any errors and solutions.
- [X] I can reproduce my issue on [the latest commit](https://github.com/hlissner/doom-emacs/commit) of Doom Emacs.
- [X] I have read [How to Debug Issues](https://doomemacs.org/d/how2debug) and found no solution.

### What did you expect to happen?

Default `init.el` comes with a flag for module 'parinfer`. Parinfer logic is supposed to help out managing parentheses automatically, by ensuring Lisp code structure remains constant and predictable.

However, default `parinfer` flag uses [parinfer-mode](https://github.com/DogLooksGood/parinfer-mode) which is now deprecated, and during my use, I found it to be highly inconsistent, slow and generally unreliable.

Fortunately, doom already supports a better alternative, already suggested by creator of parinfer-mode : [parinfer-rust-mode](https://github.com/justinbarclay/parinfer-rust-mode) (#4671).

Once I enabled +rust flag, everything works flawlessly and reliably. As such, combined with upstream deprecation, I propose to remove `parinfer-mode` completely, and make `parinfer-rust-mode` to be default without any special flag.

### What actually happened?

Paren operations while using `parinfer-mode` are inconsistent and unreliable.

### Describe your attempts to resolve the issue

Switch to `parinfer-rust-mode`.

### Steps to reproduce

1. Enable `parinfer` module flag in `init.el` (without +rust flag)
2. Type any Lisp program, with parinfer-mode enabled
3. Enter newline between two closing parens while typing the line for first time.

Above can be repeated with `+rust` flag to see intended effect.

### System Information

https://pastebin.com/ryJxxKWN

**Comment by hlissner** [comment]
Duplicate of #4635

**Comment by hlissner** [comment]
My bad, this isn't really a duplicate. That said, I don't mind dropping parinfer. I'll look into it soon.
