### ISSUE TITLE
which-key window flickers (without input) & mouse-wheel scrolling snaps back to origin

### ISSUE THREAD

**Issue by quinquice** [hlissner/doom-emacs#5117]
### 

- [X] I have searched [the FAQ](https://doomemacs.org/docs/faq.org) and [the documentation](https://doomemacs.org/docs/getting_started.org) for solutions.
- [X] I have searched [the issue tracker](https://github.com/hlissner/doom-emacs/issues) for similar issues (the closed issues too).
- [X] I have searched [the Discourse](https://doomemacs.org/d/docs) for any errors and solutions.
- [X] I can reproduce my issue on [the latest commit](https://github.com/hlissner/doom-emacs/commit) of Doom Emacs.
- [X] I have read [How to Debug Issues](https://doomemacs.org/d/how2debug) and found no solution.

### What did you expect to happen?

When a menu opens (for example, by pressing a keybinding prefix such as "SPC h d" and waiting), I expect the menu not to move until I press another key. When I use the mouse wheel to scroll and then stop, I expect the buffer to not change its vertical position.

### What actually happened?

When a menu opens, the menu opens and closes over and over, even while I press no keys. Sometimes it grows and shrinks in vertical height instead. When I scroll inside a buffer then stop, the buffer moves up and down over and over.

Here is a screencast of these two issues
https://user-images.githubusercontent.com/26653946/120134289-c8ed0400-c19b-11eb-8fd4-55f92fd2222f.mp4

### Steps to reproduce

1. Open emacs.
2. Press "SPC h d", then wait.

or

1. Open emacs.
2. Open a large file.
3. Scroll using the scroll wheel, then stop.

### System Information

https://pastebin.com/ELvzFYPS

**Comment by hlissner** [comment]
I cannot reproduce either issue with in vanilla Doom, on NixOS, Arch, macOS, or Ubuntu, on 27.1, 27.2, or 28.0.50 (with or without native-comp). This sounds like a private configuration issue.

You could try profiling the issue. `SPC h T` to start profiling, reproduce the issue, and after ~10 seconds, press `SPC h T` again to produce a report. This should tell you what functions where running during that time.

**Comment by quinquice** [comment]
Not sure what was the actual cause of this, but it now no longer happens after I switched from XMonad to i3 and changed my picom backend.
