### ISSUE TITLE
`format-all-mode` does not effect the formatting on save in any buffer.

### ISSUE THREAD

**Issue by tavurth** [hlissner/doom-emacs#5121]
### 

- [X] I have searched [the FAQ](https://doomemacs.org/docs/faq.org) and [the documentation](https://doomemacs.org/docs/getting_started.org) for solutions.
- [X] I have searched [the issue tracker](https://github.com/hlissner/doom-emacs/issues) for similar issues (the closed issues too).
- [X] I have searched [the Discourse](https://doomemacs.org/d/docs) for any errors and solutions.
- [X] I can reproduce my issue on [the latest commit](https://github.com/hlissner/doom-emacs/commit) of Doom Emacs.
- [X] I have read [How to Debug Issues](https://doomemacs.org/d/how2debug) and found no solution.

### What did you expect to happen?

When I call `(format-all-mode)` I see the text:

```
Format-All mode enabled in current buffer
Format-All mode disabled in current buffer
```

And I expect that the buffer should not be formatted in the `disabled` mode.

### What actually happened?

The buffer is formatted on every save even when `Format-All mode` is set to `disabled`

### Describe your attempts to resolve the issue

I have to disable format-all-mode entirely for the entire buffer type by doing:

```el
;; Disable linting
(setq +format-on-save-enabled-modes '(not emacs-lisp-mode sql-mode tex-mode latex-mode js2x-mode typescript-mode))
```

### Steps to reproduce

1. Add `(format +onsave)` to the `init.el`
2. Open any file (typescript)
3. Call `(format-all-mode)`
4. Format all mode is disabled
5. Save the file
6. The file will still be formatted

### System Information

https://gist.github.com/tavurth/5526cc7326de958f3339bd64a86b6f09

**Comment by hlissner** [comment]
As of 68b422c this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by tavurth** [comment]
Thank you! I will take a look tomorrow to verify it's working!

**Comment by tavurth** [comment]
Yep that seems to have fixed it! Thank you for the fast response :)
