### ISSUE TITLE
Doom doesn't recognize git on remote machine

### ISSUE THREAD

**Issue by tdstoff** [hlissner/doom-emacs#5126]
### 

- [X] I have searched [the FAQ](https://doomemacs.org/docs/faq.org) and [the documentation](https://doomemacs.org/docs/getting_started.org) for solutions.
- [X] I have searched [the issue tracker](https://github.com/hlissner/doom-emacs/issues) for similar issues (the closed issues too).
- [X] I have searched [the Discourse](https://doomemacs.org/d/docs) for any errors and solutions.
- [X] I can reproduce my issue on [the latest commit](https://github.com/hlissner/doom-emacs/commit) of Doom Emacs.
- [X] I have read [How to Debug Issues](https://doomemacs.org/d/how2debug) and found no solution.

### What did you expect to happen?

The _~/.emacs.d/bin/doom_ executable should be able to install Doom into my _.emacs.d/_ folder, but doesn't recognize my installation of git.

### What actually happened?

After connecting to the remote via ssh, I clear out the _~/.emacs.d/_ folder and clone the latest repo:
```
tdst224@login006:~$ rm -rf .emacs.d/
tdst224@login006:~$ git clone --depth 1 https://github.com/hlissner/doom-emacs ~/.emacs.d
Cloning into '/home/tdst224/.emacs.d'...
remote: Enumerating objects: 1057, done.
remote: Counting objects: 100% (1057/1057), done.
remote: Compressing objects: 100% (1010/1010), done.
remote: Total 1057 (delta 21), reused 616 (delta 8), pack-reused 0
Receiving objects: 100% (1057/1057), 963.39 KiB | 4.97 MiB/s, done.
Resolving deltas: 100% (21/21), done.
```
But when I try to install (or run any other doom command) I get the following:
```
tdst224@login006:~$ ~/.emacs.d/bin/doom install
Git isn't present on your system. Cannot proceed.
```

### Describe your attempts to resolve the issue

This remote machine has old versions of both emacs and git installed, and I thus have symlinks which put new versions of it at the top of my path. In my _~/.bashrc_:
```
export PATH=~/bin:$PATH
```
Verification:
```
tdst224@login006:~$ which emacs
~/bin/emacs
tdst224@login006:~$ which git
~/bin/git
```
The versions of these are up to par:
```
tdst224@login006:~$ emacs --version
GNU Emacs 27.1
Copyright (C) 2020 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of GNU Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
tdst224@login006:~$ git --version
git version 2.30.2
```
This git executable works fine at the command line and I even run magit through tramp remotely with success. 

### Steps to reproduce

Presumably (as described above):

1. Connect to a remote machine
2. Link to recent versions of emacs and git in local user files
3. Add those executables to PATH
4. Try to install doom 

### System Information

Since I can't install Doom I'm not sure what information could be provided. Thank you in advance for any help!

**Comment by dymontg** [comment]
I haven't had time to test this on my raspberry pi, but I suspect that the doom binary hasn't sourced your `~/.bashrc`. Can you try running `doom env` before attempting to install doom?

Hope this helps.

**Comment by tdstoff** [comment]
Hi @dymontg, thanks for the response. I see what you're saying, although I'm not sure why Doom doesn't give the error message about my version of git being too old if that's the case, as I have both a new and old version installed. The `doom env` before trying a `doom install` command still gives the same issue unfortunately:
```
tdst224@login006:~$ doom env
Git isn't present on your system. Cannot proceed.
```

**Comment by dymontg** [comment]
I've not been able to reproduce this on my raspberry pi (raspi-os) setup.

Here's what I did:

1. Built git 2.30.2 from source, configuring with `--prefix=/home/pi/git-2.30.2`. Installed using `make install`.
2. Installed emacs 27.2 using snap

I then cloned doom and installed.

```
pi@raspberrypi:~ $ ~/git-2.30.2/git clone --depth 1 https://github.com/hlissner/doom-emacs ~/.emacs.d
Cloning into '/home/pi/.emacs.d'...
remote: Enumerating objects: 1063, done.
remote: Counting objects: 100% (1063/1063), done.
remote: Compressing objects: 100% (1013/1013), done.
remote: Total 1063 (delta 24), reused 646 (delta 11), pack-reused 0
Receiving objects: 100% (1063/1063), 965.47 KiB | 4.69 MiB/s, done.
Resolving deltas: 100% (24/24), done.
pi@raspberrypi:~ $ ~/.emacs.d/bin/doom install
Git isn’t present on your system. Cannot proceed.
pi@raspberrypi:~ $ PATH=~/git-2.30.2/:$PATH
pi@raspberrypi:~ $ ~/.emacs.d/bin/doom install
> Installing straight...
  > Cloning use-package...
> Executing 'doom install' with Emacs 27.2 at 2021-06-10 05:09:14
  Installing Doom Emacs!
  
  > Creating .doom.d/
    ✓ Created .doom.d/
  - Creating .doom.d/init.el
  ✓ Done!
  - Creating .doom.d/config.el
  ✓ Done!
  - Creating .doom.d/packages.el
  ✓ Done!
Generate an envvar file? (see `doom help env` for details) (y or n) y
  > Generating envvars file at "~/.emacs.d/.local/env"
    ✓ Successfully generated "~/.emacs.d/.local/env"
  Installing plugins
  > Installing packages...
```

The doom installation finished without any issues.

If you are still having trouble, try to double check that you have added the directory of the git binary is properly added to the `PATH` variable.

You could also try symlinking the local git binary to a directory like `/usr/bin` and see if that works.
