### ISSUE TITLE
Disable lsp format would cause textDocument/didClose sent unexpected

### ISSUE THREAD

**Issue by zhuhaow** [hlissner/doom-emacs#5133]
### 

- [X] I have searched [the FAQ](https://doomemacs.org/docs/faq.org) and [the documentation](https://doomemacs.org/docs/getting_started.org) for solutions.
- [X] I have searched [the issue tracker](https://github.com/hlissner/doom-emacs/issues) for similar issues (the closed issues too).
- [X] I have searched [the Discourse](https://doomemacs.org/d/docs) for any errors and solutions.
- [X] I can reproduce my issue on [the latest commit](https://github.com/hlissner/doom-emacs/commit) of Doom Emacs.
- [X] I have read [How to Debug Issues](https://doomemacs.org/d/how2debug) and found no solution.

### What did you expect to happen?

I want to use prettier to format typescript code when using lsp at the same time. 

So I set `(setq-hook! 'typescript-mode-hook +format-with-lsp nil)`.

### What actually happened?

 While this does enable `format-all` and disable the lsp formatter, every time the file is saved, the lsp server would get an event of document closed.

```
[Trace - 08:37:54 PM] Sending notification 'textDocument/didClose'.
Params: {
  "textDocument": {
    "uri": "file:///Users/.../src/db/util.ts"
  }
}
```

This causes most of the following requests to fail, complaining something like
```

[Trace - 08:37:54 PM] Received notification 'window/logMessage'.
Params: {
  "message": "[lspserver] Received change on non-opened document file:///Users/.../src/db/util.ts",
  "type": 1
}
```
So the lsp is not usable at all.

### Describe your attempts to resolve the issue

If I remove the line from the config to enable lsp formatter, everything will be good again.

### Steps to reproduce

Enable `(format +onsave)` and lsp, disable lsp format with `(setq-hook! 'typescript-mode-hook +format-with-lsp nil)` or `(setq +format-with-lsp nil)`

### System Information

https://pastebin.com/eEkpE4JL

**Comment by robinbourianes-kalisio** [comment]
I'm facing the same issue with :lang c & python (both with lsp enabled)
I believe this is related to this loop copying original buffer props to the temp one : https://github.com/hlissner/doom-emacs/blob/develop/modules/editor/format/autoload/format.el#L145
Because of this, when the temp buffer is killed, lsp-mode sends a `textDocument/didClose` with the id of the original buffer.
Commenting the above loop fixed my issue (but probably introduced others i guess).
Hope that helps with debugging!

**Comment by robinbourianes-kalisio** [comment]
Well, my issue is not exactly what the title says, but basically everytime `+format-buffer-a` gets called, the file being edited gets kicked out of the lsp server. Which is what happening here too i believe.

**Comment by zhuhaow** [comment]
This seems like the issue. 

When buffer is killed, [lsp would notify the server with the url](https://github.com/emacs-lsp/lsp-mode/blob/f58e8dbbc98505b416bcace6a5450490b9412d5f/lsp-mode.el#L1620-L1625). 

Since all variables are copied, the temp will have the same url as the original buffer.

**Comment by hlissner** [comment]
As of 68b422c this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by zhuhaow** [comment]
Tried `68b422c786`, the issue seems not fixed

**Comment by hlissner** [comment]
> Tried `68b422c786`, the issue seems not fixed

Try making this change to [modules/editor/format/autoload/format.el](https://github.com/hlissner/doom-emacs/blob/develop/modules/editor/format/autoload/format.el#L162):

```diff
modified   modules/editor/format/autoload/format.el
@@ -159,7 +159,8 @@ (defun +format-buffer-a (formatter mode-result)
                            in (cl-remove-if-not #'listp (buffer-local-variables origin-buffer))
                            ;; Making enable-multibyte-characters buffer-local
                            ;; causes an error.
-                           unless (eq var 'enable-multibyte-characters)
+                           unless (eq var enable-multibyte-characters)
+                           unless (string-match-p (symbol-name var) "-\\(hook\\|functions\\)$")
                            ;; Using setq-local would quote var.
                            do (set (make-local-variable var) val))
                   ;; Since we're piping a region of text to the formatter, remove
```

**Comment by zhuhaow** [comment]
That fixed the issue

**Comment by zhuhaow** [comment]
Seems not fixing the issue, let me try a few more times.

**Comment by zhuhaow** [comment]
Do I need to run anything for it to take effect after I change the code from doom-emacs?

**Comment by hlissner** [comment]
Besides restarting Emacs, no.

Try this instead:

```diff
modified   modules/editor/format/autoload/format.el
@@ -148,7 +148,12 @@ (defun +format-buffer-a (formatter mode-result)
             ;; `format-all' (and various formatting functions, like `gofmt') widen
             ;; the buffer, we must copy the region first.
             (let ((output (buffer-substring-no-properties (point-min) (point-max)))
-                  (origin-buffer (or (buffer-base-buffer) (current-buffer))))
+                  (origin-buffer (or (buffer-base-buffer) (current-buffer)))
+                  write-file-functions
+                  before-save-hook
+                  after-save-hook
+                  kill-buffer-query-functions
+                  kill-buffer-hook)
               (with-temp-buffer
                 (with-silent-modifications
                   (insert output)
@@ -156,10 +161,14 @@ (defun +format-buffer-a (formatter mode-result)
                   ;; buffer as possible, in case the formatter is an elisp
                   ;; function, like `gofmt'.
                   (cl-loop for (var . val)
                            in (cl-remove-if-not #'listp (buffer-local-variables origin-buffer))
                            ;; Making enable-multibyte-characters buffer-local
                            ;; causes an error.
                            unless (eq var 'enable-multibyte-characters)
+                           unless (string-match-p (symbol-name var) "-\\(hook\\|functions\\)$")
                            ;; Using setq-local would quote var.
                            do (set (make-local-variable var) val))
                   ;; Since we're piping a region of text to the formatter, remove
```

**Comment by zhuhaow** [comment]
Ok, I found I need to run `doom compile`. 

Changing `unless (eq var 'enable-multibyte-characters)` to `unless (eq var enable-multibyte-characters)` causes an error. 

Adding `unless (string-match-p (symbol-name var) "-\\(hook\\|functions\\)$")` only doesn't fix anything.

**Comment by zhuhaow** [comment]
Confirm it's fixed! 😄

**Comment by hlissner** [comment]
Great! As of 78dde6e this should be fixed. Thanks for your help debugging this!

**Comment by zhuhaow** [comment]
@hlissner Change in https://github.com/hlissner/doom-emacs/commit/78dde6efdd81e4d11a21ba87a7f9b141d274e947#diff-fc9cf5cf94a45598a8d3ba684e02d4a10aa8b28630d821622b817995133f9643L162 would cause an error `Error (before-save-hook): Error running hook "format-all-buffer--from-hook" because: (setting-constant enable-multibyte-characters)`

**Comment by hlissner** [comment]
> @hlissner Change in [78dde6e#diff-fc9cf5cf94a45598a8d3ba684e02d4a10aa8b28630d821622b817995133f9643L162](https://github.com/hlissner/doom-emacs/commit/78dde6efdd81e4d11a21ba87a7f9b141d274e947#diff-fc9cf5cf94a45598a8d3ba684e02d4a10aa8b28630d821622b817995133f9643L162) would cause an error `Error (before-save-hook): Error running hook "format-all-buffer--from-hook" because: (setting-constant enable-multibyte-characters)`

Ack! My bad. It is fixed in 9fb96f9. Thanks for letting me know!

**Comment by zhuhaow** [comment]
Thank you for the quick fix!

**Comment by robinbourianes-kalisio** [comment]
With https://github.com/hlissner/doom-emacs/commit/9fb96f9eeb4ff8747c84a653404d1f7f8d5b5cf2, I have to `(setq-hook! 'c-mode-hook +format-with-lsp nil)` to get format on save working. I'm using eglot as lsp server for that matter. I'll do a quick check with lsp-mode.

Thanks for four work by the way :+1:

**Comment by robinbourianes-kalisio** [comment]
Doesn't work either with lsp-mode. No error, just no formatting on save. Manually calling `lsp-format-buffer` or `eglot-format-buffer` do format the buffer though.

**Comment by jeffutter** [comment]
After these changes formatting with LSP is also broken for me. I'm using elixir +lsp and now when I save I see in my Messages buffer "Reformatted with mix format" which is incorrect. `mix format` is sort of broken and reformats my entire file incorrectly, while lsp format works great.
