### ISSUE TITLE
"doom sync" failing when ":editor format" module enabled.

### ISSUE THREAD

**Issue by mmarshall540** [hlissner/doom-emacs#5136]
### 

- [X] I have searched [the FAQ](https://doomemacs.org/docs/faq.org) and [the documentation](https://doomemacs.org/docs/getting_started.org) for solutions.
- [X] I have searched [the issue tracker](https://github.com/hlissner/doom-emacs/issues) for similar issues (the closed issues too).
- [X] I have searched [the Discourse](https://doomemacs.org/d/docs) for any errors and solutions.
- [X] I can reproduce my issue on [the latest commit](https://github.com/hlissner/doom-emacs/commit) of Doom Emacs.
- [X] I have read [How to Debug Issues](https://doomemacs.org/d/how2debug) and found no solution.

### What did you expect to happen?

A successful `doom sync` on the command line with `:editor format` enabled in private init.el file.

### What actually happened?

Sync fails on cli with following message. Extended backtrace [copied to pastebin](https://pastebin.com/9Vcndqd8).

```
> Executing 'doom sync' 2021-06-04 13:30:31
  > Synchronizing your config with Doom Emacs...
    > Regenerating envvars file at "~/.config/doom-emacs/.local/env"
      ✓ Successfully generated "~/.config/doom-emacs/.local/env"
    > Installing packages...
      > Updating recipe repos...
      > Cloning emacs-format-all-the-code (for format-all)...
        Warning (straight): Could not reset to commit "47d862d40a" in repository "emacs-format-all-the-code"
        Warning (straight): Could not check out branch "master" of repository "emacs-format-all-the-code"
      x The package manager threw an error
      x Last 25 lines of straight's error log:
        $ git branch -r
        [Return code: 0]
        $ cd /home/mmarshall540/.config/doom-emacs/.local/straight/repos/emacs-format-all-the-code/
        $ git remote show origin
        * remote origin
          Fetch URL: https://github.com/lassik/emacs-format-all-the-code.git
          Push  URL: https://github.com/lassik/emacs-format-all-the-code.git
          HEAD branch: master
          Remote branch:
            master new (next fetch will store in remotes/origin)
        [Return code: 0]
        $ cd /home/mmarshall540/.config/doom-emacs/.local/straight/repos/emacs-format-all-the-code/
        $ git reset --hard 47d862d40a
        fatal: ambiguous argument '47d862d40a': unknown revision or path not in the working tree.
        Use '--' to separate paths from revisions, like this:
        'git <command> [<revision>...] -- [<file>...]'
        [Return code: 128]
        $ cd /home/mmarshall540/.config/doom-emacs/.local/straight/repos/emacs-format-all-the-code/
        $ git checkout -B master origin/master
        fatal: 'origin/master' is not a commit and a branch 'master' cannot be created from it
        [Return code: 128]
        $ cd /home/mmarshall540/.config/doom-emacs/.local/straight/repos/emacs-format-all-the-code/
        $ git checkout HEAD
        error: pathspec 'HEAD' did not match any file(s) known to git
        [Return code: 1]
      ! Extended backtrace logged to ~/.config/doom-emacs/.local/doom.error.log
```

### Describe your attempts to resolve the issue

This was during a reinstall to troubleshoot a different issue, which I believe to be related to my config.

After first experiencing this error on a `doom install`, I moved my private config out of the way so the install command could use Doom's default config.

Installation was then successful.

However, after enabling only the `:editor format` module in the newly-installed private init.el file, `doom sync`  fails with the same error.

### Steps to reproduce

1. Enable ":editor format" module in private init.el file.
2. Run "doom sync" on command line.

### System Information

https://pastebin.com/U9P7tG1k

**Comment by hlissner** [comment]
As of 027dec3 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by mmarshall540** [comment]
You're amazing! Works great now. Thanks!
