### ISSUE TITLE
doom-emacs can not recognize remaped left alt as emta on macOS with an USB-HID keyboard

### ISSUE THREAD

**Issue by hy-zhao** [hlissner/doom-emacs#5143]
### 

- [X] I have searched [the FAQ](https://doomemacs.org/docs/faq.org) and [the documentation](https://doomemacs.org/docs/getting_started.org) for solutions.
- [X] I have searched [the issue tracker](https://github.com/hlissner/doom-emacs/issues) for similar issues (the closed issues too).
- [X] I have searched [the Discourse](https://doomemacs.org/d/docs) for any errors and solutions.
- [X] I can reproduce my issue on [the latest commit](https://github.com/hlissner/doom-emacs/commit) of Doom Emacs.
- [X] I have read [How to Debug Issues](https://doomemacs.org/d/how2debug) and found no solution.

### What did you expect to happen?

Hi,

When using USB keyboard on mac, I remapped alt key as command and vice versa. I hope the left alt key function as meta when running Emacs.app.

### What actually happened?

when i run Emacs.app, the left-alt(after remap) key does not behave as meta(right-alt do), also left-command(after remap) function as `s'.

### Describe your attempts to resolve the issue

I tried disable doom-emacs configuration, which runs well both on Emacs.app and terminal. I also tried enable doom-configuration under terminal emacs, which behaves well too. So, the only problems is when running Emacs.app with doom-emacs.

### Steps to reproduce

1. open settings -> key borad -> Modifier Keys -> select keyboard as: USB-HID Keyboard -> choose option key as command, command key as option.
2. run Emacs.app with doom-emacs configuration, press M-x

### System Information

https://pastebin.com/JVFftVRx

**Comment by hlissner** [comment]
This is not a bug. Reconfigure [these variables however you'd like](https://github.com/hlissner/doom-emacs/blob/develop/core/core-keybinds.el#L33-L39) your modifier keys to behave.

**Comment by hy-zhao** [comment]
Thanks a lot! The best solution so far i got is add the below into .doom.d/config.el.

In this way, the left remapped option could work as meta now, right one behaves as modifier for symbols. But the left and right command still behave as meta only when i press Cmd+x. I can not find a perfect solution to make Cmd work exactly as itself.

(setq mac-command-modifier      'none
      ns-command-modifier       'super
      mac-option-modifier       'none
      ns-option-modifier        'none
      ;; Free up the riht option for character composition
      mac-right-command-modifier 'none
      ns-right-command-modifier 'super
      mac-right-option-modifier 'meta
      ns-right-option-modifier  'meta )
