### ISSUE TITLE
Writing python function adds a colon after closing parenthesis

### ISSUE THREAD

**Issue by quaziashfaq** [hlissner/doom-emacs#5151]
### 

- [X] I have searched [the FAQ](https://doomemacs.org/docs/faq.org) and [the documentation](https://doomemacs.org/docs/getting_started.org) for solutions.
- [X] I have searched [the issue tracker](https://github.com/hlissner/doom-emacs/issues) for similar issues (the closed issues too).
- [X] I have searched [the Discourse](https://doomemacs.org/d/docs) for any errors and solutions.
- [X] I can reproduce my issue on [the latest commit](https://github.com/hlissner/doom-emacs/commit) of Doom Emacs.
- [X] I have read [How to Debug Issues](https://doomemacs.org/d/how2debug) and found no solution.

### What did you expect to happen?

Writing a function definition
`def func_name(`
Then Emacs is adding `):`
Then typing `):` should just take my cursor after `:`

### What actually happened?

Get an additional `:`
`def func_name()::`
The cursor stays between 2 colons.

### Steps to reproduce

1. Open an empty python file in Emacs
2. Write `def func_name():`
3. You will get `def_func_name()::`

### System Information

https://pastebin.com/Maw3CSXa

**Comment by betaprior** [comment]
Confirming. This did not happen with an older version of doom.

**Comment by zahin-muhaimeen** [comment]
I am not sure if this is of much help, but this behaviour is being caused by ```smartparens-mode``` which is handling the auto parentheses. I was also bugged by this "feature", so I decided to swap it out with ```electric-pair-mode```. This is an auto pair minor mode that doesn't include the bug and in my opinion is much better. It is also a package that comes built-in to Emacs in versions above Emacs 24 (correct me if I am wrong). To replicate what I have done, put this in your ```config.el```:

```
(remove-hook 'doom-first-buffer-hook #'smartparens-global-mode)
(electric-pair-mode 1)
```

**Comment by quaziashfaq** [comment]
Thank you so much for your help. Your suggestion is working fine.
By the way, are you really 12-year old now? :-)

**Comment by zahin-muhaimeen** [comment]
> Thank you so much for your help. Your suggestion is working fine.
> By the way, are you really 12-year old now? :-)

Yeah I actually am, well turning 13 in like 2 months.
