### ISSUE TITLE
all-the-icons font not displaying 

### ISSUE THREAD

**Issue by joaquinlpereyra** [hlissner/doom-emacs#5156]
### 

- [X] I have searched [the FAQ](https://doomemacs.org/docs/faq.org) and [the documentation](https://doomemacs.org/docs/getting_started.org) for solutions.
- [X] I have searched [the issue tracker](https://github.com/hlissner/doom-emacs/issues) for similar issues (the closed issues too).
- [X] I have searched [the Discourse](https://doomemacs.org/d/docs) for any errors and solutions.
- [X] I can reproduce my issue on [the latest commit](https://github.com/hlissner/doom-emacs/commit) of Doom Emacs.
- [X] I have read [How to Debug Issues](https://doomemacs.org/d/how2debug) and found no solution.

### What did you expect to happen?

When I install and run emacs from scratch installing the all-the-icons font's I should see a nice, clean Emacs. 

### What actually happened?
![image](https://user-images.githubusercontent.com/3151940/121253958-19d9b800-c880-11eb-830c-224f73ad98bf.png)

Instead, I see:

It is worth nothing that when I do `M-x counsel-fonts` several fonts appear corrupted.
 
![image](https://user-images.githubusercontent.com/3151940/121254006-2b22c480-c880-11eb-92e0-895221d0a3dc.png)

The problem was triggered after doing `doom update`, which failed because of #4984. I updated my system just before though so I'm not sure if that could not cause the issue, I did search in the `apt` logs and emacs was not updated. 

### Describe your attempts to resolve the issue

I have seen #724, and:

* The fonts are listed in fc-list
* The fonts in `~/.local/share/fonts` are **not** 0Kb in size.
* I have tried downloading them manually anyway to no avail
* I have done `doom sync`. 
* I have even completely reinstalled emacs.

### Steps to reproduce

1. Open emacs
2. Watch

### System Information

https://pastebin.com/LN8DmTpZ

**Comment by joaquinlpereyra** [comment]
Well, that magically worked. `$ sudo apt install fonts-noto-color-emoji` did the trick.

Another thing I noticed: this issues somehow managed to slow down emacs to the point where it was unusable, so it is not only aesthetic. 

Thanks for your help @someguynamedmatt !

**Comment by someguynamedmatt** [comment]
@joaquinlpereyra yeah, mine slowed down to a grinding halt too. Glad that worked!
