### ISSUE TITLE
Default emacs key bindings!!!!!!

### ISSUE THREAD

**Issue by x61** [hlissner/doom-emacs#516]
I am trying to check my current agenda files with `C-c a` but this produced an error (says `C-c a is undefined`). Where are the default emacs/org-mode keys re-mapped/defined? 

Also, if I want to define/include my personal emacs settings, where should I put them?

**Comment by bitwalker** [comment]
I can answer the latter for you, at least if you are using `develop`:

1. Create either `~/.config/doom` or `~/.doom.d`, choose the former if you have `XDG_CONFIG_HOME` set to `~/.config` (which I'd recommend you do anyway). I'll refer to this as `$DOOM_DIR` from here on out.
2. In the folder you just created, copy `init.example.el` from the root of the `doom-emacs` directory to `$DOOM_DIR/init.el`, and edit it to your liking to enable the features/languages/etc. that you want.
3. Put your personal config settings in either `$DOOM_DIR/config.el`, `$DOOM_DIR/init.el`, depending on when you need them to take effect, I'd only put things which use `def-package!`, `def-package-hook!` in `$DOOM_DIR/init.el` though, and put everything else in `$DOOM_DIR/config.el`
4. For packages you want to install beyond what is in the doom distribution, create` $DOOM_DIR/packages.el` and use the `package!` macro to specify what (and if necessary, how) packages to install
5. For private modules you may want to define or already have, create `$DOOM_DIR/modules/private/<module_dir>` for each module, and use the `config.el`, `init.el`, `packages.el` trio the same way you do for your standard config.

As far as how to use the different mechanisms that doom provides, such as `map!`, `after!`, `def-package!`, etc., I would take the time to read the doom source code, as I found it really helpful to understand how things worked. Last I checked, it seemed documentation was a bit out of sync with what is in develop, so you may run into problems if you don't spend the time to look into how things are being done. You could also check out other doom users setups, such as [fuxialexander](https://github.com/fuxialexander/doom-emacs-private-xfu), to get a sense for what goes where and how to use various features.

The doom bindings for org-mode are defined in `~/.emacs.d/modules/lang/org/config.el` as far as I can tell.

**Comment by hlissner** [comment]
Are you sure `C-c a` is a default keybind? I do not see this keybind in org's source files and I have not unbound any default org keybinds. What command do you expect `C-c a` to invoke?

As @bitwalker mentioned, you'll find all of Doom's org-mode keybinds [in lang/org/config.el, here](https://github.com/hlissner/doom-emacs/blob/develop/modules/lang/org/config.el#L227-L297).

**Comment by JingYenLoh** [comment]
`C-c a` is not a default binding, but rather the recommended binding by the official org documentation: https://orgmode.org/manual/Activation.html#Activation

**Comment by x61** [comment]
Thanks @bitwalker  for the detailed instruction. 
@JingYenLoh `C-c a` is not the default keybinding. Thanks
