### ISSUE TITLE
Win 10 unable to load Doom emacs.

### ISSUE THREAD

**Issue by firebone-be** [hlissner/doom-emacs#5168]
### 

- [X] I have searched [the FAQ](https://doomemacs.org/docs/faq.org) and [the documentation](https://doomemacs.org/docs/getting_started.org) for solutions.
- [X] I have searched [the issue tracker](https://github.com/hlissner/doom-emacs/issues) for similar issues (the closed issues too).
- [X] I have searched [the Discourse](https://doomemacs.org/d/docs) for any errors and solutions.
- [X] I can reproduce my issue on [the latest commit](https://github.com/hlissner/doom-emacs/commit) of Doom Emacs.
- [X] I have read [How to Debug Issues](https://doomemacs.org/d/how2debug) and found no solution.

### What did you expect to happen?

I expected Doom Emacs to start.

### What actually happened?

I upgraded Emacs trough chocolatey to the latest version of Emacs at this time (27.2)
Ran .\doom build
Ran .\doom sync
Ran .\doom upgrade and ran into some issues that resulted in some additional git commands.
Fixed the upgrade issues and no every command runs without errors.
Except when I try to load up Doom Emacs, then I get following 3 errors:

> Error (+doom-dashboard-functions): Error running hook "doom-dashboard-widget-shortmenu" because: (void-variable persp-auto-save-fname)
> Error (doom-init-ui-hook): Error running hook "+doom-dashboard-init-h" because: (doom-hook-error +doom-dashboard-functions doom-dashboard-widget-shortmenu (void-variable persp-auto-save-fname)
> Error (doom-first-input-hook): Error running hook "evil-goggles-mode" because: (file-missing Searching for program No such file or directory hunspell)

### Describe your attempts to resolve the issue

Tried reinstalling, syncing, rebuilding, blank config files...

### Steps to reproduce

Doom info via pastebin.

### System Information

https://pastebin.com/6RiCjFjY

**Comment by hlissner** [comment]
These look like local issues.

> ` (void-variable persp-auto-save-fname)`

This implies the `persp-mode` package didn't install correctly. Delete it manually in `~/.emacs.d/.local/straight/repos/persp-mode`, run `~/.emacs.d/bin/doom sync` on the command line and restart Emacs. If that doesn't work, delete `~/.emacs.d/.local` and `doom sync` again.

> `file-missing Searching for program No such file or directory hunspell`

Looks like you don't have hunspell installed and in your `PATH`. Install it.

-----

As this is not a Doom issue I will close this, but feel free to follow up here. Though it would be better if you pursued help on our Discord, as our issue tracker is not for support.
