### ISSUE TITLE
Underline of link in orgmode is far away from text if I set line-spacing

### ISSUE THREAD

**Issue by quarkquartet** [hlissner/doom-emacs#5169]
### 

- [X] I have searched [the FAQ](https://doomemacs.org/docs/faq.org) and [the documentation](https://doomemacs.org/docs/getting_started.org) for solutions.
- [X] I have searched [the issue tracker](https://github.com/hlissner/doom-emacs/issues) for similar issues (the closed issues too).
- [X] I have searched [the Discourse](https://doomemacs.org/d/docs) for any errors and solutions.
- [X] I can reproduce my issue on [the latest commit](https://github.com/hlissner/doom-emacs/commit) of Doom Emacs.
- [X] I have read [How to Debug Issues](https://doomemacs.org/d/how2debug) and found no solution.

### What did you expect to happen?

I set line spacing in org mode via:
```emacs-lisp
(add-hook! 'org-mode-hook
(setq-local line-spacing 0.45))
```
It should change the line spacing, while it does no change anything else.

### What actually happened?

<img width="803" alt="image" src="https://user-images.githubusercontent.com/26316540/121741746-ee97d880-cacc-11eb-9c34-cbd58789a510.png">
As shown in the figure, the underline of the link is far away from the text. This is strange.

### Describe your attempts to resolve the issue

I first tried whether this is the default behavior of emacs. I did
```
emacs -Q --eval '(progn
                   (switch-to-buffer "*.org")
                   (org-mode)
                   (setq-local line-spacing 0.45)
                   (insert "[[link]]"))'

```
The result is 
![image](https://user-images.githubusercontent.com/26316540/121741844-0cfdd400-cacd-11eb-84ff-8e636bcbc6a0.png)
This is exactly what I expected: the underline is close to the text and the upper end of cursor is at the same height of the text. The line spacing is larger, and the lower end of the cursor is extended. So the default behavior of emacs should be correct. The problem must comes from some configurations.

Then I tried to delete all my personal doom config and `.emacs.d`. I tried to use the default setting of doom, with only the line spacing as my personal config. But the result is the same.

### Steps to reproduce

Simply add the line spacing config into `.doom.d/config.el` and you will see it.

### System Information

https://pastebin.com/TZxdinGQ

**Comment by quarkquartet** [comment]
Update:
I tried:
```emacs-lisp
(add-hook 'org-mode-hook
          (lambda ()
            (kill-local-variable 'line-spacing) 
            (setq-local default-text-properties
                        '(line-spacing 0.25    
                          line-height 1.45      
                          ))))
```
Still the same result.

**Comment by hlissner** [comment]
As of 57026c4 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by quarkquartet** [comment]
> As of [57026c4](https://github.com/hlissner/doom-emacs/commit/57026c4b70b043ad5418724ea3e45b0d4087d6a3) this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

Yes, it is solved. Thanks!
