### ISSUE TITLE
LaTeX Syntax-highlighting / preview not working

### ISSUE THREAD

**Issue by emwal** [hlissner/doom-emacs#5177]
### 

- [X] I have searched [the FAQ](https://doomemacs.org/docs/faq.org) and [the documentation](https://doomemacs.org/docs/getting_started.org) for solutions.
- [X] I have searched [the issue tracker](https://github.com/hlissner/doom-emacs/issues) for similar issues (the closed issues too).
- [X] I have searched [the Discourse](https://doomemacs.org/d/docs) for any errors and solutions.
- [X] I can reproduce my issue on [the latest commit](https://github.com/hlissner/doom-emacs/commit) of Doom Emacs.
- [X] I have read [How to Debug Issues](https://doomemacs.org/d/how2debug) and found no solution.

### What did you expect to happen?

When I open a latex document, it should be syntax-highlighted/latex-preview should work.

### What actually happened?

As you can see in Doom-Emacs (top) only brackets are highlighted, whereas in the unmodified emacs (/usr/bin/emacs -q; bottom) the syntax is properly highlighted.

![screenshot_doom and regular emacs latex](https://user-images.githubusercontent.com/38177330/121877055-80405980-cd0a-11eb-9a10-5f91b066fc36.png)

### Describe your attempts to resolve the issue

I reviewed my config and couldn't find any interference with auctex.
Otherwise I searched similar issues here and on stackexchange.

Only #3821 is remotely connected. 

### Steps to reproduce

1. Open .tex file
2. Be disoriented by non-highlighted syntax.

### System Information

https://pastebin.com/Tr8yEDpN

**Comment by ymarco** [comment]
Does anything come up in the `* messages` buffer? If so, can you [produce a backtrace](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#how-to-extract-a-backtrace-from-an-error)? Does it work in the [sandbox](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#testing-in-dooms-sandbox)?

**Comment by emwal** [comment]
Okay – I tried the varying levels in the sandbox (a feature I didn't know about - thanks!).
It does seem to be an issue with my config – at least it still works in fully loaded doom without my config.

In the *messages buffer comes up nothing.

Thank you!
So I guess I'll have to check my config once again.

This can be closed then!

**Comment by emwal** [comment]
For future generations:
Don't set `font-lock-maximum-decoration` to `nil` – it defaults to a really basic level of font-locking (level 1, see [emacs manual](https://www.gnu.org/software/emacs/manual/html_node/elisp/Levels-of-Font-Lock.html)).
Strangely this didn't interfere with orgmode and only appeared in LaTeX buffers – I wonder why.
