### ISSUE TITLE
Couldn't resolve parser "solidity-parse"

### ISSUE THREAD

**Issue by Jeiwan** [hlissner/doom-emacs#5178]
### 

- [X] I have searched [the FAQ](https://doomemacs.org/docs/faq.org) and [the documentation](https://doomemacs.org/docs/getting_started.org) for solutions.
- [X] I have searched [the issue tracker](https://github.com/hlissner/doom-emacs/issues) for similar issues (the closed issues too).
- [X] I have searched [the Discourse](https://doomemacs.org/d/docs) for any errors and solutions.
- [X] I can reproduce my issue on [the latest commit](https://github.com/hlissner/doom-emacs/commit) of Doom Emacs.
- [X] I have read [How to Debug Issues](https://doomemacs.org/d/how2debug) and found no solution.

### What did you expect to happen?

Solidity code formatting works.

### What actually happened?

When running `M-x +format/buffer` (or enabling the on-save flag) I'm getting an error:
```
[error] Couldn't resolve parser "solidity-parse"
```

### Describe your attempts to resolve the issue

1. Installed `solidity-parse` with `npm install -g solidity-parse` but couldn't find it anywhere in the repo or `solidity-mode` or the other Solidity packages.
1. `which solidity-parse` returns `/usr/local/bin/solidity-parse`.
1. I have `prettier` and `prettier-plugin-solidity` installed globally.
1. `doom env` didn't help. The file it produces contains the path.
1. `doom doctor` doesn't find any issues related to Solidity. 
1. When running `M-x getenv PATH` I see `/usr/local/bin/` among other paths.
1. When running `M-x doom/reload-env` I see:
> zsh:1: command not found: getent -ic '"/Users/jeiwan/.emacs.d/bin/doom" env'
zsh:1: command not found: zsh:1:

### Steps to reproduce

1. Open Doom Emacs
2. Enable formatting `(format +onsave)`
3. Open any Solidity file
4. Save changes or run `M-x +format/buffer`

### System Information

https://pastebin.com/D30hyQ2F

**Comment by Jeiwan** [comment]
Fixed, not an issue with Doom.

So, I had `prettier` installed in a local `node_modules` (in my project directory) but the plugin was installed globally. Since Node has stopped resolving at the local `node_modules` and didn't check the global one, it couldn't find the plugin.

Also, no need to install `solidity-parse` binary. The error message means a Prettier parser plugin named "solidity-parse" isn't found.

**Comment by alxiong** [comment]
@Jeiwan Hi Ivan, I run into the same error. Not sure how you resolve it, I also installed my `prettier` npm package globally, and I confirmed that my doom env has included the correct versioned node_modules in nvm. 

```
┌─  ~ on master [!?]
└─○ which prettier
/Users/alex/.config/nvm/versions/node/v14.15.4/bin/prettier

┌─  ~ on master [!?]
└─○ rg 'nvm/versions/node/v14.15.4/' ./.emacs.d/.local/env
19: "NVM_BIN=/Users/alex/.config/nvm/versions/node/v14.15.4/bin"
41: "PATH=.../:/Users/alex/.config/nvm/versions/node/v14.15.4/bin:/opt/homebrew/bin:/..."
61: "NVM_INC=/Users/alex/.config/nvm/versions/node/v14.15.4/include/node"
```

**Comment by Jeiwan** [comment]
@alxiong 
You need to install `prettier-plugin-solidity` either locally or globally, depending on your setup. In every Solidity project I do this:
> yarn add -D prettier prettier-plugin-solidity
