### ISSUE TITLE
`d %` leaves one character.

### ISSUE THREAD

**Issue by scturtle** [hlissner/doom-emacs#519]
System: archlinux, emacs 25.3, doom-emacs latest develop branch, latest packages.

`d %` on the first `(` of:
```
(defun foo ()
  )
```
leaves the matching `)`:
```
)
```
Same problem on macos and emacs HEAD. Disabling evil-matchit fixes that.
Probably this is an upstream problem but makes `d %` unusable.

**Comment by hlissner** [comment]
I don't want to disable evil-matchit, beacuse it allows `%` to jump between start/end keywords (like `if` and `end` in ruby, or `function` and `endfunction` in lua) as well as parentheses.

I have a couple ideas for a fix and will address this soon.

**Comment by hlissner** [comment]
Just pushed a fix that should have addressed your issue. Let me know if that isn't the case!

**Comment by scturtle** [comment]
Almost fixed. Only the first time behavior after started emacs is buggy.
