### ISSUE TITLE
centaur-tabs-mode messes with popup buffers even when disabled

### ISSUE THREAD

**Issue by lochlainn** [hlissner/doom-emacs#5196]
### What did you expect to happen?

When I disable tabs by toggling centaur-tabs-mode, I expect to be able to use emacs normally.

### What actually happened?

After disabling the mode, running for example `SPC h v my-var` won't allow help to pop up, and I instead get the following error in `warnings`:
```
Error (+popup-buffer-mode-hook): Error running hook "centaur-tabs-local-mode" because: (error Centaur-Tabs mode must be enabled)
```

### Describe your attempts to resolve the issue

My thoughts were to do something like this:

```
;;; ui/tabs/config.el -*- lexical-binding: t; -*-
  :config
...
  - (add-hook '+doom-dashboard-mode-hook #'centaur-tabs-local-mode)
  + (add-hook '+doom-dashboard-mode-hook #'(if centaur-tabs-mode-on-p (centaur-tabs-local-mode))
...
```

I'm not on emacs right now so that call to add-hook might be wrong, but basically check centaur-tabs-mode-on-p external to its own check, which seems to interrupt the buffer being created.

### Steps to reproduce

1. Install tabs
2. Disable tabs for your current session by calling centaur-tabs-mode
3. Try to run something, like variable help, that calls up a hook that centaur is on:
  a. +doom-dashboard-mode-hook
  b. +popup-buffer-mode-hook
4. Observe the warning printed, and the lack of a help buffer being created.

### System Information

https://pastebin.com/K5A9Mf0z

**Comment by hlissner** [comment]
Sorry for the tremendously late response. This issue should now be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
