### ISSUE TITLE
Add a WSL Environment Variable to doom-env-blacklist

### ISSUE THREAD

**Issue by mbenecke** [hlissner/doom-emacs#5198]
I would suggest this tiny change:

```@@ -59,7 +59,7 @@ Why this over exec-path-from-shell?
 (defvar doom-env-blacklist
   '(;; State that may be problematic if overwritten
     "^HOME$" "^\\(OLD\\)?PWD$" "^SHLVL$" "^PS1$" "^R?PROMPT$" "^TERM\\(CAP\\)?$"
-    "^USER$"
+    "^USER$" "^WSL_INTEROP$"
     ;; X server or services' variables
     "^DISPLAY$" "^DBUS_SESSION_BUS_ADDRESS$" "^XAUTHORITY$"
     ;; ssh and gpg variables (likely to become stale)
```
### Issue
1. Install an WSL2 Distribution of your choice
2. Install doom-emacs
3. run `doom install` and generate the _~/.emacs.d/core/cli/env.el_
4. use this snippet and execute a `[[https://github.com]]` link
```
browse-url-generic-program  "/mnt/c/Windows/System32/cmd.exe"
browse-url-generic-args     '("/c" "start")
browse-url-browser-function #'browse-url-generic))
```
5. you will get some error message like `<3>init: (632) ERROR: UtilConnectUnix:466: connect failed 111`
to detect the reason i run `# strace powershell.exe start .` in a vterm:
```
    SOCK_SEQPACKET|SOCK_CLOEXEC, 0) = 5 connect(5, {sa_family=AF_UNIX,
sun_path="/run/WSL/499_interop"}, 110) = -1 ENOENT (Datei oder Verzeichnis nicht
gefunden) getpid()                                = 3374 writev(2,
[{iov_base="<3>init: (3374) ERROR: UtilConne"..., iov_len=61}, {iov_base=NULL,
iov_len=0}], 2<3>init: (3374) ERROR: UtilConnectUnix:467: connect failed 2 ) =
61 close(5)                                = 0 close(4)
= 0 ioctl(3, SNDCTL_TMR_START or TCSETS, {B38400 opost isig icanon echo ...}) =
0
```
### Solution
Everytime you start a new Terminal in WSL2, it sets the environment variable `WSL_INTEROP` which contains the path to a new socket in `/run/WSL/\d+_interop`, so you have to run `doom env` again and again to refresh the value

After adding the `"^WSL_INTEROP$"` to  _~/.emacs.d/core/cli/env.el_ I am able to execute Windows applications from _vterm_ oder open a URL from my org-files.

**Comment by hlissner** [comment]
Makes sense to me. As of 8ad846e WSL_INTEROP is in our blacklist. Thanks for bringing it to my attention!
