### ISSUE TITLE
Format on save broken when using LSP formatter

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [hlissner/doom-emacs#5204]
### 

- [X] I have searched [the FAQ](https://doomemacs.org/docs/faq.org) and [the documentation](https://doomemacs.org/docs/getting_started.org) for solutions.
- [X] I have searched [the issue tracker](https://github.com/hlissner/doom-emacs/issues) for similar issues (the closed issues too).
- [X] I have searched [the Discourse](https://doomemacs.org/d/docs) for any errors and solutions.
- [X] I can reproduce my issue on [the latest commit](https://github.com/hlissner/doom-emacs/commit) of Doom Emacs.
- [X] I have read [How to Debug Issues](https://doomemacs.org/d/how2debug) and found no solution.

### What did you expect to happen?

With `(format +onsave)` and `(cc +lsp)` in my `init.el`, I expect my c++ buffers to be formatted (using `clangd` LSP) each time I save the file.

(Note: I'm on emacs 28.0.50.)

### What actually happened?

The buffer is not formatted.

### Describe your attempts to resolve the issue

Autoformatting works fine when not using LSP mode: after calling `lsp-disconnect` saving the file formats it.
Independent of whether LSP mode is on or off, `lsp-format-buffer` and `+format/buffer` format the buffer just fine.

I've fixed it for now by setting
```
(setq +format-with-lsp nil)
```
as indicated in https://github.com/hlissner/doom-emacs/issues/1652, but this seems like a slightly ugly workaround that shouldn't be necessary. (Note that I don't actually care much whether the LSP formatter or the default `clang-format` is called - I suppose they should have the same result anyway.)

Looking at the `stderr` of the `clangd` process, I can see that `lsp-format-buffer` sends a request for formatting:
```
I[18:34:52.873] <-- textDocument/formatting(53)
I[18:34:52.874] --> reply:textDocument/formatting(53) 0 ms
```
Saving the buffer doesn't send this request.

### Steps to reproduce

1. Have `(format +onsave)` and `(cc +lsp)` in `init.el`.
2. Create a new C++ file containing e.g.
```
{



}
```
3. Save the file.
4. Expected: the file now contains `{}`
5. Actual: nothing changed
6. After toggling the value of `+format-with-lsp` from `t` to `nil` and saving again, the file now contains `{}`. (Note that it may be necessary to first add another empty line to modify the buffer - saving an already saved file won't format the buffer.)

### System Information

https://pastebin.com/kyVWNQrf

**Comment by RBckmnn** [comment]
I think this is a duplicate of https://github.com/hlissner/doom-emacs/issues/5128

**Comment by RagnarGrootKoerkamp** [comment]
Ah yes, that does look the same indeed - so much for my issue searching.
