### ISSUE TITLE
Dashboard does not display font/icon

### ISSUE THREAD

**Issue by Kangaxx-0** [hlissner/doom-emacs#5206]
### 

- [X] I have searched [the FAQ](https://doomemacs.org/docs/faq.org) and [the documentation](https://doomemacs.org/docs/getting_started.org) for solutions.
- [X] I have searched [the issue tracker](https://github.com/hlissner/doom-emacs/issues) for similar issues (the closed issues too).
- [X] I have searched [the Discourse](https://doomemacs.org/d/docs) for any errors and solutions.
- [X] I can reproduce my issue on [the latest commit](https://github.com/hlissner/doom-emacs/commit) of Doom Emacs.
- [X] I have read [How to Debug Issues](https://doomemacs.org/d/how2debug) and found no solution.

### What did you expect to happen?

When I open Emacs, I should see all icons display correctly. When I open up file explorer the icons should also display correctly 

### What actually happened?

I installed Doom Emcas today, however, it appears all icons not loading, so does file explorer both for treemacs and neotree. Attaching screenshots as below

![image](https://user-images.githubusercontent.com/85712372/123356214-20249100-d51c-11eb-9e02-d09dcd538328.png)

![image](https://user-images.githubusercontent.com/85712372/123356190-100cb180-d51c-11eb-952f-a5ab99e17e69.png)

### Describe your attempts to resolve the issue

Tried below solutions, they do not work for my case:

- https://github.com/hlissner/doom-emacs/pull/4883
- https://github.com/hlissner/doom-emacs/issues/5156
- https://github.com/hlissner/doom-emacs/blob/develop/docs/faq.org#strange-or-incorrect-icons-are-displayed-everywhere

### Steps to reproduce

1. Open Emacs
2. Monitor

### System Information

https://pastebin.com/gyAcH8Rk

**Comment by hlissner** [comment]
Not a bug. Emacs can't display multiple fonts in terminal Emacs. Icons are displayed using an icon font. To see icon fonts use GUI Emacs instead.
