### ISSUE TITLE
With LSP and Snippets enabled, company-mode sorts snippets to the bottom

### ISSUE THREAD

**Issue by PatrickWulfe** [hlissner/doom-emacs#5215]
### What did you expect to happen?

When I have snippets and LSP enabled, company should show matching snippets before LSP results.

### What actually happened?

When I used snippets and lsp in a dart project, company would put the snippets at the end of the list, which is typically hundreds of entries long.  It had the same behavior with python, but it's LSP didn't make lists as long.

### Describe your attempts to resolve the issue

The default 'company-backends' is "((:separate company-capf company-yasnippet) company-yasnippet)", but when I change it to "((:separate company-yasnippet company-capf) company-yasnippet)", it works as expected.

### Steps to reproduce

1. Enable LSP and snippets for a language
2. Open a file and start typing a snippet enough for company to show up

### System Information

https://pastebin.com/Y9M0mGSs

**Comment by sei40kr** [comment]
You can change `+lsp-company-backends` to work around it:

```emacs-lisp
(setq +lsp-company-backends '(:separate company-yasnippet company-capf))
```

**Comment by hlissner** [comment]
As of ba716d6 snippets are interspersed with the normal completion results, instead of simply placing the snippets in front of them (and thus creating a new problem). This should indirectly fix this issue.
