### ISSUE TITLE
Can't paste from clipboard with pgtk build on wayland

### ISSUE THREAD

**Issue by minikN** [hlissner/doom-emacs#5219]
### What did you expect to happen?

1. Copy some text to the clipboard in another application (browser for example)
2. Paste it into an emacs buffer (with evil either using `p` in normal mode or `shift + insert` in insert mode)
3. Text gets pasted

### What actually happened?

it does not paste the copied text. Echo area instead says `Mark set`.

### Describe your attempts to resolve the issue

I tried with `emacs -Q`. It works without any problems there.
I tried `M-x yank` manually, same result (No paste, echo area says `Mark set`).

### Steps to reproduce

0. I use GNU/Guix
1. Install `emacs-pgtk-native-comp` from @flatwhatson (https://github.com/flatwhatson/guix-channel/blob/master/flat/packages/emacs.scm#L127)
2. Install Sway
3. `git clone --depth 1 https://github.com/hlissner/doom-emacs ~/.config/emacs`
4. `~/.config/emacs/bin/doom install`
5. Open emacs
6. Copy text in different window
7. In emacs buffer type `p` (normal) or `shift + insert` (insert) or `M-x yank`
8. Text doesn't get pasted.

### System Information

https://pastebin.com/DwTuMmX5

**Comment by minikN** [comment]
I added this to make it work:

```lisp
(when (getenv "WAYLAND_DISPLAY")
  (setq interprogram-cut-function (lambda (text)
                                    (let* ((process-connection-type 'pipe)
                                           (wl-copy-p (start-process "wl-copy" nil "wl-copy" "-f" "-n")))
                                      (process-send-string wl-copy-p text)
                                      (process-send-eof wl-copy-p)))
        interprogram-paste-function (lambda ()
                                      (let ((wl-paste (shell-command-to-string "wl-paste -n | tr -d '\r'")))
                                        (unless (string= (car kill-ring) wl-paste)
                                          wl-paste)))))
```

I'll leave it open though. This should be investigated since it works on vanilla.

**Comment by NINNiT** [comment]
I am encountering a similar error using sway. 
Pasting from other wayland windows into emacs-pgtk-native-comp works just fine.
It does however not work for windows running XWayland, e.g. firefox which does not use wayland by default.

**Comment by sei40kr** [comment]
> No paste, echo area says Mark set

I don't know why this is happening.

Please try `:os tty` module. It contains `xclip` and despite of its name, it supports `wl-clipboard`.

**Comment by minikN** [comment]
> > No paste, echo area says Mark set
> 
> I don't know why this is happening.
> 
> Please try `:os tty` module. It contains `xclip` and despite of its name, it supports `wl-clipboard`.

Unfortunately, that didn't work for me.

**Comment by hlissner** [comment]
`:os tty` only starts xclip in the terminal, so it won't help GUI users without an extra step: `(add-hook 'window-setup-hook #'xclip-mode)`

**Comment by edrex** [comment]
Results:

- @minikN's snippet bridges copy/paste in other apps with `yy`/`p`. Trailing newline is stripped, this is a known issue with GTK AFAIR, will have to find bug report.
- Adding the hook @hlissner posted bridges selection buffer (the old school X11 copy/paste method where you paste with middle mouse) but not standard clipboard.

**Comment by edrex** [comment]
the gtk newline brokenness, afair:
 - [[https://bugzilla.mozilla.org/show_bug.cgi?id=1547595][1547595 - GTK puts \r\n line endings into the Wayland Clipboard on Linux]]
 - [[https://gitlab.gnome.org/GNOME/gtk/-/issues/2307#note_832398][wayland: Multiline copy-paste contains CRLF line endings (#2307) · Issues · GNOME / gtk · GitLab]]

**Comment by jezcope** [comment]
Just came across this issue looking for the solution myself, really useful, thanks!

@edrex AFAICT the stripping of trailing newline is by design as @minikN's snippet includes the `-n` argument to `wl-copy`, which is short for `--trim-newline`, documented as "Do not copy the trailing newline character if it is present in the input file." I usually include long options in config files to make things clearer to my future self, so I have the following variation in my config now:

```emacs-lisp
(when (getenv "WAYLAND_DISPLAY")
  (setq wl-copy-p nil

        interprogram-cut-function
        (lambda (text)
          (setq-local process-connection-type 'pipe)
          (setq wl-copy-p (start-process "wl-copy" nil "wl-copy" "--foreground" "--trim-newline"))
          (process-send-string wl-copy-p text)
          (process-send-eof wl-copy-p))

        interprogram-paste-function
        (lambda ()
          (unless (and wl-copy-p (process-live-p wl-copy-p))
            (shell-command-to-string "wl-paste -n | tr -d '\r'")))))
```

**Comment by edrex** [comment]
@jezcope yeah, i think intended as a workaround for the gtk bug

**Comment by jezcope** [comment]
Oh right, I see, the GTK bug is adding *extra* newlines that need to be stripped. My misunderstanding :)

**Comment by minikN** [comment]
Has anyone found a appropriate solution yet? The snippet I use tends to break. Sometimes the `wl-copy` process hangs and I can't paste anymore before I kill it manually, this is unfortunate.

**Comment by edrex** [comment]
maybe everyone else already realized this, but it's a doom issue: emacs-pgtk with `-q` works fine in both directions.

**Comment by edrex** [comment]
Only pasting into (pgtk+doom) emacs from other apps is broken, so there's no need to change `interprogram-cut-function`. A simplified version of the workaround without the `wl-copy` hang noted by @minikN:

```
(when (getenv "WAYLAND_DISPLAY")
  (setq interprogram-paste-function
        (lambda ()
                (shell-command-to-string "wl-paste -n | tr -d '\r'"))))
```

PS: My emacs debugging skills are very basic, but in poking around trying to see what's going on I noted that disabling all modules in `~/doom.d/init.el` doesn't fix , so it's not something in the optional code.

**Comment by dit7ya** [comment]
Has anybody found a solution to this? 

The snippet above is considerably slow and violates various expectations around typical paste.

**Comment by jezcope** [comment]
Hmm, I've just given @edrex's latest suggested snippet a try and for some reason it breaks `org-refile` functionality with the error "The kill is not a (set of) trees".

**Comment by sei40kr** [comment]
Finally I could reproduce this issue.

And I noticed disabling `xclip-mode` solve this problem.

```emacs-lisp
(package! xcilp :disable t)
```

**Comment by sei40kr** [comment]
I found out how to fix this.

We need `'text/plain\;charset=utf-8` in `x-select-request-type` at` [core-editor.el#L240](https://github.com/hlissner/doom-emacs/blob/develop/core/core-editor.el#L240).

**Comment by minikN** [comment]
> This issue should now be resolved (thanks to @sei40kr for revealing the solution). Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

It's fixed. Thanks!
