### ISSUE TITLE
Provide safe migration path to org-roam v2

### ISSUE THREAD

**Issue by worldofgeese** [hlissner/doom-emacs#5223]
### Describe your request

Org-roam v1 is EOL on July 3rd and will be backwards incompatible from that release forward. That's just two days for Doom users to migrate but the Roam module is still on v1. Please provide a safe migration path for v1 users.

### Briefly explain its use-case

1. On next doom upgrade script checks if existing roam notes are v1, offers to auto-migrate.
2.  v1 is automatically bumped to v2.

**Comment by gagbo** [comment]
Packages are pinned, so as long as you don't touch them, you'll keep using v1 anyway.

PRs for migration are probably (very) welcome, but I can't speak for Henrik

**Comment by e3bc54b2** [comment]
From Jethro's blog, a migration function is now built into org-roam.

https://blog.jethro.dev/posts/org_roam_v2/

**Comment by jethrokuan** [comment]
I think doom can offer a `+roam2` flag, supporting both v1 and v2 with ease.
