### ISSUE TITLE
Void function definition in +vc/browse-at-remote-homepage

### ISSUE THREAD

**Issue by andrewpeck** [hlissner/doom-emacs#5224]
### 

- [X] I have searched [the FAQ](https://doomemacs.org/docs/faq.org) and [the documentation](https://doomemacs.org/docs/getting_started.org) for solutions.
- [X] I have searched [the issue tracker](https://github.com/hlissner/doom-emacs/issues) for similar issues (the closed issues too).
- [X] I have searched [the Discourse](https://doomemacs.org/d/docs) for any errors and solutions.
- [X] I can reproduce my issue on [the latest commit](https://github.com/hlissner/doom-emacs/commit) of Doom Emacs.
- [X] I have read [How to Debug Issues](https://doomemacs.org/d/how2debug) and found no solution.

### What did you expect to happen?

In a freshly opened emacs instance, `+vc/browse-at-remote-homepage`  should open the homepage of a Git repository. 

### What actually happened?

In a sandboxed doom instance, running `+vc/browse-at-remote-homepage` fails with the error:

```
*** Eval error ***  Symbol’s function definition is void: browse-at-remote--remote-ref
```

It works fine if, however, I have previously run `+vc/browse-at-remote` (which has a `(require 'browse-at-remote)` in it)

### Describe your attempts to resolve the issue

If I add `(require 'browse-at-remote)` into `+vc--remote-homepage` everything seems to work as expected:

``` elisp
(defun +vc--remote-homepage ()
  (require 'browse-at-remote)
  (or (let ((url (browse-at-remote--remote-ref)))
        (cdr (browse-at-remote--get-url-from-remote (car url))))
      (user-error "Can't find homepage for current project")))
```

### Steps to reproduce

1. Open emacs 
2. Open a version controlled file 
3. run `+vc/browse-at-remote-homepage`

### System Information

https://pastebin.com/4EfAXbDA

**Comment by sei40kr** [comment]
Probably we need `(require 'browse-at-remote)` before this line:
https://github.com/hlissner/doom-emacs/blob/2731685095d1e6101b3215aa689426e1834ce00f/modules/emacs/vc/autoload/vc.el#L4

```diff
@@ -1,6 +1,7 @@
 ;;; emacs/vc/autoload/vc.el -*- lexical-binding: t; -*-
 
 (defun +vc--remote-homepage ()
+  (require 'browse-at-remote)
   (or (let ((url (browse-at-remote--remote-ref)))
         (cdr (browse-at-remote--get-url-from-remote (car url))))
       (user-error "Can't find homepage for current project")))
```

**Comment by andrewpeck** [comment]
Yes, thanks for taking a look!

That change is what had resolved it for me.

**Comment by hlissner** [comment]
As of 6438172 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
