### ISSUE TITLE
Overriding variables already overwritten by doom

### ISSUE THREAD

**Issue by yahiasanji** [hlissner/doom-emacs#5226]
### 

- [X] I have searched [the FAQ](https://doomemacs.org/docs/faq.org) and [the documentation](https://doomemacs.org/docs/getting_started.org) for solutions.
- [X] I have searched [the issue tracker](https://github.com/hlissner/doom-emacs/issues) for similar issues (the closed issues too).
- [X] I have searched [the Discourse](https://doomemacs.org/d/docs) for any errors and solutions.
- [X] I can reproduce my issue on [the latest commit](https://github.com/hlissner/doom-emacs/commit) of Doom Emacs.
- [X] I have read [How to Debug Issues](https://doomemacs.org/d/how2debug) and found no solution.

### What did you expect to happen?

First thanks for the great work. 
I need to write in arabic (right to left) and I've seen a commit in doom that changed the value of the variables bidi-display-reordering  and bidi-paragraph-direction . 
when I added the following lines to my config 

`(setq-default bidi-display-reordering 't)
                     bidi-paragraph-direction 'nil)`

I expected the variables to change and for it to work normally 

### What actually happened?

the first one is fine but the second variable doesn't change to nil instead it stays 'left-to-right 

### Describe your attempts to resolve the issue

i tried also changing it trough the (SPC h v) it changes for the buffer and it works fine but its not permanent and for the global variable it doesn't change even when i set it. 

### Steps to reproduce

1. Open emacs 
2. change the input method to arabic by using M-x set-input-method 
3. write something 
4. text is on the left it should be on the right 
5. add the 2 lines above to the config or evaluate them or whatever 
6. nothing changes
7. use spc h v and change the variables manually to t and nil respectevly 
8. works like a charm but goes away after restart 
9. also the global value for the second variable dont change 
10. please remove it from doom it doesn't make a significant improvement in performance 
11. this is the source of the problem [here](https://pastebin.com/WfRTNcY0)

### System Information

https://pastebin.com/WfRTNcY0

**Comment by hlissner** [comment]
```elisp
(setq-default bidi-display-reordering 't) bidi-paragraph-direction 'nil)
```

This is not valid elisp. Is this a typo? If it is, the correct code is

```lisp
(setq-default bidi-display-reordering t
              bidi-paragraph-direction nil)
```

**Comment by yahiasanji** [comment]
yes its just a typo 
now i partially solved it with setq! but i have to do spc h r r each time I open a buffer in arabic 
but its now on vanilla emacs too its not a doom problem I removed all the lines that contain those variables from all the files found on .emacs.d and its still there but after setting the custom variables it works on vanilla but not on doom it gets overwritten,
i tried hebrew-mode provided by someone called yoav . its a minor mode so it should solve my problem but unfortunately i get Device 1 in not a termcap device after calling the mode
