### ISSUE TITLE
Disabling evil-snipe-mode configuration for vim s/S substitution using FAQ-recommended config does not apply

### ISSUE THREAD

**Issue by jimrustle** [hlissner/doom-emacs#5242]
### 

- [X] I have searched [the FAQ](https://doomemacs.org/docs/faq.org) and [the documentation](https://doomemacs.org/docs/getting_started.org) for solutions.
- [X] I have searched [the issue tracker](https://github.com/hlissner/doom-emacs/issues) for similar issues (the closed issues too).
- [X] I have searched [the Discourse](https://doomemacs.org/d/docs) for any errors and solutions.
- [X] I can reproduce my issue on [the latest commit](https://github.com/hlissner/doom-emacs/commit) of Doom Emacs.
- [X] I have read [How to Debug Issues](https://doomemacs.org/d/how2debug) and found no solution.

### What did you expect to happen?

According to the FAQ, the recommended way to disable evil-snipe-mode and enable the vim s/S behavior is by adding  `(after! evil-snipe (evil-snipe-mode -1))` to config.el. This does not disable evil-snipe-mode and the s/S keys are still mapped to `evil-snipe-s`.

### What actually happened?

I added `(after! evil-snipe (evil-snipe-mode -1))` to config.el. I ran `doom sync`, closed and restarted emacs, and pressing the s/S keys in a text buffer do not behave as vim's substitution commands as expected.

### Describe your attempts to resolve the issue

A workaround I have been suggested on the doom emacs discord is by adding `(map! :map general-override-mode-map :nv "s" #'evil-substitute)` to config.el, which produces the expected behavior.

Another suggestion made on the doom emacs discord is to use `(remove-hook! 'doom-first-input-hook evil-snipe-mode)`.

### Steps to reproduce

0. (optionally, delete .emacs.d and .doom.d, reinstall doom from scratch)
1. Add `(after! evil-snipe (evil-snipe-mode -1))` to config.el.
2. Run `doom sync` and `doom doctor` to ensure everything is configured and installed correctly.
3. Open emacs, `C-x b` into \*scratch\*
4. Press `s` or `S`

2> appears on the bottom, and the editor does not delete a character/line and enter insert mode as expected.

### System Information

https://pastebin.com/GiCQxJry

**Comment by hlissner** [comment]
The instructions were outdated and were corrected (in `docs/faq.org` in 43ddb10, and on [our discourse](https://discourse.doomemacs.org/t/the-s-and-s-keys-don-t-behave-like-they-do-in-vim-evil/138/3)).

You were close with `(remove-hook! 'doom-first-input-hook evil-snipe-mode)`, but you forgot to quote `evil-snipe-mode`.

 Please follow the new instructions and your issue should be resolved.

**Comment by jimrustle** [comment]
Ah thank you. I couldn't find anything related to it by searching evil-snipe on the discourse.
