### ISSUE TITLE
Would adding a +prettier on the javascript module for my javascript/typescript projects be possible?

### ISSUE THREAD

**Issue by TalhaAbid** [hlissner/doom-emacs#5245]
### Describe your request

So I love emacs but the formatter for javascript doesn't automatically work and I like to use prettier (i think the built in javascript module uses something else) so I am thinking of adding a +prettier flag that will auto add hooks for prettier formatting without the user having to do anything to get some decent formatting out of the box. Well they would have to install prettier package using npm.

### Briefly explain its use-case

1. set up doom
2. go to init.el and add +prettier on javascript 
3. auto prettier formatting on javascript/typescript projects and wolla.

**Comment by hlissner** [comment]
We already have an `:editor format` module (`:editor (format +onsave)` will enable on-save formatting across the board), which manages all our formatters using [format-all](https://github.com/lassik/emacs-format-all-the-code) (but will soon be rewritten to use [apheleia](https://github.com/raxod502/apheleia). It uses prettier for javascript modes (and others) already.

As this functionality already exists and adding module-specific formatters would be redundant I will close this.
