### ISSUE TITLE
Unreadably dark text on dark title bar on macOS

### ISSUE THREAD

**Issue by quarkquartet** [hlissner/doom-emacs#5248]
### What did you expect to happen?

I installed emacs-plus@28, tried both native-comp or without native comp. I expect everything behaves as well as before.

### What actually happened?

<img width="804" alt="image" src="https://user-images.githubusercontent.com/26316540/125127258-40328380-e0ca-11eb-8769-48fcb019f756.png">

Look at the title bar now. The font is dark even on a dark theme. The font is not at the middle of the title bar.

### Describe your attempts to resolve the issue

`mv .emacs.d .emacs.d.bak`

Then open emacs. The title bar now is always white background and black font, whatever theme I load.

The font is at the correct position, of course.

**I'm not sure whether this problem is from Doom or emacs-plus. I also submit an issue under emacs-plus.**

### Steps to reproduce

Use MacOS Big sur.

`brew install emacs-plus@28`

`doom-clean`
`doom-install`

Open emacs, and you will see it.

### System Information

https://pastebin.com/Szzbzh0s

**Comment by shaunsingh** [comment]
I have the same issue as well, using emacs-plus@28 with natural toolbar

**Comment by elken** [comment]
Try without the title bar patch and see if that resolves it

**Comment by quarkquartet** [comment]
> Try without the title bar patch and see if that resolves it

`brew install emacs-plus@28 --without-title-bar`?

**Comment by elken** [comment]
> > Try without the title bar patch and see if that resolves it
> 
> `brew install emacs-plus@28 --without-title-bar`?

**Comment by elken** [comment]
> > Try without the title bar patch and see if that resolves it
> 
> `brew install emacs-plus@28 --without-title-bar`?

I got it mixed up with the appearance patch. Does it still occur with `emacs -Q`? If so then it's not doom and this should be closed.

**Comment by shaunsingh** [comment]
It doesn't occur with emacs -Q, I have the same issue

**Comment by quarkquartet** [comment]
> It doesn't occur with emacs -Q, I have the same issue

Same. Empty emacs is totally fine.

**Comment by elken** [comment]
Do either of you get the same with the macos module off?
