### ISSUE TITLE
doom-modeline-major-mode-icon breaks emacsclient -nw

### ISSUE THREAD

**Issue by steven-lang** [hlissner/doom-emacs#5258]
### What did you expect to happen?

Setting  `(setq doom-modeline-major-mode-icon t)` and running `emacsclient -nw` should gracefully fall back to available terminal font icons.

### What actually happened?

It results in 

```
Error in a Doom startup hook: after-change-major-mode-hook, doom-modeline-update-buffer-file-icon,
(wrong-type-argument stringp nil)
```

Full backtrace: https://pastebin.com/vuuRYAgS

### Describe your attempts to resolve the issue

Setting `(setq doom-modeline-major-mode-icon nil)` (default) resolves the issue.

### Steps to reproduce

1. Set `(setq doom-modeline-major-mode-icon t)` in a clean `config.el`
2. Restart emacsclient
3. Run `emacsclient -nw` in terminal
4. Run `M-x`

### System Information

https://pastebin.com/9XMhxjeg

**Comment by gagbo** [comment]
Probably a duplicate of #3514

**Comment by steven-lang** [comment]
Oh absolutely, I must have missed that one, sorry!
