### ISSUE TITLE
With `lsp` and `snippets` enabled, the completion candidates in `python-mode` are not sorted by relevance

### ISSUE THREAD

**Issue by x6rulin** [hlissner/doom-emacs#5262]
### What did you expect to happen?

While editing Python code, the completions with more relevance should have higher priority. That means, when I type _ab_, candidates which **start with** _ab_ should be the first priority, then ones containing the string _ab_ and then the characters _a_ and _b_, like below:
![Screenshot from 2021-07-15 11-44-17](https://user-images.githubusercontent.com/22050297/125725875-63894e83-aaa0-4971-887e-ce5cae65b6dc.png)

### What actually happened?

The completions are sorted likely with some confusing order, not relevance first.

![Screenshot from 2021-07-15 11-38-54](https://user-images.githubusercontent.com/22050297/125725414-b37128c4-bd7a-4683-a5b5-5594f61b3d4d.png)

### Describe your attempts to resolve the issue

Figuring out that occurs after the commit [ba716d6](https://github.com/hlissner/doom-emacs/commit/ba716d69f0f680125e2411ac050086d54d7c8a4b), I add below codes to my _config.el_:

```
(after! python
  :init
  (setq! +lsp-company-backends
         (if (featurep! :editor snippets)
             '(:separate company-yasnippet company-capf)
           'company-capf)))
```
It works, but just covers up the real problem. A thorough solution is still needed.

### Steps to reproduce

1. upgrade **doom emacs** to the most recent commit
2. choose `company` as the code completion backend, enable `lsp` and `snippets`, set the `+lsp` flag in `python-mode`, then run `doom sync`
3. open one _.py_ file, edit some codes, observe the completion candidates

### System Information

https://pastebin.com/jrkaCBb0

**Comment by PatrickWulfe** [comment]
What's happening is 'abs' is a snippet and your setting is moving snippets in front of the lsp results.  I do this too with:
(setq +lsp-company-backends '(:separate company-yasnippet company-capf))

The previous behavior was that snippets were being pushed after the lsp results, but just in the past week or so was changed so they are now mixed in with the lsp results.  I guess moving them to the front would cause issues somehow.
[https://github.com/hlissner/doom-emacs/issues/5215](url)

**Comment by x6rulin** [comment]
> What's happening is 'abs' is a snippet and your setting is moving snippets in front of the lsp results. I do this too with:
> (setq +lsp-company-backends '(:separate company-yasnippet company-capf))
> 
> The previous behavior was that snippets were being pushed after the lsp results, but just in the past week or so was changed so they are now mixed in with the lsp results. I guess moving them to the front would cause issues somehow.
> #5215

It's okay to mix the lsp result with snippets. However, the completions should be present in a smart way that helps efficient coding, instead of some confusing and helpless ones.

**Comment by RBckmnn** [comment]
I experience the same issue with typescript and csharp language server. I asked about this issue on the lsp-discord and I was told this was caused by https://github.com/emacs-lsp/lsp-mode/issues/2970

**Comment by juanscr** [comment]
I'm having the same issue after the upgrading doom. It looks like the commit mentioned in the description caused that issue.

**Comment by Ivche1337** [comment]
BUMP

**Comment by jpcima** [comment]
I have such an issue with clangd and lsp-mode.
An update has destroyed the quality of completion candidates to a point that they're useless, because of bad sorting.

Fortunately, I can bisect it, and I am able to confirm this commit as the culprit. Reverting fixes the issue.
ba716d69f0f680125e2411ac050086d54d7c8a4b

**Comment by kamyabzad** [comment]
I have the same issue in python.

**Comment by hlissner** [comment]
Sorry for the long wait. I reverted the problem commit in 77f78f0, which should fix this issue. Thanks for bringing it to my attention!

(A friendly reminder: github has :+1: reactions. Please use these to express "I have the same issue" if you don't have more to add to the original post)
