### ISSUE TITLE
Gopls: Home is loaded instead of actual project directory

### ISSUE THREAD

**Issue by tomasmik** [hlissner/doom-emacs#5267]
### What did you expect to happen?

Create or pull a new project. If it's new create the go.mod etc.
Open a new golang project and gopls loads that project directory:
`gopls:9093 initialized successfully in folders: (/path/to/actualy/porject)`

### What actually happened?

It loads my home directory 
`gopls:6559 initialized successfully in folders: (/home/USERNAME)`

### Describe your attempts to resolve the issue

I've tried:

* to exclude home directory by setting flags in config:
```
(setq projectile-globally-ignored-directories '("/home/tomas"))
(setq projectile-ignored-projects '("/home/tomas"))
```
* adding the .projectile file to my project
* creating additional files like Makefile etc. to maybe make it grab the project
* clearing all cache for projectile
* updating gopls and doom-emacs

I have no problem with any of my olds projects I've created or pulled. Even if I remove the cache and all my projects, after I open them, gopls gets initialized to the correct dir. Only new projects seem to not work.

### Steps to reproduce

1. Create a new project
2. `go mod init X` to initialize go modules
3. Open the project in Emacs
4. It should load home directory and freeze emacs as it tries to look through all home dir

### System Information

https://pastebin.com/GNMUr2v0

**Comment by tomasmik** [comment]
This fixed itself after reinstall doom emacs from scratch. I would only assume that at some point I added my home folder as a project and it started loading that.

**Comment by martijndeheus** [comment]
I've run into similar issues with project root discovery. In my opinion it is pretty hard to figure out what is responsible for this behaviour and to possibly solve this with your config.

For now I found I workaround that works pretty well for me. You can use `lsp_workspace_folders_add` and `lsp_workspace_folders_remove`. To manually add and remove root directories for LSP.
