### ISSUE TITLE
Getting Started README page has broken quote formatting when viewed on github

### ISSUE THREAD

**Issue by SeanGrady** [hlissner/doom-emacs#5276]
### What did you expect to happen?

Copying and pasting the `export PATH="$HOME/.emacs.d/bin:$PATH"` line in the getting started readme file should work

### What actually happened?

Instead, the `~` characters intended to turn it into an inline code block do not work, and so it renders U+201D (right double quotation mark (and it's left version to close)) instead of U+0022 (quotation mark). Because of this, and because most terminals etc. render them the same way, everything will _look_ correct -- even your path variable will seem like it's updated correctly -- but:
```
❯ doom
zsh: command not found: doom
```

### Describe your attempts to resolve the issue

I tried various ways to reformat that part of the readme, but I don't think it's using standard github markdown (ReST or something?) and I can't find a way to make it work while keeping it in a block quote. I'm happy to figure out a way that works and submit a PR, but wanted to ask what the formatting language is and whether it's ok to do things like not have that bit in a block quote.

### Steps to reproduce

Copy and paste the line in question into a unicode character decoder and/or a zsh rc file.

### System Information

https://pastebin.com/sHUzYP29

**Comment by hlissner** [comment]
To quote https://github.com/hlissner/doom-emacs/pull/4709#issuecomment-788068213, our in-repo docs are being rewritten, and this will be indirectly fixed in that change. Also, I am not currently accepting PRs to our in-repo docs (`docs/*`) (see our [do-not-PR](https://discourse.doomemacs.org/t/development-roadmap/42#do-not-pr) list). In any case, thanks for bringing it to my attention.

**Comment by SeanGrady** [comment]
Ah, sounds good! Might be worth putting a note at the top of the README mentioning this, and that (it sounds like?) discourse is more up to date. I did search through the issues, but didn't find this specific one mentioned and also managed to miss #4709 _and_ the do-not-PR list (🙄 @ me). May or may not be worth the trouble, either way I appreciate the quick response!
