### ISSUE TITLE
Bring back ivy-occur for LSP-powered lookup/references

### ISSUE THREAD

**Issue by HouzuoGuo** [hlissner/doom-emacs#5285]
### What did you expect to happen?

I use doom-emacs to program in go, shell, and a couple more languages. About a week ago, the results of `lookup/references` of symbol under cursor (`gD` or `SPC c D`) used to bring up a region at the bottom of the emacs window, the behaviour is very similar to this interaction with swiper:

![image](https://user-images.githubusercontent.com/563872/126809522-165d4b1f-3da1-493a-bfe2-293855c2492f.png)

Which then enables me to use `C-c C-o` combo to bring up ivy-occur:

![image](https://user-images.githubusercontent.com/563872/126809604-dc41b2aa-52ac-4a06-8ded-65542c31891d.png)

### What actually happened?

Since about a week ago, `lookup/references` no longer brings up the window at the bottom, instead, it brings up this inline region:

![image](https://user-images.githubusercontent.com/563872/126809981-db24a89a-1909-48d7-b182-4c085a3353b3.png)

The inline region does not respond to ivy-occur key combo (`C-c C-o`), which makes large scale refactoring far more difficult.

### Steps to reproduce

Open a go project, highlight a symbol and then press `gD` or `SPC c D`.

### System Information

https://pastebin.com/4YWjD9zT

**Comment by hlissner** [comment]
Disable the `+peek` flag on `:tools lsp`.

**Comment by HouzuoGuo** [comment]
@hlissner lovely, that worked!

**Comment by HouzuoGuo** [comment]
Many thanks!
