### ISSUE TITLE
Not evaluating code block in orgmode

### ISSUE THREAD

**Issue by ashincoder** [hlissner/doom-emacs#5286]
### What did you expect to happen?

When I press enter to evaluate a code block of  python it should print the right results. 

### What actually happened?

When I press enter to evaluate a code block of  python it doesn't print the right results. Take a look at here.

https://user-images.githubusercontent.com/83629316/126871050-5f82a2dc-a9e9-49e3-8483-1a6d4e819abf.mp4

### Describe your attempts to resolve the issue

I don't know what I should do here is the code I used:

```
#+begin_src python
print("Hello")
#+end_src

#+RESULTS:
: None

```
The a

### Steps to reproduce

1. In an org document paste the following code:
```
#+TITLE: Python: Expressions
#+DESCRIPTION: Variables, Expressions, and Statements

#+begin_src python
print("Hello")
#+end_src

```
2. Press enter on the code block
3. See the result

### System Information

https://pastebin.com/9b56tDKU

**Comment by hlissner** [comment]
Please read up on the `:results output` option here: https://orgmode.org/manual/Results-of-Evaluation.html

```org
#+begin_src python :results output
print("Hello")
#+end_src

#+RESULTS:
: Hello
```

Since this isn't a bug I will close this, and because our issue tracker isn't the place for how-to questions I mark it for eventual deletion.

**Comment by ashincoder** [comment]
Thank you
