### ISSUE TITLE
Doom fails when upgrading (solved)

### ISSUE THREAD

**Issue by harabat** [hlissner/doom-emacs#5289]
### What did you expect to happen?

I'm upgrading to the latest version (today's commits). 

### What actually happened?

I first had the error described in #4950 (`void-function straight--process-buffer` error), which I solved with the suggested solution of removing `~/.emacs.d/.local/straight/repos/straight.el`. 

When running `./bin/doom sync -up` (part of the solution of #4950) I got the following:
```
> Installing straight...
> Executing 'doom sync -up' with Emacs 27.2 at 2021-07-25 11:30:48
  > Synchronizing your config with Doom Emacs...
    > Regenerating envvars file at "~/.emacs.d/.local/env"
      ✓ Successfully generated "~/.emacs.d/.local/env"
    > Installing packages...
      - No packages need to be installed
    > (Re)building packages...
      - No packages need rebuilding
    > Updating recipe repos...
    > Updating packages (this may take a while)...
      > In repository "org-journal", failed to get status:
      
        Failed to get unambiguous name for "master"
        fatal: Needed a single revision

           1) Abort

        How to proceed? (1) 
```

### Describe your attempts to resolve the issue

I found #4251 and did the following:
- remove `~/.emacs.d/.local/straight/repos/melpa`
- remove `~/.emacs.d/.local/straight/repos/straight.el` (because otherwise I rerun into the first issue)
- run `./bin/doom sync`
- run `./bin/doom upgrade`

The upgrade worked but Doom still errored on org-journal:
```
> Executing 'doom upgrade' with Emacs 27.2 at 2021-07-25 11:49:32
  > Preparing to upgrade Doom Emacs and its packages...
  ✓ Doom is already up-to-date!
  Doom is up-to-date!
  > Synchronizing your config with Doom Emacs...
    > Regenerating envvars file at "~/.emacs.d/.local/env"
      ✓ Successfully generated "~/.emacs.d/.local/env"
    > Installing packages...
      - No packages need to be installed
    > (Re)building packages...
      - No packages need rebuilding
    > Updating recipe repos...
    > Updating packages (this may take a while)...
      > In repository "org-journal", failed to get status:
      
        Failed to get unambiguous name for "master"
        fatal: Needed a single revision

           1) Abort

        How to proceed? (1) 
```

I found #4984 and did the following:
- Run `rm -rf ~/.emacs.d/.local/straight/repos/org-journal`
- Run `./bin/doom upgrade`
- Run `./bin/doom sync`

This solved the issue. 

### Steps to reproduce

1. Run `./bin/doom upgrade`
2. Get first error
3. Remove  `~/.emacs.d/.local/straight/repos/straight.el`
4. Run `./bin/doom sync -up`
5. Get second error
6. Remove  `~/.emacs.d/.local/straight/repos/straight.el` and `~/.emacs.d/.local/straight/repos/melpa`
7. Run `./bin/doom sync`
8. Run `./bin/doom upgrade`
9. Get third error
10. Run `rm -rf ~/.emacs.d/.local/straight/repos/org-journal`
11. Run `./bin/doom sync`
12. Run `./bin/doom upgrade`
13. Issue solved

### System Information

https://pastebin.com/0G4KTS2C

**Comment by hlissner** [comment]
Since this is not an issue and has been documented elsewhere, I'll close this.

**Comment by harabat** [comment]
Yeah, I wanted to centralise the bug reports in one solution to avoid similar bug reports. Thanks for pointing me to #4273.
