### ISSUE TITLE
org/+roam2 `org-roam-node-find` display garbled CJK filetitle.

### ISSUE THREAD

**Issue by colawithsauce** [hlissner/doom-emacs#5293]
### What did you expect to happen?

I expect it could show the character correctly.

### What actually happened?

But I get this 
![image](https://user-images.githubusercontent.com/51731521/126897726-65bf9312-5ce1-4322-8c9e-bc52c9046654.png)

### Describe your attempts to resolve the issue

The original org-roam-v2 didn't have this issue, so I guess it's because of doom. Finally, I find it's because the variable `org-roam-node-display-template` and the `org-roam-node-display-template`, which are all set to `"${doom-hierarchy:*} ${doom-tags:45}"`.

So, This issue must caused by these two function in `~/.emacs.d/modules/lang/org/autoload`
``` elisp
;;; Custom node accessors
;;;###autoload (autoload 'org-roam-node-doom-filetitle "lang/org/autoload/contrib-roam2" nil t)
(cl-defmethod org-roam-node-doom-filetitle ((node org-roam-node))
  "Return the value of \"#+title:\" (if any) from file that NODE resides in.
If there's no file-level title in the file, return empty string."
  (or (if (= (org-roam-node-level node) 0)
          (org-roam-node-title node)
        (org-roam-get-keyword "TITLE" (org-roam-node-file node)))
      ""))

;;;###autoload (autoload 'org-roam-node-doom-hierarchy "lang/org/autoload/contrib-roam2" nil t)
(cl-defmethod org-roam-node-doom-hierarchy ((node org-roam-node))
  "Return hierarchy for NODE, constructed of its file title, OLP and direct title.
If some elements are missing, they will be stripped out."
  (let ((title     (org-roam-node-title node))
        (olp       (org-roam-node-olp   node))
        (level     (org-roam-node-level node))
        (filetitle (org-roam-node-doom-filetitle node))
        (separator (propertize " > " 'face 'shadow)))
    (cl-case level
      ;; node is a top-level file
      (0 filetitle)
      ;; node is a level 1 heading
      (1 (concat (propertize filetitle 'face '(shadow italic))
                 separator title))
      ;; node is a heading with an arbitrary outline path
      (t (concat (propertize filetitle 'face '(shadow italic))
                 separator (propertize (string-join olp " > ") 'face '(shadow italic))
                 separator title)))))
```
I can assert that one of these two function are produce this issue, but unfortunately I have little experience to fix it.

### Steps to reproduce

1. Just create a roam file node, and paste this line as the title of the node.
```
#+title: 高等数学
```
2. `M-x org-roam-db-sync`
3. `M-x org-roam-node-find`
And you can see the garbled characters.

### System Information

https://paste.ubuntu.com/p/pTh4N8KzDr/

**Comment by colawithsauce** [comment]
It's seems that the `org-roam-node-doom-filetitle` would get garbled string when the node is not a file node and the file title is CJK character.
It's the test file I used.
```
:PROPERTIES:
:ID:       2973648b-c6ff-4fe1-92ff-d87754cbc0a3
:END:
#+title: 测试
* 测试 Bug
:PROPERTIES:
:ID:       ba1e6d89-e2c8-4c09-b8cd-1814556c254e
:END:
```
It's what I get
![image](https://user-images.githubusercontent.com/51731521/126900386-76332af7-3072-4538-9c99-83f372874f56.png)

**Comment by Wetlize** [comment]
To obtain file title Doom uses what `org-roam` already provides, specifically `org-roam-get-keyword` function. If you open the file and set the point at `#+title: 测试`, and then run `SPC ; (org-roam-get-keyword "TITLE" (org-roam-node-file (org-roam-node-at-point)))` you will see the same problem in the return value. Can you report this to `org-roam` itself?

**Comment by colawithsauce** [comment]
Thanks your reply :smile: , I will report it to `org-roam`. btw. I solve this problem by replace the `org-roam-get-keyword` with another function I copied from stackoverflow, and it works perfectly.
That's what I did:
``` elisp
(defun my/get-keyword-key-value (kwd)
  (let ((data (cadr kwd)))
    (list (plist-get data :key)
          (plist-get data :value))))

(defun my/org-file-get-title (file)
  (with-current-buffer (find-file-noselect file)
    (nth 1
         (assoc "TITLE"
                (org-element-map (org-element-parse-buffer 'greater-element)
                    '(keyword)
                  #'ndk/get-keyword-key-value)))))
;;; Custom node accessors
;;;###autoload (autoload 'org-roam-node-doom-filetitle "lang/org/autoload/contrib-roam2" nil t)
(cl-defmethod org-roam-node-doom-filetitle ((node org-roam-node))
  "Return the value of \"#+title:\" (if any) from file that NODE resides in.
If there's no file-level title in the file, return empty string."
  (or (if (= (org-roam-node-level node) 0)
          (org-roam-node-title node)
        (my/org-file-get-title (org-roam-node-file node)))
      ""))
```
Not such graceful, but useful. :grinning:

**Comment by Wetlize** [comment]
This won't scale well when you'll get a lot of files :) but a passable workaround for a time being if it works for you as for now. Thanks for the detailed bug report and also for another one in the `org-roam` repo.

**Comment by colawithsauce** [comment]
I modified org-roam-get-keyword
```elisp
(defun org-roam-get-keyword (name &optional file bound)
  "Return keyword property NAME from an org FILE.
FILE defaults to current file.
Only scans up to BOUND bytes of the document."
  (unless bound
    (setq bound 1024))
  (if file
      (with-temp-buffer
        (insert-file-contents file nil 0 bound) ;; from insert-file-contents-literally to insert-file-contents
        (org-roam--get-keyword name))
    (org-roam--get-keyword name bound)))
```
and it also works. Wondering if the "literally" essential here, anyway I will report this to `org-roam`.
