### ISSUE TITLE
switch-to-buffer-other-frame doesn't work as expected for popup buffers

### ISSUE THREAD

**Issue by daanturo** [hlissner/doom-emacs#5301]
### What did you expect to happen?

Run `switch-to-buffer-other-frame` and select a buffer which is treated as a popup (Messages, Compilation, etc.)

Expected: the buffer is opened in a new frame

### What actually happened?

The buffer appears at the bottom in the same frame.

### Describe your attempts to resolve the issue

HACK: add an advice around `switch-to-buffer-other-frame` that disables `+popup-mode` temporarily.

### Steps to reproduce

1. Turn on `+popup-mode`
2. Run `switch-to-buffer-other-frame`
3. Select a buffer which is treated as a popup (Messages, Compilation, etc.)

### System Information

https://pastebin.com/hkUN0dYh

**Comment by hlissner** [comment]
As of 2400e8b this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
