### ISSUE TITLE
:tools Magit 's +forge significantly slows down the first magit-status

### ISSUE THREAD

**Issue by daanturo** [hlissner/doom-emacs#5320]
### What did you expect to happen?

When `(doom! :tools (magit +forge))` is enabled, `magit-status` shouldn't be so slow.

### What actually happened?

Benchmarking `magit-status`'s results:
`Elapsed time: 3.383529s (0.102340s in 1 GCs)`
Profiler:
```
 701  86% - command-execute
 701  86%  - funcall-interactively
 701  86%   - pp-eval-expression
 701  86%    - my-profiler-cpu-progn
 701  86%     - benchmark-progn
 701  86%      - let
 701  86%       - progn
 699  86%        - benchmark-progn
 699  86%         - let
 699  86%          - progn
 699  86%           - magit-status
 699  86%            - apply
 699  86%             - my-with-deferred-gc-around-a
 699  86%              - #<compiled 0x12d850738aa2c9e3>
 699  86%               - apply
 593  73%                - doom--after-call-forge-h                                     <<< The culprit
 593  73%                 - condition-case
 593  73%                  - let
 573  70%                   - require
 573  70%                    - load-with-code-conversion
 204  25%                     - require
 199  24%                      - load-with-code-conversion
 44   5%                       + require
 25   3%                       + internal-macroexpand-for-load
 16   1%                       + do-after-load-evaluation
 9   1%                       + #<compiled 0x1f7efd0305c44>
 8   0%                       + eieio-defclass-internal
 3   0%                       + cl-generic-define-method
 2   0%                         defalias
 1   0%                       + defvar
 1   0%                     + if
 1   0%                     + do-after-load-evaluation
 106  13%                + #<subr magit-status>
 107  13% - ...
 103  12%    Automatic GC
 1   0%  + cconv-convert
 1   0%  + byte-optimize-form
 1   0%  + pcase--u1
 1   0%  + transient-append-suffix
```

Without `+forge`, `magit-status` only takes `Elapsed time: 0.185429s` to appear.

### Describe your attempts to resolve the issue

Remove `+forge`.

The binding is still usable if I declared `(package! forge)`, though.

### Steps to reproduce

1.In `init.el`, have `(doom! :tools (magit +forge))` enabled.
2. Open a new instance of Emacs, navigate to a repo and press `SPC g g`

### System Information

https://pastebin.com/hkUN0dYh

**Comment by hlissner** [comment]
It's natural that `doom--after-call-forge-h` would be the culprit, because that is when `forge` is being loaded.

Long first-time load times aren't something we can do much about. Forge has to initialize a lot; potentially compile emacs-sqlite, read your load DBs (takes longer the larger the project), not to mention all of magit+forge+dependencies are a long chain.

That said, I can't reproduce this in Doom, which is a moderately large project, but this could just be because of a reasonably beefy CPU (Ryzen 9 3900X) + M.2 SSDs.
