### ISSUE TITLE
Briefly summarize your issue here(void-variable EMACS27+)

### ISSUE THREAD

**Issue by pawel-domanski** [hlissner/doom-emacs#5323]
### What did you expect to happen?

Help with error

### What actually happened?

After upgrade to latest version doom I have that error

Rrror in private config: modules/editor/evil/init.el, (void-variable EMACS27+)

 > Checking Doom Emacs...
    x There was an unexpected error
      Message: Symbol's value as variable is void
      Data: (void-variable . EMACS27+)
      Backtrace:
        (if EMACS27+ '(thread))
        (append (if EMACS27+ '(thread)) '(tide timer-list transmission trashed typ
        (cons 'tetris (append (if EMACS27+ '(thread)) '(tide timer-list transmissi
        (cons '(term term ansi-term multi-term) (cons 'tetris (append (if EMACS27+
        (cons 'tar-mode (cons '(term term ansi-term multi-term) (cons 'tetris (app
        (cons 'tablist (cons 'tar-mode (cons '(term term ansi-term multi-term) (co
        (cons 'speedbar (cons 'tablist (cons 'tar-mode (cons '(term term ansi-term
        (cons 'sly (cons 'speedbar (cons 'tablist (cons 'tar-mode (cons '(term ter
        (cons 'slime (cons 'sly (cons 'speedbar (cons 'tablist (cons 'tar-mode (co
        (cons 'simple (cons 'slime (cons 'sly (cons 'speedbar (cons 'tablist (cons

### Steps to reproduce

1. Open Emacs

### System Information

https://pastebin.com/mBXb27RA

**Comment by hlissner** [comment]
`EMACS27+` no longer exists in Doom's codebase on the latest commit. The `EMACS27+` instance it's complaining about was removed in https://github.com/hlissner/doom-emacs/commit/34fae1c01ce6800cb7ed8830173cc644988af3e8#diff-627b3102c690d40dd1464ed2851e1aa37c51579a3b5cee29dff1272c1aaf9045R214 3 weeks ago.

Clearly something is wrong with your installation, and judging from your module list, you appear to be upgrading from a very old version of Doom. Your best bet is to delete `~/.emacs.d/.local/` by hand and run `doom sync` to start from scratch.

As this is not a Doom issue I will close this.

**Comment by pawel-domanski** [comment]
It's not working I try to download fresh brnch and recreate.

**Comment by pawel-domanski** [comment]
Some modules don't run too.

**Comment by hlissner** [comment]
Sounds like you're experiencing errors. Check \*Messages\* for warnings or errors (`C-h e` to open it).

**Comment by pawel-domanski** [comment]
No errors
Doom loaded 382 packages across 64 modules in 5.888s
Package cl is deprecated

**Comment by hlissner** [comment]
I can't help without more information. Try asking [on the Discord](https://doomemacs.org/discord) instead. 

You could also try again from the start.

1. Delete `~/.emacs.d`
2. Delete `~/.doom.d`
3. `git clone https://github.com/hlissner/doom-emacs ~/.emacs.d`
4. ~/.emacs.d/bin/doom install`

Please keep an eye out for errors during this process.

Because this works without problem on more than 12 test systems, this is clearly a local issue.

**Comment by pawel-domanski** [comment]
I don't know what was wrong. I recreate all emacs and now is OK.
