### ISSUE TITLE
(mu4e +org) does not work without doom-themes

### ISSUE THREAD

**Issue by e3bc54b2** [hlissner/doom-emacs#5340]
### What did you expect to happen?

I have `doom-themes` disabled because I use `modus-themes` (not included with Doom). So far I had no issues with this, and it was one less package to account for.

I have `(mu4e +gmail)` setup and working fine for few weeks with this setup and it has been very nice. But today I enabled `+org` flag, and `SPC o m` (mu4e) is not loading.

### What actually happened?

Loading mu4e fails `(SPC o m)` or `(M-x mu4e)` with below error message:

```
cons: Symbol’s function definition is void: doom-color
```

I can confirm this is reproducible with combination of `(mu4e +org) AND (disable-packages! doom-themes)` conditions are true.

### Describe your attempts to resolve the issue

I enabled `doom-themes` package and issue was resolved.

Ideally, I'd prefer no hard dependency on doom-themes, as ultimately this is aesthetic choice, and from my use so far, this is first time I've encountered an issue while doom-themes has been disabled. As such, this dependency should be removed.

But, if it is largely beneficial to use this from maintenance PoV, then this should at least be documented explicitly in module wiki.

### Steps to reproduce

1. Enable `(mu4e +org)` AND set `(disable-packages! doom-themes)` in packages.el.
2. M-x mu4e` OR `SPC o m`

### System Information

https://pastebin.com/dfeAzVxH

**Comment by hlissner** [comment]
Please [provide a backtrace of the error](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#how-to-extract-a-backtrace-from-an-error).

**Comment by hlissner** [comment]
Nevermind, found thecause. As of f74debd this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by e3bc54b2** [comment]
Confirmed fixed. Thanks for quick turnaround!
