### ISSUE TITLE
Exiting Doom Emacs fails if projectile project has been opened

### ISSUE THREAD

**Issue by GnawNom** [hlissner/doom-emacs#5345]
### What did you expect to happen?

Should be able to exit emacs.

### What actually happened?

Failed to exit emacs, backtrace below.
```
Debugger entered--Lisp error: (args-out-of-range "" 0 -1)
  substring("" 0 -1)
  (member (substring proot 0 -1) blacklist)
  (or (not (stringp proot)) (>= (length (gethash proot projectile-projects-cache)) doom-projectile-cache-limit) (member (substring proot 0 -1) blacklist) (and doom-projectile-cache-purge-non-projects (not (doom-project-p proot))) (projectile-ignored-project-p proot))
  (if (or (not (stringp proot)) (>= (length (gethash proot projectile-projects-cache)) doom-projectile-cache-limit) (member (substring proot 0 -1) blacklist) (and doom-projectile-cache-purge-non-projects (not (doom-project-p proot))) (projectile-ignored-project-p proot)) (progn (if doom-debug-p (progn (let ((inhibit-message (active-minibuffer-window))) (message #("DOOM Removed %S from projectile cache" 0 5 (face font-lock-comment-face)) proot)))) (remhash proot projectile-projects-cache) (remhash proot projectile-projects-cache-time) (remhash proot projectile-project-type-cache)))
```

### Describe your attempts to resolve the issue

Haven't tried it, because I don't know any elisp, but I think the fix is to skip any proots that are empty strings.

see line 127 in core-projects.el

`for proot in (hash-table-keys projectile-projects-cache)`

### Steps to reproduce

1. Open emacs
2. Open a project in projectile (SPC p p, select any project)
3. attempt to quit emacs (:q, select y)

### System Information

https://gist.github.com/GnawNom/05b0c0d3694e66d61098de42d71d4343

**Comment by MithicSpirit** [comment]
Sounds like doom is a bit _too_ much like Vim haha. Try using `SPC q q` to quit instead.

**Comment by GnawNom** [comment]
Tried `SPC q q`, still get the same error and backtrace. Same thing when I try cmd+q (quit via mac) or killing via activity manager or `SPC q K`.

**Comment by hlissner** [comment]
As of 1352f8a this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by GnawNom** [comment]
Let me try this out, thanks for the quick fix!

**Comment by GnawNom** [comment]
Yep. That worked 👍
