### ISSUE TITLE
Error on python with lsp using emacs-28 with native-compilation

### ISSUE THREAD

**Issue by codicef** [hlissner/doom-emacs#5349]
### What did you expect to happen?

Hello everyone I am trying to use emacs-28 with native-compilation.
My goal is to work on Python files using lsp. In init.el file I put

`       (python +lsp)           `

Note that I am still using the default doom configuration.

### What actually happened?

When I open a python file I get the following errors

`Error (python-mode-local-vars-hook): Error running hook "lsp!" because: (invalid-function lsp!)`

`Error (hack-local-variables-hook): Error running hook "doom-run-local-var-hooks-h" because: (doom-hook-error python-mode-local-vars-hook lsp! (invalid-function lsp!)) 
`

### Describe your attempts to resolve the issue

I tried to run  ~/.emacs.d/bin/doom build

### Steps to reproduce

1. Setup emacs-28 with native-compilation and default doom installation.
2. Add (python +lsp) to init.el file
3. Open a python script
4. Obtain the errors

`Error (python-mode-local-vars-hook): Error running hook "lsp!" because: (invalid-function lsp!)`

`Error (hack-local-variables-hook): Error running hook "doom-run-local-var-hooks-h" because: (doom-hook-error python-mode-local-vars-hook lsp! (invalid-function lsp!)) 
`

### System Information

https://pastebin.com/sh3e5dSe

**Comment by hlissner** [comment]
Enable the `:tools lsp` module.

To quote [the :lang python module's documentation](https://github.com/hlissner/doom-emacs/blob/develop/modules/lang/python/README.org#language-server-protocol-support):

> For LSP support the :tools lsp module must be enabled

**Comment by codicef** [comment]
Thank you very much, sorry for the question. I am trying emacs with native compilation and I missed that.
