### ISSUE TITLE
Straight doesn't compile biblio related packages enabled by `biblio` module

### ISSUE THREAD

**Issue by HyunggyuJang** [hlissner/doom-emacs#5354]
### What did you expect to happen?

When I enabled `biblio` module at `:tools` in `$DOOMDIR/init.el`, and refresh doom with `doom sync -u`, doom (actually straight) will clone bibliography related packages, here `bibtex-completion` and `bibtex-actions`, and build those by compiling them. Hence, the end result, the one under `straight-build-dir` should be compiled if no recipe designates not to.

### What actually happened?

Starting from `biblio` package, all the packages relying on which don&rsquo;t get compiled properly. Only `.el` files exist, or the files not depend on `bibilo`, or the subsequent ones, are properly compiled.

This can be observed by inspecting the build directory of doom&rsquo;s straight, which is by default `$DOOMLOCALDIR/straight/build-{version}/biblio` and or so.

### Describe your attempts to resolve the issue

First, I&rsquo;ve tried to clear whether this is doom specific issue or not, hence, built clean, vanilla emacs environment and built the same packages `biblio` module provides using straight.

Turns out, the files are all compiled correctly, with exactly same recipes.

Secondly, I&rsquo;ve made dedicated test bed for testing whether it comes from my gnarly tweaked doom configuration, and built clean doom environment, only enabling `biblio` module on top of vanilla doom configuration shipped by you.

Last, but not the least, I&rsquo;m considering to deep dive into related code but, unfortunately, I&rsquo;m running on my time, hence, not yet able to look into relevant code, but noticed that many hacks are done to make straight the right thing, like preventing `let-alist` to be cloned as it is shipped with the recent version of emacs, and so on.

### Steps to reproduce

1.  Clean installation of doom
2.  Enable `biblio` under `:tools` section in `$DOOMDIR/init.el`
3.  `doom sync -u` to install newly the enabled module
4.  Inspect the build directories: `$DOOMLOCALDIR/straight/build-{your-emacs-version}/biblio` `$DOOMLOCALDIR/straight/build-{your-emacs-version}/bibtex-completion` `$DOOMLOCALDIR/straight/build-{your-emacs-version}/bibtex-actions`
5.  You&rsquo;ll find uncompiled `.el` files after unhiding hidden files with `SPC m h`

### System Information

https://pastebin.com/gzNLBame

**Comment by bdarcus** [comment]
Is this relevant?

**Comment by HyunggyuJang** [comment]
> Is this relevant?

I guess it is more straight related configuration issue of doom side, rather than any specific packages; but cannot say with certain as I haven’t yet investigated what was the cause.

**Comment by bdarcus** [comment]
Sorry; I should have added "still". With recent update to the biblio module, do you still have the problem?

**Comment by HyunggyuJang** [comment]
Oh, I’ll recheck its liveness when I get back to my environment.

**Comment by HyunggyuJang** [comment]
I can confirm now all the biblio related packages are built properly to the byte code.
I'd like to investigate what was the crux of such issue and learn about the hacks around straight module; but since the issue I've posed gets cleared, I close this issue for now.
