### ISSUE TITLE
`+vertico/switch-workspace-buffer` does not sort by last visited time

### ISSUE THREAD

**Issue by ztlevi** [hlissner/doom-emacs#5366]
### Describe your request

I switched to vertico recently. I realized unlike `consult-buffer`, `+vertico/switch-workspace-buffer` does not sort buffer by last visited time, which makes switching inside a workspace harder.

@iyefrat Since you're the one who merge vertico package into doom, do you have any idea how to implement this?

Thanks!

### Briefly explain its use-case

try switching to a new buffer B from buffer A. `consult-buffer` will list buffer A as the second condidate, while  `+vertico/switch-workspace-buffer` does not.

**Comment by iyefrat** [comment]
Hmm. When running `consult-buffer` I get the buffers in alphabetical order. Do you get history sorting in doom?

**Comment by iyefrat** [comment]
I don't suppose there's any chance that updating doom solves this for you now (the vertico module has been updated).

**Comment by ztlevi** [comment]
@iyefrat Which commit does vertico introduce the order feature?

**Comment by iyefrat** [comment]
it's supposed to have it already, I'm not sure what's wrong with yous setup. But I can't troubleshoot it if your Doom is out of date. Can you run `doom upgrade`?

**Comment by ztlevi** [comment]
@iyefrat Thanks, I can verify `consult-buffer` is now order the buffers by recent used timestamp. But [+vertico/switch-workspace-buffer](https://github.com/hlissner/doom-emacs/blob/develop/modules/completion/vertico/autoload/workspaces.el#L31) does not. How can we make this function list buffers ordered by timestamp as well?

Thanks!

**Comment by iyefrat** [comment]
Hey, I found the source of this issue and fixed it. I'll add open a vertico improvements pr to doom in the next few days, which will close this issue once merged.

**Comment by j-minster** [comment]
Hey all, I have been doing `SPC `` (space-backtick) since moving to vertico. This calls `(evil-switch-to-windows-last-buffer)` which does what I want with 33% less keystrokes. (Compared to `SPC , RET`). Of course it would still be nice and logical to have the buffers sorted by their recent-used timestamp.
