### ISSUE TITLE
`consult-notmuch` raises the error `Symbol’s value as variable is void: consult-async-default-split`

### ISSUE THREAD

**Issue by brabalan** [hlissner/doom-emacs#5369]
### What package(s) should be bumped?

- consult-notmuch
- consult

### Why should Doom bump these packages early?

- The pinned version of `consult-notmuch` uses a void variable `consult-async-default-split`, this has been fixed in https://codeberg.org/jao/consult-notmuch/commit/b8d476f523abc97c2540a7cd66ff16875967cf42
- the current version of `consult-notmuch` needs a recent version of `consult` (I think since https://codeberg.org/jao/consult-notmuch/commit/a5133b9e1f19b6d51e51dd5c5e3a4f236ca29b57)

**Comment by gagbo** [comment]
Maybe handled by https://github.com/hlissner/doom-emacs/pull/5353 @iyefrat to confirm

**Comment by iyefrat** [comment]
It fixes half of it, but `consult-notmuch` still needs to be updated to work with the new async consult stuff. I'll push a fix for that too.
