### ISSUE TITLE
Add doom-quit message from Sid Meier's Alpha Centauri

### ISSUE THREAD

**Issue by norogoth** [hlissner/doom-emacs#5373]
### Describe your request

I would like an addition to the current set of exit messages. I would like a new message that says 

`please don't go; the drones need you; they look up to you`

This is a reference to Sid Meier's Alpha Centauri.

[source](https://www.youtube.com/watch?v=2FZNPxmTB4o)

If this is not a reference that the developer knows or cares about, just close the issue. I just think it would be funny.

### Briefly explain its use-case

(speaks for itself)

**Comment by hlissner** [comment]
Please remember to fill out the title when creating a new issue. Also, I'd welcome a PR to add this.
