### ISSUE TITLE
Keybinding conflict between iedit and embark

### ISSUE THREAD

**Issue by ajgrf** [hlissner/doom-emacs#5374]
### What did you expect to happen?

After switching from ivy to vertico, there should be no conflicts or errors in Doom.

### What actually happened?

The first time I open a file in a new Emacs instance (with `SPC f p` or `SPC h P`, for example, but *not* with `find-file`), I get a `*Warnings*` popup with the following message:

```
Warning (iedit): Iedit default key "C-;" is occupied by embark-act.
```

I'm guessing this message appears when something loads iedit for the first time, and that there are probably many ways to trigger it.

### Steps to reproduce

1. Open Emacs
2. Open a file with `SPC f p` or `SPC h P`

You can see my doom directory [here](https://github.com/ajgrf/dotfiles/tree/master/dot_config/doom).

### System Information

https://pastebin.com/ZPfpNTpY

**Comment by weidaolee** [comment]
You should try evil-multiedit, which is more powerful and elegant then iedit, and it also avoided the issue. Mark/select in normal mode, modify in insert/Emacs mode, good luck.

**Comment by ajgrf** [comment]
All I did was enable Doom's `:editor multiple-cursors` module, which includes both iedit and evil-multiedit. Since they're both in the Doom module, it's a Doom bug.

**Comment by ajgrf** [comment]
Actually, I can confirm that iedit is only used in Doom for evil-multiedit anyway. A simple `(setq iedit-toggle-key-default nil)` fixes the issue and is likely to only affect a small number of Doom users (those using `iedit` directly, and without vim bindings).

**Comment by hlissner** [comment]
This issue should now be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
