### ISSUE TITLE
`doom-reload` searches for config remotely while on remote projectile project

### ISSUE THREAD

**Issue by GiulioCentorame** [hlissner/doom-emacs#5378]
### What did you expect to happen?

Running `doom/reload`, even with a remotely-host project open, should reload the local Emacs config (independently if I am connected to something via Tramp or not)

### What actually happened?

While having an open project hosted on a remote, running `doom/reload` executes `doom sync` remotely through Tramp, instead of on the local Emacs installation

### Describe your attempts to resolve the issue

Currently, you have to change the project entirely before running `doom/reload` to work around this

### Steps to reproduce

0. Have a project on a remote, accessible through SSH
1. Open Emacs
2. `projectile-switch-project`
3. Select remote project and open any file/folder
4. `doom/reload`

### System Information

https://pastebin.com/akRnscjh

**Comment by hlissner** [comment]
As of 462bfb9 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
