### ISSUE TITLE
Can't use counsel-rg

### ISSUE THREAD

**Issue by drym3r** [hlissner/doom-emacs#538]
### Observed behavior

Describe what happened. Any aids you can include (that you think could be relevant) are a tremendous help; like a screencast gif, video, or link to your customizations for Doom (e.g. a repo or a pastebin).
When I execute `counsel-rg` or `counsel-ag` I get this error:

```
Advice to 1) get rid of the character limit from `counsel-ag-function' and 2)
disable ivy's over-zealous parentheses quoting behavior (if i want literal
parentheses, I'll escape them myself
```

### Expected behavior

It should work.
### Steps to reproduce

Jus execute `M-x counsel-rg`.

### System information

I use Debian. I can use `counsel-rg` in my main emacs configuration, so it shouln't be system related.

PD: Thanks for your work, doom seems very interesting!

**Comment by hlissner** [comment]
The most stable (at the moment) is the `develop` branch. Some mistakes were made planning out the 2.1 release, so it's taking longer than expected. Once 2.1 is released, `master` will be the stable branch (as it should be).

**Comment by drym3r** [comment]
It works, thanks!
