### ISSUE TITLE
Path completion generates partial path

### ISSUE THREAD

**Issue by ncihnegn** [hlissner/doom-emacs#5383]
### What did you expect to happen?

```:e ~/.doom.d/i TAB``` expands to ```:e ~/.doom.d/init.el```

### What actually happened?

It expands to ```:e .dinit.el```

### Describe your attempts to resolve the issue

No idea

### Steps to reproduce

1. Open Emacs
2. ```:e ~/.doom.d/i``` TAB ENTER
3. The line becomes ```:e .dinit.el```

### System Information

https://pastebin.com/a2BXLVhb

**Comment by iyefrat** [comment]
I can't reproduce this. you seem to have both the ivy module and the vertico module on at the same time. does only using one of them change anything?

**Comment by ncihnegn** [comment]
You are right. Disabling ivy fixes it.
