### ISSUE TITLE
`(org +pretty)` and `org-babel-markdown` make error `"org-fancy-priorities-mode" because: (wrong-type-argument number-or-marker-p nil)"`

### ISSUE THREAD

**Issue by hwiorn** [hlissner/doom-emacs#5391]
### What did you expect to happen?

When I write some mark-down block in an org file, Emacs should show fancy headings correctly.

### What actually happened?

Emacs occurs the below error.
```
Error (org-mode-hook): Error running hook "org-fancy-priorities-mode" because: (wrong-type-argument number-or-marker-p nil) Disable showing Disable logging

```

I found `gfm` and `markdown` make the same error.

```org
* Code 1
#+begin_src gfm
#+end_src
```

### Describe your attempts to resolve the issue

Since I have disabled `+pretty` feature, this error has gone.

### Steps to reproduce

1. Install a fresh doom
2. Enable `(org +pretty)` and `doom sync`
3. Write a Markdown code block and add some headings in an org file like below.
```org
* Code 1
- Logic 1
- Logic 2
  + Sub Logic 3
#+begin_src markdown
#+end_src
** Sub Code block 2
```
4. Save and reload the org file.

### System Information

https://pastebin.com/yhpMmSPC

**Comment by hlissner** [comment]
Sorry for the late response. This is a known issue with org-fancy-priorities-mode and org-superstar-mode, both assume that font-locking _isn't_ deferred, but Emacs will typically defer it in larger buffers (which org buffers tend to be).

See if this fixes the issue:

```elisp
;; add to $DOOMDIR/config.el
(defadvice! shut-up-org-problematic-hooks (fn &rest args)
  :around #'org-fancy-priorities-mode
  :around #'org-superstar-mode
  (ignore-errors (apply orig-fn args)))
```

**Comment by hwiorn** [comment]
@hlissner Is it fixed latest doom? I updated doom just now. I can't find any errors without fixing it.

Your fixes seem not to make `org-fancy-priorities-mode` and `org-superstar-mode` work. It is like disable the `+pretty` feature.

I think this issue has gone. But I don't know what fixes solved this issue.

**Comment by hlissner** [comment]
I have not fixed the issue, but if the issue has gone away on its own, then I'll assume it was addressed upstream at some point and close this. Let me know if it returns.
