### ISSUE TITLE
Conflicting envvar values between `doom/reload` and `doom/reload-env`

### ISSUE THREAD

**Issue by pard68** [hlissner/doom-emacs#5399]
### What did you expect to happen?

When `doom sync` or `doom/reload` is called, I expect that my PATH will be properly loaded into the envvar vaue.

### What actually happened?

When `doom sync` or `doom/reload` is called, I am getting an alternative PATH loaded.

When I reload/sync and and then in `ielm` I run `(exec-path)` I get the following output:
```
("/usr/bin" "/bin" "/usr/sbin" "/sbin" "/usr/local/Cellar/emacs-plus@28/28.0.50/libexec/emacs/28.0.50/x86_64-apple-darwin20.4.0")
```

On MacOS with Brew, this means nearly none of my executables will actually work. I can resolve this by running `doom/reload-env` which properly loads my correct PATH and can be seen to work by running `(exec-path)` which shows:
```
("/Users/USER_NAME/.emacs.d/bin/" "/Users/USER_NAME/.cargo/bin" "/Users/USER_NAME/go/bin" "/Users/USER_NAME/.local/bin" "/Users/USER_NAME/bin" "/usr/local/bin" "/usr/bin" "/bin" "/usr/local/sbin" "/usr/lib/jvm/default/bin" "/usr/bin/site_perl" "/usr/bin/vendor_perl" "/usr/bin/core_perl" "/usr/bin/core_perl" "/usr/local/go/bin/" "/usr/local/go/bin/" "/Users/USER_NAME/.emacs.d/bin/" "/usr/local/Cellar/emacs-plus@28/28.0.50/libexec/emacs/28.0.50/x86_64-apple-darwin20.4.0/")
```

### Describe your attempts to resolve the issue

I thought perhaps this was because of Fish. I changed my default shell to zsh and got the same problem. I also tried sh and bash.

My PATH is consistent across sh, bash, zsh, and fish. I can run `[sh|bash|zsh|fish] -c "echo $PATH"` and it is the same as `[sh|bash|zsh|fish] -i -c "echo $PATH"`.

I noticed a few similar issues, but none of them mention the envvar changing based on whether or not a reload was run.

### Steps to reproduce

1. run `doom sync`
2. open emacs
3. wait for zstd to fail to load

### System Information

https://pastebin.com/raw/tZc628g4

**Comment by ThomasFKJorna** [comment]
I have the exact same issue, but this results in almost no external program working. I frequently get errors that some package cannot find basic things such as node or R, while those are available on my path.

**Comment by hlissner** [comment]
This issue should now be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by ThomasFKJorna** [comment]
Fantastic, that fixed it for me!
