### ISSUE TITLE
C-u org-open-at-point / org-open-at-mouse doesn't open the file link in a new window.

### ISSUE THREAD

**Issue by AlessandroW** [hlissner/doom-emacs#5413]
### What did you expect to happen?

Clicking <kbd>mouse-3</kbd> or <kbd>C-u</kbd><kbd>C-c</kbd><kbd>C-o</kbd> (`org-open-at-point`) opens the file link at point in a new window in vanilla emacs. I expected this to work in Doom Emacs as well.

### What actually happened?

The file/buffer opens in the same window.

### Describe your attempts to resolve the issue

- I checked that `org-open-at-mouse` and `org-open-at-point` is also called in Doom Emacs and not something else using `describe-key`.
- There are no changes to these functions in Doom Emacs.
- I searched for related issues.

### Steps to reproduce

Given the files `test.org`
```
#+TITLE: Test1

[[file:test2.org]]
```
and `test2.org`
```
#+TITLE: Test2
```
When you have the point on the file link in `test.org` and click  <kbd>mouse-3</kbd> or <kbd>C-u</kbd><kbd>C-c</kbd><kbd>C-o</kbd> then the file opens in the same window instead of a new window.

### System Information

https://pastebin.com/T629SKZx

**Comment by hlissner** [comment]
Not a bug, just [a different default](https://github.com/hlissner/doom-emacs/blob/develop/modules/lang/org/config.el#L622).

To undo it:

```elisp
(after! org
  (setf (alist-get 'file org-link-frame-setup) #'find-file-other-window))
```

**Comment by AlessandroW** [comment]
@hlissner Thanks for the quick reply. Unfortunately, that is not the case (if I'm not mistaken). Following your solution *every* file link is opened in a new window. The default is that the link is opened in the same window when using `org-open-at-point` without prefix. See [org-open-at-point](https://orgmode.org/manual/Handling-Links.html#Handling-Links)

**Comment by hlissner** [comment]
This may have been changed in a later version of org (which isn't reflected in its old docs). This is from `org-open-at-point`'s docstring:

> When point is on a link, follow it.  Normally, files will be
> opened by an appropriate application.  If the optional prefix
> argument ARG is non-nil, Emacs will visit the file.  With
> a double prefix argument, try to open outside of Emacs, in the
> application the system uses for this file type.

No mention of "other-window" behavior when the prefix arg is provided.

**Comment by AlessandroW** [comment]
I tested it in vanilla emacs and org version 9.5 and there it works, only in Doom it doesn't. How can I track this down?

**Comment by hlissner** [comment]
Just tried it in vanilla. `C-u` or `C-u C-u` does not change `org-open-at-point`'s behavior. 

With `(setf (alist-get 'file org-link-frame-setup) #'find-file)`, it always opens in the same window.

Without it, it always opens in another window.

Perhaps you're on an older commit of Emacs 28 (with an older commit of Org 9.5).

**Comment by AlessandroW** [comment]
Weird.. you are right. I cannot reproduce it anymore; it always opens in a new window and your solution "fixes" it in Doom. Thanks for the quick response.

Can you give me an advice how I can restore this functionality again? It is quite handy when working with multiple references and a main document in org.

**Comment by hlissner** [comment]
If you throw this into `~/.doom.d/config.el`, it should make `org-open-at-point` behave the opposite as `org-link-frame-setup` dictates when the prefix arg is given:

```lisp
(defadvice! open-link-in-other-window (fn &optional arg)
  :around #'org-open-at-point
  (let ((org-link-frame-setup org-link-frame-setup))
    (when arg
      (push (cons 'file
                  (let ((last-method (alist-get 'file org-link-frame-setup)))
                    (if (eq last-method 'find-file)
                        #'find-file-other-window
                      #'find-file))
                  org-link-frame-setup)))
    (apply fn args)))
```
