### ISSUE TITLE
Keybinding d d broken

### ISSUE THREAD

**Issue by azy2** [hlissner/doom-emacs#542]
When I press `d d` in evil normal mode the echo area prints `Quit` and the line does not get deleted.

**Comment by hlissner** [comment]
I am unable to reproduce this.

The only recent change that could cause this are:

```elisp
;; core/core-keybinds.el
(setq which-key-allow-evil-operators t
        which-key-show-operator-state-maps t)
```

Try setting these to nil, and let me know if that resolves your issue.

**Comment by azy2** [comment]
I'm very busy for the next couple of weeks so I'll just stay on a known good commit and when I'm less busy I'll pull the latest. If the bug is still around I'll come back to this. Feel free to close it if you want. I'll reopen another issue if I can't figure it out then.

**Comment by azy2** [comment]
I am on b52a258 currently.

**Comment by azy2** [comment]
Setting `which-key-allow-evil-operators` and `which-key-show-operator-state-maps` to `nil` in my config corrects this problem.

**Comment by hlissner** [comment]
I've reverted the change to those two which-key variables, which should resolve your issue. Let me know if that isn't the case.
