### ISSUE TITLE
org-mode capture error

### ISSUE THREAD

**Issue by Kakupakat** [hlissner/doom-emacs#5421]
### What did you expect to happen?

Adding the following to config.el should create a capture template.

```
(after! org
  (add-to-list 'org-capture-templates
             '(("d" "Dream" entry
               (file+headline +org-capture-todo-file "Dream")
               "* TODO %?\n :PROPERTIES:\n :CATEGORY: dream\n :END:\n %i\n"
               :prepend t :kill-buffer t)))
)
```

### What actually happened?

After pressing SPC X the following error message appears:

```
Wrong type argument: strinp, ("d" "Dream" entry (file+headline +org-capture-todo-file "Dream") "* TODO %? 
  :PROPERTIES:
  :CATEGORY: Dream
  :END:
  %i
  " :prepend t :kill-buffer t)
```

### Describe your attempts to resolve the issue

I think the problem lies with `file+headline`.

### Steps to reproduce

Add the code as above to config.el, then press SPC X.

### System Information

https://pastebin.com/BEbQsWHC

**Comment by king-gheedorah** [comment]
Experiencing same issue here

**Comment by Kakupakat** [comment]
Yes, changing "add-to-list" to "setq" does something, but now the error is:

`Wrong type argument: symbolp 'org-capture-templates`

**Comment by progfolio** [comment]
Each element of `org-capture-templates` should be a list.
When you `add-to-list` you're adding a list with a single template to that list, resulting in the following value for `org-capture-templates`:

```emacs-lisp
((("d" "Dream"))) ;etc
```
`org-capture` throws a wrong-type error because it's taking the first element of that list and trying to parse it as a capture template (which it expects the first element to be a string):

Removing the surrounding list from your capture template should work as expected. e.g.

```emacs-lisp
(after! org
  (add-to-list 'org-capture-templates
               '("d" "Dream" entry
                  (file+headline +org-capture-todo-file "Dream")
                  "* TODO %?\n :PROPERTIES:\n :CATEGORY: dream\n :END:\n %i\n"
                  :prepend t :kill-buffer t)))
```

**Comment by Kakupakat** [comment]
Thank you!

That worked when adding to the list. To overwrite the list the following works:

``` elisp
(after! org
 (setq org-capture-templates
              '(("d" "Dream" entry
                 (file+headline "dream.org" "Dream")
                 "* TODO %?\n :PROPERTIES:\n :CATEGORY: dream\n :END:\n %i\n"
                 :prepend t :kill-buffer t))))

```
