### ISSUE TITLE
missing magit-section dependency

### ISSUE THREAD

**Issue by bboozzoo** [hlissner/doom-emacs#5435]
### What did you expect to happen?

Things work, I can open files etc.

### What actually happened?

Clean pull & install. Upon opening Emacs, any attempt to open a file fails. Messages is filled with:

```
Failed to load magit package incrementally, because: (file-missing Cannot open load file No such file or directory magit-section)
Failed to load org package incrementally, because: (file-missing Cannot open load file No such file or directory magit-section)
Failed to load org-agenda package incrementally, because: (file-missing Cannot open load file No such file or directory magit-section)
Failed to load org-capture package incrementally, because: (file-missing Cannot open load file No such file or directory magit-section)
Failed to load org package incrementally, because: (file-missing Cannot open load file No such file or directory magit-section)
condition-case: Error in a Doom startup hook: doom-first-file-hook, global-git-commit-mode, (file-missing "Cannot open load file" "No such file or directory" "magit-section")
```

The revision I have is bf8495b4122701fb30cb6cea37281dc8f3bedcd0

### Describe your attempts to resolve the issue

Added `(package! magit-section)` to packages, ran `doom sync`, things worked again.

### Steps to reproduce

1. git clone && doom install && doom sync
2. start Emacs
3. observe you can't really open any file/directory
4. switch to messages buffer

### System Information

https://paste.ubuntu.com/p/SFfYv9ZXC2/

**Comment by iyefrat** [comment]
1. Is this still an issue on the latest version of doom? I've clean installed doom since and I didn't reproduce this.
2. If this is still an issue, can you post a pastebin to a website that doesn't require login to view?

**Comment by bboozzoo** [comment]
Seems to be working with the latest master, i.e. cdb59b0a3d3e20f37df6fdb5a68c7c8090c9c25d. I see that there were a couple of commits touching magit, so maybe the dependencies are correct now. Anyways, the problem appears to be gone. Thanks!
