### ISSUE TITLE
~/.emacs.d/bin/org-capture fails with *ERROR*: Unknown terminal type

### ISSUE THREAD

**Issue by gueorgui** [hlissner/doom-emacs#5438]
### What did you expect to happen?

When I run:
```sh
org-capture -k n "To the mind that is still, the whole universe surrenders."
```
I expect a new Emacs frame to open with an org capture prompt.

### What actually happened?

The command fails with:
```sh
~/.emacs.d/bin$ ./org-capture -k n "To the mind that is still, the whole universe surrenders."
*ERROR*: Unknown terminal type
```

### Describe your attempts to resolve the issue

I thought this was because I use a non-standard shell (fish), so I tried running the same command from a `bash` shell. The outcome was the same.

### Steps to reproduce

1. Open a terminal
2. Change directory to `~/.emacs.d/bin` (if it's not in your PATH)
3. Run `org-capture`

### System Information

https://pastebin.com/QbShTSyt

**Comment by david-janssen** [comment]
Getting the same issue, using `alacritty`. Have tried manually setting `TERM` to either `linux` or `xterm-256color` without success. For me the command works perfectly as long as there is at least 1 emacs frame open, but when I'm running only the daemon without any clients I get the `Unknown terminal type` error.

**Comment by al23212321** [comment]
The issue seems to be with `if ! emacsclient --suppress-output --eval nil; then` on line 17. When the code `emacsclient --eval nil` via the terminal, `nil` is printed. However, when an emacs daemon is running in the background, the script will return `false` to the conditional statement. 
Thus,`  emacsclient -c -a "" \
    -e "(+org-capture/open-frame \"$str\" ${key:-nil})"
` is run but without any open frame, there `Unknown terminal type`

**Comment by ShahinSorkh** [comment]
I managed to work around this issue by adding the following snippet to my `config.el`:

```elisp
(after! org
  (setq +org-capture-frame-parameters
        `((name . "doom-capture")
          (width . 70)
          (height . 25)
          (transient . t)
          ,(when IS-LINUX
             `(display . ,(or (getenv "DISPLAY") ":0")))
          ,(if IS-MAC '(menu-bar-lines . 1)))))
```

Thanks to [Gilles great explanation](https://unix.stackexchange.com/a/119891/296839).

As far as I understand, `+org-capture/open-frame` calls `make-frame` which causes the error message `*ERROR*: Unknown terminal type` when an emacs daemon is running **and** no GUI frames already exists. Seems like you need to specify `display` parameter explicitly. It doesn't read from env even though `emacsclient -a '' -e '(getenv "DISPLAY")'` returns the correct display identifier.

**Comment by hlissner** [comment]
This issue should now be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by gueorgui** [comment]
Thank you for taking the time to fix this!
