### ISSUE TITLE
Pandoc option --parse-raw has been removed, causing an error during org exports

### ISSUE THREAD

**Issue by jackbaty** [hlissner/doom-emacs#544]
I've been getting an error ("Invalid Option: --parse-raw") when trying to export org-mode files via pandoc.

Best I can tell, this is caused by the following:

https://github.com/hlissner/doom-emacs/blob/8c4e6a267d8a61d917813eee714816347331c322/modules/lang/org/%2Bexport.el#L16

From the [Pandoc release notes](http://pandoc.org/releases.html):

> Removed --parse-raw and readerParseRaw. These were confusing. Now we rely on the +raw_tex or +raw_html extension with latex or html input. Thus, instead of --parse-raw -f latex we use -f latex+raw_tex, and instead of --parse-raw -f html we use -f html+raw_html.

**Comment by hlissner** [comment]
You're right. I've updated `org-pandoc-options` accordingly on `develop`. I'll keep this issue open until it hits `master`. Thanks for letting me know!
