### ISSUE TITLE
Elixir: Support new heex file template

### ISSUE THREAD

**Issue by aswinmohanme** [hlissner/doom-emacs#5442]
### Describe your request

Elixir and Phoenix now has switched to a better version of eex templates `heex` templates, it would be nice to support that too in web-mode.

### Briefly explain its use-case

1. Install Doom Emacs
2. Enable Elixir Layer
3. Open Phoenix Project
4. Open Phoenix heex file
5. Heex file get recognized as web-mode and as elixir as engine.

**Comment by hlissner** [comment]
This issue should now be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
