### ISSUE TITLE
IRC module should have company-mode disabled

### ISSUE THREAD

**Issue by createyourpersonalaccount** [hlissner/doom-emacs#5451]
### What did you expect to happen?

Two separate issues:
- I did not expect company-mode to autocomplete words when I use IRC.
- I expect the IRC module documentation to mention [circe](https://github.com/emacs-circe/circe) in the very beginning.

### What actually happened?

- company-mode autocompletes words while I chat on IRC.
- it was hard to find out which irc client was used in the irc module.

### Describe your attempts to resolve the issue

For the issue of company-mode running in IRC, I believe the fix can be inserted here,

https://github.com/hlissner/doom-emacs/blob/bf8495b4122701fb30cb6cea37281dc8f3bedcd0/modules/completion/company/config.el#L10-L19

with an addition of `circe-mode`.

For the issue of circe being mentioned, I would edit the documentation.

### Steps to reproduce

Enable the IRC module and connect with `M-x circe` to a network, join a channel and type some things, you will see a completion from company-mode. 

### System Information

https://pastebin.com/mSpkH1Tm

**Comment by createyourpersonalaccount** [comment]
I could try to fix these issues and submit a PR if someone can verify that I have correctly identified them & the solution.

**Comment by hlissner** [comment]
Rather than disable company altogether, can we replace the backend with something more useful? Say, a backend that can offer completion of nicks and/or rooms?

**Comment by createyourpersonalaccount** [comment]
> Rather than disable company altogether, can we replace the backend with something more useful? Say, a backend that can offer completion of nicks and/or rooms? (Assuming such a backend exists)

Tab already completes nicks for me with company-mode disabled. Not sure about channels, but maybe that is not so important...

**Comment by hlissner** [comment]
Sorry for the long wait! This issue should now be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by createyourpersonalaccount** [comment]
I doom upgraded and synced, but I still have company-mode activated after using `M-x circe`.
## System Information
https://pastebin.com/pq5xWPxH
