### ISSUE TITLE
mu4e main view shows a medium black circle emoji instead of an asterisk

### ISSUE THREAD

**Issue by selectric401** [hlissner/doom-emacs#5452]
### What did you expect to happen?

By default, mu4e shows an asterisk for list entries (such as for each bookmark or maildir). The asterisk is shown in a default face, so that it matches other text elements and isn't hard to discern from the background.

### What actually happened?

Each asterisk in mu4e-main is replaced with a black circle emoji (⚫, U+26AB MEDIUM BLACK CIRCLE), by the functions `mu4e~main-action-str-prettier-a` and `mu4e~main-keyval-str-prettier-a` by the file `modules/email/mu4e/autoload/advice.el`. In a terminal (for example, iTerm 2 on a Macintosh) that has support for emoji, this is hard to see on a dark background, and also doesn't really match the rest of the view.

My Linux desktop, meanwhile, shows a small bullet point instead of the graphical emoji -- I suspect that this is due to it not having the correct fonts installed/configured, and isn't because of anything happening in emacs. When I run `what-cursor-position` over the character, it tells me that it is indeed MEDIUM BLACK CIRCLE.

This feature should, in my view, be configurable so that it can be disabled or easily replaced. If I've missed an obvious way to do that already, my apologies!

### Describe your attempts to resolve the issue

I was able to manually change the character shown by changing this function, as well as `mu4e-main-action-str-prettier-a`.

```
(defun +mu4e~main-keyval-str-prettier-a (str)
   "Replace '*' with '•' in STR."
   (replace-regexp-in-string "\t\\*" "\t•" str))
```

### Steps to reproduce

1. Open Emacs
2. Start mu4e
3. Observe the bookmarks and action listings

### System Information

https://pastebin.com/cfY7x7cK

**Comment by tecosaur** [comment]
Yea, making the character configurable seems like a good idea. I'll make a PR for that at some point.

**Comment by iyefrat** [comment]
I will say that having this black circle seems to at least partially be an emoji fallback font issue (which I'm also having at the moment). It should™ be a unicode bullet. Are you also getting odd emoji stuff in the threading characters in the heading view?

**Comment by selectric401** [comment]
I don't see any odd emoji behaviour in the threading characters, no. I undid my changes to `advice.el` to take some screenshots -- the Konsole screenshot is the machine that doom-emacs is installed on, and the iTerm (Mac) screenshot is the computer i frequently SSH from to use this particular emacs install. For completion's sake, I've also added a screenshot from opening emacs in graphical mode on the same Linux machine. 

`advice.el` definitely shows the emoji itself, which would indicate that I'm getting a more advantageous (from my perspective) moji fallback issue on Linux (which makes sense, I definitely don't have full emoji support on that machine in KDE).

![Screenshot_20210905_143831](https://user-images.githubusercontent.com/13787773/132137797-1b647255-2448-4bb9-b6c5-9588b80e269b.png)
![image](https://user-images.githubusercontent.com/13787773/132137768-467503c2-af92-40df-964a-fcc1ee0291d4.png)
![Screenshot_20210905_144236](https://user-images.githubusercontent.com/13787773/132137915-d5ae414d-e324-46b5-8246-3cfdb37714f2.png)
