### ISSUE TITLE
Automatically (offer to) purge and rebuild nativecomp artifacts when comp-native-version-dir changes

### ISSUE THREAD

**Issue by telotortium** [hlissner/doom-emacs#5461]
### Describe your request

See https://github.com/hlissner/emacs-doom-themes/issues/655#issuecomment-914520115 for background.

You can get all sorts of strange errors after upgrading Emacs and trying to use any build artifacts from the previous build (see https://github.com/hlissner/emacs-doom-themes/issues/655, https://github.com/hlissner/doom-emacs/issues/5459). The only sure fix I've found is

1. Running `rm -rf ~/doom.emacs.dir/.local/straight/build*`.
2. Running `doom sync -p`.

It would be nice to automate these steps, perhaps by detecting whether old nativecomp artifacts exist and prompting to remove them and rebuild everything (or just automatically doing so).

### Briefly explain its use-case

1. Upgrade Emacs (or possibly OS).
2. Have Doom work without any trouble.

**Comment by hlissner** [comment]
This is planned for our CLI rewrite, so I've moved this to #4273. Thanks for bringing it to my attention!
