### ISSUE TITLE
Cannot start LSP on html erb mode

### ISSUE THREAD

**Issue by otavioschwanck** [hlissner/doom-emacs#5464]
### What did you expect to happen?

When entering on html.erb, have html LSP

### What actually happened?

A buffer with a lot of repeated messages with:

Warning (lsp-mode): Unable to calculate the languageId for buffer ‘index.html.erb’. Take a look at ‘lsp-language-id-configuration’. The ‘major-mode’ is web-mode

### Describe your attempts to resolve the issue

i run doom doctor and install all dependencies

### Steps to reproduce

Open an html.erb file from a rails project.

### System Information

https://pastebin.com/nKQVG9F1

**Comment by hlissner** [comment]
lsp-mode does not support web-mode out of the box. If you want it to, your best bet is to request it [upstream](https://github.com/emacs-lsp/lsp-mode), or by registering the language yourself in `lsp-language-id-configuration` (see [the lsp-mode docs](https://emacs-lsp.github.io/lsp-mode/page/adding-new-language/)).

As this is not a Doom issue I will close this.
