### ISSUE TITLE
Toolbar shows despite `tool-bar-mode` being disabled in `emacs-app-devel` MacPorts build of Emacs

### ISSUE THREAD

**Issue by catap** [hlissner/doom-emacs#5469]
### What did you expect to happen?

I expect that emacs won't have toolbar when it started, like it did before.

### What actually happened?

![Screenshot 2021-09-11 at 15 17 51](https://user-images.githubusercontent.com/37775/132954160-b0f5445a-55f8-4db8-a3c5-e7565bceeab4.png)

### Steps to reproduce

This issue happened after upgrading emacs via MacPorts. I'm using `emacs-app-devel` and after to last git master the issue appears: https://github.com/macports/macports-ports/commit/2497386d233bdbd153d7049196e1a5cc07c20f15

Wired things, that if I `Enter full screen` at emacs — toolbar disappear. When I move back — it keeps to be disappeared.

### System Information

https://pastebin.com/Z4j42wd6

**Comment by hlissner** [comment]
I do not have access to a macOS machine, but `tool-bar-mode` is disabled [here](https://github.com/hlissner/doom-emacs/blob/develop/core/core-ui.el#L308) and this appears to work fine in the emacs-plus and emacs-mac homebrew formulas for macOS, so I suspect this is a emacs-app-devel packaging issue, rather than a Doom issue.

I'll have to wait until a macos user with insight can chime in on the matter.

**Comment by catap** [comment]
@hlissner I guess you're looking for me because I'm a person who updated MacPorts ;)

It is original emacs with one small patch https://github.com/macports/macports-ports/blob/master/editors/emacs/files/site-start.el to make it compatible with MacPorts way to install something.

**Comment by catap** [comment]
The only way that I see right now is `git bisect` and find the exact commit which broke it. But it required to recompile emacs and doom  for about ~8 times.

So, if you share any clue I'll be very appricieted :)

**Comment by catap** [comment]
I'd like to confirm that this isn't doom-emacs bug at all. The issue is related to emacs sources itself. A bit more than a month ago the upstream had changes that includes changing NS port resize detection and window handling which seems a root cause.
