### ISSUE TITLE
Fast key presses of k and then j causing an exit of input mode

### ISSUE THREAD

**Issue by rako233** [hlissner/doom-emacs#5471]
### What did you expect to happen?

I'm expecting Emacs is not leaving input mode

### What actually happened?

Fast key presses of k and then j causing an exit of input mode

### Steps to reproduce

1. Open Emacs 
2. Create a new buffer
3. Start input mode with i
4.  Put fast the key sequence of jkjkjkjkjkjkj into Emacs

### System Information

https://pastebin.com/Nedc18GV

**Comment by hlissner** [comment]
See https://github.com/hlissner/doom-emacs/issues/4059#issuecomment-705995804
