### ISSUE TITLE
Org-Latex-Export-To-LaTeX Fail To Handle Code Blocks When Specifying Prog-Lang

### ISSUE THREAD

**Issue by M1ndo** [hlissner/doom-emacs#5472]
### What did you expect to happen?

Producing a proper pdf file with code block and highlighting.

### What actually happened?

when exporting from org to latex, it does produce well formated tex file , however that's not how it goes for code blocks .
if we specified prog-language name after #+BEGIN_SRC , e.g:
![image](https://user-images.githubusercontent.com/44820142/132987127-2801fc13-4b7f-4712-91c7-85c63f584de1.png)
And Export it to latex , it adds [] like below
![image](https://user-images.githubusercontent.com/44820142/132987171-d9871a79-34b4-4789-a8f8-6dc713d14d65.png)
which if we then compile it to pdf, it doesn't show the code block
![image](https://user-images.githubusercontent.com/44820142/132987288-c088cdf4-0cc8-45cf-a7e3-4059478d8bd1.png)

### Describe your attempts to resolve the issue

1 - if we remove [] manually , and then compile it . it produces the following correct pdf.
however it is stressful and requires removing [] everytime you export to latex.
![image](https://user-images.githubusercontent.com/44820142/132987295-1b29a677-1c37-4bbc-ab91-f30a121eb954.png)

2 - if we remove prog-language after #+BEGIN_SRC, it will show the code blocks, however without code highlighting since minted cannot determine which language it is thus will not not work .

### Steps to reproduce

1. Open Emacs
2. Set The Following Lines in Ur Config
```lisp
(require 'ox-latex)
(setq org-latex-listings 'minted)
```
3. Open Your Org File And Set.
```org
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [letterpaper]
#+LATEX_HEADER: \usepackage{minted}
... snip...
#+BEGIN_SRC lisp
  (defun Fib (n)
    (if (< n 2) n (+ (Fib (- n 1)) (Fib (- n 2)))))
#+END_SRC
```
4. run org-latex-export-to-latex or org-latex-export-to-pdf and see

### System Information

https://pastebin.com/EWwmfRYu

**Comment by tecosaur** [comment]
Please verify that this is a Doom-specific issue by attempting to reproduce with `emacs -Q`. If it is not, you'd be best off reporting this as a Org bug.

**Comment by M1ndo** [comment]
Apparently, this also can be reproduced with `emacs -Q`

**Comment by M1ndo** [comment]
*Minted* uses *pygments* which requires ```-shell-escape``` when compiling to pdf .
This Issue can be fixed with the following.
```
  (setq org-latex-pdf-process
        '("pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f"
          "pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f"
          "pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f"))
```
