### ISSUE TITLE
straight.el installing error

### ISSUE THREAD

**Issue by nicholasglazer** [hlissner/doom-emacs#5473]
### What did you expect to happen?

emacs doom will install dependencies

### What actually happened?

 ~/.emacs.d/bin/doom install
> Installing straight...
x There was an unexpected error
  Message: File is missing
  Data: (file-missing . "Cannot open load file")
  Backtrace:
    (require straight "/home/nicholas/.emacs.d/.local/straight/repos/straight.
    (let ((repo-dir (doom-path straight-base-dir "straight/repos/straight.el")
    (doom--ensure-straight (:host github :repo "raxod502/straight.el" :branch 
    (let* ((--cl-rest-- (alist-get 'straight packages)) (recipe (car (cdr (pli
    (let ((packages (doom-package-list nil 'core))) (let* ((--cl-rest-- (alist
    (progn (if doom-debug-p (progn (let ((inhibit-message (active-minibuffer-w
    (if (or force-p (null (and (boundp 'straight-recipe-repositories) straight
    (doom-initialize-core-packages)
    (eval-buffer #<buffer  *load*-204652> nil "/home/nicholas/.emacs.d/core/co
    (load-with-code-conversion "/home/nicholas/.emacs.d/core/core-cli.el" "/ho
! Extended backtrace logged to .emacs.d/.local/doom.error.log
No catch for tag: exit, 255

### Describe your attempts to resolve the issue

rm -rf ./emacs.d
and clone it again.
all possible doom commands.

### Steps to reproduce

clean install 
git clone --depth 1 https://github.com/hlissner/doom-emacs ~/.emacs.d
~/.emacs.d/bin/doom install

### System Information

not possible

**Comment by hlissner** [comment]
Sounds like a failure while cloning/building straight. 

```sh
rm -rf ~/.emacs.d/.local/straight
~/.emacs.d/bin/doom install
```

**Comment by nicholasglazer** [comment]
> Sounds like a failure while cloning/building straight.
> 
> ```shell
> rm -rf ~/.emacs.d/.local/straight
> ~/.emacs.d/bin/doom install
> ```
> 
> Make sure you have Git 2.23+ installed before doing this.

Git version is 2.33

After removing straight and install command nothing changed

**Comment by hlissner** [comment]
I can't reproduce it. Try simply cloning it manually then:

```sh
rm -rf ~/.emacs.d/.local/straight/repos/straight.el
git clone https://github.com/raxod502/straight.el ~/.emacs.d/.local/straight/repos/straight.el
doom install
```
