### ISSUE TITLE
menubar and toolbar enabled in emacs-plus@28 native comp

### ISSUE THREAD

**Issue by shivahnshankar** [hlissner/doom-emacs#5477]
### What did you expect to happen?

toolbar and menubar are hidden by default

### What actually happened?

<img width="1786" alt="Screenshot 2021-09-14 at 12 40 13 PM" src="https://user-images.githubusercontent.com/8016298/133211786-e510e63d-ecf3-4377-8447-ef913141e2b8.png">

### Describe your attempts to resolve the issue

They can be toggled off manually of course but like in Emacs stable 27.2, it should be hidden by default.

### Steps to reproduce

1. Install Emacs using `emacs-plus@28` --with-native-comp`
2. Install doom
3. Start Emacs. Menubar and toolbar appears

### System Information

https://pastebin.com/DFK2K6ez

**Comment by hlissner** [comment]
See https://github.com/hlissner/doom-emacs/issues/5469
