### ISSUE TITLE
Company: frontend company-box-frontend error "Wrong type argument: window-live-p, nil" on command show

### ISSUE THREAD

**Issue by gueorgui** [hlissner/doom-emacs#5481]
### What did you expect to happen?

I am writing a note in `org-roam` v2, and I have completion enabled with:

```elisp
(setq org-roam-completion-everywhere t)
```

When I type a word that matches the name of another existing Roam node, I expect a Company completion popup to appear to allow me to create a link to that node.

### What actually happened?

No company popup appears. Instead, this error message is printed:
```
Company: An error occurred in auto-begin
Company: frontend company-box-frontend error "Wrong type argument: window-live-p, nil" on command show
```

### Describe your attempts to resolve the issue

This might be related to these issues:
- hlissner/doom-emacs#4000
- sebastiencs/company-box#111

The fix in hlissner/doom-emacs@15d9761 did not seem to solve this issue.

### Steps to reproduce

1. Open a new frame, then close it.
2. Open an org-roam v2 note
3. Start typing words that match the title of another note

### System Information

https://pastebin.com/SAmN5wLu

**Comment by hlissner** [comment]
`company-box` was bumped in https://github.com/hlissner/doom-emacs/commit/27e1ed7383d6377d16d7f03a38aaae0e2fbf73f6. Please update Doom and let me know if your issue persists.

**Comment by gueorgui** [comment]
Thank you for the response! I've updated Doom and tried again, and the same behaviour persists.

One thing that I have noticed is new (though I'm not sure if it's new after the update or if it had been the case previously as well) is that if I open a new frame, Company works correctly again in the new frame (but is still broken in the original frame).
