### ISSUE TITLE
No feedback while error checker is running

### ISSUE THREAD

**Issue by beojan** [hlissner/doom-emacs#549]
While the error checker is still running, the error indication continues to reflect the old version of the file. If it changed to some working indicator, it would reduce confusion.

**Comment by hlissner** [comment]
You're referring to the modeline indicator, right? I'm not entirely sure what you're describing, but I've refactored the flycheck segment. Let me know if that resolves your issue.

**Comment by beojan** [comment]
Yes, it works now. Though it could do with a little more padding on the right, so it doesn't get cutoff.

**Comment by hlissner** [comment]
@beojan Does it still get cut off? With the exception of buffers with long path names, the flycheck symbol should not be short of padding on the right.

![image](https://user-images.githubusercontent.com/510883/40880812-0f2613cc-66b8-11e8-8d88-f21cd80c33bd.png)

**Comment by beojan** [comment]
Seems fine now.
