### ISSUE TITLE
embark-action interprets +vertico/find-file-in wrongly

### ISSUE THREAD

**Issue by kuppo** [hlissner/doom-emacs#5494]
### What did you expect to happen?

I really don't know where is the suitable place to report this one, since you used both and I think it is better to report it here.

I use vertico with embark. When using `doom/find-file-in-private-config` (key binding `SPC f p`) and `+default/find-file-under-here` (key binding `SPC f F`), if I run `embark-act` on one of the candidates, e.g. running `delete-file`, the action would apply on the wrong file. It only applies on the file name (or I can say the file name string) itself and doesn't include the full path, which will fail on the action without any warning.

### What actually happened?

I would expect the `embark-act` on the file rather than on the file name string.

### Describe your attempts to resolve the issue

The problem is from `+vertico/find-file-in`, it doesn't return the full path.

### Steps to reproduce

1. Build a test hierarchy., such as `~/test/test.txt`.
2. Open scratch buffer, enter `(+vertico/find-file-in "~/test/")`. Eval the line, it will prompt for input
3. Run `embark-act` on candidate `test.txt`. You will see from the prompt, the action's orig-target is just the file string "test.txt" itself.
4. Choose a action, such as `delete-file` on it, the file will not get deleted.
![Peek 2021-09-18 12-24](https://user-images.githubusercontent.com/17398733/133872361-a9ae8c23-da24-41ba-8bbb-08ffdef6e0d3.gif)

### System Information

https://pastebin.com/ypw5dGT5

**Comment by iyefrat** [comment]
Good catch! I can confirm that this is an issue. I _think_ that the problem here is the embark command isn't inheriting the `default-directory` from within the defined function, but I'm not sure. I'm still working on reproducing this in `emacs -Q`.

**Comment by iyefrat** [comment]
Yes this is the issue. It works if the function is called from within a larger `let` binding, but embark seems to inherit the scope of the outer function, not any inner function called inside a `let`. I'm not sure if this is a problem that should be fixed upstream or here, I'll ask the embark maintainers about it.
