### ISSUE TITLE
Doom Will not Open

### ISSUE THREAD

**Issue by Raghav-Dixit** [hlissner/doom-emacs#5499]
### What did you expect to happen?

I expected Doom Emacs to open like normal.

### What actually happened?

Emacs did not open.  As far as I remember, I did not touch the config, init, or packages file today, so I do not think it is a problem with that. Doom commands like `doom sync` work fine, but I can't launch it.

### Describe your attempts to resolve the issue

1. I initially thought it was a problem with Chemacs2, which I was using, so I ran `mv .emacs.d/ .chemacs2/ && mv doom/ .emacs.d` (`.chemacs2/` is just a test directory and `doom/` is where I stored the doom `.emacs.d`)
2. I ran `doom doctor`. Here is something it displayed:
```
> Checking Doom Emacs...
     x There was an unexpected error
      Message: File is missing
      Data: (file-missing . "Cannot open load file")
      Backtrace:
        (require core-keybinds)
        (doom-initialize-core-modules)
        (if no-config-p nil (if doom-debug-p (progn (let ((inhibit-message (active
        (progn (setq doom-init-modules-p t) (if no-config-p nil (if doom-debug-p (
        (if (or force-p (not doom-init-modules-p)) (progn (setq doom-init-modules-
        (doom-initialize-modules)
        (let ((doom-interactive-p 'doctor)) (doom-initialize 'force) (doom-initial
        (let ((doom-output-indent (+ doom-output-indent-increment doom-output-inde
        (condition-case ex (let ((doom-output-indent (+ doom-output-indent-increme
        (let nil :bare t (doom--print (doom--format (format "The doctor will see y
    ! Extended backtrace logged to .emacs.d/.local/doom.error.log
Error in kill-emacs-hook (doom-persist-scratch-buffers-h): (file-missing "Cannot open load file" "No such file or directory" "~/doom/core/autoload/scratch")
```
3. I uninstalled and reinstalled emacs through Homebrew.
4. I tried running directly through the executable (`cd / && ./Applications/Emacs.app/Contents/MacOS/Emacs`), but this returns `Font ‘JetBrains Mono Regular Nerd Font Complete Mono Windows Compatible’ is not defined`. I have never used this font.

### Steps to reproduce

I do not know how the issue came about or how to reproduce it.

### System Information

https://pastebin.com/v4aJ72yW

**Comment by hlissner** [comment]
I'm confident this is an issue with your system or private config, not Doom. 

- A `Font ‘JetBrains Mono Regular Nerd Font Complete Mono Windows Compatible’ is not defined` error indicates an expected font is not installed (maybe it was renamed when you last updated your system). 
- `core-keybinds` is in [core/core-keybinds.el](https://github.com/hlissner/doom-emacs/blob/develop/core/core-keybinds.el). A core file doesn't simply vanish.
- When you swapped chemacs out, did you remember to run `doom sync` afterwards?
- Can you reproduce this issue with your private configuration disabled? (move `~/.doom.d` elsewhere, copy init.example.el to `~/.doom.d/init.el`, run `doom sync` and start Emacs).

In any case, I cannot reproduce this on any of my test systems so I can't investigate this further.

**Comment by Raghav-Dixit** [comment]
Actually, I don't think it is a problem with my private config or Doom. The Emacs app does not open at all. I tried running emacs with no config and it still does not open.
