### ISSUE TITLE
Add a notifying line after native-compilation ends

### ISSUE THREAD

**Issue by t-e-r-m** [hlissner/doom-emacs#5501]
### Describe your request

Hi, using the latest Doom version + commit.

It'd be awesome if there was a notifying line at the end of native-compilation, like "Native Compilation Complete ✓".

The `current/total` indicator is updated on a single line on any display large enough, and it's pretty easy to think that native compliation did not occur / complete, because sometimes DOOM just doesn't build everything, I have to `fdfind -HI -e elc -e eln -e eln.error -x rm` in the emacs folder to "force" the build.

### Briefly explain its use-case

It would make `bin/doom` better and add a line notifying what steps took place during the update / upgrade / build.

**Comment by hlissner** [comment]
Moved to #4273.
