### ISSUE TITLE
Changing editor font on its own (without touching the interface font).

### ISSUE THREAD

**Issue by PurpleAzurite** [hlissner/doom-emacs#5507]
### Describe your request

Currently, doom only allows for changing the font for the entire application (editor + interface). It would be great if the two could be separated. I generally need a large font when programming, currently I achieve this effect by zooming in using ctrl +, however this causes visual artifacts in the interface (eg. the company drow-down goes out of screen boundary).

### Briefly explain its use-case

A variable that allows setting editor font on its own, separate from doom-font which should be restricted to the interface font-size alone.

**Comment by hlissner** [comment]
- `(add-hook! 'prog-mode-hook (text-scale-set 2))`
- `(add-hook! 'prog-mode-hook #'doom-big-font-mode)` and set `doom-big-font` to whatever you like
- Use `face-remap-add-relative` to customize the `default` face however you like.

Since this capability already exists, I will close this.
