### ISSUE TITLE
Interactive ranger-travel chooses wrong directory when using Vertico backend

### ISSUE THREAD

**Issue by chaorace** [hlissner/doom-emacs#5509]
### What did you expect to happen?

When both the `vertico` and `(dired +ranger)` Doom packages are enabled in `init.el`, invoking the `ranger-travel` command in a `dired` buffer should allow navigating to an arbitrary directory based on the next input.

### What actually happened?

Attempting to use the `ranger-travel` command interactively with `vertico` as the search backend will always fail to select the chosen directory. Instead, the first directory or file alphabetically is always chosen.

https://user-images.githubusercontent.com/6462592/134276136-5a0f7863-52e1-44e1-9cce-c2a00f31bd07.mp4

### Describe your attempts to resolve the issue

I reverted back to `ivy` as my search backend, which resolved the issue immediately without requiring further intervention.

### Steps to reproduce

1. Configure `vertico` as the search backend via `init.el`
2. Enable the `(dired +ranger)` plugin via `init.el`
3. Invoke `doom sync` from the command line
4. Start Emacs
5. Open a dired buffer anywhere (`SPC :` => dired => `RETURN`)
6. Invoke `ranger-travel` (`f`)
7. Attempt to fill in the name of any subdirectory or file, except for the first child (alphabetically) of the current directory
8. Press `RETURN` (the chosen subdirectory/file will now be erroneously replaced by the first child)

### System Information

https://pastebin.com/raw/mkEXtSzP

**Comment by iyefrat** [comment]
I can confirm that this is an issue, however it seems to be an upstream bug with `ranger` since `ranger-travel` defaults to `ido` if neither `helm` or `ivy` are found in the load path:
```emacs
(defun ranger-travel ()
  "Open a file or go to a directory in current buffer."
  (interactive)
  (let ((prompt "Travel: "))
    (cond
     ((featurep 'helm)
      (ranger-find-file (helm-read-file-name prompt)))
     ((featurep 'ivy)
      (ivy-read prompt 'read-file-name-internal
                :matcher #'counsel--find-file-matcher
                :action
                (lambda (x)
                  (with-ivy-window
                    (ranger-find-file (expand-file-name x default-directory))))))
     (t
      (ranger-find-file (ido-read-file-name prompt))))))
```
Imo it should default to a `read-file-name` and only use `ido` if `ido-mode` is enabled, but you should open an issue upstream.

Note that this has nothing to do with the vertico module, the issue seems to `ranger-travel` trying to use `ido-read-file-name` without `ido-mode` on, turning it on fixes the issue.

**Comment by iyefrat** [comment]
well, it was an easy fix so i sent over a PR ralesi/ranger.el#236, but there are several open PR's with no response that have been there for a while, so I don't know if it'll get accepted soon. Maybe doom should do a local override so it's at least fixed here.
