### ISSUE TITLE
Doom-emacs won't update tp Avy 0.5.0

### ISSUE THREAD

**Issue by Rareform** [hlissner/doom-emacs#5510]
### What did you expect to happen?

Hello,

I am trying to get to run the current version of Avy to use functions such as avy-action-teleport and expected to get it to run.  I am using doom-emacs on WSL on Windows.

### What actually happened?

I contacted the discord server. I am used unpin! avy, 
I deleted the folder and resynced doom with ./doom sync. However the new actions are still not showing up and the version has not been renewed.

### Steps to reproduce

1. Do the same steps as me above and you will see that you will still have the old avy version

### System Information

https://pastebin.com/WeZ5HtAB

**Comment by hlissner** [comment]
Use `doom sync -u`
