### ISSUE TITLE
Lisp error when doing `treemacs-visit-node-ace`: (void-variable aw-ignored-buffers)

### ISSUE THREAD

**Issue by joelnoomi** [hlissner/doom-emacs#5516]
### What did you expect to happen?

When I do `treemacs-visit-node-ace` by pressing `o a a` on a file in treemacs, it should let me pick a window – by pressing the corresponding letter key – in which a buffer should be open visiting that file.

### What actually happened?

When I do `treemacs-visit-node-ace` by pressing `o a a` on a file in treemacs, I got a Lisp error. Here is the backtrace:

```
Debugger entered--Lisp error: (void-variable aw-ignored-buffers)
  (cons 'treemacs-mode aw-ignored-buffers)
  (let ((aw-ignored-buffers (cons 'treemacs-mode aw-ignored-buffers))) (apply fn args))
  +treemacs--ace-window-ignore-treemacs-buffer-a(#f(compiled-function (&optional arg) "Open current file or tag in window selected by `ace-window'.\nStay in current window with a prefix argument ARG." (interactive "P") #<bytecode 0x158966555f4d>) nil)
  apply(+treemacs--ace-window-ignore-treemacs-buffer-a #f(compiled-function (&optional arg) "Open current file or tag in window selected by `ace-window'.\nStay in current window with a prefix argument ARG." (interactive "P") #<bytecode 0x158966555f4d>) nil)
  treemacs-visit-node-ace(nil)
  #<subr funcall-interactively>(treemacs-visit-node-ace nil)
  apply(#<subr funcall-interactively> (treemacs-visit-node-ace nil))
  funcall-interactively(treemacs-visit-node-ace nil)
  #<subr call-interactively>(treemacs-visit-node-ace nil nil)
  apply(#<subr call-interactively> (treemacs-visit-node-ace nil nil))
  explain-pause--wrap-call-interactively(#<subr call-interactively> treemacs-visit-node-ace nil nil)
  apply(explain-pause--wrap-call-interactively #<subr call-interactively> (treemacs-visit-node-ace nil nil))
  call-interactively(treemacs-visit-node-ace nil nil)
  command-execute(treemacs-visit-node-ace)
```

### Steps to reproduce

1. `firejail --noprofile --private=~/firejail/doom-emacs`
2. `git clone --depth 1 https://github.com/hlissner/doom-emacs .emacs.d`
3. `.emacs.d/bin/doom install`
4. `.emacs.d/bin/doom sync`
5. Enable `:ui/treemacs` by uncommenting it in `init.el`
5. Open Emacs
6. `SPC o p` (`+treemacs/toggle`)
7. `o a a` (`treemacs-visit-node-ace`)

### System Information

https://pastebin.com/UTXSABWj

**Comment by hlissner** [comment]
This issue should now be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by joelnoomi** [comment]
It works! Thank you for such an incredibly fast response.
