### ISSUE TITLE
Upgrade to latest: Checking out vertico (0df75c0)... fails

### ISSUE THREAD

**Issue by pepzi** [hlissner/doom-emacs#5517]
### What did you expect to happen?

Doom should be upgraded to the latest version

### What actually happened?

https://pastebin.com/AMqpRUG9

### Steps to reproduce

1. Open Emacs
2. `M-x doom/upgrade`
3. Upgrade fails

### System Information

https://pastebin.com/F5qqDAae

**Comment by hlissner** [comment]
Duplicate of #4984.

See https://github.com/hlissner/doom-emacs/issues/4984#issuecomment-832842879.
