### ISSUE TITLE
Problem with org-emphasis and org-latex since last update

### ISSUE THREAD

**Issue by Titikomba** [hlissner/doom-emacs#5520]
### What did you expect to happen?

Writing "`Consider $a^{*}$ and $b^{*}$`", I expected the behavior that anyone could expect.

### What actually happened?

Since last doom update, the two `*` are matching, causing "and' to appear in bold case.

### Describe your attempts to resolve the issue

It seems strange that this issue may be related to doom, but I didn't update org-mode so...

### Steps to reproduce

Pasting "`Consider $a^{*}$ and $b^{*}$`" in a org-buffer with org-emphasis turned on.

(no dedicated field for that then: Have a nive day!)

### System Information

https://pastebin.com/Wena6bys

**Comment by hlissner** [comment]
I can reproduce this in vanilla Emacs on the latest version of org:

![image](https://user-images.githubusercontent.com/510883/134807053-63167d98-0151-4408-a154-00012599f231.png)

So this is an upstream issue. [Please report this upstream](https://orgmode.org/worg/org-issues.html).

**Comment by Titikomba** [comment]
Thanks a lot, I'll report that :)
Have a nice Sunday!

**Comment by hlissner** [comment]
This issue was resolved upstream at some point, so I bumped org in a3d040b. Let me know if the issue returns and I'll reopen it. Thanks for bringing it to my attention!
