### ISSUE TITLE
Image not displaying when using org-slide-tree and ATTR_*

### ISSUE THREAD

**Issue by mpas** [hlissner/doom-emacs#5524]
### What did you expect to happen?

Be able to see the scaled image when using an #+ATTR in org-tree-slide mode.

### What actually happened?

When having a simple org document with the following structure:

```
#+TITLE: Test
#+AUTHOR: test

* slide with picture and attr

#+ATTR_ORG: :width 50
[[file:~/file.png]]

* slide with picture without attr

[[file:~/file.png]]
```

And activating org-tree-slide mode the image **without** the #+ATTR is visible in the presentation. The image *with* the #+ATTR is not visible. In normal mode both of the images are visible. 

### Normal mode

![image](https://user-images.githubusercontent.com/139094/134848640-29efd786-fe8e-40d5-b58f-fe9481629b4f.png)

### Slide **with** the #+ATTR

![image](https://user-images.githubusercontent.com/139094/134848774-4e9a163e-a9a2-40f4-9b67-5864c4024572.png)

### Slide **without** the #+ATTR

![image](https://user-images.githubusercontent.com/139094/134848862-91e35bc0-2869-4682-b165-1d3aea396a91.png)

### Describe your attempts to resolve the issue

Refreshing org-inline-images without effect, before and after opening the presentation

### Steps to reproduce

1. Create org-document with the mentioned structure
2. Start org-tree-slide mode (SPC t p)
3. Navigate through slides

### System Information

https://pastebin.com/znQsFiHm

**Comment by hlissner** [comment]
I've confirmed this is reproducible in vanilla Doom, and is caused by [this hook](https://github.com/hlissner/doom-emacs/blob/develop/modules/lang/org/contrib/present.el#L40). A quick workaround is to remove it:

```elisp
(after! org-tree-slide
  (remove-hook 'org-tree-slide-play-hook #'+org-present-hide-blocks-h))
```

I'll look into a better solution soon.

**Comment by hlissner** [comment]
This issue should now be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by mpas** [comment]
Works like a charm now!! Thanks for looking into it!
