### ISSUE TITLE
Enable lsp-ui-doc again

### ISSUE THREAD

**Issue by flexagoon** [hlissner/doom-emacs#5533]
### Describe your request

`lsp-ui-doc-enable` was set to nil because of emacs-lsp/lsp-ui#613, however, it looks like they've found a workaround to remove the lag. Could you please enable lsp-ui-doc again?

### Briefly explain its use-case

Seeing documentation automatically when programming

**Comment by hlissner** [comment]
This issue should now be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by flexagoon** [comment]
Thanks!
