### ISSUE TITLE
Error while installing Coq language support

### ISSUE THREAD

**Issue by RyanSamman** [hlissner/doom-emacs#5542]
### What did you expect to happen?

When uncommenting `coq` from `init.el`, it should successfully install coq language support.

### What actually happened?

When running `doom sync`, the following error occurs, rather than installing coq support:
```
C:\Users\RyanS\AppData\Roaming\.emacs.d\bin>doom sync
> Executing 'doom sync' with Emacs 27.2 at 2021-10-01 01:17:36
  > Synchronizing your config with Doom Emacs...
    > Regenerating envvars file at "~/.emacs.d/.local/env"
      âo" Successfully generated "~/.emacs.d/.local/env"
    > Installing packages...
      > Updating recipe repos...
        âo" melpa updated (5a74b32 -> 4e7ce4a)
          - $ cd "c:/Users/RyanS/AppData/Roaming/.emacs.d/.local/straight/repos/melpa/"
          $ "git" "config" "--get" "remote.origin.url"

          https://github.com/melpa/melpa.git

          [Return code: 0]

          $ cd "c:/Users/RyanS/AppData/Roaming/.emacs.d/.local/straight/repos/melpa/"
          $ "git" "fetch" "origin"

          From https://github.com/melpa/melpa
             5a74b32..4e7ce4a  master     -> origin/master
      > Cloning emacs-neotree...macsmirror-mirror...
      > Building neotree...
      - Checked out company-coq: 382db93374380e5db56f02934ee32bbe39159019
      > Building company-coq...
      x There was an unexpected error
        Message: File is missing
        Data: (file-missing . "Searching for program")
        Backtrace:
          (call-process "gzip" "c:/Users/RyanS/AppData/Local/Temp/jka-comghz1Py" #<b
          (apply call-process "gzip" "c:/Users/RyanS/AppData/Local/Temp/jka-comghz1P
          (jka-compr-call-process "gzip" "compressing z.html.gz" "c:/Users/RyanS/App
          (jka-compr-write-region nil nil "c:/Users/RyanS/AppData/Roaming/.emacs.d/.
          (apply jka-compr-write-region (nil nil "c:/Users/RyanS/AppData/Roaming/.em
          (jka-compr-handler write-region nil nil "c:/Users/RyanS/AppData/Roaming/.e
          (write-region nil nil "c:/Users/RyanS/AppData/Roaming/.emacs.d/.local/stra
          (save-current-buffer (set-buffer temp-buffer) (write-region nil nil temp-f
          (prog1 (save-current-buffer (set-buffer temp-buffer) (insert link-target))
          (unwind-protect (prog1 (save-current-buffer (set-buffer temp-buffer) (inse
      ! Extended backtrace logged to ~/.emacs.d/.local/doom.error.log

```

This is the error log produced
Error log: https://pastebin.com/MZKWtfeR

### Steps to reproduce

1. Go to .doom.d/init.el
2. Uncomment `coq` from the languages section (line 118 on my file)
3. run doom sync

### System Information

https://pastebin.com/NbfAhYqt

**Comment by ymarco** [comment]
Seems like it's trying to write a gzip-compressed file but not finding gzip to compress with. Do you have gzip installed and in your PATH?
If that's the issue we should document it somewhere.

**Comment by RyanSamman** [comment]
I just checked, and gzip is definitely installed and in my PATH.

However, out of the blue, it now works. 
I was installing other packages and restarted my computer, and when I ran `doom sync` afterwards, it successfully installed.
Oddly enough, I tried to do something similar a few weeks ago to fix this error, but it did not work those times.

Still no clue what the source of the error was though.

**Comment by hlissner** [comment]
It's possible the `PATH` in your envvar file was outdated. You are prompted to generate one when you first `doom install`'ed (or when you last ran `doom env`), and it is regenerated when you run `doom sync`. An envvar file is a snapshot of your shell environment that Doom loads at startup.

In any case, glad to hear this is resolved.
