### ISSUE TITLE
non-evil: Upgrading doom removes many keybindings

### ISSUE THREAD

**Issue by hermann-p** [hlissner/doom-emacs#5544]
### What did you expect to happen?

I rebuilt emacs in NixOS, then reinstalled doom (cloned the repo, ran `doom install`) while keeping my doom config folder.
Everything built and compiled without errors, and I expected to be able to keep working.

### What actually happened?

Since rebuilding doom many default keybindings, especially moving keys (M-f, M-b, M-<, M->,...) are undefined.

~~On a side note, my doom-theme variable is ignored, too, but that's no show stopper.~~ <- caused by an update to org-roam.

### Describe your attempts to resolve the issue

Did not find similar issues in the bug tracker.

### Steps to reproduce

- have evil mode disabled
- delete your emacs folder, keep your doom folder
- clone doom into a fresh folder, `doom install`, launch emacs

### System Information

https://pastebin.com/v3RUAshc

**Edit:** I checked starting `emacs -q` to see if the Emacs update caused the error, but all's working well before starting doom. If that's the right term.

**Comment by hlissner** [comment]
I can't reproduce any similar issues with the latest version of Doom. This is likely a personal configuration issue. Please test this [in vanilla Doom.](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#testing-in-dooms-sandbox)
