### ISSUE TITLE
Pin Agda packages to latest stable release

### ISSUE THREAD

**Issue by theOperand** [hlissner/doom-emacs#5545]
### Describe your request

The main method of installing Agda is to build it from the source releases posted on Hackage, using either Cabal or Stack. However, the nightly build is not released on Hackage.

Currently, the packages in `:lang agda` track the master branch of the Agda repository, resulting in a version mismatch between agda-mode and the installed version of Agda unless you either install the nightly version of Agda or manually pin the agda-mode packages.

Thus it seems like for almost all usecases of the `:lang agda` module one would have to pin the packages. I think this means it would be better to pin the package in Doom Emacs itself to the latest stable release.

### Briefly explain its use-case

1. Install Agda from Hackage
2. Add `:lang agda` to config and run `doom sync`
3. Versions match and agda-mode just works

**Comment by hlissner** [comment]
I'd be glad to do so, but as I don't know anything about Agda, and there isn't enough information here for me to act on. What _is_ "stable"? On [agda/agda](https://github.com/agda/agda) see a `stable-2.5` branch, the latest tag is `2.6.2`, and the latest announcement on the [wiki](https://wiki.portal.chalmers.se/agda/pmwiki.php) that looks remotely relevant says `(2021-02-07) Agda 2.6.1.3 is now available.` Is there a particular branch we can track? 

In any case, the `:lang agda` module has a `+local` flag, which stops it from installing anything -- leaving it entirely to the user to supply them and add them to your `load-path` (or write your own local `package!` for it).

**Comment by theOperand** [comment]
I have to admit that I don't know a lot about Agda myself (yet?), I just encountered this while trying to set up my development environment. It does seem to be a bit of a mess to pin to a particular commit or branch. My apologies for making a pretty misinformed feature request.

I didn't know about the `+local` flag, it seems like a more elegant solution considering the way Agda versions work.

Maybe just adding the details about having to either pin the packages or use the `+local` flag to the documentation for the `:lang agda` module would be a good enough solution.
