### ISSUE TITLE
Emmet in typescript-tsx-mode expands `.hoge` to `class="hoge"`

### ISSUE THREAD

**Issue by sei40kr** [hlissner/doom-emacs#5556]
### What did you expect to happen?

When Emmet expands `.hoge` in `typescript-tsx-mode`, it will be expanded to `className="hoge"`.

### What actually happened?

When Emmet expands `.hoge` in `typescript-tsx-mode`, it will be expanded to `class="hoge"`.

### Describe your attempts to resolve the issue

Add below:

```emacs-lisp
  (setq-hook! 'typescript-tsx-mode-hook emmet-expand-jsx-className? t)
```

And it worked.

### Steps to reproduce

1. Open Emacs
2. Create a new buffer and `M-x typescript-tsx-mode`
3. Try to expand `.hoge` with Emmet.

### System Information

https://pastebin.com/q6fc1wUC

**Comment by hlissner** [comment]
This issue should now be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
