### ISSUE TITLE
Join comment lines not working in C++

### ISSUE THREAD

**Issue by Cons-Cat** [hlissner/doom-emacs#5558]
### What did you expect to happen?

When I join commented lines with ``J`` in ``emacs-lisp-mode``, the ``;;`` symbols at the start of the bottom line disappear as expected. e.g.

```elisp
;; (setq evil-move-beyond-eol t)
;; (setq evil-want-o/O-to-continue-comments nil)
```
=>
```elisp
;; (setq evil-move-beyond-eol t) (setq evil-want-o/O-to-continue-comments nil)
```
I would expect this behavior to be consistent across all major modes with a concept of comment sigils.

### What actually happened?

However, in ``c++-mode``, under some circumstances (currently unclear to me), the equivalent ``//`` characters do not disappear in this way. e.g.
```cpp
    // this->logical_device.unmapMemory(device_memory);
    // this->logical_device.bindBufferMemory(temp_buffer, device_memory, 0);
```
=>
```cpp
    // this->logical_device.unmapMemory(device_memory); // this->logical_device.bindBufferMemory(temp_buffer, device_memory, 0);
```

### Describe your attempts to resolve the issue

As far as I can tell, this behavior is defined [here](https://github.com/hlissner/doom-emacs/blob/40cf6139ed53b635fec37ce623c4b1093c78a11e/modules/editor/evil/autoload/advice.el#L179). I investigated this advice, and found in ``emacs-lisp-mode``, when I ``SPC+h+k`` ``J``, I get this:
```elisp
Signature
(evil-join BEG END)

Documentation
This function has :before advice: evil-goggles--join-advice.

This function has :around advice: +evil-join-a.

Join the selected lines.
```
So this advice seems to work there. I tried in ``c++-mode``, and there does not seem to be any difference, so the advice itself appears to be active in both modes. The only potential point of failure I can see in its source code in ``doom-point-in-comment-p``, but I can't understand well enough how that function works to understand the problem any deeper.

### Steps to reproduce

I tried reproducing the issue in the scratch buffer, but ``J`` actually works perfectly in that environment. The main difference I can think of between the well-behaving scratch buffer and my "real" code buffers is that ``projectile-mode`` and ``lsp-mode`` are active there.

I will investigate this problem further later, but I wanted to raise an issue right now before I forget. Unfortunately, GitHub doesn't let me just store private drafts of issues. :crying_cat_face: 

### System Information

https://pastebin.com/MN0Lk1d7

**Comment by hlissner** [comment]
I cannot reproduce this on Emacs 28.0.50, in either c++-mode or c-mode, with or without `lsp-mode` and `projectile-mode`, on NixOS. Will test further in the morning.

**Comment by hlissner** [comment]
Finally managed to reproduce it. It seems there are three cases:

1. ```c++
   // these will
   // join correctly
   ```

2. ```c++
      // these will not because
      // of leading whitespace before first comment line
   ```

3. ```c++
   int x = 5;  // these will not because
               // of non-comments preceding first comment line
   ```

It seems case 2 is due to a bug in Doom's `evil-join-a` advice, but case 3 is a bug inherent to `fill-paragraph` (which `evil-join` uses under the hood). I'm not 100% what causes this, but C/C++ major modes are quite complex; this likely has to do with some improperly initialized (or read) comment.el configuration for these modes. `emacs-lisp-mode` and many others do not suffer these issues.

In any case, see if this fixes all 3 cases for you:

```elisp
;; add to ~/.doom.d/config.el
(defadvice! fix-evil-join-a (fn beg end)
  :override #'+evil-join-a
  ;; `fill-region-as-paragraph' is too greedy.
  (let ((realbeg (ignore-errors (comment-search-forward (min end (line-end-position))))))
    (if (null realbeg)
        (funcall fn beg end)
      (save-restriction
        (narrow-to-region realbeg (line-end-position 2))
        (let* ((count (count-lines beg end))
               (count (if (> count 1) (1- count) count))
               (fixup-mark (make-marker)))
          (unwind-protect
              (dotimes (var count)
                (if (and (bolp) (eolp))
                    (join-line 1)
                  (let* ((end (line-beginning-position 3))
                         (fill-column (1+ (- end beg))))
                    (set-marker fixup-mark (line-end-position))
                    (fill-region-as-paragraph beg end nil t)
                    (goto-char fixup-mark)
                    (fixup-whitespace))))
            (set-marker fixup-mark nil)))))))
```

**Comment by Cons-Cat** [comment]
Sorry for the late reply! That code does fix my problem. Thank you! Should this issue be closed?

**Comment by hlissner** [comment]
This issue should now be resolved. Let me know if that isn't the case and I'll reopen it. It will need more testing -- I'm expecting edge cases in some languages. In any case, thanks for bringing it to my attention!
