### ISSUE TITLE
Broken which-key pagination

### ISSUE THREAD

**Issue by memeplex** [hlissner/doom-emacs#5564]
### What did you expect to happen?

When an each-key menu having more than one page is shown, there is some way to change pages.

### What actually happened?

There is no way to change pages. This was caused by this recent change: https://github.com/hlissner/doom-emacs/commit/4613c74d8b2ba376e5174aa2a4f2d93971dc489c. The rationale of the change is:

> set which-key-use-C-h-commands to nil, otherwise sometimes which-key will override the prefix-help-command setting

But the result is not intuitive, there is no way (at least AFAICS) to change pages, you're left with a message like "page 1 of 2" without any clue on how to change the page.

But once you're inside the which-key menu why is it that important that `<C-h>` means the same than outside? At least a message is provided explaining what `<C-h>` means and how to change pages and you can indeed change pages.

If you want to keep `<C-h>` as `prefix-help-command` inside the menu, a proper solution would involve setting `which-key-paging-prefixes` so that paging could be accessed using `<F5>` or some other key. If you don't explicitly set `which-key-paging-prefixes` paging will be broken.

### Describe your attempts to resolve the issue

I modified my config.el in order to revert the aforementioned change:

```
(setq which-key-use-C-h-commands t)
```

This is easy, but my point is that the current default breaks functionality, not that it's opinionated.

### Steps to reproduce

1. Open emacs.
2. Press `g` and wait for the menu to open.
3. Try to access the second page somehow.

### System Information

https://pastebin.com/7Q3uvah1

**Comment by hlissner** [comment]
>  modified my config.el in order to revert the aforementioned change:
>
>    (setq which-key-use-C-h-commands t)

It's odd that this makes any difference to you. The only place this is set to `nil` is in the `:completion vertico` module, and if this module is enabled, in vanilla Doom `C-h` will always invoke [`embark-prefix-help-command` instead](https://github.com/hlissner/doom-emacs/blob/develop/modules/completion/vertico/config.el#L147), and this is intentional. I believe it is the superior interface for browsing (and searching for) keybinds. 

In fact, I am exploring ways to replace which-key with Embark entirely. Until I have decided that this isn't possible or have changed my mind I don't intend to change this default. I will reopen this issue if I change my mind.

**Comment by memeplex** [comment]
I won't object against a pure embark solution but my point is that the current state of things is confusing because you get a message saying there is n pages, but no indication on how you can access the following ones nor that you can go to a full listing by pressing C-h, etc. As an experienced emacs user but new to doom, I felt lost the first time I pressed g, trying to reach the second page. I concede that by chance it's easy to end up in the embark menu, but something feels broken.

**Comment by hlissner** [comment]
Ah, I see what you mean. Unfortunately, that prompt [is hard-coded into which-key](https://github.com/justbur/emacs-which-key/blob/master/which-key.el#L2061-L2062), it'd take an unseemly hack to get around. Give this a try:

```elisp
  (setq which-key-use-C-h-commands t
        prefix-help-command #'which-key-C-h-dispatch)

  (defadvice! fix-which-key-dispatcher-a (fn &rest args)
    :around #'which-key-C-h-dispatch
    (let ((keys (this-command-keys-vector)))
      (if (equal (elt keys (1- (length keys))) ?\?)
          (let ((keys (which-key--this-command-keys)))
            (embark-bindings (seq-take keys (1- (length keys)))))
        (apply fn args))))
```

Then `C-h` -> invokes which-key's native functionality and `?` -> invokes embark. Though, the `g` prefix has a `?` keybind so the latter won't be available there.

**Comment by memeplex** [comment]
It doesn't seem that hacky to me. Sadly I don't see any way to improve the message in order to include something about `?` and embark, but it's fine. Is the setq for `prefix-help-command` really necessary?

The cleanest way would be to iterate over keymaps and register `which-key-paging-prefixes` for each one, but that will be always playing catch-up when new keymaps are added.

**Comment by memeplex** [comment]
> Sadly I don't see any way to improve the message in order to include something about ? and embark

Well `which-key--next-page-hint` may be advised too, but probably that would be going too far.

**Comment by jkroes** [comment]
Newcomer to doom-emacs from an extensive vanilla config. I also wanted which-key paging alongside embark-prefix-help-command. The "hack" provided by @hlissner is great, but it has the disadvantage that typing a prefix, then "?", then "C-g" leaves the which-key buffer/window visible even though the prefix that triggered it is no longer active. With the default popup provided by doom-emacs, I was able to fix that via:

**Comment by jkroes** [comment]
I came up with another solution for those who might not want to bind to "?". `which-key` already provides "C-h h" to invoke the original `prefix-help-command` (set to `embark-prefix-help-command` when using Doom vertico). 

```
(setq which-key-use-C-h-commands t
      prefix-help-command #'which-key-C-h-dispatch)

;; A hook is needed because which-key-mode sets
;; `which-key--prefix-help-cmd-backup' when `which-key-mode' is enabled.
(add-hook 'which-key-mode-hook 'set-which-key--prefix-help-cmd-backup)

(defun set-which-key--prefix-help-cmd-backup ()
  (setq which-key--prefix-help-cmd-backup 'my/embark-prefix-help-command))

(defun my/embark-prefix-help-command (popup-showing)
  "Prompt for and run a command bound in the prefix used to reach this command.
This command is intended to be used as the value of
`which-key--prefix-help-cmd-backup' when `prefix-help-command' is set to
`which-key-C-h-dispatch' and `which-key-use-C-h-commands' is set to `t'. When
the which-key-popup is not visible, `which-key-C-h-dispatch' calls
`which-key-show-standard-help', which calls `which-key--prefix-help-cmd-backup',
which by default is set to the original value of `prefix-help-command' when
`which-key-mode' is first enabled. In Doom Emacs with `vertico',
`prefix-help-command' is typically the original `embark-prefix-help-command'
that this function replaces. Note that this function must be called from a
modified version of `which-key-show-standard-help' that passes `popup-showing'.

In addition to using completion to select a command, you can also type @ and the
key binding (without the prefix)."
  (interactive)
  (let (keys)
    (if popup-showing
        (setq keys (which-key--current-prefix))
      (setq keys (this-command-keys-vector))
      (setq keys (seq-take keys (1- (length keys)))))
    (embark-bindings keys)))

(advice-add 'which-key-show-standard-help
            :override 'my/which-key-show-standard-help)

(defun my/which-key-show-standard-help (&optional _)
  "Call the command in `which-key--prefix-help-cmd-backup'.
Usually this is `describe-prefix-bindings'.

Unlike the original function, `popup-showing' is passed to
`which-key--prefix-help-cmd-backup'."
  (interactive)
  (let ((which-key-inhibit t)
        (popup-showing (which-key--popup-showing-p)))
    (which-key--hide-popup-ignore-command)
    (cond ((and (eq which-key--prefix-help-cmd-backup
                    'describe-prefix-bindings)
                ;; If the popup is not showing, we call
                ;; `describe-prefix-bindings' directly.
                popup-showing)
           ;; This is essentially what `describe-prefix-bindings' does. We can't
           ;; use this function directly, because the prefix will not be correct
           ;; when we enter using `which-key-C-h-dispatch'.
           (describe-bindings (kbd (which-key--current-key-string))))
          ((functionp which-key--prefix-help-cmd-backup)
           (funcall which-key--prefix-help-cmd-backup popup-showing)))))
```
