### ISSUE TITLE
Broken links in Discourse Roadmap

### ISSUE THREAD

**Issue by memeplex** [hlissner/doom-emacs#5565]
### What did you expect to happen?

The links to PRs in the roadmap lead to this GitHub project.

### What actually happened?

Links are relative and so trying to resolve inside Discourse itself, of course to no avail.

### Steps to reproduce

1. Go to https://discourse.doomemacs.org/t/development-roadmap/42
2. Try to follow any PR link there

### System Information

https://pastebin.com/doesnt_apply

**Comment by hlissner** [comment]
I am aware of issues like these on the Discourse, hence the warning on the top:

![image](https://user-images.githubusercontent.com/510883/135748119-f8080567-98f0-4745-bd26-d4ae42011588.png)

They will be addressed when the Discourse is finalized.

As this is not a Doom issue I have closed this thread and marked it for deletion.
