### ISSUE TITLE
Add python-shell-interpreter-args to org-babel-python-command

### ISSUE THREAD

**Issue by memeplex** [hlissner/doom-emacs#5569]
### What did you expect to happen?

org-babel executes the same interpreter (including options) than run-python and the likes.

### What actually happened?

org-babel ignores the arguments in the command line of my python interpreter.

python-shell-interpreter is just  the name of the command (args are in python-shell-interpreter-args) while org-babel-python-command is the entire command line, so probably you want to set the babel command to a concatenation of the interpreter name and its args.

Other than that, it's somewhat questionable that you are overriding org-babel-python-command at all. It results in a surprising behavior since setting it globally or in an org-mode hook won't have any effect, given that doom is resetting it afterwards in a python hook. So even though I suggested the more conservative approach of adding args, I'm all for removing that override altogether, I don't think it's worth the surprise.

### Describe your attempts to resolve the issue

```elisp
(setq python-shell-interpreter "ipython"
      python-shell-interpreter-args "-i --simple-prompt")
(after! python
  (setq org-babel-python-command "ipython -i --simple-prompt"))
```

### Steps to reproduce

1. Set python-shell-interpreter  and python-shell-interpreter-args.
2. Create an org file and open it.
3. Inspect org-babel-python-command.

### System Information

https://pastebin.com/EQ6f53Gj

**Comment by hlissner** [comment]
This issue should now be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by memeplex** [comment]
Your fix addresses both of my concerns, thank you very much, really appreciate your dedication.

**Comment by memeplex** [comment]
I've one question regarding my workaround above, that after restarting emacs I realize doesn't actually work and it probably reveals my misunderstanding of how `after!` is supposed to behave.

In my `config.el` there is:

```elisp
(after! python
  (setq org-babel-python-command "ipython -i --simple-prompt"))
```

But when I open an org file `org-babel-python-command` is simply `ipython` (taken from `python-shell-interpreter`). Why is my personal `after!` setting not overriding the one in the org module? From https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#load-order I understand that my config is evaluated after the module's config, but they are just installing a kind of hook and maybe the order of execution of those hooks is different, I don't know.

Sorry for bothering you.

**Comment by hlissner** [comment]
> Why is my personal after! setting not overriding the one in the org module?

Sorry for the tremendously late response. You've probably figured this out by now, but just in case (and for posterity): it's because `+org-init-babel-h` isn't evaluated until `org` is loaded, so you'd need to adjust your `after!` target:

```elisp
(after! (org python)
  (setq org-babel-python-command ...))
```
