### ISSUE TITLE
Update error

### ISSUE THREAD

**Issue by ixzh** [hlissner/doom-emacs#5588]
### What did you expect to happen?

successful update

### What actually happened?

```
In repository "org", remote "origin" has URL
        "https://github.com/emacs-straight/org.git"
      but recipe specifies a URL of
        "https://git.savannah.gnu.org/git/emacs/org-mode.git"

           1) Abort
           2) Rename remote "origin" to "origin-1", re-create "origin" with correct URL, and fetch
           3) Rename remote "origin" manually, re-create it with correct URL, and fetch
           4) Delete remote "origin", re-create it with correct URL, and fetch (Choose this if unsure)
           5) Delete remote "origin", re-create it with manually set URL, and fetch

        How to proceed? (1, 2, 3, 4, 5; don't know? Pick 4) 4
      > In repository "org", failed to get status:

        Failed to get unambiguous name for "main"
        fatal: Needed a single revision

           1) Abort

        How to proceed? (1) 1

! Aborted

        ! Script was abruptly aborted! Run 'doom sync' to repair inconsistencies

Retry? (y)es/(N)o/(s)hell
```

### Describe your attempts to resolve the issue

I tried `doom sync` then `doom update -f`, not working

### Steps to reproduce

run `doom update`

### System Information

I have deleted doom emacs...just to report the error

**Comment by markflarup** [comment]
I've just encountered the same issue, with this diff to update: https://github.com/hlissner/doom-emacs/compare/0ca2e791f7e428c092ac5cc3b5f0d00fc8d718ba...ee890064f853b1a4f61965e155cff0dffc58918e

My system information:
```
$ doom info
> Executing 'doom info' with Emacs 27.2 at 2021-10-06 07:11:05
    generated    Oct 06, 2021 07:11:05
      system       MacOS 10.14.6 Darwin 18.7.0 x86_64
      emacs        27.2 ~/.emacs.d/ -> ~/.emacs.d/
      doom         3.0.0-alpha HEAD -> develop ee890064f 2021-10-06 01:30:45 +0200 ~/.doom.d/ -> ~/.doom.d/
      shell        /bin/zsh
      features     NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB MODULES THREADS JSON PDUMPER GMP
      traits       batch server-running envvar-file custom-file
      modules      :completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline ophints (popup +defaults) vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold snippets word-wrap :emacs dired electric undo vc :term vterm :checkers syntax (spell +flyspell) grammar :tools (debugger +lsp) (eval +overlay) lookup lsp magit :os macos :lang emacs-lisp (go +lsp) javascript markdown org (sh +lsp) yaml :config (default +bindings +smartparens)
      packages     (evil-tutor) (evil-terminal-cursor-changer) (gruvbox-theme) (lsp-sonarlint) (dash) (ht)
      elpa         spinner s ov markdown-mode lv lsp-sonarlint lsp-mode ht f elquery dash coverage cov
```

**Comment by liaobinbin** [comment]
same problem, 

https://github.com/hlissner/doom-emacs/commit/e3d4e05fbd53c6c438cea3c0477f70fff954117c

this commit changed the org-mode repo, i think that is reason.

**Comment by ps-143** [comment]
Same here
The repo has been changed to https://git.savannah.gnu.org/git/emacs/org-mode.git/ and if we manually clone it, it gets stuck on cloning.

**Comment by HyunggyuJang** [comment]
To resolve update problem you can always go with radical method: Remove  
the problematic repo and build then retry update.  

Like,  

```sh
rm -r $DOOMLOCALDIR/straight/repos/org
rm -r $DOOMLOCALDIR/straight/build-27.2/org
doom sync -u
```

Note that you should have substitute `27.2` of build directory path with your emacs version.  

Haven&rsquo;t checked yet, with recent revision of ea404dfa45919462b5ab4bb4df8f68f94576d319, you might do not need to delete build directory.  

Nevertheless, this should resolve the current issue, although not elegant.

**Comment by ixzh** [comment]
Sorry should have paid more attention to pinned issue...

**Comment by eddiegroves** [comment]
This fixed it on my machine: `rm -rf ~/.emacs.d/.local/straight/repos/org`
