### ISSUE TITLE
soften git version requirement 2.23+ -> 2.17+

### ISSUE THREAD

**Issue by ghuber-github** [hlissner/doom-emacs#5596]
### Describe your request

soften the git version requirement from 2.23+ to 2.17+

### Briefly explain its use-case

we run ubuntu 18.04 on our systems at work and our admin would not upgrade git to version 2.23+, as there is no newer version in the official repos.
I did however change line ~/.emacs.d/core/core-packages.el:135 to 2.17 to avoid  the user-error (due to the git version requirement) at installation. Installation run without problems and I did not encounter any issues so far.

**Comment by hlissner** [comment]
As Gagbo has stated: our minimum supported version of git depends on [straight.el](https://github.com/raxod502/straight.el). To bring it down further, this will have to be guaranteed [upstream](https://github.com/raxod502/straight.el).

A list of git commands that straight uses was [posted here](https://github.com/raxod502/straight.el/issues/768#issuecomment-852365608) (not sure if outdated by now, though), and here is an exhaustive list of git commands Doom uses (not counting what straight or other packages may use). Perhaps you can test each of them on git 2.17 to reveal incompatibilities -- if we're lucky there aren't any and I can safely lower the cap.

- **Essential:** (used in Doom core)
  - `git branch [-D|-m] $BRANCH`
  - `git clean -ffd`
  - ```sh
    git clone --origin origin 
              --no-checkout
              --depth $DEPTH
              --[no-]single-branch 
              --no-tags
              --branch $BRANCH
              $REPO_URL $REPO_DIR
    ```
  - `git fetch --force --tags $REMOTE $BRANCH:$TARGET_REMOTE`
  - `git fetch origin $HASH --depth $DEPTH --no-tags`
  - `git init`
  - `git log --oneline --no-merges`
  - `git log -1 --format=%cr $TARGET`
  - `git ls-remote $URL`
  - `git name-rev --name-only HEAD`
  - `git reflog expire --expire=all --all`
  - `git remote add $REMOTE $REPOURL [--master $BRANCH]`
  - `git remote remove $REMOTE`
  - `git reset --hard origin/$BRANCH`
  - `git rev-list --grep ^$START $END`
  - `git rev-parse [--short] $TARGET`
  - `git status --porcelain -uno`
  - `git version`
- **Non-essential:** (used in optional modules)
  - `git config --global --get-regexp $REGEX`
  - `git config github.user`
  - `git describe --abbrev=7 --match "[0-9.]*"`
  - `git describe --all --always HEAD`
  - `git grep --no-break --no-heading --line-number`
  - `git log $START..$END`
  - `git log -1 --format=%D %h %ci`
  - `git show ref`
  - `git symbolic-ref -q --short HEAD`

> I did however change line ~/.emacs.d/core/core-packages.el:135 to 2.17 to avoid the user-error (due to the git version requirement) at installation. Installation run without problems and I did not encounter any issues so far.

That's fortunate, but requires more systematic testing before I'm willing to make that change or recommend that approach.
