### ISSUE TITLE
Dired buffer doesn't show all files, hiding .aux files generated by LaTeX

### ISSUE THREAD

**Issue by Lynntee** [hlissner/doom-emacs#5616]
### What did you expect to happen?

I should get all files in dired buffer including .aux files.

### What actually happened?

![image](https://user-images.githubusercontent.com/15835427/136884587-505a4d2e-9b98-4916-88ef-a37250b70006.png)

The left figure displays how does the vanilla emacs (`emacs -Q`) show the dired buffer of a certain directory, we can see there are some .aux files.

The right figure displyas using doom emacs to open the dired buffer, it doesn't show the aux files.

As a supplement, I use WSL 2 in windows 10.

### Steps to reproduce

1. Open emacs.
2. Open a dired buffer of a certain directory containing .aux files by `SPC f d`.

### System Information

https://pastebin.com/AYganREC

**Comment by MithicSpirit** [comment]
IIRC this is because `dired-omit-mode` is enabled by default. You can use the `SPC m h` keybind (in evil) to toggle it.

**Comment by Lynntee** [comment]
Oh! It works! Silly me!

Many thanks!!!

> IIRC this is because `dired-omit-mode` is enabled by default. You can use the `SPC m h` keybind (in evil) to toggle it. If you wish to prevent it from enabling by default you need to remove the `dired-omit-mode` entry from `dired-mode-hook`.
