### ISSUE TITLE
Disable ws-butler by default in diff-mode

### ISSUE THREAD

**Issue by homer242** [hlissner/doom-emacs#5619]
### Describe your request

Hi,

IMHO, ws-butler should by disabled by default in diff-mode. Removing the white spaces automatically in this mode is not a good behavior because of the meaning of the white space in a patch and with the help of diff-mode, we could imagine edit manually a patch file (actually, I do that thing regularly).

### Briefly explain its use-case

1. open a patch file
2. try to add a line with a single white space in a chunk
3. save the patch (C-x C-s)
3. the space is gone!

**Comment by hlissner** [comment]
This issue should now be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
