### ISSUE TITLE
Custom `auth-sources` value removed

### ISSUE THREAD

**Issue by io12** [hlissner/doom-emacs#5628]
### What did you expect to happen?

I expected for the value of `auth-sources` to contain `~/.emacs.d/.local/etc/authinfo.gpg` as it had previously.

### What actually happened?

Instead, `auth-sources` has the default Emacs value of `("~/.authinfo" "~/.authinfo.gpg" "~/.netrc")`.

### Describe your attempts to resolve the issue

I believe the change that caused this is https://github.com/hlissner/doom-emacs/commit/68d8364ae#diff-ed129b37df9382424b41c4c961f1e6d2f0a6c0a91216de88ad6f9f22a945d3d0L376-L380, since it looks like that removes the custom `auth-sources` value. If I run the deleted block of code manually then it works as it did before.

### Steps to reproduce

1. Check out a commit before https://github.com/hlissner/doom-emacs/commit/68d8364ae#diff-ed129b37df9382424b41c4c961f1e6d2f0a6c0a91216de88ad6f9f22a945d3d0L376-L380
2. Restart Emacs and view `auth-sources`
3. Check out https://github.com/hlissner/doom-emacs/commit/68d8364ae#diff-ed129b37df9382424b41c4c961f1e6d2f0a6c0a91216de88ad6f9f22a945d3d0L376-L380
4. Restart Emacs and view `auth-sources`
5. Observe how the values are different

### System Information

https://pastebin.com/diMqfVww

**Comment by hlissner** [comment]
My bad. Accidentally removed the line in 68d8364. I brought it back in b36d798 which should resolve this issue. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
