### ISSUE TITLE
[develop] live-py-mode window receives unwanted focus/input

### ISSUE THREAD

**Issue by eric343** [hlissner/doom-emacs#563]
### Observed behavior
While running the [live-py-mode](https://github.com/donkirkby/live-py-plugin) plugin and editing python source code the live-py window gets focused and receives input directed to the active source code window.

### Expected behavior
No focus/input to the live-py window while working in the source code window. It works fine in Spacemacs (python layer), I searched through the Spacemacs code and it seems that they don't configure anything specially for live-py-mode.

### Steps to reproduce
1. Checkout current develop branch
2. Copy init.example.el to ~/.doom.d/init.el
3. Include the live-py-package with `(package! live-py-mode)` in ~/.doom.d/packages.el and `(def-package! live-py-mode :commands live-py-mode)` in ~/.doom.d/config.el
4. make install
5. Open any python file in python-mode and invoke live-py-mode (a vertical split opens)
6. Edit the code / navigate with vim/arrow keys

Thanks!

### System information

<details>
<summary>Click to expand</summary>

```
eric@arch> DEBUG=1 make doctor                                                                                                                                          ~/.emacs.d
Doom Doctor
Emacs v25.3.1
Doom v2.0.9 (4ef70174)
shell: /bin/zsh
Compiled with:
  XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL
  GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11
  MODULES
uname -a:
  Linux arch 4.16.6-1-ARCH #1 SMP PREEMPT Mon Apr 30 12:30:03 UTC 2018 x86_64
  GNU/Linux

----

test-emacs
test-private-config
test-windows
test-fonts
test-gnutls
test-tls
Validated https://elpa.gnu.org
Validated https://melpa.org
Successfully rejected https://self-signed.badssl.com
Successfully rejected https://wrong.host.badssl.com/
test-tar

----
Attempt to load DOOM: failed (Cannot open load file No such file or
  directory evil-collection-package-menu)

----
There were 1 issues!

```
</details>

**Comment by hlissner** [comment]
This is the work of the popup manager being a tad too aggressive. Since `live-py-mode` manages its own window, best to tell Doom not to:

```elisp
(def-package! live-py-mode
  :commands live-py-mode
  :config (set! :popup "^\\*live-py-trace" :ignore))
```

That should do it.

**Comment by eric343** [comment]
That fixes it, thanks so much.
I didn't even think about it being a popup window because of the vertical split, but now that I know I see that it's darker (because of solaire-mode).
