### ISSUE TITLE
Evil surround doesn't process ` (backtick) in a proper way on vanilla Doom Emacs

### ISSUE THREAD

**Issue by akowiz** [hlissner/doom-emacs#5633]
### What did you expect to happen?

On a vanilla Doom Emacs (with Evil and Evil surround), we should be able to surround a word or a sentence with backticks and we should be able to change them or delete them using the regular evil-surround commands (ysiw, cs, ds).
```
ysiw`
cs`"
ds`
```
This is the behavior we get on a vanilla Emacs with Evil and Evil-surround installed.

### What actually happened?

When surrounding a word with backticks, instead the word is surrounded by backtick and single quote.
```
ysiw` on surround => `surround' (backtick + single quote)
cs` on `surround' fails (obviously)
ds` on `surround' fails too

cs` on `surround` also fails
ds` on `surround` fails as well
```

### Describe your attempts to resolve the issue

Adding ``` ?\` ``` to evil-embrace-evil-surround-keys is enough to fix the improper behavior.

In config.el
```elisp
(setq evil-embrace-evil-surround-keys '(?\( ?\[ ?\{ ?\) ?\] ?\} ?\" ?\' ?\` ?< ?> ?b ?B ?t ?\C-\[ ?w ?W ?s ?p))

```

I am not sure why it is missing in the list. If it is intentional, it should probably be documented in the Doom Evil package documentation. If it is an omission, it should probably be set as part of the default value of evil-embrace-evil-surround-keys. I noticed that quoting with backtick and single quote is used for highlighting words in the comments of config.el so there might be a reason for the omission.

### Steps to reproduce

1. Install Vanilla Doom Emacs
2. Type some text
3. Use ``` ysiw` ``` to surround a word with backticks and observe the result
4. Use ``` cs`  ``` or ``` ds` ```

### System Information

https://pastebin.com/UuRB8Whq

**Comment by Lyonsclay** [comment]
I have noticed that when I try to surround a word in an Elisp buffer it will do (backtick + single quote), however when I visit other buffers I get (backtick + backtick) 

I'm not sure I have altered the default behavior but I use this in my config.el;

```
(after! smartparens
  (sp-pair "`" "`" :wrap "M-`"))
```
