### ISSUE TITLE
Bump ivy-xref for Emacs 28 support

### ISSUE THREAD

**Issue by razzmatazz** [hlissner/doom-emacs#5634]
### What package(s) should be bumped?

ixy-xref, to https://github.com/alexmurray/ivy-xref/commit/a82e8e117d2dd62c28b6a3e3d6e4cfb11c0bda38

### Why should Doom bump these packages early?

lsp/find-references with ivy configured is not working on emacs28 anymore, throws type error.

In particular this latest commit says:
>  Stop using 'with-slots'
> The latest Xref is not based on EIEIO anymore, so with-slots and oref don't work.
> Use accessor functions which work with both implementations (old and new).

**Comment by hlissner** [comment]
This issue should now be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
