### ISSUE TITLE
Bump helm-xref for Emacs 28 support

### ISSUE THREAD

**Issue by brotzeit** [hlissner/doom-emacs#5637]
### What package(s) should be bumped?

helm-xref

### Why should Doom bump these packages early?

Same issue as ivy-xref #5634

https://github.com/brotzeit/helm-xref/pull/28

**Comment by eengad** [comment]
There seem to be an issue with xref in emacs 28 in vertico as well.
I get some xref related error messages in emacs 28 and vertico does not start well.
In emacs 27.2 everything works well.

**Comment by DarkBuffalo** [comment]
> > There seem to be an issue with xref in emacs 28 in vertico as well.
> 
> Could you show the backtrace?
'''
     Message: error
      Error: (error "Given parent class xref-location is not a class")
      Backtrace:
        (error "Given parent class %S is not a class" xref-location)
        (eieio-defclass-internal xref-etags-location (xref-location) ((tag-info :t...
        (byte-code "\300\301\302\303!\"\210\300\304\305\303!\"\210\300\306\304\"\2...
        (#<subr require> etags)
        (apply #<subr require> etags)
        (progn (fset #'write-region vnew) (apply fn args))
        (unwind-protect (progn (fset #'write-region vnew) (apply fn args)) (fset #...
        (let* ((vnew #'(lambda (start end filename &optional append visit lockname...
        (let ((write-region (symbol-function #'write-region))) (ignore write-regio...
        (progn (fset #'load vnew) (let ((write-region (symbol-function #'write-reg...
    ! Extended backtrace logged to .doom-emacs/.local/doom.error.log
'''

**Comment by dvzubarev** [comment]
@DarkBuffalo The same error when starting `lispy-mode`. Quick fix is to  pin `xref` to commit before migrating off EIEIO:
`(package! xref :pin "a82f459b37b31546bf274388baf8aca79e9c30d9")`

**Comment by hlissner** [comment]
This issue should now be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
