### ISSUE TITLE
j in motion mode not acting same as vim

### ISSUE THREAD

**Issue by liujoey** [hlissner/doom-emacs#564]
After map `j` to `gj`
```elisp
(map!
 :nv [remap evil-next-line] #'evil-next-visual-line
 :nv [remap evil-previous-line] #'evil-previous-visual-line)
```

`j` no longer acting like *linewise* motion.

In vim normal mode, i have
```
  nnoremap <silent> j gj
  nnoremap <silent> k gk
```

Still command `dj` should delete two lines, because `j` is a *linewise* motion. In doom emacs, `dj` acting like *characterwise* after remap, it's acting like command `dvj` in vim. For more information, in vim run `:h linewise` to read the document.

I've tested in vim/nvim, Spacemacs and Doom. Only Doom acting incorrectly. Didn't try vanilla evil-mode though.

`dj` is a very useful command, it's a shorter version of `dddd`. And people use `[n]dj` or `d[n]j` to delete multiple lines, this is where the relative line number become important.

In vim, people use command `dvj` to convert *linewise* motion `j` to * characterwise*, this feature seems doesn't work after mapping `j` to `gj` in Doom.

### Observed behavior
Having text
```
AAAAA
BBBBB
CCCCC
 ```
Where cursor is on third A, in normal mode, type `dj`, the result become
```
AABBB
CCCCC
```

### Expected behavior

The text should become
```
CCCCC
```

**Comment by hlissner** [comment]
I see this behavior in vanilla Emacs with evil-mode. This appears to be a limitation of evil-mode, not Doom. https://github.com/emacs-evil/evil/issues/188 seems to mention this.

A quick look at Spacemacs' code doesn't reveal that they've done anything to remedy this, so I don't understand why you would not experience this problem there. I'm assuming this is what you used to remap the keys in spacemacs:

```elisp
(define-key evil-motion-state-map [remap evil-next-line] #'evil-next-visual-line)
(define-key evil-motion-state-map [remap evil-previous-line] #'evil-previous-visual-line)
```

**Comment by liujoey** [comment]
I didn't map motion state in Spacemacs. I've only mapped normal state. The command I've use in spacemacs is like below, this should definitely not affecting `dj` as the `j` here is in motion state:
```
  (define-key evil-normal-state-map (kbd "j") 'evil-next-visual-line)
  (define-key evil-normal-state-map (kbd "k") 'evil-previous-visual-line)
```

In doom setting I didn't include `m` in the map, only `n`.
```
(map!
 :n [remap evil-next-line] #'evil-next-visual-line
 :n [remap evil-previous-line] #'evil-previous-visual-line)
```
I'm assuming the two should be identical. But somehow doom changed the behavior of `j` in motion state as well.

I'm a vimmer for years, but new to Elisp (couple weeks) and extremely new to Doom (2 days). I might be doing things in a wrong way, the only experience of using Emacs for me is few months of Spacemacs, nothing more. Please excuse me if my question is silly. Thank you for the quick response.

**Comment by hlissner** [comment]
I apologize for the long delay. I've been busy preparing for the 2.1 release.

Instead of remapping commands, does this work?

```elisp
(map! :n "j" #'evil-next-visual-line
      :n "k" #'evil-previous-visual-line)
```

I try this now and it appears to work, however, in modes where `visual-line-mode` is active, `evil-next-line` and `evil-previous-line` silently work like their visual counterpart, even in normal mode. `visual-line-mode` is activated in org-mode, for example.

**Comment by liujoey** [comment]
Did a bit more investigation, seems like the problem is really just from `visual-line-mode`. Or not a problem at all I would say, that might be the intended design for this mode.

This mode makes the normal mode `j` and `k` work like their visual counterpart, but it also remaps the `j` and `k` in motion mode.

When turn on `visual-line-mode` it automatically maps `j` and `k` in both normal mode and motion mode, as if it automatically did this in vim:
```vim
nnoremap j gj
nnoremap k gk
onoremap j gj
onoremap k gk
```
And guess what, I've just learned from this experiment, when `onoremap j gj` in vim, it does change the motion behavior to *characterwise*.

I didn't aware of this behavior from `visual-line-mode` but it kinda makes sense now. This is also why I feel strange when editing my org file, because org-mode has `visual-line-mode` on by default in doom.

Please close this issue any time you feel proper. Thank you for the reply.

**Comment by hlissner** [comment]
Understandable. I looked into it myself and already disabled visual-line-mode in org-mode, replacing it with auto-fill-mode (hard wrapping). Not only to resolve this issue, but to make org-mode more behave more consistently with other text modes (like markdown).

Thanks for bringing this to my attention however, I've learnt a lot more about visual-line-mode because of it!
