### ISSUE TITLE
Emacs chokes on set-buffer: Symbol’s function definition is void: flymake--diag-buffer

### ISSUE THREAD

**Issue by robinbourianes-kalisio** [hlissner/doom-emacs#5644]
### What did you expect to happen?

Editing c files should be painless.

### What actually happened?

Emacs chokes and freeze for half a second every time I edit a c file. While it's frozen, i see `set-buffer: Symbol’s function definition is void: flymake--diag-buffer` in the minibuffer

### Describe your attempts to resolve the issue

It seems  `flymake--diag-buffer` got renamed to `flymake--diag-locus` in the flymake doom pulls. Renaming it in `modules/tools/lsp/autoload/flycheck-eglot.el` seem to solve the issue.

### Steps to reproduce

1. Open emacs
2. Edit a c file with eglot as lsp server and syntax checker enabled
3. Observe emacs freezing and yelling that `set-buffer: Symbol’s function definition is void: flymake--diag-buffer`

### System Information

https://pastebin.com/wUautdfB

**Comment by jeremyheiler** [comment]
This error also occurs for `flymake--backend-state`, which I think is now `flymake--state`.

**Comment by robinbourianes-kalisio** [comment]
I ended up pinning a specific version adding this: 

`(package! flymake :pin "cf0eb2a47125be42973822e5f91b33d5681bfd4c") ; flymake--diag-buffer becomes flymake--diag-locus after that`

to my `packages.el` to solve the issues with latest flymake.
