### ISSUE TITLE
Emms Module

### ISSUE THREAD

**Issue by Emiller88** [hlissner/doom-emacs#565]
Going to work on making an Emms module if anyone is interested in contributing:

https://github.com/Emiller88/doom-emacs/tree/emms

**Comment by Emiller88** [comment]
Inspiration: https://youtu.be/xTVN8UDScqk

**Comment by hlissner** [comment]
I'd welcome an app/emms module. Are you still working on this?

**Comment by Emiller88** [comment]
I never got around to it. I think @ar1a got one working.

**Comment by ar1a** [comment]
nah i got a google play music integration going, but i don't even use it anymore :p 

https://github.com/ar1a/dotfiles/blob/master/emacs/.doom.d/%2Bmusic.el

**Comment by hlissner** [comment]
Understood. In that case I'll close this for the time being.
