### ISSUE TITLE
String printed in machine-readable format when no references found

### ISSUE THREAD

**Issue by qoops-1** [hlissner/doom-emacs#5652]
### What did you expect to happen?

When I call interactively `+lookup/references` on string "planner" and no results are found, it should print something like:
`Couldn’t find references of "planner"`

### What actually happened?

When the string "planner" in the buffer is propertized, I get:
`Couldn’t find references of #("planner" 0 5 (face font-lock-function-name-face fontified t identifier-at-point t) 5 16 (face font-lock-function-name-face fontified t identifier-at-point t))`

### Describe your attempts to resolve the issue

Changing %S inside `+lookup/references` error call to "\\"%s\\"" solved the problem. If there are no caveats with the approach, I can make a PR for this.

### Steps to reproduce

I could only reproduce this with `lsp-managed-mode` by just interactively calling `+lookup/references` in the buffer

### System Information

https://pastebin.com/pz9Xi3XL

**Comment by hlissner** [comment]
This issue should now be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by qoops-1** [comment]
Works perfect, thank you
