### ISSUE TITLE
Make install encounters fatal error when installing packag company-box

### ISSUE THREAD

**Issue by benreyn** [hlissner/doom-emacs#566]
### Observed behavior

```
$ make install
Looking for packages to install...
1 packages will be installed:
+ company-box (ELPA)
Proceed? (y or n) y
Refreshing package archives
Importing package-keyring.gpg...
Importing package-keyring.gpg...done
Contacting host: elpa.gnu.org:443
Contacting host: elpa.gnu.org:443
Contacting host: melpa.org:443
Contacting host: orgmode.org:443
Package refresh done
Installing company-box
  FATAL ERROR: (error Package ‘emacs-26.0.91’ is unavailable)
Finished!
```

### Expected behavior

Make install completes with no errors.

### Steps to reproduce

1. Clone doom-emacs and run `make quickstart`

### System information

<details>
<summary>Click to expand</summary>

```
Doom Doctor
Emacs v25.3.1
Doom v2.0.9 (4ef70174)
shell: /bin/bash
Compiled with:
  JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS
  MODULES
uname -a:
  Darwin Benjamins-MBP 16.7.0 Darwin Kernel Version 16.7.0: Mon Nov 13 21:56:25
  PST 2017; root:xnu-3789.72.11~1/RELEASE_X86_64 x86_64
----
test-emacs
test-private-config
test-windows
test-fonts
test-gnutls
test-tls
Validated https://elpa.gnu.org
Validated https://melpa.org
Successfully rejected https://self-signed.badssl.com
Successfully rejected https://wrong.host.badssl.com/
test-tar
----
Saving file /Users/benjaminreynolds/.emacs.d/.local/packages.el...
Attempt to load DOOM: success! Loaded v2.0.9
test-modules
Loading /Users/benjaminreynolds/.emacs.d/modules/feature/snippets/packages.el (source)...
  > (:completion company) company-box is not installed
  > (:lang rust) Couldn’t find the racer binary at ‘racer-cmd’
  > (:lang rust) Couldn’t find Rust’s source code at RUST_SRC_PATH
    or ‘racer-rust-src-path’.
----
There were 3 issues!
```
</details>

**Comment by benreyn** [comment]
@hlissner Looking at this now, this is pretty clearly documented in the example init file. I managed to fix this shortly after submitting this issue by removing `:completion +childframe`. Perhaps a better solution might just be to remove `:completion +childframe` from `init.example.el`, and not assume that a user running `make quickstart` is running emacs 26? (at least until emacs 26 is released)

**Comment by hlissner** [comment]
I pushed bfc684c a little while ago, which adds a emacs version check to company-box. Whether or not you have `+childframe`, it should no longer be installed on pre Emacs26. I'd like to keep `+childframe` in `init.example.el`, because that file should be a comprehensive listing of all available modules and flags.

Please update and let me know if that hasn't resolved your issue.

**Comment by benreyn** [comment]
Looks good to me! 👍
