### ISSUE TITLE
[Question] How to add padding/margins to Emacs buffers?

### ISSUE THREAD

**Issue by nealot** [hlissner/doom-emacs#567]
How do you add margins/padding to buffers or popups in Doom Emacs? Currently, I can set the global margin width using 
```
(setq-default left-margin-width 1 right-margin-width 1)
(set-window-buffer nil (current-buffer))
```
But I can't figure out how to add margins to specific buffers.

The reason I'm asking is because some buffers look decent enough others don't so I'm trying to find a way to explicitly set the margins for each popup/buffer. Any suggestions?

**Comment by hlissner** [comment]
There's `set-window-margins`:

```elisp
(set-window-margins (selected-window) 1 1)
```

You could add it to popups by adding a hook to `+popup-buffer-mode-hook`:

```elisp
(add-hook! '+popup-buffer-mode-hook
  (set-window-margins (selected-window) 1 1))
```

Is that what you're looking for?

**Comment by nealot** [comment]
I ran into issues because I was originally hooking set-window-margins to +popup-mode-hook. Is +popup-mode not a parent of +popup-buffer-mode?

**Comment by hlissner** [comment]
No, `+popup-mode` is a global minor mode; it toggles the entire popup management system. It gets enabled once, at startup. 

`+popup-buffer-mode` is the buffer-local minor mode, enabled each time a buffer is displayed in a popup window and disabled once that popup has been closed or changed.

I'll see if I can improve their documentation to make the delineation clearer.

**Comment by nealot** [comment]
Is there a way to exclude certain buffers?

**Comment by hlissner** [comment]
@nealot Yikes, so sorry for the late response! This slipped by me.

You can exclude buffers by creating popup rules for them by name:

```elisp
(set-popup-rule! "^\\*Compilation" :ignore t)
```

Hope that helps!
