### ISSUE TITLE
font configuration on mac breaks the setup

### ISSUE THREAD

**Issue by Sparkenstein** [hlissner/doom-emacs#5686]
### What did you expect to happen?

Whenever I enable these lines of code in config.el:

![image](https://user-images.githubusercontent.com/24642451/138654196-e738a224-f268-4438-9abe-de39cda612ac.png)

Doom stops working like this:

![image](https://user-images.githubusercontent.com/24642451/138654326-396491cc-da9d-4e15-ba86-3e9d547e5781.png)

if I comment them out it works normally. I have checked IBM plex mono does exists. this issue comes with any other font and any other weight.

### What actually happened?

As mentioned above.

the errors are:

```
Error (after-init-hook): Error running hook "doom-init-fonts-h" because: (error Font not available #<font-spec nil nil IMB Plex Mono nil nil regular nil nil 17 nil nil nil nil>) Disable showing Disable logging
```

### Steps to reproduce

1. Open emacs given version on mac.
2.  uncomment the fonts config in config.el

### System Information

https://pastebin.com/R82gijFr

**Comment by glennsl** [comment]
Getting the same error.

```
❯ ~/.config/emacs/bin/doom info
> Executing 'doom info' with Emacs 27.2 at 2021-11-04 00:10:41
    generated    Nov 04, 2021 00:10:41
      system       MacOS 10.15.7 Darwin 19.6.0 x86_64
      emacs        27.2 ~/.config/emacs/ -> ~/.config/emacs/
      doom         21.12.0-alpha HEAD -> develop, origin/develop, origin/HEAD 0adaf0308 2021-11-01 02:17:34 +0100 ~/.config/doom/ -> ~/.config/doom/
      shell        /bin/zsh
      features     NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS JSON PDUMPER GMP
      traits       batch server-running envvar-file
      modules      :completion company ivy :ui doom doom-dashboard hl-todo modeline ophints (popup +defaults) treemacs vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold (format +onsave) multiple-cursors snippets :emacs dired electric undo vc :term vterm :checkers syntax :tools (eval +overlay) lookup (lsp +eglot) magit pass :os macos tty :lang data elm emacs-lisp json javascript lua markdown ocaml org rest (rust +lsp) sh web yaml :config (default +bindings)
      packages     (reason-mode) (evil-escape :disable t) (exec-path-from-shell) (gitconfig-mode :recipe (:host github :repo magit/git-modes :files (gitconfig-mode.el))) (gitignore-mode :recipe (:host github :repo magit/git-modes :files (gitignore-mode.el)))
```

**Comment by greym0uth** [comment]
Do you have the font `sans` on your system? For me removing the pitch font setting or setting it to a font I had on my system fixed it. I don't think this is a bug as much as it's just confusing messaging in the error, so you can probably change the label is this issue.

**Comment by tvirolai** [comment]
I'm getting this error as well (on Mac). I haven't had luck with any font-spec configuration I've tried, even though I have the specified fonts installed. However, using the font string format does work. For example the following simplified example does the trick:

```
(setq doom-font "SF Mono-13")
```

**Comment by glennsl** [comment]
This was my font setting when the error occurred:

```
(setq doom-font (font-spec :family "monospace" :size 12 :weight 'semi-light)
      doom-variable-pitch-font (font-spec :family "sans" :size 13))
```

I can resolve it by either commenting it out entirely, or changing both `monospace` and `sans` to actual fonts. I interpreted "monospace" and "sans" not as actual fonts bu generic font family names that would pick any font with the given characteristic, similar to how it works in CSS and elsewhere. My suspicion is that the font resolution mechanism has somehow changed such that these are no longer considered generic, or perhaps a fallback mechanism, which might have masked the issue.

> I don't think this is a bug as much as it's just confusing messaging in the error, so you can probably change the label is this issue.

I'd still consider this a bug, as falling back to some default font while giving a warning seems like much more reasonable behaviour than effectively crashing the editor.

**Comment by tkraak** [comment]
Same issue for me. As mentioned by others above, I was only able to change the font after a new DOOM install via:

```
(setq doom-font "Operator Mono SSm-16")
```

```
> Executing 'doom info' with Emacs 27.2 at 2021-11-09 22:20:02
    generated    Nov 09, 2021 22:20:02
      system       MacOS 12.0.1 Darwin 21.1.0 arm64
      emacs        27.2 ~/.emacs.d/ -> ~/.emacs.d/
      doom         21.12.0-alpha HEAD -> develop, origin/develop, origin/HEAD b4cc1c84d 2021-11-07 01:53:17 +0100 ~/.doom.d/ -> ~/.doom.d/
      shell        /bin/zsh
      features     NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS JSON PDUMPER GMP
      traits       batch server-running envvar-file
      modules      :completion company vertico :ui doom doom-dashboard doom-quit hl-todo modeline ophints (popup +defaults) vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold snippets :emacs dired electric undo vc :checkers syntax :tools (eval +overlay) lookup magit :os macos :lang emacs-lisp markdown org sh :config (default +bindings +smartparens)
```

**Comment by Sparkenstein** [comment]
Using just 
```
(setq doom-font "Operator Mono SSm-16")

```

Worked for me as well. not sure if it's some issue with `font-spec`. feel free to close this issue if mods want or keep it open for tracking

**Comment by hlissner** [comment]
I'll close this issue because:

1. An unavailable font is either a configuration issue (the specified font name is incorrect) or a system issue (the specified font isn't installed/available). 
2. `'regular` is not a valid `:weight` value (see `C-h f font-spec` to see what it supports; it will link to the docs for `set-face-attribute`, which say:

   ```
   :weight

   VALUE specifies the weight of the font to use.  It must be one of
   the symbols ultra-heavy, heavy, ultra-bold, extra-bold,
   bold, semi-bold, medium, normal, book, semi-light,
   light, extra-light, ultra-light, or thin.
   ```

   Using a valid value should get you around the issue.

> I interpreted "monospace" and "sans" not as actual fonts bu generic font family names that would pick any font with the given characteristic, similar to how it works in CSS and elsewhere. My suspicion is that the font resolution mechanism has somehow changed such that these are no longer considered generic, or perhaps a fallback mechanism, which might have masked the issue.

@glennsl Your suspicion is correct. The default fontconfig configuration often specifies fallback defaults for `monospace`, `sans`, and `sans serif`. It's possible that your fontconfig config lacks these for whatever reason. In these rare cases, you must specify one explicitly or remove them altogether (and Emacs will simply use the defaults dictated by GTK).

> I don't think this is a bug as much as it's just confusing messaging in the error, so you can probably change the label is this issue.

@greym0uth How can the error be made clearer? "Font not available" seems self-explanatory (to mean that Emacs can't find the font, so you gotta check your font settings). That said, Emacs produces this error, not Doom, so perhaps it should be reported to them.

**Comment by glennsl** [comment]
> I don't consider this a bug because Doom's default doom-font settings are examples, and are commented out by default.

Seems reasonable to me. I wonder why in my case it was still uncommented though, and unchanged from the default. I've been a Doom user for less than one year, so I shouldn't have a config from before this was commented out 2 years ago either. And it hasn't been changed since I pushed my config to github 10 months ago. I suppose there's a decent chance I've been waffling around initially and tried some things out without completely reverting them though. Just noting this in case others have the same experience and there's some pattern here.

**Comment by panchoh** [comment]
@Sparkenstein, have you noticed that you wrote "IMB Plex" instead of "IBM Plex"?  (This will surely cause a font error).

**Comment by huyiqun** [comment]
I am having the same issue. I can see that the font is installed correctly and `emacs` can see it by running: `(print(font-family-list))`. It is also there when I run `fc-list` in terminal. Using exactly the same setting in Linux, everything works fine; however for Mac, it breaks.

**Comment by shackra** [comment]
I'm experiencing this as well but in GNU/Linux:

```
(setq doom-font (font-spec :family "Iosevka" :size 16)
      doom-big-font (font-spec :family "Iosevka" :size 26)
      doom-variable-pitch-font (font-spec :family "DejaVu Serif Condensed" :size 16))
```

Running `(print (font-family-list))` displays:

```
("Noto Sans Canadian Aboriginal" "Noto Sans Gurmukhi" ...  "Iosevka" ... )
```
`doom-info`:

```
generated    mar 13, 2022 03:58:06
system       "Manjaro Linux" Linux 5.4.181-2-MANJARO x86_64 x
emacs        27.2 ~/.emacs.d/ -> ~/.emacs.d/
doom         21.12.0-alpha HEAD -> master 42e5763782 2022-02-23 17:49:53 +0100 ~/.doom.d/ -> ~/.doom.d/
shell        /bin/zsh
features     XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP
traits       gui server-running envvar-file custom-file byte-compiled-config
custom       warning-suppress-types safe-local-variable-values custom-safe-themes js-indent-level css-indent-offset sgml-basic-offset
modules      :completion (company +childframe) (vertico +icons) :ui doom doom-dashboard doom-quit hl-todo hydra indent-guides (ligatures +extra) modeline ophints (popup +defaults) treemacs unicode vc-gutter vi-tilde-fringe window-select workspaces (&user shackra:tree-sitter) :editor file-templates fold (&user shackra:reformat) lispy multiple-cursors snippets :emacs (dired +icons) electric undo vc :term vterm :checkers syntax (spell +flyspell) grammar :tools (eval +overlay) lookup (lsp +peek) magit pdf rgb (&user shackra:lsp-tailwindcss) :lang (cc +lsp) data (dart +flutter +lsp) emacs-lisp (gdscript +lsp) (go +lsp) json (javascript +lsp) (kotlin +lsp) (latex +lsp) markdown (org +dragndrop +pretty +noter +pomodoro +present) (python +lsp +pyright) (rust +lsp) (scheme +guile) (sh +lsp) (web +lsp) yaml (&user shackra:rego) (&user shackra:deno) (&user shackra:graphql) (&user shackra:pkgbuild) (&user shackra:nginx) :config literate (default +bindings) (&user shackra:me)
packages     (openapi-yaml-mode :recipe (:host github :repo magoyette/openapi-yaml-mode :files (openapi-yaml-mode.el)) :pin 0e2e9e7772b1b819d9f0033c64f03ad074ac6ffd) (svelte-mode :recipe (:host github :repo leafOfTree/svelte-mode) :pin 25d0018036f44ff9bd685a1c9a76d8ba57c1024d) (dockerfile-mode :recipe (:host github :repo spotify/dockerfile-mode) :pin ad06a41259ff2961d603bf23a3a8fbd22dde2161) (graphql-mode :recipe (:host github :repo davazp/graphql-mode) :pin 80e9ac8020f7a4a8a963136698eb97a9fca28f7d) (request :recipe (:host github :repo tkf/emacs-request) :pin 3336eaa97de923f74b90dda3e35985e122d40805)
```
