### ISSUE TITLE
persp-mode errors when +workspace/save called

### ISSUE THREAD

**Issue by samcoy3** [hlissner/doom-emacs#5687]
### What did you expect to happen?

- When I close emacs, the open perspective should automatically save
- When I hit `SPC TAB s`, and select the currently open perspective, the current state of the perspective should save.

### What actually happened?

- When I exit emacs, `persp-mode` sends an error saying:
```
[persp-mode] Error: Can not autosave perspectives -- (wrong-type-argument listp def-magit-status-buffer)
persp-mode can not save perspectives, do you want to exit anyway? (y or n)
```
- A similar error appears when I try to save perspective:
```
setq: Wrong type argument: listp, def-magit-status-buffer
```

Here's a backtrace for the error produced by `SPC TAB s`ing. I can provide the other on request, though given the error messages are similar I image the backtraces will be as well: [PasteBin](https://pastebin.com/NEiFRgSJ)

### Describe your attempts to resolve the issue

I googled the error and looked the persp-mode source. Unfortunately, I don't really understand what it's doing.

### Steps to reproduce

1. Open emacs.
2. Open an existing (saved) workspace.
3. Make some change to a file in the perspective (move the cursor in a file).
4. `M-x +workspace/save` and select (say) the same perspective name that you opened.

### System Information

https://pastebin.com/ftnnTyC1

**Comment by hlissner** [comment]
This issue should now be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by samcoy3** [comment]
Thank you very much, really appreciate the work you do ❤
