### ISSUE TITLE
`viq` includes a closing quote in selection

### ISSUE THREAD

**Issue by otavioschwanck** [hlissner/doom-emacs#5698]
### What did you expect to happen?

select only inside quotes

### What actually happened?

Select the closing quotes

### Steps to reproduce

1 - create a string on ruby-mode
2 - press viq on normal mode

### System Information

https://pastebin.com/rJqXneN8

**Comment by hlissner** [comment]
This issue should now be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
