### ISSUE TITLE
bibtex-actions should be changed to citar in the Biblio module

### ISSUE THREAD

**Issue by peterjbachman** [hlissner/doom-emacs#5723]
### What package(s) should be bumped?

bibtex-actions 

### Why should Doom bump these packages early?

Changed it's name to citar as of 10/31 [see commit here](https://github.com/bdarcus/citar/commit/6e30af6f739ed01437d58d7b3e54a5757e8eb55a). Biblio module is broken and can't update due to name change.

If an upgrade isn't necessary the name should be changed in the module to fix errors when running `doom sync`.

Running `doom sync` with the biblio module enabled gives the following error:

` (error "Could not find package bibtex-actions. Updating recipe repositories: (org-elpa melpa gnu-elpa-mirror el-get emacsmirror-mirror) with ‘straight-pull-recipe-repositories’ may fix this")`

**Comment by reedspool** [comment]
Anyone have a temporary resolution for this? 

I asked the same in discord, for posterity https://discordapp.com/channels/406534637242810369/406554085794381833/906956953606033438

**Comment by peterjbachman** [comment]
I found the easiest solution to fixing this is to change tools/biblio/packages.el to the following:

```
;; -*- no-byte-compile: t; -*-
;;; tools/biblio/packages.el

(package! bibtex-completion :pin "b85662081de98077f13f1a9fac03764702325d28")
(when (featurep! :completion ivy)
  (package! ivy-bibtex :pin "b85662081de98077f13f1a9fac03764702325d28"))
(when (featurep! :completion helm)
  (package! helm-bibtex :pin "b85662081de98077f13f1a9fac03764702325d28"))
(when (featurep! :completion vertico)
  (package! citar :pin "08c6ca0e5b736de50a4d1db5a00ce01b4c2093eb")) 
```

If you change the name of bibtex-actions to citrar the update runs without error. I'm not sure how to create a pull request with this change, since I'm not the best with Github yet.

**Comment by reedspool** [comment]
Thank you @peterjbachman this worked for me! Also suggested in the discord was to change config.el:

packages.el
```
(when (featurep! :completion vertico)
  (package! citar :pin "08c6ca0e5b736de50a4d1db5a00ce01b4c2093eb"))
```


config.el
```
(use-package! citar
  :when (featurep! :completion vertico)
  :after embark
  :defer t
  :config
  (add-to-list 'embark-keymap-alist '(bibtex . citar-map)))
```

From @nicholas https://discordapp.com/channels/406534637242810369/406554085794381833/906980704066342962

**Comment by hlissner** [comment]
This issue should now be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by pakelley** [comment]
FWIW I was running into this, and pulling the develop branch fixed it for me
