### ISSUE TITLE
Email doesn't covert to html

### ISSUE THREAD

**Issue by liujoey** [hlissner/doom-emacs#573]
On latest develop branch. Using :app email to send smtp message. From the source code I see there is a setting which can convert the email to html before send, but it seems not working for me.

From the *message* buffer, I saw following messages, not sure if they are relevant.
```
Sending...
Already sent message via mail; resend? (y or n) n
message-send: No methods specified to send by
Invalid face attribute :inherit mu4e-header-key-face
Invalid face attribute :inherit mu4e-header-key-face [13 times]
Blocking call to accept-process-output with quit inhibited!! [42 times]
```

The mu4e account settings I have is follow:
```
(set! :email "joey.liu@abc.com"
  '((mu4e-sent-folder             . "/joey.liu@abc.com/Sent")
    (mu4e-drafts-folder           . "/joey.liu@abc.com/Drafts")
    (mu4e-trash-folder            . "/joey.liu@abc.com/Trash")
    (smtpmail-smtp-user           . "joey.liu@abc.com")
    (smtpmail-stream-type         . nil)
    (smtpmail-default-smtp-server . "localhost")
    (smtpmail-smtp-server         . "localhost")
    (smtpmail-smtp-service        . 1025)
    (user-full-name               . "Liu, Joey")
    (user-mail-address            . "joey.liu@abc.com")
    (mu4e-compose-signature       . "\nBest regards\n\nJoey Liu\n\n"))
  t)
```

I'm using DavMail application as the local smtp server, it communicates with our corporate MS Exchange server to do the real work.

**Comment by liujoey** [comment]
Found a blog saying that the support of converting html and sent in mu4e is deprecated, but there is a library called org-mime, maybe we should switch?

[Sending html emails from org mode with org mime](http://kitchingroup.cheme.cmu.edu/blog/2016/10/29/Sending-html-emails-from-org-mode-with-org-mime/)

**Comment by liujoey** [comment]
the org-mime.el was in the org-plus-contrib package, but was removed recently. If do a fresh new installation (by removing ~/.emacs.d/.local/ folder), org-mime would not be available anymore.

**Comment by liujoey** [comment]
My current solution is to add org-mime package in private:
```elisp
(package! org-mime
  :recipe (:fetcher github
           :repo "org-mime/org-mime"
           :files ("*")))
```

Then add these code to config
```elisp
  (defun htmlize-before-send ()
    "When in an org-mu4e-compose-org-mode message, htmlize it."
    (when (member 'org~mu4e-mime-switch-headers-or-body post-command-hook)
      (message-mode)
      (org-mime-htmlize)))

  (advice-add 'message-send-and-exit :before 'htmlize-before-send)
```

**Comment by hlissner** [comment]
I apologize for the late response. If we add `htmlize-before-end` to `message-send-hook` instead of advising message-send-and-exit, would this still work?

**Comment by liujoey** [comment]
Can no longer test it, our company just decided to turn on two factors authentication which I no longer be able to check Office 365 emails by Emacs. Sad.

**Comment by liujoey** [comment]
This does not work for me, I guess when the hook is been triggered, the buffer was already been loaded to the mail internal variable, so when you htmlize it here, it doesn't affect that internal variable.

There is also an error in this code, the function `(message-send-and-exit)` will cause dead loop, I guess this function will trigger the `message-send-hook`.

**Comment by hlissner** [comment]
Sorry for the terribly late response, but is this issue still relevant? It appears that org-mu4e no longer uses org-mime, but the org exporter for html, which should resolve the original issue.

**Comment by liujoey** [comment]
I can't verify this anymore because my company stopped support for imap mail box, everybody switched to outlook from Microsoft couple months ago. So I would close this issue. Thank you for your reply anyway.
