### ISSUE TITLE
Used evil function removed in recent version bump

### ISSUE THREAD

**Issue by AnOctopus** [hlissner/doom-emacs#5731]
### What did you expect to happen?

To call `+haskell/evil-open-above` without error.

### What actually happened?

`+haskell/evil-open-above` throws a `void-function: evil-beginning-of-line-or-digit-argument` error.

### Describe your attempts to resolve the issue

`+haskell/evil-open-above` calls `evil-beginning-of-line-or-digit-argument`, which was removed in [a recent evil commit](https://github.com/emacs-evil/evil/commit/17c635f6e1f5) that [doom updated to about a week ago](https://github.com/hlissner/doom-emacs/commit/a08ec4ab168998e2d3de40cbb87eb42b3d958f97). Based on that evil commit, I replaced the call with one to `evil-beginning-of-line` and it appears to work again, but I did not test extensively.

### Steps to reproduce

1. Open a `haskell-mode` buffer.
2. Invoke `+haskell/evil-open-above`

**Comment by ken-scarf** [comment]
Yay! thanks so much for this temporary fix! It was quite annoying that I couldn't insert above line.

**Comment by bixuanzju** [comment]
+1

**Comment by hlissner** [comment]
This issue should now be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
