### ISSUE TITLE
+default/discover-projects does not discover projects

### ISSUE THREAD

**Issue by ineu** [hlissner/doom-emacs#5735]
### What did you expect to happen?

On the fresh installation of emacs `SPC p D` updates the list of projectile projects

### What actually happened?

The list is not updated via `+default/discover-projects`, but is updated via `projectile-discover-projects-in-search-path` 

### Steps to reproduce

1. Stop emacs
2. `rm ~/.emacs.d/.local/cache/projectile*
3. Start emacs
4. Check the `projectile-project-search-path`, it should be a list of strings like `("/home/ineu/work/project1" "/home/ineu/work/project2")`. For me the list is populated by the following snippet:
```
(require 'f)
(setq projectile-project-search-path (f-entries "~/work"))
```
5. Press `SPC p D`
6. Press `SPC p p`, see the empty list of the projects
7. Run `M-x projectile-discover-projects-in-search-path`
8. Press `SPC p p`, see the list full of projects

### System Information

https://pastebin.com/NFkevtBp

**Comment by hlissner** [comment]
This issue should now be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
