### ISSUE TITLE
+default/discover-projects doesn't support the (DIRECTORY . DEPTH) form

### ISSUE THREAD

**Issue by ineu** [hlissner/doom-emacs#5736]
### What did you expect to happen?

When I `(setq projectile-project-search-path '(("~/work" . 2)))`
And I press `SPC p D`
Then I should have my list of projects filled with nested directories.

### What actually happened?

When I `(setq projectile-project-search-path '(("~/work" . 2)))`
And I press `SPC p D`
Then I receive an error: `not: Wrong type argument: stringp, ("~/work" . 2)`

### Describe your attempts to resolve the issue

According to `SPC h v projectile-project-search-path`:
```
You can think of something like $PATH, but for projects instead of executables.
Examples of such paths might be ~/projects, ~/work, (~/github . 1) etc.

For elements of form (DIRECTORY . DEPTH), DIRECTORY has to be a
directory and DEPTH an integer that specifies the depth at which to
look for projects.
```

Looks like at the moment `+default/discover-projects` assumes that the list's elements are all strings and doesn't support the dotted pairs.

### Steps to reproduce

1. Set the variable to a list or dotted pairs, like `(setq projectile-project-search-path '(("~/work" . 2)))`
2. Run `SPC p D`
3. See the errors

### System Information

https://pastebin.com/NFkevtBp

**Comment by hlissner** [comment]
This issue should now be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by ineu** [comment]
It works, thanks you
