### ISSUE TITLE
Install packages from repository or url

### ISSUE THREAD

**Issue by drym3r** [hlissner/doom-emacs#574]
Hi
I can't see if there's a way to use `package!` with either a git repository outside github or with a url, like quelpa does. I've seen that you have this commented:
```lisp
;; (package! hack-mode
;;   :recipe
;;   (:fetcher url :url "https://raw.githubusercontent.com/facebook/hhvm/master/hphp/hack/editor-plugins/emacs/hack-mode.el"))
```
I couldn't make it work anyway, 
So, does package! support those?

PD: Thanks for your work!

**Comment by hlissner** [comment]
Quelpa stopped supporting the `url` fetcher a while back, so the only alternative is to download the entire `facebook/hhvm` project _just_ for its editor plugin, unfortunately.

```elisp
(package! hack-mode
  :recipe
  (:fetcher github :repo "facebook/hhvm" :files "hphp/hack/editor-plugins/emacs/*.el"))
```

For your reference, `:recipe` takes [a MELPA recipe](https://github.com/melpa/melpa#recipe-format).

**Comment by drym3r** [comment]
What about the `git` fetcher? I have the next one and it doesn't work:
```
(package! evil-hardcore-mode :recipe (:fetcher git :repo "https://git.daemons.it/drymer/evil-hardcore-mode"))
```

**Comment by hlissner** [comment]
The `git` fetcher works, but you have to use the `:url` property instead of `:repo`. `:repo` only applies to the github, gitlab and bitbucket fetchers.

**Comment by drym3r** [comment]
I'm triying with this and it doesn't work, is correct?:
```
(package! evil-hardcore-mode :recipe (:fetcher git :url "https://git.daemons.it/drymer/evil-hardcore-mode/"))
```

**Comment by hlissner** [comment]
The url should be `https://git.daemons.it/drymer/evil-hardcore-mode.git`, no?

**Comment by drym3r** [comment]
Thank you very much! I'll try it shortlu, this can be closed
