### ISSUE TITLE
documentation is wrong about format +onsave with rust

### ISSUE THREAD

**Issue by LiEyWe** [hlissner/doom-emacs#5740]
### What did you expect to happen?

When I enable (format +onsave) in init.el, rust files should be formatted on save.
The documentation states that no additional configuration is necessary.

### What actually happened?

Rust files were not formatted on save.

### Describe your attempts to resolve the issue

Adding
``` elisp
(after! rustic
    (setq rustic-format-on-save t))
```
to config.el did work.

### Steps to reproduce

1. Open init.el
2. uncomment (format +onsave)
3. edit a .rs file in a rust project
4. save it

### System Information

https://pastebin.com/YahxaaJP

**Comment by brotzeit** [comment]
The documentation is outdated(the variable was renamed because it's now also possible to run rustfmt before compilation automatically).

You can take a look at the readme of the package https://github.com/brotzeit/rustic#rustfmt

**Comment by brotzeit** [comment]
@LiEyWe I think the issue can be closed.

**Comment by LiEyWe** [comment]
It works. Thank you very much!
