### ISSUE TITLE
Pinned Version of Proof General cannot parse newer Coq versions

### ISSUE THREAD

**Issue by DasNaCl** [hlissner/doom-emacs#5742]
### What package(s) should be bumped?

proof-general

### Why should Doom bump these packages early?

Proof General fails to parse a new kind of version string from Coq due to a spurious regex.
The result of this is a hard-fail right now if one enables `coq-mode`, it is rendered unusable.

The most recent relevant commit that *just fixes the version parsing* is [`38ae8fdf23f37af71b8a4f9717ba48c52653db63`](https://github.com/ProofGeneral/PG/commit/38ae8fdf23f37af71b8a4f9717ba48c52653db63).

I don't think there is anything else to do other than a simple version bump.

**Comment by hlissner** [comment]
This issue should now be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
