### ISSUE TITLE
doom/help-search

### ISSUE THREAD

**Issue by jkroes** [hlissner/doom-emacs#5758]
### What did you expect to happen?

`doom/help-search` invokes `+vertico-file-search` to search org files in `doom-emacs-dir` with my query.  Other commands that use `+vertico-file-search` (e.g., `+default/search-project`) work fine.

### What actually happened?

After typing any query, no results are returned. A red "!" is shown in the prompt line where the query is typed. 

### Describe your attempts to resolve the issue

I instrumented doom/help-search, +vertico-file-search, and consult--grep in turn. Modifying +vertico-file-search by removing :args '("-t" "org") allows results to be shown, though as expected not exclusively within the org help files. This was the only clue I was able to find.

### Steps to reproduce

1. Open Emacs 27.2 or later (mac-emacs or GNU Emacs)
2. Run `doom/help-search`.

### System Information

https://pastebin.com/LH55HcQt

**Comment by jkroes** [comment]
The issue is with a deprecated xref.el variable `xref---marker-ring` used in `+lookup--xref-show`. If you call `doom/help-search`, no error is thrown but a void variable message shows up in the `*Messages*` buffer. Replacing `xref--marker-ring` with `xref--history` seems to do the trick for me.

**Comment by jkroes** [comment]
The issue is with`+vertico-file-search`.  When constructing `consult-ripgrep-argss`, the function calls `mapconcat` to shell quote any non-default `args` passed to it. When `args` are present, there's no separating space between  them and the trailing period. I hacked together a solution by modifying `consult-ripgrep-args` below:

```
(cl-defun +vertico-file-search (&key query in all-files (recursive t) prompt args)
  "Conduct a file search using ripgrep.

:query STRING
  Determines the initial input to search for.
:in PATH
  Sets what directory to base the search out of. Defaults to the current project's root.
:recursive BOOL
  Whether or not to search files recursively from the base directory."
  (declare (indent defun))
  (unless (executable-find "rg")
    (user-error "Couldn't find ripgrep in your PATH"))
  (require 'consult)
  (setq deactivate-mark t)
  (let* ((project-root (or (doom-project-root) default-directory))
         (directory (or in project-root))
         (consult-ripgrep-args
          (concat "rg "
                  (if all-files "-uu ")
                  (unless recursive "--maxdepth 1 ")
                  "--null --line-buffered --color=never --max-columns=1000 "
                  "--path-separator /   --smart-case --no-heading --line-number "
                  "--hidden -g !.git "
                  ;; When not "" (i.e., with args present), there is no space
                  ;; before the trailing ".". This makes doom/help-search fail.
                  (let ((result (mapconcat #'shell-quote-argument args " ")))
                    (unless (string= "" result) (setq result (concat result " ")))
                    result)
                  "."))
         (prompt (if (stringp prompt) (string-trim prompt) "Search"))
         (query (or query
                    (when (doom-region-active-p)
                      (regexp-quote (doom-thing-at-point-or-region)))))
         (consult-async-split-style consult-async-split-style)
         (consult-async-split-styles-alist consult-async-split-styles-alist))
    ;; Change the split style if the initial query contains the separator.
    (when query
      (cl-destructuring-bind (&key type separator initial)
          (consult--async-split-style)
        (pcase type
          (`separator
           (replace-regexp-in-string (regexp-quote (char-to-string separator))
                                     (concat "\\" (char-to-string separator))
                                     query t t))
          (`perl
           (when (string-match-p initial query)
             (setf (alist-get 'perlalt consult-async-split-styles-alist)
                   `(:initial ,(or (cl-loop for char in (list "%" "@" "!" "&" "/" ";")
                                            unless (string-match-p char query)
                                            return char)
                                   "%")
                     :type perl)
                   consult-async-split-style 'perlalt))))))
    (consult--grep prompt #'consult--ripgrep-builder directory query)))

```

**Comment by hlissner** [comment]
This issue should now be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for the detailed bug report and bringing it to my attention!
