### ISSUE TITLE
vertico +icons can't work for "switch workspace buffer" and "consult-buffer"

### ISSUE THREAD

**Issue by pluswu** [hlissner/doom-emacs#5763]
### What did you expect to happen?

dired +icons worked fine
![dired-icons](https://user-images.githubusercontent.com/1171583/141292553-8248ff75-7898-42ad-9c40-8eea52c9675d.png)

helm +icons works fine too
![helm](https://user-images.githubusercontent.com/1171583/141292563-500ad17f-ca6f-4124-97ba-b15cb63c1bdc.png)

### What actually happened?

vertico +icons workspace-buffer icons not work
![workspace-buffer](https://user-images.githubusercontent.com/1171583/141292557-4f61f9f0-f859-4570-acd0-15ab11fc3efe.png)

vertico +icons consult-buffer icons broken too
![consult-buffer](https://user-images.githubusercontent.com/1171583/141292835-1097785e-ff45-42ef-8c6e-5132d6181cd5.png)

### Describe your attempts to resolve the issue

i have used these follow code  from [https://github.com/domtronn/all-the-icons.el] checked font config,  it's works fine

```elisp
(all-the-icons-octicon "file-binary")  ;; GitHub Octicon for Binary File
(all-the-icons-faicon  "cogs")         ;; FontAwesome icon for cogs
(all-the-icons-wicon   "tornado")      ;; Weather Icon for tornado
```

what should i check for next？

### Steps to reproduce

start emacs 
SPC bb show buffer list

### System Information

manjaro/emacs-28.0.60-native-comp

**Comment by hlissner** [comment]
I can't reproduce this.

![image](https://user-images.githubusercontent.com/510883/143608778-e942c95d-992e-483f-b569-6e59bf79bb3f.png)
![image](https://user-images.githubusercontent.com/510883/143608798-0cc9c8fd-3706-47e7-a3dc-834600e7abfe.png)

1. Update Doom and double check your private config.
2. Include your `M-x doom/info` in your bug report (and always do so in the future).

**Comment by steveb-123** [comment]
I was able to reproduce the buffer icons fail, accidentally, when I had erroneously enabled both `(helm +fuzzy +icons)` _and_ `vertico` in the `:completion` section of `init.el`.

Switching to `(vertico +icons)` got me to where I wanted to get. The helm-only route worked for icons, but doesn't work with `citar`, as far as I can tell, which I need. (Slightly unrelated to OP, but leaving it here as a hint for desperate googlers.)

**Comment by ryankhart** [comment]
> a hint for desperate googlers

Hey that's me! Thanks! You tip worked for me.
