### ISSUE TITLE
please bump lsp

### ISSUE THREAD

**Issue by anquegi** [hlissner/doom-emacs#5765]
### What package(s) should be bumped?

lsp-mode, dap-mode, lsp-java

### Why should Doom bump these packages early?

I opened the [issue](https://github.com/emacs-lsp/dap-mode/issues/531) on this dap-mode and get this problem
[comment](https://github.com/emacs-lsp/dap-mode/issues/531#issuecomment-953533686)
On a fresh `doom upgrade` today the problem already exists in my mac

**Comment by gagbo** [comment]
Fixed in emacs-lsp/lsp-java@b3f2081 ([source](https://github.com/emacs-lsp/dap-mode/issues/531#issuecomment-966508285))
