### ISSUE TITLE
Org roam node missing after `org-roam-capture`

### ISSUE THREAD

**Issue by dirodriguezm** [hlissner/doom-emacs#5775]
### What did you expect to happen?

Org roam node should be still available after capturing into it

### What actually happened?

When I capture into an existing node, the captured text gets inserted, but then, the file is no longer visible by org-roam.

Example screenshots

1. Created two files, project and version inside the project file with a backlink
![image](https://user-images.githubusercontent.com/18015991/141691782-b70a68e1-0c10-44b0-bbc0-d9ade0604bc8.png)
2. Add a task with `org-roam-capture`
![image](https://user-images.githubusercontent.com/18015991/141691803-ed7520b3-0e4f-4502-ae57-6926fa560355.png)

### Describe your attempts to resolve the issue

I reinstalled doom multiple times, reinstall emacs, reinstall org-roam by removing org-roam2 from :lang org and the issue happened every time. I even posted an issue on org-roam's github.

Then I installed org-roam on vanilla emacs and realized that the problem was not present there, so I did a clean install of doom, without my config and only enabled org-roam which made the issue to happen again so it is a doom problem :(

### Steps to reproduce

1. Create node using `org-roam-node-find` with this template:
    ```
    ("t" "test" plain "%?"
             :if-new (file+head "projects/${slug}.org" "#+title: ${title}\n* First\n* Second")
             :unnarrowed t)
    ```
    So you end up with a file like this
    ```
    #+title: test

    * First
    * Second
    ```
2. Capture into previous node using `org-roam-capture` and this template:
```
("n" "new" entry "** TODO %?" 
        :if-new (file+olp "${slug}.org" ("First")))
```
So you end up with a file like this
```
#+title: test

* First
** TODO Captured note
* Second
```

At this point, the file "test" is no longer visible in org-roam

### System Information

https://pastebin.com/f04iwH7p

**Comment by hlissner** [comment]
Does unpinning org-roam fix the issue? I.e.

1. Add `(unpin! org-roam)` to `~/.doom.d/packages.el`
2. Run `$ doom sync -u`
3. Restart Emacs

**Comment by dirodriguezm** [comment]
Hi @hlissner, thanks for making the time to look at this issue. 

I tried unpinning as suggested, but it didn't fix the issue.
