### ISSUE TITLE
Error when insert Russian text in Table in org-mode 

### ISSUE THREAD

**Issue by romwhite82** [hlissner/doom-emacs#5784]
### What did you expect to happen?

When  create table in org mode and insert text its column in Russian, text should have been inserted and table aligned. 

### What actually happened?

Error occurred:

`Error (evil-insert-state-exit-hook): Error running hook "+org-realign-table-maybe-h" because: (void-function backtrace-get-frames)`
`
And i can't insert anything else.

### Describe your attempts to resolve the issue

When  insert text in English, all works fine.  
I update Doom, but it not helps.

### Steps to reproduce

1. Open Emacs
2. Create org-file
3. Insert table ||||
4. Move cursor into column and enter in INSERT-mode
5. Change Layout to Russian and begin type text
Option for switch layout in my config.el
`
(set-language-environment "Russian")
(keyboard-translate ?\C-a ?\C-\\)
`

### System Information

https://pastebin.com/RHKQaSXR

**Comment by romwhite82** [comment]
`unpin! org-mode` and `./doom sync` solve the problem

**Comment by hlissner** [comment]
This issue should now be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by romwhite82** [comment]
Try fresh install. All works fine! Thx!!!!
