### ISSUE TITLE
`wrong-number-of-arguments: #<subr general-unbind-non-prefix-key> 5` errors at startup

### ISSUE THREAD

**Issue by llight3** [hlissner/doom-emacs#5785]
### What did you expect to happen?

After the default install I expect the splash screen to load and the default keybindings to work

### What actually happened?

doom loads a warning buffer with the following in and keybindings are broken
```
Error (doom-init-ui-hook): Error running hook "persp-mode" because: (wrong-number-of-arguments #<subr general-unbind-non-prefix-key> 5) Disable showing Disable logging
Error (doom-first-input-hook): Error running hook "evil-snipe-mode" because: (wrong-number-of-arguments #<subr general-unbind-non-prefix-key> 5) Disable showing Disable logging
```

### Describe your attempts to resolve the issue

I tried using -debug-init but this didn't seem to help since it left emacs in the same state

### Steps to reproduce

install emacs from source with ./configure --with-native-compilation --with-mailutils --with-imagemagick --with-xwidgets --with-dbus --without-libsystemd --with-x
run doom install 
run emacs

### System Information

https://pastebin.com/gWDuV010

**Comment by ankhers** [comment]
I'm having the same issue at the moment. Also using nativecomp. Let me know if I can provide any extra details.

**Comment by quangIO** [comment]
I can confirm this issue using https://github.com/emacs-mirror/emacs/commit/ce2f7335f1f4ec8d276e47de79b3c9bd9797233d with native-comp and xwidgets on MacOS

**Comment by yuuyins** [comment]
same doom is unusable.

**Comment by hlissner** [comment]
I can't reproduce this issue. `general-unbind-non-prefix-key` is not used directly by Doom, so I suspect an upstream or local configuration issue. 

Can any of you [produce a backtrace](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#how-to-extract-a-backtrace-from-an-error) from the error?

**Comment by yuuyins** [comment]
@hlissner if you want try emacs 29 compiled with native comp, or some recent commit from nix-community/emacs-overlay with emacsGcc. --debug-init doesn't help, M-x doesn't work

**Comment by yuuyins** [comment]
more specifically i'm using 

```nix
  emacs-overlay = (import (builtins.fetchTarball {
    url = "https://github.com/nix-community/emacs-overlay/archive/88c62860a48ce89a4631520e4a32037702cc285e.tar.gz";
    sha256 = "1vyxjjjra0mlfmay7bnys11mpdh0ly0c0mckv6fs2sgjh55wb8fg";
  }));
```

**Comment by yuuyins** [comment]
@hlissner that function is from https://github.com/noctuid/general.el/blob/master/general.el#L2252

**Comment by hlissner** [comment]
From the sound of it, the signature of `define-key` has changed on the tip of Emacs 29. If so, this should be raised [upstream](https://github.com/noctuid/general.el). I don't have access to 29 at the moment, so your best bet is to check out 28.x. I don't recommend using 29+; there are breaking updates almost every other week.

**Comment by sekunho** [comment]
`emacs-overlay` is a bit weird right now because 28 doesn't exist. `emacsGcc` points to 29, `emacsUnstable` points to 27 https://github.com/nix-community/emacs-overlay/issues/176. It's a bit difficult to look for the commit with 28, but I found a [comment](https://gist.github.com/mjlbach/179cf58e1b6f5afcb9a99d4aaf54f549#gistcomment-3890431) with a commit hash of 28. This requires a full rebuild though since the binary is probably gone from Cachix. I don't really have the time to sift through the commit history for the latest commit with 28, especially since the commits aren't labeled anything specific.

```nix
  nixpkgs.overlays = [
    (import (builtins.fetchTarball {
      url = https://github.com/nix-community/emacs-overlay/archive/8320c615b706f0d459544d7d37a59c5a5ff5e7e0.tar.gz;
      sha256 = "1pajyn4n0yzi8qxlqjlh20zhdifxfvxqdcjmphqmb8b5p2grk2rx";
    }))
  ];

  services.emacs = {
    package = pkgs.emacsGcc;
    enable = true;
  };
```

```sh
[sekun@nixos:~]$ emacs --version
GNU Emacs 28.0.50
Copyright (C) 2021 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of GNU Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
```

**Comment by yuuyins** [comment]
@sekunho the issue was introduced after initial 29 commit. so nix-community/emacs-overlay/archive/f01c9352ea15574602234feea5b4dc25df26a77a.tar.gz, which is 29 commit 12d554e5c54487d753a133c048e262f3d54019bd, works.  henrik likely was referring to latest changes in https://github.com/emacs-mirror/emacs/commits/master/src/keymap.c

**Comment by doyougnu** [comment]
For what its worth commit `64580e3ac034e2704895a272f341a0729d165b93` works for me:

```
let unstable = import <unstable> { overlays = [
      (import (builtins.fetchTarball {
        url = https://github.com/nix-community/emacs-overlay/archive/64580e3ac034e2704895a272f341a0729d165b93.tar.gz;
      }))
    ];};
```

This is dated to just 18 days ago: https://github.com/nix-community/emacs-overlay/commit/64580e3ac034e2704895a272f341a0729d165b93

So a not-so-great workaround seems to be to pick a commit, point emacs-overlay to the commit (by changing the url from `blah/blah/master.tar.gz` to `blah/blah/<commit>.tar.gz` like I have above, and then rebuild. This allows you to use emacs 29 with native compilation and doom.

**Comment by qleguennec** [comment]
I reproduce this commit on emacs 54b2bd1be6715cbc6bc87e2a6e65ffa04aff256b

**Comment by sekunho** [comment]
@yuuyins Yeah I just want to give the commit with 28 since 29 is more unstable.

**Comment by SwiftLawnGnome** [comment]
The error is apparently the advice general adds to `define-key`. putting 
```
(general-auto-unbind-keys :off)
(remove-hook 'doom-after-init-modules-hook #'general-auto-unbind-keys)
```
in my config eliminated the issue.

**Comment by jackmac92** [comment]
FYI if you're using emacs-overlay and found this issue, you probably want to use `emacsUnstable` variants instead (unstable variants are the last tagged release, as opposed to the head of master)

```
These attributes are named emacsGit and emacsUnstable. emacsGit is built from the latest master branch and emacsUnstable is built from the latest tag.
```

**Comment by hlissner** [comment]
This issue was resolved and the responsible package was bumped in 5535457. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
