### ISSUE TITLE
How to enable the rjsx-mode for files with `.tsx.` and `.jsx` extensions

### ISSUE THREAD

**Issue by emadbaqeri** [hlissner/doom-emacs#5793]
### Describe your request

I'm a javascript developer, I'm working on some projects with lovely typescript language. in every file that I'm visiting and need to develop in the file I need to enable the `rjsx-mode` manually. is there any way of doing that? I know there should be but can you please help me on this? 

### Briefly explain its use-case

1. Typescript development 
2. React and React-Native Development
3. Can edit `jsx` more easier

**Comment by ckruse** [comment]
`rjsx-mode` does not handle type annotations. You can activate it by removing `typescript-tsx-mode` from `auto-mode-alist` and adding `rjsx-mode` for `.tsx` files:

~~~elisp
(setq auto-mode-alist (delete '("\\.tsx\\'" . typescript-tsx-mode) auto-mode-alist))
(add-to-list 'auto-mode-alist '("\\.tsx\\'" . rjsx-mode))
~~~

But it wont work very well.

To work with TSX files there are currently two popular options:

- use `typescript-mode` and use [`tree-sitter`](https://github.com/emacs-tree-sitter/elisp-tree-sitter) for highlighting
- use web-mode

Doom Emacs does the latter, I guess because Treesitter support is very new to Emacs and web-mode has more features (e.g. auto-closing tags, etc).

**Comment by emadbaqeri** [comment]
Hi @ckruse, thanks for your help, I think I should handle the problem with `typescript-mode`, as you mentioned `jsx-mode` is not the one that is going to do the job for me when I switch to the `jsx-mode` in `.tsx` files the typescript mode is missing that way

**Comment by ckruse** [comment]
Treesitter support is not yet merged. While waiting for it you can do this now by adding this to your `packages.el`:

~~~elisp
(package! tree-sitter)
(package! tree-sitter-langs)
~~~

and this to your `config.el`:

~~~elisp
(use-package! typescript-mode
  :init
  (define-derived-mode typescript-tsx-ts-mode typescript-mode "typescript-tsx")
  (add-to-list 'auto-mode-alist (cons (rx ".tsx" string-end) #'typescript-tsx-ts-mode))
  t)

(add-hook! typescript-tsx-ts-mode 'lsp!)

(use-package! tree-sitter
  :hook (prog-mode . turn-on-tree-sitter-mode)
  :hook (tree-sitter-after-on . tree-sitter-hl-mode)
  :config
  (require 'tree-sitter-langs)

  (tree-sitter-require 'tsx)
  (add-to-list 'tree-sitter-major-mode-language-alist '(typescript-tsx-ts-mode . tsx))

  ;; This makes every node a link to a section of code
  (setq tree-sitter-debug-jump-buttons t
        ;; and this highlights the entire sub tree in your code
        tree-sitter-debug-highlight-jump-region t))
~~~

But be aware, this is far away from perfect.

**Comment by emadbaqeri** [comment]
sorry, I don't know anything about lisp language, what does this line do? doom-emacs throw error for this line:
```lisp
(add-hook! typescript-tsx-ts-mode 'lsp!)
```

**Comment by emadbaqeri** [comment]
> Treesitter support is not yet merged. While waiting for it you can do this now by adding this to your `packages.el`:
> 
> ```emacs-lisp
> (package! tree-sitter)
> (package! tree-sitter-langs)
> ```
> 
> and this to your `config.el`:
> 
> ```emacs-lisp
> (use-package! typescript-mode
>   :init
>   (define-derived-mode typescript-tsx-ts-mode typescript-mode "typescript-tsx")
>   (add-to-list 'auto-mode-alist (cons (rx ".tsx" string-end) #'typescript-tsx-ts-mode))
>   t)
> 
> (add-hook! typescript-tsx-ts-mode 'lsp!)
> 
> (use-package! tree-sitter
>   :hook (prog-mode . turn-on-tree-sitter-mode)
>   :hook (tree-sitter-after-on . tree-sitter-hl-mode)
>   :config
>   (require 'tree-sitter-langs)
> 
>   (tree-sitter-require 'tsx)
>   (add-to-list 'tree-sitter-major-mode-language-alist '(typescript-tsx-ts-mode . tsx))
> 
>   ;; This makes every node a link to a section of code
>   (setq tree-sitter-debug-jump-buttons t
>         ;; and this highlights the entire sub tree in your code
>         tree-sitter-debug-highlight-jump-region t))
> ```
> 
> But be aware, this is far away from perfect.

**Comment by ckruse** [comment]
You have to enable the `lsp` feature in you `init.el` for that line. If you don't want lsp support, just remove or comment that line.

**Comment by emadbaqeri** [comment]
> You have to enable the `lsp` feature in you `init.el` for that line. If you don't want lsp support, just remove or comment that line.

Thank you really much and nice to meet you.
