### ISSUE TITLE
Emacs does not pick up themes when run as daemon

### ISSUE THREAD

**Issue by timotheosh** [hlissner/doom-emacs#5804]
### What did you expect to happen?

After starting emacs with emacs --daemon and then connecting with an emacsclient, I should see the Doom dashboard, with the defautl Doom theme:
![image](https://user-images.githubusercontent.com/5214372/142745928-90d441fb-6500-4071-8561-849aefab7eb9.png)

### What actually happened?

After starting emacs with emacs --daemon and then connecting with an emacsclient I get:
![image](https://user-images.githubusercontent.com/5214372/142745945-968bc46f-2d2b-430f-aeb3-fa5aa017595a.png)

### Describe your attempts to resolve the issue

I tried running in debug mode but was not able to get useful information (my Emacs debug-fu is not great)

### Steps to reproduce

1. git clone latest Doom Emacs
2. Install Emacs 27.1. 
3. Run doom install
4. run emacs as a daemon
5. connect to daemon with emacsclient.

### System Information

https://pastebin.com/YBB10Zec

**Comment by hlissner** [comment]
I can't reproduce this on vanilla Doom (on Emacs 27.1, 27.2, 28, or 29). Please double check your private config and try to reproduce it [with your config disabled](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#testing-in-dooms-sandbox).

Also, it seems you're using Chemacs, which could cause this. See if you can reproduce this without Chemacs.

**Comment by timotheosh** [comment]
I can't seem to reproduce this either now, either with or without Chemacs. Closing.
