### ISSUE TITLE
Error in biblio module: citar required by biblio/config.el but only optionally installed

### ISSUE THREAD

**Issue by natejlong** [hlissner/doom-emacs#5811]
### What did you expect to happen?

1. I enable the new biblio module
2. I run `doom sync`
3. I start emacs successfully without errors

### What actually happened?

1. I enable the new biblio module
2. I run `doom sync`
3. I start emacs, but get a startup error 
```Error in a Doom module: modules/tools/biblio/config.el, (file-missing Cannot open load file No such file or directory citar-org)```

The `emacs --debug-init` output is included in the pastebin below.

### Describe your attempts to resolve the issue

I believe the issue is because the `config.el` file references `citar-org`: https://github.com/hlissner/doom-emacs/blob/180a7c261f99c0a0e38207aa0e834cba17f8d6d2/modules/tools/biblio/config.el#L56-L60

but the `citar-org` package is only _optionally_ installed in the `packages.el` https://github.com/hlissner/doom-emacs/blob/180a7c261f99c0a0e38207aa0e834cba17f8d6d2/modules/tools/biblio/packages.el#L10-L11

I've worked around this in two ways, locally:
1. Just removing the `org-citar` config block, since I wasn't using citar anyways
2. Enabling the `:completion vertico` flag so that the citar package _is_ picked up and the config works as expected.

Both of these workarounds are what make me believe the explanation above.

I'd expect that the `biblio` module is self-sufficient and doesn't require any other flags to be enabled for it to successfully work. `citar-org` should either always be installed or otherwise its config block should gated so it only gets evaluated if citar is installed, but I don't know how to accomplish that best. 

Hopefully my guess is right, but my apologies if this is not actually the source of the issue!

### Steps to reproduce

1. Install the latest commit of the doom emacs branch
2. Enable the new `biblio` module, with the `:completion vertico` flag _disabled_
3. Launch emacs (and see the error)

### System Information

https://pastebin.com/E9Z9xSby

**Comment by natejlong** [comment]
cc @bdarcus as I know you're heavily involved in the biblio module (and `citar` of course!) 

While I'm here, thank you bdarcus, and everyone else involved, so much for your work on the biblio module, and your work on org citations in general! I've been following the biblio PR since it got spun up and I'm so excited to get it all working as an official doom module. This bug report is just a minor friction point I wanted to point out, no big deal in comparison to the amazing work you've done on this project!

**Comment by bdarcus** [comment]
So to be clear,  @natejlong, you got the error when using the ivy or helm completion module?

**Comment by darrenkenny** [comment]
I can confirm that testing for the use of vertico completion fixes this error for me (I use Ivy still):

```diff
diff --git a/modules/tools/biblio/config.el b/modules/tools/biblio/config.el
index 6d0cd390f23e..cc5c575ea48b 100644
--- a/modules/tools/biblio/config.el
+++ b/modules/tools/biblio/config.el
@@ -53,8 +53,9 @@

 ;;;; Third-party

-(use-package! citar-org
-  :when (featurep! :lang org +roam2)
-  :config
-  ;; Include property drawer metadata for 'org-roam' v2.
-  (setq citar-org-note-include '(org-id org-roam-ref)))
+(when (featurep! :completion vertico)
+    (use-package! citar-org
+      :when (featurep! :lang org +roam2)
+      :config
+      ;; Include property drawer metadata for 'org-roam' v2.
+      (setq citar-org-note-include '(org-id org-roam-ref))))
```

**Comment by bdarcus** [comment]
Can you please confirm the solution in #5810 works for you, and weigh in there?

**Comment by natejlong** [comment]
Just to confirm, those changes did resolve the issue. Thank you everyone!
