### ISSUE TITLE
Switch from github-review to code-review (A new package from the same dev that supersedes the old-package) 

### ISSUE THREAD

**Issue by gi-yt** [hlissner/doom-emacs#5812]
### What package(s) should be bumped?

[github-review](https://github.com/charignon/github-review) -> [code-review](https://github.com/wandersoncferreira/code-review)

### Why should Doom bump these packages early?

According to this [reddit post](https://www.reddit.com/r/emacs/comments/qz8req/comment/hlmfbre/?utm_source=share&utm_medium=web2x&context=3), one of the main contributors to github-review, wandersoncferreira has decided to make his own version which uses magit-section instead of diffs and plain text.

You might want to switch to this instead.

If I have time hopefully i can make a PR regarding the same

Regards, 
Arya

**Comment by hlissner** [comment]
Sounds good to me. I'm a bit swamped, so I won't be able to work on this under after the 21.12 release, but I'll welcome PRs!
