### ISSUE TITLE
better-jumper-jump-backward is remapped to obsolete xref-pop-marker-stack

### ISSUE THREAD

**Issue by clementguidi** [hlissner/doom-emacs#5813]
### What did you expect to happen?

In C mode, when pressing `M-.` to lookup code, and then `M-,`, the cursor should jump back to its original location.

Please note that we're dealing with two similar keystrokes `M-.` and `M-,`, don't mix them up.

### What actually happened?

When using RTags, pressing `M-,` doesn't move the cursor, as the xref history stack appears to be empty.

The following log is displayed:

```
user-error: At start of xref history
```

### Describe your attempts to resolve the issue

When using RTags, `M-.` (bound to `+lookup/definition`) uses better jumper to manage the location history.

Using `M-x better-jumper-jump-backward` has the expected behavior of sending the cursor back to the original location. But `M-,` isn't bound to `better-jumper-jump-backward`.

In `core/core-editor.el`, `better-jumper-jump-backward` is remapped to `xref-pop-marker-stack`. See below.

 https://github.com/hlissner/doom-emacs/blob/9634500a3bc5f4335427a0ed309f43c7ea5d1026/core/core-editor.el#L434

However, the function now obsolete, and has been replaced by `xref-go-back`.

Remapping `better-jumper-jump-backward` to `xref-go-back` fixes the issue.

### Steps to reproduce

1. Open a C source file in Emacs
2. Make sure we're using RTags. `+lookup-definition-functions` is set `(rtags-find-symbol-at-point t)`
3. If needed, create a Projectile project (e.g. add source file to a git repo) and index it with RTags
4. Lookup a symbol definition with `M-.`
5. Go back to the previous location with `M-,`

### System Information

https://paste.debian.net/1220472

**Comment by hlissner** [comment]
This issue should now be resolved. The issue (for posterity): `xref-go-{back,forward}` were added to the xref library in Emacs 29, deprecating `xref-pop-marker-stack`, which Doom has remapped to `better-jumper-jump-backward`. These two new commands needed to be remapped, and were in 3e5f9a1 (#5815).

Thanks for bringing it to my attention and for submitting a PR to address the issue!
