### ISSUE TITLE
`zig-format-on-save` resets writeroom-mode and doom-BIG-font-mode

### ISSUE THREAD

**Issue by WesterWest** [hlissner/doom-emacs#5817]
### What did you expect to happen?

Doom already supports it's own formatter (`+format/buffer`) which does work correctly

### What actually happened?

Both formatters are run at the same time. The `zig-format-on-save` does the same as just setting globally doom to format on save. The file gets formatted even if the `zig-format-on-save` is set to `nil`

### Describe your attempts to resolve the issue

`(setq zig-format-on-save nil)` resolves this issue. It should be turned off by default if the doom format on save is active

### Steps to reproduce

1. turn on `(format +onsave)`
2. turn on `(zig +lsp)`
3. open zig buffer
4. turn on `writeroom-mode` or `doom-BIG-mode`
5. save buffer -> mode resets

### System Information

https://pastebin.com/xLWEqPrK

**Comment by hlissner** [comment]
This issue should now be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
