### ISSUE TITLE
+default/search-project-for-symbol-at-point no longer search the whole project

### ISSUE THREAD

**Issue by ineu** [hlissner/doom-emacs#5831]
### What did you expect to happen?

`SPC *` on a symbol searches the whole project

### What actually happened?

`SPC *` on a symbol searches only the directory of the current buffer

### Steps to reproduce

According to `git bisect` the change happened in 411ed0c8f8e12d106a64a56ae437ba45c1bcd1f2
```
commit 411ed0c8f8e12d106a64a56ae437ba45c1bcd1f2
Author: Henrik Lissner <git@henrik.io>
Date:   Sat Nov 20 00:02:11 2021 +0100

    fix(default): search commands not respecting default-directory

    Commands that delegate to `+default/search-project-for-symbol-at-point`
    to search a directory (like +default/org-notes-search) would not scope
    searches to default-directory.
```

### System Information

https://pastebin.com/1VWh526T

**Comment by hlissner** [comment]
This issue should now be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by ineu** [comment]
It is fixed, thank you!
