### ISSUE TITLE
wrong type argument: commandp, +format/region-or-buffer

### ISSUE THREAD

**Issue by wingyplus** [hlissner/doom-emacs#5833]
### What did you expect to happen?

When I press `SPC c-f` on my code. It should format my code.

### What actually happened?

It returns an error. Here is stack after called `(setq debug-on-error t)`:

```
Debugger entered--Lisp error: (wrong-type-argument commandp +format/region-or-buffer)
  call-interactively(+format/region-or-buffer nil nil)
  command-execute(+format/region-or-buffer)
```

### Describe your attempts to resolve the issue

I found after I try to formatting my code with `SPC c-f`. 

### Steps to reproduce

* Open an emacs with any project, in my case, I open project under https://github.com/wingyplus/must. 
* Make sure the LSP is started.
* Edit something, formatting code with `SPC c-f`. 
* Found an error
* Try another file like elisp file, under doom emacs itself or elixir. Not work for me. :(

### System Information

https://pastebin.com/cTDir5CJ

**Comment by hlissner** [comment]
Enable the `:editor format` module.
