### ISSUE TITLE
Display issue with popup buffer 

### ISSUE THREAD

**Issue by peter-wd-1** [hlissner/doom-emacs#5834]
### What did you expect to happen?

Whenever emacs is trying to pup up mini buffer(except suggestion list buffer) at the cursor location, it shows the mini buffer with another frame pops up then the cursor moves its focus to the mini buffer. 
Then never come back to the original frame. I can't remove or control the new frame
Which package is creating this buffer?

### What actually happened?

Another frame, second one(I should go back to original frame by using mouse):
![Screen Shot 2021-11-25 at 10 58 08 AM](https://user-images.githubusercontent.com/65737603/143474773-24385343-338d-4f5f-8973-6c7e4d3e8836.png)

![Screen Shot 2021-11-25 at 10 58 03 AM](https://user-images.githubusercontent.com/65737603/143474902-f8abe031-a6a6-4299-b976-4177cfca268e.png)

If I go back to mifi buf It shows nothing.
![Screen Shot 2021-11-25 at 11 18 32 AM](https://user-images.githubusercontent.com/65737603/143475106-02690d87-cf39-48ce-8635-a9231a1fd820.png)

### Describe your attempts to resolve the issue

I've tried to fine similar issue but look like It only me having this issue?

### Steps to reproduce

1. open emacs 
2. open js file with lsp 
3. move to cursor to objects that has comment for description(jsdoc comment)
4. emacs create another frame(not window) that shows nothing
5. manually go back to original frame
6. I can see the mini buffer.
7. The other frame can be controlled somehow 

### System Information

https://pastebin.com/mt1u4X2J

**Comment by hlissner** [comment]
It's an lsp feature, not a bug with Doom.

How to identify/disable lsp-mode's features: <https://emacs-lsp.github.io/lsp-mode/tutorials/how-to-turn-off/>

Add them to `~/.doom.d/config.el` inside a `(after! lsp-mode ...)` block.

**Comment by peter-wd-1** [comment]
It's a feature but not sure creating another frame in other monitor is also what lsp-mode intended. 
(And I think no.2 frame is supposed to disappear even though It's internally creating another frame)
But I just turned off the feature anyway so

Thank you!
