### ISSUE TITLE
superword-mode dont work at Typescript language

### ISSUE THREAD

**Issue by eperfect** [hlissner/doom-emacs#5844]
### What did you expect to happen?

I use javascript model for typescript programming, but the superword-mode don't work, won't take word like FILE_NAME as one word, even add **(global-superword-mode t)** to config file.
Actions such as **daw**  **ciw** should take word contains '_' and '-' as one word.

### What actually happened?

Words like FILE_NAME taken as two word

### Steps to reproduce

```
:lang
(javascript +lsp)
```
Use javascript model and lsp server editing Typescript file.

### System Information

https://pastebin.com/cxknTn6E

**Comment by hlissner** [comment]
Not a bug, just Emacs+evil defaults. See https://github.com/hlissner/doom-emacs/blob/develop/docs/faq.org#how-do-i-get-motions-to-treat-underscores-as-word-delimiters for a solution.

**Comment by eperfect** [comment]
> Not a bug, just Emacs+evil defaults. See https://github.com/hlissner/doom-emacs/blob/develop/docs/faq.org#how-do-i-get-motions-to-treat-underscores-as-word-delimiters for a solution.

Before submit this issue I looked up faq and tried this solution, worked with Go mode but not Typescript.
