### ISSUE TITLE
Please enable wgrep integration in vertico by default

### ISSUE THREAD

**Issue by HouzuoGuo** [hlissner/doom-emacs#5848]
### Describe your request

Hello! I really like the new default completion system vertico - it looks so much better than ivy which I've been using for years. However, there is one feature I'm missing quite a bit from vertico, that is the "wgrep" integration.

### Briefly explain its use-case

Using the ivy + wgrep combination, I can perform a mass-refactoring fairly easily by first searching for the keywords of interest:
![image](https://user-images.githubusercontent.com/563872/143841677-f096ff92-3bcc-4b09-aef5-c18c57b551e4.png)

And then, press C-c C-e to enter wgrep mode:

![image](https://user-images.githubusercontent.com/563872/143841737-2cde884a-937a-4034-9849-2da2da81ff46.png)

![image](https://user-images.githubusercontent.com/563872/143841781-4ac420da-971a-4224-97b6-6bf634b7388b.png)

And finally I can save all modified lines:

![image](https://user-images.githubusercontent.com/563872/143841901-84d27dce-08b0-4deb-ba41-f686ade01c04.png)

Vertico's [readme](https://github.com/minad/vertico) says: "Install Embark-Consult and Wgrep for export from consult-line to occur-mode buffers and from consult-grep to editable grep-mode buffers."

It seems to suggest that wgrep comes as an addon that one needs to install manually. Would doom-emacs please consider installing it by default when vertico is chosen in `init.el`?

**Comment by iyefrat** [comment]
The Vertico module already has wgrep integration, as explained in the module readme. The keybindings are the same, do they not work for you?

**Comment by HouzuoGuo** [comment]
Pressing C-c C-e did not bring up wgrep mode when I used vertico. Is there any other key combo I should try?

**Comment by iyefrat** [comment]
No, that's it. Can you post your `doom/info`? What happens when you press `C-c C-e`? Is there anything written in the echo area or messages buffer?

**Comment by HouzuoGuo** [comment]
I just ran `doom sync -p` a second time and this time C-c C-e worked.
