### ISSUE TITLE
invalid-function lsp! after enabling lsp support for cc

### ISSUE THREAD

**Issue by UltraBlackLinux** [hlissner/doom-emacs#5849]
### What did you expect to happen?

lsp should work like I expect it to work after enabling it for C/C++

(Why do I have to log in to view the pretty important discourse links. Just no.)

### What actually happened?

When opening a C++ file, this happens:
```
Debugger entered--Lisp error: (invalid-function lsp!)
  lsp!()
  funcall(lsp!)
  (condition-case e (funcall hook) ((debug error) (signal 'doom-hook-error (list hook e))))
  doom-run-hook(lsp!)
```
(This)[https://0bin.net/paste/VORGQ3R+#CkApb7-gEg33Du0FsCFYMBrPGHUUffXYxX8BNhM8orK) is my package config, just in case.

### Describe your attempts to resolve the issue

I tried [this](https://github.com/hlissner/doom-emacs/issues/3827) before realising that it's actually a somewhat different problem apparently

### Steps to reproduce

Open a C++ file while having `(cc +lsp)` in the :lang config

### System Information

https://0bin.net/paste/OWzn9ZK+#naBfxTZ0QKK3a3nLrHpugWqo0vc8uspFbdFkKgJ3CNU

**Comment by hlissner** [comment]
Enable `:tools lsp`.

**Comment by UltraBlackLinux** [comment]
> Enable `:tools lsp`.

Oh thank you, I completely missed that, sorry.
