### ISSUE TITLE
No icons in terminal with brew installed emacs in MacOS 12.0.1 Darwin 21.1.0 arm6

### ISSUE THREAD

**Issue by soulomoon** [hlissner/doom-emacs#5852]
### What did you expect to happen?

I should see icons in the dashboard when I open emacs

### What actually happened?

There is no icon showing in the dashboard when I open emacs 

### Steps to reproduce

1. `brew install emacs`
2.  install doom as in the installation guide
3.  open emacs in terminal

### System Information

https://pastebin.com/raw/QPBV7Udc

**Comment by hlissner** [comment]
That's because icons are not supported in the terminal, and there is no plan to change that (it's non-trivial to support, as too many packages depend on `all-the-icons` and offer no easy way to substitute them).
