### ISSUE TITLE
html-ls not working (web +lsp)

### ISSUE THREAD

**Issue by otavioschwanck** [hlissner/doom-emacs#5858]
### What did you expect to happen?

LSP works for html (html-ls)

### What actually happened?

```
LSP :: There are no language servers supporting current mode `web-mode' registered with `lsp-mode'.

This issue might be caused by:
1. The language you are trying to use does not have built-in support in `lsp-mode`. You must install the required support manually. Examples of this are `lsp-java` or `lsp-metals`.
2. The language server that you expect to run is not configured to run for major mode `web-mode`. You may check that by checking the `:major-modes' that are passed to `lsp-register-client`.
3. `lsp-mode` doesn't have any integration for the language behind `web-mode`. Refer to https://emacs-lsp.github.io/lsp-mode/page/languages and https://langserver.org/ .
4. You are over `tramp'. In this case follow https://emacs-lsp.github.io/lsp-mode/page/remote/.
5. You have disabled the `lsp-mode` clients for that file. (Check `lsp-enabled-clients` and `lsp-disabled-clients`).
```

### Describe your attempts to resolve the issue

M-x lsp-install-server html-ls

### Steps to reproduce

Just open an html.erb file

### System Information

https://pastebin.com/3j1vNWSR

**Comment by hlissner** [comment]
Try `doom env` then restart Emacs.

**Comment by otavioschwanck** [comment]
> Try `doom env` then restart Emacs. I suspect html-ls is being correctly installed, but is not in your `PATH`. `doom env` will regenerate the envvar file, along with the new value for `PATH`.

@hlissner regenerated doom env and same error occurs.

**Comment by hlissner** [comment]
Oh, it's because there is no `*.erb` entry in `lsp-language-id-configuration`. Add one:

```elisp
(add-to-list 'lsp-language-id-configuration '("\\.*\\.html\\.erb" . "html"))
```

As this is an [upstream](https://github.com/emacs-lsp/lsp-mode) issue, I will close this. Please report it there.
