### ISSUE TITLE
Weird dashboard bug

### ISSUE THREAD

**Issue by YoussefBouzekri** [hlissner/doom-emacs#5861]
### What did you expect to happen?

The dashboard to look like the normal doom dashboard

### What actually happened?

When I open emacs my dashboard looks like this
![image](https://user-images.githubusercontent.com/77839865/144596874-a1f8ec94-c939-4d47-9f70-323a4648295f.png)
I doesnt matter if I am using emacsclient or not

### Describe your attempts to resolve the issue

I tried reinstalling emacs, doom and rewritting my config, at first deleting everything and starting over works, but then randomly at after running doom sync or just restarting emacs, the dashboards looks like this

### Steps to reproduce

1. Open emacs

### System Information

https://pastebin.com/y0qYpuxE

**Comment by hlissner** [comment]
I can't reproduce this on any of my vanilla Doom test environments (running 27.1, 27.2, 28.0.60, or 29.0.50; on Ubuntu, MacOS, NixOS, or Arch). 

1. Check \*Messages\* for errors/warnings at startup. If you find an error [produde a backtrace for it](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#how-to-extract-a-backtrace-from-an-error).
2. Comment out everything in `~/.doom.d/config.el` then try to reproduce it.
3. Check the output of `doom doctor`.

**Comment by YoussefBouzekri** [comment]
The only thing that works out of the 3 you suggested is commenting / moving my config, that works but once I readd the config everything breaks again. if this only happened with my config I would have guessed there is something wrong with it but it seems that this happens with different configurations (distrotube, mine, mine with literate config etc..)

**Comment by YoussefBouzekri** [comment]
i just started removing my config bit by bit and it seems like this piece of code is causing the issue

```elisp
(define-globalized-minor-mode global-rainbow-mode rainbow-mode
  (lambda () (rainbow-mode 1)))
(global-rainbow-mode 1 )
```
can you explain to me, why this causes an issue ? I stole it from his config when I saw that he added it and it seemed useful

**Comment by hlissner** [comment]
Ah, it's because the dashboard (among other special buffers) do their own syntax highlighting, and `rainbow-mode` imposes its own on the buffers it's activated in, which interferes with Doom's dashboard in unpredictable ways. You're better off adding `rainbow-mode` to the hooks you want, rather than activating it everywhere. E.g.

```elisp
;; add to ~/.doom.d/config.el
(add-hook! '(text-mode-hook prog-mode-hook conf-mode-hook) #'rainbow-mode)
```

Many major modes are derived from text-mode, prog-mode, or conf-mode, so this cases a pretty wide net.
