### ISSUE TITLE
Cannot Compose / Forward / Reply email inside mu4e - Other functionalities works

### ISSUE THREAD

**Issue by MrMic** [hlissner/doom-emacs#5864]
### What did you expect to happen?

When I press "C" in mu4e:main dashboard, it should 
open the mu4e:compose window

### What actually happened?

When I press "C" in the mu4e:main dashboard, I got this error:
Error (mu4e-compose-pre-hook): Error running hook "+mu4e-set-from-address-h" because: (void-function mu4e-personal-addresses)

- The same issue appears when I try to reply or forward an email.

Any idea?
Rgds,

### Describe your attempts to resolve the issue

Nothing! I do not know what to do :/

### Steps to reproduce

Open mu4e Dashboard with: SPC-o-m
Then press "C"

### System Information

https://pastebin.com/bbGubULD

**Comment by iyefrat** [comment]
cc @tecosaur

**Comment by dschrempf** [comment]
For the reference, I can not reproduce this error.

One idea: The help text of `mu4e-personal-addresses` states

```
  "Get the list user's personal addresses, as passed to `mu init --my-address=...'.
 The address are either plain e-mail address or /regular
 expressions/. When NO_REGEXP is non-nil, do not include regexp
 address patterns (if any)."
```

Maybe you did not specify `--my-address`?

It could also be that your mu4e package is outdated, or loading is somehow
deferred.

In any case, maybe `+mu4e-set-from-address-h` should check for existence of
`mu4e-personal-addresses` instead of throwing an error.

**Comment by zhelezov** [comment]
@MrMic, do you see your personal addresses when you run `mu info` in a shell? If not, re-init the message database specifying `--my-address` for *every* one of your addresses as suggested above. Have you specified `user-mail-address` in your emacs config?

**Comment by MrMic** [comment]
Finally, I manage it to work.
The version with Ubuntu was1.2 for mu, and 
I removed it and took the one from snap: v1.6
Then I gave the path to me4u in my config.el.
Now: mu info works (Before, it was unknown)
and init it with the right directory of my Maildir, and 
gave it my email address, too.

Thanks, guys for taking time for my issue.
Rgds,

@zhelezov 
@dschrempf
