### ISSUE TITLE
Add option '-y' to Doom CLI install command

### ISSUE THREAD

**Issue by teeann** [hlissner/doom-emacs#5866]
### Describe your request

I'd like Doom CLI to add option `-y` to command `doom install`. This allows users to automatically answer `yes` to all prompt questions.

### Briefly explain its use-case

1. Run `doom install -y`
2. The following prompts are automatically answered with `yes`
```
Generate an envvar file? (see `doom help env` for details) (y or n) 
...
Download and install all-the-icon's fonts? (y or n) y
```

**Comment by sei40kr** [comment]
@teeann 
I haven't tested yet, but AFAIS `doom help`

```
doom -y install
```

should work.

**Comment by ruivieira** [comment]
I can confirm this doesn't work.

Running both `doom -y install` and `doom --yes install` gives me a prompt for
`Generate an envvar file? (see 'doom help env' for details) (y or n)`

Doom cloned from `develop` just now (f458f9776049fd7e9523318582feed682e7d575c)

`uname -a`:
```
Linux rui-iMac 5.11.0-41-generic #45~20.04.1-Ubuntu SMP Wed Nov 10 10:20:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
`emacs -nw`:
```
GNU Emacs 28.0.90
```

**Comment by hlissner** [comment]
I don't intend to add `-y` to `doom install`. Going forward, `doom install` will be more of a wizard. You shouldn't be using it in headless or automated workflows. In fact, you shouldn't even be running it more than once. `doom -y sync` will work, however, and there are a number of `--no-*` switches for that, so please use that instead.
