### ISSUE TITLE
Enabling workspaces in init.el causes emacsclient to not close frames properly

### ISSUE THREAD

**Issue by NovaViper** [hlissner/doom-emacs#5876]
### What did you expect to happen?

I expected emacsclient to completely close and exit out the frame whenever I tell the frame to quit via `Spc q f` or click the close button on the window. and then when I create another frame, it creates a new frame, leaving only one single frame instance open.

The interface should end up looking like this
![image](https://user-images.githubusercontent.com/7191115/145129729-ce02a45e-36b0-4aac-981f-660d493a5ca7.png)

### What actually happened?

It doesn't actually close the frame, it just closes out of the program and if I actually tell emacs to create a frame, it actually creates a new frame while the original frame reminds open in the background, unable to access that old frame. It essentially leaves the original frame session open instead of closing it and creates another.

Example of a newly open emacsclient session, notice how it gives me instructions to close the frame
![image](https://user-images.githubusercontent.com/7191115/145129729-ce02a45e-36b0-4aac-981f-660d493a5ca7.png)
`Screenshot 1: Fresh emacsclioent/only one frame frame behavior`

And this is what happens after I tell the first session to close and tell it to create another with the `workspaces` package enabled. Notice how it doesn't give me any instructions for closing the frame this time, but instead shows two frame instances, despite I told emacs client to end the first frame.
![image](https://user-images.githubusercontent.com/7191115/145130172-847e7215-1de3-4013-9631-38740e6863d9.png)
`Screenshot 2: Two or more frames existing`

While if I did the same thing but with `workspaces` package disabled, it results in the same behavior as the screenshot example shown for a newly opened emacsclient session.

### Describe your attempts to resolve the issue

What fixed the issue was disabling the `workspaces` plugin.

### Steps to reproduce

1. Start up emacs daemon client.
2. Tell emacs client to create a new frame
3. Emacs client should open a new frame, as shown in Screenshot 1
4. Tell emacs to close the frame with `Spc f q` or close the window
5. Tell emacs client to create a new frame again
6. Emacs client opens and shows as the Screenshot 2

### System Information

https://pastebin.com/EHb39PSb

**Comment by ohmyhub** [comment]
Hi there! The following bit of code added to your `config.el` should give you the workspace behavior you're looking for.

``` emacs-lisp
(after! persp-mode
  (setq persp-emacsclient-init-frame-behaviour-override "main"))
