### ISSUE TITLE
setting lsp-dart-line-length has no effect

### ISSUE THREAD

**Issue by laynor** [hlissner/doom-emacs#5877]
### What did you expect to happen?

In my `config.el` I have 
```
(setq lsp-dart-line-length 120)
```
When I select a region  and format it with `=` or I type `SPC SPC +format/buffer RET` I expect the buffer to be correctly formatted with the specified line length.

### What actually happened?

The buffer gets formatted as if line length was set to 80.

### Steps to reproduce

1. set `lsp-dart-line-length` to 120 in your config file
2. open emacs
3. open a flutter project
4. create a new file `foo.dart` in `lib/`
5. input 
``` 
import 'package:flutter/material.dart';

class Foo extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(alignment: Alignment.bottomCenter, child: const Text('foobar'));
  }
}
```
6. `SPC SPC +format/buffer RET`

Expected: 
The file should not be reformatted

Actual:
The file gets reformatted as follows:
```
class Foo extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
        alignment: Alignment.bottomCenter, child: const Text('foobar'));
  }
}
```

### System Information

https://pastebin.com/P2CNLugF

**Comment by laynor** [comment]
Upgrading `lsp-dart` to a newer version fixes the issue.

**Comment by hlissner** [comment]
This issue should now be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
