### ISSUE TITLE
Custom font height breaks mode line alignment

### ISSUE THREAD

**Issue by d4ncer** [hlissner/doom-emacs#590]
Hello! 

Quick disclaimer, I'm not using the entirety of `doom-emacs`, just your awesome modeline. It works great out-of-the-box (thank you for making it so accessible!), but I have an issue with a custom font size breaking right alignment of the `rhs` segments of the modeline.

### Observed behavior

Changing the `:height` of the `mode-line` face to be different from the standard breaks the alignment of the RHS segments of the modeline. I'm using a height of `190` for my regular text & `140` for my modeline.

<img width="846" alt="screen shot 2018-05-17 at 09 40 04" src="https://user-images.githubusercontent.com/1840377/40145660-e5860cec-59b6-11e8-8463-d0869a748aec.png">

### Expected behavior

Using a custom font scales the middle spacing up to ensure the RHS segments are properly aligned to the right side of the modeline.

### Steps to reproduce

1. Use a different height for the `mode-line` face.
2. Force update your modeline or restart Emacs.

### My investigation

I suspect the issue is somewhere here:

```elisp
(propertize
   " " 'display
   `((space :align-to (- (+ right right-fringe right-margin)
                         ,(+ 1 (string-width rhs-str))))))
```

My elisp-foo, sadly, is not strong enough to figure out what I should scale up to ensure the difference in font size is accommodated.

**Comment by hlissner** [comment]
Unfortunately, there is no clean solution to this. Emacs defines such spacing in integer units of the default character width/height. If you've changed the character size locally, it won't calculate the correct width. You'd have to calculate the ratio between the default font and your adjusted one, then use it to scale up the number of spaces; a non-trivial solution that would bog down mode-line rendering a fair bit.

It may be better to leave the mode-line to its default font-size, and scale down everything else?

**Comment by d4ncer** [comment]
Will give that a shot, thanks! 

I've currently simplified the sections down a bit, and I'm only using the `lhs` blocks for now, which works. Will try your suggestion and report back.

**Comment by hlissner** [comment]
I'm closing this issue in prep for the 2.1 release. Please feel free to continue using it if you'd like further assistance!
