### ISSUE TITLE
lsp-mode throws error void-function lsp--matching-clients?

### ISSUE THREAD

**Issue by vikigenius** [hlissner/doom-emacs#5904]
### What did you expect to happen?

lsp server should start correctly when opening a rust file.

### What actually happened?

Lsp server does not start, instead it throws the following error.

```
Error (rustic-mode-local-vars-hook): Error running hook "rustic-setup-lsp" because: (void-function lsp--matching-clients?)
Error (hack-local-variables-hook): Error running hook "doom-run-local-var-hooks-h" because: (doom-hook-error rustic-mode-local-vars-hook rustic-setup-lsp (void-function lsp--matching-clients?))
```

### Describe your attempts to resolve the issue

I tried removing the unpin lsp

```lisp
;; (unpin! lsp-mode)
;; (unpin! lsp-ui)
```

After removing the unpin it works, but I want to have the latest version of lsp all the time, so having a fix would be good.

### Steps to reproduce

1. Upgrade to latest develop
2. Unpin lsp-mode to use latest commit
3. Open any rust file.
4. lsp server fails to start and produces error message as described above.

### System Information

https://pastebin.com/L2qm2uae

**Comment by vikigenius** [comment]
The `lsp-mode` maintainers confirm that the `lsp--matching-clients?` has been renamed. And say that it is not supposed to be used externally.

**Comment by thaenalpha** [comment]
I know what the new function name is, but I don't know how to make a contribution to fixing this. My code base is on my fork feature branch which never makes a pull request.
Should I switch to the 'develop' branch to make a pull request on this, and then switch it back to my ongoing branch, leave unstaged changes on this until this was merged into upstream?

**Comment by michaelpj** [comment]
As of [recently](https://github.com/emacs-lsp/lsp-mode/pull/3230) there's a variable to control prompting for server installation, so we can just delete that entire `defadvice` and just set `lsp-enable-server-download`.

**Comment by michaelpj** [comment]
Probably it would also be better if we didn't have lots of things that use internal functions from `lsp-mode`.

**Comment by hlissner** [comment]
> After removing the unpin it works, but I want to have the latest version of lsp all the time, so having a fix would be good.

This isn't a Doom bug. Versions are pihned to avoid exactly these errors. I will close this since it isn't a bug.

In any case, I will bump the module (and remove the advice) soon.

**Comment by fredfortier** [comment]
> > After removing the unpin it works, but I want to have the latest version of lsp all the time, so having a fix would be good.
> 
> This isn't a Doom bug. Versions are pinned to avoid exactly these incompatibilities, and the possibility of these issues are the price you pay for unpinning packages from your private config. This will never change.
> 
> I will close this since it isn't a bug, but I will bump the module (and remove the advice) soon anyway. In the meantime, you can use this as a workaround:
> 
> ```emacs-lisp
> ;; add to $DOOMDIR/config.el
> (after! lsp-mode
>   (advice-remove #'lsp #'+lsp-dont-prompt-to-install-servers-maybe-a))
> ```

I noticed an error almost identical to this today after upgrading except that the void-function was `rust-before-save-method`. I just unpinned lsp-mode and lsp-ui for now as a workaround. Here's my config after the unpin: https://gist.github.com/fredfortier/47e1b46160a661ada725b99a403dbdff if it can help in any way.

**Comment by hlissner** [comment]
> I noticed an error almost identical to this today after upgrading except that the void-function was rust-before-save-method. I just unpinned lsp-mode and lsp-ui for now as a workaround. Here's my config after the unpin: https://gist.github.com/fredfortier/47e1b46160a661ada725b99a403dbdff if it can help in any way.

This is likely because you've unpinned rustic. I vaguely recall there were some breaking changes to it lately that I haven't looked into yet.

**Comment by DAlperin** [comment]
@hlissner quick heads up. cc +lsp on a fresh install is throwing an error complaining about `(void-function lsp--matching-clients?)`

```
> Executing 'doom info' with Emacs 28.0.90 at 2021-12-20 11:03:32
    generated    Dec 20, 2021 11:03:32
      system       NixOS 21.11.20211219.e6377ff (Porcupine) Linux 5.15.4 x86_64
      emacs        28.0.90 master emacs-28. ~/.emacs.d/ -> ~/.emacs.d/
      doom         21.12.0-alpha HEAD -> develop, origin/develop, origin/HEAD af7c1d79b 2021-12-18 01:13:37 +0100 ~/.doom.d/ -> ~/.doom.d/
      shell        /run/current-system/sw/bin/zsh
      features     CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GSETTINGS HARFBUZZ JPEG JSON LIBOTF LIBSELINUX LIBSYSTEMD LIBXML2 M17N_FLT MODULES NATIVE_COMP NOTIFY INOTIFY PDUMPER PNG RSVG SECCOMP SOUND THREADS TIFF TOOLKIT_SCROLL_BARS X11 XDBE XIM XPM GTK3 ZLIB
      traits       batch server-running envvar-file
      modules      :completion company vertico :ui doom doom-dashboard doom-quit hl-todo minimap modeline neotree ophints (popup +defaults) vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold snippets :emacs dired electric undo vc :checkers syntax :tools (eval +overlay) lookup lsp magit :lang (cc +lsp) emacs-lisp markdown org sh :config (default +bindings +smartparens)
```
Using your advice-remove workaround works fine though.

**Comment by gagbo** [comment]
> Probably it would also be better if we didn't have lots of things that use internal functions from `lsp-mode`.

The reason the internal function from `lsp-mode` was used is _exactly_ because there was no exposed way of disabling that prompt. It's not like that snippet was using `lsp--*` just for the sake of it :shrug:

**Comment by ericdallo** [comment]
It's possible to disable that on lsp-mode now, PR https://github.com/hlissner/doom-emacs/pull/5945
