### ISSUE TITLE
highlight-indent-guides customization

### ISSUE THREAD

**Issue by Sleepful** [hlissner/doom-emacs#5909]
### Describe your request

I want to turn on `highlight-indent-guides` *only* for **YAML** files. It seems not-possible to do so with the current default configuration that is turned on from `init.el` in:

https://github.com/hlissner/doom-emacs/blob/f989bf60f00a0da4fdb56e1768c464b52b4dddda/modules/ui/indent-guides/config.el

So for now I just copy-pasted this into my `config.el` with the slight modification
```elisp
(use-package! highlight-indent-guides
  :hook ((yaml-mode) . highlight-indent-guides-mode)
  :init
  (setq highlight-indent-guides-method 'character
        highlight-indent-guides-suppress-auto-error t)
  :config
  (defun +indent-guides-init-faces-h (&rest _)
    (when (display-graphic-p)
      (highlight-indent-guides-auto-set-faces)))

  ;; HACK `highlight-indent-guides' calculates its faces from the current theme,
  ;;      but is unable to do so properly in terminal Emacs, where it only has
  ;;      access to 256 colors. So if the user uses a daemon we must wait for
  ;;      the first graphical frame to be available to do.
  (add-hook 'doom-load-theme-hook #'+indent-guides-init-faces-h)
  (when doom-theme
    (+indent-guides-init-faces-h))

  ;; `highlight-indent-guides' breaks when `org-indent-mode' is active
  (add-hook! 'org-mode-local-vars-hook
    (defun +indent-guides-disable-maybe-h ()
      (and highlight-indent-guides-mode
           (bound-and-true-p org-indent-mode)
           (highlight-indent-guides-mode -1)))))

```

### Briefly explain its use-case

I want indent guides only for YAML because YAML is unreadable, sadly I don't have the option to avoid using yaml whatsoever 😢 
https://noyaml.com/

**Comment by Sleepful** [comment]
thanks meatball

**Comment by hlissner** [comment]
You can replace all of that with:

```elisp
;; add to $DOOMDIR/config.el
(remove-hook! '(prog-mode-hook text-mode-hook conf-mode-hook) #'highlight-indent-guides-mode)
(add-hook 'yaml-mode-hook #'highlight-indent-guides-mode)
```

In the future, please divert support requests to [our Discord](https://doomemacs.org/discord), as our issue tracker is not the place for them.

Hope that helps!

**Comment by Sleepful** [comment]
@hlissner I went to the discord at first but did not get an answer there so I figured this was a feature-request, thanks
