### ISSUE TITLE
Fails to update dired-git-info package when running doom upgrade

### ISSUE THREAD

**Issue by 5t111111** [hlissner/doom-emacs#5913]
### What did you expect to happen?

Running `doom update` finishes without an error related to updating dired-git-info package.

### What actually happened?

When running `doom update`, the following error occurs.

```
      > (72/208) Re-cloning dired-git-info...
        > Cloning dired-git-info...
          Warning (straight): Could not reset to commit "91d57e3a4c5104c66a3abc18e281ee55e8979176" in repository "dired-git-info"
      ✓ (72/208) dired-git-info: 9461476 -> 91d57e3 [1 commit(s)]
          ERROR: Couldn't collect commit list because: fatal: bad object 91d57e3a4c5104c66a3abc18e281ee55e8979176
```

### Describe your attempts to resolve the issue

Revert this commit -> https://github.com/hlissner/doom-emacs/pull/5903

The above pull request changes SHA value of the target commit hash, and the new commit hash does not seem to exist on ELPA mirror. That commit exists only on GitHub `master` branch. I think that causes an error.

### Steps to reproduce

Running `doom update` always causes that error.

### System Information

https://pastebin.com/jpanAH83

**Comment by annagrram** [comment]
There's an explanation and a solution for a similar problem here: https://github.com/hlissner/doom-emacs/issues/4984#issuecomment-832842879

**Comment by zhelezov** [comment]
The current remote for `dired-git-info` is https://github.com/emacs-straight/dired-git-info.git, but the requested commit id is in https://github.com/clemera/dired-git-info

**Comment by 5t111111** [comment]
@annagrram Thanks for the info, but I don't think that solve the problem because, as @zhelezov explains, the current commit hash looks point to different repository's branch.

**Comment by manueldeljesus** [comment]
I also hit the problem and came here to report it. Good to know that it was not me breaking something.

> There's an explanation and a solution for a similar problem here: [#4984 (comment)](https://github.com/hlissner/doom-emacs/issues/4984#issuecomment-832842879)

I tried this but the ```doom upgrade``` command continues to throw the error.

**Comment by annagrram** [comment]
My bad.

For me, it solved the issue in the sense that it let `doom upgrade` continue running properly.
When I checked the actual folder, it seems to indeed point to https://github.com/emacs-straight/dired-git-info.git and the branch is `master` rather than the pinned commit.

**Comment by manueldeljesus** [comment]
> My bad.

Not at all. It gave me something to try. :)

> For me, it solved the issue in the sense that it let `doom upgrade` continue running properly. When I checked the actual folder, it seems to indeed point to https://github.com/emacs-straight/dired-git-info.git and the branch is `master` rather than the pinned commit.

> The current remote for `dired-git-info` is https://github.com/emacs-straight/dired-git-info.git, but the requested commit id is in https://github.com/clemera/dired-git-info. A revert of [80bdd27](https://github.com/hlissner/doom-emacs/commit/80bdd2774f476232a54f2d30c3a1fa9c91e7e318) should fix this.

I just tried to follow the initial suggestion, removed the directory and cloned the clemera repo manually. Then rerun ```doom upgrade``` and it worked like a charm.

I imagine that you may already know this should work, but I am very new to Doom Emacs so just wanted to leave this written in case someone else found the problem and wanted a quick solution before a proper one is implemented.

**Comment by zhelezov** [comment]
Do a `git revert 80bdd2774` or `git checkout 80bdd2774~ -- modules/emacs/dired/packages.el` if this is bothering you.

**Comment by gcoladon** [comment]
> 



> Do a `git revert 80bdd2774` or `git checkout 80bdd2774~ -- modules/emacs/dired/packages.el` if this is bothering you.

When I try this, and then `doom upgrade`, I get 
```
!   Refusing to upgrade because "~/doom-emacs/" has been modified.
  
  Either stash/undo your changes or run ’doom upgrade -f’ to discard local changes.
  
   M  modules/emacs/dired/packages.el
```

How can do the revert or checkout and have `doom upgrade` be happy with it?

**Comment by kishvanchee** [comment]
@gcoladon I did the following and it helped avoid that error. I'm not sure if this is the best/right approach though.

`packages.el`
```
(package! dired-git-info
  :pin "9461476a28a5fec0784260f6e318237c662c3430")
```
`doom sync -u`
