### ISSUE TITLE
doom doctor Error: (wrong-type-argument stringp nil)

### ISSUE THREAD

**Issue by tonybrady** [hlissner/doom-emacs#5915]
### What did you expect to happen?

`doom doctor` should work

### What actually happened?

```
doom doctor
> Executing 'doom doctor' with Emacs 27.2 at 2021-12-19 11:44:45
  The doctor will see you now...
  
  > Checking your Emacs version...
  > Checking for Doom's prerequisites...
  > Checking for Emacs config conflicts...
  > Checking for great Emacs features...
  > Checking for private config conflicts...
  > Checking for stale elc files...
  ! ~/.emacs.d/.local/straight/build-27.2/straight/straight-ert-print-hack.elc is out-of-date
  ! ~/.emacs.d/.local/straight/build-27.2/straight/straight-x.elc is out-of-date
  ! ~/.emacs.d/.local/straight/build-27.2/straight/straight.elc is out-of-date
  > Checking for problematic git global settings...
  > Checking Doom Emacs...
    x There was an unexpected error
      Message: Wrong type argument
      Error: (wrong-type-argument stringp nil)
      Backtrace:
        (string-match "^.*/\\(.+\\)\\.git$" nil)
        (if (string-match regexp repo) (progn (match-string 1 repo)))
        (let ((regexp "^.*/\\(.+\\)\\.git$")) (if (string-match regexp repo) (prog...
        (if host (replace-regexp-in-string "^.+/" "" repo) (let ((regexp "^.*/\\(....
        (let* ((--cl-rest-- recipe) (repo (car (cdr (plist-member --cl-rest-- ':re...
        (straight-vc-git-local-repo-name (:files ("graphql" "code-review*.el") :pa...
        (apply straight-vc-git-local-repo-name (:files ("graphql" "code-review*.el...
        (let ((func (intern (format "straight-vc-%S-%S" type method)))) (if (fboun...
        (straight-vc local-repo-name git (:files ("graphql" "code-review*.el") :pa...
        (let* ((--cl-rest-- recipe) (type (car (cdr (plist-member --cl-rest-- ':ty...
    ! Extended backtrace logged to .local/doom.error.log
```

### Describe your attempts to resolve the issue

Seems to be related to the code-review package. I can fix by checking out doom before commit https://github.com/hlissner/doom-emacs/commit/2d3a68df496f300ac219db124f44ff1bde90e464

```
cd ~/.emacs.d
git checkout 6e0b2eafa652e431442cc43e2bdae5dc301f5db0
```
Then `doom doctor` completes without the error.

### Steps to reproduce

`doom doctor`

### System Information

https://pastebin.com/Zzzcay6A

**Comment by tonybrady** [comment]
OK sorry - please ignore. `doom upgrade` gave the same error, but after updating `emacs-mac` with homebrew, `doom upgrade` then worked and installed `code-review`

**Comment by GiulioCentorame** [comment]
I have the same issue on Fedora 35, without the homebrew fix obviously :(

**Comment by sean0x42** [comment]
I'm also experiencing this issue on Mac. Which version of emacs did you upgrade to @tonybrady?

**Comment by tonybrady** [comment]
It was `railwaycat/emacsmacport/emacs-mac: stable emacs-27.2-mac-8.3` but I wonder if getting doom to rebuild packages somehow would solve it.

**Comment by sean0x42** [comment]
I'm wondering the same. The only way I could resolve this for myself was by re-installing doom

**Comment by GiulioCentorame** [comment]
The quickest way without reinstalling Doom is probably just deleting the `.emacs.d/.local/straight` folder and then run a `doom sync`, so that it forces to rebuild all the modules
