### ISSUE TITLE
org-capture-kill indents next heading

### ISSUE THREAD

**Issue by rleppink** [hlissner/doom-emacs#5920]
### What did you expect to happen?

When aborting a capture to an org file, I expect the file to remain unchanged.

With the default Doom Emacs settings, capturing to the following `~/org/todo.org` with `org-capture` (`SPC X`):

```org
* Inbox
* Another heading
```

I expect this to remain unchanged when doing `org-capture-kill` (`C-c C-k`).

### What actually happened?

It modifies the file so that the second heading is now a child of the first heading:

```org
* Inbox
** Another heading
```

![org-capture-bug](https://user-images.githubusercontent.com/1665744/146777444-8be7b570-4358-4cbb-b0be-f384665903b0.gif)

### Describe your attempts to resolve the issue

Adding a child heading in the `~/org/todo.org::Inbox` heading works, but that's not ideal.

I looked at the source code for `org-capture-kill`, which has a `FIXME` -- but I don't have the elisp knowledge to make the fix.

### Steps to reproduce

1. Open Emacs
2. Make sure there's a heading below `todo.org::Inbox`
3. Capture to todo with `org-capture` (`SPC X`)
4. Abort the capture with `org-capture-kill` (`C-c C-k`)
5. The heading below the capture target is now a subheading of the capture target

### System Information

https://pastebin.com/Fat4nBvq

**Comment by ReneFroger** [comment]
Is this issue not more related to Org-mode instead of Doom Emacs?

**Comment by rleppink** [comment]
@ReneFroger very possible! I will have to test this in a configurationless Emacs.

**Comment by rleppink** [comment]
I can confirm this happens in stock Emacs too, not a Doom related bug. Sorry for any inconvenience. :)
