### ISSUE TITLE
Evil-surround doesn't replace xml/html tags in doom

### ISSUE THREAD

**Issue by elmehalawi** [hlissner/doom-emacs#5921]
### What did you expect to happen?

Given the following text:

```html
<div class="bg-red-400">A header</div>
```

And given that the cursor is inside that tag, I expected typing `cst<h1>` to result in:

```html
<h1>A header</h1>
```

### What actually happened?

When I type `cst<`, I get this text:

```html
<A header<
```

And now I'm in normal mode, so I can't continue typing `html>`

### Describe your attempts to resolve the issue

I started an issue on the evil-surround issue tracker. They suggested I comment out my config to see what the issue is. So I commented out my entire config.el to make sure it wasn't that. But the issue persists, so I thought it might be an issue with doom.

### Steps to reproduce

1. Open emacs
2. Go to an html file (or write some html like the one above)
3. Put the cursor inside an html element
4. Try to replace the tag to an h1 with: `cst<h1>`

### System Information

https://pastebin.com/BkqqNXQe

**Comment by ymarco** [comment]
Maybe try `cstth1>`?
Both `cst<h1>` and `cstth1>` work for me though.

**Comment by elmehalawi** [comment]
@ymarco That actually works. That's very strange, I wonder why `cst<` doesn't work.

Really helpful workaround I was not aware of, thank you.

**Comment by RBckmnn** [comment]
Initially I got confused by this as well. My reasoning is that `cst<` means "replace the surrounding tags with '<'s" whereas `cstth1>` means "replace the surrounding tag with the `<h1>` tag".
