### ISSUE TITLE
eslint 8.x doesn't work

### ISSUE THREAD

**Issue by aburtsev** [hlissner/doom-emacs#5927]
### What did you expect to happen?

lsp-mode supports eslint 8.x

### What actually happened?

After updating eslint to 8.5 the lsp stops showing hints from eslint.

### Describe your attempts to resolve the issue

After investigation, it's appeared that problem is in that version 8.x of eslint introduced some breaking changes.

This issue is already [solved in lsp-mode](https://github.com/emacs-lsp/lsp-mode/issues/3272).

I tried to manually change the version in `.local/straight/repos/lsp-mode/clients/lsp-eslint.el` and everything started to work.

![image](https://user-images.githubusercontent.com/3891411/147228980-58d61fbf-852b-4382-a05c-ea21f6bd155b.png)

### Steps to reproduce

Upgrade eslint to 8.x in any project

### System Information

https://pastebin.com/EricrU8r

**Comment by hlissner** [comment]
This issue should now be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
