### ISSUE TITLE
Cannot remap tab key to indent-for-tab-command

### ISSUE THREAD

**Issue by akotulski** [hlissner/doom-emacs#5932]
### What did you expect to happen?

When I hit tab I expect that I'll get `indent-for-tab-command`.

Those are the changes to the generated `config.el`
```
(after! lsp-mode
  (setq lsp-pylsp-plugins-pydocstyle-enabled nil))

(map!
 :n "TAB" #'indent-for-tab-command)
```

I verified that it is bound to tab according to the `describe-function`:
```
indent-for-tab-command is an interactive compiled Lisp function in ‘indent.el’.
It is bound to TAB.
(indent-for-tab-command &optional ARG)
```

### What actually happened?

`evil-jump-item` is triggered instead. 

### Describe your attempts to resolve the issue

Tried to register and search the discourse, didn't get an email for 30+ minutes

Tried the following as well:
```
(map!
 :n "TAB" #'indent-for-tab-command
 :m "TAB" #'indent-for-tab-command
 :n "[tab]" #'indent-for-tab-command)
```

### Steps to reproduce

`describe-key <ret> tab` shows the following:
```
<tab> runs the command evil-jump-item (found in evil-motion-state-map), which is
an interactive compiled Lisp function in ‘evil-commands.el’.
It is bound to %.

(evil-jump-item &optional COUNT)
Find the next item in this line after or under the cursor
and jump to the corresponding one.
```

Normal repro:
1. Open `config.el` file
2. Put cursor on open paren `(` in normal mode
3. Hit tab
4. cursor moves to close paren `)`

### System Information

https://pastebin.com/4HzHPbiL

**Comment by hlissner** [comment]
```lisp
(map! :m [tab] #'indent-for-tab-command)
```

To override [this](https://github.com/hlissner/doom-emacs/blob/develop/modules/config/default/+evil-bindings.el#L47-L69).
