### ISSUE TITLE
Popup buffers flicker on open

### ISSUE THREAD

**Issue by ethan-leba** [hlissner/doom-emacs#5934]
### What did you expect to happen?

When I open a pop up buffer, it should open without any flickering.

### What actually happened?

When I open a pop up buffer, the buffer seems to open as a normal split buffer before quickly resizing into the popup buffer, causing a flicker.

https://user-images.githubusercontent.com/4625599/147361597-115a660a-396c-4018-b2fe-e9e8a0bc069e.mov

### Describe your attempts to resolve the issue

Tried using the doom sandbox but the error persisted there.

### Steps to reproduce

1. Open any pop up buffer (i.e. `SPC x`)
2. See the flicker

### System Information

https://pastebin.com/1cfyPjTE

**Comment by PyB1l** [comment]
This also happens to me for me I can verify this issue too!

**Comment by SreenivasVRao** [comment]
Confirming same issue - http://giant.gfycat.com/BlackOptimalBlackfootedferret.mp4 - I'm only stepping through the debugger and I see this happen.

**Comment by hlissner** [comment]
I can't reproduce this. It seems like a performance issue. Blank windows usually start with the fallback buffer (in our case, the dashboard) before switching to the actual buffer to display, but this should happen instantaneously. I'm inclined to suspect personal configuration to be an issue.

I'll leave this open until I find another lead.

**Comment by hlissner** [comment]
Ah, try commenting out [these lines](https://github.com/hlissner/doom-emacs/blob/develop/early-init.el#L46-L52) and see if your issue goes away.

**Comment by PyB1l** [comment]
@hlissner Just tried it but it does not seem to work. Every time I open a new buffer / window / pop it seems to first create a horizontal duplicate of the and then renders the correct buffer / window / popup

**Comment by ethan-leba** [comment]
> I'm inclined to suspect personal configuration to be an issue.

I've tested this in the doom sandbox, that should eliminate the issue of personal config correct?

That said I've `doom/upgrade`'d and now I'm not seeing the pop-up issue anymore
with or without the code block commented. Could it be a dependency related issue?

**Comment by PyB1l** [comment]
I can also verify that after a `doom upgrade` issue seems to be resolved as well
