### ISSUE TITLE
elixir-yasnippets load error

### ISSUE THREAD

**Issue by heiheshang** [hlissner/doom-emacs#5937]
### What did you expect to happen?

`Warning (initialization): An error occurred while loading ‘/home/oper/.emacs’:

File is missing: Cannot open load file, Нет такого файла или каталога, elixir-yasnippets
`
can't start emacs

distro OpenSuSe Tumbleweed

### What actually happened?

![image](https://user-images.githubusercontent.com/111087/147409456-7ff4d8da-22aa-460f-b2c8-a8e4928c4e2c.png)

### Steps to reproduce

> Executing 'doom info' with Emacs 27.2 at 2021-12-26 22:21:55
    generated    дек 26, 2021 22:21:55
      system       "openSUSE Tumbleweed" Linux 5.15.8-1-default x86_64
      emacs        27.2 ~/.emacs.d/doom/ -> ~/.emacs.d/doom/
      doom         21.12.0-alpha HEAD -> develop, origin/develop, origin/HEAD af7c1d79b 2021-12-18 01:13:37 +0100 ~/.doom.d/ -> ~/.doom.d/
      shell        /bin/bash
      features     XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER LCMS2 GMP
      traits       batch server-running envvar-file
      modules      :completion company vertico :ui doom doom-dashboard doom-quit hl-todo modeline ophints (popup +defaults) vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold snippets :emacs dired electric undo vc :checkers syntax :tools (eval +overlay) lookup magit :lang emacs-lisp markdown org sh :config (default +bindings +smartparens)

### System Information

https://pastebin.com/xU42Lu6i

**Comment by heiheshang** [comment]
solved

**Comment by heiheshang** [comment]
![image](https://user-images.githubusercontent.com/111087/147425886-473bb3f6-f576-4f6c-9377-439b41b90c05.png)

**Comment by hlissner** [comment]
What does your `package!` statement look like for elixir-yasnippet`?

You also did not provide steps to reproduce the issue.
