### ISSUE TITLE
Weird visual glitches appear while switching workspaces with treemacs opened

### ISSUE THREAD

**Issue by hyperfocus1337** [hlissner/doom-emacs#5941]
### What did you expect to happen?

An update to Doom Emacs has triggered unexpected visual glitches. This should not happen.

### What actually happened?

Since a few weeks ago some weird visual glitches started to appear while switching workspaces with treemacs opened.

Video showcasing the problem: https://imgur.com/a/xiZq8Yh

I am switching between workspace 1 and 2 using `[w` and `]w` (equivalent of `SPC tab [` / `SPC tab ]`), which triggers intermittent visual glitches in random places within Emacs.

### Describe your attempts to resolve the issue

Have not yet tried something to resolve the issue.

### Steps to reproduce

The problem happens on the latest `origin/develop`.

I did not yet pinpoint the exact commit where the issue started to appear.

The problem appears between `23f6f9051` and `2132d6006`, from what I've tested so far.

A git checkout to commit `2132d6006` of `develop` resolves the issue (commit that was made ~2 weeks ago).

1. Go to installation directory: `cd ~/.emacs.d`

2. Git reset: `git checkout 2132d6006`

3. Remove packages: `rm -r ~/.emacs.d/.local/straight`

4. Resync doom packages: `doom sync`

5. Open Emacs and glitches have disappeared.

### System Information

https://pastebin.com/gx8gehPu

**Comment by ethan-leba** [comment]
Related: #5934

**Comment by hlissner** [comment]
Try commenting out these lines and see if your issue goes away.

**Comment by hyperfocus1337** [comment]
Thanks Henrik. These are the steps I took:

1. I commented out those lines you linked
2. Checked out newer commit `git checkout af7c1d79b` in  `~/.emacs.d`
3. Removed packages again: `rm -r ~/.emacs.d/.local/straight`
4. Synced `doom sync`
5. Issue is still present in later commits

Will try pinpointing the issue once I find some more time.

**Comment by hyperfocus1337** [comment]
The glitches have automagically resolved themselves after uncommenting your suggested lines and running a `doom upgrade`. However, sometimes it does randomly come back, but will re-open the issue by then.

Thanks for the assistance!
