### ISSUE TITLE
Setting `doom-font` to a font that can't be found should fall back to a default font instead of crashing

### ISSUE THREAD

**Issue by dradetsky** [hlissner/doom-emacs#5948]
### Describe your request

Something I do fairly often is to configure a new computer by running a bunch of ansible playbooks that install all the configurations and programs I want. Since these playbooks are in a perpetual state of needing-to-be-worked-on, they don't always produce identical results.

One thing I always want for my emacs setup is to install some good bitmap fonts and to configure emacs to use them. So I have in my `user-doomdir/config.el`

```
(setq doom-font "Gohu GohuFont:pixelsize=14")
```

However, if this font can't be found for whatever reason (because I haven't actually installed it, because something went wrong with setting up `yay` since it's a AUR pkg on arch linux, etc), what I would like to have happen is for doom to continue loading as normal with the default font (and ideally print a warning message), since when I start an editor in my partially-installed system, it's usually to fix some config file or other, so I want doom to start as normally as possible. Instead, doom stops at the point where it tried to set the font, so like 20% of doom is loaded and I'm not totally sure how to go about editing things.

Additionally, in the past when I have upgraded either doom or other system packages, this has affected emacs' ability to locate the font I chose, which broke startup in a similar way. Again, this is particularly unfortunate since my attempts to fix the issue will normally involve using emacs, and now it doesn't really work the way I'm used to.

Fun fact: The above is the case as of

```
% git rev-parse HEAD
af7c1d79bd63d78410aafc410d52ee5c1109ec26
```

I'm a pretty awful emacs lisp programmer, but I think what we want to do is something along the lines of the following patch

```
diff --git a/core/core-ui.el b/core/core-ui.el
index 8e7e6c1cc..26106f1d0 100644
--- a/core/core-ui.el
+++ b/core/core-ui.el
@@ -526,6 +526,16 @@ windows, switch to `doom-fallback-buffer'. Otherwise, delegate to original
       (cons 'custom-theme-directory
             (delq 'custom-theme-directory custom-theme-load-path)))
 
+(defun usable-font-p (font)
+  (and font (can-lookup-font-p font)))
+
+(defun can-lookup-font-p (font)
+  (let ((font-obj
+         (cond ((stringp font) (font-spec :name font))
+               ((fontp font) font)
+               (t (signal 'error)))))
+    (find-font font-obj)))
+
 (defun doom-init-fonts-h (&optional reload)
   "Loads `doom-font'."
   (when (fboundp 'set-fontset-font)
@@ -538,7 +548,7 @@ windows, switch to `doom-fallback-buffer'. Otherwise, delegate to original
         (set-fontset-font t 'unicode doom-unicode-font))))
   (apply #'custom-set-faces
          (let ((attrs '(:weight unspecified :slant unspecified :width unspecified)))
-           (append (when doom-font
+           (append (when (usable-font-p doom-font)
                      `((fixed-pitch ((t (:font ,doom-font ,@attrs))))))
                    (when doom-serif-font
                      `((fixed-pitch-serif ((t (:font ,doom-serif-font ,@attrs))))))
```

Although we'd obviously call that predicate a few more times. This appears to have the correct result with my normal config seen above, as well as with

```
(setq doom-font "fuckyoubreak")
```

(where it falls back to the default font), although it does not work correctly with

```
(setq doom-font 37)
```

where I expect it to throw an error, but it doesn't actually throw the error I want (I told you I was a terrible elisp programmer). Hopefully this will be helpful to someone who is actually decent at elisp.

This is sort of related to #5686 and probably lots of other issues. I note that @hlissner closed that partly due to the fact that

> An unavailable font is either a configuration issue (the specified font name or weight is incorrect) or a system issue (the specified font isn't installed/available).

which isn't wrong, but is IMO incomplete. Part of what the user complained of was that the unavailable font _breaks setup_ which is in my view undesirable. I would say "unacceptable", but that sounds too harsh/critical, which isn't my intention here. It's more like: "We shouldn't accept a crash just because we can't find the specified font, since we have a good alternative; we can test if we can find the font & if we can't fall back to the working default"

### Briefly explain its use-case

Uhh, hopefully the use case is clear from the above.

**Comment by dradetsky** [comment]
I didn't think of this earlier, but of course I now realize I can just put those helpers in my `config.el` and then just do something like

```
;; (setq doom-font-arg "Gohu GohuFont:pixelsize=14")
(setq doom-font-arg "fuckyoubreak")
;; (setq doom-font-arg 37)

(when (usable-font-p doom-font-arg)
  (setq doom-font doom-font-arg))
```

which seems a little ugly (what with adding those defuns at the top) but works just as well *for me*. However, I wonder if this still isn't something the doom project should try to solve for everyone at once.

**Comment by hlissner** [comment]
I understand the confusion, but I don't intend to change this because throwing an error is the least surprising (and least ambiguous) outcome, is the most performant, and is trivially suppressed by the user, as you have. In dde20aa I added a `doom-font-exists-p` function to make this a little easier, so I'd suggest:

+ ```elisp
  (setq doom-font "thiswillbreak")
  (unless (doom-font-exists-p doom-font)
    (setq doom-font nil))
  ```

+ Or use this technique to have fallback fonts:

  ```elisp
  (setq doom-font
        (cl-find-if #'doom-font-exists-p
                    '("GohuGohu:pixelsize=12"
                      "JetBrainsMono:pixelsize=12"
                      "Noto Serif:pixelsize=13")))
  ```

+ Another common idiom is for users to set different fonts on a per-host basis:

  ```elisp
  (setq doom-font
        (pcase (system-name)
          ("system1" "JetBrainsMono:pixelsize=12")
          ("system2" "IBM Plex Mono:pixelsize=14"))
  ```

> (setq doom-font 37)

To quote `doom-font`'s docs:

```
Must be a font-spec, a font object, an XFT font string, or an XLFD string.
```

So `37` isn't a valid value. If you want to set the size of the system font, one of these should work:

```elisp
(setq doom-font (font-spec :size 37))
;; or
(setq doom-font (font-spec :family "monospace" :size 37)) ; only recognized on systems with
                                                          ; a sane fontconfig config. This 
                                                          ; likely won't work on Windows.
```

-----

Anyhow, I hope that helps. Thanks for bringing it to my attention and for the detailed request! It was very easy to understand.

**Comment by dradetsky** [comment]
> > (setq doom-font 37)
> 
> To quote `doom-font`'s docs:
> 
> ```
> Must be a font-spec, a font object, an XFT font string, or an XLFD string.
> ```
> 
> So `37` isn't a valid value. If you want to set the size of the system font, one of these should work:

That was supposed to represent an egregiously bad example of misconfiguration, not an attempt to set the font size. In other words, actually attempting to set the system font to `37` should crash, but I was suggesting we should fall back to the default.

In any case, your `cl-find-if` solution & your helper handles both `"fuck you"` and `37` the way I want, so I'm happy.

However, the one problem which I would urge @hlissner to consider is that lots of users won't know all of these bits of elisp to be able to come up with the solution themselves. I mean, the better an emacs config works for me, the more I forget any elisp I've learned over time & my knowledge just regresses to doing a bunch of `setq`'s. So maybe it would be worth sticking this snippet in the config FAQ or common issues or something. Or not; I can see how if you included every little thing it might be too much.

Whatever, I guess it's your project, and you have to decide how to balance the risks of messy documentation vs. redundant issues. Thanks for your help.
