### ISSUE TITLE
evil moving lines doesn't always preserve column

### ISSUE THREAD

**Issue by ngharrison** [hlissner/doom-emacs#5959]
### What did you expect to happen?

When moving the cursor up and down lines, the same column should be maintained.

### What actually happened?

Sometimes the cursor jumps a few characters side to side.

### Describe your attempts to resolve the issue

I've narrowed it down to the behavior coming directly from `vertical-motion`, which is used by `line-move` inside the simple.el package. All the evil line commands use these functions. Since `vertical-motion` is a C function, I haven't gotten any farther.

### Steps to reproduce

- Start Emacs with modules
- Open buffer with text
- Use `evil-previous-line`, `evil-next-line`, `evil-previous-visual-line`, or `evil-next-visual-line`.

It doesn't always happen. It depends on the text but I don't know the pattern yet. It happens more with the visual line movements, but often when lines aren't even visually wrapped. It might happen more when there is whitespace at the beginning of the line.

The biggest problem I have is that when using the visual line commands the cursor shifts to a column 4 characters to the right when moving up and then back to the original column when moving down. This is very consistent, occurs when moving across logical lines, and occurs even when I switch to fundamental mode.

NOTE: I do not see this behavior when using Doom core without any modules (`doom--run-vanilla-doom`), but I do see it with modules loaded but without my private config (`doom--run-vanilla-doom+`).

### System Information

https://pastebin.com/0RqbYnen

**Comment by kauesena** [comment]
I am experiencing what may be the same bug. It happens like this: the first time I make an evil motion, say `k`, the cursor moves up preserving the column. If I press 'k' again, the cursor goes up one line but also moves to the first character. Did you make any progress?

**Comment by ngharrison** [comment]
No progress on my end. It was too deep and inconsistent.
