### ISSUE TITLE
Getting "<window x on xxxxx> is not a live frame" errors

### ISSUE THREAD

**Issue by syvanpera** [hlissner/doom-emacs#596]
Unfortunately unable to give simple steps to reproduce, but happens all the time. Just by opening some file, opening a new frame and using C-x C-f to open files. Can't give the exact steps, but some combination of those.
After a while pretty much anything (at least C-x C-f and ivy and flycheck) start giving the errors in the subject line. So probably has something to do with the childframes (Emacs 26.x in use)

And this started happening after pulling the latest changes from develop this morning.

**Comment by hlissner** [comment]
Could you try:

```elisp
(after! whitespace
  (advice-remove #'company-box--make-frame #'doom*fix-whitespace-mode-in-childframes)
  (advice-remove #'posframe--create-posframe #'doom*fix-whitespace-mode-in-childframes))
```

And see if the problem goes away?

**Comment by syvanpera** [comment]
@hlissner tried your suggestion. So far so good, no errors yet. I'll keep using it today and will report if something comes up

**Comment by biox** [comment]
Running into the same problem on MacOS w/ emacs 26.1-rc1. Let me know if it would be helpful to provide debug information - the workaround suggested above by @hlissner works great.

**Comment by digizeph** [comment]
The [workaround](https://github.com/hlissner/doom-emacs/issues/596#issuecomment-390132481) works perfectly.

**Comment by hlissner** [comment]
The fix is now live on `develop`. I'll leave this open until it has been merged into `master`.

Thanks for the help!

**Comment by tvhung83** [comment]
I'm using `develop` branch but having a very annoying issue (not sure related to this, as I'm a newbie to emacs):
- macOS 10.13.5
- emacs-plus 26.1
- ivy + pos-frame (default configs)
- `.doom.d/config.el`:
```el
(when (string= system-type "darwin")
  (setq dired-use-ls-dired nil))

(setq doom-font (font-spec :family "Roboto Mono for Powerline" :size 14)
      doom-variable-pitch-font (font-spec :family "Fira Sans")
      doom-unicode-font (font-spec :family "Roboto Mono for Powerline")
      doom-big-font (font-spec :family "Roboto Mono for Powerline" :size 19)
      ns-use-native-fullscreen t)

(after! whitespace
  (advice-remove #'company-box--make-frame #'doom*fix-whitespace-mode-in-childframes)
  (advice-remove #'posframe--create-posframe #'doom*fix-whitespace-mode-in-childframes))

(toggle-frame-fullscreen)
```
- I got black screen and it won't turn back on every time I press `ESC`

**Comment by hlissner** [comment]
@tvhung83 This is a known issue with Emacs childframes and MacOS when running Emacs in fullscreen mode. MacOS doesn't know that the popup frames aren't separate apps, and fullscreens them.

Unfortunately there is no known fix, for the time being. Your best bet is either a) don't use macos fullscreen (just maximize Emacs) or b) disable the `+posframe` module flag (actually, on the latest Doom, it's `+childframe`).
