### ISSUE TITLE
Fails to yank Chinese text to doom from other applications in windows11

### ISSUE THREAD

**Issue by AbstProcDo** [hlissner/doom-emacs#5961]
### What did you expect to happen?

M-y(yank) the text in Chinese from Chrome Browser to doom.emacs.
(emacs  27.2 doom 21.12.0-alpha)

### What actually happened?

If the copied text in Chrome is English, M-y works as expected, 
but if the text is Chinese, M-y yank fails to yank it to emacs, and repeat to yank the last English text.

### Describe your attempts to resolve the issue

Test it in sandbox.

C-c C-c, vanilla Emacs works as expected, 
C-c C-d, vanilla Doom fails to yank text in Chinese to Emacs from other Application.

### Steps to reproduce

Open "vanilla Doom" , try to  copy the two Chinese words "中文” and paste it to  Emacs.

### System Information

https://pastebin.com/gSFHhmiD

**Comment by sxjune** [comment]
Maybe?

`(if IS-WINDOWS
    (set-selection-coding-system 'utf-16le-dos)
  (set-selection-coding-system 'utf-8))
`

**Comment by hlissner** [comment]
I can't reproduce this in my windows 10 WM, so I suspect this may be a windows 11 issue. As I don't have access to Windows 11 I cannot look into this.

> (if IS-WINDOWS
>    (set-selection-coding-system 'utf-16le-dos)
>  (set-selection-coding-system 'utf-8))

These are Emacs' defaults already and Doom doesn't change them. To quote `selection-coding-system`'s docs:

```
For MS-Windows and MS-DOS:
When sending or receiving text via selection and clipboard, the text
is encoded or decoded by this coding system.  The default value is
the current system default encoding on 9x/Me, utf-16le-dos
(Unicode) on NT/W2K/XP, and iso-latin-1-dos on MS-DOS.
```

Of course, it's possible Emacs does not detect (or respond to) Windows 11 correctly.

**Comment by AbstProcDo** [comment]
> Maybe?
> 
> ```
> (if IS-WINDOWS
>     (set-selection-coding-system 'utf-16le-dos)
>   (set-selection-coding-system 'utf-8))
> ```

Thank you, it perfectly solved the problem.

**Comment by AbstProcDo** [comment]
> I can't reproduce this in my windows 10 WM, so I suspect this may be a windows 11 issue. As I don't have access to Windows 11 I cannot look into this.
> 
> > ```
> > (if IS-WINDOWS
> >    (set-selection-coding-system 'utf-16le-dos)
> >  (set-selection-coding-system 'utf-8))
> > ```
> 
> These are Emacs' defaults already and Doom doesn't change them. To quote `selection-coding-system`'s docs:
> 
> ```
> For MS-Windows and MS-DOS:
> When sending or receiving text via selection and clipboard, the text
> is encoded or decoded by this coding system.  The default value is
> the current system default encoding on 9x/Me, utf-16le-dos
> (Unicode) on NT/W2K/XP, and iso-latin-1-dos on MS-DOS.
> ```
> 
> Of course, it's possible Emacs does not detect (or respond to) Windows 11 correctly.

Thank you very much for the kind help.
