### ISSUE TITLE
Not able to use `package!` for package `zh-align`

### ISSUE THREAD

**Issue by BuddhiLW** [hlissner/doom-emacs#5963]
### What did you expect to happen?

with the command 
```el
(package! zh-align :recipe
  (:host github
   :repo "chen-chao/zh-align.el"))
```

placed in `$DOOMDIR/packages.el`, I expected to get the package installed in my system.

**Package at hand:** https://github.com/chen-chao/zh-align.el

### What actually happened?

After putting in place the code mentioned above, in the packages file, I got the following from `doom sync`, I got

```el
      > Cloning zh-align.el.git (for zh-align)......
      x There was an unexpected error
        Message: error
        Error: (error "Malformed protocol detected: (:host github :repo \"https://github.com/chen-chao/zh-align.el.git\")")
        Backtrace:
          (signal error ("Malformed protocol detected: (:host github :repo \"https:/...
          (error "Malformed protocol detected: (:host %S :repo %S)" github "https://...
          (progn (error "Malformed protocol detected: (:host %S :repo %S)" host repo...
          (if (string-match-p ":" repo) (progn (error "Malformed protocol detected: ...
          (cond ((null host) repo) ((memq host '(bitbucket gitlab github)) (if (stri...
          (straight-vc-git--encode-url "https://github.com/chen-chao/zh-align.el.git...
          (let ((success nil) (repo-dir (straight--repos-dir local-repo)) (url (stra...
          (let ((package (plist-get --recipe-- ':package)) (local-repo (plist-get --...
          (let ((--recipe-- recipe)) (let* ((--cl-rest-- --recipe--) (upstream (car ...
          (straight-vc-git-clone (:host github :repo "https://github.com/chen-chao/z...
      ! Extended backtrace logged to ~/.edoom/.local/doom.error.log
```

### Describe your attempts to resolve the issue

I have tried all forms of `:repo url` assignment possible. That is, with the url from the page, **https://github.com/chen-chao/zh-align.el**, with the git code url, **https://github.com/chen-chao/zh-align.el.git**, finally, with the `user-name/repo-name`, **chen-chao/zh-align.el**.

I got the same error, everytime.

### Steps to reproduce

1. Put any of the three snippets on your `$DOOMDIR/packages.el`,

```el
(package! zh-align :recipe
  (:host github
   :repo "https://github.com/chen-chao/zh-align.el.git"))
```

```el
(package! zh-align :recipe
  (:host github
   :repo "https://github.com/chen-chao/zh-align.el"))
```

```el
(package! zh-align :recipe
  (:host github
   :repo "chen-chao/zh-align.el"))
```

2. Hit `doom sync` in the terminal.

3. See an error.

### System Information

https://pastebin.com/3R6wWtyX

**Comment by hlissner** [comment]
I can't reproduce this. Check your gitconfig. Perhaps you have something like this in it:

```sh
[url "ssh://git@github.com/"]
	insteadOf = https://github.com/
```

**Comment by BuddhiLW** [comment]
Oh, sorry, here is the `doom/info`,
https://pastebin.com/XkbEUidu

My system install has less than 1 month, so it's pretty fresh. I don't have much incidental-configs etc.

This is my `.gitconfig`.

```conf
[user]
	name = BuddhiLW
	email = pedrogbranquinho@gmail.com
[credential]
	helper = cache
```

**Comment by hlissner** [comment]
I don't see any issues with your config, but again, I am unable to reproduce this on any of my test environments, so I cannot look into this further. I'm inclined to suspect this is a local issue.

Please try my `package!` declaration:

```elisp
(package! zh-align
  :recipe (:host github
           :repo "chen-chao/zh-align.el"))
```

And post the contents of `~/.emacs.d/.local/doom.error.log` **on pastebin** afterwards (assuming it fails).

**Comment by BuddhiLW** [comment]
It worked with your snippet. Thanks!
