### ISSUE TITLE
Projectile list of files not updated

### ISSUE THREAD

**Issue by asmodeus812** [hlissner/doom-emacs#5964]
### What did you expect to happen?

When i use SPC-c-r to rename a symbol in java using jdtls the class correctly gets renamed, the file name also gets changed but when i press SPC SPC after that to see the file the view still sees the old file instead of the upated one. I renamed the class not from within the class but from one of the many places where it was used. 

### What actually happened?

No errors are observed, the file simply is missing. I am using helm with projectile. When i try to open the old file as seen in SPC SPC the buffer is empty which is fine. But the new file is nowhere to be found.

### Describe your attempts to resolve the issue

I tried adding the file to git i.e staging it but no change was observed.

### Steps to reproduce

1. Open emacs 
2. Locate a java project
3. Find a class to rename
4. Press spc-c-r select a new name
5. press spc spc
6. search for the new name

### System Information

https://pastebin.com/VT4b1gPT

**Comment by hlissner** [comment]
Projectile caches that file list. To refresh the cache use `SPC p i` or `M-x projectile-invalidate-cache`.

**Comment by asmodeus812** [comment]
Hi Thanks for the feedback. Is there a way to do that automatically instead. I assume this will also happen if i start creating files from doom as well.
