### ISSUE TITLE
php-boris is abandoned. Psysh.el recommended.

### ISSUE THREAD

**Issue by SaxJ** [hlissner/doom-emacs#5965]
### Describe your request

The PHP Repl uses [php-boris](https://github.com/tomterl/php-boris) package.
As you can see, this package is long abandoned. 

I propose replacing php-boris with the suggested replacement, [psysh.el](https://github.com/emacs-php/psysh.el)

I'm happy to work on this if it would be useful.

Thanks Doom folks!

### Briefly explain its use-case

1. Open a PHP buffer
2. Open the PHP REPL (SPC o R)
3. Psysh is launched (given the PHP project has psysh package)

**Comment by hlissner** [comment]
Sounds good to me. I'd welcome a PR to replace php-boris.
