### ISSUE TITLE
(wrong-type-argument sequencep 0) after opening dired

### ISSUE THREAD

**Issue by usdogu** [hlissner/doom-emacs#5969]
### What did you expect to happen?

Being able to use dired

### What actually happened?

When I launch dired and open a directory it gives (wrong-type-argument sequencep 0) but successfully opens the directory too.
Screenshot: https://i.imgur.com/Bjfpggs.png
Backtrace:
```
 Message: Wrong type argument
        Error: (wrong-type-argument sequencep 0)
        Backtrace:
          (append 0 0)
          (projectile-merge-known-projects)
          (projectile--cleanup-known-projects)
          (projectile-mode 1)
          (progn (projectile-mode 1) (let ((sym 'projectile-relevant-known-projects)...
          (condition-case err (progn (projectile-mode 1) (let ((sym 'projectile-rele...
          ((closure (t) nil (condition-case err (progn (projectile-mode 1) (let ((sy...
          (eval-after-load-helper "/home/dogu/.emacs.d/.local/straight/build-27.2/pr...
          (run-hook-with-args eval-after-load-helper "/home/dogu/.emacs.d/.local/str...
          (do-after-load-evaluation "/home/dogu/.emacs.d/.local/straight/build-27.2/...
```
Full Log: https://dpaste.com/7RP9G5KPM#

### Describe your attempts to resolve the issue

I tried commenting, syncing, uncommenting and syncing dired in init.el also using doom build didn't work

### Steps to reproduce

1. Open Emacs
2. Try to open a directory
3. See the error

### System Information

https://dpaste.com/783SSD4A3

**Comment by hlissner** [comment]
I can't reproduce this. Perhaps your cache files are corrupt? Try deleting them:

```sh
rm -f ~/.emacs.d/.local/cache/projectile.*
```

Then restart Emacs.

**Comment by usdogu** [comment]
looks like this was the issue. Thanks a lot
