### ISSUE TITLE
lsp-sql 

### ISSUE THREAD

**Issue by OrionRandD** [hlissner/doom-emacs#5975]
### Describe your request

Could you add the lsp feature to sql?
So that in the init.el file we can install it uncommenting like other lsp server langs?
Say,

(sql +lsp)

I have tried to use mssql in doom. But only can get the lsp connected when openning an sql file.
But I am unable to make the mssql command to work...

### Briefly explain its use-case

This is my configuration for mssql in Doom:

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;; https://emacs-lsp.github.io/lsp-mssql/

(use-package! lsp-mssql)

(require 'lsp-mssql)
(add-hook 'sql-mode-hook 'lsp)

(setq lsp-mssql-connections
      [(:server "localhost"
                :database ""
                :user "SA"
                :password "demoPWD2")])

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

I need some help:
I have tried to connect the lsp-mssql-connect in Emacs to no avail...  https://emacs-lsp.github.io/lsp-mssql/

I can connect the server. But, the lsp-mssql-connect fails to access the database

~/Documents/programming_courses/sql_course
LSP :: Connected to [sql:227538/starting].
Undo-Fu-Session discarding undo data: file length mismatch for "/home/user/Documents/programming_courses/sql_course/test.sql"
LSP :: sql:227538 initialized successfully in folders: (/home/user/Documents/programming_courses/sql_course)
evil-line-move: End of buffer

Then, when I issue:
M-x lsp-mssql-connect
I get this error:

connect with the following error error number: 0
A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 40 - Could not open a connection to SQL Server)
evil-line-move

**Comment by hlissner** [comment]
Doom does not have a `:lang sql` module, so there is no module to add a `+lsp` flag to. I'll close this since there is nothing to do here.

> I need some help:

Please send support requests [to the lsp-mode Discord](https://discord.gg/swuxy5AAgT). Our issue tracker is for bug reports and feature requests.
