### ISSUE TITLE
Doom-Emacs deletes FORTRAN *.mod files

### ISSUE THREAD

**Issue by M0M097** [hlissner/doom-emacs#5978]
### What did you expect to happen?

When I open/find-file a FORTRAN source file (mod_module.f90) that defines a module the actual modul file (mod_module.mod) should not get deleted. 

### What actually happened?

When I open a file mod_module.f90 that defines a  FORTRAN module and a file mod_module.mod is present, it gets deleted.

### Describe your attempts to resolve the issue

I disabled the Fortran package, which did not help. 
I reinstalled Doom-Emacs, which did not help. 
I also asked a qustion [here](https://emacs.stackexchange.com/questions/70090/doom-emacs-deletes-fortran-module-files) but got no answer so far

### Steps to reproduce

1.
```
echo "module mod_module

contains

end module mod_module" > mod_module.f90
```
2. `touch mod_module.mod`
3. `emacs mod_module.f90`
4. close Doom-Emacs
5. `ls` 
6. verify that the file mod_module.mod got deleted
7. repeat with plain Emacs to see that it is a Doom-Emacs issue 

### System Information

> Executing 'doom version' with Emacs 27.2 at 2022-01-11 01:07:37   Doom emacs    v21.12.0-alpha   grafted, HEAD -> develop, origin/develop, origin/HEAD 9cba286 2022-01-10 02:24:21 +0100   Doom core     v3.0.0-alpha     grafted, HEAD -> develop, origin/develop, origin/HEAD 9cba286 2022-01-10 02:24:21 +0100

**Comment by M0M097** [comment]
I just did another fresh installation of doom and made sure I moved all my custom configurations before, but I still have the same issue.  If I run `while true; do ls; done` while I edit the file, I can see that the *mod file gets deleted at the moment I finish typing the `end module mod_module` line. Not that I don't have to save the file! The moment I finish typing that line, the *mod file gets deleted.

**Comment by M0M097** [comment]
Output of M-x doom/info is:
generated    Jan 11, 2022 12:31:26
system       "Slackware Linux " Linux 5.14.6 x86_64 x
emacs        27.2 ~/.config/emacs/ -> ~/.config/emacs/
doom         21.12.0-alpha grafted, HEAD -> develop, origin/develop, origin/HEAD 9cba286 2022-01-10 02:24:21 +0100 ~/.config/doom/ -> ~/.config/doom/
shell        /bin/zsh
features     XPM JPEG TIFF GIF PNG RSVG SOUND GPM DBUS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS JSON UNEXEC LCMS2 GMP
traits       gui server-running envvar-file
modules      :completion company vertico :ui doom doom-dashboard doom-quit hl-todo modeline ophints (popup +defaults) vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold snippets :emacs dired electric undo vc :checkers syntax :tools (eval +overlay) lookup magit :lang emacs-lisp markdown org sh :config (default +bindings +smartparens)

**Comment by M0M097** [comment]
I tried almost all combinations of minor and major modes to figure out what is causing the issue. I'm pretty sure that it is flycheck that deletes the file. At least if  I disable flycheck mode the file does not get deleted. So my current workaround is to not use flycheck in f90 mode.

**Comment by hlissner** [comment]
Then I'll consider this an upstream issue. Please report it to [flycheck](https://github.com/flycheck/flycheck).

**Comment by fosskers** [comment]
@M0M097 are you using the Fortran LSP?
