### ISSUE TITLE
:tags: in org-mode files

### ISSUE THREAD

**Issue by kastidad** [hlissner/doom-emacs#5979]
### What did you expect to happen?

Hi!

org-mode's Tags are NOT being displayed close to the RIGHT border as is expected (look attached pics):

- correct:
![org TAGS emacs-vanilla](https://user-images.githubusercontent.com/46639118/148880564-ee11834e-fae9-4667-9a7a-0ae2d5c396ea.png)

- doom's:
![org TAGS emacs-doom](https://user-images.githubusercontent.com/46639118/148880560-1a631e3a-d6d5-40cf-ab5a-b23b635d029b.png)

In the correct form is easier to find/look/manage the tags.

I looked for reports, help and/or posts about this issue and found none.

Maybe I'm NOT doing something required?

Thanks!

### What actually happened?

![org TAGS emacs-doom](https://user-images.githubusercontent.com/46639118/148880560-1a631e3a-d6d5-40cf-ab5a-b23b635d029b.png)

### Describe your attempts to resolve the issue

I looked for reports, help and/or posts about this issue and found none.

### Steps to reproduce

`M-x org-set-tags-command`
choose or enter a new tag

### System Information

https://pastebin.com/S9wQ6PpU

**Comment by hlissner** [comment]
Not a bug. Adjust `org-tags-column` (see `C-h v org-tags-column`):

```elisp
(after! org
  (setq org-tags-column -77))
```

**Comment by kastidad** [comment]
Oh! Thank you!

How couldn't I find this information anywhere.

Many Thanks! for this and for Doom 👍
