### ISSUE TITLE
main README's links to the Roadmaps are broken

### ISSUE THREAD

**Issue by jrmiller82** [hlissner/doom-emacs#5980]
### What did you expect to happen?

I expected to click on a link and for it to work instead of 404'ing. 

### What actually happened?

It 404'd. 

### Describe your attempts to resolve the issue

Posting an issue here.

### Steps to reproduce

Got to the repo's main readme file and click on any of the 3 links in Roadmap section.

### System Information

no.

**Comment by hlissner** [comment]
Duplicate of #5973

**Comment by jrmiller82** [comment]
Sorry; didn't mean to submit a duplicate. Thanks!
