### ISSUE TITLE
Bug with prettier-emacs cloning

### ISSUE THREAD

**Issue by asf89** [hlissner/doom-emacs#5982]
### What did you expect to happen?

When I run `doom sync`, it should return a successful result.

### What actually happened?

When I run `doom sync`, an error appears when it is cloning the repo `prettier-emacs`:

![prettier-emacs-error](https://user-images.githubusercontent.com/35273424/148945076-ef138bb4-e63c-4439-84ee-1d815e5e3f6a.png)

I can't use Doom because the sync doesn't complete.

### Describe your attempts to resolve the issue

I tried to locate the section of code that clones the repo so I could modify the cloning format, but I couldn't find it. 

### Steps to reproduce

run `doom sync`

### System Information

https://pastebin.com/wKeLWxjG

**Comment by iyefrat** [comment]
It seems that you are trying to fetch from a release branch where none exists. did you just add the package to doom? what did you write in your `packages.el`?

**Comment by asf89** [comment]
I checked and I did write in my `packages.el` to add the `prettier` package. I changed the branch to clone there. Problem solved.
