### ISSUE TITLE
Kotlin LSP module does not work because kotlin lsp server download link is no longer valid

### ISSUE THREAD

**Issue by dCaples** [hlissner/doom-emacs#5984]
### What did you expect to happen?

When I open a kotlin file it should download and install the kotlin language server.

### What actually happened?

When I open a kotlin file and select to download the kotlin language server, it does

### Describe your attempts to resolve the issue

When I opened a kotlin file, doom prompted me to install the kotlin language server, but it failed. The reason it failed can be seen in messages. It tries to download the language server, but the link it tries is unavailable, just try git cloning it:
https://github.com/fwcd/kotlin-language-server/releases/download/latest/server.zip
It should be trying to get the server from here somehow:
https://github.com/fwcd/kotlin-language-server/releases/
I tried to download the latest zip file server release on the website, but in I put it in the location that doom wanted it downloaded to 
/home/diegocaples/.emacs.d/.local/etc/lsp/kotlin/kotlin-language-server.zip
 and tried to start the lsp install again, but it just overwrote my zip file with an empty zip file. I also extracted the zip file, but it didn't work, and still prompted me to install the kotlin lsp server.

### Steps to reproduce

1. add lsp to init.el
2. add (kotlin +lsp) to init.el
3. open a kotlin file; you will be prompted to install kotlin server
4. the install will fail

### System Information

https://pastebin.com/QrDVWXp9

**Comment by elken** [comment]
This should instead be reported to lsp-mode

**Comment by hlissner** [comment]
This is indeed an upstream issue. Please report it to lsp-mode. I'll leave this open until it's addressed and we've bumped the package.

**Comment by elken** [comment]
https://github.com/emacs-lsp/lsp-mode/pull/3315

**Comment by hlissner** [comment]
This issue should now be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
