### ISSUE TITLE
In effect disabling bidi for imagined speed improvements is the wrong thing to do.

### ISSUE THREAD

**Issue by mohsenBanan** [hlissner/doom-emacs#5987]
### What did you expect to happen?

I expected doom to behave properly with respect to bidi text.

### What actually happened?

Auto paragraph directionality is messed up. It is limited to left-to-right.

### Describe your attempts to resolve the issue

The following should be removed from core.el.
Default vanilla bidi emacs settings are the right settings. Don't mess with them.

Remove all bidi stuff from core.el. 
In specific, all of:
```
;; Disable bidirectional text scanning for a modest performance boost. I've set
;; this to `nil' in the past, but the `bidi-display-reordering's docs say that
;; is an undefined state and suggest this to be just as good:
(setq-default bidi-display-reordering 'left-to-right
              bidi-paragraph-direction 'left-to-right)

;; Disabling the BPA makes redisplay faster, but might produce incorrect display
;; reordering of bidirectional text with embedded parentheses and other bracket
;; characters whose 'paired-bracket' Unicode property is non-nil.
(setq bidi-inhibit-bpa t)  ; Emacs 27 only
```

The imagined  "Optimizations" optimization for latin users at the expense of bidi languages is
the wrong trade off. It points to mono-cultures-of-the-mind.

See https://www.youtube.com/watch?v=kqIZb80OIKE

### Steps to reproduce

Write some bidi text in a buffer.

### System Information

All systems

**Comment by hlissner** [comment]
I'm sorry that it adds an extra step for RTL language users. I may reconsider this later, but for the moment I don't intend to change this default. If Emacs addressed its performance deficits, then I wouldn't have to make such exclusionary decisions, but it makes enough of a demonstrable difference that I must defend it -- as Emacs' performance issues is among my highest priorities for Doom.

Fortunately, however, it's a simple thing to reverse:

```lisp
;; add to $DOOMDIR/config.el
(setq-default bidi-display-reordering t
              bidi-paragraph-direction nil
              bidi-inhibit-bpa nil)
```

And there is also work on [a bidi module](https://github.com/hlissner/doom-emacs/pull/5526) that will reactivate bidi and then some.

I'll close this for now, but will post here again if/when I revisit the topic.

**Comment by iyefrat** [comment]
@mohsenBanan I'd appreciate any feedback you can offer on the bidi module, I think it's in a good place, but I rely on other people to find issues with farsi (or other arabic derived scripts)

**Comment by mohsenBanan** [comment]
@iyefrat  I don't see a doom module called bidi. Please expand about what you mean.

**Comment by mohsenBanan** [comment]
@iyefrat -- Sorry about my previous question.  I did not notice  " And there is also work on a bidi module that will reactivate bidi and then some. " at first.
Let me look into that. I'll follow up later.

**Comment by mohsenBanan** [comment]
@iyefrat  (CC: @hlissner ): I looked at the bidi-module. It is a good thing. It is needed as it fills a need.
I had built something similar for myself and a general solution is called for.
But, I don't think that framing it as just a doom-module is the right thing to do. To maximize social benefit, it is better to first create a melpa bidi-mode++ package and then bring that over and config it as a doom-module.
Also, the scope of some of what you are doing is broader than bidi. It is multilingualization in general and it overlaps 
things like https://github.com/laishulu/emacs-smart-input-source ...
My suggestion is that we continue such discussions on https://lists.gnu.org/mailman/listinfo/emacs-bidi and bring the likes of Eli and others into the picture ...
Also, I have a menu that goes with my equivalent of your bidi minor mode that could be useful for some ...
What are your thoughts about all of this?

**Comment by iyefrat** [comment]
@mohsenBanan I think that you are generally right, but unfortunately I don't have much free time these days (hence the delayed response), so I can't really say when I'll be able to continue on this subject properly. A few points in the mean time:

- The bidi module is small as is, and a lot of the font stuff is to get doom's font system to play nice with bidi text. Emacs by default seems to use a perfectly fine (non-monospace) font for Hebrew at least, so I need to check what parts are relevant for vanilla emacs before bringing it up on the mailing list.

- It's true that some of the things in the module are broader than bidi and could be better organized. A while back I looked into `sis.el` and I think I was dissatisfied with it, but I can't remember why. I'll give it a proper look when I have more time.
