### ISSUE TITLE
`pip-requirements` package causes Emacswide hang when opening Python `requirements.txt` file

### ISSUE THREAD

**Issue by bleggett** [hlissner/doom-emacs#5998]
### What did you expect to happen?

Opening a Python `requirements.txt` file should open the file normally.

### What actually happened?

Opening a `requirements.txt` file causes Emacs to hang indefinitely - waited 20 mins. Have to kill via process manager.

### Describe your attempts to resolve the issue

Forcibly disabling `pip-requirements` via `packages.el` solves the hang for me:

`(package! pip-requirements :disable t)` - `requirements.txt` files open normally without hangs.

### Steps to reproduce

1. Enable python in your `init.el`:

```
       (python +lsp)
```

2. Open a valid python `requirements.txt` file

3. Observe hang

### System Information

https://pastebin.com/raw/pK8DBYcX

**Comment by bleggett** [comment]
> ```emacs-lisp
> (advice-add #'pip-requirements-fetch-packages :override #'ignore)
> ```


Adding this does fix it, yes.

An example of requirements.txt that can trigger this for me:

```
boto3
graphframes
ipycytoscape
pyspark==3.2.0
```

**Comment by hlissner** [comment]
Sorry for the tremendously late response. This is certainly an upstream issue (see https://github.com/Wilfred/pip-requirements.el/issues/11). I've mitigated this issue locally by deferring the HTTP request until the first time completion is invoked. Granted, if you're using idle completion, chances are this won't be long after opening a pip-requirements-mode buffer, but this seems like a decent compromise. In any case, this should be tackled upstream.

Anyhow, let me know if the issue resurfaces and I'll reopen the issue. Thanks for bringing it to my attention!
