### ISSUE TITLE
100% CPU usage and freeze in project with thousands of files

### ISSUE THREAD

**Issue by Jeiwan** [hlissner/doom-emacs#6000]
### What did you expect to happen?

Doom Emacs doesn't freeze when working with Golang.

### What actually happened?

When I open a Golang project, Doom Emacs freezes consuming 100% of CPU. I don't need to do anything, just open a Golang file. This lasts very long so I eventually had to kill it because it's unusable.
This whole project was programmed in Doom Emacs and everything had been ok until I updated Doom and Emacs a couple of days ago (I had an old version of Doom, maybe more than 6 months old).

This is a fresh install: Emacs 27.2, latest Doom. The only changes in `init.el` are uncommented `go` and `lsp` modules. There are no logs or error messages.

### Describe your attempts to resolve the issue

It looks like it's indexing my project and its dependencies for autocompletion (I guess). The fact that it's Emacs that uses 100% CPU, not `gopls`, makes me think that.

The issue doesn't happen when `go` and `lsp` packages are not installed.

### Steps to reproduce

1. `brew install --cask emacs`
1. `git clone --depth 1 https://github.com/hlissner/doom-emacs ~/.emacs.d`
1. `~/.emacs.d/bin/doom install`
1. Open Emacs, edit `init.el`, uncomment `go` and `lsp` modules.
1. Run `~/.emacs.d/bin/doom sync` and `doom/reload`.
1. Open a big Golang project or a project that uses a heavy dependency.

### System Information

https://pastebin.com/rimY6Bre

**Comment by Jeiwan** [comment]
I debugged it a little bit more:
1. I left it running for several hours and it hadn't unfrozen.
1. The issue happens only when go-mode is installed with LSP support.
1. The issue happens only in one project. Other projects are ok.
1. It starts hanging a few seconds after LSP is initialized (a message is printed).
1. Reverting either `lsp` or `go` modes to older commits didn't help.
1. This doesn't happen in VSCode, even though it also uses LSP.

**Comment by Jeiwan** [comment]
Added this to `config.el`:
```lisp
(setq lsp-go-gopls-server-args '("-logfile" "/Users/jeiwan/.tmp/gopls.log" "-vv" "-debug" ":8080"))
```
The log file is empty and there's nothing interesting on the debug server.

**Comment by Jeiwan** [comment]
Alright, I found the cause. That project has 170+ thousand of files (not related to Go). When Emacs opens it, it starts analyzing them or maybe caching or maybe indexing – and this is when it hangs.

I installed Doom at commit 42d5da83cc4d13454646ca5ad3afa97cbe8c00fc. When I opened the project, it showed me this message:
> There are 173301 files in folder ... so watching the repo may slow Emacs down. Do you want to watch all files in ... ? (y or n)

When choosing `n` it works without issues, when choosing `y` it hangs.

At commit 79c1fcefcf2b135deacb743dc5d2badeb67db09c, everything works without any issues and it doesn't ask about watching files.

It seems that a module was added that scans/analyzes/watches all files in a project and it just cannot handle so many files. If so, the question is: how to ignore those files? (They're ignored in `.gitignore`)

**Comment by jeetelongname** [comment]
What is the value of `lsp-enable-file-watchers`? back when I used to write go thats what caused the issue and it should be set to `nil` if not then you can set it to `nil` in go mode with this snippet
```lisp
(setq-hook! 'go-mode-hook
     lsp-enable-file-watchers nil)
```

**Comment by Jeiwan** [comment]
@jeetelongname Thanks for pointing this out! However, I do need the watchers, so I simply added the cache folder to ignored ones:
```elisp
(with-eval-after-load 'lsp-mode
  (add-to-list 'lsp-file-watch-ignored-directories "[/\\\\]cache\\'"))
```
