### ISSUE TITLE
Unrecognized switch -n on every command because every command has -nw extended.

### ISSUE THREAD

**Issue by pontakornth** [hlissner/doom-emacs#6003]
### What did you expect to happen?

The command should be run without problem. I mean every command I use has `-nw` even I didn't specify it.

### What actually happened?

When I attempt to install doom, it has `-nw` flag. The problem is when I run it, it says `Unrecognized flag -n`.

<img width="865" alt="Screen Shot 2565-01-15 at 23 28 03" src="https://user-images.githubusercontent.com/37771900/149629798-fe22e34b-4c4b-477c-b065-d2b05d5cad5a.png">

It also happens to other commands. I am not sure if my previous Spacemacs installation has anything to do with it.

Edit: Add info about Spacemacs.

### Describe your attempts to resolve the issue

I accidentally solved it by adding `-` at the end of the installation command. It should still work with out it.

```bash
~/.emacs.d/bin/doom install
```

### Steps to reproduce

1. Remove `.emacs.d` by `rm -rf`
2. Follow installation instruction on the home page by cloning the repo to `~/.emacs.d`
3. Run `~/.emacs.d/bin/doom install`.

### System Information

https://pastebin.com/PZzr5k3p

**Comment by hlissner** [comment]
This sounds like either:

- You have set the `EMACS` envvar to something like `emacs -nw`, which is not supported. Unset this, or do `EMACS=emacs doom install`.
- Or whatever source you've installed Emacs from uses a shim script. If you do `cat $(which emacs)`, it's probably going to look something like:

  ```elisp
  #!/usr/bin/env sh
  emacs -nw $@
  ```

  If this is the case, make sure Emacs is installed [from one of the correct sources](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#on-macos).

In any case, neither of these issues are Doom issues, so I will close this until there is something that Doom can do to address this issue. Feel free to follow up here, regardless.

**Comment by pontakornth** [comment]
Thank you for explanation. I will check it once I can.
