### ISSUE TITLE
Doom installs out-of-date doom-themes package

### ISSUE THREAD

**Issue by ObsidianChickenz** [hlissner/doom-emacs#6007]
### What did you expect to happen?

I expected the doom-themes package to be up to date.

### What actually happened?

The package is missing the doom-material-dark, doom-meltbus, and doom-tokyo-night themes. This can be verified through the SPC-h-t command, where the three themes are missing, and by checking ~/.emacs.d/.local/straight/repos/themes/themes, where the theme files are missing.

### Describe your attempts to resolve the issue

I deleted .emacs.d and .doom.d and reinstalled Doom from scratch, then checked the themes folder for the files.

### Steps to reproduce

1) Install Emacs and Doom.
2) Run SPC-h-t and check if the previously listed themes are there.

### System Information

https://pastebin.com/aUAsbv3F

**Comment by hlissner** [comment]
Not a bug. Doom pins its packages. See https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#pinning-packages-to-specific-commits for instructions on how to un/repin packages. Run `doom sync -u` to update packages once you have.

**Comment by ObsidianChickenz** [comment]
Thanks!
