### ISSUE TITLE
Unicode fonts are not displayed correctly

### ISSUE THREAD

**Issue by KIVix** [hlissner/doom-emacs#6009]
### What did you expect to happen?

Unicode Cyrillic fonts differ from the Latin alphabet in their size.

### What actually happened?

Hello world Привет мир
![изображение](https://user-images.githubusercontent.com/11228323/149662732-6d1357b9-9359-481a-8dc5-8d9717075b72.png)

```lisp
 (setq doom-font (font-spec :family "JetBrains Mono" :size 15)
     doom-variable-pitch-font (font-spec :family "JetBrains Mono" :size 16))
    ;; doom-unicode-font (font-spec :family "JetBrains Mono" :size 15) 
 (setq doom-unicode-font (font-spec :family "JetBrains Mono" :size 15 :slant 'normal :weight 'normal))
```
Changing various settings and sizes of unicode fonts does not lead to the desired result.

The doom/reload-font command results in the following Cyrillic script.
![изображение](https://user-images.githubusercontent.com/11228323/149662802-c010ea48-9990-48bd-83ea-8d25471cb023.png)

At the same time, if you do doom/reload and doom/reload-font, they will become normal height, but after restarting emacs everything is new
![изображение](https://user-images.githubusercontent.com/11228323/149662874-a6e9aed8-2c09-4290-9b27-543f8f20a73c.png)

But the increase and decrease of the font size in the buffer breaks.
![изображение](https://user-images.githubusercontent.com/11228323/149662934-c177d245-ef01-4d07-aee7-3ddd5778be3c.png)

### Steps to reproduce

1. Open emacs 
2. Write `Привет мир Hello world`
3. And end

### System Information

https://pastebin.com/QfdXbKGN

**Comment by iyefrat** [comment]
It might work if you remove the `:size` setting, see #5129. Although for one person there that wasn't enough, see [here](https://github.com/hlissner/doom-emacs/issues/5129#issuecomment-884156277).

**Comment by KIVix** [comment]
After removing `:size` nothing changes, still not same.

But #5129 help me to fix this problem for Cyrillic font.

**Comment by KIVix** [comment]
After removing :size nothing changes, still not same.

But #5129 help me to fix this problem for Cyrillic font.
