### ISSUE TITLE
ob-jupyter fails to load with native-comp 

### ISSUE THREAD

**Issue by Jonghyun-Yun** [hlissner/doom-emacs#6018]
### What did you expect to happen?

With `native-comp`, `ob-jupyter` fails to work.

### What actually happened?

Evaluating `jupyter-python` org-src-block throws the below error.

```
Check for compatible module binary to download? (y or n) y
Downloading https://github.com/nnicandro/emacs-zmq/releases/download/v0.10.10/emacs-zmq-x86_64-apple-darwin17.4.0.tar.gz
Verifying sha256 signature of emacs-zmq-x86_64-apple-darwin17.4.0.tar.gz
Wrote /Users/yunj/doom-emacs/.local/straight/build-28.0.91/zmq/emacs-zmq-x86_64-apple-darwin17.4.0.tar.gz
Jupyter: (cl-assertion-failed (not enable-multibyte-characters))
org-babel-execute-src-block: No org-babel-execute function for jupyter-python!
```

### Describe your attempts to resolve the issue

The issue seems to be related to https://github.com/nnicandro/emacs-jupyter/issues/297 and #5592. A temporary working solution is to disable `native-comp` in `core/core.el` for `emacs-jupyter` as suggested in #5592.
``` emacs-lisp
(with-eval-after-load 'comp
    ;; HACK Disable native-compilation for some troublesome packages
    (mapc (doom-partial #'add-to-list 'native-comp-deferred-compilation-deny-list)
          (let ((local-dir-re (concat "\\`" (regexp-quote doom-local-dir))))
            (list (concat local-dir-re ".*/evil-collection-vterm.*\\.el\\'")
                  (concat local-dir-re ".*/emacs-jupyter.*\\.el\\'")
                  (concat local-dir-re ".*/with-editor.*\\.el\\'")))))
```

### Steps to reproduce

Evaluate `jupyter-python` org-src-block when `native-comp` is used.

### System Information

https://pastebin.com/xwzJYn05

**Comment by hlissner** [comment]
This issue should now be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
