### ISSUE TITLE
[bug] jk exits insert mode

### ISSUE THREAD

**Issue by philiparvidsson** [hlissner/doom-emacs#6020]
### What did you expect to happen?

When I am in insert mode and hold j for a bit, then press k I expect the following to happen:

Lots of j's inserted and then a k that aborts the repetition of j is inserted. Expected output would be:

jjjjjjjjjjjk

### What actually happened?

Doom Emacs exits insert mode, deletes the last j and k is never inserted.

Output would be:
jjjjjjjjjj

### Describe your attempts to resolve the issue

I don't understand what is happening. Is this an issue with my kb firmware, Doom Emacs or expected behavior?  I have tried looking into the docs but cannot find it.

### Steps to reproduce

1. Open Emacs
2. Press SPC X to open scratch buffer.
3. Press i for insert mode.
3. Hold j until it starts repeating.
4. While holding j, press k.

### System Information

-

**Comment by elken** [comment]
This is intended, I believe setting `evil-escape-key-sequence` to nil should turn it off.

**Comment by jeetelongname** [comment]
Turning off evil escape mode should do the same thing if a person does not want to use it at all.

**Comment by philiparvidsson** [comment]
Thank you, I'll be using this as a clever shortcut instead of escape ahead from here.
