### ISSUE TITLE
evil-paste-pop doen't work with C-p

### ISSUE THREAD

**Issue by otavioschwanck** [hlissner/doom-emacs#6021]
### What did you expect to happen?

after pasting something on normal mode and pressing C-p, invoke evil-paste-pop.

### What actually happened?

C-h k C-p = evil-mc-make-and-goto-first-cursor

### Steps to reproduce

Open emacs
copy two things
Paste first
Press C-p.

MY CONFIG:

https://github.com/otavioschwanck/doom-emacs-on-rails

### System Information

https://pastebin.com/8eUqxMZA

**Comment by hlissner** [comment]
Give this a try:

```elisp
;; add to $DOOMDIR/config.el
(after! evil-mc
  (global-evil-mc-mode -1)
  (add-hook 'evil-mc-before-cursors-created #'evil-mc-pause-incompatible-modes)
  (add-hook 'evil-mc-before-cursors-created #'evil-mc-initialize-active-state)
  (add-hook 'evil-mc-after-cursors-deleted  #'evil-mc-teardown-active-state)
  (add-hook 'evil-mc-after-cursors-deleted  #'evil-mc-resume-incompatible-modes)
  (advice-add #'evil-mc-initialize-hooks :override #'ignore)
  (advice-add #'evil-mc-initialize-active-state :before #'turn-on-evil-mc-mode)
  (advice-add #'evil-mc-teardown-active-state :after #'turn-off-evil-mc-mode))
```

**Comment by hlissner** [comment]
This issue should now be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
