### ISSUE TITLE
Native comp on Apple M1 failing via 'doom sync'

### ISSUE THREAD

**Issue by MicLennartz** [hlissner/doom-emacs#6035]
### What did you expect to happen?

When I run `doom install` or `doom sync` it should execute the native compilation of all packages and finish the script.

This is running well on an X64 based Macbook, using the same versions of Emacs, doom and my configuration.

### What actually happened?

When I run the `doom install` or `doom sync` on an Apple M1 based systems, the native compile phase instantly fails with an error:
```
      x There was an unexpected error...
        Message: File error
        Error: (file-error "Failed select" "Operation timed out")
        Backtrace:
          (sleep-for 0.1)
          (let ((inhibit-message t)) (sleep-for 0.1))
          (if (/= previous pending) (progn (doom--print (doom--format (format (doom-...
          (while (progn (setq pending (doom--native-compile-jobs)) (not (= 0 pending...
          (let* ((pending nil) (previous 0) (--cl-var-- t)) (while (progn (setq pend...
          (doom--wait-for-native-compile-jobs)
          (progn (doom--wait-for-native-compile-jobs) (doom--write-missing-eln-error...
          (if NATIVECOMP (progn (doom--wait-for-native-compile-jobs) (doom--write-mi...
          (progn (doom--compile-site-packages) (if NATIVECOMP (progn (doom--wait-for...
          (if built (progn (doom--compile-site-packages) (if NATIVECOMP (progn (doom...
```

This is the full error log:
[Pastebin](https://pastebin.com/rxHBfNTt)

### Describe your attempts to resolve the issue

Running the native compile from within Emacs seems to be working with this command:

```
 (native-compile-async "<path-to-packages>" 'recursively)
```

The eln cache folder (~/.emacs.d/.local/cache/eln/28.0.91....) is populated with compiled files as expected.

### Steps to reproduce

Run `doom install` or `doom sync`.

### System Information

https://pastebin.com/B7n3NthR

**Comment by elken** [comment]
Are these both occuring on (what I assume to be) Monterray?

**Comment by MicLennartz** [comment]
Yes, the good one (X64) and the failing one (M1) are both running on 12.1.

**Comment by elken** [comment]
And both systems are otherwise identical? Same versions of everything? How did you install emacs?

**Comment by MicLennartz** [comment]
Well, not 100% identical, I guess: The M1 is installed and used for a while already, and the X64 is a new one. But OS and Emacs version (+dependencies) are on the same, most recent patch level. My config (~/.doom.d) is synced via git.
I install emacs via homebrew:

```
brew install emacs-plus@28 --with-modern-black-dragon-icon --with-xwidgets --with-native-comp
```
(from 'd12frosted/emacs-plus' repo)

**Comment by elken** [comment]
Odd, I'm not sure then. I don't have an M1 device anymore but when I did I didn't hit it.

@hlissner has anything changed since december that would impact this?

**Comment by MicLennartz** [comment]
Here's some update regarding this issue ....

During some additional investigations it turned out, that this problem was NOT reproducible on anther M1 based system. Furthermore the problem were related to the way, how home-brew did the 'reinstall' of emacs-plus the impacted system.
(see [emacs-plus readme](https://githubhelp.com/d12frosted/homebrew-emacs-plus#reinstall?ref=https://githubhelp.com))

An uninstall / cleanup / install for the same version of emacs-plus solved the problem. So I close the issue here.

Anyhow, thank's for looking into this.
