### ISSUE TITLE
Upgrading causes `:tools biblio` to raise a `void-variable citar-bibliography` error at startup.

### ISSUE THREAD

**Issue by abougouffa** [hlissner/doom-emacs#6047]
### What did you expect to happen?

Enable `:tools biblio`

### What actually happened?

Upgrading (with https://github.com/hlissner/doom-emacs/commit/5656a96a1bca6afb1842e08dcb58f91289150404) causes `:tools biblio` to raise a `void-variable citar-bibliography` error at startup.

```
Warning (initialization): An error occurred while loading ‘/home/abdelhak/.emacs.d/init.el’:

Error in a Doom module: modules/tools/biblio/config.el, (void-variable citar-bibliography)

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.
```

### Steps to reproduce

1. Upgrade to https://github.com/hlissner/doom-emacs/commit/5656a96a1bca6afb1842e08dcb58f91289150404
2. Enable `:tools biblio`
3. Run `doom sync`
4. Restart Emacs

### System Information

https://pastebin.com/x4cYAsmX

**Comment by jlcolbert** [comment]
Can confirm I ran into this as well. Uncommented the module until this is resolved.

**Comment by hlissner** [comment]
This issue should now be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
