### ISSUE TITLE
fontconfig isn't installed with fresh install

### ISSUE THREAD

**Issue by Jake-Mulhern** [hlissner/doom-emacs#6053]
### What did you expect to happen?

Doom doctor would find no issues with a fresh install

### What actually happened?

After deleting and re-installing Doom Emacs I ran Doom Doctor and ran into the following issue.

Checking Doom core for irregularities...
! Warning: unable to detect fonts because fontconfig isn't installed

### Describe your attempts to resolve the issue

I tried deleting again and reinstalling.

### Steps to reproduce

Install emacs using the following command.

```
git clone --depth 1 https://github.com/hlissner/doom-emacs ~/.emacs.d
~/.emacs.d/bin/doom install
```
and then 
$ cd .emacs
$ bin/doom doctor

### System Information

https://pastebin.com/rPhZYkYZ

**Comment by elken** [comment]
Install fontconfig using your distros package manager.

**Comment by hlissner** [comment]
What Elken said. You need fontconfig so Doom's doctor can look up what fonts you have installed. If you don't want/need fontconfig, then ignore the warning.

I'll close this, since there is no bug here.
