### ISSUE TITLE
emacsclient doesn't trigger file template

### ISSUE THREAD

**Issue by vinurs** [hlissner/doom-emacs#6058]
### Describe your request

when i use emacsclient to create a file , it can use a file template i defined, 

### Briefly explain its use-case

i defind a file template when open .dart file
```
(set-file-template! "\\.dart$"
  :when 'fork-from-scaffold-p
  :trigger "__flutter-scaffold-template.dart" :mode 'dart-mode)
```
but when i in terminal and use emacsclient to create a new file, the trigger seems not be triggered, but when i in emacs and use `counsel-find-file` ,then the trigger is triggered

**Comment by hlissner** [comment]
This is a bug, not a feature request.

Anyhow, see if throwing this into `$DOOMDIR/config.el` fixes the issue:

```elisp
(add-hook 'server-visit-hook #'+file-templates-check-h)
```

**Comment by vinurs** [comment]
> This is a bug, not a feature request.
> 
> Anyhow, see if throwing this into `$DOOMDIR/config.el` fixes the issue:
> 
> ```emacs-lisp
> (add-hook 'server-visit-hook #'+file-templates-check-h)
> ```

yes, add this can fix this issue

**Comment by hlissner** [comment]
As of 4a6de24 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
