### ISSUE TITLE
describe-function / describe-variable fails with unexpected error in emacs 29.0.50

### ISSUE THREAD

**Issue by Lynntee** [hlissner/doom-emacs#6063]
### What did you expect to happen?

`describe-function` or `describe-variable` should return information about the function or variable.

### What actually happened?

When I press `SPC h f` or `SPC h v` and enter something, like `reftex-ref-style-alist`, an error arises:
`elisp-refs--read-all-buffer-forms: Unexpected error whilst reading /usr/share/emacs/29.0.50/lisp/textmodes/reftex-vars.el position 974: (void-variable read-symbol-positions-list)`

Other variables or functions also lead to the same error with different path.

### Describe your attempts to resolve the issue

I tried upgrade / reinstall doom emacs, reinstall emacs itself.
This error still arises and I cannot check any documentation for  any variable and function.

I tried to use `emacs -Q`, everything works fine.
I tried to use emacs 27 with the newest doom emacs, everything is fine.

### Steps to reproduce

1. Open emacs.
2. Press `SPC h v` and enter any variable.
3. An error arises.

### System Information

https://pastebin.com/rQmtmu83

**Comment by usaoc** [comment]
This is not a Doom issue.  `read-symbol-positions-list` was recently [deprecated in master](https://github.com/emacs-mirror/emacs/commit/dfae76c9915454f9ef0885e1bac160a2c480e1d1), while `elisp-refs--read-buffer-form` happens to [expect it to be present](https://github.com/Wilfred/elisp-refs/blob/fa1de199e07fb020b776fb585613682901962ed6/elisp-refs.el#L101).  Helpful depends on Elisp-refs and thus ends up erroring.  Related issue: Wilfred/elisp-refs#35

**Comment by Lynntee** [comment]
Thank you very much.
I have found an alternative method to see the desired information.
Compare to use shortcut, using `M-x` then input `describe-function` or `describe-variable` works.

**Comment by hlissner** [comment]
A temporary workaround was added in c6d3cee, at least until the issue is addressed upstream.
