### ISSUE TITLE
commit 3d0745c changed the mu4e dashboard

### ISSUE THREAD

**Issue by liujoey** [hlissner/doom-emacs#607]
The recent commit 3d0745c made the mu4e dashboard ugly.
Before this commit, the dashboard looks like this:
<img width="276" alt="screen shot 2018-05-23 at 12 48 16 pm" src="https://user-images.githubusercontent.com/123727/40439363-b9e810e0-5e88-11e8-9802-98f5d04897ef.png">
After the commit, it lost all colors and indentation:
<img width="285" alt="screen shot 2018-05-23 at 12 54 38 pm" src="https://user-images.githubusercontent.com/123727/40439387-c95e75f0-5e88-11e8-868c-66c76f8dac7c.png">

**Comment by hlissner** [comment]
As of 2d6bef3 this should be resolved. Let me know if that isn't the case!

If it's fixed, I'll keep this open until it gets merged into `master`.

**Comment by hlissner** [comment]
Ah, my bad. I tagged the wrong commit! 1aec48a should resolve this issue.
