### ISSUE TITLE
Conda environments cannot be found due to home wrongly being set to "~/.conda"

### ISSUE THREAD

**Issue by SimonAltrogge** [hlissner/doom-emacs#6071]
### What did you expect to happen?

Using the `+conda` flag of the `python` module, I expect my environments to be found.

### What actually happened?

The environments are not found.

### Describe your attempts to resolve the issue

This seems to be related to commit bcb29f7d175bd206b050447a14df32c82f671db9, which causes the `conda-anaconda-home` and `conda-env-home-directory` variables to be set to "\~/.conda" instead of "\~/miniconda3".

The "\~/.conda" folder is automatically created by conda, even if it is installed to "\~/miniconda3". In it there is only an "environments.txt" text file that lists the paths to the different conda environments.

Renaming or removing the "\~/.conda" folder resolves this problem, but only until it is recreated when e.g. creating a new conda environment.

### Steps to reproduce

1. Have some form of conda (e.g. Miniconda) installed and at least one environment created
2. In your init.el, enable the `python` module with `+conda` flag
3. Open Emacs
4. `M-x conda-env-list` and find an empty buffer

### System Information

https://pastebin.com/A4gQTmf9

**Comment by hlissner** [comment]
This issue should now be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
