### ISSUE TITLE
use-package: Unrecognized keyword: :straight

### ISSUE THREAD

**Issue by prehonor** [hlissner/doom-emacs#6075]
### What did you expect to happen?

(use-package! websocket
    :after org-roam)

(use-package org-roam-ui
  :straight
    (:host github :repo "org-roam/org-roam-ui" :branch "main" :files ("*.el" "out"))
    :after org-roam
;;         normally we'd recommend hooking orui after org-roam, but since org-roam does not have
;;         a hookable mode anymore, you're advised to pick something yourself
;;         if you don't care about startup time, use
;;  :hook (after-init . org-roam-ui-mode)
    :config
    (setq org-roam-ui-sync-theme t
          org-roam-ui-follow t
          org-roam-ui-update-on-save t
          org-roam-ui-open-on-start t))

It should work

### What actually happened?

doom doctor
> Executing 'doom doctor' with Emacs 28.0.91 at 2022-02-02 07:39:06
  The doctor will see you now...
  
  > Checking your Emacs version...
    ! Emacs 28.0.91 detected
      Doom supports this version, but you are living on the edge! Be prepared for
      breakages in future versions of Emacs.
  > Checking for Doom's prerequisites...
  > Checking for Emacs config conflicts...
  > Checking for great Emacs features...
  > Checking for private config conflicts...
  > Checking for stale elc files...
  ! ~/.emacs.d.doom/.local/straight/build-28.0.91/markdown-mode/markdown-mode.elc is out-of-date
  > Checking for problematic git global settings...
  > Checking Doom Emacs...
    x There was an unexpected error
      Message: error
      Error: (error "use-package: Unrecognized keyword: :straight")
      Backtrace:
        (error "use-package: %s" "Unrecognized keyword: :straight")
        (use-package-normalize-plist org-roam-ui (:straight (:host github :repo "o...
        (use-package-normalize-keywords org-roam-ui (:straight (:host github :repo...
        (#[385 "\304>?\205\371\30\205\306\307\310D\311BBBC	\312=\203p\313...
        (macroexpand (use-package org-roam-ui :straight (:host github :repo "org-r...
        (internal-macroexpand-for-load (use-package org-roam-ui :straight (:host g...
        (load-with-code-conversion "/home/prehonor/.doom.d/config.el" "/home/preho...
        (load "/home/prehonor/.doom.d/config" t nomessage)
        (let (file-name-handler-alist) (load (expand-file-name "config" doom-priva...
        (condition-case e (let (file-name-handler-alist) (load (expand-file-name "...
    ! Extended backtrace logged to ~/.emacs.d.doom/.local/doom.error.log

### Steps to reproduce

follow the guide from https://github.com/org-roam/org-roam-ui
install org-roam-ui

### System Information

https://pastebin.com/B0V0w664

**Comment by brongulus** [comment]
Doom uses straight differently, look at the package management section of the documentation to see how it works.

[Getting Started - Package Management](https://github.com/hlissner/doom-emacs/blob/master/docs/getting_started.org#package-management)

**Comment by prehonor** [comment]
> Doom uses straight differently, look at the package management section of the documentation to see how it works.
> 
> [Getting Started - Package Management](https://github.com/hlissner/doom-emacs/blob/master/docs/getting_started.org#package-management)

Oh,thank you.
