### ISSUE TITLE
Shackle deleted in develop branch

### ISSUE THREAD

**Issue by drym3r** [hlissner/doom-emacs#608]
Is that correct? Seems a little weird.

PD: You may want to consider being in a irc or xmpp room or something, maybe some questions make more sense in a more distended channel.

**Comment by hlissner** [comment]
This was intended. We no longer use shackle on `develop`. Instead, the `:ui popup` module uses `display-buffer-alist` as its backend, a native feature of Emacs. Shackle was essentially a wrapper around `display-buffer-alist` anyway.

Also, we have a [Discord channel](https://discord.gg/bcZ6P3y) where I'm quite active.

**Comment by hlissner** [comment]
Since I see you've joined Discord, and have answered the original question, I'll consider this resolved. Feel free to reopen (or hit me up on Discord) if you have more questions!

**Comment by drym3r** [comment]
Thanks!
