### ISSUE TITLE
given parent class xref-parent-location is not a class in erlang-mode

### ISSUE THREAD

**Issue by heiheshang** [hlissner/doom-emacs#6083]
### What did you expect to happen?

working erlang-mode

### What actually happened?

when  run erlang-mode i'm happened

### Steps to reproduce

1. run erlang-mode

### System Information

https://pastebin.com/uvgsctA8

**Comment by hlissner** [comment]
**:warning: This issue was closed and marked for deletion for the checked reasons below:**

+ [X] Issue cannot be acted on or investigated further because:
  + [X] Could not be reproduced in vanilla Doom on any of our test environments.
  + [X] Not enough information to act on.
  + [X] Vital information was omitted or inaccessible.
  + [X] Explanations are too vague or issue is too open ended.
  + [X] It's unclear what you are trying to say.
+ [X] The following possibilities are more likely explanations and haven't been ruled out:
  + [X] A pilot error.
  + [X] Private configuration.
  + [X] A third-party package is behaving correctly, but in a manner you're not expecting.
  + [X] A corrupt or broken Emacs installation.
  + [X] Your system environment (hardware issues, the OS, shell environment, missing system dependencies, etc).

**This ruling is not absolute and _can be reversed_** if you follow up with enough information to further investigate this issue. Our [How to Debug Issues](https://discourse.doomemacs.org/how2debug) guide can help you find out more about it (note: our discourse currently requires an account).

If you still feel lost after reading our debugging guide, raise your issue on our [Discord](https://doomemacs.org/discord) or [Discourse](https://discourse.doomemacs.org) -- there may be others who have experienced it. Otherwise, this issue will be automatically deleted after 14 days.

-----
> I apologize if this is inconvenient or you feel lost, but it takes a lot of time to review issues by myself. The complexity and extensibility of Emacs tends to produce a lot of false positive or open ended bug reports, so I've restricted our issue tracker to issues that are <strong>actionable</strong>, <strong>immediately reproducible in vanilla Doom</strong>, or <strong>can be investigated in a reasonable amount of time</strong>.

**Comment by heiheshang** [comment]
`Loading erlang-skels...done
eieio-defclass-internal : Given parent class xref-parent-location`

**Comment by heiheshang** [comment]
`ebugger entered--Lisp error: (error "Given parent class xref-file-location is not a cla...")
  signal(error ("Given parent class xref-file-location is not a cla..."))
  error("Given parent class %S is not a class" xref-file-location)
  #f(compiled-function (cname superclasses slots options) "Define CNAME as a new subclass of SUPERCLASSES.\nSLOTS are the slots residing in that class definition, and OPTIONS\nholds the class options.\nSee `defclass' for more information." #<bytecode -0x9e5eaf01564a1dc>)(erlang-xref-location (xref-file-location) ((arity :type fixnum :initarg :arity :reader erlang-xref-location-arity)) (:documentation "An erlang location is a file location plus arity."))
  apply(#f(compiled-function (cname superclasses slots options) "Define CNAME as a new subclass of SUPERCLASSES.\nSLOTS are the slots residing in that class definition, and OPTIONS\nholds the class options.\nSee `defclass' for more information." #<bytecode -0x9e5eaf01564a1dc>) (erlang-xref-location (xref-file-location) ((arity :type fixnum :initarg :arity :reader erlang-xref-location-arity)) (:documentation "An erlang location is a file location plus arity.")))
  eieio-defclass-internal(erlang-xref-location (xref-file-location) ((arity :type fixnum :initarg :arity :reader erlang-xref-location-arity)) (:documentation "An erlang location is a file location plus arity."))
  (progn (defalias 'erlang-xref-location-p (eieio-make-class-predicate 'erlang-xref-location)) (defalias 'erlang-xref-location--eieio-childp (eieio-make-child-predicate 'erlang-xref-location)) (defalias 'erlang-xref-location-child-p #'erlang-xref-location--eieio-childp) (make-obsolete 'erlang-xref-location-child-p "use (cl-typep ... \\='erlang-xref-location) instead" "25.1") (define-symbol-prop 'erlang-xref-location 'cl-deftype-satisfies #'erlang-xref-location--eieio-childp) (eieio-defclass-internal 'erlang-xref-location '(xref-file-location) '((arity :type fixnum :initarg :arity :reader erlang-xref-location-arity)) '(:documentation "An erlang location is a file location plus arity.")) (cl-defmethod erlang-xref-location-arity ((this erlang-xref-location)) "Access the slot `arity' from object of class `erla..." (slot-value this 'arity)) (defun erlang-xref-location (&rest slots) "Create a new object of class type `erlang-xref-loc..." (declare (compiler-macro (lambda (whole) (if (not (stringp ...)) whole (macroexp-warn-and-return (format "Obsolete name arg %S to constructor %S" ... ...) `...))))) (apply #'make-instance 'erlang-xref-location slots)))
  (defclass erlang-xref-location (xref-file-location) ((arity :type fixnum :initarg :arity :reader erlang-xref-location-arity)) :documentation "An erlang location is a file location plus arity.")
  (progn (cl-defmethod xref-backend-identifier-at-point ((_backend (eql erlang-etags))) (if (eq this-command 'xref-find-references) (if (use-region-p) (buffer-substring-no-properties (region-beginning) (region-end)) (thing-at-point 'symbol)) (erlang-id-to-string (erlang-get-identifier-at-point)))) (cl-defmethod xref-backend-definitions ((_backend (eql erlang-etags)) identifier) (erlang-xref-find-definitions identifier)) (cl-defmethod xref-backend-apropos ((_backend (eql erlang-etags)) identifier) (erlang-xref-find-definitions identifier t)) (cl-defmethod xref-backend-identifier-completion-table ((_backend (eql erlang-etags))) (let ((erlang-replace-etags-tags-completion-table t)) (tags-completion-table))) (defclass erlang-xref-location (xref-file-location) ((arity :type fixnum :initarg :arity :reader erlang-xref-location-arity)) :documentation "An erlang location is a file location plus arity.") (cl-defmethod xref-location-marker ((locus erlang-xref-location)) (cl-call-next-method locus)))
  eval((progn (cl-defmethod xref-backend-identifier-at-point ((_backend (eql erlang-etags))) (if (eq this-command 'xref-find-references) (if (use-region-p) (buffer-substring-no-properties (region-beginning) (region-end)) (thing-at-point 'symbol)) (erlang-id-to-string (erlang-get-identifier-at-point)))) (cl-defmethod xref-backend-definitions ((_backend (eql erlang-etags)) identifier) (erlang-xref-find-definitions identifier)) (cl-defmethod xref-backend-apropos ((_backend (eql erlang-etags)) identifier) (erlang-xref-find-definitions identifier t)) (cl-defmethod xref-backend-identifier-completion-table ((_backend (eql erlang-etags))) (let ((erlang-replace-etags-tags-completion-table t)) (tags-completion-table))) (defclass erlang-xref-location (xref-file-location) ((arity :type fixnum :initarg :arity :reader erlang-xref-location-arity)) :documentation "An erlang location is a file location plus arity.") (cl-defmethod xref-location-marker ((locus erlang-xref-location)) (cl-call-next-method locus))))
  byte-code("\300\301!\203\34\0\300\302!\203\34\0\300\303!\203\34\0\300\304!\203\34\0\305\306!\210\300\207" [erlang-soft-require xref cl-generic eieio etags eval (progn (cl-defmethod xref-backend-identifier-at-point ((_backend (eql erlang-etags))) (if (eq this-command 'xref-find-references) (if (use-region-p) (buffer-substring-no-properties (region-beginning) (region-end)) (thing-at-point 'symbol)) (erlang-id-to-string (erlang-get-identifier-at-point)))) (cl-defmethod xref-backend-definitions ((_backend (eql erlang-etags)) identifier) (erlang-xref-find-definitions identifier)) (cl-defmethod xref-backend-apropos ((_backend (eql erlang-etags)) identifier) (erlang-xref-find-definitions identifier t)) (cl-defmethod xref-backend-identifier-completion-table ((_backend (eql erlang-etags))) (let ((erlang-replace-etags-tags-completion-table t)) (tags-completion-table))) (defclass erlang-xref-location (xref-file-location) ((arity :type fixnum :initarg :arity :reader erlang-xref-location-arity)) :documentation "An erlang location is a file location plus arity.") (cl-defmethod xref-location-marker ((locus erlang-xref-location)) (cl-call-next-method locus)))] 2)
  autoload-do-load((autoload "erlang" ("/home/oper/.emacs.d/.local/autoloads.28.0.91.elc" . 666560) t nil) erlang-mode)
  command-execute(erlang-mode record)
  execute-extended-command(nil "erlang-mode" #("erla" 0 4 (ws-butler-chg chg)))
  #<subr funcall-interactively>(execute-extended-command nil "erlang-mode" #("erla" 0 4 (ws-butler-chg chg)))
  apply(#<subr funcall-interactively> (execute-extended-command nil "erlang-mode" #("erla" 0 4 (ws-butler-chg chg))))
  funcall-interactively(execute-extended-command nil "erlang-mode" #("erla" 0 4 (ws-butler-chg chg)))
  #<subr call-interactively>(execute-extended-command nil nil)
  apply(#<subr call-interactively> (execute-extended-command nil nil))
  explain-pause--wrap-call-interactively(#<subr call-interactively> execute-extended-command nil nil)
  apply(explain-pause--wrap-call-interactively #<subr call-interactively> (execute-extended-command nil nil))
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
`

**Comment by gagbo** [comment]
It seems the issue is that erlang package needs a bump for emacs versions that bundle the breaking change for xref <https://github.com/erlang/otp/commit/22a7522ef3f0f3c13618214e61f60cb01d80eef4>

**Comment by gagbo** [comment]
Oh but the pin is more recent, my bad it shouldn't happen then

**Comment by heiheshang** [comment]
> It seems the issue is that erlang package needs a bump for emacs versions that bundle the breaking change for xref [erlang/otp@22a7522](https://github.com/erlang/otp/commit/22a7522ef3f0f3c13618214e61f60cb01d80eef4)

when you bump ?

**Comment by heiheshang** [comment]
I tried but it doesn't help
