### ISSUE TITLE
describe-function fails with `(wrong-number-of-arguments (1 . 1) 2)`

### ISSUE THREAD

**Issue by rhaps0dy** [hlissner/doom-emacs#6097]
### What did you expect to happen?

`M-x describe-function` and then selecting e.g. `doom/describe-autodefs` should give me the function description.

### What actually happened?

Instead, I got error `(wrong-number-of-arguments (1 . 1) 2)`. Here is the backtrace:

```
Debugger entered--Lisp error: (wrong-number-of-arguments (1 . 1) 2)
  help-fns--autoloaded-p(doom/describe-autodefs "/home/adria/.emacs.d/core/autoload/help.el")
  helpful--autoloaded-p(doom/describe-autodefs #<buffer help.el>)
  helpful--summary(doom/describe-autodefs t #<buffer help.el> nil)
  #f(compiled-function () (interactive nil) #<bytecode -0x7ae2061dd3712e2>)()
  apply(#f(compiled-function () (interactive nil) #<bytecode -0x7ae2061dd3712e2>) nil)
  helpful-update()
  helpful--update-and-switch-buffer(doom/describe-autodefs t)
  helpful-callable(doom/describe-autodefs)
  funcall-interactively(helpful-callable doom/describe-autodefs)
  call-interactively(helpful-callable nil nil)
  command-execute(helpful-callable)
```
Here is another backtrace if using `ivy` instead of the default `vertico` (like I did prior to trying a clean Doom install).
```
Debugger entered--Lisp error: (wrong-number-of-arguments (1 . 1) 2)
  help-fns--autoloaded-p(doom/describe-autodefs "/home/adria/.emacs.d/core/autoload/help.el")
  helpful--autoloaded-p(doom/describe-autodefs #<buffer help.el>)
  helpful--summary(doom/describe-autodefs t #<buffer help.el> nil)
  #f(compiled-function () (interactive nil) #<bytecode -0x21dbf1ec9e492e2>)()
  apply(#f(compiled-function () (interactive nil) #<bytecode -0x21dbf1ec9e492e2>) nil)
  helpful-update()
  helpful--update-and-switch-buffer(doom/describe-autodefs t)
  helpful-callable(doom/describe-autodefs)
  #f(compiled-function (x) #<bytecode -0x14219e71788b1a4e>)("doom/describe-autodefs")
  ivy-call()
  ivy-read("Describe function: " [evil-collection-magit-toggle-text-minor-mode magit-section-show-headings AND soap-xs-complex-type-is-group--cmacro make-rxt-char-category 0 bibtex-entry-right-delimiter make-mode-line-mouse-map python-nav-beginning-of-defun-regexp Reduce\ To:\ to\ Cc: ert-test-passed-duration--cmacro magit-revision-filter-files-on-follow amx-rebuild-cache yas-x-prompt bib-item-no &error org-journal-re-encrypt-journals magit-xref-insert-button consult--grep racket-insert-closing-bracket evil-collection-org-maps helm-show-kill-ring message-expand-name-databases transient:magit-diff-refresh:--irreversible-delete org-journal--open-entry cpp-parse-symbols traversed magit-list-modified-modules :where citeproc-blt--parse-date EXPLAIN gdb-thread-number :mac org-table-get-range citeproc-locale-getter-from-dir About allout-post-undo-hook traversing\ a\ directory python-skeleton-available xesam-engine pages-directory-mode-hook emacs-lock--set-mode ibuffer-delete-alist org-man-center-block org-get-org-file isearch-case-fold-search-state Info-breadcrumbs transient:magit-log:--dense bibtex-text-in-string puny-encode-digit ...] :predicate #f(compiled-function (sym) #<bytecode -0x1350e734efe37042>) :require-match t :history counsel-describe-symbol-history :keymap (keymap (67108908 . counsel--info-lookup-symbol) (67108910 . counsel-find-symbol)) :preselect "Open" :action #f(compiled-function (x) #<bytecode -0x14219e71788b1a4e>) :caller counsel-describe-function)
  counsel-describe-function()
  funcall-interactively(counsel-describe-function)
  call-interactively(counsel-describe-function nil nil)
  command-execute(counsel-describe-function)
```

### Describe your attempts to resolve the issue

I tried removing my `/.doom.d` and  `~/.emacs.d` and reinstalling Doom without modifying the config. The issue persists. It seems that `describe-variable` works fine.

One potential issue is I'm on Emacs 29.0.50, a commit from a couple days ago.

### Steps to reproduce

1. Update Doom to latest `master`, at the time of writing `7e6baca99da64922e70ba64cba9707dd84ac20bf`.
2. Optionally: run `mv ~/.doom.d ~/.doom.d.bak` and `doom install`.
3. `doom sync -u`
4. Open Emacs
5. Run `M-x describe-function` and select almost any function.

### System Information

https://pastebin.com/VYYMbKG5

**Comment by hlissner** [comment]
This is likely an Emacs 29 issue (with helpful), and should be reported [upstream](https://github.com/Wilfred/helpful). 

Quite a few have been popping up (like https://github.com/hlissner/doom-emacs/issues/6063). I recommend avoiding the latest commit.

I'll leave this open until it's addressed upstream.

**Comment by hlissner** [comment]
As of https://github.com/hlissner/doom-emacs/commit/2a7eee556fb4af0ed8cfc9daf2bc6c78348ae8ca this issue should be (temporarily) resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by rhaps0dy** [comment]
Hey @hlissner , a fix for this has been merged upstream https://github.com/Wilfred/helpful .

It should directly check whether `helpful--autoloaded-p` takes one or two arguments, without relying on Emacs versions, so it should solve #6127 too.

**Comment by hlissner** [comment]
I've bumped helpful in b57d4c8, which should resolve the issue. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
