### ISSUE TITLE
Jump by Org-Mode ID is not record by history properly

### ISSUE THREAD

**Issue by ZhiruiLi** [hlissner/doom-emacs#6098]
### What did you expect to happen?

When jumping between org files by ID, the jump history is not record properly, which cause pressing ctrl-o can't jump backwards to previous location. For example, if we have two org files A and B:

File A:

```
:PROPERTIES:
:ID:       33e0ba64-2ba5-4207-8f16-ab4721ce397a
:END:
* This is FileA
```

File B:

```
* This is File B
[[id:33e0ba64-2ba5-4207-8f16-ab4721ce397a][To File A]]
```

When we press enter on "To File A" link in File B, the buffer will switch to File A, now press ctrl-o, the buffer will not switch back to File B.

But, for links like `[[file:./filea.org][To File A]]`, it seems the jumpping works fine.

### What actually happened?

The cursor will point to previous location before File B.

### Steps to reproduce

- Create two org files A and B like previous
- Open File B
- Click link and jump by ID
- Press ctrl-o to jump back

### System Information

https://pastebin.com/3WjCJK1k

**Comment by hlissner** [comment]
I can reproduce this. Looks like I need to revisit what hooks to set jump points on. Throw this into `$DOOMDIR/config.el` and see if the issue goes away:

```elisp
(after! org
  (remove-hook 'org-open-at-point-functions #'doom-set-jump-h)
  (add-hook 'org-follow-link-hook #'doom-set-jump-h)
  (advice-add #'org-mark-ring-push :after #'doom-set-jump-a))
```

**Comment by hlissner** [comment]
Actually, this may offer better coverage of the various link types:

```elisp
(after! org
  (advice-add #'org-link-open :around #'doom-set-jump-maybe-a))
```

**Comment by hlissner** [comment]
Alright, I'll work this into the `:lang org` module. I'll leave this open until I've addressed it.
