### ISSUE TITLE
Breaking change in consult

### ISSUE THREAD

**Issue by gagbo** [hlissner/doom-emacs#6099]
### What package(s) should be bumped?

None for now, I use this as a sticky notice @iyefrat 

https://github.com/minad/consult/commit/2106eee75f84206715631da45eae08827da266f9 removed obsolete variables and I think it breaks there https://github.com/hlissner/doom-emacs/blob/519c54ded68717277092c12de965914ba1e8d8c2/modules/completion/vertico/config.el#L135

**Comment by gagbo** [comment]
Indeed renaming those variables fixes this

**Comment by hlissner** [comment]
Thanks for letting me know! Will fix (and bump the module) soon.

**Comment by hlissner** [comment]
Bumped and fixed in 394f7be.
