### ISSUE TITLE
Discussion: the location of org-clock-save.el file

### ISSUE THREAD

**Issue by liujoey** [hlissner/doom-emacs#610]
Hello @hlissner,

The `~/.emacs.d/` folder always showing the untracked file `org-clock-save.el` sometimes get annoying, would it be ok to move it to `~/.emacs.d/.local/`?

In the org config file it sets:
```elisp
  (setq org-clock-persist 'history
        org-clock-persist-file (concat doom-etc-dir "org-clock-save.el"))
```

by the way, I remember a recent commit you had changed this type of naive concatenation of file path, maybe here is also a place we should change the use of `concat`? Thank you.

Best regards
Joey

**Comment by hlissner** [comment]
This confuses me. The lang/org module configures `org-clock` to put its cache in `~/.emacs.d/.local/etc`. This should prevent `~/.emacs.d/org-clock-save.el` from appearing. Is this not the case?

> naive concatenation of file path

I am selective about which paths I use `expand-file-name` (smart concatenation) and `concat` (naive) on, mostly out of minor (possibly premature) concerns for performance. I choose `concat` on paths I'm certain end in a slash, and I am certain `doom-etc-dir` will. It is built using `doom-emacs-dir`, which is an alias for `user-emacs-directory`, which requires that it end with a slash.

`doom-private-dir`, however, can be changed depending on the value of the XDG_CONFIG_HOME envvar; or may be customized by the user, thus naive concatenation can be a big gamble.

That said, this philosophy may not hold up to expanding Windows support for Doom. Time will tell.

**Comment by liujoey** [comment]
My bad, I have a lot of org configuration and I some how forgot I had a setting shadowed your code, you are right, the doom put the file under .local/etc/. Closing this.
