### ISSUE TITLE
Make the title bar black

### ISSUE THREAD

**Issue by ZeRealStig** [hlissner/doom-emacs#6110]
### Describe your request

I’d like Doom to have a dark title bar on Windows

Most apps nowadays have customisable titlebars that can follow system preferences 

But (Doom)Emacs  still shows a white title bar on Windows
 (Pretty sure this is a general  Emacs issue  and not related to Doom Emacs…)

So it would be great if Doom Emacs provided a setting to hide the title bar / **not** use the system APIs for this

### Briefly explain its use-case

No more ugly white title bar on Windows

**Comment by hlissner** [comment]
This is not something Doom has any control over (on Windows, at least). You'll have to request this of Emacs upstream. 

As this is not a Doom issue I will close this.
