### ISSUE TITLE
User' set evil-collection-key-blacklist isn't respected

### ISSUE THREAD

**Issue by daanturo** [hlissner/doom-emacs#6119]
### What did you expect to happen?

Set `evil-collection-key-blacklist` in init.el (to be sure, because Doom initialize `evil` before loading `config.el`).

It is respected.

### What actually happened?

Keys in set `evil-collection-key-blacklist` is bound by `evil-collection` anyway.

### Describe your attempts to resolve the issue

Advise `evil-collection-init` and set the variable before as a workaround.

### Steps to reproduce

1. In `init.el`: `(setq evil-collection-key-blacklist '("n"))`
2. `magit-status`
3. Press `n`, expected `magit-section-forward` but got `evil-ex-search-next` instead.

### System Information

https://pastebin.com/Sdp4P1h9

**Comment by hlissner** [comment]
Did you wrap your custom `(setq evil-collection-key-blacklist ...)` in `(after! evil-collection ...)`?

**Comment by daanturo** [comment]
Yes, I have tried
```lisp
(after! evil-collection
  (setq evil-collection-key-blacklist (append (bound-and-true-p evil-collection-key-blacklist)
                                              '("n" "p"))))
```

Checking `evil-collection-key-blacklist` later gives `("SPC" "," "M-SPC" "gd" "gf" "K" "gr" "gR" "[" "]" "gz" "<escape>")`.
