### ISSUE TITLE
Font color mixing with background

### ISSUE THREAD

**Issue by manffredd** [hlissner/doom-emacs#6124]
### What did you expect to happen?

Just installed Doom Emacs on Mac OS 12.2:

Right after starting emacs I should be able to see the main starting page with the DOOM logo.

### What actually happened?

Instead of seeing the logo, it appears that the font color is mixing with the background. Only when the text is highlighted with the cursor appears visible. Even when typing (e.g. Spc-. ) to find a file, text is blind.

However, it works perfect with other terminal emulators
<img width="1440" alt="Screen Shot 2022-02-17 at 11 28 53 PM" src="https://user-images.githubusercontent.com/85195995/154573890-ad511b67-e600-4879-9386-267c2238dfd9.png">
<img width="1440" alt="Screen Shot 2022-02-17 at 11 29 10 PM" src="https://user-images.githubusercontent.com/85195995/154573903-32a2123d-28af-4c0c-a84a-0d77bfbc558e.png">

### Describe your attempts to resolve the issue

Toggled themes between doom-one, doom-one-light, etc.... no change.

Doom Emacs seems to work well on the native Terminal for Mac OS
<img width="1440" alt="Screen Shot 2022-02-17 at 11 27 18 PM" src="https://user-images.githubusercontent.com/85195995/154573642-5b5c2a39-8283-40de-90e4-cf12c12121e2.png">
.

### Steps to reproduce

1. Open any terminal Emulator
2. run "emacs"

### System Information

https://pastebin.com/v1iCwDzV

**Comment by hlissner** [comment]
This occurs because alacritty supports 24-bit color, but Emacs has only partial 24-bit support without some help. Visit [this guide](https://github.com/syl20bnr/spacemacs/wiki/Terminal) for details on how to fix it.

As this is a terminal issue, rather than Doom or Emacs, I will close this, but feel free to follow up here.

**Comment by manffredd** [comment]
FYI, a super quick solution is to just to modify alacritty.yml file to the following elements:

`env:`
`     TERM: alacritty-direct`

This will enable 24-bit color support.
