### ISSUE TITLE
Wrong type argument: plistp

### ISSUE THREAD

**Issue by Evilhotdog** [hlissner/doom-emacs#6129]
### What did you expect to happen?

When I type :q, C-x C-c, etc, the program should quit. 

### What actually happened?

When attempting to exit, sometimes (more often if the program has been running for longer), the program gives the following message both in the bottom panel and the *Messages* buffer

![image](https://user-images.githubusercontent.com/44662495/154744709-953b56d1-4396-4f4c-80eb-8a97d1e206fa.png)

Debug backtrace:

![image](https://user-images.githubusercontent.com/44662495/154744901-aa93f144-a6ea-40b7-a255-78cd53988202.png)

### Describe your attempts to resolve the issue

When launching emacs from a terminal, I attempted to close it with CTRL+C, which resulted in the same error displaying. Attempting 'killall emacs' produces the same error the first time, but running it a second time kills it. 

### Steps to reproduce

1. Open Emacs
2. Leave it for a few minutes
3. Attempt to close it with :q or C-x C-c
4. An error is logged

### System Information

https://pastebin.com/J5Bbw4ZN

**Comment by hlissner** [comment]
I can't reproduce this. This seems like your local org-persist cache got corrupted. Delete `~/.cache/org-persist/`, restart Emacs, and see if the issue goes away.

Otherwise, this is more likely an upstream bug and not a Doom issue. Can you reproduce it in [vanilla Doom](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#testing-in-dooms-sandbox)?

**Comment by Evilhotdog** [comment]
I couldn't reproduce it in Vanilla Doom, but I could reproduce it with Doom + Modules - My config. I've also wiped my config and started from the default one that's generated by ./doom install, but that didn't work. I also can't reproduce it in vanilla GNU Emacs.

**Comment by hlissner** [comment]
Have you tried deleting `~/.cache/org-persist`?

**Comment by Evilhotdog** [comment]
This seems to have worked! Thank you!
