### ISSUE TITLE
DPI settings are not respected by "setq doom-font"

### ISSUE THREAD

**Issue by arg** [hlissner/doom-emacs#6131]
### What did you expect to happen?

I have `Xft.dpi` set to `163` on a 27 inch screen. With it I can set font size to 13 in GTK, Firefox, Alacritty and other apps and they all will look consistent and quite readable to my impaired eyes. This also works with vanilla Emacs 27, where I can add
```elisp
(set-frame-font "Hack Nerd Font-13")
```
to `init.el`. I expected the same behavior using `setq doom-font` instead of `set-frame-font` but it didn't work.

### What actually happened?

Adding
```elisp
(setq doom-font (font-spec :family "Hack Nerd Font" :size 13))
```
to `config.el` makes text look roughly two times smaller than expected with my DPI settings.

### Describe your attempts to resolve the issue

I can use 
```elisp
(set-frame-font "Hack Nerd Font-13")
```
in Doom Emacs as well, but would be great if `setq doom-font` also respect DPI settings.

### Steps to reproduce

On Arch Linux or FreeBSD 13 (I'm sure other OSes are affected too, but these two I can test on):

1. Add
   ```elisp
   (setq doom-font (font-spec :family "Hack Nerd Font" :size 13))
   ```
   to Doom's `config.el`
2. Add
   ```
   Xft.dpi: 163
   ```
   to `~/.Xresources`
3. Restart Xorg
4. Run Emacs

Actual result: texts look visually two times smaller then in any other app:

![2022-02-19-101116_3840x2160_scrot-min](https://user-images.githubusercontent.com/1044277/154794619-f1b87054-e375-43bb-90d3-47bfa75248bc.png)

### System Information

https://pastebin.com/GLafGbC8

**Comment by hlissner** [comment]
I don't have a HiDPI display to test on, so please test the following alternative to `set-frame-font` and `doom-font`:

```lisp
(add-to-list 'default-frame-alist '(font . "Hack Nerd Font-13"))
```

**Comment by arg** [comment]
> I don't have a HiDPI display to test on, so please test to see if this respects the DPI (i.e. remove `set-frame-font` and `doom-font`):
> 
> ```lisp
> (add-to-list 'default-frame-alist '(font . "Hack Nerd Font-13"))
> ```

Looks fine now

![2022-02-19-142659_3840x2160_scrot-min](https://user-images.githubusercontent.com/1044277/154802798-c48518b7-817a-4b9a-84fc-99d189060d77.png)

But it seems to be mostly the same as calling `set-frame-font` (which also works fine) as per https://www.emacswiki.org/emacs/SetFonts

**Comment by hlissner** [comment]
How about:

```lisp
(add-to-list 'default-frame-alist `(font . ,(font-xlfd-name doom-font)))
```

**Comment by hlissner** [comment]
Could you also try:

```elisp
(setq doom-font (font-spec :family "Hack Nerd Font" :size 13 :dpi 163))
```

**Comment by arg** [comment]
```elisp
(add-to-list 'default-frame-alist
             `(font . ,(font-xlfd-name (font-spec :family "Hack Nerd Font" :size 13))))
```
```elisp
(setq doom-font (font-spec :family "Hack Nerd Font" :size 13 :dpi 163))
```

Tried both commands, fonts are still two times smaller than they should.

![2022-02-19-212610_3840x2160_scrot-min](https://user-images.githubusercontent.com/1044277/154817915-6ae0461c-769a-458a-8b40-d3a14b50a3d4.png)

**Comment by hlissner** [comment]
I expected them to. That explains the problem. It appears that some information is lost when converting a font-spec to an xlfd string (which `set-frame-font` or using an xft string `Hack Nerd Font-13` do not do).

Try throwing [this](https://gist.github.com/hlissner/d498ce792958c6483fcbbdcaf0b5ef3a) into your config.el (and removing all my previous snippets) and see if it works. If it does, I'll replace our font initializing logic with it.

**Comment by arg** [comment]
@hlissner I added the code you suggested, here are the results:

<details>
<summary>Only override function, just to test what happens if I don't specify font settings at all</summary>

![2022-02-20-214333_3840x2160_scrot-min](https://user-images.githubusercontent.com/1044277/154864024-5e78ca91-7950-4b99-9a32-3d92f34c8f37.png)
</details>

<details>
<summary>With setq doom-font, text is too small</summary>

![2022-02-20-214402_3840x2160_scrot-min](https://user-images.githubusercontent.com/1044277/154864078-ae0301cb-ced6-40ad-87a2-1ed41f90a8d8.png)
</details>

<details>
<summary>With setq doom-font + specified DPI, text looks bigger but still not the right size</summary>

![2022-02-20-214509_3840x2160_scrot-min](https://user-images.githubusercontent.com/1044277/154864126-d081c119-2df1-4d5b-948f-8b4f55b1ead9.png)
</details>

<details>
<summary>With add-to-list 'default-frame-alist, looks perfect!</summary>

```elisp
(add-to-list 'default-frame-alist '(font . "Hack Nerd Font-13"))
```

![2022-02-20-214847_3840x2160_scrot-min](https://user-images.githubusercontent.com/1044277/154864132-775adad3-6f5e-405e-a532-e9baec419179.png)
</details>

I also tried 

```elisp
(add-to-list 'default-frame-alist
             `(font . ,(font-xlfd-name (font-spec :family "Hack Nerd Font" :size 13))))
```
but it didn't have any effect. However having

```elisp
(add-to-list 'default-frame-alist '(font . "Hack Nerd Font-13"))
```
in `config.el` + improved `doom--make-font-specs` function fixes the issue.

**Comment by schemar** [comment]
I have an issue where the following only sets the font family of the variable pitch font, but neither size nor weight are applied:
```
(setq doom-font "MonoLisa-11"
      doom-variable-pitch-font (font-spec :family "Roboto" :size 13.0 :weight 'light))
```

@hlissner: I can confirm that copying the code from your [previous comment](https://github.com/hlissner/doom-emacs/issues/6131#issuecomment-1046126600) to my `config.el` fixes the issue.

Thank you so much for the quick support.

**Comment by hlissner** [comment]
> @hlissner: I can confirm that copying the code from your https://github.com/hlissner/doom-emacs/issues/6131#issuecomment-1046126600 to my config.el fixes the weight, but not the size of doom-variable-pitch-font. (Using "Roboto-12" instead also doesn't set the correct size.)

This is an unrelated issue. Modes like variable-pitch-mode and mixed-pitch-mode (and other things like text-scaling) can apply their own hard-coded size to the text they affect, thus overriding `doom-variable-pitch-font`.

**Comment by hlissner** [comment]
> With setq doom-font, text is too small

Try this then:

```elisp
(setq doom-font (font-spec :family "Hack Nerd Font" :size 13.0))
```

**Comment by arg** [comment]
> > With setq doom-font, text is too small
> 
> @arg Try this then:
> 
> ```emacs-lisp
> (setq doom-font (font-spec :family "Hack Nerd Font" :size 13.0))
> ```

This works, writing `size` as a float makes fonts consistent. Also no need to override `doom--make-font-specs`.

**Comment by harabat** [comment]
Had the same issue after switching to Emacs 28.1, and the solution worked.  

Would it make sense to adapt the text in config.el by replacing the size integers with floats?

```elisp
;; They all accept either a font-spec, font string ("Input Mono-12"), or xlfd
;; font string. You generally only need these two:
-;; (setq doom-font (font-spec :family "monospace" :size 12 :weight 'semi-light)
-;;       doom-variable-pitch-font (font-spec :family "sans" :size 13))
+;; (setq doom-font (font-spec :family "monospace" :size 12.0 :weight 'semi-light)
+;;       doom-variable-pitch-font (font-spec :family "sans" :size 13.0))
```

**Comment by hlissner** [comment]
Prompted by #6316, I'm looking for ways to my our font initialization more robust (and respectful of more nuanced settings in `doom-font` et co). Could someone give this code a try?

https://gist.github.com/hlissner/adbae9ae52db1e200777bf08d3d61d0d

And see if it interferes with DPI, :weight, :slant, or :width on the various fonts?

**Comment by t-e-r-m** [comment]
> Prompted by #6316, I'm looking for ways to my our font initialization more robust (and respectful of more nuanced settings in `doom-font` et co). Could someone give this code a try?
> 
> [gist.github.com/hlissner/adbae9ae52db1e200777bf08d3d61d0d](https://gist.github.com/hlissner/adbae9ae52db1e200777bf08d3d61d0d)
> 
> And see if it interferes with DPI, :weight, :slant, or :width on the various fonts?

I tried it out.  It worked well for me, font properties were respected.  I don't have a High DPI screen, though.

**Comment by hlissner** [comment]
This issue should now be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by ncihnegn** [comment]
Still having this issue on Gnome.

**Comment by hlissner** [comment]
@ncihnegn Use a float for the `:size`.

```elisp
(setq doom-font (font-spec :family "Some Font" :size 16.0))
```

An integer is interpreted as pixel size. A float is interpreted as point size, which should respect DPI.
