### ISSUE TITLE
relative line numbers

### ISSUE THREAD

**Issue by andrej1919** [hlissner/doom-emacs#6158]
### What did you expect to happen?

Comming from Vim I am used to relative line numbers. Instruction in `config.el`:

;; This determines the style of line numbers in effect. If set to `nil', line
;; numbers are disabled. For relative line numbers, set this to `relative'.
(setq display-line-numbers-type t)

### What actually happened?

While `t`and `nil`work fine, `relative`throws an error:
```
Warning (initialization): An error occurred while loading ‘/Users/h1/.emacs.d/init.el’:

Error in private config: config.el, (void-variable relative)
```

### Describe your attempts to resolve the issue

I tried all three options (t, nil, relative), just relative fails.

### Steps to reproduce

1. In `config.el` change `(setq display-line-numbers-type t)` to `(setq display-line-numbers-type relative)`
2. Close Emacs and run `doom sync`
3. Open Emacs
 

### System Information

https://pastebin.com/sDdpeNJX

**Comment by RBckmnn** [comment]
You have to use

`(setq display-line-numbers-type 'relative)`

**Comment by andrej1919** [comment]
Than you!
