### ISSUE TITLE
Document +lsp switch in the ocaml module

### ISSUE THREAD

**Issue by sarna** [hlissner/doom-emacs#6159]
### Describe your request

The `ocaml` module supports the `+lsp` flag but it's not documented what it does - in fact, it's not even mentioned in the README: https://github.com/hlissner/doom-emacs/blob/master/modules/lang/ocaml/README.org

I'm not sure what it exactly does myself, besides that after setting it and installing `ocaml-lsp-server` the mode works *much* better. It would be great if somebody competent wrote a sentence or two in the README.

### Briefly explain its use-case

1. Want to use Doom Emacs for writing OCaml
2. Look up docs for the `ocaml` module
3. Notice that its `+lsp` flag is beautifully documented
4. Set it in the config, run `opam install ocaml-lsp-server`
5. Enjoy the epic OCaml Emacs Experience™️

**Comment by hlissner** [comment]
Already done [on the `rewrite-docs` branch](https://github.com/hlissner/doom-emacs/blob/rewrite-docs/modules/lang/ocaml/README.org#module-flags), so I'll close this. The branch will be merged sometime in the next few weeks.

**Comment by sarna** [comment]
@hlissner just a heads up: while it's good that it lets you know this flag exists, it links to the wrong thing.
It links to: https://github.com/freebroccolo/ocaml-language-server (which now 404s)
And it should link to: https://github.com/ocaml/ocaml-lsp
