### ISSUE TITLE
Function git-link--remote-host was removed from git-link

### ISSUE THREAD

**Issue by ppwwyyxx** [hlissner/doom-emacs#616]
https://github.com/hlissner/doom-emacs/blob/1aec48a84833d5fe0c5bdd2b2bf9d17c4caf7c8f/modules/feature/version-control/autoload.el#L4-L12

The function `git-link--remote-host` was removed in `git-link` 0.6

**Comment by hlissner** [comment]
This should be fixed as of dc86b61. Thanks for letting me know!

I'll keep this open until it hits `master`.
