### ISSUE TITLE
Code completion not working in Spring Boot application .properties file.

### ISSUE THREAD

**Issue by svnwell** [hlissner/doom-emacs#6162]
### What did you expect to happen?

Suport validation and code completion for spring .properties and .yml file.

### What actually happened?

According to [lsp-java readme](https://github.com/emacs-lsp/lsp-java#functionality-for-properties-and-yml), lsp-java support code completion for .properties and .yml file, but not worked in doom.

### Describe your attempts to resolve the issue

Install jsts-ls and add the following configuration:

```lisp
(use-package! lsp-java-boot
  :after lsp-mode
  :preface
  (add-hook! 'conf-javaprop-mode-hook #'lsp)
  (add-hook! 'lsp-mode-hook #'lsp-lens-mode)
  (add-hook! 'java-mode-hook #'lsp-java-boot-lens-mode))
```

[lsp-java .properties and .yml](https://github.com/emacs-lsp/lsp-java#functionality-for-properties-and-yml)
[Code completion not working in Spring Boot application.properties](https://github.com/emacs-lsp/lsp-java/issues/366#issue-1052921927)

### Steps to reproduce

1.  Module flag
     =+lsp=
2.  .envrc
```bash
export JAVA_HOME="/usr/lib/jvm/java-17-openjdk"
```
3. Install jdtls

Code completion worked well in .java file, but not in .properties and .yml.

### System Information

https://pastebin.com/XqJAb9Nb

**Comment by Suyashtnt** [comment]
The jsts-ls is for Javascript and typescript, not for java

**Comment by hlissner** [comment]
1. Run `doom env` to make sure Emacs can see your `JAVA_HOME` variable.
2. Your config is likely not loading lsp-java-boot soon enough. Use this instead:

   ```elisp
   (use-package! lsp-java-boot
     :after lsp-mode
     :preface
     (add-hook 'conf-javaprop-mode-local-vars-hook #'lsp!)
     (add-hook 'yaml-mode-local-vars-hook #'lsp!)
     :config
     (add-hook 'java-mode-local-vars-hook #'lsp-java-boot-lens-mode 'append)
     (add-hook 'yaml-mode-local-vars-hook #'lsp-java-boot-lens-mode 'append))
   ```

   (The `lsp-lens-mode` hook is unnecessary, lsp-mode does that for you so long as `lsp-lens-enable` is non-nil, which it is by default).
3. If that doesn't fix the issue, try unpinning `lsp-mode` and `lsp-java` by:
   1. Add `(unpin! lsp-mode lsp-java)` to `$DOOMDIR/packages.el`,
   2. Run `doom sync -u` in the shell,
   3. Restart Emacs.
4. If after that, it still doesn't work, then Doom is likely not the issue and this should be reported upstream.
