### ISSUE TITLE
No doom icons when running in WSL terminal

### ISSUE THREAD

**Issue by maacl** [hlissner/doom-emacs#6173]
### What did you expect to happen?

When I use latest Doom in WSL 2 in the **terminal** on Windows 11 I expected to see icons in the doom interface (e.g. github icon in the *doom* buffer). 

### What actually happened?

I don't see any icons. When I run GUI emacs (ie. without the -nw switch) the icons are there.

### Describe your attempts to resolve the issue

I have installed nerd fonts and all-the-icon fonts in both WSL and Windows.

### Steps to reproduce

Run Doom emacs in WSL 2 (Ubuntu 20.04) on Windows 11 with emacs -nw. 

### System Information

https://pastebin.com/qNqyaibD

**Comment by Diablo-D3** [comment]
Terminal programs cannot set their own font, and the modern concept of icon fonts did not exist in the 1970s and 1980s when the original VT series hardware terminals were made.

**Comment by maacl** [comment]
It works flawlessly on native Linux.

**Comment by maacl** [comment]
So my latest comment was blatantly wrong. My only excuse is that I misremembered. Sorry to waste peoples time. Closing.
