### ISSUE TITLE
Vote for intuitive evil-mc

### ISSUE THREAD

**Issue by Emiller88** [hlissner/doom-emacs#618]
Vote for the issue about evil-mc.

Currently, it requires `gzt` after making evil-mc cursors to start them. 

By adding this entering insert mode toggles the multiple cursors.

https://github.com/hlissner/doom-emacs-private/blob/master/config.el#L39

```elisp
;; feature/evil
(after! evil-mc
  ;; Make evil-mc resume its cursors when I switch to insert mode
  (add-hook! 'evil-mc-before-cursors-created
    (add-hook 'evil-insert-state-entry-hook #'evil-mc-resume-cursors nil t))
  (add-hook! 'evil-mc-after-cursors-deleted
(remove-hook 'evil-insert-state-entry-hook #'evil-mc-resume-cursors t)))
```
Vote Thumbs **down** to leave as is
Vote Thumbs **up** to impliment the feature

**Comment by hlissner** [comment]
I've incorporated this into `feature/evil`'s defaults, and in a way that's easy to disable:

```lisp
(remove-hook 'evil-insert-state-entry-hook #'+evil-mc|resume-cursors)
```

So I'll consider this resolved. Feel free to reopen if it gives you trouble!
