### ISSUE TITLE
Doom (Marginalia?) shows M-$ bound to two different functions.

### ISSUE THREAD

**Issue by holgerschurig** [hlissner/doom-emacs#6204]
### What did you expect to happen?

I expect that only correct keybindings appear in Dooms (Marginalia, Consults?) `M-x` display.

### What actually happened?

When I `M-x spell`, I see that both `ispell-word` and `+spell/correct` are bound to `M-$`.

Example of the image: https://imgur.com/a/WILpdIg

Clearly the displayed binding to `ispell-word` is wrong, as `C-k h M-$` reveals.

### Describe your attempts to resolve the issue

No idea how to resolve this. I didn't bind `M-$` personally, so I cannot say if it's a clash between general.el (used by Doom) or bind-key.el (used by use-package).

### Steps to reproduce

Just `M-x spell`, as written above.

### System Information

https://pastebin.com/vebWZQp5

**Comment by hlissner** [comment]
This is not a bug. Two commands can appear to be bound to the same key if either:

1. The same key is bound to the same command different keymaps (that are both active),
2. Or, as is commonly the case across Doom, one command is remapped to another, e.g.

   ```elisp
   (map! "C-;" #'do-one-thing
         [remap do-one-thing] #'do-another-thing)
   ```

   As far as `M-x` is concerned, `do-one-thing` and `do-another-thing` are now both bound to `C-;`, but typing `C-;` will only trigger `do-another-thing`. Doom using remapping quite liberally, as it causes fewer conflicts.
