### ISSUE TITLE
Can't set uniquify-buffer-name-style value

### ISSUE THREAD

**Issue by Ice-Cube69** [hlissner/doom-emacs#6205]
### What did you expect to happen?

For some reason, I am not able to set the value of uniquify-buffer-name-style. I have this in my config:
`(setq uniquify-buffer-name-style 'forward)`
I expected it to be set to forward when i start emacs

### What actually happened?

It's always set to nil initially.

### Describe your attempts to resolve the issue

I tried using the custom menu to set it to 'forward, but to no use. A current hack is to set it to 'forward manually

### Steps to reproduce

1. Open emacs
2. put (setq uniquify-buffer-name-style 'forward) in your config.el
3. restart emacs.
4. observe the value of setq uniquify-buffer-name-style.

### System Information

https://pastebin.com/7y5xKAwC

**Comment by Lythenas** [comment]
I think this might be because of persp-mode.I found this comment in `modules/ui/workspaces/config.el`

```elisp
             ;; `uniquify' breaks persp-mode. It renames old buffers, which causes
             ;; errors when switching between perspective (their buffers are
             ;; serialized by name and persp-mode expects them to have the same
             ;; name when restored).
```

`(remove-hook 'persp-mode-hook #'+workspaces-init-persp-mode-h)` might do what you want. But it might break something in persp-mode.

Also I think just deactivating `persp-mode` should reset the value back to your value if you don't need persp-mode.

**Comment by hlissner** [comment]
Not a bug. As Lythenas mentioned, setting `uniquify-buffer-name-style` to anything other than nil will cause subtle breakage with persp-mode (provided by the `:ui workspaces` module). Either disable that module or force the change and live with the issue:

```elisp
(setq-hook! 'persp-mode-hook uniquify-buffer-name-style 'forward)
```

**Comment by JohnsonLiu1988** [comment]
just complement hlissner's comment, the complete code snippet may follow like this.

(after! persp-mode
 (setq-hook! 'persp-mode-hook uniquify-buffer-name-style 'forward))

or else, it will be override by +workspaces-init-persp-mode-h.
