### ISSUE TITLE
Prevent asking "Create envvar file" in automated installation with flag option

### ISSUE THREAD

**Issue by ReneFroger** [hlissner/doom-emacs#6206]
### My issue

@hlissner 

I use a script for every new systems, which installs many packages. Among over many other things, it will also install Doom Emacs. It calls the doom binary with `doom install`. But this deploying script will get interrupted. Doom asks me if I want to create an envvar file, which I need to answer manually.

I think it's easily solvable with adding a flag to the binary.

### My request
Is it perhaps an option to use a flag like `/bin/doom --create-envvar install` or something like that? Like `sudo apt get -y install emacs` (which uses the `-y` flag before `install` to prevent asking for confirmation). 

So that Doom Emacs could be installed with lot of other packages inside a (bash) script, when a system gets a new Linux install.

**Comment by hlissner** [comment]
```
$ doom help
...
  Options:
    -h, --help
      Same as help command
    -y, --yes
      Auto-accept all confirmation prompts
    -d, --debug
      Enables on verbose output
    -l, --load FILE
      Load an elisp FILE before executing any commands
    --doomdir DIR
      Use the private module at DIR (e.g. ~/.doom.d)
    --localdir DIR
      Use DIR as your local storage directory
    -C, --nocolor
      Disable colored output
...
```

Notice `-y`/`--yes`. e.g. `doom -y install`

```
$ doom help install
...
  Options:
    --no-config
      Don't create DOOMDIR or dummy files therein
    --no-env
      Don't generate an envvars file (see 'doom help env')
    --no-install
      Don't auto-install packages
    --no-fonts
      Don't install (or prompt to install) all-the-icons fonts
    --no-hooks
      Don't deploy git hooks
```

Notice `--no-env`. e.g. `doom --no-env install`. You can call `doom env` afterwards if you want one generated.

**That said, I don't recommend you use `doom install` for this purpose.** It is not intended for headless installations and will become even _more_ interactive in future iterations. It will always be Doom's "first time installation wizard". 

`doom sync` is better suited to this purpose.

-----

In the future, please post support/how-to requests like these on our Discord. Our issue tracker is for issues.

**Comment by ReneFroger** [comment]
The `-y` flag was not mentioned in the `doom help install`. I checked it before asking here. But I'll try that flag then. Thanks for your response.
