### ISSUE TITLE
[REQUEST] Autoformat code based on major mode

### ISSUE THREAD

**Issue by beojan** [hlissner/doom-emacs#622]
A feature to autoformat code (e.g. under `SPC c f`) based on the major mode would be nice. That is, use `clang-format` for c++-mode, autopep8 for `python-mode`, etc.

**Comment by hlissner** [comment]
I intend to add this eventually; possibly by 2.1.2. My eye is on https://github.com/lassik/emacs-format-all-the-code. I'll let you know when there's movement on this matter.

**Comment by ar1a** [comment]
could use prettier for js and friends
https://github.com/prettier/prettier

**Comment by hlissner** [comment]
@ar1a The [emacs-format-all-the-code](https://github.com/lassik/emacs-format-all-the-code) plugin uses prettier for javascript et all.

**Comment by hlissner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Look into a universal "code formatting" solution](https://trello.com/c/T7Cq7fns/27-look-into-a-universal-code-formatting-solution)

**Comment by hlissner** [comment]
This is now in `develop`, as part of the new `:editor format` module. It's still experimental and needs more testing, but I'll consider this issue resolved.
