### ISSUE TITLE
Local path in "use-package!" block doesn't evaluate correctly on Org Src environment (org-edit-special)

### ISSUE THREAD

**Issue by alienbogart** [hlissner/doom-emacs#6241]
### What did you expect to happen?

This should evaluate correctly in a `Org Src` buffer:

``` emacs-lisp
(use-package! frame-cmds
  :load-path "/home/dave/Dropbox/dotfiles/emacs/doom.d/lisp/frame")
```

### What actually happened?

When I enter an Org Src environment with `M-x org-edit-special`, evaluating a block such as 

``` emacs-lisp
(use-package! frame-cmds
  :load-path "/home/dave/Dropbox/dotfiles/emacs/doom.d/lisp/frame")
```

doesn't work, giving the message: `Error (use-package): Failed to parse package frame-cmds: Cannot get this file-path`. Outside of the environment, it works fine.

<details>
<summary>This is the backtrace with `doom-debug-mode` on</summary>
Debugger entered--Lisp error: (error "Cannot get this file-path")
  signal(error ("Cannot get this file-path"))
  error("Cannot get this file-path")
  (cond ((and (boundp 'byte-compile-current-file) byte-compile-current-file)) (load-file-name) ((stringp (car-safe current-load-list)) (car current-load-list)) (buffer-file-name) ((error "Cannot get this file-path")))
  file!()
  (and t (file!))
  (let* ((path (and t (file!)))) (if path (directory-file-name (file-name-directory path)) nil))
  dir!()
  (if (stringp arg) (dir!))
  (let ((user-emacs-directory (if (stringp arg) (dir!)))) (funcall fn label arg recursed))
  doom--resolve-load-path-from-containg-file-a(#f(compiled-function (label arg &optional recursed) "Normalize a list of filesystem paths." #<bytecode 0x155b23dd8de9>) ":load-path" "/home/dave/Dropbox/dotfiles/emacs/doom.d/lisp/fram...")
  apply(doom--resolve-load-path-from-containg-file-a #f(compiled-function (label arg &optional recursed) "Normalize a list of filesystem paths." #<bytecode 0x155b23dd8de9>) (":load-path" "/home/dave/Dropbox/dotfiles/emacs/doom.d/lisp/fram..."))
  use-package-normalize-paths(":load-path" "/home/dave/Dropbox/dotfiles/emacs/doom.d/lisp/fram...")
  use-package-as-one(":load-path" ("/home/dave/Dropbox/dotfiles/emacs/doom.d/lisp/fram...") use-package-normalize-paths)
  use-package-normalize/:load-path(frame-cmds :load-path ("/home/dave/Dropbox/dotfiles/emacs/doom.d/lisp/fram..."))
  use-package-normalize-plist(frame-cmds (:load-path "/home/dave/Dropbox/dotfiles/emacs/doom.d/lisp/fram...") nil use-package-merge-keys)
  use-package-normalize-keywords(frame-cmds (:load-path "/home/dave/Dropbox/dotfiles/emacs/doom.d/lisp/fram..."))
  #f(compiled-function (name &rest args) "Declare an Emacs package by specifying a group of configuration options.\n\nFor full documentation, please see the README file that came with\nthis file.  Usage:\n\n  (use-package package-name\n     [:keyword [option]]...)\n\n:init            Code to run before PACKAGE-NAME has been loaded.\n:config          Code to run after PACKAGE-NAME has been loaded.  Note that\n                 if loading is deferred for any reason, this code does not\n                 execute until the lazy load has occurred.\n:preface         Code to be run before everything except `:disabled'; this\n                 can be used to define functions for use in `:if', or that\n                 should be seen by the byte-compiler.\n\n:mode            Form to be added to `auto-mode-alist'.\n:magic           Form to be added to `magic-mode-alist'.\n:magic-fallback  Form to be added to `magic-fallback-mode-alist'.\n:interpreter     Form to be added to `interpreter-mode-alist'.\n\n:commands        Define autoloads for commands that will be defined by the\n                 package.  This is useful if the package is being lazily\n                 loaded, and you wish to conditionally call functions in your\n                 `:init' block that are defined in the package.\n:hook            Specify hook(s) to attach this package to.\n\n:bind            Bind keys, and define autoloads for the bound commands.\n:bind*           Bind keys, and define autoloads for the bound commands,\n                 *overriding all minor mode bindings*.\n:bind-keymap     Bind a key prefix to an auto-loaded keymap defined in the\n                 package.  This is like `:bind', but for keymaps.\n:bind-keymap*    Like `:bind-keymap', but overrides all minor mode bindings\n\n:defer           Defer loading of a package -- this is implied when using\n                 `:commands', `:bind', `:bind*', `:mode', `:magic', `:hook',\n                 `:magic-fallback', or `:interpreter'.  This can be an integer,\n                 to force loading after N seconds of idle time, if the package\n                 has not already been loaded.\n:after           Delay the use-package declaration until after the named modules\n                 have loaded. Once load, it will be as though the use-package\n                 declaration (without `:after') had been seen at that moment.\n:demand          Prevent the automatic deferred loading introduced by constructs\n                 such as `:bind' (see `:defer' for the complete list).\n\n:if EXPR         Initialize and load only if EXPR evaluates to a non-nil value.\n:disabled        The package is ignored completely if this keyword is present.\n:defines         Declare certain variables to silence the byte-compiler.\n:functions       Declare certain functions to silence the byte-compiler.\n:load-path       Add to the `load-path' before attempting to load the package.\n:diminish        Support for diminish.el (if installed).\n:delight         Support for delight.el (if installed).\n:custom          Call `custom-set' or `set-default' with each variable\n                 definition without modifying the Emacs `custom-file'.\n                 (compare with `custom-set-variables').\n:custom-face     Call `customize-set-faces' with each face definition.\n:ensure          Loads the package using package.el if necessary.\n:pin             Pin the package to an archive." #<bytecode 0x155b23ddbde1>)(frame-cmds :load-path "/home/dave/Dropbox/dotfiles/emacs/doom.d/lisp/fram...")
  macroexpand((use-package! frame-cmds :load-path "/home/dave/Dropbox/dotfiles/emacs/doom.d/lisp/fram..."))
  internal-macroexpand-for-load((use-package! frame-cmds :load-path "/home/dave/Dropbox/dotfiles/emacs/doom.d/lisp/fram...") nil)
  #<subr eval-buffer>()
  apply(#<subr eval-buffer> nil)
  eval-buffer()  ; Reading at buffer position 41865
  my-eval-buffer()
  #<subr funcall-interactively>(my-eval-buffer)
  apply(#<subr funcall-interactively> my-eval-buffer)
  funcall-interactively(my-eval-buffer)
  #<subr call-interactively>(my-eval-buffer nil nil)
  apply(#<subr call-interactively> (my-eval-buffer nil nil))
  explain-pause--wrap-call-interactively(#<subr call-interactively> my-eval-buffer nil nil)
  apply(explain-pause--wrap-call-interactively #<subr call-interactively> (my-eval-buffer nil nil))
  call-interactively(my-eval-buffer nil nil)
  command-execute(my-eval-buffer)
</details>

### Describe your attempts to resolve the issue

Tried changing to absolute paths. It didn't work. 

### Steps to reproduce

Try evaluating a local package such as the one bellow under an Org Src environment. Inside a block, run `M-x org-edit-special`, followed by `eval-buffer`:

``` org
#+begin_src emacs-lisp
(use-package! frame-cmds
  :load-path "/home/dave/Dropbox/dotfiles/emacs/doom.d/lisp/frame")
#+end_src
```

### System Information

https://pastebin.com/d90tuwYd

**Comment by hlissner** [comment]
Does this fix the issue?

```elisp
;; add to $DOOMDIR/config.el
(defadvice! fix-doom--resolve-load-path-from-containg-file-a (fn label arg &optional recursed)
  :override #'doom--resolve-load-path-from-containg-file-a
  (let ((user-emacs-directory
         (when (stringp arg)
           (or (ignore-errors (dir!))
               default-directory))))
    (funcall fn label arg recursed)))
```

**Comment by alienbogart** [comment]
> Does this fix the issue?
> 
> ```emacs-lisp
> ;; add to $DOOMDIR/config.el
> (defadvice! fix-doom--resolve-load-path-from-containg-file-a (fn label arg &optional recursed)
>   :override #'doom--resolve-load-path-from-containg-file-a
>   (let ((user-emacs-directory
>          (when (stringp arg)
>            (or (ignore-errors (dir!))
>                default-directory))))
>     (funcall fn label arg recursed)))
> ```

That seems to resolve the issue, yes. Thanks.

**Comment by hlissner** [comment]
This issue should now be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by alienbogart** [comment]
> This issue should now be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

Yes, that seems to be resolved in latest Doom. Thanks!
