### ISSUE TITLE
help-mode-hook set to nil function

### ISSUE THREAD

**Issue by zeronone** [hlissner/doom-emacs#6242]
### What did you expect to happen?

Anything that opens the help-mode buffer encounters the following error.

### What actually happened?

Anything that opens the help-mode buffer encounters the following error.

```
Error (help-mode-hook): Error running hook "nil" because: (void-function nil) Disable showing Disable logging
Error (temp-buffer-setup-hook): Error running hook "help-mode-setup" because: (doom-hook-error help-mode-hook nil (void-function nil)) Disable showing Disable logging
```

### Describe your attempts to resolve the issue

Introspecting the `help-mode-hook`, we can see that it is set to `'(nil)`

I manually set `help-mode-hook` to `'nil`.

### Steps to reproduce

1. Open emacs
2. Run `M-x` `help-mode`

### System Information

https://pastebin.com/HZRJg4b4

**Comment by hlissner** [comment]
Please produce [a backtrace](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#how-to-extract-a-backtrace-from-an-error) from the error.

**Comment by hlissner** [comment]
I am also unable reproduce this in vanilla Doom and there are no references to `help-mode-hook` anywhere in Doom's source, so I'm inclined to suspect your private configuration.

**Comment by zeronone** [comment]
Ah sorry, this was due to my private config. Sorry for the noise.
