### ISSUE TITLE
`*` is not correctly bound in magit status buffer

### ISSUE THREAD

**Issue by dit7ya** [hlissner/doom-emacs#6248]
### What did you expect to happen?

Pressing `*` should open the `magit-worktree` transient menu (as found by listing the magit keybindings). 

If `*` is not to be bound here for some reason, some other key should be bound and should be listed accordingly.

### What actually happened?

It is not correctly bound - just falls back to `evil-ex-search-word-forward`.

### Steps to reproduce

1. Open magit status buffer.
2. Press `*`.

### System Information

https://pastebin.com/sbbWgQaS

**Comment by agraul** [comment]
That's done on purpose, see the discussion in https://github.com/hlissner/doom-emacs/pull/3583

**Comment by dit7ya** [comment]
I see, thanks.
