### ISSUE TITLE
Selected background color is the same as normal one in vertico

### ISSUE THREAD

**Issue by Typas** [hlissner/doom-emacs#6253]
### What did you expect to happen?

As in `:completion ivy`, the background color of selected line is darker gray, which is easy to distinguish from normal lines.

![ivy](https://user-images.githubusercontent.com/44962044/161910144-91ec7f5e-f8f7-41a9-ba22-e6534830da4f.png)

### What actually happened?

After migrated to `:completion vertico`, I can't know which one I am selecting.

![vertico](https://user-images.githubusercontent.com/44962044/161910696-d403a853-6160-409f-aba1-4112d64600fa.png)

### Describe your attempts to resolve the issue

When I changed the theme to dark one, it's easy to distinguish again.

![vertico-dark](https://user-images.githubusercontent.com/44962044/161911028-d2ecb5e0-9065-4f51-a9b8-c0b19a68050b.png)

### Steps to reproduce

1. Open emacs
2. Add `(setq doom-theme 'doom-one-light)` in `.doom.d/config.el`
3. Enable `:completion vertico` in `.doom.d/init.el`
4. Run `~/.emacs.d/bin/doom sync`
5. Type space twice to see

both 27.2 (on fedora 35) and 28.1 (on macOS 15.7) it happens

dark theme I used to resolve is `doom-one`

### System Information

https://pastebin.com/n90Ck3SM

**Comment by hlissner** [comment]
This is an issue for https://github.com/doomemacs/themes, not Doom Emacs. Please report it there.

As doomemacs/themes is in another org (for now), I am unable to transfer this.
