### ISSUE TITLE
Yandex icon from all-the-icons replaces cyrillic letter Я

### ISSUE THREAD

**Issue by akho** [hlissner/doom-emacs#6255]
### What did you expect to happen?

When I type a ‘Я’, I expect to see the glyph from my font. 

### What actually happened?

Instead, I get the Yandex logo from file-icons.ttf from all-the-icons. This is also referenced (with a screenshot) in domtronn/all-the-icons.el#299 (but only seems valid in Doom).

### Describe your attempts to resolve the issue

I disabled all-the-icons in packages.el, the issue went away.

It seems it's related to this bit in core-ui.el:

```
(add-hook! 'after-setting-font-hook
    (defun doom-init-all-the-icons-fonts-h ()
      (when (fboundp 'set-fontset-font)
        (dolist (font (list "Weather Icons"
                            "github-octicons"
                            "FontAwesome"
                            "all-the-icons"
                            "file-icons"
                            "Material Icons"))
          (set-fontset-font t 'unicode font nil 'append)))))
```

after which file-icons takes precedence over the normal font.

### Steps to reproduce

1. Install Doom
2. Open Emacs
3. Put ‘Я’ in any buffer

### System Information

https://pastebin.com/1mM60SvB

**Comment by hlissner** [comment]
This must be resolved resolved upstream. Please report it to https://github.com/domtronn/all-the-icons.el. As this is not really a Doom issue, I'll close it.

Otherwise, use 

```lisp
(add-hook! 'after-setting-font-hook :append
  (set-fontset-font t 'unicode X nil 'append))
```

Where `X` is any font that will provide the `Я` glyph you want.

**Comment by akho** [comment]
Thank you. Didn’t work, though

```lisp
(add-hook! 'after-setting-font-hook :append
  (set-fontset-font t 'unicode (font-spec :family "FiraCode Nerd Font" :size 11.0) nil 'prepend))
```

worked (with `'prepend`).
