### ISSUE TITLE
Consult package breaking change

### ISSUE THREAD

**Issue by ngharrison** [hlissner/doom-emacs#6279]
### What did you expect to happen?

`+vertico/switch-workspace-buffer` will show a preview of the selected buffer.

### What actually happened?

The error occurs:

`consult--read: No preview, the :state function protocol changed: (wrong-type-argument stringp setup)`

### Describe your attempts to resolve the issue

This also occurs when my personal config is excluded. This is caused by the recent [bump](https://github.com/hlissner/doom-emacs/commit/7121e993ca1ccaf05bafbfe1c3d9f605fc7c0f78) in completion modules and [breaking change](https://github.com/minad/consult/commit/3668df6afaa8c188d7c255fa6ae4e62d54cb20c9) in consult. I do not know consult well enough to give a solution.

### Steps to reproduce

1. Open Emacs
2. Load vertico and consult
3. Run `+vertico/switch-workspace-buffer`

### System Information

https://pastebin.com/87Cmiycr

**Comment by hlissner** [comment]
Duplicate of #6277 and fixed in dbd3021.

**Comment by ngharrison** [comment]
Thanks for the excellent work!
