### ISSUE TITLE
SPC-m-* bindings broken python

### ISSUE THREAD

**Issue by jcrono** [hlissner/doom-emacs#628]
The `SPC-m` bindings are not defined on python mode. Tested rust and web modules and bindings are working fine on them, seems an issue of the python-module 

At first I thought that the issue was nose mode since this was showing up:
```
Doom loaded 201 packages across 45 modules in 0.667s
ivy-posframe is enabled.
File mode specification error: (void-variable nose-mode)
```

However, after commenting nose mode out of the python module the bindings are still broken...
Messages:
```
Doom loaded 201 packages across 45 modules in 0.645s
ivy-posframe is enabled.
SPC m is undefined [3 times]

```
### System information

<details>
<summary>Click to expand</summary>

```
- OS: gnu/linux (x86_64-pc-linux-gnu)
- Emacs: 26.1 (May 28, 2018)
- Doom: 2.0.9 (develop 49f16f681c6009818929bec825bdda6a6a3bfad6)
- Graphic display: t (daemon: nil)
- System features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LIBSYSTEMD LCMS2
- Details:
  ```elisp
  uname -a:  Linux 4.16.11-1-ARCH #1 SMP PREEMPT Tue May 22 21:40:27 UTC 2018 x86_64 GNU/Linux
  modules:   (:feature (evil +everywhere) file-templates (lookup +devdocs +docsets) snippets spellcheck (syntax-checker +childframe) version-control workspaces :completion (ivy +childframe) :ui doom-dashboard doom-modeline doom-quit evil-goggles hl-todo nav-flash neotree (popup +all +defaults) vi-tilde-fringe window-select :emacs ediff electric-indent eshell imenu term :tools make magit pdf :lang data emacs-lisp latex markdown (org +attach +babel +capture +export +present) python rust sh web :config :private personal)
  packages:  n/a
  elc dirs:  (core/ core/autoload/)
  exec-path: (~/.nimble/bin ~/.cargo/bin ~/.local/bin /usr/local/sbin /usr/local/bin /usr/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /usr/lib/emacs/26.1/x86_64-pc-linux-gnu)
  ```
</details>

**Comment by benreyn** [comment]
Re: #585 @hlissner, I dont think that the `assocaite!` macro is fully fixed yet. This seems to be the same for rspec mode. (although the `SPC m r` leader still works.

**Comment by hlissner** [comment]
You are quite right! I already have a fix in the pipeline; it'll be up in the next batch of commits.

**Comment by hlissner** [comment]
The fix for `associate!` is up and should address the OP's issue. Let me know if that isn't the case!

Otherwise, I'll leave this open until it is merged into `master`.

**Comment by jcrono** [comment]
`(void variable nose-mode)` issue is fixed, thanks.

However the `SPC-m` bindings in python mode/anaconda mode are still not working:
```
Doom loaded 204 packages across 46 modules in 1.606s
ivy-posframe is enabled.
SPC m is undefined [5 times]
```

**Comment by hlissner** [comment]
@jcrono The SPC-m keybinds should work now.

**Comment by jcrono** [comment]
Everything is now working fine, thanks!
