### ISSUE TITLE
Doom emacs black frame

### ISSUE THREAD

**Issue by mastersilvapt** [hlissner/doom-emacs#6284]
### What did you expect to happen?

Updating emacs and doom should work as normal.

### What actually happened?

After updating emacs to 28.1-3 all dooms frame are black, not accepting any commands.

### Describe your attempts to resolve the issue

Reversing to 27.2 works again.

If any one has the same problem and is using pacman can do:
"pacman -U /var/cache/pacman/pkg/emacs-27.2-2-x86_64.pkg.tar.zst"
and will work again.

My sugestion is to put emacs on the ignore list of pacman (/etc/pacman.conf) until this is resolved.

### Steps to reproduce

Just needs to update emacs to other version above 27.2.

### System Information

https://pastebin.com/qUS2JyYv

**Comment by innerout** [comment]
Did you run `doom sync` after going from 27.2 to 28.1?

**Comment by harabat** [comment]
I'm on Emacs 28.1.5 (http://aur.archlinux.org/packages/emacs28-git) and was on Emacs 28.1-1 before (official repository), everything works as expected, have you tried bisecting your config?

**Comment by hlissner** [comment]
Sounds like an error occurred at startup. Run Emacs in debug mode: `emacs --debug-init` to see a backtrace of it.

Also, remember to run `doom build && doom sync` whenever you change the major version of Emacs (27<->28).

**Comment by mastersilvapt** [comment]
After installing 28.1.5 I logout of my system enter again and did doom build and doom sync and iogout and back in and it works now. I still didn't figure out where I'm wrong but has something about system vars I think because if i dont do any of thats logout it doenst work.

**Comment by musicfunfan** [comment]
I have the same problem on emacs 27.1. 

I do not know when it started but now when i open doom emacs i get blank windows and i can not do anything on it. I also try ``doom upgrade`` `` doom build`` ``doom sync`` .

This is the output of the doom doctor. 

```bash
> Checking your Emacs version...
  ! Emacs 27 is supported, but consider upgrading to 28.1
    Emacs 28.1 is better supported, faster, and more stable. Plus, Doom
    will drop 27.x support sometime late-2023.
> Checking for Doom's prerequisites...
> Checking for Emacs config conflicts...
> Checking for missing Emacs features...
  ! Emacs was not built with native compilation support
    Users will see a substantial performance gain by building Emacs with
    native compilation support, availible in emacs 28+.You must install a
    prebuilt Emacs binary with this included, or compile Emacs with the
    --with-native-compilation option.
> Checking for private config conflicts...
> Checking for common environmental issues...
> Checking for stale elc files...
> Checking for problematic git global settings...
> Checking Doom Emacs...
  ✓ Initialized Doom Emacs 3.0.0-pre
  ✓ Detected 33 modules
  ✓ Detected 117 packages
  > Checking Doom core for irregularities...
    Found font NFM.ttf
  > Checking for stale elc files in your DOOMDIR...
  > Checking your enabled modules...
    > :completion vertico
      ! The installed ripgrep binary was not built with support for PCRE lookaheads.
    > :lang markdown
      ! Couldn't find a markdown compiler, `markdown-preview' won't work

There are 4 warnings!
```
I also run. ``emacs --debug-init``

I get this. 

![εικόνα](https://github.com/doomemacs/doomemacs/assets/86926443/5a8d6232-da01-4182-9433-31eec0572d95)
.

**Comment by andrew-sugarman** [comment]
I run into the same problem: 

![Screenshot from 2023-10-22 22-54-10](https://github.com/doomemacs/doomemacs/assets/67701697/74f01d5b-f796-484f-8501-9beb1873ce60)

I have the same problem on --debug-init
`Debugger entered--Lisp error: (error "Invalid script or charset name: emoji")
  set-fontset-font(t emoji "Noto Color Emoji")
`

I must be doing something stupid, but this occurred after updating doom and reinstall of emacs does not fix

**Comment by theclakuh** [comment]
> I run into the same problem:
> 
> [...]
> 
> I have the same problem on --debug-init `Debugger entered--Lisp error: (error "Invalid script or charset name: emoji") set-fontset-font(t emoji "Noto Color Emoji") `
> 
> I must be doing something stupid, but this occurred after updating doom and reinstall of emacs does not fix

I have the same problem. Going back along the commit history to avoid changes that have something todo with any emojis/fonts it worked out as usual with https://github.com/doomemacs/doomemacs/commit/5e6430e9e6e642fc12913cc6b10e599317a2bb7a
```
commit 5e6430e9e6e642fc12913cc6b10e599317a2bb7a (HEAD)
Author: Liam Hupfer <liam@hpfr.net>
Date:   Wed Sep 20 17:46:48 2023 -0500

    fix: assign Nerd Fonts directly to Unicode PUAs
    
    Nerd Fonts assign icons to code points in these Unicode Private Use
    Areas. `doom-unicode-font` is now available again as a user-defined
    fallback of last resort for non-PUA Unicode code points.
    
    Ref: https://github.com/ryanoasis/nerd-fonts/wiki/Glyph-Sets-and-Code-Points/f12c615e4d2a411d5e9b3cc57533cf4866e6e3f2#overview
```

**Comment by khayyamsaleem** [comment]
Was able to "fix" this by upgradign emacs from 27->28.1+nativecomp on Ubuntu 22.04 LTS

**Comment by andrew-sugarman** [comment]
> Was able to "fix" this by upgrading emacs from 27->28.1+nativecomp on Ubuntu 22.04 LTS. It's probably a good idea to create a new issue with @theclakuh 's comment.

I apologize for delay - a fresh install of emacs building 29.1 from source followed by reinstalling Doom worked for me, but i concur this is probably not the simplest solution

**Comment by cgreen** [comment]
> I run into the same problem:
> 
> ![Screenshot from 2023-10-22 22-54-10](https://user-images.githubusercontent.com/67701697/277218890-74f01d5b-f796-484f-8501-9beb1873ce60.png)
> 
> I have the same problem on --debug-init `Debugger entered--Lisp error: (error "Invalid script or charset name: emoji") set-fontset-font(t emoji "Noto Color Emoji") `
> 
> I must be doing something stupid, but this occurred after updating doom and reinstall of emacs does not fix

Running the last step of '[Install Doom Manually](https://github.com/doomemacs/doomemacs/blob/master/docs/getting_started.org#install-doom-manually)' fixed it for me:

`emacs --batch -f nerd-icons-install-fonts`

**Comment by edwinclement08** [comment]
@cgreen, your checkout command is the one that fixed mine. Thanks a lot 👍🏼 
That said, there must be some issue between that and current.
