### ISSUE TITLE
Is it possible to remove the dependencies to projectile (replace it with project.el)?

### ISSUE THREAD

**Issue by xqliu** [hlissner/doom-emacs#6291]
### Describe your request

Hi,

Wondering is it possible to remove the dependency to projectile and replace it with project.el?

Thanks.

### Briefly explain its use-case

As per my research, project.el has meet my requirement and would like to see whether it's feasible to use it instead of projectile?

Thanks.

**Comment by hlissner** [comment]
Unfortunately, there is no way to remove projectile from Doom, as it is a core package, and it has been deeply integrated into Doom and many of its packages. That said, project.el is already available, so you can simply use it, and there are plans to replace projectile with it [in the future](https://github.com/orgs/doomemacs/projects/6/views/1). It'll be some time until I get there, though.

In any case, as this is already on the roadmap (and because our issue tracker isn't the place for questions like these), I will close this, but feel free to follow up here.

**Comment by xqliu** [comment]
Thanks Hlissner for your timely reply and help 👍

**Comment by adamcstephens** [comment]
Is this still on the roadmap? The project link doesn't work anymore and I wasn't able to discover what it originally pointed to.

**Comment by dit7ya** [comment]
Is there any option to disable the caching when projectile opens a new project?

**Comment by peterhoeg** [comment]
> Is this still on the roadmap? The project link doesn't work anymore and I wasn't able to discover what it originally pointed to.

`projectile` is listed for removal here:
https://github.com/orgs/doomemacs/projects/5

**Comment by ugurbolat** [comment]
Projectile is especially slowing down when opening new buffers in tramp. It would be pretty cool if at least moved into the modules (of course I am not sure how much of a hard-core dependency projectile is to the doom).

**Comment by bbatsov** [comment]
@ugurbolat Slowing down how exactly? Most of the slowdown on TRAMP was coming from the way the modeline used to be implemented in the past, but has been fixed since. We're also employing some pretty aggressive caching of the project roots these days, so I'd be curious to see some data from the profiler about the slowdown you're experiencing.

**Comment by betaprior** [comment]
@bbatsov I also came here looking to maximally disable projectile. I work with a giant monorepo that projectile is unable to handle. I have to manually disable hooks/advice such as `compilation-find-file-projectile-find-compilation-buffer` to prevent emacs from hanging. It would be nice to do it in a centralized way. Alternatively, is it possible to give projectile an explicit list of files or directories that define my project? I know I can specify a custom project root, but the files relevant to my actual project can live very far in the branches of the giant monorepo tree.

**Comment by aSapien** [comment]
I came here looking to replace projectile with project.el. Did anybody here succeed in that?

**Comment by hlissner** [comment]
@aSapien Not right now. It is a core package and will cause breakage to even try, [but it's being worked on.](https://redirect.github.com/doomemacs/community/issues/31)

In any case, please don't use our issue tracker for user support. We have a [discord](https://doomemacs.org/discord) and [github discussions board](https://doomemacs.org/discuss) for that.

**Comment by aSapien** [comment]
Thanks @hlissner! I appreciate all the work you're putting into the project. I will ask some follow-ups in the community.

**Comment by panchoh** [comment]
The URL that Henrik posted got mangled, @aSapien. This is the right one:

https://github.com/doomemacs/community/issues/31

**Comment by antoniojkim** [comment]
@hlissner I can see that projectile was moved to compat in https://github.com/doomemacs/core/commit/964ad524e71c261e6f05912a4c8a61bed7272861. Does that mean the project.el support is here?

Asking because I recently did a `doom upgrade` and I can see that the `SPC p` bindings for projectile are all gone

**Comment by panchoh** [comment]
> Asking because I recently did a `doom upgrade` and I can see that the `SPC p` bindings for projectile are all gone

Possible snafu upon updating. I have my Doom current as of *now*, and those bindings are still alive and well.

**Comment by hlissner** [comment]
@antoniojkim Not yet. The `:doom compat` module is where pre-v3 functionality will live, giving folks who want to put off updating their configs some backwards compatibility, but the module is [hardcoded as enabled](https://github.com/doomemacs/core/blob/394527828a223f91bd5490aeb3931e295e171ea5/lisp/doom-modules.el#L63-L65) until v3. The missing bindings on `SPC p` sounds more like a startup error.

**Comment by 3213-cmd** [comment]
> [@hlissner](https://github.com/hlissner) I can see that projectile was moved to compat in [964ad52](https://github.com/doomemacs/core/commit/964ad524e71c261e6f05912a4c8a61bed7272861). Does that mean the project.el support is here?
> 
> Asking because I recently did a `doom upgrade` and I can see that the `SPC p` bindings for projectile are all gone

same for me..., don't see any errors on startup

**Comment by hlissner** [comment]
<img width="893" height="193" alt="Image" src="https://github.com/user-attachments/assets/885bdcce-56a3-4116-a994-16ecc7c3bcf3" />

Still there.

**Comment by 3213-cmd** [comment]
<img width="872" height="160" alt="Image" src="https://github.com/user-attachments/assets/b364248a-32e3-4b71-867c-3220e74fe04f" />

You're right, after uncommenting this from my config.org it appears again. Did not have any issues in the past with having those lines there though. Only recently ~2 weeks ago. Not sure if it was behaving as intended before that or now.

**Comment by hlissner** [comment]
Ah, this commit explains why: https://github.com/doomemacs/core/commit/635bc939d

**Comment by 3213-cmd** [comment]
That explains it, thank you for the quick help. And sorry for not noticing it when upgrading doom. I usually check all the commits to see if they affect me, must have missed this one!

Everything is much appreciated!
