### ISSUE TITLE
+default/search-project how to exclude results  with vertico

### ISSUE THREAD

**Issue by donneyluck** [hlissner/doom-emacs#6319]
### What did you expect to happen?

+default/search-project result  exclude some type files or exclude some code
like this 
![image](https://user-images.githubusercontent.com/60682638/164364519-52c2e066-64e2-4a56-8cd7-fcbf921fa62e.png)
![image](https://user-images.githubusercontent.com/60682638/164364629-bb877626-636d-4bd8-a623-7d511010446b.png)

### What actually happened?

can not exclude code or type files

![image](https://user-images.githubusercontent.com/60682638/164364700-275bfb06-ac41-4b83-afcf-f15af5325b68.png)

### Describe your attempts to resolve the issue

how can i do this 

### Steps to reproduce

SPC /    and search come code

### System Information

i try M-x doom/info and open pastebin.com  nothing happened

**Comment by hlissner** [comment]
> i try M-x doom/info and open pastebin.com nothing happened

It only opens pastebin.com in your browser. You're supposed to then paste it in and click "create new paste".

------

In any case, this is a support question, which belongs on [our Discourse](https://discourse.doomemacs.org) or [Discord](https://doomemacs.org/discord), not our Github issue tracker, so I will close it. 

[Check here for an answer to this question](https://discourse.doomemacs.org/t/how-to-filter-search-results-with-vertico/2518/2).
