### ISSUE TITLE
magit is broken due to GIT_CONFIG_GLOBAL=/dev/null

### ISSUE THREAD

**Issue by jakalx** [hlissner/doom-emacs#6320]
### What did you expect to happen?

magit works as before and uses my `~/.config/git/config` file.

### What actually happened?

magit commit fails with:

```
Author identity unknown

*** Please tell me who you are.
                                                                                  Run                                                                                                                                                                   git config --global user.email "you@example.com"                                  git config --global user.name "Your Name"
```

### Describe your attempts to resolve the issue

Removing the offending line from `bin/doom` fixes the problem for me

### Steps to reproduce

1. doom run
2. open magit in a repository
3. try to commit something

### System Information

https://pastebin.com/ePfuXS0Y

**Comment by hlissner** [comment]
Is there a `GIT_CONFIG_*` entry in your envvar file? (Found in `~/.emacs.d/.local/env`)

**Comment by jakalx** [comment]
No, there is no `GIT_CONFIG_*` in the `env` file. The variable is set in both `eshell` and regular `shell` - that's how I found out about it in the first place (comparing `/usr/bin/env` from within emacs against outside of emacs).

Regenerating the environment doesn't have any effect.

**Comment by hlissner** [comment]
So Eshell is leaking state out of shell scripts? That seems like an eshell bug (and a terrible one at that). 

I'm setting `GIT_CONFIG_GLOBAL` to address an issue of git configs interfering with our package manager, so I'm not willing to remove that line from `bin/doom`. I'll investigate eshell to see if something can be done there.

**Comment by jakalx** [comment]
But magit is also broken. How does it work for you? My path of investigation was: magit -> git in eshell/shell -> git in a shell outside of emacs, only the latter worked as expected, then I compared the environments. To me it sounds quite reasonable that eshell/shell inherit emacs' environment.

**Comment by jakalx** [comment]
`getenv` from within `doom run` does also show `GIT_CONFIG_GLOBAL`.

Would it be possible to just instruct straight to ignore the users'/systems git config and not the whole world?

**Comment by hlissner** [comment]
> doom run
Oh! You're launching Doom exclusively via `doom run`?

**Comment by hlissner** [comment]
`doom run` exists primarily for debugging purposes, not as a real entry point, so yes, it's natural that Emacs inherit `bin/doom`'s environment. If you launch it normally (by running `emacs`), it will not. I was under the impression that you were running `bin/doom` from _within_ eshell or `M-x shell`, and the state from its shebang was somehow leaking into Emacs' process environment.

In that case, I'll have to rethink bin/doom's shebang, or maybe move `doom run` out into its own shell script.

> Would it be possible to just instruct straight to ignore the users'/systems git config and not the whole world?

No, because the point is to isolate straight's environment. Any source of contamination is a source of problems. In any case, I've found the source of the issue, so I'll see if I can find a decent workaround.

**Comment by jakalx** [comment]
Yes, I thought tthat's how it's supposed to be?

**Comment by jakalx** [comment]
I'll close the issue since the problem existed mainly between keyboard and doom, not within doom :) I'll just go back to simply run `emacs` again. Thanks for enlightening me!

**Comment by hlissner** [comment]
Not at all. After some consideration, I've changed my mind on the matter and now consider it a Doom bug, because the instance of Emacs `doom run` launches is being contaminated, which is undesirable, so I'll reopen it as a bug. I have a fix in the pipeline and will deploy it soon.

**Comment by hlissner** [comment]
This issue should now be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
