### ISSUE TITLE
Failed to load magit package incrementally, because: (void-function magit-menu-set)

### ISSUE THREAD

**Issue by fredfortier** [hlissner/doom-emacs#6324]
### What did you expect to happen?

No error at startup. Display magit-status as normal.

### What actually happened?

Error upon loading my usual project:
```
Failed to load magit package incrementally, because: (void-function magit-menu-set)
```
Error on magit-status:
```
cl-generic-ensure-function: magit-menu-common-value is already defined as something else than a generic function
```

### Describe your attempts to resolve the issue

Looked up similar recent issue. Reached for the new issue button.

### Steps to reproduce

See "What actually happened" with my config. This started after `doom upgrade` which I haven't done in a month or two. I know emacs 29 isn't supported but I figure you might point me in the right direction.

### System Information

https://pastebin.com/T66PQmwN

**Comment by bilus** [comment]
I'm seeing the same error after upgrading to the latest doom and rebuilding packages using `doom build`.

**Comment by Dieken** [comment]
> I'm seeing the same error after upgrading to the latest doom and rebuilding packages using `doom build`.

@bilus , `magit/transient` is shipped with Emacs now, but old Emacs such as emacs-mac 29.4 has old package `transient` and newer Magit requires newer package `transient`, and Doom Emacs doesn't pin version of transient.

Solution:  

1) upgrade your Emacs to get latest `transient`
2) delete ~/.emacs.d/.local/straight/*/transient and run `doom sync` again, Doom Emacs will clone latest version of magit/transient.

notify @hlissner too.
