### ISSUE TITLE
Support turning off lazy `org-babel` loading (at a per language level)

### ISSUE THREAD

**Issue by femtomc** [hlissner/doom-emacs#6327]
### Describe your request

I'm trying to utilize [`julia-snail`](https://github.com/gcv/julia-snail) to execute code blocks in `org` -- unfortunately, even if I do not specify `julia` as a `babel` language (as the `doom` README suggests not to!), `doom` will load `julia` when I try to `C-c C-c`, which overwrites `julia-snail` execution -- preventing usage of the `ob-julia` module for execution.

Is it possible to turn off lazy loading of `babel` libraries for specific languages, ideally as requested by a user?

### Briefly explain its use-case

The use case is to support evaluation with `ob-X` different than the "official" one supported by `babel`.

**Comment by hlissner** [comment]
This is what `+org-babel-mode-alist` and `+org-babel-load-functions` are for:

1. Use `+org-babel-mode-alist` when the package mapping is simple, e.g.

   ```elisp
   ;;; add to $DOOMDIR/config.el
   (add-to-list '+org-babel-mode-alist '(julia . julia-snail))
   ```

2. Use `+org-babel-load-functions` when its loading needs are more complex (needs to return non-nil to inform Doom's lazy loader that it succeeded). For example:

   ```elisp
   ;;; add to $DOOMDIR/config.el
   ;; this is overkill
   (defun load-julia-snail (lang)
     (when (equal lang "julia")
       (require 'julia-snail)))
   (add-to-list '+org-babel-load-functions #'load-julia-snail)
   ```

   - Jupyter example: https://github.com/hlissner/doom-emacs/blob/master/modules/lang/org/contrib/jupyter.el#L18-L30
   - ob-ipython example: https://github.com/hlissner/doom-emacs/blob/master/modules/lang/org/contrib/ipython.el#L11-L14

Both of these will stop Doom's lazy loader from doing any other magic to load the package.

------

In the future, please use [our Discourse](https://discourse.doomemacs.org) or [our Discord](https://doomemacs.org) for requesting features or asking how-to and support questions like these. Our issue tracker is only for bug reports and previously-discussed-and-approved feature requests, and I will be enforcing this rule more strictly soon.

**Comment by femtomc** [comment]
thank you @hlissner!
