### ISSUE TITLE
Rust: Lost Inlay Hints after Upgrade

### ISSUE THREAD

**Issue by fredfortier** [hlissner/doom-emacs#6329]
### What did you expect to happen?

Display inlay hints fetched from rust-analyzer like before the upgrade.

### What actually happened?

*Messages*
```
LSP :: Error from the Language Server: waiting for cargo metadata or cargo check (Unknown error) [6 times]
```

*rust-analyzer::stderr
```
[ERROR rust_analyzer::dispatch] unknown request: Request { id: RequestId(I32(24)), method: "experimental/inlayHints", params: Object({"textDocument": Object({"uri": String("file:///home/user/src/my-project/lib.rs")})}) }
```

### Describe your attempts to resolve the issue

Tried upgrading rust-analyzer but newer versions aren't compatible with my project's toolchain (1.58). I assume that rustic or some underlying module expect a newer rust-analyzer. I didn't note by release hashes before upgrade so I don't know what module to pin to what release. I know this isn't a doom issue per say, but I'm hoping for some pointers.

### Steps to reproduce

1. Upgrade doom to latest
2. Configure rustic to use rust-analyzer
3. Install rust-analyzer tag 2021-11-01
4. Open a Rust project

### System Information

https://pastebin.com/TDykYqy1

**Comment by balloneij** [comment]
I think this broke in lsp-mode a while ago: https://github.com/emacs-lsp/lsp-mode/pull/3404

I pinned lsp-mode to a newer version to fix it for myself https://github.com/hlissner/doom-emacs/blob/master/docs/getting_started.org#pinning-packages-to-specific-commits=

**Comment by fredfortier** [comment]
@balloneij Thanks! Just to confirm, a newer version of lsp-mode than what ships with doom fixes it? I would have thought the opposite. I'll try to unpin and use the latest. But just in case, what version works for you?

**Comment by fredfortier** [comment]
Same problem with the unpinned version unfortunately: https://pastebin.com/buhVeGTg

**Comment by fredfortier** [comment]
Ok, I get it now. rust-analyzer added the "experimental" namespace to relayHints. This commit adjusts lsp-mode: fa359143f15f89cb13495f8fb4c70e35e5e0093e so I pinned it to the commit before.

```
(unpin! lsp-mode :pin "a39a35be9e01fe86cf250cd2a6c7920aaa463aea")
```
