### ISSUE TITLE
Clojure - Broken font lock / syntax highlighting after #6298

### ISSUE THREAD

**Issue by evanlouie** [hlissner/doom-emacs#6336]
### What did you expect to happen?

Prior to  #6298 functions which we're evaluated via cider would have an updated font lock to show that it is a function:
<img width="214" alt="Screen Shot 2022-04-26 at 20 16 33" src="https://user-images.githubusercontent.com/2081587/165433529-05ad0dee-79f4-4f75-8c4d-ddfe2815bb8a.png">

### What actually happened?

But after  #6298 the syntax highlighting does not update:
<img width="152" alt="Screen Shot 2022-04-26 at 20 22 26" src="https://user-images.githubusercontent.com/2081587/165433549-17a50410-7cd0-43a5-bc09-391ef1965849.png">

### Describe your attempts to resolve the issue

This fixes font locking / syntax highlighting:

```sh
cd ~/.emacs.d/modules/lang/clojure
git checkout ffe8226a5c050de63402f9baed34c5287f085f2b doctor.el config.el
```

### Steps to reproduce

1. Be on master
2. Open a clojure project
3. Open a `.clj` file
4. `cider-connect-clj` 
5. `cider-load-buffer`

### System Information

https://pastebin.com/ZBpW0BHR

**Comment by evanlouie** [comment]
pinging @ericdallo was this expected behaviour of your change?

**Comment by evanlouie** [comment]
APOLOGIES! I noticed I had not set `lsp-semantic-tokens-mode`

**Comment by ericdallo** [comment]
@evanlouie yep, maybe we could enable `lsp-semantic-tokens-enable ` when +LSP flag is on
