### ISSUE TITLE
Cascadia Code Italic issue

### ISSUE THREAD

**Issue by tachanka61** [hlissner/doom-emacs#6345]
### What did you expect to happen?

I expect Emacs to render Italic in proper weight.

### What actually happened?

My default font is Cascadia Code:
``` emacs-lisp
(setq doom-font (font-spec :family "Cascadia Code" :size 14)
      doom-variable-pitch-font (font-spec :family "Roboto" :size 14))
```
But in comments and code-highlights (with tree-sitter) italic is very thin:

![image](https://user-images.githubusercontent.com/89523794/166009349-bd0d8216-b66c-4935-9225-c8446eda8684.png)
![image](https://user-images.githubusercontent.com/89523794/166009673-0c8806f8-b251-4524-b4a8-e8e4e5d72e4b.png)

I think that it's Ultra-thin weight. 

### Describe your attempts to resolve the issue

Changing font to ``font-spec :family "Cascadia Code" :size 14 :weight 'normal`` didn't help, but when weight is ``'semi-bold`` or more, it renders properly:

![image](https://user-images.githubusercontent.com/89523794/166018712-604de8d0-8177-4ef8-ae28-8674f3ecc469.png)

Is it font issue or Doom Emacs misbehavior? Should I change font face?

### Steps to reproduce

1. Open Emacs
2. Set default font to Cascadia Code using ``(setq doom-font (font-spec :family "Cascadia Code" :size 14))``
3. Reload Emacs config
4. View face of keywords, comments or other italic (my full configuration of Doom Emacs is available in my [dotfiles](https://github.com/tachanka61/dotfiles/tree/main/doom) repo)

### System Information

https://pastebin.com/SifdBRTc

**Comment by hlissner** [comment]
This is a font issue. "Cascadia Code" appears to lack an italic variant for its regular weight (400), so you must explicitly specify another weight, as you have. [These settings](https://github.com/tachanka61/dotfiles/blob/main/doom/config.org#font-management) are responsible.

I will close this, as it is not a Doom issue, but feel free to follow up here.

**Comment by tachanka61** [comment]
Hello, @hlissner, sorry for interrupting you again, but I noticed that font in terminal Emacs works pretty fine: 
![image](https://user-images.githubusercontent.com/89523794/166113451-c77480fd-adfd-4fb0-b4fa-c8c196876ea4.png)

I'm using [kitty](https://github.com/kovidgoyal/kitty) terminal with the same font, as in Emacs, also in VSCode font has no any issues: 

![image](https://user-images.githubusercontent.com/89523794/166113593-17af350d-ad04-415f-ad99-d0fdda75f49c.png)

Also tried to play with default Emacs(not default Doom) configuration: 
![image](https://user-images.githubusercontent.com/89523794/166114230-2c698f79-6dd3-4877-acd5-0f20ba37d812.png)

So i think that it's Emacs issue, not Doom.
