### ISSUE TITLE
straight.el file is missing

### ISSUE THREAD

**Issue by marvhus** [hlissner/doom-emacs#6346]
### What did you expect to happen?

I expected that when i ran `~/.emacs.d/bin/doom install` that it would install

### What actually happened?

when I tried to install I got this error:
```
x There was an unexpected error
  Message: File is missing
  Error: (file-missing "Cannot open load file" "No such file or directory" "/home/martin/.emacs.d/.local/straight/repos/straight.el/straight.el")
  Backtrace:
    (require straight "/home/martin/.emacs.d/.local/straight/repos/straight.el...
    (let ((repo-dir (doom-path straight-base-dir "straight/repos/straight.el")...
    (doom--ensure-straight (:host github :repo "raxod502/straight.el" :branch ...
    (let* ((--cl-rest-- (alist-get 'straight packages)) (recipe (car (cdr (pli...
    (let ((packages (doom-package-list nil 'core))) (let* ((--cl-rest-- (alist...
    (progn (if doom-debug-p (progn (let ((inhibit-message t)) (message #("DOOM...
    (if (or force-p (null (and (boundp 'straight-recipe-repositories) straight...
    (doom-initialize-core-packages)
    (eval-buffer #<buffer  *load*-229703> nil "/home/martin/.emacs.d/core/core...
    (load-with-code-conversion "/home/martin/.emacs.d/core/core-cli.el" "/home...
! Extended backtrace logged to .local/doom.error.log
No catch for tag: exit, 255
```

(Because of this I can't run the `doom info`command)

### Describe your attempts to resolve the issue

I have tried multiple times to remove and re download the repo, but it keeps giving me the error.

### Steps to reproduce

1. `git clone --depth 1 https://github.com/hlissner/doom-emacs ~/.emacs.d*
2. `~/.emacs.d/bin/doom install`

### System Information

I literally can't run the "doom info" command because it just gives me the same error, and doom emacs isn't properly installed so I can't do "M-x doom/info" either

**Comment by hlissner** [comment]
I can't reproduce this, so I assume the initial installation of straight failed, possibly due to a git error or connection issue. Try deleting `~/.emacs.d/.local` by hand, the run `$ doom install` again.

**Comment by marvhus** [comment]
> I can't reproduce this, so I assume the initial installation of straight failed, possibly due to a git error or connection issue. Try deleting `~/.emacs.d/.local` by hand, the run `$ doom install` again.

That still gives me the error.
here is the log file btw
https://pastebin.com/vmLdZBjs

I quickly read over it and I saw something about git having too low of a version, but `git --version` gives:
```
git version 2.25.1
```

**Comment by hlissner** [comment]
It's complaining that the `~/.emacs.d/.local/straight/repos/straight.el` repo does not exist. Doom installs straight as one of the first things it does (because it's a core dependency). Because I cannot reproduce this on any of my test VMs (running Windows 7, 10, MacOS 10.15, 10.18, NixOS, Ubuntu, or Arch), on Emacs 27.2, 28.1, and 29, I'm convinced this is a local issue and not a Doom issue.

Please check that `~/.emacs.d/.local/straight/repos/straight.el` exists. If it doesn't, or it's empty, it's likely a networking issue (maybe you have a proxy or ISP that has blocked github, and redirects in such a way that it doesn't return a sensible HTTP error code to inform `git` that it has failed). Or your connection simply failed midway through the clone.

If you can't figure it out, then try cloning the repo manually:

```sh
git clone https://github.com/raxod502/straight.el ~/.emacs.d/.local/straight/repos/straight.el
```

Then run `doom install` again.

**Comment by marvhus** [comment]
> It's complaining that the `~/.emacs.d/.local/straight/repos/straight.el` repo does not exist. Doom installs straight as one of the first things it does (because it's a core dependency). Because I cannot reproduce this on any of my test VMs (running Windows 7, 10, MacOS 10.15, 10.18, NixOS, Ubuntu, or Arch), on Emacs 27.2, 28.1, and 29, I'm convinced this is a local issue and not a Doom issue.
> 
> Please check that `~/.emacs.d/.local/straight/repos/straight.el` exists. If it doesn't, or it's empty, it's likely a networking issue (maybe you have a proxy or ISP that has blocked github, and redirects in such a way that it doesn't return a sensible HTTP error code to inform `git` that it has failed). Or your connection simply failed midway through the clone.
> 
> If you can't figure it out, then try cloning the repo manually:
> 
> ```shell
> git clone https://github.com/raxod502/straight.el ~/.emacs.d/.local/straight/repos/straight.el
> ```
> 
> Then run `doom install` again.

I think I found the Issue.

I found a global git config:
```
url.git@github.com:.insteadof=https://github.com/
```
that converted https url into ssh
and it requires my password
but it didn't prompt me (idk git is weird)

but when I removed that, and removed and cloned the doom repo again, it worked.

**Comment by hlissner** [comment]
Ah, good catch! Doom already [prevents user/system git config from interfering with straight when it installs packages](https://github.com/hlissner/doom-emacs/blob/fbfc6353003199a0e869af3518552a8d2ca1c623/core/cli/lib/straight-hacks.el#L122-L130), but this did not extend to [Doom's installation of straight itself](https://github.com/hlissner/doom-emacs/blob/master/core/core-packages.el#L113-L187). I've fixed this in 3b78975. Thanks for bringing it to my attention!

**Comment by gdonald** [comment]
I'm hitting this same issue trying to install in Debian:

```
> git clone --depth 1 https://github.com/doomemacs/doomemacs ~/.emacs.d
Cloning into '/home/gd/.emacs.d'...
remote: Enumerating objects: 1099, done.
remote: Counting objects: 100% (1099/1099), done.
remote: Compressing objects: 100% (1051/1051), done.
remote: Total 1099 (delta 29), reused 517 (delta 10), pack-reused 0
Receiving objects: 100% (1099/1099), 1018.23 KiB | 9.34 MiB/s, done.
Resolving deltas: 100% (29/29), done.
```

And then:

```
> ~/.emacs.d/bin/doom install
> Installing straight...
x There was an unexpected error
  Message: File is missing
  Error: (file-missing "Cannot open load file" "No such file or directory" "/home/gd/.emacs.d/.local/straight/repos/straight.el/straight.el")
  Backtrace:
    (require straight "/home/gd/.emacs.d/.local/straight/repos/straight.el/str...
    (let ((repo-dir (doom-path straight-base-dir "straight/repos/straight.el")...
    (let ((process-environment (copy-sequence process-environment))) (setenv "...
    (doom--ensure-straight (:host github :repo "raxod502/straight.el" :branch ...
    (let* ((--cl-rest-- (alist-get 'straight packages)) (recipe (car (cdr (pli...
    (let ((packages (doom-package-list nil 'core))) (let* ((--cl-rest-- (alist...
    (progn (if doom-debug-p (progn (let ((inhibit-message t)) (message #("DOOM...
    (if (or force-p (null (and (boundp 'straight-recipe-repositories) straight...
    (doom-initialize-core-packages)
    (eval-buffer #<buffer  *load*-937384> nil "/home/gd/.emacs.d/core/core-cli...
! Extended backtrace logged to .emacs.d/.local/doom.error.log
No catch for tag: exit, 255
```

I tried deleting `.emacs.d` and tried again, didn't help.

I have latest git from src (Doom complained that my OS git was too old):

```
> git --version
git version 2.36.1
```

I have emacs 28.1 from src (Doom complained that my OS emacs was too old):

```
> emacs --version
GNU Emacs 28.1
```

How to proceed?  Thanks.

**Comment by gdonald** [comment]
I resolved this by installing `libcurl4-openssl-dev` and recompiling git.

**Comment by danjin250** [comment]
Writing to say I had a similar issue, and how I was able to resolve it
`Error: (file-missing "Cannot open load file" "No such file or directory" "/home/myuser/.emacs.d/.local/straight/repeos/straight.el/straight.el")`

This was happening on M1 Mac, emacs-plus@28 installed from homebrew, zsh, iterm2 with rosetta.
I had tried reinstalling many homebrew formulas like git, zsh, etc to no avail.

I did verify that there was no file there, so the git clone must've failed somehow.

Henrik's suggestion to git clone manually helped it get further along in the process:
`git clone https://github.com/raxod502/straight.el ~/.emacs.d/.local/straight/repos/straight.el`

Then I retried the install, and it failed at a different git clone, with an error like
`SSL certificate problem: unable to get local issuer certificate`

Afterwards, I found a suggestion online saying to apply this to the git config
`git config --global http.sslVerify false`

After that, the doom install worked perfectly without issues

**Comment by conorbros** [comment]
I just needed to delete `.emacs.d/.local/` and run `doom upgrade`.

**Comment by equwal** [comment]
Another issue is if you have `http_proxy` or `https_proxy` set for some reason, doom doesn't seem to know how to do that. If you actually are behind a proxy, you might need to setup an ssh tunnel instead for doom.

I just ran doom with no proxy:

```sh
http_proxy="" https_proxy="" doom install
```

**Comment by forkrul** [comment]
Lost about 2h trying to debug this.

Running
```git clone --depth 1 https://github.com/doomemacs/doomemacs ~/.config/emacs && http_proxy="YOURPROXY:PORT" https_proxy="YOURHTTPSPROXY:PORT" ~/.config/emacs/bin/doom install``` 
for corporate setups work. 

I'd suggest including a check on straight.el failure in the doom install, in order to spit out proxy used, in order for user to be able to debug this.

**Comment by recaff** [comment]
emacs-vision：This is GNU Emacs 29.4 (build 2, x86_64-w64-mingw32) of 2024-07-05
mycomputer：windows 11 system
使用boom install时，出现如下error
始终无法解决，need help，thanks~
error如下：
----------------------------------------------------------------------------------------------------------------------------
In straight-bug-report:
straight.el:6536:2: Warning: docstring has wrong usage of unescaped single quotes (use \= or different quoting)
Symbol's value as variable is void: comp-deferred-compilation-deny-list
PS C:\Users\HUAWEI\.emacs.d\bin>
