### ISSUE TITLE
eshell autocomplete dot slash

### ISSUE THREAD

**Issue by year39** [hlissner/doom-emacs#6350]
### What did you expect to happen?

autocomplete does this weird thing (see gif) when using dot slash to run an executable. It appears the ./ is emitted when selecting on the items in the pop up!
 

### What actually happened?

![emacs eshell](https://user-images.githubusercontent.com/70146464/166128892-7fa2da67-289c-4717-9885-9b443c1c93b0.gif)

### Steps to reproduce

this happens when selecting one of the items in auto complete popup.

emacs v29

### System Information

https://pastebin.com/4nbnEjQr

**Comment by year39** [comment]
[.doom.d/init.el](https://pastebin.com/SYiipB4h)

**Comment by ethan-leba** [comment]
I’ve reported this bug here: https://github.com/company-mode/company-mode/issues/1322

Seems to be an issue with eshell itself, unfortunately :/

**Comment by year39** [comment]
Thank you @ethan-leba .. I will close this issue.
