### ISSUE TITLE
company-anaconda not added to company-backends

### ISSUE THREAD

**Issue by ppwwyyxx** [hlissner/doom-emacs#638]
### Steps to reproduce

1. Open Emacs and Open an empty python file
2. M-: company-backends
3. It prints some backends but not "company-anaconda"

I found that reverting https://github.com/hlissner/doom-emacs/commit/c80baef05d61f44dd0218fce789ab3c602b96823 solves the problem.
Specifically, the hook for python-mode should be added before anaconda-mode is activated. It should stay in the `:init` block rather than `:config`.

**Comment by hlissner** [comment]
You are correct. Anaconda-mode was loading too late for its config to take effect (in the first python-mode buffer). This has been fixed as of 83db654. Let me know if that isn't the case!
