### ISSUE TITLE
Add binding for M-x woman

### ISSUE THREAD

**Issue by ar1a** [hlissner/doom-emacs#639]
seems pretty useful

**Comment by ar1a** [comment]
although, M-x man seems like it works better

**Comment by AloisJanicek** [comment]
`SPC h w` is free, but since woman can't still handle tables, I would suggest to make woman as an alias to man so we can get proper functionality without breaking key shortcut mnemonics.

**Comment by ar1a** [comment]
Seems to work fine, can probably be closed
