### ISSUE TITLE
Add search bindings for helm

### ISSUE THREAD

**Issue by ar1a** [hlissner/doom-emacs#644]
Right now, it looks like

``` emacs-lisp
      (:desc "search" :prefix "/"
        :desc "Project"                :nv "p" #'+ivy/project-search
        :desc "Directory"              :nv "d" (λ! (+ivy/project-search t))
        :desc "Buffer"                 :nv "b" #'swiper
        :desc "Symbols"                :nv "i" #'imenu
        :desc "Symbols across buffers" :nv "I" #'imenu-anywhere
        :desc "Online providers"       :nv "o" #'+lookup/online-select)
```

But obviously with helm enabled, that doesn't work!

**Comment by hlissner** [comment]
And done. This hasn't been thoroughly tested, however. Let me know on Discord if you find any issues!

**Comment by hlissner** [comment]
It appears to only affect the `ag` backnd. 641425a should fix it. Let me know if that isn't the case.

**Comment by ar1a** [comment]
Yeah, that fixed it. Unless something's missing, I think this can be closed.
