### ISSUE TITLE
private snippets can't be loaded

### ISSUE THREAD

**Issue by chengyi** [hlissner/doom-emacs#649]
private snippets can't be loaded
- OS: gnu/linux (x86_64-pc-linux-gnu)
- Emacs: 25.3.2 (9月 13, 2017)
- Doom: 2.0.9 (upstream 6729de9918006942211297adba595196b5df5590)
- Graphic display: t (daemon: nil)
- System features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES
- Details:
  ```elisp
  uname -a:  Linux prowdev 4.13.0-43-generic #48~16.04.1-Ubuntu SMP Thu May 17 12:56:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
  modules:   (:feature (evil  everywhere) file-templates (lookup  devdocs  docsets) snippets spellcheck syntax-checker version-control workspaces :completion ivy :ui doom doom-dashboard doom-modeline doom-quit evil-goggles hl-todo nav-flash neotree vi-tilde-fringe window-select :tools gist make magit pdf rotate-text upload :emacs electric-indent term imenu eshell :lang (cc  irony) data emacs-lisp latex lua markdown (org  attach  babel  capture  export  present  publish) python rust sh :config)
  packages:  n/a
  elc dirs:  n/a
  exec-path: (~/.cargo/bin /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /usr/games /usr/local/games ~/CloseSourceStuff/IDAPro_v6.4 ~/CloseSourceStuff/scitools/bin/linux64 /usr/lib/x86_64-linux-gnu/emacs/25.3/x86_64-linux-gnu)
  ```

**Comment by hlissner** [comment]
Please check the value of `yas-snippet-dirs`. From your system info, I see that `:config (default +snippets)` is disabled, therefore you do not have Doom's default snippet library. By default, it will search for snippets in `~/.doom.d/snippets` (or `~/.config/doom/snippets`, whichever it finds first). Is this where your snippets are stored?

**Comment by chengyi** [comment]
@hlissner Hi, My `yas-snippet-dirs` value is `(+snippets-dir emacs-snippets-dir +file-templates-dir)` and `+snippets-dir` value is `/home/prow/.doom.d/snippets/`. In `/home/prow/.doom.d/snippets` has one snippet called `switch2`, its content is:
``` emacs-lisp
# name: switch-case
# key: myswitch
switch ($1) {
        case $2:
                break;

        default:
                break;
}

```
but in cc-mode, i type `myswitch` and hit `tab`, it doesn't expand. is it doesn't load my snippet?

**Comment by hlissner** [comment]
Is it in the correct directory? e.g. `~/.doom.d/snippets/c++-mode/switch2`? Yasnippet snippets need to follow the `~/.doom.d/snippets/{major-mode}/{snippet}` directory structure. See my [emacs snippets repo](https://github.com/hlissner/emacs-snippets) as an example.

If you want to make a snippet that applies to both c-mode and c++-mode, then create `~/.doom.d/snippets/cc-mode/switch2` and put this in both `~/.doom.d/snippets/c-mode/.yas-parents` and `~/.doom.d/snippets/c++-mode/.yas-parents`:

```
cc-mode
```

**Comment by chengyi** [comment]
@hlissner thanks. it works!
