### ISSUE TITLE
irony completion first placeholder does not disppear when input actual parameters

### ISSUE THREAD

**Issue by chengyi** [hlissner/doom-emacs#650]
when I use irony completion, the first placeholder does not disappear when input actual parameters, if I hit `tab` to the second placeholder,  it works as expected.
pic 1: the cursor stops at first parameter
![_2018-06-04_11-28-16](https://user-images.githubusercontent.com/6308364/40897000-07b680de-67eb-11e8-90ec-434a71f3071b.png)

pic 2: the placeholder won't disappear
![_2018-06-04_11-28-51](https://user-images.githubusercontent.com/6308364/40897030-3432dd24-67eb-11e8-8f13-d84c2a26be10.png)

**Comment by chengyi** [comment]
@hlissner it can reproduce by type `#inc` and select second item in popup tips.
and you will see the `header` placeholder won't disappear. It seems some char can make yasnippet work wrong.

**Comment by hlissner** [comment]
Ah ha! This is because the default snippets are misconfigured. A fix will be up soon.

**Comment by chengyi** [comment]
@hlissner  I test the same include snippiet with custom snippet. However, it works. I guess there is some package conflict with snippet, like smartparen.

**Comment by hlissner** [comment]
I thought I had it, but turns out I didn't. I am having trouble reproducing it again. If you turn off smartparens-mode does the problem go away?

**Comment by chengyi** [comment]
@hlissner i found the `insert-in-front-hooks` not be called when the `comany-irony` package use `yasnippet` expand its cadidate. so the yasnippet won't clear the placeholder overlay.

**Comment by chengyi** [comment]
@hlissner plus switch emacs version to 26.1 solve the problem.
