### ISSUE TITLE
C-c ` runs spell-checker on LaTeX output buffer

### ISSUE THREAD

**Issue by Ptival** [hlissner/doom-emacs#654]
When there is a LaTeX error, C-c ` offers to jump to the error location and show you the error message in a buffer.

However, before the buffer is displayed, some spell-checker is being run, which takes forever (on my laptop) since the buffer is huge (and mostly garbage TeX-specific words).

Is there a way to disable this behavior, globally or locally?

Steps to reproduce:
- open a LaTeX file with garbage, let's say:
```
\documentclass{article}
\usepackage{somethingThatDoesNotExistHopefully}
\begin{document}
\end{document}
```
- `C-c C-c` to compile it
- C-c ` to try and read the error message

**Comment by hlissner** [comment]
If you do `(remove-hook 'flyspell-mode-hook #'+spellcheck|immediately)` does it resolve your issue?

**Comment by Ptival** [comment]
Yeah!

**Comment by UndeadKernel** [comment]
Something changed the behavior of spellchecking LaTeX buffers again.
In the past, this would disable immediate spellchecking on these buffers with the following in my config:
```lisp
(setq-hook! 'LaTeX-mode-hook +spellcheck-immediately nil)
```
This statement is not working anymore. I suspect that the order of the hook calls is at fault.

**Comment by hlissner** [comment]
@Ptival As of 9e85ace, you should be able to add `(setq-hook! 'LaTeX-mode-hook +spellcheck-immediately nil)` to your config and flyspell won't spell-check on startup. If that isn't the case, let me know!
