### ISSUE TITLE
'Selecting deleted buffer' error when closing helm buffer

### ISSUE THREAD

**Issue by maver1** [hlissner/doom-emacs#665]
### Observed behavior

In certain conditions (see reproducer below) emacs got stuck with "Selecting deleted buffer' error preventing opening any other buffers.

Branch is 'develop'.

Backtrace: [backtrace.txt](https://github.com/hlissner/doom-emacs/files/2080616/backtrace.txt)
~/.doom.d contents archive: [doom.d.tar.gz](https://github.com/hlissner/doom-emacs/files/2080629/doom.d.tar.gz)

### Expected behavior

After point 4. in the reproducer below, the helm buffer should be closed, while Imenu sidebar should remain.

### Steps to reproduce

Minimal reproducer:

1. Start emacs
2. Open some file with contents (:e ~/.somefile)
3. Open Imenu sidebar buffer (SPC o i). It should be non-empty to reproduce the bug.
4. Open helm buffer (M-x) and then press ESC
5. See that emacs got stuck with "Selecting deleted buffer' error preventing opening any other buffers.

### System information

<details>
<summary>Click to expand</summary>

```
Emacs v26.1
Doom v2.0.9 (b207c404)
shell: /bin/zsh
Compiled with:
  XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY
  LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS
  GTK3 X11 MODULES THREADS XWIDGETS LIBSYSTEMD LCMS2
uname -a:
  Linux hostname 4.13.0-39-generic #44~16.04.1-Ubuntu SMP Thu Apr 5 16:43:10 UTC
  2018 x86_64 x86_64 x86_64 GNU/Linux
```
</details>

**Comment by hlissner** [comment]
Thank you for this detailed bug report! I've made a number of commits that is likely to have fixed this issue on `develop`. Please update and let me know if the issue persists.

**Comment by maver1** [comment]
Hi Henrik,

Thanks for your work.

The issue is still not gone completely, but it has now slightly different behavior.
After pressing ESC in p.4 helm buffer along with Imenu sidebar are closed, no issues here.
But when you now switch to another buffer (SPC <), the current one is being deleted and same 'Selecting deleted buffer' error appears again.


I'm on:
Doom v2.0.9 (Emacs v26.1)
Branch: develop
Commit: f74d595e1762fa0b87a7591276d9fccef6880e8f.

**Comment by hlissner** [comment]
Could you experiment with the following:

```elisp
(after! helm
  (setq helm-default-display-buffer-functions '(+popup-display-buffer))
  (set-popup-rule! "^\\*helm" :ignore t))
```

And let me know if it resolves your issues?

**Comment by hlissner** [comment]
Further testing indicates that this has solved the issue. Let me know if that isn't the case!
