### ISSUE TITLE
Set fill-column to 50 in git commit messages

### ISSUE THREAD

**Issue by ar1a** [hlissner/doom-emacs#676]
it goes red after 50 anyways, and with fci this gives a bit of a better visual indicator

**Comment by hlissner** [comment]
No can do. The 50-character limit only applies to the summary. The (optional) body of the git commit message can be up to 72 characters long. These conventions are from https://chris.beams.io/posts/git-commit/

**Comment by ar1a** [comment]
Fair enough, although.. we *could* hack it and add a hook to see if the line has been changed, and set it depending on if we're on the first line ;p

**Comment by hlissner** [comment]
fill-column-indicator is a rabbit hole I'm not quite ready to explore. I'll happily accept a PR for a first-line fill column indicator, if you can figure it out. Perhaps there's a better solution out there that doesn't rely on FCI?

In any case, I'll consider this "resolved". Hit me up on Discord if you find out anything.
