### ISSUE TITLE
save-place-mode does not work for the first buffer

### ISSUE THREAD

**Issue by ppwwyyxx** [hlissner/doom-emacs#680]
The saveplace package is only loaded right before switching a buffer:
https://github.com/hlissner/doom-emacs/blob/63a8c307657b03596714cc168f3b3672cc519961/core/core-editor.el#L99-L108

Therefore it does not work for the first buffer opened by emacs.
If I open a file with `emacs a.txt`, the cursor position was not recovered.

**Comment by hlissner** [comment]
If you change `:after-call doom-before-switch-buffer-hook` to `:after-call find-file-hook`, does it resolve your issue?

**Comment by ppwwyyxx** [comment]
Still the same.

**Comment by hlissner** [comment]
What about `:after-hook after-find-file`?

**Comment by hlissner** [comment]
As of 36171f5 this should be fixed. Let me know if that's not the case!
