### ISSUE TITLE
Recursive load error running doom develop branch on alpine linux 37

### ISSUE THREAD

**Issue by linuxing3** [hlissner/doom-emacs#681]
### Observed behavior

`vagrant@alpine ~/m/doom> .emacs.d/bin/doom -p .doom.d/ install
Recursive load: "/usr/share/emacs/26.1/lisp/jka-compr.el.gz", "/usr/share/emacs/26.1/lisp/jka-compr.el.gz", "/usr/share/emacs/26.1/lisp/jka-compr.el.gz", "/usr/share/emacs/26.1/lisp/jka-compr.el.gz", "/usr/share/emacs/26.1/lisp/jka-compr.el.gz", "/usr/share/emacs/26.1/lisp/emacs-lisp/subr-x.el.gz", "/home/vagrant/m
inecraft/doom/.emacs.d/core/core-lib.el", "/home/vagrant/minecraft/doom/.emacs.d/core/core.el", "/home/vagrant/minecraft/doom/.emacs.d/init.el", "/home/vagrant/minecraft/doom/.emacs.d/bin/doom"
`

### Expected behavior

Running `.emacs.d/bin/doom -p .doom.d/ install`

and Start install o refresh

### Steps to reproduce

`.emacs.d/bin/doom -p .doom.d/ install

### System information

+ doom develop branch
+ alpine linux 37 on Virtualbox
+ emacs-nox 26
+ chemacs with profile

**Comment by hlissner** [comment]
Perhaps Emacs can't decompress `jka-compr.el.gz`. Do you have `gzip` installed on that system? And if not, does installing it fix it?

**Comment by linuxing3** [comment]
Thanks for your reply. 
Installed gzip but not fix it.

**Comment by linuxing3** [comment]
I found similar errors in other emacs distribution. Seems like a bug of linux.
[prelude issue](https://github.com/bbatsov/prelude/issues/938)

After add this line in `.emacs.d/init.el`
`(setq load-prefer-newer nil)`

And run 
`doom refresh`

I got
```
⋊> ~/m/cleandoom .emacs.d/bin/doom -p .doom.d/ refresh                                                                                                   21:51:50
Initializing modules
Wrong type argument: hash-table-p, nil
```

**Comment by linuxing3** [comment]
instead of using `doom refresh`

```
make quickstart
make install
``` 
in `.emacs.d` directory started successfully the package install

**Comment by hlissner** [comment]
I've pushed a fix for the `hash-table-p` error, but this `load-prefer-newer` fix is very interesting. Perhaps the built-in elisp libraries were byte-compiled with the wrong/older version of Emacs? Very strange.

**Comment by linuxing3** [comment]
Thanks for the quick fix

**Comment by hlissner** [comment]
Hmm, I can't say I understand the problem, but I'll consider this issue resolved and keep the `load-prefer-newer` solution in mind. Thank you for debugging this and sharing your findings with me!

**Comment by finnoleary** [comment]
For reference: The current Emacs 26.3 build on Alpine Linux is broken and causes the above error (at least on my system) - to the person reading this, if you have the same trouble, you should try doing:

```
git clone --depth 1 git://git.alpinelinux.org/aports
cd aports/community/emacs
export REPODEST=$HOME/.packages
abuild -r
sudo apk add --repository $REPODEST/community emacs
```
