### ISSUE TITLE
Definition lookup in Haskell doesn't work (with intero)

### ISSUE THREAD

**Issue by zeronone** [hlissner/doom-emacs#684]
### Observed behavior
Calling `intero-goto-definition` directly works, but invoking `lookup/definition` fallbacks to tags search. Is it because `intero-goto-definition` is not `autoload`?

### System information

<details>
<summary>Click to expand</summary>

- OS: darwin (x86_64-apple-darwin17.5.0)
- Emacs: 26.1 (May 30, 2018)
- Doom: 2.0.9 (develop cc3fd3126a52b1f66ac9c08814c3299e51849e25)
- Graphic display: t (daemon: nil)
- System features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS
- Details:
  ```elisp
  elc count: 1
  uname -a:  Darwin LF02Q331602A90M.local 17.5.0 Darwin Kernel Version 17.5.0: Fri Apr 13 19:32:32 PDT 2018; root:xnu-4570.51.2~1/RELEASE_X86_64 x86_64
  modules:   (:feature (evil +everywhere) file-templates (lookup +devdocs +docsets) snippets spellcheck (syntax-checker +childframe) version-control workspaces :completion (ivy +fuzzy) :ui doom-dashboard doom-modeline doom-quit evil-goggles fci hl-todo nav-flash neotree (popup +all +defaults) vi-tilde-fringe window-select :emacs ediff electric-indent eshell imenu term :tools gist macos make magit pdf rotate-text tmux upload :lang clojure data erlang elixir elm emacs-lisp go (haskell +intero) javascript lua markdown nix ocaml (org +attach +babel +capture +export +present) perl purescript python rest ruby rust scala sh swift web :collab :config)
  packages:  ((org-wiki :recipe (org-wiki :fetcher github :repo caiorss/org-wiki)))
  exec-path: (~/.cargo/bin/ /usr/local/bin/ /usr/bin/ /bin/ /usr/sbin/ /sbin/ ~/.gem/bin/ ~/.cargo/bin/ ~/.local/bin/ ~/bin/ ~/.sdkman/candidates/springboot/current/bin/ ~/.sdkman/candidates/gradle/current/bin/ ~/Library/Android/sdk/tools/ ~/Library/Android/sdk/platform-tools/ ~/n/bin/ /usr/local/Cellar/emacs-plus/26.1/libexec/emacs/26.1/x86_64-apple-darwin17.5.0/)
  ```
</details>

**Comment by hlissner** [comment]
@zeronone From a haskell buffer with intero-mode, could you report the value of `xref-backend-functions` and `+lookup-definition-functions`?

**Comment by hlissner** [comment]
As of 253fd77 this should be fixed. Please update and let me know if that isn't the case. Thanks for letting me know!

**Comment by zeronone** [comment]
@hlissner Yes that fixed the issue. Thanks
