### ISSUE TITLE
Flycheck for Elm not working

### ISSUE THREAD

**Issue by syvanpera** [hlissner/doom-emacs#686]
### Observed behavior

Some of the latest changes in the develop branch have seem to done something to the Elm flycheck. It no longer displays the checkmark or error mark, just the "waiting" clock icon.

### Steps to reproduce

1. Open an Elm file (with elm feature on)
2. Make any changes and save the file
3. The flycheck icon stays as the clock icon

### System information

<details>
<summary>Click to expand</summary>

- OS: darwin (x86_64-apple-darwin17.5.0)
- Emacs: 26.1 (May 03, 2018)
- Doom: 2.0.9 (develop 6fe0017e24f48c0a815868583ee36ab281b0eb9f)
- Graphic display: t (daemon: nil)
- System features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2
- Details:
  ```elisp
  elc count: 0
  uname -a:  Darwin coruscant.home 17.6.0 Darwin Kernel Version 17.6.0: Tue May  8 15:22:16 PDT 2018; root:xnu-4570.61.1~1/RELEASE_X86_64 x86_64
  modules:   (:feature (evil +everywhere) file-templates (lookup +devdocs +docsets) snippets spellcheck (syntax-checker +childframe) version-control workspaces :completion (ivy +fuzzy) :ui doom-dashboard doom-modeline doom-quit evil-goggles fci hl-todo nav-flash neotree (popup +all +defaults) vi-tilde-fringe window-select :emacs ediff electric-indent eshell imenu term :tools magit pdf rotate-text :lang elixir elm emacs-lisp (haskell +intero) javascript markdown ocaml (org +attach +babel +capture +export +present +publish) purescript web :app :config)
  packages:  (ag all-the-icons-ivy golden-ratio highlight-indent-guides org-gcal org-projectile persistent-scratch reason-mode)
  exec-path: (~/.dotfiles/bin ~/.cargo/bin/ /usr/local/bin/ /usr/bin/ /bin/ /usr/sbin/ /sbin/ /usr/local/share/dotnet/ /Library/Frameworks/Mono.framework/Versions/Current/Commands/ /usr/local/Cellar/emacs-plus/26.1-rc1_1/libexec/emacs/26.1/x86_64-apple-darwin17.5.0/)
  ```
</details>

**Comment by hlissner** [comment]
By chance, does this only affect the first Elm buffer you open?

**Comment by syvanpera** [comment]
Nope, it affects all Elm buffers, not just the first one. And no, update did not fix the issue, but it did bring out a new one also. I'm redefining the fringe markers for flycheck and now I'm getting the error "File mode specification error: (void-function fringe-helper-define)"

**Comment by syvanpera** [comment]
This is still broken in develop. I wonder if I have some settings that affect this?

**Comment by syvanpera** [comment]
@hlissner  I'm still unable to get this working. I tried removing the .local and .cache folders and reinstalled, but Elm flycheck still just showing the clock icon and doing nothing

**Comment by hlissner** [comment]
In an elm buffer, could you try `M-x flycheck-verify-setup` and see what it reports? It should list all the available checkers, whether they're working or not, and, hopefully, why they're disabled/not working.

**Comment by syvanpera** [comment]
Ah. Sorry, forgot about this. Actually this started working at some point when I updated the develop branch. Not sure at which point, though.

**Comment by hlissner** [comment]
No problem, as long as it works! Thanks!
