### ISSUE TITLE
Setting up .doom.d

### ISSUE THREAD

**Issue by chrisalcantara** [hlissner/doom-emacs#689]
I read in another issue the `develop` branch, which I've cloned and installed, suggests moving the `init.el` file to a `.doom.d`  directory at home or in `.config`. 

I've done that. However, I'm not sure how I can install everything if the `Makefile` that controls everything is in `~/.emacs.d/` and my new `init.el` is in `~/.config/.doom.d/`. A little clarification would be greatly appreciated. 

I really like the idea of keeping my custom configurations out of the main repo. Thanks so much for creating this!

**Comment by AloisJanicek** [comment]
Looking at the sources right now, `doom-private-dir` is expected to be in `~/.doom.d` **or** `~/.config/doom` (`doom` without leading dot and without `.d` suffix).  
As you correctly pointed out, you can not run `make` commands from directory without `Makefile`.
In case of doom-emacs, `make` commands executed from `~/.emacs.d/` are also applied to `doom-private-dir`.  
But for most use cases you don't need to directly interact with `make`. If you look at `~/.emacs.d/` after cloning doom-emacs, there is `~/.emacs.d/bin/` directory which contains `doom` executable. When adding this bin directory to `PATH` on your system, you can run `doom` command from everywhere and it will always apply also on `doom-private-dir`.  
You can see all available commands by just executing `doom` (or `doom h`).  
So you should:

1. clone doom-emacs to `~/.emacs.d`
2. switch to `develop` branch
3. copy `~/.emacs.d/init-example.el` to your `doom-private-dir/init.el` (and maybe edit it)
4. run` doom quickstart`
5. start emacs and run `all-the-icons-install-fonts` and restart emacs to pick up changes

**Comment by hlissner** [comment]
As @AloisJanicek suggested, `bin/doom` is the way to go. Doom's makefile is deprecated (and does little else but forward commands to `bin/doom` anyway).

You can run `doom` from anywhere in your system and it will operate on wherever you have Doom installed (typically `~/.emacs.d`).

> I read in another issue the develop branch, which I've cloned and installed, suggests moving the init.el file to a .doom.d directory at home or in .config.

Do not move `~/.emacs.d/init.el`. It is `~/.emacs.d/init.example.el` that you want to copy to `~/.doom.d/init.el`. `~/.emacs.d/init.el` is an important file. Moving it will break Doom!

-----

I'd recommend you use the `doom quickstart` command. it will create your `~/.doom.d/init.el` file and set up Doom for you. It will also leave you with a few post-install notes that may help direct you from there.

You can have it deploy your config to `~/.config/doom` with `doom -p ~/.config/doom quickstart`.

-----

Hope that helps! If you have any questions, feel free to ask! (We also have a [discord server](https://discord.gg/bcZ6P3y) if you'd like assistance in realtime)

**Comment by chrisalcantara** [comment]
Thank you, both. This answered my question.

**Comment by chrisalcantara** [comment]
f
