### ISSUE TITLE
Dired multiple files removal fails.

### ISSUE THREAD

**Issue by Amatrelan** [hlissner/doom-emacs#692]
### Observed behavior

In dired trying to remove multiple files won't work and prints
```
Symbol's value as variable is void: +popup-ttl
```
For single files works fine. No problem there.

### Expected behavior

Expected successfully remove all D tagged files.

### Steps to reproduce

1. Create 2 test files
2. Open folder in dired
3. Press d to tag for delete
4. Press x to execute
5. Press y to accept deletion of multiple files

### System information

<details>
<summary>Click to expand</summary>

- OS: gnu/linux (x86_64-pc-linux-gnu)
- Emacs: 26.1 (May 29, 2018)
- Doom: 2.0.9 (develop d822560b34e514b6e1d1cc037f79e375ce349dd3)
- Graphic display: t (daemon: nil)
- System features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LIBSYSTEMD LCMS2
- Details:

```
elisp
  elc count: 0
  uname -a:  Linux amatelan-laptop 4.14.48-2-MANJARO #1 SMP PREEMPT Fri Jun 8 20:41:40 UTC 2018 x86_64 GNU/Linux
  modules:   (:feature eval (evil +everywhere) file-templates (lookup +devdocs +docsets) snippets spellcheck (syntax-checker +childframe) version-control workspaces :completion (ivy +fuzzy) :ui doom-dashboard doom-modeline doom-quit evil-goggles hl-todo nav-flash neotree (popup +all +defaults) vi-tilde-fringe window-select :emacs ediff electric imenu :tools magit rotate-text :lang (cc +irony) data emacs-lisp markdown (org +attach +babel +capture +export +present) sh :app :config (default +bindings +snippets +evil-commands))
  packages:  n/a
  exec-path: (/usr/local/bin /usr/bin /bin /usr/local/sbin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /usr/lib/emacs/26.1/x86_64-pc-linux-gnu)

```
  
</details>

**Comment by hlissner** [comment]
My bad. This variable was accidentally removed in a recent major commit. I've brought it back in 0fd8e1d, which should resolve your issue. Let me know if that isn't the case!

**Comment by Amatrelan** [comment]
Works fine now! Thanks!
