### ISSUE TITLE
Iosevka ligatures not working

### ISSUE THREAD

**Issue by syvanpera** [hlissner/doom-emacs#695]
I just updated to the latest develop version and was delighted to see the Iosevka font ligature support. But I seem to be getting wrong glyphs for at least the ->. See screenshot.

<img width="367" alt="screen shot 2018-06-18 at 9 20 44" src="https://user-images.githubusercontent.com/281128/41521155-bc117040-72d9-11e8-9e3a-ae1092b78a95.png">

**Comment by hlissner** [comment]
This subtle bug was fixed in https://github.com/hlissner/doom-emacs/commit/ca2c8b5a4592f129619afbaa6810f93538dc42fe. Please update and let me know if that doesn't resolve your issue!

**Comment by jco2** [comment]
I just cloned the develop branch and changed the font in `.doom.d/config.el` to Iosevka. There are no ligatures.
I'm new so that the way I'm supposed to do it ?

**Comment by hlissner** [comment]
To quote @ar1a on [our Discord](https://discord.gg/bcZ6P3y):

> you can't use the proper iosevka font, you have to use a fork

> if you dont wanna compile it, i compiled it here: https://github.com/ar1a/dotfiles/blob/master/emacs/.doom.d/fonts.tar.gz

> and i used this to generate it https://gist.github.com/mrkgnao/49c7480e1df42405a36b7ab09fe87f3d

> it took me ages to get it working so i just bundle compiled fonts :p

**Comment by jco2** [comment]
It did work, that's really nice ! However there are no ligatures in some modes, for instance the tuareg mode.

**Comment by ar1a** [comment]
Posting it here, just in case I remove it from my dotfiles sometime in the future
[fonts.tar.gz](https://github.com/hlissner/doom-emacs/files/2162978/fonts.tar.gz)

**Comment by mustaqimM** [comment]
@ar1a What is actually needed in the font? because my build fails with those settings in `parameters.toml`.

**Comment by ar1a** [comment]
Moves ligatures into private use section
