### ISSUE TITLE
Password manager (pass) won't open

### ISSUE THREAD

**Issue by Amatrelan** [hlissner/doom-emacs#696]
I try to use pass tool for passwords but pass throws a error and wont open password manager.
I have run bin/doom refresh, bin/doom install.

---

### Observed behavior
When I run M-x pass it returns
```
Symbol's value as variable is void: modes
```

```
tools/password-store
Warning: Eager macro-expansion skipped due to cycle:
  … => (load "password-store.el") => (macroexpand-all (defalias (quote password-store--completing-read) …)) => (macroexpand (password-store-list …)) => (load "password-store.el")
 ```

### Expected behavior

I was expecting pass manager to open, after running M-x pass.

### Steps to reproduce

1. Enable password-store in init.el
2. Instal packages with doom/bin refresh
3. Start emacs
4. M-x pass

### System information

<details>
<summary>Click to expand</summary>

```
- OS: gnu/linux (x86_64-pc-linux-gnu)
- Emacs: 26.1 (May 29, 2018)
- Doom: 2.0.9 (develop 0d925cda5e1a4cb934e3afeb28a4685b9b1c1519)
- Graphic display: t (daemon: nil)
- System features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LIBSYSTEMD LCMS2
- Details:
  ```elisp
  elc count: 0
  uname -a:  Linux amatelan-laptop 4.14.48-2-MANJARO #1 SMP PREEMPT Fri Jun 8 20:41:40 UTC 2018 x86_64 GNU/Linux
  modules:   (:feature (evil +everywhere) file-templates (lookup +devdocs +docsets) snippets spellcheck (syntax-checker +childframe) version-control workspaces :completion (ivy +fuzzy) :ui doom-dashboard doom-modeline doom-quit evil-goggles hl-todo nav-flash neotree (popup +all +defaults) vi-tilde-fringe window-select :emacs ediff electric imenu :tools magit password-store rotate-text :lang data emacs-lisp markdown (org +attach +babel +capture +export +present) sh :app :config)
  packages:  n/a
  exec-path: (/usr/local/bin /usr/bin /bin /usr/local/sbin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /usr/lib/emacs/26.1/x86_64-pc-linux-gnu)
  ```
```
</details>

**Comment by hlissner** [comment]
Please update, turn on `M-x toggle-debug-on-error` and invoke the bug again. A backtrace would be tremendously helpful in debugging this.

**Comment by Amatrelan** [comment]
```
Warning: Eager macro-expansion skipped due to cycle:
  … => (load "password-store.el") => (macroexpand-all (defalias (quote password-store--completing-read) …)) => (macroexpand (password-store-list …)) => (load "password-store.el")
Eager macro-expansion failure: (void-variable modes)
if: Symbol’s value as variable is void: modes
Debug on Error enabled globally
Entering debugger...
or: Wrong type argument: symbolp, (lambda nil (progn (if (listp modes) (dolist (mode modes) (evil-set-initial-state mode state)) (evil-set-initial-state modes state))))
```

Well I did "clean" install again (used own config and init).
- Download develop branch
- bin/doom install
- Opened emacs
- M-x pass still returns error.
Are you using what version of pass? I'm using 1.7.1.1 from Arch Linux community

**Comment by hlissner** [comment]
I just pushed two fixes. One for the `wrong-type-argument: symbolp` error, and one for the macro-expansion error. They should resolve your issue. Please update and let me know if they haven't!

**Comment by Amatrelan** [comment]
Works! Thanks again!

**Comment by hlissner** [comment]
I prefer to keep them open, _unless_ I am fixing a regression introduced _after_ the last release. Since Doom is in a strange 2k commit limbo, don't worry about it, haha. I'll close these once 2.1 is out, which is any day now.
