### ISSUE TITLE
Loading sessions with `+workspace/load-session` does not start from a clean session

### ISSUE THREAD

**Issue by UndeadKernel** [hlissner/doom-emacs#700]
### Observed behavior

When loading a whole workspace session with `+workspace/load-session`, the loaded session is not loaded cleanly. That is, old workspaces remain. Is this intended behavior? Is there a way to open a new session and close all others?

Also, when the new loaded session shares names with any workspace in the old session, the order of the "tabs" different than what is in the session. 

### Expected behavior

When loading a new session, only workspaces of the new session should be shown. Or is this not intended behavior?

**Comment by hlissner** [comment]
As of d979c46ea225fd3e68f351a41daf92b7bc9f74c7 and 8cb36afa21f81ffa9b86b3059b42798be681f6f7, this is resolved. Thanks for letting me know!
