### ISSUE TITLE
Suggestion: a couple more modeline truncation options

### ISSUE THREAD

**Issue by Ptival** [hlissner/doom-emacs#709]
Hey, this is not a huge deal, but allow me to make my case! :-)

I am currently working on a project that has stupidly-long namespaces (kind of like Java...) in Haskell. For instance, I can be working on such files as:

```
language-ocaml/test/Language/OCaml/Parser/Implementation/Test.hs
language-ocaml/test/Language/OCaml/PrettyPrinter/Implementation/Test.hs
language-ocaml/lib/Language/OCaml/Parser/Implementation.hs
language-ocaml/lib/Language/OCaml/PrettyPrinter/Implementation.hs
```

Unfortunately, the available options for `+doom-modeline-buffer-file-name-style` are never satisfactory:

`truncate-upto-project` shortens nothing.
`truncate-upto-root` only shortens the very first part (`language-ocaml`), but I still have the stupidly-long folders.
`truncate-all` gives:
```
l/t/L/O/P/I/Test.hs
l/t/L/O/P/I/Test.hs
l/l/L/O/P/Implementation.hs
l/l/L/O/P/Implementation.hs
```
which is too short to make sense of, and has collisions...

The relative options don't help much since most of the path is in the project.

What I would consider interesting alternatives:

- defining the truncation length, for instance, I'd love a truncation length of 3:
```
lan/tes/Lan/OCa/Par/Imp/Test.hs
lan/tes/Lan/OCa/Pre/Imp/Test.hs
lan/lib/Lan/OCa/Par/Implementation.hs
lan/lib/Lan/OCa/Pre/Implementation.hs
```

- being able to truncate keeping only uppercase letters, or dash/underscore-separated initials, for instance:
```
l-o/t/L/OC/P/I/Test.hs
l-o/t/L/OC/PP/I/Test.hs
l-o/l/L/OC/P/Implementation.hs
l-o/l/L/OC/PP/Implementation.hs
```

- truncating up to parent folder:
```
l/t/L/O/P/Implementation/Test.hs
l/t/L/O/P/Implementation/Test.hs
l/l/L/O/Parser/Implementation.hs
l/l/L/O/PrettyPrinter/Implementation.hs
```

Have you considered any of these? I'd be happy trying to write some implementation if you'd like help, and would be happy adding them in the mix.

Best regards, thanks for all the hard work! <3

**Comment by hlissner** [comment]
I have run up against this problem myself, so I'd happily welcome a PR for these. The 2.1 release has me swamped, so I'd appreciate the help.

**Comment by bandresen** [comment]
I can see the use case. I will be having a look at bringing out a new version of [shrink-path](https://gitlab.com/bennya/shrink-path.el) that has new functions to allow for more options.

**Comment by hlissner** [comment]
Since this has been implemented in `:ui doom-modeline` and the new `:ui modeline` module (which will eventually replace `:ui doom-modeline` when Doom drops Emacs 25 support), I'll consider this resolved.

`:ui modeline` has the `+modeline-buffer-path-function` variable, which lets you use one of the predefined path builder functions or define your own.
