### ISSUE TITLE
Strange indentation behavior

### ISSUE THREAD

**Issue by bitwalker** [hlissner/doom-emacs#727]
### Observed behavior

Given the following code (the actual code isn't important, I just want to illustrate with an example):

```elixir
def is_nil(arg) do
  case arg do
    nil -> true
    _ -> false
  end
end
```

If I want to change that to the following:

```elixir
def is_nil(arg) do
  result =
    case arg do
      nil -> true
      _ -> false
    end
  result
end
```

What I want to do is use visual mode to select the `case` block, and indent the block with `> >`, preserving the indentation. What happens though is I get this:

```elixir
def is_nil(arg) do
      case arg do
      nil -> true
      _ -> false
      end
end
```
It is indenting the `case` and `end` lines 4 spaces, and the inner clauses 2 spaces, which results in them all on the same line. I've noticed this behavior in `elixir-mode`, `erlang-mode`, `python-mode`, but it doesn't seem to occur in `go-mode`. I only say this to clarify that this appears to not be major mode specific, but some configuration related thing.

### Expected behavior

Using the example above, I'd expect all lines of the visual selection to be indented the same number of spaces/tabs the major mode is configured to use (2 spaces in the case of `elixir-mode`). Ultimately, the desired behavior is that I can indent a selection, preserving the relative indentation of the selection.

### Steps to reproduce

1. Open up an `elixir-mode` buffer, dump in the initial code example from above
2. Starting at `case`, perform a visual selection to the `end`
3. Use `> >` to indent the selection

### System information

<details>
<summary>Click to expand</summary>

- OS: darwin (x86_64-apple-darwin16.7.0)
- Emacs: 26.1 (Jun 24, 2018)
- Doom: 2.0.9 (develop c8de34fb55d8739df3dde0dad5a7114b1034a63e)
- Graphic display: t (daemon: nil)
- System features: JPEG RSVG IMAGEMAGICK DBUS NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2
- Details:
  ```elisp
  elc count: 0
  uname -a:  Darwin ogier.local 16.7.0 Darwin Kernel Version 16.7.0: Tue Jan 30 11:27:06 PST 2018; root:xnu-3789.73.11~1/RELEASE_X86_64 x86_64
  modules:   (:feature (evil +everywhere) file-templates (lookup +devdocs +docsets) snippets spellcheck (syntax-checker +childframe) workspaces :completion (ivy +fuzzy) :ui doom-dashboard doom-modeline doom-quit evil-goggles hl-todo nav-flash neotree (popup +all +defaults) unicode vi-tilde-fringe window-select vc-gutter :editor :emacs ediff electric eshell imenu vc :tools gist make magit pdf prodigy upload :lang (cc +irony +rtags) data erlang elixir emacs-lisp go (haskell +intero) (java +meghanada) javascript (latex +latexmk +skim +pdf-tools) lua markdown ocaml (org +attach +babel +capture +export +present) perl purescript python ruby rust scala sh web :config :private fish)
  packages:  ((exec-path-from-shell :ignore (not IS-MAC)) fish-mode terraform-mode)
  exec-path: (~/.asdf/shims/ ~/.asdf/bin/ ./node_modules/.bin/ ~/bin/ ~/bin/ /usr/local/bin/ /usr/local/bin/ /usr/bin/ /bin/ /usr/sbin/ /sbin/ /Library/TeX/texbin/ ./node_modules/.bin/ ~/bin/ /usr/local/Cellar/emacs-plus/26.1/libexec/emacs/26.1/x86_64-apple-darwin16.7.0/)
  ```
</details>

**Comment by hlissner** [comment]
Could you tell me the value of `evil-shift-width` in elixir-mode, and whether it matches the value of `tab-width`?

Evil's `>>` and `<<` are governed by `evil-shift-width`, and this sounds like they are out of sync.

**Comment by bitwalker** [comment]
So, in an `elixir-mode` buffer, evaluating `evil-shift-width` and `tab-width` both return 4, which should be 2; but things are even stranger than I thought:

Given the following in my scratch buffer with `elixir-mode` active:

```elixir
defmodule Test do
  def is_nil(arg) do
    case arg do
      nil -> true
      _ -> false
    end
  end
end
```

- Dedent of the `def` line goes to the beginning of the line (column 0), which is a dedent of 2 spaces; indenting that same line again indents 4 spaces.
- Dedent of the `case` line goes to the beginning of the line, which is a dedent of 4 spaces; indenting that same line again indents 4 spaces.
- Dedent of the `nil -> true` line, dedents 2 spaces; indenting it again indents 4 spaces
- Going back to the `def` line, if I indent it, it indents 2 spaces (!!); whereas if I reset it to the default state, dedent to the beginning of the line, then indent twice, it indents 4 spaces both times.

The last two of those are the ones which confuse me the most, since the dedent/indent behavior seems to change based on context or some kind of state.

Hope that helps, if you need me to try anything, just let me know!

**Comment by hlissner** [comment]
The incorrect `tab-width` is the root of the problem (and `evil-shift-width` for your `<<` and `>>` woes). 

It doesn't get properly occurs because of a bug in `dtrt-indent` (what Doom uses to automatically detect and set indentation). I've filed a bug report upstream and will report back here when it has been resolved.

In the meantime, you could set `tab-width` file-locally, e.g.

```ruby
# Local Variables:
# coding: utf-8
# tab-width: 2
# End:
```

At the bottom of the file, or

```ruby
# -*- tab-width: 2 -*-
```

at the top.

Or, if you use the `:tools editorconfig` module, have this to your `~/.editorconfig` file:

```editorconfig
[*.rb]
indent_size = 2
```

**Comment by bitwalker** [comment]
I've updated `dtrt-indent` and pulled the latest from develop and so far so good! I'll close this, but feel free to reopen it if you want it around for tracking purposes.
