### ISSUE TITLE
(bug) putting cursor on lint warning in *.js file gives blank screen

### ISSUE THREAD

**Issue by dmitriyK1** [hlissner/doom-emacs#728]
### Observed behavior

Screen goes blank and Emacs freezes after positioning cursor on a lint warning in *.js file in fullscreen mode and pressing Escape a few times

![image](https://user-images.githubusercontent.com/3366893/41901908-d15eeb96-793a-11e8-9552-0f82a81f83d1.png)

Here's a sample project:
[https://github.com/dmitriyK1/sample](https://github.com/dmitriyK1/sample)

### Steps to reproduce
1. enable javascript in init.el
2. npm install
3. make Emacs window fullscreen
4. open index.js
5. put cursor on warning, press escape a few times

### System information
macOS High Sierra 10.13.5
GNU Emacs 26.1 (installed via ```brew cask install emacs```)

- OS: darwin (x86_64-apple-darwin14.5.0)
- Emacs: 26.1 (May 31, 2018)
- Doom: 2.0.9 (develop af41e1735590597545f83c290bd706523cef8884)
- Graphic display: t (daemon: nil)
- System features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS
- Details:

<details>
<summary>Click to expand</summary>

```elisp
  elc count: 0
  uname -a:  Darwin localhost 17.6.0 Darwin Kernel Version 17.6.0: Tue May  8 15:22:16 PDT 2018; root:xnu-4570.61.1~1/RELEASE_X86_64 x86_64
  modules:   (:feature (evil +everywhere) file-templates (lookup +devdocs +docsets) snippets spellcheck (syntax-checker +childframe) workspaces :completion (ivy +fuzzy) :ui doom-dashboard doom-modeline doom-quit evil-goggles hl-todo nav-flash neotree (popup +all +defaults) vc-gutter vi-tilde-fringe window-select :editor :emacs ediff electric imenu vc :tools magit :lang emacs-lisp javascript markdown (org +attach +babel +capture +export +present) sh :config)
  packages:  n/a
  exec-path: (~/.cargo/bin/ ~/.git-semantic-commits/ ~/.emacs.d/bin/ /usr/local/opt/fzf/bin/ /Applications/Emacs.app/Contents/MacOS/bin-x86_64-10_10/ /Applications/Emacs.app/Contents/MacOS/libexec-x86_64-10_10/ /usr/local/bin/ /usr/bin/ /bin/ /usr/sbin/ /sbin/ /opt/X11/bin/ /usr/local/share/dotnet/ /usr/local/go/bin/ /Library/Frameworks/Mono.framework/Versions/Current/Commands/ /Applications/Emacs.app/Contents/MacOS/libexec/)
```
</details>

**Comment by dmitriyK1** [comment]
Thanks for help!
Disabling ```+childframe``` helped to fix screen going black and both options you provided worked equally well for me to enable fullscreen mode

Side effect of disabling ```+childframe``` is inline rendering of warning and addition of multiple blank lines at the end of the file (if code with a warning is at the end of the file) like this:
![image](https://user-images.githubusercontent.com/3366893/41985375-d1c44fe8-7a3b-11e8-8fcb-065cdfb74543.png)

Would be nice to find a way to show warnings in the status line, but this is not critical so thanks anyway :)

**Comment by hlissner** [comment]
Unfortunately, the blank lines are unavoidable with `flycheck-popup-tip`. If you disable `flycheck-popup-tip`, errors/warnings will be shown in the minibuffer, rather than with popups.

```elisp
;; ~/.doom.d/packages.el
(package! flycheck-popup-tip :disable t)
```

(then run `bin/doom refresh`)

**Comment by dmitriyK1** [comment]
Thanks for your help! Now everything works as I wanted 👍
