### ISSUE TITLE
Make Emacs state behave like regular Emacs

### ISSUE THREAD

**Issue by deech** [hlissner/doom-emacs#734]
Is there a way to make `emacs-state` (`C-z`) behave exactly like vanilla Emacs (with the exception of `C-z` reverting to normal mode)? Currently some useful keybindings like `M-f` (forward-word) don't work in Emacs state.

Thanks for a wonderful config!

**Comment by hlissner** [comment]
Sorry about that! There were many keys bound in the emacs state that weren't thought through at the time. I've removed most of them, so emacs state should behave as you expect again. The only exception are `C-h`, `C-j`, `C-k` and `C-l` (for moving between windows), which I wasn't sure about.

I'll consider this resolved for the time being. Let me know if things aren't working as you expect!
