### ISSUE TITLE
develop branch does not compile

### ISSUE THREAD

**Issue by JanPappert** [hlissner/doom-emacs#735]
### Observed behavior

Just tried to compile the develop branch, throws the following error>

> Symbol’s function definition is void: doom!
> make: *** [Makefile:20: quickstart] Error 255

master branch works fine

**Comment by hlissner** [comment]
Did you copy `~/.emacs.d/init.example.el` to `~/.emacs.d/init.el`? The installation steps have changed on the develop branch (and are reflected in the README on the develop branch), but it is a common mistakes to read the README on `master` while installing Doom from the develop branch (sorry about that! I'll be merging very soon).

Anyhow, to fix this, reset `~/.emacs.d/init.el` and only run `make quickstart`.

**Comment by hlissner** [comment]
I'll assume this resolved your issue. Feel free to reopen if that isn't the case.
