### ISSUE TITLE
Invalid face line-number when using fci

### ISSUE THREAD

**Issue by ocharles** [hlissner/doom-emacs#738]
### Observed behavior

When enabling the `fci`, I get `File mode specification error: (error Invalid face line-number)` whenever I open a new file. Magit is unable to open a commit buffer due to this error, also.

### Expected behavior

Opening a file throws no errors and has a fill column indicator.

### Steps to reproduce

1. Use my [`.doom.d`](https://github.com/ocharles/dotcharles/tree/2944d1a8c03bda24fb5970c9bbd182cce4a206ce/doom.d)
2. Enable fci in `doom.d/init.el`.

### System information

<details>
<summary>Click to expand</summary>

- OS: gnu/linux (x86_64-pc-linux-gnu)
- Emacs: 25.3.1 (Apr 02, 2018)
- Doom: 2.0.9 (develop 637131a264ea2cf4784a33fbcc6584e6374a6bab)
- Graphic display: nil (daemon: nil)
- System features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES
- Details:
  ```elisp
  elc count: 0
  uname -a:  Linux nixos 4.14.51 #1-NixOS SMP Wed Jun 20 19:03:02 UTC 2018 x86_64 GNU/Linux
  modules:   (:feature spellcheck workspaces :completion (ivy +fuzzy) :ui doom-dashboard doom-modeline doom-quit evil-goggles fci hl-todo nav-flash neotree (popup +all +defaults) pretty-code vi-tilde-fringe window-select vc-gutter :editor :emacs ediff electric imenu vc :tools gist magit :lang elm emacs-lisp haskell markdown nix (org +attach +babel +capture +export +present) sh :app :config)
  packages:  (dhall-mode direnv)
  exec-path: (~/bin /run/wrappers/bin /etc/profiles/per-user/ollie/bin ~/.nix-profile/bin /nix/var/nix/profiles/default/bin /run/current-system/sw/bin /nix/store/fvgvj6vr36va8567nd0d00f1i94vlc43-emacs-25.3/libexec/emacs/25.3/x86_64-pc-linux-gnu)
  ```
</details>

**Comment by hlissner** [comment]
The `line-number` face didn't exist in Emacs 25, causing this error.

As of 2468694 this should be fixed. Let me know if that isn't the case!
