### ISSUE TITLE
Multiple universal arguments do not work when called with SPC u

### ISSUE THREAD

**Issue by sassjajc** [hlissner/doom-emacs#747]
Multiple universal arguments (i.e. C-u C-u ...) do not work when called with SPC u SPC u.
After a lot of searching, I eventually found a solution in spacemacs [keybinding.el](https://github.com/syl20bnr/spacemacs/blob/bd7ef98e4c35fd87538dd2a81356cc83f5fd02f3/layers/%2Bdistributions/spacemacs-base/keybindings.el#L106).

Adapted to work with doom it looks like this:

``` elisp
(define-key universal-argument-map (kbd (concat doom-leader-key " u")) 'universal-argument-more)
```

Personally, I put it in the Keybinding Fixes section of +bindings.el

**Comment by hlissner** [comment]
A great idea! I've implemented it in 6829f6f, so it should work again. Thanks for letting me know!
