### ISSUE TITLE
failed to disable packages

### ISSUE THREAD

**Issue by scturtle** [hlissner/doom-emacs#749]
I tried setting `doom-disabled-packages` manually or using `disable-packages!` but packages are still being installed and enabled.

Should this line https://github.com/hlissner/doom-emacs/blob/e2442e7d80c16e0d80e90cd62cbca1d2c10b2e14/core/core-packages.el#L222 be
```lisp
`((if (not (memq ',name doom-disabled-packages))
   (setf (alist-get ',name doom-packages) ',plist))
```
?

**Comment by hlissner** [comment]
That line is correct. There should be an entry for every package in `doom-packages` regardless of whether they are disabled or not. That is intentional.

What package are you trying to disable?

**Comment by scturtle** [comment]
I see. So disabled packages are always installed. It seems that after changing `(disable-packages! ...)` in my packages.el, I need to `make autoloads` to make them actually disabled. That solves my problem. Thanks!
