### ISSUE TITLE
Wrong type argument: commandp, +term/open

### ISSUE THREAD

**Issue by JanPappert** [hlissner/doom-emacs#756]
I get the above error when trying to open a terminal using SPC-o-t.
Same thing happens for Imenu sidebar.

Working on a fresh developer branch. I can open term using M-x just fine and I alreadz tried make autoload.

Cheers
Jan

**Comment by hlissner** [comment]
Did you run `make` (or `bin/doom refresh`) after enabling `:emacs term` and `:emacs imenu`?

**Comment by hlissner** [comment]
Also, please run `M-x doom/info` and paste it in here.

**Comment by JanPappert** [comment]
Hi, thanks for your reply!

I found the option to enable Iemacs term in init.example.el. However, I followed your new installation instructions for the developing branch, in which I must no longer cp init.example.el init.el.

Do I have to enable these options at a different place?

(I can still post M-x doom/info, but I'm fairly confident that you are correct about the :emacs term option)

Cheers

**Comment by hlissner** [comment]
On the develop branch (and onwards), personal configuration goes into `~/.doom.d` (or `~/.config/doom`, if it exists). So to enable `:emacs term`, you'll want to look at `~/.doom.d/init.el` (which is where init.example.el is now copied to).

Hope that helps!

**Comment by JanPappert** [comment]
Perfect, thank you so much, this resolves the issue for me!

Quick note on org-mode and the agenda: Do you have some system in place that would collect todo items and show them in the agenda?
I have some settings that I previously used in my manual emacs config, but I strongly suspect that there already exists a more elegant way to handle this in your project..
Currently tasks will show up in a file in `~/org/`, but are not visible in the agenda.

Cheers

**Comment by JanPappert** [comment]
For those who might see this later:
```
(after! org
  (setq org-agenda-files (list "~/org/todo.org" "~/org/notes.org")))
```
