### ISSUE TITLE
rtags doesn't work with ivy unless it is reloaded

### ISSUE THREAD

**Issue by benj02** [hlissner/doom-emacs#768]
### Observed behavior

![Screencast](https://ben-johnson.me/doom.gif)

When using the `+lookup` functions in `c++-mode`, which calls functions `rtags-find-symbol-at-point` and `rtags-find-references-at-point`, if there are multiple results, all you get is a message in the echo area saying `RTags: Found n locations.`

If you open up `rtags.el` and eval the buffer, then the expected behavior occurs afterwards.

### Expected behavior

Ivy should open up with the list of locations.

### System information

<details>
<summary>Click to expand</summary>

- OS: gnu/linux (x86_64-pc-linux-gnu)
- Emacs: 26.1 (Jul 05, 2018)
- Doom: 2.0.9 (develop e865526c75c307b8a2cf48fcf7a018364b8660e7)
- Graphic display: t (daemon: nil)
- System features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LIBSYSTEMD LCMS2
- Details:
  ```elisp
  elc count: 0
  uname -a:  Linux thinkpad 4.17.8-1-zen #1 ZEN SMP PREEMPT Wed Jul 18 09:56:17 UTC 2018 x86_64 GNU/Linux
  modules:   (:feature eval (evil +everywhere) file-templates (lookup +devdocs +docsets) snippets spellcheck (syntax-checker +childframe) workspaces :completion (ivy +fuzzy) :ui doom doom-dashboard doom-modeline doom-quit evil-goggles fci hl-todo nav-flash neotree (popup +all +defaults) vi-tilde-fringe window-select :editor :emacs dired ediff electric eshell imenu term :tools make (magit +hub) pdf tmux upload :lang (cc +irony +rtags) crystal clojure csharp data elixir elm emacs-lisp ess go (haskell +intero) hy (java +meghanada) javascript julia (latex +pdf-tools) ledger lua markdown nim nix ocaml (org +attach +babel +capture +export +present) perl php plantuml purescript python rest ruby rust scala sh swift web :collab impatient-mode :config)
  packages:  n/a
  exec-path: (/usr/local/bin /usr/local/sbin /usr/bin /opt/flutter/bin /usr/lib/jvm/default/bin /opt/openresty/bin /opt/openresty/nginx/sbin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /usr/lib/emacs/26.1/x86_64-pc-linux-gnu)
  ```
</details>

**Comment by hlissner** [comment]
If you delete rtags.elc and restart Emacs, does this fix the problem?

```elisp
(delete-file (locate-library "rtags.elc"))
```

**Comment by benj02** [comment]
That didn't help, but some change made in the last few days did. After a pull and make it works again

**Comment by hlissner** [comment]
Very odd. I'll consider this resolved in the meantime. Feel free to reopen this if the issue resurfaces.
