### ISSUE TITLE
Mode-dependent font

### ISSUE THREAD

**Issue by beojan** [hlissner/doom-emacs#769]
Can I make the buffer font mode-dependent? I have two versions of Iosevka, one with just the `calt` ligatures and one with the Haskell ligatures, and I'd like to use the Haskell version for haskell-mode only.

**Comment by hlissner** [comment]
You could, with `face-remap`. Something like:

```elisp
(defface my-haskell-default-face '((t (:inherit default :family "Iosevka version 2"))))

(add-hook! 'haskell-mode-hook (face-remap-add-relative 'default 'my-haskell-default-face))
```

I haven't tested this so no guarantees, but this _might_ conflict with `solaire-mode` (which does something similar).

**Comment by beojan** [comment]
I had to change it to
```
(defface my-haskell-default-face 
  '((t (:inherit default :family "Iosevka Haskell")))
   "Haskell default face") ; replace font name

(add-hook! 'haskell-mode-hook (face-remap-add-relative 'default 'my-haskell-default-face))
```

But it seems to work.

**Comment by hlissner** [comment]
I'm glad to hear it's working! In that case I'll consider this issue resolved.
