### ISSUE TITLE
LaTeX Refactoring: default view program is always `preview-pane`

### ISSUE THREAD

**Issue by UndeadKernel** [hlissner/doom-emacs#776]
The binding `C-c C-v` calls the function `TeX-view`.  This function would normally open the user-specified view program without asking anything. With the LaTeX configuration after the big refactoring, `preview-pane` tries to be called disregarding what the user sets in `+latex-viewers`.

This issue is caused by the statements (in the file `+viewers.el`):
```lisp
;; fall back to latex-preview-pane
(add-to-list 'TeX-view-program-list '("preview-pane" latex-preview-pane-mode))
(add-to-list 'TeX-view-program-selection '(output-pdf "preview-pane"))
```
which appear too late in the "view selection" process.

**Comment by hlissner** [comment]
This should be fixed as of cf4ea445, 14816ef1, and 128eb611. Thanks for letting me know!
