### ISSUE TITLE
Python's package for "+pyvenv" should be "pyvenv" instead of "pyvenv-mode"

### ISSUE THREAD

**Issue by fcobos** [hlissner/doom-emacs#777]
`Installing pyvenv-mode
  FATAL ERROR: (error Package ‘pyvenv-mode-’ is unavailable)
  Run again with the -d flag for details`

The actual package is [here](https://melpa.org/#/pyvenv)

**Comment by hlissner** [comment]
My bad! This is now fixed. Thanks for letting me know!
