### ISSUE TITLE
Corruption in right fringe where scrollbar would be

### ISSUE THREAD

**Issue by beojan** [hlissner/doom-emacs#789]
![image](https://user-images.githubusercontent.com/3727925/43840371-cf3879b0-9b20-11e8-9c22-9c87f8974b3f.png)

**Comment by hlissner** [comment]
I've encountered this a number of times and suspect it is an Emacs issue. Possibly to do with Emacs resizing the frame when it loads `doom-font` at startup. 

You could unsetting `doom-font` and see if the issue goes away. Otherwise, resizing the frame typically fixes this.

**Comment by ocharles** [comment]
I started getting this when I updated to Emacs 26 so I'm not sure it's Doom specific. I fix it by changing virtual desktops.

**Comment by vikigenius** [comment]
I have this same issue in emacs26 too. I am using a tiling window manager (i3). I just resize or switch to fullscreen and back as a workaround.

**Comment by hlissner** [comment]
I'll close this because I suspect it isn't a Doom issue, but rather a problem with Emacs itself or certain window managers.
