### ISSUE TITLE
global-command-log-mode is bound but doesn't exist

### ISSUE THREAD

**Issue by duog** [hlissner/doom-emacs#791]
`global-command-log-mode` is bound to `SPC h L`, but doesn't exist.

It seems that command-log-mode is made global by the defcustom
`command-log-mode-is-global`.

### Steps to reproduce

1. Start doom.
2. Enter `SPC h L`
3. Observe "command-execute: Wrong type argument: commandp,
global-command-log-mode" in the echo area.

### System information

<details>
<summary>Click to expand</summary>

- OS: gnu/linux (x86_64-pc-linux-gnu)
- Emacs: 26.1 (Jul 29, 2018)
- Doom: 2.0.9 (feature/lsp 6f2cb63d870ec33dce37edbb9d5895b54cfaf1f1)
- Graphic display: t (daemon: t)
- System features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS
- Details:
  ```elisp
  elc count: 0
  uname -a:  Linux tyrion 4.14.51 #1-NixOS SMP Wed Jun 20 19:03:02 UTC 2018 x86_64 GNU/Linux
  modules:   (:feature (evil +everywhere) file-templates (lookup +devdocs +docsets) snippets spellcheck (syntax-checker +childframe) workspaces :completion (helm +fuzzy +childframe) :ui doom-dashboard doom-modeline doom-quit evil-goggles hl-todo nav-flash treemacs (popup +all +defaults) vc-gutter vi-tilde-fringe window-select :editor :emacs ediff electric imenu term vc :tools gist make magit password-store pdf tmux :lang (cc +irony +rtags) clojure common-lisp csharp data erlang elixir elm emacs-lisp ess go (haskell +intero) hy javascript julia latex lua markdown nix (org +attach +babel +capture +export +present) perl php purescript python rest rust scala (sh +fish) swift web :app irc (rss +org) (write +wordnut +langtool) :config)
  packages:  n/a
  exec-path: (~/bin ~/.local/bin ~/.emacs.d/bin /run/wrappers/bin /etc/profiles/per-user/doug/bin ~/.nix-profile/bin /nix/var/nix/profiles/default/bin /run/current-system/sw/bin /nix/store/q7541ph9clzkvrkjxn781ig4c5jpsck8-emacs-26.1/libexec/emacs/26.1/x86_64-pc-linux-gnu)
  ```
</details>

**Comment by hlissner** [comment]
Good catch! This should be fixed as of 541ce81. Feel free to reopen this if that isn't the case.

**Comment by duog** [comment]
That does work. I'm reopening because the command fails when executed inside a popup buffer.

To reproduce:
* `SPC x` to popup and switch to a scratch buffer
* `SPC h L` to enable Command Log
* Observe `Error in post-command-hook (global-command-log-mode-check-buffers): (error "Cannot split side window or parent of side window")` in the echo area.



Error in post-command-hook (global-command-log-mode-check-buffers): (error "Cannot split side window or parent of side window")

**Comment by hlissner** [comment]
Sorry for the late response; I missed your follow up. I removed command-log-mode in c0d2ab331ec3, so I'll close this issue. It's also been quite a long time, the underlying cause of this issue was likely resolved in that time.

> Error in post-command-hook (global-command-log-mode-check-buffers): (error "Cannot split side window or parent of side window")

This error typically occurs when you try to split a popup window.
