### ISSUE TITLE
Rails mode freeze

### ISSUE THREAD

**Issue by idoo** [hlissner/doom-emacs#793]
Here are some things you should try before filing a bug report:

I made a fresh install of doom-emacs, switched to `develop` branch, enabled `ruby` and started the project

now, when emacs suggest me select rails console mode it just freezes on this step (when I press enter)

<img width="345" alt="screen shot 2018-08-09 at 08 05 28" src="https://user-images.githubusercontent.com/738921/43879105-118994e0-9bab-11e8-8486-a8a490529047.png">

Do you have any ideas on how I could debug it?

**Comment by idoo** [comment]
@hlissner do you have any ideas how I can debug it?

**Comment by vemv** [comment]
Might help: https://github.com/syl20bnr/spacemacs/wiki/Debugging#debug-a-freezing-instance

**Comment by hlissner** [comment]
@idoo Sorry for the late reply. 

Try doing `M-x toggle-debug-on-quit`, reproducing this freeze, and pressing `C-g` to try to abort it (which will produce a backtrace). Pastebin that backtrace and post the link here. Hopefully it will shed some light on what's causing this.

**Comment by idoo** [comment]
@vemv @hlissner thank you for advice — here is my logs

https://gist.github.com/idoo/312bc8bd792e1358e7965f0ffaa86f4d

**Comment by idoo** [comment]
any ideas?

**Comment by idoo** [comment]
@hlissner are you using rbenv or rvm?

**Comment by hlissner** [comment]
@idoo Sorry for the late reply. I've been preoccupied with a move. I should be settled by tomorrow to look into this a little deeper.

To answer your question, I use rbenv.

**Comment by idoo** [comment]
I try to set `development` as default `inf-ruby-console-rails` env, but still no luck here

but it works well when I few times press esc (when emacs ask me to run console automatically) and run console myself

probably some path is wrong, but messages still empy :(

**Comment by idoo** [comment]
@hlissner just let me know if I can help you somehow

**Comment by idoo** [comment]
wow! looks it works now! thanks!
