### ISSUE TITLE
Cannot load eslint from node_modules

### ISSUE THREAD

**Issue by hackeryarn** [hlissner/doom-emacs#798]
### Observed behavior

`flycheck` is not able to use `eslint` from `node_modules`.

Seems that the `node_modules` are not getting added to the `exec-path`.

The info below is from a javascript project with `node_modules` and `package.json` at root.

### Expected behavior

`flycheck` can pickup `eslint` binary from `node_modules`.

### Steps to reproduce

Open a javascript project that uses `eslint` without `eslint` installed globally.

### System information

<details>
<summary>Click to expand</summary>

```
- OS: darwin (x86_64-apple-darwin16.7.0)
- Emacs: 26.1 (May 28, 2018)
- Doom: 2.0.9 (develop e33cb446aa9803577df7ba66c60e76da8e5b3f56)
- Graphic display: t (daemon: nil)
- System features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2
- Details:
  ```elisp
  elc count: 0
  uname -a:  xx 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 21 20:07:39 PDT 2018; root:xnu-3789.73.14~1/RELEASE_X86_64 x86_64
  modules:   (:feature (evil +everywhere) file-templates (lookup +devdocs +docsets) snippets spellcheck (syntax-checker +childframe) workspaces :completion (ivy +fuzzy) :ui doom-dashboard doom-modeline doom-quit evil-goggles hl-todo nav-flash vc-gutter vi-tilde-fringe window-select :editor rotate-text :emacs ediff electric hideshow imenu vc :tools magit :lang common-lisp data emacs-lisp javascript markdown (org +attach +babel +capture +export +present) (sh +fish) web :config :private clojure lispy)
  packages:  n/a
  exec-path: (~/.rvm/gems/ruby-2.4.1/bin/ ~/.rvm/gems/ruby-2.4.1@global/bin/ ~/.rvm/rubies/ruby-2.4.1/bin/ /Library/Frameworks/Python.framework/Versions/3.7/bin/ ~/.cargo/bin/ /usr/local/bin/ /usr/bin/ /bin/ /usr/sbin/ /sbin/ /usr/local/sbin/ ~/bin/ ~/.nvm/versions/node/v8.11.0/bin/ ~/.cargo/bin/ ~/.rvm/gems/ruby-2.4.1/bin/ ~/.rvm/gems/ruby-2.4.1@global/bin/ ~/.rvm/rubies/ruby-2.4.1/bin/ ~/.rvm/bin/ ~/go/bin/ ~/.fzf/bin/ /usr/local/Cellar/emacs-plus/26.1/libexec/emacs/26.1/x86_64-apple-darwin16.7.0/)
  ```
```
</details>

**Comment by hlissner** [comment]
@hackeryarn A few questions:

1. Are you sure `:lang javascript` is enabled? Your `doom-info` suggests it is disabled.
2. Does the project you're testing use npm or yarn?
3. Does adding `(add-hook 'js2-mode-hook #'+javascript|add-node-modules-path)` fix the issue?

**Comment by hackeryarn** [comment]
1. Sorry, I was trying different things to fix this. I just updated the info above with `:lang javascript` enabled and the suggested hook from 3 added to my `~/.doom.d/config.el`. I am still experiencing the issue.

2. It is a yarn project.

**Comment by hlissner** [comment]
12c5490 should resolve this issue. Please update and let me know if it does.

**Comment by hlissner** [comment]
Sorry for the delay. Is this still an issue?

I'm looking into this and can't reproduce it on Linux or MacOS (El Capitan). Here are some things that'd help me figure out the issue:

1. From one of your project's js buffers, is `+javascript-npm-mode` enabled? 
2. Does the return value of `(doom-project-root)` return what you expect? And if so, is that folder where your `package.json` is?
3. If 1 and 2 are true, what does `(executable-find "eslint")` return?

Remember to run all this while the js buffer is selected.

**Comment by hackeryarn** [comment]
It seems to be related to the bug I was getting with `emacs-snippets`. Once I followed your advice on the other issue, everything works.
