### ISSUE TITLE
Org-cycle-separator-lines has no effect

### ISSUE THREAD

**Issue by siddharthshekar** [hlissner/doom-emacs#800]
### Observed behavior

Changing org-cycle-separator-lines has no effect. Doom sets it to 1 and the documentation suggests that if a subheading has > org-cycle-separator-lines blank lines then one blank line will be shown when that subtree is folded. However, changing this to 0 (which should never show blank lines when a subtree is folded) or a number greater than 1 has no effect on blank line visibility. The variable works as expected with `emacs -Q`.

### Expected behavior
Setting org-cycle-separator-lines to 2 should not show blank lines when a subtree is folded if there is only one blank line at the end of the subtree (and before the next heading).

### Steps to reproduce

1. Create an org file as follows:
```
* Heading 1

* Heading 2
```
2. Set org-cycle-separator-lines to 2
3. Fold heading 1

### System information

<details>
<summary>Click to expand</summary>

```
- OS: gnu/linux (x86_64-pc-linux-gnu)
- Emacs: 26.1 (May 29, 2018)
- Doom: 2.0.9 (develop 69e992e54aaa98d065d51e8530ab5a0600b8033a)
- Graphic display: t (daemon: t)
- System features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS XWIDGETS LIBSYSTEMD LCMS2
- Details:
  ```elisp
  elc count: 0
  uname -a:  Linux siddharth-VirtualBox 4.15.0-22-generic #24-Ubuntu SMP Wed May 16 12:15:17 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
  modules:   (:feature (evil +everywhere) file-templates (lookup +devdocs +docsets) snippets spellcheck (syntax-checker +childframe) workspaces :completion (ivy +fuzzy) :ui doom-dashboard doom-modeline doom-quit evil-goggles hl-todo nav-flash treemacs popup vc-gutter vi-tilde-fringe window-select :editor rotate-text :emacs ediff electric hideshow imenu vc :tools magit pdf :lang emacs-lisp latex ledger markdown (org +attach +babel +capture +export +present) python (sh +fish) :app :config (default +bindings +snippets +evil-commands) sid)
  packages:  n/a
  exec-path: (/usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /usr/games /usr/local/games /snap/bin ~/.local/bin/ ~/.local/bin/ /usr/lib/x86_64-linux-gnu/emacs/26.1/x86_64-linux-gnu)
  ```
```
</details>

**Comment by hlissner** [comment]
As of 5663778, org-cycle-separator-lines should be respected. Feel free to reopen this if that isn't the case!

Thanks for letting me know!

**Comment by siddharthshekar** [comment]
Tab-cycling the headings works great now! Thanks! Unfortunately, Shift+Tab is still broken. I believe that should respect the variable too.

**Comment by hlissner** [comment]
As of 64a8838, shifttab should respect org-cycle-separator-lines. Let me know if they don't!
