### ISSUE TITLE
Search in project very slow and matching both filename and contents (develop)

### ISSUE THREAD

**Issue by danielmt** [hlissner/doom-emacs#805]
### Observed behavior

After switching to helm, since it was now the preferred option in develop, search in project (SPC / p) became very sluggish and kind of useless. Instead of waiting for input to grep, it concatenates the whole project and does some weird fuzzy match on the content AND filenames, which is very unexpected.

Trying to search for "Object.entries" takes a couple seconds just for the search text to appear, and then, I get some results back as such:

`src/client/core/analytics.js:xx: Object.assign({}, code...)`

and a bunch of irrelevant results which has nothing to do with the search itself.

### Expected behavior

When using search in project (SPC / p), I expect it not to search before I type anything, and, the search should be done on file contents, not a mix of filename and contents which yields hundreds of irrelevant results.

### Steps to reproduce

1. Open large project
2. SPC / p
3. Watch as results appear before you even type anything
4. Search for file contents and watch as you get very weird results with backwards fuzzy-matching on filenames and file contents.

### System information

- OS: darwin (x86_64-apple-darwin17.6.0)
- Emacs: 26.1 (Jun 14, 2018)
- Doom: 2.0.9 (develop 5bb40e6dd1f92dae948e9f7bf28ccc94b6daa11e)
- Graphic display: t (daemon: nil)
- System features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS LCMS2
- Details:
  ```elisp
  elc count: 23
  uname -a:  Darwin kusanagi 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64 i386 MacBookPro14,3 Darwin
  modules:   (:feature (evil +everywhere) (lookup +devdocs) snippets (syntax-checker +childframe) workspaces :completion (helm +fuzzy) :ui doom-dashboard doom-modeline doom-quit evil-goggles hl-todo nav-flash treemacs (popup +all +defaults) vc-gutter vi-tilde-fringe window-select :editor rotate-text :emacs ediff electric hideshow imenu vc :tools macos magit :lang data emacs-lisp go javascript markdown org python rest rust sh web :private js web gtd :config)
  packages:  (deft flycheck-flow prettier-js)
  exec-path: (~/bin/mac/ /usr/local/opt/python/libexec/bin/ /usr/local/opt/coreutils/libexec/gnubin/ /usr/local/opt/gnu-sed/libexec/gnubin/ /usr/local/opt/sqlite/bin/ ~/bin/ ~/.local/bin/ ~/go/bin/ /usr/local/bin/ /usr/local/sbin/ /usr/local/bin/ /usr/bin/ /bin/ /usr/sbin/ /sbin/ ~/.nvm/versions/node/v8.11.3/bin/ ~/bin/mac/ /usr/local/opt/python/libexec/bin/ /usr/local/opt/coreutils/libexec/gnubin/ /usr/local/opt/gnu-sed/libexec/gnubin/ /usr/local/opt/sqlite/bin/ ~/bin/ ~/.local/bin/ ~/go/bin/ /usr/local/sbin/ /usr/local/Cellar/emacs-mac/emacs-26.1-z-mac-7.1/libexec/emacs/26.1/x86_64-apple-darwin17.6.0/)
  ```

**Comment by hlissner** [comment]
11b8ee5 introduces a couple changes that should resolve your issues. Please update and let me know.

**Comment by danielmt** [comment]
Working fine after pulling the fix, thank you. :)
