### ISSUE TITLE
Web-mode/smartparens compatibility breaks on Emacs < 26.1

### ISSUE THREAD

**Issue by ShyGuy32** [hlissner/doom-emacs#806]
### Observed behavior

Running `M-x web-mode` fails with the error "Wrong number of arguments: (1 . 1), 2". The buffer remains in whatever mode it was in.

### Expected behavior

Web-mode is applied to the buffer properly.

### Steps to reproduce

```M-x web-mode```

### Additional Notes

It looks like this was introduced in commit 8248e80, specifically in the call to `(string-trim-right (cdr pair) "\\(?:>\\|]\\|}\\)+")`. The regexp argument to `string-trim-right` was added in 26.1.

### System information

- OS: gnu/linux (x86_64-unknown-linux-gnu)
- Emacs: 25.1.1 (Sep 19, 2016)
- Doom: 2.0.9 (develop a824e04e9262434371ebb727f8698a135f8ce167)
- Graphic display: nil (daemon: nil)
- System features: XPM JPEG TIFF GIF PNG IMAGEMAGICK SOUND NOTIFY LIBSELINUX LIBXML2 FREETYPE XFT ZLIB X11
- Details:
  ```elisp
  elc count: 1
  modules:   (:feature file-templates (lookup +devdocs +docsets) spellcheck (syntax-checker +childframe) workspaces :completion (ivy +fuzzy) :ui doom-dashboard doom-quit hl-todo nav-flash vc-gutter window-select :editor multiple-cursors :emacs ediff electric eshell imenu term vc hideshow :tools make magit :lang emacs-lisp javascript markdown (org +attach +babel +capture +export +present) perl rest sh web :config)
  packages:  n/a
  exec-path: (~/.npm-packages/bin ~/.gem/ruby/2.3.0/bin ~/.local/bin ~/myapps/bin /usr/local/lib/npm/bin /usr/local/bin /usr/bin /usr/local/sbin /usr/sbin ~/bin ~/myapps/libexec/emacs/25.1/x86_64-unknown-linux-gnu)
  ```

**Comment by hlissner** [comment]
Thank you for the detailed bug report! You're right about `string-trim-right`. This has been fixed in 40a900f.

Feel free to reopen this if that isn't the case.
