### ISSUE TITLE
LaTeX doc-view pane interacts annoyingly with the feature that asks to reload modified files

### ISSUE THREAD

**Issue by Ptival** [hlissner/doom-emacs#807]
Whenever I save my TeX files, the preview pane uploads, as needed, but then, I get asked:

```
Please answer y or n.  File <filename>.pdf changed on disk.  Reread from disk? (y or n)
```

which kind of defeats the purpose of the doc-view pane since it has already been re-read.

**Comment by hlissner** [comment]
Are you still experiencing this issue on the latest commit of Doom?
