### ISSUE TITLE
LaTeX preview pane sometimes re-opens a new pane for each save

### ISSUE THREAD

**Issue by Ptival** [hlissner/doom-emacs#808]
Symptoms: very frequently, when I save one of my LaTeX files, instead of refreshing the existing preview pane, it creates a second preview pane, identical to the first one, but reset to the first page...
Closing either pane will result in a new pane being created next save, and from then on.

I'm sorry, it's been hard to resolve this down to a small reproducible example, but it happens to me all the time with my setup, that I will try to describe:

- I have multiple LaTeX files, the main one including the other ones using `\input{filename}`

- my files do not have local variables in them, but I have a `.dir-locals.el` with:
```
((latex-mode
  (TeX-command-extra-options . "-shell-escape")
  (TeX-engine . xetex)
  (TeX-master . "dissertation")
  (pdf-latex-command . "xelatex")
  (shell-escape-mode . "-shell-escape")))
```

I end up in situations like these:

![image](https://user-images.githubusercontent.com/478606/44173481-eb6a0d00-a094-11e8-940e-c845474d84ef.png)

where, if I close either of the two rightmost pane, the next time I save the left file, it will reopen such a pane.

---

Not sure whether this is Doom being zealous about panes, or whether the fault is upstream in latex-preview-pane for this.

**Comment by UndeadKernel** [comment]
@Ptival, which operating system are you using?
I suggest using PDF tools instead of preview-pane. They behave exactly the same but PDF tools brings in more features.

**Comment by Ptival** [comment]
@UndeadKernel yeah, I switched to zathura/okular after noticing those were better options. Thanks!

**Comment by hlissner** [comment]
Are you still experiencing this issue with preview-pane?

**Comment by mmajewsk** [comment]
@hlissner Still there is this problem with preview-pane, which was very likely solved in this pull request https://github.com/jsinglet/latex-preview-pane/pull/33 by adding an option to switching off the refresh on save but the maintaner did not do any changes for the past 2 years.

**Comment by hlissner** [comment]
Sorry for the tremendously late reply. jsinglet/latex-preview-pane#33 offers a way to turn of refresh-on-save, but I don't think this is enough. Once the preview window is closed, it should stop trying to preview the pdf entirely.

@mmajewsk Could you give this a try?

```elisp
(defadvice! +latex--dont-reopen-preview-pane-a (orig-fn &rest args)
  :around #'latex-preview-pane-update
  (letf! (defun init-latex-preview-pane (&rest _))
    (apply orig-fn args)))
```
