### ISSUE TITLE
doom bin does not AutoYes, '-y' switch is being passed.

### ISSUE THREAD

**Issue by xeijin** [hlissner/doom-emacs#817]
**Edit:** Sorry, just remembered Windows is not a supported platform, but if anyone has a clue here (or perhaps know a workaround) that would be immensely helpful -- trying to get this on my work machine so I can finally get my emacs workflow back!

### Observed behavior

Running `doom -y quickstart` is causing a CI build to hang on `windows`

Logs from AppVeyor CI:

Where `AutoYes` is confirmed to be turned on (note: please disregard the fact that this looks like an error, 'NativeCommand Error' occurs because powershell messes-up stdin/out/error - `git` and `pip` throw the same errors and continue as normal)
https://ci.appveyor.com/project/xeijin/propositum/build/1.0.173#L1311

The last line of output, at which point the build hangs (there is a 60 min limit on the build VM)
https://ci.appveyor.com/project/xeijin/propositum/build/1.0.173#L1475

A previous build **without** the `-y` switch -- it hangs in the same place.
https://ci.appveyor.com/project/xeijin/propositum/build/1.0.172

Relevant parts of the script I'm using to automate installation:
https://github.com/xeijin/propositum#install--setup-doom-emacs
(full script here (`powershell`): https://github.com/xeijin/propositum/blob/master/script/propositum-windows.ps1)

### Expected behavior

Expected `doom` to proceed with installation.

### Steps to reproduce

1. Platform should be `windows`
2. Add `doom` to `path`
3. Run `doom -y quickstart`

### System information

Unfortunately I can't get into the VM at this point to do any further investigation, will try to mess around with the RDP option that is apparently available...

**Comment by hlissner** [comment]
I just realized that `doom quickstart` wasn't passing -y/--yes to the package installation procedure. That should be fixed as of c5f3cc1, which should resolve your issue. Let me know if that isn't the case!
