### ISSUE TITLE
Use builtin line-numbers for Emacs 26.0.5 and up

### ISSUE THREAD

**Issue by MagB93** [hlissner/doom-emacs#819]
Hi

thank you for sharing such a nice emacs configuration! I'm still in the process of migrating my
configuration with doom-emacs. In that process I noticed that you're using nlinum. Since I'm 
using emacs 26.1, I've been using the new builtin line-numbers via: [display-line-numbers](https://www.emacswiki.org/emacs/LineNumbers#toc1). It's supposed to be [faster](https://github.crookster.org/macOS-Emacs-26-display-line-numbers-and-me/#display-line-numbers) than linum. 
Could that be an improvement for doom-emacs?

Best regards
Magnus

PS. For diff-hl to work nice with relative line-numbers I found this to work for me
```
(setq display-line-numbers 'relative)
(setq display-line-numbers-type 'relative)
(setq display-line-numbers-current-absolute t)

(global-display-line-numbers-mode t)
```

**Comment by hlissner** [comment]
You're very welcome!

Doom already does, If it detects `display-line-numbers` is defined. nlinum and friends won't be installed in that case. And it is certainly _much_ faster than nlinum or linum.

nlinum is only there for Emacs 25.x users. Sometime near the end of the year (or early next), I'd like to drop Emacs 25 support. When I do, nlinum will go with it.

**Comment by MagB93** [comment]
Okay I understand. Sorry for the redundant issue.
