### ISSUE TITLE
popup back to regular window?

### ISSUE THREAD

**Issue by mfiano** [hlissner/doom-emacs#825]
Perhaps a stupid question, but after I raise a popup with `+popup-raise`, is there any possible way to revert that window back to its popup status?

**Comment by hlissner** [comment]
There is no counterpart to `+popup/raise` at the moment, but I could add one. Give this command a try:

```elisp
(defun +popup/buffer ()
  "Open current buffer in a popup window."
  (interactive)
  (let ((+popup-default-display-buffer-actions '(+popup-display-buffer-stacked-side-window))
        (display-buffer-alist +popup--display-buffer-alist))
    (push (+popup--make "." +popup-defaults) display-buffer-alist)
    (pop-to-buffer (current-buffer))))
```

If it works as expected, I'll add it.

**Comment by mfiano** [comment]
I just tested this, and it doesn't close the raised window before it creates a popup window, so I have 2 windows now.

**Comment by hlissner** [comment]
Ah, I'd nearly forgotten about the `doom/window-enlargen` issue! I've modified `+popup/buffer` to bury the current buffer before opening it in a popup window. I've also fixed `doom/window-enlargen` in popup windows. Give them a try and let me know if they give you any trouble!

**Comment by mfiano** [comment]
Wow, both work great. Thanks for this!

**Comment by hlissner** [comment]
Excellent! You're very welcome. I'll consider this resolved then.

**Comment by mfiano** [comment]
Somehow enlarging windows got into a bad state today, after working fine for some time. When I try to enlarge the REPL popup window, it says: `Marker does not point anywhere`, and closes the REPL without doing anything. Additionally, I get the same message in normal windows, and no enlarging happens. I'm not sure how I got into this state, but restarting Emacs fixed it.

**Comment by hlissner** [comment]
Errors in Emacs tend to have a cascading effect, as Emacs tries to clumsily self-correct by removing errant hooks in unpredictable places. It's hard to pinpoint these things. This is with the sly REPL right?

If you find a way to reproduce it, see if you can produce a backtrace from it. That'd go a long way to help me debug the issue.

**Comment by mfiano** [comment]
Sure will do, however this had to do with enlarging any window after it got into this mess. Same message in the echo area, only popup windows are deleted before it does nothing.

**Comment by hlissner** [comment]
Found it! 6318572 should fix this issue. Let me know if that isn't the case.
