### ISSUE TITLE
Line number doesn't display at org files

### ISSUE THREAD

**Issue by PoiScript** [hlissner/doom-emacs#827]
### Observed behavior

Line number doesn't display at org files. And I can not toggle it on manually either.

![screenshot_20180823_223856](https://user-images.githubusercontent.com/17513314/44532281-5666b400-a725-11e8-9e97-3e0e16dcccef.png)

### Expected behavior

It shows up normally.

### Steps to reproduce

1. Using the latest develop branch
2. Line numbers don't work at org files
3. After removing the org module in the init.el,  it works.

### System information

<details>
<summary>Click to expand</summary>

- OS: gnu/linux (x86_64-pc-linux-gnu)
- Emacs: 26.1 (Jul 05, 2018)
- Doom: 2.0.9 (develop e003c2aa6a96c2925f7ad1323237ab2a1014a942)
- Graphic display: t (daemon: nil)
- System features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LIBSYSTEMD LCMS2
- Details:
  ```elisp
  elc count: 0
  uname -a:  Linux yuudachi-laptop 4.18.3-arch1-1-ARCH #1 SMP PREEMPT Sat Aug 18 09:22:54 UTC 2018 x86_64 GNU/Linux
  modules:   (:feature (evil +everywhere) file-templates (lookup +devdocs +docsets) snippets spellcheck (syntax-checker +childframe) workspaces :completion (ivy +fuzzy) :ui doom-dashboard doom-modeline doom-quit evil-goggles hl-todo neotree (popup +all +defaults) vc-gutter vi-tilde-fringe window-select :editor rotate-text :emacs ediff electric hideshow imenu term vc :tools magit :lang data emacs-lisp javascript latex markdown org python rust (sh +fish) web :config)
  packages:  n/a
  exec-path: (~/.cargo/bin/ ~/.yarn/bin ~/.cargo/bin ~/.yarn/bin /usr/local/bin /usr/bin /bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl ~/.cargo/bin ~/.yarn/bin /usr/local/bin /usr/bin /bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /usr/local/sbin /usr/local/bin /usr/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /usr/lib/emacs/26.1/x86_64-pc-linux-gnu)
  ```
</details>

**Comment by hlissner** [comment]
`doom|disable-line-numbers` is attached to `org-mode-hook`. You'll need to remove it:

```elisp
(remove-hook 'org-mode-hook #'doom|disable-line-numbers)
```

Otherwise, `doom-line-numbers-style` does not exist. It was replaced in https://github.com/hlissner/doom-emacs/commit/a7da9a473817bb26addd76ff01bcaa4b67ab91f4 with `display-line-numbers-type` and `display-line-numbers-mode`. I've ported this from Emacs 26.1 for Emacs 25.x users).

**Comment by PoiScript** [comment]
Thanks for your quick responds! It worked!

**Comment by rodelrod** [comment]
For people looking at this in the future, I wanted to disable line numbers in org files and keep them in other files. Adding the hook reference by @hlissner above did not work. A round of `git-timemachine` told me that the `doom|disable-line-numbers` was renamed. My solution:

```elisp
(add-hook! 'org-mode-hook #'doom-disable-line-numbers-h)
```
