### ISSUE TITLE
Some font questions

### ISSUE THREAD

**Issue by PoiScript** [hlissner/doom-emacs#832]
### Observed behavior

Firstly, I'm using Fira Code as my default font but its width varies from normal to bold. As you can see the first row of the dashboard is not alignas with others.

![screenshot_20180824_142258](https://user-images.githubusercontent.com/17513314/44569651-b012c100-a7ad-11e8-96b2-8f681c258b8d.png)

This problem becomes serious with company popup:

![screenshot_20180824_150508](https://user-images.githubusercontent.com/17513314/44570086-3b408680-a7af-11e8-98bf-76bf0aa9fae4.png)

Secondly, I can not change the font for specific fontset such as chinese and japanese.

### Expected behavior

Normally, I can resolve these by disabling bold font and using `set-fontset-font` :

```elisp
(set-face-bold-p 'bold nil)

(set-fontset-font t 'japanese-jisx0208 (font-spec :family "noto sans cjk jp" :size 19))
(set-fontset-font t 'han (font-spec :family "noto sans cjk sc" :size 19))
```

However, neither of them work in doom emacs.

### Steps to reproduce

1. Setting Fira Code as default font: `(setq doom-font (font-spec :family "Fira Code" :size 20))`
2. Typing something and waiting for company to pop up.

### System information

<details>
<summary>Click to expand</summary>

- OS: gnu/linux (x86_64-pc-linux-gnu)
- Emacs: 26.1 (Jul 05, 2018)
- Doom: 2.0.9 (develop e003c2aa6a96c2925f7ad1323237ab2a1014a942)
- Graphic display: t (daemon: t)
- System features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LIBSYSTEMD LCMS2
- Details:
  ```elisp
  elc count: 0
  uname -a:  Linux yuudachi-laptop 4.18.4-arch1-1-ARCH #1 SMP PREEMPT Wed Aug 22 07:33:26 UTC 2018 x86_64 GNU/Linux
  modules:   (:feature (evil +everywhere) file-templates snippets spellcheck (syntax-checker +childframe) workspaces :completion (ivy +fuzzy) :ui doom-dashboard doom-modeline doom-quit evil-goggles hl-todo neotree (popup +all +defaults) pretty-code vc-gutter vi-tilde-fringe window-select :editor rotate-text :emacs ediff electric hideshow imenu term vc :tools magit :lang data emacs-lisp javascript latex markdown (org +attach +babel +capture +export +present) python (rust +syntax-checker +company) (sh +fish) web :config)
  packages:  (fcitx)
  exec-path: (/usr/local/sbin /usr/local/bin /usr/bin /usr/lib/emacs/26.1/x86_64-pc-linux-gnu)
  ```
</details>

**Comment by hlissner** [comment]
It appears you're using the `doom-one` theme from my doom-themes package. If so, try disabling bolds with:

```elisp
(setq doom-themes-enable-bold nil)
```

**Comment by PoiScript** [comment]
Oh, sorry for the delay. This solves my problem. Thanks!
