### ISSUE TITLE
Need a code guidelines

### ISSUE THREAD

**Issue by yuzumx** [hlissner/doom-emacs#839]
Hello, and sorry for my poor English.

I want to contribute some code to `doom-emacs`. But I was in trouble when I read existing code.
I don't understand the difference between `(defun doom-xxx)`, `(defun doom|xxx)` and `(defun doom/xxx)`.

I think you need a code guidelines like [spacemacs/CONVENTIONS.org](https://github.com/syl20bnr/spacemacs/blob/develop/doc/CONVENTIONS.org#code-guidelines).But I am also an emacs-lisp rookie, so I can't submit PR for you, sorry.

Thank you.

**Comment by re-mx** [comment]
Thanks.

**Comment by hlissner** [comment]
With 3f6decf we have contributing guidelines (though documentation is an ongoing effort), so I'll consider this resolved. Thanks for bringing it to my attention!
