### ISSUE TITLE
Can no longer select file w/ HELM. Up or down file selection broken? 

### ISSUE THREAD

**Issue by skalfyfan** [hlissner/doom-emacs#840]
### Observed behavior

Did something change with `helm`? After typing out a path slowly and getting some fuzzy results I can no longer press UP or DOWN keys to select a file. Attempting to do this now results in the bottom modeline prompt area flickering and showing random files `helm` changing to random directories?

### Expected behavior

When I press UP or DOWN when searching w/ `helm` I can manually select a search result item from the list and open it? 

### Steps to reproduce

1. SPC . f (find a file)
2. Start searching for something which provides lots of fuzzy hits
3. Try to press UP or DOWN arrow keys to select a specific file. `helm` goes WILD! 

### System information

Mac OS X. Let me know if any further details are needed?

**Comment by skalfyfan** [comment]
Ah, it's indeed fixed in develop. You need to do a `make` and full quit & restart of emacs. 
I was doing a `make` and `Mx doom/reload` in an existing running emacs, which didn't fix it!
Thanks!

**Comment by hlissner** [comment]
Ah I see what you mean. I'd recommend not using `doom/reload`; it's highly experimental and best suited to changes to your config (not when you're upgrading Doom).

`SPC q r` is bound to `+workspace/restart-emacs-then-restore`, which will restart Emacs and restore the last session, if you're using `:feature workspaces`. That or `M-x restart-emacs` (which will only restart it, not restore).
