### ISSUE TITLE
docsinstalled by helm-dash disappear once restart emacs 

### ISSUE THREAD

**Issue by FirstLoveLife** [hlissner/doom-emacs#845]
I installed some docs via `helm-dash-install-docset`, and use `helm-dash-at-point` to view. It works fine, but once I restart emacs, I cannot find any of these docs. 

But I find all docs are in `/home/firstlove/.emacs.d/.local/etc/docsets`. So it seems helm cannot find them after restartup.

**Comment by hlissner** [comment]
This depends on the major mode in question. What docset are you trying to install, and for what major mode?

You must declare docsets for major modes. Some modes already have this, for example:

```elisp
;; from modules/lang/emacs-lisp/config.el
(set-docset! 'emacs-lisp-mode "Emacs Lisp")
```

Some modes do not, like javascript modes, but that can be fixed with:

```elisp
(set! :docset 'js2-mode "JavaScript" "JQuery")
;; Add docsets to minor modes by starting DOCSETS with :add
(set! :docset 'rjsx-mode :add "React")
;; Or remove docsets from minor modes
(set! :docset 'nodejs-mode :remove "JQuery")
```

**Comment by FirstLoveLife** [comment]
Thanks! Fixed now.
