### ISSUE TITLE
Unable to use treemacs (won't higlight any file)

### ISSUE THREAD

**Issue by qleguennec** [hlissner/doom-emacs#846]
Newbie to doom emacs, probably something I misunderstood about treemacs, sorry.

### Observed behavior

Unable to use treemacs.
It doesn't highlight any file, and shows another project than the current one.
When I hit `l`, I have this message: `[Treemacs] Ad-hoc navigation is only
possible when there is but one current project in the workspace`

### Expected behavior

When I enter SPC o p, a window on the left should show the current edited file
in the buffer, with only the current project I'm working on.
When I use `j` and `k` keybindings, it should switch the highlighted file in the
treemacs window.
I can highlight a file with my the mouse, but nothing happens when I click on it
(I can press RET to visit it)

### Steps to reproduce

1. SPC o p
2. `j` or `k`

### System information

<details>
<summary>Click to expand</summary>

```
- OS: gnu/linux (x86_64-pc-linux-gnu)
- Emacs: 26.1 (Jul 05, 2018)
- Doom: 2.0.9 (develop ee4d3172935c645fb41ef7f1b085b93ce0e99904)
- Graphic display: t (daemon: nil)
- System features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LIBSYSTEMD LCMS2
- Details:
  ```elisp
  elc count: 0
  uname -a:  Linux hal 4.17.14.a-1-hardened #1 SMP PREEMPT Fri Aug 10 00:21:59 CEST 2018 x86_64 GNU/Linux
  modules:   (:feature (evil +everywhere) file-templates (lookup +devdocs +docsets) snippets spellcheck (syntax-checker +childframe) workspaces :completion (helm +fuzzy) :ui doom-dashboard doom-modeline doom-quit evil-goggles hl-todo nav-flash treemacs (popup +all +defaults) vc-gutter vi-tilde-fringe window-select :editor multiple-cursors parinfer rotate-text :emacs ediff electric hideshow imenu term vc :tools magit :lang clojure data emacs-lisp (haskell +intero) javascript markdown (org +attach +babel +capture +export +present) racket rest (sh +fish) web :config)
  packages:  n/a
  exec-path: (/usr/local/bin /usr/local/sbin /usr/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /usr/lib/emacs/26.1/x86_64-pc-linux-gnu)
  ```
</details>

### Screenshot showing the issue
![screenshot from 2018-08-28 13-20-45](https://user-images.githubusercontent.com/7882725/44720025-959a5980-aac5-11e8-993f-51b5d920bef2.png)

**Comment by hlissner** [comment]
Treemacs prefers multiple-projects in the project sidebar. I don't, so as of d0295a2, there should only be one project present in Treemacs when you open it.

And e866fc4 makes the current selection more visible. Before used the `hl-line` face, which may be difficult to see in some themes. Now it uses `region`, which I hope will be more visible.

This should resolve your two issues. Let me know if that isn't the case.

**Comment by Alexander-Miller** [comment]
> I can highlight a file with my the mouse, but nothing happens when I click on it

Single click just sets the focus, a double click will do the same thing as RET.  A click on the icon will show a file's tags, if possible.

I don't know about doom specifics, but you should also read the first two points [in this list](https://github.com/Alexander-Miller/treemacs#detailed-feature-list). That explains how treemacs handles projects.

Looking at your treemacs code doom may also be interested in:
 * `treemacs-fringe-indicator-mode`
 * `deferred` git-mode
 * a workspace api, once it's done: https://github.com/Alexander-Miller/treemacs/issues/247
 * A full-blown extension api is in the works as well: https://github.com/Alexander-Miller/treemacs/issues/263

**Comment by qleguennec** [comment]
@hlissner Thanks a lot for the reactivity. Tested it, works perfectly.

**Comment by digizeph** [comment]
@qleguennec thanks for the issue. I had the same problem, and it was resolved beautifully thanks to @hlissner .
FYI, I am using `doom-solarized-light` theme.
