### ISSUE TITLE
doom-line-numbers-style is ignored in develop branch

### ISSUE THREAD

**Issue by mpilman** [hlissner/doom-emacs#847]
I am using the develop branch of doom.

In my ~/.doom.d/config.el file I have the following line:

`(setq doom-line-numbers-style 'relative)`

This used to work like a charm. But since my last update, it doesn't anymore - I simply get normal line numbers which is the default behavior. I grepped through the code and it seems that this variable is now only used in `doom/toggle-line-numbers`. This function now only works if I also set `doom-line-numbers-visual-style`. However, calling this function for each buffer is not what I want.

Did the way I am supposed to enable relative line numbers change?

**Comment by hlissner** [comment]
I apologize for the sudden and unannounced changed. This happened in https://github.com/hlissner/doom-emacs/commit/a7da9a473817bb26addd76ff01bcaa4b67ab91f4. The `doom-line-numbers*` family of variables were removed and replaced with the `display-line-numbers*` API built into Emacs 26+, and was backported for Emacs 25 users.

To do this now, change `doom-line-numbers-style` to `display-line-numbers-type`:

```elisp
(setq display-line-numbers-type 'relative)
```

A side note: thanks for bringing `doom/toggle-line-numbers` that to my attention, I forgot to update it and will do so soon.

**Comment by mpilman** [comment]
hehe, using `display-line-numbers-type` was my workaround. Seems that it was in fact a fix :) Thanks for your quick answer!
