### ISSUE TITLE
Why not use helm-swoop by default?

### ISSUE THREAD

**Issue by FirstLoveLife** [hlissner/doom-emacs#848]
From the commit history, I found doom use helm-swoop in the past. But it seems you have removed this package in helm's `package.el`, why?

**Comment by hlissner** [comment]
helm-swiper was determined to be faster, required significantly less configuration and produced better visual feedback (e.g. better match highlighting). Also, its window management code is sane. helm-swoop required a few hefty and unreliable hacks to have it behave with the popup manager.

Was there something from helm-swoop you're missing?

**Comment by FirstLoveLife** [comment]
Oops, I'm so stupid that I didn't find helm-swiper in doom. Now I know it bind to <kbd>M-f</kbd>
