### ISSUE TITLE
Various broken theme settings when using a custom color theme

### ISSUE THREAD

**Issue by glittershark** [hlissner/doom-emacs#851]
### Observed behavior

On `develop`, my cursor now looks like this:

![cursor-white](https://user-images.githubusercontent.com/1481027/44799092-1ff3c380-ab81-11e8-8477-c46a05d23e41.gif)

and my `org-mode` headlines look like this:

![image](https://user-images.githubusercontent.com/1481027/44799266-7e20a680-ab81-11e8-9b7f-165c958b9527.png)

### Expected behavior

On an earlier commit, my cursor looked like this:

![cursor-correct](https://user-images.githubusercontent.com/1481027/44799342-ae684500-ab81-11e8-8267-ee9e90cc8061.gif)

and my `org-mode` headings looked like this:

![image](https://user-images.githubusercontent.com/1481027/44799373-c3dd6f00-ab81-11e8-8e8e-a3b0061ea426.png)

### Steps to reproduce

I ran a bisect and the first commit that this is happening on is 6eafdd7c62d4d5d891deca0027ad168a45d5ddb4, which is surprising to me but maybe you have an idea why that might be happening. Currently just gonna run one commit before that until this can be fixed.

My config for my theme looks like this:

```elisp
# themes/grfn-solarized-light.el

(deftheme grfn-solarized-light "The light variant of Griffin's solarized theme")

(create-solarized-theme
 'light 'grfn-solarized-light
 (lambda ()
   (custom-theme-set-faces
    'grfn-solarized-light
    `(font-lock-doc-face ((t (:foreground ,+solarized-s-base1))))
    `(font-lock-preprocessor-face ((t (:foreground ,+solarized-red))))
    `(font-lock-keyword-face ((t (:foreground ,+solarized-green))))

    `(elixir-attribute-face ((t (:foreground ,+solarized-blue))))
    `(elixir-atom-face ((t (:foreground ,+solarized-cyan))))
    )

   ))

# config.el
(setq solarized-use-variable-pitch nil
      solarized-scale-org-headlines nil)

(add-to-list 'custom-theme-load-path "~/.doom.d/themes")
(load-theme 'grfn-solarized-light t)

(setq doom-theme 'grfn-solarized-light)
```

### System information

<details>
<summary>Click to expand</summary>

```
- OS: gnu/linux (x86_64-pc-linux-gnu)
- Emacs: 26.1 (May 14, 2018)
- Doom: 2.0.9 (n/a f88a97177c92ae7b07a00f26cb37e76998e8a1cd)
- Graphic display: t (daemon: nil)
- System features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS NOTIFY ACL GNUTLS LIBXML2 FREETYPE LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LIBSYSTEMD LCMS2
- Details:
  ```elisp
  elc count: 0
  uname -a:  Linux chupacabra 4.18.5-arch1-1-ARCH #1 SMP PREEMPT Fri Aug 24 12:48:58 UTC 2018 x86_64 GNU/Linux
  modules:   (:feature (evil +everywhere) file-templates (lookup +devdocs +docsets) snippets spellcheck (syntax-checker +childframe) workspaces :completion (helm +fuzzy) :ui doom-dashboard doom-modeline doom-quit evil-goggles hl-todo modeline nav-flash (popup +all +defaults) pretty-code unicode vc-gutter vi-tilde-fringe window-select :editor :emacs ediff electric hideshow imenu vc :tools gist make magit password-store pdf :lang data erlang elixir emacs-lisp haskell javascript latex markdown nix (org +attach +babel +capture +export +present) ruby (sh +fish) web :app :config)
  packages:  (alert cargo company-flow company-lsp dash dash-functional epresent evil-magit fill-column-indicator flow-minor-mode flx flycheck-credo flycheck-dialyxir flycheck-flow flycheck-mix (general :recipe (general :fetcher github :repo noctuid/general.el)) graphql-mode lsp-haskell lsp-mode (lsp-ui :recipe (lsp-ui :fetcher github :repo emacs-lsp/lsp-ui)) magit-gh-pulls magithub marshal (org-clubhouse :recipe (org-clubhouse :fetcher file :path ~/code/urb/org-clubhouse)) org-tree-slide ox-reveal paxedit prettier-js request s slack solarized-theme writeroom-mode)
  exec-path: (~/.rvm/gems/ruby-2.3.4/bin ~/.rvm/gems/ruby-2.3.4@global/bin ~/.rvm/rubies/ruby-2.3.4/bin ~/.yarn/bin ~/.local/bin ~/.cabal/bin ~/.cargo/bin /opt/google-cloud-sdk/bin /usr/local/sbin /usr/local/bin /usr/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl ~/.fzf/bin ~/code/go/bin ~/bin ~/npm/bin ~/.gem/ruby/2.1.0/bin ~/.gem/ruby/2.0.0/bin /opt/google-cloud-sdk/bin ~/.rvm/bin /usr/lib/emacs/26.1/x86_64-pc-linux-gnu /Users/griffin/.cargo/bin)
```
```
</details>

**Comment by hlissner** [comment]
Do you have your config up on github or somewhere I can see it?

**Comment by UndeadKernel** [comment]
The commit (6eafdd7) where this issue appears happens to be the same commit that created problems in issue #850. I'll term that commit the *quantum conundrum* commit.

**Comment by glittershark** [comment]
@hlissner https://github.com/glittershark/emacs.d sorry for the (horrible) mess but hopefully the stuff in there is helpful.

**Comment by hlissner** [comment]
Sorry for the late reply!

I notice you modify a lot of faces, but I think I understand the cause. You are loading your theme in your init.el (which is really early in the startup process). Some modules expect you to load it later (in your config.el). For example, `:feature evil` waits for a load-theme call before it correctly sets the cursor color (but since you already used `(load-theme 'grfn-solarized-light t)` in your init.el, it'll wait forever -- or at least until you call load-theme _again_).

I can't explain the org issue without more debugging, but I think both issues can be solved simply by moving _everything_ after your `doom!` block to [your config.el, possibly at line 21](https://github.com/glittershark/emacs.d/blob/master/config.el#L21). None of it appears to benefit from being in your init.el file instead of your config.el.

6eafdd7 changed the load order in Doom slightly. Before, the `doom!` macro would load your modules. After, `doom!` only sets some state so that Doom can load your modules _after_ your init.el is finished executing.

I hope that helps!

**Comment by glittershark** [comment]
@hlissner that fixed it!

**Comment by glittershark** [comment]
Ah, dang - looks like the org-mode font issue is still present, unfortunately.

**Comment by glittershark** [comment]
Putting
```elisp

(setq solarized-use-variable-pitch nil
      solarized-scale-org-headlines nil)
```

before the `load-theme` call fixed it - not Doom's fault at all. Sorry for the noise.
