### ISSUE TITLE
org-mode delete other windows

### ISSUE THREAD

**Issue by Pentaquark1** [hlissner/doom-emacs#858]
org-mode offers you the option of closing other windows by pressing o while showing the agenda:
https://orgmode.org/manual/Agenda-commands.html

In doom-emacs, doing so will close the agenda instead.
I also tried prefacing it with \ (switch to emacs state), resulting in the same behaviour.

The same thing can be observed if you try the following custom function:
```
(defun start-agenda ()
  (interactive)
  (org-agenda-list)
  (delete-other-windows))
```

I have always found this option very convenient, especially for viewing monthly agendas, but sadly this does not seem possible in doom yet.

**Comment by hlissner** [comment]
As of 5e25cfd this should be fixed. Please update and let me know if that isn't the case!

**Comment by Pentaquark1** [comment]
Updated, 5325cfd fixed the issue! Thanks. :)
