### ISSUE TITLE
`help-fns+` and other packages  cannot be installed.

### ISSUE THREAD

**Issue by re-mx** [hlissner/doom-emacs#859]
### Observed behavior

In China, `help-fns+` and other packages not installed by package.el cannot be installed.

### Expected behavior

All packages are installed normally

### Steps to reproduce

1. Copy init.example.el to init.el
2. run `make install`

### System information

<details>
<summary>Click to expand</summary>

```
DOOM Doctor
Running Emacs v26.1, commit 5dacbb7cb1c6ac246a9ccd15e6c4290def67757c

shell: /bin/zsh
Compiled with:
  XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY
  ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB
  TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LIBSYSTEMD LCMS2
uname -a:
  Linux mxre 4.18.5-arch1-1-ARCH #1 SMP PREEMPT Fri Aug 24 12:48:58 UTC
  2018 x86_64 GNU/Linux

Attempt to load DOOM: success! Loaded v2.0.9
Revision 5dacbb7cb1c6ac246a9ccd15e6c4290def67757c

----

test-emacs
test-windows
test-fonts
Found font material-design-icons.ttf
Found font weathericons.ttf
Found font octicons.ttf
Found font fontawesome.ttf
Found font file-icons.ttf
Found font all-the-icons.ttf
test-gnutls
test-tls
Validated https://elpa.gnu.org
Validated https://melpa.org
Successfully rejected https://self-signed.badssl.com
Successfully rejected https://wrong.host.badssl.com/
test-tar
Everything seems fine, happy Emacs’ing!
```
</details>

---

You may also understand the special situation of China's Internet. 

I don't expect to solve this problem (because it may be necessary to put the source code of these packages into this repo like spacemacs, which may not be what you want.), I just want to ask where I should download these packages?

**Comment by hlissner** [comment]
It appears you're using the `master` branch. Please switch to `develop`, which is more than 3000+ commits ahead of `master`. This issue has been resolved there (along with _many_ others). I am planning a big merge soon, but it'll take a little longer while I'm traveling.

**Comment by re-mx** [comment]
thanks.
