### ISSUE TITLE
Unable to use default keybinding under treemacs window

### ISSUE THREAD

**Issue by chengyi** [hlissner/doom-emacs#860]
Unable to use default keybinding under treemacs window.

**Comment by HaoZeke** [comment]
Which keybindings are you referring to? The treemacs hydra still works.

**Comment by hlissner** [comment]
I assume you're referring to the leader key being inaccessible from the treemacs buffer. At the moment this is unavoidable without some nontrivial refactoring. This is because the treemacs buffer is in a custom evil state called `treemacs`, and leader keys are bound to normal and visual states.

This will be fixed when I introduce general.el to doom, but until then I'm afraid you'll have to switch out of treemacs to access the leader keybinds.

**Comment by chengyi** [comment]
@hlissner thanks. :+1:

**Comment by Alexander-Miller** [comment]
> This is because the treemacs buffer is in a custom evil state called treemacs, and leader keys are bound to normal and visual states.

Is this a doom-specific thing? It works on my end (on spacemacs).
The treemacs state will also activate motion state.

**Comment by hlissner** [comment]
@Alexander-Miller It is doom-specific. Spacemacs has a different strategy for leader keys: it binds them to an override keymap, uncoupled from evil state, so they are available universally (and can be assigned to `SPC` explicitly when needed). Doom just binds to the `evil-(normal|visual)-state-map` keymaps for simplicity (a relic from the days Doom was just "my private config"), which are easily shadowed or made inaccessible (e.g. by being in motion mode). So it's definitely my fault and something I'm working on.

@HaoZeke Unless you've changed treemacs' initial state to normal mode, the leader key won't work there for now. Window movements (on `C-w`) shouldn't be inaccessible however.

**Comment by skalfyfan** [comment]
Ah! This explains a lot and why I had to switch back to _Neotree_ for now. 
@hlissner Window movements were not working for me either. Once I switched to Treemacs view I could not window move back to my editor buffer.

**Comment by hlissner** [comment]
With the introduction of general.el back in 4daa927 this issue should be resolved, so I will close this issue. Let me know if that isn't the case.
