### ISSUE TITLE
M-p and M-n unbound in repl when working on common lisp files

### ISSUE THREAD

**Issue by arejensen** [hlissner/doom-emacs#869]
### Observed behavior

M-p and M-n are unbound in the mrepl when working on common lisp files.

### Expected behavior

I expected sly-mrepl-previous-input-or-button to be called when pressing M-p and sly-mrepl-next-input-or-button to be called when pressing M-n.

### Steps to reproduce
1. Open a .lisp file
2. Start a repl (:repl, SPC c r, or C-c C-z)
3. Evaluate something, e.g., '(1 2 3) by entering insert mode, typing it, and pressing return
4. Press M-p
5. Receive message that M-p is unbound

I've reverted changes back to the first commit (6a6652d394cb0069dc4fcaba6f62d81b119ffc8e) implementing sly features but the problem remains.
I've also reverted the sly version without any luck.

The problem only occurs when the popup feature is enabled.
I traced the issue to ...

```
(defvar +popup-buffer-mode-map
  (let ((map (make-sparse-keymap)))
    (when (featurep! :feature evil)
      ;; for maximum escape coverage in emacs state buffers
      (define-key map [escape] #'doom/escape)
      (define-key map (kbd "ESC") #'doom/escape))
    map)
  "Active keymap in popup windows. See `+popup-buffer-mode'.")

```

Removing the second key define so that ...

```
(defvar +popup-buffer-mode-map
  (let ((map (make-sparse-keymap)))
    (when (featurep! :feature evil)
      ;; for maximum escape coverage in emacs state buffers
      (define-key map [escape] #'doom/escape))
    map)
  "Active keymap in popup windows. See `+popup-buffer-mode'.")

```
... fixes the issue. 

Disabling popup mode before calling the repl also works.

I've made a patch for this for myself, but I'm hesitant submitting a pull request as I neither fully understand why both defines are needed, nor the underlying reason for the bug.

### System information

<details>
<summary>Click to expand</summary>
- OS: gnu/linux (x86_64-pc-linux-gnu)
- Emacs: 26.1 (Jul 05, 2018)
- Doom: 2.0.9 (develop 96bea9e9ad4f3e3412472fa0f26a19d19be66a1a)
- Graphic display: t (daemon: nil)
- System features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LIBSYSTEMD LCMS2
- Details:
  ```elisp
  elc count: 0
  uname -a:  Linux <removed> 4.18.5-arch1-1-ARCH #1 SMP PREEMPT Fri Aug 24 12:48:58 UTC 2018 x86_64 GNU/Linux
  modules:   (:feature eval (evil +everywhere) file-templates (lookup +devdocs +docsets) snippets spellcheck (syntax-checker +childframe) workspaces :completion (ivy +fuzzy) :ui doom-dashboard doom-modeline doom-quit evil-goggles hl-todo nav-flash treemacs (popup +all +defaults) vc-gutter vi-tilde-fringe window-select :editor rotate-text :emacs ediff electric hideshow imenu vc :tools magit :lang (cc +irony +rtags) common-lisp data emacs-lisp (latex +latexmk +okular) markdown (org +attach +babel +capture +export +present) python sh web :app :config :private)
  packages:  n/a
  exec-path: (/usr/local/sbin /usr/local/bin /usr/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /usr/lib/emacs/26.1/x86_64-pc-linux-gnu)
  ```

</details>

**Comment by hlissner** [comment]
Thanks for the detailed bug report! Emacs translates `meta + ...` keybinds to `ESC + ...` in the terminal. That second ESC keybind was to ensure ESC in the terminal would invoke `doom/escape`, but this inadvertently disables meta keybinds so I've removed it in a1440f8. This should resolve your issue.

Let me know if that isn't the case and I'll reopen this.

**Comment by arejensen** [comment]
> Thanks for the detailed bug report! Emacs translates `meta + ...` keybinds to `ESC + ...` in the terminal. That second ESC keybind was to ensure ESC in the terminal would invoke `doom/escape`, but this inadvertently disables meta keybinds so I've removed it in [a1440f8](https://github.com/hlissner/doom-emacs/commit/a1440f8d66c56f43743238752dfcf188540620d6). This should resolve your issue.
> 
> Let me know if that isn't the case and I'll reopen this.

Sorry for the late reply and thank you for the patch (and teaching me about the differences between terminal and GUI emacs)!

Now it works perfectly well in insert mode. In normal mode M-p works the same way as in insert mode, but M-n opens a new buffer.
It's not a big issue for me personally since I'm usually in insert mode when using the REPL, but wanted to let you know in case its unintended behavior.
