### ISSUE TITLE
How to globally disable line numbers?

### ISSUE THREAD

**Issue by chris-kahn** [hlissner/doom-emacs#870]
What is the correct way to `disable` line numbers? 

I've tried setting `display-line-numbers-type`, `doom-line-numbers-style`, `display-line-numbers` to nil and it doesn't do anything...

Toggling line numbers with `doom/toggle-line-numbers` only affects the current buffer.

**Comment by exrok** [comment]
I had a similar problem but as a temporary work-around you can add
```elisp
 (defun nullify-mode/func (&optional _ _) (interactive))
 (advice-add 'display-line-numbers-mode :around #'nullify-mode/func)
```
to you `config.el`. Although, then you won't be able to toggle line numbers via dooms interface.

**Comment by exrok** [comment]
@hlissner I'm using Emacs 26 and `(setq display-line-numbers-type nil)` worked perfect, less hacks in my config now :).

**Comment by chris-kahn** [comment]
There must have been something else in my config conflicting... I tried with an empty config and `(setq display-line-numbers-type nil)`, confirming that this works.
