### ISSUE TITLE
def-package! in config file

### ISSUE THREAD

**Issue by chris-kahn** [hlissner/doom-emacs#871]
After reading the documentation I'm a little confused about how to include packages in my `~/.doom.d/config.el` file. I would suggest putting adding a complete example in the Wiki.

I'm trying to switch back to highlight-indent-guides mode because I prefer the character-based guides. I've added the following to my config:

```
(def-package! highlight-indent-guides
  :commands highlight-indent-guides-mode
  :hook (prog-mode . highlight-indent-guides-mode)
  :config
  (setq highlight-indent-guides-method 'character
        highlight-indent-guides-character ?\•
        highlight-indent-guides-delay 0.01
        highlight-indent-guides-responsive 'top
        highlight-indent-guides-auto-enabled nil))
```

but I get an error: `Cannot open load file: No such file or directory, highlight-indent-guides`. Am I missing something? 

Using doom `develop` and `emacs-plus --HEAD` from homebrew.

**Comment by hlissner** [comment]
I apologize for the underdeveloped documentation. It is something I am currently working on.

The trick to adding a new package is to add a `package!` statement to your private `~/.doom.d/packages.el` file. Like so:

```elisp
;; -*- no-byte-compile: t; -*-
;;; ~/.doom.d/packages.el

(package! highlight-indent-guides)
```

Then run `bin/doom refresh` (or `make`; they are equivalent).

**Comment by chris-kahn** [comment]
I had tried adding that file as well without any luck, and the final piece I was missing was to run `doom refresh`. I was only running `doom clean && doom compile :core`. All good now!

So it seems like the `.doom.d` folder is basically a private module?

No need to apologize, I appreciate you answering my questions, and you've already gone above and beyond with this project. Impressive work!

**Comment by hlissner** [comment]
> `doom clean && doom compile :core`

It is unnecessary to call `doom clean` yourself. All `doom compile` commands will do it for you before compiling.

> So it seems like the .doom.d folder is basically a private module?

That is correct.

> Impressive work!

Thank you! I'm glad Doom suits you.
