### ISSUE TITLE
.authinfo.gpg not taken into account when password-store is enabled

### ISSUE THREAD

**Issue by brabalan** [hlissner/doom-emacs#877]
### Observed behavior

Start gnus, which needs some passwords encrypted in .authinfo.gpg to connect. I'm asked the passwords at the prompt.

### Expected behavior

Ask me for the symmetric key used to encrypt .authinfo.gpg.

### Additional notes

My .authinfo.gpg is symmetrically encrypted. I use different gpg keys for pass and for email signing/encrypting, but they share the same email address.

**Comment by hlissner** [comment]
As of fad1fc8 this _should_ be fixed, but it needs more testing. Please update Doom and let me know if it resolves your issue.

**Comment by brabalan** [comment]
It resolves my issue, thanks a lot.
