### ISSUE TITLE
go-mode gofmt error

### ISSUE THREAD

**Issue by shuxiao9058** [hlissner/doom-emacs#878]
Error message is:
```
File mode specification error: (invalid-function (gofmt-before-save t ws-butler-before-save))
```

**Comment by hlissner** [comment]
Could you provide a backtrace for this error? i.e. 

1. `M-x toggle-debug-on-error`
2. Trigger the error again
3. Copy the contents of the backtrace buffer into pastebin and post the link here.

**Comment by shuxiao9058** [comment]
[https://pastebin.com/6uhTT9Ai](url)

**Comment by hlissner** [comment]
This backtrace suggests you have this in your config: 

```elisp
(add-hook 'go-mode-hook #'gofmt-before-save nil t)
```

Let me know if that isn't the case, but if it _is_, remove it and:

1. Enable the `:editor format` module
2. Add `(add-hook 'go-mode-hook #'+format|enable-on-save)` to your config.el

OR

Use this instead:

```elisp
(add-hook 'before-save-hook #'gofmt-before-save)
```

But then this would defeat the purpose of lazy-loading.

**Comment by shuxiao9058** [comment]
Yes, it works fine now,Thank you.
