### ISSUE TITLE
Notes org-capture templates puts files all over the place

### ISSUE THREAD

**Issue by ccressent** [hlissner/doom-emacs#886]
### Observed behavior

The Notes capture template targets the `+org-default-notes-file` file in `default-directory` instead of `org-directory`.

### Expected behavior

Target the `+org-default-notes-file` file in `org-directory`, just like the Todo template would target the `+org-default-todo-file` file in `org-directory`.

### Steps to reproduce

1. Open a file
2. `SPC X` to start `org-capture`
3. Select the notes template
4. `C-c C-c` to capture

The note will end up in `default-directory/+org-default-notes-file`

### Possible solution

`+org-default-notes-file` is not initialized correctly?
If so, adding the following to `+org|init-capture` in `modules/lang/org/+capture.el` should do the trick:

```
(setq +org-default-notes-file org-default-notes-file)
```

Alternatively, change the template to target `org-default-notes-file` instead of `+org-default-notes-file`.

### System information

<details>
<summary>Click to expand</summary>

```
- OS: gnu/linux (x86_64-pc-linux-gnu)
- Emacs: 26.1 (Jul 05, 2018)
- Doom: 2.0.9 (develop 96bea9e9ad4f3e3412472fa0f26a19d19be66a1a)
- Graphic display: t (daemon: nil)
- System features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LIBSYSTEMD LCMS2
- Details:
  ```elisp
  elc count: 0
  uname -a:  Linux ccx1c6 4.18.6-arch1-1-ARCH #1 SMP PREEMPT Wed Sep 5 11:54:09 UTC 2018 x86_64 GNU/Linux
  modules:   (:feature (evil +everywhere) file-templates (lookup +devdocs +docsets) snippets spellcheck (syntax-checker +childframe) workspaces :completion (helm +fuzzy) :ui doom-dashboard doom-modeline doom-quit evil-goggles fci hl-todo nav-flash treemacs (popup +all +defaults) vc-gutter vi-tilde-fringe window-select :editor rotate-text :emacs ediff electric hideshow imenu vc :tools magit :lang emacs-lisp go markdown (org +attach +babel +capture +export +present) (sh +fish) :config)
  packages:  n/a
  exec-path: (/usr/local/bin /usr/bin /bin /usr/local/sbin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl ~/go/bin /usr/lib/emacs/26.1/x86_64-pc-linux-gnu)
  ```

**Comment by hlissner** [comment]
Thanks for the detailed bug report! As of 80e8ccec, this should be resolved. Please update and let me know if that's not the case and I will reopen this.

**Comment by ccressent** [comment]
I've since defined my own org templates and they are not using those variables, so the issue doesn't affect me anymore anyway! :)

But having a quick look at 80e8cce, `org-default-notes-file` now appears to be undefined? I don't think notes captures will end up in the `notes.org` file as it was originally the intention.
