### ISSUE TITLE
exec-path in emacs is not consistent with define in shell 

### ISSUE THREAD

**Issue by driftcrow** [hlissner/doom-emacs#887]
### Observed behavior

I add a new path entry in shell both in bash and zsh rc files(.bash_profile and .zshrc), and relogin . then echo $PATH in shell is correct. but when I run emacs and describe-variable exec-path is not consistent with shell. 

and when I run bin/doom info in shell the exec-path value in output  is also different when I exec M-x doom/info in emacs.

### Expected behavior

exec-path in emacs is consistent with PATH in shell

### Steps to reproduce

1. change some path in .bash_profile then relogin
2. echo $PATH in shell
3. describe-variable exec-path then compare two value
or:
4. run bin/doom info in shell within .emacs.d dir
5. M-x doom/info then show clipborad, compare exec-path in both output

### System information

<details>
<summary>Click to expand</summary>

doom/info in emacs

```
- OS: gnu/linux (x86_64-pc-linux-gnu)
- Emacs: 26.1 (Jul 05, 2018)
- Doom: 2.0.9 (develop 856e4f27e54c9db63c7389c4097203ebff82e9c5)
- Graphic display: t (daemon: nil)
- System features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LIBSYSTEMD LCMS2
- Details:
  ```elisp
  elc count: 0
  uname -a:  Linux folder 4.18.6-arch1-1-ARCH #1 SMP PREEMPT Wed Sep 5 11:54:09 UTC 2018 x86_64 GNU/Linux
  modules:   (:feature (evil +everywhere) file-templates (lookup +docsets) snippets spellcheck (syntax-checker +childframe) workspaces :completion (ivy +fuzzy) :ui doom-dashboard doom-modeline doom-quit evil-goggles hl-todo nav-flash treemacs (popup +all +defaults) vc-gutter vi-tilde-fringe window-select :editor rotate-text :emacs ediff electric hideshow imenu term vc :tools magit pdf tmux upload :lang emacs-lisp javascript latex ledger lua markdown (org +attach +babel +capture +export +present) plantuml python (sh +fish) web :app irc (write +wordnut +langtool) :config :private org chinese)
  packages:  (atomic-chrome cal-china-x cnfonts counsel-tramp diffview discover-my-major docker-tramp drag-stuff electric-operator fcitx graphviz-dot-mode keyfreq list-environment lsp-python org-brain (org-clock-budget :recipe (org-clock-budget :fetcher github :repo Fuco1/org-clock-budget)) org-clock-convenience org-fancy-priorities org-super-agenda org-web-tools org-wild-notifier orgit pinyinlib pipenv py-isort restart-emacs sx tldr try whitespace-cleanup-mode (yapfify :recipe (yapfify :fetcher github :repo JorisE/yapfify)) youdao-dictionary ztree)
  exec-path: (/opt/google-cloud-sdk/bin /usr/local/bin /usr/bin /bin /usr/local/sbin /opt/cuda/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /usr/lib/emacs/26.1/x86_64-pc-linux-gnu)
  ```

```

---
bin/doom info in shell

```
Generating Doom info...
Initializing modules
- OS: gnu/linux (x86_64-pc-linux-gnu)
- Emacs: 26.1 (Jul 05, 2018)
- Doom: 2.0.9 (develop 856e4f27e54c9db63c7389c4097203ebff82e9c5)
- Graphic display: nil (daemon: nil)
- System features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LIBSYSTEMD LCMS2
- Details:
  ```elisp
  elc count: 0
  uname -a:  Linux folder 4.18.6-arch1-1-ARCH #1 SMP PREEMPT Wed Sep 5 11:54:09 UTC 2018 x86_64 GNU/Linux
  modules:   (:feature (evil +everywhere) file-templates (lookup +docsets) snippets spellcheck (syntax-checker +childframe) workspaces :completion (ivy +fuzzy) :ui doom-dashboard doom-modeline doom-quit evil-goggles hl-todo nav-flash treemacs (popup +all +defaults) vc-gutter vi-tilde-fringe window-select :editor rotate-text :emacs ediff electric hideshow imenu term vc :tools magit pdf tmux upload :lang emacs-lisp javascript latex ledger lua markdown (org +attach +babel +capture +export +present) plantuml python (sh +fish) web :app irc (write +wordnut +langtool) :config :private org chinese)
  packages:  (atomic-chrome cal-china-x cnfonts counsel-tramp diffview discover-my-major docker-tramp drag-stuff electric-operator fcitx graphviz-dot-mode keyfreq list-environment lsp-python org-brain (org-clock-budget :recipe (org-clock-budget :fetcher github :repo Fuco1/org-clock-budget)) org-clock-convenience org-fancy-priorities org-super-agenda org-web-tools org-wild-notifier orgit pinyinlib pipenv py-isort restart-emacs sx tldr try whitespace-cleanup-mode (yapfify :recipe (yapfify :fetcher github :repo JorisE/yapfify)) youdao-dictionary ztree)
  exec-path: (~/bin ~/bin /usr/local/bin /usr/local/sbin /opt/google-cloud-sdk/bin /opt/anaconda/bin ~/bin /usr/bin /bin /opt/cuda/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /usr/lib/emacs/26.1/x86_64-pc-linux-gnu)
  ```

```
</details>

**Comment by driftcrow** [comment]
seem  linux environment's problem

**Comment by hlissner** [comment]
With issues like these, there are two common possibilities:

1. How do you launch Emacs? Launchers like rofi and dmenu won't open programs with your shell, and so Emacs isn't launched from the correct shell environment. You'll need to correct this if that's the case. For rofi, folks generally invoke it using a keybind, so something like this would work:

   ```sh
   rofi -run-command "zsh -c '{cmd}'"
   ```

   Alternatively, you could write an emacs shim and put it somewhere in your PATH:

   ```sh
   #!/usr/bin/env zsh
   zsh -c emacs
   ```

2. In which dotfiles do you set up your `PATH`? If, by chance, you are using a well-behaved app launcher, it is possible that Emacs is being opened in a _non-interactive_ shell. `.zshrc` and `.bashrc` are only read in interactive zsh sessions, while `.zshenv` and `.bash_profile` are read for non-interactive sessions. As long as your `PATH` is set up accordingly, `exec-path` should reflect the correct PATH.

**Comment by driftcrow** [comment]
Thanks for declare these
