### ISSUE TITLE
pipenv-mode fails to find correct Pipfile

### ISSUE THREAD

**Issue by dmgening** [hlissner/doom-emacs#888]
### Observed behavior

Given the following project structure visiting any python file deeper than l3 will create new `Pipfile` and fails to set correct python path.
```
.
├── Pipfile
├── Pipfile.lock
└── l1
    ├── __init__.py
    └── l2
        ├── __init__.py
        └── l3
            ├── __init__.py
            └── l4
                └── __init__.py
```

### Expected behavior

Visiting any file inside the project should reference correct Pipfile and do not create any extras.

### Steps to reproduce

1. Create new project with Pipfile at project root.
2. Create multiple nested dirs and python files inside
3. Visit python file in 2 or more levels nesting from Pipfile 
4. New Pipfile would be created at the location of the file you visited

### System information

<details>
<summary>Click to expand</summary>

```
- OS: darwin (x86_64-apple-darwin14.5.0)
- Emacs: 26.1 (May 31, 2018)
- Doom: 2.0.9 (develop 9684b34389e3925d7156103536cbc5ecb73854f0)
- Graphic display: t (daemon: nil)
- System features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS
- Details:
  elisp
  elc count: 0
  uname -a:  Darwin earthshaker.local 17.6.0 Darwin Kernel Version 17.6.0: Tue May  8 15:22:16 PDT 2018; root:xnu-4570.61.1~1/RELEASE_X86_64 x86_64
  modules:   (:feature (evil +everywhere) file-templates (lookup +devdocs +docsets) snippets spellcheck (syntax-checker +childframe) workspaces :completion (ivy +fuzzy +posframe) :ui doom-dashboard doom-modeline doom-quit evil-goggles hl-todo nav-flash neotree (popup +all +defaults) vc-gutter vi-tilde-fringe window-select :editor :emacs ediff electric eshell imenu term vc :tools macos make magit docker :lang emacs-lisp javascript lua markdown (org +attach +babel +capture +export +present) plantuml (python +pyenv +ipython) sh web :config)
  packages:  n/a
  exec-path: (/usr/local/bin/ /usr/local/sbin/ /usr/bin/ /bin/ /usr/sbin/ /sbin/ /Applications/Emacs.app/Contents/MacOS/bin-x86_64-10_10/ /Applications/Emacs.app/Contents/MacOS/libexec-x86_64-10_10/ /Applications/Emacs.app/Contents/MacOS/libexec/)

```
</details>

**Comment by dmgening** [comment]
I've narrowed the problem down to `(+python-version)` function https://github.com/hlissner/doom-emacs/blob/9684b34389e3925d7156103536cbc5ecb73854f0/modules/lang/python/autoload/python.el#L17

While `(pipenv-project-p)` reports correct `Pipfile` location `pipenv run python --version` searching `Pipfile` on his own hitting depth limit fast. Due `pipenv` logic if it can not find project root (i.e. Pipfile) it will create a new one in cwd. 

Fast workaround for this issue is to set `PIPENV_MAX_DEPTH` to the reasonably high number.

**Comment by hlissner** [comment]
If I set PIPENV_MAX_DEPTH to a high number and it _still_ doesn't find a Pipfile, does it still create one in the cwd?

**Comment by hlissner** [comment]
As of ccaa642 this should be fixed. Please update and let me know if that isn't the case and I will reopen this.

Thanks for the detailed bug report!

**Comment by dmgening** [comment]
Works like a charm. Thank you!
