### ISSUE TITLE
feature request: key-binding for doom/window-zoom

### ISSUE THREAD

**Issue by PoiScript** [hlissner/doom-emacs#890]
`doom/window-zoom` is more common used than `doom/window-enlargen` and it really deserves a key-binding :).If you don't mind, I can send a pull request after that.

**Comment by hlissner** [comment]
Done! It is now bound to `C-w O`. If you never use `doom/window-enlargen`, you can swap them with:

```elisp
(map! :map evil-window-map
      "o" #'doom/window-zoom
      "O" #'doom/window-zoom)
```
