### ISSUE TITLE
Disable Blinking Cursor in PDFView mode

### ISSUE THREAD

**Issue by mustaqimM** [hlissner/doom-emacs#892]
With evil enabled, the cursor blinks when in PDFView mode. Ideally, the cursor bar should not be shown.

I'm still understanding Emacs and lisp but I thought this would work:
```lisp
(after! pdf-view-mode-hook
  (setq blink-cursor-mode nil))
```

I got it to work by setting:
```lisp
(after! pdf-tools-modes
  (add-hook! 'pdf-view-mode-hook (blink-cursor-mode -1)))
```

But how do I hide it completely or colour it match the page?

**Comment by mustaqimM** [comment]
No it doesn't, and the line I quoted above as working before, doesn't seem to anymore

**Comment by hlissner** [comment]
As it turns out, `blink-cursor-mode` is a global mode, so there's no disabling it for one buffer.

So instead, try adding `(blink-cursor-mode -1)` to your private config.el. I intend to disable it in an upcoming update, as it's proven too distracting in many cases.

**Comment by hlissner** [comment]
I've disabled `blink-cursor-mode` globally, which should resolve your issue. Could you update and give it a try? If not, I can explicitly disable the cursor in pdf-view-mode with:

```elisp
  (add-hook! 'pdf-view-mode-hook (internal-show-cursor nil nil))
```

**Comment by mustaqimM** [comment]
Yes! It's working, though I prefer
```lisp
(add-hook! 'pdf-view-mode-hook (internal-show-cursor nil nil))
```
because it doesn't show the cursor at all, the `(blink-cursor-mode -1)` option still shows the cursor as a blue border around the page

**Comment by hlissner** [comment]
And done! I'll consider this resolved. Let me know if it gives you any more trouble.

**Comment by hlissner** [comment]
I had to revert fd7f498 due to an issue with the cursor becoming invisible in other windows when restoring a session.
