### ISSUE TITLE
Not having a formatter set stops other before-save-hooks from being run

### ISSUE THREAD

**Issue by robbert-vdh** [hlissner/doom-emacs#893]
### Observed behavior

When saving a buffer that doesn't have an associated formatter (e.g. `conf-mode`) with the `+onsave` module option enabled,`+format-buffer` will throw an [error](https://github.com/hlissner/doom-emacs/blob/daccdc3e53e6a095e56f149e4cfe2545030123b9/modules/editor/format/autoload/format.el#L124) blocking other `before-save-hook`s such as `ws-butler-before-save` from behind run.

### Expected behavior

The other hooks should still be run.

### Steps to reproduce

1. Open a `.conf` file.
2. `(setq before-save-hook '(+format-buffer t ws-butler-before-save))` (in case these weren't set already).
3. Append trailing whitespace to some line.
4. Save the buffer.

### System information

<details>
<summary>Click to expand</summary>

- OS: gnu/linux (x86_64-pc-linux-gnu)
- Emacs: 26.1 (jul 05, 2018)
- Doom: 2.0.9 (develop daccdc3e53e6a095e56f149e4cfe2545030123b9)
- Graphic display: t (daemon: t)
- System features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LIBSYSTEMD LCMS2
- Details:
  ```elisp
  elc count: 28
  uname -a:  Linux desktop 4.18.7-arch1-1-ARCH #1 SMP PREEMPT Sun Sep 9 11:27:58 UTC 2018 x86_64 GNU/Linux
  modules:   (:feature eval (evil +everywhere) file-templates (lookup +devdocs +docsets) snippets spellcheck (syntax-checker +childframe) workspaces :completion (helm +fuzzy) :ui doom-modeline doom-quit evil-goggles hl-todo nav-flash treemacs (popup +all +defaults) vc-gutter vi-tilde-fringe window-select :editor multiple-cursors rotate-text :emacs ediff electric eshell hideshow imenu term vc :tools ein docker gist make magit pdf prodigy rgb upload :lang data emacs-lisp ess (haskell +intero) javascript latex (markdown +pandoc) (org +attach +babel +capture +export +present) php python rest rust (sh +fish) web :app :config)
  packages:  (atomic-chrome company-lsp (company-racer :ignore t :disable t) ein evil-lion ggtags kotlin-mode (lsp-css :recipe (lsp-css :fetcher github :repo emacs-lsp/lsp-css)) lsp-intellij lsp-mode lsp-rust lsp-ui page-break-lines phpcbf pkgbuild-mode (racer :ignore t :disable t))
  exec-path: (~/.cargo/bin ~/.local/bin /usr/local/sbin /usr/local/bin /usr/bin /usr/lib/emacs/26.1/x86_64-pc-linux-gnu)
  ```

</details>

**Comment by hlissner** [comment]
`+format-buffer` is not the correct function to use. It's a public function that errors if anything goes wrong (e.g. no formatter is specified).

The correct methods to enable formatting when saving are:

1. Add `+format|enable-on-save` to the mode's hook. e.g. 

   ```elisp
   (add-hook 'python-mode-hook #'+format|enable-on-save)
   ```

2. Or add `+format|buffer` to before-save-hook, either globally or locally, e.g.

   ```elisp
   (add-hook 'before-save-hook #'+format|buffer)
   ;; or buffer locally:
   (add-hook 'before-save-hook #'+format|buffer nil t)
   ```

3. Use the `+onsave` module flag for the `:editor format` module. This is the equivalent of adding `+format|buffer` to the global `before-save-hook`, except `+format-on-save-enabled-modes` serves as its white/blacklist.

**Comment by robbert-vdh** [comment]
I made a typo! `+format-buffer` should indeed have been `+format|buffer`. The problem is that `+format|buffer` doesn't handle thrown errors like I think it should. For example, running `(+format|buffer)` in my i3 config file will still throw a user error:

```
user-error: Don’t know how to format ’conf-space-mode’ code
```

This shouldn't be a problem, but when this happens during `(run-hooks 'before-save-hook)` in Emacs' built in `file.el.gz` it will block any remaining functions (like the default `ws-butler-before-save`) from being run.

**Comment by hlissner** [comment]
You are correct. I've made a few changes in 6a44cf0 that should resolve your issue. Let me know if that isn't the case and I'll reopen this.
