### ISSUE TITLE
Visual block modeline indicator not shown on `C-v`

### ISSUE THREAD

**Issue by seagle0128** [hlissner/doom-emacs#895]
https://github.com/hlissner/doom-emacs/blob/ed0857b988db8fc419e31692ca1ad2974c830bbf/modules/ui/doom-modeline/config.el#L598

Refer to https://github.com/seagle0128/doom-modeline/issues/27.

**Comment by hlissner** [comment]
Thanks for letting me know! As of d332f00 this should be resolved. Let me know if that isn't the case and I'll reopen this.

**Comment by seagle0128** [comment]
Looks good with me.
