### ISSUE TITLE
TAB completion not working in Org-mode with Helm

### ISSUE THREAD

**Issue by Yumasi** [hlissner/doom-emacs#897]
### Observed behavior

When trying to add a link to a file in Org-mode, Helm opens up to choose the file, but when taping the TAB key to complete the folder name, it fails with the message:
`Cannot split side window or parent of side window`

### Expected behavior

The TAB key should complete the name of the selected file (or folder) like in other modes.

### Steps to reproduce

1. Open an org file
2. Add a link with C-c C-l
3. Choose `file:`
4. Try to autocomplete a folder name with TAB.

### System information

<details>
<summary>Click to expand</summary>

```
- OS: gnu/linux (x86_64-pc-linux-gnu)
- Emacs: 26.1 (Jun 06, 2018)
- Doom: 2.0.9 (develop ed0857b988db8fc419e31692ca1ad2974c830bbf)
- Graphic display: t (daemon: nil)
- System features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 THREADS LCMS2
- Details:
  ```elisp
  elc count: 0
  uname -a:  Linux aiur 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u4 (2018-08-21) x86_64 x86_64 x86_64 GNU/Linux
  modules:   (:feature eval (evil +everywhere) file-templates (lookup +docsets) snippets spellcheck (syntax-checker +childframe) workspaces :completion (helm +fuzzy) :ui doom-dashboard doom-modeline doom-quit evil-goggles fci hl-todo nav-flash treemacs (popup +all +defaults) vc-gutter vi-tilde-fringe window-select :editor rotate-text :emacs ediff electric eshell hideshow imenu term vc :tools editorconfig make magit pdf rgb :lang (cc +irony +rtags) data emacs-lisp markdown (org +attach +babel +capture +export +present) python (sh +fish) :config)
  packages:  (bitbake)
  exec-path: (/app/bin /usr/bin /app/libexec/emacs/26.1/x86_64-pc-linux-gnu)
  ```
</details>

**Comment by duianto** [comment]
Confirmed

A workaround is to press `C-M-/`,  the minibuffer shows the message: `Scanning for dabbrevs...done` 
and it completes until the next word branch.

<details><summary>System Info</summary><pre><code>
- OS: windows-nt (x86_64-w64-mingw32)
- Emacs: 26.1 (May 30, 2018)
- Doom: 2.0.9 (develop ed0857b988db8fc419e31692ca1ad2974c830bbf)
- Graphic display: t (daemon: nil)
- System features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2
- Details:
  ```elisp
  elc count: 28
  uname -a:  n/a
  modules:   (:feature (evil +everywhere) file-templates (lookup +docsets) snippets spellcheck (syntax-checker +childframe) workspaces :completion (helm +fuzzy) :ui doom-dashboard doom-modeline doom-quit evil-goggles hl-todo nav-flash treemacs (popup +all +defaults) vc-gutter vi-tilde-fringe window-select :editor rotate-text :emacs ediff electric hideshow imenu vc :tools :lang emacs-lisp markdown (org +attach +babel +capture +export +present) (sh +fish) :config)
  packages:  n/a
  exec-path: (c:/Users/username/Applications/emacs-26.1-x86_64/bin C:/Python37/Scripts/ C:/Python37/ C:/WINDOWS/system32 C:/WINDOWS C:/WINDOWS/System32/Wbem C:/WINDOWS/System32/WindowsPowerShell/v1.0/ C:/ProgramData/chocolatey/bin C:/tools/cygwin/bin C:/Program Files/AutoHotkey C:/Program Files/Microsoft VS Code C:/WINDOWS/System32/OpenSSH/ C:/Program Files/Git/cmd C:/Program Files/nodejs/ C:/Users/username/AppData/Local/Microsoft/WindowsApps . C:/Users/username/AppData/Local/Programs/Microsoft VS Code/bin c:/Users/username/Applications/emacs-26.1-x86_64/libexec/emacs/26.1/x86_64-w64-mingw32)
  ```
</code></pre></details>

**Comment by siddharthshekar** [comment]
I remember seeing this when I was using the "popup" module. I don't have it enabled anymore just tried tab completion with Helm for org file-links and it works fine for me.

**Comment by hlissner** [comment]
Thanks for the detailed bug report! As of b76a095, this issue should be resolved. Let me know if that isn't the case and I'll reopen this.
