### ISSUE TITLE
[Question] Remap C-h

### ISSUE THREAD

**Issue by monkoose** [hlissner/doom-emacs#901]
I'm new to emacs, found your repo helpful. 
For now only 1 thing that bothers me much is `C-h` as emacs help and not `delete char backward` as in terminal or vim.
Is it wise to remap it? Why it is so important that it has this convenient hotkey (homeraw)? 
If it is decent practice to remap `C-h` is there any resources where i can read how to remap it everywhere (command line, pumvisible equivalent etc.)?
Thank you.

**Comment by hlissner** [comment]
This is an Emacs default keybind. You may remap it if you'd like. There are no real consequences so long as you know that Doom provides other ways to access those help commands, through `SPC h ...` and `<f1> ...`. Remapping it is as simple as adding one of these to your `~/.doom.d/config.el` file:

```elisp
;; The doom way
(map! :ie "C-h" #'backward-delete-char-untabify)

;; The emacs way
(evil-define-key* '(insert emacs) 'global (kbd "C-h") #'backward-delete-char-untabify)
```

However, I cannot guarantee that this will have perfect coverage across Emacs. There are many modes, nooks and crannies where other C-h keybindings may override yours, but here are a few that come to mind:

```elisp
(map! (:map (minibuffer-local-map
             minibuffer-local-ns-map
             minibuffer-local-completion-map
             minibuffer-local-must-match-map
             minibuffer-local-isearch-map
             read-expression-map)
        "C-h" #'backward-delete-char-untabify)
      (:after evil
        :map evil-ex-completion-map
        "C-h" #'backward-delete-char-untabify)
      
      ;; If you use :completion ivy
      (:after ivy
        :map ivy-minibuffer-map
        "C-h" #'backward-delete-char-untabify)
      
      ;; If you use :completion helm
      (:after helm
        :map helm-map
        "C-h" #'backward-delete-char-untabify))
```

I hope that helps!

**Comment by monkoose** [comment]
Thank you. If you mind I keep this issue open for some time for testing and maybe more questions.
Actually maybe there any channel for some stupid/quick question like in the first post (irc/discord/telegram) more related to doom-emacs, not pure emacs?

**Comment by hlissner** [comment]
> If you mind I keep this issue open for some time for testing and maybe more questions.

Certainly. Otherwise, we have [a discord server](https://discord.gg/bcZ6P3y).

**Comment by brabalan** [comment]
I tried to apply this, and it works well for the most part, except in `org-mode`. There `C-h` calls `org-beginning-of-line`, even after trying to remap it:
```emacs-lisp
(map!
 (:after org
  :map org-mode-map
  "C-h" #'backward-delete-char-untabify))
```

Any hint on how to proceed? (I'm very surprised because `org-beginning-of-line` is only supposed to be mapped to `C-a` or `home`.)

**Comment by find1dream** [comment]
(map! :after evil-org
      :map evil-org-mode-map
      :i "C-h" #'backward-delete-char-untabify)
works
