### ISSUE TITLE
inf-ruby-console starting every time when I'm opening ruby file in project

### ISSUE THREAD

**Issue by idoo** [hlissner/doom-emacs#907]
it represent in latest `develop` branch

**Comment by hlissner** [comment]
This is a known issue with the lang/ruby, I just haven't gotten around to fixing them. I'll look into it soon.

**Comment by hlissner** [comment]
Sorry for the _really_ late response, but I think this has long since been resolved. If that isn't the case, let me know and I will reopen this.
