### ISSUE TITLE
Magit requires PGP

### ISSUE THREAD

**Issue by jmorag** [hlissner/doom-emacs#909]
Calling `magit-status` results in the error `GPG error: "no usable configuration", OpenPGP"`. Why should magit require GPG?

**Comment by hlissner** [comment]
This was likely caused by https://github.com/hlissner/doom-emacs/commit/fad1fc8f1b57b819a774c171b933b0866804044a.

https://github.com/hlissner/doom-emacs/commit/271e7689ae61be52e6967afc81f5723290eb5a0f should fix this. Please update and let me know if that isn’t the case.

**Comment by jmorag** [comment]
That does fix it. Out of curiosity, though, should I have PGP installed?

**Comment by hlissner** [comment]
It's not required. Unless you have a private+public key and sign your commits, read/write encrypted files in Emacs, or connect to secured sources through TRAMP (passwords are saved to an encrypted authinfo.gpg file), you won't need it for Doom or Emacs.

I make extensive use of GPG. I use [pass](https://www.passwordstore.org/) as my password manager, sign my github commits, have a [keybase profile](https://keybase.io/hlissner), read/write encrypted org files, and store secrets/passwords on my system encrypted, among other things.

**Comment by huos3203** [comment]
@hlissner 
```

```
