### ISSUE TITLE
multi-language auto-completion and navigation discussion

### ISSUE THREAD

**Issue by chengyi** [hlissner/doom-emacs#910]
Hi:
@hlissner On many case, project is written by c/c++, python, Java and so on. In this case, we only depands on tag system like ctags.  So the `cc` module now can't handle multi-lang project.

**Comment by hlissner** [comment]
Sorry for the late followup. Is this issue still relevant? I don't understand the issue.

**Comment by chengyi** [comment]
@hlissner  I don't know whether `languiage-server` could handle the multi-language project. Even if it can handle this, when the project is huge, it still use too much memory. I use `GNU global` to browse AOSP code now. It base on `doom-emacs` and my personal config, of course, it work perfect. Thanks to your awesome work again. I will spend some time to intergrate `gnu global` to doom-emacs.
