### ISSUE TITLE
Some eshell commands broken

### ISSUE THREAD

**Issue by jmorag** [hlissner/doom-emacs#912]
On macOS Sierra, a bunch of commands cause weird behavior in eshell. Running `brew` causes
```
Example usage:
  brew search [TEXT|/REGEX/]
  brew info [FORMULA...]
  brew install FORMULA...
  brew update
  brew upgrade [FORMULA...]
  brew uninstall FORMULA...
  brew list [FORMULA...]

Troubleshooting:
  brew config
  brew doctor
  brew install --verbose --debug FORMULA

Contributing:
  brew create [URL [--no-fetch]]
  brew edit [FORMULA...]

Further help:
  brew commands
  brew help [COMMAND]
  man brew
  https://docs.brew.sh

Process /bin/bash exited abnormally with code 1
```
this to show up without going back to the eshell prompt. `bash --version` just blinks the screen.  There are many other examples of commands behaving strangely. Since eshell is marked as WIP in the example init.el I'm not too surprised by the erratic behavior, but I thought it might be helpful to report it.

If a more thorough list of strange command behaviors would be of use, I can try to stress test eshell and report back, but if you already are aware of all of these, I apologize for the noise. Thanks again for all of your hard work on this. Everybody here is, I'm sure, very grateful to you for all the time and energy you've put into Doom.

**Comment by hlissner** [comment]
This appears to be an eshell+homebrew issue. Some commands are too complicated for eshell to display. For example, `top`, `bash` or `tmux`. So it tries to open them in a `term` window.

`brew` spawns a bash subshell and eshell assumes the worst.

You can try to fix brew, specifically, by removing `bash` from `eshell-visual-commands` (a list of commands eshell won't try to handle):

```elisp
(after! eshell
  (setq eshell-visual-commands (delete "bash" eshell-visual-commands)))
```

Perhaps this will resolve your other issues, just don't try to run an interactive bash shell from eshell.

**Comment by bricewge** [comment]
I had a similar issue on NixOS where most of the commands are wrapped like this:
``` sh
#! /nix/store/zqh3l3lyw32q1ayb15bnvg9f24j5v2p0-bash-4.4-p12/bin/bash -e
export PATH='/nix/store/6lkl4g8jbg0m4fgl5s1jclafic2k6lhx-git-2.16.2/bin:/nix/store/7ql8gbcb514nhhkhrymi0vhr8xgbv13a-subversion-1.9.7/bin:/nix/store/d7gspk4njym9k88qk2a3sqjasi8ab2z6-mercurial-4.5/bin:/nix/store/yy3bwcj44yndcvnx4a6lqzpwwdgl3slw-bazaar-2.7.0/bin'${PATH:+':'}$PATH
exec -a "$0" "/nix/store/7pn2gpn21dwvk54kqx8nvq7h762xjxxy-go-1.10/share/go/bin/.go-wrapped"  "${extraFlagsArray[@]}" "$@"
```
It resulted in the error `-e: command not found` from eshell.

A tweak from the answer of @hlissner fixed it for me:
``` lisp
(after! eshell
  (after! em-term
    (setq eshell-visual-commands (delete "bash" eshell-visual-commands))))
```
