### ISSUE TITLE
Fake hang on first install

### ISSUE THREAD

**Issue by nedludd** [hlissner/doom-emacs#913]
### Observed behavior

On first install the make appears to hang, but apparently is waiting for the answer to a prompt.

### Steps to reproduce

1. Clone Doom
2. Copy `init.example.el` to `init.el`
3. Run `make install`
4. See this:
<img width="272" alt="_usr_local_bin_grc_-es_--colour_auto_make" src="https://user-images.githubusercontent.com/17875/46172948-e6db6b80-c272-11e8-9bbc-a2c4bec695c1.png">
Installation completes after you press `y<CR>`.  The prompt to continue had scrolled off the screen.

### System information

<details>
<summary>Click to expand</summary>

```
DOOM Doctor
Running Emacs v27.0.50, commit 5dacbb7cb1c6ac246a9ccd15e6c4290def67757c

shell: /bin/zsh
Compiled with:
  RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS
  MODULES THREADS CANNOT_DUMP LCMS2
uname -a:
  Darwin crealab.local 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21
  22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64 i386
  MacBookPro12,1 Darwin

Attempt to load DOOM: success! Loaded v2.0.9
Revision 5dacbb7cb1c6ac246a9ccd15e6c4290def67757c

```
</details>

**Comment by hlissner** [comment]
Please switch to the `develop` branch. It is currently 3300+ commits ahead (I'm working on a big merge). This and many other issues have been fixed there.

Note that the install instructions have changed slightly. The [README on the develop branch](https://github.com/hlissner/doom-emacs/tree/develop#quick-start) reflects this. Private configuration has been moved to `~/.doom.d` (or `~/.config/doom`, whichever it detects first).

We also have [a Discord](https://discord.gg/bcZ6P3y), if you need any more help.

**Comment by nedludd** [comment]
Oh my, it has changed a lot!  :-)

I’ll check it out.  Thanks for the super quick response.

Keep up the good work.
