### ISSUE TITLE
How to map keybinds for built-in modes like c++-mode?

### ISSUE THREAD

**Issue by FirstLoveLife** [hlissner/doom-emacs#920]
### first try(in my `+bindings.el`)
```
    (require 'persp-mode)
    (map!
     :nm "f" #'avy-goto-char-2
     :i "M-1"(lambda! (+workspace/switch-to 0))
     :i "M-2"(lambda! (+workspace/switch-to 1))
     :i "M-3"(lambda! (+workspace/switch-to 2))
     :i "M-4"(lambda! (+workspace/switch-to 3))
     :i "M-5"(lambda! (+workspace/switch-to 4))
     :i "M-6"(lambda! (+workspace/switch-to 5))
     :i "M-7"(lambda! (+workspace/switch-to 6))
     :i "M-8"(lambda! (+workspace/switch-to 7))
     :i "M-9"(lambda! (+workspace/switch-to 8))

     :map c++-mode-map
       :leader
       :desc "Include header and format buffer" :nv "ih" (lambda! (my/cpp-auto-include)) )
```

```
Warning (initialization): An error occurred while loading ‘/home/firstlove/.emacs.d/init.el’:

Error in private config: +bindings.el, (void-variable c++-mode-map)

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.
```

That's also why do I `(require 'perse-mode)`(Now I know that it can be placed in `after! perse-mode`

### second try(in config.el):
```
(after! c++-mode
      (map!
       :map c++-mode-map
       :leader
       :desc "Include header and format buffer" :nv "ih" (lambda! (my/cpp-auto-include))) )
```

`SPC ih` is undefined.

### third try:

```
(after! ccls
      (map!
       :map c++-mode-map
       :leader
       :desc "Include header and format buffer" :nv "ih" (lambda! (my/cpp-auto-include))) )
```

Now it works as I expected. But, iiuc, it will fail once `ccls` didn't load. 

I also have look `/modules/config/default/+bindings.el`, but they are all maps for thiry-party packages.

How to map keybinds for built-in modes like c++-mod properly?

**Comment by hlissner** [comment]
This should work:

```elisp
(map! :after cc-mode
      :map c++-mode-map
      :leader
      :nv "ih" (lambda! (my/cpp-auto-include)))
```

1. `:after` is the same as `after!`. However, you need to give this a package name, not the name of a mode or variable. You can see what package `c++-mode` is defined in with `SPC h f c++-mode`.

   ![image](https://user-images.githubusercontent.com/510883/46247627-2ec9d200-c3dc-11e8-835d-fdb03675a24d.png)

   `function defined in cc-mode.el.gz` --> therefore he package name is `cc-mode`.

2. I recommend you do not use `:desc` for buffer-local keybinds (currently, :desc does not support this, it will display _all_ `SPC i h`, anywhere, with this description.

3. I recommend you use `:localleader` for buffer-local keybinds (`:leader`'s purpose is for global keybinds, while `:localleader` is for mode/buffer-local keybinds, hence the name).

4. If `my/cpp-auto-include` is an interactive function, you do not need to wrap it in `lambda!`, just do:

   ```elisp
   (map! :after cc-mode
         :map c++-mode-map
         :leader
         :nv "ih" #'my/cpp-auto-include)
   ```

Hope that helps!
