### ISSUE TITLE
Warnings about evil-want-integration and :eval setting

### ISSUE THREAD

**Issue by mjmeintjes** [hlissner/doom-emacs#931]
### Observed behavior
When starting up, the following warnings appear in messages

Warning (evil-collection): Make sure to set `evil-want-integration' to nil before loading evil or evil-collection.
The ‘:eval’ setting is deprecated, use ‘set-eval-handler!’ instead
evil-collection error: (file-missing Cannot open load file No such file or directory evil-collection-vc-git)

### Expected behavior
Not sure if these warnings should be here.

### Steps to reproduce

Just install the latest doom-emacs and start up emacs.

### System information

<details>
<summary>Click to expand</summary>

```
- OS: gnu/linux (x86_64-pc-linux-gnu)
- Emacs: 26.1 (May 29, 2018)
- Doom: 2.0.9 (develop d8dbd0759cad2b1c52bf6dc3019a55cb2850408e)
- Graphic display: t (daemon: t)
- System features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS XWIDGETS LIBSYSTEMD LCMS2
- Details:
  ```elisp
  elc count: 0
  uname -a:  Linux matt-ubuntu 4.15.0-34-generic #37-Ubuntu SMP Mon Aug 27 15:21:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
  modules:   (:feature (evil +everywhere) file-templates (lookup +docsets) snippets spellcheck (syntax-checker +childframe) workspaces :completion (helm +fuzzy) :ui doom-dashboard doom-modeline doom-quit evil-goggles hl-todo nav-flash treemacs (popup +all +defaults) vc-gutter vi-tilde-fringe window-select :editor rotate-text :emacs ediff electric hideshow imenu vc :tools magit tmux :lang data emacs-lisp hy javascript ledger markdown (org +attach +babel +capture +export +present) php python (sh +fish) web :app (write +wordnut +langtool) :config)
  packages:  (a clojure-snippets edit-server elquery evil-string-inflection exec-path-from-shell flycheck-joker flycheck-vale lispy lispyville org-brain org-edna request request-deferred restart-emacs visual-fill-column)
  exec-path: (~/bin ~/bin /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /usr/games /usr/local/games /snap/bin /usr/lib/x86_64-linux-gnu/emacs/26.1/x86_64-linux-gnu)
  ```
```
</details>

**Comment by hlissner** [comment]
> Warning (evil-collection): Make sure to set `evil-want-integration' to nil before loading evil or evil-collection.

> evil-collection error: (file-missing Cannot open load file No such file or directory evil-collection-vc-git)

Please update your packages with `make update` (or `bin/doom update`; they both do the same thing).

This is caused by a change upstream, in the `evil-collection` package. Doom has adapted, but the fix will cause breakages if evil-collection isn't updated.

> The ‘:eval’ setting is deprecated, use ‘set-eval-handler!’ instead

I'm guessing there is a `(set! :eval ...)` somewhere in your private config. As the warning says, change it to `(set-eval-handler! ...)` instead, as the old method is deprecated.

**Comment by mjmeintjes** [comment]
Thanks for that! I was running `make install` but forgot about `make update`. That fixes a lot of things that I was having problems with.
