### ISSUE TITLE
How to load evil afte eamcs -Q

### ISSUE THREAD

**Issue by FirstLoveLife** [hlissner/doom-emacs#934]
Sometimes I want load evil with `evil-Q` like `load-file .../evil-core.el`, but I get this error:
> eval-buffer: Cannot open load file: No such file or directory, evil-common

**Comment by hlissner** [comment]
Can you get into Doom? Doom provides the `doom/open-vanilla-sandbox` command, which lets you open a blank Emacs session with some code that has access to your packages. This command is bound to `SPC h E`. It will open a buffer for the code you want to run there.

```lisp
(require 'evil)
;; do your testing
```

Then press C-c C-c to execute the vanilla session, or C-c C-d to execute the vanilla _Doom_ session (no private config is loaded).

**Comment by FirstLoveLife** [comment]
Thanks!
