### ISSUE TITLE
company-lsp + cquery does not worked well

### ISSUE THREAD

**Issue by verminniu** [hlissner/doom-emacs#935]
doom-emacs is the best for me, thanks, but there is a little problem for cquery and company-lsp

### Observed behavior

the company-lsp does not work well and the function and args.
for example:
there is a function:    
int a(int arg1, int arg2)
the company-lsp get 
int a(

### Expected behavior

I try to close smartparen, add yasnippet, but not worked well, at last i disable company at init.el, and add in my private config, it work's ok

it's seems company-backends cause this.

when used company at init.el the company-backends only has ( company-lsp  company-yasnippet company-capf)

### System information

doom-emacs ( develop )
Mac os

**Comment by hlissner** [comment]
Doom doesn't have LSP built into it yet, so I'm afraid I can't offer much insight into the matter, but you can use a specific backend for c++-mode with:

```elisp
(set-company-backend! 'c++-mode 'company-lsp)
```

**Comment by MaskRay** [comment]
Sorry I misread the comment

**Comment by MaskRay** [comment]
It is likely configuration issue that is not related to doom-emacs.

```elisp
  (set-company-backend! '(c-mode c++-mode objc-mode) 'company-lsp)
```

Can you inspect the output of `(lsp--client-capabilities)` in your buffer and check if it contains `:completion (:completionItem (:snippetSupport t)))`?

You may use strace/sysdig to dump `textDocument/completion` responses of the language server.

**Comment by verminniu** [comment]
I add company-lsp to the company backends like this

 (set-company-backend! '(c-mode c++-mode objc-mode) 'company-lsp)

the function company work well，only the args not work，and then i disable

 company in doom! :completion 

and  add this in my own config file, it's worked well

;; company
(use-package company
 :init
 (global-company-mode 1)
 )

between two of this the backends are not same,  in the init.el the backends only has (company-lsp, company-capf, company-yasnippet), but in my own config file, there ary many backends in the company-backends,  i will try later to found which cause this

**Comment by verminniu** [comment]
> It is likely configuration issue that is not related to doom-emacs.
> 
> ```emacs-lisp
>   (set-company-backend! '(c-mode c++-mode objc-mode) 'company-lsp)
> ```
> 
> Can you inspect the output of `(lsp--client-capabilities)` in your buffer and check if it contains `:completion (:completionItem (:snippetSupport t)))`?
> 
> You may use strace/sysdig to dump `textDocument/completion` responses of the language server.

I found your ccls's conf and try it，but still not works，only company function is ok，but the arg's not works，and i found your answer in emacschina to disable smartparen also not resolved

**Comment by MaskRay** [comment]
Forgot to mention I have also disabled company-prescient. It provides client-side filtering and sorting which does not play well with LSP if the language server also provides sorting (as ccls, cquery, clangd do).

```elisp 
;; ~/.config/doom/packages.el
(disable-packages! company-prescient)
```

> and i found your answer in emacschina to disable smartparen also not resolved

I think I've encountered a conflict between smartparens and company-lsp before, I disable it as I am not accustomed to its autoinsert/autoskip behavior.

```elisp
  (setq sp-autoinsert-pair nil
        sp-autodelete-pair nil
        sp-escape-quotes-after-insert nil)
  (setq-default sp-autoskip-closing-pair nil)
```

**Comment by ristomet** [comment]
Any updates on this?

**Comment by verminniu** [comment]
> Did you find any solution? Also seems to happen with Spacemacs.

disable company at init.el and add company in your private config.el, it works well, I didn't use spacemacs, you can try your self

**Comment by hlissner** [comment]
What company-backends do you want enabled? This sounds like it's a matter of enabling the correct backends. If you know which backends you want, just adjust the above:

```elisp
(set-company-backend! '(c-mode c++-mode objc-mode) 'company-lsp)

;; maybe you want company-yasnippet too?
(set-company-backend! '(c-mode c++-mode objc-mode) '(company-lsp company-yasnippet))
```

**Comment by MaskRay** [comment]
I'm pretty sure the completion module is good and does need special tweak.

`(set-company-backend! '(c-mode c++-mode cuda-mode objc-mode) 'company-lsp)`

`company-lsp` being the first entry of `company-backends` suffices.

If you want LSP style snippets (as specified in [the spec](https://microsoft.github.io/language-server-protocol/specification)), require `yasnippet`. If company-lsp detects you have yasnippet installed, it'll expand snippets for completion items.

If you use `xref-find-references` for `textDocument/references`, make sure `xref-find-references` is in `xref-prompt-for-identifier` (alternatively, use `lsp-ui-peek-find-references`)

**Comment by ristomet** [comment]
I'm not sure this is related to that.

![pic](https://user-images.githubusercontent.com/7595856/47783287-f84ce300-dd0a-11e8-86ff-8f6e64844c34.png)

Ends up with,

reader->parse(

rather than,

reader.parse(const char* beginDoc, const char *endDoc, Value *root, std::string *errs) which it is suggest, though I'm not sure it is even inteded to work like that

**Comment by MaskRay** [comment]
You don't need any initialization options tweak (named `extra-init-params` in lsp-mode, which is a bit weird).

`company-lsp.el` registers `snippetSupport` capability in lsp-mode:

```elisp
(defun company-lsp--client-capabilities ()
  "Return the extra client capabilities supported by company-lsp."
  (when company-lsp-enable-snippet
    '(:textDocument (:completion (:completionItem (:snippetSupport t))))))
```

When a completion item is expanded, if `yas-expand-snippet` is bound, it expands the snippet:

```elisp
;; company-lsp.el
    let ((start-marker (set-marker (make-marker) start)))
      (when additional-text-edits
        (lsp--apply-text-edits additional-text-edits))
      when (and company-lsp-enable-snippet
                 (fboundp 'yas-expand-snippet))
```

I've received many similar issues for my project, the issues were either they hadn't installed company-lsp or they hadn't enabled yasnippet. They were not doom-emacs/spacemacs's fault.

**Comment by verminniu** [comment]
;; maybe you want company-yasnippet too?
(set-company-backend! '(c-mode c++-mode objc-mode) '(company-lsp company-yasnippet))

this works well, add-hook not good thanks a lot
