### ISSUE TITLE
always use system clipboard in evil-mode

### ISSUE THREAD

**Issue by alvintangzc** [hlissner/doom-emacs#938]
### Observed behavior
when I use dd or yy command in evil，it always store result in system clipboard.
Can I turn this feature off by use doom config?  If so, how to turn this off.
Thank you.

### Expected behavior

dd or yy in evil, don't store result in system clipboard.

### Steps to reproduce

1. yy or dd in evil
2. paste outside emacs

### System information
doom-emacs ( develop )
Mac os

**Comment by alvintangzc** [comment]
I find it's because "osx-clipboard" .
So I add this to my confil.el.
```
(when IS-MAC (add-hook 'after-init-hook (lambda () (osx-clipboard-mode -1))))
```
then it close when startup.

**Comment by hlissner** [comment]
A shorter, perhaps more elegant version would be:

```elisp
(remove-hook 'doom-post-init-hook #'osx-clipboard-mode)
```

An `IS-MAC` check won't be necessary, since the above will do nothing if `osx-clipboard-mode` isn't in `doom-post-init-hook`.
