### ISSUE TITLE
Treemacs icons show black background with light themes

### ISSUE THREAD

**Issue by deech** [hlissner/doom-emacs#947]
### Observed behavior

The background of the Treemacs icons should be white.

![image](https://user-images.githubusercontent.com/76703/46755557-fa330180-cc8a-11e8-832a-705b3ac4693e.png)

### System information

<details>
<summary>Click to expand</summary>

```
- OS: gnu/linux (x86_64-pc-linux-gnu)
- Emacs: 26.1 (Aug 29, 2018)
- Doom: 2.0.9 (develop cdf745e72a3e8bf9bef1f0fa4d051b00aab351e3)
- Graphic display: t (daemon: nil)
- System features: XPM JPEG TIFF GIF PNG RSVG SOUND GPM DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS XWIDGETS LIBSYSTEMD LCMS2
- Details:
  ```elisp
  elc count: 0
  uname -a:  Linux deech-pc 4.14.69-1-MANJARO #1 SMP PREEMPT Mon Sep 10 02:18:25 UTC 2018 x86_64 GNU/Linux
  modules:   (:feature (evil +everywhere) file-templates (lookup +docsets) snippets spellcheck (syntax-checker +childframe) workspaces :completion (helm +fuzzy) :ui doom-dashboard doom-modeline doom-quit evil-goggles hl-todo nav-flash treemacs (popup +all +defaults) vc-gutter vi-tilde-fringe window-select :editor rotate-text :emacs ediff electric hideshow imenu vc :tools magit :lang emacs-lisp go haskell markdown (org +attach +babel +capture +export +present) (sh +fish) :config)
  packages:  n/a
  exec-path: (~/Downloads/ATS/ATS2/bin ~/.local/bin ~/JavaScript/qooxdoo-compiler ~/.cargo/bin ~/npm/bin ~/.cabal/bin ~/Haskell/stack-1.0.4.3-linux-x86_64 ~/Downloads/jdk1.8.0_91//bin ~/Scala/sbt/bin ~/Scala/scala-2.11.8/bin ~/Scala/apache-maven-3.3.9/bin ~/Scala/apache-ant-1.10.1/bin ~/.local/bin ~/CCAD/firebird/meta/dev-tools/bin ~/Lisp/lfe/bin /bin . ~/Nim/Nim/bin ~/Nim/Nim/tools ~/.nimble/bin ~/Downloads/PostiATS-Utilities ~/fpc-3.0.2/bin ~/Dlang/dmd/generated/linux/release/64/ ~/Dlang/phobos/generated/linux/release/64/ ~/Dlang/dub/bin ~/Dlang/DCD/bin ~/Dlang/D-Scanner/bin /usr/local/bin /usr/bin /bin /usr/local/sbin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /usr/local/libexec/emacs/26.1/x86_64-pc-linux-gnu)
  ```
```
</details>

**Comment by Alexander-Miller** [comment]
Sounds like https://github.com/Alexander-Miller/treemacs/issues/148. If so updating your treemacs should fix things.

**Comment by deech** [comment]
Just updated via `bin/doom update` and restarted Emacs. Same result.

**Comment by hlissner** [comment]
Is your config up somewhere I can see it? Perhaps it is a load order issue, i.e. you are loading treemacs early in the startup process. 

If you set the `doom-theme` variable, the theme is loaded *after* your private config.el. If you use `load-theme` explicitly, it needs to be done _before_ you invoke treemacs.

**Comment by Alexander-Miller** [comment]
And some some debugging for my end of things:
 * What are the values of `treemacs--not-selected-icon-background` and `treemacs--selected-icon-background`?
 * Do they change if you evaluate `treemacs--setup-icon-background-colors`?
 * Do you see any `[Treemacs]` warnings in the messages buffer when you first load treemacs?
 * What is the output of `(face-attribute 'default :background nil t)`?
 * What is the output of `(face-attribute 'hl-line :background nil t)`?
 * Do the colors still look wrong if you load another theme?

**Comment by DougBeney** [comment]
I am having the same issue as #148 again but this time with a black background color.
Treemacs v2.2.2-2018.11.03 @ 26.1
Ubuntu 18.04.

> What are the values of treemacs--not-selected-icon-background and treemacs--selected-icon-background?

In the case of my theme, `sanityinc-tomorrow-blue` they are two different dark-blue colors - Exactly as they should be.

> Do they change if you evaluate treemacs--setup-icon-background-colors?

Nope.

> Do you see any [Treemacs] warnings in the messages buffer when you first load treemacs?

Nope.

> What is the output of (face-attribute 'default :background nil t)?

Another dark-blue value that is exactly what it is supposed to be.

> What is the output of (face-attribute 'hl-line :background nil t)?

Another dark-blue value that is exactly what it is supposed to be.

> Do the colors still look wrong if you load another theme?

Yep. However, there is still a fix. If you go into `customize-themes`, select a new theme, then go back to your other theme it will be fixed until you quit and re-open Emacs.

**Comment by Alexander-Miller** [comment]
Try again with the newest treemacs. It should be fixed as of https://github.com/Alexander-Miller/treemacs/commit/b91bae8744bbb7cc2f87161ef875bcb1aa8bbfbf.

**Comment by hlissner** [comment]
@deech Are you still experiencing this issue?

**Comment by deech** [comment]
This is no longer happening. Sorry I didn't close earlier.
