### ISSUE TITLE
Feature Request: Multiple Cursors and TextPastry type editing

### ISSUE THREAD

**Issue by raguay** [hlissner/doom-emacs#951]
I love doom-emacs. I was using Spacemacs, but it loads and runs so slowly. This configuration is much better. But, I'm really missing two things that I use a lot in Sublime Text that I really want here in Emacs:

1) Multiple cursors: I tried loading a elisp package I found for it on Spacemacs, but it really didn't work well. It also didn't allow selecting multiple locations with a regular expression. Do you know how to get it done in doom?

2) Sublime has a package called TextPastry. It allows you to take multiple cursor locations and insert a 0 or 1 based count. That way, I have a cursor on multiple lines and can number them with one command. Do you know of a similar package that would work with Doom?

Thanks. You really have a great product here!

**Comment by hlissner** [comment]
Doom has the `:editor multiple-cursors` module, which provides:

+ For evil users:
  + [evil-mc](https://github.com/gabesoft/evil-mc/tree/master) (multiple-cursors for evil-mode)
  + [evil-multiedit](https://github.com/hlissner/evil-multiedit) (similar to evil-iedit-mode, which I believe Spacemacs uses)
+ For non-evil users
  + [multiple-cursors](https://github.com/magnars/multiple-cursors.el)

The typical use case for evil-mc is to create cursors with `gzz` or `:mc REGEXP` (all evil-mc keys in Doom are bound to the `gz` prefix). Cursors are "activated" when you switch to insert mode, or upon pressing `gzt` (toggle).

Evil-multiedit can be used by a) pressing <kbd>M-d</kbd> or <kbd>M-D</kbd>, to highlight the symbol at point (or selection), b) selecting a word and pressing <kbd>R</kbd> to highlight all matches, or c) with `:iedit REGEXP` to highlight matches.

---

> TextPastry

Unfortunately, there is no such package in Doom, and none that I know of with this functionality.

**Comment by raguay** [comment]
Okay. Thanks. I've been out of town the last several days, so my reply is delayed. I'll see if I can create the functionality myself. It's been quite a while since I've done much elisp (over 20 years now).

**Comment by jmorag** [comment]
There are some functions for that in the [multiple cursors](https://github.com/magnars/multiple-cursors.el#special) package.

**Comment by raguay** [comment]
Thanks everyone. I'm working through the multiple cursors package trying to learn how to use it. Thanks for pointing me in the right direction.
