### ISSUE TITLE
OSX - CMD+H do not show emacs window in GUI mode

### ISSUE THREAD

**Issue by idoo** [hlissner/doom-emacs#952]
is it possible to make emacs hidden by pressing CMD+H ?

**Comment by hlissner** [comment]
Try:

```elisp
(setq mac-command-modifier 'super)
```

**Comment by hlissner** [comment]
I'll assume this resolved the matter. Not to mention super+h is no longer being used by Doom, so it should work again as normal. Let me know if that isn't the case.
