### ISSUE TITLE
Parentheses (and other brackets) highlighted in background colour

### ISSUE THREAD

**Issue by beojan** [hlissner/doom-emacs#953]
Brackets are highlighted in the background colour, making them invisible:

Unhighlighted:
![image](https://user-images.githubusercontent.com/3727925/46866461-c211f700-ce21-11e8-9559-4aa961e5c7b2.png)

Highlighted:
![image](https://user-images.githubusercontent.com/3727925/46866482-deae2f00-ce21-11e8-9167-d2e500f55037.png)

**Comment by hlissner** [comment]
What theme are you using? Doom-one or Doom-vibrant?

Is Doom up to date?

Are your packages (particularly doom-themes) up to date?

**Comment by beojan** [comment]
I'm using Doom-one. All packages are up to date, as is Doom.

**Comment by hlissner** [comment]
Are you running GUI or terminal emacs?

Can you post your `M-x doom/info`?

**Comment by beojan** [comment]
GUI.

```
- OS: gnu/linux (x86_64-pc-linux-gnu)
- Emacs: 26.1 (Jul 05, 2018)
- Doom: 2.0.9 (develop 5076ed592c3b3c3a51708fc46a70d28f9dee4e00)
- Graphic display: t (daemon: nil)
- System features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LIBSYSTEMD LCMS2
- Details:
  ```elisp
  elc count: 0
  uname -a:  Linux quee2769 4.18.12-1-ck #1 SMP PREEMPT Sat Oct 6 19:52:20 CEST 2018 x86_64 GNU/Linux
  modules:   (:feature (evil +everywhere) file-templates (lookup +devdocs +docsets) snippets spellcheck (syntax-checker +childframe) workspaces :completion (helm +fuzzy) :ui doom-dashboard doom-quit evil-goggles hl-todo modeline nav-flash treemacs (popup +all +defaults) vc-gutter vi-tilde-fringe window-select :editor multiple-cursors rotate-text :emacs ediff electric hideshow imenu vc :tools make magit rgb :lang (cc +irony +rtags) common-lisp data emacs-lisp (haskell +intero) latex lua markdown (org +attach +babel +capture +export +present) perl python qt sh :config)
  packages:  n/a
  exec-path: (~/.local/bin ~/bin /usr/local/sbin /usr/local/bin /usr/bin /usr/share/backuppc/bin /opt/cuda/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /usr/lib/emacs/26.1/x86_64-pc-linux-gnu)
  ```

**Comment by hlissner** [comment]
Hmm, I see nothing problematic and cannot seem to reproduce this issue. Could you offer more specific steps to reproduce your issue?

**Comment by beojan** [comment]
It started after I downgraded from Emacs 26.1.50 (from git) to the 26.1 release, which required a doom refresh.

**Comment by beojan** [comment]
I tried reinstalling doom and still see the bug.

**Comment by UndeadKernel** [comment]
Could you place your cursor on a wrongly color parenthesis and do `M-x doom/what-face`? Please post back its output.

**Comment by beojan** [comment]
`rainbow-delimiters-depth-2-face`.

Shouldn't it be one of the `paren-mode` face when highlighted?

**Comment by UndeadKernel** [comment]
Join us in DOOM's discord channel and we might be able to debug your issue faster: https://discord.gg/bcZ6P3y
