### ISSUE TITLE
Cannot search a directory or project with `SPC / d` or `SPC / p`

### ISSUE THREAD

**Issue by deech** [hlissner/doom-emacs#954]
Whenever I try to search under a directory or project wide using 'SPC / {d,p}` I get:
```
helm-make-source: Symbol’s value as variable is void: helm-projectile-grep-or-ack-actions
```
in the Message buffer.

### System information

<details>
<summary>Click to expand</summary>
- OS: gnu/linux (x86_64-pc-linux-gnu)
- Emacs: 27.0.50 (Sep 05, 2018)
- Doom: 2.0.9 (develop cdf745e72a3e8bf9bef1f0fa4d051b00aab351e3)
- Graphic display: t (daemon: nil)
- System features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD JSON LCMS2 GMP
- Details:
  ```elisp
  elc count: 0
  uname -a:  Linux deech-pc 4.14.67-1-MANJARO #1 SMP PREEMPT Fri Aug 24 16:33:26 UTC 2018 x86_64 GNU/Linux
  modules:   (:feature (evil +everywhere) file-templates (lookup +docsets) snippets spellcheck (syntax-checker +childframe) workspaces :completion (helm +fuzzy) :ui doom-dashboard doom-modeline doom-quit evil-goggles hl-todo nav-flash treemacs (popup +all +defaults) vc-gutter vi-tilde-fringe window-select :editor rotate-text :emacs ediff electric hideshow imenu vc :tools magit :lang emacs-lisp go markdown nim (org +attach +babel +capture +export +present) (sh +fish) :config)
  packages:  n/a
  exec-path: (/usr/local/bin /usr/bin /bin /usr/local/sbin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /usr/local/libexec/emacs/27.0.50/x86_64-pc-linux-gnu)
  ```
</details>

**Comment by deech** [comment]
Yes, that fixes it!

**Comment by hlissner** [comment]
11793be should fix this issue. Let me know if that isn't the case.

You can also get around the issue by installing `ripgrep` (rg) or `the_silver_searcher` (ag), which project/directory search will use, instead of grep/git-grep, if they are available (they are also much faster).
