### ISSUE TITLE
The latex module doesn't recognized the +latexmk and +pdf-tools options

### ISSUE THREAD

**Issue by maikol-solis** [hlissner/doom-emacs#955]
### Observed behavior

Using doom-emacs in latex-mode and trying to compile with latexmk  the .tex with `C-c C-a` and view the pdf with `pdf-tools`. In neither case those options worked.  

In the private init.el I have `(latex +latexmk +pdf-tools)`. 

I followed all the steps in the documentation and I don't know if there is something wrong. 
### Expected behavior

Press `C-c C-a` and the compiled pdf shows in another buffer with pdf-tools

### Steps to reproduce

1. Open a latex file. 
2. Try to compile it with `C-c C-a`

### System information

<details>
<summary>Click to expand</summary>

```
- OS: gnu/linux (x86_64-suse-linux-gnu)
- Emacs: 26.1 (Oct 12, 2018)
- Doom: 2.0.9 (develop cdf745e72a3e8bf9bef1f0fa4d051b00aab351e3)
- Graphic display: t (daemon: nil)
- System features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS XWIDGETS LIBSYSTEMD
- Details:
  ```elisp
  elc count: 0
  uname -a:  Linux linux-yl24 4.18.12-2.ga880bd8-default #1 SMP PREEMPT Thu Oct 4 06:37:48 UTC 2018 (a880bd8) x86_64 x86_64 x86_64 GNU/Linux
  modules:   (:feature (evil +everywhere) file-templates (lookup +docsets) snippets spellcheck (syntax-checker +childframe) workspaces :completion (helm +fuzzy) :ui doom-dashboard doom-modeline doom-quit evil-goggles hl-todo nav-flash treemacs (popup +all +defaults) vc-gutter vi-tilde-fringe window-select :editor rotate-text :emacs ediff electric hideshow imenu vc :tools magit pdf :lang (latex +latexmk +pdf-tools) markdown (org +attach +babel +capture +export +present) (sh +fish) :app :config)
  packages:  n/a
  exec-path: (~/bin /usr/local/bin /usr/bin /bin /usr/lib/mit/sbin /usr/lib/emacs/26.1/x86_64-suse-linux)
  ```

```
</details>

**Comment by hlissner** [comment]
Could you expand how these options failed to work? Was there an error? A message? Did it simply do nothing?

---

> +pdf-tools

I'm afraid the documentation for lang/latex (in fact, much of Doom) is sorely outdated (something I am currently working on). The `+pdf-tools` flag no longer exists. Instead, there is a `+latex-viewers` variable which defines all the available viewers:

```elisp
(defconst +latex-viewers `(skim zathura okular pdf-tools)
  "A list of enabled latex viewers to use, in this order. If they don't exist,
they will be ignored. Recognized viewers are skim, zathura, okular and
pdf-tools.

If no viewers are found, `latex-preview-pane' is used.")
```

If you want to only use pdf-tools, you can set this:

```elisp
(setq +latex-viewers '(pdf-tools))
```

_And_ you must have the `:tools pdf` module enabled.

But this should only be necessary if you have more than one of these viewers installed on your system.

**Comment by maikol-solis** [comment]
Thanks @hlissner for your answer. 

First, I haven't any error in the `Message` buffer,  but the mentioned features don't work at all.  If I want to compile the document I have to make `C-c C-b` a couple of times and then  `C-c C-a`. At this point latexmk works. 

The thing that I don't know how to make it work is show the pdf with pdf-tools. 

This is the output of `SPC-h-m`, 

```
Doom loaded 180 packages across 40 modules in 1.385s
Loading /home/maikol/.emacs.d/.local/cache/recentf...done
No docstring slot for grep-compute-defaults [3 times]
File mode specification error: (file-missing Cannot open load file No such file or directory emacs-snippets)
Loading /home/maikol/.emacs.d/.local/packages/elpa/auctex-12.1.1/style/inputenc.elc...done
Loading /home/maikol/.emacs.d/.local/packages/elpa/auctex-12.1.1/style/textcomp.elc...done
Loading /home/maikol/.emacs.d/.local/packages/elpa/auctex-12.1.1/style/babel.elc...done
Loading /home/maikol/.emacs.d/.local/packages/elpa/auctex-12.1.1/style/color.elc...done
Loading /home/maikol/.emacs.d/.local/packages/elpa/auctex-12.1.1/style/amsmath.elc...done
Loading /home/maikol/.emacs.d/.local/packages/elpa/auctex-12.1.1/style/amstext.elc...done
Loading /home/maikol/.emacs.d/.local/packages/elpa/auctex-12.1.1/style/amsbsy.elc...done
Loading /home/maikol/.emacs.d/.local/packages/elpa/auctex-12.1.1/style/amsopn.elc...done
Loading /home/maikol/.emacs.d/.local/packages/elpa/auctex-12.1.1/style/amssymb.elc...done
Loading /home/maikol/.emacs.d/.local/packages/elpa/auctex-12.1.1/style/amsfonts.elc...done
Loading /home/maikol/.emacs.d/.local/packages/elpa/auctex-12.1.1/style/natbib.elc...done
Loading /home/maikol/.emacs.d/.local/packages/elpa/auctex-12.1.1/style/graphics.elc...done
Loading /home/maikol/.emacs.d/.local/packages/elpa/auctex-12.1.1/style/graphicx.elc...done
Loading /home/maikol/.emacs.d/.local/packages/elpa/auctex-12.1.1/style/bm.elc...done
Loading /home/maikol/.emacs.d/.local/packages/elpa/auctex-12.1.1/style/booktabs.elc...done
Applying style hooks...done
```

Now, where exactly do I have to put `(setq +latex-viewers '(pdf-tools))` ?

Best

**Comment by hlissner** [comment]
I'm not familiar enough with auctex to know what `C-c C-b` or `C-c C-a` do. However, you should place  that snippet in `~/.doom.d/config.el`.

**Comment by siddharthshekar** [comment]
For what it's worth, I only have `latex` set in my init.el and have the following snippet in my config.org:
```
#+BEGIN_SRC emacs-lisp
  (after! latex
    (add-to-list 'TeX-command-list '("LatexMk" "latexmk -pdflatex='pdflatex -file-line-error -synctex=1' -pdf %t" TeX-run-TeX nil)))
#+END_SRC
```
I never had to do anything to use `pdf-tools` beyond enabling the `pdf`module. The keybinding for this should be `C-c C-v` although I've personally remapped this to `SPC m v`, which opens up the PDF file in `pdf-tools`.

**Comment by hlissner** [comment]
I see. `lang/latex` has a `+latexmk` flag, btw, which adds a `TeX-command-list` entry much like the one you have. Has that not worked for you?

**Comment by siddharthshekar** [comment]
I was operating under the assumption that only file names `+XYZ.el` in a module directory were available as relevant flags for a given module. I should have looked deeper haha!

**Comment by hlissner** [comment]
@maikol-solis sorry for the late reply, but are you still experiencing this issue?

**Comment by hlissner** [comment]
I will assume this issue has been resolved. Feel free to follow up here if that isn't the case.
