### ISSUE TITLE
treemacs directory icon broken

### ISSUE THREAD

**Issue by iamburning** [hlissner/doom-emacs#956]
brand new doom-emacs on develop branch
setting doom-font via 
` doom-font (font-spec :family "Sarasa Mono SC" :weight 'bold :size 14)
`
move cursor in treemacs.  the icon will be broken.  normal weight font was ok
![screenshot from 2018-10-13 19-50-51](https://user-images.githubusercontent.com/17723587/46916169-86298e00-cfe9-11e8-8037-0ac201b59e02.png)

GNU Emacs 26.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30)

**Comment by hlissner** [comment]
I'm not sure this is necessarily a Doom or `doom-themes` issue. Do the artifacts go away when you do `M-x redraw-display`?

**Comment by iamburning** [comment]
actually no need to run "redraw-display" command . when pushed M-x these white blank were gong.

**Comment by hlissner** [comment]
Sorry for the late response: are you still experiencing this issue?

**Comment by iamburning** [comment]
yeap

**Comment by hlissner** [comment]
Can you reproduce this with other fonts?

**Comment by iamburning** [comment]
I have tried "DeJaVe sans, Droid sans"  on Manjaro width gnome-desktop and cinnamon environment.
it  caused this issue. 
it sames no matter what font that I used with ":weight 'bold " attribute cause this issue.
same configuration on Mac OS this issue wouldn't happen

**Comment by hlissner** [comment]
Can you reproduce this effect in vanilla Emacs? i.e. `M-x doom/open-vanilla-sandbox` with

```elisp
(set-frame-font (font-spec :family "Sarasa Mono SC" :weight 'bold :size 14))
(require 'treemacs)
```

Then press `C-c C-c` to start a vanilla session with that code.

**Comment by iamburning** [comment]
icon was diffrent, but no broken.
![screenshot from 2019-03-02 11-59-23](https://user-images.githubusercontent.com/17723587/53676871-27885680-3ce3-11e9-9893-2aacfaac4dc4.png)

**Comment by hlissner** [comment]
Ah, sorry, allow me to modify that snippet:

```elisp
(set-frame-font (font-spec :family "Sarasa Mono SC" :weight 'bold :size 14))
(require 'treemacs)
(require 'doom-themes)
(require 'all-the-icons)
(doom-themes-treemacs-config)
(setq doom-treemacs-enable-variable-pitch t)
```

This should mimic the original set better. Try that and let me know.

**Comment by iamburning** [comment]
no broken icon
![screenshot from 2019-03-02 13-00-08](https://user-images.githubusercontent.com/17723587/53677470-3ffc6f00-3ceb-11e9-9ed3-058ee6dda413.png)

**Comment by iamburning** [comment]
move cursor up and down, icon broken. but less than before
![screenshot from 2019-03-02 13-07-05](https://user-images.githubusercontent.com/17723587/53677523-463f1b00-3cec-11e9-866b-8b688eff4138.png)

**Comment by iamburning** [comment]
finally i found the solution. it's about the font rendering. ( using octicon.ttf )
default setting is "rgb". change to "rgba" there is no broken icon at all
![2019-03-03_23-54](https://user-images.githubusercontent.com/17723587/53698170-f65b7380-3e13-11e9-97a3-701b67309d7c.png)

**Comment by hlissner** [comment]
Ah! That explains it. In that case I'll consider this resolved. Thanks for looking into this. I'll mention it in the new FAQ I'm working on.
