### ISSUE TITLE
undo-tree: cannot show diff window

### ISSUE THREAD

**Issue by UndeadKernel** [hlissner/doom-emacs#960]
### Observed behavior

When the undo-tree popup is being shown, the shortcut `d` should be able to display the diff at the selected undo level. This is due to the popup window being a 'side window' which cannot be split.

### Expected behavior

When the undo-tree popup is open and the user presses `d`, the side window should be split such that the diff of the undo level is shown at the bottom.

### Steps to reproduce

1. In a buffer that has some edits, open undo-tree with `undo-tree-visualize`.
2. Press `d`

**Comment by hlissner** [comment]
This appears to have been resolved recently, with the new popup settings for undo-tree, so I'll consider this resolved. Let me know if that isn't the case.
