### ISSUE TITLE
How to test my fix for `doom-emacs`?

### ISSUE THREAD

**Issue by laishulu** [hlissner/doom-emacs#969]
I want to submit pull request, but surely I should test in my own emacs.
So I do the following:
```
diff --git a/modules/config/default/+bindings.el b/modules/config/default/+bindings.el
index 7cbfee74..2abacf6d 100644
--- a/modules/config/default/+bindings.el
+++ b/modules/config/default/+bindings.el
@@ -103,6 +103,8 @@
       :n  "g@" #'+evil:apply-macro
       ;; repeat in visual mode (FIXME buggy)
       :v  "."  #'evil-repeat
+      ;; line mode in visual mode
+      :v  "V"  #'evil-visual-line
       ;; don't leave visual mode after shifting
       :v  "<"  #'+evil/visual-dedent  ; vnoremap < <gv
       :v  ">"  #'+evil/visual-indent  ; vnoremap > >gv
```
Then I reopen emacs, but my new codes does not take effect.
I run make/make compile/make clean etc, still don't work.

**Comment by hlissner** [comment]
I don't understand why that doesn't work for you. It does for me. But I suspect the problem exists elsewhere in your code.

Can you pastebin or link the whole file? Or make the PR anyway? I won't be able to tell without seeing more of it.

**Comment by laishulu** [comment]
Got it. because "V" is mapped later in https://github.com/hlissner/doom-emacs/blob/develop/modules/config/default/%2Bbindings.el#L296.
