### ISSUE TITLE
mu4e message view hook disables wrapping

### ISSUE THREAD

**Issue by brabalan** [hlissner/doom-emacs#970]
This hook https://github.com/hlissner/doom-emacs/blob/develop/modules/app/email/config.el#L98 disables the wrapping of lines in `mu4e-view-mode`. In addition, there does not seem a way to disable it. If I add
``` emacs-lisp
(after! mu4e
  (setq mu4e-view-mode-hook nil)
  (add-hook! mu4e-view-mode 'turn-on-visual-line-mode)
```
to restore the default behavior, it does not work.

**Comment by hlissner** [comment]
```elisp
(setq-hook! 'mu4e-view-mode-hook truncate-lines t)
```

However, if you enable visual-line-mode, it sets truncate-lines to nil. So it's up to you to pick the above or this:

```elisp
(add-hook 'mu4e-view-mode-hook #'visual-line-mode)
```

**Comment by hlissner** [comment]
>for text messages
>when html is displayed

These don't help narrow it down much. I'd need to know the major modes of those buffers, then you'd know what hook to target.

Looking at its source code, `mu4e-headers-mode` and `mu4e-main-mode` are the only modes that set `truncate-lines` to `t`, and no where else. In fact, now that I'm looking into it, setting `truncate-lines` appears to be unnecessary for mu4e-view-mode.

Try this instead:

```elisp
(setq-hook! '(mu4e-headers-mode mu4e-main-mode) truncate-lines nil)
```

**Comment by brabalan** [comment]
In both cases the buffer is in `mu4e-view-mode`. When `truncate-lines` is t in a buffer, it is because it is taken from the global value. This means that the hook has not run. I guess this is because of this code from `mu4e-view.el` (I'm pasting from my installed version, which is the latest stable release of mu. The current code has changed and seems to always run the hook)
``` emacs-lisp
(defun mu4e-view (msg)
  "Display the message MSG in a new buffer, and keep in sync with HDRSBUF.
'In sync' here means that moving to the next/previous message in
the the message view affects HDRSBUF, as does marking etc.

As a side-effect, a message that is being viewed loses its 'unread'
marking if it still had that."
  (let* ((embedded ;; is it as an embedded msg (ie. message/rfc822 att)?
	   (when (gethash (mu4e-message-field msg :path)
		   mu4e~path-parent-docid-map) t))
	  (buf
	    (if embedded
	      (mu4e~view-embedded-winbuf)
	      (get-buffer-create mu4e~view-buffer-name)))
         mode-enabled)
    (with-current-buffer buf
      (unless (setq mode-enabled (eq major-mode 'mu4e-view-mode))
        (let (mu4e-view-mode-hook) (mu4e-view-mode)))
      (setq mu4e~view-msg msg)
      ;; When MSG is unread, mu4e~view-mark-as-read-maybe will trigger
      ;; another call to mu4e-view (via mu4e~headers-update-handler as
      ;; the reply handler to mu4e~proc-move)
      (let ((inhibit-read-only t))
        (when (or embedded (not (mu4e~view-mark-as-read-maybe msg)))
	  (erase-buffer)
	  (mu4e~delete-all-overlays)
	  (insert (mu4e-view-message-text msg))
	  (goto-char (point-min))
	  (mu4e~fontify-cited)
	  (mu4e~fontify-signature)
	  (mu4e~view-make-urls-clickable)
	  (mu4e~view-show-images-maybe msg)
	  (when embedded (local-set-key "q" 'kill-buffer-and-window))
          (unless mode-enabled (run-mode-hooks 'mu4e-view-mode-hook)))))
    (switch-to-buffer buf)))
```
I'll close this issue because now I'm convinced it's a mu issue, not a doom issue. Sorry for the noise.
