### ISSUE TITLE
Python re enabling flycheck checkers after activating conda environment

### ISSUE THREAD

**Issue by vikigenius** [hlissner/doom-emacs#972]
### Observed behavior

Right now I am using `conda-env-activate` to activate a python environment. I have flake8 installed in this environment. But flycheck reports flake8 as disabled. Most likely because before activating the environment, flake8 was not installed and thus no executable. 

### Expected behavior
Re-enable disabled checkers after activating an environment so that flycheck can select the best available checker in the new environment

### Steps to reproduce

1. Install flake8 in a particular environment
2. Open python file
3. Activate environment having flake8
4. Check if flake8 is enabled post activation

### System information

<details>
<summary>Click to expand</summary>

```
Replace this line with the output of *one* of these commands:

+ `- OS: gnu/linux (x86_64-unknown-linux-gnu)
- Emacs: 26.1 (Jul 25, 2018)
- Doom: 2.0.9 (develop d8dbd0759cad2b1c52bf6dc3019a55cb2850408e)
- Graphic display: t (daemon: nil)
- System features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS XWIDGETS LCMS2
- Details:
  ```elisp
  elc count: 0
  uname -a:  Linux voidlab 4.18.14_1 #1 SMP PREEMPT Sun Oct 14 01:09:30 UTC 2018 x86_64 GNU/Linux
  modules:   (:feature (evil +everywhere) file-templates (lookup +docsets) snippets spellcheck (syntax-checker +childframe) workspaces :completion (helm +fuzzy) :ui doom-dashboard doom-modeline doom-quit evil-goggles hl-todo nav-flash treemacs (popup +all +defaults) vc-gutter vi-tilde-fringe window-select :editor rotate-text :emacs ediff electric hideshow imenu vc :tools :lang emacs-lisp markdown (org +attach +babel +capture +export +present) (python +conda) (sh +fish) :config)
  packages:  n/a
  exec-path: (~/.miniconda/envs/NLP/bin/ ~/.zplug/bin ~/.symlinks /usr/local/sbin /usr/local/bin /usr/bin /usr/sbin /sbin /bin /usr/libexec/emacs/26.1/x86_64-unknown-linux-gnu)
  ```
```
</details>

**Comment by vikigenius** [comment]
Right now as a workaround I have installed flake8 in my system python too. Which means flycheck won't disable flake8 anymore.

**Comment by hlissner** [comment]
Does flycheck see the new flake8 binary if you reopen the file after changing your conda environment?

**Comment by vikigenius** [comment]
Yes, even in the old buffer it updates the path to correct path. But just that it has disabled it. I am not sure how flake8 is doing this but it seems the disabled list is common across buffers, so once a checker has been disabled we can only manually enable it I think using an interactive command.

**Comment by vikigenius** [comment]
After investigating further it seems that reverting the file does make flake8 use the executable from the environment so maybe a possible solution could just be to reload the buffers upon activating an environment.
