### ISSUE TITLE
`goto-char` does not work in line visual state (`V`)

### ISSUE THREAD

**Issue by brabalan** [hlissner/doom-emacs#975]
### Observed behavior

Enter line visual state (`V`), then evaluate `goto-char (point-max)`. The point does not move.

### Expected behavior

The point is at the end of the file with everything selected from where it was to the end.

### Additional notes

It works in normal visual state (`v`), but not in line visual state.

**Comment by brabalan** [comment]
I don't know. I was trying to figure out why `mu4e-compose-goto-bottom` does not work in line visual mode, and I tracked it down to this.

**Comment by hlissner** [comment]
This appears to be the intended behavior of evil's visual-line mode. Even in vanilla Emacs+evil it behaves this way, unless you use `M-x goto-char`, rather than `M-x eval-expression RET (goto-char (point-max))`. Perhaps it should be reported to the evil guys?

**Comment by brabalan** [comment]
Thank you for the investigation, I'll open an issue with the evil people.

**Comment by brabalan** [comment]
To solve it I can add
``` emacs-lisp
(evil-set-command-property 'mu4e-compose-goto-bottom :keep-visual t)
(evil-set-command-property 'mu4e-compose-goto-top :keep-visual t)
```

This could be a useful addition to the mu module.

**Comment by hlissner** [comment]
Thanks for looking into this for me. I've pushed it in ab79799, so I'll consider this resolved. 

Perhaps the evil-collection guys should be informed. This might be a better fit for their evil-collection-mu4e package.

**Comment by brabalan** [comment]
I opened an issue on the evil-collection page, I'll let you know when/if they integrate it.

**Comment by brabalan** [comment]
And they've just done it.

**Comment by hlissner** [comment]
Great. I've reverted the changes in app/email in 1f3c41a8 (though I marked the wrong issue, whoops!).

Thanks for letting me know!
