### ISSUE TITLE
Bindings for intero-mode are not loaded

### ISSUE THREAD

**Issue by wedens** [hlissner/doom-emacs#979]
### Observed behavior

When I open haskell source with `(haskell +intero)` in my config, there are no intero related bindings under SPC-m. If I manually disable and enable intero-mode, they appear.

### Expected behavior

Bindings are loaded when I open a file.

### Steps to reproduce

1. Add `(haskell +intero)` to modules
2. Open .hs file
3. Press SPC-m. No intero-* bindings.

### System information

<details>
<summary>Click to expand</summary>

```
Doom Doctor
Emacs v26.1
Doom v2.0.9 (9599ca3c)
shell: /bin/zsh
Compiled with:
  XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL
  GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11
  MODULES THREADS LIBSYSTEMD LCMS2
uname -a:
  Linux wedens 4.18.12-arch1-1-ARCH #1 SMP PREEMPT Thu Oct 4 01:01:27 UTC 2018
  x86_64 GNU/Linux

Checking your OS...
Checking your fonts...
Checking gnutls/openssl...
Testing your root certificates...
Checking for GNU/BSD tar...
Checking your enabled modules...
Loading /home/wedens/.emacs.d/core/autoload/cache.el (source)...


Everything seems fine, happy Emacs’ing!
```
</details>

**Comment by wedens** [comment]
Temporary workaround: `(add-hook 'intero-mode-hook #'evil-normalize-keymaps)`

**Comment by hlissner** [comment]
This is an known (and potentially unsolvable) implementation detail with evil. Evil performs some bookkeeping on all active evil keybinds (keybinds in an evil state on a keymap), and only does this a) when switching major modes or b) when you switch between evil states (e.g. normal -> insert).

Unfortunately, this means this bookkeeping occurs _before_ minor modes (like intero-mode) are activated, so evil keybinds in minor mode keymaps (like intero-mode-map) are inaccessible until you change evil states _or_ until `evil-normalize-keymaps` is called (which performs this bookkeeping).

To fix this, we can either a) force evil to normalize its keymaps when intero-mode is activated:

```elisp
(add-hook 'intero-mode-hook #'evil-normalize-keymaps)
```

or b) move evil keybinds to the major mode's keymap `haskell-mode-map`. 

I'll implement one of these two fixes in lang/haskell soon. I'll leave this issue open until I have.

**Comment by PoiScript** [comment]
I just found out that @hlissner had rewritten the `map!` macro and it's now using `general` under the hook. Sine `general` have already provided the wrapping [`evil-define-minor-mode-key`](https://github.com/noctuid/general.el#wrapping-evil-define-minor-mode-key). Can we just use that implantation for defining keybindings for minor mode directly?

**Comment by hlissner** [comment]
Since the fix was merged into lang/haskell some time ago, I'll consider this issue resolved.

> Can we just use that implantation for defining keybindings for minor mode directly?

We can, but I'd rather we just use `map!` and add the hook, as that requires a good deal less code. Localleader keybinds are complicated creatures under the hood.
