### ISSUE TITLE
helm-man-women called error when disable evil

### ISSUE THREAD

**Issue by verminniu** [hlissner/doom-emacs#980]
### Observed behavior

I remove :feature evil from init.el, then the M-x helm-man-women ,then got " **Symbol's function definition is void: evil-define-key*** "

I can't understand how it caused, when I add evil back, is ok

### System information

Mac os, doom-develop

**Comment by hlissner** [comment]
Sorry for taking so long to look into this. I'm having trouble finding the errant evil-define-key* call. Could you provide a backtrace for this error? e.g. `M-x toggle-debug-on-error`, then recreate the error.

**Comment by verminniu** [comment]
Debugger entered--Lisp error: (void-function evil-define-key*)
   (evil-define-key* 'normal Man-mode-map "q" (function kill-this-buffer))
   (closure (t) nil (evil-define-key* 'normal Man-mode-map "q" (function kill-this-buffer)))()
   eval-after-load-helper("/usr/local/Cellar/emacs-mac/emacs-26.1-z-mac-7.2/share/emacs/26.1/lisp/man.elc")
   run-hook-with-args(eval-after-load-helper "/usr/local/Cellar/emacs-mac/emacs-26.1-z-mac-7.2/share/emacs/26.1/lisp/man.elc")
   do-after-load-evaluation("/usr/local/Cellar/emacs-mac/emacs-26.1-z-mac-7.2/share/emacs/26.1/lisp/man.elc")
   require(man)
   byte-code("\300\301!\210\300\302!\210\303\304\305\306\307\310%\207" [require man button define-button-type WoMan-xref-man-page :supertype Man-abstract-xref-man-page func #f(compiled-function (arg) #<bytecode 0x41469c3f>)] 6)
   require(woman)
   helm-man--init()
   apply(helm-man--init nil)
   helm-apply-functions-from-source(((name . "Manual Pages") (init . helm-man--init) (candidates . helm-candidates-in-buffer) (keymap keymap (tab . helm-execute-persistent-action) (2 . backward-word) (18 . evil-paste-from-register) (21 $
   helm-compute-attr-in-sources(init (((name . "Manual Pages") (init . helm-man--init) (candidates . helm-candidates-in-buffer) (keymap keymap (tab . helm-execute-persistent-action) (2 . backward-word) (18 . evil-paste-from-register) (2$
   helm-initial-setup(nil (((name . "Manual Pages") (init . helm-man--init) (candidates . helm-candidates-in-buffer) (keymap keymap (tab . helm-execute-persistent-action) (2 . backward-word) (18 . evil-paste-from-register) (21 . helm-de$
   helm-initialize(nil nil nil helm-source-man-pages)
   helm-internal(helm-source-man-pages nil nil nil nil "*helm man woman*" nil nil nil)
   apply(helm-internal (helm-source-man-pages nil nil nil nil "*helm man woman*" nil nil nil))
   helm(helm-source-man-pages nil nil nil nil "*helm man woman*" nil nil nil)
   apply(helm (helm-source-man-pages nil nil nil nil "*helm man woman*" nil nil nil))
   helm(:sources helm-source-man-pages :buffer "*helm man woman*")

**Comment by hlissner** [comment]
[This](https://github.com/hlissner/doom-emacs/blob/develop/modules/config/default/+bindings.el#L834-L835) appears to be the cause, but it shouldn't run unless `:feature (evil +everywhere)` is enabled.

Have you byte-compiled your config (with `bin/doom compile`)? If so, run `bin/doom clean`.

**Comment by verminniu** [comment]
thanks for reply

I run **bin/doom clean**, and update **~/.emacs.d** to the last version of the develop branch,  and not solved

and my +bindings.el is 
```
(setq persp-keymap-prefix (kbd "C-c e")
      projectile-keymap-prefix (kbd "C-c p"))

(map!
   "C-v"              #'scroll-up-command
)
```

**Comment by hlissner** [comment]
Are you still experiencing this issue?

**Comment by verminniu** [comment]
thanks，it's ok now
