### ISSUE TITLE
Switch workspace buffer broken (SPC b b)

### ISSUE THREAD

**Issue by danielmt** [hlissner/doom-emacs#986]
### Observed behavior

Using `SPC b b` to switch workspace buffers is broken, yields: `Invalid function: "B"`

### Expected behavior

When using `SPC b b` should reveal a list of all workspace buffers.

### Steps to reproduce

1. Type SPC b b
2. Will get `invalid function: "B"` instead of workspace buffer list

### System information

<details>
<summary>Click to expand</summary>

- OS: darwin (x86_64-apple-darwin18.0.0)
- Emacs: 26.1 (Oct 30, 2018)
- Doom: 2.0.9 (develop 86305f21755f035d368be0320a85cc4577a05748)
- Graphic display: t (daemon: nil)
- System features: NOTIFY ACL LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS LCMS2
- Details:
  ```elisp
  elc count: 29
  uname -a:  Darwin kusanagi 18.0.0 Darwin Kernel Version 18.0.0: Wed Aug 22 20:13:40 PDT 2018; root:xnu-4903.201.2~1/RELEASE_X86_64 x86_64 i386 MacBookPro14,3 Darwin
  modules:   (:feature eval (evil +everywhere) (lookup +docsets) snippets (syntax-checker +childframe) workspaces :completion company (helm +fuzzy) :ui deft doom doom-dashboard doom-modeline doom-quit evil-goggles hl-todo nav-flash treemacs (popup +all +defaults) vc-gutter vi-tilde-fringe window-select :editor multiple-cursors rotate-text :emacs dired ediff electric hideshow imenu vc :tools docker editorconfig macos magit :lang cc data emacs-lisp go javascript markdown org python rest rust sh web :private personal js web gtd :config default)
  packages:  (flycheck-flow prettier-js)
  exec-path: (/bin/mac/ /usr/local/opt/python/libexec/bin/ /usr/local/opt/coreutils/libexec/gnubin/ /usr/local/opt/gnu-sed/libexec/gnubin/ /usr/local/opt/sqlite/bin/ ~/bin/ ~/.local/bin/ ~/go/bin/ /usr/local/bin/ /usr/local/sbin/ /usr/local/bin/ /usr/bin/ /bin/ /usr/sbin/ /sbin/ ~/.nvm/versions/node/v8.11.4/bin/ ~/bin/mac/ /usr/local/opt/python/libexec/bin/ /usr/local/opt/coreutils/libexec/gnubin/ /usr/local/opt/gnu-sed/libexec/gnubin/ /usr/local/opt/sqlite/bin/ ~/bin/ ~/.local/bin/ ~/go/bin/ /usr/local/sbin/ /usr/local/Cellar/emacs-mac/emacs-26.1-z-mac-7.3/libexec/emacs/26.1/x86_64-apple-darwin18.0.0/)
  ```
</details>

**Comment by triklsbg** [comment]
Proposal from Henrik (Discord): You can try getting around it by running `bin/doom compile :plugins`

**Comment by danielmt** [comment]
> Proposal from Henrik (Discord): You can try getting around it by running `bin/doom compile :plugins`

Worked fine!
