### ISSUE TITLE
Enhance the visual separation between helm-command and helpfull buffer

### ISSUE THREAD

**Issue by triklsbg** [hlissner/doom-emacs#988]
### Observed behavior
nearly invisible small black (dark-grey) line on a grey background
### Expected behavior
line with more contrast or perhaps a text-line or a contrasting background of the helpful buffer
### Steps to reproduce
select a command in helm-command window and press TAB
### System information

![doom miss visual sep_20181031_114332](https://user-images.githubusercontent.com/3647083/47783877-2a0e7b80-dd04-11e8-8ee6-06bc58a4b817.png)

**Comment by hlissner** [comment]
As far as I know, there is no way to make only that divider thicker. You can make all bottom-window dividers however. These are the defaults ([source](https://github.com/hlissner/doom-emacs/blob/develop/core/core-ui.el#L228-L233)):

```elisp
(setq-default window-divider-default-places t
              window-divider-default-bottom-width 1
              window-divider-default-right-width 1)
(add-hook 'doom-init-ui-hook #'window-divider-mode)
```

e.g. Add `(setq window-divider-default-bottom-width 2)` to your private config.
