### ISSUE TITLE
goto definition broken

### ISSUE THREAD

**Issue by azy2** [hlissner/doom-emacs#989]
Goto definition is broken for me. Hitting `C-]` in any language (I've tried C++, python, and elisp) prints this to the console and does nothing:
```
(fn STRING PRED ACTION)] nil f nil nil nil helm-comp-read-get-candidates  helm-cr-default helm-pattern] 6]’ 
 (user-error "No recursive edit is in progress")
Aborting an helm session running in background
In ‘xref-find-definitions’ source: ‘#[0 \306\300\301\304\305\303\203
\0\307\202\0	%\310\302"\207 [#[771 r\300q\210\212\302\303 \210)\304\305\300!$*\207 [test.py enable-recursive-minibuffers t visit-tags-table-buffer complete-with-action tags-completion-table] 8 
```

I've tried deleting the entire .local directory and running `make install` over again. But it did not fix it.

<details>
```
- OS: gnu/linux (x86_64-pc-linux-gnu)
- Emacs: 26.1 (May 29, 2018)
- Doom: 2.0.9 (develop 4063b8d14abb365c975fd29ce7fd3b08210d32a1)
- Graphic display: t (daemon: nil)
- System features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS XWIDGETS LIBSYSTEMD LCMS2
- Details:
  ```elisp
  elc count: 0
  uname -a:  Linux ben-XPS-13-9360 4.15.0-36-generic #39-Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
  modules:   (:feature eval (evil +everywhere) file-templates (lookup +docsets) snippets spellcheck (syntax-checker +childframe) workspaces :completion company (helm +fuzzy) :ui doom doom-dashboard doom-modeline doom-quit evil-goggles fci hl-todo nav-flash treemacs (popup +all +defaults) vc-gutter vi-tilde-fringe window-select :editor format multiple-cursors rotate-text :emacs dired ediff electric hideshow imenu term vc :tools editorconfig magit pdf rgb :lang assembly (cc +irony +rtags) data emacs-lisp go javascript (latex +okular +latexmk) markdown (org +attach +babel +capture +export +present) (sh +fish) web :config default)
  packages:  (exec-path-from-shell)
  exec-path: (/usr/local/bin/ /usr/local/sbin/ ~/bin/ ~/go/bin/ ~/.local/bin/ /usr/sbin/ /usr/bin/ /sbin/ /bin/ /usr/games/ /usr/local/games/ /snap/bin/ /usr/lib/x86_64-linux-gnu/emacs/26.1/x86_64-linux-gnu/)
  ```
```
</details>

**Comment by hlissner** [comment]
I cannot reproduce this. `C-]` is bound to `projectile-find-tag`, so this doesn't seem like a Doom issue.

1. Does `gd` work for you? This uses `+lookup/definition`, which is much more sophisticated.
2. Try `bin/doom compile :plugins` and see if your issue goes away.
3. Can you provide a backtrace of this error? `M-x toggle-debug-on-error` and then recreate the error.

**Comment by azy2** [comment]
Hmmmm, it sounds like my best option is to just rebind `C-]` to `+looup/definition`. Thanks.

**Comment by azy2** [comment]
I have a new problem. `+lookup/definition` works for elisp but when I try to use it in my C++ project it doesn't do anything. Well, that's not quite true. My cursor doesn't move but the cursor stack changes. If I hit `gd` followed by a `C-o` I end up at the definition. Is that a problem with doom or rtags?

**Comment by hlissner** [comment]
That's a problem with Doom. I'll look into a solution when I get the chance.

**Comment by hlissner** [comment]
Are you still experiencing this issue? There have been a few recent changes to the lookup module, including a rewrite of the lookup commands.

**Comment by hlissner** [comment]
I will assume this issue has been resolved. Feel free to follow up here if that isn't the case.
