### ISSUE TITLE
Elixir auto-complete inside parentheses does not work

### ISSUE THREAD

**Issue by nresni** [hlissner/doom-emacs#991]
Hi,

I don't know if it's doom-emacs or Alchemist.

### Observed behavior

When I try to auto-complete a term which is just before a closing parenthesis, I have no result.

I have to put a space between my term and the closing parenthesis for it to work.

```ruby
function(Enum.|)  #C-SPC does not work
function(Enum.| ) #C-SPC works
```

![2018-10-31_536x367_escrotum](https://user-images.githubusercontent.com/504562/47787657-da35b180-dd0f-11e8-95e1-931ee8887012.png)

### Expected behavior

Open auto-complete

![2018-10-31_395x372_escrotum](https://user-images.githubusercontent.com/504562/47787680-e91c6400-dd0f-11e8-9c47-883f398b007d.png)
 
Thks in advance

**Comment by hlissner** [comment]
This does seem like an alchemist issue, but to be sure, try to reproduce this in vanilla Emacs. You can do so with `SPC h E` (`doom/open-vanilla-sandbox`) with the following code:

```elisp
(require 'company)
(setq company-idle-delay nil
      company-require-match 'never)
(define-key company-mode-map (kbd "C-SPC") #'company-manual-begin)
(require 'elixir-mode)
(require 'alchemist-company)

;; If you want evil-mode you can include this
(require 'evil)
(evil-mode +1)
(evil-define-key* 'insert company-mode-map (kbd "C-SPC") #'company-manual-begin)
;;;;;;;;

(with-current-buffer (switch-to-buffer "*elixir-test*")
  (elixir-mode)
  (company-mode)
  (setq-local company-backends '(alchemist-company company-yasnippet))
  (insert "my_func(Enum.")
  (save-excursion (insert ")")))
```

Then press C-c C-c to start the vanilla emacs session, and press C-SPC, and see if you have the same trouble.

**Comment by nresni** [comment]
I have the same trouble on vanilla-sandbox.
