### ISSUE TITLE
feature request: fallback to `neotree-toggle` in `+neotree/open` and `+neotree/find-this-file`

### ISSUE THREAD

**Issue by PoiScript** [hlissner/doom-emacs#992]
Neotree doesn't popup correctly, when I'm editing an non-project file, like `~/.doom.d/init.el`. The problem is the variable [`doom-project-root`](https://github.com/hlissner/doom-emacs/blob/develop/modules/ui/neotree/autoload.el#L11) is unset. It will be great that `+neotree/open` and `+neotree/find-this-file` can fallback to the `neotree-toggle` function when `doom-project-root` is nil.

**Comment by hlissner** [comment]
As of 8085a55 this should be fixed. I had simply forgotten to update the ui/neotree module after a recent (and big) change in projectile. Let me know if that isn't the case and I'll reopen this.
