### ISSUE TITLE
Multiple instances of emacs[NOT A BUG]

### ISSUE THREAD

**Issue by jbharat** [hlissner/doom-emacs#999]
This is not a bug. I am creating this issue to have a better understanding of this issue.

I like fast launching of emacs. I have been using spacemacs for a long time and recently switched to doom. Great work in keeping stuff simple, minimal and fast 👍 

I am using mac(mojave) and doom develop branch.

I always use separate instances of emacs for each project.

If I type `code .` in multiple projects, it creates multiple instances of vscode for each project and I can switch between them using cmd+\`. 

If I type `emacs &` in the same way as above in multiple projects, I cannot switch between emacs instances using cmd+\`. cmd+tab works but cmd+\` doesn't. 

This seems to be an issue of Emacs itself. I am posting this here to discuss if this is really a bug of emacs and if we can somehow get around this.

**Comment by jbharat** [comment]
I tried playing with emacsclient. You are right. `cmd+\`` works with frames. So they have to be from the same instance of emacs for fast switching.

I have the below code block for emacs

```
function startEmacs() {
 if [ -z "$1" ]
  then
   emacsclient -c -n  
 else
  emacsclient -c -n $1
 fi
}

alias e=startEmacs
```
I found something that seems to be a bug. 
Let say I have two projects projA and projB. 
If I run `e` in projA, it opens a frame and then on pressing SPC SPC, I can see all the files of projA in projectile. 
Now if I run `e` in projB, it opens a frame and then on pressing SPC SPC, I should see files of projB, but I see files of projA which seems to be a bug.

This does not happen if I open a specific file using `e package.json`. This loads the correct files in projectile.

**Comment by qleguennec** [comment]
What is `e`?

**Comment by jbharat** [comment]
All sorted. Using emacs in daemon mode and emacsclient. The issue mentioned https://github.com/hlissner/doom-emacs/issues/999#issuecomment-436117131 was caused by workspace module. Disabled it and now frames are working as expected. 

- I am able to switch between emacs frames using cmd+`(because of frames)
- Frames load the correct project files(disabled workspace module for this)
